### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'round'

### ISSUE THREAD

**Issue by thmeta** [freqtrade/freqtrade#10008]
## Describe your environment

  * Operating system: Win10
  * Python Version: 3.11.3 (`python -V`)
  * CCXT version: 4.2.82 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.3-dev-82a9bdca5, 2024.3-dev-06c4431c3 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Inconsistent behavior in backtesting

### Steps to reproduce:

  1. Run trade in dry mode
  2. Run backtesting with the same strategy
  
### Observed Results:

  * What happened? Trade in dry mode goes fine while the same strategy outputs fatal exception in backtesting
  * What did you expect to happen? Both trade and backtesting work with the strategy

### Relevant code exceptions or logs

2024-03-27 10:08:15,399 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "D:\freqtrade\freqtrade\main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "D:\freqtrade\freqtrade\commands\optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "D:\freqtrade\freqtrade\optimize\backtesting.py", line 1405, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\freqtrade\freqtrade\optimize\backtesting.py", line 1322, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\freqtrade\freqtrade\strategy\interface.py", line 1378, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\freqtrade\freqtrade\strategy\interface.py", line 1378, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\freqtrade\freqtrade\strategy\interface.py", line 1410, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\freqtrade\user_data\strategies\QuickAdapterV58.py", line 417, in populate_indicators
    informative_15m[f'EMA{length}'] = pta.ema(informative_15m['close'], length=length).round(5)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'round'
PS D:\freqtrade>

**Comment by xmatthias** [comment]
you can't use `.round()` like this. what you get out of an indicator function is a pandas Series - which will usually have empty values - so round may fail.

Now in pta's case, I'm not even sure if it returns a series directly, or if it's instead assigning the dataframe - but that's because i usually use ta-lib, not pandas-ta. For support with individual indicator libraries, best get in touch through their dedicated support channels.

At any rate, it's not a problem we will be able to fix, as it's not a freqtrade problem.
It's your strategy that causes the error.

**Comment by froggleston** [comment]
round() is supported on Series objects, and as far as I know pandas-ta does return Series objects. I get the feeling this is something to do with how the data in the informative might be presented (in pandas-ta if your input data is None, then your output data will be None). You could try doing it longhand to make sure the series exists to round on:

```
e = pta.ema(informative_15m['close'], length=length)
if e:
  informative_15m[f'EMA{length}'] = e.round(5)
```

**Comment by thmeta** [comment]
> you can't use `.round()` like this. what you get out of an indicator function is a pandas Series - which will usually have empty values - so round may fail.
> 
> Now in pta's case, I'm not even sure if it returns a series directly, or if it's instead assigning the dataframe - but that's because i usually use ta-lib, not pandas-ta. For support with individual indicator libraries, best get in touch through their dedicated support channels.
> 
> At any rate, it's not a problem we will be able to fix, as it's not a freqtrade problem. It's your strategy that causes the error.

What I really meant here, is why it works in dry but not in backtesting?

**Comment by froggleston** [comment]
This might be because all your values are NaN in your informative dataframe as your startup_candle_count is insufficient? Hard to say really.

**Comment by xmatthias** [comment]
Closing this as we've had no further feedback.
