### ISSUE TITLE
Add `max_value` field for VolumePair list

### ISSUE THREAD

**Issue by stevanStevic** [freqtrade/freqtrade#10009]
## Describe the enhancement

Similar to `min_value` we have for [VolumePair list](https://www.freqtrade.io/en/stable/plugins/#volume-pair-list) I would like to add `max_value` to have upper limit on volume in which bot can trade.

**Comment by xmatthias** [comment]
Sounds like a good first issue ... should be pretty simple to do - and scope is very limited.

**Comment by ststevic** [comment]
> Sounds like a good first issue ... should be pretty simple to do - and scope is very limited.

I'll add it 👍 Wanted to check if okay with you!

**Comment by xmatthias** [comment]
well, no worries, this is what i'd usually consider a simple enhancement :+1:
