### ISSUE TITLE
Bot fails to load custom config path with download-data

### ISSUE THREAD

**Issue by harindersinghk** [freqtrade/freqtrade#10012]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.11.6
  * CCXT version: using freqtrade docker latest pull
  * Freqtrade Version: freqtrade 2024.2
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Fails to load custom config file when using command `sudo docker compose run --rm freqtrade download-data  --config ~/ft_userdata/user_data/custom_config.json --timerange 20240101-20240327 --datadir user_data/data/file`

### Steps to reproduce:

  1. Install using docker
  2. sudo docker compose up -d
  3. run `sudo docker compose run --rm freqtrade download-data  --config ~/ft_userdata/user_data/custom_config.json --timerange 20240101-20240327 --datadir user_data/data/file`

  
### Observed Results:

  * What happened? 
  * Doesn't load custom config but works if no config is provided (works for default config)
 
  * What did you expect to happen?
  * Load custom config

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2024-03-28 13:53:22,038 - freqtrade - INFO - freqtrade 2024.2
2024-03-28 13:53:22,039 - freqtrade.configuration.load_config - INFO - Using config: /home/user/ft_userdata/user_data/custom_config.json ...
2024-03-28 13:53:22,039 - freqtrade - ERROR - Config file "/home/user/ft_userdata/user_data/custom_config.json" not found! Please create a config file or check whether it exists.

  ```

**Comment by stash86** [comment]
Because that is a wrong way of defining the path.

Try --config user_data/custom_config.json

**Comment by xmatthias** [comment]
To explain the reason: The command you pass in is executed within the docker container - hence needs to refer to the path within the container.

`~/ft_userdata/user_data/custom_config.json ` (probably) refers to the path outside of the container ... but that's not available under the same name within the container.

**Comment by harindersinghk** [comment]
Ahh i see. My apologies for the oversight and thanks

**Comment by harindersinghk** [comment]
closing issue
