### ISSUE TITLE
Reinforcement Learner GPU support

### ISSUE THREAD

**Issue by mert-donmez** [freqtrade/freqtrade#10017]
## Describe your environment

  * Operating system: 
  * Python Version:  Python 3.12.2
  * CCXT version:  4.2.82 
  * Freqtrade Version: 2024.3-dev-82a9bdca5, 2024.3-dev-06c4431c3
  
## Your question

Hi,

Based on what I've seen in the freqai documentation, it appears that in the parameter table section, specifying 'task_type' or 'device' allows for the activation of GPU support during the training of models. However, in the parameter table section for the Reinforcement Learner model, 'cpu_count' is mentioned, but there is no information related to GPU support. 
Is GPU support irrelevant to the training of the Reinforcement Learner model, or is such information simply not provided?

Thanks.

**Comment by robcaulk** [comment]
Hello,

GPU is activated by default when you run reinforcement learning in FreqAI.

thank you,

rob

**Comment by mert-donmez** [comment]
Hi robcaulk,

GPU usage during an RL training looks like this:
```
GPU 0
	Intel(R) UHD Graphics 630
	Driver version:	27.20.100.8729
	Driver date:	10/12/2020
	DirectX version:	12 (FL 12.1)
	Physical location:	PCI bus 0, device 2, function 0
	Utilization	5%
	Dedicated GPU memory	
	Shared GPU memory	0.9/7.9 GB
	GPU Memory	0.9/7.9 GB
```
```
GPU 1
	NVIDIA GeForce GTX 1050 Ti
	Driver version:	31.0.15.5152
	Driver date:	2/7/2024
	DirectX version:	12 (FL 12.1)
	Physical location:	PCI bus 1, device 0, function 0
	Utilization	0%
	Dedicated GPU memory	0.0/4.0 GB
	Shared GPU memory	0.0/7.9 GB
	GPU Memory	0.0/11.9 GB
```
The GPU usage seems very low, almost as if it's not being used. I was expecting the GPU usage to be 100% just like the CPU usage, because normally training takes a very long time. Is my expectation wrong?

**Comment by robcaulk** [comment]
Hello,

It is common for newcomers to expect the GPU to be active 100% all the time. But these people are unfamiliar with the RL algoritthm. Here, I will try to help you, but please do spend some time at the link below.

In RL, GPU is used for the forward and backward passes through your neural network.

There are about 8 other steps involved in reinforcement learning, and many of these steps depend on the output from previous steps, which means that they are inherently sequential. There are more FreqAI steps involved in general data pre and post-processing before and after your training.

Have a look at how RL works: https://towardsdatascience.com/reinforcement-learning-101-e24b50e1d292

Cheers,

Rob
