### ISSUE TITLE
Add lock [pair] in rest API

### ISSUE THREAD

**Issue by eltech35** [freqtrade/freqtrade#10018]
## Describe the enhancement
Add action: lock [pair] in rest API so we can remotely lock a specific pair
(Could we also specify a lock reason/comment ?) 

When a coin symbol becomes "inactive" on exchange for diverse reasons:
- hack
- chain split
- suspended by authorities
- whatever exchange reason (maintenance... etc)

It could go to blacklist but if it last only ... 2h by exemple, better just lock it no ?
If we had a lock [pair] like blacklist [pair] already works, would be great.

**Comment by xmatthias** [comment]
I don't understand what you mean with "hack". who is it that's hacked?  the exchange? coin? you?

Aside from that - you should probably be using blacklist for most of these.
If pair is delisted ... it must be blacklisted to be permanently removed from the pairlist (locked pairs will still have their data updated - they just don't enter new positions).

That same thing really applies to all other scenarios you mention, too - where you'd want the pair to be gone from the pairlist - not keep in the pairlist, having it's data updated, just preventing entries should they occur.

chain split can in theory be justified to some degree - but you'll still want to be careful with that, too - a chain split often has a price-jump builtin ... which can mess up indicator calculations pretty good (having them trigger while they shouldn't) - so a permanent blacklist (with a manual check afterwards) will be a must in this case almost certainly.


---

Initially - i wanted to treat it as enhancement - but thinking about it - i  fail to see the usecase - the scenarios you mention are better accomplished via blacklisting the pair (obviously you'll want to remove them from the whitelist later - but the same applies for a lock - which would require an expiration date).

**Comment by eltech35** [comment]
I specified lock because, don't u need to restart the strat / read config file again so the blacklist applies ?
Vs locks a strategy rule can set or unset without restarting the bot/strat ?
Am i wrong ?

**Comment by xmatthias** [comment]
yes you're wrong.

Blacklist (added via /blacklist RPC endpoints) is applied immediately - but it "disappears" after a reload/restart (it's not persisted).

**Comment by eltech35** [comment]
k

**Comment by xmatthias** [comment]
What you didn't see is that i've created a PR for this same feature ;)
