### ISSUE TITLE
Actions Menu + Manual Actions

### ISSUE THREAD

**Issue by mohamed95ivy** [freqtrade/freqtrade#10020]
Hello, 
I would like to adjust the Trade. I can adjust it by selling "force_exit_limit" and "force_exit_market".. But there is no Possibility to "buy" and that's important for DCA to limit and minimize the loss. I did take care of that in the function "adjust_trade_position". But, sometimes there is a need for a manual adjustment. 

I am a C# Dev but a newbie in Python. If someone directs me to the point, I would like to develop it.

**Comment by xmatthias** [comment]
The functionality is there - just not in the Actions menu (though we can probably add it there without much effort).

You can simply use "force-entry" again on that pair - obviously this assumes that force entries are enabled in the backend (otherwise you'll not have this button at all).
