### ISSUE TITLE
custom_stake_amount NOTIONAL Exception

### ISSUE THREAD

**Issue by vilipwong** [freqtrade/freqtrade#10026]
## Describe your environment

  * Operating system: AMZ Linux
  * Python Version: FROM freqtradeorg/freqtrade:stable (`python -V`)
  * CCXT version: 4.2.51 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.2 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

1. I have looked at [stake size management](https://www.freqtrade.io/en/stable/strategy-callbacks/#stake-size-management), it stated that `Freqtrade will fall back to the proposed_stake value should your code raise an exception. The exception itself will be logged.`. When i run in Binance exchange in live mode, occasionally i am getting `freqtrade.exceptions.OperationalException: binance {"code":-1013,"msg":"Filter failure: NOTIONAL"}` and the bot will stop and will not fallback to use `proposed_stake`

my code: 
```
def custom_stake_amount(self, pair: str, current_time: datetime, current_rate: float,
                            proposed_stake: float, min_stake: Optional[float], max_stake: float,
                            leverage: float, entry_tag: Optional[str], side: str,
                            **kwargs) -> float:
        t = proposed_stake / self.dca_limit.value
        # logging.info(f"[DEBUG] stake {t} ,min_stake: {min_stake}, proposed_stake: {proposed_stake}, current_rate: {current_rate}, leverage: {leverage}, max_stake: {max_stake} ")
        if t < min_stake:
            return min_stake
        return t
```
Log:
```
freqtrade1  | 2024-03-31 13:09:53,328 - root - INFO - [DEBUG] stake 5.265289433999999 ,min_stake: 5.25, proposed_stake: 26.326447169999994, current_rate: 6.686, leverage: 1.0, max_stake: 26.326447169999994 
freqtrade1  | 2024-03-31 13:09:53,330 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for ETHFI/USDT with stake_amount: 5.265289433999999 ...
freqtrade1  | 2024-03-31 13:09:53,545 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exception, 'status': '*OperationalException:*\n```\nTraceback (most recent call last):\n 
```
2. so based on the log the stake amount is higher than min stake, but exception still thrown, is the `min_stake` value accurate? or `current_rate` is the one i should be looking at ?

**Comment by xmatthias** [comment]
The comment on the callback refers to errors that the strategy issues. the error doesn't appear to come from there - but without complete logs, it's a waste of time to look at this further.

As an aside - on binance, I'd say that stakes below 15$ are usually not a good idea, as you'll usually struggle to place a stoploss below that (aside from the fact that a position of 5$ will not make much wins).

Going very close to the limit is problematic, as it can cause rounding issues.
Your stake at 5.25$ will cause a position of < 1 ETHFI.
Binance's limits menton a minimum limit of 0.1ETHFI as tradable - but at the same time, the precision is 1 ... so you can only buy full ETHFI - but not 0.5 or 1.5 ETHFI.

At a current price of >6$ - your amount will be 0 after applying the precision.
The limits binance reports here are a bit odd - as you can trade 0.1 ETHFI - but you can't trade <1 ETHFI) - and are a sign that they didn't expect price to be this high (Limits will most likely be adjusted at some point).
