### ISSUE TITLE
Feature: MEXC Support

### ISSUE THREAD

**Issue by FungY911** [freqtrade/freqtrade#10035]

**Comment by xmatthias** [comment]
We'll not be adding support for mexc.

I've looked at this exchange in the past with the aim of adding it to freqtrade as supported exchange - but it has some very odd / shady practices - like having major pairs disabled from trading through the API for months/years - while orderbook movements clearly show that other players ARE trading via API (most likely it's internal trading against their customers).

As such - this is not something we'll consider - at least not until these practices are both explained (why was BTC/USDT trading disabled for over a year) - and stop. Best contact mexc support for this - maybe if enough users question this it'll change their behavior.

Until then - please use one of the supported exchanges instead.
