### ISSUE TITLE
Bitpanda supported now?

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#10039]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.3 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

According to a past github post, with your answer, I read, that Bitpanda is not supported.
But now, I just discovered, that in the subfolder freqtrade\exchange, a file named bitpanda.py is present.
the 2nd comment in the file contains ". . .Contains adjustments needed for Freqtrade to work with this exchange".
Does that mean, that this exchange is now supported?
If yes: Only for crypto currencies, or even for stocks and ETFs?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by froggleston** [comment]
Freqtrade only uses CCXT to trade crypto, not stocks or ETFs. As for bitpanda, it's not a formally supported exchange so I presume the implementation is still in development.

**Comment by myNextCoder** [comment]
I understand, so a tokenization of these assets, like it was the case on FTX with the tokenized stocks, would be necessary.

**Comment by xmatthias** [comment]
Officially Supported exchanges are listed on the repository's readme page (the home page for the repository) - as well as on the front page of the [documentation](https://www.freqtrade.io/en/stable/).

Bitpanda is not one of these - so you're most likely the first to try (at least recently).

In theory, freqtrade supports every exchange ccxt supports, which would also include this exchange.

Now ccxt doesn't seem to support bitpanda at first glance - though in reality it seems to have renamed to onetrading (https://github.com/ccxt/ccxt/issues/20629).


Now having an adjustment file is _often_ a good step - but it doesn't mean we'll actively support this exchange. It just means someone looked at that exchange at some time in the past - and did some minor adjustments.

I know from the past that others have had success with bitpanda (or an exchange with a similar name ...) using it for crypto - but we don't actively test this exchange, and don't plan to do so, either.
If ccxt supports it for trading non-crypto - i can't tell - often ccxt has aliases in place - freqtrade won't necessarily limit this - depending on what the output from ccxt will be.


If you encounter specific problems, we're happy to assist _up to a certain point_ - but the expectation for new exchanges is that the user interested is doing the legwork / most of the testing work - which also assumes a somewhat familiarity with python / testing/debugging things in python.

If you're new to python / development - you're almost certainly better of with one of the supported exchanges.

**Comment by myNextCoder** [comment]
I thank you for your detailed answer. Before testing Bitpanda / Onetrading, I would need to have a deep dive of ccxt. Generally it seems, that beside of the other numerous exchanges, not 100% supported by Freqtrade, one might discover profitable opportunities, by testing all those ones.

**Comment by xmatthias** [comment]
i'm not sure why a different exchange would give you more profitable opportunities.
what should make your profitable or not should be your strategy - the exchange is just a tool to accomplish that.
The selection of these should include properties like 
* is it available in my country
* what requirements in regards to KYC does it have
* **do you trust it to handle your money** (highlighted, as this is where most exchanges will fail you)
*  does it offer markets i'd like to trade.

Sure, not all exchanges will behave identically in detail on the same strategy (you can't transfer strategies between exchanges) - but picking an exchange that's not even ranked on coinmarketcap / coingecko is NOT going to be the way for "profitable opportunities".

**Comment by stash86** [comment]
To give an example of why you shouldn't choose any random exchange

https://botacademy.ddns.net/2023/11/11/why-volume-matters/

Top ranked exchanges usually will have more trading volumes, which means you won't have such issue. Of course within the exchange, not all pairs gonna have big volume, but it's easily filterable using the volume pairlist. But if the exchange as a whole has very low volume, your rate of success is very very very low

**Comment by myNextCoder** [comment]
Yes absolutely, choosing a rather unknown exchange, instead of a top ranked one, won't give me more cash at the bottom line, in the contrary, I guess. My only reason of testing additional exchanges, which are not yet officially supported, is to "decentralize my capital", as having multiple bots, running on one exchange (dry bots / live bots). In addition, a reason may be the security (FTX). The four points, of choosing the right exchange, you gave me, are important ones. The way of testing the volume, is a clever idea, not to have bad trades. I may use the new market cap pairfilter, so using tokens only among the 100 top ones, should give me a good security.
