### ISSUE TITLE
Stop loss set to $40 ignored - took $499 dollar hit. 

### ISSUE THREAD

**Issue by creslinux** [freqtrade/freqtrade#1003]
Setting stop under $7200($7198) , to cap loss to $40 is ignored.
Actual trade realised $499 loss.

Stop-loss is not stoping loss to the calculated value. 
2hr candles BTC.

```
2018-07-08 19:22:55,545 - freqtrade.persistence - DEBUG - None - current price 7235.10000000, 
bought at 7235.10000000 and calculated stop loss is at: 7198.92450000 initial stop at 7198.92450000. 
trailing stop loss saved us: 0.00000000 and max observed rate was 7235.10000000
2018-07-08 19:22:55,546 - freqtrade.analyze - DEBUG - Stop loss hit.
2018-07-08 19:22:55,551 - freqtrade.optimize.backtesting - INFO - Dumping backtest results to btc.json
dumping json to "btc.json"
2018-07-08 19:22:55,568 - freqtrade.optimize.backtesting - INFO - 
======================================== BACKTESTING REPORT =========================================
| pair     |   buy count |   avg profit % |   total profit USDT |   avg duration |   profit |   loss |
|:---------|------------:|---------------:|--------------------:|---------------:|---------:|-------:|
| BTC/USDT |           1 |          -6.90 |         -0.06913137 |          360.0 |        0 |      1 |
| TOTAL    |           1 |          -6.90 |         -0.06913137 |          360.0 |        0 |      1 |
2018-07-08 19:22:55,577 - freqtrade.optimize.backtesting - INFO - 


```

**Comment by creslinux** [comment]
Ive tested this same scenario in Trading view, the stop was triggered at $7198.

**Comment by xmatthias** [comment]
how is this different to #985?
your logs indicate this happened during backtest, too...

**Comment by creslinux** [comment]
985 was a couple of issues on deeper consideration, and primarily drifted toward using the low of the candle to trigger the stop mid timeframe; also what if there was also an upward wick to touch ROI. 
 
This is a more common, single, and clean scenario where a market moves in a single direction, the close itself is beyond the stop level.

**Comment by creslinux** [comment]
<img width="1117" alt="screen shot 2018-07-09 at 8 39 43 am" src="https://user-images.githubusercontent.com/34645187/42440016-f09c7bd6-8353-11e8-9b84-784b6b13c165.png">

**Comment by creslinux** [comment]
Suggested testable requirements 
<img width="779" alt="screen shot 2018-07-09 at 1 56 34 pm" src="https://user-images.githubusercontent.com/34645187/42454784-ecad947a-837f-11e8-81da-9bb0a0597eb1.png">

**Comment by creslinux** [comment]
Document with candle data to create the fail scenarios. 
For xmatthias functional test harness

[BT_Fails.docx](https://github.com/freqtrade/freqtrade/files/2178219/BT_Fails.docx)

**Comment by xmatthias** [comment]
even though it's technically a bug, i'll keep it as enhancement too - as it's a ... bigger thing i'm working on ...

**Comment by xmatthias** [comment]
i think the following branch should fix the problematic scenarios outlined above.
https://github.com/xmatthias/freqtrade/tree/feat/functional_tests

due to buy-signal shift (avoiding look-ahead in backtest) i had to add a "empty" candle at the beginning of each test-case.

would be great if @creslinux could give this a look when time permits, so i know if it fixes the outlined problems - and i can get to try and adapt this into "usable" code.

**Comment by xmatthias** [comment]
these tests have been covered with #1306, therefore closing.
If you don't think #1306 resolves this or discover a bug feel free to reopen (or open a new issue).

@creslinux Thanks for investigating this so thorough and developing the test-cases
