### ISSUE TITLE
update image get TypeError: void() takes at least 1 positional argument (0 given) error

### ISSUE THREAD

**Issue by ssssi** [freqtrade/freqtrade#10036]
## Describe your environment

  * Operating system: linux
  * Python Version: ___3.12__ (`python -V`)
  * CCXT version: i use docker
  * Freqtrade Version:freqtrade docker-2024.4-dev-7bb6c5e7
  
## Your question
I updated  image today, but this error was reported after startup

```
2024-04-01 15:42:02,326 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2024-04-01 15:42:03,011 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-04-01 15:42:03,011 - telegram.ext.Application - INFO - Application.stop() complete
2024-04-01 15:42:03,012 - freqtrade.rpc.telegram - WARNING - Telegram NetworkError: httpx.ReadError: ! Trying one more time.
2024-04-01 15:42:03,013 - freqtrade.rpc.telegram - WARNING - TelegramError: Unknown error in HTTP implementation: RuntimeError('This HTTPXRequest is not initialized!')! Giving up on that message.
2024-04-01 15:42:11,580 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 75, in run
    state = self._worker(old_state=state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 116, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs,
  File "/freqtrade/freqtrade/worker.py", line 147, in _throttle
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 180, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 247, in process
    self.enter_positions()
  File "/freqtrade/freqtrade/freqtradebot.py", line 530, in enter_positions
    trades_created += self.create_trade(pair)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 560, in create_trade
    (signal, enter_tag) = self.strategy.get_entry_signal(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1087, in get_entry_signal
    latest, latest_date = self.get_latest_candle(pair, timeframe, dataframe)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1019, in get_latest_candle
    latest = dataframe.loc[dataframe['date'] == latest_date].iloc[-1]
             ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/indexing.py", line 1413, in _getitem_axis
    return self._getbool_axis(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/indexing.py", line 1211, in _getbool_axis
    return self.obj._take_with_is_copy(inds, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4150, in _take_with_is_copy
    result = self.take(indices=indices, axis=axis)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4130, in take
    new_data = self._mgr.take(
               ^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 894, in take
    return self.reindex_indexer(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 688, in reindex_indexer
    blk.take_nd(
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 1307, in take_nd
    new_values = algos.take_nd(
                 ^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/array_algos/take.py", line 117, in take_nd
    return _take_nd_ndarray(arr, indexer, axis, fill_value, allow_fill)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/array_algos/take.py", line 133, in _take_nd_ndarray
    dtype, fill_value, mask_info = _take_preprocess_indexer_and_fill_value(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/array_algos/take.py", line 592, in _take_preprocess_indexer_and_fill_value
    dtype, fill_value = arr.dtype, arr.dtype.type()
                                   ^^^^^^^^^^^^^^^^
TypeError: void() takes at least 1 positional argument (0 given)
```

**Comment by xmatthias** [comment]
Using the same exact image - it seems to work just fine.

Now the logs you provided _start_ when it's already in the process of shutting down (the first message is "Cleaning up") - so this is most likely a subsequent problem while shutting down - not the actual problem you're looking at.
more logs ... with what's provided - all i can tell is "works for me".

**Comment by ssssi** [comment]
> Using the same exact image - it seems to work just fine.
> 
> Now the logs you provided _start_ when it's already in the process of shutting down (the first message is "Cleaning up") - so this is most likely a subsequent problem while shutting down - not the actual problem you're looking at. more logs ... with what's provided - all i can tell is "works for me".

It's a problem with my strategy code. Someone from our discord sent me a private message and told me the specific problem.thanks xmatthias

**Comment by xmatthias** [comment]
I've got no idea what  problem in a strategy would cause this (probably something else crashed ...) - but in the end, it's also a report that's lacking the relevant part of the logs - so it's impossible to tell for sure.

**Comment by cnbzmst** [comment]
**Describe your environment**
Operating system: Ubuntu 22.04
Python Version: Python 3.10.12
CCXT version: I use Docker
Freqtrade Version: freqtrade 2024.3 (docker-2024.4)


**Your question**
Hello,

I updated freqtrade with docker compose today and got the same errors opened in this thread. I also used a simple strategy that always works, but the result does not change. Despite my long research, I couldn't figure it out. Then I updated my bot, which was running on the same configurations on another hardware. That system also collapsed.

After updating the packages in Ubuntu, the following warning started to appear.
WARN[0000] /home/ubuntu/freqtrade/ft_userdata/docker-compose.yml: `version` is obsolete
However, I made no changes to the docker-compose.yml file. I don't know if it might be related. I searched but couldn't find a link.

**Log:**
> freqtrade  | 2024-04-05 12:34:28,057 - freqtrade.freqtradebot - INFO - Updating 0 open orders.
freqtrade  | 2024-04-05 12:34:28,403 - telegram.ext.Application - INFO - Application started
freqtrade  | 2024-04-05 12:34:28,589 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
freqtrade  | 2024-04-05 12:34:28,589 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
freqtrade  | 2024-04-05 12:34:28,591 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
freqtrade  | 2024-04-05 12:34:28,595 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "1 open trades active.\n\nHandle these trades manually on Binance, or '/start' the bot again and use '/stopentry' to handle open trades gracefully. \n"}
freqtrade  | 2024-04-05 12:34:28,598 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
freqtrade  | 2024-04-05 12:34:28,598 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
freqtrade  | 2024-04-05 12:34:28,598 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
freqtrade  | 2024-04-05 12:34:28,688 - uvicorn.error - INFO - Shutting down
freqtrade  | 2024-04-05 12:34:28,789 - uvicorn.error - INFO - Waiting for application shutdown.
freqtrade  | 2024-04-05 12:34:28,790 - uvicorn.error - INFO - Application shutdown complete.
freqtrade  | 2024-04-05 12:34:28,790 - uvicorn.error - INFO - Finished server process [1]
freqtrade  | 2024-04-05 12:34:28,791 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
freqtrade  | 2024-04-05 12:34:29,470 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
freqtrade  | 2024-04-05 12:34:29,471 - telegram.ext.Application - INFO - Application.stop() complete
freqtrade  | 2024-04-05 12:34:29,473 - freqtrade.rpc.telegram - WARNING - Telegram NetworkError: httpx.ReadError: ! Trying one more time.
freqtrade  | 2024-04-05 12:34:29,473 - freqtrade.rpc.telegram - WARNING - TelegramError: Unknown error in HTTP implementation: RuntimeError('This HTTPXRequest is not initialized!')! Giving up on that message.
freqtrade  | 2024-04-05 12:34:38,645 - freqtrade - ERROR - Fatal exception!
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/main.py", line 42, in main
freqtrade  |     return_code = args['func'](args)
freqtrade  |                   ^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
freqtrade  |     worker.run()
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 75, in run
freqtrade  |     state = self._worker(old_state=state)
freqtrade  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 116, in _worker
freqtrade  |     self._throttle(func=self._process_running, throttle_secs=self._throttle_secs,
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 147, in _throttle
freqtrade  |     result = func(*args, **kwargs)
freqtrade  |              ^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 180, in _process_running
freqtrade  |     self.freqtrade.process()
freqtrade  |   File "/freqtrade/freqtrade/freqtradebot.py", line 238, in process
freqtrade  |     self.exit_positions(trades)
freqtrade  |   File "/freqtrade/freqtrade/freqtradebot.py", line 1096, in exit_positions
freqtrade  |     if not trade.has_open_orders and trade.is_open and self.handle_trade(trade):
freqtrade  |                                                        ^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/freqtradebot.py", line 1127, in handle_trade
freqtrade  |     (enter, exit_, exit_tag) = self.strategy.get_exit_signal(
freqtrade  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 1052, in get_exit_signal
freqtrade  |     latest, _latest_date = self.get_latest_candle(pair, timeframe, dataframe)
freqtrade  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/strategy/interface.py", line 1019, in get_latest_candle
freqtrade  |     latest = dataframe.loc[dataframe['date'] == latest_date].iloc[-1]
freqtrade  |              ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
freqtrade  |     return self._getitem_axis(maybe_callable, axis=axis)
freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/indexing.py", line 1413, in _getitem_axis
freqtrade  |     return self._getbool_axis(key, axis=axis)
freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/indexing.py", line 1211, in _getbool_axis
freqtrade  |     return self.obj._take_with_is_copy(inds, axis=axis)
freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4150, in _take_with_is_copy
freqtrade  |     result = self.take(indices=indices, axis=axis)
freqtrade  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 4130, in take
freqtrade  |     new_data = self._mgr.take(
freqtrade  |                ^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 894, in take
freqtrade  |     return self.reindex_indexer(
freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 688, in reindex_indexer
freqtrade  |     blk.take_nd(
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 1307, in take_nd
freqtrade  |     new_values = algos.take_nd(
freqtrade  |                  ^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/array_algos/take.py", line 117, in take_nd
freqtrade  |     return _take_nd_ndarray(arr, indexer, axis, fill_value, allow_fill)
freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/array_algos/take.py", line 133, in _take_nd_ndarray
freqtrade  |     dtype, fill_value, mask_info = _take_preprocess_indexer_and_fill_value(
freqtrade  |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/home/ftuser/.local/lib/python3.12/site-packages/pandas/core/array_algos/take.py", line 592, in _take_preprocess_indexer_and_fill_value
freqtrade  |     dtype, fill_value = arr.dtype, arr.dtype.type()
freqtrade  |                                    ^^^^^^^^^^^^^^^^
freqtrade  | TypeError: void() takes at least 1 positional argument (0 given)

**Comment by xmatthias** [comment]
This problem happens if you have an assignment like `dataframe.loc[(), ['exit_long', 'exit_tag']] = (0, 'long_out')`.

I'm not sure this was ever valid syntax when it comes to the docs (I don't find this documented anyplace) - though it probably accidentally worked.
It's no longer working (changed between pandas 2.2.0 and 2.2.1) - proper syntax to assign without condition should be the following: 
`dataframe.loc[:, ['exit_long', 'exit_tag']] = (0, 'long_out')`

I don't even think it's a regression - more like a fix to some odd behavior (which might've had side-effects we've never known).

**Comment by cnbzmst** [comment]
xmatthias thank you very much. 
After following your advice, the problem was resolved.
