### ISSUE TITLE
custom exit price 

### ISSUE THREAD

**Issue by k4pak** [freqtrade/freqtrade#10047]
im working on strategy and i want to use a custom exit price , here is the problem that i have noticed about : when you are using a Function custom exit price and Custom exit which they call them CALLBACKS , in your documentation said that all these functions are runs at on closin candle , but this is not what i am facing . in reality when im coding , custom exit is not implementing on same candle as custim exit price , for example .. i want to use custom exit price on current candle but it makes an order for the next closing candle which i need to use it as a current candle not the next one ... which you have written wrongly on your documentation and the fucntion is not working ....

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

I'm not entirely sure where you got the fact from that a "custom_exit_price" callback would only be executed on candle close - that's not the case - and is also not written in the documentation like this.

custom exit price will be executed whenever an exit order is being placed - in live / dry-run - this can be "whenever". In backtesting, it'll be once per candle - UNLESS you're using `--timeframe-detail` - in which case it can be within a "main" candle - but it'll never be executed more often than once per detail candle.

**Comment by xmatthias** [comment]
Testing this a bit - i really don't see what you mean.

in backtesting, printing in both functions - i get the following output:

```
2024-04-05 19:58:51,786 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2023-01-01 00:00:00 up to 2023-02-01 00:00:00 (3
1 days).                                                                                                                                     
custom_entry_price      BTC/USDT         2023-01-01 01:00:00+00:00                                                                           
custom_exit             BTC/USDT         2023-01-01 04:00:00+00:00                                                                           
custom_exit_price       BTC/USDT         2023-01-01 04:00:00+00:00                                                                           
custom_entry_price      BTC/USDT         2023-01-01 05:00:00+00:00                                                                           
custom_exit             BTC/USDT         2023-01-01 08:00:00+00:00                                                                           
custom_exit_price       BTC/USDT         2023-01-01 08:00:00+00:00                                                                           
custom_entry_price      BTC/USDT         2023-01-01 09:00:00+00:00                                                                           
custom_exit             BTC/USDT         2023-01-01 12:00:00+00:00                                                                           
custom_exit_price       BTC/USDT         2023-01-01 12:00:00+00:00
custom_entry_price      BTC/USDT         2023-01-01 13:00:00+00:00                                                                           
custom_exit             BTC/USDT         2023-01-01 16:00:00+00:00
custom_exit_price       BTC/USDT         2023-01-01 16:00:00+00:00      
.....
```

Essentialy what it shows is
there's an entry
several hours later (as configured) - there's a `custom_exit()` call that triggers the exit - and a subsequent `custom_exit_price()` call within the same candle.
Now `custom_exit` is also called in every candle between entry and exit - but these are not relevant as they don't trigger an exit.

Code for reproduction below.

<details><summary>Callbacks to produce this</summary>
<p>

``` python
    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['date'].dt.minute % 4 == 0)
            ),
            ['enter_long', 'enter_tag']] = (1, 'long_tag')
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        return dataframe

    def custom_exit(self, pair: str, trade: Trade, current_time: datetime, current_rate: float, current_profit: float, **kwargs) -> str | bool | None:

        if trade.open_date_utc + timedelta(hours=2) < current_time:
            print(f"custom_exit\t\t{pair}\t {current_time}")
            return 'asdfasdf'

    def custom_exit_price(self, pair: str, trade: Trade, current_time: datetime, proposed_rate: float, current_profit: float, exit_tag: str | None, **kwargs) -> float:
        print(f"custom_exit_price\t{pair}\t {current_time}")
        return proposed_rate

    def custom_entry_price(self, pair: str, trade: Trade | None, current_time: datetime, proposed_rate: float, entry_tag: str | None, side: str, **kwargs) -> float:
        print(f"custom_entry_price\t{pair}\t {current_time}")
        return proposed_rate
```
</p>
</details>

**Comment by k4pak** [comment]
> im working on strategy and i want to use a custom exit price , here is the problem that i have noticed about : when you are using a Function custom exit price and Custom exit which they call them CALLBACKS , in your documentation said that all these functions are runs at on closin candle , but this is not what i am facing . in reality when im coding , custom exit is not implementing on same candle as custim exit price , for example .. i want to use custom exit price on current candle but it makes an order for the next closing candle which i need to use it as a current candle not the next one ... which you have written wrongly on your documentation and the fucntion is not working ....

![photo_2024-04-06_13-08-48](https://github.com/freqtrade/freqtrade/assets/39931392/66d61bf8-9e22-4246-8d11-9835a2fdd137)

I entered a long position here. TP is the red line that I marked on the chart. Then I said in the custom exit function that when my shares go above this red line of 68483, return it to me. TP. After this function: I executed the custom exit price function, when I came to this custom exit price function, I said that when the exit tag was TP, return the same number 68483 as the output to the custom exit price.

And the problem is that when this custom exit is activated and the custom exit price comes, it leaves this 68683 as the exit, instead of closing the position in the same candlestick, it checks from the next candles whether it has reached 68483 and whether The position should be closed or not

**Comment by k4pak** [comment]
> Please get used to filling out the issue template. Those who frequently omit the template may have their issues closed without comment. We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.
> 
> Filling out the template helps reduce our workload, and we greatly appreciate that.
> 
> I'm not entirely sure where you got the fact from that a "custom_exit_price" callback would only be executed on candle close - that's not the case - and is also not written in the documentation like this.
> 
> custom exit price will be executed whenever an exit order is being placed - in live / dry-run - this can be "whenever". In backtesting, it'll be once per candle - UNLESS you're using `--timeframe-detail` - in which case it can be within a "main" candle - but it'll never be executed more often than once per detail candle.

thank you for your reply . but look at the new post i have sent here please.

**Comment by k4pak** [comment]
> Testing this a bit - i really don't see what you mean.
> 
> in backtesting, printing in both functions - i get the following output:
> 
> ```
> 2024-04-05 19:58:51,786 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2023-01-01 00:00:00 up to 2023-02-01 00:00:00 (3
> 1 days).                                                                                                                                     
> custom_entry_price      BTC/USDT         2023-01-01 01:00:00+00:00                                                                           
> custom_exit             BTC/USDT         2023-01-01 04:00:00+00:00                                                                           
> custom_exit_price       BTC/USDT         2023-01-01 04:00:00+00:00                                                                           
> custom_entry_price      BTC/USDT         2023-01-01 05:00:00+00:00                                                                           
> custom_exit             BTC/USDT         2023-01-01 08:00:00+00:00                                                                           
> custom_exit_price       BTC/USDT         2023-01-01 08:00:00+00:00                                                                           
> custom_entry_price      BTC/USDT         2023-01-01 09:00:00+00:00                                                                           
> custom_exit             BTC/USDT         2023-01-01 12:00:00+00:00                                                                           
> custom_exit_price       BTC/USDT         2023-01-01 12:00:00+00:00
> custom_entry_price      BTC/USDT         2023-01-01 13:00:00+00:00                                                                           
> custom_exit             BTC/USDT         2023-01-01 16:00:00+00:00
> custom_exit_price       BTC/USDT         2023-01-01 16:00:00+00:00      
> .....
> ```
> 
> Essentialy what it shows is there's an entry several hours later (as configured) - there's a `custom_exit()` call that triggers the exit - and a subsequent `custom_exit_price()` call within the same candle. Now `custom_exit` is also called in every candle between entry and exit - but these are not relevant as they don't trigger an exit.
> 
> Code for reproduction below.
> 
> Callbacks to produce this

thank you for your reply . but look at the new post i have sent here please.

**Comment by stash86** [comment]
If you want any help, please provide the strategy that we can use to test it ourselves. It all depends on how you write the two functions.

**Comment by k4pak** [comment]
> If you want any help, please provide the strategy that we can use to test it ourselves. It all depends on how you write the two functions.

Here is my functions:

```
def custom_exit(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, **kwargs):
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = dataframe.iloc[-1].squeeze()    
        global old_exit_price
        global old_sl_price
        if (trade.open_date_utc == current_time):
            old_sl_price = last_candle['SL82']
            if last_candle['low'] < last_candle['SL82']:
                print('SL82 price is touched')
                return 'SL'
            else:
                new_exitprice = last_candle['TP18']
                old_exit_price = new_exitprice
                print(current_time)
                print('set limit order at:')
                print(new_exitprice)
        else: 
            if last_candle['ishighest'] == True:
                old_sl_price = last_candle['SL05']
            if last_candle['high'] >= old_exit_price:
                print('limit has been riched')
                print(current_time)
                print('old exit price is: {}'.format(old_exit_price))
                print('high of candle is: {}'.format(last_candle['high']))
                return 'limit'
            elif last_candle['low'] < old_sl_price:
                print('SL touched')
                return 'SL'
    def custom_exit_price(self, pair: str, trade: Trade,
                          current_time: datetime, proposed_rate: float,
                          current_profit: float, exit_tag: Optional[str], **kwargs) -> float:

        dataframe, last_updated = self.dp.get_analyzed_dataframe(pair=pair,
                                                                timeframe=self.timeframe)
        
        global old_exit_price
        global old_sl_price
        print(exit_tag)
        exit_price = proposed_rate
        if exit_tag == 'limit':
            exit_price = old_exit_price
            print(exit_tag, exit_price)
            print('limit has been placed at:')
            print(current_time)
        elif exit_tag == 'SL':
            exit_price = old_sl_price
            print('set SL')
            print(exit_tag, exit_price)
            ex_tag = 'SL'
        else:
            print('exit_tag is not predicted!!!')
            print(current_time)
        return exit_price
```

**Comment by stash86** [comment]
Are we talking about backtest behavior or dry/live behavior? And I don't see "TP" tag in your code

**Comment by k4pak** [comment]
> Are we talking about backtest behavior or dry/live behavior? And I don't see "TP" tag in your code

Im talking about backtesting and as I mentioned my "TP" named as "limit" in custom_exit function

**Comment by k4pak** [comment]
![image](https://github.com/freqtrade/freqtrade/assets/39931392/c97954c5-82a6-4d63-a8d3-4a1a53354d2d)


this is my backtest result :


> "pair": "BTC/USDT",
                    "stake_amount": 899.9457012,
                    "max_stake_amount": 899.9457012,
                    "amount": 0.09604,
                    "open_date": "2020-02-02 08:00:00+00:00",
                    "close_date": "2020-02-06 12:00:00+00:00",
                    "open_rate": 9370.53,
                    "close_rate": 9736.12,
this is my backtest result 

look at my log which show you that my limit has been reach at this date and time  which is different from the time that freqtrade closing my postion ...  all i am saying is that , freqtrade function is not working at the SHADOW of the current candle and it close my trade when for the second time high of candle is above my exact price  ... and also there is a delay of timing ... see my current limit order in candle time and date 2020-02-05 20:00:00+00:00  but freqtrade close_date": "2020-02-06 12:00:00+00:00"..... there is so much differences ... 

this is log of my code :

limit has been placed at:
2020-02-05 20:00:00+00:00

**Comment by k4pak** [comment]
my code log has detected the time of 2020-02-05 **20:00:00**+00:00 which is not correct .. cuase my tp limit candle is at 2020-02-05 **16:00:00**+00:00 this time ... so here we are .. instead of current price limit time and candle , the freqtrade is going to choose next candle to update the results

**Comment by k4pak** [comment]
> Please get used to filling out the issue template. Those who frequently omit the template may have their issues closed without comment. We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.
> 
> Filling out the template helps reduce our workload, and we greatly appreciate that.
> 
> I'm not entirely sure where you got the fact from that a "custom_exit_price" callback would only be executed on candle close - that's not the case - and is also not written in the documentation like this.
> 
> custom exit price will be executed whenever an exit order is being placed - in live / dry-run - this can be "whenever". In backtesting, it'll be once per candle - UNLESS you're using `--timeframe-detail` - in which case it can be within a "main" candle - but it'll never be executed more often than once per detail candle.

i have updated my question .. can you see them and help me out ... appereciate it .

**Comment by stash86** [comment]
First of all, since you are new, calling a (relatively) old program with regularly-updated docs wrong just because you don't understand how the software work isn't really a good choice. The docs isn't wrong. You are the one understand it wrong,

Let's get to the issue. In backtest, exits are only checked once at the start of a candle. Let's use your example

![image](https://github.com/freqtrade/freqtrade/assets/13656154/a72ab6e2-7dd6-4ffd-ac77-58ac8c207121)
The candle at the right of A will be named B, C, and so on.

At the start of candle A, the "last candle" used in the custom_exit check is the "short" green candle, which doesn't satisfy your exit logic. So the bot move to the next candle.
At the start of candle B, the "last candle" is candle A. Your custom_exit is triggered, hence it will place the exit limit order at 9736.12. But remember, you are already at candle B. And if you look at candle B, C, D, and E, the candle never touch price of 9736.12. Only at candle F, the price reached your exit limit price, hence the exit happened at candle F.

So the result of your backtest is correct. You need to learn about the software more. Thanks

**Comment by k4pak** [comment]
first of all thank you and appereciate your time and fast response ... secondly i am now at freq you are right but i guess there is a misundrstanding over here ... as you mentioned candle A is my target price which touched by the shadow of the candle ... im gonna cut so much talking , what can i do to close my trade at my target TP in candle A ??



In addition ,i have also used custom_exit_price fucntion when i have **open** my trade but when i have done this my SL was not working , because my custom_exit_price (order)  blocked other closing ways of my trades .

**Comment by stash86** [comment]
As you mentioned on your first post, Freqtrade only work on closed candle. As long as candle A still open, custom_exit won't look at it. The "last candle" in the function will always be the short candle before it. And as I said, once candle A closed, you are already at candle B. So there is no way to close your trade at candle A using your functions.

**Comment by k4pak** [comment]
> As you mentioned on your first post, Freqtrade only work on closed candle. As long as candle A still open, custom_exit won't look at it. The "last candle" in the function will always be the short candle before it. And as I said, once candle A closed, you are already at candle B. So there is no way to close your trade at candle A using your functions.

i see , so most of trade is base on exact TP ... so how come i can get my hand on exact results of backtest when i cant have a exact TP on it ... you said that with these functions i cant close my trade on candle A ... so is there any other functions available in freqtrade that i can reach to my purpose im not aware of ???

**Comment by k4pak** [comment]
![image](https://github.com/freqtrade/freqtrade/assets/39931392/22f263c4-166a-4624-bcf1-9841dcc6970f)

this is a great example of exact TP ... look at the place of price that candle shadow on it and dropped like hell .. so imagin my tp is there and i have to wait untill the candle close above it ... never happend ... so what should i do ? :D

**Comment by k4pak** [comment]
lightenning me please how to use freqtrade function to overcome on this problem ... appereciate it .

**Comment by k4pak** [comment]
> As you mentioned on your first post, Freqtrade only work on closed candle. As long as candle A still open, custom_exit won't look at it. The "last candle" in the function will always be the short candle before it. And as I said, once candle A closed, you are already at candle B. So there is no way to close your trade at candle A using your functions.

⏫⏫⏫⏫⏫

**Comment by xmatthias** [comment]
Please learn how to **EDIT** your comments if you have something to add to your previous comment.

having 4 consecutive comments within a span of a few minutes is both hard to read - and can be seen as spamming.
Consecutive offenders of this can also be prevented from interacting with this repository. . .

---

You're correct - if you've got a High that'll trigger your TP - then it's possible that your exit order is placed too late.
The same thing can happen during live trading.
There's really no information in the candle if that "shadow high" was 1ms long - or if it took 1 hour (you're on 4h candles, it seems).

Freqtrade only provides the closed candle to avoid lookahead bias as much as possible (if you assume your trade triggers on the high of a candle - it's VERY likely that in reality, you'd be late to place the order, and hence would NOT be filled).
This is also true for backtesting - where lookahead bias can lead to very great looking strategies - while in reality - they'll simply fail as they use data they shouldn't have.
We spent a great deal of time to ensure that this can't happen accidentally as much as possible.

You can look "into" a candle by using `--timeframe-detail` when backtesting. 
It will simulate intra-candle movements based on a lower timeframe (you seem to work on 4h timeframe - so everything <4h will work.
it's a tradeoff between precision (1m) vs. speed (2h, in your case). Obviously this assumes that the smaller data is available, too.

**Comment by k4pak** [comment]
> Please learn how to **EDIT** your comments if you have something to add to your previous comment.
> 
> having 4 consecutive comments within a span of a few minutes is both hard to read - and can be seen as spamming. Consecutive offenders of this can also be prevented from interacting with this repository. . .
> 
> You're correct - if you've got a High that'll trigger your TP - then it's possible that your exit order is placed too late. The same thing can happen during live trading. There's really no information in the candle if that "shadow high" was 1ms long - or if it took 1 hour (you're on 4h candles, it seems).
> 
> Freqtrade only provides the closed candle to avoid lookahead bias as much as possible (if you assume your trade triggers on the high of a candle - it's VERY likely that in reality, you'd be late to place the order, and hence would NOT be filled). This is also true for backtesting - where lookahead bias can lead to very great looking strategies - while in reality - they'll simply fail as they use data they shouldn't have. We spent a great deal of time to ensure that this can't happen accidentally as much as possible.
> 
> You can look "into" a candle by using `--timeframe-detail` when backtesting. It will simulate intra-candle movements based on a lower timeframe (you seem to work on 4h timeframe - so everything <4h will work. it's a tradeoff between precision (1m) vs. speed (2h, in your case). Obviously this assumes that the smaller data is available, too.

Thank you so much 👍
