### ISSUE TITLE
How to bot activate at a certain price

### ISSUE THREAD

**Issue by cnbzmst** [freqtrade/freqtrade#10042]
**Describe your environment:**

- Operating system: Ubuntu 22.04
- Python Version: 3.10.12
- CCXT version: using docker with latest version of freqtrade
- Freqtrade Version: 2024.1 (freqtrade -V or docker compose run --rm freqtrade -V for Freqtrade running in docker)

  
**My question:**

Hello,
I read the documentation and researched the platform before the question.
My Question: I want my bot to run after a certain price drop. In other words, I want my strategy to work through the breakout after falling to a certain price. I don't mean opening a position multiple times, each time below a certain price. 
I could not develop a solution with populate_entry_trend or Callbacks. By what method or configuration can I do this? Can you give me an idea or direct me to a suitable link if available on the platform.

Thank you.

**Comment by stash86** [comment]
Add the price drop check on your entry logic

**Comment by xmatthias** [comment]
In the ehd, it is most likely a combination of indicators.

Yours kinda sounds like a combination of a MA (price dropped then recovered) - combined with a rolling max (price > rolling max = breakout). 
if you combine this with `crossed_above()` - it'll trigger when this breakout happens.

The exact details on HOW to combine things is however a question of "trial and experiment". There's no "THE ONE SOLUTION" - and everyone you'll ask will have a different opinion on what the actual, right logic is (wait for a confirmation candle, use other indicators to identify the previous drop, ...).

As a matter of fact, we're happy to provide technical assistance (or provide ideas for potential solutions) - but the assumption is that you do the legwork with both experimenting, and with implementing your solution (which is essentially a question of understanding pandas / indicators - and then running backtests to confirm and improve).

**Comment by cnbzmst** [comment]
Thank you very much for your quick response.
So, is there such an opportunity in Freqtrade? With my strategy, can I turn my bot, which is in "Stop" mode, into "Running" mode, in other words, can I wake the bot with a code?

**Comment by xmatthias** [comment]
Please refer to the [documentation](https://www.freqtrade.io/en/stable/telegram-usage/#start) for such issues.

I usually recommend to read through the documentation at least once, to know what possibilities freqtrade offers - and to avoid asking unnecessary questions, and subsequently avoiding wasting contributors precious free time.
