### ISSUE TITLE
I modified the price history file and got the error "No data history".

### ISSUE THREAD

**Issue by Artemkiin** [freqtrade/freqtrade#10040]
## Describe your environment

  * Operating system: Windows 10 Pro build 19045.4170
  * Python Version: 3.12.2
  * CCXT version: Unfortunately, grep doesn't work on Windows, but if I type "pip freeze" without "| grep ccxt" I get the following output:
  
dnspython==2.6.1
pymongo==4.6.2

  * Freqtrade Version: freqtrade 2024.2
  
## Your question

Hello, Freqtrade community!

Previously, I contacted the Freqtrade community in discord with a question about testing a custom signal pack

One of the users suggested this to me:

"All the indicators are just columns in the dataframe, you can add your own with whatever data you want, so full of 0s for example except for where you have your entry points"

And after I changed the historical data for the pair (now only for one pair for testing) and now my dataframes look like this:

[1652544660000,8.75,8.75,8.64,8.68,604.23,101202303]

[1652699640000,10.14,10.14,10.14,10.14,0.0,999888777]

If we are not interested in the current frame, I add “999888777” to the end.
If there is an enter in the current frame, I append "101202303" to the end.
 
For enter condition I wrote this:

          dataframe.loc[
              (
                  (data frame[6] == 101202303)
              ),
              'enter_long'] = 1

When I try to run backtesting with this strategy I get a "no data history" error with the history file modified.

Is this the right way or not? I read https://www.freqtrade.io/en/stable/strategy-customization/, it only says I should not change or delete the main columns, but nothing about adding additional ones

Could you help me with this issue? Thank you

**Comment by xmatthias** [comment]
Modifying the history file is NEVER the right approach, and i'm pretty certain that's not what was recommended.

the [documentation](https://www.freqtrade.io/en/stable/strategy-customization/#customize-indicators) does mention addition of new columns for indicators - but these should be added to the dataframe as part of the strategy - not to the history file.
A modified history file will most likely fail to load - which causes the "No data history" error. That's expected - and modifying the history file is clearly not anything we support, ever supported, or will support.

Aside from that, adding data to the history file directly would also not translate to dry-run  / live - where the stored files are irrelevant, but rather the data directly from the exchange will be used.

**Comment by Artemkiin** [comment]
Thank Your very much, xmatthias. Because i didn't see another way to impletement mark to do enter or not in this frame (i mean, without any TA, i just take custom pack of signals to enter from some source and testing a few conditions to exit) i will try to change volume column, i do not use it my strategies, so i hope it will not distort any important 

I know this may cause outrage, because this is an incorrect use of your product, but I hope you understand me

If You know more corrent way to do it, I would be very grateful for a hint

**Comment by xmatthias** [comment]
> will try to change volume column, i do not use it my strategies, so i hope it will not distort any important

Changing source files is not supported, and highly discouraged.
I don't see why you can't use a custom file - load that file, and merge it onto the dataframe - though how you use it is up to you.

You'll not get past backtesting with this way - simply caused by the fact that dry/live modes will NOT read the saved files - but that's up to you, too - we can't do more than tell you not to do something.

If you do it anyway - please don't expect any further help.

**Comment by Artemkiin** [comment]
> 
> Changing source files is not supported, and highly discouraged. I don't see why you can't use a custom file - load that file, and merge it onto the dataframe - though how you use it is up to you.
> 

Now i don't know how, but will seek it in documentation, thank You!
