### ISSUE TITLE
Implementing Exponential Stake Decrease. 

### ISSUE THREAD

**Issue by keithorange** [freqtrade/freqtrade#10052]
I'm exploring a unique approach to manage the stake amount for each new trade in Freqtrade, aiming to maximize the utilization of available capital while assuming a conservative posture that not many trades will be open simultaneously. The concept is straightforward: allocate a significant portion of the available capital to the initial trade, and then progressively reduce the stake amount for each subsequent trade by half.

Here's the breakdown of the strategy:

    Initial Trade: For an available total capital of $100, the first trade will utilize 50% of this amount, amounting to $50.
    Second Trade: The next trade will use 25% of the original capital, which is $25.
    Third Trade and Onwards: Each subsequent trade continues this pattern, halving the stake amount from the previous trade. So, the third trade would use $12.5, the fourth $6.25, and so on.

This staking strategy ensures that the first few trades utilize the bulk of the capital, under the premise that it's less likely to have many concurrent trades, thus potentially maximizing returns on fewer, more capitalized trades.

I'm seeking insights, suggestions, or existing implementations that align with this strategy. Has anyone in the community worked on or come across a similar approach in Freqtrade? Any pointers towards implementing this custom staking logic effectively within the Freqtrade framework would be highly appreciated.

**Comment by keithorange** [comment]
Also I want to have MULTIPLE parallel simultaneous bots running! So ensure each bot can use this as well!

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Please also use the EDIT function to update the original post if you notice you've forgotten something.

---

Now to be fair, nothing you describe sounds very innovative or unique.
you can accomplish this pretty easily with some logic in [custom_stake_amount()](https://www.freqtrade.io/en/stable/strategy-callbacks/#stake-size-management).

Combine this with [assign available capital](https://www.freqtrade.io/en/stable/configuration/#assign-available-capital) - and i don't see anything preventing this from happening.

Now i don't see us implementing your logic - that's up to you - and if you come across any particular questions, more than happy to help that - based on the existing logic.
