### ISSUE TITLE
Backtesting Error: "StaticPairList requires pair_whitelist" - Futures Console file does not find any Whitelist Trade Pairs

### ISSUE THREAD

**Issue by Diabolika1** [freqtrade/freqtrade#10054]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: Python 3.11.3
  * CCXT version: pip-24.0
  * Freqtrade Version: freqtrade 2024.3 (on docker)
  
## Your question

What is falsly setup in my console file regarding the "pair_whitelist", due to the fact i always receive after many tries the error
"freqtrade - ERROR - Configuration error: StaticPairList requires pair_whitelist to be set." when i try to backtest via "docker compose run --rm freqtrade backtesting --config user_data/config.json"

**Part of the console file in the code (checked syntax via chatgpt multiple times):**

    "pair_whitelist": [
        "ETH/USDT:USDT"
    ],
    "pair_blacklist": [
        "BNB/*"
    ],
    "pairlists": [
        {
            "method": "StaticPairList"
        }

Important info:
My goal is to run it for isolated futures ("trading_mode": "futures",     "margin_mode": "isolated",) and to check own strategies. With the sample_strategy and the pair_whitelist for Spot it worked, so i checked the nomenclature and changed it to "ETH/USDT:USDT", but it still always gives the same error. I run "StaticPairList" due to the fact the VolumePairList is not working for the backtesting.

I DryRan the script also with the Binance API, seems to be fine, Freqtrade UI i did not yet manage to setup, but can try in case that could support.

**Comment by xmatthias** [comment]
well the key `pair_whitelist` is not a top level key - but one that's within the exchange section.

That same part is mentioned in both the [configuration](https://www.freqtrade.io/en/stable/configuration/) - as well as in the [static pairlist](https://www.freqtrade.io/en/stable/plugins/#static-pair-list) section.

Same goes for the blacklist obviously ... which is even more dangerous - as it'll not warn you if it's not there as it's not required.

You're best off to start by using `freqtrade new-config` to generate a new configuration - or alternatively, by using one of the example configs - which all do include the pair-whitelist key in the correct location

**Comment by Diabolika1** [comment]
Thanks Matthias for the simple clarification. Moving the entries as based on the newConfig File is showing under Exchange, the issue is not popping up anymore. Seems some websites with examples do not have this covered correctly from earlier versions.

-- topic closed

**Comment by Diabolika1** [comment]
Closed
