### ISSUE TITLE
Please add futures for Kraken.

### ISSUE THREAD

**Issue by DragonBtc93** [freqtrade/freqtrade#10051]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*

**Comment by xmatthias** [comment]
Unfortunately, my country is restricted from trading futures on kraken.

As such - it's impossible for me to implement / test kraken futures (as well as it'll be impossible to verify a PR that's trying to add this, or trying to provide support for it going forward).

While that doesn't exclude others adding it, i'll not be accepting this from new contributors - as i need to be certain that that contributor will also stick around to provide support for this going forward (should users encounter problems, should things change on kraken's side, ...).

I currently don't see interest in this from the existing contributors - hence i'll close this as "not planned". 

That doesn't mean it'll not land at some point (GEO restrictions COULD also be lifted in the future...) - but it's neither planned, nor am i aware of any existing (longer-term contributores) with the desire to contribute and support this going forward.
