### ISSUE TITLE
Missing import on your adjust_trade_position example

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#10053]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Just a small thing:

For the adjust_trade_position example on https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position you may want to add

from typing import Optional, Union, Tuple

which is also needed.

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
Quite honestly - that would apply to most example sections.

They're not "full, run as is" examples - and i don't think it makes sense to aim for that, either (that'd make most examples WAY longer - as that'd require all `populate_*` methods to be implemented - subsequently drawing away focus from what the example aims to show).

Now i'm happy to review / accept Pull requests that aim to improve this if you think it's something that's lacking in the docs.

**Comment by myNextCoder** [comment]
Sorry for that, I was not sure - since you have placed some imports -, if you take care, to publish the complete header, corresponding to these callbacks. You don't need to do anything, since the bot stops, and the log contains the missing part.
