### ISSUE TITLE
Put /SL TP with price

### ISSUE THREAD

**Issue by ahmad-develop** [freqtrade/freqtrade#10060]
## my environment : 

  * Operating system: ubuntu 20
  * Python Version: python 3.9
  * CCXT version: ccxt==4.2.87
  * Freqtrade Version: freqtrade 2024.4-dev-24717b160
  

Hello, is it possible for TP/SL to put a price instead of a percentage when placing an order?
For example, I want my SL to be the high of the previous candle, and I cannot use a percentage for this.

**Comment by stash86** [comment]
Use this as an example on how to use absolute price instead of percentage

https://botacademy.ddns.net/2024/03/04/fsd-how-to-use-atr-for-exits-roi-and-stoploss/

**Comment by xmatthias** [comment]
You can use [custom-exit-signal](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-exit-signal) for regular exits once a certain price crosses, and [custom-stoploss](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stoploss) for stoploss. 
Combine the stoploss with the [stoploss_from_absolute](https://www.freqtrade.io/en/stable/strategy-callbacks/#stoploss-relative-to-open-price) helper - and you should have everything you need.


Please do make sure to understand the restrictions for custom-stoploss behavior (it can only move up / closer to the position) - never away from it (then it'd be no stoploss, just a random order that's replaced whenever price goes near it).
