### ISSUE TITLE
How can i attach extra data on data-downloading?

### ISSUE THREAD

**Issue by PushjoeYY** [freqtrade/freqtrade#10066]
## Describe your environment

  * Operating system: ubuntu
  * Python Version: 3.10 (`python -V`)
  
## Your question

Freqtrade only has OHLCV data during data downloading. Is it possible to attach other data? Such as https://binance-docs.github.io/apidocs/futures/en/#long-short-ratio.

**Comment by xmatthias** [comment]
long/short ratio is not something that's currently supported.

I also don't think ccxt has this data in an unified way - at least i can't find it in their [unified api](https://docs.ccxt.com/#/?id=unified-api) list.
While that doesn't prevent us from using it in theory - it's not something that's planned, either.
