### ISSUE TITLE
Position stacking in live/dry mode - implementation

### ISSUE THREAD

**Issue by ir0nt0ad** [freqtrade/freqtrade#10092]
## Describe your environment
irrelevant  

## Your question

Hi, just wanted to confirm my understanding that position stacking in live/dry is done via `adjust_trade_position`. I see the example code in the docs, and I simply want to replicate the logic of `--eps` of the backtesting mode. Any advice will be appreciated. Thanks!

**Comment by stash86** [comment]
--eps is different than adjust trade. You can however use adjust trade on backtest.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

`--eps` is a mode for experimentation, trying to show "hidden" signals.

this is also covered in the [FAQ](https://www.freqtrade.io/en/stable/faq/#can-freqtrade-open-multiple-positions-on-the-same-pair-in-parallel).
