### ISSUE TITLE
related parameters for hyper opt 

### ISSUE THREAD

**Issue by k4pak** [freqtrade/freqtrade#10095]
i have a 3 parameters that i want to optimize them , and they are related to each other . when i wrote the connection fomula between them , the connection suposed to work regarding freqtrade base .. but it doesnt .. here is my code : 

   exit_percentage_tp1 = DecimalParameter(0.0, 0.9, decimals=2, default=0.0, space="buy")
    exit_percentage_tp2 = DecimalParameter(0.0, 1.0 - exit_percentage_tp1.value, decimals=2, default=0.0, space="buy")
    exit_percentage_tp3 = DecimalParameter(0.0, 1.0 - exit_percentage_tp1.value - exit_percentage_tp2.value, decimals=2, default=0.0, space="buy")
  

exit_percentage_tp1 has been open from 0 to 0.9 then exit_percentage_tp2 is open from (0 to 1 - exit_percentage_tp1) and now sum of these 2 prameters must be maximum = 1 and so on ,.,, here is the problem coming out from freqtrade ... the freq numbers output is over than sum number of 1 and the hyper opt  result is 

 "exit_percentage_tp1": 0.9,
        "exit_percentage_tp2": 0.01,
        "exit_percentage_tp3": 1.0,

which is the sum of the above results is more than 1 ....

**Comment by stash86** [comment]
It won't work that way. The params are expanded into list of values on startup. So any limitation you put there won't work like what you think

**Comment by k4pak** [comment]
> It won't work that way. The params are expanded into list of values on startup. So any limitation you put there won't work like what you think

so what should i do then ? i have 100$ as my initial amount , so i want to tell freq by my code to find a exit tp and find the best precentage of my initial amount so here is 4 or 5 exit point , the total of these 5 must be 100 $ , what should i do to then ?

**Comment by stash86** [comment]
Well, there is no solution for that. You have to be creative and use other way, or change the logic, or something else

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---


Well you can't do this logic in this location.
`.value` is only usable in either callbacks - or in `populate_*()` methods (except `populate_indicators()` - unless `--analyze-per-epoch` is given).
It's however not available at the class level - or rather - it'll be available, but will not be changing, and keep it's default value - as the code defining the parameters is not re-evaluated again after the strategy is initialized.


---

Your logic does however look fairly simple - you can simply use 3 parameters going from 0 to 1 (or whatever else) - and then assume the sum of the upper limit as 100% - and then split it accordingly where you're actually using this.

Now the exact logic will depend on your exact needs - but should be fairly simple to be implemented at the location of where you're using it.
