### ISSUE TITLE
USD/EUR Fiat convert not working on Telegram, showing 0

### ISSUE THREAD

**Issue by jelalanne** [freqtrade/freqtrade#10102]
Same as https://github.com/freqtrade/freqtrade/issues/661

**Comment by stash86** [comment]
Post the logs

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Considering you're saying it's the same as #661 - i'd encourage you to update to a more recent version.
That'll most likely fix your issue.
