### ISSUE TITLE
dataframe['volume'] is 0, can't seem to call upon talib volume? freqtrade volume need to access.

### ISSUE THREAD

**Issue by Nikita-Anistratov** [freqtrade/freqtrade#10101]
## Describe your environment

  * Operating system: ____  macOS 12.7.4
  * Python Version: _____ (`python -V`) Python 3.12.2
  * CCXT version: _____ (`pip freeze | grep ccxt`) ? 
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker) newest running with docker
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Im not getting any volume data for some reason when running  "dataframe['volume'] "

print("volume is: " + str(dataframe['volume']))

i'm running this= when backtesting on historical data which works with other strategies, but I was writing some new parameters using volume and turns out volume is returning 0, what do you think the issue could be?  

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened? volume is 0
  * What did you expect to happen? need volume to not be 0 

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by stash86** [comment]
If it works with other strategies but not that specific strategies, then that specific strategies is the issue. Without looking at any code, we won't be able to help you. All I can guess is, you unintentionally modify the value of dataframe['volume']
