### ISSUE TITLE
How to use spot market data, but trade using futures?

### ISSUE THREAD

**Issue by gmvp3** [freqtrade/freqtrade#10119]
How to use spot market data, but trade using futures?
Because the futures market data always deviates from the spot.
Thanks.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

You can use the [`@informative`](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs-decorator-informative) decorator and provide the `candle_type` argument (spot, to get spot data).

It's however not guaranteed that this method works on all exchanges in dry/live mode - as the underlying ccxt object is for futures markets. 
I know this works for some exchanges, but it's not something we actively test for (you'll get data back, but please do sanity checks for your exchange to ensure it's actually spot data).

**Comment by gmvp3** [comment]
I'll look into it. Thank you very much~~
