### ISSUE TITLE
Reinforced Learning CPU Core Utilization

### ISSUE THREAD

**Issue by RuiSiang** [freqtrade/freqtrade#10129]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: freqtrade:stable_freqairl latest
  * CCXT version: freqtrade:stable_freqairl latest
  * Freqtrade Version: freqtrade:stable_freqairl latest
  
## Your question

When I used FreqAI, CPU usage hit nearly 100% on all cores during training; however when switched to RL, training is only done on one core, is this expected? Thanks!

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by robcaulk** [comment]
Yes, it is expected that different algorithms and different ML architectures will have completely different CPU usage.

With that said, RL has parameters for controlling how many cores should be used during *parts* of the RL process. You did not mention what values you have set those parameters to, so I'm not sure how to help you on this piece, besides direct you to the RL parameter table: https://www.freqtrade.io/en/2024.1/freqai-parameter-table/#reinforcement-learning-parameters

On a related note: RL is inherently sequential, so there are certain aspects that are not parallelizable. Have a look at topical discussion https://github.com/freqtrade/freqtrade/issues/10017#issuecomment-2027325705 .

**Comment by RuiSiang** [comment]
My bad, must have missed that param.
