### ISSUE TITLE
REST API - couldn't expose port 8080 to network as per doc instruction

### ISSUE THREAD

**Issue by actuarialsnail** [freqtrade/freqtrade#10128]
I'm running the bot using docker on a remote pi on a local network, however I was not able to expose the docker to incoming connections via the pi with the following instruction

Make sure that the following 2 lines are available in your docker-compose file:
    ports:
      - "127.0.0.1:8080:8080"

It works if I instead change the lines in the docker-compose file to:
    ports:
      - "0.0.0.0:8080:8080"

Is the 127.0.01 intended for accessing the bot via the local network?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

` "127.0.0.1:8080:8080"` means it's only available to the host it's running on (unless you've got other setup that exposes the port to the network).

`"0.0.0.0:8080:8080"` (or `"8080:8080"`) will expose the port to the whole network.
if that's a private network (your home network) - that's usually safe (assuming you trust the members on this network).
It's however unsafe for a VPS - as that would expose the port to the whole internet - so everyone from everywhere could access it - knowing your IP (there's enough checks around for every IP every hour - so they'll know your IP in a second).

**Comment by xmatthias** [comment]
Essentially - it's what's described in the security warning in [API configuration with docker](https://www.freqtrade.io/en/latest/rest-api/#configuration-with-docker) - which i've just slightly reworded to also include the `"0.0.0.0:8080:8080"` case.

**Comment by actuarialsnail** [comment]
thanks
