### ISSUE TITLE
1 call to the exchange to service 2 strategies

### ISSUE THREAD

**Issue by Immortality-IMT** [freqtrade/freqtrade#10123]
Is there a way to configure config.json for 1 api call to the exchange to service 2 or more  strategies so that the api calls are optimized.

1 call to binance for example, get used by 2 or more strategies

considering both are using identical settings such as identical pair list and so on.

I am currently using a number of config.json that are pretty much identical except for bot name and webui details.

Thanks in advance.

**Comment by stash86** [comment]
You can split the config into several parts, so you only have to change certain part, and use same files for the rest

**Comment by Immortality-IMT** [comment]
How does that ensure 1 api call to the exchange or does it when the each strategy has its own terminal?

**Comment by stash86** [comment]
If you want only 1 API call, use proxy. Google "freqtrade binance proxy" or "freqtrade kucoin proxy"

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that. 

---

While it may seem identical - calls are usually not.
Timing will be different - and calls deviate a lot once you're in a position with one bot, but not with the other.
One IP can usually handle ~3 bots (on binance, at least) - after that, you'll need to scale horizontally, using multiple servers.
Usually however, the limit is also the resources available on the actual system - not just api calls - so scaling horizontally (more servers) usually makes sense after a few bots - unless you attempt to run on a pretty big server / system).


Whilest running with a proxy is something common - all of the ones i looked at are unmaintained - and we will be unable to support deployments that do use such proxies.

**Comment by Immortality-IMT** [comment]
Noted, Idk, but the limits of running multiple strategies on a single machine are quickly reached. I am dry run testing 10 strategies and I am using about 16GB ram and CPU is at 100%.

If any efficiencies are available in the next versions they are welcome.

Like for instance, a single call to the exchange.

**Comment by stash86** [comment]
Call to exchange don't contribute a lot to the CPU usage. Your strategies are too "heavy". Make them simpler if you can

**Comment by froggleston** [comment]
CPU usage comes down to indicator calculation. I'm running 15-21 bots on a single server and use about 30-40GB RAM (5m timeframe plus informatives) and need to use 3 binance-proxy services to make sure I don't hit rate limits.

**Comment by Immortality-IMT** [comment]
Idk what the solution is here. Compile the strategies? Shared candlestick data? If the performance of dry run testing could improve that would allow for running more strategies.

pmap -X pid lists heap and a strategy is running checks on the heap every 0.1ms

Flat files? for dry run mode.

**Comment by froggleston** [comment]
`Shared candlestick data` - that's what an exchange proxy like [binance-proxy](https://github.com/nightshift2k/binance-proxy) does. You still have to do the indicator calculation per bot instance though, so again, you're not really saving many CPU cycles. Compiling strategies will make zero difference to this. There's no real "issue" with the performance of dry runs. The more complex your strategy is, the higher single core clock speed you'll need.
