### ISSUE TITLE
Difference between SKDecimal and DecimalParameter

### ISSUE THREAD

**Issue by Debeet** [freqtrade/freqtrade#10137]
Hello. My question is what is the difference between SKDecimal and DecimalParameter in Hyperopt? Is one more performant than the other or is it just an alias?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

The answer is neither.

DecimalParameter is a parameter for freqtrade's hyperopt process - which will use the underlying SKDecimal space (a scikit-optimize compatible space).
You can't use them interchangably - and which one is the correct one will depend on the actual place you're trying to use them.


In almost all cases, using DecimalParameter is the correct way.
You shouldn't use spaces directly in your strategy unless you're overwriting space functions (roi, stop, ...).
