### ISSUE TITLE
how to see BackTesting result in FreqUI?

### ISSUE THREAD

**Issue by whichouno** [freqtrade/freqtrade#10134]
## Describe your environment

  * Operating system: macos docker
  * Freqtrade Version: 2024.3  (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
     FreqUI Version: 1.2.6-95a879b

## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
you can start freqtrade in webserver mode (`freqtrade webserver`) - which will then have freqUI in a mode that allows backtesting, visualization of past backtest results ...

**Comment by whichouno** [comment]
> you can start freqtrade in webserver mode (`freqtrade webserver`) - which will then have freqUI in a mode that allows backtesting, visualization of past backtest results ...

got it，thanks
