### ISSUE TITLE
modify the method to guarantee the execution of model training (freqai_interface - ensure_data_exists)

### ISSUE THREAD

**Issue by xsa-dev** [freqtrade/freqtrade#10145]
https://github.com/freqtrade/freqtrade/blob/71ef6f70e5e80696d7dfaaa27d07b5c5d12b881a/freqtrade/freqai/freqai_interface.py#L296
in order to avoid model training errors it is necessary to check the dataset

**Comment by xmatthias** [comment]
I'm ... not entirely sure if the provided details are sufficient.

It's kinda lacking ... basically every nuance of detail one could think off :laughing: 
i hope it's based on some conversation you had - otherwise i doubt that we'll be able to do much with this.

**Comment by xsa-dev** [comment]
@xmatthias
Yes, you got that right. We'll solve that issue later. Thank you!
