### ISSUE TITLE
Access to metadta in bot_start callback

### ISSUE THREAD

**Issue by quantsirius** [freqtrade/freqtrade#10162]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: Python 3.10.12
  * CCXT version:ccxt==4.2.82
  * Freqtrade Version: freqtrade 2024.3
  
## Your question

Hi. I would ask how can I use metadata info in bot_start callback. I wand to load separate ml models for each pair and need to have metadata or pair info. Or maybe another solution that someone can recommend to load models. Thank you. Would be appreciate for any help.

**Comment by xmatthias** [comment]
both `bot_start()` and `bot_loop_start()` (runs once per iteration) do not run in the context of a pair, but do run once globally - so you'll not be getting metadata for it.

in theory - you should be able to use something around [dp.current_whitelist](https://www.freqtrade.io/en/latest/strategy-customization/#current_whitelist) to get the actual current whitelist - though i don't think you can access this in bot_start - as the whiltelist isn't built at that point yet.

I'm also asking myself why you can't use freqAI - which brings essentially the same logic builtin - though it also includes continuous training of these models  . . .

**Comment by quantsirius** [comment]
Thank you for answer. I think dp.current_whitelist would be solution.
I don't use freqAI as I have more complex implementation. Especially I need to train model by more power server unlike that I used for live trading.
