### ISSUE TITLE
Feature idea: Store sell reason in the database

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#1017]
## Basic Idea

Storing the reason for the sell (stop-loss / trailing-stop / ROI / sell-signal) will enable us to better diagnose problems / issues with sells. it should also enable a "post run" analysis of a strategy, checking if stop-loss / sell-signal causes losses.
The information is currently in the logs, however this makes analysis very difficult (and requires a high log-level as "stop-loss" is a debug signal.

## Implementation details
- [x] Add DB column with sell-reason
- [x] Add DB migration 
- [x] record sell-reason in trade object
- [x] record this in Backtest-result as well 
- [x] show reason-statistics in backtest-output
- [x] (Optional) Store `ticker_interval` and `StrategyName`
- [x] (Optional) Add helper-scripts to facilitate analysis by users

**Comment by creslinux** [comment]
I agree with this. 
I would also say we should strategy that opened the trade in the database too.

From a user perspective i want to query my trades and know what opened/closed a trade - after switch strategies around that information would be lost.

**Comment by xmatthias** [comment]
> I would also say we should strategy that opened the trade in the database too.

you mean to add the strategy-name? i think that would only be of limited use - you will probably keep the name the same and modify parameters "until you like them" ... at least that's how i do it ...

**Comment by creslinux** [comment]
The strategy name, the ticker_interval, and the pair
From a user perspective that information is valuable to keep record of and is lost unless keeping a manual record.

**Comment by xmatthias** [comment]
i don't think you should change ticker_interval on a existing database - the sell-signals could be completely different ... 

but i'll have a look, if it's straightforward, adding 3 more columns is ... easy

**Comment by creslinux** [comment]
awesome

**Comment by xmatthias** [comment]
Closing this as it's actually implemented now.
