### ISSUE TITLE
Trade object: Remaining amount

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#10172]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.3 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

As I split my trade in adjust_trade_position, I exit by a "sliced stoploss" with a division, finally I need to sell the remaining amount of the trade. Will return trade.stake_amount fire an error, since not the entire stake amount is anymore present? Can I use trade.amount instead, which is declared as "Amount in Asset / Base currency that is currently owned" ?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
`stake_amount` will be adjusted with trade adjustments - so you can use it independent of the eventual adjustments.

returning `trade.amount` will be in the wrong currency - so depending on the price of that asset - results can be that the result is either rejected (if trade.amount > trade.stake_currency) - or it's selling part of it (if trade.amount < trade.stake_currency).

**Comment by myNextCoder** [comment]
I use stake_amount in that case, I thank you. Strongly mathematically I can go on with selling a divided amount until the end, but as amounts may be rounded, I might have to handle "dust" finally, which will probably remain on the wallet.

**Comment by xmatthias** [comment]
you can go on selling divided amounts until you reach the minimum tradable amount (around 10-15$ on binance) - in the callback reflected as `min_stake`.

After that, partial exits will be rejected unless they're for the full amount.

**Comment by myNextCoder** [comment]
Ok, currently I sell stake_amount as the last part, if I discover remaining amounts on the wallet, because they are less than min_stake, I go more deep into the code.
