### ISSUE TITLE
AI Code optimization "proof-reading"?

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#10190]
## Describe your environment

  * Operating system: Windows 2022
  * Python Version: Current Minicoda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.3 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

(Please tell me, if you are not intended with your forum, to answer such kind of questions. I'll ask them as seldom as possible.)

Since this code optimization was done "in collaboration" with AI, I have to be careful with the result. Are the two code fragments logically the same?

This line is added later: Due to the line wrap, the code is not readable anymore, I just add my code as images, sorry for that.

original:

``` python
        p = 14
        d = 3
        k = 3

        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=30)
        srsi  = (dataframe['rsi'] - dataframe['rsi'].rolling(p).min()) / (dataframe['rsi'].rolling(p).max() - dataframe['rsi'].rolling(p).min())
        dataframe['k'] = srsi.rolling(k).mean() * 100
        dataframe['d'] = dataframe['k'].rolling(d).mean()
```
        
optimized:

``` python
        dataframe['k'] = (ta.STOCHRSI(ta.RSI(dataframe, timeperiod=30), timeperiod=14, fastk_period=3, fastd_period=3)[0]) * 100
dataframe['d'] = dataframe['k'].rolling(3).mean()
```

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by myNextCoder** [comment]
![optimized](https://github.com/freqtrade/freqtrade/assets/34372534/2162e7a8-ed7f-47ef-a81c-4d2f2c76f436)
![original](https://github.com/freqtrade/freqtrade/assets/34372534/a02b9c6b-b927-42d0-a101-60a1229abf46)

**Comment by xmatthias** [comment]
I don't see why the "original" would need performance tuning - as it's already using vectorized methods - so i doubt it'll go "that much" faster.
The controll however, if the AI generated the identical response - is 100% up to you.

Please understand that we'll not be debugging and correcting "optimizations" the AI provided you with.

Please don't open issues that ask for such things in the future. 
We're not providing "AI proof reading" services (though maybe we should - but these will clearly not be free).

**Comment by myNextCoder** [comment]
I thank you for having reformatted my textbased code. It is absolutely ok, when you do not spend time here, to offer code optimization tips. I didn't think about the easy solution before, which I follow now: Plotting both lines (original and optimized) at the same time shows me, if the calculation is identical.

**Comment by myNextCoder** [comment]
. . .finally I discovered, that the optimization was wrong. I just had to re-invent the wheel without AI, by myself ;)
