### ISSUE TITLE
Is it good practice to store objects in main dataframe?

### ISSUE THREAD

**Issue by snussik** [freqtrade/freqtrade#10193]
## Describe your environment

* Operating system: Win 11
* Python Version: 3.12.2
* (CCXT version: 4.2.87
* Freqtrade Version: freqtrade 2024.4-dev-e6da491ca
  
## How-to store objects better?
In the context of the performance and data consistency, which option is better while storing additional objects in strategy:

1. inside main dataframe:
```python

needed_objects = pd.DataFrame({'id':[1,2,3], 'obj':[ob1, ob1, ob1]})
dataframe.loc[condition, 'needed_objects '] = needed_objects 

```
2. In global objects, created above the strategy class.

**Comment by Axel-CH** [comment]
It is not a good practice to store customized informations in dataframe outside of indicators.
Please take a look at the [advanced strategy](https://www.freqtrade.io/en/latest/strategy-advanced/#storing-information-persistent) part of the documentation witch explain how to store data for later usage

**Comment by snussik** [comment]
@Axel-CH  I've read this before that's why is the question: my purpose is to store objects, like last 100 pivot points, or nearest 20 support and resistancel levels. I'd like to store them as dataframe objects. But I doubt that  putting them inside main dataframe is a good idea.

**Comment by Axel-CH** [comment]
In that case you are talking about custom indicators, you can use the dataframe to generate and manage them. This is advanced usage that go beyond the documentation. I suggest you to familiarize yourself with panda dataframe usage. Start with simple cases, then raise complexity as you get more experienced. 
The example you provided is not valid as you are trying to create a new dataframe.
You should add columns to the existing one, so the custom indicator data will be available like 'open', 'high', 'low', 'close'.

**Comment by snussik** [comment]
@Axel-CH yep, thats what I'm asking about. Is it's a good decision to store "nested" dataframes inside the main dataframe. Or anything better exists in freqtrades  functionality?

**Comment by Axel-CH** [comment]
I think storing a dataframe within another one can be considered as an antipattern, also it is not an efficient way to store and retrieve data. I would not encourage you to do that.
Feel free to join the [Discord](https://discord.com/invite/p7nuUNVfP7) channel get more information from the community about strategy related topics.

**Comment by xmatthias** [comment]
If it's a nested dataframe, it'll not be available for plotting - which (for such points) is often a key determining factor.

the dataframe is however made to add additional columns which contain your values - so they can be easily used and plotted (e.g. "pivot1", "pivot2", ...).
