### ISSUE TITLE
Custom Telegram message from Strategy

### ISSUE THREAD

**Issue by alisalama** [freqtrade/freqtrade#10207]
## Describe your environment

  * Operating system: MacOS
  * Python Version: 3.8.12
  * CCXT version: 4.3.16
  * Freqtrade Version: freqtrade docker-2024.5-dev-63c8eae4

## Your question

Hi, is there anyway to send a custom telegram message from the strategy? I have a daily data feed into my bot, and my strategy detects whether it has been updated or not. I wondered if it is possible to send a telegram message from my strategy confirming whether it has been updated or not.

I have read through all the docs, but can't see that anywhere.

Thanks,
Ali

**Comment by xmatthias** [comment]
> I have read through all the docs, but can't see that anywhere.

Well the [docs](https://www.freqtrade.io/en/stable/strategy-customization/#send-notification)  proof otherwise :laughing:
