### ISSUE TITLE
trailing_stoploss_positve and minimal_roi

### ISSUE THREAD

**Issue by TearsOfTheEarth** [freqtrade/freqtrade#1020]
Hi,

I have a suggestion that trailing_stoploss_positve should only kick in once the minimal_roi reached. So it will take advantage on bursts when you are above expected profit. Currently it seems to be selling at loss that is not something would expected. So for example: you have an asset that is +0.01% and have trailing_stoploss_positve set to 1% and you can end up with a trade closed at -0.99%.
What do you think?

**Comment by xmatthias** [comment]
The way ROI currently works is that it sells once it's above that value, so your approach would not work.
The idea with `trailing_stoploss_positive` was to have ROI "higher" ... and trailing-stop kicks in after that. 

You're right that the above scenario can happen, however i would not use ROI for it, but a "trailing_stop_positive" offset / limit value (unrelated to ROI).
i may want ROI at 5% (cash out) ... but trailing-stop should apply 1% after 1.5% gain ...

**Comment by TearsOfTheEarth** [comment]
Thanks for the explanation.
What if we add another option for trailing take profit? I will borrow an animation to show the idea:
![trailing take profit](https://3commas.zendesk.com/hc/article_attachments/360001003713/TTP.gif)
So if it set then reaching minimal_roi should start trailing instead of the instant buy.
Anyway I have a feeling that something wrong with how trailing_stoploss_positve works, maybe it should kick in not above 0% but above its own value?

**Comment by xmatthias** [comment]
> Anyway I have a feeling that something wrong with how trailing_stoploss_positve works, maybe it should kick in not above 0% but above its own value?

that's a good point, @berlinguyinca you where the original author of this feature - may i ask for your opinion on this?

**Comment by TearsOfTheEarth** [comment]
ok, will try running this one for a while (if trailing_take_profit is set to true in the config then baseline for trailing_stop_positive will be minimal_roi instead of 0%):
```diff
--- analyze.py.orig     2018-07-12 21:30:22.724952115 +0300
+++ analyze.py  2018-07-14 23:52:42.484442379 +0300
@@ -189,8 +189,10 @@
             logger.debug('Buy signal still active - not selling.')
             return False

+        trailing_take_profit = self.config.get('trailing_take_profit', False)
+
         # Check if minimal roi has been reached and no longer in buy conditions (avoiding a fee)
-        if self.min_roi_reached(trade=trade, current_profit=current_profit, current_time=date):
+        if not trailing_take_profit and self.min_roi_reached(trade=trade, current_profit=current_profit, current_time=date):
             logger.debug('Required profit reached. Selling..')
             return True

@@ -235,12 +237,17 @@
             # check if we have a special stop loss for positive condition
             # and if profit is positive
             stop_loss_value = self.strategy.stoploss
-            if 'trailing_stop_positive' in self.config and current_profit > 0:
-
-                # Ignore mypy error check in configuration that this is a float
-                stop_loss_value = self.config.get('trailing_stop_positive')  # type: ignore
-                logger.debug(f"using positive stop loss mode: {stop_loss_value} "
-                             f"since we have profit {current_profit}")
+            if 'trailing_stop_positive' in self.config:
+                if 'trailing_take_profit' in self.config:
+                    if self.min_roi_reached(trade=trade, current_profit=current_profit, current_time=current_time):
+                        stop_loss_value = self.config.get('trailing_stop_positive')
+                        logger.debug(f"min_roi_reached hit, starting trailing take profit @ {current_profit}")
+                elif current_profit > 0:
+
+                    # Ignore mypy error check in configuration that this is a float
+                    stop_loss_value = self.config.get('trailing_stop_positive')  # type: ignore
+                    logger.debug(f"using positive stop loss mode: {stop_loss_value} "
+                                 f"since we have profit {current_profit}")

             trade.adjust_stop_loss(current_rate, stop_loss_value)
```

**Comment by berlinguyinca** [comment]
I think this is really difficult to answer. I personally think we should have a configuration to define a custom stop loss over X percent. Since 0%, will cause too often to sell an asset to soon.

Having the stoploss over minimal ROI is a great way to lose a lot of money quickly if a trade goes against you and this might be a different stop, or even better handled by the strategy and not the bot it self.

**Comment by xmatthias** [comment]
i agree with @berlinguyinca , i'm currently eying with 2 different configurations;

``` json
{
    "trailing_stop": false,
    "trailing_stop_positive": 0.005,
    "trailing_stop_positive_offset": 0.001,
}
```

or break current configurations for everyone:

``` json
{
    "trailing_stop": {
      "enabled": true,
      "positive": 0.005,
      "positive_offset": 0.001,
     }
}
```

... i like the 2nd option better as it groups the elements - but will break configuration for everyone currently using it.

**Comment by TearsOfTheEarth** [comment]
How about supporting both for a while with a warning for the first one that it will be depreciated going further.
The thing is that I believe it is not something very useful if you can't tie it to min ROI.
Would it be possible to literally set positive_offset to "minimal_roi"? :)

> Having the stoploss over minimal ROI is a great way to lose **a lot of money quickly** if a trade goes against you and this might be a different stop

How is that possible in most cases?

**Comment by xmatthias** [comment]
not sure about that...
supporting both will introduce a lot of management code for basically nothing ...

i think i'll go with the first option, as it should allow moving this to strategy more easily.

not sure i understand your piont on min-roi stuff - you configure min-ROI too (either in config, or strategy) ... so can't you simply configure it to your "minimal ROI?"

**Comment by TearsOfTheEarth** [comment]
>not sure i understand your piont on min-roi stuff - you configure min-ROI too (either in config, or strategy) ... so can't you simply configure it to your "minimal ROI?"

    minimal_roi = {
        "1440": 0.01,
        "80": 0.02,
        "40": 0.03,
        "20": 0.04,
        "0":  0.05
    }
what value do you suggest to put in this case?

>once min-ROI is reached it will sell anyway ... so what's the point to adjust stoploss once the trade is sold?

It should not! That is the point. Check the animation above, the cyan line is our min roi and patch is quick implementation of this.

**Comment by xmatthias** [comment]
to match the behaviour in the picture is possible easily with the PR.

```json
{
"trailing_stop_positive_offset": 0.05,
"trailing_stop_positive": 0.01,
"stop_loss": 0.xx
}
```

you set positive_offset to 5% - and stop-positive to 1% - so once you hit 5% profit, you pull a trailing stop of 1% below the maximum behind you until the peak is reached and it pulls back more than 1%.

i did not configure stoploss as it's not clear from the animation, set it to whatever you are ready to loose (probably 5% or 10%).

**Comment by TearsOfTheEarth** [comment]
When it will be sold? Maybe the below will help:
https://3commas.zendesk.com/hc/en-us/articles/360000239454-How-Trailing-Take-Profit-works
So you can have min ROI set to 5% but get a profit more then that if trend is bullish.

**Comment by xmatthias** [comment]
then set ROI to a very high number (1) ... and rely on the above configuration sample, which does accomplish the same thing.

**Comment by TearsOfTheEarth** [comment]
yes, I agree that the desired behavior can be achieved this way, though it feels like a "config hack" :)

**Comment by xmatthias** [comment]
no, it's actually what it was developed for...

the naming of `trailing_stop_positive` is unfortunate, as it's really a "take profit" if configured correctly - but i am hesitant to rename the option (and therewith breaking everyones config, as it can be either a different stop-loss, or a "trailing profit", depending on how it's configured ).

**Comment by vpotap** [comment]
if i have in strategy 10% 
  minimal_roi = {
        "0": 0.1
    }

and in config.json for trailing stop

"trailing_stop": true,
"trailing_stop_positive_offset": 0.01,
"trailing_stop_positive": 0.01,

Just to be sure ... once i hit profit >1% , then trailing stop  pull to 1%  but when i hit profit >2% then trailing stop pull to 2% ? Does this mean trailing stop is pulled when next positive offset step is reached - in this example trigger points are 1% ,2% , 3% ... 9% when stop loss is pulled ?

**Comment by xmatthias** [comment]
no, `trailing_stop_positive_offset` defines when the positive value is applied.

your above configuration would set the trailing-stop to 0% profit after it reached 1% gain (so i would recommend using 1.2% positive offset here to avoid early sells).

Basically it's pulling stop-loss after itself with `trailing_stop_positive` offset (so 1% in your case).
stop-loss would be set to 0.5% after 1.5% profit.
if you have 9% profit (without ever pulling back more  than 1% while climbing) - stop-loss would be set to 8%.

hope this makes sense.

i'll also close this issue as the PR was merged, but feel free to keep the discussion going if there are still open questions.
