### ISSUE TITLE
`trade()`: truncate data at "current date" to avoid lookahead bias in callbacks

### ISSUE THREAD

**Issue by TheJoeSchr** [freqtrade/freqtrade#10218]
> yes - but the point is - dataprovider is available to the stratgy via `self.dp.xxx` - so - if we assume `self.dp.trades()` is used within a callback (for whatever reason) - then this should have "lookahead bias protection" for backtesting (truncate data at "current date") - otherwise i can use a callback (say, `confirm_trade_entry()`) and reject all trades where the price in 1h is not above current price - though in live, that's info i would never be able to have.

If we don't wanna do that for now - i'm fine with a small hint in the docstring saying "this is not meant to be used in callbacks" or similar - to alert users that this is potentially problematic.

_Originally posted by @xmatthias in https://github.com/freqtrade/freqtrade/pull/9066#discussion_r1527189948_

**Comment by xmatthias** [comment]
well i still think that the "docstring hint" will suffice 
it'll alert users about this - and quite honestly - slicing huge dataframes is rather expensive (from a time perspective).

**Comment by TheJoeSchr** [comment]
Just wanted to document it somewhere before it's lost in the PR discussion thread. You can close it if you think it's not relevant

**Comment by xmatthias** [comment]
It's fine - the docstring is fine as is now (docstrings will be visible to users while implementing, too).

There's no need for this explicit issue at this point - if we really see that it's something that will be necessary we can still implement it - but i think the expansiveness of this will make this pretty difficult to do in reality.
