### ISSUE TITLE
Add Python version 3.12 in the setup file

### ISSUE THREAD

**Issue by g3k0** [freqtrade/freqtrade#10220]
## Describe your environment

  * Operating system:  MX Linux 23.2
  * Python Version: 3.12 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

In the setup.sh file add the python version 3.12 to the list of  versions in  `check_installed_python()` function

**Comment by xmatthias** [comment]
I can't even call it an oversight, as it's intentionally not been available for some time - as we were waiting for all dependencies to be compatible.

That's the case now though - so the docker-image was updated already - hence nothing speaks againt updating the setup script, too.
