### ISSUE TITLE
Two strategies on one account

### ISSUE THREAD

**Issue by slowdive42** [freqtrade/freqtrade#10239]
How can I do this. I want to distribute funds between two bots. If there's only one bot signal , I'll allocate all the money to that bot. However, if there are two bot signals, I'd like to split the funds equally between them.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Please take the time to read [through the documentation](https://www.freqtrade.io/). Most questions that will arise will be covered there. This greatly reduces our workload - allowing us to do some actual useful stuff - like improving the bot and documentation.

This includes (but is not limited to) this question - which can be found [here](https://www.freqtrade.io/en/stable/configuration/#assign-available-capital).

**Comment by slowdive42** [comment]
> Please get used to filling out the issue template. Those who frequently omit the template may have their issues closed without comment. We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.
> 
> Filling out the template helps reduce our workload, and we greatly appreciate that.
> 
> Please take the time to read [through the documentation](https://www.freqtrade.io/). Most questions that will arise will be covered there. This greatly reduces our workload - allowing us to do some actual useful stuff - like improving the bot and documentation.
> 
> This includes (but is not limited to) this question - which can be found [here](https://www.freqtrade.io/en/stable/configuration/#assign-available-capital).

Thank you very much! It's possible that I misunderstood the documentation. I apologize for it.
