### ISSUE TITLE
how to express the crossing of the MA5 over the MA10 twice

### ISSUE THREAD

**Issue by gmvp3** [freqtrade/freqtrade#10236]
## Describe your environment
Operating system: ____debian12
Python Version: _____ 3.11.2
CCXT version: _____ 4.3.11
Freqtrade Version: ____ 2024.4
  
## Your question
I need help figuring out how to express the crossing of the MA5 over the MA10 twice in the populate_exit_trend().
Thank you~

**Comment by stash86** [comment]
Well, you need to learn about `.shift()` command of pandas

**Comment by gmvp3** [comment]
I know qtpylib.crossed_above(),
but how to crossed twice in the populate_exit_trend().

**Comment by stash86** [comment]
Is it possible for a line to cross above another line twice in a row?

**Comment by xmatthias** [comment]
Your question is a bit vague i'd say, making it rather difficult to answer.

most likely, it's "crossed within a certain interval" - which i usually accomodate by assigning the result of `qtlib.crossed_*` to a column, and then do a rolling sum over that (`dataframe['crossed_result'].rolling(5).sum()`) - if that sum is >= 2 - then it crossed more than twice.

You'll need to experiment a bit to get what you actually want (which is what we don't actually know) - but in reality, it's just some pandas logic.

**Comment by gmvp3** [comment]
> Your question is a bit vague i'd say, making it rather difficult to answer.
> 
> most likely, it's "crossed within a certain interval" - which i usually accomodate by assigning the result of `qtlib.crossed_*` to a column, and then do a rolling sum over that (`dataframe['crossed_result'].rolling(5).sum()`) - if that sum is >= 2 - then it crossed more than twice.
> 
> You'll need to experiment a bit to get what you actually want (which is what we don't actually know) - but in reality, it's just some pandas logic.

Thank you for your response. Could you please explain how to perform a technical double cross at the start of an order?

**Comment by xmatthias** [comment]
I just did in the above comment.

Please do your own research if you don't understand some things in what was said.
It's very basic pandas logic - which you can probably find with a simple search in the search engine of your preference.

It's also no problem if you have specific questions about this - which does show that
* you did read and tried to understand what was explained
* Did try to do your own research, but had problems to find a particular solution.

However, please understand that implementing your ideas is not a service that we are able to provide.

Thanks for your understanding.

**Comment by gmvp3** [comment]
> I just did in the above comment.
> 
> Please do your own research if you don't understand some things in what was said. It's very basic pandas logic - which you can probably find with a simple search in the search engine of your preference.
> 
> It's also no problem if you have specific questions about this - which does show that
> 
> * you did read and tried to understand what was explained
> * Did try to do your own research, but had problems to find a particular solution.
> 
> However, please understand that implementing your ideas is not a service that we are able to provide.
> 
> Thanks for your understanding.

Got it, thanks！
