### ISSUE TITLE
config futures trading, using spot data in the strategy，No data found for (BTC/USDT:USDT, 5m, spot) in backtesting

### ISSUE THREAD

**Issue by gmvp3** [freqtrade/freqtrade#10234]
## Describe your environment

Operating system: ____debian12
Python Version: _____ 3.11.2
CCXT version: _____ 4.3.11
Freqtrade Version: ____ 2024.4
  
## Your question

I configured Binance futures trading, using spot data in the strategy:

@informative('5m', candle_type='spot')
def populate_indicators_5m(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
    dataframe['sma5'] = ta.SMA(dataframe, timeperiod=5)
    dataframe['sma10'] = ta.SMA(dataframe, timeperiod=10)

However, the backtest keeps throwing errors:
freqtrade.data.dataprovider - INFO - Loading data for BTC/USDT:USDT 5m from 2024-05-01 00:00:00 to 2024-05-20 00:00:00
2024-05-22 00:18:52,262 - freqtrade.data.history.datahandlers.idatahandler - WARNING - No history for BTC/USDT:USDT, spot, 5m found. Use `freqtrade download-data` to download the data
2024-05-22 00:18:52,262 - freqtrade.data.dataprovider - WARNING - No data found for (BTC/USDT:USDT, 5m, spot).

I have already downloaded both futures and spot data.

**Comment by xmatthias** [comment]
Well the bot is correct - `BTC/USDT:USDT` is not a [valid spot pair](https://www.freqtrade.io/en/stable/bot-basics/#pair-naming).

Technically, it'll be treated as a different pair - so specifying "BTC/USDT" will work fine.

If you wanna keep this dynamic, then [the `@informative` documentation](https://www.freqtrade.io/en/latest/strategy-customization/#informative-pairs-decorator-informative) will help you out in configuring this. (should be something around `{base}/{quote}`).


---

It should be noted that it's not guaranteed that ccxt does provide this type of data (data that doesn't correspond to the exchange's initialization).
I know it works  on some exchanges - but i've also seen instances where you'll either not get the correct data - or you'll still get futures data - though labeled for spot pair naming.

That's the main reason this approach is not widely documented - as behavior is not clearly defined (through ccxt) - and we also don't test for this actively - so testing IF this actually works correctly in live mode (you DO get different data) for your exchange is up to the user.
