### ISSUE TITLE
ERROR - No pair in whitelist.

### ISSUE THREAD

**Issue by bsshor** [freqtrade/freqtrade#10230]
Hello! When I try to execute this command：
`docker-compose run --rm freqtrade backtesting   --strategy SimpleMA_strategy -i 15m -p BTC/USDT   --timerange 20230101-20231231   --starting-balance 400 -c ./user_data/learndatasci-config.json`  
， I meet an error, look ,please:
![image](https://github.com/freqtrade/freqtrade/assets/53682007/d88b4c01-a24e-4549-bac4-a89e32fd8818)
 But I think my setting about is siut to the rules, as you can see in bellow, in  futures, I write "BTC/USDT:USDT " into whitelist

 `
{
    "max_open_trades": -1,
    "stake_currency": "USDT",
    "stake_amount": 350,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 100000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
            "BTC/USDT:USDT"
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList"
        }
    ],
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "fc3439cc2e0e4402afc0221fb5fd6733c36f7f39875934673b03866337da0fdb",
        "ws_token": "SJOtfyBWX1Pqt_3Ngd3Zi5fxwQozKz94sg",
        "CORS_origins": [],
        "username": "test",
        "password": "112233445566778899"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}`
Can you help me?

**Comment by Hassffw** [comment]
check this path: 
![image](https://github.com/freqtrade/freqtrade/assets/88439310/e15b9d9a-fcb2-4cf9-a59b-a4d06014d713)

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Your pairs must correspond to your markets.

We have an explanation about this in the [documentation](https://www.freqtrade.io/en/latest/bot-basics/#pair-naming).

essentially - BTC/USDT is invalid for futures markets. 
Your logs (next time, please use text, not screenshots) show that you've configured BTC/USDT - not BTC/USDT:USDT - which means that either, you didn't save the configuration file - or the configuration file is not the one you're using.

**Comment by bsshor** [comment]
> 请习惯于填写问题模板。那些经常省略模板的人可能会在不加评论的情况下关闭他们的问题。我们提出了一些非常基本的问题 - 通过删除问题模板，您明确选择不回答我们的问题。
> 
> 填写模板有助于减少我们的工作量，我们非常感谢。
> 
> 您的货币对必须与您的市场相对应。
> 
> [我们在文档](https://www.freqtrade.io/en/latest/bot-basics/#pair-naming)中对此进行了解释。
> 
> 本质上 - BTC/USDT 对期货市场无效。您的日志（下次请使用文本，而不是屏幕截图）显示您配置了 BTC/USDT，而不是 BTC/USDT：USDT，这意味着您没有保存配置文件 - 或者配置文件不是您正在使用的配置文件。

I can confirm that freqtrade does read my custom config file. Because I changed the exchange to htx, binance, okx and saved it, then when I executed the backtest command, the log outputs the htx, binance, okx fields in order.
But I also noticed that the log outputs the pair as ‘BTC/USDT’ instead of ‘BTC/USDT:USDT’ as I wrote in my custom configuration, which confuses me

**Comment by xmatthias** [comment]
Well it shouldn't - your command does include it (`-p BTC/USDT `).

CLI arguments will always overwrite configuration or strategy settings.

**Comment by bsshor** [comment]
> Well it shouldn't - your command does include it (`-p BTC/USDT `).
> 
> CLI arguments will always overwrite configuration or strategy settings.

！！okok，I understand. and I fixed it, thank all of you very much!! now I‘m contunuing.
