### ISSUE TITLE
bitmart download-data"message":"request step is invalid","data":null}"

### ISSUE THREAD

**Issue by hippocritical** [freqtrade/freqtrade#10248]
## Describe your environment

  * Operating system: ubuntu 22.04.4 LTS
  * Python Version: 3.10.12 (`python -V`)
  * CCXT version: 4.3.11 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.4 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*
when downloading data for bitmart, this error happens (as an example, for full logs see the attached log file):
2024-05-26 11:17:31,814 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair BTC/USDT due to BadRequest. Message: bitmart {"code":71005,"trace":"8276d32a2a3b42a2a234141f1c9765c4.96.17167222517533403","message":"request step is invalid","data":null}". Retrying still for 4 times.

### Steps to reproduce:

  1. install freqtrade as usual
  2. launch the usual download-data command
  3. get errors on every pair + timeframe

Here the one of the commands that is used, which is successful for other exchanges:
(the command was simplified, configs are not provided since they are not the issue - the issue is the download itself)
freqtrade download-data --config=./user_data/configs_backtest/config_baseline.json --config=./user_data/pairlists/bitmart_spot/USDT/monthly/monthly_90_USDT_0,0_minprice_20240401.json --config=./user_data/configs_backtest/config_ccxt100.json --timeframes 3h 1m 45m 30m 15m 1h 1d 3m 1w 1M 5m 2h 4h --timerange=20240302-20240501
  
### Observed Results:

  * What happened?
download failed
  * What did you expect to happen?
being able to download

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

**Comment by xmatthias** [comment]
> Here the one of the commands that is used, which is successful for other exchanges:

i doubt that's true, as i don't think many exchanges will have timeframes like 3h.

As you seem to test several exchanges, please, **before** opening an issue, try to drill it down to a **minimal ** command (which timeframes does it happen, ...).

A command with "all" timeframes will not really help - as it's more than questionable that you'll have this failing on ALL timeframes (hint: it's not).

---

Now drilling into this - it's quickly noticable that the [bitmart api docs](https://developer-pro.bitmart.com/en/spot/#get-latest-k-line-v3) is wrong.

Step is documented as follows (which also corresponds to what list-timeframes outputs).

> k-line step, value [1, 3, 5, 15, 30, 45, 60, 120, 180, 240, 1440, 10080, 43200] unit: minute, default 1

API requests like `https://api-cloud.bitmart.com/spot/quotation/v3/klines?symbol=ETH_USDT&step=5` do work - while `https://api-cloud.bitmart.com/spot/quotation/v3/klines?symbol=ETH_USDT&step=3` fail with the above mentioned error.


So simply put - it's a question of "the API docs are wrong.
you can't even say ccxt is wrong (which would justify an issue against ccxt) - as their timeframes list does correspond to what bitmart documents.

If you'd like to see this fixed, then the correct way to go is:
* open an issue against bitmart support - asking why it ain't working despite being documented (which will lead to either an explanation, or a fix in the docs).
* With the information you get there - open an issue against ccxt having them fix the "timeframes" property for bitmart.

Currently however - i don't see ccxt adjusting it (i wouldn't) - as their implementation corresponds to the documentation.


As a workaround - you can exclude all "odd" timeframes - and you'll see that data-download will work just fine.

From a freqtrade perspective however, there's nothing we can do for this case.
you use it as documented by the bitmart API - just the API ain't working as documented - which is not something we'll try to work around by maintaining our own lists.

**Comment by hippocritical** [comment]
made a ticket to bitmart, will keep you posted.
after removing 3m and 45m for good measure, this works now.
