### ISSUE TITLE
htx download-data bad request history kline query invalid from to

### ISSUE THREAD

**Issue by hippocritical** [freqtrade/freqtrade#10247]
## Describe your environment

  * Operating system: ubuntu 22.04.4 LTS
  * Python Version: 3.10.12 (`python -V`)
  * CCXT version: 4.3.11 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.4 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*
when downloading data for htx, the error happens: history kline query with invalid from to ... resulting in a 0 length download

### Steps to reproduce:

  1. install freqtrade as usual
  2. launch the usual download-data command
  3. get errors on every pair + timeframe

Here the one of the commands that is used, which is successful for other exchanges:
(the command was simplified, configs are not provided since they are not the issue - the issue is the download itself)
freqtrade download-data --config=./user_data/configs_backtest/config_baseline.json --config=./user_data/pairlists/htx_spot/USDT/monthly/monthly_90_USDT_0,0_minprice_20240401.json --config=./user_data/configs_backtest/config_ccxt100.json --timeframes 5m 8h 1d 30m 1h 7d 15m 2h 1m 1w 4h --timerange=20240302-20240501
  
### Observed Results:

  * What happened?
download failed
  * What did you expect to happen?
being able to download

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.
[output_downloader_htx_spot_USDT.txt](https://github.com/freqtrade/freqtrade/files/15447523/output_downloader_htx_spot_USDT.txt)

**Comment by xmatthias** [comment]
Well it's only happening on 1w and up.

A few (manual) tests would make it seem that their [documentation](https://www.htx.com/en-us/opend/newApiPages/?id=7ec4a4da-7773-11ed-9966-0242ac110003) is kinda wrong - as they claim to support size between 1 and 2000 ... but for these timeframes - values of more than ~620 fail (interestingly, only on 1w and 1M timeframes).

I'd recommend to get in touch with HTX support regarding this - as we're using their API as documented - though it's failing, which either means that the docs are incomplete - or that you found a bug in their API.
