### ISSUE TITLE
New actions for FreqAI's RL environment

### ISSUE THREAD

**Issue by szucsaaron2** [freqtrade/freqtrade#10240]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*

Hey, great and high quality work so far!
I wonder how could one implement partial trades for the RL environment. What I mean is for example the agent would have more control about how much it invests, and not only Buying with 100% of the capital and Selling with 100% of the capital. I think something like this could increase the agent's performance as it would potentially enable it to learn strategies such as "doubling down" etc. I am aware that adding really fine control (1%, 2%, 3%, 4%, 5%, ... , 100%) would increase the complexity of the environment tremendously, but for example it could also only have something like (10%, 20%, 100%) for both buy and sell. I actually also tried implementing this myself, but I had challanges implementing the profit tracking. For example if the agent buys 20% first, at tick 100, and buys another 20% at tick 110, it would first have to keep track of the profit earned on the this first period with 20% of the capital, and then calculate profits based on the next trading ticks. Any idea on how to implement this correctly?

Thank you!

**Comment by richardjozsa** [comment]
Hey Aron, 

this is possible with some coding in the env, but this is a special case of use. The default environments and actions and even the algorithms what you can use are showcases, show you how to deal with the problems coming up. They have been designed to be basic, but anything is possible which can be coded in python. you need to tweak some default function approximately 3 -8 hours of work once you understand the minimal constraints of the environment and your data what is there.

If you wanna differentiate from the original profit calculation than tweak the pnl calculation function, you can use many ways to track your profit. we assumed two basic scenario when it was designed, fixed position size, or unlimited a.k.a  basically compounded profit. When the agent enters in the original environment it uses a basic pnl calculation in both case. If you wanna do doubling down you need to track where your agent entered the first trade than the second(two class variable). BUT to do this, you wanna have different states for each and different actions, unless you just confuse your agent.

GLHF

**Comment by szucsaaron2** [comment]
@richardjozsa Köszi megvan ;)
