### ISSUE TITLE
FullTradesFilter for DCA strategies

### ISSUE THREAD

**Issue by fawazx** [freqtrade/freqtrade#10250]
Hello,

FullTradesFilter is great in saving CPU and speeding up the bot by shrinking the whitelist when the trade slots are full. However, it doesn't work with DCA strategies because most of the time the trade slots are less than max_open_trades because most of funds are used for DCA positions. 

I suggest adding another condition to shrink the whitelist to in-trade pairs when the trade slots are full OR remaining stake is less than the minimum stake amount.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---


I don't really see that happening if i'm honest (for multiple reasons).

minimum stake amount is something that's VERY dynamic - you can have a pair with 5$ minimum stake - and another pair just next it with a minimum stake of 40$.
The difference between the two is that the 2nd had it's price recently spiked - and the exchange didn't adjust the minimum stake yet.

My point is however - there is no "minimum stake" per se - as it's per pair.

**Comment by fawazx** [comment]
Thank you

**Comment by stash86** [comment]
Just want to add that you should calculate the required money and initial stake in precise way to make sure each trading slot will have their own money to trade. So let's say if you have 6 max trading slots, you must give the bot enough money so that it can have 6 open trades where all of them can DCA to the max without fear of having no money to trade.
