### ISSUE TITLE
Failed to load data - FreqUI - 

### ISSUE THREAD

**Issue by PiotrJuzwiak** [freqtrade/freqtrade#10262]
## Describe your environment

  * Operating system: Pop OS 22.04
  * Python Version: 3.10 (`python -V`)
  * CCXT version: ccxt==4.2.25(`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
If the strategy takes a long time to generated dataframe, I get "Failed to load data" in the "Visualise result" "tab"
*Explain the problem you have encountered*
As above
### Steps to reproduce:

  1. Have a strategy that runs for I think at least 1 minute in the "Visualise result" tab after running backtesting on FreqUI
  2. 
  
### Observed Results:

  * What happened?
  Plot will not generate and I will get message "Failed to load data"
  * What did you expect to happen?
  I'd expect it to wait until the dataframe is generated and ready to display
### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
Well the timeout for this is currently 50s - and is intentionally there.

i guess it'll depend a bit on your timerange, too - but if your strategy takes >1m to call all `populate_*` methods (the call made here is not triggering any callbacks) - then i doubt your strategy will have "timely" entries.

I guess it'd be acceptable to some degree on 1h+ timeframes - but there, i again doubt that you CAN get such times - as you'll not have THAT many candles even available.

While i don't necessarily mind updating this to something slightly higher - it's really an arbitrary limit - which however also means that people will eventually need to wait for it.

**Comment by xmatthias** [comment]
increased the timeout a bit in d593b04e235ab0e608fae040d7e78bfc644e144f.
