### ISSUE TITLE
Static stop loss based on EnterTag and pair

### ISSUE THREAD

**Issue by thkwon9474** [freqtrade/freqtrade#10263]
## Describe your environment
Operating system: Ubuntu 22.04.2 LTS(docker)
Python Version: python 3.11.7
CCXT version: 4.0.71
Freqtrade Version: freqtrade 2024.04

## Your question
Hi!

Is there a way to set a static stop loss based on Pair or Enter_Tag?

I would like to inquire because custom stoploss only operates as a trailing stoploss.

**Comment by stash86** [comment]
You can use custom_exit for static exit

**Comment by xmatthias** [comment]
>I would like to inquire because custom stoploss only operates as a trailing stoploss.

This is not true - and will depend Solely on your implementation.
It's trailing if you always return a value - but you return None - and the existing stoploss will not be touched.


If you implement the [after_fill](https://www.freqtrade.io/en/latest/strategy-callbacks/#adjust-stoploss-after-position-adjustments) parameter in the function header and explicitly check for this (returning None in all other cases) - then you'll only be setting the stoploss once (per filled entry).
You can pretty easily add additional conditions to avoid these additional changes if you're using DCA, too.

This call will also happen "early" - allowing you to set the stoploss immediately.

**Comment by stash86** [comment]
You can also use the available `stoploss_from_open` or `stoploss_from_absolute` function in custom_stoploss if you don't want trailing stoploss
