### ISSUE TITLE
Inconsistent results between backtest and paper trade despite following best practices

### ISSUE THREAD

**Issue by GabrielBertoli** [freqtrade/freqtrade#10272]
## Describe your environment

  * Operating system: mac os
  * Python Version: Python 3.11.9 (`python -V`)
  * CCXT version: ccxt==4.3.21 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2024.4
 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Dear Xmatthias,

I've been evaluating the freqtrade platform extensively over the past 3 months. I must say, I am extremely impressed by how powerful and feature-rich it is. The amount of work and dedication that has gone into developing and maintaining freqtrade is truly commendable. I want to sincerely thank you and the entire freqtrade community for your efforts in creating such a valuable open-source tool for crypto trading.

As I prepare to deploy freqtrade in a production environment, there is one question I was hoping you could provide some guidance on. I've noticed that when I run a strategy in backtest mode and then test that same strategy with paper trading, the results differ quite significantly. It's not just a matter of the overall performance being different, but even the number of trades executed varies between backtest and paper trade modes. The results seem too disparate to be attributed to normal market fluctuations.

I have been using the recommended settings for backtesting, such as `--timeframe-detail 5m`. Additionally, I have carefully reviewed the backtesting assumptions and have made sure to avoid the common strategy mistakes outlined in the documentation. Despite following these guidelines, I still can't understand why the results are never the same when I run the strategy in real-time.

I was wondering if you have any insights into why this might be happening and how I can troubleshoot the issue to achieve more consistent results between backtest and paper trade? Any suggestions or best practices you can share would be greatly appreciated. 

Thank you again for your work on freqtrade and for taking the time to assist me. I look forward to your response.

Best regards,
Gabriel

**Comment by xmatthias** [comment]
well first off -  past performance is never a guarantee for future performance.

It's also a bit vague to give you anything to really go further.

are you getting fewer signals - or fewer trades?

While the first is a pretty clear signal that your strategy has a lookahead bias (signals don't trigger at the most recent candle, but will only "appear" at a later date - once the lookahead period passed) - the latter is often simple execution - are you getting tons of canceled orders in your paper trading (play with pricing settings ...).

**Comment by GabrielBertoli** [comment]
Hi Xmatthias,
Thank you for your prompt and insightful response. Your explanation of the discrepancies between backtesting and paper trading results is much appreciated.
Today, I noticed a striking example of this issue. My strategy showed 21 trades when backtested for May 31st, but executed zero trades in paper trading mode. I believe this particular case may be due to limited funds, as my "max_open_trades" is set to 15, but it only opened 3-4 positions before indicating insufficient funds. However, I consistently see fewer trades in paper trading compared to back-testing, even if less dramatic than today.

Additional info: my strategy is build on SMA.
here is part of my config data
{
    "max_open_trades": 15,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "leverage": true,
    "dry_run_wallet": 10000,
    "db_url": "sqlite:///futurecaps1.sqlite",
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
      "entry": 10,
      "exit": 10,
      "exit_timeout_count": 0,
      "unit": "minutes"
    },
    "entry_pricing": {
      "price_side": "same",
      "use_order_book": true,
      "order_book_top": 1,
      "price_last_balance": 0.0,
      "check_depth_of_market": {
        "enabled": false,
        "bids_to_ask_delta": 1
      }
    },
    "exit_pricing": {
      "price_side": "same",
      "use_order_book": true,
      "order_book_top": 1
    },
    "order_types": {
      "timeframe": "1h",
      "entry": "limit",
      "exit": "limit",
      "emergency_exit": "market",
      "force_exit": "market",
      "force_entry": "market",
      "stoploss": "market",
      "stoploss_on_exchange": true,
      "stoploss_on_exchange_interval": 60
  },

Thank you again for sharing your knowledge and for your dedication to Freqtrade.
Gabriel
