### ISSUE TITLE
How to get current pair name in strategy file so i could use it to get informative dataframe for same and only this pair?

### ISSUE THREAD

**Issue by MrGalacticClouds** [freqtrade/freqtrade#10293]
## Describe your environment

  * Operating system: Linux Mint 21.3
  * Python Version: 3.10.12 
  * CCXT version: 4.2.79 
  * Freqtrade Version: 2024.2 
  
## Your question

Hi. Question as in the topic.
How to get current pair name in strategy file so i could use it to get informative dataframe for same and only this pair?

So i know that i can do this.

```
informative = self.dp.get_pair_dataframe(pair=f"BTC/USDT",
                                                     timeframe=inf_tf)
```
But what can I do to get current tested/used pair and use it insted of _pair=f"BTC/USDT"_ ?

```
currentpair = ____ ????
informative = self.dp.get_pair_dataframe(pair = currentpair,
                                                     timeframe=inf_tf)
```

I couldnt find answer. There is a possible that it is in documentation or its just obvious for python users but still didnt know what to ask in search to get it :/
Please help, thank You :)

**Comment by xmatthias** [comment]
You can use [`metadata['pair']`](https://www.freqtrade.io/en/stable/strategy-customization/#metadata-dict) to get the current pair name.

For your particular usecase - using the [`@informative`](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs-decorator-informative) decorator is even easier - if you don't provide the pair (just the timeframe) - it'll default to the current pair automatically.

**Comment by MrGalacticClouds** [comment]
Got it, work as it should.
Thank You again :)
