### ISSUE TITLE
how could I get a cross section of coins

### ISSUE THREAD

**Issue by hahau6** [freqtrade/freqtrade#10291]
## Describe your environment

  * Operating system: ____win10
  * Python Version: __3.11___ (`python -V`)
  * CCXT version: ___4.3.38__ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __2024.5__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

What do I do if I want to get the maximum and minimum values of momentum for all currencies at a given time, the crosssection of coins.  Thank you

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

well a dataframe is just pandas - so you can use something like `dataframe['somevalue'].rolling(<somevalue>).max()` (and corresponding min) to get the min/max within a certain interval.

**Comment by hahau6** [comment]
In  populate_indicators (self, dataframe: DataFrame, metadata: dict) ,the dataframe only has one coin information one time, but  I want to get the max or min value  cross all coins at a given time.

for example, I want to select the max or min momentum coin from all coins at a given time.

**Comment by xmatthias** [comment]
well you can use [informative pairs](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs) for this - though not through the decorator.

essentially,you'll want to loop [`self.dp.current_whitelist()` ](https://www.freqtrade.io/en/stable/strategy-customization/#current_whitelist) - and combine that with [`self.dp.get_pair_dataframe(pair=inf_pair, timeframe=self.timeframe)`](https://www.freqtrade.io/en/stable/strategy-customization/#get_pair_dataframepair-timeframe) - which will get you access to all pairs.

How you'll then combine the data for all pairs - i'll leave up to you - but most likely, you'll pick one column (close?) - and put it all into one dataframe that contains all pairs as columns.

**Comment by hahau6** [comment]
for example, I want to get the VolumeMean indicator ,  and then  rank the meanVolumn of  all coins  at each loop. Finally,  select the 20% to trade at each loop .  How could I send this information for finally buy/sell descion  in backtesting and live?

 the VolumeMeanindicator:
    df["VolumeMean "] = df['quote_volume'].rolling(n, min_periods=1).mean()

select the 20%
    all_coins_df['filter_rank'] =groupby('candle_time')["VolumeMean"].rank(ascending=True, pct=True)
    all_coins_df= all_coins_df[(all_coins_df['filter_rank'] > 0.8)]

**Comment by xmatthias** [comment]
My comment above includes all information necessary - with a bit of pandas knowledge (or the will to learn it).

Writing the code for you based on how you'd like to have it is however not a service we're offering.
Thanks for your understanding.
