### ISSUE TITLE
Error in freqai_interface.py -- IndexError: deque index out of range

### ISSUE THREAD

**Issue by Johan1974** [freqtrade/freqtrade#10290]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: 3.12.3 
  * CCXT version: 4.3.35 
  * Freqtrade Version: 2024.5 
  * Docker version 20.10.24+dfsg1, build 297e128
  * docker-compose version 1.29.2, build unknown
  * image: freqtradeorg/freqtrade:stable_freqaitorch

## Your question

I'm encountering an issue with my Freqtrade setup and need assistance in resolving it. In my trading bot, I'm consistently receiving the following error:

```
Exception in thread Thread-2 (_start_scanning):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 222, in _start_scanning
    pair = self.train_queue[0]
           ~~~~~~~~~~~~~~~~^^^
IndexError: deque index out of range
```

I've checked the documentation but couldn't find a solution. Could you please provide guidance on how to resolve this issue?

**Comment by robcaulk** [comment]
Is this a common pitfall? 

https://www.freqtrade.io/en/latest/freqai/#common-pitfalls

**Comment by Johan1974** [comment]
Hello Rob,

I read the article your pointing to but i do not see the difference between a dynamic or a constant VolumePairListpairlist. 

At the moment i have the following, how do i make this constant as mentioned in the artcle.

"pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 10,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        },
        {
            "method": "AgeFilter",
            "min_days_listed": 30
       },
       {
            "method": "RangeStabilityFilter",
            "lookback_days": 10,
            "min_rate_of_change": 0.01,
            "max_rate_of_change": 0.99,
            "refresh_period": 1440
       }
    ],

**Comment by stash86** [comment]
Use StaticPairlist

**Comment by Johan1974** [comment]
Yes that seems the correct way at the end but this is not what the help is telling me. 

`However, FreqAI does work with the ShufflePairlist or a VolumePairlist which keeps the total pairlist constant (but reorders the pairs according to volume).`

So i would like to understand correctly what is meant bij the last line in the help file.

**Comment by stash86** [comment]
https://www.freqtrade.io/en/stable/plugins/#volume-pair-list

**Comment by xmatthias** [comment]
Essentially it means - you can use `VolumePairlist` - but in "sort" mode  (where it's not the first item in the list) - and has `number_assets > number of pairs`.
Pair positions can change within the pairlist - but swapping pairs with different pairs does not work.


The way you're using it, you get the top 10 pairs based on volume.
This means it can be 10 pairs today - but different pairs tomorrow - as positions 8 and 9 changed - which is not supported by freqAI, as it changes which pairs are in the pairlist.
