### ISSUE TITLE
Backtesting for futures trade

### ISSUE THREAD

**Issue by ai0learner** [freqtrade/freqtrade#10292]
## Describe your environment
(if applicable)

  * Operating system: macOS
  * Python Version: 3.9 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

Backtesting for futures trade. Backtesting works for spot trading but not for futures.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Based on the provided details - i'm VERY tempted to simply close this with "backtesting futures works for me".

I really don't understand how you would expect us to help you find your problem if you're not providing _any_ details besides "it doesn't work".

Please provide as much details as possible (essentially, the configuration you're using (make sure to remove private info like exchange keys) - as well as logs - and why you think it's not working.

**Comment by ai0learner** [comment]
Hi,

Thank you so much for your prompt response. Sorry I am a bit new to this field. 

When I set

"trading_mode": "futures",
"margin_mode": "isolated",

the pairs in pair_whitelist doesn't get detected anymore, and I can't download history data. I think that's why futures backtesting doesn't work. 

It works well without any issues when I just do dry-run 

Thank you so much for all of your work.

**Comment by stash86** [comment]
https://www.freqtrade.io/en/stable/leverage/#pair-namings

**Comment by ai0learner** [comment]
OK so the format is different when downloading the previous data history (different from dry run). I wonder if there is any reasoning behind it but it solved the problem. Thanks!

**Comment by xmatthias** [comment]
well it's a different pair - one that has a settlement currency, too.
in the end, the naming comes off of how ccxt names it - we're just adapting that same naming, as it saves us a lot of problems in name translation.
