### ISSUE TITLE
Spot Margin account on Binance

### ISSUE THREAD

**Issue by GabrielBertoli** [freqtrade/freqtrade#10313]
## Describe your environment

  * Operating system: mac os
  * Python Version: Python 3.11.9 
  * CCXT version: ccxt==4.3.21 
  * Freqtrade Version: freqtrade 2024.4 
  
## Your question

Hi,

I was wondering if it is possible to access my Spot Margin account on Binance in order to do Spot Margin trading? To clarify, I'm not asking about doing Spot Margin trading in a regular Spot account, but rather using Spot in my existing Margin account. 

Please let me know if this is feasible and if there are any specific steps I need to take to enable Spot Margin trading functionality within my Margin account.

Thanks for your help!
Gabriel

**Comment by froggleston** [comment]
No, this is not currently possible.

**Comment by GabrielBertoli** [comment]
Ok thank you
