### ISSUE TITLE
Hope to provide a method for Futures grid trading.

### ISSUE THREAD

**Issue by gmvp3** [freqtrade/freqtrade#10310]
Currently, only OKX has an API for grid trading, other exchanges do not. Hope to provide a simple method, thank you.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Freqtrade's logic is solely based on your strategy - which is not something that will change.
You can replicate the logic for a grid-trading bot already - though the "how" is up to you, really.
if your strategy determines prices, and once current price goes near one of these prices, it places an order (and cancels it if price moves away again without the order filling) - you've got a grid trading bot.

One thing to keep in mind is that freqtrade will currently only have one open order at any time. 

While there is an issue for that - #10074 - that's not something that's planned to be implemented anytime soon - but it's also not something that's limiting you greatly if you're using callbacks cleverly.
