### ISSUE TITLE
Different values in decorative informative populate_indicators

### ISSUE THREAD

**Issue by Debeet** [freqtrade/freqtrade#10338]
## Describe your environment

  * Operating system: Docker Image
  * Python Version: 3.12.3 (`python -V`)
  * CCXT version: 4.3.35 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.5 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the problem:

During my backtesting and hyperopting I've noticed that informative decorative populate_indicators() gives me different results for pct_change() than if I get it outside the decorative. This code should explain it better:

```
    @informative('1h', 'BTC/USDT')
    def populate_indicators_btc_1h(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['pct_change'] = dataframe['close'].pct_change(periods=1)
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        print(dataframe['btc_usdt_close_1h'].pct_change(periods=1))
        print(dataframe['btc_usdt_pct_change_1h'])
```

Here's what it prints:

```
Name: btc_usdt_close_1h, Length: 6567, dtype: float64
0            NaN
1            NaN
2            NaN
3       0.001974
4       0.001974
          ...   
6562    0.001133
6563    0.001133
6564    0.001133
6565    0.001133
6566    0.001133
Name: btc_usdt_pct_change_1h, Length: 6567, dtype: float64
0       NaN
1       NaN
2       NaN
3       NaN
4       0.0
       ... 
6562    0.0
6563    0.0
6564    0.0
6565    0.0
6566    0.0
```

Shouldn't these values be the same regardless from where I get this data?

**Comment by stash86** [comment]
No it shouldn't be the same

https://botacademy.ddns.net/2023/07/27/how-dataframe-looked-like-after-merging-informative-data/

**Comment by Debeet** [comment]
Thanks!
