### ISSUE TITLE
The predicted closing price deviates from the actual closing price for the cryptocurrency Bitcoin.

### ISSUE THREAD

**Issue by LeQuocViet02** [freqtrade/freqtrade#10339]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: 3.9 (`python -V`)
  * CCXT version: 4.3.35(`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.5 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I am having issues with the LightGBMRegressor model as its predictions for future closing prices are significantly different from the actual closing prices. Do you have any suggestions for improving the model to enhance the accuracy of the predicted closing prices?
Thank you very much.

**Comment by robcaulk** [comment]
Well, that would depend entirely on your targets that you created.
