### ISSUE TITLE
No pairs available for download.

### ISSUE THREAD

**Issue by quancntt05** [freqtrade/freqtrade#10332]
## Describe your environment

  * Operating system: Docker for window
  * Freqtrade Version: 2024.5
  
## Your question
I faced an issue when follow the document https://www.freqtrade.io/en/stable/docker_quickstart/#example-download-data-with-docker
![Screenshot_6](https://github.com/freqtrade/freqtrade/assets/34080595/df378f45-dad5-415a-9349-a9f51214324c)
Please help me check. Thank you so much

**Comment by stash86** [comment]
Have you read the link given in the last line?

**Comment by xmatthias** [comment]
Please do read the output. 
posting the link again here for clarity: https://www.freqtrade.io/en/stable/bot-basics/#pair-naming

In short: your spot pair naming doesn't work for futures markets.
