### ISSUE TITLE
Is multiple entries possible for each pair?

### ISSUE THREAD

**Issue by JuhanKimSeoul** [freqtrade/freqtrade#10345]
## Describe your environment

  * Operating system: linux
  * Python Version: 3.9.5
  * CCXT version: 4.3.11
  * Freqtrade Version: 2024.4
  
## My Configuration

{
    "timeframe": "15m",
    "max_open_trades": 3,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 10000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "trailing_stop": true,
    "trailing_stop_positive": 0.049,
    "trailing_stop_positive_offset": 0.05,
    "trailing_only_offset_is_reached": true,
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
            "BTC/USDT:USDT"
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList"
        }
    ],
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": false,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "",
        "ws_token": "",
        "CORS_origins": [],
        "username": "",
        "password": ""
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
  
## Your question

I would like to use a average-down strategy, that is, trading every time an entry signal appears for one pair. Is this possible with the current framework structure? As a result of backtesting using the sample strategy with the above configuration, even though the long signal appeared twice in a row, no transactions were made twice, and no trading occurred for the signal.

![image](https://github.com/freqtrade/freqtrade/assets/128209402/e4c29aeb-3c46-424c-b49d-3e70bbccec75)
You can see that the bot ignores the long entry signal after I did open a trade even though the max_open_trades is more than 1.

**Comment by stash86** [comment]
What you need is this https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position
