### ISSUE TITLE
how to get active pair in bot_loop_start?

### ISSUE THREAD

**Issue by uplight-dev** [freqtrade/freqtrade#10347]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

As per title.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

There is no "active pair" at the point of `bot_loop_start()`.
It's a callback that runs before we drop into pair context - once per loop, not once per pair.

If you mean getting the active pairlist - then [current_whitelist](https://www.freqtrade.io/en/stable/strategy-customization/#current_whitelist) will work just as in every other method.

**Comment by uplight-dev** [comment]
Thank you for all your previous answers, highly appreciated.
For the template filing, I thought my questions weren't specific to any version but rather more generic in their nature. Normally if it were a bug or similar, I'd surely fill it in as it is useful.
