### ISSUE TITLE
Option to disable/hide the "objective has been evaluated at this point before" message

### ISSUE THREAD

**Issue by Debeet** [freqtrade/freqtrade#10351]
## Describe your environment

  * Operating system: Docker Image
  * Python Version: 3.12.3 (`python -V`)
  * CCXT version: 4.3.35 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.5 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

Is there an option to hide the "objective has been evaluated at this point before" message in hyperopt? I know it's an information that it probably is stuck in the local minima and/or there's nothing left to test for but many times it gets unstuck and presents better results. At this time the log is flooded with these messages and I need to scroll a lot to find out what was the best result. Thanks in advance.

**Comment by xmatthias** [comment]
No there is not.
It's also not a message freqtrade is showing - but a a sublibrary (don't remember if it's scikit-optimize, or scikit-learn itself).

Trying to hide that from freqtrade's perspective would be messing with internals - which we'll clearly not be going into.

**Comment by macsim26** [comment]
Hello you can disable it by adding this in your strategy just after all the other imports:

import warnings

def filter_warning(message, category, filename, lineno, file=None, line=None):
    if "The objective has been evaluated at this point before." in str(message):
        return None
warnings.showwarning = filter_warning

**Comment by froggleston** [comment]
You can use the hyperopt helper commands to print out results, including the best. No need to scroll back through the output - https://www.freqtrade.io/en/stable/utils/#show-details-of-hyperopt-results
