### ISSUE TITLE
backtesting and producer/consumers

### ISSUE THREAD

**Issue by uplight-dev** [freqtrade/freqtrade#10359]
## Describe your environment

  * Operating system: __Linux__
  * Python Version: __3.12.3___ (`python -V`)
  * CCXT version: __ccxt==4.3.11___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade 2024.4__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

1. In backtesting mode, is there any possibility to use producer/consumer dataframes? For some reason they're only populated in trade mode.

2. And also, in trade mode, if I have producer at timeframe=1w and consumer at timeframe=5m, the consumer doesn't see any producer data. I have set FFill = True and also tried dataframe = dataframe.ffill(). Doesn't seem to work.
Only if I change producer to 4h or similar, I can see further back in time enough to see producer's data.

Thank you!

**Comment by stash86** [comment]
1. No
2. You need to understand candle timestamp. 1w and 5m candles are too wide of a gap, your 5m timeframe won't ever reach 1w worth of data

**Comment by uplight-dev** [comment]
Ok, then I guess what remains to ask is why does the 1w bot only show results up to 10 june 2024. 
There is 17 june also possible but in Trade mode it only goes up to 10 june?

**Comment by stash86** [comment]
Because the 17 june 1w candle hasn't closed yey

https://botacademy.ddns.net/2023/10/14/misconception-about-candles-timestamp/
