### ISSUE TITLE
Is it possible to close and open new position on same pair in one candle? (change direction of position)

### ISSUE THREAD

**Issue by decado87** [freqtrade/freqtrade#10355]
## Describe your environment

  * Operating system: mac OS Sonoma 14.5
  * Python Version: 3.10.10
  * CCXT version: 4.3.42
  * Freqtrade Version: 2024.6-dev-03d2d5dc5
  
## Your question

Hellou, sorry if it was answered but didn't find solution. Is it possible to immediately change position? From long (close long) to short (open short) in one 'candle'  on same pair if some condition is fulfilled? Thanks for your answer

**Comment by xmatthias** [comment]
Nope, that's not possible.

Obviously, it's been asked (and answered) before (#9817, #8966 #6666 #5680) - with most containing some extended rationale as to why.
