### ISSUE TITLE
DataFrame truncated to 1 row after changing stake amount of FreqAI strategy

### ISSUE THREAD

**Issue by monkeyden** [freqtrade/freqtrade#10371]
## Describe your environment

  * Operating system: Ubuntu 22.04.1 LTS (WSL)
  * Python Version: 3.10.12
  * CCXT version: 4.3.35
  * Freqtrade Version: 2024.5
  
## Describe the problem:
After successfully training and backtesting, backtesting a second time without making any changes works correctly.

If you make any changes (even non-FreqAI changes), the historical df gets truncated and backtesting may not complete successfully, depending on what features you are using.

### Steps to reproduce:
The strategy below adds Fast Fourier Transform, which relies on number of rows to be >= n_components.

1. Train the below strategy using the provided config
freqtrade backtesting -s MissingDataStrategy -c user_data/strategies/config/bybit/MissingDataStrategy.json --freqaimodel LightGBMRegressor --timerange 20230610-20240610

2. After successful training and first backtesting, rerun backtesting to observe a successful run.

3. Change stake amount from 100 to 200 in your configuration and rerun backtesting.  Observe a failed backtest.

## config.json
``` jsonc
{
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "max_open_trades": 5,
    "stake_currency": "USDT",
    "stake_amount": 100,
    "tradable_balance_ratio": 1,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "timeframe": "3m",
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": true,
    "unfilledtimeout": {
        "entry": 10,
        "exit": 30
    },
    "exchange": {
        "name": "bybit",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [                        
            "BTC/USDT:USDT"
        ],
        "pair_blacklist": []
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing": {
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1
    },
    "pairlists": [
        {
            "method": "StaticPairList"
        }
    ],
    "freqai": {
        "enabled": true,
        "purge_old_models": 2,
        "train_period_days": 30,
        "backtest_period_days": 7,
        "live_retrain_hours": 0,
        "identifier": "MissingDataStrategy",
        "feature_parameters": {
            "include_timeframes": [
                "3m",
                "15m",
                "1h"
            ],
            "include_corr_pairlist": [
                
            ],
            "label_period_candles": 20,
            "include_shifted_candles": 2,
            "DI_threshold": 0.9,
            "weight_factor": 0.9,
            "principal_component_analysis": false,
            "use_SVM_to_remove_outliers": true,
            "indicator_periods_candles": [
                10,
                20
            ],
            "plot_feature_importances": 0
        },
        "data_split_parameters": {
            "test_size": 0.33,
            "random_state": 1
        },
        "model_training_parameters": {
            "n_jobs": 10,
            "verbosity": 1,
            "device": "cpu"
        }
    },
    "telegram": {
        "enabled": true,
        "token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "chat_id": "XXXXXX",
        "allow_custom_messages": true,
        "notification_settings": {
            "status": "on",
            "warning": "on",
            "startup": "off",
            "entry": "on",
            "entry_fill": "on",
            "entry_cancel": "silent",
            "exit": {
                "roi": "silent",
                "emergency_exit": "on",
                "force_exit": "on",
                "exit_signal": "on",
                "trailing_stop_loss": "on",
                "stop_loss": "on",
                "stoploss_on_exchange": "on",
                "custom_exit": "on",
                "partial_exit": "on"
            },
            "exit_cancel": "on",
            "exit_fill": "off",
            "protection_trigger": "off",
            "protection_trigger_global": "on",
            "strategy_msg": "off",
            "show_candle": "off"
        },
        "reload": true,
        "balance_dust_level": 0.01
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "somethingrandom",
        "CORS_origins": [
            "http://172.27.81.38:8080"
        ],
        "username": "ft",
        "password": "ft",
        "ws_token": "sercet_Ws_t0ken"
    },
    "bot_name": "MissingDataStrategy",
    "force_entry_enable": true,
    "initial_state": "running",
    "internals": {
        "process_throttle_secs": 5
    }
}
```

## Strategy impl

``` python
import numpy as np
import pandas as pd

import logging
from functools import reduce
from typing import Dict

import talib.abstract as ta
from pandas import DataFrame

import datetime as dt
from typing import Optional

from freqtrade.strategy import IStrategy

from scipy.stats import kurtosis, skew

def add_fft_components(data, n_components=10):
    fft_values = np.fft.fft(data['close'].values)
    
    fft_real = {f'%-fft_real_{i}': np.real(fft_values[i]) for i in range(1, n_components + 1)}
    fft_imag = {f'%-fft_imag_{i}': np.imag(fft_values[i]) for i in range(1, n_components + 1)}
    
    fft_df = pd.DataFrame(fft_real, index=data.index)
    fft_df_imag = pd.DataFrame(fft_imag, index=data.index)
    
    fft_df = fft_df.join(fft_df_imag)
    
    return data.join(fft_df)

logger = logging.getLogger(__name__)

class MissingDataStrategy(IStrategy):

    minimal_roi = {"0": 0.1, "240": -1}

    plot_config = {
        "main_plot": {},
        "subplots": {
            "&-s_close": {"&-s_close": {"color": "blue"}},
            "do_predict": {
                "do_predict": {"color": "brown"},
            },
        },
    }

    process_only_new_candles = True

    # ROI table:
    minimal_roi = {
        "0": 0.074,
        "12": 0.035,
        "43": 0.028,
        "50": 0
    }

    # Stoploss:
    stoploss = -0.05

    use_exit_signal = True
    # this is the maximum period fed to talib (timeframe independent)
    startup_candle_count: int = 40
    can_short = True

    def feature_engineering_expand_all(
        self, df: DataFrame, period: int, metadata: Dict, **kwargs
    ) -> DataFrame:
        pair = metadata['pair']

        add_fft_components(df)

        df["%-rsi-period"] = ta.RSI(df, timeperiod=period)
        df["%-mfi-period"] = ta.MFI(df, timeperiod=period)
        df["%-adx-period"] = ta.ADX(df, timeperiod=period)
        df["%-sma-period"] = ta.SMA(df, timeperiod=period)
        df["%-ema-period"] = ta.EMA(df, timeperiod=period)

        df_copy = df.copy()
        df_copy.dropna(inplace=True)
        if df_copy.empty:
            print("All data dropped due to NaNs. Here is the NaN count for each column:")
            nan_counts = df.isna().sum()
            for column, count in nan_counts.items():
                if count > 0:
                    print(f"Column {column} has {count} NaNs")

        return df

    def feature_engineering_expand_basic(
        self, df: DataFrame, metadata: Dict, **kwargs
    ) -> DataFrame:

        df["%-pct-change"] = df["close"].pct_change()
        df["%-raw_volume"] = df["volume"]
        df["%-raw_price"] = df["close"]

        return df

    def feature_engineering_standard(
        self, df: DataFrame, metadata: Dict, **kwargs
    ) -> DataFrame:
        
        df["%-day_of_week"] = df["date"].dt.dayofweek
        df["%-hour_of_day"] = df["date"].dt.hour

        return df

    def set_freqai_targets(self, df: DataFrame, metadata: Dict, **kwargs) -> DataFrame:
        df["&-s_close"] = (
            df["close"]
            .shift(-self.freqai_info["feature_parameters"]["label_period_candles"])
            .rolling(self.freqai_info["feature_parameters"]["label_period_candles"])
            .mean()
            / df["close"]
            - 1
        )
        return df


    def populate_indicators(self, df: DataFrame, metadata: dict) -> DataFrame:
        print(f"Length df in populate_indicators(): {len(df)}")
        df = self.freqai.start(df, metadata, self)
        return df

    def populate_entry_trend(self, df: DataFrame, metadata: dict) -> DataFrame:

        enter_long_conditions = [
            df["do_predict"] == 1,
            df["&-s_close"] > 0.01
        ]
        if enter_long_conditions:

            long_mask = reduce(lambda x, y: x & y, enter_long_conditions)
            logger.debug(long_mask)

            df.loc[
                reduce(lambda x, y: x & y, enter_long_conditions), ["enter_long", "enter_tag"]
            ] = (1, "long")

        enter_short_conditions = [
            df["do_predict"] == 1,
            df["&-s_close"] < -0.01
        ]
        if enter_short_conditions:

            short_mask = reduce(lambda x, y: x & y, enter_short_conditions)
            logger.debug(short_mask)

            df.loc[
                reduce(lambda x, y: x & y, enter_short_conditions), ["enter_short", "enter_tag"]
            ] = (1, "short")
        return df

    def populate_exit_trend(self, df: DataFrame, metadata: dict) -> DataFrame:
        exit_long_conditions = [
            df["do_predict"] == 1, 
            df["&-s_close"] < 0
        ]
        if exit_long_conditions:
            df.loc[reduce(lambda x, y: x & y, exit_long_conditions), "exit_long"] = 1

        exit_short_conditions = [
            df["do_predict"] == 1, 
            df["&-s_close"] < 0
        ]
        if exit_short_conditions:
            df.loc[reduce(lambda x, y: x & y, exit_short_conditions), "exit_short"] = 1

        return df

    def confirm_trade_entry(
        self,
        pair: str,
        order_type: str,
        amount: float,
        rate: float,
        time_in_force: str,
        current_time,
        entry_tag,
        side: str,
        **kwargs,
    ) -> bool:
        df, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = df.iloc[-1].squeeze()

        if side == "long":
            if rate > (last_candle["close"] * (1 + 0.0025)):
                return False
        else:
            if rate < (last_candle["close"] * (1 - 0.0025)):
                return False

        return True
```

  
### Observed Results:
The populate_indicators() callback is invoked and the full historical dataset is passed off to freqai.start(df, metadata, self) wherein, on line 318 of stable, the below code which calls tail(1) on the df is executed:
```
 df_fts = self.dk.use_strategy_to_populate_indicators(
    strategy, prediction_dataframe=dataframe.tail(1), pair=pair
)
```
As best as I can tell, this is where the df is truncated and the problem at least manifests, though the root cause may be in deriving training state.  The "Initial Training" use case works fine with this in place, so it must be there for a valid reason.

### Relevant code exceptions or logs
  ```
2024-06-24 15:45:39,966 - freqtrade.resolvers.iresolver - INFO - Using resolved freqaimodel LightGBMRegressor from '/home/dev/clean-ft/freqtrade/freqtrade/freqai/prediction_models/LightGBMRegressor.py'...
2024-06-24 15:45:39,966 - freqtrade.freqai.freqai_interface - INFO - Backtesting module configured to save all models.
2024-06-24 15:45:39,966 - freqtrade.freqai.data_drawer - INFO - Could not find existing historic_predictions, starting from scratch
2024-06-24 15:45:39,966 - freqtrade.freqai.freqai_interface - INFO - Set existing queue from trained timestamps. Best approximation queue: {best_queue}
2024-06-24 15:45:39,967 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2024-06-24 15:45:39,967 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2024-06-24 15:45:39,967 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
Length df in populate_indicators(): 190121
2024-06-24 15:45:39,979 - freqtrade.freqai.freqai_interface - INFO - Training 53 timeranges
2024-06-24 15:45:39,981 - freqtrade.freqai.freqai_interface - INFO - Training BTC/USDT:USDT, 1/1 pairs from 2023-05-11 00:00:00 to 2023-06-10 00:00:00, 1/53 trains
2024-06-24 15:45:39,984 - freqtrade.freqai.data_kitchen - INFO - Found backtesting prediction file at /home/dev/clean-ft/freqtrade/user_data/models/MissingDataStrategy/backtesting_predictions/cb_btc_1686355200_prediction.feather
Length df in feature_engineering_expand_all(): 1
2024-06-24 15:45:39,986 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/dev/clean-ft/freqtrade/freqtrade/main.py", line 43, in main
    return_code = args["func"](args)
  File "/home/dev/clean-ft/freqtrade/freqtrade/commands/optimize_commands.py", line 60, in start_backtesting
    backtesting.start()
  File "/home/dev/clean-ft/freqtrade/freqtrade/optimize/backtesting.py", line 1616, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/home/dev/clean-ft/freqtrade/freqtrade/optimize/backtesting.py", line 1526, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/home/dev/clean-ft/freqtrade/freqtrade/strategy/interface.py", line 1575, in advise_all_indicators
    return {
  File "/home/dev/clean-ft/freqtrade/freqtrade/strategy/interface.py", line 1576, in <dictcomp>
    pair: self.advise_indicators(pair_data.copy(), {"pair": pair}).copy()
  File "/home/dev/clean-ft/freqtrade/freqtrade/strategy/interface.py", line 1610, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/dev/clean-ft/freqtrade/user_data/strategies/MissingDataStrategy.py", line 123, in populate_indicators
    df = self.freqai.start(df, metadata, self)
  File "/home/dev/clean-ft/freqtrade/freqtrade/freqai/freqai_interface.py", line 161, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
  File "/home/dev/clean-ft/freqtrade/freqtrade/freqai/freqai_interface.py", line 318, in start_backtesting
    df_fts = self.dk.use_strategy_to_populate_indicators(
  File "/home/dev/clean-ft/freqtrade/freqtrade/freqai/data_kitchen.py", line 834, in use_strategy_to_populate_indicators
    dataframe = self.populate_features(
  File "/home/dev/clean-ft/freqtrade/freqtrade/freqai/data_kitchen.py", line 746, in populate_features
    df_features = strategy.feature_engineering_expand_all(
  File "/home/dev/clean-ft/freqtrade/user_data/strategies/MissingDataStrategy.py", line 71, in feature_engineering_expand_all
    add_fft_components(df)
  File "/home/dev/clean-ft/freqtrade/user_data/strategies/MissingDataStrategy.py", line 21, in add_fft_components
    fft_real = {f'%-fft_real_{i}': np.real(fft_values[i]) for i in range(1, n_components + 1)}
  File "/home/dev/clean-ft/freqtrade/user_data/strategies/MissingDataStrategy.py", line 21, in <dictcomp>
    fft_real = {f'%-fft_real_{i}': np.real(fft_values[i]) for i in range(1, n_components + 1)}
IndexError: index 1 is out of bounds for axis 0 with size 1
  ```

**Comment by xmatthias** [comment]
there's no need to change something - you can get the same by using `--cache none` (skipping cache).


That said - at first glance, this appears to be a bug.

https://github.com/freqtrade/freqtrade/blob/3348283b05a1bea94479cec1ed69c73bed2ef3ce/freqtrade/freqai/freqai_interface.py#L319

in reality though - the functionality that triggers this is "actually" originating from prediction caching - which aims to identify if something for the model has been changed or not  and eventually reuses previous predictions.
This can be very helpful for cases where you'd for example train a model, and then want to experiment with different, non-freqAI related strategy parameters (like stake-amount, open trades, ... or different callbacks), where you'd really not need a re-training (which can take hours if you're using more than a few pairs) - and you'd just need the previous predictions.

[explained here](https://www.freqtrade.io/en/stable/freqai-running/#saving-prediction-data_1).

This functionality is using the last row to identify which features would've been calculated - which is usually working fine, unless (like in your case) the strategy hard-requires a certain amount of data.

---

In your particular case - you're suffering from 2 problems (one that causes this to fail - the other to ignore all `%-fft-*` columns).

1. You can initially work around the bug by simply checking `if len(data) < 2: return  data` in your ftt_components column.
this will make your strategy work - also with `--cache none` and multiple executions - as the actual failure happens as 

_Your strategy does however suffer from a different problem, which voids the above workaround_

2.  `df.join()` does **not** modify the original dataframe, so after the `add_fft_components(df)` call your columns are still `['date', 'open', 'high', 'low', 'close', 'volume']` (not including any `%-fft-*` columns) - so from a freqAI perspective, they're non-existant.
  You can pretty easily fix this by using `df = add_fft_components(df)` - though this will void the fix from 1 - as now your columns will change - causing _"Trying to access pretrained model with `identifier` but found different features furnished by current strategy. Change `identifier` to train from scratch, or ensure the strategy is furnishing the same features as the pretrained model. In case of --strategy-list, please be aware that FreqAI requires all strategies to maintain identical feature_engineering* functions"_.


To effectively work around this - you should therefore (in the "small call" case) - assign the columns with a dummy value (only the column headers are actually relevant).

---

I don't think there's a way around the "feature names check" - as it's there for very good reason - allowing the identification of changed values.
Maybe the `.tail(1)` could be somehow parametrized to provide some level of control to the strategy / user for such cases - though adding a manual "create these columns for this case in the strategy" workaround doesn't seem like a huge hurdle - as i do see this as a very specific / special case - one i've not seen before if i'm honest.

@robcaulk any other thoughts?

---

As an aside: 
I think numpy.fft.fft (at least the way you're using it) is not lookahead-bias safe.
so you'll get the fourier transformation across all provided data - which will be significantly different between backtesting and live modes (backtesting get's also "future" data, while live, that future doesn't exist yet).

**Comment by robcaulk** [comment]
I think this may be a backtesting bug - you would need to re run with a new identifier until it can be investigated and fixed.

You could help by confirming with the freqai example strategy, and just backtesting the same config two times in a row. Does the same thing occur?

**Comment by xmatthias** [comment]
@robcaulk I don't think it will - it's specifically related to how the indicators in the strategy are being calculated (which rely on having more than one row).

essentially, it's got the same effect than adding a `assert len(df) > 1` to the strategy - which will work for "regular" usage, but not for the "backtest predictions" case, where it's called with `.tail(1)` to generate the column headers.

**Comment by robcaulk** [comment]
@xmatthias then I was confused by:

> The "Initial Training" use case works fine with this in place, so it must be there for a valid reason.

And his logs show that he has "Found existing predictions", so he is reusing an existing identifier. I believe when he runs fresh, it works. 

@monkeyden can it be confirmed?

**Comment by robcaulk** [comment]
Also, I will mention - we had a couple reports that rebacktesting was not working. I am working on finding the issue.

**Comment by xmatthias** [comment]
Well at least for the provided configuration - backtesting FreqaiExampleStrategy with `--cache none` multiple times in a row does work perfectly fine, and will only train on the initial call (unless i change the identifier, obviously).

As mentioned above - the strategy requires more than 1 row to not raise an error (leaving aside that the columns are then not used ...) - making the `tail(1)` the problematic part.
Now tail(2) might fix it for this case, but i don't think that's a scalable solution - as what we really require is "does this strategy generate the same features or did something change" - which is required to determine if the previous predictions _can_ be reused or not.

**Comment by monkeyden** [comment]
> @xmatthias then I was confused by:
> 
> > The "Initial Training" use case works fine with this in place, so it must be there for a valid reason.
> 
> And his logs show that he has "Found existing predictions", so he is reusing an existing identifier. I believe when he runs fresh, it works.
> 
> @monkeyden can it be confirmed?

Confirmed.  I trained and backtested to successful completion.  Re-ran backtesting without any changes at all, which was also successful.  Changed only the stake amount, it hits the block with tail(1) and the error presents.  

@xmatthias Good spot on that join() call.  That's a familiar nemesis.

**Comment by xmatthias** [comment]
> Re-ran backtesting without any changes at all

This will use caching unless you use `--cache none` :) which is why a change to the config breaks it - as that voids the cache.

**Comment by xmatthias** [comment]
This ain't a bug in freqAI - simply an unexpected / unexplained safety check.

I've added a new note to the docs now to explain that freqAI may call your strategy with a dataframe of length 1 during re-backtesting
While this COULD be changed / configurable eventually - i'm not sure if it's worth the effort of doing so - as that's the first occurance of such an issue in several years of having freqAI available.
