### ISSUE TITLE
Select columns of the df

### ISSUE THREAD

**Issue by Mo7mud** [freqtrade/freqtrade#10376]
## Describe your environment

  * Operating system: Linux mint
  * Python Version: 3.10
  * CCXT version: 4.3.35
  * Freqtrade Version: 2024.5
  
## Your question

There is a function in `rpc.py` file which as I understand selects which columns will be passed to the dataset in the UI

``` @staticmethod
    def _convert_dataframe_to_dict(
        strategy: str,
        pair: str,
        timeframe: str,
        dataframe: DataFrame,
        last_analyzed: datetime,
        selected_cols: Optional[List[str]],  // This parameter which I want to control
    ) -> Dict[str, Any]:
        has_content = len(dataframe) != 0
        dataframe_columns = list(dataframe.columns)
        signals = {
            "enter_long": 0,
            "exit_long": 0,
            "enter_short": 0,
            "exit_short": 0,
        }
        if has_content:
            if selected_cols is not None:
                # Ensure OHLCV columns are always present
                cols_set = set(DEFAULT_DATAFRAME_COLUMNS + list(signals.keys()) + selected_cols)
                df_cols = [col for col in dataframe_columns if col in cols_set]
                dataframe = dataframe.loc[:, df_cols]

            dataframe.loc[:, "__date_ts"] = dataframe.loc[:, "date"].astype(int64) // 1000 // 1000
            # Move signal close to separate column when signal for easy plotting
            for sig_type in signals.keys():
                if sig_type in dataframe.columns:
                    mask = dataframe[sig_type] == 1
                    signals[sig_type] = int(mask.sum())
                    dataframe.loc[mask, f"_{sig_type}_signal_close"] = dataframe.loc[mask, "close"]

            # band-aid until this is fixed:
            # https://github.com/pandas-dev/pandas/issues/45836
            datetime_types = ["datetime", "datetime64", "datetime64[ns, UTC]"]
            date_columns = dataframe.select_dtypes(include=datetime_types)
            for date_column in date_columns:
                # replace NaT with `None`
                dataframe[date_column] = dataframe[date_column].astype(object).replace({NaT: None})

            dataframe = dataframe.replace({inf: None, -inf: None, NAN: None})

        res = {
            "pair": pair,
            "timeframe": timeframe,
            "timeframe_ms": timeframe_to_msecs(timeframe),
            "strategy": strategy,
            "all_columns": dataframe_columns,
            "columns": list(dataframe.columns),
            "data": dataframe.values.tolist(),
            "length": len(dataframe),
            "buy_signals": signals["enter_long"],  # Deprecated
            "sell_signals": signals["exit_long"],  # Deprecated
            "enter_long_signals": signals["enter_long"],
            "exit_long_signals": signals["exit_long"],
            "enter_short_signals": signals["enter_short"],
            "exit_short_signals": signals["exit_short"],
            "last_analyzed": last_analyzed,
            "last_analyzed_ts": int(last_analyzed.timestamp()),
            "data_start": "",
            "data_start_ts": 0,
            "data_stop": "",
            "data_stop_ts": 0,
        }
        if has_content:
            res.update(
                {
                    "data_start": str(dataframe.iloc[0]["date"]),
                    "data_start_ts": int(dataframe.iloc[0]["__date_ts"]),
                    "data_stop": str(dataframe.iloc[-1]["date"]),
                    "data_stop_ts": int(dataframe.iloc[-1]["__date_ts"]),
                }
            )
        return res
```
Can I control `selected_cols` from the strategy or the config or even from UI code?
I want to pass some columns to the UI without editing Freqtrade base code.
Is this possible?

**Comment by froggleston** [comment]
You'd have to edit the UI to accept those columns, so that's a separate issue. However, with the REST API you can supply the `columns` payload option to return specific columns from the main dataframe: https://github.com/freqtrade/freqtrade/pull/10160

**Comment by xmatthias** [comment]
FreqUI will request the necessary columns based on the configured plot config, given you're using a recent version and didn't disable that functionality in the ui.

**Comment by Mo7mud** [comment]
> You'd have to edit the UI to accept those columns, so that's a separate issue. However, with the REST API you can supply the `columns` payload option to return specific columns from the main dataframe: #10160

Yes I know that I have to edit the UI and I did it already but with hardcoded set of columns in the `rpc.py` file, this is why I'm asking if I can control it from the UI code or strategy code.
I'm not very familiar with the project so if there is any docs explaining this will be very appreciated.
Thank you very much

**Comment by Mo7mud** [comment]
> FreqUI will request the necessary columns based on the configured plot config, given you're using a recent version and didn't disable that functionality in the ui.

Where can I find this functionality? I'm using last version of Freqtrade and FreqUI

**Comment by froggleston** [comment]
https://www.freqtrade.io/en/stable/freq-ui/#plot-configurator
https://www.freqtrade.io/en/stable/plotting/#advanced-plot-configuration

**Comment by xmatthias** [comment]
It's automatic once you have your plot config configured. There is no need to edit either freqtrade, nor the UI code.
If you think you need that to use this feature - don't - then you're lacking understanding on how this works.
