### ISSUE TITLE
Support for Multi-asset mode

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#10379]
## Describe your environment
(if applicable)

  * Operating system: Linux mint Ulya
  * Python Version: 3.10.4
  * CCXT version: 4.2.25
  * Freqtrade Version: 2024.1

## Describe the enhancement

Are there any chances to support multi-asset mode on freqtrade? after the MicA we no longer have access to futures trading in the EU.

**Comment by froggleston** [comment]
This is not currently planned or in development.

**Comment by moinonin** [comment]
Understood. Could someone share a workaround they needed to do to implement a futures trading in the EEA region? especially working with binance futures credit trading mode. Highly appreciated.

**Comment by xmatthias** [comment]
I don't see how multi asset mode would work in europe, which banned futures trading in many countries anyway.

Mica has little to do with that, as you'd still trade usdt pairs, and are as such subject to MiCa regulation.
