### ISSUE TITLE
API Server GUI: Entering Price far above candle

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#10384]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.5 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

A limit order was filled instantly, so the open rate of both Telegram posts "new trade" and "new trade filled" are the same at 0.00924 USDT. For a reason, this price is far above the candle, meaning above the closing price of the green candle, above the high wick. Above the default candle, as well as above the heikin ashi candle. In my understanding, the top point of the high wick (0.0092269 USDT) would graphically represent the highest price, the asset reached during this time period. What is possibly the reason, this could happen? (also see attached image) 
![Screenshot_1](https://github.com/freqtrade/freqtrade/assets/34372534/3d5132cb-fd31-4226-9798-ade550b4ad7d)

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by stash86** [comment]
Is this dry-run?

**Comment by myNextCoder** [comment]
Yes, this is dry run, I thank you for the input. Can this initiate such a difference?

**Comment by xmatthias** [comment]
On a low volume pair - sure.

If your limit price on a long trade is above the current orderbook price, then the order will fill immediately, usually as a marketable limit order (its a market order with a "worst acceptable price" representing your limit price).
Now depending on the orderbook depth (this is where volume of the market comes in), your (now an order behaving like a market order) order will push the price of the token (hard capped by freqtrade at 3 or 5%, don't remember from memory) up the orderbook until the volume is sufficient to fill your order. This could be 1 orderbook slot, or 10 ... Up to the above mentioned hard cap to avoid pointless slippage.

In live, you'd now set a new candle high.
Its dry however, so the market doesn't know your order ... Which effectively never happened for other market participants.

We don't sinulate the impact of orders onto the market ... so your dry order can fill above a candle in unfortunate circumstances.

[This section of the docs](https://www.freqtrade.io/en/stable/configuration/#considerations-for-dry-run) explains this ... Though it seems to miss the market order limit.

as an aside:

Also keep in mind that candles represent the price of executed trades, not necessarily the range the orderbook spread moved in.

**Comment by myNextCoder** [comment]
Wow absolutely great again you answer, I thank you xmatthias. Although we might not discuss "better" or "less good" Python strategies, I ask you, if I should possibly add a confirmation, where, for example the current volume must be higher, than during the last 10 candles? If this makes sense, some trades, which would have waited for enough volume, might not be fired anymore at all. By the way, I trade with orderbook off at entering and exiting. The other possibility is, to increase minimum asset pricing, if I have understood you correctly. I thank you for the link, I am not sure now, if - even at dry run time - it is generally better to switch on the orderbook, for reducing some cases of the issues.

**Comment by xmatthias** [comment]
Switching orderbook on or off is not necessarily relevant, though i'd recommend leaving it on if your exchange supports it.
If you turn it off, the "ticker" endpoint is used for pricing.
While it also delivers a (best) bid / ask, its usually delayed a bit (compared to orderbooks) - and exchanges dont guarantee uptodate price in that endpoint.

market order filling will however always use orderbook pricing if that's available for the exchange.

Volume checks usually make sense - though this is really only a problem on general low volume pairs. Top 50-100 volume should not really encounter this - not after their first weeks of listing, anyway.

Asset price per se has nothing to do though, it can be 0.001 or 100$ - volume can still be near 0 on that exchange / pair.

**Comment by myNextCoder** [comment]
My answer is late. I now instantly turn on the orderbook.
My coins must have a certain age, so I may not need to check volume. I still might start e testbot, which is deciding to enter uniquely after a mean or max volume check, the results won't be good of course, but I can observe the behavior.
