### ISSUE TITLE
Back test calculates duration wrong

### ISSUE THREAD

**Issue by creslinux** [freqtrade/freqtrade#1038]
BAcktest calculate 5 days 4 hours as "840"
Also the profit does not marry to either BackSlap or online binance calculator. 

The delta is the bot is not using 50% fees that binance offer by using their token for fees. 
So -- this may/may-not be  a bug, but the bot should use bnb, so backtest should too. 

Otherwise the cost is double. 

<img width="900" alt="screen shot 2018-07-17 at 9 04 30 pm" src="https://user-images.githubusercontent.com/34645187/42845928-eebc5336-8a06-11e8-8a73-ff3cb35790e9.png">

**Comment by xmatthias** [comment]
I doubt that this should be fixed, as i would consider it desired behavior.
backtest tries to keep away from exchange-specifics - and BNB is a binance construct.

Also - on binance, the BNB fees only applies if you actually own BNB (and have that enabled) - which backtest has no way of knowing as it does not need nor want your binance keys - so it's not per se wrong (the calculation may be wrong for your account, but correct for mine as i don't own BNB).


The way this works in the bot is that it uses what ccxt returns with `get_fee`. Only after the trade has executed, the api knows that BNB has been applied. This was a pain while getting ccxt working.

The only potential solution i could imagine is adding a `--fee 0.001` property where you can configure a fee yourself if you think you know better, but standard behavior should remain what `ccxt.get_fees()` returns.

**Comment by creslinux** [comment]
I would never describe doubling cost as desired behaviour 
but get your point 

The duration is a bug - 840minutes is not 5days 14 hours.
Displaying the wrong duration breaks any reporting metric applied after test for how profitable a trade is over time. 1% gain an hour is more desired than 1% a year as example

**Comment by xmatthias** [comment]
that's true - but it's double cost for your particular account ... we're not applying the "regular" binance fees twice :)

mmh ... there is a reason i did not comment on that part ... ;)

**Comment by creslinux** [comment]
#1040 has been merged and is the fix to this. Closing.
