### ISSUE TITLE
freqUI incorrect Dashboard -> Bot comparison -> Balance value

### ISSUE THREAD

**Issue by ApsidD** [freqtrade/freqtrade#10381]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.12.3
  * CCXT version: 4.3.46
  * Freqtrade Version: 2024.5

## Describe the problem:

The balance field in the freqUI shows wrong amount after trade closes. page needs to be refreshed to see the proper balance.

*Explain the problem you have encountered*

I trade futures with binance and when the trade is open or close balance in the freqUI decreases or increases on the amount of the whole stake. Once I change tab to trade tab and back to dashboard the balance is proper again.
for example. initial balance is 1000. trade opened with stake amount of 100$. the balance at the same moment becomes 900.
then I refresh the page and balance gets back to 1000. then trade is closed let's say at 
101$. balance becomes 1101$. I refresh the page and balance returns to 1001$.

### Steps to reproduce:

  1. start bot with frerqui
  2. open frequi dashbort and wait for the bot to make an order
  3. notice how balance has decreased on the amount of stake.
  4. refresh the page and notice balance grow back to its actual value.
  5. wait for the trade to close.
  6. notice the balance has increased on the amount of stake
  7. refresh the page and notice balance drop back to it's actual value
  
### Observed Results:

  * What happened?
  On order create Balance decreases on the amount of stake. If I refresh the page balance jumps back to its actual value.
  On order close Balance increases on the amount of stake. If I refresh page balance jumps back to its actual value.

  * What did you expect to happen?
  On order create I expect Balance it to stay as it was. On order close I expect Balance it to show new balance after profit/loss

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
your description is either confuse - or i fail to understand what you mean.

for simplicity, i've used an (existing) dry-run futures bot for this:
Fresh - no order:
![image](https://github.com/freqtrade/freqtrade/assets/5024695/2f5611d7-6f72-4e7a-b1f7-4d17e995929c)


Enter trade (wait a bit for the balance and everything to correct itself:

![image](https://github.com/freqtrade/freqtrade/assets/5024695/de4c51dd-8f63-49ee-a47b-5db9f203cd7f)

(i can refresh the page and did - but always see the same thing)

If i now close out the trade - my balance returns back to how it was (though slightly lower than originally, as i lost roughly 7$ on this trade)

![image](https://github.com/freqtrade/freqtrade/assets/5024695/2135f29f-7cdc-477e-b98d-ba77079ca73f)


Unless you can better describe what you mean or what you're encountering exactly (maybe with screenshots showing what you mean) - i wouldn't know what's wrong in this above sample.

**Comment by xmatthias** [comment]
closing this as we got no further feedback.

Feel free to comment below if this is still unclear / you have something more to add.
