### ISSUE TITLE
some coins leverage setup not working.

### ISSUE THREAD

**Issue by hccap** [freqtrade/freqtrade#10396]
I'm using API to place orders.

most of coin works good.

but so strange for some coins,  

```
  data = {
            "pair": symbol.upper() + "/USDT:USDT",
            "side": side,
            "ordertype": method,
             "stakeamount": float(amount) , 
            "entry_tag": reason,
            "leverage": 10,
        }
```

leverage is not working ,it fallback to 1 ,

I have checked binance if this coin has that leverage 10, it is! 

since this problem comes sometime, I dont know to debug..

also I have tried to place order from admin .  still not working, only leverage 1 avalible.

**Comment by stash86** [comment]
Dry run?

**Comment by hccap** [comment]
yes dry run!  that's why?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

We'll also need some information on the actual pair you're encountering this with.

Without this information, it's going to be impossible to assist you further on this topic.
Thanks for your understanding.

**Comment by korenhskoh** [comment]
Sorry to ask. How did you setup the leverage for trade in dry run ? In config file or strategy template ?

**Comment by froggleston** [comment]
As per the docs: https://www.freqtrade.io/en/stable/strategy-callbacks/#leverage-callback

**Comment by hccap** [comment]
yes. it's in my strategy.  I did as doc says.  like I said most of coins works fine, some coin fallback to 1.

**Comment by stash86** [comment]
Binance require api key to access leverage information. In backtest and dry-run, the bot will use local cache of leverage info. If the coin isn't on the exchange when the bot last update the cache, then it will use leverage of 1 for the trade.

Make sure you regularly pull latest ft code from the githib, because it will update the cache as well

**Comment by xmatthias** [comment]
I'm going to close this - as you don't seem to desire help.

Unless the information requested in https://github.com/freqtrade/freqtrade/issues/10396#issuecomment-2205305725 is provided, i'll assume this issue as solved - and the problem having been that you're using an outdated version.

**Comment by hccap** [comment]
@stash86  I think you are right. that's the issue.  only newer coin has this issue.
