### ISSUE TITLE
Request Rate Limit Exceeded (003)

### ISSUE THREAD

**Issue by XinuxC** [freqtrade/freqtrade#10395]
## Describe your environment

  * Operating system: using docker 2024.6 on Ubuntu 22
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.6  (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair PEPE/USDT due to RateLimitExceeded. Message: gate {"label":"TOO_MANY_REQUESTS","message":" Request Rate Limit Exceeded (003)"}". Retrying still for 2 times.

what should I do with these WARNINGs

**Comment by stash86** [comment]
Reduce number of pairs would help

**Comment by XinuxC** [comment]
> Reduce number of pairs would help

Thx, it does work

**Comment by xmatthias** [comment]
don't disabling builtin ccxt ratelimiting would help, too.

for supported exchanges, i'm pretty certain these limits are correct and won't cause this warning to happen.

**Comment by XinuxC** [comment]
> don't disabling builtin ccxt ratelimiting would help, too.
> 
> for supported exchanges, i'm pretty certain these limits are correct and won't cause this warning to happen.

"ccxt_config": {
            "hostname": "gate.io"
        },
        "ccxt_async_config": {
        },
does this help?I reduced the number of pairs,it rate limit warnings came out after a few miniutes

**Comment by stash86** [comment]
How many pairs are you using?

**Comment by XinuxC** [comment]
> How many pairs are you using?

{
            "method": "VolumePairList",
            "number_assets": 85,
            "sort_key": "quoteVolume",
            "refresh_period": 1800
        },

3bots both set to 85

**Comment by xmatthias** [comment]
well builtin rate-limiting applies to 1 bot.
3 bots will use 3x the same rate-limit - which is best scaled horizontally (using different IP's).
