### ISSUE TITLE
Managing open trades after power/network outage

### ISSUE THREAD

**Issue by valek333** [freqtrade/freqtrade#10403]
Hey Freqtrade devs! Huge thanks for this awesome project, I really appreciate the ongoing support! It's been super interesting to learn about and test it out.

Here's what I'm curious about: what happens if, say, the internet goes down, the power goes out, or I simply need to shut down my PC, and the bot has open trades at that time?

When the bot starts back up, will it remember all the trades it placed before the crash and keep them going, or will I have to manually close them?

Thanks in advance! I must've missed it in the docs, but I couldn't find an answer to that anywhere.

**Comment by stash86** [comment]
As long as you don't remove the database, when you start the bot again, it will manage the open trades again.

**Comment by valek333** [comment]
> As long as you don't remove the database, when you start the bot again, it will manage the open trades again.

Thank you so much!

**Comment by xmatthias** [comment]
For production / live usage - I'd strongly suggest using a VPS (server) - which is independent of you turning your system off or from random internet outages.

While the bot can recover - you'll usually have the outage at the most inopportune time - missing either a good exit - or a stoploss (unless you use stoploss on exchange, which protects at least the stoploss portion from this).
