### ISSUE TITLE
More detailed pre-selection for whitelist?

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#10415]
## Describe your environment

  * Operating system: Windows Server 2022
   * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.5 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Does Freqtrade offer an automatic way, to generate a whitelist with “rising” assets? With this I mean, if we can gather out assets with an increasing value (example: Growing assets between 5 and 20% during the last 5 days). This may result in a whitelist of less pairs, which might move in the wrong direction (for long trading). This may help to keep the whitelist smaller, I guess, with more 'high quality pairs'. I ask this question here, because I didn’t see any pairlistfilter, which covers such a task.

(Rangestability and Volatility are both similar, but the change may not be bullish, but bearish)

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by stash86** [comment]
If you can't find it in the docs, then it doesn't exist

**Comment by xmatthias** [comment]
Duplicate of #10348
