### ISSUE TITLE
Source Code Question:  why use contextmanager

### ISSUE THREAD

**Issue by iridescentGray** [freqtrade/freqtrade#10423]
## Describe your environment

  * Operating system: Docker devcontainer
  * Python Version: 3.12.3(`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: newest (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

contextmanager always used with yield
https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager

Why is there no yeild in this function?  Is there any special usage for contextmanager ?
https://github.com/freqtrade/freqtrade/blob/5cabd49becb984a421c989a6a92d652e11fcb217/freqtrade/rpc/api_server/uvicorn_threaded.py#L56

**Comment by iridescentGray** [comment]
https://github.com/freqtrade/freqtrade/pull/10424

**Comment by xmatthias** [comment]
Probably a remainder from the initial implementation - which allowed different usage - at least in part - as it's actually commented there already: https://github.com/freqtrade/freqtrade/commit/1e38fec61b42c998111297a56b8e2c7b2a304919.

I don't really see that's relevant for actual operations? as we're not using it as context manager, it's actually irrelevant - and hence wasn't noticed.

**Comment by iridescentGray** [comment]
I understood.  Thank you for your answer.
