### ISSUE TITLE
Clarification on Liquidation Price Calculation: Should nominal_value Include Leverage?

### ISSUE THREAD

**Issue by linimin** [freqtrade/freqtrade#10422]
## Describe your environment

  * Operating system: Mac OS 14.5
  * Python Version: 3.12.4 (`python -V`)
  * CCXT version: 4.3.58 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade docker-2024.7-dev-8a166b04 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I have a question regarding the liquidation price calculation in the [dry_run_liquidation_price function](https://github.com/freqtrade/freqtrade/blob/b9c2868dff3809a70e17f73df5ba05d6093a3d9f/freqtrade/exchange/binance.py#L147). Specifically, I am unsure whether the `get_maintenance_ratio_and_amt` function should be called with the `stake_amount` or the total trade amount including leverage (nominal_value).

Current Code:
In the current implementation, the function is called as follows:
```
mm_ratio, maintenance_amt = self.get_maintenance_ratio_and_amt(pair, stake_amount)
```

Question:
Should this call be:
```
mm_ratio, maintenance_amt = self.get_maintenance_ratio_and_amt(pair, stake_amount * leverage)
```

I would appreciate any clarification on whether the current implementation is correct or if it should be modified to include leverage in the nominal_value.

**Comment by stash86** [comment]
Yes, we believe current implementation is correct. Any issue with it?

**Comment by linimin** [comment]
Thank you for your response. I wanted to highlight a specific [comment](https://github.com/freqtrade/freqtrade/blob/b9c2868dff3809a70e17f73df5ba05d6093a3d9f/freqtrade/exchange/exchange.py#L3416) in the code that seems to indicate nominal_value should include leverage. Based on this comment, it appears the current implementation might not be aligning with the intended calculation. 
```
    def get_maintenance_ratio_and_amt(
        self,
        pair: str,
        nominal_value: float,
    ) -> Tuple[float, Optional[float]]:
        """
        Important: Must be fetching data from cached values as this is used by backtesting!
        :param pair: Market symbol
        :param nominal_value: The total trade amount in quote currency including leverage
        maintenance amount only on Binance
        :return: (maintenance margin ratio, maintenance amount)
        """
```

**Comment by xmatthias** [comment]
I've cleaned up the comment now.

what is meant here is the **notional** value (that's what it's compared to) to determine the maximum leverage amount.
Essentially, what you see in this table [source](https://www.binance.com/en/futures/trading-rules/perpetual/leverage-margin):

![image](https://github.com/user-attachments/assets/6e79c717-fede-4acd-a326-85933471de7e)

It's used to determine leverage - so it's not the result of leverage (i don't think it could be the result of leverage, actually).

Especially for liquidations though - it's usually not "that" relevant unless you trade huge positions.
