### ISSUE TITLE
Dry test only open 5-8 trades, when buy =1 is on tens of pairs. 

### ISSUE THREAD

**Issue by creslinux** [freqtrade/freqtrade#1043]
I've moved my QA into dry test / live. 

The volume of trades seen in Backtest are realistic, but FT in Dry and Live only open 5-10 of these. 

This issue is to highlight the bot quickly ties itself up processing only open trades when 5-8 trades are open, and ignores other pairs. Thus not discovering their Buy =1  signal, not buying. 

When the 5-9 open trades receive SELL =1 the bot starts processing the pairs that were ignored. 

This manifests itself as only ever having a few - 7/8 open trades and then ignoring all other buy opportunities.  This is perfect world, the strategy has no processing overhead. The concurrency falls when over head is higher. 

In live there a many exampled of users seeing only 1-4 pairs open when expecting open trades against many tens of pairs. 

Below describes the work flow in the linked video. 

Test scenarion 53 pairs, max trades 53, strategy returns 0 on even minutes, 1  on odd - no delay.

Ill paraphrase but the workflow of the bot in dry test quickly becomes thus. 

**odd minute - sell =1**
1) tests though loop of pairs while sell = 1  / buy = 0, maybe 1-2 seconds per pair.

**even minute - buy = 1**
2) 
 - opens first trade. Time to process 1 second
     tends to trade 1 
 - opens second trade : Time to process 4 seconds
    tends to trade 1
    tends to trade 2
 - opens third trade : Time to process 6 seconds
   tends to trade 1
   tends to trade 2
   tends to trade 3
......
trade 7 takes 12 seconds to open. No more pairs are open.
<img width="758" alt="screen shot 2018-07-18 at 5 02 22 pm" src="https://user-images.githubusercontent.com/34645187/42896731-607d5f14-8aad-11e8-8870-ad9b528c09c7.png">

3) The bot spends an ever increasing time managing open trades and during this time does not process the "Other pairs" 

**Even minute - Sell = 1**
4) The bot notices the change,  
        - as now no longer solely focuses on the open pairs
        - processes other pairs from the 53

**even minute - buy = 1**
5) The 7 sold open trades now show in trades DB ,, 

first trade shows as closed on exactly even minute in the trades db when buy =1
<img width="577" alt="screen shot 2018-07-18 at 5 10 49 pm" src="https://user-images.githubusercontent.com/34645187/42896802-8ca2fb76-8aad-11e8-9e65-962ad50b7fa1.png">

others close very soon after (2 seconds) (but not when they are sell-1, when flipped back to buy =1
<img width="649" alt="screen shot 2018-07-18 at 5 12 02 pm" src="https://user-images.githubusercontent.com/34645187/42896857-ba2ec160-8aad-11e8-9859-b480bceb3f73.png">

6) New trades begin to open again - as per step 2. 
     It is the same pairs to open. 
<img width="669" alt="screen shot 2018-07-18 at 5 13 11 pm" src="https://user-images.githubusercontent.com/34645187/42896922-eb93d1dc-8aad-11e8-9d09-5c728face143.png">

7) repeat. 

A video of the issue. 

https://highfrequencybot.slack.com/files/UAU4J8LU9/FBTQFU431/ft_drytest.mp4

**Comment by jblestang** [comment]
What does your config looks like? After a pair is bought the bot stops looking for a pair, sleep for a while (in the config), then check opened trades , then looks for new pairs that have not been checked yet.

**Comment by creslinux** [comment]
Config attached 

[config.dry.test.txt](https://github.com/freqtrade/freqtrade/files/2206756/config.dry.test.txt)

**Comment by jblestang** [comment]
Try with process_throttle_secs set to 1 this is your limit (not an ideal solution )

**Comment by creslinux** [comment]
ok ill spin it up like this.

**Comment by creslinux** [comment]
No change to output
Trades open at ever slowing rate - max at 7. 
Also the open trades do not sell on sell -1, but when buy =1 again. 

Opening
<img width="943" alt="screen shot 2018-07-18 at 5 45 17 pm" src="https://user-images.githubusercontent.com/34645187/42898500-e09d7648-8ab2-11e8-9b69-79b260ca172b.png">

Not selling
<img width="943" alt="screen shot 2018-07-18 at 5 45 17 pm" src="https://user-images.githubusercontent.com/34645187/42898533-f0e8429e-8ab2-11e8-9036-76a8570c1bd5.png">

Sold on buy =1 then opening again. 
<img width="704" alt="screen shot 2018-07-18 at 5 46 52 pm" src="https://user-images.githubusercontent.com/34645187/42898546-fa2c8db0-8ab2-11e8-9ead-01f7d8bf0a35.png">

**Comment by creslinux** [comment]
config was set to 1s
 

<img width="463" alt="screen shot 2018-07-18 at 5 52 06 pm" src="https://user-images.githubusercontent.com/34645187/42898677-536d6dc2-8ab3-11e8-9fe3-2d53048c9bde.png">

**Comment by creslinux** [comment]
#1046 is gathering momentum and is the fix to this.

**Comment by xmatthias** [comment]
I'll close this one as it's going to be fixed by #1046 / it's followup PR's, as it's really a side-product of how we handle downloading ticker data.

but it's great to highlight such issues!
