### ISSUE TITLE
Minor visual history order issues

### ISSUE THREAD

**Issue by aliengofx** [freqtrade/freqtrade#10457]
## Describe your environment

  * Operating system: Ubuntu (Docker)
  * Freqtrade Version: Lasted (07/24/2024)

## Describe the enhancement

There are two very minor issues I would like to be paid attention in the future.
 - For shorts sell orders while using the isolated futures on the on the GUI freqtrade candle graph, the sell shorts orders icon is the same as the sell long orders (there is no visual difference between short sell and long sell orders). For someone who would like to see a detailed view of the short and long orders it's kind of difficult to distinguish.
 - Also on telegram there is no distinguish between short and long history orders while using the "/trades" command for isolated futures.

That's all. Good luck to you all!
![trades2024-07-24 194011](https://github.com/user-attachments/assets/43f61b08-f839-44c4-91ff-6aa35b1b3b4c)

**Comment by xmatthias** [comment]
It's unlikely that we'll be adding more information to the "/trades" table in telegram - though it seems to lack information from /status-table - so this letter can be added.

For more info though - the width of telegram won't allow for this - and it'd start wrapping even more (it already does in some instances) - which we clearly want to avoid.
You'll anyway lack most of the information on telegram - so the trade-list on freqUI should be the way to go.

---

For the "exit order" topic on freqUI - i'm not entirely sure what you mean.
An exit order (one that was executed on) will be pointing down for a long trade (see below) - and will be rotated by 180° for shorts.

![image](https://github.com/user-attachments/assets/2cf1ef8e-2b62-4e98-9a77-5ea5fc1ace6c)

If that ain't what you mean, best provide some screenshots for it.

**Comment by aliengofx** [comment]
Ok, I totally understood for the telegram subject mentioned. Now about the other subject, the basic idea was to differentiate visually the short orders that are not taken from the long orders that are not taken. That because the **not executed exit orders there is only a brown dot (either is short or long exit)**, so in order to see if there was a short or long not executed exit order you should have place your mouse arrow on each dot on the chart. Hope I made myself clear this time and again it's just a minor thing hope wont be too much struggle to implement it if you would consider.

Now, one other possible issue I may have noticed is about the Hyperopt mechanism. I probably should have opened a new subject for this one but it may not be necessary in the end, so I thought I would mention it here. Well, after successfully hyperopted some of my stategies, most of them with worst results than the initial raw ones. That probably because I noticed there were taken a massive amount of orders with very small losses or close to zero profits. I'm not sure if the hyperopt and the backtesting method takes into consideration the spreads of the exchanges or if the orders are executed on the same or other limit prices, because I thought that might be the issue. Especially for the lower time frame strategies (5m, 15m) the results in my cases were worst with a lot more unusual trades which in the end due to the fees from the exchanges the hyperopted strategy could become way worst than the initial one. Hope it makes sense. Thank you.

**Comment by xmatthias** [comment]
I'm not entirely sure why that'd be relevant.
a short exit signal is only relevant **if you're in a short position**. If you're in a long position - it's irrelevant and will be ignored.

On a funny side-note: 
the signals DO differ - with short exit signals being represented as a small pin - and long exit signals as diamond.
Their color is identical - which is intentional to avoid the chart becoming too noisy at first glance.

![image](https://github.com/user-attachments/assets/2edeeb86-b549-4959-8a0f-147e83445175)

---

If you don't like the direction of the optimization - you're best off using a different [loss function](https://www.freqtrade.io/en/stable/hyperopt/#loss-functions).
Hyperopt is repeated backtesting in the end - so which method is used to place orders is actually up to the strategy / configuration for the most part.

**Comment by aliengofx** [comment]
I know it may seem irrelevant, for me I only needed to confirm visually that my strategy enters and exits respectively as it supposes according to it's past activity.

Tehe, I really didn't notice the signals differ in a way. Now, I'm at peace, I'll use my zooming tool to double check my exits. xD

Also, thank you for clarifying my concern about the Hyperopt function. I should prob switch to another loss function. Thanks for everything!

**Comment by aliengofx** [comment]
Along with with the other updates, thank you so much for adding the trade direction and leverage info on telegram!
