### ISSUE TITLE
Creating a complex (maybe basic but strong ) strategy

### ISSUE THREAD

**Issue by rcpislr** [freqtrade/freqtrade#10462]
Hi Everybody. I am new on freqtrade. 
I am working on a strategy development. I have backtested this strategy on tradingview and i can say that winrate is about %82 but i dont know how to write a freqtrade strategy.

explanation of strategy. 
1. will identify support and resist points (tolerance will be given manual or can be define as parameter like %2 - smthnelse)
2. if price touches support/resist , will save the ris value
3. if price touches 2. time support/resist , will compare with 1 rsi value. If 2. rsi value is bigger than 1. rsi value that means (if support level long - if resist level short position)

this is  something like is rsi divergence but stronger signal than it and more dynamically. Bec. in divergence strat we should define for ex. last 100 candlestick. 

anyone can help about that?

**Comment by stash86** [comment]
While we will help to answer some questions, we won't create the strategy for you from scratch. You will have to write it yourself, then you can ask here for any issue.

Pro tips: support and resistance levels are really hard (if not impossible) to be coded without having lookahead issue. That strat won't really perform well in live trade.

But here is a simple tutorial on how to write a strategy, if you still want to try it

https://botacademy.ddns.net/2023/10/18/fsd-basic-template-of-a-strategy/

**Comment by froggleston** [comment]
Additionally, winrate means nothing. As an example, from 100 trades, 99 make 1% profit. One makes a 100% loss. Whilst the winrate is 99%, the profit ratio and expectancy are terrible.
