### ISSUE TITLE
Question about minimal_roi when using partial exit with adjust_trade_position()

### ISSUE THREAD

**Issue by dobremha** [freqtrade/freqtrade#10476]
## Describe your environment

  * Operating system: Linux
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.4 (docker)
  
## Your question
Hello everyone,

Let's say trading spot, so no leverage.
I have:
minimal_roi = {"0": 0.032} # +3.2%

I close 50% (half) of my position at +1.7% via adjust_trade_position().

When current price will reach > +3.2% from entry price, will minimal_roi trigger an exit signal for rest of the stake ?

Because ROI of trade will be something like +2.5%, from closing half at +1.7% and half at +3.2.

Thanks.

**Comment by xmatthias** [comment]
ROI will be calculated against the currently open position - not necessarily against the open-price.

Now in your example - it will be against open price (minus fees - so price will need to move slightly more) - but in a more complex setup (where you'll do subsequent entries as well) - it will be calculated against the adjusted open price - with the amount currently in the trade

**Comment by dobremha** [comment]
Thanks, can be closed.
