### ISSUE TITLE
Is there any alternate approach to download trade data? Data downloading takes way too much time .  

### ISSUE THREAD

**Issue by febin-16** [freqtrade/freqtrade#10475]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
With the provided information - no, there isn't.

for some exchanges, there can be alternatives (which are eventually highlighted in the exchange specific notes).
