### ISSUE TITLE
Environment variables do not allow for case sensitive CCXT config keys

### ISSUE THREAD

**Issue by jmrichardson** [freqtrade/freqtrade#10481]
## Describe your environment

  * Operating system: Redhat Linux
  * Python Version: Python 3.9.18
  * CCXT version: ccxt==4.3.69
  * Freqtrade Version: freqtrade 2024.8-dev-9b11597fc
  
## Describe the problem:

Setting proxy in environment variables do not respect case sensitivity:

### Steps to reproduce:

FREQTRADE__EXCHANGE__CCXT_CONFIG__verify=false
FREQTRADE__EXCHANGE__CCXT_CONFIG__HTTPSPROXY=http://172.16.5.9:8080
FREQTRADE__EXCHANGE__CCXT_CONFIG__WSPROXY=http://172.16.5.9:8080

or 

export FREQTRADE__EXCHANGE__CCXT_CONFIG__httpsProxy="http://$IP_ADDRESS:8080"
export FREQTRADE__EXCHANGE__CCXT_CONFIG__wsProxy="http://$IP_ADDRESS:8080"
export FREQTRADE__EXCHANGE__CCXT_CONFIG__verify="false"

  
### Observed Results:

Keys are all lowercase:

```
2024-07-31 10:27:55,560 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'httpsproxy': 'http://172.16.5.9:8080', 'wsproxy': 'http://172.16.5.9:8080', 'verify': False}
2024-07-31 10:27:55,563 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'httpsproxy': 'http://172.16.5.9:8080', 'wsproxy': 'http://172.16.5.9:8080', 'verify': False, 'rateLimit': 4100}
```

They should be httpsProxy and wsProxy.  CCXT does not work with the above proxy settings

### Relevant code exceptions or logs

This works correctly when specified in json:

```
 "ccxt_config": {
            "enableRateLimit": true,
            "httpsProxy": "http://172.16.5.10:8080",
            "wsProxy": "http://172.16.5.10:8080",
            "verify": false
        },
```

**Comment by xmatthias** [comment]
That's correct - configurations are intended to be provided as environment variables in upper case - and are transformed to lower case.

we don't have any means to validate which case you mean or imply - or what ccxt would require - so i'd not know HOW to support this in the first place.

Also - ccxt_config keys are arbitrary keys when it comes to our configuration. 
While we don't actively validate against "Is this a known key" at this moment - it's an implementation detail which keeps this working for now (your variables would come to ccxt as `wsproxy`) - but is neither something we do aim to support, nor can guarantee will work in the future.


Best use the configuration to provide additional ccxt_config options - eventually via a [partial config](https://www.freqtrade.io/en/stable/configuration/#multiple-configuration-files) that only contains this key

**Comment by jmrichardson** [comment]
@xmatthias Completely understand and thank you for the fast reply!  I was originally hoping for a one-off that would update the proxy keys to httpsProxy and wsProxy from lowercase given its what ccxt requires.  Unfortunately, I have a system behind a proxy and wanted to maintain one json file by adding the env variables on this system.  With json, I don't believe I can programmatically do a partial config based on the proxy for this host vs my local host which doesn't use a proxy.  Given the proxy is a popular setting was hoping this could be done for just these settings but not a big deal.  Will just keep a config_proxy.json on the proxy host.  Appreciate freqtrade very much!
