### ISSUE TITLE
How to adjust 'Entry Price' instead of closing price

### ISSUE THREAD

**Issue by thkwon9474** [freqtrade/freqtrade#10488]
## Describe your environment

Operating system: Ubuntu 22.04.2 LTS(docker)
Python Version: python 3.11.7
CCXT version: 4.0.71
Freqtrade Version: freqtrade 2024.08
  
## Your question

Helllo!

There have been similar questions before, but I couldn't find the answer I was looking for, so I'm asking.

The features I would like to implement are:
In the current system, entry is made at the closing price with ['enter_long'] = 1.
At this time, is there a way to enter a different price instead of the closing price?

In the case of adjust_entry_price in the Freqtrade document, it is assumed only when order.fill is not fully completed, so it does not seem suitable in the case above.

**Comment by stash86** [comment]
First of all, the entry rate will be based of whatever the oderbook rate at the moment is (for limit) or the filled market rate (market order).

Second, look for `custom_entry_price` in the docs

**Comment by thkwon9474** [comment]
I found it . Thank you so much:)
