### ISSUE TITLE
ReinforcementLearning TypeError: PPO.__init__() got an unexpected keyword argument 'trainer_kwargs'

### ISSUE THREAD

**Issue by Agilitytime** [freqtrade/freqtrade#10504]
## Describe your environment

  * Operating system: Docker Container on Ubuntu 22.04
  * Python Version: freqtrade docker-2024.8-dev-fa2fc63b
  * CCXT version: freqtrade docker-2024.8-dev-fa2fc63b
  * Freqtrade Version: freqtrade docker-2024.8-dev-fa2fc63b
  
## Your question

Hi, 

i want to integrate ReinforcementLearning in my Freqtrade AI Strategy.
I follow the guide on the Freqtrade wiki but become always this error, when I start the bot.
Can somebody help me with this problem?

Thanks,
Sebastian

```
freqtrade  | 2024-08-05 23:08:38,834 - freqtrade.freqai.RL.BaseReinforcementLearningModel - INFO - --------------------Starting training DOT/USDT:USDT --------------------
freqtrade  | 2024-08-05 23:08:38,841 - freqtrade.freqai.data_kitchen - INFO - DOT/USDT:USDT: dropped 2 training points due to NaNs in populated dataset 2859.
freqtrade  | 2024-08-05 23:08:38,866 - freqtrade.freqai.RL.BaseReinforcementLearningModel - INFO - Training model on 213 features and 2285 data points
freqtrade  | 2024-08-05 23:08:38,867 - freqtrade.freqai.freqai_interface - ERROR - Training DOT/USDT:USDT raised exception TypeError. Message: PPO.__init__() got an unexpected keyword argument 'trainer_kwargs', skipping.
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 243, in _start_scanning
freqtrade  |     self.extract_data_and_train_model(
freqtrade  |   File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 625, in extract_data_and_train_model
freqtrade  |     model = self.train(unfiltered_dataframe, pair, dk)
freqtrade  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/freqai/RL/BaseReinforcementLearningModel.py", line 146, in train
freqtrade  |     model = self.fit(dd, dk)
freqtrade  |             ^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/freqai/prediction_models/ReinforcementLearner.py", line 67, in fit
freqtrade  |     model = self.MODELCLASS(
freqtrade  |             ^^^^^^^^^^^^^^^^
freqtrade  | TypeError: PPO.__init__() got an unexpected keyword argument 'trainer_kwargs'
```

**Comment by xmatthias** [comment]
well the model class is given your configuration's  `model_training_parameters` as keyword args.

As the [documentation](https://www.freqtrade.io/en/stable/freqai-parameter-table/#model-training-parameters)  for this parameter describes:

> A flexible dictionary that includes all parameters available by the selected model library. For example, if you use LightGBMRegressor, this dictionary can contain any parameter available by the LightGBMRegressor [here](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMRegressor.html) (external website). If you select a different model, this dictionary can contain any parameter from that model.

the note in the [reinforcement-learner](https://www.freqtrade.io/en/stable/freqai-reinforcement-learning/#configuring-the-reinforcement-learner) section goes into the same direction
> Remember that the general model_training_parameters dictionary should contain all the model hyperparameter customizations for the particular model_type.

linking to the [ppo docs](https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html) to find valid parameters (apparently, `trainer_kwargs`, which you have in your configuration, is not).

**Comment by codewithsupra** [comment]
The error indicates that the PPO class is not expecting a trainer_kwargs argument. This might be due to changes in the library or a mismatch between expected and provided arguments.

Inspect the PPO Class: Locate the PPO class in your RL library (e.g., stable-baselines3) and check its __init__ method to confirm which arguments it expects. The PPO class should not have trainer_kwargs as an argument.

Update Initialization Code: If trainer_kwargs is not a valid argument, you will need to update your code to match the expected arguments of the PPO class.

**Comment by Agilitytime** [comment]
Thanks for your help!!!
