### ISSUE TITLE
Upgrading from 2024.5 stable to 2024.7

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#10506]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.5 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Upgrading on August, 7th, 2024, from 2024.5 stable, with pip install --upgrade freqtrade does not result in the current version 2024.7, but gives me 2024.6. Sending the command a 2nd time, does not change anything. What is most likely the reason?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Nice spot - seems like the deployment CI ran into an error (https://github.com/freqtrade/freqtrade/actions/runs/10149039995/job/28063053968).

Will let you know once the re-run is complete.

**Comment by myNextCoder** [comment]
I thank you in advance (at least, the system upgrades to a valid version and does not crash)

**Comment by xmatthias** [comment]
2024.7.1 will be available through pypi (as well as through docker) now.

**Comment by myNextCoder** [comment]
Great, yes indeed, after the upgrade I read:
Successfully installed freqtrade-2024.7.1
I thank you :)
