### ISSUE TITLE
multiple webhook endpoints and new message of error/warning/timeout of exchange

### ISSUE THREAD

**Issue by denisdemaisbr** [freqtrade/freqtrade#10502]
## Describe the enhancement

- possibility to have many webhook targets
- add a new message in case of error/warning/timeout of exchange
- maybe compatible with pior cofiguration, i.e., if webhook is a object (single) or a array (many)
- threaded version, launch webhook using threads to not hang execution
 
{
  "webhook": {
        "enabled": true,
        "url": "https://<YOURSUBDOMAIN>.cloud.mattermost.com/hooks/<YOURHOOK>",
        "format": "json", "status": {"text": "Status: {status}"}
    }
}

*Explain the enhancement you would like*
{
"webhook": [
  { "enabled": true, "url": "https://endpoint10.com/" },
  { "enabled": true, "url": "https://endpoint20.com/>", "warning":  "{reason}", "timeout": "{reason}": "error": "{reason}" }
]
}

**Comment by xmatthias** [comment]
What'd be the usecase for this? (as in - why would you need this?)

I feel like this would complicate code (and usage) without actually providing benefits to the average user.

**Comment by denisdemaisbr** [comment]
in case of unavailability.
after some search https://webhookrelay.com/ can able to "relay" to endpoints.

thanks!

**Comment by xmatthias** [comment]
well i think webhooks should be treated as they are meant - as information provided to the user.

missing a notification shouldn't be an issue - as you can still actively look at what happened later on.
