### ISSUE TITLE
Access to Datatable in calculate_reward

### ISSUE THREAD

**Issue by Agilitytime** [freqtrade/freqtrade#10518]
Hi, 

i want to Access the Datatable in the calculate_reward function.

When iam debug the Funtion, i see that under

self.raw_fetures are the Data for Example

%-cci-period_30_BTC/USDTUSDT_15m
or
%-close-bb_lower-period_60_shift-10_ETH/USDTUSDT_2h

but what is the correct way to access this data?

Thanks,
Sebastian

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.


---


I'm inclined to think that the [documentation for creating a custom reward function](https://www.freqtrade.io/en/stable/freqai-reinforcement-learning/#creating-a-custom-reward-function) covers this quite nicely if you carefully read through the example provided in this section

> ``` python
>     # you can use feature values from dataframe
>     # Assumes the shifted RSI indicator has been generated in the strategy.
>     rsi_now = self.raw_features[f"%-rsi-period_10_shift-1_{pair}_"
>                           f"{self.config['timeframe']}"].iloc[self._current_tick]
>```

(but absolutely look through the full sample).

**Comment by xmatthias** [comment]
Closing this with the assumption that the above link did help.

Feel free to comment below if there's still questions about this topic.
