### ISSUE TITLE
Getting episodic trades to the reward function on freqtrade-rl

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#10517]
## Describe your environment

  * Operating system: Linux Mint Ulya
  * Python Version: 3.10.4
  * CCXT version: 4.3.65
  * Freqtrade Version: 2024.7
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

I would like to bring periodic results to the reward function when using reinforcement learning with Freqtrade -rl. On the notebook I usually get these results this way upon backtesing:
```
# Assuming your pickled file is named 'example.pkl'
file_path = 'backtest-result-2024-08-07_06-53-48.json'
with open(file_path, 'rb') as file:
    unpickled_object = json.load(file)
trades_dict = unpickled_object.get('strategy').get('MyStrategy').get('trades')
```
Except in this case I would like to ship them to the reward function after say 10 days of training.

Any ideas on this? or does get_unrealized_profit() contain these info?

**Comment by robcaulk** [comment]
Hello,

What does "periodic results" mean?

Currently, you can take a look at `add_state_info` parameter, where the positions are considered in the environment/model.

**Comment by xmatthias** [comment]
Closing this, as there hasn't been any further activity here, so there's nothing further to do for us.
