### ISSUE TITLE
Time of the last candle

### ISSUE THREAD

**Issue by thmeta** [freqtrade/freqtrade#10520]
* Operating system: Win10
  * Python Version: 3.11.3
  * CCXT version: 4.3.76
  * Freqtrade Version: 2024.8-dev-67fe7f8d3
  
I have strategy with timeframe=1h, and my last candle's date is more than 3 hours behind my system time, while I'm UTC+1 timezone (which should give UTC+2 in summer time). I wonder why is that so... anyone has an idea...? At the time of writing of this message the last candle is 17:00, my system time is 20:47, and freqtrade's time is also 20:47

![image](https://github.com/user-attachments/assets/9288e624-bff7-4273-a691-34bae48fd901)

![image](https://github.com/user-attachments/assets/9e66687e-1767-4c65-aac6-83bb053cd3dd)

**Comment by xmatthias** [comment]
well the candle time (the time you're shown) is the candle open time.

so the candle that shows 17:00 - will be the candle containing all trades between 17:00 and 18:00 (that's when the close happens).
Considering your UTC time is 18:47 - (UTC+2) - the candle shown is the last closed candle - the candle of 18:00 UTC (until 19:00 UTC)  is still open - hence not available through freqtrade (to avoid repainting).


Now freqUI will (by default) display data in UTC (which is the default for most exchanges, too) - though you can change this in the settings to be your local timezone (assuming your browser's system has the correct timezone, obviously).

**Comment by thmeta** [comment]
Thanks for your reply - it seems somewhat odd that the time shown is the candle open time instead of its close time. If the current time is 18:47 UTC it would be more intuitive to see the last candle's close time at 18:00 UTC and not its open time at 17:00 UTC

**Comment by xmatthias** [comment]
it's the exchange default - all exchanges i've looked at so far display the candle open timeframe.

call it industry standard if you will - but we'll surely not deviate from that - as it'd be highly confusing as freqtrade would essentially be the only one to suddenly use a "close date" of a candle.

**Comment by thmeta** [comment]
OK got it, but how can I get the view similar to trading view where the last candle is being drawn in real time. I tried  with process_only_new_candles = False but it seems to not work

Below on the left is freqtrade, and tradingview on the right with one more candle at the end

![image](https://github.com/user-attachments/assets/e1da2a16-4c2c-4e31-a83b-0ddd0bc41cfe)

**Comment by xmatthias** [comment]
tradingview is very prone to repainting (signals appear and disappear within a candle) due to updating candles throughout their duration.

To prevent that from happening - freqtrade only works on closed candles.
The FAQ also covers this [here](https://www.freqtrade.io/en/stable/faq/#i-want-to-use-incomplete-candles)
