### ISSUE TITLE
Define pairlist dynamically within the strategy?

### ISSUE THREAD

**Issue by xenon1001** [freqtrade/freqtrade#10521]
## Describe your environment

  * Operating system: ubuntu 24
  * Python Version: 3.10 
  * CCXT version: 4.3.70
  * Freqtrade Version: 2024.7
  
## 
Is it possible to define a pairlist (whitelist and blacklist) dynamically within the strategy file, rather than using the configuration file? I noticed that the documentation provides predefined options for configuring these lists, but I need to define them based on calculations done within the strategy. Is there a way to set them directly in the strategy file and leave the configuration file blank or bypass it?

**Comment by stash86** [comment]
You can do something like this

https://botacademy.ddns.net/2024/06/26/how-to-trade-only-x-amount-of-pairs-with-lowest-highest-y-indicator-value/

**Comment by xenon1001** [comment]
@stash86 Thanks man I read it, interesting method to solve what looks like a simple problem and seems a bit too resource consuming. Still thanks for the solution.

**Comment by xmatthias** [comment]
Preventing entries (while keeping the full pairlist) is definitely the worst solution i can think of (it'll be incredibly noisy as in a "full pairlist" scenario - it'll block all non-traded pairs all the time, always with log messages ...).

---

Resource consumption of such an approach will be high anyway if you think about it.

You want to define pairs dynamically via strategy - this implies that
* you download candles for ALL pairs
* do your calculation to determine the filtering for all pairs

It's not impossible - and some pairlists do this already - but it needs very careful implementation.

while it would be possible to add this to a strategy (it'd def. be a separate method, not using existing calculations) - i don't really see the benefit of this, as it'll limit reusability.
Logic for a pairlist can usually be used for tons of strategies - so having it in a strategy will be counter-intuitive.

---

Something i can imagine is to allow users to (easily) write custom pairlist plugins - which can then be reused - but everyone can use their own, random logic.

Something like #4477 would enable this (best subscribe to this issue for updates) - and while it's an open enhancement, there's currently no plans on enabling this near-term - as the pairlist interface is not considered to be a public interface at this point.

**Comment by stash86** [comment]
Well, that's the only way to do it as of today 😁 Never claimed it to be fast.

Personally, I find it would be putting too much load on your bot to filter and/or sort pairs based of indicator(s) value, no matter in-strat or as custom plugin, because as matthias pointed out above, you would need to download and process the data of ALL pairs.

The best way is actually how https://remotepairlist.com currently doing it, which is having a separate script to do all the calculation, then your bot just need to frequently fetch the new list.

**Comment by xmatthias** [comment]
well volumepairlist (in advanced mode) is doing just that - as well as a few other pairlists (e.g. VolatilityFilter, Rangestabilityfilter, ...).
on some exchanges, it's the only way.
