### ISSUE TITLE
Can i use leverage in binance futures? 

### ISSUE THREAD

**Issue by kleanth11** [freqtrade/freqtrade#10526]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
So i tried to look into the documents but some docs say that you cant use margin or futures some say you can use futures margin avaliable or in testing phase so i wanted to get here and ask a simple question. 
Can i use binance futures and leverage with freqtrade, i want to run it on dry mode and i thought i did but putting the leverage to 10x doesnt seem to work as the trades take place like im not using leverage at all, now the way i put leverage could be totally wrong so if i can use binance futures with leverage can someone just show me how to integrate that into my config file? 
Thank you very much in advance

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

You can use leverage on binance futures.

if it doesn't work - then either your version is too old - or you're setting it wrong.
Especially for dry-run, keeping uptodate with freqtrade versions is key, as we need to cache the allowed leverage values. Using an old version will mean you'll not get leverage on newer pairs.


the only way to set leverage is through the [leverage callback](https://www.freqtrade.io/en/stable/strategy-callbacks/#leverage-callback).
