### ISSUE TITLE
Stoploss Not Updating due to outdated position balance

### ISSUE THREAD

**Issue by erhangunay** [freqtrade/freqtrade#10533]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: Docker Version 2024.7.1 (`python -V`)
  * CCXT version: Docker Version 2024.7.1(`pip freeze | grep ccxt`)
  * Freqtrade Version: Docker Version 2024.7.1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

After noticing that my stoploss is not updating, i went to the logs to understand the situation and noticed that freqtrade does not update open position balances in terms of coins.

I am running the bot on 1m tf

### Steps to reproduce:

  1. Trying to update stoploss (it was not updated automatically so i reloaded the trade)
  2. Got the error;
  freqtrade.freqtradebot - Trade(id=1, pair=RVN/USDT:USDT, amount=22038.00000000, is_short=False, leverage=21.0, open_rate=0.01595000, open_since=2024-08-14 12:32:02) has a total of 22038.0 RVN, but the Wallet shows a total of 0 RVN. Refusing to adjust as the difference is too large.This may however lead to further issues.
  4. This happened on live trading on my VPS, so before posting here i tried to run it on my computer fresh start with dryrun, it happens again.
  
### Observed Results:

  * What happened?
 Stoploss not updating with the error;
freqtrade.freqtradebot - Trade(id=1, pair=RVN/USDT:USDT, amount=22038.00000000, is_short=False, leverage=21.0, open_rate=0.01595000, open_since=2024-08-14 12:32:02) has a total of 22038.0 RVN, but the Wallet shows a total of 0 RVN. Refusing to adjust as the difference is too large.This may however lead to further issues.

  * What did you expect to happen?
I wanted my stoploss to update automatically based on my preferences.

PS: If i check it from telegram by /balance the results are reflecting the actual balances however on the logs and FreqUI it is always 0 as shown in both screenshots below.

### Relevant code exceptions or logs
freqtrade.freqtradebot - Trade(id=1, pair=RVN/USDT:USDT, amount=22038.00000000, is_short=False, leverage=21.0, open_rate=0.01595000, open_since=2024-08-14 12:32:02) has a total of 22038.0 RVN, but the Wallet shows a total of 0 RVN. Refusing to adjust as the difference is too large.This may however lead to further issues.

![image](https://github.com/user-attachments/assets/e1dcb84c-498c-4c81-9e4e-47031b1191c0)

In the image where it says 0 is causing the problem in my opinion. The above image is live trading on binance on vps.

![image](https://github.com/user-attachments/assets/23ca5cb0-e479-4d52-bf22-376181af5240)

This image is from dry run again on binance. 

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by hippocritical** [comment]
you need a certain amount left in the pair to trade back, that amount is decided by the exchange not freqtrade. You can get stuck if you don't exit early enough or the pair suddenly crashes.
Live would have you auto liquidated, maybe the pair flucuated too hard for freqtrade to enter force sell like behavior to do the same before you pay the liquidation fees.

A solution (since you are dry running it) would be to delete that pair and pretend it never happened.

**Comment by erhangunay** [comment]
thank you for your message but this situation is the same for all pairs and i am running on live. I could not understand what you mean by certain amount left in the pair

**Comment by xmatthias** [comment]
There's a table below the image - tooltips in the graph will not necessarily contain meaningfull information.
It has a % - so there IS balance there - otherwise it would be 0.0% of your bot balance.

If you can post a screenshot of the whole balance screen (the graph AND the table) - you'll see what i mean.


Unfortunately, the whole post revolves around this fact - ignoring both the table below the chart - as well as what logs actually say.

What's actually happening (or what you think your problem is, for that matter) is not really clear to me.
It's clearly not balance (though there might be a small bug in the tooltip display of the chart for futures).

somewhere in the middle, you claim the following:

> Stoploss not updating with the error;

Though you neither provide what the error is - nor logs of that error happening.

Please post proper logs (not just one line - but several lines) - and try to better describe what your actual problem is - ignoring the tooltip in the chart.

**Comment by erhangunay** [comment]
Hi again,

I used to see amounts here before, i thought my problem was related to this, maybe I am wrong.
![image](https://github.com/user-attachments/assets/0766d122-f2de-4a97-9782-dfe5e4f31db6)

Error code:


2024-08-14 16:02:58 INFO    freqtrade.freqtradebot - handled order 7778785659
2024-08-14 16:02:58 INFO    freqtrade.freqtradebot - Found open order for Trade(id=7, pair=QTUM/USDT:USDT, amount=56.20000000, is_short=False, leverage=6.0, open_rate=2.37800000, open_since=2024-08-14 12:45:49)
2024-08-14 16:02:58 INFO    freqtrade.freqtradebot - handled order 7779946864
2024-08-14 16:02:58 INFO    freqtrade.freqtradebot - Found open order for Trade(id=7, pair=QTUM/USDT:USDT, amount=56.20000000, is_short=False, leverage=6.0, open_rate=2.37800000, open_since=2024-08-14 12:45:49)
2024-08-14 16:02:58 INFO    freqtrade.freqtradebot - handled order 7779951636
2024-08-14 16:02:58 WARNING freqtrade.freqtradebot - Trade(id=7, pair=QTUM/USDT:USDT, amount=56.20000000, is_short=False, leverage=6.0, open_rate=2.37800000, open_since=2024-08-14 12:45:49) has a total of 56.2 QTUM, but the Wallet shows a total of 0 QTUM. Refusing to adjust as the difference is too large.This may however lead to further issues.

**Comment by erhangunay** [comment]
> Hi again,
> 
> I used to see amounts here before, i thought my problem was related to this, maybe I am wrong. ![image](https://private-user-images.githubusercontent.com/17651818/357898088-0766d122-f2de-4a97-9782-dfe5e4f31db6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NTE3MDEsIm5iZiI6MTcyMzY1MTQwMSwicGF0aCI6Ii8xNzY1MTgxOC8zNTc4OTgwODgtMDc2NmQxMjItZjJkZS00YTk3LTk3ODItZGZlNWU0ZjMxZGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE2MDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNTU3YzdiYmE3NjczOTk3ZmEyMjZjMzM0N2FkOGNjMjQyNDQ3NzUxODU3YmY2NmQ0MDA5ZmUxMDdmMDJlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ki1vowo7KTlkWruq2KXnoCZxUtVHFLcpUU2orZRc7rk)
> 
> Error code:
> 
> 2024-08-14 16:02:58 INFO freqtrade.freqtradebot - handled order 7778785659 2024-08-14 16:02:58 INFO freqtrade.freqtradebot - Found open order for Trade(id=7, pair=QTUM/USDT:USDT, amount=56.20000000, is_short=False, leverage=6.0, open_rate=2.37800000, open_since=2024-08-14 12:45:49) 2024-08-14 16:02:58 INFO freqtrade.freqtradebot - handled order 7779946864 2024-08-14 16:02:58 INFO freqtrade.freqtradebot - Found open order for Trade(id=7, pair=QTUM/USDT:USDT, amount=56.20000000, is_short=False, leverage=6.0, open_rate=2.37800000, open_since=2024-08-14 12:45:49) 2024-08-14 16:02:58 INFO freqtrade.freqtradebot - handled order 7779951636 2024-08-14 16:02:58 WARNING freqtrade.freqtradebot - Trade(id=7, pair=QTUM/USDT:USDT, amount=56.20000000, is_short=False, leverage=6.0, open_rate=2.37800000, open_since=2024-08-14 12:45:49) has a total of 56.2 QTUM, but the Wallet shows a total of 0 QTUM. Refusing to adjust as the difference is too large.This may however lead to further issues.

Just wanted to mention the situation is the same for all the open trades

**Comment by xmatthias** [comment]
can you provide the output of the following command:

`freqtrade show-config <-c yourconfig>`

Also, please provide the bot's startup logs (the logs up to the first hearthbeat).


Also, please enable `"log_responses" : true` in the `exchange` section of your configuration and provide us with the logs once the error repeates.
Please make sure to include as much logs as possible - considering it should happen on each iteration - this should be pretty quick.

**Comment by erhangunay** [comment]
i could not fit it here, here is my config
> can you provide the output of the following command:
Your combined configuration is:
```
{
  "max_open_trades": 50,
  "stake_currency": "USDT",
  "stake_amount": "unlimited",
  "tradable_balance_ratio": 1,
  "fiat_display_currency": "USD",
  "dry_run": false,
  "dry_run_wallet": 100,
  "cancel_open_orders_on_exit": true,
  "trading_mode": "futures",
  "margin_mode": "isolated",
  "unfilledtimeout": {
    "entry": 618,
    "exit": 60,
    "exit_timeout_count": 1,
    "unit": "seconds"
  },
  "entry_pricing": {
    "price_side": "other",
    "use_order_book": true,
    "order_book_top": 6,
    "price_last_balance": 0.0,
    "check_depth_of_market": {
      "enabled": false,
      "bids_to_ask_delta": 1
    }
  },
  "exit_pricing": {
    "price_side": "other",
    "use_order_book": true,
    "order_book_top": 6
  },
  "order_types": {
    "entry": "limit",
    "exit": "limit",
    "emergency_exit": "market",
    "force_exit": "market",
    "stoploss": "limit",
    "stoploss_on_exchange": true
  },
  "exchange": {
    "name": "binance",
    "key": "REDACTED",
    "secret": "REDACTED",
    "ccxt_config": {
      "enableRateLimit": true
    },
    "log_responses": true,
    "ccxt_async_config": {},
    "pair_whitelist": [],
    "pair_blacklist": [],
    "apiKey": "REDACTED",
    "password": "REDACTED",
    "uid": "REDACTED",
    "accountId": "REDACTED",
    "walletAddress": "REDACTED",
    "privateKey": "REDACTED"
  },
  "pairlists": [
    {
      "method": "RemotePairList",
      "number_assets": 20,
      "pairlist_url": "https://remotepairlist.com?q=389f1b3a22bd2df6"
    },
    {
      "method": "FullTradesFilter"
    },
    {
      "method": "ShuffleFilter",
      "shuffle_frequency": "candle",
      "seed": 42
    }
  ],
  "telegram": {
    "enabled": true,
    "token": "REDACTED",
    "chat_id": "REDACTED"
  },
  "api_server": {
    "enabled": true,
    "listen_ip_address": "0.0.0.0",
    "listen_port": 8080,
    "verbosity": "error",
    "enable_openapi": false,
    "jwt_secret_key": "rGL353cTtDSR9DtpqP8xZyTLIM9KNbfaKwlh1uODvbaxHAfBXr4PNNtL9jFOx6Cq",
    "ws_token": "LEVVMitFkAZ0Y0J15Tp2Ua6vBpYbruF63aczlo5qiBOuMakBMAiYPBXSuug1YALd",
    "username": "freqtrade",
    "password": "REDACTED"
  },
  "bot_name": "FreqTrade",
  "initial_state": "running",
  "force_entry_enable": true,
  "internals": {
    "process_throttle_secs": 5
  },
  "config_files": [
    "user_data/config.json"
  ]
}
```
> Also, please provide the bot's startup logs (the logs up to the first hearthbeat).

**Comment by erhangunay** [comment]
[New Text Document (6).txt](https://github.com/user-attachments/files/16616139/New.Text.Document.6.txt)
i could not fit the log sorry

**Comment by xmatthias** [comment]
well one thing up front (though it's not directly related to this issue) - running with 50 open trades on a 1m timeframe is insane. If you have more than a handful of trades open, your processing time (time it takes for one iteration) will exceed 1 minute VERY easily.

Now the 50 open trades is obviously a missconfiguration - as your whitelist only has 20 pairs (so 60% of your trades lots never fill - leaving 60% of your capital untouched 100% of the time).

---

Unfortunately - the log doesn't seem to clearly excert the problem you're claiming.
I tried to look at QTUM - which doesn't seem to show this problem.

the only instance in the logs is for LQTY - where the logs stop right at the problematic point (maybe the followup would contain something useful ...).
Now let's focus on that trade ... 
Please provide the ouptut of the following command for this trade:
`freqtrade show-trades --db-url sqlite:///<trades.sqlite> --print-json --trade-ids 4`
Please use a "details block" to keep the issue itself kindof readable (see below for details on how to do that). 

<details>
<summary>Expand to see how to do details blocks</summary>

```
<details>
<summary>Expand full </summary>
(wrap in tripple ticks `)
Trades output ...
</details>
```
</details>

---

now the log for this trade seems odd in itself - to the point of hinting that some lines are missing / have been excluded.

Up to 2024-08-14 16:26:30 - everything seems normal ... starting with that:

`2024-08-14 16:26:30 INFO    freqtrade.freqtradebot - handled order 2085397179` - is printed from within `handle_onexchange_order()` (
https://github.com/freqtrade/freqtrade/blob/23510c80bea33fdb7fa1dfbc9ddb4146d2ec4fab/freqtrade/freqtradebot.py#L530).

The only way to reach this point is past `self.exchange.fetch_orders` - which itself would log a `API fetch_orders: ` log line - but doesn't (which i don't see happening, really).

It's also unclear how this method is actually reached - it's called from 2 places - either via explicit RPC method (did you trigger this?) - or from within the bot - which would log a different message, which is however also missing.

**Comment by erhangunay** [comment]
i deleted the db after this chat to start over.

May i ask what happens when you click on reload trade from freqUI ? that handled order message is appearing due to that.

Previously when i reloaded a trade from frequi it recalculated the stop without any errors and i could also see my balances in the table of balances per each position the qty of coins that have been bought. now when i click on reload trade, no matter what the coin is, it is always saying the amount is 0 and that it can not adjust. when setting the first stop it is not causing an issue but sometimes i notice that the stoploss function has not done what its supposed to do and click on reload trade to recalculate and this issue happens.

apart from LQTY, no matter what the coin is i can never reload a trade from freqUI. can you try please? maybe it is due to a setting i have set that i somehow broke it but i really want to know if it works for anybody else. i even tried it on 2 different places, my computer and vps. Either it is being caused by my config or there is something not right there. could you confirm?

**Comment by xmatthias** [comment]
well there's little reason to click "reload trade" unless you think something's wrong with a trade.
So just to confirm - in the logs above - it's been you who clicked the button (this would confirm one missing log-message - but not the other).


as explained above - your "has no qty" problem is rooted in the tooltip being slightly missleading (this was never different, really).
- if telegram OR the table below has it correctly - then it will still have the amount.

Also the warning that happens - it's a warning - really - which can be fixed easily - and in your case - ignored.

I don't really see either of the 2 things causing any subsequent problems at this moment though.

**Comment by erhangunay** [comment]
if its just a warning maybe it was due to my stoploss calculation. sorry for taking your time on this, i will post again if it happens again.

**Comment by erhangunay** [comment]
> well there's little reason to click "reload trade" unless you think something's wrong with a trade. So just to confirm - in the logs above - it's been you who clicked the button (this would confirm one missing log-message - but not the other).
> 
> as explained above - your "has no qty" problem is rooted in the tooltip being slightly missleading (this was never different, really).
> 
> * if telegram OR the table below has it correctly - then it will still have the amount.
> 
> Also the warning that happens - it's a warning - really - which can be fixed easily - and in your case - ignored.
> 
> I don't really see either of the 2 things causing any subsequent problems at this moment though.

yes i clicked reload trade to show, i guess i was wrong

**Comment by xmatthias** [comment]
Well i'm not even saying "it's nothing" - all i'm saying is - with the provided information - it's impossible to analyze further - as the 2 things you found odd are either normal (the chart tooltip) - or just a (in this case, irrelevant) warning message.

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
