### ISSUE TITLE
My prints no longer display during hyperopt: How can I make them appear?

### ISSUE THREAD

**Issue by NicolasGuigui** [freqtrade/freqtrade#10532]
## Describe your environment

  * Operating system: Windows with Docker
  * Python Version: last version of docker image freqtrade:develop_plot
  * CCXT version: last version of docker image freqtrade:develop_plot
  * Freqtrade Version: freqtrade docker-2024.8-dev-90092276
  
## Your question
Hi,

I'm currently trying to debug a hyperopt loss function. A few months ago I was able to put prints in the hyperopt_loss_function function in order to understand my calculations and find failures. For several months, the outputs have been displayed but disappear very quickly when the results table is refreshed.

I have the impression that it is linked to the update with the creation and use of the hyperopt_output.py class and to the progress bar which recalculates the display. How can I restore the display of logs?
I tried with print, console class instantiation and logger but none worked.

You can test on your side with this code

```
from datetime import datetime
from math import exp
from typing import Dict

from pandas import DataFrame

from freqtrade.constants import Config
from freqtrade.optimize.hyperopt import IHyperOptLoss
from rich.console import Console

import logging
logger = logging.getLogger(__name__)

class Test_HOL(IHyperOptLoss):

    @staticmethod
    def hyperopt_loss_function(results: DataFrame, trade_count: int,
                               min_date: datetime, max_date: datetime,
                               config: Config, processed: Dict[str, DataFrame],
                               *args, **kwargs) -> float:
        
        result = 1

        print("My output", flush=True)

        console = Console()
        console.print("My console output!", style="bold yellow")

        logger.info("My logger output")

        return result 
```

Can I have a help on this please ?

I would also like to take advantage of this ticket because I would like to add conditions to access the parameters being tested, for example, to check that the generated stop loss is higher than the generated ROI at level 1. How can I access it in the hyperopt_loss_function?

Thank you for your help and work,
Nicolas

**Comment by xmatthias** [comment]
you can get regular output with both print or logger output in single process mode (`-j`).
This should be sufficient to debug both a loss function or a strategy until you're sure it's stable.


in multiprocessing, it seems to be a bit a question of luck (it works one out of 10ish times) - and is most likely either a rich bug - or an oddity in how python works with multiple processes.

**Comment by NicolasGuigui** [comment]
Thank you, I just tested it and in fact it works and I hadn't thought of this tip which is sufficient for debugging in fact.

Do you want me to make a pull request to add a part in the documentation to add this "tip"?

I also asked a question about retrieving parameters during testing. Is it possible to recover them in the hyperopt_loss_function function?

> I would also like to take advantage of this ticket because I would like to add conditions to access the parameters being tested, for example, to check that the generated stop loss is higher than the generated ROI at level 1. How can I access it in the hyperopt_loss_function?

**Comment by xmatthias** [comment]
well i'm not sure where you'd add it - as it MAY make sense in either hyperopt-loss - or in a general hyperopt section - as you'll hit the same when outputting from a strategy.

---

it's not about "recover" - they're known - but not provided to the loss function - and i'm not sure that makes sense, either.

a loss function should evaluate the results (was it consistently profitable, ...) - not "i don't like that you compare RSI with 50".

technically, it'd be pretty simple (add another argument to the loss) - from a usage (and explanation) perspective - it'll be pretty difficult to use - as it's a dict - but a dict containing "all or nothing" (e.g. with `--spaces buy` - there'll only be the buy space, no stop or ROI values).
There's another dict containing "what wasn't optimized" - but again - you can't rely on either being there

example:
Optimizing ROI:
```
params {'roi_t1': 1117, 'roi_t2': 502, 'roi_t3': 371, 'roi_p1': 0.084, 'roi_p2': 0.153, 'roi_p3': 0.093}
not optimized {'stoploss': {'stoploss': -0.071}, 'trailing': {'trailing_stop': False, 'trailing_stop_positive': 0.05, 
'trailing_stop_positive_offset': 0.1, 'trailing_only_offset_is_reached': True}, 'max_open_trades': {'max_open_trades': 3}, 'buy': 
{'buy_block': 7.211, 'buy_enabled': True, 'buy_high_lookback': 101, 'buy_volume_mean': 31, 'enter_low_lookback': 90}, 'sell': 
{'sell_low_lookback': 106}, 'protection': {'coolback_lookback': 5, 'stop_duration': 5}}

```

optimizing sell:

```
params {'sell_low_lookback': 111}                                                                                                            
not optimized {'roi': {'0': 0.33799999999999997, '174': 0.132, '471': 0.033, '600': 0}, 'stoploss': {'stoploss': -0.071}, 'trailing':        
{'trailing_stop': False, 'trailing_stop_positive': 0.05, 'trailing_stop_positive_offset': 0.1, 'trailing_only_offset_is_reached': True},     
'max_open_trades': {'max_open_trades': 3}, 'buy': {'buy_block': 7.211, 'buy_enabled': True, 'buy_high_lookback': 101, 'buy_volume_mean': 31, 
'enter_low_lookback': 90}, 'sell': {}, 'protection': {'coolback_lookback': 5, 'stop_duration': 5}}      
```

At this point - the format is "raw" - so (especially for roi and stop parameters) - you get the raw dimensional values - which were not yet transposed back to what they should be (compare the ROI value between the two outputs).

**Comment by NicolasGuigui** [comment]
Ok I understand and it makes sense.

Thank you.
