### ISSUE TITLE
Plotting Hyperopt raw data. 

### ISSUE THREAD

**Issue by xenon1001** [freqtrade/freqtrade#10543]
Operating system: ubuntu 24
Python Version: 3.10
CCXT version: 4.3.70
Freqtrade Version: 2024.7
  
## Your question
I'm looking to visualize the results from Hyperopt to analyze the impact of different functions. The files I discovered in the user data folder have a '.fthypt' extension. They appear to be structured like JSON files, but they aren't actual JSON files, which makes reading them a bit tricky. Has anyone come across this type of file and knows how to extract the features so I can convert them into a dataframe and process the rest? or is there another way to export Hyperopt processing data?

**Comment by xmatthias** [comment]
You can use the tools freqtrade provides - namely `hyperopt-list` and `hyperopt-show` (to show details for one epoch).

The format itself is semi-custom to freqtrade (being open source - everyone can read how we write it) - but it's not considered part of the interface - so changes to it's structure / how we write it is seen as internal change.

**Comment by xenon1001** [comment]
@xmatthias
Thanks for your explanation. I wrote the script to convert it to JSON anyway. not sure if it's working flawlessly or not but handled what I had in mind. If you would like I can share it here.

**Comment by xmatthias** [comment]
well technically, it's json already - though one json object per line (so it can be appended).

what i mean is though - that's an implementation detail, not something actually relevant, so it could be changed without notice if necessary.
