### ISSUE TITLE
Loading trades from the DataProvider is hardcoded to futures

### ISSUE THREAD

**Issue by froggleston** [freqtrade/freqtrade#10540]
## Describe your environment

  * Operating system: WSL2 Ubuntu 20.04
  * Python Version: 3.11.9
  * CCXT version: 4.3.79
  * Freqtrade Version: 2024.8-dev-2ffe93820
  
## Describe the problem:

I have downloaded BTC/USDT spot data on the 5m and 1h timeframes using the `--dl-trades` command. When running backtesting, I expected that the trades data would be loaded and available. The orderflow columns are populated correctly in the main dataframe, but there was no data (all rows were `NaN`s).

When digging into the code, it seems that loading data from the dataprovider is hardcoded to TradingMode.FUTURES, even though SPOT seems to download fine and can be loaded if this is changed to TradingMode.SPOT.

### Steps to reproduce:

  1. Load SPOT trade data with --dl-trades
  2. Run backtesting in SPOT mode
  
### Relevant code exceptions or logs

```
Loading all feather spot candle data: 20240801-20240816 [/mnt/h/freqtrade_data/binance_json/binance]
[flow_minfrog_v14] Loaded 4189 rows of TradingMode.SPOT data for BTC/USDT from /mnt/h/freqtrade_data/binance_json/binance
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: orderflow, dtype: object
```

When setting the following hardcoded line in dataprovider.trades() to TradingMode.SPOT, it works fine: https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/data/dataprovider.py#L532

Edit:

It seems that the data is incomplete for spot? `trades`, `total_trades`,`max_delta`, `min_delta` , `delta`, `bid` and `ask` are populated. `orderflow`, `imbalances` and the stacked columns are not.

**Comment by xmatthias** [comment]
I'm ... not entirely sure i understand the 2nd part ? 

If the appropriate data is loaded - then spot and futures won't differ - really - obviously assuming the data is there.

Now you might need to be careful - i'd print the "tail" of the dataframe instead - and ensure that the trades data ends at the same time than the candles (or print something in the middle where you're sure data is there).

`freqtrade list-data --show` and `freqtrade list-data  --trades --show` might help with that (they have additional options to filter on specific pairs - on big datacollections they can be pretty slow).

**Comment by froggleston** [comment]
I think the TradingMode does matter, as with the `--trades` option, it does list spot as the type?
![image](https://github.com/user-attachments/assets/8fadd33e-df96-42e5-baaf-c7339fd6f677)

If I use the code as is, I get the public trade-based dataframe series being NaNs. If I change the dataprovider code to TradingMode.SPOT, it works (but only for the columns I specified - the imbalances for example do not show any data - again, only NaNs)

**Comment by xmatthias** [comment]
the first point (it shouldn't be hardcoded) i didn't argue about :laughing: - and that's fixed (see linked commit).

The moment you get some of the orderflow columns populated - there's no longer a differentiation between spot and futures (i'm sure of that). 
I also know it works - as i did most of my dry/live tests on spot (not futures).

The most likely cause will be configurations (or data availability)  - for example the imbalances will populate in a "filtered" way - filtering on "big enough volume" - which can obviously be different between spot and futures).

https://github.com/freqtrade/freqtrade/blob/4ca6e617268442e945593dc57c9b60f5116f6dbf/freqtrade/data/converter/orderflow.py#L255-L262
