### ISSUE TITLE
Can't set Asset Mode to Single-Asset Mode on Binance

### ISSUE THREAD

**Issue by thmeta** [freqtrade/freqtrade#10561]
I'm preparing for live trading on Binance but I noticed it's not possible to use Single-Asset Mode for my region. I guess it's not possible to use freqtrade in this case, but can someone confirm ? If not, is there a workaround for this?

**Comment by stash86** [comment]
Maybe give us more info. What is your region?

**Comment by thmeta** [comment]
Why does it matter? Basically, Binance doesn't allow me to change "Asset Mode" to "Single-Asset Mode", and the only available option is "Multi-Asset Mode". Question is, if I can use freqtrade in this case somehow, or not?
![image](https://github.com/user-attachments/assets/faeedc9e-c0f5-409f-867e-8e77876ac2e2)

**Comment by froggleston** [comment]
No, you can't trade cross margin, as the docs clearly state.

**Comment by thmeta** [comment]
So, since it applies to all users in Europe, looks like freqtrade becomes unusable for EU users when it comes to futures trading :-(
