### ISSUE TITLE
Freqtrade with Kraken: "freqAI is not enabled" Error When Running Strategy

### ISSUE THREAD

**Issue by mdelhaous** [freqtrade/freqtrade#10569]
Hey everyone, 

I'm running into an issue with Freqtrade on Kraken. I'm trying to use the FreqaiExampleStrategy.py strategy but keep getting this error:

**freqtrade.exceptions.OperationalException: freqAI is not enabled. Please enable it in your config to use this strategy.**

Here’s my setup:

_Config file:_ config_kraken.example.json
_Strategy file:_ FreqaiExampleStrategy.py from the official repo
_Command used:_**freqtrade trade --config config_kraken.example.json --strategy FreqaiExampleStrategy --freqaimodel LightGBMRegressor**

I found out that the issue might be due to Kraken’s API not providing enough historical OHLCV data, which freqAI needs to work properly.

Has anyone managed to get freqAI strategies working with Kraken, or is there a workaround? Also, if you have any strategy recommendations that work well with Kraken, I'd appreciate the suggestions!

Thanks in advance!

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

I don't see how this differs from #10567 - which contains the same answer you'll also get here.

for clarity for future readers - pasting that answer here:
> It [freqai with kraken] won't work due to technical limitations of the kraken API.
> Kraken does not offer historic ohlcv data (it must be converted from trades data - where downloading is a very slow process).
Exactly this data (in a timely manner) is however key for freqAI - so it's technically not possible to run a freqAI enabled strategy on kraken.

closing as duplicate.

**Comment by mdelhaous** [comment]
Could you please specify which issue template you're referring to? The template helps us address issues more effectively. Without it, we may need to close issues as duplicates.

Thanks for your understanding.

@xmatthias

**Comment by xmatthias** [comment]
The one you get as content when opening a new issue - the one you deleted and replaced with your own content.

**Comment by mdelhaous** [comment]
I didn't pay attention, sorry.
