### ISSUE TITLE
Hyperopt  Logging/Output issue - rich table can not be scrolled and causes huge logs

### ISSUE THREAD

**Issue by Cristy94** [freqtrade/freqtrade#10572]
## Describe your environment

  * Operating system: Windows/Linux
  * Python Version: 3
  * CCXT version: 4.3.65
  * Freqtrade Version: 2024.7.1
  
## Describe the problem:

There are several issues I encountered with the new rich table output for hyperopt results:

- I can't see all results, table can not be scrolled after screen height is reached
- Entire table is flashing and is hard to read when viewed through a SSH aggent (e.g. Putty)
- Docker output/logs are now huge, as the entire table is re-logged every second
- Trying to open directly the logs in an editor (e.g. nano) crashes the editor (likely because the logs are no huge)

### Steps to reproduce:

  1. Run hyperopt
  2. Try to view the results table
  3. After several steps, a maximum height is reached, and you can not see new entries, instead you see only three red dots:
<img width="881" alt="image" src="https://github.com/user-attachments/assets/24708fd1-f593-4305-ab7d-f460e9f472ab">

  
### Observed Results:

  * What happened?
  * Hyperopt results are hidden
  * What did you expect to happen?
  * Be able to see all hyperopt results

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
                                                     │        │   71/10000 │     43 │   23     0    20  53.5 │     -0.16% │   -6.678 USDT   (-0.67%) │        5:20:00 │    6.67799 │  27.071 USDT    (2.70%) │
                                                      │        │   72/10000 │    228 │  176     0    52  77.2 │     -0.14% │  -31.005 USDT   (-3.10%) │        3:02:00 │   31.00467 │  69.913 USDT    (6.94%) │
                                                      │        │   73/10000 │     29 │   20     0     9  69.0 │     -0.39% │  -11.182 USDT   (-1.12%) │        3:56:00 │   11.18173 │  20.884 USDT    (2.07%) │
                                                                                                                                 ...       
  ```

**Comment by Cristy94** [comment]
Maybe this is related: https://stackoverflow.com/questions/66355239/vertical-overflow-of-table-in-live-display-should-scroll-the-content

Apparently the application itself (Freqtrade) might have to delete old rows from the output, so latest results can be seen.

Also, maybe also related:  https://github.com/freqtrade/freqtrade/issues/10536

**Comment by xmatthias** [comment]
> Also, maybe also related: https://github.com/freqtrade/freqtrade/issues/10536

This is definitely not related. It's using terminal output as part of a jupyter like cell (colab != jupyter).
That's flimsy to begin with, i wouldn't bet it ever worked - and is not a supported way to run freqtrade.

---

> I can't see all results, table can not be scrolled after screen height is reached

I can somewhat recreate this - though rich seems to work oddly in this regard - and is not consistent (it may work correctly in one session, but not in the other).
While the solution in the stackoverflow thread seems nice at first - i'm not sure it is- as it's potentially re-rendering the table on every row multiple times (up to "row" times) - especially if results get large / the terminal size detection fails.
 
Anyway, we should however be able to provide a fix for this.

---


For the rest - i can't recreate (or understand)  your concerns so far - at least not using sane approaches.

> Docker output/logs are now huge, as the entire table is re-logged every second

How are you generating "docker logs" ? 
running hyperopt with docker will be using `--rm` - so log size shouldn't be a problem considering the output (`--log-file`) will not contain the table.
combining everything - it sounds a bit like you're piping the output to a file (`> myfile.log`). 
This will be huge - sure - but (unless used through docker) should be captured by rich which will change the output (essentially, it'll remove coloring).
It's however not really a mode we'd recommend or aim to support.

In reality - you'll want to get the table afterwards - best use `freqtrade hyperopt-list` to get the full previous result.

> Trying to open directly the logs in an editor (e.g. nano) crashes the editor (likely because the logs are no huge)

Simple solution: Use a better editor - vim doesn't have problems with big files (not related to freqtrade though).
Freqtrade will not attempt to fix nano - nor should we.

> Entire table is flashing and is hard to read when viewed through a SSH aggent (e.g. Putty)

I've only used it through the linux ssh client - and it's working perfectly fine through that. sounds like a putty oddity (maybe a limitation of what it sends as "supported formatting") - best try a different ssh client. 
Also - i've seen very old versions of putty around - so maybe it's just a matter of updating to a more recent version (not saying that's necessarily the case - though putty you usually download once, and never touch again - at least that's my experience).

**Comment by Cristy94** [comment]
Thanks for the response!

So, the problem is that I simply can't see more than 50-70 lines of HO output, and I usually try it for 100-1000 epochs, which makes the fancy table/logs kinda useless.

> How are you generating "docker logs" ?

I simply have the hyperopt container running. If I try to open the  logs output `docker logs freqtrade_ho`, it takes too long to open to be usable:

https://github.com/user-attachments/assets/e5648892-ba04-429a-8705-5a9bd7de9d4e

The flashing is acceptable, and also the opening of logs in a different screen is not needed if the live table works properly.
The scrolling is the only thing that's really a breaking bug.

**Comment by xmatthias** [comment]
and yet, it really isn't if you use `freqtrade hyperlopt-list` - which is a very simple workaround - and should in theory even work while the main hyperopt process is still running - though i didn't test that explicitly.

For docker - you might be able to use `docker compose logs --tail 1000` (or whatever number) - which limits the output to the last few rows.
