### ISSUE TITLE
I want to control new trades after stoploss occurs.

### ISSUE THREAD

**Issue by shio2345** [freqtrade/freqtrade#10595]
I would like to get advice on how to build a logic.
 I would like to build a logic where the next trade is not executed for a period of 5 hours after the stop loss (except trailing stoploss)occurs.
 I could not build it well with custom stop loss(), probably because I also set a trailing stop.
 If possible, I would like to record that the stop loss occurred in the chart data frame.
 Could you please give me some ideas?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

What you're looking for is the [stoploss guard](https://www.freqtrade.io/en/stable/plugins/#stoploss-guard).
It'll lock one (or all) pairs - preventing new trades on these pairs.

in the default setting (with `required_profit = 0.0`) - it'll apply to all losses - but will ignore "positive stoplosses" - which in the end are trailing stops that triggered once the trade was in profit.

**Comment by shio2345** [comment]
I am so sorry for asking a question that ignored the template...
Thank you for sharing the reference link.
I'll attempt to use this as a reference to build the logic.

**Comment by xmatthias** [comment]
well plugins are a configuration setting - really - there's nothing to "build the logic" - just reading and understanding the docs, applying them - and verifying it works the way you desire.

**Comment by shio2345** [comment]
I completely missed the pulgins section of the documentation. I will carefully check the details of the documentation once again.
Thank you for your patience.
