### ISSUE TITLE
PercentChangePairList: Change direction

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#10601]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.8 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Can I see the change direction (increase or decrease of the asset value) of PercentChangePairList by setting a specific parameter?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by myNextCoder** [comment]
Ok, I see, finally I need to set a positive min value, to have good coins, which are increasing for long trading :)

**Comment by myNextCoder** [comment]
According to my first tests, there might be an issue with the lookback timeframe of 1h. 30m or even 5m both work fine, but not 1h. And as I just discovered, 4h does not work either. Are 1h and 4h both working correctly in your tests?

**Comment by xmatthias** [comment]
well "not working" is kinda pointless - as it doesn't explain what we're looking for.

It'll work for all timeframes available for an exchange - obvioulsy if you're on an exchnage that doesn't offer 4h - it'll not work - and that's expected.

**Comment by myNextCoder** [comment]
I understand. Obviously on gate.io this lookback mechanism does not fit on 1h and 4h. I go on with my tests, also on further exchanges, giving you code examples, if I cannot clarify myself.

**Comment by xmatthias** [comment]
i'm not sure what you're comparing - and you apparently don't wan't help with it - otherwise it wouldn't be such blurry / imprecise comments.

Please keep in mind though that even with "1h" and lookback of 1 - - it'll not be the last 60 minutes (you can get that by using 1m - 60)- but it'll be the last 1 _closed candle_.

**Comment by myNextCoder** [comment]
I am just about to see the result of my first tests. Learning as many basics without using your time. I reach you again with precise questions, if needed.
