### ISSUE TITLE
How to enter both sides and then resolve it in custom_stake_amount?

### ISSUE THREAD

**Issue by DeevsDeevs** [freqtrade/freqtrade#10613]
## Describe your environment
  * Operating system: docker
  * Freqtrade Version: 2024.7.1
  
## Your question
I'm facing an issue with Freqtrade while trading multiple instruments on the 1D timeframe. For each instrument, I generate an ML-based signal to determine whether I want to go long or short. However, after generating these predictions for each instrument, I want to rank them together using a specific function.

For example, let's say I have three instruments: BTCUSDT, ETHUSDT, and SOLUSDT. After generating predictions in populate_indicators, I get values like 1, 0.5, and 0.2. I would then like to rank these values, resulting in, for example, 1, 0.5, and -0.5.

The challenge is that Freqtrade, in live mode, processes each pair individually in the sequence populate_indicators -> populate_entry_trend. This means that when processing BTCUSDT, I can't access the predictions of ETHUSDT and SOLUSDT, since BTCUSDT is processed first.

To work around this, I attempted to set both enter_long = 1 and enter_short = 1 for each pair and then perform the ranking within custom_stake_amount. My idea was to cancel trades by setting the stake to None if the ranked predictions had conflicting signs, as mentioned in the Freqtrade documentation.

However, Freqtrade doesn't enter any trades when I implement this approach.

Is there an alternative method or a better approach to achieve this?

**Comment by hippocritical** [comment]
solved on discord, please close

**Comment by xmatthias** [comment]
If you're setting both enter_long and exit_long, you'll have [colliding signals](https://www.freqtrade.io/en/stable/strategy-customization/#colliding-signals) - which will be ignored as "strategy is undecided".

You'll therefore never get a call to any callback - as no entry will be happening.

closing as it seems to have been solved on discord.

**Comment by Costwen** [comment]
> solved on discord, please close

hi, where can i find the solved way? I also meet the same problem
