### ISSUE TITLE
Entering spot signals

### ISSUE THREAD

**Issue by aliengofx** [freqtrade/freqtrade#10615]
## Describe your environment

  * Operating system: Ubuntu
  * Freqtrade Version: Latest fq version with docker (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi! Currently, I'm testing some signals and I was just wondering, if in case I would change my entering conditions to enter in the open price after the signal, do I have to change any other settings in the freqtrade strategy. Otherwise is there possible to enter in the same candle with the signal, in the open or at least in the middle of it? Same logic for exits. If any of the above is possible with freqtrade, do I have to modify any settings? 
(In the picture below you can see my current state)
 
![photo_2024-09-04_16-27-50](https://github.com/user-attachments/assets/1eceff18-d0ca-4381-9128-7b38ab18bfa5)

**Comment by stash86** [comment]
There is no such setting. Market is fluid, there is no way you can guaranteed to enter at the exact open price. What you can do is to make sure your calculation time is fast enough so the bot will open the trade few seconds after the new candle opened. Using limit order will also make sure you don't get a big slippage

**Comment by xmatthias** [comment]
>  Otherwise is there possible to enter in the same candle with the signal, in the open or at least in the middle of it?

There is no signal until the candle is closed. It appears like the entry is "late" - but in reality - the entry usually happens the first moment the signal is available. Ideally, that's seconds after the new candle starts - but on slow / heavy strategies (strategies with tons of indicators, or configurations running tons of pairs) - this may be slowed down by the strategy processing logic. 

Now for the price - freqtrade has several [pricing options](https://www.freqtrade.io/en/stable/configuration/#prices-used-for-orders) - which will have differences in the price - but also if the order fills immediately (market order, limit order with "price-side=other" ) - or if the order might stay around until price "returns" to it (limit order with price-side same).

If these options (think about them as shortcuts) don't suffice - there's [pricing callbacks](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-price-rules) which will allow you to define the price any way you like - obviously with the same market constraints than ever - a market order placed way below the current price will simply not fill immediately - and may never fill or time out.

**Comment by aliengofx** [comment]
Well, I started using price-side=other for both entry and exit because sometimes the orders were not fulfilled but I guess it wasn't such a good idea in general. I haven't experienced the [pricing callbacks](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-price-rules) yet but maybe I will. I'm not entirely sure if that will help with my strategy. 


![Screenshot 2024-09-04 210107](https://github.com/user-attachments/assets/5f6233ed-4f72-43a2-8670-b00429917de9)

Also, I have one more question. Well, let's suppose I'm using the 30m time frame. For conditions, In case I need to check the value of a specific variable if is true as soon as possible, and not waiting 30mins for the response. How do I do that? In that case I may need to exit as soon as possible. 

Btw, thanks for your time!

**Comment by xmatthias** [comment]
well pricing configuration is a tradeoff - you want it at your desired price - or fast / now? :laughing: 
These tradeoffs are explained in the pricing docs - but that assumes some basic market understanding (how do orderbooks / order filling work).

There's no correct or wrong - as it'll fully depend on what you're expecting.

---

you can always use [callbacks - in this case the custom exit signal](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-exit-signal) for frequent checking.
Conditions there should be quick - and not take "too long" - as that'll slow your bot loop down.
