### ISSUE TITLE
Freqtrade Unable to Execute Real Trades on Kraken - Dry Run Works Fine

### ISSUE THREAD

**Issue by LaiWenKang** [freqtrade/freqtrade#10610]
Understood.

## Describe your environment

  * Operating system: Ubuntu 22.04.4 LTS
  * Python Version: Python 3.12.5
  * CCXT version: ccxt==4.3.93  
  * Freqtrade Version: freqtrade 2024.8
  
## Your question
I am currently experiencing an issue where Freqtrade operates as expected in dry run mode but fails to execute trades when running live on Kraken. AFreqtrade reports the wallet balance as 0 USDT in Telegram when live trading. However, API calls made directly using Python scripts show the correct balance. 

Additionally, I noticed that the balance is displayed with an .F suffix, such as USDT.F, in the API responses. I’m not clear on what this suffix signifies or if it’s related to the issue where Freqtrade fails to recognize the balance and execute trades properly.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

<img width="442" alt="Screenshot 2024-09-02 at 2 16 10 PM" src="https://github.com/user-attachments/assets/122c52e8-b910-4991-a0dc-d2b414aa5f97">

<img width="539" alt="Screenshot 2024-09-02 at 2 17 37 PM" src="https://github.com/user-attachments/assets/7c2d7871-7d66-461d-93b0-e7a4c2824048">

**Comment by xmatthias** [comment]
Well all that means is that you either didn't - or did incorrectly - specify your API keys in the freqtrade configuration, or you've got no balance in the configured coins.

you should also be VERY careful not to leak them - as you partially leaked them already - potentially making it easier to guess the keys - so you should definitely revoke the ones from the screenshot above.


Assuming your keys are correct (if they're not, you'll have errors in the log file) - you could try `/balance all` on telegram - which will show non-bot assets.

My suspicion is that the ".F" postfix is a sign that you're not actually owning USDT - but instead some other, derivate currency - though I've never used the kraken API without ccxt - which does pair naming translation.

**Comment by xmatthias** [comment]
The kraken docs confirm my suspicion - you're using the wrong endpoint - and are hence getting Futures data.

[TradeBalance](https://docs.kraken.com/api/docs/rest-api/get-trade-balance) is to retrieve Futures data 
> Retrieve a summary of collateral balances, margin position valuations, equity and margin level.

For kraken, freqtrade does not support futures at this point.
The correct endpoint is hence [balance](https://docs.kraken.com/api/docs/rest-api/get-account-balance) - or [balanceEx](https://docs.kraken.com/api/docs/rest-api/get-extended-balance).

i'd however recommend to use ccxt for such tests  - that'll make your code a lot simpler - and will avoid using the wrong endpoint - and the result will be as simple as the following:

``` python
import ccxt
exchange = ccxt.kraken({
    'apiKey': '<yourApiKey>', 
    'secret': '<yoursecret>', 
    })
_ = exchange.load_markets()
res = exchange.fetch_balance()
```
