### ISSUE TITLE
Can we run multiple bots for different strategies simultaneously? We have a scenario where we need to implement it. Any suggestion is welcome.

### ISSUE THREAD

**Issue by shubhamraut41** [freqtrade/freqtrade#10634]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
This will be your **very last warning.**
Another mal-formatted issue (only content in the title) with a missing template, and you'll **definitely** be blocked from interacting with this organization.

reference: https://github.com/freqtrade/freqtrade/issues/10587#issuecomment-2310314197

As mentioned in that post already - this issue goes (again) into the direction of "i wanna sell freqtrade as a service" - which we interpret as "we wanna scam people".
This is confirmed to some degree considering that you're apparently unable to open an issue the way it's designed as (you wouldn't open an empty word document and put all the content in the filename?!?), unable to fill out an issue template - and even more concerning - unable to **search the documentation**.

Let me repeat this one final time: 
Freqtrade is designed for single user use. 
We will not support, nor will we answer questions regarding your attempts to provide freqtrade as a service. 

While you're more than welcome to use freqtrade for your personal use - further questions in the direction of multi tenancy (you've been warned before) will not be answered - and will result in your account being banned from interacting with this organization - as we'll consider it spamming at that point.

---

Regarding the topic - a simple search in the docs would show you that [it's possible](https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade).
