### ISSUE TITLE
Newbie Question about running multiple bots.

### ISSUE THREAD

**Issue by vikashbaraiya** [freqtrade/freqtrade#10650]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi FreqTrade Team, Greetings!!! Am relatively newbie to Freqtrade Bot and unable to find an answer to a particular Use-Case as given below. Use-Case: One of our collaborating client is interested in knowing regarding the following functionality wrt to your Cryptotrading bot. ---- Is it possible in FreqTrade to create multiple strategies  within a single or multiple bot as chosen by the end-user? If yes, what is the solution to address the same. Looking forward to your inputs even if otherwise.  Thanks and Regards

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

Also, the content should go into the content section - not into the title.

---

While we can answer questions here - spending our free time digesting the documentation for users is not how we're going to be spending our time - as that will draw scarse resources away from actually useful development.

As a newbie, I'd recommend you read through the [freqtrade documentation](https://freqtrade.io) at least once to learn about the features freqtrade offers.
You should also not be offering services to clients in this case - as you'll not be providing them good service - so please advise them that you actually don't know about what you're trying to sell.

---


freqtrade is aimed at individual traders, not to be used to build a business on top of (which this pretty much sounds like).
That's a usecase we'll not be providing support for.
It's one strategy per bot - but you can run multiple bots. The solution can be found in the documentation.
