### ISSUE TITLE
Installation via setup.py fails

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#1065]
## Describe your environment

  * Python Version: 3.6.6
  * Branch:  Develop
  
## Describe the problem:

installing the bot in a clean virtual environment via `python setup.py install` fails twice:

1) Numpy not installed / needed for talib. Fixed by manually installing numpy beforehand
2) ccxt installation gets stuck and does not process. running `pip install -r requirements.txt` works fine in a clean environment.

**Comment by xmatthias** [comment]
will investigate this further.

i think it could be an issue with ccxt as it's only happening with this library (also in an empty sample project).

i therefore opened an issue there, mainly to chekc if others have this too
https://github.com/ccxt/ccxt/issues/3474

**Comment by rhamnett** [comment]
See https://github.com/freqtrade/freqtrade/issues/1073 - sorry I hadn't seen this ticket before posting

**Comment by xmatthias** [comment]
I think i'll close this as there is nothing on our side we can do (see https://github.com/ccxt/ccxt/issues/3474). 
Our documentation doesn't mention installing via `setup.py`, but `setup.sh` - which does use `pip install -r requirements.txt` - which works fine.
