### ISSUE TITLE
trade canvas drawing issue

### ISSUE THREAD

**Issue by uplight-dev** [freqtrade/freqtrade#10673]
## Describe your environment

  * Operating system: linux
  * Python Version: __Python 3.12.5___ (`python -V`)
  * CCXT version: __ccxt==4.3.93___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade docker-2024.9-dev-704e32b0__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the problem:
When lots of data is displayed (i.e. 6 month period for a 1H timeframe), zooming the canvas which displays the trade chart becomes garbled. Please see the attached image.

### Steps to reproduce:

  1. do a backtest in the Web version of freqtrade using a 6 month or more period with a 1H timeframe.
  2. zoom inside the period and start dragging the chart
  3. sometimes the chart becomes garbled and starts overlaying the price line over the entire canvas
  
### Observed Results:

  * What happened?
The chart becomes garbled and unreadable.

  * What did you expect to happen?
The chart should work even when working with higher amounts of data in it.

**Comment by uplight-dev** [comment]
![Screenshot_2024-09-17_11-14-44](https://github.com/user-attachments/assets/e6a372fa-0365-4877-be76-bee89639173b)

**Comment by xmatthias** [comment]
This is known - and has been reported upstream to the charting library (https://github.com/apache/echarts/issues/19981).

From a freqtrade / freqUI perspective, there's little to nothing we can do (it's also not the amount of data, but the speed of zooming that makes this happen).

I'll be closing this here - as it's an issue with no actionable points other than "wait for upstream to resolve".

Best subscribe (and/or comment on the upstream issue to raise priority for them) for updates on this.

**Comment by uplight-dev** [comment]
Thank you!
