### ISSUE TITLE
dynamic-whitelist detects new coin without enough historic data

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#1067]
## Describe your environment

  * Python Version: 3.6.6 (`python -V`)
  * Branch: Develop
  * Last Commit ID: 0b3190552ec02b9a5b03dbe60896af06462d36bb
  
## Describe the problem:

running the bot with --dynamic-whitelist 20 picked up "HOT/BTC" today. 
it's a coin [listed today](https://support.binance.com/hc/en-us/articles/360007931511-Binance-Will-List-Holo-HOT-on-2018-07-24)

This coin should not be picked up as it does not have any historic candles, so signals may fluctuate randomly without control.
Also i don't understand how it can be used as there is a check for volume in place, and i doubt it is in the top20 coins for the last 24 hours.

this is the result from today - it did 32 trades in the last ~12 hours - probably all buying / selling right away, at least that's how i noticed it in the last hour.

![2018-07-24-165421_526x448_scrot](https://user-images.githubusercontent.com/5024695/43150618-412e229c-8f62-11e8-991c-f230a2303e89.png)

```
Performance:
...
7. HOT/BTC -283.87% (32)
```

A check for "is listed since 100 x interval" should be implemented to make sure there is enough historic candles to generate signals safely.

**Comment by iuvbio** [comment]
I think this should be possible to resolve in the strategy by setting a buy signal only if, for example, the ema100 indicator is populated. If the strategy requires an indicator and there is not enough data to calculate it, I don't think a buy signal will be set.

**Comment by xmatthias** [comment]
that would be a workaround, yes.

but the coin should not even be in the whitelist (at least not in my opinion)...

**Comment by iuvbio** [comment]
I had the same problem with coins that I thought should not be in the top20 by volume, but they actually were. I output the quote volume in the log and it seems the pairlist is working correctly. Maybe the whitelist should not be generated based on the volume of the latest candle only, but on the last 20 (arbitrary) or so?

**Comment by xmatthias** [comment]
I'll close this one as it can be handled by using VolumePairList with precisionFilter set to on, since new coins are very low in value at the start of the period.
