### ISSUE TITLE
Bybit Exchange API (unified account)

### ISSUE THREAD

**Issue by arashhadad1** [freqtrade/freqtrade#10674]
* Operating system: ubuntu 22.04
  * Python Version: _____ (3.10.12)
  * CCXT version: _____ (4.3.88)
  * Freqtrade Version: ____ (freqtrade 2024.8)
  

Hello guys 
i am just trying run the bot on spot with bybit api but got unified account error , i have created sub account and trying it's api but get same error 
<img width="959" alt="Screenshot 2024-09-17 at 21 22 17" src="https://github.com/user-attachments/assets/e0ace596-f145-4346-8aef-57d52bf5f67b">

any idea ?

**Comment by xmatthias** [comment]
Support for unified accounts was added in the latest develop version - after Bybit disabled the possibility to create regular  (standard) subaccounts.

as such, please either use the develop version - or wait for the next update.

**Comment by arashhadad1** [comment]
ok , can you tell me how i can use develop version ? and how long next update will take ?

**Comment by xmatthias** [comment]
Usually, we release around the end of the month - but there's no precise date as to when an update will happen.

[Installation instructions](https://www.freqtrade.io/en/stable/installation/) (make sure to switch to your install method) do contain the information on how to switch to develop for  the respective, supported installation methods.

**Comment by aliengofx** [comment]
Hi! Here using bybit. It worked for a while with the older develop one but after pulling the latest version (with docker) I keep getting this error below. Not sure if there is any other parameter I need to set up as well. I couldn't find anything on the docs yet. Thanks!

![photo_2024-09-24_21-32-00](https://github.com/user-attachments/assets/b1a58fc9-f562-4069-bb5b-2658b8f48698)

**Comment by xmatthias** [comment]
@aliengofx don't see this as related tbh.

please open a new issue filling out the issue template (and paste the logs as code, not as screenshot) - thanks.

**Comment by aliengofx** [comment]
Ok, will think about it but since it's unusual there might be some errors with my configs/strategy. I'll double check that and see if it fixes it.

**Comment by xmatthias** [comment]
@aliengofx it's related to a recent change - previously "fallback" behavior was necessary.

Should work again in the most recent version (just pushed).
