### ISSUE TITLE
How to connect kraken demo account?

### ISSUE THREAD

**Issue by winsonet** [freqtrade/freqtrade#10685]
## Describe your environment

  * Operating system:  Mac OS 15
  * Python Version: 3.12.2 (`python -V`)
  * CCXT version: 4.4.5 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.9-dev-3bbc6cbab  (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I want to make the demo trading in kraken's demo account (https://demo-futures.kraken.com/), I also tried to generate the API in demo site (https://demo-futures.kraken.com/settings/api) , and set the config below

```
"dry_run": false,
"exchange": {
        "name": "kraken",
        "key": "f/8M/rnoQV0KTxLlRZ*******",
        "secret": "Hqjz7GuGKI1jQXUezgNlax/saS5170mBRZZwh4a*******",
        "ccxt_config": {
            "enableRateLimit": true
        },
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 3100
        },
        "pair_whitelist": [
            "BTC/USD"
        ],
        "pair_blacklist": []
    },
```

and I got the below error

```
freqtrade.exchange.common - WARNING - get_balances() returned exception: "Could not get balance due to AuthenticationError. Message: kraken {"error":["EAPI:Invalid key"]}". Retrying still for 3 times.
```

I don't know whether need to change any settings for that, or `freqtrade` can't support the demo site? 

Thanks!

**Comment by xmatthias** [comment]
Please revoke your API keys  - even though they're partially obfuscated, you're still making it easier for potential attackers to test them - as they now only need to test for the last few digits.


First off - freqtrade doesn't support kraken futures.

Then - we've removed support for demo / sandbox accounts (probably 2 years ago?). Volume on these markets is VERY bad, so you can't rely on any results you get from there (you place a (medium sized) market order, and it may slip 10% or more - which ain't going to happen in reality).
The only "real" use for demo accounts is in testing the API directly - so it's not something users will require.

Instead, freqtrade has the concept of dry_run - it'll not require your API keys, run against real market data - simulating trades.
it provides a much clearer picture regarding the actual use of a strategy (or failure of a strategy).

**Comment by winsonet** [comment]
I see, thanks for your reply!

In my case, I just want to see whether it can be worked to open a trading order, and I don't want to open an order casually in my live account 😅

**Comment by xmatthias** [comment]
well as mentioned - kraken futures is not supported at this point - so what you're trying to do will not work anyway.

**Comment by winsonet** [comment]
got it, thanks!
