### ISSUE TITLE
Unexpected strategy behavior with 1d timeframe in dry run mode

### ISSUE THREAD

**Issue by GabrielBertoli** [freqtrade/freqtrade#10680]
Operating system: mac os
Python Version: Python 3.11.9
CCXT version: ccxt==4.3.21
Freqtrade Version: freqtrade 2024.4

## Describe the problem:
Unexpected strategy behavior with 1d timeframe in dry run mode

*Explain the problem you have encountered*
I've observed a discrepancy between the expected behavior of my strategy with a 1d timeframe and what I'm seeing in dry run mode. The strategy appears to be processing data and making decisions more frequently than expected for a daily timeframe.

### Steps to reproduce:
With a 1d timeframe and process_only_new_candles = True:

The strategy should process data and make decisions once per day when a new candle is completed.
Functions like populate_indicators(), populate_entry_trend(), and populate_exit_trend() should be called once per day, right?
Entry decisions should only occur on daily candle closes.
Exits (like stoploss and ROI) can be checked more frequently.
  
### Observed Results:
The strategy appears to be processing data and making entry decisions multiple times within a single day.
populate_indicators(), populate_entry_trend(), and/or populate_exit_trend() seem to be called more frequently than once per day.

### Relevant code exceptions or logs
timeframe = '1d' 
process_only_new_candles = True

Is there a known issue with how Freqtrade handles 1d timeframes in dry run mode?
Could there be any configuration settings or strategy implementation details that might cause this behavior?
Are there any debugging steps you'd recommend to help isolate the cause of this unexpected behavior?

**Comment by xmatthias** [comment]
> Functions like populate_indicators(), populate_entry_trend(), and populate_exit_trend() should be called once per day, right?

with `process_only_new_candles = True` - that's a correct assumption _for the most part_.

It's not a correct assumption if you're using dynamic pairlists that do more than sorting. 
If a dynamic pairlist refreshes, and pair XYZ is replaced with pair ABC at 11:00 am ... then the `populate_*()` methods will be called at that time for the new pair.
You also can't really prevent this (it also wouldn't make sense, really) reliably except by using a static pairlist, but you can prevent acting on this by setting `ignore_buying_expired_candle_after` to a sensible number - so "late" signals are ignored by the bot.

**Comment by GabrielBertoli** [comment]
Thank you for the clarification. I'd like to provide some additional context and ask for further clarification:

1. I'm using a static pairlist, so the dynamic pairlist refresh scenario you mentioned shouldn't apply in my case.

2. Regarding backtesting, I've been using the following command with --timeframe-detail:
   freqtrade backtesting --config config.json --strategy Mystrat --timerange=20240101-  --fee=0.001 --timeframe 1d --timeframe-detail 5m

   My understanding is that using --timeframe-detail essentially translates to process_only_new_candles = False in this context. Is this correct?

3. For comparison, when I want to backtest with process_only_new_candles = True, I use:
   freqtrade backtesting --config config.json --strategy Mystrat --timerange=20240101-  --fee=0.001 --timeframe 1d

4. Given this setup, are you suggesting that I need to add the `ignore_buying_expired_candle_after` parameter with a sensible value to make the dry-run behavior match the backtest behavior?

5. If so, could you provide guidance on what a "sensible number" for `ignore_buying_expired_candle_after` might be in the context of a 1d timeframe strategy?

6. Are there any other settings or considerations I should be aware of to ensure consistency between backtesting and dry-run behavior for a 1d timeframe strategy with a static pairlist?

Thank you for your help in clarifying these points.

**Comment by xmatthias** [comment]
> My understanding is that using --timeframe-detail essentially translates to process_only_new_candles = False in this context. Is this correct?

Well no
Signals will be produced on the main timeframe. you use `--timeframe-detail` in backtesting to get more resolution for other reasons (callbacks, ROI, stoploss, ...). On a 1d timeframe, that's probably a must to get even remotely reliable results.

Entries will however still not happen in the middle of a candle in backtesting.

`ignore_buying_expired_candle_after` makes sense to avoid "late entries". 
There's a few reasons for this - dynamic pairlists being one - `process_only_new_candles = False` (and unstable strategies which produce signals in the middle of a candle) being another - sold trades (freed trade slots) being the other (probably the most common one besides dynamic pairlists). 
An example for the last point: say you trade with 3 parallel trades - and have all 3 slots filled - now trade B closes after 45% of the candle - the bot would look to enter a new trade for a different pair. This is often not desired - as the signal is now 45% of a candle old.

Sensible values for this depend on what you're trying to assume (is a signal old after 1h on a 1d timeframe? after 5 minutes?)
Most importantly - make sure it's > your overall calculation time (if your strategy takes 5 minutes to calculate indicators for all pairs - having this value < 5m will lead to no more trades).


6. check your order execution settings (pricing, timeouts, ...). you can cheat backtesting quite easily with custom pricing  -which can produce orders that would never fill on live.
