### ISSUE TITLE
No response from telegram

### ISSUE THREAD

**Issue by 0jessica0** [freqtrade/freqtrade#10681]
-->

## Describe your environment

Operating system: ____windows（no docker）
Python Version: _____3.11.9 (python -V)
CCXT version: _____4.3.98 (pip freeze | grep ccxt)
Freqtrade Version: ____2024.9 (freqtrade -V or docker compose run --rm freqtrade -V for Freqtrade running in docker)

## Your question

Hi, I have some questions about telegram settings.
I think I set up the telegram correctly, cause I got the first `/balance` response.
But after that no matter what i click there is no response at all. And there is nothing on the log.
But I can still get the exit and new trade info from telegram.

Where can I start to find what the problem is, so that I can use the Telegram to control the bot.
Thanks

**Comment by xmatthias** [comment]
That's difficult to say - if you got a `/balance` response - then that means it's working (or was working).

your best bet is to carefully look at the logs - and try to restart the bot (and look at the logs again).

If you've reused the same telegram bot on 2 freqtrade bots (need to be clear here - both are bots :laughing:) - then this could cause such behavior (even if the 2nd bot was stopped again).
That would throw of the "receiving updates" (how it  get's your messages / commands) from both bots in my experience (a bit a question of luck what exactly happens) - but usually do work still for sending notifications.

The logs would contain a notification about this.
