### ISSUE TITLE
How is Freqtrade working out for everyone?

### ISSUE THREAD

**Issue by BatmanPDX** [freqtrade/freqtrade#1068]
I was just wondering, if freqtrade is making profits for anyone here? if so, what's your daily avg if you don't mind me asking.

**Comment by vertti** [comment]
Issue tracker is not the best place for these discussions. You should join our [chat room](https://join.slack.com/t/highfrequencybot/shared_invite/enQtMjQ5NTM0OTYzMzY3LWMxYzE3M2MxNDdjMGM3ZTYwNzFjMGIwZGRjNTc3ZGU3MGE3NzdmZGMwNmU3NDM5ZTNmM2Y3NjRiNzk4NmM4OGE).
