### ISSUE TITLE
How to disable /forceexit and /forceexit all？

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#10682]
## Describe your environment

* Operating system: Canonical Ubuntu 22.04
* Python Version: 3.10.12
* CCXT version: 4.3.88
* Freqtrade Version: 2024.8
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Is it possible to disable `/forceexit` and `/forceexit all` in telegram?

Thanks.

**Comment by xmatthias** [comment]
You can't, and i don't see why, either.

Teletram notifications are designed to be something personal - to be informed and get a quick overview about the bot's state.
They're not designed to be shared with others (the only reason i can imagine having this need).
