### ISSUE TITLE
Why only can not short in spot mode?

### ISSUE THREAD

**Issue by winsonet** [freqtrade/freqtrade#10686]
## Describe your environment

   * Operating system:  Mac OS 15
  * Python Version: 3.12.2 (`python -V`)
  * CCXT version: 4.4.5 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.9-dev-3bbc6cbab  (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

As your description below  (https://www.freqtrade.io/en/stable/leverage/#shorting)

> Shorting is not possible when trading with [trading_mode](https://www.freqtrade.io/en/stable/leverage/#leverage-trading-modes) set to spot. To short trade, trading_mode must be set to margin(currently unavailable) or [futures](https://www.freqtrade.io/en/stable/leverage/#futures), with [margin_mode](https://www.freqtrade.io/en/stable/leverage/#margin-mode) set to cross(currently unavailable) or [isolated](https://www.freqtrade.io/en/stable/leverage/#isolated-margin-mode)

I am just confused about why only can't short in spot mode?  and for now, it can't support futures in Kraken but it also can't short in spot mode, that's means I can only long in Kraken, right?

**Comment by xmatthias** [comment]
well your digestion is exactly the wrong way around.
Spot markets don't allow for short trades (that's not a freqtrade limitation, but a fact about (crypto)markets in general).

The only markets that do allow for short trades are margin markets, or futures markets.
A selected number of futures markets are supported on freqtrade - but kraken is not one of these.

> that's means I can only long in Kraken

This is correct - and is also unlikely to change if i'm honest. Kraken is a niche exchange (with a very slow API) - one that not very many freqtrade users are using.

Best switch to one of the [supported futures exchanges](https://www.freqtrade.io/en/stable/#supported-futures-exchanges-experimental) if you're looking for an exchange that supports short trades.

**Comment by winsonet** [comment]
oh, yes, you are right, only the margin markets can be short it, thanks!
