### ISSUE TITLE
The set leverage keeps changing intermittently.

### ISSUE THREAD

**Issue by isonex** [freqtrade/freqtrade#10707]
## Describe your environment

  * Operating system:  window 10 
  * Python Version: Python 3.12.6
  * CCXT version: ccxt==4.4.5
  * Freqtrade Version: freqtrade docker-2024.9-dev-3bbc6cba
  

## Describe the problem:
    lev = 10
    def leverage(self, pair: str, current_time: datetime, current_rate: float,
                 proposed_leverage: float, max_leverage: float, entry_tag: Optional[str],
                 side: str, **kwargs) -> float:
        return  self.lev
  
    def confirm_trade_exit(self, pair: str, trade: Trade, order_type: str, amount: float,
                        rate: float, time_in_force: str, exit_reason: str,
                        current_time: datetime, **kwargs) -> bool:      
        spantime= current_time - trade.open_date_utc
        IsShort="short" if trade.is_short is True else "long"
        cur_profit=trade.calc_profit_ratio(rate)
                 
        logger.info(f"{self.version()}:exit-> {trade.pair} {current_time.strftime('%Y-%m-%d %H:%M')}:({spantime.total_seconds() /(60.0*60):0.1f}h) ID={trade.id} cur={rate:0.4f} open ={trade.open_rate:0.4f}  lev={trade.leverage:0.1f}  {exit_reason} {IsShort} profit={ cur_profit*100:0.2f}% ") 
        
        return True

During backtesting, after setting leverage and entering a position, when checking trade.leverage in confirm_trade_exit, the leverage sometimes appears different from what was initially set. 

The leverage should be set to 10 (lev=10), but sometimes it appears differently when checked in confirm_trade_exit.
The result of trade.calc_profit_ratio(rate) is being calculated using the modified leverage instead of the initially set leverage.

### Relevant code exceptions or logs
2024-09-25 20:48:43,819 - skzV9 - INFO - skzV9T1_0925_1:exit-> ROSE/USDT:USDT 2024-05-29 08:00:(8.0h) ID=821 cur=0.0941 open =0.0921 long atr_roi  lev=4.0   profit=8.11% 
2024-09-25 20:48:43,860 - skzV9 - INFO - skzV9T1_0925_1:exit-> LINK/USDT:USDT 2024-05-29 08:03:(8.1h) ID=822 cur=18.2230 open =18.5460 long atr_sl  lev=10.0   profit=-18.66% 
2024-09-25 20:48:44,536 - skzV9 - INFO - skzV9T1_0925_1:exit-> AR/USDT:USDT 2024-05-29 10:44:(10.7h) ID=823 cur=39.1820 open =38.1300 short atr_sl  lev=5.0   profit=-14.21% 
2024-09-25 20:48:44,561 - skzV9 - INFO - skzV9T1_0925_1:exit-> STORJ/USDT:USDT 2024-05-29 08:02:(8.0h) ID=824 cur=0.5617 open =0.5717 long atr_sl  lev=4.0   profit=-7.47%

**Comment by isonex** [comment]
I checked max_leverage and there are cases where it is less than 10.
This issue has been resolved.^^

**Comment by xmatthias** [comment]
well that was my expectation but i wanted to double-check :laughing:

leverage is respected IF it's below max_leverage - everything else wouldn't make sense ;)
