### ISSUE TITLE
Backtesting table in only 1 row for pair

### ISSUE THREAD

**Issue by michelecinque** [freqtrade/freqtrade#10700]
Hi Xmatthias,
it's possible modify the bt output tables to fit 1 only row for every pair? From 2024.8 version the bt table is different, but i use a script for analyzing bt and this new layout create some problems in my analysis.

Thankyou
Mike

![immagine](https://github.com/user-attachments/assets/1a39eb9c-3730-4770-8333-e2e467e1870a)

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Terminal size is determined automatically through rich.
If you're on a small terminal - it'll wrap (in a better, more readable way than the previous tables did - which your screenshot confirms).

it'll fit to one row assuming the terminal is wide enough - which doesn't appear to be the case in your screenshot.
Best make the terminal wider - which will also make the table look better again.

As an aside - it's text output designed to be human readable.
We don't guarantee output stability - so parsing the output in a script is definitely not something we support (or aim to support).
Freqtrade provides documentation and methods to read the stored backtest file - which i'd recommend to look into. That format isn't likely to be changed (and if it is, we'll try to provide some compatibility).

**Comment by michelecinque** [comment]
Thankyou for explaning this Xmatthias.
Mike
