### ISSUE TITLE
Why did stoploss change at backtest and hyperopt?

### ISSUE THREAD

**Issue by 8a2a8** [freqtrade/freqtrade#10705]
i have search all related document i know, search history issues and question

## environment

  * Operating system: win11
  * Python Version: 3.12
  * CCXT version: 4.3.79
  * Freqtrade Version:  2024.9-dev-d377d8462
  
## question

strategy stoploss configuration:
```
    stoploss = -0.25
    trailing_stop = True
    trailing_stop_positive = 0.003
    trailing_stop_positive_offset = 0.03
    trailing_only_offset_is_reached = True
```
when i run hyperopt and backtest, stoploss change, like as follow:
```
freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.026
```
i'm curious about why stoploss is not equal with backtest and hyperopt

**Comment by xmatthias** [comment]
well full startup logs will contain the answer to your question (where did it come from).

Essentially - there's really only 3 options
* from the strategy file (`Loading parameters from file <strategyfilename.json>`) - which suggests it was hyperopted with that value previously 
* from the configuration (stoploss can come from the configuration, too)

Logs (essentially up to the point you posted above) will be rather verbose about this if you take the time to read them carefully ;)

**Comment by 8a2a8** [comment]
ok,  I have found the reason. I made a basic mistake
