### ISSUE TITLE
LTC as stake_currency

### ISSUE THREAD

**Issue by vpotap** [freqtrade/freqtrade#1071]
is it possible to get LTC/USDT pair for binance trading?

Invalid configuration. See config.json.example. Reason: 'LTC' is not one of ['BTC', 'ETH', 'USDT', 'EUR', 'USD']

Failed validating 'enum' in schema['properties']['stake_currency']:
    {'enum': ['BTC', 'ETH', 'USDT', 'EUR', 'USD'], 'type': 'string'}

On instance['stake_currency']:
    'LTC'
Fatal exception!

**Comment by vertti** [comment]
Yes, you can trade LTC/USDT, but then your stake currency is USDT, not LTC. Binance does not have LTC as a base currency for pairs.

**Comment by vpotap** [comment]
Ok, if in start position with pair LTC/USDT and USDT is set as stake_currency but  I have all start balance in LTC only start balance with USDT = 0, is it possible to start trading ?
 WARNING - Unable to create trade: Available balance(0.000000 USDT)

**Comment by xmatthias** [comment]
in this case you would need to insert the trade manually in LTC depending on the strategy (could lead to loss!) - however the bot would sell all to USDT (so you can take this step manually too, with a more controlled rate).

Then the bot can open  positions from USDT to other currencies.
