### ISSUE TITLE
single entry/exit not enough for a Trade to get created

### ISSUE THREAD

**Issue by uplight-dev** [freqtrade/freqtrade#10715]
## Describe your environment

  * Operating system: __Linux__
  * Python Version: __Python 3.12.5___ (`python -V`)
  * CCXT version: __ccxt==4.3.93___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade docker-2024.9-dev-704e32b0__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

When a single entry/exit exists and no other entries/exits near it, a Trade is not created/ended. It is required that 2 or more entries besides eachother to actually have a Trade appear.

Is there any parameter I can modify to override this behavior?

Thank you!

**Comment by xmatthias** [comment]
This sounds like a bug / problem in your strategy.

Freqtrade is not looking for "multiple" signals (there's no logic for that) - only if signals [collide](https://www.freqtrade.io/en/stable/strategy-customization/#colliding-signals) - but that's not "consecutive" signals - but signals on the same candle.

Entries will always be acted on unless prohibited (callback, no open trade slots, out of capital, ...).
Exits can be prohibited via `use_exit_signal`, `exit_profit_only`, `exit_profit_offset` ... which is however usually a sign of bad signals.

**Comment by uplight-dev** [comment]
You were right, I realized I was expecting this to happen for live mode on a period that was in the past. 
In backtest it works fine, single entries do create a trade.

Thank you!
