### ISSUE TITLE
current profit and total profit

### ISSUE THREAD

**Issue by VerDoe** [freqtrade/freqtrade#10719]
Operating system: Debian 12 (bookworm)
Python Version: 3.11.2
CCXT version: 4.3.88
Freqtrade Version: 2024.8
  
![image](https://github.com/user-attachments/assets/480febc4-1925-454c-82af-f0ddceaf0c00)

I can query current profit with current_profit, how can I query total profit without making calculations? Is there also a variable for Freqtrade?

**Comment by xmatthias** [comment]
`current_profit` is provided to some (most?) callbacks - it's not a variable that's directly available on the trade object.

You won't get around doing calculations (in a computational sense - you don't really have to do these calculations in the strategy) - but you can use `trade.calculate_profit(current_rate)` - which will return a struct with `total_profit` and `total_profit_ratio` as elements.

This should work wherever current_profit is available - as that assumes a callback in a trade context, which will get the trade object, too.

**Comment by VerDoe** [comment]
That's exactly what I was looking for. I need it for custom_exit, because current_profit is there. Thank you very much!
