### ISSUE TITLE
How to understand the legend  within plot by draw with plot-dataframe

### ISSUE THREAD

**Issue by winsonet** [freqtrade/freqtrade#10722]
## Describe your environment

  * Operating system:  Mac OS 15
  * Python Version: 3.12.2 (`python -V`)
  * CCXT version: 4.4.5 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.9-dev-3bbc6cbab  (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I am  confused about how to read and understand the `enter_long` , `enter_short`, `Trade entry` and `Exit - Profit` legends in the plot, please take a look at below screen capture generated by `plot-dadaframe`

<img width="666" alt="image" src="https://github.com/user-attachments/assets/fe7bcea1-f4da-4eb2-8106-a9af2c3fa814">

I checked with the backtest result JSON file, the `Trade entry` is actually the order entry point, but why will show many other `enter_long` and `enter_short` points in the chart? From my understanding, the name `enter_long` should be the really enter long/short in `populate_entry_trend` method in the strategy

Can anyone show me why? Thanks!

**Comment by xmatthias** [comment]
well enter_long and enter_short are the signals your strategy generates.

a strategy can often generate tons of signals that are not acted - either because the market can't short - or for other reasons (like - it's already in a trade for this pair, there's all trade slots occupied, ...).

**Comment by winsonet** [comment]
I see, but for my understanding, the bot should make an order when the enter signal is true every time, if there are many signals in the short period, maybe that's mean there are something wrongs with the strategy, if the case like you said, then how can I know which enter signal is true and how to decide which one should count it for open the order or close the order?

**Comment by xmatthias** [comment]
well assuming your screenshot from above - after the 2nd signal, all signals will be ignored as the bot is in a position for this pair already (the trade starts with the circle - no close (trade exit) is visible).

The first signal is a different topic - this is most likely covered by a different trade (so no trade-slot was open).
you could also be "denying" entries via callback - or simply have changed the strategy between running the backtest and running the plot (plotting will always use the "current" strategy - so changes will make the plot invalid and not make sense).

**Comment by winsonet** [comment]
Got it, thanks for your explanation ！
