### ISSUE TITLE
Docker numpy dependency order

### ISSUE THREAD

**Issue by rhamnett** [freqtrade/freqtrade#1073]
Docker needs to install numpy first before other requirements.txt in order for it to be accessible when ta-lib is installed. This has been a common issue for any of my projects using Docker and ta-lib

Solution change Dockerfile to install numpy first:

# Install dependencies
COPY requirements.txt /freqtrade/
RUN pip install numpy
RUN pip install -r requirements.txt

**Comment by xmatthias** [comment]
is this actually causing a problem or is it just "odd" to have ta-lib show it failed (while it's there in the end ..)? 
i think ta-lib echos an error - but installs just fine in the end (at least that's what i observed).

trying to install numpy first did not "really" fix the issue as it reinstalled numpy anyway - but maybe that was a timing-issue back when i tried this myself (few months ago i think).

**Comment by rhamnett** [comment]
Not sure, I had to change the order for it to work correctly on a fresh checkout.

**Comment by rhamnett** [comment]
If you look here at another project crypto-signals you will see they have separated their requirements into two files too for the same issue

https://github.com/CryptoSignal/crypto-signal/tree/master/app

**Comment by xmatthias** [comment]
closing this since we implemented your suggested fix
