### ISSUE TITLE
Unlimited Marketcap Pairlist?

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#10742]
## Describe your environment
(if applicable)

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.9 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

Is it technically possible for you, to also make the marketcap pairlist unlimited, like the volume pairlist, going beyond the position of 250? This approach moves the responsibility (usefull or useless) from you as the programmer team to the trader. What do you think about this? 

*Explain the enhancement you would like*

**Comment by xmatthias** [comment]
Is it technically possible? sure - it's pagination.
is it worth our time to implement, ensure it's correctly working and maintaining it in the future? 
I don't think so - unless you can provide a _very compelling_ reason to do so.

It's not a responsability question either - but simply a "it's a pointless feature we'd be wasting our time" decision (which can be changed, but in this issue, i currently don't see arguments for).

if you're using a Pairlist beyond 250 (so the market-cap of that coin is 250 positions below the top coin) - you can just as well go with a "all" pairlist or Volumepairlist.
Tokens past 250 are rather unlikely to be listed on exchanges anyway - which auto-excludes them (you can't have a pair in your whitelist you can't trade on the exchange).

If you're looking for a specific pair you see missing, you can use the  new "category" feature - but again, i don't see why it should paginate beyond the initial response.

Unless you'll have some compelling reason as to why we should complicate our code with this - I'm going to close this as a question which has been answered.

**Comment by stash86** [comment]
Since there is no more follow-up, I assume you have your question answered.
