### ISSUE TITLE
connection problem

### ISSUE THREAD

**Issue by xiaosanxiao13** [freqtrade/freqtrade#10751]
I didn’t find this problem in the documentation. For some reasons, mainland China seems to be unable to connect directly to Binance using ccxt. What should I do in this case? Of course, I can open my clash to solve it, but there is a better solution. Is there any way?

**Comment by xmatthias** [comment]
Ccxt supports proxies - and would probably also work through a VPN.

Aside from this - we'll not provide assistance or guidance on how to circumvent your country's laws and regulations, sorry.


Thanks for your understanding.
