### ISSUE TITLE
recursive-analysis  - cashes with type error

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#10754]
## Describe your environment

  * Operating system: Linux Mint Una
  * Python Version: 3.10.4
  * CCXT version: 4.3.88
  * Freqtrade Version: 2024.9
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Failure to complete recursive-analysis on a strategy

### Steps to reproduce:

  1. Run: freqtrade recursive-analysis -c user_data/configsamplebtc.json --strategy AwesomeStrategy --timerange 20240101-20241002
  2. _____
  3. _____
  
### Observed Results:

  * What happened? The process stopped with Fatal error after starting to check for recursive bias
  * What did you expect to happen? I expected to see a complete list of recursive biases

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 45, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 162, in start_recursive_analysis
    RecursiveAnalysisSubFunctions.start(config)
  File "/freqtrade/freqtrade/optimize/analysis/recursive_helpers.py", line 102, in start
    RecursiveAnalysisSubFunctions.initialize_single_recursive_analysis(
  File "/freqtrade/freqtrade/optimize/analysis/recursive_helpers.py", line 70, in initialize_single_recursive_analysis
    current_instance.start()
  File "/freqtrade/freqtrade/optimize/analysis/recursive.py", line 196, in start
    self.analyze_indicators()
  File "/freqtrade/freqtrade/optimize/analysis/recursive.py", line 73, in analyze_indicators
    diff = (values_diff_other - values_diff_self) / values_diff_self * 100
            ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'str'
ERROR: 1
  ```

**Comment by xmatthias** [comment]
well recursive analysis works fine for me / my strategies - so it seems to be strategy dependant.

Please provide us with a minimal reproductive strategy (i assume by removing indicator after indicator to try and find what's causing it) - so we can investigate what your strategy does differently.
