### ISSUE TITLE
Use exchange staking reward as bot owned

### ISSUE THREAD

**Issue by klara31** [freqtrade/freqtrade#10757]
My exchange (Bitvavo) is offering staking profits for some assets. These rewards are paid in the stake asset, which means that my position increases. When checking the stake balance in telegram, it shows like:
``` 
 Available: 296.57720500
 Balance: 296.57720500
 Pending: 0.00000000
 Bot Owned: 293.98600000
```
How to get freqtrade to use the complete balance, so to put the earning from staking directly back into the bot owned wallet?
This is not just with stakes, but also with currency:
```
EUR:
 Available: 6.61000000
 Balance: 6.61000000
 Pending: 0.00000000
 Bot Owned: 0.85106790
 Est. EUR: 0.851
```

**Comment by stash86** [comment]
if you are using `tradable_balance_ratio` in your config, then the bot will take into account any change in your `stake_currency` balance. It won't take into account any changes to any other coins, even if you have an open trade.

**Comment by xmatthias** [comment]
You should also note that without trade activity (no orders opening, ...) - the balance will cache for about an hour until it updates - so don't expect "up to the minute" updates when no trades happen.
