### ISSUE TITLE
Exit Reason: trailing_stop_loss

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#10769]
## Describe your environment

* Operating system: Ubuntu 22.04
* Python Version: 3.10.12
* CCXT version: 4.3.88
* Freqtrade Version: 2024.8
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**My strategy file is set up like this:**

```
    # Trailing stop:
    trailing_stop = False
    trailing_stop_positive = 0.25
    trailing_stop_positive_offset = 0.40
    trailing_only_offset_is_reached = False

    process_only_new_candles = False

    exit_profit_only = False
    ignore_roi_if_entry_signal = False
```

**Therefore, `trailing_stop` should not be used, but when my robot is running, it will prompt the exit of `trailing_stop_loss`. Is it because my policy is not set?**

```
❌ Binance (dry): Exited SUPER/USDT:USDT (#21)
Profit: -9.84% (loss: -219.524 USDT / -219.743 USD)
Exit Reason: trailing_stop_loss
Direction: Short
Amount: 2205
Open Rate: 1.012 USDT
Exit Rate: 1.11 USDT
Duration: 4 days, 10:48:17 (6408.3 min)


Protection triggered due to Cooldown period for for 6 candles.. SUPER/USDT:USDT will be locked until 2024-10-08 08:00:00.


❌ Binance (dry): Exiting SUPER/USDT:USDT (#21)
Unrealized Profit: -9.77% (loss: -217.979 USDT / -218.197 USD)
Exit Reason: trailing_stop_loss
Direction: Short
Amount: 2205
Open Rate: 1.012 USDT
Current Rate: 1.11 USDT
Exit Rate: 1.11 USDT
Duration: 4 days, 10:48:17 (6408.3 min)
```

**Thanks.**

**Comment by stash86** [comment]
Are you using custom_stoploss?

**Comment by WinPoss** [comment]
**I have set:**

`use_custom_stoploss = True`

**But I didn't use the following function:**

```
def custom_stoploss(self, pair: str, trade: Trade, current_time: datetime,
                        current_rate: float, current_profit: float, after_fill: bool, 
                        **kwargs) -> Optional[float]:
    ......
```

Do I need to set `use_custom_stoploss = True` to `False`?

**Comment by xmatthias** [comment]
the default for `custom_stoploss` (if not implemented in your strategy) is `self.stoploss` - which will correspond to a regular trailing stoploss (without conditions).

So the behavior is correct - but your configuration doesn't really make sense - enabling `use_custom_stoploss` explicitly tells the bot "call `custom_stoploss()`". 
i can see no sane reason to set it to true (make the bot run slightly slower) without actually requiring the functionality that this callback provides.

**Comment by WinPoss** [comment]
> the default for `custom_stoploss` (if not implemented in your strategy) is `self.stoploss` - which will correspond to a regular trailing stoploss (without conditions).
> 
> So the behavior is correct - but your configuration doesn't really make sense - enabling `use_custom_stoploss` explicitly tells the bot "call `custom_stoploss()`". i can see no sane reason to set it to true (make the bot run slightly slower) without actually requiring the functionality that this callback provides.


Ok, thanks for the reply, I've commented out `use_custom_stoploss`.
