### ISSUE TITLE
Problem with docker desktop

### ISSUE THREAD

**Issue by Petikesz** [freqtrade/freqtrade#10786]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

My config file created but dockdesktop csnt find it and i cant rum freqtrade locally because of this. Why is that?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Aside from that - please put the question context **in the body**. I was pretty close to closing this as "has no content" until i realized that the question is in the header.

---

With the  context provided (there is none), the only even remotely reasonable answer is "you put it in the wrong place".

There's no "one answer fits all" answer - as it'll depend on configurations within docker as to where the actual place for it is.

if you follow the [docker quickstart](https://www.freqtrade.io/en/stable/docker_quickstart/#docker-quick-start) (at least the steps about `create-userdir` and `new-config`) - you'll see where the config will be placed.
if docker then "finds" it or not will also depend on the commands you issue - so without further context - there's nothing more to add.
