### ISSUE TITLE
How do I get my strategy to place sell trades with trading_mode spot?

### ISSUE THREAD

**Issue by WinstonN** [freqtrade/freqtrade#10788]
## Describe your environment

  * Operating system: Docker (Mac OS 15.0.1)
  * Python Version: Python 3.12.5 (`python -V`)
  * CCXT version: ccxt==4.3.88 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2024.8 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I am building a strategy based off the sample strategy. I see within the `populate_entry_trend` method
"enter_long" & "enter_short"

I am using Binance and Binance allows me to "buy" and "sell" on the spot market

![image](https://github.com/user-attachments/assets/9d61a1ac-b199-49bc-a5fc-b4d9bc4a7bd0)

My strategy places "buy" trades just fine, but it does not place "sell" trades. 
I do not want to use futures and short trades, I simply want to place sell trades. My trading mode in the config is `"trading_mode": "spot",`

In the strategy Bandtastic I see `populate_buy_trend` and `populate_sell_trend` methods. Is this the way to do it?

**Comment by WinstonN** [comment]
I'm closing this question because I want to do more research, especially on this document https://www.freqtrade.io/en/stable/strategy_migration/

**Comment by xmatthias** [comment]
What you're missing is not a freqtrade topic - but something binance tries to hide from you if you don't look carefully.

When you buy on binance (without leverage) - you're trading in spot markets.

When you're selling (going short) (or buying with leverage) - you're technically in margin markets - which is a different market type - and has quite different rules, too (you buy for the time you're short, as you need to lend the money from someone, ...). 

Freqtrade only supports spot and futures, but currently no margin markets.

**Comment by stash86** [comment]
To make sure you don't fall into the margin trap, please only use enter_long and exit_long. Never set can_short to True

**Comment by WinstonN** [comment]
Thank you for helping me understand the concepts better <3
