### ISSUE TITLE
Telegram notifications can contain HTML code

### ISSUE THREAD

**Issue by tobyhage** [freqtrade/freqtrade#10787]
Hello,

I have made a signal bot with Freqtrade and it is working :-)
But I want to add this HTML: `<a href='altrady://xxx.example.com/d/BYBI_BTC/USDT'>Open in Altrady<a/>` to the telegram notifications.

If I tested everything correct this is currently not supported. 

There is this error when i add this html: Telegram NetworkError: Can't parse entities: can't find end of the entity starting at byte offset 120

And if I understood correct send_msg function has already parameter parse_mode='HTML'
Is it possible to extend the self.dp.send_msg command with the possibility to add messages with HTML?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

I've removed the "hidden advertisement" from your post. 
we will not allow links to commercial offerings in issues (or on the discord server, for that matter). 

Freqtrade is not a signal bot - it's not designed this way, and i'm not sure it's going to work well for that usecase, either - so this is not a usecase we aim to support.

Aside from this - freqtrade is a free, open source project supported by volunteers in their free time.
Our target audience are individuals with an interest to trading - but not people trying to build a business out of it (usually with the aim to rip users off, as is all to common in the crypto space).

Hence please understand that we have no interest in supporting  business requirements for you in providing links to your service.

Thanks for your understanding.

**Comment by tobyhage** [comment]
Sorry for breaking the rules. However, I would like to provide some clarification.

I deliberately removed your template because I wanted to keep the issue as explicit and concise as possible to help reduce your workload.

Furthermore, I had no intention of advertising. Here, too, I wanted to explicitly clarify what I was trying to do. I am just a regular user and have no affiliation with that company, so there will be no business proposals coming from me.

It's unfortunate that this functionality is not planned. It seemed like a nice feature and probably not too difficult to implement, but I can't assess that.

**Comment by xmatthias** [comment]
A signal bot would require a rather different structure than an actual trading bot - so that's clearly not planned.

We've also experimented with links to the exchange page in the past - but found it difficult to provide deep links into exchanges reliably (pair naming, link structure, ...) - as we expect it to work cross-exchange - and would clearly not link to some odd 3rd party service.


As for adding links to telegram - telegram supports 2 modes of sending messages - html and markdown - freqtrade uses both, depending on the "usecase".

Assuming you send your notifications as [strategy notifications](https://www.freqtrade.io/en/stable/strategy-customization/#send-notification) - you'll need markdown syntax - and i don't think telegram supports direct links there (though something around `[link](http://whatever/)` might work.

**Comment by tobyhage** [comment]
I know freqtrade is not meant for a signal bot. But i like the tool very much and the way i programmed the strategy now it is working quit nice :-)

When i send the link as normal text in the telegram message as strategy notification it is already working, because telegram detect that there is a link in the text. So with https://xxx.xxx it is working.

But i was try to change the protocol to the application specific protocol and then the link is not detected anymore by telegram.
I have not tried markdown syntax yet, so i will try this. I will let you know if this works.

Thank you for your help.

**Comment by tobyhage** [comment]
Markdown links are working with https, but with the application specific protocol it is not working.
Again thank you for your help.
