### ISSUE TITLE
LLM's, Freqtrade with Large Language Models

### ISSUE THREAD

**Issue by Immortality-IMT** [freqtrade/freqtrade#10798]
* Operating system: Linux
  * Python Version: Python 3.10.12
  * CCXT version: ccxt==4.4.14
  * Freqtrade Version: freqtrade 2024.9

Large language models, send the dataframe to the LLM using an API key perhaps and get a trade decision, pass, buy, sell reply.
Use freqtrade with various LLM's

Worth it?

**Comment by xmatthias** [comment]
Well essentially, it's up to you to implement this in a strategy.

I don't see this as anything freqtrade would (or should) provide out of the box - but a strategy can implement this for sure.
It's then up to the user how exactly to implement this.

We're also happy to accept strategy contributions to the [strategy repo](https://github.com/freqtrade/freqtrade-strategies/) if you think it's something worth sharing (make sure to not share your actual API token!).
Probably also some note on the (token) cost might be needed in this case ... but that's just some side-comment.


---

Now if it's worth it (financially) - i have my doubts (if you consider what an LLM is, essentially).
I've also seen freqAI implementations which do try to use it, but from what I've heard, they were little better than a random generator - but your experience may obviously vary (other models, other questions, other markets, ...)

Also from a profit calculation perspective, you'll need to subtract the overall token cost - so even a bot that has a slight edge will first have to pay for itself to be "actually worth it".

**Comment by froggleston** [comment]
LLMs are language models, not machine learning tools that understand trading decisions. They generate text, and don't understand the context of financial markets. You would be better off using a different ML technique, as is available in FreqAI, as xmatthias says.
