### ISSUE TITLE
Downloading trades is always 0%.

### ISSUE THREAD

**Issue by beiluo97** [freqtrade/freqtrade#10800]
## Describe your environment

  * Operating system:  Mac OS
  * Python Version: Python 3.9.6 (`python -V`)
  * CCXT version: Nothing (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2024.9 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

As I have use 
' docker-compose run --rm freqtrade download-data --timeframes 1h --exchange binance --pairs BTC/USDT:USDT'
Everything looks like ok, but with only problem that it is always 0%.
<img width="1001" alt="Screenshot 2024-10-15 at 23 27 29" src="https://github.com/user-attachments/assets/68641e4d-1d02-4dc3-912b-a2a0f727b3a0">

So I try to use a proxy with docker compose, write the docker-compose.yml with 
```
    environment:
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890
      - NO_PROXY=localhost,127.0.0.1
```
Well this is also not working. And 
` curl -x http://127.0.0.1:7890 -L http://google.com`
is ok.
And I notice it show a website when timeout, as
"https://fapi.binance.com/fapi/v1/aggTrades?symbol=BTCUSDT&limit=1000&fromId=2264573484", this I can visit on Chrome.

So, does there any method I can download with proxy? Or freqtrade support direclty download backtest data manually? Or might be I need to find a server which can directly acess 'google.com'?

**Comment by froggleston** [comment]
Do you have `"use_public_trades": true` set in your exchange configuration? If so, you're downloading trade data, not candle data. Trade data downloads are *much* slower than normal candle downloads.

**Comment by xmatthias** [comment]
The progress-bar moves in steps between pair/timeframe combinations - so if you have 10 pairs and 1 timeframe - you'll get 10 steps in the progress bar.

Now you're downloading one pair - and trades-data at that (which is a TON slower as it's a lot bigger) - and that for the biggest pair volume-wise. 
Just wait it out - the logs (next time please as text, not as screenshots) does show that it did download 60k trades (trades, not candles!). from the default timerange of 30 days, that's probably about a day or 2.

on logs of the the 2nd try, you can see that it found the 60k trades, and what date that data ends - which is about a month away - so just wait about 40x as long - and download-trades would finish (better read on - as there's a much faster alternative that almost certainly fits your need).


Your configuration also contains `download_trades` (equivalent to passing `--dl-trades` via command line) - which is used to download trades - which is usually not necessary unless you're either on kraken (you're not) - or if you intend to use the orderflow feature - which i doubt you are attempting to use.

removing that key (or setting it to false) will download ohlcv data - which you'll notice will be MUCH faster.

**Comment by beiluo97** [comment]
> The progress-bar moves in steps between pair/timeframe combinations - so if you have 10 pairs and 1 timeframe - you'll get 10 steps in the progress bar.
> 
> Now you're downloading one pair - and trades-data at that (which is a TON slower as it's a lot bigger) - and that for the biggest pair volume-wise. Just wait it out - the logs (next time please as text, not as screenshots) does show that it did download 60k trades (trades, not candles!). from the default timerange of 30 days, that's probably about a day or 2.
> 
> Your configuration also contains `download_trades` (equivalent to passing `--dl-trades` via command line) - which is used to download trades - which is usually not necessary unless you're either on kraken (you're not) - or if you intend to use the orderflow feature - which i doubt you are attempting to use.
> 
> removing that key (or setting it to false) will download ohlcv data - which you'll notice will be MUCH faster.

Yes that's what you said! When I comment the config line  
    // "download_trades": true,
everything is ok.
Thank you and [froggleston](https://github.com/froggleston). Have a nice day!
