### ISSUE TITLE
How to  local freqtrade not use proxy? 

### ISSUE THREAD

**Issue by beiluo97** [freqtrade/freqtrade#10804]
## Describe your environment

  * Operating system: MacOS
  * Python Version: Python 3.10.15 (`python -V`)
  * CCXT version: ccxt==4.4.14 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2024.10-dev-d503724bd and freqtrade 2024.9 
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hello, here I meet a strange problem is that, when I use 
`docker compose run --rm  freqtrade backtesting --timeframe 1m --strategy Heracles`, it tells  me 
<img width="822" alt="Screenshot 2024-10-17 at 00 55 55" src="https://github.com/user-attachments/assets/c450573b-0a0f-475d-9bba-3cc13eecc622">
And I think ok, I will try local freqtrade rather than docker, and `pip install ta` with 
` freqtrade backtesting --timeframe 1m --strategy Heracles`, but it told me 
<img width="1010" alt="Screenshot 2024-10-17 at 00 58 02" src="https://github.com/user-attachments/assets/cc211ce3-c27c-4c24-bc32-33fde95b603f">Actually,  I can  `curl -X GET "https://api.binance.com/api/v3/exchangeInfo"` to visit get the info.

**Comment by xzmeng** [comment]
> To use a proxy for exchange connections - you will have to define the proxies as part of the ccxt configuration.
> 
> ```
> { 
>   "exchange": {
>     "ccxt_config": {
>       "httpsProxy": "http://addr:port",
>       "wsProxy": "http://addr:port",
>     }
>   }
> }
> ```
> For more information on available proxy types, please consult the [ccxt proxy documentation](https://docs.ccxt.com/#/README?id=proxy).


https://www.freqtrade.io/en/2024.8/configuration/#proxy-exchange-requests

**Comment by beiluo97** [comment]
> > To use a proxy for exchange connections - you will have to define the proxies as part of the ccxt configuration.
> > ```
> > { 
> >   "exchange": {
> >     "ccxt_config": {
> >       "httpsProxy": "http://addr:port",
> >       "wsProxy": "http://addr:port",
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For more information on available proxy types, please consult the [ccxt proxy documentation](https://docs.ccxt.com/#/README?id=proxy).
> 
> https://www.freqtrade.io/en/2024.8/configuration/#proxy-exchange-requests

When I add this part into config.json, everything is ok. Deeply thanks you so much, have a nice day!
