### ISSUE TITLE
Extract trades data and indicators in one csv

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#10802]
## Describe your environment

  * Operating system: Linux mint Una
  * Python Version: 3.10.4
  * CCXT version: 4.35
  * Freqtrade Version: 2024.09
  
## Your question

*Ask the question you have not been able to find
I am looking for a way to have OHCLV data plus indicators for the corresponding trades executed and recorded on the database. What I have used in documentation is back test analysis after exporting signals, but the trades can only be found on the bactest results Jason file. Any workaround to have indicators matching the trades executed into one csv file?

**Comment by froggleston** [comment]
Yes, use the `backtesting-analysis` command: https://www.freqtrade.io/en/stable/advanced-backtesting/

**Comment by xmatthias** [comment]
i don't think backtesting-analysis will provide the full data - just the candles where activity happened.

That said - i don't think that's data suitable for a csv file.
Freqtrade offers [several](https://www.freqtrade.io/en/stable/data-analysis/) [different](https://www.freqtrade.io/en/stable/strategy_analysis_example/) [ways](https://www.freqtrade.io/en/stable/advanced-backtesting/) to analyze backtest data, and [frequi in backtest mode](https://www.freqtrade.io/en/stable/freq-ui/#backtesting) to visualize backtest data.

CSV is not a suitable format for this.
