### ISSUE TITLE
Adding futures trading for LBank exchange 

### ISSUE THREAD

**Issue by abmahmoodi** [freqtrade/freqtrade#10809]
## Describe your environment
(if applicable)

  * Operating system: Ubuntu 22.04
  * Python Version: 3.10
  * CCXT version: 4.4.20
  * Freqtrade Version: 2024.9

## Describe the enhancement

In futures trading we have the following error:
freqtrade - ERROR - Freqtrade does not support cross futures on LBank

*Explain the enhancement you would like*

**Comment by stash86** [comment]
As said in the previous issue of yours, you will need to do the works yourself.

First of all, make sure all the basic functions works

https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip

**Comment by abmahmoodi** [comment]
Unfortunately LBank does not support API trading in futures.
