### ISSUE TITLE
Can not see earlier K chart info on freqUI

### ISSUE THREAD

**Issue by liyunlongaaa** [freqtrade/freqtrade#10811]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
![image](https://github.com/user-attachments/assets/4e9fce52-c770-4748-b283-5a1985eb8f2f)

Hi everyone, I can't see earlier K chart info on freqUI, for example if today is October 19th, I can only see info from October 15th at the furthest. This is because I want to compare earlier live trades to see how signals were triggered or not triggered. Because there are no entry and exit signals on the k-chart seen elsewhere, backtesting can sometimes produce different results than live trading. So I want to see the signals triggered when I actually trade.
Thanks everyone !

**Comment by xmatthias** [comment]
FreqUI shows the same data the strategy has access to (it uses the same dataframe).
In a dry/live bot, you'll hence not get more data than what the strategy gets - which by default for most exchanges - is between 500 and 1000 candles (depending on the exchange).

To some degree, you can influence this by setting `startup_candle_count` to a higher value (up to 5x what your exchange provides) - but this will have an impact on your running bot - and can potentially slow your bot down.

If you set the value too high, freqtrade will fail to start.
