### ISSUE TITLE
Ta-Lib installation failed

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#10812]
## Describe your environment

  * Operating system:WIN 11 / WSL
  * Python Version: Python 3.10.15

![obraz](https://github.com/user-attachments/assets/9fa22720-cea2-4e85-8276-38ec39163aef)

**Comment by stash86** [comment]
Please use the available setup.sh script to install/update FT

**Comment by xmatthias** [comment]
We have a whole section about installing ta-lib in the [documentation](https://www.freqtrade.io/en/stable/installation/#install-ta-lib) - neither of which says a plain `pip install ta-lib` is supposed to work.
However, we do strongly recommend the `setup.sh` script for sure - as that handles these things for you.
