### ISSUE TITLE
How to backtest a trained AI model without retraining ?

### ISSUE THREAD

**Issue by ducky-duke** [freqtrade/freqtrade#10826]
## Describe your environment

  * Operating system: 24.04
  * Python Version: 3.12
  * CCXT version: 4.4.20
  * Freqtrade Version: 2024.9
  
## Your question
Step 1: train a model using backtesting on timerange A. -> get saved model (AA)
Step 2: I want to test model (AA) on timerange B without retrain.

I can't find any instruction in docs, please give me some suggestion.

**Comment by robcaulk** [comment]
Hello, it is not supported. FreqAI is a tool for adaptive modeling - so it helps you build a model that adapts automatically.

If you want to do something manual, you do not have any need for FreqAI, you can simply load your own custom model into `populate_indicators()` and run your inference. No need for FreqAI in this case.
