### ISSUE TITLE
How to hyperopt the parameters without the space definition?

### ISSUE THREAD

**Issue by KaiZheng2020** [freqtrade/freqtrade#10830]
There is no space definition in the following parameters from [hyperopt documentation page](https://www.freqtrade.io/en/stable/hyperopt/) Optimizing an indicator parameter:

```
    buy_ema_short = IntParameter(3, 50, default=5)
    buy_ema_long = IntParameter(15, 200, default=50)
```

also there is no clear way how to hyperopt them without the space definition.

**Comment by stash86** [comment]
If you read further down, there is an info box containing this

```
Parameters must either be assigned to a variable named buy_* or sell_* - or contain space='buy' | space='sell' to be assigned to a space correctly. If no parameter is available for a space, you'll receive the error that no space was found when running hyperopt.
Parameters with unclear space (e.g. adx_period = IntParameter(4, 24, default=14) - no explicit nor implicit space) will not be detected and will therefore be ignored.
```

For the 2 variables above, they are assigned to `buy` space

**Comment by KaiZheng2020** [comment]
Got it, I will try to use `buy` space. 

Thanks.
