### ISSUE TITLE
Typo in Adjust Entry Price docs

### ISSUE THREAD

**Issue by AchmadFathoni** [freqtrade/freqtrade#10838]
## Describe the problem:
If it for the first 10 minutes, should it be 
```
            and (current_time - timedelta(minutes=10))  < trade.open_date_utc
```
 https://github.com/freqtrade/freqtrade/blob/b8f8d1d4b1d7a2dc28b1c52187a3bb3e97350ae5/docs/strategy-callbacks.md?plain=1#L973-L978

**Comment by xmatthias** [comment]
Nice spot - should be fixed / adjusted in the latest docs (it should actually be <= ... though that'll only matter for a second 😆 )
