### ISSUE TITLE
FreqAiModel Error

### ISSUE THREAD

**Issue by danxathome** [freqtrade/freqtrade#10841]
Hello Guys,

I need help with freqai.

I try freqai for the first time and it didnt work.
Everytime I tried to train the model it says that the class doesnt ecist or contsins python code error.

Here is my model.
``` python

import numpy as np
import lightgbm as lgb
import pandas as pd

class LightGBT:
    def __init__(self):
        self.model = None

    def train(self, data):
        # Features und Zielvariable definieren
        data['target'] = np.where(data['Close'].shift(-1) > data['Close'], 1, 0)
        features = ['return', 'ma_5', 'ma_10', 'volatility', 'Volume']
        X_train = data[features]
        y_train = data['target']

        # Training durchführen
        train_data = lgb.Dataset(X_train, label=y_train)
        params = {
            'objective': 'binary',
            'boosting_type': 'gbdt',
            'metric': 'binary_error',
            'learning_rate': 0.05,
            'num_leaves': 31,
            'max_depth': -1,
            'feature_fraction': 0.9
        }
        self.model = lgb.train(params, train_data, num_boost_round=100)

    def predict(self, X):
        if self.model:
            return self.model.predict(X)
        else:
            raise ValueError("Model not trained. Please train the model before predicting.")

```
Can anyone tell me if code has a error?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.


---

You'll also want to provide us with the exact command you're running - and the error you're getting.

Ad hock, i'd say that this is "nothing" to do with freqtrade / freqai  - it's neither inheriting from `IStrategy` (for a strategy), nor from any `IFreqaiModel` or any other existing Model.
As such, freqtrade is right - this is no model, and hence not a class it's supposed to load (freqtrade will NOT load every class - only subclasses from the defined interface classes).


Please refer to the [documentation](https://www.freqtrade.io/en/stable/freqai/) on how to **properly** define a model.
