### ISSUE TITLE
download-data downloads trades past --timerange end time

### ISSUE THREAD

**Issue by biiiipy** [freqtrade/freqtrade#10840]
## Describe your environment

  * Operating system: freqtradeorg/freqtrade:2024.9_freqairl docker image on windows
  * Python Version: 3.12.6 (`python -V`)
  * CCXT version: 4.4.6 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.9 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Describe the problem:

`--dl-trades` also downloads some trades after defined --timerange end period.

### Steps to reproduce:

using default configuration, download trades for october 2019
```
freqtrade download-data --data-format-trades parquet --exchange binance --trading-mode futures --pairs BTC/USDT:USDT --timerange 20191001-20191101 --timeframes 1d --dl-trades
```

### Observed Results:
So timerange is 20191001-20191101

It downloaded 3390607 trades in a file `BTC_USDT_USDT-trades.parquet`

Last trade has timestamp `1572566905343`, which is `Nov 01 2019 00:08:25 GMT+0000` - **8:25 minutes into next month and outside defined range**. 

![Image](https://github.com/user-attachments/assets/8f7f77e0-5183-4a21-994b-dcd974a12358)

And if we download trades for november 2019
```
freqtrade download-data --data-format-trades parquet --exchange binance --trading-mode futures --pairs BTC/USDT:USDT --timerange 20191101-20191201 --timeframes 1d --dl-trades
```

we can find the trade mentioned before
![Image](https://github.com/user-attachments/assets/683aecfd-11fa-4c16-9b3a-64339527b145)

**Comment by xmatthias** [comment]
downloading data happens in steps - based on what the exchange gives us - usually something between 500 and 1000 trades / candles.

We don't truncate at the end-date - and that's also pointless, really - as you'd be dropping perfectly fine data.
end-date is only respected to allow for improved "stepped downloading" - but on data-downloads, it's not designed to cut off at the second you specify.
It'll also ignore stat/end-dates depending on the situation (check the docs for which scenarios exactly).

As such - i'd say it's working as expected / designed.
