### ISSUE TITLE
BNB sell on binance

### ISSUE THREAD

**Issue by vpotap** [freqtrade/freqtrade#1084]
ft from last source is running with smooth scalp strategy from repo after buy BNB/ETH , cant sell
- freqtrade.freqtradebot - WARNING - Unable to sell trade: Insufficient funds to create limit sell order on market BNB/ETH.Tried to sell amount 2.36 at rate 0.03026 (total 0.0714136).Message: binance {"code":-2010,"msg":"Account has insufficient balance for requested action."}, 
Telegram balance show Amount: 2.36.
in Binance account show only 2.33 !

If I use /forcesell id get the exception .env/lib/python3.6/site-packages/ccxt/binance.py", line 894, in handle_errors
    raise InsufficientFunds(self.id + ' ' + body)
ccxt.base.errors.InsufficientFunds: binance {"code":-2010,"msg":"Account has insufficient balance for requested action."}

are there some limits of min trading stake amount ? May be this is depends on that 'BNB is for tax' ?

**Comment by vpotap** [comment]
some research https://twitter.com/binance/status/950672981579128832

**Comment by xmatthias** [comment]
Yes you are absolutely right, this is something we need to add to the documentation.

As binance is using BNB if available, it will draw from your open trade (if you didn't have any before), so i would reccomend to add it to the blacklisted pairs list.

will see to get some documentation on that in. Thanks for pointing it out

**Comment by xmatthias** [comment]
since we merged #1110, which added a note to have users exclude BNB from their trading on Binance, i think we should close this issue, as there is no other way around it.

there is however still #1086 around the fee issue - so the topic is not completely closed yet.
