### ISSUE TITLE
Reset old trade

### ISSUE THREAD

**Issue by vpotap** [freqtrade/freqtrade#1085]
Is it possible reset one ft trade ?  After some manual pair trading ft continue to sell old balance for this pair

**Comment by xmatthias** [comment]
we have a sql cheatsheet [here](https://github.com/freqtrade/freqtrade/blob/develop/docs/sql_cheatsheet.md).

closing a trade manually should work via, but please check the full documentation to find the correct trade-id.
```
UPDATE trades
SET is_open=0, close_date=<close_date>, close_rate=<close_rate>, close_profit=close_rate/open_rate-1  
WHERE id=<trade_ID_to_update>;
```
