### ISSUE TITLE
Integrate Alpaca exchange to do spot trading with freqtrade.

### ISSUE THREAD

**Issue by Immortality-IMT** [freqtrade/freqtrade#10862]
Here is the list of prior threads on the subject, and it appears to be implementable at least as a side to do some spot paper trading with alpaca using freqtrade strategies. Has anyone achieved this, can we get an unsupported hack to do this.

Integrate Alpaca exchange to do spot trading with freqtrade.

Threads:

- https://github.com/freqtrade/freqtrade/issues/10404
- https://github.com/freqtrade/freqtrade/issues/7953
- https://github.com/freqtrade/freqtrade/issues/7952

1. CCXT Alpaca already has fetch_ohlcv implemented. 
2. alisalama states he has implemented:  fetchTicker + fetchTickers and includes bid/ask/last.

He looks like he has forked and implemented the support.

**Comment by xmatthias** [comment]
`freqtrade list-exchanges --all` will show you what's missing. 


```
│ Alpaca                 │ alpaca                          │ spot                   │ missing: fetchL2OrderBook. missing opt:               │
│                        │                                 │                        │ fetchMyTrades, fetchL2OrderBook, fetchTicker,         │
│                        │                                 │                        │ fetchTickers. 
```

Optional things are not necessarily required (but will limit certain functionalities) - but either `fetchL2OrderBook` or `fetchTicker` are a must (that's what seems to be missing).

Best work with ccxt to get the necessary things implemented if you intend to spend time on this.
For freqtrade, it's not of interest until the things **we know** upfront are required are implemented - then we can look at what's missing that's not that obvious.

**Comment by Immortality-IMT** [comment]
I have raised the issue with ccxt fyi thread here: https://github.com/ccxt/ccxt/issues/24127
I have raised the issue with Alpaca thread here: https://github.com/alpacahq/alpaca-py/issues/521
