### ISSUE TITLE
Docker history not kept

### ISSUE THREAD

**Issue by alfirin** [freqtrade/freqtrade#10867]
## Describe your environment

  * Operating system:  Ubuntu 24.04.1 LTS with Docker 
  * Docker version 27.3.1, build ce12230
  * Python Version: the one from Docker version (freqtrade: 2024.9)
  * CCXT version: the one from Docker version (freqtrade: 2024.9)
  * Freqtrade: 2024.9
  
## Describe the problem:

I have one freqtrade bot that is running with docker compose.
There is one database sqlite file that I used with `--db-url` option.

Here is the command to run the bot:
```
trade
      --db-url sqlite:////freqtrade/user_data/freqtrade.live.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SomeStrategy.py

```

When I restart the bot (via the docker compose restart command) all the trades are not shown and the trades are also not shown.
It's like the history is not saved or used.

It's the same with the profit and all data (trades in progress, ...).

### Steps to reproduce:

  1. Start the bot: docker compose up -d
  2. Do some trades (during a few days)
  3. See the history in the freqUI
  4. Restart the bot
  5. Don't see the history or trades in progress

### Observed Results:

  * What did you expect to happen: When I restart the Docker container I expect it to have all the historical data.
Maybe I am doing something wrong?

Thanks a lot for your help !

**Comment by stash86** [comment]
Copy the complete docker-compose.yml here

**Comment by Danson77** [comment]
I think you just have to wait some time for database to load, I have seen same thing when resetting bots, some time later it loaded but other times I had messed up config or strategy so bot couldn't start up, check your log files or in this case printed commands out in docker terminal

**Comment by alfirin** [comment]
Yes I tried it a few times also.
It didn't worked (even for a few days).

For example here is what it's shown (even if some trades were made):
![Image](https://github.com/user-attachments/assets/a6dc1ef3-5019-49cd-826d-512be2f728e3)

**Comment by alfirin** [comment]
@stash86 thanks for your reply, here is the docker compose file:
```
---
services:
  freqtrade-prod:
    image: freqtradeorg/freqtrade:2024.9
    restart: unless-stopped
    container_name: freqtrade-prod
    volumes:
      - "./user_data_test:/freqtrade/user_data"
      - "./prod_config.json:/freqtrade/prod_config.json"
    ports:
      - "127.0.0.1:4596:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/freqtrade.live.sqlite
      --config /freqtrade/user_data/config-prod.json
      --config /freqtrade/prod_config.json
      --strategy XXX
```

**Comment by xmatthias** [comment]
well based on your config - you should see a file `freqtrade.live.sqlite` appear in `user_data_test`.
Is that the case when you start the container

also, what do startup logs show? (the logs leading up to the first "bot heartbeat" ?
