### ISSUE TITLE
freqtrade webserver param support feature needed.

### ISSUE THREAD

**Issue by leochan007** [freqtrade/freqtrade#10865]
freqtrade webserver backtesting mode should support "|--data-format-ohlcv=json" param.
'coz the data is downloaded in this specified data format.

**Comment by stash86** [comment]
Why not specify it in the config file?

**Comment by froggleston** [comment]
By default, data isn't downloaded as JSON, it's now feather. As stash says, it's configurable through the configuration file.

**Comment by xmatthias** [comment]
you can't use webserver mode without a config anyway (there'd be no api configuration). 
Hence - best add this setting to your configuration (it's called `"dataformat_ohlcv"`).

i'd also strongly advise against using json.
we've done [a few tests](https://www.freqtrade.io/en/stable/data-download/#dataformat-comparison) - and it's **clearly** the worst of all formats (biggest, slowest).

There's a conversion tool (same page, further down) you can use to get your existing data to a better format.
