### ISSUE TITLE
Fee Calculation

### ISSUE THREAD

**Issue by vpotap** [freqtrade/freqtrade#1086]
trying ft with smooth scalp strategy on binance , after altcoins pair buy the result amount for sell is smaller (should be calculated -fee) as the result ft cant' sell any altcoins with warning binance {"code":-2010,"msg":"Account has insufficient balance for requested action."} 
there are two issues:
1. bot use market order fee not limit order
2. bot don't recalculate real amount of altcoins for sell on balance but use the same as it was for buy

**Comment by xmatthias** [comment]
Can you please specify the branch and last commit, so we know which branch/version you're on, thanks.

you can get the last commit via `git log --format="%H" -n 1`

**Comment by xmatthias** [comment]
Is this maybe happening with a BNB pair on Binance, and therefore related to #1084 ?

**Comment by xmatthias** [comment]
technically, this part is supposed to handle your case.

did you see any message like 
`Applying fee on amount for XXX failed: myTrade-Dict empty found` ... ?

https://github.com/freqtrade/freqtrade/blob/cfcc2e61e5779dffb9f7d5d49dc1eaa43415cbda/freqtrade/freqtradebot.py#L462-L475

**Comment by creslinux** [comment]
there is general confusion around fees. 
limit orders and market orders do not have different fees when the limit order is a marketable limit order. 

for a limit order to have less fees it has to be "far from" market price.
The type of order does not determine the fee, the price it is submitted at and the current orderbook on the exchange does. 

An exchange will reward a user that adds liquidity to the book and charge a user that removes liquidity,

**Comment by creslinux** [comment]
see #1059

**Comment by xmatthias** [comment]
Agreed - so the initial insert to the trade table can be wrong in certain cases (mainly binance so far).

However, the "update" code i pointed to above should update both the `open_fee` and `amount` if necessary, unless it has a (still undetected??) flaw.

I'll try to have a look at it.

**Comment by xmatthias** [comment]
this should be fixed by #1211
