### ISSUE TITLE
Failed to reuse watch with stable Internet and datetime sync

### ISSUE THREAD

**Issue by danpeterson24** [freqtrade/freqtrade#10873]
- Operating System: Windows 10
- Python Version: 3.11.2
- CCXT Version: 4.4.24
- Freqtrade Version: 2024.1
- Environment: WSL - Debian

I am encountering persistent errors in my logs that appear frequently:

> 2024-11-02 23:00:01,559 - freqtrade.exchange.exchange - INFO - Failed to reuse watch WIF/USDT, 1m, False, 1730568600000, 1730568599733, 2024-11-02T17:30:00, 2024-11-02T17:29:59
> 2024-11-02 23:00:01,563 - freqtrade.exchange.exchange - INFO - Failed to reuse watch LTC/USDT, 15m, False, 1730568600000, 1730567765528, 2024-11-02T17:30:00, 2024-11-02T17:16:05
> 2024-11-02 23:00:01,565 - freqtrade.exchange.exchange - INFO - Failed to reuse watch BNB/USDT, 3m, False, 1730568600000, 1730568490818, 2024-11-02T17:30:00, 2024-11-02T17:28:10
> 2024-11-02 23:00:01,565 - freqtrade.exchange.exchange - INFO - Failed to reuse watch DOGE/USDT, 15m, False, 1730568600000, 1730567767704, 2024-11-02T17:30:00, 2024-11-02T17:16:07

These logs continue with dozens of similar entries.

It was suggested that these errors could stem from connection outages or time synchronization issues between WSL and Windows. However, my internet connection is stable, and I verified that the WSL Debian time is synchronized with Windows to the second, ruling out the known causes.

Could you provide guidance on resolving these issues? I am happy to supply any additional relevant details, as necessary.

**Comment by xmatthias** [comment]
To start with - these are not necessarily errors - but info messages. 
They're pointing out issues with the websocket connection - however freqtrade will fall back to regular rest connections - so the bot won't really notice a difference (other than a slight delay as it needs to fetch from rest instead of having data readily available).


> WSL Debian time is synchronized with Windows to the second

you'll want to ensure that it's synchronized to a proper, global clock. 
Windows clock  can be scewed / slightly wrong just as well - especially if it's a domain-joined system.


also, is this "actual" binance, or a binance derivate like binance.us?

**Comment by danpeterson24** [comment]
My exchange is the main Binance platform. I don't have a deep understanding of technical details, so I appreciate your patience and support.

So, I wouldn't have minded these, but the target, which I am monitoring on the FreqUI page becomes flatlined at certain time segments.

> ChatGPT: Data Handling and NaNs: If there’s missing data, Freqtrade typically tries to fill gaps from the REST API, but it can depend on your configuration settings. If the missing data isn’t fetched successfully, it may result in NaNs. This often happens if there’s an interruption in the WebSocket connection or if the REST data fails to backfill properly, leading to dropped predictions. When these gaps occur, Freqtrade’s logging shows lines like:

> 2024-11-03 02:04:16,396 - freqtrade.freqai.data_kitchen - INFO - dropped 1 of 1 prediction data points due to NaNs.

1.  Is the missing data fetched from the Rest API before resuming training or dropped with a lot of NaNs?  Once these info messages start, I get a lot of these dropped prediction data points (1 of 1) messages.

2. Is it recommended to deactivate the WebSocket and rely on Rest API to ensure streamlined uninterrupted availability of candle data?

3. "you'll want to ensure that it's synchronized to a proper, global clock.
Windows clock can be scewed / slightly wrong just as well - especially if it's a domain-joined system"

I'd be glad to do that. Is there a known way to sync Debian WSL to a non-native clock/time source?

**Comment by xmatthias** [comment]
I'll just ignore the completely wrong and missleading chatgpt response.

>  Once these info messages start, I get a lot of these dropped prediction data points (1 of 1) messages.

Well this essentially means that the rest api also didn't have the candle we're looking for.

> Is it recommended to deactivate the WebSocket and rely on Rest API to ensure streamlined uninterrupted availability of candle data?

well if you're encountering problems - you can surely deactivate it - though it most likely points to a different problem - especially if you're encountering "dropped 1 point" - as that means that the candle the rest API returned **also** wasn't completed yet - (most likely, a time offset problem).
Is this a live or dry-run bot? 

> I'd be glad to do that. Is there a known way to sync Debian WSL to a non-native clock/time source?

I wouldn't call it non-native - look for chronyd / ntp implementations - it's pretty standard for a linux system

**Comment by danpeterson24** [comment]
It is a dry-run bot.  You infer that this is a time offset problem.

I installed chronyd and ensured that it was running before starting the bot.  Did not get any "failed to reuse' messages. 

In the beginning, I was getting:

```
2024-11-03 07:49:05,265 - freqtrade.freqai.data_kitchen - INFO - dropped 318 of 999 prediction data points due to NaNs.
2024-11-03 07:49:05,747 - freqtrade.freqai.data_kitchen - INFO - dropped 318 of 999 prediction data points due to NaNs.
```

for most of my pairs, but after 1 minute, (timeframe is 1m) I was consistently receiving these:

```
2024-11-03 07:49:05,265 - freqtrade.freqai.data_kitchen - INFO - dropped 1 of 1 prediction data points due to NaNs.
2024-11-03 07:49:05,747 - freqtrade.freqai.data_kitchen - INFO - dropped 1 of 1 prediction data points due to NaNs.
2024-11-03 07:49:06,202 - freqtrade.freqai.data_kitchen - INFO - dropped 1 of 1 prediction data points due to NaNs.
2024-11-03 07:49:06,832 - freqtrade.freqai.data_kitchen - INFO - dropped 1 of 1 prediction data points due to NaNs.
2024-11-03 07:49:07,466 - freqtrade.freqai.data_kitchen - INFO - dropped 1 of 1 prediction data points due to NaNs.
2024-11-03 07:49:08,242 - freqtrade.freqai.data_kitchen - INFO - dropped 1 of 1 prediction data points due to NaNs.
2024-11-03 07:49:08,886 - freqtrade.freqai.data_kitchen - INFO - dropped 1 of 1 prediction data points due to NaNs.

```
Things to note:
1. In the beginning phase, the bot generates enough prediction data points and retains about 2/3 of them.
2. As time passes and new candles are generated, the number of prediction data points drops to 1, which is dropped anyways due to NaNs.

**Comment by danpeterson24** [comment]
I set my Debian timezone to UTC.

**Comment by xmatthias** [comment]
Well feel free to try without websocket ([`"enable_ws": false,`](https://www.freqtrade.io/en/stable/configuration/#consuming-exchange-websockets)) as you seem convinced that's the problem (i'm not and there's little info to suggest that were the case).

you should test websocket stability on a non-freqAI strategy, really.
Freqai MAY consume all resources if configured improperly - which can obviously also impact parallel websocket connections.
also, ` dropped 1 of 1 prediction data points due to NaNs` can also have other reasons - for example problems with the indicators you're calculating - and is not suitable to actually diagnose any websocket problems.

> I set my Debian timezone to UTC.

The timezone itself is irrelevant, really - but it's important that it's aligned (if you set it to UTC - then the time displayed must be UTC, too).
