### ISSUE TITLE
Whether backtest consider funding rate cost/return by exchanger?

### ISSUE THREAD

**Issue by liyunlongaaa** [freqtrade/freqtrade#10888]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hi, I want to research the funding rate effect by exchanger, but I don't know whether backtest consider funding rate cost/return by exchanger? Or where can I find some strategies for funding rate arbitrage for an example? Thank you!

**Comment by xmatthias** [comment]
Freqtrade does include funding rates when doing backtests as part of the calculations - assuming the data is available (some exchanges don't provide historic data beyond a few 100 datapoints) - and will fall back to 0 if it's not given.
