### ISSUE TITLE
running on docker, and in 2 days, the disk consumed 60GB

### ISSUE THREAD

**Issue by liva0126** [freqtrade/freqtrade#10889]
## Describe your environment

  * Operating system: __centOS7__
  * Python Version:  the one from Docker version (freqtrade: 2024.9)
  * CCXT version:  the one from Docker version (freqtrade: 2024.9)
  * Freqtrade Version: _ 2024.9__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I started the robot with the recommended docker-compose in the doc. At first everything going well, but then I found that the disk usage was increasing bit by bit.
My sys is centOS7，from 10GB to 60GB in two days. This resulted in me having to restart it every once in a while

**Comment by stash86** [comment]
It shouldn't be that way. Last time it happened to me, it was because there were issues on the bots and the logs basically grew too big. Before you restart, check the logs first.

Apart from such general advice, please give us the info asked in the template that you have delete entirely

**Comment by liva0126** [comment]
> It shouldn't be that way. Last time it happened to me, it was because there were issues on the bots and the logs basically grew too big. Before you restart, check the logs first.
> 
> Apart from such general advice, please give us the info asked in the template that you have delete entirely



Sorry, I have re-edited the version information in the template freqtrade 2024.9 (other versions are included in the docker container)
In addition, I found that this directory occupies a very large disk/var/lib/docker/overlay2/(this should be the docker container getting bigger and bigger)
Finally, I checked the log in/ft_userdata/user_data/logs/and it was a normal size with 3mb .

**Comment by liva0126** [comment]
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "0.0.0.0:3030:3030"
    # Default command used when running docker compose up
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy HarmonicDivergence

**Comment by xmatthias** [comment]
> /var/lib/docker/overlay2/

well this is where docker stores it's data - most prevalent - the image.
now freqtrade's default image is for sure not 60Gb big - but including all layers, a few Gb will be there for sure (our build-cache has around 9Gb in there - but that includes each version of the image at least once.

You can run `docker system df` to see what actually takes up this much memory from a docker perspective.
Ad hock - i'd say it's a misconfigured docker instance (check your `/etc/docker` directory for eventual configuration files) - or your strategy is dumping data to disk (to a location that's not mounted) or making use of `print()` heavily - both of which would cause your container to grow without showing up in the log.

Most likely amplified by having docker on an outdated system - not sure if it's possible to get a recent docker version for centos7, considering centos7 reached end of life 4 months ago, and didn't get active support in the last 4 years [source](https://endoflife.date/centos).

As it's not a new system (nobody would install centos7 nowadays) - you should very carefully evaluate how that server is configured - and definitely consider switching to an actively supported OS  _latest_ when you put your API keys onto that server - as nobody will care about existing vulnerabilities in an outdated system. (that's not related to freqtrade - but to

**Comment by liva0126** [comment]
Thank you very much for your patient answer. Do you have a recommended linux system?

**Comment by xmatthias** [comment]
well everything that's supported, really ? 

for a server, i'd go with debian/ubuntu - but linux systems is personal preference in almost all cases (or forced uppon you as you're in a corporation).

---

Having a different OS doesn't guarantee a fix - so i'd recommend to investigate the actual cause.
if it's the strategy causing this - it'll happen just the same on any other system.

That said - i'm running bots in docker - sometimes for months at a a time - and my disk never grew that big (my disk on servers usually is 50G in total ...).

**Comment by liva0126** [comment]
Understand, and I will further analyze the reasons for the problem. Thanks again!
