### ISSUE TITLE
Configuration error: Starting balance is smaller than stake_amount. Wallet is calculated as `dry_run_wallet * tradable_balance_ratio`.

### ISSUE THREAD

**Issue by wasertech** [freqtrade/freqtrade#10892]
Hey Team,

I hope your strategies are well optimized. On my end I've been having a lot of fun with _freqAI_, futures and feature exploration. Thank you so much for maintaining such an amazing project! ❤️

During my exploration, I've stumbled into a weird behavior.

Let's say you want to configure a strategy like so for instance; the strategy:
-  **must always keep 10%** of the balance as stake currency at all times.
- is only allowed to open  **3 simultaneous trades maximum**.
- can only open **a trade with a maximum of 10 000 units** of the stake currency.
- can only open **a trade with a minimum of 1 000 units** of the stake currency.

According to sections _[Amend Last Stake Amount](https://www.freqtrade.io/en/stable/configuration/#amend-last-stake-amount)_ and _[Static Stake Amount](https://www.freqtrade.io/en/stable/configuration/#static-stake-amount)_ of the [docs](https://www.freqtrade.io/en/stable/), the config should look like so for a 2'000 USDT dry run.

```json
{
    "tradable_balance_ratio": 0.9,
    "max_open_trades": 3,
    "stake_amount": 10000,
    "amend_last_stake_amount": true,
    "last_stake_amount_min_ratio": 0.1,
    "stake_currency": "USDT",
    "dry_run_wallet": 2000,
    "dry_run": true,
}
````
> [!NOTE] 
> This is only a partial configuration, checkout a complete example [here](https://gist.github.com/wasertech/6e7761039ff4ca65e93b6030c9463831).

Basically the goal here is replicate the exponential compounding effect of using  `"stake_amount": "unlimited"` but also to capture our understanding of the inertia of the stake's mass. Basically it boils down to:
> The larger the amount of currency to move, the more energy is required.

So we arbitrarily throttle the strategy to be able to absorb all those profits into diverse avenues while still been able to enjoy the ride of the exponential compounding curve at the beginning to rapidly grow to our desired throttle threshold.

Now when I try to backtest a strat. (i.e [BreakEven](https://github.com/freqtrade/freqtrade-strategies/blob/main/user_data/strategies/BreakEven.py)) w/ this config using the below command,

```shell
docker run --rm -it \
    -v /path/to/userdata:/path/to/mounded/volume \
    freqtradeorg/freqtrade:stable \
        backtesting \
        -c $config_filepath \
        --userdir "/path/to/mounded/volume"\
        --timerange 20200101- \
        --strategy-list BreakEven \
        --timeframe 5m

```
I get the this error:
```
2024-11-05 19:54:44,086 - freqtrade - INFO - freqtrade 2024.4-dev
2024-11-05 19:54:44,101 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/configs/smaOffset.usdt.binance.futures.backtest.json ...
2024-11-05 19:54:44,102 - freqtrade.loggers - INFO - Verbosity set to 0
2024-11-05 19:54:44,102 - freqtrade.configuration.configuration - INFO - Parameter -i/--timeframe detected ... Using timeframe: 1d ...
2024-11-05 19:54:44,102 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2024-11-05 19:54:44,102 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20200101- ...
2024-11-05 19:54:44,178 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2024-11-05 19:54:44,179 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2024-11-05 19:54:44,179 - freqtrade.configuration.configuration - INFO - Using strategy list of 1 strategies
2024-11-05 19:54:44,179 - freqtrade.configuration.configuration - INFO - Overriding timeframe with Command line argument
2024-11-05 19:54:44,179 - freqtrade.configuration.configuration - INFO - Parameter --cache=day detected ...
2024-11-05 19:54:44,179 - freqtrade.configuration.configuration - INFO - Filter trades by timerange: 20200101-
2024-11-05 19:54:44,180 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-11-05 19:54:44,190 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2024-11-05 19:54:44,190 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-11-05 19:54:44,190 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-11-05 19:54:44,193 - freqtrade - ERROR - Configuration error: Starting balance (1800 USDT) is smaller than stake_amount 10000 USDT. Wallet is calculated as `dry_run_wallet * tradable_balance_ratio`.
Please make sure to review the documentation at https://www.freqtrade.io/en/stable.
```

I saw [#3115](https://github.com/freqtrade/freqtrade/issues/3115) but OP ended up setting `dry_run_wallet` at the level of the stake amount and didn't explicitly used `amend_last_stake_amount`.

I will definitely start exploring the code base to see if I can make a PR about this issue.

Let me know your thoughts, your perspective is greatly appreciated. Maybe I am missing something so obvious I can't see it or maybe this ability is not currently supported by FT.

**Comment by stash86** [comment]
Set stake amount as unlimited in the config, and use custom_stake_amount function to check the max and min limit

**Comment by wasertech** [comment]
> Set stake amount as unlimited in the config, and use custom_stake_amount function to check the max and min limit

That's wonderful! Thank you @stash86.

Indeed the docs is [quite adamant about doing it this way](https://www.freqtrade.io/en/stable/configuration/#dynamic-stake-amount-with-position-adjustment). Closing this issue.

**Comment by xmatthias** [comment]
>     "stake_amount": 10000,
>     "dry_run_wallet": 2000,

Essentially - these 2 lines tell the bot "you got a 2000$ wallet, please enter a trade with 10.000$" ... to which the bot says "nah, not enough money" 😆

**Comment by wasertech** [comment]
```json
{
 "amend_last_stake_amount": true, 
 "last_stake_amount_min_ratio": 0.1
} 
```
@xmatthias yeah but I though those two lines would let it say:
> Ah yes I don't have enough to open a full trade but I can use a minimum of 10% of stake

Anyways I like the fact we keep stake_amount set to unlimited to refect we are still looking to compound. Syntax is syntax, as long as we can implement this behaviour. 🤷🏻‍♂️

**Comment by wasertech** [comment]
And for anyone else having trouble with this, here is how I ended up doing it.

I created [`strategies/custom_stake.py`](https://gist.github.com/wasertech/698ebcad65f3529982d596626a87c64e) to create an `IStrategy` subclass...
```python
# strategies/custom_stake.py
class CustomStake(IStrategy):
    
    def custom_stake_amount(self, pair: str, current_time: datetime, current_rate: float,
                            proposed_stake: float, min_stake: Optional[float], max_stake: float,
                            entry_tag: Optional[str], side: str, **kwargs) -> float:
        """       
        When you want to use position adjustment with unlimited stakes, you must also implement custom_stake_amount to a return a value depending on your strategy. Typical value would be in the range of 25% - 50% of the proposed stakes, but depends highly on your strategy and how much you wish to leave into the wallet as position adjustment buffer.
        For example if your position adjustment assumes it can do 2 additional buys with the same stake amounts then your buffer should be 66.6667% of the initially proposed unlimited stake amount.
        Or another example if your position adjustment assumes it can do 1 additional buy with 3x the original stake amount then custom_stake_amount should return 25% of proposed stake amount and leave 75% for possible later position adjustments.
        """
        
        # proposed_stake: currency_balance / (max_open_trades - current_open_trades)
        # https://www.freqtrade.io/en/stable/configuration/#dynamic-stake-amount

        if not min_stake:
            min_stake = self.get_min_stake(pair)
        
        if not max_stake:
            max_stake = self.get_max_stake(pair) 
                
        max_open_trades = self.get_max_open_trades()
        threshold = proposed_stake * 1-(1/max_open_trades)
        
        return max(min_stake, min(max_stake, threshold))
    
    def get_max_open_trades(self) -> int:
        return self.max_open_trades or 1
    
    def get_min_stake(self, pair: str) -> float:
        return 10.1
    
    def get_max_stake(self, pair: str) -> float:
        return 100.0


class Stake3x10Kx1K(CustomStake):
    
    def get_max_open_trades(self) -> int:
        return self.max_open_trades or 3
    
    def get_min_stake(self, pair: str) -> float:
        return 1_000.0
    
    def get_max_stake(self, pair: str) -> float:
        return 10_000.0
```
...to easily convert any strategy.
```python
# strategies/example.py
from custom_stake import CustomStake, Stake3x10Kx1K

class ThreeTradesFrom1KTo10K(Stake3x10Kx1K):
    """
    Your strategy goes here
    """

class FiveTradesFrom500To50K(CustomStake):
    """
    Your strategy goes here
    """
    def get_max_open_trades(self) -> int:
        return self.max_open_trades or 5
    
    def get_min_stake(self, pair: str) -> float:
        return 500.0
    
    def get_max_stake(self, pair: str) -> float:
        return 50_000.0
```

> [!NOTE]
> This strategy will keep enough reserve to open `max_open_trades` number of trades with an even amount. A better strategy is to fill up each trade to its maximum stake before opening a new one. This can be achieved by returning `max(min_stake, min(max_stake, max(threshold, min(proposed_stake, max_stake))))` instead in `custom_stake_amount`.
