### ISSUE TITLE
Swap Features in USDT-M

### ISSUE THREAD

**Issue by erhangunay** [freqtrade/freqtrade#10894]
## Describe your environment
(if applicable)

  * Operating system: Docker
  * Python Version: Docker 2024-10 (`python -V`)
  * CCXT version:Docker 2024-10 (`pip freeze | grep ccxt`)
  * Freqtrade Version: Docker 2024-10 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

Hi guys, 

Do you think there might be an automation implementation on using the swap feature in USDT-M Futures Binance to convert to BNB automatically?

**Comment by xmatthias** [comment]
it's kindof completely unclear what you're talking about ?

do you mean automatically purchasing BNB? (which would make this a duplicate of #5562) ?

**Comment by erhangunay** [comment]
It is the same yes. I am closing due to that
