### ISSUE TITLE
Adding Append Mode to Other PairList Implementations in Freqtrade

### ISSUE THREAD

**Issue by 14790897** [freqtrade/freqtrade#10893]
## Describe your environment
(if applicable)

  * Operating system:  windows
  * Python Version: __Python 3.10.11___ (`python -V`)
  * CCXT version: __ccxt==4.3.63___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade 2024.10__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

I have noticed that in the RemotePairList, there is an option to select between append and filter modes for handling the pairlist. However, in other PairList implementations (such as MarketCapPairList or VolumePairList), the default mode is filter, and there is no append option.

I would suggest adding the append processing mode to other PairList implementations, similar to what is available in RemotePairList. This would allow users to dynamically append new pairs to the existing pairlist during each iteration rather than just filtering them.

**Comment by xmatthias** [comment]
To be quite frank - i don't see the usecase / need - and it's not really explained why it would be necessary other than "other pairlists have this".
It's also a generic request "just add it everywhere" - which doesn't really make sense and shows that no real thought was put into this.


You can start with a full pairlist by using a static pairlist with `".*/USDT"` - which will contain all pairs.
You can then simply filter out all pairs you don't like / don't want to trade using the different filters / lists.

If you use an append mode - i'd not see how you can control the actual sorting properly - as each pairlist may add a duplicate pair - so there's no guarantee that the last pairlist's pairs are actually added at the bottom of the list (as an aside, most pairlists also do sorting).

**Comment by 14790897** [comment]
I understand.
Thank you for the clarification.
