### ISSUE TITLE
TemporaryError: Error in reload_markets due to PermissionDenied.

### ISSUE THREAD

**Issue by XinuxC** [freqtrade/freqtrade#10918]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtradeorg/freqtrade:2024.10
  
## Your question

When I use freqtradeorg/freqtrade:2024.10 running on Gateio, errors came up:

File "/freqtrade/freqtrade/exchange/exchange.py", line 638, in _load_async_markets
    markets = self.loop.run_until_complete(self._api_reload_markets(reload=reload))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 630, in _api_reload_markets
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Error in reload_markets due to PermissionDenied. Message: gate {"message":"Request API key does not have account permission","label":"FORBIDDEN"}
2024-11-11 14:54:38,823 - freqtrade - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.

When I go back with  freqtradeorg/freqtrade:2024.9, All good. What's the possible reason?

**Comment by xmatthias** [comment]
Well what the error says - missing permissions (a new call was added to ccxt lately).

the [updated docs](https://www.freqtrade.io/en/latest/exchanges/#gateio) also point this out. Simply adding the "account - read only" permission will have the bot work again.

**Comment by XinuxC** [comment]
> Well what the error says - missing permissions (a new call was added to ccxt lately).
> 
> the [updated docs](https://www.freqtrade.io/en/latest/exchanges/#gateio) also point this out. Simply adding the "account - read only" permission will have the bot work again.

Get it, Thank you
