### ISSUE TITLE
FreqUI does not display any charts

### ISSUE THREAD

**Issue by Sadcatcat** [freqtrade/freqtrade#10917]
## Describe your environment

  * Operating system: windows 11
  * Python Version:Python 3.12.7
  * CCXT version:ccxt==4.4.24
  * Freqtrade Version:freqtrade 2024.10
  
## Your question
My robot has started running the default simple trading strategy, even in a simulated environment. But my FreqUI doesn't have any data, or do I need to backtest first? How to operate it, brother
![Image](https://github.com/user-attachments/assets/fd2f3b53-972f-44d2-8627-4d8fea8e836d)
![Image](https://github.com/user-attachments/assets/d09d1685-d50d-473c-a655-537471623084)

I am using OKX, can my pairlists only be set to this
![Image](https://github.com/user-attachments/assets/7ef454bb-a429-4d8b-ba2e-4c7cfffab454)

**Comment by Sadcatcat** [comment]
The API and token of my Telegram robot are different from the ones I successfully configured before, and I guarantee that they are functioning properly

**Comment by Sadcatcat** [comment]
It's strange that commands with intervals of less than a second sometimes produce different results. Is it a problem with my network? brother
![Image](https://github.com/user-attachments/assets/eefcb730-4b91-4d8c-a516-c579248904e0)

**Comment by Sadcatcat** [comment]
After changing my proxy, it seems that the connection issue has been resolved, but the problem is' ERROR - This Pairlist Handler should not be used at the first position in the list of Pairlist Handler's. '‘ What is the problem
![Image](https://github.com/user-attachments/assets/90cd5628-2048-4302-ba20-263690683744)

**Comment by Sadcatcat** [comment]
Solved it, brother. But can OKX only use this
![Image](https://github.com/user-attachments/assets/6469dde2-8e70-414e-b0a9-e3e549b5e39f)

**Comment by xmatthias** [comment]
For logs and configuration - please provide them as text in the future.
I'll not try and parse out relevant information from screenshots - where it could be easily searchable from a log.

From a UI perspective, you should start at the Trade pane. 
That'll contain the most information - though one has to say that the logs don't really contain any hint about the fact that a UI did connect.

**Comment by xmatthias** [comment]
Closing this as other's of your issues suggest that you got this working now.
