### ISSUE TITLE
Strange exit signals skipping/logic of exit signals

### ISSUE THREAD

**Issue by kivinblue1** [freqtrade/freqtrade#10928]
* Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: latest docker version
  

Recently, I noticed two "stuck" positions on Bybit and OKX. Last week, all my long positions closed with large profit, except for two: the profit on these positions was 60-70%, and they didn’t close on the exit signal (at the time, I assumed exit signals should have appeared). It looked very strange. I closed these trades using "/fx all" after a couple of days. Then, checked the strategy files through backtesting. During backtesting, exit signals did indeed show up. Why might the bot have ignored them? 
![Image](https://github.com/user-attachments/assets/5dfefa32-d534-4674-bb29-05f11c534211)
![Image](https://github.com/user-attachments/assets/1e3fc536-8d36-4d92-805e-22954ad2d5bb)

**Comment by xmatthias** [comment]
well that can essentially have hundreds of reasons.
maybe your strategy refused the exit (confirm_exit) 
or you use limit orders, and the order never filled before the timeout occurred
Or your exit signals use data from the future, and only appear once a few subsequent candles have been posted ...

with the given information - more than speculation won't be possible.

**Comment by froggleston** [comment]
Impossible to say without strategy code and logs. Most likely candidates are [lookahead bias](https://www.freqtrade.io/en/stable/lookahead-analysis/) and/or [recursive bias](https://www.freqtrade.io/en/stable/recursive-analysis/). Please run these commands to check that your strategy is able to generate signals properly.

**Comment by kivinblue1** [comment]
> Impossible to say without strategy code and logs. Most likely candidates are [lookahead bias](https://www.freqtrade.io/en/stable/lookahead-analysis/) and/or [recursive bias](https://www.freqtrade.io/en/stable/recursive-analysis/). Please run these commands to check that your strategy is able to generate signals properly.



> well that can essentially have hundreds of reasons. maybe your strategy refused the exit (confirm_exit) or you use limit orders, and the order never filled before the timeout occurred Or your exit signals use data from the future, and only appear once a few subsequent candles have been posted ...
> 
> with the given information - more than speculation won't be possible.

Ok, i checked docker logs in both bots in in the all places where exit signals should be:

OKX:
2024-11-11 13:45:01,094 - freqtrade.exchange.exchange - INFO - Failed to reuse watch LDO/USDT:USDT, 15m, False, 1731332700000, 1730919481968, 2024-11-11T13:45:00, 2024-11-06T18:58:01 

OTHER PAIRS GET THE SAME ERROR
BYBIT:
2024-11-05 14:15:01,099 - freqtrade.exchange.common - WARNING - fetch_l2_order_book() returned exception: "Could not get order book due to NetworkError. Message: bybit GET https://api.bybit.com/v5/market/orderbook?symbol=INJUSDT&category=linear&limit=1". Retrying still for 3 times.

OTHER PAIRS GET THE SAME ERROR

**Comment by kivinblue1** [comment]
> well that can essentially have hundreds of reasons. maybe your strategy refused the exit (confirm_exit) or you use limit orders, and the order never filled before the timeout occurred Or your exit signals use data from the future, and only appear once a few subsequent candles have been posted ...
> 
> with the given information - more than speculation won't be possible.



> > Impossible to say without strategy code and logs. Most likely candidates are [lookahead bias](https://www.freqtrade.io/en/stable/lookahead-analysis/) and/or [recursive bias](https://www.freqtrade.io/en/stable/recursive-analysis/). Please run these commands to check that your strategy is able to generate signals properly.
> 
> > well that can essentially have hundreds of reasons. maybe your strategy refused the exit (confirm_exit) or you use limit orders, and the order never filled before the timeout occurred Or your exit signals use data from the future, and only appear once a few subsequent candles have been posted ...
> > with the given information - more than speculation won't be possible.
> 
Ok, i checked docker logs in both bots in in the all places where exit signals should be:

OKX: 2024-11-11 13:45:01,094 - freqtrade.exchange.exchange - INFO - Failed to reuse watch LDO/USDT:USDT, 15m, False, 1731332700000, 1730919481968, 2024-11-11T13:45:00, 2024-11-06T18:58:01

OTHER PAIRS GET THE SAME ERROR BYBIT: 2024-11-05 14:15:01,099 - freqtrade.exchange.common - WARNING - fetch_l2_order_book() returned exception: "Could not get order book due to NetworkError. Message: bybit GET https://api.bybit.com/v5/market/orderbook?symbol=INJUSDT&category=linear&limit=1". Retrying still for 3 times.

OTHER PAIRS GET THE SAME ERROR

maybe it was at these moments that there were problems with the connection and the bot could not calculate the exit signals?

**Comment by froggleston** [comment]
Definitely looks like it! I think we have our answer 😄

**Comment by kivinblue1** [comment]
> Определенно похоже! Думаю, у нас есть ответ 😄

The bot will not exit the position if it detects an exit signal on the old candles?

**Comment by froggleston** [comment]
No.

**Comment by kivinblue1** [comment]
> No.

I found  ignore_buying_expired_candle_after in the configuration, but there is no such var for exit signals.

**Comment by froggleston** [comment]
Correct, there isn't, and this wouldn't apply in your case anyway for either entries or exits that have happened on previous/expired candles.

**Comment by xmatthias** [comment]
> OKX: 2024-11-11 13:45:01,094 - freqtrade.exchange.exchange - INFO - Failed to reuse watch LDO/USDT:USDT, 15m, False, 1731332700000, 1730919481968, 2024-11-11T13:45:00, 2024-11-06T18:58:01

This won't cause problems - the bot will fall back to using the rest api.
it may get the data a second or two later - but that's about it.


> BYBIT: 2024-11-05 14:15:01,099 - freqtrade.exchange.common - WARNING - fetch_l2_order_book() returned exception: "Could not get order book due to NetworkError. Message: bybit GET https://api.bybit.com/v5/market/orderbook?symbol=INJUSDT&category=linear&limit=1". Retrying still for 3 times.

this is a problem if the error repeats (for more than once) - as it suggests that there was a network interruption.

**Comment by kivinblue1** [comment]
> > OKX: 2024-11-11 13:45:01,094 - freqtrade.exchange.exchange - INFO - Failed to reuse watch LDO/USDT:USDT, 15m, False, 1731332700000, 1730919481968, 2024-11-11T13:45:00, 2024-11-06T18:58:01
> 
> This won't cause problems - the bot will fall back to using the rest api. it may get the data a second or two later - but that's about it.
> 
> > BYBIT: 2024-11-05 14:15:01,099 - freqtrade.exchange.common - WARNING - fetch_l2_order_book() returned exception: "Could not get order book due to NetworkError. Message: bybit GET https://api.bybit.com/v5/market/orderbook?symbol=INJUSDT&category=linear&limit=1". Retrying still for 3 times.
> 
> this is a problem if the error repeats (for more than once) - as it suggests that there was a network interruption.

thanks for the answers,  I hope I will be able to catch the moment when the bot gets stuck with trades. 
at least until this moment, I did not know that the bot does not exit trades on expired exit signals

**Comment by xmatthias** [comment]
>  I did not know that the bot does not exit trades on expired exit

well it depends what you consider expired exit signal
a signal is valid for the duration of it's candle - once it disappears - the bot won't try to exit on that past signal again.

That said - a more likely scenario is a lookahead issue, where you're seeing a signal now - but it wasn't there while the candle was happening - because signal is based on data from the future.

**Comment by froggleston** [comment]
We can reopen this if there's any further confirmation of issues, but it sounds like strategy logic rather than a freqtrade problem.
