### ISSUE TITLE
scikit-optimize has been archived by the owner on Feb 28, 2024

### ISSUE THREAD

**Issue by ducky-duke** [freqtrade/freqtrade#10929]
## Your question

[scikit-optimize](https://github.com/scikit-optimize/scikit-optimize) This repository has been archived by the owner on Feb 28, 2024. It is now read-only.

Do you have any plan to replace it by other lib ?

**Comment by xmatthias** [comment]
We run our [own fork](https://github.com/freqtrade/ft-scikit-optimize) with a few compatibility fixes and cherry-picked PR's which were ready but not merged.

It shouldn't be considered a fully supported replacement - but a project in maintenance mode - but considering that scikit-optimize works well as is without updates (there haven't been updates in the past several years before it got archived) - i don't really see an immediate need to take action - especially considering that we can keep compatibility with newer versions of other dependencies if necessary.
