### ISSUE TITLE
Missing decimal precision in telegram notification

### ISSUE THREAD

**Issue by xzmeng** [freqtrade/freqtrade#10922]
![image](https://github.com/user-attachments/assets/495953a2-9d22-4009-8fd7-96077211c14b)

the exit rate is 1.222, but displayed 1.22, missing one decimal precision.

**Comment by xmatthias** [comment]
well no it's not? (or your description is odd / off / ...).


The screenshot shows the exit rate as 0.122 ... there's no 1.Xxx involved - so your description - and the actual price - are off by more than 1$ (while XLM spiked today - it wasn't > 1$ this week).

Maybe you can include the logs for this - which should simplify correlating the screenshot with the price.

**Comment by xzmeng** [comment]
i am not sure why i misplaced the decimal point, but it looks like you have deciphered the intended meaning👍
