### ISSUE TITLE
Question about rounded(stop_price) in PrecisionFilter documentation

### ISSUE THREAD

**Issue by AchmadFathoni** [freqtrade/freqtrade#10939]
## Your question
Is there any value of `stop_price` that can satisfy  `rounded(stop_price) < rounded(stop_price*0.99)`? I think no matter what the rounding policy is (floor, ceiling, closest), no value of `stop_price` can satisfy that. If this true, should the [documentation](https://www.freqtrade.io/en/stable/plugins/#precisionfilter) be changed to `rounded(stop_price) == rounded(stop_price*0.99)` for clarity?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.

We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.


Filling out the template helps reduce our workload, and we greatly appreciate that.

---

The actual comparison is `<=` in the code  - so the documentation is fine as is.

There won't be many pairs that will hit this boundary for sure - but it's surely possible (we added it as we encountered such a case) - especially on exchanges with very low valued coins (gate, kucoin).

**Comment by AchmadFathoni** [comment]
I didn't find any 'rounded()' function in the entire code repository so I thought it just imaginary example. I'll look in PrecisionFilter code to understand this.

**Comment by xmatthias** [comment]
it's not intended to describe how the code works (which functions it calls) - but what the functionality does in terms a regular user unfamiliar with the codebase understands.

`price_to_precision()` is what you're looking for - which will round (or trunc) price to precision. 
Depending on the exchange, there's several different modes rounding can happen - for that to understand, best look at the tests we have for that function.
