### ISSUE TITLE
htx exchange and VolatilityFilter

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#10934]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: current miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.10 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

With the htx exchange (dryrun), using a simple VolumePairList of 250 assets (or a different number), I do not have any pairs in the whitelist, as I add the VolatilityFilter, even when I set it to max_volatility 0.99, with no minimum. Does htx not send any volatility information, or can I set a volatility range in a different way? If you think, you need to test it, just do it as simple, as I have described it: A VolumePairlist with 250 assets, and the above very simple volatility rule. No other restrictions. I look forward to your feedback.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Quite honestly - not a problem i can recreate.

using the following config on HTX, i get around 244 pairs.
if i increase max_volatitlity beyond repair (i tried with 20) - i get 246 pairs - probably increasing it more would yield the full 250 results that come out of the volatility filter.

That's kinda expected, as we've seen a big spike, so several pairs will have seen gains of > 100% gain.

```
[
  {
    "method": "VolumePairList",
    "number_assets": 250,
    "sort_key": "quoteVolume",
    "refresh_period": 1800
  },
  {
    "method": "VolatilityFilter",
    "lookback_days": 10,
    "max_volatility": 0.99,
    "refresh_period": 1800
  }
]
```

**Comment by myNextCoder** [comment]
I thank you, I was almost sure, that the reason must be elsewhere. I will find it out. . .
