### ISSUE TITLE
PercentChangePairList, needs fixing, *100 need to be added

### ISSUE THREAD

**Issue by ManstonGaming** [freqtrade/freqtrade#10937]
* Operating system: Ubuntu
  * Python Version: 3
  * CCXT version: 4.4.24
  * Freqtrade Version: 2024.10
  
I created a strat that fetches big dips. now i'm using the " PercentChangePairList ".
now i've stumbled apon something i cant wrap my head around haha.

so i want to load only the pairs that are in a certain Percentage range within a certain amount of candles.
now the issue is the max_value it always has to be positive else it loads nothing. so 0 > 
i have swapped it arround to see if it changes anything. is there a work around or am i thinking wrong or is it just not possible? ( cant imagine )

but the idea is atleast -5% and max -30%

so this is what i have, and it wont load anything:
```javascript
    {
        "method": "PercentChangePairList",
        "number_assets": 100,
		"sort_key": "percentage",
		"max_value": -5,
		"min_value": -30,
        "lookback_timeframe": "5m",
        "lookback_period": 12,
		"sort_direction": "asc"
    }
``` 

Now it will load from 0 to -30%
```javascript
    {
        "method": "PercentChangePairList",
        "number_assets": 100,
		"sort_key": "percentage",
		"max_value": 0,
		"min_value": -30,
        "lookback_timeframe": "5m",
        "lookback_period": 12,
		"sort_direction": "asc"
    },
``` 

lets sum it up, i only want to see the pairs that are in between a negative percentage, and not from a minimum negative to 0.
but the max filter only take positive input.

**Comment by froggleston** [comment]
Looking at [the code](https://github.com/freqtrade/freqtrade/blob/3276dd6b94adcb6df4f2362fabb22216b9a37317/freqtrade/plugins/pairlist/PercentChangePairList.py#L223) your first example looks correct. We'd need more information as to what "it won't load anything" means. 

We'd need an exact example of a pair you'd expect to see in that list, and when it doesn't appear in the filter.

**Comment by ManstonGaming** [comment]
ok, so i created a indicator for the visuals:

```python
df['prc_num'] = ( (df['close']-df['close'].shift(12)) / df['close'].shift(12) * 100 )
``` 
![Image](https://github.com/user-attachments/assets/c08e5a46-7c11-426a-b0a3-cceaa8445d75)
now i got the settings:
```javascript
"max_value": 0,
"min_value": -20,
``` 
the outcome: ![Image](https://github.com/user-attachments/assets/91c1b3da-f6be-4e04-addc-13d5b9f5e458)
```
2024-11-15 09:02:03,868 - AgeFilter - INFO - Validated 93 pairs.
2024-11-15 09:02:03,869 - PercentChangePairList - INFO - Using change range of 12 candles, timeframe: 5m, starting from 2024-11-15T06:55:00 till 2024-11-15T07:55:00
2024-11-15 09:02:14,044 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 80 pairs: ['NEIRO/USDT', 'TNSR/USDT', 'EOS/USDT', 'ATH/USDT', 'IO/USDT', 'XLM/USDT', 'APEX/USDT', 'SUNDOG/USDT', 'PEPE/USDT', 'MOG/USDT', 'RENDER/USDT', 'KAS/USDT', 'XRP/USDT', 'STX/USDT', 'MASK/USDT', 'INJ/USDT', 'DOGE/USDT', 'ADA/USDT', 'BOME/USDT', 'EIGEN/USDT', 'HMSTR/USDT', 'PEOPLE/USDT', 'NEAR/USDT', 'SHIB/USDT', 'STRK/USDT', 'WIF/USDT', 'GALA/USDT', 'DOGS/USDT', 'AVAX/USDT', 'ATOM/USDT', 'ICP/USDT', 'MERL/USDT', 'ARKM/USDT', 'MNT/USDT', 'ARB/USDT', 'JASMY/USDT', 'STETH/USDT', 'RUNE/USDT', 'ORDI/USDT', 'JTO/USDT', 'ETH/USDT', 'ALT/USDT', 'NOT/USDT', 'LINK/USDT', 'ZETA/USDT', 'W/USDT', 'UNI/USDT', 'OP/USDT', 'PYTH/USDT', 'APE/USDT', 'SEI/USDT', 'FIL/USDT', 'TIA/USDT', 'PUFFER/USDT', 'ZRO/USDT', 'TON/USDT', 'BCH/USDT', 'BTC/USDT', 'PONKE/USDT', 'WLD/USDT', 'ZK/USDT', 'FTM/USDT', 'BNB/USDT', 'FET/USDT', 'ONDO/USDT', 'MEME/USDT', 'POL/USDT', 'ETHFI/USDT', 'CTC/USDT', 'ENA/USDT', 'CARV/USDT', 'SOL/USDT', 'LTC/USDT', 'APT/USDT', 'LDO/USDT', 'FLOKI/USDT', 'JUP/USDT', 'DOT/USDT', 'MYRO/USDT', 'DRIFT/USDT']
``` 

now i got the settings:
```javascript
"max_value": -1,
"min_value": -20,
``` 
the outcome: ![Image](https://github.com/user-attachments/assets/d2b036c6-d0a7-4ee7-b949-1beba7d02f72)
```
2024-11-15 09:05:40,326 - AgeFilter - INFO - Validated 93 pairs.
2024-11-15 09:05:40,327 - PercentChangePairList - INFO - Using change range of 12 candles, timeframe: 5m, starting from 2024-11-15T07:00:00 till 2024-11-15T08:00:00
2024-11-15 09:05:50,819 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 0 pairs: []
``` 
I hope this give the idea of the problem, 
max_value to 0 and min_value to -20 means it gives me correct from -20 to 0
so now even with -1 and its clearly has to be there? since the shown pair is -5 >

i was looking trough [the code](https://github.com/freqtrade/freqtrade/blob/3276dd6b94adcb6df4f2362fabb22216b9a37317/freqtrade/plugins/pairlist/PercentChangePairList.py#L292) for the percentage, it seems right?
```python
            # in case of candle data calculate typical price and change for candle
            if pair_candles is not None and not pair_candles.empty:
                current_close = pair_candles["close"].iloc[-1]
                previous_close = pair_candles["close"].shift(self._lookback_period).iloc[-1]
                pct_change = (
                    ((current_close - previous_close) / previous_close) if previous_close > 0 else 0
                )

                # replace change with a range change sum calculated above
                filtered_tickers[i]["percentage"] = pct_change
            else:
                filtered_tickers[i]["percentage"] = 0
```

**Comment by ManstonGaming** [comment]
So i found out the code forgot the *100.
i made an edit, dont know if its completly correct but this has to be fixed :P

```python
            # in case of candle data calculate typical price and change for candle
            if pair_candles is not None and not pair_candles.empty:
                current_close = pair_candles["close"].iloc[-1]
                previous_close = pair_candles["close"].shift(self._lookback_period).iloc[-1]
                pct_change = (
                    ((current_close - previous_close) / previous_close) * 100 if previous_close > 0 else 0
                )

                # replace change with a range change sum calculated above
                filtered_tickers[i]["percentage"] = pct_change
            else:
                filtered_tickers[i]["percentage"] = 0
``` 

with the code as is you need to filter on:
than it works!! so the way its explained in the calculation and script differs! :D
```javascript
	"max_value": -0.01,
        "min_value": -0.20,
``` 

[part from the documentation](https://www.freqtrade.io/en/stable/plugins/#percent-change-pair-list) 

Example Configuration to Read from Ticker

```javascript
"pairlists": [
    {
        "method": "PercentChangePairList",
        "number_assets": 15,
        "min_value": -10,
        "max_value": 50
    }
],
```

**Comment by xmatthias** [comment]
that fix seems OK, actually.
It's actually a fallback mode for this - as usually, exchanges provide this properly in one dictionary (as percentage).

The  *100 was clearly forgotten here, as the fallback mode used a different unit than the original mode.

Will be fixed on develop in a bit.
