### ISSUE TITLE
Hi, how to realize signal warning?

### ISSUE THREAD

**Issue by liyunlongaaa** [freqtrade/freqtrade#10930]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
Hi, I would like to customize a function, for example, when a technical indicator is triggered, I would like it to notify me via telegram or other means, and I decide whether to act on it or not, how can I implement it? Can I do it inside the populate_indicators function, thanks!

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.

We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.


Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Freqtrade is designed to be an automated trading bot, so this is not something freqtrade does support out of the box - or aims to support out of the box.

you can probably use something around [send notification](https://www.freqtrade.io/en/stable/strategy-customization/#send-notification) to notify yourself about a signal - and then use [force_enter](https://www.freqtrade.io/en/stable/telegram-usage/#forcelong-rate-forceshort-rate) to enter a trade.

it's still not something we support, or aim to support - hence i'll be closing this as not planned.
