### ISSUE TITLE
Can you buy two positions of the same coin?

### ISSUE THREAD

**Issue by husnoo** [freqtrade/freqtrade#10936]
## Your question
From https://www.freqtrade.io/en/latest/bot-basics/:
```
Trade: Open position.
Open Order: Order which is currently placed on the exchange, and is not yet complete.
```
from https://www.freqtrade.io/en/stable/configuration/:
```
max_open_trades	Required. Number of open trades your bot is allowed to have. Only one open trade per pair is possible, so the length of your pairlist is another limitation that can apply. If -1 then it is ignored (i.e. potentially unlimited open trades, limited by the pairlist). [More information below](https://www.freqtrade.io/en/stable/configuration/#configuring-amount-per-trade). [Strategy Override](https://www.freqtrade.io/en/stable/configuration/#parameters-in-the-strategy).
```

Does this mean that a single position is kept for a given coin? For example on the way down a market crash, I can't keep buying multiple positions of `stake_amount` for the same coin?

**Comment by froggleston** [comment]
No, you can't position stack (multiple open *trades* of the same coin).

You can adjust an existing trade by making multiple *orders*: https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position
