### ISSUE TITLE
docker question

### ISSUE THREAD

**Issue by nbwcbz** [freqtrade/freqtrade#10945]
docker-compose.yml folder configuration, image: freqtradeorg/freqtrade:stable does not support the reversal of long and short signals? But image: freqtradeorg/freqtrade:develop can support the reversal of long and short signals in backtesting? What's going on?

**Comment by xzmeng** [comment]
It's not yet released.

**Comment by xmatthias** [comment]
It's a different version.

develop is the rolling version - which will update whenever we change something in the develop branch (as the name implies).
It can contain breaking changes eventually without much notice (following PR's will help for this).

Stable is aligned to the latest release version - which is essentially a monthly snapshot - where we'll take the time to write a change log - point out potentially breaking changes.
