### ISSUE TITLE
"dry_run": false，无法交易

### ISSUE THREAD

**Issue by daguanglu** [freqtrade/freqtrade#10958]
当dry_run是true的时候可以正常时间模拟交易，但是当我改为false、配置exchange的key和secret、将binance API中的允许读取和允许现货及杠杆交易打开时，没有产生任何交易订单。

**Comment by xmatthias** [comment]
Issues will only be considered if they're in english.

Feel free to use a translator if you must - but try to proof-read the response you get from the automatic translation.


---

Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.
