### ISSUE TITLE
OKX Error 50119: API key doesn't exist

### ISSUE THREAD

**Issue by plinders** [freqtrade/freqtrade#10967]
## Describe your environment

  * Freqtrade Version: 2024.10, through Docker
  
## Your question

Running into the following error when going live on OKX spot market: `ccxt.base.errors.ExchangeError: okx {"msg":"API key doesn't exist","code":"50119"}`. 

My OKX config.json:
```
    "name": "okx",
    "key": "OKX-api-key",
    "secret": "apisecret",
    "password": "API_passphrase or account_password",
```
Not really sure whether to add the API passphrase or my account password in the "password" field, but neither works so I assume something else is going on. I've given permissions for View and Trade, and have only whitelisted the public IP that belongs to the bot. Could you please advise on how to resolve this?

**Comment by xmatthias** [comment]
Well the error is very explicit in "does not exist" - which essentially means that you made a mistake copying the api key (spaces at the front / back, ...).


If the password is wrong (the API key password goes here!) - that's a different error - as well as if you've got the IP limitation wrong.

**Comment by plinders** [comment]
Thanks for the reply! Still can't get it to work unfortunately, tried fresh API keys, both on my main account as well as a subaccount but still get the same error. The other thing I noticed is that if I try logging into `okx.com`, it redirects me to `my.okx.com`. Not sure if that matters for API usage?

Either way, I'm now using Bybit which is working for me.

**Comment by xmatthias** [comment]
my.okx.com should be fine - though it's curious, as i can use OKX just fine.

Is that config section you posted above actually within the exchange section of the configuration?

essentially, when you run `freqtrade show-config -c config.json` - you should see a structure similar to the following (show-config will redact known secrets - if you can see your keys there - they're in the wrong place).

![Image](https://github.com/user-attachments/assets/e3657935-0bbd-45c3-b959-d3776fbb38d1)

essentially, it should look like this:

```jsonc
{
//...
  "exchange": {
    "name": "okx",
    "key": "OKX-api-key",
    "secret": "apisecret",
    "password": "API_passphrase or account_password",
  }
}
```

**Comment by plinders** [comment]
Looks about right to me:

![Image](https://github.com/user-attachments/assets/feb39e21-f967-4340-9d12-ad79bf1ee58e)

If necessary I can post the rest of my config. 
Maybe a long shot - and probably not true - the OKX API key has a few hyphens in it, I don't need to escape those with a slash right?

**Comment by xmatthias** [comment]
no - what you get from the exchange, you essentially use "ctrl+c" - and then "ctrl+v" that into the appropriate field.

Things to keep in mind though:
environment variables may overwrite what's in there
leading / trailing spaces will cause errors / problems.

**Comment by AbuzarAkbari** [comment]
I am experiencing the same issue. I am trying out OKX as an alternative exchange, but I keep encountering the error: {"msg":"API key doesn't exist","code":"50119"}.

**Comment by xmatthias** [comment]
well the error is clear - the api code doesn't exist (which suggests that the key string is wrong).

There's nothing freqtrade does to this string - and the error also comes directly from the API.

**Comment by jimmson** [comment]
I'm having the same issue, might be related to this https://github.com/ccxt/ccxt/issues/24601

**Comment by jimmson** [comment]
I assume it will be fixed when the fix is released in ccxt

**Comment by plinders** [comment]
Perhaps good to add here, in my initial post I’ve been using API keys from my.okx.com. Reckon this will be resolved with the ccxt fix

**Comment by xmatthias** [comment]
well i'm not entirely sure what my.okx.com is (compared to the "real" okx.com). 
that's even more confusing as i get redirected to www.okx.com if i navigate to my.okx.com immediately.

seems like ccxt added another subclass that implements that - which will fix it - but will **not** work flawlessly with freqtrade without further adjustment (ccxt's myokx won't use the freqtrade okx subclass, which will be necessary for proper workings).

**Comment by xmatthias** [comment]
the very very latest develop (0032f9a960ea9279eb6fe892036c54ac00cfca8c and later) should work with myokx - though i can't really test that myself.

When updating to that - make sure to also update dependencies - as the ccxt update is key to even have a myokx exchange (the exchange used must be "myokx").

**Comment by plinders** [comment]
> well i'm not entirely sure what my.okx.com is (compared to the "real" okx.com). that's even more confusing as i get redirected to [www.okx.com](http://www.okx.com) if i navigate to my.okx.com immediately.
> 
> seems like ccxt added another subclass that implements that - which will fix it - but will **not** work flawlessly with freqtrade without further adjustment (ccxt's myokx won't use the freqtrade okx subclass, which will be necessary for proper workings).

Pretty sure both are the 'real' okx, I get redirected to [my.okx.com](http://my.okx.com) if I try to login at [www.okx.com](http://www.okx.com). Perhaps a regional thing? I'm in NL.

Great to hear you've added it to freqtrade, will be trying it soon.

**Comment by plinders** [comment]
Can confirm, works great now!

**Comment by DevMichiel** [comment]
Seem to experience the same issue as described above, also from NL. Re-created the API key, using 'myokx' and updated ccxt.
Using freqtrade stable and develop container. Hope somebody can help...

`freqtrade-myokx | 2025-01-20 20:18:48,940 - freqtrade.exchange.exchange - INFO - Using CCXT 4.4.48`
`freqtrade-myokx | 2025-01-20 20:18:48,964 - freqtrade.exchange.exchange - INFO - Using Exchange "MyOKX(EEA)"`
`freqtrade-myokx | 2025-01-20 20:18:49,246 - freqtrade.exchange.common - WARNING - _load_async_markets() returned exception: "Error in reload_markets due to ExchangeError. Message: myokx {"msg":"API key doesn't exist","code":"50119"}". Retrying still for 3 times.`
`freqtrade-myokx | 2025-01-20 20:18:49,646 - freqtrade.exchange.common - WARNING - _load_async_markets() returned exception: "Error in reload_markets due to ExchangeError. Message: myokx {"msg":"API key doesn't exist","code":"50119"}". Retrying still for 2 times.`
`freqtrade-myokx | 2025-01-20 20:18:50,072 - freqtrade.exchange.common - WARNING - _load_async_markets() returned exception: "Error in reload_markets due to ExchangeError. Message: myokx {"msg":"API key doesn't exist","code":"50119"}". Retrying still for 1 times.`
`freqtrade-myokx | 2025-01-20 20:18:50,467 - freqtrade.exchange.common - WARNING - _load_async_markets() returned exception: "Error in reload_markets due to ExchangeError. Message: myokx {"msg":"API key doesn't exist","code":"50119"}". Giving up.`
`freqtrade-myokx | 2025-01-20 20:18:50,467 - freqtrade.exchange.exchange - ERROR - Could not load markets.`

**Comment by xmatthias** [comment]
@DevMichiel well it's the exchange returning this error - so it's for sure right "somehow" 😆 

You may not have saved the file (happened to me before) - you may have mixed up secret and key, ...
you may have ip restrictions not matching the IP (though i THINK that should raise a different error / problem).

**Comment by Aqvdrt** [comment]
I met the same problem. After struggling for hours, found that the problem lies in the hostname of request url. ❌When I used "eea.okx.com" which is shown on the okx api doc v5, it threw out the error "API key doesn't exist". ✅But when I switched to "www.okx.com", it got the right result. [😓speechless....]

**Comment by xmatthias** [comment]
well depending on which one you're with - you can use either "okx" or "myokx" as exchange name.
both work and are supported - though it's ... not obvious when you're being redirected to the one or the other 😆

**Comment by nicot2025** [comment]
Hello,

I am facing a persistent issue while trying to connect to the OKX Testnet API, and I need your assistance to identify the cause. I’ll explain the problem in detail below:

General Description of the Issue: I am attempting to connect to the endpoint GET /api/v5/account/balance using an API key created in the Testnet environment, but I consistently receive the error "API key doesn't exist" (error code: 50119) with an HTTP 401 Unauthorized status.
Steps I’ve Tried:
I created four different API keys in OKX Testnet through the "API Management" interface.
I tested each key in Postman and with a custom Python script to calculate the signature (OK-ACCESS-SIGN) and update the timestamp (OK-ACCESS-TIMESTAMP) using the following script:

import hmac
import hashlib
import base64
import time

secret_key = "YOUR_SECRET_KEY"
timestamp = time.strftime("%Y-%m-%dT%H:%M:%S.000Z", time.gmtime())
method = "GET"
path = "/api/v5/account/balance"
body = ""

message = timestamp + method + path + body
signature = hmac.new(secret_key.encode(), message.encode(), hashlib.sha256).digest()
signature_base64 = base64.b64encode(signature).decode()


I added my device’s IP address (31.34.177.14) to the IP Whitelist in the key’s settings, but the error persists.
I tried switching networks (Wi-Fi and mobile data) and synchronizing my device’s time automatically, but it didn’t help.
Configuration Details:
URL used: https://www.okx.com/api/v5/account/balance (I confirmed this is for Testnet).
Headers used in the request:
Content-Type: application/json
OK-ACCESS-KEY: [copied directly from the OKX interface]
OK-ACCESS-PASSPHRASE: [entered correctly]
OK-ACCESS-TIMESTAMP: [calculated automatically based on current UTC time]
OK-ACCESS-SIGN: [calculated using the corresponding Secret Key]
My device’s IP address: 31.34.177.14 (added to IP Whitelist).
Consistent Response: I always receive:
text

Copier
{
    "msg": "API key doesn't exist",
    "code": "50119"
}
Additional Notes:
I double-checked the copying of the keys manually to avoid errors.
I tried creating new keys with different configurations (with and without IP Whitelist) without success.
I suspect there might be an issue with my Testnet account or the server settings, as all keys fail regardless of the configurations.
I kindly request your help in identifying the cause and resolving this issue. If you need additional details (such as the key ID or request logs), please let me know what’s required, and I’ll provide them carefully while protecting my sensitive data. I urgently need a solution to this problem, and I thank you in advance for your support.

Best regards,

**Comment by stash86** [comment]
we don't support testnet. You can do a dry-run if you want to do paper trading.

**edit by @xmatthias**: On top of the question being about test-net - it's not a question related to freqtrade - so this is absolutely the wrong place to ask.
