### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by coppaxamsukk** [freqtrade/freqtrade#10977]
## Describe your environment

  * Operating system: ____LINUX
  * Python Version: _____ (`python -LATEST `)
  * CCXT version: _____ (`pip freeze | grep ccxt`)LATEST
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)LATEST 
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
The error :

error: failed to solve: process "/bin/sh -c pip install -e . --user --no-cache-dir --no-build-isolation && mkdir /freqtrade/user_data/ && freqtrade install-ui" did not complete successfully: exit code: 1

**Comment by froggleston** [comment]
Please *fill in* the template.

**Comment by coppaxamsukk** [comment]
> Please _fill in_ the template.

Just tell me can it be deployed in render? Or others?
I would debug and share!

**Comment by hippocritical** [comment]
why cant you do the basic stuff and just fill out the template

**Comment by stash86** [comment]
`Latest` and `Linux` give us zero info. Please open a new issue with complete information if you want us to look at your issue. Thanks

**Comment by xmatthias** [comment]
Freqtrade may or may not work with render - it's a service i hear about for the first time.
We also don't give recommendations about which service to use aside from "any VPS provider of your choice".

Services that run apps "as a service" are often difficult to work with, as freqtrade requires the service to be up 24/7 - and most such services pause containers if they don't get any traffic for some period of time - making them unsuitable to run freqtrade.
If that's the case for your particular service - i can't tell - it's up to you to do this investigation if you're keen on using a particular service (feedback on "this works, or doesn't work" is obviously welcome).

At any rate, your best bet testing with such services is however to use the pre-built docker-container - as then you control what's going to be deployed.
