### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by coppaxamsukk** [freqtrade/freqtrade#10976]
The error :  

--------------------
error: failed to solve: process "/bin/sh -c pip install -e . --user --no-cache-dir --no-build-isolation   && mkdir /freqtrade/user_data/   && freqtrade install-ui" did not complete successfully: exit code: 1

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.

We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.


Filling out the template helps reduce our workload, and we greatly appreciate that.
---


well something in the installation process failed.

With the amount of information given however, it's however impossible to help you further.

**Comment by coppaxamsukk** [comment]
I'm opening new one with template
