### ISSUE TITLE
Backtesting Error: pyarrow.lib.ArrowInvalid: Not an Arrow file despite valid Feather files

### ISSUE THREAD

**Issue by 14790897** [freqtrade/freqtrade#10978]
## Describe your environment

  * Operating system: _windows___
  * Python Version: __Python 3.10.11___ (`python -V`)
  * CCXT version: __4.4.26___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _freqtrade 2024.10___ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Describe the problem:

I encountered an issue while running backtesting in Freqtrade. The process fails with the error message pyarrow.lib.ArrowInvalid: Not an Arrow file. However, upon manually checking the Feather files in the user_data/data/binance directory, all files are valid and can be read without any errors using pandas.read_feather().

### Steps to reproduce:

  1. freqtrade download-data --exchange binance --pairs .*/USDT -t 1m
  2. freqtrade backtesting --strategy YourStrategy --config user_data/config.json
  3. Backtesting fails with the following error:
```
pyarrow.lib.ArrowInvalid: Not an Arrow file
```

  
### Observed Results:

  * What happened?
  Backtesting fails, reporting that the file is "Not an Arrow file." However, when I manually test the files using the following script, all Feather files in the directory load correctly without any errors:

```py
import pandas as pd
import os

directory = r"user_data\data\binance"

for filename in os.listdir(directory):
    if filename.endswith(".feather"): 
        filepath = os.path.join(directory, filename)
        try:
            df = pd.read_feather(filepath)
            print(f"Successfully read: {filename}")
            print(df.head())
        except Exception as e:
            print(f"Error reading {filename}: {e}")

```
The issue seems to occur specifically when running backtests on 1-minute (1m) timeframe data. Backtests with 5-minute (5m) timeframe data run without issues.
Since the error message (pyarrow.lib.ArrowInvalid: Not an Arrow file) does not specify which file is problematic, I am unable to pinpoint the exact file causing the issue.
  * What did you expect to happen?
Backtesting should successfully load Feather files and proceed without errors.

### Relevant code exceptions or logs

  ```
  2024-11-24 11:01:47,142 - freqtrade - ERROR - Fatal exception! 
Traceback (most recent call last): 
  File "C:\git-program\freqtrade\freqtrade\main.py", line 44, in main 
    return_code = args["func"](args) 
  File "C:\git-program\freqtrade\freqtrade\commands\optimize_commands.py", line 61, in start_backtesting 
    backtesting.start() 
  File "C:\git-program\freqtrade\freqtrade\optimize\backtesting.py", line 1638, in start 
    data, timerange = self.load_bt_data() 
  File "C:\git-program\freqtrade\freqtrade\optimize\backtesting.py", line 288, in load_bt_data 
    data = history.load_data( 
  File "C:\git-program\freqtrade\freqtrade\data\history\history_utils.py", line 110, in load_data 
    hist = load_pair_history( 
  File "C:\git-program\freqtrade\freqtrade\data\history\history_utils.py", line 65, in load_pair_history 
    return data_handler.ohlcv_load( 
  File "C:\git-program\freqtrade\freqtrade\data\history\datahandlers\idatahandler.py", line 396, in ohlcv_load 
    pairdf = self._ohlcv_load( 
  File "C:\git-program\freqtrade\freqtrade\data\history\datahandlers\featherdatahandler.py", line 62, in _ohlcv_load 
    pairdata = read_feather(filename) 
  File "C:\git-program\freqtrade\venv\lib\site-packages\pandas\io\feather_format.py", line 124, in read_feather 
    return feather.read_feather( 
  File "C:\git-program\freqtrade\venv\lib\site-packages\pyarrow\feather.py", line 226, in read_feather 
    return (read_table( 
  File "C:\git-program\freqtrade\venv\lib\site-packages\pyarrow\feather.py", line 252, in read_table 
    reader = _feather.FeatherReader( 
  File "pyarrow\\_feather.pyx", line 79, in pyarrow._feather.FeatherReader.__cinit__ 
  File "pyarrow\\error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status 
  File "pyarrow\\error.pxi", line 92, in pyarrow.lib.check_status 
pyarrow.lib.ArrowInvalid: Not an Arrow file
  ```

some files in user_data\data\binance:
<details>
<summary>Expand full </summary>
  <pre><code>
futures
1000SATS_USDT-15m.feather
1000SATS_USDT-1h.feather
1000SATS_USDT-1m.feather
1000SATS_USDT-5m.feather
1INCH_USDT-15m.feather
1INCH_USDT-1h.feather
1INCH_USDT-1m.feather
1INCH_USDT-5m.feather
1MBABYDOGE_USDT-15m.feather
1MBABYDOGE_USDT-1h.feather
1MBABYDOGE_USDT-1m.feather
1MBABYDOGE_USDT-5m.feather
AAVE_USDT-15m.feather
AAVE_USDT-1h.feather
AAVE_USDT-1m.feather
AAVE_USDT-5m.feather
ACA_USDT-15m.feather
ACA_USDT-1h.feather
ACA_USDT-1m.feather
ACA_USDT-5m.feather
ACE_USDT-15m.feather
ACE_USDT-1h.feather
ACE_USDT-1m.feather
ACE_USDT-5m.feather
ACH_USDT-15m.feather
ACH_USDT-1h.feather
ACH_USDT-1m.feather
ACH_USDT-5m.feather
ACM_USDT-15m.feather
ACM_USDT-1h.feather
ACM_USDT-1m.feather
ACM_USDT-5m.feather
ACT_USDT-15m.feather
ACT_USDT-1h.feather
ACT_USDT-1m.feather
ACT_USDT-5m.feather
ADA_USDT-15m.feather
ADA_USDT-1h.feather
ADA_USDT-1m.feather
ADA_USDT-5m.feather
ADX_USDT-15m.feather
ADX_USDT-1h.feather
ADX_USDT-1m.feather
ADX_USDT-5m.feather
AERGO_USDT-15m.feather
AERGO_USDT-1h.feather
AERGO_USDT-1m.feather
AERGO_USDT-5m.feather
AEUR_USDT-15m.feather
AEUR_USDT-1h.feather
AEUR_USDT-1m.feather
AEUR_USDT-5m.feather
AEVO_USDT-15m.feather
AEVO_USDT-1h.feather
AEVO_USDT-1m.feather
AEVO_USDT-5m.feather
AGLD_USDT-15m.feather
AGLD_USDT-1h.feather
AGLD_USDT-1m.feather
AGLD_USDT-5m.feather
AI_USDT-15m.feather
AI_USDT-1h.feather
AI_USDT-1m.feather
AI_USDT-5m.feather
AKRO_USDT-15m.feather
AKRO_USDT-1h.feather
AKRO_USDT-1m.feather
AKRO_USDT-5m.feather
ALCX_USDT-15m.feather
ALCX_USDT-1h.feather
ALCX_USDT-1m.feather
ALCX_USDT-5m.feather
ALGO_USDT-15m.feather
ALGO_USDT-1h.feather
ALGO_USDT-1m.feather
ALGO_USDT-5m.feather
ALICE_USDT-15m.feather
ALICE_USDT-1h.feather
ALICE_USDT-1m.feather
ALICE_USDT-5m.feather
ALPACA_USDT-15m.feather
ALPACA_USDT-1h.feather
ALPACA_USDT-1m.feather
ALPACA_USDT-5m.feather
ALPHA_USDT-15m.feather
ALPHA_USDT-1h.feather
ALPHA_USDT-1m.feather
ALPHA_USDT-5m.feather
ALPINE_USDT-15m.feather
ALPINE_USDT-1h.feather
ALPINE_USDT-1m.feather
ALPINE_USDT-5m.feather
ALT_USDT-15m.feather
ALT_USDT-1h.feather
ALT_USDT-1m.feather
ALT_USDT-5m.feather
AMB_USDT-15m.feather
AMB_USDT-1h.feather
AMB_USDT-1m.feather
AMB_USDT-5m.feather
AMP_USDT-15m.feather
AMP_USDT-1h.feather
AMP_USDT-1m.feather
AMP_USDT-5m.feather
ANKR_USDT-15m.feather
ANKR_USDT-1h.feather
ANKR_USDT-1m.feather
ANKR_USDT-5m.feather
APE_USDT-15m.feather
APE_USDT-1h.feather
APE_USDT-1m.feather
APE_USDT-5m.feather
API3_USDT-15m.feather
API3_USDT-1h.feather
API3_USDT-1m.feather
API3_USDT-5m.feather
APT_USDT-15m.feather
APT_USDT-1h.feather
APT_USDT-1m.feather
APT_USDT-5m.feather
ARB_USDT-15m.feather
ARB_USDT-1h.feather
ARB_USDT-1m.feather
ARB_USDT-5m.feather
ARDR_USDT-15m.feather
ARDR_USDT-1h.feather
ARDR_USDT-1m.feather
ARDR_USDT-5m.feather
ARKM_USDT-15m.feather
ARKM_USDT-1h.feather
ARKM_USDT-1m.feather
ARKM_USDT-5m.feather
ARK_USDT-15m.feather
ARK_USDT-1h.feather
ARK_USDT-1m.feather
ARK_USDT-5m.feather
ARPA_USDT-15m.feather
ARPA_USDT-1h.feather
ARPA_USDT-1m.feather
ARPA_USDT-5m.feather
AR_USDT-15m.feather
AR_USDT-1h.feather
AR_USDT-1m.feather
AR_USDT-5m.feather
ASR_USDT-15m.feather
ASR_USDT-1h.feather
ASR_USDT-1m.feather
ASR_USDT-5m.feather
ASTR_USDT-15m.feather
ASTR_USDT-1h.feather
ASTR_USDT-1m.feather
ASTR_USDT-5m.feather
AST_USDT-15m.feather
AST_USDT-1h.feather
AST_USDT-1m.feather
AST_USDT-5m.feather
ATA_USDT-15m.feather
ATA_USDT-1h.feather
ATA_USDT-1m.feather
ATA_USDT-5m.feather
ATM_USDT-15m.feather
ATM_USDT-1h.feather
ATM_USDT-1m.feather
ATM_USDT-5m.feather
ATOM_USDT-15m.feather
ATOM_USDT-1h.feather
ATOM_USDT-1m.feather
ATOM_USDT-5m.feather
AUCTION_USDT-15m.feather
AUCTION_USDT-1h.feather
AUCTION_USDT-1m.feather
AUCTION_USDT-5m.feather
AUDIO_USDT-15m.feather
AUDIO_USDT-1h.feather
AUDIO_USDT-1m.feather
AUDIO_USDT-5m.feather
  </code></pre>

</details>

**Comment by xmatthias** [comment]
from previous, similar errors, the problem was an empty file (0 bytes).
while the file exists - it can't be read (uppon testing, it seems to trigger a `File is too small to be a well-formed file` error, which is slightly different from your example).


Freqtrade doesn't really do much else than to your example.

The only "obvious" difference is that freqtrade uses `Pathlib` over `os.path` - which may trigger a different code-path within pandas - though i doubt that's an actual problem.


I'm afraid that without identifying the problematic file (which i'll then need, or at least need a way to reproduce) - i'd not know what else to do with this.

**Comment by 14790897** [comment]
[INJ_USDT-1m.zip](https://github.com/user-attachments/files/17892625/INJ_USDT-1m.zip)
I found the problematic file by sorting the files from smallest to largest, and the smallest file turned out to be the problematic one.

**Comment by 14790897** [comment]
Previously, my code had too many log entries, which made it difficult for me to identify the problematic file in the logs. Now I’ve updated the code below to pinpoint the file causing the error without outputting unnecessary logs:

```python
import pandas as pd
import os

directory = r"user_data\data\binance"

for filename in os.listdir(directory):
    if filename.endswith(".feather"):
        filepath = os.path.join(directory, filename)
        try:
            df = pd.read_feather(filepath)
        except Exception as e:
            print(f"Error reading {filename}: {e}")
```
