### ISSUE TITLE
Plot with net value or unrealized profit

### ISSUE THREAD

**Issue by Hoshinaaa** [freqtrade/freqtrade#10972]
## Describe your environment
(if applicable)

  * Operating system: Centos
  * Python Version: 3.12 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*

Dear sir,
I'm using the plot function and it's really good. But i noticed one thing. So if we are doing the dry run or live run, we can see the realized profit as well as the unrealized one. But the plot-profit only shows the realized one (cumulative profit)
If it's a short term strategy, they probably won't have much difference, but a long term strategy may be quite different. 
I'm not so sure.

**Comment by xmatthias** [comment]
As the comment at the top of the [plotting](https://www.freqtrade.io/en/stable/plotting/)  documentation mentions - it's deprecated and currently in maintenance mode. That means we don't plan on removing it, but there's also no plans on adding additional functionality to de graphs created through plotly.

That said - we'll keep this in mind for freqUI.
