### ISSUE TITLE
Can freqtrade perceive price changes in real time?

### ISSUE THREAD

**Issue by YangShuai-uestc** [freqtrade/freqtrade#10975]
I have seen the doc like: 
Why can't I see "real time" candle data?[¶](https://www.freqtrade.io/en/stable/strategy-customization/#why-cant-i-see-real-time-candle-data)
Freqtrade does not store incomplete/unfinished candles in the dataframe.

The use of incomplete data for making strategy decisions is called "repainting" and you might see other platforms allow this.

Freqtrade does not. Only complete/finished candle data is available in the dataframe.

  
## Your question

I've noticed that the data in the candlestick chart is candlestick (OHLCV) data. If I choose a one-minute candlestick as a strategy indicator, but within this minute, only the opening price remains constant, while the highest price, lowest price, closing price, and trading volume may continue to change. Can freqtrade perceive these changes in real time? If not, is there any way to work around this to achieve real-time updates?

Because I have noticed that the indicators implemented in Pine language on TradingView are updated in real-time, even though the candlestick charts on TradingView are set to 1-minute intervals. I would like to implement this capability on freqtrade. How can I achieve this?

Thanks！

**Comment by xmatthias** [comment]
> Because I have noticed that the indicators implemented in Pine language on TradingView are updated in real-time,

Yes, this is called repainting, by using incomplete candles.
A sure way to get a strategy to look good on paper, and fail miserably as you'll enounter ghost signals - trades which happen with no trace that there's ever been a signal, as the indicator is no longer showing this signal once the candle actually closes

There's a [faq entry](https://www.freqtrade.io/en/stable/faq/#i-want-to-use-incomplete-candles) for this.
Freqtrade does not support this - and we don't plan to.

**Comment by YangShuai-uestc** [comment]
thanks very much!
