### ISSUE TITLE
Signal generated but no trade is placed

### ISSUE THREAD

**Issue by valek333** [freqtrade/freqtrade#10973]
Hi there, Freqtrade developers,

I've come across an interesting issue that I've never seen before. There's a signal to enter a trade, but it's not actually being executed. I've stripped out everything unnecessary from my strategy that could have influenced this, and I've also cleaned up the config file. Freqtrade is installed from scratch. The command line logs show no errors.

Could you please help me figure out what might be causing this?

Thanks!

  * Operating system: Ubuntu 22.04.4 LTS
  * Python Version: 3.10
  * Freqtrade Version: 2024.10

![Image](https://github.com/user-attachments/assets/18da5aa1-af53-4b15-aa1f-355c174d50cd)

**Comment by xmatthias** [comment]
well considering that apart from a screenshot there's no information, we'll not be able to provide you with anything other than guesses

* you've got a callback preventing entries
* all trade-slots are occupied
* there's no money left to enter
* your strategy has a lookahead bias, so the signal doesn't appear at the very last candle, but only afterwards
* the strategy loaded is not the one you're looking at (more common than you think 😆 )


For some - logs from around that time may provide hints (assuming it's a dry/live run).
for others (e.g. lookahead bias, wrong strategy) - there's not - and it's an implicitly hard problem to debug (though we have a [lookahead bias](https://www.freqtrade.io/en/stable/lookahead-analysis/) helper to help analyze this particular problem.
