### ISSUE TITLE
Multiple open trades with same pair (position stacking)

### ISSUE THREAD

**Issue by vpotap** [freqtrade/freqtrade#1099]
sometimes after pump/dump need re-buy the same pair again , now ft waits till open  trade on this pair is completed to create next one, using on binance with scalp strategy

**Comment by xmatthias** [comment]
Hi,

Having the same pair open multiple trades on the same pair is currently not supported in Freqtrade.

however, just to specify - is this something you saw happening  - or is this a feature request?

**Comment by vpotap** [comment]
i think it's future request

**Comment by xmatthias** [comment]
Going to close this in favor of #1519, which has a better description on position stacking.

**Comment by stevenn98** [comment]
Multiple open trades with same pair. Is this feature available or not yet?

**Comment by xmatthias** [comment]
it's not (and probably never will be) - but you can [adjust trade position size](https://www.freqtrade.io/en/latest/strategy-callbacks/#adjust-trade-position) - which results in effectively the same endresult.
