### ISSUE TITLE
Change the behavior of missing leverage tiers in backtesting from an error to a warning

### ISSUE THREAD

**Issue by 14790897** [freqtrade/freqtrade#10999]
## Describe your environment

  * Operating system: _windows___
  * Python Version: __Python 3.10.11___ (`python -V`)
  * CCXT version: __4.4.26___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _freqtrade 2024.10___ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

Current Behavior:
When certain trading pairs (e.g., PNUT/USDT, AKT/USDT, GRASS/USDT, ACT/USDT) are missing leverage tier information during backtesting, Freqtrade raises an ERROR and terminates the backtesting process:
```
2024-11-27 11:53:44,074 - freqtrade - ERROR - Pairs PNUT/USDT:USDT, AKT/USDT:USDT, GRASS/USDT:USDT, ACT/USDT:USDT got no leverage tiers available. It is therefore impossible to backtest with this pair at the moment.
```
However, these pairs can be used successfully in live trading. This discrepancy creates inconvenience as users must manually exclude such pairs from the configuration to continue backtesting.

Proposed Enhancement:
Change this ERROR to a WARNING and allow backtesting to continue by skipping the affected pairs. 
https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/optimize/backtesting.py#L374

**Comment by xmatthias** [comment]
Not having leverage tiers means the bot can't determine max leverage (amongst other things) - so while it might mean that you can use these pairs - they'd be limited to no leverage, calculate liquidation prices wrongly or fail at it, ...

While you can use these pairs for live - you couldn't use them for dry-run either if they're not in the leverage tier file - so i think it's more consistent this way, anyway.

As such, it wouldn't improve behavior - but increase discrepancy without the user noticing (from experience we can tell - nobody reads logs unless something fails - so having this a failure is intended, and we have no intend to change this.

---

I also don't really see this as a problem.

For all exchanges except binance, freqtrade refreshes leverage tiers automatically - either all the time, or in a cached manner for performance reason (you can delete the file from `user_data/<exchange>/futures/leverage_tiers_<COIN>.json` to force a refresh).

For Binance, leverage tiers require authentication - hence we refresh the data once a week (on develop).
If that's not sufficient for you, best use the [documented binance leverage tier update process](https://www.freqtrade.io/en/stable/developer/#update-binance-cached-leverage-tiers) manually (depending on your installation method, you may need to change the path around slightly - it should go alongside the `binance.py` file).
