### ISSUE TITLE
Bot opens new trade before previous trade funds are fully available

### ISSUE THREAD

**Issue by 14790897** [freqtrade/freqtrade#10994]
## Describe your environment

 * Operating system: linux
  * Python Version: Python 3.12.7
  * CCXT version: ccxt==4.4.24
  * Freqtrade Version: freqtrade 2024.10
  

## Describe the problem:

When a trade is closed and a new signal is generated immediately, the bot attempts to open the new trade before the funds from the previous trade are fully settled. This results in the bot using only the remaining wallet balance (extra funds). My strategy relies on using the entire wallet balance for every trade.
In the following example, the new trade only used a very small amount:

<img src="https://github.com/user-attachments/assets/b41de5ad-5149-45b6-a188-500953a8a7e9" alt="Image" width="300">

### Steps to reproduce:
Here is my config file:
```
"max_open_trades": 1,
  "stake_currency": "USDT",
  "stake_amount": "unlimited",
  "tradable_balance_ratio": 0.99,
  "amend_last_stake_amount": true,
```
  
### Observed Results:
  
  * What did you expect to happen?
Wait for the funds from the closed trade to fully settle and become available in the wallet before executing the new trade.

**Comment by xmatthias** [comment]
"stable" is a moving target from a version perspective - if we release a new version today - would that automatically mean that you're seeing it with that version, too? ;) there's a reason we provide a command to run to get the **actual** version of the bot.
Thanks.


---


let's start with logs, shall we? 
telegram Messages don't really paint a good picture (like - not at all).

**Comment by 14790897** [comment]
<details>
<summary>Expand full </summary>
  <pre><code>
freqtrade  | 2024-11-26 01:05:06,348 - freqtrade.freqtradebot - INFO - Exit for PNUT/USDT detected. Reason: exit_signal Tag: exit_signal
freqtrade  | 2024-11-26 01:05:06,350 - freqtrade.freqtradebot - INFO - Cancelling stoploss on exchange for Trade(id=79, pair=PNUT/USDT, amount=1575.20000000, is_short=False, leverage=1.0, open_rate=1.23139774, open_since=2024-11-25 11:55:06) order: 309242891
freqtrade  | 2024-11-26 01:05:06,865 - freqtrade.wallets - INFO - Wallets synced.
freqtrade  | 2024-11-26 01:05:06,865 - freqtrade.freqtradebot - WARNING - Unable to exit trade PNUT/USDT: Not enough amount to exit trade. Trade-amount: 1575.2, Wallet: 0.09208
freqtrade  | 2024-11-26 01:05:07,197 - freqtrade.exchange.exchange - INFO - stoploss limit order added for PNUT/USDT. stop price: 0.6157. limit: 0.6096
freqtrade  | 2024-11-26 01:05:07,415 - freqtrade.freqtradebot - INFO - Exit for PNUT/USDT detected. Reason: exit_signal Tag: exit_signal
freqtrade  | 2024-11-26 01:05:07,416 - freqtrade.freqtradebot - INFO - Cancelling stoploss on exchange for Trade(id=79, pair=PNUT/USDT, amount=1575.20000000, is_short=False, leverage=1.0, open_rate=1.23139774, open_since=2024-11-25 11:55:06) order: 318785340
freqtrade  | 2024-11-26 01:05:07,782 - freqtrade.wallets - INFO - Wallets synced.
freqtrade  | 2024-11-26 01:05:07,862 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 79, 'exchange': 'Binance', 'pair': 'PNUT/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'loss', 'limit': 1.1743, 'order_rate': 1.1743, 'order_type': 'market', 'amount': 1575.2, 'open_rate': 1.2313977399695277, 'close_rate': 1.1743, 'current_rate': 1.1743, 'profit_amount': -92.77041979, 'profit_ratio': -0.04779156, 'buy_tag': 'buy_rsi_my_strat', 'enter_tag': 'buy_rsi_my_strat', 'exit_reason': 'exit_signal', 'open_date': datetime.datetime(2024, 11, 25, 11, 55, 6, 643926, tzinfo=datetime.timezone.utc), 'close_date': datetime.datetime(2024, 11, 26, 1, 5, 7, 862084, tzinfo=datetime.timezone.utc), 'stake_amount': 1939.6977200000001, 'stake_currency': 'USDT', 'base_currency': 'PNUT', 'quote_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0, 'final_profit_ratio': None, 'is_final_exit': False}
freqtrade  | 2024-11-26 01:05:07,862 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=79, pair=PNUT/USDT, amount=1575.20000000, is_short=False, leverage=1.0, open_rate=1.23139774, open_since=2024-11-25 11:55:06)
freqtrade  | 2024-11-26 01:05:08,861 - freqtrade.persistence.trade_model - INFO - Updating trade (id=79) ...
freqtrade  | 2024-11-26 01:05:08,862 - freqtrade.persistence.trade_model - INFO - MARKET_SELL has been fulfilled for Trade(id=79, pair=PNUT/USDT, amount=1575.20000000, is_short=False, leverage=1.0, open_rate=1.23139774, open_since=2024-11-25 11:55:06).
freqtrade  | 2024-11-26 01:05:08,863 - freqtrade.persistence.trade_model - INFO - Marking Trade(id=79, pair=PNUT/USDT, amount=1575.20000000, is_short=False, leverage=1.0, open_rate=1.23139774, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.
freqtrade  | 2024-11-26 01:05:09,073 - freqtrade.wallets - INFO - Wallets synced.
freqtrade  | 2024-11-26 01:05:09,076 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit_fill, 'trade_id': 79, 'exchange': 'Binance', 'pair': 'PNUT/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'loss', 'limit': 1.174339563230066, 'order_rate': 1.174339563230066, 'order_type': 'market', 'amount': 1575.2, 'open_rate': 1.2313977399695277, 'close_rate': 1.174339563230066, 'current_rate': None, 'profit_amount': -92.71245285, 'profit_ratio': -0.0477617, 'buy_tag': 'buy_rsi_my_strat', 'enter_tag': 'buy_rsi_my_strat', 'exit_reason': 'exit_signal', 'open_date': datetime.datetime(2024, 11, 25, 11, 55, 6, 643926, tzinfo=datetime.timezone.utc), 'close_date': datetime.datetime(2024, 11, 26, 1, 5, 7, 824000, tzinfo=datetime.timezone.utc), 'stake_amount': 1939.6977200000001, 'stake_currency': 'USDT', 'base_currency': 'PNUT', 'quote_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': -92.71245285, 'final_profit_ratio': -0.0477617020367261, 'is_final_exit': True}
freqtrade  | 2024-11-26 01:05:09,273 - freqtrade.wallets - INFO - Wallets synced.
freqtrade  | 2024-11-26 01:05:09,479 - freqtrade.wallets - INFO - Wallets synced.
freqtrade  | 2024-11-26 01:05:09,560 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for SAND/USDT with stake_amount: 19.1691894141 ...
freqtrade  | 2024-11-26 01:05:09,771 - freqtrade.freqtradebot - INFO - Order 3396406865 was created for SAND/USDT and status is closed.freqtrade  | 2024-11-26 01:05:09,869 - freqtrade.wallets - INFO - Wallets synced.
freqtrade  | 2024-11-26 01:05:09,871 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 80, 'type': entry, 'buy_tag': 'buy_rsi_my_strat', 'enter_tag': 'buy_rsi_my_strat', 'exchange': 'Binance', 'pair': 'SAND/USDT', 'leverage': 1.0, 'direction': 'Long', 'limit': 0.6696, 'open_rate': 0.6696, 'order_type': 'market', 'stake_amount': 18.7488, 'stake_currency': 'USDT', 'base_currency': 'SAND', 'quote_currency': 'USDT', 'fiat_currency': 'USD', 'amount': 28.0, 'open_date': datetime.datetime(2024, 11, 26, 1, 5, 9, 771309, tzinfo=datetime.timezone.utc), 'current_rate': 0.6695, 'sub_trade': False}
freqtrade  | 2024-11-26 01:05:09,872 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=80, pair=SAND/USDT, amount=28.00000000, is_short=False, leverage=1.0, open_rate=0.66960000, open_since=2024-11-26 01:05:09)
freqtrade  | 2024-11-26 01:05:09,955 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=80, pair=SAND/USDT, amount=28.00000000, is_short=False, leverage=1.0, open_rate=0.66960000, open_since=2024-11-26 01:05:09) [buy]: 2.199e-05 BNB - rate: 0.00075191
freqtrade  | 2024-11-26 01:05:09,956 - freqtrade.persistence.trade_model - INFO - Updating trade (id=80) ...
freqtrade  | 2024-11-26 01:05:09,956 - freqtrade.persistence.trade_model - INFO - MARKET_BUY has been fulfilled for Trade(id=80, pair=SAND/USDT, amount=28.00000000, is_short=False, leverage=1.0, open_rate=0.66960000, open_since=2024-11-26 01:05:09).
freqtrade  | 2024-11-26 01:05:10,168 - freqtrade.wallets - INFO - Wallets synced.
freqtrade  | 2024-11-26 01:05:10,171 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 80, 'type': entry_fill, 'buy_tag': 'buy_rsi_my_strat', 'enter_tag': 'buy_rsi_my_strat', 'exchange': 'Binance', 'pair': 'SAND/USDT', 'leverage': 1.0, 'direction': 'Long', 'limit': 0.6696, 'open_rate': 0.6696, 'order_type': 'market', 'stake_amount': 18.7488, 'stake_currency': 'USDT', 'base_currency': 'SAND', 'quote_currency': 'USDT', 'fiat_currency': 'USD', 'amount': 28.0, 'open_date': datetime.datetime(2024, 11, 26, 1, 5, 9, 771309, tzinfo=datetime.timezone.utc), 'current_rate': 0.6695, 'sub_trade': False}
freqtrade  | 2024-11-26 01:05:10,171 - freqtrade.rpc.telegram - INFO - Notification 'entry_fill' not sent.
freqtrade  | 2024-11-26 01:05:12,344 - freqtrade.exchange.exchange - INFO - stoploss limit order added for SAND/USDT. stop price: 0.3348. limit: 0.3315

  </code></pre>

</details>

**Comment by xmatthias** [comment]
From a bot perspective - `MARKET_SELL has been fulfilled for ` - or `Sending rpc message: {'type': exit_fill, ` concludes a sell.
Wallets are updated after that correctly (twice - i assume once after the close, and as part of the new entry).

Assuming you're not implementing the custom_stake callback - then the reason the bot would enter with a smaller stake is that the exchange didn't report the filled order as part of the "fetch_balance" call.
(Especially during peak times, we've seen delays in responses again and again - also / especially from binance)

To confirm this - please enable `"log_responses" : true` in the `exchange` section of your configuration and provide us with the logs once/should the problem repeat.
(please make sure to use the very latest develop branch for this (must include the linked commit)  - as I've only just added logging of `fetch_balance` responses .


---

working with that assumption (exchange reports the balance wrongly after the order filled) for now - i don't see freqtrade as responsible for checking if "is this the full balance I'd expect" - as there is really no such expectation. 

There can be several reasons for reduced balance in live - like you withdrew something or whatever.

If your strategy relies on that - you're best off checking this in `confirm_trade_entry` - though you'll need to be careful HOW that's checked.
Assuming you start with a balance of 1000$ - you can't check "stake> 1000" - you lose the first trade, and the bot would be blocking your bot from entering any successive trade.

**Comment by 14790897** [comment]
ok,   I will enable "log_responses": true in the exchange section
I’d also like to clarify that during the bot's operation, I did not perform any manual operations on the funds, such as withdrawals or external transfers.

**Comment by xmatthias** [comment]
obviously, feel free to reopen should it happen again, so we can have a look through the logs.

> I’d also like to clarify that during the bot's operation, I did not perform any manual operations on the funds, such as withdrawals or external transfers.

I didn't imply this (not at all) - sorry if it came across this way.
That part was meant as an explanation as to why freqtrade cannot reliably check for this - as freqtrade can't have the expectation "this is my money - if it's not there, the exchange forgot to update" ;)

**Comment by mahmoudeA** [comment]
"max_open_trades": 1,
  "stake_currency": "USDT",
  "stake_amount": "unlimited",
  "tradable_balance_ratio": 0.99,
  "amend_last_stake_amount": true,
