### ISSUE TITLE
Download all pairs, no matches found: .*/USDT

### ISSUE THREAD

**Issue by Hoshinaaa** [freqtrade/freqtrade#10996]
## Describe your environment

  * Operating system: _Macos_Ventura 13.3.1 M1, using docker
  * Python Version: __3.12___ (`python -V`)
  * CCXT version: ___4.4.24__ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _2024.10__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

I tried to download all pairs data from 20240101 till today, but it returns "no matches found: .*/USDT"

```
(base) hxm@HXMdeMacBook-Pro ft_userdata % docker compose run --rm freqtrade download-data --exchange binance --trading-mode spot --pairs .*/USDT --timerange 20240101-20241117 --timeframes  15m
zsh: no matches found: .*/USDT

(base) hxm@HXMdeMacBook-Pro ft_userdata % docker compose run --rm freqtrade download-data --exchange binance --trading-mode spot --pairs .*/USDT <...> --timerange 20240101-20241117 --timeframes  15m
zsh: no matches found: .*/USDT
```

And I copied the code from the doc
```
(base) hxm@HXMdeMacBook-Pro ft_userdata % docker compose run --rm  freqtrade download-data --exchange binance --pairs .*/USDT
zsh: no matches found: .*/USDT
```
I know this might be a stupid question but I stuck here for a while and i didn't find a solution.(If pair is specified it worked well, like BTC/USDT etc.)

**Comment by froggleston** [comment]
This is most likely due to zsh expanding the `.*` glob in the shell before the command runs. A quick way around it would be to supply a config file or pairlist file as per the doc, rather than using the command line `--pairs` argument.

I don't have access to a Mac, but you might also want to try `--pairs ".*/USDT"` to try and avoid the shell expansion of the wildcard?

**Comment by xmatthias** [comment]
Well the fact that it's zsh that's answering, not the bot makes this a pretty clear "zsh" problem.

quoting should work though - if it doesn't work with double quotes, try single quotes.
