### ISSUE TITLE
Lead Trading account - Binance

### ISSUE THREAD

**Issue by aleeepp** [freqtrade/freqtrade#10991]
Hello, the project is great, I have been following it for several years!!!

I would like to use freqtrade so that instead of the binance spot account , we can operate the account called "Lead Trading account" (this account is the one that allows you to offer your trades to make copy trades)

Do you think it is possible?

thank you!

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Well quite honestly - i have no clue.

based on the binance docs for [spot](https://www.binance.com/en/support/faq/how-to-create-an-api-key-for-a-futures-lead-trading-portfolio-2bec848b904b422197ce121d0925f20b)  and [futures](https://www.binance.com/en/support/faq/how-to-create-an-api-key-for-a-futures-lead-trading-portfolio-2bec848b904b422197ce121d0925f20b) lead trading - this _sounds_ to be as simple as "create an api key from a specific page".

If that's true and as simple as that - no clue - feel free to report back if it works or not :) 
You should see "pretty" soon (at least initially) if the bot sees the copy-account balance, or not.

**Comment by stash86** [comment]
I have been using copy trading for a while, and as matthias said, you just need to create API for the copy trading account. That's all

**Comment by aleeepp** [comment]
perfect thank you very much!! I knew that Binance had it enabled for futures but only now for spot, which is where I operate, so great!!

**Comment by aleeepp** [comment]
@stash86 just out of curiosity, do you have followers on your binance copy account? (for motivation)
