### ISSUE TITLE
Complete open trades without creating new

### ISSUE THREAD

**Issue by vpotap** [freqtrade/freqtrade#1100]
is it possible to complete currently open trades (without using /forcesell only in standard way with strategy)  without creating new trades , for a example i'm testing some settings i want ft to complete  old trades then i make some configuration changes and re-run ft with new config ?

**Comment by xmatthias** [comment]
you can change the `max_open_trades` to 0 and restart the bot (without changing something else) 

this will gracefully handle all trades (sell them according to the strategy), but may take a while depending on the positions and strategy and ROI and market situation.

Once all trades are sold, change whatever else - change `max_open_trades` back to what it was - and it will buy again.
