### ISSUE TITLE
Is it possible to show exits in telegram？

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#11004]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.10.12
  * CCXT version: 4.3.88
  * Freqtrade Version: 2024.8
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

In telegram the following message is now displayed:

```
/status table

ID L/S    Pair            Since       Profit (USD)      # Entries
--------  --------------  ----------  --------------  -----------
1 L 5x    PNUT/USDT:USDT  50 min ago  -5.67% (-3.37)            1
```

May I ask if it is possible to add the display of Exits here in Entries, for example:

```
Entries/Exits
1/0
```
This is helpful for grid trading strategies.

Thank you!

**Comment by xmatthias** [comment]
The message for telegram is already too wide - so while we could add it, it'd be at the expense of removing something else.

Please use `/status` - this will show individual messages per trade - which does already include both entries and exits.
