### ISSUE TITLE
recalc_trade_from_orders breaks custom stoploss

### ISSUE THREAD

**Issue by zihaom** [freqtrade/freqtrade#11002]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

LocalTrade/recalc_trade_from_orders: we can see that it uses adjust_stop_loss. I can see other cases where  adjust_stop_loss is being used directly. My question is that if custom stoploss is used by strategy, wouldnt these cases give the wrong stoploss?

Say that my stoploss is to find the new pct that gets the old abs_stoploss. Wouldnt this update the stoploss by mistake?

**Comment by xmatthias** [comment]
`custom_stoploss()` returns the relative stoploss value, which is then stored as `stop_loss_pct` (as well as calculating the absolute price).
`adjust_stop_loss()` will not update stop_loss_pct - so the value you returned will remain as is.

As `open_rate` may change (see calculation example of [adjust_position](https://www.freqtrade.io/en/stable/strategy-callbacks/#position-adjust-calculations) as to why this happens) - stoploss is "re-placed" based on the new entry rate. 
As stoploss can only ever move closer (at least the way it's called there) - that's however not going to change the offset of the stoploss.

this ensures that your 5% risk tolerance remains at 5% - even though the order you entered at 100$ now has an entry rate of 105$ - as you did a position adjustment at a higher rate. Your stoploss still defines a max risk of 5%.

Now if the position size didn't change - then `open_rate` won't change either - leaving the stoploss as is anyway.
if your position size changed however, the stoploss must be re-calculated as your risk is now different.

If you need new logic for the new position size, then you can control the (new) stoploss in the callback (there's [a parameter](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-stoploss-after-position-adjustments) that's only set when an order fills and allows for almost random adjustments to the stoploss both closer AND further away from the order) if that's what your after.


Relying on "abs_stoploss" is not something I'd recommend anyway - as it's not something that's assumed to be "95 and leave it there" - not if you're using custom_stoploss.
`custom_stoploss` behaves like a trailing stop - so (unless you explicitly bail with None) - it'll trail the stoploss at the % you return.

**Comment by zihaom** [comment]
Thanks for the reply! 
I am currently working on a feature that would set the stoploss on a value not a pct. Currently I am just recalculating the stoploss pct in custom_stoploss() to match the old abs_stoploss. Any suggestions? @xmatthias

**Comment by zihaom** [comment]
Here is my code anyways 
``` python
def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, after_fill: bool, 
                        **kwargs) -> Optional[float]:        
        if after_fill: 
            # find out whether the last order is a reduce postion made by trader
            last_order = trade.orders[-1]
            if last_order.ft_order_side == "stoploss":
                last_order = trade.orders[-2]
            if last_order.ft_order_side != trade.entry_side:
                # calculates the new stoploss so that abs_stoploss remains the same
                last_abs_stoploss = trade.stop_loss
                if trade.is_short:
                    new_stoploss = float((current_rate - last_abs_stoploss)/current_rate * trade.leverage)
                else:
                    new_stoploss = float((last_abs_stoploss - current_rate)/current_rate * trade.leverage)
                logger.error("new_stoploss: " + str(new_stoploss))
                logger.error("current_rate: " + str(current_rate))
                logger.error("last_abs_stoploss: " + str(last_abs_stoploss))
                if trade.is_short:
                    new_abs_stoploss = float(current_rate * (1 + abs(new_stoploss / trade.leverage)))
                else:
                    new_abs_stoploss = float(current_rate * (1 - abs(new_stoploss / trade.leverage)))
                logger.error("new_abs_stoploss: " + str(new_abs_stoploss))
                new_stoploss = price_to_precision(new_stoploss, trade.price_precision, trade.precision_mode,
                                            rounding_mode=ROUND_DOWN if trade.is_short else ROUND_UP)
                return new_stoploss
            return self.config["newtrades_stoploss"]
```

**Comment by xmatthias** [comment]
well you're acting only  after partial exits.

partial exits won't change the average entry rate - so unless you aim to place a new stoploss at a different rate - i don't see why you'd need to re-set the rate at all.

As an aside - your code is wrong - like - totally.
the [docs](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stoploss) pretty clearly mention the following

> The method must return a stoploss value (float / number) as a percentage of the current price. 

Your code uses an absolute stoploss - rounds it to precision - and then returns it - which is absolutely not what the function expects.

this MAY accidentally work for assets that are placed around the 1$ mark (or below) - but will place a stop at ~3000% below current rate for ETH.

**Comment by zihaom** [comment]
Lol, thanks again for the reply. I believe that you thought I returned new_abs_stoploss . new_abs_stoploss  is just calculated for debug. new_stoploss is intended to be a reverse of the calculation of abs_stoploss in adjust_stop_loss. Please point out if I ve made a mistake!

**Comment by zihaom** [comment]
Lol, thanks again for the reply. I believe that you thought I returned new_abs_stoploss . new_abs_stoploss  is just calculated for debug. new_stoploss is intended to be a reverse of the calculation of abs_stoploss in adjust_stop_loss. Please point out if I ve made a mistake!

**Comment by zihaom** [comment]
And yes, I do want to place another stoploss(pct) base on the current rate so that I can keep the stoploss_abs the same.

**Comment by xmatthias** [comment]
That makes the problem of rounding worse 😆 
you're now rounding a percentage to a price precision.

if you're unlucky - this can mean to 0 decimals (BTC - which on some exchanges does no longer allow `.1` increments) - which essentially would be no stoploss (or 1 - depending if you're rounding up or down).

**Comment by zihaom** [comment]
Thanks man for point that out😆
Any suggestion on how I can implementing on such a feature? I m planning on meddling with the ft db and record the abs stoploss we need.

**Comment by xmatthias** [comment]
not really - as i absolutely don't understand what you're after - and i also don't really care, either, if i'm honest.

Storing random data attached to a trade is [easily possible](https://www.freqtrade.io/en/stable/strategy-advanced/#storing-information-persistent) - i don't quite understand what you're after though
if you're after "place a stoploss at 95$ and be done with it - use the [available helpers](https://www.freqtrade.io/en/stable/strategy-callbacks/#stoploss-percentage-from-absolute-price) on entry.

I'll however neither code your logic for you - nor is it important for me to understand your exact logic :)

**Comment by zihaom** [comment]
That is actually helpful. Thanks!
