### ISSUE TITLE
Wrong timeframe when plotting backtest results

### ISSUE THREAD

**Issue by szwagros** [freqtrade/freqtrade#11009]
* Operating system: Linux
  * Python Version: Python 3.12.7
  * CCXT version: 4.4.26
  * Freqtrade Version: freqtrade 2024.11-dev
  

When running backtest on different timeframe than specified in strategy class and then plotting results strategy is "run" on class hardcoded timeframe not on timeframe specified during backtesting. It happens during call to ap1/v1/pair_history. Candle data is loaded at correct timeframe from request parameter but config "timeframe" is not override so later call to:

df_analyzed = strategy.analyze_ticker(_data[pair], {"pair": pair}) in  _rpc_analysed_history_full "runs" strategy od "default" timeframe.

To reproduce:

  1. Add print(self.timeframe) to populate_indicators method
  2. run backtest - checklogs - it shows timeframe selected during backtesting
  3. visualize results - checklogs it show timeframe specified in strategy class
  
It also breaks functionality of merge_informative_pair when plotting results because it is trying to merge dataframes based on timeframe from strategy not from backtest but candle data is loaded properly (on timeframe from backtest).  

I've fixed this locally by overriding timeframe setting in config during api call:

diff --git a/freqtrade/rpc/api_server/api_v1.py b/freqtrade/rpc/api_server/api_v1.py
index 5722ad157..38b431adc 100644
--- a/freqtrade/rpc/api_server/api_v1.py
+++ b/freqtrade/rpc/api_server/api_v1.py
@@ -379,6 +379,7 @@ def pair_history_filtered(
         {
             "strategy": payload.strategy,
             "timerange": payload.timerange,
+            "timeframe": payload.timeframe,
             "freqaimodel": (
                 payload.freqaimodel if payload.freqaimodel else config.get("freqaimodel")
             ),

**Comment by xmatthias** [comment]
Nice spot - though this wasn't the only instance where this could've happend (at least in theory).

will be fixed soon.
