### ISSUE TITLE
Use same data with multiple bots

### ISSUE THREAD

**Issue by Mo7mud** [freqtrade/freqtrade#11012]
* Operating system: Kubuntu
  * Python Version: 3.12.3 (`python -V`)
  * CCXT version: 4.3.68
  *   * Freqtrade Version: 2024.8-dev
  
## Your question

I have multiple bots running on one PC and the config file is identical but the strategies are different but they use the same time frames
My question is:
Can bot 2 use the same data bot 1 used it instead of getting it again from the exchange and the same goes for the other instances?

This will reduce bandwidth consumption and lower the pressure on the network because some times there are more than 5 bots running at the same time and there is probability for more.
Thank you very much.

**Comment by stash86** [comment]
There are unofficial proxy for binance and kucoin. A quick googling should show you the proxies. For other exchanges, you would need to write one yourself. We won't support any proxy related question/issue, so if you face any issue, you need to ask the author of the proxy.

**Comment by Mo7mud** [comment]
What proxy?
You didn't understand me at all
What I mean that bot 1 downloads live data for BTC for example 
Bot 2 downloads same data for another strategy
Can bot 2 use the same already downloaded data with bot 1 instead of downloading it from the exchange?
What proxy you're talking about?
I don't need a proxy or vpn, I don't have issues connecting to exchanges.
If you need more explanation please let know

**Comment by Mo7mud** [comment]
Let me put it in another way
Can a bot access the data that another bot downloaded from an exchange?
This is in case of dry run or live run not backtesting

**Comment by stash86** [comment]
Yes I know, and we call it proxy. Go googling before you typed more and embarassed yourself

**Comment by froggleston** [comment]
@Mohammad699 we're referring to a "data proxy" rather than the "http proxy" you might already be familiar with. One example is https://github.com/nightshift2k/binance-proxy. There might be others. This will download data once, and you set your bot endpoints to the proxy, not the actual exchange.

**Comment by xmatthias** [comment]
We do however neither support these, nor do we advertise people using these.

Most are outdated by years, so if you encounter  problems, the first step will always be to disable these proxies, or search for help with the provider / author of such proxies.

**Comment by Mo7mud** [comment]
OK thank you very much.
Special thanks for Robert Davey for clarifying the meaning of proxy here
and his kind reply instead of shutting me up.

في الاثنين، ٢ ديسمبر ٢٠٢٤, ٢:٢٩ م Matthias ***@***.***> كتب:

> We do however neither support these, nor do we advertise people using
> these.
>
> Most are outdated by years, so if you encounter problems, the first step
> will always be to disable these proxies, or search for help with the
> provider / author of such proxies.
>
