### ISSUE TITLE
ccxt DDoSProtection and protection

### ISSUE THREAD

**Issue by 0jessica0** [freqtrade/freqtrade#11025]
## Describe your environment

Operating system: ____windows（no docker）
Python Version: _____3.11.9 (python -V)
CCXT version: _____4.3.98 (pip freeze | grep ccxt)
Freqtrade Version: ____2024.9 (freqtrade -V or docker compose run --rm freqtrade -V for Freqtrade running in docker)
  
## Your question
Hi there. I met two questions. I didn't find any good solution to both of them.
Question 1: I tried to backtest a strategy. Then I wanted to see the result on UI. I can see the PNL. But when cliked "Visualized result". I cannot see the Kline. The log on the terminal shows "ccxt.base.errors.DDoSProtection: binance 418 I'm a teapot {"code":-1003,"msg":"Way too much request weight used; IP banned until 1733134578159. Please use WebSocket Streams for live updates to avoid bans."}".
Similar things happen when I tried to backtest this strategy.

Quesiont 2:
I added a protection in the strategy:
    @property
    def protections(self):
        return [
            {
                "method": "StoplossGuard",
                "lookback_period_candles": 5,
                "trade_limit": 30,
                "stop_duration_candles": 3,
                "required_profit": 0.0,
                "only_per_pair": False,
                "only_per_side": False
            }
        ]

But in the dry run, when there were more than 30 loss contracts, the bot still didn't pause for 3 bars. 
![Image](https://github.com/user-attachments/assets/31b3aca1-7a8b-4750-a3ec-314ce5392bd0)

what went wrong?
Thanks

**Comment by froggleston** [comment]
Nothing went wrong - you're requesting too much data in too short a time period than the exchange allows: https://www.freqtrade.io/en/stable/exchanges/#setting-rate-limits

**Comment by 0jessica0** [comment]
> Nothing went wrong - you're requesting too much data in too short a time period than the exchange allows: https://www.freqtrade.io/en/stable/exchanges/#setting-rate-limits

I know. I saw this link. But I have already added this part in the config
"exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {
          "httpsProxy": "http://127.0.0.1:7890",
          "enableRateLimit": true
        },
    "ccxt_async_config": {
      "enableRateLimit": true,
        "rateLimit": 3100
    }
But I still got "{"code":-1003,"msg":"Way too much request weight used; IP banned until 1733134578159. Please use WebSocket Streams for live updates to avoid bans."}"
plus, I have already done this for like two months now. This is the first day showing this bug.

Any suggestiongs about question 2?
Thanks

**Comment by froggleston** [comment]
httpsProxy won't do anything. That's only if you're going through a third party firewall or web proxy - it's nothing to do with rate limits.

The rateLimit setting should work, but it does still depend on just how many requests you're actually making from the same IP address.

**Comment by 0jessica0** [comment]
> httpsProxy won't do anything. That's only if you're going through a third party firewall or web proxy - it's nothing to do with rate limits.
> 
> The rateLimit setting should work, but it does still depend on just how many requests you're actually making from the same IP address.

httpsProxy has nothing to do with this problem. I need it for another reason. But couple days ago, I didn't even add the rateLimit setting. Yet it worked perfectly.
This message shows up today. And still there after I added the ratelimite in the config

**Comment by froggleston** [comment]
Well I'm not sure what else to say other than the exchange is rate limiting you, and setting the rate limit in the config is the explicit way around this. Typically CCXT will manage this for you absolutely fine without you needing to set the rateLimit option yourself, but if you're running a few bots and downloading data/running backtests on the same IP, you'll likely get limited.

**Comment by 0jessica0** [comment]
> Well I'm not sure what else to say other than the exchange is rate limiting you, and setting the rate limit in the config is the explicit way around this. Typically CCXT will manage this for you absolutely fine without you needing to set the rateLimit option yourself, but if you're running a few bots and downloading data/running backtests on the same IP, you'll likely get limited.

Yeah, I never met this question before. I don't have another bot running. And I am not downloading data at all.
Did I write the config correctly?
What about the protections? Any ideas?

**Comment by froggleston** [comment]
Backtesting downloads data, and also connects to markets. Depending on the timerange, you might have hit limits. It's wise not to backtest and run bots on the same machine/IP address, especially if you're running a live bot.

In terms of the protections, were each of those losses actual stoplosses? And did *all 30* happen in the last 5 candles?

**Comment by 0jessica0** [comment]
> Backtesting downloads data, and also connects to markets. Depending on the timerange, you might have hit limits. It's wise not to backtest and run bots on the same machine/IP address, especially if you're running a live bot.
> 
> In terms of the protections, were each of those losses actual stoplosses? And did _all 30_ happen in the last 5 candles?

I am running a dryrun, but on a different server. I don't think we are using the same IP.
Everytime I checked, the time I got ban will move forward. I really don't know what changed. 
Those losses are triggered by custom_exit, not stoplosses. All 30 happen in the last 5 candles.

**Comment by froggleston** [comment]
custom_exit won't trigger StoplossGuard.

**Comment by 0jessica0** [comment]
> custom_exit won't trigger StoplossGuard.

Cool. Can I just change the def custom_exit to def custom_stoploss?
Will that trigger the StoplossGuard?

**Comment by froggleston** [comment]
Please do check the docs: https://www.freqtrade.io/en/stable/plugins/#stoploss-guard. The note covers the stoploss condition types that it will check.

**Comment by xmatthias** [comment]
> httpsProxy has nothing to do with this problem

I'm not sure about this.
Binance rate-limiting is based on IP's. 
If your proxy is configured to use some shared Exit (shared with others) - then it's the combined requests that will impact you.

Now backtesting / plotting in webserver mode will only make a couple of requests when it's starting (unless your strategy does so directly) - so if you're hitting it at that point, you've either got a ton of other bots running locally on your system - or the proxy is used by other people who aggressively query the API.

Now "enableRateLimit":true  does exactly nothing for you - as it's the default.
setting an explicit `rateLimit` is usually counter-productive, as binance has dynamic weight depending on the endpoint - but you're forcing it onto a specific timelimit - which may be correct for some entries, but not for others.

**Comment by 0jessica0** [comment]
> > httpsProxy has nothing to do with this problem
> 
> I'm not sure about this. Binance rate-limiting is based on IP's. If your proxy is configured to use some shared Exit (shared with others) - then it's the combined requests that will impact you.
> 
> Now backtesting / plotting in webserver mode will only make a couple of requests when it's starting (unless your strategy does so directly) - so if you're hitting it at that point, you've either got a ton of other bots running locally on your system - or the proxy is used by other people who aggressively query the API.
> 
> Now "enableRateLimit":true does exactly nothing for you - as it's the default. setting an explicit `rateLimit` is usually counter-productive, as binance has dynamic weight depending on the endpoint - but you're forcing it onto a specific timelimit - which may be correct for some entries, but not for others.

Thanks a lot. I did figure this part out. I changed proxy, and it went normal. 
Possible to DM me some place to find great strategies? Now I am stuck at find great signals.

**Comment by 0jessica0** [comment]
> Please do check the docs: https://www.freqtrade.io/en/stable/plugins/#stoploss-guard. The note covers the stoploss condition types that it will check.

cool, thanks a lot

**Comment by froggleston** [comment]
> if you're hitting it at that point, you've either got a ton of other bots running locally on your system - or the proxy is used by other people who aggressively query the API.

Good point - I didn't think about that as it was a localhost URL, but sure, that would make sense.
