### ISSUE TITLE
Get correct data from Trade.get_trades_proxy in order_filled callback

### ISSUE THREAD

**Issue by quantsirius** [freqtrade/freqtrade#11039]
* Operating system: Ubuntu 22.04
  * Python Version:Python 3.10.12
  * CCXT version: ccxt==4.3.65
  * Freqtrade Version: freqtrade 2024.7.1
  
Hi.
I want to implement **only one time calculations per** trade immediately after exiting. I have studied the documentation and decided that `order_filled` `callback` is perfect place for this. But there are some problems with it, and I want to ask for your help. There are calculations with trade history so my `order_filled` is simple for debug:

```
def order_filled(self, pair: str, trade: Trade, order: Order, 
                     current_time: datetime, **kwargs) -> None:

        if (order.side == trade.exit_side):
            print("--- Order filled section, activate by tag:", index_in_stat)
            print("Trade hist:")
            trade_hist = Trade.get_trades_proxy(is_open=False)
            print(trade_hist, "\n")
```

And my terminal output:
![Image](https://github.com/user-attachments/assets/f9fddb5d-8897-418a-a1f7-e074089fbd18)

OPEN ORDER and EXIT ORDER is simple debug output from `custom_stake_amount` and `custom_exit` `callback`.

The `order_filled` `callback ` executed immediately after the trade is completed – it is good. **But `Trade.get_trades_proxy` didn't return any data.** As you see after **first** trade EXIT there are **empty Trade history list**. After **second** is only **one trade** in list. 

Are there an error in my implementation? Or it is a correct work and at the time of the call `Trade.get_trades_proxy` there are no saved data yet?

I would be grateful for your help.

**Comment by xmatthias** [comment]
well first off - logs are text for a reason - taking a picture of it is not that reason :)

Please paste logs as text next time.

---

Well it's based the order of execution - so when `order_filled()` is called in the chain of "an order filled".

This call happens the moment the order status reports as filled.
after this call - other actions happen (e.g. replacing existing stoploss orders, update liquidation prices, eventually adjust stoploss, ...)

The trade will be committed to database after these actions - at which point it'll be available completely by explicit database calls (like the one you're making).

If you use it from the database via `get_trades_proxy()` (for a non-first order, you'd get this trade if you query correctly) - you'll be getting an old state - before the order actually filled.

Essentially, you can use `Trade.get_trades_proxy()` for every trade except the one that's being handled at that point - use the provided `trade` object for that.


Now at first glance, don't think that's wrong behavior per se - as this same assumption applies to essentially all callbacks that have a trade object (changes to it may have happened before it - though for some callbacks it's more likely than for others).

**Comment by quantsirius** [comment]
Thank you for your explanation. I think I understand how it works.

> The trade will be committed to database after these actions - at which point it'll be available completely by explicit database calls (like the one you're making).

Where is the best place to call Trade.get_trades_proxy() to get the completely filled trades? 
I think on a new candle it will definitely work, but that's not good option since I need a one-time calculation after exit trade.

**Comment by quantsirius** [comment]
For those who are interested, in the `order_filled()` `callback` I create a stack list of trades for the update, and then on a new candle, I update the trades only once from the list.

```
def order_filled(self, pair: str, trade: Trade, order: Order, 
                     current_time: datetime, **kwargs) -> None:
        """
        """
        if (order.side == trade.exit_side):
            # When trade exit add it to update list
            self.trade_list_to_update.append([trade.enter_tag, pair])
```
