### ISSUE TITLE
RemotePairList PriceFilter is not using the entire pairlist, only filtering within number_assets

### ISSUE THREAD

**Issue by hotston** [freqtrade/freqtrade#11036]
* Operating system: Windows 10
  * Python Version: Python 3.12.7
  * CCXT version: 4.4.24
  * Freqtrade Version: 2024.11

## Describe the problem:

RemotePairList `PriceFilter` is not using the entire pairlist, it is limited by the first `n` pairs within the `number_assets` value and only filters within this value, ignoring the rest of the valid pairs in the list. For example, if I set `"number_assets": 3` and `"method": "PriceFilter", "min_price": 1, "max_price": 10`, and the first 3 tokens will be outside the `1-10` range, no pairs will be included in the bot pairlist, even though the rest 17 tokens are within `1-10` range.

### Steps to reproduce:

  1. Create pairlist.json stored locally with the following values: 
```
{
    "pairs": ["FTM/USDT", "TAO/USDT", "WLD/USDT", "JUP/USDT", "UMA/USDT", "WIF/USDT"],
    "refresh_period": 120
}
```
  2. Set config file to: 
```
    "pairlists": [
        {
            "method": "RemotePairList",
            "mode": "whitelist",
            "processing_mode": "filter",
            "pairlist_url": "file:///user_data/pairlist.json",
            "number_assets": 3,
            "refresh_period": 120,
            "keep_pairlist_on_failure": false,
            "read_timeout": 20
        },
        {"method": "PriceFilter", "min_price": 1, "max_price": 10}
    ],
```
  3. Launch the bot in `dry_run` and `spot` mode.
 
### Observed Results:

  * Only two pairs `"FTM/USDT"` and `"WLD/USDT"` are added to the bot pairlist, even though  `"JUP/USDT", "UMA/USDT", "WIF/USDT"` are also within the `1-10` range. If you move any of the tokens  `"JUP/USDT", "UMA/USDT", "WIF/USDT"` higher up, within the first 3 positions (as set in `number_assets`) in the pairlist.json, then they will be included.
  * What did you expect to happen?
 I expect 3 pairs `"FTM/USDT", "WLD/USDT", "JUP/USDT"` added to the pairlist, filtering only out-of-range `"TAO/USDT"`.

### Relevant code exceptions or logs

freqtrade  | 2024-12-04 03:16:25,099 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist RemotePairList from '/freqtrade/freqtrade/plugins/pairlist/RemotePairList.py'...
freqtrade  | 2024-12-04 03:16:25,104 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PriceFilter from '/freqtrade/freqtrade/plugins/pairlist/PriceFilter.py'...
freqtrade  | 2024-12-04 03:16:25,814 - RemotePairList - INFO - Fetched Pairlist.
freqtrade  | 2024-12-04 03:16:25,815 - PriceFilter - INFO - Removed TAO/USDT from whitelist, because last price > 10.00000000
freqtrade  | 2024-12-04 03:16:25,825 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 2 pairs: ['FTM/USDT', 'WLD/USDT']

**Comment by stash86** [comment]
It's the correct behavior, because you yourself tell RemotePairlist to only give 3 pairs. That 3 pairs are the one passed to PriceFilter. PriceFilter can only work on what RemotPairlist give it. If you want more pairlist, then RemotePairlist should return more than 3

**Comment by hotston** [comment]
> It's the correct behavior, because you yourself tell RemotePairlist to only give 3 pairs. That 3 pairs are the one passed to PriceFilter. PriceFilter can only work on what RemotPairlist give it. If you want more pairlist, then RemotePairlist should return more than 3

Thanks for explaining. It doesn't make sense to me though. I want to limit the number of pairs the bot can work on at any moment, because of some heavy advanced orderlow data processing. The `pairlist.json` allows me to add a list of potential tokens to work on, and I want to filter the tokens within the specified price range, but I don't want the bot to work on more than 3 pairs at any given time because it will overload the bot. How to get around it? I cannot prepend the `RemotePairlist` with `PriceFilter` as it gives and error that `PriceFilter` has to go after `RemotePairlist`. 

This is essential and needed to set the `scale` setting correctly so that the bot can work correctly with advanced orderflow data as referenced here:  https://github.com/freqtrade/freqtrade/issues/11008#issuecomment-2509747074

To me `"number_assets": ` value is then pointless, because I can limit the number of assets in the `pairlist.json` itself. Do you know what I'm talking about? Thanks a lot in advance.

**Comment by xmatthias** [comment]
> To me "number_assets":  value is then pointless, because I can limit the number of assets in the pairlist.json itself. Do you know what I'm talking about? Thanks a lot in advance.

Yes you can - because it's a file - but on a remote pairlist (using a remote service) - you may not be able to.
It's not suitable for what you're aiming to do - but that doesn't make the setting pointless.

---

Quite honestly - it's a logic / understanding problem (not even really related to which pairlist you're using as first or second).

If the first pairlist set's "number_assets=3" - then the expectation is that after the first step of the pairlist - only 3 elements are present (you can use VolumePairlist with the same exact outcome - but that makes it easier to understand as volumepairlist has a commonly known rule for sorting).
Essentially it means - use Volumepairs - and use the top 3 (tradable) pairs by volume - and that's exactly what it does.

If these 3 pairs are filtered out by the next filter - that's not the fault of Volumepairlist. pairs 5 6 and 9 are not in the top 3 volume pairs - so it's correct that they're not passed on.


What you want to accomplish is pretty simple though - move the "only trade 3 pairs" filter to the end.

``` json
"pairlists": [
        {
            "method": "RemotePairList",
            "mode": "whitelist",
            "processing_mode": "filter",
            "pairlist_url": "file:///user_data/pairlist.json",
            "number_assets": 20, // or any number high enough to include 3 pairs after the PriceFilter
            "refresh_period": 120,
            "keep_pairlist_on_failure": false,
            "read_timeout": 20
        },
        {"method": "PriceFilter", "min_price": 1, "max_price": 10},
       {
        "method": "OffsetFilter",
        "offset": 0,
        "number_assets": 3
       }
    ],
```

**Comment by hotston** [comment]
> > To me "number_assets":  value is then pointless, because I can limit the number of assets in the pairlist.json itself. Do you know what I'm talking about? Thanks a lot in advance.
> 
> Yes you can - because it's a file - but on a remote pairlist (using a remote service) - you may not be able to. It's not suitable for what you're aiming to do - but that doesn't make the setting pointless.
> 
> Quite honestly - it's a logic / understanding problem (not even really related to which pairlist you're using as first or second).
> 
> If the first pairlist set's "number_assets=3" - then the expectation is that after the first step of the pairlist - only 3 elements are present (you can use VolumePairlist with the same exact outcome - but that makes it easier to understand as volumepairlist has a commonly known rule for sorting). Essentially it means - use Volumepairs - and use the top 3 (tradable) pairs by volume - and that's exactly what it does.
> 
> If these 3 pairs are filtered out by the next filter - that's not the fault of Volumepairlist. pairs 5 6 and 9 are not in the top 3 volume pairs - so it's correct that they're not passed on.
> 
> What you want to accomplish is pretty simple though - move the "only trade 3 pairs" filter to the end.
> 
> "pairlists": [
>         {
>             "method": "RemotePairList",
>             "mode": "whitelist",
>             "processing_mode": "filter",
>             "pairlist_url": "file:///user_data/pairlist.json",
>             "number_assets": 20, // or any number high enough to include 3 pairs after the PriceFilter
>             "refresh_period": 120,
>             "keep_pairlist_on_failure": false,
>             "read_timeout": 20
>         },
>         {"method": "PriceFilter", "min_price": 1, "max_price": 10},
>        {
>         "method": "OffsetFilter",
>         "offset": 0,
>         "number_assets": 3
>        }
>     ],

Yes, this worked like a charm. Thanks a ton!
