### ISSUE TITLE
Can't see staked coin on coinbase 

### ISSUE THREAD

**Issue by DragonBtc93** [freqtrade/freqtrade#11032]
Was trading fine then all of a sudden it couldn't see USDT. I have tried, updating, full reinstall, changing to USD, BTC pairs, new api. It can see all other coins in wallet just not the stake coin. Ran fine for 2 weeks before it did this.

**Comment by Vickynicole** [comment]
Hello @DragonBtc93  If your wallet isn't recognizing USDT, I'll have to refer you to the official support live chat with the ticket ID CON07638
Please see the link below to our dedicated support line:
[Coinbase Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by ancoredev-sudo** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Coinbase SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by froggleston** [comment]
More than likely it's due to Coinbase delisting Tether due to MiCA regulations: https://news.bitcoin.com/coinbase-to-delist-usdt-in-europe-amid-new-eu-regulations/

**Comment by DragonBtc93** [comment]
They where no help but found fix. Updated CCXT and it works
