### ISSUE TITLE
coinex futures market

### ISSUE THREAD

**Issue by Moe5M** [freqtrade/freqtrade#11037]
If possible, please add the Coinex futures market, as it is the only market that operates in my country.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

In theory, freqtrade supports every exchange ccxt supports, which would also include this exchange.

Now you're the first to ask for that (at least as far as i remember), so you're probably the first to have a look at this.
we have a rough guideline on things to check in the [contributors section of the documentation](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip).
While it's probably not complete, it should give you a good idea if the exchange will work for spot trading.

If you encounter specific problems, we're happy to assist up to a certain point - but the expectation for new exchanges is that the user interested is doing the legwork / most of the testing work - which also assumes a somewhat familiarity with python / testing/debugging things in python.

If you're new to python / development - you're almost certainly better of with one of the supported exchanges.

---

Now the above applies for spot trading.
Futures trading does always require some additional work - work we've currently not planned for coinex.

While it's unfortunate that it's the only futures market operating in your country - you're obviously free to test it for spot (and do necessary adjustments there).
This obviously assumes that you've got some development experience.

If that works, feel free to look at futures - but a known, working and tested spot is the base to even start looking at futures - which i don't see as being the case for coinex at this point.
