### ISSUE TITLE
Freqtrade limiting numba's parallelism to a single core

### ISSUE THREAD

**Issue by dnuno89** [freqtrade/freqtrade#11035]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: 3.12.7 (`python -V`)
  * CCXT version: 4.4.6 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.9
  
I have also tried with Intel's python distribution (3.12) and also on another Windows 11 computer with freqtrade 2024.8 and python 3.11.5 with identical results.
I do not use freqAI nor I have all its dependencies installed (though I have some dependencies installed for other reasons)

## Your question

I’m encountering an issue where Numba’s @njit functions with parallel=True are limited to single-core execution when running within my custom strategy in Freqtrade (both in live/dry run and backtesting or hyperopting). Outside of Freqtrade, these functions utilize multiple cores as expected. 

I’d like to understand what in the Freqtrade's threading model or execution design (e.g., joblib, thread pools, or subprocess management) might be affecting Numba’s parallelism. I extensively searched both in the documentation and in the code, but found nothing that can explain it. My best guess is somewhere in Freqtrade there is an initialization of multithreading that will not allow numba to initialize correctly.

I've tried changing numba's threading layer (tbb and omp), and set number of threads, with no change. 

Example code to test (will use all cores except when executed inside a freqtrade strategy):
```
from numba import njit, prange
import numpy as np

@njit(parallel=True)
def compute(arr):
    result = np.zeros(arr.shape)
    for i in prange(arr.shape[0]):
        result[i] = arr[i] ** 2
    return result

data = np.random.rand(1_000_000)
compute(data)
```

**Comment by xmatthias** [comment]
Unless you're using hyperopt or freqAI, we're neither using joblib (not even importing it) - nor subprocesses.

While freqtrade does use threading - we don't change base settings that i think could influence other libraries.
There's however also other libraries that use threads under the hood (telegram comes to mind, but it's not the only one) - where i don't know how it works - nor do i necessarily care unless it breaks something freqtrade depends on (numba is not among these things).

That said - we don't don't depend or use numba - so quite honestly - if it can be influenced by something (without telling you what it is) - it's a numba bug, not something we will or can support.

Your best bet is to try and eliminate all parts possible (webserver, telegram, ...).

**Comment by dnuno89** [comment]
Thanks for the answer, I'll research a bit more what's happening and will report any findings.
