### ISSUE TITLE
Exclude current pair from freqai feature df

### ISSUE THREAD

**Issue by TekpreXyz** [freqtrade/freqtrade#11033]
* Operating system: Debian 12
  * Python Version: Python 3.12.7
  * CCXT version: ccxt==4.4.33
  * Freqtrade Version: freqtrade 2024.11-dev-7ef93e92e

  
I would need to exclude the current pair from the calculation of 'feature_engineering_expand_x' 
For example if I had in the "pair_whitelist":["ETH/USDT"], and in the "include_corr_pairlist":["BTC/USDT","ETH/USDT","SOL/USDT"], I would like to train the model only on "BTC/USDT" and "SOL/USDT", excluding the main pair from all training databases, is it possible?

**Comment by robcaulk** [comment]
Hello, 

To be honest, I do not understand the question at all. I will guess at your intent.

If you want to avoid adding features based on the current pair, use metadata to filter the addition of features:

https://www.freqtrade.io/en/stable/freqai-feature-engineering/#gain-finer-control-over-feature_engineering_-functions-with-metadata

Cheers,

Rob
