### ISSUE TITLE
add coin dcx too your bot please support please

### ISSUE THREAD

**Issue by chintu4** [freqtrade/freqtrade#11048]
actually i need  support for coindcx please

**Comment by xmatthias** [comment]
coindcx doesn't seem to be supported by ccxt - hence there won't be support for it in freqtrade, either.

Feel free to give it a try once ccxt has added support (you can check `freqtrade list-exchanges` to see if something is missing) - but unless it's in ccxt - we won't even attempt to look at an exchange.
