### ISSUE TITLE
OKX Error code 60032

### ISSUE THREAD

**Issue by Anggel7x** [freqtrade/freqtrade#11044]
* Operating system: Mac Pro Sequoia 15.0.1
  * Python Version: 3.10
  

I was trying to run the market making example for the page but I always receive the message of **API doesn't exist** to all my request. I am debugging using the wrapper on python and plain API web socket connections and still got the error. On a similar thread I found that for the Rest API the correct url to make the request was **https://my.okx.com** and not **https://www.okx.com** . Now I am trying to connect to the private demo web socket and sill have the same issue. My API key is well built since I was able to get the account information from a rest request without problem. I cannot help but wonder if those urls for WSS are outdated?? 

I am using this part of the documentation [production-trading-services](https://www.okx.com/docs-v5/en/#overview-production-trading-services) to get the WSS urls for Demo plus this [websocket-login](https://www.okx.com/docs-v5/en/?shell#overview-websocket-login) example to test it out.

This is my code to test the connection on python:

```
import websocket
import hmac
import hashlib
import base64
import time
import json

# Define constants
url = "wss://wspap.okx.com:8443/ws/v5/private" #Defined in the documentation 
api_key = API_KEY
passphrase = API_PASSPHRASE
secret_key = API_KEY_SECRET 

# Generate the timestamp (in seconds)
timestamp = str(int(time.time()))

# Create the message to sign
method = "GET"
request_path = "/users/self/verify"
message = f"{timestamp}{method}{request_path}"

# Generate the HMAC SHA256 signature
signature = hmac.new(
    key=secret_key.encode('utf-8'),  # Secret key as bytes
    msg=message.encode('utf-8'),    # Concatenated string as bytes
    digestmod=hashlib.sha256        # Use SHA256
).digest()

# Perform Base64 encoding on the signature
base64_signature = base64.b64encode(signature).decode('utf-8')

# Prepare the login request payload
login_payload = {
    "op": "login",
    "args": [
        {
            "apiKey": api_key,
            "passphrase": passphrase,
            "timestamp": timestamp,
            "sign": base64_signature
        }
    ]
}

# Callback functions for WebSocket
def on_message(ws, message):
    print("Received message:", message)

def on_error(ws, error):
    print("Error occurred:", error)

def on_close(ws, close_status_code, close_msg):
    print("Connection closed:", close_status_code, close_msg)

def on_open(ws):
    print("Connection opened.")
    # Send the login payload
    ws.send(json.dumps(login_payload))

# Add the `x-simulated-trading` header required for demo connections
headers = {
    "x-simulated-trading": "1"
} 

# Create a WebSocketApp instance with headers
ws = websocket.WebSocketApp(
    url,
    header=headers,
    on_message=on_message,
    on_error=on_error,
    on_close=on_close
)

# Assign the on_open function
ws.on_open = on_open

# Run the WebSocket
ws.run_forever()
```

This is the message I got:

```
Connection opened.
Received message: {"event":"error","msg":"API key doesn't exist","code":"60032","connId":"e565de42"}
```

**Comment by xmatthias** [comment]
This is the  repository for freqtrade - a crypto trading bot.

While we support okx as an exchange - we don't support scripts that don't use freqtrade, so this is clearly the wrong support channel.
Your best bet is to search for support in the channels you've got the script from - which is either okx support directly, or some repository owned by okx.

**Comment by achuprynov** [comment]
I had the same problem with Demo API and it self-solved after 2-3 days on wspap.okx.com, but Demo API is still not exists on wseeapap.okx.com

Prod API is still not exists on wseea.okx.com, but Prod API is exists on wsaws.okx.com.

I checked only login request for websockets to /ws/v5/private

Very bad that OKX is not documented all details ((
