### ISSUE TITLE
Backtesting in past market like live market in the past

### ISSUE THREAD

**Issue by elite-trader110** [freqtrade/freqtrade#11051]
## Describe your environment
  * Operating system: ____ Ubuntu 
  * Python Version: _____ Python 3.10.12
  * CCXT version: _____ ccxt==4.4.33
  * Freqtrade Version: ____ freqtrade 2024.11-dev-5841b56f2

## Describe the enhancement

I would like to request a feature, which is that I think we could get better results from backtesting. Is it possible to simulate the backtesting process in a way that simulates real-time market conditions in the past? when testing a strategy in the past, we can feed the klines 1 by 1 (for example every 1 minute) from the kline history that simulate the real market in the past. this can make backtesting the most accurate and avoid any look ahead mistakes or assumption in strategies. the only thing is that we should run this kind of backtest faster than real market so we will gave a faster result in comparison with real time execution it means we can process 1000 backtest iteration in in 1 seconds so on.
Thanks

**Comment by xmatthias** [comment]
For a "proper" simulation, you'd need real-time orderbooks (not filled trades - but actual orderbook data) - which you'd have to collect a few times every second.
From a data perspective - that's unfeasible - at least for an open source project that aims to be easily runnable without huge infrastructure requirements.


As such - it'd still be based on 1m data - so it's not different from running backtesting with `--timeframe-detail 1m` (on binance, you can download 1s data, and use that as timeframe-detail - but expect that to be VERY slow.

For callbacks (and stop / roi / ...) - this will get you a pretty good simulation already.

---

The only thing you therefore risk lookahead mistakes is in the analysis process (`populate_*` methods) - where in reality - doing a bit of due diligence makes it not that difficult (and we've got a helper to discover [exactly this](https://www.freqtrade.io/en/stable/lookahead-analysis/)).

To run the analysis as it would run in live - you'll have to analyze dataframe once per candle - use only the latest candle.

if you however think about what this would mean:  
for a 1000 candle backtest (on 5m that's a couple of days) - you'd have to run analysis 1000 times - on each iteration, you'd have to throw away 999 candles, as only the very latest one counts.
so in total, you've analyzed `1000 * 1000` rows - for a backtest of 3 days of 5m data - which then would take hours.

I tried this (it's pretty simple to do as part of a decorator or similar) - but the performance impact makes backtesting unusable.
There's also no beneifit over the `lookahead-analysis` command - not if you run it with a large enough minimum trade count.

>  it means we can process 1000 backtest iteration in in 1 seconds so on.

This won't be archivable for an even slightly complex strategy using a couple of indicators (see calculation of "to analyze rows" above). 

It's simply not worth it - not from a development perspective - but more importantly, not from a user backtest perspective.

**Comment by elite-trader110** [comment]
Thank you matthias
