### ISSUE TITLE
APIKey does not match current environment

### ISSUE THREAD

**Issue by yanliang19920923** [freqtrade/freqtrade#11054]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*
Does freqtrade support okx’s simulated trading? When I use okx’s simulated API, I get the message APIKey does not match current environment.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Freqtrade does in general not support sandbox environment (however exchanges decide to call these).
These sandbox environments usually have very low trading volume - and are not actually suited to simulate trading environments.
the only thing they can be used for is testing if the API functionality works - which is done by developers of freqtrade - not something users need to care about.

With Freqtrade, you can simulate trades using dry-run mode - which acts against actual markets (with realistic volume and price movements) - while simulating placing trades on the exchange. As such - that mode won't require api keys.
