### ISSUE TITLE
freqtrade script install fails on Latest Ubuntu 24.10, still works fine on the last stable release 24.04

### ISSUE THREAD

**Issue by uadissa** [freqtrade/freqtrade#11050]
## Describe your environment

  * Operating system: Ubuntu 24.10. 
   * Python Version: 3.12
  * CCXT version: NA
  * Freqtrade Version: freqtrade 2024.11
  * VM Spec : DigitalOcean hosted 2x vCPU, 2GB RAM, 60 GB disk, region SYD1
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

script install ./setup.py -i fails with error below on Ubuntu 24.10

### Steps to reproduce:

  1. return setup.py
  2. install ta-lib manually and retry
  3. try script install on the last stable Ubuntu release 24.04 with same VM spec. Install was  successful!
  
### Observed Results:

  * What happened? 
  Error below and fails 

```
_Building wheels for collected packages: TA-Lib
  Building wheel for TA-Lib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for TA-Lib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-312/talib
      copying talib/__init__.py -> build/lib.linux-x86_64-cpython-312/talib
      copying talib/abstract.py -> build/lib.linux-x86_64-cpython-312/talib
      copying talib/deprecated.py -> build/lib.linux-x86_64-cpython-312/talib
      copying talib/stream.py -> build/lib.linux-x86_64-cpython-312/talib
      running build_ext
      building 'talib._ta_lib' extension
      creating build/temp.linux-x86_64-cpython-312/talib
      x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -fPIC -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/tmp/pip-build-env-4ru08r2i/overlay/lib/python3.12/site-packages/numpy/core/include -I/root/freqtrade/.venv/include -I/usr/include/python3.12 -c talib/_ta_lib.c -o build/temp.linux-x86_64-cpython-312/talib/_ta_lib.o
      In file included from /tmp/pip-build-env-4ru08r2i/overlay/lib/python3.12/site-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                       from /tmp/pip-build-env-4ru08r2i/overlay/lib/python3.12/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                       from /tmp/pip-build-env-4ru08r2i/overlay/lib/python3.12/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                       from talib/_ta_lib.c:1235:
      /tmp/pip-build-env-4ru08r2i/overlay/lib/python3.12/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
         17 | #warning "Using deprecated NumPy API, disable it with " \
            |  ^~~~~~~
      x86_64-linux-gnu-gcc: fatal error: Killed signal terminated program cc1
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for TA-Lib
Failed to build TA-Lib
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (TA-Lib)_
  ```

  * * What did you expect to happen?
Successful install

### Relevant code exceptions or logs
NA

**Comment by xmatthias** [comment]
For the moment - i can't really reproduce that.

Running the following steps (this creates an isolated docker container with the version you point out) does work fine for me.


``` bash
docker run --rm -it ubuntu:24.10
# All remaining commands run within the docker container
apt update && apt install -y curl python3 git python3-venv python3-dev build-essential
git clone https://github.com/freqtrade/freqtrade.git
cd freqtrade
./setup.sh --install
```

Output: 

```
...
Successfully installed freqtrade-2024.12.dev0 freqtrade-client-2024.11
Installing freqUI
2024-12-07 08:16:13,429 - freqtrade - INFO - freqtrade 2024.12-dev-63f8217cd
2024-12-07 08:16:13,864 - freqtrade.commands.deploy_ui - INFO - Removing UI directory content.
2024-12-07 08:16:13,865 - freqtrade.commands.deploy_ui - INFO - Downloading https://github.com/freqtrade/frequi/releases/download/1.5.0/freqUI.zip
pip install completed

----------------------------
Please use 'freqtrade new-config -c user_data/config.json' to generate a new configuration file.
----------------------------
----------------------------
Run the bot !
----------------------------
You can now use the bot by executing 'source .venv/bin/activate; freqtrade <subcommand>'.
You can see the list of available bot sub-commands by executing 'source .venv/bin/activate; freqtrade --help'.
You verify that freqtrade is installed successfully by running 'source .venv/bin/activate; freqtrade --version'.
root@3ab40dbe400b:/freqtrade# 
root@3ab40dbe400b:/freqtrade# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.10
DISTRIB_CODENAME=oracular
DISTRIB_DESCRIPTION="Ubuntu 24.10"
PRETTY_NAME="Ubuntu 24.10"
NAME="Ubuntu"
VERSION_ID="24.10"
VERSION="24.10 (Oracular Oriole)"
VERSION_CODENAME=oracular
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=oracular
LOGO=ubuntu-logo

```


This suggests that it's a problem with your environment - which is (probably) missing something, or has some conflicting system level dependency installed.

The following line from your log suggests that this could also be caused by too little memory

> `x86_64-linux-gnu-gcc: fatal error: Killed signal terminated program cc1`

This usually suggests that the system killed the process - you should probably see this after the fact in your system level logs (something along "Out of memory, killed ...") or similar. you should be able to check that with `journalctl` ...

**Comment by uadissa** [comment]
> For the moment - i can't really reproduce that.
> 
> Running the following steps (this creates an isolated docker container with the version you point out) does work fine for me.
> 
> docker run --rm -it ubuntu:24.10
> # All remaining commands run within the docker container
> apt update && apt install -y curl python3 git python3-venv python3-dev build-essential
> git clone https://github.com/freqtrade/freqtrade.git
> cd freqtrade
> ./setup.sh --install
> Output:
> 
> ```
> ...
> Successfully installed freqtrade-2024.12.dev0 freqtrade-client-2024.11
> Installing freqUI
> 2024-12-07 08:16:13,429 - freqtrade - INFO - freqtrade 2024.12-dev-63f8217cd
> 2024-12-07 08:16:13,864 - freqtrade.commands.deploy_ui - INFO - Removing UI directory content.
> 2024-12-07 08:16:13,865 - freqtrade.commands.deploy_ui - INFO - Downloading https://github.com/freqtrade/frequi/releases/download/1.5.0/freqUI.zip
> pip install completed
> 
> ----------------------------
> Please use 'freqtrade new-config -c user_data/config.json' to generate a new configuration file.
> ----------------------------
> ----------------------------
> Run the bot !
> ----------------------------
> You can now use the bot by executing 'source .venv/bin/activate; freqtrade <subcommand>'.
> You can see the list of available bot sub-commands by executing 'source .venv/bin/activate; freqtrade --help'.
> You verify that freqtrade is installed successfully by running 'source .venv/bin/activate; freqtrade --version'.
> root@3ab40dbe400b:/freqtrade# 
> root@3ab40dbe400b:/freqtrade# cat /etc/*release
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=24.10
> DISTRIB_CODENAME=oracular
> DISTRIB_DESCRIPTION="Ubuntu 24.10"
> PRETTY_NAME="Ubuntu 24.10"
> NAME="Ubuntu"
> VERSION_ID="24.10"
> VERSION="24.10 (Oracular Oriole)"
> VERSION_CODENAME=oracular
> ID=ubuntu
> ID_LIKE=debian
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> UBUNTU_CODENAME=oracular
> LOGO=ubuntu-logo
> ```
> 
> This suggests that it's a problem with your environment - which is (probably) missing something, or has some conflicting system level dependency installed.
> 
> The following line from your log suggests that this could also be caused by too little memory
> 
> > `x86_64-linux-gnu-gcc: fatal error: Killed signal terminated program cc1`
> 
> This usually suggests that the system killed the process - you should probably see this after the fact in your system level logs (something along "Out of memory, killed ...") or similar. you should be able to check that with `journalctl` ...

Thanks for your reply and checking this from your end.
I wasn’t running it on docked though. A raw install using the setup.py as per below.

https://www.freqtrade.io/en/stable/installation/#script-installation

I was able to work around it by installing freqtrade on a Ubuntu 24.04 machine. Posted mainly for the community benefit.

Following were my failed vm spec from Digital Ocean,

2 GB Memory / 60 GB Disk / SYD1 - Ubuntu 24.10(LTS) x64

Thanks again !

**Comment by xmatthias** [comment]
Well docker is not the crucial point here - but it's the simplest way to get a ubuntu 24.10 machine 😆 

2Gb is the bare minimum - if you need to compile ta-lib - it MAY no longer suffice. 
you can probably get around that by mounting a swap partition - but i don't think there's anything "actually" blocking with the new ubuntu version.
