### ISSUE TITLE
Question about integrating custom broker

### ISSUE THREAD

**Issue by jedi108** [freqtrade/freqtrade#11067]
## Describe your environment

  * Operating system: Unix/Linux
  * Python Version: 3.12
  * CCXT version: 4.4.37
  * Freqtrade Version: 2024.11
  
## Your question
# Question about integrating custom broker

## Description
I want to integrate a custom broker (non-cryptocurrency) into a project using CCXT. The broker has API support for WebSocket, gRPC, and REST.

## Current Solution
Currently, I only see one way:
1. Install freqtrade via pip
2. Copy existing exchange files in the environment directory `./venv/python3.X/site-packages/ccxt`
3. Rename them and implement connection to my broker

## Questions
1. What are alternative ways to integrate a custom broker, considering:
   - It's not a cryptocurrency broker
   - The API is used locally and won't be accepted into the main CCXT repository
   - WebSocket, gRPC, and REST support is needed

2. Is it possible to implement a solution without modifying files in the Python environment? For example:
   - Have freqtrade look for exchange configuration and implementation in the project folder
   - Use some plugin or extension mechanism

## Additional Context
- Using freqtrade with CCXT, but not mandatory to keep using both
- Broker has a full-featured API
- The ability to update freqtrade and CCXT is not critical

Would appreciate any ideas and recommendations on the architecture for such a solution.

**Comment by stash86** [comment]
Your option is to either get it added to ccxt or manually adding it to FT on your own. Do note that even if you manage to get it integrated to CCXT, we still need you to work on it on FT side of codes. We won't help you with that.

**Comment by jedi108** [comment]
> Your option is to either get it added to ccxt or manually adding it to FT on your own. Do note that even if you manage to get it integrated to CCXT, we still need you to work on it on FT side of codes. We won't help you with that.

Thanks for the response. I understand that I need to work on the integration myself.

Could you please clarify: is it possible to integrate a custom exchange/broker implementation without modifying CCXT/Freqtrade files in the Python environment (`venv`)? 

For example:
1. Keep all custom exchange implementation files in the project directory
2. Configure Freqtrade to look for exchange implementations in custom locations
3. Or use some kind of plugin system/extension mechanism

The goal is to avoid modifying installed packages in `venv` and keep custom implementation separate from the core libraries. This would make it easier to:
- Maintain the code
- Update Freqtrade/CCXT without losing custom changes
- Share the implementation with team members

Is there a recommended way to achieve this?

**Comment by stash86** [comment]
You will have to modify the source code one way or another. There is no way to "just add one file and done".

Personal opinion, it might be easier to write your own bot from scratch. If you want to modify FT to add your exchange, you will need to mimic CCXT's structure of responses, which might be easy or not depending on the difference to your exchange's responses. FT relies heavily on CCXT, so it won't be a small task to replace it.
