### ISSUE TITLE
I want to understand the principles of freqtrade. How can I debug it?

### ISSUE THREAD

**Issue by touhoufan2024** [freqtrade/freqtrade#11068]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

![Image](https://github.com/user-attachments/assets/95e42296-39e8-4322-b390-c6cdb2e6e2ba)

hello i want to debug it on vscode launch.json,  what should i do?

**Comment by xmatthias** [comment]
/Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.

We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.


Filling out the template helps reduce our workload, and we greatly appreciate that.

---

We have [documentation](https://www.freqtrade.io/en/stable/developer/#debug-configuration) on how to debug freqtrade - which is still up to date.
