### ISSUE TITLE
FT hard links wallet and base pair 

### ISSUE THREAD

**Issue by creslinux** [freqtrade/freqtrade#1107]
In any margin or futures exchange balance will more than likely be in the pair not the base currency. 

As example for BTC/USD - USD is the base currency. 
But in a margin market the wallet will be BTC

This produces an error in FT as Wallet and Base are assumed to be the same, this a false expectation in trading.

As example in bitmex, FT will not start as bitmex returns the wallet but FT is expecting only USD as the base.
```
2018-08-01 06:14:26,575 - freqtrade.exchange - WARNING - get_balance() returned exception: "Could not get USD balance due to malformed exchange response: {'BTC': {'free': 2.285, 'used': 0.0, 'total': 2.285}}"
2018-08-01 06:14:26,575 - freqtrade.exchange - WARNING - retrying get_balance() still for 2 times
```

**Comment by doftorul** [comment]
I don;t think its easy at the stage the bot is right now to go for leveraged/futures/options. Although this is something i would love as well.
There are lots of changes that need to be made basically from the config to the way the bot handles ccxt interaction with the exchanges, going thru the profit and stop loss handling.
I don;t think this was intended to work with futures.

**Comment by xmatthias** [comment]
no definitely not, but that doesn't mean we can work towards this long-term

not something we can easily implement quick - that's for sure
