### ISSUE TITLE
Unable to create trade

### ISSUE THREAD

**Issue by Zwei0521** [freqtrade/freqtrade#11071]
* Operating system: windows/Docker
  * Python Version: 3.13.0 
  * CCXT version: 4.4.35
  * Freqtrade Version: 2024.11
  
## Your question

```
2024-12-10 06:59:00,708 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for USUAL/USDT with stake_amount: 74.25 ...
2024-12-10 06:59:01,160 - freqtrade.freqtradebot - WARNING - Unable to create trade for USUAL/USDT: Could not create market buy order on market USUAL/USDT. Tried to buy amount 125.0 at rate 0.5899. Message: binance {"code":-2010,"msg":"This symbol is not permitted for this account."}
2024-12-10 06:59:05,253 - freqtrade.wallets - INFO - Wallets synced.
```
![Image](https://github.com/user-attachments/assets/1a50a0e4-ce63-42b3-b7d3-722b691d4eae)

Hi, everyone. I have a problem. My binance API had opened all permissions. But, there is get a WARNING about bianance code -2010.
Have anyone ever been this case?

**Comment by xmatthias** [comment]
`This symbol is not permitted for this account.` is pretty clear I'd say

For very new / shitty shitcoins, you have to do a "test" in the UI.
Other coins are not permitted in certain jurisdictions.

it's not a "API key permission" Problem - but a "this account ain't allowed to do" problem.
If you try to buy this coin in the UI, you'll most likely get a more comprehensive explanation for this - which is either a "acknowledge heightened risk" - or "your country has shitty regulations, so you can't buy certain coins". (both are equally likely - but depend on the actual country you're in / your account has KYC for).

**Comment by Zwei0521** [comment]
> `This symbol is not permitted for this account.` is pretty clear I'd say
> 
> For very new / shitty shitcoins, you have to do a "test" in the UI. Other coins are not permitted in certain jurisdictions.
> 
> it's not a "API key permission" Problem - but a "this account ain't allowed to do" problem. If you try to buy this coin in the UI, you'll most likely get a more comprehensive explanation for this - which is either a "acknowledge heightened risk" - or "your country has shitty regulations, so you can't buy certain coins". (both are equally likely - but depend on the actual country you're in / your account has KYC for).

thank you， i will check it as you said
