### ISSUE TITLE
Backtesting stocks and forex with freqtrade

### ISSUE THREAD

**Issue by Immortality-IMT** [freqtrade/freqtrade#11076]
* Operating system: Linux
  * * Python Version: Python 3.12.3
  * * * CCXT version: ccxt==4.4.24
  * Freqtrade Version: freqtrade 2024.11

Backtesting stocks and forex with freqtrade strategy format.

Considering if the data file format is identical to the crypto files, the same freqtrade architecture could backtest stocks or forex using the standard freqtrade strategy format. Freqtrade should not care about what it is backtesting as long as the format is compatible.

I am at the stage where I have set up two custom exchanges bypassing ccxt and working with API's to download stock and fx data to the data directory and to do then, process it to the same format required by existing freqtrade backtesting and some time away from running a test backtest.

It is backtesting only, not paper trading or live trading.

**Comment by xmatthias** [comment]
Freqtrade is a crypto trading bot - relying heavily on ccxt for exchange communications.

We don't aim to integrate exchanges directly bypassing ccxt - as the work required for that greatly exceeds the resources we have available for this (maintaining exchange communications is a full time job on it's own)
If the exchange is part of ccxt - there's a good chance that it's already working.

If it's not - it's out of scope for this project.

For stocks in particular - you'll encounter the problematic of "market open times" - which is quite important (higher activity right after market open, price gaps in market downtimes) - which freqtrade doesn't handle and would probably require significant changes.
There's no plans on adding such functionality anytime soon - so this is not something we'll be looking at.

Obviously, you're free to do this in your own fork - but it's not something we'll be providing support for, or will spend our time helping you get things working that ain't.

**Comment by Immortality-IMT** [comment]
My write-up is at https://www.imtcoin.com/kb.php?page=Add+Stocks+and+FX+to+a+default+Freqtrade

Both backtesting is working with stocks and forex. The new exchanges need work, however the backtest is successful. It bypasses ccxt altogether and all exchange actions are direct to the exchanges API.
