### ISSUE TITLE
Bot calculates my manual trades on the exchange as part of its trades

### ISSUE THREAD

**Issue by Mo7mud** [freqtrade/freqtrade#11085]
* Operating system: Ubuntu 
  * Python Version: 3.12.3
  * CCXT version: 4.4.35
  * Freqtrade Version: 2024.12-dev
  
Bot entered a trade for the pair `HIVE/USDT` but it went down a lot so I bought it on the exchange as a personal managed trade.
The bot increased his position after that but when I checked the bot now I found the trade I made on the exchange is included in trade details as the screenshot shows:

![Image](https://github.com/user-attachments/assets/ae326f1f-d0c1-4ef6-9033-59a2c33cd9b9)

Order # 3 was made by me on the exchange not through the bot at all. I used the Binance application on my phone to make this trade.

Is this behavior intended or it's a bug?
Actually I was wondering if the bot can manage trades opened by me on the exchange or not if I want it to do so.

**Comment by stash86** [comment]
It was some random bug. It shouldn't include manually traded order into the database.

**Comment by xmatthias** [comment]
The bot had a position for HIVE open - and apparently didn't find some balance at one point - causing it to re-find the trade.
Why the refind was triggered - you'll have to look in the logs (timing wise - sometime after order 3).


If that happens, then freqtrade will try to re-find all orders from the exchange that happened between "trade.open_date" and the current date.

This is mainly aimed towards "find that the user closed the trade on the exchange" - but will obviously also work in the other direction - and include all buys you take on the exchange just as well.


You can avoid this by using subaccounts (for the bot).
In general, i'd advise leaving the bot positions alone - for futures, that's a requirement, for spot - it'll kinda work as long as the coins don't overlap.

if i look at the trade - when you aim to exit your manual trade - will you really remember "i can only exit 1153 HIVE, the rest is freqtrade's trade position"? It's a too odd number to ACTUALLY remember i think.


---

Adding a completely manual trade to freqtrade is not something that's supported (nor planned, really) - but this is kinda like designed (you can trigger this refinding manually via UI "reload trade" button in the trade's action menu).
