### ISSUE TITLE
Trading bot gigadynamics 

### ISSUE THREAD

**Issue by Zeenat30** [freqtrade/freqtrade#11106]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by Zeenat30** [comment]
Need to change money management tools

**Comment by xmatthias** [comment]
Closing this due to no content.
If this is about "exchange support" - please double-check if the exchange you're looking for is in the [ccxt supported exchanges](https://docs.ccxt.com/#/Exchange-Markets).

Considering this exchange is not in that list - i assume it's not a supported one.

**Comment by Zeenat30** [comment]
Sorry my git hub was hacked by thay freak
