### ISSUE TITLE
FreqAI with AMD GPU

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#11109]
## Describe your environment

  * Operating system: Linux Mint
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.11 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Does FreqAI support AMD GPUs, as I use "FROM freqtradeorg/freqtrade:stable_freqaitorch" in my Docker file?
(Currently the host Linux system does not have any graphical card related additions)

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
FreqAI itself won't care about the type of CPU/GPU you're using.

If any - it's the model you pick that needs this support this - so if you use Catboost - catboost documentation is your way to go, if it's torch - search in torch support channels (it's probably not just "generic AMD GPU" - but "My particular GPU" that's going to be ACTUALLY relevant in this case).
You'll however still need to search for this information in "model provider" related documentation and/or support channels.

**Comment by myNextCoder** [comment]
Here is my late thank you. Thanks to your text, I see, that Freqtrade does not handle internal functionality of the ai-models, you rather link and integrate them correctly with your software solution.
