### ISSUE TITLE
Trailing stop on exchange #9662

### ISSUE THREAD

**Issue by hupq22** [freqtrade/freqtrade#11107]
Hi everyone!

I agree that implementing trailing stops directly on the exchange would be a great addition. Many platforms, including Kraken Pro, have recognized the value of this feature for enhancing trade reliability.

Implementing trailing stops at the exchange level could reduce the need for Freqtrade to make frequent API calls to adjust stop losses manually. This would not only streamline operations but also potentially minimize latency and improve execution.

What do you all think? Would this be a valuable feature for Freqtrade users?

Thanks!

**Comment by xmatthias** [comment]
There's already an existing enhancement request in #9662.

As such - closing as duplicate.
