### ISSUE TITLE
Add Support for Resuming Hyperopt from Saved Checkpoints

### ISSUE THREAD

**Issue by 14790897** [freqtrade/freqtrade#11101]
## Describe your environment
(if applicable)

Operating system: windows
Python Version: Python 3.12.7_ (python -V)
CCXT version: _4.4.35 (pip freeze | grep ccxt)
Freqtrade Version: freqtrade 2024.12-dev-6082bf7ee8 (freqtrade -V or docker compose run --rm freqtrade -V for Freqtrade running in docker)

## Describe the enhancement

Sometimes, when I run the hyperparameter optimization, the process takes a long time. I often run these optimizations overnight. However, in the morning, the optimization may still be incomplete, and I need to stop it during the day due to resource constraints.

It would be highly beneficial if Hyperopt supported the ability to save progress (e.g., intermediate results and evaluated parameters) and resume the optimization later without restarting from scratch.

**Comment by xmatthias** [comment]
We've had this functionality in the past (several years ago) - but it isn't actually beneficial, and has shown to have severe limitations - mainly in the space of which points have already been evaluated before.

There's no plans to bring this functionality back though.


Considering that hyperopt is searching for local minima in a multi-dimensional space - running a hyperopt "for a long time" / many epochs is usually way less effective than running several shorter hyperopts (eventually optimizing spaces one after the other) - as these get new random points - and have way less dimensionality - and as such - can improve the final outcome.
