### ISSUE TITLE
use of freqaimodels folder files

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#11108]
## Describe your environment

  * Operating system: Linux Mint
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.11 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I plan to put the files in the folder freqaimodels on a share, which harddrives are sightly slower. That's why I ask you, if these files (only those in this folder) are called regularly by the bot, or just once on startup and after /reload_config.
 

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
`user_data/freqaimodels` are used only when loading (startup and reload_config).

`user_data/models` on the other hand is used quite frequently by the bot - and should definitely be on quick storage.

**Comment by myNextCoder** [comment]
Good to know, I thank you. Since I roll out FreqAI for the first time, the 2nd folder "models" was not known to me. Now I will have a look at it. . .

**Comment by xmatthias** [comment]
well that 2nd folder is where the rolling, trained models are stored (that can also get bigger eventually, depending a bit on settings).
the freqaimodels one is just for the python files - which contain just the definitions.

**Comment by myNextCoder** [comment]
Ok, I see, the access to the folder models must be as fast as possible :)
