### ISSUE TITLE
Telegrambot write in subtopic

### ISSUE THREAD

**Issue by mcpolo99** [freqtrade/freqtrade#11116]
## Environment Details
Operating System: Windows 11
Python Version: 3.12.7
CCXT Version: 4.4.40
Freqtrade Version: 2024.12-dev-5b505ccf6
Problem Description
When managing a group with multiple bots, each bot operates in the same topic (thread) within a shared Telegram channel. Currently, there is no direct support for specifying a Topic ID in the telegram configuration. This limitation makes it challenging to send messages to a specific topic in a group, which is essential for organization and separation of bot messages. 

## Proposed Solution
Enhance the Telegram integration to support a Topic ID in the chat_id configuration. The proposed solution involves parsing the chat_id value to extract the base chat ID and Topic ID, then utilizing the message_thread_id parameter when sending messages.

## Example Configuration
Add support for a combined chat_id and topic_id format in the configuration file, where the Topic ID is appended to the chat_id with an underscore:

config.json
```
"telegram": {
"chat_id": "-xxxxxxxx_95"
}
```

## Implementation Details
Modify the _send_msg method in telegram.py to parse and utilize the Topic ID if present. Below is an example of the updated code:

telegram.py

````````
async def _send_msg(.......):
    # Parse topic ID from chat_id if present
    chat_id = self._config["telegram"]["chat_id"]
    topic_id = None
    if "_" in chat_id:
        base_chat_id, topic_id_str = chat_id.split("_", 1)
        chat_id = int(base_chat_id)
        try:
            topic_id = int(topic_id_str)
        except ValueError:
            logger.warning("Invalid topic ID format in chat_id: %s", topic_id_str)

    try:
        await self._app.bot.send_message(
            chat_id=chat_id,
            text=msg,
            parse_mode=parse_mode,
            reply_markup=reply_markup,
            disable_notification=disable_notification,
            message_thread_id=topic_id,  # Pass the parsed Topic ID
        )
    except NetworkError as network_err:
        logger.warning(
            "Telegram NetworkError: %s! Trying one more time.", network_err.message
        )
        await self._app.bot.send_message(
            chat_id=chat_id,
            text=msg,
            parse_mode=parse_mode,
            reply_markup=reply_markup,
            disable_notification=disable_notification,
            message_thread_id=topic_id,  # Retry with Topic ID
        )
    except TelegramError as telegram_err:
        logger.warning("TelegramError: %s! Giving up on that message.", telegram_err.message)
````````
## Benefits
**Improved Message Organization:**
Messages from different bots or functionalities can be directed to specific topics, reducing clutter and improving readability in shared Telegram groups.
**Backwards Compatibility:** 
Bots will continue to function for configurations without a _ in the chat_id, ensuring seamless adoption.

**Comment by xmatthias** [comment]
I'm ... not entirely sure how you're setting this up - so you might wan't to provide some more information on this (from a telegram side, mainly).

In a regular setup - it's one chat per telegram bot, one telegram bot per freqtrade bot.
I don't think using channels in that case makes any sense whatsoever - so i'm not sure what your setup looks like to need support for topic id.

**Comment by mcpolo99** [comment]
![Image](https://github.com/user-attachments/assets/42c3aec7-e732-450a-8a3e-bb6c28171912)

In telegram i create a group,
inside that group i do sub topics to separate "channels/bots" to keep cleaner flow for each bot. se example in picture.
So when i provide in each bot config the ID_topicid freqtrade still consider only ID, thus implementing topic identification.
the purpose is to keep the chats inside same group but still keep the chat flow cleaner for each bot

**Comment by xmatthias** [comment]
well it ain't as simple as your sample above - as that would mean that all bots listen to all channels - so one `/status` will have all bots respond in their own channel.

there's fixes for that - and adding this functionality isn't difficult (see linked PR which will close this issue).

**Comment by mcpolo99** [comment]
> well it ain't as simple as your sample above - as that would mean that all bots listen to all channels - so one `/status` will have all bots respond in their own channel.
> 
> there's fixes for that - and adding this functionality isn't difficult (see linked PR which will close this issue).

I thought it would not be as simple as i thought 😅 I am no where close to be a good developer,  and right now im trying to understand the logic behind the bot😅
