### ISSUE TITLE
threading and performance

### ISSUE THREAD

**Issue by thehoff** [freqtrade/freqtrade#11121]
* Operating system: Ubuntu 22.04 (Physical node, 28core)
  * Python Version: 3.12
  * CCXT version: ccxt==4.4.40
  * Freqtrade Version: freqtrade 2024.12-dev-32f592444
  
## Your question

Super new here and trying to get my head around this all. I have noticed something that while startup indicating threading, we dont seem to escape the single core boundry?

4 running tasks, but they max out at 100%/single core? When the process starts indicates the 56 cores/threads it see's but then locks to 16 but also does not really max the machine/cores/threads at all.

In "production" I can separate out pairs to bots and run multiple bots to eliminate any processing bottleneck? Just wondering/questioning if this is right or if I have missed a performance setting somewhere?

**TOP**
    PID USER       PRI  NI  VIRT   RES   SHR    S  CPU% MEM%   TIME+  Command                                                                                     
 192735 user     20   0 12.0G 6025M  107M R  97.3  4.7 11:35.10 .venv/bin/python3.12 ../freqtrade/.venv/bin/freqtrade ba
 192737 user     20   0 12.1G 6063M  107M R  97.3  4.7 11:35.20 .venv/bin/python3.12 ../freqtrade/.venv/bin/freqtrade ba
 200377 user     20   0 12.0G 6027M  108M R  97.3  4.7  2:21.11 .venv/bin/python3.12 ../freqtrade/.venv/bin/freqtrade ba
 201059 user     20   0 10.3G 4324M  108M R  97.3  3.4  1:44.46 .venv/bin/python3.12 ../freqtrade/.venv/bin/freqtrade ba

**Comment by stash86** [comment]
Yes, one core per bot. If you have more than one core, you can separate pairs into several bots

**Comment by xmatthias** [comment]
it's a limitation of python - and always has been.
While threading may use more cores (it's not core-bound) - it can't run more than one thread in parallel (search for "python GIL" for more information).

While there's work going on at the python level to alleviate that - i don't expect us to be utilizing this anytime soon - as it requires explicit support from all low-level modules.

Multiprocessing works differently - but the tradeoffs wouldn't work for freqtrade except for very limited usecases like hyperopt.

**Comment by thehoff** [comment]
all good! makes sense :) ill look at how I can run one bot with some dynamic pairs and then ill run a suite of them on a 1 pair config.
