### ISSUE TITLE
Custom configuration for trading pairs

### ISSUE THREAD

**Issue by vpotap** [freqtrade/freqtrade#1112]
Due to some altcoins market volatility  it's usefull for some trading pairs to have custom config (use global otherwise) - for a example to define : 1. stack_amount 2. stoploss 3.  trailing stop 4. minimal roi etc.   + possible here can also define simultaneously open trades for this pair

**Comment by xmatthias** [comment]
we currently don't support multiple open trades per pair, but we have a dedicated, open issue for this here: #1099

we also have #909, which, when fully implemented should give you points 1, 2, 3 and 4 per pair in the strategy.

For now, i would suggest to use one bot instance per configuration as a workaround.

unless i misunderstood, all points mentioned above are covered by one of the 2 other issues.
feel free to reopen if you feel that's not the case.
