### ISSUE TITLE
Drawdown information for hyperopt-list --export-csv command

### ISSUE THREAD

**Issue by andrasmining** [freqtrade/freqtrade#11136]
Hi Matthias,

### Background
I checked and did not find a similar request.

I really love the hyperopt-list --export-csv command to export hyperopt results, merge them and send per mail from my VPS. With this, I have all my results in 1 CSV file for all hyperopt runs.

This works like a charm.

### Actual request
Cherry on the cake would be if drawdown information would be available as well in the csv export file (eg. max_drawdown_account & max_drawdown_abs).

### Selfcheck result
As far as I checked, the place should be here:
`hyperopt_tools.py->export_csv_file(config: Config, results: list, csv_file: str)`

The epochs should have the information available in JSON format, so it could be added there.
But I am unsure of any issue related. Just wanted to cross-check if this could be something to add in the future (probably easy for you) or if I could do that as well as a pull request (but for that, I would need to setup everything, so it definitely will take much longer, but happy to contribute!).

Thanks for the help!

Best Regards,
Andras

**Comment by andrasmining** [comment]
Is my approach correct to change in this method:
`hyperopt_tools.py->export_csv_file(config: Config, results: list, csv_file: str)`

the 2 lists and add the drawdown info to filter from the epochs like this:

```
base_metrics = [
            "Best",
            "current_epoch",
            "results_metrics.total_trades",
            "results_metrics.profit_mean",
            "results_metrics.profit_median",
            "results_metrics.profit_total",
            "Stake currency",
            "results_metrics.profit_total_abs",
            "results_metrics.holding_avg",
            "results_metrics.trade_count_long",
            "results_metrics.trade_count_short",
            "loss",
            "is_initial_point",
            "is_best",
            "results_metrics.max_drawdown_account",
            "results_metrics.max_drawdown_abs",
        ]
```

```
base_columns = [
            "Best",
            "Epoch",
            "Trades",
            "Avg profit",
            "Median profit",
            "Total profit",
            "Stake currency",
            "Profit",
            "Avg duration",
            "Trade count long",
            "Trade count short",
            "Objective",
            "is_initial_point",
            "is_best",
            "Max drawdown %",
            "Max drawdown abs",
        ]
```

And then format and check NN values:
```
trials["Max drawdown abs"] = trials["Max drawdown abs"].apply(lambda x: f"{x:,.2f}" if not isna(x) else "")
trials["Max drawdown %"] = trials["Max drawdown %"].apply(lambda x: f"{x * perc_multi:,.2f}%" if not isna(x) else "")
```

**Comment by xmatthias** [comment]
tough to tell if your approach is correct without context of where you're adding it.
At first glance, it looks mostly okish (without running it or looking if the format makes sense) - though if you can get around the apply performance would be better.

I personally don't use csv export (there's better ways to get all the data) and i personally would probably never have added a csv export ... so if you think something is missing, best make a PR adding it.

as a side note: You shouldn't round abs drawdown to 2 decimals though - if youre on BTC stake currency (e.g. XRP/BTC) - you'll only get 0.00 with that as price is below that.

**Comment by andrasmining** [comment]
> tough to tell if your approach is correct without context of where you're adding it. At first glance, it looks mostly okish (without running it or looking if the format makes sense) - though if you can get around the apply performance would be better.

I will remove the "apply" for the absolute value, but percentage I would still need.

> I personally don't use csv export (there's better ways to get all the data) and i personally would probably never have added a csv export ... so if you think something is missing, best make a PR adding it.

I will add a PR, just testing it now.

> as a side note: You shouldn't round abs drawdown to 2 decimals though - if youre on BTC stake currency (e.g. XRP/BTC) - you'll only get 0.00 with that as price is below that.

You are right, removed the "apply" anyway for performance.

Can you please ellaborate on a "better way"? I was really happy with my csv, because reading the 500MB JSON files is not really what I wanted to stress. Or do you think its better to read the hyperopt results directly?

**Comment by xmatthias** [comment]
personally, i do analysis in jupyter notebooks.
reading the json file is not really an issue there - as i'll usually not need the "full" epoch list, but just a few.

it assumes familiarity with jupyter/python though - so lacking that, you might be better of with csv.
