### ISSUE TITLE
hyperopt-list --export-csv command stake currency taken from config instead of result file

### ISSUE THREAD

**Issue by andrasmining** [freqtrade/freqtrade#11142]
During Issue #11136 and creating pull request #11141 found the problem that stake currency is taken from the config file, although it should be taken from the hyperopt result file. Creating pullrequest for the fix.

**Comment by xmatthias** [comment]
wouldn't have needed an explicit issue for this ;) 
it's a minor fix ... it's included in the PR - mention it there and it's fine (saving both of us some work 😆 )

**Comment by andrasmining** [comment]
> wouldn't have needed an explicit issue for this ;) it's a minor fix ... it's included in the PR - mention it there and it's fine (saving both of us some work 😆 )

done
