### ISSUE TITLE
Docker Desktop - container data caching

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#11152]
## Describe your environment

  * Operating system: Linux Mint
  * Python Version: Python3 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.11 `freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

In some cases, after editing a json or py file, while the Bot is running, and then pushing "reload_config" after saving the files, Docker Desktop seems to use a cached version of the files, because my changes aren't always reflected in the Bot's new behavior. Even after deleting the container, the issue might remain the same in the new container. I have to re-start Docker Desktop to force reading from the disk, which results in stopping all bots. If you run similar test systems, knowing this problem, let me know, how you have fixed it. I will post the solution here, in case, I find it.

(Under Windows with Minicoda, I never have experienced such a case, any saved changes on any files, have immediately been used by Freqtrade after reloading the config. Therefore, I don't think, that Freqtrade itself uses cached data) 

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
I don't use docker desktop, so won't be able to help you with this. it's at any rate a docker problem 😄 

on windows - i'm using WSL2 with docker installed there. This circumvents docker desktop shenanigans, and i haven't had any such problem.

To get support for docker desktop - please use the appropriate channels from the docker
