### ISSUE TITLE
How to derive the slippage losses caused by market orders?

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#11155]
I'm currently trying to figure out why my backtesting is significantly more profitable than live and I suspect it's caused by market orders for entries and exits.

However: can I derive what losses I got by using market orders compared to using limit orders of side 'other' that were theoretically fully filled?

I have as data the database and the logs and telegram logs. I'd like a simple example of calculating that if it's possible from that data.

**Comment by xmatthias** [comment]
you can probably do so with something around the following:

```sql
select ft_pair, ft_order_side, ft_price, price, average
from orders
where order_type = 'market' and status = 'closed'
```

where `ft_price` is the "requested" price - and `price` and/or `average` is the actual price (`average` can be different from `price` if your order ain't filled in one trade - and is _probably_  the better choice - but will be empty for canceled orders).

which filters / aggregations / calculations / additional columns you aim to do / need - up to you.
you might need an order size, too - as i think slippage for a 100$ order **should**  be way lower than for a 10_000$ order 😆 

---

with backtesting - i don't think you can compare this directly - pricing is not necessarily relevant there (it won't matter if you use "this" or "other") - as backtesting will fill the order always if the price is within the candle. The only way to get a price "outside" of a candle is by using custom pricing - which are callbacks that won't be called for market orders (you don't control price, why ask you for a price if the exchange will ignore it anyway 😆 ).

so in reality - you're comparing a "orderbook price" from live with a "open" price in backtesting - if your strategy takes 10s to go through all pairs - you'll probably never get "open" rate - but you'll get something higher or lower (randomly).
