### ISSUE TITLE
Fraqtrade-Trade-Bot-Different-Pair-Error

### ISSUE THREAD

**Issue by gokce53** [freqtrade/freqtrade#11153]
Hi All,

When I run the trade bot in Freqtrade, it tries to trade pairs that are not in my code. Even if I select the pair BTC/USDT, which is in my code, it doesn't appear in the trades. I am going to share my codes and powershell screen please help :(

**The main config:**
```
{
    "$schema": "https://schema.freqtrade.io/schema.json",
    "max_open_trades": 3,
    "stake_currency": "USDT",
    "stake_amount": 45,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": false,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "gate",
        "key": "****",
        "secret": "****",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": ["BTC/USDT"],
        "pair_blacklist": []
    },
    "pairlists": [
        {
            "method": "StaticPairList",
            "allow_inactive": false,
            "pairs": ["BTC-USDT"]
        }
    ],
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "",
        "ws_token": "",
        "CORS_origins": ["***********"],
        "username": "***",
        "password": "****"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
``` 

**Strategy config:**
```
{
    "$schema": "https://schema.freqtrade.io/schema.json",
    "max_open_trades": 3,
    "stake_currency": "USDT",
    "stake_amount": 45,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": false,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "gate",
        "key": "***",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": ["BTC/USDT"],
        "pair_blacklist": []
    },
    "pairlists": [
        {
            "method": "StaticPairList",
            "allow_inactive": false,
            "pairs": ["BTC-USDT"]
        }
    ],
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "",
        "ws_token": "",
        "CORS_origins": ["******"],
        "username": "***",
        "password": "***"
    },
    "bot_name": "****",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

``` 

Why The pairs below appears in powershell ? 
![Image](https://github.com/user-attachments/assets/3757982d-9594-433d-ad03-8aa8e8682898)

**Comment by gokce53** [comment]
strategy code

```python
from freqtrade.strategy import IStrategy
from pandas import DataFrame

class *****(IStrategy):
    
    minimal_roi = {
        "0": 1  
    }
    stoploss = -0.1
    timeframe = '5m'  
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['buy'] = 0  
        
        dataframe['buy_price'] = dataframe['close'].shift(1)  
        
        dataframe.loc[dataframe['close'] <= (dataframe['buy_price'] * 0.99), 'buy'] = 1

        dataframe.loc[dataframe['close'] >= (dataframe['buy_price'] * 1.01), 'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['sell'] = 0  
        
        dataframe['buy_price'] = dataframe['close'].shift(1)  
        
        dataframe.loc[dataframe['close'] >= (dataframe['buy_price'] * 1.01), 'sell'] = 1
        
        return dataframe
```

**Comment by xmatthias** [comment]
For logs - please use text - not screenshots - that makes it a lot easier to read and look at.


The logs are however pretty clear. You've got an open order for BTC/USDT - and no further pairs in the pairlist (aligned with the configuration).
On top of that, you do however have a couple of additional trades open (BITBOARD, UXLINK, MOCA, ...) - which the bot thinks are still owned, but the wallet says they're not (suggesting you've manually sold them on exchange i suppose).

I suspect that your best bet will be to start with a fresh database - so old trades will no longer carry over.

as for your config - `"pairs": ["BTC-USDT"]` is wrong - both in location (it shouldn't be in the pairlists section) - and in the notation (pairs are BTC/USDT - never BTC-USDT).

**Comment by gokce53** [comment]
Hi matthias,

Thanks for your answer

I have never traded with bitboard, uxlink and moca before. What should I do to start with a new database.  I m new to software. Is there any option other than resetting the database? 

_as for your config - "pairs": ["BTC-USDT"] is wrong - both in location (it shouldn't be in the pairlists section) - and in the notation (pairs are BTC/USDT - never BTC-USDT)._  // **I delete it from pairs but now it says the error below**
```powershell
 Please verify the following segment of your configuration:
freqtrade  |             "allow_inactive": false,
freqtrade  |             "pairs":
```

**Comment by xmatthias** [comment]
Well that's error is a syntax error - i'd recommend using an editor with basic syntax highlighting for json files (e.g. vscode).
It'll help you by highlighting such errors.


The simplest way to reset the database is by deleting the database files - which are usually named "tradesv3.*.sqlite".
The exact name will depend on the mode (dry run or live).
you'll lose all information about open positions - so if it's a live bot - make sure to manually close out positions on exchange as freqtrade will "froget" about it.

an alternative can be to use a different database url via `--db-url`. 
best check the [documentation](https://www.freqtrade.io/en/stable/bot-usage/#how-to-use-db-url) on how to use that

**Comment by gokce53** [comment]
Hi matthias,

Thanks for all your help I have last question :) 

I downloaded the freqtrade files now I didnt know that I should download them. Do I have to download freqtrade files before I use the bot ? 
If I delete all database files, how will new database files come? 

And my last question is I cant login to my localhost
![Image](https://github.com/user-attachments/assets/077d1a27-756a-4613-95de-ea2d21b863ac)

**Comment by xmatthias** [comment]
database files are automatically created on startup.

For the API problem - the error suggests that the bot is not running - after startup, you'll need to give the bot a bit of time to finish startup.
