### ISSUE TITLE
Is it possible to add the functionality of holding both spot and futures contracts simultaneously?

### ISSUE THREAD

**Issue by bug-code** [freqtrade/freqtrade#11166]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

For example, holding both spot and short contracts simultaneously can be used for risk hedging, or to arbitrage the funding fee。

**Comment by froggleston** [comment]
No, you cannot have open inverse positions on the same pair. You would have to use two bots to do this AFAIK.
