### ISSUE TITLE
Pair definied in pair_blacklist still sell

### ISSUE THREAD

**Issue by vpotap** [freqtrade/freqtrade#1148]
Issue : when trying to exclude pair using pair_blacklist bot still sell , possible pair_blacklist only works for buy ?

**Comment by xmatthias** [comment]
yes, that is correct.

i'm not sure about the usecase here - open trades shall be closed based on strategy / settings or it can lead to a huge loss (missed stoploss, ...)

**Comment by xmatthias** [comment]
I'll close this now as the question is answered, and i think this is desired behaviour.

if you think differently feel free to either keep the discussion going, or reopen the issue.
