### ISSUE TITLE
install under aarch64 error

### ISSUE THREAD

**Issue by fachos** [freqtrade/freqtrade#1158]
hi... i dont know how to solve this... everythings fine... only ta-lib got an error... please help me...
thank you in advance....

=========== 

Running setup.py install for TA-lib ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-immo21p4/TA-lib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-gt3vgfsg-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    /tmp/pip-build-immo21p4/TA-lib/setup.py:82: UserWarning: Cannot find ta-lib library, installation may fail.
      warnings.warn('Cannot find ta-lib library, installation may fail.')
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.6
    creating build/lib.linux-aarch64-3.6/talib
    copying talib/test_stream.py -> build/lib.linux-aarch64-3.6/talib
    copying talib/abstract.py -> build/lib.linux-aarch64-3.6/talib
    copying talib/stream.py -> build/lib.linux-aarch64-3.6/talib
    copying talib/__init__.py -> build/lib.linux-aarch64-3.6/talib
    copying talib/test_data.py -> build/lib.linux-aarch64-3.6/talib
    copying talib/deprecated.py -> build/lib.linux-aarch64-3.6/talib
    copying talib/test_func.py -> build/lib.linux-aarch64-3.6/talib
    copying talib/test_abstract.py -> build/lib.linux-aarch64-3.6/talib
    running build_ext
    skipping 'talib/_ta_lib.c' Cython extension (up-to-date)
    building 'talib._ta_lib' extension
    creating build/temp.linux-aarch64-3.6
    creating build/temp.linux-aarch64-3.6/talib
    aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/pirate/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/usr/include/python3.6m -c talib/_ta_lib.c -o build/temp.linux-aarch64-3.6/talib/_ta_lib.o
    talib/_ta_lib.c:526:10: fatal error: ta-lib/ta_defs.h: No such file or directory
     #include "ta-lib/ta_defs.h"
              ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-immo21p4/TA-lib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-gt3vgfsg-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-immo21p4/TA-lib/

**Comment by xmatthias** [comment]
To install ta-lib on linux in general, you need to first install ta-lib manually (see here).

the python package pip (or setup, or `requirements.txt`) installes is only a python-wrapper around the c library, so the installation requires to first have the underlying library installed.

the commands listed [here](https://github.com/freqtrade/freqtrade/blob/develop/docs/installation.md#2-install-ta-lib) should work on any unix system.

please execute these steps, then run the above installation command again to properly install ta-lib (the python wrapper).


should you have any more problems please let us know, thanks.

**Comment by fachos** [comment]
hi xmatthias.. still have no luck, it stuck while ./configure...

------------->
root@black-pearl:/home/pirate/freqtrade# cd ta-lib
root@black-pearl:/home/pirate/freqtrade/ta-lib# sed -i "s|0.00000001|0.000000000000000001 |g" src/ta_func/ta_utility.h
root@black-pearl:/home/pirate/freqtrade/ta-lib# ./configure --prefix=/usr
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... ./config.guess: unable to guess system type

This script, last modified 2006-07-02, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess
and
  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2006-07-02

uname -m = aarch64
uname -r = 4.14.37-hypriotos-v8
uname -s = Linux
uname -v = #1 SMP PREEMPT Sun Apr 29 17:26:16 UTC 2018

/usr/bin/uname -p =
/bin/uname -X     =

hostinfo               =
/bin/universe          =
/usr/bin/arch -k       =
/bin/arch              =
/usr/bin/oslevel       =
/usr/convex/getsysinfo =

UNAME_MACHINE = aarch64
UNAME_RELEASE = 4.14.37-hypriotos-v8
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP PREEMPT Sun Apr 29 17:26:16 UTC 2018
configure: error: cannot guess build type; you must specify one
---------------->
also i try running under docker... same issue stuck with ta-lib

**Comment by fachos** [comment]
hi again... i solve the problem... due the config.sub & config.guess too old.... for future use need to replace these files inside directory of Ta-Lib... then all good to go ./configure

`wget 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD' -O config.guess` 

`wget 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' -O config.sub`

**Comment by xmatthias** [comment]
great you where able to fix the issue.

so aarch64 was not supported in the 0.4.0 release of ta-lib?

not familiar with this platform other than it's name tbh - so i would not be able to help too much anyway

**Comment by fachos** [comment]
after untar the ta-lib, theres config.guess & config.sub in the directory... these files is too old.. just replace it with new one... thank you...
