### ISSUE TITLE
Utilize multiple time frames in a single strategy

### ISSUE THREAD

**Issue by chhudson** [freqtrade/freqtrade#1166]
Hi everyone,

I did a basic search trying to answer this question and please excuse me if its already in the documentation.

Question:
Can I currently utilize multiple time frames in a single strategy? Feel free to point me to a post that might already exist.

**Comment by chhudson** [comment]
Thanks! I appreciate the link 💃 

Can you elaborate on what they are resampling the 5m candles too?

```
# resample our dataframes
dataframe_short = resample_to_interval(dataframe, self.get_ticker_indicator() * 2)
dataframe_long = resample_to_interval(dataframe, self.get_ticker_indicator() * 8)
```

I am assuming this is resampling to 10m and 40m. Is this correct?

Thanks again for the help

**Comment by xmatthias** [comment]
this depends on the ticker interval.
if if the interval is 5m - then your assumption above is correct.

please note that you can only sample in one direction (from low to high) and not from 1h to 15m intervals.

I'll close this now as i think the question is answered, if you feel differently feel free to reopen.

**Comment by ibitebyt3s** [comment]
For starters, you can also delete the columns you don't need with:

```python
dataframe = dataframe.drop(columns=['resample_30_date', 'resample_30_volume', 'resample_30_open', 'resample_30_close', 'resample_30_high', 'resample_30_low'])
```
and rename columns with
``` python
dataframe.rename(columns={'resample_30_sar': 'higher_sar'}, inplace=True)
```
