### ISSUE TITLE
How to manually install the tool on Centos 7 / Windows 10?

### ISSUE THREAD

**Issue by anhtuantt** [freqtrade/freqtrade#1169]
Hello,
This is an amazing project to research and develop a trading bot. I tried to install the bot on Centos 7 by script install.sh without success. Please help me the instructions how to manually install the trading tool on Centos 7 or Windows 10 without using docker because I'm going to deeply debug it in Eclipse/Python IDE and improve the trading strategies.

Regards,
Tuan Nguyen.

**Comment by xmatthias** [comment]
for centos - [the documentation](https://github.com/freqtrade/freqtrade/blob/develop/docs/installation.md#setup-config-and-virtual-env) using pip should work just fine. (eventually replace `pip3.6` with either `pip3` or `pip3.7` if you run a newer version.

for windows 10, first install [ta-lib according to this documentation](https://github.com/freqtrade/freqtrade/blob/develop/docs/installation.md#install-ta-lib), and then do the same steps than for centos.


``` bash
# Assuming the current directory is the cloned repository:
pip install -r requirements.txt
pip install -e .
```

**Comment by anhtuantt** [comment]
Yeah,
I tried to install on Windows 10  Python 3.6.1 and follow Windows installation in the github page, successfully ran activate.bat and installed TA-Lib from wheel, but at this line "pip install -r requirements.txt", the error was thrown:
Running setup.py install for idna-ssl ... done
Running setup.py install for toolz ... done
Running setup.py install for cytoolz ... error
building 'cytoolz.dicttoolz' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

Not sure what i was missing, please give me an advises.

Thanks,
Tuan Nguyen.

**Comment by Axel-CH** [comment]
He @anhtuantt have you tried this? https://stackoverflow.com/a/40888720

However I strongly recommend you to use freqtrade on a windows host with docker or [WSL](https://docs.microsoft.com/fr-fr/windows/wsl/about) I personnaly use the both solutions.
Trying to run freqtrade directly on Windows is really painfull but it's up to you

**Comment by anhtuantt** [comment]
Thank you for your help. Let me do it at the weekend and have a feedback at that time.

**Comment by xmatthias** [comment]
closing this as the installation (and windows caveats) are explained in the documentation now.
