### ISSUE TITLE
trailing_stop or trailing_stoploss ?

### ISSUE THREAD

**Issue by agarzon** [freqtrade/freqtrade#1178]
I just noticed the config.json example files talks about **trailing_stop**, however this is not documented in https://github.com/freqtrade/freqtrade/blob/develop/docs/configuration.md and the closest one is called **trailing_stoploss**

**Comment by xmatthias** [comment]
Great catch

`trailing_stop` is the one - documentation is wrong, sorry for that.

**Comment by agarzon** [comment]
Oh don't ever sorry :) I just found this software 10 minutes ago and I'm testing it right now (docker + linux).
