### ISSUE TITLE
TA-Lib error while installing requirements.txt in env

### ISSUE THREAD

**Issue by ustuzou** [freqtrade/freqtrade#1181]
Hi guys,
while installing requirements from the requirements.txt file in environment i am receiving error on TA-Lib as pasted at the bottom (running the following line -> ''pip3.6 install -r requirements.txt'' in the client connected to the server preinstalled with UBUNTU). 
Any clues what am I doing wrong here?

Command "/root/freqtrade/.env/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-2ul7whxd/TA-Lib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ghwgjajn/install-record.txt --single-version-externally-managed --compile --install-headers /root/freqtrade/.env/include/site/python3.6/TA-Lib" failed with error code 1 in /tmp/pip-install-2ul7whxd/TA-Lib/

**Comment by ustuzou** [comment]
even when i was installing TA-Lib from [these ](https://github.com/freqtrade/freqtrade/blob/develop/docs/installation.md#2-install-ta-lib) steps, namely the order was:
1. 'git clone <www repository>'     #copy the freqtrade files into my server
2. './setup.sh -i'      #executing setup file
3.     'apt-get install python3-venv'     #getting env
4. 'python3.6 -m venv .env' then activate and then upgrade command
5.  doing step 2 from the above steps: [these ](https://github.com/freqtrade/freqtrade/blob/develop/docs/installation.md#2-install-ta-lib) steps, 
5. AND finally running: 'pip3.6 install -r requirements.txt' -> which was giving error as in my 1st post.

any suggestions how to fix this? or suggestion about the order of inserted commands please?

**Comment by ustuzou** [comment]
Anyhow, based on my above steps: './setup.sh -i' linux script  is already installing TA-Lib so manual installation in the 5. above, is just to check if makes any difference (normally was doing without step 5.).
Each time results in error code 1 on TA-Lib ;/ argh..

**Comment by ustuzou** [comment]
Anyone¿

**Comment by xmatthias** [comment]
Hi,

According to the error, ta-lib (the c library) may have a problem of either not beeing installed, or is not "findable" by python. check if you can find folders like `/usr/include/ta-lib/`on your system.

Also - the error in the first post mentions `/tmp/pip-record-ghwgjajn/install-record.txt` - and `/tmp/pip-install-2ul7whxd/TA-Lib/` - hopefully one of these files contains some more expressive logs.
Note that these will be different for each time you try to install it.
