### ISSUE TITLE
stoploss manually configed by strategy

### ISSUE THREAD

**Issue by yaotian** [freqtrade/freqtrade#1182]
My strategy is to set lowest price of rolling(10) as the stoploss point.
How to config this in the strategy?

**Comment by mishaker** [comment]
For now you cannot. stoploss is hard coded in the strategy or in the config. but this is part of future development to set the stoploss dynamically by the strategy. 
Maybe you wanna work on it and do a PR ? :)

**Comment by yaotian** [comment]
Any example or develop doc?

**Comment by xmatthias** [comment]
we do have the contributing doc [here](https://github.com/freqtrade/freqtrade/blob/develop/CONTRIBUTING.md) - but unfortunately that's not showing you how to develop this feature - but how to properly create a PR.

If you have programming experience, maybe look at `interface.py` file (in combination with strategy) on how such a thing can be implemented (it's there for buy/sell signals at the moment).

This request is actually part of #909 - therefore i'll combine the 2 requests into one.
