### ISSUE TITLE
Max open trades ignored if multiple buys in same loop

### ISSUE THREAD

**Issue by Axel-CH** [freqtrade/freqtrade#1189]
## Step 3: Describe the problem:
If the bot have multiple buy signal on same loop the max open trades parameter will not work. The problematic code  is in the "_process" function:

            if len(trades) < self.config['max_open_trades']:
                state_changed = self.process_maybe_execute_buy()

### Steps to reproduce:

Run the bot with multiple pairs and set the max open trades parameter. Create a buy compulsive strategy. Wait for the bot to by a batch of coins.
  
### Observed Results:
The bot will buy on all buy signals even if the maximum open teades limit is reached.

### Solution
The "max_open_trades" should be checked in the "create_trade" function.

**Comment by xmatthias** [comment]
Hi,

i am not certain this is correct with the current develop version.

`create_trade` does return exit the "whitelist-loop" with the first bought coin (see below, line 407).

https://github.com/freqtrade/freqtrade/blob/4303e86e09fa902a62ca597f2a3c879c1c0f5a51/freqtrade/freqtradebot.py#L396-L407

I think with async and cached klines, it would be possible to allow multiple buys per loop - however that's not implemented at the moment - and if we do, we certainly need to make sure not to go over the specified max limit.

**Comment by xmatthias** [comment]
I'm going to close this now as I'm unable to recreate and think this was a bug in backtest (fixed in #1290), but not dry/live runs.

Feel free to reopen if you encounter this bug again.
