### ISSUE TITLE
metadata to keep info

### ISSUE THREAD

**Issue by yaotian** [freqtrade/freqtrade#1192]
Bug to:
populate_indicators(self, dataframe: DataFrame, metadata: dict) 
populate_buy_trend(self, dataframe: DataFrame, metadata: dict) 
populate_sell_trend(self, dataframe: DataFrame, metadata: dict) 

Use Case:
in strategy, if want to keep something like "second cross above" and need record cross time.
if 'cross_time' in metadata:
    metadata['cross_time'] =  metadata['cross_time']  + 1
else:
     metadata['cross_time'] =  0

Expected:
This info (like cross_time) can be kept to next interval to track.

Bug:
every time cross_time is 0

**Comment by Axel-CH** [comment]
Hi @yaotian to perform what you explained you need to create In the dataframe a new column that will store what you want. But you must proceed to multiple steps that will implie other collumn to perform the calculation. First you have to define an event related  group to specify what you mean by "second cross above" It can be second cross of:

- Rolling Time period (ex: 60 min)
- Above a specified resistance level
- And so on...

A quick example with an indicator that I've made to count the consecutive green candles number:

1. Store the raw event that you want to capture in benary form (0 or 1):
`dataframe['gc'] = (dataframe['close'] >= dataframe['open']) * 1`

2. Create a group flag to base you groups on:
`dataframe['samegcs'] = dataframe.gc.diff().ne(0).cumsum()`
In this case all consecutive green candles series have the same flag

3. You create groups of data to allow you to perform specific operation on them:
`gcgroup = dataframe.groupby(dataframe['samegcs'])`

4. Then you perform the operation that you want to create you final result:
`dataframe['gcn'] = gcgroup['gc'].transform('cumsum')`

The same logic applies for almost all custom indicators, the main advantage of such logic is that it keep you code vectorized so it won't consume a lot of CPU.

During the creation / debugging of you indicator I advise you to use Jupyter notebook to validate the logic. Then when you are familiar with the logic you create a subplot in the plot dataframe script to validate that you indicator work properly.
Regards,
Axel

**Comment by yaotian** [comment]
@Axel-CH  too complex. And it is usual use case and should not so complex. 
Still think metadata can be regarded as _Context_ to put things.
