### ISSUE TITLE
Followup to asyncio PR

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#1196]
During the asyncio PR #1101, a few points where pointed out by @jblestang (thanks!) which where not taken on during the PR as they are general improvements, not directly related to asyncio (even though the affected code segments where touched).

This issue is to keep track (and not forget) the issues pointed out:

* [x] `load_markets()` should be in `init_ccxt`, not `validate_pairs` (pr #1204 available)
* [x] `_LIMIT = 500` in `_async_get_history` should not be hardcoded (and probably increased to 1000 as that seems to be in the cache on most exchanges) (kind of solved - it's adjustable by exchange in a configuration now).
* [x] sorting of candle data (in `_async_get_history` and it's non-async counterpart) should not happen if not necessary. (Idea: compare first with last timestamp to determine correct sorting)
* [x] remove `get_candle_history` - it's not called anywhere apart from tests (but keep / reuse some of the test-logic for async!)
* [x] check for incompatible parameter (dynamic whitelist + edge), ... [from edge] #2158

**Comment by xmatthias** [comment]
based on https://github.com/ccxt/ccxt/issues/4236#issuecomment-442224306 using a different `_LIMIT` seems not possible at the moment, as ccxt does not guarantee the total amount of candles returned, which differs from exchange to exchange.

Also using 500 could fail on some exchanges (lead to holes in the data).

**Comment by hroff-1902** [comment]
>     * `_LIMIT = 500` in `_async_get_history` should not be hardcoded (and probably increased to 1000 as that seems to be in the cache on most exchanges)

@xmatthias 
Leave this for me, I'm working on support for dataframe length for strategies as well as on support for pagination while fetching the dataframe.

**Comment by xmatthias** [comment]
sure thing
Just know that the reason this is hardcoded is that ccxt does not provide a way to know the length before the first call, (some exchanges may only return a max of 120 per call)

**Comment by hroff-1902** [comment]
> sure thing
> Just know that the reason this is hardcoded is that ccxt does not provide a way to know the length before the first call, (some exchanges may only return a max of 120 per call)

Exactly! That's the point for sublassing (one of) where a developer that adds compatibility for a new exchange into FT could specify it in the exchange options! (See my illustrative commit in the BitMEX subclassing PR; that contain just some initial changes there, more should be added for full support of pagination...)
