### ISSUE TITLE
Reduce memory footprint

### ISSUE THREAD

**Issue by flightcom** [freqtrade/freqtrade#121]
The bot seems to crash if it reaches the available memory.
My original config:
- Debian9
- 512MB RAM
- 19 pairs whitelisted
- --dynamic-whitelist enabled
- process_throttle_secs: 5 at first, extended to 30 => still crashing but after a longer period of time.

My config now, that seems to work:
- Added 1Gb of swap
- process_throttle_secs: reduced to 10
- memory consumption: ~420MB RAM + ~80MB SWAP

**Comment by seansan** [comment]
We ran into the same problem. Updated readme for minimal requirements although can differ. But a little bit more RAM is certainly fine

**Comment by shusso** [comment]
this is a constant battle. I think some profiling needs to be done to know what and where to optimize. Closing this until then
