### ISSUE TITLE
Output Coin Name with dataframe in strategy

### ISSUE THREAD

**Issue by chhudson** [freqtrade/freqtrade#1212]
Is there a way to add the coin name to the dataframe in my strategy file? I'd like to be able to output a csv for each coin in my whitelist with all indicators attached for further analysis.

**Comment by xmatthias** [comment]
hi,

you can use the following snippet.
Please make sure to use the last function-header (with metadata dictionary):

``` python
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
    dataframe['pair'] = metadata['pair']
```

explanation:
`metadata['pair']` is a dictionary. Pandas broadcasting makes sure to add this valule to each line of the dataframe in the column `'pair'`.
