### ISSUE TITLE
No trade_buy trade_sell in plot_dataframe.py

### ISSUE THREAD

**Issue by yaotian** [freqtrade/freqtrade#1217]
want to plot buy/sell point.
```
 python scripts/plot_dataframe.py --db-url sqlite:///tradesv3.dry_run.sqlite -p BTC/USDT --refresh-pairs-cached
```

Expected:
trade_sell, trade_buy can be shown on the picture.

![jietu20180917-002627](https://user-images.githubusercontent.com/470917/45598545-5a2de380-ba10-11e8-8745-c812461ef22e.jpg)

**Comment by yaotian** [comment]
plat_dataframe.py

These codes may have logic error? They have default value and never be false?
```
if args.db_url:
   xxxx

if args.exportfilename
   xxxx
```

This line missed "sell_reason" column?
```
columns = ["pair", "profit", "opents", "closets", "index", "duration",
                   "open_rate", "close_rate", "open_at_end"]
```

**Comment by yaotian** [comment]
@xmatthias

**Comment by xmatthias** [comment]
the picture does show buy and sell signals (the green/red triangles) - are they not what's in the sqlite database?

sell-reason is currently not part of the plot-script - but maybe we can add it as a hint or so...

**Comment by yaotian** [comment]
@xmatthias 

1. args.db_url always has value which means "elif" part never work.
"elif" part to show trade_sell, trade_buy from exported trade json file in the picture.
2. exported trade json file missed one column which is wrong.

**Comment by xmatthias** [comment]
1) you're right - it's an idiotic bug really ... but more difficult to fix than one would think...

2) same - but easy to fix ...

**Comment by xmatthias** [comment]
with #1220 merged, i think we can close this.
Thanks for reporting and finding the issue
