### ISSUE TITLE
please add poloniex and indodax exchange

### ISSUE THREAD

**Issue by neonorv** [freqtrade/freqtrade#1231]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```

**Comment by mishaker** [comment]
The project uses CCXT. so if the exchange is supported by CCXT then Freqtrade is supposed to work: 
https://github.com/ccxt/ccxt
That being said the majority of the community use Binance and we are optimizing it for Binance for now.

**Comment by mishaker** [comment]
@neonorv not sure if my answer was convincing. I am going to close this issue but if you test the bot with a specific exchange and you encounter a problem, then don't hesitate to open another issue with logs and more specifications.

**Comment by neonorv** [comment]
sir i dont know any programming, i dont know how to implement ccxt

**Comment by xmatthias** [comment]
What @mishaker means is something different - if the exchange is supported by ccxt (which both poloniex and indodax are) - then you can configure it in freqtrade as well, however we cannot guarantee success because we don't have accounts on that exchange, and you're probably the first to try freqtrade with this exchange.

No coding involved - only trying (and eventually reporting errors)
