### ISSUE TITLE
Exchange klines update can be improved

### ISSUE THREAD

**Issue by mishaker** [freqtrade/freqtrade#1243]
## Summary 
Exchange downloads 500 candles per pair and reassign **klines[pair]** on every interval if it sees a new candle.
There are two problems with this approach: 
- Unnecessary IO bound process
- If klines has lets say only one candle (the most recent one) exchange won't update klines and suppose you have a complete set of klines.

### Current code with added logs
```python
if (not since_ms and self._pairs_last_refresh_time.get(pair, 0) + interval_in_sec >= arrow.utcnow().timestamp):
  data = self.klines[pair]
  logger.debug("Using cached klines data for %s ...", pair)
else:
  print("downloading OHLCV for %s since_ms value: (%s) ..." % (pair, since_ms))
  data = await self._api_async.fetch_ohlcv(pair, timeframe=tick_interval, since=since_ms)
  print("downloaded %s OHLCV for %s ..." % (len(data), pair))
```

### Result on every iteration
```bash
downloading OHLCV for TRX/BTC since_ms value: (None) ...
downloading OHLCV for LOOM/BTC since_ms value: (None) ...
downloading OHLCV for EOS/BTC since_ms value: (None) ...
downloading OHLCV for ETH/BTC since_ms value: (None) ...
downloaded 500 OHLCV for LOOM/BTC ...
downloaded 500 OHLCV for TRX/BTC ...
downloaded 500 OHLCV for EOS/BTC ...
downloaded 500 OHLCV for ETH/BTC ...
```

This can be improved by fetching only new candles but it means _klines should have a data structure to be able to detect and sort tickers according to timestamp and can guarantee there is no distance more than interval between two added candles.

**Comment by xmatthias** [comment]
this was discussed in #1046 ... 
and the agreement was that the exchange probably has the most common value (500 or 1000) in it's cache - and we wouldn't want the burden to properly merge the candles on our end - as that can lead to very bad problems and errors you cannot really debug as the klines end up comming messed up to the strategy.

**Comment by mishaker** [comment]
oops, now I remember :D sorry, going to close the issue
