### ISSUE TITLE
Using freqtrade with external signals

### ISSUE THREAD

**Issue by cristiur** [freqtrade/freqtrade#1260]
Hi,

Can I use freqtrade with external signals ? I mean , i have a server with some machine learning, and when this server push a signal, I want freqtrade to be used as a buy/sell/statistics software.

If so, please point me some directions.

Thank you!

**Comment by xmatthias** [comment]
I actually think this is similar (if not the same) than #1221 - requesting for a `/forcebuy` option to manually buy and have freqtrade manage your position.

**Comment by xmatthias** [comment]
@cristiur is using `/forcebuy` suitable for your usecase (so buy-signals come in through telegram), or do you require something different?

**Comment by cristiur** [comment]
No. I have already implemented my own system for buy and sell. So , no need anymore. 
But thanks for asking.
