### ISSUE TITLE
we should Hide Balances valued less than 1USD on telegram

### ISSUE THREAD

**Issue by ynzheng** [freqtrade/freqtrade#1274]
we should do this 

too much  Small balances(less than 1 USDT ) to view account Balances on telegram by /balances command

![image](https://user-images.githubusercontent.com/107111/46751514-65152480-cced-11e8-9a9a-0fb812eb35fe.png)

**Comment by xmatthias** [comment]
Closing as #1277 is merged, which implements your request.

any issues, feel free to reopen or open a new issue.
