### ISSUE TITLE
No ticker data for pairs opened days ago while using dynamic-whitelist

### ISSUE THREAD

**Issue by doftorul** [freqtrade/freqtrade#1298]
Environment

  * Python Version: Python 3.6.6+ (`python -V`) 
  * CCXT version:  ccxt==1.17.399 (`pip freeze | grep ccxt`)
  * Branch: Develop
  * Last Commit ID: 7da127d28e01d6d633b14b9c155b7a998e7b1635 (`git log --format="%H" -n 1`) 
  
## Step 3: Describe the problem:

While using the dynamic-whitelist to trade, if the pairs are not in the top x by volume anymore after a given amount of time (days, weeks) the ticker history is empty for the opened trades.

freqtrade.strategy.interface - WARNING - Empty ticker history for pair GRS/BTC

**Comment by xmatthias** [comment]
clearly a bug - I think this bug was introduced in #1101 

will have a look.

**Comment by doftorul** [comment]
When constructing the list of pairs via the dynamic-whitelist, there should be a comparison with the pairs on open trades registered in the DB in order to add the relevant pairs to the whitelist requested from the exchange.

**Comment by xmatthias** [comment]
yes i know - the same bug exists if you have an open trade and modify a static whitelist (so it's not limited to dynamic whitelists)

working on a fix ...
