### ISSUE TITLE
Stop loss ignored if it got changed since the trade was opened.

### ISSUE THREAD

**Issue by doftorul** [freqtrade/freqtrade#1304]
Environment

Python Version: Python 3.6.6+ (python -V)
CCXT version: ccxt==1.17.399 (pip freeze | grep ccxt)
Branch: Develop
Last Commit ID: 7da127d (git log --format="%H" -n 1)

If there are opened trades and there is a change for the stop loss in the strategy, if the stop loss is set above the current position profitability, the stop loss is ignored.
Eg:

Position is currently at -12%, the stop loss is set at -0.2. The bot is stopped and the stop loss is changed from -0.2 to -0.1 but the position is ignored and not automatically sold although the threshold is set at -0.1 

Every position that was > -0.1 and reaches in the future the said -0.1 stop loss is executed as it should.

**Comment by mishaker** [comment]
Are you talking about trailing stoploss ? this is the only way to change the stoploss as far as I know.

**Comment by doftorul** [comment]
Nope, not trailing stop loss.
Assume you have a specific stop loss set in your strategy, for example -20% lose, sell the position
Your bot starts to make some trades and some positions are at -17% and some at -15%.
You stop the bot in this moment and modify the strategy and its stop loss to be -10% so you can get rid of the losers and have the bot open new positions.
All the positions that are at -17% and -15% are not liquidated, they are simply ignored. 
Any new position that reaches the newly set -10% stop loss, will be liquidated as intended.

**Comment by mishaker** [comment]
this is a more general question. and yes this is a typical case which proves that we are not handling it correctly: your trades are not synced. you cannot stop the bot he then would be disconnected from the exchange. 
The bot should be synced with the connected exchange when it is started. 
@xmatthias has a better memory than me. but I think we have this issue somewhere and definitely part of the next improvement.

**Comment by doftorul** [comment]
The bot gets stopped for seconds. Change the stop loss. Re-start the bot.

**Comment by xmatthias** [comment]
there are 2 issues with stop-loss - but only one applies here i think

* we don't use stop-loss on the exchange - which can lead to losses if the bot is stopped for longer - but is also difficult to implement as ccxt does not unify this currently, so different code per exchange would be needed - see #988  
* stop-loss is written to the database for better tracking when the trade is opened, but (i think) not updated if you change it in the configuration.

it's the 2nd problem which applies here i think.
You could temporarily circumvent this by manually updating the database (set stoploss to `null` so it gets populated by the new values). this would break trailing stoploss however ... (or at least i think it would) - but if you're not using that anyway it shouldn't be a problem.
or manually selling via `/forcesell` - both methods are not ideal.

I'd need to have a closer look at this - but i don't think fixing this is straightforward without breaking trailing stoploss support.

I'm also not sure if it should be seen as a bug or rather an enhancement - it's simply not supported ATM...

**Comment by mishaker** [comment]
For me it is an enhancement. DB should mirror the exchange at boot. I think we should not put time for a fix on this before sync is implemented.

**Comment by doftorul** [comment]
Not being able to change the stop loss is anything but an enhancement...

**Comment by mishaker** [comment]
From trading point of view you are right :)
