### ISSUE TITLE
Invalid syntax error 

### ISSUE THREAD

**Issue by esitharth** [freqtrade/freqtrade#1309]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: Python 3.6.5 :: Anaconda, Inc.  (`python -V`)
  * CCXT version: ccxt==1.17.448 (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: b3e144f3175fc5df5bb83713397133e02f1b4f6e (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*
Encountered 
File "freqtrade/main.py", line 21
    def main(sysargv: List[str]) -> None:
                    ^
SyntaxError: invalid syntax
while executing the main.py
### Steps to reproduce:

  1. sudo python freqtrade/main.py

  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
are you sure that `sudo python` links to anconda python?
please run `sudo python -V` and post the output. 

Apart from that - 
I don't think that you should be needing `sudo` for freqtrade other than for the installation.

the exception itself is known if running with an older python-version not supporting type-hints (either 2.7 or ~3.4 ... )

**Comment by esitharth** [comment]
O/P for sudo python -V - Python 2.7.15rc1
O/P for python freqtrade/main.py  : 
Traceback (most recent call last):
  File "freqtrade/main.py", line 11, in <module>
    from freqtrade import OperationalException
ModuleNotFoundError: No module named 'freqtrade'

**Comment by xmatthias** [comment]
freqtrade does not work in python 2.7.

please reinstall freqtrade (`pip3 install -e .`) without sudo - and try to run it using `python3 freqtrade --version` (just to check it's working and installed correctly)

**Comment by esitharth** [comment]
> pip3 install -e . 
> python3 freqtrade --version 
> /home/dexter/LearningMaterials/TradingBot/freqtrade/.env/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
freqtrade 0.17.3

**Comment by xmatthias** [comment]
looks like it installed correctly (ignore the warning - there is nothing we can do against that at the moment).

thanks for reporting back
