### ISSUE TITLE
Edge

### ISSUE THREAD

**Issue by creslinux** [freqtrade/freqtrade#1334]
Edge expectancy only works if allowed risk is 1% (0.01) , anything other its broken. 
Here is a toy to play with it, show the drift. 
```
#some vars
expected_risk_reward = 2
win_rate_pct = 0.7

loss_rate_pct = 0.3
allowed_risk = 0.05
total_capital = 3


# FT expectancy algo
expectancy = expected_risk_reward * win_rate_pct - (1 - win_rate_pct)
print("FT_expectancy", expectancy)
print("----")


# Calculate Expectancy - add to nested dict under 'expectancy'
win_expectancy = win_rate_pct * (total_capital * allowed_risk * expected_risk_reward)
loss_expectancy = loss_rate_pct * (total_capital * allowed_risk)
expectancy = win_expectancy - loss_expectancy
avg_interest = expectancy / total_capital

print("win_expectancy", win_expectancy)
print("loss_expectancy", loss_expectancy)
print("expectancy", expectancy)
print("avg %", avg_interest)
```

Also
docs issue,  R is in here as `profit / loss`  I think its supposed to be RR(risk reward, not R)
https://github.com/freqtrade/freqtrade/blob/develop/docs/edge.md

R is users quote capital at risk in a position.
i.e The amount of quote currency lost at if stopped out, it had nothing to do with profit, its the multiplier.

**Comment by mishaker** [comment]
Expectancy does not consider allowed_risk. allowed risk and total capital only scale up or down "relative" expectancy for all pair. 
Expectancy is only used to sort pair (thus, it can be divided or multiplied by any number). 
Allowed risk and capital come to the scene while position sizing is calculated.
In your example Edge calculated expectancy at 1.099
Then sorts all pairs accordingly. 
Multiply or divide that number by anything you want (e.x.  3 * 0.05, so 1.09 * 3 * 0.05 = 0.165) then sort pairs. The result would be the same ...

**Comment by mishaker** [comment]
Scrap it ! your are right ! expectancy should consider allowed risk.

**Comment by xmatthias** [comment]
I'll close this for inactivity.
The explanation from @mishaker  makes sense and is also shown when changing allowed_risk in the script provided above.

Feel free to comment if there's more about this so we can reopen this issue again.
