### ISSUE TITLE
Followup to wallets sync PR

### ISSUE THREAD

**Issue by mishaker** [freqtrade/freqtrade#1345]
In current state the PR works well as it updates the wallet immediately after any trade transaction with exchange occurs. 

However if sometime in future we put stoploss on exchange then it would become problematic as we never know when the stoploss is executed. 

while writing this, it makes me think of something ... stoploss can be treated like an ordinary order in handle_trade ... 

Anyway the solution is to be found and decided.

**Comment by xmatthias** [comment]
i don't think it's problematic after all - even in case of stoploss you'll need to check on the trade (hopefully it's profitable, so we can cancel the stoploss and sell for profit) - so we need to check on it anyway - once we see the order is gone we know we need to update ...

**Comment by mishaker** [comment]
You are right actually, stoploss is like any order and it is updated by handle ... going to close this issue.
