### ISSUE TITLE
Run pytest using docker

### ISSUE THREAD

**Issue by pan-long** [freqtrade/freqtrade#1356]
The `ENTRYPOINT` is set to `['freqtrade']` which is impossible to run other commands for example `pytest` or `flake8`.

This is needed for people running docker and wanting to contribute.

To solve this issue, we can either remove the `ENTRYPOINT` so we can run arbitrary commands, or we can use a custom script as `ENTRYPOINT`, which looks something like this:

    if [ $1 == 'test' ]
    then
        pytest "${@:2}"
    else
        freqtrade "$@"
    fi

**Comment by xmatthias** [comment]
That's a great idea 👍

**Comment by shusso** [comment]
@pan-long sounds good. In the `requirements-dev.txt` you can just `-r requirements.txt` to include the  `default` requirements as the first line

**Comment by pan-long** [comment]
Cool, I will then go ahead and create a PR next week.

**Comment by xmatthias** [comment]
i think #1415 did solve this

Thanks a lot @pan-long
