### ISSUE TITLE
Strats sending more than 1 buy =1 or Sell =1, creates bad/late buys when balance is available later. 

### ISSUE THREAD

**Issue by creslinux** [freqtrade/freqtrade#1362]
Money effecting - Yes.

The impact is trades can be entered many hours late as if were first time the signal is seen.

The test condition is a position is not taken on a base asset on the the first buy=1 signal as there is no quote balance to spend to do so. 
Many hours later there is balance and a position is taken as the strat is continuing sending buy=1 on subsequent candle TA. 

The use-case of this bug is 
1) Many strategies send buy=1 when indicators are in a state, not the first time the state changed. 
i.e when a fast MA is over a slow MA, not only the first time it was seen to cross-over. 

2) A buy =1 is send on first seen cross-over. 
3) A position / trade is not taken up as there is no quote-balance to spend
4) Later from the quote wallet has balance. 
5) The strat is continuing to send buy=1 signals. 
6) The bot considers it has no position on the base asset already so enters the trade - this is many candles late

The fix is to ensure that strategies ONLY send ONE buy or sell = 1 when the TA state changes. 
Ie the prior candle was not a buy=

**Comment by mishaker** [comment]
I am not sure I understand it. If strategy says buy and balance is available then you enter to the trade. What is the importance of knowing say 2 hours ago the balance was not available? 
Sorry it is not clear for me :/

**Comment by creslinux** [comment]
Most of the strats send buy=1 while indicators are in state, not on change as state. 
Take as example 
```
12:00 - first seen buy=1 LTC/BTC. There is no BTC balance. Nothing happens. 
12:00 - first seen buy=1 LTC/BTC. There is no BTC balance. Nothing happens. 
12:00 - first seen buy=1 LTC/BTC. There is no BTC balance. Nothing happens.

**Comment by creslinux** [comment]
The default FT strategy example, as example, will put out buy=1 all the way up. Not only on the first time it was seen. 
```
 def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                (dataframe['rsi'] < 35) &
                (dataframe['fastd'] < 35) &
                (dataframe['adx'] > 30) &
                (dataframe['plus_di'] > 0.5)
            ) |
            (
                (dataframe['adx'] > 65) &
                (dataframe['plus_di'] > 0.5)
            ),
            'buy'] = 1

        return dataframe
```

**Comment by mishaker** [comment]
oh wait ... I think I get it now. So let's say interval is one day: 
at close of yesterday you have a buy signal but no balance. 
today at noon the balance is freed, you still have the buy signal ... (but actually the momentum is lost) 
Richtig ?

**Comment by creslinux** [comment]
To depict the issue. The DFs are sending Buy=1 all the way up. 
The assumption, presumably, is that this is safe as the bot bought on the first square and will not enter a second trade on the same pair 

This assumption is false as if there is no balance it will not open on first square, and may enter on any or last as balance becomes available. 

<img width="276" alt="screenshot 2018-11-26 at 14 47 41" src="https://user-images.githubusercontent.com/34645187/49021695-221eeb80-f18b-11e8-8dcb-6795942e13b5.png">

**Comment by mishaker** [comment]
I can understand it in case it falls between interval. but you seem referring to another issue which is cross over. we you use: 
`qtpylib.crossed_above(df['close'], df['some_indicator'])`
then you wouldn't have this issue

**Comment by creslinux** [comment]
Thats correct - but most, and even the default example FT strategy is not using cross-over. 
i.e its not checking state-change, only in-state.

**Comment by mishaker** [comment]
yes, but it is up to the strategy, bot cannot check it. If we want to handle these things then there are many more issues. here is another example: if you don't check the volume in your strategy before market buy order and the volume is zero then almost certainly your order is fulfilled far above the spot price (20% or so above).

**Comment by creslinux** [comment]
for sure its a strategy thing 
When the bot ships with a bunch of strategies as example and the default have this bad behaviour then its not so clean as to say  not the bots problem. FT is a package to users not just core code.

**Comment by mishaker** [comment]
That's true. the default strategy is misleading and has to be changed.

**Comment by xmatthias** [comment]
Closing this in favor of #1364
