### ISSUE TITLE
Default strategy has to be changed as it is misleading for new users.

### ISSUE THREAD

**Issue by mishaker** [freqtrade/freqtrade#1364]
as discussed in #1362 the default strategy has to be changed to a more reasonable one. 
some basic things are not respected in default strategy which can be misleading and discouraging for new users.
Issues I can think of: 
- It doesn't check the volume so price can deviate radically from TA.
- Buy/Sell moments are propagated to many frames.

**Comment by mishaker** [comment]
@creslinux feel free to add to the list, and if you are ok we replace #1362 with this one.

**Comment by xmatthias** [comment]
Are you talking about the `DefaultStrategy` in `freqtrade/strategy/default_strategy.py` - or rather about `TestStrategy` in `user_data/strategies/test_strategy.py` - which  is the sample code for users ... or both?

while at that - maybe we can also improve / fix the issue with documentation pointed out in #818 ... as i assume the above points will need additions / changes to the documentation as well.

**Comment by xmatthias** [comment]
If you're talking DefaultStrategy, then i don't see much sense in it for the average user, as the documentation [here](https://github.com/freqtrade/freqtrade/blob/develop/docs/bot-optimization.md#change-your-strategy) points to the `TestStrategy`, not `DefaultStrategy`.


This documentation also explains how to add indicators, but lacks information on the other areas (stoploss, roi, ...) as pointed out in #818. 
My assumption based on the above is that you intend to add notes pointing out that volume should be included as indicator for reasons - and that "crossed" should be used to avoid problem Y ... 
which you can add inline - but also in the documentation

**Comment by mishaker** [comment]
Going to close this one as I think we cannot do more than #1562.

**Comment by xmatthias** [comment]
not sure i agree ... 
something like 
```
                (
                    (qtpylib.crossed_above(dataframe['rsi'], 70)) |
                    (qtpylib.crossed_above(dataframe['fastd'], 70))
```

could still be added - but fixing this was not necessarily the purpose of that PR - it was really aimed at fixing my copy/paste error / typo
