### ISSUE TITLE
Getting ticker in handle_trade is not necessary.

### ISSUE THREAD

**Issue by mishaker** [freqtrade/freqtrade#1377]
What we do currently in handle_trade: 
```python
sell_rate = self.exchange.get_ticker(trade.pair)['bid']
```

This is misleading as the bid is not guaranteed to be the best bid.

From CCXT Manual: 

> Although some exchanges do mix-in orderbook's top bid/ask prices into their tickers (and some even top bid/asks volumes) you should not treat ticker as a fetchOrderBook replacement. The main purpose of a ticker is to serve statistical data, as such, treat it as "live 24h OHLCV". It is known that exchanges discourage frequent fetchTicker requests by imposing stricter rate limits on these queries. If you need a unified way to access bid/asks you should use fetchL[123]OrderBook family instead.

`use_order_book`tries to address this but there are two problems with it:

1. It does not consider volume.
1. The ticker is anyway called few lines above so it consumes API call and reduce speed.

Suggestion: 
Best bid price should be calculated directly from Level 2 of orderbook against the amount of trade. Ticker should be removed.

UPDATE: as mentioned in CCXT manual, ticker should be used for statistical purposes. for now the place I can think of using it is in Context or DataProvider as a hint to the strategy (if possible global ticker for all pairs in whitelist).

**Comment by xmatthias** [comment]
I think #1550 solves this (in combination with using orderbook).
feel  free to reopen if you think differently.
