### ISSUE TITLE
Align usage of --data-dir 

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#1384]
## problem
Currently different commands implement the same command (`--data-dir`, `--strategy-dir`) - which however needs to be pointed to different folders depending on the action taken.

### examples:
* download-script needs to be pointed to `user_data/data/<exchange>`

## expectation

This should be aligned (maybe with exception to `--strategy-dir` ) - to ensure a consistent user experience.

* Ideally, this should be pointed to  `user_data` - wherever this is located. 
* A script to create the default user_data structure "anywhere" should be provided to assist users getting started.
* Pointing to `user_data` will load data from `user_data/data/<exchange>`
* pointing to `user_data will load hyperopt files from `user_data/hyperopts`

this should ensure flexibility when more custom/pluggable components are added.

**Comment by hroff-1902** [comment]
#1893 can be considered as a part of this (--export --> --datadir), right?

**Comment by hroff-1902** [comment]
I the whole, I guess there should be a common setting like --userdata-dir (--user-data, or something) which by default points to the user_data dir. That's in addition to the --datadir option. If --datadir is not specified, its value is composed as <userdata_dir>/data/<exchange>. Same for other paths -- for strategies, hyperopt files, etc -- they should start from userdata_dir, which can be set in the command line options (if not overriden explicitely by other options, --datadir, --strategy-dir, maybe --hyperopt-dir etc.)

An env. variable FREQTRADE_USERDATA_DIR can also be fetched from the environment...
