### ISSUE TITLE
Buy limit order is not cancelled after unfilledtimeout period if its size or remaining amount is too small.

### ISSUE THREAD

**Issue by dm1tryx** [freqtrade/freqtrade#1424]
My strategy received a buy signal and the bot placed a limit order for 0.711 ETH/USD that was not filled during the unfilledtimeout period. However it was not cancelled, because int() function in the line 

if int(order['remaining']) == 0:

in the check_handle_timedout function (freqtradebot module) rounds the order size to zero (while in fact order['remaining'] = 0.711) and thinks the order is filled. Once I removed 'int' before 'order['remaining']' the unfilled order got cancelled.

**Comment by mishaker** [comment]
@dm1tryx the bug is resolved now.  please update your bot.
