### ISSUE TITLE
dust

### ISSUE THREAD

**Issue by berlinguyinca** [freqtrade/freqtrade#1425]
Hi a short question. Is there some way with ccxt to utilize the binance dust to bnb feature?

thanks for your great work!

**Comment by xmatthias** [comment]
i think this question would be more suited for the ccxt repository / issues section, as it's not really related to freqtrade.

**Comment by mishaker** [comment]
@berlinguyinca I am closing this one as it is not really related to FT but ask it again on CCXT, I am curious about the answer :)

**Comment by berlinguyinca** [comment]
thanks and ok
