### ISSUE TITLE
update installation.md for Raspberry

### ISSUE THREAD

**Issue by oonid** [freqtrade/freqtrade#1432]
related to new installation for Raspbian #1175 
here's my proposal to update installation.md

```
conda config --add channels rpi
conda install python=3.6
conda create -n freqtrade python=3.6
conda activate freqtrade
conda install scipy pandas numpy

sudo apt install libffi-dev
python3 -m pip install -r requirements.txt
python3 -m pip install -e .
```

I'm getting an error build cryptography (from python-telegram-bot); `ffi.h` no such file or directory.
that would be solved by install Raspbian package `libffi-dev`

actually, on installation steps would be better to guide user to delete `scipy`, `pandas`, `numpy` from `requirements.txt`, and install those from `conda`.

for example, if user try to build `scipy` from pip, it would need to install Fortran compiler to build `dfftpack`.
(eg: `sudo apt install gfortran`)

**Comment by xmatthias** [comment]
Hi,

I did have "libffi-dev" installed because the raspberry I used also had pyenv installed (which does require this for certain versions of python), so probably did not notice this was missing, sorry for that.

We would be very happy to get a PR fixing / enhancing the instructions if you don't mind (you did 98% of the work already... :+1: )

**Comment by mishaker** [comment]
@xmatthias how did you calculate that 98% ?! I would say 99%

**Comment by xmatthias** [comment]
commit + pr -> 2% to :100:

**Comment by oonid** [comment]
@xmatthias thank you.
before I create PR, I have one more question, when I want to try the custom strategy, it complains about `hyperopt` package not installed.
I can't find it on `requirements.txt` is this intentionally? 
so I'm thinking to put information about `python3 -m pip install hyperopt dill` in the installation notes too.

thoughts?

**Comment by xmatthias** [comment]
`hyperopt` used to be part of the bot and included/imported in the default template, however, we switched to scikit-learn for optimizations about half a year ago.

where did you find this strategy / template? I think we removed all "official" references in this repository and in [freqtrade-strategies](https://github.com/freqtrade/freqtrade-strategies) - but maybe we missed it somewhere.

Anyway, it wasn't used within any strategy i've seen for "strategy operations", so if you remove the line `import hyperopt` (or `import hyperopt as hp`) from the strategy it should be fine.

**Comment by oonid** [comment]
I got the strategy from "official" references, but, I copy it from the issues (reference from the README.md).
the issues still refer to [@glonlas repo](https://github.com/glonlas/freqtrade-strategies/tree/master/user_data/strategies), which still use hyperopt.

I will try to use strategy from `[user_data/strategies/](https://github.com/freqtrade/freqtrade-strategies/tree/master/user_data/strategies)`, and check if everything is ok.

**Comment by oonid** [comment]
I think next time, the [README.md](https://github.com/freqtrade/freqtrade-strategies/blob/master/README.md) should be updated,
so the first 5th of strategy should not refer to issues,
instead, refer to files inside [user_data/strategies/](https://github.com/freqtrade/freqtrade-strategies/tree/master/user_data/strategies).
will apply for another PR if it ok.

**Comment by xmatthias** [comment]
yes, absolutely, more contributions are great! :+1: 

and thanks for the PR
