### ISSUE TITLE
Bot cannot be started. Updating problem python and pip

### ISSUE THREAD

**Issue by dowu** [freqtrade/freqtrade#1451]
Hey guys,

I tried to start the bot with `source .env/bin/activate; python3 freqtrade/main.py` but then this error shows up `-bash: .env/bin/activate: No such file or directory
Traceback (most recent call last):
  File "freqtrade/main.py", line 11, in <module>
    from freqtrade import OperationalException
ImportError: No module named 'freqtrade'`

According to the issue #1236 I tried to use `pip3 install -e .` then. But the output of that one gives me another error `Obtaining file:///root/freqtrade
    Complete output from command python setup.py egg_info:
    Your Python interpreter must be 3.6 or greater!
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /root/freqtrade/
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

But here's the first problem. The output of `pip --version` is `pip 18.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)`.

I also got the python version 3.5.2 and tried to update it to 3.6 but it's not possible. I tried
`sudo apt-get update` and
`sudo apt-get install python3.6` but I still got v3.5.2

any ideas?

**Comment by xmatthias** [comment]
do you have a folder `.env`? 
I think the creation of the virtual environment somehow failed - pip3 is using the system python because activation of the venv does not work.

how exactly did you install the bot?

**Comment by xmatthias** [comment]
the guide is from April - at least in the configuration much did change - so please don't copy-paste that part.

Could you please post the output of `./stup.sh --install`? This part must have gone wrong, otherwise you should have a virtual environment under `.venv`.

**Comment by dowu** [comment]
Ah ok that could be the problem.
the output is: `-bash: ./stup.sh: No such file or directory`

**Comment by mishaker** [comment]
@dowu I think you should try `./setup.sh`
There was a typo in xmatthias message

**Comment by dowu** [comment]
Ok so I got another error
`-------------------------
Update your virtual env
-------------------------
pip3 install in-progress. Please wait...
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Do you want to install dependencies for dev [Y/N]? Y
Could not open requirements file: [Errno 2] No such file or directory: 'requirements-dev.txt'
Could not open requirements file: [Errno 2] No such file or directory: 'requirements-dev.txt'
Directory '.' is not installable. File 'setup.py' not found.
pip3 install completed`

But it runs through the whole installation process so I have no idea if it should be like that or not. But when I try to start the bot with `source .env/bin/activate; python freqtrade/main.py` I got this error:
`-bash: .env/bin/activate: No such file or directory
  File "freqtrade/main.py", line 21
    def main(sysargv: List[str]) -> None:
                    ^
SyntaxError: invalid syntax`

**Comment by mishaker** [comment]
you are following installation steps which are obsolete (the article is an outdated one). 
please clone the project from the official repo: 
```bash
git clone https://github.com/freqtrade/freqtrade.git
``` 
and then run: 
```bash 
./setup.sh --install
```
more information on the official documentation: 
https://www.freqtrade.io/en/latest/installation/#easy-installation-linux-script

**Comment by dowu** [comment]
I've already done that. I deleted the folder and it's content and installed it from that source but it still shows this error when I want to start it.

**Comment by xmatthias** [comment]
a) which system are you on?
is it debian? (assuming from you running `apt-get install`...)


>  Directory '.' is not installable. File 'setup.py' not found.

did you cd into the (first) freqtrade directory?

you should be in the same folder than "setup.sh" when running `setup.sh` (if that makes sense)

**Comment by dowu** [comment]
I got macOS.

Yep I am in the first one.
and yes the setup.sh is also here

**Comment by xmatthias** [comment]
I think under macos the commands to get python3 should be:
```
brew install python3
```
taken from [here](https://github.com/freqtrade/freqtrade/blob/develop/docs/installation.md#install-python-36-git-and-wget-1)

apt-get you tried to use before would be for debian-based systems (debian, ubuntu)

@mishaker i think you are on a mac ... ? does the above command give you python 3.5 or python 3.6?

**Comment by dowu** [comment]
yeah i already tried that too. But it tells me that I am not able to install it. Also tried it with sudo

`W: be careful as root.

========================================================================
You may want to update following environments after installed linuxbrew.

  PATH, MANPATH, INFOPATH 

(example: /usr/share/doc/linuxbrew-wrapper/examples/profile)
========================================================================
Don't run this as root!`

**Comment by mishaker** [comment]
@dowu we found the problem. it is fixed now ! please update your code: 
`> git pull`
and run ./setup.sh again. 
Thanks for reporting 👍

**Comment by dowu** [comment]
Hm ok nice. But it doesn't work at all :D

When I run the update or the install command for the setup.sh it tells me that:
```
./setup.sh: line 26: .env/bin/activate: No such file or directory
pip3 install in-progress. Please wait...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-y15m_pq6/py-find-1st/
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-dym18jyv/py-find-1st/
Do you want to install dependencies for dev [Y/N]? Y
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-466qkoaa/py-find-1st/
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-m4h8rrch/py-find-1st/
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-e2blb7cf/py-find-1st/
```

And I realized that I can't use neither the `pip3 install -r requirements.txt` nor the `pip3 install -e .` command because I always got this: 
```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-n9x4npdt/py-find-1st/setup.py", line 10, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-n9x4npdt/py-find-1st/ 
```

aaand when I want to start the bot the first time (as mentioned in the docs) with `python3.6 ./freqtrade/main.py -c config.json` I got that one:
```
Traceback (most recent call last):
  File "./freqtrade/main.py", line 11, in <module>
    from freqtrade import OperationalException
ModuleNotFoundError: No module named 'freqtrade'
```

**Comment by dowu** [comment]
Any idea how i can clear those errors?

**Comment by xmatthias** [comment]
Working on it ... but i had to setup a new server as my system is not supported by the install script (no debian and no brew).

but it's currently running, so we'll see how far i get ...

**Comment by xmatthias** [comment]
Hi, sorry it took a while and thanks for sticking with us.

I did run the full installation without problems multiple times with the following PR #1470 

This should be merged soonish - but if you want to try beforehand (and help us with testing it) - please run

```bash
git fetch
# Assuming your upstream is origin
git checkout -b fix/installscript origin/fix/installscript
./install.sh --install
```

**Comment by mishaker** [comment]
@dowu update your bot please. it should work now.

**Comment by dowu** [comment]
Yep it's running now. Thank you very much guys :)
