### ISSUE TITLE
Anyone trade BTC of Bitmex using freqtrade?

### ISSUE THREAD

**Issue by yaotian** [freqtrade/freqtrade#1480]
As title.

**Comment by gaugau3000** [comment]
no, as far i know this tool don't offert margin trading so i could be diffucult.@xmatthias tell me if i'im wrong.

**Comment by xmatthias** [comment]
If bitmex offers "regular" limit trades it should technically be possible because of ccxt (although untested).

**Comment by yaotian** [comment]
@xmatthias Your "regular" means long side, right? i.e. buy first then sell. So ft can't support short (sell first then buy)

**Comment by xmatthias** [comment]
it does not support that at the moment, no.

**Comment by hroff-1902** [comment]
working on it in the meantime...

**Comment by pookNast** [comment]
Please update when BitMex short/leverage functionality is available, thank you! Cheers

**Comment by xmatthias** [comment]
I'll close this for now since the question was answered, and we have another ticket tracking short support: #892
