### ISSUE TITLE
Does freqtrade support multi ticker_interval setting?

### ISSUE THREAD

**Issue by liubingonline** [freqtrade/freqtrade#1482]
Hi,

I have a case, can strategy using 5min KLine to generate buy/sell signal, but use 1min to do the real backtesting to make the trade more accurate.

For example, there is a buy signal at 2019-1-10 10:00:00, in existing setting, we only can make the trade happen at 2019-1-10 10:00:05.

How to make the trade happen at 2019-1-10 10:00:01 ?

Thanks!

**Comment by xmatthias** [comment]
you could set "process_throttle_secs" to 0 ... 

however I'm not very certain about your example - you talk about 5min/1min candles, but buying 5s or 1s after 10:00, which are 2 different things.

**Comment by liubingonline** [comment]
Thanks for this inforamtion
