### ISSUE TITLE
Cumulative profit in backtest is misleading

### ISSUE THREAD

**Issue by gianlup** [freqtrade/freqtrade#1497]
## Step 3: Describe the problem:

I think (but maybe I'm wrong) that cumulative profit column in backtest report should take in consideration the max_open_trades value. Example: 

stake_amount=0.05
max_open_trades=3
cum profit=30%
total profit BTC=0.015 BTC

Instead of using 0.15 BTC is used 0.05 BTC to calculate cumulative profit, so in reality the cumulative profit is 10%.

**Comment by xmatthias** [comment]
I'm not sure I follow the argumentation ... you do not know if the 3 trades have been made all in parallel or one after the other.

Your assumption is that you always have 3 positions open - but a strategy can also be a "conservative" one, which opens rarely (but almost never looses a trade). 
I have it set to 3 `max_open_trades` as well, but I very rarely have more than 1-2 positions open at the same time.

In my case, 2 would be correct for the calculation. Cum-profit assumes one - simply adding the % profit per trade up (so 20 trades a 1% profit = 20% profit).


maybe similar to #986 - which  might be a better way to display this "clearly"...?

**Comment by gianlup** [comment]
Since I declare `max_open_trades=3` I "allocate" 3*0.05 BTC so I expect the profit % to be relative to 0.15 BTC regardless of how many trades are open at the same time.

I think it's the same thing from the issue you pointed out. 

It may be useful to have both percentages:
* cum profit expressed as sum of percentages (like now)
* total profit % relative to `stake_amount * max_open_trades`. Maybe we can add it to the total profit BTC column like 
```
| total profit BTC |
|-----------------:|
|      0.015 (10%) |
```

**Comment by xmatthias** [comment]
Would be happy to see a PR about this - visualization is not something I'm particularly good at ...
