### ISSUE TITLE
Dynamic stake amount instead of fixed

### ISSUE THREAD

**Issue by mikequant** [freqtrade/freqtrade#1499]
Current state:
when you load config.json file is allows you to define the stake amount. So when you start trading and is making money, your account balance increases, but your stake amount is not.
Hence, you are missing the benefits of compounding interest.

Here is an example of how it looks like vs how it can be:
![image](https://user-images.githubusercontent.com/45214133/51430853-1565c380-1c21-11e9-961b-f1132c5ab099.png)

So simply making it dynamic, you can increase the profit by 20% in a given example.

**Comment by xmatthias** [comment]
Hi,

if you are fine with the bot using all available balance in stake currency - then it is possible bu setting stake_amount to "unlimted".
Documentation [here](https://www.freqtrade.io/en/latest/configuration/#understand-stake_amount)

I think however that "edge" would provide more benefit, as this does dynamic position sizing based on the calculated risk for each trade.
Documentation [here](https://www.freqtrade.io/en/latest/edge/)

**Comment by mikequant** [comment]
Hi,

I think you are right, it will be better to use edge rather then creating something new.

Thank you!
