### ISSUE TITLE
Feature: Plotting Web UI / Strategy Test data Selector

### ISSUE THREAD

**Issue by Axel-CH** [freqtrade/freqtrade#1505]
## INTRO
Visualisation and observation is important in Developing a trading strategy. Currently on freqtrade, to visualize a graph and trades, the user need to generate and html file with a command line (plot-dataframe.py).
It's working well, but the whole process is not efficient and user friendly. Even more so during multiple tests.
Furthermore, for my ongoing experimentations, I need a tool to quickly select and extract specific price movement history and indicators in dataframe.

## GOAL:
- Quickly visually check strategy behavior
- Facilitate the selection and backup of pertinent price movement / paterns

### MAIN FEATURES
_#Input data pipe 1_

- [x]  Import json ticker history file 
- [x] plot candles
- [x] Select strategy

_#Input data pipe 2_

- [x]  Enter Pairs
- [x]  Select strategy, Timeframe
- [x]  Enter Pairs

_# Backtest execution, visualisation and export_
- [x] Run a backtest
- [ ] Plot candles with strategy indicators
- [ ] Select the important movement (time interval) to export
- [ ] Export Dataframes to json
- [ ] Export Dataframes Plots to html

### OTHER FEATURES
- [ ] Display standard indicators
- [ ] Select a date range
- [ ] Filter pairs by volume
- [ ] Realistic mode (remove same consecutive signals)
- [ ] Beter UX, collapsible sidebar for conf, plots on full screen

## SCREENSHOOT
<img width="956" alt="2019-01-21 23_25_14-dash" src="https://user-images.githubusercontent.com/7593404/51510723-9f09c280-1dd4-11e9-92ca-48b7a91f4c77.png">

## Step 2: Describe your environment
  * Python Version: Python 3.6.5 :: Anaconda, Inc.
  * CCXT version: ccxt==1.17.352
  * Branch: feature/plot_web_ui (on fork)
  * Last Commit ID: 54109abc6adf1ceb919b572b3972fc6ffedeb23c (fork)

Note that the Dash module used for the UI use a flask server.
 
## Step 3: Describe the problem:
I'm not able to execute a backtest due to an error with the async ccxt feature.

### Steps to reproduce:
  1. git clone https://github.com/Axel-CH/freqtrade.git
  2. git checkout feature/plot_web_ui
  3. pip install -e .    (to install dash modules)
  4. python .\scripts\plot_df_web_ui.py
  5. Open navigator on http://127.0.0.1:8050/
  6. Fill the fields
  7. Click on "Run Backtest"

### Observed Results:
Error on backtest execution due to the asyncio event loop.

### Relevant code exceptions or logs:
```
Traceback (most recent call last):
  File "/home/Axel/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/Axel/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/Axel/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Axel/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/Axel/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Axel/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Axel/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Axel/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/Axel/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Axel/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/Axel/anaconda3/lib/python3.7/site-packages/dash/dash.py", line 967, in dispatch
    return self.callback_map[target_id]['callback'](*args)
  File "/home/Axel/anaconda3/lib/python3.7/site-packages/dash/dash.py", line 907, in add_context
    output_value = func(*args, **kwargs)
  File "/mnt/c/Users/Axel/Documents/Dev_center/framework-dev/public/freqtrade/scripts/plot_df_web_ui.py", line 240, in update_run_backtest
    self.run_backtest(strategy_name, pairs)
  File "/mnt/c/Users/Axel/Documents/Dev_center/framework-dev/public/freqtrade/scripts/plot_df_web_ui.py", line 370, in run_backtest
    results = Backtesting(validated_conf)
  File "/mnt/c/Users/Axel/Documents/Dev_center/framework-dev/public/freqtrade/freqtrade/optimize/backtesting.py", line 82, in __init__
    self.exchange = Exchange(self.config)
  File "/mnt/c/Users/Axel/Documents/Dev_center/framework-dev/public/freqtrade/freqtrade/exchange/__init__.py", line 98, in __init__
    exchange_config, ccxt_async, ccxt_kwargs=exchange_config.get('ccxt_async_config'))
  File "/mnt/c/Users/Axel/Documents/Dev_center/framework-dev/public/freqtrade/freqtrade/exchange/__init__.py", line 143, in _init_ccxt
    api = getattr(ccxt_module, name.lower())(ex_config)
  File "/home/Axel/anaconda3/lib/python3.7/site-packages/ccxt/async_support/base/exchange.py", line 52, in __init__
    self.asyncio_loop = self.asyncio_loop or asyncio.get_event_loop()
  File "/home/Axel/anaconda3/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-74'.
```
### Possible Solutions
-> Add a parameter to disable async on Backtest at specific ocasions
-> Create an event loop in web ui.

As this issue is related to the tricky topic of async, I ask advice from specialists. Also let me know what you think about the general  idea of adding a Web User interface to freqtrade.

**Comment by Axel-CH** [comment]
Hi @xmatthias thank you four that response, 

> I did not try this yet but I'm not quite sure why asyncio / ccxt_async should be relevant for backtesting unless you use "--refresh-pairs-cached" (or it's counterpart in the configuration), since asyncio is only used to download ohlcv data.

You are right, this feature is not critical for backtesting but when I  start a backtests "asyncio / ccxt_async" is automatically loaded. I added the full logs Traceback in the description.
Of course I would be happy to contribute on this part ;-)

**Comment by jamesthesken** [comment]
Hey @xmatthias and @Axel-CH I was also planning to develop a Web UI. I've been getting into React development and came across this repo, seems like a good feature to get involved with. Should I open a new issue for tracking that feature? I started off by testing a simple javascript REST API client below. Let me know what your thoughts are, I hope to find a way to contribute as best as possible! Maybe I could complete the javascript api client and commit that first.

```
// deprecated, should use Fetch instead
var request = require('request');

var options = {
  url: 'http://127.0.0.1:8080/api/v1/status',
  headers: {"Accept": "application/json",
            "Content-Type": "application/json"},
  auth: {
      'username': 'user',
      'password': 'password'
  }
};

request.get(options,function(error, response, body) {
  console.log(body);
});
```

**Comment by xmatthias** [comment]
@jamesthesken 
I've forgotten that we still got this issue.

After using Dash for a bigger project at work, i don't think it's a good fit to use for Freqtrade.
Once it moves beyond "a few" simple components, it becomes a mess very quickly.

I'm currently working on a UI in Vue.js, i will opensource once it's "presentable".

Regular operations (what's possible with telegram ATM) is working for the most part, but i'm still having to do a bit (lot?) of work to have it look better (i'm not really a graphical genious).

My biggest concerns with that at the moment are if it should be included in this repository, or in a seperate repository, and how to best deploy it in an easy, non-technical user friendly manner.

It will not include graphs / plotting in a first step, but adding that at a later point should be rather easy.

**Comment by jamesthesken** [comment]
@xmatthias 
Thank you for the reply. I think I should clarify, I haven't used Dash before and not sure what that is. Is that this library? https://dash.plotly.com/react-for-python-developers

I'd agree that looks cumbersome. I meant I would be on a similar path as you, but I'm more familiar with React. I think I may pursue it given my educational interests in React. 

I'll try to poke around some more for a good contribution to make. Look forward to seeing your UI.

**Comment by xmatthias** [comment]
yes it's that library ...
It's built in react - but you'll never really see or use that - it's all coded in python itself.

I know react, but i find it's template syntax a huge mess ... 
Also, i hope using vue (a framework known to be simple to learn) can spark more community contributions.

**Comment by jamesthesken** [comment]
okay, thank you. I'll keep up to date on when you release the UI, that could be a good chance to learn Vue. As a side-note I really like the dry-run features you guys have made, I have a lot to explore still in this repo.

**Comment by xmatthias** [comment]
@jamesthesken just for completeness:

the UI is now opensource ([here](https://github.com/freqtrade/frequi)). It's still in early alpha mode - so things change on a regular basis - but i'm hoping for contributions.

I've also added a quick [roadmap](https://github.com/freqtrade/frequi/issues/6) for that UI project ... but it'll focus on "operational" stuff first, and plotting at a later point once the rest is stable and looks ok.

**Comment by xmatthias** [comment]
I'll close this here - as [freqUI](https://github.com/freqtrade/frequi) will be the future from a freqtrade UI perspective.

Using Dash is not really suitable for any bigger project as it'll become a huge mess soon (experienced this at work, never going to do that again).

While sad, i hope everyone will be happy with what freqUI will provide (especially with the features that are still to come).

**Comment by Axel-CH** [comment]
Hi @xmatthias i'm totally agree with you, dash is a bit messy for the moment. I didn't have the time to work more deeply on that, I will take a look at freqUI soon. And again, thank you for your work ;-)
