### ISSUE TITLE
Edge - FUTURE warning

### ISSUE THREAD

**Issue by macd2** [freqtrade/freqtrade#1523]
## Step 2: Describe your environment

  * Python Version: __3.6___ (`python -V`)
  * CCXT version: __latest___ (`pip freeze | grep ccxt`)
  * Branch:  Develop
  
## Step 3: Describe the problem:
```
../freqtrade/freqtrade/edge/__init__.py:306: FutureWarning: 'pair' is both an index level and a column label.
Defaulting to column, but this will raise an ambiguity error in a future version
  df = results.groupby(['pair', 'stoploss'])['profit_abs', 'trade_duration'].agg(

../freqtrade/freqtrade/edge/__init__.py:306: FutureWarning: 'stoploss' is both an index level and a column label.
Defaulting to column, but this will raise an ambiguity error in a future version
  df = results.groupby(['pair', 'stoploss'])['profit_abs', 'trade_duration'].agg(
```

*Explain the problem you have encountered*

Also i only get results for 2 pair's why's that?

**Comment by UncleVasya** [comment]
You get results only for 2 pairs because there are filters in config.json (Edge section):

`
"minimum_winrate": 0.60,
"minimum_expectancy": 0.20,
"min_trade_number": 10,
`

**Comment by mishaker** [comment]
@macd2 the above answer is exact. I am going to close this one but don't hesitate to reopen if you think otherwise.
