### ISSUE TITLE
Clear / reset trade history

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#1532]
Hello! Simple beginner questions again  (sorry for this):

I am running my bot dry at the moment, how can I reset / clear the tables (trading history, RoI etc.) before I go in production (or test another strategy dry)?

PS: is there any platform to exchange on such easy questions for Freqtrade? Is it ok to post it here on Github?

PPS: what is the exact name of the trading strategy slack channel, cannot find it

**Comment by xmatthias** [comment]
you can join slack using [this](https://join.slack.com/t/highfrequencybot/shared_invite/enQtMjQ5NTM0OTYzMzY3LWMxYzE3M2MxNDdjMGM3ZTYwNzFjMGIwZGRjNTc3ZGU3MGE3NzdmZGMwNmU3NDM5ZTNmM2Y3NjRiNzk4NmM4OGE) link.

To reset the trading history - simply delete (or move) the sqlite file (by default `tradesv3.sqlite` or `tradesv3-dry-run.sqlite`).
You can also use `--db-url PATH` when starting the bot to use a different file.

**Comment by Eowm** [comment]
HI,

I've changed my strategy on the one already working live, how to remove old data of the trades? 
I've it connected to the teleram, and I can see all of the old trades.

Thanks

**Comment by hroff-1902** [comment]
remove the database file

**Comment by Eowm** [comment]
Thanks, and which one is that ?

**Comment by hroff-1902** [comment]
From the docs:
> db_url | Declares database URL to use. NOTE: This defaults to sqlite:///tradesv3.dryrun.sqlite if dry_run is true, and to sqlite:///tradesv3.sqlite for production instances.

File name is the same, but without first part of URL -- tradesv3.dryrun.sqlite or tradesv3.sqlite.

**Comment by umz007** [comment]
Hi, Apologies if this is a basic question.

I have tried to search for the database file and have found a file called "test_persistence.py". Will deleting this file remove the historic trades from my telegram?

Many Thanks

**Comment by xmatthias** [comment]
no.
The database file is usually called `tradesv3.dryrun.sqlite` or `tradesv3.sqlite`.
