### ISSUE TITLE
Kraken support

### ISSUE THREAD

**Issue by iuvbio** [freqtrade/freqtrade#1549]
Environment:
  * Python 3.7.2
  * ccxt==1.18.221
  * Develop
  * Last Commit ID: 018cee8413ffb81079a61ab2c207f11101594a3b

### Problem

I am trying to get Kraken to work, yet whenever I try to download historic data, I get a Rate limit error.

Config:
```
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true
        }
```

To check if there is some issue with my API credentials, I instantiated a `ccxt.kraken` instance with the same credentials and from there the ohlcv could be fetched without problems.

I know that Kraken has stricter rate limits than Bittrex and Binance, so I tried to get the ohlcv synchronously by adapting the asynchronous methods in `freqtrade.exchange`:

```python
def _sync_get_history(self, pair: str, tick_interval: str,
                          since_ms: int) -> List:
        _LIMIT = 500

        one_call = constants.TICKER_INTERVAL_MINUTES[tick_interval] * 60 * _LIMIT * 1000
        logger.debug("one_call: %s", one_call)
        logger.info("Synchronously getting history")

        tickers = [self._sync_get_candle_history(pair, tick_interval, since)
                   for since in range(since_ms, arrow.utcnow().timestamp * 1000, one_call)]

        # Combine tickers
        data: List = []
        for p, ticker_interval, ticker in tickers:
            if p == pair:
                data.extend(ticker)
        # Sort data again after extending the result - above calls return in "async order"
        data = sorted(data, key=lambda x: x[0])
        logger.info("downloaded %s with length %s.", pair, len(data))
        return data

def _sync_get_candle_history(self, pair: str, tick_interval: str,
                                 since_ms: Optional[int] = None) -> Tuple[str, str, List]:
        try:
            # fetch ohlcv asynchronously
            logger.debug("fetching %s, %s since %s ...", pair, tick_interval, since_ms)

            data = self._api.fetch_ohlcv(pair, timeframe=tick_interval,
                                         since=since_ms)

            ...

            try:
                if data and data[0][0] > data[-1][0]:
                    data = sorted(data, key=lambda x: x[0])
            except IndexError:
                logger.exception("Error loading %s. Result was %s.", pair, data)
                return pair, tick_interval, []
            logger.debug("done fetching %s, %s ...", pair, tick_interval)
            return pair, tick_interval, data

        except ccxt.NotSupported as e:
            raise OperationalException(
                f'Exchange {self._api.name} does not support fetching historical candlestick data.'
                f'Message: {e}')
        except (ccxt.NetworkError, ccxt.ExchangeError) as e:
            raise TemporaryError(
                f'Could not load ticker history due to {e.__class__.__name__}. Message: {e}')
        except ccxt.BaseError as e:
            raise OperationalException(f'Could not fetch ticker data. Msg: {e}')
```

`exchange.get_history()` calls `_sync_get_history()` when the exchange id is "kraken". This works, as confirmed by the log. However, I still get the rate limit error and right away from the first call. Even if there was some issue with the rate limiting, I'd expect at least the first few calls to go through.

I know that Kraken is not officially supported, but I'd like to contribute to making it work, so I'd appreciate any pointers that might help explain this behaviour or provide me with a starting point for further investigation.

### Steps to reproduce:

  1. Specify kraken in config
  2. run download script or backtest with `-r`
  
### Observed Results:

  * See log and description above

### Relevant code exceptions or logs:

  ```
About to download pairs: ['BTC/EUR', 'DASH/BTC', 'ETC/BTC', 'ETH/BTC', 'ETH/EUR', 'LTC/BTC', 'LTC/EUR'] to user_data/data/kraken
2019-02-12 18:34:33,364 - freqtrade.exchange - INFO - Instance is running with dry_run enabled
2019-02-12 18:34:33,365 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2019-02-12 18:34:33,366 - freqtrade.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2019-02-12 18:34:33,377 - freqtrade.exchange - INFO - Using Exchange "Kraken"
Exchange Kraken allows asynchronous pair getting False
downloading pair BTC/EUR, interval 1m
2019-02-12 18:34:42,467 - freqtrade.data.history - INFO - Download the pair: "BTC/EUR", Interval: 1m
2019-02-12 18:34:42,468 - freqtrade.exchange - INFO - Synchronously getting history
2019-02-12 18:35:10,342 - freqtrade.data.history - INFO - Failed to download the pair: "BTC/EUR", Interval: 1m, Msg: Could not load ticker history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}
  ```

**Comment by xmatthias** [comment]
the downloadscript only uses config when used with `--config config.kraken.json`, otherwise it uses a mocked / fake exchange configuration
https://github.com/freqtrade/freqtrade/blob/b9a5899c994175f87135f09dccfefb2fdc1c49f4/scripts/download_backtest_data.py#L39-L50

I do think that multiple requests are made before you are blocked, but not enough to download 1 pair completely - so it seems to you that no requests are made. Try the below to confirm that, if that fails, then your IP is blocked and you should change that / wait for the block to disappear).
You can also change the download-script logging level to DEBUG to confirm this (line 17ish...)

using the following lines with the latest (unmodified) version I am able to download data without problems (rate-limit enabled for ccxt_async).

```bash
 python scripts/download_backtest_data.py --pairs-file user_data/data/kraken/pairs.json --config user_data/config.kraken_ETH.json -t 1h --days 1
2019-02-12 19:13:33,005 - freqtrade.configuration - INFO - Validating configuration ...
About to download pairs: ['BCH/EUR', 'BTC/EUR', 'DASH/EUR', 'EOS/EUR', 'ETC/EUR', 'ETH/EUR', 'GNO/EUR', 'LTC/EUR', 'REP/EUR', 'XLM/EUR', 'XMR/EUR', 'XRP/EUR', 'ZEC/EUR'] to user_data/data/kraken
2019-02-12 19:13:33,010 - freqtrade.exchange - INFO - Instance is running with dry_run enabled
2019-02-12 19:13:33,018 - freqtrade.exchange - INFO - Using Exchange "Kraken"
downloading pair BCH/EUR, interval 1h
2019-02-12 19:13:42,192 - freqtrade.data.history - INFO - Download the pair: "BCH/EUR", Interval: 1h
2019-02-12 19:13:46,319 - freqtrade.exchange - INFO - downloaded BCH/EUR with length 42.
2019-02-12 19:13:46,319 - freqtrade.misc - INFO - dumping json to "user_data/data/kraken/BCH_EUR-1h.json"
downloading pair BTC/EUR, interval 1h
2019-02-12 19:13:46,329 - freqtrade.data.history - INFO - Download the pair: "BTC/EUR", Interval: 1h
2019-02-12 19:13:49,034 - freqtrade.exchange - INFO - downloaded BTC/EUR with length 42.
2019-02-12 19:13:49,034 - freqtrade.misc - INFO - dumping json to "user_data/data/kraken/BTC_EUR-1h.json"
downloading pair DASH/EUR, interval 1h
2019-02-12 19:13:49,034 - freqtrade.data.history - INFO - Download the pair: "DASH/EUR", Interval: 1h
2019-02-12 19:13:52,098 - freqtrade.exchange - INFO - downloaded DASH/EUR with length 42.
2019-02-12 19:13:52,099 - freqtrade.misc - INFO - dumping json to "user_data/data/kraken/DASH_EUR-1h.json"
downloading pair EOS/EUR, interval 1h
...
```

my configuration is not  special - however by limiting the history to 1 day and 1h candles, only one request per pair has to be made.
without `--days` it falls back to 30 days, which (assuming 1m candles) requires many requests ( `60 (mins) * 24(hours) * 30 (days)`).

you can get around this limit by configuring ccxt to apply the kraken-specific rate-limit:

```config
"ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200 
        },
```
`rateLimit` is in ms - the above configuration works for binance - for Kraken you'll probably want to set it WELL above 1000 ...

Also note that last time i checked, kraken only provided ~2000 candles per interval - but this may have changed since they launched their new platform last week.

**Comment by xmatthias** [comment]
An additional word about Kraken support:

Technically kraken should be supported for "regular" usage (no stoploss on exchange), however I tried to use it ~half a year ago in dry-run and their api was instable and returned errors / 404 / 502 / .../ every other day or so (just while fetching candles ...)

this may have improved since - but use with caution and do "longish" dry-run tests before putting money on the line...

**Comment by iuvbio** [comment]
Thanks for the support! You're right, I can confirm that it works with only 1 day and 1h timeframe, even without setting the rate limit.

I thought the issue had to be due to async, because *theoretically* ccxt's rate limiting should take care of timing the requests so that the rate limit is not reached, no matter how many requests in total, right? As far as I know, the newer versions of ccxt (don't know when exactly it was implemented) dynamically adjust the rate limit, do you know if that still happens if you set the rate limit initially via the config?

I will do some tests with rate limit set to 1000 or more, that's what their docs suggest for public calls as well. You're right, these issues made Kraken barely usable a while ago, but I feel like they have improved a lot in that respect and their new platform might improve performance even more. The future trading might bring some new volume, so it would be great if we could use the bot there.

**Comment by iuvbio** [comment]
After some initial testing, it seems that using a `rateLimit` of 3000 even a large number of requests is supported. I still sometimes get 520 errors, but they are handled quite well by the retrier.

I think that Kraken indeed limits the amount of candles it provides per interval, but it seems to be even less than 2000, unless my logic is not right here?

For example, I download the data with `python scripts/download_backtest_data.py -c config_kraken.json -t 5m --days 5` successfully, but the maximum time range I can get is apparently two days back. 2000 candles should be about 7 days. This is also the case when I specify `timerange` to start earlier than 2 days ago.

```
python ./freqtrade/main.py -c config_kraken.json backtesting -i 5m
...
freqtrade.optimize.backtesting - INFO - Measuring data from 2019-02-10T11:20:00+00:00 up to 2019-02-12T23:10:00+00:00 (2 days)..
```

Kraken requires an additional parameter to ccxt.create_order() [see here](https://github.com/ccxt/ccxt/wiki/Manual#custom-order-params). Should these be added just before the calls in `sell`, `buy`, and `stoploss_limit`? I think it would be good to set the extra parameters at once something like

```python
params = {}
if time_in_force != 'gtc':
    params.update({'timeInForce': time_in_force})
if self.id == "kraken":
    params.update({"trading_agreement": "agree"})
```

**Comment by xmatthias** [comment]
it's very well possible that it's 2 days - I gave up trying Kraken for this reason (makes no sense to run the bot if you can't backtest due to lack of data). even 7 days is not enough in my opinion, I would backtest at least a month to be certain that a strategy works in a particular market.

You can set the parameters this way - but from the documentation, it's not clear to me if the trading_agreement needs to be set each time - or if it's enough to tick a box on the website initially ...

**Comment by iuvbio** [comment]
Yea, the ability to backtest is kind of essential.. It'd be possible to get around this restriction by periodically running the download script and get the necessary history that way, but that's not a great solution. I found that for the 4h timeframe it's possible to download more history (up to 100 candles tested). Of course that limits possible strategies a lot, but it's something.

I checked and it seems that trading_agreement has to be set on each call. However, as @creslinux is saying [here](https://github.com/freqtrade/freqtrade/issues/1371#issuecomment-447456197), I don't think params should be set in this way. Eventually there will be if clauses for different exchanges everywhere.. I'll make a kraken subclass that takes care of this and potentially other kraken specific things.

**Comment by iuvbio** [comment]
Hi, the subclass is finished, all the tests pass, as well as `flake8` and `mypy`. The `stoploss_limit` method is still the same, so `stoploss_on_exchange` won't work currently, but that's also possible to implement on Kraken.

Should I open a pull request or is there anything else to do before?

**Comment by xmatthias** [comment]
Feel free to open a Pull request.

Note that just "passing tests" may not be enough in the subclass case (that's why this has not been implemented yet). We'll see that when reviewing though ... :+1:

**Comment by iuvbio** [comment]
I'm happy to write additional unittests as well, if necessary. I've added an exchange_resolver to pick up the exchange class, so yea considering this, there's probably some additional things required. Anyway, I'll open the PR and just let me know what to change :)

**Comment by xmatthias** [comment]
@iuvbio 
did #1563 implement kraken successfully (i don't have funds there atm) or are there still some things to tweak to add kraken to the supported exchange-list?

**Comment by iuvbio** [comment]
Base implementation is fully functional (have that version running since a while). Go ahead and close this, I haven't yet because of stoploss support, but that can be taken up in a different issue or just PR.
