### ISSUE TITLE
Cannot join "highfrequencybot" channel in Slack

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1564]
Browse channels --> "highfrequencybot" --> "No matches found for highfrequencybot"
:-1: -(

**Comment by hroff-1902** [comment]
Why, why elementary things are so complicated in XXI century?

**Comment by xmatthias** [comment]
I don't think you can search for slack channels ...

the link to join is [this](https://join.slack.com/t/highfrequencybot/shared_invite/enQtMjQ5NTM0OTYzMzY3LWMxYzE3M2MxNDdjMGM3ZTYwNzFjMGIwZGRjNTc3ZGU3MGE3NzdmZGMwNmU3NDM5ZTNmM2Y3NjRiNzk4NmM4OGE), which can also be found on the bottom of the readme.md (and in a few places in the documentation)...

**Comment by hroff-1902** [comment]
I tried this link, exactly, it created new workspace.

"You’ve joined the new Slack workspace highfrequency." as stated in the mail from Slack...

**Comment by hroff-1902** [comment]
I tried that link, exactly, from that .md,

It created a new workspace wharever it means in Slack:
"You’ve joined the new Slack workspace highfrequency." as a mail (second one, after e-mail validation) from Slack says...

**Comment by hroff-1902** [comment]
I've open this issue with a thought that the link in that .md was broken/outdated. Well, since it's okay, nothing to discuss, it's a problem of my local environment.

@xmatthias, thanks alot.
