### ISSUE TITLE
cannot run pytest

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1565]
Since I cannot join dev Slack channel, issuing here:
```
$ pip3 install telegram
Collecting telegram
Installing collected packages: telegram
Successfully installed telegram-0.0.1
```

Okay, telegram package already installed...

```
$ pytest freqtrade
ImportError while loading conftest '/home/user/freqtrade-wrk/freqtrade/freqtrade/tests/conftest.py'.
freqtrade/tests/conftest.py:12: in <module>
    from telegram import Chat, Message, Update
E   ImportError: cannot import name 'Chat'
```

Where am I wrong?

**Comment by xmatthias** [comment]
`telegram` is not the correct package ...
try running 
```
pip3 uninstall telegram
pip3 install -r requirements-dev.txt
```

This should set up everything you need to run (and run pytest) for the bot.

I would strongly suggest to use a virtual envrionment for this to separate your environments.

**Comment by hroff-1902** [comment]
Ah, right, thanks.
