### ISSUE TITLE
Question: any theory behind Edge?

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1573]
@mishaker 
Hi, are there any theory, articles or other publications behind all that stuff in the Edge module?
Trying to understand better the internals of FT...

**Comment by mishaker** [comment]
https://www.tradeciety.com/ultimate-math-guide-for-traders/
http://www.vantharp.com/tharp-concepts/expectancy.asp
https://samuraitradingacademy.com/trading-expectancy/
https://www.learningmarkets.com/determining-expectancy-in-your-trading/
http://www.lonestocktrader.com/make-money-trading-positive-expectancy/
https://www.babypips.com/trading/trade-expectancy-matter

**Comment by hroff-1902** [comment]
No, no that one. I do not need "ultimate guide for traders". :-)

I mean some kind of materials illustrating particular ideas implemented in the Edge module. They seem for me to be not so common to search for them in a generic "ultimate guide for traders"...

**Comment by mishaker** [comment]
Read the first article, it explains expectancy, winrate, risk management
etc...

**Comment by xmatthias** [comment]
Stupid question - should the references (maybe not all of them) be in the documentation for Edge ... maybe?

**Comment by mishaker** [comment]
What I wrote on Edge docs was a complication of parts of those articles with a lot of brainstorming with @creslinux (RIP). happy to enrich it further but it doesn't 100% comply to those articles. those articles are more for general trading than FT adapted.

**Comment by hroff-1902** [comment]
> What I wrote on Edge docs was a complication of parts of those articles with a lot of brainstorming with @creslinux (RIP). happy to enrich it further but it doesn't 100% comply to those articles. those articles are more for general trading than FT adapted.

That's what I wanted to know, man! ;-))

**Comment by mishaker** [comment]
well you are aware of our site ? :) 
you can find the complete documentation of Edge here: 
https://www.freqtrade.io/en/latest/edge/

**Comment by hroff-1902** [comment]
Documentation of Edge is broad and complete, yeah.
Just wanted to know about sources of the idea, nevermind...

**Comment by hroff-1902** [comment]
The list of the references may be included in the doc on Edge -- may be useful for a thoughtful reader...

**Comment by mishaker** [comment]
don't hesitate to do a PR and add (maybe one of them?) to the docs. I spent a lot of time on Edge so I need a new pair of eyes ;)

**Comment by hroff-1902** [comment]
> don't hesitate to do a PR and add (maybe one of them?) to the docs. I spent a lot of time on Edge so I need a new pair of eyes ;)

May be anything except the docs. English is not my mother tongue...

**Comment by xmatthias** [comment]
> English is not my mother tongue...

Also not ours ... (that's probably why we find many typos each time we read through the docs ...)

**Comment by hroff-1902** [comment]
#1590
