### ISSUE TITLE
dry_run orders and create_order

### ISSUE THREAD

**Issue by iuvbio** [freqtrade/freqtrade#1574]
Currently, the order structure returned by buy or sell in dry_run is different from the one returned by stoploss_limit. Not only that, but the former return only `{"id": order_id}`, while the latter returns the complete order (with an id). I suggest this should be unified and all be moved to one method.

Same goes for the actual buy/sell methods. I suggest to make a wrapper around `ccxt.create_order` that takes a param argument. Kind of what @xmatthias proposed as an alternative for subclassing in #1563. All the exception handling now triplicated could be done in the wrapper and the various order types are done by calling that method with the respective arguments. Makes it easier to implement featured in only some exchange's subclasses as well.

**Comment by xmatthias** [comment]
the dry-run returns are done to support the bot running.
Returning a complete, mocked result from an exchange would only have limted usage if we don't use that information - and everything that is used from the answers is returned anyway.

I do however agree that exchange could need some love - for example extracting the common exception handlers into a decorator, but also to extract certain similar return-values to a method of some kind...

**Comment by iuvbio** [comment]
> and everything that is used from the answers is returned anyway.

Sorry, I don't get what you mean here. Currently the mock only returns a dict with only the id for buy/sell, but the complete order dict for stoploss. In freqtradebot only the id is retrieved (also for stoploss orders), so I guess returning just the id dict in stoploss_limit would be fine. Only in `execute_buy` the status is also retrieved, but that defaults to zero (as mock order dict only contains id).

> I do however agree that exchange could need some love - for example extracting the common exception handlers into a decorator, but also to extract certain similar return-values to a method of some kind...

I'll work on that.

**Comment by xmatthias** [comment]
all I intended to say was that the dict "has what is used". It's limiting and doesn't make sense, so any improvement is welcome :+1:
