### ISSUE TITLE
Bug: RecursionError in Edge

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1600]
## Step 2: Describe your environment

  * Branch: Develop
  
## Step 3: Describe the problem:

In the Edge code the _detect_next_stop_or_sell_point() method contains recursive call. This function and the Edge module in the whole if used can fail generating exception "RecursionError: maximum recursion depth exceeded while calling a Python object" after (a bit less than) 1000 recursive calls which is the default limit for python. For an ordinal trader it's inappropriate to dig into unix `setrlimit` and python's `sys.setrecursionlimit` options to allow Edge working. And even worse, exception may happen unexpectedely when Edge is used live rather then being called standalone...

### Steps to reproduce:

It may happen when running Edge on short timeframes, longer timeranges, with custom strategies generating many trades. 

Even with DefaultStrategy: set exchange name: "binance", pair "ETH/BTC", (almost) arbitrary timerange set to default 7d or longer, 1m timeframe. For instance:

```freqtrade edge -r -i 5m --timerange=20190210-20190218```
  
### Relevant code exceptions or logs:

```RecursionError: maximum recursion depth exceeded while calling a Python object```

**Comment by xmatthias** [comment]
We're aware of it - but you found a fix for it :+1: 

have to love it when issues are reported with a fix attached 
Thanks a lot
