### ISSUE TITLE
Add pages from https://www.freqtrade.io into git repository

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1606]
@xmatthias Would you place pages from https://www.freqtrade.io into git repository,

There are some typos there I'd like to fix.

**Comment by xmatthias** [comment]
they are - it's running on readthedocs.io - built from the /docs/ folder within this repository, so to be honest - you fixed a few typos already ....

**Comment by hroff-1902** [comment]
Not all of them, as I see. For example, if you look at the site's menu, you'll find "Sanbox testing" which should be fixed. But it's not grepped out in the docs/.

**Comment by xmatthias** [comment]
the titles on the left are in `mkdocs.yml` in the root directory ...

**Comment by hroff-1902** [comment]
> the titles on the left are in `mkdocs.yml` in the root directory ...

Aha, okay, closing it, sorry.

**Comment by xmatthias** [comment]
No worries, happy to help you help the project :+1:
