### ISSUE TITLE
A command to prevent the bot to execute buy (/stopbuy)

### ISSUE THREAD

**Issue by mishaker** [freqtrade/freqtrade#1607]
Comes handy when you encounter some reason you want to stop the bot but dealing with currently open trades. sell should be activated but no more buy ...

**Comment by xmatthias** [comment]
you can set max_open_trades to 0 and reload the configuration ... so the bot will "gracefully" stop by selling all open trades according to the respective rules ..

**Comment by mishaker** [comment]
you can also remove all pairs from whitelist then reload the config ;) 
those solutions are not practical when you are outside not having access to your server :/

**Comment by hroff-1902** [comment]
There is another related enhancement to this, also as a safety measure in case when something is wrong with the trades initiated by the bot or as a general safety measure -- close all open or partially filled orders and/or close the positions at graceful exit. So simply command the bot to exit and it will return all positions to zeros.

**Comment by xmatthias** [comment]
I'm not saying this command would not be usefull - just pointing out alternatives we currently would have.

@hroff-1902 
well that's `/forcesell all` ... and then /stop

**Comment by hroff-1902** [comment]
> I'm not saying this command would not be usefull - just pointing out alternatives we currently would have.
> 
> @hroff-1902
> well that's `/forcesell all` ... and then /stop

Have not known of /forcesell command yet, still studying all the capabilities implemented in the bot... :-)

It should be better */stopbuy*, /forcesell all, /stop in order to prevent opening new trades between /forcesell and /stop, if /forcesell does not stop new buys by itself...
