### ISSUE TITLE
TSL on exchange is buggy

### ISSUE THREAD

**Issue by mishaker** [freqtrade/freqtrade#1608]
```
"trailing_stop_positive":  0.01,
"trailing_stop_positive_offset":  0.011,
```

But the bot will cancel/update the SL on exchange even though the profit is not at 1.1% yet ...

**Comment by xmatthias** [comment]
I'm not certain this is a bug ... 

Remeber that trailing stoploss is not inactive while it's below the offset - it's just at the "regular" `stoploss` value.

Assuming you have a `stoploss` of -5% ... that means that as soon as it has the bot has 0.1% profit, it'll "move" the stoploss to -4.9% ... and so on.
Once the trade is at 1.1% profit (`trailing_stop_positive_offse` you set above), then the stoploss is moved "closer" to the position (-1% in the above case), so it'll jump from -3.9% to 0.1%.

This should be visible at the time of the "cancel-stoploss" by looking at `max_rate` - which I assume was slightly higher than the open_rate.

Not saying it can't be a bug, but it can also be intendet behavior.
Would you happen to have some logs + an excerpt for the relevant trade?

**Comment by mishaker** [comment]
oh ! then my bad. 
I thought `"trailing_stop_positive_offset":  0.011`means TSL is not activated till you have at least 1.1% of profit !
