### ISSUE TITLE
Don't compare floats for equality

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1639]
**(Almost) never compare floats for equality...**

I found a few, in the freqtradebot.py:

* `if float(order['filled']) == 0`
* `float(order['remaining']) == 0.0`

Both (at least first, I do not understand the meaning of second comparison yet) should probably be something like:

```val <= 0.0 + (10 ** (-market_precision)) / 2``` (i.e. less then 0.5 satoshi in case of BTC)
or probably ```math.isclose(val, 0.0, abs_tol = (10 ** (-market_precision)) / 2)```

More comparisons of floats for equality should appear in the code, I've seen something suspicious for fees, for example...

In the future the Decimal type with appropriate precision (corresponding to particular currency and market) may be used instead of floats, but that seems to be hard to implement...

P.S.
More in freqtradebot.py:
* `if trade.fee_open == 0 or order['status'] == 'open':`
* `if order['amount'] != new_amount:`
* `if amount != order_amount:`
* `if fee_abs != 0:`

**Comment by xmatthias** [comment]
> float(order['remaining']) == 0.0

This simply assumes that if there is nothing remaining,  ... (whatever comes next).
there is no difference between `float(xxx)==0.0` or `float(xxx) == 0`:
```
>>> 0 == 0.0
True
>>> 0 == float(0.0)
True
```

I also doubt that exchanges fill this small amounts, since all exchanges I've looked at have a "min-lotsize" ([binance](https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule) - which depends on the coin (in binances example, that's 0.00000001 -> 1 Satoshi - so a remaining value of < 0.5 Satoshi should not be possible ... unless i miss something ... ?

**Comment by hroff-1902** [comment]
> > float(order['remaining']) == 0.0
> 
> This simply assumes that if there is nothing remaining, ... (whatever comes next).
> there is no difference between `float(xxx)==0.0` or `float(xxx) == 0`:
> 
> ```
> >>> 0 == 0.0
> True
> >>> 0 == float(0.0)
> True
> ```

Sure. It's not about changing 0.0 --> 0 or 0 --> 0.0 here, not at all about it. It's about rounding errors in floats, especially when values are results of calculation rather than casting of integers or strings into floats. Even trivial calculations. See the example:

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 0.1 + 0.1 + 0.1 == 0.3
False
>>> 
```

> I also doubt that exchanges fill this small amounts, since all exchanges I've looked at have a "min-lotsize" ([binance](https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule) - which depends on the coin (in binances example, that's 0.00000001 -> 1 Satoshi - so a remaining value of < 0.5 Satoshi should not be possible ... unless i miss something ... ?

Simply read 0.5 of min-lotsize instead of 0.5 satoshi above, okay.

The point is that instead of getting 0,0000000000000000 which should be ideally equal to 0 or 0.0 as your test suppose, you can get 0.0000000000000000000321 as the float value simply as a result of a trivial math operation (as on the example above), simply somewhere inside ccxt when they multiply a quote currency amount by price in their unified API, whatever, and your test for equality will fail where you expect strict zero.

Look at the last appearences I found -- with amount, You calculate the value in the bot. And *sometimes* (quite often) you won't obtain true in the cases when it should be true because of rounding errors and accumulated error in the float vars.

**Comment by hroff-1902** [comment]
Example 3 ("equal" values are obtained in different ways):

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 0.3 - 3 * 0.1
-5.551115123125783e-17
>>> 0.3 - 0.1 - 0.1 - 0.1
-2.7755575615628914e-17
>>> 
```
If you compare them for equality, you won't get True.
