### ISSUE TITLE
Telegram RPC to inform about stoploss_on_exchange trade

### ISSUE THREAD

**Issue by mikequant** [freqtrade/freqtrade#1653]
When in config you have stoploss_on_exchange enabled and telegram enabled, once stoploss is hit, then there will be no message in telegram. 

However, when bots buys or sells with roi or stoploss order, then you will get a message. So it would be nice to close this gap in rpc module.

**Comment by xmatthias** [comment]
Great find, thanks a lot for reporting :+1: 

it should work with the latest develop version.
