### ISSUE TITLE
no Telegram Status Table update

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#1658]
Python Version: 3.6.7
    CCXT version: 1.18.347
    Branch: Master

## Step 3: Describe the problem:

the status table on Telegram is "static", showing same values. I was relaoding the config and the values being updated. Otherwise the values are not changing.

PS: just seen that the same porblem is with the "performance" - same values if checking several times after same waiting period, static ...

### Relevant code exceptions or logs:

no error message

**Comment by Prossi79** [comment]
I have solved the problem - seems to be a bug:

when I change the ask strategy to "false" it is working, before I was running on true

    "ask_strategy":{
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 10

**Comment by xmatthias** [comment]
so order_book does impact the telegram reporting messages ... ? that's surely not how it should be ...

**Comment by Prossi79** [comment]
yes, for sure not ... can you reproduce this error?

**Comment by xmatthias** [comment]
yes - it happens because get_ticker is never called when orderbook is on.
