### ISSUE TITLE
Bot crashes due to sort key not being populated in ticker data

### ISSUE THREAD

**Issue by iuvbio** [freqtrade/freqtrade#1662]
Experienced on Bittrex. Bot crashes when using VolumePairList and the given sort key is not populated in the ticker data for a given pair. I'm almost certain this is because of some new pair on Bittrex where `quoteVolume` is not populated (yet), since it happened suddenly without any code change and only on Bittrex.

### Relevant code:
```python
tickers = [v for k, v in tickers.items()
           if len(k.split('/')) == 2 and k.split('/')[1] == base_currency]
sorted_tickers = sorted(tickers, reverse=True, key=lambda t: t[key])
```

If `t[key]` is not populated the list cannot be sorted, resulting in a fatal exception.

**Comment by xmatthias** [comment]
Great find - Thanks for fixing :+1:
