### ISSUE TITLE
Installation using install setup.sh and requirements.txt fails for Mac.OS

### ISSUE THREAD

**Issue by dt2555** [freqtrade/freqtrade#1675]
## Step 2: Describe your environment

  * Mac OS Mojave (Version 10.14.1)
  *Python Version: Python 3.7.2
  * CCXT version: 1.18.368
  * Branch: Master
  * Last Commit ID: e6bfedb58bc6caec84e453e9f5b98a33fa3d152b (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

*The installation is not working with either the install.sh scrip or by installing the required dependencies on requirements.txt. 

### Steps to reproduce:

  1. Created a virtual env in anaconda envs folder.
  2. Cloned the repo into the site-packages portion of that folder.
  3. Conda installed scipy, numpy, and pandas successfully.
  4. Removed scipy, numpy, and pandas from requirements.txt.
  5. Ran $ ./setup.sh --install. It failed with the error below.
  6. pip installed -r requirements.txt. It failed with a nearly identical error to the one below

  
### Observed Results:

  * The installation failed. It seems to have something to do with the numpy module, but the version is up-to date and displayed in the env. 
  * Expected the installation to succeed. 

### Relevant code exceptions or logs:

  ```
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from utils_find_1st/find_1st.cpp:4:
    In file included from /anaconda3/envs/HFT/lib/python3.7/site-packages/freqtrade/.env/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /anaconda3/envs/HFT/lib/python3.7/site-packages/freqtrade/.env/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
    In file included from /anaconda3/envs/HFT/lib/python3.7/site-packages/freqtrade/.env/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:
    /anaconda3/envs/HFT/lib/python3.7/site-packages/freqtrade/.env/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it with " \
     ^
    2 warnings generated.
    g++ -bundle -undefined dynamic_lookup -L/anaconda3/envs/HFT/lib -arch x86_64 -L/anaconda3/envs/HFT/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/utils_find_1st/find_1st.o -o build/lib.macosx-10.7-x86_64-3.7/utils_find_1st/find_1st.cpython-37m-darwin.so
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'g++' failed with exit status 1
    
    ----------------------------------------
Command "/anaconda3/envs/HFT/lib/python3.7/site-packages/freqtrade/.env/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/v5/33wc7g317zld5v6hmryw51w00000gn/T/pip-install-s3fh2fdz/py-find-1st/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/v5/33wc7g317zld5v6hmryw51w00000gn/T/pip-record-r_gj54xc/install-record.txt --single-version-externally-managed --compile --install-headers /anaconda3/envs/HFT/lib/python3.7/site-packages/freqtrade/.env/include/site/python3.7/py-find-1st" failed with error code 1 in /private/var/folders/v5/33wc7g317zld5v6hmryw51w00000gn/T/pip-install-s3fh2fdz/py-find-1st/
  ```

**Comment by xmatthias** [comment]
What's the OS you're on? 
That's an important info for problems with the installation.

**Comment by dt2555** [comment]
My apologies. I updated the post... @xmatthias

**Comment by mishaker** [comment]
`open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` solves the problem. 
it is Mojave problem (new mac OS). install the headers as mentioned above then retry the install.

**Comment by dt2555** [comment]
That worked! If I may ask, how did you diagnose the problem? It was quite the source of frustration for me. @mishaker

**Comment by imjonathan** [comment]
install instructions for missing headers here:
https://donatstudios.com/MojaveMissingHeaderFiles

**Comment by xmatthias** [comment]
i'm going to close this as i think the issue was answered.

Also, installation seems to work "easily" now, since github actions also test on MacOS.
