### ISSUE TITLE
ImportError: libta_lib.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xaviermiss** [freqtrade/freqtrade#1676]
## Step 1: Have you search for this issue before posting it?
Yes but did not found.

## Step 2: Describe your environment

  * Python Version:3.6 (`python -V`)
  * CCXT version: 1.18.368 (`pip freeze | grep ccxt`)
  * Branch: Develop
  * Last Commit ID: bdc0134e88b419bf409ce77ed7f35cd98d4c3d09 (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:
No error during the installation.
When I launch Freqtrade:
python3.6 ./freqtrade/main.py -c config.json

I obtain the following issue:
  ```
freqtrade$ python3.6 ./freqtrade/main.py -c config.json
Traceback (most recent call last):
  File "./freqtrade/main.py", line 14, in <module>
    from freqtrade.freqtradebot import FreqtradeBot
  File "/home/xavier/freqtrade/freqtrade/freqtradebot.py", line 20, in <module>
    from freqtrade.edge import Edge
  File "/home/xavier/freqtrade/freqtrade/edge/__init__.py", line 16, in <module>
    from freqtrade.optimize import get_timeframe
  File "/home/xavier/freqtrade/freqtrade/optimize/__init__.py", line 11, in <module>
    from freqtrade.optimize.default_hyperopt import DefaultHyperOpts  # noqa: F401
  File "/home/xavier/freqtrade/freqtrade/optimize/default_hyperopt.py", line 3, in <module>
    import talib.abstract as ta
  File "/home/xavier/freqtrade/.env/lib/python3.6/site-packages/talib/__init__.py", line 43, in <module>
    from ._ta_lib import (
ImportError: libta_lib.so.0: cannot open shared object file: No such file or directory
  ```

How can I solve this issue

Thanks
Xavier

**Comment by xmatthias** [comment]
Ta-lib (the python module) is only a wrapper around the C module.

You need to install that module - [here](https://www.freqtrade.io/en/latest/installation/#1-install-ta-lib) is the documentation on how to do that manually.
please don't use `apt-get install ta-lib` or similar - since that has a problem with precision of bitcoin.

**Comment by mishaker** [comment]
@xaviermiss how did you try to install ? if you used `./setup.sh` ta-lib would have been installed for you beforehand.

**Comment by iuvbio** [comment]
I think he has intalled it, I had the same issue in the beginning.

First check whether it's been installed correctly with `ls -la /usr/local/lib`. If the ta_liv files are there, try adding usr/local/lib to your library path like this `export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH`

**Comment by xaviermiss** [comment]
Hi all,

First thank you very much for all your answers.
@xmatthias and @mishaker : I installed Freqtrade using the ./setup.sh script. talib were well installed.
@iuvbio : it worked with your command line.

Thank you again
C u 
Xavier

**Comment by Mad-Kingu** [comment]
Making path permanent: 

They are configuration files. One way:
1.     Open a terminal window using Ctrl+Alt+T
2.     Run the command gedit ~/.profile
3.     Add the line
4.     export PATH=$PATH:/media/De\ Soft/mongodb/bin
5.     to the bottom and save
6.     Log out and log in again

Link: https://askubuntu.com/questions/500775/permanent-path-variable
