### ISSUE TITLE
Improving Telegram messages

### ISSUE THREAD

**Issue by mishaker** [freqtrade/freqtrade#1678]
The "None" lines should be removed as they take space without any added value: 

<img width="196" alt="Screen Shot 2019-03-18 at 4 48 52 PM" src="https://user-images.githubusercontent.com/939309/54543422-edcf7500-499d-11e9-84d1-d1c09a210833.png">

three additional lines should be added: 

- stoploss value (and %): 0.002 (-0.02)
- amount spent in quote currency (i.e. position size). it can be placed between parentheses in front of the amount: 50 (0.1 ETH) 
- Winrate and expectancy in case Edge is enabled: Winrate: 60%, Expectancy: 2.4

modification suggestion:
"Trade ID: 1" can be converted to "Trade ID: 1 (open since 5 hours ago)". thus the line "open since" can be removed.

**Comment by xmatthias** [comment]
> in case Edge is activated: 0.002 (-0.02)

I don't understand this part. stoploss is stoploss - not sure why it should matter if edge is enabled and setting the stoploss or not ...

**Comment by mishaker** [comment]
cause actually the only reason your stoploss (in terms of %) can change is Edge being enabled. but I am not against including it anyway (Edge or not)

**Comment by xmatthias** [comment]
nope, trailing stoploss would change it as well.

**Comment by mishaker** [comment]
oops ! right !

**Comment by xmatthias** [comment]
well it should, unless you buy and it only moves down from there :laughing:

**Comment by mishaker** [comment]
that never happened to me :D

**Comment by mishaker** [comment]
also winrate and expectancy in case Edge is enabled. I'll update the issue.

**Comment by xmatthias** [comment]
None of these 2 are captured with the trade - why send them via telegram if it's not important enough to capture it in the database ... ?

**Comment by mishaker** [comment]
good point ... 
maybe we should add a command `/edge`so that we can see pairs selected by edge as well as winrate and expectancy of each ?

**Comment by xmatthias** [comment]
I guess #1707 in combination with #1698 solve this issue ...

feel free to reopen if not
