### ISSUE TITLE
freqtrade configuration problem  

### ISSUE THREAD

**Issue by bulentongun** [freqtrade/freqtrade#1682]
Hi guys, 
I have encountered this problem, and looked around a lot but didn't manage to solve it. I have changed the main.py but this time it told me that "No module named 'freqtrade.logger'".
So i reload the old main.py. And got this message again. Can someone help me? 

![Screenshot from 2019-03-20 19-34-18](https://user-images.githubusercontent.com/2774546/54702059-31b1ae00-4b47-11e9-8fc5-8e508c3b41ff.png)

**Comment by mishaker** [comment]
could you include your `config.json` file here ? 
**NOTE:** Don't forget to remove your exchange key and secret

**Comment by xmatthias** [comment]
There seems to be a error in the config.json - line 4... according to the error, anyway.

**Comment by hroff-1902** [comment]
> could you include your `config.json` file here ?
> **NOTE:** Don't forget to remove your exchange key and secret

That's why we should force users (in the docs, as a 'standard' approach to establish the user configuration) to use multiple configuration files in their installations, keeping the keys in the separate configuration file(s) that should not be published...

**Comment by bulentongun** [comment]
Thanks for support guys. 
Here it is; 
[XYconfig.txt](https://github.com/freqtrade/freqtrade/files/2990978/XYconfig.txt)

**Comment by xmatthias** [comment]
You have a typo in your pairlist - the "f" after ETC/BTC needs to move ...

``` json
   "pair_whitelist": [
            "ETH/BTC",
            "LTC/BTC",
            "ETC/BTC",f
            "DASH/BTC",
            "ZEC/BTC",
            "XLM/BTC",
            "POWR/BTC",
            "ADA/BTC",
            "XMR/BTC"
        ],
```

after removing the `f` - the bot starts with this configuration :+1:

**Comment by bulentongun** [comment]
Hi 

> You have a typo in your pairlist - the "f" after ETC/BTC needs to move ...
> 
> ```json
>    "pair_whitelist": [
>             "ETH/BTC",
>             "LTC/BTC",
>             "ETC/BTC",f
>             "DASH/BTC",
>             "ZEC/BTC",
>             "XLM/BTC",
>             "POWR/BTC",
>             "ADA/BTC",
>             "XMR/BTC"
>         ],
> ```
> 
> after removing the `f` - the bot starts with this configuration 
> 
> Edit: github highlights the f very nicely ... which kindof makes my description a duplicate

Hi : ) 
Original config.json file i use does not have this 'f'. It probably happened when i was editing my binance keys.

**Comment by hroff-1902** [comment]
@bulentongun,

Do you have same problem with configuration file you attached (with exactly same content without additional edits, with `-c XYconfig.txt` in the command line instead of `-c ./config.json`)?

**Comment by bulentongun** [comment]
No hroff-1902. Here is the exact one i use to configure. 
[ORIGINALconfig.txt](https://github.com/freqtrade/freqtrade/files/2991187/ORIGINALconfig.txt)

**Comment by hroff-1902** [comment]
So if it works fine with ORIGINALconfig.txt, simply use that config file.

**Comment by bulentongun** [comment]
No it does not work. It gives this error >>>

![54702059-31b1ae00-4b47-11e9-8fc5-8e508c3b41ff](https://user-images.githubusercontent.com/2774546/54742799-68cda100-4bd3-11e9-9528-322bb0c12851.png)

**Comment by mishaker** [comment]
>That's why we should force users (in the docs, as a 'standard' approach to establish the user configuration) to use multiple configuration files in their installations, keeping the keys in the separate configuration file(s) that should not be published...

@hroff-1902 100% agreed !

**Comment by bulentongun** [comment]
I reinstalled all and it worked all this time. Thank you guys,
