### ISSUE TITLE
No currency pairs in whitelist

### ISSUE THREAD

**Issue by xaviermiss** [freqtrade/freqtrade#1704]
## Step 1: Have you search for this issue before posting it?

Yes !

## Step 2: Describe your environment

  * Python Version: 3.6.7 (`python -V`)
  * CCXT version: 1.18.372  (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: c8617e70a87cc2835738d5d2bad0cd46dc2e9d68 (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

Freqtrade is well launched but tells me some hours later:
'2019-03-20 09:22:58,649 - freqtrade.freqtradebot - WARNING - Unable to create trade: No currency pairs in whitelist'

Here is what is specified in my configuration file:
        "pair_whitelist": [
            "BTC/USDT"
        ],

When I launch the bot, telegram:
'Searching for USDT pairs to buy and sell based on StaticPairList: ['BTC/USDT']'

So I conclude that a currency pair is well configured....

Do you identify what I could have done wrong ?

Thank you
Regards
Xavier

**Comment by xmatthias** [comment]
how does your configuration look like?
edge on or off?
please run `/status table` or `/status` on telegram - maybe the bot has a position open for BTC/USDT?

**Comment by mishaker** [comment]
if edge is on, then probably we should enrich that warning

**Comment by xmatthias** [comment]
I think Edge warns itself when it removes them all ... but the log is kinda minimalistic ...

**Comment by xaviermiss** [comment]
Dear @xmatthias ,

No, edge is not enabled.

Here is my configuration (I am testing the soft, not strategies nor timers therefore values of the configuration are not customized):

Thank you very much
Xavier

`{
    "max_open_trades": 10,
    "stake_currency": "USDT",
    "stake_amount": 0.05,
    "fiat_display_currency": "USDT",
    "ticker_interval" : "15m",
    "dry_run": true,
    "trailing_stop": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy":{
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 9
    },
    "exchange": {
        "name": "binance",
        "key": "XXX",
        "secret": "YYY",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": false
        },
        "pair_whitelist": [
            "BTC/USDT"
        ],
        "pair_blacklist": [
            "ETH/USDT"
        ]
    },
    "experimental": {
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "capital_available_percentage": 0.5,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "XXX",
        "chat_id": "YYY"
    },
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
`

**Comment by hroff-1902** [comment]
As I see from the code, this message ("Unable to create trade: No currency pairs in whitelist") is issued every time after positions are open for all pairs in the whitelist at next throttling iteration. So if you have only one pair, this message will be issued after buying that pair. Is it really as intended? ('Cause, yes, no actually pairs in whitelist since a pair is removed from the whitelist when it has open position...)

**Comment by xaviermiss** [comment]
@hroff-1902 ,
You are right.
I tested by adding a second pair and the message only shows up when there are two open positions.
Therefore it does not seem to be an issue to trade but at most a not-easy-to-understand message.

Thank you very much

**Comment by hroff-1902** [comment]
@xaviermiss 
I prepared a small fix for it in my clone repository, could you test it in your environment before I push a new PR to the main repo?

```
git clone git@github.com:hroff-1902/freqtrade.git
git checkout fix_1704
```

There shall not be a DependencyException in case of empty whitelist and the message is also changed to be less confusing...

**Comment by xaviermiss** [comment]
> 
> 
> @xaviermiss
> I prepared a small fix for it in my clone repository, could you test it in your environment before I push a new PR to the main repo?
> 
> ```
> git clone git@github.com:hroff-1902/freqtrade.git
> git checkout fix_1704
> ```
> 
> There shall not be a DependencyException in case of empty whitelist and the message is also changed to be less confusing...

Hi,
I installed it but it gives me the folowing output when all pairs have open positions:
'''
2019-04-02 09:02:05,558 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again..
2019-04-02 09:02:09,841 - freqtrade.freqtradebot - INFO - No currency pair left in whitelist, no more trade can be created.
2019-04-02 09:02:09,841 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again..
2019-04-02 09:02:14,841 - freqtrade.freqtradebot - INFO - No currency pair left in whitelist, no more trade can be created
'''

**Comment by hroff-1902** [comment]
> Is that the output you wanted ?

Sorry for silence,
Yes, but that was a temporary induced error in my intermediate implementation...

Now that my failed code is fixed and your original issue is finally resolved, fix was merged into the develop branch. That's why @mishaker closed this issue.

**Comment by Obad94** [comment]
Well, the reason for the error was something else for me, I do trading on the Binance exchange, and today (i.e.13/08/2021) while developing my strategy I noticed this weird error all of a sudden.  Later I saw the announcement [here](https://www.binance.com/en/support/announcement/92a9a5bc0129427f8e9928c9b7b09836) which said Binance is under maintenance for some hours. I ran the code again after the maintenance and it resolved the issue. 

Dear contributors kindly add such kind of functionality that can tackle such a bug. What is the relation of exchange maintenance with the whitelisted pair code? Hope in the future we don't get the same bug again.

**Comment by xmatthias** [comment]
> Dear contributors kindly add such kind of functionality that can tackle such a bug. What is the relation of exchange maintenance with the whitelisted pair code? Hope in the future we don't get the same bug again.

There is no bug with this anymore. Assuming you use volumepairlist, then the pairlist will repopulate latest after "refresh_period" configured (after the downtime ended).

Also - please do not revive old issues. This will send notifications / warnings to people for no reason. Therefore i'll also lock this thread now.
