### ISSUE TITLE
Binance: Stoploss on exchange should support both stoploss types

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#1718]
According to the Binance Docs, the API supports 2 types of stoploss orders:
* STOP_LOSS_LIMIT
* STOP_LOSS

[source](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md) - search for stop_loss

We only support STOP_LOSS_LIMIT - which is (in part) causing #1717.

**Comment by mishaker** [comment]
true but I implemented only stoploss limit because if I remember correctly the stoploss is not supported by CCXT.

**Comment by xmatthias** [comment]
ccxt code disagrees with you:

https://github.com/ccxt/ccxt/blob/a30dfd65704cbf025b39edcedeb3c9482be3fe6e/python/ccxt/binance.py#L788-L793

```python
        elif (uppercaseType == 'STOP_LOSS') or (uppercaseType == 'TAKE_PROFIT'):
            stopPriceIsRequired = True
        elif (uppercaseType == 'STOP_LOSS_LIMIT') or (uppercaseType == 'TAKE_PROFIT_LIMIT'):
            stopPriceIsRequired = True
            priceIsRequired = True
            timeInForceIsRequired = True
```

**Comment by mishaker** [comment]
@xmatthias pay attention however to stoploss without limit. as explained in #1717 stoploss without limit is risky in a sense that if there is no ask (volume 0) in front of the order then the engine matches your order with the first shitty ask (say 20% below the last best ask). it happens a lot in alts as 0 volume is not rare. I would not personally use stoploss without limit.

**Comment by xmatthias** [comment]
After looking at this more in detail i'll close this.

While the binance API supports `STOP_LOSS` as order-type - there is currently no market which actually supports it, and the UI does not support it either. 
So implementing this type of stoploss for binance will not make any sense.

Tested using:
```
[p for p, v in ct.load_markets().items() if 'STOP_LOSS' in v['info']['orderTypes']]
```
