### ISSUE TITLE
Stoploss order unable to be filled due to too low notional amount

### ISSUE THREAD

**Issue by iuvbio** [freqtrade/freqtrade#1723]
I've encountered a problem that my stoploss on exchange order is unable to be filled, because after the price dropping, the minimum order amount is not reached anymore.

Example:
Minimum order size is 0.05 BTC
Buy 1 ETH for 0.05 BTC and set stoploss at 5%
Price drops to 0.475 -> stoploss is triggered
Can't execute order, because minimum order size is not reached.

These are obviously made up values, but this happened to me with ENJ/BTC on Binance.

My proposed solution would be to verify at order creation whether the minimum order size is met including the stoploss.

**Comment by mishaker** [comment]
yes it is a problem and yes your proposition is the right one !

**Comment by xmatthias** [comment]
Honestly, this is possible with dynamic-whitelist - setting ` "precision_filter": true`.

We maybe should add a similar check to static-pairlist, so it can warn you on startup (or at least document on how to create your pairlists ...)

**Comment by iuvbio** [comment]
As it is at the moment, the precision filter will not prevent this (I had it turned on in the case of ENJ/BTC). It will only kick out the pair if stoploss would be equal to stoploss limit. Unless you mean that it should be added there? And yes, it should be added for static pairlist as well, whenever there is any stoploss given (so pretty much always)

**Comment by mishaker** [comment]
@xmatthias ha? I don't get it :/ actually stoploss is calculated dynamically, the thing is that at the moment we create the buy order we should check also if stoploss satisfies the filter otherwise we don't buy. is it possible with dynamic-whitelist ?

**Comment by xmatthias** [comment]
Well my understanding of that  is that every low-value pair (where value is too low to create a stoploss) is thrown out of the pairlist.

Stoploss is dynamic based on price - so maybe a small offset should be created.

I do however agree that we should check for that before buying - price could drop between list generation and buying - so it's possible we can't generate the stoploss.

I would not implement that filtering in Staticpairlist ... but maybe it's worth extracting this from VolumePairList and calling it from Static, Dynamic and edge, and once again before buying (but by passing in the buy-price...).

Relevant code: 
https://github.com/freqtrade/freqtrade/blob/ecd75e43b0a2e605a1a83770468cef3c657d4b50/freqtrade/pairlist/VolumePairList.py#L79-L92

**Comment by iuvbio** [comment]
Yes, but this doesn't really have anything to do with low value pair or not, more with the order size. Yes, it is much more likely to happen with a low value coin, where a small percentage drop in price significantly changes the notional amount, but it might just as well happen with BTC/ETH, if your initial order size was just above the minimum order size.

**Comment by xmatthias** [comment]
I think this is related (if not exactly the same) than #1702 ...

**Comment by iuvbio** [comment]
No, it's completely unrelated.. #1702 can indeed be solved by the precision filter. This here depends purely on the order size, so your stake amount in connection with the price.

Basically, if your stake amount is just above the minimum order order size and then the price drops, the stop loss order size is below the required minimum. This is the log:

```bash
2019-04-02 23:44:37,557 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Could not create stop_loss_limit sell order on market ENJ/BTC.Tried to sell amount 11.0 at rate 4.462e-05 (total 0.00049082).Message: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
```

The minimum order value is 0.001 BTC (see [here](https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule)). This error is thrown on every iteration. The pair can also not be forcesold, because of the same problem. I'll have to buy some more ENJ to then sell everything.

I still wonder how this could have happened though.. my stake amount is 0.002 BTC, so after a 5% price drop the order value should still be above the minimum..

**Comment by mishaker** [comment]
Agreed ! And the solution is in your proposition.  At the moment of order
creation, stoploss should be checked too. If it doesn’t meet filters then
buy order should be skipped.

**Comment by iuvbio** [comment]
So, I checked my trade history on Binance to find out how this could even have happened.. it was due to a partially filled order.. the rest of the order was probably cancelled because of timeout. This is the trade:
![image](https://user-images.githubusercontent.com/13389526/55575097-5cd2fa80-570e-11e9-922d-04aaa4683357.png)

This means that my proposed fix would not solve this.. Even including stoploss the order value was still above the minimum value. Do you have any idea for another way to prevent this from happening?

**Comment by mishaker** [comment]
when did this happen ? I think it is related to that nasty bug (real amount not updated) that we fixed few days ago.

**Comment by xmatthias** [comment]
it's not if it's a partial fill...

there's really nothing we can do i think - try using another ordre type maybe - so it will have to fill all - a partial fill may  leave you with the exactly 1 notional unit - so if price drops by 1 - it can't sell neither in stoploss noar in regular sell mode.

**Comment by iuvbio** [comment]
Yea that's what happened.. I guess you're right, can't really be prevented. Different order type you mean market order? That's not an option.. Or you mean time_in_force? I guess that'd be possible, but only on Binance at the moment.

**Comment by xmatthias** [comment]
time_in_force (sorry, my bad) 

another way could be to increase timeouts ... maybe ...

yes, only on binance for now ...

**Comment by mishaker** [comment]
I use FOK, full or kill, at least you are sure of your order

**Comment by iuvbio** [comment]
I'll close this one, as the best options to handle this were mentioned.
