### ISSUE TITLE
How to update the project?

### ISSUE THREAD

**Issue by bulentongun** [freqtrade/freqtrade#1732]
## Step 1: Have you search for this issue before posting it?

Yes. 

## Step 2: Describe your environment

  * Python Version: Python 3.6
 And i am using Atom 
  
## Step 3: Describe the problem:

There is no problem but i need to be sure. 

Would someone please let me know how to update the new versions of freqtrade codes without loosing the changes we have made in our codes (in config.json etc.)

 

_*** Sorry for the jargon or if it is a rookie question :) But i am a newbie and do not want to loose things i have changed. So need to be sure.**_

**Comment by hroff-1902** [comment]
Just backup your stuff (maybe simply by saving the app dirs in a separate archive) and you won't loose anything... 

Stop (terminate) temporary the bot first so that DB will be in the consistent state during backup process (just imho)...

What OS are you using? Do you use docker configuration? How have you installed FT and how are you going to update it?

**Comment by bulentongun** [comment]
I am using Ubuntu on Mac with Parallels Desktop, 
I don't know what is docker conf: ) 
I  don't have any problem about configuring other things. Backtest, change currencies, add strategies etc.  But don't know how to merge the old codes on my desktop and the changed ones on github. I am also new to Atom.io and git pull, push stuff : )
Thanks,

**Comment by bulentongun** [comment]
btw, i am really appreciated for this project. it is really perfect +

**Comment by xmatthias** [comment]
if it's a git folder - you can check if there are changes by using `git status`.
if there are not, simply run `git pull`.

If there are, it becomes tricky as it depends what you changed...

**Comment by hroff-1902** [comment]
I am also new to ... git pull, push stuff : )

https://www.mediawiki.org/wiki/Git_for_dummies

**Comment by iuvbio** [comment]
> If there are, it becomes tricky as it depends what you changed...

Not too tricky though, just `git pull` and if there are merge conflicts resolve them by accepting either your changes or the ones that you pulled (they are marked in the code).

If you want to contribute, I'd recommend forking the project. What I do is always keep the `develop` branch of my fork up to date with with `upstream` and implement any changes in a new branch. That way it will be easier for you to create PRs as well.

**Comment by xmatthias** [comment]
Going to close this as i think it has been answered.

Feel free to reopen if you think differently
