### ISSUE TITLE
Bot stops outputting in terminal after a while

### ISSUE THREAD

**Issue by a1437** [freqtrade/freqtrade#1739]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: _3.6.8____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _python freqtrade\main.py
  2.  wait, 30min - 1hr
 
  
### Observed Results:

At my terminal, freqtrade starts writing:

2019-04-05 22:27:13,927 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again..

this at regular intervals. But after like 30 mins, it stops writing anymore, and just stays there with a blinking underscore (" _ ").
Is this normal behavior? or is my bot getting stuck.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
What is the output right before the blinking underscore?

does the bot still respond to telegram messages?

**Comment by hroff-1902** [comment]
You might have pressed Ctrl+S in the terminal, for example.
Give us some more info. Has it repeated again?

**Comment by xmatthias** [comment]
I'm going to close this now for inactivity.

feel free to reopen if you still experience this issue.
