### ISSUE TITLE
Telegram message limit

### ISSUE THREAD

**Issue by vpotap** [freqtrade/freqtrade#1745]
* Python Version: 3.6.5
  * CCXT version: 1.18.435
  * Branch: Develop
  * Last Commit ID: 4a6c8f3cb27d33c24d4baefa33ebc177c5e742e4
  
Don't get any output for telegram  /balance command 
in console get 
WARNING - Telegram NetworkError: Message is too long! Trying one more time.
WARNING - TelegramError: Message is too long! Giving up on that message.

**Comment by hroff-1902** [comment]
The limit for Telegram messages is, if I remember it properly, 4096 symbols. This can be reached in case of less than 40 currencies in the user account on exchange with balance large enough to be printed in the message (small balances are ignored in the output).

Maybe the bot should send a separate message for each currency. Or other kind of pagination of the balance data should be implemented.

**Comment by xmatthias** [comment]
I think if we know the limit (i did not), we can simply split it when we reach the limit - so we would send 2 messages, not 50 (in case of 50 currencies...)

**Comment by hroff-1902** [comment]
https://core.telegram.org/method/messages.sendMessage
(may require VPN to access in some countries)
states: "Current maximum length is 4096 UTF8 characters"
