### ISSUE TITLE
Question: Position and order management

### ISSUE THREAD

**Issue by CooleRnax** [freqtrade/freqtrade#1756]
Hello, I'm new to freqtrade. I have read docs, but i'm still confused.
I have a strategy that buys based on % from account value.
And sell based on % of asset in the wallet using target limit order.
I don't get how I can implement this.
I don't see any position and order management.

Does freqtrade support such complex strategies?

**Comment by xmatthias** [comment]
position / order management is currently not exposed to the strategy - so the strategy cannot control this part yet.

**Comment by hroff-1902** [comment]
Closing it since the question was answered and there is no more activity here. Of course, the position/order management is one of the major thigs TODO in the future versions.
