### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#1774]
Step 4 (Run the Docker image): 

docker: Error response from daemon: Mounts denied: 
The path /etc/localtime
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERRO[0000] error waiting for container: context canceled 
sdtyfug:freqtrade nielsschmidtmartinez$

**Comment by gitgitgat** [comment]
went to docker -> preferences -> file sharing and '/etc/localtime' is shaded in grey, it cannot be chosen/clicked on

**Comment by gitgitgat** [comment]
trying the other non-docker way.
in step 5. install dependencies, pip3 install -r requirements.txt, the following error:

  Failed building wheel for py-find-1st

and later

Command "/Users/nielsschmidtmartinez/Downloads/GITHUB/.env/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/ht/9_342yln3_16qflfk8x7g1qw0000gn/T/pip-install-qpnidqvk/py-find-1st/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ht/9_342yln3_16qflfk8x7g1qw0000gn/T/pip-record-86felmoj/install-record.txt --single-version-externally-managed --compile --install-headers /Users/user/Downloads/GITHUB/.env/include/site/python3.7/py-find-1st" failed with error code 1 in /private/var/folders/ht/9_342yln3_16qflfk8x7g1qw0000gn/T/pip-install-qpnidqvk/py-find-1st/

tried 'sudo pip3 install --upgrade pip setuptools wheel' and same error from above comes up

**Comment by hroff-1902** [comment]
Hmm, do you see "There is known issue in OSX Docker versions after 17.09.1..." in the installation docs?
Have you tried the command stated there? How do you run freqtrade in docker?

**Comment by xmatthias** [comment]
Which of the 2 docker-commands did you run?

There is a specific command for MacOS which should work.

```
docker run --rm -e TZ=`ls -la /etc/localtime | cut -d/ -f8-9` -v `pwd`/config.json:/freqtrade/config.json -it freqtrade
```

Regarding the 2nd problem, it's related to #1675.

Try running `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` if you're on Mojave as stated [here](https://github.com/freqtrade/freqtrade/issues/1675#issuecomment-474070861)

**Comment by gitgitgat** [comment]
> Hmm, do you see "There is known issue in OSX Docker versions after 17.09.1..." in the installation docs?
> Have you tried the command stated there? How do you run freqtrade in docker?

I'll have a look at it, from terminal, like stated in the line, might have already been answered in following line. thanks

**Comment by gitgitgat** [comment]
> Which of the 2 docker-commands did you run?
> 
> There is a specific command for MacOS which should work.
> 
> ```
> docker run --rm -e TZ=`ls -la /etc/localtime | cut -d/ -f8-9` -v `pwd`/config.json:/freqtrade/config.json -it freqtrade
> ```
> Regarding the 2nd problem, it's related to #1675.
> 
> Try running `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` if you're on Mojave as stated [here](https://github.com/freqtrade/freqtrade/issues/1675#issuecomment-474070861)

Okay, second problem was fixed, thanks.
