### ISSUE TITLE
List of further hyperopt enhancements

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1775]
TODOs, for discussion/evaluation, as I see it:

* [x] --print-all option which allows to see all hyperopt results in the optimization path, not only the best ones.
* [x] Add the --refresh-pairs option to hyperopt. Now it's available for backtesting and edge commands only.
* [x] -j N option to set the number of workers. With the same semantics as joblib.parallel uses: -1 means joblib will automaticaly define proper number of workers to utilize all CPUs.
* [ ] The following is probably the most important drawback in hyperopt: if you restart hyperopt, skopt does not use previously collected results and starts evaluation again from a random point in the parameters hyperspace. Implement fetching the last point from previous results as x0, y0 for skopt to allow it go on from same point it stopped before.
* [x] In addition to the previous question, an option (how to name it? --remove-data? --restart-evals?) can be added that forces skopt to forget, throw away all previous results and restart evals from scratches, again from a random point.
* [x] An option which allows to pass a particular starting point (random_state) to skopt for reproducible results, for testing/development.
* [ ] An option which duplicates results as csv in addition to pickling them. Maybe not all of them (including collected at previous runs), but only those that have been collected during current run of the hyperopt. That would allow to see all the parameters in the hyperspace, explore them, plot the curves, process the points using external utilities and so on...
* [x] An utility that fetches the pickle file with results already collected and export it to csv.
* [x] The debug log message for every evaluation printing current state of the optimization (attributes of the skopt.Optimizer)

-------------

* [x] Prevent freqbot from running multiple instances of hyperopt simultaneously,
* [x] The --min-trades=N option. The points in the optimization path that generate less than N option are to be considered "bad" (with maximal Loss value) and thus be excluded by the optimizer from the optimization path. This prevents the optimization path from descending to points in the hyperspace with small amount (1, 2) of trades. Sometimes (always with default hyperopt after several hundreds of optimization evals) the optimization path descends to the points with small amount of trades, starting optimization of the 'hodl' strategy when no trades (or only small amount of trades) appear instead of optimization of the real target strategy. The current implementation now excludes points with number of trades equal to 0 only.
* [x] --color/--no-color for --print-all. Print best records in green, 'bad' records (with maximal Loss set) in red.

-------------

* [x] Fix SumProfit% value printed by hyperopt (multiply it by 100) so that
`SumProfit% = N_trades * Avg Profit%`
Currently printed value is incorrect.
* [x] Add verification of the ticker data via optimize.validate_backtest_data() (in the same manner it's made in backtesting start()) and log min_date, max_date and interval used -- now it's impossible to determine what time interval is really used by hyperopt, if not specified explicitely in the command line options.
* [x] Add `--print-table` (`--table`?) option, which tabulates printed results (implies --print-all / should require --print-all / can have effect only when --print-all is specified) P.S.: implemented as default output format.

**Comment by xmatthias** [comment]
> if you restart hyperopt, skopt does not use previously collected results and starts evaluation again from a random point in the parameters hyperspace

We do save / reload trials - but yes, we should also save hyperspace options

> In addition to the previous question, an option (how to name it? --remove-data? --restart-evals?) can be added that forces skopt to forget, throw away all previous results and restart evals from scratches, again from a random point.

Both options clearly express what they do - so i have no preference - and i suspect that you'l want to remove previous trials as well ... ? 

Overall: Great job on this! very helpful improvements!

**Comment by hroff-1902** [comment]
> We do save / reload trials - but yes, we should also save hyperspace options

Well, the current behaviour is: you run hyperopt for 100/1000/10000 evals, it creates trials, they are saved. Then you run hyperopt again, past trials are loaded into the trials var, *not passed to the hyperopt*, hyperopt starts again from a new random starting point, generates new 100/1000/10000 evals, they are added to the past trials and saved. Then again -- all past trials are not used by sebsequent runs of the hyperopt.

I thought it works as intended -- the trials in the file are saved for analyzing them by external tools, for example, but with you comment I understand that it's just a serious bug.

**Comment by xmatthias** [comment]
well no - that's not the intend - but i never noticed it either.
it's a pickled file - if it's for "external" usecases it would be csv or json i suppose ...)

**Comment by hroff-1902** [comment]
> well no - that's not the intend - but i never noticed it either.
> it's a pickled file - if it's for "external" usecases it would be csv or json i suppose ...)

Yes, it's a picked file -- picked down from a var and pickled up again to a var. This var is not used in the `generate_optimizer()` and all the stuff beneath it, New trials (results from `generate_optimizer()`) simply appended to it when ready and collected in the loop, saved at the end and are not used at the next run of the hyperopt command,

**Comment by hroff-1902** [comment]
I'll create a proofing example with new --random-state option.

**Comment by xmatthias** [comment]
One thing that jumps my mind with this - if we pass in the pickled results to skopt, we need to be carefull on detecting changes to the hyperopt file.

we should not load previous results if a different space is used ( or different parameters within the same space are used) - but also when something within the space changed since last time - which will be VERY hard to track unless we hash them - but maybe i added a comment so restarting would not be necessary...

**Comment by hroff-1902** [comment]
> One thing that jumps my mind with this - if we pass in the pickled results to skopt, we need to be carefull on detecting changes to the hyperopt file.
> 
> we should not load previous results if a different space is used ( or different parameters within the same space are used) - but also when something within the space changed since last time - which will be VERY hard to track unless we hash them - but maybe i added a comment so restarting would not be necessary...

Exactly, agree. So probably it's better to save the current behavior (start optimization from new random point), BUT remove also all previous trials from the file, they are useless (since the conditions may have changed) AND, additionaly, add a command line option which allows to proceed from previously collected trials...

**Comment by hroff-1902** [comment]
Plus an option for saving results (trials) as csv and/or json, to a file with data/time in the name if the user wants to keep results of every run for later analyzing by external tools...

What do you think?

**Comment by hroff-1902** [comment]
Updated the list with the second bunch of enhancements.

**Comment by hroff-1902** [comment]
Updated the list with the third bunch of enhancements.

**Comment by xmatthias** [comment]
answering to https://github.com/freqtrade/freqtrade/pull/1925#issuecomment-501846262 here as it's not related to that PR at all.

Be very carefull to not waste a lot of time with the hyperopts change you mention in that comment - since you can pass in `--strategy-path ../whatever/`hyperopt is not able to unpickle that class. 

I had that problem for over 2 weeks without solution, simply because strategy is in that case not available in python_path, and hyperopt-unpickle (the one in the new process) is unable to unpickle this, even though the class is available through the Strategy_resolver, so we technically use DefaultStrategy, but we really don't as all functions from there are exchanged with stuff from the custom hyperopt class.

We might be able to get rid of the DefaultStrategy for hyperopt by not having hyperopt be a subclass of backtesting (which is doubtfull at best to begin with) - but i doubt that loading a custom strategy (from acustom location) will be possible for parallel hyperopting

**Comment by hroff-1902** [comment]
Thanks alot for notice! I've forgotten that pickiling problems already,,,

**Comment by xmatthias** [comment]
Inspired by this comment https://github.com/freqtrade/freqtrade/issues/1907#issuecomment-505524849 - i think we may want to add the posibility to select some predefined loss functions (and provide custom ones):

We could extract the current loss function, and the sharp-calculation from the comment to a `hyperopt_loss.py` file (for cleanness more than anything).

We could then start hyperopt using `freqtrade hyperopt --loss legacy` to use the current function, or `freqtrade hyperopt --loss sharpe` for the new function, or `freqtrade hyperopt --loss custom` to read the loss-function from a predefined name in the custom hyperopt class.

This should allow us to easily add new loss-functions should we have ideas (or if someone comes up with an idea ...).

@hroff-1902 what do you think?

**Comment by xmatthias** [comment]
_Partially crossposed from https://github.com/freqtrade/freqtrade/pull/2142#issuecomment-521917486 to avoid cluttering that PR with usefull stuff we will loose once that's merged_

We should think of building a "strategy_from_hyperopt" method ... a first step would be to output the following instead of json / dictionaries ... which will simplify copy/pasting this to a strategy manually (For now).

```
def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
dataframe.loc[
(
 (dataframe['rsi'] < 35) &
(dataframe['fastd'] < 35) &
(dataframe['adx'] > 30) &
(dataframe['plus_di'] > 0.5)
)
, 'buy'] = 1
return dataframe


```

**Comment by hroff-1902** [comment]
> An utility that fetches the pickle file with results already collected and export it to csv.
See #2581 , implemented as `hyperopt-list`, `hyperopt-show` subcommands (no export to csv)

**Comment by Fredrik81** [comment]
I would like to see that win/loss trades are recorded. this is interesting data when searching for good strat.
Thoughts?

**Comment by yazeed** [comment]
> I would like to see that win/loss trades are recorded. this is interesting data when searching for good strat.
> Thoughts?

I have a PR for this in the making, will introduce it soon.

**Comment by yazeed** [comment]
>  The following is probably the most important drawback in hyperopt: if you restart hyperopt, skopt does not use previously collected results and starts evaluation again from a random point in the parameters hyperspace. Implement fetching the last point from previous results as x0, y0 for skopt to allow it go on from same point it stopped before.

Is this still the case with --continue?

**Comment by xmatthias** [comment]
I would think so - #2464 ...

**Comment by Fredrik81** [comment]
There was requests to get csv-file export for hyperopt. Did some work on this (almost ready tbh) but is it something that we want to implement for the hyperopt-list command?

**Comment by hroff-1902** [comment]
> There was requests to get csv-file export for hyperopt. Did some work on this (almost ready tbh) but is it something that we want to implement for the hyperopt-list command?

you can take it if you are interested in it... I was thinking yesterday of possible approach for how this can be implemented: possibly the `--print-csv` option is the best one (for `hyperopt-list` AND `hyperopt`), which will simply print output in csv format instead of default tabular...

**Comment by xmatthias** [comment]
Personally i wouldn't implement it for `hyperopt`. 
using `hyperopt-list` afterwards is very quick (if you need it as csv file) and the data is persisted by default ... so i struggle to see the benefit - and i think the time spent on that might be better spent elsewhere ... 

In addition to that, i assume it'll be a bit more complicated - as in hyperopt all data is not available at once.

**Comment by hroff-1902** [comment]
Printing csv line by line is easier than for tabular format, since we should be guess the length of the columns.

Can be useful in the future for pipelining -- an external tool can then fetch the output as csv and show the table from these data on a html page in real time, Parsing csv is easier than tabular data, it's machine-readable format.

**Comment by xmatthias** [comment]
@hroff-1902  can we close this issue? 

i think the only 2 open issues are csv export (which is available in hyperopt-list - so i think should be ticked) - and the "continuation" issue - which is however seperately tracked as #2898

**Comment by hroff-1902** [comment]
sure,
I'll create the new one with actual tasks if needed
