### ISSUE TITLE
Understanding hyperopt results

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1779]
The docpage on hyperopt contains an example of the hyperopt output:

```
Best result:
   135 trades. Avg profit  0.57%. Total profit  0.03871918 BTC (0.7722Σ%). Avg duration 180.4 mins.
with values:
```

Well:
* What is "0.7722Σ%"?
* 0.7722% of what amount? 0.7722% of stake_amount?
* Why "Avg profit  0.57%" differs from "0.7722%"?
* The "Loss: " value is missing in the example. _(bug in docs)_
* What is that "Loss"? Why it's always positive, even for rows where "Avg profit" is also positive? (for DefaultHyperOpt and default config)

Sorry, I do not understand anything in these results, how to treat them properly...

**Comment by hroff-1902** [comment]
'Loss' -- should be called objective function. Its value is the subject for hyperopt optimization.

Objective function consists of three components:

`Objective = Trade Component + Profit Component + Duration Component`

`Trade Component = 1 - 0.25 * exp(-(trades_count - N) ** 2 / 10 ** 5.8)`
where `N = 600` 
As far as I understand, this function is designed to attract the optimization path to the points in the hyperspace that produce 600 trades. Very smooth function with minimum for points in the hyperspace where number of trades = 600.
Actually this should depend on the timeframe, timerange and the strategy style (many small quick trades a-la scalping or more 'hodl'-styled) but currently it's simply hardcoded.

`Profit Component = max(0, 1 - total_profit / P)`
where `P = 3.0` (3.0%) -- expected max profit. 
This function is 1 for profit=0, >1 if profit is negative and =0 for all points in the hyperspace that generate profit >= P. This is the main component of the objective function.

`Duration Component = 0.4 * min(trades_duration / M, 1)
where `M = 300` (300 minutes) -- so called in the code 'max. trades duration'. Also simply hardcoded.
This function attracts hyperopt optimization path to the points where avg trades duration <= 300 min.

Previously (some months ago) all points in the hyperspace that have trades duration > M obtained the value of MAX_LOSS as (a deliberately large value that excluded them from the optimization path as good points for optimization). I haven't get for now why this code was removed.

For me the 0.4 weight coefficient used here seems to be too agressive. In the experiments with DefaultHyperOpt I obtained better optimization results (more points with interesting values for profit) when 0.4 was changed to 0.1 or even to 0.04. With weighting factor set to 0.4 (as now implemented) hyperopt quite often starts optimizing duration of the trades instead of the main component, the Profit Component...

Actually, all this values should be adjustable in the config and/or command line, Including weight coefficients for components.

**Comment by hroff-1902** [comment]
I would like to see some more details (or historical explainations why it was designed in this way it's designed) from the old members of the team...

**Comment by xmatthias** [comment]
I agree, and it's been long on my secret todo-list (the one in my brain...) to make loss configurable, since 600 is a "random" number depending on the other parameters.

Ideally, we'd configure loss in DefaultHyperopt, so users can override it with their preferences - i'm not sure if the whole function, or just some parameters (weights for the different attribues).

I'm also not sure on the loss-function itself (apart from 600 Trades). It's assigning weights to different parameters, but without transparency, or without any means for the users to easily change this. Maybe i want to optimize on as short as possible trades - or on as many as possible, ... but i currently wouldn't know how to do that.

> Previously (some months ago) all points in the hyperspace that have trades duration > M obtained the value of MAX_LOSS as (a deliberately large value that excluded them from the optimization path as good points for optimization). I haven't get for now why this code was removed.

Can you point me to some old commit to see the code? if i see it i MAY be able to xplain why ...

**Comment by hroff-1902** [comment]
> Ideally, we'd configure loss in DefaultHyperopt

Hmm, brilliant idea. 👍 
In the custom hyperopt, you mean?

**Comment by hroff-1902** [comment]
So, the 'Loss' is the value of the optimization objective function. It's absolute value has no physical or financial meaning...

Then, other values in the example, stated above:
```
Best result:
   135 trades. Avg profit  0.57%. Total profit  0.03871918 BTC (0.7722Σ%). Avg duration 180.4 mins. with values:
```

'Avg profit' is incorrectly multiplied by 100. Because Number of trades * Avg profit shall be = value designated as Σ% (total profit in %).

Here 0.0057...% * 135 = 0.7722Σ%. Avg profit is 0.0057%, not 0.57...%

**Comment by hroff-1902** [comment]
Closing it since there is no more reasons to leave it open.
The readers will be able to find it using the search engine.
