### ISSUE TITLE
load pickle EOFError raised

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#1803]
What could be causing the following error in hyperopts, new dev version:
 

> File "/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "freqtrade/__main__.py", line 15, in <module>
>     main.main(sys.argv[1:])
>   File "/Users/user/Downloads/GITHUB/freqtrade/freqtrade/main.py", line 34, in main
>     args.func(args)
>   File "/Users/user/Downloads/GITHUB/freqtrade/freqtrade/optimize/hyperopt.py", line 350, in start
>     hyperopt.start()
>   File "/Users/user/Downloads/GITHUB/freqtrade/freqtrade/optimize/hyperopt.py", line 274, in start
>     self.load_previous_results()
>   File "/Users/user/Downloads/GITHUB/freqtrade/freqtrade/optimize/hyperopt.py", line 248, in load_previous_results
>     self.trials = self.read_trials()
>   File "/Users/user/Downloads/GITHUB/freqtrade/freqtrade/optimize/hyperopt.py", line 94, in read_trials
>     trials = load(self.trials_file)
>   File "/Users/user/.env/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 598, in load
>     obj = _unpickle(fobj, filename, mmap_mode)
>   File "/Users/user/.env/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 526, in _unpickle
>     obj = unpickler.load()
>   File "/anaconda3/lib/python3.7/pickle.py", line 1083, in load
>     raise EOFError
> EOFError
>

**Comment by gitgitgat** [comment]
also in master version

**Comment by xmatthias** [comment]
it sounds like a problem with your pickle file (it's corrupted) - probably caused by running multiple instances in parallel ...

try to deltee these files:

```
rm user_data/hyperopt_results.pickle
rm user_data/hyperopt_tickerdata.pkl
```

(or one of the 2 - or move them away one by one)

**Comment by hroff-1902** [comment]
exception is in self.read_trials() -- so delete the user_data/hyperopt_results.pickle file

need to think on how to avoid this and allow multiple heperopt running simultaneously (if someone wants it for some reasons)...

**Comment by xmatthias** [comment]
i would simply not support running multiple hyperopt-processes in parallel to be honest ... adding a statement in the documentation ...

it does not make sense, i would rather have 1 hyperopt finish sooner than wait for 4 all day ... at least then it's possible to improve that strategy further ...

**Comment by hroff-1902** [comment]
> i would simply not support running multiple hyperopt-processes in parallel to be honest ... 

Yeap, I also got to it after thinking on possibilities...

> adding a statement in the documentation ...

I'll probably add a file lock on the pickle file or something similar for serializing access to it so that only one instance can be run. Will probably add a command line option for selecting another file (or better the user data directory?)

**Comment by gitgitgat** [comment]
> it sounds like a problem with your pickle file (it's corrupted) - probably caused by running multiple instances in parallel ...
> 
> try to deltee these files:
> 
> ```
> rm user_data/hyperopt_results.pickle
> rm user_data/hyperopt_tickerdata.pkl
> ```
> (or one of the 2 - or move them away one by one)

thanks a lot, that fixed it
