### ISSUE TITLE
Custom Strategy in docker

### ISSUE THREAD

**Issue by vapor99** [freqtrade/freqtrade#1824]
I have searched everywhere I can and would like to know how to use a custom strategy in a docker container.  Currently as a one off container for testing I use:

docker run --rm -v /etc/localtime:/etc/localtime:ro -v `pwd`/config.json:/freqtrade/config.json -it freqtrade

**Comment by xmatthias** [comment]
You're right - that's missing in the docs.

you can use the [backtest example](https://www.freqtrade.io/en/latest/installation/#7-backtest-with-docker) from the documentation and leave out the "backtesting" at the end.

basically 
```
docker run -d \
  --name freqtrade \
  -v /etc/localtime:/etc/localtime:ro \
  -v ~/.freqtrade/config.json:/freqtrade/config.json \
  -v ~/.freqtrade/tradesv3.sqlite:/freqtrade/tradesv3.sqlite \
  -v ~/.freqtrade/user_data/:/freqtrade/user_data/ \
  freqtrade --strategy AwsomelyProfitableStrategy
```

Note that this assumes that `~/.freqtrade/user_data/strategies` exists and contains a strategy called `AwsomelyProfitableStrategy`

**Comment by vapor99** [comment]
Worked great!  Thanks!
