### ISSUE TITLE
Ability to see candles update in terminal

### ISSUE THREAD

**Issue by highwaterr** [freqtrade/freqtrade#1833]
It would be nice to be able to see candles as they update into dataframe. This would help greatly with creating a custom indicator and ensure its working properly. This feature could be turned on/off with "-v", just an idea. Thanks for the time.

**Comment by xmatthias** [comment]
specify "see" ... ? 

you can always print head / tail (probably `.tail()` of the dataframe within the strategy (maybe before returning in `populate_buy_trend()`) - however printing a dataframe to a terminal window will almost never be really usefull, especially once you move past 2/3 addditional indicators.

**Comment by highwaterr** [comment]
I would just like to view the dataframe(specifically the ohlc of the most recent candles, plus new info I’m adding with my custom indicator).

I’ve written a mock version of my custom indicator in jupyter using a .csv file of BTC candle history. Now I need to apply it to freqtrade, and need some sort of visual to confirm it’s doing what I’d like it to.

I personally could not get dataframe.tail() to print from populate_buy_trend,  but I’m also new to python and freqtrade(I have some JS knowledge). With that said I’d appreciate any help so I can start to write my own indicator/strategy.

**Comment by xmatthias** [comment]
A simple `print(dataframe.tail())` does work for me ... ? 

make sure to place it before the return:

``` python
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict):
        dataframe.loc[
            (
              >> whatever condition<<<
            ),
            'buy'] = 1
        print(dataframe.tail())
        return dataframe
```

**Comment by highwaterr** [comment]
I’m sure I was doing something wrong.  Thanks for the quick reply and the patience!

**Comment by xmatthias** [comment]
so it's working now?

**Comment by highwaterr** [comment]
I will have to try after work.  I’ll let you know

**Comment by highwaterr** [comment]
Matthias I got it to work... exactly what I was looking for thanks.  My issue, for whatever reason, was print dataframe from default strat did not work. Using another strategy file worked great.

**Comment by hroff-1902** [comment]
This (quite simple) recipe should probably be cited in the docs (in the FAQ, for example)...
Could be useful for many users and particular code sample is helpful for python- and programming-unexperienced ones,,,
