### ISSUE TITLE
Bittrex does not support market orders.

### ISSUE THREAD

**Issue by fachos** [freqtrade/freqtrade#1842]
2019-05-11 20:04:52,039 - freqtrade - ERROR - Exchange Bittrex does not support market orders.

**Comment by xmatthias** [comment]
You'll need to change your configuration to use limit orders (which is the default anyway).

basically:
```
"order_types": {
    "buy": "limit",
    "sell": "limit",
    "stoploss": "limit",
    "stoploss_on_exchange": False,
    "stoploss_on_exchange_interval": 60
},
```

**Comment by fachos** [comment]
ok i try change.. but while im doing backtesting no problem occur

**Comment by fachos** [comment]
now got error...

    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 26 column 29 (char 567)

**Comment by xmatthias** [comment]
Order-types are irrelevant during backtesting, since nothing is done on the exchange.

It depends if this is added to the configuration - or to the strategy (both are possible, but require slightly different syntax. 
Below the one for the configuration (False needs to be lowercased).

```
"order_types": {
    "buy": "limit",
    "sell": "limit",
    "stoploss": "limit",
    "stoploss_on_exchange": false,
    "stoploss_on_exchange_interval": 60
},
```

**Comment by fachos** [comment]
thank you xmatthias...  now running... but facing cloudflare... always retry 30sec..

**Comment by xmatthias** [comment]
you need to play with rate-limit  in the configuration:

```
  "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 500
        },
```

500 should work, if not increase it to 1000 (that's the default from ccxt) - however if you're facing cloudflare now you best back off (stop) for a few hours to let the level for your IP lower (or change the IP - if thats possible).

**Comment by fachos** [comment]
how bout this one

json.decoder.JSONDecodeError: Expecting ',' delimiter: line 52 column 7 (char 1178)

**Comment by xmatthias** [comment]
sounds like a syntax error in the configuration file (line 52 or 51, most likely)
