### ISSUE TITLE
telegram urllib3

### ISSUE THREAD

**Issue by fachos** [freqtrade/freqtrade#1847]
hi matt...
my rpi3 running now... but this error come out... earlier yesterday i have problem with cloudflare now i set to free vpn... what is bittrex timezone? thanks

2019-05-12 18:09:15,758 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x6a703ef0>, 'Connect timed out. (connect timeout=5.0)')': /botxxxxxxxxxxxxx1234567890/getUpdates

**Comment by fachos** [comment]
i think need to edit this.. but i dont know where to start....

https://github.com/python-telegram-bot/python-telegram-bot/wiki/Working-Behind-a-Proxy

**Comment by xmatthias** [comment]
a Proxy is not a VPN... VPN's route your traffic automatically through the configured server, whereas a proxy needs to be actively configured in most applications.

The bigger problems with free VPN's (generally public VPN's) is that other people are using the same servers (so have the same IP) - so on popular services (telegram ...) you're more likely to be blocked because of bad actions from other actors.

The warning however suggests that the connection was broken / reset ... is name-resolution working correctly (`nslookup telegram.com`)?

**Comment by fachos** [comment]
oh ok.. understanding now... im using vpnbook... if not i always get error msg from cloudflare.. 30sec retrying... any changes i can solve this matters?

**Comment by xmatthias** [comment]
Well i guess you can increase the `rateLimit` parameter ... however you should also wait a bi to allow them to remove your ip from the watch-list ... that's a common method (too often in the past - so watching that ip for X amount of time) ...

**Comment by fachos** [comment]
inot using vpn and increase rateLimit to 1500... no more cloudflare.. no more telegram urllib3 errors no more bittrex request timeout so far.... thank you xmatthias

**Comment by fachos** [comment]
again... cloudflare.. :(

**Comment by hroff-1902** [comment]
How's Cloudflare is involved in interaction between your bot connecting via vpn (vpnbook) and the telegram server?
I just wonder...

**Comment by fachos** [comment]
if i not using vpn... cloudflare come out with bunch html code and 30sec retrying...
if using vpn... got telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x6a703ef0>, 'Connect timed out. (connect timeout=5.0)')': /botxxxxxxxxxxxxx1234567890/getUpdates

then i follow xmatthias suggest increase rateLimit... i set  500 to 1000 to 1500 without vpn connection... 1st 10-15minutes not problem occurs..

**Comment by hroff-1902** [comment]
please paste your config (do not forget to REMOVE exchange key and secret as well as telegram chat_id and token when pasting the config!)

**Comment by fachos** [comment]
{
    "max_open_trades": 2,
    "stake_currency": "BTC",
    "stake_amount": 0.0041,
    "fiat_display_currency": "USD",
    "ticker_interval" : "5m",
    "dry_run": false,
    "trailing_stop": true,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy":{
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 9
    },
    "order_types": {
        "buy": "limit",
        "sell": "limit",
        "stoploss": "limit",
        "stoploss_on_exchange": false,
        "stoploss_on_exchange_interval": 60
    },
    "exchange": {
        "name": "bittrex",
        "key": "",
        "secret": "",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 1500,
            "aiohttp_trust_env": true
        },
        "pair_whitelist": [
            "TRX/BTC",
            "LBA/BTC",
            "BAT/BTC",
            "RVN/BTC",
            "XMR/BTC"
        ],
        "pair_blacklist": [
            "DOGE/BTC"
        ]
    },
    "experimental": {
        "use_sell_signal": true,
        "sell_profit_only": true,
        "ignore_roi_if_buy_signal": true
    },
    "telegram": {
        "enabled": true,
        "token": "",
        "chat_id": ""
    },
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    },
    "strategy": "Strategy002",
    "strategy_path": "/home/pi/freqtrade/user_data/strategies"
}

**Comment by hroff-1902** [comment]
Ah, "enableRateLimit": true for both "ccxt_config" and "ccxt_async_config". That's okay, that's what I wanted to see... (I thought perhaps you set a longer "rateLimit" for "ccxt_async_config" but did not switch on the "enableRateLimit" setting...) 

Have no additional idea for a while, sorry.

Try to use another vpn service, as an option...
seed4.me works fine for me, I can send you a promo for 1 year free access, not sure if it still active, but just as a trial...

**Comment by fachos** [comment]
ok i would like to try... thank you hroff

**Comment by hroff-1902** [comment]
see for the promo:
https://highfrequencybot.slack.com/archives/C6V6YH3N2/p1553285996189800

**Comment by fachos** [comment]
i just register slack... but cant access highfrequencybot...

**Comment by hroff-1902** [comment]
See here the invitation link: https://freqtrade.io/

**Comment by xmatthias** [comment]
Going to close this since i feel the question was answered.

feel free to reopen if you think differently
