### ISSUE TITLE
Daily dependency updates

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1849]
I propose to change from daily dependency updates to weekly ones. Do we really need to check for new versions of dependencies so frequently?

**Comment by mishaker** [comment]
No, I agree also with weekly ! I don't see any interest on daily.

**Comment by xmatthias** [comment]
i guess it kinda depends - if we encounter a bug in ccxt, then yes (these are normally fixed within hours of reporting ...) - however we can always update manually in that case.

ps: Daily is MUCH better than what we had before - where ccxt would update 3-5 times per evening alone ... :smile:
