### ISSUE TITLE
Stop loss not sync with actual configuration

### ISSUE THREAD

**Issue by vpotap** [freqtrade/freqtrade#1856]
## Step 2: Describe your environment
  * Python Version: 3.6.5
  * CCXT version: 1.18.523
  * Branch: Develop
  * Last Commit ID: 175fc859 
## Step 3: Describe the problem:

For configuration using  "trailing_stop": true  , with stoploss definied in strategy. If there are some open trades with this config and letter stoploss value is changed previous stoploss values for already open trades not sync with new value (in db values not updated). Is there any solution maybe with configurations settings to disable old stoploss usage in already opentrades, maybe config disables stoploss at all  (for now use db table update)?

**Comment by xmatthias** [comment]
especially with `trailling_stop=True`  this should work (but after the first iteration / change of the trailing stoploss).

It's known (#1304) to not work without trailing-stop - however we'll need to analyze why it's not working in this case.

**Comment by vpotap** [comment]
@xmatthias is it possible somehow  with configuration changes to enable - "sell only positive" for already open trades ?

**Comment by xmatthias** [comment]
change it in the configuration, and restart the bot / use `/reload_conf` from telegram ... almost everything related to selling (roi, sell-signal, ...) are based on strategy / configuration settings, and not stored in the database, so it'll apply to open trades. 

Stoploss is the exception from that.
