### ISSUE TITLE
Order cancelled AND fullfilled

### ISSUE THREAD

**Issue by xerviami** [freqtrade/freqtrade#1858]
## Step 1: Have you search for this issue before posting it?
Yes

## Step 2: Describe your environment

  * Python Version: 3.6.7 (`python -V`)
  * CCXT version: 1.18.516 (`pip freeze | grep ccxt`)
  * Branch: Develop
  * Last Commit ID: 46b1ecc77d53054aed6835d69f9989316422aa78 (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

Exchange: Kraken
In configuration file: "stake_amount": "unlimited",

- Freqtrade makes a limit order

```
2019-05-16 10:00:05,129 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again..
2019-05-16 10:00:16,095 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 19.7381 ...
2019-05-16 10:00:16,096 - freqtrade.freqtradebot - INFO - Using Last Ask / Last Price
2019-05-16 10:00:19,401 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': buy, 'exchange': 'Kraken', 'pair': 'BTC/EUR', 'limit': 7150.3, 'stake_amount': 19.7381, 'stake_currency': 'EUR', 'fiat_currency': 'EUR'}
2019-05-16 10:00:22,382 - freqtrade.wallets - INFO - Wallets synced.
```

- Kraken cancels the order

```
2019-05-16 10:00:25,471 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'Unfilled buy order for BTC/EUR canceled on Exchange'}
```

ISSUE:

- Kraken tells FT that the order is canceled

- but Kraken filled the order.
Here is the explaination of the behavior of kraken:
https://support.kraken.com/hc/en-us/articles/235162907-Order-Canceled-due-to-Out-of-Funds-

```
Order Canceled due to "Out of Funds":
It is possible for an order to partially execute (or "fill") if there are insufficient balances in the account for the order to fully execute.
This most commonly occurs when an order is placed for maximum volume. 
[...]
This is because the trading fee was not taken into consideration when placing the order.
```

- But FT has no active trade (cf. telegram /status -> 'no active trade') so it does not seem to be aware that the order were filled

Is that a normal way to act for FT or an issue ?
If freqtrade has no active trade, will it be able to sell the previously bought cryptos ? (perhaps I did not correctly understood the "active trade" definition)

To bypass this issuer, I configured the "stake_amount" parameters a little bit lower than the amount of available currency (currently testing).

Thank you
Xavier

**Comment by xmatthias** [comment]
Well, to be honest, this seems to be something specific to kraken (which not an officially supported exchange yet - however there is work to get that included).

I've not seen anything similar (that an order reports as cancelled, but is partially filled).

We'd need the output / return value from ccxt for that order  - feel free to mask order numbers / anything tied to your account.


``` python
import ccxt
ct = ccxt.Kraken({'apiKey': 'yourkey', 'secret': 'yoursecret'})
ct.fetch_order('order_id', 'pair')

```

**Comment by xaviermiss** [comment]
> 
> 
> Well, to be honest, this seems to be something specific to kraken (which not an officially supported exchange yet - however there is work to get that included).
> 
> I've not seen anything similar (that an order reports as cancelled, but is partially filled).
> 
> We'd need the output / return value from ccxt for that order - feel free to mask order numbers / anything tied to your account.
> 
> ```python
> import ccxt
> ct = ccxt.Kraken({'apiKey': 'yourkey', 'secret': 'yoursecret'})
> ct.fetch_order('order_id', 'pair')
> ```
> 
> you should be able to find both order_id and pair in the database ... (and you'll need to obviously supply your api keys to that script)...

@xmatthias 
Thank you for giving me the script commands.
Here is the result:

```
{'info': {'id': 'XXXXXXX',
  'refid': None,
  'userref': 0,
  'status': 'canceled',
  'reason': 'Out of funds',
  'opentm': 1557993619.2635,
  'closetm': 1557993619.2742,
  'starttm': 0,
  'expiretm': 0,
  'descr': {'pair': 'XBTEUR',
   'type': 'buy',
   'ordertype': 'limit',
   'price': '7150.3',
   'price2': '0',
   'leverage': 'none',
   'order': 'buy 0.00276045 XBTEUR @ limit 7150.3',
   'close': ''},
  'vol': '0.00276045',
  'vol_exec': '0.00275330',
  'cost': '19.6',
  'fee': '0',
  'price': '7150.2',
  'stopprice': '0.00000',
  'limitprice': '0.00000',
  'misc': 'partial',
  'oflags': 'fciq',
  'trades': ['TYBUIY-ZB7QG-STPUW5']},
 'id': 'OX6FHZ-6IMG3-FTU6Y4',
 'timestamp': 1557993619263,
 'datetime': '2019-05-16T08:00:19.263Z',
 'lastTradeTimestamp': None,
 'status': 'canceled',
 'symbol': 'BTC/EUR',
 'type': 'limit',
 'side': 'buy',
 'price': 7150.3,
 'cost': 19.6,
 'amount': 0.00276045,
 'filled': 0.0027533,
 'average': 7150.2,
 'remaining': 7.149999999999605e-06,
 'fee': {'cost': 0.0, 'rate': None, 'currency': 'EUR'}}
```
