### ISSUE TITLE
Issue running the container

### ISSUE THREAD

**Issue by hpdeandrade** [freqtrade/freqtrade#1860]
Hi,
I have been running freqtrade with VirtualBox (Ubuntu) without any problem so far. However, when trying with Docker I'm having some (newbie) issues while following freqtrade installation guide.

I'm on Windows (with Docker running Linux containers), with Python3.

Everything goes well until I create the Docker image. Problem comes up when I run the image with the provided commandline to bind mount my config.json file:

`docker run --rm -v /etc/localtime:/etc/localtime:ro -v pwd/config.json:/freqtrade/config.json -it freqtrade`

I'm not sure whether I'm correctly replacing `pwd`. My config.json file is located at C:/Users/Henrique/freqtrade, so I'm running the following (is it correct?):

`docker run --rm -v /etc/localtime:/etc/localtime:ro -v C:/Users/Henrique/freqtrade/config.json:/freqtrade/config.json -it freqtrade`

Image attached shows the error I get.

Also, section 5.1 and 5.2 shows how to move my config file and database. It creates a directory called `.freqtrade` which I don't really understand. Am I supposed to have a `.freqtrade` folder inside the `C:/Users/Henrique/freqtrade` folder?

Thank you and apologize if this is the wrong place to ask something like that. I took a look into all freqtrade material, Docker `-v` documentation but still couldn't figure out.

Cheers,
Henrique

**Comment by xmatthias** [comment]
The place to ask is absolutely correct, don't worry!

you'll first of all need to remove `-v /etc/localtime:/etc/localtime:ro` - it's a linux construct which does not exist on windows.

The folders in the documentation are meant as a sample (using .freqtrade makes it a hidden folder in the home directory, which is common practice in unix systems) - however does not matter for windows (it's not hidden there by default) - so you can use whatever folder you'd like the database/strategies/configs to be stored.

You'll however need to make sure they're exposed to docker ([instruction on how to configure this](https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c) ) so the bind-mount we're using for config/strategy/database does actually work.

**Comment by hpdeandrade** [comment]
Thanks xmatthias. It worked!
