### ISSUE TITLE
Issue with freqtrade module when plotting (plot_dataframe.py)

### ISSUE THREAD

**Issue by hpdeandrade** [freqtrade/freqtrade#1881]
Hello everyone!

I'm having some issues while plotting results. Issue is towards the freqtrade module and I think this happens because the Python version I'm using.

Currently, to run backtesting and optimization I'm using the following code (somehow my main.py is being executed without the need of specifying it):

`python -m freqtrade backtesting`
`python -m freqtrade hyperopt -e 100`

However, when plotting results (which instead of main.py, needs to be plot_dataframe.py), I'm not sure how should I replace my code. I see the following error.

![image](https://user-images.githubusercontent.com/46167400/58390065-aef51580-8005-11e9-82e6-62ec5a3870d3.png)

I'm using Python 3.7 on Windows.

Thanks!

**Comment by xmatthias** [comment]
According to the error, it's not installed correctly.

what happens if you run `freqtrade --help` alone (not with `python -m freqtrade`)?

I suspect it'll produce the same error, in which case, you might wanna try to run `pip install -e .`

**Comment by hpdeandrade** [comment]
Thank you again Matthias! ;)

It worked! I haven't had installed freqtrade on my venv. Do you know hi I was able to run backtesting/optimization without having that? (by only including `-m freqtrade` before the commands?)

Anyway, now I have an issue while optimizing - will close this one and open a new topic.

Cheers!

**Comment by xmatthias** [comment]
yes - you had all dependencies installed (probably `pip install -r requirements.txt`) - but not freqtrade itself. `python -m freqtrade` uses the package  (`freqtrade/__main__.py`) even if it's not installed. 
It does not really matter as everything should work similarly apart from scripts - but is more verbose than running `freqtrade --help` (without any python ...).
