### ISSUE TITLE
Telegram: Market orders are identified as limit (Binance)

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#1887]
## Step 2: Describe your environment

  * Python Version: python3.7
  * CCXT version: 1.18.551 
  * Branch: Master | Develop
  
## Step 3: Describe the problem:

I'm using market orders for my strategy, the bot is executing proper market orders on the exchange (binance) and i've verified them on exchange, the only issue is that the telegram bot says that its a limit order

example:

Binance: Buying SKY/BTC
with limit 0.00022700
(0.004692 BTC,40.586 USD)

Binance: Selling ZEN/BTC
Limit: 0.00134500
Amount: 3.49200000
Open Rate: 0.00128900
Current Rate: 0.00134500
Sell Reason: force_sell
Profit: 4.14% (profit: 0.00018636 BTC / 1.612 USD)

### Steps to reproduce:

1. Run binance
2. Use both market for buy/sell

**Comment by xmatthias** [comment]
well ... err ... yes ... it's "kinda" hardcoded in the `telegram.py` file (it's not getting the information about the trade type).

definitely something we should look at and fix

**Comment by Dante2333** [comment]
Should I mark this as solved? @xmatthias let me know.

**Comment by xmatthias** [comment]
nah, it's plain wrong currently, so i'd leave this open until we get to fix it.
It's not a one-liner , as we first need to add this information to what is sent to RPC handlers - so don't expect this to be fixed right away.
