### ISSUE TITLE
Suggestions - accumulation 

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#1890]
Include accumulate settings 
Say I don't want to compound my gains, for every winning trade I want it to use that pair to accumulate specific pair. If I trade eth pairs, maybe I want more btc rather than eth, so for every winning trade then buy btc when it reaches a threshold or simply make a bank reserve of given currency 

Accumulate true or false 
If true, if profit > X then buy up to X. I'll elaborate further in a few hrs.

This can also serve the particular purpose of trading btc to accumulate more usd

**Comment by hroff-1902** [comment]
I did not get this issue, sorry.

**Comment by Dante2333** [comment]
If my base is btc, i want my bot to keep trading with 0.5 btc, if I'm at 0.54 btc i want it to cover 0.04 into a coin i want to accumulate. This coin can be usdt or usd or simply an alt that I'm looking to dca into.

**Comment by hroff-1902** [comment]
Would you change the existing trade or differ the stake amount for next trade, increasing it after a previous trade with profit?

**Comment by Dante2333** [comment]
if you use "unlimited" its increased automatically; it would have to be something like
If trade is done:
        If profit > x: (define x as minimum sellable in exchange or so)
                 Sell profit to Y coin

so you'll have same stake amount and profits will sit on Y coin

**Comment by hroff-1902** [comment]
So you want to "fix profit", selling a part of an open position which is in profit?

**Comment by xmatthias** [comment]
honestly, i think this is a too complicated and edge-case logic (if i understood it correctly, anyway).

If you wanna trade 0.5 BTC - best define `stake_amount=0.1, max_open_trades=5`. so your 0.04 BTC profit will "remain" as BTC on the exchange.

You can then move it to that other coin manually (maybe that coin changes over time and will depend on the rate, too).

The point with stake_amount * max_trades is that the bot doesn't touch other currencies (you may want the bot to not touch the other 0.5 BTC for now as you don't fully trust the strategy yet) - which this would go completely against.

**Comment by xmatthias** [comment]
by specifying `stake_amount=0.1, max_open_trades=5` - you will only trade 0.5BTC (`stake_amount * max_open_trades` ) - the eventual profit (reserve) will stay in your account (as BTC) unless you move it (or start a second bot), so i think this will actually already do what you desire...

**Comment by Dante2333** [comment]
Yes, you are right but still it wont be converted into a specific currency. Thanks for the suggestion.
