### ISSUE TITLE
Backtesting - Simpla SMAcross daily - Inaccuracy backtesting

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#1894]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

Python Version: python3.7
CCXT version: 1.18.551
Branch: Master | Develop
  
## Step 3: Describe the problem:

I created a strategy, a simple SMACROSS, using sma7 and 25; in order to verify my theory I used the following code:

Populating dataframe:

```
  dataframe['sma7'] = ta.SMA(dataframe, timeperiod=7)
  dataframe['sma25'] = ta.SMA(dataframe, timeperiod=25)
```

Buy conditon:

```
dataframe.loc[
            (
                (dataframe['sma7'] > dataframe['sma25']) &
                (dataframe['sma7'].shift(1) <= dataframe['sma25'].shift(1)) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'buy'] = 1

```

Sell condition:

```
dataframe.loc[
            (
                (dataframe['sma7'] < dataframe['sma25']) &
                (dataframe['sma7'].shift(1) >= dataframe['sma25'].shift(1)) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'sell'] = 1
        return dataframe
```
                          

### Steps to reproduce:

1.Configure binance as usual, pointing to strategy file
2. in strategy, use code above to populatedataframe and then to create buy/sell conditions
3. Download binance ADA/BTC
4. chart smacross 7/25 (simple moving average) on tradingview, 
5. use the backtesting with following timerange: 20190301- (this should do March 1 to now
6. at least 1 buy 1 sell happened in this moment, use no stoploss and sell on sell signal, no trailing stop
7. I can confirm this strategy works as I have verified it on lower timeframes and bots acts accordingly.

### Observed Results:
Expected result: at least 1 buy and 1 sell https://www.tradingview.com/x/kpRw6f0d/

Results:

```
2019-05-30 13:20:18,802 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy smacross
2019-05-30 13:20:18,803 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2019-03-01T00:00:00+00:00 up to 2019-05-29T00:00:00+00:00 (89 days)..
Result for strategy smacross
========================================================= BACKTESTING REPORT ========================================================
| pair    |   buy count |   avg profit % |   cum profit % |   tot profit BTC |   tot profit % | avg duration   |   profit |   loss |
|:--------|------------:|---------------:|---------------:|-----------------:|---------------:|:---------------|---------:|-------:|
| ADA/BTC |           0 |            nan |           0.00 |                0 |           0.00 | 0:00           |        0 |      0 |
| TOTAL   |           0 |            nan |           0.00 |                0 |           0.00 | 0:00           |        0 |      0 |
========================================================= SELL REASON STATS =========================================================
| Sell Reason   | Count   |
||
====================================================== LEFT OPEN TRADES REPORT ======================================================
| pair   |   buy count |   avg profit % |   cum profit % |   tot profit BTC |   tot profit % | avg duration   |   profit |   loss |
|:-------|------------:|---------------:|---------------:|-----------------:|---------------:|:---------------|---------:|-------:|
| TOTAL  |           0 |            nan |           0.00 |                0 |           0.00 | 0:00           |        0 |      0 |
```

**Comment by xmatthias** [comment]
> 7. I can confirm this strategy works as I have verified it on lower timeframes and bots acts accordingly.

what timeframe did you use? that's not mentioned above

**Comment by MichealReed** [comment]
Also would recommend using qtpylib.crossed_above(val1, val2) or qtpylib.crossed_below(val1, val2) for something like this.

**Comment by xmatthias** [comment]
I agree with @MichealReed , using crossed_above is a lot less errorprone - but not the problem as qtlib implements it almost identically than you did..

The below assumes that you use daily candles (you use that in the chart too).

However: the problem you're having is not enough data. 
You use SMA25 - which requires 25 days of data PRIOR to generating the first buy signal.
In real operations, that's not an issue as we get ~500 candles at startup from the exchange, so you don't need to run the bot 25 days until the first buy-signal.

However, you have 90 day's worth of data - the screenshot shows the buy-signal on the 11th day. 

If i backtest your strategy sample with data since February (first download)

```bash 
python3 scripts/download_backtest_data.py --pairs-file adabtc.json --exchange binance -t 1d --days 130
```

```bash
freqtrade --config user_data/config_binance_onepair.json -s SMACROSS backtesting --timerange 20190201-
```

i get the following output:

```
2019-05-30 20:06:42,455 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2019-02-01T00:00:00+00:00 up to 2019-05-29T00:00:00+00:00 (117 days)..
Result for strategy SMACROSS
========================================================= BACKTESTING REPORT ========================================================
| pair    |   buy count |   avg profit % |   cum profit % |   tot profit BTC |   tot profit % | avg duration     |   profit |   loss |
|:--------|------------:|---------------:|---------------:|-----------------:|---------------:|:-----------------|---------:|-------:|
| ADA/BTC |           1 |          33.94 |          33.94 |       0.01698601 |          11.31 | 34 days, 0:00:00 |        1 |      0 |
| TOTAL   |           1 |          33.94 |          33.94 |       0.01698601 |          11.31 | 34 days, 0:00:00 |        1 |      0 |
========================================================= SELL REASON STATS =========================================================
| Sell Reason   |   Count |
|:--------------|--------:|
| sell_signal   |       1 |
====================================================== LEFT OPEN TRADES REPORT ======================================================
| pair   |   buy count |   avg profit % |   cum profit % |   tot profit BTC |   tot profit % | avg duration   |   profit |   loss |
|:-------|------------:|---------------:|---------------:|-----------------:|---------------:|:---------------|---------:|-------:|
| TOTAL  |           0 |            nan |           0.00 |       0.00000000 |           0.00 | 0:00           |        0 |      0 |
 
```


which i assume is in line with your expectations.

**Comment by MichealReed** [comment]
@xmatthias this kind of goes back to an issue I brought up in slack the other day about use of historical data. Could logic be added to backtesting.py to prepend the max number of candles needed for TA purposes to the date range provided if available? How could you detect this from strategy?

**Comment by hroff-1902** [comment]
> @xmatthias this kind of goes back to an issue I brought up in slack the other day about use of historical data. Could logic be added to backtesting.py to prepend the max number of candles needed for TA purposes to the date range provided if available? How could you detect this from strategy?

I'm going to add a parameter into strategies (to be set straight in the custom strategy) which defines the number of candles it needs. In case of indicators that need long history (like EMA(180)) it may have sense.

So backtesting will need history for <min. timerange datetime> - <appropriate number of candles> to have all indicators valid straight at the first candle of the timerange used for backtesting...

**Comment by MichealReed** [comment]
> 
> 
> > @xmatthias this kind of goes back to an issue I brought up in slack the other day about use of historical data. Could logic be added to backtesting.py to prepend the max number of candles needed for TA purposes to the date range provided if available? How could you detect this from strategy?
> 
> I'm going to add a parameter into strategies (to be set straight in the custom strategy) which defines the number of candles it needs. In case of indicators that need long history (like EMA(180)) it may have sense.
> 
> So backtesting will need history for <min. timerange datetime> - to have all indicators valid straight at the first candle of the timerange used for backtesting...

Brilliant. Any plans to loop this in with the CLI? Would also be good to have as a param for live and dry running of the trading engine vs making this work for backtesting only.

**Comment by hroff-1902** [comment]
> Brilliant. Any plans to loop this in with the CLI? Would also be good to have as a param for live and dry running of the trading engine vs making this work for backtesting only.

Well, my idea was to set in right in the custom strategy since it's the strategy that contains indicators and "knows" how long history they need... Do you have any usecases why having it in the command line options may be useful?

**Comment by Dante2333** [comment]
You're right. I messed up, it's obvious it needs the 25 candles from before, thank you! @xmatthias.

**Comment by xmatthias** [comment]
> I'm going to add a parameter into strategies (to be set straight in the custom strategy) which defines the number of candles it needs. In case of indicators that need long history (like EMA(180)) it may have sense. 

not sure if it's not just a documentation issue ... 
to me, if i define `--timerange 20190301-` - that means that i have data from that day onward - so your parameter would download the whole data again to get data since Feb 3rd - which is risky as not all exchanges offer unlimited historic data - so using `--refresh-` would actually delete data i had.
