### ISSUE TITLE
Port CHOPP Index as an indicator for freqtrader

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#1897]
Chop index description:
https://www.tradingview.com/wiki/Choppiness_Index_(CHOP)
Python implementation:
https://qiita.com/hoshitter1/items/d241cd2d13b72df9a204

I'm going to try to do it my self but probably something that could benefit other users.

can this be added to freqtrade/freqtrade/vendor/qtpylib/indicators.py ?

I tried adding choppiness.py and import it o my strategy but I keep getting Impossible to load strategy, this class does not exist or contains python code errors.

**Comment by hroff-1902** [comment]
> can this be added to freqtrade/freqtrade/vendor/qtpylib/indicators.py ?

Ask pls this at the qtpylib project: https://github.com/ranaroussi/qtpylib.
Another apprpriate place is the freqtrade/technical repository: https://github.com/freqtrade/technical
