### ISSUE TITLE
/forcebuy not working for bittrex

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#1898]
## Step 1: Have you search for this issue before posting it?

yes

## Step 2: Describe your environment

Python Version: python3.7
CCXT version: 1.18.551
Branch: Master | Develop

## Step 3: Describe the problem:

Forcebuy wont work for bittrex even when its enabled

### Steps to reproduce:

1. configure bittrex
2.enable forccebuy on config.json
3.turn on freqtrade with config file
4.try to forcebuy a pair
  
### Observed Results:

What happened? telegram rpc says forcebuy not enabled when its enabled
what should happen? a forcebuy should have happened

### Relevant code exceptions or logs:

  ```
2019-05-31 21:30:53,877 - freqtrade.rpc.telegram - INFO - Executing handler: _forcebuy for chat_id: 146554112
  ```

**Comment by xmatthias** [comment]
this has nothing to do with the configured exchange, but it may be a typo or similar in the configuration.

please post your configuration (without keys) so we can verify.

**Comment by Dante2333** [comment]
You're right. I found the same line written twice, fixed and it did fix my problem.
