### ISSUE TITLE
Hyperopt Resamples

### ISSUE THREAD

**Issue by MichealReed** [freqtrade/freqtrade#1900]
Python Version: 3.6.7
    CCXT version: 1.18.507
    Branch: Develop
    Last Commit ID: 4ae743e

  
## Step 3: Describe the problem:

self.ticker_interval is not implemented in the hyperopt interface, so you cannot resample data to higher timeframes.

**Comment by hroff-1902** [comment]
why can't you resample data if you _know_ that, for example, your timeframe set in the config is 5 min and you need data for the 1h timeframe? Just resample from 5 min to 1 h in your strategy, using hardcoded 5 min and 1 h there...

**Comment by hroff-1902** [comment]
@MichealReed implemeting the solution for it (almost done), see the reference to the Pull Request above.

The timeframe used by the bot will be available as `metadata['timeframe']` in the populate_*() methods in both strategies and hyperopts.
