### ISSUE TITLE
Avoid sell/buy on same candle

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#1904]
## Step 1: Have you search for this issue before posting it?
Yes. Post related 1850
#
https://github.com/freqtrade/freqtrade/issues/1850

Python Version: python3.7
CCXT version: 1.18.551
Branch: Master | Develop
  
## Step 3: Describe the problem:
Bot using 30m candle. Simple smacross. So far so good, but it seems it bought and since condition to sell was reached on the same candle it bought again after selling. 
### Steps to reproduce:

Its hard to reproduce as the sell condition has to happen on the same candle as the buy condition. 
  
### Observed Results:

What happened? It bought back after selling in profit. 
What should have happened? That it only bought once rather than immediately buying after sell

### Relevant code exceptions or logs:
Sadly systemd is not keeping the whole log so I can't take it from there and I was not saving it on another file. 
![Screenshot_20190603-012154](https://user-images.githubusercontent.com/5402278/58764082-fea38600-859d-11e9-84df-834b5e25d128.png)

Binance: Buying TNT/BTC
with limit 0.00000374
(0.009040 BTC,78.713 USD)

Binance: Selling TNT/BTC
Limit: 0.00000431
Amount: 2417.00000000
Open Rate: 0.00000374
Current Rate: 0.00000431
Sell Reason: roi
Profit: 15.01% (profit: 0.00135823 BTC / 11.827 USD)

Binance: Buying TNT/BTC
with limit 0.00000431
(0.009137 BTC,79.563 USD)

Binance: Selling TNT/BTC
Limit: 0.00000388
Amount: 2120.00000000
Open Rate: 0.00000431
Current Rate: 0.00000392
Sell Reason: stoploss_on_exchange
Profit: -10.39% (loss: -0.00095014 BTC / -8.273 USD)

As you can see on timestamp it's still the same candle that it bought, so my assumption is that somehow it verifies that the condition happen before and he doesn't understand that hr already sold in profit so he buys again.

Shouldn't it turn the buy condition off in the same pair after roi or stoploss until it happens again?

**Comment by xmatthias** [comment]
there is a flag - `ignore_roi_if_buy_signal` which would not sell if the buy-signal is still active (which i would think is the correct way - since that'll avoid costs and your strategy thinks it'll go up again, otherwise the buy-signal would be gone).

this does not apply to stoploss obviously ...

**Comment by hroff-1902** [comment]
@xmatthias 
I think, there is a bug here, need some further investigations...

**Comment by hroff-1902** [comment]
In FreqtradeBot.create_trade() (i.e., while buying) we have a check:
```
if buy and not sell:
```

In principle, there should not be any buys if sell signal is produced on the same candle...

**Comment by Dante2333** [comment]
@xmatthias signal is produced and target is reached, so ignore roi if buy signal doesn't solve the issue here as it did what I intended it do, the re buy after roi within the same buy signal is the issue.

**Comment by xmatthias** [comment]
> In principle, there should not be any buys if sell signal is produced on the same candle...

ROI / stoploss are not signals in that sense (and more importantly, they don't "remain" there once the trade is sold.

@Dante2333 i'm not sure if it's not your strategy then. You want the asset to be sold at that point based on ROI ... but you don't want to buy again - doesn't that mean that your strategy produces a wrong buy signal?

**Comment by Dante2333** [comment]
I do want it to buy again, the problem is it bought again after selling for ROI on the same candle. In this case my strategy is a simple SMAcross; it happened, it bought, then it did a 15% roi on the same candle that it bought, the cross did not happen again but since it still was the signal candle then it bought again which should have not happened according to the strategy, it only happened due to the lingering "buy"

**Comment by hroff-1902** [comment]
@Dante2333 I think I got you, and I think I know how to implement an enhancement which allows to avoid such buys after selling for any reason, including for roi. It's not a bug, it will be an enhancement, so let's mark it now, for returning to it later...

**Comment by Dante2333** [comment]
I would like to say that this is a mandatory enhancement as trading on daily or 12hr becomes impossible if its a trigger once event for the buy condition. I've had same issue on 12hr candles where the buy condition was met before then since the candle had not closed, it did buy again after being stopped out

**Comment by gianlup** [comment]
This issue is strictly related to #1850, but it's strange that your bot had re-bought the same pair. Did you have `process_only_new_candles=1`?

I think we can use something like that for now to mitigate the problem
```python
def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
    dataframe['buy'] = 0
    
    # To prevent a buy on the same candle (timeframe 2h)
    if 'last_buy' in self.cust_info and dataframe.iloc[-1]['date'] < self.cust_info['last_buy'] + DateOffset(hours=2):
        return dataframe

    dataframe.loc[
        (
            ...
        ),
        'buy'] = 1

    if dataframe.iloc[-1]['buy']:
        self.cust_info['last_buy'] = dataframe.iloc[-1]['date']

    return dataframe
```

This workaround will work only in live/dry run. In backtest should be commented out (is not necessary and produces wrong results).

**Comment by Dante2333** [comment]
> This issue is strictly related to #1850, but it's strange that your bot had re-bought the same pair. Did you have `process_only_new_candles=1`?
> 
> I think we can use something like that for now to mitigate the problem
> 
> ```python
> def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
>     dataframe['buy'] = 0
>     
>     # To prevent a buy on the same candle (timeframe 2h)
>     if 'last_buy' in self.cust_info and dataframe.iloc[-1]['date'] < self.cust_info['last_buy'] + DateOffset(hours=2):
>         return dataframe
> 
>     dataframe.loc[
>         (
>             ...
>         ),
>         'buy'] = 1
> 
>     if dataframe.iloc[-1]['buy']:
>         self.cust_info['last_buy'] = dataframe.iloc[-1]['date']
> 
>     return dataframe
> ```
> 
> This workaround will work only in live/dry run. In backtest should be commented out (is not necessary and produces wrong results).

No, I did not have process only new candles.

**Comment by gianlup** [comment]
Ok this makes sense. My considerations are:

- with `process_only_new_candles=0` no matters your sell reason SL, TSL or ROI if you are in the same candle the bot will re-buy the same pair (this issue).
- with `process_only_new_candles=1` no matters your sell reason SL, TSL or ROI if you are in the same candle the bot will **not** re-buy the same pair (because of `_last_candle_seen_per_pair`), but probably another one if there are other pairs with an active buy signal (issue #1850).

**Comment by Dante2333** [comment]
I can try with process_only_new_candles and report back, will let you know

**Comment by Dante2333** [comment]
@gianlup I've tried with the following (I assume this is what you referred to):

   # run "populate_indicators" only for new candle
    ta_on_candle = True
It did not work, it keeps buying, will try now to use the code you created for me.

**Comment by xmatthias** [comment]
i think the problem is a bit more complex. the hacky solution within the strategy will definitely work.

`_last_candle_seen_per_pair`  is  set once the ticker is analyzed to get a buy or sell signal.
Since the pair is currently open, the bot will not check for a buy signal.

within handle trade, we only check for the sell-signal (call `strategy.ticker_interval`) if `"use_sell_signal"` is enabled.
If it's not enabled, then `_last_candle_seen_per_pair` is never set since this method is never reached for this pair - so once ROI / stoploss hits, the pair is "fresh", get's reanalyzed and produces a buy signal.



@Dante2333  what's the state of `"use_sell_signal"` in your tests?

**Comment by Dante2333** [comment]
@xmatthias I've been using use_sell_signal from the beginning, the thing is since its 12h timeframe it will wait 12h at least to produce a sell signal and this is actually what I've seen in reality.

**Comment by xmatthias** [comment]
well with 12h candles that's kind of expected with 12h timeframes tbh (it may sell on ROI/stoploss though). (it's the same with 5m candles, you just don't notice it that much if you wait for 5minutes to sell).

we do not use the last, incomplete candle for calculations, so assuming you bought at midnight - the next complete candle is at mid-day (noon), so this is when the candle may flip to sell-signal. intra-candle sells are generated by roi / stoploss usually, but not by sell_signal (basing indicators on incomplete candles can be dangerous, as they change over time).

`ta_on_candle` brings that to an extreme, as it only ever calculates at midnight and noon (when a new candle arrives) - however also without that the signal will only trigger right after the new candle (unless your strategy does some hackery ...).

**Comment by gianlup** [comment]
@Dante2333 

>ta_on_candle = True
>It did not work, it keeps buying, will try now to use the code you created for me.

Just to be sure, the parameter name isn't `ta_on_candle` but `process_only_new_candles`either in config or strategy.

**Comment by xmatthias** [comment]
Great catch @gianlup 

Note to self: don't copy-paste parameters from previous comments without checking if they are correct.

**Comment by Dante2333** [comment]
@gianlup i still had ta_on_candle on strategy file as it was on the old template i used, should i re-test ? 
@xmatthias Yes, thats the expected behavior, but still it does not matter in this case; 
My bot buys every 12hr, thats fine for my strategy, but if it sells by roi/stoploss then it will buy again, if i use process_only_new_candles it wont try to buy again if it bought once already?

**Comment by Dante2333** [comment]
I can confirm that with process_only_new_candles it won't buy again the same pair after selling due to roi or stoploss on the same candle it bought. @xmatthias @gianlup

**Comment by gianlup** [comment]
Ok so we are in the same situation :)

@xmatthias what do you think about https://github.com/freqtrade/freqtrade/issues/1904#issuecomment-498662741?

**Comment by gianlup** [comment]
Just my thoughts from another issue:

I think there is a problem only in dry run/live (1850, 1904). In backtest we don't know what happens intra-candle.

I try to explain my point of view:

With `process_only_new_candles=1` I expect that **all** buy signals are evaluated only when a new candle come and I don't want a delayed buy. Example:

timeframe: 2h max_open_trades=1, new candle at 12:00 and there are 2 buy signals: ETH/BTC and LTC/BTC. Few seconds and ETH is bought. At 12:45 SL is reached and the bot sells. After few seconds it buys LTC, but this buy is 45 min late (and in my view this shouldn't happen). This is also true with max_open_trades>1.

With `process_only_new_candles=0` I think we have multiple options:

- let the bot re-buy the same pair multiple times during a candle - like now
- exclude from whitelist only pairs already bought in this candle 
- exclude all pairs to avoid delayed buys

**Comment by xmatthias** [comment]
as mentioned a few comments above - the problem is `_last_candle_seen_per_pair`, which is not called necessarily for pairs with open trades (only if `use_sell_signal` is true ...), so `_last_candle_seen_per_pair` is not set correctly, causing the next iteration after sell to reevaluate this pair, and create a (undesired) buy signal.

It does not make sense to me to try and create buy-signals for open pairs (which would solve the issue, but have a rather huge performance penalty for users not using `process_only_new_candles`, since a evaluation would be run which is not necessary.
