### ISSUE TITLE
README token fees

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#1906]
I'm planning to do extensive testing of huobi, so far so good, it would be good to include or modify Binance reference *adding of bnb/pair to blacklist " to make it more abstract to refer to all exchanges who have a token for discounted fees, example Huobi, for huobi it would be <HT/pair>, etc

**Comment by xmatthias** [comment]
That'll work for me - if you have an idea on how to improve this, please feel free to submit a PR to improve this, we're always looking for helping hands.

Until now it didn't make too much sense (supporting only Bittrex and Binance, and only binance has a token) - but i can see this in tue future.

**Comment by Dante2333** [comment]
For example, huobi has its own token, HT and multiple other exchanges does the same thing.

**Comment by xmatthias** [comment]
As mentioned, if you have an idea on how to improve wording for this (and generalize it more) please submit a PR.

I don't see this with any priority as we currently only support bittrex and Binance officially - so others currently don't apply.

**Comment by hroff-1902** [comment]
@Dante2333 For easy creation of PR with changes in the doc. file like your proposal pls refer to:
https://help.github.com/en/articles/editing-files-in-another-users-repository
