### ISSUE TITLE
Enhancement - Add Sharpe Ratio for strategies backtesting 

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#1907]
https://corporatefinanceinstitute.com/resources/templates/excel-modeling/sharpe-ratio-calculator/

Introduce Sharpe Ratio for strategies for backtesting
Additional command or parameters for backtesting: --risk-free=X; 

then --risk-free is a number between 0.00 and 1.00, then adjust to sharpe calculation in months if months for strategies > 1; in years if years for strategy > 3

Add new column on strategy summary: Sharpe Ratio

**Comment by yperfanov** [comment]
I have the Sharpe Ratio implemented but is a copy paste from a Udemy freqtrade course I took. 
@hroff-1902  do you think I can make a pull request with that code?

**Comment by hroff-1902** [comment]
> I have the Sharpe Ratio implemented but is a copy paste from a Udemy freqtrade course I took.
> @hroff-1902 do you think I can make a pull request with that code?

Sure, that addendum should also be licensed under GPL (otherwise it cannot be used along with GPLed freqtrade and distributed) so no problem to borrow it. You may add a link to them somehow in the comments to keep the attribution of the authors of the code.

**Comment by wolvesproduction** [comment]
Yes I took the same course on Udemy and I trully believe its a great feature that will bring better and more accurate results. It only needs a few changes in hyperopt.py. I'd be more than happy to make this happen.

**Comment by hroff-1902** [comment]
Thanks for the example of the code.

The problem with it does not consist in python code for calculating the ratio. The problem is that in case of many ratios and other parameters added to the existing table, the result can become overloaded and unreadable. So one the ideas by @xmatthias was to add a new table to the backtesting results for this kind of ratios...

**Comment by wolvesproduction** [comment]
Well the function is replacing the current calculate_loss function in hyperopt.py. I've inspected the whole file and the function is not calling any table. Basically, it just makes an on-the-fly calculation based on the current profit and trades count. There're maybe 3 changes in the whole file and these are simple arithmetic calculation. 

Maybe I'm missing something under the hood? Could you elaborate?

**Comment by hroff-1902** [comment]
> Well the function is replacing the current calculate_loss function in hyperopt.py. 

Ah, that's another point (replacing the calculate_loss and/or objective optimization function in the hyperopt). @Dante2333 wrote in his original suggestion above: "Add new column on strategy summary: Sharpe Ratio"

>I've inspected the whole file and the function is not calling any table. Basically, it just makes an on-the-fly calculation based on the current profit and trades count. There're maybe 3 changes in the whole file and these are simple arithmetic calculation.
> 
> Maybe I'm missing something under the hood? Could you elaborate?

I meant this reply by @xmatthias: https://github.com/freqtrade/freqtrade/issues/1908#issuecomment-500146927

**Comment by xmatthias** [comment]
Stupid question for someone more familiar with sharpe ratio (@hroff-1902, @wolvesproduction, @Dante2333  ?)

the code above uses `sharp_ratio = -sharp_ratio` - negating the sharpe-ratio before returning.
For Hyperopt, lower = better, so it'll prefer higher sharpe-ratios.

doesn't this mean that hyperopt would optimize for a sharpe-ratio as high as possible - basically optimizing for the riskiest strategy?

or did i miss something?

**Comment by hroff-1902** [comment]
Nope, higher values of the Sharp Ratio show how potential profit __can compensate__ the risks, even for risky strats. The higher SR the better. For hyperopt, right, since it descends to the local minimum of the objective function, SR should be included with some negative coefficient...

**Comment by xmatthias** [comment]
ok thank you - that explains my doubt

**Comment by hroff-1902** [comment]
Let's not change the hyperopt objective in the meantime (I have a generic solution), but include SR to the output of `backtesting` instead...

**Comment by hroff-1902** [comment]
> ok thank you - that explains my doubt (ps: you'll love what i'm currently working on)

Have not seen it when I was writing the previous comment. Hmm, let's see (intrigued)

**Comment by xmatthias** [comment]
> Let's not change the hyperopt objective in the meantime (I have a generic solution), but include SR to the output of backtesting instead...

sorry ... didn't know that ...

**Comment by hroff-1902** [comment]
Sorry I did not tell you (and the community) about my considerations and plans regarding this...

**Comment by hroff-1902** [comment]
^ I'm not sure the example of sharpe ratio function calculates it properly since it does not contain the risk free value at all. A kind of index (like cci30) for corresponding time period could be used as an example of risk free, or comparison with a hodl strategy for the given stake currency can be implemented... Or at least some percentage set in the parameters of this objective function...

Maybe I'm wrong here.

**Comment by hroff-1902** [comment]
Then, the function above uses period.days. It won't work properly for small timeframes and small backtesting timeranges (1m, several hours).

Then, when it calculates standard deviation, for proper calculation, the trades in the total_profit list should be grouped by days and std() applied to the grouped results. This a) is not done, b) won't work for small timeranges as well. So the standard deviation used here is not that is expected in the definition of the Sharpe Ratio.

My conclusion: this function is completely wrong. Well, this can probably be used as the objective for optimization, but it's not that is called Sharpe Ratio.

**Comment by Dante2333** [comment]
@hroff-1902 https://www.investopedia.com/terms/s/sharperatio.asp on what defines sharpe ratio; ideally instead of comparing within timeframes this should be ideal used to compare within days or months or even years.

**Comment by hroff-1902** [comment]
years? o_O

**Comment by xmatthias** [comment]
i got backtest data from binance at 5m interval from 2018-01-01 (available would be starting with september 2017 i think) until last week (or 2 weeks ago ...) for most ETH and BTC pairs (some will have data start later, obviously), so it's not that unrealistic.

**Comment by hroff-1902** [comment]
Yeah, but how would you calculate it in the boundaries of backtesting in shorter timeframes? Well, backtesting for, say, 1 month timerange in 1h interval is okay, right? but this is just 30*24 = 720 bars. So we can assume that backtesting for comparable amount of bars, say 1000 bars, would be okay for shorter timeframes, right? But for 1m timeframe 1000 bars is just 1000/60 = 16.6 hours. How would you calculate even daily Sharpe Ratio value for this timerange? Or where would you import daily/monthly/yearly value from during backtesting in this timerange?

**Comment by xmatthias** [comment]
backtesting for 1000 bars only does not make too much sense tbh - i normally use 1 month 5m candles for testing, and half a year/year to "really" evaluate a strategy.

Ideally, your backtesting-period should cover different trade-cycles (up-trend, down-trend, no-trend, ...) - and with everything < 1 month you may only have one, but not the other ...

**Comment by hroff-1902** [comment]
> backtesting for 1000 bars only does not make too much sense tbh - i normally use 1 month 5m candles for testing

It's 30*24*12 = 8640‬ bars,, So testing for a week on 1m is even better..., Okay, how would you import monthly Sharpe Ratio if you are backtesting on 1m for a week?

**Comment by xmatthias** [comment]
well you can't - you need to have it dynamic according to the timeframe and time-range used.

noone said it's easy and the same thing works for all cases ;)

**Comment by hroff-1902** [comment]
thanks for the link

**Comment by werkkrew** [comment]
This is almost two years old, is it still a "good first issue" to work on?

**Comment by xmatthias** [comment]
that just means noone took the time / effort to work on it yet, or noone did consider it important enough.

To be fair - adding this should now be simpler (with the backtesting-summary section available) - which didn't exist when this was first posted.

**Comment by jbird1998** [comment]
Been a few months since the last person asked, but is this still a "good first issue"?

**Comment by xmatthias** [comment]
I don't think issues will/can "age out" of "good first issue". They'll be closed when worked on - but the complexity of a change (which makes an issue "good first" or not) for a particular issue will not really change.

**Comment by gaugau3000** [comment]
If a choice is needed between shape and sortino ratio :
Shape ratio penalize volatility (up and down) when Sortino only penalize the down volatility. So in term of performance metric Sortino may be better. I would like only to penalize drawdowns/loss not profit volatility.

Have a nice day.

**Comment by vaidab** [comment]
Definitely agree on the last comment. Please add either the Sortino or both, but sharpe is not as accurate as Sortino is.

**Comment by moinonin** [comment]
I like the idea. The problem with risk assessment rations, including those two mentioned, is that they use 'risk-free-rate-of-return' which is determined by the user. For example I want my risk free rate to be 5.5% a year, you might want to use the US Bond rate of return or some other value of around 2%. May be there could be a function so that the user will fill this in the cli

**Comment by froggleston** [comment]
Sharpe and Sortino caveats are well-documented. Any metric we choose to add in the backtest results need to be intepreted by the user effectively. So, the same arguments you are making to add more complexity could easily be applied to any of the other metrics.

Also the Sharpe vs Sortino is "better" discussion is not really relevant. Both are applicable as typical backtest metrics and should probably be included.
