### ISSUE TITLE
Enhancement - Backtesting - Add Max Drawdown for strategy

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#1908]
Add Max portofolio drawdown for strategy; include a new  column for strategy summary: max drawdown

**Comment by xmatthias** [comment]
The problem i have with adding new columns to the backtest result is that we already have a 2 tables with 9 columns - which becomes quite difficult to interpret if you run it for more than a couple of pairs.

I personally think that a collection of code snippets everyone can run easily against their backtest results would be simpler to interpret and produce a less cluttered output (not everyone will be interrested in the same metrics, so everyone can run the part of the snippet they want to know).
My idea was to extend [this](https://www.freqtrade.io/en/latest/backtesting/#further-backtest-result-analysis) section in the documentation, and if it grows too big to move it to it's own page, or alternatively provide sample-notebooks (yes, jupyter, i know...) which users can easily run against their strategies.
