### ISSUE TITLE
Hyperopts instability

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#1910]
Python 3.6.8 :: Anaconda, Inc.
ccxt==1.18.578
Develop
f04089ef1e7d774594dd3a67b4fbcdad60168eb8
  
Hyperopts is a bit unstable. It starts running some times, and some other times these different error shows up:

 
<img width="886" alt="Screen Shot 2019-06-04 at 6 11 39 PM" src="https://user-images.githubusercontent.com/48162530/58993014-e99f4080-87b1-11e9-8e12-d77fed771017.png">

<img width="787" alt="Screen Shot 2019-06-04 at 6 32 26 PM" src="https://user-images.githubusercontent.com/48162530/58993085-22d7b080-87b2-11e9-9d69-a851efd91071.png">

**Comment by hroff-1902** [comment]
Do you run the bot in a container?

**Comment by hroff-1902** [comment]
these are diff. issues.

The UnicodeEncodeError caused the "Σ" unicode character printed in the results. It produces the error if the environment does not support unicode.

What's output of:
```
echo $LANG
echo $LC_ALL
```
?

if LC_ALL is set to C, try to set as below:
```
export LC_ALL='en_US.utf8'
```
or try
```
unset LC_ALL
```

If you run the bot in a LXC container, you may try to setup environment as:
```
lxc config set CONTAINER environment.LC_ALL=en_US.UTF-8
```

**Comment by hroff-1902** [comment]
For the first part of your issue ("negative dimensions"): please read https://github.com/freqtrade/freqtrade/issues/123

It's an issue in the qtpylib implementation of AO. Still open for more than 2 years: https://github.com/ranaroussi/qtpylib/issues/62

I'll think about what else can we do (a bit more than we do in the meantime in the freqtrade codebase) with it...

**Comment by xmatthias** [comment]
it's difficult to check within Freqtrade i think (other than maybe warning below a certain data-length threshold) - since the indicators / calls to indicators are supposed to be "user-supplied".

we could parse the file as text and check for numbers, but a call to `indicatorxz(df, 25)` could mean a history of 25, or something else entirely, so i would rather not go down that rabbit hole.

**Comment by hroff-1902** [comment]
I guess @gitgitgat runs hyperopt on 1d timeframe with short timerange.

The quick workaround here is to download and use data for a longer timerange.

The strategic solution would probably be to implement own version of the buggy indicators (AO, ATR, what else?) in freqtrade/technical.

**Comment by gitgitgat** [comment]
Okay thanks @hroff-1902  @xmatthias , I'm not running the bot in a container.

**Comment by xmatthias** [comment]
but even a own implementation will require a minimum data length (also ta-lib does that) ... so i don't think we can pinpoint this to one indicator, but it's a general problem that's difficult to tackle.

**Comment by hroff-1902** [comment]
> but even a own implementation will require a minimum data length (also ta-lib does that) ... so i don't think we can pinpoint this to one indicator, but it's a general problem that's difficult to tackle.

Right, but there are different behaviour approaches implemented: 1) when pandas,ewm() do not see enough candles in the window, it fills first rows with NaNs. 2) when qtpylib.numpy_rolling_window() do not see enough candles in the window, it crashes with the exception stated above. First is okay. Second is awful.

**Comment by xmatthias** [comment]
I'll close this since it's not a hyperopt issue, but a issue with indicators, which i think was solved by changing the custom hyperopt file.

Feel free to reopen if you still have this issue
