### ISSUE TITLE
Refresh-pairs--cached

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#1911]
In the most recent refresh-pairs-cached, it appears to be capped to 99 frames, loads of missing values:

<img width="959" alt="Screen Shot 2019-06-04 at 8 55 29 PM" src="https://user-images.githubusercontent.com/48162530/58993238-87930b00-87b2-11e9-9d1c-caa9355c9d8c.png">

<img width="962" alt="Screen Shot 2019-06-04 at 7 30 39 PM" src="https://user-images.githubusercontent.com/48162530/58993239-87930b00-87b2-11e9-95e5-897e2f7105be.png">

maybe pandas?

**Comment by Dante2333** [comment]
I've downloaded the whole binance history with refresh-pairs-cached for multiple intervals and nevre had this issue.

**Comment by gitgitgat** [comment]
Okay, I didn't have that issue at the end of may and now I have it.

**Comment by Dante2333** [comment]
go on user/data/binance and purge them (assuming its binance) and fetch them again

**Comment by xmatthias** [comment]
to be honest, i do not like the `--refresh-pairs-cached` option too much, and prefer the download-script, which does exactly one thing.

Maybe, once we've added that as a freqtrade subcommand, we can remove the --refresh-pairs-cached option? 

@hroff-1902, what do you think?

**Comment by hroff-1902** [comment]
Need to think about this. From one point of view, this option is useful since it allows to run backtesting for a given timerange with a single commands...

**Comment by Dante2333** [comment]
Refresh-pairs-cached is quite handy as sometimes you are testing with new pairs that were not on your previous pairs and downloading them on the go rather than having to use the download script is useful.

**Comment by xmatthias** [comment]
I'm just asking this myself as we seem to have quite a lot of problems with this option recently - and the download script offers the `--erase` option to download it all again.

It's not something i'd remove short-term anyway, was just an idea.

One note: be carefull that even if you specify a timerange of `20190201-20190301` you're getting ALL data since Feb 1st, even though the latter 3 months are not used (#902).

**Comment by xmatthias** [comment]
i'll close this since the original issue was incomplete data.

feel free to reopen if it's not resolved.

**Comment by hroff-1902** [comment]
btw, we could add the --erase-data option to backtesting and hyperopt as well. To be used along with `-r`, with same behavior as `--erase` from the download script...
