### ISSUE TITLE
New exchange API

### ISSUE THREAD

**Issue by hpdeandrade** [freqtrade/freqtrade#1916]
Hi all,
I'm sucessfully using freqtrade for Binance. Bot seems to be working soundly.

Now, I want to do some arbitrage among Brazilian exchanges (starting with only 2 of them) and, as a person with no experience with coding, wanted to clarify the following:

=> Where in the freqtrade archive the code does the work of "link" the buy/sell signal to the trade command sent to a given exchange?
=> How "doable" would it be to replace the buy/sell triggers to arbitrage triggers in my strategy file? (e.g. if BTC in Exchange A trades at a price at least 8% lower than Exchange B I send a signal to execute a buy in A + send the BTC to Exchange B + sell in Exchange B)

Essentially, I would like to know whether I could take the advantage of freqtrade. Otherwise I would work on a new script from scratch.

Cheers,
Henrique

**Comment by hroff-1902** [comment]
> and, as a person with no experience with coding

In this case you should not better do this. Nothing personal.

> => Where in the freqtrade archive the code does the work of "link" the buy/sell signal to the trade command sent to a given exchange?

Examine freqtrade/freqtradebot.py. It contains the bot top-level "business logic".

> => How "doable" would it be to replace the buy/sell triggers to arbitrage triggers in my strategy file? (e.g. if BTC in Exchange A trades at a price at least 8% lower than Exchange B I send a signal to execute a buy in A + send the BTC to Exchange B + sell in Exchange B)

Not achievable now. An instance of freqtrade can only work with a single exchange. If you run multiple instances of freqtrade, they run separately, no communication channel between them exist. So arbitrage strategies are not applicable for freqtrade yet.

**Comment by hpdeandrade** [comment]
Thank you @hroff-1902 !

**Comment by xmatthias** [comment]
IIRC, there exists a "Arbitrage bot" (unrelated to FreqTrade) which would do just what you're asking for ... but don't ask me for a link, it's been about a year i've not looked at that...
