### ISSUE TITLE
Huobi - Market orders do not work to buy

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#1920]
## Step 1: Have you search for this issue before posting it?

Yes.

## Step 2: Describe your environment

Python Version: python3.7
CCXT version: 1.18.551
Branch: Master | Develop
  
## Step 3: Describe the problem:

*Can't use market orders to buy but exchange does support them*

### Steps to reproduce:

1. Configure huobi
2.run with market orders for buying
3. wait for buy signal
  
### Observed Results:

* There was an error saying something about spread but calling an error on the python function
*I was expecting it to simply market buy the pair when the buy signal came in

### Relevant code exceptions or logs:
```
2019-06-10 15:03:02,906 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 0.0045 ...
2019-06-10 15:03:02,907 - freqtrade.freqtradebot - INFO - Using Last Ask / Last Price
2019-06-10 15:03:04,833 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/dantefreqtrade/freqtrade/exchange/exchange.py", line 353, in create_order
    amount, rate, params)
  File "/home/dante.local/lib/python3.7/site-packages/ccxt/huobipro.py", line 754, in create_order
    raise InvalidOrder(self.id + " market buy order requires price argument to calculate cost(total amount of quote currency to spend for buying, amount * price). To switch off self warning exception and specify cost in the amount argument, set .options['createMarketBuyOrderRequiresPrice'] = False. Make sure you know what you're doing.")
ccxt.base.errors.InvalidOrder: huobipro market buy order requires price argument to calculate cost(total amount of quote currency to spend for buying, amount * price). To switch off self warning exception and specify cost in the amount argument, set .options['createMarketBuyOrderRequiresPrice'] = False. Make sure you know what you're doing.

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/home/dantefreqtrade/freqtrade/main.py", line 42, in main
    worker.run()
  File "/home/dantefreqtrade/freqtrade/worker.py", line 72, in run
    state = self._worker(old_state=state)
  File "/home/dantefreqtrade/freqtrade/worker.py", line 110, in _worker
    self._throttle(func=self._process, min_secs=throttle_secs)
  File "/home/dantefreqtrade/freqtrade/worker.py", line 123, in _throttle
    result = func(*args, **kwargs)
  File "/home/dantefreqtrade/freqtrade/worker.py", line 133, in _process
    state_changed = self.freqtrade.process()
  File "/home/dantefreqtrade/freqtrade/freqtradebot.py", line 129, in process
    state_changed = self.process_maybe_execute_buy()
  File "/home/dantefreqtrade/freqtrade/freqtradebot.py", line 423, in process_maybe_execute_buy
    if self.create_trade():
  File "/home/dantefreqtrade/freqtrade/freqtradebot.py", line 290, in create_trade
    return self.execute_buy(_pair, stake_amount)
  File "/home/dantefreqtrade/freqtrade/freqtradebot.py", line 340, in execute_buy
    time_in_force=time_in_force)
 File "/home/dantefreqtrade/freqtrade/exchange/exchange.py", line 382, in buy
    return self.create_order(pair, ordertype, 'buy', amount, rate, params)
  File "/home/dantefreqtrade/freqtrade/exchange/exchange.py", line 362, in create_order
    f'Could not create {ordertype} {side} order on market {pair}.'
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

```

**Comment by xmatthias** [comment]
Honestly, without logs and for an exchange we don't support officially, i am very tempted to close the issue until we have logs at least, since this will be impossible to even try to analyze.

**Comment by Dante2333** [comment]
> Honestly, without logs and for an exchange we don't support officially, i am very tempted to close the issue until we have logs at least, since this will be impossible to even try to analyze.

Give me 2 days as im traveling at the moment, I should be able to reproduce it quite easily.

**Comment by Dante2333** [comment]
@xmatthias added the logs

**Comment by xmatthias** [comment]
well technically the message is clear - HuobiPro seems to require a price for market orders (which i still need to investigate the reason for) - which does not make sense to me, as a market-order is (by definition) a order which you want filled immediately, at the "best price" available, which will probably not be what you supply as price.

Related ccxt code:
https://github.com/ccxt/ccxt/blob/d5e98352e17694a66a4656d0a4a7ec29b56e99c5/python/ccxt/huobipro.py#L753-L764

**Comment by hroff-1902** [comment]
@xmatthias should not be this ccxt option (options['createMarketBuyOrderRequiresPrice'] = False) be set in ft_has for Huobi?

@Dante2333 Try to set this option in the config (just an example, not tested):
```
    "exchange": {
        "name": "huobi",
        ...
        "ccxt_config": {
            "enableRateLimit": true,
            "createMarketBuyOrderRequiresPrice": false
        },
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 500,
            "createMarketBuyOrderRequiresPrice": false
        },
```

**Comment by xmatthias** [comment]
@hroff-1902 
this solution would assume that ccxt has this requirement for "fun" ... which i strongly doubt. 
It's probably a requirement of the Huobi API to have a price, so with this setting it'll not fail on ccxt, but on the API itself (at least that's my assumption)... 

ps: no need to add it to the async config dict - that's only used for downloading data
