### ISSUE TITLE
[Question] - [Dynamic roi and stop loss depending on market conditions]

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#1929]
Hi,

I 'd like to know if it is possible set a dynamic roi and stop loss depending on market indicators infos.

For example :  i don't want the same stop loss and roi to be the same all the time but take into account a normalize volality indicator that can be apply on stoploss and roi.

Is there a way to to that ?

It can be useful ?

Many tks.

**Comment by xmatthias** [comment]
Yes (non-documented), but it'll always apply to all pairs.

Technically, you could set it using `self.minimal_roi` and `self.stoploss` (always respecting the format - so roi is a dict with time:value, and stoploss a float).

It'll then be used (but it's pair-independent, and will always use the latest value (also for open trades) - so if ETH/BTC sets stoploss to 0.05, then this stoploss will apply to XRP/BTC as well, even if the original stoploss was 0.10 (assuming no trade was opened).

It's even (probably) possible to do this by pair (assumign sell-signal usage is active) - but it's risky and completely untested.

**Comment by gaugau3000** [comment]
Oki i will take a look many tks :-)
