### ISSUE TITLE
reduce() of empty sequence with no initial value

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#1932]
What may be causing that? Hyperopts is set to -e 1000. It starts running and the error pops up around -e 300-600 

Anaconda 3.6.8
1.18.667
Develop
`0d8b572a171e767e3429699c62250816294ede53`

**Comment by gitgitgat** [comment]
There is no hyperopts_results.pkl file

**Comment by xmatthias** [comment]
try to limit search using `-s buy` `-s sell` ... to find out in which optimization function this appears.

The cause for this seems simple. Looking at part of the sample implementation:

https://github.com/freqtrade/freqtrade/blob/0d8b572a171e767e3429699c62250816294ede53/user_data/hyperopts/sample_hyperopt.py#L54-L87

Lines 60-80 adds conditions. It however only adds them if the corresponding `enabled` flag is true. This means that, if conditions remains empty (hyperopt found all parameters to be non-ideal) this error may occur.

do you have the check we have in line 82, which was added recently to fix this problem?
This needs to be there for all optimizers (buy, sell, ...).

**Comment by gitgitgat** [comment]
Okay, I get it. Yeah, I have the recent check from line 82.

**Comment by gitgitgat** [comment]
so far that is fixing buys, will check what happens with sells

**Comment by xmatthias** [comment]
well you need to have this for every "part" which can (in theory) disable all conditions.

**Comment by gitgitgat** [comment]
the error is only raised for `populate_sell_trend` even though `-s sell` runs ok on its own.

**Comment by gitgitgat** [comment]
oh wait, it also raises error for `-s sell` only

**Comment by gitgitgat** [comment]
hmm, okay, actually just realised the `if conditions` were wiped, trying that again

**Comment by gitgitgat** [comment]
it's fine.
