### ISSUE TITLE
ValueError: The truth value of a Series is ambiguous

### ISSUE THREAD

**Issue by rizzopablo** [freqtrade/freqtrade#1976]
Hi, how do you compute this indicators?

`

        compras = dataframe['volume'] if dataframe['close'] > dataframe['open'] else 0
        ventas = dataframe['volume'] if dataframe['close'] < dataframe['open'] else 0
        dataframe['compras'] = compras 
        dataframe['ventas'] = ventas
`
The above code gives this error:

> ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by xmatthias** [comment]
not really a freqtrade problem, but a pandas issue...

try: 

``` python
import numpy as np

dataframe['compras'] =np.where(dataframe['close'] > dataframe['open'], dataframe['volume'], 0)
dataframe['ventas'] = np.where(dataframe['close'] < dataframe['open'], dataframe['volume'], 0)
```

**Comment by rizzopablo** [comment]
Yes! Thank you!
