### ISSUE TITLE
Pax balance not detected

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#1981]
Version 2019.5
Bot won't detect pax base, will update to newest to see if fixed. Will also assumes that this is the same issue for other stable coins that are not tether 

Last version of CCTX
Running 2019.6
Exchange Binance
Edited to add more information about the issue

**Comment by xmatthias** [comment]
This is lacking quite some information.

What exchange are you using?
what version of ccxt?

**Comment by Dante2333** [comment]
Sorry @xmatthias .
Latest version of CCTX and running version 2019.6 of freqtrade on Binance.

**Comment by Dante2333** [comment]
> This is lacking quite some information.
> 
> What exchange are you using?
> what version of ccxt?
> 
> Edit: did you get any message while starting the bot?

No, no specific message.

**Comment by xmatthias** [comment]
So what's the behaviour you observed? "does not detect" is very generic ...

**Comment by hroff-1902** [comment]
I also did not get the issue...

**Comment by Dante2333** [comment]
Basically when you click Balance it says I have PAX < 1, and is not included in the overall calculation of my balance.

**Comment by xmatthias** [comment]
This means that it does recognize that you have PAX in your account - however it's < 1$, which is excluded due to "binance dust", which has the potential to show a very large amount of coins with almost 0 balance.

The limit is 0.0001 BTC - which is ~0.91$ at this moment (according to google - but it'll fluctuate a lot ).

**Comment by Dante2333** [comment]
@xmatthias I'm aware, I was holding around 1500 PAX so that was not the case.

**Comment by xmatthias** [comment]
without the related logs i doubt there is much we can do (i don't currently hold PAX ...)

**Comment by Dante2333** [comment]
It's simply to re-create this issue, you simply buy PAX and query for balance, i can do one, give me a few minutes

**Comment by xmatthias** [comment]
What's the configuration you use for this? (mainly interrested in stake_currency)
Do other currencies you have in your account show up fine?

how exactly is the telegram output? (does it include `PAX: not showing <1$ amount`)?

**Comment by xmatthias** [comment]
Testing the below code returns all zeroes. 
Is this some kind of delisted coin? (sorry if that should be clear, but i have no idea about PAX).

```python
import ccxt
ct = ccxt.binance()
ct.fetch_ticker('PAX/BTC')
```

``` output
{'symbol': 'PAX/BTC',
 'timestamp': 1558080536929,
 'datetime': '2019-05-17T08:08:56.929Z',
 'high': 0.0,
 'low': 0.0,
 'bid': 0.0,
 'bidVolume': 0.0,
 'ask': 0.0,
 'askVolume': 0.0,
 'vwap': 0.0,
 'open': 0.0,
 'close': 0.0,
 'last': 0.0,
 'previousClose': 0.00025175,
 'change': 0.0,
 'percentage': 0.0,
 'average': None,
 'baseVolume': 0.0,
 'quoteVolume': 0.0,
 'info': {'symbol': 'PAXBTC',
  'priceChange': '0.00000000',
  'priceChangePercent': '0',
  'weightedAvgPrice': '0',
  'prevClosePrice': '0.00025175',
  'lastPrice': '0.00000000',
  'lastQty': '0.00000000',
  'bidPrice': '0.00000000',
  'bidQty': '0.00000000',
  'askPrice': '0.00000000',
  'askQty': '0.00000000',
  'openPrice': '0.00000000',
  'highPrice': '0.00000000',
  'lowPrice': '0.00000000',
  'volume': '0.00000000',
  'quoteVolume': '0.00000000',
  'openTime': 1557994136929,
  'closeTime': 1558080536929,
  'firstId': -1,
  'lastId': -1,
  'count': 0}}
```

Since this returns 0 (and not an exception which would be expected from a non-existing pair) we exclude the pair, since 1500 * 0 is 0.

**Comment by xmatthias** [comment]
Seems like the market was switched to be "BTC/PAX" (but the old combination is still returned as ticker).

Should be easy to fix - but i'll need to think of a way to get this working for all pairs, not just the ones we get issues for.

**Comment by Dante2333** [comment]
It's goof to know that most stable pairs run against them, pax usdt, usdc usdt, pax usdc, etc, maybe this could help.
