### ISSUE TITLE
Kraken: rate limit exceeded on `--refresh-pairs-cached` ?

### ISSUE THREAD

**Issue by asmodehn** [freqtrade/freqtrade#1982]
* Python Version: Python 3.7.3
  * CCXT version: ccxt==1.18.805
  * Branch: Develop
  * Last Commit ID: ca7080c2bbf0aef060f5e3385679edb0db98fddb
  
## Step 3: Describe the problem:

Using `backtesting --refresh-pairs-cached` with kraken triggers : 
```
2019-06-28 18:22:25,586 - freqtrade.data.history - INFO - Download history data for pair: "ETH/BTC", interval: 5m and store in user_data/data/kraken.
2019-06-28 18:22:56,161 - freqtrade.exchange.exchange - WARNING - _async_get_candle_history() returned exception: "Could not load ticker history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2019-06-28 18:22:56,161 - freqtrade.exchange.exchange - WARNING - retrying _async_get_candle_history() still for 3 times
```

My configuration has : 
```
"exchange": {
        "name": "kraken",
        "key": "empty",
        "secret": "empty",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 3000
        },
        "pair_whitelist": [
            "ETH/BTC",
            "BCH/BTC",
            "ADA/BTC",
            "XRP/BTC",
            "XTZ/BTC",
            "ZEC/BTC",
            "EOS/BTC",
            "XMR/BTC",
            "XLM/BTC",
            "DOGE/BTC"
        ],
        "pair_blacklist": [

        ]
    },
```

Is it a problem with my configuration, or does anyone else has the same problem ?
How would I go about investigating that further ?

### Steps to reproduce:

  1. Setup kraken exchange, with default strategy.
  2. Attempt backtesting with `--refresh-pairs-cached`
  
### Observed Results:

  * rate limit exceeded

### Expected Results :

  * rate limit not exceeded
Kraken documentation specify a 1 second rate limit for public endpoints.
But even setting 3 seconds doesn't prevent hitting the rate limit.

**Comment by xmatthias** [comment]
you need to be carefull with rate-limits - most exchanges use incremental values - so it may be 1 second - but only 50 per minute (for example) ... 

their [documentation](https://www.kraken.com/features/api#api-call-rate-limit) specifies this differently:

> The user's counter is reduced every couple of seconds, and if the counter exceeds the user's maximum API access is suspended for 15 minutes. Starter verified users have a maximum of 15 and their count gets reduced by 1 every 3 seconds. Intermediate and Pro verified users have a maximum of 20; the count is reduced by 1 every 2 seconds for Intermediate users, and is reduced by 1 every 1 second for Pro users.

one call is 1 "call count".
the count gets reduced by 1 every 3 seconds, . (assuming it's non-authenticated).
that would give you exactly 1 call every 3 seconds - so a Rate-limit of 3000 is too agressive, as you're maxing that out (and ccxt needs to fetch market-data too) - with that, you're > max soon.



Apart from limits -  last time i checked they only had ~3 days of 5m candles (roughly 1000 iirc) of history - so unsuitable or backtesting anyway. This may have changed ...

**Comment by asmodehn** [comment]
Ah thanks for the explanation. Since I was connecting on public API I was not expecting the user part of that documentation to matter, and I was expecting ccxt to handle the details for each exchange, but it probably doesnt, as they can be very specific...
Anyway, I ll keep trying with less agressive rate limit then, until I find a proper rate... Ill see how much data I can retrieve, but thanks for the note.

**Comment by asmodehn** [comment]
FYI, I got back one month of 5m candles (around 12000).

**Comment by xmatthias** [comment]
Good to know - thanks for the info!

**Comment by arasharchor** [comment]
> FYI, I got back one month of 5m candles (around 12000).
@asmodehn 
What do you mean exactly by 5m candles using this library?
