### ISSUE TITLE
Bitstamp has no attribute 'timeframes'

### ISSUE THREAD

**Issue by asmodehn** [freqtrade/freqtrade#1983]
Python Version: Python 3.7.3
    CCXT version: ccxt==1.18.805
    Branch: Develop
    Last Commit ID: ca7080c
  
## Step 3: Describe the problem:

```
Traceback (most recent call last):
  File "/opt/Projects/freqtrade/freqtrade/main.py", line 51, in main
    worker = Worker(args)
  File "/opt/Projects/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/opt/Projects/freqtrade/freqtrade/worker.py", line 51, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/opt/Projects/freqtrade/freqtrade/freqtradebot.py", line 56, in __init__
    self.exchange = ExchangeResolver(self.config['exchange']['name'], self.config).exchange
  File "/opt/Projects/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 31, in __init__
    self.exchange = Exchange(config)
  File "/opt/Projects/freqtrade/freqtrade/exchange/exchange.py", line 140, in __init__
    self.validate_timeframes(config['ticker_interval'])
  File "/opt/Projects/freqtrade/freqtrade/exchange/exchange.py", line 272, in validate_timeframes
    timeframes = self._api.timeframes
AttributeError: 'bitstamp' object has no attribute 'timeframes'
```

### Steps to reproduce:

  1. Attempt to use bitstamp
  
### Observed Results:

  * Exchange initialization failed
  * Exchange initialization succeed

### What to do ?
Is there a way to fix this ?
If not, how about a way to have it fail in a little bit nicer fashion ?

**Comment by xmatthias** [comment]
> timeframes: An associative array of timeframes, supported by the fetchOHLCV method of the exchange. This is only populated when has['fetchOHLCV'] property is true.

(source: [ccxt docs](https://ccxt.readthedocs.io/en/latest/manual.html?highlight=timeframe)

fetchOHLCV is "emulated" for bitstamp, which means that ccxt uses "some other" means to get some OHLCV data (bitstamp api apparently does not offer a fetchOHLCV method).

Trying that interactively yields 9 5m candles. With that low amount of history,  don't think bitstamp will work with the bot, since almost all indicators require 20-100 candles of history to be populated correctly.


``` python
import ccxt
bst = ccxt.bitstamp()
len(bst.fetch_ohlcv('ETH/BTC', timeframe="5m", limit=500))
```

Yes, we should fail "nicer" ... but running the bot with this exchange will probably not work, sorry

**Comment by asmodehn** [comment]
Hmmm, then : 
- we have a "white list" of known working & well supported exchanges
- shouldn't we also have a "black list" (documented somewhere) of exchanges that are known not to work, for reasons outside of freqtrade control ? I mean I had hoped that bitstamp was "implementable", even if it was not working out of the box...

**Comment by xmatthias** [comment]
well we do:
https://github.com/freqtrade/freqtrade/blob/152e138c17c1f19882c497eb36cee727fb15da57/freqtrade/exchange/exchange.py#L725-L726

we'll add exchanges as we discover problems with them - but we're not actively testing all 100+ exchanges for problems. 
I guess Bitstamp needs to be added to that list

**Comment by asmodehn** [comment]
Oh ok, I didn't noticed that one, I meant on the README ;-)
Anyway, here you go : #1984

**Comment by tomgross** [comment]
Is this still an issue?

```python
In [1]: import ccxt
In [2]: bst = ccxt.bitstamp()
In [3]: len(bst.fetch_ohlcv('ETH/BTC', timeframe="5m", limit=500))
Out[3]: 500
```

Versions:
Python 3.9.1
cxxt 1.41.35 (I think it uses bitstamp API v2 underneath.)

**Comment by xmatthias** [comment]
I don't think anyone has looked into bitstamp again...
