### ISSUE TITLE
Extend the list of 'bad' exchanges

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#1992]
...in addition to #1984, with those of them that also do not return the `timeframes` attribute from ccxt.

The list is the following:
``` bash
$ for i in `./freqtrade/main.py list-exchanges -1`; do ./freqtrade/main.py list-markets --exchange $i --print-list | grep "object has no attribute 'timeframes'"; done
AttributeError: 'anxpro' object has no attribute 'timeframes'
AttributeError: 'anybits' object has no attribute 'timeframes'
AttributeError: 'bcex' object has no attribute 'timeframes'
AttributeError: 'bigone' object has no attribute 'timeframes'
AttributeError: 'bit2c' object has no attribute 'timeframes'
AttributeError: 'bitbay' object has no attribute 'timeframes'
AttributeError: 'bitflyer' object has no attribute 'timeframes'
AttributeError: 'bitforex' object has no attribute 'timeframes'
AttributeError: 'bithumb' object has no attribute 'timeframes'
AttributeError: 'bitsane' object has no attribute 'timeframes'
AttributeError: 'bitso' object has no attribute 'timeframes'
AttributeError: 'bitstamp' object has no attribute 'timeframes'
AttributeError: 'bitstamp1' object has no attribute 'timeframes'
AttributeError: 'bl3p' object has no attribute 'timeframes'
AttributeError: 'braziliex' object has no attribute 'timeframes'
AttributeError: 'btcbox' object has no attribute 'timeframes'
AttributeError: 'btcchina' object has no attribute 'timeframes'
AttributeError: 'btctradeim' object has no attribute 'timeframes'
AttributeError: 'btctradeua' object has no attribute 'timeframes'
AttributeError: 'bxinth' object has no attribute 'timeframes'
AttributeError: 'chilebit' object has no attribute 'timeframes'
AttributeError: 'coinbase' object has no attribute 'timeframes'
AttributeError: 'coincheck' object has no attribute 'timeframes'
AttributeError: 'coinegg' object has no attribute 'timeframes'
AttributeError: 'coinexchange' object has no attribute 'timeframes'
AttributeError: 'coinfalcon' object has no attribute 'timeframes'
AttributeError: 'coinfloor' object has no attribute 'timeframes'
AttributeError: 'coingi' object has no attribute 'timeframes'
AttributeError: 'coinmarketcap' object has no attribute 'timeframes'
AttributeError: 'coinmate' object has no attribute 'timeframes'
AttributeError: 'coinnest' object has no attribute 'timeframes'
AttributeError: 'coinone' object has no attribute 'timeframes'
AttributeError: 'coinspot' object has no attribute 'timeframes'
AttributeError: 'coolcoin' object has no attribute 'timeframes'
AttributeError: 'crex24' object has no attribute 'timeframes'
AttributeError: 'crypton' object has no attribute 'timeframes'
AttributeError: 'deribit' object has no attribute 'timeframes'
AttributeError: 'dsx' object has no attribute 'timeframes'
AttributeError: 'exmo' object has no attribute 'timeframes'
AttributeError: 'exx' object has no attribute 'timeframes'
AttributeError: 'flowbtc' object has no attribute 'timeframes'
AttributeError: 'foxbit' object has no attribute 'timeframes'
AttributeError: 'fybse' object has no attribute 'timeframes'
AttributeError: 'fybsg' object has no attribute 'timeframes'
AttributeError: 'gemini' object has no attribute 'timeframes'
AttributeError: 'hitbtc' object has no attribute 'timeframes'
AttributeError: 'ice3x' object has no attribute 'timeframes'
AttributeError: 'independentreserve' object has no attribute 'timeframes'
AttributeError: 'indodax' object has no attribute 'timeframes'
AttributeError: 'itbit' object has no attribute 'timeframes'
AttributeError: 'lakebtc' object has no attribute 'timeframes'
AttributeError: 'liqui' object has no attribute 'timeframes'
AttributeError: 'liquid' object has no attribute 'timeframes'
AttributeError: 'livecoin' object has no attribute 'timeframes'
AttributeError: 'luno' object has no attribute 'timeframes'
AttributeError: 'lykke' object has no attribute 'timeframes'
AttributeError: 'mixcoins' object has no attribute 'timeframes'
AttributeError: 'negociecoins' object has no attribute 'timeframes'
AttributeError: 'nova' object has no attribute 'timeframes'
AttributeError: 'paymium' object has no attribute 'timeframes'
AttributeError: 'southxchange' object has no attribute 'timeframes'
AttributeError: 'stronghold' object has no attribute 'timeframes'
AttributeError: 'surbitcoin' object has no attribute 'timeframes'
AttributeError: 'therock' object has no attribute 'timeframes'
AttributeError: 'tidex' object has no attribute 'timeframes'
AttributeError: 'urdubit' object has no attribute 'timeframes'
AttributeError: 'vaultoro' object has no attribute 'timeframes'
AttributeError: 'vbtc' object has no attribute 'timeframes'
AttributeError: 'virwox' object has no attribute 'timeframes'
AttributeError: 'xbtce' object has no attribute 'timeframes'
AttributeError: 'yobit' object has no attribute 'timeframes'
AttributeError: 'zaif' object has no attribute 'timeframes'
```

If you agree, I could create a PR.

**Comment by hroff-1902** [comment]
We could ignore all of them and quit execution, even for the `list-markets` subcommand.

However, for development purposes, an option (probably undocumented) like `--ignore-bad-flag` (`--work-with-bad-exchanges` -- propose other name...) can be added.

**Comment by hroff-1902** [comment]
We could also add a reason for each exchange, why it's in the list of bad exchanges. So, for the exchanges above it could be `no timeframe attribute from ccxt`, for bitmex: `various serious problems`, etc.

**Comment by xmatthias** [comment]
no timeframe is not necessarily a problem, so maybe we should just warn about that, (instead of quitting).

The problem with bitstamp is that it only gives a history of ~5 candles (try `fetch_ohlcv('ETH/USD', '5m')` - not the missing timeframes attribute...

**Comment by hroff-1902** [comment]
> no timeframe is not necessarily a problem, so maybe we should just warn about that, (instead of quitting).
> 
> The problem with bitstamp is that it only gives a history of ~5 candles (try `fetch_ohlcv('ETH/USD', '5m')` - not the missing timeframes attribute...

Well, I cherry-picked https://github.com/freqtrade/freqtrade/pull/1988/commits/0c7d14fe50694edd916c550b1c1213990146f648 into #1989, all those exchanges fail in validate_timeframes():

```
2019-07-02 21:22:23,679 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 46, in main
    args.func(args)
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/utils.py", line 61, in start_list_pairs
    exchange = Exchange(config)
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/exchange/exchange.py", line 140, in __init__
    self.validate_timeframes(config['ticker_interval'])
  File "/home/user/freqtrade-wrk/github-hroff-1902/freqtrade/freqtrade/exchange/exchange.py", line 297, in validate_timeframes
    if timeframe not in timeframes:
TypeError: argument of type 'NoneType' is not iterable
```

I guess #1988 may be incomplete yet in sense it does not prevent exception in validate_timeframes()...
Just run the command I stated above:
```
for i in `./freqtrade/main.py list-exchanges -1`; do ./freqtrade/main.py list-markets --exchange $i --print-list; done
```
using the current branch from #1989...

**Comment by hroff-1902** [comment]
What about adding a reason for exchange explaining why it's in the list of bad exchanges (in order to place it in our warning log message)?

**Comment by xmatthias** [comment]
#1988 does "intentionally" raise the exception (so the exception is clearer than simply failing with "timeframe missing"), however the validation is not really required if the output of all other functions is sufficient (for bitstamp it's not ... but that needs to be tested one by one i think).

I was thinking about the reason too - not sure if it should be in the list (converted to dict??) of invalid exchanges, so we can print it, or if it should be in developer.md (or so ...)

For development / testing, i guess we can remove this line from exchange.py ... it'll be developers doing this testing anyway i would think.

**Comment by hroff-1902** [comment]
> I was thinking about the reason too - not sure if it should be in the list (converted to dict??) of invalid exchanges, so we can print it, or if it should be in developer.md (or so ...)

The list of bad exchanges can simply be a list of tuples (optionally):

Pseudocode of the possible implementation in exchange.py:
```
REASON1 = "Some std explaination (no timeframe attribute or something)"
REASON2 = "Whatever std reason"
BAD_EXCHANGES = [('bitmex, "Various critical issues"), 'bitstamp', ('exchange-1', REASON1), ('exchange-2', REASON1), ('exchange-3', REASON2)]
```
So if element is a tuple -- print the reason (second element of the tuple) in the warning...

**Comment by hroff-1902** [comment]
> For development / testing, i guess we can remove this line from exchange.py ... it'll be developers doing this testing anyway i would think.

In this case there is a chance for those changes to be forgotten and commited errorneously by the developer.

**Comment by hroff-1902** [comment]
> #1988 does "intentionally" raise the exception (so the exception is clearer than simply failing with "timeframe missing"), however the validation is not really required if the output of all other functions is sufficient (for bitstamp it's not ... but that needs to be tested one by one i think).

Yes, but due to (I got the reason) https://github.com/ccxt/ccxt/commit/2be61d6b80a7e7e9be44ba5fe0f5bcc54997584d this (#1988) does not work (does not issue the exception)...

**Comment by xmatthias** [comment]
Yes on #1994 

regarding tuple:
i'm personally more a fan of dicts (tuples require us to use `entry[1]` especially if it's not guaranteed that it's a tuple - a dict can be iterated nicer).

The advantage is that it requires a reason - and if we exclude a exchange we have to know why and should also mention this - so optional reasons will lead to mostly no reasons...

```python
BAD_EXCHANGES = {'bitmex': "various reasons",
"bitstamp": REASON1,
"exchange2: REASON2
}
```

**Comment by hroff-1902** [comment]
> regarding tuple:
> i'm personally more a fan of dicts (tuples require us to use `entry[1]` especially if it's not guaranteed that it's a tuple - a dict can be iterated nicer).
> 
> The advantage is that it requires a reason - and if we exclude a exchange we have to know why and should also mention this - so optional reasons will lead to mostly no reasons...
> 
> ```python
> BAD_EXCHANGES = {'bitmex': "various reasons",
> "bitstamp": REASON1,
> "exchange2: REASON2
> }
> ```

Yes, the dict in this format is even better and easier to implement. 👍
