### ISSUE TITLE
freqtrade performs

### ISSUE THREAD

**Issue by aleeepp** [freqtrade/freqtrade#2001]
Hello, I am new here :)

And i have some questions
1) I want to trade alts(example ltc/usd) but in the strategy i need read BTC/USD for have signal to buy or sell.
2) Multiframe , buy on 5min and sold in 1min.
3) Use NN (tensorflow) in the strat.

Can freqtrade help whit this?

Thanks !!!! Its a great work!!

**Comment by hroff-1902** [comment]
Hi there,

1. Read for informative pairs in the freqtrade docs.
2. Resampling can help you. You can try to run freqtrade on 1m timeframe and resample 1m ohlcv to 5m timeframe. You probably find something about this technique here:
https://github.com/freqtrade/freqtrade-strategies
or here:
https://github.com/freqtrade/technical

This can be hard to implement, so you need to be familiar enough with pandas and python...

3. Again, the question, how would you use it. If you know how to apply Neural Networks to the strategy -- get a bucket and implement it, why not...

**Comment by aleeepp** [comment]
Thanks , Yes I implemented a Neural network in gekko (it use Js) but  i need more flexibility for a better strat.

**Comment by xmatthias** [comment]
I'm not sure i understand this last comment - you can use 1m candles, resample these to 5m for buy signals, and use 1m btc/usd data as informative pairs - and feed all that in "whatever" input format your NN needs.

yes, it'll need some knowledge of pandas to get this correct.

however, from the question you asked above, i don't see what else you need - so please explain what other flexibility you'd require.

**Comment by aleeepp** [comment]
I 'll buy on 5 min and sell on 1 min, i 'll use btc/usd like a index and i 'll have a nn for a probability to get long or short trades :), this will be my strat

**Comment by hroff-1902** [comment]
please let us know of your achievements in implementing this strat.

**Comment by hroff-1902** [comment]
Closing it for now. Feel free to reopen it if you have some more inputs to the points you asked.
