### ISSUE TITLE
hyperopt don't use the dataframe indicators of populate_indicators (of curent file) when optimize only roi stoploss

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2013]
## Step 3: Describe the problem:

when running hyperopt with --spaces roi stoploss the populate_buy_trend use the indicators of i think default_strategy instead of use the indicators of the populate_indicators of the current file.

It raise an keyerror exception because he don't find the indicator.

### Steps to reproduce:

  1. Create a custom indicator in hyperopt populate_indicators 
  2. run hyperopt with --spaces roi stoploss
  3. freqtrade raise a key error because he don't find the indicator in the dataframe.

Have a nice day

**Comment by xmatthias** [comment]
Does your custom hyperopt file contain the function `self.custom_hyperopt.populate_buy_trend`?
