### ISSUE TITLE
Not showing in telegram open orders!

### ISSUE THREAD

**Issue by sbralin** [freqtrade/freqtrade#2016]
In installed freqtrade on Ubuntu-desktop 18.04, my custom strategy use only BTC/USDT pair and bot bought BTC, but telegram doesn't show open orders saying no active orders.....
Pls, advise.
{
    "max_open_trades": 1,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "fiat_display_currency": "USD",
    "ticker_interval" : "5m",
    "dry_run": false,	
    "trailing_stop": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 20
    },
    "bid_strategy": {
        "ask_last_balance": 1.0,
        "use_order_book": true,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": true,
            "bids_to_ask_delta": 1
        }
    },
  "ask_strategy": {
    "use_order_book": true,
    "order_book_min": 1,
    "order_book_max": 9
  },
  "exchange": {
    "name": "binance",
    "key": "rLzD8u................................",
    "secret": "xtKM....................................",
    "ccxt_config": { "enableRateLimit": true },
    "ccxt_async_config": {
      "enableRateLimit": true,
      "rateLimit": 400
    },
    "pair_whitelist": [
            "BTC/USDT"
        ],
        "pair_blacklist": [
            "DOGE/BTC"        ]
    },
    "experimental": {
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "capital_available_percentage": 0.5,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "835731063:AAHGvrfBv3E5UUfcI3--H_VHbm727u62CCI",
        "chat_id": "585296593"
    },
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

**Comment by xmatthias** [comment]
Please provide us with the output of the database:
You can have a look at how to connect to the database (here)[https://www.freqtrade.io/en/latest/sql_cheatsheet/].

Then please run `select * from trades;` and post the output here (it should only have one entry - if i understand your report correctly).
