### ISSUE TITLE
Hyperopt "best result" often is NOT the Best

### ISSUE THREAD

**Issue by ZippelZappel** [freqtrade/freqtrade#2025]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Python Version: 3.7.3 
  * CCXT version: 1.18.860
  * Branch: Develop
  * Last Commit ID:
Freqtrade Version 2019-6
  
## Step 3: Describe the problem:
See log. Eval 449 and 467 are higher than "Best result" shown below. I expected the highest evaluated value as "the Best". Any ideas or advices ?

### Observed Results:

   449/500:    112 trades. Avg profit  0.09%. Total profit  **101.18148746 EUR (  10.11Σ%)**. Avg duration 172.6 mins. Objective: 2.02502
   450/500:    230 trades. Avg profit -0.01%. Total profit -30.81940185 EUR (  -3.08Σ%). Avg duration 164.6 mins. Objective: 2.02850
   451/500:     40 trades. Avg profit -0.13%. Total profit -50.54594650 EUR (  -5.05Σ%). Avg duration 120.5 mins. Objective: 2.02541
   452/500:   1465 trades. Avg profit -0.09%. Total profit -1290.23307314 EUR (-128.89Σ%). Avg duration 167.0 mins. Objective: 2.57593
   453/500:    652 trades. Avg profit -0.02%. Total profit -145.69048053 EUR ( -14.55Σ%). Avg duration 207.1 mins. Objective: 2.07578
   454/500:    141 trades. Avg profit -0.07%. Total profit -100.59900836 EUR ( -10.05Σ%). Avg duration 165.3 mins. Objective: 2.07485
   455/500:   1165 trades. Avg profit -0.08%. Total profit -896.72838592 EUR ( -89.58Σ%). Avg duration 154.9 mins. Objective: 2.35437
   456/500:    121 trades. Avg profit -0.05%. Total profit -58.42310132 EUR (  -5.84Σ%). Avg duration 125.5 mins. Objective: 2.01294
   457/500:     90 trades. Avg profit -0.04%. Total profit -37.68264979 EUR (  -3.76Σ%). Avg duration 110.1 mins. Objective: 1.99382
   458/500:     62 trades. Avg profit  0.02%. Total profit  13.08409388 EUR (   1.31Σ%). Avg duration 132.5 mins. Objective: 2.01429
   459/500:    179 trades. Avg profit -0.01%. Total profit -10.66453209 EUR (  -1.07Σ%). Avg duration 130.5 mins. Objective: 1.98882
   460/500:     90 trades. Avg profit  0.07%. Total profit  65.63026070 EUR (   6.56Σ%). Avg duration 116.2 mins. Objective: 1.96749
   461/500:    121 trades. Avg profit -0.04%. Total profit -46.84684483 EUR (  -4.68Σ%). Avg duration 124.5 mins. Objective: 2.00782
   462/500:    577 trades. Avg profit -0.06%. Total profit -320.82412136 EUR ( -32.05Σ%). Avg duration 187.4 mins. Objective: 2.10688
   463/500:     73 trades. Avg profit  0.03%. Total profit  23.15718243 EUR (   2.31Σ%). Avg duration 142.9 mins. Objective: 2.02190
   464/500:    177 trades. Avg profit  0.03%. Total profit  44.76068537 EUR (   4.47Σ%). Avg duration 139.7 mins. Objective: 1.98315
   465/500:    507 trades. Avg profit -0.01%. Total profit -53.53617781 EUR (  -5.35Σ%). Avg duration 182.7 mins. Objective: 2.01481
   466/500:    123 trades. Avg profit  0.05%. Total profit  62.14639411 EUR (   6.21Σ%). Avg duration 130.7 mins. Objective: 1.97919
   467/500:    104 trades. Avg profit  0.09%. Total profit  **91.07926204 EUR (   9.10Σ%)**. Avg duration 144.1 mins. Objective: 1.99251
   468/500:    118 trades. Avg profit  0.04%. Total profit  49.36408256 EUR (   4.93Σ%). Avg duration 134.9 mins. Objective: 1.99046
   469/500:    162 trades. Avg profit  0.01%. Total profit  8.55148220 EUR (   0.85Σ%). Avg duration 124.0 mins. Objective: 1.97805
   470/500:    128 trades. Avg profit  0.05%. Total profit  62.52206204 EUR (   6.25Σ%). Avg duration 127.7 mins. Objective: 1.97381
   471/500:     94 trades. Avg profit -0.04%. Total profit -37.24784570 EUR (  -3.72Σ%). Avg duration 120.4 mins. Objective: 2.00636
   472/500:     49 trades. Avg profit  0.10%. Total profit  51.16263600 EUR (   5.11Σ%). Avg duration 128.0 mins. Objective: 1.99906
   473/500:    295 trades. Avg profit -0.11%. Total profit -325.84859349 EUR ( -32.55Σ%). Avg duration 107.6 mins. Objective: 2.03619
   474/500:     90 trades. Avg profit -0.03%. Total profit -30.37393087 EUR (  -3.03Σ%). Avg duration 118.6 mins. Objective: 2.00272
   475/500:    500 trades. Avg profit -0.00%. Total profit -7.63455922 EUR (  -0.76Σ%). Avg duration 183.4 mins. Objective: 2.00103
   476/500:    121 trades. Avg profit -0.06%. Total profit -71.56995991 EUR (  -7.15Σ%). Avg duration 119.3 mins. Objective: 2.00906
   477/500:     90 trades. Avg profit  0.08%. Total profit  69.72344420 EUR (   6.97Σ%). Avg duration 118.7 mins. Objective: 1.96946
   478/500:    288 trades. Avg profit -0.00%. Total profit -0.45653646 EUR (  -0.05Σ%). Avg duration 151.7 mins. Objective: 1.98814
   479/500:     80 trades. Avg profit -0.04%. Total profit -28.68852908 EUR (  -2.87Σ%). Avg duration 118.0 mins. Objective: 2.00402
   480/500:     99 trades. Avg profit  0.05%. Total profit  50.24047109 EUR (   5.02Σ%). Avg duration 129.7 mins. Objective: 1.98825
   481/500:    161 trades. Avg profit -0.02%. Total profit -38.63228277 EUR (  -3.86Σ%). Avg duration 158.8 mins. Objective: 2.04043
   482/500:    158 trades. Avg profit -0.02%. Total profit -24.49335387 EUR (  -2.45Σ%). Avg duration 144.5 mins. Objective: 2.01743
   483/500:     46 trades. Avg profit  0.16%. Total profit  73.42118256 EUR (   7.33Σ%). Avg duration 141.6 mins. Objective: 2.01069
   484/500:    190 trades. Avg profit -0.03%. Total profit -64.99565954 EUR (  -6.49Σ%). Avg duration 133.9 mins. Objective: 2.00871
   485/500:     76 trades. Avg profit  0.04%. Total profit  33.43001242 EUR (   3.34Σ%). Avg duration 108.5 mins. Objective: 1.97173
   486/500:    107 trades. Avg profit -0.04%. Total profit -46.55441757 EUR (  -4.65Σ%). Avg duration 119.3 mins. Objective: 2.00455
   487/500:    697 trades. Avg profit -0.10%. Total profit -669.69903834 EUR ( -66.90Σ%). Avg duration 138.9 mins. Objective: 2.16195
   488/500:    624 trades. Avg profit -0.04%. Total profit -231.45146259 EUR ( -23.12Σ%). Avg duration 192.3 mins. Objective: 2.08372
   489/500:    177 trades. Avg profit -0.10%. Total profit -172.96762611 EUR ( -17.28Σ%). Avg duration 128.0 mins. Objective: 2.03995
   490/500:     65 trades. Avg profit -0.15%. Total profit -98.32914738 EUR (  -9.82Σ%). Avg duration 129.6 mins. Objective: 2.04674
   491/500:    652 trades. Avg profit -0.07%. Total profit -440.31452529 EUR ( -43.99Σ%). Avg duration 178.4 mins. Objective: 2.13562
   492/500:     61 trades. Avg profit  0.07%. Total profit  43.68463174 EUR (   4.36Σ%). Avg duration 137.6 mins. Objective: 2.01120
   493/500:    100 trades. Avg profit -0.05%. Total profit -45.67548571 EUR (  -4.56Σ%). Avg duration 128.7 mins. Objective: 2.01853
   494/500:    141 trades. Avg profit -0.03%. Total profit -47.25150389 EUR (  -4.72Σ%). Avg duration 122.5 mins. Objective: 2.00006
   495/500:     87 trades. Avg profit -0.00%. Total profit -0.72843077 EUR (  -0.07Σ%). Avg duration 112.2 mins. Objective: 1.98516
   496/500:    223 trades. Avg profit  0.03%. Total profit  62.46802254 EUR (   6.24Σ%). Avg duration 137.8 mins. Objective: 1.96336
   497/500:     45 trades. Avg profit -0.12%. Total profit -55.98669871 EUR (  -5.59Σ%). Avg duration 118.8 mins. Objective: 2.02358
   498/500:    142 trades. Avg profit -0.01%. Total profit -17.42789054 EUR (  -1.74Σ%). Avg duration 122.2 mins. Objective: 1.98947
2019-07-16 10:07:05,119 - freqtrade.optimize.hyperopt - INFO - Saving 498 evaluations to 'user_data/hyperopt_results.pickle'
2019-07-16 10:07:05,356 - freqtrade.optimize.hyperopt - INFO - Best result:
   662 trades. Avg profit  0.01%. Total profit  **80.43764356 EUR (   8.04Σ%)**. Avg duration 169.3 mins.

**Comment by hroff-1902** [comment]
Right, because hyperopt does not optimize total profit (nor average profit). It optimizes the values of the objective function (optimization loss-function). The default implementation of the loss-function consists of several components with their weights, including avarage trade duration and count of trades. If you wish to optimize with another objective function (taking into account only total profit, for example), you may try to assign 0 as weights to the trade_count and/or trade_loss and duration_loss components in the `calculate_loss()` method in `freqtrade/optimize/hyperopt.py`. However, this part is under active refactoring in the meantime and you'll be able to write and use your own custom objective functions for hyperoptimization pretty soon.

You may have a look at #2024 if you have programming skills, that contains current rafactoring results for hyperopt objective functions.

**Comment by ZippelZappel** [comment]
Thanks hroff, i really do appreciate this explanation. I'm a newbee in python and do my very best to optimize FT for my aims. Thanks a lot. Have a nice day.
