### ISSUE TITLE
"BCHABC/BTC" not available in binance

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2030]
Title says it.

**Comment by hroff-1902** [comment]
The symbol for this pair is 

```
python3 ./scripts/get_market_pairs.py binance|grep 'BCHABC'
...
BCHABCBTC       BCH/BTC         BCH             BTC            
BCHABCPAX       BCH/PAX         BCH             PAX            
BCHABCTUSD      BCH/TUSD        BCH             TUSD           
BCHABCUSDC      BCH/USDC        BCH             USDC           
BCHABCUSDT      BCH/USDT        BCH             USDT   
```

If it's not correct -- this should be issued into ccxt project.

**Comment by hroff-1902** [comment]
Seems ccxt 'renames' BCHABC into a well-known symbol, BCH (like it renames XBT to BTC in pairs). I don't know if it's correct or not. Pls ask there.

**Comment by xmatthias** [comment]
Basically you can use "BCH/BTC"  in your whitelist and ccxt will convert this to BCHABC/BTC towards the exchange.

I think this has been done since binance did some odd things with BCH (renaming it to BCHABC for one ...)

**Comment by hroff-1902** [comment]
Yes, ccxt substitutes 'BCHABC' with 'BCH' for binance using its `safe_currency_code()` method. As it does for some other currencies ('XBT' --> 'BTC', for example). 

The current ccxt's substitution table is:
```
commonCurrencies = {
        'XBT': 'BTC',
        'BCC': 'BCH',
        'DRK': 'DASH',
        'BCHABC': 'BCH',
        'BCHSV': 'BSV',
    }
```

**Comment by hroff-1902** [comment]
Closing the issue since it was answered. 
Feel free to reopen it.
