### ISSUE TITLE
Different results with backtest/hyperopts

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2036]
hyperopts: python3 freqtrade -c config.json hyperopt --customhyperopt Test -i 1h -e 100 -s all--timerange 20190713 - 20190718
5 trade avg profit 3.02% 15.12% total

backtest: freqtrade -s hyperteststrategy -c config.json backtesting --timerange 201907 - 20190718
avg.profit 0.31% ı cum profit 0.31% ı tot profit 0.10%

**Comment by hroff-1902** [comment]
what exchange and how many pairs are used?

**Comment by gitgitgat** [comment]
binance, btc/usdt

**Comment by hroff-1902** [comment]
The user was using old (June 12) version of freqtrade, that have not yet included #2009 fix yet.

Not a bug, closing it.
