### ISSUE TITLE
ccxt.base.errors.InvalidOrder:

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#2037]
### Observed Results:

I have set "stoploss on exchange", below error messages are popping up - what is the problem?

### Relevant code exceptions or logs:

  ```
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/exchange/exchange.py", line 395, in create_order
    amount, rate, params)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 710, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 433, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1233, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 458, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 551, in fetch
    self.handle_errors(response.status_code, response.reason, url, method, headers, http_response, json_response)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1216, in handle_errors
    raise ExceptionClass(self.id + ' ' + message)
ccxt.base.errors.InvalidOrder: binance Order would trigger immediately.

During handling of the above exception, another exception occurred:

  ```

**Comment by xmatthias** [comment]
Please fill out the default issue form so we have some basic information about the version you're running.
This form is not there for fun ...

**Comment by Prossi79** [comment]
sorry Matthias ... here we go:

## Step 2: Describe your environment

  * Python Version: Python 3.7.3
  * CCXT version: ccxt==1.18.860
  * Branch: Develop
  * Last Commit ID: cbe25178d711358bdb883a04602abd6827fbb068

anything else needed let me know please

**Comment by Dante2333** [comment]
@Prossi79 try putting and answering all the questions on the form please, its easier for the devs then to inquiry in what they need to ask to see whats the problem.

**Comment by xmatthias** [comment]
a few log-messages before / after this exception would help too (always try to include more from the stacktrace - it's better to have too much information [within reason] than too less)

Also the 2nd stacktrace is missing (`During handling of the above exception, another exception occurred:`, so we know the exception was raised in `create_order` - but not where it came from.

I hope you still have more from this log, otherwise there is no way to tell you what the problem really was, and to work on a fix, sorry.

**Comment by Prossi79** [comment]
Hey - sorry for my late reply, I was out of twon for some days. Unfortunately I dont have any more logs available. 

If I recap what has happened -> for any reasons my FT bot was telling me "Process Died" ... I restarted it, so far so good. The bot was for some hours, in the meantime the price of the pair being traded was decreasing to the trailing stopploss being reached before my bot was off.

Difficult to recap without the full log ... if this will happen again I will be more detailed with my issue.

Until then I will close the issue.
