### ISSUE TITLE
running Freqtrade as a system service in Ubuntu

### ISSUE THREAD

**Issue by whatTHEh3ll** [freqtrade/freqtrade#2039]
Can you go into a little more depth on how to run Freqtrade as a system service on Ubuntu 18?

**Comment by hroff-1902** [comment]
See the description in https://github.com/freqtrade/freqtrade/pull/1648#issue-259776847

**Comment by hroff-1902** [comment]
I implemented it several months ago and slightly documented in that pull request, but had no time to make a more wide description in the docs. You can help the project if you reproduce the deployment that uses the system service (and sd-notify) feature and write resulting notes on this that could be inserted into the docs.

**Comment by hroff-1902** [comment]
btw, even without sd-notify, freqtrade can run as a systemd service.

This is already described in the docs in detail, see https://www.freqtrade.io/en/latest/installation/#7-optional-configure-freqtrade-as-a-systemd-service.

Have you read it?

**Comment by hroff-1902** [comment]
Closing the issue since it was answered.
Feel free to reopen it.
