### ISSUE TITLE
Start Bot docs differ from what `setup.sh --install` advises

### ISSUE THREAD

**Issue by metaperl** [freqtrade/freqtrade#2042]
The [`start bot` part of the docs](https://www.freqtrade.io/en/latest/bot-usage/) does not advise "You can now use the bot by executing 'source .env/bin/activate; freqtrade'." but `setup.sh --install` does and it is very useful advice.

Should the manual be updated with this advice?

**Comment by xmatthias** [comment]
i guess it should - but we have multiple install methods documented (`setup.sh` being one of them), so activating the environment will fail if you use docker, or if you use conda (raspberrypi), so until now we kept the "start bot" part cleanish from these things.

**Comment by hroff-1902** [comment]
@metaperl Could you suggest us what should particularly be changed in the docs? Or create a pull request with the changes to the docs...

**Comment by hroff-1902** [comment]
Closing it since it was resolved by already merged #2050.
