### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by guillermoaviles** [freqtrade/freqtrade#2047]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: 3.6
  * CCXT version: 1.18.756
  * Branch: Don't know
  * Last Commit ID: ??
  
## Step 3: Describe the problem:

I'm fairly new to freqtrade and python so I must have changed something that I should not have. I've been messing around with some strategies and trying to make hyperopt files for them. 

*Explain the problem you have encountered*

Now when I try to run a strategy, it tries to go through freqtrade.optimize instead of freqtrade.strategy

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```
(.env) gjbit@gjbitvb:~/freqtrade$ python3 ./freqtrade/main.py -c config.json -s REINFORCEDQUICKIE 
Traceback (most recent call last):
 File "./freqtrade/main.py", line 14, in <module>
   from freqtrade.freqtradebot import FreqtradeBot
 File "/home/gjbit/freqtrade/freqtrade/freqtradebot.py", line 18, in <module>
   from freqtrade.edge import Edge
 File "/home/gjbit/freqtrade/freqtrade/edge/__init__.py", line 16, in <module>
   from freqtrade.optimize import get_timeframe
 File "/home/gjbit/freqtrade/freqtrade/optimize/__init__.py", line 12, in <module>
   from freqtrade.optimize.reinforced_quickie import REINFORCEDQUICKIE
ModuleNotFoundError: No module named 'freqtrade.optimize.reinforced_quickie'

**Comment by xmatthias** [comment]
Please check the file `freqtrade/optimize/__init__.py`.
From the log, it seems like you modified this to improt something called `REINFORCEDQUICKIE` or `reinforced_quickie`.

**Comment by hroff-1902** [comment]
> Branch: Don't know
How can this be? How have you installed freqtrade?

**Comment by guillermoaviles** [comment]
@xmatthias I was trying to test a hyperopt file for that strategy. That's why I changed the init file. I changed it back bun now I get this message.

(.env) gjbit@gjbitvb:~/freqtrade$ python3 ./freqtrade/main.py -c config.json -s REINFORCEDQUICKIE 
Traceback (most recent call last):
 File "./freqtrade/main.py", line 14, in <module>
   from freqtrade.freqtradebot import FreqtradeBot
 File "/home/gjbit/freqtrade/freqtrade/freqtradebot.py", line 18, in <module>
   from freqtrade.edge import Edge
 File "/home/gjbit/freqtrade/freqtrade/edge/__init__.py", line 17, in <module>
   from freqtrade.strategy.interface import SellType
 File "/home/gjbit/freqtrade/freqtrade/strategy/__init__.py", line 8, in <module>
   from freqtrade.reinforced_quickie import REINFORCEDQUICKIE
ModuleNotFoundError: No module named 'freqtrade.reinforced_quickie'

**Comment by guillermoaviles** [comment]
@hroff-1902 I don't remember what I installed it as. How can I find that out?

**Comment by hroff-1902** [comment]
> @hroff-1902 I don't remember what I installed it as. How can I find that out?

Save your current freqtrade directory and install freqtrade again from scratches in a sep. directory following the docs: https://www.freqtrade.io/en/latest/installation/. You can choose between current develop or current master branches.

Then copy your strategy and/or hyperopt file from the location where you saved it into the user_data/strategies and user_data/hyperopts directories in the new actual freqtrade installation.

Devs cannot support unknown versions of the app that are in the unknown state.

**Comment by xmatthias** [comment]
you could try to run `git checkout freqtrade/strategy/__init__.py` before reinstalling (aparently this file changed too).

Also, the output of `git status` would help - since it would show which files have changed.

**Comment by guillermoaviles** [comment]
I was able to fix it. The problem was I removed .strategy from the path!

**Comment by hroff-1902** [comment]
Okay, closing the issue then.
Feel free to reopen if you decide something is left regarding it.
