### ISSUE TITLE
[discussion/idea]Dry run: clean persistence

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2061]
In the meantime, if the bot is running in dry-run mode, creates a trade and then fails (at least due to unhandled exception, maybe same can be found if it's stopped with Ctrl+C), the open trade is left in the database. When the bot is restarted, it handles that trade in the terms of new session, while new run should start from scratches.

It's okay to leave open trades in the database in the live-run mode while the trades left on the exchange, but in the dry-run it should start every time from the scratches.

So the cleaning of the trades should be performed somewhere in the handler of the exceptions in main.py for dry-run...

As an alternative, the bot could clean persistence at the start of new dry-run session, but it should destinguish between dry-run and live-run in the database in this case...

**Comment by xmatthias** [comment]
I disagree with this.

We do clean **open orders** for dry-run (since they are only stored in memory) as part of startup.

However, if running the bot in dry-run, i would want to be able to restart it (and had 3 open trades, for example) - then i expect these 3 open trades to be there afterwards too - and they shall then be handled as they would in live). It's unrealistic to assume that a bot restart will sell / remove the trades (they could be good or bad - but a restart should not have an effect on this).

If you want to start from scratch each time, then don't define `--db-url ` so it's using the in-memory sqlite database - or delete the database each time ?

**Comment by hroff-1902** [comment]
> We do clean open orders for dry-run (since they are only stored in memory) as part of startup.
Have not noticed it, I was using the db for dry-run...

> i would want to be able to restart it

Hmm, agree, need to think of it. You see, use cases people use differ...

In any case, in my opinion, a user should preferably not open and clean the database or remove database files, There should be probably a cli option to start from the scratches -- and remove the trades either at shutdown or at the start (or both)... Or maybe running with no db is just okay, need to think and explore the code...

**Comment by xmatthias** [comment]
well "no db" is not really no db, but an in-memory sqlite database ...

so the database is there as long as the process lives.
For dry-run i would want to inspect trades afterwards (probably) ... so deleting at shutdown is not a good idea - if at any time, then startup - but then again - that's a very limited usecase to me...

**Comment by hroff-1902** [comment]
> well "no db" is not really no db, but an in-memory sqlite database ...

yeah, I know

> so the database is there as long as the process lives.
> For dry-run i would want to inspect trades afterwards (probably) ... so deleting at shutdown is not a good idea - if at any time, then startup - but then again - that's a very limited usecase to me...

well, I probably meant not deleting the entries from the database, but closing the open trades...

Assume I changed the strategy and now it produces sell signal very seldom and roi also waits for long period of time. If I have an open trade from the previous dry-run, I will unexpectedly found after long period of time that the strategy closed the trade. And it's result can be awful since long time till opening time, it can produce huge loss or profit, which is not related to the current strategy I'm running the dry-run with... 

Your usecase (restarting the dry-run mode) has only meaning if the strategy and the config was not changed. In other cases it produces strange and wrong results...

**Comment by xmatthias** [comment]
well if the strategy was changed, i would want a completely empty database (so i use a different name for the database file) ... otherwise /profit reports (and similar) will be incorrect anyway...

**Comment by hroff-1902** [comment]
closing it since dry-run uses in-memory db by default, which is okay and the data will not be kept between runs in dry mode.

I have not realized this before since I've had a db-file set in my common dry-run configuration.
