### ISSUE TITLE
Insufficient funds error

### ISSUE THREAD

**Issue by sbralin** [freqtrade/freqtrade#2065]
I have account in hitbtc and started freqtrade in real account with stake_amount: "unlimited, but I got error.
...........................
WARNING - Unable to create trade: Insufficient funds to create limit buy order on market BTC/USDT.Tried to buy amount 0.01394 at rate 9503.98 (total 132.48548119999998).Message: hitbtc2 {"error":{"code":20001,"message":"Insufficient funds","description":"Check that the funds are sufficient, given commissions"}}
Pls, advice....

And second question how to set stake amount as % of my balance?

**Comment by xmatthias** [comment]
if you set stake_amount to unlimited, then the bot will use "available amount" / "max_open_trades".

So assuming you have 100 usdt, and max_open_trades set to 4 - then it would buy 4 trades with 25usdt each, unless you're using edge, which has it's own method for position sizing.

**Comment by sbralin** [comment]
Hi, is that possible to configure to use stake amount only 90%, on
unlimited and trades 1?

**Comment by xmatthias** [comment]
no, in that case you'll need to set `stake_amount` to the absolute value of 90% (basically doing the 90% calculation yourself).

**Comment by sbralin** [comment]
I have problems with insufficient funds error when trying to buy limit
order on unlimited stake amount, how to fix it?

**Comment by xmatthias** [comment]
well according to the message above, the bot tried to buy for `132.48548119999998 USDT`. How much have you got in your wallet?

Also, hitbtc is not a "officially" supported exchange, so it's possible that it requires some space to be left for fees - which is not the case for binance (which subtracts it from the order)...

these are the subtilities which makes supporting many exchanges difficult :(

**Comment by sbralin** [comment]
I got problems it was wrong stake amount... it is ok.
I am testing bot but i need for multiple users bot trading with multi
exchange accounts is that possible to do that?

**Comment by xmatthias** [comment]
you can always run multiple instances of the bot (make sure to use different databases and configuration files).

One bot instance is limited to one useraccount and one exchange.

**Comment by sbralin** [comment]
Ok, thanks! Can two accounts use one db?

**Comment by sbralin** [comment]
Can i make change in source code in freqtradebot to configure stake amount
to be default as 90% of stake value?

**Comment by hroff-1902** [comment]
> Can i make change in source code in freqtradebot to configure stake amount to be default as 90% of stake value?

Let's file it as a sep. feature request, as a proposal for enhancement. Could you create a new issue about this so that it will not be related with the first point -- an error, stated above?

**Comment by hroff-1902** [comment]
Closing it since the original question was answered and the reason for the issue found.
Feel free to reopen it.
Create pls separate issues for other questions not related to the original one.
