### ISSUE TITLE
Potential dependency conflicts between freqtrade and urllib3

### ISSUE THREAD

**Issue by NeolithEra** [freqtrade/freqtrade#2077]
Hi, as shown in the following full dependency graph of  **_freqtrade_**, freqtrade requires _**urllib3**_ (the latest version)， while the installed version of **_requests_**(2.22.0) requires _**urllib3>=1.21.1,<1.26**_.

According to Pip's “first found wins” installation strategy, _**urllib3 1.25.3**_ is the actually installed version.  

Although the first found package version _**urllib3 1.25.3**_ just satisfies the later dependency constraint （_**urllib3>=1.21.1,<1.26**_), it will lead to a build failure once developers release a newer version of **_urllib3_**.

### Dependency tree--------
```
freqtrade(version range:)
| +-ccxt(version range:)
| +-SQLAlchemy(version range:)
| +-python-telegram-bot(version range:)
| +-arrow(version range:)
| +-requests(version range:)
| | +-chardet(version range:>=3.0.2,<3.1.0)
| | +-idna(version range:>=2.5,<2.9)
| | +-urllib3(version range:>=1.21.1,<1.26)
| | +-certifi(version range:>=2017.4.17)
| +-urllib3(version range:)
| +-wrapt(version range:)
| +-pandas(version range:)
| +-scikit-learn(version range:)
| +-scipy(version range:)
| +-joblib(version range:)
| +-jsonschema(version range:)
| +-TA-Lib(version range:)
| | +-numpy(version range:)
| +-tabulate(version range:)
| +-cachetools(version range:)
| +-coinmarketcap(version range:)
| | +-requests(version range:>=2.18.4)
| | | +-chardet(version range:>=3.0.2,<3.1.0)
| | | +-idna(version range:>=2.5,<2.9)
| | | +-urllib3(version range:>=1.21.1,<1.26)
| | | +-certifi(version range:>=2017.4.17)
| | +-requests_cache(version range:>=0.4.13)
| +-scikit-optimize(version range:)
| +-python-rapidjson(version range:)
| +-py_find_1st(version range:)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution
1.	Fix your direct dependencies to be **_urllib3>=1.21.1,<1.26_** and **_requests==2.22.0_**, to remove this conflict. 
        I have checked this revision will not affect your downstream projects now.

2.	Remove your direct dependency urllib3, and use the library urllib3 transitively introduced by requests.

@#1xmatthias Please let me know your choice.
I can submit a PR to fix this issue.

**Comment by xmatthias** [comment]
I think we pinned urllib3 due to a problem with requests (and probably forgot to unpin)

I'll look into it - i suspect we can simply update urllib to the latest version, but i'll need to test a little

**Comment by hroff-1902** [comment]
I'm a kind of doubting...
https://github.com/Netflix/bless/issues/98

**Comment by NeolithEra** [comment]
@hroff-1902 What are your doubts?

**Comment by hroff-1902** [comment]
That you are actually an AI... 😁

**Comment by NeolithEra** [comment]
@hroff-1902 Sorry, I am not an AI, but I can become an AI in the future. ^_^

**Comment by xmatthias** [comment]
Thanks for the headsup, since requests has been upgrade we can safely update urllib3 now :+1:
