### ISSUE TITLE
ImportError: libta_lib.so.0:

### ISSUE THREAD

**Issue by mace2113** [freqtrade/freqtrade#2087]
## Step 1: Have you search for this issue before posting it?

Yes similar to #1676 #2032 #1813 

## Step 2: Describe your environment

  * Python Version: 3.6.8
  * Branch: Master
  * Last Commit ID: 4c005e70
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

1. git clone https://github.com/freqtrade/freqtrade.git
2. cd freqtrade
3. 
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar xvzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          sed -i.bak "s|0.00000001|0.000000000000000001 |g" src/ta_func/ta_utility.h
          ./configure --prefix=/usr/local
          make
          sudo make install
          cd ..
          rm -rf ./ta-lib*
4. ./setup.sh --install
5. source .env/bin/activate
6. python3.6 ./freqtrade/main.py -c config.json

### Observed Results:
         Traceback (most recent call last):
          File "./freqtrade/main.py", line 19, in <module>
          from freqtrade.worker import Worker
          File "/home/steve/freqtrade/freqtrade/worker.py", line 14, in <module>
         from freqtrade.freqtradebot import FreqtradeBot
         File "/home/steve/freqtrade/freqtrade/freqtradebot.py", line 18, in <module>
         from freqtrade.edge import Edge
         File "/home/steve/freqtrade/freqtrade/edge/__init__.py", line 15, in <module>
         from freqtrade.strategy.interface import SellType
         File "/home/steve/freqtrade/freqtrade/strategy/__init__.py", line 7, in <module>
         from freqtrade.strategy.default_strategy import DefaultStrategy  # noqa: F401
         File "/home/steve/freqtrade/freqtrade/strategy/default_strategy.py", line 3, in <module>
         import talib.abstract as ta
         File "/home/steve/freqtrade/.env/lib/python3.6/site-packages/talib/__init__.py", line 43, in       <module>
         from ._ta_lib import (
         ImportError: libta_lib.so.0: cannot open shared object file: No such file or directory

I get this Import error. I looked through the issues and found the fix to be adding the following:

         export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

However I have to do this every time I open terminal as the settings reset. I did see the permanent fix although i didnt know how to implement it. 

Is there a perfect way to install everything to not get this error? I also read it might have something to do with installing ta-lib after installing dependencies. What is the correct order to install everything so we dont get these errors?

thanks

**Comment by xmatthias** [comment]
what's your OS? 
the default LD_LIBRARY_PATH is different on every os (mainly between MacOS and Linux ...).

**Comment by hroff-1902** [comment]
> what's your OS?

we should add this point to the issue template...

**Comment by xmatthias** [comment]
Apart from the questions (i assume it's MacOS) ... i think you can add this line to your `~/.profile`

Open `~/.profile` in the editor of your choice (`~` stands for your home directory) and insert the following there:

```
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
```

You'll then need to logout/login to have this change applied.

**Comment by mace2113** [comment]
Thanks I’ll try that. I use Linux. Ubuntu. Do you know why this error happens in the first place? Did I install in the wrong order?

**Comment by hroff-1902** [comment]
@xmatthias 
should not
```
sudo ldconfig
```
be run at the end of the ta-lib installation procedure?
(I wonder why this is still needed in the XXI century...)

**Comment by hroff-1902** [comment]
> Apart from the questions (i assume it's MacOS) ... i think you can add this line to your `~/.profile`
Not always. Depending on a system (Linux, WSL or MacOS -- terminal on MacOS has its own differences IIRC) and scenario (direct login to KDE, using ssh, screen, tmux) it can be `~/.bash_profile` or `~/.bashrc`...

**Comment by xmatthias** [comment]
> (I wonder why this is still needed in the XXI century and why sudo make install for ta-lib does not do it...)

Honestly, because we install ta-lib using `./configure --prefix=/usr/local` - which, according to @mishaker who introduced this change, is required for this to work on a Mac (apparently it creates problems for ubuntu/Linux though).

I don't own a mac so verifying if installing without this on mac would also work is impossible for me.
Maybe we need to use different paths for ta-lib depending on the OS?

**Comment by hroff-1902** [comment]
On my system (also Ubuntu) I have `/usr/local/lib/` in ld.so.conf standard dirs... It's in `/etc/ld.so.conf.d/libc.conf`, which is set up along with the system libc... But sit eems installing ta-lib still needs to run ldconfig to put in in the ld.so cache... That's the strange point... `make install` for ta-lib installs the lib into `/usr/local/lib`, but does not update cache. I wonder why this is still needed in the systems...

We could place both variants (with `--prefix=/usr` for Linuxes and `--prefix=/usr/local` for MacOS) in the docs, the first variant resolves the problem on Linuxes...

**Comment by xmatthias** [comment]
> because we install ta-lib using ./configure --prefix=/usr/local

just to be clear - this part is in `setup.sh` 
honestly, i would prefer not to set `--prefix`at all, since i think then it's system-dependent ... but testing that on all different systems may not be that easy

**Comment by hroff-1902** [comment]
> just to be clear - this part is in `setup.sh`

It's also in `freqtrade/build_helpers/install_ta-lib.sh` (it does not apply `--prefix`, btw) and is a part of manual installation procedure as described in `docs/installation.md` (where `--prefix` is used)...

Seems I found why I was finally able to run freqtrade without docker on my system -- after several attempts I run that script from build_helpers and it does not use `--prefix`... 🤣

**Comment by mace2113** [comment]
Apart from the questions (i assume it's MacOS) ... i think you can add this line to your ~/.profile

Open ~/.profile in the editor of your choice (~ stands for your home directory) and insert the following there:

export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
You'll then need to logout/login to have this change applied.

So does this work for Ubuntu as well? And still confused on what to install first. I’m going to delete my VM and start over. I’d like to get a good grasp on what order to install so I don’t get errors

**Comment by xmatthias** [comment]
first, you install the ta-lib c dependency ... (`build_helpers/install_ta-lib.sh` ...)

then `pip intall numpy`, then `pip install -e .` (that's how i do it, anyway).

The `setup.sh` script will take care of most of this - but apparently has a problem on ubuntu with `LD_LIBRARY_PATH`.

**Comment by mace2113** [comment]
> first, you install the ta-lib c dependency ... (`build_helpers/install_ta-lib.sh` ...)
> 
> then `pip intall numpy`, then `pip install -e .` (that's how i do it, anyway).
> 
> The `setup.sh` script will take care of most of this - but apparently has a problem on ubuntu with `LD_LIBRARY_PATH`.

ok thanks..
also solved it by editing .bashrc and inserting "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"

**Comment by Audition-CSBlock** [comment]
@hroff-1902 
> ```
> sudo ldconfig
> ```

Sorry for the bump but just saying that this fixed it for me, maybe include this in the manual part of the installation? 👍

**Comment by xmatthias** [comment]
Good point - added this now - thanks for noticing (it was part of the setup.sh installation script...)
