### ISSUE TITLE
KuCoin could not update buy order

### ISSUE THREAD

**Issue by yilongwen** [freqtrade/freqtrade#2093]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Ubuntu 1604
  * Python Version: 3.7.3
  * CCXT version: 1.18.1008
  * Branch: Develop
  * Last Commit ID:f0206a90b1504c40e74b1c6bae4c719779cdee85
  
## Step 3: Describe the problem:

The bot is able to place a market buy order on KuCoin. But after the order is been filled(which I can comfirm on exchange), the bot couldn't update the 'completed' market buy order.

### Observed Results:

  * What happened?
The bot gave a 'Bad request' error, saying it could not get trades due to networking error. I suspect that the link of the request, i.e. "https://openapi-v2.kucoin.com/api/v1/fills?symbol=BTC-USDT&startAt=1564998855.765331" is not right, since the timestamp is a decimal number somehow, in stead of an integer.

  * What did you expect to happen?
I expect the bot to get an update when the buy order has been filled.

### Relevant code exceptions or logs:

  ```
 2019-08-05 11:04:05,947 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1, pair=BTC/USDT, amount=0.01698307, open_rate=11694.00000000, open_since=an hour ago)
2019-08-05 11:04:06,517 - freqtrade.exchange.exchange - WARNING - get_trades_for_order() returned exception: "Could not get trades due to networking error. Message: GET https://openapi-v2.kucoin.com/api/v1/fills?symbol=BTC-USDT&startAt=1564998855.765331 400  {"code":"400000","msg":"Bad Request"}"
  ```

**Comment by xmatthias** [comment]
I'm not sure if this bug is with us or ccxt, since i'm not clear on the type ccxt expects for "since", therefore i raised this question to the ccxt project.
https://github.com/ccxt/ccxt/issues/5636

Once they get back - usually within a day or two - we should have clarity on how to approach this issue



*Note: i don't expect this responsiveness from ccxt - it's just what my experience has been so far.*
