### ISSUE TITLE
Strategy list is space separated

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2098]
`--strategy-list Strat1,Strat2` produces an error while `--strategy-list Strat1 Strat2` works

It became a space separated list somehow while its description states it's a comma-separated list:
```
  --strategy-list STRATEGY_LIST [STRATEGY_LIST ...]
                        Provide **a comma-separated list** of strategies to
                        backtest. Please note that ticker-interval needs to be
                        set either in config or via command line. When using
                        this together with `--export trades`, the strategy-
                        name is injected into the filename (so `backtest-
                        data.json` becomes `backtest-data-
                        DefaultStrategy.json`
```

Which direction this should be fixed to?

**Comment by xmatthias** [comment]
it was never a comma seperated list - argparse does not support this and we never split the list manually - so the docstring / documentation is wrong.
