### ISSUE TITLE
Docker - Custom Strategy and Custom Hyperopt

### ISSUE THREAD

**Issue by sidnicholas** [freqtrade/freqtrade#2105]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: ____Ubuntu 18.04
  * Python Version: _____ Python 3.7.3g
  * CCXT version: _____ (`pip freeze | grep ccxt`)_ Not listed with pip freeze
  * Branch: Develop
  * Last Commit ID: _____ 41f24898e5fc29248f82afdd52cbfe12f9a8b9f1
  
## Step 3: Describe the problem:  This is more user error than a problem.  I installed freqtrade using docker.  I had previously been using freqtrade via the virtualenv installation.  All of my custom files were built in the virtualenv.

I successfully installed docker and it works although I am not sure how to use my custom strategy file and my custom hyperopt file.  I added the file to the /user_data/strategy, and user_data/hyperopt directories but I get an error message when running the launch command.

Command I run to execute:
```
ubuntu@ip-172-31-73-195:~/freqtrade$ docker run -v /etc/localtime:/etc/localtime:ro -v ~/.freqtrade/config.json:/freqtrade/config.json -v ~/.freqtrade/tradesv3.sqlite:/freqtrade/tradesvt.sqlite -v ~/.freqtrade/user_data/:/freqtrade/user_data/ freqtrade --strategy BBRSI
```
The error message I get is:
Error - Impossible to load Strategy 'BBRSI'.  This class does not exist of contains Python code errors.

I appreciate any help you can give.

Thanks

-Sidney

 

  ```

**Comment by xmatthias** [comment]
The snippet above assumes you add the strategy to `~/.freqtrade/user_data/strategies/`.

If you have the strategy in another location, then you should adjust the docker mount points (`-v arguments`)  accordingly

**Comment by sidnicholas** [comment]
@xmatthias 
Thanks for your answer.  I had the custom strategy and custom hyperopt file in ~/freqtrade/user_data instead of ~/.freqtrade/user_data.  Both strategy and hyperopt are working now.
