### ISSUE TITLE
Hyperopts error

### ISSUE THREAD

**Issue by Kaidokuni** [freqtrade/freqtrade#2115]
## Step 1: Have you search for this issue before posting it?

Yes but I didn't find a similar issue. 

## Step 2: Describe your environment

  * Operating system: Windows
  * Python Version: 3.7.3(`python -V`)
  * CCXT version:1.18.860 (`pip freeze | grep ccxt`)
  
## Step 3: Describe the problem:

I tried to test a hyperopt strategy by running this command "python ./freqtrade/main.py -c config.json --customhyperopt ABCOPT -e 100" 
I followed the instructions as indicated on "https://github.com/freqtrade/freqtrade/blob/develop/docs/hyperopt.md " , but the same message appear "freqtrade.DependencyException: --strategy configured but not supported for hyperopt". If someone know how to fix this
 
 "(base) C:\Users\john\freqtrade>python ./freqtrade/main.py -c config.json hyperopt --customhyperopt ABCOPT -e 100
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
2019-08-09 17:22:39,435 - freqtrade.loggers - INFO - Verbosity set to 0
2019-08-09 17:22:39,436 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2019-08-09 17:22:39,436 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite://"
2019-08-09 17:22:39,437 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2019-08-09 17:22:39,437 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2019-08-09 17:22:39,437 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 15 ...
2019-08-09 17:22:39,438 - freqtrade.configuration.configuration - INFO - Using data directory: user_data\data\binance ...
2019-08-09 17:22:39,438 - freqtrade.configuration.configuration - INFO - Using Hyperopt file ABCOPT
2019-08-09 17:22:39,438 - freqtrade.configuration.configuration - INFO - Parameter --epochs detected ... Will run Hyperopt with for 100 epochs ...
2019-08-09 17:22:39,438 - freqtrade.configuration.configuration - INFO - Parameter -s/--spaces detected: all
2019-08-09 17:22:39,438 - freqtrade.configuration.configuration - INFO - Parameter -j/--job-workers detected: -1
2019-08-09 17:22:39,439 - freqtrade.configuration.configuration - INFO - Parameter --min-trades detected: 1
2019-08-09 17:22:39,439 - freqtrade.optimize - ERROR - Please don't use --strategy for hyperopt.
2019-08-09 17:22:39,439 - freqtrade.optimize - ERROR - Read the documentation at https://github.com/freqtrade/freqtrade/blob/develop/docs/hyperopt.md to understand how to configure hyperopt.
2019-08-09 17:22:39,439 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 43, in main
    args.func(args)
  File "c:\users\john\freqtrade\freqtrade\optimize\__init__.py", line 69, in start_hyperopt
    config = setup_configuration(args, RunMode.HYPEROPT)
  File "c:\users\john\freqtrade\freqtrade\optimize\__init__.py", line 36, in setup_configuration
    raise DependencyException("--strategy configured but not supported for hyperopt")
freqtrade.DependencyException: --strategy configured but not supported for hyperopt"

**Comment by hroff-1902** [comment]
Hi there,
remove the "strategy" setting in the config.json

**Comment by mace2113** [comment]
What do you mean by remove it? sorry I have the exact same issue

**Comment by hroff-1902** [comment]
> What do you mean by remove it? sorry I have the exact same issue

Check if you find the "strategy" setting in the hyperopt. If so, remove it.

**Comment by mace2113** [comment]
i dont have it there.. its in config_full.json.example but I dont use that one

**Comment by hroff-1902** [comment]
The exception text says that the strategy name cannot be used when you run freqtrade in the hyperopt mode. The strategy name can be set in 2 places: the `--strategy` command line option (and I see it's not there) and in the configuration file used to run hyperopt (the "strategy" setting).

What version of freqtrade do you use, guys? (run `freqtrade -V`)

**Comment by mace2113** [comment]
freqtrade 2019.7-dev

**Comment by hroff-1902** [comment]
> freqtrade 2019.7-dev

@Kaidokuni and you?

**Comment by hroff-1902** [comment]
@mace2113 pls attach the exact command you use to run hyperopt as well as your configuration file (do not forget to remove or mask telegram and exchange token. secret, etc.)

**Comment by Kaidokuni** [comment]
Hi @hroff-1902, 
I removed the "strategy" part from the config.json as you said and it worked ! Thanks for that !

But now I have to deal with an other issue " hyperopt = self._load_object(paths=abs_paths, object_type=IHyperOpt,
AttributeError: 'HyperOptResolver' object has no attribute '_load_object'"

I was trying to fix it and I noticed that "https://github.com/freqtrade/" had new files that I didn't have when I downloaded it, I understand it will constantly have new files because it will always improving, so how can I update my freqtrade? Do I have to copy each new file manually?

**Comment by hroff-1902** [comment]
> Hi @hroff-1902,
> I removed the "strategy" part from the config.json as you said and it worked ! Thanks for that !
> 
> But now I have to deal with an other issue " hyperopt = self._load_object(paths=abs_paths, object_type=IHyperOpt,
> AttributeError: 'HyperOptResolver' object has no attribute '_load_object'"
> 
> I was trying to fix it and I noticed that "https://github.com/freqtrade/" had new files that I didn't have when I downloaded it, I understand it will constantly have new files because it will always improving, so how can I update my freqtrade? Do I have to copy each new file manually?

No, you should use `git` to fetch the freqtrade.
The best way to cleanup your installation is to copy the current one to an archive and install freqtrade into a new fresh catalog following exactly the installation procedure as it's described in the docs. Now it seems your installation contains mess with files from different versions.

**Comment by hroff-1902** [comment]
Have you came from the udemy Freqtrade course, guys?

**Comment by Kaidokuni** [comment]
Yes is it so obvious haha?
But I did not download their freqtrade I downloaded directly from here. (if it make a difference)

**Comment by mace2113** [comment]
I have yes, but i took the course, deleted everything (entire VM) and reinstalled according to the docs. I used the command:

freqtrade -c config.json -s BBRSI hyperopt --customhyperopt BBRSIOPT -e 100

config.json
{
    "max_open_trades": 10,
    "stake_currency": "BTC",
    "stake_amount": 0.01,
    "fiat_display_currency": "USD",
    "ticker_interval" : "1h",
    "dry_run": true,
    "trailing_stop": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy":{
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 9
    },

    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 500
        },
        "pair_whitelist": [
            "ADA/BTC",
            "BAT/BTC",
            "DASH/BTC",
            "ETC/BTC",
            "ETH/BTC",
            "LSK/BTC",
            "LTC/BTC",
            "NEO/BTC",
            "POWR/BTC",
            "STORJ/BTC",
            "QTUM/BTC",
            "WAVES/BTC",
            "XLM/BTC",
            "XMR/BTC",
            "XRP/BTC",
            "ZEC/BTC",
            "AST/BTC",
            "EOS/BTC",
            "IOTA/BTC",
            "MTH/BTC",
            "TNT/BTC",
            "ONE/BTC",
            "CELR/BTC",
            "TRX/BTC",
            "ZIL/BTC",
            "FTM/BTC",
            "ANKR/BTC",
            "PHB/BTC",
            "REN/BTC",
            "IOTX/BTC",
            "RVN/BTC",
            "POE/BTC",
            "MITH/BTC",
            "IOST/BTC",
            "REQ/BTC",
            "COS/BTC",
            "FET/BTC",
            "FUEL/BTC",
            "DOCK/BTC",
            "TFUEL/BTC",
            "SNM/BTC",
            "VIB/BTC",
            "OST/BTC",
            "WPR/BTC",
            "LEND/BTC",
            "CDT/BTC",
            "BLZ/BTC",
            "GNT/BTC",
            "QLC/BTC",
            "CND/BTC",
            "VIBE/BTC",
            "GTO/BTC",
            "CMT/BTC",
            "ENJ/BTC",
            "BQX/BTC",
            "LOOM/BTC",
            "GO/BTC",
            "DNT/BTC",
            "DUSK/BTC",
            "LRC/BTC",
            "ICX/BTC",
            "SNT/BTC",
            "POLY/BTC",
            "QSP/BTC",
            "LINK/BTC",
            "MANA/BTC",
            "POA/BTC",
            "CVC/BTC",
            "RCN/BTC",
            "OAX/BTC"
        ],
        "pair_blacklist": [
            "BNB/BTC"
        ]
    },

    "experimental": {
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "capital_available_percentage": 0.5,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "",
        "chat_id": ""
    },
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

**Comment by mace2113** [comment]
@hroff-1902 also as far as keeping the bot updated, I noticed setup.sh takes an update parameter.. will executing that every once in a while update everything? virtual env, php etc?
I do a git pull origin command every day bot that doesnt really update the packages right?

**Comment by hroff-1902** [comment]
> @hroff-1902 also as far as keeping the bot updated, I noticed setup.sh takes an update parameter.. will executing that every once in a while update everything? virtual env, php etc?
> I do a git pull origin command every day bot that doesnt really update the packages right?

yes, you can run `./setup.sh -u` if you don't run the bot on Windows as @Kaidokuni does. It will update the bot and the venv with actual dependencies

git pull only updates the bot codebase, to update the dependencies you need to run `pip3 install -e requirements.txt` (ideally after each update of the bot codebase since the dependencies may also update every day...) Maybe this is the reason of your problem. Pls double check that the config you attached is really one used with hyperopt...

**Comment by hroff-1902** [comment]
> freqtrade -c config.json -s BBRSI hyperopt --customhyperopt BBRSIOPT -e 100

My goodness, OMG... `-s BBRSI hyperopt` -- that's it

```
  -s NAME, --strategy NAME
                        Specify strategy class name (default:
                        `DefaultStrategy`).
```

**Comment by mace2113** [comment]
sorry i did run it without the -s flag once..although then I got a different error so I started trying stuff untill this error came up..

the error I get when i run it the way you said is:

 

2019-08-09 19:37:04,249 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/steve/freqtrade/.env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2890, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'middle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/steve/freqtrade/freqtrade/main.py", line 43, in main
    args.func(args)
  File "/home/steve/freqtrade/freqtrade/optimize/__init__.py", line 84, in start_hyperopt
    hyperopt.start()
  File "/home/steve/freqtrade/freqtrade/optimize/hyperopt.py", line 327, in start
    preprocessed = self.strategy.tickerdata_to_dataframe(data)
  File "/home/steve/freqtrade/freqtrade/strategy/interface.py", line 396, in tickerdata_to_dataframe
    for pair, pair_data in tickerdata.items()}
  File "/home/steve/freqtrade/freqtrade/strategy/interface.py", line 396, in <dictcomp>
    for pair, pair_data in tickerdata.items()}
  File "/home/steve/freqtrade/user_data/hyperopts/BBRSIOPT.py", line 40, in populate_indicators
    dataframe['bb_middleband1'] = bollinger1['middle']
  File "/home/steve/freqtrade/.env/lib/python3.6/site-packages/pandas/core/frame.py", line 2975, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/steve/freqtrade/.env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2892, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'middle'

**Comment by xmatthias** [comment]
well this error now appears to be a problem with your hyperopts file .... how are you initializing `bollinger1`?

**Comment by mace2113** [comment]
like this:


from functools import reduce
from math import exp
from typing import Any, Callable, Dict, List
from datetime import datetime

import numpy as np# noqa F401
import talib.abstract as ta
from pandas import DataFrame
from skopt.space import Categorical, Dimension, Integer, Real

import freqtrade.vendor.qtpylib.indicators as qtpylib
from freqtrade.optimize.hyperopt_interface import IHyperOpt


 class BBRSIOPT(IHyperOpt):

    @staticmethod
    def populate_indicators(dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe['rsi'] = ta.RSI(dataframe)
        dataframe['sell-rsi'] = ta.RSI(dataframe)

        # Bollinger bands
        bollinger1 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=1)
        dataframe['bb_lowerband1'] = bollinger1['lower']
        dataframe['bb_middleband1'] = bollinger1['middle']
        dataframe['bb_upperband1'] = bollinger1['upper']

        bollinger2 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband2'] = bollinger2['lower']
        dataframe['bb_middleband2'] = bollinger2['middle']
        dataframe['bb_upperband2'] = bollinger2['upper']

        bollinger3 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=3)
        dataframe['bb_lowerband3'] = bollinger3['lower']
        dataframe['bb_middleband3'] = bollinger3['middle']
        dataframe['bb_upperband3'] = bollinger3['upper']

        bollinger4 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=4)
        dataframe['bb_lowerband4'] = bollinger4['lower']
        dataframe['bb_middleband4'] = bollinger4['middle']
        dataframe['bb_upperband4'] = bollinger4['upper']

        return dataframe

    @staticmethod
    def buy_strategy_generator(params: Dict[str, Any]) -> Callable:
        """
        Define the buy strategy parameters to be used by hyperopt
        """
        def populate_buy_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Buy strategy Hyperopt will build and use
            """
            conditions = []
            # GUARDS AND TRENDS
            if 'rsi-enabled' in params and params['rsi-enabled']:
                      conditions.append(dataframe['rsi'] > params['rsi-value'])

            # TRIGGERS
            if 'trigger' in params:
                if params['trigger'] == 'bb_lower1':
                      conditions.append(dataframe['close'] < dataframe['bb_lowerband1'])
                if params['trigger'] == 'bb_lower2':
                      conditions.append(dataframe['close'] < dataframe['bb_lowerband2'])
                if params['trigger'] == 'bb_lower3':
                      conditions.append(dataframe['close'] < dataframe['bb_lowerband3'])
                if params['trigger'] == 'bb_lower4':
                      conditions.append(dataframe['close'] < dataframe['bb_lowerband4'])


            if conditions:
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'buy'] = 1

            return dataframe

        return populate_buy_trend

    @staticmethod
    def indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching strategy parameters
        """
        return [
            Integer(5, 50, name='rsi-value'),
            Categorical([True, False], name='rsi-enabled'),
            Categorical(['bb_lower1','bb_lower2','bb_lower3','bb_lower4'], name='trigger')
        ]

    @staticmethod
    def sell_strategy_generator(params: Dict[str, Any]) -> Callable:
        """
        Define the sell strategy parameters to be used by hyperopt
        """
        def populate_sell_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Sell strategy Hyperopt will build and use
            """
            # print(params)
            conditions = []
            # GUARDS AND TRENDS
            if 'sell-rsi-enabled' in params and params['sell-rsi-enabled']:
                      conditions.append(dataframe['rsi'] > params['sell-rsi-value'])

            # TRIGGERS
            if 'sell-trigger' in params:
                if params['sell-trigger'] == 'sell-bb_lower1':
                      conditions.append(dataframe['close'] > dataframe['bb_lowerband1'])
                if params['sell-trigger'] == 'sell-bb_middle1':
                      conditions.append(dataframe['close'] > dataframe['bb_middleband1'])
                if params['sell-trigger'] == 'sell-bb_upper1':
                      conditions.append(dataframe['close'] > dataframe['bb_upperband1'])


            if conditions:
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'sell'] = 1

            return dataframe

        return populate_sell_trend

    @staticmethod
    def sell_indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching sell strategy parameters
        """
        return [
              Integer(30, 100, name='sell-rsi-value'),
              Categorical([True, False], name='sell-rsi-enabled'),
              Categorical(['sell-bb_lower1',
                           'sell-bb_middle1',
                           'sell-bb_upper1'], name='sell-trigger')
        ]

    @staticmethod
    def generate_roi_table(params: Dict) -> Dict[int, float]:
        """
        Generate the ROI table that will be used by Hyperopt
        """
        roi_table = {}
        roi_table[0] = params['roi_p1'] + params['roi_p2'] + params['roi_p3']
        roi_table[params['roi_t3']] = params['roi_p1'] + params['roi_p2']
        roi_table[params['roi_t3'] + params['roi_t2']] = params['roi_p1']
        roi_table[params['roi_t3'] + params['roi_t2'] + params['roi_t1']] = 0

        return roi_table

    @staticmethod
    def stoploss_space() -> List[Dimension]:
        """
        Stoploss Value to search
        """
        return [
            Real(-0.5, -0.02, name='stoploss'),
        ]

    @staticmethod
    def roi_space() -> List[Dimension]:
        """
        Values to search for each ROI steps
        """
        return [
            Integer(10, 120, name='roi_t1'),
            Integer(10, 60, name='roi_t2'),
            Integer(10, 40, name='roi_t3'),
            Real(0.01, 0.04, name='roi_p1'),
            Real(0.01, 0.07, name='roi_p2'),
            Real(0.01, 0.20, name='roi_p3'),
        ]

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators. Should be a copy of from strategy
        must align to populate_indicators in this file
        Only used when --spaces does not include buy
        """
        dataframe.loc[
                (
                    (dataframe['rsi'] > 35) &
                    (dataframe['close'] < dataframe['bb_lowerband'])
                ),
                'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators. Should be a copy of from strategy
        must align to populate_indicators in this file
        Only used when --spaces does not include sell
        """
        dataframe.loc[
                (
                    (dataframe['close'] > dataframe['bb_middleband'] )
                ),
                'sell'] = 1

        return dataframe

**Comment by hroff-1902** [comment]
Hmm, this one
```
    @staticmethod
    def populate_indicators(dataframe: DataFrame, metadata: dict) -> DataFrame:
...
        # Bollinger bands
        bollinger1 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=1)
        dataframe['bb_middleband1'] = bollinger1['middle']
```
works fine at my site with no errors in the last line... (current develop, Ubuntu)

@mace2113 try to update dependencies (np, pandas) with pip3 (see the command above)

**Comment by xmatthias** [comment]
@hroff-1902 you sure?
`qtpylib` does not use `middle` but `"mid"` as key for the middle band ... 

Reference:

https://github.com/freqtrade/freqtrade/blob/de999424999df46575f262ecc56913703e75060e/freqtrade/vendor/qtpylib/indicators.py#L426-L436


@mace2113 - please replace `'middle'` with `'mid'`, that shoudl fix this error.

**Comment by hroff-1902** [comment]
> @hroff-1902 you sure?

No. 🤣 
I pasted the code into my testing hyperopt, but after this your note I found I have another file in the hyperopts dir with the hyperopt class with the same name. Freqtrade has resolved and used wrong module. Found this in the log, but only after this your note...

(@xmatthias, I said to you, let's allow --strategy-path and --hyperopt-path be a single file i.o. the whole directory. That's the example of an error that can appear when a user just copies the file and forgets to change the name of the class.)

**Comment by mace2113** [comment]
omg ive been at the computer for too long today.. I used mid in the strategy file but for some reason typed middle in opt file.. thanks for the help. much appreciated

**Comment by Kaidokuni** [comment]
I have updated the files and downloaded the ones I didn't have but still stuck at this  :
"Traceback (most recent call last):
  File "./freqtrade/main.py", line 43, in main
    args.func(args)
  File "c:\users\john\freqtrade\freqtrade\optimize\__init__.py", line 84, in start_hyperopt
    hyperopt = Hyperopt(config)
  File "c:\users\john\freqtrade\freqtrade\optimize\hyperopt.py", line 49, in __init__
    self.custom_hyperopt = HyperOptResolver(self.config).hyperopt
  File "c:\users\john\freqtrade\freqtrade\resolvers\hyperopt_resolver.py", line 34, in __init__
    self.hyperopt = self._load_hyperopt(hyperopt_name, extra_dir=config.get('hyperopt_path'))
  File "c:\users\john\freqtrade\freqtrade\resolvers\hyperopt_resolver.py", line 65, in _load_hyperopt
    hyperopt = self._load_object(paths=abs_paths, object_type=IHyperOpt,
AttributeError: 'HyperOptResolver' object has no attribute '_load_object'"

**Comment by hroff-1902** [comment]
@Kaidokuni pls give output of 
```
dir c:\users\john\freqtrade\freqtrade\resolvers
```

**Comment by Kaidokuni** [comment]
"(base) C:\Users\john\freqtrade>dir c:\users\john\freqtrade\freqtrade\resolvers
 Le volume dans le lecteur C s’appelle SYSTEME
 Le numéro de série du volume est 9629-A288

 Répertoire de c:\users\john\freqtrade\freqtrade\resolvers

01/08/2019  07:03    <DIR>          .
01/08/2019  07:03    <DIR>          ..
18/07/2019  19:48             1 851 exchange_resolver.py
09/08/2019  20:57             5 051 hyperopt_resolver.py
18/07/2019  19:48             2 556 iresolver.py
09/08/2019  20:59             1 835 pairlist_resolver.py
09/08/2019  20:59             7 597 strategy_resolver.py
18/07/2019  19:48               471 __init__.py
09/08/2019  21:01    <DIR>          __pycache__
               6 fichier(s)           19 361 octets
               3 Rép(s)  84 188 127 232 octets libres"

**Comment by hroff-1902** [comment]
```
18/07/2019  19:48             2 556 iresolver.py
```
Please compare the date with the date of the last commit (which changed this file) here: https://github.com/freqtrade/freqtrade/commits/develop/freqtrade/resolvers/iresolver.py

You are doing something strange with your installation... It's partly old, partly fresh...

> I have updated the files

How?

> downloaded the ones I didn't have

Sounds even more suspicious... How did you download it?

Or... Are you using your own clone of the freqtrade repo? I saw this once at a one user who also attended the udemy course...

**Comment by Kaidokuni** [comment]
I used the word download but I just CRTL+A, CRTL+C / CRTL+V, for files that I didn't have or that seemed to be upgraded because I don't know how to not do it manually. But hyperopt finally works thank you !!

I summarize in case someone with the same problem end up here, I deleted the strategy part of the config.json file, I upgraded all the files in the following folder to have no import problem between files (/ optimizes, /user_data/hyperopt, /resolver, and constant.py) and changed the middle in mid as said before.

**Comment by hroff-1902** [comment]
> I used the word download but I just CRTL+A, CRTL+C / CRTL+V, for files that I didn't have or that seemed to be upgraded 

Oh my holy <s>cow</s>bear...

> because I don't know how to not do it manually. 

Assume you have already installed python, ta-lib, etc. as written in the doc: https://www.freqtrade.io/en/latest/installation/#windows

Install and use git at your machine. First, "download" the repo in a fresh empty directory:
```
git clone git@github.com:freqtrade/freqtrade.git
```
Then you can simply update the freqtrade codebase to the current state as simple as
```
git pull
```
Do not forget to update the dependencies after running the previous command:
```
pip3 install -r requirements.txt
```
Do not forget to activate venv before.

>But hyperopt finally works thank you !!

You are welcome.
