### ISSUE TITLE
ArrowParseWarnings - turning to errors in 0.15.0

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#2126]
## Describe your environment

  * Operating system: linux 
  * Python Version: 3.7.3
  * Branch:  Develop
  
## Step 3: Related logs

```
site-packages/arrow/factory.py:201: ArrowParseWarning: The .get() parsing method without a format string will parse more strictly in version 0.15.0.See https://github.com/crsmithdev/arrow/issues/612 for more details.

```

we'll need to find all `arrow.get()` calls which don't use one of the supported formats (see github issue https://github.com/crsmithdev/arrow/issues/612) for more details.

**Comment by hroff-1902** [comment]
I already grepped for it for a first glance...

**Comment by xmatthias** [comment]
seems like the warnings will stay for all string-parsing, no matter if it's supported in 0.15.0 or not.

Parsing integers (like `arrow.get(since_ms // 1000)`) will however continue to work, so i think the imact to freqtrade is very limited, if it impacts us at all.

Also all supported date-formats remain there (and we don't use anything exotic afaik) - so i'm not sure if we need to act. We'll however need to do testing once 0.15.0 hits.

**Comment by hroff-1902** [comment]
```
arrow.get(starts, 'YYYYMMDD')
```
in `freqtrade.configuration.arguments.Arguments.parse_timerange()` will also be supported...

**Comment by hroff-1902** [comment]
Have not found any suspicious yet. (grepped for `import|from Arrow|arrow`, `Arrow|arrow`)

I wanted to post here the whole list of appearances where `arrow.get()` is used in the current codebase for review, but a bit lazy for this...

**Comment by xmatthias** [comment]
This has now landed - and i ran through all modes we have and didn't find any issues, so i'll close this issue now.
