### ISSUE TITLE
ModuleNotFoundError: No module named 'arrow'

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2128]
## Step 2: Describe your environment

Ubuntu 18.04
Python 3.7.4
`pip freeze | grep ccxt` doesn't return anything, although it seems to have been installed in the dependencies.
Develop
8c1efec43a71b4e28312010fb8691bfe8badffd7
  
Command line argument: 'python3 -m freqtrade -c config.json backtesting'

Traceback (most recent call last):
  File "/home/snowflake/anaconda2/envs/freqtrade/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/snowflake/anaconda2/envs/freqtrade/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/snowflake/GITHUB/freqtrade/freqtrade/__main__.py", line 9, in <module>
    from freqtrade import main
  File "/home/snowflake/GITHUB/freqtrade/freqtrade/main.py", line 18, in <module>
    from freqtrade.configuration import Arguments
  File "/home/snowflake/GITHUB/freqtrade/freqtrade/configuration/__init__.py", line 1, in <module>
    from freqtrade.configuration.arguments import Arguments, TimeRange  # noqa: F401
  File "/home/snowflake/GITHUB/freqtrade/freqtrade/configuration/arguments.py", line 8, in <module>
    import arrow
ModuleNotFoundError: No module named 'arrow'

**Comment by gitgitgat** [comment]
Had to do soemthing with mixing conda and virtualenv.

**Comment by xmatthias** [comment]
thanks for reporting back.

You'll need to decide between conda env and virtualenv - they don't play together, but more or less replace each other

**Comment by hroff-1902** [comment]
Why do you use conda if it's Ubuntu, not Windows? For example, I've never used conda in my life and live pretty well with this... 😉

**Comment by xmatthias** [comment]
conda is pretty common for data science usecases since it installs the data-science stack (pandas, numpy, jupyter) almost automatically.

Also, it's like the choice of ubuntu over fedora or archlinux... there's no reason other than personal preference

**Comment by Prossi79** [comment]
Hello! I got the same error message while trying to use the Jupyter notebook. A beginner question - how do I make sur eNOT to mix conda and virtual env?

**Comment by xmatthias** [comment]
best - don't use both on the same machine, but decide on one or the other.

the error - `arrow not found` - indicates that you're probably using the wrong kernel - so the next error would probably be "freqtrade not found".

Please look at the jupyter documentation on how to install and add the correct kernel (you need to activate the venv before adding the kernel). But please understand that support for such problems is beyond the scope of this project.

**Comment by Prossi79** [comment]
yes, you are right - for general questions its the wrong place here. I will go to the Slack Channel to solve it

**Comment by gitgitgat** [comment]
Now I am getting that error although the only virtual environment being used is venv. `pip3 install arrow` returns `requirement already satisfied`. The command used is `python3 -m freqtrade .... `

**Comment by xmatthias** [comment]
@gitgitgat the error you're getting is a different one - you seem to have a syntax-error error in your configuration - at offset 337.
this has nothing to do with arrow.

**Comment by gitgitgat** [comment]
But that doesn't explain why the config file works with the 'backtesting', 'hyperopt' commands but not with 'trade'
