### ISSUE TITLE
Find optimal MA's values

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2129]
Adding an option to find the optimal MA value for a given timeperiod within a timeframe in indicator hyperspace, instead of fixed values.

**Comment by hroff-1902** [comment]
Am I right reading it as a proposal for adding the params parameter and a corresponding separate optimization space for the `populate_indicators()` IHyperOpt method?

**Comment by xmatthias** [comment]
maybe take a look at https://github.com/freqtrade/freqtrade-strategies/pull/58/files - it defines a rather clever way to use hyperopt to find the best MA values i didn't even think about yet.

This will also eliminate the need to recalculate the indicators within hyperopt, but instead will allow the calculation before running hyperopt - so should even give a performance boost (as long as the parameters are kept within reasonable numbers).

**Comment by hroff-1902** [comment]
Yes, thanks for the note, I've also noticed this.

That is *another* way of hyperopting MA values.

**Comment by gitgitgat** [comment]
Cool, thanks.
gitgitgat

**Comment by xmatthias** [comment]
I'm going to close this as a sample for this is now available [in the strategy repository](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/hyperopts/AverageHyperopt.py).
