### ISSUE TITLE
No pairs file found with path "user_data/data/binance/pairs.json", --refresh-pairs-cached downloads a different list

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2133]
* Operating system: Ubuntu 18.04 
  * Python Version: _____ 3.6.8
  * CCXT version: _____ ccxt==1.18.1043
  * Branch: Develop
  * Last Commit ID: _____ 8c1efec43a71b4e28312010fb8691bfe8badffd7
  
My pairs.json is found in user_data/data/binance/pairs.json but the following error appears:

2019-08-13 17:38:36,164 - freqtrade.configuration.configuration - INFO - Using data directory: user_data/data/binance ...
2019-08-13 17:38:36,164 - download_backtest_data - INFO - Reading pairs file "user_data/data/binance/pairs.json".
No pairs file found with path "user_data/data/binance/pairs.json".

**Comment by gitgitgat** [comment]
Only possible with the download_backtest_data script, but the -r command did not work in the command line.

**Comment by gitgitgat** [comment]
But -r is not fetching the same list as the user_data/data/pairs.json, when using freqtrade hyepropts for example

**Comment by xmatthias** [comment]
It's not quite clear what you're trying to do ... 

first of all: 
The download-script does not have a `-r` option ... ? 

if you get `2019-08-13 17:38:36,164 - download_backtest_data - INFO - Reading pairs file "user_data/data/binance/pairs.json".
No pairs file found with path "user_data/data/binance/pairs.json".` - then the download-script will fallback to the whitelist in the configuration.

Can you how the output of the pairs.json? (i would assume it has a syntax-error - preventing it from loading correctly).

**Comment by gitgitgat** [comment]
Ok, I have downloaded my pairs.json list with the download-script.
I then go to hyperopts, and use the option -r, but the downloaded list is different from the script and therefore different from the pairs.json. Even when I am using the last 5 days it does not download the same list of pairs. I just selected all binance pairs, except BCHABC/BTC and YOYO/BTC.

**Comment by gitgitgat** [comment]
Oh, it is a different list in the config file and it seems that is the one it downloads. But even then I get an error.

**Comment by xmatthias** [comment]
`pairs.json` is ONLY used by the download script. it is not transferred to the configuration, nor is it used by backtesting / hyperopt.

also - if you use the download script to get data - please **don't** use `-r` - it'll overwrite the data (but based on the whitelist in the configuration), so running the download-script was pointless.

**Comment by hroff-1902** [comment]
I did not get what "but the -r command did not work in the command line" can mean. '-r' is an option for the optimization freqtrade subcommands.

**Comment by hpdeandrade** [comment]
Also having some issues to download pairs data using pairs.json file. I placed the file at ``freqtrade/userdata/data/binance`` but after running the command ``freqtrade download-data --exchange binance`` I get the below error message.

![error](https://user-images.githubusercontent.com/46167400/63391562-3d6cff00-c389-11e9-863a-9d79a95dfe99.JPG)

**Comment by xmatthias** [comment]
@hpdeandrade There seems to be a bug that snuck in which loads the file from the wrong file.

I made the error worse by crashing it recently ... will fix it ... sorry for the inconvenience

**Comment by hpdeandrade** [comment]
Thank you very much for the help.

If I want to change the files destination, which file I have to change (now it's downloading data to user_data/data and not user_data/data/binance...)

Best regards,

**Comment by xmatthias** [comment]
@hpdeandrade 
using `freqtrade --datadir user_data/data/some_directory download-data --exchange binance --pairs ETH/BTC` does work for me.
If you don't specify `--datadir`, then it'll download to `user_data/data/<exchange>`.

If you have futher problems wit this, i suggest to open a new issue, since this is not relate to the original issue here.
