### ISSUE TITLE
Question : use external historical data

### ISSUE THREAD

**Issue by Gabri** [freqtrade/freqtrade#2139]
Hello

I just wanted to know if it is a simple way to load external historical canldes data.
I have, on csv files, 1 min candles data from a lot of Binance pairs since ..the beginning. I'd like to use it on freqtrade.

1. Is there a script to produce data that freqtrade need? (starting from a generical source, like csv)
1. Which is the format of the json used for backtesting? Maybe this : _timestamp, open, close, volume_ ?
1. Is there a way, a script for example, to produce higher timeframes data from a lower ones? (ie: produce 5m candles from 1m ones)

Thanks a lot!

**Comment by hroff-1902** [comment]
3. Have a look at https://github.com/freqtrade/technical, see "resample"

**Comment by Gabri** [comment]
Thank you @hroff-1902, helpful!

**Comment by hroff-1902** [comment]
for 1) and 2) refer to the `parse_ticker_dataframe()` function in the https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/data/converter.py module. It accepts the list with saved history data.

The format of data, as you can see from this function, is pretty simple: these are list of 
`['date', 'open', 'high', 'low', 'close', 'volume']`

**Comment by xmatthias** [comment]
@Gabri 
if you load the data into a pandas dataframe, you should be able to save it in "our" format using to_json with `orient="values"`.

as mentioned above, the columns for the dataframe are `['date', 'open', 'high', 'low', 'close', 'volume']` - 
but note that the date needs to be a millisecond integer timestamp.
Assuming it's a date in CSV (`pd.read_csv(... parse_dates=['date'])`, you'll need to convert it to timestamp first.


``` python
# assuming date is a datetime object
df['date'] = df['date'].astype(np.int64) 
df['date'] = df['date'] // 1000 // 1000
# save
df.to_json(filename, orient="values")
```

**Comment by Gabri** [comment]
Thank you very much. I'll try with your suggestions
