### ISSUE TITLE
Question about possibility of stopping bot when BTC unstable

### ISSUE THREAD

**Issue by mace2113** [freqtrade/freqtrade#2143]
This relates to #320 and might have been solved in #1507 but is there a way to stop the bot from taking trades now when btc/usd behaves a certain way? Im guessing define btc/usd in 'informative pairs' section of Strategy... How would you then refer to it later in the populate buy trend?

**Comment by hroff-1902** [comment]
Please let us know what kind of conditions you would like to check to have a signal to stop trading?
Would you like to stop trading a particular pair only or stop the bot completely till next manual restart?

**Comment by xmatthias** [comment]
data for non-tradable pairs can be read using the dataprovider as documented [here](https://www.freqtrade.io/en/latest/strategy-customization/#ohlcv-historic_ohlcv).

I think i understand what you mean (it's the main reason we have informative pairs) - you can load the BTC data (probably in `populate_indicators()` method) - merge some signal from there to the original dataframe or set a custom variable (`self.BTC_behaves_badly = True`), which you then check in the `populate_buy()` method.
Now how to generate this signal - i'll leave that up to you.


having this automatically stop the bot is not something I'd know how to do (also does not really make sense if you think about it - you'll want to exit your positions cleanly first - and probably want the bot to continue once the "bear run" is over ...).

issuing a `/stop` or `/stopbuy` via telegram would accomplish stopping the bot ... but it's a manual interaction...

**Comment by mace2113** [comment]
> Please let us know what kind of conditions you would like to check to have a signal to stop trading?
> Would you like to stop trading a particular pair only or stop the bot completely till next manual restart?

I would want to stop trading all XXX/BTC pairs, when BTC/USD change on the 15 minute chart goes above 1%. Then i'd like to restart the bot when BTC calms down, for example when the BTC/USD 15m change has been below 1% for at least an hour.




> data for non-tradable pairs can be read using the dataprovider as documented here.
> I think i understand what you mean (it's the main reason we have informative pairs) - you can load the BTC data (probably in populate_indicators() method) - merge some signal from there to the original dataframe or set a custom variable (self.BTC_behaves_badly = True), which you then check in the populate_buy() method.
> Now how to generate this signal - i'll leave that up to you.
> 
> edit: we have a sample for this in the strategy repository here.
> 
> having this automatically stop the bot is not something I'd know how to do (also does not really make sense if you think about it - you'll want to exit your positions cleanly first - and probably want the bot to continue once the "bear run" is over ...).
> issuing a /stop or /stopbuy via telegram would accomplish stopping the bot ... but it's a manual interaction...

Yes i'd want an if statement to adjust a Boolean value which can be checked before buying.. 
if (btc/usd.change.15mInterval > 0.01) 
     self.BTC_behaves_bad = True
else
     false

I'd need it to get checked every time the bots scans for buying opportunities. Ill check the sample you provided.
Also I would want to exit my positions cleanly yes. But moreover it would be my goal not to start new deals while BTC is tanking for example. There are many strategies that may buy at terrible times (when BTC/USD tanks) that would otherwise be great strategies when applied only when BTC is stable. A simple "buy at lower Bollinger band, sell at middle band" is an example.

**Comment by xmatthias** [comment]
no need to stop the bot for me - simply write something to detect if btc/usd tanks (probably usdt, since usd is not available on most exchanges)  and use that as "guard" against buy signals.

**Comment by hroff-1902** [comment]
> I would want to stop trading all XXX/BTC pairs, when BTC/USD change on the 15 minute chart goes above 1%. Then i'd like to restart the bot when BTC calms down, for example when the BTC/USD 15m change has been below 1% for at least an hour.

In my opinion, ATR ('BTCUSDT') on 15m (or even 5m) timeframe as informative pair resolves it. Or other volatility indicator which values you can treat properly to translate to these conditions. Simply check if it's above some value you need to check and do not form the buy signal.

**Comment by mace2113** [comment]
ok so how to I access the ATR of just the pair BTC/USDT?
in the example, we have
      data = self.dp.ohlcv(pair=f"{self.stake_currency}/USDT", ticker_interval=self.ticker_interval)
however there is no option to go; self.dp.ATR for example so im a little confused as to how to get the data.

I tried something like this in the populate_indicators section:
           
    if metadata['pair'] = ("BTC/USDT"):
              if dataframe['ATR'] > 0.5:
                          self.btc_unstable = True

I realized however that informative pairs dont get checked at all in the populate indicators section. So the bot never got to this loop.

**Comment by hroff-1902** [comment]
@mace2113 pls wait till #2149 merged, we are simplifying and cleaning up this stuff a bit...

**Comment by xmatthias** [comment]
@mace2113 i think you misunderstood informative pairs.

populate_indicators is not called for informative pairs.
You need to load this pair with each of the other pairs - calculate the indicator you're interretsed in on that pair - and merge that dataframe to the original dataframe

The informative strategy shows most of this - however using this requires some knowledge on using pandas / python i think, to avoid unexpected problems.

https://github.com/freqtrade/freqtrade-strategies/blob/b05c669a8b7f82c8e0bcb219748f14feaf0f66ce/user_data/strategies/InformativeSample.py#L98-L105

**Comment by mace2113** [comment]
> @mace2113 pls wait till #2149 merged, we are simplifying and cleaning up this stuff a bit...

this really helped actually.. Got it to work now with:
    
     if self.dp:
         data = self.dp.get_pair_dataframe(pair = "BTC/USDT", ticker_interval = "15m")
         dataframe['ATR_BTC'] = ta.ATR(data)

**Comment by xmatthias** [comment]
please don't do it this way, it's problematic and will cause you pain for the following reasons

* It'll fail miserably if your interval (the running one) is not 15m, since the time will not match.
* Also, it'll fail during backtesting if BTC/USDT data is present for a longer / shorter period of time (data will be misaligned).


Use something like in the link i posted above:

``` python
 if self.dp:
     data = self.dp.get_pair_dataframe(pair = "BTC/USDT", ticker_interval = "15m")
     data['ATR_BTC'] = ta.ATR(data)
     dataframe = dataframe.merge(data[["date", "ATR_BTC"]], on="date", how="left")
    # Forwardfill to make sure all rows have a value (if ticker_interval is lower than BTC/USDT interval).
     dataframe['ATR_BTC'] = dataframe['ATR_BTC'].ffill()

```

**Comment by mace2113** [comment]
@xmatthias thanks for the help! all great points

**Comment by mace2113** [comment]
date          open          high           low         close    volume  ao  plus_di  pct_change
     0  2019-08-17 19:50:00+00:00  6.500000e-07  6.500000e-07  6.500000e-07  6.500000e-07     334.0 NaN      NaN         NaN
     1  2019-08-17 19:55:00+00:00  6.500000e-07  6.500000e-07  6.500000e-07  6.500000e-07       0.0 NaN      NaN         NaN
     2  2019-08-17 20:00:00+00:00  6.500000e-07  6.500000e-07  6.500000e-07  6.500000e-07       0.0 NaN      NaN   -0.000917

@xmatthias @hroff-1902 can anyone help me with this while im at it :)
for some reason when i print dataframe to inspect how it works, the time is always 2 hours behind what it should be. line 2 for example is actually the data for 22:00. prob an easy fix for you guys?

**Comment by xmatthias** [comment]
well i assume you're in the CEST timezone? (which is UTC +2) ... 

Times are in UTC timezone ... 2019-08-17 20:00:00+**00:00**

**Comment by xmatthias** [comment]
Closing this since i think the problem was explained ( it was not really about stopping the bot, but preventing new buys, which can be done by using informative pairs).

Feel free to reopen if you still have questions or problems regarding this.
