### ISSUE TITLE
[discussion] Switching from pyup.io to dependabot

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#2147]
Looking at the repositories from [pyup](https://github.com/pyupio/pyup) and dependabot[https://github.com/dependabot/dependabot-core] , it appears like pyup.io is not maintained anymore (last commit 6 months ago - no one answering to issues since 2018).

Also, dependabot is a github application (now) - so i expect the integration to be better.

addition: also mozilla did this switch [source](https://bugzilla.mozilla.org/show_bug.cgi?id=1525923).

Opinions?

**Comment by hroff-1902** [comment]
why not...

**Comment by Rifon** [comment]
https://kara881.livejournal.com/50817.html

пт, 16 авг. 2019 г., 20:37 Matthias <notifications@github.com>:

**Comment by xmatthias** [comment]
Deleted one comment due to beeing spam (link to some russian site, confirmed to be spam).
