### ISSUE TITLE
Deprecate -r option

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2148]
As many times suggested and discussed, let's deprecate `-r` option alone with introducing the new `download-data` subcommand.

**Comment by xmatthias** [comment]
I'm the biggest supporter for this ;) 

Removing it will allow for a rather big cleanup in backtesting/history.py ...

**Comment by hroff-1902** [comment]
deprecated or removed right after addition of `download-data` subcommand?

**Comment by xmatthias** [comment]
i guess it'll be deprecation (we also have `--live` deprecated)...
