### ISSUE TITLE
 ImportError: cannot import name 'Arguments' from 'freqtrade.configuration' 

### ISSUE THREAD

**Issue by CapitalZe** [freqtrade/freqtrade#2162]
## Step 1: Have you search for this issue before posting it?

Yes, I've searched but not found anything that solves this problem for me.

## Step 2: Describe your environment

  * Operating system: ____Ubuntu
  * Python Version: _____ 3
  * CCXT version: _____ ccxt==1.18.1063
  * Branch: Master | Develop

  
## Step 3: Describe the problem:

Try running hyperopt with

`Python3 ./freqtrade/main.py -c config.json hyperopt`

### Steps to reproduce:

  1. Follow install instructions
  2. Run the above code
  
### Observed Results:

  * What happened?

The following error was thrown back.

`Traceback (most recent call last):
  File "./freqtrade/main.py", line 18, in <module>
    from freqtrade.configuration import Arguments
ImportError: cannot import name 'Arguments' from 'freqtrade.configuration' `

  * What did you expect to happen?

I expected hyperopt to run.

I've been stuck on this hyperopt for quite a while. Everything else in the platform up to this point works, but I just cannot seem to get around this one stage.

Any pointers would be greatly appreciated.

**Comment by xmatthias** [comment]
Please try to run hyperopt using `freqtrade -c config.json hyperopt`.

Running the main.py manually can cause unexpected problems - and the above will point out problems with the installation.
If the above command does not work (or `command freqtrade not found` or similar), please  make sure to install freqtrade using `python3 -m pip install -e .` from within the root folder of freqtrade (the one with the readme.md).

**Comment by CapitalZe** [comment]
This helped.

There was a pickling issue thereafter, but I solved that too. If anyone else gets stuck with that, let me know and I'll provide the solution.

Many thanks!

**Comment by hroff-1902** [comment]
What kind of pickling issue? Let us know...

**Comment by CapitalZe** [comment]
`joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable`

I tried multiple things but eventually traced back to the following three issues:

`ERROR: astroid 2.2.5 requires typed-ast>=1.3.0; implementation_name == "cpython", which is not installed.`

`ERROR: tables 3.5.1 requires mock>=2.0`

`ERROR: alpaca-trade-api 0.30 has requirement urllib3<1.25, but you'll have urllib3 1.25.3 which is incompatible.`

I wasn't able to resolve the astroid issue, but the latter two and the error message ceased to be apparent and I could successful hyperopt with both default and custom methods.

I'm not sure if they're directly related, but there is some tenuous connection as these were the only changes I made in the given environment (as I'm running multiple clones in tandem to faithfully recreate my error messages and reduce variability when trying to debug).

If anyone has further information to enlighten me I'd be very grateful, as for now it has done the trick and I can move forward.

I hope this helps someone else.

**Comment by xmatthias** [comment]
hmm, have you got custom imports in the custom hyperopt file?

**Comment by CapitalZe** [comment]
At the time of bearing the error and solving it, no.

**Comment by hroff-1902** [comment]
astroid is a joomla framework, right? we do not include joomla in the bot...

**Comment by xmatthias** [comment]
none of the above requirements makes sense unless there's a custom import in the file - we don't require / install any of these dependencies i think

**Comment by CapitalZe** [comment]
I also found it strange, as they seemed to be unrelated. 

It confused me why it worked. I have no answers as to why, but it seemed to do the trick. If anyone can shed more light on what was going on I'd be keen to know.

Many thanks!
