### ISSUE TITLE
Suggestion - Implement WCX to trade other assets using XBT (btc)

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#2164]
I know we are far from having freqtrade using leverage, what do you think on implementing an exchange like WCX https://github.com/wcxofficial/api-docs, which allows trading forex pairs, stocks and other markets using BTC and leverage?

**Comment by xmatthias** [comment]
Hi,

we're using [ccxt](https://github.com/ccxt/ccxt) to communicate with exchanges. 
if this exchange is available there, it may work already with freqtrade (you can check this [here](https://github.com/ccxt/ccxt/wiki/Manual#exchanges - i did not find it looking quickly - but maybe it has other names).

If it's not, then please submit a feature request there.

Implementing exchange API's reliably is hard work and requires constant maintenance (we've been there, won't go there again) and is way beyond the scope of this project (that's whay we rely on ccxt).

**Comment by hroff-1902** [comment]
@Dante2333 you may ask ccxt developers for adding support for this exchange...

**Comment by Dante2333** [comment]
ok, will do.

> @Dante2333 you may ask ccxt developers for adding support for this exchange...

**Comment by xmatthias** [comment]
:+1: 
For future reference: 
https://github.com/ccxt/ccxt/issues/5714
https://github.com/ccxt/ccxt/issues/5309
