### ISSUE TITLE
Dynamic stake_amount

### ISSUE THREAD

**Issue by RusEu** [freqtrade/freqtrade#2181]
Hello,

I want to test a strategy which needs to see if the last trade had profit or loss, get the amount of profit or loss and also dynamically change the stake_amount depending on the last trade.
Looking at the source code I didn't found any way to do that.
The edge module seems to do something like this but it does it's own logic, and what I need is different.

Is there any way to set the stake amount on each trade with my logic?

I have programming skills, and I can implement it if you think this is usefull for the comunity, but maybe is something that I'm missing, and this can be done with the current code.

**Comment by hroff-1902** [comment]
No position management in the freqtrade yet.

I have some stashes with movements to it, some design solutions... Slightly moving to it.

That's fine if you have programming skills -- try to study the codebase, fix some issues you think you can resolve, that's the best way to get familiar with the codebase. Then propose you solution for this point.

**Comment by xmatthias** [comment]
Getting the latest trades can be done as shown in that comment (we still miss that in the documentation, and we should simplify that too ...)... https://github.com/freqtrade/freqtrade/issues/1753#issuecomment-483931640

**regarding dynamic stake-amount:**
Technically, you may be able to use `stake_amount=unlimited` [documentation](https://www.freqtrade.io/en/latest/configuration/#understand-stake_amount) - but i suspect that's not exactly what you are after...? 

Thinking about this, it should be "relatively" simple to add a function to the strategy interface which is called and "asks" for "stake_amount" - if `"stake_amount"` is set to "strategy" (for example).


This won't be a quick task though, as it'll touch quite a few files, will require new tests and will also require good documentation so others feel confident to use this feature as well.

Should you decide to look at this please let us know.
We'll definitely support you through this (should you decide to work on it, anyway).

**Comment by hroff-1902** [comment]
Described my current ideas in #2183

**Comment by GrilledChickenThighs** [comment]
I would also like to see a dynamic stake amount for different reasons. IE. 1% of equity

**Comment by hroff-1902** [comment]
Closing it in favor to #2183.
