### ISSUE TITLE
download-data not downloading BCH/BTC and BSV/BTC complete data

### ISSUE THREAD

**Issue by hpdeandrade** [freqtrade/freqtrade#2198]
Hi everyone,

I haven't been able to download ``BCH/BTC`` and ``BSV/BTC`` data. I'm running the command ``freqtrade -c config.json download-data --timeframes 1h``, therefore pairs download follow the whitelist pairs from my config.

However, for these two pairs above, data downloaded is limited and goes only up to April 2019.

I understand from issue #2030 that when I run my strategy, ccxt converts BCH/BTC into BCHABC/BTC. However, if I try to download BCHABC/BTC (to run my backtesting), it says data does not exist.

Would you know which are the correct string to download data of BCH/BTC and BSV/BTC from Binance?

Thank you and best regards,

**Comment by xmatthias** [comment]
`BCH/BTC` works for me - quickly checking with `--days 300` i got data starting in november 2018 ... so i cannot really confirm this.

`BSV/BTC`is not listed on binance (at least i could not find it in their trading portal) - and iirc, it was delisted a few months ago (the API does return it, but as inactive market).
[source](https://cryptopotato.com/breaking-binance-delists-bictoin-cash-sv-bch-abc-surges/)

**Comment by hroff-1902** [comment]
Closing as the question was answered. Feel free to reopen.
