### ISSUE TITLE
Option to recalculate on every tick during live trading

### ISSUE THREAD

**Issue by GrilledChickenThighs** [freqtrade/freqtrade#2202]
Currently, Freqtrade fetches the latest compete candle for calculating values; however, there is always an incomplete candle, specifically hlcv values that are left out of the equation until the candle completes. 

As far as I understand, Freqtrade intentionally leaves this incomplete data out of the equation to avoid repainting issues, and because some exchanges do not provide incomplete data. 

That being said, some strategies can still work using incomplete data and the user should have the option (if available) to recalculate their algo's with the incomplete data.

One proposed solution to this issue would be resampling at a lower timeframe, but it is not ideal (added complexity to strategy, rate limiting).

In an ideal situation, this feature would be similar to tradingview's recalculate on every tick option show below.
![Screen Shot 2019-08-30 at 14 09 42](https://user-images.githubusercontent.com/29057302/64017601-a5aea400-cb32-11e9-807f-46af4cb91c19.png)
![Screen Shot 2019-08-30 at 14 09 58](https://user-images.githubusercontent.com/29057302/64017605-a8a99480-cb32-11e9-9161-c576402fbf4b.png)

**Comment by xmatthias** [comment]
Having an option to disable the removed last candle would not be a huge problem (nor effort) - however we cannot guarantee similar behavior across different exchanges - and it's up to the strategy to figure this out (we cannot test all exchanges for this ...).
This would result in an instable strategy, which may work for binance, but not for bittrex (or viceversa).

ccxt has plans to provide this information per exchange "somehow" (not yet defined i think) ... but I've not seen it implemented yet, so it'll be "kinda random" per exchange.

I can understand the request, and i'm sure specific strategies will benefit from this (however having latest tick-data should be better than OHLCV data?)

I'm however a bit concerned about users using this wrongly (almost no-one seems to read the docs ... ?), and then wondering why their strategy produces odd (repainted) buy-signals, finally resulting at losses, and increase the workload here figuring out why users strategies don't work.

That's the main reason i'm hesitant to add this possibility.

**Comment by hroff-1902** [comment]
@xmatthias Don't you know why all Russians (including myself) want to use incomplete candles? 🙄

**Comment by hroff-1902** [comment]
@xmatthias 

Let's introduce the 'use_incomplete_candle' setting in 'experimental'?
To test handling incomplete data...
For those exchanges that provide the incomplete candle in live ohlcv, otherwise should be taken from the ticker... (Or taken from the ticker for all exchanges?)

(That should have sense only when process_only_new_candles: false, to get new data at every throttling iteration)

**Comment by xmatthias** [comment]
it's an exchange-setting, really ... (especially after you removed everything "experimental" ... )

I don't mind this, but it'll need very good and clear documentation (with multiple warnings - one being that this can cause repainting ...), as not all exchanges provide incomplete candles, which creates a problem.

Also, I wouldn't add it to the default config - but i would leave the default behavior to `ft_has['ohlcv_partial_candle']`, and only allow users to eventually override this.

Another caveat we'll need to "document away":
If i (as a user) set this, i expect incomplete candles (maybe i drop them myself after doing some stuff?)... however, if my exchange does not support this, then I won't get incomplete candles, and there is nothing freqtrade can do against this...

**Comment by xmatthias** [comment]
After looking at this again, this is already possible as an undocumented setting:

```json
{
    "exchange": {
        "_ft_has_params": {"ohlcv_partial_candle": false}
    }
}
```

Setting this to false will prevent dropping of the last (possibly incomplete) candle.
Results (if you really get an incomplete candle) will depend on the exchange.

If this is changed, users need to take care themselfs to eventually drop incomplete candles, and to prevent repainting, which will cause odd results in dry/live trading operations.
