### ISSUE TITLE
Plot-scripts require --datadir

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#2215]
## Describe your environment

  * Python Version: 3.7
  * Branch: Develop
  * Last Commit ID:  962d487edb0d28f95d6395c09189a333c436fd20
  
## Describe the problem:

Currently, `freqtrade plot-dataframe` does require either a valid configuration (`--config` or `config.json` in cwd - or `--datadir user_data/data/bittrex` to find the backtest data.
This is because without one of these, the exchange is not known, which is a requirement to find the data in the datadir.

## Possible fixes

* Error and point out that one of the 2 conditions have to be met
* add `--exchange` parameter as alternative (including the above)

* ... other ideas?

**Comment by hroff-1902** [comment]
My idea was (is) to make behavior of all commands same -- if -c is not specified in cli, then the default config is used. The command will take the exchange name from the config and make anything it needs with it -- in the case it will form the path to the data-dir.

If default config is not loaded for some commands (plot-* in this case) as now, it's not data-dir which is needed. It's actually --exchange. With the same behavior as mentioned above -- the command will use it to make the path to the data. The --data-dir is only needed if it points to another location (can also be specified, but not required).
