### ISSUE TITLE
Easy way to list supported timeframes for exchange(s)

### ISSUE THREAD

**Issue by acrabb** [freqtrade/freqtrade#2216]
* Operating system: macOS 10.14.5
  * Python Version: Python 3.7.2
  * CCXT version: ccxt==1.18.1112
  * Branch: Develop
  * Last Commit ID: 962d48
  
## Step 3: Describe the problem:

Add a way to list available timeframes for exchanges.
Given that strategies are defined for a certain timeframe, it'd be nice to know which exchanges support that timeframe for backtesting and/or running the strategy.

### Steps to reproduce:

  1. Set timeframe to 4h
  2. Try to download data / backtest using bittrex
  3. Notice error: `2019-09-02 15:22:24,289 - freqtrade - ERROR - Invalid ticker 4h, this Exchange supports {'1m': 'oneMin', '5m': 'fiveMin', '30m': 'thirtyMin', '1h': 'hour', '1d': 'day'}`

**Comment by hroff-1902** [comment]
Notice to myself and other devs:

It's not about the particular error, but is an enhancement about new subcommand that would print the timeframes available on exchange.

Thanks for suggestion! 👍

**Comment by hroff-1902** [comment]
@acrabb please check how new `freqtrade list-timeframes` subcommand works...
