### ISSUE TITLE
Unable to sell trade: Could not create limit sell order 

### ISSUE THREAD

**Issue by Claudio-F** [freqtrade/freqtrade#2218]
Suddenly it seems that freqtrade has stopped working:

Unable to sell trade: Could not create limit sell order on market LTC/BTC. Tried to sell amount 0.01 at rate 0.006617. Message: binance {"code": -1013, "msg": "Filter failure: MIN_NOTIONAL"}

Why?! Help me pls

**Comment by xmatthias** [comment]
Please fill out the Issue form (detailing the versions). Otherwise it's difficult to support you.

Also, we'll need more logs (ideally starting with the buy-point of this trade).

**Comment by hroff-1902** [comment]
Closing the issue since no additional info that would allow to identify and localize the problem was provided.

Feel free to reopen this.
