### ISSUE TITLE
Kraken: EUR zero balance, BTC unknown format 

### ISSUE THREAD

**Issue by sgarcia159** [freqtrade/freqtrade#2225]
## Step 1: Have you search for this issue before posting it?
Yes, I am done my research. I found what I believe was a similar issue that was resolved but has not resurfaced --> #1840  

## Step 2: Describe your environment

  * Operating system: Ubuntu 19.04
  * Python Version: Python 3.7.3 
  * CCXT version: ccxt==1.18.1085 
  * Branch: Master
  * Last Commit ID: a7e45c5a732c60e2815bfd7bd3f2cb4cb24faf56 

 
  
## Step 3: Describe the problem:
I am wanting to use Kraken as my exchange. when using BTC I receive the below error:

 **File "/home/sgarc90/freqtrade/freqtrade/rpc/telegram.py", line 52, in wrapper
    return command_handler(self, *args, **kwargs)
  File "/home/sgarc90/freqtrade/freqtrade/rpc/telegram.py", line 336, in _balance
    "\t`Est. BTC: {est_btc: .8f}`\n".format(**currency)**
--------------------------
When I change to EUR. a zero balance is returned.

WARNING - Unable to create trade: Available balance(0 EUR) is lower than stake amount(19 EUR)
*Explain the problem you have encountered*

### Steps to reproduce:
once you start up freqtrade using Kraken. from within telegram send the balance button and watch the screen is a short time the telegram request will error out.

I just happened to see the EUR error appear on the screen when freqtrade tried to place an order

**Comment by xmatthias** [comment]
The problem here is the return from ccxt - which does only contain "total" - but not "available", nor "free" per pair.

i know this worked before since I tested kraken in the past. 

Maybe it's simply a bug in ccxt, or  the exchange did change how / what they return.

In the latter case, this will land kraken on the blocked list, since freqtrade cannot operate if it does not know how much free balance is available.

**Comment by xmatthias** [comment]
according to the answer from ccxt, the API does not return free balance - so they can't either (which is understandable).

However, without knowing free balance, we cannot trade kraken - so i've added Kraken to the list of disabled exchanges for now (until we have a workaround for this ...).

**Comment by hroff-1902** [comment]
Yeah, I've seen that issue in ccxt repo...

**Comment by sgarcia159** [comment]
Thank you, all, for running this down so quickly.  Unless there are objections, I am going to consider this matter closed and close this thread.

**Comment by sgarcia159** [comment]
Thank you, all, for running this down so quickly.  Unless there are objections, I am going to consider this matter closed and close this thread.
