### ISSUE TITLE
Redesign experimental settings

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2233]
The suggestion is:

* move experimental settings out of experimental to the root:
```
    "experimental": {
        "use_sell_signal": false,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
```
They are implemented for more than an year and should no longer be considered as experimental. The code for experimental branch of settings should be kept in the codebase since we could add some new settings to it in the future.

* assign the `use_sell_signal` the default value of true.

**Comment by xmatthias** [comment]
yes and yes - we could (probably should) also have a grace-period - where these settings are "copied" to the root-level with a depreciation warning ... 

so people can slowly adapt to this.

**Comment by hroff-1902** [comment]
the latter one (the default value of true for `use_sell_signal`) does not require adding deprecation messages.
