### ISSUE TITLE
ModuleNotFoundError: No module named '_bz2'

### ISSUE THREAD

**Issue by acemi1** [freqtrade/freqtrade#2245]
* Operating system: ____Ubuntu 16.04.6 LTS
  * Python Version: _____ Python 3.7.3
  
## Step 3: Describe the problem:

 freqtrade -c config.json
 or
 python3.7 ./freqtrade/main.py -c config.json
error message is below
...
import bz2
  File "/usr/local/lib/python3.7/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

when I check; The file "bz2.py" is located in the "/usr/local/lib/python3.7/" folder.

### Steps to reproduce:

sudo apt-get install libbz2-dev
message is below

Reading package lists... Done
Building dependency tree
Reading state information... Done
libbz2-dev is already the newest version (1.0.6-8ubuntu0.2).
The following packages were automatically installed and are no longer required:
  linux-gcp-headers-4.15.0-1033 linux-gcp-headers-4.15.0-1034 linux-gcp-headers-4.15.0-1036 linux-gcp-headers-4.15.0-1037
  linux-headers-4.15.0-1033-gcp linux-headers-4.15.0-1034-gcp linux-headers-4.15.0-1036-gcp linux-headers-4.15.0-1037-gcp
  linux-image-4.15.0-1033-gcp linux-image-4.15.0-1034-gcp linux-image-4.15.0-1036-gcp linux-image-4.15.0-1037-gcp linux-modules-4.15.0-1033-gcp
  linux-modules-4.15.0-1034-gcp linux-modules-4.15.0-1036-gcp linux-modules-4.15.0-1037-gcp
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 67 not upgraded.

  * CCXT version: _____ (`pip freeze | grep ccxt`)
aiodns==1.1.1
aiohttp==3.6.0
arrow==0.14.6
asn1crypto==0.24.0
async-timeout==3.0.1
atomicwrites==1.3.0
attrs==19.1.0
cachetools==3.1.1
ccxt==1.18.1115
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
Click==7.0
coinmarketcap==5.0.3
colorama==0.4.1
coverage==4.5.4
coveralls==1.8.2
cryptography==2.7
docopt==0.6.2
entrypoints==0.3
filelock==3.0.12
flake8==3.7.8
flake8-tidy-imports==2.0.0
flake8-type-annotations==0.1.0
Flask==1.1.1
-e git://github.com/freqtrade/freqtrade.git@3d028f512e23fa7d365223666d5faa79442f9964#egg=freqtrade
future==0.17.1
idna==2.8
importlib-metadata==0.20
itsdangerous==1.1.0
Jinja2==2.10.1
joblib==0.13.2
jsonschema==3.0.2
MarkupSafe==1.1.1
mccabe==0.6.1
more-itertools==7.2.0
multidict==4.5.2
mypy==0.720
mypy-extensions==0.4.1
numpy==1.17.1
packaging==19.1
pandas==0.25.1
plotly==4.1.0
pluggy==0.12.0
py==1.8.0
py-find-1st==1.1.4
pycares==3.0.0
pycodestyle==2.5.0
pycparser==2.19
pyflakes==2.1.1
pyparsing==2.4.2
pyrsistent==0.15.4
pytest==5.1.2
pytest-asyncio==0.10.0
pytest-cov==2.7.1
pytest-mock==1.10.4
pytest-random-order==1.0.4
python-dateutil==2.8.0
python-rapidjson==0.8.0
python-telegram-bot==12.0.0
pytz==2019.2
requests==2.22.0
requests-cache==0.5.2
retrying==1.3.3
scikit-learn==0.21.3
scikit-optimize==0.5.2
scipy==1.3.1
sdnotify==0.3.2
six==1.12.0
SQLAlchemy==1.3.8
TA-Lib==0.4.17
tabulate==0.8.3
tornado==6.0.3
typed-ast==1.4.0
typing-extensions==3.7.4
urllib3==1.25.3
wcwidth==0.1.7
Werkzeug==0.15.6
wrapt==1.11.2
yarl==1.1.0
zipp==0.6.0

ccxt==1.18.1115

**Comment by hroff-1902** [comment]
It's a python problem, you are running 'new' python 3.7 on 'old' Ubuntu 16.04

> The file "bz2.py" is located in the "/usr/local/lib/python3.7/" folder.
But '_bz2' is not.

seems the solutions may require recompilation of python, so you should probably better move to a newer Ubuntu...
See https://stackoverflow.com/questions/12806122/missing-python-bz2-module for example.

**Comment by hroff-1902** [comment]
@xmatthias 
it may also be a requirement of skit-learn as well (see https://github.com/scikit-learn/scikit-learn/issues/7526)

If so, would splitting hyperopt dependencies in setup.py help to run main trading part on this platform, in this environment?

**Comment by acemi1** [comment]
> @ xmatthias
> aynı zamanda skit- learn'ın bir gerekliliği de olabilir (bakınız [scikit-learn / scikit-learn # 7526](https://github.com/scikit-learn/scikit-learn/issues/7526) )
> 
> Öyleyse, hipermetrop bağımlılıklarını setup.py dosyasına bölmek, bu ortamda ana ticaret bölümünü bu ortamda çalıştırmaya yardımcı olur mu?

**Comment by acemi1** [comment]
Thank you for your quick response.
I don't know what you're saying. I'm a beginner.

**Comment by acemi1** [comment]
> It's a python problem, you are running 'new' python 3.7 on 'old' Ubuntu 16.04
> 
> > The file "bz2.py" is located in the "/usr/local/lib/python3.7/" folder.
> 
> But '_bz2' is not.
> 
> seems the solutions may require recompilation of python, so you should probably better move to a newer Ubuntu...
> See https://stackoverflow.com/questions/12806122/missing-python-bz2-module for example.

I use google cloud.
I can choose the linux version I want.
For other users who use Ubuntu 16.04.6 LTS, does installing python 3.6 solve the problem?

**Comment by hroff-1902** [comment]
> > It's a python problem, you are running 'new' python 3.7 on 'old' Ubuntu 16.04
> > > The file "bz2.py" is located in the "/usr/local/lib/python3.7/" folder.
> > 
> > 
> > But '_bz2' is not.
> > seems the solutions may require recompilation of python, so you should probably better move to a newer Ubuntu...
> > See https://stackoverflow.com/questions/12806122/missing-python-bz2-module for example.
> 
> I use google cloud.
> I can choose the linux version I want.
> For other users who use Ubuntu 16.04.6 LTS, does installing python 3.6 solve the problem?

Probably. We cannot test all the platforms. Just try and let us know here.

**Comment by xmatthias** [comment]
> it may also be a requirement of skit-learn as well (see scikit-learn/scikit-learn#7526)

last time i checked, it was a pandas problem [source](https://github.com/pandas-dev/pandas/issues/27575)   (at least for me - but pandas installs prior to scikit-learn) ... - but it will affect other libraries as well for sure.

I would suggest to use a newer image (Ubuntu 18.04 LTS for example) - this should have python (3.6?) preinstalled so no need to install python.

**Comment by raftersvk** [comment]
ok it has to do with the difference between the python version :
- local install : python 3.8
- pip install : 3.9

i'll try to sort this out ;)

**Comment by sammcj** [comment]
Did you ever find a solution to this for older linux distros by chance @raftersvk ?
