### ISSUE TITLE
handling of trailing stop losses by edge positioning

### ISSUE THREAD

**Issue by orehunt** [freqtrade/freqtrade#2262]
If I got it right, a trailing stop loss is supposed to be at best a win lower than the first minimal_roi step or at worst a neutral (although it can be a negative if `offset - stoploss < 2 * trading_fees`. 
So edge, which currently unconditionally considers them as losses, should either treat them as positives or ignore them within the calculation.

**Comment by xmatthias** [comment]
I think the answer to this depends ... 

Edge does it's own implementation of generating buy/sell signals.

as stated in the documentation:

> Edge does not consider anything else than buy/sell/stoploss signals. So trailing stoploss, ROI, and everything else are ignored in its calculation.

[source](https://www.freqtrade.io/en/latest/edge/) [github](https://github.com/freqtrade/freqtrade/blob/develop/docs/edge.md)

Based on the above, trailing stoploss is not evaluated at all to calculate expectancy, acting as if it's disabled.


Now once you put a strategy with edge to dry-run with trailing stoploss on, trailing stops will work, however it will not be considered for the calculations done by edge (expectancy / active pairs / stoploss value).

This may create an odd disconnect between trades that happened and edge (same with ROI sells ...), leading to pairs either beeing considered better or worse for future calculations, but this has been something that has been explicitly opted for by the author(s).

@mishaker as author of edge, maybe you want to explain the reasons for this decision as i'm sure you know them better than i do?

**Comment by mishaker** [comment]
Above explanation by @xmatthias is correct. 
In its calculation, Edge doesn't consider anything other than stoploss/sell/buy signals. But it doesn't mean you cannot activate TSL and other features when trading live or dry-run. 

I am closing this issue as I think it is clear now. but feel free to re-open if you think differently.

**Comment by orehunt** [comment]
mmh it could be that an "aggressive" strategy which relies too much on TSL is an anti-pattern, and edge is right to ignore them. I thought it kept count of past trades, but it is more akin to live backtesting
