### ISSUE TITLE
minimal_roi and stoploss in the hyperopt class

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2263]
It's impossible to define minimal_roi and/or stoploss in the custom hyperopt class.

Usecase:
* A user created a new custom hyperopt class for a new strategy. She implemented `buy_strategy_generator()` and `sell_strategy_generator()` methods, defined spaces for hyperopting.
* She made hyperopting for the 'all' space.
* She created `populate_buy()` and `populate_space()` using the triggers and guards from the hyperopting best result.
* Then she decided to optimize minimal_roi and stoploss, so she runs hyperopting for the 'roi stoploss' spaces. This is also okay, hyperopting will print best results for both minimal_roi and stoploss.
* Now she decides to optimize stoploss more precisely, fixing the minimal_roi found in the previous step, by running hyperopt for the 'stoploss' space only. And it's impossible to do, since hyperopting does not fetch minimal_roi from the custom hyperopt class. The minimal_roi will be fetched from the default strategy, which does not have any sense for custom hyperopt and will produce completely different results while hyperopting for the 'stoploss' space.
* Same if she wants to fix 'stoploss' value found and hyperopt for minimal_roi.

**Comment by xmatthias** [comment]
i'll be honest, i think that a solution to this may conflict with #2231 ...

Assuming i also forget to remove this from my custom hyperopt after correcting it in my strategy and run hyperopt with `--strategy MyAwesomeLosingStrategy` - which one should take prevelance - the content of the Strategy (`--strategy`) or the content of the custom hyperopt (`--customhyperopt`) file?

The documentation around htis is not clear - but i'm afraid that a technical solution may result in confusing behaviour....

**Comment by hroff-1902** [comment]
year, all this should be clarified, (and should be clear enough to avoid confusions)
but I described the case when the user starts with the custom hyperopt class and she does not have any strategy yet. Fetching minimal_roi silently is simply wrong...

Btw, do you know that if you did not implement populate_buy/sell_trend() in the HyperOpt, the resolver loads it from DefaultStrategy (with a warning in the log)... Just found this behavior...

**Comment by xmatthias** [comment]
well i implemented it ... so yes ... 
it's not ideal - but was required to allow optimizing only one side without loading a custom strategy.
Honestly, you'll still need to get this method from "somewhere" ... 

note: it's [documented](https://www.freqtrade.io/en/latest/hyperopt/#checklist-on-all-tasks-possibilities-in-hyperopt)

> Optional, but recommended:
>
> copy populate_buy_trend from your strategy - otherwise default-strategy will be used
> copy populate_sell_trend from your strategy - otherwise default-strategy will be used

**Comment by hroff-1902** [comment]
and if it falls back to the populate_buy/sell_trend from the DefaultStrategy, it will use populate_indicators from the DefaultHyperopt or a custom hyperopt and will then fail with very strange and unexpected messages about 'sar' not found in the dataframe, for example... So, a user implemented a custom hyperopt, with the buy/sell generator functions (no populate_buy/sell_trend), so she runs successfully hyperopt for 'all' space, then she decides to, yes, optimize only one side, or optimizer only for 'roi stoploss' and instead of a clean message stating 'please implement populate_buy/sell_trend in the hyperopt class or specify you custom strategy which implements these methods and is aligned to your hyperopt', she obtains strange messages about indicators that are not found...

This even fails for DefaultHyperOpts -- the DefaultStrategy uses different set of indicators and populate_buy/sell_trend from the DefaultStrategy (the fallbacks) fail for populate_indicators from DefaultHyperOpts... 

Let's align them, I mean DefaultStrategy and DefaultHyperOpts?

**Comment by xmatthias** [comment]
sure thing (side note: it was me who broke this when removing all indicators from the DefaultStrategy this week).

one historic note: Hyperopt used to be seen as the "adanced" method - for people familliar with what they're doing. It's mainly your work to make it accessible to more people and improve it's interface. 

On the other hand, should we load DefaultStrategy at all during a user's hyperopt, now, since loading custom strategies is technically possible?

**Comment by xmatthias** [comment]
@hroff-1902 question

does this issue still apply? 
we don't default to `DefaultStrategy` anymore / allow custom strategies - so by using a custom strategy, you can specify `minimal_roi` there instead of the custom_hyperopt file (as in your example above, minimal_ROI is already ok - so you moved it ot the "final" file).

**Comment by hroff-1902** [comment]
Yes, it's no longer applicable since those values can be 'frozen' in the custom strategy used along with the hyperopt class.

I've some enhancement ideas for the future, when this can also be required to be set in the hyperopt class itself, but I'm not sure about this in the meantime. So I'm closing this issue now and will reopen it in the future if this will have sense.
