### ISSUE TITLE
How do I know your change from the previous candle?

### ISSUE THREAD

**Issue by acemi1** [freqtrade/freqtrade#2279]
How do I understand how an indicator changes from a previous candle?
For example:
Last candle indicator value> previous candle indicator value = BUY
Last candle indicator value> previous candle indicator value = Wait
Last candle indicator value> previous candle indicator value = Wait
...
Last candle indicator value <previous candle indicator value = SELL
Last candle indicator value <previous candle indicator value = Wait
Last candle indicator value <previous candle indicator value = Wait
...

Usage of tradingview: indicator> indicator [1]

**Comment by xmatthias** [comment]
I'm not sure about the trading view (i don't know pinescript) ...

but you should be able to use `dataframe['indicator'].shift(1) < dataframe['indicator']`.

this is equal to `indicator previous candle < indocator this candle`.

Please do not use negative shift values, as this will create lookahead bias and may look good in backtesting, but will not work in live trading at all.

**Comment by acemi1** [comment]
I will try. Thank you for replying.
