### ISSUE TITLE
Ability to /forcesell stop

### ISSUE THREAD

**Issue by seansan** [freqtrade/freqtrade#228]
Currently it is almost impossible to stop the bot

/forcesell all
/stop

is difficult because it starts buying parallel to the selling (or so quickly so fast after the forcesell all)

Therefore it would be good if 
- during /forcesell all that buying is actually disabled (so from sell1 tot sell-last no buys are started)
- and maybe we should introduce /forcesell stop where it executes /forcesell all followed by an immediate stop (so no buy is made)

**Comment by bbspike** [comment]
I think its better to enable the /forcesell options while a bot is stopped. So let the bot react on the /forcesell   when its status is stopped. Then you can first stop the bot ad then forcesell. Then you can start back whenever you want.

**Comment by seansan** [comment]
​I agree this is a smarter option

(on the other hand forcesell stop could do just that, in that order)

main goal is: the ability to pull out all​

**Comment by shusso** [comment]
please feel to re-open if still needed
