### ISSUE TITLE
No DefaultStrategy and DefaultHyperopt

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2281]
It's good time to make this change in terms of #2264 / quickly at the same time since it changes user cli interface:

* No DefaultStrategy. If a user wants to load a use some sample strategy, she needs to specify it explicitely: `-s SampleStrategy`.

Technically, if hyperopt needs a strategy class as a placeholder for methods for backtesting, it should create an instance of IHyperopt in this case. This should probably be the behavior of resolver.

* No DefaultHyperopt -- specify SampleHyperopt explicitely.

Same probably for other resolvables.

**Comment by xmatthias** [comment]
is a simple "yes" enough discussion? :laughing: 

I completely agree - but i'm not sure if i should include it into #2264, or if we should do these seperately.

I'm think we can change `--strategy` in #2264 without much fuss - but loading the Hyperopt change should probably be done seperately (honestly, because i would want to leave that to you ...)

**Comment by hroff-1902** [comment]
Not probably included into #2264, but merged together when implemented...

**Comment by hroff-1902** [comment]
What about DefaultLoss (legacy) and Default pairlist (static)?

**Comment by xmatthias** [comment]
i would leave these to be honest - 
Having sensible defaults does make sense in some areas (defaultloss / pairlist) - but not in others which we assume users have to change to be profitable (strategy, hyperopt).


side note: to merge them together, we can do Pull requests against the branch `args_aftersubcommand2` (based on that branch too, obviously)... this way we can review the changes we're doing seperately, without the "huge" change...

**Comment by hroff-1902** [comment]
Right, or we could create a separate feature branch, create and merge prs against it (including args_aftersubcommand2) and finally merge it into develop...

**Comment by xmatthias** [comment]
args_aftersubcommand2 is technically a feature branch ... ;)

**Comment by hroff-1902** [comment]
Not completely -- the changes are already there (say, merged), but okay, let's use it for this purpose.

**Comment by xmatthias** [comment]
ah now i understood - ok can do that :+1:

**Comment by xmatthias** [comment]
Going to close this, since its merged into #2397 - and will be merged to develop soonish.
