### ISSUE TITLE
Wrong hyperopt calculations

### ISSUE THREAD

**Issue by sanitariu** [freqtrade/freqtrade#2283]
Hello,
I am running hyperopt on bittrex with the following:

freqtrade -c config.json hyperopt -e 100 --spaces all

These are the results:
*    1/100:      8 trades. Avg profit -2.06%. Total profit -0.00827267 BTC ( -16.50Σ%). Avg duration 878.8 mins. Objective: 2.31156
.....
*    7/100:     27 trades. Avg profit  0.02%. Total profit  0.00027148 BTC (   0.54Σ%). Avg duration 2192.6 mins. Objective: 2.24962
...
*   11/100:     58 trades. Avg profit -0.02%. Total profit -0.00071510 BTC (  -1.43Σ%). Avg duration 1621.8 mins. Objective: 2.24781
.................................
    45/100:      1 trades. Avg profit  0.00%. Total profit  0.00000000 BTC (   0.00Σ%). Avg duration 180.0 mins. Objective: 2.09843
............
    58/100:     39 trades. Avg profit -0.55%. Total profit -0.01077780 BTC ( -21.50Σ%). Avg duration  79.9 mins. Objective: 2.02635
.....
    64/100:      7 trades. Avg profit  0.02%. Total profit  0.00006760 BTC (   0.13Σ%). Avg duration  85.0 mins. Objective: 1.96970
.
    66/100:      1 trades. Avg profit -0.26%. Total profit -0.00012806 BTC (  -0.26Σ%). Avg duration   5.0 mins. Objective: 1.86595
..............................2019-09-21 12:27:41,421 - freqtrade.optimize.hyperopt - INFO - Saving 96 evaluations to '/home/dri/miner/freqtrade/user_data/hyperopt_results/hyperopt_results.pickle'

Best result:

    66/100:      1 trades. Avg profit -0.26%. Total profit -0.00012806 BTC (  -0.26Σ%). Avg duration   5.0 mins. Objective: 1.86595

Buy hyperspace params:
{   'adx-enabled': True,
    'adx-value': 45,
    'fastd-enabled': True,
    'fastd-value': 18,
    'mfi-enabled': False,
    'mfi-value': 12,
    'rsi-enabled': True,
    'rsi-value': 28,
    'trigger': 'sar_reversal'}
Sell hyperspace params:
{   'sell-adx-enabled': True,
    'sell-adx-value': 70,
    'sell-fastd-enabled': False,
    'sell-fastd-value': 97,
    'sell-mfi-enabled': False,
    'sell-mfi-value': 94,
    'sell-rsi-enabled': False,
    'sell-rsi-value': 65,
    'sell-trigger': 'sell-sar_reversal'}
ROI table:
{0: 0.15743, 19: 0.03912, 47: 0.0178, 114: 0}
Stoploss: -0.4717

Why it says that best result is number 66 (which is negative) if we have positive results like number 7 and 64 ?

**Comment by xmatthias** [comment]
I think you should explore different loss functions.

The default is not ideal in most cases, giving (in my opinion) WAY too much weight to the trade duration.

As specified in the [documentation](https://www.freqtrade.io/en/latest/hyperopt/#loss-functions), please try out the other 2 loss functions `OnlyProfitHyperOptLoss` (which ONLY looks at profit, nothing else) and `SharpeHyperOptLoss`.

**Comment by hroff-1902** [comment]
we should better make OnlyProfitHyperopt to be default one...

**Comment by sanitariu** [comment]
OnlyProfitHyperopt is perfect solution

**Comment by sanitariu** [comment]
Is there anyway i can see the full results from number 7 and number 64 ?

**Comment by xmatthias** [comment]
from the documentation [here](https://www.freqtrade.io/en/latest/bot-usage/#hyperopt-commands)

```
  --print-all           Print all results, not only the best ones.
```

**Comment by hroff-1902** [comment]
> Is there anyway i can see the full results from number 7 and number 64 ?

Do you mean previous results. that were kept in the hyperopt_results pickle file?

If so, I'm going to create a couple of hyperopt utility subcommands that would help exploring hyperopt results, let's discuss the possible interface here, since you are also interested in this:

* `hyperopt-results --list` -- prints same strings with dots and best results, from hyperopt_results pickle file. `hyperopt-results --list --print-all` prints all results, in the format `hyperopt --print-all` uses.
* `hyperopt-results -n N` -- prints the detailization for hyperopt result N from the hyperopt_results pickle file.
* something else?

**Comment by hroff-1902** [comment]
Closing it as the question was answered.
Feel free to reopen.
