### ISSUE TITLE
Support multiple exchanges

### ISSUE THREAD

**Issue by shusso** [freqtrade/freqtrade#230]
Base branch: https://github.com/gcarq/freqtrade/tree/feat/objectify-ccxt
  
The priority and task list for ccxt work. 
- [x] make dry_run work
- [x] make tests pass
- [x] make trading work
- [x] make tests pass
- [x] make backtesting work
  - [x] conversion script that converts the old-data format to new ccxt dataformat
  - [ ] ~~..or overwrite `parse_ticker_dataframe` in backtesting to support the old format for timebeing~~
- [x] make hyperopt work

Known [issues](https://github.com/gcarq/freqtrade/labels/ccxt)

*Note* small PR's will make everybody's life easier and is much easier and faster to review & merge 👍

**Comment by fashaikh** [comment]
Excited to see this come out and take advantage of lower trading fees on other exchanges.
Please let me know if I can help

**Comment by davidalbertonogueira** [comment]
Any plans for Kraken support?

**Comment by josemariabooymts** [comment]
Cut it

**Comment by shusso** [comment]
@davidalbertonogueira in the future yes, most likely. There is still few stability issues we are planning to fix

**Comment by linhndd** [comment]
Hi,

I waiting for new update support for binance, because that's big exchanger platform. And I usage it for main trade. Thank you

**Comment by elRadix** [comment]
Please add Binance support, see below multiple ways to integrate with their API.

https://support.binance.com/hc/en-us/articles/115002604631-Winners-of-Binance-API-Competition

**Comment by abeburnett** [comment]
+1 for Binance support

**Comment by eliashassing** [comment]
Hi guys, any idea when this enhancement will be available?

**Comment by shusso** [comment]
I'm currently working on adding CCXT support. There is a PR ongoing for adding just binance at #489

**Comment by ElanHasson** [comment]
@shusso Do you have a timeline for CCXT?

**Comment by gcarq** [comment]
ccxt got merged into develop #652. There are still some rough edges but it should be somewhat stable for now.
Implemented and tested exchanges: bittrex and binance

**Comment by xmatthias** [comment]
@gcarq  Any reason you repoened this?

**Comment by gcarq** [comment]
@xmatthias I closed it by accident and reopened it one second later, but you're right. We can close this one.
