### ISSUE TITLE
hourly high and low

### ISSUE THREAD

**Issue by moeen25** [freqtrade/freqtrade#2304]
## Step 1: Have you search for this issue before posting it?
yes about 2 days
If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: ____Windows 10 64x
  * Python Version: _____ (`python -V`) Python 3.7.4
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*
sorry if this newbie questions but i use 1m interval but i want to get 1hr high/low price,i dont want to change my interval to 1hr,so  to get 1hr low i run like this: dataframe['low'].shift(1).......dataframe['low'].shift(60),what should i do  to get 1hr low and hight price?

**Comment by xmatthias** [comment]
If this is the only information you need, you can use something like `dataframe['low'].rolling(60).max()` and `dataframe['low'].rolling(60).min()`, which will give you a rolling 1h window.

Alternatively, you can use resample to resample the candles to hourly candles (these are REAL 1h candles, not rolling candles) - and take the min/max from there.

[this](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/MultiRSI.py) strategy has a sample about this - and you will want [this library](https://github.com/freqtrade/technical/) for resample and merge (or code it yourself ...).

**Comment by moeen25** [comment]
> 
> 
> If this is the only information you need, you can use something like `dataframe['low'].rolling(60).max()` and `dataframe['low'].rolling(60).min()`, which will give you a rolling 1h window.
> 
> Alternatively, you can use resample to resample the candles to hourly candles (these are REAL 1h candles, not rolling candles) - and take the min/max from there.
> 
> [this](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/MultiRSI.py) strategy has a sample about this - and you will want [this library](https://github.com/freqtrade/technical/) for resample and merge (or code it yourself ...).

thanks xmatthias for ur answer,I'm just sad why I didn't ask the question earlier

**Comment by hroff-1902** [comment]
@moeen25 you can also ask questions at our Slack channel instead of opening an issue here for each question.
