### ISSUE TITLE
cant join freqtrade slackchanel

### ISSUE THREAD

**Issue by mj1300** [freqtrade/freqtrade#2309]
## Step 1: Have you search for this issue before posting it?
yes
## Step 2: Describe your environment

  * Operating system: ____ windows 10 x64
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

i try to join slack chanel but it said "This invite link is no longer active."
i tried this link:
https://join.slack.com/t/highfrequencybot/shared_invite/enQtNjU5ODcwNjI1MDU3LWEyODBiNzkzNzcyNzU0MWYyYzE5NjIyOTQxMzBmMGUxOTIzM2YyN2Y4NWY1YTEwZDgwYTRmMzE2NmM5ZmY2MTg

**Comment by xmatthias** [comment]
I'll have a look tonight .... not sure why this expired again already ...

**Comment by mj1300** [comment]
> 
> 
> I'll have a look tonight .... not sure why this expired again already ...

thanks i will wait till night

**Comment by xmatthias** [comment]
please use https://join.slack.com/t/highfrequencybot/shared_invite/enQtNjU5ODcwNjI1MDU3LTU1MTgxMjkzNmYxNWE1MDEzYzQ3YmU4N2MwZjUyNjJjODRkMDVkNjg4YTAyZGYzYzlhOTZiMTE4ZjQ4YzM0OGE

will update the documentation accordingly (after finding out why the other expired, when it says (in bold!) "this link does not expire" ...
