### ISSUE TITLE
Use the term 'timeframe' instead of non-standard 'ticker interval'

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2318]
This issue proposes the use of the term 'timeframe' instead of 'ticker interval' everywhere in the docs, settings and cli options.

'Timeframe' is the "standard" term, used everywhere in the trading literature. Ccxt also uses this term.

The existing '--ticker-interval' option should get the `--timeframe` alias and be declared as deprecated (and then removed in the next versions).

Can be (should be) a part of #2264, so that all these changes into the cli were implemented in the upcoming release at once.

**Comment by xmatthias** [comment]
> Can be (should be) a part of #2264, so that all these changes into the cli were implemented in the upcoming release at once.

i'm not sure about this ... maybe gradually changing options has advantages too (there's no 100 options that are different, but a few every update ...), so i'm not certain about that part yet.

Rest is fine - i've been anoyed by the terminology in the past, too :D

**Comment by xmatthias** [comment]
🥳 🎉 
(that's all i can say to this ...).
