### ISSUE TITLE
ModuleNotFoundErrror / Please Help

### ISSUE THREAD

**Issue by MrN8** [freqtrade/freqtrade#2336]
// paste your log here
  ```
hi sorry the bot gives me an error
Error : Traceback (most recent call last):
File "./freqtrade/main.py", line 11, in
from freqtrade import OperationalException
ModuleNotFoundError: No module named 'freqtrade'

**Comment by hroff-1902** [comment]
Hi, are you from Udemy course?

**Comment by hroff-1902** [comment]
The Udemy course is outdated, it's based on a very old version of the bot. The approaches to install, to run and to control the bot has changed.

* Update the bot to the latest master or to the latest develop as specified in the documentation: https://www.freqtrade.io/en/latest/installation/
* Run the bot as specified in the documentation: https://www.freqtrade.io/en/latest/bot-usage/
* Read the FAQ: https://www.freqtrade.io/en/latest/faq/
* Read the rest of the actual documentation: https://www.freqtrade.io/en/latest/

**Comment by MrN8** [comment]
So I should not use the course at all? Is it totally outdated ?

**Comment by hroff-1902** [comment]
The course is a set of educational lessons that provide you with knowledge, why should not you use the knowledge you obtained?

As for their assets, it's outdated and was updated since then in many parts, many errors were fixed as well.

**Comment by MrN8** [comment]
Thanks a lot for helping!

**Comment by xmatthias** [comment]
the authors intentionally base the course on their version of freqtrade, which is a snapshot.
This is understandable and has the advantage to not have to upgrade the course with each change we make, however once you then use the uptodate version things may have changed, so it does not replace reading the documentation.

**Comment by hroff-1902** [comment]
Closing it as the question was answered.
Feel free to reopen it.
