### ISSUE TITLE
unrecognized arguments: --datadir

### ISSUE THREAD

**Issue by carmelo42** [freqtrade/freqtrade#2338]
* Operating system: ubuntu
  * Python Version: 3.6.8
  * CCXT version: ccxt==1.18.1159
  * Branch: Master | Develop
  * Last Commit ID: 7fff1f5ce125db14a6f467b09253671f441720e9
  
Hello,

I have downloaded backtesting data, and put the data in backtesting_data directory.
But when I want to use it, I obtain this error : 

(.env) root@common-bionic-freqtrade-01:~/freqtrade# freqtrade -c config.json backtesting --datadir backtesting_data/ --strategy-list ADXMomentum ClucMay72018 MACDStrategy_crossed Simple AdxSmas CMCWinner MACDStrategy ASDTSRockwellTrading
CofiBitStrategy SmoothScalp AverageStrategy CombinedBinHAndCluc DoesNothingStrategy Quickie BbandRsi EMASkipPump ReinforcedQuickie ReinforcedSmoothScalp CCIStrategy Low_BB Scalp --ticker-interval=5m --timerange=20181010- --export-filename
=backtesting.json
usage: freqtrade [-h] [-v] [--logfile FILE] [-V] [-c PATH] [-d PATH]
                 [--userdir PATH] [-s NAME] [--strategy-path PATH]
                 [--db-url PATH] [--sd-notify]
                 {backtesting,edge,hyperopt,create-userdir,list-exchanges,download-data,plot-dataframe,plot-profit}
                 ...
freqtrade: error: unrecognized arguments: --datadir backtesting_data/

I have found the argument "--datadir backtesting_data/" in the freqtrade doc : 

https://www.freqtrade.io/en/latest/backtesting/
"freqtrade backtesting --datadir user_data/data/bittrex-20180101"

**Comment by xmatthias** [comment]
seems to be a typo in the docs - datadir needs to be before backtesting at the moment (but this willl be changed in the future).

try `freqtrade --datadir user_data/data/bittrex-20180101 backtesting`

**Comment by carmelo42** [comment]
perfect :) thanks for your quick action :)

**Comment by hroff-1902** [comment]
> perfect :) thanks for your quick action :)

Did not you forget to 'star' our repo? 😉 
(a Star button at the top)

**Comment by carmelo42** [comment]
this big mistake is now past ;)
