### ISSUE TITLE
Hyperopt trailing stoploss hyperoptimization space

### ISSUE THREAD

**Issue by Theagainmen** [freqtrade/freqtrade#2363]
## My environment

* Operating system: Windows
* Python Version: Python 3.7.4
* Branch: freqtrade develop-7d1f66cc

### The suggestion
In hyperopt I currently can't find an easy way to hyperopt values like `trailing_stop_positive` or `trailing_stop_positive_offset`. Maybe make a way that you can easily add them like the `stoploss` value.

**Comment by hroff-1902** [comment]
this is probably not easy to implement...

**Comment by xmatthias** [comment]
at first look it looks rather straightforward...

it's another space - almost identical to stoploss...
could probably also be implemented into the stoploss_space() - which will make it a 8 line change (excluding tests and such).

``` python
    def stoploss_space() -> List[Dimension]:

        return [
            Real(-0.35, -0.02, name='stoploss'),
            Real(-0.35, -0.02, name='trailing_stoploss_positive'),
            Categorical([True, False], name='tsl_enabled'),
            Real(0, 0.1, name='trailing_stoploss_positive_offset'),  # (?)
            Categorical([True, False], name='tsl_positive_enabled'),
        ]
```

and in hyperopt.py:
``` python
        if self.has_space('stoploss'):
            self.backtesting.strategy.stoploss = params['stoploss']
            self.backtesting.strategy.trailing_stoploss_positive = params['trailing_stoploss_positive']
           ...

```

Now i didn't test this and it may not be THAT straightforward  ... but it's not that difficult either ...

**Comment by hroff-1902** [comment]
should probably be a separate optimization space

**Comment by Theagainmen** [comment]
As I was thinking about this, I think the pairs in your whitelist are also a BIG part of your tot profit, maybe a hyperopt function that checks your whitelist (or blacklist) and filters out the bad ones? But looking at the message above I think this one will require more programming and is not that easy to implement :3

**Comment by hroff-1902** [comment]
Updated the title to reflect the content of the issue.

**Comment by hroff-1902** [comment]
@Theagainmen pls test it (merged into current develop)
