### ISSUE TITLE
WARNING: Unable to sell trade: Insufficient funds to create limit sell order on market

### ISSUE THREAD

**Issue by cyberjunky** [freqtrade/freqtrade#2383]
## Describe your environment

  * Operating system: Ubuntu 18.04.3 LTS
  * Python Version: Python 3.6.8
  * CCXT version: ccxt==1.18.1208
  * Branch: Develop
  * Last Commit ID: 06ab51b53d9c7b5bc43e0cdd03d704376aa71c26
  
## Describe the problem:

Sometimes a buy fails for the total amount, due to a timeout, for example:

Binance: Buying OMG/BTC
at rate 0.00009590
(0.050000 BTC,362.484 EUR)

A bit later:
Status: Remaining buy order for OMG/BTC cancelled due to timeout

A portion is bought, but in the database (trades) the total amount is written.

Trade ID: 26 (since 35 minutes ago)
Current Pair: OMG/BTC
Amount: 235.17 (0.0225528 BTC)
Open Rate: 0.00009590
Current Rate: 0.00009590
Current Profit: -0.20%
Stoploss: 0.00007193 (-25.00%)

The real amount bought in Binance is 234.93

So when it want to sell the items, there areinsufficient funds on Binance... Resulting in these kind of errors:

Unable to sell trade: Insufficient funds to create limit sell order on market OMG/BTC.Tried to sell amount 235.17 at rate xxx.Message: binance Account has insufficient...

### Observed Results:

  * What happened?
See Above

  * What did you expect to happen?
I expect that the trades table contains the updated amount of bought coins after a timeout to reflect the real amount so a sell cannot fail. (resulting in losses)

**Comment by xmatthias** [comment]
unfilled / half-filled timeouts are a known problem (#1858) ... 

Would you have the logs from right after the buy / cancel?

I'm looking for messages like `Half bought? Amounts don't match` or `"Amount xxx does not match amount`  ...

Thanks in advance

**Comment by cyberjunky** [comment]
I looked for similar issues before opening issue, but didn't notice the one you mentioned, overlooked it..

Here are the log snippets related to my example:
```
Oct 17 05:32:02 server python3[13987]: 2019-10-17 05:32:02,674 - freqtrade.freqtradebot - INFO - Partial buy order timeout for Trade(id=26, pair=OMG/BTC, amount=235.17000000, open_rate=0.00009590, open_since=2019-10-17 03:21:59).
Oct 17 05:32:02 server python3[13987]: 2019-10-17 05:32:02,674 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'Remaining buy order for OMG/BTC cancelled due to timeout'}
Oct 17 05:32:03 server python3[13987]: 2019-10-17 05:32:03,177 - freqtrade.wallets - INFO - Wallets synced.
Oct 17 09:33:07 server python3[13987]: 2019-10-17 09:33:07,913 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Insufficient funds to create limit sell order on market OMG/BTC.Tried to sell amount 235.16 at rate 9.61e-05.Message: binance Account has insufficient balance for requested action.
```
Last one repeats until I manually correct the trades table record with correct OMG/BTC amount
```
UPDATE trades
SET amount=234.93 WHERE id=26;
```
```
Oct 17 09:33:12 server python3[13987]: 2019-10-17 09:33:12,925 - freqtrade.persistence - INFO - Updating trade (id=26) ...
Oct 17 09:33:12 server python3[13987]: 2019-10-17 09:33:12,925 - freqtrade.persistence - INFO - Marking Trade(id=26, pair=OMG/BTC, amount=234.93000000, open_rate=0.00009590, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.
Oct 17 09:33:12 server python3[13987]: 2019-10-17 09:33:12,925 - freqtrade.persistence - INFO - LIMIT_SELL has been fulfilled for Trade(id=26, pair=OMG/BTC, amount=234.93000000, open_rate=0.00009590, open_since=closed).
Oct 17 09:33:12 server python3[13987]: 2019-10-17 09:33:12,945 - freqtrade.exchange.exchange - INFO - returning cached ticker-data for OMG/BTC
```

I see no other related errors or warnings. As far as I can see the update of bought amount is not corrected after the timeout warning. 
A quick fix could be to check the amount in wallet after these errors/warnings occur and if it's lower than the db amount correct it. (maybe easier said then done)

**Comment by xmatthias** [comment]
This is strange - right before the output of `Partial buy order timeout for ...` the amount should be updated. 

https://github.com/freqtrade/freqtrade/blob/df62dd65d3ff3c04492f2fb91affa136f533d3eb/freqtrade/freqtradebot.py#L811-L816

Can you please provide the output of the below (either the commented line if you know the order id, otherwise the statement below).


```
import ccxt
from datetime import datetime
ct = ccxt.Binance({'apiKey': 'yourkey', 'secret': 'yoursecret'})
# ct.fetch_order('order_id', 'pair')
ct.fetch_orders(symbol='OMG/BTC', since=int(datetime(2019, 10, 17, 8, 0).timestamp()))
```

**Comment by cyberjunky** [comment]
All OMG/BTC orders since 05:00 today below.
So the filled value is same as the one in the database!
But it's not the amount available in my Binance wallet after the buy (234,93)
Any idea, has to with fees, timing/latency, slippage?
I'm a cryptotrader novice, so don't shoot me ;-)
BTW I changed the Client and OrderID's not to give away sensitive data.

`#!/usr/bin/python
#
[{
    'info': {
        'symbol': 'OMGBTC',
        'orderId': 62125617,
        'orderListId': -1,
        'clientOrderId': 'iuqVeqm5s4NulGg0nMMW8B',
        'price': '0.00009590',
        'origQty': '521.37000000',
        'executedQty': '235.17000000',
        'cummulativeQuoteQty': '0.02255279',
        'status': 'CANCELED',
        'timeInForce': 'GTC',
        'type': 'LIMIT',
        'side': 'BUY',
        'stopPrice': '0.00000000',
        'icebergQty': '0.00000000',
        'time': 1571282519521,
        'updateTime': 1571283122559,
        'isWorking': True,
        },
    'id': '62125617',
    'timestamp': 1571282519520,
    'datetime': '2019-10-17T03:21:59.521Z',
    'lastTradeTimestamp': None,
    'symbol': 'OMG/BTC',
    'type': 'limit',
    'side': 'buy',
    'price': 9.59e-05,
    'amount': 521.37,
    'cost': 0.02255279,
    'average': 9.589994472084025e-05,
    'filled': 235.17,
    'remaining': 286.20000000000005,
    'status': 'canceled',
    'fee': None,
    'trades': None,
    }, {
    'info': {
        'symbol': 'OMGBTC',
        'orderId': 62131619,
        'orderListId': -1,
        'clientOrderId': 'DFVLrHoY8Z2xYichNKelAA',
        'price': '0.00009610',
        'origQty': '234.93000000',
        'executedQty': '234.93000000',
        'cummulativeQuoteQty': '0.02257677',
        'status': 'FILLED',
        'timeInForce': 'GTC',
        'type': 'LIMIT',
        'side': 'SELL',
        'stopPrice': '0.00000000',
        'icebergQty': '0.00000000',
        'time': 1571297592794,
        'updateTime': 1571297592794,
        'isWorking': True,
        },
    'id': '62131619',
    'timestamp': 1571297592794,
    'datetime': '2019-10-17T07:33:12.794Z',
    'lastTradeTimestamp': None,
    'symbol': 'OMG/BTC',
    'type': 'limit',
    'side': 'sell',
    'price': 9.61e-05,
    'amount': 234.93,
    'cost': 0.02257677,
    'average': 9.609998723023879e-05,
    'filled': 234.93,
    'remaining': 0.0,
    'status': 'closed',
    'fee': None,
    'trades': None,
    }]
`

**Comment by xmatthias** [comment]
Nobody will be shot here (not today, anyway ...)

I think the relevant section is the following
```
  'amount': 521.37,
    'cost': 0.02255279,
    'average': 9.589994472084025e-05,
    'filled': 235.17,
    'remaining': 286.20000000000005,
```

the order was for 521.37 - it filled 235.17 (the entry in the database) - and had 286.2 remaining (the logic to update the amount did work).

Now you are left with 234.93 - which is 0.239 - or 0.1xx% ... so yes, i suspect that you're right, it's fees which are missing.


Can we please have the response for the question about the Trades too (it'll include how fees were calculated).

```
import ccxt
from datetime import datetime
ct = ccxt.Binance({'apiKey': 'yourkey', 'secret': 'yoursecret'})

ct.fetch_my_trades(symbol='OMG/BTC', since=int(datetime(2019, 10, 17, 5, 0).timestamp()))
```

**Comment by cyberjunky** [comment]
This is the trades query output.

```
#!/usr/bin/python
#
[{
    'info': {
        'symbol': 'OMGBTC',
        'id': 10244928,
        'orderId': 62125617,
        'orderListId': -1,
        'price': '0.00009590',
        'qty': '132.53000000',
        'quoteQty': '0.01270962',
        'commission': '0.13253000',
        'commissionAsset': 'OMG',
        'time': 1571282519521,
        'isBuyer': True,
        'isMaker': False,
        'isBestMatch': True,
        },
    'timestamp': 1571282519521,
    'datetime': '2019-10-17T03:21:59.521Z',
    'symbol': 'OMG/BTC',
    'id': '10244928',
    'order': '62125617',
    'type': None,
    'takerOrMaker': 'taker',
    'side': 'buy',
    'price': 9.59e-05,
    'amount': 132.53,
    'cost': 0.012709627,
    'fee': {'cost': 0.13253, 'currency': 'OMG'},
    }, {
    'info': {
        'symbol': 'OMGBTC',
        'id': 10244931,
        'orderId': 62125617,
        'orderListId': -1,
        'price': '0.00009590',
        'qty': '100.00000000',
        'quoteQty': '0.00959000',
        'commission': '0.10000000',
        'commissionAsset': 'OMG',
        'time': 1571282519521,
        'isBuyer': True,
        'isMaker': False,
        'isBestMatch': True,
        },
    'timestamp': 1571282519521,
    'datetime': '2019-10-17T03:21:59.521Z',
    'symbol': 'OMG/BTC',
    'id': '10244931',
    'order': '62125617',
    'type': None,
    'takerOrMaker': 'taker',
    'side': 'buy',
    'price': 9.59e-05,
    'amount': 100.0,
    'cost': 0.00959,
    'fee': {'cost': 0.1, 'currency': 'OMG'},
    }, {
    'info': {
        'symbol': 'OMGBTC',
        'id': 10244930,
        'orderId': 62125617,
        'orderListId': -1,
        'price': '0.00009590',
        'qty': '2.64000000',
        'quoteQty': '0.00025317',
        'commission': '0.00264000',
        'commissionAsset': 'OMG',
        'time': 1571282609097,
        'isBuyer': True,
        'isMaker': True,
        'isBestMatch': True,
        },
    'timestamp': 1571282609097,
    'datetime': '2019-10-17T03:23:29.097Z',
    'symbol': 'OMG/BTC',
    'id': '10244930',
    'order': '62125617',
    'type': None,
    'takerOrMaker': 'maker',
    'side': 'buy',
    'price': 9.59e-05,
    'amount': 2.64,
    'cost': 0.00025317600000000003,
    'fee': {'cost': 0.00264, 'currency': 'OMG'},
    }, {
    'info': {
        'symbol': 'OMGBTC',
        'id': 10245304,
        'orderId': 62131619,
        'orderListId': -1,
        'price': '0.00009610',
        'qty': '234.93000000',
        'quoteQty': '0.02257677',
        'commission': '0.00002258',
        'commissionAsset': 'BTC',
        'time': 1571297592794,
        'isBuyer': False,
        'isMaker': False,
        'isBestMatch': True,
        },
    'timestamp': 1571297592794,
    'datetime': '2019-10-17T07:33:12.794Z',
    'symbol': 'OMG/BTC',
    'id': '10245304',
    'order': '62131619',
    'type': None,
    'takerOrMaker': 'taker',
    'side': 'sell',
    'price': 9.61e-05,
    'amount': 234.93,
    'cost': 0.022576773,
    'fee': {'cost': 2.258e-05, 'currency': 'BTC'},
    }]

```

**Comment by xmatthias** [comment]
Thanks for your help - #2384 will fix this case and apply the fees correctly the logic was there for a long time - just not applied to cancelled trades.

**Comment by cyberjunky** [comment]
Thank you for the prompt reply and help, I guess I can test your branch improve_buy_timeout_handling ?

**Comment by xmatthias** [comment]
yes of course - or use develop - since the change has been merged a few hours ago :)
