### ISSUE TITLE
No module named 'filelock'. Please ensure that the hyperopt dependencies are installed.

### ISSUE THREAD

**Issue by sidnicholas** [freqtrade/freqtrade#2385]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Ubuntu
  * Python Version: Python 3.6.8
  * CCXT version: ccxt==1.18.860
  * Branch: Develop
  * Last Commit ID: 31389b38f198779f2b0f05fe704cb913736779c3

I am using freqtrade in a docker container - No module named 'filelock'. Please ensure that the hyperopt dependencies are installed.

  
## Step 3: 
I am using freqtrade in a docker container.

I haven't been able to get hyperopt to work properly.  The error message I get when I execute hyperopt is "No module named 'filelock'. Please ensure that the hyperopt dependencies are installed."
This is the command I am executing:  
docker run  -v ~/.freqtrade/config.json:/freqtrade/config.json   -v ~/.freqtrade/user_data/:/freqtrade/user_data   -v ~/.freqtrade/tradesv3.sqlite:/freqtrade/tradesv3.sqlite   freqtrade --db-url sqlite:///tradesv3.sqlite hyperopt --customhyperopt hyperopt_BBRSI -e 100

Thanks

**Comment by hroff-1902** [comment]
* make sure you updated dependencies, run `pip3 install -r requirements.txt`
* recreate Docker image

**Comment by sidnicholas** [comment]
Update:  I am still having problems running hyperopt
Here are the steps I took - Keep in mind I am a novice developer
I had a previous installation of freqtrade on my ubuntu machine.  I copied the following requirements file to the directory I used for the docker installation.
Requirements docs
requirements-common.txt
requirements-dev.txt
requirements-hyperopt.txt
requirements-plot.txt
requirements.txt

I ran all the above files above using:
pip install -r requirements*.txt
All the requirements for all the files appeared to install

I then rebuilt the image using:
docker build -t freqtrade -f Dockerfile.technical .

A new image was successfully built .

I think tried running my hyperopt file again but I got the same error message:
No module named 'filelock'. Please ensure that the hyperopt dependencies are installed.

Thanks for any help you can offer.

**Comment by xmatthias** [comment]
Create a new docker file as follows and build that - with that image, hyperopt should work.

``` Dockerfile
FROM freqtradeorg/freqtrade:develop
RUN pip install -r requirements-hyperopt.txt
```

**Comment by hroff-1902** [comment]
or create docker image using Dockerfile.develop -- it contains everything, including hyperopt dependencies...

@xmatthias, should we add the Dockerfile.hyperopt file, which builds image using requirements-hyperopt.txt?

**Comment by xmatthias** [comment]
i don't know yet - i'll need to test how different the size of the image is if hyperopt dependencies are installed ... having another different image will make running things complicated soon ...

**Comment by xmatthias** [comment]
The hyperopt image is ~100 Mb bigger in size (from 889MB to 1.01Gb).

```
freqtrade_hyp                   latest               c30e25d2f9a3        43 seconds ago      1.01GB
freqtrade_nohyp                 latest               cefb99712830        6 minutes ago       899MB
```

I don't think that these 100 Mb matter that much, so i'll include hyperopt dependencies to the docker image again.

**Comment by sidnicholas** [comment]
Okay, thanks for the update.

**Comment by hroff-1902** [comment]
@sidnicholas  #2395 merged to develop, pls update freqtrade to the current develop, check the solution and report back.
Please free to reopen in case of problems,

**Comment by Antonio-Bit** [comment]
Hello folks, I would reopen this issue as I'm facing the same problem with the stable version "freqtrade 2022.9.1". 

`2022-10-12 12:00:06,235 - freqtrade - INFO - freqtrade 2022.9.1`
`2022-10-12 12:00:06,237 - freqtrade - ERROR - No module named 'filelock'. Please ensure that the hyperopt dependencies are installed.`

This is the command I run:
`docker-compose run --rm -d freqtrade hyperopt --config user_data/config.json --strategy bb_riding --epochs 10 --spaces roi stoploss --hyperopt-loss SharpeHyperOptLoss`

Would you be able to check whether there is some sort of regression? 

Thanks a mil

**Comment by xmatthias** [comment]
We will not reopen an issue that's 3 (!) years old.
please open a new issue if you think you encounter a similar problem - providing full details (including the image you're actually using in your compose file).
