### ISSUE TITLE
Edge state of art/feedback (question)

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2409]
Hi there,

I d like to know what is the state of edge and his future. Seems to have an [open issue](https://github.com/freqtrade/freqtrade/issues/1334) that don't move a lot.

And this a specific tactic to position management but not the sole.

Any feedback on persons using on live (tips/tricks)? For example the default config look back 7 days with min 10 trades for a pair but seems that the sample is very slow and maybe lead to overfitting ?

Many tks :-) 

Have a nice day

**Comment by xmatthias** [comment]
As far as i know, edge works as expected.

The open issue seems explained below by @mishaker, so we maybe can close that issue - but i'm not that familiar with edge, and never looked deeply into the math of this issue.

Personally, I think edge does too much with too little flexibility ... 

as ~~discussed~~ discussing in #2183 (ongoing) - we'll try to bring position management into the strategy, so you could define `dataframe['buy']=0.2` and it'll buy 20% of your position (for example - not decided yet).
That's a long-term plan though - so don't expect anything soonish yet, as this will need to be properly defined before implementing - changing the interface is always a pain-point as it requires manual interaction  / modifications as part of an upgrade.

**Comment by gaugau3000** [comment]
Many tks for this feedback i will try to read #2183 and contribute in i have some ideas.

**Comment by gaugau3000** [comment]
Hi, i try to rephrase in the **documentation -> features** the edge module (with a certain difficulty) and then i remember that edge make optimization based on stoploss and then choose markets witch is another kind of optimization : he can make is optimization on a non representative sample `"min_trade_number": 10` by default

Pretty sure it he don't perform well in live because of this over-fitting bias. 

I am curious to know person using it in live.

Maybe you have a vision about this tool but i am not sure about provide a out of the box for end user ?

**Comment by xmatthias** [comment]
why is 10 trades in 7 days overfitting? Yes, the values depend on the timeframe.

However, you're assuming the default configuration - so please also assume this for 5m tickers ... 
and for 5m tickers, i would rather trade a pair that had > 10 trades in the last X days.

Yes, this is unrealistic if you use longer candles - but so is using 7 days of backtest time - and 1440 as "max_trade_duration_minute"  - but for the standard (5m tickers) - this should be fine.

I personally don't use edge - but i know @mishaker  spend a ton of time finding "sensible" default parameters.

**Comment by Blackhawke** [comment]
I know this is an old thread (and not so much an issue, at least not coding wise), but as someone whose still trying to understand how Edge works in real time, I want to check my understanding:

 * Run independently, Edge uses historical data to produce the output chart showing the expected W/R/E based on its calculations as determined by the config settings.

* Unless limited by the use of the `--timeframe` switch, these results are calculated using the *entire* database, so there's no way to know when/how these trades might have played out "in real time". 
  * IOW, if a pair shows 10 trades (historically) occurred over 100 days,  that could mean that the pair was "whitelisted" for a brief period ten times over that 100 days, or it may mean that the pair was "whitelisted" once during that 100 days and 10 trades took place in that interval, or anything in between. There's simply no way to know.
 * Which means that, when running live, a continuous stream of `freqtrade.freqtradebot - INFO - Active pair whitelist is empty` in the log is---or could be---quite normal as it is reasonable to assume there will be periods where none of the pairs in the `StaticPairList` meet Edge's criteria to be sent on to the trading strategy for consideration.

Am I understanding this correctly? If I am, this should be added to the documentation (which I can do) to help noobs like me understand how Edge fits into the bot's decision making process.

**Comment by gaugau3000** [comment]
@Blackhawke Just my opinion but edge use a sample of trades to find the best stop loss on each market (use Expectancy Ratio) -> there is no theory behind that (why change stop loss depending market ? if market is volatile maybe use a stop loss based on average true range ?).

Honestly i think edge is misguidance for new users and introduce complexity for no reasons.

Tell yourself why one day a stop loss is -0.03 on a market and then 1 month later -0.06 and the next month -0.03 -> the market change that fast ? and if it change what is it maybe volatility only ?

I am sorry to not answer to your points in detail but before going to deep into it you should ask what theory there is behind edge ? 

Use an expectancy ratio as a criteria of evaluation compute on stop loss change value why ?

We all would like to find an edge in trading and the edge module by is naming introduce a kind of confirmation bias i have find the holy grail (the same with hyperopt witch suffer of surviving biais because we use this hype ml overkill algorithm).

GL. Hope this help.

**Comment by Blackhawke** [comment]
Excellent points, and thanks for the input.

I think the docs say something about who did the original design work on Edge, but little more than the basics about W/R/E. There's nothing about the questions I asked above (real time operation) and so also nothing about how it interacts with the market in real time to adjust Expectency. In my testing, for instance, I found out that results changed simply by moving the start/stop dates by one day. I found that fascinating.

Anyway, it would be nice to hear the original developer's thoughts, or from someone who knows them.

As for the magical Trading Edge(tm): I hear you, but I seriously doubt freqtrade is the kind of software those who still believe in faeries (i.e. the crypto version of the RobinHood crowd) are likely to use. They're much more likely to plop down $10,000 to get that secret, magical, trading strategy, complete its shiny, private, version of a Slack channel.  Too, if I recall correctly (I'm mobile right now, so don't have the docs in front of me), the name refers to positioning, as in "Edge Positioning", not some magic formula.

**Comment by xmatthias** [comment]
In the end, it mostly depends on your config.

Yes, edge uses historical data based on the configuration.
`--timeframe` is not relevant for "trade" operations - but `calculate_since_number_of_days` is. If this is to 7, edge will use the history of the last 7 days to calculate this.

Now depending on the activity of your strategy (200 trades a day / 1 trade a day) this might be too low a timerange to find `min_trade_number` for a pair - so you should increase `calculate_since_number_of_days` to match your strategy.
Now if these 2 configs (+ `minimum_expectancy`) don't match your strategy, you'll have the "whitelist is empty" message most of the time.
This can be normal (also a strategy with an average of 200 trades per day over a year can have these trades in "bursts" - doing 400 trades one day, and 0 trades the next ...) - but usually it shouldn't happen when configured correctly.

---

edge itself is not really related to backtesting in that sense.
We have edge-cli - which does the same calculation it does in real time operations over the last X days for `--timerange` - if you don't use this, it'll use all available data (but this is only true for edge-cli - not for trade operations using edge!).

It's an alternative, limited form of backtesting. 
I say limited as it ignores ROI / trailing stoploss - therefore excludes all strategies that rely on either of these for sell signal (and don't generate a sell-signal themselfs).

You therefore need to be "a bit" careful with how the strategy is setup - as edge's simulation can stay in a trade for a week, while real trading would've sold it after an hour based on 1% ROI.
Not having ROI and trailing stop is a main drawback to me - so personally, i don't use it.


-----

I don't disagree with @gaugau3000, edge gives your mind the sense that this is an "edge" over all other users of Freqtrade (which may or may not be true).
Now you can belive in it's methods or not - that's not really the point i think - i think it can work for certain strategies - but certainly doesn't work for all strategies.

To me, Edge does "too much" - and thinking about it now, should've been done differently (you are always wiser in the aftermath...). 

It's combining dynamic stoploss, dynamic stake positions, and whitelist generation into one isolated module.
This is problematic as it's ONLY available as one package - but you can't do dynamic stoploss without enabling all of Edge (so it's also managing your whitelist, ...).


Hope the above answers  most of your questions  ...

**Comment by Blackhawke** [comment]
Thanks @xmatthias. So, if I took your next to the last sentence and used it as a description of  Edge like so:

> Edge combines dynamic stoploss, dynamic positions, and whitelist generation into one isolated module which is then applied to the trading strategy. It can, therefore, improve the performance of some trading strategies while decreasing the performance of others.

Would that be a correct description?

Then there's this from the other end of your post, which should probably go elsewhere in the doc (don't know yet):

> Edge ignores historical information based on your configuration (`--timeframe`) and instead uses `calculate_since_number_of_days`, which it compares to `minimum_expectancy` to find `min_trade_number`. If no `min-trade_number` is found, the bot will return "whitelist empty". After the `process_throttle_secs` has passed, Edge will again process `calculate_since_number_of_days` against `minimum_expectancy` to find `min_trade_number`.

> If `calculate_since_number_of_days` and `minimum_expectancy` are not set correctly according to the methodology being deployed by the strategy, Edge may return a "whitelist empty" message most of the time&mdash;or *all* the time. It is also possible that the deployed strategy will cause trading to happen in bursts with long periods of inactivity, though when correctly configured this is a rarity.

Finally, you mentioned edge-cli, which should get a paragraph or two. Is there more on its use somewhere? (I did a search on freqtrade.io but it doesn't return anything useful.)

**Comment by xmatthias** [comment]
well - edge documentation would need some love (edge itself might want some love ... )

`edge-cli` is really `freqtrade edge` (which is mentioned in the edge docs ...)- but it's  different to running `freqtrade trade` with edge enabled ... so calling it `edge` above would make the whole sentence quite difficult to grasp due to the naming collision.

**Comment by Blackhawke** [comment]
An update to the Edge documentation is what I'm doodling on here, so yeah. :) 

Okay, so `edge-cli` is really `freqtrade edge`, but Edge doesn't operate in real time (`freqtrade trade` with edge enabled) like it does when "backtesting" with `freqtrade edge`, which can cause unexpected results. Considerable dry-run testing is probably wise. (Does that about cover it?)

Also, whose the original developer of the edge module, or was this a team effort?

**Comment by xmatthias** [comment]
well, i think you must consider edge as 2 things:
* `freqtrade edge` - which is comparable to a limited version of backtesting  
* `freqtrade trade` with edge enabled - which runs edge every few hours (on a limited, rolling dataset) - to determine fresh results.

Yes - dry-run is wise - but that's true for every strategy - as sometimes backtesting can seem great - while it won't work in reality (like using a very very close stoploss ...).

the developer was @mishaker (after this he'll get a notification - so he'll probably put his comments here too...).

**Comment by Blackhawke** [comment]
Hopefully @mishaker will, indeed chime in. I should have time to work on some changes to the documentation page this coming weekend. (And I'll be using this discussion as reference. :> )

**Comment by xmatthias** [comment]
Going to close this as #3677 does improve documentation around edge.
