### ISSUE TITLE
--export-filename flag and backtest results location

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2410]
Hi,

On docker,

When i export the backtest results using --export-filename flag it seems to export at the project root but not in /freqtrade/user_data/backtest_results/* (I need to specify --export-filename=/freqtrade/user_data/backtest_results/_StrategyName.json_)

Have a nice day

**Comment by xmatthias** [comment]
`--export-filename` needs to be a (relative) path ...
it defaults to `user_data/backtest_results/backtestresults.json` - for docker the same should work (assuming user_dir is mounted into the container).

Only specifying `--exportfilename MyFileName.json` does not (and never did) export this to the backtest-results directory, but to cwd (current working directory), not within a docker container, and not outside of it ...

**Comment by gaugau3000** [comment]
Ok my bad :-) tks
