### ISSUE TITLE
Errorneous handling of active_pair_whitelist

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2413]
`Freqtradebot._active_pair_whitelist` is changed in the `process()` method while throttling: first it obtains the content of the whitelist config setting or a dynamic pairlist, then the list can be adjusted by the Edge, then it's extended with the list of pairs from the open trades.

It's okay for the trading logic, which is run in the same thread. However, it's accessed in the rpc modules as well, that typically run in different threads (for api server and telegram at least), so fetching of its value is performed independently of the transformations described above. As a result, two subsequent calls to `_rpc_whitelist()` may report completely different results: either the list from the config, or one after Edge, or one extended with trades.

All transformations of the active_pair_list in freqtradebot should be done using either local vars or another intermediate attribute, and active_pair_list should only get the resulting list after all transformations.

Btw, it's actually not active pair whitelist, but active pair list (maybe renamed during fix of this issue, to reflect its content more precisely).

**Comment by hroff-1902** [comment]
Found during WiP on #1861, I would not include there the changes that are not explicitly related to it but needs to be changed/fixed/refactored, to keep the PRs observable.

**Comment by hroff-1902** [comment]
@xmatthias it's not a problem to fix it, the question is what of those 3 values are to be fetched by `_rpc_whitelist()` and used by rpc modules then: 1) pair list after pairlist/whitelist from config in case of static pairlist used; 1.2) whitelist minus blacklist, in case of static pairlist? 2) pair list after Edge 3) pair list extended with trades...

**Comment by xmatthias** [comment]
3. - it's the pairlist that's really used ... 

I'm not sure if this is a realistic problem though (apart from edge - where i guess this can happen).
Ignoring edge for now - then there is no calculation involved between the updates, no networking... so between setting `active_pair_whitelist` and extending it it's milliseconds if not less - so i'm not sure if it's realistic to experience this while calling /whitelist.

Yes, it's possible in theory - but changes are very low...

**Comment by xmatthias** [comment]
I'll "accidentally" fix this in #2417 ... :D
