### ISSUE TITLE
Introduce Dry run wallet 

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2421]
Hi,

Most of the volume in crypto move from XXX/BTC to XXX/USDX so have more than 999.9 dollar in the wallet is not a big deal.

I say that because i have this beautiful message during my dryrun because i missed this point (and of course i don't see it because i monitor my logs like a stupid idiot ) :-)

> WARNING - Unable to create trade: Available balance(999.9 USDT) is lower than stake amount(1000 USDT)

What do you think about it ?

Have a nice day.

**Comment by xmatthias** [comment]
I'm not sure what you'd expect ...
if you use `stake_amount` = 1000 - then you must set `dry_run_wallet` to something > than that.

Note that `dry_run_wallet` has no practical use other than that - so it's not the "starting point" - and you can get the final balance out of that...  It's used for stake-calculations (for example when using edge / unlimited stake amount.

**Comment by gaugau3000** [comment]
Yes it is because i have a representation that my dry_run_wallet was unlimited :-) so i missed the dry_run_wallet config part . But this value 999.9 seems like to be choose like a kind of arbitrary unlimited btc (lucky if you have more 999.9 BTC :-) ) maybe i'm wrong. 

Maybe increase this value as USDX becomes more popular or an unlimited dry_run_wallet amount default if edge disable/unlimited stake amount not use

This idea is behind : 
- Ok i make a dry run don't take care about wallet because i manage that after to see how max open trade i use for this strategy. 

Have a nice day.

**Comment by xmatthias** [comment]
999.9 is a default choosen for BTC (yes, arbitrarily high to simulate unlimited funds). 

if you use another currency, you should change this to something that fit's it's rate (USDT probably 10000 or 100000).

Personally, i think that also dry-run should be assigned a starting balance, keep track of this (just as you would do in live trading ...).
That would make dry-run feel more real ... and would allow simulating compound gains 
 (or losses) by using dynamic stake amounts.

**Comment by gaugau3000** [comment]
> 999.9 is a default choosen for BTC (yes, arbitrarily high to simulate unlimited funds).

If there is a default for BTC why there is not a default for USDX ? (it is not a big deal but got the impression freqtrade to be more design for BTC pairs ;-) )

> Personally, i think that also dry-run should be assigned a starting balance, keep track of this (just as you would do in live trading ...).

Yes I agree. By the way even if telegram is not the best place to monitor the bot performance dry run balance are disabled. (maybe it can be useful to see the dry run balance, i can open an other topic ? )

**Comment by xmatthias** [comment]
there is ONE default for this value ... 

the sample configuration is setup for BTC ... yes, we could have one sample config for every possible stake - but that would make selecting the correct configuration almost impossible.
Honestly, most "stable" coins were not a thing a year ago, and 90% of crypto trading happened between xxx/BTC or xxx/ETH.
This has now changed, more stable coins are now tradable (also with freqtrade - selecting the correct pairs and stake currency).

**Comment by gaugau3000** [comment]
To summarize and tell if i'm wrong.
-> the dry run wallet is used only for stake-calculations but the dry run wallet does not evolve depending on trade results and is not persistent.

You label it at Enhancement for i think the persistence feature ? I create a new issue for that or i rename the topic to reflect the enhancement part?

Have a nice day.

**Comment by xmatthias** [comment]
I've renamed it now, you're right, the title did not reflect the enhancement well.

i think persisting it would not be "too" difficult ... depending on the "level of persistence" we'll want.
If we assume `dry_run_wallet` (the start amount) is not modified in the configuration, then i think we can calculate it out of the trades database with relative ease without adding too much complexity.

I've only had a very brief look at it though as i was "sidetracked" by other issues (and life) ....
