### ISSUE TITLE
Manually closing trade in sql

### ISSUE THREAD

**Issue by sanitariu** [freqtrade/freqtrade#2424]
Hello,
For some reason kraken added me to firewall and bot was unable to close successfully a trade.
Now it prints not enough funds because it still thinks that it holds the currency.
Trade is still open in database. How i can manually close/remove it ?
I tried /forcesell all but it can not close because not enough money.
Does anyone knows good value for queries delay so kraken do not add you in the blocked list ?

**Comment by xmatthias** [comment]
try this: [sql cheatsheet](https://www.freqtrade.io/en/latest/sql_cheatsheet/#fix-trade-still-open-after-a-manual-sell-on-the-exchange)

**Comment by xmatthias** [comment]
I'll close this since i think it's explained in detail in the sql cheatsheet.

Feel free to reopen if you still have problems closing the trade.
