### ISSUE TITLE
Plot all trades out of a DB (dry-run / live)

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#2431]
Hi there,

how can I plot all my trades out of the DB in one chart? As many traders I try to trade with multiple USDT pairs and it would be very nice to have all of them in one chart for analysis.

As far as I understand this is not possible at the moment, I would need to plot 10 charts (one per pair) if I would have for example 10 USDT pairs in my database to see all trades in a chart - correct? 

In the plot-profit function there is one chart where the profit per pair is being illustraded for all the pairs, I am thinking on a similar chart

Thanks and BR

**Comment by xmatthias** [comment]
Hi there,

i'm sorry, but that does not make any sense.

No exchange i know shows you more than one pair in the same candle-plot.

The main reason for that is that the ranges of the different prices can differ greatly (looking at USDT pairs - you can have 9k for BTC, and 150 for ETH - so both will only show a horizontal line without ANY comparability.

Comparing profits is possible at the moment - comparing dataframes between pairs does not make sense for the above reasons.

**Comment by Prossi79** [comment]
:) be innovate ... I guess it does make sense especially in the cryptospace as many pairs are heavily correlated. If BTC/USDT drops, most of the altcoins do the same. But you are right, it would need a log scale then ... some USDT pairs are at 8000, some at 0,01

On some websites which offer crypto data analytics I have seen such graphs.

**Comment by xmatthias** [comment]
Honestly, the more pressing problem here is the fact that plotly struggles to handle more than a month of 5m ticker data for ONE pair. 
If we start adding more it'll only get worse.

However, feel free to add a 3rd plot-method to compare plots and submit a PR - maybe via log-scale and only one trace (so not candles, but single traces) - i will not look at that since i don't see any value in it, and lack the time to develop another plotting method.

**Comment by Prossi79** [comment]
okay, no worries - you are right, if more load is being added to the existing plotting method it 'll be problematic. And you need to set priorities.

If I would be more fluent in coding I would love to add an additional plotting method :)
