### ISSUE TITLE
incorporation of datafeeds into FT?

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#2447]
hello team! I am working with FT for some months now - it is an impressive project and tool. So far I was working with all the technical indicators / analysis available but I am more and more convinced that those "classical" technical indicators should be complemented with other data streams such as the CFGI as sentiment element ->> https://alternative.me/crypto/fear-and-greed-index/#fng   (... just an example, there are many other interesting feeds available, hashrate of BTC, BTC net work transactions etc ->> https://www.blockchain.com/de/charts/hash-rate )

Is this possible to implement into FT via the API they provide? Then to be used as condition in the buy and sell rules in a strategy file? (buy only if CFGI < 25 for example)

Would such kind of enhancement a big thing or just little work which could fit into the current FT structure?

**Comment by xmatthias** [comment]
well i don't think this should go into the freqtrade base codebase.

If you think about it, it's just another form of indicators - not technical ones, but sentiment or other data.

If these projects/sites offer API's, they can be consumed as part of the strategy with ease.

Sometimes it can be as easy as using `requests.get(URL)` (and then doing something with the data), other times an additional library may be necessary.

with "light" coding skills, i'm sure these can be easily integrated into any strategy.
You may need to do some "backoff" code to only query it once every hour (depending on how often the other data refreshes and their rate limits ...) and assign the result to `self.additionaldatafeedwhatever`.

**Comment by xmatthias** [comment]
I'll close this since consumption of custom API's is not part of freqtrade core code, but can (and should) be implemented within the strategy to everyones needs (most likely everyone will want another dataframe, with other parameters and sutch).
