### ISSUE TITLE
Relative stake_amount

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#2458]
This issue will replace #2359 - to summarize the points discussed there relating stake-amount / upper stake_amount_% limits.

### Idea

usage of  `stake_amount="unlimited"` is currently tied to `max_open_trades`.
one stake is always `available_balance / (max_open_trades - open_trade_count)`.

A new config option should be introduced, specifying `stake_amount_max`.
This `stake_amount_max` can either be absolute or relative

* absolute: `stake_amount_max_abs=1`: Even if i have 200 ETH in my account, only trade up to 1 ETH, splitting the 1ETH into `max_open_trades` elements (assuming 2 max_open_trades, it would be 0.5ETH per trade). 
Gains will be kept "untradable" - losses will be eaten up by the remaining 199ETH.

* relative: `stake_amount_max_ratio=0.5`: assuming i have 1 ETH in my account, only trade 50% of the total account. assuming 2 max_open_trades: first 2 trades have a stake of  0.25ETH each.
Won trades will increase the stake used in subsequent trades, lost trades will decrease this.

**note:** These options will require `stake_amount` to be absent or "unlimited".

###  discussion points:

* [ ] is `stake_amount_max_abs` even needed? it's just another way to specify `stake_amount=0.5`, `max_open_trades=2` - which will do exactly the same.
* [x] how to handle `stake_amount_max_ratio` in conjunktion with dry-mode - since it does currently not keep track of balance.

** future addons**
support compound-gains for backtesting ...

**Comment by gaugau3000** [comment]
Hi,

just a general through about this topic. Why we would like to increase or decrease risk between two trades with a stake_amount_max_ratio ? It is like a psychological argument like if i loose i reduce the size if i win i increase the size (like a revert martingale) : it seems like a risk management based on fear and greed :-) .

If each trade is independent i want the risk to be the same all the time and i provision money for draw-downs.

And about compound-gains you may want to simulate this with n bots like a bot portfolio but as a strategy level i am not sure. I love the story telling of compound-gains but using it in real i am not sure.

Have a nice day.

**Comment by xmatthias** [comment]
mh that's an interresting aspect to this - and i think that's where `stake_amount_max_abs` comes in.

Maybe it's not clear from above - but `stake_amount_max_ratio` (or `stake_amount_max_abs`)  would be the upper limit - so by limiting it with an absolute value, you're not increasing / decreasing risk over time / depending on previous results.

Everything you own "above" `stake_amount_max_abs` would be your "provisioned money" for draw-down periods.

where this becomes really interresting is in combination with #2183 - which "envisions" the strategy to return a % of a position it should enter - so you could say:
"risk 50% of my total account at max - and 10% of the enabled balance for this trade" - which would enter a trade with 5% of your total account balance.

Now both will not be implemented tomorrow - and usage of relative stake_amount will definitely be optional - so each user can decide for himself if it's good or bad to use this approach.

**Comment by peeperspoopers** [comment]
This `stake_amount_max_ratio` would most likely solve the problem with #2489 and allow for `stake_amount=unlimited` usage without problems.

**Comment by hroff-1902** [comment]
I understand that this issue should be resolved before adding the position management. Otherwise it would be inconvenient behavior...

**Comment by hroff-1902** [comment]
The idea is brilliant 👍 , but another name should be used imho.

0.5 of what? Wallet? Balance? The setting should probably be called `tradable_balance_ratio` or `tradable_wallet_ratio` ( or simply `tradable_balance` or `tradable_wallet`).

As for the absolute limit, this can also be convenient for a user at the first glance, but in this case we should check that any 2 of `max_open_trades`, `stake_amount` and `take_amount_max_ratio_abs` (whatever name it will have) are set to fixed values. One and only one of them should be omitted or set to `"unlimited"`, it can be calculated using 2 others... So it's pretty complicated. Thus this probably is not required, to keep it simple.

**Comment by xmatthias** [comment]
well the name is "flexible" ... it's not important how it's called in the end as long as it's clear what it does.

so to understand your point correctly - `tradable_balance_ratio` - yes
`take_amount_max_ratio_abs` - better no to avoid confusion (since `take_amount_max_ratio_abs` / `max_open_trades` = `stake_amount` anyway) ?

**Comment by hroff-1902** [comment]
Right.

The boat will sail well or not depending on the name you give to it... 😉

**Comment by xmatthias** [comment]
not true - call it "sinking ship" and no one will feel safe :D

**Comment by hroff-1902** [comment]
I'm exactly about this -- if you call it "Disaster", something will always happen with it...

Same for the names of the settings -- a setting with a bad name can be the constant headache for support, causing misunderstanding and strange questions from the users. So it does make sense.
