### ISSUE TITLE
Documentation for systemctl user service FOR RASPIAN🍓

### ISSUE THREAD

**Issue by Escaliert** [freqtrade/freqtrade#2461]
**For all users who wants to start the freqtrade.service on RASPIAN**🍓

![chrome_VnYTKNZoXw](https://user-images.githubusercontent.com/39638559/68033933-0c7e4400-fcc1-11e9-9680-6286541251ec.png)
👆
**Steps are the same as in https://www.freqtrade.io/en/latest/advanced-setup/#configure-the-bot-running-as-a-systemd-service but the directory on RASPIAN is** 
`pi@raspberry:/etc/systemd/user $`

**copy your freqtrade.service file there and match to your Setup.**
👇
![Code_gMxovnJw0u](https://user-images.githubusercontent.com/39638559/68033941-12742500-fcc1-11e9-871e-ee15b098e4bd.png)
👇
**Start service with**
`systemctl --user start freqtrade`
👌
_done..._

enjoy this lovely bot without typing any command on restarts ❤️

btw i know 🍓 is not a raspberry 😉

**Comment by xmatthias** [comment]
Are you sure?
According to all documentation i found ~/.config/systemd/user/ seems to be correct as well.


> /usr/lib/systemd/user/ where units provided by installed packages belong.
~/.local/share/systemd/user/ where units of packages that have been installed in the home directory belong.
/etc/systemd/user/ where system-wide user units are placed by the system administrator.
~/.config/systemd/user/ where the user puts their own units.

[source archlinuxwiki](https://wiki.archlinux.org/index.php/Systemd/User#How_it_works)

or from [stackoverflow](https://unix.stackexchange.com/a/367237):
> The best place to put user unit files: /etc/systemd/user or $HOME/.config/systemd/user but it depends on permissions and the situation.



Even the manpage agrees with this `man systemd.unit`

`~/.config/systemd/user/` seems correct and is accessible by the user without sudo.
`/etc/systemd/user` needs root level access to the system... which yes - users will probably have on their own raspberry - but should not be necessary.

**Comment by hroff-1902** [comment]
Well, let me find my RPI in the dusty box...

User-specific and system-wide services are both two valid approaches on running the app as a service (on an ordinal systemd system)

**Comment by Escaliert** [comment]
> Are you sure?
> According to all documentation i found `~/.config/systemd/user/` seems to be correct as well.
> 
> > /usr/lib/systemd/user/ where units provided by installed packages belong.
> > ~/.local/share/systemd/user/ where units of packages that have been installed in the home directory belong.
> > /etc/systemd/user/ where system-wide user units are placed by the system administrator.
> > ~/.config/systemd/user/ where the user puts their own units.
> 
> [source archlinuxwiki](https://wiki.archlinux.org/index.php/Systemd/User#How_it_works)
> 
> or from [stackoverflow](https://unix.stackexchange.com/a/367237):
> 
> > The best place to put user unit files: /etc/systemd/user or $HOME/.config/systemd/user but it depends on permissions and the situation.
> 
> Even the manpage agrees with this (`man systemd.unit`)
> 
> `~/.config/systemd/user/` seems correct and is accessible by the user without sudo.
> `/etc/systemd/user` needs root level access to the system... which yes - users will probably have on their own raspberry - but should not be necessary.
> 
> unless raspbian does something completely different ... the way we have it in the documentation should work as well


sorry iam not a coder and maybe it was my fault but this was the only way for me to get the service working on rpi4 without any help :-D sorry if i steal your time but on "SLACK" i told that create an issue isnt a really good idea because the risk that only was my on fault is to high :-D

**Comment by xmatthias** [comment]
> sorry if i steal your time but on "SLACK" i told that create an issue isnt a really good idea because the risk that only was my on fault is to high :-D

This approach is wrong. It sparks discussion and keeps that "findable" for others who may face the same problem.

Maybe you're right - i did not try it on raspbian specifically yet.
I've just been surprised - since all documentation says that `~/.config/systemd/user/` should also work / load the service correctly.

**Comment by hroff-1902** [comment]
@xmatthias I asked him at Slack to report it as an issue because on Slack it will quickly go to the sand, to the Slack history...

@Escaliert thanks alot for reporting, I'll check this on Raspberry, both approaches (system-wide and user-specific services) should work on a 'normal' linux, both should be described in the docs, and probably a special not should be inserted for Raspbian if only one of them is valid for this platform...

**Comment by xmatthias** [comment]
> sorry if i steal your time but on "SLACK" i told that create an issue isnt a really good idea because the risk that only was my on fault is to high :-D

> This approach is wrong. It sparks us to investigate and keeps your findings "findable" for others who may face the same problem.

I tried to point that out as well ... maybe not successfull ... 

I also tried it on a raspbian - and it's not finding the file in the ~/.config location ... even though the system documentation (`man systemd.unit` ) says that it should load from there as well.

I didn't dig deeper into this yet ...

**Comment by Escaliert** [comment]
> 

> > sorry if i steal your time but on "SLACK" i told that create an issue isnt a really good idea because the risk that only was my on fault is to high :-D
> 
> > This approach is wrong. It sparks us to investigate and keeps your findings "findable" for others who may face the same problem.
> 
> I tried to point that out as well ... maybe not successfull ... i definitely meant to say that he did not waste our time!
> 
> I also tried it on a raspbian - and it's not finding the file in the ~/.config location ... even though the system documentation (`man systemd.unit` ) says that it should load from there as well.
> 
> I didn't dig deeper into this yet ...

**Comment by Escaliert** [comment]
> > sorry if i steal your time but on "SLACK" i told that create an issue isnt a really good idea because the risk that only was my on fault is to high :-D
> 
> > This approach is wrong. It sparks us to investigate and keeps your findings "findable" for others who may face the same problem.
> 
> I tried to point that out as well ... maybe not successfull ... i definitely meant to say that he did not waste our time!
> 
> I also tried it on a raspbian - and it's not finding the file in the ~/.config location ... even though the system documentation (`man systemd.unit` ) says that it should load from there as well.
> 
> I didn't dig deeper into this yet ...

hey guys... well, that sounds you didnt get to work on first try too ?

**Comment by Escaliert** [comment]
> > sorry if i steal your time but on "SLACK" i told that create an issue isnt a really good idea because the risk that only was my on fault is to high :-D
> 
> > This approach is wrong. It sparks us to investigate and keeps your findings "findable" for others who may face the same problem.
> 
> I tried to point that out as well ... maybe not successfull ... i definitely meant to say that he did not waste our time!
> 
> I also tried it on a raspbian - and it's not finding the file in the ~/.config location ... even though the system documentation (`man systemd.unit` ) says that it should load from there as well.
> 
> I didn't dig deeper into this yet ...

Sorry iam an idiot xD 
clicked wrong button .... haha

so, this sounds like u didnt get service running on first try too?

**Comment by xmatthias** [comment]
clicking the wrong button happens more often than you might think, so github may need some work on their UI :D 
we have several  issues with "closed / opened"  patterns ... either accidentally closed by us, or by the author ...

> so, this sounds like u didnt get service running on first try too?

no i didn't ... 
i first searched documentation - which all points that `~/.config/systemd/user` is correct (with no mention that it would be different on raspbian).

However i coulnd't get it to work "later" - after i tried .... but i only tried for a short amount of time .... without digging deeper into it.

**Comment by xmatthias** [comment]
You were right - raspbian does not load from `~/.config/systemd/user` (at least not on my image, downloaded ~a week ago).

I've added a note about this to the docs in #2501 (i doubt it's explicitly raspbian specific though ... but can't test all systems) - so i added it in a slightly generic form.

**Comment by hroff-1902** [comment]
How's it related to #2501? (systemd issues and exchange-specific notes)

**Comment by xmatthias** [comment]
because the only change between the existing documentation, and this tutorial is the changed path from `~/.config/systemd/user` to `/etc/systemd/user` - which is now part of the tutorial (mentioning raspbian specifically).

**Comment by hroff-1902** [comment]
ah, you just mixed it there... I did not notice it...
👍

**Comment by xmatthias** [comment]
well, the change is not that huge, but it was a nice find nonetheless :+1:

**Comment by hroff-1902** [comment]
> well, the change is not that huge, but it was a nice find nonetheless 👍

I mean I have missed the second commit there (still sleepy, AWS is killing me 😆)
