### ISSUE TITLE
Hyperopt --continue doesn't work, suggestion

### ISSUE THREAD

**Issue by Theagainmen** [freqtrade/freqtrade#2464]
## Step 1: Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.7 (64-bit)
  * Branch: Develop
  * Last Commit ID: develop-5254059f
  
## Step 2: Describe the problem:

Lately I've had issues with running hyperopts for over 1 month+ or backtesting with multiple strategies for a longer period of time. It would eventually crash with the memory error: `MemoryError: Unable to allocate array with shape (5, 52704) and data type float64`. Upgradeing from the 32-bit version to the 64-bit version made it a lot better. I can backtest for over a year with many strategies. However hyperopting over 150+ days still seem to crash at about 500+ epochs for me. Usually when it tends to go for trades amount > 10k+.

When it crashes I'm left with no information 
![hyperopt](https://user-images.githubusercontent.com/24569139/68069843-30e02c00-fd66-11e9-9211-21016a2c5699.png)

I would love to see a feature that saves the settings from each result that gets printed in this terminal. For example everytime it shows you it made an improvement, it writes it with the settings to a txt file. It's important that it does it while it's in the process and not when it's done. Otherwise when it crashes you're still left with nothing. This way when it crashes I can still see it's output in a txt file.
I could also use `--continue` (which currently doesn't work), but then it will probably go into the same loop where it crashed due to the many trades amount, and I will be left with none optimized output settings.

Reason for these suggestions is because hyperopting takes a long time and is a very intense process, when I'm hyperopting I can't use my PC for anything else (well.. it's very slow). With these things added it would save a lot of time and hyperopting :). 

### Steps to reproduce:

  1. Hyperopt a file for over 200+ days with 750 epochs.
  2. Watch it crash
 

### Relevant code exceptions or logs:

In case wondering, here is the memory error I'm getting: https://pastebin.com/J0Sai8Ym

**Comment by hroff-1902** [comment]
Okay, taking it.

**Comment by xmatthias** [comment]
well, i knew you had some thoughts about this before ... :)

**Comment by hroff-1902** [comment]
This splits into 2 almost completely different parts:
* saving results more frequently
* get `--continue` working

**Comment by Theagainmen** [comment]
> * saving results more frequently

Did it ever save results, except when it was finished? I know there are some pickle files saved but I can't read them. Maybe this already exist and I missed it, but I doubt it.

**Comment by hroff-1902** [comment]
I mean more frequently than just at the end of all epochs.
After, right, each best result found, and/or on every, say, 100 epochs... Not sure yet which approach is best and more robust.

**Comment by xmatthias** [comment]
configurable? so you can say every 100 ... or every 10 if you expect it to "most likely" fail ?

**Comment by xmatthias** [comment]
As `--continue` has been broken for a long time, i've removed it from hyperopt.

It may be introduced once the underlying functionality is available - but i don't see that happen anytime soon, so there's no point in keeping this option in freqtrade at this moment as it will confuse users.

**Comment by shroukkhan** [comment]
hi @hroff-1902 did we ever implement this one : https://github.com/freqtrade/freqtrade/issues/2464#issuecomment-549074563 .
Right now I am looking at freqtrade in conjunction with monigomani and having a way to store every evaluated epoch with good result during a hyperopt will be very useful

**Comment by xmatthias** [comment]
continuation of hyperopt has been removed (the `--continue` parameter), and is not possible (it never worked, even though the documentation said differently).
It's not something we're investigating further.

Hyperopt will however store all epochs (including full results and parameters) to disk, which are available with the commands `freqtrade hyperopt-list` (to see all results) and `freqtrade hyperopt-show -n epoch` (to see detailed results for one epoch).
You can also specify other (older) hyperopt files with `--hyperopt-file` - so for your requirement, there's no need for continuation to work or be implemented..
