### ISSUE TITLE
Freqtrade create 2 buys with same pair...

### ISSUE THREAD

**Issue by Escaliert** [freqtrade/freqtrade#2477]
i noticed that the bot takes two buys with same pair 
![image](https://user-images.githubusercontent.com/39638559/68229578-ce9e5a00-fff7-11e9-9cd8-97181a00c6dc.png)

if i activate  this...
![image](https://user-images.githubusercontent.com/39638559/68229485-a7e02380-fff7-11e9-9a02-13e635eee6a7.png)

... is this a feature or a bug ? :-)

**Comment by xmatthias** [comment]
definitely not a feature ...
i don't think it's to do with the buy-strategy though...

Are you able to access the database (via sqlbrowser or sqlite3 ) and run the following command and show us the output?
(first line is for sqlite3
```
.headers on 
select * from trades where id in (32, 33, 36, 37, 38, 39, 40, 31);
```

Also, still got the logs of the buys for these trades? that'll help us identify the problem.

**Comment by Escaliert** [comment]
uff so iam able to access the database via a sqlbrowser but where should i run this command?

**Comment by xmatthias** [comment]
then run `select * from trades where id in (32, 33, 36, 37, 38, 39, 40, 31);` only ...

sqlitebrowser has a "Execute SQL" tab ... insert this command and it should show you 8 rows ...

**Comment by Escaliert** [comment]
![image](https://user-images.githubusercontent.com/39638559/68239127-bd127d80-000a-11ea-860b-4433afb06338.png)
 like this?

**Comment by xmatthias** [comment]
Yes
That's very odd, never seen something like this before...

Have you got the logs from when these buys happen ...?

**Comment by Escaliert** [comment]
**i confirm that fix solved this problem**
