### ISSUE TITLE
Insufficient funds to create limit sell order on market .../BTC. Amount in database isn't deducted from fee

### ISSUE THREAD

**Issue by pepukrit** [freqtrade/freqtrade#2478]
## Step 1: Have you search for this issue before posting it?
Yes, I've searched for this issue. And, I follow all suggested instructions. 

## Step 2: Describe your environment

  * Operating system: Raspberry Pi
  * Python Version: Python 3.7.3
  * Branch: Develop
  * Last Commit ID: 581907305a462d0e8a7cf89d39b5337c53bcbee5
  
## Step 3: Describe the problem:
When the bot has ordered to close my trade (including typing /forcesell <number_id>), the system could not close the trade and then alert in terminal that
 
"freqtrade.DependencyException: Insufficient funds to create limit sell order on market LOOM/BTC.Tried to sell amount 1600.0 at rate 2.49e-06.Message: binance Account has insufficient balance for requested action." 

In addition, I have already fetched my git repository to be up on date and stay at develop branch according to suggestion on the previous issue and run the strategy again. This still could not fix the issue.

However, I notice that amount of trade in my database is not the same as the balance in my Binance account. It seems like the amount collected in my database are not deducted from fee. So, I need to correct it in my databasee.
by
> UPDATE trades
> SET amount=1598.4 WHERE id=5;

Here is total amount in my Binance
<img width="547" alt="Screen Shot 2562-11-05 at 19 40 34" src="https://user-images.githubusercontent.com/33507066/68233745-65880800-0032-11ea-803b-b7f48157df56.png">

And, force sell here should not work as I expect
![:forcesell-didn't-work](https://user-images.githubusercontent.com/33507066/68233824-90725c00-0032-11ea-92f0-b5ad545c11c5.png)

Here is total amount in my sqlite (It said that 1600)
![capture-from-sqlite3](https://user-images.githubusercontent.com/33507066/68233796-7e90b900-0032-11ea-8ad7-586febea11c0.png)

after update the correct total amount, the trade can be closed and forced sell
![:forcesell-worked](https://user-images.githubusercontent.com/33507066/68233872-a3852c00-0032-11ea-88ab-96ff77bc6042.png)

  * What did you expect to happen?
I expect that my amount of each trade in database should be automatically deducted from fee like the same amount in my Binance account so that the bot can automatically close the trade without insufficient fund. And, I do not need to update it every time the trade was opened.

I'm a very newbie in this field. Sorry if I make any mistakes. 
Thanks :)

**Comment by xmatthias** [comment]
what's your `order_types` look like?

also - we'll need the logs from the time of the buy in order to reproduce this... it's then (and a bit after that) where this reduction "should" take place.

**Comment by pepukrit** [comment]
Here is my order_types 
```
order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }
```
Okay, for logs, I will post it here asap. I'm not at home right now.

**Comment by pepukrit** [comment]
Hi!! @xmatthias
I'm not even that sure if this was a bug.
I remember that I added the below block of code in my configuration file.
```
,
    "pairlist": {
        "method": "VolumePairList",
        "config": {
            "number_assets": 50,
            "sort_key": "quoteVolume",
            "precision_filter": false
        }
    },
```
I do not guarantee this resulted in my bot not be able to sell.

At first, back to the previous comment that I said I was not at home now. However, I carried my MacBook to my uni. So, I ran my bot live (now without the above block of code) with the very low stake_amount: 0.001 or smth and used a strategy on 5m - 30m timeframes in order to quickly test if it would occur bug again. And, my bot did sell the trade correctly on my MacBook. Then, I realized the bug might only occur in my raspberry pi. So, I headed up to my home and reproduce everything within the raspberry pi. And bravo!!, I could force sell trade without any problem (even the bot didn't sell trades due to roi and sell signal). So, that's pretty much it.

I would like to close this issue now, and if I encounter some bugs on this issue in the future I will reopen this issue again.

**Comment by xmatthias** [comment]
one additional info

Especially if you're using BTC as stake-currency, i would reccomend enabling precision_filter. 

```json
,
    "pairlist": {
        "method": "VolumePairList",
        "config": {
            "number_assets": 50,
            "sort_key": "quoteVolume",
            "precision_filter": true
        }
    },
```

It'll filter out low value pairs - which can have this (and other) problems (if 1 pip is > 5% change, it's difficult to set a stoploss ...) 


Glad you could figure it out :+1:

**Comment by pepukrit** [comment]
@xmatthias Thanks man !! Hope you have an amazing day ☺️
