### ISSUE TITLE
Binance Invalid API-key, IP, or permissions for action.

### ISSUE THREAD

**Issue by Phrendo** [freqtrade/freqtrade#2480]
Ubuntu 18.04 Desktop
Python 3.6.8
ccxt==1.18.1306
Master
15938472032c5eae1b09edbed24151b6b63508cd
  
I have a fresh build of freqtrade. I have been running my strategy in dry_run true for weeks connected to Binance without a problem.  When i finally decide to go live, I start getting the following.  I even created a new key with all permissions and it's still doing the same thing, with and without IP restriction.

```
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.binance.com/api/v3/account?timestamp=1573006811133&recvWindow=5000&signature=<REMOVED>

freqtrade.TemporaryError: Could not get balance due to AuthenticationError. Message: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
```
  
I know this has been mentioned a few times before, but none of the previous solutions are helping me.  Let me know what else I need to supply to help.

**Comment by xmatthias** [comment]
well there can be 2 things - and the binance message is quite clear - the API-key is not correct:

* "key" and "secret" are not defined correctly / swapped / have a typo / have a leading or trailing space
* something is wrong with the API key - it can be expired, it can also have the wrong permissions (you say it does have the correct ones) - or it can have an IP restriction.

Unfortunately debugging and helping with these types of errors is very difficult, since 

a) we don't want you to post the config here without removing the keys first
b) we don't want to print the keys to screen to help YOU verify them - since they'll then be in the logs - which is a security risk again.

What helped others:
delete this API key - create a new one from scratch (you can't see the secret anymore now ...) - and be very careful when inserting the key/secret pair into the correct fields. (also make sure the location within the config is `{"exchange:{"key": "xxx", "secret": "yyy"}}`).

**Comment by Phrendo** [comment]
I found the problem.  The exchange must be listed as "binanceus" for us based accounts.  I didn't realize they were on different APIs.

**Comment by xmatthias** [comment]
unfortunately there are - the api itself is identical - but the url's are slightly different.

... it's actually different legal entities - probably for regulatory compliance.
there's also binanceje ... but i don't remember where that's from.

**Comment by markus27183** [comment]
I had to use   BaseAddress = "https://api.binance.com",

not   BaseAddress = "https://api.binance.com/api",

**Comment by Eli-J-Camara** [comment]
> I found the problem. The exchange must be listed as "binanceus" for us based accounts. I didn't realize they were on different APIs.

Can you elaborate on this? How do you list the exchange as "binanceus"?

**Comment by xmatthias** [comment]
the exchange-name for binance.us is `binanceus` - not `binance` - as such - that name needs to go into the configuration instead of binance.

**Comment by na81cho** [comment]
podrias dar mas detalle? donde dice binanceus, yo la manera que hice andar la api fue sacando la ip de la configuracion de binance.

**Comment by xmatthias** [comment]
Please stick to english for getting support (and don't revive old issues - but create new ones for new problems).

**Comment by andreat2009** [comment]
Where should I set the binanceus value instead of binance? I don't understand, is it an intrinsic problem of the cassandre libraries or should I set some specific property in the configuration.properties end. Thanks

**Comment by andreat2009** [comment]
> the exchange-name for binance.us is `binanceus` - not `binance` - as such - that name needs to go into the configuration instead of binance.

Where should I set the binanceus value instead of binance? I don't understand, is it an intrinsic problem of the cassandre libraries or should I set some specific property in the configuration.properties end. Thanks

**Comment by xmatthias** [comment]
@andreat2009 i strongly doubt that this is the correct repository - your namings suggest that you're not using freqtrade, but some other library/tool.

**Comment by pingaowang** [comment]
I added one line and it works:  'options': { 'defaultType': 'future', }

Now my code looks like: 

binance = ccxt.binance(
    {
        'apiKey': xxx,
        'secret': yyy,
        'enableRateLimit': True,
        'options': { 'defaultType': 'future', },
    }
)

I hope this can be helpful.

**Comment by xmatthias** [comment]
@pingaowang i don't see how your comment relates to this issue.

This is about freqtrade, not about using ccxt directly.
Aside from that, it's a solution, but not a solution to _this problem_ - i've therefore hidden your comment, as it's missleading and most likely wrong (aside from trying to revive a 4 (!) year old issue (therefore also locking this issue to avoid further pointless conversation here).
