### ISSUE TITLE
Insufficient funds to create buy order on 'stake_amount="unlimited" '

### ISSUE THREAD

**Issue by peeperspoopers** [freqtrade/freqtrade#2489]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04.3
  * Python Version: 3.6.8
  * Branch: Develop
  
## Step 3: Describe the problem:

I have set up my bot to run with 'stake_amount="unlimited" ', but it is running into an error while trying to open a trade. The error message reads: 

`"WARNING - Unable to create trade: Insufficient funds to create market buy order on market X. Tried to buy amount X at rate None.Message: binance Account has insufficient balance for requested action."`

The amount it tried to create a buy order for matches exactly to the amount I have available on Binance - I checked.

The first time the bot encountered a buy signal with 'stake_amount="unlimited" ' went well and the trade was executed but the following ones ran into the error described above.

I have tried setting 'amount_reserve_percent=0' but to no avail. Here's the bid/ask strategy part of my config file:

```
"bid_strategy": {
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy":{
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 9
```

Worth mentioning that I do not have any BNB available on my Binance account and BNB is blacklisted in my config.

Is there a way to resolve this issue? Could I change anything in the bid/ask part of my config file to work around this?
  
Thanks for your help
Kevin

**Comment by xmatthias** [comment]
Using `"stake_amount"="unlimited"` is heavily tied to "max_open_trades" (`available_stake / (max_open_trades - open_trades)` )...

so, what's your `"max_open_trades"` setting?

Also, setting 'amount_reserve_percent=0' will have no effect to this problem - this is a way to prevent buys with too low quantity - but has nothing to do with the "unlimited" calculation above.

**Comment by peeperspoopers** [comment]
My `max_open_trades` is set to 1

**Comment by peeperspoopers** [comment]
For further context, the bot has worked incredibly well with `stake amount` set to a certain amount and I have run over 250 live trades without problem.

**Comment by xmatthias** [comment]
I'm not certain this is "fixable" without #2458 (reserving a small amount of the stake-currency as "untradable").

The buy was a market order (visible in the logs above) - which means the API requires only the amount, and then sells at current market price.

The problem with that is that to get to the amount, we need "some" price.
Now we have your balance (let's say 100USD) - and we know the current price of the asset (let's assume 0.2891).

The calculation will therefore be `stake_amount / buy_limit_requested` - so 100 / 0.2891.

The amount resulting from this will be 345.9010722933241 - which - to be tradable, willl be truncated to 345.9 (depending on the asset, obviously).

Now assuming the price moves up slightly (from 0.2891 to 0.2892) exactly between "getting the price" and "placing the order".
the resulting necessary stake-amount - `345.9 * 0.2892 = 100.03428` - is 0.03USDT more than what the account holds - and therefore the market order becomes unplacable.

This won't happen with a limit order - since limit orders get both the Price and the amount - so we place the order at the calculated price - for which the calculated amount is "placeable".

**Comment by peeperspoopers** [comment]
So to try and fix this, I should set my 'buy' as 'limit'? Do I have to do this in my config or strategy file?

`order_types = {
        'buy': 'limit',
        'sell': 'market',
        'stoploss': 'market',
        'stoploss_on_exchange': False`

_Taken from my strategy file_

**Comment by peeperspoopers** [comment]
Assuming I set my buy order to 'limit', then could there by a situation where my order would not be filled?

**Comment by xmatthias** [comment]
you can set it in either config or strategy (config will owewrite strategy configurations).

Well obviously yes, it's a limit order - so if the market moves "away from your price", then the order may time out.

As said, #2458 should provide a solution to this by reserving 1% (or 0.5% ) of your account as "moving room" - however without it i don't see a quick solution (other than quickly hardcoding this modification ...)

**Comment by peeperspoopers** [comment]
Solution would then be to either set buy order as "limit" or giving it "amount_reserve_percent=0.01"?

**Comment by xmatthias** [comment]
`amount_reserve_percent` is named to create confusion (it's a ratio, not percent) and works in the "other" direction - protecting you from entering too small trades (which you then can't sell anymore, as they are below the tradable range).

assume you use "stake_amount=unlimited" ... and max_open_trades=10, and you use edge (which dynamically sizes positions based on a risk calculation).

Edge can then decide that the position for pair X has a high risk - so should be entered with a low position % - so it assigns 2% of your total account to this trade.

Depending on the asset, and your account size, this may be too small to guarantee that there is enough room in the "tradable range" for the pair to eventually apply a stoploss.
So the calculation is 

`min_stake_amount / (stoploss + amount_reserve_percent)`.

so this won't protect your case where the amount to buy is calculated as "too high" - but would protect the calculation from going too low (you could cause the same by using unlimted, 100 max_open_trades, on an account with 50 USDT (0.5USDT may be below the minimum tradable value - especially once you account to have enough "room" at the bottom for a stoploss).
