### ISSUE TITLE
Unable to run bot

### ISSUE THREAD

**Issue by acost-matt** [freqtrade/freqtrade#2493]
## Step 1: Yes I have and was unable to find a response for my specific problem. 

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Linux - Ubuntu 19.10
  * Python Version: Python 3.7.5rc1 (`python -V`)
  * CCXT version: pkg-resources==0.0.0 |  (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: ad2289c34cc938bc8b529f2676e71555fb216faa (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

I cannot get the bot to run and am not too sure why. I followed the installation guide on freqtrade.io for linux distributions as I am using Ununtu 19.10. I downloaded python, pip, git, and ta-lib, setup and activated my virtual environment, cloned the freqtrade git repository, and initialized my configuration. (Apologies if this is a very rudimentary issue, I have been working on this for a while though and can't seem to figure it out)

When I try running the bot using the command on the installation guide,  'freqtrade -c config.json'  I receive this error, 'freqtrade: command not found' .

I also tried an alternate command to start the bot given to me from a udemy course 'python3 ./freqtrade/main.py -c config.json'  , although unsurprisingly that did not work, I was given this error code...
'Traceback (most recent call last):
  File "./freqtrade/main.py", line 16, in <module>
    from freqtrade import OperationalException
ModuleNotFoundError: No module named 'freqtrade' '

![BotRunError](https://user-images.githubusercontent.com/56096762/68439837-f1f31180-017d-11ea-907b-7c0a9cc1858f.png)

### Steps to reproduce:

(my_env) acost3@acost3-VirtualBox:~/freqtrade$ freqtrade -c config.json
freqtrade: command not found

  
### Observed Results:

  * What happened? Does not run the bot
  * What did you expect to happen? I assumed it would

### Relevant code exceptions or logs:

Alternate command I tried which I had seen on Udemy along with the error it gave me...

(my_env) acost3@acost3-VirtualBox:~/freqtrade$ python3 ./freqtrade/main.py -c config.json
Traceback (most recent call last):
  File "./freqtrade/main.py", line 16, in <module>
    from freqtrade import OperationalException
ModuleNotFoundError: No module named 'freqtrade'

(I attached a photo of me trying both commands if this helps)

**Comment by hroff-1902** [comment]
> and initialized my configuration.

How did you do it?

**Comment by acost-matt** [comment]
I opened the file in atom, edited what I needed in the file (like kraken api and secret key/telegram information), then saved that file. I initially tried the steps in the installation guide on freqtrade.io .... cd freqtrade
cp config.json.example config.json
but that did not give me any response so I went the route of editing it in atom. Am I missing a step here?

**Comment by hroff-1902** [comment]
pls read this section in the docs: https://www.freqtrade.io/en/latest/installation/#quick-start

From your description, you missed the step which installs freqtrade in the system (`./setup.sh --install`). From your description, you cloned content from github, created the config and is trying to run the bot, without running the setup script or doing corresponding actions manually...

(Btw, Udemy is outdated, many old commands were changed and won't work, so your second approach shall not work.)

**Comment by acost-matt** [comment]
This time I downloaded everything necesary and used the ( ./setup.sh --install ) command. This seemed correct as this time the code generated the config file for me to edit. Although again I get the same error when running the bot with ( freqtrade -c config.json )

Attached is a picture. Thanks again for your help.
![BotRunError2](https://user-images.githubusercontent.com/56096762/68458539-e7556e00-01b7-11ea-8a77-77da01d9f459.png)

**Comment by hroff-1902** [comment]
* immediately change your exchange key, secrete, telegram token -- you've accidentally disclosed this publicly

* if you look at the beginning of the output in the screenshot, all stuff was installed into the `.env` venv. And you then activate another venv, which does not contain all this installed

**Comment by sanitariu** [comment]
Before running the bot you must activate virtual env like with similar command:
source .env/bin/activate;

**Comment by acost-matt** [comment]
Oh wow my fault, I immediately changed those. I tried running it in the .env virtual environment where all packages were downloaded and it is still giving me errors. I just can't figure out what I'm doing wrong here.
![BotRunError3](https://user-images.githubusercontent.com/56096762/68517235-92f3d200-023b-11ea-9c89-19f55b3656d8.png)

**Comment by hroff-1902** [comment]
wrong config

**Comment by acost-matt** [comment]
Why exactly is it the wrong config? config.json is the one that was generated when I executed the ./setup.sh --install command. If it is incorrect which config should I be using?

And for position 78 which file are you referring to?

**Comment by hroff-1902** [comment]
config.json, 

How's stake_amount is defined there?

**Comment by acost-matt** [comment]
That's the one I've been trying to run though so I'm not seeing why there is an error. 

stake_amount in the config.json file is defined as .01, stake_currency is BTC.

**Comment by hroff-1902** [comment]
`.01` is not valid json value for floats. Define it as `0.01`.

**Comment by acost-matt** [comment]
That worked! Thank you so much for all the help
