### ISSUE TITLE
Optimized Telegram Output 🤖

### ISSUE THREAD

**Issue by Escaliert** [freqtrade/freqtrade#2502]
**For all those guys who wants a better visual Telegram Output. Specially on Smartphones its very useful for a quick look into nofication-list.
Its possible to format the telegram Output in the "telegram.py" file like this...**

![image](https://user-images.githubusercontent.com/39638559/68532532-9449fb00-031e-11ea-86f9-306d8a67c581.png)
![Telegram_G3JmQx0SgZ](https://user-images.githubusercontent.com/39638559/68532396-ff92cd80-031c-11ea-82e1-3fe6042ce7ac.png)
![image](https://user-images.githubusercontent.com/39638559/68532398-09b4cc00-031d-11ea-8353-ccedabf4ca63.png)

**you only have to set your emotes from https://emojipedia.org/ in the "telegram.py"-file like this**

![image](https://user-images.githubusercontent.com/39638559/68532442-74fe9e00-031d-11ea-87be-c6c55cab537a.png)

**thats it 👍**

**_btw here is my example file_** 

[telegram.zip](https://github.com/freqtrade/freqtrade/files/3827523/telegram.zip)

ENJOY 🤖

**Comment by xmatthias** [comment]
Now, i personally would want to see sells in either Green or Red - depending on the outcome (positive / negative) ...
and buys in blue (or some neutral color ...).

Apart from that (which are visual details ...) - why is this an issue and not a PR, where you're proposing to change this so everyone can benefit? :smile:

**Comment by Theagainmen** [comment]
I indeed would like something mathias said. I quickly made this, there are probably better ways to do this tho, but it works :)
``` python
        elif msg['type'] == RPCMessageType.SELL_NOTIFICATION:
            msg['amount'] = round(msg['amount'], 8)
            msg['profit_percent'] = round(msg['profit_percent'] * 100, 2)

            message = ("*{exchange}:* Selling {pair}\n"
                       "*Rate:* `{limit:.8f}`\n"
                       "*Amount:* `{amount:.8f}`\n"
                       "*Open Rate:* `{open_rate:.8f}`\n"
                       "*Current Rate:* `{current_rate:.8f}`\n"
                       "*Sell Reason:* `{sell_reason}`\n").format(**msg)

            print (float(msg['profit_percent']))

            if float(msg['profit_percent']) > 0:
                message += ('💲*Profit:* `{profit_percent:.2f}%`').format(**msg)

            elif float(msg['profit_percent']) > 5:
                message += ('🚀*Profit:* `{profit_percent:.2f}%`').format(**msg)

            elif float(msg['profit_percent']) <= 0:
                message += ('❌*Profit:* `{profit_percent:.2f}%`').format(**msg)
```

**Comment by Theagainmen** [comment]
Tweaked it a little since the 💲 is grey in Telegram so you don't really see it. Now it's just some nice green emoji. For buying I added a neutral blue color. I also made all the emojis at the beginning of the message so you would see it immediately and also in the notifications. And it now also shows another emoji when it hits your stop loss value.

``` python
message = ("🔵 *{exchange}:* Buying {pair}\n"
                       "at rate `{limit:.8f}\n"
                       "({stake_amount:.6f} {stake_currency}").format(**msg)
```

``` python
            if float(msg['profit_percent']) > 0:
                message = ("✳ *{exchange}:* Selling {pair}\n").format(**msg)

            elif float(msg['profit_percent']) > 5:
                message = ("🚀 *{exchange}:* Selling {pair}\n").format(**msg)

            elif float(msg['profit_percent']) <= float(self._config['stoploss']):
                message = ("⚠ *{exchange}:* Selling {pair}\n").format(**msg)

            else:
                message = ("❌ *{exchange}:* Selling {pair}\n").format(**msg)

            message += ("*{exchange}:* Selling {pair}\n"
                       "*Rate:* `{limit:.8f}`\n"
                       "*Amount:* `{amount:.8f}`\n"
                       "*Open Rate:* `{open_rate:.8f}`\n"
                       "*Current Rate:* `{current_rate:.8f}`\n"
                       "*Sell Reason:* `{sell_reason}`\n").format(**msg)
```

**Comment by gaugau3000** [comment]
@Theagainmen hi, i don't understand the role of '?' in red below Current Rate. Could you explain ? Many tks.

**Comment by Theagainmen** [comment]
That part I'm not using, I'm only using the code snippet I sent here, I like the default message, but just with a nice colored emoji depending on the sell percentage :). I assume Escaliert made that for the 'Sell reason', but he made a new line there so it looks kinda weird. You should see it as this probably:
```❓ Sell reason: reason```

**Comment by Theagainmen** [comment]
Here's how mine look like:
![buy](https://user-images.githubusercontent.com/24569139/68614620-95675d80-04c1-11ea-8076-6679ab179932.png)
![sell profit](https://user-images.githubusercontent.com/24569139/68614597-87b1d800-04c1-11ea-8fc3-de2810d95125.png)
![stoploss](https://user-images.githubusercontent.com/24569139/68614670-b16aff00-04c1-11ea-9bfe-90a5bf11dd0b.png)


![sell loss](https://user-images.githubusercontent.com/24569139/68614596-87b1d800-04c1-11ea-95f5-1c01f553a314.png)

**Comment by hroff-1902** [comment]
@xmatthias 
Should we add emojies into the telegram messages as proposed (or other ones for some of the cases)? For me it looks attractive and increases usability...

**Comment by Escaliert** [comment]
> That part I'm not using, I'm only using the code snippet I sent here, I like the default message, but just with a nice colored emoji depending on the sell percentage :). I assume Escaliert made that for the 'Sell reason', but he made a new line there so it looks kinda weird. You should see it as this probably:
> `❓ Sell reason: reason`

well, i made my homework ;-)

![image](https://user-images.githubusercontent.com/39638559/72492788-cf851080-381e-11ea-86fe-1ec016242f03.png)

**Comment by xmatthias** [comment]
> Should we add emojies into the telegram messages as proposed (or other ones for some of the cases)? For me it looks attractive and increases usability...

I guess so - i like the version from this comment https://github.com/freqtrade/freqtrade/issues/2502#issuecomment-552580197 - which color-codes by profit / loss (i don't like having a sell for profit in red as in the original post...).

We'll probably need to pay attention to encoding - but python offers some good ways to not use these symbols directly (they can cause problems, as we've seen with the sum symbol in hyperopt).

**Comment by xmatthias** [comment]
For anyone thinking about implementing this - it would be great to use named unicode (`'\N{WARNING SIGN}'`) to allow the code to work on all platforms.
