### ISSUE TITLE
Default value but required parameters in configuration (source documentation) ?

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2532]
Hi,

I don't understand why in the [documentation -> configuration -> configuration-parameters](https://www.freqtrade.io/en/latest/configuration/#configuration-parameters) if parameters are required why there is a default value associated : we never can use the default value is this case ?

Many tks.

**Comment by xmatthias** [comment]
I think you're misreading the default as something it is not.

even if it's required, it can have a default value - which basically is the value set in the sample configurations.
It doesn't mean that it automatically "falls back" to this. 

while this could be one possibility - that's not how it's handled.

**Comment by hroff-1902** [comment]
That's confusing at least, I agree with @gaugau3000
