### ISSUE TITLE
Telegram doesn't work on Windows 10 (Ubuntu) in Russia

### ISSUE THREAD

**Issue by Ilya88Weber** [freqtrade/freqtrade#2534]
## Step 2: Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.6(`python -V`)
 
  * Branch: Master | Develop
  
  
## Step 3: Describe the problem:

When I try to run this command freqtrade trade -c config.json --strategy DefaultStrategy this error came up Fatal Error (Protocol Error)
Telegram runs from Russia. Does it related to VPN and because it has been working very unstable? 

![IMG_6901](https://user-images.githubusercontent.com/39600315/68934264-a8ff1680-0796-11ea-97a7-d3165aa18599.JPG)
![IMG_6902](https://user-images.githubusercontent.com/39600315/68934278-b0262480-0796-11ea-9828-827aa514cf7d.JPG)
![IMG_6903](https://user-images.githubusercontent.com/39600315/68934331-ccc25c80-0796-11ea-8335-653db7d72689.JPG)

**Comment by hroff-1902** [comment]
Same here,

Telegram in Russia only works for some providers. For instance, my home provider blocks it, but it's okay when I use mobile (Beeline) tethering. 

Try to use a VPN service (I personally use Seed4Me, there are promo-codes for it for 1-year free usage for testing their service).

**Comment by Ilya88Weber** [comment]
> 
> 
> Same here,
> 
> Telegram in Russia only works for some providers. For instance, my home provider blocks it, but it's okay when I use mobile (Beeline) tethering.
> 
> Try to use a VPN service (I personally use Seed4Me, there are promo-codes for it for 1-year free usage for testing their service).
> 
> Or use a VPS located in other countries (like AWS or DigitalOcean), they are also available for free for 10-12 months.

Thank you for reply,

my telegram works well (Desktop version and Android) however when I try to use this command it shows the error above. I am curios then if Telegram itself works good while this Telegram bot doesn't want to connect (or whatever) it still the network error as I understand.  

So if I set up Seed4Me on both Windows 10 and an Android smartphone then I no need to use any VPS? Sorry if this sounds a dumb question.  And which DigitalOcean VPS would you suggest? 

Highly appreciated.

**Comment by hroff-1902** [comment]
Telegram clients realize other means to bypass blocks and constantly updated with new methods, this all is not available for a app which simply uses Telegram API.

**Comment by hroff-1902** [comment]
Refer to Hardware Requirements to figure out which VPS machine is recommended: https://www.freqtrade.io/en/latest/#hardware-requirements

Actually, Freqtrade can even work on a small Raspberry PI. However, if you use a cheap VPS, it can be a pain to run hyperopt on it, so you'll also need to setup local environment for hyperoptimization if you'll use it.

**Comment by Ilya88Weber** [comment]
Perfect, thank you for your explanation.
First, I will try to use a VPN on android smartphone and let's see if it works, I will keep updating.

**Comment by hroff-1902** [comment]
I did not tell you that using tethering via smartphone is an option for the bot -- it's a definitely a bad idea, even in dry-run mode. I only told that *Telegram* itself is blocked by some providers and works itself with others, including mobile ones.

It's bad idea, only as a testing option for short time to see how it works...

**Comment by Ilya88Weber** [comment]
> 
> 
> I did not tell you that using tethering via smartphone is an option for the bot -- it's a definitely a bad idea, even in dry-run mode. I only told that _Telegram_ itself is blocked by some providers and works itself with others, including mobile ones.
> 
> It's bad idea, only as a testing option for short time to see how it works...



> 
> 
> I did not tell you that using tethering via smartphone is an option for the bot -- it's a definitely a bad idea, even in dry-run mode. I only told that _Telegram_ itself is blocked by some providers and works itself with others, including mobile ones.
> 
> It's bad idea, only as a testing option for short time to see how it works...

Well, perhaps I didn't express myself correctly 
As I understand I can use a VPN Speed4Me both on Windows and smartphone instead a VPS.

**Comment by hroff-1902** [comment]
Sees4Me is just one of miriads of VPS services available, you can use any of them. That was just an example of my personal usage (no hidden adverts in the comments 😄 )

Yes, if you connect via VPS (using location that do not have similar limitations), it should fix the connectivity problem to Telegram API servers.

However, with VPS approach used, it will also connect to the exchange via same VPS, this can add extra unwanted latency, which can be high and inacceptable, especially for lower timeframes. The best case is a VPN or a dedicated host on a location near the exchange site.

**Comment by Ilya88Weber** [comment]
Well explained hroff! I strictly follow your instructions! :) 
I am not very good at expressing myself in a simple way and have no proper knowledge regardless this topic yet so the best choice is to follow the leader, I guess (less harm). I gonna try them all and will see which one will work best for me.

**Comment by hroff-1902** [comment]
You can also join our Slack channels (see the docs for the invitation link) and ask me in the Russian language, if this better suites you (but, pls, not in the main channel, the '#random' can be used for this, I guess)...

**Comment by Ilya88Weber** [comment]
Oh, great! I will join the channel and will find you there!
Thank you once again

**Comment by hroff-1902** [comment]
closing it since the issue was answered.
