### ISSUE TITLE
Proper way to add pairs on config.json

### ISSUE THREAD

**Issue by hanswayne23** [freqtrade/freqtrade#2537]
Ubuntu 18.04.3 LTS

Kindly i would like to know what is the proper way to add more coins /pairs?

i followed directions on this page  https://www.freqtrade.io/en/latest/data-download/. at first it was ok. but when i add coins/pairs on config.json and run freqtrade download-data i got this error already? i did add coins/pairs to try to simulate or backtest to see more results on more coins.

Really need help on this one.

Thanks.

![download data error1](https://user-images.githubusercontent.com/55561332/69004323-7dbe2800-094c-11ea-94a0-52235ffbec2e.jpg)

**Comment by hroff-1902** [comment]
why did not you fill the issue template?

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)

**Comment by hroff-1902** [comment]
In short: just update your installation.

**Comment by hroff-1902** [comment]
what's in the config near character with position 1351? How do you add the pairs?

**Comment by xmatthias** [comment]
well the error is pretty clear - "missing a comma or ]" ... 

best use an editor which can do syntax highlighting for json (vscode, vim, ...) - go to that line - and it should highlight the area around the error.

**Comment by hanswayne23** [comment]
my apologies i got worried when is saw those errors that is why i forgot to fill up the form.
Ubuntu 18.04.3 LTS
Python 3.6.8
CCXT version 1.3.6 - if im not mistaken
Develop - 58190730
Last Commit ID - 581907305a7cf89d39b5337c53bcbee5

what's in the config near character with position 1351? on this question i really dont know the answer?

I add the pairs:
1. use gedit the add the coins/pairs one by one in the whitelist

Default pairs when i install freqtrade:
ETH,LTC,ETC,DASH,ZEC,XLM,TRX,ADA,XMR

Pairs that i added:
POWR,BNB,QLC,KMD,WTC,XRP,EOS,XVG,NEO,LINK,ONT,XEM,VET,ICX

@xmatthias 

oh ok. i used gedit and atom to edit json file of freqtrade. 

At first when i run freqtrade download-data and run freqtrade backtesting their is no problem.

When i add pairs at config.json thats when the error happen.

Kindly i would like to know if i need to study deeper python programming to avoid this kind of problems?

Thanks.

**Comment by hroff-1902** [comment]
it's not about python programming it's about values in the configuration file.

Attach the config (do not forget to remove tokens/secrets)

**Comment by xmatthias** [comment]
atom should do syntaxhighlighting of json too (not sure about gedit - never used that).

As @hroff-1902 said, it's not about python (not at all, actually) -but about json.
probably the last line of the pairs list which has the error, most likely you're missing the `],`...

**Comment by hanswayne23** [comment]
Ok.

Please see attached config file.

What i observed is when i added the new pairs the letters are in color white compare to others that is color green. Is that a sign that there is a broken link?

kindly need help on this one.

Thanks,

![config1](https://user-images.githubusercontent.com/55561332/69015631-ce776480-09d0-11ea-947d-583c8a23b444.jpg)
![config2](https://user-images.githubusercontent.com/55561332/69015632-ce776480-09d0-11ea-86f3-b45b82227cfa.jpg)
![config3](https://user-images.githubusercontent.com/55561332/69015634-cf0ffb00-09d0-11ea-9fb9-5cb1039cc9d0.jpg)
![config4](https://user-images.githubusercontent.com/55561332/69015636-cfa89180-09d0-11ea-9d16-ca27f622967e.jpg)

**Comment by hroff-1902** [comment]
add commas between pairs

**Comment by xmatthias** [comment]
starting with line 48, you're missing commas, best conclude every line with a colon (,)..

so your line 48 looks like `"XMR/BTC",` - instead of `"XMR/BTC"`

**Comment by hanswayne23** [comment]
Its working already. Thank you for your help.

![pair](https://user-images.githubusercontent.com/55561332/69123865-6a8e9200-0add-11ea-8a64-56bc7d9a6c34.jpg)
![running now1](https://user-images.githubusercontent.com/55561332/69123866-6b272880-0add-11ea-8e3e-0144019083bd.jpg)

By the way i would like to ask permission if i can post questions here for backtesting, hyperopt and other installation problems or i need to create another thread for this?

My apology for being a newbie.

Thanks.

**Comment by xmatthias** [comment]
yes you can - but mixing questions will lead to chaos ... 

to get quicker answers, it's probably better to join the [slack channel](https://join.slack.com/t/highfrequencybot/shared_invite/enQtNjU5ODcwNjI1MDU3LTU1MTgxMjkzNmYxNWE1MDEzYzQ3YmU4N2MwZjUyNjJjODRkMDVkNjg4YTAyZGYzYzlhOTZiMTE4ZjQ4YzM0OGE) - that's a "more interactive" way and others will more likely jump in to help.
