### ISSUE TITLE
problem with telegram on new install of freqtrade

### ISSUE THREAD

**Issue by hanswayne23** [freqtrade/freqtrade#2554]
## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04.3 LTS
  * Python Version: 3.6.8 (`python -V`)
  * CCXT version: 1.3.6(`pip freeze | grep ccxt`)
  * Branch: Master | Develop 09b302ab
  * Last Commit ID: 09b302abf74fd8249318d2a3fa6ed4616235b9b9

  
## Step 3: Describe the problem:

i installed new freqtrade and there's a problem with telegram.

There's no notifications already on telegram once i run freqtrade 

My step by step installation of freqtrade

sudo apt update

 

sudo apt install python3-pip

sudo apt install git 

 

git clone https://github.com/freqtrade/freqtrade.git

 

cd freqtrade

 

sudo apt-get install python3-venv

 

bash ./setup.sh --install

source .env/bin/activate

pip3 install -e .

Kindly need help on this one

![new install freq1](https://user-images.githubusercontent.com/55561332/69214983-60cf6200-0ba3-11ea-8eba-d7bea7b5ab7c.png)
![new install freq2](https://user-images.githubusercontent.com/55561332/69214984-60cf6200-0ba3-11ea-8ab4-3fc32291fddd.png)

**Comment by hroff-1902** [comment]
Telegram is disabled by default, enable it in the config:
```
    "telegram": {
        "enabled": true,
...
    },
```
