### ISSUE TITLE
Bitfinex - Outdated history live/dry

### ISSUE THREAD

**Issue by sanitariu** [freqtrade/freqtrade#2556]
## Step 1: Have you search for this issue before posting it?
Yes i searched it may be duplicate but i am not sure

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment
os - gentoo linux
pyton - Python 3.7.5
ccxt - ccxt==1.19.54
branch - develop
commit - 09b302abf74fd8249318d2a3fa6ed4616235b9b9
  
## Step 3: Describe the problem:

Trading live or dry at bitfinex gives incorrect outdated history for all pairs.
Downloading and backtesting works fine on that exchange.
System clock is okay because i am running ntpdate from crontab each 30 minutes.
Pairs i am trading have enough volume.
My ticker interval is 1h. I tested also 5 minutes and others without any success.
I tested at least 3 strategies including sample one and still no result.

Log file shows the following
```
2019-11-20 17:17:34,521 - freqtrade.data.converter - INFO - Missing data fillup for BTC/USD: before: 99 - after: 101
2019-11-20 17:17:34,664 - freqtrade.strategy.interface - WARNING - Outdated history for pair BTC/USD. Last tick is 737 minutes old
2019-11-20 17:18:14,530 - freqtrade.data.converter - INFO - Missing data fillup for BTC/USD: before: 99 - after: 101
2019-11-20 17:18:14,686 - freqtrade.strategy.interface - WARNING - Outdated history for pair BTC/USD. Last tick is 738 minutes old
2019-11-20 17:18:54,507 - freqtrade.data.converter - INFO - Missing data fillup for BTC/USD: before: 99 - after: 101
2019-11-20 17:18:54,642 - freqtrade.strategy.interface - WARNING - Outdated history for pair BTC/USD. Last tick is 738 minutes old
```
and so on .....

While i was extracting the log file i noticed this too which may be separate problem because it catch in bittrex and seems like it happens while i do /reload_conf during testing. Will paste it here
just for information. If you think it is irrelevant you can edit my post.
```
2019-11-20 17:20:54,952 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=13080
Exception ignored in: <function Exchange.__del__ at 0x7f5c35804440>
Traceback (most recent call last):
  File "/home/dri/miner/freqtrade/freqtrade/exchange/exchange.py", line 134, in __del__
    asyncio.get_event_loop().run_until_complete(self._api_async.close())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 566, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 521, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2019-11-20 17:21:19,414 - ccxt.base.exchange - WARNING - bitfinex requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
2019-11-20 17:21:19,415 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5c37a08b10>
2019-11-20 17:21:19,416 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f5c50354830>, 1141873.981506697)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f5c34ac38d0>
```
I hope my post not going with big letters again !

**Comment by xmatthias** [comment]
> I hope my post not going with big letters again !

I've fixed formatting in your issue ... you should wrap log output / code blocks in tripple \` (ticks -  \`\`\` ).
You can have a look at how i did it if you edit your post.

The asyncio issue is not related to the bitfinex issue - but seems to come from improper closing / reopening of the loop... 



Letme repeat (for the record) what i said in the old issue (a bit more in detail, too).
Please use the code from [the developer docs](https://www.freqtrade.io/en/latest/developer/#incomplete-candles) to verify the data returned from bitfinex (adapt timeframes and exchange to your needs).


Things to look out for:
* is the last candle really the last candle (compare with UI - and date (dates should be in UTC)
* is the last candle a partial candle (does it change intra-candle)
* ...

**Comment by sanitariu** [comment]
Playing with dev docs i think this is cxxt bug.
If using bitfinex as exchange i have the following

(.env) dri@dri ~/miner/freqtrade $ python test.py
101   2013-04-05 04:00:00+00:00
Name: date, dtype: datetime64[ns, UTC]
2019-11-20 16:20:18.758552

Using bitfinex2 gives more correct information but it may not be well supported ?
(.env) dri@dri ~/miner/freqtrade $ python test.py
99   2019-11-20 16:00:00+00:00
Name: date, dtype: datetime64[ns, UTC]
2019-11-20 16:19:16.299625

I am using the example from your docs page. Timeframe is 1 hour and pair is BTC/USD.

Do i have to report the bug if it is bug at all to cxxt group ?

**Comment by sanitariu** [comment]
Seems like using bitfinex2 is better... i am going to test all with API2

**Comment by xmatthias** [comment]
well usually "v2" should be more uptodate / stable...

having used neither of the 2, i would instinctively go with the (seemingly newer) bitfinex2 (especially since it's parent-class is bitfinex) ... - so bitfinex2 is an extension of bitfinex ...

**Comment by sanitariu** [comment]
Yes thanks. I am already downloading data with bitfinex2 and will do backtesting + plotting. If everything is ok i will go live testing....

**Comment by hroff-1902** [comment]
maybe move `bitfinex` to bad exchanges with a message pointing to use `bitfinex2`, as it was done for `hitbtc`/`hitbtc2`?

**Comment by xmatthias** [comment]
potentially  yes ... but let's "outwait" some more testing before doing that ;)

**Comment by xmatthias** [comment]
@sanitariu how is bitfinex2 doing? any more problems with that or did you move on to other exchanges?

**Comment by sanitariu** [comment]
Hello bot is working from over 30 days but still no trade happened. Eveything seems correct so it may be my strategy.....
I think we should close this.

**Comment by kiandp** [comment]
Hi
I am encountering to the same problem as you described and when i ran the code to check data from binance is showing 2013 which is really irrelevant.(outdated history and like 900 minutes old and so on :( )
Can you please tell me how did you fix this problem?
I read all your conversations that you moved to bitfinex2.
How can i get api for bitfinex2?!
Thanks

**Comment by xmatthias** [comment]
@kiandp bitfinex is not supported, and as far as i know, has multiple problems, so should be assume to be non-working.

Also, please don't highjack year-old threads - this will notify all people involved in this issue, and i'm therefore locking this issue now to avoid notifying everyone again and again.
