### ISSUE TITLE
freqtrade list-pairs --> no result

### ISSUE THREAD

**Issue by antoniosap** [freqtrade/freqtrade#2562]
* Operating system: ubuntu 16.04 LTS
  * Python Version: Python 3.6.8 (`python -V`)
  * CCXT version: ccxt==1.18.1260 (`pip freeze | grep ccxt`)
  * Branch: Develop
  * Last Commit ID: a5f35e8ac1ce8787e3c595321f51ec64d33e34fe (`git log --format="%H" -n 1`)
  
  ```
freqtrade list-pairs
usage: freqtrade [-h] [-v] [--logfile FILE] [-V] [-c PATH] [-d PATH]
                 [--userdir PATH] [-s NAME] [--strategy-path PATH]
                 [--db-url PATH] [--sd-notify]
                 {backtesting,edge,hyperopt,create-userdir,list-exchanges,download-data,plot-dataframe,plot-profit}
                 ...
freqtrade: error: argument subparser: invalid choice: 'list-pairs' (choose from 'backtesting', 'edge', 'hyperopt', 'create-userdir', 'list-exchanges', 'download-data', 'plot-dataframe', 'plot-profit')

  ```

**Comment by xmatthias** [comment]
it is not clear to me what version you're running - but a5f35e8ac1ce8787e3c595321f51ec64d33e34fe is not a commit in this repository...

please post the output of `git remote -v` (i hope this gives us some insight into where this version / commit came from)...

**Comment by antoniosap** [comment]
```
origin  https://github.com/freqtrade/freqtrade.git (fetch)
origin  https://github.com/freqtrade/freqtrade.git (push)

```
![Schermata del 2019-11-21 17-52-41](https://user-images.githubusercontent.com/2323966/69358942-fba16c80-0c87-11ea-96ee-44a1e60bac0b.png)

**Comment by xmatthias** [comment]
hmm, this version does (or should) include list-pairs.

please run ` pip show freqtrade` - the output of "location" should point to the git folder (the folder you did check this out).

If it's not and it shows something containing `site-packages` - you'll need to run `python setup.py develop` to install it in "linked" mode, so the latest version is actually used.

Note: all commands listed here need to be ran with the virtualenv activated.

**Comment by antoniosap** [comment]
now is ok. thanks.
