### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by samrk2** [freqtrade/freqtrade#2573]
(.env) root@SAMARTH:~/freqtrade# python3.7 ./freqtrade/main.py -c config.json
Traceback (most recent call last):
  File "./freqtrade/main.py", line 11, in <module>
    from freqtrade import OperationalException
ModuleNotFoundError: No module named 'freqtrade'

**Comment by hroff-1902** [comment]
Seems you are using the Freqtrade version from the Udemy course -- it's outdated and no longer supported. Install the current Freqtrade from the master or develop branch.

**Comment by xmatthias** [comment]
apart from that - seems that freqtrade is not installed in the virtual envrionment.
Best run `python3.7 setup.py develop` with the activated virtual environment.
