### ISSUE TITLE
'trade' command unkown

### ISSUE THREAD

**Issue by OtenMoten** [freqtrade/freqtrade#2585]
## My environment

  * Operating system: Ubuntu 18.04 VM
  * Python Version: 3.7 (`python -V`)
  * Branch: Master
  
## The problem

Hello dear Community,

after installing the new version of Freqtrade with the [official tutorial ](https://www.freqtrade.io/en/latest/installation/) it does not work anymore.

`freqtrade trade -c config.json`
results in
`freqtrade: error: argument subparser: invalid choice: 'trade' (choose from 'backtesting', 'edge', 'hyperopt', 'create-userdir', 'list-exchanges', 'list-timeframes', 'list-markets', 'list-pairs', 'download-data', 'plot-dataframe', 'plot-profit')`

Does anyone noticed the same issue?

PS: The usual command 
`python3.7 freqtrade/main.py -c config_bb_cci_ema.json -s BB_CCI_EMA `
works fine.

The offical tutorial suggest to enter this command:
`freqtrade trade -c config.json`
but it does not work.

Kind regards
Oten

**Comment by hroff-1902** [comment]
You are using freqtrade from the master branch but are reading the docs for the develop branch.
The trade command is not yest in the master, will be in the next version.
The docs for the master is here (use selector at the bottom right): https://www.freqtrade.io/en/master/bot-usage/

**Comment by OtenMoten** [comment]
Hello Mr. @hroff-1902 

thanks for your kind response.

**Comment by xmatthias** [comment]
Note for future readers:
the documentation has a "floating bar" at the right bottom corner allowing to switch to different versions of the documentation - from there you can get to the matching documentation for "master" or any previous version, should this be desired.
