### ISSUE TITLE
Binance - ERROR - Time in force

### ISSUE THREAD

**Issue by OtenMoten** [freqtrade/freqtrade#2586]
## Describe your environment

  * Operating system: Ubuntu 18.04 VM
  * Python Version: 3.7 (`python -V`)
  * Branch: Master
  
## Describe the problem:

Hello community,

I used the latest version and got this error:

`2019-11-30 09:52:32,084 - freqtrade - ERROR - Time in force policies are not supported for Binance yet.`

Optional order type mapping
   ```
 order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'limit',
        'stoploss_on_exchange': False
    }
```

Optional time in force for orders
```
order_time_in_force = {
        'buy': 'gtc',
        'stoploss': 'limit',
        'sell': 'gtc',
    }
```

**Comment by xmatthias** [comment]
Please post the exact commit version too (as requested in the template).

  * Last Commit ID: _____ (`git log --format="%H" -n 1`)

I'd also like to see the whole startup log up to this error.

Also, please show us the "exchange" section of your configuration (don't forget to remove api keys before posting).

**Comment by xmatthias** [comment]
After reading the above again - `'stoploss': 'limit',` is not a valid `order_time_in_force`.

valid options for `order_time_in_force` are `['gtc', 'fok', 'ioc']`.
"limit" is an order type, not a time in force type. Remove that line so it looks as follows and it should work for binance.

```
order_time_in_force = {
        'buy': 'gtc',
        'stoploss': 'limit',
        'sell': 'gtc',
    }
```

**Comment by hroff-1902** [comment]
@OtenMoten is it okay now?

**Comment by hroff-1902** [comment]
Closing it as it was a configuration misunderstanding problem and suggestions were issued.
Feel free to reopen it if you think it's relevant.
