### ISSUE TITLE
Telegram Channel

### ISSUE THREAD

**Issue by OtenMoten** [freqtrade/freqtrade#2587]
## Have you search for this issue before posting it?

https://github.com/GabrielRF/telegram-id/blob/master/README.md

## Describe your environment

  * Operating system: Ubuntu 18.04 VM
  * Python Version: 3.7 (`python -V`)
  * Branch: Master
  
## Describe the problem
The bot post messages to all groups, that works fine.

I got the chat_id from my Telegram-channel from [](https://api.telegram.org/bot55555:AAAAAA/getUpdates) and entered in `config.json`. It does not work.

Error message:
`2019-11-30 10:22:12,396 - freqtrade.rpc.telegram - WARNING - Telegram NetworkError: Inline keyboard expected! Trying one more time.`
`2019-11-30 10:22:12,413 - freqtrade.rpc.telegram - WARNING - TelegramError: Inline keyboard expected! Giving up on that message.
`

Anybody noticed same issue?

Kind regards
OtenMoten

**Comment by xmatthias** [comment]
No, this works fine when configured correctly. I suspect you're missing either the chat_id or the token from your configuration (or have a typo in one of the 2 keys).
Please make sure to configure both "token" and "chat_id" with the appropriate tokens.

Note: `chat_id` is tied to your account and usually 8-10 numbers and will only change if you change your telegram account) - while `token` is dedicated to the telegram bot you created according to the [documentation](https://www.freqtrade.io/en/latest/telegram-usage/#1-create-your-telegram-bot) and is a longer string (>40 characters).

**Comment by hroff-1902** [comment]
Closing it since no additional info was provided, this seems to be due to misconfiguration in the user's config (as explained above).

Feel free to reopen.

**Comment by dimm0** [comment]
Does bot supposed to work in a group or channel, instead of directly speaking to a user? What if I want two users to control the bot?

**Comment by snussik** [comment]
for those, who faces the same issue, check that "chat": {"type" : "**group**"}" and your bot its member.

**Comment by vallemar** [comment]
I can send messages to my telegram group with my bot making an http call, however with the same parameters I am getting this error
EDIT: right, he had created a channel instead of a `group`. When I have changed to a `group` everything has worked
