### ISSUE TITLE
VolumePairList not working

### ISSUE THREAD

**Issue by OtenMoten** [freqtrade/freqtrade#2588]
## Have you search for this issue before posting it?

https://www.freqtrade.io/en/latest/configuration/#available-pairlists

## Describe your environment

  * Operating system: Ubuntu 18.04 VM
  * Python Version: 3.7 (`python -V`)
  * Branch: Master
  
## Describe the problem

*Explain the problem you have encountered*

Hello dear Community,

this is my config:

```
{
    "max_open_trades": 15,
    "stake_currency": "BTC",
    "stake_amount": 1.0,
    "fiat_display_currency": "USD",
    "ticker_interval" : "5m",
    "dry_run": true,
    "trailing_stop": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy":{
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 9,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
    "exchange": {
        "name": "binance",
        "key": "[xxx]",
        "secret": "[xxx]",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 500
        },
        "pair_whitelist": [],
        "pair_blacklist": ["DOGE/BTC"]
    },
    "pairlists": [{
        "method": "VolumePairList",
        "number_assets": 200,
        "sort_key": "quoteVolume",
        "refresh_period": 1800,
        },
        {"method": "PrecisionFilter"},
        {"method": "PriceFilter", "low_price_ratio": 0.01}
        ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "capital_available_percentage": 0.5,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "[xxx]",
        "chat_id": "[xxx]"
    },
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```

When the bot starts the following message is displayed:

`freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'Searching for BTC pairs to buy and sell based on StaticPairList: []'}`

The bot does not use a volume pair list.

**Comment by hroff-1902** [comment]
Yes, it does not work in the master branch since it's not yet merged in the master, the current master version was created before all those changes.

**Comment by OtenMoten** [comment]
Hello @hroff-1902,

I though that the Master is the latest release.

Which version I need to install to use all those wonderful settings?

**Comment by hroff-1902** [comment]
> Hello @hroff-1902,
> 
> I though that the Master is the latest release.
> 
> Which version I need to install to use all those wonderful settings?

Master is baked ~once month. As you can see in the logs (or with the `-V` option, which prints the version) current master is 2019.10, which means it contains changes made in October.
The latest release is available in the develop branch.

**Comment by hroff-1902** [comment]
How to switch to develop: https://www.freqtrade.io/en/latest/installation/#quick-start

**Comment by hroff-1902** [comment]
New master is to be made in a few days, it's time for it.

**Comment by OtenMoten** [comment]
Oh well, I never thought that these cool changes was made in the last month.
Hmn ok, then I created more issues than needed today. 

Now I'm aware, thanks for the notes. I will use the develop branch further.

Kind regards and thanks for answering
