### ISSUE TITLE
logs output in a json format 

### ISSUE THREAD

**Issue by wiseflat** [freqtrade/freqtrade#2591]
Hi, 

Is it possible to get all logs output in a json format ?

**Comment by hroff-1902** [comment]
yes, via systemd and journalctl with `-o json` option

**Comment by xmatthias** [comment]
or via [docker JSON File logging](https://docs.docker.com/config/containers/logging/json-file/)

**Comment by wiseflat** [comment]
Hi, Thank you guys but it doesn't fit my needs :-( 

journalctl doesn't parse properly the message : 

This is a journalctl -u freqtrade (with json output)
```
{ "__CURSOR" : "s=3c5c413cd97242428d75d61dfee9dfa8;i=350d;b=ca8afccddc3043218b4adfcb54a4fab2;m=41ec6e9094a;t=59842c23cea25;x=b58512e9b725a46d", "__REALTIME_TIMESTAMP" : "1574787377588773", "__MONOTONIC_TIMESTAMP" : "4530232691018", "_BOOT_ID" : "ca8afccddc3043218b4adfcb54a4fab2", "_TRANSPORT" : "stdout", "_STREAM_ID" : "5ffaf4eebca74b8e91bec41015e567ba", "PRIORITY" : "6", "SYSLOG_FACILITY" : "3", "SYSLOG_IDENTIFIER" : "python3", "_PID" : "26112", "_UID" : "1001", "_GID" : "1001", "_COMM" : "python3", "_EXE" : "/usr/bin/python3.6", "_CMDLINE" : "/opt/freqtrade/.env/bin/python3 /opt/freqtrade/bin/freqtrade", "_CAP_EFFECTIVE" : "0", "_SELINUX_CONTEXT" : "unconfined\n", "_SYSTEMD_CGROUP" : "/system.slice/freqtrade.service", "_SYSTEMD_UNIT" : "freqtrade.service", "_SYSTEMD_SLICE" : "system.slice", "_SYSTEMD_INVOCATION_ID" : "767b601c56824e10a3bd4336dfdd4577", "_MACHINE_ID" : "5805f3b93af9457ea8a95e9973d70d84", "_HOSTNAME" : "freqtrade-0", "MESSAGE" : "2019-11-26 16:56:17,588 - freqtrade.pairlist.IPairList - INFO - Ignoring BTCB/BTC from whitelist. Market is not active." }
```

As you can see, MESSAGE is still not parsed, output MESSAGE value is still a string...


This is a line from journalctl (or my log file)
```
2019-11-26 16:56:17,587 - freqtrade.pairlist.IPairList - INFO - Ignoring BCN/BTC from whitelist. Market is not active.
```

I thought about something like that :
{
    "timestamp": "2019-11-26 16:56:17,587",
    "info1": "freqtrade.pairlist.IPairList",
    "status": "INFO",
    "message": "Ignoring BCN/BTC from whitelist. Market is not active.",   
}

**Comment by xmatthias** [comment]
what's the usecase? maybe there is a simple solution ... ?

**Comment by hroff-1902** [comment]
it does not work this way with journald, other parsers should be used as a medium, read more details for example here: https://nbsoftsolutions.com/blog/introduction-to-journald-and-structured-logging

**Comment by wiseflat** [comment]
I would like to send logs to an external solution (like graylog for instance). That's why, a native freqtrade json output will be great to parse the entire message.

**Comment by xmatthias** [comment]
well i've never used graylog, but the ELK stack, has the logstash component, which makes it simple to parse the output from log messages. I assume that any other solution has a similar component, allowing to easily parse the logs. Since our logs are very predictable, it's very easy to write such a log parser.

Please also check out the docker solution - which DOES support natively forwarding logs to external solution.

Personally, I don't think that outputting logs in the destination format will be a good idea, since everyone will have different requirements from a format perspective, so it's best to leave the parsing to the required destination format to the receiving system (which i'm sure has this component builtin).

**Comment by wiseflat** [comment]
Ok @xmatthias, no pb. 
I am not a python developer but I will try to make a pull request if I manage to make a new python definition, based on this file :  https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/loggers.py

If it works, I'll share it :-)

**Comment by xmatthias** [comment]
Best look at #2418 how other log methods are implemented.

However, I would suggest to wait for #2418 (should be ready as soon as i have time to review) - which will add support for logging to syslog servers - which is something graylog does support (see link above).

**Comment by hroff-1902** [comment]
yeah, @wiseflat you should better start from #2418 (it's already merged into the develop branch, pls update your installation). The description is here: https://www.freqtrade.io/en/latest/advanced-setup/#advanced-logging, pls review it.

**Comment by hroff-1902** [comment]
Closing it as the question was answered and various info provided.

@wiseflat pls feel free to post here more info on integration with graylog or other logging software if you have any tips or results.
