### ISSUE TITLE
No Pairlist defined! 

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2592]
I do not know why I am getting 2019-11-30 00:35:01,196 - freqtrade - ERROR - No Pairlist defined!  even though the pairlist is defined in the config file. it is working with hyperopt and backtesting but not with other modules

ubuntu 
Python 3
ccxt==1.19.54
Develop
 cab748588cdb5dfa9f89fe917b70235e32f6e373

**Comment by hroff-1902** [comment]
pls fill the fields with versions,
and the config (remove keys and other secrets)

**Comment by xmatthias** [comment]
Based on the commit, i think that it's impacted by #2565.

Please update to the latest develop and retry, thanks.

**Comment by hroff-1902** [comment]
From config set in Slack:

pairlists is to be one level up, not in the exchange branch of settings.

**Comment by gitgitgat** [comment]
> Based on the commit, i think that it's been fixed in #2565 - which was merged 1 day after your pointed out commit.
> 
> Please update to the latest develop and retry, thanks.

okay thanks
