### ISSUE TITLE
db-url defaults during dryrun

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2600]
In the [docker doc](https://www.freqtrade.io/en/latest/docker/#create-your-database-file) the doc recommend to create the database in live with  ` touch tradesv3.sqlite`, and in dryrun with`touch tradesv3.dryrun.sqlite`.

But then in the note below it says :

> db-url defaults to sqlite:///tradesv3.sqlite but it defaults to sqlite:// if dry_run=True is being used. To override this behaviour use a custom db-url value: i.e.: --db-url sqlite:///tradesv3.dryrun.sqlite

1/ not sure end user know what _sqlite://_ means : create in memory or create a default file, but we don't know his name ?
2/ When we say the end-user to create the files `touch tradesv3.dryrun.sqlite` for dry-run then the default should be _sqlite:///tradesv3.dryrun.sqlite_ and not _sqlite://_ .If we give recommandations for naming the databases in the doc, then we should take this in account for default. And It can be seen like a convention over configuration approach.

Have a nice day.

**Comment by hroff-1902** [comment]
There is nothing to discuss 😄 , this badly covered in the docs, should be improved...

**Comment by xmatthias** [comment]
Agreed, i also don't like the approach to use in-memory as default for dry-run - I expect users to want to analyze the results after a dry-run - so without a database we remove this possibility - which can be a pain if you get started.

So i personally would change this to default to a "persisted" database - not just limit us to aligning the docs related to this.
