### ISSUE TITLE
About the config file location

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2602]
Config file(s) should for now be created in the root directory when developing a bot. But the folder user_data seems to have been created to contain all the logic needed to create a bot.

Why the config file(s) are not below the user_data folder (as kind of unique entry folder for end-user)?

Have a nice day.

**Comment by xmatthias** [comment]
well ... it is "in progress" ... somehow ...  see #2112 point 2:

>  move default configuration to `user_data` directory

Not saying i did anything in this regard ... but at least it's something we're aware of...

**Comment by gaugau3000** [comment]
i havent see it :-) i close this one so !

**Comment by xmatthias** [comment]
it's "hidden" / not clearly visible ...but a (my?) todo-list ...

**Comment by hroff-1902** [comment]
same for #1775 (for hyperopt tasks) 😆
