### ISSUE TITLE
using informative_pair in hyperopt

### ISSUE THREAD

**Issue by mj1300** [freqtrade/freqtrade#2608]
## Step 2: Describe your environment

  * Operating system: ____ Windows 10
  * Python Version: _____ python 3
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:
i just want to use informatove pair in hyperopt 
i use this code:
   ```
@staticmethod
    def informative_pairs(self):
        return [("BTC/USDT", "1h")]
        

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        data = self.dp.get_pair_dataframe(pair="BTC/USDT", ticker_interval=self.ticker_interval)

        dataframe = dataframe.merge(data[["date", "low"]],on="date",how="left",suffixes=("",self.config['stake_currency']))
        dataframe2 = dataframe.merge(data[["date", "high"]],on="date",how="left",suffixes=("",self.config['stake_currency']))

```
but i got this error:
```

2019-12-03 21:57:08,251 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "c:\users\test\desktop\freqtrade-develop1\freqtrade\main.py", line 39, in main
    args['func'](args)
  File "c:\users\test\desktop\freqtrade-develop1\freqtrade\optimize\__init__.py", line 76, in start_hyperopt
    hyperopt.start()
  File "c:\users\test\desktop\freqtrade-develop1\freqtrade\optimize\hyperopt.py", line 404, in start
    preprocessed = self.backtesting.strategy.tickerdata_to_dataframe(data)
  File "c:\users\test\desktop\freqtrade-develop1\freqtrade\strategy\interface.py", line 429, in tickerdata_to_dataframe
    for pair, pair_data in tickerdata.items()}
  File "c:\users\test\desktop\freqtrade-develop1\freqtrade\strategy\interface.py", line 429, in <dictcomp>
    for pair, pair_data in tickerdata.items()}
TypeError: populate_indicators() takes 2 positional arguments but 3 were given
```

**Comment by xmatthias** [comment]
Assuming you copy/paste `populate_indicators` into hyperopt - then you'll need to remove the `self` - and convert it to a staticmethod (the HyperoptInterface is slightly different) than the 

```
 def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
```
becomes

```
@staticmethod
def populate_indicators(dataframe: DataFrame, metadata: dict) -> DataFrame:
```

This is not necessary if you keep `populate_indicators` in the strategy and call hyperopt via
``` 
freqtrade hyperopt --strategy MyStrategy --hyperopt MyHyperopt ... `
```
which is also simpler since you'll need populate_indicators in your strategy anyway.

**Additional Note:**
 you will need to check if dataprovider is available as shown [in the documentation](https://www.freqtrade.io/en/latest/strategy-customization/#example-fetch-live-ohlcv-historic-data-for-the-first-informative-pair):

```python
if self.dp:
    inf_pair, inf_timeframe = self.informative_pairs()[0]
    informative = self.dp.get_pair_dataframe(pair=inf_pair,
                                             timeframe=inf_timeframe)
```

We do not guarantee dataprovider to be available with all operations.

**Comment by hroff-1902** [comment]
> you will need to check if dataprovider is available as shown [in the documentation]

But there is no `self` after transferring `populate_indicators` to the hyperopt...
And if he leave it in the strategy, he receives that error, as far as I understand. That's the point.
(needs to be checked)

**Comment by xmatthias** [comment]
well you can always use `HyperoptName.dp.` - since we assign it at class level, not at instance level.

**Comment by aak-dev** [comment]
any update on this issue?
Currently the informative pairs are unable to hyperopt on. @hroff-1902 and @xmatthias

**Comment by xmatthias** [comment]
they are available by using `HyperoptName.dp.get_pair_dataframe()` (as pointed out above already)... (Replace HyperoptName with the name of your hyperopt class).

**Comment by aak-dev** [comment]
MA2Opt is my hyperopt class name. Checkout the error message.
 `AttributeError: type object 'MA2Opt' has no attribute 'dp'`

**Comment by alexcrownjr** [comment]
I didn't get is DataProvider enabled for Hyperopt or not ?

**Comment by xmatthias** [comment]
Dataprovider is enabled for hyperopt, but only if populate_indicators is NOT in the hyperopt class, but in the strategy.
