### ISSUE TITLE
cant export plot-dataframe with informative_pairs

### ISSUE THREAD

**Issue by mj1300** [freqtrade/freqtrade#2610]
## Step 2: Describe your environment

  * Operating system: ____ windows 10
  * Python Version: _____ python 3
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:
i just wants to export the backtest trade history with `freqtrade plot-dataframe` but it doesnt work and it has an error that says:
```
data = self.dp.get_pair_dataframe(pair="BTC/USDT", ticker_interval=self.ticker_interval)
AttributeError: 'DefaultStrategy' object has no attribute 'dp'
```

**Comment by xmatthias** [comment]
I'm going to close this now since there's been no response, so i'll assume it was solved by the answer given.

Feel free to reopen and include the details about version if you still have this problem.
