### ISSUE TITLE
rest api cannot load config

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2611]
Operating system: ubuntu 18.04
Python Version: _____ (python 3.6.8)
CCXT version: _____ (1.18.1306)
Branch: Develop
git log --format="%H" -n 1

2019-12-04 00:09:04,605 - ft_rest_client - WARNING - Could not load config file rest_config1H.json.

**Comment by xmatthias** [comment]
well, the message is clear - `rest_config1H.json` points to a nonexisting file.
Best use a filename which exists ... 

You don't provide any more information for us to help you (the command you run or so) ... so this is the best i can tell you.

**Comment by gitgitgat** [comment]
OKay, just noticed, it's 

`python3 scripts/rest_client.py --config rest_config.json <command> [optional parameters]`

**Comment by gitgitgat** [comment]
It is now 
```
 - ft_rest_client - WARNING - Connection error
None
```

**Comment by xmatthias** [comment]
is the bot running (in another terminal)? 
otherwise the api will not be available.

Also, how are you running the bot? within docker?

**Comment by gitgitgat** [comment]
there doesn't seem to be a bot running. ps aux|grep python looks like:

```
root      1018  0.0  0.0 170832 17220 ?        Ssl  Nov24   0:00 /usr/bin/python3 /usr/bin/networkd-dispatcher --run-startup-triggers
root      1256  0.0  0.0 187668 19996 ?        Ssl  Nov24   0:00 /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
user+ 20795  0.0  0.0  14856  1064 pts/0    S+   21:10   0:00 grep python
```
docker installation didn't work so it is running from the linux server

**Comment by hroff-1902** [comment]
just run it

**Comment by xmatthias** [comment]
i think there is a misunderstanding about the functioning of the rest-client.

you need to run the bot (`freqtrade trade --config restapiconfig.json ...`) - then open a new terminal, and use the client to connect to it (the bot needs to run to be able to connect to).

The client-side script does ONLY query the running bot and acts as a replacement to telegram, it does not run the bot itself.

**Comment by gitgitgat** [comment]
okay, cannot remember if that was tried. thanks
