### ISSUE TITLE
Kraken invalid nonce 

### ISSUE THREAD

**Issue by enzesi** [freqtrade/freqtrade#2613]
## Step 1: Have you search for this issue before posting it?

Kraken invalid nonce 

## Step 2: Describe your environment

  * Operating system: ____
  * Python Version: 3.6.0_____ (`python -V`)
  * CCXT version: 1.20.22_____ (`pip freeze | grep ccxt`)
  * Branch: Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

when I change exchange name to kraken in config file and set key and secret. Then I run the bot.

The following error occurs.
  
![Screen Shot 2019-12-04 at 12 00 39 PM](https://user-images.githubusercontent.com/32287882/70163579-b7ea3200-168d-11ea-8780-a9691117b16a.png)

![Screen Shot 2019-12-04 at 11 59 30 AM](https://user-images.githubusercontent.com/32287882/70163492-9426ec00-168d-11ea-91b1-986df910a984.png)

**Comment by hroff-1902** [comment]
do you use same api key with another bot on the same machine or on another machine?

**Comment by enzesi** [comment]
yes. I used the same api key on another bot before.

**Comment by hroff-1902** [comment]
* Have a look at this: https://support.kraken.com/hc/en-us/articles/360001148063-Why-am-I-getting-invalid-nonce-errors-
-- create a new key for this machine, use it only on a single instance of the bot
* try to increase the nonce window for the key used, see https://support.kraken.com/hc/en-us/articles/360001148023-What-is-a-nonce-window-

**Comment by enzesi** [comment]
Thanks. So even if i am not using the other bot any more, I have to generate a new key and increase nonce window to run on freqtrade?

**Comment by hroff-1902** [comment]
first try to generate new key
if this does not help, assign a wider nonce window to it

**Comment by hroff-1902** [comment]
also make sure that Query Funds is On for that key

**Comment by hroff-1902** [comment]
what has helped particularly? pls report back...

**Comment by enzesi** [comment]
create a new key for this machine and change nonce window to 5000
