### ISSUE TITLE
backtesting bug

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2616]
There is some sort of bug in backtesting. 

When using `python3 -m freqtrade backtesting -c config.json -s Strategy  -i 1h` it backtests up to the latest day. Today it backtests for about 40 days up to 2019-12-05. But if `--timerange` is specified, for instance `--timerange 20190112-20190512`,  the following error appears:  

```
2019-12-05 17:50:57,686 - freqtrade.data.history - WARNING - No history data for pair: "ETH/BTC", timeframe: 1h. Use `freqtrade download-data` to download the data
2019-12-05 17:55:51,691 - freqtrade - ERROR - No data found. Terminating.
```

**Comment by hroff-1902** [comment]
2019-12-05 (5th of December) corresponds to 20191205, not to 20190512
The format for `--timerange` is YYYYYMMDD.

**Comment by gitgitgat** [comment]
okay thanks

**Comment by gitgitgat** [comment]
There is still something off about backtesting. Let's say I backtest StrategyOne with configOne.json. 
If `--timerange` is `20191125-20191205` there is an x % of profit. But if I split that into chunks, for example, backtest `20191125-20191129` the output is 0 profit, and the output is also 0 profit if `20191201-20191205`

**Comment by hroff-1902** [comment]
Do you have any trades during these both chunks? What timeframe are you using?

**Comment by gitgitgat** [comment]
Those are the timeframes I am using (single block: 20191125-20191205 and chunk one: 20191125-20191129; chunk two: 20191201-20191205). No trades are present in any of the chunks, only in the single block

**Comment by hroff-1902** [comment]
How many trades in the whole block do you have? What timeframe is used?
Can you attach output (including full log) for all 3 runs?

**Comment by gitgitgat** [comment]
I don't know, it looks weird now everything outputs 0

**Comment by hroff-1902** [comment]
so there is no bug now.
I'm closing this now, please understand that we need a way to review (to explain in case of misunderstanding) and to reproduce (in case this is an error).
