### ISSUE TITLE
ROI tables

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2621]
In hyperopt, the roi table result is something like "0:0.04", "20:0.3", "40:0.02", "80: 0.01". Would it be possible to add more extra roi spaces, or has four been decided as most optimal for the result?

**Comment by hroff-1902** [comment]
It's possible and it's described in the docs:

> Override the generate_roi_table() and roi_space() methods and implement your own custom approach for generation of the ROI tables during hyperoptimization if you need a different structure of the ROI tables or **other amount of rows (steps)**. A sample for these methods can be found in user_data/hyperopts/sample_hyperopt_advanced.py.

**Comment by hroff-1902** [comment]
Closing it as answered

**Comment by samgermain** [comment]
Is there an example of the code for this anywhere?

**Comment by samgermain** [comment]
[Here's an example of how to do this](https://github.com/freqtrade/freqtrade/issues/3743#issuecomment-685704916)
