### ISSUE TITLE
Hyperopt ValueError

### ISSUE THREAD

**Issue by Mixcoatl5** [freqtrade/freqtrade#2623]
Operating system: 18.04
Python Version: 3.6.9
CCXT version: 1.19.86
Branch: Developp
Last Commin ID: 6b142d716f4fc202ceb7c4b3c6781f3b41c2dba6

 ----------------------------

Hey,
Strange thing happen to me. My hyperopt used to work well. Few days ago my hyperopt stopped work whenever I set more than `-e 31`.  Whenever I start  `-e32` or more plugin starts, and when reach 32th I got following error:
![Screenshot from 2019-12-07 12-33-58](https://user-images.githubusercontent.com/58388876/70373968-fa11ae80-18ed-11ea-9ff8-dcca3b6d4ff3.png)

`
python3 freqtrade hyperopt -c config.json -s Strategy -e 50 --hyperopt-loss SharpeHyperOptLoss --hyperopt AwesomeHyperOpt` was used to start command

Could anybody help, please?

**Comment by hroff-1902** [comment]
* Last Commit ID: _____ (`git log --format="%H" -n 1`)

**Comment by Mixcoatl5** [comment]
>     * Last Commit ID: _____ (`git log --format="%H" -n 1`)

6b142d716f4fc202ceb7c4b3c6781f3b41c2dba6

Sorry, I forgot

**Comment by hroff-1902** [comment]
It's fresh enough...

Is the message the same each time or it fails in different places?

* try to update the dependencies: `pip3 install -r requirements.txt` in venv
* try to run hyperopt with `-j 1` option
* watch the free memory (your system may be out of memory when you run hyperopt): you can do this with a `htop` utility running in a sep. terminal, or with another utility if you have any.

**Comment by xmatthias** [comment]
well the error `ValueError: operands could not be broadcast together with shapes ` suggests that it may be a problem with the customized hyperopt file itself (to be precise, with something that's assigning "something" to an array) - but without seeing the hyperopt section it's difficult to tell.

It may be coincidence that this happens after 32 epochs ... i suspect the error is "covered" by a conditional which is first tried after 32 epochs.

**Comment by Mixcoatl5** [comment]
> It's fresh enough...
> 
> Is the message the same each time or it fails in different places?

> Yes, I always got same error

>     * try to update the dependencies: `pip3 install -r requirements.txt` in venv
>  
>     * try to run hyperopt with `-j 1` option
> 
>     * watch the free memory (your system may be out of memory when you run hyperopt): you can do this with a `htop` utility running in a sep. terminal, or with another utility if you have any.

Thanks for answer,

I tried yo install requirements into venv - succesfully.
Tried run hyperopt with `-j 1`
Installed htop
Increased RAM for my virtual machine and checked disk free space (over 3 Gb)

During hyperopt I was watching free space and everything seems to be OK

i still got the same error as previously mentioned

**Comment by Mixcoatl5** [comment]
> well the error `ValueError: operands could not be broadcast together with shapes ` suggests that it may be a problem with the customized hyperopt file itself (to be precise, with something that's assigning "something" to an array) - but without seeing the hyperopt section it's difficult to tell.
> 
> It may be coincidence that this happens after 32 epochs ... i suspect the error is "covered" by a conditional which is first tried after 32 epochs.

According to your note I checked hyperopt file one more time... Cant believe I didn't noticed it earlier. My sell-tiggers were set up so bad I assume hyperopt run out of possibilities after 31 epochs. I set up sell-tiggers correctly and currently running epoch over 40 and everything is working!

Thx very much for your help.

PS: I may have one more question - probably very noobish.
When I run hyperopt I use `--hyperopt AwesomeHyperOpt` from my freqtrade/freqtrade/optimize folder. But when I want to make new class of '--hyperopt' and I add it to __init__.py  in this folder I am not able to load that --hyperopt. So I assume I have to import my class into different folder than __init__.py. My question is where do I need to specify this so I ll be able to load multiple --hyperopt file. Currently I have to rename my class in every hyperopt file I want to use to 'AwesomeStrategy'.

**Comment by xmatthias** [comment]
well, your hyperopt file should not be in freqtrade/freqtrade/optimize - but in `freqtrade/user_data/hyperopts/`.

Best use `freqtrade new-hyperopt --hyperopt HyperoptName` - this will create a new hyperopt file in the correct place (check the output for the full filename) - there is no need to add the classname anywhere other than in the command line

**Comment by hroff-1902** [comment]
30 epochs are generated by skopt in a random manner (they are marked with asterisk in the hyperopt output), starting from epoch 31 skopt starts to fill ML models with results and plan its descending path in the hyperspace to a local minimum of the objective (loss) function. That's why my idea was that it's related with memory or something like that.

**Comment by Mixcoatl5** [comment]
> well, your hyperopt file should not be in freqtrade/freqtrade/optimize - but in `freqtrade/user_data/hyperopts/`.
> 
> Best use `freqtrade new-hyperopt --hyperopt HyperoptName` - this will create a new hyperopt file in the correct place (check the output for the full filename) - there is no need to add the classname anywhere other than in the command line

Thx, just testing this out and everything seems to be OK! Thx a lot for help


> First 30 epochs are generated by skopt in a random manner (they are marked with asterisk in the hyperopt output), starting from epoch 31 skopt starts to fill ML models with results and plan its descending path (using bayesian search algorithm) in the hyperspace to a local minimum of the objective (loss) function. That's why my idea was that it's related with memory or something like that.

I got SWP memory full during first tests. When I rise RAM memory my SWP fold to 0. So there was a little change in this manner. Thx for your advice anyway. Very appreciated :)

**Comment by hroff-1902** [comment]
So changing the definition of your hyperopt spaces helps, am I right?
It's interesting to see that first version of the spaces that caused the problem...

**Comment by Mixcoatl5** [comment]
> So changing the definition of your hyperopt spaces helps, am I right?
> It's interesting to see that first version of the spaces that caused the problem...

Ye, changing of hyperopt file helped :)

**Comment by xmatthias** [comment]
> First 30 epochs are generated by skopt in a random manner (they are marked with asterisk in the hyperopt output), starting from epoch 31 skopt starts to fill ML models with results and plan its descending path (using bayesian search algorithm) in the hyperspace to a local minimum of the objective (loss) function. That's why my idea was that it's related with memory or something like that.

i think this should be documented in the hyperopt documentation ... this is completely new to me ...

**Comment by hroff-1902** [comment]
I'm thinking, should this be customizable (the number of optimizer startup random epochs) via a config, or not...
It's here (and INITIAL_POINTS = 30):
https://github.com/freqtrade/freqtrade/blob/9e85376a2df3443b2d3cf5888ddb4b08f75601ff/freqtrade/optimize/hyperopt.py#L391
