### ISSUE TITLE
Limit BUY/SELL Oders

### ISSUE THREAD

**Issue by maxma-bit** [freqtrade/freqtrade#2638]
I'm having a little trouble understanding the part of the doc related to Limit BUY/SELL Oders. In particular, the doc say:
bid_strategy. check_depth_of_market.enabled
Do not buy if the difference of buy orders and sell orders is met in Order Book.

What does it mean that the difference of buy orders and sell orders is satisfied? How such difference is met? Also, do you refer to the numerical difference between the number of BUY and SELL orders present in the Order Book at a given time. Or, the difference in price between the first BUY and the first SELL at the top of the Order Book?
Maybe you mean something like that:
the ratio between the total number of orders of BUY and the total number of orders of SELL is computed, if such ratio exceeds the constant defined in "bid_strategy. check_depth_of_market.bids_to_ask_delta", then the order of BUY is created, otherwise the order of BUY is ignored.

A second issue of interpretation also in the Limit SELL options part of the doc: ask_strategy.order_book_min
Bot will scan from the top min to max Order Book Asks searching for a profitable rate.
How is it determined if a rate is profitable? what is it meant by rate? if "rate" is the selling price then this parameter always select the maximum price?

perhaps it is worth re-phrasing the text in the documentation in a manner consistent with the code.

**Comment by hroff-1902** [comment]
@maxma-bit pls verify the changes made to the documentation in #2686
