### ISSUE TITLE
cancel an order before the unfilledtimeout expires

### ISSUE THREAD

**Issue by maxma-bit** [freqtrade/freqtrade#2646]
Is there a way to cancel an order before the unfilledtimeout expires, in a way that the local sqlite database remains consistent with the exchage?
Please note that the RPC command /forcesell or /forcebuy do not help with this. In the case of a SELL, one would like to cancel the SELL order in Order Book before the sale is actually executed. It seems a bit different from forcing a SELL with the RPC command /forcesell.
For BUY order, one would like to cancel the order before the BUY purchase is made. It seems to me different from forcing a purchase with /forcebuy.
if there is no way to do it, could you consider this for a possible extension?

**Comment by xmatthias** [comment]
I guess you should be able to cancel the buy-order "on exchange" - the database should notice that and update the trade.
One problem this causes:
assuming you don't use `process_only_new_candles=True`, then the buy-signal may still be active - so it reopens the trade seconds after you cancelled that.
We should be able to prevent that by locking the pair anyway - but that'll mean that you the bot can't buy this pair for the duration of this candle.


i think you may be able to stop a buy via `/forcesell` (don't pin me on that though - never tested this scenario).

**Comment by hroff-1902** [comment]
> assuming you don't use process_only_new_candles=True, then the buy-signal may still be active - so it reopens the trade seconds after you cancelled that.

Should not the pair be locked after first buy?

Pair of 2 commands `/stopbuy=pair`, `/cancelorder=id` issued should help in this case anyway...

**Comment by werkkrew** [comment]
Is this still considered a valuable "good first issue"?

**Comment by xmatthias** [comment]
sure thing - i think all issues we've got currently open (with the label Enhancement) are kindof "free to pick" or are otherwise closed, although some will not be easy to implement / require multiple steps to fully be implemented  (this does not apply to "good first issue" though).
