### ISSUE TITLE
Add a new exchange 

### ISSUE THREAD

**Issue by enzesi** [freqtrade/freqtrade#2647]
## Step 1: Have you search for this issue before posting it?

How to add a new exchange? I would like to add rightbtc exchange to freqtrade and it is listed on https://github.com/ccxt/ccxt/

## Step 2: Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

Do not know how to add Rightbtc to freqtrade.

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

![Screen Shot 2019-12-11 at 2 33 03 PM](https://user-images.githubusercontent.com/32287882/70653796-2e090e80-1c23-11ea-82bc-444c41ffca8b.png)
![Screen Shot 2019-12-11 at 2 31 54 PM](https://user-images.githubusercontent.com/32287882/70653863-46792900-1c23-11ea-86ea-7864d7b83c29.png)

**Comment by hroff-1902** [comment]
It's already in the list of exchanges available for freqtrade:
```
$ freqtrade list-exchanges
Exchanges available for Freqtrade: _1btcxe, acx, allcoin, bequant, bibox, binance, binanceje, binanceus, bitbank, bitfinex, bitfinex2, bitkk, bitlish, bitmart, bitmax, bittrex, bitz, bleutrade, btcalpha, btcmarkets, btcturk, buda, bw, bytetrade, cex, cobinhood, coinbaseprime, coinbasepro, coinex, coss, crex24, digifinex, dsx, fcoin, fcoinjp, ftx, gateio, gemini, hitbtc2, huobipro, huobiru, idex, kkex, kraken, kucoin, kuna, lbank, mandala, mercado, oceanex, okcoincny, okcoinusd, okex, okex3, poloniex, rightbtc, stex, theocean, tidebit, upbit, whitebit, zb
```
You can try to use the bot with it. Probably you'll be the first person who used the bot with that exchange, we do not know this.

**Comment by enzesi** [comment]
I tried and there is some error with api urls.
Api should be 'api': 'https://api.rightbtc.com',
and here is the documentation: https://docs.rightbtc.com/api/rest_pub.html
and when I change to the correct api 
the following error occurs.
![Screen Shot 2019-12-11 at 4 04 27 PM](https://user-images.githubusercontent.com/32287882/70660351-f5236680-1c2f-11ea-9009-7b511856cd7b.png)

**Comment by hroff-1902** [comment]
Report it to ccxt, there is nothing to do with it in Freqtrade, we rely on ccxt in communication with the exchanges.

**Comment by enzesi** [comment]
Okay, thank you.

**Comment by xmatthias** [comment]
also make sure to use the latest version of ccxt (`pip install -U ccxt`). 

CCXT is usually very quick in fixing this type of problems - so maybe they already did.
Also, it would not make sense for freqtrade to fix this, since then application XYZ which also uses ccxt would encounter the same problem too, and would then fix it themselfs - that's the whole point of using a central library ... to have one place to fix this type of bug.

**Comment by hroff-1902** [comment]
@enzesi I've seen your issue made at ccxt repo 👍 
Closing this then.
Feel free to reopen if this makes sense.
