### ISSUE TITLE
FTX issue when backtesting spot markets

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#2653]
## Step 1: Have you search for this issue before posting it?

yes

## Step 2: Describe your environment

  * Operating system: linux
  * Python Version: Python 3.7.5rc1
  * CCXT version: ccxt==1.19.25 
  * Branch: Develop 
  * Last Commit ID: latest
  
## Step 3: Describe the problem:

When doing 
`freqtrade backtesting -c ftx.json --strategy-list chop ao ao2 ao3 --ticker-interval=4h`
using BTC/USD and FTT/USD markets with proper USD as stake currency, then an error pops out.

### Steps to reproduce:

  1. try to backtest using FTX as exchange, pair BTC/USD 
  2. Error pops out
  
### Observed Results:

  Error: 
```
2019-12-13 17:08:48,545 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/dante/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/dante/freqtrade/freqtrade/optimize/__init__.py", line 43, in start_backtesting
    backtesting = Backtesting(config)
  File "/home/dante/freqtrade/freqtrade/optimize/backtesting.py", line 68, in __init__
    self.fee = self.exchange.get_fee()
  File "/home/dante/freqtrade/freqtrade/exchange/common.py", line 113, in wrapper
    return f(*args, **kwargs)
  File "/home/dante/freqtrade/freqtrade/exchange/exchange.py", line 932, in get_fee
    price=price, takerOrMaker=taker_or_maker)['rate']
  File "/home/dante/.local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1710, in calculate_fee
    market = self.markets[symbol]
KeyError: 'ETH/BTC'

```
I was expecting a simple backtest as usual.

**Comment by xmatthias** [comment]
well - please use pairs that are available in your pairlist.
The error shows that your pairlist (in your configuration) contains ETH/BTC.
ETH/BTC is not available.

```
freqtrade list-pairs --exchange ftx --quote BTC

Exchange FTX has 1 active market with BTC as quote currency:
| Id      | Symbol   | Base   | Quote   | Active   | Is pair   |
|:--------|:---------|:-------|:--------|:---------|:----------|
| FTT/BTC | FTT/BTC  | FTT    | BTC     | True     | True      |

```


with BTC as quote - that's exactly one, which is FTT/BTC.

Remove ETH/BTC from the pairlist ... then it should work.

**Comment by Dante2333** [comment]
I don't have Eth btc as pair. The only pairs on my list are fttusd and btcusd.

**Comment by Dante2333** [comment]
I don't have Eth btc as pair. The only pairs on my list are fttusd and btcusd.

**Comment by hroff-1902** [comment]
can confirm this,
can be reproduced with DefaultStrategy:

* `cp config_binance.json.example config_ftx.json`
* Edit config_ftx.json, set: exchange name "ftx:, pair_whitelist: ["BTC/USD", "FTT/USD"], pair_whitelist: [], stake_currency: "USD", stake_amount: 100.
* `freqtrade download-data -c config_ftx.json --days 90 -t 4h`
* `freqtrade backtesting -c config_ftx.json -s DefaultStrategy`
-- fails with `KeyError: 'ETH/BTC'`

**Comment by xmatthias** [comment]
for now - use `--fee 0.001` (or whatever the fee as ratio is on FTX). then it'll work.

**Comment by xmatthias** [comment]
@hroff-1902 
using `freqtrade download-data -c config_ftx.json --days 90 -t 4h` will not do you any good - i've just tried it with 5m and 15min tickers - ftx seems to only return the latest 500 candles via fetch_ohlcv (similar to kraken ...).

this aint going to be an easy exchange to work with, if it's already problematic when downloading data...

**Comment by hroff-1902** [comment]
> @hroff-1902
> using `freqtrade download-data -c config_ftx.json --days 90 -t 4h` will not do you any good - i've just tried it with 5m and 15min tickers - ftx seems to only return the latest 500 candles via fetch_ohlcv (similar to kraken ...).
> 
> this aint going to be an easy exchange to work with, if it's already problematic when downloading data... - especially since the [api docs](https://docs.ftx.com/#get-historical-prices) say that historic data should be available (and don't mention anything about a limit ...).

Yes and this issue is not about any exchange-specific error, it founds a general bug, which is applied for any exchange with no ETH/BTC pair. That's why I have not closed it (or postponed) with a message ("FTX is not officially supported")

**Comment by xmatthias** [comment]
> That's why I have not closed it (or postponed) with a message ("FTX is not officially supported")

I assume most errors with FTX (and most other, untested exchanges) will not be exclusive to these but may affect other exchanges too. 
If users are willing to test exchanges, then I'm willing to support that - but I'll not start testing exchanges i'm not interrested in (that was also my point in  #2443 - maybe that wasn't clear)
