### ISSUE TITLE
Backtesting results strongly differ from real results

### ISSUE THREAD

**Issue by deci260** [freqtrade/freqtrade#2662]
## Describe your environment
Freqtrade running in live mode:
  * Freqtrade development docker image
  * Last commit: `8dd9b5c6fba973b98defc0f9a9e2e3c01af735dd`
 
Freqtrade used for backtesting  
  * Operating system: Ubuntu 18.04
  * Python Version: 3.6.9
  * CCXT version: 1.20.81
  * Branch: Develop
  * Last Commit ID: 18dfa56752e0b1fcd301db24fe8967aae5035911
  
## Describe the problem:

I've been running freqtrade in live mode since yesterday (14/12/2019) at 9.00 AM UTC. These are the results (from telegram):

```
ROI: Close trades
∙ -4.89786055 USDT (-0.79%)
∙ -0.000 EUR
ROI: All trades
∙ -5.21113150 USDT (-0.77%)
∙ -0.000 EUR
Total Trade Count: 11
First Trade opened: a day ago
Latest Trade opened: 4 hours ago
Avg. Duration: 1:34:34
Best Performing: MATIC/USDT: 1.12%
```
Just to test stuff, I decided to run a backtest on my local machine starting at the exact date the bot started and using the same strategy and the same config file. Here are the results of every trade opened:

 ```
2019-12-15 14:05:24,259 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2019-12-14T09:00:00+00:00 up to 2019-12-15T12:47:00+00:00 (1 days)..
pair       |   buy count |   avg profit % |   cum profit % |   tot profit USDT |   tot profit % | avg duration   |   profit |   loss
MATIC/USDT |           3 |           0.89 |           2.68 |        0.26835792 |           2.68 | 0:02:00        |        3 |      0
CHZ/USDT   |           1 |           0.53 |           0.53 |        0.05346124 |           0.53 | 0:08:00        |        1 |      0
COCOS/USDT |           1 |           1.11 |           1.11 |        0.11136992 |           1.11 | 0:00:00        |        1 |      0
ARPA/USDT  |           1 |           0.51 |           0.51 |        0.05114829 |           0.51 | 0:42:00        |        1 |      0
CTXC/USDT  |           1 |           0.44 |           0.44 |        0.04404568 |           0.44 | 0:49:00        |        1 |      0
ICX/USDT   |           1 |           0.42 |           0.42 |        0.04232891 |           0.42 | 0:14:00        |        1 |      0
REN/USDT   |           2 |          -0.98 |          -1.95 |       -0.19519979 |          -1.95 | 0:20:00        |        1 |      1
PERL/USDT  |           1 |           0.54 |           0.54 |        0.05450679 |           0.54 | 0:37:00        |        1 |      0
RLC/USDT   |           1 |           0.62 |           0.62 |        0.06195314 |           0.62 | 0:53:00        |        1 |      0
MITH/USDT  |           1 |           1.16 |           1.16 |        0.11644356 |           1.16 | 0:01:00        |        1 |      0
STORM/USDT |           1 |           0.63 |           0.63 |        0.06306371 |           0.63 | 1:29:00        |        1 |      0
TOMO/USDT  |           4 |           1.59 |           6.35 |        0.63520931 |           6.35 | 0:00:00        |        4 |      0
DENT/USDT  |           1 |           0.67 |           0.67 |        0.06745984 |           0.67 | 2:19:00        |        1 |      0
MFT/USDT   |           1 |           0.86 |           0.86 |        0.08617943 |           0.86 | 0:29:00        |        1 |      0
CVC/USDT   |           2 |           1.24 |           2.48 |        0.24854255 |           2.48 | 0:08:00        |        2 |      0
TOTAL      |          22 |           0.78 |          17.07 |        1.70887050 |          17.07 | 0:24:00        |       21 |      1

 ```
As you can see backtesting returns a whooping 17.07% profit while in reality in live mode the profit is -0.79%.

NOTICE: I've used --fee 0.001 to account to the 0.1% binance fee.
NOTICE2: I've been using 1m timeframes.

### Steps to reproduce:

  1. Run live mode for a day
  2. Run backtesting from the exact time you started live mode
  3. Compare the results
  
### Observed Results:
It's kind of obvious that the results are not the exact same, but an 18% difference in just one day leads me to believe that the backtesting feature is highly broken.

**Comment by xmatthias** [comment]
> NOTICE: I've used --fee 0.001 to account to the 0.1% binance fee.

That's not really necessary, backtesting fetches the default fee from the exchange - so it'll be set to 0.001 already for binance. 

> It's kind of obvious that the results are not the exact same, but an 18% difference in just one day leads me to believe that the backtesting feature is highly broken.

i think your numbers are slightly off target, and the comparison of numbers is wrong.
you're comparing a cumulative profit (17.07%) with the average profit -0.79%.
If you compare the same values, then the values are 0.78% for backtesting, and -0.79% for real runs.


Now regarding comparing - there's a ton of things which can cause this - from mistakes in the strategy (using data which it should not have access to) to bad pair selection (where one pip is > 1%) - which causes one stoploss to pull you down 10% or more - even if the stoploss was set at 5%.

Now assuming the above problems did not occur, there's still a lot of analysis to be done.

Please provide the following for further analysis:
* output of /performance (to identify if one pair caused this drawdown)
* backtesting output detailing the sell reasons (roi / stoploss / sellsignal, ...)
* strategy parameters (roi / stoploss / trailing stoploss / ...).
* `max_open_trades` parameter
* Strategy (if possible / willing to share) - eventually privately in slack channel ...

Assuming the last point is not possible (you're unwilling to share the strategy), then please compare the trades yourself by selecting a pair which ideally has at least one aligned trade - and plotting both backtesting and real run - comparing where buys and sells did happen.

**Comment by deci260** [comment]
> i think your numbers are slightly off target, and the comparison of numbers is wrong.
you're comparing a cumulative profit (17.07%) with the average profit -0.79%.

Is that really the average profit? How do I get the cumulative profit from real runs?
By the way here are the information you requested:
`/performance`:

```
Performance:
1. MATIC/USDT 1.12% (2)
2. CVC/USDT 0.26% (1)
3. TOMO/USDT -1.99% (2)
4. VITE/USDT -2.36% (3)
5. STORM/USDT -2.41% (1)
6. COCOS/USDT -2.48% (1)
```

Backtesting sell reasons:
```
| Sell Reason        |   Count |
|:-------------------|--------:|
| trailing_stop_loss |      21 |
| stop_loss          |       1 |
```
Strategy parameters:
* ROI: Disabled, `minimal_roi = { "0": 100 }`
* Stoploss: `-0.02164`
* Trailing stoploss offset: `0.005`
* Trailing stoploss: `0.001`

 `max_open_trades`: 1

I'm about to send my strategy to you on slack.

**Comment by deci260** [comment]
I've done some further analysis and I think this might be a really serious issue that occurs when running in live mode.
Let's analyze backtesting and live date from  the currency COCOS/USDT
Look at this graph from backtesting data:
![Screenshot_2019-12-15 Screenshot](https://user-images.githubusercontent.com/36604712/70866966-4739f400-1f70-11ea-896a-74552413a8ea.png)
We can clearly see that the buy signal gets sent at the end of that big bearish candle (green triangle) and the asset gets bought at the start of the next candle (green square). It then gets sold (due to trailing stoploss) before the end of the same candle.

Now look at the live graph
![Screenshot_2019-12-15 Screenshot(2)](https://user-images.githubusercontent.com/36604712/70867053-3dfd5700-1f71-11ea-986a-ef8e6982f67c.png)
The buy signal gets sent at the same time as the backtesting, but it looks like the asset is getting bought more than 1 minute later, after the end of the next candle! 

The same is happening with every other pair and the fact that I was able to make a profit from some of the trades is purely luck.

Here is another example with MATIC/USDT:

Backtesting:
![Screenshot_2019-12-15 Screenshot(3)](https://user-images.githubusercontent.com/36604712/70867144-499d4d80-1f72-11ea-9277-9fafd6b71b15.png)

Live:
![Screenshot_2019-12-15 Screenshot(4)](https://user-images.githubusercontent.com/36604712/70867155-65085880-1f72-11ea-95cb-51e767caa21d.png)

In this case I was lucky enough so that the price remained pretty much the same when the order got fulfilled.
I think this actually is a really serious issue. My guess (might be stupid but who knows) is that this problem is caused by hardware. My bot is running in the cloud with 2 vcpus and 2.5 GB of ram. I'm guessing that freqtrade finishes querying the strategy on whether to buy/sell assets before sending the orders to the exchange.
For example:
Let's say I have 100 pairs in my whitelist. Freqtrade queries my strategy on whether it should buy the first one or not. Let's say it's a yes, before sending the order to the exchange freqtrade has to repeat the process 99 more times (once per pair). While this might not be a problem on normal computers, when the bot is running on a docker container with low hardware this can actually take a little while.
I don't know if that's really the case, I haven't read the code yet due to lack of time. Let me know what you think might be the cause of this issue.

**Comment by xmatthias** [comment]
just from looking at the trailing stop parameters i have my suspicions ...

> Trailing stoploss
> - High happens first - adjusting stoploss
> - Low uses the adjusted stoploss (so sells with large high-low difference are backtested correctly)

from the docs - [assumptions made by backtesting](https://www.freqtrade.io/en/latest/backtesting/#assumptions-made-by-backtesting)

backtesting assumes high happens first, pulling trailing stop all the way up to high. However, in reality, the sequence will not be open -> HIGH - lower ... -> ... 
it'll be more like open - a bit higher - a bit higher - a bit lower - a bit lower - a bit higher - HIGH. 

during backtesting, we don't have this "intra-candle" data ... so by pulling the stoploss to 0.1% after 0.5% gain, will almost surely result in 90% sells at a maximum of 0.5% ... more likely 0.4%.


backtesting and plotting your strategy, it shows another pattern which i find ... dangerous.

It frequently buys - and sells on trailing stop during the same candle.
This may happen in reality if the candle opens (you buy at that price) - and the price shoots right to this "high" value - and then retracts to close (or low ...).

However - as explained above - that's unlikely to happen - a gain of 0.5% can easily be reached - but 

This is again a problem of pulling the trailing stop this tight (lower than 1%).

![2019-12-15-194501_558x436_scrot](https://user-images.githubusercontent.com/5024695/70867220-68501400-1f73-11ea-93be-bbc305f1d67b.png)

![2019-12-15-194622_763x529_scrot](https://user-images.githubusercontent.com/5024695/70867234-959cc200-1f73-11ea-9637-f82bc1f87162.png)

In addition to that - backtesting assumes that counterparties (buyers / sellers) are always available ... which may or may not be the case in real trading.

to summarize: i think your trailing stop is way too tight - everything < 1% will almost certainly lead to bad results ... 

> The buy signal gets sent at the same time as the backtesting, but it looks like the asset is getting bought more than 1 minute later, after the end of the next candle!

Please use the jupyter notebook (or sqlite / sqlitebrowser) to open the database - and search for the "real" timestamp of buy. 
I suspect that this could be a problem with plotting trades in 1m timeframe - the open_time will not be xx:01:00 - but xx:01:05 (or similar) - it might be that this is moved to the next candle in the graphic.

also looking at your first live example, it clearly shows that buying at the candle where it's displayed is impossible ... since there was no volume (and the price was never at that rate at all!).

**Comment by yupengoo7** [comment]
hi buddy I got the very result similar to you got, how did you solve it?

**Comment by xmatthias** [comment]
Please don't revivew issues that are 3 years old, thanks. Your issue will almost certainly not be the same - otherwise you'd clearly have to update.
