### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by Mixcoatl5** [freqtrade/freqtrade#2663]
Hey guys,
I was looking into code and in hyperopt_loss_sharpe.py in line 35 I found this:
```
# adding slippage of 0.1% per trade
total_profit = total_profit - 0.0005
```
If I am not mistaken this slippage should be calculated based on `stake_amount` in config.json file. So if I change my `stake_amount` on different amount than 0.05, slippage is calculated badly.

My idea is change line 35 into: `total_profit = total_profit - (total_profit * 0.001)`

I am new to coding so I am not sure if my idea is correct. Please could anybody confirm or disprove this?

**Comment by hroff-1902** [comment]
`total_profit` here is profit expressed as percentage (ratio) of amount, it's not absolute profit in stake currency:
https://github.com/freqtrade/freqtrade/blob/2282f4bd37e7669de87f2d6a1eb2115dc44eaa13/freqtrade/optimize/hyperopt_loss_sharpe.py#L31

So `total_profit - 0.0005` subtracts 0.05% from the profit percentage, not 0.05 of amount.

**Comment by Mixcoatl5** [comment]
> `total_profit` here is profit expressed as percentage (ratio) of amount, it's not absolute profit in stake currency:
> 
> https://github.com/freqtrade/freqtrade/blob/2282f4bd37e7669de87f2d6a1eb2115dc44eaa13/freqtrade/optimize/hyperopt_loss_sharpe.py#L31
> 
> So `total_profit - 0.0005` subtracts 0.05% from the profit percentage, not 0.05 of amount.
> 
> Imho not a bug and anything is correct here...

Ok, thx for explanation
