### ISSUE TITLE
strategy_analysis_example.ipynb ModuleNotFoundError: No module named 'arrow'

### ISSUE THREAD

**Issue by segatrade** [freqtrade/freqtrade#2670]
## Step 1: Have you search for this issue before posting it?
Yes. "strategy_analysis_example" no issues found.

## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04 WSL
  * Python Version: Python 3.6.8 (`python -V`)
  * CCXT version: ccxt==1.18.1306 (`pip freeze | grep ccxt`)
  * Branch: Master
  * Last Commit ID: 15938472032c5eae1b09edbed24151b6b63508cd (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

*strategy_analysis_example.ipynb in # Load data using values set above got an error ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-fd635a5f80a6> in <module>
      1 # Load data using values set above
----> 2 from freqtrade.data.history import load_pair_history
      3 
      4 candles = load_pair_history(datadir=data_location,
      5                             ticker_interval=ticker_interval,

/mnt/c/Users/V2/Documents/freqtrade/freqtrade/freqtrade/data/history.py in <module>
     13 from typing import Any, Dict, List, Optional, Tuple
     14 
---> 15 import arrow
     16 from pandas import DataFrame
     17 

ModuleNotFoundError: No module named 'arrow'*

### Steps to reproduce:

  0. Install by guide. Download data. Run backtest.
 1. Copy strategy_analysis_example.ipynb to project root
  2. Set .env kernel in notebook
  3. Run each cell after cell
  
### Observed Results:

  * What happened?
Error: ModuleNotFoundError: No module named 'arrow'

  * What did you expect to happen?
Notebook is showing results

### Relevant code exceptions or logs:

  ```

Requirement already satisfied: arrow in ./.env/lib/python3.6/site-packages (0.15.2)

  // paste your log here
  ```

**Comment by xmatthias** [comment]
there are only very few possibilities why this can happen.
a) the installation in the virtualenv is incorrect / not correct
b) you're using the wrong kernel / the kernel points to the wrong virtual environment.

You can verify the first point easily as follows:
you activate the virtual environment - open a python shell (`python`) and type `import arrow`.... 
If it fails, then there's something wrong with the installation in the virtual environment.
If that's working correctly, then it's the 2nd point - the kernel is somehow wrong.

In case it's the 2nd point:
From your explanation, it seems you have jupyter installed "natively" - and use different kernels to "hop" to the correct environment?
the easiest solution is to simply install jupyter within the virtual environment - and start the notebook server from within the activated environment. This will remove the problems with activating kernels.

**Comment by segatrade** [comment]
Thank you for your respone

I tried to run it from https://github.com/freqtrade/freqtrade/issues/2500 but get another error there

**Comment by xmatthias** [comment]
To be honest, problems with jupyter (using the wrong kernel for example- which is the most likely cause here) are difficult to solve from our end.

Please either install jupyter within the virtual environment and start it from there (so it should have one kernel - which is the local one) - otherwise please refer to the jupyter documentation or help resources to get help with picking the right kernel.

If freqtrade works if you activate the virtual environment, run `python3` and are able to import it from there, then it's installed correctly.
