### ISSUE TITLE
download-data should take startup_candles into account

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2673]
`freqtrade download-data` should take startup_candles into account. accepting it from the command line and/or from the strategy (also taken either from the cli or config).

So if I download 1d data for default 30 days and startup_candles is set to 20, it should download data for last 50 days (same for other timeframes).

Otherwise, I should either calculate dates and run download data and backtesting with different timeranges (download data starting with the date 50 days (hours, 5m timeframes, etc) and backtesting starting with the date 30 days ago. Or I will get backtesting for only 10 days, because the startup candles will be removed.

**Comment by xmatthias** [comment]
i do tend to disagree... i don't think it's necessary and will lead to confusion. I prefer to exactly specify how much data i download - not "specified" - and then some.

`download-data` is suposed to download data for X days.
It downloads data irrelevant of the strategy (and that's fully on purpose).
You can use the downloaded data once to backtest 100ds of strategies - all will have a different startup time. 

Also, `download-data` is supposed to be run regularily to update / refresh the data with the latest candles. So suppose i downloaded 4 months of backtesting data - and i'm now updating it every week using `--days 14` (to create some overlap should i miss a update...). 


To me, this is a Documentation issue only - adding a note to the download-data section that download-data downloads data for exactly X days - not considering startup period.

**Comment by hroff-1902** [comment]
> `download-data` is suposed to download data for X days.
> It downloads data irrelevant of the strategy (and that's fully on purpose).
> You can use the downloaded data once to backtest 100ds of strategies - all will have a different startup time.

That's why I suppose the startup_candle value should also be specified in the cli option -- the biggest one, irrelevant on the strategy I'm going to backtest later.

Now you have data downloaded for last 90 days, then backtest strategies on 1d timeframe with different startup candles values, and all of them will be backtested for different period -- strategies with startup period 20 will contain backtesting results for last 70 days, while a strategy with startup candles set to 50 will contain results only for 50 days...

For shorter timeframe, like even for 5m, if I use EMA100 and set startup candle value to 100, how do I calculate the number of days I need to download? Will 1 extra day suffice? Why should I actually do these calculations?

Worse for Edge, I'll create a separate issue for it, it requires some more data collected about the behavior of Edge...

> Also, `download-data` is supposed to be run regularily to update / refresh the data with the latest candles. So suppose i downloaded 4 months of backtesting data - and i'm now updating it every week using `--days 14` (to create some overlap should i miss a update...).

It's not for me, for example, I frequently download data for some specific period (using some `--days` to be in the desired period in the past), backtest on different periods during that period of time, and sometimes delete data to save disk space. And simply for cleanup, because I do not know, what data is contained in the files on the disk -- it's easier to re-download them every time I start backtesting again for some new backtesting period...

> To me, this is a Documentation issue only - adding a note to the download-data section that download-data downloads data for exactly X days - not considering startup period.

Yes, maybe. Many issues can be closed by adding appropriate descriptions to the docs.

The current issue is that a user wants to backtest on a period for last 30 days, she is told she has not history data available, so she downloads data with `--days 30` assuming that after this backtesting will be done for this period, but actually backtesting contains results for shorter timerange because of startup candles.

**Comment by xmatthias** [comment]
> Now you have data downloaded for last 90 days, then backtest strategies on 1d timeframe with different startup candles values, and all of them will be backtested for different period -- strategies with startup period 20 will contain backtesting results for last 70 days, while a strategy with startup candles set to 50 will contain results only for 50 days...

but you won't solve this by adding the "largest" startup-candle value.

Assume the largest startup-period is 20 days. - so you specify `--days 90 --su 20` - it'll download 110 days.
You'll still need to specify the backtest data correctly (`20190901-` for example) for the strategy results to be comparable. 

~If you run backtest without `--timerange` since  you assume that you downloaded only the data you need, you again don't have comparable results - since one strategy will use 90 days (the one with 20 days startup period) - but another strategy will use 100 days (startup-period of 10) - or even all 110 days (startup-period of 0).~
^ This is wrong - we do use the maximum startup_candle count IF backtesting is performed using `--strategy-list`. If you use a loop to backtest each strategy indivitually this will not apply - and the above becomes relevant again.

in the end, you did gain nothing over running `download-data --days 110` other than complexity for both the user - who needs to specify an additional argument - and the system, which needs to aggregate the 2 numbers.
