### ISSUE TITLE
List pairs/list markets : add an option to exclude restricted markets

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2677]
Hi,

During automation of downloading bittrex candle i cannot get straight the list of non restricted pairs.

Maybe it can be useful to has an option to exclude restricted markets.

PS : my internet connection is in France,  the geo ip located it in France but bittrex don't give me the restricted markets (do you know why ?) 

Have a nice day.

**Comment by xmatthias** [comment]
not really ... but if you read [here](https://www.reddit.com/r/Bittrex/comments/ay1xqr/whats_up_with_bittrex_restricted_markets/) there's others with similar problems.

you should be able to get the nonrestricted list via the snippet shared in https://github.com/freqtrade/freqtrade/issues/2074#issuecomment-552307926 ... (not sure if it still works...).

This can also serve as a template for "future" implementations of this feature.

**Comment by hroff-1902** [comment]
well, this is the exchange-specific and not necessarily should cause the user orders failed...
how can we handle such pairs?
* add a ft_has flag, which is controllable in the exchange settings, like "ft_has": {'BlacklistRestricted':true}
* add a pairlist filter, BlacklistRestrictedPairListFilter, which will only work for Bittrex...

**Comment by xmatthias** [comment]
pairlists won't apply for `list-pairs` (nor should they ...).

the problem with the restricted pairs is that it's impossible to determine if a user is affected by them automatically.

see also https://github.com/ccxt/ccxt/issues/5624#issuecomment-517907796 - where kroitor confirms that the only possibility to determine if you are affected is to try and create an order when logged in ... which i don't think should be an option for list-pairlist.


On the other hand, i'm not certain if restricting pairs from certain countries is unique to bittrex ... binance kind of does the same (by using binance.us and binance.com) - and i assume most other exchanges will probably have to follow suite - if i remember the current US legislation around this correctly.

**Comment by hroff-1902** [comment]
Yes, I read those comments at ccxt issue...

Yes, it's impossible to determine is the user affected.

But it's possible to filter out such the pairs (using the 'IsRestricted' field in the market structure) and filter those pairs out of whitelist if the user wants to do it -- by parilist, ft_has, or even by an another setting somewhere under 'exchange' settings, if 'ft_has' is not convenient...

**Comment by xmatthias** [comment]
I'm not quite certain how / if we should handle this, other than warning the user that this may be a restricted pair (which we do already).


Even if we were to add a flag for the user to indicate "i'm a restricted one" - it'll still be "at grace" of the exchange to determine this correctly (which apparently, is not working for at least one person in france ...), so the "self-indication" may be wrong - not intentionally, but because the exchange THINKS you are restricted (which unfortunately, is enough to have these pairs to not work).

**Comment by xmatthias** [comment]
as this hasn't come up anymore - and because facts did not change (it's still not possible to reliably determine if the exchange thinks you're a restricted user) - i'll close this as there is nothing we can do to determine this reliably.
