### ISSUE TITLE
download-data validates whitelist when --pairs is used

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2679]
The download-data subcommands validates whitelist when `--pairs` is used:

```
$ freqtrade download-data -c config.json --exchange kraken --pairs BTC/USD -t 1d --days 100 -v
...
2019-12-17 20:07:49,885 - freqtrade - ERROR - Pair NXT/BTC is not available on Kraken. Please remove NXT/BTC from your whitelist.
```

Expected behavior: ignore pair_whitelist, work only with pairs set in the cli.

**Comment by xmatthias** [comment]
A solution to that is not as simple as it looks like ...

the main problem is that we've got 2 versions of the pairlist - `config['pairs']` and `config['exchange']['pair_whitelist']` - both of which can exist at the same time - with different contents.

in theory, we can fix this rather easily by copying `config['pairs']` into pair_whitelist ... but that would change the behaviour of a custom configuration file which specifies both lists (currently regular trading would use 'pair_whitelist' - but in the future it would use 'pairs' instead if that was specified).
