### ISSUE TITLE
What does this mean and how do I fix it?

### ISSUE THREAD

**Issue by dwhe123** [freqtrade/freqtrade#2684]
## Step 1: Have you search for this issue before posting it?

If (.env) dwhee@dwVB:~/freqtrade$ python3 ./freqtrade/main.py -c config.json -s bbrsi
/home/dwhee/freqtrade/.env/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
/home/dwhee/freqtrade/.env/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.metrics.scorer module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)
Fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 42, in main
    config = Configuration(args).get_config()
  File "/home/dwhee/freqtrade/freqtrade/configuration.py", line 299, in get_config
    self.config = self.load_config()
  File "/home/dwhee/freqtrade/freqtrade/configuration.py", line 47, in load_config
    config = self._load_config_file(self.args.config)
  File "/home/dwhee/freqtrade/freqtrade/configuration.py", line 81, in _load_config_file
    conf = json.load(file)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 55 column 11 (char 1429)
you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```

**Comment by hroff-1902** [comment]
`json.decoder.JSONDecodeError: Expecting value: line 55 column 11 (char 1429)`
-- wrong symbol at your config, at line 55 and column 11.

**Comment by dwhe123** [comment]
This is what I have, is it wrong?:
          },
          "pair_whitelist": [
            "ETH/BTC",
            "XRP/BTC",
            "WAVES/BTC",
            "FET/BTC",
            "BNB/BTC",
            "XTZ/BTC",
            "LINK/BTC",
            "LTC/BTC",
            "MATIC/BTC",
            "TOMO/BTC",
            "ATOM/BTC",
            "EOS/BTC",
            "BCH/BTC",
            "XMR/BTC",
            "VET/BTC",
            "THETA/BTC",
            "ZEC/BTC",
            "ENJ/BTC",
         ],    #this  is line 54
          "pair_blacklist": [
              "DOGE/BTC"
        ]
    },

**Comment by xmatthias** [comment]
Json does not allow a list to have a "trailing" colon.


``` json
"ZEC/BTC",
"ENJ/BTC", # <-- Remove this colon ... 
], #this is line 54
"pair_blacklist": [
```

These lines should look as follows:
``` json
"ZEC/BTC",
"ENJ/BTC"
], 
"pair_blacklist": [
```

**Comment by dwhe123** [comment]
That fixed that problem. Now when I run I get this issue:
Traceback (most recent call last):
  File "./freqtrade/main.py", line 45, in main
    freqtrade = FreqtradeBot(config)
  File "/home/dwhee/freqtrade/freqtrade/freqtradebot.py", line 54, in __init__
    self.strategy: IStrategy = StrategyResolver(self.config).strategy
  File "/home/dwhee/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 40, in __init__
    extra_dir=config.get('strategy_path'))
  File "/home/dwhee/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 141, in _load_strategy
    " or contains Python code errors".format(strategy_name)
ImportError: Impossible to load Strategy 'bbrsi'. This class does not exist or contains Python code errors
which file do I need to fix and where in the file? I get confused when it says 4 different references

**Comment by xmatthias** [comment]
well - you need to have a file with a valid strategy class named `bbrsi` (case sensitive) in `user_data/strategies` (or whatever you specified as `--strategy-path`.

**Comment by dwhe123** [comment]
Thank you.

From my_init_ file:
# Import Default-Strategy to have hyperopt correctly resolve
from freqtrade.strategy.default_strategy import DefaultStrategy  # noqa: F401
from freqtrade.strategy.bbrsi import bbrsi
logger = logging.getLogger(__name__)

from my bbrsi.py file:
import talib.abstract as ta
from pandas import DataFrame

import freqtrade.vendor.qtpylib.indicators as qtpylib
from freqtrade.indicator_helpers import fishers_inverse
from freqtrade.strategy.interface import IStrategy


class bbrsi(IStrategy):

Both files are under freqtrade/strategy

**Comment by dwhe123** [comment]
All is resolved. Thank you for all of your help, that is what makes this community so great!
