### ISSUE TITLE
Issue with pip install -e .

### ISSUE THREAD

**Issue by vytautasjar** [freqtrade/freqtrade#2708]
* Operating system: macOS 10.14.6
  * Python Version: 3.7.3

I am getting error when trying to pip install -e . 
There seems to be an issue with py-find-1st
<img width="1120" alt="Screen Shot 2019-12-23 at 6 33 18 PM" src="https://user-images.githubusercontent.com/51506341/71369291-f56a1d00-25b2-11ea-8d05-7a1bfba547c7.png">

**Comment by hroff-1902** [comment]
Would running `xcode-select --install` help?

**Comment by vytautasjar** [comment]
<img width="709" alt="Screen Shot 2019-12-23 at 11 07 46 PM" src="https://user-images.githubusercontent.com/51506341/71380739-147ba580-25d9-11ea-9515-5c7b98107a8e.png">
I reinstalled Xcode command line tools and now I get this error

**Comment by vytautasjar** [comment]
Update, tried pip install -e . one more time and now I'm getting the first error all over again

**Comment by hroff-1902** [comment]
Something more about similar issues (some of the recipes there may help):

* https://stackoverflow.com/questions/58278260/cant-compile-a-c-program-on-a-mac-after-upgrading-to-catalina-10-15/58278392#58278392
* https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave
* https://stackoverflow.com/questions/53792480/installing-mmh3-package-with-pip-on-conda-macos/53862228#53862228

**Comment by vytautasjar** [comment]
The second link worked. Thank you!

**Comment by hroff-1902** [comment]
which one of that stuff suggested there?

**Comment by xmatthias** [comment]
I suspect it's a similar issue to #1675 ... 
but without a mac i've never been able to confirm if we should document that as it's a common issue, or if it needs certain prerequisites on a mac to happen first to apply.

**Comment by vytautasjar** [comment]
> which one of that stuff suggested there?

Running:   
`open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`
