### ISSUE TITLE
More than one  indicator is not found in your strategy when i try to run my mine 

### ISSUE THREAD

**Issue by 7baughj** [freqtrade/freqtrade#2713]
Hi,

When I  run this following command freqtrade plot-dataframe --strategy BBRSI -p ETH/BTC --indicators1 lowerbb, middlebb, upperbb   --indicators2 rsi

I get the following  info message :
freqtrade.plot.plotting - INFO - Indicator "lowerbb," ignored. Reason: This indicator is not found in your strategy.
- freqtrade.plot.plotting - INFO - Indicator "middlebb," ignored. Reason: This indicator is not found in your strategy.
 freqtrade.plot.plotting - INFO - Indicator "upperbb" ignored. Reason: This indicator is not found in your strategy.

 Also added my trading script bellow 

import talib.abstract as ta
from pandas import DataFrame

import freqtrade.vendor.qtpylib.indicators as qtpylib
from freqtrade.strategy.interface import IStrategy

class BBRSI(IStrategy):
    """
    Default Strategy provided by freqtrade bot.
    Please do not modify this strategy, it's  intended for internal use only.
    Please look at the SampleStrategy in the user_data/strategy directory
    or strategy repository https://github.com/freqtrade/freqtrade-strategies
    for samples and inspiration.
    """
    INTERFACE_VERSION = 2

    # Minimal ROI designed for the strategy
    minimal_roi = {

    }

    # Optimal stoploss designed for the strategy
    stoploss = -0.10

    # Optimal ticker interval for the strategy
    ticker_interval = '1h'

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 20

    def informative_pairs(self):
        """
        Define additional, informative pair/interval combinations to be cached from the exchange.
        These pair/interval combinations are non-tradeable, unless they are part
        of the whitelist as well.
        For more information, please consult the documentation
        :return: List of tuples in the format (pair, interval)
            Sample: return [("ETH/USDT", "5m"),
                            ("BTC/USDT", "15m"),
                            ]
        """
        return []

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Adds several different TA indicators to the given DataFrame

        Performance Note: For the best performance be frugal on the number of indicators
        you are using. Let uncomment only the indicator you are using in your strategies
        or your hyperopt configuration, otherwise you will waste your memory and CPU usage.
        :param dataframe: Raw data from the exchange and parsed by parse_ticker_dataframe()
        :param metadata: Additional information, like the currently traded pair
        :return: a Dataframe with all mandatory indicators for the strategies
        """

        # RSI
        dataframe['rsi'] = ta.RSI(dataframe)

        # Bollinger bands
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=5)
        dataframe['lowerbb'] = bollinger['lower']
        dataframe['middlebb'] = bollinger['mid']
        dataframe['upperbb'] = bollinger['upper']

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                (dataframe['RSI'] >= 40) &
                (dataframe["close"] =< dataframe['lowerbb'])
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the sell signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                 ( (dataframe["close"] => dataframe['middlebb'] )
            ),
            'sell'] = 1

        return dataframe

any help would be appreciated

Baugh

**Comment by xmatthias** [comment]
it's right, `lowerbb,` is not part of your indicators.
it's a space-seperated list you need to pass in, not comma + space seperated

Please try the below:

```
freqtrade plot-dataframe --strategy BBRSI -p ETH/BTC --indicators1 lowerbb middlebb upperbb --indicators2 rsi
```

**Comment by 7baughj** [comment]
Thank you for getting back to me quickly,

unfortunately, I have the same errors.

**Comment by xmatthias** [comment]
first of all -it should have generated a plot under `/home/baugh/freqtrade/user_data/plot/freqtrade-plot-ETH_BTC-1h.html`.

Then you should make sure that the file `/home/baugh/freqtrade/user_data/strategies/bbrsi.py` is the correct file. maybe you have the same class name (BBRSI) in 2 files - and freqtrade is not using the strategy from the file you think it should.


A side note:
if you use `bb_lowerband` and `bb_upperband` as Bollingerband names, the plot will show a real band - otherwise it'll just be rendered as 2 lines.

**Comment by 7baughj** [comment]
I rename Bollinger band names and I found another strategy with the same name but in a different location  

Thank you for your time,
