### ISSUE TITLE
Docker- telegram webhook conflict

### ISSUE THREAD

**Issue by sanket-k** [freqtrade/freqtrade#2715]
## Step 1: Have you search for this issue before posting it?
Yes, i haven't been able to find a similar issue raised before.

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Amazon Linux 2017.09
  *  docker container running on AWS Fargate 
  * allocated resources: 2GB ram 2 vcpus.
  * build as on 05-12-2019
  * Python Version: 3.7.6 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:
With Telegram and webhook(for alerts on an other platform) enabled the bot seemed to have entered a loop. 
I would like to understand what went wrong and if it can be avoided next time.
Also is it necessary to turn telegram off in order to receive updates from webhooks or are the independent of each other ??

### Steps to reproduce:

  1. https://www.freqtrade.io/en/latest/docker/ (exact steps followed till the docker container was built with different config and strategy file)
  2. uploaded to ECR
  3. deployed on AWS Fargate 
  
### Observed Results:

  * Expected: For bot to buy and sell asset with updates on telegram and another platform(e.g discord) 
  * Observed: The bot seemed to have been in a loop when checked several hours later as telegram "/status" requests were unresponsive.

### Relevant code exceptions or logs:

```
2019-12-05 23:23:45,580 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=1
2019-12-05 23:24:50,612 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=1
2019-12-05 23:25:55,639 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=1
2019-12-05 23:27:00,670 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=1
2019-12-05 23:28:05,711 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=1
2019-12-05 23:29:10,760 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=1
2019-12-05 23:30:15,792 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=1
2019-12-05 23:31:20,833 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=1
2019-12-05 23:32:25,885 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=1
2019-12-05 23:33:09,667 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by setWebhook request
2019-12-05 23:33:09,667 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
if not action_cb():
File "/usr/local/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
allowed_updates=allowed_updates)
File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
result = func(self, *args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 1983, in get_updates
result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
**urlopen_kwargs)
File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by setWebhook request
2019-12-05 23:33:13,751 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2019-12-05 23:33:13,752 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
if not action_cb():
File "/usr/local/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
allowed_updates=allowed_updates)
File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
result = func(self, *args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 1983, in get_updates
result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
**urlopen_kwargs)
File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2019-12-05 23:33:15,336 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2019-12-05 23:33:15,336 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/telegram/ext/updater.py", line 332, in _network_loop_retry
if not action_cb():
File "/usr/local/lib/python3.7/site-packages/telegram/ext/updater.py", line 293, in polling_action_cb
allowed_updates=allowed_updates)
File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
result = func(self, *args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 1983, in get_updates
result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
**urlopen_kwargs)
File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2019-12-05 23:33:20,673 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2019-12-05 23:33:20,673 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
```

**Comment by xmatthias** [comment]
I don't think this has to do with freqtrade itself.

The message is comming from the telegram library - and searching for that message suggests that you may have been running 2 bots (freqtrade or something else) with the same telegram token (?).
You'll need one token per freqtradebot instance.

The alternative is that freqtrade was forcefully shutdown (pressing ctrl+c multiple times or killing the docker container) so the telegram library did not properly close and telegram now thinks that the "other" instance is still listening. Waiting a bit before restarting should fix it in this case.

**Comment by sanket-k** [comment]
It was a docker container with only freqtrade and nothing else,
About the telegram bot part, i had changed the chat id to a group chat e.g (-55387638) would sending updates to the group may have created the issue ??

rite, about AWS Fargate, as per my understanding, if the instance(container)  crashes/dies Fargate automatically restarts it.

Could you elaborate the "dangerous" part, i would like to understand the problems a bit more,

about the persistence(still looking it up) i was thinking about updating the db file to a s3 bucket at timed intervals.

**Comment by xmatthias** [comment]
> would sending updates to the group may have created the issue ??

Never tested running it against a group ... but assuming you're not the only person in that group, you'll be granting access to the whole group to start/stop/buy(if enabled)/sell with your bot / your money - so that's most likely not what you'll want anyway.

> Could you elaborate the "dangerous" part, i would like to understand the problems a bit more

Well the way i understand Fargate (never used it, heared about it the first time today) - it's basically "just" a container runtime.
however the container does run on physical (well, virtual, most likely) server. So the container may be spun up on another server by the system without any action from your side (maybe that physical server needed a reboot, or had a problem, ...).
Once that new container is up and running, it'll spin down the old container.

The problem with that is that both instances would point to the same persistence for a limited amount of time.
If during that time, a buy / sell action happens, the persistence is either updated twice - or the asset is sold twice (you only own it once!) ... which will lead to errors which will be almost impossible to detect afterwards unless fargate offers clear logs about these actions.

> about the persistence(still looking it up) i was thinking about updating the db file to a s3 bucket at timed intervals.

That may be dangerous when running in production. Assume the bot has a problem  5 minutes after buying - the "new" instance would never know the trade happened, since the new bot will have the "last sync" version of the database. 
No matter what time you use for the sync, the problem will remain (you won't want to sync it every second ... ).

maybe it allows you to mount an S3 bucket to the container ... so it's "always" uptodate.

Apart from that, maybe an external database (non sqlite) would be the solution - i think AWS offers managed postgres or mysql.

**Comment by sanket-k** [comment]
> Apart from that, maybe an external database (non sqlite) would be the solution - i think AWS offers managed postgres or mysql.

I think that is good suggestion, i would try an implementation and update if successful, thanks

i'll be closing the issue for now, will reopen if i come across the similar issue, thanks for the clarity

**Comment by xmatthias** [comment]
>  i would try an implementation

it's technically implemented in freqtrade (not in your container, obviously) - you just need to add the necessary dependencies (`psycopg2-binary` for postgres) , and construct the [sqlalchemy url](https://docs.sqlalchemy.org/en/13/core/engines.html#database-urls) ... that's the beauty of sqlalchemy ...

**Comment by sanket-k** [comment]
> it's technically implemented in freqtrade

I was unaware, nice..lots to explore, i'll look it up , thanks for the share.

**Comment by sanket-k** [comment]
hi, i seem to have faced the same issue again, this seems to be repeating only when the telegram and webhook module are enabled simultaneously, could you suggest a work around ?

``` 
{"log":"2020-01-06 01:46:01,848 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=1\n","stream":"stderr","time":"2020-01-06T01:46:01.848500344Z"}
{"log":"2020-01-06 01:46:07,143 - freqtrade.freqtradebot - INFO - No currency pair in active pair whitelist, but checking to sell open trades.\n","stream":"stderr","time":"2020-01-06T01:46:07.143876512Z"}
{"log":"2020-01-06 01:46:11,849 - freqtrade.freqtradebot - INFO - No currency pair in active pair whitelist, but checking to sell open trades.\n","stream":"stderr","time":"2020-01-06T01:46:11.85002352Z"}
{"log":"2020-01-06 01:46:16,851 - freqtrade.freqtradebot - INFO - No currency pair in active pair whitelist, but checking to sell open trades.\n","stream":"stderr","time":"2020-01-06T01:46:16.851820033Z"}
{"log":"2020-01-06 01:46:22,147 - freqtrade.freqtradebot - INFO - No currency pair in active pair whitelist, but checking to sell open trades.\n","stream":"stderr","time":"2020-01-06T01:46:22.147661334Z"}
{"log":"2020-01-06 01:46:26,861 - freqtrade.freqtradebot - INFO - No currency pair in active pair whitelist, but checking to sell open trades.\n","stream":"stderr","time":"2020-01-06T01:46:26.861819548Z"}
{"log":"2020-01-06 01:46:31,868 - freqtrade.freqtradebot - INFO - No currency pair in active pair whitelist, but checking to sell open trades.\n","stream":"stderr","time":"2020-01-06T01:46:31.86865795Z"}
{"log":"2020-01-06 01:46:36,871 - freqtrade.freqtradebot - INFO - No currency pair in active pair whitelist, but checking to sell open trades.\n","stream":"stderr","time":"2020-01-06T01:46:36.871872922Z"}
{"log":"2020-01-06 01:46:41,877 - freqtrade.freqtradebot - INFO - No currency pair in active pair whitelist, but checking to sell open trades.\n","stream":"stderr","time":"2020-01-06T01:46:41.87745593Z"}
{"log":"2020-01-06 01:46:46,882 - freqtrade.freqtradebot - INFO - No currency pair in active pair whitelist, but checking to sell open trades.\n","stream":"stderr","time":"2020-01-06T01:46:46.883133958Z"}
{"log":"2020-01-06 01:46:51,856 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by setWebhook request\n","stream":"stderr","time":"2020-01-06T01:46:51.856584687Z"}
{"log":"2020-01-06 01:46:51,856 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n","stream":"stderr","time":"2020-01-06T01:46:51.864863673Z"}
{"log":"Traceback (most recent call last):\n","stream":"stderr","time":"2020-01-06T01:46:51.864877751Z"}
{"log":"  File \"/usr/local/lib/python3.7/site-packages/telegram/ext/updater.py\", line 332, in _network_loop_retry\n","stream":"stderr","time":"2020-01-06T01:46:51.864882451Z"}
{"log":"    if not action_cb():\n","stream":"stderr","time":"2020-01-06T01:46:51.864886932Z"}
{"log":"  File \"/usr/local/lib/python3.7/site-packages/telegram/ext/updater.py\", line 293, in polling_action_cb\n","stream":"stderr","time":"2020-01-06T01:46:51.864890821Z"}
{"log":"    allowed_updates=allowed_updates)\n","stream":"stderr","time":"2020-01-06T01:46:51.864895035Z"}
{"log":"  File \"/usr/local/lib/python3.7/site-packages/telegram/bot.py\", line 66, in decorator\n","stream":"stderr","time":"2020-01-06T01:46:51.86489902Z"}
{"log":"    result = func(self, *args, **kwargs)\n","stream":"stderr","time":"2020-01-06T01:46:51.864903174Z"}
{"log":"  File \"/usr/local/lib/python3.7/site-packages/telegram/bot.py\", line 1983, in get_updates\n","stream":"stderr","time":"2020-01-06T01:46:51.864907006Z"}
{"log":"    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n","stream":"stderr","time":"2020-01-06T01:46:51.864911373Z"}
{"log":"  File \"/usr/local/lib/python3.7/site-packages/telegram/utils/request.py\", line 327, in post\n","stream":"stderr","time":"2020-01-06T01:46:51.864915346Z"}
{"log":"    **urlopen_kwargs)\n","stream":"stderr","time":"2020-01-06T01:46:51.864919353Z"}
{"log":"  File \"/usr/local/lib/python3.7/site-packages/telegram/utils/request.py\", line 242, in _request_wrapper\n","stream":"stderr","time":"2020-01-06T01:46:51.864923134Z"}
{"log":"    raise Conflict(message)\n","stream":"stderr","time":"2020-01-06T01:46:51.864927201Z"}
{"log":"telegram.error.Conflict: Conflict: terminated by setWebhook request\n","stream":"stderr","time":"2020-01-06T01:46:51.864930996Z"}
{"log":"2020-01-06 01:46:51,880 - freqtrade.freqtradebot - INFO - No currency pair in active pair whitelist, but checking to sell open trades.\n","stream":"stderr","time":"2020-01-06T01:46:51.880249099Z"}
{"log":"2020-01-06 01:46:55,938 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first\n","stream":"stderr","time":"2020-01-06T01:46:55.939543084Z"}
{"log":"2020-01-06 01:46:55,939 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n","stream":"stderr","time":"2020-01-06T01:46:55.939570584Z"}
{"log":"Traceback (most recent call last):\n","stream":"stderr","time":"2020-01-06T01:46:55.93958878Z"}
{"log":"  File \"/usr/local/lib/python3.7/site-packages/telegram/ext/updater.py\", line 332, in _network_loop_retry\n","stream":"stderr","time":"2020-01-06T01:46:55.93959304Z"}
{"log":"    if not action_cb():\n","stream":"stderr","time":"2020-01-06T01:46:55.939596764Z"}
{"log":"  File \"/usr/local/lib/python3.7/site-packages/telegram/ext/updater.py\", line 293, in polling_action_cb\n","stream":"stderr","time":"2020-01-06T01:46:55.93960015Z"}
{"log":"    allowed_updates=allowed_updates)\n","stream":"stderr","time":"2020-01-06T01:46:55.939603739Z"}
{"log":"  File \"/usr/local/lib/python3.7/site-packages/telegram/bot.py\", line 66, in decorator\n","stream":"stderr","time":"2020-01-06T01:46:55.939607224Z"}
{"log":"    result = func(self, *args, **kwargs)\n","stream":"stderr","time":"2020-01-06T01:46:55.939610819Z"}
{"log":"  File \"/usr/local/lib/python3.7/site-packages/telegram/bot.py\", line 1983, in get_updates\n","stream":"stderr","time":"2020-01-06T01:46:55.939614324Z"}
{"log":"    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n","stream":"stderr","time":"2020-01-06T01:46:55.939617884Z"}
{"log":"  File \"/usr/local/lib/python3.7/site-packages/telegram/utils/request.py\", line 327, in post\n","stream":"stderr","time":"2020-01-06T01:46:55.939621491Z"}
{"log":"    **urlopen_kwargs)\n","stream":"stderr","time":"2020-01-06T01:46:55.939625048Z"}
{"log":"  File \"/usr/local/lib/python3.7/site-packages/telegram/utils/request.py\", line 242, in _request_wrapper\n","stream":"stderr","time":"2020-01-06T01:46:55.939628397Z"}
{"log":"    raise Conflict(message)\n","stream":"stderr","time":"2020-01-06T01:46:55.939632068Z"}
{"log":"telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first\n","stream":"stderr","time":"2020-01-06T01:46:55.939635501Z"}
{"log":"2020-01-06 01:46:56,892 - freqtrade.freqtradebot - INFO - No currency pair in active pair whitelist, but checking to sell open trades.\n","stream":"stderr","time":"2020-01-06T01:46:56.892805193Z"}
{"log":"2020-01-06 01:46:57,521 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first\n","stream":"stderr","time":"2020-01-06T01:46:57.521903094Z"}
```

**Comment by xmatthias** [comment]
Nothing in the errors suggests that it's related to the usage of freqtrade webhooks, unless you're using webhooks to push updates to telegram - which i doubt would work ...

Yes, the message contains webhook in it's name / error - but it's comming from the telegram library (actually from telegram servers, which return a 400 error) - not from freqtrade, and is therefore not related to webhook.


If you search for the error on google (try: `telegram Conflict: can't use getUpdates method while webhook is active (409)`) you'll find multiple occurances.

For example 
https://github.com/telegraf/telegraf/issues/475
or 
https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot/issues/72

While both are different libraries, especially the 2nd one shows where the error is comming from - which is reuse of the same tocken bot somewhere else, with a system which uses webhooks instead of get_updates to get data from the telegram bot.

Please make sure you're using a telegram bot dedicated to freqtrade (not used for something else).
If you're not sure about that best register a new telegram bot which you'll not reuse for anything else.

**Comment by sanket-k** [comment]
> The mostlikely cause is that the bot is "old" - and another system had it configured to use webhooks.

As i am aware i think i have not used it for anything other than freqtrade.

> If you're not sure about that best register a new telegram bot which you'll not reuse for anything else to make sure this error disappears.

Yeah thats a good suggestion, i will try this and update if i encounter the same issue

> telegraf/telegraf#475
witnessmenow/Universal-Arduino-Telegram-Bot#72

Thanks for the mention, i'll try to look around for possible fixes, and if possible find a work around and update.

**Comment by xmatthias** [comment]
Does it now work, using a new telegram bot?

**Comment by sanket-k** [comment]
Yes, its been up for a week now, noticed no issues so far, mostly i think it was due to the old bot, will closely monitor the bot and reopen issue, if faced again.

Will be closing the issue now, thanks for the help.
