### ISSUE TITLE
Backtest exchange fees?

### ISSUE THREAD

**Issue by djacky** [freqtrade/freqtrade#2738]
Binance has a trading fee of 0.1% per trade...so when I do a backtest,  which commands do I input in freqtrade: `freqtrade backtesting --fee 0.001` or `freqtrade backtesting --fee 0.1` ?

**Comment by xmatthias** [comment]
As the help specifies:
```
  --fee FLOAT           Specify fee ratio. Will be applied twice (on trade entry and exit).

```

it's a ratio - so it's `--fee 0.001`.
However, it's an unnecessary step, since freqtrade fetches the fees from the exchange (the default fee, not respecting any tiers or rebates) - so for binance, it'll already use 0.001 as fee. 
It'll also know that for kraken it's 0.0016 ... (for example).

**Comment by djacky** [comment]
Thanks @xmatthias ! I was just confused because on the freqtrade website on backtesting ([https://www.freqtrade.io/en/latest/backtesting/](url)), it stating the following: 

> To account for this in backtesting, you can use --fee 0.001 to supply this value to backtesting. **This fee must be a percentage**, and will be applied twice (once for trade entry, and once for trade exit).

**Comment by xmatthias** [comment]
On the other hand, it also states

> Supplying custom fee value
Sometimes your account has certain fee rebates (fee reductions starting with a certain account size or monthly volume), which are not visible to ccxt. To account for this in backtesting, you can use --fee 0.001 to supply this value to backtesting

but you're right, the term "percentage" is wrong in this regards.

**Comment by hroff-1902** [comment]
It's percentage, with the setting value written in the form of ratio.
😆

**Comment by hroff-1902** [comment]
@djacky the docs was updated, pls review: 
https://www.freqtrade.io/en/latest/backtesting/#supplying-custom-fee-value

**Comment by djacky** [comment]
@hroff-1902 Right before `freqtrade backtesting --fee 0.001`, I would just add the following:

For example, if the buying and selling commission fee is 0.1% per trade, then you would implement the following:
