### ISSUE TITLE
systemd enable / virtualenv activation on vps. 

### ISSUE THREAD

**Issue by fernandobender** [freqtrade/freqtrade#2743]
## Step 1: Have you search for this issue before posting it?
yes

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: ubuntu 18.04
  * Python Version: python 3.7.3
  * CCXT version: 1.20.46
  * Branch: Master
  * Last Commit ID: 7c53dcb0afd2ad663faad4bc03406f0575c87f6b
  
## Step 3: Describe the problem:
i'm willing to put freqtrade as a systemd service to ensure it restarts after reboot. i believe "sudo systemd enable freqtrade.service" should work, but i can't see how it'll run "source .env/bin/activate" command, first. perhaps i should point ExecStart to a .sh file on /freqtrade folder that does that?

*Explain the problem you have encountered*
n/a

**Comment by xmatthias** [comment]
well you don't need to run `source .env/bin/activate`, you'll "just" need the correct path to the freqtrade binary.

The best way to get this:
``` bash
# Activate virtual environment
source .env/bin/activate

which freqtrade
```

The output of `which freqtrade` should show you a path similar to this:
`/home/user/freqtrade/.env/bin/freqtrade` (details may vary).
You'll then use this as `ExecStart` parameter - and freqtrade will run within the virtual environment.

**Comment by fernandobender** [comment]
thank you, @xmatthias. it solved the restart problem.

**the problem now is as follows**
FT, as if, forgets previous trades at reboot.
for instance, i'm on dry run mode, simple EMA Cross strategy.
crossed above, buys; crossed below, sells.

when i reboot the server, FT starts by buying in 5 of my 5 pairs, while max trade is set to 6.
so, /count (telegram bot command) results always in 5, thus clearly ignoring previous buys 5min ago, before the last restart.

this same install was previously running ok,
installed from easy setup (not the docker install, the quick install steps).
it was running through virtual env activation through tmux.
of course, it had no restart on reboot feature, so i went on and tried the systemd solution, to rely on "systemctl --user enable freqtrade.service"
freqtrade.service is located on /etc/systemd/user

**Comment by hroff-1902** [comment]
> FT, as if, forgets previous trades at reboot.
> for instance, i'm on dry run mode, simple EMA Cross strategy.
> crossed above, buys; crossed below, sells.
> 
> when i reboot the server, FT starts by buying in 5 of my 5 pairs, while max trade is set to 6.
> so, /count (telegram bot command) results always in 5, thus clearly ignoring previous buys 5min ago, before the last restart.

This behavior was changed couple of weeks ago, see #2699 for details.
It's now available in the develop branch, will be included in the next release.
In the meantime, simply specify a db file either in the cli options or in the config.

**Comment by hroff-1902** [comment]
Let's close this issue if the original question was resolved. Pls create new issues for new questions that are not directly related to the original post. Otherwise noone will understand what this issue was about and which part of it is still open or indicate a problem that need to be resolved.
