### ISSUE TITLE
GPUs for hyperopt

### ISSUE THREAD

**Issue by Ta1aSuM** [freqtrade/freqtrade#2754]
Hello guys, 
What I want to ask is not related to an real issue, but I have searched on the net for it, and didn't find anything as info. So my question is: can, or is going to be possible in future versions for the GPUs to be used when optimization is performed by  hyperopt?
Thank you in advance for your reply!

**Comment by xmatthias** [comment]
Hi, 

Well, hyperopt uses scikit-optimize and scikit-learn under the hood.

To quote the docs from scikit-learn:
> No, or at least not in the near future. The main reason is that GPU support will introduce many software dependencies and introduce platform specific issues. scikit-learn is designed to be easy to install on a wide variety of platforms. Outside of neural networks, GPUs don’t play a large role in machine learning today, and much larger gains in speed can often be achieved by a careful choice of algorithms.

[source](https://scikit-learn.org/stable/faq.html#will-you-add-gpu-support)

**Comment by xmatthias** [comment]
Will close this now as i think the above link explains our thoughts on this sufficiently.

Feel free to reopen if you still got questions regarding this.
