### ISSUE TITLE
USD pairs in Binance not recognized by freqtrade

### ISSUE THREAD

**Issue by noahfigueras** [freqtrade/freqtrade#2758]
## Step 1: Have you search for this issue before posting it?
Yes 
If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: __Linux Ubuntu 18.6__
  * Python Version: _____ (`python -3`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:
Hi there, I am currently trying to trade with binance US with USD as stake currency and the bot is not recognizing any of the USD pairs in the exchange. There is any way I can make this work as I am trying to trade with USD pairs ?
* I tried to update the pair_whitelist and also using the dynamic whitelist of the exchange and it does not recognize any of the pairs.

It happens with all pairs.

Regards,
*Explain the problem you have encountered*

### Steps to reproduce:

  1. Connect API Binance 
  2. Change stake currency to USD
  3. Run bot in dry_run mode 
  
### Observed Results:

  * What happened? Bot does not recognize USD pairs

  * What did you expect to happen? Trade with USD pairs

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```
2020-01-10 12:34:12,934 - freqtrade - ERROR - Pair ALGO/USD is not available at BinancePlease remove ALGO/USD from your whitelist.

**Comment by hroff-1902** [comment]
There is no pairs at Binance with USD as quote currency. You can see this:
```
$ freqtrade list-pairs --exchange binance --quote USD --all
$ freqtrade list-pairs --exchange binance --all
```

There are ALGO/TUSD, ALGO/USDC and ALGO/USDT. Please also note the ALGO/USDC pair is not active so cannot be traded.

**Comment by hroff-1902** [comment]
Upd: you should use 'binanceus' as the exchange name. It does have pairs for USD quote currency.

**Comment by noahfigueras** [comment]
Awesome, just changed the exchange name to ''binanceus" and solved my problem.

Thanks for your help @hroff-1902

**Comment by hroff-1902** [comment]
Fine. Binance and Binance US are two different exchanges under the Binance umbrella.
They split the US part due to regulatory issues.

**Comment by elijahmurray** [comment]
I'm having this issue even using `binanceus` as my exchange.

**Comment by xmatthias** [comment]
@elijahmurray you will most likely not have the same issue. Also, highjacking an issue that's a year old is bad practice - as it will notify everyone in this issue (i'll therefore lock this issue now).

Best use the commands provided in https://github.com/freqtrade/freqtrade/issues/2758#issuecomment-573201108 with `binanceus` to see what's available, and in case of problems, raise an issue containing your logs, and details of your environment so we can have a look at it in detail.
