### ISSUE TITLE
setup.sh suggests to run invalid command

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2773]
`./setup.sh -i` suggests at the end:
```
-------------------------
Run the bot !
-------------------------
You can now use the bot by executing 'source .env/bin/activate; freqtrade trade'.
```

While `freqtrade trade` is not a valid command, a strategy should be supplied.

Should we suggest `--strategy DefaultStrategy`? Or `--strategy SampleStrategy`?

Or probably suggest to create a new custom strategy with the `new-strategy` subcommand?

**Comment by xmatthias** [comment]
well right after installing, running `freqtrade trade` is hardly the right command, unless you're reinstalling and know what you're doing / going to do.

I wouldn't print the whole documentation here ... coz in theory, this can be a valid command (assuming config.json exists and contains a "strategy" key.
If you add `--strategy` - then why not `--user-data-dir` - and why not `--strategy-path` ... (you see where i'm going with this ...).

Ideally, i'd like to get rid of this install script (as i've mentioned numerous times before) ... Touching peoples system modules by "guessing" the OS may be problematic on it's own right ... and the configuration possibilities using `sed` are very limited...


As a short-term alternative - we could run `freqtrade trade --help` here ... that would show that it installed - + show all options.
