### ISSUE TITLE
How can stake_amount be set by the strategy?

### ISSUE THREAD

**Issue by kinkalias** [freqtrade/freqtrade#2776]
In the configuration file (config.json) the required parameter _stake_amount_ has to be set to a fixed number or to _unlimited_. 

How can I make _stake_amount_ a variable parameter set by the strategy? 

The idea is to use bigger stake amount on high-volume pairs and smaller stake amount on low-volume pairs.

**Comment by xmatthias** [comment]
I don't think that's a particularily good approach, as it's still a static list.

To me, this should be a function / property called within the strategy right before opening the trade - which defaults to returning the configured `"stake_amount"` from config / strategy.

You can still use this list within the function if that's the desire - but in the end, the most usefull will be to have "some" way to calculate this based on everyones own immagination. 

Maybe based on todays volume vs. yesterdays volume, maybe based on asset price (more for higher priced, less for lower prieced) ... but in the end, its up to every single one to come up with something (if you want to use this, anyway).

**Comment by hroff-1902** [comment]
closing it since we have the main issue with discussion wrt position management: #2183
