### ISSUE TITLE
The first buy signal ins't the first buy trade in single pair excecution.

### ISSUE THREAD

**Issue by freskpe** [freqtrade/freqtrade#2777]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04
  * Kernel: 5.4.11-050411
  * Python Version: 3.7.4
  * CCXT version: 1.21.22
  * Branch: Develop
  * Last Commit ID: 2f82122fc40caf428d48f7ab942c8dc49c3ee8f1
  
## Step 3: Describe the problem:

   The first buy signal isn't the first buy trade in single pair excecution.

### Steps to reproduce:

  1. Execute a only pair in bactesting mode 
  2. Plot the dataframe 
  3. Open plot in the browser.
  
### Observed Results:

  * What happened?
     R: The first buy signal ins't the first buy trade, only one pair is set and the maximun open 
          trade is 100.
  * What did you expect to happen?
    R: The first buy signal is the first buy trade.

![newplot](https://user-images.githubusercontent.com/24432922/72665953-c7c29900-39e3-11ea-9888-40edac3e16e6.png)

**Comment by xmatthias** [comment]
I've just tried to recreate this with 3 strategies i had lying around and was unable to reproduce - so it doesn't seem to happen with everything / every strategy.

Therefore, well we'll need a few things to recreate this:

* timeframe used (5m / 15m / 1h / ...)
* exact timeperiod used
* pair and exchange used (i assume it's ZEC/BTC - but from which exchange?)
* strategy used (you can also share that privately via slack (or private message here) if you don't feel comfortable to share it publicly)

**Comment by freskpe** [comment]
> I've just tried to recreate this with 3 strategies i had lying around and was unable to reproduce - so it doesn't seem to happen with everything / every strategy.
> 
> Therefore, well we'll need a few things to recreate this:
> 
> * timeframe used (5m / 15m / 1h / ...)
> * exact timeperiod used
> * pair and exchange used (i assume it's ZEC/BTC - but from which exchange?)
> * strategy used (you can also share that privately via slack (or private message here) if you don't feel comfortable to share it publicly)

Sorry! i'm currently doing some changes in the strategy, however i will share actual strategy where i'm experiency son similar problem but some signal after the las sell trade. 

timeframe = 5m
![newplot-1](https://user-images.githubusercontent.com/24432922/72671959-dbdcb980-3a28-11ea-928b-bc748aa31683.png)

timerange=20190707-20190907
exchange = binance
pair = ZEC/BTC


def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                #(dataframe["rsi"] < 60) &
                #(dataframe['slowk'] <= 25) &

                ((dataframe['bb_diff'] > dataframe['bb_diff'].rolling(10).mean() * 2) &
                (dataframe['volume'] > dataframe['volume'].rolling(10).mean() * 3) &
                (dataframe['volume'] > 0) &
                (dataframe['volume'].shift(1) > 0 ))
                &  ####################### CONDICION AND ######################
                (
                (qtpylib.crossed_above(dataframe["close"] , dataframe["bb_lowerband"]))
                 |  ###################### CONDICION OR #######################
                qtpylib.crossed_above(dataframe["close"] , dataframe["bb_upperband"])
                 )



            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the sell signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                #(dataframe["rsi"] > 65) &
                #(dataframe['slowk'] <= 28) &

                ((dataframe['bb_diff'] > (dataframe['bb_diff'].rolling(10).mean() * 1.5)) &

                (dataframe['volume'] > 0) &
                (dataframe['volume'].shift(1) > 0 ))
                &  ####################### CONDICION AND ######################
                (
                #((dataframe["close"].shift(1) < dataframe["bb_lowerband"]) &
                #(dataframe["close"] > dataframe["bb_lowerband"]))
                # |  ###################### CONDICION OR #######################
                qtpylib.crossed_above(dataframe["bb_middleband"] , dataframe["close"])
                 )

            ),
            'sell'] = 1
        return dataframe

**Comment by freskpe** [comment]
i'm thinking that could be a error in my strategy file but i dont know how to fix it!

Thank you in advance!

**Comment by xmatthias** [comment]
To fully recreate this: how is `bb_diff` calculated? (i assume the rest is a regular BollingerBand).

**Comment by freskpe** [comment]
You right! was my bad don't use timerange in dataframe-plot.

Thank you very much.
