### ISSUE TITLE
Empty sub-folders in user_data

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2778]
Why are all sub-folders in user_data empty?

**Comment by xmatthias** [comment]
As pointed out in the [documentation](https://www.freqtrade.io/en/latest/installation/#5-initialize-the-configuration):

```
# Initialize the user_directory
freqtrade create-userdir --userdir user_data/
```

**Comment by gitgitgat** [comment]
ah, ok
