### ISSUE TITLE
How i can check if a pair have an open trade in the populate_buy function?

### ISSUE THREAD

**Issue by freskpe** [freqtrade/freqtrade#2784]
Hello and sorry, this isn't a issue.

I want to verify if a pair have an open trade at moment to check buy or sell condition. How i can do this?

**Comment by xmatthias** [comment]
This is not clear to me ... when / where would you like to do this?

You can [query the database](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-trades) (also using the shortcut `Trade.get_open_trades()`) to get all open trades... 

However, due to the nature of how backtesting works, this will NOT work for backtesting at all.

**Comment by freskpe** [comment]
> This is not clear to me ... when / where would you like to do this?
> 
> You can [query the database](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-trades) (also using the shortcut `Trade.get_open_trades()`) to get all open trades...
> 
> However, due to the nature of how backtesting works, this will NOT work for backtesting at all.

I want to do it when i check conditions to create a buy or sell signals for example: 

` indicatorA > xx & 
  indicatorB < yy & 
  openTrade = True
`

i need that verification work in the live and backtesting.

**Comment by hroff-1902** [comment]
in principle, you do not need it -- if the pair has a trade open, then the 'buy' signals in the 'buy' column will not produce new trade for same pair, so you can think of it like it's ignored. Same for the 'sell' conditions -- if the pair does not contain open trades, then the sell signal in the 'sell' column won't produce any sells till the pair is bought...

The Freqtrade's 'sell' and 'buy' is closer to 'open position'/'close position' in this sence...

**Comment by freskpe** [comment]
> in principle, you do not need it -- if the pair has a trade open, then the 'buy' signals in the 'buy' column will not produce new trade for same pair, so you can think of it like it's ignored. Same for the 'sell' conditions -- if the pair does not contain open trades, then the sell signal in the 'sell' column won't produce any sells till the pair is bought...
> 
> The Freqtrade's 'sell' and 'buy' is closer to 'open position'/'close position' in this sence...

Thank you for your response... 

in my case, the verification openTrade == True isn't optional... my strategy use some similar conditions in some cases for buy or sell and i need to discriminate which execute (sell or buy)... 

other posibility for me is, know the condition (condition1, condition2, etc) that create a particular buy is important to generate a respective sell signal.

**Comment by hroff-1902** [comment]
you can query this info from the `Trade` (see the link @xmatthias posted above), but it won't work for backtesting.
you can also keep this info in a custom dict (with the pair name as the key), this won't also work for backtesting, though.
you can also keep this mark (if trade is open or not) in a sep. column in the dataframe, but also in backtesting it won't probably produce correct results

**Comment by xmatthias** [comment]
Will close this one as the question was answered.

Feel free to reopen if you feel that the question was not answered sufficiently
