### ISSUE TITLE
Adding a link to `/forcesell` in the table status command and a link to the Graph

### ISSUE THREAD

**Issue by jblestang** [freqtrade/freqtrade#280]
For each opened trades in the `/status table` command, we should add : 

- a link to a telegram commande /forcesell trade_id (with an optional Inline Keyboard to ask a confirmation from the user)
- a link to the URL which links to the graph (the same that we have in the sell/buy) message

**Comment by glonlas** [comment]
Nice feature. But haven't you already tried to do it in a previous PR?
Do you still have the PR?

**Comment by jblestang** [comment]
This generate two longs content for telegram (there is a 1k limit)
