### ISSUE TITLE
TA-Lib installation error

### ISSUE THREAD

**Issue by djacky** [freqtrade/freqtrade#2805]
## Step 1: Have you search for this issue before posting it?

Yes, I have searched for this problem before posting. No solutions have worked.

## Step 2: Describe your environment

  * Operating system: Debian 9.11
  * Python Version: 3.8.0 (`python -V`)
  * CCXT version: 1.20.46 (`pip freeze | grep ccxt`)
  * Branch: Master 

  
## Step 3: Describe the problem:

I am attempting to install freqtrade on a linux system running Debian. I am following the steps in [https://www.freqtrade.io/en/latest/installation/ ](url) (steps in Common). I run the first step with the following code:

`wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz`
`tar xvzf ta-lib-0.4.0-src.tar.gz`
`cd ta-lib`
`sed -i.bak "s|0.00000001|0.000000000000000001 |g" src/ta_func/ta_utility.h`
`./configure --prefix=/usr/local`
`make`
`sudo make install`
`cd ..`
`rm -rf ./ta-lib*`

Everything works fine after this. I then try to install TA-Lib with `pip install TA-Lib`. The output of this process returns an error, and doesn't install the library. 

### Steps to reproduce:

  1. Launch `pip install TA-Lib` 
  
### Observed Results:

The error seems to be related to a gcc error (see the logs below)
`gcc --version` --> gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

I have also tried to install and upgrade:
`sudo apt-get update`
`sudo apt-get install build-essential git`
`sudo apt-get install python3-dev`
`sudo apt -y install gcc`

### Relevant code exceptions or logs:
The log is quite long. So to shorten it, I put ```...continues...``` to signify that similar outputs from the previous error are occurring.

  ```
    ERROR: Command errored out with exit status 1:
     command: /home/debian/.env/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-juqv6n3z/TA-lib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-juqv6n3z/TA-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9v4_6hix/install-record.txt --single-version-externally-managed --compile --install-headers /home/debian/.env/include/site/python3.8/TA-lib
         cwd: /tmp/pip-install-juqv6n3z/TA-lib/
    Complete output (2799 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.8
    creating build/lib.linux-armv7l-3.8/talib
    copying talib/test_func.py -> build/lib.linux-armv7l-3.8/talib
    copying talib/abstract.py -> build/lib.linux-armv7l-3.8/talib
    copying talib/test_pandas.py -> build/lib.linux-armv7l-3.8/talib
    copying talib/test_abstract.py -> build/lib.linux-armv7l-3.8/talib
    copying talib/__init__.py -> build/lib.linux-armv7l-3.8/talib
    copying talib/test_stream.py -> build/lib.linux-armv7l-3.8/talib
    copying talib/stream.py -> build/lib.linux-armv7l-3.8/talib
    copying talib/deprecated.py -> build/lib.linux-armv7l-3.8/talib
    copying talib/test_data.py -> build/lib.linux-armv7l-3.8/talib
    running build_ext
    skipping 'talib/_ta_lib.c' Cython extension (up-to-date)
    building 'talib._ta_lib' extension
    creating build/temp.linux-armv7l-3.8
    creating build/temp.linux-armv7l-3.8/talib
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/debian/.env/lib/python3.8/site-packages/numpy/core/include -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/home/debian/.env/include -I/usr/local/include/python3.8 -c talib/_ta_lib.c -o build/temp.linux-armv7l-3.8/talib/_ta_lib.o
    In file included from /home/debian/.env/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1830:0,
                     from /home/debian/.env/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /home/debian/.env/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from talib/_ta_lib.c:533:
    /home/debian/.env/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^~~~~~~
    talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_14ACOS’:
    talib/_ta_lib.c:8328:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_real); if (unlikely(!__pyx_t_2)) __PYX_ERR(2, 48, __pyx_L1_error)
                   ^
    talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_16AD’:
    talib/_ta_lib.c:8784:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_high); if (unlikely(!__pyx_t_2)) __PYX_ERR(2, 100, __pyx_L1_error)
                   ^
    talib/_ta_lib.c:8889:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_low); if (unlikely(!__pyx_t_2)) __PYX_ERR(2, 107, __pyx_L1_error)
                   ^
    talib/_ta_lib.c:8994:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_close); if (unlikely(!__pyx_t_2)) __PYX_ERR(2, 114, __pyx_L1_error)
                   ^
    talib/_ta_lib.c:9099:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_volume); if (unlikely(!__pyx_t_2)) __PYX_ERR(2, 121, __pyx_L1_error)
                   ^
    talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_18ADD’:
    talib/_ta_lib.c:9737:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_real0); if (unlikely(!__pyx_t_2)) __PYX_ERR(2, 187, __pyx_L1_error)
                   ^
    talib/_ta_lib.c:9842:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_real1); if (unlikely(!__pyx_t_2)) __PYX_ERR(2, 194, __pyx_L1_error)
                   ^




...continues...



    cc1: out of memory allocating 13017700 bytes after a total of 73768960 bytes
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/debian/.env/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-juqv6n3z/TA-lib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-juqv6n3z/TA-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9v4_6hix/install-record.txt --single-version-externally-managed --compile --install-headers /home/debian/.env/include/site/python3.8/TA-lib Check the logs for full command output.
  ```

**Comment by hroff-1902** [comment]
```
cc1: out of memory
```

**Comment by djacky** [comment]
@hroff-1902 Why is this error occurring? How do I correct this?

**Comment by hroff-1902** [comment]
do you install it on a virtual machine? do you have some other processes, consuming memory, running on the machine? (services or browser with many open tabs are examples)

**Comment by hroff-1902** [comment]
ah, it's arm7 architecture, is it on a rpi?

**Comment by djacky** [comment]
It's a BeagleBone Black (rev C)...I think it has 512MB of ram...
No processes were running in the background. I was connected via SSH.
Would a 4GB Rasberry Pi work?

**Comment by hroff-1902** [comment]
right, 512 should be too low... We've got 2GB in the system requirements, see https://www.freqtrade.io/en/latest/#hardware-requirements

While 2GB here is a bit more than the absolute minimum necessary to run and install and is written taking mostly Intel architecture in the account, the processes on ARM (and the compilers/linkers in big degree since they deal with machine code in the memory) require significantly more RAM since it's RISC architecture...

Rasberry Pi is a platform used by many users as we know.

**Comment by djacky** [comment]
@hroff-1902 Ok thanks! I guess I will need a higher RAM board...

**Comment by santiagofranchi** [comment]
Hi. I am installing talib on my elementary linux (ubuntu) and it throws me the following error:

pip3 install ta-lib
Collecting ta-lib
  Using cached TA-Lib-0.4.18.tar.gz (265 kB)
Requirement already satisfied: numpy in ./.env/lib/python3.7/site-packages (from ta-lib) (1.15.4)
Using legacy 'setup.py install' for ta-lib, since package 'wheel' is not installed.
Installing collected packages: ta-lib
    Running setup.py install for ta-lib ... error
    ERROR: Command errored out with exit status 1:
     command: /home/tagonio/freqtrade/.env/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wgp9g6ks/ta-lib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wgp9g6ks/ta-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ui0mgohi/install-record.txt --single-version-externally-managed --compile --install-headers /home/tagonio/freqtrade/.env/include/site/python3.7/ta-lib
         cwd: /tmp/pip-install-wgp9g6ks/ta-lib/
    Complete output (27 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/talib
    copying talib/test_abstract.py -> build/lib.linux-x86_64-3.7/talib
    copying talib/test_data.py -> build/lib.linux-x86_64-3.7/talib
    copying talib/deprecated.py -> build/lib.linux-x86_64-3.7/talib
    copying talib/stream.py -> build/lib.linux-x86_64-3.7/talib
    copying talib/test_stream.py -> build/lib.linux-x86_64-3.7/talib
    copying talib/test_pandas.py -> build/lib.linux-x86_64-3.7/talib
    copying talib/__init__.py -> build/lib.linux-x86_64-3.7/talib
    copying talib/abstract.py -> build/lib.linux-x86_64-3.7/talib
    copying talib/test_func.py -> build/lib.linux-x86_64-3.7/talib
    running build_ext
    building 'talib._ta_lib' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/talib
    /home/tagonio/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -I/home/tagonio/freqtrade/.env/lib/python3.7/site-packages/numpy/core/include -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/home/tagonio/freqtrade/.env/include -I/home/tagonio/anaconda3/include/python3.7m -c talib/_ta_lib.c -o build/temp.linux-x86_64-3.7/talib/_ta_lib.o
    In file included from /home/tagonio/anaconda3/include/python3.7m/Python.h:11:0,
                     from talib/_ta_lib.c:4:
    /usr/include/limits.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
     #include <bits/libc-header-start.h>
              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command '/home/tagonio/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/tagonio/freqtrade/.env/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wgp9g6ks/ta-lib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wgp9g6ks/ta-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ui0mgohi/install-record.txt --single-version-externally-managed --compile --install-headers /home/tagonio/freqtrade/.env/include/site/python3.7/ta-lib Check the logs for full command output.

**Comment by xmatthias** [comment]
the error would suggest that it might be related to libc not beeing installed ... 

I've never used elementary linux before - and i've never seen this on ubuntu, so i assume it's something specific to elementary (maybe they miss a libary ubuntu installs by default).

however, for support on ta-lib installation, it might be better to head to the [ta-lib](https://github.com/mrjbq7/ta-lib) repository - they are the experts in this field

**Comment by santiagofranchi** [comment]
Thanks!

**Comment by v4lue4dded** [comment]
Thanks!

**Comment by traderblakeq** [comment]
Solution for not enough memory ( This worked for me on Debian 10.2 )

How to create a Swap file (2GB):
1.
sudo fallocate -l 2G /swapfile
2.
sudo chmod 600 /swapfile
3.
sudo mkswap /swapfile
4.
sudo swapon /swapfile

5.
in "sudo nano /etc/fstab" add this line at the end of the file:

/swapfile none swap sw 0 0

6.
now run "sudo swapon --show" to see that the swap file have been activated.



Should solve any memory issues related to installment of TA-LIB
