### ISSUE TITLE
Hyperopt with data from custom .json files

### ISSUE THREAD

**Issue by djacky** [freqtrade/freqtrade#2813]
I just had a general question about using the hyperopt function (as I think this is a fantastic tool for strategy optimization).

I have some custom .json files  (with close, open, high, low, volume, time data), and would like to use hyperopt to optimize a strategy with these custom files. These files are not contained in the exchange (but they are formatted to be exactly like the data downloaded from the exchange). Is there a way to bypass communication with the exchange and tell hyperopt to just use the custom .json files in the user_data/data/custom_files directory?

**Comment by hroff-1902** [comment]
(edited the title a bit
)

**Comment by xmatthias** [comment]
Well if the filename is correct (`QUOTE_STAKE-INTERVAL.json` -> `DASH_BTC-5m.json`) you should be able to use `--datadir user_data/data/custom_files directory` when starting hyperopt.

#2719 will further simplify this by allowing to user other formats (other than json).

**Comment by djacky** [comment]
@xmatthias So I tried that (with a custom .json file using pair BSV/BTC), and I get an error: `ERROR - Pair BSV/BTC is not available on Binance. Please remove MOMO/BTC from your whitelist.`

So it's still going to the exchange to fetch information. For my purposes, I need to completely bypass the exchange.

**Comment by hroff-1902** [comment]
There is no BST currency on the Binance exchange.

> These files are not contained in the exchange (but they are formatted to be exactly like the data downloaded from the exchange).

How can this be? The files from exchange for pairs that are not on the exchange...

Freqtrade currently uses some other market (pair) data, like limits and precisions, fees, from the exchange, including backtesting, so it requires the pair to be on the exchange...

**Comment by djacky** [comment]
I basically download the data for BST from another exchange and formatted the .json file to be exactly like the one from Binance. Backtesting can just use the data I supply in the .json file, no? For the other things (fees, etc...) I would think that I can modify some scripts to supply my own. 

So there is no way to completely bypass the exchange to optimize the strategy?

**Comment by xmatthias** [comment]
no, sorry.

**Comment by djacky** [comment]
Ok, thanks anyways! Much appreciated.
