### ISSUE TITLE
Include a colum in "sell reason stat" with the profit/loss ratio  

### ISSUE THREAD

**Issue by freskpe** [freqtrade/freqtrade#2814]
I think that including a colum named "ratio" in the "sell reason stat" table give us an idea about eficiency of strategy. 

ratio could be: profit/count or profit/loss 

What do you think about it?

**Comment by xmatthias** [comment]
I'm not against it...but i also don't see a whole lot of benefits in it... (but then, maybe other people look for other things in backtests).
we've got absolute profit / loss numbers - and profit % (so how much profit did this sell-type generate on average).


how it looks now:
```
| Sell Reason   |   Count |   Profit |   Loss |   Profit % |
|:--------------|--------:|---------:|-------:|-----------:|
| roi           |      21 |       21 |      0 |       1.04 |
| stop_loss     |       3 |        0 |      3 |     -10.18 |
| force_sell    |       3 |        1 |      2 |      -1.13 |

```

i'm not certain about profit/count vs. profit / loss.
Looking at forcesell in the above example - we'd either show 50% (profit / loss) or 33% (profit / count). 

Neither of the 2 seems too appealing to me - but i guess 33% win-rate will be easier to understand (?)

**Comment by freskpe** [comment]
You right! win-rate is a better measure. this give you an idea of performance of your strategy i think...

i was reading that a **win-rate** + **risk-reward**  (average of gains and losses) give you and idea of eficiency of your strategy.

**Comment by hroff-1902** [comment]
Sidenote: I we add some win-rate and risk metrics to the backtesting tables in the same terms as Edge calculates and describes in its docs chapter, then the backtesting will be better aligned to the Edge module...

**Comment by xmatthias** [comment]
I think this should've been addressed with the changes done to the sell-stats table lately
(this is how it looks now):

```
| Sell Reason   |   Sells |   Wins |   Draws |   Losses |   Avg Profit % |   Cum Profit % |   Tot Profit ETH |   Tot Profit % |
|:--------------|--------:|-------:|--------:|---------:|---------------:|---------------:|-----------------:|---------------:|
| roi           |      56 |     56 |       0 |        0 |           2.53 |         141.74 |       0.141877   |          47.25 |
| stop_loss     |      36 |      0 |       0 |       36 |          -4.19 |        -150.91 |      -0.151056   |         -50.3  |
| sell_signal   |       4 |      1 |       0 |        3 |          -1.07 |          -4.29 |      -0.00429162 |          -1.43 |
| force_sell    |       3 |      0 |       0 |        3 |          -0.59 |          -1.77 |      -0.00177582 |          -0.59 |

```

Feel free to reopen if you think differently
