### ISSUE TITLE
Hyperopt running when it shouldn't

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2822]
It is really odd, there are strategies which are commented out in my hypeorpt.py file and 'freqtrade hyperopt' does not recognise any error and lets hyperopt run. for example, 

1) a strategy is written in the `def buy_strategy_generator().... def populate_buy_trend`, 
2) the strategy is appended to the strategy list in the `Categorical([...])` subsection of the `def space_indicator()`,
3) the strategy from `def buy_strategy_generator().... def populate_buy_trend` is commented out with '#' at the beginning of the line
4) exit .py file

Another example would be defining a dataframe in `def populate_indicators` and appending it to `Categorical([...])` subsection of the `def space_indicator()`, without writing anything in `def buy_strategy_generator().... def populate_buy_trend`.

then 'freqtrade hyperopt...'  runs with strategies that appear not to be there without any comment of an error

**Comment by hroff-1902** [comment]
> then 'freqtrade hyperopt...' runs with strategies that appear not to be there without any comment of an error
Why have you decided it behaves like this?

**Comment by hroff-1902** [comment]
One common error is when you have two strategy classes with the same name in two separate files in the user_data/strategies dir, and editing one of them, while freqtrade resolves and uses the strategy from the second .py file.
The name of the python file it uses can be found in the logs, make sure it uses the correct one.

**Comment by gitgitgat** [comment]
> > then 'freqtrade hyperopt...' runs with strategies that appear not to be there without any comment of an error
> 
> Why have you decided it behaves like this?

It used to raise an error if there were errors in `Categorical([...])` when 'guard' indicator parameters were not correct (for example if CCI had some errors), but the error is not being raised in `Categorical([...])` for the list of 'triggers'.

At the moment there is only one strategy.py file and one hyperopt.py file in the user_data subdirectories

**Comment by hroff-1902** [comment]
send pls the hyperopt file to me at Slack in a PM

**Comment by hroff-1902** [comment]
closing as it's paired with #2852
