### ISSUE TITLE
Strategy using different time frames

### ISSUE THREAD

**Issue by djacky** [freqtrade/freqtrade#2823]
I have consulted issue #1166 to use multiple time frames in strategies.
However, it seems that the `technical.util` library is no longer available, as I get the following error:

`'No module named 'technical''`

`2020-01-30 20:15:40,081 - freqtrade - ERROR - Impossible to load Strategy...`

Is there another method to use/import multiple time frames in a strategy?
To resample to a daily frame (assuming using ticker_interval < 1d), I guess we can use something like `dataframe_long = dataframe.resample('D', on='date')`...but I'm not sure what aggregate function to add to this to get the daily candlesticks...Perhaps something like:

`dataframe_long = dataframe.resample('D', on='date').agg({'open': 'first', 'high': 'max', 'low': 'min', 'close': 'last'})`

Is this the correct approach?

**Comment by hroff-1902** [comment]
See https://github.com/freqtrade/technical#usage for how technical library should be installed.
It's not a part of freqtrade, it's a sister repo with the library which should be installed separately if it's used in the custom strategies.

**Comment by djacky** [comment]
Thanks @hroff-1902 !
Much appreciated. Sorry, didn't see this page in the freqtrade site.

**Comment by hroff-1902** [comment]
can be closed?

**Comment by djacky** [comment]
Just one more thing...can we use Hyperopt to optimize in different time frames as well? I tried this, but didn't seem to work as expected....

**Comment by hroff-1902** [comment]
This one?
```
$ freqtrade hyperopt ... --ticker_interval 5m
$ freqtrade hyperopt ... --ticker_interval 1h
```
Or set the required timeframe in the `ticker-interval` setting in the config.

**Comment by djacky** [comment]
I'll test this out and keep you updated...

**Comment by djacky** [comment]
Oh sorry, I think you misunderstood what I meant...
What I meant was, for example, can I use both 15m AND 30m ticker intervals to optimize a set of parameters using hyperopt...for example, putting the following code snippet in the hyperopt file:

```
ticker_interval = '15m'
...
dataframe_long = resample_to_interval(dataframe, 100)

dataframe['rsi'] = ta.RSI(dataframe)
dataframe_long['rsi_long'] = ta.RSI(dataframe_long)

dataframe = resampled_merge(dataframe, dataframe_long)
dataframe.fillna(method='ffill', inplace=True)

...

            if 'rsi-enabled' in params and params['rsi-enabled']:
                conditions.append(dataframe['rsi'] > params['rsi-value'])

            if 'rsi-long-enabled' in params and params['rsi-long-enabled']:
                conditions.append(dataframe['rsi_long'] > params['rsi-long-value'])

...

```

Is this kind of operation allowed? With initial tests, it didn't seem to work properly...so my question was, is this kind of optimization feasible, and if so, what am I doing wrong?

**Comment by xmatthias** [comment]
Well you build the dataframe in `populate_indicators()`...

so if it contains a column `rsi_long` - then this will be possible.

If you're using `resampled_merge()` from technical - then the name will be slightly different (i think `resample_15_rsi` ) - but it'll still work.

**Comment by hroff-1902** [comment]
hm, resampling can be performed in hyperopt, why not -- it's just manipulation of the dataframe...
however, be careful with it (and in backtesting as well, when same code is transferred to the strategy).

Another option is using informative pairs (see in the docs) -- they can be of any timeframe.

**Comment by djacky** [comment]
@xmatthias With the example code I posted above (with the `resampled_merge` command), it looks like I can access the resampled data by just calling `dataframe['rsi_long']`

Ok thanks guys, I'll try this out and keep you posted...I'll close this thread for now.

**Comment by djacky** [comment]
Looks like it's working :)

**Comment by fabohax** [comment]
Hi, I've just installed technical lib but the result is "'No module named 'technical' too. Any thought?

**Comment by xmatthias** [comment]
@fabohax please don't highjack old issues, everyone that ever commented on this issue will get (spam)-notified for this.

You most likely didn't install technical in the correct virtual environment. Make sure it's activated before running `pip install technical`.

**Comment by bleriot14** [comment]
How can I sync 5m timeframe and 15m timeframe with _resampled_merge_ and resample_to_interval(dataframe, x). I can't merge dataframes synchronous (I mean I want change values at 15:15, 15:30, 15:45 not at 15:20, 15:35, 15:50 )

**Comment by xmatthias** [comment]
@bleriot14 Please don't highjack old issues (as this is now the 2nd time in this issue - i'll lock this issue, also because it's now 2 years old).

your 15 minute indicators will be identical for the "non-15m" intervals - and will only change at the 15m interval if using technical correctly.
