### ISSUE TITLE
How to create separate data-frames for indicators at entry and close. 

### ISSUE THREAD

**Issue by King-Techno** [freqtrade/freqtrade#2824]
Using `macd = ta.MACD(dataframe)` and `dataframe['macdhist'] = macd['macdhist']`. 

How will I create two separate data frames; One for the previous MACD Histogram close value (this will be the current MACD entry value) and another for the current MACD Histogram value?

To give an overview of my goal I am trying to enter a trade when the current MACD Histogram value exceeds the close of the previous MACD Histogram value by a certain percentage. 

If anyone can help me understand how this can be done, I would really appreciate it! This will enable me to apply this same principle to my other indicators

**Comment by hroff-1902** [comment]
>  One for the previous MACD Histogram close value (this will be the current MACD entry value) and another for the current MACD Histogram value?

I did not get this: what is "previous MACD Histogram" and what is "MACD Histogram close value"?

**Comment by King-Techno** [comment]
Sorry for the confusion. 

So I am trying to create the dataframe of the MACD Histogram bar for the current candle and also create one for the previous candle. 

Goal:
Essentially if the size of the current histogram bar is a certain percentage greater than the previous bar I will enter the trade.

**Comment by hroff-1902** [comment]
`macd['macdhist'].shift(1)` or `dataframe['macdhist'].shift(1)` (after assignment `dataframe['macdhist'] = macd['macdhist']`) is probably what you are looking for...

**Comment by King-Techno** [comment]
Thank you! and the shift(1) essentially shifts it back by one?

**Comment by hroff-1902** [comment]
> Thank you! and the shift(1) essentially shifts it back by one?

yeap, it shift a pandas Series (a column of the pandas DataFrame) one row back.

See https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.Series.shift.html

**Comment by King-Techno** [comment]
Great! You have been a huge amount of help. Really appreciate your time :)

**Comment by King-Techno** [comment]
I am getting the error:
can't assign to function call (<unknown>, line 81)

My code:
# MACD
       ` macd = ta.MACD(dataframe)` #Current MACD Histogram Value 
        `dataframe['macdhist'] = macd['macdhist']`
       
        `macd2 = ta.MACD(dataframe)` #This is the previous MACD Histogram Value
        `dataframe['macdhist2'].shift(-1) = macd2['macdhist2'].shift(-1)` --- line 81

I am new to this :(

**Comment by hroff-1902** [comment]
* you cannot use series.shift() in the left part of an assignment; if you need to keep the result of ,shift() -- assign it into a new column, like `dataframe['mycolumn'] = dataframe['macdhist2'].shift(1)`
* NEVER use negative shifts in the strategy -- by using this you try to lookforward into the future, this may give you unrealistic good results during backtesting and no effect at dry run/live trade

```
   macd = ta.MACD(dataframe) #Current MACD Histogram Value 
   dataframe['macdhist'] = macd['macdhist']
   dataframe['macdhist2'] = macd['macdhist'].shift(1) # This is the previous MACD Histogram Value
```

**Comment by King-Techno** [comment]
Thank you again :)
