### ISSUE TITLE
--print-trades to backtesting and hyperopt show-hyperopt

### ISSUE THREAD

**Issue by yazeed** [freqtrade/freqtrade#2837]
The purpose of this issue is to log the feature request mentioned in #2727 in its own issue, where it was discussed the possibility of supporting a flag **--print-trades** with the following commands:

- hyperopt show-hyperopt --print-trades
- backtesting --print-trades

The flag would print a table of the trades.

Another possibility is to have it export them into a CSV file with **--export-trades**, since some some outputs may have too many trades to print in the console.

Feel free to discuss here which one you'd prefer.

**Comment by xmatthias** [comment]
I'm not a huge fan of printing the list of trades to screen.
If it's just a few this may be fine - but you won't know this before running backtesting, so you'll have confusing printouts almost guaranteed.

We provide [sample code](https://www.freqtrade.io/en/latest/strategy_analysis_example/#load-backtest-results-to-pandas-dataframe) to load the results to a dataframe - which i think provides a lot more flexibility - as it'll allow you to do analysis on top of the data - what exactly would you expect to read from printing 20 trades? you wouldn't even know if they averaged positive or negative ...

> Another possibility is to have it export them into a CSV file with --export-trades

What's the difference to exporting to CSV as opposed to exporting to json?

We even provide code to load the json to a pandas dataframe - so to me, a simple `results.to_csv()` in a jupyter notebook will suffice this (i see this as a very edgecase requirement).

**Comment by hroff-1902** [comment]
> The purpose of this issue is to log the feature request mentioned in #2727 in its own issue, where it was discussed the possibility of supporting a flag **--print-trades** with the following commands:
> 
> * hyperopt show-hyperopt --print-trades
> * backtesting --print-trades
> 
> The flag would print a table of the trades.

Can you propose the columns for that table? (Or simply offer a PR containing proposal, if it's not heavy)

> Another possibility is to have it export them into a CSV file with **--export-trades**, since some some outputs may have too many trades to print in the console.

For backtesting, is not it same with `--export trades`? Should we change it into `--export-trades`, the syntax of `--export` raises question for myself for long time? Same syntax should simply be implemented into `show-hyperopt`.

> Feel free to discuss here which one you'd prefer.

Both (--print-trades and export) are handy and can coexist imho.

**Comment by xmatthias** [comment]
> Both (--print-trades and export) are handy and can coexist imho.

Export - yes - it'll provide you with possibilities to analyze the data in detail - but json is fine for that in my opinion.

Printing - i disagree (as stated above).

**Comment by hroff-1902** [comment]
`--print-trades` for `show-hyperopt` requires keeping all trades for every epoch in the hyperopt results file. They are now not stored -- only results/metrics. This can make the hyperopt results file extremely long, if many epochs contain thousands of trades. Needs evaluation.

**Comment by yazeed** [comment]
> `--print-trades` for `show-hyperopt` requires keeping all trades for every epoch in the hyperopt results file. They are now not stored -- only results/metrics. This can make the hyperopt results file extremely long, if many epochs contain thousands of trades. Needs evaluation.

Perhaps they can be simulated based on an epoch via running a backtest on an epoch, that way they don't need to be stored?

**Comment by xmatthias** [comment]
I'll close this as hyperopt is now storing the same info as backtesting - and `show-hyperopt` is printing the backtesting-resut for the selected epoch (#4848).
