### ISSUE TITLE
Error with hyperopt stop loss function 

### ISSUE THREAD

**Issue by King-Techno** [freqtrade/freqtrade#2841]
When I paste the code from the hyperopt_interface:

```
 @staticmethod
    def stoploss_space() -> List[Dimension]:

        return [
            Real(-0.35, -0.02, name='stoploss'),
        ]
```

I am getting the error: Undefined variable 'Real'. 

I assumed the variable real has already been defined? or do I have to create a new variable called real and define it to 'blank'

**Comment by hroff-1902** [comment]
You should have it imported like this (see sample_hyperopt.py in the user_data/hyperopts):
```
from skopt.space import Categorical, Dimension, Integer, Real  # noqa
```

**Comment by hroff-1902** [comment]
In my case it's a different error though (if I remove that import):
`NameError: name 'Real' is not defined`

**Comment by King-Techno** [comment]
Thanks for the reply, I do not have a sample_hyperopt.py in my hyperopts folder. I only have .gitkeep also when i run that line of code from my terminal I get from: can't read /var/mail/skopt.space

**Comment by hroff-1902** [comment]
> Thanks for the reply, I do not have a sample_hyperopt.py in my hyperopts folder.
run `freqtrade create-userdir --userdir user_data/`, it will place the samples (strategy, hyperopt, the notebook file) into the subdirs

**Comment by hroff-1902** [comment]
> I only have .gitkeep also when i run that line of code from my terminal I get "`from: can't read /var/mail/skopt.space`"

that's not for terminal, that should be at the top of the hyperopt python module where you copied the `stoploss_space()` too. Same in the hyperopt_interface.py, have a look at the beginning of this module

**Comment by King-Techno** [comment]
ohh yes! perfect thank you!

Should i also add:

```
import logging
import math
from abc import ABC
from typing import Any, Callable, Dict, List

from skopt.space import Categorical, Dimension, Integer, Real

from freqtrade.exceptions import OperationalException
from freqtrade.exchange import timeframe_to_minutes
from freqtrade.misc import round_dict
```

**Comment by hroff-1902** [comment]
better take the sample_hyperopt.py as the starting point (after populating it into user_data) -- it contains all lines needed and does not have ones that are only needed for the interface, like ABC, logging etc.

**Comment by King-Techno** [comment]
Thank you, will do this now. Really appreciated!
