### ISSUE TITLE
FTX: using subaccount, how to add subheader for subaccount?

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#2860]
## Step 1: Have you search for this issue before posting it?

yes

Not a bug per-se but cant use subaccounts only main account; from here https://github.com/ccxt/ccxt/issues/6038#issuecomment-581135441 I tried adding on the configuration file:
```
"exchange.headers": {
     "FTX-SUBACCOUNT":"name"

}

and other variants as well, let me know if you have any suggestions on where to add this.

**Comment by hroff-1902** [comment]
try it this way:
```
    "exchange": {
        "name": "binance",
        ...
        "headers": {
            "FTX-SUBACCOUNT": "name"
        }
```

**Comment by xmatthias** [comment]
it'll work - but not this way.
You need to put it under ccxt_config.

You may also add it to async_config - but since tha'ts only used to pull OHLCV data i don't think that's relevant.

```
    "exchange": {
        "name": "ftx",
        ...
        "ccxt_config": {
            "headers": {
                "FTX-SUBACCOUNT": "name"
            }
        },
        "ccxt_async_config": {
            "headers": {
                "FTX-SUBACCOUNT": "name"
            }
        }
    }
```

**Comment by hroff-1902** [comment]
I tested. the headers dict is inserted into the exchange params (`ex_config` var in `_init_ccxt()`) in both cases (mine aproach and yours) in the same way...

**Comment by hroff-1902** [comment]
We should later add this into exchange-specific docs after confirmation from @Dante2333 that either approach works.

**Comment by xmatthias** [comment]
i don't see how your approach would add it as it's at exchange level - the code does not back this, nor does testing.

Testing this it does not add it to ex_config - so i don't know what you've been testing, but your approach does NOT work.

 -  we select 4 attributes to send to CCXT from the "exchange" config level (header being not one of these) - and we pass ALL options inside ccxt_config and ccxt_async_config.

**Comment by hroff-1902** [comment]
right, I was wrong with curly brackets in config,

@Dante2333 pls try it in the way stated by @xmatthias above.

**Comment by Dante2333** [comment]
@xmatthias method worked. Thanks!

**Comment by zyang87** [comment]
whats the sub account name for the main account? "Main" or "null" per the FTX API docs isnt working for me

c = ftx({
    'apiKey': key,
    'secret': secret,
    'headers': {
        'FTX-SUBACCOUNT': 'subaccount',
    },})

works for sub account - but id like to pass a null or something through for the sub account

**Comment by xmatthias** [comment]
you can simply remove the "headers" section for that (the default is for the main account - assuming the API key has permissions to that, obviously)

**Comment by zyang87** [comment]
Yes i know that, but is there a null return or something i can put there if i want that header there? Trying to write one script i can use for both subs and mains etc

**Comment by xmatthias** [comment]
i don't think so
