### ISSUE TITLE
Exception on 'profit' command from TG

### ISSUE THREAD

**Issue by dexion** [freqtrade/freqtrade#2861]
## Step 1: Have you search for this issue before posting it?

Yep

## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.6.9
  * CCXT version: 1.22.35
  * Branch: Develop
  * Last Commit ID: f5fb1294835adbb3bc881c6ee629faedaa34e66a
  
## Step 3: Describe the problem:

From TG send command `/profit` (or `/daily` etc)

*Explain the problem you have encountered*

### Steps to reproduce:

  1. move bot with db to another dir

### Observed Results:

nothing in TG

### Relevant code exceptions or logs:

  ```
2020-02-04 11:00:58,773 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
Traceback (most recent call last):
  File "/home/user/freqtrade/freqtrade/rpc/telegram.py", line 52, in wrapper
    return command_handler(self, *args, **kwargs)
  File "/home/user/freqtrade/freqtrade/rpc/telegram.py", line 298, in _profit
    fiat_disp_cur)
  File "/home/user/freqtrade/freqtrade/rpc/rpc.py", line 244, in _rpc_trade_statistics
    profit_percent = trade.calc_profit_ratio()
  File "/home/user/freqtrade/freqtrade/persistence.py", line 408, in calc_profit_ratio
    profit_percent = (close_trade_price / self.open_trade_price) - 1
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
  ```

**Comment by xmatthias** [comment]
I've just tried with this version and a brandnew database, and it seems to work just fine.

Does any command return anything from the database (`/status` | `/status table` | `/performance`?
are there errors / warnings at bot startup?

can you open the database (sqlite3 / sqlbrowser) and show us the output of the following command:
```
sqlite3 tradesv3.sqlite
.schema trades
```

**Comment by dexion** [comment]
Commands `/status` | `/status table` | `/performance` works fine. I've checked all commands from `/help`, problems only with `/daily` and `/profit`

```
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> .schema trades
CREATE TABLE trades (
        id INTEGER NOT NULL,
        exchange VARCHAR NOT NULL,
        pair VARCHAR NOT NULL,
        is_open BOOLEAN NOT NULL,
        fee_open FLOAT NOT NULL,
        fee_close FLOAT NOT NULL,
        open_rate FLOAT,
        open_rate_requested FLOAT,
        open_trade_price FLOAT,
        close_rate FLOAT,
        close_rate_requested FLOAT,
        close_profit FLOAT,
        stake_amount FLOAT NOT NULL,
        amount FLOAT,
        open_date DATETIME NOT NULL,
        close_date DATETIME,
        open_order_id VARCHAR,
        stop_loss FLOAT,
        stop_loss_pct FLOAT,
        initial_stop_loss FLOAT,
        initial_stop_loss_pct FLOAT,
        stoploss_order_id VARCHAR,
        stoploss_last_update DATETIME,
        max_rate FLOAT,
        min_rate FLOAT,
        sell_reason VARCHAR,
        strategy VARCHAR,
        ticker_interval INTEGER,
        PRIMARY KEY (id),
        CHECK (is_open IN (0, 1))
);
CREATE INDEX ix_trades_is_open ON trades (is_open);
CREATE INDEX ix_trades_pair ON trades (pair);
CREATE INDEX ix_trades_stoploss_order_id ON trades (stoploss_order_id);
sqlite> select count(*) from trades;
174

```

**Comment by hroff-1902** [comment]
I guess that's the case of race condition appeared, when the `/profit` RPC command arrives in one thread and main worker closes the position and removes the trade from persistence in the same time asynchronously, so RPC thread proceeds processing with incorrect data.

**Comment by xmatthias** [comment]
@hroff-1902 I don't think that a timing error can cause this - maybe for 5 entries - but not for 10 entries - noone can have THAT much bad luck.


This sounds like the migration somehow went wrong - which i don't "really" understand why, as the calculation for this field is as simple as `amount * open_rate * (1 + fee_open)`.

Would you mind checking the trades_bak<x> versions within the database (there may be multiple) ... ? 

----
On the other hand - i can imagine a scenario where the migration would not correctly work.

did you maybe do something similar to the following (this seems to be a database which has been in use for some time)

* Run the bot on any older version (probably uptodate at that point)
* update the bot to a newer version
* bot created 10 trades
* return to a previous version 
* update bot again ... 

If this applies, having trades_bak won't help ... as it's clear as to why the migration did not work.

**Comment by hroff-1902** [comment]
@dexion pls respond to this part (we need a feedback from you):


> Would you mind checking the trades_bak versions within the database (there may be multiple) ... ?
> 
> On the other hand - i can imagine a scenario where the migration would not correctly work.
> 
> did you maybe do something similar to the following (this seems to be a database which has been in use for some time)
> 
> * Run the bot on any older version (probably uptodate at that point)
> * update the bot to a newer version
> * bot created 10 trades
> * return to a previous version
> * update bot again ...
> 
> If this applies, having trades_bak won't help ... as it's clear as to why the migration did not work - and i'm honestly not certain how we would be able to support this.

**Comment by dexion** [comment]
No, I didn't return back to previous version.  I run bot on older version, update repo, rerun bot. (I don't remember when I was update repo, so can't correlate this with bot trades). After some time I wanted to move bot to another location and after moving I caught problem.

**Comment by hroff-1902** [comment]
> No, I didn't return back to previous version. I run bot on older version, update repo, rerun bot. (I don't remember when I was update repo, so can't correlate this with bot trades). After some time I wanted to move bot to another location and after moving I caught problem.

This issue maybe related to telegram (yes, even if it sounds strange), @dexion Am I right in the assumption, that on your first location you've got telegram not-working (blocked by Russian authorities) and you moved the bot to another server where telegram works? And that you have telegram enabled in the config and moved bot along with the database?

**Comment by dexion** [comment]
@hroff-1902, you are not right. I had had TG config all the time (on first and on second server), and I don't have any server in Russia, so I don't have problem with TG connectivity.

**Comment by xmatthias** [comment]
I do think this was created by upgrade - and downgrade (maybe / probably unintentional while changing from one server to the other).

There's no other explanation why some trades "in the middle" suddenly miss a field which is there on all prior (handled by migration, most likely) and later (inserted by the updated bot version) trades.


Another solution would've been to update `open_trade_price` by doing the calculation in sql (it's just `amount * open_rate * (1 + fee_open)`).

I'll close this as i think it's a isolated issue - and unless we see this more frequently there's not much we will do about this.
