### ISSUE TITLE
crash, binance stop_loss insuffice funds

### ISSUE THREAD

**Issue by squat0001** [freqtrade/freqtrade#2862]
i got this crash it happens if the bot uses stop_loss on exchange but runs out of funds:

```
Feb  4 21:20:22 trade python[28119]: Traceback (most recent call last):
Feb  4 21:20:22 trade python[28119]:   File "/srv/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 552, in fetch
Feb  4 21:20:22 trade python[28119]:     response.raise_for_status()
Feb  4 21:20:22 trade python[28119]:   File "/srv/freqtrade/.env/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
Feb  4 21:20:22 trade python[28119]:     raise HTTPError(http_error_msg, response=self)
Feb  4 21:20:22 trade python[28119]: requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order
Feb  4 21:20:22 trade python[28119]: During handling of the above exception, another exception occurred:
Feb  4 21:20:22 trade python[28119]: Traceback (most recent call last):
Feb  4 21:20:22 trade python[28119]:   File "/srv/freqtrade/freqtrade/exchange/binance.py", line 65, in stoploss_limit
Feb  4 21:20:22 trade python[28119]:     amount, rate, params)
Feb  4 21:20:22 trade python[28119]:   File "/srv/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1028, in create_order
Feb  4 21:20:22 trade python[28119]:     response = getattr(self, method)(self.extend(request, params))
Feb  4 21:20:22 trade python[28119]:   File "/srv/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 439, in inner
Feb  4 21:20:22 trade python[28119]:     return entry(_self, **inner_kwargs)
Feb  4 21:20:22 trade python[28119]:   File "/srv/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1676, in request
Feb  4 21:20:22 trade python[28119]:     response = self.fetch2(path, api, method, params, headers, body)
Feb  4 21:20:22 trade python[28119]:   File "/srv/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 458, in fetch2
Feb  4 21:20:22 trade python[28119]:     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
Feb  4 21:20:22 trade python[28119]:   File "/srv/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 564, in fetch
Feb  4 21:20:22 trade python[28119]:     self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
Feb  4 21:20:22 trade python[28119]:   File "/srv/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1660, in handle_errors
Feb  4 21:20:22 trade python[28119]:     self.throw_exactly_matched_exception(self.exceptions, message, self.id + ' ' + message)
Feb  4 21:20:22 trade python[28119]:   File "/srv/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 476, in throw_exactly_matched_exception
Feb  4 21:20:22 trade python[28119]:     raise exact[string](message)
Feb  4 21:20:22 trade python[28119]: ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.
Feb  4 21:20:22 trade python[28119]: The above exception was the direct cause of the following exception:
Feb  4 21:20:22 trade python[28119]: Traceback (most recent call last):
Feb  4 21:20:22 trade python[28119]:   File "/srv/freqtrade/freqtrade/freqtradebot.py", line 660, in create_stoploss_order
Feb  4 21:20:22 trade python[28119]:     rate=rate * LIMIT_PRICE_PCT)
Feb  4 21:20:22 trade python[28119]:   File "/srv/freqtrade/freqtrade/exchange/binance.py", line 73, in stoploss_limit
Feb  4 21:20:22 trade python[28119]:     f'Message: {e}') from e
Feb  4 21:20:22 trade python[28119]: freqtrade.exceptions.DependencyException: Insufficient funds to create stop_loss_limit sell order on market IOTA/USDT.Tried to sell amount 44.6 at rate 0
```

**Comment by hroff-1902** [comment]
(formatted it a bit)

**Comment by hroff-1902** [comment]
please fill in the form with data:

## Step 2: Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)

**Comment by squat0001** [comment]
Operating system: debian buster
    Python Version:  Python 3.7.3 (python -V)
    CCXT version: ccxt==1.21.91 (pip freeze | grep ccxt)
    Branch: Master
    Last Commit ID: 8371003c05b83cb1c3c99307537932597d9caf4c (git log --format="%H" -n 1)

**Comment by xmatthias** [comment]
I think to properly triage this one we'll need a bit more logs (at least 10 lines prior to the exception one).

Now it says "at rate 0" - which doesn't seem to make sense - so i suspect there should've been other errors prior to this error.

**Comment by squat0001** [comment]
i think i understand the problem.
the bot tries to sell something, but the amount in the wallet is lower than stake_amount.

in the file(see below) a InvalidOrderException  is expected, but ccxt returns a DependencyException, so the bot is not able to sell anything.

So IMHO the bug is, that the bot tries to use a STOP_LOSS_LIMIT on exchange in the case it tries to sell back to the stake amount.


freqtrade/freqtradebot.py

>         except InvalidOrderException as e:
            trade.stoploss_order_id = None
            logger.error(f'Unable to place a stoploss order on exchange. {e}')
            logger.warning('Selling the trade forcefully')
            self.execute_sell(trade, trade.stop_loss, sell_reason=SellType.EMERGENCY_SELL)

        except DependencyException:
            trade.stoploss_order_id = None
            logger.exception('Unable to place a stoploss order on exchange.')

**Comment by xmatthias** [comment]
Please provide the additional logs (at least 10 lines before this exception happened).

Without more logs / earlier logs - it's impossible to determine if there is a bug or not, and everything we'd be doing is guessing around.

The log above says `Tried to sell amount 44.6 at rate 0`- which tells me that there must have been a problem before it reached the stoploss creation.

Thanks.

**Comment by hroff-1902** [comment]
@squat0001 just can you provide additional info @xmatthias asked at the previous comment?

**Comment by xmatthias** [comment]
I'll close this one as with the information provided, triaging/investigating this further is not possible.

Feel free to comment if you got the information requested so we can reopen and investigate further.

**Comment by devilsinthedetail** [comment]
I just encountered the same issue. The critical line (i think) is this one:
freqtrade.exceptions.DependencyException: Insufficient funds to create stop_loss_limit sell order on market EOS/BTC.Tried to sell amount 13.84 at rate 0.

In Binance I had a stop-loss order placed but no sell order, and the currency was "in order".

I dont have the logs for the same moment when it wanted to sell the coin but I guess at that point it had to remove the stop-loss order to be able to sell it and that did not work? Not sure how it works exactly. Thanks for any help. 

Log:
> freqtrade.exceptions.DependencyException: Insufficient funds to create stop_loss_limit sell order on market EOS/BTC.Tried to sell amount 13.84 at rate 0.
> 0002958. Message: binance Account has insufficient balance for requested action.                                                                        
> 2020-04-30 13:13:55,803 - freqtrade.freqtradebot - INFO - Executing Sell for EOS/BTC. Reason: SellType.ROI                                              
> 2020-04-30 13:13:56,319 - freqtrade.wallets - INFO - Wallets synced.                                                                                    
> 2020-04-30 13:13:56,320 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Not enough amount to sell. Trade-amount: 13.84, Wallet: 0            
> 2020-04-30 13:14:00,338 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.                                                
> Traceback (most recent call last):                                                                                                                      
>   File "/home/pi/Documents/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 562, in fetch                                         
>     response.raise_for_status()                                                                                                                         
>   File "/home/pi/Documents/freqtrade/.env/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status                                
>     raise HTTPError(http_error_msg, response=self)                                                                                                       
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order                                              
>                                                                                                                                                         
> During handling of the above exception, another exception occurred:                                                                                     
>                                                                                                                                                          
> Traceback (most recent call last):                                                                                                                      
>   File "/home/pi/Documents/freqtrade/freqtrade/exchange/binance.py", line 75, in stoploss                                                               
>     amount=amount, price=stop_price, params=params)                                                                                                     
>   File "/home/pi/Documents/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1149, in create_order                                      
>     response = getattr(self, method)(self.extend(request, params))                                                                                         File "/home/pi/Documents/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 446, in inner                                        
>     return entry(_self, **inner_kwargs)                                                                                                                 
>   File "/home/pi/Documents/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1846, in request                                           
>     response = self.fetch2(path, api, method, params, headers, body)                                                                                    
>   File "/home/pi/Documents/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 465, in fetch2                                       
>     return self.fetch(request['url'], request['method'], request['headers'], request['body'])                                                           
>   File "/home/pi/Documents/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 574, in fetch                                         
>     self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)           
>   File "/home/pi/Documents/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1827, in handle_errors                                     
>     self.throw_exactly_matched_exception(self.exceptions, message, self.id + ' ' + message)                                                             
>   File "/home/pi/Documents/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 483, in throw_exactly_matched_exception              
>     raise exact[string](message)                                                                                                                        
> ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.                                                      
>                                                                                                                                                         
> The above exception was the direct cause of the following exception:                                                                                    
>                                                                                                                                                         
> Traceback (most recent call last):                                                                                                                      
>   File "/home/pi/Documents/freqtrade/freqtrade/freqtradebot.py", line 720, in create_stoploss_order                                                     
>     order_types=self.strategy.order_types)                                                                                                              
>   File "/home/pi/Documents/freqtrade/freqtrade/exchange/binance.py", line 83, in stoploss                                                               
>     f'Message: {e}') from e                                                                                                                             
> freqtrade.exceptions.DependencyException: Insufficient funds to create stop_loss_limit sell order on market EOS/BTC.Tried to sell amount 13.84 at rate 0.
> 0002958. Message: binance Account has insufficient balance for requested action.

**Comment by hroff-1902** [comment]
^^ formatted, reopened (for @xmatthias to review)

**Comment by xmatthias** [comment]
@devilsinthedetail please open a new issue for new problems, even though they seem related.
Please also don't forget to fill out the issue form which will let us know which version you're using.

Also, for this type of error, we'll need the logs from the time of the buy for this trade. Just this section is non-conclusive.

**Comment by squat0001** [comment]
Hi!

sorry for being late.
the prolem arises when i use more than one bot, but do not have enough
funds on binance.

so if its a bug, it would be that the bot simple has to catch the
exception and maybe tell the user via telegram
that it run out of funds unexpected.

greetings

Am 01.05.2020 um 13:25 schrieb Matthias:
