### ISSUE TITLE
Fiat_Convert.py Not working Properly

### ISSUE THREAD

**Issue by rnaveen99-github** [freqtrade/freqtrade#2865]
# While running /profit (in Telegram), it returns an empty fiat currency.
**All USD conversations return 0.00 USD or the BTC value**

**Observed Results:**
Bittrex: Selling
Current Pair: ETH/BTC
Limit: 0.081371
Amount: 0.24669734
Open Rate: 0.08107100
Current Rate: 0.08137100
Profit: 0.17% (profit: 0.17%, 0.00003393 BTC / **0.000 USD**)

**Expected results:**
Bittrex: Selling
Current Pair: ETH/BTC
Limit: 0.081371
Amount: 0.24669734
Open Rate: 0.08107100
Current Rate: 0.08137100
Profit: 0.17% (profit: 0.17%, 0.00003393 BTC / **0.290 USD**)

Please help me why I see **0.000 USD** in the profit.

**Comment by hroff-1902** [comment]
please fill in the form with data:

## Step 2: Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)

**Comment by xmatthias** [comment]
In addition to that, we'll need the logs of the bot.

Once at startup - and once when the sell occured - checking for errors.

We've had this happen when coinmarketcap had some problems a few months ago - which led to either coinmarketcap not being started up correctly (hence the startup-logs) - or did not properly update when used (hence the logs when the sell occured).

Related issue from december: #2589

**Comment by rnaveen99-github** [comment]
Operating system: Ubuntu
Python Version:  Python3

**Comment by rnaveen99-github** [comment]
Thanks xmatthias for your suggestions. The bot works fine now.

**Comment by hroff-1902** [comment]
can be closed?

**Comment by rnaveen99-github** [comment]
Yes, it can be closed. Thank you.
