### ISSUE TITLE
Running freqtrade on AWS EC2 (VPS) 

### ISSUE THREAD

**Issue by King-Techno** [freqtrade/freqtrade#2868]
OS: Ubuntu

Do I have to re-install freqtrade on my vps or can I just transfer the freqtrade folder + files to my VPS? Also are there any specific files that are required to run my bot on the VPS without me having to transfer the whole folder?

**Comment by xmatthias** [comment]
You can install docker and use the [docker image](https://www.freqtrade.io/en/latest/docker/) - so you don't have to install freqtrade directly (that's how i run freqtrade - as it allows to provision a new server within minutes - while installing all dependencies tends to take a lot longer.

Without docker - you'll need to install certain things.
You should be able to copy the virtual environment **if the system architecture / OS is identical** - so you only need to install the binary ta-lib dependency.
On the other hand - the slowest thing to install is ta-lib - so you'll not gain too much if it's about speed of installation.

my personal recommendation - use docker. 
ta-lib is sometimes picky when running on a system with low memory.

**Comment by King-Techno** [comment]
Thank you, I am going to try and install it now. Hopefully, I do not run into any problems

**Comment by King-Techno** [comment]
Do I have to use `sudo snap install docker` to install it on my VPS? before I run `docker pull freqtradeorg/freqtrade:develop`. I am very new to docker

**Comment by King-Techno** [comment]
I got the error:

```
docker pull freqtradeorg/freqtrade:develop
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/images/create?fromImage=freqtradeorg%2Ffreqtrade&tag=develop: dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by King-Techno** [comment]
Okay I am meant to run it from my terminal on my computer not my VPS just realised haha

**Comment by King-Techno** [comment]
After I have run the command `docker pull freqtradeorg/freqtrade:develop`

I am still getting this message on my docker app?

No containers running...
...please start one from your terminal.

How do I get my docker up and running so i can clone from git hub?

**Comment by xmatthias** [comment]
Well - by following the instructions in the documentation?

you will do the clone outside of docker - create the configurations (copy them from your local machine?) - and then start it as explained [in the documentation](https://www.freqtrade.io/en/latest/docker/#run-the-docker-image).

To be honest, it's all on the page i linked above  ...

**Comment by King-Techno** [comment]
I have literally followed all the steps. I can not download TA-Lib and even when i try to run `docker run --rm -v `pwd`/config.json:/freqtrade/config.json -it freqtrade` it fails and doesn't appear on docker. 

I have been at this for so long, none of the documentation is working for me when installing TA-Lib. Is it because I am using Ubuntu 18.04???

**Comment by xmatthias** [comment]
i think you need to pick one way.
Either - you use docker. Alternatively - you'll need to install ta-lib.

You will not need both.

Now assuming the docker point - the command you list is a basic sample command.
To run it properly, scroll down a bit to [this point](https://www.freqtrade.io/en/latest/docker/#run-the-docker-image_1).

The command will look somewhat like the below:

```
docker run -d \
  --name freqtrade \
  -v ~/.freqtrade/config.json:/freqtrade/config.json \
  -v ~/.freqtrade/user_data/:/freqtrade/user_data \
  -v ~/.freqtrade/tradesv3.sqlite:/freqtrade/tradesv3.sqlite \
  freqtrade trade --db-url sqlite:///tradesv3.sqlite --strategy MyAwesomeStrategy
```

Now obviously you'll need to make sure that the paths are matching your environment - and you need to create the database file first (`touch ~/.freqtrade/tradesv3.sqlite` - in the above case).

**Comment by King-Techno** [comment]
I think my issue is when I am creating the database file.

Do I just have to enter `touch tradesv3.sqlite
````

Dry-Run

```bash
touch tradesv3.dryrun.sqlite` into the terminal?

I have never created a database file before.

**Comment by King-Techno** [comment]
I am getting the error message, when itry to run my strategy on freqtrade:

`docker: Error response from daemon: Conflict. The container name "/freqtrade" is already in use by container "51ec07f50e889919c7fd5302f5e9d013d5cc1998c44232161fa442e943". You have to remove (or rename) that container to be able to reuse that name.`

**Comment by hroff-1902** [comment]
-- the `touch` command simply creates an empty file
-- when you run the bot outside a container, that's not needed -- the bot creates the db file by itself if that does not exist
-- however, when you run bot in a container, you need the file in the filesystem to mount into the container, and you need it when you start the container, i.e. before the bot starts inside the container and have a chance to create the file
-- thus you need this command to be applied before you start the container (to create an empty db file which is then specified to be mounted into the container)

**Comment by King-Techno** [comment]
Thank you, that makes sense. So I ran the command ```
docker run -d \
  --name freqtrade \
  -v ~/.freqtrade/config.json:/freqtrade/config.json \
  -v ~/.freqtrade/user_data/:/freqtrade/user_data \
  -v ~/.freqtrade/tradesv3.sqlite:/freqtrade/tradesv3.sqlite \
  freqtrade trade --db-url sqlite:///tradesv3.sqlite --strategy <My Strategy>
```
and after that I am getting a long container code Example:`cfcf61f5d23e857ff4773ec3936ed544ca6949c0c0c6958bc` "Not actual code". I think this indicates the container has been created.

I then checked back to my docker application and nothing is running. The set up of this should be straight forward but I am not sure why I am having so many hurdles :(

**Comment by xmatthias** [comment]
how are you checking if it's running?

best run `docker ps`. If that returns nothing, try `docker ps -a`.
You can always check what was wrong by using `docker logs <the_id_you_just_got>` - so `docker logs cfcf61f5d23e857ff4773ec3936e4ca6949c0c6958bc` in your case.

I assume it's crashing with "something" - the logs should tell you what's wrong - without them it could be anything and everything...

**Comment by King-Techno** [comment]
I am getting the error:

`Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 33, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 46, in _init
    self._config = Configuration(self._args, None).get_config()
  File "/freqtrade/freqtrade/configuration/configuration.py", line 41, in get_config
    self.config = self.load_config()
  File "/freqtrade/freqtrade/configuration/configuration.py", line 94, in load_config
    config: Dict[str, Any] = self.load_from_files(self.args.get("config", []))
  File "/freqtrade/freqtrade/configuration/configuration.py", line 73, in load_from_files
    config = deep_merge_dicts(load_config_file(path), config)
  File "/freqtrade/freqtrade/configuration/load_config.py", line 26, in load_config_file
    with open(path) if path != '-' else sys.stdin as file:
IsADirectoryError: [Errno 21] Is a directory: 'config.json'`

I do not understand this error statement. I think there is something wrong with my config file?

**Comment by hroff-1902** [comment]
(^^ formatted)

**Comment by hroff-1902** [comment]
if you still mount it as 
```
docker run -d \
  --name freqtrade \
  -v ~/.freqtrade/config.json:/freqtrade/config.json \
```
pls give us output of 
`ls -la ~/.freqtrade/`

**Comment by King-Techno** [comment]
The output is:

```
drwxr-xr-x   6 charles  staff   192  7 Feb 13:55 .
drwxr-xr-x+ 61 charles  staff  1952  6 Feb 17:56 ..
drwxr-xr-x   2 charles  staff    64  6 Feb 17:56 config.json
drwxr-xr-x   2 charles  staff    64  7 Feb 13:55 tradesv3.dryrun.sqlite
drwxr-xr-x   2 charles  staff    64  6 Feb 17:56 tradesv3.sqlite
drwxr-xr-x   2 charles  staff    64  6 Feb 17:56 user_data
```

**Comment by hroff-1902** [comment]
you see, `config.json` here is a dir. 
`tradesv3.dryrun.sqlite` and `tradesv3.sqlite` are also dirs

**Comment by King-Techno** [comment]
So, only `config.json` is meant to be a directory? or just `tradesv3.dryrun.sqlite` and `tradesv3.sqlite`?

How should I go about resolving this please? Sorry for the lack of knowledge I am really new to this.

**Comment by hroff-1902** [comment]
> So, only `config.json` is meant to be a directory? 
hmm, what?
https://www.freqtrade.io/en/latest/configuration/#the-freqtrade-configuration-file

**Comment by hroff-1902** [comment]
> or just `tradesv3.dryrun.sqlite` and `tradesv3.sqlite`?

above ^^ we've been talking about touch utility: `touch tradesv3.sqlite`
the touch utility creates an empty *file*.
sorry, I completely do not understand what you are doing in your system

config.json should be a text file in json format and should contain your configuration parameters.
db files are to be empty files, created (for example, if you do not know other means how to do this) by the touch utility. When freqtrade starts in the container, it will write something into db and the db file will not be empty. But you can always recreate it as empty, loosing info on previous trades.

the user_dir should be a dir with your strategy in the 'strategies' subdir, specified in the command line option to freqtrade...

**Comment by King-Techno** [comment]
I think maybe an issue is when i enter `touch tradesv3.dryrun.sqlite` it doesn't create an empty database. I only have the  `tradesv3.sqlite` file in my freqtrade folder.

**Comment by hroff-1902** [comment]
Show me
```
rm -fr tradesv3.dryrun.sqlite
touch tradesv3.dryrun.sqlite 
ls -l tradesv3.dryrun.sqlite
```

**Comment by hroff-1902** [comment]
> I only have the `tradesv3.sqlite` file in my freqtrade folder.

wrong: 1) it's not about `freqtrade` dir, but about `~/.freqtrade/` directory 2) `tradesv3.sqlite` in that dir is not a file but a dir

**Comment by hroff-1902** [comment]
man, pls collect all this together: maybe you are looking into files in the wrong (current) dir, while mounting files from another dir (`~/,freqtrade`), and there are subdirs there that should actually be files, touch does not probably work either because you are creating a file in the wrong dir, or because the file name is taken by a subdir which should not be there...

**Comment by King-Techno** [comment]
ohhh so I am meant to be in the `~/.freqtrade/` . dir and not the `freqtrade` dir when executing the command? I think that may be my issue

**Comment by King-Techno** [comment]
I think I have been using the wrong jargon which has caused confusion, my bad

**Comment by hroff-1902** [comment]
see, in the command 
```
docker run -d \
  --name freqtrade \
  -v ~/.freqtrade/config.json:/freqtrade/config.json \
  -v ~/.freqtrade/user_data/:/freqtrade/user_data \
  -v ~/.freqtrade/tradesv3.sqlite:/freqtrade/tradesv3.sqlite \
  freqtrade trade --db-url sqlite:///tradesv3.sqlite --strategy <My Strategy_name> 
```
you are mounting all the stuff from `~/.freqtrade/`. It can be any other dir, but it's `~/.freqtrade/` in your case (and in the example in the docs)

**Comment by King-Techno** [comment]
I am going to start the process over again and look over the files in my dir and subdirs. 

Sorry for the confusion, I know it must be frustrating. Please bare with me.

**Comment by hroff-1902** [comment]
just prepare properly that stuff which is mounted into container (see above what it should be)

**Comment by xmatthias** [comment]
honestly - @hroff-1902  is not the best to help with docker issues (sorry) 😆 

Let's revisit this last hour and correct a few statements made above:
You're running the following command (maybe with slightly different paths).

``` bash
docker run -d \
  --name freqtrade \
  -v ~/.freqtrade/config.json:/freqtrade/config.json \
  -v ~/.freqtrade/user_data/:/freqtrade/user_data \
  -v ~/.freqtrade/tradesv3.sqlite:/freqtrade/tradesv3.sqlite \
  freqtrade trade --db-url sqlite:///tradesv3.sqlite --strategy <My Strategy_name> 
```
If you now get the error `IsADirectoryError: [Errno 21] Is a directory: 'config.json'` - then this happens because the host mount points are not files / did not exist yet.

To explain what happens: `~/.freqtrade/config.json` from your system is mounted into the container. 
Since this file did not exist, docker created a folder - which freqtrade does not like. So to fix that - you should have a config.json **file** (this is important) at the location specified in the docker command.

The same is true for the database (the `touch` command pointed out above is there to fix this).

This `config.json` should be correspond to your desires - eventually including exchange keys - telegram token, ... and this can usually be reused from a local "test" - after maybe creating a new telegram bot.

### quick fixes

create a (valid) config.json file at `~/.freqtrade/config.json`.
Create a empty database file `touch ~/.freqtrade/tradesv3.sqlite` 


Then start the container using the above command again.

**Comment by King-Techno** [comment]
Walkthrough of steps I have taken:

1. The `config.json` & `tradesv3.sqlite` & `tradesv3.dryrun.sqlite` are in my freqtrade dir. I did this because this is where the empty databases automatically placed themselves when I used `touch`. Also, the config.json is naturally in this main `freqtrade` dir. As a result these things will be mounted from `~/freqtrade/` instead of ~/.freqtrade/

2. Because I have done this I have changed the command to:

```
docker run -d \
  --name freqtrade \
  -v ~/freqtrade/config.json:/freqtrade/config.json \
  -v ~/freqtrade/user_data/:/freqtrade/user_data \
  -v ~/freqtrade/tradesv3.sqlite:/freqtrade/tradesv3.sqlite \
  freqtrade trade --db-url sqlite:///tradesv3.sqlite --strategy <My Strategy_name>
```
3. After running this command I produced a log and then I ran `docker logs <my_log>`

4. The output of that was:

```
2020-02-07 15:25:06,363 - freqtrade.loggers - INFO - Verbosity set to 0
2020-02-07 15:25:06,363 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2020-02-07 15:25:06,363 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2020-02-07 15:25:06,364 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2020-02-07 15:25:06,364 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 15 ...
2020-02-07 15:25:06,364 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2020-02-07 15:25:06,364 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2020-02-07 15:25:06,365 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-02-07 15:25:06,365 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-02-07 15:25:06,365 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-02-07 15:25:06,365 - freqtrade.freqtradebot - INFO - Starting freqtrade develop
2020-02-07 15:25:06,412 - freqtrade - ERROR - Impossible to load Strategy 'bbADXRSI'. This class does not exist or contains Python code errors.
```

5. This indicates that everything is working well except from my strategy file. At this point, I am not sure what to do to fix this. The file works fine when I run it from my laptop but not through Ubuntu VPS.

**Comment by xmatthias** [comment]
Well that's 10 steps forward i think...

Where is the strategy file located?

Best make sure to have the strategy (`bbADXRSI`) in `~/freqtrade/user_data/strategies/`. While there are other ways - that'll be the simplest.

**Comment by hroff-1902** [comment]
> honestly - @hroff-1902 is not the best to help with docker issues (sorry) 😆

Right, I was just wondered that the config is a dir.

> Since this file did not exist, docker created a folder

Did not know that. 🙄

**Comment by xmatthias** [comment]
> Did not know that. 🙄
Yes, that became clear ... 

this caused my above comment about "not the best" - and i know you're not a regular docker user ... :) so no offense i hope

**Comment by King-Techno** [comment]
ITS WORKING!!!!!!!!  Thank you both so much!!!!

**Comment by hroff-1902** [comment]
> > Did not know that. 🙄
> 
> Yes, that became clear ...
> 
> this caused my above comment about "not the best" - and i know you're not a regular docker user ... :) so no offense i hope

No, no, I have not perceived this as such, not at all 👍
