### ISSUE TITLE
Proposal for setup.sh

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2871]
We should not ask for installing development dependencies in setup.sh -- they are to be installed manually as `pip install -r requirements-dev.txt` by those who need them.

Instead, we should ask for installing hyperopt in this place of script.

And, the answer is to be hardcoded as 'N' for arm platforms (RPI and other boards).

**Comment by xmatthias** [comment]
why ask for hyperopt, but not for plot ? (needs to be called seperately via `./setup.sh -p`).

We should align the 2 - either ask for both - or make both as seperate call (`./setup.sh -o` - for Optimize)?

Apart from that i think we should keep in mind that the `setup.sh` script will probably lose 90% of it's users if freqtrade can be sanely installed from pypi - so i wonder how much time we should invest in this script ...

**Comment by hroff-1902** [comment]
right, 1) ask for hyperopt, 2) ask for plot; if not installed, can later be installed separated with those `-o` and `-p` options... (maybe also `-d` for dev deps, but no question for this during main install procedure)

I suppose setup.sh will be alive till May at least, so some polishing is okay in my opinion...
