### ISSUE TITLE
/status table not showing complete information

### ISSUE THREAD

**Issue by yazeed** [freqtrade/freqtrade#2874]
When using /status table with the RPC telegram bot, it returns existing trades (bought pairs) mixed with open buy orders (pending orders) without any way to differentiate between them.

This is not truthful to the purpose of the function, in the sense that it should convey the difference between these two types, since it also shows Profit, which is false for buy orders that haven't been filled.

This is to log that issue, until a PR I plan to work on is introduced.

We can also discuss how to solve this.

I'm thinking we can add an asterisk (*) next to pairs that aren't owned yet, and to show 0 profit for those. In the sqlite database these can be differentiated by open_order_id.

We can also expand this potential enhancement to show open_bid for those open orders, and open_rate for existing pairs, and current_bid.

Would love to hear your thoughts.

I'm focused at the moment on consistency to polish freqtrade in such areas in small iterations.

**Comment by xmatthias** [comment]
Well yeah - but there's another part to this too ...
while `/status` shows you this trade while the order is still open - the notifications in case of a cancel are not consistent.

* A notification is sent on buy
* a notification is sent on sell
* **NO** notification is sent on buy cancel

So if you rely on these notifications alone - you think the bot is in a position while it really cancelled the order.
Now *most orders (on higher volume pairs) fill almost instantly ... so it's not a huge issue - but it's still something i think somehow fits to this issue.

#2646 hints to something similar - but from the other direction - that a open buy order cannot be cancelled via RPC.
