### ISSUE TITLE
Bittrex Partially Filled Order Causes Fatal Exception

### ISSUE THREAD

**Issue by Smone5** [freqtrade/freqtrade#2893]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04.3 LTS 
  * Python Version: Python 3.6.9 (`python -V`)
  * CCXT version: ccxt==1.22.30 (`pip freeze | grep ccxt`)
  * Branch: Honeslty not sure. I use the setup -i to install, but I usually install the developer dependecies
  * Last Commit ID: b5ee4f17cb610cba273c2663112d6fe4f60154b9 (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:
The bot crashes on a partially filled order using Bittrex. 

### Steps to reproduce:

  1. Bot places order using ask price and 5min ticker
  2. The unfilled buy timeout is set for 15min
  3. Volume filter set for top 20 in quote volume
  4. Precision filter is set and with price filter set to low price ratio of 0.01
  
### Observed Results:

  * What happened?
 The bot has a fatal exception if the order is only partially filled after 15min. If I restart the bot, it assumes it filled 100% and will eventually try to sell the quantity but will fail because the quantity I own on the exchange is less than the quanity the bot is trying to sell. 

  * What did you expect to happen? 
I exepcted if an order is partially filled, the bot does not crash. Instead, it communicates to the exchange and updates the quantity in the bot/sqllite3 trades table with the actual partially filled quantity on the exchange. Allowing the bot to use it's exit strategy and stop loss. 

### Relevant code exceptions or logs:
```
2020-01-29 10:19:25,707 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/root/freqtrade/freqtrade/utils.py", line 58, in start_trading
    worker.run()
  File "/root/freqtrade/freqtrade/worker.py", line 71, in run
    state = self._worker(old_state=state)
  File "/root/freqtrade/freqtrade/worker.py", line 109, in _worker
    self._throttle(func=self._process, min_secs=throttle_secs)
  File "/root/freqtrade/freqtrade/worker.py", line 122, in _throttle
    result = func(*args, **kwargs)
  File "/root/freqtrade/freqtrade/worker.py", line 132, in _process
    self.freqtrade.process()
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 144, in process
    self.check_handle_timedout()
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 802, in check_handle_timedout
    self.handle_timedout_limit_buy(trade, order)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 843, in handle_timedout_limit_buy
    trade.amount = order['amount'] - corder.get('remaining', order['remaining'])
TypeError: unsupported operand type(s) for -: 'float' and ‘NoneType'
```

![Screen Shot 2020-01-29 at 9 26 58 AM](https://user-images.githubusercontent.com/19376953/74114671-6c666f80-4b79-11ea-84a8-67186b661cda.png)

**Comment by hroff-1902** [comment]
(formatted attached log)

**Comment by xmatthias** [comment]
To debug this further i'll need to ask you to do a "bit" of digging for me.

I'll try to provide template code as much as possible ... but certain things are unknown to me so will need your own input.

please open the database (`sqlite3 tradesv3.sqlite`) (i hope you still got it) and run the following query:

``` sql
select id, pair, open_order_id from trades where id = 16;
```

take note of the "open_order_id" field and use it in the below query:

```python
import ccxt
ct = ccxt.bittrex({'apiKey': '<yourAPIKey>', 'secret': '<your_secret'})
order = ct.fetch_order('<order_id_from_database>', 'LSK/BTC')
print(order)

```

This should print a json string to screen. 
I'd need that to see what the filled fields look like (unfortunately i don't have many coins on bittrex - and i've never been so "fortunate" to have a order half-filled).

**Comment by Smone5** [comment]
Luckily I made a snapshot, other wise it would be gone. 

Query result:
16|LSK/BTC|496468af-07d8-4f06-bc1f-681ef736787b

Print Result:
`{'info': {'AccountId': None, 'OrderUuid': '496468af-07d8-4f06-bc1f-681ef736787b', 'Exchange': 'BTC-LSK', 'Type': 'LIMIT_BUY', 'Quantity': 360.10185777, 'QuantityRemaining': 356.81926154, 'Limit': 9e-05, 'Reserved': None, 'ReserveRemaining': None, 'CommissionReserved': None, 'CommissionReserveRemaining': None, 'CommissionPaid': 7.3e-07, 'Price': 0.00029543, 'PricePerUnit': 9e-05, 'Opened': '2020-01-29T10:07:51.34', 'Closed': '2020-01-29T10:19:03.91', 'IsOpen': False, 'Sentinel': None, 'CancelInitiated': True, 'ImmediateOrCancel': False, 'IsConditional': False, 'Condition': 'NONE', 'ConditionTarget': 0.0}, 'id': '496468af-07d8-4f06-bc1f-681ef736787b', 'timestamp': 1580292471034, 'datetime': '2020-01-29T10:07:51.034Z', 'lastTradeTimestamp': 1580293143091, 'symbol': 'LSK/BTC', 'type': 'limit', 'side': 'buy', 'price': 9e-05, 'cost': 0.00029543, 'average': 9e-05, 'amount': 360.10185777, 'filled': 3.2825962299999674, 'remaining': 356.81926154, 'status': 'canceled', 'fee': {'cost': 7.3e-07, 'currency': 'BTC'}}`

**Comment by xmatthias** [comment]
well it may or may not fill enough to be sold - that's a different issue. it should still not cash the bot.

Will have a look ...

**Comment by hroff-1902** [comment]
@Smone5 hi, the fix which should resolve it was merged (current develop branch), pls verify
