### ISSUE TITLE
Sample code in doc Strategy Customization > Orderbook seems wrong

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2911]
Hi,

the following code coming from docs don't work :

```
    if self.dp.runmode in ('live', 'dry_run'):
        ob = self.dp.orderbook(metadata['pair'], 1)
        dataframe['best_bid'] = ob['bids'][0][0]
        dataframe['best_ask'] = ob['asks'][0][0]
```

because `self.dp.runmode` returns an enum `RunMode.LIVE` or `RunMode.DRY_RUN` and never 'live' or  'dry_run'

Maybe

```
from freqtrade.state import RunMode
   if self.dp.runmode in (RunMode.LIVE, RunMode.DRY_RUN):
        ob = self.dp.orderbook(metadata['pair'], 1)
        dataframe['best_bid'] = ob['bids'][0][0]
        dataframe['best_ask'] = ob['asks'][0][0]
```

not sur the more elegant way

Have a nice day

**Comment by xmatthias** [comment]
You're right - the right comparison would be `self.dp.runmode.value in ('live', 'dry_run')`.

that'll avoid having to import ... although that would also work
