### ISSUE TITLE
Include more data to hyperopt output

### ISSUE THREAD

**Issue by Fredrik81** [freqtrade/freqtrade#2913]
I would like to see that total win/loss trades are recorded. this is interesting data when searching for good strat.
If data is stored with the hyperopt then it can be displayed and used when reviewing the hyperopt result and even filtered when using hyperopt list.

Example:
   119/1096:     97 trades, 93 Win, 4 Loss. Avg profit   0.11%. Total profit  0.00061558 BTC (  10.25Σ%). Avg duration 506.6 min. Objective: 2.19842

Thoughts?

**Comment by hroff-1902** [comment]
My proposal:
You can start by adding the table output format (enabled by `--print-table`, for example) into `hyperopt-list`. The table format will save lot's of space in the output so the new columns can be added there to have the output more aligned to output of backtesting (or even same with the addition of the values of the loss-function, number of the epoch and other possible columns specific for hyperopt)

**Comment by orehunt** [comment]
hyperopt results tabulation is not cheap, maybe it shouldn't be the default when running the optimization...

**Comment by xmatthias** [comment]
> hyperopt results tabulation is not cheap

what do you mean with cheap? the computational power needed to generate the table?

**Comment by hroff-1902** [comment]
need to compare the performance btw, we did not do it
between master and current tabular

**Comment by xmatthias** [comment]
This is actually iplemented - we are now showing Win / draw / losses as part of the hyperopt output table.

**Comment by Stonk8** [comment]
I can't see it in hyperopt-list csv export. Should it? I would like it for post processing (win rate)
