### ISSUE TITLE
Live trading: missing last candle?

### ISSUE THREAD

**Issue by yilongwen** [freqtrade/freqtrade#2924]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Ubuntu 16.04
  * Python Version: 3.6 (`python -V`)
  * CCXT version:  1.21.32 (`pip freeze | grep ccxt`)
  * Branch: Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

I printed the 'dataframe' when running the bot live. I reckon that that last candle is missing, since the "ohlcv_candle_limit" is 500, and it printed row 0-498. Also the parameter "process_only_new_candles" is set to false, which means partial(incomplete) candle should be shown. Does anyone have an idea about this?

### Steps to reproduce:

  1. Run the bot .
  2. Add print statement in strategy file.

  
### Observed Results:

  * What happened?
Last row(most recent) row did not show.
  * What did you expect to happen?
Last row to show.

### Relevant code exceptions or logs:

  ```
date     close   volume
496 2020-02-15 09:45:00+00:00  0.000192  2103.80
497 2020-02-15 10:00:00+00:00  0.000192  5607.46 
498 2020-02-15 10:15:00+00:00  0.000191  9164.32 
2020-02-15 10:34:04,349 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=3743
  ```

**Comment by hroff-1902** [comment]
which exchange you are working with?

**Comment by yilongwen** [comment]
Thanks for the quick reply! I'm on Binance. 
So even though if the specified param "process_only_new_candles" is set to false, it still only shows when the candle has been completed?

**Comment by xmatthias** [comment]
To me, this looks ok (no matter which exchange, really).
As @hroff-1902 mentions above - the last **complete** candle (10:15-10:30 )is there (timestamps indicate the start of the candle, not the end).

Freqtrade won't give you the last incomplete candle as indicators would not know this, which would lead to repainting (changing indicators within one candle until the candle is complete).

**Comment by yilongwen** [comment]
Ah okay, thanks for clarifying that!

**Comment by hroff-1902** [comment]
more words on it should be added into docs

**Comment by xmatthias** [comment]
I'm not sure ... seems pretty clear to me (?) 

> Enable processing of indicators only when new candles arrive. If false each loop populates the indicators, this will mean the same candle is processed many times creating system load but can be useful of your strategy depends on tick data not only candle.

**Comment by hroff-1902** [comment]
I mean, better description for the question in the original post, regarding the dataframe used in dry/live mode, how it's prepared, not for the process_only_new_candles setting.

**Comment by hroff-1902** [comment]
@yilongwen can this issue be closed?

**Comment by yilongwen** [comment]
Yes, Thanks! :)

**Comment by ek-ex** [comment]
I know this is a pretty old so I apologize. But is there any use-case where the open, partial or incomplete candle is valid? Maybe an early RSI crossover where one could act immediately. Is there such use-case?

**Comment by Axel-CH** [comment]
If you want your bot to be more reactive, you can lower used base timeframe.

Incomplete candles are not used to create signals, such usage would lead to unreliable signals.

The only case usage of incomplete candles could be acceptable is for custom order pricing and this is not yet available.

**Comment by xmatthias** [comment]
Letme correct the above slightly.
incomplete candles are not available - and won't be available in the future, either.

It'll lead to repainting signals - as most indicators calculate on the candle close (which is a moving target for an un-closed candle).
As this issue is 5 years old in the meantime, i'm going to close this - as facts didn't change - but every comment here will ping everyone in this issue.
