### ISSUE TITLE
Buy/sell triggers not being sent at right times...bad losses

### ISSUE THREAD

**Issue by djacky** [freqtrade/freqtrade#2926]
## Step 2: Describe your environment

  * Operating system: Raspberry pi 4 (4GB)
  * Python Version: 3.7.3 (`python -V`)
  * CCXT version: ccxt == 1.22.30 (`pip freeze | grep ccxt`)
  * Branch: Develop
  * Last Commit ID: b5ee4f17cb610cba273c2663112d6fe4f60154b9 (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

The buy and sell triggers (during real trading) are not being sent properly...This has caused some large losses...

During backtesting, the buy/sell triggers seem consistent, and the orders are being placed at the right times. But in real trading, the buy/sell signals are not being sent at the right times, and has caused some large losses on my part...This is quite concerning since timing is of huge importance...

I will explain this issue with some plots.
Below is a backtest plot for the pair WPR/BTC (with 1h ticker intervals). For the buy trigger to be set, the black indicator needs to cross 0 from below (with another condition). For the sell trigger to be set, the black indicator needs to cross 0 from above (with another condition).

From the backtest plot below, you can see that the buy and sell signals were not properly triggered at the right times, and caused me to take a big loss. The black line never crossed zero (from below) when the buy order was sent...

Why did this happen? Are the indicators during backtest and real trading processed differently?

![image](https://user-images.githubusercontent.com/25647528/74589660-50dee700-5007-11ea-8506-f3aed3cea1d1.png)

![Screen Shot 2020-02-15 at 3 32 46 PM](https://user-images.githubusercontent.com/25647528/74589809-fba3d500-5008-11ea-87d3-0862930eb730.png)

**Comment by xmatthias** [comment]
well the most likely reason is that there is a problem with how you calculate the "black line".

Indicators are calculated identically during backtesting and live - however live has "limited" availability of data (limited to 499 historic candles).
Certain indicators suffer from this and calculate slightly different results (I've especially observed this with EMA - usually it evens out after enough candles - but not always depending on the precise formulae used).

Honestly, impossible to tell you for sure without seeing the strategy. 
Sometimes it becomes apparent while looking at it, sometimes the problems are more subtle and require a more detailed analysis.

Feel free to send it to me via PM on slack (or github) and i'll have a closer look ...

**Comment by hroff-1902** [comment]
![lklkjlkjlkj](https://user-images.githubusercontent.com/47309513/74591419-e2ab1c00-5028-11ea-8957-44578ec86474.png)

I added numbers to the candles.
The indicator is above 0 at candle 1 and is below 0 at candle 2. So it does crosses 0 line below.
And since both candles are available when candle 3 starts, the bot detects it and buys at the beginning of the candle 3.

For me, anything is okay.

**Comment by djacky** [comment]
@xmatthias The black indicator does involve an EMA calculation, and only uses a timeperiod of 10. So I don't think it's a problem of limited data. I started the strategy on February 9 at 10pm, and the WPR/BTC buy signal triggered on February 11 4am, so I think enough time passed to even out the EMA. I think something else is going on here...

@hroff-1902 No, the buy signal should only be triggered when the black line crosses zero FROM BELOW, not from above. The case you stated crosses zero from above.

**Comment by hroff-1902** [comment]
> @hroff-1902 No, the buy signal should only be triggered when the black line crosses zero FROM BELOW, not from above. The case you stated crosses zero from above.

Show us, how have you implemented this condition?

**Comment by djacky** [comment]
@hroff-1902 Here you are:
![Screen Shot 2020-02-15 at 5 37 47 PM](https://user-images.githubusercontent.com/25647528/74591733-aec8fa00-501a-11ea-818d-bb01d766eed2.png)

**Comment by hroff-1902** [comment]
I mean how have you implemented this buy condition ("crosses zero FROM BELOW") in the code.

**Comment by djacky** [comment]
@hroff-1902 `(qtpylib.crossed_above(dataframe['buy_trigger'], 0))`

**Comment by hroff-1902** [comment]
from the charts, looks very close if the condition is reversed...

**Comment by djacky** [comment]
> from the charts, looks very close as if the condition is reversed...

I'm not quite sure what you mean. For me, it's clear that when the black line crosses zero from below, the buy order is sent. The backtest results are consistent on this...it's in real trading where the error occurs...

**Comment by djacky** [comment]
@xmatthias I sent you a sample of the strategy via Slack.

**Comment by hroff-1902** [comment]
you can duplicate it to me as well...

**Comment by djacky** [comment]
@hroff-1902 done :)

**Comment by xmatthias** [comment]
After looking at it - i think the problem is clear - the "np" function behaves slightly different if the current value is the last value in the array (which in real-mode is always the case - but in backtesting it's not).

I've explained the details via slack - since the strategy is also not "public" i think there's not too much left for us here.

**Comment by djacky** [comment]
Yup, thanks @xmatthias !

**Comment by King-Techno** [comment]
I am having the same issue. I set my strategy to only buy when the close price is below the Bollinger band. However, it bought when it was above. If you see the image below it shouldn't have bought. I lost a huge amount because of this.

![image](https://user-images.githubusercontent.com/53098717/74600674-ab6e5680-508c-11ea-9b65-e077e1655c51.png)

**Comment by hroff-1902** [comment]
@King-Techno pls open a new issue for this.

**Comment by hroff-1902** [comment]
@King-Techno pls open a new issue for this.

**Comment by djacky** [comment]
@xmatthias After thinking about this, i'm still confused as to why the buy signal (in live trading) would have been triggered if the "black line" never crossed the 0 point...Even if the array had a lookahead bias, why would it trigger the buy signal in real trading?

**Comment by hroff-1902** [comment]
https://docs.scipy.org/doc/numpy/reference/generated/numpy.gradient.html says:

"using second order accurate central differences" -- this is applicable during backtesting, when "black line" is calculated in the whole backtesting timerange
and
"and either first or second order accurate one-sides (forward or backwards) differences at the boundaries" -- that's for the case of dry/live run, when the signal (last row) as at the boundary of the dataframe rows.

you can add printing of values of your "blackline" and have a look at the values to see why it's detected as crossed_above during dry/live runs

**Comment by djacky** [comment]
@hroff-1902 Thanks. How can I print the indicator values (and trigger times) in real time while running in live mode?

**Comment by hroff-1902** [comment]
something like this:
```
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        ...
        print (dataframe[['date'], ['close'], ['your_indicator1'], ['your_indicator2']].tail(10))
        return dataframe
```

**Comment by djacky** [comment]
Thanks. I'll keep you guys updated on the results.
