### ISSUE TITLE
Pair list filter enhancement that checks the liquidity of the orderbook in the static white list.

### ISSUE THREAD

**Issue by kobertkirk** [freqtrade/freqtrade#2928]
Filter out pairs for which the sum of first N entries in the orderbook (in stake currency XYZ) is less than M XYZ or less than K (say, 3) stake amount values'... and optionally sort pairs by that sum of amounts in the orderbook (first N entries).

Props to hroff-1902

**Comment by xmatthias** [comment]
i am not certain if / how this should work, considering orderbook is changing multiple times per second.

Depending on luck (or no luck) - you might end up with an almost empty pairlist, just because the pairlist update ran at an unfortunate time - even though the orderbook had a ton of liquidity added a splitsecond later (or viceversa, liquidity is pulled and you're buying into it nonetheless).

You might be better of looking at a rolling volume - as the orderbook can be manipulated quite easily ... faking liquidity where there is none (pulling it out the last second).

**Comment by hroff-1902** [comment]
I thought about similar, there is the similar setting in the "blackbird" bot, for example:

> OrderBookFactor | 3.0 | In order to be executed as fast as possible and avoid slippage, Blackbird checks the liquidity in the order books of the exchanges and makes sure there are at least 3.0 times the needed liquidity before executing the order

**Comment by kobertkirk** [comment]
I've looked at a way to simulate market buys and sells within a certain threshold in the the order book. The same could be used to accomplish not filtering the pair list but avoid buying into a pair that would have no liquidity to begin with.

Something like:

Condition to buy or sell is triggered in straegy.py.
Get snapshot of the first x number of limit orders (x being a variable set by user). 
Average the price and volume (y).
Check to see if y is with in threshold z (z being how much the price would be compared to last price bought or sold and user's stake).

It would be better to see what the slippage could be than to not and have a higher slippage when buying or selling. I've only glanced at freqtrade code. So I haven't a clue of how to implement it my self.

**Comment by hroff-1902** [comment]
> Check to see if y is with in threshold z

That's completely different with the original approach suggested in the starting message, as I see -- the original suggestion was about checking the liquidity of the orderbook side and filter pairs on it, the latter is an attempt to implement a strategy utilizing so-called Static Orderbook Imbalance (SOBI). The latter can be done in the strategy itself and should not be (and probably cannot be) implemented as a pairlist filter.

**Comment by kobertkirk** [comment]
Yes it is a different approach but similar goal. Many alts follow BTC. If base currency is not BTC many alts would trigger. In this case skipping the undesirables. I think xmatthias is right about the manipulation. I've seen buying and selling of volumes that were never in the orderbook. The original approach would be a bad idea IMO. I could close this if you would like?

**Comment by kobertkirk** [comment]
As far as a SOBI goes why not havethat some kind of freqtrade standard with that in the strategy.py or some where else? Maybe configurable in the config.json. It would seem a pretty useful function.

**Comment by hroff-1902** [comment]
it can be easily implemented in the strategy, I placed once a sample implementation in the strategy-sharing channel, IIRC. (get orderbook data, separate both buy and sell parts, then calculate VWAP on them, and compare with the latest price from the ticker)

**Comment by kobertkirk** [comment]
Should I close or would a pair list filter on liquidity be a good feature in your opinion?

**Comment by hroff-1902** [comment]
As I said, I was thinking of it, but it requires pairlists be calculated at every bot throttling iteration (on current orderbook data) and it's not how pairlists and pairlist filters now work. So, yes, I think it can be closed...
