### ISSUE TITLE
Docker raspberry pi 4 installation

### ISSUE THREAD

**Issue by Amurmurmur** [freqtrade/freqtrade#2932]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Noob OS
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. `docker-compose -f ./docker-compose.technical.yml up`
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
Tried to run it within the docker environment on raspberry pi 4.
The same image (freqtrade technical) runs just fine on Windows and Mac machines however it throws the error below when trying to run on a raspberry pi4 running a Noob OS
  * What did you expect to happen?
Run as expected.

### Relevant code exceptions or logs:

  ```
pi@raspberrypi:~/Documents/freqtrade $ docker-compose -f ./docker-compose.pi.yml up
Building freqtrade_pi
Step 1/16 : FROM balenalib/raspberrypi3-debian:stretch
stretch: Pulling from balenalib/raspberrypi3-debian
6bc458b08134: Pull complete
c2ade603d2b2: Pull complete
41caef1d094d: Pull complete
7b09be146ceb: Pull complete
840fc53ec78e: Pull complete
e91616512c64: Pull complete
4fec01e2556c: Pull complete
891544b14a12: Pull complete
939e981e1f20: Pull complete
2955acf0b294: Pull complete
2a3e18d92ea9: Pull complete
Digest: sha256:21e2e176aa121b4ee0e16dec6a6610f2eee29eb1615251c52b7314e5d393281a
Status: Downloaded newer image for balenalib/raspberrypi3-debian:stretch
 ---> 75476cdc4cce
Step 2/16 : RUN [ "cross-build-start" ]
 ---> Running in f475e63bbc45
standard_init_linux.go:211: exec user process caused "exec format error"

  ```

**Comment by xmatthias** [comment]
The dockerfile we have for the raspberry - `Dockerfile.pi` is designed to be built on a x64 host using cross-compiling - and to then to run on the raspberry - building it on raspberry is not possible due to the cross-compiler not beeing ARM compatible.

While it is possible to build a native image on a raspberry - building that takes a few hours - and it's impossible in CI so we would not be able to build that for you.

what should work however is to use the prebuild PI image as source - and build it from there.

The dockerfile should then look as follows:

``` dockerfile
FROM freqtradeorg/freqtrade:develop_pi

RUN pip install technical

```

**Comment by Amurmurmur** [comment]
@xmatthias As always on top of the world! Thank you very much !!!
Yes thats what Im going to use Ill test it tonight and see if that works.

**Comment by xmatthias** [comment]
Did it work as expected or were you facing problems with the above snippet?

**Comment by hroff-1902** [comment]
@Amurmurmur pls give us feedback, has the issue been answered, can be closed?

**Comment by xmatthias** [comment]
Assuming this did work ... feel free to comment if not so we can reopen if necessary.

**Comment by techdadbkk** [comment]
@xmatthias newbie here...could you please write in detail on how this is done? Thanks!
