### ISSUE TITLE
Shorting with freqtrade 

### ISSUE THREAD

**Issue by King-Techno** [freqtrade/freqtrade#2942]
Is it possible to short with freqtrade. Instead of just profiting from buying and selling? If so could you please direct me on how this can be done.

**Comment by xmatthias** [comment]
This is not possible at the moment, but we're working towards it (however it'll take some time, as we want to design it correctly).

#892, #2312 and mainly #2183 all revolve around this - please search for open issues before opening a new issue.

**Comment by gaugau3000** [comment]
Even it is not a short in margin trading (borrow money). FTX exchange create tokens BEAR ([FTX tokens](https://ftx.com/tokens)) witch in a way simulate short. Some of these tokens are now included in binance witch is an exchange supported by freqtrade (FTX can be tested using freqtrade but may have issues).

**Comment by xmatthias** [comment]
I'll close this as duplicate.

**Comment by MauricioHorn** [comment]
1 Year ago someone make this question: " Is it possible to short with freqtrade. Instead of just profiting from buying and selling? If so could you please direct me on how this can be done" 

I would like to know if this is already available or not, and if not, it will be updated soon? Thanks!

**Comment by xmatthias** [comment]
@MauricioHorn Instead of asking the same exact question in 3 (!) different places - you could've simply referred to the [FAQ entry](https://www.freqtrade.io/en/stable/faq/#can-i-open-short-positions), or used the search To find open issues about this.
