### ISSUE TITLE
How to use Data Provider?

### ISSUE THREAD

**Issue by fbport** [freqtrade/freqtrade#2949]
Hi, i'm wondering how to use the Data Provider on my strategy. Can you share any example of use like returning the MACD.signal of other periods (5m, 15m) while the bot is running on 1m?

Thanks for answering!

**Comment by xmatthias** [comment]
We do have [documentation](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-dataprovider) which does cover how to load data from pairs you got in the informative section.

You'll then have to merge the informative dataframe to the real dataframe as shown in the [InformativeSample strategy](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/InformativeSample.py).

Calculationg indicators on top of it is then just a question of positioning it in the correct place (before the merge) - and avoiding naming collisions between the columns.

**Comment by hroff-1902** [comment]
also see an article by @Dante2333 : https://cryptocue.io/freqtrade-multiple-timeframes-using-resampling/

**Comment by xmatthias** [comment]
I'll assume this quesiton answered as no additional quesitons did arrise from our answers.

Please post here if you still have questions about this topic and we will reopen this.
