### ISSUE TITLE
Do not sell code override

### ISSUE THREAD

**Issue by King-Techno** [freqtrade/freqtrade#2958]
Hi,
I am just wondering if it is possible to add to my strategy a piece of code that says 'do not sell if the current price is under the entry price' ultimately, this will override my sell signal to prevent a sale at a lower price.

**Comment by xmatthias** [comment]
well - the [documentation](https://www.freqtrade.io/en/latest/configuration/#configuration-parameters) is your friend.

The option you're looking for is `ask_strategy.sell_profit_only`.

Similar to that, there's another option to disable sell-signal completely - but that's technically identical to `dataframe['sell'] = 0` - having no sell signal.
