### ISSUE TITLE
stochastic RSI in samplestrategy / template

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#2961]
## Describe the problem:

Based on some recent acivity in #sharing-strategies on slack, i think we should add a warning to the samples containing stochastic RSI - as it's calculation is ... not in line what you see on exchange / tradingview (not to say ta-lib calculates it wrong).

According to @hroff-1902 (on slack), finta implementation is different (but also broken).

# Potential solution

The slack-channel also includes a proposed new calculation method ... so i guess we could have that in technical (or evaluate how finta calculates stoch_rsi) - after it's evaluated.

I'm copy-pasting this here as slack messages disappear after 10k messages - and it's work we should not waste.

``` python
        # Slow Stoch RSI
        # Tried using the ta.STOCHRSI library by using the Fast %D as Slow %K and applying SMA(3) on that to get Slow %D, but results were very poor...
        # Also tried using Tulip library but that required more gymnastics to correct the format of the data this library returns was significant...
        # This remains our best option, and tracks the values on TradingView to a T.
        rsi = pd.DataFrame()
        fastk_rsi = pd.DataFrame()
        slowk_rsi = pd.DataFrame()
        rsi['close'] = ta.RSI(dataframe, timeperiod=14) # We put the results of the RSI calculation into a 'close' value to trick our library in processing this data as price action...
        rsi['max'] = ta.MAX(rsi, timeperiod=14) # Also store the max and min vlaues in temp space so we don't clutter our dataframe...
        rsi['min'] = ta.MIN(rsi, timeperiod=14)
        fastk_rsi['close'] = (rsi['close'] - rsi['min']) / (rsi['max'] - rsi['min']) * 100.0
        slowk_rsi['close'] = ta.SMA(fastk_rsi, timeperiod=3)
        dataframe['slowk_rsi'] = slowk_rsi['close']
        dataframe['slowd_rsi'] = ta.SMA(slowk_rsi, timeperiod=3)
```

**Comment by hroff-1902** [comment]
just compared with trading view -- RSI from ta-lib is 1-to-1 to tradingview values (if set same precision)...
But it's not that for Stochastic RSI -- the values are completely different...

**Comment by xmatthias** [comment]
this is not about RSI ... ;) 
but about STOCHRSI ... which there's issues around the web with ... :(

**Comment by Phunties** [comment]
This will generate the same S RSI as tradingview.

`        #StochRSI 
        period = 14
        smoothD = 3
        SmoothK = 3
        stochrsi  = (dataframe['rsi'] - dataframe['rsi'].rolling(period).min()) / (dataframe['rsi'].rolling(period).max() - dataframe['rsi'].rolling(period).min())
        dataframe['srsi_k'] = stochrsi.rolling(SmoothK).mean() * 100
        dataframe['srsi_d'] = dataframe['srsi_k'].rolling(smoothD).mean()`

**Comment by Phunties** [comment]
This will replicate tradingview's STOCHRSI

       ```
 #RSI
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)

        #StochRSI 
        period = 14
        smoothD = 3
        SmoothK = 3
        stochrsi  = (dataframe['rsi'] - dataframe['rsi'].rolling(period).min()) / (dataframe['rsi'].rolling(period).max() - dataframe['rsi'].rolling(period).min())
        dataframe['srsi_k'] = stochrsi.rolling(SmoothK).mean() * 100
        dataframe['srsi_d'] = dataframe['srsi_k'].rolling(smoothD).mean()
```
