### ISSUE TITLE
Question about order_time_in_force = FOK

### ISSUE THREAD

**Issue by djacky** [freqtrade/freqtrade#2966]
Just a quick question about the FOK function in `order_time_in_force`.
In the freqtrade website, the following is stated:

> FOK (Full Or Kill):
It means if the order is not executed immediately AND fully then it is canceled by the exchange.

What does "immediately" mean here? Does it refer to the times set in `unfilledtimeout`?
So for example, if
```
    order_time_in_force = {
        'buy': 'fok',
        'sell': 'gtc',
    }

    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    }
```

Does this mean that if a buy order is not fully filled within 10 minutes, then it is permanently cancelled?

**Comment by xmatthias** [comment]
it's a setting for the order on the exchange.
[api-docs](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-oco-trade) - this setting defines "stopLimitTimeInForce".

The default ordertype is Good Til Cancelled - which means "nothing special" - keep it open til i explicitly cancel this.

These types of settings are not available in the UI iirc, only via API.

The best documentation i found while searching quickly is [this](https://www.binance.vision/tutorials/the-ultimate-guide-to-trading-on-binance-futures#what-is-post-only-time-in-force-and-reduce-only) ...
not 100% sure if the page is really related to binance - but the explanation seems correct. 
Our documentation in this regards is just copy/paste from the binance documentation - the wording is (should be) identical.

FOK: This means that the order must be filled fully (this prevents half-filled orders).

when using either IOC or FOK, unfilledtimeout settings for that side (buy, in your case) would be irrelevant, as the order must be immediately filled or will be cancelled by the exchange. Freqtrade will then parse the info and either mark the order as filled - or as cancelled depending on the result.

This will happen almost instantly - so unfilledtimeout will not apply.

**Comment by djacky** [comment]
I see...The term "immediately" is just a very vague term. Market orders are immediate, but limit orders are typically not immediate. 

So if you wanted to implement a limit order which waits 10 minutes to get fully filled, and permanently cancels the order if it doesn't get fully filled in 10 minutes, how would we do that? With GTC, the bot keeps trying to fill the order every 10 minutes (until you get a partial or full fill, or until the user cancels it manually), but if you want to permanently cancel the order if it's not fully filled after 10 minutes (in an automated way, without manual intervention), is this possible?

**Comment by xmatthias** [comment]
at least the binance API does not offer what you ask.

GTC may or may not be fully filled - so we can cancel it after 10 minutes - but how much is filled is "open".
IOC / FOK will be similar to market orders - being required to be filled "immediately" - which i take to be "right at that time".
If you send it as limit, then the price is fixed - (however taker fees will incur [source](https://www.binance.com/en/support/articles/360007720071)).


With that - i don't see how we could implement an order that stays open for 10 minutes - but must be fully filled or will be cancelled.

Feel free to open an issue with Binance Support for this - but no documentation i've seen suggests that this is supported - as it would be an additional "time in force" entry.

**Comment by gaugau3000** [comment]
@djacky be aware depending on liquidity and order book configuration of freqtrade if you create many orders that are not filled and cancelled because you use FOK or IOC then binance will ban you (i know what i talking ;-) ). Even you trade not on binance jersey look at [this](https://support.binance.je/hc/en-us/articles/360027113071-Binance-Jersey-API-Trading-Rules)

Have a nice day.

**Comment by djacky** [comment]
@gaugau3000 Thanks for the warning. I guess GTC mode would be sufficient for most trading strategies.
