### ISSUE TITLE
Feature Suggestion (buy sell if conditions)

### ISSUE THREAD

**Issue by Phunties** [freqtrade/freqtrade#2972]
This applies to both 'populate_buy_trend' and 'populate_sell_trend' however for simplicity will be discussed in terms of sell only.

Suppose for 1 strategy there are 3 independent sell strategies (combinations of signals)

1. Optimal Sell Strategy (max profit, perfect trade execution)
2. Average Sell Strategy (some profit, trade misses optimal and starts to fail)
3. Poor Sell Strategy (happy to take what I can get, trade has been moving sideways for 10 intervals)
4. Trade Fails / Stoploss

Given the time bound nature of the data and indifference of the OR opreator the overall sell strategy will always choose the lowest hanging strategy to execute on when true.

If we could use if statements (or somthing of that nature) it should provide the ability provide heirarchy to different sell strategies, or make different sell signals available for use under different conditions. 

e.g. trade going as expected only sell strategy 1 available, trade starts to correct and misses strategy 1 trigger, make strategy 2 available for execution and so on.

**Comment by xmatthias** [comment]
I'm not sure what feature / change you'd expect from freqtrade.

it's your choice to use an if-statement within the `populate_*_trend()` functions and populate the signal depending on different conditions.

``` python
# Initialize dataframe to avoid errors in case no condition hits
dataframe.loc[:,'sell'] = 0

if condition1:
    dataframe.loc[(<whateverconditions>
                           ),'sell'] = 1
elif condition2:
    dataframe.loc[(<whateverconditions>
                           ),'sell'] = 1

return dataframe
```

**Comment by Phunties** [comment]
Sweet
