### ISSUE TITLE
Bug: Freqtrade keeps showing trade after manually sold

### ISSUE THREAD

**Issue by King-Techno** [freqtrade/freqtrade#2975]
I made a sale using binance instead of force selling on my freqtrade bot. This has caused the trade not to disappear and my bot keeps showing my trade when I click `\status table` How do I get rid of this without refreshing my database?

**Comment by gaugau3000** [comment]
you can look [here](https://www.freqtrade.io/en/latest/sql_cheatsheet/#fix-trade-still-open-after-a-manual-sell-on-the-exchange)

**Comment by King-Techno** [comment]
for my file path i entered `.open /freqtrade/tradesv3.sqlite` however nothing seems to have opened?

**Comment by King-Techno** [comment]
please could you explain what I should type to open the database?

**Comment by hroff-1902** [comment]
@xmatthias we need the `freqtrade fix-db --action <action> --db-url dburl` utility subcommand for most frequently needed actions on the db

**Comment by gaugau3000** [comment]
@hroff-1902 I am not sure it is the role of freqtrade to provide a command for smt the user should not do :-).

**Comment by King-Techno** [comment]
how should I open the data base? I dont think it has opened correctly as I am getting the error `Error: no such table: trades`

**Comment by hroff-1902** [comment]
what db are you using? for dry-run the implicit default is `tradesv3.dryrun.sqlite`
(see description for `db_url` in https://www.freqtrade.io/en/latest/configuration/, for example)

**Comment by King-Techno** [comment]
I am using `tradesv3.sqlite` so i am using the command `.open tradesv3.sqlite` but nothing is opening. 

I have also tried `.open sqlite:///tradesv3.sqlite` but i get the error `unable to open database "sqlite:///tradesv3.sqlite": unable to open database file`

**Comment by hroff-1902** [comment]
> I am using `tradesv3.sqlite` so i am using the command `.open tradesv3.sqlite` but nothing is opening.

How do you found that anything is not opening?

```
$ ls tradesv3.sqlite 
tradesv3.sqlite
$ sqlite3 
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open tradesv3.sqlite
sqlite> 
```

**Comment by King-Techno** [comment]
Thank you I have done it :)
