### ISSUE TITLE
wrong runmode value during dryrun

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2980]
Hi,

using in dryrun

`print('current mode : {}'.format(self.dp.runmode.value))`

got this (i have cut other logs)

```
2020-02-26 09:48:38,425 - freqtrade.configuration.configuration - INFO - Dry run is enabled
current mode : live
```

i expected 

`current mode : dryrun`

Have a nice day.

**Comment by xmatthias** [comment]
where (which part) did you place this in? 

i've just tried in the strategy (both in `populate_buy()` and `populate_indicators()` - and i get dry_run assigned correctly every time.

also how (where) is dry_run set? command line or configuration? (not that it should matter)

**Comment by gaugau3000** [comment]
Ok i have tested when in config file you have `"dry_run": false` and in the command line the `--dry-run` flag you should be able to reproduce this issue (no impact if it is in populate_buy() or populate_indicators()).

**Comment by xmatthias** [comment]
well ... yes

**Comment by hroff-1902** [comment]
Hmm, scheisse...

**Comment by xmatthias** [comment]
it's not "that" bad - dry_run was set correctly, just runmode wasn't...

**Comment by hroff-1902** [comment]
yeah, but... as always, because was not covered by the tests
