### ISSUE TITLE
askVolume and bidVolume in VolumePairList

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2981]
Hi,

I come back with the discussion with @hroff-1902 we have about askVolume and bidVolume.
If i have well understood it filtered based on the volume of the best bid/ask.

It means like if Bitcoin have a bid with 30 dollar and a shitcoin have a bid at 3000 dollar it will update  the pairlist and put before in the list shitcoin vs BTC ?

Many tks.

**Comment by hroff-1902** [comment]
askVolume and bidVolume can also be rolling 24-h values. At least on Binance.

**Comment by gaugau3000** [comment]
I don't understand where  in freqtrade i can specify the rolling interval (i don't see this params in the doc). Tks.

**Comment by hroff-1902** [comment]
It cames from exchange. Exchange calculates those rolling values. As quoteVolume -- it's also a rolling 24-h value. askVolume and bidVolume are not related to orderbook volumes. These are 24-h rolling values of bought and sold amounts for the pair.

**Comment by xmatthias** [comment]
@hroff-1902, i'm not sure where you got the information that bidVolume/askVolume can be rolling - it's not on binance.

``` python
import ccxt
ct1 = ccxt.binance()
t = ct1.fetch_ticker('IOTA/USDT')
print(t['baseVolume'])
print(t['quoteVolume'])
print(t['askVolume'])
print(t['bidVolume'])

# output:
19025801.69
4166761.633471
7582.39
2784.37
```

Now this 7582.39 did correspond to the orderbook amount at the time of writing.

In the screenshot below it's the lowest value in the orderbook's ask side.

![2020-02-27-071553_389x592_scrot](https://user-images.githubusercontent.com/5024695/75417319-00ce2180-5931-11ea-8120-01fda760fcd8.png)

----

You can also look at the definition by ccxt [here](https://github.com/ccxt/ccxt/wiki/Manual#ticker-structure).

relevant sections in this case:

```
     'bidVolume':     float, // current best bid (buy) amount (may be missing or undefined)
...
    'askVolume':     float, // current best ask (sell) amount (may be missing or undefined)
...
    'baseVolume':    float, // volume of base currency traded for last 24 hours
    'quoteVolume':   float, // volume of quote currency traded for last 24 hours
```

Now the problem with baseVolume is that it's in base-currency - so what does it tell you if you compare 
300 BTC with 10_000 IOTA? 
USDT volume for these tow might correspond to `300 * 10_000 = 3_000_000` and `10_000 * 0.2 = 2_000` USDT (which will correspond to QuoteVolume) - and for that reason, using baseVolume does not make sense (it's never been possibile iirc). 

bidVolume / askVolume on the other hand uses the volume of the orderbook closest to the current spread (not rolling - just the "current" volume.

Now using that in VolumePairlist, which is refreshed every X hours is higly questionable to me - but it's been there as possibility from the beginning...

**Comment by gaugau3000** [comment]
If i have well understood the unique criteria that have a functional sense for VolumePairList  is quoteVolume has the others are defined on their base currency and cannot not be compared to each others.

Plus event even if bidVolume and askVolume could be transform in a bidQuoteVolume and askQuoteVolume to be sure we can compare markets volume to each other than it drop in this case :

> It means like if Bitcoin have a bid with 30 dollar and a shitcoin have a bid at 3000 dollar it will update the pairlist and put before in the list shitcoin vs BTC ?

witch still don't have sense i think.

So how it can be handle ?

Have a nice day.

**Comment by hroff-1902** [comment]
ah, yeah, they are from the orderbook, I do not know where I got the opposite info, maybe just invented it from the air, my bad

in this case seems these values are also in the base currency units, no?

**Comment by xmatthias** [comment]
you're probably right, and no other setting than `quoteVolume` does make sense in reality, as the others are in base-currency.

**Comment by hroff-1902** [comment]
let's deprecate this parameter? to have this filter using quoteVolume only?
