### ISSUE TITLE
backtesting and hyperopt change period of test data

### ISSUE THREAD

**Issue by tkso1997** [freqtrade/freqtrade#299]
I want to hyperopt and backtest test data from the last couple of days, for instance from January 1 till today. Where can I find the particular settings for that and adapt them to my needs?

Thanks!

**Comment by glonlas** [comment]
Hello,

At this moment this is not possible to define the period to test by Backtesting or Hyperopt. The bot take the full period for the data he has (local data or live data).
However, this will be a good feature to implement.

**Comment by xmatthias** [comment]
This is implemented now with the `--timerange=20180101-` flag.
