### ISSUE TITLE
Warning log level when VolumePairList and a blacklist are associated

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2992]
Hi,

Given i have set a VolumePairList and a blacklist containing ` [BNB/USDT]`
When the bot refresh the markets
Then I have a warning message
`2020-02-28 16:01:47,568 - freqtrade.pairlist.IPairList - WARNING - Pair BNB/USDT in your blacklist. Removing it from whitelist...`

I understand a warning in the case i have put in your whitelist and blacklist the same market (has it can be human mistake), but in this case i don't understand why.

Maybe a make an error in my config file ?

Many tks.

**Comment by xmatthias** [comment]
why? volumepairlist would have selected it - but blacklist removed it.

assuming, you have volumepairlist configured for 20 pairs - you'll end up with 19 pairs, because BNB/USDT has been removed.

**Comment by gaugau3000** [comment]
What i tried to explain is i don't understand why the log level is a `warning`. I tried to manage the logs with elk stack and this `warning` is more and `info` for me. that's all.
