### ISSUE TITLE
ohlcv_partial_candle how to use it ?

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2993]
Hi,

I don't understand how `ohlcv_partial_candle` param can be useful for trading :
- an incomplete candle is not really a candle because his shape change at every trade so it cannot be consider as a reliable information.
- maybe i am wrong but freqtrade refresh the candles only once per timeframe so this code coming from docs below don't reflect what happens in freqtrade has it trigger once per candle and not once per `process_throttle_secs` ?

EDIT : the doc seems to imply that this code is executed many times

> Another way is to run this command multiple times in a row and observe if the volume is changing (while the date remains the same).

```
import ccxt
from datetime import datetime
from freqtrade.data.converter import parse_ticker_dataframe
ct = ccxt.binance()
timeframe = "1d"
pair = "XLM/BTC"  # Make sure to use a pair that exists on that exchange!
raw = ct.fetch_ohlcv(pair, timeframe=timeframe)

# convert to dataframe
df1 = parse_ticker_dataframe(raw, timeframe, pair=pair, drop_incomplete=False)

print(df1.tail(1))
print(datetime.utcnow()) 
```

I can understand we use the ticker/current price in a strategy to compute every `process_throttle_secs` but the ohlcv_partial_candle i don't get it.

I maybe missed something.

Have a nice day.

**Comment by xmatthias** [comment]
> an incomplete candle is not really a candle because his shape change at every trade so it cannot be consider as a reliable information.

yes i agree, still people have been asking for it - however i think it'll generate repainted indicators, and honestly, i've not heared from anyone using this successfully yet.

---

You might be right, while using this setting will return the incomplete candle, it won't refresh the candle again for that candle - so it's kinda pointless.

I would propose to remove this section of the documentation completely unless @hroff-1902  disagrees (i know he wanted to use this in the past, too).

Using incomplete candles will create false signals based on repainted indicators, and honestly, i'm not interrested in fixing the reloading, as it would lead to a lot of convoluted code, with very little and potentially dangerous use.

When people ask for it, i think what they really want is the latest price - which is available usign `self.dp.orderbook()`.

**Comment by hroff-1902** [comment]
The main purpose of this setting is not for the exchanges that return the incomplete candle via API, It's for exchanges (as BitMEX) that do not include the incomplete candle in the ohlcv data. For those exchanges this setting should be set to false, otherwise last candle returned (the complete one) will be errorneously removed.

**Comment by xmatthias** [comment]
> The main purpose of this setting is not for the exchanges that return the incomplete candle via API, It's for exchanges (as BitMEX) that do not include the incomplete candle in the ohlcv data. For those exchanges this setting should be set to false, otherwise last candle returned (the complete one) will be errorneously removed.

Well yes - and that's covered in the developer documentation.
This is in the exchange documentation - to allow users to use the incomplete candle (which however does not work correctly, as we don't query ohlcv data in each iteration).

**Comment by alexandroskr77** [comment]
I am working on a strategy with 4h timeframe.
I want to calculate my indicators based also on the partial candle, something like tradingview.
Last price by itself cannot be used to calculate for example the 4h macd based on this last price.
4h timeframe is along time to wait to calculate my indicators.
Is there an option where I can force to query ohlcv data in each iteration for the partial candle?

**Comment by xmatthias** [comment]
No there is not. freqtrade does not provide incomplete candles - only completed ones (where close is set).

You can however use either a faster timeframe as informative pair, or use a faster (e.g.1h) timeframe on it's own and calculate the indicators based on the 4h informative pair).

**Comment by alexandroskr77** [comment]
1.Does any of the above mentioned options give us data on the 4hour timeframe partial candle?
2.In other words, there is no way to know where exactly for example the macd of the 4hour timeframe crosses 0? And if this happens after 1 hour after the last closed candle we will be 3 hours late on our signal (crossed over or below)?
3. Can you share any example that uses faster timeframe as informative pair in order to understand it?
Thanks in advance

**Comment by xmatthias** [comment]
The problem with incomplete candles is that you'll get "random" signals intra-candle (most indicators including macd are usually calculated against the candle's close). 
As such - you'll not know after the candle why the bot actually bought.

Personally, i'd not use a faster timeframe as informative pair, but instead would use the faster timeframe.

Also, your question (where within the 4h candle was macd crossed) does not make any sense.
there can be 20 crosses within a 4h candle (crossed after 5 minutes, gone after 10 minutes, there after 50 minutes again)  - this is called repainting. 

Where it crossed within the 4h timeframe is not relevant - as it can show a cross after 5 minutes - but the complete candle does not have a cross at all, as the close-price is now again next to the open.
If you want it in a more precise manner - use a faster timeframe.

**Comment by alexandroskr77** [comment]
We need to stop thinking like humans. That's the main reason we use the bots.
Repainting, yes, and let the bot buy & sell as many times it crosses your targets (it will not be more than 2-3 times, and that means that all of them will be almost at the same price).
The verdict will be to have or the minimal loss, in case of wrong signal, or the maximum profit, in case of correct signal.
I will try to work as  you said, with faster timeframe and 4h as informative.
Thank you for your time.

**Comment by MM19871366** [comment]
> We need to stop thinking like humans. That's the main reason we use the bots. Repainting, yes, and let the bot buy & sell as many times it crosses your targets (it will not be more than 2-3 times, and that means that all of them will be almost at the same price). The verdict will be to have or the minimal loss, in case of wrong signal, or the maximum profit, in case of correct signal. I will try to work as you said, with faster timeframe and 4h as informative. Thank you for your time.

Actually I use this method for RSI ... I mean calculating intera-candle value for daily RSI from 4h candles with some strategy in pine script in tradingview . its interesting idea and we are not first guys use incomplete candles data because I see mql code that calculate something like that. 
I will write some function to do that if there is no other python lib for it 
if anyone see something like that I will appreciate to reply on this comment

**Comment by d65535** [comment]
> 
I was looking to implement something similar with RSI, to use the details from an incomplete candle but couldn't find a way to this with freqtrade.

**Comment by xmatthias** [comment]
Freqtrade does not provide incomplete candles, as described in the [FAQ](https://www.freqtrade.io/en/stable/faq/#i-want-to-use-incomplete-candles).
