### ISSUE TITLE
Coinbase Pro Trades Not Closing in Sqlite3

### ISSUE THREAD

**Issue by Smone5** [freqtrade/freqtrade#2996]
## Step 1: Have you search for this issue before posting it?

I searched and to the best of my knowledge have not seen this issue yet. I am aware that Coinbase Pro exchange is not supported, however, my impression is this isn't an exchange issue since the trades are being completed as they should on CCXT side of things.

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04.3 LTS
  * Python Version: 3.6.9
  * CCXT version: 1.22.30
  * Branch: Develop
  * Last Commit ID: 97e48080e8601dcf692e687f0c4f7de747cce62e
  
## Step 3: Describe the problem:
Once a trade is completed, bought and sold, the asset is sold on the exchange, however in Freqtrade the sell order remains open indefinately. 

### Steps to reproduce:

  1. Open trade in Coinbase Pro
  2. Close trade in Coinbase Pro
  3. Asset is sold in Coinbase Pro
  4. Asset remains unsold in Freqtrade Sqlite3 database and Telegram
  
### Observed Results:
  * What happened?
The trade never closes in Freqtrade, not allowing new trades to happen in the future
 
 * What did you expect to happen?
The trade closes in Freqtrade and new trades can happen in the future. 

### Relevant code exceptions or logs:
**Telegram Output**
@3:30am EST
Coinbasepro: Selling LINK/USD
Rate: 4.34505000
Amount: 121.87000000
Open Rate: 4.27343000
Current Rate: 4.34505000
Sell Reason: trailing_stop_loss
Duration: 1:55:24 (115.4 min)
Profit: 0.66% (profit: 3.47665861 USD / 3.477 USD)

@7:53am EST
Trade ID: 5 (since 6 hours ago)
Current Pair: LINK/USD
Amount: 121.87 (520.82557526 USD)
Open Rate: 4.27343000
Current Rate: 4.34505000
Current Profit: 0.66%
Initial Stoploss: 4.05031422 (-5.22%)
Stoploss: 4.34994650 (-0.00%)
Open Order: (market sell rem=0.00000000)

**Coinbase Results**
![Screen Shot 2020-02-29 at 9 14 15 AM](https://user-images.githubusercontent.com/19376953/75609129-03b54780-5ad4-11ea-88c0-fb695c124bd9.png)

**Terminal Output**
![Screen Shot 2020-02-29 at 9 18 59 AM](https://user-images.githubusercontent.com/19376953/75609226-b8e7ff80-5ad4-11ea-887c-e22b7e753628.png)

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
Does this happen with every trade, or just with this one?

Output from telegram is kinda irrelevant...that's just informative, so it's mostly where you notice it first - but what counts are logs.


Please post the logs as text in tripple ticks (```) (so searching through them is possible).

Also, we'll need to have logs from the time the bot sold (or tried to sell) the asset (so please post the logs from 8:25/8:30).


Also, please open the database (`sqlite3 dbfile.sqlite`  or via sqlitebrowser) and post the entry for one of the trades (best use the Link trade (id=5).

**Comment by Smone5** [comment]
It happens every time. So far three times. I deleted the trade in sqlite3 this time to quickly continue trading. The next time it happens I will post the triage information as requested.

**Comment by xmatthias** [comment]
well - but if it happens every time - what's the point in deleting the trade ... ? 

in the end, it means that you're running experimental ... expecting every sell to fail - no?

**Comment by Smone5** [comment]
That is correct. I am expecting every sale the fail at the moment based on my previous history. That is all I can assume at the moment. I have the data in Coinbase to measure my performance. This is just a temporary means to get around it. The trade still executes, I just have to manually go in and reset the bot every time. I am not executing a lot of trades so this works for now.  I did some more testing and it worked when I used /forcesell on Telegram. Meaning the trade closed out correctly on both Coinbase Pro and Sqlite3. I thought that was interesting. I still don't have a good example, so hopefully, a trade executes soon that provides one.

**Comment by Smone5** [comment]
For me personally, I have decided not to use Coinbase Pro and go back to Kraken since it is supported. I liked the volume and liquidity on Coinbase and I don't have access to Binance. The Kraken exchange is working great. Thanks for everything! If you want to close this out please feel free.
