### ISSUE TITLE
Record profits in absolute value

### ISSUE THREAD

**Issue by yazeed** [freqtrade/freqtrade#3010]
This is a proposal to create a new column **trades.close_profit_abs** that records profit in absolute value. I think it can be used in different ways, such as easily aggregating total profits in stake_currency value, (would simplify _rpc_trade_statistics() for example), and it can be used in other references to calculate stake_currency based profit.

There's also lots of checks on the existing **Trade.close_profit** (percentage based) so we'd have to make sure we continue using it as a source of truth, and that we don't approve future PRs using the new column as a new source of truth, for consistency.

Let me know if you have any thoughts on this.

**Comment by xmatthias** [comment]
> There's also lots of checks on the existing Trade.close_profit (percentage based) so we'd have to make sure we continue using it as a source of truth, and that we don't approve future PRs using the new column as a new source of truth, for consistency.

why ... ? in theory (assuming stake-amount did not change) - the 2 should contain the same - or should at least be convertable between each other ... ? 

either way - i don't see adding that column as a problem ... the probably most difficult part is the migration ...

**Comment by hroff-1902** [comment]
"assuming stake-amount did not change" -- it already can be not same (last one is amended, plus Edge)...

In principle I agree with @yazeed , I think. This would simplify calculating PNL and be the bot better prepared for dynamic stake_amount for trades, which can be ...

Moreover, all loss functions in hyperopt should be calculated on abs profits instead of ratio values... For same reason -- stake_amounts can differ, and varying it can be a part of the trading strategy...

**Comment by xmatthias** [comment]
i think my point was lost above ... i'm not arguing adding this column - that's not much of a problem i think.
I'm not certain why we must make sure to not use this new column, it should be the same truth ... 

for backtesting / hyperopt / loss functions ... i'm not certain and will need to think this through (if it makes a difference or not) - but that's something to work on after this column is implemented.

**Comment by hroff-1902** [comment]
For backtesting / hyperopt / loss functions -- I thinks there can be an option for a user to choose, if loss function is calculated on percentage data or on absolute results.
