### ISSUE TITLE
Set minimum take profit percentage

### ISSUE THREAD

**Issue by King-Techno** [freqtrade/freqtrade#3015]
I know it is possible to only sell when you want a profit using the config file but is it possible to set the minimum profit you want before selling? e.g. minimum of 2% profit on all trades before sale. I cant find anything in the guide indicating this except from ROI which is time based.

**Comment by xmatthias** [comment]
that's not possible out of the box - but can be archived relatively easily by querying the database  as shown in the [documentation](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-trades).

you'll obviously need to modify the filter a bit - but getting the currently open trade should be possible easily (but will not work during backtesting, since that does not use the database for performance reasons).

**Comment by King-Techno** [comment]
hmmm I am not quite sure how to edit the code to do this? 

`if self.config['runmode'].value in ('live', 'dry_run'):
    trades = Trade.get_trades([Trade.pair == metadata['pair'],
                               Trade.open_date > datetime.utcnow() - timedelta(days=1),
                               Trade.is_open == False,
                ]).order_by(Trade.close_date).all()
    # Summarize profit for this pair.
    curdayprofit = sum(trade.close_profit for trade in trades)`

Will I just edit the Summarize section?

**Comment by hroff-1902** [comment]
(formatted output, triple quotes will give you better layout for multiline code snippets)

**Comment by xmatthias** [comment]
no, use Trade.is_open == True .... that should give you only one result - and then use `trade[0].calc_profit_ratio()` ... obviously checking first if you got a result, otherwise you risk key-errors in some cases.

A bit of python knowledge will be require for this as I'd call it an advanced method.

**Comment by King-Techno** [comment]
great thank you, I really appreciate your time

**Comment by natefoss** [comment]
I was searching for this same functionality today, so I implemented my own solution. I don't claim to be a Python programmer, so this may not be the Python way, but it's simple, and adds the configuration option to the strategy. Maybe this will help the next person who comes along. EDIT: fixed a typo left over from an earlier test...
```diff --git a/freqtrade/constants.py b/freqtrade/constants.py
index e7d7e80f..f41fae26 100644
--- a/freqtrade/constants.py
+++ b/freqtrade/constants.py
@@ -154,6 +154,7 @@ CONF_SCHEMA = {
                 'order_book_max': {'type': 'integer', 'minimum': 1, 'maximum': 50},
                 'use_sell_signal': {'type': 'boolean'},
                 'sell_profit_only': {'type': 'boolean'},
+                'sell_profit_roi': {'type': 'number', 'minimum': 0},
                 'ignore_roi_if_buy_signal': {'type': 'boolean'}
             }
         },
diff --git a/freqtrade/optimize/optimize_reports.py b/freqtrade/optimize/optimize_reports.py
index d029ecd1..6c0b5c65 100644
--- a/freqtrade/optimize/optimize_reports.py
+++ b/freqtrade/optimize/optimize_reports.py
@@ -299,6 +299,7 @@ def generate_backtest_stats(btdata: Dict[str, DataFrame],
             'minimal_roi': config['minimal_roi'],
             'use_sell_signal': config['ask_strategy']['use_sell_signal'],
             'sell_profit_only': config['ask_strategy']['sell_profit_only'],
+            'sell_profit_roi': config['ask_strategy']['sell_profit_roi'],
             'ignore_roi_if_buy_signal': config['ask_strategy']['ignore_roi_if_buy_signal'],
             **daily_stats,
         }
diff --git a/freqtrade/resolvers/strategy_resolver.py b/freqtrade/resolvers/strategy_resolver.py
index 2b7a4f0c..af202e63 100644
--- a/freqtrade/resolvers/strategy_resolver.py
+++ b/freqtrade/resolvers/strategy_resolver.py
@@ -78,6 +78,7 @@ class StrategyResolver(IResolver):
                       ("unfilledtimeout",                 None,        None),
                       ("use_sell_signal",                 True,        'ask_strategy'),
                       ("sell_profit_only",                False,       'ask_strategy'),
+                      ("sell_profit_roi",                 0.0,         'ask_strategy'),
                       ("ignore_roi_if_buy_signal",        False,       'ask_strategy'),
                       ("disable_dataframe_checks",        False,       None),
                       ]
diff --git a/freqtrade/strategy/interface.py b/freqtrade/strategy/interface.py
index 348e6a44..e400c622 100644
--- a/freqtrade/strategy/interface.py
+++ b/freqtrade/strategy/interface.py
@@ -512,7 +512,7 @@ class IStrategy(ABC):
                        and self.min_roi_reached(trade=trade, current_profit=current_profit,
                                                 current_time=date))

-        if config_ask_strategy.get('sell_profit_only', False) and trade.calc_profit(rate=rate) <= 0:
+        if config_ask_strategy.get('sell_profit_only', False) and trade.calc_profit(rate=rate) <= trade.open_trade_value * config_ask_strategy.get('sell_profit_roi', 0):
             # Negative profits and sell_profit_only - ignore sell signal
             sell_signal = False
         else:
```

**Comment by xmatthias** [comment]
yeah, noone said it'd be difficult to parametrize this ;) 
it's just not done .... (and i don't like the parameter name - as it's really a "sell_profit_offset" - to have it kindof aligned with `trailing_stop_positive_offset`.

**Comment by natefoss** [comment]
I wasn't trying to suggest it was difficult to implement. I just thought someone might find it useful, since I have no idea what your development roadmap looks like, or if you are even interested in this feature, I just posted it in the most relevant comment.

And I agree, `sell_profit_offset` is more consistent with your current naming convention.
