### ISSUE TITLE
wrong starting datetime for download-data

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#3022]
```
$ freqtrade download-data --exchange ftx -t 1d -p ETH/USD --days 100
...
2020-03-05 12:38:23,910 - freqtrade.exchange.exchange - INFO - downloaded ETH/USD with length 101.

$ freqtrade download-data --exchange ftx -t 1h -p ETH/USD --days 100
...
2020-03-05 12:38:37,412 - freqtrade.exchange.exchange - INFO - downloaded ETH/USD with length 2411.
```

-- here 101 is okay (seems to be): 100 days plus 1 current day, which is then thrown away as incomplete (?)
-- 2411 is wrong, should be 2401 or 2400. Plus, 11 hours here relates to the local time on the machine (as you can see, local time is 12:38, in UTC+3)

**Comment by xmatthias** [comment]
why?
It's downloading data for the last 100 days up to the current moment - which is 100 days (2400) + 11 hours.

downloading data from 100 days ago starting at 11:00 (which is what you're requesting here) does not make any sense at all - what would you do with half a day worth of data ... ?

**Comment by hroff-1902** [comment]
> why?
> It's downloading data for the last 100 days up to the current moment - which is 100 days (2400) + 11 hours.

I expected it to be last 100 full 24-h intervals (as data load for last 5 hours assumes 5 last full 1h-intervals and not 5 hrs + 38 minutes, if it happens that we start downloading at 38th minute of the current hour...)

**Comment by hroff-1902** [comment]
at least, local time shift is used. UTC time is 09:38:37,412, while 11 hours are added to 100 days... Very confusing.

**Comment by xmatthias** [comment]
the parameter is called `--days X` ... it calculates X days back from the current day - and downloads full days.

Using the current time of the day would be strange - you would get data from 100 days ago - starting at 17:15 ... but what's the point in not having these additional 17 hours... ? if you're that tight on disk-space you probably got other problems to worry about first.

**Comment by hroff-1902** [comment]
it's not about disk space, current behavior is odd, as for me: it's "X days back", i.e. starting since the time X 24-h intervals ago, as "5 hrs ago" means 5 hrs ago, not 5 hrs and 38 min ago... Why "X full days" should be used if we download for shorter timeframe, for 1h or 1m?
