### ISSUE TITLE
Telegram error

### ISSUE THREAD

**Issue by magick93** [freqtrade/freqtrade#3050]
## Step 1: Have you search for this issue before posting it?

Yes.

## Step 2: Describe your environment

  * Operating system: Ubuntu 19.04 but am using docker-compose
  * Docker image `freqtradeorg/freqtrade:develop`
  
## Step 3: Describe the problem:

When sending a command via Telegram I'm getting:

```
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 390, in process_update
freqtrade    |     handler.handle_update(update, self, check, context)
freqtrade    |   File "/usr/local/lib/python3.8/site-packages/telegram/ext/handler.py", line 117, in handle_update
freqtrade    |     return self.callback(update, context)
freqtrade    |   File "/freqtrade/freqtrade/rpc/telegram.py", line 37, in wrapper
freqtrade    |     chat_id = int(self._config['telegram']['chat_id'])
freqtrade    | ValueError: invalid literal for int() with base 10: 'priceinsight_bot

```

### Steps to reproduce:

  1. Add the below conf
  2. Run `docker-compose up`
  3. Send any command via Telegram, eg `/status`

#### Telegram conf

```
"telegram": {
        "enabled": true,
        "token": "12345678:AXXXREDACTED",
        "chat_id": "my_redacted_bot"
    }
```

## Additional

I noticed the following log when starting the strategy.

```
reqtrade    | 2020-03-10 10:31:36,075 - freqtrade.worker - INFO - Changing state to: RUNNING
freqtrade    | 2020-03-10 10:31:36,075 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': custom, 'status': "*Exchange:* `poloniex`\n*Stake per trade:* `0.1 BTC`\n*Minimum ROI:* `{'1440': 0.01, '80': 0.02, '40': 0.03, '20': 0.04, '0': 0.05}`\n*Stoploss:* `-0.27615`\n*Ticker Interval:* `5m`\n*Strategy:* `PriceinsightStrategy`"}
freqtrade    | 2020-03-10 10:31:36,403 - freqtrade.rpc.telegram - WARNING - Telegram NetworkError: Chat not found! Trying one more time.
freqtrade    | 2020-03-10 10:31:37,093 - freqtrade.rpc.telegram - WARNING - TelegramError: Chat not found! Giving up on that message.
freqtrade    | 2020-03-10 10:31:37,093 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': "Searching for BTC pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
freqtrade    | 2020-03-10 10:31:37,502 - freqtrade.rpc.telegram - WARNING - Telegram NetworkError: Chat not found! Trying one more time.
freqtrade    | 2020-03-10 10:31:37,912 - freqtrade.rpc.telegram - WARNING - TelegramError: Chat not found! Giving up on that message.
```

I'm not sure why the chat is not found, but it maybe due to being a newly created Telegram account.

**Comment by magick93** [comment]
User error - I had the wrong id.

**Comment by juliorobertoalvarez** [comment]
> 
> 
> User error - I had the wrong id.

where you find the right id?, on telegram or another method?

**Comment by stspinu** [comment]
> > User error - I had the wrong id.
> 
> where you find the right id?, on telegram or another method?

After you set the Telegram Bot username, you'll get the "Done! Congratulations on your new bot. You will find it at ________. You can..." 

You MUST click on that link to your Bot and start it (in a sense activate it). 

After that, messages will go through, but until then I was getting the same error messages as the original post in this thread.

I thought I already did that, but I actually didn't. This solved it for me.
