### ISSUE TITLE
How to insert delays into BUY/SELL 

### ISSUE THREAD

**Issue by Vildnex** [freqtrade/freqtrade#3052]
## Step 1: Have you search for this issue before posting it?

Yes, but I didn't find anything on either the internet or documentation. 

## Step 2: Describe your environment

  * Operating system: Linux
  * Python Version: 3.7.6 (`python -V`)
  * CCXT version: 1.23.81 (`pip freeze | grep ccxt`)
  * Branch: Develop
  
## Step 3: Describe the problem:

I'm creating a strategy that has 3 indicators so far, and I would like so wait for them one after another. 
So basically let's say that I have an BB, RSI and VFI.
Now for this example lets, I will describe my question just for a BUY function, but it's the same also for SELL.
BUY function:
**What is it right now:**

def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                    (dataframe['close'] < dataframe['bb_middleband']) &
                    (dataframe['rsi'] < 50) &
                    qtpylib.crossed_above(dataframe['vfi'], dataframe['vfima'])
            ),
            'buy'] = 1
        return dataframe

**What I'm trying to do:**

def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        self.result_BB = (dataframe['close'] < dataframe['bb_middleband'])
        self.result_RSI = (dataframe['rsi'] < 50)
        self.result_VFI = qtpylib.crossed_above(dataframe['vfi'], dataframe['vfima'])

        if any(self.result_BB):
            self.check_BB = True

        if any(self.result_RSI):
            self.check_RSI = True

        if any(self.result_VFI):
            self.check_VFI = True

        result = ()
        if self.check_BB and self.check_RSI and self.check_VFI:
            result = (self.result_BB & self.result_RSI & self.result_VFI)
            self.check_BB = False
            self.check_RSI = False
            self.check_VFI = False

        dataframe.loc[
            (
                result
            ),
            'buy'] = 1

        return dataframe

The question would be how can I **BUY** at that specific moment when all the conditions are meat (**self.result_BB & self.result_RSI & self.result_VFI**)? Because I don't really want to do an **OR** or **AND** bit operations between them because that is not necessarily relevant result by that time, but they were. 

Could anyone of you help me with some advice here?
Thanks :D

**Comment by hroff-1902** [comment]
```
    if dataframe['adx'] > 25:
        first_check = True

    if dataframe['mom'] < 0:
        second_check = True
    
    if first_check and second_check:
      #  then buy the candle at that specific time
```
is equal to
```
    if (dataframe['adx'] > 25) and (dataframe['mom'] < 0):
      #  then buy the candle at that specific time
```

in the syntax of pandas expressions for assigning the values of the buy column with `loc`, it will be 
```
dataframe.loc[
(
    (dataframe['adx'] > 25) &
    (dataframe['mom'] < 0)
),
'buy'] = 1
```

**Comment by hroff-1902** [comment]
* you do not have any code for setting the conditions back to False;
* you can simply assign the values to the custom strategy attribute or a variable at the module level;
* this will not work for backtesting, though

**Comment by Vildnex** [comment]
> 
> 
>     * you do not have any code for setting the conditions back to False;
> 
>     * you can simply assign the values to the custom strategy attribute or a variable at the module level (a global var);
> 
>     * this will not work for backtesting, though

I just update the question with some code. I hope that my question is clear because I'm not sure if I was explained in the right way.

**Comment by xmatthias** [comment]
you will need to be very careful with this during backtesting to avoid having a lookahead bias.

Assuming dry run now:
Am i correctly reading that you'd like to buy whenever RSI is < 50 anywhere within all available candles?

I am pretty certain that this condition alone will yield results in almost all cases.
So to be honest, it's not clear at all what you're trying to do - but i suspect your best bet might be something around the following

```
dataframe['rsi_cond'] = (dataframe['rsi'] < 50) 

dataframe['rsi_cond'].rolling(20).max() # this should get you true / 1 if rsi was < 50 within the last 20 candles
```

**Comment by Vildnex** [comment]
> 
> 
> you will need to be very careful with this during backtesting to avoid having a lookahead bias.
> 
> Assuming dry run now:
> Am i correctly reading that you'd like to buy whenever RSI is < 50 anywhere within all available candles?
> 
> I am pretty certain that this condition alone will yield results in almost all cases.
> So to be honest, it's not clear at all what you're trying to do - but i suspect your best bet might be something around the following
> 
> ```
> dataframe['rsi_cond'] = (dataframe['rsi'] < 50) 
> 
> dataframe['rsi_cond'].rolling(20).max() # this should get you true / 1 if rsi was < 50 within the last 20 candles
> ```

Well... that's not exactly what I'm trying to do. What I was trying to explain and what I'm actually trying to do is to implement this [strategy](https://www.tradingview.com/chart/USDJPY/2NljpKEH-BEST-COMBINATION-OF-TECHNICAL-INDICATORS/), but in order to do that I need to wait for the next indicator to be True.

So basically instead of doing something like this...
(indicator_1 & indicator_2 & indicator_3) which means that I'm waiting for all indicators to be TRUE at that specific moment, I'm trying to do something like this:

1. Wait for indicator_1 to be true
2. Wait for indicator_2 to be true
3. Wait for indicator_3 to be true
4. After ALL, indicators are TRUE, then and just THEN I want to **buy** at that specific time. So I don't care if indicator_1 it was true 10min ago, indicator_5 5min ago and the last indicator_3 1min, if all them checked to be at least once true, I want to **BUY** at that moment.

**Comment by xmatthias** [comment]
The approach i showed you above using `.rolling().max()` on the condition (this is key)  will work.

The key parameter is the rolling() - as this defines how many candles you're accepting the "truthyness" of the indicators.

The maximum is 498 for dry-run - but i doubt that you'll want to buy if an indicator was true 3 days ago (assuming 5m candles).

**Comment by hroff-1902** [comment]
as I said, simply keep the state of your indicator_1, indicator_2 and indicator_3 in the strategy class attributes or in the global variables.
(same caution once again: this won't work in backtesting)

**Comment by Vildnex** [comment]
> 
> 
> The approach i showed you above using `.rolling().max()` on the condition (this is key) will work.
> 
> The key parameter is the rolling() - as this defines how many candles you're accepting the "truthyness" of the indicators.
> 
> The maximum is 498 for dry-run - but i doubt that you'll want to buy if an indicator was true 3 days ago (assuming 5m candles).

Oh right, now I see what you mean and we were right. Sorry to bodder you guys with such a simple quesiton but thanks for help :D
