### ISSUE TITLE
Buying with no buy signal

### ISSUE THREAD

**Issue by yarinbar** [freqtrade/freqtrade#3056]
## Step 1: Have you search for this issue before posting it?

Yes I have, found something similar that ended up being an indicator error and I suspect i have a different issue.

For reference - https://github.com/freqtrade/freqtrade/issues/533

## Step 2: Describe your environment

  * Operating system: linux
  * Python Version: Python 3.6.9 (`python -V`)
  * CCXT version: 1.23.67 (`pip freeze | grep ccxt`)
  * Branch: Master
  * Last Commit ID: 54c07e5e62b9c1a6b6411618a4dc9c78e234c036 (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

I created a custom made, super simple strategy. When i plotted the strategy backtesting i  saw that there are plenty 'Trade bay' instances without any 'buy signal'.
To eliminate the option that 'Trade buy' and the 'buy signal' overlap i looked very carefully and since the strategy is indeed extremely simple it was easy to see that it was not possible a 'buy signal' would have existed there.

I even reduced the max positions to 1 to see if it might was the multiple positions that threw the strategy off, but the problem persisted.

What's even weirder is that between 2 profitable sales i have no buy signal and it still entered a position. (i attached a picture)
 
![Capture](https://user-images.githubusercontent.com/37772157/76451576-48948480-63d8-11ea-8e51-f7149f7e8bab.JPG)

Any help would be appreciated!

Thanks! :)

**Comment by xmatthias** [comment]
The solution is simple - this is not possible and it has to be a handling error while running the 2 commands.

There's only 2 conditions where this can happen:

* You're either using the wrong / a different strategy for plotting (maybe loaded from the wrong file)
* or you didn't export the backtesting results in the last backtesting iteration - so now the trades are based on an old (or different) strategy - while the signals are from a new strategy.

**Comment by orehunt** [comment]
maybe exporting the backtest results could also store a checksum of the strategy that plotting can compare against to ensure it is plotting results that match the strategy

**Comment by hroff-1902** [comment]
check that you do not have other strategies with the same name first: `freqtrade list-strategies`

**Comment by yarinbar** [comment]
I actually did mess up with the files and now the buys are actually do appear adjacent to the buy signals - BUT there is something new i can't figure out (that i didnt find an answer to):

It appears that there are some buy signals that are ignored. For instance in this picture there is a buy signal that is not being acted on and the following one is, even though there's no selling in between.
![Capture](https://user-images.githubusercontent.com/37772157/76469781-a2587700-63f7-11ea-9b8a-6c62998363e2.JPG)

**Comment by xmatthias** [comment]
there's 2 possibilities for this (again):
* if your backtest included more than one pair - then maybe `max_open_trades` was reached so it didn't act.
* Make sure to pass in the same `--timerange` setting to both backtest and plot-dataframe ... since plot-dataframe analyzes the strategy again, passing in a longer timeframe here would show buy-signals which are not included in the backtesting results.

**Comment by yarinbar** [comment]
I changed the whitelist to only one pair with no change.

Regarding your second point, i run the backtests on the entirety of my data and only use some of it to plot to reduce the file size. 

for plotting i use:
`freqtrade plot-dataframe --strategy Grad -p ETH/BTC --timerange=20180801-20200205 --indicators2 ema200acc --indicators1 ema100 ema200 ema400`

for backtesting i used the entire the data:
`freqtrade backtesting -s Grad --ticker-interval 15m`

and i  downloaded the data with:
`freqtrade download-data -p ETH/BTC -t 15m --days 2500`

so the data used for backtesting is covering my plotting `timerange`. 
but nevertheless, i don't understand how my backtesting command affect the plot because it re-analyzes the strategy.

**Comment by hroff-1902** [comment]
is not the signal in the first 'strategy startup period candles'?

**Comment by yarinbar** [comment]
im not quite sure i understand your question.

do you mean to ask if the first buy signal is during the 'strategy startup period candles'? 
if so, it isn't it's very much in the middle of the trade time period and there were trades before that.

**Comment by xmatthias** [comment]
I think your plot command is missing one crucial thing.
You're backtesting 15m timeframe ... but when not passing that to plot-dataframe, it'll default to 5m (unless it's loaded from the configuration ...).
So you're plotting trades made on 15m candles onto indicators for 5m candles ... it'll somehow work ... but not show what you need.

Try the below (stolen from your above command and added the -i command).

```
freqtrade plot-dataframe --strategy Grad -p ETH/BTC --timerange=20180801-20200205 --indicators2 ema200acc --indicators1 ema100 ema200 ema400 -i 15m
```

**Comment by yarinbar** [comment]
I actually did change the `config.json` to match the 15m interval and checked in the plot that each candle is indeed 15m long, but ran the modified command anyway. I was able to spot both a buy without a signal and ignoring buy signals without open positions. (I changed the strategy since but it's is still simple and shouldn't be a problem.

is there a way i can help you more to help me? i feel like the pictures aren't exactly informative but the full log seems like an overkill.

I did get a dataframe warning that i ignored cause i honestly think it has nothing to do with it, but to be on the safe side i'll add the lines that make the warning pop and the warning itself,

the code (df is a column, not the entire dataframe):

        df['diff']      = df.subtract(df.shift(1))
        df['direction'] = df['diff']
        df['direction'][df['direction'] < 0] = -1
        df['direction'][df['direction'] > 0] =  1

        return df['direction']

the warning:

    SettingWithCopyWarning:
    A value is trying to be set on a copy of a slice from a DataFrame
    See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    2020-03-12 18:38:44,392 - freqtrade.plot.plotting - INFO - Generate plot file for ETH/BTC
`

cheers :)

**Comment by xmatthias** [comment]
that warning itself is not relevant.

To verify - run backtesting and plot-dataframe on exactly the same timerange (specify that explicitly - and limit it to something sensible.

As you only got one pair, this should be easy and quick to do - but as said, assuming the same strategy is used, this is not a possibility unless the wrong exported trades file is used. 
you can try to specify that explicitly via `--export-filename testbacktestexport.json` in both commands as well.

**Comment by yarinbar** [comment]
Ok maybe that's the problem, when using `export-filename` flag there's no new file in the results folder. I even deleted all files from user_data (except from the strategy) and the folders are empty after i run:

`freqtrade backtesting -s Grad --ticker-interval 15m --timerange=20190101-20190201 --export-filename testbacktestexport.json`

when i try to run:
`freqtrade plot-dataframe --strategy Grad -p ETH/BTC  --indicators2 ema200acc --indicators1 ema100 ema200 ema400 -i 15m --timerange=20190101-20190201 --export-filename testbacktestexport.json
`

i get the following `ValueError`:
`ValueError: File testbacktestexport.json does not exist.`

**Comment by xmatthias** [comment]
well to export you always have to specify `--export trades` ... 

it's covered in the [docs](https://www.freqtrade.io/en/latest/backtesting/#exporting-trades-to-file).

**Comment by yarinbar** [comment]
thank you matthias!
I started using the `--export trades` flags with every backtest and now it works perfectly.

thanks again!
