### ISSUE TITLE
ValueError: Lengths must match to compare

### ISSUE THREAD

**Issue by Ellina-fox** [freqtrade/freqtrade#3058]
My aim is to write a function which removes English stop words from a tweet. The tweet DataFrame data is provided (df), the stop words dictionary is provided (stop_words_dict). I need to create and additional column named 'Without Stop Words', where all the words from "Tweets' column of my Data Frame (except for the words from stop words dictionary) will be listed.

I am receiving the ValueError: Lengths must match to compare when running the follwoing code:

def stop_words_remover(df):
    new_list = df['Tweets'].str.lower().str.split() 
    df['Without Stop Words'] = None
    df['Without Stop Words'].append(lambda word: word for word in new_list  not in stop_words_dict.values()) 
    return df
What am I doing wrong?

**Comment by hroff-1902** [comment]
what is "tweet" here?
how's it related to the bot?

**Comment by xmatthias** [comment]
> df['Without Stop Words'].append(lambda word: word for word in new_list not in stop_words_dict.values())

i'm not sure if this is correct comprehension syntax - i think you're missing square parentheses within the lambda function.

On another note, writing this yourself is rather pointless - there's a few libraries for python to do english text decomposition / stopword removal (spaCy - for example) - which will do a much better job than writing something from scratch can do in a very long time.


Please note however that this is not really a question that belongs to this repository as it's not related to anything we use or show in examples for freqtrade.

It's not using the dataframe we pass to a strategy - so while i guess you'll use it for strategy development, this is still not the question we'll be able to answer here sufficiently.

Thanks for your understanding.

> what is "tweet" here?

Tweet - twitter message

> how's it related to the bot?

Strategy development based on twitter news / twitter sentiment.
