### ISSUE TITLE
combination of indicators and roi for selling a position

### ISSUE THREAD

**Issue by yarinbar** [freqtrade/freqtrade#3067]
To enhance my strategies performance i would really like to use more complex roi targets.

when i say complex i mean that instead of setting the roi target to a percentage i would really love to set it to something like this:

"sell when price hits `SMA` and profit is greater than 2%"

when i set the sell indicator to be 1 when `price == sma` it doesn't necessarily means at leat 2% profit and vice versa.

i looked in the documentation and couldnt find anything like that. is it possible to implement in the current state? 

if so, how? and if no, could you add this feature in the future?

thanks!

**Comment by xmatthias** [comment]
It's no turnkey solution, but definitely possible with some python knowledge.

best start [here](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-trades):

Something along the lines of

```python 
if self.config['runmode'].value in ('live', 'dry_run'):
    ob = self.dp.orderbook(metadata['pair'], 1)
    rate = ob['bids'][0][0]
    trade = Trade.get_trades([Trade.pair == metadata['pair'],
                               Trade.is_open == True,
                ]).first()
    profit = trade.calc_profit_ratio(rate)
```

Won't work in backtesting as backtesting does not write data into the database...
You should be able to use profit to compare within the sell condition ... just use something around `(profit > 0.02) & ` - but as said, won't work in backtesting, so you need to dry-run test this immediately.

**Comment by xmatthias** [comment]
I'll assume this as solved by the above comment.
Feel free to comment / reopen if you don't think it solves your question.
