### ISSUE TITLE
Error and freqtrade:command not found

### ISSUE THREAD

**Issue by jord99** [freqtrade/freqtrade#3075]
## Step 1: Have you search for this issue before posting it?
I have searched for the issue and the fixes have not worked. I think this might be because of another issue accompanying this.
If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04 LTS____
  * Python Version: _3.6.9____ (`python -V`)
  * CCXT version: Don't know how to check this_____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:
I run the following lines in the terminal:
git clone https://github.com/freqtrade/freqtrade.git
cd freqtrade
git checkout master  # Optional, see (1)
./setup.sh --install
I then enter the .env folder to try to run the bot and receive this error.
*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```Building wheels for collected packages: py-find-1st
  Building wheel for py-find-1st (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/cryptobot1/freqtrade/.env/bin/python3.6 /home/cryptobot1/freqtrade/.env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmps9fzq7ha
       cwd: /tmp/pip-install-03v3w1_x/py-find-1st
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/utils_find_1st
  copying utils_find_1st/__init__.py -> build/lib.linux-x86_64-3.6/utils_find_1st
  running build_ext
  check for clang compiler ... no
  building 'find_1st' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/utils_find_1st
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_13_API_VERSION -I/tmp/pip-build-env-zjkhib7x/overlay/lib/python3.6/site-packages/numpy/core/include -I/home/cryptobot1/freqtrade/.env/include -I/usr/include/python3.6m -c utils_find_1st/find_1st.cpp -o build/temp.linux-x86_64-3.6/utils_find_1st/find_1st.o
  utils_find_1st/find_1st.cpp:3:10: fatal error: Python.h: No such file or directory
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for py-find-1st
Failed to build py-find-1st
ERROR: Could not build wheels for py-find-1st which use PEP 517 and cannot be installed directly
pip install completed

-------------------------
Please use 'freqtrade new-config -c config.json' to generate a new configuration file.
-------------------------
-------------------------
Run the bot !
-------------------------
You can now use the bot by executing 'source .env/bin/activate; freqtrade trade'.
cryptobot1@cryptobot1vb:~/freqtrade$ source .env/bin/activate
(.env) cryptobot1@cryptobot1vb:~/freqtrade$ freqtrade new-config -c config.json
freqtrade: command not found
(.env) cryptobot1@cryptobot1vb:~/freqtrade$

**Comment by hroff-1902** [comment]
try 
```
sudo apt-get install python3.6-dev
```
and re-run `./setup.sh --install`

**Comment by jord99** [comment]
(.env) freqtradebot@freqtradebotvb:~/freqtrade$ freqtrade trade
2020-03-17 09:18:43,295 - freqtrade.loggers - INFO - Verbosity set to 0
2020-03-17 09:18:43,297 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2020-03-17 09:18:43,297 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2020-03-17 09:18:43,298 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2020-03-17 09:18:43,298 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/freqtradebot/freqtrade/user_data ...
2020-03-17 09:18:43,299 - freqtrade.configuration.configuration - INFO - Using data directory: /home/freqtradebot/freqtrade/user_data/data/bittrex ...
2020-03-17 09:18:43,300 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-03-17 09:18:43,300 - freqtrade.configuration.check_exchange - INFO - Exchange "bittrex" is officially supported by the Freqtrade development team.
2020-03-17 09:18:43,300 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-03-17 09:18:43,300 - freqtrade.freqtradebot - INFO - Starting freqtrade 2020.02
2020-03-17 09:18:43,301 - freqtrade - ERROR - No strategy set. Please use `--strategy` to specify the strategy class to use.

The setup now ran smoothly with no errors. This is the message I now receive when trying to run the bot, I assume this means it worked and I now have to configure everything, is that correct?
Thank you for your help.

**Comment by xmatthias** [comment]
Yes, that is correct, you'll need select / create a strategy - set configuration, and so on...

**Comment by jord99** [comment]
I've noticed the current release of freqtrade doesn't come with a default strategy to run. I wanted to try running the bot before testing a new strategy. I found a forked version of freqtrade and copied the default_strategy.py file to the freqtrade/strategy directory.
After trying to run it through the terminal I receive the following error (I configured the config.json file with telegram and binance):
(.env) freqtradebot@freqtradebotvb:~/freqtrade$ freqtrade trade -c config.json -s DefaultStrategy
2020-03-17 10:02:29,491 - freqtrade.loggers - INFO - Verbosity set to 0
2020-03-17 10:02:29,493 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2020-03-17 10:02:29,493 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2020-03-17 10:02:29,493 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2020-03-17 10:02:29,494 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/freqtradebot/freqtrade/user_data ...
2020-03-17 10:02:29,495 - freqtrade.configuration.configuration - INFO - Using data directory: /home/freqtradebot/freqtrade/user_data/data/binance ...
2020-03-17 10:02:29,495 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-03-17 10:02:29,496 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-03-17 10:02:29,496 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-03-17 10:02:29,496 - freqtrade.freqtradebot - INFO - Starting freqtrade 2020.02
2020-03-17 10:02:29,497 - freqtrade - ERROR - Impossible to load Strategy 'DefaultStrategy'. This class does not exist or contains Python code errors.

Is there any way for me to test a simple strategy so that I can see the bot send me buy/sell messages in telegram before I devote time to building a strategy?
Thank you

**Comment by harnoor992** [comment]
Hi,
Whenever i try to run the installation. It halts at below line.
    Running setup.py install for yarl ... done
    Running setup.py install for SQLAlchemy ... done
    Running setup.py install for tornado ... done
    Running setup.py install for future ... done
    Running setup.py install for wrapt ... done
    Running setup.py install for pyrsistent ... done
    **Running setup.py install for TA-Lib ... \**

I have python 3.7. Trying hard to have this setup as i'm new here.

**Comment by xmatthias** [comment]
@jord99 It would be written in the documentation (in several places, actually).

```
# Initialize the user_directory
freqtrade create-userdir --userdir user_data/
freqtrade trade --strategy SampleStrategy
```

@harnoor992 

It does not halt - installing TA-Lib takes some time - and may appear stuck while installing.

Also, it's very susceptible to not having enough memory - so make sure to size your machine according to the minimum requirements.

**Comment by jord99** [comment]
Thank you that worked.
I've noticed that when the bot prints the orders in telegram, the USD amount is 0.000 USD. How do I get it to display the USD amount?
In the config.json, the fiat display currency is set to USD.

**Comment by xmatthias** [comment]
i assume you're using the master branc / latest release.
coinmarketcap disabled their api eariler this month.

Develop version includes a fix (it's now using coingecko instead of coinmarketcap) - but we haven't had time to do a release yet.

**Comment by jord99** [comment]
How do I know which minimization function is being used when I run hyperopt?
I would like to ensure I'm optimizing with respect to the sharpe ratio.

**Comment by xmatthias** [comment]
well you need to specify it explicitly, otherwise the default lossfunction is used.

Best read the [documentation](https://www.freqtrade.io/en/latest/hyperopt/#loss-functions) - which is there to answer such questions.

Since the original answer has been answered, i'll close this issue now.

**Comment by Joris1Jansen** [comment]
@jord99 @xmatthias where do I have to place te following:
# Initialize the user_directory
freqtrade create-userdir --userdir user_data/
freqtrade trade --strategy SampleStrategy

Because I have the same error as you, but  I can't find this piece of code...

**Comment by xmatthias** [comment]
it's a command - you run it in the terminal with freqtrade virtual environment activated?

**Comment by hroff-1902** [comment]
the question above ^^ should be in the list of banned questions.

**Comment by benedito5ai** [comment]
> try
> 
> ```
> sudo apt-get install python3.6-dev
> ```
> 
> and re-run `./setup.sh --install`

Hello, 
![image](https://github.com/freqtrade/freqtrade/assets/145056261/e72caa70-4c9b-48cb-ae48-b9c46e63af3b)
I was wondering if you could give me the password. Thanks sir.
![Captura](https://github.com/freqtrade/freqtrade/assets/145056261/8d22bd14-9207-45cd-b136-602669ec3b04)

**Comment by stash86** [comment]
Python3.6 already not supported. Use at least 3.9.

sudo password is set by the admin. We won't know the password. Ask your admin.

and please open a new issue if you have any issue, instead of reviving old issue
