### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: subtemplates/exchange_generic.j2 Error

### ISSUE THREAD

**Issue by bDyEz8c8CtL8dJ8aaQhV8** [freqtrade/freqtrade#3078]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Arch Linux
  * Python Version: 7.13 
  * CCXT version: 1.24.37 
  * Branch: Master 
  
## Step 3: Describe the problem:

I installed the package from AUR, it is the latest version. I am getting a jinja error.

### Steps to reproduce:

  1. Try to create new config
  
### Observed Results:

  * What happened?
I expected it to work.

  * What did you expect to happen?
Threw jinja error.
### Relevant code exceptions or logs:

  ```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/usr/lib/python3.8/site-packages/freqtrade/commands/build_config_commands.py", line 193, in start_new_config
    deploy_new_config(config_path, selections)
  File "/usr/lib/python3.8/site-packages/freqtrade/commands/build_config_commands.py", line 165, in deploy_new_config
    selections['exchange'] = render_template(
  File "/usr/lib/python3.8/site-packages/freqtrade/misc.py", line 149, in render_template
    template = env.get_template(templatefile)
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python3.8/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python3.8/site-packages/jinja2/loaders.py", line 299, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: subtemplates/exchange_generic.j2

  ```

**Comment by xmatthias** [comment]
> I installed the package from AUR,

which AUR package?
`python-freqtrade-git` is heavily outdated and no longer maintained, and i could not find another AUR package.

Please install freqtrade either using pypi (`pip install freqtrade`) or by following the [installation documentation](https://www.freqtrade.io/en/latest/installation/), or by using [docker](https://www.freqtrade.io/en/latest/docker/), thanks.

**Comment by bDyEz8c8CtL8dJ8aaQhV8** [comment]
Hey, thanks for the reply.

I adopted that package from AUR and updated it, it works now. 

I tried to install with pypi, I still get the same error. Jinja cannot find the templates.

**Comment by hroff-1902** [comment]
we do not know what particular you adapted, which way, how, what files are taken from where, etc.
why have not you installed the bot one of the ways described in the docs?

**Comment by bDyEz8c8CtL8dJ8aaQhV8** [comment]
Yes I understand what you are saying, I try to keep my packages from distro repos instead of installing from multiple places. The AUR package aside, I installed the program from PyPi and I still get the same error.

**Comment by hroff-1902** [comment]
installing from pypi is not one of the installation methods described in the docs, it's just work in progress

**Comment by xmatthias** [comment]
Yes you're right - templates are missing from the pypi release.

#3079 will fix this, but even once that's merged, it'll not be automatically available on pypi as we'll need to create a release first.

Also - the AUR package is called `python-freqtrade-git` - so i'd expect this to be pointed towards the develop branch (latest) of the git repository (which is common practice for `*-git` AUR Packges. 
For a release distribution, a name like `freqtrade` or `python-freqtrade` would be more appropriate.

**Comment by hroff-1902** [comment]
opened this so that the new pypi release with the fix can be verified.

**Comment by hroff-1902** [comment]
Checked with current pypi release (freqtrade-2020.3) -- templates and jupyter files are installed.

Closing it.
