### ISSUE TITLE
Hyperopt and Backtesting not even close results.

### ISSUE THREAD

**Issue by psionyx2311** [freqtrade/freqtrade#3082]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04 Bionic Beaver
  * Python Version: 3.6.9
  * CCXT version: ccxt==1.21.91
  * Branch: Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

Using Hyperopt to optimize the BBandRSI strategy, I plug all the numbers into my strategy and make sure the config.json and my strategy file are exact to the hyperopt results, but Backtesting shows very diferent results, sometimes in the negative

### Steps to reproduce:

  1.Run Hyperopt on strategy BBandRSI
  2. Plug hyperopt results into strategy
  3. Run Backtest
  
### Observed Results:

  * What happened?
     Backtest results always differ from Hyperopt results.
  * What did you expect to happen?
   Backtest results to be somewhat similar

**Comment by xmatthias** [comment]
I've done this several times before (with other strategies) - so the error must be in the transfer of the numbers / conditions.

A few things to ensure:
* is the direction of comparison correct (< vs. >)
* are ALL conditions the same (volume is in most backtesting examples, but hasn't been considered for hyperopt until recently - it will also not show up in results)
* Are you using the same pairs, same timerange, timeframe and same configuration


Assuming the above won't help - We'll need the following information to discover the mistake you made:
* Full hyperopt file
* Hyperopt results you used
* resulting strategy file
* Parameters used to run both hyperopt and backtesting
* timeframe used
* timerange used

Feel free to provide this in private to either myself or @hroff-1902 here or via Slack if you don't want to share it publicly.

**Comment by hroff-1902** [comment]
@psionyx2311 has it been resolved after my review of the files you send to me at Slack?

**Comment by psionyx2311** [comment]
Yes, thanks again! The solution was put a # infront of the RSI part of the
buy trend as HyperOpt said to disable it.
