### ISSUE TITLE
wrong Telegram output after forceselling non-filled order

### ISSUE THREAD

**Issue by LiquiGate** [freqtrade/freqtrade#3084]
I am on the latest developed branch, and it seems that Telegram **Daily Stats** gives a negative of 100% if the order is unfilled and gets canceled, or if you forcesell it at 2 different rates (for example forcesell when price is 0.1 and forcesell when price is 0.09999).... --- (one of the 2 reasons gives a negative daily stat of 100%)... 

In the below images, I am trading with a balance of 0.02BTC, and I forceselled in order to gain the profit

![image](https://user-images.githubusercontent.com/16623905/77044344-26da6500-69b7-11ea-8cf4-64a9848c4bcb.png)

![image](https://user-images.githubusercontent.com/16623905/77044519-7fa9fd80-69b7-11ea-8afb-a4b7ac6c9be8.png)

Telegram account: @deniswithin

**Comment by xmatthias** [comment]
well this is not really enough information to do anything.

looking at the 17th (for example) - when you use 0.02 as stake, then a loss of -0.06 in 25 trades is viable, and has nothing to do with 100% loss.

Best open the database, and run the following query:

```
select * from trades where close_date between '2020-03-19' and '2020-03-20';
```

This should show you the rates / trades that happened - which are also the basis of the statistic, which does not consider the sell-reason.

**Comment by LiquiGate** [comment]
Giving more detail...>

As you can see in the first image, there is an **unfilled** open order to buy MATIC at the current price of  175 Satoshi.... (based on /help section, double asterisk = ** pending sell, single asterisk * pending buy) 

On the second image, I am forceselling order 55 which is the open order for MATIC, and it gives a daily loss of 100%.

![image](https://user-images.githubusercontent.com/16623905/77048490-6bb5ca00-69be-11ea-959d-ada86b628946.png)

![image](https://user-images.githubusercontent.com/16623905/77048575-99027800-69be-11ea-9fe3-8a9379a04009.png)

**Comment by xmatthias** [comment]
Well but this is a completely different scenario than what you posted above.

You're forceselling a non-filled pair - which is nowhere mentioned in the initial post - and is an edge-case (which we know is not fully covered #2646 ).

How does this play out on the exchange? has MATIC been bought at all (with this trade - so look at timings)? 
is it half-filled or not filled at all?

is the open order cancelled on the exchange as expected, or does that remain open on the exchange?

Please also post the logs around the time of when you ran the `/forcesell 55` method.

To avoid this issue - best don't use /forcesell on pairs with open buy-orders for now.

**Comment by LiquiGate** [comment]
Thanks for waiting my reply before closing this topic xmanthias :) 

The order was partially bought and it was waiting to get fully filled (* one asterisk)

Once force-selled, the balance went on negative. 
The order remained open until the new forcesell order got filled.

I did not had time to check the logs as I went offline, but I will try to re-create the issue in the following days and I will post an update on this issue (unless you close it)....

You are right, the best way to avoid this issue is to not forcesell on pairs with open buy-orders...

The exchange trading / order history, as expected, it is only the telegram data / history that gets confused... 

Cheers

**Comment by xmatthias** [comment]
#3724 should correct this behavior and make forcesell a safer thing (cancels open buy orders - eventually cancels + replaces sell orders).
