### ISSUE TITLE
Add daily equity curve to plot profit 

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#3102]
It would be nice to have this statistic immediately when using plot profit in stake pair.

This could easily be plotted by doing some per day of /daily command

**Comment by xmatthias** [comment]
Great, feel free to contribute this 👍

**Comment by octaviusgus** [comment]
![image](https://user-images.githubusercontent.com/86911628/124382721-30c9c980-dcc9-11eb-93be-5c80066b87ec.png)
[patch_daily_profit.txt](https://github.com/freqtrade/freqtrade/files/6759788/patch_daily_profit.txt)

jupyter notebook snippet
```
# Plotting equity line (starting with 0 on day 1 and adding daily profit for each backtested day)

from freqtrade.configuration import Configuration
from freqtrade.data.btanalysis import load_backtest_data, load_backtest_stats
import plotly.express as px
import pandas as pd

# strategy = 'Strat'
# config = Configuration.from_files(["user_data/config.json"])
# backtest_dir = config["user_data_dir"] / "backtest_results"

stats = load_backtest_stats(backtest_dir)
strategy_stats = stats['strategy'][strategy]

equity = 0
equity_datapoints = []
for dp in strategy_stats['daily_profit']:
    equity_datapoints.append(equity)
    equity += float(dp)

dates = pd.date_range(strategy_stats['first_open_date'], strategy_stats['last_close_date'])

lower_len = min(len(equity_datapoints), len(dates))
df = pd.DataFrame({'dates':dates[:lower_len],'equity_datapoints':equity_datapoints[:lower_len]})

fig = px.line(df, x="dates", y="equity_datapoints")
fig.show()
```

@xmatthias I can do a PR for this, I'm just a little concerned about messing with hyperopt performance because it requires adding these lines to optimize_reports.generate_daily_stats:
```
daily_profits_list = daily_profit.tolist()
first_open_trade = min(results["open_date"])
last_close_date = max(results["close_date"])
```
solution could be optimized by complicating the jupyter notebook snippet and finding dates there, this was cleaner to write and to demo the solution.

**Comment by xmatthias** [comment]
it's great that you think about the performance - but how much will the impact really be (are we talking seconds in a 5h hyperopt run - or 1 hour on top of the 5 hours it takes before this?) - considering that we're talking about an array of 365 items per year maximum - and not about dumping the whole raw dataframe again and again ...

As such - i'd say - make a PR for it - and let's then look at the impact when it's "builtin" ... (i have my doubts that this will perform VERY bad ...).

is there a reason you can't use `backtest_end` and `backtest_start` for this? i'd want to have the plot show the whole backtest period - even though the first trade was only opened 2 days in ... ?

**Comment by octaviusgus** [comment]
didn't notice the backtest_start and backtest_end, I kept looking for kw "date" and "daily" in the project files. Will do a PR. it's pretty much 3 lines of code (could be even 1, but I'd rather follow the current code structure).

testing and creating a PR.

**Comment by octaviusgus** [comment]
using backtest_start and backtest_end fixes the issue with different array lengths as well, perfect. thanks

**Comment by xmatthias** [comment]
This is actually available through freqUI now since quite a while.

I'll therefore close this, as we don't intend to enhance regular plotting functionality further.
