### ISSUE TITLE
Segmentation fault Error while downloading data

### ISSUE THREAD

**Issue by acemi1** [freqtrade/freqtrade#3104]
I use this command to download historical data.
I get an error message before the process is completed.
Error 2: I rewrite the same command. It starts downloading from the beginning. BTC / USDT was downloaded in good health beforehand. Why is it wasting time downloading again?

There are 4 core CPUs and 8 GB RAM.
CPU and ram usage is at most 40% during the process. So 60% of system resources are free
freqtrade download-data --days 1200 --timeframes  1m

2020-03-23 19:45:36,297 - freqtrade.loggers - INFO - Verbosity set to 0
2020-03-23 19:45:36,298 - freqtrade.configuration.configuration - INFO - Using user-data directory: /root/freqtrade/user_data ...
2020-03-23 19:45:36,299 - freqtrade.configuration.configuration - INFO - Using data directory: /root/freqtrade/user_data/data/binance ...
2020-03-23 19:45:36,299 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1m']
2020-03-23 19:45:36,299 - freqtrade.configuration.configuration - INFO - Detected --days: 1200
2020-03-23 19:45:36,300 - freqtrade.configuration.configuration - INFO - Using "json" to store OHLCV data.
2020-03-23 19:45:36,300 - freqtrade.configuration.configuration - INFO - Using "jsongz" to store trades data.
2020-03-23 19:45:36,300 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-03-23 19:45:36,300 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-03-23 19:45:36,300 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-03-23 19:45:36,300 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-03-23 19:45:36,308 - freqtrade.commands.data_commands - INFO - About to download pairs: ['BTC/USDT', 'ETH/USDT', 'XRP/USDT', 'XLM/USDT', 'WAVES/USDT', 'ADA/USDT', 'EOS/USDT', 'BCH/USDT', 'LTC/USDT', 'TRX/USDT', 'NEO/USDT', 'LINK/USDT', 'DASH/USDT'], intervals: ['1m'] to /root/freqtrade/user_data/data/binance
2020-03-23 19:45:36,308 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-03-23 19:45:36,308 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-03-23 19:45:36,313 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2020-03-23 19:45:36,317 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-03-23 19:45:36,318 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-03-23 19:45:36,318 - freqtrade.exchange.exchange - WARNING - Markets were not loaded. Loading them now..
2020-03-23 19:45:37,082 - freqtrade.data.history.history_utils - INFO - Downloading pair BTC/USDT, interval 1m.
2020-03-23 19:45:37,082 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "BTC/USDT", timeframe: 1m and store in /root/freqtrade/user_data/data/binance.
2020-03-23 19:57:18,223 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT with length 1729007.
2020-03-23 19:57:27,227 - freqtrade.data.history.history_utils - INFO - Downloading pair ETH/USDT, interval 1m.
2020-03-23 19:57:27,228 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "ETH/USDT", timeframe: 1m and store in /root/freqtrade/user_data/data/binance.
Segmentation fault

**Comment by xmatthias** [comment]
Please fill out the issue template, so we know which version you're using (and also which operating system you're using).

  * Operating system: ____
  * Python Version: _____ (`python -V`) <-- Please make sure to be in the correct virtual environment
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)


Paths suggest you're on linux / macOS - so please also analyze system-level logs (`journalctl` for linux - not sure for macOS) from around the time where the error happened - it should have some information if the process was killed by the system.

**Comment by acemi1** [comment]
> Please fill out the issue template, so we know which version you're using (and also which operating system you're using).
> 
> * Operating system: ____ Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-70-generic x86_64)
> * Python Version: _____Python 3.6.9
> * CCXT version: _____  ccxt==1.24.83
> * Branch: Master | Develop
> * Last Commit ID: _____ 030c487d6b53fb2a4f52046b06be724fae253f45(`git log --format="%H" -n 1`)
> 
aiodns==1.1.1
aiohttp==3.6.2
arrow==0.15.5
async-timeout==3.0.1
atomicwrites==1.3.0
attrs==19.3.0
bleach==3.1.0
cachetools==4.0.0
ccxt==1.24.83
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
Click==7.0
coinmarketcap==5.0.3
colorama==0.4.3
coverage==4.5.4
coveralls==1.11.1
cryptography==2.8
decorator==4.4.1
defusedxml==0.6.0
docopt==0.6.2
entrypoints==0.3
filelock==3.0.12
flake8==3.7.9
flake8-tidy-imports==4.0.0
flake8-type-annotations==0.1.0
Flask==1.1.1
-e git://github.com/freqtrade/freqtrade.git@030c487d6b53fb2a4f52046b06be724fae253f45#egg=freqtrade
future==0.18.2
idna==2.8
idna-ssl==1.1.0
importlib-metadata==1.3.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
Jinja2==2.11.1
joblib==0.14.1
jsonschema==3.2.0
jupyter-core==4.6.1
MarkupSafe==1.1.1
mccabe==0.6.1
mistune==0.8.4
more-itertools==8.0.2
multidict==4.7.1
mypy==0.770
mypy-extensions==0.4.3
nbconvert==5.6.1
nbformat==4.4.0
numpy==1.18.2
packaging==19.2
pandas==1.0.3
pandocfilters==1.4.2
pkg-resources==0.0.0
plotly==4.5.4
pluggy==0.13.1
prompt-toolkit==3.0.4
py==1.8.0
py-find-1st==1.1.4
pyaml==19.12.0
pycares==3.0.0
pycodestyle==2.5.0
pycoingecko==1.2.0
pycparser==2.19
pyflakes==2.1.1
Pygments==2.5.2
pyparsing==2.4.5
pyrsistent==0.15.6
pytest==5.4.1
pytest-asyncio==0.10.0
pytest-cov==2.8.1
pytest-mock==2.0.0
pytest-random-order==1.0.4
python-dateutil==2.8.1
python-rapidjson==0.9.1
python-telegram-bot==12.4.2
pytz==2019.3
PyYAML==5.3
questionary==1.5.1
requests==2.23.0
requests-cache==0.5.2
retrying==1.3.3
scikit-learn==0.22.2.post1
scikit-optimize==0.7.4
scipy==1.4.1
sdnotify==0.3.2
six==1.13.0
SQLAlchemy==1.3.15
TA-Lib==0.4.17
tabulate==0.8.7
testpath==0.4.4
tornado==6.0.3
traitlets==4.3.3
typed-ast==1.4.0
typing-extensions==3.7.4.1
urllib3==1.25.8
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.16.0
wrapt==1.12.1
yarl==1.1.0
zipp==0.6.0

> Paths suggest you're on linux / macOS - so please also analyze system-level logs (`journalctl` for linux - not sure for macOS) from around the time where the error happened - it should have some information if the process was killed by the system.
> 
> Also, don't even look at CPU - that's definitely not what causes anything related to download-data to fail (not with 4 cores, anyway).

I couldn't find the journalctl file. In which folder?

**Comment by hroff-1902** [comment]
journalctl is the system utility: https://www.linode.com/docs/quick-answers/linux/how-to-use-journalctl/

**Comment by acemi1** [comment]
> journalctl is a system utility: https://www.linode.com/docs/quick-answers/linux/how-to-use-journalctl/
> 
> you may also use syslog: https://www.linux.com/topic/desktop/viewing-linux-logs-command-line/

journalctl --since "2020-03-23 19:57:18"

There are no error messages related to
I only saw one hacker trying to log into the system.

pam_unix(sshd:auth): check pass; user unknown
 pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=212.47.250.50
Failed password for invalid user julie from 212.47.250.50 port 55746 ssh2
Received disconnect from 212.47.250.50 port 55746:11: Normal Shutdown, Thank you for playing [preauth]
 Disconnected from invalid user julie 212.47.250.50 port 55746 [preauth]
Invalid user restricted_user from 212.47.250.50 port 45338
..
 Failed password for invalid user juliejung from 212.47.250.50 port 38020 ssh2
..
 Failed password for invalid user ronjones from 212.47.250.50 port 51740 ssh2
..
Disconnected from invalid user ovhusr 212.47.250.50 port 59008 [preauth]
..
Invalid user vpn from 150.136.149.102 port 56576
..
 Failed password for invalid user admin from 45.236.183.45 port 48835 ssh2
Received disconnect from 45.236.183.45 port 48835:11: Bye Bye [preauth]
 Disconnected from invalid user admin 45.236.183.45 port 48835 [preauth]

**Comment by xmatthias** [comment]
>  Normal Shutdown, Thank you for playing [preauth]

hah - i know that message - i get that all the time on my servers ... 
but i wonder that you only got one hacker trying to log in - i get multiple per hour ... (but that's a different topic alltogether).

---

I think the best thing to do is to run the command again with the `-v` flag (and `--logfile dldatalog.txt`) - so we get the full log. the dldatalog.txt file keeps all of the logs ... which i hope will provide us with some feedback.

for background: The way download-data works is it logs this message, and then stays "quiet" until it's done downloading - so it's unknown at what stage of the process this error happened, it could be while downloading, or while writing to disk... (unless an error happens, it's not really relevant where it is).

**Comment by hroff-1902** [comment]
@xmatthias should we close this?

**Comment by xmatthias** [comment]
well - it's difficult to determine what's causing it without the logs ... :( 

One point with Segmentation fault is bad memory - You might hit this "randomly" whenever ram starts to fill up  ... in which case the only solution would be to exchange the faulty ram-module .

another  thing i can imagine is that it's memory (not out of memory - but out of memory for this process - somehow limited by ulimit (?)).

----

Freqtrade does dump this to disk per pair - so once the first pair finishes, it'll dump that to disk and continue with the next pair (so memory usage should go up and down when downloading multiple pairs).

The complexity of dumping the data every X calls would be pretty high (especially considering that all calls are made in an async way ...) - and in my opinion currently not worth the effort.
Also, it would increase the strain on the disks - which can become a cost-factor depending on the storage used  - especially since json / jsongz do not support appending, but must be written as completely, so it would still need to read all data into memory - at which point it would not have helped any.


Also, when use correctly, then  `download-data` is intended to download the huge junk once - and then subsequently only download the missing pieces - which will be done very quickly.

you run it with `--days 700` once to get 2 years of data - and then subsequenly use `--days 20` - and run this command every 10-15 days - and the bot will always keep the "current" state.

---

I agree, we can close this - we won't implement "periodic" dumping - and a segmentation fault is not something we are likely to fix, as it's related to the machine - not to bot code.

**Comment by acemi1** [comment]
freqtrade download-data --days 1800 --timeframes 1m 5m 15m  30m 1h 4h 1d -v --logfile dldatalog1dtumu1800.txt

https://github.com/freqtrade/freqtrade/issues/3104#issue-586380443 As I mentioned here
"There are 4 core CPUs and 8 GB RAM.
CPU and ram usage is at most 40% during the process. So 60% of system resources are free "

[dldatalog1dtumu1800.txt](https://github.com/freqtrade/freqtrade/files/4495018/dldatalog1dtumu1800.txt)

[dldatalog1dtumu1800-1.txt](https://github.com/freqtrade/freqtrade/files/4495020/dldatalog1dtumu1800-1.txt)
[dldatalog1dtumu1800-2.txt](https://github.com/freqtrade/freqtrade/files/4495021/dldatalog1dtumu1800-2.txt)
