### ISSUE TITLE
use freqtrade as systemd service on vps 

### ISSUE THREAD

**Issue by hanswayne23** [freqtrade/freqtrade#3105]
## Step 1: Have you search for this issue before posting it?

Yes, but i couldnt get right answer

## Step 2: Describe your environment

  * Operating system: ____ Ubuntu 19.10 x64
  * Python Version: _____3.7.5
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master - Develop
  * Last Commit ID: _____ f320c0a410e5832d4a3fc35647aa6fea6a958b
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*

i tried to run this command /home/hstest/freqtrade/.env/bin/freqtrade trade -c /home/hstest/freqtrade/config.json --strategy SampleStrategy --userdir /home/hstest/freqtrade/
on /freqtrade/freqtrade command line but the error i can see all the time is failed to load Sample Strategy.

Kindly needed help on this one. Thanks.

### Steps to reproduce:

I bought online course and this the details that i follow to run systemd on freqtrade

Go to ~/freqtrade/freqtrade, and edit the file called main.py using nano:

nano main.py
```
#!/root/freqtrade/.env/bin/python3

"""
Main Freqtrade bot script.
Read the documentation to know what cli arguments you need.
"""

from freqtrade.exceptions import FreqtradeException, OperationalException
import sys
# check min. python version
if sys.version_info < (3, 6):
    sys.exit("Freqtrade requires Python version >= 3.6")

# flake8: noqa E402
import logging
from typing import Any, List

from freqtrade.commands import Arguments


logger = logging.getLogger('freqtrade')


def main(sysargv: List[str] = None) -> None:
    """
    This function will initiate the bot and start the trading loop.
    :return: None
    """

...


Add the freqtrade systemd service using:

sudo systemctl edit --force --full freqtrade.service



Paste the following:

[Unit]
Description=Freqtrade Service
Wants=network.target
After=network.target

[Service]
ExecStartPre=/bin/sleep 10
ExecStart=/root/freqtrade/freqtrade/main.py trade -c /root/freqtrade/config.json --strategy DefaultStrategy --userdir /root/freqtrade/
Restart=always

[Install]
WantedBy=multi-user.target
```

  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
So to understand this correctly - running `/home/hstest/freqtrade/.env/bin/freqtrade trade -c /home/hstest/freqtrade/config.json --strategy SampleStrategy --userdir /home/hstest/freqtrade/` does generate the error that `SampleStrategy` was not found?

what are the contents of `/home/hstest/freqtrade/`? (you should be able to show this using `ls -l /home/hstest/freqtrade/`.

**Comment by hanswayne23** [comment]
Yes. you are right doesgenerate the error that SampleStartegy was not found.

i tried to execute using ls -l /home/hstest/freqtrade/ but it showed cannot access /home/hstest/freqtrade/ : no such file or directory? 

Kindly what i need to do next?

**Comment by xmatthias** [comment]
fix your directories / paths? 
i assume you've got something wrong in the path - probably the user (but who knows) ... i've just copy/pasted what you've posted above ...

**Comment by hanswayne23** [comment]
i will try to fix my directories / paths.

just in case can i just use screen as alternative to systemd?. Im not really a programmer. i might encounter too much problem on fixing directories and paths? 

i want to really learn on how to use freqtrade as systemd service but if i will encounter difficulties on fixing my directories / paths i might opt out to use screen instead. if that is ok?

Thanks.

**Comment by hroff-1902** [comment]
screen will keep your running sessions when you logout, but you need to start freqtrade manually when you restart the system or if it fails

**Comment by xmatthias** [comment]
but your issue is not with systemd if i understood the initial issue correctly.

you're having problems running freqtrade within your shell when using the following command:
```
/home/hstest/freqtrade/.env/bin/freqtrade trade -c /home/hstest/freqtrade/config.json --strategy SampleStrategy --userdir /home/hstest/freqtrade/
```

As long as this does not work correctly, there's no point in using systemd (nor sceen)- but you need to get the installation (or paths) fixed first - as the same problem will happen in screen / tmux / everything else.

Once running freqtrade "the usual way" works you can start transferring the settings to the systemd file - but without having it working first there's no point.

**Comment by hanswayne23** [comment]
thank you for your reply and details. i will install a new freqtrade and setup systemd at service from scratch. i will let you know if it is successful or not.

**Comment by hanswayne23** [comment]
Installed freqtrade from scratch

sudo apt update

sudo apt install python3-pip

git clone https://github.com/freqtrade/freqtrade.git

cd freqtrade

sudo apt-get install python3-venv

sudo apt install python3-pip

bash ./setup.sh --install

source .env/bin/activate

pip3 install -e .

freqtrade --version

and run the basic command of freqtrade and its working

but when i try to apply systemd

~/freqtrade/freqtrade

opened nano main.py and edited the top to #!/root/freqtrade/.env/bin/python3

and start to run /root/freqtrade/freqtrade/main.py trade -c /root/freqtrade/config.json 
--strategy SampleStrategy --userdir /root/freqtrade/ before putting it to sudo systemctl edit --force --full freqtrade.service

the error is still the same - Impossible to load Strategy 'SimpleStrategy'

Should i study futher on systemd? So i can undertand more on how to use it?

Thanks.

**Comment by xmatthias** [comment]
well first of all, try to activate the virtual environment, and run the command you're adding to the systemd service manually.

That'll tell you if SampleStrategy is present or not.

Based on the commands above, i don't think it is, so please run the following two commands from the freqtrade base/root directory

```bash
source .env/bin/activate
freqtrade create-userdir --userdir user_data
```

This will create the sample files in the user_data directory.
Then try to run the above command again (not with systemd, but manually first). 

There's no point in using systemd (or anything else) if you're unable to run the command interactively first.

**Comment by hanswayne23** [comment]
Thank you for your reply. 

There is a typo error in my message above instead of 'SimpleStrategy' its 'SampleStrategy'

When i run the basic freqtrade there is no problem.

![freq-new-install-vps-march-27-20-9](https://user-images.githubusercontent.com/55561332/77751460-bdb2bb80-7060-11ea-94ee-5f0454c4a09e.jpeg)

But when i run with systemd that i implemented based on the tutorial i bought there is a 
problem with running SampleStrategy

![freq-new-install-vps-march-27-20-11](https://user-images.githubusercontent.com/55561332/77751559-e89d0f80-7060-11ea-886a-1bd45f4cb3c2.jpeg)

Kindly need help on this one. Thanks.

By the way hope you and hroff-1902 are doing well in this crazy time due to coronavirus.

Take care!!! :)

**Comment by xmatthias** [comment]
which tutorial are you following that tells you to use main.py? that's nowhere in our documentation - and shouldn't be used since quite a long time.

The correct path to use for ExecStart can be determined by running `which freqtrade` with activated virtual environment.

the systemd file you're using should look as follows (please correct the path if the above command shows something differently - as i'm NOT in your environment, but i'm typing from screenshots ...).

```
[Unit]
Description=Freqtrade Daemon
After=network.target

[Service]
# Set WorkingDirectory and ExecStart to your file paths accordingly
# NOTE: %h will be resolved to /home/<username>
WorkingDirectory=%h/freqtrade
ExecStart=/root/freqtrade/.env/bin/freqtrade trade  <whatever other parameter>
Restart=on-failure

[Install]
WantedBy=default.target


```

**Comment by hanswayne23** [comment]
the online course is called run your trading robot on a vps or raspberry pi.

i followed your instruction and it resulted to:

source .env/bin/activate
which freqtrade
/root/freqtrade/.env/bin/freqtrade

So the next step that i have to do based on your website freqtrade.io is:

copy freqtrade.service file to your systemd user directory (usually ~/.config/systemd/user) and update it.

i tried to find ~/.config/systemd/user to copy freqtrade.service file but i couldn't find it?

i try to find systemd
source .env/bin/activate
which systemd
i got: /usr/bin/systemd

so i will copy updated freqtrade.service file to /usr/bin/systemd? 

cp freqtrade.service /usr/bin/systemd - i hope this is correct?

i edited freqtrade.service document:
[Unit]
Description=Freqtrade Daemon
After=network.target

[Service]
# Set WorkingDirectory and ExecStart to your file paths accordingly
# NOTE: %h will be resolved to /home/<username>
WorkingDirectory=/home/skfreqtrade/freqtrade
ExecStart=/root/freqtrade/.env/bin/freqtrade trade  --config /root/freqtrade/config.json --strategy SampleStrategy
Restart=on-failure

[Install]
WantedBy=default.target

I hope the edited details above of freqtrade.service file is correct?

Thanks.

**Comment by xmatthias** [comment]
Letme be honest - using systemd for freqtrade is seen as an advanced technique (that's why the documentation page lists it as  "advanced post-install", which will require certain linux skills to be available.

I would suggest to raise this with the course authors (best in the course comments) - as obviously they did not explain this well (not how to use it - nor that there are certain pre-requirements).
The course ifself is based on top of freqtrade - but the authors are not part of the team, nor contributors to freqtrade (therefore they are seen as not affiliated to freqtrade at all).


copying the file to ` /usr/bin/systemd` will not work.
The documentation explains this - copy it either to `~/.config/systemd/user` (create the folder if it doesn't exist - but depending on the system this folder is ignored, thats why we got the fallback folder of `/etc/systemd/user/` in the documentation). 

----

Now being honest (please don't feel offended) - with the struggles and questions you got so far, i don't think running freqtrade as systemd-service is a good idea for you.

Best use the simplest method to run freqtrade - which is via docker (i use this myself, as it's the fastest (and recommended) way to get started).
Everything else will require a certain level of linux system knowledge, which i don't feel in you,, reading through this issue.

**Comment by hanswayne23** [comment]
Oh ok. i understand.

I already raised this concern of mine with the course authors. but so far i got one reply only
im waiting for more reply from their end with regards to my questions.

Im not offended. your just telling me what is reality.

ok i will try running freqtrade via docker. is there a function in docker that is similar to systemd
that can run freqtrade 24/7? 

also kindly can you recommend online tutorial or online course of how to use docker?

thank you for your help and guidance. im a bit sad right now because i have been studying 
freqtrade and linux for couple of months now. and i didnt expect i will have a problem like this.

anyway i will start studying freqtrade for docker right now. if you have any recommendation 
just let know? plus i will still continue on exploring freqtrade using linux.

**Comment by hanswayne23** [comment]
by the way i saw this article online. Kindly i would like to know if this proper way of setting up docker for freqtrade. Thanks.

https://www.publish0x.com/ijhdev/setting-up-a-simple-crypto-trading-bot-xmkpmn

**Comment by hroff-1902** [comment]
> https://www.publish0x.com/ijhdev/setting-up-a-simple-crypto-trading-bot-xmkpmn

That article was created almost year ago, it's no longer relevant to be followed one-to-one

>  if this proper way of setting up docker for freqtrade.

The proper way to of setting up docker for freqtrade is one described in the docs: https://www.freqtrade.io/en/latest/docker/

It's detailed enough. Why do you need to search for additional articles for installing rather then simply follow the bot's docs?

**Comment by xmatthias** [comment]
> is there a function in docker that is similar to systemd
that can run freqtrade 24/7? 

That's the default method when using the docker-compose file from this repository:

```yml
restart: unless-stopped
```

**Comment by hanswayne23** [comment]
freqtrade docker install

$ sudo apt-get remove docker docker-engine docker.io containerd runc

sudo apt-get update

sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

$ sudo apt-key fingerprint 0EBFCD88

$ sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

$ sudo apt-get update

$ sudo apt-get install docker-ce docker-ce-cli containerd.io

$ sudo docker run hello-world

Install docker compose

sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

sudo chmod +x /usr/local/bin/docker-compose

Docker quick start freqtrade

mkdir ft_userdata
cd ft_userdata/
# Download the docker-compose file from the repository
curl https://raw.githubusercontent.com/freqtrade/freqtrade/develop/docker-compose.yml -o docker-compose.yml

# Pull the freqtrade image
docker-compose pull

# Create user directory structure
docker-compose run --rm freqtrade create-userdir --userdir user_data

# Create configuration - Requires answering interactive questions
docker-compose run --rm freqtrade new-config --config user_data/config.json

i edited config.json to my account but i didnt touch the strategy yet. i stayed with SampleStrategy
to test it first.

so to run the freqtrade :root@dockerfreqtrade:~/ft_userdata# docker-compose up -d? 
using docker-compose up -d my bot will run 24/7? so i dont need to run systemctl of systemd?

i stopped the bot by pressing stop on my telegram

so everytime i wanted to run the bot 
cd ft_userdata# docker-compose up -d?

can i use filezilla to transfer my strategy file inside the docker freqtrade to change my strategy file?

based on the all the details i presented i hope im doing the right thing?

Thanks.

**Comment by xmatthias** [comment]
This looks good so far - you've got telegram messages, so the configuration seems to have worked.

To add files / strategies, you should have a folder called user_data in the directory you've been operating out of (`~/ft_userdata`) - simply copy everything user-related into that directory (`~/ft_userdata/strategies/` for strategies).

to "properly" stop the bot (so the process is not running), use `docker-compose stop`.

You can also try the "automatic" startup by restarting the server. once the server is back up, you should get messages on telegram of the bot starting up (you'll obviously have to call `/stop` to stop the bot again).

you can also check it's running with either `docker-compose ps` - or `docker ps` - which should both show you one container of the bot running.

You can get to the logs by using `docker-compose logs --tail 100 -f` - or by using `tail -f user_data/freqtrade.log` (you need to ctrl+c out of both commands).

Hope this helps

**Comment by hanswayne23** [comment]
To add files / strategies, you should have a folder called user_data in the directory you've been operating out of (~/ft_userdata) - simply copy everything user-related into that directory (~/ft_userdata/strategies/ for strategies).
- will i use filezilla to transfer strategy file or
- linux command cp BBRSI /ft_userdata/user_data/strategies?

once the strategy file is successfully copied at user_data so the SampleStrategy file will automatically replaced or erased?

to run freqtrade docker basic command:

/ft_userdata docker-compose run freqtrade trade --config user_data/config.json --strategy SampleStrategy

to "properly" stop the bot (so the process is not running), use docker-compose stop.
-yes, docker-compose stop worked properly but i didnt see any notification on my telegram that the bot stopped when i checked it via docker-compose ps it indicates that the bot had exit.

You can also try the "automatic" startup by restarting the server. once the server is back up, you should get messages on telegram of the bot starting up (you'll obviously have to call /stop to stop the bot again).

What do you mean by "automatic startup by restarting the server? is there a docker freqtrade command that i need to run for this?

-i tried docker-compose start to turn it on again and it worked.
i not sure what command should i run in order for freqtrade bot to run again is it:
docker-compose start?
docker-compose up?
or docker-compose run?

you can also check it's running with either docker-compose ps - or docker ps - which should both show you one container of the bot running.
-yup this is working

You can get to the logs by using docker-compose logs --tail 100 -f - or by using tail -f user_data/freqtrade.log (you need to ctrl+c out of both commands).
- im a bit confuse on this one should i run this command while freqtrade is running or freqrade is stop?

Hope all the details i provided is correct?

Thanks.

**Comment by xmatthias** [comment]
> What do you mean by "automatic startup by restarting the server? is there a docker freqtrade command that i need to run for this?

make sure the bot is running in docker compose (`docker-compose up -d`) - then `sudo reboot` .
after the server comes back, log back in, and the bot should be up again (you'll also get telegram messages for this).


Well fetching logs will work while the bot is running (but the 2nd command (tail -f) will also work after it's been stopped).


Anyway, all of this is covered either in the documentation (how to docker-compose), or in generic documentation regarding linux or docker - or by simply using google, i'll therefore close this issue.

**Comment by raminhafezi** [comment]
Hi, 
Have you checked/tried this config on systemd
http://hacks-for-life.blogspot.com/2020/12/run-code-on-raspberry-pi.html
