### ISSUE TITLE
Trades are running in Telegram although closed in Exchange. Bot and Exchange Sync is not working.

### ISSUE THREAD

**Issue by rnaveen99-github** [freqtrade/freqtrade#3109]
When running my bot, I have closed the python by pressing cntrl+C. 

This stopped by bot but the telegram still shows few trades running in the background. When I went into my Bittrex account, I could not see any of these trades. I tried to sell these trades on Telegram by /forcesell. But this did not work. 

I have restarted my computer, changed my API. Nothing did not work. The problem is I could ignore those trades in Telegram. But problem is that, a new trade will not be picked by same pair unless the present one is closed. So I am loosing three very important trades. 

This does not happen when I am running my bot in dry mode. The dummy trades come back only when I am on live mode. 

They do not obey my strategy as well. Please help me in resolving this problem. Thank you.

**Comment by xmatthias** [comment]
just to be sure as it sounds like the following  - you've been running the bot in dry-run - and 3 trades have been created.

You've then stopped the bot, switched to production, but you then still see the 3 trades?
If that's the case (and these are the only 3 trades) - then best rename / remove the database and start fresh.
If the bot did other trades, then best use [SQL Cheatsheet](https://www.freqtrade.io/en/latest/sql_cheatsheet/) to close or remove the trades manually from the exchange.

If the above is not correct:

* What does `/status table` show you? 3 trades?
* do you own these assets on the exchange?

**Comment by rnaveen99-github** [comment]
The three trades started running in Live mode (production). 

In the dry run, these 3 trades are not active. But once in live mode, these 3 trades appear.

I tried to remove these trades by /forcesell on Telegram, but it does not work. Says Insufficient funds to sell. This occurs because it cannot see it in exchange.

I do not have these on Bittrex account to manually remove.

I have even changed my API.But still does not work. Please help.

**Comment by xmatthias** [comment]
Please use the [SQL cheatsheet](https://www.freqtrade.io/en/latest/sql_cheatsheet/) and remove them from the database (queries are in the documentation).

Since you don't own these assets - you obviously cannot sell them. changing the API keys won't help since it's still the same acount on Bittrex.

**Comment by rnaveen99-github** [comment]
Ok Will try it. Thanks.

**Comment by rnaveen99-github** [comment]
Yes it worked. thank you very much for your help.

**Comment by xmatthias** [comment]
you're welcome - no problem :)
