### ISSUE TITLE
question about orders and portfolio managing

### ISSUE THREAD

**Issue by Amarchuk** [freqtrade/freqtrade#3113]
Hi there,

Great project! I read docs, code examples and search the existing issues, but still not sure about some important parts:

1. For example, I want to sell half of my BTC to get ETC regardless of the price. Is it possible?

2. I am not sure how the trading works when we just setup buy/sell signals in dataframe without stoploss etc. (are they set by default somewhere?) If we set "buy" for same row in `df` for both ETC/BTC and LTC/BTC - what will happen with our BTC amount? Or this is not possible and we can work with just one pair at the time?

3. In hyperopt part is it possible to provide the same parameters to `buy_strategy_generator`/`sell_strategy_generator`? So find the best parameters optimized for both sell and buy at the same time.

If a question covered in documentation - the link is appreciated. Thanks!

**Comment by hroff-1902** [comment]
"are they set by default somewhere?" -- what "they", stoplosses or buy/sell signals?

**Comment by Amarchuk** [comment]
> -- what "they", stoplosses or buy/sell signals?

Sorry, stoplosses, not signals

**Comment by xmatthias** [comment]
1) no - no position stacking / scaling out of a trade (not automated, anyway)
2) well usually you set a stake_amount - so assuming you own 1.1 btc - and want 2 open trades at a time - you'd set `stake_amount=0.5` - and freqtrade will use 0.5BTC for every trade. There's other configuration methods and possibilities - which are described in the [docs](https://www.freqtrade.io/en/latest/configuration/).
3) well yes it is possible (although manually) - but normally you'd want this different - you would compare RSI < X for buys, and RSI > X for sells ... (or viceversa) ... doing RSI < X on both sides will not work well ... so i think using some kind of "strategy idea" before starting the hyperopt process does make sense and will facilitate faster results (assuming the idea is good, obviously)

**Comment by hroff-1902** [comment]
1. You can set stake_amount to 'unlimited', and if you have 2 pairs in your pairlist -- it will SELL half of your BTC to buy one of those pairs (assuming BTC is set as the stake currency).
*) Almost half, leaving small portion reserved for fee and to avoid rounding problems
**) Also read about the `tradable_balance_ratio` setting.
***) Read about stake amounts in general: https://www.freqtrade.io/en/latest/configuration/#configuring-amount-per-trade

**Comment by Amarchuk** [comment]
@xmatthias, @hroff-1902  - thanks for the clarification and fast response! It helps, I really miss a part of configuration process.

About 3.: Fair point, I forget to mention that will use a custom loss for this case.

My usecase strategy is simple to formulate: I have a portfolio with some weights (for example [0.25, 0.5, 0.25, 0.0]) and on each step I have new prediction of the weights and thus need to sell/buy several pairs to rebalance according to prediction. Previously I did this manually calculating limit prices and tradable amount and it works more or less correctly. And I try to understand if it possible to develop such approach here, because really wanted to use all cool features `freqtrade` propose (they and project itself looks far more best from any other project I experienced before).

**Comment by xmatthias** [comment]
portfolio management / rebalancing is not the purpose nor the scope of freqtrade - it's a trading bot - which buys / sells assets.


While the grand goal might be similar (increase profits / wealth) - the 2 goals are not really compatible from an architectural standpoint, so i doubt you can use freqtrade for portfolio management the way you imagine.

**Comment by Amarchuk** [comment]
Thanks again for the explanation
