### ISSUE TITLE
Issues starting the bot

### ISSUE THREAD

**Issue by ayricky** [freqtrade/freqtrade#3114]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: ____Ubuntu 19.10 x64
  * Python Version: _____ 3.6.9
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

I can't seem to find a solution to this problem searching through the issues threads. I'm new to Freqtrade and I can't seem to get the bot to start.  After going through the configuration process I try to start the bot and I keep getting this traceback.

```
  File "/home/ricky/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/ricky/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker = Worker(args)
  File "/home/ricky/freqtrade/freqtrade/worker.py", line 34, in __init__
    self._init(False)
  File "/home/ricky/freqtrade/freqtrade/worker.py", line 50, in _init
    self._config = Configuration(self._args, None).get_config()
  File "/home/ricky/freqtrade/freqtrade/configuration/configuration.py", line 41, in get_config
    self.config = self.load_config()
  File "/home/ricky/freqtrade/freqtrade/configuration/configuration.py", line 94, in load_config
    config: Dict[str, Any] = self.load_from_files(self.args.get("config", []))
  File "/home/ricky/freqtrade/freqtrade/configuration/configuration.py", line 73, in load_from_files
    config = deep_merge_dicts(load_config_file(path), config)
  File "/home/ricky/freqtrade/freqtrade/configuration/load_config.py", line 27, in load_config_file
    config = rapidjson.load(file, parse_mode=CONFIG_PARSE_MODE)
rapidjson.JSONDecodeError: Parse error at offset 25: Invalid value.
  ```

There may be a very simple solution to this sorry for the hassle. I'm fairly new to code. 
It seems whatever I try to run I get the same traceback error. Appreciate your patience.

### Steps to reproduce:

  1.  freqtrade trade -c ./config.json
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
I tried to start the bot
  * What did you expect to happen?
The bot to start
### Relevant code exceptions or logs:

  ```
  ```

**Comment by xmatthias** [comment]
> rapidjson.JSONDecodeError: Parse error at offset 25: Invalid value.

well - your configuration has an invalid value at character 25.

i'd suspect it's `.10` instead of `0.10` for stake_amount - but it could be anything else too.
Best open the configuration file with a syntax-highlighting editor which should point out the error in color.

**Comment by ayricky** [comment]
It seems it was the max_open_trades field.
I had it as:
"max_open_trades": unlimited,

I set it to 3 and it seems to have started fine. Though I thought that field could be unlimited?
Again thank you for your patience, I knew it had to be something stupid. Appreciate the help!

**Comment by hroff-1902** [comment]
```
"max_open_trades": -1,
```
for unlimited (refer to the description of this option in the table: https://www.freqtrade.io/en/latest/configuration/)

**Comment by hroff-1902** [comment]
@xmatthias let's allow `"unlimited"` as an alias for `-1` for this option?

**Comment by xmatthias** [comment]
well but even if - `"unlimited" != unlimited` ... so that wouldn't have prevented this either
