### ISSUE TITLE
How to allocate trade size based on currency pair?

### ISSUE THREAD

**Issue by magick93** [freqtrade/freqtrade#3118]
## Step 2: Describe your environment

  * Operating system: using docker image - master tag

  
## Step 3: Describe the problem:

I'm using a strategy that allocates funds(risk) based on the result of one or more indicators. For example:
-  if price goes below lower bband, then trade one unit
- if rsi is greater than x then trade two units. 
- if market is ETCBTC, and if price goes below lower bband, then trade 2.5 units
- if market is DOGEBTC, and if price goes below lower bband, then trade 0.5 units

In short, I'm wondering how/where does one set the trade size?

Am I correct in thinking that all buy signals and sell signals in Freqtrade have the same weight? And a buy signal, for example, regardless of what rules produced the signal, will then create an order with the same amount at risk?

In Freqtrade are all markets, and all signals are essentially given the same weight / treated the same? 

I really hope my understanding is a misunderstanding - it would seem odd to treat all technical indictor signals as being the identical on all markets. Each market should be seen as unique.

**Comment by hroff-1902** [comment]
* no position management yet (so you cannot set custom size for each trade, only with existing freqtrade settings)
* you can implement any weights for the parts of your buy/sell signal in the strategy methods

**Comment by magick93** [comment]
HI @hroff-1902 

Thanks for the prompt reply.

> there are no "all signals", there is only one buy and only one sell signal, which is returned by the strategy methods

Perhaps my wording wasnt the best. What I meant is, are all signals, long or short, given the same weight? For example, a golden cross on market ABC might be something I consider to have a high probability of profit, whereas a over sold signal on market XYZ might be something I consider to have a medium probability of profit.  


> if you need the buy/sell signals be calculated with different conditions/values for different pairs -- use the name of the pair, passed to the strategy method to alter calculations depending on pair.

Ok, this sounds closer to what I'm seeking. Do you mean I should pass the pair into the strategy constructor?

**Comment by magick93** [comment]
I've seen a few other posts from users requesting features that are somewhat similar - at least they all require the ability to set the trade size:

- https://github.com/freqtrade/freqtrade/issues/2183
- https://github.com/freqtrade/freqtrade/issues/3113

While the authors of the above are looking for different specific cases, they all require the ability to treat each market as unique, and thus being able to determine risk allocation appropriately - unlike the current mechanism that is hardcoded to treat the portfolio of coins as equal.

What I was thinking, as a possible solution, is that the `BUY` value is a percentage rather than a boolean, eg:

```
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['rsi'], 30)) &  # Signal: RSI crosses above 30
                (dataframe['tema'] <= dataframe['bb_middleband']) &  # Guard: tema below BB middle
                (dataframe['tema'] > dataframe['tema'].shift(1)) &  # Guard: tema is raising
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'buy'] = setBuyStakeAmount(dataframe) # returns a value between 0 - 1. This is a percentage of the stack amount

        return dataframe
```

**Comment by xmatthias** [comment]
well the discussion on how to change the interface is in #2183 ... 

This was one proposal there, too - but has drawbacks as well as it'll limit other advanced possible usecases i'll not repeat here.

The problem with defining an interface is to find an approach which is enabling certain things, without blocking other things in the future. The same applies to changing an existing interface, while keeping compatibility to the existing interface.

Yes, using percentages is one possibility - but it would limit usage of leverage (what would buy=2.0 mean - buy 200% - or buy 1 with 2x leverage? or 0.5 with 4x leverage)?

I do have a (rough) list in mind as to what must be supported by a new interface - and i'll probably add that to #2183 at a later point... 


However, i'll be honest, this is (at the moment) not really a priority (the day has only so many hours) - and i think the bot works fine without this for the most part - and there's other things (stability - if you look at the latest issues) which will always have higher priority than enhancements.

**Comment by xmatthias** [comment]
I'll close this to move further discussion to #2183, as the topic here overlaps almost completely.
