### ISSUE TITLE
Inconsistent backtest results (conditions unchanged)

### ISSUE THREAD

**Issue by acemi1** [freqtrade/freqtrade#3132]
## Step 1: Have you search for this issue before posting it?
Yes
If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment
  * Operating system: ____Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-91-generic x86_64)
  * Python Version: _____ Python 3.6.9
  * CCXT version: _____ ccxt==1.24.83
  * Branch: Master | Develop
  * Last Commit ID: _____ 39ea1266981d0e207159d978b4ac90a4142c7a56
  
## Step 3: Describe the problem:
config.json , strategy file and although the test date range does not change, the backtest results are very different
*Explain the problem you have encountered*

### Steps to reproduce:

`freqtrade backtesting --strategy-list   ADXMomentum AdxSmas ASDTSRockwellTrading AverageStrategy AwesomeMacd BbandRsi   BinHV27 BinHV45 CCIStrategy ClucMay72018 CMCWinner CofiBitStrategy   CombinedBinHAndCluc DoesNothingStrategy EMASkipPump   Freqtrade_backtest_validation_freqtrade1 InformativeSample Low_BB   MACDStrategy MACDStrategy_crossed Quickie ReinforcedQuickie   ReinforcedSmoothScalp Scalp Simple SmoothScalp TechnicalExampleStrategy   hokes1 strateji1 strateji3 strateji2 strateji ichimoku1 ichimoku2 hokes   --timerange=20200101- --ticker-interval 5m`

 
```
Result for strategy hokes
====   BACKTESTING REPORT   ====
  | Pair | Buys | Avg Profit % | Cum Profit % | Tot Profit % | Avg Duration | Wins | Draws | Losses |  

  | BTC/USDT | 33 | -0.24|  -7.81|-1.56 | 2 days,8:11:00 | 18 | 0 | 15 |  
  | ETH/USDT | 66 | 0.19 | 12.40 | 2.48 | 1 day, 3:25:00 | 39 | 0 | 27 |  
  | XRP/USDT | 50 | 0.17 | 8.57  | 1.71 | 1 day, 12:36:00| 29 | 0 | 21 |  
  | XLM/USDT | 57 | 0.31 | 17.79 | 3.56 | 1 day, 7:44:00 | 33 | 0 | 24 |  
  |WAVES/USDT| 72 |-0.10 |-7.24  |-1.45 | 1 day, 0:32:00 | 37 | 0 | 35 |  
  | TOTAL   | 278 | 0.09 | 23.71 | 4.74 | 1 day, 8:37:00 | 156 | 0 | 122 |  
======================================================   SELL REASON STATS =======================================================
  | Sell Reason | Sells | Wins | Draws | Avg Profit % | Cum Profit % | Tot Profit USDT | Tot Profit % |  
 -------------------------------------------------------------
  | roi        | 151 | 151 | 0 | 5.85  | 883.9    | 884.788 | 176.78 |  
  | stop_loss  | 122 | 0   | 0 | -7.19 | -876.67  | -877.546 | -175.33 |  
  | force_sell | 5   | 5   | 0 | 3.3   | 16.48    | 164.935 | 3.3 |   |  
====   LEFT OPEN TRADES REPORT   
===========================================
  | Pair | Buys | Avg Profit % | Cum Profit % | Tot Profit % | Avg Duration | Wins | Draws | Losses |  
  ------------------------------------------------------------------------------------
  | BTC/USDT | 1 | 3.66 | 3.66 | 0.73 | 4:45:00 | 1 | 0 | 0 |  
  | ETH/USDT | 1 | 5.01 | 5.01 | 1.00 | 4:50:00 | 1 | 0 | 0 |  
  | XRP/USDT | 1 | 2.67 | 2.67 | 0.53 | 4:50:00 | 1 | 0 | 0 |  
  | XLM/USDT | 1 | 2.18 | 2.18 | 0.44 | 3:15:00 | 1 | 0 | 0 |  
  |WAVES/USDT| 1 | 2.95 | 2.95 | 0.59 | 2:35:00 | 1 | 0 | 0 |  
  | TOTAL    | 5 | 3.30 | 16.48| 3.30 | 4:03:00 | 5 | 0 | 0 |  
===========================
```

`freqtrade backtesting   --strategy-list  MACDStrategy hokes   --timerange=20200101- --ticker-interval 5m`
or
`freqtrade backtesting   --strategy hokes   --timerange=20200101- --ticker-interval 5m`
```
Result for strategy hokes 
====   BACKTESTING REPORT   
====
  | Pair | Buys | Avg Profit % | Cum Profit % | Tot Profit % | Avg Duration | Wins | Draws | Losses |   |   |   |  
  | ------------+--------+----------------+----------------+-------------------+----------
  | BTC/USDT | 42 | 0.04 | 1.63 | 0.33 | 1 day, 19:53:00 | 24 | 0 | 18 |   |   |   |  
  | ETH/USDT | 58 | 0.43 | 24.67| 4.93 | 1 day, 7:19:00 | 35 | 0 | 23 |   |   |   |  
  | XRP/USDT | 48 | 0.17 | 8.12 | 1.62 | 1 day, 14:07:00 | 28 | 0 | 20 |   |   |   |  
  | XLM/USDT | 55 | 0.29 | 16.20| 3.24 | 1 day, 8:48:00 | 31 | 0 | 24 |   |   |   |  
  |WAVES/USDT| 73 | 0.74 | 53.98| 10.80| 1 day, 0:17:00 | 42 | 0 | 31 |   |   |   |  
  | TOTAL   | 276 | 0.38 |104.61| 20.92 | 1 day, 8:51:00 | 160 | 0 | 116 |   |   |   |  
======================================================   SELL REASON STATS ======================================================= |  
  | Sell Reason | Sells | Wins | Draws | Avg Profit % | Cum Profit % | Tot Profit USDT | Tot Profit % |   |   |   |  
  | ---------------+---------+--------+---------+----------+----------------+-------------- 
  | roi | 155 | 155 | 0 | 5.95 | 922.85 | 923.774 | 184.57 |   |   |   |  
  | stop_loss | 116 | 0 | 0 | -7.19 | -833.55 | -834.388 | -166.71 |   |   |   |  
  | force_sell | 5  | 5 | 0 | 3.06 | 15.31 | 153.261 | 3.06 |   |   |   |  
==========================================================   LEFT OPEN TRADES REPORT   ==========================================================
  | Pair | Buys | Avg Profit % | Cum Profit % | Tot Profit % | Avg Duration | Wins | Draws | Losses |   |   |   |  
  | ------------+--------+----------------+----------------+-------------------+-------------  
  | BTC/USDT | 1 | 1.18 | 1.18 | 0.24 | 4:15:00 | 1 | 0 | 0 |   |   |   |  
  | ETH/USDT | 1 | 5.01 | 5.01 | 1.00 | 4:50:00 | 1 | 0 | 0 |   |   |   |  
  | XRP/USDT | 1 | 2.67 | 2.67 | 0.53 | 4:50:00 | 1 | 0 | 0 |   |   |   |  
  | XLM/USDT | 1 | 1.44 | 1.44 | 0.29 | 3:10:00 | 1 | 0 | 0 |   |   |   |  
  |WAVES/USDT| 1 | 5.01 | 5.01 | 1.00 | 5:00:00 | 1 | 0 | 0 |   |   |   |  
  |  TOTAL  | 5 | 3.06 | 15.31 | 3.06 | 4:25:00 | 5 | 0 | 0 |   |   |   |  
========================================================
 ```
### Observed Results:

  Although no conditions have changed, I found 4.94% and 20.92% results for the same strategy
What is the reason for this discrepancy?

**Comment by xmatthias** [comment]
The most likely reason - startup-period.

When backtesting a strategy list - the highest value of `startup_candle_count` is used. the used value is also shown in the startup logs of the strategy-list backtest.

Now assuming this moves the backtest period by a few hours - this will mean that it's a question of luck - if the first trade is a "sticky" one - which remains open for a long time - it can result in many other, short-term profitable trades to be missed / not acted on.
Because of this, it can also change the  pairs that are bought (same reason) - which can also result in different results (it's a similar effect than moving the starting point by a day ...)

**Comment by acemi1** [comment]
I noticed something. When you remove some strategies from the backtest list, the error gets better. For example, this strategy https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/Scalp.py

`freqtrade backtesting --strategy-list MACDStrategy hokes --timerange = 20200101- --ticker-interval 5m` hokes strategy = 20.92%

`freqtrade backtesting --strategy-list scalp hokes --timerange = 20200101- --ticker-interval 5m` hokes strategy = 4.94%

The time period is 5 minutes. How many candles can be inaccurate?

**Comment by xmatthias** [comment]
well - let me be honest - so far you're saying that the strategy `hokes` is inconsistent.

That's a strategy which is not in the strategy repository - so it might very well be a problem of the strategy.

There's many things which can cause this within a strategy.
Last time i checked (must've been around decemer), I did quite a few tests related to this, and for me, results stayed identical no matter if backtesting was run for one, or 20 strategies.

Now I'm not saying it's not possible this is happening - but unless you're able to verify this with a public strategy - it's not a bug in the bot to me, but a bug in the strategy.

**Comment by xmatthias** [comment]
Please try this with the code from #3134. this should fix this issue.

**Comment by acemi1** [comment]
I've tried. However, there has been no change.
Results are still inconsistent (as in screenshots)

**Comment by xmatthias** [comment]
how did you apply that branch ?

**Comment by acemi1** [comment]
I changed the related lines with the copy-paste method.

https://github.com/freqtrade/freqtrade/issues/3132#issuecomment-608082686 None of the strategies here are mine. If you ban the screenshot, the entire test is https://github.com/freqtrade/freqtrade-strategies/tree/master/user_data/strategies/berlinguyin strategies here

**Comment by xmatthias** [comment]
Using the latest ta-lib code (from master) does align results no matter the sequence.

best try for yourself with the udpated ta-lib installation.

Now a word of caution - there are several instances of `ta.STOCHF(dataframe, 5.0, 3.0, 0.0, 3.0, 0.0)` in the strategy repository - all of these need to be fixed to integers, otherwise errors (must be an integer) will happen.

I'll update the strategy repo sometime tomorrow with the fixed files - as it's incorrect to use floats for this anyway, no matter th ta-lib version.

**Comment by acemi1** [comment]
Thank you. I'll try it tomorrow.
Is this command enough for Ta-lib update?
cd freqtrade
go pull
pip install -r requirements.txt --user
pip install -r requirements-hyperopt.txt --user
pip install -r requirements-plot.txt --user

**Comment by xmatthias** [comment]
no, ta-lib did not release the update yet as of this point - so you'll need to clone the ta-lib repository, and install ta-lib from that repository.

something around the following should work in theory.

```
git clone https://github.com/mrjbq7/ta-lib.git
cd ta-lib
pip install . # (with activated virtual environment from freqtrade)
```

**Comment by acemi1** [comment]
I'm still getting inconsistent backtest results.
(After installing the Talib, I started getting the error below. I changed the decimal numbers to integers.)

 File "/root/freqtrade/user_data/strategies/Scalp.py", line 46, in populate_indicators
  stoch_fast = ta.STOCHF(dataframe, 5.0, 3.0, 0.0, 3.0, 0.0)
  File "talib/_abstract.pxi", line 396, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 277, in talib._ta_lib.Function.set_function_args
  File "talib/_abstract.pxi", line 454, in talib._ta_lib.Function.__check_opt_input_value
TypeError: Invalid parameter value for fastk_period (expected int, got float)

**Comment by acemi1** [comment]
https://github.com/freqtrade/freqtrade/issues/3132#issuecomment-608082686
As in the example in the link, when the order of strategies in --strategy-list changes, the profit / loss situation changes.

freqtrade   backtesting --strategy-list Astrategy Bstrategy Cstrategy --timerange=20200101-   --ticker-interval 4h

freqtrade   backtesting --strategy-list Cstrategy Bstrategy Astrategy --timerange=20200101-   --ticker-interval 4h

**Comment by xmatthias** [comment]
I've fixed that in this pr: https://github.com/freqtrade/freqtrade-strategies/pull/73

As mentioned above - with the updated ta-lib installation, this is not happening anymore on the testcase i've tried.
note: i did test it on top of #3134 - as that pr will still be needed to fix this completely.

**Comment by acemi1** [comment]
Please try this strategy?

`freqtrade backtesting --strategy-list emastrategy  BinHV27 CMCWinner EMASkipPump ADXMomentum AdxSmas ASDTSRockwellTrading AverageStrategy AwesomeMacd BbandRsi BinHV45 CCIStrategy ClucMay72018 CofiBitStrategy CombinedBinHAndCluc DoesNothingStrategy  Freqtrade_backtest_validation_freqtrade1 InformativeSample Low_BB MACDStrategy MACDStrategy_crossed Quickie ReinforcedQuickie ReinforcedSmoothScalp Scalp Simple SmoothScalp TechnicalExampleStrategy --timerange=20200101- --ticker-interval 4h`

emastrategy =15.17%

`freqtrade backtesting --strategy-list BinHV27 CMCWinner EMASkipPump ADXMomentum AdxSmas ASDTSRockwellTrading AverageStrategy AwesomeMacd BbandRsi BinHV45 CCIStrategy ClucMay72018 CofiBitStrategy CombinedBinHAndCluc DoesNothingStrategy  Freqtrade_backtest_validation_freqtrade1 InformativeSample Low_BB MACDStrategy MACDStrategy_crossed Quickie ReinforcedQuickie ReinforcedSmoothScalp Scalp Simple SmoothScalp TechnicalExampleStrategy emastrategy --timerange=20200101- --ticker-interval 4h`

emastrategy = 17.36%

`# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement

import talib.abstract as ta
from pandas import DataFrame

import freqtrade.vendor.qtpylib.indicators as qtpylib
#from freqtrade.indicator_helpers import fishers_inverse
from freqtrade.strategy.interface import IStrategy


class emastrategy(IStrategy):
    INTERFACE_VERSION = 2

    # Minimal ROI designed for the strategy
    minimal_roi = {
        

        "0":  0.2
    }

    # Optimal stoploss designed for the strategy
    stoploss = -0.5

 # Trailing stoploss
    trailing_stop = False
    trailing_stop_positive = 0.01
    trailing_stop_positive_offset = 0.2 
    trailing_only_offset_is_reached = True
    
    # Optimal ticker interval for the strategy
    ticker_interval = '5m'

    # Optional order type mapping
    order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'limit',
        'stoploss_on_exchange': False
    }

    # Optional time in force for orders
    order_time_in_force = {
        'buy': 'gtc',
        'sell': 'gtc',
    }

    def informative_pairs(self):

        return []

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        # EMA - Exponential Moving Average
        dataframe['ema10'] = ta.EMA(dataframe, timeperiod=10)
        dataframe['ema20'] = ta.EMA(dataframe, timeperiod=20)
        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (

                (qtpylib.crossed_above(dataframe['ema10'],dataframe['ema20'] ))&
                (dataframe['close'] > 0.00000130)
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['ema20'],dataframe['ema10'] ))#|
            ), 
            
            'sell'] = 1
        return dataframe
`

**Comment by xmatthias** [comment]
As said before - this test is pointless and wastes my time as it includes 20+ strategies.

The cause for this will be one, or maximum 2 strategies - and investing a bit of time to test this further would have shown you this.

The problem is (once again) ta-lib, which seems to cache things (reported here: https://github.com/mrjbq7/ta-lib/issues/306#issuecomment-610513723).

Nothing freqtrade can do - please try to test with sample cases which are as small as possible - having 20+ strategies will not help - as the reason is ONE single strategy (or multiple strategies causing the same problem - in this case).

**Comment by xmatthias** [comment]
Please update to the latest ta-lib master again - which fixes this problem (since sometime overnight ...).

Note: you'll need to pull the repository (`git pull`) - and then run `pip install .` within that repository to install the latest version.

**Comment by acemi1** [comment]
I think the problem continues.
https://github.com/freqtrade/freqtrade/issues/3132#issuecomment-610438765
Strategy codes are in this link.
My strategy is very plain. Very simple


`freqtrade backtesting --strategy-list CofiBitStrategy emastrategy --timerange=20200101- --ticker-interval 4h`

![cofiema](https://user-images.githubusercontent.com/39681665/78780949-14e15600-79a8-11ea-884c-be76d71c8f40.jpg)

`freqtrade backtesting --strategy-list emastrategy CofiBitStrategy --timerange=20200101- --ticker-interval 4h`

![emacofi](https://user-images.githubusercontent.com/39681665/78780990-262a6280-79a8-11ea-8a1e-6ba01b52c318.jpg)

**Comment by xmatthias** [comment]
Then you did not update ta-lib correctly - or have anohter problem in your environment.
Now i'm using a different timerange (all of 2019 as i don't have 4h 2020 data - but since i'm using more data, my results should deviate more - not less).

Also keep in mind to use the backtesting_memory branch.

Proof that these 2 strategies do work when using the latest ta-lib master branch (combined with backtesting_memory branch):

![2020-04-08-155536_1204x121_scrot](https://user-images.githubusercontent.com/5024695/78792473-70fca800-79b1-11ea-8311-4419310570f8.png)

![2020-04-08-155617_1202x110_scrot](https://user-images.githubusercontent.com/5024695/78792521-807bf100-79b1-11ea-9e0c-cd9e20989d3e.png)
