### ISSUE TITLE
Run backtesting encounters "SettingWithCopyWarning"

### ISSUE THREAD

**Issue by uncaughtgregory** [freqtrade/freqtrade#3147]
* Operating system: MacOS Mojave
  * Python Version: 3.7
  * CCXT version: 1.25.81 (`pip freeze | grep ccxt`)
  * Branch: Develop
  * Last Commit ID: 9387585756837a089647703cd88516c57ff0fb7c
  
## Step 3: Describe the problem:
When I ran backtesting, I encountered the following warnings:
```/home/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
```
Although the backtesting is able to finish the execution, the warning makes me concern the validity of its results, due to the uncertainty of the value setting.

Is my concern valid? If so, how to fix it?

### Steps to reproduce:
Backtest an arbitrary valid strategy

**Comment by xmatthias** [comment]
it's not really a problem - it's the way we usually assign things to a strategy.

```
# This can potentially raise this warning (in some circumstances, not always)
dataframe['sma'] = dataframe['close'].rolling(5).mean()

# the below should not raise this warning - but produces the same result
dataframe.loc[:, 'sma'] = dataframe['close'].rolling(5).mean()

```

Now to be fair, it's not just the strategy, but also freqtrade internals which do it the "wrong" way (it's not really wrong - just generating this warning) - but #3134 should correct these cases.

**Comment by uncaughtgregory** [comment]
@xmatthias Thank you for such a quick response! And thanks again for confirming this warning is not a real issue.
