### ISSUE TITLE
price filter logic and calculation

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#3170]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

Operating system: Ubuntu 18.04 LTS
Python Version: 3.7.3
CCXT version: ccxt==1.26.12
Branch: Develop
Last Commit ID: c8ccdbcb9a63aefe0a2ea1e1cbd4a7c075b4d5c6

 
 
## Step 3: Describe the problem:

price filter calculation seems not to be accurate

### Steps to reproduce:

Example: 

1) FT log
`2020-04-14 18:06:52,458 - PriceFilter - INFO - Removed BSVBEAR/USDT from whitelist, because 1 unit is 112.200%`

2) prices on FTX are quoted on this precision for BSVBEAR/USDT: 0,89950 

3) CCXT information
for BSVBEAR/USDT at FTX:
`'precision': {'amount': 0.1, 'price': 0.00025}`

4) how is 112% is being calculated?

  
### Observed Results:

if price of 0,89950 be increased by 1 unit (pip), which is 0.00025 = 0.89975  ->> 112%?

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
well - FTX is not a officially supported exchange for a reason - because there's a lot of things not yet tested.

They use a different method to define their precision ... which is causing this issue. 
It's fixed in #3169 however.

**Comment by Prossi79** [comment]
very good, so we are testing step by step the bot features on FTX :) 

hope to see FTX soon as officially supported exchange

**Comment by hroff-1902** [comment]
@Prossi79 the fix merged into develop, pls verify

**Comment by Prossi79** [comment]
@hroff-1902  ok, seems to work! thank you!

**Comment by hroff-1902** [comment]
thanks to @xmatthias
