### ISSUE TITLE
SpreadFilter calculation sometimes wrong

### ISSUE THREAD

**Issue by tarek-vader** [freqtrade/freqtrade#3174]
* Operating system:  ubuntu18
  * Python Version: python 3.6.9
  * CCXT version: ccxt==1.24.97
  * Branch: Develop
  * Last Commit ID: 030c487d6b53fb2a4f52046b06be724fae253f45
  
## Step 3: Describe the problem:

the calculation provided by the log for the spreadfilter doesnt match with the real calculation.
2020-04-14 20:21:20,238 - SpreadFilter - INFO - Removed KEY/USDT from whitelist, because spread **0.666%** >0.5%
and the log line is comming repeatedly in comparision with other SpreadFilter  log lines...

while the order book has following
ask side:
0.000596
--------
bid side:
0.000601

calculation:  1-(0.000596/0.000601) = 0.00831
this problem is not reproducible immediately with every pair!!
it could be a logging problem or very old value..

to reproduce:

dry run with binance 
with this config of pairlist:
    "pairlists": [
        {
		"method": "VolumePairList",
		"number_assets": 95,
		"sort_key": "quoteVolume",
		"refresh_period": 600
	},
	{"method": "PrecisionFilter"},
	{"method": "PriceFilter", "low_price_ratio": 0.01},
	{"method": "SpreadFilter", "max_spread_ratio": 0.005},
    ]

**Comment by xmatthias** [comment]
i don't think this is an issue to be honest.

Keep in mind that the orderbook is constantly moving, so the spread can be 0.5% now, and 0.6% two 2 minutes ago (and 0.4% now - as you've read another 10 words).

For the purpose of pairlist filtering, we're not pulling the latest orderbook value constantly with every iteration (that would probably get the bot blocked soonish), but cache the spread value for a certain amount of time.

The purpose of the spreadfilter (of all filters...) is to filter out generally dangerous pairs - but it's enough to do that once every few hours - there's no point to do this "to the minute" - while spread does change - it usually doesn't change very heavily (from 1% to 0.01% ...)

If the spread is 0.5% now - and 0.49% in a minute - why would one be better than the other - it's just passing your threshold - but the change itself is not that substancial.


In your example, the difference is 0.666% and 0.831% ... which is kindof in the same ballpark - and if you watch that pair - i'm pretty certain that you'll notice that the orderbook is changing - and both values can apppear within the same minute ... or even more often.

**Comment by tarek-vader** [comment]
ok thanks for clarification..
