### ISSUE TITLE
Issue selling FTX futures

### ISSUE THREAD

**Issue by hclivess** [freqtrade/freqtrade#3177]
##  Step 2: Describe your environment

  * Operating system: Ubuntu 18.04.3 LTS
  * Python Version: Python 3.7.5
  * CCXT version: 1.26.12
  * Branch: Master | Develop
  * Last Commit ID: 4d80f52db41c4f731cfe9d75711314f5cf9f6d0b
  
## Step 3: Describe the problem:

The bot is unable to close trades on futures which it opens on the FTX exchange, because it does not recognize there is balance in the account. The balance is not handled as token balance, but you can still "sell + reduce only" to sell your outstanding position

### Steps to reproduce:

  1. Try to trade any of the "PERP" future contracts on FTX
  2. Bot will complain with the following:

```
2020-04-16 21:13:08,204 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Not enough amount to sell. Trade-amount: 0.26, Wallet: 0
2020-04-16 21:13:18,598 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=74, pair=EOSBEAR/USD, amount=0.07000000, open_rate=12.53000000, open_since=2020-04-16 16:40:50)
2020-04-16 21:13:21,891 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=85, pair=OKBBEAR/USD, amount=0.06844627, open_rate=14.61000000, open_since=2020-04-16 19:04:42)
2020-04-16 21:13:23,298 - freqtrade.freqtradebot - INFO - Executing Sell for HT-PERP. Reason: SellType.SELL_SIGNAL

```
```
Unsupported pairs examples:

	"ADA-PERP",
	"ALT-PERP",
	"BCH-PERP",
	"BNB-PERP",
	"BSV-PERP",
	"EOS-PERP",
	"ETC-PERP",
	"ETH-PERP",
	"EXCH-PERP",
	"HT-PERP",
	"LINK-PERP",
	"LTC-PERP",
	"MID-PERP",
	"OKB-PERP",
	"PAXG-PERP",
	"PRIV-PERP",
	"SHIT-PERP",
	"TOMO-PERP",
	"XRP-PERP",
	"XTZ-PERP",
	"DRGN-PERP",
	"MATIC-PERP",
```

**Comment by xmatthias** [comment]
well i assume you're currently owning such a pair.
in which case, please run the following for me:


```python
import ccxt
ct = ccxt.ftx({'apiKey': '<key>', 'secret': '<secret>'}
_ = ct.load_markets()
res= ct.fetch_balance()
print(res)
```

Please insert your key / secret into the above code snippet before running this.

We'll need the output of this.
Make sure to 
a) remove eventual secret information (like your key / secret). It'll not be in the output itself - but just to make sure
b) lower balances you're not comfortable sharing with "the public".

If the 2nd is a general concern, feel free to send the result in private via slack.

**Comment by hclivess** [comment]
Hi, none of the PERP markets is listed there. So I assume I have to open an issue with them. Also this is the way to pull a subaccount:

`ct = ccxt.ftx({'apiKey': 'key', 'secret': 'secret',"headers": {"FTX-SUBACCOUNT": "subaccount_name"}})`

**Comment by xmatthias** [comment]
Well the docs only list one balance option https://docs.ftx.com/#get-balances ... (Or one for all subaccounts) 

Does the info key also not contain what you own?
 In that case it would be a ccxt issue ...

**Comment by hclivess** [comment]
Tokens work, even show 0 balances for tokens I don't have. Perpetual futures are not present on the wallet at all. I think they'll add support at cctx, it's quite a popular exchange. Thanks. I think we can close this.

**Comment by xmatthias** [comment]
well - i'm not certain it's a ccxt issue - since looking at the ftx docs, there doesn't seem to be a method to get "futures balance" - but feel free to open an issue regarding this against ccxt - they can tell you best if it's an issue from the exchange ... (most likely is).


either way - since ccxt isn't returning it (not in /balance, not via another method afaik) - there is nothing freqtrade can do at this point.

**Comment by gring0-cripto** [comment]
@OP, you managed to solve this ?
