### ISSUE TITLE
Kraken Error

### ISSUE THREAD

**Issue by kimasplund** [freqtrade/freqtrade#3186]
Seems im not the only one experiencing this. 
Not sure from what it comes. Running docker. exchange Kraken.
```
2020-04-18 11:36:04,993 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
 File "/freqtrade/freqtrade/main.py", line 36, in main
  return_code = args['func'](args)
 File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
  worker = Worker(args)
 File "/freqtrade/freqtrade/worker.py", line 34, in __init__
  self._init(False)
 File "/freqtrade/freqtrade/worker.py", line 53, in _init
  self.freqtrade = FreqtradeBot(self._config)
 File "/freqtrade/freqtrade/freqtradebot.py", line 63, in __init__
  self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
 File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 37, in load_exchange
  exchange = Exchange(config, validate=validate)
 File "/freqtrade/freqtrade/exchange/exchange.py", line 122, in __init__
  self.validate_stakecurrency(config['stake_currency'])
 File "/freqtrade/freqtrade/exchange/exchange.py", line 296, in validate_stakecurrency
  quote_currencies = self.get_quote_currencies()
 File "/freqtrade/freqtrade/exchange/exchange.py", line 227, in get_quote_currencies
  return sorted(set([x['quote'] for _, x in markets.items()]))
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by xmatthias** [comment]
Please fill out the issue template, otherwise we're not able to help you as your version is unknown.

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)

**Comment by hroff-1902** [comment]
also pls give us some more logs above this traceback

**Comment by xmatthias** [comment]
well the error happens (probably) if markets fail to initialize - so if you "outwait" the capta errors - you may eventually end up with something like this...

However - ccxt has been updated on develop, and i just tested - kraken startup works perfectly fine.

**Comment by hroff-1902** [comment]
yeah, read on Slack -- this should gone with updating ccxt to the latest one

**Comment by kimasplund** [comment]
it was on a fresh build on docker image and updated ccxt.
Il see if i happends again.

**Comment by kimasplund** [comment]
running on Ubuntu 20.04

**Comment by xmatthias** [comment]
If it happens again - please make sure to post all logs from the startup (i assume this happens within 1-2 minutes of starting the bot ...).

**Comment by xmatthias** [comment]
i'll close this for now - feel free to comment if it happens again (but i think the ccxt update should've fixed this).

**Comment by pnmartinez** [comment]
Hello!

Having the same problem with my instance, **using ccxt==1.29.52**. 

Since it has been a while since this issue was closed, I assume this ccxt version should be ok. Can anyone confirm **what ccxt version should prevent this error?**

Cheers.

**Comment by xmatthias** [comment]
@pnmartinez considering the newest version is  1.33.23 - i guess anything newer than your version will do - but in general, the latest ccxt version is usually the best to use, as it'll have the latest changes exchanges implemented.

Hope this makes sense

**Comment by pnmartinez** [comment]
Should the `requirements`be updated? If I have that outdated ccxt version, it is because of it being the default installation for Freqtrade.

**Comment by xmatthias** [comment]
@pnmartinez freqtrade's requirements are updated once a week automatically, and once a month for the release version.

Your version was from June - so you're most likely running an outdated version of freqtrade.
