### ISSUE TITLE
How do I optimise RSI between a range (10-80) that I also have 2 moving averages based on?

### ISSUE THREAD

**Issue by dimadude101** [freqtrade/freqtrade#3187]
Just to be clear, I have a moving average crossover strategy that buy's on a cross above and sells on a cross below of two moving averages. The moving averages are based on the RSI (instead of the traditional closing price).
My question is in Hyperopt how do I optimise the best value (default 14) of the RSI itself that the moving averages depend on?

**Comment by xmatthias** [comment]
You'll find an example for this in the [strategy](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/hyperopts/AverageHyperopt.py) repository as `AverageHyperopt`.

You'll need to modify it a bit as it's optimizing the "real" averages - not RSI values - but the concept will remain the same.

**Comment by dimadude101** [comment]
Thanks that's exactly what I have been trying to do for 3 days and still no luck please could you help more I'm about to go crazy? Please

**Comment by xmatthias** [comment]
I'm sorry, but we'll not write your strategy-idea for you.

If you have specific problems with the implementation, please post the code you got so far and we can point you in the right direction - but you will not get a "this is how" solution.

Thanks for your understanding.

**Comment by acemi1** [comment]
https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/hyperopts/MACDStrategy_hyperopt.py

This file is simpler. It may be easier to adapt this by taking the example.

**Comment by xmatthias** [comment]
I'll close this as i hope we were able to point you in the right direction.

Feel free to join our [freqtrade slack channel](https://highfrequencybot.slack.com/join/shared_invite/enQtNjU5ODcwNjI1MDU3LTU1MTgxMjkzNmYxNWE1MDEzYzQ3YmU4N2MwZjUyNjJjODRkMDVkNjg4YTAyZGYzYzlhOTZiMTE4ZjQ4YzM0OGE) for more help (we've got a great community which can help with questions).
