### ISSUE TITLE
Coinbase Pro XRP/USDT (BadSymbol)

### ISSUE THREAD

**Issue by nspotrepka** [freqtrade/freqtrade#3190]
## Step 1: Have you search for this issue before posting it?

Yes, I have searched for `usdt`, `whitelist`, and `staticpairlist`.

## Step 2: Describe your environment

  * Operating system: macOS Catalina 10.15.3
  * Python Version: 3.7.4
  * CCXT version: 1.26.32
  * Branch: Both master and develop
  * Last Commit ID: e3e38ba68f7d0981d504d52d3c01f0dde9d44516 (develop)

## Step 3: Describe the problem:

`XRP/USDT` is also showing up in my whitelist pairs when doing a dry run on Coinbase Pro.

### Steps to reproduce:

  1. Create a new config for coinbasepro with USD as stake currency.
  2. Put all 17 /USD pairs into whitelist pairs. This includes `XRP/USD`.
  3. Leave method as StaticPairList.
  4. Trade with dry_run = true.
  
### Observed Results:

I am getting several log messages relating to `XRP/USDT` not being a valid pair.

Despite not having added it in my config file, `XRP/USDT` is also showing up in my whitelist pairs on Telegram, along with the 17 /USD pairs, for a total of 18 pairs.

I would not expect `XRP/USDT` to be in my whitelist pairs. `XRP/USDT` is not a valid pair on Coinbase Pro. Coinbase Pro does not have USDT pairs.

### Relevant code exceptions or logs:

```
2020-04-19 00:10:04,381 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair XRP/USDT due to BadSymbol. Message: coinbasepro does not have market symbol XRP/USDT"
```

```
2020-04-19 00:10:19,725 - freqtrade.exchange.common - WARNING - fetch_ticker() returned exception: "Pair XRP/USDT not available"
```

```
2020-04-19 00:20:58,727 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Pair XRP/USDT not available
```

**Comment by xmatthias** [comment]
I suspect you've used a different exchange in the past - and didn't clense the database - so now you got an open (dry run) order in your database (open trades are ALWAYS added to your whitelist).


You have several options on how to deal with this 
- delete / rename the existing database file (the name should be shown in the logs right at the start - and is most likely `tradesv3.dryrun.sqlite`.
- Use a different database for each bot (this is what i'd reccomend).
  You can easily do this by either appending `--db-url sqlite:///coinbaseprotest.sqlite` to your command - or by adding `"db_url": "sqlite:///coinbaseprotest.sqlite"` to your configuration.


If you're using multiple exchanges, i'd go for th 2nd option, as it allows you to "forget" about this.

**Comment by nspotrepka** [comment]
Ah, this makes sense. Good to know I can delete the existing database file if anything goes awry!

**Comment by xmatthias** [comment]
Only while the bot is not running please - otherwise it may cause unexpected behaviour.

Also, i wouldn't delete a productive / live database (and if you do, make sure no open trade is present), but only dry-run databases.
