### ISSUE TITLE
Question : How to use or test multiple bots (good practices)

### ISSUE THREAD

**Issue by magkia** [freqtrade/freqtrade#3191]
Hello,

I would like to test two or three strategy at same time in dry mode but i would like to know if there's some good practices and if some body would like to share it?...

I already know how to do it in local but, i don't know how to run more than one bot on VPS. Could anybody explain it to me please? :)

Also, how can I control more than one bot with telegram to follow the develop ? or How should it be done?

Any good practice is welcome 

Thanks in advance :pray:

**Comment by xmatthias** [comment]
well, there is no real difference between running the bot locally and on a VPS (other than the need to SSH into the VPS first).

what you'll need:
* one config per bot
* one telegram bot per freqtrade bot (token inserted into the config above).

You can start all bots from the same directory if you wish - but you'll need to specify the database file explicitly - as the database cannot be shared - doing so will lead to problems (with both bots).


From there on, you can either use docker and start multiple containers (supplying the corresponding config and strategy, and using a different database file) - docker compose (by adding a 2nd service to the compose file or using 2 directoreis) - or simply start it in multiple tmux (or screen) windows.

Now the simplest way without much docker-experience will probably be to use docker-compose - and use 2 different directories to enable seperation. You'll then just need to cd into the correct directory to control each bot.

Hope this helps

**Comment by magkia** [comment]
ok thanks!
