### ISSUE TITLE
any way to implement a Trailing Stop Buy?

### ISSUE THREAD

**Issue by gwopr** [freqtrade/freqtrade#3198]
Hello,
this is a question regarding the global capabilities of this excellent piece of software.
I have searched around freqtrade options and config tags, but, strangely, I can't find a way to implement a trailing stop buy. That is, a way to trail the buy order as the price goes down, having set up a max offset in case, instead, the price raises.
As far as I know, once the bot decides to buy, the price gets "fixed" in the order book. This way, if the price keep on going down, it would mean a bad trade. Any solution?

**Comment by xmatthias** [comment]
no, sorry.

in the end, it's the exercise of the strategy to determine the correct entrypoint. 
If this is a requirement for the strategy to work, then most likely the entrypoint was selected badly / too early. You might be able to overcome this by shifting the buy-signal by a candle or two - but in the end, that could mean you miss other entries.

I'm also not certain that would protect you - in most longer downtrends, you often have a slight recovery / bounceback - right before it falls again - so at the worst, it'll fill your trailing buy at the peak of that - and dump right after that - so the potential to protect you in this case must be seen as very low.

**Comment by gwopr** [comment]
that you for the prompt reply. I could set this feature up by using in the strategy a proper variable that gets its starting value once the BUY trigger is raised, and the same variable is resetted once the BUY order is submitted.
Question is: in order to manage this variable, which strategy class attribute can I use to get the information that the BUY trigger is raised and, then, that the BUY order is submitted?

**Comment by hroff-1902** [comment]
> Question is: in order to manage this variable, which strategy class attribute can I use to get the information that the BUY trigger is raised and, then, that the BUY order is submitted?

If I understand it correctly -- you'll get the notification in the telegram channel when the buy order is submitted (following the buy signal).

There is no notification for a buy signal which is not followed by submission of the buy order, but you can try to parse the logs for this info.

@xmatthias should not we add an ability to send those notifications for buy/sell signals even if they do not cause buy/sell orders? It's possible technically, but I'm not sure this will be useful in practice, plus this can be noisy...

**Comment by xmatthias** [comment]
i don't think that'll be useful - most configs i've seen limit `max_open_trades` to something rather small (3, 5) - so chances to see trade signals while no slot is open are pretty high - and sending a notification for this would be spamming.

Nothing against a callback on when the order is filled - but as pointed out before somewhere - all future strategy callbacks are currently kinda "blocked" by #2872. 

With the setup code from there in place, adding an empty callback is probably more work to document than to implement ...

**Comment by acemi1** [comment]
If I understood correctly, what you want to do is very logical.
I was trying to do that too. But my python coding knowledge is not enough.
Tradingview has many similar ones.

https://tr.tradingview.com/script/gnAsoRii/

https://tr.tradingview.com/script/sLXhpDO8/

**Comment by gwopr** [comment]
@acemi1 thanks for your interest, you, too, got the sense of my proposal.
the code and logic to implement trialing buy would be quite simple. here is what I was thinking.

```
# INITIALISE GLOBAL VARIABLES
trailing_buy_offset = (e.g.) 0.02
trailing_buy_order_enabled = (e.g.) True
trailing_buy_order_started = False
trailing_buy_order_uplimit = trailing_buy_order_uplimit = null
----------------
# GLOBAL VARIABLES SET ELSEWHERE
new_buy_trigger = (set by the trigger routine)
----------------
# TRAILING BUY ROUTINE BODY
if new_buy_trigger and traling_buy_order_enabled: # if BUY trigger has just been raised and trailing buy is enabled

	if trailing_buy_order_started:

		if current_price < trailing_buy_order_downlimit: # if price is still falling down
			trailing_buy_order_uplimit = current_price * (1 + trailing_buy_offset) # update uplimit
			trailing_buy_order_downlimit = current_price # update downlimit
			confirm_buy_order = False # keep on trailing

		if current_price > trailing_buy_order_downlimit and current_price < trailing_buy_order_uplimit: # if price is between limits
			trailing_buy_order_downlimit = current_price # update only downlimit
			confirm_buy_order = False # keep on trailing

		if current_price > trailing_buy_order_uplimit: # if price has bounces back and now is over uplimit
			confirm_buy_order = True # finished trailing - buy order must be submitted immediately

	if !trailing_buy_order_started and traling_buy_order_enabled:

		trailing_buy_order_started = True
		trailing_buy_order_uplimit = buy_trigger_price * (1 + trailing_buy_offset) # initialize uplimit
		trailing_buy_order_downlimit = buy_trigger_price # initialize down limit
		confirm_buy_order = False # keep on trailing

	return(confirm_buy_order) # exit code: keep on trailing (False) or proceed and submit BUY order (True)

else:
	return(True) # exit code: no trailing: proceed and submit BUY order
```
The info I am missing are:
1. how to get new_buy_trigger, e.g. as a method / attribute of structures / classes already embedded in freqtrade
2. how to run this routine on every period (candle)
3. how to submit BUY orders only once confirm_buy order is True

Any help from @xmatthias and others is much appreciated, as the solution is shared in this wonderful community.

**Comment by hroff-1902** [comment]
> If I understood correctly, what you want to do is very logical.
> I was trying to do that too. But my python coding knowledge is not enough.
> Tradingview has many similar ones.
> We will use trailingbuy using trailingstop logic.
> 
> https://tr.tradingview.com/script/gnAsoRii/
> 
> https://tr.tradingview.com/script/sLXhpDO8/

I see from these links that trailing stop logic as you describe it -- is just a yet another indicator, which can be transpiled from tradingview pine code into python and used in the strategy as the base for the buy signal. This does not require any changes into the freqtrade logic.

Am I wrong here?

**Comment by gwopr** [comment]
Well @hroff-1902 , is not that simple. In freqtrade, an indicator is something that looks at the dataframe, does the math with its rows, and builds up a new column filled up with the results.
On the contrary, trailing stop buy is something that runs just after the strategy, basing on indicators, highlights a (potential) buy signal. So, instead of submitting immediately a buy order, trailing waits if the trend keeps on, hoping to place a better trade. In essence, trailing buy is a routine that runs AFTER the strategy, and not simply another indicator. As @xmatthias said, it must be placed into the strategy. And that is the reason why I need to get the buy trigger and the submit order trigger.
But IMHO, trailing buy should be embedded in the code, exactly as trailing sell.
Hope my explanation is clear.

**Comment by xmatthias** [comment]
no, @hroff-1902 is right - this can be done in the strategy pretty easily.

The strategy get's called every iteration by default (~every 5s).
You build your buy-signal the way you want but don't assign it to `'buy'` - but to `'buy_maybe'` - then check if the last row is a "buy_maybe" - and if it is, you use the dataprovider to get the latest price, compare if it moves the way you want - and then decide to assign 'buy' or not to the last row.

It'll not work during backtesting - but no "trailing stop buy" method would - simply because we lack information of intra-candle information during backtesting.
"Trailing stoploss" is already imprecise as it uses candle high / low to "guess" what happens intracandle - adding another "guessing" mechanism for buying will make backtesting even less precise.

**Comment by gwopr** [comment]
OK thanks @xmatthias 
I could try and evaluate if trailing stop buy is really convenient (sometimes it is not, simply because the offset is more than the gain of the trailing itself). to do this, I would use the whole dataframe available to the strategy, implementing a loop that scans the candles just after each buy trigger...

**Comment by hroff-1902** [comment]
which is shown by the links to tradingview above -- looks simply a yet another indicator.
or you are talking of different things.
I still not quite understand what 'trailing stop buy' is.

**Comment by gwopr** [comment]
> no, @hroff-1902 is right - this can be done in the strategy pretty easily.
> 
> The strategy get's called every iteration by default (~every 5s).
> You build your buy-signal the way you want but don't assign it to `'buy'` - but to `'buy_maybe'` - then check if the last row is a "buy_maybe" - and if it is, you use the dataprovider to get the latest price, compare if it moves the way you want - and then decide to assign 'buy' or not to the last row.
> 
> It'll not work during backtesting - but no "trailing stop buy" method would - simply because we lack information of intra-candle information during backtesting.
> "Trailing stoploss" is already imprecise as it uses candle high / low to "guess" what happens intracandle - adding another "guessing" mechanism for buying will make backtesting even less precise.

can I get a few examples / references of how the dataprovider is build and works? e.g. a demo strategy that uses the data provider, or the pandas reference...

**Comment by gwopr** [comment]
> which is shown by the links to tradingview above -- looks simply as a yet another indicator.
> or you are talking of different things.
> I still not quite understand what proposed 'trailing stop buy' is.

I confirm, the logic of trialing stop buy is very simple. how to implement it in freqtrade is (to me) not so simple...

**Comment by xmatthias** [comment]
> can I get a few examples / references of how the dataprovider is build and works? e.g. a demo strategy that uses the data provider, or the pandas reference...

How about reading the [documentation](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-dataprovider). It includes samples on how to use the dataprovider.

> I confirm, the logic of trialing stop buy is very simple. how to implement it in freqtrade is (to me) not so simple...

Well yes, it's pretty clear that you think it's easy, but would like us to implement it ... 

> to do this at backtesting level, I would use the whole dataframe available to the strategy, implementing a loop that scans the candles just after each buy trigger...

You can't do it at backtesting level and that's the point.
during backtesting, you do not know what happens intra-candle (is high before low / low before high, ... or something else switching between high and low multiple times) - so you cannot backtest this method.

**Comment by hroff-1902** [comment]
> I confirm, the logic of trialing stop buy is very simple.

Do not think so, I still do not understand/did not get it. 😉

**Comment by acemi1** [comment]
https://github.com/freqtrade/technical/issues/89

I may not have understood you correctly. If I understood correctly, the codes after the # Set the Supertrend value statement in the code above can be useful. If the price falls, it follows the price downwards (such as Trailing stop)
If the price goes up, it doesn't go up. If it rises as much as the percentage you want, you buy.

https://tr.tradingview.com/script/r6dap7yi/
SuperTrend indicator has both trailing stop and trailing buy feature.

**Comment by gathad** [comment]
Okay, you can implement it to data frame as "trailingBuy".

lets say you have %2 space with the price and trailing buy. 
``
trailingBuy=currentPrice*1.02
if trailingBuy < dataframe["trailingBuy"][-1]:
   dataframe["trailingBuy"]=trailingBuy
else:
   dataframe["trailingBuy"]=dataframe["trailingBuy"][-1]
``
I think this will work. Maybe not [-1] part, maybe you need to use [-2]. And you can send a buy order if current price goes higher than dataframe["trailingBuy"].

**Comment by hroff-1902** [comment]
I still do not understand which is discussed here.
The pine code at tradingview referred above -- looks like yet another simple indicator (based strictly on ohlcv candles), you may implement it in your strategy, no changes to Freqtrade intrinsics is needed.

If it's about something similar to trailing stop loss (moving constantly somehow, based on current ticker data, for example), pls describe (someone, who understand it in detail) the proposed algorithm, I, repeating, still not understand what "Trailing Stop Buy" can be.

**Comment by gathad** [comment]
Hello hroff,

Implementing it to the freqtrade is not necessary, also meaningless because of too much confusion on configurations. 

I just wanted to explain a way to do that from strategy.py file for the question owner. There is no need to discuss it.

**Comment by xmatthias** [comment]
Sounds like this quesiton was answered, and trailing stop can be done in the strategy.

Going to close this. feel free to comment below / reopen if this issue is still unclear.

**Comment by jacquesbuys** [comment]
> @acemi1 thanks for your interest, you, too, got the sense of my proposal.
> the code and logic to implement trialing buy would be quite simple. here is what I was thinking.
> 
> ```
> # INITIALISE GLOBAL VARIABLES
> trailing_buy_offset = (e.g.) 0.02
> trailing_buy_order_enabled = (e.g.) True
> trailing_buy_order_started = False
> trailing_buy_order_uplimit = trailing_buy_order_uplimit = null
> ----------------
> # GLOBAL VARIABLES SET ELSEWHERE
> new_buy_trigger = (set by the trigger routine)
> ----------------
> # TRAILING BUY ROUTINE BODY
> if new_buy_trigger and traling_buy_order_enabled: # if BUY trigger has just been raised and trailing buy is enabled
> 
> 	if trailing_buy_order_started:
> 
> 		if current_price < trailing_buy_order_downlimit: # if price is still falling down
> 			trailing_buy_order_uplimit = current_price * (1 + trailing_buy_offset) # update uplimit
> 			trailing_buy_order_downlimit = current_price # update downlimit
> 			confirm_buy_order = False # keep on trailing
> 
> 		if current_price > trailing_buy_order_downlimit and current_price < trailing_buy_order_uplimit: # if price is between limits
> 			trailing_buy_order_downlimit = current_price # update only downlimit
> 			confirm_buy_order = False # keep on trailing
> 
> 		if current_price > trailing_buy_order_uplimit: # if price has bounces back and now is over uplimit
> 			confirm_buy_order = True # finished trailing - buy order must be submitted immediately
> 
> 	if !trailing_buy_order_started and traling_buy_order_enabled:
> 
> 		trailing_buy_order_started = True
> 		trailing_buy_order_uplimit = buy_trigger_price * (1 + trailing_buy_offset) # initialize uplimit
> 		trailing_buy_order_downlimit = buy_trigger_price # initialize down limit
> 		confirm_buy_order = False # keep on trailing
> 
> 	return(confirm_buy_order) # exit code: keep on trailing (False) or proceed and submit BUY order (True)
> 
> else:
> 	return(True) # exit code: no trailing: proceed and submit BUY order
> ```
> 
> The info I am missing are:
> 
> 1. how to get new_buy_trigger, e.g. as a method / attribute of structures / classes already embedded in freqtrade
> 2. how to run this routine on every period (candle)
> 3. how to submit BUY orders only once confirm_buy order is True
> 
> Any help from @xmatthias and others is much appreciated, as the solution is shared in this wonderful community.

I modified this code slightly to try and get it to work with backtesting

```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
    # TRAILING BUY
    current_price=dataframe['close'].tail(1)
    dataframe['trailbuy'] = 0 # keep on trailing
    trailing_buy_offset = 0.005
    trailing_buy_order_enabled = True
    trailing_buy_order_started = False
    if trailing_buy_order_started:
        if current_price < trailing_buy_order_downlimit: # if price is still falling down
            trailing_buy_order_uplimit = current_price * (1 + trailing_buy_offset) # update uplimit
            trailing_buy_order_downlimit = current_price # update downlimit
            dataframe['trailbuy'] = 0 # keep on trailing 

        if current_price >= trailing_buy_order_uplimit: # if price has bounced back and now is over uplimit
            dataframe['trailbuy'] = 1 # finished trailing - buy order must be submitted immediately
            trailing_buy_order_started = False
    
    if trailing_buy_order_started == False and trailing_buy_order_enabled == True:
        trailing_buy_order_started = True
        trailing_buy_order_uplimit = current_price * (1 + trailing_buy_offset) # initialize uplimit
        trailing_buy_order_downlimit = current_price # initialize down limit
        

    return dataframe
```
It uses the 'close' values of each candle as the current price. The backtesting results shows that it doesn't place any 'buy' orders. I ran the code again in a 'for' loop going through each candle at a step and that shows that the logic seems to work. Not sure if I am placing the variables at the right place.
(`dataframe['trailbuy']>0  #populate buy trend`)

**Comment by xmatthias** [comment]
please use tripple-ticks (```) to format multi-line code properly.

`dataframe['close'].tail(1)` looks at the absolute last row (identical behaviour to `dataframe.iloc[-1]`).
This is therfore not backtesting compatible - as mentioned in the docs.

**Comment by jacquesbuys** [comment]
> please use tripple-ticks (```) to format multi-line code properly.
> 
> `dataframe['close'].tail(1)` looks at the absolute last row (identical behaviour to `dataframe.iloc[-1]`).
> This is therfore not backtesting compatible - as mentioned in the docs.

Thanks for the prompt reply. Still doesn't seem to do any 'buy' in backtesting when using just `dataframe['close']` or `dataframe['close'].shift(1)`
