### ISSUE TITLE
SQL Help Fixing manual trade

### ISSUE THREAD

**Issue by Wackietim** [freqtrade/freqtrade#3201]
Good evening everyone,

Unfortunately I have a question about the SQL commands. I really did my best to solve it myself but without any luck, so sorry for asking this here.
It probably was not a smart move at all to manually sell a trade without looking at the consequences.
However I found the instructions on the Freqtrade.io website on how to fix this. The code looks like this:

UPDATE trades
SET is_open=0, close_date=<close_date>, close_rate=<close_rate>, close_profit=close_rate/open_rate-1, sell_reason=<sell_reason>  
WHERE id=<trade_ID_to_update>;

I found the database file and succeed in changing the code, in my case it looked like this

UPDATE trades
SET is_open=0, close_date='2020-04-21 09:08:45.103418', close_rate=0.00007881, close_profit=(close_rate/0.00007810)-1, sell_reason='force_sell'
WHERE id= 2;

It worked, so it changed the trade to close, so in a way it helped. But after this change, every time I ask my /daily or /profit through the Telegram commands I get an error.

Traceback (most recent call last):
  File "-/freqtrade/freqtrade/rpc/telegram.py", line 52, in wrapper
    return command_handler(self, *args, **kwargs)
  File "-freqtrade/freqtrade/rpc/telegram.py", line 277, in _daily
    fiat_disp_cur
  File "-freqtrade/freqtrade/rpc/rpc.py", line 200, in _rpc_daily_profit
    curdayprofit = sum(trade.close_profit_abs for trade in trades)

I assume this error is linked to the change I made in the trade with Id=2. I looked at the structure of all the trades with the SQL command: SELECT * FROM trades. When I look at these trades, I see there is a difference in how they are set up, the trade with Id=2 is missing some values? But I could not figure out how I could solve this. 

1|binance|WRX/BTC|0|0.001|
0.001|1.889e-05|1.889e-05|0.01000280281
|1.914e-05|1.914e-05|0.01121007|0.00011213|0.01|529.0|
2020-04-20 21:15:30.196628|2020-04-21 07:35:10.079251||1.3510128e-05|-0.2848|
1.3510128e-05|-0.2848||2020-04-20 21:16:01.760309|1.938e-05|1.842e-05|sell_signal|Stratgyx|60

2|binance|SOL/BTC|0|0.001|
0.001|7.81e-05|7.809e-05|0.0100067968
|7.881e-05||7.09999999999998e-07||0.01|128.0|2020-04-20 21:15:33.896451|2020-04-21 09:08:45.103418||5.585712e-05|-0.2848|5.585712e-05|-0.2848||2020-04-20 21:15:56.930609|7.983e-05|7.55e-05|force_sell|Strategyx|60

I think the second trade causes the problem, all the other trades, just like the first trade have more values. I was planning on deleting the whole trade, but was to scared to f"ck it up even harder than I already did.

I really hope someone knows how this works. Excuse me for this probably easy to solve problem.

Thank you in advance!

**Comment by xmatthias** [comment]
well deleting the trade is always an option - but then you lack the profit / loss of that trade.

Not all columns are needed - but close_profit_abs is.

what might work (the  output above is difficult to read / makes it hard to determine which column is missing precisely (other than close_profit_abs).

```
update trade
set close_profit_abs = (amount * close_rate * (1 - fee_close) - (amount * open_rate * 1 - fee_open)
where id = '2';
```
