### ISSUE TITLE
Binance - Crash caused by "Unknown order sent"

### ISSUE THREAD

**Issue by hclivess** [freqtrade/freqtrade#3208]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Operating system: 18.04.3 LTS (Bionic Beaver)
  * Python Version: Python 3.7.5
  * CCXT version: 1.26.45
  * Branch: Master | Develop
  * Last Commit ID: 4d80f52db41c4f731cfe9d75711314f5cf9f6d0b
  
## Step 3: Describe the problem:

Bot crashes on Binance with the following error: 

`freqtrade - ERROR - Could not cancel order. Message: binance {"code":-2011,"msg":"Unknown order sent."}`

### Steps to reproduce:

Set the following config:
```
    "unfilledtimeout": {
        "buy": 1,
        "sell": 1
    },
```

### Relevant code exceptions or logs:

  ```
2020-04-24 19:25:05,897 - freqtrade.worker - INFO - Bot heartbeat. PID=7613, version='develop-4d80f52d', state='RUNNING'
2020-04-24 19:25:28,685 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=51, pair=LTC/USDT, amount=0.33887079, open_rate=44.22000000, open_since=2020-04-24 10:36:45)
2020-04-24 19:25:42,653 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=51, pair=LTC/USDT, amount=0.33887079, open_rate=44.22000000, open_since=2020-04-24 10:36:45)
2020-04-24 19:25:53,924 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=51, pair=LTC/USDT, amount=0.33887079, open_rate=44.22000000, open_since=2020-04-24 10:36:45)
2020-04-24 19:26:01,693 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2020-04-24 19:26:01,694 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-04-24 19:26:01,842 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-04-24 19:26:01,842 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2020-04-24 19:26:18,048 - freqtrade - ERROR - Could not cancel order. Message: binance {"code":-2011,"msg":"Unknown order sent."}
  ```

**Comment by hroff-1902** [comment]
the config is very specific, but this situation should be properly handled and should not cause the bot to die, thanks for reporting...

**Comment by xmatthias** [comment]
This was already closed in #3181.

Please update the bot and retry - thanks.

**Comment by xmatthias** [comment]
I'll close this since it's been addressed in the latest version.

Feel free to reopen / comment if the issue reappears with the latest develop (or 2020.4).

**Comment by devilsinthedetail** [comment]
Had the same crash just now, and as far as I can tell I have the above commit merged. 

> 2020-05-08 01:11:00,121 - freqtrade.freqtradebot - INFO - Executing Sell for KNC/ETH. Reason: SellType.ROI
> 2020-05-08 01:11:00,941 - freqtrade.wallets - INFO - Wallets synced.
> 2020-05-08 01:11:01,474 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
> 2020-05-08 01:11:01,921 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell, 'exchange': 'Binance', 'pair': 'KNC/ETH', 'gain': 'profit', 'limit': 0.0029946, 'order_type': 'limit', 'amount': 49.0, 'open_rate': 0.0029714, 'current_rate': 0.0029859, 'profit_amount': 0.00084447, 'profit_ratio': 0.00579417, 'sell_reason': 'roi', 'open_date': datetime.datetime(2020, 5, 7, 22, 56, 16, 859404), 'close_date': datetime.datetime(2020, 5, 7, 23, 11, 1, 921528), 'stake_currency': 'ETH', 'fiat_currency': 'EUR'}
> 2020-05-08 01:11:02,991 - freqtrade.wallets - INFO - Wallets synced.
> 2020-05-08 01:11:17,821 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:11:28,632 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:11:32,104 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:11:37,105 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:11:42,116 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:11:46,787 - freqtrade.worker - INFO - Bot heartbeat. PID=3083, version='develop-25d9001f', state='RUNNING'
> 2020-05-08 01:11:47,112 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:11:52,113 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:11:57,116 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:12:15,073 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:12:28,972 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:12:33,517 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:12:38,522 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:12:43,555 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:12:48,205 - freqtrade.worker - INFO - Bot heartbeat. PID=3083, version='develop-25d9001f', state='RUNNING'
> 2020-05-08 01:12:48,566 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:12:53,556 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:12:58,563 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:13:16,926 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:13:28,346 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:13:32,515 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:13:37,493 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:13:42,504 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:13:47,503 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:13:52,182 - freqtrade.worker - INFO - Bot heartbeat. PID=3083, version='develop-25d9001f', state='RUNNING'
> 2020-05-08 01:13:52,509 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:13:57,507 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:14:15,745 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=42, pair=KNC/ETH, amount=49.00000000, open_rate=0.00297140, open_since=2020-05-07 22:56:16)
> 2020-05-08 01:14:16,254 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
> 2020-05-08 01:14:16,254 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
> 2020-05-08 01:14:16,317 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
> 2020-05-08 01:14:16,317 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
> 2020-05-08 01:14:32,299 - freqtrade - ERROR - Could not cancel order. Message: binance {"code":-2011,"msg":"Unknown order sent."}

**Comment by xmatthias** [comment]
@devilsinthedetail please open a new issue - filling out the issue template.
