### ISSUE TITLE
Enable position stacking in live/dry mode

### ISSUE THREAD

**Issue by gilsonmandalogo** [freqtrade/freqtrade#3209]
## Step 1: Have you search for this issue before posting it?

Similar to #1519 and #1099

## Step 2: Describe your environment

  * Operating system: OSX
  * Python Version: Python 3.7.7 (`python -V`)
  * CCXT version: ccxt==1.24.83 (`pip freeze | grep ccxt`)
  * Branch: Master
  * Last Commit ID: 9abfdaaaa240dcab2fbd105982ed6eed025d8936 (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

I’m trying to use position stacking in live/dry mode. After look at code, I find a config `position_stacking` that have effects only on backtesting mode.
So I removed this code block (from [here](freqtrade/freqtradebot.py)) to get position stacking in live/dry mode:
```python
# Remove pairs for currently opened trades from the whitelist
for trade in Trade.get_open_trades():
  if trade.pair in whitelist:
    whitelist.remove(trade.pair)
    logger.debug('Ignoring %s in pair whitelist', trade.pair)
```
I made some tests in dry mode, and looks good.
Will this change create future problems?

I can create a PR that use the existing `position_stacking` config to avoid this code block by a "if" statement.

Thanks.

**Comment by xmatthias** [comment]
Simply changing this will work, as most of the code assumes that only one trade for a pair is allowed - changing only this will most likely break in many other areas (RPC, ...).


One problem you'll encounter for sure is that it'll buy the same pair with EVERY iteration for the whole candle (a signal is usually enabled for a whole candle) - so assuming you're using 5m candles, you'd be buying ETH/BTC roughly every 5 seconds for a total of 5 minutes.

It may work with very specific configurations (`process_only_new_candles=True`) and with very specific startegies (which do not suffer from "sticking signals") - but without a TON of further safeguards, this is to dangerous as it'll just buy the same symbol until you run out of balance in stake_currency.

Please continue further discussion in #1519 to avoid splitting the same topic into multiple issues.

**Comment by Ectsang** [comment]
> Simply changing this will work, as most of the code assumes that only one trade for a pair is allowed - changing only this will most likely break in many other areas (RPC, ...).
> 
> One problem you'll encounter for sure is that it'll buy the same pair with EVERY iteration for the whole candle (a signal is usually enabled for a whole candle) - so assuming you're using 5m candles, you'd be buying ETH/BTC roughly every 5 seconds for a total of 5 minutes.
> 
> It may work with very specific configurations (`process_only_new_candles=True`) and with very specific startegies (which do not suffer from "sticking signals") - but without a TON of further safeguards, this is to dangerous as it'll just buy the same symbol until you run out of balance in stake_currency.
> 
> Please continue further discussion in #1519 to avoid splitting the same topic into multiple issues.

@xmatthias - so if I force `process_only_new_candles=True` and only stick to specific strategies that do not suffer from "sticking signals" (what are they, by the way?) and have safeguards like checking the balance of stake_currency, then does freqtrade support positioning stacking?

**Comment by xmatthias** [comment]
No, freqtrade does not support position stacking at this moment.

**Comment by ir0nt0ad** [comment]
Is it still not supported for live/dry, or handled through `adjust_trade_position`? Thanks

**Comment by stash86** [comment]
well, you already answered your own question. Please open a new issue if you want to ask something.
