### ISSUE TITLE
Can't autorun both the trading and telegram bots after server restart

### ISSUE THREAD

**Issue by BlueSkyTrading** [freqtrade/freqtrade#3213]
## Step 1: Have you search for this issue before posting it?
yes, this [ticket 3105](https://github.com/freqtrade/freqtrade/issues/3105) is close to my issue but not the same problem.

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Ubuntu 19.10 Server Headless (VPS)
  * Python Version: 3.7.5
  * CCXT version: 1.26.53
  * Branch: Develop
  * Last Commit ID: e6d3e2e7d38b7b07ac1f6c21d1c5e517fee2ff06
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*
systemd don't autorun the bot after server restart, and no error message to find where the issue is also.
### Steps to reproduce:

  1. _____
Here is the file location:
`(.env) root@xxx:~/freqtrade# which freqtrade`
  ```
/root/freqtrade/.env/bin/freqtrade
  ```

  2. _____
Here is the freqtrade file with the first line updated
`root@xxx:~/freqtrade/bin# nano freqtrade`
  ```
#!/root/freqtrade/.env/bin/python3

import sys
import logging

logger = logging.getLogger(__name__)


logger.error("DEPRECATED installation detected, please run `pip install -e .` again.")

sys.exit(2)
  ```

  3. _____
Here is the service file content:
`root@xxx:~# sudo systemctl edit --force --full freqtrade.service`
  ```
[Unit]
Description=Freqtrade Service
Wants=network.target
After=network.target

[Service]
ExecStartPre=/bin/sleep 10
ExecStart=/root/freqtrade/freqtrade trade -c /root/freqtrade/config.json --strategy SampleStrategy --userdir /root/freqtrade/
Restart=always

[Install]
WantedBy=multi-user.target
  ```
  
### Observed Results:

  * What happened?
Nothing
  * What did you expect to happen?
Freqtrade to start automatically and Telegram Bot sending notifications that it's up and running.

### Relevant code exceptions or logs:
Once and re-enable the service and restart the server, I get no error or success messages, and the log of the service status shows this:
`root@xxx:~# sudo systemctl enable freqtrade.service`
`root@xxx:~# sudo reboot now`
`root@xxx:~# sudo systemctl status freqtrade.service`

  ```
Last login: Sat Apr 25 02:31:00 2020 from xxx.xxx.xxx.xxx
root@xxx:~# sudo systemctl status freqtrade.service
● freqtrade.service - Freqtrade Service
   Loaded: loaded (/etc/systemd/system/freqtrade.service; enabled; vendor preset: enabled)
   Active: activating (start-pre) since Sat 2020-04-25 04:33:34 UTC; 7s ago
Cntrl PID: 861 (sleep)
    Tasks: 1 (limit: 1078)
   Memory: 144.0K
   CGroup: /system.slice/freqtrade.service
           └─861 /bin/sleep 10
  ```
I just can't figure out what I did missed!

**Comment by xmatthias** [comment]
Does it run without restarting the server (`systemctl start freqtrade.service`) ? 

I don't think it will, as your paths to binaries seem messed up.

Please open `/root/freqtrade/freqtrade` and verify it's a file (i think it'll be a directory...). 
This is the file that you configured as binary to run - not `/root/freqtrade/bin/freqtrade` (which is the file you opened a few lines above - and which is unable to run as that's a deprecated file).

Best enable the virtual environment - and run `which freqtrade` to get the correct path - and configure THAT as `ExecStart`.

**Comment by iboumiza** [comment]
Starting the service doesn't give either a success or failure message:
`root@xxx:~# sudo systemctl start freqtrade.service`
```
root@xxx:~# 
```

Yes, using this command return a file, not a folder:
`root@vultrjpycryptobot:~/freqtrade# freqtrade`
```
Usage of Freqtrade requires a subcommand to be specified.
```

Also, here is the correct path:
```
root@xxx:~/freqtrade# source .env/bin/activate
(.env) root@xxx:~/freqtrade# which freqtrade
```
`/root/freqtrade/.env/bin/freqtrade`

And I updated freqtrade.service to this:
```
[Unit]
Description=Freqtrade Service
Wants=network.target
After=network.target

[Service]
ExecStartPre=/bin/sleep 10
ExecStart=/root/freqtrade/.env/bin/freqtrade trade -c /root/freqtrade/config.json --strategy SampleStrategy --userdir /root/freqtrade/
Restart=always

[Install]
WantedBy=multi-user.target
```

But still, nothing happens...

**Comment by xmatthias** [comment]
well what do you expect to happen? logs will be in journald ... (`journalctl -f` should show them)...

as said - you first need to get it running using `systemctl start freqtrade`.

To test - best use only the line from ExecStart - maybe there's a mistake in the configuration, or a typo in the strategy ... something like that.

Just run the following in your terminal - and observe the log messages.

```
/root/freqtrade/.env/bin/freqtrade trade -c /root/freqtrade/config.json --strategy SampleStrategy --userdir /root/freqtrade/
```

**Comment by iboumiza** [comment]
I expect it to start running the bot and send notifications through the telegram bot automatically each time the server reboots.

Here is the log messages for the command:
`root@xxx:~/freqtrade# /root/freqtrade/.env/bin/freqtrade trade -c` 
```
/root/freqtrade/config.json --strategy SampleStrategy --userdir /root/freqtrade/
2020-04-25 18:33:06,105 - freqtrade.loggers - INFO - Verbosity set to 0
2020-04-25 18:33:06,106 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2020-04-25 18:33:06,106 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2020-04-25 18:33:06,106 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2020-04-25 18:33:06,106 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 15 ...
2020-04-25 18:33:06,106 - freqtrade.configuration.configuration - INFO - Using user-data directory: /root/freqtrade ...
2020-04-25 18:33:06,107 - freqtrade.configuration.configuration - INFO - Using data directory: /root/freqtrade/data/binance ...
2020-04-25 18:33:06,107 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-04-25 18:33:06,107 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-04-25 18:33:06,107 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-04-25 18:33:06,107 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-e6d3e2e7
2020-04-25 18:33:06,108 - freqtrade - ERROR - Impossible to load Strategy 'SampleStrategy'. This class does not exist or contains Python code errors.
```
What's weird is that I can run the bot without issues in the (.env)

`(.env) root@xxx:~/freqtrade# freqtrade trade -c config.json -s SampleStrategy`
```
2020-04-25 18:47:23,145 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SampleStrategy from '/root/freqtrade/user_data/strategies/sample_strategy.py'...
```

And the journal log:
`root@xxx:~/freqtrade# journalctl -f`
```
-- Logs begin at Fri 2020-04-24 05:22:41 UTC. --
Apr 25 18:33:33 xxx freqtrade[4915]: 2020-04-25 18:33:33,098 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
Apr 25 18:33:33 vultrjpycryptobot freqtrade[4915]: 2020-04-25 18:33:33,098 - freqtrade.freqtradebot - INFO - Starting freqtrade develop
Apr 25 18:33:33 xxx freqtrade[4915]: 2020-04-25 18:33:33,098 - freqtrade - ERROR - Impossible to load Strategy 'SampleStrategy'. This class does not exist or contains Python code errors.
Apr 25 18:33:33 xxx systemd[1]: freqtrade.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 25 18:33:33 xxx systemd[1]: freqtrade.service: Failed with result 'exit-code'.
Apr 25 18:33:33 xxx systemd[1]: freqtrade.service: Service RestartSec=100ms expired, scheduling restart.
Apr 25 18:33:33 xxx systemd[1]: freqtrade.service: Scheduled restart job, restart counter is at 4818.
Apr 25 18:33:33 xxx systemd[1]: Stopped Freqtrade Service.
Apr 25 18:33:33 xxx systemd[1]: Starting Freqtrade Service...
```

**Comment by xmatthias** [comment]
it's very simple.
Fix the directories until the command the way you specify it in ExecStart works.

Systemd is just executing this command - if it doesn't work manually, it will NEVER work with systemd (how could it - your command is obviously wrong).

It's not a systemd problem, but a problem of your environment.

**Comment by BlueSkyTrading** [comment]
ok, I got this line working:
`ExecStart=/root/freqtrade/freqtrade/main.py trade -c /root/freqtrade/config.json --strategy SampleStrategy --userdir user_data/`

the solution was to replace `--userdir /root/freqtrade/` by `--userdir user_data/`

But my problem still persists, rebooting the server doesn't restart the bot automatically, still investigating...

**Comment by hroff-1902** [comment]
`systemctl enable servicename`

**Comment by BlueSkyTrading** [comment]
yes, already did:
`sudo systemctl start freqtrade.service`
and
`sudo systemctl enable freqtrade.service`

**Comment by hroff-1902** [comment]
then the system should restart it after reboot

what `systemctl status` says after reboot?

**Comment by BlueSkyTrading** [comment]
Here is the result after reboot:
```
root@xxx:~# systemctl status freqtrade.service
● freqtrade.service - Freqtrade Service
   Loaded: loaded (/etc/systemd/system/freqtrade.service; enabled; vendor preset: enabled)
   Active: activating (start-pre) since Sun 2020-04-26 18:24:25 UTC; 9s ago
Cntrl PID: 968 (sleep)
    Tasks: 1 (limit: 1078)
   Memory: 152.0K
   CGroup: /system.slice/freqtrade.service
           └─968 /bin/sleep 10

Apr 26 18:24:25 xxx systemd[1]: Starting Freqtrade Service...
```

And it remains stuck in Starting service state like every time.

**Comment by hroff-1902** [comment]
what's in the freqtrade log?

**Comment by xmatthias** [comment]
well - you're trying to restart - but does `systemctl start freqtrade.service` actually work?

i don't think it is, since your `--userdir` is relative.

`--userdir user_data/` should most likely be `--userdir /root/freqtrade/user_data/` ...

**Comment by hroff-1902** [comment]
If it starts with start but not with enable, the reason can be the current directory.
If you use a non-absolute path in the command line (like user_data instead of /user_data) then you probably need to add the `RuntimeDirectory=dir` into the service file to point into the dir where user_data resides.

**Comment by BlueSkyTrading** [comment]
It finally worked,
now anytime I restart the server, the systemd will wait 10 seconds to avoid connection error then starts both the trading and telegram bots automatically!

Thank you so much @xmatthias and @hroff-1902 , you guys are Rock Stars!!!

Here is the final systemd file:
```
[Unit]
Description=Freqtrade Service
Wants=network.target
After=network.target

[Service]
ExecStartPre=/bin/sleep 10
ExecStart=/root/freqtrade/freqtrade/main.py trade -c /root/freqtrade/config.json --strategy SampleStrategy --userdir /root/freqtrade/user_data/

Restart=always

[Install]
WantedBy=multi-user.target
```
Long Live Freqtrade!

**Comment by hroff-1902** [comment]
(this is more for others, reading this later)

I was a bit wrong above -- `systemctl start` also starts the service with the same (non-current) dir, so @xmatthias was correct, your `systemctl start` should also been non-working, due to non-absolute path used...

In order to debug the reason, you could temporarily remove `Restart=always` -- you'll be able to see the last status code then; also, you could try to add the `-v` into the freqtrade options to have more verbose output in the log (debug level) to find out the problem easier...

**Comment by raminhafezi** [comment]
Hi 

I came up with this script to have create/manage multiple instances of the freqtrade on .env environment and set them to systemd
I am running freqtrade on raspberry pi and shebang of the main.py in freqtrade/freqtrade folder is _#!/usr/bin/env python3_  we run and install freqtrade in virtual environment

Since I want to run multiple instances of the freqtrade simultaneously, I am using @ in a command line bellow, which will be  a Service name when we want to enable this service. notice any name after @ in the bellow command will be replace with %i on the script.
`**sudo systemctl edit --force --full freqtrade@.service**
`
the above command should open an empty file. so copy-paste bellow script. Replace "pi" to your username.

====================================
```
[Unit]
Description=Freqtrade %i Service
Wants=network.target
After=network.target

[Service]
type=simple
ExecStart=/home/pi/freqtrade/.env/bin/python3 /home/pi/freqtrade/freqtrade/main.py trade -c /home/pi/freqtrade/config_%i.json --strategy %i --strategy-path /home/pi/freqtrade/user_data/strategies --userdir /home/pi/freqtrade/ --db-url sqlite:///%i.dryrun.sqlite
Restart=always

[Install]
WantedBy=multi-user.target
```
=============================================

so if I want to run SampleStrategy, I will make a freqtrade service with the same name. like this

```
sudo systemctl enable freqtrade@SampleStrategy.service
sudo systemctl start freqtrade@SampleStrategy.service

```
the above command is looking for a 
 - config file with a name config_SampleStrategy.json on the main folder of the freqtrade
 - a strategy file named SampleStrategy in the user_data/strategy folder
 - make/open a database with the name of SampleStrategy.drydun.sqlite on the main folder.
 - and finally make a service with a name of freqtrade@SampleStrategy
 
This service should be run everytime after reboot and also you can control it with 

```
systemctl start freqtrade@SampleStrategy
systemctl status freqtrade@SampleStrategy 
systemctl stop freqtrade@SampleStrategy
```

for making another instance of the freqtrade to run simultaneously with SampleStrategy

`**sudo systemctl enable freqtrade@RSI.service** 
`

just check inadvance you have the config_RSI.json and RSI.py strategy in strategy folder
