### ISSUE TITLE
Memory leak on Ubuntu Server

### ISSUE THREAD

**Issue by Vildnex** [freqtrade/freqtrade#3220]
## Step 1: Have you search for this issue before posting it?
Yes I did and I found nothing, except something on hyperopt side but I don't really care about that one.

## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04.3 (Server edition) (I'm using DigitalOcean Cloud)
  * Python Version: 3.7 (`python -V`)
  * CCXT version: 1.26.53 (`pip freeze | grep ccxt`)
  * Branch: Master | Develop (I've also checked that on **2020.3** as Release)
  
## Step 3: Describe the problem:

PS: I've tried to use also docker for this issue.

I've created a Droplet using DigitalOcean Cloud using the following configurations:

- First try: 1 vCPU, 1 GB RAM
- Second try: 1 vCPU, 2 GB RAM
- Third try: 2 vCPU, 2 GB RAM
- LAST try: 1 vCPU, 3 GB RAM

### Steps to reproduce:

Every time I've just start te robot with this command: 
`freqtrade trade -s MY_STRATEGY -c ./config.json --db-url sqlite:///tradesv3.SOME_DB.sqlite
`  and I'm just waiting

This is the CPU and RAM in the past 24h. Doesn't matter if I have one CPU or two, neither 1, 2 or 3 GP of RAM, every time it's exactly the same, the only difference been how long its gonna take until my RAM will be full, and at that moment the bot will crash most of the times (sometimes is going to stay at 100% CPU and RAM for a while until it will crash)

![image](https://user-images.githubusercontent.com/10352059/80291153-c11a8f00-8753-11ea-8342-e7917ba8538c.png)
![image](https://user-images.githubusercontent.com/10352059/80291182-24a4bc80-8754-11ea-9f9c-5f105e547e75.png)

## UPDATE

I've just checked and one the release **2020.1** everything it's fine and there is no memory leak, It's happening just in **2020.3** and on the **development** branch. 
**PS:** I didn't check in 2020.2

![image](https://user-images.githubusercontent.com/10352059/80293254-90902080-8766-11ea-9bbd-54def283138e.png)
![image](https://user-images.githubusercontent.com/10352059/80293256-95ed6b00-8766-11ea-8336-8327988b2a9a.png)

**Comment by hroff-1902** [comment]
maybe pandas memory leak in the strategy...

**Comment by xmatthias** [comment]
i guess so. Please verify if your strategy is using `.rolling().max()` either directly, or within one of the methods (e.g. ichimoku).

**Comment by Vildnex** [comment]
You were right @xmatthias, the problem of memory leak was because of pandas. I've removed the pandas 1.0 and I've installed 0.25.3, now everything it's working properly. Thanks.

**Comment by Chyang777** [comment]
Can someone please help me how to downgrade the pandas. Thanks.

**Comment by Chyang777** [comment]
```
(.env) root@chyang:~/freqtrade# pip install pandas==0.25.3
Collecting pandas==0.25.3
  Using cached pandas-0.25.3-cp38-cp38-manylinux1_x86_64.whl (10.4 MB)
Requirement already satisfied: pytz>=2017.2 in ./.env/lib/python3.8/site-packages (from pandas==0.25.3) (2021.1)
Requirement already satisfied: python-dateutil>=2.6.1 in ./.env/lib/python3.8/site-packages (from pandas==0.25.3) (2.8.1)
Requirement already satisfied: numpy>=1.13.3 in ./.env/lib/python3.8/site-packages (from pandas==0.25.3) (1.20.3)
Requirement already satisfied: six>=1.5 in ./.env/lib/python3.8/site-packages (from python-dateutil>=2.6.1->pandas==0.25.3) (1.16.0)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 1.2.4
    Uninstalling pandas-1.2.4:
      Successfully uninstalled pandas-1.2.4
Successfully installed pandas-0.25.3
(.env) root@chyang:~/freqtrade# freqtrade trade --config config.json --config config-private.json --strategy BBRSI
Traceback (most recent call last):
  File "/root/freqtrade/.env/bin/freqtrade", line 11, in <module>
    load_entry_point('freqtrade', 'console_scripts', 'freqtrade')()
  File "/root/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/root/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/root/freqtrade/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/freqtrade/freqtrade/main.py", line 15, in <module>
    from freqtrade.commands import Arguments
  File "/root/freqtrade/freqtrade/commands/__init__.py", line 11, in <module>
    from freqtrade.commands.data_commands import (start_convert_data, start_download_data,
  File "/root/freqtrade/freqtrade/commands/data_commands.py", line 14, in <module>
    from freqtrade.resolvers import ExchangeResolver
  File "/root/freqtrade/freqtrade/resolvers/__init__.py", line 10, in <module>
    from freqtrade.resolvers.strategy_resolver import StrategyResolver
  File "/root/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 17, in <module>
    from freqtrade.strategy.interface import IStrategy
  File "/root/freqtrade/freqtrade/strategy/__init__.py", line 4, in <module>
    from freqtrade.strategy.hyper import (CategoricalParameter, DecimalParameter, IntParameter,
  File "/root/freqtrade/freqtrade/strategy/hyper.py", line 10, in <module>
    from freqtrade.optimize.hyperopt_tools import HyperoptTools
  File "/root/freqtrade/freqtrade/optimize/hyperopt_tools.py", line 12, in <module>
    from pandas import isna, json_normalize
ImportError: cannot import name 'json_normalize' from 'pandas' (/root/freqtrade/.env/lib/python3.8/site-packages/pandas/__init__.py)
```

**Comment by xmatthias** [comment]
0.25 is most likely a too old version - which freqtrade won't work on.

This bug should be fixed in 1.0.4 or higher ... as such there's no need to downgrade pandas due to this bug.

**Comment by Chyang777** [comment]
it cause crash on my vps if using pandas version 1.2.4, I downgrade it to 1.0.4, problem at numpy, I downgrade the numpy to 1.20.0, still problem, all this I used script installation not docker.

Unexpected error Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>'
2021-06-22 06:42:58,545 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair MATIC/USDT: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

**Comment by xmatthias** [comment]
as far as i know, there's no known memory leak in the recent pandas versions (at least not the one that's mentioned in this issue).
As such - i doubt that it's related to pandas - but simply to a undersized VPS for the task at hand.

Please note: we do not support using older versions of pandas (it may work - but we can't guarantee it - and investigation which version is the earliest possible is up to the user) 


Please avoid reviving old issues - this will send notifications to everyone involved. 
As such - i'll lock this issue to avoid further unnecessary notifications to all involved in this issue.

If you have a problem, please open a new issue posting your issue details. 
While it may seem to be related to you- it's very unlikely that you encounter the same issue today, as it was a issue that was limited to pandas versions 1.0.0-1.0.3.
