### ISSUE TITLE
Trailing_stop_positive_offset - Positive maximum value?

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#3227]
Is there a specific reason why this variable has a MAXIMUM of 1?

**Comment by xmatthias** [comment]
well it's a ratio ... - having 110% is not very usual.

And limiting it "upwards" prevents users from setting 1.1 - and assuming it's 1.1% - while they should be setting 0.011 - so i'm not convinced if opening it up towards the top is a good idea
