### ISSUE TITLE
How to test based on the volume (up/down - red/green)

### ISSUE THREAD

**Issue by funappfactory** [freqtrade/freqtrade#3230]
Hi,
In my strategy, I want to add a test depending on the volume type. So I wonder if there is way to test if: 

-  the trade volume goes up or down
-  the type of the trade volume ( red or green)

Thank you.

**Comment by hroff-1902** [comment]
To test how values in the 'volume' column changed comparing to the previous candle:
```
(dataframe['volume'].shift(1) > dataframe['volume'])
```
and
```
(dataframe['volume'].shift(1) < dataframe['volume'])
```

What is "type of the trade volume ( red or green)"?

**Comment by funappfactory** [comment]
ThAnk you for the quick response.
For the trade type, I guess I will test the close and open values.

**Comment by hroff-1902** [comment]
> For the trade type, I guess I will test the close and open values.

But it's not about volume, it's about prices.
