### ISSUE TITLE
VWAP indicator not recognised

### ISSUE THREAD

**Issue by funappfactory** [freqtrade/freqtrade#3236]
Hi,
when I try to use the VWAP indicator in my strategy as follow

`dataframe['vwap'] = ta.VWAP(dataframe)`

I get the following error

`AttributeError: module 'talib.abstract' has no attribute 'VWAP'`

even if the vwap is defined in the qtpylib. any ideas ?

thank you.

**Comment by xmatthias** [comment]
well - you're calling ta.VWAP - but qtpylib is not ta-lib - it's two different things.

You should be able to call it via `qtpylib.vwap(dataframe)` ...

**Comment by hroff-1902** [comment]
right, there is not VWAP in ta-lib: see https://mrjbq7.github.io/ta-lib/funcs.html

yes, qtpylib has VWAP indicator (available as `qtpylib.vwap`)

**Comment by hroff-1902** [comment]
See https://mrjbq7.github.io/ta-lib/funcs.html for the list of indicators in ta-lib

**Comment by funappfactory** [comment]
Thank you for your replies.

qtpylib.vwap works

**Comment by paul67567** [comment]
Hi, Firstly, Thanks for all the work you've put into this software, much appreciated.
I'm not sure if I should start a new thread but it's a very similar topic so I will add it here for now.
When I tried to add vwap using 
dataframe['vwap'] = qtpylib.vwap(dataframe)
I get TypeError: 'Series' object is not callable

I've also tried it like this, as I've seen other dataframes declared in this format
mvwap = qtpylib.vwap(dataframe)
dataframe['vwap'] = mvwap['vwap']
In which case I get

KeyError: 'vwap'

Any idea why neither of these are working for me and what I can do to resolve this?
I'm trying to use it on the binance exchange.
Thanks

**Comment by xmatthias** [comment]
the first error (Series object is not callable) wil not appear on this line - but suggests that in your buy (or sell) condition, you're missing a operator.

this error usually comes up if you got `(<something>)(<something>)` instead of `(<something>)&(<something>)`..

**Comment by paul67567** [comment]
thank you

**Comment by bigsee** [comment]
@xmatthias I had a similar issue - thank you!

**Comment by xmatthias** [comment]
You might be careful with `qtpylib.vwap`. 
It's calculating vwap based on the full timerange, which means it'll have lookahead bias in backtesting.

Better use `qtpylib.rolling_vwap()` - which will calculate vwap in a rolling manner, without lookahead bias by using the full dataframe.

**Comment by straj-granicy** [comment]
@xmatthias ,
when using qtpylib.rolling_vwap() I've got the error
TypeError: rolling_vwap() missing 1 required positional argument: 'bars'

**Comment by xmatthias** [comment]
well you can't use `qtpylib.rolling_vwap()` just like this - it'll obvioulsy need arguments like the dataframe (`qtpylib.rolling_vwap(dataframe)`) should work when using default parameters.

In general, i'd suggest to properly configure an editor with syntax highlighting and code-completion (e.g. vscode + python plugin) - which will show you arguments.

**Comment by gfaus91** [comment]
Hi, 
I've just calculated TWAP. I share with you, that I think is a good indicator to see where intelligent money is selling and buying.
I think is well calculated.

def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['av_row'] = dataframe[["open","high","low","close"]].mean(axis=1)
        dataframe['twap'] = dataframe['av_row'].rolling(28).mean()

Maybe you can include it easily in your library. 
Thanks for your job, is very good, I'm trying to see if something works, but using Technical Indicators is very difficult, as the prices have to be considered random. In my test for now always 50% wins and losses.

Are you working on the possibility of using other pairs as an indicator like Nasdaq to predict BTC in a very short time?
For now, I didn't run a real-live bot with Freqtrade, but are you working on the order system? and recalculation of limits orders and cancels? There are a lot of boots in the book always relocating orders. I need to focus more on that part. I don't think any simple strategy with Technical indicators is going to work, but If any person can show me some code that returns some benefits in the long term, I'll be very thankfull.

Thanks

**Comment by xmatthias** [comment]
@mcweeds you're free to explore the [docs](https://www.freqtrade.io/en/stable/) - more specifically the [callbacks](https://www.freqtrade.io/en/stable/strategy-callbacks/) section - which will show you that pure technical trading is far from the only thing that freqtrade offers.

**Comment by gfaus91** [comment]
@xmatthias Thank you!
Yes, I'm trying to understand but is complex, I need time.
