### ISSUE TITLE
Plot only a specific period

### ISSUE THREAD

**Issue by funappfactory** [freqtrade/freqtrade#3237]
Hi,

Is there a way to make the  `./scripts/plot_dataframe.py`  plot only a given period of time ?

Thank you

**Comment by hroff-1902** [comment]
there is no ./scripts/plot_dataframe.py for long time. You must be using an outdated version, pls update to current one (and read the actual docs)

**Comment by funappfactory** [comment]
Ok thank you

**Comment by xmatthias** [comment]
Please review [the documentation](https://www.freqtrade.io/en/latest/plotting/) for the commands.

Plotting dataframes now works via `freqtrade plot-dataframe` - which has quite some options.

As @hroff-1902 says, if you still have the `plot_dataframe.py` file in your folder, best upate the bot to a new version.
