### ISSUE TITLE
Dynamic Informative pairs

### ISSUE THREAD

**Issue by pAulseperformance** [freqtrade/freqtrade#3240]
**Using the informative pairs method is essentially limited to static pairs known before initialization.** 

This causes an impediment if I want to use a dynamic pairlist like a volumepairlist, as I won't know which pairs I need to define until after the bot has initialized. 

To enhance this method for dynamic pairs I found a solution that worked for me. 

I simply attached the PairListManager instance to an Istrategy attribute during the FreqtradeBot initialization. This allows access to the pairlist when the informative_pairs method is called. 
  
    # freqtrade.py

    Class FreqtradeBot:
        def __int__...
            # init other stuff
        
            self.pairlists = PairListManager(self.exchange, self.config)
            # Attach pairLists to Strategy baseclass
            IStrategy.pairlists = self.pairlists
        

Then during the initialization of the strategy. When informative_pairs() is called...

    # mystrategy.py
    
    ...
    ticker_interval = '1m'
    ...
    
    def informative_pairs(self):
        pairs = self.pairlists.whitelist
        informative_pairs = [(pair, '1d') for pair in pairs]
        return informative_pairs
        
I'm not sure if this is the best approach, but it works for me.

**Comment by xmatthias** [comment]
at first i thought "but you can change the return-value of `informative_pairs()`with every iteration and it would pick it up" - but yeah, you're right, it's not working as you don't know your current whitelist.

While this method works, i would probably want to abstract this through dataProvider ... so it's a "unified" user-interface for all data / additional info methods

basically so you could call it as `self.dp.current_whitelist` ... (or something like that ...).

**Comment by GrilledChickenThighs** [comment]
Yea keeping it under dp would be more intuitive and unified.

**Comment by xmatthias** [comment]
Comments from @hroff-1902  in #3267 - migrated here to keep the PR clean:

My old idea (stash with it was lost) was to allow
```
    def informative_pairs(self):
        return [(None, "5m"),
                   ]
```
or
```
    def informative_pairs(self):
        return [("", "1d"),
                   ]
```
and correspondingly, in populate_indicators() or in populate_buy/sell_trend():
```
    informative = self.dp.get_pair_dataframe(pair=None,  # or ""
                                             timeframe="1d")
```
to fetch the data for the current pair but with different timeframe...

--------

Another idea, to implement it with a decorator, which adds a parameter to the strategy method with ohlcv for informative pair (also, if pair is omitted it means current pair):

```
    @add_informative(timeframe="1d")
    def populate_indicators(self, dataframe: DataFrame, metadata: dict,
                                           df_1d: DataFrame) -> DataFrame:
        # RSI on "normal" ohlcv
        dataframe['rsi'] = ta.RSI(dataframe)
        # RSI on "1d" ohlcv for current pair
        rsi_1d = ta.RSI(df_1d)
        # Any other calculations on rsi_1d can be done here
        # And finally it can be merged back with resampling to "normal" dataframe
        ...
```

Multiple informative can be used this way:
```
    @add_informative(timeframe="1d")
    @add_informative(timeframe="1h")
    @add_informative(pair="ETH/BTC")
    def populate_indicators(self, dataframe: DataFrame, metadata: dict,
                                           ethbtc_df: DataFrame,  # Current timeframe, but for ETH/BTC
                                           df_1h: DataFrame, df_1d: DataFrame) -> DataFrame:
        # RSI on "normal" ohlcv
        dataframe['rsi'] = ta.RSI(dataframe)
        # RSI on "1d" ohlcv for current pair
        rsi_1d = ta.RSI(df_1d)
        # RSI on "1h" ohlcv for current pair
        rsi_1h = ta.RSI(df_1h)
        # RSI on ETJ
        rsi_ethbtc = ta.RSI(ethbtc_df)
        ...
```

**Comment by xmatthias** [comment]
@hroff-1902 i took the liberty to migrate your comments here (see above post) and delete them in the issue - as they don't really belong there (which you realized yourself, in the end).

----

As said already someplace else, i'm against the use of decorators in user-exposed (speak strategy) places, since i think they are complicated to understand for non-developers (which some/most of our audience is).

**Comment by GrilledChickenThighs** [comment]
@xmatthias I like the idea of decorators from @hroff-1902. I can see how it would be confusing for non-developers, but at the same time it might not be... They don't need to understand how the decorator works. Just adding @add_informative will give them access to additional information.
But it's hard to know, because I remember when I first saw decorators it was daunting haha. 

@xmatthias The 'None' abstraction is cool, keeps things easy, so users don't have to create a list from self.dp.current_whitelist inside of informative pairs. The wording could be confusing though. I would expect None to return None. Maybe use a keyword for all?

```python
# Returns all pairs on 5m timeframe
def informative_pairs(self):
        return [("All", "5m"),
                   ]
```

**Comment by hroff-1902** [comment]
decorators can be implemented later as addendum using ordinal methods from the dataprovider...

I was only generating ideas, possible implementation as I see them

**Comment by xmatthias** [comment]
well to be fair - if it's `None` - `'all'` - or `'all_pairs'` is not really relevant at this stage, is it?


The thing i found confusing with the decorator idea is that the function will suddenly have more parameters - basically resulting in - i added a decorator, now my function tells me "not  parameters than expected".

**Comment by hroff-1902** [comment]
for me, treating None/'' pair string as the marker to apply it to all pairs in the pairlist is optimal, and the decorators can be added later as a handy addendum to those who understand what they mean and how to use, modify the standard method signature, etc...

**Comment by GrilledChickenThighs** [comment]
Whichever way works best for you guys, but yea not really relevant until the method is in place. I'm still having troubles setting up the test for this. 🤕

**Comment by xmatthias** [comment]
i'd say - just push what you got so we might be able to help you out on that ?

**Comment by GrilledChickenThighs** [comment]
Tried my best to clean it up and show my logic.

**Comment by hroff-1902** [comment]
As I see it now:
* Support for wildchars (fnmatch style, i.e. '*' and '.') in informative pairs
This will allow for a user to set the pairname for informative pairs as `'*/BTC'` or `'*BEAR/USD'` (the latter example are the BEAR futures on FTX). However, this list of pairs defined this way is not limited to the current active whitelist.
* Possible further extension: wildchars in pair_whitelist/pair_blacklist in the config.
* Support for empty ("", None) pairname in the informative pairs list. This should be treated as / limited to the active pair list, but with specified timeframe. This would allow the user to fetch market for the current pair (for which the custom strategy methods are now called) but with another timeframe and avoid resampling.

**Comment by GrilledChickenThighs** [comment]
Ok should I keep this issue open for further expansion? I'm going to shift my dev efforts to helping with the UI for the moment. :)

**Comment by hroff-1902** [comment]
> Ok should I keep this issue open for further expansion? I'm going to shift my dev efforts to helping with the UI for the moment. :)

Sure, let's keep it open (I did not mark #3267 as closing it completely), I'm working on the rest described above...

**Comment by xmatthias** [comment]
I'd think we can consider this now supported, with the regex support we got for pairlists.
