### ISSUE TITLE
Installing on a Raspberry Pi: Could not build wheels for freqtrade, since package 'wheel' is not installed.

### ISSUE THREAD

**Issue by Princeton007** [freqtrade/freqtrade#3243]
## Step 2: Describe your environment

  * Operating system: Raspbian Linux raspberrypi3 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
  * Python Version: 3.7.3
 
## Step 3: Describe the problem:

Hello, 
I tried to install freqtrade on my raspberry Pi 3 running Raspbian buster with the following commands as described:
```
sudo apt-get install python3-venv libatlas-base-dev
git clone https://github.com/freqtrade/freqtrade.git
cd freqtrade
bash setup.sh -i
```
It runs and before it ends I get these messages:
```
....
Requirement already satisfied: pycparser in ./.env/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.6.1->ccxt>=1.18.1080->freqtrade===develop-0f504491) (2.20)
Could not build wheels for freqtrade, since package 'wheel' is not installed.
Could not build wheels for SQLAlchemy, since package 'wheel' is not installed.
Could not build wheels for TA-Lib, since package 'wheel' is not installed.
Could not build wheels for arrow, since package 'wheel' is not installed.
Could not build wheels for cachetools, since package 'wheel' is not installed.
....
Could not build wheels for pycparser, since package 'wheel' is not installed.
Installing collected packages: freqtrade
  Running setup.py develop for freqtrade
Successfully installed freqtrade
pip install completed

-------------------------
Please use 'freqtrade new-config -c config.json' to generate a new configuration file.
-------------------------
-------------------------
Run the bot !
-------------------------
You can now use the bot by executing 'source .env/bin/activate; freqtrade <subcommand>'.
You can see the list of available bot subcommands by executing 'source .env/bin/activate; freqtrade --help'.
You verify that freqtrade is installed successfully by running 'source .env/bin/activate; freqtrade --version'.
```

But when checking the version it answers:
```
source .env/bin/activate; freqtrade --version
freqtrade develop-0f504491
```
Are these "Could not build wheels" messages something serious or can I ignore them since the bot seems to be installed and run?

Thanks

**Comment by xmatthias** [comment]
they're not relevant. 
Wheels are a form of package to distribute modules ... but you're not trying to do that, just installing it regularily - so these are just warnings you can safely ignore.

The installation completed (if it were a problem, pip would fail).

**Comment by Princeton007** [comment]
OK great, thanks for the fast answer, so I'm good to go :-)

**Comment by hroff-1902** [comment]
@xmatthias is there the `--no-wheel` option for venv, like one which is available for virtualenv? If so, this one could be used at least while installing on RPI...

**Comment by xmatthias** [comment]
why? these messages don't hurt ... ?

**Comment by hroff-1902** [comment]
> why? these messages don't hurt ... ?

to avoid them
