### ISSUE TITLE
"Parse error at offset 800" when running config.json for dry run.

### ISSUE THREAD

**Issue by umz007** [freqtrade/freqtrade#3244]
* Operating system: macOS Version 10.12.6
  * Python Version: Python 3.7.3
  * CCXT version: 
  * Branch: Master
  * Last Commit ID: 
  
Describe the problem:

After configuring the config.json file for binance and telegram, an error appears saying "Parse error at offset 800". It also asks me to verify certain aspects of the file as shown below, which I do not know how to do. Any help will be much appreciated. Thanks

### Steps to reproduce:

  1.  freqtrade trade -c config.json

  

After configuring the config.json file and trying to run it, I receive the following error:

Parse error at offset 800: Invalid value.
Please verify the following segment of your configuration:
    },
    "exchange": {
        "name": “binance”,

**Comment by hroff-1902** [comment]
wrong quotes around "binance"

**Comment by hroff-1902** [comment]
> wrong quotes around "binance"

**Comment by umz007** [comment]
Great! This fixed it. Thanks for your help!
