### ISSUE TITLE
Buying and Selling with the Orderbook

### ISSUE THREAD

**Issue by ajimunro** [freqtrade/freqtrade#3257]
I'm attempting to create a strategy file for market-making as a project. I'm running into some issues getting the bot to buy and sell at the bid and ask. 

According to what I can see on tradingview and binance, the bot isn't reacting to buy and sell signals as I expect it to and seems to ignore many buy and sell signals (which is probably due to my very limited coding knowledge). I want to send a limit buy order at the best bid price and a limit sell order at the ask price.

`   

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        # OrderBook
        
        if self.dp:
          if self.dp.runmode.value in ('live', 'dry_run'):
            ob = self.dp.orderbook(metadata['pair'], 1)
            dataframe['best_bid'] = ob['bids'][0][0]
            dataframe['best_ask'] = ob['asks'][0][0]

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                (dataframe['low'] == dataframe['best_bid'])
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the sell signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                (dataframe['high'] == dataframe['best_ask'])
            ),
            'sell'] = 1
        return dataframe`

This is the best I could come up with. Is there a better way of doing this? My config file looks as follows as well:

`

        {
    "max_open_trades": -1,
    "stake_currency": "BTC",
    "stake_amount": 0.01,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "GBP",
    "ticker_interval": "15m",
    "dry_run": true,
    "trailing_stop": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "ask_last_balance": 0.0,
        "price_side": "bid", 
        "use_order_book": true,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy":{
        "use_order_book": true,
        "price_side": "ask",
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": true
    },`

**Comment by xmatthias** [comment]
to be honest, i'm not certain this will work (but it's also not quite clear what you'd like to do).

first of all, you'll only ever enter a trade, and then exit it - so sell signals are irrelevant until you're actually in a long position.

Then - you're comparing "low / high" with the best orderbook position. 
This sounds okish in theory, but thinking about how markets work, i don't think this will generate many (if any) signals - and if it does, it'll be pure chance.

Think about it - you're comparing the low of the previous candle with the current order books best ask.
Thinking on how cryptomarkets work - say the previous low is 99.00 USDT.
Now in the current candle, price ranges between 98 and 100 USDT. 
However, the current bit will probably be 99.1, maybe 99.01 or 98.99 - and only by chance be 99.00 at a specific point - but only for a split second before another order is placed (or this one is filled).

**Comment by ajimunro** [comment]
Yes, you're right. That must be the reason I'm not getting many buy and sell signals through the bot. I just don't know what else I can compare it to besides [open] [close] [high] or [low] in the buy and sell trends. I tried using indicators like SMA and bollinger bands with no success.

I want basically to enter a position at the best bid price and then exit the position at the ask (so enter at the 1st position on the bid side and then exit on the first position on the ask side). The coins I use have stable bids and asks so they rarely change in the short-term.

I'm guessing that if I can't send orders purely by using the order book (in other words, not taking candles into consideration) then it won't work and I'll need to find a way to code it from scratch.

**Comment by xmatthias** [comment]
well noone said that you MUST compare to open/high/low/close...
you could also compare orderbook to a fixed value 

Assuming your above setup code:
``` python
 dataframe.loc[
        (
             (1.02 >  dataframe['best_ask'])
        ),
        'sell'] = 1

```

----

Now what you must consider though is that exchange fees will usually kill this kind of strategy - I did the math for trading a stable-pair (i think it was BUSD/USDT) for a similar strategy - which has a daily move of < 0.2%.
It seems tempting - but consider that you will pay fees twice - which are 0.1% for each fee (assuming the default binance fees) - so you got 0 margin for error to come out even - letalone make a profit off of this..

**Comment by amjad-12** [comment]
Hi mr.ajimunro I want to ask you if you implemented the strategy then please
