### ISSUE TITLE
Dollar Cost Average for loss Open position

### ISSUE THREAD

**Issue by mouhamed-o** [freqtrade/freqtrade#3260]
Hi,
I want to suggest to implement DCA ([Dollar Cost Average](https://www.investopedia.com/terms/d/dollarcostaveraging.asp)). The idea is when the bot open a position, if the profit is negative and the bot detect new buy signal, the bot will buy again. This can be usefull when the market is bear.

PS : We can add new parameters to specify the maxi rebuy number for example and also the amont!

The is a link for DCA

**Comment by hroff-1902** [comment]
is it what the Shrimpy project implements?

**Comment by mouhamed-o** [comment]
Yes, something like that

**Comment by hroff-1902** [comment]
it requires complete redesign of internals of the bot, so it's not a niche for freqtrade and not a target for development efforts.

**Comment by xmatthias** [comment]
In the end, it's a request for Position staking (which we have already open #1519), as this requires the same pair to be bought again and again.


The method / strategy, as to how and when to buy (when previous profit is negative / when previous profit is positive / whenever a chicken stumbles over an egg, or a sack of rice falls in china) - is then up to the strategy.

Since position stacking is covered in #1519 - i'll close this as duplicate. Please monitor/subscribe to #1519 for future updates on this.

**Comment by hroff-1902** [comment]
In addition: I'm not sure that position staking is enough for averaging strategies be implemented in freqtrade...

**Comment by xmatthias** [comment]
why not? the strategy needs to define if it's to buy more or not. I wouldn't know what else would be reuquired ... ?

**Comment by hroff-1902** [comment]
it also requires an ability to know the amounts of all other open positions (to calculate the mean (if the positions should be equally averaged) or a fraction of the sum of them (if some other rule for the amounts of the positions is used)), and, note, non-cached, current values;
plus, it requires access for the strategy to minimal limits for orders -- to avoid issuing small orders that are less than the limit set by exchange... 

imho

**Comment by qkum** [comment]
DCA can be done in several ways

the whole idea is just to buy over a long timespan. with many small orders, so you hopefully get a nice average price in the end

the buy signal can be every hour, day, week, month etc. or some indicator

**Comment by ingo-eichhorst** [comment]
I think this can possibly archived in the strategy by having one bot for every DCA-Pair. If a certain level (e.g. -10%) is reached another trade is opened. If one trade succeeds, all others need to be closed.

According to the docs it's possible to have access to the other trades.
https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-trades

What do you think?

**Comment by xmatthias** [comment]
There's nothing wrong with DCA - and freqtrade supports that through the [adjust_trade_position() callback](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position).

what logic you apply there is fully up to you - whatever you think is profitable / gives you an edge.
