### ISSUE TITLE
Error while trying to backtest new strategy

### ISSUE THREAD

**Issue by M3L0NM4N** [freqtrade/freqtrade#3266]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

Using the latest Docker container
  
## Step 3: Describe the problem:

I developed my own very rudimentary strategy to get my feet wet... When I try to backtest, I get this error. I have tried countless things to try to fix it. Alas, I am here.
  
"2020-05-06 07:41:55,434 - freqtrade.configuration.config_validation - CRITICAL - Invalid configuration. See config.json.example. Reason: {} does not have enough properties

Failed validating 'minProperties' in schema['properties']['minimal_roi']:
    {'minProperties': 1,
     'patternProperties': {'^[0-9.]+$': {'type': 'number'}},
     'type': 'object'}

On instance['minimal_roi']:
    {}
2020-05-06 07:41:55,435 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 48, in start_backtesting
    backtesting = Backtesting(config)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 85, in __init__
    validate_config_consistency(self.config)
  File "/freqtrade/freqtrade/configuration/config_validation.py", line 80, in validate_config_consistency
    validate_config_schema(conf)
  File "/freqtrade/freqtrade/configuration/config_validation.py", line 58, in validate_config_schema
    raise ValidationError(
jsonschema.exceptions.ValidationError: {} does not have enough properties"

## Here is my code (some copied from the sample strategy)
`import numpy as np
import pandas as pd
from pandas import DataFrame
from freqtrade.strategy.interface import IStrategy
import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib

class ShortMovingAverage(IStrategy):

    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi".
    minimal_roi = {
       # "60": 0.01,
       # "30": 0.02,
       "0": 0.04
    }

    # Optimal stoploss designed for the strategy.
    # This attribute will be overridden if the config file contains "stoploss".
    stoploss = -0.10

    # Trailing stoploss
    trailing_stop = False
    # trailing_only_offset_is_reached = False
    # trailing_stop_positive = 0.01
    # trailing_stop_positive_offset = 0.0  # Disabled / not configured

    # Optimal ticker interval for the strategy.
    ticker_interval = '1m'

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = False

    # These values can be overridden in the "ask_strategy" section in the config.
    use_sell_signal = True
    sell_profit_only = False
    ignore_roi_if_buy_signal = True

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 20

    # Optional order type mapping.
    order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': True
    }

    # Optional order time in force.
    order_time_in_force = {
        'buy': 'gtc',
        'sell': 'gtc'
    }

    plot_config = {
        'main_plot': {
            'tema': {'color': 'red'},
            'sar': {'color': 'blue'},
        },
        'subplots': {
        }
    }

    def informative_pairs(self):

        return []

    def populate_indicators(self, df: DataFrame, metadata: dict) -> DataFrame:

        df['ema5'] = ta.EMA(df, timeperiod=5)
        df['sma1'] = ta.SMA(df, timeperiod=1)
        #df['adx'] = ta.ADX(df)

        return df

    def populate_buy_trend(self, df: DataFrame, metadata: dict) -> DataFrame:

        df.loc[
            (
                    (df['sma1'] >= df['ema5']) &
                    (df['sma1'] > df['sma1'].shift(1)) &
                    (df['volume'] > 0)
            ),
            'buy'] = 1

        return df

    def populate_sell_trend(self, df: DataFrame, metadata: dict) -> DataFrame:

        df.loc[
            (
                    (df['sma1'] < df['ema5']) &
                    (df['sma1'] < df['sma1'].shift(1)) &
                    (df['volume'] > 0)
            ),
            'sell'] = 1

        return df
`

## Here is my config file if that is needed.
```{
    "max_open_trades": 10,
    "stake_currency": "USDT",
    "stake_amount": 500,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "ticker_interval": "1m",
    "dry_run": true,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": true
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
        "pair_whitelist": [
            "BTC/USDT"
             
        ],
        "pair_blacklist": [
            "BNB/BTC",
            "BNB/BUSD",
            "BNB/ETH",
            "BNB/EUR",
            "BNB/NGN",
            "BNB/PAX",
            "BNB/RUB",
            "BNB/TRY",
            "BNB/TUSD",
            "BNB/USDC",
            "BNB/USDS",
            "BNB/USDT",
        ]
    },
    "pairlists": [
        {"method": "StaticPairList"}
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "nice try",
        "chat_id": "not so fast"
    },
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}


I would greatly appreciate if someone could tell me what is going wrong. Thank you so much!

**Comment by M3L0NM4N** [comment]
I'm stupid, I really apologize, I know it is annoying to make a pointless issue and close it. I have solved the issue. Bad code.

**Comment by hroff-1902** [comment]
😆 yeah, nevermind

glad that you found the problem with the config (as I can see from the first version of this issue)...
