### ISSUE TITLE
Allow interpolation of sell price.

### ISSUE THREAD

**Issue by TheSkynet1337** [freqtrade/freqtrade#3270]
## Step 1: Have you search for this issue before posting it?

I Have.

## Step 2: Describe your environment

  * Operating system:  Ubuntu 18.04.4 LTS bionic x86_64 running in docker
  * Python Version: Python 3.6.9
  * CCXT version: ccxt==1.27.1
  * Branch: Develop
  * Last Commit ID: 25d9001f8864d6a641037f7d6f8e0177df18d752
  
## Step 3: Describe the problem:
It is currently possible to have the bot buy at an interpolated price between the ask side and last price when creating a buy. This allows for buying at the exact last price(bid_strategy.ask_last_balance=1.0) or a price closer to the ask price making a quick buy more likely.

I think it would be nice if the bot could sell at an interpolated price between the bid side and last price when creating a sell. This would allow to sell at last price(using a new config option ask_strategy.bid_last_balance=1.0) or allow for quicker selling by selling closer to the bid side.

This would require the introduction of a new configuration option ask_strategy.bid_last_balance.

### Relevant code:
I think it should be possible to reuse code from get_buy_rate:

            ticker = self.exchange.fetch_ticker(pair)
            ticker_rate = ticker[bid_strategy['price_side']]
            if ticker['last'] and ticker_rate > ticker['last']:
                balance = self.config['bid_strategy']['ask_last_balance']
                ticker_rate = ticker_rate + balance * (ticker['last'] - ticker_rate)
            used_rate = ticker_rate
            self._buy_rate_cache[pair] = used_rate

and replace this code in get_sell_rate:
    
    else:
        rate = self.exchange.fetch_ticker(pair)[ask_strategy['price_side']]

with something like:

            ticker = self.exchange.fetch_ticker(pair)
            ticker_rate = ticker[ask_strategy['price_side']]
            if ticker['last'] and ticker_rate > ticker['last']: #not sure about the > here
                balance = self.config['ask_strategy'][bid_last_balance']
                ticker_rate = ticker_rate + balance * (ticker['last'] - ticker_rate)
            rate = ticker_rate

**Comment by devilsinthedetail** [comment]
I wonder if you could just use the orderbook side and go one pip higher for the buy strategy and one pip lower for the sell strategy? Could be more stable then ask_last_balance which (i think) is correlated with the spread, giving you more risk to make a bad trade

**Comment by TheSkynet1337** [comment]
With ask_last_balance buying price, if last price is below ask side on the orderbook, should calculate like this I think: buy price = ask side + ask_last_balance * (last price - ask side).
 So if ask side price is 110, last price is 100 , and ask_last_balance is 0.5 you would get 105 = 110 + 0.5 * (100 - 110) or you can buy at any other value between 100 and 110 depending on your ask_last_balance. 
If you just go down 1 pip you would just buy at 109 without any of the configurability ask_last_balance provides.
Setting ask_last_balance to 1.0 is also the only way to actually buy at last price at the moment I think.

A hypothetical bid_last_balance for selling would simply allow the same kind of flexibility on sell price which is currently bound to either selling on ask or bid price.

**Comment by hroff-1902** [comment]
Guys, am I write in assumption that this issue is a suggestion to implement the same mechanism as `bid_strategy.check_depth_of_market.bids_to_ask_delta`, but for the sell orders?

**Comment by TheSkynet1337** [comment]
No, my suggestion is to implement a mechanism similar to [bid_strategy.ask_last_balance](https://www.freqtrade.io/en/latest/configuration/#buy-price-without-orderbook-enabled) but for sell orders.
 This would only be used when ask_strategy.use_order_book=false just as bid_strategy.ask_last_balance is only used when bid_strategy.use_order_book=false.
There is no relation to ckeck_depth_of_market.
