### ISSUE TITLE
Better exception handling in exchange retrier

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#3273]
Now the retrier decorator throttles both TemporaryError and DependencyException, then raises same exception after the `count` of iterations. This is not quite correct:
* there is no need to throttle with DependencyException's at all, since these indicate the unrecoverable situations like "No such pair" by its semantics (and that's how this exception is used in the exchange classes)
* so retrier should only throttle with TemporaryError's, silently passing the DependencyException at the top level as it does for OperationalException.
* after `count` of attempts, the retrier should transfer the TemproraryError into the DependencyException, which is to be also raised to the top level. It's not a recoverable error anymore, after `count` of attempts.

It's easy to improve since the usage of TemporaryError is limited to the exchange classes (well, and RPC and worker also checks it in only one place each).

**Comment by xmatthias** [comment]
I would propose to make the exceptions more explicit (i tried this with `StrategyException` - but would drive this further ...).

Introducing a new `ExchangeError` exception (maybe as subclass of DependencyException for now) ... which is raised out of the exchange.
Obviously, there will still be other, more fain-grained exceptions, like `InvalidOrderException` which come out of Exchange - but i guess you get my point.

`DependencyException` right now does not really tell you anything - all it signals is an exception which is "most likely" not critical - without any hint (other than the message) as to what / where it's comming from.
currently, it can come from the exchange, freqtradebot itself - and even from backtesting ...
