### ISSUE TITLE
proper setup docker freqtrade on raspberry pi 4 

### ISSUE THREAD

**Issue by hanswayne23** [freqtrade/freqtrade#3274]
## Step 1: Have you search for this issue before posting it?
Yes
## Step 2: Describe your environment

  * Operating system: raspbian buster lite Kernel version: 4.19
  * Python Version: 2.17.16(`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

I install docker for freqtrade but when i try step by step installation of freqtrade from Docker.pi i got an error.

### Steps to reproduce:

installation for docker

sudo apt update
sudo apt upgrade

curl -sSL https://get.docker.com | sh

sudo usermod -aG docker pi

docker run hello-world

sudo apt-get install -y libffi-dev libssl-dev

sudo apt-get install -y python3 python3-pip

sudo apt-get remove python-configparser

sudo pip3 install docker-compose

setup freqtrade

[ "cross-build-start" ]

apt-get update \
 && apt-get -y install wget curl build-essential libssl-dev libffi-dev \
 && apt-get clean

then this error appeared:

E: Could not open loc file /var/lib/apt/lists/lock -open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)

i don't know if i install docker or freqtrade the wrong way? 

Kindly need help on this one. I just want to setup docker freqtrade on raspberry pi 4 the proper way.

Thanks.

**Comment by hroff-1902** [comment]
sudo for all apt-get's in 
```
apt-get update && apt-get -y install wget curl build-essential libssl-dev libffi-dev && apt-get clean
```
?

**Comment by hanswayne23** [comment]
i followed your advice for sudo for all apt-get and it worked.

but when it comes to creating environment:
sudo mkdir /freqtrade is also worked
but for WORKDIR /freqtrade it resulted to -bash: workdir: command not found

by the way based on the Docker.pi document. from # Install TA-LIB till the end There are lots of words like COPY and RUN.
should i use sudo to replace COPY and RUN in order for me to execute the code in the terminal?

This is my first time to install docker freqtrade on raspberry pi4 so kinda bit struggling to install it from Docker.pi

My apologies for being amateur.

**Comment by hroff-1902** [comment]
where did you get this instruction from?

**Comment by hanswayne23** [comment]
my apologies it should be Dockerfile.pi not Docker.pi. I got it from the main freqtrade github page

https://github.com/freqtrade/freqtrade/blob/develop/Dockerfile.pi

**Comment by hroff-1902** [comment]
it does not contain sudo's and thus assume you are logged as root user

**Comment by xmatthias** [comment]
the Raspberry dockerfile (`Dockerfile.pi`) cannot be built on the raspberry, but must be built on a x86 machine (a regular pc).

Best download one of the prebuilt images from [dockerhub](https://hub.docker.com/r/freqtradeorg/freqtrade) - tags `develop_pi` or `master_pi`.

We're using a cross-build for this as it allows us to build it in CI for users - and because building it on a raspberry takes something between 6 and 10 hours (on a Raspberrypi3 though).

**Comment by hanswayne23** [comment]
i installed docker freqtrade for rapsberry pi 4 from scratch.

from sudo apt update step by step until docker compose.

i also run docker pull command docker pull freqtradeorg/freqtrade

when i run docker images i saw the freqtradeorg/freqtrade

but when i execute docker run freqtradeorg/freqtrade i hit an error:
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by xmatthias** [comment]
well you'll need to edit the docker-compose file to use the "*_pi" tags.

I don't understand why you'd be running apt-get when using docker - it's an either / or - you either use docker - OR you install it using apt / `setup.sh` - i assume you're mixing the 2 install instructions.

**Comment by hanswayne23** [comment]
Can i close this issue then reopen it next time?

im studying the basics of docker for raspberry pi.

never thought it would be this difficult to install docker freqtrade on raspberry pi.

i was easy for me to setup docker freqtrade on ubuntu vps before. But raspberry pi is really difficult 
for me.

I hope there's an easy way to learn this as i tried a lot of method already to install docker freqtrade
for raspberry pi but still kept on having error in the process.

i don't know if i should close these issue for now? 

thanks.

**Comment by hroff-1902** [comment]
if you close it -- you'll be able to reopen
if we close it -- you'll only be able to post new comments in the closed issue

**Comment by xmatthias** [comment]
as mentioned above - open the docker-compose file - and append `_pi` to the end of the line starting with `image:`.

Then run `docker-compose up`  and freqtrade should start (after downloading the image, obviously).


Aslo,, you should follow the docker-compose instructions as you'll most likely need to create the user-data directory (and maybe configuration?) first - but the above is the only thing to get going on a raspberry.

it is not difficult (not even that different) from a regular installation - all you need to do is use a different image.

**Comment by hanswayne23** [comment]
i successfully installed docker freqtrade on my raspberry pi 4

docker freqtrade raspberry pi

curl -sSL https://get.docker.com | sh

sudo usermod -aG docker pi

docker run hello-world

sudo pip3 install docker-compose

mkdir ft_userdata
cd ft_userdata/

curl https://raw.githubusercontent.com/freqtrade/freqtrade/develop/docker-compose.yml -o docker-compose.yml

docker pull freqtradeorg/freqtrade

edit docker-compose.yml file:
image: _pi

docker-compose run --rm freqtrade create-userdir --userdir user_data

docker-compose run --rm freqtrade new-config --config user_data/config.json

thank you for your help on this one.

I hope i did the right thing installing it. I don't know what i still need to study or to understand docker for freqtrade?

if there's something that i need to learn more just let me know.

**Comment by xmatthias** [comment]
well i think installing is the very first step.

after that, you'll need to find a strategy, backtest the strategy, dry-run a strategy - and hopefully, you've found / developed a winning strategy.

**Comment by hroff-1902** [comment]
the description of actions needed for docker install on RPI was added into the docs: #3307

**Comment by xmatthias** [comment]
Since you've succeeded in installing freqtrade via docker on the Raspberry, i'll close this issue.

Thanks for providing your commands, it confirms that it's working by simply adding "_pi" to the image. (The remainder is to install docker - which however is out of scope for the freqtrade documentation).
