### ISSUE TITLE
Documentation is outdated or not all arguments are valid

### ISSUE THREAD

**Issue by MarcelBeining** [freqtrade/freqtrade#3280]
## Step 1: Have you search for this issue before posting it?

yes

## Step 2: Describe your environment

  * Operating system: Windows 10 64bit
  * Python Version: 3.6 (`python -V`)
  * CCXT version: '1.18.64'
  * Branch: Develop
  * Version: '0.17.3'
  
## Step 3: Describe the problem:

I just have cloned the repo, installed the requirements and freqtrade with `pip install -e .` and wanted to create a new data dir and config. According to the [docs](https://www.freqtrade.io/en/latest/utils/#utility-subcommands) I can give these argument to pass is one of (found different docs)
* new-config
* create-userdir
* new-strategy

However, trying these gives me
> freqtrade: error: argument subparser: invalid choice: 'create-userdir' (choose from 'backtesting', 'edge', 'hyperopt')

So either there is something wrong with my installation or the docs are outdated at multiple points.

My question is now how to initialize new user dirs, new configs or new strategies?

**Comment by hroff-1902** [comment]
Version: '0.17.3'
which you stated above is more than one year old.
Update the bot to the actual version if you refer to the docs for the actual version of the bot.

Seems you are using one from Udemy course -- they have their own repository, which is outdated comparing to the main freqtrade. In this case, either switch to our repository or ask creators of the Udemy course for support.

> Please note that the Udemy course has not been created by maintainers / authors / team of freqtrade, but by an independent trader / company not affiliated nor related to this repository (other than using the code) - so for support regarding support questions, please refer to the Udemy comments / questions page - that's where you can get support for that.

**Comment by hroff-1902** [comment]
closing it as the question related to an outdated third-party version
