### ISSUE TITLE
Strategy with Customized Variables

### ISSUE THREAD

**Issue by Andi1990** [freqtrade/freqtrade#3288]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Operating system: Linux Ubuntu 
  * Python Version: 3.6.9
  
## Step 3: Describe the problem:

I would like to write a customized strategy with my own variables and set a buy/sell signal depending on those variables. However, I am encountering the following problems or ambiguities:

- I need to resolve my variables every time a new candle is available (e. g. when ticker_interval is 1h, every hour): Where in the strategy class can I place the code in order to get executed in these intervals? My variables only need information about ohlc-values of the last candles (via shift).

- Is it recommended to save my variables in my own column of the dataframe by just adding new columns similar to the "buy" or "sell" column which is added in the function populate_buy/sell_trend? It seems right, since every row in the ohlc-dataframe resolves to my own variables and hence, those variables change from row to row. I also need to get access to the variables from past intervals and dataframe-rows, respectively. 

- How can I trigger a buy/sell order in the function populate_buy/sell_trend by using my own variables or my own variable in the dataframe? It seems that e.g. (dataframe['close'].shift(1) < dataframe['close'] resolves to an array and not to True/False

- Is it possible to set a stop buy/sell order on the exchange via freqtrade?

I would be very glad if anybody can help me out.

**Comment by hroff-1902** [comment]
> Is it recommended to save my variables in my own column of the dataframe by just adding new columns similar to the "buy" or "sell" column which is added in the function populate_buy/sell_trend?

Exactly. Each indicator is that "variable". Just store the values in a new column and use `.shift()` if you need a value from the previous candle.

The reason is that calculations should normally be vectorized, i.e. on the rows of the dataframe, otherwise, if you keep the value in a class attribute or in a variable at the module level, you won't be able to backtest your strategy, since backtesting runs populate_*() methods from your strategy only once with the dataframe with all historical data for the timerange of backtesting.

**Comment by xmatthias** [comment]
To add to the above point - if you only need the strategy to evaluate when a new candle arrives, then set `process_only_new_candles` to True. 
Freqtrade will then execute all `populate_*` methods only once every candle (right at the beginning).

**Comment by Andi1990** [comment]
Thank you for your fast responses. They helped me a lot.
My variables are now calculated in the function populate_indicators and saved in every row of the dataframe.
The functions populate_buy/sell_trend just check if (dataframe["cust_var"] >= 1). That works pretty good.
Finally I have one open question:
- Is it possible to set a stop buy/sell order on the exchange via freqtrade? In my understanding, when buy signal is True, the algorithm just takes the best ask of the orderbook for buying (when live-mode) or it takes the open-price of the next candle (when backtesting).

**Comment by xmatthias** [comment]
for backtesting, there is no option to configure this.

for real - dry mode - we have a [documentation page](https://www.freqtrade.io/en/latest/configuration/#prices-used-for-orders) explaining the options you got for price selection.

**Comment by xmatthias** [comment]
I will assume this as answered.

Feel free to comment if that's not the case so we can reopen.
