### ISSUE TITLE
I get TypeError: reduce() of empty sequence with no initial value when i run my hyperopt

### ISSUE THREAD

**Issue by ebuka-odih** [freqtrade/freqtrade#3295]
OS: Linux Mint
Python V: 3.7
pip freeze:
```
- [ ] `aiodns==1.1.1
- [ ] aiohttp==3.6.2
- [ ] arrow==0.15.6
- [ ] async-timeout==3.0.1
- [ ] attrs==19.3.0
- [ ] bleach==3.1.5
- [ ] cachetools==4.1.0
- [ ] ccxt==1.27.20
- [ ] certifi==2020.4.5.1
- [ ] cffi==1.14.0
- [ ] chardet==3.0.4
- [ ] click==7.1.2
- [ ] colorama==0.4.3
- [ ] coverage==5.1
- [ ] coveralls==2.0.0
- [ ] cryptography==2.9.2
- [ ] decorator==4.4.2
- [ ] defusedxml==0.6.0
- [ ] docopt==0.6.2
- [ ] entrypoints==0.3
- [ ] filelock==3.0.12
- [ ] flake8==3.7.9
- [ ] flake8-tidy-imports==4.1.0
- [ ] flake8-type-annotations==0.1.0
- [ ] Flask==1.1.2
- [ ] -e git+https://github.com/freqtrade/freqtrade.git@18ec65e05f855967f6f22e5aa280037646932d1f#egg=freqtrade
- [ ] future==0.18.2
- [ ] idna==2.9
- [ ] importlib-metadata==1.6.0
- [ ] ipython-genutils==0.2.0
- [ ] itsdangerous==1.1.0
- [ ] Jinja2==2.11.2
- [ ] joblib==0.14.1
- [ ] jsonschema==3.2.0
- [ ] jupyter-core==4.6.3
- [ ] MarkupSafe==1.1.1
- [ ] mccabe==0.6.1
- [ ] mistune==0.8.4
- [ ] more-itertools==8.2.0
- [ ] multidict==4.7.5
- [ ] mypy==0.770
- [ ] mypy-extensions==0.4.3
- [ ] nbconvert==5.6.1
- [ ] nbformat==5.0.6
- [ ] numpy==1.18.4
- [ ] packaging==20.3
- [ ] pandas==1.0.3
- [ ] pandocfilters==1.4.2
- [ ] plotly==4.6.0
- [ ] pluggy==0.13.1
- [ ] progressbar2==3.51.3
- [ ] prompt-toolkit==3.0.5
- [ ] py==1.8.1
- [ ] py-find-1st==1.1.4
- [ ] pyaml==20.4.0
- [ ] pycares==3.1.1
- [ ] pycodestyle==2.5.0
- [ ] pycoingecko==1.2.0
- [ ] pycparser==2.20
- [ ] pyflakes==2.1.1
- [ ] Pygments==2.6.1
- [ ] pyparsing==2.4.7
- [ ] pyrsistent==0.16.0
- [ ] pytest==5.4.1
- [ ] pytest-asyncio==0.12.0
- [ ] pytest-cov==2.8.1
- [ ] pytest-mock==3.1.0
- [ ] pytest-random-order==1.0.4
- [ ] python-dateutil==2.8.1
- [ ] python-rapidjson==0.9.1
- [ ] python-telegram-bot==12.7
- [ ] python-utils==2.4.0
- [ ] pytz==2020.1
- [ ] PyYAML==5.3.1
- [ ] questionary==1.5.2
- [ ] requests==2.23.0
- [ ] retrying==1.3.3
- [ ] scikit-learn==0.22.2.post1
- [ ] scikit-optimize==0.7.4
- [ ] scipy==1.4.1
- [ ] sdnotify==0.3.2
- [ ] six==1.14.0
- [ ] SQLAlchemy==1.3.16
- [ ] TA-Lib==0.4.17
- [ ] tabulate==0.8.7
- [ ] testpath==0.4.4
- [ ] tornado==6.0.4
- [ ] traitlets==4.3.3
- [ ] typed-ast==1.4.1
- [ ] typing-extensions==3.7.4.2
- [ ] urllib3==1.25.9
- [ ] wcwidth==0.1.9
- [ ] webencodings==0.5.1
- [ ] Werkzeug==1.0.1
- [ ] wrapt==1.12.1
- [ ] yarl==1.1.0
- [ ] zipp==3.1.0
```

git branch: develop
last commit ID: 18ec65e05f855967f6f22e5aa280037646932d1f

When i try to run my hyperopt it brought out the first result and then crashed showing an error of 
`TypeError: reduce() of empty sequence with no initial value`
from the log i think is referring to my hyperopt line 127 on my sell populate, here is the code

`   def sell_strategy_generator(params: Dict[str, Any]) -> Callable:
        """
        Define the sell strategy parameters to be used by hyperopt
        """
        def populate_sell_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Sell strategy Hyperopt will build and use
            """
            # print(params)
            conditions = []
            # GUARDS AND TRENDS
            if 'sell-rsi-enabled' in params and params['sell-rsi-enabled']:
                conditions.append(dataframe['rsi'] > params['sell-rsi-value'])

            # TRIGGERS
            if 'sell-trigger' in params:
                if params['sell-trigger'] == 'sell-bb_lower1':
                    conditions.append(dataframe['close'] > dataframe['bb_lowerband1'])

                if params['sell-trigger'] == 'sell-bb_middle1':
                    conditions.append(dataframe['close'] > dataframe['bb_middleband1'])

                if params['sell-trigger'] == 'sell-bb_upper1':
                    conditions.append(dataframe['close'] > dataframe['bb_upperband1'])

            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
                'sell'] = 1

            return dataframe

        return populate_sell_trend`

**Comment by hroff-1902** [comment]
I marked it as duplicated, see for example: https://github.com/freqtrade/freqtrade/issues/1932

We fixed this problem in the hyperopt samples an year ago, and you are using a hyperopt file which is even older and does not contain the fix.

In short, add `if conditions:`
```
            if conditions:
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'sell'] = 1
```

Have a look at the actual hyperopt samples. If you do not have under `user_data` dir, populate samples into it with the command `freqtrade create-userdir --userdir user_data`.

Also note, that currently you may (or even should) create new strategy/hyperopt files from the actual templates with the `new-strategy`/`new-hyperopt` subcommands -- you'll obtain actual samples with all latest features. Please have a look at the description of these commands in the docs.

**Comment by ebuka-odih** [comment]
thank you, i am running my custom hyperopt now.
