### ISSUE TITLE
pytestError

### ISSUE THREAD

**Issue by AronWater** [freqtrade/freqtrade#3298]
`if run pytest tests`

```
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\optimize\test_hyperopt.py:19: in <module>
    from freqtrade.optimize.default_hyperopt import DefaultHyperOpt
freqtrade\optimize\default_hyperopt.py:8: in <module>
    from skopt.space import Categorical, Dimension, Integer
E   ModuleNotFoundError: No module named 'skopt'
```

**Comment by xmatthias** [comment]
First of all, please fill out the issue template so we know which version you're on.

Then - you should follow the [developer guide](https://www.freqtrade.io/en/latest/developer/#developer-setup) - installing all dependencies (`pip install -r requirements-dev.txt` - or selecting Y in the setup.sh script (which has the same effect).

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment if you still encounter problmes running the tests.
