### ISSUE TITLE
I want to know how i can change the Starting capital of my dry run

### ISSUE THREAD

**Issue by ebuka-odih** [freqtrade/freqtrade#3299]
I found out that my Starting capital is 1000 BTC when am running on dry mood.
please i want to know if there is any way how i can change it to something else.

**Comment by xmatthias** [comment]
by changing the value of `dry_run_wallet`.

Please, before posting an issue, try to find the answer yourself in [the documentation](https://www.freqtrade.io/en/latest/configuration/). 

We try hard to keep the documentation up-todate and complete to avoid such questions - which can be found in the documentation easily.
Thanks.
