### ISSUE TITLE
Add columns legends for exported trades in documentation

### ISSUE THREAD

**Issue by vxg20** [freqtrade/freqtrade#3302]
Currently there does not seem to be any explanations on the columns of exported trades in the documentation. I only managed to get the columns names after using load_backtest_data (which is actually explained in a separate section in the documentation that is not about trades exporting, so a bit difficult to make the connection). Could we please add a bit more explanations on each of the columns of the exported trades json file ? thanks

**Comment by xmatthias** [comment]
I've labeled this as "good first issue" as i think it's a very simple task to document this (look it up in the code, write some documentation) - but it's a very good way to get started contributing and get familiar with the freqtrade code structure.
