### ISSUE TITLE
[Question]Backtesting multi strategies

### ISSUE THREAD

**Issue by Pascal66** [freqtrade/freqtrade#3305]
##  Describe the problem:
Testing with strategy-list need to enter all the name of a strategies.

Can we have for example an 'all' shortcut or a wildcard for only some strategy name ?

Maybe sorting result for that too

**Comment by hroff-1902** [comment]
you can automate fetching the list of strategies with
`freqtrade list-strategies -1`,

then in the backtesting (assume you do not have ones that fail): 
```
freqtrade backtesting ... --strategy-list `freqtrade list-strategies -1`
```
or even with grep:
```
freqtrade backtesting ... --strategy-list `freqtrade list-strategies -1|grep 'SelectionPhrase'`
```
or bash wildchar selection

**Comment by xmatthias** [comment]
I don't think that an `--all` shortcut would be very useful - it's very rare that you're going to compare ALL strategies - but only the ones you see / feel interresting, have matching timeframes etc.

So you'd want `--all --except ABC` - but then it becomes complicated very soon.

**Comment by Pascal66** [comment]
@xmatthias it's to automate things when starting to use freqtrade, and send the best results to hyperopt. And I generaly dont do thing  because I 'feel' it interesseting :)
I agree with you, and the linux way solution of @hroff-1902 is the best one

**Comment by hroff-1902** [comment]
^^
`freqtrade list-strategies -1` needs an extra cli option to list only "good" strategies that can load...
