### ISSUE TITLE
Hyperopt results

### ISSUE THREAD

**Issue by Pascal66** [freqtrade/freqtrade#3306]
### Steps to reproduce:

  `~/freqtrade$ freqtrade hyperopt -e 150 --spaces all -c config_pp.json --strategy Strategy003 --hyperopt AdvancedSampleHyperOpt`
  
### Observed Results:
  * What happened?
```
2020-05-14 13:09:14,603 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 12
+--------+---------+----------+--------------+------------------------------+----------------+-------------+
|   Best |   Epoch |   Trades |   Avg profit |                       Profit |   Avg duration |   Objective |
|--------+---------+----------+--------------+------------------------------+----------------+-------------|
| * Best |   1/150 |        1 |      -16.06% |   -0.16099617 ETH  (-16.06%) |     42,480.0 m |     2.31196 |
| * Best |   3/150 |        5 |       -0.41% |   -0.02061846 ETH   (-2.06%) |        737.0 m |     2.26421 |
| * Best |   6/150 |       78 |       -0.33% |   -0.25918647 ETH  (-25.85%) |        197.0 m |      2.1865 |
| * Best |   7/150 |       39 |       -0.45% |   -0.17570336 ETH  (-17.53%) |        206.0 m |     2.18131 |
| * Best |   8/150 |       26 |       -0.34% |   -0.08886621 ETH   (-8.86%) |        161.2 m |     2.09611 |
| * Best |   9/150 |        3 |       -0.05% |   -0.00144159 ETH   (-0.14%) |        138.3 m |     2.04282 |
|   Best |  63/150 |        3 |        0.03% |    0.00079388 ETH    (0.08%) |        136.7 m |     2.03985 |
|   Best |  80/150 |        9 |       -0.33% |   -0.02944464 ETH   (-2.94%) |        121.7 m |     2.02829 |
|   Best | 133/150 |        4 |       -0.17% |   -0.00669177 ETH   (-0.67%) |        126.2 m |     2.02818 |
 [Epoch 150 of 150 (100%)] ||                                                                                                           | [Time:  0:05:29, Elapsed Time: 0:05:29]
2020-05-14 13:14:49,051 - freqtrade.optimize.hyperopt - INFO - 150 epochs saved to '/home/user/freqtrade/user_data/hyperopt_results/hyperopt_results.pickle'.

Best result:

   133/150:      4 trades. Avg profit  -0.17%. Total profit -0.00669177 ETH (  -0.67Σ%). Avg duration 126.2 min. Objective: 2.02818
```

  * What did you expect to happen?
 Best result seems :  63/150

PS : There's a typo in **`(  -0.67Σ%)`**

**Comment by xmatthias** [comment]
63/150 is the best in regards to profit - however what's evaluated is the "objective" column, which is slightly lower for 133/150.

Now freqtrade has [several loss-functions](https://www.freqtrade.io/en/latest/hyperopt/#loss-functions) available, so by changing these, you'll also get other results (each Loss-function optimizes for something else).

The default optimizes on mostly short trades (which is often not the best criteria) - but we have others to choose from.
`ProfitOnly` would use 63/150 in the above case ... but it'll have other drawbacks (like using a very wide stoploss).

Best read through the documentation linked above - it'll explain what each of them does optimize for.

**Comment by Pascal66** [comment]
Thank you. I've read the doc, but it not include a full output, just the best result. That's why I asked.

**Comment by hroff-1902** [comment]
should be added into FAQ

**Comment by xmatthias** [comment]
well you can always get to the best result with `freqtrade show-hyperopt ...`  [doc](https://www.freqtrade.io/en/latest/utils/#show-details-of-hyperopt-results)

**Comment by Pascal66** [comment]
Got it
