### ISSUE TITLE
config override strategy

### ISSUE THREAD

**Issue by Pascal66** [freqtrade/freqtrade#3310]
Let starting from a config.json and a strategy.

First: I hyperopt this stragegy,
Second: I modifiy it in accordance of the result i want
(Third: backtrace too verify)

Fourth : launching trade with the modified strategy is OVERRIDED by not modified config.

So, my question is, why not override the initial config, with the modified strategy ?

**Comment by xmatthias** [comment]
I'm sorry, but it's not clear what behavior you're experiencing (nor what you would be expecting).

**Comment by Pascal66** [comment]
What I see :  
Let my config.json as it it.
Modify my strategy.
Launching trade
strategy is overrided by config
```
2020-05-15 08:58:40,167 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stoploss' with value in config file: -0.1.
2020-05-15 08:58:40,168 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop' with value in config file: False.
2020-05-15 08:58:40,169 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop_positive' with value in config file: 0.005.
2020-05-15 08:58:40,169 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_stop_positive_offset' with value in config file: 0.0051.
2020-05-15 08:58:40,170 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'trailing_only_offset_is_reached' with value in config file: False.
2
```
What I expect : 
strategy override config

**Comment by xmatthias** [comment]
it's expected behaviour as [documented](https://www.freqtrade.io/en/latest/configuration/#configuration-parameters).

CLI overrides config and strategy, config overrides strategy - and strategy is last.

If you want the strategy-values to apply, best remove these values from the configuration.

**Comment by hroff-1902** [comment]
maybe it should be said more clear and explicit in the docs: when you transfer the values found by hyperopt into the docs, you may need to adjust values in config or even change cli options if they are used and override corresponding strategy settings.

**Comment by Pascal66** [comment]
That's what I do before asking.
First, removing  params in config one by one
Second, until: 
```
2020-05-15 08:56:02,492 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-05-15 08:56:02,509 - freqtrade.configuration.config_validation - CRITICAL - Invalid configuration. See config.json.example.
```

What I expect : 
No removing any config params, override them by strategy
Not the inverse.

Strategies move all the time (because of market trend, or else)
config stay the same.

**Comment by xmatthias** [comment]
then please remove the configurations that you override in the strategy (most likely that's ROI and the stoploss parameters).

As said, it's documented this way, and expected this way - and it works perfectly fine by removing the overridden parameters from the configuration (but it assumes all removed parameters are available in the strategy).

the configuration page mentions every parameter that can be overridden by the strategy - but most must be present in either configuration or strategy.

----

To explain WHY it is this way:
You may want to try different strategies - which have different settings (like different stoplosses). By allowing to override these from the configuration, you can keep the same configuration and try different strategies without increasing risk (wider stoploss).

**Comment by Pascal66** [comment]
Ok @xmatthias different point of view.

For me: config is my way.
I can change it with differents strategy

**Comment by xmatthias** [comment]
To be honest, i do the same thing - i remove these settings from the configuration in most instances.

However i would not want the process changed, as i can ensure  (via the configuration) that the desired values are used.

**Comment by Pascal66** [comment]
It's ok, for me it's counterproductive.
(as i can change strategy every day, and wish my global config adapted to it)

**Comment by hroff-1902** [comment]
maybe not removed, but commented out?

**Comment by Pascal66** [comment]
As a 'reload-config' exist that's solve my question :)
