### ISSUE TITLE
How to run freqtrade on VPS

### ISSUE THREAD

**Issue by ebuka-odih** [freqtrade/freqtrade#3311]
Please, i know this question is not what I am supposed to ask here but i believe someone might have experienced or might have faced the same thing.
i am trying to know how i can be running freqtrade on a Linux vps where it won't get to stop anytime i turn off my computer, the issue is that i don't know how to go about it. Please any help will be appreciated.

**Comment by hroff-1902** [comment]
copied my posts from Slack, hope it explains the possibilities well:

>well, ways to run the bot:
>1. Just in the command line/terminal; Pros: easiest way for noobs; Contras: it will stop when you close the terminal or accidentally have the connection closed (if running in a ssh session/terminal on a remote VPS). Tips: do not forget to activate venv and go to proper directory. Summary: easiest way for complete noobs.
>2. Same as 1, but under screen/tmux (read about those utils). Pros: screen/tmux keeps the terminal session when the terminal is closed/connection lost. Contras: you need to educate yourself how to use these utils and how to switch to a previously opened screen/tmux session.
(xmatthias added:
biggest contra for both of the above: manual intervention after a server reboot (you do patch your servers, don't you) :smile:)
>3. Run in background with & or bg command. Contras: stupid way, in my opinion.
>4. Run in a docker containter. Pros: one of the smoothest and cleverest ways. @xmatthias as a guru of docker can add more meat here; Contras: you need to get basic knowledge of docker (edited) 
>5. Run as a system service. Pros: a native way for unix-olders like myself; Contras: you need to know what you are doing when you configure them as system service(s) and do not ask stupid questions...
>6. ???

Summary: try to install and run in the docker container.

**Comment by ebuka-odih** [comment]
Please, how can i read the full article

**Comment by hroff-1902** [comment]
about installing on docker? there is a separate chapter in the docs about it: https://www.freqtrade.io/en/latest/docker/

**Comment by ebuka-odih** [comment]
here is the error am having when i try to run the command on freqtrade

`Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3089, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'docker-compose==1.17.1' distribution was not found and is required by the application
`

**Comment by xmatthias** [comment]
it seems like your docker-compose installation is broken.
Best refer to the docker / docker compose repositories / help-channels for help regarding this.

**Comment by ebuka-odih** [comment]
> it seems like your docker-compose installation is broken (i suspect you installed it via pip - but that's not the correct way to install docker-compose).
> 
> Best refer to the docker / docker compose repositories / help-channels for help regarding this.

i just uninstalled the previous one and installed it the proper way but am still getting the error.

**Comment by xmatthias** [comment]
The error you are getting above is not a freqtrade specific error, but an error related to your docker-compose installation.

Please look for help in the appropriate channels (docker support forums, google).

Supporting erroneous docker installations is not something we can or will help with.

thanks for your understanding.

**Comment by dragon-master-5892** [comment]
Please run your bot on ubuntu with **nohup**  like this:

`nohup freqtrade trade --config config.json --strategy EMAPriceCrossoverWithThreshold`

**Comment by xmatthias** [comment]
I'd not recommend using nohup. You'll have difficulty getting back at the logs ... using docker-compose, systemd (service) or tmux or screen are all better ways than using nohup.
