### ISSUE TITLE
How to run freqtrade on VPS

### ISSUE THREAD

**Issue by ebuka-odih** [freqtrade/freqtrade#3314]
please, this question is the continuation of  #3311
i have installed docker and followed the instruction on their doc, i have even run some freqtrade command to see how it works, now how do i move it on my vps?

**Comment by xmatthias** [comment]
Running freqtrade on a VPS is no different than running it on your pc, other than that you SSH into the VPS first.

Please be specific in asking questions. 
We have very extensive [docs](https://www.freqtrade.io/en/latest/). 
Please read them before asking questions that are answered already there.

Installation is covered quite deeply in the documentation - and as mentioned above - a VPS is just someone elses pc in the cloud - so the install instructions will work perfectly fine.


I would also reccomend you learn about servers (how to protect a server from attackers) - how to manage a server, ... - to make sure you're not up for nasty surprises.

**Comment by hroff-1902** [comment]
man, we'll ban you for such questions...
