### ISSUE TITLE
How can you specify time as a sell trigger?

### ISSUE THREAD

**Issue by leeu3581** [freqtrade/freqtrade#3316]
How can you trigger a sell after a set amount of time of 1 day after buying regardless of the outcome of the trade?

I tried df['buy'].shift inside the populate_sell_trend method, but it does not seem to trigger the sell and ends up force selling. Since there are also multiple buy triggers, but limited number of trades, the bot won't be able to buy after every buy == 1. Is there a way to specify this?

Thank you!

**Comment by hroff-1902** [comment]
you can you minimal_roi for this.

although normally minimal_roi is intended for taking profit, it also accepts negative values (where -1.0 means the price dropping -100%, i.e. to the zero values)

so you can set it as
```
    minimal_roi = {
        "90": -1.0,
        "60": 0.01,
        "30": 0.02,
        "0": 0.04
    }
```
-- it will sell the pair in 90 min at every price.

(should be added into the docs)

**Comment by leeu3581** [comment]
Thank you!

**Comment by leeu3581** [comment]
I tried the config
minimal_roi = {
        "90": -1.0
}
And when I run it in backtesting mode, it keeps selling at -99.90%. ( 1% of the original price). Minimal roi is definitely triggering the sell, but it seems to consistently sell at -99.9% for some reason. I plot the charts and the sell is happening not on the candlesticks as you would expect but towards the x axis. Please see below. 

<img width="1143" alt="Screen Shot 2020-05-17 at 14 48 43" src="https://user-images.githubusercontent.com/15639564/82136892-9a7cdf00-984d-11ea-8cf6-c3bbb4a48f7b.png">

Is there additional config that needs to be added when using minimal roi to trigger a time based sell?

Thank you.

**Comment by xmatthias** [comment]
Please specify the version you're using (which you should have done when opening the issue)...

**Comment by leeu3581** [comment]
Here is the version information I'm using:

freqtrade 0.17.3
  * Operating system: MacOS Sierra
  * Python Version: Python 3.7.7
  * CCXT version: ccxt==1.27.58
  * Branch: Develop

**Comment by hroff-1902** [comment]
> freqtrade 0.17.3

> Please note that the udemy course has not been created by maintainers / authors / team of freqtrade, but by an independent trader / company not afiliated nor related to this repository (other than using the code) - so for support regarding support questions, please refer to the Udemy comments / questions page - that's where you can get support for that.

**Comment by leeu3581** [comment]
Perfect, this solved the issue. Thanks a lot!
