### ISSUE TITLE
Allow freqtrade to trade in real with zero fee

### ISSUE THREAD

**Issue by sanitariu** [freqtrade/freqtrade#3335]
## Step 1: Have you search for this issue before posting it?
Yes

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```

Allow freqtrade to trade in real with zero fee. No option to setup that except with backtesting.

freqtrade: error: unrecognized arguments: --fee 0.00

**Comment by xmatthias** [comment]
Freqtrade will use the fees as the exchange reports and charges them (for live mode).

Explicitly setting `--fee` does not make sense - it would seem you got a very good strategy - but in reality you're not considering fees. Almost any strategy is profitable if fees can be neglected, many are highly negative once fees need to be considered.

While setting `--fee 0.00` would be nice - the exchange will not agree with that and charge you fees anyway.


Personally, i'd also recommend NOT to touch this setting for backtesting, as it can seem like your strategy is profitable while it's not.
It's intended to be used in very specific scenarios like Binance, when fees are paid in BNB (must be configured ON the exchange) - and incur a slight rebate (0.0075 intead of 0.01).

However, i know no exchange that has 0 fees - so this option would be higly misleading for any live mode.

**Comment by sanitariu** [comment]
Hi,
Actually there are other exchanges where you do not pay fees or it is already paid like kraken fee credits on Kraken. So you already have 2 exchanges from supported ones where you can actually have ZERO fee. In my particular case i have over 30 thousands kraken fee credits. They are automatically reduced from my trades and actually i have zero fee which i can not use in trade algo.
The same situation is on binance where i have bnb credits too. I think setting fee number in the config file is good thing to do.

**Comment by hroff-1902** [comment]
I also think this can be a good enhancement, which would allow to obtain the dry-run results more close to live results in the case when real fee is reduced for the user on exchange for some reasons

**Comment by xmatthias** [comment]
if you pay fees in BNB or FEE, the trades are not for free - but you pay for them in a different currency.

Yes, the fee will be reduced in these 2 cases - but you can also sell all your BNB - so it IS in fact capital lost - so it MUST be factored into the calculation.

**Comment by hroff-1902** [comment]
some exchanges pay to market makers, so negative value should be used. And this can depend on the volume produced by the trader's, so no way to fetch the correct value for dry-run except setting it manually to the expected value in config and/or in cli option to get the correct dry-run results.

**Comment by sanitariu** [comment]
Yes i know that. Actually at Kraken you can not sell kfees. They can only be used for trading. Actually if i am able to set zero fee at kraken my bot will place better then all others ... because it will buy early and sell early. If there is no such setting in the config file I can live with it and will touch the code .... like hard coding that fee. I just think that more good is to be able to set it via config file ..... anyway we can backtest with some manual fee so why not trade with the same manual fee :)

**Comment by hroff-1902** [comment]
I assume you mean "why not paper trade (dry-run) with the same manual fee", for live trading it's impossible

**Comment by sanitariu** [comment]
I did my backtesting with fee 0.00 and was planing to run live trade when i saw that this fee i can not set except if i touch kraken exchange code. Then i think why we have the option to test with different fees when it is impossible to use the same fee in real trading. Then i checked again my kfee credits and bnb credits and i think why i can not use freqtrade bot advantage with zero fee against other players when i have the credits already in my account...... Anyway touching the code via hardcoded 0.00 fee for kraken seems better. When i do it i will post solution for others who want to use it.

**Comment by hroff-1902** [comment]
"why i can not use freqtrade bot advantage with zero fee"
-- pardon me, which "advantage" you are talking about? Do you really think that if you set `--fee 0.0` for real trading, the exchange won't charge fee from you?

**Comment by xmatthias** [comment]
letme be clear - i can think of this as an acceptable solution for dry-run (assuming you know how high your final fees will be) - but for live trading (where trades are executed on the exchange) this is a solution that will only cost users money.

Also - it may seem simple to apply (patching `get_fee()`) - but you'll discover that in real mode this will not work as fees are extracted from the executed trades, so a solution for that will not be as easy.


for KFEE - you cannot sell them now (you could not sell BNB at the beginning either) - but i expect it's very well possible that it'll be possible to sell them in the future.

**Comment by sanitariu** [comment]
Ok i see this will be hard to be coded.
About - "why i can not use freqtrade bot advantage with zero fee" - Yes this is advantage for me because I have already KFEE credits bought and if i am possible to set zero fee my bot will enter in trade early then others because fee will be zero and of course will exit trade early than others because i have zero fee. Yes this is advantage over other players also in binance. Some fees are based on amount of trade or additional discounts like bnb and i see now this as hard to be implemented do not take me wrong.....

**Comment by hroff-1902** [comment]
I do not understand what you are talking about, to be honest...

In live trading, the fee is set by exchange, for each order (buy or sell, according to the order type and fee schedule applicable for your account) and they are set by the exchange independently of any assumptions the bot or your strategies make about fee. If you have zero fee set up by exchange for your orders, they will be zero independently of what fee is hardcoded or manually set in the bot / ccxt library / cli option, whatever. You'll be taken anyway the amount of fee exactly how exchange calculates it internally, zero, positive or negative.

For dry-run, yes, this option can be useful, while for live trading it should be ignored or lead to an error if set.

**Comment by sanitariu** [comment]
Hello,
Lets close this because seems like you do not understand what i am talking about..... Lets say someone gift me 100 000 kfee. This is equal to approx $1000. Now i can trade at Kraken and everytime kraken will take 0.20 maker/taker from my kfee NOT from my real usd/eur or crypto balance ! Kfee is already paid and it is there. Now if freqtrade calculates zero fee it will enter/exit trades early than other traders i hope you understand this. Finally this is advantage over other traders because freqtrade will feel the market 0.20 maker/taker fee early. Yes there is fee but it is already paid. The same can happen at binance. Yes seems like this is hard to be implemented so lets close it or leave it for better times :)

**Comment by hroff-1902** [comment]
"Now if freqtrade calculates zero fee it will enter/exit trades early than other traders i hope you understand this." -- no, I don't...

**Comment by sanitariu** [comment]
For example i can calculate very little profit even the fee by itself as a profit to return back my KFEEs ($1000) :) Doing many trades like this will transfer my kfee into real usd/eur. This was just an example. As i said there is a fee ! If it is kfee or bnb it is already paid and is there. We must use it somehow.
Also backtesting at kraken with manually specified fee does not work correctly. Seems like there is something wrong with fee calculation. For example:

freqtrade backtesting -c config-kraken.json -s Simple --fee 0.000 
gives the same result as
freqtrade backtesting -c config-kraken.json -s Simple --fee 0.002
but it is different from 
freqtrade backtesting -c config-kraken.json -s Simple --fee 0.001.
So command --fee 0.000 is not taken in calculations ... maybe because it is 0. --fee 0.00 just takes the fee from the exchange. Testing my strategy with zero fee is impossible. Only solution is fee no to be zero. Working example is like --fee 0.0000001 or more zeroes.

**Comment by hroff-1902** [comment]
"Doing many trades like this will transfer my kfee into real usd/eur." -- and what prevents you know from "returning" kfee this way now? Exchange will charge your fee using kfee in exactly same way, as if would --fee option exist and be set to some (zero or non-zero) value. This option for live trading would have no effect into real fee calculation and charging made by exchange. I just do not understand how will it (or should it) affect real trades, in the live trade mode.

**Comment by xmatthias** [comment]
I think the point you're trying to make has been understood.

However you're wrong. Consider your account balance (all assets combined on the exchange) is 1000$.
It's split evenly between BNB and USDT  (so 500$ USDT and 500$ worth of BNB).

You now start trading USDT with BNB fees enabled - so your USDT will slowly raise - and BNB will fall.

Say after 2 days you now have 505$ USDT - and 490$ BNB. 
If you take your calculation of 0 Fees, then you've made 5$ Profit - but in reality youre at -5$ on your total account balance. 

It may feel like you're paying 0 fees if you only look at the USDT balance - but looking at the overall balance you're still down - and this is where you're wrong. It'll therefore not give you an advantage over other traders - but a disatvantage, because you're slowly loosing without even noticing this.

The same thing happens with KFEE. I understand you can't use them to trade at the moment - but it still counts towards the total balance and therefore the trades are not free.

**Comment by sanitariu** [comment]
Hi,
I will try to explain it more good why i have advantage if I already bought kfee.
Lets say my bot and your bot play same strategy on same exchange and same pair. Lets say that fee is 1%. We setup both bots to sell at 1% earnings. Your bot actually will sell when it reaches 2%.
My bot will sell exactly at 1%. Lets just suppose that price of that pair moves between 0 - 1.9% !
Your bot will actually make 0 sells or you can stay in very long position while my bot will do many sells. Yes if we calculate that kfee costs money too i will be zero earnings in reality. But if i setup my bot to play with 1.1% earnings and have my kfees already bought or gifted from someone in reality i will win 0.1% from each trade and i can do thousands while your bot will never do the trade because it can not reach 2%. These are just basic examples .... yes there are many ifs but it is not so complicated to happen. Difference here is that my fee is already paid i have already lost it while your the bot for your trades still calculates it and will not go in trade without the positive result.
I hope i explained it well :) I am just trying to help make freqtrade the best and thank you , hroff-1902 and others for the coding !

**Comment by xmatthias** [comment]
You could also just set your ROI to a lower number and achieve exactly the same result, so for me, you're still not faster by any means - you're just using a strategy that's configured slightly differently (which is `original ROI - fee * 2`).

**Comment by sanitariu** [comment]
Thanks this looks promising !
