### ISSUE TITLE
Edge not producing any data

### ISSUE THREAD

**Issue by ebuka-odih** [freqtrade/freqtrade#3337]
After setting up my edge, i ran the command only for it to bring out an empty table showing no data but i have downloaded data on my data folder. why is this?

**Comment by hroff-1902** [comment]
paste full output along with the command and pls fill the fields of the issue template

**Comment by ebuka-odih** [comment]
OS: Linux
Python Version: 3.7
pip freeze: 
`aiodns==1.1.1
aiohttp==3.6.2
arrow==0.15.6
async-timeout==3.0.1
attrs==19.3.0
bleach==3.1.5
cachetools==4.1.0
ccxt==1.27.20
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
click==7.1.2
colorama==0.4.3
coverage==5.1
coveralls==2.0.0
cryptography==2.9.2
decorator==4.4.2
defusedxml==0.6.0
docopt==0.6.2
entrypoints==0.3
filelock==3.0.12
flake8==3.7.9
flake8-tidy-imports==4.1.0
flake8-type-annotations==0.1.0
Flask==1.1.2
-e git+https://github.com/freqtrade/freqtrade.git@18ec65e05f855967f6f22e5aa280037646932d1f#egg=freqtrade
future==0.18.2
idna==2.9
importlib-metadata==1.6.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
Jinja2==2.11.2
joblib==0.14.1
jsonschema==3.2.0
jupyter-core==4.6.3
MarkupSafe==1.1.1
mccabe==0.6.1
mistune==0.8.4
more-itertools==8.2.0
multidict==4.7.5
mypy==0.770
mypy-extensions==0.4.3
nbconvert==5.6.1
nbformat==5.0.6
numpy==1.18.4
packaging==20.3
pandas==1.0.3
pandocfilters==1.4.2
plotly==4.6.0
pluggy==0.13.1
progressbar2==3.51.3
prompt-toolkit==3.0.5
py==1.8.1
py-find-1st==1.1.4
pyaml==20.4.0
pycares==3.1.1
pycodestyle==2.5.0
pycoingecko==1.2.0
pycparser==2.20
pyflakes==2.1.1
Pygments==2.6.1
pyparsing==2.4.7
pyrsistent==0.16.0
pytest==5.4.1
pytest-asyncio==0.12.0
pytest-cov==2.8.1
pytest-mock==3.1.0
pytest-random-order==1.0.4
python-dateutil==2.8.1
python-rapidjson==0.9.1
python-telegram-bot==12.7
python-utils==2.4.0
pytz==2020.1
PyYAML==5.3.1
questionary==1.5.2
requests==2.23.0
retrying==1.3.3
scikit-learn==0.22.2.post1
scikit-optimize==0.7.4
scipy==1.4.1
sdnotify==0.3.2
six==1.14.0
SQLAlchemy==1.3.16
TA-Lib==0.4.17
tabulate==0.8.7
testpath==0.4.4
tornado==6.0.4
traitlets==4.3.3
typed-ast==1.4.1
typing-extensions==3.7.4.2
urllib3==1.25.9
wcwidth==0.1.9
webencodings==0.5.1
Werkzeug==1.0.1
wrapt==1.12.1
yarl==1.1.0
zipp==3.1.0
`
git branch: Master
git last commit ID: 66175e560df9f4285816b8ba37f2bd4368f268fc

this is the command i used `freqtrade edge -s BBRSI`

here is my output
![image](https://user-images.githubusercontent.com/46707159/82252686-5e2da980-9947-11ea-9a09-6d84fd98edf8.png)

**Comment by hroff-1902** [comment]
Which version are you using?
`freqtrade -V`

**Comment by ebuka-odih** [comment]
freqtrade develop-66175e5

**Comment by hroff-1902** [comment]
cannot be, you wrote "git branch: Master" above

**Comment by ebuka-odih** [comment]
> cannot be, you wrote "git branch: Master" above

these are my last few commands
![image](https://user-images.githubusercontent.com/46707159/82253087-2e32d600-9948-11ea-9948-7e7cd460376e.png)

**Comment by hroff-1902** [comment]
you have fetched the master branch, but did not install freqtrade using it, and seems you are still using the old version

**Comment by hroff-1902** [comment]
I cannot find "66175e5" in our commits

**Comment by ebuka-odih** [comment]
> you have fetched the master branch, but did not install freqtrade using it, and seems you are still using the old version

no i am not, i downloaded it according to the doc

**Comment by hroff-1902** [comment]
but have you installed it, the new version, after you fetched (downloaded) the content from git?

**Comment by ebuka-odih** [comment]
> but have you installed it, the new version, after you fetched (downloaded) the content from git?

after i installed ta-lib, i activated my env and clone freqtrade from git and i used the command 
`python3 -m pip install -e .` to install it.

**Comment by hroff-1902** [comment]
you might be doing it in another venv or outside of venv...

pls update the bot first so that it clearly show either actual master or actual develop.
I have no idea which version you are using, this commit is not from our repository.

If it's hard for you, I can suggest you archiving you custom stuff from user_data dir, cleaning the installation dir completely and installing again from scratches, to get the actual installation.

**Comment by ebuka-odih** [comment]
> you might be doing it in another venv or outside of venv...
> 
> pls update the bot first so that it clearly show either actual master or actual develop.
> I have no idea which version you are using, this commit is not from our repository.
> 
> If it's hard for you, I can suggest you archiving you custom stuff from user_data dir, cleaning the installation dir completely and installing again from scratches, to get the actual installation

okay, i will do that, thank u

**Comment by hroff-1902** [comment]
why don't you use the Slack channel first before issuing here?

**Comment by ebuka-odih** [comment]
> why don't you use the Slack channel first before issuing here?

i don't have the link, i would prefer there. thank you

**Comment by hroff-1902** [comment]
https://github.com/freqtrade/freqtrade#help--slack
