### ISSUE TITLE
Question about an alert system

### ISSUE THREAD

**Issue by dimadude101** [freqtrade/freqtrade#3338]
Question about Freqtrade - does anyone know if Freqtrade offer an alert system (just send alerts on Telegram when a particular condition has been met?

**Comment by hroff-1902** [comment]
you can run freqtrade in dry-run -- the bot won't execute real orders on exchange and send messages to the telegram bot when it simulates buy and sell orders

**Comment by xmatthias** [comment]
I'll close this as i think the question was answered - and dry-run does offer this (kindof).

It'll even do more for you - and simulate the results - so you'll know if the signals did work out or not.
Although freqtrade has not been made for this ( but for doing the trading automatically) - it is one way to run Freqtrade.
