### ISSUE TITLE
How to use API

### ISSUE THREAD

**Issue by akbardwi** [freqtrade/freqtrade#3340]
Hello i will connect the bot from my apps to control bot, but i get the respon "error": "Unauthorized"
Can you help me?

**Comment by xmatthias** [comment]
It's quite unclear what you are trying to do and where you encounter the error.

**Comment by Pascal66** [comment]
@akbardwi Use Authorisation Basic Base64 in your POST/GET headers

**Comment by xmatthias** [comment]
We do also have a [documentation](https://www.freqtrade.io/en/latest/rest-api/#advanced-api-usage-using-jwt-tokens) with curl examples showing how basic authentication works.

When using the API: Please make sure to read the security warning at the top to be aware and know about the security risks.

**Comment by hroff-1902** [comment]
closing as the question was answered
