### ISSUE TITLE
Freqtrade plot-profit crash

### ISSUE THREAD

**Issue by steffenix** [freqtrade/freqtrade#3342]
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Operating system: Docker
  * Digest: sha256:6c321963e1ab57d829e2465c08d48d9066e1bd90d5b213fc182b5a26dc671f58

  
## Step 3: Describe the problem:

I can't get plot-profit to work

### Steps to reproduce:

```
docker-compose run --rm freqtrade backtesting --ticker-interval 5m -s SampleStrategy --config user_data/config.json --export trades
```

```
docker-compose run --rm freqtrade plot-profit --ticker-interval 5m --config user_data/config.json  --export=trades --export-filename=backtest_results/backtest-result.json
```

I get:
```
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/plot_commands.py", line 36, in start_plot_profit
    plot_profit(config)
  File "/freqtrade/freqtrade/plot/plotting.py", line 510, in plot_profit
    fig = generate_profit_graph(plot_elements["pairs"], plot_elements["ohlcv"],
  File "/freqtrade/freqtrade/plot/plotting.py", line 392, in generate_profit_graph
    df_comb = create_cum_profit(df_comb, trades, 'cum_profit', timeframe)
  File "/freqtrade/freqtrade/data/btanalysis.py", line 201, in create_cum_profit
    _trades_sum = trades.resample(f'{timeframe_minutes}min', on='close_time')[['profitperc']].sum()
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 8104, in resample
    return resample(
  File "/usr/local/lib/python3.8/site-packages/pandas/core/resample.py", line 1270, in resample
    return tg._get_resampler(obj, kind=kind)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/resample.py", line 1403, in _get_resampler
    raise TypeError(
TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'
```
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
well the docker digest won't help us to determine the version since the official images don't include plotly - so you've for sure rebuilt it (there is no other way to use plotly within docker).

what's the output of `docker-compose run --rm freqtrade -v`?

**Comment by steffenix** [comment]
I am just adding to rebuilding from the docker image

```
FROM freqtradeorg/freqtrade:master

RUN pip install technical plotly

ENTRYPOINT [ "freqtrade" ]

```

**Comment by xmatthias** [comment]
That's clear - but depending on WHEN you first pulled the initial image, your version may be an uptodate one, or an outdated one.

Please post the output of `docker-compose run --rm freqtrade -v` - so we know which version you're using and don't waste time chasing already fixed bugs.

**Comment by steffenix** [comment]
```
freqtrade 2020.4
```

**Comment by xmatthias** [comment]
Right above the exception - are you receiving `2020-05-21 07:01:44,903 - freqtrade.plot.plotting - WARNING - Backtest file is missing skipping trades.`?


I think the filename you're passing in explicitly is wrong.
can you try with the following - basically omitting the explicit filename (backtesting and plot-profit default to the same filename if not specified explicitly.

```
docker-compose run --rm freqtrade plot-profit --ticker-interval 5m --config user_data/config.json
```


The only way i can recreate this issue is by not having trades available ... 
there's 2 possibilities for this i think - backtesting didn't generate a trade - or plot-profit did not find the exported file.

**Comment by steffenix** [comment]
You are right, I get `freqtrade.plot.plotting - WARNING - No trades found - not plotting max drawdown.`

**Comment by xmatthias** [comment]
still it shouldn't crash this way - so we improved handling in #3351 for this problem.
