### ISSUE TITLE
SyntaxError: unmatched

### ISSUE THREAD

**Issue by Maurits14** [freqtrade/freqtrade#3345]
## Step 2: Describe your environment

  * Operating system: Ubuntu 20.04 LTS
  * Python Version: 3.8.2
  * Branch: Develop
 
## Step 3: Describe the problem:
I am trying to optimize my strategy. For this I configured a hyperopt file and I ran the following command: freqtrade hyperopt --config config.json --hyperopt BBRSI_hyperopt -e 100

This resulted in the following error: SyntaxError: unmatched.

I could not find anything to fix this problem; I read that hyperopt crashes when using 1 CPU, so I do use 2 CPU's. I was wondering whether someone could help me out. 

The full output: Fatal exception!
Traceback (most recent call last):
  File "/home/maurits/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/maurits/freqtrade/freqtrade/commands/optimize_commands.py", line 61, in start_hyperopt
    from freqtrade.optimize.hyperopt import Hyperopt
  File "/home/maurits/freqtrade/freqtrade/optimize/__init__.py", line 1, in <module>
    from user_data.hyperopts.BBRSI_hyperopts import BBRSI_hyperopt
  File "/home/maurits/freqtrade/user_data/hyperopts/BBRSI_hyperopts.py", line 99
    ))
    ^
SyntaxError: unmatched ')'

Thank you very much in advance!

**Comment by hroff-1902** [comment]
you have not filled the version of the freqtrade field (`freqtrade -V`)

**Comment by xmatthias** [comment]
> File "/home/maurits/freqtrade/user_data/hyperopts/BBRSI_hyperopts.py", line 99
))
^
SyntaxError: unmatched ')'

You've got a syntax error in your hyperopt file - in line 99 ... (probably one `)` too much, judging from the erorr).

Best use a syntax-highlighting editor (e.g. vscode with python plugin) which will highlight such problems.

Nothing freqtrade can do for you ... sorry :)

**Comment by Maurits14** [comment]
So stupid, thank you so much!
