### ISSUE TITLE
Freqtrade doesn't update to Python3.8 after Ubuntu upgrade to 20.04

### ISSUE THREAD

**Issue by BlueSkyTrading** [freqtrade/freqtrade#3360]
## Step 1: Have you search for this issue before posting it?
Yes

## Step 2: Describe your environment

  * Operating system: Ubuntu 20.04 Headless
  * Python Version: 3.8.2
  * CCXT version: 1.27.91
  * Branch: Develop
  * Last Commit ID: f1ab1835f157c88cd0d74e27fe4f1760bb1a9267
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*
After upgrading the VPS from Ubuntu 19.10 to 20.04, Freqtrade is still looking to run Python3.7 instead of 3.8.

The update command doesn't add Python3.8 in .env/bin and reinstalling the virtual environment doesn't work either because it says everything is up to date.

### Steps to reproduce:

  1. Update Ubuntu 19.10
`sudo apt update`
`sudo apt upgrade`
`sudo apt dist-upgrade`
`sudo do-release-upgrade`

  2. Update Freqtrade
`./setup.sh -update`
`sudo apt-get install python3`
`sudo apt-get install python3-pip`
`sudo apt-get install python3-venv build-essential libssl-dev libffi-dev python3-dev`

  3. Run the bot
`(.env) root@server:~/freqtrade# freqtrade trade -c config.json --strategy SampleStrategy`
or
`/root/freqtrade/freqtrade/main.py trade -c /root/freqtrade/config.json --strategy SampleStrategy --userdir /root/freqtrade/user_data/`
  
### Observed Results:

  * What happened?
The bot is looking for Python3.7 (which exists in the folder but removed from Ubuntu 20.04) instead of Python3.8 (that is installed by Ubuntu 20.04 but doesn't exists in .env/bin)

  * What did you expect to happen?
The bot will run based on Python3.8

### Relevant code exceptions or logs:

  ```
-bash: /root/freqtrade/.env/bin/freqtrade: /root/freqtrade/.env/bin/python3.7: bad interpreter: No such file or directory
  ```
```
python3 is already the newest version (3.8.2-0ubuntu2)
```
```
python3-pip is already the newest version (20.0.2-5ubuntu1)
```
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.8ubuntu1).
libffi-dev is already the newest version (3.3-4).
libssl-dev is already the newest version (1.1.1f-1ubuntu2).
python3-dev is already the newest version (3.8.2-0ubuntu2).
python3-venv is already the newest version (3.8.2-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by xmatthias** [comment]
This is not something freqtrade can handle for you (yes, we provide the `setup.sh` script - but certain system-level tasks have to be done manually nonetheless).

It's virtualenv that's (kindof) at fault - you've removed it's base dependency (python3.7) - there is nothing freqtrade can nor will do for you in this case, as this is out of our control.

---

You can easily solve this by either removing the .venv folder manually (`rm -rf .env`)- or by running running the setup.sh script's reset (`setup.sh -r`).

Both commands will remove the virtual environment.
You can then use `setup.sh -i` (installing it again) - and should be good to go.

**Comment by BlueSkyTrading** [comment]
For a weird reason the upgrade corrupted PIP when it appears installed but can't be called...
Did a clean reinstall and all is good now...

**Comment by hroff-1902** [comment]
I installed (Ubuntu 18.04, then 19.04) both python 3.7 and python 3.8, pip still works with python 3.7, so everytime when I run setup.sh for some reasons (to recreate venv, for example), I need to comment out (temporary) that part in the setup.sh which recognizes python 3.8 installed in the system...

So it's just about system configuration, if you are doing strange or non-standard things, like me installing many pythons...
