### ISSUE TITLE
No Ticker Data from Binance via DataProvider

### ISSUE THREAD

**Issue by Andi1990** [freqtrade/freqtrade#3362]
## Step 1: Have you search for this issue before posting it?

Yes
## Step 2: Describe your environment

  * Operating system:  Linux Ubuntu
  * Python Version: 3.6.9
  * CCXT version: 1.25.81
  * Branch: Master | Develop
  * Last Commit ID: 18a6c98a825a26e48e6748f053df3ceb2750f368
  
## Step 3: Describe the problem:

I need ticker data (last-price) from Binance. However, the received ticker object from the dataprovider is None. On the other side, the orderbook object is received correctly.

### Steps to reproduce:

if self.dp:
    if self.dp.runmode.value in ('live', 'dry_run'):
        ticker = self.dp.ticker(metadata['pair'])
        dataframe['last_price'] = ticker['last']

### Relevant code exceptions or logs:

in populate_indicators
    dataframe['last_price'] = ticker['last']
TypeError: 'NoneType' object is not subscriptable
2020-05-23 06:44:35,056 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair Z
EC/USDT: 'NoneType' object is not subscriptable
2020-05-23 06:44:35,078 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'NoneType' object is not subscriptable

**Comment by xmatthias** [comment]
Please fill out the version template in the issue completely (which version are you running)...

Without that we'll be unable to support you.

Thanks for your understanding.

**Comment by Andi1990** [comment]
> Please fill out the version template in the issue completely (which version are you running)...
> 
> Without that we'll be unable to support you.
> 
> Thanks for your understanding.

I have updated the environment.

**Comment by Andi1990** [comment]
> > Please fill out the version template in the issue completely (which version are you running)...
> > Without that we'll be unable to support you.
> > Thanks for your understanding.
> 
> I have updated the environment.

**Update:** I have updated my freqtrade version via _./setup.sh --update_ and now the ticker works. However, in docker master-branch ticker is still not available for binance (docker develop-branch works as well).

**Comment by xmatthias** [comment]
Well that's not a problem but intentional.

The feature you're trying to use was merged in #3267 - ten days ago.
We'll do a new release soonish - but master is the stable branch - with roughly one release per month.

If you're trying to use newer features, use develop.
