### ISSUE TITLE
REST RPC Formatting

### ISSUE THREAD

**Issue by Pascal66** [freqtrade/freqtrade#3364]
{"version":"develop-d31a091d"}

### Observed Results: 

  * What happened?
JSON-RPC command 'profit' 
`"first_trade_date":"5 days ago","latest_trade_date":"a day ago"`

Difficult to parse for any real client (not telegram) in any programming langage and not precise.

  * What did you expect to happen?
the real datetime or a unix timestamp
(like the resturn of 'trades' cmd wich include both formated datetime and human readable)

**Comment by xmatthias** [comment]
When you say "RPC" command - which RPC method are we talking about? 
telegram? rest? webhooks?

Also - please fill out the issue template containing versions.

**Comment by xmatthias** [comment]
Now it makes more sense. 3369 should address this.

If i may ask - what are you building with it? 
We're working on a WebUI as well - if that's what you're trying to build: https://github.com/freqtrade/frequi

Combined efforts will lead to better results (due to increased Resources!)

**Comment by Pascal66** [comment]
Ok for #3369 
Making a simple android java client, as webhook (ifttt) and telegram doesnt fit my need.

**Comment by hroff-1902** [comment]
#3369 addressed this was just merged into develop.
