### ISSUE TITLE
Question about stake amount

### ISSUE THREAD

**Issue by Maurits14** [freqtrade/freqtrade#3370]
I am not having any problems at all, but I do have a question about the stake amount in the config file. I was wondering whether it is possible to set your stake amount as a percentage of your trading capital, so that the bot would automatically trade with the profit you gained.

For example: let's say you started with $1000 capital. You had a stake amount of 5% of your capital so $50. Then you made 10% profit -> giving a capital of $1100. Would it be possible to automatically get a new stake amount of $55, so basically setting a stake amount of 5% of your total capital?

I was not able to find the answer to my question on freqtrade.io, so I suppose it is not possible at this moment, but please correct me if I am wrong.

**Comment by xmatthias** [comment]
yes - https://www.freqtrade.io/en/latest/configuration/#dynamic-stake-amount

setting stake_amount to unlimited, it'll use the available capital (1000) divided by max_open_trades - so to get to 10% - you need to set max_open_trades to 10.

**Comment by Maurits14** [comment]
Thanks
