### ISSUE TITLE
Hyperopt confusing warning message

### ISSUE THREAD

**Issue by Theagainmen** [freqtrade/freqtrade#3371]
## Step 1: Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.7.5 (`python -V`)
  * Branch: freqtrade develop-1aa1fada
  
## Step 2: Describe the problem:

When hyperopting with the following command: `freqtrade hyperopt -c test_config.json --hyperopt strategy_hyperopt -e 750--spaces buy sell stoploss trailing -–min-trades=20 –-timerange=20200111-20200510 –j 2 --no-color` 

I get the following warning messages:
![image](https://user-images.githubusercontent.com/24569139/82764678-db0dc700-9e10-11ea-9679-a9efc64f6207.png)

I didn't include the 'normal' buy/sell trends in the hyperopt file, but since I am using the buy/sell trends generated by the hyperopt file, these messages can be confusing. It's taking the 'normal' buy/sell trends from the original strategy file, but it doesn't use it anyway.

**Comment by xmatthias** [comment]
well it depends on the space you're using. 

Assume you use `--spaces buy` - then the `populate_sell` would be used.

**Comment by hroff-1902** [comment]
buy and sell spaces are specified -- in this case only decorated methods from hyperopt class are used, hyperopt should not issue a message about the missing non-decorated methods.

**Comment by xmatthias** [comment]
i disagree - it'll make spotting "typos" very difficult - where the wrong method is being used due to a typo in the header.

**Comment by hroff-1902** [comment]
okay, maybe info
or maybe still a warning in this case, to have it more visible,
need to think about this a bit...
