### ISSUE TITLE
Hyperopt searches for best statistical fit, not the best trades

### ISSUE THREAD

**Issue by nardholio** [freqtrade/freqtrade#3383]
Consider the following Hyperopt output

<pre>+--------+-------------+----------+--------------+------------------------------+----------------+-------------+
|   Best |       Epoch |   Trades |   Avg profit |                       Profit |   Avg duration |   Objective |
|--------+-------------+----------+--------------+------------------------------+----------------+-------------|
| <font color="#4E9A06">* Best</font> | <font color="#4E9A06">    1/10000</font> |      <font color="#4E9A06">172</font> |      <font color="#4E9A06">  0.34%</font> | <font color="#4E9A06">   0.00348252 BTC   (57.98%)</font> |      <font color="#4E9A06">1,282.2 m</font> |     <font color="#4E9A06">2.01971</font> |
| <font color="#4E9A06">* Best</font> | <font color="#4E9A06">   15/10000</font> |      <font color="#4E9A06">161</font> |      <font color="#4E9A06">  0.39%</font> | <font color="#4E9A06">   0.00376093 BTC   (62.62%)</font> |      <font color="#4E9A06">1,057.7 m</font> |     <font color="#4E9A06">2.00708</font> |                                            
| <font color="#4E9A06">* Best</font> | <font color="#4E9A06">   20/10000</font> |      <font color="#4E9A06">143</font> |      <font color="#4E9A06">  0.87%</font> | <font color="#4E9A06">   0.00744080 BTC  (123.89%)</font> |      <font color="#4E9A06">2,127.7 m</font> |     <font color="#4E9A06">1.80748</font> |                                            
|   <font color="#4E9A06">Best</font> | <font color="#4E9A06">   49/10000</font> |      <font color="#4E9A06">155</font> |      <font color="#4E9A06">  0.84%</font> | <font color="#4E9A06">   0.00780534 BTC  (129.96%)</font> |      <font color="#4E9A06">1,645.1 m</font> |     <font color="#4E9A06">1.78415</font> |                                            
|   <font color="#4E9A06">Best</font> | <font color="#4E9A06">   51/10000</font> |      <font color="#4E9A06">203</font> |      <font color="#4E9A06">  0.80%</font> | <font color="#4E9A06">   0.00977311 BTC  (162.72%)</font> |      <font color="#4E9A06">1,086.9 m</font> |     <font color="#4E9A06">1.66285</font> |                                            
|   <font color="#4E9A06">Best</font> | <font color="#4E9A06">   52/10000</font> |      <font color="#4E9A06">215</font> |      <font color="#4E9A06">  0.80%</font> | <font color="#4E9A06">   0.01030110 BTC  (171.51%)</font> |        <font color="#4E9A06">898.6 m</font> |     <font color="#4E9A06">1.63063</font> |
|   <font color="#4E9A06">Best</font> | <font color="#4E9A06">   68/10000</font> |      <font color="#4E9A06">255</font> |      <font color="#4E9A06">  0.43%</font> | <font color="#4E9A06">   0.00654487 BTC  (108.97%)</font> |        <font color="#4E9A06">110.4 m</font> |     <font color="#4E9A06">1.57697</font> |                                            
|   <font color="#4E9A06">Best</font> | <font color="#4E9A06">  105/10000</font> |      <font color="#4E9A06">200</font> |      <font color="#4E9A06">  1.03%</font> | <font color="#4E9A06">   0.01242231 BTC  (206.83%)</font> |      <font color="#4E9A06">1,260.9 m</font> |     <font color="#4E9A06">1.51656</font> |                                            
|   <font color="#4E9A06">Best</font> | <font color="#4E9A06">  197/10000</font> |      <font color="#4E9A06">251</font> |      <font color="#4E9A06">  0.61%</font> | <font color="#4E9A06">   0.00914335 BTC  (152.24%)</font> |        <font color="#4E9A06">148.7 m</font> |     <font color="#4E9A06">1.48472</font> |                                            
|   <font color="#4E9A06">Best</font> | <font color="#4E9A06">  553/10000</font> |      <font color="#4E9A06">188</font> |      <font color="#4E9A06">  1.17%</font> | <font color="#4E9A06">   0.01324023 BTC  (220.45%)</font> |      <font color="#4E9A06">1,343.8 m</font> |     <font color="#4E9A06">1.47414</font> |                                            
|   <font color="#4E9A06">Best</font> | <font color="#4E9A06">  558/10000</font> |      <font color="#4E9A06">184</font> |      <font color="#4E9A06">  1.29%</font> | <font color="#4E9A06">   0.01427631 BTC  (237.70%)</font> |      <font color="#4E9A06">1,255.1 m</font> |     <font color="#4E9A06">1.41762</font> |                                            
|   <font color="#4E9A06">Best</font> | <font color="#4E9A06">  745/10000</font> |      <font color="#4E9A06">214</font> |      <font color="#4E9A06">  1.14%</font> | <font color="#4E9A06">   0.01468999 BTC  (244.59%)</font> |        <font color="#4E9A06">667.0 m</font> |     <font color="#4E9A06">1.38728</font> |                                            
|   <font color="#4E9A06">Best</font> | <font color="#4E9A06">  790/10000</font> |      <font color="#4E9A06">182</font> |      <font color="#4E9A06">  1.40%</font> | <font color="#4E9A06">   0.01531421 BTC  (254.98%)</font> |      <font color="#4E9A06">1,255.3 m</font> |     <font color="#4E9A06">1.36053</font> | </pre>

At epochs 68 and 197 the trade profit drops substantially, even though it is a better statistical fit to the data. As a human being, I don't care how well my strategy fits the data set, I want to maximize my profits. Hyperopt should not mark an epoch as "better" if the profit drops.

**Comment by xmatthias** [comment]
For this we have a several different loss functions.

Best read the documentation [documentation](https://www.freqtrade.io/en/latest/hyperopt/#loss-functions) and select one that fits your needs.

**Comment by hroff-1902** [comment]
Hyperopt (as all other optimization engines) always searches for a local minimum of the objective (loss) function in the hyperspace of optimization parameters, by definition.
