### ISSUE TITLE
Wrong Results in Plot-Profit?

### ISSUE THREAD

**Issue by Andi1990** [freqtrade/freqtrade#3386]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: Python 3.6.9
  * CCXT version: 1.27.91
  * Freqtrade Version: develop-b50d072d

## Describe the problem:

I have backtested my strategy and saved the results in my data folder. 
`freqtrade backtesting -c config.json -s Strategy --timerange=20190501-20200505 --export trades --export-filename=user_data/backtest-results/201905_backtest.json`

After that I wanted to plot the profit which has been achieved by the strategy.
`freqtrade plot-profit -c config.json --timerange 20190501-20200505 --ticker-interval 1h --export=trades --export-filename=user_data/backtest-results/201905_backtest.json`

The backtesting as well as the plotting succeeded. However, it is absolutely not clear to me why my Tot Profit % is sharply higher than the Combined Profit at the end of the considered time (here: 20200505).

### Observed Results:
Tot Profit % (around 50%) is sharply higher than the Combined Profit at the end of the considered time (here: 17.9%).

![image](https://user-images.githubusercontent.com/12513560/83063914-2dddbd80-a061-11ea-8b04-5019dfcc4f75.png)

**Shouldn't be the last combined profit in the plot exactly the same as the total profit of the backtest result?** 

I would be glad if anyone can help.

**Comment by xmatthias** [comment]
I assume you might want to add a screenshot / some output showing what you think is wrong? 

from the above, it's not clear to me what you think is wrong...

**Comment by Andi1990** [comment]
> I assume you might want to add a screenshot / some output showing what you think is wrong?
> 
> from the above, it's not clear to me what you think is wrong...

I have added a screenshot of my plot result

**Comment by xmatthias** [comment]
I am sorry but i'm unable to validate / confirm this.

My result:
```
|      Pair |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit EUR |   Tot Profit % |      Avg Duration |   Wins |   Draws |   Losses |
|     TOTAL |     35 |           1.30 |          45.51 |      13.67355096 |          15.17 |    1 day, 6:39:00 |     24 |       0 |       11 |

```

My plot:

the resulting value does show 0.455 at the last step (my screenshot program does remove hovers before screenshotting ...)

![2020-05-28-072000_1669x232_scrot](https://user-images.githubusercontent.com/5024695/83101907-af5e3b80-a0b3-11ea-9564-d1a921d859d8.png)

**Comment by Andi1990** [comment]
I see, the combined profit is showing cumulated profit / 100. In my previous understanding the plot would show the total profit.  Now it is clear to me. I guess this can be closed.

Thank you.

**Comment by xmatthias** [comment]
I don't think you can correctly show the total profit in the plot - as it's implicitly cumulative profit.

Now it's /100 - which is ... not "sooo" intentional - but that's a different topic i guess
