### ISSUE TITLE
Take a 'realist' filled price in dry run for market orders (compute using order book and the stake amount)

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#3389]
### Story like :

As a trader
I want the dry run to be closed to real money behavior
So that i can make a choice on number of asset i trade with (depends liquidity).

### Further explanations:

What about compute the average filled price (as it is a market buy and market sell) using the order book and taking into account the stake_amount ?

Then this average filled price is used to compute profit.

### The snippet :

```
def forecast_avg_filled_price(self, action, stake_amount, orderbook) -> float:
        
        book_entry_type = None
        if action == 'buy':
            book_entry_type = 'asks'
        if action == 'sell':
            book_entry_type = 'bids'
        
        remain_amount_to_be_filled = stake_amount
        filled_amount = 0
        for book_entry in orderbook[book_entry_type]:
            book_entry_price = book_entry[0]
            book_entry_coin_volume = book_entry[1]
            book_entry_ref_currency_volume = book_entry_price * book_entry_coin_volume
            if remain_amount_to_be_filled > 0:
                if remain_amount_to_be_filled < book_entry_ref_currency_volume:
                    filled_amount += remain_amount_to_be_filled * book_entry_price
                else:
                    filled_amount += book_entry_ref_currency_volume * book_entry_price
                remain_amount_to_be_filled -= book_entry_ref_currency_volume
                # print(' {} : book_entry price : {} with ref volume {}'.format(action, book_entry_price, book_entry_ref_currency_volume))
                # print(' {} : remain_amount_to_be_filled {} '.format(action, remain_amount_to_be_filled))
            else:
                break
        forecast_avg_filled_price = filled_amount / stake_amount
        return forecast_avg_filled_price
```
Have a nice day.

**Comment by xmatthias** [comment]
but this would only apply on market orders?
for limit you cannot calculate this this way - as limit orders don't have this kind of slippage.

it's not a bad idea for market orders (which are currently not well emulated) - but for limit orders it's more difficult i think - these never show slippage - so the situation is quite different.

**Comment by orehunt** [comment]
to emulate limit orders you would have to fetch past trades since sell reason triggered and match price/amounts. This is of course unfeasable for very liquid markets, at the same time it is not very useful in those cases, since trades are easily filled and spread is low, so it could be enabled on case by case if the pair is below some threshold of volume/trades frequency.
