### ISSUE TITLE
Hyperopt: cannot import name 'qtrade' from 'ccxt'

### ISSUE THREAD

**Issue by Vildnex** [freqtrade/freqtrade#3391]
## Describe your environment

  * Operating system: Ubuntu Server 20.04
  * Python Version: 3.8 (`python -V`)
  * CCXT version: 1.27.1 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.04 and also the lust update (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
 
## Describe the problem:

I've tryed to run the hyperopt with this command:
`freqtrade hyperopt --config config_test.json --hyperopt MACDStrategyBB_hyperopt -s MACDStrategyBB -e 10000 --spaces all --continue --timerange=20171106-20191206 --hyperopt-loss SortinoHyperOptLossDaily`

But from some interesting reason I'm getting this error:

`ImportError: cannot import name 'qtrade' from 'ccxt' (/home/vlad/freqtrade/.env/lib/python3.8/site-packages/ccxt/__init__.py)`

Any idea?

**Comment by xmatthias** [comment]
upgrade your ccxt.

the current ccxt version is `1.28.85` - and iirc, then qtrade is a fairly new exchange.

**Comment by Vildnex** [comment]
Ok... I did that, now it almost working because I"m getting this error:
`joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.`

**Comment by xmatthias** [comment]
well are you creating an instance of an exchange within the strategy (or using the exchange directly in the strategy?

if yes, then you can't use hyperopt - as that's a limitation of pickle ...

**Comment by Vildnex** [comment]
I'm not sure what do you mean by using an exchange within the strategy

**Comment by xmatthias** [comment]
well i assume the new error has nothing to do with the exchange then - but with your hyperopt file.

There are certain things that are "not picklable" - now that's a very broad term and very difficult to describe - but basically it means that it's using something that it should not (cannot) use.

**Comment by hroff-1902** [comment]
you can paste your hyperopt file here so that we could try to reproduce

**Comment by Vildnex** [comment]
It's fine, I found the problem. I've used the jhTalib package and from some reason, it's not working in multithreading

**Comment by xmatthias** [comment]
hyperopt is not multithreading - but it's pickling the python objects and sending them to other processes. 
That's a tricky process for certain objects (if they open connections to the web, for example) - therefore not everything is allowed there. Nothing freqtrade can do in this case though...
