### ISSUE TITLE
Add 'available liquidity' to real trades report

### ISSUE THREAD

**Issue by yilongwen** [freqtrade/freqtrade#3393]
Just throwing out some random thoughts: I'd love to know when I take a trade, what the available liquidity is at the time when the order is executed. Say the top N entries of the orderbook yields a X amount of coins and an average price of Y, with N as an input given by the user. My goal for this is to have an estimate of slippage and hopefully gain some general understanding in the relationship between the strategy performance and liquidity.

**Comment by hroff-1902** [comment]
how to calculate "available liquidity"?

maybe VWAP (volume-weighted avg/ price) for both bid and ask sides of the orderbook would suffice as the measure of liquidity?

**Comment by orehunt** [comment]
I think vwap is based on past trades not on orderbook, so it doesn't compare

**Comment by hroff-1902** [comment]
No, I mean 2 VWAP values calculated on 'ask' and 'bid' parts of the orderbook (each using 2 data series of prices and respective volumes)...

Those 2 values can then be compared with the spread mean price/ticker last trade price and are indicating a measure of Statistical Ordebook Imbalance and depend on liquidity in the orderbook (since calculated on series of prices and volumes in the orderbook).

This issue proposes an ability to "know" the "available liquidity" for the custom strategies -- and the first question here is what is assumed under the "available liquidity" here?

**Comment by yilongwen** [comment]
I was more thinking about taking a snapshot of the order book when executing the trade. And I kinda assumed it already does, when executing a limit order. We can then use that snapshot to calculate things like the amount of available asset for sale at that particular moment, and the average price for it.  

 ask price      amount
------------|------------
     $1.0      |     100
     $1.01    |     200
     ...          |     ...
Available amount in dollar: $1.0 * 100 + $1.01 * 200 = $302
Average price: $302 / 300 = $1.0067

**Comment by hroff-1902** [comment]
Won't the orderbook data from the Dataprovider suffice your need?
See https://www.freqtrade.io/en/latest/strategy-customization/#orderbookpair-maximum

**Comment by yilongwen** [comment]
Yeah exactly, I wonder if it'd be an idea to add those numbers to the trade report. It might be handy for analysis purposes, say to see what the liquidity is at some particular buy/sell moments(depending on the strategy).
... | open_rate | open_rate_requested | available liquidity | average price | ...
--- | --- | --- | --- | --- | ---

**Comment by hroff-1902** [comment]
Now I do not understand what do you mean by "trade report"...

**Comment by yilongwen** [comment]
I mean trades results which are stored in sql database. Things like open_date, open_rate, and so on.

**Comment by hroff-1902** [comment]
It's not a "trade result" but some metrics on orderbook data which changes with every moment of time (each freqtrade throttling iteration), also adding it would require an additional exchange API call to fetch orderbook data even if a user does not use orderbook. Adding it will increase the number of requests to exchange API and increase the chances to be banned by exchange. I think we should reject it -- you can calculate in in your custom strategy methods in any way you wish, and others may want it to be calculated in another way...

**Comment by xmatthias** [comment]
Timing of this will be impossible to get right (orderbooks change with millisecond frequency - so getting the value right when the order is placed will be near impossible - and every half-second (or whatever) of offset will cause this value to be pointless).

As such - i agree with the comments above that this will not make much sense, and i'm therefore closing it.
