### ISSUE TITLE
ReadTheDocs VirtualEnv link dead (https://virtualenv.pypa.io/en/stable/installation/)

### ISSUE THREAD

**Issue by juliencarponcy** [freqtrade/freqtrade#3401]
Hello all,

Sorry if this the wrong place to report that, but in the guide to setup requirements the link sending to virtualenv is dead (for me now).
https://virtualenv.pypa.io/en/stable/installation/
possibly to replace by:
https://virtualenv.pypa.io/en/stable/

in the beginning of :
https://www.freqtrade.io/en/latest/installation/

Thanks for your work

**Comment by hroff-1902** [comment]
Thanks! 👍 

(You can easily improve the doc pages, by pressing the Edit button for a file at the docs dir, it will then create a pull request with the changes made)

**Comment by juliencarponcy** [comment]
Ok thanks, will try next time
