### ISSUE TITLE
Calculate moving average on custom value on dataframe

### ISSUE THREAD

**Issue by NilanjanaBala** [freqtrade/freqtrade#3406]
## Describe your environment

  * Operating system: Linux/macOS
  * Freqtrade Version: latest
  
## Your question

1. How can i calculate moving average, MACD on heikin ashi close/open price?

If we try to overwrite 

dataframe['open']= dataframe['open_ha']
dataframe['close']= dataframe['close_ha']

and try to calculate all, in backtesting it works but getting warning while trading. Any pointer how it can be done?

Is there any way to pass custom dataframe['close'] while calculating the indicator value?

        dataframe['ema8'] = ta.EMA(**dataframe**, timeperiod=8)

thanks for your help.

thanks

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by hroff-1902** [comment]
It should not be in the Freqtrade docs, because recipes differ depending on the indicator library you are using.

Assuming you are using abstract ta-lib interface, as in all Freqtrade samples, have a read the doc page on it: https://mrjbq7.github.io/ta-lib/abstract.html

You will find there, that you can use the `price` parameter with the name of the column on which an indicator, which requires one column can be calculated:
```
ta.EMA(dataframe, timeperiod=8, price='close_ha')
```
If an indicator needs more columns (like STOCH), then the `prices` parameter can be used:
```
slowk, slowd = ta.STOCH(dataframe, 5, 3, 0, 3, 0, prices=['high_ha', 'low_ha', 'open_ha'])
```

Alternatively, you may use non-abstract ta-lib interface (their Function API, as they call it), see https://mrjbq7.github.io/ta-lib/func.html. In order to use it insteas of Abstract ta-lib API, import ta-lib as
```
import ta-lib as ta
```
instead of 
```
import ta-lib.abstract as ta
```

**Comment by NilanjanaBala** [comment]
thanks @hroff-1902 for the details. I am trying with that.. is there any way i can check what the order/parameter i need pass. 

dataframe['rsi'] = ta.RSI(dataframe, price_wrong='ha_close', timeperiod=12)
dataframe['rsi'] = ta.RSI(dataframe, price='ha_close', timeperiod=12)
dataframe['rsi'] = ta.RSI(dataframe, timeperiod=12, price='ha_close')

All works, i don't see any error while running. Does it really working.

Thanks,

**Comment by NilanjanaBala** [comment]
Looks like 

real = RSI(close, timeperiod=14)
https://mrjbq7.github.io/ta-lib/func_groups/momentum_indicators.html
Looks like freqtrade is a adapter layer of TA

is it the correct order should be :
ta.EMA(dataframe, price='ha_close', timeperiod=8)

Many thanks

**Comment by hroff-1902** [comment]
> Looks like freqtrade is a adapter layer of TA

I have no idea what you are talking about here. It's an example of your custom strategy code, freqtrade only uses it, it's not an any kind of "adapter" here.

> is it the correct order should be :
ta.EMA(dataframe, price='ha_close', timeperiod=8)

In python, "keyword arguments" (named parameters) can be specified in any order.

**Comment by NilanjanaBala** [comment]
Thanks for the details.

 dataframe['rsi'] = ta.RSI(dataframe, price_bad='ha_open', timeperiod=12)
 dataframe['ema8'] = ta.EMA(dataframe, timeperiod=8, price_bad='ha_open')
macd = ta.MACD(dataframe, fastperiod=12, slowperiod=26, signalperiod=9, prices_xyz=['ha_open'])

I am not seeing any error while passing wrong key of the argument. Above all works, does it really working? As key wrong it should gives error. Any thought please

thanks

**Comment by xmatthias** [comment]
These questions have nothing to do with freqtrade - you're calling ta-lib functions directly. Freqtrade does not have nor offer (nor intends to offer) any wrapper for ta-lib.

If you have concerns about the correctness of calls to the ta-lib library (either using the abstract interface, or the function based interface), please direct them to the [ta-lib](https://github.com/mrjbq7/ta-lib/) repository.

From a freqtrade point of view - yes - our samples do use ta-lib - but we don't give support for questions regarding the usage of ta-lib.

**Comment by hroff-1902** [comment]
> As key wrong it should gives error. Any thought please

No, in python they should not. You should learn about python kwargs and their usage (if you'd like to know how it works)

Agree with @xmatthias -- these are general questions, not related to freqtrade functionality, you should get more familiar with ta-lib and with python...

**Comment by NilanjanaBala** [comment]
thanks for taking time to help, really appreciate.. I made a simple python script and i could see it gives error in case of wrong key:

`def fun(a="val", b="val"):
    print("a:",a)
    print("b:",b)

fun(b_bad="hii hello 1", a='hello world 1')`

`>Traceback (most recent call last):
  File "e2.py", line 5, in <module>
    fun(b_bad="hii hello 1", a='hello world 1')
TypeError: fun() got an unexpected keyword argument 'b_bad'

Process finished with exit code 1`

**Comment by hroff-1902** [comment]
man, I told you, you should better learn what python kwargs are and what they are used by python devs and python API designers for.

```
def fun(a="val", b="val", **kwargs):
    print("a:",a)
    print("b:",b)

fun(b_bad="hii hello 1", a='hello world 1')
```
-- this won't produce any error.

You (wrongly) assume that ta-lib interface does not use kwargs...

**Comment by NilanjanaBala** [comment]
yes right, got it. thanks
