### ISSUE TITLE
Trades dates in backtest are always set to year 1970

### ISSUE THREAD

**Issue by BlueSkyTrading** [freqtrade/freqtrade#3412]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: 3.8.2
  * CCXT version: 1.28.49
  * Freqtrade Version: develop-9f8b21de
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. Generate Backtesting JSON file
`
freqtrade backtesting -c config.json -s CustomStrategy --export trades
`
  2. Convert UNIX date to numerical date in LibreOffice Calc
`
= (date_cell)/1000/(60*60*24) + 25569
`
  3. Convert numeric date to time value
`
YYYY-MM-DD HH:MM:SS
`
  
### Observed Results:
1970-01-18 09:54:19

  * What happened?
date of trade is always set to 1970

  * What did you expect to happen?
True trades dates should appear

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // 

Field1 | Field2 | Field3 | Field4 | Field5 | Field6 | Field7 | Field8 | Field9 | Field10
BTC/USDT | 0.0000000 | 1504459800 | 1504472400 | 34 | 210 | 4476.05 | 4485.01106106106 | false | roi
ETH/USDT | 0.0151901 | 1504459800 | 1504459800 | 34 | 0 | 338.39 | 344.217927 | false | trailing_stop_loss
BTC/USDT | 0 | 1504508400 | 1504652400 | 61 | 2400 | 4459.77 | 4468.69846846847 | false | roi
ETH/USDT | 0.01176858 | 1504551600 | 1504551600 | 85 | 0 | 290 | 294.0003 | false | trailing_stop_loss
ETH/USDT | 0.03546262 | 1504587600 | 1504594800 | 105 | 120 | 279.5 | 289.991205 | false | trailing_stop_loss
ETH/USDT | 0.02339859 | 1504630800 | 1504632600 | 129 | 30 | 299.08 | 306.690818 | false | trailing_stop_loss
BTC/USDT | 0.01635458 | 1504683000 | 1504686600 | 158 | 60 | 4446.49 | 4528.257954 | false | trailing_stop_loss
ETH/USDT | 0.01234031 | 1504686600 | 1504686600 | 160 | 0 | 322.05 | 326.676899 | false | trailing_stop_loss
ETH/USDT | 0.01100931 | 1504708200 | 1504720800 | 172 | 210 | 330.69 | 335 | false | roi
BTC/USDT | 0.01726274 | 1504776600 | 1504782000 | 210 | 90 | 4546.43 | 4634.17291331331 | false | roi
BTC/USDT | 0 | 1504814400 | 1504827000 | 231 | 210 | 4716.61 | 4726.05266266266 | false | roi
ETH/USDT | 0 | 1504816200 | 1504828800 | 232 | 210 | 332.91 | 333.576486486486 | false | roi
BTC/USDT | 0 | 1504859400 | 1504872000 | 256 | 210 | 4657.53 | 4666.85438438438 | false | roi
ETH/USDT | 0.01145832 | 1504861200 | 1507876200 | 257 | 50250 | 331.6 | 336.07105 | false | trailing_stop_loss
BTC/USDT | 0 | 1504911600 | 1504926000 | 285 | 240 | 4285.99 | 4294.57056056056 | false | roi


  ```

**Comment by xmatthias** [comment]
Wen do provide [documentation](https://www.freqtrade.io/en/latest/strategy_analysis_example/#load-backtest-results-to-pandas-dataframe) for loading trades into a dataframe in a interactive juptyer environment, which is our preferred and recommended way to analyze the data.

The dates we store are unixtimestamps (epoch) - and are correct when parsed correctly, however loading data to excel (or libreoffice, in this case) is not supported by the freqtrade team.


Thanks for your understanding.
