### ISSUE TITLE
Exporting trades to file command is incomplete in the documentation

### ISSUE THREAD

**Issue by BlueSkyTrading** [freqtrade/freqtrade#3413]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: 3.8.2
  * CCXT version: 1.28.49
  * Freqtrade Version: develop-9f8b21de
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*
Exporting backtesting trades in JSON file requires to set the config and strategy files, the current documentation don't mention that.

### Steps to reproduce:

  1. Navigate to the export trades in the freqtrade website
[Exporting trades to file](https://www.freqtrade.io/en/latest/backtesting/#exporting-trades-to-file)
  2. Copy backtesting trades command
`
freqtrade backtesting --export trades
`
  3. Run the command in the virtual environment
  
### Observed Results:

  * What happened?
1. error message that no data is available if -c config.json is not added to the command
2. error message that no strategy is set if -s SampleStrategy is not added to the command

  * What did you expect to happen?
generate trades json file

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // 2020-05-31 17:53:09,691 - freqtrade - ERROR - No data found. Terminating.
  // 2020-05-31 17:38:59,127 - freqtrade - ERROR - No strategy set. Please use `--strategy` to specify the strategy class to use.

  ```

**Comment by xmatthias** [comment]
Thanks a ton for your involvement and for updating the documentation to be readily usable!

Closed in #3545
