### ISSUE TITLE
Change columns headers in the backtesting trades export file from generic to meaningful

### ISSUE THREAD

**Issue by BlueSkyTrading** [freqtrade/freqtrade#3414]
## Describe your environment
(if applicable)

  * Operating system: Ubuntu 20.04
  * Python Version: 3.8.2
  * CCXT version: 1.28.49
  * Freqtrade Version: develop-9f8b21de

## Describe the enhancement

*Explain the enhancement you would like*
json generated file, once converted to csv so it can be manipulated in LibreOffice Calc shows columns headers as generic Field1, Field 2, etc.

It would be more meaningful if they can be set to:
column1: tickers
...
column10: order type / execute reason

the file [backtesting.py](https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/optimize/backtesting.py) has already the columns headers names:

`

            if sell.sell_flag:
                trade_dur = int((sell_row.date - buy_row.date).total_seconds() // 60)
                closerate = self._get_close_rate(sell_row, trade, sell, trade_dur)

                return BacktestResult(pair=pair,
                                      profit_percent=trade.calc_profit_ratio(rate=closerate),
                                      profit_abs=trade.calc_profit(rate=closerate),
                                      open_time=buy_row.date,
                                      close_time=sell_row.date,
                                      trade_duration=trade_dur,
                                      open_index=buy_row.Index,
                                      close_index=sell_row.Index,
                                      open_at_end=False,
                                      open_rate=buy_row.open,
                                      close_rate=closerate,
                                      sell_reason=sell.sell_type
                                      )
        if partial_ohlcv:
            # no sell condition found - trade stil open at end of backtest period
            sell_row = partial_ohlcv[-1]
            bt_res = BacktestResult(pair=pair,
                                    profit_percent=trade.calc_profit_ratio(rate=sell_row.open),
                                    profit_abs=trade.calc_profit(rate=sell_row.open),
                                    open_time=buy_row.date,
                                    close_time=sell_row.date,
                                    trade_duration=int((
                                        sell_row.date - buy_row.date).total_seconds() // 60),
                                    open_index=buy_row.Index,
                                    close_index=sell_row.Index,
                                    open_at_end=True,
                                    open_rate=buy_row.open,
                                    close_rate=sell_row.open,
                                    sell_reason=SellType.FORCE_SELL
`

  ```
Field1 | Field2 | Field3 | Field4 | Field5 | Field6 | Field7 | Field8 | Field9 | Field10
BTC/USDT | 0.0000000 | 1504459800 | 1504472400 | 34 | 210 | 4476.05 | 4485.01106106106 | false | roi
ETH/USDT | 0.0151901 | 1504459800 | 1504459800 | 34 | 0 | 338.39 | 344.217927 | false | trailing_stop_loss
BTC/USDT | 0 | 1504508400 | 1504652400 | 61 | 2400 | 4459.77 | 4468.69846846847 | false | roi
ETH/USDT | 0.01176858 | 1504551600 | 1504551600 | 85 | 0 | 290 | 294.0003 | false | trailing_stop_loss
ETH/USDT | 0.03546262 | 1504587600 | 1504594800 | 105 | 120 | 279.5 | 289.991205 | false | trailing_stop_loss
ETH/USDT | 0.02339859 | 1504630800 | 1504632600 | 129 | 30 | 299.08 | 306.690818 | false | trailing_stop_loss
BTC/USDT | 0.01635458 | 1504683000 | 1504686600 | 158 | 60 | 4446.49 | 4528.257954 | false | trailing_stop_loss
ETH/USDT | 0.01234031 | 1504686600 | 1504686600 | 160 | 0 | 322.05 | 326.676899 | false | trailing_stop_loss
ETH/USDT | 0.01100931 | 1504708200 | 1504720800 | 172 | 210 | 330.69 | 335 | false | roi
BTC/USDT | 0.01726274 | 1504776600 | 1504782000 | 210 | 90 | 4546.43 | 4634.17291331331 | false | roi
BTC/USDT | 0 | 1504814400 | 1504827000 | 231 | 210 | 4716.61 | 4726.05266266266 | false | roi
ETH/USDT | 0 | 1504816200 | 1504828800 | 232 | 210 | 332.91 | 333.576486486486 | false | roi
BTC/USDT | 0 | 1504859400 | 1504872000 | 256 | 210 | 4657.53 | 4666.85438438438 | false | roi
ETH/USDT | 0.01145832 | 1504861200 | 1507876200 | 257 | 50250 | 331.6 | 336.07105 | false | trailing_stop_loss
BTC/USDT | 0 | 1504911600 | 1504926000 | 285 | 240 | 4285.99 | 4294.57056056056 | false | roi


  ```

**Comment by xmatthias** [comment]
We do provide [documentation](https://www.freqtrade.io/en/latest/strategy_analysis_example/#load-backtest-results-to-pandas-dataframe) for loading trades into a dataframe in a interactive juptyer environment, which is our preferred and recommended way to analyze the data.

Conversation from json to csv is something not supported directly by freqtrade, we'll therefore also not support this method.

This also adds column headers to the columns.

We also have a request to improve documentation in this regards #3302 - i'll therefore close this as duplicate.

Please try to read the documentation before opening issues with questions which can be easily answered.
