### ISSUE TITLE
Backtesting / Hyperopt - track rejected trades (due to max_open_trades reached)

### ISSUE THREAD

**Issue by nardholio** [freqtrade/freqtrade#3423]
Have backtesting and hyperopt report the number of simultaneous open trades, which would help me optimize how much I should allocate per trade. Right now I have to manually adjust this value and rerun the backtest.

Note I am not asking to backtest or hyperopt different values for this, merely a report of how many were used and perhaps a report on how many trades were rejected due to maximum open positions.

**Comment by xmatthias** [comment]
What value was used is in the logs (before the backtesting), as that value comes from the config

Counting rejected signals might be difficult as there are 2 reasons entry signals are rejected, either because this pair is already open, or because max_open_trades is reached...

**Comment by hroff-1902** [comment]
I also thought about this, can be a good enhancement.
