### ISSUE TITLE
Problem with PrecisionFilter after updating freqtrade to 2020.5

### ISSUE THREAD

**Issue by flogui** [freqtrade/freqtrade#3424]
Have you searched for similar issues before posting it?
Yes
If you have discovered a bug in the bot, please [search our issue tracker

## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: Python 3.6.9
  * CCXT version: 1.28.49
  * Freqtrade Version: 2020.5
  
## Describe the problem:

The precision filter is not working anymore.
Config.json :
`{"method": "StaticPairList"},
      
  {"method": "PrecisionFilter"},
  {"method": "PriceFilter", "low_price_ratio": 0.01},
  {"method": "SpreadFilter"}`

Screen Capture of the error :
![image](https://user-images.githubusercontent.com/65234052/83427531-2cc9d900-a431-11ea-870e-efe0b08ac2f4.png)

**Comment by xmatthias** [comment]
The precision-filter never did work with backtesting - it was disabled implicitly before.

see also #3363 for a deeper discussion around this.

we're still unsure how to fix this - as disabling it implicitly is not good - but keeping it enabled for backtesting might produce odd results, especially (or mainly) when used in combination with `--strategy-list`.
