### ISSUE TITLE
Hedge trading by selling the pair in phases

### ISSUE THREAD

**Issue by BlueSkyTrading** [freqtrade/freqtrade#3428]
## Describe your environment
(if applicable)

  * Operating system: Ubuntu 20.04
  * Python Version: 3.8.2
  * CCXT version: 1.28.49
  * Freqtrade Version: develop-9f8b21de

## Describe the enhancement

*Explain the enhancement you would like*
When I trade manually, I always hedge my orders like this (I'm using simple example here):
Buy:
 Pair ABC/USD order placed at $1,000
Sell:
 1. Sell 50% of ABC/USD when the price reaches $1,100 (10%)
 2. Sell 30% of ABC/USD when the price reaches $1,200 (20%)
 3. Sell 20% of ABC/USD when the price reaches $1,300 (30%)

Is it possible to have the ability to choose between the current system or the above proposed (order buy price can be replaced by the current indicators and it will still have the same proposed purpose).

**Comment by hroff-1902** [comment]
Duplicate to #1519
