### ISSUE TITLE
Why is there a delay in buying orders?

### ISSUE THREAD

**Issue by cgw-9527** [freqtrade/freqtrade#3434]
please help me
![image](https://user-images.githubusercontent.com/57701281/83619563-a04d2100-a5be-11ea-8ed7-76919ae02b7b.png)

**Comment by xmatthias** [comment]
Most likely you have other pairs which are blocking this due to `max_open_trades` beeing maxed out at this moment.

Then the long, green candle had a sell in another pair - freeing up the "trade-slot" for this pair.

**Comment by devilsinthedetail** [comment]
I'm amazed how @xmatthias is answering this when the only information he got is a "please help me" and a picture. 
I mean this is _a free & open source_ trading bot where they even get _fast & helpful_ support. At least try to make the life of people who make all of this happen a little more easy. 
Sorry for off topic (can probably deleted as it does not add anything to the issue)

**Comment by cgw-9527** [comment]
> Most likely you have other pairs which are blocking this due to `max_open_trades` beeing maxed out at this moment.
> 
> Then the long, green candle had a sell in another pair - freeing up the "trade-slot" for this pair.

**Comment by cgw-9527** [comment]
> 很可能您有其他配对正在阻止此操作，因为`max_open_trades`此时此刻蜜蜂已超出极限。
> 
> 然后，长长的绿色蜡烛在另一对中卖出-释放了该对的“交易时段”。

**Comment by cgw-9527** [comment]
> Most likely you have other pairs which are blocking this due to `max_open_trades` beeing maxed out at this moment.
> 
> Then the long, green candle had a sell in another pair - freeing up the "trade-slot" for this pair.

thank you very mach

**Comment by cgw-9527** [comment]
> Most likely you have other pairs which are blocking this due to `max_open_trades` beeing maxed out at this moment.
> 
> Then the long, green candle had a sell in another pair - freeing up the "trade-slot" for this pair.

Excuse me, why is there a signal to buy but not to buy?And it's not the same as the delay of the above buy order！
![image](https://user-images.githubusercontent.com/57701281/85988077-1eb3ac00-ba21-11ea-8354-3e9eb5c54c9c.png)
