### ISSUE TITLE
Does Freqtrade take the transaction fee of exchange into account?

### ISSUE THREAD

**Issue by AronWater** [freqtrade/freqtrade#3435]
After browsing the doc, I couldn't find that whether the transaction fee of exchange has been taken into an account in the calculation of profit, etc.

**Comment by xmatthias** [comment]
yes.
for backtesting / hyperopt / dry-run, we use the exchange default fee (which is the lowest tier).

For live, we use the fee that the exchange did apply.

**Comment by AronWater** [comment]
> yes.
> for backtesting / hyperopt / dry-run, we use the exchange default fee (which is the lowest tier).
> 
> For live, we use the fee that the exchange did apply.

@xmatthias   may I know which part of the code is handling the logic of exchange transaction fee collected by Binance? I know this is better asked in slack however I get no reply for this. I just couldn't find this part.

**Comment by hroff-1902** [comment]
> > yes.
> > for backtesting / hyperopt / dry-run, we use the exchange default fee (which is the lowest tier).
> > For live, we use the fee that the exchange did apply.
> 
> @xmatthias may I know which part of the code is handling the logic of exchange transaction fee collected by Binance? I know this is better asked in slack however I get no reply for this. I just couldn't find this part.

many places in `freqtrade/freqtradebot.py`

**Comment by xmatthias** [comment]
well - and in other places - making sure that the fee calculation is correct (which is not always easy).
