### ISSUE TITLE
Sorting filter by performance

### ISSUE THREAD

**Issue by apneamona** [freqtrade/freqtrade#3441]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.8
  * CCXT version: 1.28.49
  * Freqtrade Version: 2020.4

## Describe the enhancement
I would like to suggest a new filter that can be used instead of the ShuffleFilter, that is, it takes the current list of pairs from the filter above it and sort pairs according to their overall performance over time. At first, there’s no performance because there are no trades, but over time, pairs get performance. If they are positive, the filter pushes them to the top of the list, if they are negative, the filter pushes them to the bottom of the list. Pairs which do not jet have trades are in the middle of the list. Sorting can be done with performance value and a count of trades (as in 'get_overall_trades). Also, there is a possibility to introduce a threshold for values below a certain level.

**Comment by xmatthias** [comment]
i think this approach may have a "startup problem"

Consider a fresh bot (new database) ... it buys and is successful with ETH 3 times in a row ... 
that means, ETH will always be favored over other pairs, for no good reason other than luck in the first few trades...

I can see it beneficial after the bot runs for a few days/trades ... but at the beginning, it might be very critical.

---

That's not to say it can't be beneficial nonetheless, so might be a good enhancement, and i think this can be a good way to get started contributing to the bot as the overall understanding of bot-mechanics needed for this is not very high.

As a starting point for anyone working this Issue:
* look at how `ShuffleFilter` works (`ShuffleFilter.py`)
* to get to trades data:
  * use `Trade.get_trades()` (maybe with some filter?) to get all trades
  * use `Trade.get_overall_performance()` to get performance grouped by pair (identical to /performance output)

**Comment by Theagainmen** [comment]
This seems like a great enhancement, never thought of this!
Matthias about that startup problem, what about you set a minimum amount of trades to be done before this filter activates? Like if there are less than <50 trades in the database, don't use this filter yet. Maybe make that '50' a config value too.

**Comment by xmatthias** [comment]
yeah, absolutely, but you'll need "some" way of fallback ... so maybe shuffle until 50 trades are reached (or something like that) ...

**Comment by Theagainmen** [comment]
I was also thinking, the total amount of trades doesn't have to necessarily say that much. For example your /performance gives this output:
`
1. Pair1 55% (26)
2. Pair2 5% (5)
3. Pair3 4% (6)
4. Pair4 3% (1)
5. Pair5 2% (3)
6. Pair6 -5% (3)
7. Pair7 -5% (1)
8. Pair8 -5% (1)
9. Pair9 -5% (1)
10. Pair10 -5% (1)
`
The total amount of is now around~50, but there are multiple pairs that only have been bought once and hit a stoploss. Then there is a pair that performed very well, but also has the half of total trade amounts. Maybe we need to give each pair an equal chance before this filter activates, so around 3-5 trades per pair BUT some pairs just simply don't trigger that much or will be bought rarely, what do we do with these pairs? Or should we simply look at the total trades only? 

So yeah that's just a thought process where I'm stuck :P, let me know what you guys think.

**Comment by hroff-1902** [comment]
^^ is not it what the Edge module is doing (but on backtested trades instead of real traded ones) when it ranges the pairs by the win ratio?

**Comment by gaugau3000** [comment]
Hi guys (hi @apneamona),

I think we have to be careful about this categories of features based on statistical approach.

Extract statistics/decisions on a small sample have no sense. Even after 100 to 1000 trades on the same pair your confidence interval on return is not so good.

Will you choose a strategy that give you less than 10 trades in backtest. Here it is the same.

Edge is built the same way optimize the stop loss based on x trades but i see not any statistical to to that. The market change so quickly, i am not sure ?

Here a simulation with replacement with a bucket of 100 trades (alternate 0.5 win and -0.3 loose) that are simulated 100 times

```
from random import choices
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (20,10)
trades = np.resize([-0.3, 0.5], 100)
x = np.arange(0,100)

for i in range(1,100):
    plt.plot(x,np.cumsum(choices(trades, k=100)))

```
![randomize](https://user-images.githubusercontent.com/2643583/84071461-06c2ac80-a9ce-11ea-84f6-274b2f5e966e.png)

Maybe 5% of the plots show an equity curve below 0 event with a simple uniform distribution (can only be 0.5 or -0.3 and results with [0.5,0.5] as weight).

i should have to group by bins the plots and calculate confidence interval but i hope you see the idea : we cannot take decisions with a small sample.

You can manipulate statistics has they say plenty of things i have seen that in France with the "miracle" of chloroquine for coronavirus treatment. 

Have a nice day.

**Comment by apneamona** [comment]
Greeting!
In the chart above, I would like to cut off some of the traces that appear below zero (the green one), and beyond 20 on x axis. Why not taking a preference from a pair that has a performance of, for eg. ‘-25,00% (15)’. 
If the average profit per trade for that pair is known and is, for example, 5%.
It would mean that more likely, consecutive trades are needed for a positive outcome. Then why not allocate those resources to a more positive pair by taking/giving a preference.

Of course, filter does have a startup problem, when there is not enough trades for proper statistics.
So, there is a limit where this filter has no usability. Minimal count of trades of a single pair has to be present.
Filter, as it goes, mixes the list by pushing pairs up and down based on their performance. So sorting can be done using overall performance per pair and/or count of trades per pair, or within the last 'n' trades, or ... .
Some sort of limiting lower positions in whitelist , can be done even with 'max_open_trades". This is opposite to ShuffleFilter which tries to give an equal chance to every pair.

I’m not an IT guy, I don’t know how to code, but I kind of get along with pandas and my ideas. So I made a very rough version of this filter using pandas (only sorting per profit and count), and I started testing it on my own set, and I will report here if someone wants. In the meantime, if someone likes idea and has the time to deal with this in the proper way, it would be great. (I would give this code although it is embarrassing, rough and full of flaws, but works within limits - a toddler would code better)

**Comment by xmatthias** [comment]
> (I would give this code although it is embarrassing, rough and full of flaws, but works within limits - a toddler would code better)

I would tend to argue this as it's giving you results you expect ... i'm not sure a toddler can get to that (or even know to expect something...).

I guess there is interest in this feature (see above) - so feel free to post it here so "some random guy" can pick this up eventually ...

**Comment by apneamona** [comment]
It was a figure of speech. Some kids have far better code literacy than I have. Here it is, then.
It is a ShuffleFilter with few changes.
```
"""
Performance pair list filter
"""
import logging
import random
from typing import Any, Dict, List

import pandas as pd
from pandas import DataFrame, Series

from freqtrade.pairlist.IPairList import IPairList

from freqtrade.persistence import Trade
from datetime import timedelta, datetime, timezone

logger = logging.getLogger(__name__)

class PerformanceFilter(IPairList):

    def __init__(self, exchange, pairlistmanager,
                 config: Dict[str, Any], pairlistconfig: Dict[str, Any],
                 pairlist_pos: int) -> None:
        super().__init__(exchange, pairlistmanager, config, pairlistconfig, pairlist_pos)


    @property
    def needstickers(self) -> bool:
        """
        Boolean property defining if tickers are necessary.
        If no Pairlist requries tickers, an empty List is passed
        as tickers argument to filter_pairlist
        """
        return False

    def short_desc(self) -> str:
        """
        Short whitelist method description - used for startup-messages
        """
        return f"{self.name} - Sorting pairs by performance."

    def filter_pairlist(self, pairlist: List[str], tickers: Dict) -> List[str]:
        """
        Filters and sorts pairlist and returns the whitelist again.
        Called on each bot iteration - please use internal caching if necessary
        :param pairlist: pairlist to filter or sort
        :param tickers: Tickers (from exchange.get_tickers()). May be cached.
        :return: new whitelist
        """

        # Get the trading performance for pairs from database
        perf = pd.DataFrame(Trade.get_overall_performance())
        # update pairlist with values from performance dataframe
        # set initial value for pairs with no trades to 0
        # and sort the list using performance and count
        list_df = pd.DataFrame({'pair':pairlist})
        sorted_df = list_df.join(perf.set_index('pair'), on='pair')\
            .fillna(0).sort_values(by=['profit', 'count'], ascending=False)
        pairlist = sorted_df['pair'].tolist()
        

        return pairlist
```



`

**Comment by mrsegen** [comment]
@apneamona I'm working on writing the test cases for this. 
E.g.: A [sample pairlist](https://github.com/freqtrade/freqtrade/blob/22ff67c8f81bd75c73f03a51262f914ee2a73ded/tests/pairlist/test_pairlist.py#L296) such as `['ADADOUBLE/USDT', 'ETH/USDT', 'NANO/USDT', 'ADAHALF/USDT']` is getting reordered to `['ETH/USDT', 'NANO/USDT', 'ADAHALF/USDT', 'ADADOUBLE/USDT']`.

It seems like this is ordering is based on length of the strings. I can't imagine that anyone would prefer that ordering. Perhaps it's as good as any, though, since there's no data yet for that test case. (I'm providing mocked performance data for additional test cases specific to the PerformanceFilter.)

**Comment by mrsegen** [comment]
The added tests are passing for the PR to add @apneamona's solution. It's ready for review,

**Comment by apneamona** [comment]
Fantastic! During this period, I made some progress and extended its functionality by adding expectancy to the mix. Also, have been testing this to some degree. Expectancy is based on edge module. Code is here if you want to use it https://github.com/apneamona/freqtrade/blob/PerformanceFilter/freqtrade/pairlist/PerformanceFilter.py. I'm not knowledgeable in python enough, so there is no tests for it, or anything else really.

**Comment by mrsegen** [comment]
Cool! I’m still learning about Edge within Freqtrade.
For now, I’ll defer to @xmatthias or others more experienced with the project to comment on the approach you used. 

It’s unlikely that I’ll add it to the current PR - given that it my be hard for me to sustain current level of attention to it after the Thanksgiving break. Though, if anyone else would like to take it on, they’re welcome.

**Comment by xmatthias** [comment]
@mrsegen thanks for NOT including it into this filter :+1:  (no matter your reasons :laughing:)

i think it would make it rather difficult to use, and mainly hard to maintain.
since it'll most likely use a similar calculation than edge, we should aim to combine as much code as possible.

It's mostly known that i'm not a huge fan of edge myself (it does too much and should be split up - and is too inflexible to work with) - so i guess a filter working with expectancy should replace parts of what edge is doing currently.
