### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by eduardohem** [freqtrade/freqtrade#3450]
Hi, it is not clear for me, when a read the doc, the following situation:

If Config.json file sell strategy sell_profit_only=true, and the price goes bellow StopLoss. Will the bot sell or not?

**Comment by RaphaelNanje** [comment]
I do not believe so. Check out [xmatthias's](https://github.com/xmatthias) breakdown of it https://github.com/freqtrade/freqtrade/issues/3319#issuecomment-629743409 and the original post behind why it was implemented https://github.com/freqtrade/freqtrade/pull/265

**Comment by hroff-1902** [comment]
`sell_profit_only=true` has only effect for sell signals (generated by `populate_sell_trend()`), stoplosses are always below profit, by definition (it protects you from big losses)

**Comment by eduardohem** [comment]
thank you, that was a great doubt mine.
