### ISSUE TITLE
How to change starting balance of an alternative asset

### ISSUE THREAD

**Issue by MASalem** [freqtrade/freqtrade#3454]
Hello

I want to backtest a strategy on Bittrex data.
Is there a way I can set manually (even from inside the code?) the starting balance of a different asset (not the stake asset)?

For example, if I want to start with 5 ETH in my wallet instead of only 1000USD

Thank you in advance!

**Comment by hroff-1902** [comment]
Why do you need it? Freqtrade trades stake currency.
Assume stake currency is USD and freqtrade buys ETH for 100 USD, then it closes the position and sells ETH back, same amount it bought before. It does not absolutely matter what amount of ETH you've had before the position was opened.

**Comment by xmatthias** [comment]
in short - freqtrade would not touch your 5 ETH - but only the 1000 USD (assuing USD is the stake currency).

**Comment by MASalem** [comment]
The reason behind my question is that I actually already have ETH on my account, and I wanted to know whether freqtrade is able to take over handling those too: for example do not sell if prices are still going up
I think you answer is well detailed, thank you both

**Comment by xmatthias** [comment]
well you can run a bot with ETH as stake-currency (which is what i do...) - but you should backtest the strategy for these markets - most strategies that work on USDT don't work on ETH and viceversa... (but don't quote me on that) 😆 

anyway, as you confirmed that the question is answered, i'll close this.
