### ISSUE TITLE
SQL typo in SQL cheatsheet

### ISSUE THREAD

**Issue by pnmartinez** [freqtrade/freqtrade#3475]
## Describe the problem:

The Example snippet in the [SQL cheatsheet](https://www.freqtrade.io/en/latest/sql_cheatsheet/) is missing a closing parenthesis on the `close_profit_abs calculation`:

```
UPDATE trades
SET is_open=0,
  close_date='2017-12-20 03:08:45.103418',
  close_rate=0.19638016,
  close_profit=0.0496,
  close_profit_abs = (amount * 0.19638016 * (1 - fee_close) - (amount * open_rate * 1 - fee_open) 
  sell_reason='force_sell'  
WHERE id=31;
```

### Steps to reproduce:

  1. Copy paste and run the current snippet (the one above) on the SQL DB. 
  
### Observed Results:

  * `SQL Error [1]: [SQLITE_ERROR] SQL error or missing database (near "WHERE": syntax error)`

### Quick fix:

Just adding the parenthesis at the end of `close_profit_abs`. Documentation should be updated.
```
UPDATE trades
SET is_open=0,
  close_date='2017-12-20 03:08:45.103418',
  close_rate=0.19638016,
  close_profit=0.0496,
  close_profit_abs = (amount * 0.19638016 * (1 - fee_close) - (amount * open_rate * 1 - fee_open))
  sell_reason='force_sell'  
WHERE id=31;
```

**Comment by tehnuge** [comment]
Made [PR](https://github.com/freqtrade/freqtrade/pull/3476) to address this.

**Comment by xmatthias** [comment]
@tehnuge thanks for the PR, and thanks for reporting! :+1:
