### ISSUE TITLE
Request to use more than one stoploss type

### ISSUE THREAD

**Issue by acemi1** [freqtrade/freqtrade#3477]
## Describe your environment
(if applicable)

  * Operating system: ____Ubuntu 18.04.4 LTS
  * Python Version: _____ Python 3.6.9
  * CCXT version: _____ ccxt==1.29.5
  * Freqtrade Version: ____ freqtrade develop-9adb4d00

## Describe the enhancement

*Explain the enhancement you would like*

I have a suggestion.
Request to use more than one stoploss.

During sudden drops, trailing stoploss comes into play. However, there may be less loss stoploss. Price I want it to sell as soon as it touches an indicator line that I set. (Without waiting for the price to close)
Stoploss, trailingstoploss, populate_sell_trend or my stoploss. Whichever is triggered first, sales will take place. However, according to the triggering method, sales will take place as limit or market order.

populate_sell_trend Limit will remain an order.

**Comment by xmatthias** [comment]
i'm not sure what you're asking to be honest. 
The title suggests it has something to do with stoploss, while in the issue, you're talking about order-types with sell-orders.

you can configure sell orders to be market orders as well...

from [the documentation](https://www.freqtrade.io/en/latest/configuration/#understand-order_types)

```
order_types = {
    "buy": "limit",
    "sell": "limit",   <-- set this to market if you want sells to be a market order?
    "emergencysell": "market",
    "stoploss": "market",
    "stoploss_on_exchange": False,
    "stoploss_on_exchange_interval": 60,
    "stoploss_on_exchange_limit_ratio": 0.99,
}
```

**Comment by acemi1** [comment]
The title is correct.
I want to be able to define more than one stoploss. Let's think it is stoploss2 or stoploss3. I want to set the trigger conditions myself.

This article has no connection with populate_sell_trend.
Sales conditions written in populate_sell_trend will be preserved. In addition to populate_sell_trend I will set stoploss2.
Unlike populate_sell_trend, for stoploss2, a market order will be applied instead of a limit order. Also, I don't want to wait for the candle to close.
(populate_sell_trend My sales orders must remain limit orders.)

For example, for someone using a 4-hour or daily candle, there is only the option of stoploss or trailing stoploss in sudden price drops. If I can determine my own stoploss conditions, I can do less damage than normal stoploss or trailing stoploss.

**Comment by hroff-1902** [comment]
> I want to be able to define more than one stoploss. Let's think it is stoploss2 or stoploss3. I want to set the trigger conditions myself.

How cannot it be different from custom sell signal?

**Comment by acemi1** [comment]
I tried to explain above, for 2 reasons.
first reason.
populate_sell_trend sales form should continue as limit order.
Should stoploss2 or stoploss3 be market order

second reason
For stoploss2, I don't want to wait for the candle to turn off. The trigger should be the moment the price touches the indicator line.

populate_sell_trend, I want to continue using it as a candle close

**Comment by acemi1** [comment]
populate_buy_trend
populate_sell_trend
populate_stop_trend

order_types = {
    "buy": "limit",
    "sell": "limit", 
     "conditional_stop":"market",
    "emergencysell": "market",
    "stoploss": "market",
    "stoploss_on_exchange": False,
    "stoploss_on_exchange_interval": 60,
    "stoploss_on_exchange_limit_ratio": 0.99,
}

**Comment by xmatthias** [comment]
then configure stoploss to be market order?

I'm sorry, but this will overcomplicate both the bot code, as well as configuration for the user, so i don't think this will bring any benefit.

**Comment by orehunt** [comment]
@acemi1 maybe you want to use `informative_pairs` and use a sell signal on shorter timeframes if you are using `1d`/`4h`, you can override the order types every time the signals are checked, so you can just insert a condition  in populate_sell_trend that
```python
if whatever_triggered_stoploss2 == True:
    self.order_types["sell"] = "market"
```

**Comment by acemi1** [comment]
Only "open", "high", "low", "close" can be used in the strategy. Is it correct?
Is it possible to use instant price information in the strategy?

**Comment by acemi1** [comment]
@orehunt Thank you. I did not fully understand what you said. I'm inexperienced.

**Comment by xmatthias** [comment]
i think what you wanted to do is possible now by using the custom stoploss function, where you yourself define where the stoploss should be.
You can then set different sell order types between sell-order and stoploss order, allowing you to use market order for one type, and limit orders for the other type of sell.

Feel free to comment below / reopen if it's still unclear.
