### ISSUE TITLE
Create config_bittrex.json.example with minimum allowed rateLimit

### ISSUE THREAD

**Issue by BlueSkyTrading** [freqtrade/freqtrade#3479]
## Describe your environment
(if applicable)

  * Operating system: Ubuntu 20.04
  * Python Version: 3.8.2
  * CCXT version: 1.28.49
  * Freqtrade Version: develop-a0a00b74

## Describe the enhancement

*Explain the enhancement you would like*

Create a config.json example file with Bittrex minimum allowed rateLimit (the default value 200 is not allowed), so we can put 10000, and then users can try to test lower values.

```
<h2 class="cf-subheadline">You are being rate limited</h2>
...
<p>The owner of this website (bittrex.com) has banned you temporarily from accessing this website.</p>

```

**Comment by BlueSkyTrading** [comment]
Sorry, I found out the open ticket with ccxt [7104](https://github.com/ccxt/ccxt/issues/7104)

**Comment by BlueSkyTrading** [comment]
Reopening this request after updating to ccxt==1.29.97, I tested various rateLimit values and so for, 3000 is the minimum that didn't got me banned (yet!).
So maybe it's a good request to either have an example config file added or update the documentation.

**Comment by xmatthias** [comment]
i think the allowed rateLimit strongly depends on the mode you're running in.

I know this from Kraken - using the ccxt default (1000) - freqtrade can run perfectly fine in trade mode with about 20 pairs.
Downloading however requires a rateLimit of ~3100.

so - which mode are you running in where you think 3000 is required?

**Comment by BlueSkyTrading** [comment]
right now I'm in dry-mode, 3000 works fine for both dry-mode and data-download (2500 gets me banned straight away and 30mn candles of last 30 days took me 3 hours);
I'll go live later today (I can confirm live mode rateLimit value as well).

**Comment by xmatthias** [comment]
just keep in mind that this ratelimit can have an impact - it'll download the first pair in the pairlist at the hour, the 2nd pair 3 seconds later - and the 32nd pair 32 * 3s (~2 minutes) after the candle actually closes ...

with ratelimit 1000, it's 32 seconds later (in your case) - which can be late, but i think is kinda acceptable - but 2 minutes - i don't know...

I normally recommend to not use exchanges with that strickt rate-limits in dry / live run - as this timing CAN have an impact (the size impact itself depends on the strategy though).
Bittrex used to work ok a while ago - but they since lost a lot of volume - and increased their rateLimit requirements quite a lot ...

**Comment by hroff-1902** [comment]
with rateLimit=500 (the default one defined in the config for Bittrex created from actual template with `new-config`) I ran download-data (for 200 days, 1m and 5m) -- well, it shown a few temporary errors (only a few ones), but they were okay in the next retry...

The situation can also depend on the network you are working from: if it's not a VPS with a dedicated "white" IP address, for example if the bot is running from your home-internet channel provider, the exchange will calculate you and other users of the provider together, since you all are requesting the data using the limited amount of IP addresses, the gateway host used by the internet provider... Same if you run multiple bots on same exchange -- they will be counted together...

**Comment by BlueSkyTrading** [comment]
very informative discussion, meaning Bittrex became bots (non)friendly, and any enhancement from our end will never fix their API limitations (unless I'm trading few pairs that I can count on my hand)...

**Comment by hroff-1902** [comment]
I just run same downloading of data with rateLimit = 500 once again, no errors at all...

**Comment by hroff-1902** [comment]
for the latency of fetching data for many pairs @xmatthias pointed out above -- I guess only fetching data via webSocket (when exchange pushes new ohlcv data) can actually work well...

**Comment by BlueSkyTrading** [comment]
I run dry-runs in my local VM at home and live bot in dedicated VPS, yesterday I got banned in dry-run with 200, 500, 1000, 2000 and 2500.
3000 is the minimum that I'm allowed in dry-run for now, so you recommend me to go live in VPS and test with 500?

**Comment by hroff-1902** [comment]
> I run dry-runs in my local VM at home and live bot in dedicated VPS, yesterday I got banned in dry-run with 200, 500, 1000, 2000 and 2500.
> 3000 is the minimum that I'm allowed in dry-run for now, so you recommend me to go live in VPS and test with 500?

yes, get a free/cheap VPS (DigitalOcean for example -- they have coupons that allow you to use the services for free for several months) and compare the results...

**Comment by BlueSkyTrading** [comment]
perfect, already have a VULTR High-Frequency VPS ready ($6/month), will test and update

**Comment by acemi1** [comment]
I am using this vps. You can review.
https://contabo.com/?show=vps
4 cpu 8 gb ram 200gb ssd 5Euro/month

**Comment by BlueSkyTrading** [comment]
looks competitive, couldn't find uptime page?

**Comment by BlueSkyTrading** [comment]
ok, I just mounted a VPS in Germany and got banned with rateLimit 200, 500, 1000 and 2000...
Only 3000 like my home VM did work...

**Comment by xmatthias** [comment]
> I guess only fetching data via webSocket (when exchange pushes new ohlcv data) can actually work well...

websockets will not allow you to get ANY historic data - just the latest candle / latest change ... so it's only suited for very specific areas ... but definitely not for ohlcv downloading.

**Comment by BlueSkyTrading** [comment]
@xmatthias @hroff-1902, ok, yesterday the 15m candles weren't supported by Bittrex, and today they removed the 30m as well...
```
2020-06-15 19:01:19,976 - freqtrade.commands.trade_commands - ERROR - Invalid timeframe '30m'. This exchange supports: ['1m', '5m', '1h', '1d']
```

**Comment by xmatthias** [comment]
well don't tell them that you use freqtrade - it's not relevant from an API perspecive anyway.
just tell them you're using ccxt (bittrex is a certified exchange there - so they do have some interrest in this).

their [api documentation](https://bittrex.github.io/api/v3#tag-Markets) (search for `/markets/{marketSymbol}/candles/{candleInterval}/recent`) only lists the 4 supported candle types - so while ccxt may had them listed before, the other types may not have worked.

**Comment by BlueSkyTrading** [comment]
ok, closing this issue as trading in their platform has no restriction (compared to using the API), all timeframes are available, but one big major issue is the liquidity, half my buy orders get cancelled...

**Comment by xmatthias** [comment]
i know - they have very low trading volume for most pairs (except for a few - but that's why i like to use them anymore).


just look at https://coinmarketcap.com/rankings/exchanges/ - and filter on "avg liquidity" - they move down the list quite far ...

**Comment by BlueSkyTrading** [comment]
@xmatthias , don't forget when coinmarketcap introduced avg. liquidity, Binance disputed the process because it lost the top exchange title until it was acquired last month or 2 for 400M USD by it...

**Comment by xmatthias** [comment]
kraken is popular as they do fiat trading, which binance does not really do ...

so i do understand this - but i also understand the concerns  - i honestly forgot that binance aquired them.
surely, binance is now rated "better" - but i doubt they'd target bittrex specifically ... not with the volume i observed there
