### ISSUE TITLE
Could not get balance due to AuthenticationError

### ISSUE THREAD

**Issue by Maurits14** [freqtrade/freqtrade#3480]
#2957  Describe your environment

  * Operating system: Dietpi
  * Python Version: 3.7.2 (`python -V`)
  * Freqtrade version: freqtrade develop-10ed0d11
  * CCXT version: 1.29.52
 
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

I tried to start trading for the first time with real money. While executing my trading command the following Error occurred: "Could not get balance due to AuthenticationError. Message: binance {"code":-1022,"msg":"Signature for this request is not valid."}" 

The only change I made with the previous run (dry-run) (which worked): 
I changed "dry-run" from true to false.

Could you please be so kind to help me with this problem?

**Comment by hroff-1902** [comment]
please fill other fields in the form:

  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

**Comment by Maurits14** [comment]
I have added the CCXT and Freqtrade version

**Comment by xmatthias** [comment]
well the message is quite clear - the api key is invalid or inexistent.

Best read [Switch to production](https://www.freqtrade.io/en/latest/configuration/#switch-to-production-mode) on what is needed for this to work.

**Comment by Maurits14** [comment]
Thank you. I don't know what happend. I just copied the same API codes and pasted them again in the config file, which worked... I guess I made a typo.

Again thank you for your help!

**Comment by hroff-1902** [comment]
I dry-run the API keys are not used, freqtrade does not authenticate itself and is only using public API data (since no orders are created on exchange and no wallet data is used). So if you have had wrong API key/secret in the settings, it won't tell you anything about this before you switch to live-trade mode...
