### ISSUE TITLE
Trade.get_trades() returning empty list 

### ISSUE THREAD

**Issue by leeu3581** [freqtrade/freqtrade#3489]
Have you searched for similar issues before posting it?

Yes- I tried searching Trade.get_trades and trade not returning etc..

Did you have a VERY good look at the [documentation](https://www.freqtrade.io/en/latest/) and are sure that the question is not explained there?

Yes. I looked at the example code given in the docs.

```
from freqtrade.persistence import Trade
from datetime import timedelta, datetime, timezone
# Put the above lines a the top of the strategy file

#Within populate indicators (or populate_buy):
if self.config['runmode'] in ('live', 'dry_run'):
   # fetch trades for the last 2 days
    trades = Trade.get_trades([Trade.pair == metadata['pair'],
                               Trade.open_date > datetime.utcnow() - timedelta(days=2),
                               Trade.is_open == False,
                ]).all()
    # Analyze the conditions you'd like to lock the pair .... will probably be different for every strategy
    sumprofit = sum(trade.close_profit for trade in trades)
    if sumprofit < 0:
        # Lock pair for 2 days
        self.lock_pair(metadata['pair'], until=datetime.now(timezone.utc) + timedelta(days=2))
```

## Describe your environment

  * Operating system: MacOS Sierra
  * Python Version:3.7.7
  * CCXT version: ==ccxt==1.27.1
  * Freqtrade Version: freqtrade 2020.4
  
## Your question

Although max_open_trades is 10, I would like it to not open all 10 trades on the same day. To do this, I tried adding the modified example code into the populate_buy_trend() function inside the strategy. 

```
trades = Trade.get_trades([Trade.pair == metadata['pair'], 
Trade.open_date > datetime.utcnow() - timedelta(hours=24),
Trade.is_open == True,
                ]).all()
num_open = len(trades)
 if num_open > 5:
self.lock_pair(metadata['pair'], until=datetime.now(timezone.utc) + timedelta(days=2))
```
However, Trade.get_trades does not return anything. I tried print(trades) but when I print this it prints an empty list [], even after making trades (and there are open trades in the dry run db). This was run in dry mode. I'm not sure why this is happening. 

I would really appreciate your help!
Thanks in advance.

**Comment by xmatthias** [comment]
well you filter on the current pair (`Trade.pair == metadata['pair']`) ... 

Since you're doing this in `populate_buy_trend()`, this cannot return a result, as `populate_buy_trend()` is currently only called for pairs which it will try to open a trade for (*subject to change in the near future).

Either remove this condition ... or reverse it (but removing it will be better for what you're trying to do).

**Comment by leeu3581** [comment]
Ah got it. Thank you!
