### ISSUE TITLE
WARNING - Outdated history

### ISSUE THREAD

**Issue by Pascal66** [freqtrade/freqtrade#3492]
## Describe your environment

  * Operating system: Ubuntu 20 LTS
  * Python Version: 3.8.2
  * CCXT version: 1.28.49
  * Freqtrade Version: develop
  
## Describe the problem:

Warning ticks

### Steps to reproduce:

  1. Update to latest 
  2. launch
  
### Observed Results:

  * What happened?
See log
  * What did you expect to happen?
No warning

### Relevant code exceptions or logs

  ```
  020-06-16 18:35:49,866 - freqtrade.strategy.interface - WARNING - Outdated history for pair BCH/USDT. Last tick is 50 minutes old
2020-06-16 18:35:51,321 - freqtrade.strategy.interface - WARNING - Outdated history for pair LTC/USDT. Last tick is 20 minutes old
2020-06-16 18:35:52,792 - freqtrade.freqtradebot - INFO - No currency pair in active pair whitelist, but checking to sell open trades.
2020-06-16 18:35:52,908 - freqtrade.data.converter - INFO - Missing data fillup for LTC/USDT: before: 101 - after: 282
2020-06-16 18:35:52,940 - freqtrade.data.converter - INFO - Missing data fillup for BCH/USDT: before: 49 - after: 269
  ```

**Comment by xmatthias** [comment]
well, in general, outdated history is just a warning and can happen if a pair did not have any trades in the last X minutes.

Now the "missing data fillup" suggests that maybe it was a exchange downtime - but without knowing the exchange, we can't confirm that either...

**Comment by Pascal66** [comment]
Bittrex wich seems working fine.
Not happen 5m before the git update

**Comment by xmatthias** [comment]
there is nothing wrong with this behaviour - as said, it's a warning, that there was no candle in the last X minutes.

if you look at the chart, you'll see that bittrex does not have much volume - so the warning is justified, as there were no trades for the last 20 minutes.

for LTC-USDT (bittrex reverses pairs) it's a matter fo just opening the chart to find periods with half hours / hours wihtout ANY trade happening - and exactly this is what the above warning is showing.

![2020-06-17-061249_1389x603_scrot](https://user-images.githubusercontent.com/5024695/84854297-9406a080-b061-11ea-816d-9d11613f2b61.png)

**Comment by Pascal66** [comment]
Ok Thanks.

**Comment by xmatthias** [comment]
just to clarify this further - the warning - `Outdated history for pair LTC/USDT. Last tick is 20 minutes old` - will prevent freqtrade from buying at this point in time. 

It will continue to check and as soon as a new candle (with volume) is posted, buying is possible again.

Now the change was with ccxt, which switched from v2 to v3 of the Bittrex API, which returns a sparse array (where 0 volume candles are not reported anymore). 

if 0 volume candles are included in the API response, then the warning will not be shown - but the base problem (pair has no volume in the last X candles) will still be there.

In that case, this check should be done in the strategy by adding `dataframe['volume'] > 0` (as suggested in the documentation).

**Comment by Pascal66** [comment]
That's what I suspected (change in ccxt), so that why I read again the doc and apply the always good suggestion

**Comment by amaanr** [comment]
@xmatthias curious if there could be any other reason for this error to show up? I'm using `binance` and have the `dataframe['volume'] > 0` in my strat. I've been getting the `Outdated history for pair LTC/USDT. Last tick is 96 minutes old` error on both `LTC/USDT` and `XRP/USDT`

**Comment by xmatthias** [comment]
the volume condition has nothing to do with it, that's mostly for backtesting.
Depending on the exchange, this error can be caused by low volume, or by your system clock beeing out of date.

Now on binance, that's rather unrealistic - so best check your clock.

**Comment by marcosfreitas** [comment]
I'm getting this same warning for all my pairs.
I changed the timezone from default UTC to America/Sao_Paulo but it didn't fix.
I'm running the bot with docker-compose inside an EC2 instance at AWS.

![image](https://user-images.githubusercontent.com/1065688/134993004-688912b7-ca36-4d25-9a03-38480a1f1ff9.png)

My current EC2 `timedatectl` output:

```
               Local time: Mon 2021-09-27 19:20:11 -03   
           Universal time: Mon 2021-09-27 22:20:11 UTC   
                 RTC time: Mon 2021-09-27 22:20:11       
                Time zone: America/Sao_Paulo (-03, -0300)
System clock synchronized: yes                           
              NTP service: active                        
          RTC in local TZ: no
```

**Comment by xmatthias** [comment]
Times are always used in UTC, so timezone itself will not matter.
The important thing is that the UTC time is aligned to the global UTC time.
