### ISSUE TITLE
 Unable to initialize markets. Reason: kraken fetchMinOrderAmounts HTML page markup has changed

### ISSUE THREAD

**Issue by GuyT07** [freqtrade/freqtrade#3494]
Error message: 

`reqtrade.exchange.exchange - WARNING - Unable to initialize markets. Reason: kraken fetchMinOrderAmounts HTML page markup has changed: https://kraken.zendesk.com/api/v2/help_center/en-us/articles/205893708`

So it seems the markup has been changed 😝 

2020-06-17 18:53:01,007 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/<user>/git/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/Users/<user>/git/freqtrade/freqtrade/commands/optimize_commands.py", line 48, in start_backtesting
    backtesting = Backtesting(config)
  File "/Users/<user>/git/freqtrade/freqtrade/optimize/backtesting.py", line 65, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/Users/<user>/git/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 37, in load_exchange
    exchange = Exchange(config, validate=validate)
  File "/Users/<user>/git/freqtrade/freqtrade/exchange/exchange.py", line 122, in __init__
    self.validate_stakecurrency(config['stake_currency'])
  File "/Users/<user>/git/freqtrade/freqtrade/exchange/exchange.py", line 296, in validate_stakecurrency
    quote_currencies = self.get_quote_currencies()
  File "/Users/<user>/git/freqtrade/freqtrade/exchange/exchange.py", line 227, in get_quote_currencies
    return sorted(set([x['quote'] for _, x in markets.items()]))
AttributeError: 'NoneType' object has no attribute 'items'

### Describe your environment
Operating system: macOS Catalina
Python Version: Python 3.7.7
CCXT version: 1.29.5
Freqtrade Version: 2020.5

**Comment by xmatthias** [comment]
Please fill out the issue template.

As stated when opening this issue - we'll close the issue if that's not filled out.

---

## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

**Comment by GuyT07** [comment]
Bump, updated

**Comment by xmatthias** [comment]
i'd say ccxt is at fault, but it really isn't, as the latest version (1.30.x) does work.
kraken is changing around stuff (all the time, basically) ...

ccxt is good at keeping up with that - but keeping up with ccxt updates did push ~5 new updates per day - which is unreasonable to merge as we're just busy merging updates ....


Either way - it seems fixed for me in the latest ccxt version (i just refreshed my kraken data with it)

You can easily do this by running `pip install -U ccxt`.

(this is why we need the version template - as it helps us quickly determine "this version -> most likely this problem" )

**Comment by GuyT07** [comment]
It works! Great. Closing the issue. Thank you for your fast response and time!
