### ISSUE TITLE
Docker strategy issue

### ISSUE THREAD

**Issue by rdws1323** [freqtrade/freqtrade#3496]
Hi,

I recently switched over to docker to run freqtrade and ran fine on initial setup but when change my strategy file doesnt seem to find strategy with below error:

freqtrade.exceptions.OperationalException: Impossible to load Strategy 'SampleStrategy'. This class does not exist or contains Python code errors

Strategy located in correct folder and names match on both strategy file and .yml
Can anyone please provide assistance.
Thanks very much

**Comment by xmatthias** [comment]
Please specify the command you are using when starting the docker container.

The most likely cause is that you are not following the [freqtrade docker](https://www.freqtrade.io/en/latest/docker/#docker-quick-start) documentation page - and you're therefore missing the mounts docker requires.

**Comment by rdws1323** [comment]
docker-compose up -d
Documentation page is working up until the strategy section.
Everything runs until I try and add a new strategy then says it cannot find, even when I revert back to SampleStrategy it says it cannot find it.
Tried deleting folder and restarting whole setup and still doesn't work.
Apologies in advanceif missing something simple here.

**Comment by xmatthias** [comment]
where exactly do you place the strategy (in which folder)

and how did you edit the docker-compose file?

**Comment by xmatthias** [comment]
@rdws1323 is this still an issue, or have you been able to resolve this problem?

**Comment by xmatthias** [comment]
I'll close this assuming it's been solved.

Feel free to comment below if it's not been solved, so we can reopen this issue and investigate further.
