### ISSUE TITLE
Ticker Interval Error

### ISSUE THREAD

**Issue by DustinScharf** [freqtrade/freqtrade#3501]
## Describe your environment

  * Operating system: Ubuntu 20.4 (Server)
  * Python Version: 3.8.2 (`python -V`)
  * CCXT version: 1.28.49 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.5 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I don't know if this is a bug or I made a mistake here but I get this error if I send the "/start" command via Telegram (if I start without Telegram I get the same error).

![image](https://user-images.githubusercontent.com/56603727/85233433-62495d00-b406-11ea-8a32-b7724b8d6dd8.png)

Within a VM It works fine, but on a VPS it does not.

**Comment by xmatthias** [comment]
You must have ticker_interval defined in either strategy or configuration or as comand line argument. 

The pc/server got nothing to do with it (assuming both run the same version).

Unless you use develop in the working version, as this setting will be renamed in the upcomming release to timeframe.

**Comment by DustinScharf** [comment]
Thank you, sir, I copied the files from my local machine and defined it as `timeframe`, I should have checked this...
