### ISSUE TITLE
REST-API: Get token and execute commands

### ISSUE THREAD

**Issue by OtenMoten** [freqtrade/freqtrade#3512]
* Operating system: Docker on Synology NAS
  * Docker Release
  * Freqtrade Version: Master 
  * Synology NAS IP Address: 192.168.178.42
  * Docker Port: 808 to 8080

Freqtrade Config
```
"api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "jwt_secret_key": "somethingrandom",
        "username": "Freqtrader",
        "password": "SuperSecret1!"
}
```

Using Postman to send requests. I did http://192.168.178.42:8080/api/v1/ping and got 
```
{
    "status": "pong"
}
```

Working fine, but I changed GET to POST and put in body:
- username
"Freqtrader"
- password
"SuperSecret1!"

I did http://192.168.178.42:8080/api/v1/token/login and got:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

What else I need to do to get it working? Where to place the "jwt_secret_key" : "somethingrandom" in Postman? Header? Body?

**Comment by xmatthias** [comment]
i would recommend to use the `scripts/rest_client.py` helper.

It has a wrapper for all Rest methods and will handle authentication for you.

If you're keen to do it yourself:
the Rest-api uses Basic-auth (throughout - for all endpoints) - or you can request a JWT token and pass that in.

Explaining how Either of the 2 methods work is beyond this project - google will help you if you're unfamiliar with these concepts.

**Comment by OtenMoten** [comment]
Hello @xmatthias 

I can't, just got Postman. There is no Python or Linux console at the Synology. 

I've tried couple of hours and investigating. I don't get the token, but /ping works. 

Is the config correct I mentioned above? I can't get a JWT token from the Docker container, but got a ping. Therefore, the connections works but how to get the token?

**Comment by OtenMoten** [comment]
@xmatthias 

Thanks for the note to do Basic-auth - it should be mentioned in the docs. I've tried for a couple of hours, it works now. Thank you.

**Comment by xmatthias** [comment]
On a side note - Synology usually does have Python ... although maybe an outdated version ...

also - i assume you're querying from another pc (not directly from the synology) - which would enable the rest script again :)

you might also wanna have a look at https://github.com/freqtrade/frequi - that'll implement the API as well :)

**Comment by OtenMoten** [comment]
You're right.  My Synology DSM is in the living room and I sit in front of my pc ;D

Thanks for the link.

**Comment by OtenMoten** [comment]
Lol, there is Vue and React stuff. Never worked with. I just sitting here and develop a WebApp with Spring MVC and Thymeleaf.

**Comment by xmatthias** [comment]
well guess what the Vue app is going to do :) (it does not include React...).

My point is - rather than everyone developing his own webapp seperately, combining efforts will lead to better results...

**Comment by xmatthias** [comment]
gonna close this as i think the original question has been answered.
