### ISSUE TITLE
What is the use of xxx/xxx-trades.json files?

### ISSUE THREAD

**Issue by fogkaspoker** [freqtrade/freqtrade#3516]
## Describe your environment

  * Operating system: Proxmox server
  * Python Version: 3.8.1
  * CCXT version: 1.30.17
  * Freqtrade Version: freqtrade 2020.5

  
## Your question

What is the use of the trades files?, and what do you mean by re-sampling locally as written in the documentation?

Thanks in advance,

**Comment by xmatthias** [comment]
Trades files are files containing raw trades.

They're needed as some exchanges (mainly kraken) do not offer more than a few candles of history via the OHLCV endpoint.
Therefore, we need to download the raw trade data and build candles out of that.

To facilitate updating (you can run this command every few days and you'll get an incremental set of data - speeding up subsequent updates by avoiding to download the full history again), these files are kept in the data directory - but they are not used unless a new download-data command for the same pair with `--dl-trades` (or it's corresponding configuration option) are ran again.

**Comment by fogkaspoker** [comment]
Ok, so besides kraken, the raw data can be used to further customize.
Thanks

**Comment by xmatthias** [comment]
define "further customize" ?

in theory you could use it - but i don't know what for ...

**Comment by xmatthias** [comment]
I think this issue was explained as a combination of this and #3515.

Feel free to let us know if it's not solved so we can reopen.
