### ISSUE TITLE
Buy and sell at 'CLOSE'

### ISSUE THREAD

**Issue by operational13** [freqtrade/freqtrade#3522]
Hi all,

I was wondering if anyone could point me in the right direction to modify the live/dry run scripts to operate similarly to the backtesting script. The major difference I see is that all buy/sell/ROI/SL/TSL actions occur at the end of candles in backtesting. I would like to know if I can also make this occur in live/dry run.

Matthias has previously mentioned this:
"yes. the incomplete candle's close would repaint - change every few seconds.
That creates very unreliable signals - there's whole whitepapers about repainting as it's a huge problem ..."

And this had led me to question if live/dry runs could mirror backtesting.

Any thoughts/comments would be appreciated!
Thank you!

If you only use candle data and technical indocators for buy / sell signals, the signals will only change at the full candle.
However - if you use realtime data (orderbook, ticker) - then signals may change in between too.

Also - selling is always possible via either ROI, stoploss or trailing stoploss - as these are evaluated at every iteration - and not just at fulll candles (otherwise you might blow your stoploss big-time ...).

_Originally posted by @xmatthias in https://github.com/freqtrade/freqtrade/issues/3498#issuecomment-646993519_

**Comment by operational13** [comment]
Edit: Having seen other trading bots, I notice that they enable the option to enter/exit trades at 'CLOSE', instead of just 'limit' and 'market' orders. Even if 'CLOSE' would not be possible in crypto with these exchanges (I'm using Binance), I am almost certain it would be possible to act on the data at the close of candles.

Why? Well, my biggest issue is that SLs and TSLs are triggering within the candle, even though the bigger trend shows that these entered trades would continue in their uptrends. The only way to prevent these triggers is if decisions are only made at the end of candle. I may be completely wrong, so please correct me and educate me!

A question I have for anyone experienced with bots is: is there a way for this backtesting method to be used as an actual live method? Or am I missing something?

Thank you once again with my tedious questions!

**Comment by xmatthias** [comment]
I think you're approaching this wrong / search for the wrong thing.

If stoplosses trigger too early - then your stoploss / trailing stoploss is too tight.

Stoploss must ALWAYS be evaluated at every iteration (ideally even more often - but that's what we got stoploss-on-exchange).
You'd not want the stoploss to be at 5% - but only evaluated at the close of a 1h candle. Crypto can move -30% in one candle - so you'd blow your stoploss, and your risk in the market would not be the 5% you specified, but 100% (assuming it drops 100%).

This behaviour is however also mirrored in backtesting.
While the time of the stoploss is unknown during backtesting - the price is known (it's the trade's open - fee -5%) - and that's the price the stoploss (and roi) are recored with.
So backtesting does sell intra-candle as well - it just doesn't record the time (as the time is unknown). But you should be able to see this in longer timeframes in the charts - where you have a long candle (up or down) - and the sell price is in the middle of that (between open and close).

**Comment by operational13** [comment]
Hi Matthias,

Thank you for your reply. As a beginner to trading and algotrading, I find your info very useful! 

I think I understand what you're saying. It doesn't matter if the candle is closed or not, the SL and TSL will still activate accordingly?

However, I do have one question. In backtesting, the data available is: OHLC. In backtesting, does the bot assume the price of the asset to rise to (1) HIGH and then drop to CLOSE, or does it (2) rise to HIGH, then LOW, then CLOSE?
If it only does (1), then surely the TSL would not activate on a positive candle (under specific TSL conditions)?
Therefore, to me it matters the order in which the bot performs calculations, as this could impact the performance of dry/live runs.

I hope what I say makes sense? Thank you for your time!

**Comment by xmatthias** [comment]
It's all in the documentation about [assumptions made by backtesting](https://www.freqtrade.io/en/latest/backtesting/#assumptions-made-by-backtesting).

for TSL evaluation, it's high, then low, then close.

**Comment by xmatthias** [comment]
I'll assume this as answered.
 
Feel free to open a new issue (for new questions) or comment below if you still have questions regarding this question.
