### ISSUE TITLE
Introduce SlippageFilter

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#3524]
To discuss possible enhancement: Introduce SlippageFilter.

* calculate estimated slippage against orderbook data: find orderbook.ask[n] which covers stake_amount if it's placed as the market order (i.e., find `n` for which `sum(orderbook.ask, 0, n) > stake_amount`), estimated slippage (as ratio) is then `(orderbook.ask[n] - orderbook.ask[0]) / orderbook.ask[0]`.
* filter out pairs for which `estimated slippage > max_slippage_ratio`
* as a possible enhancement: add a coefficient (multiplier) M, which is used in calculations of slippage. For example, if M = 3, than the estimated slippage is calculated against `amount = 3 * stake_amount` instead of `stake_amount`
* as a possible enhancement: estimate/filter out pairs for the bid side of the orderbook as well. This can either be implemented as an attribute, defining the sides used (bid, ask, both bid and ask) or (which can be easier for users) as separate pairlist filters AskSlippageFilter/BidSlippageFilter

This can normally be used if market orders are used, but can also be used with limit orders, just to filter out inactive pairs same way, even if limit orders are used.

**Comment by xmatthias** [comment]
I'm not sure how / what you'd filter with this...

for inactive pairs - i think VolumeFilter with a reasonable number should filter these out (usually inactive pairs won't be in the top 30 pairs of an exchange - at least not on binance), that in combination with SpreadFilter (if a pair is very inactive, it's likely to have a higher spread).

for slippage - i assume you're thinking about using the volume level at each step of the orderbook ...

I don't think that'll work out, as orderbooks change multiple times per second - so the moment you know "not enough volume there" - it'll be different again, and might have a huge order come in - or worse - you determine "enough volume there" - but then that order is cancelled (or filled, does not matter).


If this is really necessary for a strategy, i think this would make more sense to be implemented in the new callback methods going to be introduced in #3497 - which are called right before placing the order to the exchange (giving you a "last moment" chance to cancel your buy).


---

Apart from the speed problems - the benefit of this is close to 0 if you look at binance (i know this for binance, but assume other exchanges have similar "features").
Binance allows "iceberg" orders - so say i want to buy 100 ETH - i can post 1 ETH to the orderbook at my desired price, but when someone comes in and tries to sell 50 ETH - he'll get filled by my "iceberg" - hidden order in the orderbook.

All pairs i used so far at binance have this "iceberg Allowed" flag to true ... so the real value of the order can be concealed - so you might determine that there is slippage - but really there won't be as there's a hidden order in the orderbook.

**Comment by hroff-1902** [comment]
the idea raised after reading the blog post: https://blog.shrimpy.io/blog/cryptocurrency-trading-101-exchange-market-slippage, it's not for my concrete strategy

the Blackbird bot (currently inactive; https://github.com/butor/blackbird) also have similar setting: see OrderBookFactor
(the additional idea for the multiplier above is inspired by this)

> OrderBookFactor | 3.0 | In order to be executed as fast as possible and avoid slippage, Blackbird checks the liquidity in the order books of the exchanges and makes sure there are at least 3.0 times the needed liquidity before executing the order

yes, it filters out inactive pairs, in a yet another way than Volume filter (using orderbook info instead of volumes)

actually, all other filters (Spread, Volume, Price/Precision) can also be implemented in the strategy, but we offer them as filters to simplify the usage

**Comment by xmatthias** [comment]
the problem i have with this is the time when filters run.

Pairlist filters run at the start of the iteration, for every pair.
This filter however, you'll only need when the actual order happens - so we'd end up pulling orderbook for 50 pairs, while only one produced a signal - so we really could've run it for just one pair.

---
## Check depth of market

Also - `_check_depth_of_market_buy()` does almost exactly what you're proposing (without multiplication, only looking at the first step of the orderbook) - but when the buy decision is actually taken.


However - the way to go for me would not be to have it as pairlist filter (as that runs on inopportune times), but to extend the "check_depth_of_market" feature to (maybe) work on both buy and sell (but on the other hand - you'll have to get out of the trade anyway, so even if you don't "like" the market at that point - staying in the trade for too long can cost you more than slippage would) ...

However, extending that feature with the addition you propose above (orderbookfactor, checking multiple levels) ... does make more sense than implementing it as a pairlistfilter.

**Comment by hroff-1902** [comment]
can also be cached, as other filters using market info

**Comment by xmatthias** [comment]
if you cache it, then it's pointless information - as slippage now will not be the same than slippage 10 seconds from now (at least not on a decently active pair).
