### ISSUE TITLE
Execute populate_sell_trend only when profit > 0% 

### ISSUE THREAD

**Issue by aarensan** [freqtrade/freqtrade#3525]
## Describe your environment

  * Operating system: MAC OS X Mojave
  * Python Version: 3.8 
  * CCXT version: 1.30.2
  * Freqtrade Version: develop-b13bb888
  
## Execute populate_sell_trend strategy only when profit is > 0% ?
Most of the times my strategies behave like if roi wins, then the sell signals lose and vice versa. Is there a possibility to calculate the sell signals profit first and if it is above 0% execute the sell signal otherwise do not sell.

**Comment by pan-long** [comment]
You should be able to set `sell_profit_only` to True in your strategy.

Example here: https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/Strategy001.py#L48

**Comment by aarensan** [comment]
Well, that's what I had overseen all the time. So, I assume I tried those experimental settings in the beginning and then it resulted into an error so I didn't use them anymore. If `sell_profit_only` is in the strategy file, will it be overwritten from the config file?

```
"ask_strategy": {
        "price_side": "ask",
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
```

**Comment by pan-long** [comment]
You can refer to the doc:
https://github.com/freqtrade/freqtrade/blob/c10545ef8957659c2587d24c0f091739e779ce2d/docs/configuration.md#parameters-in-the-strategy

So config file will override strategy for those values.

**Comment by aarensan** [comment]
Thank you, got it.

**Comment by xmatthias** [comment]
Yes config will overwrite strategy configurations. Best remove it from the configuration if you're testing with different strategies, which require different settings for this (that's how i do it, anyway).
