### ISSUE TITLE
How can I make long/short contracts of BTC/USDT pair?

### ISSUE THREAD

**Issue by zzm88** [freqtrade/freqtrade#3528]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
We have already an issue open requesting the possibility to short in #892 
Feel free to subscribe to that to get updates as to when we'll be supporting this.
