### ISSUE TITLE
[Feature Request] Buy & Sell fill RPC message

### ISSUE THREAD

**Issue by JamesGDiaz** [freqtrade/freqtrade#3542]
# Describe your environment

- Operating system: Raspbian
- Python Version: 3.8
- CCXT version: 1.30.2
- Freqtrade Version: develop-11290645

# Describe the enhancement
Just a simple webhook and/or telegram notification when an order is filled, perhaps the same as the buy/sell notification with these extra parameters:

### Buy/Sell Filled
- partial_fill_pct
- filled_complete _(boolean)_
- fill_notification_timestamp

**Comment by xmatthias** [comment]
To be honest, i don't think that's a particularily good idea (not for telegram, anyway)

Think about the sequence of a trade after this:
- buy signal (get a notification) 
- buy is filled (get a notification) 
- sell-signal (get a notification)
- sell is filled (get a notification)

Now multiply this by 5 parallel pairs and a quickly moving strategy, and you'll be bombarded with messages.

Implementing the notification in itself would not be difficult i think - my bigger worry is the spam potential of such a message.

**Comment by hroff-1902** [comment]
may this be controlled by the user?

**Comment by JamesGDiaz** [comment]
Allowing the user to control this would be ideal, I was thinking the same
way webhook notifications work.

The reason I'm thinking about this is because I'm currently developing an
Android app using a nodejs proxy, and when I get a buy notification, I
don't really know wether I'm really gaining or losing money until it fills,
and I don't know if it's filled unless I check the logs or check the
exchange.

Perhaps it would be useful too if this was automatically disabled for
market orders, since both messages would trigger at pretty much the same
time.

I can try implementing it myself but I'm not familiar with the codebase
and, but from what I looked earlier today, it doesn't seem too difficult,
I'd just have to know where things are.

**Comment by xmatthias** [comment]
The only thing i don't understand is why everyone works on his own UI instead of working together on one thing.

I now know of 2 seperate people working on an android app, one did a QT application - and we've got [freqUI](https://github.com/freqtrade/frequi) - which will be responsive (in the end, not necessarily now) - so will also work on phones.

**Comment by JamesGDiaz** [comment]
Well I didn't know about those, only about frequi and only found out about
it about a week or so ago.

Anyway if you can point me in the right direction, I can try and do this
myself and you decide if it gets merged.

**Comment by hroff-1902** [comment]
> The only thing i don't understand is why everyone works on his own UI instead of working together on one thing.
> 
> I now know of 2 seperate people working on an android app, one did a QT application - and we've got [freqUI](https://github.com/freqtrade/frequi) - which will be responsive (in the end, not necessarily now) - so will also work on phones.

maybe people try to monetize/earn money on side services based on Freqtrade...

**Comment by jaesbit** [comment]
> To be honest, i don't think that's a particularily good idea (not for telegram, anyway)
> 
> Think about the sequence of a trade after this:
> 
>     * buy signal (get a notification)
> 
>     * buy is filled (get a notification)
> 
>     * sell-signal (get a notification)
> 
>     * sell is filled (get a notification)
> 
> 
> Now multiply this by 5 parallel pairs and a quickly moving strategy, and you'll be bombarded with messages.
> 
> Implementing the notification in itself would not be difficult i think - my bigger worry is the spam potential of such a message.

You are right, a notification for purchase and another for filled would be excessive, but an interesting alternative could be to edit the message once it is filled

I checked the bot that uses this solution has implemented the functionality to edit messages [on this link](https://python-telegram-bot.readthedocs.io/en/stable/telegram.message.html#telegram.Message.edit_text)

**Comment by ghost** [comment]
I think it would be good beacuase I actually prefer to be notified of filled orders instead of created orders (sell/buy signals).
