### ISSUE TITLE
Plotting dataframe when using DataProvider

### ISSUE THREAD

**Issue by jblestang** [freqtrade/freqtrade#3544]
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.6.9
  * CCXT version: 1.30.48
  * Freqtrade Version: develop
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*I'm trying to use "plot-dataframe" to visualize the result of my strategy which is using data from several time frame (4H, 1D, 1W) using the data provider. Unfortunately when trying to plot the following error occurs : *

### Steps to reproduce:

`freqtrade plot-dataframe -p LINK/BTC -s EMAHL`
  
### Observed Results:

```
in populate_indicators daily = self.super_trend(self.dp.get_pair_dataframe(metadata['pair'], timeframe='1D'))`
AttributeError : 'NoneType' object has no attribute 'get_pair_dataframe'`
```

### Relevant code exceptions or logs

  ```
in populate_indicators daily = self.super_trend(self.dp.get_pair_dataframe(metadata['pair'], timeframe='1D'))`
AttributeError : 'NoneType' object has no attribute 'get_pair_dataframe'`
  ```

**Comment by xmatthias** [comment]
All examples we have in the [documentation](https://www.freqtrade.io/en/latest/strategy-customization/#get_pair_dataframepair-timeframe) show that before using DP, you should check it exists (via `if self.dp:` ). 
That will avoid this error.

Now for the problem itself - yes, dataprovider is not supported in plotting mode, we should add this to the documentation as well.
