### ISSUE TITLE
Could not create virtual environment. Leaving now

### ISSUE THREAD

**Issue by Vildnex** [freqtrade/freqtrade#3548]
## Describe your environment

  * Operating system: Manjaro 20.0.3
  * Python Version: 3.8.3 (`python -V`)
  * CCXT version: 1.30.48 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.6 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
 

I'm getting the fallowing error message:
```
Error: [Errno 38] Function not implemented: 'lib' -> '/run/media/vlad/Common/Linux/freqtrade/.env/lib64'
Could not create virtual environment. Leaving now
```

When I'm trying to run `./setup.sh --install`. I've also tried older versions and I'm getting the same error.

**Comment by hroff-1902** [comment]
found these two posts regarding python problems on that Manjaro (whatever it is, never seen it):
https://forum.manjaro.org/t/python-virtualenv-error-when-try-to-create-a-new-one/19390/3
https://forum.manjaro.org/t/trying-to-install-virtualenv-package-using-pip/75362/7

**Comment by xmatthias** [comment]
I think the best link is https://stackoverflow.com/questions/56412842/virtualenv-myenv-doesnt-create-virtual-environment-on-exfat-hard-drive-on-ubunt ...

`/run/media/vlad/...` ... sounds like a portable (removable) device (without ever having used MacOS).

i suspect python is detecting that and preventing creation. 
Best use a "non-removable" location to try the installation.

**Comment by xmatthias** [comment]
I'm assuming this as solved now.

Feel free to comment below if you're still having problems installing so we can reopen and help you get running.

**Comment by Fusseldieb** [comment]
I could actually fix the issue mentioned in the title with this answer:
https://stackoverflow.com/a/65936772/3525780


> Try installing python3-distutils as well.
> Altogether, for python 3.8, the following worked for me.
> 
> $ apt-get install python3.8 python3.8-venv python3.8-distutils python3.8-dev

Assuming you're using Python 3.8
