### ISSUE TITLE
realtime strategy testing

### ISSUE THREAD

**Issue by jbmustaq** [freqtrade/freqtrade#3550]
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.6.9
  * CCXT version: 1.30.48
  * Freqtrade Version: develop-cf1bbb1a
  
## Your question

I am new to freqtrade and wanted to ask if we can do the strategy testing on realtime. I am not able to find answer in the doc.

**Comment by xmatthias** [comment]
it's called [dry-run](https://www.freqtrade.io/en/latest/configuration/#switch-to-dry-run-mode).

**Comment by jbmustaq** [comment]
Thanks alot
