### ISSUE TITLE
Timestamp for this request was 1000ms ahead of the server's time

### ISSUE THREAD

**Issue by gathad** [freqtrade/freqtrade#3555]
## Describe your environment

  * Operating system: WSL Ubuntu 20.04 LTS
  * Python Version: 3.8.2
  * CCXT version: 1.28.49
  * Freqtrade Version: 2020.5
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

I was able to make Dryrun but when I tried to start live run, I'm not able to start it because of the following error.

I didn't take the error messages earlier parts because it contains my api keys.

`
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gatha/freqtrade/freqtrade/exchange/exchange.py", line 597, in get_balances
    balances = self._api.fetch_balance()
  File "/home/gatha/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 581, in fetch_balance
    response = getattr(self, method)(query)
  File "/home/gatha/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 449, in inner
    return entry(_self, **inner_kwargs)
  File "/home/gatha/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 1925, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/gatha/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 468, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/gatha/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 577, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/gatha/freqtrade/.env/lib/python3.8/site-packages/ccxt/binance.py", line 1919, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/home/gatha/freqtrade/.env/lib/python3.8/site-packages/ccxt/base/exchange.py", line 486, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gatha/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker = Worker(args)
  File "/home/gatha/freqtrade/freqtrade/worker.py", line 34, in __init__
    self._init(False)
  File "/home/gatha/freqtrade/freqtrade/worker.py", line 51, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/gatha/freqtrade/freqtrade/freqtradebot.py", line 72, in __init__
    self.wallets = Wallets(self.config, self.exchange)
  File "/home/gatha/freqtrade/freqtrade/wallets.py", line 31, in __init__
    self.update()
  File "/home/gatha/freqtrade/freqtrade/wallets.py", line 109, in update
    self._update_live()
  File "/home/gatha/freqtrade/freqtrade/wallets.py", line 87, in _update_live
    balances = self._exchange.get_balances()
  File "/home/gatha/freqtrade/freqtrade/exchange/common.py", line 120, in wrapper
    return wrapper(*args, **kwargs)
  File "/home/gatha/freqtrade/freqtrade/exchange/common.py", line 120, in wrapper
    return wrapper(*args, **kwargs)
  File "/home/gatha/freqtrade/freqtrade/exchange/common.py", line 120, in wrapper
    return wrapper(*args, **kwargs)
  [Previous line repeated 1 more time]
  File "/home/gatha/freqtrade/freqtrade/exchange/common.py", line 123, in wrapper
    raise ex
  File "/home/gatha/freqtrade/freqtrade/exchange/common.py", line 113, in wrapper
    return f(*args, **kwargs)
  File "/home/gatha/freqtrade/freqtrade/exchange/exchange.py", line 606, in get_balances
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not get balance due to InvalidNonce. Message: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}`

I'm using binance exchange. How can I fix this?

I have already re-syncronized my clock but didn't work.

**Comment by hroff-1902** [comment]
try to recreate keys

**Comment by gathad** [comment]
Hello,

I have try that twice already. Nothing has changed.

**Comment by xmatthias** [comment]
well the time syncronization should run regularily (ccxt recommends every 10 minutes) - and to make sure the timezone is not DST (for whatever reason).

There seems to be a different workaround in ccxt - but be sure to read and understand the [security implications explained in this ccxt post](https://github.com/ccxt/ccxt/issues/850#issuecomment-382787816).

You should be able to utilize the method mentioned in that issue to get around this via the below configuration section, but i'd really recommend to setup proper time syncronization instead (eventually change the time server - if you're having continued problems with this).

```jsonc
// ...
"ccxt_config": {
          "enableRateLimit": true,
          "options": {"options": { "adjustForTimeDifference": true }
        },
// ...
```

**Comment by gathad** [comment]
Hello,

I did syncronized time manually (clicked on synronyze button on Windows, changed server and tried again too) but it didnt help. I just tried it again in 1 minute after syncronization. So I think the problem is not related with syncronizing regularly. 

I will read the file you have send and try to find the error. I will inform you about latest situation when I try.

**Comment by hroff-1902** [comment]
> Hello,
> 
> I have try that twice already. Nothing has changed.

have you recreated the key **after** you syncronized the time?

**Comment by gathad** [comment]
Yes, I have recreated the key 5 times. 

1. I have read something says "recreate the key" on github, I recreated and tried again. --Failed
2. I have syncronized the clock, tried again, failed, recreated the key failed again but the time between syncronization and trial was about 30 minutes. --Failed
3. I have syncronized the clock with another server, recreated the key, tried (too much waiting time again) --Failed
4. syncronized (second server) + recreated the key in 3 and half minute --Failed
5. syncronized (first server which is windows own server) + recreated the key in a minute (getting faster on every trial :) ) --Failed

So, I don't think that this issue is about sync or re creating the key again. I know they can effect the result but still problem is not about that.

I'm thinking that maybe it's about wsl. In the and, there is a second kernel working on windows. Maybe, using clock information has it's own delay. But I'm not sure about that. 

I will change the ccxt configuration like xmatthias mentioned, if it fails again, I will make again the sync and recreating operation from begining.

**Comment by xmatthias** [comment]
maybe you should try on a different pc / server (obviously with a new set of keys).

It's working fine for multiple pc/servers of mine, and also other users have no such issues - which suggests that it's related to your setup (most likely to something in your pc).

**Comment by hroff-1902** [comment]
check that time in WSL is also syncronized and aligns Windows time

**Comment by gathad** [comment]
I have found the problem. WSL is using a different clock than windows. I know it looks stupid but it is. 

Today, I have changed the configuration file like xmathias said, than tried it out. --Failed
Than I recreate the keys. --Failed

Than I tried to check the wsl clock. It was looking like the same. Since I can't write a code to know both systems clock from a single systems therminal and calculate automatically, I was trying to check it by my eyes. I have failed to determine the problem on first trials. But linux is suplying seconds information too. So, I have send the "date" command again and again until the minute information of the windows changes. Than I found 17 seconds shift. When I fix that, bot started normally.

Thank you for helping me!

So, it doesn't matter if the windows clock is syncronized or not, we need to syncronize the wsl seperately.

For the people who are living the same problem with me, following code syncs the clock. 

> sudo ntpdate pool.ntp.org

Only problem left over is, clock is still shifting. I need to run this command as service on wsl or I need to implement this inside of my freqtrade installation. Do you know a way to do that?

Maybe implementing the clock syncronization directly to the freqtrade could be reasonable since ccxt needs it.

**Comment by hroff-1902** [comment]
I suspected this (see my previous comment)

**Comment by hroff-1902** [comment]
some recipes: https://github.com/microsoft/WSL/issues/4245

**Comment by xmatthias** [comment]
Are yiubusing wsl2?

I never noticed this on the old wsl ... But didnt try the new one yet, whixh works a lot different now ...

**Comment by xmatthias** [comment]
> Maybe implementing the clock syncronization directly to the freqtrade could be reasonable since ccxt needs it.

No. 
python uses the system clock, as most other programming languages as well.
A normal, userlevel process (like freqtrade) should never have access to change the clock of the system. You had to use sudo to do it - so run as root - but freqtrade should not be running as root.

Clock syncronization is usually done by a program like ntpd or chronyd (both of which should in theory also work on WSL).

Since you're having this issue, i'm assuming you're on WSL2 (which is technically a full virtual machine).
You should be able to enable time syncronization by running `sudo systemctl enable ntpd` and `sudo systemctl start ntpd`.
