### ISSUE TITLE
Every time I run hyperopt the bot runs the same file no matter what.

### ISSUE THREAD

**Issue by gabriel34** [freqtrade/freqtrade#3565]
The bot is runs the same file no matter what even if I change it. I think it has something to do with the hyperopt.lock

**Comment by hroff-1902** [comment]
what do you mean by "runs same file"?

check for duplicating hyperopt classes by `freqtrade list-hyperopts`

**Comment by gabriel34** [comment]
OS: Ubuntu 20.04 LTS
Python Version: 3.8.2
CCXT version:  1.30.71
Freqtrade Version: 2020.6
Every time I run hyperopt it always runs thinking that I want an roi table even though it is not were in my code.
![Screenshot from 2020-07-07 11-34-47](https://user-images.githubusercontent.com/36419935/86833582-2fc67380-c046-11ea-9394-3e07d94dc4d4.png)
![Screenshot from 2020-07-07 11-35-20](https://user-images.githubusercontent.com/36419935/86833604-36ed8180-c046-11ea-9f90-021176d9909d.png)

**Comment by gabriel34** [comment]
I have tried everything I know how any advice with help and thank you for you time.

**Comment by xmatthias** [comment]
The file may not be thenproblem, but the command youre using.
Make sure to use `--spaces` as described in the hyperopt documentation ...

**Comment by gabriel34** [comment]
You are a life saver I have been trying to figure this out for so long thanks for the help and I hope you have a great year.

**Comment by hroff-1902** [comment]
yet another tip: if you run hyperopt with the `roi` space excluded -- make sure the strategy has minimal_roi set to the value you actually wish the strategy to run with.

can this be closed?

**Comment by gabriel34** [comment]
Yes thanks for you help
