### ISSUE TITLE
When doing hyper opt getting the same buy and sell trigger.

### ISSUE THREAD

**Issue by gabriel34** [freqtrade/freqtrade#3567]
## Describe your environment

  * Operating system: Ubuntu 20.04 LTS
  * Python Version: Python 3.8.2 (`python -V`)
  * CCXT version: 1.30.71 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.6
 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
When I am doing hyperopt I am getting the same buy and sell trigger the lower Bollinger Bands.
*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
When I am doing hyperopt I am getting the same buy and sell trigger the lower Bollinger Bands.
  * What did you expect to happen?
Them to be different indicators.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```
![Screenshot from 2020-07-07 17-25-39](https://user-images.githubusercontent.com/36419935/86863201-36211380-c077-11ea-83eb-b2db42933de2.png)

**Comment by hroff-1902** [comment]
look at the values for other epochs with the `hyperopt-show` subcommand -- there should be epochs with other values of the trigger.

if optimization path ends with the triggers set to those values -- that means those triggers give better results than others.

**Comment by xmatthias** [comment]
Also, its just the name thats similar, its impossible to know with the info above if sell-bb_lower1 really does the same than bb_lower1.

The name seems the same, but implementation can compare it to upper bands for all we know ... The name is patient, and wont care how its implemented.

**Comment by gabriel34** [comment]
Thank you the first thing you told me helped. Thanks for helping me even though you had very little info. I really appreciate you help and I was able to fix the problem
