### ISSUE TITLE
 No module named 'sklearn.linear_model._logistic'

### ISSUE THREAD

**Issue by AmirHoseinSafari** [freqtrade/freqtrade#3571]
## Describe your environment

  * Operating system: MacOs
  * Python Version: 3.8
  * CCXT version: 1.30.71
  * Freqtrade Version: freqtrade develop-d9d999ea
  
## My question

Hi,
I am trying to load my model in my strategy, but I got an error.
Here is my code:

```
from sklearn.linear_model import LogisticRegression
import pickle
model = pickle.load(open("model.sav", 'rb'))
```

But I got this error:

```
Traceback (most recent call last):
  File "/Users/amir/PycharmProjects/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 16, in wrapper
    return f(*args, **kwargs)
  File "/Users/amir/PycharmProjects/freqtrade/freqtrade/strategy/interface.py", line 274, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/Users/amir/PycharmProjects/freqtrade/freqtrade/strategy/interface.py", line 254, in analyze_ticker
    dataframe = self.advise_buy(dataframe, metadata)
  File "/Users/amir/PycharmProjects/freqtrade/freqtrade/strategy/interface.py", line 542, in advise_buy
    return self.populate_buy_trend(dataframe, metadata)
  File "/Users/amir/PycharmProjects/freqtrade/user_data/strategies/ml_strategy.py", line 342, in populate_buy_trend
    model = pickle.load(file)
ModuleNotFoundError: No module named 'sklearn.linear_model._logistic'
2020-07-08 17:42:49,666 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BTC/USDT: No module named 'sklearn.linear_model._logistic'

```

I use this command to run my strategy:

`freqtrade trade --strategy ml_strategy
`

I am sure that sklearn is installed on my env, so I think maybe the env that strategy is using is different from other parts of the code?

Thanks in advance.

**Comment by xmatthias** [comment]
The environment is definitely the same, running part of a program in a different environment is not possible with python at the moment.

However, when using pickle to load models, the sklearn version (and all other versions) must match 100%, otherwise loading fails.
Best create and save the model from the freqtrade virtual environment to avoid version problems. Note that updates(to sklearn or dependencies  of that) can break the model again.

**Comment by xmatthias** [comment]
I've also found https://github.com/Azure/MachineLearningNotebooks/issues/656 - which agrees with my previous comment that you're using 2 different versions of scikit-learn (one to write the file, a different one to read the file).

**Comment by xmatthias** [comment]
Going to close this as as it's not an issue with freqtrade itself, but with a mismanagement of environments (newer version of sklearn was used to create the model, and an older version was used to read the model).

Feel free to comment below if this does not answer your question.

**Comment by ayhamsh** [comment]
if u are working on pythonanywhere server Kill the process between runs.  before running it a second time, exit the console at the bottom of the screen using control-D or the exit() command. Then the next run will start a fresh console, and it will work again.

**Comment by akramayman** [comment]
> The environment is definitely the same, running part of a program in a different environment is not possible with python at the moment.
> 
> However, when using pickle to load models, the sklearn version (and all other versions) must match 100%, otherwise loading fails. Best create and save the model from the freqtrade virtual environment to avoid version problems. Note that updates(to sklearn or dependencies of that) can break the model again.



Hi, I have the same problem but I would ask how can know the versions of packaging in the pickle file.?
