### ISSUE TITLE
Freqtrade's profit calculation could not be reproduced

### ISSUE THREAD

**Issue by pnmartinez** [freqtrade/freqtrade#3575]
Hi everyone. I've been tinkering a while with the bot (~ 2-3 months), and I must say it's an wonderful project you've got here.

## Describe your environment

  * Operating system: Raspbian Jesie
  * Python Version: 3.7.0
  * CCXT version: 1.27.56
  * Freqtrade Version: develop-dfc44e5b
  
## Freqtrade's profit calculation cannot be reproduced

So I am analyzing my `tradesv3.sqlite`, and **not being able to reproduce `close_profit` and `close_profit_abs` columns**, using the relevant variables for it. **My profit values calculated this way differ greatly from the ones FREQTRADE adds to the table history** (see figure).

![freqtrade_vs_me](https://i.imgur.com/57pbs3q.png)

To calculate `close_profit_abs` by hand, I am using the next variables from the SQL: `amount`, `stake_amount`, `close_rate_requested` and `fee_close`, as indicated below (based on `persistence.py`)
```
# Following FREQTRADE's calculation on persistence.py, lines 440-480 aprox

close_trade_before_fees = amount * close_rate_requested            # amount in BTC before fees
fee = fee_close * close_trade_before_fees                        # fee amount in BTC
close_trade_after_fees = close_trade_before_fees - fee               # resulting BTC after fees
close_profit_abs_by_hand = close_trade_after_fees - stake_amount    # absolute difference between BTC spent and recovered
```

## Question

The question would be **where this disagreement comes from (what I am calculating wrong)**, or in case everything seems fine, how's that Freqtrade is consistently accounting for a profit that turns out to be much lower calculated by hand (and the worrying implication: is it loosing over time and missinforming us?).

**Comment by xmatthias** [comment]
I think you're simplifying the calculation here too much.

The fee calculation is not that simple, as exchanges have different methods to apply fees:

* always on the target currency (so you get a lower amount)
* always on the stake (quote) currency (so you get the requested amount - but pay "fee" more)
* In a 3rd currency (like BNB) - in which case you pay a (reduced) % of the value - but in a currency that's neither quote, nor base currency.
* a combination of the above (entry fees in BNB, exit fees in target currency)


For a start,  you're using "close_rate_requested" - which freqtrade does not use for the calculation at all, and depending on the order type, that's not what you'll get on the exchange (called slippage). This column is just there for analysis of slippage - but it's not used in freqtrade for anything "operational".

In addition to that, your calculation above does ignore the `open_fee` part completely (so you assume trade entries are free). For that, your calculation method is wrong.

Fix that and i'll have a look why you think they deviate - but for now, it's clear that they MUST be different - as you do ignore certain parts of the calculation completely.

**Comment by pnmartinez** [comment]
> I think you're simplifying the calculation here too much.
> 
> The fee calculation is not that simple, as exchanges have different methods to apply fees:
> 
>     * always on the target currency (so you get a lower amount)
> 
>     * always on the stake (quote) currency (so you get the requested amount - but pay "fee" more)
> 
>     * In a 3rd currency (like BNB) - in which case you pay a (reduced) % of the value - but in a currency that's neither quote, nor base currency.
> 
>     * a combination of the above (entry fees in BNB, exit fees in target currency)
> 
> 
> For a start, you're using "close_rate_requested" - which freqtrade does not use for the calculation at all, and depending on the order type, that's not what you'll get on the exchange (called slippage). This column is just there for analysis of slippage - but it's not used in freqtrade for anything "operational".
> 
> In addition to that, your calculation above does ignore the `open_fee` part completely (so you assume trade entries are free). because of that, your calculation method is wrong as you're using `stake_amount` instead of the real entry value.
> 
> Fix that and i'll have a look why you think they deviate - but for now, it's clear that they MUST be different - as you do ignore certain parts of the calculation completely.

Thanks for the insights! Gonna update my analysis according to your input and get back with updated results.

Of course, if in the end of this thread I build a reasonable clear cheatsheet of how are the DB figures built, feel free to include in the docs! It surely will be helpful to help others double checking results.

Cheers.

**Comment by pnmartinez** [comment]
@xmatthias ok, so I recalculated with the proper figures and it's a perfect match!

## Profit calculation from database variables

- `close_rate` instead of `close_rate_requested` (which was not affecting me, slippage is 0 for 97% of the trades).
- `open_trade_price` instead of `stake_amount`, which was what produced the mistake. So **the right profit calculation from DB's values** is:

```
# Summing up persistence.py, lines ~ 440-480
close_trade_before_fees = amount * close_rate   # instead of "close_rate_requested"
fee = fee_close * close_trade_before_fees   
close_trade_after_fees = close_trade_before_fees - fee          
close_profit_abs_by_hand = close_trade_after_fees - open_trade_price  # instead of "stake_amount"
```

![match](https://i.imgur.com/RYcSOxi.png)
## Full disclosure: open fees role

 **Open_fees** were already taken into account in the original calculation. `amount` is the amount of quote currency in the balance **after the trade has been successfully opened and fees taken into account**.

Look at the next trade: `amount` is the quantity on balance and hence sold, which equals to the amount bought minus the fee (0'1 %, ~ 0.17 IOTA).

![open](https://i.imgur.com/JkCqaGv.png)

## Conclusion

I think we can close this issue, and I hope summing up the profit calculations in the snippet above will be useful for others who'll analyze the same as me. Feel free to add it to the SQL cheatsheet.

**Comment by xmatthias** [comment]
so you've hit the case without BNB (you don't own BNB / have BNB disabled in your account).

I think it should be noted that freqtrade internally always uses relative profit - not absolute profit values.
Absolute values are only used for RPC methods / analysis.

This is an important distinction as freqtrade MAY report absolute values slightly off, depending on the case (but we try to be off on the "better" end):

On kraken, i'm currently paying fees in KFEE (everyone got KFEE a few months ago).
The way kraken implemented this is that i pay fee in EUR first (this is what the bot sees) - and kraken then "converts" this in a 3rd trade to KFEE (at 0 cost). 
That's a very "odd" way of doing it - and it's not properly covered in freqtrade (we can't, as nothing in the order response suggests fees were paid in KFEE).
So Kraken currently underrepresents my absolute profits by "fee" (it assumes fees are in EUR - which technically, they are at first).

For my bot, this means it may report 1% gain for a day - but in reality i made 1.2% (depending on the amount of trades - amount of stoplosses etc.).

In theory, paying in BNB is similar and can have a similar effect. 
However, Binance implemented this "properly" - which means that fees are repored as being paid in BNB - so we can calculate this. 
The way this is done is that BNB fees will still lower your overall profit - as BNB is not free - so they should not be treated as free trades, so if you made 2% of profits from open to close - you really only made 1.95% profit - and paid 0.05% fees (in BNB).

If we were not doing that, then your overall account balance (combination of BTC and BNB) could become lower over time, while the bot reports slight profits, as it's ignoring the BNB balance, which is getting lower with every trade.

**Comment by pnmartinez** [comment]
Really good, thorough explanation on using exchange coins for fees, and what parts of that are currently being handled right. 

Thanks @xmatthias !
