### ISSUE TITLE
Minor: Notify user when a force sell fails

### ISSUE THREAD

**Issue by Theagainmen** [freqtrade/freqtrade#3576]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.7.5 
  * CCXT version: 1.30.48
  * Freqtrade Version: 2020.6 

## Describe the enhancement

Notify the user in the Telegram channel when a force sell fails. For example because you are below the minimum order amount or whatever reason. It happened to me, and I only figured out after a day. This way the user can manually take control over this trade and prevent it from big losses.

```
freqtrade.freqtradebot - WARNING - Selling the trade forcefully
freqtrade.wallets - INFO - Wallets synced.
freqtrade.freqtradebot - WARNING - Unable to sell trade: Could not create market sell order on market DOGE/USDT.Tried to sell amount 1254.0 at rate 0.0.Message: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
```

In addition to this: this usually requires the user to manually trade on the exchange, which causes the bot 'stuck' with this trade, because it will never be able to sell it. Maybe a discussion point, but should there be some kind of command to force close a trade in your database file (and maybe calculate the profits at the current price you run this command, to somewhat keep the stats realistic?), so you don't have to manually do this whenever you're stuck with a trade? Because if you don't do this, you will have -1 trade from your max_open_trades.

I already looked at the code where it's executed, but I'm not sure how to code it so that it won't spam your telegram chat (this is in the `freqtradebot.py` file).
![image](https://user-images.githubusercontent.com/24569139/87188923-fca70d00-c2ef-11ea-8b0a-79a4cf5ce3b3.png)

**Comment by xmatthias** [comment]
I'm not sure about this - as technically, you got the message about ""Remaining buy order for XXX cancelled due to timeout" already.

That'll already tell me that something might be up and i need to check that trade.
now running `/status` once - i can (usually) see if it's below the limits right away (unless it's VERY close to the limit) - as these limits are usually quite regular (like <10 USDT on binance).

Now most of the time, that knowledge is enough to know it can't sell it anymore ...

**Comment by Theagainmen** [comment]
You're right.. I just searched the chat and found the message. I've never seen it before, I really didn't notice it (I even found 3 more in the days before this). The bot makes quite some trades a day and the message is just 1 line in between those 5 line buy/sell messages. Just have a look at this image, you barely notice it.
![bericht](https://user-images.githubusercontent.com/24569139/87205127-fa9c7880-c306-11ea-899e-328f2f185049.png)


I think the message should at least be changed to a warning message with the emoji in front of it, that way you will see it way faster.

One thing I also don't understand, the remaining **buy order** got cancelled. So it bought < 15 USDT (my stake amount) and > 10 USDT (minimum binance order amount). So it should have been able to sell this (because >10 USDT, otherwise it could have never been bought). But it wasn't able to sell it because there was only ~5 USDT left (which was below the minimum order amount of 10 USDT on Binance). So that means that it was partially sold somewhere right? Shouldn't there be a message or something (I searched for 'partial' in the chat and found nothing)?

**Comment by xmatthias** [comment]
> So it bought < 15 USDT (my stake amount) and > 10 USDT (minimum binance order amount). 

no, there's different limits in place on the exchange.
>10USDT is the minimum order size, which means you can't place an order for 9 USDT.

However - the lot size (minimum step size) may be 1 USDT - or 0.1 USDT, or even lower (depends on the pair, usually) - so you can order 10 USDT, or 10.1 USDT.

Now what happens is you place the order of 15 USDT. Someone else comes in with an order of 200 USDT. It's filled by the 199 USDT in the orderbook in front of you, and 1 USDT from you - so now you own 1 USDT of DODGE.

If the order ain't cancelled, it got a chance to be filled "later" (but maybe not if price never reaches here again). If it's cancelled, you're "stuck" with the 1 USDT of DODGE you're unable to sell unless you buy more DODGE to be above the 10 USDT limit again.

**Comment by Theagainmen** [comment]
Ahh I didn't know, I thought that even then it should be filled by a minimum of 10 USDT.. should it maybe sent another buy message that it's partially filled with X DOGE/USDT? 

(I think I can change the Status message to a warning message myself, I can create a PR if you agree with that change?)

**Comment by xmatthias** [comment]
well in theory, the 2 messages might better be combined into one. 
I wasn't aware that it's sending 2 messages - that doesn't really make sense.

**Comment by xmatthias** [comment]
As said above - the message exists already, but it used to be 2 seperate messages.

However, i guess we can close this - as #3724 does address the double notification by combining the 2 messages into one.
