### ISSUE TITLE
[Feature request] Adding trade id to webhooks.

### ISSUE THREAD

**Issue by sanket-k** [freqtrade/freqtrade#3578]
## Describe the enhancement
A request to add **trade id** as a parameter in webhooks while data is sent.

*Explain the enhancement you would like*

Currently matching trades send via webhooks is quite difficult as there is no constant identifier, I would like to suggest sending the **trade id**, the return field, this would help matching trades much easier imhp.

**Comment by hroff-1902** [comment]
merged into develop, 
@sanket-k pls verify

**Comment by sanket-k** [comment]
hi @hroff-1902 and @xmatthias, it works, thanks :)

**Comment by xmatthias** [comment]
Great, thanks for reporting back! :+1:
