### ISSUE TITLE
Possible workaround for market orders not working for exchanges like Upbit?

### ISSUE THREAD

**Issue by viti0sus1** [freqtrade/freqtrade#3579]
* Operating system:  Linux
  * Python Version:  3.8.2
  * CCXT version: 1.30.48
  * Freqtrade Version: 2020.6

After setting orders to market orders in the config file, I was getting the fatal exception posted at the bottom of this issue.  Using the fetch_order function from ccxt it was deteremined the "**amount**" shouldn't be "**None**".

After filing an issue with ccxt, a response was posted from Kroitor:

[https://github.com/ccxt/ccxt/issues/7235]

To summarize, Upbit just doesn't output the information needed to allow market orders to work, as is with many other exchanges that use market orders.  It was also suggested that:

> If you can paste a link to your freqtrade issue we could try to address it in collaboration with the authors of freqtrade. In this particular case, I would suggest freqtrade to add the code for the following:
> 
> check if it's a market order
> check if the amount is not defined
> then use the filled value instead

  
### The Verbose fetch_order output:

> Request: GET https://api.upbit.com/v1/order?uuid=618ff809-f942-417f-8fa4-c4ea41410597 {'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3Nfa2V5IjoiTVJmMjVSSVFTc1N0ZmtZeFg1eFp6VWdtdGRPZzhiTTgybnRscUY3YiIsIm5vbmNlIjoxNTk0MTM3NzMwOTQ2LCJxdWVyeV9oYXNoIjoiNjJhZTkwNmI3MjIxOTM1ZmM3ZDk3Y2ViODE3OTY4NThjMDNjZGFmMGQ5ZjYyZTAwMTM0ZGYzMmMzM2ViNjRhZWQ0ZjQ4OGJhYWE5NjNiODkzYjk4NTUwMDA2NjFlNmJjMDNmYWExYWVhNTNlNTNlNDgzMTNiMWU3NTNkNWFiMDgiLCJxdWVyeV9oYXNoX2FsZyI6IlNIQTUxMiJ9.2IQLsSjoJhGZXHoXnFI-4G1IdcKYs-2zC2d1IdXtgeA', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} None
> 
> Response: GET https://api.upbit.com/v1/order?uuid=618ff809-f942-417f-8fa4-c4ea41410597 200 {'Date': 'Tue, 07 Jul 2020 16:02:10 GMT', 'Content-Type': 'application/json', 'Content-Length': '559', 'Connection': 'keep-alive', 'Remaining-Req': 'group=default; min=899; sec=29', 'Access-Control-Allow-Origin': '*', 'ETag': 'W/"df1af7e8c5932df7c2942b890bff9963"', 'Cache-Control': 'max-age=0, private, must-revalidate', 'X-Request-Id': '3e684802-7649-46a1-b809-44bc37a94799', 'X-Runtime': '0.026137', 'Vary': 'Origin', 'X-Kong-Upstream-Latency': '28', 'X-Kong-Proxy-Latency': '1', 'Via': 'kong/1.4.3'} {"uuid":"618ff809-f942-417f-8fa4-c4ea41410597","side":"bid","ord_type":"price","price":"1999.99","state":"cancel","market":"KRW-ETH","created_at":"2020-07-03T03:25:53+09:00","volume":null,"remaining_volume":null,"reserved_fee":"0.999995","remaining_fee":"0.000000671","paid_fee":"0.999994329","locked":"0.001342671","executed_volume":"0.00735831","trades_count":1,"trades":[{"market":"KRW-ETH","uuid":"e95ad0f2-2b03-4972-8e23-6610f04b397b","price":"271800.0","volume":"0.00735831","funds":"1999.988658","created_at":"2020-07-03T03:25:53+09:00","side":"bid"}]}
> {'info': {'uuid': '618ff809-f942-417f-8fa4-c4ea41410597', 'side': 'bid', 'ord_type': 'price', 'price': '1999.99', 'state': 'cancel', 'market': 'KRW-ETH', 'created_at': '2020-07-03T03:25:53+09:00', 'volume': None, 'remaining_volume': None, 'reserved_fee': '0.999995', 'remaining_fee': '0.000000671', 'paid_fee': '0.999994329', 'locked': '0.001342671', 'executed_volume': '0.00735831', 'trades_count': 1, 'trades': [{'market': 'KRW-ETH', 'uuid': 'e95ad0f2-2b03-4972-8e23-6610f04b397b', 'price': '271800.0', 'volume': '0.00735831', 'funds': '1999.988658', 'created_at': '2020-07-03T03:25:53+09:00', 'side': 'bid'}]}, 'id': '618ff809-f942-417f-8fa4-c4ea41410597', 'clientOrderId': None, 'timestamp': 1593714353000, 'datetime': '2020-07-02T18:25:53.000Z', 'lastTradeTimestamp': 1593714353000, 'symbol': 'ETH/KRW', 'type': 'market', 'side': 'buy', 'price': None, 'cost': 1999.988658, 'average': 271800.0, 'amount': None, 'filled': 0.00735831, 'remaining': None, 'status': 'canceled', 'fee': {'currency': 'KRW', 'cost': 0.999994329}, 'trades': [{'id': 'e95ad0f2-2b03-4972-8e23-6610f04b397b', 'info': {'market': 'KRW-ETH', 'uuid': 'e95ad0f2-2b03-4972-8e23-6610f04b397b', 'price': '271800.0', 'volume': '0.00735831', 'funds': '1999.988658', 'created_at': '2020-07-03T03:25:53+09:00', 'side': 'bid'}, 'order': '618ff809-f942-417f-8fa4-c4ea41410597', 'timestamp': 1593714353000, 'datetime': '2020-07-02T18:25:53.000Z', 'symbol': 'ETH/KRW', 'type': 'limit', 'side': 'buy', 'takerOrMaker': None, 'price': 271800.0, 'amount': 0.00735831, 'cost': 1999.988658, 'fee': None}]}
> 

### The Fatal Exception:

> 2020-07-08 00:34:50,997 - freqtrade.resolvers.exchange_resolver - INFO - No Upbit specific subclass found. Using the generic class instead.
> 2020-07-08 00:34:50,997 - freqtrade.exchange.exchange - INFO - Using CCXT 1.30.48
> 2020-07-08 00:34:50,997 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
> 2020-07-08 00:34:50,999 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 1000}
> 2020-07-08 00:34:51,001 - freqtrade.exchange.exchange - INFO - Using Exchange "Upbit"
> 2020-07-08 00:34:52,125 - freqtrade.wallets - INFO - Wallets synced.
> 2020-07-08 00:34:52,129 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/home/itiviti/freqtrade/freqtrade/pairlist/VolumePairList.py'...
> 2020-07-08 00:34:53,068 - VolumePairList - INFO - Searching 3 pairs: ['BSV/KRW', 'QKC/KRW', 'BTC/KRW']
> 2020-07-08 00:34:53,068 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
> 2020-07-08 00:34:54,522 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['forcebuy'], ['performance'], ['daily'], ['count'], ['reload_config', 'reload_conf'], ['show_config', 'show_conf'], ['stopbuy'], ['whitelist'], ['blacklist'], ['edge'], ['help'], ['version']]
> 2020-07-08 00:34:54,587 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
> 2020-07-08 00:34:55,609 - freqtrade.worker - INFO - Changing state to: RUNNING
> 2020-07-08 00:34:55,609 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': custom, 'status': "Exchange: upbit\nStake per trade: 2000 KRW\nMinimum ROI: {'0': 0.12, '30': 0.1, '60': 0.05, '120': 0.025, '240': 0.0125, '480': 0.005, '960': 0.0025}\nStoploss: -0.25\nTimeframe: 15m\nStrategy: BR2"}
> 2020-07-08 00:34:56,077 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': "Searching for KRW pairs to buy and sell based on [{'VolumePairList': 'VolumePairList - top 3 volume pairs.'}]"}
> 2020-07-08 00:34:56,596 - freqtrade.persistence - INFO - Found open trade: Trade(id=1, pair=ETH/KRW, amount=0.00735835, open_rate=271800.00000000, open_since=2020-07-02 18:25:53)
> 2020-07-08 00:34:58,679 - freqtrade.data.converter - INFO - Missing data fillup for QKC/KRW: before: 199 - after: 213
> 2020-07-08 00:34:58,696 - freqtrade.data.converter - INFO - Missing data fillup for BSV/KRW: before: 199 - after: 200
> 2020-07-08 00:34:58,751 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1, pair=ETH/KRW, amount=0.00735835, open_rate=271800.00000000, open_since=2020-07-02 18:25:53)
> 2020-07-08 00:34:58,751 - freqtrade.commands.trade_commands - ERROR - must be real number, not NoneType
> 2020-07-08 00:34:58,751 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
> Traceback (most recent call last):
> File "/home/itiviti/freqtrade/freqtrade/commands/trade_commands.py", line 20, in start_trading
> worker.run()
> File "/home/itiviti/freqtrade/freqtrade/worker.py", line 73, in run
> state = self._worker(old_state=state)
> File "/home/itiviti/freqtrade/freqtrade/worker.py", line 107, in _worker
> self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
> File "/home/itiviti/freqtrade/freqtrade/worker.py", line 128, in _throttle
> result = func(*args, **kwargs)
> File "/home/itiviti/freqtrade/freqtrade/worker.py", line 141, in _process_running
> self.freqtrade.process()
> File "/home/itiviti/freqtrade/freqtrade/freqtradebot.py", line 156, in process
> self.check_handle_timedout()
> File "/home/itiviti/freqtrade/freqtrade/freqtradebot.py", line 898, in check_handle_timedout
> fully_cancelled = self.update_trade_state(trade, order)
> File "/home/itiviti/freqtrade/freqtrade/freqtradebot.py", line 1212, in update_trade_state
> if not isclose(order['amount'], new_amount, abs_tol=constants.MATH_CLOSE_PREC):
> TypeError: must be real number, not NoneType
> 2020-07-08 00:34:58,754 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
> 2020-07-08 00:34:58,754 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
> 2020-07-08 00:34:59,248 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
> 2020-07-08 00:34:59,752 - freqtrade.freqtradebot - INFO - Buy order cancelled on exchange for Trade(id=1, pair=ETH/KRW, amount=0.00735835, open_rate=271800.00000000, open_since=2020-07-02 18:25:53).
> 2020-07-08 00:34:59,753 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1, pair=ETH/KRW, amount=0.00735831, open_rate=271800.00000000, open_since=2020-07-02 18:25:53)
> 2020-07-08 00:34:59,753 - freqtrade - ERROR - Fatal exception!
> Traceback (most recent call last):
> File "/home/itiviti/freqtrade/freqtrade/main.py", line 36, in main
> return_code = args'func'
> File "/home/itiviti/freqtrade/freqtrade/commands/trade_commands.py", line 29, in start_trading
> worker.exit()
> File "/home/itiviti/freqtrade/freqtrade/worker.py", line 179, in exit
> self.freqtrade.cleanup()
> File "/home/itiviti/freqtrade/freqtrade/freqtradebot.py", line 120, in cleanup
> self.cancel_all_open_orders()
> File "/home/itiviti/freqtrade/freqtrade/freqtradebot.py", line 932, in cancel_all_open_orders
> self.handle_cancel_buy(trade, order, constants.CANCEL_REASON['ALL_CANCELLED'])
> File "/home/itiviti/freqtrade/freqtrade/freqtradebot.py", line 973, in handle_cancel_buy
> self.update_trade_state(trade, corder, trade.amount)
> File "/home/itiviti/freqtrade/freqtrade/freqtradebot.py", line 1212, in update_trade_state
> if not isclose(order['amount'], new_amount, abs_tol=constants.MATH_CLOSE_PREC):
> TypeError: must be real number, not NoneType
>

**Comment by xmatthias** [comment]
Would you mind giving #3497 a try? 

it did fix this issue in my tests - but i'm not a user of upbit - so i had to fake having empty amount's returned ...

**Comment by viti0sus1** [comment]
Sure, I'll let it run with a small amount to see what it'll come up with.  I can say that it did allow me to forcebuy and forcesell without crashing the bot.  Whereas before, while "market" orders were enabled in config, the bot would crash if I tried to forcebuy any pair.

**Comment by xmatthias** [comment]
now forcebuy is not VERY conclusive - regular buys / sells would be better (although there should not be much difference), thanks for confirming

**Comment by viti0sus1** [comment]
After running it a couple days and seeing the outcome, I noticed that the trade stays open after it has bought and sold the asset.

Here's the fetch_order:

> Response: GET https://api.upbit.com/v1/order?uuid=bd900ac3-c780-4454-b28e-f1030174ddba 200 {'Date': 'Sun, 19 Jul 2020 17:46:04 GMT', 'Content-Type': 'application/json', 'Content-Length': '541', 'Connection': 'keep-alive', 'Remaining-Req': 'group=default; min=888; sec=29', 'Access-Control-Allow-Origin': '*', 'ETag': 'W/"8a414e8bcc0b757fc2c3b4858ee8f33a"', 'Cache-Control': 'max-age=0, private, must-revalidate', 'X-Request-Id': '1c617473-8d8e-46cb-9d7b-427744592428', 'X-Runtime': '0.020429', 'Vary': 'Origin', 'X-Kong-Upstream-Latency': '23', 'X-Kong-Proxy-Latency': '1', 'Via': 'kong/1.4.3'} {"uuid":"bd900ac3-c780-4454-b28e-f1030174ddba","side":"ask","ord_type":"market","price":null,"state":"done","market":"KRW-ONT","created_at":"2020-07-20T02:36:25+09:00","volume":"1.14660939","remaining_volume":"0.0","reserved_fee":"0.0","remaining_fee":"0.0","paid_fee":"0.51024117855","locked":"0.0","executed_volume":"1.14660939","trades_count":1,"trades":[{"market":"KRW-ONT","uuid":"54f83c44-d346-4d5f-9098-44e68299152c","price":"890.0","volume":"1.14660939","funds":"1020.4823571","created_at":"2020-07-20T02:36:25+09:00","side":"ask"}]}
{'info': {'uuid': 'bd900ac3-c780-4454-b28e-f1030174ddba', 'side': 'ask', 'ord_type': 'market', 'price': None, 'state': 'done', 'market': 'KRW-ONT', 'created_at': '2020-07-20T02:36:25+09:00', 'volume': '1.14660939', 'remaining_volume': '0.0', 'reserved_fee': '0.0', 'remaining_fee': '0.0', 'paid_fee': '0.51024117855', 'locked': '0.0', 'executed_volume': '1.14660939', 'trades_count': 1, 'trades': [{'market': 'KRW-ONT', 'uuid': '54f83c44-d346-4d5f-9098-44e68299152c', 'price': '890.0', 'volume': '1.14660939', 'funds': '1020.4823571', 'created_at': '2020-07-20T02:36:25+09:00', 'side': 'ask'}]}, 'id': 'bd900ac3-c780-4454-b28e-f1030174ddba', 'clientOrderId': None, 'timestamp': 1595180185000, 'datetime': '2020-07-19T17:36:25.000Z', 'lastTradeTimestamp': 1595180185000, 'symbol': 'ONT/KRW', 'type': 'market', 'side': 'sell', 'price': None, 'cost': 1020.4823571, 'average': 889.9999999999999, 'amount': 1.14660939, 'filled': 1.14660939, 'remaining': 0.0, 'status': 'closed', 'fee': {'currency': 'KRW', 'cost': 0.51024117855}, 'trades': [{'id': '54f83c44-d346-4d5f-9098-44e68299152c', 'info': {'market': 'KRW-ONT', 'uuid': '54f83c44-d346-4d5f-9098-44e68299152c', 'price': '890.0', 'volume': '1.14660939', 'funds': '1020.4823571', 'created_at': '2020-07-20T02:36:25+09:00', 'side': 'ask'}, 'order': 'bd900ac3-c780-4454-b28e-f1030174ddba', 'timestamp': 1595180185000, 'datetime': '2020-07-19T17:36:25.000Z', 'symbol': 'ONT/KRW', 'type': 'limit', 'side': 'sell', 'takerOrMaker': None, 'price': 890.0, 'amount': 1.14660939, 'cost': 1020.4823571, 'fee': None}]}

This is what came out in the terminal right after the sell:

> 2020-07-20 02:36:25,339 - freqtrade.freqtradebot - INFO - Using cached sell rate for ONT/KRW.
2020-07-20 02:36:25,339 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell, 'exchange': 'Upbit', 'pair': 'ONT/KRW', 'gain': 'profit', 'limit': 890.0, 'order_type': 'market', 'amount': 1.14660939, 'open_rate': 873.0, 'current_rate': 890.0, 'profit_amount': 18.4716226, 'profit_ratio': 0.01844395, 'sell_reason': 'sell_signal', 'open_date': datetime.datetime(2020, 7, 19, 16, 0, 47, 43661), 'close_date': datetime.datetime(2020, 7, 19, 17, 36, 25, 339792), 'stake_currency': 'KRW', 'fiat_currency': 'KRW'}
2020-07-20 02:36:26,450 - freqtrade.wallets - INFO - Wallets synced.
2020-07-20 02:36:26,463 - freqtrade.strategy.interface - WARNING - Outdated history for pair AERGO/KRW. Last tick is 36 minutes old
2020-07-20 02:36:26,496 - freqtrade.strategy.interface - WARNING - Outdated history for pair ARK/KRW. Last tick is 36 minutes old
2020-07-20 02:36:26,498 - freqtrade.strategy.interface - WARNING - Outdated history for pair QKC/KRW. Last tick is 36 minutes old
2020-07-20 02:36:26,500 - freqtrade.strategy.interface - WARNING - Outdated history for pair XEM/KRW. Last tick is 36 minutes old
2020-07-20 02:36:26,506 - freqtrade.strategy.interface - WARNING - Outdated history for pair KMD/KRW. Last tick is 66 minutes old
2020-07-20 02:36:26,517 - freqtrade.strategy.interface - WARNING - Outdated history for pair LOOM/KRW. Last tick is 51 minutes old
2020-07-20 02:36:27,198 - freqtrade.data.converter - INFO - Missing data fillup for LOOM/KRW: before: 199 - after: 216
2020-07-20 02:36:27,213 - freqtrade.data.converter - INFO - Missing data fillup for ARK/KRW: before: 199 - after: 208
2020-07-20 02:36:27,229 - freqtrade.data.converter - INFO - Missing data fillup for XEM/KRW: before: 199 - after: 215
2020-07-20 02:36:27,502 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=2, pair=ONT/KRW, amount=1.14660939, open_rate=873.00000000, open_since=2020-07-19 16:00:47)
2020-07-20 02:36:27,502 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=2, pair=ONT/KRW, amount=1.14660939, open_rate=873.00000000, open_since=2020-07-19 16:00:47) [sell]: 0.51024118 KRW - rate: 0.0005
2020-07-20 02:36:28,516 - freqtrade.strategy.interface - WARNING - Outdated history for pair AERGO/KRW. Last tick is 36 minutes old
2020-07-20 02:36:28,550 - freqtrade.strategy.interface - WARNING - Outdated history for pair ARK/KRW. Last tick is 36 minutes old
2020-07-20 02:36:28,552 - freqtrade.strategy.interface - WARNING - Outdated history for pair QKC/KRW. Last tick is 36 minutes old
2020-07-20 02:36:28,554 - freqtrade.strategy.interface - WARNING - Outdated history for pair XEM/KRW. Last tick is 36 minutes old
2020-07-20 02:36:28,560 - freqtrade.strategy.interface - WARNING - Outdated history for pair KMD/KRW. Last tick is 66 minutes old
2020-07-20 02:36:28,570 - freqtrade.strategy.interface - WARNING - Outdated history for pair LOOM/KRW. Last tick is 51 minutes old
2020-07-20 02:36:32,202 - freqtrade.data.converter - INFO - Missing data fillup for LOOM/KRW: before: 199 - after: 216
2020-07-20 02:36:32,218 - freqtrade.data.converter - INFO - Missing data fillup for ARK/KRW: before: 199 - after: 208
2020-07-20 02:36:32,233 - freqtrade.data.converter - INFO - Missing data fillup for XEM/KRW: before: 199 - after: 215
2020-07-20 02:36:32,505 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=2, pair=ONT/KRW, amount=1.14660939, open_rate=873.00000000, open_since=2020-07-19 16:00:47)

and this is what I got from the Database:

> 

2 | upbit | ONT/KRW | 1 | 0.0005 | 0.500494998735 | KRW | 0.0005 | 0.51024117855 | KRW | 873.0 | 873.0 | 1001.50049331666 |   | 890.0 |   |   | 1000.98999747 | 1.14660939 | 1.14662084 | 2020-07-19 16:00:47.043661 |   | bd900ac3-c780-4454-b28e-f1030174ddba | 844.6275 | -0.0325 | 844.6275 | -0.0325 |   | 2020-07-19 16:07:27.548449 | 892.0 | 873.0 | sell_signal |   | BR3 | 15

Please let me know if I can give you any more information.  Thanks.

**Comment by viti0sus1** [comment]
This is for one of the first trades it made:

> GET https://api.upbit.com/v1/order?uuid=4f31c984-fcf0-4261-97f8-c51363c7b498 200 {'Date': 'Mon, 20 Jul 2020 02:08:53 GMT', 'Content-Type': 'application/json', 'Content-Length': '543', 'Connection': 'keep-alive', 'Remaining-Req': 'group=default; min=899; sec=29', 'Access-Control-Allow-Origin': '*', 'ETag': 'W/"b7b740f2fc0ff95601df1830c1a8512d"', 'Cache-Control': 'max-age=0, private, must-revalidate', 'X-Request-Id': '97da9aa1-772f-4445-b0c6-ce6ec62e71ad', 'X-Runtime': '0.029470', 'Vary': 'Origin', 'X-Kong-Upstream-Latency': '32', 'X-Kong-Proxy-Latency': '0', 'Via': 'kong/1.4.3'} {"uuid":"4f31c984-fcf0-4261-97f8-c51363c7b498","side":"ask","ord_type":"market","price":null,"state":"done","market":"KRW-ATOM","created_at":"2020-07-20T03:54:18+09:00","volume":"0.20702998","remaining_volume":"0.0","reserved_fee":"0.0","remaining_fee":"0.0","paid_fee":"0.5082586009","locked":"0.0","executed_volume":"0.20702998","trades_count":1,"trades":[{"market":"KRW-ATOM","uuid":"a1239ae1-ab92-4284-9b83-2cecaa4d3578","price":"4910.0","volume":"0.20702998","funds":"1016.5172018","created_at":"2020-07-20T03:54:18+09:00","side":"ask"}]}
{'info': {'uuid': '4f31c984-fcf0-4261-97f8-c51363c7b498', 'side': 'ask', 'ord_type': 'market', 'price': None, 'state': 'done', 'market': 'KRW-ATOM', 'created_at': '2020-07-20T03:54:18+09:00', 'volume': '0.20702998', 'remaining_volume': '0.0', 'reserved_fee': '0.0', 'remaining_fee': '0.0', 'paid_fee': '0.5082586009', 'locked': '0.0', 'executed_volume': '0.20702998', 'trades_count': 1, 'trades': [{'market': 'KRW-ATOM', 'uuid': 'a1239ae1-ab92-4284-9b83-2cecaa4d3578', 'price': '4910.0', 'volume': '0.20702998', 'funds': '1016.5172018', 'created_at': '2020-07-20T03:54:18+09:00', 'side': 'ask'}]}, 'id': '4f31c984-fcf0-4261-97f8-c51363c7b498', 'clientOrderId': None, 'timestamp': 1595184858000, 'datetime': '2020-07-19T18:54:18.000Z', 'lastTradeTimestamp': 1595184858000, 'symbol': 'ATOM/KRW', 'type': 'market', 'side': 'sell', 'price': None, 'cost': 1016.5172018, 'average': 4910.0, 'amount': 0.20702998, 'filled': 0.20702998, 'remaining': 0.0, 'status': 'closed', 'fee': {'currency': 'KRW', 'cost': 0.5082586009}, 'trades': [{'id': 'a1239ae1-ab92-4284-9b83-2cecaa4d3578', 'info': {'market': 'KRW-ATOM', 'uuid': 'a1239ae1-ab92-4284-9b83-2cecaa4d3578', 'price': '4910.0', 'volume': '0.20702998', 'funds': '1016.5172018', 'created_at': '2020-07-20T03:54:18+09:00', 'side': 'ask'}, 'order': '4f31c984-fcf0-4261-97f8-c51363c7b498', 'timestamp': 1595184858000, 'datetime': '2020-07-19T18:54:18.000Z', 'symbol': 'ATOM/KRW', 'type': 'limit', 'side': 'sell', 'takerOrMaker': None, 'price': 4910.0, 'amount': 0.20702998, 'cost': 1016.5172018, 'fee': None}]}

and here's what I got out of the database:

1|upbit|ATOM/KRW|1|0.0005|0.50049497665|KRW|0.0005|0.5082586009|KRW|4835.0|4835.0|1001.50046173088||4910.0|||1000.9899533|0.20702998|0.20703205|2020-07-19 15:46:53.112238||4f31c984-fcf0-4261-97f8-c51363c7b498|4677.8625|-0.0325|4677.8625|-0.0325||2020-07-19 15:49:57.153722|4960.0|4825.0|roi|partially filled - keeping order open|BR3|15

As you can see, even though on the exchange all of it sold, the database still thinks it was "partially filled" and kept the order open.
