### ISSUE TITLE
How to increase candles from 500 to 1000? Binance. Production Mode.

### ISSUE THREAD

**Issue by ragnarok0501** [freqtrade/freqtrade#3581]
## Describe your environment

  * Operating system: macOS Mojave v.10.14.6
  * Python Version: 3.8.3 64 bit (`python -V`)
  * CCXT version: 1.30.2 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop-5a189ae2 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
How to increase candles from 500 to 1000 in binance production/live trade mode?

Output:
2020-07-11 19:23:04,235 - freqtrade.data.converter - INFO - Missing data fillup for PPT/BTC: before: 499 - after: 502
2020-07-11 19:23:04,283 - freqtrade.data.converter - INFO - Missing data fillup for ENJ/BTC: before: 499 - after: 502
2020-07-11 19:23:05,903 - freqtrade.worker - INFO - Bot heartbeat. PID=2643, version='develop-5a189ae2', state='RUNNING'

Test1:
in "config.json"
"exchange": {
        "name": "binance",
        "key": "XXX",
        "secret": "XXX",
        "ccxt_config": {
            "enableRateLimit": true
        },
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
        "_ft_has_params": {
            "ohlcv_candle_limit": 1000
        },

Test2:
in "exchange.py"
class Exchange:

    _config: Dict = {}

    # Parameters to add directly to ccxt sync/async initialization.
    _ccxt_config: Dict = {}

    # Parameters to add directly to buy/sell calls (like agreeing to trading agreement)
    _params: Dict = {}

    # Dict to specify which options each exchange implements
    # This defines defaults, which can be selectively overridden by subclasses using _ft_has
    # or by specifying them in the configuration.
    _ft_has_default: Dict = {
        "stoploss_on_exchange": False,
        "order_time_in_force": ["gtc"],
        "ohlcv_candle_limit": 1000,
        "ohlcv_partial_candle": True,
        "trades_pagination": "time",  # Possible are "time" or "id"
        "trades_pagination_arg": "since",

Test3:
in "binance.py"

class Binance(Exchange):

    _ft_has: Dict = {
        "stoploss_on_exchange": True,
        "order_time_in_force": ["gtc", "fok", "ioc"],
        "trades_pagination": "id",
        "trades_pagination_arg": "fromId",
        "ohlcv_candle_limit": 1000,
    }

Congratulations for the great project, i had found everything on the documentation or here.
Thanks in advance.

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
sorry, completely missed this issue.
I don't think this is possible at the moment - as we rely on the ccxt defaults for candle-limit. 
This allows compatibility with untested exchanges - and usually, the default 500 candles are enough.
