### ISSUE TITLE
Multiple instances slow downs Ubuntu

### ISSUE THREAD

**Issue by sbralin** [freqtrade/freqtrade#3588]
Hi, I have multiple strategies and run multiple instances of freqtarde bots via *.service in /etc/systemd/user. But it causes problem with memory and OS Ubuntu freezing and it needs to reboot....How to optimize memory ussage of each instances?

**Comment by xmatthias** [comment]
How much memory does your server have, and how many instances are we talking about that run on this server?

We recommend 2GB per instance - although certain strategies can run below this as well - it'll strongly depend on the strategy used.
When you're having problems with memory - please stick to this recommendation and provide 2GB per instance to the bot.
There is nothing to optimize memory usage, really, other than making sure you're using python3.8 (it's slightly better than 3.7).

One additional thing to point out: 
Linux will usually not "freeze" and need a reboot if single (non-system) processes start consuming too much memory, but will start killing high consumers (processes).

If the system freezes completely, you might have a different problem (broken ram module, ...), corrupt OS installation, ...

**Comment by sbralin** [comment]
I have 7 instances of freqbot or 7 files *.services in etc/systemd/user
each started command systemctl --user enable/start *.service....

I have 7 strategies for each alts

**Comment by xmatthias** [comment]
And how much memory has the machine?

**Comment by sbralin** [comment]
2 BG

**Comment by xmatthias** [comment]
As stated in freqtrades [hardware requirements](https://www.freqtrade.io/en/latest/#hardware-requirements), freqtrade requires 2 GB. This assumes running one bot on the machine.

You will probably get away with running 2-3 bots on 2 GB of ram - but more will simply not work.
If you want to run 7+ bots on one machine, please increase the memory to at least 4GB (see how it goes with that) - and if you still run into issues, increase the memory further (precise data will heavily depend on the strategy / strategies you're running - so we cannot precisely say how much will be needed).

However, running 7 bots on one machine will most likely also run you into API rate-limiting issues, so my suggestion is to scale horizontally (use 2-3 2GB machines). This way, you'll have different IP Addresses, so the exchange is not being bombarded from the same IP address.

**Comment by hroff-1902** [comment]
you may run `top` or `htop` utility in a sep. terminal window and look at the memory consumption; I also think the system is simply went to the deep swapping
