### ISSUE TITLE
Telegram erros with multiple bots

### ISSUE THREAD

**Issue by sbralin** [freqtrade/freqtrade#3600]
I run couples of freqtrade bots on the same 1 machine OS Ubuntu. All freqtrade bots are connected to one telegram bot token.
In config.json files couples of bots have the same telegram token ID. I have telegram erros in logs of freqtrade bots...
```
{
    ......................... 
    # I have couples of config*.json files with various pairs and strategies....But all have the same telegram token and chat_id
    "telegram": {
        "enabled": true,
        "token": "xxx",
        "chat_id": "xxx"
    },
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```

**Comment by xmatthias** [comment]
Please have a look at the [documentation](https://www.freqtrade.io/en/latest/advanced-setup/#running-multiple-instances-of-freqtrade) regarding running multiple instances of the bot.

> Use different Telegram bots

Telegram does only allow one controlling process per bot. To run multiple bots - please create one telegram bot per freqtrade instance.

**important** 
Also - The telegram tokens should be treated as secrets. 
I've removed them from the above post - however they will still be visible in the post's history, therefore please delete the telegram bot you just shared the token with the world and create 2 new ones (one per freqtrade bot).

**Comment by xmatthias** [comment]
Going to close this as it's clear from the above that you're using the same telegram bot on multiple freqtrade instances.

Feel free to comment below if there are still questions after reading the [documentation](https://www.freqtrade.io/en/latest/advanced-setup/#running-multiple-instances-of-freqtrade) related to this.
