### ISSUE TITLE
A way to only export the Strategy summary of backtesting?

### ISSUE THREAD

**Issue by tikkeninc** [freqtrade/freqtrade#3603]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Say I would like to backtest several strategies and compare. I'd write this command:

`run --rm freqtrade backtesting --strategy-list ADXMomentum ASDTSRockwellTrading AdxSmas AverageStrategy AwesomeMacd BbandRsi BinHV27 BinHV45 CCIStrategy CMCWinner ClucMay72018 CofiBitStrategy CombinedBinHAndCluc DoesNothingStrategy EMASkipPump Freqtrade_backtest_validation_freqtrade1 Low_BB MACDStrategy MACDStrategy_crossed Quickie ReinforcedQuickie ReinforcedSmoothScalp Scalp Simple SmoothScalp Strategy001 Strategy002 Strategy003 Strategy004 Strategy005 TDSequentialStrategy --timeframe 5m`

I've automated it so that it just reads whatever strategy file I have in the Strategies folder and runs it every Monday, then exports the results to JSON files.

But I'm getting JSON files with a bunch of arrays with values inside of them;

```
    [
        "MBL/BTC",
        0.00999001,
        1592608500,
        1592610600,
        1126,
        35,
        2e-7,
        2.0240240240240237e-7,
        false,
        "roi"
    ],
```

I honestly just want the Strategy summary;
<img width="1327" alt="Screen Shot 2020-07-16 at 5 49 44 AM" src="https://user-images.githubusercontent.com/68200738/87708604-e2ab7580-c79a-11ea-9da3-0d39d9fba13a.png">

Any suggestions on how I can export only the Strategy summary?

**Comment by xmatthias** [comment]
Its not possible at the moment, but will be added as part of #3558 .

**Comment by tikkeninc** [comment]
> Its not possible at the moment, but is part of #3558 .
> 
> Either use that branch, or copy/paste the terminal outout yourself.

Awesome, great to know!
