### ISSUE TITLE
How would I use 24h bitcoin percentage change as a buy indicator

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#3607]
## Describe your environment

  * Operating system: Linux Mint Tricia
  * Python Version: Python 3.6.9
  * CCXT version: ccxt==1.28.49
  * Freqtrade Version: freqtrade 2020.5
  
## Your question

I would like my bot to buy pairs only if the 24h change in the bitcoin is greater than or equal to 0.20% as I have noticed it does much better during that window period. In my naivete I have gone to an extent to trying to scrape the value but I have not been successful since it is a dynamic value that would need other prerequisites such as selenium, let a lone extra authentication issues. My question is, is there a way that this value can be pulled to the main dataframe of indicators so that I can easily populate it as one of the buy indicators? e.g. simply adding say:

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                (dataframe['tema'] > dataframe['tema'].shift(1)) &  # Guard: tema is raising
                dataframe['24h_percent_change'] >= 0.002  &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'buy'] = 1

        return dataframe

I will highly appreciate your comments on this.

**Comment by xmatthias** [comment]
Well - i guess the simplest way is to use [informative pairs](https://www.freqtrade.io/en/latest/strategy-customization/#get-data-for-non-tradeable-pairs).

A (almost) full sample can be found in the [strategy repository](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/InformativeSample.py) .

Obviously, you'll have to calculate the pctchange yourself (which is `.pct_change()` when using a daily dataframe).

Hope this gets you started.

**Comment by moinonin** [comment]
Thanks @xmatthias I found my way around it. I figured out how to use the percentage change as a buy indicator.
