### ISSUE TITLE
Rebase on Alpine Linux, use distro python packages where possible, use s6 process manager

### ISSUE THREAD

**Issue by bolet** [freqtrade/freqtrade#3617]
I won't fork the project on github to open a pull request but I am dropping my patch here because it may be useful to some people.

Basically I only worked on the docker image:
- Rebase the image on current [Alpine Linux](https://alpinelinux.org/) (much smaller than debian and uses less ram).
- Bring latest python packages from [alpine repositories](https://pkgs.alpinelinux.org/packages?name=py3-*&branch=edge&arch=x86_64) (they are pre-compiled and up to date), use pip only when necessary.
- Use [s6 process manager](https://skarnet.org/software/s6/) to handle multiple bots in the same container (and restart them should they crash). The s6 layout for starting and controlling jobs is quite simple, but I'm willing to help if needed.

I have one such container handling 3 bots (different markets and strategies) running for about one month on a RPI like board, plus the same container built on arm64 (which I use for backtesting because it's much faster).

Cheers!

Obtained with `git diff master MYBRANCH | gzip | base64` 
Copy-paste in PATCHFILE and then `cat PATCHFILE | base64 -d | gunzip | git apply`

```
H4sIAC45F18AA60Ya2/bOPK7fgUvwe0CUUhZlu3YBnxo2nT3ArRpL8keUOwtspREO6olUStSSXy//mZI
SZb8yC4OSQFXmuE8OU/FyXJJKF0lmnCPxTJaizJZ5bIUJOy/O0keixcyHAZhEPo+Y8OQB4NlFBF/MJiM
Rg6ldJeH47ruHp937wj1z/0xceH3grx75xAG8u1vfYZeGYplkgKP7fMZHOrxopHMl8mKfVcyP3Nc+wYP
9hCF82dM/ZEmWgBlJJ9EyVeijOBFrFbKinysQngoNmmSa4PSJX9KFNtkqeOyq7uHO42iyIcvN/e31+9/
ub+++ZllsUM+X95c//Tx7p4luUNuP15eff6IcLosxR/AIxZMifIpicCEPdCZE/c835qO7tr6wfp8ORxM
lpGYMDbivphGXOz4fEtQO3wLQG/PRucBceF3At4mmpcroT2HOORUvESi0InMwRd/O0OytRCF4zru6Wce
dc3vqbu9ERDWuSqrbjgJgmAZQoiIwXgQc3/WV7d7t0bdDsAGx9TERoCxQX+6/fKZFBv9KPN5wKYsoCpN
MhpWSovScQ2ap0WSi7mIV3BPDr395YbwQlMwk1RFzLUg/3Eogb8ffmgRdEOSXGmepiSqypSEVZLGVCgl
cp3wlKRJqFRKY/F0gDhKBc8B7n748vUbQNcPpSgU8YSOPHjz4E2qBByXCOW4Vp814XEMLqw1wocVhgQ8
5ZJGPHoUXU1CrgSRhcgbLdD1IJHUf4n1CbgmoHmVFRtzCN8KnsdcmUctUgFCwF1SGwAkA09BUrYxr7ws
5bN5MvK1lKnqCkEMhG4llLYMQT9wTGCen0twh3nC9FPIlVupPKxStNHgkvw7H+4yXaZcrS3+2fKIZCpB
U8uhKGVW6AfUZ9032x7FRE5T1bBai6kl22jQtPNIudrkUSK7IKDuvmYQfHvaQSimCDcKyhBMbtRalRAi
IS93SVQEF9I8gc4UIqTMuwAJiZYl/7VeKZICOJA6rPCtCcZtXADUJCn5CuHEoTSI/CkpZZ5BhNpEmWCS
uEPIFR8zG+MsiomnswK54v9ezfZBcwpWMPWImDIjtLT4M4uASvnx5t/k09XDp+v3t5e33x6+Xt7/k3iV
Kj3wBE89OGS1ua4VjQUEZyzAvRDj1CQChkpSClRQMf2iewBwfJbJfB/+uClECd4xGK8tlZ5N5K5vTJx3
8oXGSWmzc9eJ5Ssi+vR1Dr+B6j1MkcoDUEjRPSvdXSt3lW+IdvTuXQakPBEvIqq06VRgEHvdlVTAiR2O
9CN0uG9fv1zf3JNfT1rqk98cekquxJJXqSZaEgMlmYyhAX/4fEV+JSf2IPntgDX7gnZvCyqb+6h1oeae
Zxsy9Oqso74W0WOeQBTu1tK2cKoJ3COqcuKFSe6pCVVPKuL5yTk56TCqoP0+QPnlXt2HFYvBvF5za6t5
2D46uXgmpt2h0U03s91uUP8x5vuTaDkKpqbNeXBrXl6lad3jWlaYuIPzAXY40+CM5WB4njLbxmAOqV6Y
LFeeffewrXkZhynjL57FaK3yRG/+KgEWwiRf9f1Qz1DADHqZwHEIzNgHOjH0GC3iY/4ZzeJpwPmYscZT
9RhwgBW6aus4OwsMfeKiv3AWgD+HQu1XMLHMyY/Bjw5t7nGOVaC96Lnt2EkG4958C0a7t2cybkYIc/L0
T86CUtARiubwe2zRBMgLQonM0w3JhYjBCc+PIsfYTHCo4v0iSbCG23MNH9Pq580bITDAavGi54RtYXE7
Hc3JCesMS6xNixN7GloTDHdAXeUpdCmqtCyKRhiyhhiC+M951jXUop9kWmW1G/GPoqw2XeaHcuik0bEp
DRh3WIjgRO2JsspzCCzyuzWC1JcNU9nvjVaGZE7+0Qju6ARa0FSuTGAdTGJAqi2CweuWMA5xWCF2+ocU
8A5yMO/qKWi2hJbcrhKHxXaWji2BglNarDbkjmdFKu7q135OdTp4nVA7kDppphPBB8HYx4mfRzHM0f0R
epfK1phdKCbQeAxTvwu/WGx64Th36ou2AxTV0Msoz3Opeb0RWHQ9J5VwTTKjsowhZ2oU1naHmn89M4/1
zvAYplkuZ6NpOF0GUEvHw8nFMNwx+xi1Nf8Y1taRwCycw6FZOE97HZY8Q9ORVb9XN92JhxB9TwnHBIo5
kmIphow3Ub6UJbnlqghFWcL4lzRUMBFF0YteLHwWDNgIesLdvz5d2snbAJkPMDvC96Z0QA4ZoMxkvlgM
wBPswumM54vFiPnMd9q5fLEYsuGIQVmth3PkPxyzmWMndHwFnkCxHdMXi4ANkeT+kn5KQpQzMho1oztC
pii42EQSMlhEa2n4IpEd6VGuDxDcFtFWx7XMHLdDY6eUJVwv/JRKn5MPRMFkHD2Cp6AglnyjUMgDHnnw
ldWWjZBJC7NMPkkeE52YOoIlQZFg8HeyrIt47UowOInRTjRgBka7uwjL7EbqZLkhagPUuLOrODcQJAvQ
pgZgj1/CzWKnQUlmdbFqDus3XGIo1G3Mrdj4doT+trhIlgph4FDH3T/ewPAYLq+n5K4qCllqE1tmK4Kl
ASwXZZZgS4FALSrttAuTvbzAadoS1tu6elk3JdBTSh7pBFrYxqEmarA7lSYSx2iF3bdovW9ZbceO2zn6
SoI382l4EFyntohHy+nyAiradLC8GIqL4JXUbkgP5HWDwqQOzn2obfBrpoO9ubkZwfcx3bEdfd4ulBjT
AwxxWxPREVNwLT1SIk1+bo9TncQbmmR4e3WeAi7bFCasLqZDp146F4uxubKdLdWwM5m8XVVNlg06MNxX
US9TAw7UZrzTASbQsbLuHlDWcVFLkyz7tR4j64PMwUWafK/wSEmAnQilXCvcBzJermP5nOOoUhkPOzQP
I0uCtk4wEVvIK6HU26fC47imX1xMR2EEFZJdRL644KF4Jah69Aciq4evP1KaMb1pGdd5lFYw3uLK0usU
4AIYdIiGPQQqONuLN8ORYmrfWqjtG41Ax348sMk4cHofEDAkhgFe9c5XBBNRcM3ttwqbtD7EmP1gUfcO
3+l+tRjiqTHW1+N30G6u4WF4k9DRmC+DOGQsHs04n4bxK75vaQ/4vcVZn4/bzegtXI7M0w3m4hTrHES4
ARw3/4DlHaN9MfFjf4IBF0ZxPIhmx40+Yu+uqU10mfZmp5aeJfvVqzPagIXmm4hpRzNTJczHP1sExn0z
twNsyKM1JjpspAoGd+U1X35B179w6s9WPjGZxWI4Czsr3xFFzM9B4T3M2wlscu6IyfvotxNtlpWDUnuY
txPY1ujDUvfRbye6XoZgyzgs+wD+/xD+PzgUQry9GgAA
```

**Comment by xmatthias** [comment]
Hi,

thanks for your efforts.
Please understand that i have to close this and not accept it this way for the following reasons:

* it's a issue not a PR with an obfuscated blob of text users are supposed to run, which only works on linux, and honestly, is a security risk as this code could also be a zip-bomb (in theory - i know it's not) - or something worse.
* Removing pinned dependencies from requirements files
  * this suggests that you had problems with versions between APK and requirements files - which makes me think that the APK versions are not all uptodate even though you claim they are.
* removal of all userdata folders (this will be problematic for updates, as this patch will not apply correctly if users have data in these folders)
* removal of docker-compose.yml file
* Lack of documentation on how you intend to set up s6 to run multiple bots
  * generally, the preferred method to run multiple bots via docker is via one docker-container per Bot this works fine and i run multiple bots on one machine using that method myself, and allows to update the strategy/ config for each container by restarting them via `docker-compose restart freqtrade1`.

Also, this patch does not apply against develop - which means that it'll also not apply against master as soon as we release a new version.

One sidenote:
We might accept the conversion of the dockerfile to alpine if it's done as a Pull request (against develop!) - leaving non-related files (requirements*, docker-compose, ...) files in peace.

Also, that PR should do this for all dockerfiles / dockerfile templates, not just for one - as with this, people using the technical module / Dockerfile would encounter problems.

Thanks for your understanding.

**Comment by bolet** [comment]
Thanks for the reply.

- A base64/gzipped file can be confusing indeed, sorry for that.
- I haven't even tried to make the whole stuff work with explicit versions of packages. I am assuming backward compatibility is a general rule in release management, so not specifying a package version should bring the latest, and hopefully best one. Maybe my assumptions are wrong.
- The meaning of the current user_data changes when running multiple bots on the same container. Now we have
  - a history data per exchange (maybe current bots working on the same exchange will race to write to this dir? I haven't checked the source code),
  - a dir with a config.json and a tradesv3.sqlite per bot.
The change is unfortunately not easily compatible with the current layout (we have to move existing files and folders in new locations). The patched Dockerfile shows where s6 will look for it's configuration (/freqtrade/user_data/services.d) and my docker-compose.yml is simply:
```yaml
version: '3.7'
services:
  freqtrade:
    image: freqtrade-alpine:local
    build: ./build
    restart: always
    hostname: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
```
Then the relevant new dir structure with s6 is (from inside the container):
```sh
# ls -l /freqtrade/user_data/services.d/tony/
-rwxr-xr-x 1 root root 216 Jun 28 17:21 run

# cat /freqtrade/user_data/services.d/tony/run
#!/bin/sh
BOT=tony
cd /freqtrade
exec freqtrade trade --db-url sqlite:////freqtrade/user_data/bots/$BOT/tradesv3.sqlite --config /freqtrade/user_data/bots/$BOT/config.json --datadir /freqtrade/user_data/data/binance

# ls -l /freqtrade/user_data/bots/tony/
total 148
-rw-r--r-- 1 root root   4020 Jul 22 10:40 config.json
-rw-r--r-- 1 root root 147456 Jul 22 21:35 tradesv3.sqlite
```
A pstree shows:
```
        ├─containerd─┬─containerd-shim─┬─s6-svscan─┬─s6-supervise───freqtrade─┬─{freqtrade}
        │            │                 │           │                          └─{freqtrade}
        │            │                 │           ├─s6-supervise───freqtrade─┬─{freqtrade}
        │            │                 │           │                          └─{freqtrade}
        │            │                 │           └─s6-supervise───freqtrade─┬─{freqtrade}
        │            │                 │                                      └─{freqtrade}
```
This bug was meant to be closed anyway, it was just a convenient place to share my progress and maybe inspire evolutions of freqtrade. On my side I'll adapt my changes with upcoming releases of master.

Congratulations for freqtrade, I've tested a dozen different bots before selecting this one.
