### ISSUE TITLE
Crypto scanner

### ISSUE THREAD

**Issue by NilanjanaBala** [freqtrade/freqtrade#3634]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement
Is there any way to make freqtrade to help scanning potential pair to buy or sell. After scanning I want to place entry manually.

Any tips / guide please.

*Explain the enhancement you would like*

**Comment by xmatthias** [comment]
I guess you can run freqtrade in dry-run mode - and act on the buy telegram message manually by placing the trade on the exchange manually.
freqtrade will then also send you a notification for sell - so you'll simply have to ignore these.

It is however not the intend nor the goal of freqtrade to act as a scanner only - so we will not take any steps towards enabling this explicitly.

**Comment by xmatthias** [comment]
I'll close this as i think the question has been answered.

Feel free to comment below / reopen this issue if there's something more to add to this topic.
