### ISSUE TITLE
My env could not be created when installing freqtrade

### ISSUE THREAD

**Issue by ebuka-odih** [freqtrade/freqtrade#3636]
Yes i have searched for it and there is no explanation of such bug

## Python 3.8

When i was installing Freqtrade using the first method of cloning and installing.
when i installing it i was asked to reset the git branch i entered "Y" and press enter
then it gave me an error saying 
`` Reseting branch and virtual env
----------------------------
Reset git branch? (This will remove all changes you made!) [y/N]? y
- Hard resetting of 'master' branch.
HEAD is now at d0d63426 Merge pull request #3543 from freqtrade/new_Release
- Delete your previous virtual env

Error: Command '['/home/emma/Desktop/freqtrade/.env/bin/python3.8', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Could not create virtual environment. Leaving now
``

**Comment by xmatthias** [comment]
it's not clear how you're installing freqtrade, please include more details (other than "first method" ).

the command above `python3.8 -lm ensurepip --upgrade --default-pip` is not something the install-script (`install.sh`) is executing explicitly.
I suspect this could be executed while creating the virtual environment - which would suggest an error with that - which can be either a permission error - or something wrong with the python that's creating the environment).

Please understand that we don't provide support for base python problems - and support for these must be received through appropriate channels where the experts for these problems are.

**Comment by ebuka-odih** [comment]
Okay, but is there any reason why ./setup.sh -i is using the python3.8 when I have 3.7?

**Comment by xmatthias** [comment]
it'll use the latest python available. 
so if you have 3.8 and 3.7 and 3.6, it'll use the highest available (For now, excluding 3.9 as that's not yet officially out).

**Comment by ebuka-odih** [comment]
Is there a way i could change the Python V that its using, because I think is my pip for python3.8 that is causing the error.

**Comment by xmatthias** [comment]
no, setup.sh will always use the latest version available.

if python3.8 is broken on your system, best either fix that, or remove python 3.8.

**Comment by ebuka-odih** [comment]
Thanks very much, i removed the 3.8 and now is working fine.

**Comment by GonReina** [comment]
I am having the exact same issue, I managed to remove python3.8 and it is now using pyton3.7 however the same error comes up. I thought it might be because venv may not be installed but it is so I am not sure what is gong on

**Comment by xmatthias** [comment]
Please open a new issue with the details from your installation. 
Its questionable if you have the same error, and posting here will notify everyone in this thread.
