### ISSUE TITLE
Not trading on Binance US

### ISSUE THREAD

**Issue by Maxridenhour** [freqtrade/freqtrade#3643]
I have had great luck running the trading bot on dry run for about a month and I decided to put it into production a few weeks ago. I put some money into my Binance US account and setup the config file. I was able to run the bot for a few weeks with no errors and Telegram integration but it didn't make a single trade. I tried the same exact config file and strategy on dry run and got trades within a few minutes. Am I missing something or should I try a different exchange?

I am also having trouble with the pairs offered through Binance US. I know there are a ton more pairs than what is in this config file because I can trade them manually through the Binance site. 

> {
    "max_open_trades": 20,
    "stake_currency": "BTC",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "ticker_interval": "1m",
    "dry_run": false,
    "dry_run_wallet": 0.16,
    "cancel_open_orders_on_exit": true,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": true,
        "ignore_roi_if_buy_signal": true
    },
    "exchange": {
        "name": "binanceus",
        "key": "its_a_key",
        "secret": "its_a_secret",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
        "pair_whitelist": [
            "ADA/BTC",
            "BCH/BTC",
            "BNB/BTC",
            "ETH/BTC",
            "LTC/BTC",
            "XRP/BTC",
            "XTZ/BTC"
        ],
        "pair_blacklist": [
            "BNB/BUSD",
            "BNB/ETH",
            "BNB/EUR",
            "BNB/NGN",
            "BNB/PAX",
            "BNB/RUB",
            "BNB/TRY",
            "BNB/TUSD",
            "BNB/USDC",
            "BNB/USDS",
            "BNB/USDT",
        ]
    },
    "pairlists": [
	        {"method": "StaticPairList"}
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "token_goes_here",
        "chat_id": "and_the_chat_id_here"
    },
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

**Comment by xmatthias** [comment]
First of all - your primary analysis point must be the logs - they'll tell you if something is wrong.

well i can't use binanceus myself...

but it should be the same than binance - just for US users (with fewer pairs :disappointed: ).

Most likely, there is something wrong with the API keys - either the permissions are wrong (limited to a (wrong) IP).

Assuming settings for binanceus are similar:
the key must NOT be read-only and must have "enable trading" set to true.

I would recommend to leave all other's (futures, withdrawals, margin) disabled, so in case you ever "lost" your key, youre making it slightly more difficult for the "finder" of that key.

---

freqtrade will not have your keys in the logs - best start the bot with the config (with keys, obviously) - look at startup messages.
If they don't tell you what's wrong, try calling `/balance` - to see if freqtrade is able to get the balance correctly.

**Comment by xmatthias** [comment]
I'll assume that you were able to solve the issue and will therefore close this.

Feel free to reopen / comment below if you're still having problems.
