### ISSUE TITLE
What does <STAKE> mean in pair_blacklist?

### ISSUE THREAD

**Issue by rraallvv** [freqtrade/freqtrade#3646]
* Freqtrade Version: 2020.6
  
What does `"BNB/<STAKE>"` mean in the recommended option for `pair_blacklist` [when trading on Binance](https://github.com/freqtrade/freqtrade/blob/develop/docs/exchanges.md#blacklists)?

Does `<STAKE>` work like a wildcard in `pair_blacklist`, or do I have to add each entry for each BNB/* pairs separately like [this](https://github.com/freqtrade/freqtrade/blob/master/freqtrade/templates/subtemplates/exchange_binance.j2#L28-L39)?

**Comment by Theagainmen** [comment]
It means whatever market you're trading on, the most popular are BTC and USDT. So if you're trading on the BTC market, your stake is BTC and thus add BNB/BTC to your blacklist..

![image](https://user-images.githubusercontent.com/24569139/89101591-9e0e1400-d401-11ea-8920-3ede4446b05d.png)

**Comment by xmatthias** [comment]
It's intended as a sample - you can add all BNB pairs - or you can just add the one in your stake currency, this is up to you.

There is however currently no wildcard support for either blacklist, nor whitelist.

**Comment by rraallvv** [comment]
Thanks @Theagainmen and @xmatthias for the quick reply. I'm closing this then.
