### ISSUE TITLE
available pairs not matching exchange pairs on binance 

### ISSUE THREAD

**Issue by macd2** [freqtrade/freqtrade#3656]
Error: 
freqtrade.exceptions.OperationalException: Pair WAVES is not available on Binance. Please remove WAVES from your whitelist.

But the pair is definitely available on binace: 
https://nimb.ws/zSx5f9

in config i got:
`"stake_currency": "USDT",`

**Comment by xmatthias** [comment]
Please fill out the issue template, otherwise i'll close this issue without further comment.

Also, please include complete logs, not just one line, thanks.

**Comment by macd2** [comment]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.6 (`python -V`)
  * CCXT version: latest (`pip freeze | grep ccxt`)
  * Freqtrade Version: latest (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*


### Observed Results:
Error happen on startup and even for other pairs like ETH or even BTC 
quote / stake currency is USDT
### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2020-08-03 19:23:52,903 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
   File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
     worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 34, in __init__
     self._init(False)
   File "/freqtrade/freqtrade/worker.py", line 51, in _init
     self.freqtrade = FreqtradeBot(self._config)
   File "/freqtrade/freqtrade/freqtradebot.py", line 68, in __init__
     self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 30, in load_exchange
     exchange = ExchangeResolver._load_exchange(exchange_name,
   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 52, in _load_exchange
     exchange = ex_class(**kwargs)
   File "/freqtrade/freqtrade/exchange/exchange.py", line 125, in __init__
     self.validate_pairs(config['exchange']['pair_whitelist'])
   File "/freqtrade/freqtrade/exchange/exchange.py", line 320, in validate_pairs
     raise OperationalException(
 freqtrade.exceptions.OperationalException: Pair ETH is not available on Binance. Please remove ETH from your whitelist.
  ```

**Comment by xmatthias** [comment]
well the logs are pretty clear ...

ETH is not a pair - it's just one asset. - XRP/ETH would be a pair, or XRP/USDT.

Since your stake is USDT - then ETH/USDT is the correct way to define the whitelist.

**Comment by macd2** [comment]
why then defining the stake_currency separately? 

when leaving the stake currency at `USDT` but change the pair to `ETH/BTC` I get ` freqtrade.exceptions.OperationalException: Stake-currency 'USDT' not compatible with pair-whitelist. Please remove the following pairs: ['ETH/BTC']` 

so when stake currency is defined than the asset alone should be enough or at least also accepted!

**Comment by xmatthias** [comment]
pairlist is always a list of pairs - not single assets (and that's always been the case).

There's multiple reasons for that (mainly the flexibility things like VolumePairList provide).
Also, by supporting the "single asset" way, a potential multi-stake future will be prevented - as in that case, stake-currency MUST be unique.


Feel free to submit a Pull Request if you think this is worth the effort to change and i'm more than happy to review - however i think it's not worth the time - especially not since it is potentially introducing a limiting problem in the future.

**Comment by macd2** [comment]
I don't have time right now either but thanks for the clarification!
