### ISSUE TITLE
Bot does not trade

### ISSUE THREAD

**Issue by andykov** [freqtrade/freqtrade#3659]
Explain, please.
I downloaded data for the last 120 days on timeframes 1 and 5 minutes. For four couples.

I just changed the price of the bet and chose one of the standard strategies.

Then I made a copy of the configuration and started testing it. The "Average Duration" column indicates how many days the transactions took place. In my test, each pair took about 1 day. A total of 171 transactions were made.

Yesterday I started trading in combat mode, but yesterday and today there were no deals.
There was only an attempt, as far as I understand, to buy, a purchase order was created, but after 10 minutes it was canceled.
I don’t understand why there wasn’t a single deal in two days.
Is this normal bot behavior?

There are no errors in the console.

Bittrex Exchange
The secret keys are installed. The necessary checkboxes are enabled in the control panel on the exchange.

**Comment by xmatthias** [comment]
well - best backtest your strategy to know what to expect - as explained [here](https://www.freqtrade.io/en/latest/faq/#i-have-waited-5-minutes-why-hasnt-the-bot-made-any-trades-yet).

Strategies differ - some make 20 trades per day, others one every other day - backtesting / dry-run will tell you what to expect for the pairs you're trading.

Overall, crypto is also subject to market cycles, so depending on that (and on the strategy, obviously) , trade frequency will also vary greatly.

**Comment by andykov** [comment]
Got it. Thank!
