### ISSUE TITLE
Setting explicitely stoploss value inside "populate_buy_trend" function

### ISSUE THREAD

**Issue by larick** [freqtrade/freqtrade#3664]
For some strategies, I would like to be able to set dynamically a stop loss value depending of some data like indicators.

For instance, when I detect a Buy situation, I would like to set stop loss according to this Buy situation like setting stop loss equals to lower bollinger band

Same for ROI, I would like to set it as upper bollinger band on the Buy context.

Is there any workaround to adress this need, or do we need to have an additional feature in Freqtrade ?

Thanks in advance for your replies !

**Comment by xmatthias** [comment]
There is no working workaround for this as far as i am aware. Changing the config's stoploss can have other consequences, so i strongly advise against this 

We will have this eventually at some point in the future (most likely however via a callback, not assignable directly in the `populate_buy_trend()` method.

To be honest, this is not a priority for myself in the near future ... so please don't expect work on this anytime soon.

**Comment by larick** [comment]
Thanks for your answer ! I'm not a Python developper, so i'm afraid it will be too difficult for me !!

But i'm thinking to another way to adress my need : why not adressing that on "populate_sell_trend" with the following process :
--> in populate_buy_trend, I store somewhere (but I don't know where, ideally in the Trade) values for expected sell value for benefit and for stop loss
--> in populate_sell_trend, I compare current values to the stored ones. But for that working, I need to attach these values to the created Trade, because it is contextual to a trade !

**Comment by xmatthias** [comment]
simulating sells this way is an option - you might be able to use the [storage method](https://www.freqtrade.io/en/latest/strategy-customization/#storing-information) for this.

You most likely can't backtest this though - as backtesting works slightly (very?) different.

**Comment by larick** [comment]
I tried to understand a little bit more how it works (limited with my capacity to understand Python !) and the way it is designed seems that buy and sell signal computation can be computed only with "local" information. By local, I mean with the information of the current dataframe timetick.
I assume it is for having the same interface for live running and efficient backtesting (I mean backtesting without having to replay all the story tick by tick, but computing in bulk the buy and sell order)
It is good for backtesting efficiency, but then it brings difficult to have a more "alrogithmic" and "external data" computation for buy and sell signal !!

Then, I think that instead of the "local" enhancement I suggested, I could be better to have an enhancement allowing interface implementers to have more flexibility in signal computations.... but still compatible with callback ! not an easy task, but a big added value for Freqtrade if I may !

Unfortunately, my skills in Python are near to 0, I'm an old java 'man', so i'm afraid I won't be able to face it myself !!

**Comment by xmatthias** [comment]
#4089 will introduce a way to set this via the strategy.

It'll however be a custom strategy callback, not be set from within `populate_buy_trend()`, since this allows a lot better flexibility to control stoploss throughout the lifetime of a trade.
