### ISSUE TITLE
Wrong slippage on hyperopt with SharpeRatio

### ISSUE THREAD

**Issue by gathad** [freqtrade/freqtrade#3678]
https://github.com/freqtrade/freqtrade/blob/767332405e08478b7e82c64b0c1891fead3080bd/freqtrade/optimize/hyperopt_loss_sharpe.py#L35

This line has designed to use only one test which 0.0005 satoshi means %0.1 of trade amount. So, if the trade amount changes, slippage not stays same as percentage (for fee's).

Please revise it as following:

`total_profit = total_profit*0.999`

**Comment by xmatthias** [comment]
I think you're misreading what `total_profit` represents in this context.

It's the percentage of profit of this trade (see first line below) - so this is already a ratio (e.g. 5%). 

https://github.com/freqtrade/freqtrade/blob/767332405e08478b7e82c64b0c1891fead3080bd/freqtrade/optimize/hyperopt_loss_sharpe.py#L31-L35

Subtracting is therefore correct.

Using multiplication would make slippage dependent on profit, which it's not (no matter if i lost 5% or gained 5% - slippage can still be identical).

Slippage however has nothing to do with how profitable a trade was - it's just a general offset that we apply to account for eventual slippage. 
The value is arbitrary anyway - using 0.1% can be just as wrong as it can be correct, depending on your pricing configuration, on the selected markets, ...

**Comment by gathad** [comment]
Oh, I see! Sorry for wasting your time with my misunderstanding. You are correct, total profit is configured as percentage already.

On this matter, I need to learn more to set that amount according to my fees. 0.0005 represents %0.05 per trade isn't it? For binance, it takes %0,1 per order so I need to set it as 0.002. Is it correct?

**Comment by xmatthias** [comment]
Freqtrade considers fees (the default fee - 0.1% on binance) in both backtesting and hyperopt result already.

this value (slippage) is applied in addition to fees. it's assumign that you're not getting the price you're asking for (which in backtesting / hyperopt is always the candle's open price).

**Comment by gathad** [comment]
So, I don't need to make anything additionally according to fees.

Thank you very much!
