### ISSUE TITLE
Backtesting Different results same strategy

### ISSUE THREAD

**Issue by ovresko** [freqtrade/freqtrade#3679]
## Describe your environment

  * Operating system: WIN 10
  * Python Version: _____ 2.8
  * CCXT version: _____  
  * Freqtrade Version: ____ master
  
So i know this is a beginner question, but i've 2 strategies A and B (same periode, stake_amount, timeframe....)
when i run backtesting on A alone it gives me a result, but when i combine it with B both give identical results and A is no longer like the initial test, not even close.

**Comment by xmatthias** [comment]
Closing this as duplicate of #3680.
