### ISSUE TITLE
Dynamic Stake Amount doesn't run on backtesting

### ISSUE THREAD

**Issue by sinak7** [freqtrade/freqtrade#3681]
## Describe your environment

  * Operating system: Raspbian 10
  * Python Version: Python 2.7.16
  * CCXT version: 1.32.88
  * Freqtrade Version: develop-3670be5d
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
Hello,

I set dynamic stake_amount based on the instructions here https://www.freqtrade.io/en/latest/configuration/#dynamic-stake-amount and when I run `freqtrade backtesting --strategy Teststrategy002` , I got

`freqtrade - ERROR - The value of `stake_amount` cannot be set as "unlimited" for backtesting`

If you need more information, please let me know.

**Comment by xmatthias** [comment]
Dynamic stake is not supported during backtesting, since dynamic-stake would require to know the starting balance (and would require compounding to be available in backtesting, which it's not).

**Comment by sinak7** [comment]
Thank you very much for the ultra-fast response!
