### ISSUE TITLE
How accurate is a dry run?

### ISSUE THREAD

**Issue by MLidstrom** [freqtrade/freqtrade#3685]
I've been tinkering with freqtrade for two weeks now and got it tuned in as I like it. I've been using dry run connected to my binance account, but how do I know how this is translated to a real account? Are there any any hidden fees I don't see? Would my dry runs be accurate when applying them to a real account?

**Comment by xmatthias** [comment]
dry-run is generally accurate - as long as you give some good thought to how you price your trades.
If you don't / misconfigure pricing, you can end up with a lot of unfilled trades in live, which is a thing dry-run does not even try to simulate.

Dry-run assumes all trades are filled immediately.
You will not see any cancelled orders in dry-run - but that means that fill prices are as you configure them - which may or may not be realistic (depending on your configuration, like market vs. limit orders, which side you use for which prices, ...).

For the most realistic dry-run scenario, i personally swap sides (so each buy / sell action crosses the spread). This will reduce the profit by "spread" - but make the simulation more realistic, as this will also guarantee mostly filled orders.

--- 

Fees are included in the calculation (using the most basic level from binance), there are no hidden fees - at maximum fees in real mode are a little lower, depending if you use BNB fees, and if you're in a higher fee tier (like VIP1 or higher).

**Comment by MLidstrom** [comment]
Ok thank you.

Will I see the cancelled orders when I go live? In statistics I mean? I saw somewhere that unfilledtimeout.buy has default of 60 minutes (If I remember correctly). If I set that at 10 it would cancel any unfilled earlier. And I would rather adjust the price a bit than have unfilled trades stuck in the loop. What's the easiest way of doing that? I haven't found any example of that.

**Comment by xmatthias** [comment]
order cancellation sends a notification.

If the buy-signal is still there after the cancel, the bot will retry to buy using the latest price as configued.
You cannot however use a different price calculation method after a cancelled buy, as for the bot, this is treated as a new trade.

**Comment by MLidstrom** [comment]
Ok so if the order is cancelled the bot just drops it? It doesn't get stuck in the system? I mean it calculates a new price?

**Comment by xmatthias** [comment]
well the assumption is that if the order is cancelled - then price moved away from your place.

assuming you use 10m as timeout - and 15m as timeframe - then usually, the buy-signal iwll still be active, and the order will be placed - but at a price that corresponds to the current market price - not to the one 10 minutes ago.

**Comment by MLidstrom** [comment]
I have a 5m timeframe so I guess I should have a 5m timeout. And probably not trade with low volume pairs.

Ok I think I understand now :) Thank you!

**Comment by xmatthias** [comment]
it's not about volume, but it's also about the price itself - you can use the ask-side of the orderbook, or bid-side ... both have benefits and drawbacks. If you're not crossing the spread - then also on the most liquid pair you will find some timeouts as price is moving away from you.

**Comment by MLidstrom** [comment]
Ok got it. I probably have to do some adjustments when I go live then.

**Comment by xmatthias** [comment]
it's a possibility - yes.

Using the correct price is not an easy task - as it'll depend heavily on the strategy type (mean reversion, breakout, ...) - and on the pairs you select ... so there's not really a "you should use this" advice - and you can only really experience cancels in live mode.

**Comment by xmatthias** [comment]
i'll close this as i think the original question was answered.

Feel free to reopen or comment below if it's not been answered sufficiently.

**Comment by Botman-Hotman** [comment]
Hey I know this was closed but I wanted to ask what you mean by "swap sides (so each buy / sell action crosses the spread)."

Does this mean you put a sell = bid and buy = ask?

**Comment by xmatthias** [comment]
yes, that's what it would mean.
