### ISSUE TITLE
Any workaround to using a shorter dataframe 

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#3686]
## Describe your environment

  * Operating system: Linux
  * Python Version: Python 3.6.9
  * CCXT version: 1.32.7
  * Freqtrade Version: 2020.7
  
## Your question

Hi peeps!

I have this indicator that I would like to use. However, it filters down the whole dataframe to a length of just 2577 from like 11235. As a result obviously I get an interface error when I run edge with live trading. The error reads: 'Unable to analyze candle (OHLCV) data for pair {pair}: {error}' even though the backtesting results are much better than when I use the full dataframe. When I disable dataframe checking it then becomes the following warning: 'Dataframe returned from strategy has mismatching {message}' 

So the genesis of the problem comes when I filtered out the trades I would not want to get into by doing this to the returned dataframe just before populating the buy method:

dataframe = dataframe[dataframe['close-ind'] > dataframe['open-ind']]

'''
My buy strategy then looks like this:
        dataframe.loc[
            ( 
                (dataframe['close'].shift(1)<dataframe['bb_lowerband']) & 
                (dataframe['close'] > dataframe['bb_lowerband']) &
                (dataframe['rsi'] <= 48) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'buy'] = 1

        return dataframe
'''
Is there a workaround to using a shorter length dataframe without running into length mismatch error so I just analyse my 2577 length dataframe and try to get only into those trades?

Your replies are appreciated.

**Comment by xmatthias** [comment]
The strategy should work with the disabled check (however it'll post the warning).

I think this is done in a odd way i don't really understand.

Why do you have to reduce the length of the dataframe? 

In the end, it's just a filter - so you could also use `(dataframe['close-ind'] > dataframe['open-ind']) &` as part of the buy signal conditions, instead of removing all non-matching lines from the dataframe.

**Comment by moinonin** [comment]
Thanks @xmatthias I finally got my way around it. The strategy looks much promising now. 

Cheers!
