### ISSUE TITLE
Ability to set a custom fee for dry-run trading

### ISSUE THREAD

**Issue by Levos-IG1075** [freqtrade/freqtrade#3696]
## Describe the enhancement

Hi, just registered on github for a quick suggestion. I think it would be great to have an option to set a custom fee when running `trade` with `dry-run` enabled in the JSON config.

As for the parameter `dry_run_wallet`, I'd love to be able to set an option like `dry_run_fee`.
My strategy is based on small profits, and while I can set the fee in backtesting/hyperopt (with the `--fee` parameter), I didn't find a way to do it with the dry-run mode, and my strategy runs poorly.

What do you think?

**Comment by xmatthias** [comment]
What would be the reason for this?

Freqtrade is assuming the exchange's default fee for trades in dry-run (so for binance, thats 0.1%).
In reality, you will also be paying fees - given, these may be 0.075% if you're paying in BNB - however, considering slippage / sometimes unfilled orders, using a slightly higher fee in dry-run will make your dry-run more realistic.

---


Apart from that - Especially when aiming for very minimal profits per trade, you must be very careful how you price your trades (which side of the orderbook, which order type, ...) - as dry-run will always assume that an order fills within seconds - which in live may not the case if the order is priced poorly.

**Comment by Levos-IG1075** [comment]
> What would be the reason for this?

I think it would help with consistency between hyperopt, backtest and dry-run.

> Freqtrade is assuming the exchange's default fee for trades in dry-run (so for binance, thats 0.1%).
In reality, you will also be paying fees - given, these may be 0.075% if you're paying in BNB - however, considering slippage / sometimes unfilled orders, using a slightly higher fee in dry-run will make your dry-run more realistic.

I agree, in the meantime I've set a 0.2% fee to account for that. Maybe this could be mentionned in the docs?

If you think this is not a useful improvement feel free to close the ticket :)

**Comment by tejeshreddy** [comment]
@xmatthias I would like to take this issue up. I will look to set up the custom fee for dry run

**Comment by xmatthias** [comment]
sure, go for it :+1: 

I think it shouldn't be "too" hard - best look at the methods `dry_run_order()` and `_store_dry_order()` in exchange.py.

The setting (fee) should already be there for backtesting, so there's not "too much" additional setup required

**Comment by tejeshreddy** [comment]
@xmatthias that sounds great, thanks!!

**Comment by woerty** [comment]
I think this has been implemented by now?
