### ISSUE TITLE
Buying Multiple Postions Per Pair

### ISSUE THREAD

**Issue by ovresko** [freqtrade/freqtrade#3697]
## Describe your environment

  * Operating system: Win 10
  * Python Version: _____ 2.8
  * CCXT version: _____ 
  * Freqtrade Version: ____ 2020 07
  
## Your question
I've looked for the possibility of buying multiple positions for the same pair, as my strategy depends on it, i've tied setting max open trades higher, but it seems like freqtrade hold one trade open per pair in any given time.
if this is possible how ?

**Comment by xmatthias** [comment]
Freqtrade is limited to one position per pair.

While this limit is artificial, and lifting it may or may not require a lot of work (unclear at the moment), this is unlikely to change in the near future as it would break many peoples strategies (or lead to big surprises, anyway) - but we have an open issue for this in #1519 .

**Comment by ovresko** [comment]
Thank you for the response, 
can you point me where in code this has secondary effect (beside other people's strategies), i've found that the pair in question get thrown out of the whitelist before buy process if it has open trades.
https://github.com/freqtrade/freqtrade/blob/22f6e884edcdd5a3961751d8ee002d54551392a8/freqtrade/freqtradebot.py#L244

**Comment by xmatthias** [comment]
that is one point.

However, i don't think removing just this will suffice - as the whole of freqtrade is based around the assumption that there is only one trade per pair at a time.

If you want to change this, feel free to do so - but you should be very familiar with the freqtrade codebase first, as mentioned above, this may or may not be a simple change (most likely it's not).
