### ISSUE TITLE
Is it possible to set a Order before Listing Coin?

### ISSUE THREAD

**Issue by tobiashaas** [freqtrade/freqtrade#3698]
Is it possible to set a Order before Listing Coin?

**Comment by xmatthias** [comment]
It's not clear what you mean with this - but if it's before a coin is listed on the exchange, then the clear answer is no, this is not possible. Freqtrade needs some information about the coin - which the exchange API will usually only provide once the coin is listed.

Also, exchanges will usually only accept orders once they are listed - so i don't see how this would be possible.

**Comment by tobiashaas** [comment]
Thank you for your quick reply.
Stupid, that this is not possible 🤣

Or is there a possibility that the bot triggers the order as soon as the coin is available? It is very difficult to get the perfect price. 

And at the start you often have 10x 😅

Thanks

**Comment by xmatthias** [comment]
Freqtrade is basing it's buy-signals on technical indicators - on a new coin you will not have any history to even calculate a technical signal.

This is a very edge-casy usecase - which you might be able to get to by using a external forcesell (basically you tell the bot "buy now") ... but otherwise, i don't see this possible with freqtrade.

I must admit however, i'm not sure if it's possible to create a order on exchange before it starts trading ... but i would strongly doubt this - as it would give an unfair advantage to api users.

**Comment by xmatthias** [comment]
I'll close this as i think the original question was answered.

I also don't think this is anything freqtrade can help you with automatically - as it relies on technical analysis for it's buy decisions.

Also - exchanges don't provide information about upcoming new listings via their API (at least not the ones i use)- so the bot would not know about a new coin before it's even listed.
Furthermore, exchanges don't allow posting orders before the coin is listed - so it'd be a race with everyone else to get the "best" buy price - and would lead to MANY unfilled orders (assuming limit orders are used).

Feel free to comment below if you disagree with these points (or have additional information on how to get information about "upcomming coins" via API) ...

**Comment by Payback80** [comment]
I'm asking the same here.
I've tried to use to buy a new listed coin but it is impossible due the fact freqtrade need some indicators history.
Is there a workaround?

**Comment by xmatthias** [comment]
If your strategy doesn't require it, then freqtrade does NOT require coin history except for 1 candle (which you can get 1 minute after listing on 1m candles0.

you'll however need to find some way to add the pair on launch (it will not work before, as it'll be disabled).
So buying "right at launch" will not be possible, and i wouldn't know any workaround.

**Comment by Payback80** [comment]
thx for the ultra fast reply , however this is sad because there is a lot of room for profit.
Today i tried with a cron job and it worked, however i had to wait the candles and the opportunity gone

So, is there a way to just buy forcebuy at  process start?

**Comment by xmatthias** [comment]
well you can forcebuy every pair that corresponds to your stake currency (even if it's not in your pairlist).

the big problem from an automation perspective is though that there's no info available via API as to which pair will be newly listed when.

Also, there's a lot of chance for profit, but also for loss (just look at the first candle in LINA/USDT on binance) ....

**Comment by Payback80** [comment]
yes i know the chance of loss, i've sett the process polling to 100ms without api banning BUT:
how forcebuy works? Do i have to type it into telegram?

**Comment by xmatthias** [comment]
manually ... ? 

otherwise, you should probably use the API, not telegram.
Freqtrade provides a quick script for the [rest-api](https://www.freqtrade.io/en/latest/rest-api/#rest-api) - but for a automated script i'd recommend some more sophisticated implementation than that quick script.

**Comment by Payback80** [comment]
thanks again, now i know a little bit more :) 
so last questione is there a way to allow to start freqtrade (and ccxt) before coin listing using staticpairlist?

**Comment by xmatthias** [comment]
noish ... although you can skip pair validation with `exchange.skip_pair_validation` and `allow_inactive` [docs](https://www.freqtrade.io/en/latest/plugins/#static-pair-list) - i'm not sure how trade mode behaves, as this was really created to backtest expiring spot pairs (available on FTX, for example) - and not tested in trade mode.


to forcebuy a pair it doesn't need to be in the pairlist - so this should not limit a /forcebuy approach.
