### ISSUE TITLE
Backtesting with config edge.enabled = true

### ISSUE THREAD

**Issue by betogontijo** [freqtrade/freqtrade#3699]
## Describe the enhancement
Backtesting with edge enabled

*Explain the enhancement you would like*
I would like to backtesting a strategy with edge enabled. The problem is that to edge work i need to set steak_amount to unlimited. Once steak_amount='unlimited' backtesting throw this error "ERROR - The value of `stake_amount` cannot be set as "unlimited" for backtesting".
Is there anything I am missing or it is really not working right now?

**Comment by xmatthias** [comment]
Backtesting with edge is not possible. It's 2 contradicting methods to backtest.
There is edge cli (`freqtrade edge`) - which does something similar to backtesting and gives you the edge results - but it's not exactly the same than backtesting.

However, backtesting with edge enabled is not possible and most likely will never be.

**Comment by xmatthias** [comment]
I'll close this as i think the original question was answered.

Feel free to reopen / comment below if it's still unclear.
