### ISSUE TITLE
Run Two Strategies

### ISSUE THREAD

**Issue by tutecode** [freqtrade/freqtrade#3703]
Can I run 2 different strategies in the same account of Binance?

I want to run a Bot that use BTC, and the other with USDT

**Comment by tutecode** [comment]
Yes yes, I have a VPS in Vultr.

My question is now, If I have one server, can I run 2 SSH? Or I have to pay another server?

**Comment by xmatthias** [comment]
you can run 2 docker containers on a server, or you can use tmux / screen (which both allow multiple windows within one session).

You can also use 2 ssh connections - but in that case the bot will stop if you lose connection, so this is clearly not recommended.

Please note that your server specs are way below our minimal recomendations - so it will depend on the strategy if it will work (even for one bot) or not.

**Comment by xmatthias** [comment]
Going to close this as i think the original question was answered.

Feel free to reopen or comment below if you think differently.

**Comment by slowdive42** [comment]
How can I do this. I want to distribute funds between two bots. If there's only one bot signal , I'll allocate all the money to that bot. However, if there are two bot signals, I'd like to split the funds equally between them.

**Comment by stash86** [comment]
> How can I do this. I want to distribute funds between two bots. If there's only one bot signal , I'll allocate all the money to that bot. However, if there are two bot signals, I'd like to split the funds equally between them.

please open new issue instead of reviving old one. Thanks
