### ISSUE TITLE
Skip a sell order if the price is lower than buying price

### ISSUE THREAD

**Issue by idew7** [freqtrade/freqtrade#3715]
Hello,

So basically I want to know what command can I add to my code inside freqtrade strategy in order to skip a sell order if the price is lower than buying price (or negative profit (loss) ) so when next sell order appears it should be more than buying price in order to place the order for getting profit. Or if there is a price comparison between the buy price and sell price (sell price - buy price, if it's + positive then sell)

How can I implement this in my strategy populate_sell_trend section of the code?

**Comment by Theagainmen** [comment]
https://www.freqtrade.io/en/latest/configuration/#configuration-parameters the answer is here :) `sell_profit_only`

**Comment by moinonin** [comment]
It also depends on your buy strategy. There are prices if you buy with, you will never make a profit 😁 so keep that in mind. Buy signal is the most important component of the strategy, in the sense that you can leave the sell signal empty and still sell with trailing stop loss and ROI.

**Comment by idew7** [comment]
@Theagainmen I have checked the link, and I tried to implement it in my strategy but it doesn't start up, so I researched a bit and found that this setting is inside C:\Users\(NAME)\Desktop\freqtrade-develop\freqtrade\configuration\depreciated_settings 

Can anyone please tell me how do I implement it in my bot so strategy starts up?
