### ISSUE TITLE
hyperopt-show command does not display results

### ISSUE THREAD

**Issue by pyloud7** [freqtrade/freqtrade#3716]
Hello all, 

I surprised (positively) about the huge work done on this project.
I have a question concerning the command "hyperopt-show", I have downloaded data for cryptos, run backtesting, generated backtesting results and I can see results when I execute : 

![image](https://user-images.githubusercontent.com/52707465/91096809-eca87a00-e65e-11ea-8f09-2b0f294fd2e7.png)

Although the command that analyses the parameters for each epoch (hyperopt-show) does not display anything for me. Could you please help me out ? For sure I am doing something wrong, but I have no clue about what it is..

![image](https://user-images.githubusercontent.com/52707465/91097052-5163d480-e65f-11ea-90d4-d17061de7211.png)

**Comment by xmatthias** [comment]
Your output looks odd ... even the one that seems working (`hyperopt-list`) is missing a lot of output (from the bot startup, ...).

I guess this can be a terminal configuration - maybe it's configured to not show stderr? (this is where eventual errors and/or log messages whould be shown).

**Comment by pyloud7** [comment]
many thanks for your reply, indeed that was the error. Via git bash terminal in Windows there were no outputs/logs, although I run the same command via cmd and it worked correclty.
