### ISSUE TITLE
Forcesell: Exception within Telegram module

### ISSUE THREAD

**Issue by Blackhawke** [freqtrade/freqtrade#3717]
Tried to use the \forcesell <trade_id> on an open (stoploss on exchange) order and got the following error:

 > 2020-08-25 08:30:25,706 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram moduleTraceback (most recent call last):
 > File "[-]/freqtrade/freqtrade/rpc/telegram.py", line 54, in wrapper return command_handler(self, *args, **kwargs)
 > File "[-]/freqtrade/freqtrade/rpc/telegram.py", line 478, in _forcesell msg = self._rpc_forcesell(trade_id)
 > File "[-]/freqtrade/freqtrade/rpc/rpc.py", line 502, in _rpc_forcesell  _exec_forcesell(trade)
 > File "[-]/freqtrade/freqtrade/rpc/rpc.py", line 479, in _exec_forcesell self._freqtrade.execute_sell(trade, current_rate, SellType.FORCE_SELL)
 > File "[-]/freqtrade/freqtrade/freqtradebot.py", line 1109, in execute_sell amount = self._safe_sell_amount(trade.pair, trade.amount)
 > File "[-]/freqtrade/freqtrade/freqtradebot.py", line 1077, in _safe_sell_amount f"Not enough amount to sell. Trade-amount: {amount}, Wallet: {wallet_amount}")
 > freqtrade.exceptions.DependencyException: Not enough amount to sell. Trade-amount: 171.9992398, Wallet: 1.0000007932831068e-08

(Shortened file path from log entries mine.)

Since this is a trade that's already open and being close, "not enough amount to sell" makes *no* sense unless the bot has lost track of the trade. But as it has an ID and is listed as open both in the bot and on the exchange, that explanation doesn't work either.

## Describe your environment

  * Operating system: Ubuntu 18.04 lts
  * Python Version: 3.6.9
  * CCXT version: 1.30.48
  * Freqtrade Version: 2020.7

**Comment by xmatthias** [comment]
This will need some more info...

* Exchange
* using stoploss on exchange(?)
* what is the status on the exchange (are there open orders for this pair on the exchange) 
* how much does the bot report it owns (/status) 
* how much do you see in the exchange's UI?


Depending on the above, we'll need logs from either the time the bot bought the pair, or when the last stoploss was placed (in case you use stoploss on exchange, and at least one stoploss on exchange was placed in the past).

**Comment by Blackhawke** [comment]
Okay cool. 

Exchange: Kraken  
Stoploss on exchange -- yes. (That was included above, and the "Sell Stop Loss" is shown.)  
Bot reports: 171.9992398
Exchange: Same amount (171.992398)

**Comment by xmatthias** [comment]
Is this the trade you mentioned on slack? 
are there other logs other than the above - like it's trying to sell the trade over and over and over again, spamming the logs?

I suspect the trade doesn't "remember" the stoploss order id - therefore doesn't cancel it - which obviously leaves the assets tied up so it' can't place a new stoploss order.

However, that's only a suspicion - the logs can confirm this - but it'd be the logs from around the time the bot placed the stoploss order (should be available on the kraken webpage).

**Comment by Blackhawke** [comment]
No, this isn't the trade I asked you about on Slack, and no, the bot isn't
continually trying to sell it.

I'm remote today, so I'll get the Kraken logs posted tomorrow.

**Comment by Blackhawke** [comment]
Here's the exchange information (I hope this is what you were looking for):

 > Ledger Entry LPEIID-7I3VW-XGKXBV￼
 > Trade		T7F4XS-P2Y3G-UVBMD7
 > The trade associated with this ledger entry.
 > Order		OYHATR-T7X2H-FBOTBG
 > The order the trade was executed under.
 > Type		Trade
 >
 > Date		08-22-20 00:09:44 +0000

**Comment by xmatthias** [comment]
kindof ... no?

I'd need the freqtrade logs from around the time these trades/orders did happen ... (a bit before - a bit after).
Otherwise, debugging what went wrong within freqtrade will not be possible (as said above - the error only shows the symptom - not what caused it).

**Comment by Blackhawke** [comment]
There is also this. It may or may not be related to the other issue:

 > 2020-08-27 08:04:52,386 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
 > Traceback (most recent call last):
 > File "[-]/freqtrade/freqtrade/exchange/kraken.py", line 86, in stoploss amount=amount, price=stop_price, params=params)
 > File "[-]/freqtrade/.env/lib/python3.6/site-packages/ccxt/kraken.py", line 924, in create_order response = self.privatePostAddOrder(self.extend(request, query))
 > File "[-]/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 463, in inner return entry(_self, **inner_kwargs)
 > File "[-]/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 486, in request return self.fetch2(path, api, method, params, headers, body)
 > File "[-]/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 482, in fetch2 return self.fetch(request['url'], request['method'], request['headers'], request['body'])
 > File [-]/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 604, in fetch   self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "[-]/freqtrade/.env/lib/python3.6/site-packages/ccxt/kraken.py", line 1546, in handle_errors raise InsufficientFunds(self.id + ' ' + body) ccxt.base.errors.InsufficientFunds: kraken {"error":["EOrder:Insufficient funds"]}
 >
 > The above exception was the direct cause of the following exception:
 > 
 > Traceback (most recent call last):
 > File "[-]/freqtrade/freqtrade/freqtradebot.py", line 781, in create_stoploss_order order_types=self.strategy.order_types)
 > File "[-]/freqtrade/freqtrade/exchange/common.py", line 130, in wrapper return f(*args, **kwargs)
 >  File "[-]/freqtrade/freqtrade/exchange/kraken.py", line 94, in stoploss f'Message: {e}') from e
freqtrade.exceptions.ExchangeError: Insufficient funds to create stop-loss sell order on market NANO/USD. Tried to create stoploss with amount 171.9992398 at stoploss 0.770278. Message: kraken {"error":["EOrder:Insufficient funds"]}

The problem is, the stoploss was already created on the exchange, so it shouldn't be trying to do it again:

 > Ledger Entry LXXISW-U3FVC-WD7KTI￼
 > Trade		T7F4XS-P2Y3G-UVBMD7
 > The trade associated with this ledger entry.
 > Order		OYHATR-T7X2H-FBOTBG
 > The order the trade was executed under.
 > Type		Trade
 > 
 > Date		08-22-20 00:09:44 +0000

**Comment by Blackhawke** [comment]
Okay, well crap. I posted the bot's stderr output above. You said what you wanted was on the Kraken Webpage, so I though you wanted the exchange info.

**Comment by xmatthias** [comment]
no, the stderr output is exactly what i'm looking for :) 

now this "insufficient funds" error - if you still have the logs and are able to go all the way back where they started - that's where the interresting part happens (why the bot actually "lost" the order it created).

In the end, what happens is simple - the bot places an order - and then "somehow" loses this order (or thinks the order placement went wrong, and tries to place a new order).
On the kraken UI, you should see *when* this stoploss-order was placed - allowing to search the logs more efficiently ... (that's where the kraken UI comes in - just to get the time of order creation).


The easiest fix for this is to cancel the order on the exchange, allowing the bot to place a new one, but obviously this won't help me solve the problem for the future.

However - this error will most likely fixed in #3682 - which is really a fix for the same problem but on binance (i didn't know and never saw this error on kraken though).

However, since it's unclear what causes this on kraken - it would be nice to have the logs that introduce this state (the "insufficient funds" is just the symptom that the bot "lost" an order ... not the reason it lost that order.

**Comment by Blackhawke** [comment]
Excuse me. Being a dork, I misspoke (misswrote?). I was running the bot off of the wrong command line history and didn't have the `--logfile` set, so everything went to stdout (*not* stderr) and so wasn't recorded. (That's also true of the second post, which was a copy/paste from the terminal output.)

I've since restarted the bot *with* the `--logfile` set, because I'm smart that way. =sigh=

Anyway, the stoploss problem is occurring on the same pair as the forcesell problem, so one way or another, I'll now be able to get logs on that transaction. Sorry for being a dork!

**Comment by xmatthias** [comment]
Keep in mind however that in this case, logs will only be relevant for new trades where this happens - not for this trade (as it lost track already).

As mentioned above - best cancel the order on the exchange and the bot should recover by placing a new order.

**Comment by Blackhawke** [comment]
Okay. Well, given that (we must begin the search for the bug with a new trade), it may be awhile. The only reason I stumbled across the bug in the first place is the trailing stop didn't seem to work. But I'll pick a trade to manually close as soon as I can.

As for closing on the exchange: If you don't mind, let's discuss that for a sec with expansion of this topic in the docs in mind, as I don't find it referenced anywhere, but it should probably be a section in "controling the bot". Assume Trade _xyz_ is open. What is the proceedure for manually closing that trade on the exchange safely, so it doesn't screw up the bot's database? My assumption, based on the message you have it putting out on Telegram, is that you `/stop` the bot, close the trade(s) on the exchange, then `/start` the bot again, and it re-reads the trades from the exchange and cleans up its sqlite records accordingly. Is that correct?

**Comment by xmatthias** [comment]
Your case is not a standard case, but one where the bot "lost" an order for whatever reason.


You still own the assets, but they are tied up in a trade the bot placed but "lost".
That's the simplest case - cancel the existing order on the exchange, and the bot will resume as usual (as i mentioned multiple times above).

**Comment by Blackhawke** [comment]
Let me break this in two for clarity.

**First, my issue:** I understand it's not typical and I also understand tracing the problem has to begin with the new order placed. Which means there's little that can be done about it right now.

**Second, manual trades in general:** Because this is related, and because it's documented so poorly, I raised the issue here, but we can move it to another topic or to Slack if you prefer. When you kill the bot, it pushes the Telegram message about closing trades manually on the exchange. No further information is given. I'd like to fill in that information for others just starting out.

As I find issues like this, what I'm trying to do is address them in the documentation for a new users of while I still *am* a new user of the bot. No doubt, once I'm as familiar with the program as long time user, I too will begin to overlook things that are not well documented for newbs.

**Comment by xmatthias** [comment]
the "closing" topic is a difficult one - as there are many reasons to terminate a bot (e.g. update and immediately restart again).

It's a hint to notify people that the bot still "owns" stuff ... and if there's no plan to restart the bot "soon", it should be handled manually on the exchange (while it's preferrable and simpler to just restart the bot and let it handle the trade).

Rather than document this, we might need to rephrase the notification that's sent out ... as i honestly would not know where / how to document this ...

**Comment by Blackhawke** [comment]
Well, let's have the discussion and maybe that will shed some light on how and where it should be documented.

Let's say hypothetical trade *xyz* is opened by the bot. Then, for whatever reason, the bot is shut down and, while its shutdown, trade *xzy* is closed on the exchange. Then, the bot is restarted. What does the bot do with trade *xyz*? What does the user need to do about trade *xyz*, if anything?

I seem to recall you saying the trade (*xyz*, in this case) would have to be manually removed from the database, but that might have been specific to my situation.

**Comment by xmatthias** [comment]
Since you "Interfered" with the bot's trade - manual intervention will be necessary.
Most likely, that's [deleting the trade](https://www.freqtrade.io/en/latest/sql_cheatsheet/#remove-trade-from-the-database) ...

**Comment by Blackhawke** [comment]
Okay, so the bot does no auditing of its "internal" database on startup. All manual trades are 100% manual.

Can the `/stop` `/start` Telegram commands be used, or does the bot have to be completely killed and restarted?

**Comment by xmatthias** [comment]
well yes - manual trades are manual ...

Detecting "random" changes on the exchange correctly is very difficult - as it can have may flavours - like you could withdraw the assets the bot "owns" -  or sell part of it, sell all of it, buy more, invest more (but want the bot to manage it's own assets) - however the intend is not clear.

It's different if a order the bot placed is filled while it's offline, it will catch up to that when it restarts.

**Comment by Blackhawke** [comment]
Not Tesla overdrive equiped. Got it. 😁

So, to recap: To do a manual trade, `/stop` the bot; do your trade on the exchange; remove the trade from the DB; `/start` the bot.

Correct?

**Comment by xmatthias** [comment]
i don't understand your point and i think you're overcomplicating this.
why would you want to do that?

`/forcesell` will work just fine if you just want to close a trade manually.
you can in theory also just sell the trade manually on the exchange without stopping the bot - as long as you then "tell" the bot by deleting the trade, it'll just generate a few exception logs eventually (depending on timing, not even that).

Also, be careful with wording - a trade in freqtrade is a sequence of buying an asset, managing this asset - and then selling it again - so i think what you mean is to do a manual order.

**Comment by Blackhawke** [comment]
I think you're right. Good point!

What I'm talking about isn't "manual trades". `/forcesell` covers that just fine. 

What I'm talking about is more like "contingency operations". In other words, how to clean up a mess and have the bot take over again cleanly. In my case, it was the the trade that the bot partially lost, so `/forcesell` wouldn't work; but I can think of other situations (power outage, internet outage, computer crash) where such information would be invaluable.

**Comment by xmatthias** [comment]
in 99% of the cases, the bot will resume just fine.

All other cases are edge-cases - which are unique all on their own. As said before, you'rs would've been solved by cancelling the open stoploss on exchange - but this only applies to this particular case. Another case will most likely look different, and therefore have a different solution.

**Comment by Blackhawke** [comment]
So, are you saying the solution I gave above (`/stop` the bot -- or the program -- do what you're going to do on the exchange, cleanup the sqlite, the `/start` the bot) is not a valid way to handle contingencies when a `/forcesell` doesn't (or can't) work? Or is this a caution against wording things too strongly?

**Comment by xmatthias** [comment]
it is a valid way - but doing it is not required in 99% of the cases (including the case we discussed in this issue).

Nothing prevents you from doing it that way - but then that's true for many other things too...

**Comment by Blackhawke** [comment]
Granted! :)

So, I guess the question is, do you feel this is something that should be added to the docs, or not? Personally, with all the caveats we've been discussing, I think it should be, but I'll defer to you on that.

BTW, if there's anything else in the docs you'd like me to work on, I'm more than willing. Not trying to create problems here, just trying to help.

**Comment by xmatthias** [comment]
well everything that you feel is unclear in the docs might be worth improving.
for me, this is difficult to say 

The problem with this particular point here is - the method on HOW to remove it is in the sql cheatsheet (and it's even easier now, with the `/delete` telegram command).
it's the "when" to apply this which is very difficult to describe - as it'll depend on the situation. 

In reality, the only situation you really would want to delete a trade is if you manually sold the asset (maybe by mistake) - or if for some reason, the bot thinks it bought and filled, while in reality it wasn't (never seen that happen in real live though) - or if you `/forcebuy` it and it's a strong looser, and you don't want to mess up your strategies good record by your own stupidity :laughing: 

I'm running the bot now for "quite some time" - and most of the time in multiple instances on multiple exchanges, and i haven't had to touch the database once all of this year for anything other than investigating something that didn't seem right, or to generate some generic metrics i was interrested in.
