### ISSUE TITLE
Bot stopped working suddenly(unable to find out why)

### ISSUE THREAD

**Issue by sanket-k** [freqtrade/freqtrade#3720]
## Describe your environment

  * Operating system: linux - AWS ubuntu
  * Docker version: 2020.07
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
Unable to figure out why the bot suddenly stopped. 
not sure it'll be helpful, but I have used group id, instead of user id for telegram bot, would using group id cause the bot to fail ?
note: the bot had been up for a few months, without any issues.

### Steps to reproduce:

  1. Unable to reproduce.
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
    The bot stopped working suddenly, unable to figure why.
  * What did you expect to happen?
    Bot to work normally.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```

2020-08-23 06:48:44,844 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2020.7', state='RUNNING'
2020-08-23 06:49:44,906 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2020.7', state='RUNNING'
2020-08-23 06:50:44,967 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2020.7', state='RUNNING'
2020-08-23 06:51:45,030 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2020.7', state='RUNNING'
2020-08-23 06:52:45,093 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2020.7', state='RUNNING'
2020-08-23 06:53:45,155 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2020.7', state='RUNNING'
2020-08-23 06:54:45,217 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2020.7', state='RUNNING'
2020-08-23 06:55:45,400 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2020.7', state='RUNNING'
2020-08-23 06:56:45,776 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2020.7', state='RUNNING'
2020-08-23 06:57:46,151 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2020.7', state='RUNNING'
2020-08-23 06:58:46,469 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2020.7', state='RUNNING'
2020-08-23 06:59:46,717 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2020.7', state='RUNNING'
2020-08-23 07:41:05,586 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcc4fca64c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /bot018541548:AAH-x5pL-ljn3ac3TfHi5I8aNSe2Ey2P-TE/getUpdates
2020-08-23 07:54:17,384 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2020.7', state='RUNNING'
  ```

**Comment by xmatthias** [comment]
The provided logs don't indicate that the bot stopped to me - stopping would show a exception log...

The only thing noticeable thing in these logs is that telegram seems to have problems connecting to it's servers (actually that the connection was "broken" - and that it's retrying to reconnect. Since this is the only message from telegram, i assume it was able to reconnect.
Also, technically, telegram runs in it's own thread - so problems with it should not stop the bot main process anyway.

You don't however provide enough details about your environment - are you running on an ec2 instance, or on one of amazons other services?

**Comment by sanket-k** [comment]
thanks for the quick reply :) 
environment -> AWS lightsail instance: 512 MB RAM, 1 vCPU, 20 GB SSD (since my entry and exit rules are very simple, so resource wise it hardly takes 150mb in ram and CPU utilisation is 1-2% most of the time) [i use it mostly for the ease of use and quick connection using ssh]

rite, I was at the same conclusion, as it had logged `2020-08-23 07:54:17,384 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2020.7', state='RUNNING'` before stopping, hence I been trying find out what went wrong and where.

ended up a missing a trade :(, started it after a day or so, when I realised it had stopped, its working fine now. 

and the instance had not stopped, as I had an other cron job running (which seemed to have worked properly)

not sure if these would be helpful:
![image](https://user-images.githubusercontent.com/23406725/91269315-89206880-e794-11ea-98fb-4ea787258f3d.png)
![image](https://user-images.githubusercontent.com/23406725/91269353-9dfcfc00-e794-11ea-95c5-8e0aa9d4b20b.png)
![image](https://user-images.githubusercontent.com/23406725/91269374-a35a4680-e794-11ea-836a-cfc90648bb14.png)

**Comment by xmatthias** [comment]
While freqtrade may work with underpowered machines (like 512MB of ram) - it's not guaranteed nor supported to work that way, as with such low-powered machines, a small memory / cpu spike can cause the system to start killing process (which is most likely what happened).

I never used lightsail - but i assume it's a normal linux system, so the system level logs might have something available (showing what happened at that time ...).

The spike may or may not come from freqtrade - that'll be difficult to determine - but if the system says "out of ressources", then this can have odd, sometimes unpredictable effects to processes.

The only recommendation i can give you - upgrade to something with a bit more juice - i'm yet to experience this on supported configurations (although i have to admit, i sometimes also use 1G machines for freqtrade - which also don't show this problem).

---

Another potential - depending where you're running freqtrade, this might even be a general AWS  problem - as they had an outage of their europe Datacenter yesterday (i know it was the london one ... not sure if other regions were affected, too).

**Comment by sanket-k** [comment]
thats a good suggestion, i'll try and explore the system level logs (might be able to find something), thanks

rite, for the extra juice, AWS facilitates a Burstable performance instances, where we can use 100%+ CPU load at a short bursts of intervals (I think this might be a good way to use it :p)
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-performance-instances.html

hadn't considered that option tbh, i'll try and look into the region (I was hosting in japan).

**Comment by xmatthias** [comment]
Any news on this?
otherwise i'd want to close this - as i doubt that there is anything freqtrade can do to adress this problem...

**Comment by sanket-k** [comment]
hi, yes
I was able to check out the system logs, the issue was as you had suggested, out of resources.
though wasn't able to figure out how it ran out of memory, still trying to identify that part, but it was something other freqtrade i guess, will be closing the issue.

Thanks for the help :)

```
Aug 23 08:08:51 ip-172-26-5-0 kernel: [6467530.700747] Out of memory: Kill process 21954 (freqtrade) score 236 or sacrifice child
Aug 23 08:08:51 ip-172-26-5-0 kernel: [6467530.710245] Killed process 21954 (freqtrade) total-vm:620368kB, anon-rss:115588kB, file-rss:0kB, shmem-rss:0kB
Aug 23 08:08:51 ip-172-26-5-0 kernel: [6467530.757193] oom_reaper: reaped process 21954 (freqtrade), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
Aug 23 08:08:53 ip-172-26-5-0 systemd[1]: snapd.service: Scheduled restart job, restart counter is at 12.
Aug 23 08:08:54 ip-172-26-5-0 snapd[32014]: AppArmor status: apparmor is enabled and all features are available
Aug 23 08:08:54 ip-172-26-5-0 systemd[1]: Stopped Snap Daemon.
Aug 23 08:08:54 ip-172-26-5-0 systemd[1]: Starting Snap Daemon...
```
