### ISSUE TITLE
Multiple Telegram user_id with single bot

### ISSUE THREAD

**Issue by kumkee** [freqtrade/freqtrade#3722]
## Describe your environment
(if applicable)

  * Operating system: Ubuntu 18.04.4 LTS
  * Python Version: 3.6.9 (`python -V`)
  * CCXT version: 1.33.7 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.7 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement
Is it possible to have more than one Telegram user_ids for a single bot?
I've done a quick search through past issues, but didn't manage to see an answer.

*Explain the enhancement you would like*
We are a team of three developing trading strategies and would love to manage the same bot and observe its performance with the Telegram interface.

**Comment by xmatthias** [comment]
It is not possible to use multiple chat_id's for telegram.

According to people on slack it's possible to us a group-chat, add the bot to the group chat, and use the group-chat-id for the bot - but this is something i've never tried, so if you need help with that, best ask on slack so people who use this can jump in and help.

**Comment by kumkee** [comment]
> It is not possible to use multiple chat_id's for telegram.
> 
> According to people on slack it's possible to us a group-chat, add the bot to the group chat, and use the group-chat-id for the bot - but this is something i've never tried, so if you need help with that, best ask on slack so people who use this can jump in and help.

Thanks for the hint.
We will experiment group-chat option. If that fails, we will come onto Slack and seek help.

**Comment by xmatthias** [comment]
That sounds great - maybe consider adding the working option to the corresponding telegram documentation page ... 😄

**Comment by kumkee** [comment]
The solution is found on this [stackoverflow answer](https://stackoverflow.com/a/38388851).
Please note that I repeated Step 2 twice before successfully getting the chat id
