### ISSUE TITLE
Dry run trading in between candles

### ISSUE THREAD

**Issue by zlac116** [freqtrade/freqtrade#3723]
Hi Team - I'm trying to understand how the bot trades using new candles. My dry-run is running using 15m candles so I assumed that it would only trade/react every 15m. However, it seems to trade outside / in between this timeframe. I have searched the freqtrade configs documentation to find the setting that will allow my bot to only trade on new candles (i.e. every 15m) but I was unable to clearly understand how to do this.

Could you please help?

Thanks
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
the setting is called `process_only_new_candles`.

While it's main purpose is to reduce load on the system by analyzing the strategy only once per candle, it'll also have the side-effect of not trading between candles **for the most part**.

In general, it will however depend on your strategy - if you only rely on technical indicators, buys should happen at the beginning of candles only (unless a trade is sold mid-candle), as the buy-signal is available throughout the whole 15m candle, and is acted as soon as it's available.

ROI / stoploss are always evaluated at every iteration - so these trades will always happen "whenever" - not tied to the timeframe at all.

Obviusly, if ROI / stoploss frees up a trade-slot (max_open_trades was reached before this) - then it'll act on the still available buy signal.

**Comment by zlac116** [comment]
Thanks. If process_only_new_candles is set to False (default), how often is populate_indicators analysed and which config can control this?

**Comment by zlac116** [comment]
Also, if I were to replicate a backtest in a dry/live run, which uses 15m candles, presumably I would need to set `process_only_new_candles` to True?

**Comment by zlac116** [comment]
I have found a good strategy, which seems to perform remarkably well in most/if not all periods in a backtest environment. However, my issue is deploying it to a dry/live environment or replicating the backtest envt in a dry run. The strategy seems to perform very far from my backtest results in a dry run. Do you have any suggestions on how I can replicate backtest environment in a dry run, in terms of candle refresh period, etc?
Thanks

**Comment by xmatthias** [comment]
candle refresh period is usually not the "breaking factor" on a strategy.
with `process_only_new_candles=False` - the strategy is analyzed once every iteration (so ~once every 5s on default settings).
However, if the strategy is done without using "current" market data (which is not available in backtesting anyway) - then it will return the same thing on every call for the duration of the candle - so if it's analyzed once, or 200 times, will not matter, as the result is deterministic and remains static throughout.


Usually, when backtesting performs well, and dry-run does not - there is some subtle error in the strategy, where backtesting uses data it should not use (data from the future) to analyze the strategy.

We've got a "common" list of these in the documentation - but there can be other things too (we try to extend this list as we  discover more problems ...).

**Comment by zlac116** [comment]
Thanks for this response. I will take a look at this common list, in the documentation. In the meantime, if you don't mind, below is my `populate_indicators`, `populate_buy_trend` and `populate_sell_trend` methods. Should work in the same way as using bollinger bands but instead of assuming that price reverts to the long-run mean, this assumes that price reverts to the trend.

    def populate_indicators(self, dataframe: DataFrame) -> DataFrame:

        # RSI
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=3)

        # MACD
        macd = ta.MACD(dataframe, fastperiod=12, slowperiod=26, signalperiod=1)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']

        # Linear Regression Line
        dataframe['lr_middle'] = ta.LINEARREG(dataframe['close'], timeperiod=25)
        dataframe['atr'] = ta.ATR(dataframe,timeperiod=25)
        dataframe['lr_lower1.0'] = dataframe['lr_middle'] - dataframe['atr'] * 1
        dataframe['lr_lower0.5'] = dataframe['lr_middle'] - dataframe['atr'] * 0.5

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['macd'] < dataframe['macdsignal']) &
                (dataframe['close'] < dataframe['lr_lower1.0']) &
                (dataframe['volume'] > 0)
            ),
            'buy'] = 1
        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['rsi'] > 42) &
                (dataframe['close'] > dataframe['lr_lower0.5']) &
                (dataframe['volume'] > 0)
            ),
            'sell'] = 1
        return dataframe

**Comment by zlac116** [comment]
I had a look at the common mistakes within the strategy development section but I couldn't find anything specific that may cause a subtle error.
I did however find a bug in my code within the MACD settings. The `signalperiod` is set to 1, which doesn't make much sense considering you need at least 2 periods to compute an EMA of the MACD line. However, it would be interesting to find out what is exactly being computed with this incorrect setting as it seems to result in exceedingly good backtest results. If I correct this setting to 9 (required), my backtest results are ok and more in line with my dry runs.

**Comment by xmatthias** [comment]
I'm not a ta-lib expert - best ask this question in the [ta-lib python wrapper](https://github.com/mrjbq7/ta-lib/) repository (i don't think there is support for the underlying C part though - but maybe you can get some answers from there).

**Comment by zlac116** [comment]
Thanks, will do - appreciate your time on this!

**Comment by zlac116** [comment]
Just found a similar qu in their issues section. As you mentioned, there is no longer much support for this part but I've added to the thread...I guess there's no harm!

https://github.com/mrjbq7/ta-lib/issues/335

**Comment by xmatthias** [comment]
I'll close this here as i think the problem itself has been solved.

Would be great if you could let us know if there is some outcome from your question in the ta-lib repository.

**Comment by zlac116** [comment]
Sure will do. 😊
