### ISSUE TITLE
How to set percentage for different pairs

### ISSUE THREAD

**Issue by idew7** [freqtrade/freqtrade#3725]
Hello,

I would need to use for example 60% out of my whole account balance for BTC/USDT Pair,
20% out of my whole account balance for ETH/USDT pair
other 20% out of my whole account balance for EOS/USDT pair

Total 100% account balance, and every time bot gets profit it will use earned money for the trades

*Using 1 Bot

I couldn't find the way to do it, hope someone knows and helps.

**Comment by xmatthias** [comment]
You can't.
You can use dynamic stakes by setting stake_amount to unlimited, and letting the bot split your available balance between trades - however the split will be even between all pairs - and it's currently impossible to define this split yourself.

**Comment by kumkee** [comment]
> You can't.
> You can use dynamic stakes by setting stake_amount to unlimited, and letting the bot split your available balance between trades (basically `availablebalance / max_open_trades` ) - however the split will be even between all pairs - and it's currently impossible to define this split yourself.

I'd love to see as well this as a new feature in the future.

**Comment by kumkee** [comment]
> > You can't.
> > You can use dynamic stakes by setting stake_amount to unlimited, and letting the bot split your available balance between trades (basically `availablebalance / max_open_trades` ) - however the split will be even between all pairs - and it's currently impossible to define this split yourself.
> 
> I'd love to see as well this as a new feature in the future.

If I want to contribute and make this feature a reality, which part of the codebase of the project should I dive into?

**Comment by xmatthias** [comment]
@kumkee thanks for your offer. I would strongly suggest to not start with this, but with one of the issues labeled as "good first issue" to avoid frustration - as this might be a more complicated change.

**Comment by kumkee** [comment]
> @kumkee thanks for your offer. I would strongly suggest to not start with this, but with one of the issues labeled as "good first issue" to avoid frustration - as this might be a more complicated change.

Would it be easier to implement multiple staking slots for one trading pair?

**Comment by xmatthias** [comment]
As mentioned above - I would recommend to get familiar with the bot's codebase and structure by starting with something simple (usually labeled with good first issue).

You may also want to look at issues labeled "RPC" - as these usually only touch part of the codebase, and are therefure usually not as complex as other things.

Everything involving the trading-mechanics directly should be considered fairly advanced, and we will require extensive tests (which is something people usually struggle at the beginning).

**Comment by kumkee** [comment]
> Everything involving the trading-mechanics directly (or adding new methods to the strategy) should be considered fairly advanced, and we will require extensive tests (which is something people usually struggle at the beginning until there is a certain familiarity with the codebase).

That completely makes sense to me. Trading part is more vital to the users as well.

**Comment by xmatthias** [comment]
just to be clear - i'm not saying it's not possible - just that it'll be complex eventually - which will lead to frustrations - which should not happe when starting to contribute to a project ... :smile:

**Comment by kumkee** [comment]
@idew7 @xmatthias 
People have been already working on multiple orders for single pair on [this and its related issues](https://github.com/freqtrade/freqtrade/issues/3702). 
Once that feature is implemented, percentage staking can be just done within config or strategy definition.
As a result, I suggest we close this issue.
