### ISSUE TITLE
Getting considered pairs

### ISSUE THREAD

**Issue by kumkee** [freqtrade/freqtrade#3726]
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

I want to get the list of currently considered pairs within the strategy, like DataProvider.current_whitelist(), but for static pairs as well. I've tried self.dp.available_pairs in my populate_indicators, but it always returns an empty list to me.
Updated: or is it a way to get config settings in a strategy?

**Comment by xmatthias** [comment]
it's unclear what you mean with "considered pairs".

`current_whitelist()` will return the current whitelist (list of all pairs that are currently considered for buying). If youre using a static, or dynamic whitelist does not matter.

**Comment by kumkee** [comment]
> `current_whitelist()` will return the current whitelist (list of all pairs that are currently considered for buying). If youre using a static, or dynamic whitelist does not matter.

I get OperationalException calling current_whitelist() during backtesting.
```
ipdb> self.dp.current_whitelist()
*** freqtrade.exceptions.OperationalException: Dataprovider was not initialized with a pairlist provider.
```

**Comment by xmatthias** [comment]
yeah, seems like it's not available during backtesting.
will have a look at that.


You should be able to get most of the configuration from within a strategy by using `self.config` - so i your case, this would be `self.config.get('ma_open_trades')`.

**Comment by kumkee** [comment]
> You should be able to get most of the configuration from within a strategy by using `self.config` - so i your case, this would be `self.config.get('ma_open_trades')`.

Just tried, and it works even under backtesting. Thanks! This doesn't seem to be documented in the documentation, though. 
Shall we remain this open until it is documented?
