### ISSUE TITLE
Summary Metrics does not appear on backtesting reporting

### ISSUE THREAD

**Issue by silvavn** [freqtrade/freqtrade#3728]
## Describe your environment
  * Operating system: Windows
  * Python Version: 3.7 
  * CCXT version: 1.32.7 
  * Freqtrade Version: 2020.7
  
## Your question

In [this page](https://www.freqtrade.io/en/latest/backtesting/) you show that there is a "SUMMARY METRICS" table in reporting. However, after several runs, I could not figure how to show it using docker. Is this still supported or is the documentation outdated? If supported, how can I make it appear?

**Comment by xmatthias** [comment]
Summary metrics is available on the develop branch, but is not in any release yet.

You can (and should) switch to the documentation version matching your Version by clicking on the floating box in the bottom right corner [example link for your version](https://www.freqtrade.io/en/2020.7/backtesting/).

**Comment by xmatthias** [comment]
Assuming this as explained by the above.

Feel free to comment or reopen if it's still unclear.
