### ISSUE TITLE
Data discrepancy on Telegram

### ISSUE THREAD

**Issue by sinak7** [freqtrade/freqtrade#3729]
### Have you searched for similar issues before posting it? 
Yes

## Describe your environment

* Operating system: Raspbian 10
* Python Version: Python 2.7.16
* CCXT version: 1.32.88
* Freqtrade Version: develop-3670be5d

## Describe the problem:

Hello,

I run the /daily command on Telegram and I got the table with the sum of the profits per day. When I tried to cross-check the accuracy of the data (by adding by my own all the profits/loss per day), I saw that the data did not match.

Is there something I'm missing?

**Comment by xmatthias** [comment]
There's a ton of things this wil depend on - and with the information you provided, it's impossible to say anything in particular - so the below is based on assumptions only.

The most likely cause are fees. 
Assuming binance and BNB fees (the most common scenario):

your exchange may show you 10 USD profit on the exchange - but you need to subtract fees still - so while your USD balacne did raise by 10 USD - your overal account balance was only rasising by 9.8 USD (or something similar).

**Comment by sinak7** [comment]
Thank you xatthias for your immediate response!

The discrepancies I observed were 30-50% off.

But your comment got me thinking so I exported the trade history report from Binance and my mistake was that I was cross-checking day by day instead of a longer period. So when I assessed the data of a week I realized that the overall profit was as expected. 

Thanks!

**Comment by xmatthias** [comment]
well - freqtrade's "daily" relates to the trade-close (when the profit / loss is realized) - so if a trade is opened at 23:00 - and closed at 1:00, it'll count towards the 2nd day (when the trade got closed).
