### ISSUE TITLE
Feature: Add coins

### ISSUE THREAD

**Issue by robmoggach** [freqtrade/freqtrade#373]
It'd be great to be able to add existing coins to the queue to be traded via the telegram api.

Eg.

    /add DOGE 4000@0.00000093

Triggering the sell would obviously be based on user configuration and documentation should caveat accordingly.

**Comment by xmatthias** [comment]
would you immagine this feature to be something like a `/forcebuy` ... or adding the coin to whitelist?

**Comment by shusso** [comment]
for now I don't think there is anyone to implement this. Closing for now.
