### ISSUE TITLE
Hyperopt gives me a trailing_stop_positive_offset at 1.7 but backtesting says it can't be greather than 1

### ISSUE THREAD

**Issue by bigchakalaka** [freqtrade/freqtrade#3743]
## Describe your environment

  * Operating system: Linux 18.04 LTS
  * Python Version: 3.8.2
  * CCXT version: 1.33.52
  * Freqtrade Version: Freqtrade develop

  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
Hello,
it's all in the title, after running hyperopt on a strategy it gives me this :
   # Stoploss:
    stoploss = -0.47502

    # Trailing stop:
    trailing_params = {
        'trailing_only_offset_is_reached': True,
        'trailing_stop': True,
        'trailing_stop_positive': 0.60467,
        'trailing_stop_positive_offset': 1.50726
    }

However when I want to try it in backtesting it says that I cannot use a trailing_stop_positive_offset greater than the maximum of 1

2020-09-01 22:56:00,756 - freqtrade.configuration.config_validation - CRITICAL - Invalid configuration. See config.json.example. Reason: 1.50726 is greater than the maximum of 1

Failed validating 'maximum' in schema['properties']['trailing_stop_positive_offset']:
    {'maximum': 1, 'minimum': 0, 'type': 'number'}

On instance['trailing_stop_positive_offset']:
    1.50726

Any idea why?
Thank you!

**Comment by xmatthias** [comment]
well what does your hyperopt file look like?

Have you got the method `trailing_space()`  in your hyperopt file?

**Comment by bigchakalaka** [comment]
Hi xmatthias, thank you for your answer. Here is my hyperopt file below. Yes I have trailing_space().

thank you

# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement

# --- Do not remove these libs ---
from functools import reduce
from typing import Any, Callable, Dict, List

import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame
from skopt.space import Categorical, Dimension, Integer, Real  # noqa

from freqtrade.optimize.hyperopt_interface import IHyperOpt

# --------------------------------
# Add your lib to import here
import talib.abstract as ta  # noqa
import freqtrade.vendor.qtpylib.indicators as qtpylib


class Strat1_OPT3(IHyperOpt):
 
    @staticmethod
    def populate_indicators(dataframe: DataFrame, metadata: dict) -> DataFrame:


        dataframe['rsi'] = ta.RSI(dataframe)
        dataframe['sell-rsi'] = ta.RSI(dataframe)

        # Bollinger bands
        bollinger1 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=1)
        dataframe['bb_lowerband1'] = bollinger1['lower']
        dataframe['bb_upperband1'] = bollinger1['upper']
        dataframe['bb_middleband1'] = bollinger1['mid']

        bollinger2 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband2'] = bollinger2['lower']
        dataframe['bb_upperband2'] = bollinger2['upper']
        dataframe['bb_middleband2'] = bollinger2['mid']

        bollinger3 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=3)
        dataframe['bb_lowerband3'] = bollinger3['lower']
        dataframe['bb_upperband3'] = bollinger3['upper']
        dataframe['bb_middleband3'] = bollinger3['mid']

        bollinger4 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=4)
        dataframe['bb_lowerband4'] = bollinger4['lower']
        dataframe['bb_upperband4'] = bollinger4['upper']
        dataframe['bb_middleband4'] = bollinger4['mid']

        return dataframe

    @staticmethod
    def buy_strategy_generator(params: Dict[str, Any]) -> Callable:
        """
        Define the buy strategy parameters to be used by hyperopt
        """
        def populate_buy_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Buy strategy Hyperopt will build and use
            """
            conditions = []
            # GUARDS AND TRENDS
            if 'rsi-enabled' in params and params['rsi-enabled']:
                conditions.append(dataframe['rsi'] > params['rsi-value'])

            # TRIGGERS
            if 'trigger' in params:
                if params['trigger'] == 'bb_lower1':
                    conditions.append(dataframe['close'] < dataframe['bb_lowerband1'])
                if params['trigger'] == 'bb_lower2':
                    conditions.append(dataframe['close'] < dataframe['bb_lowerband2'])
                if params['trigger'] == 'bb_lower3':
                    conditions.append(dataframe['close'] < dataframe['bb_lowerband3'])
                if params['trigger'] == 'bb_lower4':
                    conditions.append(dataframe['close'] < dataframe['bb_lowerband4'])
                if params['trigger'] == 'bb_middle1':
                    conditions.append(dataframe['close'] < dataframe['bb_middleband1'])
                if params['trigger'] == 'bb_middle2':
                    conditions.append(dataframe['close'] < dataframe['bb_middleband2'])
                if params['trigger'] == 'bb_middle3':
                    conditions.append(dataframe['close'] < dataframe['bb_middleband3'])
                if params['trigger'] == 'bb_middle4':
                    conditions.append(dataframe['close'] < dataframe['bb_middleband4'])
                if params['trigger'] == 'bb_upper1':
                    conditions.append(dataframe['close'] < dataframe['bb_upperband1'])
                if params['trigger'] == 'bb_upper2':
                    conditions.append(dataframe['close'] < dataframe['bb_upperband2'])
                if params['trigger'] == 'bb_upper3':
                    conditions.append(dataframe['close'] < dataframe['bb_upperband3'])
                if params['trigger'] == 'bb_upper4':
                    conditions.append(dataframe['close'] < dataframe['bb_upperband4'])

            # Check that volume is not 0
            conditions.append(dataframe['volume'] > 0)

            if conditions:
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'buy'] = 1

            return dataframe

        return populate_buy_trend

    @staticmethod
    def indicator_space() -> List[Dimension]:

        return [
            Integer(5, 50, name='rsi-value'),
            Categorical([True, False], name='rsi-enabled'),
            Categorical(['bb_lower1','bb_lower2','bb_lower3','bb_lower4'], name='trigger')
        ]

    @staticmethod
    def sell_strategy_generator(params: Dict[str, Any]) -> Callable:
        """
        Define the sell strategy parameters to be used by hyperopt
        """
        def populate_sell_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:

            # print(params)
            conditions = []
            # GUARDS AND TRENDS
            if 'sell-rsi-enabled' in params and params['sell-rsi-enabled']:
                conditions.append(dataframe['rsi'] > params['sell-rsi-value'])

            # TRIGGERS
            if 'sell-trigger' in params:
                if params['sell-trigger'] == 'sell-bb_lower1':
                    conditions.append(dataframe['close'] > dataframe['bb_lowerband1'])
                if params['sell-trigger'] == 'sell-bb_middle1':
                    conditions.append(dataframe['close'] > dataframe['bb_middleband1'])
                if params['sell-trigger'] == 'sell-bb_upper1':
                    conditions.append(dataframe['close'] > dataframe['bb_upperband1'])
                if params['sell-trigger'] == 'sell-bb_lower2':
                    conditions.append(dataframe['close'] > dataframe['bb_lowerband2'])
                if params['sell-trigger'] == 'sell-bb_middle2':
                    conditions.append(dataframe['close'] > dataframe['bb_middleband2'])
                if params['sell-trigger'] == 'sell-bb_upper2':
                    conditions.append(dataframe['close'] > dataframe['bb_upperband2'])
                if params['sell-trigger'] == 'sell-bb_lower3':
                    conditions.append(dataframe['close'] > dataframe['bb_lowerband3'])
                if params['sell-trigger'] == 'sell-bb_middle3':
                    conditions.append(dataframe['close'] > dataframe['bb_middleband3'])
                if params['sell-trigger'] == 'sell-bb_upper3':
                    conditions.append(dataframe['close'] > dataframe['bb_upperband3'])
                if params['sell-trigger'] == 'sell-bb_lower4':
                    conditions.append(dataframe['close'] > dataframe['bb_lowerband4'])
                if params['sell-trigger'] == 'sell-bb_middle4':
                    conditions.append(dataframe['close'] > dataframe['bb_middleband4'])
                if params['sell-trigger'] == 'sell-bb_upper4':
                    conditions.append(dataframe['close'] > dataframe['bb_upperband4'])


            if conditions:
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'sell'] = 1

            return dataframe

        return populate_sell_trend

    @staticmethod
    def sell_indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching sell strategy parameters
        """
        return [
            Integer(30, 100, name='sell-rsi-value'),
            Categorical([True, False], name='sell-rsi-enabled'),
            Categorical(['sell-bb_lower1',
                         'sell-bb_middle1',
                         'sell-bb_upper1'], name='sell-trigger')
        ]

    @staticmethod
    def generate_roi_table(params: Dict) -> Dict[int, float]:
        """
        Generate the ROI table that will be used by Hyperopt

        This implementation generates the default legacy Freqtrade ROI tables.

        Change it if you need different number of steps in the generated
        ROI tables or other structure of the ROI tables.

        Please keep it aligned with parameters in the 'roi' optimization
        hyperspace defined by the roi_space method.
        """
        roi_table = {}
        roi_table[0] = params['roi_p1'] + params['roi_p2'] + params['roi_p3']
        roi_table[params['roi_t3']] = params['roi_p1'] + params['roi_p2']
        roi_table[params['roi_t3'] + params['roi_t2']] = params['roi_p1']
        roi_table[params['roi_t3'] + params['roi_t2'] + params['roi_t1']] = 0

        return roi_table

    @staticmethod
    def roi_space() -> List[Dimension]:
        """
        Values to search for each ROI steps

        Override it if you need some different ranges for the parameters in the
        'roi' optimization hyperspace.

        Please keep it aligned with the implementation of the
        generate_roi_table method.
        """
        return [
            Integer(10, 120, name='roi_t1'),
            Integer(10, 60, name='roi_t2'),
            Integer(10, 40, name='roi_t3'),
            Real(0.01, 0.04, name='roi_p1'),
            Real(0.01, 0.07, name='roi_p2'),
            Real(0.01, 0.20, name='roi_p3'),
        ]

    @staticmethod
    def stoploss_space() -> List[Dimension]:
        """
        Stoploss Value to search

        Override it if you need some different range for the parameter in the
        'stoploss' optimization hyperspace.
        """
        return [
            Real(-0.5, -0.02, name='stoploss'),
        ]

    @staticmethod
    def trailing_space() -> List[Dimension]:
        """
        Create a trailing stoploss space.

        You may override it in your custom Hyperopt class.
        """
        return [
            # It was decided to always set trailing_stop is to True if the 'trailing' hyperspace
            # is used. Otherwise hyperopt will vary other parameters that won't have effect if
            # trailing_stop is set False.
            # This parameter is included into the hyperspace dimensions rather than assigning
            # it explicitly in the code in order to have it printed in the results along with
            # other 'trailing' hyperspace parameters.
            Categorical([True], name='trailing_stop'),

            Real(0.01, 1, name='trailing_stop_positive'),

            Real(0.01, 1, name='trailing_stop_positive_offset_p1'),

            Categorical([True, False], name='trailing_only_offset_is_reached'),
        ]

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (

                ((dataframe["close"]) < (dataframe['bb_lowerband3'])) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the sell signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                ((dataframe["close"]) > (dataframe['bb_lowerband1']))
            ),
            'sell'] = 1
        return dataframe

**Comment by xmatthias** [comment]
Well if you think about what your results mean, you'll also notice that your search-space is insane.

You're telling the bot to trail by 60% once it reaches 150% profit.
So the first trailing stop you're setting is set to a profit of 90% - but you're giving away 60% of that profit.

Now letalone that this profit is insane for one trade - it tells me that your hyperopt result will have one of 2 problems:
* it doesn't really use trailing stop but sell-signal - so values for trailing stop are irrelevat
* it does use trailing stop - but only did one trade where these values accidentally make sense (but the bot will most likely never trade again)

---

stoploss_space / trailing_space should only be in your hyperopt file if you really need them different from the defaults (which i don't think anyone will ever need unles you want to reduce the space).

the defaults we provide optimize for more realistic values (between 0.01 and 0.35 for trailing - and between 0.001 and 0.1 for the positive offset on top of the trailing value).

This will also make sure that offsets will stay within the defined parameter boundaries.

**Comment by bigchakalaka** [comment]
hi, thanks a lot for the answer i'm pretty new to this, it gives me a lot of information.

So if I understand correctly, I shouldn't try to optimize for the trailing at first?

**Comment by xmatthias** [comment]
That's a discussion point - i like to optimize spaces one by one, others like to optimize "everything" at once ...
Results will vary, and both can bring you great results.

You should however try to limit each space to something reasonable - a trailing stop of 60% will most likely never fire ... (and if because at 40% profits you grew impatient and forcesold) 😆

**Comment by bigchakalaka** [comment]
thanks a lot!
Another quick question, sometimes hyperopt says rsi-enabled false but gives me a value let's say 34. Does it mean that I should use it but if I decide to use it, the best value would be 34?

**Comment by xmatthias** [comment]
no, unfortunately hyperopt does not provide hirarchical spaces - so it'll always try to change "all" values in the search space - even if they are disabled and not used (hyperopt does not know this, and we have no way of telling it).

If the value is disabled, the resulting 34 is irrelevant, as it hasn't been used.

**Comment by xmatthias** [comment]
going to close this as the question was answered.

Feel free to comment / reopen if you still have questions regarding the initial issue.
