### ISSUE TITLE
PricePairList

### ISSUE THREAD

**Issue by screwfaze** [freqtrade/freqtrade#3746]
## Describe your environment
(if applicable)

  * Operating system: ____Docker
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (develop-38c52c7e)

## Describe the enhancement
List pairs by Price
*Explain the enhancement you would like*
I would like to request ability to pair list by price similar to how its done by volume.

Thanks

**Comment by xmatthias** [comment]
We have [PriceFilter](https://www.freqtrade.io/en/latest/configuration/#pricefilter) - which allows you to specify both a lower and upper limit, so i guess this is covered already.

If not, please describe in detail what your idea for this is.

**Comment by xmatthias** [comment]
I'll assume that PriceFilter will suffice this need.

Let me know if that's not the case and then please explain this in more detail.
