### ISSUE TITLE
Pairlist handlers and Whitelist

### ISSUE THREAD

**Issue by polakenfold** [freqtrade/freqtrade#3748]
firstq on git. From Argentina
 when using diferent pairlist handlers, i also want to doit just with the pairs in the whitelist, how does this works?
also want to try the whiteIist AND the other pairs in the exchange
 Thanks.

**Comment by xmatthias** [comment]
you have to pick - either you use StaticPairlist as first handler, which uses only pairs in pair_whitelist.

Alternatively, you can use VolumePairlist as first handler, so it'll select pairs by volume.
Combining the two is not possible - you need to pick one of the 2 methods.

**Comment by polakenfold** [comment]
Thats what i thougt...
Thanks
