### ISSUE TITLE
What does the timeperiod refer to in the strategies.

### ISSUE THREAD

**Issue by devshaaran** [freqtrade/freqtrade#3749]
## Your question

1) Very sorry if you find this question lame, I'm confused about how the timeperiod is quantified in the strategies.

`dataframe['rsi'] = ta.RSI(dataframe, timeperiod=20)` 

Is it based on the `ticker_interval` or does it always denote days?

2) Yet another question, what does close mean in this part of the code, the markets never close right?

`(dataframe['close'] < dataframe['bb_lowerband'])`

**Comment by xmatthias** [comment]
a dataframe gives you candlestick data (one candle per row).
One candle consists of a date (open date of the candle) - an open price, a high and low price, and a close price (at the end of the candle). 

[some info](https://www.investopedia.com/terms/c/candlestick.asp).

---

timeperiod is usually meant to be taken as candles - so a timeperiod of 20 would be 20 hours in a 1h chart, or 20 days in a 1d chart).
However, this is just a "usually" - and details can very depending on the indicator / indicator library you're using.

**Comment by xmatthias** [comment]
I'll assume this as answered and will close it.

Feel free to comment below / reopen the issue should this still be unclear.
