### ISSUE TITLE
Trouble with capturing output of hyperopt-show 

### ISSUE THREAD

**Issue by ziegi** [freqtrade/freqtrade#3750]
## Describe your environment

  * Operating system:  ubuntu 20.04.1
  * Python Version:  3.8.2
  * CCXT version:  1.33.72
  * Freqtrade Version: develop-8c9297e1
  
## Your question

This is weird, so I post it as a question rather than a bug, maybe I am just blind...

* I try to capture the output of hyperopt-show, i have done this a year ago and everything was fine, but now it seems impossible to capture stdout.

`freqtrade hyperopt-show -v -n -1 --best --profitable --no-header `  
is working fine and shows 
```2020-09-07 08:45:03,798 - freqtrade.loggers - INFO - Verbosity set to 1
2020-09-07 08:45:03,798 - freqtrade.configuration.configuration - INFO - Using user-data directory: /data/dokumente/projekte/cryptocurrencies/freqtrade/user_data ...
2020-09-07 08:45:03,799 - freqtrade.configuration.configuration - INFO - Using data directory: /data/dokumente/projekte/cryptocurrencies/freqtrade/user_data/data ...
2020-09-07 08:45:03,799 - freqtrade.configuration.configuration - INFO - Parameter -n/--index detected: -1
2020-09-07 08:45:03,799 - freqtrade.configuration.configuration - INFO - Parameter --best detected: True
2020-09-07 08:45:03,799 - freqtrade.configuration.configuration - INFO - Parameter --profitable detected: True
2020-09-07 08:45:03,799 - freqtrade.configuration.configuration - INFO - Parameter --no-header detected: True
2020-09-07 08:45:03,799 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-09-07 08:45:03,803 - freqtrade.optimize.hyperopt - INFO - Reading epochs from '/data/dokumente/projekte/cryptocurrencies/freqtrade/user_data/hyperopt_results/hyperopt_results.pickle'
2020-09-07 08:45:03,873 - freqtrade.optimize.hyperopt - INFO - Loaded 319 previous evaluations from disk.
2020-09-07 08:45:03,874 - freqtrade.commands.hyperopt_commands - INFO - 7 best profitable epochs found.

    # Buy hyperspace params:
    buy_params = {
     'bb_lowerband_factor-buy-value': 1.0591, 'rsi-buy_value': 34
    }

    # Sell hyperspace params:
    sell_params = {
     'rsi-sell_value': 76
    }
```
but trying to capture it to files 
`freqtrade hyperopt-show -v -n -1 --best --profitable --no-header 1>stdout.txt 2>stderr.txt`
shows me the logs (all lines beginning with Timestamp) in stderr.txt but stdout.txt is empty
I expected the result text (Buy hperspace params ...) to show up in stdout.txt or at least in one of the two files

piping is also not working:
`freqtrade hyperopt-show -v -n -1 --best --profitable --no-header | less`
shows logs on stderr in terminal console but nothing in less <- I expected to see the result text in less
`freqtrade hyperopt-show -v -n -1 --best --profitable --no-header 2>&1 | less`
shows nothing in terminal console but only logs in less <- I expected to also see the result text in less
`freqtrade hyperopt-show -v -n -1 --best --profitable --no-header 1>&2 | less`
shows all output, logs and result text on stderr in terminal console and nothing in less <- this is what i expected

So it seems that stdout is only visible in the terminal but can not be captured, this leaves me with no clue.
Any help appreciated.
Torsten

**Comment by xmatthias** [comment]
It's interresting indeed ... 

It seems to be related to the following 2 lines - which DO some odd things to stdout/stderr...

https://github.com/freqtrade/freqtrade/blob/8c9297e1f0effeccd5490652f83b91a0a3105507/freqtrade/optimize/hyperopt.py#L48-L49


However, i remember this worked before (i explicitly tested for this when we added the progressbar) - so i guess some update to progressbar might have broken this.

**Comment by xmatthias** [comment]
For the time beeing, i've been able to create a very minimalistic example demonstrating the problem and opened an issue with the progressbar library: https://github.com/WoLpH/python-progressbar/issues/235

Now this won't necessarily help us here very quickly - but it demonstrates that it's "somehow" an incompatibility between 3 libraries (python-progressbar, ccxt and pandas) - and "one" of the 2 latter libraries will do "something" to stdout causing this issue.

So far, i'm however left blank as to what could cause this (therefore the issue i opened).

**Comment by ziegi** [comment]
While I see that a progress bar is useful for the hyperopt runs.
I do not see its necessity for the hyperopt-list and hyperopt-show commands.
Wouldn't it be possible to remove the progress bar from these parts ?

**Comment by xmatthias** [comment]
it's not explicitly enabled - but it has to be enabled in this way to work correctly.
Not importing anything from hyperopt for list / show methods would require a major refactor.

it's for sure possible, but please understand that this issue, while technically interresting, is quite low on a priority list, as it's a inconvenience at best.

**Comment by xmatthias** [comment]
@ziegi upgrading progressbar2 will solve this. Apparently there was some odd problem (i did not fully understand yet) ... but it's solved with the new upgrade - which i'll merge as soon as CI finishes.
