### ISSUE TITLE
handling of startup period

### ISSUE THREAD

**Issue by orehunt** [freqtrade/freqtrade#3754]
## Describe your environment

  * Operating system: ____
  * Python Version: Python 3.8.0 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop-4c349342
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

- exchange:
 binance
- timerange: 
20190301-20190501
- pairlist: 
BTC/USDT,ETH/USDT,XMR/USDT
- startup_period: 
anything >0 like 20
- run a backtest

### Observed Results:

  * What happened?
XMR/USDT is not trimmed
  * What did you expect to happen?
all pairs to get clipped by startup period
### Relevant code exceptions or logs

Startup period is trimmed by reducing the timerange that includes all the pairs by the required length
the the timerange is made of the union, not the intersection, so trimming by date on data where that period is missing won't trim anything.
I just make sure that the length of the df after the trim by timerange is at least short of the `required_startup` 

Rare case: after that adjustment a df can be left empty, so I was removing those because some operations might error out if applied on an empty df.

During optimization, if you are generating indicators within pop buy/sell you have to account for startup yourself. 

To fix for all the cases maybe do not add the required_startup to the timerange trim here:
https://github.com/freqtrade/freqtrade/blob/4c34934258457ffeb53f57c187e4639091c8966b/freqtrade/optimize/backtesting.py#L146

instead exclude the first rows by index right before executing the 
backtest (so within the backtest function), maybe here
https://github.com/freqtrade/freqtrade/blob/4c34934258457ffeb53f57c187e4639091c8966b/freqtrade/optimize/backtesting.py#L314

**Comment by xmatthias** [comment]
It's unclear what did happen from the above, as it's missing crucial information (like logs!).

First of all - Please include the full log of the run. Log messages often include a lot of useful information - and are almost always required to diagnose anything.


For this particular case, it's also important to know, from when to when  (start / end date) do you have data for each of the pairs available.

**Comment by xmatthias** [comment]
Thanks for reporting, i've now been able to understand and replicate what you intend to explain above - and have fixed it in #4628.
