### ISSUE TITLE
VSCode Remote-Containers for dev

### ISSUE THREAD

**Issue by theaidem** [freqtrade/freqtrade#3758]
## Describe the enhancement

Could you provide the .devcontainer with full installed dependencies for development and strategy customization?

Thanks!

**Comment by xmatthias** [comment]
I'm more than happy to accept a Pull request which will add this.

Since we provide a docker-image already, this should not be too difficult to accomplish.

**Comment by xmatthias** [comment]
hi @theaidem 

The devcontainer config is now available on the develop branch.
