### ISSUE TITLE
Custom positioning

### ISSUE THREAD

**Issue by njvitto** [freqtrade/freqtrade#3767]
Hi all,
I'm new to freqtrade and I already read the documentation (not everything in detail but some things more in detail and others on the surface).

Long story short the question is: I don't see any possibility to customize the positioning, more than using Edge instead of the dynamic (volume-based) whitelist. If, let's say, I have in mind to implement a strategy that evaluate the positioning on a trade based on the volatility, is there any way to do that?

Thank you!

**Comment by xmatthias** [comment]
well - define "customize positioning" ... 

Edge does a lot - so there's multiple things you might want to do manually, what edge provides.

**Comment by njvitto** [comment]
Hi @xmatthias thanks, I see and I hope that I can do what I have in mind: essentially I wanna base the positioning calculating the volatility (let's say, using the standard deviation of the last X days) and then applying the inverse of that.
But more in general I wanted to know how is it possibly to customize the positioning logic with more sophisticated strategies.

**Comment by xmatthias** [comment]
Without edge, you can currently use either [static stake](https://www.freqtrade.io/en/latest/configuration/#static-stake-amount) or [dynamic stake](https://www.freqtrade.io/en/latest/configuration/#dynamic-stake-amount).

Neither of both can be controlled via the strategy at this moment.

**Comment by njvitto** [comment]
Hi @xmatthias yes I was talking about position size. Thank you for the comments!
I think that controlling the position size from the strategy would be important, if I start using freqtrade more seriously maybe I will evaluate a PR on this.
