### ISSUE TITLE
Getting Active trading pairs during backtesting, dry run, and live run

### ISSUE THREAD

**Issue by kumkee** [freqtrade/freqtrade#3768]
## Describe your environment

  * Operating system: linux
  * Python Version: 3.6.9 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.8 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*
In my strategy file, how do I get the list of active trading pairs during all situations, i.e. backtesting, dry run and live trading?
Or within populate_indicators or populate_buy_trend, how do I tell if self.metadata['pair'] is in active trade or not?

**Comment by xmatthias** [comment]
You can do this for dry-run and live via [the trades object](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-trades).

Due to the way backtesting works (in a vectorized way) - this information is not available in backtesting, as the trade entries are only calculated after all signals have been generated.

**Comment by kumkee** [comment]
> Due to the way backtesting works (in a vectorized way) - this information is not available in backtesting, as the trade entries are only calculated after all signals have been generated.

For vectorized manner (dataframe), given a populate_buy_trend and sell trend (two arrays of 1s and 0s) and a pair's dataframe, is it possible to get a column of trading status for a pair?

**Comment by xmatthias** [comment]
for dry-run and live - yes, you can populate a column with this.

For backtesting, no, this is not possible as this information is not available at the time populate_buy_trend would be called.

**Comment by xmatthias** [comment]
Going to close this as i think the question was answered.

Feel free to reopen if it's still unclear.
