### ISSUE TITLE
stopped buying after update to 2020.8

### ISSUE THREAD

**Issue by ovresko** [freqtrade/freqtrade#3772]
## Describe your environment

  * Operating system: Win 10 64bit
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ 2020.8

Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*
Well i had a live bot for days working perfectly, yesterday i've decided to update from 2020.07 to 08. didn't change anything except pulling updates. restarted docker from yesterday not a single buy (had 20 to 40 buy average per day before) no errors, no warnings logs show running, i've tried to delete sqlite and clear pyc nothing same strategy same config executed 29 buys in backtesting with 2020.07
are there any breaking changes in this version i should consider?
i've tried everything i can think of. what could by the issue. should i rollback to 2020.7
thanks

**Comment by xmatthias** [comment]
No there were no breaking changes (we try hard to avoid breaking changes).

I just went through the change diff ([available here](https://github.com/freqtrade/freqtrade/compare/2020.7...2020.8)) - but there's nothing i can think of that can break a strategy.

Best look at the "startup" logs - maybe it's something very subtle - but usually, the logs should point that out.

The simplest answer is usually - the bot simply did never return a "buy" signal - or max_open_trades is reached ... (but neither of these were touched between 2020.7 and 2020.8 ...).

**Comment by ovresko** [comment]
well it's been 2 days now, i've installed ft2020.8 in another machine with same config and strategy, same result backtesting the past 12 hours gives 14 buys, live running nothing without errors.
how can i pull back 2020.7, it looks docker has only master tag.

**Comment by xmatthias** [comment]
yes, docker has only the master tag.
best retagg your previous image (assuming it's still around). Otherwise you need to build the image yourself.

**Comment by xmatthias** [comment]
Just one note - not upgrading will not really solve the problem. 
The diff did not show anything even potentially problematic - so i do suspect other reasons for the problems you're seeing.

**Comment by ovresko** [comment]
thank you for your help, i've been on it for 2 days now, it's related to PrecisionFilter and/or SpreadFilter config, i've removed them from the config and immediately got a buy. 
thanks again
