### ISSUE TITLE
2 telegram accounts in config.json

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#3780]
Is there a way to configure 2 telegram accounts in the config.json, so 2 people can pull information and send commands to the Freqtrade bot?

Like this, but twice maybe?

```
    "telegram": {
        "enabled": true,
        "token": "token-here",
        "chat_id": "id-here"
    },
```

Thanks

**Comment by xmatthias** [comment]
No, this is not possible.

According to people on slack, it's possible to add a telegram bot to a group chat (where then everyone can control the bot) - but i've never tried this, so best join the Slack channel and ask there.

**Comment by aristosv** [comment]
thank you
