### ISSUE TITLE
"--spaces trailing" - Hyper-Opt Results Are Not Matching Back Test Results.

### ISSUE THREAD

**Issue by PythonCommander** [freqtrade/freqtrade#3781]
## Describe your environment

  * Operating system: UBUNTU 18.04
  * Python Version: 3.6.9 (`python -V`)
  * CCXT version: ccxt==1.33.72 (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-10c5b230 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I am having trouble using the trailing stoploss in hyperopt. I cannot seem to match the results it gives me with the backtest results in freqtrade. 

### Steps to reproduce:

  1. I start off my hyperopt by using the "--spaces default" parameter. I pick the best hyperopt result, and run it in freqtrade backtester. It will provide me with matching hyperopt and backtesting results at this point.

  2. Next, I run the trailing hyperopt with "--spaces trailing" parameter. This is when I get hyperopt results that don't match backtest results.

  
### Observed Results:

From what I noticed is that every time I use "--spaces trailing" I get inaccurate backtest results in freqtrade. I am not sure if this is a bug and if I should continue to use trailing stoploss in my strategies anymore.

**Comment by xmatthias** [comment]
Hyperopt is just running backtesting under the hood, so if the parameters are transferred correctly, then results will match 100%. There is no technical base for results to not match if all conditions are in the strategy as defined in the hyperopt file / hyperopt output.

One common gotcha:
Make sure to read the backtesting log messages VERY carefully it's very likely that you have something in the config overwriting a setting you set in the strategy - making that setting irrelevant.

This is not done when hyperopting that specific parameter, so the same configuration that sets `"trailing_stop": false` will produce different results for backtesting when hyperopting for the trailing space.

Explicit disabling used to be in the configuration examples [up to recently](https://github.com/freqtrade/freqtrade/commit/dff0ac276803e480c03ba6fb33620b7179307824) - so i suspect this is the reason for your misalignment.

**Comment by PythonCommander** [comment]
Oh okay, that's good to know. I'll take a look at the configuration file and logging to see what might be causing my problem. It definitely sounds like that could be the issue.

**Comment by PythonCommander** [comment]
> Hyperopt is just running backtesting under the hood, so if the parameters are transferred correctly, then results will match 100%. There is no technical base for results to not match if all conditions are in the strategy as defined in the hyperopt file / hyperopt output.
> 
> One common gotcha:
> Make sure to read the backtesting log messages VERY carefully it's very likely that you have something in the config overwriting a setting you set in the strategy - making that setting irrelevant.
> 
> This is not done when hyperopting that specific parameter, so the same configuration that sets `"trailing_stop": false` will produce different results for backtesting when hyperopting for the trailing space.
> 
> Explicit disabling used to be in the configuration examples [up to recently](https://github.com/freqtrade/freqtrade/commit/dff0ac276803e480c03ba6fb33620b7179307824) - so i suspect this is the reason for your misalignment.

I took a look at the logging during backtest and I found out the problem. It was because the trailing stoploss wasn't being picked up on in the strategy file. So what I did was put the trailing stoploss parameters in the config file, and the backtester was able to use the trailing stoploss. Which leads me to another question, I think I might be inputing trailing stoploss incorrectly on the strategy file. I was wondering if you can take a look at my format? I'm not sure what I could be typing wrong on the strategy file for trailing stoploss.

`class STRATEGY(IStrategy):

    ticker_interval = '5m'

    # ROI table:
    minimal_roi = {
        "0": 0.10002,
        "13": 0.06943,
        "40": 0.03326,
        "140": 0
    }

    # Stoploss:
    stoploss = -0.32554

    # Trailing stop:
    trailing_params = {
        'trailing_only_offset_is_reached': True,
        'trailing_stop': True,
        'trailing_stop_positive': 0.01,
        'trailing_stop_positive_offset': 0.04137
    }`

**Comment by xmatthias** [comment]
Well you're using the wrong syntax for the parameters (that's why i said - if it's done correctly, it'll match).

each setting needs to be a top level setting - so the correct way in a strategy would be:

``` python
    trailing_only_offset_is_reached: True,
    trailing_stop: True,
    trailing_stop_positive: 0.01,
    trailing_stop_positive_offset: 0.04137
```

**Comment by PythonCommander** [comment]
Oh okay cool, I'll make sure to use that format. I was just copy any pasting the results from hyperopt thinking that was the correct way. Do you think I can contribute by fixing that format on the hyperopt file?

**Comment by xmatthias** [comment]
Yeah sure

changing the format of something is usually a good way to start contributing :+1:

**Comment by PythonCommander** [comment]
Hey xmatthias, I had a quick question that's not in regards to this post but I just don't want to open up another issue since it's not really an issue. 

So I'm thinking of buying the new Ryzen 5900x CPU coming out in November, and also buying 64Gb of RAM. Do you really  think it will make hyperopt run better than my current build? Right now,  I have a Ryzen 2600 12 core CPU and 24Gb RAM. 

I really want to hyperopt at least 365 days of data on 5 minute time frame but my build is having trouble hyperopting 150 days of data. On the system monitor, I see about every 5 minutes all my cpu cores go to 100%, and my 24Gb of RAM is 100% used. I also see my CPU temp is around 55C which is good but I'm not sure why my computer freezes if I try to hyperopt 365 days of data.

**Comment by xmatthias** [comment]
because you run out of memory.

I'm not into the "high powered machines" anymore (not since about 15 years i think) - so i can't really recommend.
Now i'm not going to look into the differences between the 2 CPU's - but assuming both have 12 cores, then a slightly faster CPU will not give you much benefits, more cores on the other hand might - but the really limiting factor will be RAM, as each core requires the full datset in memory. You should however be albe to get around that by defining a biggish swap-file (at least avoid freezing).

**Comment by PythonCommander** [comment]
Awesome, I went ahead and adjusted my swap file size and I see a good difference. Thanks for your advice.

**Comment by xmatthias** [comment]
For everyone trying to work on this:
A good place to start working on this is `_params_pretty_print()` in `hyperopt.py`.

Once you got a result in hyperopt, further testing can be done using `freqtrade hyperopt-show -n xx` - this prevents having to run hyperopt 200ds of times.
