### ISSUE TITLE
automatically answer questions during installation

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#3782]
I am using this in a bash script to install Freqtrade on Debian 10

```
apt install -y git python3-pip python3-venv sudo
git clone https://github.com/freqtrade/freqtrade.git
cd freqtrade
git checkout develop
./setup.sh --install
```

Is there a way to automatically answer the following 2 questions during installation?

![1](https://user-images.githubusercontent.com/528302/93118823-88129500-f6c9-11ea-8174-a22ce773f621.png)

![2](https://user-images.githubusercontent.com/528302/93118846-8fd23980-f6c9-11ea-8387-7aa2bf9b73ab.png)

Thanks

**Comment by aristosv** [comment]
never mind, I used this

printf 'y\ny\n' | ./setup.sh --install

Seems it did the job

**Comment by xmatthias** [comment]
i assume you're trying to automate - in which case i would recommend to not use the installation script, but run the few commands it really runs manually (which is creating the environment, followed by `pip install -r requirements.txt` followed by `pip install -e .`).

If you're about automating this, i'd recommend to use docker - much simpler to automate it that way :)

**Comment by aristosv** [comment]
thank you, I'll test the docker method also.
