### ISSUE TITLE
How to extract freqtrade edge data and the max number of bots to run on a 4 GB RAM, 2 vCPUs, 80 GB SSD

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#3785]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.6.8
  * CCXT version: 1.32.7
  * Freqtrade Version: 2020.8
  
## Your question
Hey good people.
I have a few questions regarding running freqtrade: 
1. How many bots can be run simultaneously on a 4 GB RAM, 2 vCPUs, 80 GB SSD? I took one from the cloud recently because I want to experiment with several bots. 
2. Supposing that I want to create an api of the list returned by freqtrade edge, where is this list coming from? it seems they are not entered on sqlite database anyone knows how I can extract just the list of pairs, expectancy and winrates in json format?
3. Does anyone have an idea how to convert freqtrade into a service? just a summary or a link to a guide will help.

As always comments much appreciated.

**Comment by xmatthias** [comment]
In general - please read the documentation, 2 of the 3 points below are covered there.

1) we have [default requirements](https://www.freqtrade.io/en/latest/#hardware-requirements) - which say that 2 vCPU's will run 1 bot. Now inofficially, you might be able to run multiple bots on that machine, but it'll depend on the amount of pairs, timeframe, and on the strategy you run.
  you can't scale it indefinitely either (so having 10 vcpu won't mean you can run 10 bots) -  after 2-3 bots (depending on the exchange) you'll run into API rate limit errors - so you're usually better off running multiple smaller Machines.
2) you can't while real runs. It's calculated on the fly when edge runs. i guess you can use edgeCLI, which is similar to backtesting and should give you a summary per pair. 
3) [Read the documentation!!!](https://www.freqtrade.io/en/latest/advanced-setup/#configure-the-bot-running-as-a-systemd-service).

**Comment by moinonin** [comment]
Thank you @xmatthias. The first and the third questions are fabulously answered. About getting edge data, I have been looking at that edge_psotioning.py module. Do you think it could be possible to write an external file that gets that "result" variable out as a continuous loop while edge is running? If so, a little juice will go a long way 🙏

**Comment by xmatthias** [comment]
i'm not sure what the benefit would be for that.
Edgecli shows you the results already.

is it possible - for sure - everything is possible.
does it make sense? Not in my opinion
does freqtrade do it? No it does not - but it's open source, so you can add it if you think it's necessary.

**Comment by moinonin** [comment]
Thanks @xmatthias. I will play with it in my free time.
