### ISSUE TITLE
Calculation from your buy point(price)?

### ISSUE THREAD

**Issue by kiandp** [freqtrade/freqtrade#3800]
## Describe your environment

  * Operating system: LINUX
  * Python Version: _____ 3.6.9
  
## Your question
How can I use my buy point value & how can I define it for further calculations?

I want to sell a pair when the price dropped 1 ATR(AVERAGE TRUE RANGE) from my last buy price.?
I know stop_loss & ROI function calculation is based on our last buy, but how can I define it and use this value for further calculations?
I deeply appreciate your time & effort in sharing your valuable time & knowledge.

**Comment by xmatthias** [comment]
i guess you can implement this in your `populate_sell_trend()` method.

Stoploss / ROI are currently not dynamic, which means that you can only set it once for the whole bot, but not per pair (and also not per trade).

this might be an enhancement in the future (see #909) - but it's currently not possible.

**Comment by kiandp** [comment]
Dear @xmatthias, I want to implement it in my sell_trend  signal, however, I don't know if it's possible to set my sell trend based on my buy point value.
My intention is to sell:(Whenever it Dropped 1ATR from my buy point)
"buy_point< "1ATR".
So from my understanding, I can't get the value?
 How can I define my "buy_point" 
However, ROI /Stoploss function keeps updating themselves based on new buy points, right?
So, how I can get the value they are using?
Thanks

**Comment by xmatthias** [comment]
You can get trades in live and dry-run modes [as documented](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-trades).

The trade object will also contain the stoploss price.

This won't work in backtesting however, as backtesting calculates all signals once right at the start (where no buys / sells did happen yet - only buy signals).

**Comment by xmatthias** [comment]
i'll assume this question as answered.

Feel free to comment below / reopen if it's still unclear.

**Comment by x0y-gt** [comment]
I need something very similar(or probably the same)

Based on the **open price**, how can I set a fixed stop loss 1 ATR below? (the ATR at the time of the open price)
