### ISSUE TITLE
Incorrect /profit calculations

### ISSUE THREAD

**Issue by elisy** [freqtrade/freqtrade#3804]
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.6.9
  * CCXT version: 1.30.48 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.6 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Sometimes /profit ROI: All trades percents are not correspond to stake and fiat currencies
![p1](https://user-images.githubusercontent.com/2704050/94345379-2fd37f80-0047-11eb-8289-fa6aca26e34b.PNG)

### Steps to reproduce:

  1. Open Telegram
  2. Send command /profit
  
### Observed Results:

  * What happened?
It shows ROI: All trades positive percents and Σ% while sums of stake and fiat are negative
  * What did you expect to happen?
I want percent calculated based on the BTC amounts. They will be negative when BTC is negative.

### Relevant code exceptions or logs
n/a

**Comment by xmatthias** [comment]
Are you using dynamic stake amount (stake amount = unlimited)? 

Irrespective of this - (something similar can also happen when buy-orders are partially filled), of if stake-amount has been changed at a certain point.

Please provide a corresponding `/status table` and `/status` - so the calculation can be verified.

I do not think this is a bug however.
The calculation of % is done per trade, and then an average (and sum) of this % is taken.

Assume the following 3 trades (I'm using USDT as it simlifies calculations)
trade 1: 100 USDT
trade 2: 100 USDT
trade 3: 50 USDT (half filled / last stake / for whatever reason, this trade is only half the size).

Now let's look at profits:
Trade1: +2% (102 USDT)
Trade2: -10% (90 USDT)
Trade 3: +10% (55 USDT)

your absolute profits are negative  2 - 10 + 5 = -3 USDT
Your relative profits however are positive (2% - 10% + 10% = +2%) - and the average is also positive (2 - 10 + 10) / 3 ~= 0.66)

The relative profit must consider the trade size (so must be calculated per trade and then aggregated) - otherwise you'd penalize strategies once you size up (give it bigger stakes - and the first few bigger stakes are losers).
This would also show very odd results for edge (which will change size depending on the calculated risks - so it's supposed to use lower stake-amounts on risky trades, and higher stakes for trades that edge considers less risky).

**Comment by elisy** [comment]
> Are you using dynamic stake amount (stake amount = unlimited)?
yes

> Please provide a corresponding `/status table` and `/status` - so the calculation can be verified.
They cannot show anything
  ID  Pair      Since    Profit (USD)
----  --------  -------  ----------------
  51  ANKR/BTC  1 month  -10.17% (-62.90)
  57  ETC/BTC   1 month  -9.10% (-10.68)
  78  IOTA/BTC  1 month  -8.56% (-23.59)
  94  DCR/BTC   1 month  -7.98% (-24.68)
 100  STX/BTC   1 month  -11.20% (-25.75)
 102  ALGO/BTC  1 month  -6.86% (-17.46)
 107  VIA/BTC   1 month  -10.26% (-17.83)
 115  VITE/BTC  3 weeks  -10.87% (-27.46)
 146  POWR/BTC  2 weeks  -17.46% (-8.47)
 152  XLM/BTC   2 weeks  -15.66% (-7.59)
 162  ZEC/BTC   2 weeks  -17.36% (-9.38)
 163  ETH/BTC   2 weeks  -10.93% (-5.88)
 165  OMG/BTC   2 weeks  -24.66% (-14.33)
 166  WRX/BTC   2 weeks  -19.51% (-11.49)
 169  AGI/BTC   2 weeks  -13.64% (-7.34)

**Comment by elisy** [comment]
> I do not think this is a bug however.
> The calculation of % is done per trade, and then an average (and sum) of this % is taken.
May be additional results should be done like stake/currency turnover and total profit %

**Comment by xmatthias** [comment]
> In the current state % allows compare strategies. But this parameter does not say how strategy is profitable.

I don't agree with this.

Assume you'd be using a static stake amount (and let's assume all buy orders fill completely) - and the same trades you have now would have been executed with this static stake amount - then the strategy would be profitable (see avg / sum profit).

You're not using the static stake amount - and the bigger trades happen to be bigger losers. 
That's however not the strategy's fault - as the strategy does not control stake amount - but you do.

**Comment by elisy** [comment]
> I don't agree with this.

In any cases ROI (Return on Investment) is determined as 
ROI = (Current Value of Investment−Cost of Investment) / Cost of Investment
and it is not determined like 
ROI = SUM(percents)/COUNT()

In my case Telegram returns 
ROI: All trades
∙ -0.00457319 BTC (1.16%) (195.31 Σ%)

-0.00457319 is correct - it is (Current Value of Investment−Cost of Investment)
And 1.16 is not ROI because it is not calculated like -0.00457319 / Cost of Investment
So in not profitable situation ROI is positive and equals 1.16% this is error.
​

**Comment by yagmot** [comment]
I'm seeing something similar, and it's related to the stake amount changing. In my case, I had a max number of trades at 15, then upped it to 20, and now my daily profit numbers are showing negative despite all the days trades being positive.

If the calculations are thrown off when the stake amount changes, and the stake amount is configured to be dynamic, won't the ROI and profit number be incorrect at all times?

```
Daily Profit over the last 7 days:
Day         Profit USDT       Profit USD    Trades
----------  ----------------  ------------  ---------
2021-02-01  -1.50127318 USDT  -1.498 USD    7 trades


10 recent trades:
Open Date     Pair       Profit (USDT)
------------  ---------  ------------------
an hour ago   HTR/USDT   2.57% (0.34738794)
2 hours ago   HTR/USDT   3.36% (0.12956561)
2 hours ago   API3/USDT  1.50% (0.05738325)
2 hours ago   AMPL/USDT  1.12% (0.0428904)
15 hours ago  AMPL/USDT  1.85% (0.791394)
17 hours ago  SXP/USDT   2.15% (0.89943112)
17 hours ago  LUNA/USDT  5.31% (2.21411941)
```

**Comment by xmatthias** [comment]
i THINK we might end up removing that sum % alltogether ... 

the average is quite easy to calculate - but the sum is not if stakes are uneven - and all possibilities are considered:

e.g.: 
* stake-amount is changed from 20$ to 50$ per trade (i trust the strategy now)
* max_open_trades are static to 5 (so i'm limiting the bot to first 5 * 20$, then 5 * 50$ total investments).
* my account is bigger than this - i might have 10k$ in the account - but the bot only get's 250$ to trade.

* As consequence of the stake-amount change - we can't use "max_open_trades * stake_amount" as starting capital
* As consequence of having more money in the account, we can't use "balance" to derrive the absolute profit (current$ - absolute profit != starting capital)

Now how should we calculate the summarized profit?

**Comment by samgermain** [comment]
@xmatthias `Amount_BTC_returned - Amount_BTC_spent - Trading fees`, and for current trades `Current_BTC_value - Amount_BTC_spent - trading_fees`

**Comment by yagmot** [comment]
The database already contains the profit percentage and absolute amount for each transaction. Just use those values. Why does it matter what the current stake amount or wallet size is?

**Comment by xmatthias** [comment]
@yagmot the problem is not with absolute profit - that's pretty clear (it's simply the summed up absolute profits).

It's however problematic for the relative profit - as you don't have a base for the "relativeness".
