### ISSUE TITLE
Hyperopt List with indices 

### ISSUE THREAD

**Issue by 3inary** [freqtrade/freqtrade#3806]
## Describe your environment

   *Operating system: Ubuntu 18.04
   *Python Version: 2.7.17
   *CCXT version: 1.34.7
   *Freqtrade Version: develop-4c349342
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

After hyperopting with the --continue argument the epoch indices start again with 1 in the hyperopt list. This makes results after the first run inaccessible. 

freqtrade hyperopt-list:
+--------+---------+----------+---------------+--------------+------------------------------+----------------+-------------+
|   Best |   Epoch |   Trades |         W/D/L |   Avg profit |                       Profit |   Avg duration |   Objective |
|--------+---------+----------+---------------+--------------+------------------------------+----------------+-------------|
| * Best |   1/200 |      892 |   396/240/256 |       -0.02% |   -0.00139695 BTC  (-13.96%) |        141.1 m |     2.0162  |
| *      |   2/200 |     3045 | 1241/555/1249 |       -0.11% |   -0.03240355 BTC (-323.71%) |        177.6 m |     3.31584 |
| *      |   3/200 |     3640 |  1370/71/2199 |       -0.13% |   -0.04687602 BTC (-468.29%) |         63.4 m |     3.64556 |
| *      |   4/200 |     2922 | 1087/500/1335 |       -0.12% |   -0.03463698 BTC (-346.03%) |        141.8 m |     3.34242 |
.
.
.

|        |  98/200 |      525 |     255/6/264 |       -0.00% |   -0.00002624 BTC   (-0.26%) |         60.8 m |     1.83411 |
|   Best |  99/200 |      486 |     241/4/241 |        0.02% |    0.00101469 BTC   (10.14%) |         56.7 m |     1.79693 |
|        | 100/200 |      362 |     171/8/183 |        0.01% |    0.00041274 BTC    (4.12%) |         51.5 m |     1.82638 |
| * Best |   1/200 |      477 |    207/178/92 |       -0.11% |   -0.00531791 BTC  (-53.13%) |        193.1 m |     2.19047 |
| * Best |   2/200 |      204 |     104/28/72 |        0.13% |    0.00260183 BTC   (25.99%) |         62.5 m |     1.80171 |
| *      |   3/200 |      660 |   312/201/147 |        0.03% |    0.00180539 BTC   (18.04%) |        291.4 m |     2.0798  |
.
.
.
|        |  96/200 |     1616 |     725/7/884 |       -0.08% |   -0.01250800 BTC (-124.95%) |         52.2 m |     2.43739 |
|        |  97/200 |      244 |    118/10/116 |        0.05% |    0.00120067 BTC   (11.99%) |         65.7 m |     1.84316 |
|        |  98/200 |      280 |     142/5/133 |        0.04% |    0.00121177 BTC   (12.11%) |         65.0 m |     1.83372 |
|        |  99/200 |      420 |    216/10/194 |        0.01% |    0.00046165 BTC    (4.61%) |         71.3 m |     1.84226 |
|   Best | 100/200 |      482 |    258/13/211 |        0.12% |    0.00561579 BTC   (56.10%) |         74.6 m |     1.66796 |
+--------+---------+----------+---------------+--------------+------------------------------+----------------+-------------+

### Steps to reproduce:

  1. freqtrade hyperopt --hyperopt Hyper --strategy Strategy -e 100
  2. freqtrade hyperopt --hyperopt Hyper --strategy Strategy -e 100 --continue
  3. freqtrade hyperopt-list
  4a. freqtrade hyperopt-show -n 100 -> shows first epoch  100
  4b. freqtrade hyperopt-show -n 200 -> shows second epoch 100
  
### Observed Results:

  * What happened?
  "Print details for the epoch 168 (the number of the epoch is shown by the hyperopt-list subcommand or by Hyperopt itself during hyperoptimization run)"
   This does not work since there are multiple epochs with the number 168, one for each --continue run.
  * What did you expect to happen?
   epochs match index in the hyperopt-list 

Technically it is working as it should. For the first run epochs link to the list index, but with a large numbers of results from multiple runs, and different epoch lengths, it is impossible to find the right index from the list to call it with _freqtrade hyperopt-show -n xxx_ . This problem worsens if the list gets filtered with other parameters like --best.
Suggestion: make the epochs continuous in the list or, probably easiest, print the list index. 
I don't know here, if the original epoch is any useful information or if it just could be replaced by the list index.

**Comment by xmatthias** [comment]
i don't think you should be using `--continue` at all - it's broken (#2464) and does not do what you think it does.
I think --continue should be disabled - removed until it's working as it should (which will probably be never, as it doesn't provide any benefits).

Yes, hyperopt results from a new run will overwrite previous runs as the filename is static (open issue #3407).
For now, best rename the file if you want to keep previous results - but really there's not much point - once you know your results are good - transfer them to a strategy.

A new hyperopt will always find other points - which are either better or worse - but i don't see why keeping old results around would make sense.

Either way - #3407 might introduce a simliar method to backtesting, where old results ARE kept around - so you would then be able to select the correct filename.

**Comment by 3inary** [comment]
Ok, thank you for clarification.
