### ISSUE TITLE
Custom indicator function performance issue

### ISSUE THREAD

**Issue by zlac116** [freqtrade/freqtrade#3808]
I have added a custom indicator function which attempts to find the local maxima and minima using the scipy.signal.argrelextrema module. I added the function to the freqtrade.vendor.qtpylib.indicators.py script. However, the performance is extremely slow when I run backtests and dry/live runs. I guess I have two questions:
1. Is this the best place to add custom indicator functions?
2. If so, how can I circumvent this performance issue?

Thanks

**Function**

```
from scipy.signal import argrelextrema

def get_max_min(prices, smoothing, window_range):
    smooth_prices = prices['close'].rolling(window=smoothing).mean().dropna()
    local_max = argrelextrema(smooth_prices.values, np.greater)[0]
    local_min = argrelextrema(smooth_prices.values, np.less)[0]
    price_local_max_dt = []
    for i in local_max:
        if (i > window_range) and (i < len(prices) - window_range):
            price_local_max_dt.append(prices.iloc[i - window_range:i + window_range]['close'].idxmax())
    price_local_min_dt = []
    for i in local_min:
        if (i > window_range) and (i < len(prices) - window_range):
            price_local_min_dt.append(prices.iloc[i - window_range:i + window_range]['close'].idxmin())
    maxima = pd.DataFrame(prices.loc[price_local_max_dt])
    minima = pd.DataFrame(prices.loc[price_local_min_dt])

    maxima['maxima'] = 1
    minima['minima'] = 1
    max_min = prices.join(maxima[['maxima']], how='left').drop_duplicates()
    max_min = max_min.join(minima[['minima']], how='left').drop_duplicates()
    max_min['maxima'] = max_min['maxima'].fillna(0)
    max_min['minima'] = max_min['minima'].fillna(0)

    return max_min[['maxima','minima']]
```

**Comment by zlac116** [comment]
Managed to use a few lines of code instead of using a custom indicator functions. Thanks

**Comment by xmatthias** [comment]
and adding an indicator to a freqtrade internal file is NEVER the right way. 
Any update would remove your changes again.

You can add it to your strategy file - or contribute it to the technical module...

**Comment by zlac116** [comment]
Ended up using the following code, within the strategy script. It seems to give very good backtest results, perhaps too good so I'm still investigating the final dataframe to ensure that there are no subtle errors.

```
# Local Maxima/Minima
        dataframe['min'] = dataframe.iloc[argrelextrema(dataframe.close.values, np.less_equal, order=9)[0]]['close']
        dataframe['max'] = dataframe.iloc[argrelextrema(dataframe.close.values, np.greater_equal, order=9)[0]]['close']
        dataframe['minima'] = np.where(dataframe['min'].isnull(), 0, 1)
        dataframe['maxima'] = np.where(dataframe['max'].isnull(), 0, 1)
        dataframe['min'].ffill(inplace=True)
        dataframe['max'].ffill(inplace=True)
        dataframe['minima_sum'] = dataframe['minima'].rolling(window=19).sum()
```

**Comment by xmatthias** [comment]
I've never used `argrelextrema` - but based on the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.argrelextrema.html) it looks at both sides of the currently evaluated section - so in your case (`order=9`) - it would look 9 candles into the past - and 9 candles into the future.

Now this could be wrong (do your own investigation please) - but it's easy to trade well if i know what the minimum/maximum in 9 hours from now have been ...

**Comment by zlac116** [comment]
Thanks @xmatthias. I also noticed that the `order` arg is used to control number of local candles to the compute the local minima and maxima and is possibly causing issues by attempting to look at candles in the future. I may have to find another way of finding the peaks and troughs on the historic data sets, perhaps just using pandas only and in the rolling window format.

**Comment by TheJoeSchr** [comment]
>I may have to find another way of finding the peaks and troughs on the historic data sets, perhaps just using pandas only and in the rolling window format.

Did you find a way to do this?

**Comment by adevrent** [comment]
> > I may have to find another way of finding the peaks and troughs on the historic data sets, perhaps just using pandas only and in the rolling window format.
> 
> Did you find a way to do this?

I came up with a way to find maxima and minima points without lookahead bias, just using numpy and pandas. It is not slow imo but any optimization is appreciated. Here's  [the strategy file](https://github.com/adevrent/freqtrade_custom_strats/blob/master/strats/pandaspivots.py) and the [jupyter notebook](https://github.com/adevrent/freqtrade_custom_strats/blob/master/python_concepts/pivot_points/pivots_pandas_version.ipynb)
