### ISSUE TITLE
Install 3rd Party Python Modules onto the Docker image

### ISSUE THREAD

**Issue by kumkee** [freqtrade/freqtrade#3809]
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*
Is it possible to modify the Docker image to include some 3rd part python models? 
I am looking to include Pytorch for example.

**Comment by xmatthias** [comment]
Then you did not look very hard (nor very thorough...): [Documentation Link](https://www.freqtrade.io/en/latest/docker_quickstart/#additional-dependencies-with-docker-compose) :smiley: 

You'll have to build the image yourself - but if you base it off of the freqtrade image, then only your dependencies will be necessary.

**Comment by kumkee** [comment]
Thank you @xmatthias 
What about private repository?
If I don't want to share my public key with my team, is there a way to pull my GitHub private code and build that into my image?

**Comment by xmatthias** [comment]
I'm not sure there is - but it's not relevant for freqtrade.

Best use google to research this- it's not related to freqtrade, but in general on how to build images with private information (which you shouldn't do).
