### ISSUE TITLE
Current daily volume from a 1m strategy

### ISSUE THREAD

**Issue by rylos** [freqtrade/freqtrade#3816]
## Describe your environment

  * Operating system: ____Ubuntu 20.04
  * Python Version: 3.8_____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Currently I'm on a 1min strategy and getting informative dataframe for 1d too, all is working fine with indicators etc but
I'm not able to retrieve the "current" 1D volume. The informative dataframe has the last (yesterday) volume. How can I get the current live volume daily?
Thank you in advance

**Comment by xmatthias** [comment]
Well you can ticker endpoint [as shown in the docs](https://www.freqtrade.io/en/latest/strategy-customization/#tickerpair).

the `'quoteVolume'` line should contain what you're looking for. It'll depend on the exchange if it's rolling 24h or 00:00 - now volume...

**Comment by rylos** [comment]
Ok but what if I need current RSI (daily) value from a 30m interval strategy. Is there a way?
I've tried with resample and informative dataframe but I loose always the current candle values (like current RSI_1d value).
Help?

**Comment by xmatthias** [comment]
The current candle is not yet complete - so values calculated based on it are subject to repainting - therefore freqtrade will not pass these candles to the strategy.
