### ISSUE TITLE
Installation issues - ModuleNotFoundError: No module named 'freqtrade'

### ISSUE THREAD

**Issue by rrrohit** [freqtrade/freqtrade#3819]
Hi, I am struggling to get the bot to run. Looked in multiple places but haven't been able to identify the issue/fix. Help will be appreciated.

1. I was getting an issue installing the freqtrade instance from montrealtradinggroup github because of Python version mismatch (had python 3.8 installed vs python 3.6 or python 3.7). I read on a different thread that in such cases we should install freqtrade directly from freqtrade.io - which I did

2. I got 2 errors while building directly from freqtrade.io

Building wheels for collected packages: blosc, py-find-1st

  Building wheel for blosc (PEP 517) ... error

   Building wheel for py-find-1st (PEP 517) ... error

But the installation did complete and it gave a msg saying that I can run the bot

3. I activated the .env and tried to run the bot. When I did try to run the bot using the command

freqtrade trade -c config.json

freqtrade: command not found

It gave an error

4. I then tried using a different command and got another error -

python ./freqtrade/main.py -c config.json

Traceback (most recent call last):

  File "./freqtrade/main.py", line 15, in <module>

    from freqtrade.commands import Arguments

ModuleNotFoundError: No module named 'freqtrade'

5. Someone mentioned on a different thread to run "pip install -e ." - which I did but got the same error on (2) above. Also when I tried to run (4) again got the same error.

6. Based on feedback from a different thread, ran this command "(.env) rrohit@rrohit-VirtualBox:~/freqtrade$ export PYTHONPATH=.:$PYTHONPATH"

And now get this error -

.env) rrohit@rrohit-VirtualBox:~/freqtrade$ python ./freqtrade/main.py -c config.json

Traceback (most recent call last):

  File "./freqtrade/main.py", line 15, in <module>

    from freqtrade.commands import Arguments

  File "/home/rrohit/freqtrade/freqtrade/commands/__init__.py", line 10, in <module>

    from freqtrade.commands.build_config_commands import start_new_config

  File "/home/rrohit/freqtrade/freqtrade/commands/build_config_commands.py", line 5, in <module>

    from questionary import Separator, prompt

ModuleNotFoundError: No module named 'questionary'

7. I ran "(.env) rrohit@rrohit-VirtualBox:~/freqtrade$ pip install questionnaire" but still getting the same error.

.env) rrohit@rrohit-VirtualBox:~/freqtrade$ python ./freqtrade/main.py -c config.json

Traceback (most recent call last):

File "./freqtrade/main.py", line 15, in <module>

from freqtrade.commands import Arguments

File "/home/rrohit/freqtrade/freqtrade/commands/__init__.py", line 10, in <module>

from freqtrade.commands.build_config_commands import start_new_config

File "/home/rrohit/freqtrade/freqtrade/commands/build_config_commands.py", line 5, in <module>

from questionary import Separator, prompt

ModuleNotFoundError: No module named 'questionary'

Pls. help!

**Comment by xmatthias** [comment]
Well you hit an error installing - what did you expect?

You don't include which error you're encountering on installation - so it's difficult to help.

You also choose to delete all information we request from issues (which operating system you're running on, ....). We're not asking this for fun - without it, this issue will be closed without further warning, as it'll be a waste of time trying to help you if you're not telling us if you're using windows, linux,mac, or something else entirely.


Best delete the virtual environment (`rm .env -rf`) and start fresh (make sure to deactivate the virtual environment first).
Please then record the errors you get on installation - they should tell us what you're missing.

**Comment by rrrohit** [comment]
Here you go ...
**Describe your environment**

    Operating system: Ubuntu 20.04
    Python Version: Python 3.8.2

**Describe the problem:**

The error was due to some issue in python installation. On re-installing Python (sudo apt-get install python3-dev), the installation got completed successfully.

Thanks!

**Comment by xmatthias** [comment]
Great to hear, and thanks for updating us that you were able to solve the issue (and more importantly, how!).
