### ISSUE TITLE
Hyperopt results design is broken

### ISSUE THREAD

**Issue by elisy** [freqtrade/freqtrade#3822]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.6.9 (`python -V`)
  * CCXT version: ccxt==1.34.59 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop-d2111c08 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Describe the problem:

When I run hyperopt calculations results are not so beautiful like in the previous versions

### Steps to reproduce:

  1. Run freqtrade hyperopt -c ....
  2. Wait for results table
  
### Observed Results:

  * What happened?
Table is interrupted by " - freqtrade.misc - INFO - dumping json to "/home/sk/freqtrade/user_data/hyperopt_results/.last_result.json" messages

![fq-1](https://user-images.githubusercontent.com/2704050/94985538-78c09200-0579-11eb-84f5-8e4e4c4bd8f5.JPG)

  * What did you expect to happen?

I want results table to be unbreakable

**Comment by xmatthias** [comment]
Hi there,
Thanks for reporting - i didn't notice that this is happening while saving every 100 epochs.

will be fixed/merged once CI on #3823 completes.
