### ISSUE TITLE
'nan' result in Edge Module

### ISSUE THREAD

**Issue by michelecinque** [freqtrade/freqtrade#3839]
Hi developers, i would like to bring to your attention a computation problem of the edge module that is solved in this way to avoid 0/0 with result 'nan' on the best and worst paris.

I hope you solve it in a more elegant way than mine.
Thank you

https://github.com/freqtrade/freqtrade/blob/1628a0a4f08de4b40617db50fba6d54fe723898b/freqtrade/edge/edge_positioning.py#L313
![Immagine 2020-10-06 215021](https://user-images.githubusercontent.com/72468858/95252943-f99fb800-081d-11eb-9bde-0c02a3f56569.png)

**Comment by xmatthias** [comment]
Can you please elaborate what the actual problem is you're trying to solve?

I don't see why having nan should be a problem - it'll show nan if there are no trades - but when there are no trades, then nan is a valid outcome.

**Comment by michelecinque** [comment]
Hi xmatthias, the problem is in the case where have no loss trade and all trade are winnning trade: the 'nan' values migrate in the winrate, filtering out the pairs with winrate 100%.

**Comment by xmatthias** [comment]
are you able to share an example output of this?

the impact of this is not clear to me.

**Comment by michelecinque** [comment]
Hi Xmatthias
In the attachments you find the same edge results with or without the modify

You can see in the standard version pairs with winrate 1.00 (100%) and expectancy 'nan' that are filtered out.

In the modified version the pair with winrate 100% has expectancy 'inf' and are not filtered out.

I'm not a experienced programmer, i think my metod is really rought, but that work for me.
Thank you

[backtesting-mod.txt](https://github.com/freqtrade/freqtrade/files/5340309/backtesting-mod.txt)
[backtesting.txt](https://github.com/freqtrade/freqtrade/files/5340310/backtesting.txt)

**Comment by xmatthias** [comment]
I guess a proper fix should be the following.

Would be great if you could give this a try before we incorporate it - i've not been able to get any strategy suitable for edge to do only winning trades for one pair.


```
        df['average_win'] = np.where(df['nb_win_trades'] == 0, 0.0, df['profit_sum'] / df['nb_win_trades'])
        df['average_loss'] = np.where(df['nb_loss_trades'] == 0, 0.0, df['loss_sum'] / df['nb_loss_trades'])
```

**Comment by michelecinque** [comment]
Hi xmatthias
i think that it's works fine!
You can see in the attachment

Thank you for all.
Mike 5



![2020-10-08_20-53](https://user-images.githubusercontent.com/72468858/95501259-4ca57680-09a8-11eb-9950-2a481f0276d1.png)


[backtesting.txt](https://github.com/freqtrade/freqtrade/files/5350742/backtesting.txt)

**Comment by xmatthias** [comment]
Great, thanks for confirming! :+1:
