### ISSUE TITLE
Saving dataframe column between "cycles" and documentation error on cust_info

### ISSUE THREAD

**Issue by rylos** [freqtrade/freqtrade#3843]
## Describe your environment

  * Operating system: ____Ubuntu 20.04 
  * Python Version: _3.8____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __last develop__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
What I need is to store an entire column in dataframe between bot cycles.
If I create dataframe['longband'] in populate_indicators, every time this column is destroyed between cycles.
I've read about cust_info, but I'm not able to save the column as I get an error, I've trid in this way:

self.cust_info[metadata["pair"]["longband"] = dataframe['longband'] but i think there is a syntax error with []
Documentation says: self.cust_info[metadata["pair"]["crosstime"] += 1 (syntax error here too?)

Thank you

**Comment by xmatthias** [comment]
yeah, i guess it should be `self.cust_info[metadata["pair"]]["crosstime"] += 1`.

Be careful with saving a whole column here - it's meant for scalars / single values, not for dataframes.

**Comment by rylos** [comment]
Yeah I've tried this too, but the problem is that this raises a KeyError exception.  In my case metadata["pair"] is "BTC/USDT" and also writing directly  `self.cust_info["BTC/USDT"]["TEST"] = 25` raises KeyError.
cust_info is initialized as documentation to = {} in the main class.
Any idea?
