### ISSUE TITLE
How to create custom hyperopt

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#3844]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.6.8
  * CCXT version: 1.34.40
  * Freqtrade Version: 2020.9.1
  
## Your question

Hello peeps!

I know this might be out of scope for implementation, but I was wondering if anyone knows a quick way to run backtesting in a loop, fetch some results e.g. total profit, average duration, etc., and write to a file with spaces being say rsi between 47 and 60 for the populate buy/sell method(s).

Any leads are highly appreciated. 

Nick.

**Comment by xmatthias** [comment]
Well it's called hyperopt, as your title already suggests.

best study the [corresponding documentation](https://www.freqtrade.io/en/latest/hyperopt/).

**Comment by xmatthias** [comment]
I'll assume this as answered by the above - as hyperopt is exactly what asking about .

If you have more specific questions feel free to comment below or open a new issue if it's unrelated to this.
