### ISSUE TITLE
How would you pause trading after stop loss is hit?

### ISSUE THREAD

**Issue by kaiserex** [freqtrade/freqtrade#3846]
Hey, Guys,

I am trading ~ 30 pairs against BTC and they will all crash violently when the crypto market crashes and the stop loss will get triggered. My worry is, if the stop loss is at 10%, i will get stopped on all 30 pairs at 10%, but when the bot will start buying again and on a second wave down i will get stopped with 10% again, etc. Making it pretty stressful going to sleep :)
How would you recommend pausing the bot after a certain amount of stop losses have been triggered?
Currently what i can think off is polling the trades via api_server and once recent trades pass some threshold, you just send the command to /stop or /stopbuy. 
Is there a more elegant way to do this?

**Comment by xmatthias** [comment]
well in theory, your strategy should handle this.
You can use [informative pairs](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-informative_pairs) with a BTC/stable pair to detect the first wave down, preventing the bot from entering again.

[If you're really good at this, you're able to detect the first wave of the crash - but i guess THAT could make you millionaire :laughing: If you're able to detect the first wave before it happens please let me know :laughing:  ]


There's also multiple open issues about this (#2968, #1841, and to some degree #1091) - but nothing has been implemented so far. Ideally, it should be flexible so multiple of these "stopping" methods can be applied in parallel, as everyone will have different opinions / needs on when a bot should stop (and for how long)..
I've got some ideas, but time did not allow me to implement it yet.

In the meantime, nothing will stop you from implementing this in your strategy:

I don't see why you would need api_server for this - your strategy has access to [trades data](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-trades) - so doing this as an external, seperate process seems pointless / wrong to me, as the strategy can handle this.
in case of a "stopbuy situation" - just return 0 as buy-signal (without even evaluating your indicators eventually) to prevent further buys.

**Comment by kaiserex** [comment]
Thanks @xmatthias  for an extensive answer. I agree that strategy should handle the new buy signals by checking previous trades. This makes much more sense than an outside app. 
What about the open buy orders that are still open? Is freqtrade capable of cancelling these or should you use outside logic to do that?

**Comment by xmatthias** [comment]
I would strongly recommend to read the documentation (at least read all headers once - so you know what's there).

Almost everything that is possible with freqtrade is covered by the documentation.

I know it's extensive to read in full - but it covers [exactly this topic](https://www.freqtrade.io/en/latest/strategy-advanced/#custom-order-timeout-example) - and using the search, you should be able to get to these pages quite easily.
