### ISSUE TITLE
Is there a way to launch a short only strategy, which sells all the time instead of buying?

### ISSUE THREAD

**Issue by kaiserex** [freqtrade/freqtrade#3848]
I was thinking about launching a new strategy, which would short sell pairs against BTC on margin trading platforms such as poloniex. Are there some options to flip how the buying/selling happens?
For example the bot should be able to go and short sell DOGE/BTC as a buy signal and close the position as the sell signal.

**Comment by xmatthias** [comment]
Please use the search to find similar / related issues to avoid reopening issues which already exist.

There are multiple open issues that all cover part of this topic (#892, #2312 and mainly #2183).

In short:
there is currently no option to short.
