### ISSUE TITLE
Binance exchange access while hyperopt

### ISSUE THREAD

**Issue by elisy** [freqtrade/freqtrade#3866]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.6.9 (`python -V`)
  * CCXT version: 1.35.22 (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-62859455 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Describe the problem:

After hyperopt start freqtrade bot accesses Binance exchange. In the same time all data loaded locally and there is no need to get binance data remotely. 

### Steps to reproduce:

  1. Use Binance api in config json
  2. Start hyperopt
  3. The following log message:

020-10-14 09:25:52,417 - ccxt.base.exchange - WARNING - binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
2020-10-14 09:25:52,417 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fabb8222978>
2020-10-14 09:25:52,418 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fabb9128730>, 801.696480883)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fabb82228d0>
Traceback (most recent call last):                                                                                                                 
  File "/home/sk/freqtrade/freqtrade/exchange/exchange.py", line 142, in __del__
    asyncio.get_event_loop().run_until_complete(self._api_async.close())
  File "/usr/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'QueueFeederThread'
  
### Observed Results:

  * What happened?
Access to Binance api
  * What did you expect to happen?
There is no need api access while data downloaded locally

**Comment by xmatthias** [comment]
the exchange object is necessary to get the correct (and uptodate) fees for the exchange you're using.

The exception seems to occur while the exchange is removed before hyperopt (it's not needed for hyperopt, and it's not compatible with hyperopt either).

Now i've never seen this error before - but i also find the event loop (QueueFeederThread) very strange.

is there anything you did / messed with in your python installation (either via environment variables, or via settings) that can cause a different eventloop to be used?

**Comment by elisy** [comment]
> is there anything you did / messed with in your python installation (either via environment variables, or via settings) that can cause a different eventloop to be used?

The message has been occurred after version develop-d2111c08

I use standard installations. Freqtrade update made via 
git pull 
./setup.sh --update
and 'y' for all questions

Screen is like this:
![fq-2](https://user-images.githubusercontent.com/2704050/95944988-58ab9100-0e0b-11eb-910a-159ace5eff4b.JPG)

**Comment by xmatthias** [comment]
while i don't understand the error (it's not happening when i run hyperopt) - is it actually creating a problem?

It seems to progress just fine.


Also - are you using something from the exchange or dataprovider in either hyperopt or strategy files?

**Comment by elisy** [comment]
> while i don't understand the error (it's not happening when i run hyperopt) - is it actually creating a problem?

No error does not create problem. It does not block the process. Hyperopt works correctly.

> Also - are you using something from the exchange or dataprovider in either hyperopt or strategy files?

I am not using neither dataprovider nor direct access to exchange. Hyperopt processes 2 spaces only: --spaces buy sell
It accesses qtpylib.bollinger_bands(qtpylib.typical_price(dataframe),... ,  qtpylib.typical_price(dataframe), ta.RSI(dataframe), dataframe['close'], dataframe['open'], dataframe['high']

**Comment by elisy** [comment]
> it's not happening when i run hyperopt

Since yesterday I cannot reproduce the issue and log message. I have run about 4 hyperopt tests. I cannot run the exact same hyperopt and strategy that reproduced issue because I redesigned them.
Now I see another message
warnings.warn("The objective has been evaluated "
This message is strange because after "The objective has been evaluated " it shows another best result.
![fq-3](https://user-images.githubusercontent.com/2704050/96221286-22594780-0fac-11eb-8d6d-8065de740c9b.JPG)

**Comment by xmatthias** [comment]
well this comes directly out of scikit-optimize.

It suggests that your search-space has converged, so most likely, this hyperopt run will not find any much better results.

This does not necessarily mean "it can't get better" - just that this is a local minima hyperopt will most likely not find out again, as any move in any direction will cause results to worsen again.

**Comment by cgw-9527** [comment]
> well this comes directly out of scikit-optimize.
> 
> It suggests that your search-space has converged, so most likely, this hyperopt run will not find any much better results.
> 
> This does not necessarily mean "it can't get better" - just that this is a local minima hyperopt will most likely not find out again, as any move in any direction will cause results to worsen again.

How to deal with this problem? I stopped when I was training

**Comment by xmatthias** [comment]
As mentioned above, this error will not cause hyperopt to stop.
Comparing the times in your screenshot, the exception occurs "right away" - but hyperopt ran at least for 19 minutes (Elapsed time, bottom right corner).


If it stopped, there will have been other reasons - either you pressed ctrl+c, or the most likely cause if you didn't stop it - out of memory - so your operating system decided to kill this process.

**Comment by cgw-9527** [comment]
> As mentioned above, this error will not cause hyperopt to stop.
> Comparing the times in your screenshot, the exception occurs "right away" - but hyperopt ran at least for 19 minutes (Elapsed time, bottom right corner).
> 
> If it stopped, there will have been other reasons - either you pressed ctrl+c, or the most likely cause if you didn't stop it - out of memory - so your operating system decided to kill this process.

Thank you, I checked and it seems to be the problem
