### ISSUE TITLE
Double quote signs in test-pairlist

### ISSUE THREAD

**Issue by elisy** [freqtrade/freqtrade#3867]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.6.9 (`python -V`)
  * CCXT version: 1.35.22 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 1.34.59 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

While I am running command
freqtrade test-pairlist ...
I receive result in the following form:
Pairs for BTC: 
['ETH/BTC', 'LINK/BTC', 'XRP/BTC', ......

I cannot copy it and paste into json config file because '-sign is not valid for json string parameter. So I need to replace result into "-signs in a text editor.
I would like test-pairlist results in the form
["ETH/BTC", "LINK/BTC", "XRP/BTC", ......
to copy and paste into json config file.

**Comment by xmatthias** [comment]
I would recommend to use `freqtrade test-pairlist --print-json`.
That's exactly what it's there for.

**Comment by xmatthias** [comment]
I'll close this as i think the above answers your question.

Feel free to comment below if you still have questions.
