### ISSUE TITLE
plot buy and sell values 

### ISSUE THREAD

**Issue by macd2** [freqtrade/freqtrade#387]
* Python Version: 3.6 (`python -V`)
  * Branch: Develop
 
This is an improvement for : plot_dataframe.py

Assume we do only `(dataframe['mfi'] > 0)` now we only say value must be lower than `0` but we don't know exactly which value triggers the buy or sell. Can we plot the exact "trigger" values for buy and sell on to the indicators, or just mark them with a dot and display them on mouse over?

**Comment by macd2** [comment]
this issue can be closed since we have it in the new plot

**Comment by xmatthias** [comment]
it's in the `plot_dataframe.py`script now - therefore closing this issue.
