### ISSUE TITLE
getting NaNs in buy and sell columns in dry run mode

### ISSUE THREAD

**Issue by yarinbar** [freqtrade/freqtrade#3872]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.7(`python -V`)
  * CCXT version: 1.34.40(`pip freeze | grep ccxt`)`
  * Freqtrade Version: 2020.9.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I have been trying to run my strategy in dry run mode  and i noticed the bot didnt make any trades.
Ive gone through the doc and ruled out forward looking in my strategy since i use `rolling` and built in `talib` methods.

I printed the dataframe i work with in the dry run and i noticed that the `buy` and `sell` columns are populated with NaNs  whereas in the backtest they were filled with 0s. 

Why does it happen and would it impact the bot behavior?

**Comment by xmatthias** [comment]
Freqtrade looks for 1 in both `buy` and `sell` column.

0 or nan can be seen as the same (even though it's not) - as freqtrade ignores both  of these values.
