### ISSUE TITLE
`Error: cannot unpack non-iterable TimeoutError object` when downloading data

### ISSUE THREAD

**Issue by jafarlihi** [freqtrade/freqtrade#3883]
## Describe your environment

  * Operating system: Arch Linux
  * Python Version: 3.8.6 (`python -V`)
  * CCXT version: Whatever `freqtrade:stable` image provides (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.9.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Describe the problem:

When attempting to download 1m data for long periods of time, the process runs for a while then randomly crashes with this:
```
2020-10-22 16:32:12,697 - freqtrade.exchange.exchange - DEBUG - Done fetching pair BTC/USDT, interval 1m ...
2020-10-22 16:32:12,908 - freqtrade.exchange.exchange - DEBUG - Done fetching pair BTC/USDT, interval 1m ...
2020-10-22 16:32:13,087 - freqtrade.exchange.exchange - DEBUG - Done fetching pair BTC/USDT, interval 1m ...
2020-10-22 16:32:13,096 - freqtrade.data.history.history_utils - ERROR - Failed to download history data for pair: "BTC/USDT", timeframe: 1m. Error: cannot unpack non-iterable TimeoutError object
2020-10-22 16:32:13,282 - freqtrade.exchange.exchange - DEBUG - Exchange object destroyed, closing async loop
```

This happened for downloads that span longer periods of time. In few instances, I had to re-run the command and the download finished successfully -- but I can't seem to be doing the same with download that spans 2 years no matter how many times I restart.

### Steps to reproduce:

  1. Run `sudo docker-compose run --rm freqtrade download-data --pairs BTC/USDT --exchange binance --timerange 20190101-20190601 -t 1m -v`
  
### Observed Results:

Error was thrown. I expected data to be downloaded instead.

I guess the correct behavior would be to ignore the TimeoutError and re-try without failing whole download.

Might be related to #1491 and #1500

**Comment by xmatthias** [comment]
to fix the main part of the problem, you should use a configuration and specify an appropriate rate-limit
(for binance, the following works usually fine)

```
 "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
```
.

Now i suspected this part of the code to have a problem a while ago - but it never appeared when i've been runnign the bot - so it's difficult to fix it if it's not happening.

The above error should (hopefully) also include a stacktrace with line-numbers - that would be very helpful in order to fix this error (hopefully for good, this time).
