### ISSUE TITLE
Does backtesting take compounding into account?

### ISSUE THREAD

**Issue by c0d3r34d3r** [freqtrade/freqtrade#3887]
# Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.6 (`python -V`)
  * CCXT version: 11 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2019.9.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Say while backtesting it makes first trade and takes %20 profit. Do subsequent trades get calculated with 120% of stake amount as base investment or do they always just trade no more than the stake amount?

I'm aware of `"stake_amount": "unlimited"`, I'm just wondering how backtest results are calculated.
If you have `"stake_amount": "unlimited"` in your dry-run/live mode can you expect significantly higher returns than what is seen on backtesting because of compounding?

**Comment by xmatthias** [comment]
Backtesting does not support unlimited stake amount. It always takes what you're providing as "stake_amount" - without compounding.
