### ISSUE TITLE
Understanding hyperopting "Objective" results

### ISSUE THREAD

**Issue by rylos** [freqtrade/freqtrade#3893]
## Describe your environment

  * Operating system: Linux
  * Python Version: _3.8____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __dev__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
Just a quick question as title says...is -150 in objective to be considered a discrete/good/top result?
Thank you

**Comment by xmatthias** [comment]
The absolute value of the "objective" column in hyperopt output has no meaning other than to compare it to itself from a different epoch, since the calculation will differ greatly based on which [hyperopt-loss-function](https://www.freqtrade.io/en/latest/hyperopt/#loss-functions) is being used.

**Comment by xmatthias** [comment]
Going to close this as i think the documentation explains this pretty well.

Feel free to comment below if it's still unclear.
