### ISSUE TITLE
Running strategy_analysis_example Impossible to load Strategy 'BBRSI'

### ISSUE THREAD

**Issue by dyorepo** [freqtrade/freqtrade#3894]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.8.5 (`python -V`)
  * CCXT version: ccxt==1.36.66 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop-f6da9e35 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
Unable to run notebook : strategy_analysis_example

---------------------------------------------------------------------------

OperationalException: Impossible to load Strategy 'BBRSI'. This class does not exist or contains Python code errors.
### Steps to reproduce:

  1. Jupyter notebook
  2. Change the # Name of the strategy class
config["strategy"] = "BBRSI"
  3.Run the notebook 
  4. The strategy is placed in the user_data/strategies/bbrsi.py

  ```
  // paste your log here
  ```OperationalException                      Traceback (most recent call last)
<ipython-input-16-2ebbe0a4385b> in <module>
      1 # Load strategy using values set above
      2 from freqtrade.resolvers import StrategyResolver
----> 3 strategy = StrategyResolver.load_strategy(config)
      4 
      5 # Generate buy/sell signals using strategy

~/freqtrade/freqtrade/resolvers/strategy_resolver.py in load_strategy(config)
     43 
     44         strategy_name = config['strategy']
---> 45         strategy: IStrategy = StrategyResolver._load_strategy(
     46             strategy_name, config=config,
     47             extra_dir=config.get('strategy_path'))

~/freqtrade/freqtrade/resolvers/strategy_resolver.py in _load_strategy(strategy_name, config, extra_dir)
    189             return strategy
    190 
--> 191         raise OperationalException(
    192             f"Impossible to load Strategy '{strategy_name}'. This class does not exist "
    193             "or contains Python code errors."

OperationalException: Impossible to load Strategy 'BBRSI'. This class does not exist or contains Python code errors.

**Comment by xmatthias** [comment]
The message is pretty clear.
There is a problem with loading your strategy. 

This can have several reasons - maybe the class name is not `BBRSI`, but `BBRsi` (python is case sensitive)... or there are syntax errors in the class (mixed spaces and tabs, for example).
Maybe the strategy is using dependencies that are not installed in the virtual environment, or the path you're providing in `config['strategy_path']` is different to where the strategy is.

Especially the last point (location) should be reviewed carefully - as the correct `strategy_path` may not be `user_data/strategies` - but should be seen as relative to the jupyter notebook - so if the notebook is in `user_data/notebooks` - it might be `../strategies` (as said, difficult to tell as it'll depend where your notebook is running from).

The list is probably not complete - but i suspect it's one of the above reasons.
you'll most likely encounter the same when you run freqtrade (with this strategy) in the CLI.

**Comment by blockrationale** [comment]
freqtrade backtesting --strategy BBRSI works fine

**Comment by dyorepo** [comment]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-19-12fae82d8dc1> in <module>
     20 pair = "ETH_BTC"
     21 
---> 22 print(config['strategy_path'])

KeyError: 'strategy_path'

**Comment by dyorepo** [comment]
The notebook is running inside ~freqtrade/user_data/notebooks/strategy_analysis_example.ipynb

**Comment by xmatthias** [comment]
best set 'strategy_path' to the correct path, then before loading the strategy.

in your case that's most likely `config['strategy_path'] = Path('~freqtrade/user_data/strategies/')`

**Comment by raph92** [comment]
As another solution, you can change the directory using `os.chdir("../../")` so that the directory becomes `freqtrade/`.
That way freqtrade can correctly figure that your strategies are in `./user_data/strategies`

**Comment by blockrationale** [comment]
thanks will try these

**Comment by xmatthias** [comment]
I'll assume that the above did help you get going.

Feel free to comment below / reopen if this is still unclear.
