### ISSUE TITLE
Send hyperopt best result into a file

### ISSUE THREAD

**Issue by Chocamow** [freqtrade/freqtrade#3897]
## Describe your environment

  * Operating system: Mac OS 10.15.7
  * Python Version: 3.8.2
  * CCXT version: 1.33.52
  * Freqtrade Version: 2020.8
  
## Your question

Hello everyone, 

For a few hours now I'm trying to get the hyperopt best result into a file.

I've tried the --log-file option but it redirects logs only.

When I try redirecting the best result with '>' in my shell I only get the log too.

My question is: In which stream are you sending the best result? 

Even if I redirect both stdout and stderr to a file it doesn't work.

Thank's a lot!

**Comment by xmatthias** [comment]
results are sent to stdout.

however, there was a bug in one of the dependencies (#3750) used for output a while ago - which is most likely affecting your version and which caused redirection to be broken.

Best update your bot to the latest version (make sure to also update dependencies!), and let me know if it works then.

**Comment by Chocamow** [comment]
I update the bot and the dependencies, it works!

Thank's a lot.

**Comment by xmatthias** [comment]
Great, thanks for the feedback
