### ISSUE TITLE
Edge and config "use_sell_signal": false

### ISSUE THREAD

**Issue by rylos** [freqtrade/freqtrade#3900]
## Describe your environment

  * Operating system: _Ubuntu___
  * Python Version: __3.8___ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _dev___ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I've read the docs and  they says edge will override roi stoploss & trailing from config.
What if i want to use edge but no strategy sell signal....when freqtrade will sell the trade?
Thank you.

**Comment by xmatthias** [comment]
the only way for edge to sell a trade is via sell signal (or stoploss).

neither ROI nor trailing stoploss will apply - so if you're not using sell-signal, you cannot use edge - it will work technically - but you'll never have a pair, as the only trades edge can simulate are trades that end in stoploss (not trailing stoploss) - so you end up with an empty pairlist all the time.

To summarize:
want to use edge -> have a good, strong sell signal.
want to work without sell-signal -> don't use edge.

**Comment by rylos** [comment]
I've just tried enabling edge with some filters and leaving use_sell_signal: false in config.
When interrogating the pair list via telegram via /whitelist command  I get the current edge filtered pairlist (and it's correct). So I suppose trades will be done and just waiting for the edge stoploss and never sell in profit?
Maybe this can be blocked in some way.

**Comment by xmatthias** [comment]
Then maybe the sell-signal flag is not used correctly in edge.
We should probably have a filter that prevents using it this way, as it's really something that's not really desirable.

it'll mean that your pairlist (and position size and stoploss) is based on running edge on a **different** strategy than what you're really running (with sell-signal for edge vs. without sell signal for real trades).


in the end, this is a configuration/combination that is not supported, so i can only strongly advise against using it this way.
