### ISSUE TITLE
Failed building wheel for ninja

### ISSUE THREAD

**Issue by igormen2001** [freqtrade/freqtrade#3911]
I'm using Net Hunter on android and have troubles installing freqtrade

.
root@kali:/freqtrade# pip install -e .
Obtaining file:///freqtrade
Collecting ccxt>=1.24.96
  Using cached ccxt-1.37.10-py2.py3-none-any.whl (1.9 MB)
Collecting SQLAlchemy
  Using cached SQLAlchemy-1.3.20-cp37-cp37m-manylinux2014_aarch64.whl (1.3 MB)
Collecting python-telegram-bot
  Using cached python_telegram_bot-13.0-py2.py3-none-any.whl (404 kB)
Collecting arrow
  Using cached arrow-0.17.0-py2.py3-none-any.whl (50 kB)
Collecting cachetools
  Using cached cachetools-4.1.1-py3-none-any.whl (10 kB)
Collecting requests
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting urllib3
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting wrapt
  Using cached wrapt-1.12.1.tar.gz (27 kB)
Collecting jsonschema
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting TA-Lib
  Using cached TA-Lib-0.4.19.tar.gz (267 kB)
Collecting tabulate
  Using cached tabulate-0.8.7-py3-none-any.whl (24 kB)
Collecting pycoingecko
  Using cached pycoingecko-1.4.0-py3-none-any.whl (7.4 kB)
Collecting py_find_1st
  Using cached py_find_1st-1.1.4.tar.gz (8.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting python-rapidjson
  Using cached python-rapidjson-0.9.3.tar.gz (201 kB)
Collecting sdnotify
  Using cached sdnotify-0.3.2.tar.gz (2.5 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting jinja2
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting questionary
  Using cached questionary-1.7.0-py3-none-any.whl (33 kB)
Collecting prompt-toolkit
  Using cached prompt_toolkit-3.0.8-py3-none-any.whl (355 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/site-packages (from freqtrade===develop-a2626188) (1.19.3)
Collecting pandas
  Using cached pandas-1.1.4-cp37-cp37m-manylinux2014_aarch64.whl (9.4 MB)
Requirement already satisfied: tables in /usr/local/lib/python3.7/site-packages (from freqtrade===develop-a2626188) (3.6.1)
Collecting blosc
  Using cached blosc-1.9.2.tar.gz (816 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3 /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-roj37yx0/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake ninja
       cwd: None
  Complete output (48 lines):
  Collecting setuptools
    Using cached setuptools-50.3.2-py3-none-any.whl (785 kB)
  Collecting wheel
    Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
  Collecting scikit-build
    Using cached scikit_build-0.11.1-py2.py3-none-any.whl (72 kB)
  Collecting cmake
    Using cached cmake-3.18.2.post1-py3-none-manylinux2014_aarch64.whl (15.2 MB)
  Collecting ninja
    Using cached ninja-1.10.0.post2.tar.gz (25 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting packaging
    Using cached packaging-20.4-py2.py3-none-any.whl (37 kB)
  Collecting distro
    Using cached distro-1.5.0-py2.py3-none-any.whl (18 kB)
  Collecting six
    Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
  Collecting pyparsing>=2.0.2
    Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
  Building wheels for collected packages: ninja
    Building wheel for ninja (PEP 517): started
    Building wheel for ninja (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpgwqawgmf
         cwd: /tmp/pip-install-u59m6gg9/ninja
    Complete output (13 lines):
    Traceback (most recent call last):
      File "/usr/local/bin/cmake", line 5, in <module>
        from cmake import cmake
    ModuleNotFoundError: No module named 'cmake'
      File "/tmp/pip-build-env-c2lmolrm/overlay/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 560, in setup
        cmkr = cmaker.CMaker(cmake_executable)
      File "/tmp/pip-build-env-c2lmolrm/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 95, in __init__
        self.cmake_version = get_cmake_version(self.cmake_executable)
      File "/tmp/pip-build-env-c2lmolrm/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 82, in get_cmake_version
        "Problem with the CMake installation, aborting build. CMake executable is %s" % cmake_executable)
    Traceback (most recent call last):

    Problem with the CMake installation, aborting build. CMake executable is cmake
    ----------------------------------------
    ERROR: Failed building wheel for ninja
  Failed to build ninja
  ERROR: Could not build wheels for ninja which use PEP 517 and cannot be installed directly
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3 /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-roj37yx0/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake ninja Check the logs for full command output.
root@kali:/freqtrade#

I've spent couple days trying to solve the problem
Any help?

**Comment by xmatthias** [comment]
well you seem to miss cmake - how to get it to android / nethunter - best use google.

---

There's a few parts to this, and the combination of them lead me to close this issue:
* Android / Mobile is not a supported target for freqtrade - so it may or may not work, but it's up to the user to figure it out.
* This error is with installing a dependency, not with freqtrade directly. Best go to the project page of that failing dependency for support - maybe they support your platform - but most likely they're not as you're using a real edge-case platform.
* We're an open source project with people donating their free time to support other people and move the project further. This means we must focus our available time on supporting main platforms and main usecases - supporting edge-case usecases and plattforms (like nethunter / android ) will therefore not be possible.


I would suggest to use freqtrade on one of the suported platforms (best via docker) for a good user experience.


Thanks for your understanding
