### ISSUE TITLE
0 trades --dmmp [Backtesting-Hyperopt]

### ISSUE THREAD

**Issue by waresz** [freqtrade/freqtrade#3912]
## Describe your environment

  * Operating system: Centos 7
  * Python Version: 3.8
  * CCXT version: 1.36.85 
  * Freqtrade Version: 2020.10
  

## Describe the problem:

When --dmmp option is enabled in backtesting or hyperopt, there are no trades.  But when you don't run with that option, it works.

-> In the previous version it worked correctly.

**Comment by xmatthias** [comment]
Seems like it was introduced in #3845 - nothing too grave in my eyes though - as this is one of the "unrealistic" settings.

you can either switch to develop until the next release, or circumvent this problem by using `--max-open-trades 1000` (or even higher).

**Comment by waresz** [comment]
Thank you! What I'm trying to do is look at all trades, regardless of the limit (max-open-trades).
But you're right, setting a high limit is the same as "--dmmp".
