### ISSUE TITLE
Storing Rsi Value in strategy

### ISSUE THREAD

**Issue by 7kOz** [freqtrade/freqtrade#3915]
Hello Im just wondering how can i store an rsi value of an entry point based on other indicators to use that value later for exiting.

**Comment by xmatthias** [comment]
As stated in the [documentation](https://www.freqtrade.io/en/latest/strategy-customization/#storing-information) - you can store information.

What / when you store it is totally up to you, although i'd advise against storing full dataframes as this can lead to memory leaks.

Also - this "store" is not persisted across restarts, so please make sure that whatever reads this information can handle missing information.

**Comment by 7kOz** [comment]
thanks mate
