### ISSUE TITLE
Telegram Bot

### ISSUE THREAD

**Issue by tutecode** [freqtrade/freqtrade#3924]
How can I reset my bot telegram bot, so as not to set up another server?

I want to delete my previous tradings

**Comment by xmatthias** [comment]
i assume it's not about resetting the telegram bot, but resetting the trading bot itself.

In that case, best stop the bot, delete / move the database file (usually `tradesv3.sqlite` or `tradesv3.dryrun.sqlite`) and then start the bot again.

**Comment by tutecode** [comment]
Yes, I want to delete the database file, thank you!
