### ISSUE TITLE
freqtrade.plot.plotting - ERROR - Module plotly not found

### ISSUE THREAD

**Issue by jisnardo** [freqtrade/freqtrade#3927]
## Describe your environment

Latest docker image.
  
## Describe the problem:

https://www.freqtrade.io/en/latest/docker_quickstart/#plotting-with-docker-compose

2020-11-05 13:27:31,089 - freqtrade.plot.plotting - ERROR - Module plotly not found

### Steps to reproduce:

docker-compose run --rm freqtrade plot-dataframe --strategy BBRSI -p STORJ/ETH
  
### Observed Results:

ModuleNotFoundError: No module named 'plotly'

### Relevant code exceptions or logs

```
[jisnardo@host ftb_dev]$ docker-compose run --rm freqtrade plot-dataframe --strategy BBRSI -p STORJ/ETH
2020-11-05 13:27:31,089 - freqtrade.plot.plotting - ERROR - Module plotly not found
 Please install using `pip3 install plotly`
Traceback (most recent call last):
  File "/freqtrade/freqtrade/plot/plotting.py", line 26, in <module>
    from plotly.subplots import make_subplots
ModuleNotFoundError: No module named 'plotly'
```

**Comment by xmatthias** [comment]
While linking the docs - i don't think did switch to the `develop_plot` (or `stable_plot`) tag.

Only that image will include the plotting dependencies, so you'll need to edit your compose file to opt into this image. The default is for "running" the bot - which will not require the plot-libraries.

**Comment by zcythe** [comment]
Edit your Dockerfile.technical in your root folder, create one if it doesn't exist

Paste these inside
> FROM freqtradeorg/freqtrade
>
> RUN pip install git+https://github.com/freqtrade/technical
> RUN apt-get install git -y
> RUN pip install plotly
> RUN pip install technical
> RUN pip install git+https://github.com/freqtrade/technical

Then run the following command to rebuild docker:
docker build -t freqtrade -f docker/Dockerfile.technical .

After that you should be able to run freqtrade plot-dataframe.
Took me a while to figure it out, I hope it helps here.

**Comment by xmatthias** [comment]
@zcythe this applies if you need both technical and plotly.

Otherwise (just for plotly), using the pre-created docker images `freqtradeorg/freqtrade:develop_plot` or `freqtradeorg/freqtrade:stable_plot` should work just fine.

I think both above posts explain this issue, so i'm going to close this.
Feel free to reopen / comment below if it's you are still having problems.

**Comment by jisnardo** [comment]
Thanks @xmatthias

**Comment by mark-tanser** [comment]
How should I resolve this if using a mac M1 ?  

According to the docs I need to use the pre-created docker image: freqtradeorg/freqtrade:custom_arm64 
, but I see this same error:

Creating freqtrade_freqtrade_run ... done
2021-06-08 03:37:02,729 - freqtrade.plot.plotting - ERROR - Module plotly not found 
 Please install using `pip3 install plotly`
Traceback (most recent call last):
  File "/freqtrade/freqtrade/plot/plotting.py", line 25, in <module>
    import plotly.graph_objects as go
ModuleNotFoundError: No module named 'plotly'
ERROR: 1

Any help much appreciated, thanks!

**Comment by xmatthias** [comment]
you'll simply have to add `pip install --user plotly` to the dockerfile before building. 

It's not there by default as it's unneeded when running the bot. For reular platforms, we build a "*_plot" image - but building the image for ARM on CI is currently not possible.

**Comment by mark-tanser** [comment]
Thanks!

I thought that should have worked, but unfortunately still see the same. Did I miss a step somewhere in here?

step1 
I modified: Dockerfile.aarch64 , in this section:

WORKDIR /freqtrade

# Install dependencies
FROM base as python-deps
RUN  apt-get update \
  && apt-get -y install build-essential libssl-dev git libffi-dev libgfortran5 pkg-config cmake gcc \
  && apt-get clean \
  && pip install --upgrade pip \
  && pip install --user plotly

step 2. 
In terminal I input this command in freqtrade directory: 

docker-compose build

this ran with output as follows:

Building freqtrade
[+] Building 1077.5s (17/17) FINISHED                                                                                                                                                                       
 => [internal] load build definition from Dockerfile.aarch64                                                                                                                                           0.0s
 => => transferring dockerfile: 1.83kB                                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                      0.0s
 => => transferring context: 84B                                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/python:3.9.4-slim-buster                                                                                                                            0.0s
 => [internal] load build context                                                                                                                                                                      0.4s
 => => transferring context: 13.96MB                                                                                                                                                                   0.4s
 => [base 1/3] FROM docker.io/library/python:3.9.4-slim-buster                                                                                                                                         0.1s
 => [base 2/3] RUN mkdir /freqtrade   && apt-get update   && apt-get -y install sudo libatlas3-base curl sqlite3 libhdf5-serial-dev    && apt-get clean   && useradd -u 1000 -G sudo -U -m ftuser   &  8.9s
 => [base 3/3] WORKDIR /freqtrade                                                                                                                                                                      0.0s
 => [python-deps 1/5] RUN  apt-get update   && apt-get -y install build-essential libssl-dev git libffi-dev libgfortran5 pkg-config cmake gcc   && apt-get clean   && pip install --upgrade pip   &&  27.3s
 => [python-deps 2/5] COPY build_helpers/* /tmp/                                                                                                                                                       0.0s 
 => [python-deps 3/5] RUN cd /tmp && /tmp/install_ta-lib.sh && rm -r /tmp/*ta-lib*                                                                                                                    23.3s 
 => [python-deps 4/5] COPY --chown=ftuser:ftuser requirements.txt requirements-hyperopt.txt /freqtrade/                                                                                                0.0s 
 => [python-deps 5/5] RUN  pip install --user --no-cache-dir numpy   && pip install --user --no-cache-dir -r requirements-hyperopt.txt                                                              1008.5s 
 => [runtime-image 1/4] COPY --from=python-deps /usr/local/lib /usr/local/lib                                                                                                                          0.2s 
 => [runtime-image 2/4] COPY --from=python-deps --chown=ftuser:ftuser /home/ftuser/.local /home/ftuser/.local                                                                                          1.1s 
 => [runtime-image 3/4] COPY --chown=ftuser:ftuser . /freqtrade/                                                                                                                                       0.1s 
 => [runtime-image 4/4] RUN pip install -e . --user --no-cache-dir --no-build-isolation  && mkdir /freqtrade/user_data/   && freqtrade install-ui                                                      5.4s 
 => exporting to image                                                                                                                                                                                 1.7s 
 => => exporting layers                                                                                                                                                                                1.7s 
 => => writing image sha256:5986abb6a10cae81a79922cacf5f7ba6ed3c530eed8c6cbd180195198b90d659                                                                                                           0.0s 
 => => naming to docker.io/freqtradeorg/freqtrade:custom_arm64                                                                                                                                         0.0s 
                                                                                                                                                                                                            
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them  

step 3

from same Terminal I input command:

docker-compose run freqtrade plot-dataframe --strategy BTCUSDT_1

with output as follows:

Creating freqtrade_freqtrade_run ... done
2021-06-08 07:01:17,610 - freqtrade.plot.plotting - ERROR - Module plotly not found 
 Please install using `pip3 install plotly`
Traceback (most recent call last):
  File "/freqtrade/freqtrade/plot/plotting.py", line 25, in <module>
    import plotly.graph_objects as go
ModuleNotFoundError: No module named 'plotly'
ERROR: 1


what did I miss?

Thanks again!

**Comment by xmatthias** [comment]
i don't know?
personally, i'd add it to the very last step of the dockerfile (basically to the `runtime-image`) - as i'm not 100% certain what dependencies plotly has - so it might be possible that it installs some parts into other directories which are not moved between different stages.

**Comment by mark-tanser** [comment]
Awesome, that worked! Thanks very much. 

For anyone else stumbling across this issue, here's where I inserted the install command...


```
USER ftuser
# Install and execute
COPY --chown=ftuser:ftuser . /freqtrade/

RUN pip install -e . --user --no-cache-dir --no-build-isolation\
  && mkdir /freqtrade/user_data/ \
  && freqtrade install-ui

RUN pip install --user plotly

ENTRYPOINT ["freqtrade"]
# Default to trade mode
CMD [ "trade" ]
```

**Comment by ppkantorski** [comment]
I installed using the docker-compose command and docker image, and i'm getting the same issue.   What do I do with the commands listed below?  I am new to Docker, I understand what it is, but I am lost when it comes to how to install a pip module into a docker image.

> Awesome, that worked! Thanks very much.
> 
> For anyone else stumbling across this issue, here's where I inserted the install command...
> 
> ```
> USER ftuser
> # Install and execute
> COPY --chown=ftuser:ftuser . /freqtrade/
> 
> RUN pip install -e . --user --no-cache-dir --no-build-isolation\
>   && mkdir /freqtrade/user_data/ \
>   && freqtrade install-ui
> 
> RUN pip install --user plotly
> 
> ENTRYPOINT ["freqtrade"]
> # Default to trade mode
> CMD [ "trade" ]
> ```
