### ISSUE TITLE
All strategies are in heavy loss. Doing something wrong?

### ISSUE THREAD

**Issue by SebaSbs** [freqtrade/freqtrade#3930]
I just installed freqtrade (latest version 2020.10), then I downloaded 90 days of Binance history and backtested in bulk strategies from https://github.com/freqtrade/freqtrade-strategies repo. It turns out **all** strategies goes in very huge loss, between -100% and -2000%, not even one with positive profit. This seems very wrong, I think I'm doing something wrong.

I'm using the default Binance config file already included, is this normal to not have a single profit strategy from default configuration? I just added the API keys, saved as config.json and put strategies inside the strategies folder.

Any suggestion on how to debug this? I have no idea where to start debugging since here everything seems in very huge loss which is unlikely to happen.

Backtesting command:
`freqtrade backtesting --strategy-list ADXMomentum AdxSmas ASDTSRockwellTrading AverageStrategy AwesomeMacd BbandRsi BinHV27 BinHV45 CCIStrategy ClucMay72018 CMCWinner CofiBitStrategy CombinedBinHAndCluc EMASkipPump Low_BB MACDStrategy MACDStrategy_crossed Quickie Scalp TDSequentialStrategy --timeframe 5m
`

**Comment by mattneel** [comment]
The losses are expected, this isn't a magic money machine. You will need to put in a lot of time and work into your own strategies before you'll see any kind of sustained gains.

**Comment by moinonin** [comment]
It's understandable. Think of freqtrade as a tool where you test YOUR strategy and not find a ready one. Strategy can be as simple as keying in conventional indicators like RSI, ADX etc. If you don't get any different results, then you want to be more innovative. I recommend to you this white paper that used freqtrade as a test platform but with much recently developed indicators https://www.researchgate.net/publication/345313655_KryptoNHedge-WhitePaper#fullTextFileContent 
Applying that method, I got something promising - (
![btc1](https://user-images.githubusercontent.com/14851890/98459248-e166e400-21a1-11eb-8c5c-dded664a693d.png)
checkout the attached image)

**Comment by rylos** [comment]
Is there a way to have this indicator to try? Thank you

**Comment by zcythe** [comment]
> It's understandable. Think of freqtrade as a tool where you test YOUR strategy and not find a ready one. Strategy can be as simple as keying in conventional indicators like RSI, ADX etc. If you don't get any different results, then you want to be more innovative. I recommend to you this white paper that used freqtrade as a test platform but with much recently developed indicators https://www.researchgate.net/publication/345313655_KryptoNHedge-WhitePaper#fullTextFileContent
> Applying that method, I got something promising - (
> ![btc1](https://user-images.githubusercontent.com/14851890/98459248-e166e400-21a1-11eb-8c5c-dded664a693d.png)
> checkout the attached image)

I would be more than happy if you can shed some light on some equation in the whitepaper.
I have been cracking my head and read the whitepaper carefully for more than 5 times.
I find it hard to understand the equation derivation.
Can you kindly share some insight?
How to derivate the delta C and find out the Bid & Ask?

![FoxitReader_8KoFtFyHoC](https://user-images.githubusercontent.com/3666021/99148396-5f574d80-26c2-11eb-8dee-f753b1478895.jpg)

![FoxitReader_mmE7PHKON0](https://user-images.githubusercontent.com/3666021/99148400-61211100-26c2-11eb-8d71-8f73889de00a.jpg)

**Comment by zielichowski** [comment]
@moinonin Could you share how did you make backtesting with this strategy? As far as I understand we need bid and ask values. The doc says that: 

> The order book is not part of the historic data which means backtesting and hyperopt will not work correctly if this method is used

.
Thanks

**Comment by xmatthias** [comment]
@zielichowski the paper says explicitly that it's only using OHLCV data to get a +90% accuracy on predicting the spread - so i don't think that's needed.

I didn't go into the implementation details though - as it seems to only contain the raw math formulaes, but no python code ...

**Comment by jblestang** [comment]
A part of the process is
Not available in the paper IMHO

“Upon estimating the bid-ask spread from historical data, these values are then run through a rigorous pattern recognition attempting to replicate future (un-seen) sce- narios. Generating the buy-sell signals with EVX then become as simple as drawing a matrix between the asset’s asks, bids, and current (open and close) prices. The determinants of the matrix dictates whether it is worth-wile entering or exiting a trade. The following equations summarizes the buy-sell conditions:...”

**Comment by samatix** [comment]
Here is a recent [crypto trading survey](https://arxiv.org/pdf/2003.11352.pdf) to help with your strategy development

**Comment by xmatthias** [comment]
As explained above - freqtrade is not a magic money machine (i like that wording!) ... 

Creating a profitable strategy is hard work - and a strategy will also not be as simple as a "one off" development, and will most likely require ongoing finetuning as markets / market cycles change.


I'll close this as i don't think this'll lead to much, and I'd encourage discussion of the papers above in the [Discord server](https://discord.gg/MA9v74M) or in the [Slack channel](https://join.slack.com/t/highfrequencybot/shared_invite/zt-jaut7r4m-Y17k4x5mcQES9a9swKuxbg)
