### ISSUE TITLE
Undocumented setting to view current candle values

### ISSUE THREAD

**Issue by rylos** [freqtrade/freqtrade#3940]
## Describe your environment

  * Operating system: _linux___
  * Python Version: __3.8___ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _dev___ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

What is the undocumented setting to have the current candle values in the dataframe? (ok ok, I will handle repainting myself)
Thank you in advance

**Comment by xmatthias** [comment]
there is no undocumented setting for this. 
Incomplete candles are removed and not passed to the strategy.

If you need the current price, you can use [orderbook](https://www.freqtrade.io/en/latest/strategy-customization/#orderbookpair-maximum) or [ticker](https://www.freqtrade.io/en/latest/strategy-customization/#tickerpair) data.

**Comment by rylos** [comment]
Perfect, thank you.
