### ISSUE TITLE
Add customisable commands to Telegram bot keyboard

### ISSUE THREAD

**Issue by Killian-A** [freqtrade/freqtrade#3942]
## Describe your environment

Doesn't matter

## Describe the enhancement

I think it would be cool to have the ability to set custom commands to the bot's reply keyboard , for example i don't care about the /help one but i'd like to put the /forcesell all instead, so i can use it in one click.
Maybe it could be done on the config file in the Telegram section , by supplying an array of custom commands which would override the displayed ones ?

**Comment by xmatthias** [comment]
while technically possible for sure, i find it rather dangerous to add "breaking" action buttons (for example `/forcesell`) to the overview.
If you accidentally hit that button, it'll `/forcesell all` without further warning - which can lead to undesired / unexpected losses. 

By having users explicitly type it out - as that is a form of confirmation, not an accidental buttonpress.

At it's current state, /especially `/forcesell ` is not in the list intentionally for this reason.

**Comment by Killian-A** [comment]
That's a good point, but i thought that having to add it manually in the config file is a bit like " i understand the risks " thing.
But then, to keep things safe, there could be a "take profit" command, selling all positive trades ?

**Comment by xmatthias** [comment]
it depends on your usecase i guess - normally you wouldn't want to do this but trust the strategy.

otherwise, you may end up selling with 0.5% profit - but the strategy was right and keeping it would've made you a gain of 5-10% ... so now you've "lost" 4-9% of your profit ... just by clicking on a button ...

**Comment by DebarghyaDutta** [comment]
I was thinking of adding more options, such as changing dynamic whitelisting parameters (maybe sort by OI instead of volume), or maybe a separate button that displays requested plots.

**Comment by xmatthias** [comment]
@DebarghyaDutta pairlists must be done via the [pairlist provider](https://www.freqtrade.io/en/latest/developer/#pairlists) (link goes to the developer docs on how to write a new provider).

This has nothing to do with RPC messages directly - as it must work no matter if a user is looking at telegram or not. Telegram will only show you the current whitelist / current whitelist methods (and eventually blacklist pairs).


Regarding plots:
we will not be adding plotting capabilities to telegram. 
Creating the images reliably on different systems is quite difficult (and would most likely lead to reimplementation in different plotting frameworks - as i don't think plotly works well to generate static images) - and is honestly not worth the effort, as it will be heavily limited (you cannot send a interactive plot via telegram).

If you require plots, please check out [frequi](https://github.com/freqtrade/frequi/) - which is the web frontend that will provide plots. It's currently in early alpha (so it has rough edges, and may or may not work well) - but I try hard to make it a great experience.

**Comment by xmatthias** [comment]
@Killian-A i'm not strictly against the customizable list - but i'll not have time to implement this anytime soon.
If we can keep the current list (at least for now) as default (if not configured) - then i'd aporeciate if you're able to work on this and create a PR that will introduce this.

Obviously we'll need a check that only valid commands are provided - but i guess that'll then count as "implementation details"...

**Comment by Killian-A** [comment]
@xmatthias I might look into this when i'll have time , rn i'm kinda busy with work ^^"
But for anyone seeing this, it's really a nice first issue .
And of course if the params for custom commands are not set in the config.json they stay as their "default" state of right now

**Comment by MrKrautee** [comment]
working on this. 
https://github.com/freqtrade/freqtrade/compare/develop...MrKrautee:telegram
if im finished , I will add a pull request.
