### ISSUE TITLE
Regarding trailing and process_only_new_candles

### ISSUE THREAD

**Issue by Corfucinas** [freqtrade/freqtrade#3943]
Hi,

I'm running a swing strategy that runs on either the `1d` or `3d`  `timeframe`. 
Three things:

1) The backtests show that the strategy will not buy for a certain period, however, as soon as the bot started, it will buy, these signals cannot be found on the plot.

Does the `process_only_new_candles` affect this in any way?

2) The `trailing_stop_positive` of the strategy is about ~2%, I'm unaware of the strategy running at a `1d` or `3d` timeframe will take this into consideration when doing a `Hyperopt`. That is, does the Hyperopt will look into these price changes? 

3) For some reason the `avg duration` of the trades is showing as 0:00:00 for a lot of my backtests....is this normal?

 
![image](https://user-images.githubusercontent.com/53630064/99047712-8d0f9a00-25cf-11eb-901e-d45761a481f3.png)

**Comment by Corfucinas** [comment]
I went tru' the "assumptions made by backtesting", but still had those doubts, specially the odd thing regarding the 0:00:00 duration.

Is it possible to just adjust the trailing_space() in hyperopt_interface.py to just force the optimizer to look for higher values?

**Comment by xmatthias** [comment]
You can use the `AdvancedSampleHyperOpt` (generated automatically when creating a user directory) as sample, it includes a custom trailing space method.

the 0:00 is clear when using 2% with long timeframes - as it'll sell at the same candle.
your trailing parameters should be > than the average candle size - on 3d candles, 2% swings will almost always happen - so your backtest is basically worthless, as you'll not know what intra-candle movements the pair took.


Also, i'm sure that the signals will be there when the bot starts - maybe your plot_dataframe starts too late.
I don't think plotting considers startup-candles, as you'll very rarely be able to plot the full timerange you're backtesting anyway (although that assumption changes when you're using 1d candles).
