### ISSUE TITLE
Ta-Lib precision is 6 decimals instead of default 8

### ISSUE THREAD

**Issue by rylos** [freqtrade/freqtrade#3951]
## Describe your environment
(if applicable)

  * Operating system: _ubuntu___
  * Python Version: __3.8___ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _dev___ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

Is there a way to increase the precision of ta-lib to 8 decimals? A lot of indicators have low numbers on the default six digits and numbers are rounded or truncated that is not good on comparisons in strategy with low numbers....
(Using Binance)
From what I see, all dataframe is 6 decimals precision when I'm expecting 8 for correct calculations... (using crypto/BTC pairs)

Thank you.

**Comment by xmatthias** [comment]
i think you're mixing the calculation precision with the display precision.

Pandas uses 6 per default for output i think ... but you can change this for pandas by setting the pandas option
```
pd.set_option('precision', 8)
```

[source - pandas docs](https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html#frequently-used-options)

**Comment by rylos** [comment]
Sorry, seen it. Thank you very much.

**Comment by xmatthias** [comment]
:+1:
