### ISSUE TITLE
stoplos per time interval

### ISSUE THREAD

**Issue by macd2** [freqtrade/freqtrade#396]
* Python Version: 3.6
  * Branch: Develop
  * Last Commit ID: a799b7d  

Extend Stop loss with time Intervall like ROI
Example:
 "stoploss": -0.25 @ 0min, 
"stoploss": -0.15 @ 60min

**Comment by pan-long** [comment]
Duplicated with https://github.com/gcarq/freqtrade/issues/90

**Comment by gcarq** [comment]
Closing in favor of #90
