### ISSUE TITLE
Edge pairs validation

### ISSUE THREAD

**Issue by Sarimarcus** [freqtrade/freqtrade#3964]
## Describe your environment

  * Operating system: Debian
  * Python Version: Python 3.7.3
  * CCXT version: ccxt==1.37.69
  * Freqtrade Version: develop-bf6682d3 
 
## Your question

Hello everyone, I have a question about Edge Positioning. 

I have a StaticPairList of about 20 pairs, with the default edge configuration, and when I run Freqtrade, I have some pairs validated, for example : 

`Minimum expectancy and minimum winrate are met only for ['YFII/BNB', 'CTSI/BNB', 'BAND/BNB', 'ANKR/BNB', 'CRV/BNB', 'FIL/BNB'], so other pairs are filtered out.`

From the doc : 

> Edge Positioning control your strategy trade entry points, position side and, stoploss

I'm checking with /edge command on Telegram, everything is working fine. 

Then, each hour (_ 3600 process_throttle_secs_) Edge is ran again, and strategy configuration shoud be adjusted. But when I check again I have noticed that the validated pairs are never updated when Edge is ran. I have to /reload_config, in order to have pairs checked again, and entry points updated.

Is it a normal behaviour ? Don't you think it would be better if validated pairs could be adjusted each time Edge is run ?

Thank you for your help

**Comment by xmatthias** [comment]
edge will update the validated pairs if something changed.

However, depending on multiple factors (timeframe, how far back you look, how many trades are required, required expectancy) your pairs may or may not change within this timeframe - so the pairs can also remain identical eventally. Pairlist can also become empty at one point - which however is correct behaviour - and should happen again if you restart / reload right after that.


It's unclear to me from the above what you think isn't working - maybe including the logs which show this problem can help ... ?

**Comment by Sarimarcus** [comment]
> edge will update the validated pairs if something changed.

Well, I have the feeling that it only updates when reloading config. 
I'll try to get some logs soon.

**Comment by Sarimarcus** [comment]
OK, i've done additional testing, and actually, I think it's working fine. Pairs have been updated after Edge ran. 
Sorry about that !

**Comment by xmatthias** [comment]
Don't worry - it's important to get an understanding and verify.
Can be a bug, can be a "bug in understanding" ... 😆 either way - clarification is good 👍
