### ISSUE TITLE
 Stake-currency 'BTC' not compatible with pair-whitelist. 

### ISSUE THREAD

**Issue by Rokuyou** [freqtrade/freqtrade#3966]
* Operating system: Debian GNU/Linux 10 (buster)
  * Python Version: Python 3.8.2
  * CCXT version: 1.37.69
  * Freqtrade Version: 2020.10
  
Hello. Iḿ trying to run a dryrun with freqtrade using BTC on the kraken exchange. However, even after modyfing the pair whitelist, I still get the following error:

"Stake-currency 'BTC' not compatible with pair-whitelist. Please remove the following pairs: ['BTC/EUR']"

As far as I understand the documentation and the kraken specific configs, it should be the correct pair? 
I use the basic configuration which is autogenerated by freqtrade, only removing unwanted pairs from the whitelist. 
As strategy I use the Sample Strategy.

This is how I configured freqtrade:
 Do you want to enable Dry-run (simulated trades)?  Yes
? Please insert your stake currency: BTC
? Please insert your stake amount: 0.01
? Please insert max_open_trades (Integer or 'unlimited'): 3
? Please insert your desired timeframe (e.g. 5m): 5m
? Please insert your display Currency (for reporting): EUR
? Select exchange  kraken
? Do you want to enable Telegram?  No

Thank you in advance!

**Comment by xmatthias** [comment]
if you're using BTC/EUR, then EUR is your stake currency (you also need to have EUR in your account once you trade live).

to use BTC as stake currency, the pair can be ETH/BTC (for example).

**Comment by Rokuyou** [comment]
> 
> 
> if you're using BTC/EUR, then EUR is your stake currency (you also need to have EUR in your account once you trade live).
> 
> to use BTC as stake currency, the pair can be ETH/BTC (for example).

Thank you, I will try that

**Comment by xmatthias** [comment]
well, the assumption is that most exchanges offer only crypto pairs - which was correct when that part of the docs was written.

it sure could be rephrased as more exchanges now offer fiat pairs too - but obviously stake_amount is in stake_currency ... so you'd use 100 for Euro, as you cannot trade 0.1€ - at least on none of the exchange i use.
