### ISSUE TITLE
DryRun vs LiveRun

### ISSUE THREAD

**Issue by 7kOz** [freqtrade/freqtrade#3968]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*
While in dryrun the strategy is generating good returns as soon as i switch it to live mode returns decrease way much and some big losses start happening i tried it for like 2 days over and over with different strategies same thing happens does any one have an idea ?

**Comment by xmatthias** [comment]
markets change all the time - so in theory, what worked 2 days ago might not work today (especially this week ...).

With the information provided, it's almost impossible to determine what can cause this.
Most likely, you're seeing many cancelled buys / sells - which will mean that your pricing strategy is not working for your strategy - and buys / entries come late.

Dry-run assumes orders to be immediately filled - however that's not reality depending on which price you use for your orders.

**Comment by 7kOz** [comment]
my orders are all market orders and the switch between dry and live is within hours tried it for many times tho same thing dry wins i have been testing it for the past days switching off and on again same thing always its weird

**Comment by xmatthias** [comment]
Are you using the correct pricing strategy for market orders? [relevant documentation](https://www.freqtrade.io/en/latest/configuration/#market-order-pricing).

If not, then your prices are completely wrong in dry-run (not crossing the spread) - and ROI / stoploss calculations will also be wrong.

**Comment by 7kOz** [comment]
yes mate using the correct pricing but i dunno its really weird the results im getting from dry run and live

**Comment by xmatthias** [comment]
market orders are also always subject to slippage - which get's worse depending on the order size - so personally, i would not use these, as these give you NO control on the execution price.

**Comment by 7kOz** [comment]
okay thank you so much for the help
