### ISSUE TITLE
StaticPairList notification

### ISSUE THREAD

**Issue by vpotap** [freqtrade/freqtrade#3976]
Using last source and docker-compose for running when starting freqtrade (docker-compose up -d) don't see in telegram any pairlist info (pair_whitelist section is defined in config.json and not empty) only get msg "Searching for USDT pairs to buy and sell based on {'StaticPairList': 'StaticPairList'}", in docker-compose console also dont' see any information about pairlist for trading only freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/pairlist/StaticPairList.py'...
Is this expected behaviour  ?

**Comment by mattneel** [comment]
This is the expected behavior. You can use the `test-pairlist` subcommand to test out your pairlist before live or dry running, and use the `/whitelist` command in Telegram to see your pairlist while the bot is running.
