### ISSUE TITLE
Running freqtrade with docker not creating/not seeing the db file

### ISSUE THREAD

**Issue by NilanjanaBala** [freqtrade/freqtrade#3987]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker) : freqtrade 2020.10
  
## Your question

I am running freqtrade with docker image, in case of dry run trade, it suppose to create db file (tradesv3.dryrun.sqlite), but not seeing it into user_data directory. I could see my dry run my bot is working and could see notification on telegram too. Any pointer where does it keep the DB file? I am running trade manually (i.e. docker-compose run --rm freqtrade trade --config user_data/) not via docker up command.

version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./Dockerfile.technical"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
       -p 127.0.0.1:8080:8080

pls help

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
the docker-file is using a fixed database url - so it'll be as `user_data/tradesv3.sqlite` for both dry-run and live.

**Comment by NilanjanaBala** [comment]
@xmatthias, sorry actually i am not seeing that file with ls command. How can i copy that db file to other machine?

2020-11-23 14:25:29,435 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"

Looks the path showing as sqlite:///tradesv3.dryrun.sqlite, can i put into my "ft_userdata/user_data", where to configure. I am not seeing any file inside <docker_base_path>/ft_userdata/user_data

many thanks!

**Comment by xmatthias** [comment]
the default docker file includes the following line: `--db-url sqlite:////freqtrade/user_data/tradesv3.sqlite` - and also your shared section above includes this line.
This suggests that the file is created always under user_data - and always with the name tradesv3.sqlite.

Your log suggests that you're NOT using the docker-compose file (docker-compose-up) - but that you're running docker "somehow" differently.

What's the command you use to start freqtrade within the docker container?

**Comment by NilanjanaBala** [comment]
it worked thanks @xmatthias
