### ISSUE TITLE
Maxdrawdonw higher than 100%

### ISSUE THREAD

**Issue by Fimap9to1** [freqtrade/freqtrade#3988]
Hi, I'm backtesting a strategy and in the results i see "max drawdown" but don't understand what the bot means by that.

In https://www.freqtrade.io/en/latest/backtesting/ the explenantion is unclear to me: Maximum drawdown experienced. For example, the value of 50% means that from highest to subsequent lowest point, a 50% drop was experienced).

Now, I just want to ask if this drawdonw is the same calculated this way: 
MDD=Peak Value / (Trough Value−Peak Value​​)
Find it here: https://www.investopedia.com/terms/m/maximum-drawdown-mdd.asp#:~:text=Maximum%20drawdown%20(MDD)%20is%20a,down%20movements%20could%20be%20volatile

Which refers to total deposit.

In this case a max drawdown higher than 100% would mean loss of all capital. And no chance to get a positive return since we run out of money in the deposit at some point.

Now my issue is: the strategy returns a positive total profit in backtesting with a maxdrawdonw of 200%. What does this means?

**Comment by xmatthias** [comment]
Freqtrade backtesting will allow you to be broke in the middle, and will assume that there is sufficient "replacement-capital" available - so you can have a drawdown of 1000% - and still end up positive - but obviously you've lost greatly in between, and you'd most likely have switched of that strategy by then.

You can also use `freqtrade plot-profit` to visualize the max-drawdown - i think then it'll become clearer.

**Comment by Fimap9to1** [comment]
@xmatthias thankyou Matthias. Ho can it "waste" the whole deposit if the drawdown is based just on profits? Maybe you mean it can "waste" the whole profit?

**Comment by xmatthias** [comment]
Well, 100% would be wasted the whole profit. 1000% can be wasting the whole deposit - so i think it'll depend on the size of max drawdown.

As said before - use `freqtrade plot-profit` - and it'll become clear (the middle graph shows you profit - and max-drawdown start/stop times.

**Comment by xmatthias** [comment]
I'll assume this as answered.

Feel free to reopen / comment below if that's not the case.

**Comment by Fimap9to1** [comment]
Thanks, all clear! ;)
