### ISSUE TITLE
error doesn't get printed when trades fail to download

### ISSUE THREAD

**Issue by Samaoo** [freqtrade/freqtrade#3992]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.5
  * CCXT version: 1.38.13
  * Freqtrade Version: 2020.10
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

When trades fail to download, the error explaining why the trades failed to download doesn't get printed

### Steps to reproduce:

  1. run ```freqtrade download-data```
  2. disable your wifi so it fails to download
  3. It will print ```Failed to download historic trades for pair: "WAVES/EUR". Error:``` but it won't print the actual error

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
 2020-11-16 08:28:36,905 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair WAVES/EUR.
2020-11-16 08:28:36,911 - freqtrade.data.history.history_utils - INFO - Current Amount of trades: 0
2020-11-16 08:38:11,110 - freqtrade.data.history.history_utils - ERROR - Failed to download historic trades for pair: "WAVES/EUR". Error:
2020-11-16 08:38:11,110 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair XLM/EUR.
  ```

**Comment by Devicore** [comment]
I would like to precise that this Only happen in trade mode, back testing and downloading data work normally without any errors

**Comment by xmatthias** [comment]
@Devicore i doubt this is related to this issue - as this error cannot happen during trade mode.

**Comment by Devicore** [comment]
Yes it is happening in trade mode.  Try it and you will see.. even in dry mode the terror happens

**Comment by xmatthias** [comment]
@Devicore no it does not. trade mode does not use downloading of historic pairs.

**Comment by Devicore** [comment]
Well just try it and you will see, I use « freqtrade trade -s mystrategie » and I got this, but not on Binance or other exchange
