### ISSUE TITLE
NumPy 1.19.4 broken on Windows 10 2004

### ISSUE THREAD

**Issue by THETCR** [freqtrade/freqtrade#3995]
The latest version of NumPy is not suitable for the latest version of Windows 10.

Currently the only solution is to downgrade to 1.19.3

[More information can be found here](https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html)

**Comment by xmatthias** [comment]
I am aware of this issue - but honestly, i don't see how this affects Freqtrade directly.

We pin versions in requirements files, but not in setup.py - so you can downgrade numpy in your installation, run `pip install .` or so - and everything should work fine.

**Comment by mattneel** [comment]
I use Anaconda and MKL BLAS on Windows 10 personally. No issues.
`conda create -n mkl python numpy`

**Comment by THETCR** [comment]
@mattneel 
I don't see the link between your case and the issue reported. 

The issue for NumPy is with the MSVC compiler, 
Microsoft has confirmed it is fixed in the Insider Preview build 20270 and that they are currently on schedule to release it at the end of January 2021.

NumPy has implemented their own fix which is available in version 1.20.0 (currently in the RC stage).

**Comment by THETCR** [comment]
@xmatthias 

Downgrading Windows is not a suggestable solution in my opinion. There can be a lot of reasons why somebody needs the latest version etc.

It might not affect Freqtrade directly, but, Freqtrade says to it's users that it can be used on Windows and the requirements.txt suggests that NumPy 1.19.4 needs to be installed.

At least an issue like this should be present to inform users.

**Comment by xmatthias** [comment]
the freqtrade documentation also strongly recommends to use WSL/WSL2 (or docker) when using windows, and to ONLY use the direct windows installation when you have no easier way to run freqtrade, as installing ta-lib on windows is simply a pain (at least without the wheel).

**Comment by xmatthias** [comment]
Going to close this as numpy 1.19.5 (updated in #4171) supports windows fully again.
