### ISSUE TITLE
Order Buy Problem

### ISSUE THREAD

**Issue by tutecode** [freqtrade/freqtrade#3998]
I have two bots running on different servers in "dry-run", both contain all the cryptocurrency pairs in (USDT).

One of them doesn't work properly, sometimes he buys and sometimes he doesn't.

What could it be?

----------------------------------------------------------
Mode: Dry-run
Exchange: binance
Stake per trade: 50 USDT
Max open Trades: inf
Minimum ROI: {'0': 500}
Ask strategy: 
{"use_order_book": false, "order_book_min": 1, "order_book_max": 1, "use_sell_signal": true, "sell_profit_only": false, "ignore_roi_if_buy_signal": false, "price_side": "ask"}

Bid strategy: 
{"ask_last_balance": 0.0, "use_order_book": false, "order_book_top": 1, "check_depth_of_market": {"enabled": false, "bids_to_ask_delta": 1}, "price_side": "bid"}

Stoploss: -0.99
Timeframe: 4h
Strategy: Ichimoku_SenkouSpanCross
Current state: running

**Comment by xmatthias** [comment]
honestly i don't know what you'd expect with this kind of information.

"does not work" is not a valid description. 

What do the logs say? is everything identical? is it different strategies? what are the versions you're running?

**Comment by tutecode** [comment]
I will try to explain it.

My bot in the backtesting works fine.

But at the moment of executing it in real time. It may be that sometimes the cryptocurrency (x) gives a buy signal, theoretically, and does not make the purchase, could it be because just several cryptocurrencies gave buy signals, and of all it chose the best one?

Is there any of that in the documentation?

**Comment by xmatthias** [comment]
when multiple signals on different pairs happen on the same candle, freqtrade will buy until `max_open_trades` are exhausted - in the sequence of your pairlist (which can either be static or dynamic).

If it doesn't buy at all, you might run into one of the [common mistakes](https://www.freqtrade.io/en/latest/strategy-customization/#common-mistakes-when-developing-strategies) ... where you'd not get any signals in trade mode.

**Comment by tutecode** [comment]
I could solve it, I did not realize that it had a "tradable_balance_ratio" = 0.5
