### ISSUE TITLE
Process_only_new_candles and data from the data provider

### ISSUE THREAD

**Issue by Feianor** [freqtrade/freqtrade#4005]
## Describe your environment

  * Operating system: Ubuntu 18.04.4
  * Python Version: 3.6 (`python -V`)
  * CCXT version: 1.36.85 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.10 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I am very sorry to bother you, and firstly I'd like to express my gratitude for what you do.

My question is about the interaction between requesting data from the data provider and the process_only_new_candles option.

Since I had some problems with stoploss-on-exchange paired with trailing stoploss in live mode, I'm now testing a strategy using ordinary stoploss.
However, a whole iteration is needed before freqtrade checks again if the price has crossed the stoploss, so I am trying to reduce the iteration length as much as possible.

My strategy uses the current price, and compares it to some previous data, therefore, I don't need to process all the candles at every iteration, but it seems that, even placing ob = self.dp.orderbook(metadata['pair'], 1) in populate_buy_trend rather than in populate_indicators, i cannot get the currest best ask price without processing all the candles at each iteration.

It is intended to work this way? I thought that process_only_new_candles = True should only affect populate_indicators and nothing else.

Thank you very much for your time.

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
`process_only_new_candles=True` will affect all `populate*()` methods.
If the indicators don't change, then the buy / sell signal can't change either.

If you're using orderbook data and want the orderbook to be processed more than once per candle, then you must leave `process_only_new_candles=False`. Also orderbook is an indicator (an indicator is something that tells you to buy or sell - noone said that it must be RSI or MACD ...).

**Comment by xmatthias** [comment]
I'll assume this as answered.

Feel free to comment below / reopen if that's not the case.

**Comment by thunderwin** [comment]
process_only_new_candles = Ture will increase system pressure, since they recalculate the indicator like every 5 seconds?  I m not sure, how do it work.

**Comment by stash86** [comment]
1. Your statement is false
2. You can always test by printing things in log to see how it actually work
3. Open new issue if you have any question. Asking on old closed issue isn't the recommended way
