### ISSUE TITLE
[Backtesting] Total Profit % Report Inconsistent

### ISSUE THREAD

**Issue by mrsegen** [freqtrade/freqtrade#4008]
I raise this because of an inconsistency in backtesting output. I note that the same issue appears in [this backtesting example](https://www.freqtrade.io/en/latest/backtesting/#understand-the-backtesting-result). So this may be a misunderstanding on my part, but labels could be phrased in a way that doesn't overlap terms.

## Describe your environment

  * Operating system: Ubuntu 18.04.1 (WSL2 w/in Windows)
  * Python Version: Python 3.6.9
  * CCXT version: 1.36.85
  * Freqtrade Version: 2020.11
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Within backtesting output `Total Profit %` in SUMMARY METRICS matches `Cum Profit %` in BACKTESTING REPORT instead of `Tot Profit %`.

### Steps to reproduce:

  1. Download Binance data with `--timerange 20200201-20200331 -t 5m -p BTC/USDT`
  2. Backtest this dataset with the [AwesomeMacd strategy](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/AwesomeMacd.py)
  
### Observed Results:

  * What happened?
Output:
```
Result for strategy AwesomeMacd
============================================================ BACKTESTING REPORT ===========================================================
|     Pair |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Wins |   Draws |   Losses |
|----------+--------+----------------+----------------+-------------------+----------------+----------------+--------+---------+----------|
| BTC/USDT |    134 |          -0.06 |          -7.58 |       -2.65480401 |          -2.53 |        5:08:00 |     32 |       0 |      102 |
|    TOTAL |    134 |          -0.06 |          -7.58 |       -2.65480401 |          -2.53 |        5:08:00 |     32 |       0 |      102 |
====================================================== SELL REASON STATS =======================================================
|   Sell Reason |   Sells |   Wins |   Draws |   Losses |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |
|---------------+---------+--------+---------+----------+----------------+----------------+-------------------+----------------|
|   sell_signal |     130 |     28 |       0 |      102 |          -0.37 |         -47.54 |          -16.6548 |         -15.85 |
|           roi |       4 |      4 |       0 |        0 |           9.99 |          39.96 |           14      |          13.32 |
======================================================== LEFT OPEN TRADES REPORT ========================================================
|   Pair |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Wins |   Draws |   Losses |
|--------+--------+----------------+----------------+-------------------+----------------+----------------+--------+---------+----------|
|  TOTAL |      0 |           0.00 |           0.00 |        0.00000000 |           0.00 |           0:00 |      0 |       0 |        0 |
=============== SUMMARY METRICS ===============
| Metric                | Value               |
|-----------------------+---------------------|
| Backtesting from      | 2020-02-01 01:40:00 |
| Backtesting to        | 2020-03-31 00:00:00 |
| Max open trades       | 3                   |
|                       |                     |
| Total trades          | 134                 |
| First trade           | 2020-02-01 04:10:00 |
| First trade Pair      | BTC/USDT            |
| Total Profit %        | -7.58%              |
| Trades per day        | 2.31                |
| Best day              | 9.99%               |
| Worst day             | -6.17%              |
| Days win/draw/lose    | 17 / 2 / 40         |
| Avg. Duration Winners | 11:23:00            |
| Avg. Duration Loser   | 3:11:00             |
|                       |                     |
| Max Drawdown          | 32.13%              |
| Drawdown Start        | 2020-02-12 15:05:00 |
| Drawdown End          | 2020-03-16 03:30:00 |
| Market change         | -31.3%              |
===============================================
```

  * What did you expect to happen?
While I don't yet understand the intended difference between Total Profit and Cumulative Profit, I would have expected the 8th line under SUMMARY METRICS to read either:
```
| Cum Profit %          | -7.58%              |
```
or:
```
| Total Profit %        | -2.53%              |
```

**Comment by xmatthias** [comment]
You can see the difference in calculation for `Cum Profit %` and `Total Profit %` here:

https://github.com/freqtrade/freqtrade/blob/829a47b187136b514489f8459cbde9807f61c884/freqtrade/optimize/optimize_reports.py#L125-L126


* "Tot Profit %" will be the sum of all relative profits divided by `max_open_trades`
* "Cum Profit %" will be the sum of all relative profits (independent of `max_open_trades`)

I'd agree we should align this - but should we maybe show both rows in the Summary metrics?

**Comment by mrsegen** [comment]
Thanks for clarifying and pointing to where these are calculated.

I don't yet understand: What is the point of this metric...?:
> "Tot Profit %" will be the sum of all relative profits divided by max_open_trades

**Comment by xmatthias** [comment]
i guess the naming of this is kindof misleading... (had me look it up too ...)

assume you use USDT - and `max_open_trades=5, stake_amount=20`.
your total stake is now 100$ ... 

the "cum profit" will be the profit per stake - so if you have 100% cum profit, your actual gain is 20$.
the "Total profit" will be the overall  - so if you have 100% total profit, it will be 100$ (your cum-profit would in this case be ~500%).

In my opinion, both are important - and will allow tuning of `max_open_trades` (at least that's the idea)

**Comment by mrsegen** [comment]
In exploring a fix PR, I ran into some discrepancies between the stable branch (which I used to generate the quoted output) and the develop branch I was branching from. I may revisit once the dust settles on this.

I was thinking to rename "Total Profit %" to "Total Profit $ per Allowed Open Trade." Since that's really long, I was able to break it into two lines within the same cell like this: `Tot Profit % per\nAllowed Open Trade`.

**Comment by xmatthias** [comment]
well things move - and the differences "should" be smallish (i made some "random finds" of these yesterday after looking up the info for this issue ...) - but generally, branching off of develop is correct, as stable can be dated by up to a month.

**Comment by mrsegen** [comment]
It should have been that simple. However, the 20-04 build of Windows introduced a change to processing of `fmod` IIRC which prevents the version of numpy that's in requirements.txt from working correctly. So freqtrade isn't runnable within Windows - where I'm doing dev at the moment. (I was only able to make the other PR because I was running tests through WSL.)

Not insurmountable, just an excuse to focus elsewhere, honestly.

**Comment by mattneel** [comment]
https://docs.anaconda.com/mkl-optimizations/
Using the MKL BLAS on Windows with Anaconda passes the fmod() test in the newer versions of NumPy, and I use it daily.

**Comment by xmatthias** [comment]
using anaconda is one option, using a lower version of numpy is another (it's pinned in requirements, but not in setup.py - so downgrading numpy is another option).


Requirements files don't allow downgrading of one platform as far as i know - and "pure" windows is really an edge-case installation as far as i know (I don't know many who use it on windows without docker or WSL).

Installing on windows is hard enough (due to the c dependencies) so i think that most people will be using WSL (hopefully 2) anyway.

Anyway, i'd want to keep this issue focused on-topic - there's another topic about the numpy incompatibility already in #3995 
As said there, it's a numpy problem (introduced by microsoft) - not one of freqtrade directly.
