### ISSUE TITLE
configuration in the strategy - what am I doing wrong?

### ISSUE THREAD

**Issue by interSAP** [freqtrade/freqtrade#4010]
## Describe your environment

  * Operating system: Windows 10 pro, running freqtrade in a WSV 2 and Ubuntu 20.04
  * Python Version: 3.8.5
  * CCXT version: 1.38.13
  * Freqtrade Version: freqtrade develop
  
## Your question
I'm trying to move several parameters from config.json to a sample strategy. Specifically, I want to move 
    "stake_currency": "USD",
    "stake_amount": 0.01,

While I have been able to move timeframe without any issue, I get an error while executing the same backtesting command after moving the two parameters above.

What am I doing wrong?

Thanks

I refer to the following page:
https://www.freqtrade.io/en/latest/configuration/#parameters-in-the-strategy

## Steps to reproduce
with the following lines active in my config.json
`    "stake_currency": "USD",`
`    "stake_amount": 0.01,`
`     "tradable_balance_ratio": 0.99,`
`     "fiat_display_currency": "USD",`
` //    "timeframe": "1m",`

and the following change to Low_BB.py strategy
`    # Optimal timeframe for the strategy`
`    timeframe = '1m'`

`    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:`

I get the following result: after exectuting
`freqtrade backtesting --strategy Low_BB`
> 2020-11-28 08:41:26,673 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
> 2020-11-28 08:41:26,674 - freqtrade.loggers - INFO - Verbosity set to 0
> 2020-11-28 08:41:26,675 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
> 2020-11-28 08:41:26,675 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/crypto/user_data ...
> 2020-11-28 08:41:26,675 - freqtrade.configuration.configuration - INFO - Using data directory: /home/crypto/user_data/data/bitstamp ...
> 2020-11-28 08:41:26,676 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
> 2020-11-28 08:41:26,676 - freqtrade.configuration.check_exchange - WARNING - Exchange "bitstamp" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
> 2020-11-28 08:41:26,676 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
> 2020-11-28 08:41:26,676 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
> 2020-11-28 08:41:26,677 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
> 2020-11-28 08:41:26,677 - freqtrade.resolvers.exchange_resolver - INFO - No Bitstamp specific subclass found. Using the generic class instead.
> 2020-11-28 08:41:26,678 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
> 2020-11-28 08:41:26,678 - freqtrade.exchange.exchange - INFO - Using CCXT 1.38.13
> 2020-11-28 08:41:26,678 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
> 2020-11-28 08:41:26,681 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
> 2020-11-28 08:41:26,685 - freqtrade.exchange.exchange - INFO - Using Exchange "Bitstamp"
> 2020-11-28 08:41:27,834 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy Low_BB from '/home/crypto/user_data/strategies/Low_BB.py'...
> 2020-11-28 08:41:27,835 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USD.
> 2020-11-28 08:41:27,835 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.01.
> 2020-11-28 08:41:27,835 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
> 2020-11-28 08:41:27,835 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
> 2020-11-28 08:41:27,835 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
> 2020-11-28 08:41:27,835 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
> 2020-11-28 08:41:27,835 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.9, '1': 0.05, '10': 0.04, '15': 0.5}
> 2020-11-28 08:41:27,835 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1m
> 2020-11-28 08:41:27,835 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.015
> 2020-11-28 08:41:27,836 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
> 2020-11-28 08:41:27,836 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
> 2020-11-28 08:41:27,836 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
> 2020-11-28 08:41:27,836 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
> 2020-11-28 08:41:27,836 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
> 2020-11-28 08:41:27,836 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
> 2020-11-28 08:41:27,836 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USD
> 2020-11-28 08:41:27,836 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.01
> 2020-11-28 08:41:27,837 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
> 2020-11-28 08:41:27,837 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
> 2020-11-28 08:41:27,837 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
> 2020-11-28 08:41:27,837 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
> 2020-11-28 08:41:27,837 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
> 2020-11-28 08:41:27,837 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
> 2020-11-28 08:41:27,838 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
> 2020-11-28 08:41:27,840 - freqtrade - ERROR - No Pairlist Handlers defined

as expected, but If I change my config.json as
`//    "stake_currency": "USD",`
`//    "stake_amount": 0.01,`
`     "tradable_balance_ratio": 0.99,`
`     "fiat_display_currency": "USD",`
` //    "timeframe": "1m",`

and my Low_BB.py strategy with:
`    # Optimal timeframe for the strategy`
`     timeframe = '1m'`
`     stake_currency = "USD"`
`     stake_amount = 0.01`

after executing
`freqtrade backtesting --strategy Low_BB`
I get the following result:
> 2020-11-28 08:46:32,743 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
> 2020-11-28 08:46:32,744 - freqtrade.loggers - INFO - Verbosity set to 0
> 2020-11-28 08:46:32,744 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
> 2020-11-28 08:46:32,744 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/crypto/user_data ...
> 2020-11-28 08:46:32,744 - freqtrade.configuration.configuration - INFO - Using data directory: /home/crypto/user_data/data/bitstamp ...
> 2020-11-28 08:46:32,745 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
> 2020-11-28 08:46:32,745 - freqtrade.configuration.check_exchange - WARNING - Exchange "bitstamp" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
> 2020-11-28 08:46:32,745 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
> 2020-11-28 08:46:32,745 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
> 2020-11-28 08:46:32,746 - freqtrade - ERROR - Fatal exception!
> Traceback (most recent call last):
>   File "/home/crypto/freqtrade/freqtrade/main.py", line 37, in main
>     return_code = args['func'](args)
>   File "/home/crypto/freqtrade/freqtrade/commands/optimize_commands.py", line 44, in start_backtesting
>     config = setup_optimize_configuration(args, RunMode.BACKTEST)
>   File "/home/crypto/freqtrade/freqtrade/commands/optimize_commands.py", line 26, in setup_optimize_configuration
>     config['stake_amount'] == constants.UNLIMITED_STAKE_AMOUNT):
> KeyError: 'stake_amount'

So I'm not sure what am I doing wrong, as the documentation states:

> The following parameters can be set in either configuration file or strategy
> [..]
> timeframe
> [..]
> stake_currency
> stake_amount
> [..]

Thanks for your kind support

**Comment by mrsegen** [comment]
I don't know why _exactly_ the `KeyError: 'stake_amount'` is appearing. But you might try a larger `stake_amount`. With it set to 0.01, it means that every purchase will be of the amount $0.01. See: https://www.freqtrade.io/en/latest/configuration/#configuring-amount-per-trade

**Comment by interSAP** [comment]
`   stake_amount = 10`

tried: same result.

**Comment by xmatthias** [comment]
It does work fine for me - whee exactly within the strategy are you positioning the stake_amount line?

make sure it's a class level attribute (e.g.):

``` python
# ...

class CoolStrategy(IStrategy):
    stake_amount = 20
    timeframe = '5m' 
```

With this, it does load the stake-amount perfectly fine for me in trade mode.

---

Backtesting is slightly different - because backtesting allows you to backtest multiple strategies at once (which could all define a different stake-amount - making them non-comparable) - therefore backtesting does currently not support this parameter to be in the strategy only - however you can pass it as `--stake-amount 20`.

**Comment by interSAP** [comment]
yes, it's in the class.

Fair explanation. Note taken in terms of backtesting

thanks

**Comment by interSAP** [comment]
only one comment, for future releases:

as backtesting has two parameters for defining strategy(ies) to be backtested: --strategy and --strategy-list, a point of improvement could be to allow backtesting not to require stake-currency or stake-amount when only one strategy is defined.

just a thought.

**Comment by xmatthias** [comment]
I don't mind that, feel free to contribute if you see this as necessary. 

I see it as not necessary and implementing it as a waste of my time, as it will make the startup-logic quite complex as the sequence in which things happen must change depending on the parameter used.

Also, adding the relevant parameters is possible as command line arguments, if you must use it this way.
