### ISSUE TITLE
How do I rank assets in the pairList based on some alpha?

### ISSUE THREAD

**Issue by nikhgupta** [freqtrade/freqtrade#4011]
* Operating system: MacOS
  * Python Version: 3.8.3
  * CCXT version: 1.36.85
  * Freqtrade Version: 2020.10

I have searched for this in the docs, and also had a stab at it after viewing the related code, but could not find a robust way to rank a signal with other assets, e.g. I want to buy/sell the top 5 assets/pairs which have the widest %B width. I am adding a column for %B width in `populate_indicators`. Is this possible?

Effectively, I am looking for a hook similar to `bot_loop_start` after the dataframe has been populated using `analyze_pair` calls, so that I can operate on the dataframe for all pairs as a whole, and rank the assets based on indicators/columns.

**Comment by xmatthias** [comment]
such a hook does not exist - and honestly, i don't think it's wise to make buying of one pair dependent on all other pairs.

In theory, you can get the analyzed dataframe for all pairs from within the `populate*()` methods with `get_analyzed_dataframe()` - but you'll not know if it's the first or last pair you're analyzing.

**Comment by nikhgupta** [comment]
> such a hook does not exist - and honestly, i don't think it's wise to make buying of one pair dependent on all other pairs.
Honestly, this is useful for ranking assets based on an alpha, which is pretty common in trading. We have a universe of stocks, which we filter and then rank them based on some alphas - the top/bottom scorers/rankers are of interest for long/short calls.

> In theory, you can get the analyzed dataframe for all pairs from within the `populate*()` methods with `get_analyzed_dataframe()` - but you'll not know if it's the first or last pair you're analyzing.

I did exactly this. Within `populate_indicators` (and also, in `populate_buy_trend`), I looped through all `available pairs` which sets a boolean to know if this is the last pair we are analyzing, and afterwards, I used `get_analyzed_dataframe()` to get the df, but these df were empty - I don't understand why?

**Comment by xmatthias** [comment]
which mode did you try this with?
`get_analyzed_dataframe()` is not available in backtesting ... so i assume it'll return empty dataframes then (i guess we should error that case ...)

**Comment by nikhgupta** [comment]
Yeah, I used the function in backtesting. So, how can I do this in backtests then?

I have a fairly profitable strategy that I have been using with a custom library I developed, but lately, I am seeing negative growths and wanted to check if that is due to some updates I made to this library or because the market has changed. I am unable to dedicate a lot of time to this library now and wanted to shift to freqtrade, if possible. But to do that I first need to configure freqtrade, run backtests and analysis and finally, switch to Live Trading. I am stuck on backtests :/

**Comment by xmatthias** [comment]
the way backtesting works, what you're trying to do is most likely impossible.

Backtesting analyzes the full set of data at once - but in real mode, your pairs would alternate over time.

For backtesting, you should be able to do this with informative pairs (obviously recalculating the indicator each time) to replace `get_analyzed_dataframe()` functionality.

You'll still need to be careful as you can't loop, but need to do this in a vectorized way.

**Comment by nikhgupta** [comment]
> Backtesting analyzes the full set of data at once - but in real mode, your pairs would alternate over time.

Not sure what you mean by `pairs would alternate overtime`? And, still not clear on how I can rank assets.

Right now, freqtrade allows us to trade assets based on their time-series data (directional movement). If somehow, ranking instruments based on an indicator/alpha could be done (so that they can be compared to each other) - it would allow us to develop a whole new set of strategies and risk management.

For an example of risk management (and not a great one), let's say we have an indicator that ranks assets based on the Bollinger Band width over X candles. Now, one of my sell signal condition could be to sell assets which are in the first quarter of this indicator (top 25% that have the highest volatility), and one of the buy signal condition could be to buy assets which are in the lower 25% (and least volatile).

Of course, the primary use of ranking indicators is that they can be used to create market-neutral strategies (long the top 10% assets while short the bottom 10%)

**Comment by nikhgupta** [comment]
Oh, and yes, you can set a fixed value for comparing the indicator as opposed to a rank - but, a rank would work regardless of how volatile the overall market is (in the above example) v/s a fixed value wherein the cutoff value would need to be updated based on the current market condition. A highly volatile overall market would need a higher value, and then it starts becoming guess-work / hyperopt for that value.

**Comment by xmatthias** [comment]
During trading, you analyze all indicators at least once every candle - so pairs can alternate over time (you use different pairs over time).

Backtesting analyzes the full timerange in one go - so the changing of ranks must be done within the dataframe, in a vectorized way.
If you're able to do that - perfect - most likely, informative pairs are the way to go for backtesting.

If not - then your strategy is not backtestable. 
You can most likely still use dry-run and live for your strategy - but you cannot check beforehand if everything seems correct before dry-running the strategy - and depending on the timeframe, it can take a few days/weeks to identify that you got a mistake.

**Comment by nikhgupta** [comment]
I am using Pandas 0.23.4 (which is the last version that supported Panels), and therein the change of ranks can be calculated very easily using: `panel.loc[:, :, 'indicator'].rank(axis=1, pct=True)` - this is vectorized and populates data for ranks in one go for all time periods.

With the deprecation of Panels - I am not sure how to do so anymore. But, since the data is already there (all past candles), and since we only calculate rank once every candle, they can be vectorized.

I will try to make this work with informative pairs and will report back.

Also, I understand what you mean by pairs can alternate over time, but for this (ranking) to work we need to analyze all available pairs from the exchange/strategy - so, yes, VolumePairFilter would not work. But, then again, you can always use Volume as an `alpha` for ranking purpose, and discard the bottom 80% for generating buy or sell signals.

**Comment by xmatthias** [comment]
well in theory, you can just merge all together (so you have columns like `bbp_BTCUSDT, bbp_XRPUSDT` ) - then do a rank across these values (obviously assuming they are comparable) - assign that rank to the dataframe again, and use `(dataframe['rank'] < 5)` (or whatever) in the strategy.

**Comment by nikhgupta** [comment]
> well in theory, you can just merge all together (so you have columns like `bbp_BTCUSDT, bbp_XRPUSDT` ) - then do a rank across these values (obviously assuming they are comparable) - assign that rank to the dataframe again, and use `(dataframe['rank'] < 5)` (or whatever) in the strategy.

Good point. I will try to make this work.

**Comment by xmatthias** [comment]
I'll assume this as answered.

Feel free to comment below / reopen if it's still unclear.
