### ISSUE TITLE
Optimization ROI + stoploss or ROI + stoploss + trailing

### ISSUE THREAD

**Issue by mathias5986** [freqtrade/freqtrade#4018]
Hello,

I am currently optimizing the stoploss and ROI of one strategy and I have great results. However, if I include the trailing in the optimization, I still get great returns, but not as high as the other optimization.
Would you recommend to optimize the trailing too together with the ROI and stoploss and take a lower sharpe or should I continue with the strategy, only optimized by stoploss and ROI ? 

Another quick question: does the telegram bot take into account fees ? 

Cheers,
Mathias

**Comment by xmatthias** [comment]
the telegram bot is just a means of notification - it does not do anything other than sending messages.

That said - freqtrade (the python program) does consider default exchange fees for all non-live modes (dry-run, backtesting and hyperopt) - and will apply the really applied fees for real trading.

**Comment by mathias5986** [comment]
Thanks. Thus, if I am trading live (no dry run) and telegram sends me the following message:
**Profit: 1.50%**

I have 1.50% _net_ profit (fees already taken into account)?

**Comment by xmatthias** [comment]
yes, fees are already taken into account.
