### ISSUE TITLE
Impossible to use backtesting after setting stake_amount to unlimited in config

### ISSUE THREAD

**Issue by evenlund** [freqtrade/freqtrade#4019]
* Operating system: Lubuntu 20.04
  * Python Version: 3.8.5
  * CCXT version: 1.37.69
  * Freqtrade Version: freqtrade develop-22ff67c8
  
It is impossible to use backtesting without setting stake-amount to a fixed value in config-file. When setting the stake-amount to a fixed value 0.001 from "unlimited" I get the following error:

> raise ValidationError(jsonschema.exceptions.ValidationError: '0.001' does not match 'unlimited'

**Comment by xmatthias** [comment]
it's unclear what you're trying to do ... 

first of all - unlimited stake-amount is not supported in backtesting - you must configure a stake-amount (but it's only there for your convenience, all calculations are done in %, which turns the amount traded into something only in your mind (you made 1000 from 10 trades with 100$ stake, or 100$ from 10 trades 10$ does not change the strategy's worth).

Then - the validation error: please share a configuration that is causing this - as it's unclear what you mean with the following:
>  When setting the stake-amount to a fixed value 0.001 from "unlimited"

**Comment by evenlund** [comment]
Sorry if I made myself unclear: I am trying to go back and forth between dry running, trading and backtesting without too much hazzle. For dry run I usually run with "unlimited" stake amount. I know that I need to run with a fixed stake amount when backtesting, but when trying to edit the same config file used for dry run with a fixed stake amount (eg. 0.001) I get the mentioned error that I cannot fix without first deleting the database and possible regenerate the config file.

**Comment by xmatthias** [comment]
the database is irrelevant for backtesting - so that for sure is unnecessary.

for the config - the configuration will not care what the parameter was "before" - most likely, you're making some small mistake while switching back to 0.001 (most likely you keep quotes around the numbers - which makes it a string).

However, if you're not sharing a config that's not working (no API keys!), there is nothing other than guessing involved.

**Comment by evenlund** [comment]
You were correct - I had included the quotes around the value.
