### ISSUE TITLE
How to know in which state the strategy is running?

### ISSUE THREAD

**Issue by baont** [freqtrade/freqtrade#4021]
I see there is a state.py describes various states and running-modes. However after searching, i found no way a strategy know in which running mode it is running.
Should we implement this mechanism?

**Comment by xmatthias** [comment]
state.py defines different states.
the first (`State`) is irrelevant for the strategy, as it will only ever be called when in RUNNING mode.

the 2nd (`RunMode`) is available to the strategy through dataprovider (`self.dp.runmode.value in ('live', 'dry_run')`). 

there's no explicit point for this in the documentation - but it's used in the [strategy-orderbook](https://www.freqtrade.io/en/latest/strategy-customization/#orderbookpair-maximum) section.

**Comment by baont** [comment]
thank you for the answer, sorry for response this late :)
