### ISSUE TITLE
Question about Telegram bot /forcesell all function

### ISSUE THREAD

**Issue by grg909** [freqtrade/freqtrade#4023]
## Have you searched for similar issues before posting it?
Yes, I have check [doc about this](https://www.freqtrade.io/en/latest/faq/#is-there-a-setting-to-only-sell-the-coins-being-held-and-not-perform-anymore-buys), but when i use it, it doesn't work as expected.
## Describe your environment

  * Operating system: Mac
  * Python Version: python 3.7(`python -V`)
  * CCXT version: I use docker, I don't know
  * Freqtrade Version: 2020.10
  
## Your question
My want to sell all current coins and hope bot won't keep buying because there is a bad trend, but I found bot still keep buying after I use /forcesell all. It does not work as doc says, I can't find a way for user to use telegram to clear everything and stop buying:
If I use /stop firstly, then /forcesell can't work, if I use /forcesell all firstly, bot will buy something else. I just can't get out of market through it.
*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
you will need to use `/stopbuy` (prevent new buys) - followed by `/forcesell all`.

To reactivate the bot, either restart the instance - or (better most likely) - use `/reload_config` to reinitiate the bot without having to log into your server.

**Comment by grg909** [comment]
Thank you for explaining, I understood. But I think if [doc here](https://www.freqtrade.io/en/latest/faq/#is-there-a-setting-to-only-sell-the-coins-being-held-and-not-perform-anymore-buys) can include this, it will be better
