### ISSUE TITLE
Binance coin pairlist

### ISSUE THREAD

**Issue by mathias5986** [freqtrade/freqtrade#4027]
Hello,

Apparently, you get a fee discount if you have binance coins in your wallet. What should I add/change to the code below to make the binance coin not tradable ? 

 "pair_whitelist": [
        "ADA/BTC",
	"BAT/BTC",
	"BCH/BTC",
	"DASH/BTC",
	"EOS/BTC",
	"ETC/BTC",
	"ETH/BTC",
	"IOTA/BTC",
	"LINK/BTC",
	"LTC/BTC",
	"NEO/BTC",
	"NMR/BTC",
	"OMG/BTC",
	"PIVX/BTC",
	"QTUM/BTC",
	"STEEM/BTC",
	"TRX/BTC",
	"WAVES/BTC",
	"XEM/BTC",
	"XLM/BTC",
	"XMR/BTC",
	"XRP/BTC",
	"ZEC/BTC"
	],
        "pair_blacklist": ["BNB/BTC"]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 130,
            "sort_key": "quoteVolume",
            "refresh_period": 960
        },
        {"method": "AgeFilter", "min_days_listed": 10},
        {"method": "PrecisionFilter"},
        {"method": "PriceFilter", "low_price_ratio": 0.01, "min_price": 0.00000010},
        {"method": "SpreadFilter", "max_spread_ratio": 0.005}

**Comment by xmatthias** [comment]
using blacklist BNB/BTC will suffice as long as you're using BTC as stake currency.
The default config for binance does include a full BNB Blackist (at least complete at the time of filling it out) 

You will have to have this "use BNB for fees" enabled in your account settings too. I THINK it's on by default, but best doublecheck.

**Comment by mathias5986** [comment]
Yes, exactly. My BNB coins disappear in my wallet, but I haven't traded any BNB coin. So I guess Binance uses the BNB coins for decreasing their fees?

**Comment by xmatthias** [comment]
you will see this on binance in your trade overview (there should be a fee + fee currency column).
If it contains BNB fees, then your BNB balance will slowly decrease (this is expected depending on your BNB fee settings on the binance account page)

If you don't want to use BNB fees, you can disable this on the Binance webpage. Obviously you'll then pay the full fee binance applies for your account level.

For further questions related to this topic, best contact the binance support, or read the binance documentation.
