### ISSUE TITLE
Can I use two different strategies?

### ISSUE THREAD

**Issue by tutecode** [freqtrade/freqtrade#4028]
Can I use two different strategies, with the same USDT currency pairs, on the same Binance API?

**Comment by xmatthias** [comment]
you can use run 2 different bots with 2 different strategies.

Obviously you'll risk that the 2 strategies buy the same asset, which then increases your total risk - but i guess that's expected.

One way to separate these is via subaccounts (contact binance support to enable subaccounts), but it will also work with one account as long as you're using fixed stake amounts (stake_amount != unlimited).
