### ISSUE TITLE
Custom range for VolumePairList

### ISSUE THREAD

**Issue by Feianor** [freqtrade/freqtrade#4029]
## Describe your environment
  * Operating system: Ubuntu 18.04.4
  * Python Version: 3.6 (`python -V`)
  * CCXT version: 1.36.85 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.10 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hello everyone, I'd like to know if it is possible to specify a custom range of pairs within the VolumePairList configuration.
I'l try to give some context.

For the strategy I'm running in dry_run mode I've set certains stoploss and trailing_stop_positive_offset values.
However, they may be good for some pairs (let's say the top 10), while from the 11th to the 20th I'd like to give more room, since those pairs should have an higher volatility.
So I was thinking of running two different bots, with different configuration files. I may do what I need manually using two different static pairlists, but didn't find a way to do this using the VolumePairList. I apologize in advance if I missed an answer to a similar question.

Thank you.

**Comment by xmatthias** [comment]
volumepairlist does currently not allow you to select the "nth to mth" pair, it'll always pick the top X pairs.

**Comment by Feianor** [comment]
Thank you for your answer.
