### ISSUE TITLE
Arrow object has no attribute

### ISSUE THREAD

**Issue by Blackhawke** [freqtrade/freqtrade#4034]
Just did a pull, which said I was up to date, but when I restarted the bot, I got the following error and now the bot won't start:

/.env/lib/python3.6/site-packages/arrow/arrow.py", line 530, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Arrow' object has no attribute 'int_timestamp'

I changed _nothing_. The bot has been running flawlessly. Any ideas?

**Comment by xmatthias** [comment]
Whenever doing an upgrade, make sure to also upgrade dependencies (we show this in the release-notes ...)

You can fix this by either running `pip install -e .` - or `pip install -r requirements.txt` - which you should do each time you upgrade (in reality, you'll most likely do it when something breaks - but still, it's the FIRST step to take when you notice that something is broken and it points to a library).

The "broken" dependency is arrow (which is not broken at all if you have the right version), which we require now a specific min-version for - as they did change timestamp to int_timestamp - and will remove the previous behaviour with the next major version.

**Comment by xmatthias** [comment]
It's now also described in the [updating docmentation](https://www.freqtrade.io/en/latest/updating/)

but to be fair - i've just pushed this 2 minutes ago, prior to that this was only in the release logs, not in the documentation itself.

**Comment by Blackhawke** [comment]
ARG!!!

Thanks Matthias. Hopefully things will slow down soon and I'll be able to get back to helping you guys with those docs!

Anyway... Yup. That fixed it. Thanks!
