### ISSUE TITLE
Stop loss and trailing stop loss questions in backtesting and live trading

### ISSUE THREAD

**Issue by Hulkstance** [freqtrade/freqtrade#4036]
I just found the project and I have a few questions.

1. How does your backtesting simulate stop loss and trailing stop loss? High and Low wouldn't be that accurate compared to live trading.
2. How does your stop loss/ trailing stop loss actually work in live trading? Does it put a stop limit order and then cancels it and places it again once the price raises?

**Comment by xmatthias** [comment]
Sorry, wrong issue in that commit ... didn't want to close this.

1) Best refer to the backtesting documentation related to [assumptions](https://www.freqtrade.io/en/latest/backtesting/#assumptions-made-by-backtesting). 
2) freqtrade offers 2 methods for stoploss 
  - either on exchange (where a stoploss limit / stoploss market order is placed) - which is then updated regularily in case of trailing stoploss
  - and one off the exchange - where freqtrade handles this, and in case of a triggered stoploss, it'll place a limit or market order (can be configured).

**Comment by Hulkstance** [comment]
Thanks for the information! Closing the issue for now.
