### ISSUE TITLE
Download data to database instead of file

### ISSUE THREAD

**Issue by baont** [freqtrade/freqtrade#4042]
Currently data downloaded into text files which is very difficult to analyze and navigate. Do we intent to provide an option to download OHCLV data to a db system (can sql lite a feasible option) in the future?

**Comment by xmatthias** [comment]
freqtrade provides methods to load the ohlcv data, so i don't see where the difficulty would be.
Maybe, you didn't read the documentation, and therefore don't know about these methods - but a database wouldn't help in that case either.

We also provide not just json, but json, jsongz and hdf5 as available formats (with hdf5, reading is a lot faster than with json).

I don't see why we should support sql - there's 0 benefit for freqtrade other than increased complexity, as it'll be another set of code we need to first write, and then eventually maintain.

**Comment by baont** [comment]
i got it, thank you for your detailed reply
