### ISSUE TITLE
Using python environment variables for the exchange section of the configuration file

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#4043]
Hello,

Does anyone have an idea how this section of the configuration file can be tweaked to use something more secure? In my naivete I tried moving it to the strategy so I could try to fill out the sensitive information using python environment variables. As you can guess it didn't pan out. Any suggestions are welcome.     

 'exchange': {
        'name': 'binance',
        'key': 'api-key',
        'secret': 'api-secret',
        'ccxt_config': {'enableRateLimit': True},
        'ccxt_async_config': {
            'enableRateLimit': True,
            'rateLimit': 200
        }

**Comment by xmatthias** [comment]
an environment variable is in no means more secure than a configuration file. 

it'll always be in memory in clear-text - so having it on disk as well doesn't make matters worse (in fact, usually you'll store your environment variables in a .env file - so the difference is just the filename / extension / syntax, which is by no means more secure.


honestly, if you fear someone can read it from your disk / configuration file, you're screwed anyway, as that would mean your box is owned.

That said - the best way is to use multiple configuration files - where you have one for "all" settings, and the last is providing ONLY the secrets (the syntax/structure must be identical, but you can use a configuration that ONLY contains api_key / api_secret).


Exactly this usecase is covered in the documentation [here](https://www.freqtrade.io/en/latest/bot-usage/#how-to-use-multiple-configuration-files)

**Comment by moinonin** [comment]
much appreciated detail @xmatthias  :+1:
