### ISSUE TITLE
pthread.h - not found

### ISSUE THREAD

**Issue by swami-gk** [freqtrade/freqtrade#4049]
-- The C compiler identification is GNU 8.2.0
  -- The CXX compiler identification is GNU 8.2.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/MinGW/bin/gcc.exe - skipped
....
 -- Looking for pthread.h - not found

**Comment by xmatthias** [comment]
Please fill out the issue template.

Based on the current Issue, i'm not sure how this relates to freqtrade. 
If we don't get more information (Which includes the full, filled out issue template) i will close this issue within one day without further notice.
