### ISSUE TITLE
multiple data download 

### ISSUE THREAD

**Issue by macd2** [freqtrade/freqtrade#4050]
## Describe your environment

  * Operating system: ubuntu
  * Python Version: 3.6 (`python -V`)
  * CCXT version: latest docker  (`pip freeze | grep ccxt`)
  * Freqtrade Version: latest docker (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

Every single time the bot is started with edge it downloads new data even if the candle is set to 1h and you just restart within 1 minute the bot it still downloads data again. 
```
2020-12-09 12:54:58,802 - freqtrade.exchange.exchange - INFO - Downloaded data for ONG/USDT with length 21.
2020-12-09 12:54:59,032 - freqtrade.exchange.exchange - INFO - Downloaded data for HOT/USDT with length 21.
2020-12-09 12:54:59,267 - freqtrade.exchange.exchange - INFO - Downloaded data for ZIL/USDT with length 21.
2020-12-09 12:54:59,496 - freqtrade.exchange.exchange - INFO - Downloaded data for ZRX/USDT with length 21.
```
```
2020-12-09 12:58:32,895 - freqtrade.exchange.exchange - INFO - Downloaded data for NEAR/USDT with length 3.
2020-12-09 12:58:32,921 - freqtrade.data.history.history_utils - INFO - Download history data for pair: "FIL/USDT", timeframe: 15m and store in /freqtrade/user_data/data/binance.
```
 after that i get every time:
````
2020-12-09 12:58:42,176 - freqtrade.data.converter - INFO - Missing data fillup for CRV/USDT: before: 1007 - after: 1011
2020-12-09 12:58:42,203 - freqtrade.data.converter - INFO - Missing data fillup for SAND/USDT: before: 1007 - after: 1011
```

This data is just an example it happens for every pair in whitelist

**Comment by xmatthias** [comment]
> `Downloaded data for ZIL/USDT with length 21.`

This suggests that you're using additional pairlists, either `AgePairlist` (with a length of 21 days) - or `RangeStabilityFilter`, with the same.

If you're using edge, then you should only use `StaticPairlist` (and nothing else).

When edge is enabled, you should not configure additional pairlists (they will run but the results will be ignored, and only `'pair_whitelist'` will be considered).

We maybe should disallow this (so the bot fails to start) - but i don't think that download will come from edge, but from the pairlist (your log is truncated too much, so it's unclear - but edge does usually not download for 21 ... ).

**Comment by macd2** [comment]
Thanks for the replay.
I don't get the logic why the age filter should be an issues for edge?

Edge should get the pair list after it has been filtered. 

Maybe i want to trade edge with the volume pair list which would make perfect sense?

**Comment by xmatthias** [comment]
> Edge should get the pair list after it has been filtered.

Edge uses the 'pair_whitelist' directly from the configuration, and ignores all pairlists.

> Maybe i want to trade edge with the volume pair list which would make perfect sense?

Feel free to implement this and submit a Pull request. This is currently not implemented.

> i removed now all filters but it still try's to download new data even if it should not.

Now it's downloading the last 4 candles. Edge will ALWAYS try to update the data before it runs - so it will always download at least 2-4 candles to verify it's got the latest candles.
You cannot prevent this - and it's perfectly normal behaviour.

**Comment by macd2** [comment]
thanks for the clarification regarding the download.
 
Is there a reason that `Edge ... ignores all pairlists.`?

**Comment by xmatthias** [comment]
it's not implemented, and it's using `pair_whitelist` directly. I'm not sure if there was a particular reason not to - but the most likely cause is time.
Technically, edge is a pairlist provider itself ... so results might be unreliable when combining the 2 approaches.

i'm also not sure if it would be simple to add - but as i don't use edge personally, i'm sure to implement this myself anytime soon.

**Comment by macd2** [comment]
alright got ya!

**Comment by macd2** [comment]
sorry just gone one more. 
when the downloading is done than i get this:
````
2020-12-09 23:21:37,237 - freqtrade.edge.edge_positioning - INFO - Measuring data from 2020-12-01 23:00:00 up to 2020-12-09 21:00:00 (7 days)..
2020-12-09 23:21:38,088 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
```
and after that 

```
2020-12-09 23:21:44,904 - freqtrade.freqtradebot - INFO - Active pair whitelist is empty.
2020-12-09 23:21:49,902 - freqtrade.freqtradebot - INFO - Active pair whitelist is empty.
2020-12-09 23:21:54,907 - freqtrade.freqtradebot - INFO - Active pair whitelist is empty.
2020-12-09 23:21:59,910 - freqtrade.freqtradebot - INFO - Active pair whitelist is empty.
```

now as you can see edge saying it measures 7 days of data but 
1. the buy_trend function is never called and 
2. the time taken themes a bit short  from  `23:21:37,237` to `2020-12-09 23:21:38,088`

it looks like edge is rejecting all pairs straight away any idea why?

**Comment by xmatthias** [comment]
Best familiarize yourself with how edge work by studying [the edge documentation](https://www.freqtrade.io/en/latest/edge).

Edge will ONLY allow pairs in the whitelist that show minimum performance in the last 7 days (can be configured).
Obviously, this will highly depend on the timeframe you're using - so you might need to adjust this value to match your strategy's trading frequency ...

**Comment by macd2** [comment]
yes im absolutely aware if that but how can edge measure 30+ pairs in one second? 
i set for fun all the requirements to 0 nd still all pairs rejected

```
  "edge": {
    "enabled": true,
    "process_throttle_secs": 3600,
    "calculate_since_number_of_days": 7,
    "allowed_risk": 0.02,
     "stoploss_range_min": -0.01,
     "stoploss_range_max": -0.1,
     "stoploss_range_step": -0.01,
    "minimum_winrate": 0.0,
    "minimum_expectancy": 0.0,
    "min_trade_number": 10,
    "max_trade_duration_minute": 1440,
    "remove_pumps": false
  },
``` 
the strategy is on 15min so plenty of trades in 7 days.

**Comment by xmatthias** [comment]
> the strategy is on 15min so plenty of trades in 7 days.

this depends on the strategy and can not be generalized.

You can use `freqtrade edge` with the same configuration (over the last 7 days) to see what will be the outcome.
