### ISSUE TITLE
freqtrade backtesting killed

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4053]
Debian 10
Python 3.7.3
ccxt==1.38.55
freqtrade develop-058d40a7

While running the following command:

`freqtrade backtesting -c config.json --strategy freqtrade`

The following issue occurs:

![Greenshot 2020-12-09 22 08 34](https://user-images.githubusercontent.com/528302/101681806-68da9800-3a6b-11eb-9ba8-ba2885a92161.png)

What could be causing this issue?

Thanks

**Comment by xmatthias** [comment]
usually - out of memory

What's your timeframe, number of pairs, and memory (ram) avavilable?

**Comment by aristosv** [comment]
365 days, 212 pairs, 1GB RAM.
ok, I'll increase the RAM. It's a virtual machine.

**Comment by xmatthias** [comment]
i assume it's 1m or 5m timeframe ... with this amount of data - i would use something around 8-12Gb of RAM.

You can also work with swap-files to increase memory eventually.

**Comment by aristosv** [comment]
yes, its 5m. Got it, thanks.
