### ISSUE TITLE
Cancelling open buy Order for "coinpair". Reason: cancelled due to timeout, fully cancelled.

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4055]
Debian 10
Python 3.7.3
ccxt==1.38.55
freqtrade develop-058d40a7

I can only assume this is some misconfiguration on my end. Any idea why this is happening?

![123](https://user-images.githubusercontent.com/528302/101913859-3dbb8a00-3bcc-11eb-8774-4998191e296a.png)

**Comment by xmatthias** [comment]
well the default [pricing ](https://www.freqtrade.io/en/latest/configuration/#prices-used-for-orders) positions the order in the best spot at the same side of the spread.

The documentation linked does illusrated this quite well i think.
If your signal is now buying right when it takes off, you'll encounter cancellations, as price never "returns" to get you.
You can get around this by either reversing sides (and sticking to limit orders) - or by reversing sides and using market orders (which however have a higher risk profile, as you're not guaranteed an execution price).

Hope this makes sense.

**Comment by aristosv** [comment]
ok, thanks for the info.
