### ISSUE TITLE
store user data to trade record

### ISSUE THREAD

**Issue by baont** [freqtrade/freqtrade#4070]
Based on my experience, there is currently no way (or there is) to store a custom data field to a trade record in database. My suggestion is to add a new column call 'user_data', type string where user can store anything they want for that trade

**Comment by xmatthias** [comment]
For now, i don't see what value this would bring / what the usecase for this would be.

one of the big problems with this is that everyone will want to store something different, so whatever column we create, it'll be wrong tomorrow.

For you, a string will be ok.
someone else will need a integer / float - or will want to store a whole series of 20 values, or 200 values... which will not be covered by a string field (or will require odd logics to get it back to the right format, or the string is too short, or ...).
The risk of this method breaking (crashing) the bot when providing something wrong is quite high, as it'll only crash once the data is inserted into the database, not when you assign it.

If you can explain a valid usecase on where and how you'd use this (what you'd store there, where you would want to get this value "back"), maybe we can think about it.
But for now i'll treat this as a question, as i don't see a valid usecase that will also generalize well and benefit more strategies.

**Comment by baont** [comment]
> one of the big problems with this is that everyone will want to store something different, so whatever column we create, it'll be wrong tomorrow.

well, user could store a string and interpret it the way their want, like a json string



> If you can explain a valid usecase on where and how you'd use this (what you'd store there, where you would want to get this value "back"), maybe we can think about it

For my case, when i enter a trade, i want to store a custom value calculated based on many indicators, price... Then when i want to exit that trade, i will get that values and determine based on some more calculation. That's what i can think of for now

**Comment by xmatthias** [comment]
> well, user could store a string and interpret it the way their want, like a json string

a string field will be limited to a certain number of characters in most databases - so i don't think this will give you what you want - at least not with the flexibility you expect.
Using an unlimited string field is a risk - as we have many inexperienced users, which will bloat their database, which will make the database slow and will therefore risk performance (which in the end, is risking capital, as you can be late entering or exiting a trade).

Also (and more severly) - this approach will simply not work for backtesting (where a trade is not available when calculating the sell signal) - so it would break core functionality of freqtrade.
That's a limitation that almost no user will be able to work with.

**Comment by baont** [comment]
In backtest anh hyperopt, i must calculate them and store in a column. Which mean i have 2 versions of poulalate...indicators for live trading and backtesint/hyperopt. I guess my need is pretty rare...

**Comment by xmatthias** [comment]
honestly, your need can be covered by adding the data to the [stratgy itself](https://www.freqtrade.io/en/latest/strategy-customization/#storing-information).

Unless you have very long hold-times (or restart the bot frequently) - i don't see why this shouldn't work (and it's not limited by the datatypes we use for the database).

Obviously you'll need to be cautious with storing large information (like full dataframes) - as that would lead to memory leaks

**Comment by baont** [comment]
Thanks for your advice. I just want to store a couple of numbers per trade. I restart the bot frequently so will try to persist my information
