### ISSUE TITLE
Including api_server in docker-compose

### ISSUE THREAD

**Issue by willwillis** [freqtrade/freqtrade#4071]
Below is the docker-compose file I use to start freqtrade. I acknowledge this may be more of a docker question, so apologies if this is strictly a freqtrade question.

I've enabled the `api_server` in my config, and I've included `-p 127.0.0.1:8080:8080` as the very last line in the docker-compose file however I'm getting the following error: `freqtrade: error: unrecognized arguments: -p 127.0.0.1:8080:8080`

How exactly do I enable api_server using docker-compose?

```
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:master
    # image: freqtradeorg/freqtrade:develop
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./Dockerfile.technical"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Default command used when running `docker compose up`
    # orig sqlite file tradesv3
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/realmoney.sqlite
      --config /freqtrade/user_data/config.json
      --strategy MACDStrategy_crossed
```

with this added at the end

```-p 127.0.0.1:8080:8080```

**Comment by xmatthias** [comment]
well honestly - a simple google search for `docker-compose port forwarding` would've given you this result too:

You'll need to forward the port (ports goes at the sme level as volumes or command).

```
    ports:
      - "127.0.0.1:8080:8080"
```

You'll obviously also need to enable the API in the configuration, and make sure it's running on 0.0.0.0 so you can actually connect via docker.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
