### ISSUE TITLE
BUY signal wrong (dataframe by binance with wrong data sometime?)

### ISSUE THREAD

**Issue by rylos** [freqtrade/freqtrade#4077]
## Describe your environment

  * Operating system: __ubuntu 20.04__
  * Python Version: __3.8.5___ (`python -V`)
  * CCXT version: _1.39.33____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _develop___ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Sometimes, I get wrong buy signals and the bot buy a pair it should not.
Very simple example, I've a strategy that test if macdhist is > 0 then buy.
On mdt/usdt it bought when macdhist was -0.00000168. After some hours, I've seen the trade and I've printed dataframe data to analyze. Some new candles has arrived since then. The data is correct and macdhist is -0.00000168 for the wrong buy.
Is it possible that binance sends some "wrong" data sometimes so indicators can be wrong for this specific iteration and correct on the next iterations (like my printed dataframe later)?

This is making some wrong buys in random mode.

**Comment by xmatthias** [comment]
Not that i'd know off - but you should ask binance support, not here...
I do however doubt they do that - that would be highly misleading - and even crypto-exchanges would face some consequences from this...

I don't think they will do that - it'll more like have something to do with how you calculate the indicators - and maybe it's got a 2nd condition or something ... 


or you have 2 strategies with the same name, so the strategy running is not the one you're looking at (this is a very frequent problem!).

**Comment by rylos** [comment]
Just a single strategy file, macdhist calculated from ta-lib. It's really strange but it happens on a random basis. Currently the strategy is handling 190 pairs, and in 3 days I got 3 cases. The last one under my eyes. Printing the dataframe later will show correct values.
the buy signal is just (dataframe['macdhist'] > 0.0).
No clue.

**Comment by rylos** [comment]
I've discovered the error. Not freqtrade or binance problem....BUT i think we should warn users because:
I've installed freqrade & requirements on an amazon instance running ubuntu 20.04 ARM (aarch64) architecture; ok the problem is on ta-lib (compiled from sources) that on some circumstances calculates WRONG data (bollinger bands is good example of wrong data). So this results on wrong signals on random basis.

Reinstalled all on a x64 amazon istance with ubuntu 20.04 and the problem is resolved for good.

**Comment by xmatthias** [comment]
this would suggest that ta-lib was installed somehow in a faulty way?

maybe try to report this finding in the [ta-lib python wrapper](https://github.com/mrjbq7/ta-lib/) repository ... while it's not the 100% correct spot, its the best way to get support for ta-lib i know ... 

Maybe they have come across this before, and it's as simple as "change this compiler flag" or whatever ...

**Comment by rylos** [comment]
My mistake. Ta-lib is currently working well on my ARM aarch64 architecture.
The error was my miss to do the command `sed -i "s|0.00000001|0.000000000000000001 |g" src/ta_func/ta_utility.h`
Without this, I get some random -inf and +inf values on ta-lib calculations.

**Comment by xmatthias** [comment]
i suspect it'll be depending on the pair - but on low-priced pairs, this can for sure happen without this fix (on all architectures).

Anyway, thanks for updating us on this 👍 

I guess this will conclude this issue...
