### ISSUE TITLE
Possible to buy just on candle's open? 

### ISSUE THREAD

**Issue by Fimap9to1** [freqtrade/freqtrade#4078]
Hi, I'd like the bot to buy just on candles opening, I don't want it to open a new position intra candle basically.

How can I do that if possible? 

Thank you for you answer!

**Comment by Fimap9to1** [comment]
process_only_new_candles is enabled in the config file. But as far as I understood this works only with if another position has been opened/closed/is still open on the same candle. 

What I'd like to do is to buy just on candles opening. Not intra-candle, even if sells occurs during the current candle.

**Comment by xmatthias** [comment]
`process_only_new_candles`  does techncially work - but it's shortcomming is if a trade-slot is opened mid-candle due to another pair selling.

There are other approaches for this as discussed in #2423 ... 
but there's nothing builtin to freqtrade at the moment.

**Comment by rylos** [comment]
Is the callback confirm_trade_entry executed before the intracandle buy even if process_only_new_candles is set to true?
Just to know if I need to disable process_only_new_candles to have confirm_trade_entry  fired every 5 sec?
Thank you in advance

**Comment by xmatthias** [comment]
`confirm_trade_entry ` has nothing to do with `process_only_new_candles`.  
It's called whenever a buy signal is found, and a buy is initiated (right before the order is placed).

`process_only_new_candles` is there to prevent the bot from recalculating signals over and over again - it never had the intend to prevent intra-candle buys, that was just a side-effect.

**Comment by rylos** [comment]
Ok thank you very much. 
Is there a way to access the dataframe in the confirm_trade_entry callback?
What I would do, is read the last candle datetime to make a super fast calculation. 
If not possible, I will investigate other paths.

**Comment by xmatthias** [comment]
[the docs](https://www.freqtrade.io/en/latest/strategy-customization/#get_analyzed_dataframepair-timeframe) prove helpful as often .. ;)

**Comment by rylos** [comment]
Missed this function in the docs ;)
Perfect, it is exactly what I was looking for. Thank you as always.

**Comment by Fimap9to1** [comment]
Thank you!

**Comment by rodrigo-brito** [comment]
Hi @rylos, can you share the final `confirm_trade_entry` function?
My second question is about, backtesting, the process considers it?

**Comment by rodrigo-brito** [comment]
I tried something like this:
```python
    def confirm_trade_entry(self, pair: str, order_type: str, amount: float, rate: float,
                            time_in_force: str, **kwargs) -> bool:
        if self.dp:
            dataframe, last_updated = self.dp.get_analyzed_dataframe(pair=pair, timeframe=self.timeframe)
            if datetime.now() - last_updated > timedelta(minutes=10):
                return False
        
        return True
```

**Comment by xmatthias** [comment]
backtesting does not consider this the `confirm_trade_*` functions - but backtesting will only buy at candle open, never within the candle.
