### ISSUE TITLE
Docker-compose file for arm Jupyter Notebook

### ISSUE THREAD

**Issue by sethemis** [freqtrade/freqtrade#4079]
Is posible to use Jupyter notebook with arm because i see all _plot images x86.. Thanks

**Comment by xmatthias** [comment]
you should be able to build the image yourself by using the dockerfile within docker/ and changing the "FROM" to a ARM image.

We don't build it as i think it's an edge-case (and building for ARM takes forever already).
Most people will use a raspberry as a server, in a headless mode, so i don't think it's worth the effort  (and wait time in ci) at this moment.

**Comment by sethemis** [comment]
I saw this https://github.com/freqtrade/freqtrade/issues/3559 is very similar but is not for arm..

**Comment by xmatthias** [comment]
well there is a compose file in the docker folder: https://github.com/freqtrade/freqtrade/blob/develop/docker/docker-compose-jupyter.yml

What you'll need to change is how the image is build - so it's referring to the PI image and then installing needed additional dependencies.

**Comment by sethemis** [comment]
Ok but this come from docker/Dockerfile.jupyter & this from develop_plot (x86)

**Comment by xmatthias** [comment]
yeah - you'll need to change the Dockerfile.jupyter to use the develop_pi - and add plotly in there.

As said, raspberry + jupyter + plotting is a quite rare occurance i'd think ... haven't seen that yet

**Comment by sethemis** [comment]
you haven't seen that yet but mein electricity bill will appreciate.. ;)
sorry but this is too complicated, now come other errors
![image](https://user-images.githubusercontent.com/70799038/102533460-becfc100-40a5-11eb-9e61-a08aa37ac33a.png)

**Comment by xmatthias** [comment]
Please use code tags (tripple `) to post logs.

I will not read through screenshots of logs.

**Comment by sethemis** [comment]
Step 2/3 : RUN pip install jupyterlab --no-cache-dir    && pip install plotly==4                                                                                        .14.1
 ---> Running in b0888ba4266c
Collecting jupyterlab
  Downloading jupyterlab-2.2.9-py3-none-any.whl (7.9 MB)
Requirement already satisfied: jinja2>=2.10 in /root/.local/lib/python3.7/site-p                                                                                        ackages (from jupyterlab) (2.11.2)
Requirement already satisfied: tornado!=6.0.0,!=6.0.1,!=6.0.2 in /root/.local/li                                                                                        b/python3.7/site-packages (from jupyterlab) (6.1)
Requirement already satisfied: MarkupSafe>=0.23 in /root/.local/lib/python3.7/si                                                                                        te-packages (from jinja2>=2.10->jupyterlab) (1.1.1)
Collecting jupyterlab-server<2.0,>=1.1.5
  Downloading jupyterlab_server-1.2.0-py3-none-any.whl (29 kB)
Requirement already satisfied: jsonschema>=3.0.1 in /root/.local/lib/python3.7/s                                                                                        ite-packages (from jupyterlab-server<2.0,>=1.1.5->jupyterlab) (3.2.0)
Requirement already satisfied: requests in /root/.local/lib/python3.7/site-packa                                                                                        ges (from jupyterlab-server<2.0,>=1.1.5->jupyterlab) (2.25.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packa                                                                                        ges (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.5->jupyterlab) (51.0.0)
Requirement already satisfied: six>=1.11.0 in /root/.local/lib/python3.7/site-pa                                                                                        ckages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.5->jupyterlab) (1.15                                                                                        .0)
Requirement already satisfied: importlib-metadata in /root/.local/lib/python3.7/                                                                                        site-packages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.5->jupyterlab                                                                                        ) (3.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /root/.local/lib/python3.7/                                                                                        site-packages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.5->jupyterlab                                                                                        ) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in /root/.local/lib/python3.7/site-                                                                                        packages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.5->jupyterlab) (20                                                                                        .3.0)
Collecting notebook>=4.3.1
  Downloading notebook-6.1.5-py3-none-any.whl (9.5 MB)
Collecting jupyter-client>=5.3.4
  Downloading jupyter_client-6.1.7-py3-none-any.whl (108 kB)
Requirement already satisfied: python-dateutil>=2.1 in /root/.local/lib/python3.                                                                                        7/site-packages (from jupyter-client>=5.3.4->notebook>=4.3.1->jupyterlab) (2.8.1                                                                                        )
Collecting jupyter-core>=4.6.1
  Downloading jupyter_core-4.7.0-py3-none-any.whl (82 kB)
Collecting pyzmq>=17
  Downloading pyzmq-20.0.0.tar.gz (1.2 MB)
Collecting terminado>=0.8.3
  Downloading terminado-0.9.1-py3-none-any.whl (13 kB)
Collecting traitlets>=4.2.1
  Downloading traitlets-5.0.5-py3-none-any.whl (100 kB)
Collecting argon2-cffi
  Downloading argon2-cffi-20.1.0.tar.gz (1.8 MB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip ins                                                                                        tall --ignore-installed --no-user --prefix /tmp/pip-build-env-smq40yzt/overlay -                                                                                        -no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi                                                                                        .org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.0'
       cwd: None
  Complete output (128 lines):
  Collecting cffi>=1.0
    Downloading cffi-1.14.4.tar.gz (471 kB)
  Collecting wheel
    Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
  Collecting pycparser
    Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
  Collecting setuptools>=40.6.0
    Downloading setuptools-51.0.0-py3-none-any.whl (785 kB)
  Building wheels for collected packages: cffi
    Building wheel for cffi (setup.py): started
    Building wheel for cffi (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys                                                                                        .argv[0] = '"'"'/tmp/pip-install-rc2n2tte/cffi_5fe769162ff44486b7bab94559ac14c5/                                                                                        setup.py'"'"'; __file__='"'"'/tmp/pip-install-rc2n2tte/cffi_5fe769162ff44486b7ba                                                                                        b94559ac14c5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);c                                                                                        ode=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code,                                                                                         __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-t6okuoyv
         cwd: /tmp/pip-install-rc2n2tte/cffi_5fe769162ff44486b7bab94559ac14c5/
    Complete output (50 lines):
    unable to execute 'gcc': No such file or directory
    unable to execute 'gcc': No such file or directory

        No working compiler found, or bogus compiler options passed to
        the compiler from Python's standard "distutils" module.  See
        the error messages above.  Likely, the problem is not related
        to CFFI but generic to the setup.py of any Python package that
        tries to compile C code.  (Hints: on OS/X 10.8, for errors about
        -mno-fused-madd see http://stackoverflow.com/questions/22313407/
        Otherwise, see https://wiki.python.org/moin/CompLangPython or
        the IRC channel #python on irc.freenode.net.)

        Trying to continue anyway.  If you are trying to install CFFI from
        a build done in a different context, you can ignore this warning.

    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.7
    creating build/lib.linux-armv7l-3.7/cffi
    copying cffi/lock.py -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/error.py -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/model.py -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/cparser.py -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/pkgconfig.py -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/recompiler.py -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/api.py -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/verifier.py -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/commontypes.py -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/__init__.py -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/_embedding.h -> build/lib.linux-armv7l-3.7/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-3.7/cffi
    warning: build_py: byte-compiling is disabled, skipping.

    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-armv7l-3.7
    creating build/temp.linux-armv7l-3.7/c
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall                                                                                         -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/usr/local/include/python3.7m                                                                                         -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.7/c/_cffi_backend.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
    ERROR: Failed building wheel for cffi
    Running setup.py clean for cffi
  Failed to build cffi
  Installing collected packages: pycparser, wheel, setuptools, cffi
      Running setup.py install for cffi: started
      Running setup.py install for cffi: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; s                                                                                        ys.argv[0] = '"'"'/tmp/pip-install-rc2n2tte/cffi_5fe769162ff44486b7bab94559ac14c                                                                                        5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rc2n2tte/cffi_5fe769162ff44486b7                                                                                        bab94559ac14c5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__)                                                                                        ;code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code                                                                                        , __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-s5e4wjim/install-                                                                                        record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-smq40                                                                                        yzt/overlay --compile --install-headers /tmp/pip-build-env-smq40yzt/overlay/incl                                                                                        ude/python3.7m/cffi
           cwd: /tmp/pip-install-rc2n2tte/cffi_5fe769162ff44486b7bab94559ac14c5/
      Complete output (50 lines):
      unable to execute 'gcc': No such file or directory
      unable to execute 'gcc': No such file or directory

          No working compiler found, or bogus compiler options passed to
          the compiler from Python's standard "distutils" module.  See
          the error messages above.  Likely, the problem is not related
          to CFFI but generic to the setup.py of any Python package that
          tries to compile C code.  (Hints: on OS/X 10.8, for errors about
          -mno-fused-madd see http://stackoverflow.com/questions/22313407/
          Otherwise, see https://wiki.python.org/moin/CompLangPython or
          the IRC channel #python on irc.freenode.net.)

          Trying to continue anyway.  If you are trying to install CFFI from
          a build done in a different context, you can ignore this warning.

      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-3.7
      creating build/lib.linux-armv7l-3.7/cffi
      copying cffi/lock.py -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/error.py -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/model.py -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/vengine_gen.py -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/cparser.py -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/ffiplatform.py -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/pkgconfig.py -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/recompiler.py -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/api.py -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/verifier.py -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/commontypes.py -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/__init__.py -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/_cffi_include.h -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/parse_c_type.h -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/_embedding.h -> build/lib.linux-armv7l-3.7/cffi
      copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-3.7/cffi
      warning: build_py: byte-compiling is disabled, skipping.

      running build_ext
      building '_cffi_backend' extension
      creating build/temp.linux-armv7l-3.7
      creating build/temp.linux-armv7l-3.7/c
      gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wa                                                                                        ll -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/usr/local/include/python3.7                                                                                        m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.7/c/_cffi_backend.o
      unable to execute 'gcc': No such file or directory
      error: command 'gcc' failed with exit status 1
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'im                                                                                        port sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rc2n2tte/cff                                                                                        i_5fe769162ff44486b7bab94559ac14c5/setup.py'"'"'; __file__='"'"'/tmp/pip-install                                                                                        -rc2n2tte/cffi_5fe769162ff44486b7bab94559ac14c5/setup.py'"'"';f=getattr(tokenize                                                                                        , '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'                                                                                        "'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record                                                                                         /tmp/pip-record-s5e4wjim/install-record.txt --single-version-externally-managed                                                                                         --prefix /tmp/pip-build-env-smq40yzt/overlay --compile --install-headers /tmp/pi                                                                                        p-build-env-smq40yzt/overlay/include/python3.7m/cffi Check the logs for full com                                                                                        mand output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/                                                                                        lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /t                                                                                        mp/pip-build-env-smq40yzt/overlay --no-warn-script-location --no-binary :none: -                                                                                        -only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cf                                                                                        fi>=1.0' Check the logs for full command output.
ERROR: Service 'ft_jupyterlab' failed to build: The command '/bin/sh -c pip inst                                                                                        all jupyterlab --no-cache-dir    && pip install plotly==4.14.1' returned a non-z                                                                                        ero code: 1
[root@DietPi docker]# ERROR: Command errored out with exit status 1:
-bash: ERROR:: command not found

**Comment by xmatthias** [comment]
seems like it's lacking build dependencies. 
you'll be best off looking at the issues / documentation for the package that failed installing (in this case, cffi).

maybe installing build-deps `apt install build-essential` is enough ... maybe it's not.
we do however not provide support for installation-problems with build-dependencies - because in the end, it's either me googling or you googling.

**Comment by sethemis** [comment]
i was googling but really too complicate to find the solution, i have proof in rpi2,rpi4, or not work for me.. and with custom installation come this error again from pip-build-env-smq40yzt/overlay/incl ude/python3.7m/cffi .. the only thing work for me is the basis installation with (dry, real, backtesting module) .. 
Another way i was thinking about to use https://github.com/freqtrade/frequi and is it possible to connect with docker image from here?...is that similar to plot module+ jupyter from here?..

**Comment by xmatthias** [comment]
in theory you should be able to use the frequi docker image on a raspberry (i think both node and nginx provide a arm image out of the box, and it's not using anything special).

I've not tested this though, so feel free to open an issue in frequi with the relevant logs should building it on a raspberry not work.

**Comment by xmatthias** [comment]
I'm going to close this with the instruction on how to build the jupyter image on a rpi successfully.

As mentioned above, you're missing binary dependencies ...  the following docker file will work on a raspberry 
Please note that installation / build-process will take a while, as a lot of packages are not available as wheels.


Modify the file `docker/Dockerfile.jupyter`

``` docker
FROM freqtradeorg/freqtrade:develop_pi

RUN apt-get update && apt-get install build-essential libffi-dev -y

RUN pip install jupyterlab plotly --no-cache-dir

# Empty the ENTRYPOINT to allow all commands
ENTRYPOINT []
```

``` bash
# build:
docker-compose -f docker/docker-compose-jupyter.yml build

# run (from the docs)
docker-compose -f docker/docker-compose-jupyter.yml up
```

once it's running, the regular [docker-compose](https://www.freqtrade.io/en/latest/docker_quickstart/#data-analayis-using-docker-compose) instructions will work for running on a raspberry.

Depending if you use the raspberry UI or you're accessing the raspberry over the network, you may also need to change the exposed ports in the docker-compose file, as by default, we only allow connections from localhost - not from other network devices.
You can do this by changing `- "127.0.0.1:8888:8888"` to `- "8888:8888"` in the docker-compose file.

**Comment by sethemis** [comment]
Thanks! That's work for me.. but now i need the docker-compose.yml for frequi...
