### ISSUE TITLE
If I have two "strategies" in buy_trend separated by an OR, can I choose the buy signal coming from one to be filled first?

### ISSUE THREAD

**Issue by Fimap9to1** [freqtrade/freqtrade#4080]
Hello Matthias, I have two sets of "filters" in my buy trend separated by an OR, so let's make an assumpion.

We have a buy signal.
1) The buy signal come from selection 1 (OR)
2) The buy signal come from selection 2

This said, I'd like to make the bot buy first all the signals coming from selection 1 and, if spare slots are available for buy, fill them with signals coming from selection 2.

Please let me know if this is possible, I didn't find the answer yet. Something is explained here (https://www.freqtrade.io/en/latest/strategy-advanced/#derived-strategies) but maybe you can provide me with further information!

**Comment by xmatthias** [comment]
pairs are processed in the sequence they come out of the pairlists, the strategy has no influence on this.

**Comment by Fimap9to1** [comment]
Clear. There's any way to condition the pairlist sequence based on buy details?

**Comment by xmatthias** [comment]
no, it's 2 completely separate modules.

keep in mind that you will only generate buy signals for pairs in the pairlist ... so combining the two would never work.

**Comment by Fimap9to1** [comment]
Understood, thank you!

**Comment by xmatthias** [comment]
Closing this as i think the original question has been answered.

Feel free to comment below / reopen if it's still unclear.
