### ISSUE TITLE
modify the telegram buttons that send commands to the bot

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4081]
Debian 10
Python 3.7.3
ccxt==1.38.55
freqtrade develop-058d40a7

I am not sure if this is the right place to ask this, if it's not, let me know.

Is there a way to add/remove/modify the telegram buttons that send commands to the bot?

![buttons](https://user-images.githubusercontent.com/528302/102501677-5de4c080-4086-11eb-8392-9436be175592.png)

Thanks

**Comment by xmatthias** [comment]
There is currently no way to modify this.
#3942 proposes to allow the user to customize this - but i don't think anyone is working on that at the moment.

While changing the default we have now may or may not make sense - it must be optimized for portrait mode of a phone - which doesn't allow more buttons next to each other (it's already pretty cramped as is).

**Comment by aristosv** [comment]
Is it ok if I modify freqtrade/freqtrade/rpc/telegram.py ?
Or will I cause other issues?

I think it's this part

![keys](https://user-images.githubusercontent.com/528302/102503934-e8c6ba80-4088-11eb-95d3-a4b4c403fb51.png)

**Comment by xmatthias** [comment]
it's open source, you can modify whatever you want.

Should there be upstream changes to this (in this repository), then you might encounter problems with upgrades which you then need to figure out yourself.
