### ISSUE TITLE
TA-Lib installation error on random distribution

### ISSUE THREAD

**Issue by sobeit2020** [freqtrade/freqtrade#4085]
* Operating system:  ANTIX (Light Debian)
  * Python Version: 3.7.3 
  * CCXT version: 1.39.33
  * Freqtrade Version: freqtrade develop-b9f3410d (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  ## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. Setup two VirutalMachines in parrarel : one on ANTIX (Debian) second on Ubuntu
  2. Install all programs and packages: Virtualenv, TaLib. ./source. and recommended packages
  3. Use SampleStrategy and config.json (example) as a base
  4.
  
### Observed Results:

  * Program, runned in .venv, on Ubuntu works, on Debian brokes

### Relevant code exceptions or logs

#DEBIAN
```
$ freqtrade trade --strategy SampleStrategy
2020-12-18 07:08:13,735 - freqtrade.worker - INFO - Starting worker develop-b9f3410d
2020-12-18 07:08:13,735 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2020-12-18 07:08:13,736 - freqtrade.loggers - INFO - Verbosity set to 0
2020-12-18 07:08:13,736 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2020-12-18 07:08:13,736 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2020-12-18 07:08:13,736 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2020-12-18 07:08:13,736 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2020-12-18 07:08:13,742 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/black/freqtrade/user_data ...
2020-12-18 07:08:13,742 - freqtrade.configuration.directory_operations - INFO - Created data directory: None
2020-12-18 07:08:13,742 - freqtrade.configuration.configuration - INFO - Using data directory: /home/black/freqtrade/user_data/data/bittrex ...
2020-12-18 07:08:13,743 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-12-18 07:08:13,743 - freqtrade.configuration.check_exchange - INFO - Exchange "bittrex" is officially supported by the Freqtrade development team.
2020-12-18 07:08:13,743 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-12-18 07:08:13,743 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-b9f3410d
2020-12-18 07:08:13,758 - freqtrade.resolvers.iresolver - WARNING - Could not import /home/black/freqtrade/user_data/strategies/sample_strategy.py due to 'libta_lib.so.0: cannot open shared object file: No such file or directory'
2020-12-18 07:08:13,760 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'SampleStrategy'. This class does not exist or contains Python code errors.
2020-12-18 07:08:13,761 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/black/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/black/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/black/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/home/black/freqtrade/freqtrade/freqtradebot.py", line 66, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/home/black/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 47, in load_strategy
    extra_dir=config.get('strategy_path'))
  File "/home/black/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 203, in _load_strategy
    f"Impossible to load Strategy '{strategy_name}'. This class does not exist "
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'SampleStrategy'. This class does not exist or contains Python code errors.
```

**Comment by xmatthias** [comment]
According to the error, this has NOTHING to do with the system you're running on, but simply with the fact that you don't have the strategy you're loading (`SampleStrategy`) available.

This suggests that you didn't create the userdir (which is not a problem per se - but you won't have the sample files in the file then).

**Comment by sobeit2020** [comment]
$ tree
.
├── build_helpers
│   ├── install_ta-lib.sh
│   ├── install_windows.ps1
│   ├── publish_docker_pi.sh
│   ├── publish_docker.sh
│   ├── ta-lib-0.4.0-src.tar.gz
│   ├── TA_Lib-0.4.19-cp37-cp37m-win_amd64.whl
│   └── TA_Lib-0.4.19-cp38-cp38-win_amd64.whl
├── config_binance.json.example
├── config_full.json.example
├── config.jsoexample
├── config.json
├── config.json.example
├── config_kraken.json.example
├── CONTRIBUTING.md
├── datas to forum
├── docker
│   ├── docker-compose-jupyter.yml
│   ├── Dockerfile.develop
│   ├── Dockerfile.jupyter
│   ├── Dockerfile.plot
│   └── Dockerfile.technical
├── docker-compose.yml
├── Dockerfile
├── Dockerfile.armhf
├── docs
│   ├── advanced-hyperopt.md
│   ├── advanced-setup.md
│   ├── assets
│   │   ├── freqtrade-screenshot.png
│   │   ├── plot-dataframe2.png
│   │   ├── plot-dataframe.png
│   │   └── plot-profit.png
│   ├── backtesting.md
│   ├── bot-basics.md
│   ├── bot-usage.md
│   ├── configuration.md
│   ├── data-analysis.md
│   ├── data-download.md
│   ├── deprecated.md
│   ├── developer.md
│   ├── docker.md
│   ├── docker_quickstart.md
│   ├── edge.md
│   ├── exchanges.md
│   ├── faq.md
│   ├── hyperopt.md
│   ├── images
│   │   └── logo.png
│   ├── includes
│   │   ├── pairlists.md
│   │   └── protections.md
│   ├── index.md
│   ├── installation.md
│   ├── javascripts
│   │   └── config.js
│   ├── partials
│   │   └── header.html
│   ├── plotting.md
│   ├── plugins.md
│   ├── requirements-docs.txt
│   ├── rest-api.md
│   ├── sandbox-testing.md
│   ├── sql_cheatsheet.md
│   ├── stoploss.md
│   ├── strategy-advanced.md
│   ├── strategy_analysis_example.md
│   ├── strategy-customization.md
│   ├── stylesheets
│   │   └── ft.extra.css
│   ├── telegram-usage.md
│   ├── updating.md
│   ├── utils.md
│   ├── webhook-config.md
│   └── windows_installation.md
├── environment.yml
├── freqtrade
│   ├── commands
│   │   ├── arguments.py
│   │   ├── build_config_commands.py
│   │   ├── cli_options.py
│   │   ├── data_commands.py
│   │   ├── deploy_commands.py
│   │   ├── hyperopt_commands.py
│   │   ├── __init__.py
│   │   ├── list_commands.py
│   │   ├── optimize_commands.py
│   │   ├── pairlist_commands.py
│   │   ├── plot_commands.py
│   │   ├── __pycache__
│   │   │   ├── arguments.cpython-37.pyc
│   │   │   ├── build_config_commands.cpython-37.pyc
│   │   │   ├── cli_options.cpython-37.pyc
│   │   │   ├── data_commands.cpython-37.pyc
│   │   │   ├── deploy_commands.cpython-37.pyc
│   │   │   ├── hyperopt_commands.cpython-37.pyc
│   │   │   ├── __init__.cpython-37.pyc
│   │   │   ├── list_commands.cpython-37.pyc
│   │   │   ├── optimize_commands.cpython-37.pyc
│   │   │   ├── pairlist_commands.cpython-37.pyc
│   │   │   ├── plot_commands.cpython-37.pyc
│   │   │   └── trade_commands.cpython-37.pyc
│   │   └── trade_commands.py
│   ├── configuration
│   │   ├── check_exchange.py
│   │   ├── config_setup.py
│   │   ├── configuration.py
│   │   ├── config_validation.py
│   │   ├── deprecated_settings.py
│   │   ├── directory_operations.py
│   │   ├── __init__.py
│   │   ├── load_config.py
│   │   ├── __pycache__
│   │   │   ├── check_exchange.cpython-37.pyc
│   │   │   ├── config_setup.cpython-37.pyc
│   │   │   ├── configuration.cpython-37.pyc
│   │   │   ├── config_validation.cpython-37.pyc
│   │   │   ├── deprecated_settings.cpython-37.pyc
│   │   │   ├── directory_operations.cpython-37.pyc
│   │   │   ├── __init__.cpython-37.pyc
│   │   │   ├── load_config.cpython-37.pyc
│   │   │   └── timerange.cpython-37.pyc
│   │   └── timerange.py
│   ├── constants.py
│   ├── data
│   │   ├── btanalysis.py
│   │   ├── converter.py
│   │   ├── dataprovider.py
│   │   ├── history
│   │   │   ├── hdf5datahandler.py
│   │   │   ├── history_utils.py
│   │   │   ├── idatahandler.py
│   │   │   ├── __init__.py
│   │   │   ├── jsondatahandler.py
│   │   │   └── __pycache__
│   │   │       ├── history_utils.cpython-37.pyc
│   │   │       ├── idatahandler.cpython-37.pyc
│   │   │       └── __init__.cpython-37.pyc
│   │   ├── __init__.py
│   │   └── __pycache__
│   │       ├── btanalysis.cpython-37.pyc
│   │       ├── converter.cpython-37.pyc
│   │       ├── dataprovider.cpython-37.pyc
│   │       └── __init__.cpython-37.pyc
│   ├── edge
│   │   ├── edge_positioning.py
│   │   ├── __init__.py
│   │   └── __pycache__
│   │       ├── edge_positioning.cpython-37.pyc
│   │       └── __init__.cpython-37.pyc
│   ├── exceptions.py
│   ├── exchange
│   │   ├── bibox.py
│   │   ├── binance.py
│   │   ├── bittrex.py
│   │   ├── common.py
│   │   ├── exchange.py
│   │   ├── ftx.py
│   │   ├── __init__.py
│   │   ├── kraken.py
│   │   └── __pycache__
│   │       ├── bibox.cpython-37.pyc
│   │       ├── binance.cpython-37.pyc
│   │       ├── bittrex.cpython-37.pyc
│   │       ├── common.cpython-37.pyc
│   │       ├── exchange.cpython-37.pyc
│   │       ├── ftx.cpython-37.pyc
│   │       ├── __init__.cpython-37.pyc
│   │       └── kraken.cpython-37.pyc
│   ├── freqtradebot.py
│   ├── __init__.py
│   ├── loggers.py
│   ├── __main__.py
│   ├── main.py
│   ├── misc.py
│   ├── mixins
│   │   ├── __init__.py
│   │   ├── logging_mixin.py
│   │   └── __pycache__
│   │       ├── __init__.cpython-37.pyc
│   │       └── logging_mixin.cpython-37.pyc
│   ├── optimize
│   │   ├── backtesting.py
│   │   ├── default_hyperopt_loss.py
│   │   ├── edge_cli.py
│   │   ├── hyperopt_interface.py
│   │   ├── hyperopt_loss_interface.py
│   │   ├── hyperopt_loss_onlyprofit.py
│   │   ├── hyperopt_loss_sharpe_daily.py
│   │   ├── hyperopt_loss_sharpe.py
│   │   ├── hyperopt_loss_sortino_daily.py
│   │   ├── hyperopt_loss_sortino.py
│   │   ├── hyperopt.py
│   │   ├── __init__.py
│   │   └── optimize_reports.py
│   ├── pairlist
│   │   ├── AgeFilter.py
│   │   ├── __init__.py
│   │   ├── IPairList.py
│   │   ├── pairlistmanager.py
│   │   ├── PerformanceFilter.py
│   │   ├── PrecisionFilter.py
│   │   ├── PriceFilter.py
│   │   ├── __pycache__
│   │   │   ├── __init__.cpython-37.pyc
│   │   │   ├── IPairList.cpython-37.pyc
│   │   │   └── pairlistmanager.cpython-37.pyc
│   │   ├── rangestabilityfilter.py
│   │   ├── ShuffleFilter.py
│   │   ├── SpreadFilter.py
│   │   ├── StaticPairList.py
│   │   └── VolumePairList.py
│   ├── persistence
│   │   ├── __init__.py
│   │   ├── migrations.py
│   │   ├── models.py
│   │   ├── pairlock_middleware.py
│   │   └── __pycache__
│   │       ├── __init__.cpython-37.pyc
│   │       ├── migrations.cpython-37.pyc
│   │       ├── models.cpython-37.pyc
│   │       └── pairlock_middleware.cpython-37.pyc
│   ├── plot
│   │   ├── __init__.py
│   │   └── plotting.py
│   ├── plugins
│   │   ├── __init__.py
│   │   ├── protectionmanager.py
│   │   ├── protections
│   │   │   ├── cooldown_period.py
│   │   │   ├── __init__.py
│   │   │   ├── iprotection.py
│   │   │   ├── low_profit_pairs.py
│   │   │   ├── max_drawdown_protection.py
│   │   │   ├── __pycache__
│   │   │   │   ├── __init__.cpython-37.pyc
│   │   │   │   └── iprotection.cpython-37.pyc
│   │   │   └── stoploss_guard.py
│   │   └── __pycache__
│   │       ├── __init__.cpython-37.pyc
│   │       └── protectionmanager.cpython-37.pyc
│   ├── __pycache__
│   │   ├── constants.cpython-37.pyc
│   │   ├── exceptions.cpython-37.pyc
│   │   ├── freqtradebot.cpython-37.pyc
│   │   ├── __init__.cpython-37.pyc
│   │   ├── loggers.cpython-37.pyc
│   │   ├── main.cpython-37.pyc
│   │   ├── misc.cpython-37.pyc
│   │   ├── state.cpython-37.pyc
│   │   ├── wallets.cpython-37.pyc
│   │   └── worker.cpython-37.pyc
│   ├── resolvers
│   │   ├── exchange_resolver.py
│   │   ├── hyperopt_resolver.py
│   │   ├── __init__.py
│   │   ├── iresolver.py
│   │   ├── pairlist_resolver.py
│   │   ├── protection_resolver.py
│   │   ├── __pycache__
│   │   │   ├── exchange_resolver.cpython-37.pyc
│   │   │   ├── __init__.cpython-37.pyc
│   │   │   ├── iresolver.cpython-37.pyc
│   │   │   ├── pairlist_resolver.cpython-37.pyc
│   │   │   ├── protection_resolver.cpython-37.pyc
│   │   │   └── strategy_resolver.cpython-37.pyc
│   │   └── strategy_resolver.py
│   ├── rpc
│   │   ├── api_server.py
│   │   ├── fiat_convert.py
│   │   ├── __init__.py
│   │   ├── __pycache__
│   │   │   ├── fiat_convert.cpython-37.pyc
│   │   │   ├── __init__.cpython-37.pyc
│   │   │   ├── rpc.cpython-37.pyc
│   │   │   └── rpc_manager.cpython-37.pyc
│   │   ├── rpc_manager.py
│   │   ├── rpc.py
│   │   ├── telegram.py
│   │   └── webhook.py
│   ├── state.py
│   ├── strategy
│   │   ├── __init__.py
│   │   ├── interface.py
│   │   ├── __pycache__
│   │   │   ├── __init__.cpython-37.pyc
│   │   │   ├── interface.cpython-37.pyc
│   │   │   ├── strategy_helper.cpython-37.pyc
│   │   │   └── strategy_wrapper.cpython-37.pyc
│   │   ├── strategy_helper.py
│   │   └── strategy_wrapper.py
│   ├── templates
│   │   ├── base_config.json.j2
│   │   ├── base_hyperopt.py.j2
│   │   ├── base_strategy.py.j2
│   │   ├── sample_hyperopt_advanced.py
│   │   ├── sample_hyperopt_loss.py
│   │   ├── sample_hyperopt.py
│   │   ├── sample_strategy.py
│   │   ├── strategy_analysis_example.ipynb
│   │   └── subtemplates
│   │       ├── buy_trend_full.j2
│   │       ├── buy_trend_minimal.j2
│   │       ├── exchange_binance.j2
│   │       ├── exchange_bittrex.j2
│   │       ├── exchange_generic.j2
│   │       ├── exchange_kraken.j2
│   │       ├── hyperopt_buy_guards_full.j2
│   │       ├── hyperopt_buy_guards_minimal.j2
│   │       ├── hyperopt_buy_space_full.j2
│   │       ├── hyperopt_buy_space_minimal.j2
│   │       ├── hyperopt_sell_guards_full.j2
│   │       ├── hyperopt_sell_guards_minimal.j2
│   │       ├── hyperopt_sell_space_full.j2
│   │       ├── hyperopt_sell_space_minimal.j2
│   │       ├── indicators_full.j2
│   │       ├── indicators_minimal.j2
│   │       ├── plot_config_full.j2
│   │       ├── plot_config_minimal.j2
│   │       ├── sell_trend_full.j2
│   │       ├── sell_trend_minimal.j2
│   │       ├── strategy_methods_advanced.j2
│   │       └── strategy_methods_empty.j2
│   ├── vendor
│   │   ├── __init__.py
│   │   └── qtpylib
│   │       ├── indicators.py
│   │       └── __init__.py
│   ├── wallets.py
│   └── worker.py
├── freqtrade.egg-info
│   ├── dependency_links.txt
│   ├── entry_points.txt
│   ├── not-zip-safe
│   ├── PKG-INFO
│   ├── requires.txt
│   ├── SOURCES.txt
│   └── top_level.txt
├── freqtrade.service
├── freqtrade.service.watchdog
├── LICENSE
├── MANIFEST.in
├── mkdocs.yml
├── README.md
├── requirements-dev.txt
├── requirements-hyperopt.txt
├── requirements-plot.txt
├── requirements.txt
├── scripts
│   └── rest_client.py
├── setup.cfg
├── setup.py
├── setup.sh
├── tests
│   ├── commands
│   │   ├── __init__.py
│   │   ├── test_build_config.py
│   │   └── test_commands.py
│   ├── config_test_comments.json
│   ├── conftest.py
│   ├── conftest_trades.py
│   ├── data
│   │   ├── __init__.py
│   │   ├── test_btanalysis.py
│   │   ├── test_converter.py
│   │   ├── test_dataprovider.py
│   │   └── test_history.py
│   ├── edge
│   │   ├── __init__.py
│   │   └── test_edge.py
│   ├── exchange
│   │   ├── __init__.py
│   │   ├── test_binance.py
│   │   ├── test_exchange.py
│   │   ├── test_ftx.py
│   │   └── test_kraken.py
│   ├── __init__.py
│   ├── optimize
│   │   ├── conftest.py
│   │   ├── hyperopts
│   │   │   └── default_hyperopt.py
│   │   ├── __init__.py
│   │   ├── test_backtest_detail.py
│   │   ├── test_backtesting.py
│   │   ├── test_edge_cli.py
│   │   ├── test_hyperoptloss.py
│   │   ├── test_hyperopt.py
│   │   └── test_optimize_reports.py
│   ├── plugins
│   │   ├── __init__.py
│   │   ├── test_pairlist.py
│   │   ├── test_pairlocks.py
│   │   └── test_protections.py
│   ├── pytest.sh
│   ├── rpc
│   │   ├── __init__.py
│   │   ├── test_fiat_convert.py
│   │   ├── test_rpc_apiserver.py
│   │   ├── test_rpc_manager.py
│   │   ├── test_rpc.py
│   │   ├── test_rpc_telegram.py
│   │   └── test_rpc_webhook.py
│   ├── strategy
│   │   ├── __init__.py
│   │   ├── strats
│   │   │   ├── default_strategy.py
│   │   │   ├── failing_strategy.py
│   │   │   └── legacy_strategy.py
│   │   ├── test_default_strategy.py
│   │   ├── test_interface.py
│   │   ├── test_strategy_helpers.py
│   │   └── test_strategy.py
│   ├── test_arguments.py
│   ├── test_configuration.py
│   ├── testdata
│   │   ├── ADA_BTC-5m.json
│   │   ├── backtest-result_multistrat.json
│   │   ├── backtest-result_new.json
│   │   ├── backtest-result_test.json
│   │   ├── DASH_BTC-5m.json
│   │   ├── ETC_BTC-5m.json
│   │   ├── ETH_BTC-5m.json
│   │   ├── LTC_BTC-5m.json
│   │   ├── NXT_BTC-5m.json
│   │   ├── pairs.json
│   │   ├── TRX_BTC-5m.json
│   │   ├── UNITTEST_BTC-1m.json
│   │   ├── UNITTEST_BTC-30m.json
│   │   ├── UNITTEST_BTC-5m.h5
│   │   ├── UNITTEST_BTC-5m.json
│   │   ├── UNITTEST_BTC-8m.json
│   │   ├── UNITTEST_BTC-8m.json.gz
│   │   ├── XLM_BTC-5m.json
│   │   ├── XMR_BTC-5m.json
│   │   ├── XRP_ETH-1m.json
│   │   ├── XRP_ETH-5m.json
│   │   ├── XRP_ETH-trades.h5
│   │   ├── XRP_ETH-trades.json.gz
│   │   ├── XRP_OLD-trades.json.gz
│   │   └── ZEC_BTC-5m.json
│   ├── test_directory_operations.py
│   ├── test_docs.sh
│   ├── test_freqtradebot.py
│   ├── test_indicators.py
│   ├── test_integration.py
│   ├── test_main.py
│   ├── test_misc.py
│   ├── test_persistence.py
│   ├── test_plotting.py
│   ├── test_talib.py
│   ├── test_timerange.py
│   ├── test_wallets.py
│   └── test_worker.py
├── user_data
│   ├── backtest_results
│   ├── data
│   │   └── bittrex
│   ├── hyperopt_results
│   ├── hyperopts
│   ├── logs
│   ├── notebooks
│   ├── plot
│   └── strategies
│       ├── __pycache__
│       │   └── sample_strategy.cpython-37.pyc
│       └── sample_strategy.py
└── ussr
    ├── backtest_results
    ├── data
    ├── hyperopt_results
    ├── hyperopts
    │   ├── sample_hyperopt_advanced.py
    │   ├── sample_hyperopt_loss.py
    │   └── sample_hyperopt.py
    ├── logs
    ├── notebooks
    │   └── strategy_analysis_example.ipynb
    ├── plot
    └── strategies
        └── sample_strategy.py

**Comment by xmatthias** [comment]
``
2020-12-18 07:08:13,758 - freqtrade.resolvers.iresolver - WARNING - Could not import /home/black/freqtrade/user_data/strategies/sample_strategy.py due to 'libta_lib.so.0: cannot open shared object file: No such file or directory'
```



Your installation is faulty / it's missing ta-lib.
You'll need to install the ta-lib C library first, then reinstall the python ta-lib library.

**Comment by sobeit2020** [comment]
Hey Xmatthias, thanks for your reply,

on the ANTIX OS,
I tried many approaches with Ta-Lib,  but my mistakes were like dog chasing its own tail. Failures keept coming back again and again.

What I did was two additional installs on VMs to check if UBUNTU like software works, 
ran my script of installation steps and 
what turned out is YES, THEY DO WORK: (ANTIX does no.)

XUBUNTU / lightweight and hopefully spayware-free (compared to Ubuntu) installation - it is my number ONE now for the mission, since it is Xfce;
MINT / one of the top www.distrowatch.com distros, it works same good.

The third was MANJARO, a very good looking distro, but this failed at the first steps of installing some Python programs, and then at Ta-Lib. I abandoned it because of this.

=====

The last other software  I could check is download DEBIAN 10 itself
to perform the installation and demo run there - it might fail, or it might run.

**Comment by xmatthias** [comment]
this is an installation problem of ta-lib (actually the c library) - not of freqtrade itself.

i'm sure ta-lib will support any distribution as long as the build-packages are installed. 
Generally, the expectation of users from non-mainstream distributions in the linux world is that they are able to search the web for installation errors and be able to install missing packages themselfs.
If that's not the case, then it's best to stick to main-stream distros (like ubuntu), which will be officially supported.

You also never provided any logs of the failures you're getting when installing ta-lib, as most likely it's simply a build-dependency that's missing. Most likely, copy/pasting the correct failure-message to google will fix this problem.

Either way - please understand that we cannot support random distributions - freqtrade will most likely work on everything that runs python 3.7+ if you're able to get the dependencies installed, but you should search for the solution of these dependency problems yourself, or at least ask in the repository / support channels of these packages.

The likelyness of one of the maintainers using "your exotic distribution" (can be the one you use, but i keep it general on purpose) is quite low - so it's either you using google to search for the solution, or us - but i don't see why we should do the searching for you.

**Comment by sobeit2020** [comment]
That is right, and understandable,
the job you that are doing is of high value and respect, thank you.

Thank you for the mentioning logs from ta-lib, unfortunately (fortunately?) Instalation process, went without problems, however i would repeat the process at some point, and will have watchful eye for that. In case i would find something, i will publish it here.

The system of my choice for purpose of freqtrade for the moment is 'Xubuntu' rather than 'Ubuntu', 
since it has no big flaws of Ubuntu but its merits.

Thank you and enjoy your holiday time!

**Comment by xmatthias** [comment]
well honestly, all *ubuntu flavors are identical from a freqtrade point of view ...
the X is meerly for the DE you're using (xfce) - which honestly, freqtrade, beeing a terminal application, doesn't care about :laughing: 

How did you install ta-lib? with the setup.sh script? 
you may need to patch your ldconfig / update ldconfig ... we have a "ubuntu detection" builtin (if apt-get exists) - maybe that fails on that distro ?

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.

**Comment by sobeit2020** [comment]
Hey Xmatthias, thanks,

I again made an approach, to load the freqtrade on MX Linux,
this is what i came up with, and here is just a tiny step to make it up. Could you hel p?

Trick is to involve loading of the library 'libta_lib.so.0', which surely exists, according to the hints provided by authors in the installation notes 


1. Piece of Info during installing Ta-lib
```
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,--rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
```


2. Mentioned Library directory
```
$ ls /usr/local/lib -la
total 8244
drwxr-xr-x  6 root root     4096 Dec 23 18:41 .
drwxr-xr-x 10 root root     4096 Oct 29 20:10 ..
drwxr-xr-x  2 root root     4096 Dec 21 20:15 antiX
drwxr-xr-x  4 root root     4096 Dec 21 20:15 cli-shell-utils
-rw-r--r--  1 root root  5345260 Dec 23 18:41 libta_lib.a
-rwxr-xr-x  1 root root      837 Dec 23 18:41 libta_lib.la
lrwxrwxrwx  1 root root       18 Dec 23 18:41 libta_lib.so -> libta_lib.so.0.0.0
lrwxrwxrwx  1 root root       18 Dec 23 18:41 libta_lib.so.0 -> libta_lib.so.0.0.0
-rwxr-xr-x  1 root root  3065848 Dec 23 18:41 libta_lib.so.0.0.0
drwxrwsr-x  4 root staff    4096 Oct 29 21:52 python2.7
drwxrwsr-x  3 root staff    4096 Oct 29 21:02 python3.7
```

3. Error @ $ freqtrade trade --strategy SampleStrategy
```
2020-12-23 18:39:18,616 - freqtrade.resolvers.iresolver - WARNING - Could not import /home/black/freqtrade/user_data/strategies/sample_strategy.py due to 'libta_lib.so.0: cannot open shared object file: No such file or directory'


2020-12-23 18:39:18,616 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'SampleStrategy'. This class does not exist or contains Python code errors.
2020-12-23 18:39:18,616 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
```

**Comment by xmatthias** [comment]
honestly, it's a ta-lib installation problem, not one with freqtrade directly

you can test this with independent of freqtrade.

```
# Activate virtualenv eventually
python3

> import talib.abstract as ta
# This will fail 
```

You can try to install the python dependency again (`pip install ta-lib`) - maybe the output will give you hints where to search.

Since this is a problem with ta-lib - you may search in the ta-lib [python wrapper repository](https://github.com/mrjbq7/ta-lib) for others that had such a problem.

As said above, best use a supported distribution, or be comfortable to debug and search for the solution to your issue yourself.
We will not waste our time supporting a not supported distribution's installation problem.

Thanks for your understanding.

**Comment by sobeit2020** [comment]
It is done, Freqtrade works on MX 

during installation process of Ta-Lib
instead of 
sudo ./config

it is necessary to use (which stands in documentation as well)
sudo ./configure --prefix=/usr 

Ubuntu somehow is OK with first command, MX is not.

**Comment by xmatthias** [comment]
well it'll depend on the predefined paths for LD ... 

That's "known" to be quite different for each distribution ... although simliar families (like debian + ubuntu) often use the same path - but not always (think of this like $PATH - but for loading libraries)
