### ISSUE TITLE
Timestamp in Output of /api/v1/status

### ISSUE THREAD

**Issue by denniswisnia** [freqtrade/freqtrade#4086]
## Describe the enhancement

I want to make a Grafana Dashboard to get a visualisation of the bot trading activity. The Idea is: Build a Graph with a line of a pair with the Profit right now.
The problem here is, that I dont get a timestamp inside the single trade. And it would be easy to integrate. I already tried to get the timestamp there, but I didnt get it inside the API. 

```
import time
 def _rpc_trade_status(self) -> List[Dict[str, Any]]:
        """
        Below follows the RPC backend it is prefixed with rpc_ to raise awareness that it is
        a remotely exposed function
        """
        # Fetch open trade
        trades = Trade.get_open_trades()
        if not trades:
            raise RPCException('no active trade')
        else:
            results = []
            for trade in trades:
                order = None
                if trade.open_order_id:
                    order = self._freqtrade.exchange.fetch_order(trade.open_order_id, trade.pair)
                # calculate profit and send message to user
                try:
                    current_rate = self._freqtrade.get_sell_rate(trade.pair, False)
                except (ExchangeError, PricingError):
                    current_rate = NAN
                current_profit = trade.calc_profit_ratio(current_rate)
                current_profit_abs = trade.calc_profit(current_rate)
                # Calculate guaranteed profit (in case of trailing stop)
                stoploss_entry_dist = trade.calc_profit(trade.stop_loss)
                stoploss_entry_dist_ratio = trade.calc_profit_ratio(trade.stop_loss)
                # calculate distance to stoploss
                stoploss_current_dist = trade.stop_loss - current_rate
                stoploss_current_dist_ratio = stoploss_current_dist / current_rate

                trade_dict = trade.to_json()
                trade_dict.update(dict(
                    timestamp=print(int(time.time())), <<<<<<<< 
                .....
```
EDIT: Ah, I forgot the "why": I need the timestamp right there to draw a graph properly in grafana. I could spend hours now to Implement it with a Prometheus Exporter and Pull it in Grafana, but this would be the easiest solution. 

When I am finished it, I would share my dashboard if someone is interested.

Other Question: Sometimes I get no response from the API - are there any default limitations?

If someone want to try it aswell:
I used the Datasource from here: https://github.com/marcusolsson/grafana-json-datasource

Datasource: http://127.0.0.1:8080 (ignore the error and save)
then add a new panel:

Choose JSON API as Datasource
Path: /api/v1/status
Query: e.g. $.[*].pair

**Comment by xmatthias** [comment]
i don't see why the current timestamp is relevant for the status endpoint ... 
It'll only bloat the result (apart from that, your implementation is wrong, print resturns None, not the content you printed, so you'll get an empty field for this).
 
You do get the trade open and trade close (if trade is closed) timestamps, which are the ones relevant for the trade, and the requester will know the current time (it's the time when you made the request), so if it's needed, i think using a `new Date()` in js (or whatever) should suffice.

**Comment by denniswisnia** [comment]
Okay, nevermind - I found FreqUI, which does exactly what I want.

Grafana needs a timestamp of the data point from the json to get valid graphs. The JSON Data Source is not enjoyable and you cant combine a timestamp generated by Grafana and the json query.

But, yea - lets move on with frequi. I close this Issue here and thanks for your answer.
