### ISSUE TITLE
Sell trade after timeout

### ISSUE THREAD

**Issue by Akronae** [freqtrade/freqtrade#4088]
## Describe your environment

  * Operating system: Win10
  * Python Version: 3.8.3 (`python -V`)
  * CCXT version: 1.39.33 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop-b9f3410d (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
I'm playing around with custom strategies, and I'm looking for a way to sell the trade after `n` days, if ROI could not have been reached.
This timeout would come on top of the current strategy I'm experimenting with, which uses `populate_buy_trend` and `populate_sell_trend` to make decisions.

Thanks for your help! :)

PS: I'm also looking for a way to log things in my strategy, could not find any doc on that either

**Comment by xmatthias** [comment]
The [documentation](https://www.freqtrade.io/en/latest/configuration/#understand-minimal_roi) is your friend.

Please read the "special case" note ... which will give you what you need.

You can obviously also code this somehow in the sell signal ... but using ROI with -1 is the easiest way to get a sell.

**Comment by Akronae** [comment]
Thank you I did not payed attention to the special note, and that did exactly what I wanted, wonderful!

**Comment by Akronae** [comment]
Thank you I did not payed attention to the special note, and that did exactly what I wanted, wonderful!
