### ISSUE TITLE
Backtesting additional Value in Statistics / cumsum-profit-min/max

### ISSUE THREAD

**Issue by squat0001** [freqtrade/freqtrade#4090]
## Describe the enhancement

freqtrade generates the output of max-drawdown, which is very useful, but lacks an important information.. the real question
of max-drawdown is, does the strategy have a enough money to complete? 

i wrote an backtesting tool, and i generate two more columns which i find useful:

    df_trades['sum'] = df_trades['profit_abs'].cumsum()
    trades_profit_min = df_trades['sum'].min()
    trades_profit_max = df_trades['sum'].max()

trades_profit_min = cumsum_profit_min is additional useful, its the value needed for the wallet in the first place to run with stake amount.

**Comment by xmatthias** [comment]
Feel free to submit a pull request adding this to the output report if you think it would be useful.

It'll be a good way to start contributing to freqtrade, as the scope of change is quite limited.

**Comment by squat0001** [comment]
Hi,

here the patch.. 

`Index: freqtrade/data/btanalysis.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- freqtrade/data/btanalysis.py	(revision a52d3ddda6da8c1064bc08d3dcf5bb21049e4376)
+++ freqtrade/data/btanalysis.py	(revision 6fb23382d8bd006b3d46658860ddfeafbfd4994e)
@@ -380,3 +380,21 @@
     high_date = profit_results.loc[max_drawdown_df.iloc[:idxmin]['high_value'].idxmax(), date_col]
     low_date = profit_results.loc[idxmin, date_col]
     return abs(min(max_drawdown_df['drawdown'])), high_date, low_date
+
+def calculate_csum(trades: pd.DataFrame
+                           ) -> Tuple[float, float]:
+    """
+    Calculate min/max cumsum of trades, to show if the wallet/stake amount ratio is sane
+    :param trades: DataFrame containing trades (requires columns close_date and profit_percent)
+    :return: Tuple (float, float) with cumsum of profit_abs
+    :raise: ValueError if trade-dataframe was found empty.
+    """
+    if len(trades) == 0:
+        raise ValueError("Trade dataframe empty.")
+
+    csum_df = pd.DataFrame()
+    csum_df['sum'] = trades['profit_abs'].cumsum()
+    csum_min = csum_df['sum'].min()
+    csum_max = csum_df['sum'].max()
+
+    return csum_min,csum_max
Index: freqtrade/optimize/optimize_reports.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- freqtrade/optimize/optimize_reports.py	(revision a52d3ddda6da8c1064bc08d3dcf5bb21049e4376)
+++ freqtrade/optimize/optimize_reports.py	(revision 6fb23382d8bd006b3d46658860ddfeafbfd4994e)
@@ -9,7 +9,7 @@
 from tabulate import tabulate
 
 from freqtrade.constants import DATETIME_PRINT_FORMAT, LAST_BT_RESULT_FN
-from freqtrade.data.btanalysis import calculate_market_change, calculate_max_drawdown
+from freqtrade.data.btanalysis import calculate_market_change, calculate_max_drawdown, calculate_csum
 from freqtrade.misc import file_dump_json
 
 
@@ -314,6 +314,13 @@
                 'drawdown_end': drawdown_end,
                 'drawdown_end_ts': drawdown_end.timestamp() * 1000,
             })
+
+            csum_min, csum_max = calculate_csum(results)
+            strat_stats.update({
+                'csum_min': csum_min,
+                'csum_max': csum_max
+            })
+
         except ValueError:
             strat_stats.update({
                 'max_drawdown': 0.0,
@@ -321,6 +328,8 @@
                 'drawdown_start_ts': 0,
                 'drawdown_end': datetime(1970, 1, 1, tzinfo=timezone.utc),
                 'drawdown_end_ts': 0,
+                'csum_min': 0,
+                'csum_max': 0
             })
 
     strategy_results = generate_strategy_metrics(all_results=all_results)
@@ -427,6 +436,10 @@
             ('Avg. Duration Winners', f"{strat_results['winner_holding_avg']}"),
             ('Avg. Duration Loser', f"{strat_results['loser_holding_avg']}"),
             ('', ''),  # Empty line to improve readability
+
+            ('Abs Profit Min', f"{round(strat_results['csum_min'] , 2)}"),
+            ('Abs Profit Max', f"{round(strat_results['csum_max'] , 2)}"),
+
             ('Max Drawdown', f"{round(strat_results['max_drawdown'] * 100, 2)}%"),
             ('Drawdown Start', strat_results['drawdown_start'].strftime(DATETIME_PRINT_FORMAT)),
             ('Drawdown End', strat_results['drawdown_end'].strftime(DATETIME_PRINT_FORMAT)),
`

**Comment by squat0001** [comment]
i filed a pr #4115 
its my first on github ever..

**Comment by squat0001** [comment]
sorry, i do believe my PR is not perfect, here the correct number #4116

**Comment by xmatthias** [comment]
This has actually been merged now, therefore closing.

Thanks for your contribution! 👍

**Comment by squat0001** [comment]
Thanks 😊😊 my first patch ever merged!Am 18.02.2021 12:43 schrieb Matthias <notifications@github.com>:

This has actually been merged now, therefore closing.

Thanks for your contribution! 👍



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/freqtrade/freqtrade/issues/4090#issuecomment-781285550",

"url": "https://github.com/freqtrade/freqtrade/issues/4090#issuecomment-781285550",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Jay-ArBrouillard** [comment]
The documentation (https://www.freqtrade.io/en/stable/backtesting/#understand-the-backtesting-result) is missing the explanation for Abs Profit Min and Abs Profit Max. If I had $1000 starting capital and my Abs Profit Min is $10 and my Abs Profit Max is $1100, does that mean at one point during the backtesting my account dropped to $10? Or does that mean lowest value my account had is my starting capital + Abs Profit Min = $1010? I don't quite understand what these terms means.

**Comment by xmatthias** [comment]
@Jay-ArBrouillard Please make sure to use a documentation that corresponds to your version.

Abs Profit Min / Abs Profit Max is missing from the documentation because it doesn't exist on the latest stable any longer.
Best update to the latest version (2021.3) to benefit from the latest changes.
