### ISSUE TITLE
Performance Calculation

### ISSUE THREAD

**Issue by FahadAziz** [freqtrade/freqtrade#4108]
Hi 

first, I would like to thank every single person who contributed to this project the job has been done nicely. I have one issue that is bugging me and I am willing to help to get it sorted but I am not a coder unfortunately. 

Overall performance calculation is simply wrong and cannot be relied upon for backtesting and hyperopt. I will show you an example of trades and returns and how calculation should be done for pairs performance and overall performance to help fix the issue.

First this demonstration is taking traded value as your whole portfolio since we cannot control for redemption or addition in the wallet.

**Simple trade**: (closing price / opening price) -1

**Pair Performance:** 
Weight of the pair = (total pair (closed/active) value / total portfolio (closed / active)  **cost** value)
Pair Performance = SUM (Simple trade perf. * Weight of the pair)

**_Equally weighted portfolio_:**
![image](https://user-images.githubusercontent.com/6364652/102884472-b3dcae00-4462-11eb-90af-86c7ef94c5b5.png)

**_Unequally weighted portfolio_:**

![image](https://user-images.githubusercontent.com/6364652/102884528-c9ea6e80-4462-11eb-9d52-cd3e36808ed8.png)

**Overall performance:** 

Weight of the trade = (trade (closed/active) value / total portfolio (closed / active) **cost** value)
Performance = SUM (Simple trade perf. * Weight of the trade)

**_Equally weighted portfolio_:**

![image](https://user-images.githubusercontent.com/6364652/102884324-7ed05b80-4462-11eb-9af6-bdd5bdafa525.png)

**_Unequally weighted portfolio_:**

![image](https://user-images.githubusercontent.com/6364652/102884380-9576b280-4462-11eb-8aac-04b5ba991afc.png)

Notes to consider:
- All returns can be calculated based on before and after fees 
- The issue is not about inconsistency between different modules, the issue is when I run a strategy backtest and it shows 8000% total return I know something is wrong.
- Each trade (losing or winning) should be calculated on weighted basis and should not be summed.

All calculations are done in excel. I will help explain and test when implemented.

I have attached the excel file as well

Thank you again for all the hard work.

[freqtrade.xlsx](https://github.com/freqtrade/freqtrade/files/5729654/freqtrade.xlsx)

**Comment by xmatthias** [comment]
Especially for backtesting, i think your assumptions above are wrong.

You're calculating trade weight - but especially in backtesting, all trades have the same weight, as `stake_amount` is identical for each trade (backtesting does NOT support dynamic stake amount, letalone compounding at this moment) - so your weight will always be identical (in your 1000$ Portfolio example, it might be 100, with 10 max_open_trades).

Backtesting provides 2 columns with relative profit, 
* one being "Cum Profit %", which is the profit per stake_amount.
* The second column "Tot Profit %" is the profit across the whole portfolio (basically it's Cum Profit % / "max_open_trades".

It's unclear which value you're looking at above (as well as it's unclear if the formulas you're explaining are how you think it should be, or how you think it is now).

Also, your calculation does not include Fees, which backtesting does (unless it's explicitly disabled), so obviously freqtrade profit will be lower - as it does include open and close fees per trade. 
The above does not specify wether this was explicitly disabled (set to 0) for the freqtrade calculation or not.


Maybe edit the post above to clarify ... but for now, i find this highly confusing, and no help at all  as it's unclear which performance metrics you're even talking about.
Unfortunately, this means, there won't be any action taken based off of this.

**Comment by FahadAziz** [comment]
Thank you xmatthias for your prompt response, I will lay out full explanations for each metric and situation.

**Comment by FahadAziz** [comment]
> Thank you xmatthias for your prompt response, I will lay out full explanations for each metric and situation.

I have updated the post with more clarifications.

**Comment by xmatthias** [comment]
Keep in mind that freqtrade uses 2 different profit calculation methods - one is per stake (this is where you'll see 800%) - which you can basically divide by max_open_trades to get an idea.

---

I'll take the "Equally weighted portfolio:" to start with:

As mentioned above, for backtesting, we got 2 values - one (`Cum Profit %`) will be shown as 3.6%, and the other (`Tot Profit %`)will be shown as 0.9% - assuming `max_open_trades` is 4 (it's calculated as `sum(returns) / max_open_trades`).

As this is a simple example it uses one pair, it'll be trades done one after the other - so your actual starting total porfolio value is 1x stake, not 4x stake amount.

Freqtrade would in this case never use more than 66.7$, so you maybe have 10.000$ in your account - but that doesn't mean you can calculate freqtrade's profit against these 10.000$ - if you only allowed it to trade with 66.7$.


---

for the "Unequally weighted portfolio":
This is where it might become more interresting after #3886 ... 
but until then, backtesting uses one fixed stake (set as stake_amount) - so technically, backtesting can not produce such a result at this moment.
Also, as it's the same pair - you're never actually investing 340$ at the same time - but at max. 100$ (as this is your highest cost).

---

**overall performance - equally weighted**

this is where it becomes more interresting ... 
your assumption here is that you're in all 15 trades at the same time (so you can distribute weights across all trades), trades however happen over a period of time, with some trades in parallel (up to `max_open_trades`) - but it's unlikely that all trades will be open at the same time.

so you might open the first 3 trades, close one and replace it with the 4th trade, (and so forth).

Again (at least in the equaly weighted portfolio case), you can get from the "freqtrade return" to your weighted return by dividing by 15.

Again for backtesting, the same restrictions as above apply, so with this as result - (and assuming `max_open_trades=15`) - you would get both values shown in the backtesting table.


**overall performance - unequally weighted**

This one is tricky again - as it's impossible in backtesting - but i agree with you that it's most likely wrong in real modes (where different stake-amounts can be possible) - so i'd focus on this case if you don't mind, as it's the most realistic (implicitly, i assume it'll also fix the other cases ...).

I'm not certain on the weightning just yet - as i don't think it considers the time component properly (prove me wrong!) 

---

Consider the following case (it's similar to your equally weighed overall portfolio... but i hope it helps us understand this better)
* i got 1000$ starting capital
* i split these 1000$ into 5 buckets (ignore for a moment if equally or not)
* i do 15 trades with 200$ each (equally weighted) over a period of a week.
* to make this unrealistic, i really have 1400$ in my account, so "lost" amount replenishes automatically, so a total of 1000$ are always available to be in trades (in reality, i lost the first 2 trades, so i'd only be able to do 4.5 trades ...).


Obviously, no more than 5 trades will ever be open at the same time.
now where i have my doubts is ... by using a weighted approach (using your formula), i'd assume  15 * 200$ = 3000$ as total balance, and then split this to get my weights.

I do however never have 3000$ ... but i only ever traded a max of 1000$ - so would your formula still work in that case?

**Comment by FahadAziz** [comment]
Thank you xmatthias, very thorough and well thought walk through details. Let me walk you through some assumptions first.

1- formula can be changed and modified based on assumption and availability of data.
2- My assumption above is that performance is calculated based on **Active/Closed total traded value** regardless of total available or actual funds available for trading since this is going to make calculating performance more challenging to account for funds in/out of the wallet.

The way I would think about it for the sake of simplicity to solve some of these challenges is to have a performance logger (separately or within trades log). This can log weighted performance. Then use following formulas:

**Pair performance** = ((Pr1+1) * (Pr2+1) * (Pr3+1) ......) - 1 <-- this would take the weighted performance logs for that pair
**Overall performance** uses the same formula but it will take all weighted performance logs

Calculation of weights would be based on **total available for trading** funds.

This is just a thought I do not know about applicability, Wil run a simulation on Excel and share later today to verify.

**Comment by xmatthias** [comment]
> In doing it this way I would assume that backtesting would need an adjustment to make it more realistic and add an initial fund balance.

i don't see why this should be necessary / or rather - this is already there, as `stake_amount * max_open_trades`.

> weighted performance

if i understand your formula correctly - it would simply be:
`(stake_amount / sum(all stake amounts for all trades within this group)  * profit = profit% within this group`

*note:* with "within this group" it can be within one pair, or for all pairs...

**Comment by FahadAziz** [comment]
> > In doing it this way I would assume that backtesting would need an adjustment to make it more realistic and add an initial fund balance.
> 
> i don't see why this should be necessary / or rather - this is already there, as `stake_amount * max_open_trades`.
> 
> > weighted performance
> 
> if i understand your formula correctly - it would simply be:
> `(stake_amount / sum(all stake amounts for all trades within this group) * profit = profit% within this group`
> 
> _note:_ with "within this group" it can be within one pair, or for all pairs...

Please have a look at the attached file under "trade log" sheet I think we got it right. 

It calculates the overall performance (adjusting for unstable cash balance). The way it will work like this:

- let us assume I started the bot for the first time **ever**. It will take my available funds for trading as my initial cost.
- Cost will be adjusted based on trading activity (buy/sell).
- If I transfer funds in and out, cost will be adjusted accordingly.

It also calculates pair contribution to the overall performance.

Please have a look and let me know if any adjustments needed.


[freqtrade (1).xlsx](https://github.com/freqtrade/freqtrade/files/5736619/freqtrade.1.xlsx)

**Comment by xmatthias** [comment]
sorry this took a while ... looking at excel sheets and trying to get out a formula (or checking it's correct) is something i really dislike - so i've been putting it off for quite some time ... 

---

I don't THINK it is correct (please do checks yourself and don't trust my excel skills!)
The sheet only has wins, no losses. 
While this would be great, it's ... quite unrealistic.

For fun, i changed one sell to be a loss (F13 = 19000).

While Return / gain/loss for this trade does adjust seemingly correctly (i didn't do the math manually, but it seems to be in the right vicinity) - the "weighted return" for this row is now 0.000%.

---

Changing all trades to be a loss (by simply moving the price in the sell lines) - the weighted return is now 0.000% for all pairs.
So now my dot-product will return 0.0 (because 0.0 * anything will still remain 0)

The most likely reason is that the O formula (formula in column O) doesn't have a "if" tree, if profit is negative.
I'll leave that up to you if you don't mind - as honestly, i don't understand why this needs to be "if-checked" - and how the formula should be different for negative profits.

---

Side note:
As explanation WHY i hate excel / excel formulas:
If you look at the formula in H4, it'll be `=IF(D4="Buy",E4*F4+G4,E4*F4-G4)`.
This formula seems correct ... but it's not been copied down that column correctly, so the formula in H5 is `=IF(D5="Buy",E5*F5+G5,E5*F5+G5)` (note the wrong sign for selling fees).

Since this is a very common problem in excel sheets - it makes using excel (for me) a quite unreliable tool - as i can never trust that each row really had the same calculation applied correctly.

**Comment by FahadAziz** [comment]
Thank you xmatthias for the efforts and I do hate it as much as you do but you always need a third eye to double check :)

You are right there was a typo in the formula in column O that checks if it is a buy or sell transaction and changed "<" to "=" to filter out anything that not a sell transaction.

It should work now perfectly. 

Side note: this should work as long as you do not introduce a new feature that lets you buy multiple times of the same coin. in that case, instead of taking the last cost in columns I, one would calculate the average cost of that coin (total cost / amount held) 

Hope this solves the performance issue unless you have any other concern :) 

Thank you for the  effort you are putting into this.
[freqtrade.1.xlsx](https://github.com/freqtrade/freqtrade/files/5754110/freqtrade.1.xlsx)

**Comment by xmatthias** [comment]
> Side note: this should work as long as you do not introduce a new feature that lets you buy multiple times of the same coin. in that case, instead of taking the last cost in columns I, one would calculate the average cost of that coin (total cost / amount held)

I'm not sure that's true ...keep in mind that from an implementation perspective, we'll probably not do the calculation to aggregate to "per pair" first, and only then to the full profit, but to "full profit" right away from the single trades
So even with staking (same coin multiple times) - the weight per trade would not change.

leaving that asside, all calculations we do in freqtrade assume the "current state" of the project, and changes to logic will always have to also look at the implementation of calculations.

**Comment by FahadAziz** [comment]
Indeed but what I meant is:

- lets assume you bought one ETH at $500
- Market went down and you bough another one at $450
- Your average cost now sits at $475 ($950 / 2)
- Market went up and you sold 2 ETH at $550, your return is 15.78%

The current state of the excel calculation assumes you buy only once so it takes the last cost you bought at. If you were to allow staking this should change to look for open trades and take their cost and divide that by the amount your are holding ( Total cost / amount held). This way will get you the right weighted performance per coin (whether you sell full or partial stakes). 

This is just for the future to keep in mind, just in case you are planning in introducing staking in the future so you implement the calculation structure once without adjusting it in the future.

I would recommend that you do it now (total cost / amount held) method so there is no need to go back to it in the future. This will also help in incorporating fees in the (cost per coin) figure. It is up to you how you would implement it in code and what are the possibilities.

Hope that helps in explaining what I mean.

Thanks

**Comment by xmatthias** [comment]
well talking about staking is a distant bet ... 

It'll also depend HOW it's done (best check the related issue for that) ... as you can EITHER then have one trade which has 2 ETH ... or 2 seperate trades (both with 1 ETH) (which are both handled as independent trades).

**Comment by FahadAziz** [comment]
My opinion is:

For handling trade log, buy trades of course should be handled separately that is for sure, however sell trades should take into account the overall cost of open trades of that pair to calculate the performance. This is a market practice. however in reporting the portfolio positions it should be aggregated as 2 ETH not two separate lines of 1 ETH each.

But that is a discussion for another day :)

Finally, if anything needed from myside going forward I would happily help.

Thanks

**Comment by xmatthias** [comment]
> But that is a discussion for another day :)

yes for sure :) 

> Finally, if anything needed from myside going forward I would happily help.

Oh don't worry, once it's implemented / available as a PR, i'll be sure to take you up on your offer to test that :+1:

**Comment by xmatthias** [comment]
i've now tried this ... using the initial formula using total_stake as `profit * (stake_amount / sum(stake_amount))`, i don't think this will work correctly - as then my total stake can be 20.000 USD (assuming i did 200 trades a 100$ each) - while my account never really was above 1000$.

However, also the other formula (using the amount that's previously been available) is rather problematic.

First of all, we don't keep track of the full account balance when a trade opens or close.
Then, i could have 10.000$ in my account, but the bot is only allowed to trade 1000$ (10 x 100$). Using "what's available" will show my profits as very minimal, while in reality, they'd have been 10x higher, as my starting stake (total account) would be assumed as 10k$, while the bot only got 1k$.

Also, this logic will completely break once i start to deposit / withdraw, as the available balance will fluctuate without the bot making even one trade, which will completely throw the calculations off.
