### ISSUE TITLE
1 delayed candle from exchanges.

### ISSUE THREAD

**Issue by fernandobender** [freqtrade/freqtrade#4114]
hello.

i'm using 

freqtrade develop-48f7997a
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
Description:    Ubuntu 20.04.1 LTS

i've noticed that the last candle downloaded is not the last candle available.

the current candle is still in formation, thus, only it's open is defined.
the previous candle is already formed, so its ohlcv are set.
the latest downloaded candle is its preceding candle.

i've tested it in different timeframes (1h, 2h) and exchanges (binance, okex)
i've added dataframe.tail() just before return in populate_indicators()
i've checked the information against tradingview data on these exchanges

here are some screenshots.

1. freqtrade backtesting with dataframe.tail() at 20h25 (GMT)[*1] timeframe 1h, BTC/USDT at OKEX.
[fig. 1](https://drive.google.com/file/d/1sV6WoXiKsjT6FbuyNqhisr3QnTtJNlas/view?usp=sharing)

2. respective chart on trading view
[fig. 2](https://drive.google.com/file/d/1aV4lWAknkd5tUrTb9yfXps7NDgYTe643/view?usp=sharing)

i have others to add, 2h on okex and binance. in case they're needed, i gladly edit this post.

many thanks.

[*1] i'm on GMT -3

**Comment by xmatthias** [comment]
Freqtrade will only provide you with complete candles, but not with incomplete candles.

Assume it's now 10:30 ... so the last 1h candle you'll get is from 09:00 - 10:00.

The candle from 10:00-11:00 will be available at ~11:00:01 (exact time depends on the exchange and pair).

Also, all dates are candle OPEN dates, so if you get 09:00, then this refers to the candle from 09:00 to 10:00.

Hope this explains what you're seeing.

**Comment by fernandobender** [comment]
thank you for the reply so promptly.
precise what you mentioned, i was expecting to see.

if you check fig. 1, the latest candle available is 18:00, which is its open time. thus, it closes at 19:00,
but the time in the clock was 17:25 @ gmt -3, i.e. 20:25 @ gmt, the chart time.
so being, the candle that opens at 19:00 and closes at 20:00 should be available in the dataframe, but it wasn't.

am i missing something here?

best!

**Comment by xmatthias** [comment]
wait, are we talking about backtesting, or are we talking about live runs?

the screenshot seems to show backtesting ... ?

**Comment by fernandobender** [comment]
it is backtesting, indeed. the download-data command was performed 5min before that. so, the latest possible candle was downloaded.

**Comment by xmatthias** [comment]
yes, you'll be missing the 2 last candles.

download-data removes the incomplete candle
backtesting will not "trust" this and will remove the last candle as well.

Usually, that's no problem unless you're using very wide timeframes (like 1d or 1w).

**Comment by fernandobender** [comment]
ah, ok. so in live trading it doesn't happen this second removal? if so, i gladly close this thread.
thank you!

**Comment by xmatthias** [comment]
as said, download-data removes the last candle when it saves (actually when it transforms candles to a dataframe).

backtesting will remove the last candle when it loads

This "storage / load" step is not happening in live - so only one candle is removed then (the incomplete one).

**Comment by fernandobender** [comment]
thank you very much for thid important clarifying.
