### ISSUE TITLE
How to totally reset installation

### ISSUE THREAD

**Issue by corourke** [freqtrade/freqtrade#4117]
Greetings, been playing with Freqtrade over the last few days -- seems I'm getting funny errors (lots of 'Missing data fillup' warnings and now ('unable to fetch order') and I think it is just due to me stopping the service and messing with the configuration a lot. 

Is there a way to totally reset all of the data? I tried deleting the SQLite database file but I don't think that removed everything. I could reset the user_date folder as documented (after saving off my strategy classes) but I don't see where it is actually holding any data.

**Comment by xmatthias** [comment]
backtesting source data is in `user_data/data/<exchange>`.
backtesting results will be in `user_data/backtest_results`

Trades (for live / dry runs) are in the sqlite files. 
Make sure to stop the instance (or all instances, if you started more with the same database in error) before deleting them.

> Missing data fillup

this message just says that there's a gap in data. This can be a exchange downtime (like we had on binance yesterday) - it'll "age out" eventually - until then there's not much you can do against it.

**Comment by corourke** [comment]
Thanks -- that makes sense. I didn't realize that the exchange was down for a while. Now playing with Hyperopt. You can spend days and days with this stuff!!!
