### ISSUE TITLE
Custom strategy not loading properly by using the docker compose file.

### ISSUE THREAD

**Issue by indiafoxtrot** [freqtrade/freqtrade#4120]
Have you searched for similar issues before posting it?

Yes, I have found some related to this but even so, it hasn't solved my problem...

I would like to know what is the right format to write the path to our custom Strategy using the docker compose file provided in the documentation. Because whenever I try to run my strategy or the sample_startegy.py provided by you does not work. the log says "Impossible to load Strategy '/freqtrade/user_data/strategies/strategy.py'. This class does not exist or contains Python code errors." My compose file looks like this:

```
command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy /freqtrade/user_data/strategies/strategy.py

```

I have tried different paths and even just writing  --strategy strategy.py but nothing besides the SampleStrategy ends up working. But besides from that, everything else works, for example, I was able to step up the telegram API and I can do other changes to the config.json file. Do you have any idea about what may be happening? Thanks!

**Comment by mrsegen** [comment]
You just need the name of the class from within the strategy *.py file. 

See how the strategy is marked in this backrest example: (It still applies for running the bot.)

https://www.freqtrade.io/en/latest/docker_quickstart/#example-backtest-with-docker-compose

**Comment by indiafoxtrot** [comment]
Thanks a lot mrsegen , sorry I misunderstood step three that mentioned "add the Strategy class name to the docker-compose.yml file", thanks for taking the time to clarify! Also, I would recommend bold the word class to be more visible because some people may miss that just like I did.

**Comment by xmatthias** [comment]
You mean - like [here](https://www.freqtrade.io/en/latest/bot-usage/#how-to-use-strategy) ?

**Comment by lexatisa** [comment]
Hmmmm fun
