### ISSUE TITLE
hyperopt sell_strategy_generator is not called, backtesting perfom sells

### ISSUE THREAD

**Issue by fernandobender** [freqtrade/freqtrade#4130]
## Describe your environment

  * Operating system: lubuntu 20.04
  * Python Version: 3.8.5 (`python -V`)
  * CCXT version: 1.39.79 (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-dcc7d559 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
our strategy trades 15 times in dec/20, having 4 sell reasons = sell signals.
its hyperopt file runs without error, but its sell_strategy_generator() is not called.
i have inserted a syntax error (just let a character "a" alone in a line just after initial comments) and no error is raised.
also, sell_params output is empty, while there are 1 integer, and 1 categorical.

it also outputs buy_params that are not used, for instance 'bb_lower', is a triger we do not use, while it is in the default template.

*Explain the problem you have encountered*

### Steps to reproduce:

  1.freqtrade hyperopt -c config.json --hyperopt BOopt -e 10 --hyperopt-loss OnlyProfitHyperOptLoss --strategy BO
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
based on what you describe, the most probable reason is that you've got 2 hyperopt files with this name (`BOopt`) - and it's loading the wrong one.

Also make sure that the right methods are in the right locations (basically `*strategy_generators` and `*space` in hyperopt file, the rest in the strategy)

I've just tested this and sell_strategy_generator is called just fine.
---
you can also test this yourself on a fresh userdir:
```
freqtrade create-userdir --userdir user_data_to_test
freqtrade hyperopt --userdir user_data_to_test --datadir tests/testdata -e 5 --strategy SampleStrategy --hyperopt SampleHyperOpt --hyperopt-loss SharpeHyperOptLossDaily --print-all
```

Please don't rely on results as its test-data based on some random coins from 2018 (or so) - but it should show that the correct methods are called.
By using a fresh userdirectory, it'll automatically exclude the possibility of duplicate classnames.

**Comment by greenfield-br** [comment]
indeed. thank you. case closed
