### ISSUE TITLE
2020.12 plot_config example missing from documentation

### ISSUE THREAD

**Issue by MrKrautee** [freqtrade/freqtrade#4132]
see: https://www.freqtrade.io/en/latest/plotting/#advanced-plot-configuration

**Comment by MrKrautee** [comment]
i did not add 'triage needed' label !! :P :D

**Comment by xmatthias** [comment]
> i did not add 'triage needed' label !! :P :D

yes you did - by selecting "reporting a bug" ;) 

---

You'll laugh when you look into the commit to see WHAT the problem was ...

**Comment by MrKrautee** [comment]
oh :D :) blank line missing. maybe we need to check this in test-docs.sh. 
It rendered quit well on my local machine.

**Comment by xmatthias** [comment]
it didn't in the end (once the !!! part was fixed).

feel free to submit a PR adding this test to test-docs.sh ... i think a good manual review (i wasn't aware of this behaviour when combining code and note blocks) should suffice in most cases, as this is the first time this happened.
