### ISSUE TITLE
Download pair and total crypto market cap

### ISSUE THREAD

**Issue by zlac116** [freqtrade/freqtrade#4135]
Hi team - I have checked the freqtrade docs and I couldn’t find any information on how to download crypto pair and total crypto **market capitalisation** data, in order to use this in a strategy. Is it possible to obtain this data via any of the available exchanges?
Thanks

**Comment by xmatthias** [comment]
Downloading data is covered [in the documentation](https://www.freqtrade.io/en/latest/data-download/).

Market Cap is not provided by any of the exchanges i use AFAIK (they provide THEIR 24h volume, but that's not market capitalisation).

As the strategy is just some python code, you could use any api / provider you find that provides the data you need and pull that into the strategy - but we don't have anything builtin.

You could also ask this question at the ccxt repository directly - but as far as i know, they don't integrate data aggregators (like coinmarketcap) - so i don't think this data will be available.

**Comment by zlac116** [comment]
No problem, appreciate the suggestions @xmatthias.
