### ISSUE TITLE
Mismatch backtest and hyperopt results 

### ISSUE THREAD

**Issue by Drissa21** [freqtrade/freqtrade#4152]
## Describe your environment

  * Operating system: Macos 
  * Python Version: 3.8
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.12
  
## Your question

I am unable to successfully to get the results from Hype-opt to match with the results from backtesting. I've reviewed my custom hyper-opt file several times and I've also reviewed my custom strategy file. I've been unable to determine what's been causing the discrepancy in the numbers.

Similar responses regarding this issue have all pointed to correcting the config and strategy files and i have edited both multiple times and still have not received the same results as the hyper-opt. i have pasted the strategy the config file and the hyper-opt results can someone please help. 

CONFIG:
```
 "max_open_trades": 15,
    "stake_currency": "BTC",
    "stake_amount": 0.01,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "5m",
    "dry_run": true,
    "position_stacking": true,
    "cancel_open_orders_on_exit": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30

    },

    "Trailing stop": {
    "trailing_only_offset_is_reached": false,
    "trailing_stop": true,
    "trailing_stop_positive": 0.33772,
    "trailing_stop_positive_offset": 0.42962,

    },
    "bid_strategy": {
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy":{
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
```

STRATEGY;
```
    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi"
    minimal_roi = {
        "0": 0.47345,
        "155": 0.18491,
        "718": 0.05583,
        "1071": 0

    }

    # Optimal stoploss designed for the strategy
    # This attribute will be overridden if the config file contains "stoploss"
    stoploss = -0.05571

    # Trailing stop:
    trailing_only_offset_is_reached = False
    trailing_stop = True
    trailing_stop_positive = 0.33772
    trailing_stop_positive_offset = 0.42962
     

    # Optimal timeframe for the strategy
    timeframe = '5m'

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        stoch_fast = ta.STOCHF(dataframe, 5, 3, 0, 3, 0)
        dataframe['fastd'] = stoch_fast['fastd']
        dataframe['fastk'] = stoch_fast['fastk']
        dataframe['ema_high'] = ta.EMA(dataframe, timeperiod=5, price='high')
        dataframe['ema_close'] = ta.EMA(dataframe, timeperiod=5, price='close')
        dataframe['ema_low'] = ta.EMA(dataframe, timeperiod=5, price='low')
        dataframe['adx'] = ta.ADX(dataframe)

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                (dataframe['open'] < dataframe['ema_low']) &
                (qtpylib.crossed_above(dataframe['fastk'], dataframe['fastd'])) &
                # (dataframe['fastk'] > dataframe['fastd']) &
                (dataframe['fastk'] < 30) &
                (dataframe['fastd'] < 29) &
                (dataframe['adx'] < 42)
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the sell signal for the given dataframe
        :param dataframe: DataFrame
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                (dataframe['open'] >= dataframe['ema_high'])
            ) |
            (
                # (dataframe['fastk'] > 70) &
                # (dataframe['fastd'] > 74)
                    (qtpylib.crossed_above(dataframe['fastk'], 70))
            ),
            'sell'] = 1

        return dataframe
```

HYPER-OPT RESULTS;
```
 # Buy hyperspace params:
    buy_params = {
     'adx-enabled': True, 'adx-value': 42, 'fastd-enabled': True, 'fastd-value': 29
    }

    # Sell hyperspace params:
    sell_params = {
        'sell-adx-enabled': True,
        'sell-adx-value': 74,
        'sell-fastd-enabled': False,
        'sell-fastd-value': 71
    }

    # ROI table:
    minimal_roi = {
        "0": 0.47345,
        "155": 0.18491,
        "718": 0.05583,
        "1071": 0
    }

    # Stoploss:
    stoploss = -0.05571

    # Trailing stop:
    trailing_stop = True
    trailing_stop_positive = 0.33772
    trailing_stop_positive_offset = 0.42962
    trailing_only_offset_is_reached = False
    
```

**Comment by xmatthias** [comment]
Please carefully read the [hyperopt documentation](https://www.freqtrade.io/en/latest/hyperopt/) multiple times until you FULLY understand how to transfer results to the strategy

In general, i recommend to remove all stoploss settings from the configuration - that'll move all changes you do to the strategy, so it's easier to handle (same for ROI).
You can check the startup-logs of backtest-runs to check where each parameter comes from.


Your `populate_buy_trend` (and `populate_sell_trend`, for that matter) has very little to do with the results.

Based on the buy-results, you should have 3 conditions for buy, and 2 condition for selling.
In the default hyperopt samples / templates, there's a "hidden" `dataframe['volume'] > 0` which is mandatory and therefore not part of the hyperopt resut.

The problem is, what you're doing is not even close to the hyperopt result.

**Comment by Drissa21** [comment]
thank you xmatthias for your comment but im still lost as to how i have entered the information incorrectly. My original strategy came from the Montreal trading group course and i changed it to the cofibit strategy, and from what i got from the course and the hyper-opt doc i thought i have all the information in the right areas.  

can you also explain the hidden dataframe['volume'] > 0 this is the first im hearing of this and not sure what to do with it from here?

**Comment by xmatthias** [comment]
[this section of the docs](https://www.freqtrade.io/en/latest/hyperopt/#reproducible-results) clearly explains how to transfer the result you get from Hyperopt to the strategy.

You clearly didn't do this - so it's not working.

The "volume > 0" check is in newer hyperopt templates (not sure if it's in yours or not)

If you check the above linked documentation, you'll find it as follows.
It's then up to you to determine if you had this in your hyperopt file or not (if it came from the course maybe not, as that is pretty outdated ...).

``` python
            # Check that volume is not 0
            conditions.append(dataframe['volume'] > 0)`
```

**Comment by xmatthias** [comment]
I hope the above gives you enough hints to get this working.

If you have further questions relating to this, please use the [discord channel](https://discord.gg/MA9v74M) to get support / help from the community.
People there love to help assuming the documentation has been consulted first.
