### ISSUE TITLE
I ran freqtrade against AWS CodeGuru

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#4157]
I ran freqtrade repo against CodeGuru to help with code recommendations, I got the following:

__init__.py Line: 33 
It appears that you are generically passing an Exception object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the logging.exception() API. For example,

try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception('ZeroDivisionError: %s', e)

--- 

load_config.py Line: 49 
Analysis of this code determined that this line of code contains a resource that might not have closed properly. A resource leak can slow down or crash your system. Programs are strongly recommended to use the built in with keyword to open a resource or to use a try-finally block to open and close resources explicitly. The contextlib module provides helpful utilities for using the with statement.

---

hyperopt.py Line: 412 
Analysis of this code determined that this line of code contains a resource that might not have closed properly. Although there is an explicit call to close(), some execution paths do not reach it, such as in case of an exception. A resource leak can slow down or crash your system. Programs are strongly recommended to use the built in with keyword to open a resource or to use a try-finally block to open and close resources explicitly. The contextlib module provides helpful utilities for using the with statement.

----

test_configuration.py Line: 761 
It appears that you are generically passing an Exception object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the logging.exception() API. For example,

try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception('ZeroDivisionError: %s', e)

**Comment by xmatthias** [comment]
Thanks for this, but blindly copy/pasting results from an automated tool to an issue without analyzing them first will not help this project.

If you think they are real problems and must be fixed, please provide Pull-requests which address the issue you think is problematic.

while doing so, you'd have found that they are either false positives (it seems to not know what a context manager is) or have a valid usecase where it's implemented like this.

If this are the recommendations, then honestly i don't think it's even worth the time running AWS CodeGuru, and i'm sorry for you to have wasted the time (not sure how long it takes).

**Comment by ghost** [comment]
I totally get your point.
I do like your project Freqtrade a lot, and will do my best to help whenever possible.
Thanks again.
