### ISSUE TITLE
Split configs for Protections not working

### ISSUE THREAD

**Issue by ziegi** [freqtrade/freqtrade#4160]
## Describe your environment
  freqtrade develop-516e56b

## Describe the problem:
I am using multiple configuration files for my bots.
And within them I split and or overwrite the configuration parts e.g.
partial_config_1:
```
 "exchange": {
         "pair_blacklist": [
            "BNB/TUSD"
       ]
    }
```
partial_config_2:
```
 "exchange": {
        "pair_blacklist": [],
        "pair_whitelist": [ "SYS/BTC" ]
    }
```

Using the right order while loading the configuration files, this works perfectly for the "main" freqtrade application,
but does not seem to work for the protection plugins.

If I use the following:
```
partial_config_1:
    "protections": [
    {
        "method": "MaxDrawdown",
        "lookback_period_candles": 20,
        "stop_duration_candles": 20,
    },
    {
        "method": "StoplossGuard",
        "lookback_period_candles": 20,
        "stop_duration_candles": 20,
    }        
    ]    
```
partial_config_2:
```
 "protections": [
    {
        "method": "MaxDrawdown",
        "trade_limit": 20,
        "max_allowed_drawdown": 0.16
    },
    {
        "method": "StoplossGuard",
        "trade_limit": 2,
        "only_per_pair": true
    }    
    ]
```

The bot can gives me this response:
021-01-06 16:23:48,860 - freqtrade.resolvers.iresolver - INFO - Using resolved protection MaxDrawdown from '.../freqtrade/plugins/protections/max_drawdown_protection.py'...
2021-01-06 16:23:48,862 - freqtrade.resolvers.iresolver - INFO - Using resolved protection StoplossGuard from '.../freqtrade/plugins/protections/stoploss_guard.py'...
.....
2021-01-06 16:23:52,138 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': 'Using Protections: \nMaxDrawdown - Max drawdown protection, stop trading if drawdown is > 0.0 within 20 candles.\nStoplossGuard - Frequent Stoploss Guard, 10 stoplosses within 20 candles.'}

So only the first partial config is used to configure the protection plugin, missing values are filled with standard values. The second partial config file is not used.

Combining both parts into one configuration file will solve the problem.

I guess that this is minor problem affecting almost nobody, except my strange setup. 
But maybe it can be fixed without to much effort.

Thanks for your work and effort on freqtrade:

**Comment by xmatthias** [comment]
This is not a supported scenario (and i doubt we'll ever support this, as it'll create very unclear results.

`protections` is seen as one configuration key/entry (of type list/array) - so the last instance will overwrite prior instances.
For `pair_whitelist` / `pair_blacklist` exactly the same would happen - and having a `pair_whitelist` (with pairs!) in both configurations would also only keep the values from the last configuration, and would not merge the 2 together.

While for pair_whitelist / pair_blacklist this might still work as the sequence is not "that" relevant (even though for pair_whitelist, it really is if you don't use any other pairlists), for `protections` (and even more so for `pairlists`) combining the array would be problematic, as it's would not be obvious in which sequence the 2 keys would be combined, and the order of the array will be important.

**Comment by ziegi** [comment]
Ok, I see,
I also found the documentation saying this:
`Configuration parameters defined in the latter configuration files override parameters with the same name defined in the previous configuration files specified in the command line earlier.`
