### ISSUE TITLE
Issue with test_optimize_reports.py

### ISSUE THREAD

**Issue by nas-** [freqtrade/freqtrade#4161]
## Describe your environment

  * Operating system: ____ Windows 10
  * Python Version: _____ (`python -V`) Python 3.9.1
  * CCXT version: _____ (`pip freeze | grep ccxt`) Irrelevant, but 1.39.79
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker) 2020.12
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

The test at [L124](https://github.com/freqtrade/freqtrade/blame/7a628432a85a4136f4dbc542d83274e078ed722b/tests/optimize/test_optimize_reports.py#L124) fails on windows 10 + timezone UTC+1.
This is simply because calling _Arrow.fromtimestamp(0).datetime_ fails on windows
It is somewhat related to [this](https://github.com/arrow-py/arrow/issues/668) issue presented in arrow repo, + [this SO issue](https://stackoverflow.com/questions/36179914/timestamp-out-of-range-for-platform-localtime-gmtime-function) as windows has problems handling negative timestamps.

The proposed solution would be to replace every call of fromtimestamp(0) to fromtimestamp(86400) (24 hours) so to avoid any issue in timezones from UTC+1 to UTC +12

### Steps to reproduce:

  1. Be in timezone UTC+1
  2.  in python terminal from arrow import Arrow; Arrow.fromtimestamp(0).datetime

### Observed Results:

  * What happened? > the test fails
  * What did you expect to happen? > expected the test to pass
 
Note that in my experience the problem is limited to the test, to does not have any effect on the normal operation of the program.
I also understand that this problem is windows specific, while the program is mostly targeted to be run under Linux systems.

### Relevant code exceptions or logs

optimize\test_optimize_reports.py:124: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\venv\lib\site-packages\arrow\arrow.py:189: in fromtimestamp
    dt = datetime.fromtimestamp(timestamp, tzinfo)
..\venv\lib\site-packages\dateutil\tz\_common.py:144: in fromutc
    return f(self, dt)
..\venv\lib\site-packages\dateutil\tz\_common.py:258: in fromutc
    dt_wall = self._fromutc(dt)
..\venv\lib\site-packages\dateutil\tz\_common.py:222: in _fromutc
    dtoff = dt.utcoffset()
..\venv\lib\site-packages\dateutil\tz\tz.py:222: in utcoffset
    if self._isdst(dt):
..\venv\lib\site-packages\dateutil\tz\tz.py:291: in _isdst
    dstval = self._naive_is_dst(dt)

**Comment by xmatthias** [comment]
> I also understand that this problem is windows specific, while the program is mostly targeted to be run under Linux systems.

That's not really true, however installation under windows is quite a pain - for which reason we recommend to use WSL2 instead - as the installation is easier in that case.
Once you have it installed (especially the dependencies), windows will work just fine.

How did you install python on your windows system? is it a conda installation? native python ... some other distribution?

I'm asking because we have CI running on windows (although not on 3.9 due to installation problems) and i've never seen this issue before.
i'm also running tests manually on my windows box from time to time (also in UTC+1 or UTC+2 - depending on the temperature outside) - and i've never seen this fail before.

**Comment by nas-** [comment]
> How did you install python on your windows system? is it a conda installation? native python ... some other distribution?

Just native python, nothing too fancy. Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
I am using venv to manage the library, so no conflicts.

Anyhow, this issue with the dateutil library is exactly the same problem:  [here](https://github.com/dateutil/dateutil/issues/197)
Users there report the exact same problem that I am seeing. In this  [other issue](https://github.com/dateutil/dateutil/issues/434#issuecomment-596234183) they mention that they found a fix for windows 7+, but it will be in next release of dateutil, which is not out yet.

**Comment by xmatthias** [comment]
The funny thing is - it's not even "really" relevant to use exactly this method on windows - there's other methods that archive the same exact thing.
