### ISSUE TITLE
freqtrade - ERROR - Impossible to load Strategy 'samplestrategy'. This class does not exist or contains Python code errors.

### ISSUE THREAD

**Issue by manvalorian** [freqtrade/freqtrade#4175]
My Python tells me there are problem with the sample strategy - to be more precise 
![grafik](https://user-images.githubusercontent.com/77176486/104072744-4f647180-520c-11eb-8924-d4d2e2ac1064.png)

XXXXXXXXXXXXX> docker-compose run freqtrade backtesting --timerange=XXXXXXXX- --strategy samplestrategy
Creating ft_userdata_freqtrade_run ... done
.
.
.
.

2021-01-08 22:39:39,475 - freqtrade - ERROR - Impossible to load Strategy 'samplestrategy'. This class does not exist or contains Python code errors.

**Comment by raphant** [comment]
Make sure the name matches (case-sensitive) the name of the class, not the .py file name.

Example: `samplestrategy.py` with class name `SampleStrategy` will be loaded as `--strategy SampleStrategy`

**Comment by xmatthias** [comment]
Please fill out the issue template (it's good practice and avoids unnecessary back and forth).

Should information from the template be necessary and it is not provided, i'd simply close the issue.

---

The screenshot just shows that you didn't tell vscode the correct virtual environment.

As mentioned above, the strategy parameter is  case sensitive.

you can use `freqtrade list-strategies` to find out how the strategies in your directory are called.
