### ISSUE TITLE
UP/DOWN wildcards for whitelist

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#4177]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

After having the "UP/DOWN" token wildcard feat. for the blacklist, it would be very helpful having the same for the whitelist to filter / unfilter leveraged markets

**Comment by xmatthias** [comment]
I'm labling this as "good first issue" - which means i'll leave it open for an undefined period of time without working on it myself.
This can be a good issue for new contributors to freqtrade.

The logic for the pairs is available (used by blacklist) - and would simply need to be implemented to StaticPairlist - which makes this a pretty simple, quick issue.
