### ISSUE TITLE
ohlcv, historical_data, different timeframes, debugging, daily log rotate

### ISSUE THREAD

**Issue by YuriyTigiev** [freqtrade/freqtrade#4178]
Hello, 

I didn't find answers to my questions in the documentation.

I would like to set a simple business rule for testing in the populate_buy_trend function.

1) ohlcv['close']['last_candle'] < ohlcv['close']['prev_candle']. 
How to access ohlcv data and how it sorted?

2) rsi(timefame='1h', timeperiod=14) > 35 & rsi(timefame='5m', timeperiod=14)  > 35
Is it possible to use two different timeframes in one strategy? If yes, how to prepare data and access them? 

3) rsi['last'] > rsi['prev']. How to access to historical rsi values and how them sorted?

4) How to debug strategy for the docker version? I would like to see how to evaluate the parameters in the function.

5) How to configure daily logrotate for the logs?

**Comment by xmatthias** [comment]
1) we provide documentation and sample strategies. The answer is in either / both of these (also see below on using google to find simple pandas answers).
2) use the [documentation](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-informative_pairs).
3) Please learn how pandas work. While freqtrade strategies are heavily based on pandas, we do not provide support for simple pandas questions that can easily be googled.

5) `--logfile abcd.log` will log to this file in a rolling fashion. It's not daily but based on filesize and will keep 10 logs.
If that's not what you look for, please use google to find out how to configure logrotate - as this is not freqtrade related.

Keep in mind that this is a free, open source project, with people donating their time to support and move the project forward.
Therefore, i expect some self-research before asking questions that can be found in the documentation and / or via google, as it's wasting contributors time that would be better spent improving the bot / fixing bugs.

Thanks for your understanding.

(side note: Please get used to filling out the issue template. It's there for a reason, and sometimes answers will depend on the version you have, Filling the template out will take you less than 1 minute, and will avoid unnecessary back and forth).

**Comment by YuriyTigiev** [comment]
Thank you for your attention and support.
