### ISSUE TITLE
Indicator "ema50" ignored despite plot_config 

### ISSUE THREAD

**Issue by gendrelom** [freqtrade/freqtrade#4179]
## Describe your environment

  * Operating system: WIndows 10
  * Freqtrade Version: 2020.12 in Docker
  
## Your question
Hi! I want to plot ema50 using this command:
`docker run -d --name freqtrade_plot -v ${pwd}/user_data/strategies/strategy_config.json:/freqtrade/config.json -v ${pwd}/user_data:/freqtrade/user_data -v ${pwd}/tradesv3.dryrun.sqlite:/freqtrade/tradesv3.sqlite freqtrade_plot plot-dataframe --strategy Strategy1 -p ETH/BTC  --indicators1 ema50`
I also added this in the strategy file itself:
```
    plot_config = {
        'main_plot': {
            "EMA50": {
                'ema50': {'color': 'blue'},
            }
        },
        'subplots': {
        }
    }
```
But output says: `freqtrade.plot.plotting - INFO - Indicator "ema50" ignored. Reason: This indicator is not found in your strategy.`
After that, I get a plot without this indicator. What am I doing wrong?

**Comment by xmatthias** [comment]
well your strategy must create a column "ema50" ... 

ALso make sure you got no spaces before / after the name (within the quotes).

while it's clear to you and me what this entails, for the plotting module it's just a column in the dataframe like any other.

**Comment by gendrelom** [comment]
Thanks! This makes sense and works
