### ISSUE TITLE
Outdated History on Bittrex

### ISSUE THREAD

**Issue by Andi1990** [freqtrade/freqtrade#4181]
## Describe your environment

  * Operating system: Debian 10
  * Python Version: latest
  * CCXT version: latest
  * Freqtrade Version: latest develop
  
## Your question
I am not able to trade on bittrex since I get the following log for all pairs:
`freqtrade.strategy.interface - WARNING - Outdated history
`
My server is ntp synchronized:
```
$ timedatectl
               Local time: Sun 2021-01-10 07:42:50 UTC
           Universal time: Sun 2021-01-10 07:42:50 UTC
                 RTC time: Sun 2021-01-10 07:42:51
                Time zone: Etc/UTC (UTC, +0000)
             System clock synchronized: yes
              NTP service: active
             RTC in local TZ: no
```

Does anybody have the same issue?

**Comment by xmatthias** [comment]
if you get it for all pairs, it would indicate that the exchange is down (not sure for bittrex - doesn't appear to have been down today).

Especially on bittrex, this can also happen if a candle had no volume, but in this case, it'd be usually happen with one pair only.

**Comment by Andi1990** [comment]
this is really odd. For instance, I got the following warning a few minutes ago:
`2021-01-10 10:20:39,701 - freqtrade.strategy.interface - WARNING - Outdated history for pair BTC/USDT. Last tick is 14720 minutes old`
Especially for a market like BTC/USDT, this is very unlikely. All ticks (from all pairs) are exactly 14720 minutes old.

**Comment by xmatthias** [comment]
well no, if all pairs get the same "outdated" - then it's for sure not a "no volume" problem.

what's your ccxt version (latest is NOT an  appropriate version - and with ccxt, "latest" changes multiple times per day, usually).

**Comment by Andi1990** [comment]
May ccxt version is 1.40.25
Since I have installed freqtrade via docker-compose (develop image), I am not sure how to update ccxt.

**Comment by xmatthias** [comment]
it's not so much about updating, but about knowing which version you're using - so we can try to recreate what you're experiencing.

Did you try to get the container down / up again? 
I've just tried and the timestamp i get from ccxt is as expected (correct format, expected time).

you can also try to run superverbose mode (`-vvv`) - which will show the ccxt requests / responses too.

**Comment by xmatthias** [comment]
It's strange as the time you highlight (14720) would be exactly 10 days.

Can you paste a "more complete" log of this issue - like a few (10) lines before this message - maybe there's something else that's wrong.

I've just tested this for bittrex again, and for me it's working just fine - creating order after order ... 

Best also test this in dry-run with the provided SampleStrategy - to exclude the possibility that the strategy does something to the dataframe (although this should raise another warning too, unless you disabled that warning).

**Comment by mczero80** [comment]
I can confirm this issue. For me its 14700 minutes. The process died after a few hours. I even tested it in dry run mode with the Simple strategy and updated freqtrade with "./setup.sh --update". Its the same. Then I reduced the pairs and max_open_trades to just one, did nothing. I have attached some log lines.

I think I had the same problem with the Stex exchange, I am not sure at the moment. I can attach further information and also test with Stex if you want.

[log.txt](https://github.com/freqtrade/freqtrade/files/5818966/log.txt)

**Comment by mczero80** [comment]
I did a test with a fresh installation.

`git clone https://github.com/freqtrade/freqtrade.git`
`cd freqtrade`
`./setup.sh --install`

All questions from setup.sh were answered with "N".
Then copied config.json.example to config.json and copied Simple.py to the strategies folder.
Then ran it with:

`
source .env/bin/activate; freqtrade trade --logfile ./log.txt --config config.json --strategy Simple
`

The issue occured again.

**Comment by xmatthias** [comment]
maybe it's region (IP) related? 

i know exchanges have different regulations for the US ... maybe bittrex blocks ie based on this ... ? 
I'm in europe, so kinda difficult to test (as said, for me it works just fine ... without this problem at all).

**Comment by mczero80** [comment]
I'm in europe too, I don't know... hmm.
Wasn't there something that the system clock must be very precise?

**Comment by xmatthias** [comment]
yes - but that's a different error.
your clock won't be off by 10 days (i hope) ... it might be off by a few seconds - in which case authenticated (!) calls will send you a "timestamp wrong" on SOME exchanges. I've never seen that error on bittrex though - so not sure if it's impacted by it (i know it from binance only, if i'm honest).

It's a security feature by the exchange, really ...

**Comment by Andi1990** [comment]
I really don't know what's the reason behind that error. I'll let you know if I find it out.

**Comment by mczero80** [comment]
Thank you. Otherwise, I am very happy with Freqtrade!

**Comment by sndvll** [comment]
Just want to chip in on this. I have also had this issue with Bittrex in dry run running on docker both on my Mac and and my Pi, located in Europe, but not in a GCP instance running in the US (same config, same strategy). Thanks to this thread I connected my Mac via VPN through the US and now it works as expected, so @xmatthias is probably right that this is region related.

**Comment by xmatthias** [comment]
@sndvll thanks for giving this test a go.

Funnily, i don't have this problem (never had) - and i'm in europe, not in the US (and i'm not using a US based vpn or something either) :laughing:

**Comment by sndvll** [comment]
Yeah really weird. Maybe it's country related. I'm in Sweden, but I do not have any trouble trading manually on Bittrex via either the app or browser 🤷🏼‍♂️
Maybe the Bittrex support is where to go, or just use Binance which works.

**Comment by mczero80** [comment]
I'm in Germany, and Binance works as expected. Yes we should contact the Bittrex support, and leave a note here

**Comment by xmatthias** [comment]
yeah, but i think that should be done by someone who has the problem ... if they make me test, i can't even say it didn't work before :laughing:

**Comment by mczero80** [comment]
You are correct... Do you or anyone here have experience with a exchange support? I must think a bit about it and collect what we have

**Comment by xmatthias** [comment]
just send them what's not working - also reporting that it does work when coming from an other IP (like from the US).

You'll end up with first level support initially anyway ... so ...

**Comment by mczero80** [comment]
I now have a support ticket, let's see what they will respond.

**Comment by mczero80** [comment]
I got a message that it takes longer to process the request. Will update here.

**Comment by Andi1990** [comment]
For me a us-based instance doesn't work either.. I am really curious about the response from bittrex.

**Comment by Andi1990** [comment]
After a further analysis of the problem, I think that I found the reason: It looks like the error occurs only at a timeframe of 1h. When I switch to e.g. 5m in my strategy it works as expected...

**Comment by mczero80** [comment]
I also had a 1h timeframe running. Will do some testing when I find time again!

**Comment by Andi1990** [comment]
@xmatthias could you check if 1h timeframe also works in your case?

**Comment by mczero80** [comment]
Can confirm, 5m timeframe works, 1h not. Also interested if @xmatthias can do a test

**Comment by xmatthias** [comment]
interresting ... seems like a bug in ccxt, which seems to be removing the wrong candles ...

**Comment by Andi1990** [comment]
is this already transmitted to ccxt or should I take care of that?

**Comment by xmatthias** [comment]
Did already yesterday ...
https://github.com/ccxt/ccxt/issues/8445

**Comment by xmatthias** [comment]
while i do belive that the original problem stems from ccxt removing the wrong candles, we can work around this in freqtrade.

#4367 will allow candle-limits per timeframe (which is required for bittrex) - and will subsequently use this limit to download the full list.

One important note:
Due to how bittrex returns candles (different limits per timeframe) - downloaded data (which you downloaded before this PR) for 5m periods might have gaps - so make sure to check your downloaded data before relying on a backtest from this.

You should see this as **"Missing data fillup"** during backtesting, if the numbers seem excessively high (low numbers are usually exchange downtimes - but if you have half of the data missing, it's a sign that something is wrong.

**Comment by Andi1990** [comment]
Unfortunately, the bug still occurs on my side. I have pulled the latest develop-image (version='docker-3110d2db') but still on timeframe = '1h' I get the following warning for all pairs on bittrex:
freqtrade.strategy.interface - WARNING - Outdated history for pair BTC/USDT. Last tick is 14742 minutes old

Can anybody confirm this?

**Comment by xmatthias** [comment]
3110d2db is from february 9th ... 

i fixed this on the 14th, so you're not using the latest image. best use `docker-compose pull` to get the latest image.

**Comment by Andi1990** [comment]
ok but on dockerhub the latest push on develop tag was 7 days ago. I cannot get the latest version via pull.

**Comment by xmatthias** [comment]
interresting - nice catch - i hadn't noticed that before (but i also don't see what would've broken this ...)

will investigate - you can however use latest - which is (should be) identical to develop anyway

edit: works again now for develop and develop_plot too.

**Comment by mablue** [comment]
https://github.com/freqtrade/freqtrade/issues/1811#issuecomment-487452353

**Comment by xmatthias** [comment]
@mablue Please don't revive issues that are solved and almost a year old. That's pointless, and will lead to meaningless notifications to everyone involved here.
