### ISSUE TITLE
Edge positioning "Active pair whitelist is empty"

### ISSUE THREAD

**Issue by steltz** [freqtrade/freqtrade#4182]
I turned on Edge positioning for my strategy and it greatly improved my ROI during back testing. However, when I try to run the strategy in dry run mode, I keep getting "Active pair whitelist is empty" in the console.

Can someone explain to me why this is happening?

**Comment by steltz** [comment]
Does it mean that with my strategy, it can't find any pairs that have an expectancy over 1? Basically my strategy sucks? Is it because of the recent huge price increase? What I don't understand is why it is successful in back testing against last 3 months of data

**Comment by xmatthias** [comment]
Best read the [edge documentation](https://www.freqtrade.io/en/latest/edge/) from top to bottom (multiple times). It's quite difficult and we know it - so consider it an advanced feature.


Depending on your strategy, you'll have to tune different parameters (for example `minimum_expectancy` / `min_trade_number` and `calculate_since_number_of_days`).

With defaults, edge will look at the last 7 days, require a `minimum_winrate` of 60% and a `minimum_expectancy` of 0.20, at least 10 trades for this pair (and `max_trade_duration_minute` of 1 day - so trades longer than this are ignored).

The correct parameters for these settings will heavily depend on your strategy. 
The defaults should work for 5m timeframes - but if you're using 1h or longer timeframes, you might want the strategy to look back for longer than 7 days - or require fewer trades (or both).
Also, if your strategy tends to make 1 trade per day - then requiring 10 trades in 7 days will not work either (i guess you get the picture ...).

However, this "finetuning" will depend  on your strategy (and timeframe) - looking back too long will make you look at a potentially completely different market, while not looking back enough can result in an almost always empty pairlist.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.

**Comment by brunof20** [comment]
I have same message but not enabled edge. I had to restart Docker and it stopped showing the message.
