### ISSUE TITLE
stochastic is not equal tradingview stochastic

### ISSUE THREAD

**Issue by YuriyTigiev** [freqtrade/freqtrade#4184]
## Describe your environment

  * Operating system: Microsoft Windows [Version 10.0.19042.685]
  * I'm using a docker with the latest docker version of freqtrade
  * docker-compose version 1.27.4, build 40524192
  * docker-py version: 4.3.1
  * CPython version: 3.7.4
  * OpenSSL version: OpenSSL 1.1.1c  28 May 2019
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Stochastic is not equal tradingview stochastic for the same datetime, timeframe = 5m and timeperiod = 14
I thought that  dataframe['fastk'] = stoch(close,high,low,14)
Other indicators (sma10, team, rsi) that I have tested are equal. 

--- trading view pine script code 

```
//@version=4
study("My Script")
plot(stoch(close,high,low,14), color=color.blue)
plot(stoch(close,close,close,14), color=color.red)

```

### Steps to reproduce:

```
        stoch = ta.STOCH(dataframe, timeperiod=14)
        dataframe['slowd'] = stoch['slowd']
        dataframe['slowk'] = stoch['slowk']

        # Stochastic Fast
        stoch_fast = ta.STOCHF(dataframe, timeperiod=14)
        dataframe['fastd'] = stoch_fast['fastd']
        dataframe['fastk'] = stoch_fast['fastk']


    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                (dataframe['rsi'] < 60) &
                (dataframe['fastd'] < 60) &
                (dataframe['sma10diff']          > dataframe['sma10diff'].shift(1)) &
                (dataframe['sma10diff'].shift(1) > dataframe['sma10diff'].shift(2)) &
                
                #(qtpylib.crossed_above(dataframe['rsi'], 35)) &  # Signal: RSI crosses above 30
                (dataframe['tema'] <= dataframe['bb_middleband']) &  # Guard: tema below BB middle
                (dataframe['tema'] > dataframe['tema'].shift(1)) &  # Guard: tema is raising
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'buy'] = 1
        
        if(metadata['pair'] == 'BTC/USDT'):
            pd.options.display.max_columns = None
            #print(metadata['pair'])
            print(dataframe.loc[:,['date','close','high','low','fastd', 'fastk', 'slowd', 'slowk']].tail(15))
        return dataframe
```

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

```

# | date | close | high | low | fastd | fastk | slowd | slowk | TV RSI(close,high,low) | TV RSI(close,close,close)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
984 | 2021-01-10 13:25:00+00:00 | 39922.18 | 39951.09 | 39827.42 | 75.575196 | 68.536034 | 81.661770 | 75.575196 |   |  
985 | 2021-01-10 13:30:00+00:00 | 40005.49 | 40126.00 | 39830.12 | 72.622283 | 74.887995 | 76.537851 | 72.622283 |   |  
986 | 2021-01-10 13:35:00+00:00 | 39822.35 | 40020.79 | 39785.07 | 51.452942 | 10.934796 | 66.550140 | 51.452942 |   |  
987 | 2021-01-10 13:40:00+00:00 | 39834.84 | 40121.33 | 39790.01 | 33.473699 | 14.598305 | 52.516308 | 33.473699 |   |  
988 | 2021-01-10 13:45:00+00:00 | 39782.75 | 39921.75 | 39745.35 | 11.786133 | 9.825299 | 32.237591 | 11.786133 |   |  
989 | 2021-01-10 13:50:00+00:00 | 39760.00 | 39786.07 | 39678.00 | 14.242392 | 18.303571 | 19.834074 | 14.242392 |   |  
990 | 2021-01-10 13:55:00+00:00 | 39800.90 | 39800.94 | 39710.19 | 18.616961 | 27.722013 | 14.881829 | 18.616961 |   |  
991 | 2021-01-10 14:00:00+00:00 | 39573.84 | 39812.48 | 39502.00 | 19.208405 | 11.599632 | 17.355919 | 19.208405 |   |  
992 | 2021-01-10 14:05:00+00:00 | 39669.17 | 39728.99 | 39570.00 | 26.382577 | 39.826087 | 21.402648 | 26.382577 |   |  
993 | 2021-01-10 14:10:00+00:00 | 39677.91 | 39739.26 | 39602.99 | 36.027717 | 56.657434 | 27.206233 | 36.027717 |   |  
994 | 2021-01-10 14:15:00+00:00 | 39470.44 | 39680.00 | 39400.67 | 37.808600 | 16.942279 | 33.406298 | 37.808600 |   |  
995 | 2021-01-10 14:20:00+00:00 | 39596.12 | 39599.98 | 39466.67 | 40.353640 | 47.461208 | 38.063319 | 40.353640 |   |  
996 | 2021-01-10 14:25:00+00:00 | 39764.82 | 39825.34 | 39596.11 | 50.050807 | 85.748934 | 42.737682 | 50.050807 |   |  
997 | 2021-01-10 14:30:00+00:00 | 39758.98 | 39847.26 | 39748.00 | 71.147523 | 80.232428 | 53.850657 | 71.147523 | 53.93 | 49.40
998 | 2021-01-10 14:35:00+00:00 | 39548.92 | 39760.00 | 39454.23 | 66.392453 | 33.195996 | 62.530261 | 66.392453 | 14.67 | 20.44



```

**Comment by xmatthias** [comment]
Feel free to open this issue against the [ta-lib](https://github.com/mrjbq7/ta-lib) repository to see if they are able to help you.

The methods you are using are imported from ta-lib and are not part of freqtrade, but of ta-lib (or rather, the underlying C wrapper), therefore we will not be able to assist you with this.



However, as mentioned elsewhere - many libraries implement indicators to match the author's formula. If tradingview deviates from this, you should raise it with them, not with the libraries (but this is just a sidenote / personal comment).
Your test should therefore really be to find the original paper describing the indicator, compare it with tradingview, and if it doesn't match, complain to tradingview.

**Comment by YuriyTigiev** [comment]
Ok. I will open a ticket, just can you share which paramers (dataframe columns) use the implemented stoch indicator?

**Comment by xmatthias** [comment]
honestly, this too, is in the ta-lib documentation. 
I THINK the default is always `price='close'` for the abstract interface (which we're using) - but it can be different for single indicators if the original author intended that.

**Comment by YuriyTigiev** [comment]
I have coppied the stoch  description from talib documentation. I still have the question - which parameters pass the freqtrade to these functions? I should provide more information for ta-lib team.


STOCH - Stochastic

slowk, slowd = STOCH(high, low, close, fastk_period=5, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)

Learn more about the Stochastic at tadoc.org<http://tadoc.org>.

STOCHF - Stochastic Fast

fastk, fastd = STOCHF(high, low, close, fastk_period=5, fastd_period=3, fastd_matype=0)

Learn more about the Stochastic Fast at tadoc.org<http://tadoc.org>.



Sent via the Samsung Galaxy S8+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by xmatthias** [comment]
I think you're not properly understanding how this works.

Freqtrade does not call ta.STOCH at all (nor any other indicator, apart from some tests, which however are not relevant for day-to-day operations).
It's your strategy that calls it - so you should know how you are calling the indicator.

If (optional) parameters are not explicitly set, then the default will be used.

```
slowk, slowd = STOCH(high, low, close, fastk_period=5, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)
```

since we're using the abstract interface, the first 3 parameters (high, low, close) will be combined into "dataframe". 
you can set the remaining parameters as you see fit.

source: [ta-lib docs](http://mrjbq7.github.io/ta-lib/func_groups/momentum_indicators.html).
