### ISSUE TITLE
Up-to-date clock

### ISSUE THREAD

**Issue by drpaprika** [freqtrade/freqtrade#4191]
* Operating system: Windows
  * Python Version: 3.8

Hi,
The README and the docs say that :

> Up-to-date clock
> The clock must be accurate, synchronized to a NTP server very frequently to avoid problems with communication to the exchanges.

How can I do that ? Especially with windows admin priviledges that prevent from updating the clock.

Thanks !
DrPaprikaa

**Comment by xmatthias** [comment]
Windows should do this by default (i think) - i can click on the clock (bottom right corner) and go to "date and time settings" (the link at the bottom of the opening popul).

From there, you should have a "sync now" button - which (in my case) syncs to time.windows.com.

I think windows does this automatically at certain periods - but i also think that it CAN be disabled.

Side note:
if you're not administrator on your machine, then i'd suggest to not use this machine for freqtrade as it suggests it's a company machine - and almost all companies i know will forbit people to use the company assets to partecipate in trading (crypto).

**Comment by nodwan** [comment]
i‘m running freqtrade with my raspberry 4, i‘was install a very correct working realtimeclock. what automatical sync the time.

**Comment by xmatthias** [comment]
I'm not quite sure what you intend with this.

There is no realtimeclock necessary, only a time sync daemon (on linux for example ntpd or chronyd) to get the time syncronized at regular intervals.
Even if the "hardware" time slightly drifts (which happens on almost any computer) - these daemons make sure the clock is updated to the correct time.

Windows has the same, but builtin (and enabled by default, if i remember correctly).
when using Windows with WSL2, there are some difficulties to keep the clock uptodate - best consult the internet, there's multiple help / issues in relation to this (simply use `wsl2 uptodate clock"). 

It appears to be a bug in WSL2, so answers to this will most likely vary over time.

**Comment by drpaprika** [comment]
Thanks for your answers ! So if I understand correctly, no action is required to have a synchronized clock ?

**Comment by xmatthias** [comment]
no, i said it depends, and it's up to you to verify it's not disabled for your windows system.
