### ISSUE TITLE
TensorFlow integration

### ISSUE THREAD

**Issue by nodwan** [freqtrade/freqtrade#4194]
**It will be great if a TensorFlow integration can be happen. if i have a wish free ... this will be my wish ...** 

deep learning is the biggest goal in the next years ... if we can use it, it is free, opensource and available.

please make this happen ... 

thx

**Comment by xmatthias** [comment]
There is nothing preventing you from integrating / using tensorflow in your strategy.

For freqtrade itself (the core-code, excluding strategies), we do not have plans to use tensorflow for anything, as it would be overkill (and i don't see where we could benefit from this).

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
