### ISSUE TITLE
Incorrect Buy Order with Dynamic Stake Amounts

### ISSUE THREAD

**Issue by compulshun** [freqtrade/freqtrade#4198]
## Describe your environment

  * Operating system: Ubuntu Server 20.04 LTS
  * Python Version: Python 3.8.5 (`python -V`)
  * CCXT version: 1.40.25 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop-61d225a5 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

When using dynamic stake amounts in a dry-run, no trades are placed as it seems the calculations are adding an extra decimal place, making the buy orders too small.

### Steps to reproduce:

  1. Set up the config as such:
  {
    "max_open_trades": 20,
    "stake_currency": "BTC",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.20,
    "fiat_display_currency": "CAD",
    "timeframe": "5m",
    "dry_run": true,
    "dry_run_wallet": 0.00137,
    "cancel_open_orders_on_exit": true,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
  2. Attempt dry-run trading with any strategy that will process buy orders.
  3. Get this error when it attempts to make a purchase:
  freqtrade.freqtradebot - WARNING - Can't open a new trade for BCH/BTC: stake amount is too small (1.37e-05 < 0.0001356281618315227)
  
### Observed Results:

  * What happened? It attempted to make a purchase for 1.37e-05 (0.0000137, 0.1% of the dry-run wallet balance and below Binance's minimum of 0.0001 BTC)
  * What did you expect to happen? It to make a purchase for 1.37e-04 (0.000137, 1% of the dry-run wallet balance)

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

2021-01-11 16:39:55,350 - freqtrade.worker - INFO - Bot heartbeat. PID=362272, version='develop-61d225a5', state='RUNNING'
2021-01-11 16:40:11,327 - freqtrade.wallets - INFO - Wallets synced.
2021-01-11 16:40:11,332 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 1.37e-05 ...
2021-01-11 16:40:11,332 - freqtrade.freqtradebot - INFO - Executing Buy for BCH/BTC
2021-01-11 16:40:11,332 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2021-01-11 16:40:11,497 - freqtrade.freqtradebot - WARNING - Can't open a new trade for BCH/BTC: stake amount is too small (1.37e-05 < 0.0001356281618315227)

**Comment by xmatthias** [comment]
Well your configuration will assume a starting balance fo 0.00137.
with `tradable_balance_ratio` - you're defining the balance available to the bot as 20% - so you'll have `0.00137 * 0.2 == 0.000274 ` as "available" balance.

Your single stake is then `0.000274 / 20` (trades) - which comes out as `1.37e-05` - which is `0.0000137` ... and is most around a factor 10 below the exchange's minimum trade limit (although this limit will vary between different exchanges).

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
