### ISSUE TITLE
Howto enable edge in config file

### ISSUE THREAD

**Issue by nodwan** [freqtrade/freqtrade#4199]
I‘m using the lastest version config_full.json for binance

i‘m new with freqtrade, and i‘want try out the „edge“ this config is enabled with static pairs, so my question is 
what i have to change for get the edge option running in this config?

thx for your Patience

**Comment by xmatthias** [comment]
Honestly, read and get familiar with the [edge documentation](https://www.freqtrade.io/en/latest/edge/).

Simply enabling - set `edge.enabled = true` in the configuration. 
You will however need to have a strategy that works for edge, have the edge parameters tuned to work for your strategy. 
The documentation will tell you all you need to know - but you need to take the time to read it from top to bottom until you understand it fully.

**Comment by nodwan** [comment]
Thx for replay, 

edge.enabled = true

it was my first choice but it don’t work, if i start freqtrade, it‘s stop and say, not with static pairs and VolumenPairList. 
So the question, what is to do, put all this section out about pairlists ... or stet the method to „edge“ 

pairlists": [
{"method": "StaticPairList"},
{
"method": "VolumePairList",
"number_assets": 20,
"sort_key": "quoteVolume",
"refresh_period": 1800
},
{"method": "AgeFilter", "min_days_listed": 10},
{"method": "PrecisionFilter"},
{"method": "PriceFilter", "low_price_ratio": 0.01, "min_price": 0.00000010},
{"method": "SpreadFilter", "max_spread_ratio": 0.005},
{
"method": "RangeStabilityFilter",
"lookback_days": 10,
"min_rate_of_change": 0.01,
"refresh_period": 1440
}
],

**Comment by xmatthias** [comment]
well `pairlists` are irrelevant when using edge, as edge provides it's own, final version of the pairlist - calculated based on `pair_whitelist`.
So you can keep the pairlists as an empty array, remove it completely from the configuration, or leave only the static-pairlist in. It's not going to be used.

We explicitly check for VolumePairlist, as this is known to not work / cooperate, and would raise wrong expectations in users.

**Comment by nodwan** [comment]
thx, for help, i‘will try it out!

**Comment by xmatthias** [comment]
Closing this as i think the question has been answered.

Feel free to comment below / reopen if it's still unclear.

**Comment by YuriyTigiev** [comment]
How to implement filters below for strategies when using edge?

{"method": "PrecisionFilter"},
{"method": "PriceFilter", "low_price_ratio": 0.01, "min_price": 0.00000010},
{"method": "SpreadFilter", "max_spread_ratio": 0.005},

**Comment by xmatthias** [comment]
edge provides it's own pairlist based on pair_whitelist.

All configured pairlists are therfore ignored.

**Comment by YuriyTigiev** [comment]
> edge provides it's own pairlist based on pair_whitelist.
> 
> All configured pairlists are therfore ignored.

I understand that, but my question - how to in my strategy I can filter some pairs which not meet the criteria described above?

I can run test-pairlist and copy paste generated list to static list, but it is a Work Around.

**Comment by xmatthias** [comment]
you can't at the moment.
Edge should be changed to include pairlists - but it's currently not implemented and i don't see myself having time for that in the near future. You can subscribe to #4298 for progression on this as it's basically the same problem (edge also does not do pair validation but accepts whatever you give it).

**Comment by YuriyTigiev** [comment]
ok. understand.
Is it possible technically (theoretical) - write some code (conditions) in strategies that will be doing dynamic filtering?

**Comment by YuriyTigiev** [comment]
VolumePairList + Edge + Protection - real a good combination, I understand that you are very busy. We hope this option will be available in the future. Thank you for your support.
