### ISSUE TITLE
Analyzing the result of Strategy with multiple rules

### ISSUE THREAD

**Issue by YuriyTigiev** [freqtrade/freqtrade#4201]
Hello, 

I would like to run a few different strategies (rules) for the pair BTC/USDT for the one binance account. 
What is an optimal solution/configuration for this case if I would like to make a post-analysis to determine which rule more profitable?
Currently, I use OR logic (rule1 OR rule2 OR rule3) for trading, but I don't know how to split analyze the result of trading.

**Comment by xmatthias** [comment]
I guess you can't - as you're combining them together directly

i guess you can assign each condition to a seperate column `dataframe['cond1'] = (dateframe['rsi'] > 30)` ... and then combine these "cond1/cond2/..." conditions into the buy signal.

That way, you can plot these signals as well - which will make them binary flags of "1 and 0" - allowing you to see which signal triggered a buy (always assume that multiple signals can trigger the same buy).

You could also run multiple strategies (or backtest multiple strategies) and compare results - and then combine them for live.

**Comment by YuriyTigiev** [comment]
As I understand run multiple strategies has one minus - you should have a few binance accounts or you will be banned by exchange because bots will make a huge amount of requests

**Comment by xmatthias** [comment]
not really, as long as you use multiple servers (source IP's) for your actions.
You can run between 2 and 3 bots on one IP (at least on 5m + candles)... i didn't test this for 1m candles though.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
