### ISSUE TITLE
Modify config.json

### ISSUE THREAD

**Issue by tutecode** [freqtrade/freqtrade#4202]
I ran out of money, in my dry-run, and I want to modify it, how can I do it? And I also want to add coins to the blacklist.

**Comment by xmatthias** [comment]
stop the bot, edit the configuration and then start the bot again.

All settings you need are documented [in the config documentation page](https://www.freqtrade.io/en/latest/configuration/).

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
