### ISSUE TITLE
Common a vertical spike line for a main chart and indicators

### ISSUE THREAD

**Issue by YuriyTigiev** [freqtrade/freqtrade#4203]
Does a "plotting" support a common vertical "spike" line for the main chart and indicators like does the TradingView? It is very comfortable when you can see all values when you move over a mouse on the chart.

https://github.com/plotly/plotly.py/issues/1677

![image](https://user-images.githubusercontent.com/22752322/104409728-5da1ed00-5580-11eb-8f24-b90fad71f994.png)

**Comment by xmatthias** [comment]
First of all, transferring this issue to the main repository, as it's nothing to do with the strategies.

---

@YuriyTigiev (pinging you here so you refind this issue eventually)
As you already found the upstream issue, it doesn't appear to be something that the underlying technology (plotly) supports - so the probability that freqtrade supports it is not very high.

That said, it's also quite unlikely that we'll do any major changes to the plotting module in the near future, as i see the future with [freqUI](https://github.com/freqtrade/frequi).
While it doesn't support the same features just yet (plotting historic data, ...) - it will eventually do so, so please don't expect much movement when it comes to the freqtrade plotting commands (like `plot-dataframe` / `plot-profit`).

What this means is - even if plotly internally will start supporting this - we might not be adding this if it requires major changes. If it's a oneline change - sure, but we'll not invest too much time into the plotting modules anymore.

Hope this makes sense
