### ISSUE TITLE
Random questions about to download-data and backtesting

### ISSUE THREAD

**Issue by FahadAziz** [freqtrade/freqtrade#4204]
Good Morning 

I have few suggestions that could enhance few things here and there.

1- Backtesting and strategy: My understanding is that when you put `{"60": 0}` in strategy file it will sell at whatever return after 60mins. However, this is not the case when backtesting it will show a draw. Is it possible to adjust that?

2- Data Download: Lets say that I downloaded BTC/USDT at 1m interval for the past 60 days. It takes ages to download. If I want to update it, it will again go back and download the whole history from the exchange. My idea is let the code check the last tick downloaded and update forward so it can be faster to update the historical data.

3- This is not an enhancement per say and it could be done now i am not sure. Let us say that I have two strategies that do well in different market conditions. Would it be possible to let the bot switch strategies based on certain indicators?

Thanks

**Comment by xmatthias** [comment]
1) your understanding is incorrect. It'll sell after 60 minutes if profit is > 0. To "always" sell, you should use `{"60": -1}`.

2) again, this is wrong. You can download the data from a year ago (`--days 365`) - and then you run `--days 60` every month (to be sure you have a bit of overlap) - and it'll only download the necessary data. This is also described [in the docs](https://www.freqtrade.io/en/latest/data-download/) in the first "Tip" box.

3) You can do this within your strategy, or by running 2 bots with exclusive conditions (say one uses `dataframe['BTC_adx'] > 50` and the other `dataframe['BTC_adx'] <=50`).

**Comment by FahadAziz** [comment]
Thank you @xmatthias there is a lot to learn about the bot :) 

Regarding point 3, If I were to run two strategies with one bot, is it possible to set different ROIs and stoplosses?

**Comment by xmatthias** [comment]
well you can use the [custom stoploss](https://www.freqtrade.io/en/latest/strategy-advanced/#custom-stoploss-examples) for this i guess.

Not possible for ROI at the moment - in that case, go for 2 bots with 2 strategies.
