### ISSUE TITLE
Issue using Freqtrade on Raspberry Pi using DietPi

### ISSUE THREAD

**Issue by Gdoc1994** [freqtrade/freqtrade#4210]
## Describe your environment

  * Operating system: Diet Pi
  * Python Version: 3.7.2
  * CCXT version: 1.40.30
  * Freqtrade Version: Throws error detailed below when running freqtrade -V
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

When trying to set systemd to keep the bot running 24/7 it encounters fatal error. I'm not sure where the setup_logging_pre should be defined or what it should be defined as.

This is the second time I've installed Freqtrade on the pi, last time the main.py seemed to work, however when I ran the below it would just go to a new command line with nothing happening (example below).

`/home/dietpi/freqtrade/freqtrade/main.py trade -c /home/dietpi/freqtrade/configg.json -s BBRSI_Sharpe -strategy-path /home/dietpi/freqtrade/user_data/strategies --userdir /home/dietpi/freqtrade`

### Steps to reproduce:

  1.  Edit the main.py.
  2. Run `sudo systemctl edit --force --full freqtrade.service`
  3. Enable the service:  `sudo systemctl enable freqtrade.service`
  4. Either run the long path or freqtrade trade -c configg.json -s BBRSI_Sharpe

### Observed Results:

  * What happened? The errors outlined above
  * What did you expect to happen? Expected the bot to run. I should say that before I began this system control step it worked normally.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

First error: `(.env) dietpi@DietPi:~/freqtrade$ freqtrade trade -c configg.json -s BBRSI_Sharpe
Fatal exception!
Traceback (most recent call last):
  File "/home/dietpi/freqtrade/freqtrade/main.py", line 31, in main
    setup_logging_pre()
NameError: name 'setup_logging_pre' is not defined`

Second error returns to command line with nothing executed: `dietpi@DietPi:~/freqtrade$ /home/dietpi/freqtrade/freqtrade/main.py trade -c /home/dietpi/freqtrade/configg.json -s BBRSI_Sharpe -strategy-path /home/dietpi/freqtrade/user_data/strategies --userdir /home/dietpi/freqtrade
dietpi@DietPi:~/freqtrade$`

**Comment by xmatthias** [comment]
Starting freqtrade with `main.py` is  depecated and not recommended.

The error suggests that you've got some mixed version (maybe a new `main.py`, but it's not properly installed).

For quick / easy setup, best go with the [docker-compose](https://www.freqtrade.io/en/latest/docker_quickstart/) installation, which also works on a raspberry with some minor changes (listed in the documentation).

For a regular installation, best make sure that your version is clean (best do a fresh git clone - obviously keeping a backup of your use data) and runn the full installation again.

While we don't test on dietPI, i know it works fine on a raspberry if it's installed correctly.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
