### ISSUE TITLE
Possible of having more than one timeframe data in one strategy?

### ISSUE THREAD

**Issue by sherryxiao1988** [freqtrade/freqtrade#4211]
I am wondering if it's possible to have for example both 15m and 1hour timeframe data for one strategy to generate signal?
Thanks.

**Comment by xmatthias** [comment]
Please search the [documentation](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-informative_pairs) (and [here](https://www.freqtrade.io/en/latest/strategy-customization/#complete-data-provider-sample)) before opening an issue.

**Comment by sherryxiao1988** [comment]
Thanks!
