### ISSUE TITLE
USDT stake currency is not trading on > 100

### ISSUE THREAD

**Issue by chescake** [freqtrade/freqtrade#4212]
* Operating system: Linux Ubuntu 20.04
  * Python Version: 3.8.5
  * CCXT version: ccxt==1.40.30
  * Freqtrade Version: freqtrade develop-adb3fb12
  
I'm unable to trade in binance with USDT as stake currency, if i set 100 as stake amount  buy signal is execute correctly but if the stake amount is more than 100, buy signal is never executed only "freqtrade.wallets - INFO - Wallets synced." message is send it constantly.

I'm doing something wrong?
I created a simple strategy just to test the buy signal and find the stake amount issue.

thanks

Only tested in dry mode.

**config.json:**
`
{
        "max_open_trades": 4,
        "stake_currency": "USDT",
        "stake_amount": 1011,
        "tradable_balance_ratio": 0.25,
        "fiat_display_currency": "USD",
        "amend_last_stake_amount": true,
        "timeframe": "5m",
        "dry_run": true,
        "cancel_open_orders_on_exit": false,
        "unfilledtimeout": {
                "buy": 10,
                "sell": 30
        },
        "bid_strategy": {
                "price_side": "bid",
                "ask_last_balance": 0.0,
                "use_order_book": false,
                "order_book_top": 1,
                "check_depth_of_market": {
                        "enabled": false,
                        "bids_to_ask_delta": 1
                }
        },
        "ask_strategy": {
                "price_side": "ask",
                "use_order_book": false,
                "order_book_min": 1,
                "order_book_max": 1,
                "use_sell_signal": true,
                "sell_profit_only": false,
                "ignore_roi_if_buy_signal": false
        },
        "exchange": {
                "name": "binance",
                "key": "",
                "secret": "",
                "ccxt_config": { "enableRateLimit": true },
                "ccxt_async_config": {
                        "enableRateLimit": true,
                        "rateLimit": 200
                },
                "pair_whitelist": [
                        "ALGO/USDT",
                        "ATOM/USDT",
                        "BAT/USDT",
                        "BCH/USDT",
                        "EOS/USDT",
                        "ETH/USDT"
                ],
                "pair_blacklist": [
                        "BNB/BTC",
                        "BNB/BUSD",
                        "BNB/ETH",
                        "BNB/EUR",
                        "BNB/NGN",
                        "BNB/PAX",
                        "BNB/RUB",
                        "BNB/TRY",
                        "BNB/TUSD",
                        "BNB/USDC",
                        "BNB/USDS",
                        "BNB/USDT"
                ]
        },
        "pairlists": [{ "method": "StaticPairList" }],
        "edge": {
                "enabled": false,
                "process_throttle_secs": 3600,
                "calculate_since_number_of_days": 7,
                "allowed_risk": 0.01,
                "stoploss_range_min": -0.01,
                "stoploss_range_max": -0.1,
                "stoploss_range_step": -0.01,
                "minimum_winrate": 0.6,
                "minimum_expectancy": 0.2,
                "min_trade_number": 10,
                "max_trade_duration_minute": 1440,
                "remove_pumps": false
        },
        "telegram": {
                "enabled": false,
                "token": "",
                "chat_id": ""
        },
        "api_server": {
                "enabled": false,
                "listen_ip_address": "127.0.0.1",
                "listen_port": 8080,
                "verbosity": "info",
                "jwt_secret_key": "somethingrandom",
                "CORS_origins": [],
                "username": "",
                "password": ""
        },
        "initial_state": "running",
        "forcebuy_enable": false,
        "internals": {
                "process_throttle_secs": 5
        }
}
`

**Strategy to test:**
`import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame

from freqtrade.strategy.interface import IStrategy

import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib

class TestBuy(IStrategy):
    # Strategy interface version - allow new iterations of the strategy interface.
    # Check the documentation or the Sample strategy to get the latest version.
    INTERFACE_VERSION = 2

    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi".
    minimal_roi = {
        "0": 0.03
    }

    # Optimal stoploss designed for the strategy.
    # This attribute will be overridden if the config file contains "stoploss".
    stoploss = -0.1

    # Trailing stoploss
    trailing_stop = False
    # trailing_only_offset_is_reached = False
    # trailing_stop_positive = 0.01
    # trailing_stop_positive_offset = 0.0  # Disabled / not configured

    # Optimal timeframe for the strategy.
    timeframe = '5m'

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = False

    # These values can be overridden in the "ask_strategy" section in the config.
    use_sell_signal = True
    sell_profit_only = False
    ignore_roi_if_buy_signal = False

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 30

    # Optional order type mapping.
    order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }

    # Optional order time in force.
    order_time_in_force = {
        'buy': 'gtc',
        'sell': 'gtc'
    }
    
    # plot_config = {
    #     # Main plot indicators (Moving averages, ...)
    #     'main_plot': {
    #         'tema': {},
    #         'sar': {'color': 'white'},
    #     },
    #     'subplots': {
    #         # Subplots - each dict defines one additional plot
    #         "MACD": {
    #             'macd': {'color': 'blue'},
    #             'macdsignal': {'color': 'orange'},
    #         },
    #         "RSI": {
    #             'rsi': {'color': 'red'},
    #         }
    #     }
    # }

    def informative_pairs(self):
        """
        Define additional, informative pair/interval combinations to be cached from the exchange.
        These pair/interval combinations are non-tradeable, unless they are part
        of the whitelist as well.
        For more information, please consult the documentation
        :return: List of tuples in the format (pair, interval)
            Sample: return [("ETH/USDT", "5m"),
                            ("BTC/USDT", "15m"),
                            ]
        """
        return []

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Adds several different TA indicators to the given DataFrame

        Performance Note: For the best performance be frugal on the number of indicators
        you are using. Let uncomment only the indicator you are using in your strategies
        or your hyperopt configuration, otherwise you will waste your memory and CPU usage.
        :param dataframe: Dataframe with data from the exchange
        :param metadata: Additional information, like the currently traded pair
        :return: a Dataframe with all mandatory indicators for the strategies
        """

        # Retrieve best bid and best ask from the orderbook
        # ------------------------------------
        """
        # first check if dataprovider is available
        if self.dp:
            if self.dp.runmode in ('live', 'dry_run'):
                ob = self.dp.orderbook(metadata['pair'], 1)
                dataframe['best_bid'] = ob['bids'][0][0]
                dataframe['best_ask'] = ob['asks'][0][0]
        """
        
        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                (dataframe['close'] > dataframe['open']) |
                (dataframe['open'] > dataframe['close'])
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the sell signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
            ),
            'sell'] = 1
        return dataframe`

**Comment by xmatthias** [comment]
Based on your configuration combination (`"stake_amount": 1011, "tradable_balance_ratio": 0.25, "max_open_trades": 4`), you're giving the bot 25% of the total USDT balance, which will be split across 4 trades.

To open ONE trade with 1011$, you'll therefore need to have an available USDT balance of > 4044 (1011 = 4044 * 0.25).

Since you're using 4 open trades, your 4044$ becomes the minimum to open one trade - but to open all 4 trades, you'd need 4044$ * 4 (minimum) balance, even though the bot will only use the 4044$.

Most likely, you've got ~4000$ in your account - and you'd like to split it across 4 trades (i assume that's why you set tradable_balance_ratio to 25%) ... so `tradable_balance_ratio` should be 0.99 (close to 1) - to give the bot access to the available funds.

**Comment by chescake** [comment]
ohh my bad, in fact i'm trying to do 4 trades of 250 each one, i set 1011(11 for fees, 1011*0.99= 1000.89 for the four trades)
`"stake_amount": 1011, "tradable_balance_ratio": 0.99, "max_open_trades": 4`

but as soon the bot start only one trade is executed with 1000 USDT

> freqtrade trade -s TestBuy
> 2021-01-14 10:18:24,106 - freqtrade.worker - INFO - Starting worker develop-adb3fb12
> 2021-01-14 10:18:24,107 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
> 2021-01-14 10:18:24,117 - freqtrade.loggers - INFO - Verbosity set to 0
> 2021-01-14 10:18:24,118 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
> 2021-01-14 10:18:24,119 - freqtrade.configuration.configuration - INFO - Dry run is enabled
> 2021-01-14 10:18:24,120 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
> 2021-01-14 10:18:24,120 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 4 ...
> 2021-01-14 10:18:24,122 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
> 2021-01-14 10:18:24,122 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
> 2021-01-14 10:18:24,123 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
> 2021-01-14 10:18:24,124 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
> 2021-01-14 10:18:24,124 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
> 2021-01-14 10:18:24,125 - freqtrade.freqtradebot - INFO - Starting freqtrade develop-adb3fb12
> 2021-01-14 10:18:24,145 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy TestBuy from '/freqtrade/user_data/strategies/TestBuy.py'...
> 2021-01-14 10:18:24,146 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
> 2021-01-14 10:18:24,147 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
> 2021-01-14 10:18:24,148 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 1011.
> 2021-01-14 10:18:24,149 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
> 2021-01-14 10:18:24,149 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
> 2021-01-14 10:18:24,150 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
> 2021-01-14 10:18:24,151 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
> 2021-01-14 10:18:24,152 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.03}
> 2021-01-14 10:18:24,153 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
> 2021-01-14 10:18:24,154 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
> 2021-01-14 10:18:24,155 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
> 2021-01-14 10:18:24,156 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
> 2021-01-14 10:18:24,157 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
> 2021-01-14 10:18:24,158 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
> 2021-01-14 10:18:24,162 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
> 2021-01-14 10:18:24,169 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
> 2021-01-14 10:18:24,170 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
> 2021-01-14 10:18:24,171 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 1011
> 2021-01-14 10:18:24,173 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
> 2021-01-14 10:18:24,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
> 2021-01-14 10:18:24,179 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
> 2021-01-14 10:18:24,186 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
> 2021-01-14 10:18:24,187 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
> 2021-01-14 10:18:24,191 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
> 2021-01-14 10:18:24,198 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
> 2021-01-14 10:18:24,199 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
> 2021-01-14 10:18:24,200 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
> 2021-01-14 10:18:24,205 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
> 2021-01-14 10:18:24,206 - freqtrade.exchange.exchange - INFO - Using CCXT 1.40.30
> 2021-01-14 10:18:24,215 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
> 2021-01-14 10:18:24,226 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
> 2021-01-14 10:18:24,238 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
> 2021-01-14 10:18:25,100 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
> 2021-01-14 10:18:25,197 - freqtrade.persistence.migrations - INFO - Moving open orders to Orders table.
> 2021-01-14 10:18:25,220 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:25,226 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
> 2021-01-14 10:18:25,228 - freqtrade.plugins.protectionmanager - INFO - No protection Handlers defined.
> 2021-01-14 10:18:25,884 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
> 2021-01-14 10:18:26,347 - apscheduler.scheduler - INFO - Scheduler started
> 2021-01-14 10:18:28,783 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['forcebuy'], ['trades'], ['delete'], ['performance'], ['stats'], ['daily'], ['count'], ['locks'], ['reload_config', 'reload_conf'], ['show_config', 'show_conf'], ['stopbuy'], ['whitelist'], ['blacklist'], ['logs'], ['edge'], ['help'], ['version']]
> 2021-01-14 10:18:28,791 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
> 2021-01-14 10:18:29,510 - freqtrade.worker - INFO - Changing state to: RUNNING
> 2021-01-14 10:18:29,511 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': 'Dry run is enabled. All trades are simulated.'}
> 2021-01-14 10:18:29,817 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `binance`\n*Stake per trade:* `1011 USDT`\n*Minimum ROI:* `{'0': 0.03}`\n*Stoploss:* `-0.1`\n*Timeframe:* `5m`\n*Strategy:* `TestBuy`"}
> 2021-01-14 10:18:30,130 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USDT pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
> 2021-01-14 10:18:35,466 - numexpr.utils - INFO - Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
> 2021-01-14 10:18:35,468 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
> 2021-01-14 10:18:35,637 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:35,641 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 1000.89 ...
> 2021-01-14 10:18:35,641 - freqtrade.freqtradebot - INFO - Executing Buy for ALGO/USDT
> 2021-01-14 10:18:35,643 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
> 2021-01-14 10:18:35,852 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:35,854 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 1, 'type': buy, 'exchange': 'Binance', 'pair': 'ALGO/USDT', 'limit': 0.4554, 'order_type': 'limit', 'stake_amount': 1000.89, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'amount': 2197.82, 'open_date': datetime.datetime(2021, 1, 14, 18, 18, 35, 806555), 'current_rate': 0.4554}
> 2021-01-14 10:18:36,538 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,561 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,588 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,613 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,637 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,663 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,688 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,715 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,741 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,766 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,790 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,827 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,853 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,877 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,901 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,926 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,953 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,977 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:36,981 - freqtrade.worker - INFO - Bot heartbeat. PID=262, version='develop-adb3fb12', state='RUNNING'
> 2021-01-14 10:18:37,156 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1, pair=ALGO/USDT, amount=2197.82000000, open_rate=0.45540000, open_since=2021-01-14 18:18:35)
> 2021-01-14 10:18:37,160 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=1, pair=ALGO/USDT, amount=2197.82000000, open_rate=0.45540000, open_since=2021-01-14 18:18:35) [buy]: 1.0008872 USDT - rate: 0.001
> 2021-01-14 10:18:37,161 - freqtrade.persistence.models - INFO - Updating trade (id=1) ...
> 2021-01-14 10:18:37,162 - freqtrade.persistence.models - INFO - LIMIT_BUY has been fulfilled for Trade(id=1, pair=ALGO/USDT, amount=2197.82000000, open_rate=0.45540000, open_since=2021-01-14 18:18:35).
> 2021-01-14 10:18:37,425 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,448 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,475 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,500 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,525 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,550 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,575 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,601 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,626 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,652 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,681 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,720 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,744 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,772 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,801 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,840 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,873 - freqtrade.wallets - INFO - Wallets synced.
> 2021-01-14 10:18:37,910 - freqtrade.wallets - INFO - Wallets synced.

**Comment by xmatthias** [comment]
`"stake_amount": 1011` refers to ONE stake, while `tradable_balance_ratio` refers to the whole account.

To trade with a trade-size of 250, set stake_amount to 250. (you can leave the rest the same).

**Comment by chescake** [comment]
now it's working, thanks for the clarification
