### ISSUE TITLE
Binance stake_amount - Can't open a new trade: stake amount is too small (11 < 20.0)

### ISSUE THREAD

**Issue by unplugged8** [freqtrade/freqtrade#4213]
## Describe your environment

  * Operating system: Ubuntu 20.04.1 LTS
  * Python Version: 3.8.5
  * CCXT version:  1.29.79
  * Freqtrade Version: 2020.12
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

When trying to set stake_amount in config.json to 11 (stake_currency USDT), freqtrade displays "Can't open a new trade: stake amount is too small (11 < 20.0)

When stake_amount set to 20, the bot is working fine and make buys and sells.

Minimum stake on Binance is 10 USDT.

### Steps to reproduce:

  1.  Set "stake _currency": "USDT", Set "stake_amount": 11, in config.json
  2. Run freqtrade
  3. Displays error (stake amount is too small (11 < 20.0) - when stake_amount is set to 20, the bot is working fine.
  
### Observed Results:

  * What happened?
  Bot not starting new trades
  * What did you expect to happen?
  Minimum Binance stake is 10 USDT so I was thinking that it will run with 11 USDT.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
2021-01-14 13:26:11,671 - freqtrade.wallets - INFO - Wallets synced.
2021-01-14 13:26:11,672 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 11 ...
2021-01-14 13:26:11,672 - freqtrade.freqtradebot - INFO - Executing Buy for SRM/USDT
2021-01-14 13:26:11,672 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2021-01-14 13:26:12,148 - freqtrade.freqtradebot - WARNING - Can't open a new trade for SRM/USDT: stake amount is too small (11 < 20.0)
2021-01-14 13:26:12,251 - freqtrade.worker - INFO - Bot heartbeat. PID=3885, version='2020.12', state='RUNNING'
2021-01-14 13:26:14,931 - freqtrade.wallets - INFO - Wallets synced.
  ```

**Comment by xmatthias** [comment]
11$ will definitely be too low as stake-currency.

While the market may be limited to 10$, it's also limited by the other currency - so often with low-priced pairs, this will end up closer to 15$, as you can't buy less than 0.01 of a random currency.

in addition to this, the minimum Order-size must consider stoploss.
If you buy for 11$ now, and price drops by 10%, you now only own 9$ of this asset ... however you cannot sell this anymore as it's below the minimum order size (the only thing you can do then is either convert to BNB, or buy more so you're able to sell it "all at once". 
The calculation of the minimum ordersize is therefore based on the asset's current price - stoploss (- 1%).
This way, freqtrade makes sure that you can exit the trade.

Now obviously, the value changes greatly here depending on the stoploss value - based on the value you're getting, i assume you're using a pretty wide stoploss - as i don't think this particular pair is very low priced.
 
e.g. With a stoploss-value of 0.5 (50%) - you'll need to allow the pair to drop 50% in value, while keeping the order size still over the 10$ (or whatever it is, after looking at both sides).

**Comment by unplugged8** [comment]
Yes, that makes sense :) Thank you :) Closing...
