### ISSUE TITLE
Use BTC as stake currency to trade aganist USDT

### ISSUE THREAD

**Issue by sherryxiao1988** [freqtrade/freqtrade#4219]
Hi,

This may be a dumb question, but I've tried to look through the documentation and code, and can't find an answer. :)

It seems the "stake currency" is what we actually get as profit by using freqtrade. Some configurations (minimal ROI, stoploss, etc.) are specifically for us to gain more stake currency. We enter a position by buying using stake currency and exit a position by selling and getting back the stake currency.

In my use case, I'd like to accumulate more BTC over time, but instead of trade BTC with other coins, I'd like to trade the USDT/BTC pair. However, Binance only has BTC/USDT pair, which suggests using USDT as the stake currency.

Can I still specify BTC as the stake currency, but put BTC/USDT as whitelisted pair? Or is there any other way to achieve the same purpose?

Thanks a lot!

**Comment by xmatthias** [comment]
It's quite simple - no you can't.

You can however use a multitude of other pairs (XRP/BTC, ...) for this - however FIAT(like) pairs cannot be used for this, as these pairs are usually the quote currench (*may depend on the exchange - but i don't know any where it's reversed).

**Comment by sherryxiao1988** [comment]
Ok. Thanks for the quick reply!
