### ISSUE TITLE
Following "Quickstart with Docker" documentation fails

### ISSUE THREAD

**Issue by sobeit2020** [freqtrade/freqtrade#4220]
## Describe your environment

  * Operating system:  Ubuntu / MX / Xubunut 
  * Python Version: 3.8.6
  * CCXT version: 1.39.79 
  * Freqtrade Version: freqtrade develop 
  * Docker version 20.10.2, build 2291f61
  * docker-compose version 1.21.0, build 5920eb0
  * pandas version : 1.2.0
  * numpy version : 1.19.4
 
## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

1. I want to see how clear documentation is to guide me through the steps to install freqtrade, with different technologies
2. Lets to https://www.freqtrade.io/en/latest/docker_quickstart/#docker-quick-start and follow instruction steps of 

### Docker quick start

Create a new directory and place the [docker-compose file](https://github.com/freqtrade/freqtrade/blob/develop/docker-compose.yml) in this directory.

=== "PC/MAC/Linux"
``` bash
mkdir ft_userdata
cd ft_userdata/
# Download the docker-compose file from the repository
curl https://raw.githubusercontent.com/freqtrade/freqtrade/stable/docker-compose.yml -o docker-compose.yml

# Pull the freqtrade image
docker-compose pull

# Create user directory structure
docker-compose run --rm freqtrade create-userdir --userdir user_data

# Create configuration - Requires answering interactive questions
docker-compose run --rm freqtrade new-config --config user_data/config.json
```

### Observed Results:

  * I can download the docker-compose file
  * But Pull the freqtrade image fails

### Relevant code exceptions or logs

```bash
$ sudo docker-compose pull
[sudo] password for mx: 
Pulling freqtrade ... error

ERROR: for freqtrade  Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:48543->[::1]:53: read: connection refused
ERROR: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:48543->[::1]:53: read: connection refused
```

I don't know how to proceed, 
connection refused, any reasons i could check?

**Comment by xmatthias** [comment]
First of all, there shouldn't be a need to use `sudo` if you configured docker correctly (if your user has the docker group).

Then, this seems to be a network / configuration issue on your side - maybe you have a proxy set that prevents the connection, or you've got no proxy set but you should use one.

You should be able to test docker itself by running `docker run hello-world` - which should print some "hello from docker ......".
As long as that does not work, it's an installation problem of docker itself - and nothing we can support you with i'm afraid.

While i understand that your problem is with freqtrade, please search for help in docker support channels, as we cannot support basic issues with underlying technology.
Thanks for your understanding.

**Comment by sobeit2020** [comment]
```
$ docker run hello-world
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'
```

and 

```
$ sudo docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

```

I will work on it, and be back to you in some time after docker-homework is done

**Comment by xmatthias** [comment]
How come you're getting the following message:
```
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'
```

What do you do after this to get the correct output?
I suspect you're missing the docker group on your user (`usermod -aG docker <youruser>`) ... then you'll need to logout / log back in, and sudo should no longer be necessary.

If pulling the image works, then `docker pull freqtradeorg/freqtrade:develop` should work as well.
If that works, then the docker-compose methods will also work. 

The documentation for docker assumes that docker is setup correctly.

**Comment by sobeit2020** [comment]
ups, now it is corrected,
the difference was sudo,

i've checked the search engine, and it told me as well about usermode

**Comment by xmatthias** [comment]
so you're now able to run the docker image just fine?

does that mean we can close this issue?

**Comment by sobeit2020** [comment]
Yes, please close,
when i will go through the Docker documentation, i will pull request with its update

**Comment by xmatthias** [comment]
Best ask first if you encounter problems.
The docker-quickstart documentation does work as is - and we will NOT start explaining how docker works  in the documentation.

**Comment by victorhez** [comment]
sudo docker-compose pull solved my issue
