### ISSUE TITLE
Sell all Coins on Exchange

### ISSUE THREAD

**Issue by nodwan** [freqtrade/freqtrade#4222]
hi, 

with all tests and strategy test you will have later a worst of balances in several coins ... it will be really nice if there is the option /sellallbalances what will sell all coins around, to get all your invests, with one command back ... so you must not handle all manual

**Comment by xmatthias** [comment]
I don't see why this should be necessary if you keep a decently organized way of working.

Even if you test multiple strategies, switch bots on and off, before switching a bot off completely (to not restart anymore), do a `/forcesell all` and all coins will be sold.


If you're talking about the "binance dust" (small, non-tradable balances that cannot be sold anymore) - best get BNB and use that for fees, avoids the dust.
The only think you can do with the dust is convert it to BNB, which can be done with 2 clicks on binance.


it's also against the concept we pursue with freqtrade, which is to try and not touch assets you may want to manually trade with on the exchange.

You can buy "COINXYZ" and keep that in your balance manually, as long as you blacklist this coin, freqtrade will not touch it.
We will therefore also not implement a "convert all to stake currency" - as this would be deadly for people running multiple bots against one account.

Thanks for your understanding.
