### ISSUE TITLE
SpreadFilter refresh_period for white listed pairs

### ISSUE THREAD

**Issue by steeff** [freqtrade/freqtrade#4227]
## Describe your environment

  * Operating system: ____ ubuntu 20.04.1
  * Python Version: _____ 3.8.5
  * CCXT version: _____ ccxt==1.30.15
  * Freqtrade Version: ____ develop-572f5f91
  
## Your question

Hi,
1st of all thanks for this amazing piece of software!
I can't get my white listed pairs refreshed on some interval using SpreadFilter... so I have some pairs defined in pair_whitelist and I would like that this list gets filtered every 10 minutes using the SpreadFilter. tried several config settings but with no luck, that list is never refreshed or the engine tries to refresh the previous filtered pairs...

my last config is the following
`"pair_whitelist": ["xx/xx", "xx/xx"],
        "pair_blacklist": []
    },
    "pairlists": [
    {
        "method": "StaticPairList",
        "refresh_period": 300
    },
    {
        "method": "SpreadFilter",
        "refresh_period": 300,
         "max_spread_ratio": 0.005
    },
    {
        "method": "PerformanceFilter",
        "refresh_period": 300
    },
    ],`
is it possible to get it working refreshed on that interval?

thanks a lot!

**Comment by steeff** [comment]
Well, found some kind of workaround by using blacklist instead of whitelist + VolumePairList like this
`"pair_whitelist": [],
        "pair_blacklist": ["xx/xx", "xx/xx"]
    },
    "pairlists": [
     {
        "method": "VolumePairList",
        "number_assets": 15,
        "sort_key": "quoteVolume",
        "refresh_period": 300
    },
    {
        "method": "SpreadFilter",
        "refresh_period": 300,
         "max_spread_ratio": 0.005
    },
    ],`

this generates a lot of logs and is not ideal but do the job...

**Comment by xmatthias** [comment]
`refresh_period` is not really supported by all pairlists, only the ones which actively download data.
It's not failing if it's there, but it's also not considered.

You'll also need to be  quite careful with this filter - it's intended to be a "one-off" filter, generally eliminating pairs that have a too high spread (maybe we need to clarify this in the docs).

In reality, even refreshing this every minute is WAY too slow, as orderbooks move in sub-second intervals, so you can't rely on the data as soon as you looked at it, as orders could come in (or be cancelled / filled).

your workaround will however not give you what you want anyway, as this filter relies on cached tickers data, while you THINK it's looking every 300 seconds, it's looking every 300 seconds, but never changes the underlying data, which is refreshed every 1800s, which currently cannot be changed.

**Comment by steeff** [comment]
then the purpose of the spreadfilter is not pretty clear if you can not really rely on it because it's moving that fast...but anyway thx for your explanation!

**Comment by xmatthias** [comment]
I've never been a huge fan of this as i don't think you can filter pairs based on something that changes a few times a second.

It CAN be useful to filter out pairs with a generally wide spread (which are usually also very low priced - so most pairs might not even reach this filter).
