### ISSUE TITLE
Permission for sample_strategy.py

### ISSUE THREAD

**Issue by kravtsls** [freqtrade/freqtrade#4229]
hello, sorry for a stupid question, but can someone tell me What to write to get permission for sample_strategy.py file to edit it and to save also strategies in the strategies folder as well? (run with docker)
![4](https://user-images.githubusercontent.com/74933054/104858067-0a7fbf80-591d-11eb-92b2-632e8f4397fa.png)

I add the new strategy in the folder strategies with $sudo nano [bbrsi.py] but even can not edit that file or delete that i didn't save as .py 

thank you 
 

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
It's totally what you're trying to do / where the problem lies.
Your screenshot also does not show any error or whatever ... 

when you're using `sudo` - this makes the file owned by root, so further edits will also need to happen with "sudo", otherwise the file will be write-protected.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
