### ISSUE TITLE
Issue with freqtrade download-data --pairs-file FILE

### ISSUE THREAD

**Issue by YuriyTigiev** [freqtrade/freqtrade#4236]
Yes.

## Describe your environment

  * Operating system: Windows 10 Pro - 10.0.19042 N/A Build 19042
  * Python Version: _____ (`python -V`)
  * CCXT version: 1.40.74 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade docker-d05cbe23  (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

I can't download data without using a config.json file. I would like to download data for pairs in the pairs.json file.

### Steps to reproduce:

  1. `C:\ft_userdata>docker-compose run --rm freqtrade download-data --exchange binance ` 
( If no additional parameter is specified, freqtrade will download data for "1m" and "5m" timeframes for the last 30 days. Exchange and pairs will come from config.json (if specified using -c/--config). Otherwise --exchange becomes mandatory. )

https://www.freqtrade.io/en/2019.10/data-download/
freqtrade download-data --exchange binance
This will download historical candle (OHLCV) data for all the currency pairs you defined in pairs.json.

  
### Observed Results:

  * What happened?
  freqtrade returns error
  * What did you expect to happen?
  start to download data for pairs defined in the pairs.json 

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

```
C:\ft_userdata>docker-compose run --rm freqtrade download-data --exchange binance
Creating ft_userdata_freqtrade_run ... done
2021-01-18 10:30:58,545 - freqtrade.loggers - INFO - Verbosity set to 0
2021-01-18 10:30:58,545 - freqtrade.configuration.configuration - INFO - Using exchange binance
2021-01-18 10:30:58,552 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2021-01-18 10:30:58,553 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2021-01-18 10:30:58,553 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1m', '5m']
2021-01-18 10:30:58,553 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-01-18 10:30:58,553 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-01-18 10:30:58,557 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)                                                                                                                                                                                 File "/freqtrade/freqtrade/commands/data_commands.py", line 25, in start_download_data                                                                                                                               config = setup_utils_configuration(args, RunMode.UTIL_EXCHANGE)                                                                                                                                                  File "/freqtrade/freqtrade/configuration/config_setup.py", line 21, in setup_utils_configuration                                                                                                                     config = configuration.get_config()                                                                                                                                                                              File "/freqtrade/freqtrade/configuration/configuration.py", line 41, in get_config                                                                                                                                   self.config = self.load_config()                                                                                                                                                                                 File "/freqtrade/freqtrade/configuration/configuration.py", line 114, in load_config                                                                                                                                 self._resolve_pairs_list(config)                                                                                                                                                                                 File "/freqtrade/freqtrade/configuration/configuration.py", line 461, in _resolve_pairs_list                                                                                                                         config['pairs'] = json_load(f)                                                                                                                                                                                   File "/freqtrade/freqtrade/misc.py", line 76, in json_load                                                                                                                                                           return rapidjson.load(datafile, number_mode=rapidjson.NM_NATIVE)                                                                                                                                               rapidjson.JSONDecodeError: Parse error at offset 0: Invalid value.                               
```

dir 

```
 Directory of C:\ft_userdata\user_data\data\binance

18.01.2021  13:56    <DIR>          .
18.01.2021  13:56    <DIR>          ..
18.01.2021  13:56                19 pairs.json
               1 File(s)             19 bytes
               2 Dir(s)  249 303 662 592 bytes free       
```

pairs.json 

```
[
"BTC/BUSD"
]


```

**Comment by mobrine1** [comment]
`rapidjson.JSONDecodeError: Parse error at offset 0: Invalid value.` your json is not formatted correctly. What did you use to edit pairs.json? You should use code editor

**Comment by zn3x** [comment]
`rapidjson.JSONDecodeError: Parse error at offset 0: Invalid value.` your json is not formatted correctly. What did you use to edit pairs.json?

**Comment by YuriyTigiev** [comment]
I have used notepadd++ and farmanger. Please, share the correct example file. I would like to check my side.

**Comment by xmatthias** [comment]
it's most likely a formatting issue (maybe the file is "with BOM" - while the system youre loading this on expects it without - you can convert this in notepad++ - but see below for caveats about this).

In general, i recommend to create the file on the target system to avoid such problems - as you can't know for sure if the transfer program (i assume farmanager in your case) thinks to be clever and partially converts a file.

**Comment by YuriyTigiev** [comment]
> it's most likely a formatting issue (maybe the file is "with BOM" - while the system youre loading this on expects it without - you can convert this in notepad++ - but see below for caveats about this).
> 
> In general, i recommend to create the file on the target system to avoid such problems - as you can't know for sure if the transfer program (i assume farmanager in your case) thinks to be clever and partially converts a file.

The reason why I met this problem was that I used copy-paste to this file from text information from the screen for the   
`docker-compose run --rm freqtrade test-pairlist --config user_data/configBinanceDynamicList.json  --quote BUSD --print-json` 

Is it an approach to simplify this process? Export result of the script run to the pairs.json file?

**Comment by xmatthias** [comment]
as mentioned, the content (what is visible / what you posted above) looks fine.

Unfortunately, what's visible to users does not always correspond to the real content of the file (hidden characters, "magic" bits, ...).

best remove the file and recreate it on the system you're running the bot.

**Comment by YuriyTigiev** [comment]
What about the optimize/automat of the process of generating the pairs.json?

**Comment by xmatthias** [comment]
You can simply copy/paste the output of that command to a file and run download-data.

you will however usually want to filter out some uninterresting pairs (like USDT/BUSD - which has a stable price, so there's no profit to be made for this) - so providing this as "automated" has little value.

If you think it's a must, feel free to contribute this in a Pull request.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above, and the command shown works when the pairs-file is a valid json file (corresponding to the platform it's running).

Feel free to comment below / reopen if that's not the case.

**Comment by nasrin-kh** [comment]
I can't download data with docker and without.
2021-11-14 21:07:59,172 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2021-11-14 21:08:07,543 - freqtrade.commands.data_commands - INFO - About to download pairs: [], intervals: ['1m', '5m'] to /home/nasrin/freqtrade/user_data/data/binance

**Comment by xmatthias** [comment]
you need to define pairs.
please also don't revive issues that are almost a year old. It's almost never the same issue, even if you think it is.
