### ISSUE TITLE
Optimal numbers of pairs and timerange for hyperops

### ISSUE THREAD

**Issue by YuriyTigiev** [freqtrade/freqtrade#4239]
This is a general question - from your experience what is an optimal number of pairs and time range for hyperopts. 
I think 1-2 week range and not more 50 pairs.  I understand that depends on a strategy which testing, but I think exist common parameters for most strategies.

**Comment by xmatthias** [comment]
In general, it'll strongly depend on your timeframe and how the strategy works - but by focusing on 1-2 weeks, you'll risk to only ever look at one market period (say a strong bull period) - so your strategy may fail once market moves sideways.
Obvioulsy, it'll depend on your picking of the time, on timeframe, and on the basic goal / idea of the strategy (high frequency with small profits, slow strategy with high profits, ...).

---

For questions like this, i'd encourage to use our [discord server](https://discord.gg/MA9v74M). 

This is a highly opinionated topic, so you'll benefit from asking this in generic channels, which may get you multiple different opinions (which basically leaves you to pick the best out of these).
