### ISSUE TITLE
Heavily different result from hyperopt vs. backtesting

### ISSUE THREAD

**Issue by martongyorgy59** [freqtrade/freqtrade#4240]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: 3.6.5 (`python -V`)
  * CCXT version: 1.18.119 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 0.17.3 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

Hello Guys,

First of all I am here because i'm following the Udemy course and since i tried to follow everything i could. And their strategy's optimization (RSI + Bollinger) lead me to this question.

Now I have issues with either the hyperopt (and I guess so) or with my parameter settings, but that one seems better. 
I have a ~30day historical data for backtesting for ~21 pairs.

Biggest issue is that hyperopt gives me ridiculous - unbelievable numbers:

command ran: 

python freqtrade/main.py -c config.json hyperopt -e 100
(yes, overwritten the default_hyperopt.py and default_strategy.py files this is why i did not put custom file / strategy )

![kép](https://user-images.githubusercontent.com/77622124/105097518-01bbf480-5aa9-11eb-9971-fa335fedc4be.png)

And of course when I'd like to implement this, i have negative return...

Please find attached the default_hyperopt.py file as well as the default_strategy.py

(i already set in hyperopt.py: 'position_stacking': self.config.get('position_stacking', False), ---> coming from commit c474e2ac86bc6b1a5a448f11a76622e3ed59cd57 )

[defaults_.zip](https://github.com/freqtrade/freqtrade/files/5838793/defaults_.zip)

Please help me ! :)

**Comment by xmatthias** [comment]
Please note that the Udemy course version is heavily outdated (it's a modified snapshot from early 2018), and that we're not providing support for this. If you need support for this particular version - please ask in the udemy questions section, or in the Udemy course repository fork.

--- 

Assuming an uptodate version (2020.11, 2020.12 or develop) (this should also work for earlier versions, but things changed heavily).

If you transfer your parameters to the strategy correctly, then the results will match. 
If you have deviations, then you didn't transfer correctly. This can be as easy as a sign inversion (`<` vs. `>`)  - or a completely wrong parameter.

Also, some parameters can come from the configuration (stoploss, roi, ...) - so make sure to check the logs if the strategy parameters are overwritten.

On top of that - i'll surely not download a random zip-file (and i encourage anyone else to not download it either) - zip is known to have some bugs (zip-bomb, ...).
The files you'd be needing are text files, which can be uploaded "standalone" or to a service like pastebin.

However, please understand that we'll not take your hyperopt result and convert it to a strategy for you.

---

This is a free, open source project, which means that people spend their free time helping others and moving this project forward.
This also means that these people will most likely not spend their time developing the strategy for someone else. 
This time is better spent by bringing this project forward, working on either their own strategy, or or helping with bugs / issues.

Thanks for your understanding.

**Comment by martongyorgy59** [comment]
Hello Matthias,

First, thanks , understood I will proceed as proposed, but let me ask one thing. 

Would you think (based on the print screen) that those values are correct ? 2575% cummulated return on ~30days of data, and so many trades for exact same strategy ? (Bollinger with std:2 as lower level buy with minimum RSI of 30, and sell at Bollinger middle). Isn't there any suspicious thing ? I do not know just quessing, but i spent at least ~3 hours in front of my monitor to cross-check that i implemented the same in the strategy...
Anyway, any little hint would be helpful !

Thank you!

**Comment by xmatthias** [comment]
well if hyperopting shows this, then backtesting can reach this as well (hyperopting just runs backtesting under the hood) - but that doesn't necessarily mean it can be reached in live - as backtesting CAN be cheated.

If it's realistic to reach - i guess it can be possible - but as always, use dry-run to verify the strategy works in forward-testing as well, and there isn't some subtle error making the strategy look into the future somehow.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
