### ISSUE TITLE
Exchange : FXCM #enhancement

### ISSUE THREAD

**Issue by lemassykoi** [freqtrade/freqtrade#4243]
Hi, would it be possible to add support for FXCM exchange ?

GitHub : [https://github.com/fxcm/RestAPI](url)
[https://github.com/fxcm/RestAPI/issues/58#issuecomment-758670454](url)

[https://www.quantnews.com/algo-trading-with-rest-api-and-python-part-1/](url)

Maybe useful :
[https://www.fxcm.com/fxcmpy/](url)

I have some working scripts for this exchange, let me know if you need something

Thanks

**Comment by xmatthias** [comment]
We will not implement exchange API's directly, but we're using ccxt to abstract the exchange logic away.
Maintaining an exchange-api is rather hard work, which we simply don't have the ressources (time) to do, therefore we will not include any exchange that's not part of ccxt's supported exchanges.

Looking at it's [current list of supported exchanges](https://github.com/ccxt/ccxt/wiki/Exchange-Markets), it doesn't seem to be supported at the moment.
Please therefore open an issue (or better yet, a Pull request implementing this exchange) with ccxt.

once it's available as part of ccxt, then it may work (if all the right methods are implemented).

Thanks for your understanding.

**Comment by lemassykoi** [comment]
Thanks, and sorry for continuously being wrong between CCXT and Freqtrade 

I found a post with similar demand : [https://github.com/ccxt/ccxt/issues/6716](url)
