### ISSUE TITLE
 `Swarm` of dry-run strategies / proper way to run / possible?

### ISSUE THREAD

**Issue by sobeit2020** [freqtrade/freqtrade#4246]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.8 (`python -V`)
  * Python Version: 3.8.6 
  * CCXT version: 1.39.79
  * Freqtrade Version: freqtrade develop

## Your question

I have list of pre-sorted, off-the-shelf strategies, and i would like to be able to dry-run them simultaneously. 
What would be best approach to do that? Best on one account of Binance, and with multiple telegram bots.

Would docker-swarm be something alike?

**Comment by zn3x** [comment]
Dry run basically doesn't affect your trading account (it uses api to check open markets, get prices, etc... But it doesn't touch anything related to orders, all is emulated in your machine), so you can run as much dry run instances as you want.
You can run multiple dry runs instances by creating multiple configs if you want to change pairs or staking currency (warning: always keep dry_run enabled) or keep only one config if you want to try multiple strategies with same config. You should also separate databases
This question has been answered in a similar way in #1768

**Comment by xmatthias** [comment]
> so you can run as much dry run instances as you want.

This is ... not quite true. You'll run into rate-limit problems at a certain point (for dry-run on binance, it can be 3-4 instances per host, usually).

---

Docker swarm is ... kinda dead ... i've not seen it even mentioned in a long time.

What i personally do is use docker-compose with multiple services (copy-paste the whole service and change config, strategy, service name and container name), but you can also use multiple directories with one docker-compose file each.

**Comment by sobeit2020** [comment]
Hmm
@

> This question has been answered in a similar way in #1768
yes this one i saw


> > so you can run as much dry run instances as you want.
i try, doing telegram is easy,
but what i got, is that second bot, with new config and new strategy, starts exactly with the place where the first one is - filled orders.

Is there something that i missed? Is it possible, that on the same Binance account, second bot could start with empty account, and prove what it is?

**Comment by xmatthias** [comment]
I'm not sure what your question is now ....

For running multiple bots, we got a [documentation page](https://www.freqtrade.io/en/latest/advanced-setup/#running-multiple-instances-of-freqtrade) explaining what to pay attention to.

If the new instance still sees the old trades, then you didn't switch the database file.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
