### ISSUE TITLE
- INFO - No protection Handlers defined.

### ISSUE THREAD

**Issue by aginyor** [freqtrade/freqtrade#4247]
I tried add protection handlers to my strategy, but i think it is not working.

My strategy:

from freqtrade.strategy import IStrategy

class AwesomeStrategy(IStrategy)
    timeframe = '1h'
    protections = [
        {
            "method": "CooldownPeriod",
            "stop_duration_candles": 5
        },
        {
            "method": "MaxDrawdown",
            "lookback_period_candles": 48,
            "trade_limit": 20,
            "stop_duration_candles": 4,
            "max_allowed_drawdown": 0.2
        },
        {
            "method": "StoplossGuard",
            "lookback_period_candles": 24,
            "trade_limit": 4,
            "stop_duration_candles": 2,
            "only_per_pair": False
        },
        {
            "method": "LowProfitPairs",
            "lookback_period_candles": 6,
            "trade_limit": 2,
            "stop_duration_candles": 60,
            "required_profit": 0.02
        },
        {
            "method": "LowProfitPairs",
            "lookback_period_candles": 24,
            "trade_limit": 4,
            "stop_duration_candles": 2,
            "required_profit": 0.01
        }
    ]

After I strating my freqtrade: - INFO - No protection Handlers defined. I using Docker 2020.12. Thank you.

**Comment by xmatthias** [comment]
Please use the appropriate documentation page for your version [here](https://www.freqtrade.io/en/2020.12/plugins/#protections) (you can switch documentation versions in the small flyover at the bottom right corner).

Please note the difference to "develop" - which is the missing part about "can be defined in the strategy".

defining protections in the strategy was added after the 2020.12 release - and is therefore not yet available in the version you're using.
Either define them in the configuration, or upgrade to develop.
