### ISSUE TITLE
Add max_day_listed  in Age Filter

### ISSUE THREAD

**Issue by Dat1606** [freqtrade/freqtrade#4251]
## Describe the enhancement

Less than 1 year new listed coins usually have better performance. It will be great if we have an option to filter only newly listed pairs with VolumnPairList.

**Comment by xmatthias** [comment]
I'll label it as "good first issue" - as this can be a great starting point to get started.

This implicitly also means that i'll not be working on this in the forseable future.

**Comment by Dat1606** [comment]
Thank you. @xmatthias 
I am quite new with freqtrade but i have time. 
I want to implement this thing but can you give me some hints ?

**Comment by xmatthias** [comment]
Just look at the `AgeFilter.py` file ... changes on this should most likely be limited to this file (and docs) - but even if not, it'll be a great starting point :)
