### ISSUE TITLE
Is internet essential for hyperopting?

### ISSUE THREAD

**Issue by Fimap9to1** [freqtrade/freqtrade#4253]
Hi I'd just like to know if a stable internet connection is a must when hyperopting. And what would happen in case of internet connection shut down during hyperopting. Thanks for your answer!

**Comment by xmatthias** [comment]
hyperopt does not use the internet once it's started.

The only time it connects to the exchange is right after startup to get the fees - but once it's running, the internet will be irrelevant.

**Comment by Fimap9to1** [comment]
Thanks!

**Comment by Corfucinas** [comment]
@xmatthias 

Is it possible to absolutely do not require an internet connection to the exchange? I'm currently behind the great firewall using a bare metal server, but I cannot contact Binance...

Is there's a way to use a proxy for this initial exchange call? I saw various methods calling the load markets, load pairs, validate stake currency etc.

**Comment by xmatthias** [comment]
@Corfucinas you can use a [Proxy](https://www.freqtrade.io/en/latest/configuration/#using-proxy-with-freqtrade) for sure .

not requiring internet is however not possible and has become even more critical in the lastest version, as hyperopt needs to be able to fetch the limits to properly calculate pair minimum limits.

Once hyperopt is started however you can remove the internet and it'll work just fine (so maybe consider a temporary proxy or VPN ...)

**Comment by Corfucinas** [comment]
Thanks @xmatthias 

I ended up proxying the server to my laptop with Squid 

Going to leave the link here in case anyone is interested => [Squid tutorial](https://likegeeks.com/linux-proxy-server/)
