### ISSUE TITLE
Backtesting with a "custom stoploss" - no difference in results?

### ISSUE THREAD

**Issue by unplugged8** [freqtrade/freqtrade#4254]
## Describe your environment

Operating system: Ubuntu 20.04.1 LTS
Python Version: 3.8.5
CCXT version: 1.29.79
Freqtrade Version: 2020.12
  
## Your question
Hi guys. Is it possible to backtest strategy with a custom stoploss? I've tried:

use_custom_stoploss = True
def custom_stoploss(self, pair: str, trade: Trade, current_time: datetime, current_rate: float,
                        current_profit: float, **kwargs) -> float:

        # Calculate as -desired_stop_from_open + current_profit to get the distance between current_profit and initial price
        if current_profit > 0.40:
            return (-0.25 + current_profit)
        if current_profit > 0.25:
            return (-0.15 + current_profit)
        if current_profit > 0.20:
            return (-0.7 + current_profit)
        return 1

but backtest results are the same with or without this custom stoploss. I've imported datetime and Trade at the top in the strategy file. Thanks

**Comment by xmatthias** [comment]
Please ensure to use the correct version of the documentation corresponding to your version.

You can switch the documentation version in the bottom right corner.

custom_stoploss is NOT available in 2020.12 (and it's also not mentioned in the logs there).
please either wait for the next release which will include this, or use the develop version.
