### ISSUE TITLE
Is it possible to save backtesting data to the database?

### ISSUE THREAD

**Issue by kevintraver** [freqtrade/freqtrade#4269]

**Comment by xmatthias** [comment]
You can use `--export trades` and the backtesting results will be written to a file.

You can then use the provided methods [as documented here](https://www.freqtrade.io/en/latest/strategy_analysis_example/#load-backtest-results-to-pandas-dataframe) to load the data into a dataframe and analyze it further.

Writing it to database is not supported, and does not really make sense either, as then you'd need one database per backtest run - which will make analyzing / comparing them very painful.

**Comment by kevintraver** [comment]
Ok, thanks for the explanation!
