### ISSUE TITLE
custom stoploss using "process_only_new_candles": true

### ISSUE THREAD

**Issue by rylos** [freqtrade/freqtrade#4274]
## Describe your environment

  * Operating system: __ubuntu 20.04__
  * Python Version: __3.8___ (`python -V`)
  * CCXT version: __last___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __dev__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Is custom stoploss working realtime also when "process_only_new_candles": true ?
Thank you

**Comment by xmatthias** [comment]
process_only_new_candles is only impacting the `populate*` methods.

stoploss and ROI are updated based on `process_throttle_secs` (5s by default) - and custom_stoploss is no exception to this.

**Comment by rylos** [comment]
I'm unable to see custom stoploss working on binance. It's working perfect on dry_run but as soon as I put dry run=false I don't see stoploss getting adjusted.
I'm using stoploss on exchange.
Any idea?

**Comment by xmatthias** [comment]
stoploss on exchange will usually not adjust immediately, but by default once every minute.

you can configure this interval with `stoploss_on_exchange_interval` - but setting this too low will eventually cause you problems.
[read here for more details about this](https://www.freqtrade.io/en/latest/stoploss/#stop-loss-on-exchangefreqtrade).

you should also keep in mind that stoploss can only move up, never down, so if stoploss is already above what you try to set, it'll simply be ignored.

**Comment by rylos** [comment]
Yes i know well this section, currently I'm using 12 seconds for update but watching it live it never adjust the stoploss even after 3 minutes (in dry run it works). Reverting to old trailing mode it's working too.

**Comment by xmatthias** [comment]
there's no technical difference between dry run and live, except for the fact that the stoploss on exchange isn't updated this often.

Also, make sure that "trailing" is off, as this can conflict with the new mode.

**Comment by e850205** [comment]
Custom stoploss is also not working for me on binance. The stoploss is not being updated

**Comment by xmatthias** [comment]
should work now in develop
