### ISSUE TITLE
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by sobeit2020** [freqtrade/freqtrade#4281]
## Describe your environment

Debian 10
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
ccxt==1.40.99
freqtrade develop-16dad8b6
numpy                   1.19.5

  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

Newly done installation, on new system, performed with `./script.sh -i` method
questions were answered during installation as follows:
-y
dev:-y
plot:-n
hyperopt:-n

`freqtrade trade --config config.json --strategy SampleStrategy` fails to start

`RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd`

```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
2021-01-30 22:02:55,644 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/root/freqtrade/freqtrade/commands/trade_commands.py", line 13, in start_trading
    from freqtrade.worker import Worker
  File "/root/freqtrade/freqtrade/worker.py", line 15, in <module>
    from freqtrade.freqtradebot import FreqtradeBot
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 19, in <module>
    from freqtrade.edge import Edge
  File "/root/freqtrade/freqtrade/edge/__init__.py", line 1, in <module>
    from .edge_positioning import Edge, PairInfo  # noqa: F401
  File "/root/freqtrade/freqtrade/edge/edge_positioning.py", line 8, in <module>
    import utils_find_1st as utf1st
  File "/root/freqtrade/.env/lib/python3.7/site-packages/utils_find_1st/__init__.py", line 3, in <module>
    from .find_1st import find_1st
ImportError: numpy.core.multiarray failed to import
```

**Comment by sobeit2020** [comment]
`pip install numpy --upgrade` works, something has to be updated in the files, when you figure out what, could you tell me please, thanks

**Comment by xmatthias** [comment]
it would appear that numpy is up and downgraded during installation.

The logs during the installation should tell if that's happening - i suspect it's a pinned install-dep version on find_1st (it has numpy as install dependency, so numpy MUST be installed before it's installed).
So if they pin the version on install, but not on run, numpy might be installed twice, first a older version, then a newer one.

**Comment by Fusseldieb** [comment]
Yup, same problem. Searched for about 2 hours and found nothing...

```
(.env) fusseldieb@home-nuc:~/freqtrade$ freqtrade trade --config config.json --strategy SampleStrategy
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
2021-01-31 09:24:40,898 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/fusseldieb/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/fusseldieb/freqtrade/freqtrade/commands/trade_commands.py", line 13, in start_trading
    from freqtrade.worker import Worker
  File "/home/fusseldieb/freqtrade/freqtrade/worker.py", line 15, in <module>
    from freqtrade.freqtradebot import FreqtradeBot
  File "/home/fusseldieb/freqtrade/freqtrade/freqtradebot.py", line 19, in <module>
    from freqtrade.edge import Edge
  File "/home/fusseldieb/freqtrade/freqtrade/edge/__init__.py", line 1, in <module>
    from .edge_positioning import Edge, PairInfo  # noqa: F401
  File "/home/fusseldieb/freqtrade/freqtrade/edge/edge_positioning.py", line 8, in <module>
    import utils_find_1st as utf1st
  File "/home/fusseldieb/freqtrade/.env/lib/python3.8/site-packages/utils_find_1st/__init__.py", line 3, in <module>
    from .find_1st import find_1st
ImportError: numpy.core.multiarray failed to import
(.env) fusseldieb@home-nuc:~/freqtrade$

```

**Comment by xmatthias** [comment]
@Fusseldieb what's your numpy version (`pip freeze | grep numpy`) ? 

after that, please try `pip install -U numpy` - and post the output of this here (and also if it works after running this).

**Comment by Fusseldieb** [comment]
> @Fusseldieb what's your numpy version (`pip freeze | grep numpy`) ?
> 
> after that, please try `pip install -U numpy` - and post the output of this here (and also if it works after running this).

Thanks for the quick reply!

I did just solve it somehow.

I went into the virtual env and did `pip3 install --upgrade numpy`

Now it runs ahahaha

**Comment by xmatthias** [comment]
i guess it's related to the numpy 1.20.0 release.

I suspect that 1.20.0 is installed as build dependency, and later replaced by the pinned version - causing this "compilation conflict".
I'll bump the numpy version in develop soon, that should resolve this.

**edit**
In my opinion, it's a failure of pip resolution though - as it should recognize that numpy (1.19.5) is beeing installed with the same command, and the build-dependency should therefore be the same.
As consequence of this, i've opened https://github.com/pypa/pip/issues/9542 in hopes to have this fixed in pip.

**Comment by emejinglilcompany** [comment]
thx for this

**Comment by alvarosan** [comment]
Thanks for this (https://pypi.org/project/py-find-1st/) fix  also @xmatthias .  Because of my setup I needed to still build freqtrade against numpy 1.19.5,  so bumping py-find-1st to `Version 1.1.5 (2021-02-02)` fixed my problems.

**Comment by neilyoung** [comment]
Same issue here out of the blue.  I have a requirements.txt for my project, which explicitly requires numpy=1.19.3. Same error as above on a fresh installation (Ubuntu 20.04 on a Banana PI M2Z). Some other module must have required 1.20. After having applied the update command everything works.
Thanks

**Comment by shek510** [comment]
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "/home/pi/Desktop/pyun0rick.py", line 15, in <module>
    import matplotlib
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/rcsetup.py", line 26, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/colors.py", line 82, in <module>
    from matplotlib import _api, cbook, scale
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/scale.py", line 18, in <module>
    from matplotlib.ticker import (
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/ticker.py", line 179, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import


how to resolve this error

**Comment by xmatthias** [comment]
This is neither related to freqtrade, nor to the problem discussed in this topic. 
Please use google / the appropriate support channels for Numpy (or potentially matplotlib) to get help on this topic.

**Comment by caranguyen** [comment]
> RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
> Traceback (most recent call last):
> File "/home/pi/Desktop/pyun0rick.py", line 15, in
> import matplotlib
> File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/**init**.py", line 107, in
> from . import _api, cbook, docstring, rcsetup
> File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/rcsetup.py", line 26, in
> from matplotlib.colors import Colormap, is_color_like
> File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/colors.py", line 82, in
> from matplotlib import _api, cbook, scale
> File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/scale.py", line 18, in
> from matplotlib.ticker import (
> File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/ticker.py", line 179, in
> from matplotlib import transforms as mtransforms
> File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/transforms.py", line 46, in
> from matplotlib._path import (
> ImportError: numpy.core.multiarray failed to import
> 
> how to resolve this error

did you find a solution? i'm stuck on the same issue

**Comment by xmatthias** [comment]
Letme repeat what i said above - this is NOT related to freqtrade - please stop abusing other repositories / issues.
