### ISSUE TITLE
Exchange FTX - lots of cancelled orders

### ISSUE THREAD

**Issue by nodwan** [freqtrade/freqtrade#4283]
hello, so i’was try several config changes with this exchange FTX, i’dont use sub accounts. only with order type “market” buy and sell, it is possible 100%, to set a order. but i’dont like market orders. if i’m use buy & sell set to “limit” always my orders are be cancel ... only sometimes the order is accepted. i’dont know, later now hours, what is wrong to set a limit order.

maybe someone have a working config.json where i‘can check my config special for FTX, the same config work on binance, perfect. but with FTX ...

maybe i stay in the forrest and dont see the tree ...  

thx for help

**Comment by xmatthias** [comment]
your limit orders will not be cancelled by the exchange, but by the bot.

By default, freqtrade will place itself at the best price on the SAME side of the ordrebook (so best bid for buy orders, and best ask for sell orders).

Depending on the strategy, this can lead to a lot of cancelled orders as the price moves away from your order.
Best read [the pricing documentation](https://www.freqtrade.io/en/latest/configuration/#prices-used-for-orders).

Personally, i use reversed pricesides with limit orders - so the bot still controls the worst price - but i match the best order on the other side of the orderbook.

It's however got nothing to do with the exchange itself - although some exchanges have a wider spread / lower volume - which can affect this.

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.
