### ISSUE TITLE
Add ping support to rest_client.py

### ISSUE THREAD

**Issue by sap51** [freqtrade/freqtrade#4288]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.8.6
  * CCXT version:1.40.99
  * Freqtrade Version: 2021.1

## Describe the enhancement

Add `ping` support to the `rest_client.py` script.

I'm using the `rest_client.py` script to monitor my freqtrade bot using a custom shell+python script, and it looks like I cannot use the `ping` command to verify that freqtrade is running fine.

According to the [documentation](https://www.freqtrade.io/en/latest/rest-api/#available-endpoints), I should be able to use the `ping` command on the HTTP endpoint, but sadly it's not working with the `rest_client.py` script.

Current result :
```
root@3fda54e2f926:/freqtrade# python3 scripts/rest_client.py --config config_binance.json ping
2021-02-01 01:34:03,473 - ft_rest_client - ERROR - Command ping not defined
```

Expected result (when freqtrade is running) :
```
root@3fda54e2f926:/freqtrade# python3 scripts/rest_client.py --config config_binance.json ping
{'status': 'pong'}
# or
{'pong': 'ok'}
# or
{'response': 'pong'}
```

Expected result (when freqtrade is NOT running) :
```
root@3fda54e2f926:/freqtrade# python3 scripts/rest_client.py --config config_binance.json ping
{'status': 'not_running'}
# or
{'pong': 'ko'}
# or
{'response': 'not_running'}
```
Thanks :)

**Comment by xmatthias** [comment]
I think this was left out intentionally, as ping is kindof a pointless command for the rest-client - which is supposed to control the bot and issue authenticated commands, while "ping" is not.
It'll only give you a "pong" back, no information about the state of the bot (nor shold it do that - as that's not the purpose of this command).

the show_config endpoint will give you the state (running / stopped) - so if you need this information, please use this endpoint.

Feel free to contribute this if you really need it - it should be no more than a few lines.

I've also labeled it good first issue, which means i'll not be working on this and it'll be left to new contributors - so please either try to contribute this yourself or be patient as it can take a while until it's implemented.
