### ISSUE TITLE
Startup candle count

### ISSUE THREAD

**Issue by Fimap9to1** [freqtrade/freqtrade#4297]
Hi, just to make sure, the startup candle count Is not always equal to the max timeperiod used right?

Because if I use a larger startup candle count I get better results in backtesting, than using the same startup as the bigger time period used for the indicators.

Ex. Bigger timeperiod is 200.
When I backtest using startup candle count = 200 I get 10% profit.
When I backtest using startup candle count = 480 I get 15% profit. 

(They are just examples to make the reader understand).

Thanks for your answer!

**Comment by xmatthias** [comment]
i'll say "it'll depend".

If you have more data than what is available (using `--timerange 20200201-` - and data is available from 2020.01.01) - it'll load more data to generate indicators, and then remove this additional data for backtesting.

if you don't specify timerange, the backtest-period is simply moved by startup_candle_count.

If you encounter substancial differences, then maybe your startup-candle-count is not correct.
If you only use "simple" indicators (e.g. sma / ema) - you can use the number as is.

If you however use different indicators, you must be carefull on how they are calculated - sometimes calling `indicator(dataframe, 20)` might use a double SMA (sma20 over sma20) - which would really have a lookback of 40 candles.

To be on the safe side, use a value wide enough (and don't download more data than what you intend to backtest) to avoid looking up every indicator - which in some cases can be quite tedious.

**Comment by Fimap9to1** [comment]
Why shouldn't I download more data than what I use for backrest?

If time range is 20201201-20201222 for example and I have data downloaded from 20200801 what's the difference? It always tests the time range selected + loads data from 5min*startup candle count right?

**Comment by xmatthias** [comment]
if you have more data than necessary (earlier data) - your backtest will start at 20201201 00:00.

If you only have data starting with 20201201  - then the backtest start time will be moved by startup_candle_count - so your backtest period will start maybe at 20201201 06:00 - or later - depending on how many candles you selected (and timeframe used).

**Comment by Fimap9to1** [comment]
Ok all clear, thanks!
