### ISSUE TITLE
Question about CCXT Pro Version

### ISSUE THREAD

**Issue by nodwan** [freqtrade/freqtrade#4304]
Hi, may the developer team will answer my question about the ccxt.pro version. my questions is, there will be a problem to use the professional version from ccxt?

thanks for answer.

**Comment by xmatthias** [comment]
You can use the professional version if you want (but there's no difference for freqtrade).
freqtrade is currently only using features available in the free version, so you'll have no benefits).

ccxt.PRO is built on top of the free version, extending it by certain features (like websocket support), which freqtrade however is not using at the moment.

We may optionally support ccxt.PRO in the future, but that is probably still quite a long way off.

**Comment by nodwan** [comment]
Many Thanks for your answer!!! i‘t was helpfull!!!

**Comment by vishalsawai** [comment]
@xmatthias Hi Matthias, is there any optionally support available in Freqtrade to support CCXT.PRO for websockets?

**Comment by xmatthias** [comment]
At this moment, there is not.
we will make sure to mention it in the release notes once this is the case.
