### ISSUE TITLE
Do i run Freqtrade  twuce and how can stop one?

### ISSUE THREAD

**Issue by NickThePigeon** [freqtrade/freqtrade#4305]
## Describe your environment

  * Operating system: raspberry os
  * Python Version: 3.7 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

Hello everyone,
I tried to search for an answer but could't find it.

i have this error in the log.

![Schermafbeelding 2021-02-03 om 17 50 20](https://user-images.githubusercontent.com/47255128/106780439-49658300-6648-11eb-8599-161cff18258c.png)

when i do `docker-compose ps` i get this 
![Schermafbeelding 2021-02-03 om 17 52 38](https://user-images.githubusercontent.com/47255128/106780769-9d706780-6648-11eb-81d6-d616bebfc3eb.png)

the problem came when changing the strategy.
i tried to kill one but i have the feeling i mess everything more up.

**Comment by xmatthias** [comment]
hm, best use `docker-compose down` to see if that stops all.

I'm honestly not sure if that will also remove the single runs, so you may need to stop (and then rm) the manually.

you might use `docker ps` to get the container name- and then stop them with `docker stop <containerid>` - before removing them with `docker rm <containerid>` .

both commands accept a list of space-seperated container-id's too.


For backtesting, you should never use `-d` - that will daemonize (bring it in the background) the container, so you won't see the result, and they'll backtest again and again.

**Comment by NickThePigeon** [comment]
Thank you very much,

No i didn't figured it out.
I moved the thread to freqtrade/freqtrade.
But this gives me the understanding i need.
Thank you!

**Comment by xmatthias** [comment]
Just to confirm - did the above  work out for you ... ? 

Ideally, `docker ps` should only show ONE freqtrade container (or more, if you're intentionally running multiple).

**Comment by NickThePigeon** [comment]
Yes everything worked out, docker-compose down did the job 

Now i have only one container running if i look with docker ps

**Comment by xmatthias** [comment]
Perfect, thanks for the feedback
