### ISSUE TITLE
how do I use the leverage parameter for a Kraken order?

### ISSUE THREAD

**Issue by BrannonKing** [freqtrade/freqtrade#4310]
I would like to try the leverage parameter on my Kraken buys. How do I do so? I can see that it is supported by ccxt like so:

https://github.com/ccxt/ccxt/blob/2571d9352e249ae303884d71e4be1f72ca9332a7/examples/py/margin-leverage-order-kraken.py

And if I get it working on the orders, would the back-testing take this value into account?

**Comment by xmatthias** [comment]
You can't (well you do everything by modifying the exchange class) - but i can only recommend against this, as it's not as simple as you think it is.

No profit calculation will take leverage into account - so your profit calculation is almost certainly wrong (it'll also not consider the leverage-fees, which are usually based on "time leveraged".

obviously backtesting will not care about leverage either, as it's not a concept currently known to freqtrade.

we will will surely not support margin / leverage until it's unified by ccxt (using it the way you show it in the example is NOT unified, but would require different behaviour for each exchange, so we'd be redoing the work ccxt is currently working on already).

**Comment by BrannonKing** [comment]
Thanks. Tracking here: https://github.com/ccxt/ccxt/issues/4834

**Comment by xmatthias** [comment]
exactly :)
