### ISSUE TITLE
print/log to console or file for each iteration (or last iteration at least)

### ISSUE THREAD

**Issue by rfamuk** [freqtrade/freqtrade#4311]
Have you searched for similar issues before posting it?
Sure. I checked several ways (-vvv, reading code LoggingMixing, logger, logfile,  ...)

## Describe your environment

  * Operating system: Windows
  * Python Version:  3.7 (command not available on windows, I guess it's 3.7)
  * CCXT version: 1.40.99 (from logs during backtests)
  * Freqtrade Version: freqtrade docker-65459086
  
## Your question
First of all congratulations for the project and the huge available documentation. It's great to see comunity like this one. A couple of years ago I was playing with other implementation where it took me arround 4 months (freetime before sleep) to implement the same I implemented here 4-5 nights (I developed my own stop loss, trailing lost, ...). 

I read about logs on different locations on the documentation but I'm not being able to just print some lines on each iteration of 'populate_indicators'/'populate_buy_trend'/'populate_sell_trend'.

I'm aware about the impact, but I just need it for some small checks to be sure that stuffs I'm implementing over some libraries are correct. 

I'm sure I'm missing something because it should not be so difficult and probably it's documented somewhere but due to my lack of experience on python or python keywords I'm not being able to find the way to re-enable the log during backtesting or similar. Maybe is related to work with docker over Windows where logfile doesn't shows the same information that the redirection of stdrr or similar...

I found some interesting lines along the code but I was not able to use that information to re-enable the logger.info or similar.

I have been checking for arround 2-3 hours trying to do it and it's an idiot thing that it's taking too much time, I would like to know if you can provide me some way/light about this.

As developer of embedded systems with 8 years experience I can say that code is really nice (clear, tests coverage, comments, ...) and I'm starting to love python language trough this activity. Congratulations again.

Sorry about the idiot question and thank you so much in advance

**Comment by xmatthias** [comment]
i don't see why `pring(whatever)` should not work on windows unless you have the terminal / console configured to not show stdout (which i'm not sure is even possible) - but it'll not show up in log-files, just on the console.

If you want it as log, then you'll need the following

``` python
import logging

logger = logging.getLogger(__name__)

### Now you can use logger.info('asfd') to log

```

**Comment by rfamuk** [comment]
Due to some strange reason:
- the common print('test') 
- logger.info('test) (using --logfile and without using it)

that I'm including on the populate_indicators funcion onmy strategy only shows the message on console or files during the first iteration (candle) but not for the rest of them. 

For instance if i'm running backtest for 1m along one day of backtest, I'm expecting to see the message 1440 times, one each time the candle is populate, but it's only showed one time per pair.

Certainly from my point of view it would be better using something such a callback at the end of a backtesting to print some final information that maybe I persist on a cust_info = {} declared on the class but something simpliest such as the print on each iteration is enough by checking the last iteration (for each pair). I introduced a counter to check that is the first one.

I already explore are played a little with hperloop, generate my own dataframes, ... so this should be easiest..

This is Windows + docker + power shell (following the guide ) but also tested with mingw64 console from git windows program and using the output redirection 2>&1 without success.

On code I tested some probably not correct at all things such as

(on class declaration)
```
// Using the own logging
    logger = logging.getLogger(__name__)
    logger.('start 1')

// try with other logger that could have access to print always if there is some specific restriction (I'm not sure if this is valid, I show it on the code somewhere)
    logger2 = logging.getLogger('freqtrade')
    logger2.('start 1.2')

// checking if common disable works
    logging.disable(logging.DEBUG)
    print("Log enabled: ",logger.isEnabledFor(logging.DEBUG))

// try enable it again
    logging.disable(logging.NOTSET)
    print("Log enabled: ",logger.isEnabledFor(logging.DEBUG))

// trying to remove some seems-related/similar restriction I show in the code
    LoggingMixin.show_output = True
```

(on populate functions - message I'm expecting to see each candle)
```
    logger.info('iteration1')
    print('iteration2')

```

with process_only_new_candles = True option on config it should show 1440 from my point of view, without this maybe even more on real or dry mode I guess

Maybe with this better explanation you can understand the issue.

Something such as if there is something similar to
```
    @classmethod
    def setUpClass(cls):
        logging.disable(logging.DEBUG) # disable debug logs that slow backtesting a lot
```
I found in
https://github.com/freqtrade/freqtrade/blob/a2f7709cfd9e53408cb0a7a19d5bbdf24c673929/test/test_backtesting.py

but is not the real backtest execution class, is a unity test so is not the issue.


------------

Or.. I'm totally wrong and this is the last execution, since I have all the candle results on the dataframes related with indicators... :?

**Comment by xmatthias** [comment]
I think you didn't understand how backtesting works ...

To archive the speed backtesting has, all `populate_*` methods are called once with the full dataframe during backtesting.

Due to this, you need to be slightly carefull with how you calculate your indicators (to not look into the future) - but the performance penalty to generate indicators "in a loop" would be insanely high).

Because of this, you also can't access the trade object in "Populate_" methods during backtesting, as it simply doesn't exist when the methods are called.

So if it's logged once (per pair) during backtesting, then it's working as expected.

**Comment by rfamuk** [comment]
Thank you so much for the clarification. Really nice.

In that case all have sense for me, 
- The log output I'm able to see right now is correct
- The fact of implement on this way the back testing to speed up the process.

Not a problem, I will process my own algorithms for the X iterations/candles on the populate indicators (this is insane but it's only for development purposes) in the case of backtesting/hyperopt

I guess this is also applicable for Hyperopt, right?

I guess I can expect to have a call to populate indicators on each iteration/candle in dry-mode/real-mode (with and without process_only_new_candles), so the implementation will be slightly different on this mode. Right?

**Comment by xmatthias** [comment]
Hyperopt is just calling backtesting over and over again, with slightly different parameters...

Dry / live mode works on "live" data - so you'll always have the latest ~500 candles to work with - which are called on every iteration (every 5 s by default) - or once per candle (with `process_only_new_candles=True`).

**Comment by yougop** [comment]
Very interesting, didn't get it also. Now things are clearer. Miss the typical print statement on each candle though...
