### ISSUE TITLE
Possibility to trade different token based on a specific chart?

### ISSUE THREAD

**Issue by chikko80** [freqtrade/freqtrade#4330]
Hello, 

in the last few weeks, i have played a lot with the freqtrade bot and all his special features like hyperopt etc.
Yesterday i came up with an idea about the Binance Leveraged Tokens, but i couldn't find anything in the docs so i couldn't solve the problem.
The idea is to track the underlying chart of the leveraged token with a trend strategie. If the chart is uptrending the strategie should buy the UP token, if its downtrending buy the DOWN token.
So for instance: 
A strategie which uses the MACD to determine the trend would scan the BTC/USD chart. 
If there is a uptrend buy the BTCUP, otherwise the BTCDOWN.

Is that possible with freqtrade?

greetings chikko80

**Comment by xmatthias** [comment]
Just use [informative pairs](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-informative_pairs) to track the underlying asset, and use the leveraged tokens as "real" pairs.
