### ISSUE TITLE
list-data should report date ranges

### ISSUE THREAD

**Issue by BrannonKing** [freqtrade/freqtrade#4339]
Please enhance the list-data command to show the date ranges on the downloaded data, including any gaps in the middle. In other words, there may be multiple ranges per pair.

**Comment by xmatthias** [comment]
While this seems interesting at first, I've looked at this in the past, and it'll not be possible for now.

It would require us to load all data (a json limitation) - and if i look at my data-folder for binance alone, i'd be reading 4+GB of data just for the list command, which is no option.

For that reason, we will not provide this option for now.

**Comment by BrannonKing** [comment]
Ah yes -- the fundamental issue of storing historical data in JSON. Let's count this as a vote for storing historical data in Sqlite instead. Alternatively, we could put each date range into its own JSON file. Then use a file naming scheme that makes it obvious.

**Comment by xmatthias** [comment]
Well freqtrade supports hdf5 as storage format, which does not really have this limitation (but json is the default, and is probably used by almost all users).

Using SQLite will most likely not happen - as that's not a suitable format for this kind of data.
