### ISSUE TITLE
building freqtrade image locally error

### ISSUE THREAD

**Issue by pedroelmoucho** [freqtrade/freqtrade#4347]
Hello,

I am currently trying to modify freqtrade code and generate a new docker image to test it.
Unfortunately, I am facing an issue when building the docker image

I'm on Windows 10 64bit

Command line output : 
```PS 
D:\Dev\freqtrade> docker build -t freqtrade .
Sending build context to Docker daemon  28.44MB
Step 1/24 : FROM python:3.9.1-slim-buster as base
 ---> 8c84baace4b3
Step 2/24 : ENV LANG C.UTF-8
 ---> Using cache
 ---> f8a7915da409
Step 3/24 : ENV LC_ALL C.UTF-8
 ---> Using cache
 ---> d8570f1e21ec
Step 4/24 : ENV PYTHONDONTWRITEBYTECODE 1
 ---> Using cache
 ---> 9f899c09b6b3
Step 5/24 : ENV PYTHONFAULTHANDLER 1
 ---> Using cache
 ---> 544a9d4db236
Step 6/24 : ENV PATH=/root/.local/bin:$PATH
 ---> Using cache
 ---> ed866369cabe
Step 7/24 : RUN mkdir /freqtrade
 ---> Using cache
 ---> 1edd1e8a069d
Step 8/24 : WORKDIR /freqtrade
 ---> Using cache
 ---> 65c443a6866f
Step 9/24 : FROM base as python-deps
 ---> 65c443a6866f
Step 10/24 : RUN apt-get update     && apt-get -y install curl build-essential libssl-dev git     && apt-get clean     && pip install --upgrade pip
 ---> Using cache
 ---> 98de328de9f9
Step 11/24 : COPY build_helpers/* /tmp/
 ---> Using cache
 ---> 66ccd3ac570e
Step 12/24 : RUN /tmp/install_ta-lib.sh
 ---> Running in 4d5e61619084
/tmp/install_ta-lib.sh: 10: /tmp/install_ta-lib.sh: Syntax error: "&&" unexpected
The command '/bin/sh -c /tmp/install_ta-lib.sh' returned a non-zero code: 2
```

FYI : I made my modifications on the master version atm
I'm using your docker file
TA lib is correctly installed on my computer
I'm using powershell

If my issue is missing informations or whatever, don't hesitate, I didnt find the issue template

Any ideas ?
Thanks

**Comment by xmatthias** [comment]
How's your docker setup? are you using linux containers, or windows containers?

(we do not support windows containers).

**Comment by pedroelmoucho** [comment]
I'm using Linux containers, just checked 5mn ago :)
Here is the dockerFile (without .txt ofc)
[Dockerfile.txt](https://github.com/freqtrade/freqtrade/files/5958603/Dockerfile.txt)

And the install_ta script
[install_ta-lib.txt](https://github.com/freqtrade/freqtrade/files/5958608/install_ta-lib.txt)

Those files are same as master ones

**Comment by xmatthias** [comment]
hm, building on docker from windows is ... odd sometimes. The below is a suspicion - but most likely a good one ...

i suspect it's because you checked out the files with `\r\n` line-endings (git does that by default) ... but for the linux container, it'll be needed as `\n`.

The "simplest" way might be to do the "git clone" with wsl2 ...

**Comment by pedroelmoucho** [comment]
Genius
I update line endings with notepad++, everything working fine for the moment
Thanks a lot mate

**Comment by xmatthias** [comment]
yeah but now they'll all show up as modified in `git status` - which is obviously the downside to this

**Comment by dream2541** [comment]
- 21:01:47 ~/trading/freqtrade$ python3 -V Python 3.7.3
