### ISSUE TITLE
Is it possible to use ROI in populate_sell_trend()?

### ISSUE THREAD

**Issue by EloutV** [freqtrade/freqtrade#4348]
Hi,

Relatively new to Freqtrade I was wondering if you can use ROI of the trade in the populate_sell_trend() method?
Tried to look for 'roi' in the TA lib (populate_indicators method), but it is not part of the talib.abstract.
Any sugestions?

Thanks,
Elout

**Comment by xmatthias** [comment]
ROI is not an indicator.

Due to the way freqtrade works, you also cannot use ROI in the populate* methods - at least not during backtesting, as you're defining signals only - the trade itself is however not known until the real backtesting starts.
