### ISSUE TITLE
Mac OSX: No usable python found. Please make sure to have python3.7 or newer installed

### ISSUE THREAD

**Issue by aDu** [freqtrade/freqtrade#4349]
```
$ which python
/usr/bin/python

$ which python3
/usr/bin/python3

$ which pip3
/usr/bin/pip3

$ ./setup.sh 
No usable python found. Please make sure to have python3.7 or newer installed
```

**Comment by xmatthias** [comment]
The issue template is there for a reason, please fill it out.
It'll tell us which version you're trying to install - which version of python you got, ... 

Your description only shows that you got python3 installed, but not which version. 
Most likely, your python3 is actually python3.6 - which is no longer supported.

The checks setup.sh is doing are for `which python3.7`, `which python3.8` and `which python3.9`, and the output tells me that you got neither of these installed.

**Comment by aDu** [comment]
```
21:01:42 ~/trading/freqtrade$ python -V
Python 2.7.16
21:01:47 ~/trading/freqtrade$ python3 -V
Python 3.7.3

21:01:50 ~/trading/freqtrade$ pip3 freeze | grep ccxt
21:02:04 ~/trading/freqtrade$ pip | grep ccxt
-bash: pip: command not found

21:02:37 ~/trading/freqtrade$ git log -1
commit 3110d2dbb192efe7944b09f68a10410daad39fea (HEAD -> develop, origin/develop, origin/HEAD)
Author: Matthias <xmatthias@outlook.com>
Date:   Tue Feb 9 20:03:03 2021 +0100

    Add small test cases
```

OS: macOS Big Sur 11.1 (20C69)

**Comment by aDu** [comment]
I worked around it by adding inside check_installed_python method:

```
PYTHON=python3
check_installed_pip
return
```

Before I didn't read the bash file thoroughly and only tried running PYTHON=python3 before running the bash file.

**Comment by patlux** [comment]
Same issue here on a Mac mini m1.

```bash
❯ python3 --version
Python 3.8.2
```

Added `PYTHON=python3` to the top of `setup.sh` to fix it.

**Comment by xmatthias** [comment]
based on my understanding, you should also have a `python3.8` binary.

if not, then that's something quite specific to Mac - which is only popping up now .

**Comment by FaisalAfroz** [comment]
I was also having same error `No usable python found. Please make sure to have python3.7 or newer installed` while installing from script.
So while installing i just removed the below check from setup.py. And then run `./setup.sh --install` . After the setup completed it hard reset the changes and symlinked to my python3.9.
```
if [ -z ${PYTHON} ]; then
        echo "No usable python found. Please make sure to have python3.7 or newer installed"
        exit 1
fi
```
