### ISSUE TITLE
Is it possible to set startup_candle_count for informative pairs?

### ISSUE THREAD

**Issue by cakeslice** [freqtrade/freqtrade#4351]
For example:

A strategy using the DOGE/USDT pair on a 5m timeframe and an informative pair of DOGE/USDT on a 12h timeframe.

Will backtesting use the same startup_candle_count that was set in the strategy for the informative pair? If not, is it possible to set one for it?

**Comment by xmatthias** [comment]
startup_candle_count does not apply to informative pairs - it'll always load all available data.

as you're however usually merging the informative dataframe to the real dataframe, the cutoff will automatically apply as there's nothing to match to in the dataframe with the original timeframe.

**Comment by cakeslice** [comment]
Alright, about the merging just to be clear, does it mean that if we have a 5m original timeframe with 1000 candles, and a 12h informative timeframe, the merged time frame will never have more than 6/7 candles of the 12h timeframe?

Thanks

**Comment by xmatthias** [comment]
for live - for sure, you'll only have ~500 candles (depends on the exchange) - which is about 3 days. obviously, if you use 12h candles, you merge them to the 500 5m candles, so you'll only have this timerange.

Usually, you'll however use a SMA / EMA (or whatever else) on the 12h timeframe - so by calculating that BEFORE merging, you can get more historic data - so it's not really limiting if done correctly.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
