### ISSUE TITLE
More options for verbosity

### ISSUE THREAD

**Issue by vakker** [freqtrade/freqtrade#4354]
## Describe the enhancement

Currently the level of verbosity is either `INFO` or `DEBUG`, which can clutter the terminal.
It would be great to choose `WARNING`, especially when a batch of strategies are evaluated, currently it's a bit messy to go through all the outputs.

**Comment by xmatthias** [comment]
This is currently not possible, and honestly, i also don't plan on introducing this.
Unimportant messages have DEBUG level, while Warnings, Errors and Exceptions have their respective level.

Increasing the level of certain normal (but important) messages to Warning would be highly missleading - and would mess up people's log-setups (normal log-analysis tools will by default highlight everything > info).


while i understand that it can be verbose in certain instances - it'll also be helpful in case of problems.

In "live" modes (dry-run / live) it might also lead to many missed, but important messages (in case of a problem / issue).
Would people then open an issue with only warning messages, we'd probably have to close these issues without further action, as it's simply not clear what was happening at the time.

**Comment by vakker** [comment]
What I meant is having the option to use other verbosity levels, so only the warnings and errors would be showed and not info logs. 
I didn't mean to change the log level of the messages in the code. 

I.e. having the option to use something like in loggers.py:
```
if verbosity == 0:
    level = logging.WARN
elif verbosity == 1:
    level = logging.INFO
else:
    level = logging.DEBUG
logging.root.setLevel(level)
```

**Comment by xmatthias** [comment]
i do understand this, but please read above as to why this will make my job as maintainer much more difficult.
