### ISSUE TITLE
Running two strategies, each optimized for one pair, on same exchange account

### ISSUE THREAD

**Issue by atc93** [freqtrade/freqtrade#4355]
Hello there,

I browsed the many questions/answers available but I believe I did not find the answer to my question. My goal is to run on one account (let's say Binance) two different strategies, each one optimized for a given pair.

Let's say I ran the hyper-optimization individually for both BTC/USDT and ETH/USDT and I came up with different optimized strategies. Now say I have a Binance account all setup with API key and whatnot and $USDT 100. I am hoping, using USDT as the staked currency (using "tradable_balance_ratio": 0.99), to run both strategies at the same time on the same account/money. They de facto will be "competing" because as soon as one strategy gets a buy signal, all the money will be invested and if a buy signal is triggered for the second pair, no money would be available. But this allows me to use one money pool, and if the pairs/strategies are chosen wisely, the transaction will not be competing with one another.

My first thought was to stretch what freqtrade can do by running two bot instances with same API information, each one tailored to a given pair, using the same sqlite db. So when a pair starts a transaction, the db locks out the possibility of trading with the other pair. But that might sound a bit sketchy and asking for problem.

So I wonder: what is the best way to proceed forward to accomplish what I want?

Thanks!

PS: besides this question, freqtrade has been working very well for me and my live trading!

**Comment by xmatthias** [comment]
personally, i would split the money between the 2 pairs, so you're not "all in" on either pair, but you're in with 50% of your money on each pair. 
It'll probably reduce your risk in case a trade goes south (btc can run into a stoploss, while ETH still makes up for it in the potentially parallel trade).
it's a personal opinion though, not investment advice :smile:

I guess running 2 bots would work, you don't even need to lock anything in the database (when running 2 bots, you'll need to use 2 databases anyway) - the 2nd bot will just not have enough money left to buy.

As you're only talking about only 2 pairs, a potentially better alternative might be to combine the 2 strategies and check with `if metadata['pair'] == 'BTC/USDT':`- creating different signals based on which pair you're using.

it'll get messy soon if you have 20 pairs with this - but for 2 pairs, i don't see why it shouldn't work.
By then setting `max_open_trades=1` - you'd allow the bot to go "all in" - without causing a ton of "not enough balance left" messages, which you would get with 2 bots, if one bot uses all available money.

**Comment by sanoj2021** [comment]
Hi, maybe consider implementation of pairwise strategy customization with hyperopting option in future updates is worthwhile? Would be a really nice feature in my opinion. Thanks, greetings

**Comment by slowdive42** [comment]
> personally, i would split the money between the 2 pairs, so you're not "all in" on either pair, but you're in with 50% of your money on each pair. It'll probably reduce your risk in case a trade goes south (btc can run into a stoploss, while ETH still makes up for it in the potentially parallel trade). it's a personal opinion though, not investment advice 😄
> 
> I guess running 2 bots would work, you don't even need to lock anything in the database (when running 2 bots, you'll need to use 2 databases anyway) - the 2nd bot will just not have enough money left to buy.
> 
> As you're only talking about only 2 pairs, a potentially better alternative might be to combine the 2 strategies and check with `if metadata['pair'] == 'BTC/USDT':`- creating different signals based on which pair you're using.
> 
> it'll get messy soon if you have 20 pairs with this - but for 2 pairs, i don't see why it shouldn't work. By then setting `max_open_trades=1` - you'd allow the bot to go "all in" - without causing a ton of "not enough balance left" messages, which you would get with 2 bots, if one bot uses all available money.

Hi. I want to know that if run 2 pairs in a strategy with max_open_trades=1, when both of the pairs give entry long, what will the strategy do? Thank you a lot!

**Comment by stash86** [comment]
> > personally, i would split the money between the 2 pairs, so you're not "all in" on either pair, but you're in with 50% of your money on each pair. It'll probably reduce your risk in case a trade goes south (btc can run into a stoploss, while ETH still makes up for it in the potentially parallel trade). it's a personal opinion though, not investment advice 😄
> > I guess running 2 bots would work, you don't even need to lock anything in the database (when running 2 bots, you'll need to use 2 databases anyway) - the 2nd bot will just not have enough money left to buy.
> > As you're only talking about only 2 pairs, a potentially better alternative might be to combine the 2 strategies and check with `if metadata['pair'] == 'BTC/USDT':`- creating different signals based on which pair you're using.
> > it'll get messy soon if you have 20 pairs with this - but for 2 pairs, i don't see why it shouldn't work. By then setting `max_open_trades=1` - you'd allow the bot to go "all in" - without causing a ton of "not enough balance left" messages, which you would get with 2 bots, if one bot uses all available money.
> 
> Hi. I want to know that if run 2 pairs in a strategy with max_open_trades=1, when both of the pairs give entry long, what will the strategy do? Thank you a lot!

Please open new issue instead of reviving old issue. Thanks
