### ISSUE TITLE
Wrong Calculation of Profit

### ISSUE THREAD

**Issue by bhavyashah98** [freqtrade/freqtrade#4358]
<img width="302" alt="Screenshot 2021-02-12 at 5 59 03 PM" src="https://user-images.githubusercontent.com/22994444/107768444-73135e00-6d5c-11eb-90f9-9eb04edfb66e.png">
When u see open rate and close rate, close rate > open rate giving me profit but this is showing me the loss of 10%. It perfectly worked out when I view my balance but still this info ruins the calculation of daily, profit, and other functionalities.

**Comment by xmatthias** [comment]
Please fill out the issue template, otherwise we'll close this issue.

Without knowing which version you use, we will not even start investigating.
Also, please provide application logs from the time the trade was sold.
