### ISSUE TITLE
Binance no dry_run - error message: WARNING - Unable to create trade for (): Available balance (0.0 BTC) is lower than stake amount (0.0005 BTC)

### ISSUE THREAD

**Issue by castalia3** [freqtrade/freqtrade#4359]
## Describe your environment

  * Operating system: Virtual machine Ubuntu 20.10 on Windows 10
  * Python Version: 3.8.6 
  * CCXT version: 1.41.70
  * Freqtrade Version: freqtrade develop-3110d2db 
  
## Your question
I am trying for the first time to start freqtrade with real money from Binance (the sandbox works quite well), i've 60usd  (0.0012BTC)

I get the following error message (for all the pair list): 

`2021-02-12 12:41:10,659 - freqtrade.wallets - INFO - Wallets synced.
2021-02-12 12:41:10,661 - freqtrade.freqtradebot - WARNING - Unable to create trade for XMR/BTC: Available balance (0.0 BTC) is lower than stake amount (0.0005 BTC)
`

Thats my config.json:
------------------------------------------------------------------------------------------------
{
    "max_open_trades": 2,
    "stake_currency": "BTC",
    "stake_amount": 0.0005,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "5m",
    "dry_run": false,
    "cancel_open_orders_on_exit": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
    "exchange": {
        "name": "binance",
        "key": "censored but correctly compiled",
        "secret": "censored but correctly compiled",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
        "pair_whitelist": [
            "ALGO/BTC",
            "ATOM/BTC",
            "BAT/BTC",
            "BCH/BTC",
            "BRD/BTC",
            "EOS/BTC",
            "ETH/BTC",
            "IOTA/BTC",
            "LINK/BTC",
            "LTC/BTC",
            "ADA/BTC",
            "NEO/BTC",
            "NXS/BTC",
            "XMR/BTC",
            "XRP/BTC",
            "XTZ/BTC"
        ],
        "pair_blacklist": [
            "BNB/BTC"
        ]
    },
    "pairlists": [
        {"method": "StaticPairList"}
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "censored but correctly compiled",
        "chat_id": "censored but correctly compiled"
    },
    "api_server": {
        "enabled": false,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "jwt_secret_key": "somethingrandom",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "SuperSecurePassword"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

------------------------------------------------------------------------------------------------

In telegram i can see my correct balance:

/balance

EUR:
 Available:  49.10000000
 Balance:  49.10000000
 Pending:  0.00000000
 Est. BTC:  0.00124781

Estimated Value:
 BTC:  0.00124781
 USD:  59.08

How to resolve?

Thanks in advance!!

**Comment by xmatthias** [comment]
Well, your `/balance` statement shows that you have ~50 EUR ... but no BTC.
It shows the estimated BTC value - but there's no real value in the account.
if your stake-currency is BTC, you should hold the balance in BTC as well.

In general, there's nothing wrong with using EUR  as stake currency (other than maybe volume) - but then your `stake_currency` should be EUR - and pairs will need to be adjusted as well.

You should also be warned that not all strategies simply support swapping currency - as markets can be quite different depending if the quote-currency is a crypto currency or a fiat (or fiat like) currency.

**Comment by castalia3** [comment]
@xmatthias 
Thanks for answer me so quickly, so i should  convert my euros to BTC on binance first.
thanks also for your reminder about the strategy, for now it is a simple test to be able to use real money. 
I try to convert to BTC and relaunch the program, update as soon as possible.
Thanks!

**Comment by castalia3** [comment]
@xmatthias
Problem solved converting euros to bitcoins, thanks!
