### ISSUE TITLE
Bitvavo

### ISSUE THREAD

**Issue by hdkbouma** [freqtrade/freqtrade#4360]
Freqtrade works very well with Bitvavo exchange

**Comment by xmatthias** [comment]
First of all, thanks for the info.


which functions specifically did you try?
what type of orders (limit, market, ...?)

**Comment by hdkbouma** [comment]
All functions but Edge.
order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }
Works flawlessly for a month now. Compliments!

**Comment by hdkbouma** [comment]
All functions but Edge.
order_types = {
'buy': 'limit',
'sell': 'limit',
'stoploss': 'market',
'stoploss_on_exchange': False
}
Works flawlessly for a month now. Compliments! 

Matthias schreef op 13-02-2021 08:17:

> First of all, thanks for the info. 
> 
> which functions specifically did you try?
> what type of orders (limit, market, ...?) 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/freqtrade/freqtrade/issues/4360#issuecomment-778575635
[2]

**Comment by xmatthias** [comment]
that's honestly very great to hear.

I'm however not sure how to proceed with that information - i'm cautious on adding it to the list of officially supported exchanges, as that would mean we would need to be able to support it in case of future changes / problems - however being able to support an exchange basically means having at least a bit of money there to be able to live-trade - which honestly, i currently have no interrest (nor time) to do.

**Comment by hdkbouma** [comment]
I understand.
I will try to help if there are Bitvavo specific questions.

**Comment by xmatthias** [comment]
Perfect, thanks a lot! I've added bitvavo now to the docs as "community tested" - so others can benefit from your positive experience (and especially, from your great feedback!)
