### ISSUE TITLE
I figured a way to trade in Binance Futures BUTT

### ISSUE THREAD

**Issue by gring0-cripto** [freqtrade/freqtrade#4362]
So devs and gents, i found a way to trade (half way there) at Binance Futures WITH Leverage, as you all know when you choose the options in Leverage (Isolated or Cross and Leverage), they stay there as default, so using the bot to get in is fairly easy using the ccxt help i found inother issues here. And about the entries, in the config file, we have this option ""stake_amount": 10.0," per exemple. The bot will take this amount and divided by the X amount leverage you chose in the Binance Futures GUI, so lets say your amount is set to 10, your entry price will be 1$ with 10x leverage. BUT when it gets to selling, there's the interesting part, seems like the bot gets it's WALLET DATA from the AMOUNT of COINS you have, not the amount of USDT you have in binance futures so it gets the error "Not enough amount to sell. Trade-amount: X Wallet: 0"
Can anybody from the devs point me where is the actual code that pulls the data from the wallets ? Since it's knowing i have balance in my Futures Wallet so the code is implemented somewhere.

Note: when i use the /balance it shows the actual balance i have in USDT in the futures account.

I've red on other issues that freqtrade ISN'T compatible with Binance Futures, but i'm about to make it happen if someone helps me finding the code that's used to get the Data from the Wallet.

I don't know if i've been clear with this. I just brainstormed everything that i've done in more that 2 no sleep days in this small text lol. If anybody needs more clarifying, i'm open to explaining and showing my config file and the strategy

EDIT: i thought about something earlier today. when the bot sells, it used the data from the database created in the freqtrade folder, if you run 2 bots, 1 actual bot for buying the dips, and another DRY RUN bot just to signal the SELLS so you sell manually at will, then delete the database so the bot doesnt "see" the open order that couldnt be closed because of the error mentioned above. it's a nice little "hack" for not to miss the dips, but the bot is made to buy and sell lmfao. i guess i figured it out i swear the only help i need is someone pointing me where is the code that is used to get the data from the SPOT WALLET not the FUTURE` WALLET in USDT, not the ACUTAL COINS

**Comment by xmatthias** [comment]
you didn't figure out anything, then.

Opening a trade is easily possible in both futures and margin markets, most likely with 1-2 config changes.
it's selling that won't work (simply because futures work completely different).

also, all your profit calculations will be wrong - as you can't use the profit-calculations as is for leveraged trades.

As i said in multiple other issues - this will waste our time until ccxt has unified futures / margin markets - which they haven't so far.
Implementing it for binance alone, we risk taking decisions that will then block implementation of other exchanges, simply because it may work completely different than in other markets.

**Comment by gring0-cripto** [comment]
> you didn't figure out anything, then.
> 
> Opening a trade is easily possible in both futures and margin markets, most likely with 1-2 config changes.
> it's selling that won't work (simply because futures work completely different).
> 
> also, all your profit calculations will be wrong - as you can't use the profit-calculations as is for leveraged trades.
> 
> As i said in multiple other issues - this will waste our time until ccxt has unified futures / margin markets - which they haven't so far.
> Implementing it for binance alone, we risk taking decisions that will then block implementation of other exchanges, simply because it may work completely different than in other markets.

thx

**Comment by gring0-cripto** [comment]
can you at least point me where is the SELL SIGNAL code that generate the SELL ORDER on spot trading ? 

edit? my idea is to /delete the trade when the sell occures, ill be having a dryrun bot running for signal aswell
i be closing trades manually
what i mean is instead of actually selling the order, i want the bot to just delete the trade from the database when the sell signal occurs

**Comment by xmatthias** [comment]
all live trading logic is in `freqtradebot.py`.
orders are placed by `exchange.py` - or the respective exchange subclass in the `exchange` package.

I will however close this - as your way does not seem to be something we'll support in freqtrade itself - as it's a rather manual process, and it doesn't appear like you were able to use futures for anything other than placing an order.

I can also only recommend to not use this as you describe it - as the risk will be quite high (the bot may enter a trade while you're sleeping, and when you wake up, you're down 50%).

**Comment by defidummy** [comment]
love freqtrade but wish we also have futures tradind. Can anyones recommend any other repos/dashboard?
