### ISSUE TITLE
Incorrect/superfluous `cancelled due to timeout`

### ISSUE THREAD

**Issue by thisiscam** [freqtrade/freqtrade#4365]
## Describe your environment

  * Operating system: Mac
  * Python Version: 3.9 (`python -V`)
  * CCXT version: 1.41.70 (`pip freeze | grep ccxt`)
  * Freqtrade Version:  develop-4cb67f14 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

This is an problem I observed in the Telegram messages and it occurs in production (not dry-run).

### Steps to reproduce:

Since it's only reproducible in production, I can't describe the steps here (that will be hard and also dangerous).
But I will describe what the bot did and how I observed the issue.

Assume their's only one tradable pair XXX: 
  1. Bot opens buy order and the order is filled
  2. Bot opens cell order and the order cannot be filled in time; bot times out and cancelled the sell order 
  3. Bot re-opens another sell order after a while, the sell order is again cannot be filled immediately. 
  4. Command `\status` in Telegram. 

### Observed Results:

Telegram RPC comes back with:
```
Trade ID: _ (since 9 hours ago)
Current Pair: XXX
Amount:  10 (... USD)
Open Rate: ...
Current Rate: ...
Current Profit: ...%
Stoploss: ... (-...%)
Stoploss distance: ... (-..%)
Open Order: (limit sell rem=10) - cancelled due to timeout
```

Notice the _cancelled due to timeout_ message at the very end.
The new sell order is not cancelled  at this point, but it is reported as cancelled. 

### Relevant code exceptions or logs

I think the problem is caused by this line https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/freqtradebot.py#L1247.
Notice that `trade.sell_order_status` is only modified here (other than `migrations.py` and `models.py`, which I don't believe are relevant for this issue). 
I think what happened was 
1. `trade.sell_order_status` is changed to "cancelled due to timeout" at this line due to the first cancelled sell order
2. the flag is never reset/cleared when the second sell order comes in

Not a huge problem but would be nice for a fix (to avoid future confusion)

**Comment by xmatthias** [comment]
A minor one for sure :D 

great catch though - i never look at "/status" THAT closely (if i would, i'd start to micro-manage my trades) ... :laughing:
