### ISSUE TITLE
Stop Loss timeout?

### ISSUE THREAD

**Issue by figaro001** [freqtrade/freqtrade#4366]
Hi,
The bot will perform an additional check when the price reaches Stop Loss level. After the specified amount of seconds passes, the bot will check if the price is still below Stop Loss level. If yes, the bot closes the deal by market order. If not, the deal remains active.

Can you please implement this? So that the bot does not catch sharp and short-term falls.

**Comment by xmatthias** [comment]
the short answer is "no, we will not implement this".

I understand what you're trying to do - however please consider a stoploss as a hard stop, protecting your assets.

by "waiting" after stoploss triggered, you convert it to a soft stoploss - which can cost you a considerable amount of money.

assume you configure a stoploss of 5%.
* you enter a trade, and after a while, it goes to -5.5%.
* you'd like to wait for X amount of time before selling this pair

Now if the pair recovers, all is good, and you were right.
However, if the pair does not recover, your loss might not be 5% - but your loss can be 20% or more - depending on how much the pair falls without recovering in time.

The risk for this is therefore to high to have such a thing built into the bot.

---

By reading the documentation carefully you will see that the strategy might be able to do such a thing already by cleverly combining a few methods. I will however not describe these in detail here and leave this research up to you, as i don't think this should be used - and will only really work in a bull market, in a bear market, this has the potential to ruin you.
