### ISSUE TITLE
API v1 http to https

### ISSUE THREAD

**Issue by rylos** [freqtrade/freqtrade#4377]
## Describe your environment

  * Operating system: __ubuntu__
  * Python Version: __3.8___ (`python -V`)
  * CCXT version: __last___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _develop___ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I'm currently developing a Garmin ConnectIQ widget to fetch data from freqtrade API v1 and everthing works very well on the simulation via http requests. Problem is that garmin uses Android BT communications and when compiling for real use https is enforced on every webrequest. So my question is, what's the best and easy way to have https on the API? Thank you.

**Comment by xmatthias** [comment]
First of all - we don't recommend to expose the freqtrade API over the internet.
Unless you are 100% confident on how to properly secure a webserver, you should clearly not do that, but only allow connections through a VPN / ssh tunnels.


In general, you'll probably want an nginx reverse proxy (or an alternative) in front of the api, which will handle https for you.

We do not have a guide, nor will we support such a setup, as this can go into a lot of detail, which we lack ressources to properly support as a free, open source project.
There's plenty of nginx guides on the internet, and i don't think you'll need something specific / extra complicated to work with the Freqtrade API.

**Comment by rylos** [comment]
Thanks for your reply, nginx is what I was looking for.

**Comment by Theagainmen** [comment]
@rylos I recently got my hands on a Garmin watch too (the venu) and I have been looking into developing stuff like this too. I'm very new in that field and can barely get a start, could you please share your project and maybe provide some information? I'm very interested!

**Comment by rylos** [comment]
@Theagainmen I will release it on Garmin App Store when it's ready, as a free widget (almost completed and working fine). Name will be "freqtradeIQ". You will just need to setup API, token and the SSL proxy (to have API over https) like I've done following @xmatthias tip. Working fine now with https.

**Comment by Theagainmen** [comment]
@rylos ok thank you, can you also make it open source maybe, or share the code? I would like to learn from it, if you want you can add me on Discord through the Freqtrade channel (https://discord.gg/MA9v74M), my name is the same as my GitHub name.
