### ISSUE TITLE
Variables shared between the trades

### ISSUE THREAD

**Issue by DRPozdniakov** [freqtrade/freqtrade#4383]
May i ask you what is best way to store and keep updated some value between the different dataframes.

My purpose is to add into the strategy some parameter which will describe is the market green or bad, i want to calculate that parameter based on one set of all "closed" values of my pairslist. What would be the proper way to do that?

I guess the strategy settings are stored somewhere on start and they are not getting read each takt of indicators filling?

**Comment by xmatthias** [comment]
the [docs got you covered](https://www.freqtrade.io/en/latest/strategy-customization/#storing-information).

**Comment by DRPozdniakov** [comment]
can you please provide some info how would you implement it. In docs there is not much mentioned. I have created for me the test environment, but now additionally handle there the way you have implemented Dataprovider and informationve_pairs is quite challenging. 
The idea with cust_ values sounds to be quite easy, but it doesnt work the way you have described it in the documentation.

My use case is - to create a Dataframe containing all the labels from the whitelist (let it be 30 values) and update there during the _populate_indicatiors_ action the rate value for actual _metadata['pair']_ , then to calculate based on the 30 current values some overall values and write it into the actual coin dataframe["rate"].
So please, just a few word how would you implement it?

**Comment by DRPozdniakov** [comment]
Ok, i ve got the idea. In documentation you use 2 different variables _cust_info and cust_info to refer to the same one.
