### ISSUE TITLE
PyJWT 2.0.1

### ISSUE THREAD

**Issue by hdkbouma** [freqtrade/freqtrade#4390]
## Describe your environment

  * Operating system: Ubuntu 20.4____
  * Python Version: 3.8.5_____ (`python -V`)
  * CCXT version: 1.40.99_____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.1____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*
during update:
flask-jwt-extended 3.25.0 requires PyJWT<2.0,>=1.6.4, but you have pyjwt 2.0.1 which is incompatible.

**Comment by xmatthias** [comment]
you should remove all flask related dependencies, freqtrade is no longer using flask, but switched to fastapi.

**Comment by hdkbouma** [comment]
from setup.py?
line 22
api = ['flask', 'flask-jwt-extended', 'flask-cors']

**Comment by xmatthias** [comment]
ups :laughing: 

it's not in the requirements, and shouldn't interfere UNLESS you install with `pip install -e .[api]` - or `pip install freqtrade[api]`.

It's gone now, so will be fixed in the next release (although this is not something that's breaking ...).
