### ISSUE TITLE
custom_stoploss/roi/trailing should provide access to the dataframe

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#4392]
I consider this limitation crucial to be improved since it's extremely popular to have algorithms that set the stoploss/roi/trailing based on data from indicators. 
I'm not familiar with the codebase but am I right that in the case of custom_stoploss it would be mainly a matter of changing the function definition?

**Comment by xmatthias** [comment]
roi / trailing are not functions, but settings - the dataframe is not relevant for these, as the strategy can't modify them "on the go" anyway at the moment.

for custom-stoploss it's slightly different, as this is a function.

You can access the dataframe in dry-run / live via [dataprovider](https://www.freqtrade.io/en/latest/strategy-customization/#get_analyzed_dataframepair-timeframe).

This dataframe is however not available during backtesting - and it's also impossible to do so without sacrificing performance of backtesting, as we would have to slice the dataframe once for every candle / pair combination, which would turn a 30s backtest into a 5-20 minute affair (and yes, i did play with this in the past).

**Comment by epigramx** [comment]
By mentioning roi/trailing too I implied that since those are also based on indicators in certain algorithms they could use a custom function.
I understand there are performance issues. I suspect it can become irrelevant by having the impact only when the relevant feature is used.

**Comment by epigramx** [comment]
> we would have to slice the dataframe once for every candle / pair combination

By the way: this sounds that it be mitigated considerably, in the case a strategy only needs it at the moment of opening a position.
The software would not have to take it into account at all for any other moment in the span of the position.

**Comment by xmatthias** [comment]
> By the way: this sounds that it be mitigated considerably, in the case a strategy only needs it at the moment of opening a position.
The software would not have to take it into account at all for any other moment in the span of the position.

custom stoploss is evaluated at each candle for the duration of the position - so if you have a position open for 2 hours on 1m candles, you'd be needing 120 slices of 500 candles each (assuming you'd want to use "some" history to calculate what's needed).

**Comment by epigramx** [comment]
Would it be prohibitive for a 1h chart that runs for a range of one week only? I worry that there is not an option to try it.
If possible let me know how I can test it myself locally.

**Comment by xmatthias** [comment]
To include it in freqtrade we not only have to consider 1h charts for 1 week (which will be a rather pointless backtest in most cases unless it's a VERY active strategy) - but also backtesting 1m charts for a year or more, and multiple pairs.

Feel free to implement and test this in practice if you have the time.

I will not spend my time on this, as it's not going to be applicable (just do the math for the 1m case for 1 year), and is therefore a waste of my time.

The additional limitation will be memory. To reduce memory consumption, all columns except for buy/sell will be removed before doing backtesting (after generating the buy/sell signals).
Keeping all user columns around will heavily increase memory consumption, breaking hyperopt (which is already VERY memory hungry).

**Comment by epigramx** [comment]
Some algorithms may require more local trends or wider timeframes with much fewer data, so I don't see why it can't be an option.
Anyway: before I make a static list of factors for each pair: let me know if it's easily testable/or if it requires extensive hacking.

**Comment by xmatthias** [comment]
as said above, in my opinion this will break hyperopt (completely) and/or  backtesting performance - so i'll not look into this.

I don't think it'll be a one-line change, but never looked how much would need to be changed for this (neither will i do that now).

**Comment by epigramx** [comment]
I guess it would be an extensive hack then so I'll look into manual options and trial and error. Still an idea worth keeping in mind in case you find it of low performance impact for long timeframes or/and short timeranges. Closing the issue to prevent it appearing by default I guess.
