### ISSUE TITLE
How to check if 3 indicators out of 5 are positive

### ISSUE THREAD

**Issue by tobyhage** [freqtrade/freqtrade#4396]
Hello,

I'am not very good at python and don't know how to check if minimal 3 indicators out of 5 are positive.
So in function populate_buy_trend i want to check in code

        dataframe.loc[
            (
// here i want to check if minimal 3 out of 5 indicators are positive
            ),
            'buy'] = 1

How can i do this in Python?

If my question is not clear, please let me know.
Thank you.

Toby.

**Comment by GerhardK90** [comment]
Hello tobyhage, 

"positive" is a very elastic term in this context. 

Let's take a look at an example from the strategy repo (https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/CombinedBinHAndCluc.py). 
The CombinedBinHAndCluc buy strategy combines the two strategies BinHV45 and ClucMay72018. 

The strategies are linked with a logical Or, so either one strategy must apply or the other. 
Within a strategy, several expressions are listed that must be true together (they are linked with a &). 

From combinatorics (binomial coefficient) we know that your plan allows 10 combinations (C(5, 3) = 10). We can also consider the number of these combinations as the number of strategies we want to combine.
Specifically, the following combinations are the ones you want to implement:

```
1,2,3
1,2,4
1,2,5
1,3,4
1,3,5
1,4,5
2,3,4
2,3,5
2,4,5
3,4,5
```

So let's assume that three out of five expressions must be true. We also assume that the indicators to be used have already been populated in the `populate_indicators` function, i.e. they are present in the dataframe.
We simply call the corresponding columns 'ind1', 'ind2', 'ind3', 'ind4' and 'ind5' and these contain boolean values. 

Then a solution to your problem could look like this:

```
dataframe.loc[ 
 (dataframe['ind1'] & dataframe['ind2'] & dataframe['ind3'])
| (dataframe['ind1'] & dataframe['ind2'] & dataframe['ind4'])
| (dataframe['ind1'] & dataframe['ind2'] & dataframe['ind5'])
| (dataframe['ind1'] & dataframe['ind3'] & dataframe['ind4'])
| (dataframe['ind1'] & dataframe['ind3'] & dataframe['ind5'])
| (dataframe['ind1'] & dataframe['ind4'] & dataframe['ind5'])
| (dataframe['ind2'] & dataframe['ind3'] & dataframe['ind4'])
| (dataframe['ind2'] & dataframe['ind3'] & dataframe['ind5'])
| (dataframe['ind2'] & dataframe['ind4'] & dataframe['ind5'])
| (dataframe['ind3'] & dataframe['ind4'] & dataframe['ind5'])
]
```

I don't know what form your indicators have, but I strongly assume that you have to make a comparison and that the indicators are not boolean variables. 
With a fictitious example, the first line could look like this:

`(dataframe['ind1'].lt(42) & dataframe['ind2'].gt(1337) & dataframe['ind3'].ge(421337) )`

You can read more about the operators ge, eq, ne, le, lt, gt here: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.ge.html

Good luck!

**Comment by tobyhage** [comment]
Hello GerhardK90,

Thank you for the quick response. With your two tips:

`
dataframe.loc[ 
 (dataframe['ind1'] & dataframe['ind2'] & dataframe['ind3'])
| (dataframe['ind1'] & dataframe['ind2'] & dataframe['ind4'])
| (dataframe['ind1'] & dataframe['ind2'] & dataframe['ind5'])
| (dataframe['ind1'] & dataframe['ind3'] & dataframe['ind4'])
| (dataframe['ind1'] & dataframe['ind3'] & dataframe['ind5'])
| (dataframe['ind1'] & dataframe['ind4'] & dataframe['ind5'])
| (dataframe['ind2'] & dataframe['ind3'] & dataframe['ind4'])
| (dataframe['ind2'] & dataframe['ind3'] & dataframe['ind5'])
| (dataframe['ind2'] & dataframe['ind4'] & dataframe['ind5'])
| (dataframe['ind3'] & dataframe['ind4'] & dataframe['ind5'])
]
`

and

`
(dataframe['ind1'].lt(42) & dataframe['ind2'].gt(1337) & dataframe['ind3'].ge(421337) )
`

i can make the code i want. Thank you very much!

**Comment by alexcrownjr** [comment]
```
This file provides you with the consensus indicator and all associated helper methods.
The idea is based on the concept that, if you have 1 indicators telling you to buy things are great
if 100 indecators telling you to buy at the same time, things are better.
If we can now have an easily understandalbe score, things should be perfect.
```

https://github.com/freqtrade/technical/blob/master/technical/consensus.py

**Comment by tobyhage** [comment]
interesting. Thank you for the suggestion!
