### ISSUE TITLE
Buy Timeout

### ISSUE THREAD

**Issue by elestranobaron** [freqtrade/freqtrade#4402]
Hello,

Is buy timeout a bug, simply due to slow connection or passed a certain amount ? After that the order is partially abandoned.

Thanks,

**Comment by xmatthias** [comment]
buy timeout can be configured, and defaults to 10 minutes.

if price moves away from your order, then it'll not be filled, and will therefore be cancelled after the timeout.
That's a basic trading principle for limit orders.

**Comment by elestranobaron** [comment]
OK, so is it possible to make some sort of price range ?
In the configuration. because for me, It's ok in the base strategy, buy is made at the right time but, probably because the price moves too fast I often have a timeout.

And another question is when you stop and start the bot, does he have to recount 30 candles before looking for a signal.

Edit : by price range I mean plus or minus 0.1%  or so compared to buy price signal

Thanks for your answer, good job for this app

regards

**Comment by elestranobaron** [comment]
Just took another timeout right now order fully cancelled  and not sure a longer timeout can help ?

**Comment by elestranobaron** [comment]
possibly. it's cause of my poor connection -> must some sorts of pings (latency) on this platforms like some sort of Counterstrikeserver shit
I keep you intouch

**Comment by xmatthias** [comment]
Unfilled orders have nothing to do with connection speeds - but with simple mechanics of how exchanges work.
I would STRONGLY suggest do do some research how orders on exchanges work and are filled, to gain an understanding of this in general.



You can do many things with the price by simply [reading the documentation](https://www.freqtrade.io/en/latest/configuration/#prices-used-for-orders).

by default, a buy order is placed at the best bid orderbook spot as limit order - so if it starts to raise immediately (which suggests a good buy signal) - your price will not be reached again - so it'll remain unfilled.
you can counter this by using the best ask value for price instead (with the downside of paying spread).

**Comment by elestranobaron** [comment]
What i noticed is that, mostly, the more stock you need to buy, because the price is low, the more chances it has to happen.

In relation with law of offer and demand: But, after that, if you expect a 1% revenue for a 0.15% spread, that's still ok.

So, Great recommandation.

**Comment by xmatthias** [comment]
> In relation with law of offer and demand: But, after that, if you expect a 1% revenue for a 0.15% spread, that's still ok.

yes it is - but you need to be aware of it anyway - as it CAN eat your profits away if you're running a barely profitable strategy.

**Comment by elestranobaron** [comment]
just one more question because I Can put last balance to 1 for buy option, but whats the équivalent for selling ?
Is the configuration below the way to put best ask price and best selling ? (Because I got timeout in selling too .. .)
also what is the difference with order book ? 

What i did: in config:

ask last balance still at 0 but use_order book at true for bask and bif (because put it at 1 did not change nothing)

In strategy, uncomment the part:

if self.dp:
    if self.dp.runmode in ('live', 'dryrun'):
        ob = self.dp.orderbood(metadata['pair'], 1)
        dataframe['best_bid'] = ob['bids'][0][0]
        dataframe['best_ask'] = ob['asks'][0][0]

**Comment by xmatthias** [comment]
that option doesn't exist for selling yet.

orderbook simply uses the orderbook endpoint - it's more a technical difference than one from the values (althoug some claim orderbook endpoints update faster than ticker endpoints ...)

**Comment by elestranobaron** [comment]
Ok,
So i'd like an advice on my buy config, because i still have buy timeout for example now at 29.47 euros on REP although i saw price did'nt move. It was the same. 

The only part i changed in strategy file is that part above i uncommented: dp.orderbood: is that good ? 
**Edit2: I also commented again the dataprovider part in the strategy file. Only the config file is changed.**
and in config.json i went back to order_book as false but what else can i do to modify price range at ticker level as you do:
**Edit: For let's say a range at +1 or -1% on cryptocurrencies, like from 29.30 to 29.70 in this REP example.**
"bid_strategy": {
"price_side": "bid,"
"use_order_book": false,
"ask_last_balance": 0.0,
"order_book_top": 1,
"check_depth_of_market": {
"enabled": false,
"bids_to_ask_delta": 1
}
},
"ask_strategy": {
"price_side": "ask",
"use_order_book": false,
"order_book_min": 1,
"order_book_max": 1,
"use_sell_signal": true,
"sell_profit_only": false,
"ignore_roi_if_buy_signal": false
}

Thx alot

**Comment by elestranobaron** [comment]
> you can counter this by using the best ask value for price instead (with the downside of paying spread).

In fact i don't know where to modify this best asking value for price ?

**Comment by elestranobaron** [comment]
> that option doesn't exist for selling yet.
> 
> orderbook simply uses the orderbook endpoint - it's more a technical difference than one from the values (althoug some claim orderbook endpoints update faster than ticker endpoints ...)


I think i'm starting to getting it . Which part can i make suggestions for selling counter balance pricing ? Thanks

**Comment by xmatthias** [comment]
Please read the documentation about [pricing](https://www.freqtrade.io/en/latest/configuration/#prices-used-for-orders) until you understand it.

There's multiple options - which one works / doesn't work  for your particular strategy you must find out yourself.

**Comment by elestranobaron** [comment]
Thank you
