### ISSUE TITLE
Request: latest FreqUI that includes the "reason sold" column on closed orders

### ISSUE THREAD

**Issue by jbishop129** [freqtrade/freqtrade#4406]
FreqUI native integration on the latest :develop branch is awesome, and cuts out all the CORS headaches of running it separately, thank you for this! I was hoping the `sell_reason` column (I believe that's the column name) which is visible in the latest standalone FreqUI could also be included in the built-in FreqUI. It's visible in the logs when you see a sell go through. I find this data point incredibly important when analyzing trade history, to know if a trade was closed because of stoploss, trailing stoploss, roi, etc.
 FWIW, I am running the latest docker image `freqtradeorg/freqtrade:develop`, but I have also tried building my own from source. Either way is fine with me, I just dont know how the FreqUI code was rolled in to the repo, so I dont want to go messing around in there!

Edit: get the name of the actual column right 😂

**Comment by xmatthias** [comment]
it's always downloading the latest release from frequi.

I'll try to do a release on frequi soon - then it'll just be a question of updating the image / running `freqtrade install-ui` once more to get the atest version.

**Comment by jbishop129** [comment]
Confirmed the Close Reason column now shows, in the recently pushed `:develop` image. Thanks!
