### ISSUE TITLE
Get token's underlying asset as informative pair

### ISSUE THREAD

**Issue by mayipainther** [freqtrade/freqtrade#4407]
Hi,

first: Thank you so much for this great project! 

I came across an issue, for which I didn't find the solution for myself nor here or in the doc: When I'm using leveraged tokens as traded pairs (e.g. BTCUP/USDT) and therefore want to track the underlying asset (in this case BTC/USDT) - how to implement that? I got underlying assets listed as informative pairs inside the strategy, but when using the code below, freqtrade obviously is looking for .*UP/USDT data to cache, because that's what `metadata['pair']` means by then...

`informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf)`

So, how to achieve here to take the dataframe of the underlying asset? I'm somehow stuck.

Thanks in advance! Have a great weekend!

**Comment by xmatthias** [comment]
i guess in theory you can try to somehow parse out the UP / DOWN with a regex (or search and replace).

I'm not sure it'll work in all cases (maybe a token is called "UPS" - so "UPSUP/USDT" would only leave "S/USDT" ).
Will depend on the pairs available though ...

**Comment by mayipainther** [comment]
Tried hard with regex yesterday and then only got attribute-hash-mutable-...problems. But because you'd do it the same way, I tried again and got it now: I use DataProvider to get the market data and then use its base key. So I can simply remove the last two letters (or 4 letters when using .*DOWN/...). Voilà. 

```
market = self.dp.market(metadata['pair'])
dataframe.base = market['base']
informative = self.dp.get_pair_dataframe(pair=f"{dataframe.base[:-2]}/USDT", timeframe=inf_tf_m)
```

**Comment by xmatthias** [comment]
using `[:-2]` will only work for UP markets, not for DOWN markets.

In the end, what you're working with is a string, so simple replace methods will work ...

most likely a better way:

```python
pair = metadata['pair']
pair_base = pair.replace('UP', '').replace('DOWN', '')

# Do whatever you want with the pair base
```

**Comment by mayipainther** [comment]
I'm using only one direction in the strategy, so that's fine. Nevertheless using yours now, because it's much better. Thx!
