### ISSUE TITLE
Download data incomplete (Binance)

### ISSUE THREAD

**Issue by OtenMoten** [freqtrade/freqtrade#4411]
## Describe your environment

  * Operating system: `Ubuntu 20.05 LTS focal`
  * Python Version: `3.8.5`
  * Docker Version: `20.10.3`
  * Freqtrade Version: `freqtrade latest`
  * Freqtrade Plot Version: `freqtradeorg/freqtrade develop_plot`
 
## Download data incomplete

Hello dear community,

since approx. two weeks I face the issue that my downloaded data from exchanges is incomplete. I discovered the missing data if I create a plot of a backtest. I wondered why the backtest did less trades, then I saw the flat lines on the plot.

![image](https://user-images.githubusercontent.com/32872932/108622385-c3637d80-7438-11eb-8ed9-3b7e524e2734.png)

### Steps to reproduce:

  1. Download data from Binance with this command:
`sudo docker run -d --name DL-SwingHighToSky -v ~/.freqtrade/configs/conf-ho-swing-high-to- 
 sky.json:/freqtrade/config.json -v ~/.freqtrade/user_data/:/freqtrade/user_data/ freqtrade download-data -t 30m -- 
 timerange=20210101-`
You can download the Binance data that was downloaded with the command above here: https://mega.nz/file/CBsgASYS#566oLJEKZCpEEQQKmIRJzwHnHSi37Zj5lA9luQlOdGM 

  2. Do a backtest to generate a backtest result file with this command: 
`
sudo docker run -d --name BT-SwingHighToSky -v ~/.freqtrade/configs/conf-ho-swing-high-to-sky.json:/freqtrade/config.json -v ~/.freqtrade/user_data/:/freqtrade/user_data/ freqtrade backtesting --strategy SwingHighToSky --fee 0.001 --dmmp --export trades --export-filename=user_data/backtest_results/backtest-result.json --timerange=20210101-`
In my case the result-file is `backtest-result-2021-02-21_10-18-56.json`.
You can download it here: https://mega.nz/file/GJsmVKCT#GiZcKXUC8_PnJmUMukFCFfHFEWmJpXGbN17CdQsWNRs

  3. Finally I plotted the frame at the top of this thread with this command:
`sudo docker run -d --name PLOT-SwingHighToSky -v ~/.freqtrade/configs/conf-ho-swing-high-to-sky.json:/freqtrade/config.json -v ~/.freqtrade/user_data/:/freqtrade/user_data/ freqtradeorg/freqtrade:develop_plot plot-dataframe --strategy SwingHighToSky -p BTC/USDT --timerange=20210101- --indicators2 macd cci`
The source link to the plot on the top of this thread is: https://i.ibb.co/x38j0np/freqtrade-plot.jpg
  
### Observed Results:

  * As you can see the flatten lines on the price chart as well as on the indicators there is no opportunity for a trade because the buy and sell signales are not triggered during these flatten periods.
  
  * I expect price movement on this periods.
  
  * Did anybody experienced this issue?

### Relevant files

`conf-ho-swing-high-to-sky.json`
```
{
    "max_open_trades": 1,
    "stake_currency": "USDT",
    "stake_amount": 900,
    "dry_run_wallet" : 1000,
    "fiat_display_currency": "USD",
    "timeframe": "30m",
    "dry_run": true,
    "cancel_open_orders_on_exit": true,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 5
    },
    "bid_strategy": {
	"price_side": "ask",
        "use_order_book": true,
        "ask_last_balance": 0.0,
        "order_book_top": 1
    },
    "ask_strategy": {
	"price_side": "bid",
        "use_order_book": true,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
    "order_types": {
        "buy": "limit",
        "sell": "limit",
        "emergencysell": "market",
        "stoploss": "market",
        "stoploss_on_exchange": false,
        "stoploss_on_exchange_interval": 30
    },
    "exchange": {
        "name": "binance",
        "key": "...",
        "secret": "...",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 500
        },
        "pair_whitelist": [
            "BTC/USDT"   
        ]
    },
    "pairlists": [
        {"method": "StaticPairList"}
    ],
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5,
        "heartbeat_interval": 60
    },
    "disable_dataframe_checks": false,
    "dataformat_ohlcv": "json",
    "dataformat_trades": "jsongz"
}
```

`Swing-High-To-Sky.py`
```
# --- Do not remove these libs ---
from freqtrade.strategy.interface import IStrategy
from typing import Dict, List
from functools import reduce
from pandas import DataFrame
# --------------------------------

import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib
import numpy # noqa

__author__      = "Kevin Ossenbrück"
__copyright__   = "Free For Use"
__credits__     = ["Bloom Trading, Mohsen Hassan"]
__license__     = "MIT"
__version__     = "1.0"
__maintainer__  = "Kevin Ossenbrück"
__email__       = "kevin.ossenbrueck@pm.de"
__status__      = "Live"

class_name = 'SwingHighToSky'
class SwingHighToSky(IStrategy):

    # Disable ROI
    minimal_roi = {
         "0":  100
    }

    stoploss = -0.50

    ticker_interval = '30m'

    def informative_pairs(self):
        return []

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        dataframe['macdhist'] = macd['macdhist']
        
        dataframe['cci'] = ta.CCI(dataframe)

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        dataframe.loc[
            (
                (dataframe['macd'] > dataframe['macdsignal']) &
                (dataframe['cci'] <= -100.0)
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        dataframe.loc[
            ( 
                (dataframe['macd'] < dataframe['macdsignal']) & (dataframe['cci'] >= 200.0)
            ),
            'sell'] = 1
            
        return dataframe
```

### Relevant code exceptions or logs

_There was no error in the docker containers while downloading the data, executing the backtest and even not whilst plotting the chart._

**Comment by OtenMoten** [comment]
_PS: I also face this issue with ETH/USDT and XRP/USDT at the same timeperiod._ 

_PSPS: I downloaded explicit the flatten timeperiods and it works. On the picture above you can see that from January 12 to Januar 17 is no data. I downloaded from 12th to 17th, did backtest and printed the chart without flatten lines._

_It's not Binance as it seems. Does the flatten lines origins from plotting or from backtest? Hmmmmnn  ...._

### **PSPSPS: I can confirm now that the problem is the backtest. I tested two timeperiods A) from 1st Jan to 15th Jan and B) from 15th Jan to 1st Feb. If I backtest and plot timeperiod (A) and (B) explicit then everything works as expected. If I do a backtest from 1st Jan to 1st Feb then the result is the same as mentioned above in the issue.**

**Comment by xmatthias** [comment]
make sure to delete the existing data, and download it again with a recent version.

The problem was in ccxt, and was fixed ~2-3 weeks ago (i can look for the issue if you need it - but usually it's enough that it's solved now).

unfortunately, it'll impact the downloaded data, so you can either try and remove the "broken" data-segments manually, or remove all affected data and download it again (on binance, removing all is most likely faster).

**Comment by OtenMoten** [comment]
Worked for me. 

Thank you very much!
