### ISSUE TITLE
Problem with _pi docker image, No module named import lib_metadata

### ISSUE THREAD

**Issue by rkhaled0** [freqtrade/freqtrade#4414]
## Describe your environment

  * Operating system: `Ubuntu 20.10`
  * Python Version: `Python 3.7.9`
  * CCXT version: `ccxt==1.40.99`
  * Freqtrade Version: `freqtrade 2021.1`
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Freqtrade bot failed to start.

I'm using docker image `freqtradeorg/freqtrade:2021.1_pi`.

I notice that the python version differs between `Dockerfile` & `Dockerfile.armhf` docker files. Is expected or a mistake ?

I think that python version used as base image into `Dockerfile.armhf` docker file should be bumped.

With `freqtradeorg/freqtrade:2020.11_pi` docker image, everything is ok. freqtrade bot started successfully.

### Steps to reproduce:

  1. Try to docker run a new container with `freqtradeorg/freqtrade:2021.1_pi` img
  2. See logs
  3. container has crashed

### Observed Results:

  * What happened?

container crashed.

  * What did you expect to happen?

container in running state.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
Traceback (most recent call last):
  File "/usr/local/bin/freqtrade", line 10, in <module>
    from importlib.metadata import distribution
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/freqtrade", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/freqtrade", line 15, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3242, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'blosc' distribution was not found and is required by freqtrade
  ```

**Comment by xmatthias** [comment]
The version for the image of the raspberry cannot be bumped.
We're using piwheels.org for this, which is only building for 3.7 at the moment.

Without being able to use these wheels, building the image via CI is impossible as it will take between 6 and 10 hours (it times out after 6 - but I've build it locally in about 10 hours in the past).

Are you sure you're on a raspberry? 
your OS (ubuntu 20.10) indicates that you're not on a raspberry, but on a regular linux machine with Ubuntu installed - in which case you should be using the regular (non `*_pi`) image.

Either way, I've just successfully pulled and started the image you point out (`2021.1_pi`) on a raspberry without problems.

**Comment by rkhaled0** [comment]
@xmatthias , thank you for yours explanations.

I'm on raspberry arm64 model 4, more precisely a microk8s cluster.

Really ? On my side, the container cannot started successfully :( .

Be advised that I've no issue with `2020.11_pi` version.

**Comment by xmatthias** [comment]
We didn't test arm64 (nor do we support this at the moment, as the dependency compatibility is simply not there).

You'll see that on a regular ARM, it'll work just fine.

**Comment by rkhaled0** [comment]
Exact, that's why I've this following warning message

```
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Will you plan support for arm64 ? I think that it would be relevable because of raspberry model 4 architecture.

I can contribute to achieve this goal.

**Comment by xmatthias** [comment]
sometime in the future, potentially yes.

It'll however not happen until [piwheels.org](https://www.piwheels.org/) supports it as well (builds wheels for arm64) - otherwise i see the "dependency support" as not given, and compiling everything from source will take too long and will therefore time out CI.
It's the same than with upgrading the docker-image to python.3.8/3.9 - which is also tied to piwheels.

From their homepage:
> Wheels provided support all Raspberry Pi models (Pi 4, Pi 3, Pi 2, Pi 1 and Pi Zero). Wheels are provided for Raspbian Jessie (Python 3.4), Raspbian Stretch (Python 3.5) and Raspberry Pi OS / Raspbian Buster (Python 3.7) — though currently only the 32-bit OS is supported, not 64-bit.

**Comment by rkhaled0** [comment]
Potentially, for the arm64 platform, I think that it's not necessary to use piwheel.

Because most freqtrade dependencies already have wheel for any or specific arm64 architecture, except some dependencies (at this moment) -> sdist -> increase time of building docker image as you said.

So, I've used `docker manifest` to create a multi platform freqtrade docker image.
You can find my repository on Docker hub [here](https://hub.docker.com/repository/docker/flucky/freqtrade)

Do you think that it would be more efficient to do that (multi platform image) ?

**Comment by xmatthias** [comment]
if you do a multiplatform build or not is not the point, in theory you can have different files for each image.

What's the build time building the arm64 image when using docker buildx and cross-building it (without cache) on a x64 machine?

**Comment by rkhaled0** [comment]
When using `docker buildx`, I think that you need to have a single `Dockerfile`. That's why I've used `docker manifest`.

Additionally, it took almost 37min to build the arm64 image without cache.

Be advised that I've overwrite  the `config.guess` file  containing into Ta-lib archiv in order to use a more recent version.
