### ISSUE TITLE
Buy Intra Candle

### ISSUE THREAD

**Issue by ntzazz** [freqtrade/freqtrade#4425]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.8
  * CCXT version: 1.40.99
  * Freqtrade Version: develop-bc586fe7
  
## Your question

I have a certain strategy which should trigger BUY intra candle. However, during dry run, I have noticed that BUY signals are only getting process at Open price of new Candle. I tried using "process_only_new_candles" = false, however it didn't worked. Is there a way that I can enable the Intra candle BUY?

Regards
Nimit

**Comment by xmatthias** [comment]
by default, freqtrade will buy whenever the signal "flips" from your strategy / whenever a trade-slot becomes available.

While you can prevent this with `ignore_buying_expired_candle_after` - i assume you're not using this.

`process_only_new_candles` will control if your `indicator_*()` methods are called once per candle or multiple times - however candles will not change throughout the candle.

freqtrade provides you with complete candles only, so no signal will "appear" after 50% of a candle unless you use some real-time information (usually orderbook or something simliar).
Everything else (using close / high / low) before the candle is closed will lead to repainting - as the signals will still change throughout the candle.

**Comment by ntzazz** [comment]
So does this mean there is no way I can buy within a candle using Open/high/low?

Is there a way we can know the current market price in our strategy?

**Comment by xmatthias** [comment]
As said, freqtrade does not provide you incomplete candles to avoid repainting.

Please use the [documentation - deep link dataprovider methods](https://www.freqtrade.io/en/latest/strategy-customization/#orderbookpair-maximum) - it's there for a reason.
