### ISSUE TITLE
webhook from tradingview

### ISSUE THREAD

**Issue by yaotian** [freqtrade/freqtrade#4432]
I have already implemented a strategy in tradingview.
Tradingview supports webhook to send sell/buy commands.

Q:
How to use tradingview webhook to send commands to my freqtrade?

**Comment by xmatthias** [comment]
This is a duplicate of #2644.

While the original issue itself is old - the arguments listed there are still valid, especially the onces around security and about alignment (a strategy working on tradingview might make different assumptions about price-movements, so roi / stoploss will be different than reality).

in short - it's not possible, and it's also not planned to implement.
