### ISSUE TITLE
Docker: "Failed to kill subprocesses on this platform"

### ISSUE THREAD

**Issue by mpicard** [freqtrade/freqtrade#4435]
## Describe your environment

  * Operating system: MacOS Catalina 10.15.7 12 cores 16GB
  * Python Version: N/A Python 3.9.2 (but using only official docker)
  * CCXT version: N/A only using docker
  * Freqtrade Version: freqtrade 2021.1
  
## Describe the problem:

When running hyperopt in docker, using the provided docker-compose.yml on the stable branch v2021.1, it crashes often when getting into 100+ epochs range. Docker is configured to 12 cores, 8GB Memory, 1GB swap  

### Steps to reproduce:

  1. follow instructions to run hyperopt in docker using provided docker-compose 
  2. using 2021.1 stable image
  3. `	docker-compose run --rm freqtrade hyperopt \
		--config user_data/config.json \
		--hyperopt EmptyHyperopt \
		--hyperopt-loss SharpeHyperOptLossDaily \
		--spaces roi stoploss trailing \
		--strategy CourseStrategy \
		--timerange 20200101- \
		--stake-amount 0.02 \
		--job-workers 8 \
		--epochs 250`
  
### Observed Results:

  * What happened? It crashed 
  * What did you expect to happen? It would finish running hyperopt for all 250 epochs OR *at least print the best result, instead of losing the best effort, which is just a waste of time and resources because I have to start over again*

### Relevant code exceptions or logs

```
/root/.local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/root/.local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/root/.local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/root/.local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/root/.local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/root/.local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/root/.local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
/root/.local/lib/python3.8/site-packages/joblib/externals/loky/backend/utils.py:55: UserWarning: Failed to kill subprocesses on this platform. Pleaseinstall psutil: https://github.com/giampaolo/psutil
  warnings.warn("Failed to kill subprocesses on this platform. Please"
 [Epoch 864 of 10000 (  8%)] |███████\                                                                                   | [ETA:   6:38:28, Elapsed Time: 0:37:41]
2021-02-24 07:48:42,172 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 83, in start_hyperopt
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 716, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 620, in run_optimizer_parallel
    return parallel(delayed(
  File "/root/.local/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/root/.local/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/root/.local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}
make: *** [hyperopt] Error 1
```

**Comment by xmatthias** [comment]
In the end, the Warnings are just warnings about not beeing able to kill a process.

While that's easily fixable, the real reason is this:
`This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.`

It's ran out of memory - which can easily happen with hyperopt depending on the amount of pairs / timerange.
Try reducing either the timerange or number of pairs, or number of parallelity (which will also reduce the memory requirements)  - and it should work.
While i think we can fix the warnings (failed to kill process) - the out of memory will remain.

**Comment by xmatthias** [comment]
I'll close this as this error shouldn't appear anymore with 262394e ... (however it's just fixing the error itself, not the fact fact your system runs out of memory).

**Comment by mpicard** [comment]
Ah okay thanks for looking in to it, I started using freqtrade outside the
container in the host which works better for me, as there is more memory
available.
