### ISSUE TITLE
Dry run trade doesn't produce transactions

### ISSUE THREAD

**Issue by flavienbwk** [freqtrade/freqtrade#4437]
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Freqtrade Version: 2021.2 (Docker, ":last" image) 
  
## Your question

Hello, I'm testing Freqtrade and encounter an issue when I enable dry run : no transaction are produced.

The program informs me that the worker "heartbeats" but nothing is inserted in the sqlite database.

I've let the program run for 6 hours and I am using the "Low_BB" strategy. 

Where could the problem come from?

Thank you.

**Comment by xmatthias** [comment]
This is covered by this [FAQ point](https://www.freqtrade.io/en/latest/faq/#i-have-waited-5-minutes-why-hasnt-the-bot-made-any-trades-yet).

If you only see the heartbeat, then the strategy didn't generate a buy signal, so the bot does not buy.

**Comment by flavienbwk** [comment]
Thanks, that was it. I've tried another strategy, let it run a bit longer and it works.
