### ISSUE TITLE
Minimal ROI - "in effect after X minutes"?

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4438]
What does it mean "in effect after X minutes"?

For example, if 2% profit is reached after 19 minutes, freqtrade will not sell? It will wait for at least a 2% profit **after** 20 minutes?

Also, what happens when 3% profit is reached in 39 minutes? It won't sell?

![Greenshot 2021-02-25 10 01 40](https://user-images.githubusercontent.com/528302/109122082-c0c29a00-7750-11eb-98f7-f9ab644386d5.png)

I just want a minimum of 1% profit whenever that comes. I assume this is enough?

```
    minimal_roi = {
        "0":  0.01
    }
```

**Comment by xmatthias** [comment]
Yes, this will be enough.

The example above does show a declining ROI - so it's 4% whenever, 2% after 20 minutes, and 1% after 30 minutes.

Now technically, it'll also sell with 5% after 50 minutes (anything greater than 30 minutes, really) - but it's unlikely to reach 5% as the bot will sell once it reaches 1% profit (is above 1% profit) - which can be exactly 1%, 1.5%, 2%, or more (but as it sells as soon as it's above - you'll probably not reach 5% profits.

**Comment by aristosv** [comment]
thank you
