### ISSUE TITLE
Plotting error

### ISSUE THREAD

**Issue by ilyassbc** [freqtrade/freqtrade#4440]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.8.5
  * ccxt==1.42.19
  * Freqtrade Version: freqtrade develop-1f30c3d

## Your question
  
 Hi, when I run a backtest and try to plot using this command: `freqtrade plot-dataframe -s Strategy002` . I get this error message : `freqtrade - ERROR - Directory '/home/ilyassbc/freqtrade/user_data/backtest_results' does not seem to contain backtest statistics yet.` . How do I solve that?

**Comment by OtenMoten** [comment]
Did you run a backtest before try to plot?

**Comment by ilyassbc** [comment]
> Did you run a backtest before try to plot?

Yes, I did

**Comment by xmatthias** [comment]
did you include `--export trades` while running your backtest? otherwise results are not stored - and are therefore also not available for plotting.

**Comment by OtenMoten** [comment]
If you run in docker try this:

`sudo docker run -d --name BT-SwingHighToSky -v ~/.freqtrade/configs/conf-ho-swing-high-to-sky.json:/freqtrade/config.json -v ~/.freqtrade/user_data/:/freqtrade/user_data/ freqtrade backtesting --strategy SwingHighToSky --fee 0.001 --export trades --export-filename=user_data/backtest_results/backtest-result.json --timerange=20210101-`

**Comment by ilyassbc** [comment]
I didn't know that I should run the command `--export trades`. You've both resolved the issue. Thank you.
