### ISSUE TITLE
No currency pair in active pair whitelist : bot is stuck ?

### ISSUE THREAD

**Issue by flavienbwk** [freqtrade/freqtrade#4442]
## Describe your environment

* Operating system: Ubuntu 18.04
* Freqtrade Version: 2021.2 (Docker, ":last" image)
  
## Your question

Hi, I am trying freqtrade and running it for a day now. But it seems like the bot is unable to sell. **Buying works correctly however**.

The bot keeps saying : 

```
freqtrade.freqtradebot - INFO - No currency pair in active pair whitelist, but checking to sell open trades.
```

What does that mean ?

Thank you.

**Comment by xmatthias** [comment]
You should really backtest the strategy you run, to know how it'll behave.

You'll get the empty pairlist warning if you have 1 trade open, and only one pair in the whitelist.

Not all strategies will buy / sell multiple times per day, some hold trades for days or weeks.
It's your strategy you're running, so it's your responsibility to know which sell-signals you'd expect, be that stoploss (maybe the pair is going down, and you're using a very wide stoploss), roi (maybe that's set high, not reached yet?), or sell-signal (this condition might not have been met yet).

Using dry-run without backtesting first is clearly not recommended.
