### ISSUE TITLE
detect BTC value - invest 100 USD

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4447]
I want to trade in BTC pairs but I want each trade to invest 100 USD, which today is around 0.0022 BTC. The problem is that the BTC value keeps changing so I will have to keep adjusting the stake_amount value.

Is there a way for freqtrade to check the current BTC value, and invest 100 USD, in BTC? I also want the max_open_trades value to be -1 so all the portfolio is used.

I did check the dynamic stake amount configuration but that will depend on the portfolio value, which will also keep changing with each trade.

**Comment by xmatthias** [comment]
I'm not quite sure what you're trying to do...

What's your stake-currency? BTC or USD?

If it's USD, then you can simply use 100 as stake-currency, and the bot will use that in whatever many chunks to use the full wallet.

If your stake its BTC,  then you need to configure the investment amount in BTC - so 0.0022 BTC (or whatever else).
That's however a static value, and using a remote currency to calculate this is not possible at the moment.

It may become possible for the strategy to control stake amount, so you can do this configuration yourself with #3886 - that PR is still a draft, and is currently not seeing much progress, so it'll probably still take a while until that's possible.

---

The main problem with using BTC pairs is the instability of BTC itself, so even if your bot is +20% in BTC - you might be down in FIAT, as BTC took a 30% dive.
With the method above, you can't really counter this either...

**Comment by aristosv** [comment]
> If your stake its BTC, then you need to configure the investment amount in BTC - so 0.0022 BTC (or whatever else).
That's however a static value, and using a remote currency to calculate this is not possible at the moment.

This answered my question. Thanks

**Comment by aristosv** [comment]
Just as an FYI, with my limited bash knowledge, I created this script that will update the BTC stake_amount to the equivalent of $100. A simple cron job can run this on specified intervals.

My only concern is the interruption of freqtrade while it's doing something.

```
#!/bin/bash

echo get BTC price
btc_value=$(curl -s https://api.binance.com/api/v1/ticker/price?symbol=BTCUSDT | jq '.price|tonumber|floor')

echo get equivalent 100 dollar price
usdt_value=$(awk -v var1=3 -v var2=4 "BEGIN { print  ( 100 / $btc_value ) }")

echo modify freqtrade configuration
sed -i -e "/stake_amount/c \    \"stake_amount\": $usdt_value," /root/freqtrade_test/config.json

echo restart freqtrade
systemctl restart freqtrade
```

**Comment by sanitariu** [comment]
I think you just need to reload the config file like in telegram. No need to restart all.

**Comment by aristosv** [comment]
Can I reload the config from the terminal? Or do I have to do it from telegram?

**Comment by sanitariu** [comment]
FAQ says this ->
I’d like to make changes to the config. Can I do that without having to kill the bot?

Yes. You can edit your config and use the /reload_config command to reload the configuration. The bot will stop, reload the configuration and strategy and will restart with the new configuration and strategy.

**Comment by aristosv** [comment]
/reload_config runs from telegram though. I dont know if it can run from the bash script itself.
