### ISSUE TITLE
 Unable to initialize markets - Binance 

### ISSUE THREAD

**Issue by viktors1982** [freqtrade/freqtrade#4448]
* Operating system: Ubuntu 20.10  (rasspbery pi 3)
  * Freqtrade Version:  2021.2
  * CCXT: 1.42.19
  * Both pi docker images:  freqtradeorg/freqtrade:develop_pi and freqtradeorg/freqtrade:stable_pi

 Get error after starting docker USDT stake (trying to BTC stake same error) :

WARNING - Unable to initialize markets. Reason: binance GET https://api.binance.com/api/v3/exchangeInfo
 freqtrade.commands.trade_commands - ERROR - USDT is not available as stake on Binance. Available currencies are:
 freqtrade.commands.trade_commands - ERROR - Fatal exception!

from console i'm get exchangeInfo file:

ubuntu@ubuntu:~/ft_userdata$ wget https://api.binance.com/api/v3/exchangeInfo
--2021-02-26 16:04:41--  https://api.binance.com/api/v3/exchangeInfo
Resolving api.binance.com (api.binance.com)... 52.84.150.39
Connecting to api.binance.com (api.binance.com)|52.84.150.39|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1442769 (1.4M) [application/json]
Saving to: ‘exchangeInfo’

On Windows 10 wsl2 freqtrade working great, big tnx for your work!!!

**Comment by bozzfozz** [comment]
For me too, I was wondering why nothing happened for hours

**Comment by xmatthias** [comment]
Interrestingly, this works perfectly fine for me with the 2021.2 image on a raspberry (as well as on my regular pc) (tried with ETH - but that's not the point, as it didn't get any currency).

I'd assume it'll be location based, and binance has some problems only in certain regions (or maybe they're over now ...).

**Comment by viktors1982** [comment]
After reflash Ubuntu on raspberry. Now working fine. Tnx.
