### ISSUE TITLE
Ignore the sell signal before buying or during the buy signal. 

### ISSUE THREAD

**Issue by Superior18** [freqtrade/freqtrade#4451]
Hello.
I want to configure Freqtrade so that when the buy signal arrives ignore the sell signal and wait for the sell signal in the future candlesticks after the buying.
For example, I want to buy when the EMA14 is above the closing price and the EMA50 is below the closing price, and I want to sell only when the EMA30 is above the closing price.
But at the time of buy, if the EMA30 was above the closing price, the buy should be made and wait for the EMA30 changes in future candlesticks. 
It may be necessary to define an option called `ignore_sell_signal_before(when)_buying` .
Do you have an idea?

**Comment by xmatthias** [comment]
your approach will definitely not work for backtesting - and is also problematic for live-runs (depending on the duration of your trades).

During backtesting - all signals are generated up-front (without knowing if a trade entered or not) - so relying on the entry will not be possible to generate the exit.

While you can (probably) somehow forwardshift the latest buy signal, you can't be sure if that signal was acted on - nor if it was really the buy signal, or if you've already been in that trade at that point.

In theory, you can use [storing information](https://www.freqtrade.io/en/latest/strategy-customization/#storing-information) in combination with [entry confirmations](https://www.freqtrade.io/en/latest/strategy-advanced/#trade-entry-buy-order-confirmation) to store this info - however it'll only really work in live / dry run modes - and not in backtesting.
