### ISSUE TITLE
hyperopt for protections

### ISSUE THREAD

**Issue by squat0001** [freqtrade/freqtrade#4458]
to find protections params is not easy.. i played a bit with the code.. to add a protection space is easy.
so .. questions:
- would it better.. to add many protections spaces, for each protetction, i would find it nicely if each protection class has the parameters included for hyperopt
- is it okay to alter the config of protections like in the patch..

?

```
Index: freqtrade/plugins/protections/iprotection.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/freqtrade/plugins/protections/iprotection.py b/freqtrade/plugins/protections/iprotection.py
--- a/freqtrade/plugins/protections/iprotection.py	(revision 64a2897d64c75176ab68685a912d5d586228cb12)
+++ b/freqtrade/plugins/protections/iprotection.py	(date 1614464052268)
@@ -38,7 +38,7 @@
         else:
             self._lookback_period_candles = None
             self._lookback_period = protection_config.get('lookback_period', 60)
-
+        print(self._protection_config)
         LoggingMixin.__init__(self, logger)
 
     @property
Index: freqtrade/optimize/hyperopt.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/freqtrade/optimize/hyperopt.py b/freqtrade/optimize/hyperopt.py
--- a/freqtrade/optimize/hyperopt.py	(revision 64a2897d64c75176ab68685a912d5d586228cb12)
+++ b/freqtrade/optimize/hyperopt.py	(date 1614463943213)
@@ -36,7 +36,7 @@
 from freqtrade.optimize.hyperopt_loss_interface import IHyperOptLoss  # noqa: F401
 from freqtrade.resolvers.hyperopt_resolver import HyperOptLossResolver, HyperOptResolver
 from freqtrade.strategy import IStrategy
-
+from freqtrade.plugins.protectionmanager import ProtectionManager
 
 # Suppress scikit-learn FutureWarnings from skopt
 with warnings.catch_warnings():
@@ -195,6 +195,9 @@
         if self.has_space('trailing'):
             result['trailing'] = self.custom_hyperopt.generate_trailing_params(params)
 
+        # if self.has_space('protections'):
+        #     result['protections'] = self.custom_hyperopt.generate_protections_params(params)
+
         return result
 
     @staticmethod
@@ -497,6 +500,10 @@
             logger.debug("Hyperopt has 'trailing' space")
             spaces += self.custom_hyperopt.trailing_space()
 
+        if space == 'protections' or (space is None and self.has_space('protections')):
+            logger.debug("Hyperopt has 'protections' space")
+            spaces += self.custom_hyperopt.protections_space()
+
         return spaces
 
     def generate_optimizer(self, raw_params: List[Any], iteration=None) -> Dict:
@@ -531,6 +538,22 @@
             self.backtesting.strategy.trailing_only_offset_is_reached = \
                 d['trailing_only_offset_is_reached']
 
+        if self.has_space('protections'):
+            protections_orig = self.config['protections'].copy()
+            protections = []
+            for p in protections_orig:
+                if p['method'] == 'MaxDrawdown':
+                    p['lookback_period_candles'] =  int(params_dict['lookback_period_candles'])
+                    p['trade_limit'] = int(params_dict['trade_limit'])
+                    p['stop_duration_candles'] = int(params_dict['stop_duration_candles'])
+                    #p['only_per_pair'] = params_dict['only_per_pair']
+                    p['max_allowed_drawdown'] = params_dict['max_allowed_drawdown']
+                    print(p)
+                protections.append(p)
+            self.config['protections'] = protections
+            self.backtesting.config['protections'] = protections
+            self.backtesting.protections = ProtectionManager(self.config)
+
         processed = load(self.data_pickle_file)
 
         min_date, max_date = get_timerange(processed)
Index: freqtrade/commands/cli_options.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/freqtrade/commands/cli_options.py b/freqtrade/commands/cli_options.py
--- a/freqtrade/commands/cli_options.py	(revision 64a2897d64c75176ab68685a912d5d586228cb12)
+++ b/freqtrade/commands/cli_options.py	(date 1614457835772)
@@ -207,7 +207,7 @@
     "spaces": Arg(
         '--spaces',
         help='Specify which parameters to hyperopt. Space-separated list.',
-        choices=['all', 'buy', 'sell', 'roi', 'stoploss', 'trailing', 'default'],
+        choices=['all', 'buy', 'sell', 'roi', 'stoploss', 'trailing', 'default','protections'],
         nargs='+',
         default='default',
     ),
Index: freqtrade/optimize/hyperopt_interface.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/freqtrade/optimize/hyperopt_interface.py b/freqtrade/optimize/hyperopt_interface.py
--- a/freqtrade/optimize/hyperopt_interface.py	(revision 64a2897d64c75176ab68685a912d5d586228cb12)
+++ b/freqtrade/optimize/hyperopt_interface.py	(date 1614463552058)
@@ -175,6 +175,22 @@
             Real(-0.35, -0.02, name='stoploss'),
         ]
 
+    @staticmethod
+    def protections_space() -> List[Dimension]:
+        """
+        Create a stoploss space.
+
+        Defines range of stoploss values to search.
+        You may override it in your custom Hyperopt class.
+        """
+        return [
+            Integer(1, 400, name='lookback_period_candles'),
+            Integer(1, 100, name='trade_limit'),
+            Integer(1, 400, name='stop_duration_candles'),
+            Real(0, 1, name="max_allowed_drawdown"),
+            #Categorical([True,False], name='only_per_pair'),
+        ]
+
     @staticmethod
     def generate_trailing_params(params: Dict) -> Dict:
         """

```

**Comment by xmatthias** [comment]
I'm not convinced about optimizing protections.
Sure, it's a parameter you can (and have to) optimize and that will make a difference eventually. 

However, i think you'll get into complexity troubles very soon.

Your optimization seems to only optimize one protection (for now i guess) - the problem is - you'll want to optimize the combination of all possible protections - with all possible parameters for each protection.

For that to work correctly, you'll need to build a rather complex space.
considering that not all protections use all parameters - so you might optimize `trade_limit` for `CooldownPeriod` - which doesn't use that parameter - so it's cpu cycles wasted.

---

to make an example to explain the complexity of this further: 

Say i want to use between 0 and 5 protections (don't care which ones as long as they increase profits).
the possibilities here would be

* the same protection multiple times with different parameters (shorter-term lock, longer term lock looking back longer)
* each protection only once 
* no protection
* anything in between the above

the next problem is - skopt won't allow you to build hierarchical spaces - so it'll change the parameters of each protection even if the protection itself is disabled, again, leading to a lot of wasted (cpu) time.

This is a problem with the other spaces too, but will multiply here as i have 4 parmeters that can be optimized without changing anything (because the protection is disabled).

**Comment by squat0001** [comment]
Hi!

ok, i do know this. I do run hyperopt multiple times with different 
spaces, mostly to get sane
defaults for the parameter space.

And i do know that running hypertopt for all protections at once is not 
easy do able
(normaly one would like roi+all_protections which would be a huge search 
space).
But.. trying, guessing, running multiple times backtesting to find some 
parameters which do something "okish", is also very time consuming, and 
let it run
for some days, why not.

So .. my plan would be adding a hyperopt space per protection, or maybe 
better a hyperopt space for "configuration" at all, which would allow 
people to
test for all parameters like "use_sell_signal".. and, yes not all 
parameters do make sense, but nobody has to do them.

The main problem i see, is clean code. At this time a protection gets 
registered, and nearly all code for a protection is in one place, which 
is nice.
Adding a space per protection would spread code from protections into 
hyperopt, and adding new protections will lead to more code spreading.

Adding a space for configuration would be much cleaner in terms of 
programming. (i would also allow in a second step refactor the spaces 
for stoploss/trailing/roi).

greetings


Am 28.02.2021 um 08:33 schrieb Matthias:
