### ISSUE TITLE
 joblib.externals.loky.process_executor.TerminatedWorkerError

### ISSUE THREAD

**Issue by samgermain** [freqtrade/freqtrade#4466]
**Environment**
VM: Azure F2s_v2 (vCPUs: 2, Ram(GiB): 4, Data disks: 4, Max IOPS: 3200, Storage(GiB): 16)
Supported
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Ubuntu 18.04.5 LTS
Python 3.7.9
numpy: '1.20.1'
scipy: '1.6.1'
joblib: '1.0.1'

<hr></hr>

i get this error when running the hyperopt sometimes. Do you know why this might be happening?
[Looks like it might be able to be fixed by setting n-jobs=-2](https://github.com/scikit-learn-contrib/skope-rules/issues/18#issuecomment-625893373), but I don't really know much about this, I was just googling it

```
2021-03-01 04:15:59,357 - freqtrade.optimize.hyperopt - INFO - Found 2 CPU cores. Let's make them scream!
2021-03-01 04:15:59,357 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2021-03-01 04:16:01,070 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 2
 [Epoch 0 of 1000 (N/A%)] |/                                                                 | [ETA:  --:--:--, Elapsed Time: 0:00:00]
2021-03-01 04:21:20,631 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/azureuser/freqtrade/freqtrade/commands/optimize_commands.py", line 83, in start_hyperopt
    hyperopt.start()
  File "/home/azureuser/freqtrade/freqtrade/optimize/hyperopt.py", line 718, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/home/azureuser/freqtrade/freqtrade/optimize/hyperopt.py", line 623, in run_optimizer_parallel
    wrap_non_picklable_objects(self.generate_optimizer))(v, i) for v in asked)
  File "/home/azureuser/freqtrade/.env/lib/python3.7/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/azureuser/freqtrade/.env/lib/python3.7/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/azureuser/freqtrade/.env/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.
```

**Comment by xmatthias** [comment]
it's a memory problem.

Hyperopt is quite memory intensive, as the data is needed by each process - and hyperopt defaults to use your (virtual) cpu count as parallelism, so for example, if you got 4 physical cores (8 hyperhreaded cores) - hyperopt will use 8 parallel processes, which means the data needs to fit into memory at least 8 times (it's actually more, as there's some overhead).

You can "fix" this by
* use more memory (RAM)
* limit parallelism with `-j` to a lower number - negative numbers will be threaded as "available -" - so in the above sample, -2 would mean 6 cores - but it's possible that you'll need to go lower with this, depending on the memory and the below parameters.
* use a shorter timerange (reduces amount of data)
* use a longer timeframe (reduces amount of data)
* use fewer pairs (reduces amount of data)

**Comment by samgermain** [comment]
@xmatthias From the research I did, it seems like I can go to max 2 jobs, since my number of cpu's is 2. I changed this line in `hyperopt.py` to this, with the second argument of `self.config.get` to be 2 instead of -1
```
config_jobs = self.config.get('hyperopt_jobs', 2)   
```

I thought that -1 was going to return 2 anyway, but I don't know, maybe sometimes it messes up or something. The error doesn't appear immediately, so I don't know if it's going to happen yet.

How can I tell how many cores I have? Is changing that line above the same as setting `-j 2`?

**Comment by xmatthias** [comment]
yes, it's the same as using `-j 2`.

If you run it with `-j -1` (the default) - hyperopt will print the effective number of workers.
Your log output shows `Effective number of parallel workers used: 2` - so this would seem correct.

**Comment by samgermain** [comment]
It looks like it crashed with my adjustment, so it looks like I essentially can't have any parralel workers

But it was still telling me

```
2021-03-01 07:28:01,274 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: -1
2021-03-01 07:28:01,295 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 2
```

**Comment by xmatthias** [comment]
as said above, it's not a paralelity problem, but a ram problem.

try to reduce the amount of data that's being used (as explained above).

**Comment by samgermain** [comment]
@xmatthias So I set up a different VM on azure(Standard D2s v3), this one has 8 GB Ram, 2 vCPUs, and 16 GB storage. I running hyperopt on 93 pairs for 28 days of data, and the error still happened (on Epoch 613). Is 93 pairs too much to test on? Is 28 days unneccessary?

**Comment by xmatthias** [comment]
as said above - it'll depend on many things.

28 days with 93 pairs on a 1h timeframe is surely not a problem.
28 days with 93 pairs on a 1m timeframe will (probably) bring you to the limit of 8Gb
28 days with 93 pairs on a 5m timeframe probably somewhere in between - but i guess it should work in theory (otherwise, limiting parallelity will always work).

**Comment by samgermain** [comment]
@xmatthias Sorry, I thought I said the timeframe. It's 30m. I set -j 1 because that seems to be the only thing that will work for it. It's taking a long time though, but i guess thats to be expected

**Comment by xmatthias** [comment]
as said, -1 is the default - and will use all (but one) available cores.

**Comment by samgermain** [comment]
So it turns out that using `-j -2` with 8gb of ram on 28 days for 30 min candles  and 94 pairs couldn't even do it, it crashed on Epoch 759. I guess I'll try less pairs, or less days.

**Comment by samgermain** [comment]
I set up an 8 vCPU 32gb VM on Google Cloud with their free trial credits. I'm thinking this should work.

**Comment by samgermain** [comment]
@xmatthias  So even with 8 vCPU and 32gb ram on 28 days of data with 30 minutes candles and 94 pairs it still crashed (on epoch 2161 this time). I'm starting to think I might have something else wrong.

Did I install everything right? I run this script before running `setup.sh`, because otherwise the setup doesn't work

```
curPath=${pwd}
sudo apt-get update
sudo apt-get install gcc
sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev wget liblzma-dev lzma
cd /usr/src
sudo wget https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz
sudo tar xzf Python-3.7.9.tgz
cd Python-3.7.9
sudo ./configure --enable-optimizations
sudo make
sudo make altinstall
# sudo ./configure
cd ${pwd}
```

**Comment by xmatthias** [comment]
in general, newer pythons are better, so i'd use python 3.7 only if you must (which i'd only do on a raspberry).

in general, If it starts and does more than a few epochs, it's installed correctly. 
If your script is correct i don't know, as i don't install python this way.

While you increased memory - you also increased the amount of cores, so unless you limit the paralellism with `-j`, it'll also automatically take more memory.

I've said it above, please reduce either the timerange or amount of pairs and it should work.
You can also reduce the search-space of your hyperopt by either running only a few spaces (`--space buy sell`) - or by limiting the options it has.
scikit-optimize keeps track of all previously evaluated values (and calculates the potential best next step for it) - so it'll obviously consume more memory if there's more options).

Also, running for more than 1000 epochs will most likely not give you much better results, as baesian search tends to run into local minima it won't find out again, which means results will no longer improve / not improve very much.
Running it for a limited amount of epochs multiple times and picking the best of these runs manually willl most likely result in better results.

**Comment by samgermain** [comment]
@xmatthias 

> Also, running for more than 1000 epochs will most likely not give you much better results, as baesian search tends to run into local minima it won't find out again

Is the bayesian search implemented by freqtrade or by joblib? I'm assuming you know more A.I. than I do, but I wrote a simulated annealing program once, and the point of that algorithm was to specifically solve the problem of local minima

**Comment by xmatthias** [comment]
neither, it's part of scikit-optimize.

**Comment by rokups** [comment]
I am getting same exception, but there is something interesting about it. I am definitely not running out of RAM.

`-j 24` results in original exception and this resource usage:
![image](https://user-images.githubusercontent.com/19151258/110236006-288c9800-7f3c-11eb-9eb1-d6f890b6dfee.png)

-j 32 results in `*** stack smashing detected ***: terminated` + original exception and this resource usage:
![image](https://user-images.githubusercontent.com/19151258/110236009-2cb8b580-7f3c-11eb-83f9-62b0ccfb0324.png)

**Comment by xmatthias** [comment]
Best search for the new exception in the context of scikit-optimize.

It's not an error i've ever come across.

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.
