### ISSUE TITLE
separate pair list - possible?

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4471]
## Describe your environment

Operating system: Debian 10
Python Version: Python 3.7.3
CCXT version: ccxt==1.42.19
Freqtrade Version: freqtrade develop-05f057fe
  
## Your question

Is there a way to use a separate pair list, so that the coin pairs are not inside config.json?
Something like the pairs file mentioned [here](https://www.freqtrade.io/en/latest/data-download/#pairs-file). I tried that but I think that's only valid for downloading data, not running freqtrade, because I got this message `freqtrade.exceptions.OperationalException: StaticPairList requires pair_whitelist to be set.` 

It's not a big deal I just think config.json would be a lot more tidy, and it would make it easier to make changes to the pairs automatically, if they are not inside the config.json file.

**Comment by xmatthias** [comment]
You can use multiple `--config` parameters which will merge the configuration together, so you can have the pairlist in the "last" config file and it'll be combined with the rest.

Alternatively, you can use [VolumePairList](https://www.freqtrade.io/en/latest/plugins/#volume-pair-list) which will automatically select pairs based on 24h volume.

**Comment by aristosv** [comment]
Great tip on the multiple --config parameters. I had no idea.

Regarding "VolumePairList", I assume there's no base currency right? It won't select only USDT pairs for example?

Does that mean I need to have multiple coins available on the Exchange, so it can use them to buy/sell?

**Comment by xmatthias** [comment]
It will always only select pairs in your stake currency.

**Comment by aristosv** [comment]
Awesome. Thanks.
