### ISSUE TITLE
Telegram Notification / Protections StopLossGuard 

### ISSUE THREAD

**Issue by bozzfozz** [freqtrade/freqtrade#4475]
Are there possibilities of telegram notification for the protections, for example when StopLossGuard is active

**Comment by xmatthias** [comment]
no, there's not.

I'm also not sure it'll make sense - if it would be notified for one protection, the same exact would apply to all - so you'd probably get spammed (depending on the configuration).

In the end, it's a feature to allow you to NOT look at the markets all the time to eventually manually stop the bot ...

**Comment by bozzfozz** [comment]
No, the bot shouldn't spam me, if I make a status query it should possibly answer me that the StopLossGuard is currently active


It is active, but I don't know and then have to look in the logs and so I can query the status

**Comment by xmatthias** [comment]
you can use `/locks` to get this information (also for all other protections, obviously).

**Comment by bozzfozz** [comment]
Ok thanks, didn't think of it
