### ISSUE TITLE
VolumePairList - Exclude leveraged tokens

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4476]
## Describe your environment

Operating system: Debian 10
Python Version: Python 3.7.3
CCXT version: ccxt==1.42.19
Freqtrade Version: freqtrade develop-05f057fe

## Your question

When using VolumePairList, is it possible to exclude Leveraged tokens? I found the wildcards option, but that was listed under StaticPairList.

Ideally, excluding something like this would work.

*.UP/BTC
*.DOWN/BTC

How can I implement this when using VolumePairList?

**Comment by xmatthias** [comment]
You can use wildcards in your blacklist.
Blacklisted coins will not be used in any pairlist / will be removed.

**Comment by aristosv** [comment]
thank you
