### ISSUE TITLE
canceled open sell order 

### ISSUE THREAD

**Issue by Ronandz** [freqtrade/freqtrade#4479]
Hello everyone,

 I have a question: I'm running a strategy with 1m timeframe, its running very fast, the strategy working very well in the dry mode, but it doesnt work good in the live mode.
I have all the time canceling open sell order, could you help me please what to do for selling ? 
this is my config:
```javascript
{

    "max_open_trades": 15,
    "stake_currency": "USDT",
    "stake_amount": 100,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "1m",
    "dry_run": false,
    "cancel_open_orders_on_exit": false,
    "unfilledtimeout": {
        "buy": 5,
        "sell": 5
    }, 
    "bid_strategy": {
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
```

![image](https://user-images.githubusercontent.com/80004289/109866370-19b49580-7c5d-11eb-9515-eb398d7ff49c.png)

Regards.

**Comment by xmatthias** [comment]
well orders time out after 5 minutes if they are not filled.

You can control this by changing how [orders are priced](https://www.freqtrade.io/en/latest/configuration/#prices-used-for-orders) - but you should understand the implications first.
if you change the side the price is taken from, you'll pay the spread, which will often kill a fast strategy's profits.
