### ISSUE TITLE
Getting Error when running ./setup.sh script

### ISSUE THREAD

**Issue by sameertariq** [freqtrade/freqtrade#4480]
I am trying to install Freqtrade on Ubuntu machine. 
I am getting errors when I run ./setup.sh --install command.

it takes a lot of time on the following line
  Building wheel for pandas (setup.py) ... | 

and then i give me a lot of errors

**Comment by eaimounir** [comment]
I noticed a similar issue on 1 core machine. Try to install with at least 2 cores.
@sameertariq, can you please share the list of errors

**Comment by samgermain** [comment]
@sameertariq I think it might be your python version, I was getting this on an azure vm with 2 vCPUs. Could you list your `python` version and `ubuntu` version?  (`python -V` and `lsb_release -a`)

I made a script to install `python3.7` which contains all the installs and commands you'll need to run

```
curPath=${pwd}
sudo apt-get update
sudo apt-get install gcc
sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev wget liblzma-dev lzma
cd /usr/src
sudo wget https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz
sudo tar xzf Python-3.7.9.tgz
cd Python-3.7.9
sudo ./configure --enable-optimizations
sudo make
sudo make altinstall
# sudo ./configure
cd ${pwd}
```

If you're on a VM, you may need to reboot it, or just disconnect your `ssh` and re-connect

This is what worked for me

---------------

Also, if the `setup.sh` script won't install Ta-lib correctly, you can use this script

```
wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
if [ ! -f "ta-lib/CHANGELOG.TXT" ]; then
  tar zxvf ta-lib-0.4.0-src.tar.gz
  cd ta-lib && sed -i.bak "s|0.00000001|0.000000000000000001 |g" src/ta_func/ta_utility.h && ./configure && make && sudo make install && cd ..
else
  echo "TA-lib already installed, skipping download and build."
  cd ta-lib && sudo make install && cd ..
fi
```

**Comment by samgermain** [comment]
@sameertariq My original post was missing 2 installs, it should work now
