### ISSUE TITLE
bot shows some times in the past

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4481]
## Describe your environment

Operating system: Debian 10
Python Version: Python 3.7.3
CCXT version: ccxt==1.42.19
Freqtrade Version: freqtrade develop-05f057fe
  
## Your question

Even though the server's time is correct, and freqtrade detects the time correctly, I noticed that when showing until when a pair is locked, the time is in the past. I'm not sure if it's something on the server, or some misconfiguration with the bot.

<img width="209" alt="2" src="https://user-images.githubusercontent.com/528302/109933877-8d45b980-7cd4-11eb-91b2-49ae655adb47.png">

![Greenshot 2021-03-04 10 26 07](https://user-images.githubusercontent.com/528302/109933891-9040aa00-7cd4-11eb-8a57-6626e63b2813.png)

**Comment by xmatthias** [comment]
log time will be the server time.
The lock time is in UTC - with EET being 2h ahead of UTC, this seems correct.

While it's not ideal, exchanges in general work with UTC - therefore transferring the date to local time can lead to a lot of confusion.
This is especially true in cases where the server time does not correspond to the user time (e.g. a server running in Japan, the user being in Europe).

The times reported would be server time - which has no correlation with Europe whatsoever and will only confuse you, as now times are ahead by 6-8 hours.

**Comment by aristosv** [comment]
So I guess it would be better to just add 2 hours to the lock time. Thanks for the clarification.
