### ISSUE TITLE
Range Stability Filter with large volume pairlist

### ISSUE THREAD

**Issue by jameslewisuk** [freqtrade/freqtrade#4483]
I am running with a very large volume pair list of 250 to include every USDT pair

I would notice that with the filters running, it would initially search for however many available on exchange pairs:

Using whitelist ['VolumePairList', 'AgeFilter', 'PrecisionFilter', 'PriceFilter', 'SpreadFilter', 'RangeStabilityFilter', 'PerformanceFilter'] with 178 pairs
BTC/USDT, ETH/USDT, ADA/USDT, CHZ/USDT, ENJ/USDT, XRP/USDT, DOT/USDT, LTC/USDT, UNI/USDT, LINK/USDT, VET/USDT, SXP/USDT, TRX/USDT, XEM/USDT, REEF/USDT, ATOM/USDT, THETA/USDT, FTM/USDT, SUSHI/USDT, IOST/USDT, EGLD/USDT, LUNA/USDT, XLM/USDT, ALGO/USDT, MANA/USDT, BCH/USDT, SAND/USDT, EOS/USDT, ALPHA/USDT, FIL/USDT, HBAR/USDT, DOGE/USDT, GRT/USDT, ICX/USDT, MATIC/USDT, AVAX/USDT, BAT/USDT, ONT/USDT, AAVE/USDT, CAKE/USDT, SUN/USDT, AXS/USDT, IOTA/USDT, CRV/USDT, BNT/USDT, COTI/USDT, NEO/USDT, CHR/USDT, 1INCH/USDT, SOL/USDT, ZIL/USDT, GBP/USDT, TOMO/USDT, TFUEL/USDT, XVS/USDT, DASH/USDT, SFP/USDT, QTUM/USDT, NEAR/USDT, XTZ/USDT, VTHO/USDT, DODO/USDT, SRM/USDT, FET/USDT, SNX/USDT, KAVA/USDT, LIT/USDT, STX/USDT, ZEC/USDT, ETC/USDT, ANKR/USDT, TUSD/USDT, KSM/USDT, RSR/USDT, HARD/USDT, OCEAN/USDT, RUNE/USDT, BAND/USDT, YFI/USDT, RVN/USDT, XMR/USDT, OMG/USDT, AUDIO/USDT, BTT/USDT, ZRX/USDT, REN/USDT, ORN/USDT, UNFI/USDT, SKL/USDT, AUD/USDT, BLZ/USDT, CELR/USDT, KNC/USDT, HOT/USDT, ARPA/USDT, BTCST/USDT, WRX/USDT, COMP/USDT, IOTX/USDT, ROSE/USDT, NPXS/USDT, DENT/USDT, DIA/USDT, WAVES/USDT, FLM/USDT, YFII/USDT, ONE/USDT, LRC/USDT, FTT/USDT, FIO/USDT, MFT/USDT, ANT/USDT, STORJ/USDT, CTK/USDT, RLC/USDT, NANO/USDT, AION/USDT, JST/USDT, ZEN/USDT, PNT/USDT, INJ/USDT, BZRX/USDT, TRB/USDT, CVC/USDT, CKB/USDT, BEL/USDT, DGB/USDT, BAL/USDT, ONG/USDT, TWT/USDT, DOCK/USDT, KEY/USDT, WIN/USDT, PAXG/USDT, UMA/USDT, WNXM/USDT, MKR/USDT, OXT/USDT, UTK/USDT, LSK/USDT, HNT/USDT, FIRO/USDT, DNT/USDT, WTC/USDT, IRIS/USDT, CELO/USDT, BTS/USDT, SC/USDT, DUSK/USDT, LTO/USDT, KMD/USDT, MTL/USDT, NMR/USDT, WAN/USDT, DCR/USDT, MBL/USDT, TROY/USDT, TRU/USDT, AVA/USDT, MDT/USDT, MITH/USDT, HIVE/USDT, NULS/USDT, CTXC/USDT, BEAM/USDT, NKN/USDT, ARDR/USDT, FUN/USDT, VITE/USDT, REP/USDT, NBS/USDT, PSG/USDT, OG/USDT, ASR/USDT, GXS/USDT, ATM/USDT, DREP/USDT, SUSD/USDT

On the 2nd scan for pairs, it always changes to 100 pairs, even though the RangeStabilityFilter is not filtering out 78 pairs.

Using whitelist ['VolumePairList', 'AgeFilter', 'PrecisionFilter', 'PriceFilter', 'SpreadFilter', 'RangeStabilityFilter', 'PerformanceFilter'] with 100 pairs
BTC/USDT, ETH/USDT, ADA/USDT, CHZ/USDT, ENJ/USDT, XRP/USDT, DOT/USDT, LTC/USDT, UNI/USDT, LINK/USDT, VET/USDT, SXP/USDT, TRX/USDT, XEM/USDT, REEF/USDT, ATOM/USDT, THETA/USDT, FTM/USDT, SUSHI/USDT, IOST/USDT, EGLD/USDT, LUNA/USDT, XLM/USDT, ALGO/USDT, MANA/USDT, BCH/USDT, SAND/USDT, EOS/USDT, ALPHA/USDT, FIL/USDT, HBAR/USDT, DOGE/USDT, GRT/USDT, ICX/USDT, MATIC/USDT, AVAX/USDT, BAT/USDT, ONT/USDT, AAVE/USDT, CAKE/USDT, SUN/USDT, AXS/USDT, IOTA/USDT, CRV/USDT, BNT/USDT, COTI/USDT, NEO/USDT, CHR/USDT, 1INCH/USDT, SOL/USDT, ZIL/USDT, GBP/USDT, TOMO/USDT, TFUEL/USDT, XVS/USDT, DASH/USDT, SFP/USDT, QTUM/USDT, NEAR/USDT, XTZ/USDT, VTHO/USDT, DODO/USDT, SRM/USDT, FET/USDT, SNX/USDT, KAVA/USDT, LIT/USDT, STX/USDT, ZEC/USDT, ETC/USDT, ANKR/USDT, TUSD/USDT, KSM/USDT, RSR/USDT, HARD/USDT, OCEAN/USDT, RUNE/USDT, BAND/USDT, YFI/USDT, TRU/USDT, AVA/USDT, MDT/USDT, MITH/USDT, HIVE/USDT, NULS/USDT, CTXC/USDT, BEAM/USDT, NKN/USDT, ARDR/USDT, FUN/USDT, VITE/USDT, REP/USDT, NBS/USDT, PSG/USDT, OG/USDT, ASR/USDT, GXS/USDT, ATM/USDT, DREP/USDT, SUSD/USDT

If I remove the RangeStabilityFilter from my config, it scans all the pairs.

	"pairlists": [
	{
        "method": "VolumePairList",
        "number_assets": 200,
        "sort_key": "quoteVolume",
        "refresh_period": 900
	},
	{"method": "AgeFilter", "min_days_listed": 10},
	{"method": "PrecisionFilter"},
	{"method": "PriceFilter", "low_price_ratio": 0.0001},
    	{"method": "SpreadFilter", "max_spread_ratio": 0.005},
   	{"method": "RangeStabilityFilter",
        "lookback_days": 10,
        "min_rate_of_change": 0.03,
        "refresh_period": 1440
	},
    	{"method": "PerformanceFilter"}
    ],

It seems to be that with RangeStabilityFilter enabled, once it has processed and filtered, the output of pairs is always reduced to 100 pairs? (it certainly doesnt show it is filtering out 78 pairs)

**Comment by xmatthias** [comment]
what version are you using? (the issue template is there for a reason!)

Also, please provide logs from this happening (i guess you can remove the "irrelevant" stuff from the logs in between).

**Comment by jameslewisuk** [comment]
Sorry to jump to possible conclusing.  I am using 2021.2
I think it might be related to

freqtrade/plugins/pairlist/rangestabilityfilter.py

Line 31
        self._pair_cache: TTLCache = TTLCache(maxsize=100, ttl=self._refresh_period)

I think maxsize may be limiting it?  I changed mine to 250 it seems to fix

**Comment by xmatthias** [comment]
I noticed this too - but i'm not convinced that's the problem.

while it's limiting the cache to 100 items - it would simply re-test the remaining pairs again as it doesn't find them in the cache, which should either remove them with log - or keep them correctly.
now the log message would not be shown every time to limit log spamming - but it would still not limit this to 100 pairs.

**Comment by jameslewisuk** [comment]
With maxsize= 250 it is now scanning all the pairs each time, maybe some issue with the caching?

**Comment by jameslewisuk** [comment]
Here is log file, you can see at 10:19:29 it scans all the filtered pairs, then shortly after at 10:20:13 the pairs have reduced to the 'limit' of 100

I think the rangestabilityfilter works correctly at inital start up and pull of data from API at 10:19:27, but once everything has 'started up' and settled down running/scanning for pairs at 10:20:13 the rangestabilityfilter seems to have some issue on subsequent passes and limits output to 100 pairs, seems to be something to do with the cache?

What seemed to "fix" it was changing the cache maxsize greater than 100 in 
freqtrade/plugins/pairlist/rangestabilityfilter.py

Line 31
self._pair_cache: TTLCache = TTLCache(maxsize=100, ttl=self._refresh_period)


Log attached
[log.txt](https://github.com/freqtrade/freqtrade/files/6089835/log.txt)

**Comment by xmatthias** [comment]
It's an interresting case for sure.

You're right that the cache eviction plays a role - but not in a way you'd expect :laughing: 

we only pull data for pairs that need refreshing - which will be all pairs except for the ones in the cache.

Now because the list of pairs is longer than the cache, the pairs that used to be in the cache are evicted BEFORE they are checked - which results in not having data available - which evicts the pair.

It's quite a different kind of problem than what i expected ... 

The fix is quite simple, and max_size here is not really relevant - so i'll make it big enough to not interfere (i'll pick 1000 instead of the 250 you picked - just to be sure).
