### ISSUE TITLE
VolumePairList  - exclude all fiat currencies

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4487]
## Describe your environment

Operating system: Debian 10
Python Version: Python 3.7.3
CCXT version: ccxt==1.42.19
Freqtrade Version: freqtrade develop-05f057fe
  
## Your question

I am using VolumePairList, along with all the available filters, to utilise a dynamic pair list. I noticed that freqtrade is also using fiat currencies when trading. (EUR, AUD, GBP etc). The problem with fiat currencies is that they are a lot more stable than crypto, so it's hard to take advantage of the volatility to make a profit. So they stay open for a lot more time than crypto currencies. 

Is there a way to exclude all fiat currencies, without having to specify them all manually, one by one, in the blacklist?

Thanks

**Comment by xmatthias** [comment]
A fiat currency is nothing special from an exchange api point of view.
Would freqtrade offer such a functionality, we'd need to keep a list of these currencies - which is WAY too risky to provide, as we might always miss a currency here and there - and would need to keep that list updated all the time - which is in no way better than the user having to do it himself - except that then the responsibility is also with the user.

---

for the most part, RangestabilityFilter was made for this - but it doesn't cover 100% of the pairs (obviously depends on the configured values) (and it'll depend what your base-currency is).

**Comment by aristosv** [comment]
great, RangestabilityFilter makes sense. Thank you.
