### ISSUE TITLE
implementing informative pairs into buy signals 

### ISSUE THREAD

**Issue by cchhrriiss92** [freqtrade/freqtrade#4492]
I'm new to freqtrade and also just been started to learn python ..
Could anyone help me why I'm getting the wrong buy signal.
I'm using timeframe of 3m and 1h (using informative pair)
I restricted buying signal to pairs that have movement range of under 45% within past 50hrs.
But recently it bought a pair that has moved more than 70% within past 50hrs.

just for your info, I'm using volume based pairlists of 70

`

    def informative_pairs(self):

        pairs = self.dp.current_whitelist()
        informative_pairs= [(pair, '1h') for pair in pairs]

        return informative_pairs

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        if not self.dp:
            return dataframe

        inf_tf = '1h'
        informative= self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf)
        informative['ema12']=ta.EMA(informative, timeperiod=12)

        dataframe= merge_informative_pair(dataframe, informative, self.timeframe, inf_tf, ffill=True)

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (
                ((max(dataframe['high_1h'][-50:])/(min(dataframe['low'][-50:])))<1.45) &`

**Comment by xmatthias** [comment]
by using absolute indexing, this strategy is not backtestable / backtest results will be wrong as it'll look at the (real) last 50 hours of the data - not the 50 hours prior to when the signal happens.

You should use `dataframe['high_1h'].rolling(50).max()` and `dataframe['high_1h'].rolling(50).min()` instead.

**Comment by cchhrriiss92** [comment]
Thank you for the reply. Btw I was on live mode. Anyway, I just came to this idea.. which since I used ffill=True when merging dataframe with informative pair, so dataframe['high_1h'].rolling(50) only applies to 150m(3m*50) and not 50 hrs which I was intending. So maybe I should instead use dataframe['high_1h'].rolling(1000)?

**Comment by xmatthias** [comment]
you'll need to apply the "rolling" before merging and store it as seperate column, otherwise you're right, it'll not be what you think it is (and 1000 candles are not available for alle xchanges).

**Comment by cchhrriiss92** [comment]
Thank you. After taking times to look through dataframe formed, I understood what you are saying and fixed everything. :)
