### ISSUE TITLE
The output of the command /trades is sorted by ID instead of by close_date

### ISSUE THREAD

**Issue by Th0masL** [freqtrade/freqtrade#4498]
## Describe your environment

  * Freqtrade Version: 2021.2

## Describe the problem:

I believe that the command `/trades [limit]` should list the last closed trades, ordered by closure time.

But right now the trades are listed by Trade ID, therefore it's not showing the last closed trades but it is showing the last opened trades that have been closed.

If you are looking for the last closed trade, you might have to go back as far as `/trade XX` (like `/trade 30`), depending when it was opened initially.

### Steps to reproduce:

  1. Look for a trade that got opened long time ago and that just got closed
  2. Run the command `/trades`
  3. Search for this trade in the list
  4. If it has been opened long enough ago, it won't be visible
  
### Observed Results:

  * What happened?
  The trades are ordered by Trade ID, so the recent closed trades might be missing, depending on their ID
  * What did you expect to happen?
  The trades should be ordered by Closure Time

### Relevant code exceptions or logs

I believe that in the `rpc/rpc.py` file below, `Trade.id.desc()` should be changed to `Trade.close_date.desc()`
  ```
    def _rpc_trade_history(self, limit: int) -> Dict:
        """ Returns the X last trades """
        if limit > 0:
            trades = Trade.get_trades([Trade.is_open.is_(False)]).order_by(
                Trade.id.desc()).limit(limit)
        else:
            trades = Trade.get_trades([Trade.is_open.is_(False)]).order_by(Trade.id.desc()).all()
  ```

It could also be worth changing the columns in the output of `/trades` :
- add the Trade ID
- replace "Open Date" by "Close Date", or add "Close Date" (although there isn't that much space)

From :
```
10 recent trades:
Open Date     Pair        Profit (USDT)
------------  ----------  ------------------
6 hours ago   SFP/USDT    0.25% (0.16807254)
7 hours ago   ZIL/USDT    0.76% (0.50417386)
8 hours ago   CVC/USDT    0.01% (0.00792157)
9 hours ago   DOCK/USDT   0.81% (0.53431329)
```

To :

```
10 recent trades:
  ID  Close Date     Pair        Profit (USDT)
----  -------------  ----------  ------------------
  17  0.1 hours ago  CVC/USDT    0.01% (0.00792157)
  26  0.3 hours ago  SFP/USDT    0.25% (0.16807254)
  15  1.0 hours ago  DOCK/USDT   0.81% (0.53431329)
  22  1.5 hours ago  ZIL/USDT    0.76% (0.50417386)
```

Do we agree that this need to be fixed ? I can take care of it if needed :slightly_smiling_face:

**Comment by ShubhamPalriwala** [comment]
Hey @Th0masL , I'd like to take this issue up !

**Comment by Th0masL** [comment]
@Theagainmen may I ask why you reacted with thumbs-down ? Maybe you have a better idea on how we can improve that ?

@xmatthias Which layout do you think is the best ?

1) The long version, using `.humanize()`
```
2 recent trades:
Close Date      ID    Pair     Profit (BTC)
--------------  ----  -------  --------------
13 hours ago    3     XRP/BTC  1.00% (None)
a day ago       2     ETC/BTC  0.50% (None)
```

or 2) The short version, using `shorten_date()` + `.humanize()`
```
2 recent trades:
Close Date    ID    Pair     Profit (BTC)
------------  ----  -------  --------------
13 h ago      3     XRP/BTC  1.00% (None)
1 d ago       2     ETC/BTC  0.50% (None)
```

Other questions :
- should we keep both the `Open Date` colum and add the `Close Date` too ?
- should the column label be `Close Date` or `Closed Since` ?

**Comment by xmatthias** [comment]
i wouldn't add open date - this table is already slightly too wide for most phones.

if we must have it, we should have a endpoint with `/trade <tradeid>` (or something less ambivalent) to get the full details (bud i'd keep that separate for now).

i'm personally not sure on using "humanize" on this at all ... maybe the real time (like 2021-03-06 18:04) makes more sense (although i think that'll take up slightly more space).

**Comment by Th0masL** [comment]
Yeah, I like the idea of using the full date, but if we compare the size of the table with real data, that's taking quite more space :disappointed: 

Current output :
```
2 recent trades:
Open Date     Pair       Profit (USDT)
------------  ---------  ------------------
10 hours ago  REN/USDT   0.84% (0.56323963)
11 hours ago  SFP/USDT   1.80% (1.20487136)
```

Possible future output :
````
2 recent trades:
Close Date           Pair (ID)       Profit (USDT)
-------------------  --------------  ------------------
2021-03-08 05:37:22  REN/USDT (#30)  0.84% (0.56323963)
2021-03-08 04:37:22  SFP/USDT (#29)  1.80% (1.20487136)
````

I think we will need to use `humanize` to keep this table as short as possible, and as you said, implement a `/trade <number>` later to be able to show more detail about a specific trade.

Your call, I'm happy with both date output anyway.

**Comment by xmatthias** [comment]
well i don't think we'll need seconds ... but yes, it'll be "quite a bit" longer... 

My problem with humanize is that in most cases, it'll take quite a bit of information away ...
I'd say, keep it with humanize for now - we use that already ... but switching to close data (and sorting by that!) will make absolute sense.

**Comment by Th0masL** [comment]
PR #4508 has been made, I'm closing this issue
