### ISSUE TITLE
sell_signal vs ROI behavior

### ISSUE THREAD

**Issue by jbishop129** [freqtrade/freqtrade#4507]
## Describe your environment

  * Operating system: Ubuntu Server 20.04
  * Python Version: 2.7.17
  * CCXT version: 1.42.47
  * Freqtrade Version: freqtrade docker-02d7dc47
  * * In Docker, running latest `freqtradeorg/freqtrade:develop` as of 3/7/2021
  
## Your question
I apologize in advance as I feel like this likely has been covered in excruciating detail, and I have just failed to search for the right terms to find this:
I feel like I may be misunderstanding the relationship between `sell_signal` and `minimal_roi`. My understanding was that the values in the `minimal_roi` would take precedent over a `sell_signal` (generated by the logic defined in `def populate_sell_trend()`. So for example if I have a basic ROI:
``` json
    minimal_roi = {
        "30": 0.01,
        "0": 0.02
    }
```
.. whereby I'm telling the bot, "hey we'll take 2% right away, then after 30 min, we'll take 1%". I thought (though have learned through experience I am wrong) this would prevent a `sell_signal` from selling off a trade too early. In practice I see the vast majority of my trades close out with status `sell_signal` and tend to be pretty far below the indicators in my ROI table.

I will happily provide config files if needed, but first thought I'd just open this up to see if I (likely) am just misunderstanding the order of events and what instructions have priority.

Thanks!

**Comment by xmatthias** [comment]
consider minimal_roi as "take profit" - sell whenever above this - not as "prevent sells below this".

If your sell-signal indicates to sell, then the bot will follow through on this.
Negative sell-signals are not necessarily a bad thing, as they can prevent you from big losses if you're using a good sell signal.

You can control the activeness of sell-signals with `use_sell_signal`, `sell_profit_only` and `sell_profit_offset`.

**Comment by jbishop129** [comment]
Thanks, this makes sense. I also see that the behavior I described above is likely caused by a strategy I'm testing which is basically only looking for profit; anything above buy price + fee offset, so in that context, Working As Intended™. I had not explored the `sell_profit_offset`, thanks for pointing that out, I'm digging in to that now.
