### ISSUE TITLE
Backtesting fails when using startup_candle_count

### ISSUE THREAD

**Issue by anyn99** [freqtrade/freqtrade#4509]
Hi there!

I have exactly this problem with the recent develop branch and Python 3.8!

Everything works fine until i set the variable "startup_candle_count"

I tried printing the pairs and start/end timestamp by altering the get_timestamp function inside history-util.py, as suggested above. All timestamps where ok, but the ones with no history dataframes showed for both timeframes "NaT"!
```
('OMG/EUR', Timestamp('2021-01-01 00:00:00+0000', tz='UTC'), Timestamp('2021-03-05 14:10:00+0000', tz='UTC')), 
('BTC/EUR', NaT, NaT),
```

Without "startup_candle_count", those "NaT" got filtered out as i see the message 
```
2021-03-07 23:33:37,899 - freqtrade.data.history.idatahandler - WARNING - No history data for pair: "BTC/EUR", timeframe: 5m. Use `freqtrade download-data` to download the data
```
only then.

_Originally posted by @anyn99 in https://github.com/freqtrade/freqtrade/issues/2798#issuecomment-792372791_

**Comment by xmatthias** [comment]
define "the ones with no history" ? 

does that mean you have BTC/EUR in your pairlist - but you have no history for this? or no history in the relevant timerange ... ?

**Comment by anyn99** [comment]
Sorry my post was partly incorrect.

In fact the pairs are not blacklisted, they just lack history data in the relevant timerange.

**Comment by xmatthias** [comment]
ah, so basically you download data from 2021-01-01 forward - and try to backtest 2020-11-01 until 2020-12-01 ... so you don't have history for "some" pairs?

Does no pair have historic data in this interval ... or just one pair?
i'm not 100% certain i understand your problem just yet ...

**Comment by xmatthias** [comment]
I'll close this as without further information about what you're doing exactly, there's nothing i can do in this case.

I suspect it's related to how you treat the informative pair ... but without seeing the code you're using for this - i can't say for sure.

Feel free to comment below / reopen if you still see this issue (please with the code used to load and merge the informative pair) - so we can have a closer look.
