### ISSUE TITLE
using IFTTT webhooks with freqtrade

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4512]
## Describe your environment

  * Operating system: Debian 10
  * Python Version: Python 3.7.3
  * CCXT version: ccxt==1.42.66
  * Freqtrade Version: freqtrade develop-7e45af97
  
## Your question

I've never worked with webhooks so I'm trying to understand their usage with Freqtrade. I've read the [webhooks part of the documentation](https://www.freqtrade.io/en/latest/webhook-config/), I just need some clarifications.

1. Webhooks will allow me to control the bot, and get information from the bot, just like Telegram, but on a web based interface? (kinda like frequi?)

2. Does anyone have any examples on how to set up IFTTT to work with Freqtrade? The documentation covers the Freqtrade part of the configuration, but I haven't used IFTTT either, so I don't know if I should choose an Applet or a Service (or what their difference is.)

Thanks

**Comment by xmatthias** [comment]
1) no, webhooks are a "one-way street" - the bot will push information out - but it cannot receive any information / commands back. IFTTT also doesn't really provide you with an interface - it'll just take the webhook, convert it to "something else" and send it forward. 
 
for 2, i'd need to look it up, but it's a plain webhook (service) which needs to be configured, obviously the messages (or whatever you do with this) will need to align to your webhook configuration.
