### ISSUE TITLE
Question: ta.EMA with dataframe and price

### ISSUE THREAD

**Issue by jisnardo** [freqtrade/freqtrade#4516]
## Describe your environment

```
root@host:~# uname -a
Linux host.com 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
root@host:~# docker version
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:21 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:32 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
image: freqtradeorg/freqtrade:stable
```

## Your question

Hi, according to this:

https://www.freqtrade.io/en/latest/strategy-customization/#customize-indicators

We have this columns "open", "high", "low", "close", "volume" in the dataframe.

If I use EMA - Exponential Moving Average

https://github.com/mrjbq7/ta-lib/blob/master/docs/func_groups/overlap_studies.md

```
real = EMA(close, timeperiod=30)
```

Example:

https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/SmoothScalp.py

```
dataframe['ema5'] = ta.EMA(dataframe, timeperiod=5)

dataframe['ema5_close'] = ta.EMA(dataframe, timeperiod=5, price='close')
```

What's the difference between:

```
dataframe['close'] < dataframe['ema5']

dataframe['close'] < dataframe['ema5_close']
```

Is there any place where I can found documentation of ta-lib functions?

https://github.com/mrjbq7/ta-lib/blob/master/talib/_func.pxi#L2910

import talib.abstract as ta

```
def stream_EMA( np.ndarray real not None , int timeperiod=-2**31 ):
    """ EMA(real[, timeperiod=?])
    Exponential Moving Average (Overlap Studies)
    Inputs:
        real: (any ndarray)
    Parameters:
        timeperiod: 30
    Outputs:
        real
    """
    ...
```

Where price is allowed as a parameter?

```
dataframe['ema5_close'] = ta.EMA(dataframe, timeperiod=5, price='close')
```

Thank's in advance.

**Comment by xmatthias** [comment]
You should ask these questions in the ta-lib python repository.

Price is generally available in the abstract version of the library (which is what we use / document by default) - but i don't know if there is a dedicated documentation page for this.

**Comment by jisnardo** [comment]
Okay, for the documentation, but for the code?

What's the difference between:
```
dataframe['ema5'] = ta.EMA(dataframe, timeperiod=5)

dataframe['ema5_close'] = ta.EMA(dataframe, timeperiod=5, price='close')

1) dataframe['close'] < dataframe['ema5']

2) dataframe['close'] < dataframe['ema5_close']
```
What I'm comparing in the first one?

The price at close with...?

Thanks.

**Comment by xmatthias** [comment]
nothing, the default for price is close.

**Comment by jisnardo** [comment]
Thanks again @xmatthias.

**Comment by xmatthias** [comment]
The only "abstract" docs i know can be found [here](http://mrjbq7.github.io/ta-lib/abstract.html) 

not ... too extensive unfortunately.
