### ISSUE TITLE
Telegram message length limit

### ISSUE THREAD

**Issue by Pytness** [freqtrade/freqtrade#4519]
## Describe your environment

  * Operating system: Manjaro
  * Python Version: Python 3.9.2
  * CCXT version: ccxt==1.42.66
  * Freqtrade Version: freqtrade develop-ef9977fc

## Describe the problem:

When sending commands (/edge and potentially others) to the telegram bot, the bot does not respond due to the message being larger than the length limit.

The following errors are logged:

```
WARNING - Telegram NetworkError: Message is too long! Trying one more time.
WARNING - TelegramError: Message is too long! Giving up on that message.
  ```

## Related issues
#1745
#1749

**Comment by Pytness** [comment]
Maybe, a form of text paging could be implemented right into _send_msg, prefixing the page number to the text, for example:
```
[01/02]
some long text
...
```
```
[02/02]
the end of the text
```

Although this would probably break some of the HTML-based messages.

**Comment by xmatthias** [comment]
for some messages, pagination is implemented (like /balance).

it's definitely not the case for all messages, as it complicates the output quite a bit (you need to search for a good breakpoint, ...) - and it doesn't seem that common.
