### ISSUE TITLE
Minimal roi not activating 

### ISSUE THREAD

**Issue by Novitec1** [freqtrade/freqtrade#4520]
## Describe your environment

  * Operating system: _Ubuntu___
  * Python Version: __3.8.5___ 
  * CCXT version: _1.42.19____ 
  * Freqtrade Version: __freqtrade-develop 0bb90d14_

Hello,

I gave entered all the correct values for my minimal_roi based on my hyperopt.  However, when I run a backtest it shows many trades being open WAY longer than my max roi says they should be.  Why isnt that function being activated when it should be.  Am I missing something?

**Comment by xmatthias** [comment]
hyperopt will only use the configured ROI values if ROI is not part of the space to optimize (you can specify spaces with `--spaces <spaces>`.
The default space does include ROI - so if you want "your" ROI to be used, you should be explicit about the spaces to optimize.

Also, ROI can come from either config, or strategy (In this sequence) - so make sure you don't have anything in the config overwriting this.

**Comment by Novitec1** [comment]
For sure, I understand that part but, what about it not activating during the backtest?

For example, if my roi states I want to get out of a trade at 400min with 0 profit why does the backrest show there are trades left open for 10 days?

**Comment by xmatthias** [comment]
if you're defining it with "0" profit, then you're waiting for break-even.
All trades that are negative beyond that point will remain open until they break even (or hit stoploss).

**Comment by Novitec1** [comment]
Ahhhhhhhh, ok that makes sense.  I knew it was something simple I couldn't figure out lol.  Thank you, sir.

**Comment by xmatthias** [comment]
You can set the roi to -1 to force a sell at any price ... but 0 will wait for break-even ... :)

**Comment by Novitec1** [comment]
Awesome!  So, no matter what, as long as the stop loss isn't hit then it will wait for breakeven no matter how long it takes.  Am I understanding that correctly?

**Comment by xmatthias** [comment]
depends on what you configure.

with `{'60', 0}` - it'll sell at break even after 60 minutes.
with  `{'60', -1}`  - it'll always sell after 60 minutes, no matter what (unless there is a buy signal still active).

**Comment by Novitec1** [comment]
Perfect, that answers my question.  Thanks again.
