### ISSUE TITLE
hyperopt not launching

### ISSUE THREAD

**Issue by domojob** [freqtrade/freqtrade#4524]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.5
  * CCXT version: 1.42.66
  * Freqtrade Version: freqtrade develop-5e3e1e22
  
Hi !
I try to launch the hyperopt but it doesn't work, I look everywhere Slack, Discord, the freqtrade site but nothing. I got the following message but honestly don't know where to look

2021-03-11 13:27:14,186 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/root/freqtrade/freqtrade/commands/optimize_commands.py", line 83, in start_hyperopt
    hyperopt.start()
  File "/root/freqtrade/freqtrade/optimize/hyperopt.py", line 667, in start
    self.backtesting.exchange.close()
AttributeError: 'Binance' object has no attribute 'close'

Thanks for your guidance

**Comment by xmatthias** [comment]
to me, this sounds like you've got a mixed version (not properly merged).

Best check your checkout ... and eventually, make sure to install again `pip install -e .` with activated virtualenv ...

**Comment by domojob** [comment]
Hi Matt

You were right analyzing the installation from Udemy MTG it was well mixed between python 3.6 version, updates MTG release on their course, and the Freqtrade Latest with python 3.8.5. I reinstalled everything from scratch from Freqtrade Latest installation, and voila! It works.

Thanks
