### ISSUE TITLE
Possible to clear locks manually, besides with Telegram?

### ISSUE THREAD

**Issue by jbishop129** [freqtrade/freqtrade#4525]
* Operating system: Ubuntu Server 20.02
  * Python Version: 3.9.2
  * CCXT version: 1.42.66
  * Freqtrade Version: docker-441d3fad (latest `freqtradeorg/freqtrade:develop` image)
  
Relates to: #4103 

Hi, I was just wondering if there is a way to manually clear a lock, created from a `protections` entry in my config? I see reference to doing so from Telegram (which I dont use), and the api `/locks` endpoint seems to be only for listing currently active locks, unless I've missed something. Can I clear a lock from bash or API, or is this only possible via Telegram?

**Comment by xmatthias** [comment]
you can use `/unlock <pair>` via telegram or api (the name will be slightly different).

that's been added in #4469, so it's not yet available in the stable version.
