### ISSUE TITLE
How to properly use custom_stoploss function

### ISSUE THREAD

**Issue by Vildnex** [freqtrade/freqtrade#4527]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.9.2(`python -V`)
  * CCXT version: 1.42.66(`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-ef9977fc (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  

I am trying to create a strategy in which I am calculating my stoploss and take-profit based on ATR. Because my stoploss will be a dynamic one which is going to be different for every trade I was thinking to use the custom_stoploss function something like this:

```
def custom_stoploss(self, pair: str, trade: Trade, current_time: datetime, current_rate: float,
                    current_profit: float, **kwargs) -> float:

    REWARD = 2
    RISK = 1
    prev_sl = 0.0
    if self.custom_info and pair in self.custom_info and trade:
        if self.dp and self.dp.runmode.value in ('backtest', 'hyperopt'):
            atr_sl = self.custom_info[pair].loc[current_time]['atr'] * 2 * RISK
            sl = ((current_rate - atr_sl) / current_rate) - 1
            self.minimal_roi[0] = float(abs(sl) * REWARD)
            return sl
        else:
            dataframe, last_updated = self.dp.get_analyzed_dataframe(pair=pair, timeframe=self.timeframe)
            atr_sl = dataframe['atr'].iat[-1] * 2 * RISK
            sl = ((current_rate - atr_sl) / current_rate) - 1
            sl = round(sl, 5)
            self.minimal_roi[0] = float(abs(sl) * REWARD)
            return sl
```

And I say that this would be it, but something weird is happening and I'm not sure if this was intended (and if so, how can I change it). 

My stoploss will be calculated multiple times, once on each minute (I'm using 1min timeframe), I guess. But I don't want that, I want to be calculated just once per each trade, and that once to be only at the beginning of a trade. 

I've checked my math and strategy and the take profit area and also the stoploss should look something like this.
![image](https://user-images.githubusercontent.com/10352059/110965934-66832500-835d-11eb-9a47-d8527849af14.png)

But for some reason, my actual trade looks something like this.

![image](https://user-images.githubusercontent.com/10352059/110966049-8dd9f200-835d-11eb-8bc3-26047a1b52ac.png)

In the first picture you can also see with a white mark where was my trade stopped. I have this kind of weird situation in multiple places but I don't really understand what I am doing wrong.

**Comment by xmatthias** [comment]
custom stoploss will be called on every iteration (whenever freqtrade tries to find a sell opportunity).

That way, it can act similar to a trailing stop.
If you don't wan't to keep updating the stop, you can either set a static stop (will not be per pair/trade, but only one for everything) - or return a very high (-1) number after the first instance - as the stoploss will never be lowered, only raised

**Comment by Vildnex** [comment]
So what you are saying is that... After my first call of **custom_stoploss** per pair which let's say it will return -0.05(0.5%) if I will make something like a boolean check if it's the first try and if not I could return anything greater than **-0.05(0.5%)**? But if I am doing this is not going to affect backtesting results?

**Comment by xmatthias** [comment]
it'll affect backtesting just the same (although in backtesting, it's called once per candle, not once every iteration).
