### ISSUE TITLE
ERROR - wenn calling /profit

### ISSUE THREAD

**Issue by jurekl** [freqtrade/freqtrade#4528]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: Python 3.7.8
  * CCXT version: 1.42.47
  * Freqtrade Version: freqtrade develop
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. run freqtrade from commandline
  2. normally use  FreqUI, Dashboard, Trade, etc.
  3. from Telegram use /profit button
  
### Observed Results:

  * What happened?

Exception in the application, error message on stderr and in the log, probably incorrect operation - as a result, there is probably no indication of the profit of a given order

  * What did you expect to happen?

None

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

  // paste your log here
  2021-03-12 17:53:28,785 - freqtrade.rpc.telegram - INFO - Executing handler: _profit for chat_id: 1170104869
2021-03-12 17:53:28,797 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
Traceback (most recent call last):
  File "c:\tmp\freqtrade-develop\freqtrade\rpc\telegram.py", line 61, in wrapper
    return command_handler(self, *args, **kwargs)
  File "c:\tmp\freqtrade-develop\freqtrade\rpc\telegram.py", line 401, in _profit
    fiat_disp_cur)
  File "c:\tmp\freqtrade-develop\freqtrade\rpc\rpc.py", line 361, in _rpc_trade_statistics
    **if trade.close_profit >= 0:**
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
2021-03-12 17:53:30,902 - freqtrade.worker - INFO - Bot heartbeat. PID=5580, version='develop', state='RUNNING'

**Comment by jurekl** [comment]
Sorry, this is my first time reporting a problem with Freqtrade, I closed it by mistake :-)

**Comment by xmatthias** [comment]
i don't think the title corresponds to the topic ... 

the exception comes out of telegram - i wouldn't see how this is related to the ASGI exception (which is the webserver)

**Comment by jurekl** [comment]
The title can indeed be confusing, I copied it from the header / beginning of the log fragment describing the exception in the code.
As you can see, the error comes from line 361 in rpc.py, in the routine `_rpc_trade_statistics:

```
            if not trade.is_open:
                profit_ratio = trade.close_profit
                profit_closed_coin.append(trade.close_profit_abs)
                profit_closed_ratio.append(profit_ratio)
                if trade.close_profit >= 0:                             <==== line 361
                    winning_trades += 1
                else:
                    losing_trades += 1  
```

I do not know why and where this error occurs, but it seems to me that in this case it is worth checking in the code whether the value   **trade.close_profit** is not equal to None by chance...

I haven't explored ALL the source code of Freqtrade, but I can guess that this procedure is called from different places in the program's code, that's obvious.

The exception was signaled for me both when navigating the FreqUI web interface and using some Telegram keys, it seems related to the profit.

In my rush, I did not paste another section of the log showing this error on another occasion. At the time of writing this text, I refreshed the FreqUI page and immediately there was a long fragment in the log:

> 2021-03-12 19:03:54,190 - freqtrade.worker - INFO - Bot heartbeat. PID=5580, version='develop', state='RUNNING'
> 2021-03-12 19:04:54,200 - freqtrade.worker - INFO - Bot heartbeat. PID=5580, version='develop', state='RUNNING'
> 2021-03-12 19:05:54,554 - freqtrade.worker - INFO - Bot heartbeat. PID=5580, version='develop', state='RUNNING'
> 2021-03-12 19:06:54,564 - freqtrade.worker - INFO - Bot heartbeat. PID=5580, version='develop', state='RUNNING'
> 2021-03-12 19:07:54,575 - freqtrade.worker - INFO - Bot heartbeat. PID=5580, version='develop', state='RUNNING'
> **ERROR:    Exception in ASGI application**
> Traceback (most recent call last):
>   File "c:\python\python37\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
>     result = await app(self.scope, self.receive, self.send)
>   File "c:\python\python37\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
>     return await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\fastapi\applications.py", line 199, in __call__
>     await super().__call__(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\applications.py", line 111, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
>     raise exc from None
>   File "c:\python\python37\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
>     await self.app(scope, receive, _send)
>   File "c:\python\python37\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
>     await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\exceptions.py", line 82, in __call__
>     raise exc from None
>   File "c:\python\python37\lib\site-packages\starlette\exceptions.py", line 71, in __call__
>     await self.app(scope, receive, sender)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 566, in __call__
>     await route.handle(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 227, in handle
>     await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 41, in app
>     response = await func(request)
>   File "c:\python\python37\lib\site-packages\fastapi\routing.py", line 202, in app
>     dependant=dependant, values=values, is_coroutine=is_coroutine
>   File "c:\python\python37\lib\site-packages\fastapi\routing.py", line 150, in run_endpoint_function
>     return await run_in_threadpool(dependant.call, **values)
>   File "c:\python\python37\lib\site-packages\starlette\concurrency.py", line 34, in run_in_threadpool
>     return await loop.run_in_executor(None, func, *args)
>   File "c:\python\python37\lib\concurrent\futures\thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "c:\tmp\freqtrade-develop\freqtrade\rpc\api_server\api_v1.py", line 63, in profit
>     config.get('fiat_display_currency')
>   File "c:\tmp\freqtrade-develop\freqtrade\rpc\rpc.py", line 361, in _rpc_trade_statistics
>     if trade.close_profit >= 0:
> TypeError: '>=' not supported between instances of 'NoneType' and 'int'
> 2021-03-12 19:08:37,247 - uvicorn.error - **ERROR - Exception in ASGI application**
> Traceback (most recent call last):
>   File "c:\python\python37\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
>     result = await app(self.scope, self.receive, self.send)
>   File "c:\python\python37\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
>     return await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\fastapi\applications.py", line 199, in __call__
>     await super().__call__(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\applications.py", line 111, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
>     raise exc from None
>   File "c:\python\python37\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
>     await self.app(scope, receive, _send)
>   File "c:\python\python37\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
>     await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\exceptions.py", line 82, in __call__
>     raise exc from None
>   File "c:\python\python37\lib\site-packages\starlette\exceptions.py", line 71, in __call__
>     await self.app(scope, receive, sender)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 566, in __call__
>     await route.handle(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 227, in handle
>     await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 41, in app
>     response = await func(request)
>   File "c:\python\python37\lib\site-packages\fastapi\routing.py", line 202, in app
>     dependant=dependant, values=values, is_coroutine=is_coroutine
>   File "c:\python\python37\lib\site-packages\fastapi\routing.py", line 150, in run_endpoint_function
>     return await run_in_threadpool(dependant.call, **values)
>   File "c:\python\python37\lib\site-packages\starlette\concurrency.py", line 34, in run_in_threadpool
>     return await loop.run_in_executor(None, func, *args)
>   File "c:\python\python37\lib\concurrent\futures\thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "c:\tmp\freqtrade-develop\freqtrade\rpc\api_server\api_v1.py", line 63, in profit
>     config.get('fiat_display_currency')
>   File "c:\tmp\freqtrade-develop\freqtrade\rpc\rpc.py", line 361, in _rpc_trade_statistics
>     if trade.close_profit >= 0:
> TypeError: '>=' not supported between instances of 'NoneType' and 'int'
> **ERROR:    Exception in ASGI application**
> Traceback (most recent call last):
>   File "c:\python\python37\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
>     result = await app(self.scope, self.receive, self.send)
>   File "c:\python\python37\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
>     return await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\fastapi\applications.py", line 199, in __call__
>     await super().__call__(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\applications.py", line 111, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
>     raise exc from None
>   File "c:\python\python37\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
>     await self.app(scope, receive, _send)
>   File "c:\python\python37\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
>     await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\exceptions.py", line 82, in __call__
>     raise exc from None
>   File "c:\python\python37\lib\site-packages\starlette\exceptions.py", line 71, in __call__
>     await self.app(scope, receive, sender)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 566, in __call__
>     await route.handle(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 227, in handle
>     await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 41, in app
>     response = await func(request)
>   File "c:\python\python37\lib\site-packages\fastapi\routing.py", line 202, in app
>     dependant=dependant, values=values, is_coroutine=is_coroutine
>   File "c:\python\python37\lib\site-packages\fastapi\routing.py", line 150, in run_endpoint_function
>     return await run_in_threadpool(dependant.call, **values)
>   File "c:\python\python37\lib\site-packages\starlette\concurrency.py", line 34, in run_in_threadpool
>     return await loop.run_in_executor(None, func, *args)
>   File "c:\python\python37\lib\concurrent\futures\thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "c:\tmp\freqtrade-develop\freqtrade\rpc\api_server\api_v1.py", line 63, in profit
>     config.get('fiat_display_currency')
>   File "c:\tmp\freqtrade-develop\freqtrade\rpc\rpc.py", line 361, in _rpc_trade_statistics
>     if trade.close_profit >= 0:
> TypeError: '>=' not supported between instances of 'NoneType' and 'int'
> 2021-03-12 19:08:38,464 - uvicorn.error - **ERROR - Exception in ASGI application**
> Traceback (most recent call last):
>   File "c:\python\python37\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
>     result = await app(self.scope, self.receive, self.send)
>   File "c:\python\python37\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
>     return await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\fastapi\applications.py", line 199, in __call__
>     await super().__call__(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\applications.py", line 111, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
>     raise exc from None
>   File "c:\python\python37\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
>     await self.app(scope, receive, _send)
>   File "c:\python\python37\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
>     await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\exceptions.py", line 82, in __call__
>     raise exc from None
>   File "c:\python\python37\lib\site-packages\starlette\exceptions.py", line 71, in __call__
>     await self.app(scope, receive, sender)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 566, in __call__
>     await route.handle(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 227, in handle
>     await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 41, in app
>     response = await func(request)
>   File "c:\python\python37\lib\site-packages\fastapi\routing.py", line 202, in app
>     dependant=dependant, values=values, is_coroutine=is_coroutine
>   File "c:\python\python37\lib\site-packages\fastapi\routing.py", line 150, in run_endpoint_function
>     return await run_in_threadpool(dependant.call, **values)
>   File "c:\python\python37\lib\site-packages\starlette\concurrency.py", line 34, in run_in_threadpool
>     return await loop.run_in_executor(None, func, *args)
>   File "c:\python\python37\lib\concurrent\futures\thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "c:\tmp\freqtrade-develop\freqtrade\rpc\api_server\api_v1.py", line 63, in profit
>     config.get('fiat_display_currency')
>   File "c:\tmp\freqtrade-develop\freqtrade\rpc\rpc.py", line 361, in _rpc_trade_statistics
>     if trade.close_profit >= 0:
> TypeError: '>=' not supported between instances of 'NoneType' and 'int'
> **ERROR:    Exception in ASGI application**
> Traceback (most recent call last):
>   File "c:\python\python37\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
>     result = await app(self.scope, self.receive, self.send)
>   File "c:\python\python37\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
>     return await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\fastapi\applications.py", line 199, in __call__
>     await super().__call__(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\applications.py", line 111, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
>     raise exc from None
>   File "c:\python\python37\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
>     await self.app(scope, receive, _send)
>   File "c:\python\python37\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
>     await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\exceptions.py", line 82, in __call__
>     raise exc from None
>   File "c:\python\python37\lib\site-packages\starlette\exceptions.py", line 71, in __call__
>     await self.app(scope, receive, sender)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 566, in __call__
>     await route.handle(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 227, in handle
>     await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 41, in app
>     response = await func(request)
>   File "c:\python\python37\lib\site-packages\fastapi\routing.py", line 202, in app
>     dependant=dependant, values=values, is_coroutine=is_coroutine
>   File "c:\python\python37\lib\site-packages\fastapi\routing.py", line 150, in run_endpoint_function
>     return await run_in_threadpool(dependant.call, **values)
>   File "c:\python\python37\lib\site-packages\starlette\concurrency.py", line 34, in run_in_threadpool
>     return await loop.run_in_executor(None, func, *args)
>   File "c:\python\python37\lib\concurrent\futures\thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "c:\tmp\freqtrade-develop\freqtrade\rpc\api_server\api_v1.py", line 63, in profit
>     config.get('fiat_display_currency')
>   File "c:\tmp\freqtrade-develop\freqtrade\rpc\rpc.py", line 361, in _rpc_trade_statistics
>     if trade.close_profit >= 0:
> TypeError: '>=' not supported between instances of 'NoneType' and 'int'
> 2021-03-12 19:08:38,829 - uvicorn.error - **ERROR - Exception in ASGI application**
> Traceback (most recent call last):
>   File "c:\python\python37\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
>     result = await app(self.scope, self.receive, self.send)
>   File "c:\python\python37\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
>     return await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\fastapi\applications.py", line 199, in __call__
>     await super().__call__(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\applications.py", line 111, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
>     raise exc from None
>   File "c:\python\python37\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
>     await self.app(scope, receive, _send)
>   File "c:\python\python37\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
>     await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\exceptions.py", line 82, in __call__
>     raise exc from None
>   File "c:\python\python37\lib\site-packages\starlette\exceptions.py", line 71, in __call__
>     await self.app(scope, receive, sender)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 566, in __call__
>     await route.handle(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 227, in handle
>     await self.app(scope, receive, send)
>   File "c:\python\python37\lib\site-packages\starlette\routing.py", line 41, in app
>     response = await func(request)
>   File "c:\python\python37\lib\site-packages\fastapi\routing.py", line 202, in app
>     dependant=dependant, values=values, is_coroutine=is_coroutine
>   File "c:\python\python37\lib\site-packages\fastapi\routing.py", line 150, in run_endpoint_function
>     return await run_in_threadpool(dependant.call, **values)
>   File "c:\python\python37\lib\site-packages\starlette\concurrency.py", line 34, in run_in_threadpool
>     return await loop.run_in_executor(None, func, *args)
>   File "c:\python\python37\lib\concurrent\futures\thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "c:\tmp\freqtrade-develop\freqtrade\rpc\api_server\api_v1.py", line 63, in profit
>     config.get('fiat_display_currency')
>   File "c:\tmp\freqtrade-develop\freqtrade\rpc\rpc.py", line 361, in _rpc_trade_statistics
>     if trade.close_profit >= 0:
> TypeError: '>=' not supported between instances of 'NoneType' and 'int'
> 2021-03-12 19:08:55,025 - freqtrade.worker - INFO - Bot heartbeat. PID=5580, version='develop', state='RUNNING'
> 2021-03-12 19:09:55,057 - freqtrade.worker - INFO - Bot heartbeat. PID=5580, version='develop', state='RUNNING'
> 2021-03-12 19:10:55,672 - freqtrade.worker - INFO - Bot heartbeat. PID=5580, version='develop', state='RUNNING'
> 2021-03-12 19:11:55,683 - freqtrade.worker - INFO - Bot heartbeat. PID=5580, version='develop', state='RUNNING'

As we can see, the text **ERROR - Exception in ASGI application** appears several times here.

greetings

**Comment by jurekl** [comment]
I checked better now. After using the **/profit** key on Telegram, an excerpt from the log immediately appeared:

> 2021-03-12 19: 22: 31,297 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
> Traceback (most recent call last):
>    File "c: \ tmp \ freqtrade-develop \ freqtrade \ rpc \ telegram.py", line 61, in wrapper
>      return command_handler (self, * args, ** kwargs)
>    File "c: \ tmp \ freqtrade-develop \ freqtrade \ rpc \ telegram.py", line 401, in _profit
>      fiat_disp_cur)
>    File "c: \ tmp \ freqtrade-develop \ freqtrade \ rpc \ rpc.py", line 361, in _rpc_trade_statistics
>      if trade.close_profit> = 0:
> TypeError: '> =' not supported between instances of 'NoneType' and 'int'
> 

As you can see, the error is mentioned in the same place in the code. Telegram is already mentioned here.
Indeed, the title that I invented is not good, it does not reflect the essence of the problem, I do not know how to change it.

**Comment by xmatthias** [comment]
Did you modify something in the database manually?

The check that's done (`if not trade.is_open:`)  will be sufficient - as close_profit is assigned the moment the trade is closed - so this is a invalid state for this trade.

Please open the database and search for the trade in question 
``` sql
select * from trades where is_open = 0 and close_profit is null;
```

**Comment by jurekl** [comment]
Hi @xmatthias,

My adventure with Freqtrade lasts only a few days, so sometimes I do things that are not fully thought out, like most beginners :-)

One of those things was yesterday's manual nulling of an order from Freqtrade.
A moment after that, a boring series of repetitive log entries about one "incorrect" order appeared, I was convinced that this was the canceled order.
I don't remember now what the order was, or if I found the website https://www.freqtrade.io/en/latest/sql_cheatsheet/#fix-trade-still-open-after-a-manual-sell-on-the-exchange whether I decided myself
"fix" the situation with the interrupted job and interfere "manually" with the database. Anyway, I certainly did:

`UPDATE trades SET is_open = 0 WHERE id = 2;`

After that, the log entries for order # 2 stopped appearing, which I thought was a temporary "success", of course without going into the details. After that, I noticed the series of profit bugs that I described yesterday.
Now I can see that my intervention was only half done, the correct way is described in the SQL Helper page.

By answering your question directly:

1. Yes, I confirm manual database manipulation.

2. Execution of SQL query


```
.header ON

select * from trades where is_open = 0 and close_profit is null;
```

shows the record in question (id = 2):

> sqlite> select * from trades where is_open = 0 and close_profit is null;
> id | exchange | pair | is_open | fee_open | fee_open_cost | fee_open_currency | fee_close | fee_close_cost | fee_close_currency | open_rate | open_rate_requested | open_trade_value | close_rate | close_rate_requested | fee_open_cost | close_rate_currency_currency | fee_close | fee_close_cost | fee_close_currency | open_rate | open_rate_requested | open_trade_value | close_rate | close_rate_requested | close_open_costl | amount_pross_requested | close_profit_ab | amount_profit_ab | initial_stop_loss | initial_stop_loss_pct | stoploss_order_id | stoploss_last_update | max_rate | min_rate | sell_reason | sell_order_status | strategy | timeframe
> 2 | binance | ATOM / BTC | 0 | 0.00075135 | 4.104e-05 | BNB | 0.00075135 ||| 0.000338292682926829 | 0.0003383 | 0.00027760842449 ||||| 0.000279 | 0.82 | 0.82 | 2021-03-11 20: 35: 12.246136 | || 0.000304463414634146 | -0.1 | 0.000304463414634146 | -0.1 || 2021-03-11 20:36: 51.261254 | 0.0003445 | 0.0003303 ||| Strategy005 | 5

for simplicity:

`sqlite> select id, is_open, close_profit from trades where is_open = 0 and close_profit is null;`

> id | is_open | close_profit
> 2 | 0 |

Thank you for the fantastic program, I'm just getting to know it, but I'm already freaking out, especially since I have already noted my first, **VERY modest**, successes on the Binance exchange :-)

best regards,

jurekl

**Comment by xmatthias** [comment]
congratulations to your success :+1: 

That's the problem though :laughing: 

the cheatsheet does explain/contain how to fill all necessary columns for a closed trade - if you don't want / need the profits, the best course of action is to delete the trade alltogether (`delete from trades where id = xxx;` - `/delete xxx` via telegram).

While this problem can probably be solved (not raising an exception) - not having the "resulting" value there will still cause odd / unexpected results in the metrics ... and handling "manual changes" to all columns in the database is not feasible ... as then we could not rely on ANY value the database gives.

**Comment by jurekl** [comment]
Hi @xmatthias,
Thanks for explanation.
I confirm, remove the problematic record from the SQLite database, solves the problem.
greetings!
