### ISSUE TITLE
How to transform ignore a sell signal when buy signal is equal to 1 ? 

### ISSUE THREAD

**Issue by ViddelD** [freqtrade/freqtrade#4529]
Hi Everyone,
I'm not a dev and quite new to python.

So, i'm requesting your help with the code :)
## Describe your environment

  * Operating system: Ubuntu 20
  * Python Version: ___3.8.5CC__ (`python -V`)
  * CCXT version: ____21.0.1_ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __Last one
  
## Your question
Some time to time, i noticed that some buy and sell signals arrives at the exact same time. I would like to be able to prioritize one or the other during my backtesting. I tried to write a code by myself, but with no knowledge of python... it's not so easy.
Please be kind : 
I first tried to implement this kind of code within the sell signal between the Sell = 1 and the return dataframe of the def.

Please do not laugh too loud... :)
----------------------------------------
),
            'sell'] = 1
if self.populate_buy_trend:
            if self.populate_buy_trend in ('self', 'dataframe'):
                if ['buy'] in dataframe == 1 :
                    dataframe['sell'] in populate_sell_trend() == 0

return dataframe
-----------------------------------------------------------------------------------

I would, first, like to adapt the value of the sell signal and then during the testing be able to test between sell and buy value.
Thanks in advance for your time and your help !

Big thanks to the dev's for this incredible tool and piece of work.

Regards,
Vd

**Comment by xmatthias** [comment]
you cannot use "if" for dataframe operations.
It's a table (multiple rows) - not a value you can use "if" with (which would require one row/value).

most likely the easiest thing to do is to have something like `(dataframe['buy'] != 1) & (...)` in your populate_sell to surpress sell signals if a buy signal exists.

In general though, this most likely means that your buy and sell strategy generate similar signals - which is usually a sign that the signals are not particularily good (either one, or both) - as the strategy should detect EITHER that the price will most likely be raising (buy) - or that it'll fall (sell) ... not both at the same time (which would mean inconclusiveness.

**Comment by ViddelD** [comment]
Hi Matthias,

Sure y'r right. It's a particular case i'm trying to fix within the strat.
I'm trying your trick.

Thanks !

Vd
