### ISSUE TITLE
Something odd about the database

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#4531]
ft_order_side appears to be always identical with side on orders, even if the bid/ask settings are changed, unless I'm not aware of special circumstances on the order book and trade in real time that allow it to remain that way.

**Comment by xmatthias** [comment]
bid/ask settings determine how the order is priced. it will not change if you're buying or selling a pair.

`ft_order_side` can only be either buy, sell or stoploss, and has nothing to do with how you price the order.

**Comment by epigramx** [comment]
So I guess ft_order_side could be stoploss, and then 'side' would be sell. I saw 'side' and I thought it would refer to the bid/ask settings.

ok thanks.
