### ISSUE TITLE
confirm_trade_entry/exit during backtesting

### ISSUE THREAD

**Issue by Cybergrany** [freqtrade/freqtrade#4541]
Hello,

I'm not super experienced with python so maybe I'm missing something obvious here, so forgive me if that's the case!

I'd like to execute custom logic every time the buy or signal is executed. Let's say for example's sake change a boolean from `false` to `true` if certain indicator conditions are met when a sale is made, and then I'd like to check the value of that boolean before a buy is made.

The ideal way seems to be in the `confirm_trade_entry` or `confirm_trade_exit` methods, but neither of these seem to be called during backtesting. (And I'd like to make sure my logic works before going live)

Only workaround I can think of is making a dataframe of all the buy/sell outcomes in `populate_indicators`, and doing boolean checks on them, but that seems fairly convoluted for something so simple.

Is there any other way to run custom logic that I might be missing? 

Thanks in advance!

**Comment by xmatthias** [comment]
no, `confirm_trade_*` methods are currently not being used during backtesting.

**Comment by Cybergrany** [comment]
No worries, thanks for your response.
