### ISSUE TITLE
Jupyter Strategy Analysis of Strategy with Informative Pairs

### ISSUE THREAD

**Issue by sanderklous** [freqtrade/freqtrade#4542]
## Describe your environment

  * Operating system: OSX
  * Python Version: 3.9.1 (`python -V`)
  * CCXT version: 1.40.99 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I'm trying to run strategy.analyze_ticker() in my notebook and it doesn't add my indicators. It turns out that this is because my indicators are based on an informative pair. My strategy contains the statement: self.dp.get_pair_dataframe(), so I first check if self.dp exists and it doesn't. Can I create it with the ExchangeResolver? Or by running Backtesting from within the notebook? If I try, it fails with: "RuntimeError: This event loop is already running". See below for the trace.
Thanks,
-- Sander

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

RuntimeError                              Traceback (most recent call last)
<ipython-input-8-328f93069000> in <module>
      1 from freqtrade.optimize.backtesting import Backtesting
----> 2 backtesting = Backtesting(config)
      3 #backtesting.start()

~/freqtrade/freqtrade/optimize/backtesting.py in __init__(self, config)
     80         self.all_results: Dict[str, Dict] = {}
     81 
---> 82         self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
     83 
     84         dataprovider = DataProvider(self.config, self.exchange)

~/freqtrade/freqtrade/resolvers/exchange_resolver.py in load_exchange(exchange_name, config, validate)
     29         exchange = None
     30         try:
---> 31             exchange = ExchangeResolver._load_exchange(exchange_name,
     32                                                        kwargs={'config': config,
     33                                                                'validate': validate})

~/freqtrade/freqtrade/resolvers/exchange_resolver.py in _load_exchange(exchange_name, kwargs)
     51             ex_class = getattr(exchanges, exchange_name)
     52 
---> 53             exchange = ex_class(**kwargs)
     54             if exchange:
     55                 logger.info(f"Using resolved exchange '{exchange_name}'...")

~/freqtrade/freqtrade/exchange/exchange.py in __init__(self, config, validate)
    122 
    123             # Initial markets load
--> 124             self._load_markets()
    125 
    126             # Check if all pairs are available

~/freqtrade/freqtrade/exchange/exchange.py in _load_markets(self)
    293         try:
    294             self._api.load_markets()
--> 295             self._load_async_markets()
    296             self._last_markets_refresh = arrow.utcnow().int_timestamp
    297         except ccxt.BaseError as e:

~/freqtrade/freqtrade/exchange/exchange.py in _load_async_markets(self, reload)
    282         try:
    283             if self._api_async:
--> 284                 asyncio.get_event_loop().run_until_complete(
    285                     self._api_async.load_markets(reload=reload))
    286 

/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py in run_until_complete(self, future)
    616         """
    617         self._check_closed()
--> 618         self._check_running()
    619 
    620         new_task = not futures.isfuture(future)

/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py in _check_running(self)
    576     def _check_running(self):
    577         if self.is_running():
--> 578             raise RuntimeError('This event loop is already running')
    579         if events._get_running_loop() is not None:
    580             raise RuntimeError(

RuntimeError: This event loop is already running

**Comment by xmatthias** [comment]
Running backtesting from within a notebook is not supported (although there are ways to make it work eventually).

Depending on what you need from dataprovider, you should be able to assign it to the strategy directly without exchange or pairlists object.
while this will cause errors in certain methods (orderbook, current_pairlist) - it shouldn't be a problem for backtesting usually.

Now in backtesting, you shouldn't use the exchange methods (orderbook, ticker) anyway ... 


`IStrategy.dp = DataProvider(config, None, None)`, or assigning it to `strategy.dp` (usually you'll not need current-pairlist in what you're trying to do either).

**Comment by sanderklous** [comment]
Thanks Matthias that worked. 

Closing this.
