### ISSUE TITLE
Backtesting documents says dynamic stake amounts is an option

### ISSUE THREAD

**Issue by Botman-Hotman** [freqtrade/freqtrade#4544]
In the documentation here: https://www.freqtrade.io/en/latest/backtesting/

it says: 

_**Dynamic stake amount
Backtesting supports dynamic stake amount by configuring stake_amount as "unlimited", which will split the starting balance into max_open_trades pieces. Profits from early trades will result in subsequent higher stake amounts, resulting in compounding of profits over the backtesting period.**_

but when I try to run a backtest it says this:

freqtrade - ERROR - The value of `stake_amount` cannot be set as "unlimited" for backtesting.

Am I missing something or do I need to change to a different branch i.e developer and not stable?

  * Operating system: MacOSX
  * Python Version: 3.7 (`python -V`)
  * CCXT version: 1.42.19 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.2 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

**Comment by Botman-Hotman** [comment]
I changed to a more up to date developer and it worked.

**Comment by xmatthias** [comment]
the docs have a small hover box at the bottom right, where you can switch to the docs corresponding to the version you're using.

as you correctly noticed - unlimited stake is not available in backtesting in the released version - only in develop.
