### ISSUE TITLE
Ability to apply a weighted preference to hyperopt-loss functions?

### ISSUE THREAD

**Issue by samgermain** [freqtrade/freqtrade#4545]
* Operating system: Ubuntu 18.04.5 LTS
  * Python Version: Python 3.7.9
  * CCXT version: 1.42.19
  * Freqtrade Version: freqtrade develop-9530674

I'm running some hyperopts, and if I use the `hyperopt-loss` function `SharpeHyperOptLoss`, then my profits drop by more than half, but have a really good Objective value of about -500. If I decide that i don't want to cut my profits in half, and use the `OnlyProfitHyperOptLoss`, then I get an Objective value of about -8.

I don't want to cut my profits by that much, but I would be ok cutting them about 5-10% for an Objective value that get's below 100. It looks like right now I need to choose between one or the other though. In extreme cases, I could be sacrificing hundreds off my objective value for a 0.01% profit which is overtuned anyway.

Another way to do this could be that if you already know approximately what kind of percentage you want to profit, you could specify that percentage as an argument, and then the hyperopt could try to find the best Objective value on epochs with a minimum of the specified profit.

**Comment by xmatthias** [comment]
well every [loss function](https://www.freqtrade.io/en/latest/hyperopt/#loss-functions) has it's own benefits / drawbacks. Sharpe will in general look at optimizing for sharpe ratio - which clearly does not only look for profits, but also for minimized risk.

The 2 functions you mention are not the only ones freqtrade offers - and if you think one is missing, you can [create your own stoploss function](https://www.freqtrade.io/en/latest/advanced-hyperopt/#creating-and-using-a-custom-loss-function) to suit your needs.

If it's usefull (and you're willing to) - they can also be contributed back so they are then available for future users as well.

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.
