### ISSUE TITLE
Crash when trying to calculate tot_profit (unsupported operand type(s) for +: 'int' and 'NoneType')

### ISSUE THREAD

**Issue by mehdico** [freqtrade/freqtrade#4554]
* Operating system: MacOS BigSur
  * Python Version: 3.8.0
  * CCXT version: 1.42.66
  * Freqtrade Version: develop-ecc677ad

Got this error when trying to /custombuy on telegram (TRB/USDT) :

  ```
Traceback (most recent call last):
  File "freqtrade/freqtrade/rpc/telegram.py", line 61, in wrapper
    return command_handler(self, *args, **kwargs)
  File "freqtrade/freqtrade/rpc/telegram.py", line 617, in _forcebuy
    self._rpc._rpc_forcebuy(pair, price)
  File "freqtrade/rpc/rpc.py", line 593, in _rpc_forcebuy
    stakeamount = self._freqtrade.wallets.get_trade_stake_amount(
  File "freqtrade/freqtrade/wallets.py", line 193, in get_trade_stake_amount
    self.update()
  File "freqtrade/wallets.py", line 124, in update
    self._update_dry()
  File "freqtrade/freqtrade/wallets.py", line 74, in _update_dry
    tot_profit = sum([trade.close_profit_abs for trade in closed_trades])
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
2021-03-15 15:14:41,844 - freqtrade.rpc.telegram - INFO - Executing handler: _performance for chat_id: XXXXXXXX

  ```

also by running /state and /status i've got the same error.

Two previous custom buys were successful on the same session/dry run (one of them is active and the other one is closed by the custom stoploss function)

Stake settings:

  ```
    "max_open_trades": -1,
    "tradable_balance_ratio": 0.99,
    "stake_currency": "USDT",
    "stake_amount": 20,
    "dry_run": true,
    "dry_run_wallet": 1000,
  ```

My custom stoploss function :

  ```
    def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:

        if current_profit > 0.04:
            return (-0.04 + current_profit)
        return 1
  ```
initial stoploss => -0.15
use_custom_stoploss => True

also Trades table export is attached.

[trades_table.csv.zip](https://github.com/freqtrade/freqtrade/files/6141176/trades_table.csv.zip)

**Comment by xmatthias** [comment]
Your problem will most likely be the same as in #4528 - trying to close a trade manually without following the instruction properly.

**Comment by mehdico** [comment]
I didn't close any trade inside (using forcesell) or outside of the bot. also close_profit is not null in my case for the closed trade.

**Comment by xmatthias** [comment]
but `close_profit_abs`  will be ... (that's what the error says)
unfortunately the csv file you attached doesn't contain headers, which makes it almost impossible to know which column is which o confirm / have a look at what will be causing this.

**Comment by mehdico** [comment]
> but `close_profit_abs` will be ... (that's what the error says)

no also its not null.

> unfortunately the csv file you attached doesn't contain headers, which makes it almost impossible to know which column is which o confirm / have a look at what will be causing this.

Sorry for that, column names are the same order as database. this is the same file with column names : 

[trades_table2.csv.zip](https://github.com/freqtrade/freqtrade/files/6141785/trades_table2.csv.zip)

**Comment by mehdico** [comment]
This is my strategy : 

  ```
class CustomBuyC(IStrategy):

    minimal_roi = {
        "0": 100
    }

    use_custom_stoploss = True
    stoploss = -0.15

    timeframe = '1m'


    order_types = {
        "buy": "market",
        "sell": "market",
        "emergencysell": "market",
        "stoploss": "market",
        "stoploss_on_exchange": False,
        "stoploss_on_exchange_interval": 30,
        "stoploss_on_exchange_limit_ratio": 0.99,
    }


    def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:

        # raise stoploss by profit after 4% (first target)
        if current_profit > 0.04:
            return (-0.04 + current_profit)
        return 1


    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:


        return dataframe


    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
            ),
            'buy'] = 0

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
            ),
            'sell'] = 0

        return dataframe
  ```

all commands i ran: 

/forcebuy NULS/USDT
  ```
🔵 Binance: Buying NULS/USDT (#1)
Amount: 22.21000000
Open Rate: 0.90030000
Current Rate: 0.90030000
Total: (19.996 USDT, 19.877 USD)
  ```

/forcebuy 1INCH/USDT
  ```
🔵 Binance: Buying 1INCH/USDT (#2)
Amount: 5.11000000
Open Rate: 3.91240000
Current Rate: 3.91240000
Total: (19.992 USDT, 19.873 USD)
  ```

bot closing 1INCH/USDT by his custom stoploss function automatically
  ```
✳ Binance: Selling 1INCH/USDT (#2)
Amount: 5.11000000
Open Rate: 3.91240000
Current Rate: 4.07100000
Close Rate: 4.07100000
Sell Reason: trailing_stop_loss
Duration: 0:34:52 (34.9 min)
Profit: 3.85% (profit: 0.76965083 USDT / 0.765 USD)
  ```

then i ran:  /forcebuy TRB/USDT

ERROR OCCURRED


*note that I was on dry-run.

**Comment by xmatthias** [comment]
i currently can't see anything wrong in your database...


does this happen continuously (if you try to buy again)?
Does it recover with a restart of the bot? (so the trades are still there - but the instance is "fresh") ?

**Comment by mehdico** [comment]
> does this happen continuously (if you try to buy again)?

Yes
> Does it recover with a restart of the bot? (so the trades are still there - but the instance is 
"fresh") ?

Not testes on that one, but also today its happened to me for another strategy (with a new database) im running(in dry-run), **All the trades are open in the new one** (and its ok), but 
 after a few hours, when i ran /forcebuy or /state ... got same error , when i kill the bot and start it again (orders still in db) problem gone.

**Comment by xmatthias** [comment]
Please give the new version (just pushed, so give it a bit for CI to complete) a try.
