### ISSUE TITLE
Implement strategy based on x% profit a day

### ISSUE THREAD

**Issue by fintaro123** [freqtrade/freqtrade#4555]
## Your question
I want to implement a strategy that is based on the amount of x% profit I have during a day.
If the profit reaches above 1.1% it will automatically not buy any orders for **that day.**

1) I have already made a function for the calculation of the total profit of the closed trades using the below function and "counting" the profits

```
if self.config['runmode'].value in ('live', 'dry_run'):
     performance = Trade.get_overall_performance()
```

and set this "count" variable (not in above function) in the populate_buy_trend function with the condition "count" <= x% which works great because it make buy signals.

2) I now need to make sure that in the next day this count variable goes again to 0 and again make x% amount of profit.
I am not sure how I have to do this. Does anyone have any suggestions of how to handle this?

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
i don't think this will work - `get_overall_performance` will give you the performance of all pairs for the whole history - not for one day.

you'll probably need to fetch the trades for the current day and aggregate the profit yourself for what you need (by using the current day as filter, it'll also automatically reset after midnight.

**Comment by fintaro123** [comment]
> i don't think this will work - `get_overall_performance` will give you the performance of all pairs for the whole history - not for one day.
> 
> you'll probably need to fetch the trades for the current day and aggregate the profit yourself for what you need (by using the current day as filter, it'll also automatically reset after midnight.



So I have to use

```
if self.config['runmode'].value in ('live', 'dry_run'):
    trades = Trade.get_trades([Trade.pair == metadata['pair'],
                               Trade.open_date > datetime.utcnow() - timedelta(days=1),,
                               Trade.is_open.is_(False),
                ]).order_by(Trade.close_date).all()
    # Summarize profit for this pair.
    curdayprofit = sum(trade.close_profit for trade in trades)
```

which is already summing the open trades that are greater than the time now - 1 day  I think?

So I want to track all the trades of today so then I come up with the following code

```
import datetime

now_datetime = datetime.datetime.now()
end_of_day = now_datetime.replace(hour=23, minute=59, second=59, microsecond=999999)

   if self.config['runmode'].value in ('live', 'dry_run'):
            trades = Trade.get_trades([Trade.pair == metadata['pair'],
                                       Trade.open_date > end_of_day - timedelta(days=1)
                                       Trade.is_open.is_(False),
                                       ]).order_by(Trade.close_date).all()

    curdayprofit = sum(trade.close_profit for trade in trades)
```


Is this correct?

**Comment by xmatthias** [comment]
it doesn't look obviously wrong (but you'll need to make sure your commas are in palce) ... b
ut i think an easier way would be to replace hours / minutes / seconds to 0 instead of setting it to 23:59 and then subtracting 1 day...

**Comment by quantsirius** [comment]
@fintaro123 
Hi. Have you made this method work? Could you share the final code?
