### ISSUE TITLE
freqtrade hyperopt-show --best --print-json Output format error

### ISSUE THREAD

**Issue by wupeng1211** [freqtrade/freqtrade#4556]
freqtrade hyperopt-show --best --print-json

Output format error

-------------------------------------------------------------------------------------------------------
{
    "minimal_roi":
    {
        "0": 0.22340289743561562,
        "28": 0.07004935584425317,
        "40": 0.03010032822017973,
        "127": 0
    },
    "stoploss": -0.11393742618102942,
    "trailing_stop": "True",
    "trailing_stop_positive": 0.29874885845244786,
    "trailing_stop_positive_offset": 0.32463360867202673,
    "trailing_only_offset_is_reached": "False"
}

--------------------------------------------------------------------------------------------
The correct format is like this

{
    "minimal_roi":
    {
        "0": 0.22340289743561562,
        "28": 0.07004935584425317,
        "40": 0.03010032822017973,
        "127": 0
    },
    "stoploss": -0.11393742618102942,
    "trailing_stop": true,
    "trailing_stop_positive": 0.29874885845244786,
    "trailing_stop_positive_offset": 0.32463360867202673,
    "trailing_only_offset_is_reached": false
}

**Comment by wupeng1211** [comment]
freqtrade hyperopt-show --best

Epoch details:

    86/200:     76 trades. 56/13/7 Wins/Draws/Losses. Avg profit   1.76%. Median profit   0.93%. Total profit  26.72996498 USD ( 133.44Σ%). Avg duration 249.7 min. Objective: 0.55521


    # ROI table:
    minimal_roi = {
        "0": 0.22674,
        "30": 0.08387,
        "42": 0.03019,
        "144": 0
    }

    # Stoploss:
    stoploss = -0.11315

    # Trailing stop:
    trailing_stop = True
    trailing_stop_positive = 0.06688
    trailing_stop_positive_offset = 0.06984
    trailing_only_offset_is_reached = True

freqtrade hyperopt-show --best --print-json


Epoch details:

    86/200:     76 trades. 56/13/7 Wins/Draws/Losses. Avg profit   1.76%. Median profit   0.93%. Total profit  26.72996498 USD ( 133.44Σ%). Avg duration 249.7 min. Objective: 0.55521{
    "minimal_roi":
    {
        "0": 0.22673703833657066,
        "30": 0.08386968002691012,
        "42": 0.030190922193879144,
        "144": 0
    },
    "stoploss": -0.11315054912716724,
    "trailing_stop": "True",
    "trailing_stop_positive": 0.06688045333591246,
    "trailing_stop_positive_offset": 0.06983985040028488,
    "trailing_only_offset_is_reached": "True"}

**Comment by wupeng1211** [comment]
trailing_stop = True -->> trailing_stop = true

**Comment by wupeng1211** [comment]
@xmatthias

**Comment by xmatthias** [comment]
Feel free to either submit a pull request fixing this - or exercise in patience.

I understand what you mean - but it'll take some time to create a case so i can replicate this - and i didn't have time for it (also, i honestly don't see this as something urgent).

**Comment by wupeng1211** [comment]
freqtrade hyperopt-show --best --profitable --print-json --no-header | sed -e 's/"True"/true/g' | sed -e 's/"False"/false/g' > user_data/Best.json

**Comment by wupeng1211** [comment]
freqtrade hyperopt-show --best --profitable --print-json --no-header | sed -e 's/"True"/true/g' | sed -e 's/"False"/false/g' > user_data/Best.json

**Comment by wupeng1211** [comment]
freqtrade hyperopt-show --best --profitable --print-json --no-header | sed -e 's/"True"/true/g' | sed -e 's/"False"/false/g' > user_data/Best.json

**Comment by xmatthias** [comment]
I would actually think this is related to your version.

I've just tried this on the latest develop version, where the output seems like valid json to me.
```
{"trailing_stop":true,"trailing_stop_positive":0.05239898221966555,"trailing_stop_positive_offset":0.14257832128368336,"trailing_only_offset_is_reached":true}
```

The same output is also comming from the latest release (2021.2), so bes tmake sure to update your bot.
