### ISSUE TITLE
frequtrade Fiat display is missing 

### ISSUE THREAD

**Issue by kosik8686** [freqtrade/freqtrade#4557]
There is an issue with reocurring missing FIAT currecny display in Balance/Profit .

examples:

  ID  Pair      Since    Profit (PLN)
----  --------  -------  --------------
 102  XEM/BTC   40 min   0.43%
 103  NKN/BTC*  23 sec   0.18%

🔵 Binance: Buying NKN/BTC
Amount: 817.90314504
Open Rate: 0.00000262
Current Rate: 0.00000262
Total: (0.00214291 BTC, 0.000 PLN)

Daily Profit over the last 7 days:
Day         Profit BTC       Profit PLN    Trades
----------  ---------------  ------------  ---------
2021-03-15  0.00052229 BTC   0.000 PLN     17 trades
2021-03-14  0.00000923 BTC   0.000 PLN     32 trades
2021-03-13  0.00000248 BTC   0.000 PLN     30 trades
2021-03-12  -0.00001475 BTC  -0.000 PLN    14 trades
2021-03-11  0.00000000 BTC   0.000 PLN     0 trades
2021-03-10  0.00000000 BTC   0.000 PLN     0 trades
2021-03-09  0.00000000 BTC   0.000 PLN     0 trades

It's not displaying, after some time it's back again and again not displaying.

**Comment by xmatthias** [comment]
a) please fill out the issue template
b) we'll need the logs (most likely the logs from the time of startup) - if fiat conversion is not working, it's usually a problem connecting to coingecko, which causes the fiat convert to not initialize correctly.

As this has informative purpose only (so users can see it in a "comfortable currency", it'll have no impact on trading.

**Comment by kosik8686** [comment]
Case can be closed, it was due to lack performance of storage where freqtrade was installed.
