### ISSUE TITLE
Issue with "unlimited" stake amount

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#4558]
If the slots are full and one is released and it tries to buy immediately, it appears that it bugs out with "unable to create trade for pair X: Available balance Y (a negative) is lower than stake amount Z(another negative)". I suspect because according to the documentation it tries to do "currency_balance / (max_open_trades - current_open_trades)" which would be a division by zero.

**Comment by xmatthias** [comment]
Please fill out the issue template, otherwise there will be no further investigation, and the issue will be closed.

also, please provide logs, without them, it's difficult to determine what happened exactly.

**Comment by epigramx** [comment]
As there are no logs and I did not investigate the particular case further, I will close it to clean the room. If I encounter it again I might look into it further.
