### ISSUE TITLE
Is it possible to bring the OHLCV data as a logarithmic chart?

### ISSUE THREAD

**Issue by Botman-Hotman** [freqtrade/freqtrade#4559]
Would love to bring in the current data which is linear and use the log charts, anyone looked into this?

**Comment by xmatthias** [comment]
which charts are you talking about? freqUI? plot-dataframe?

**Comment by xmatthias** [comment]
Without more information - i will just say "no".
Neither in freqUI, nor in the plotting functions, it's currently possible to use log charts.
