### ISSUE TITLE
understanding a strategy

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4560]
Operating system: Debian 10
Python Version: Python 3.7.3
CCXT version: ccxt==1.42.66
Freqtrade Version: freqtrade develop-7e45af97

I am trying to get a better understanding of strategies, and the strategy I am currently using.

I know that this strategy has a 1% ROI, which means that if a trade reaches 1% profit or above, the bot will sell. I also know that if a trade goes below 30% the bot will also sell, and that the bot monitors 5 minutes candles.

After that it gets tricky. I know that the three parts below that, between "def populate_indicators" and "return dataframe" have something to do with monitoring the MACD and CCI indicators and have something to do with reaching 50 and 100...something.

Obviously I'm no trader, so can anyone explain in simple terms what this strategy does? Or point me to documentation with simple terms?

```
    minimal_roi = {
        "0":  0.01
    }

    stoploss = -0.3
    timeframe = '5m'

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        dataframe['macdhist'] = macd['macdhist']
        dataframe['cci'] = ta.CCI(dataframe)
        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                qtpylib.crossed_above(dataframe['macd'], dataframe['macdsignal']) &
                (dataframe['cci'] <= -50.0)
            ),
            'buy'] = 1
        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                qtpylib.crossed_below(dataframe['macd'], dataframe['macdsignal']) &
                (dataframe['cci'] >= 100.0)
            ),
            'sell'] = 1
        return dataframe
```

**Comment by xmatthias** [comment]
the buy signal will check that cci is below -50 - and that macd crosses the signal line from the bottom.

the sell signal is basically just the reverse - except that it's checking for cci > 100.

What these single indicators mean is best researched on pages like investopedia.com - which describe how the indicators are calculated, and how the can (potentially) be used.

**Comment by aristosv** [comment]
thanks for the information
