### ISSUE TITLE
QNAP Container Station - freqtrade

### ISSUE THREAD

**Issue by kosik8686** [freqtrade/freqtrade#4561]
## Describe your environment

QAP TS-451 - Intel CPU
## Your question

Was anyone able to install freqtrade using QNAP Cointainer Station? If yes I will be grateful for any advices.

**Comment by xmatthias** [comment]
if it supports docker, then it shouldn't be a problem (you'll just need to investigate if it's running a ARM or intel cpu).

if not - it should also work assuming it is able to run a python version >=3.7 (which is not always the case on these integrated boxes).

**Comment by kosik8686** [comment]
Case can be closed, it was docker issue related to issues with docker on LXC containers. So if someone want to use QNAP as freqtrade server it's better to use Virtualization Station that Linux station which is contenairized server itself.
