### ISSUE TITLE
I need to make the current bid and/or ask price into an indicator so that I can use it in the buy and sell signals.

### ISSUE THREAD

**Issue by beanofdoom** [freqtrade/freqtrade#4563]
As the titles says, I need to make the current bid and/or ask price into an indicator so that I can use it in the buy and sell signals.

I've read the documentation and have been searching through these issues for the answer for a few days now with no luck. Part of the problem is that I'm very new to all this and even when I think I've found what could be an answer I don't know how to implement it in the code.

For example, it seems my answer may have something to do with DataProvider, but where I've seen this mentioned in these comments and where it's discussed in the documentation I'm still not sure how to actually use it even after reading what's there! It's talking about non-whitelisted pairs, setting timeframes and merging stuff, warning not to try to pull data from the future, however that would work, and I don't get any of it!

I just simply want to be able to reference the current price of the pair in question in the strategy so that I can create a sell signal using it. How can I do this? Is there some way I can make the current price into an indicator?

Thanks in advance for any help/guidance you can provide.

**Comment by xmatthias** [comment]
honestly - define "current price"?
is one priceupdate per candle enough? Then use open (or close).

if you need it real-time, ou can use the [get orderbook](https://www.freqtrade.io/en/latest/strategy-customization/#orderbookpair-maximum) to get the latest bid and ask price.

Using orderbook is NOT possible during backtesting.
It would use the "now" price - which in the context of backtesting, would be looking into the future, as backtesting the last month is not allowed to know what the price is today.

If you knew what the price of BTC would be in 2021 back in 2015 - you'd for sure have put ALL your money into that pair ... and backtesting works the same way - as it analyzes historic data - so it cannot know what happens after that point in time (even though you yourself know this already).

Hope this didn't confuse you more than it helped ...

**Comment by beanofdoom** [comment]
Hey, thanks for your response!

Yeah, I do need it to update in real-time. when the bot runs at each 5 second iteration, it needs to check the current ask and if it is greater than or equal to a certain price I'll be getting from elsewhere it needs to trigger the sell.

I think I get where you're coming from, the orderbook checks prices from right now even if I'm back testing. Now I understand the warning against 'pulling data from the future'. If that were actually possible I couldn't understand why it wouldn't be a good thing, haha!

You've also confirmed my suspicion that the orderbook is the way to go, but this is a shame because I can't make heads or tails of how to code it. For example I saw the Complete Data-provider sample on that page and there are so many parts of it I don't get:

```

from freqtrade.strategy import IStrategy, merge_informative_pair
from pandas import DataFrame

class SampleStrategy(IStrategy):
    # strategy init stuff...

    timeframe = '5m'

    # more strategy init stuff..

    def informative_pairs(self):

        # get access to all pairs available in whitelist.
        pairs = self.dp.current_whitelist()
        # Assign tf to each pair so they can be downloaded and cached for strategy.
        informative_pairs = [(pair, '1d') for pair in pairs]
        # Optionally Add additional "static" pairs
        informative_pairs += [("ETH/USDT", "5m"),
                              ("BTC/TUSD", "15m"),
                            ]
        return informative_pairs

```

Okay first they've already defined the five minute timeframe for the strategy, why are they setting a 1 day timeframe for 'informative pairs'?

If I'm getting access to all pairs available in the white list, what happens if I'm running a dynamic whitelist of the top 100 coins by volume? Will it use that whitelist or the one in the config file?

I get what the snippet of code 'informative_pairs = [(pair, '1d') for pair in pairs]' is doing I think, but I don't understand the 'for pair in pairs' part

Moving on:


```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        if not self.dp:
            # Don't do anything if DataProvider is not available.
            return dataframe
```

So does this mean that the bot will not run at all if DataProvider is not available or just that it won't populate the dataframe with the indicators?

```
        inf_tf = '1d'
        # Get the informative pair
        informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf)
        # Get the 14 day rsi
        informative['rsi'] = ta.RSI(informative, timeperiod=14)

        # Use the helper function merge_informative_pair to safely merge the pair
        # Automatically renames the columns and merges a shorter timeframe dataframe and a longer timeframe informative pair
        # use ffill to have the 1d value available in every row throughout the day.
        # Without this, comparisons between columns of the original and the informative pair would only work once per day.
        # Full documentation of this method, see below
        dataframe = merge_informative_pair(dataframe, informative, self.timeframe, inf_tf, ffill=True)

```
 
What??

So they've already set the strat as running on 5m timeframe, then they have datprovider they set up on 1d, now they're setting it as one day again? I have no idea what _inf_tf = '1d'_ and then setting it as the timeframe is doing. This is already done, right? If they already set it as 1d then why do they have to set the timeframe as 1d again here?

Why are we merging stuff? What's that all about? Got NO idea. 

```
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['rsi'], 30)) &  # Signal: RSI crosses above 30
                (dataframe['rsi_1d'] < 30) &                     # Ensure daily RSI is < 30
                (dataframe['volume'] > 0)                        # Ensure this candle had volume (important for backtesting)
            ),
            'buy'] = 1
```

So they went through all the trouble of setting it up then they don't even use it! So I'm left with no idea how to use it in my buy or sell signals, there are no examples of this on the whole page!

Surely there has to be an easier way than all this! All I need is for the bot to check the current price on each iteration. It can do mad calculations with all these crazy indicators and most of that's a breeze to set up, but you're telling me I can't just get a dataframe['current_ask'] or something?

Again thanks for your response. I'm sorry if all of this seems painfully obvious to you. For me I don't think I've ever attempted anything that made me feel so stupid!

**Comment by xmatthias** [comment]
as mentioned above - please follow [this link](https://www.freqtrade.io/en/latest/strategy-customization/#orderbookpair-maximum) - and use the sample shown there.

The full dataprovider sample is NOT what you need - that shows the full example with informative pairs and whatnot.

what you need is (straight copy from the documentation)

```python
if self.dp:
    if self.dp.runmode.value in ('live', 'dry_run'):
        ob = self.dp.orderbook(metadata['pair'], 1)
        dataframe['best_bid'] = ob['bids'][0][0]
        dataframe['best_ask'] = ob['asks'][0][0]
```

You'll then have the current price in best_bid / best_ask.
for backtesting, best implement an "else" tree here and assign it with either open or close - there is not much more information available for backtesting.

**Comment by beanofdoom** [comment]
Thanks for that.

Yeah I was trying to look at that full sample because I don't know where to put these code snippets. They give lots of them but no real instructions.

Do I put this under 'populate indicators'? Do I need to do anything at the top to to get to get dataprovider or orderbook so that the bot will know what dp is? 

I've looked through all the samples I could find but no luck. I saw someone else post an issue where they'd done something like populate dataprovider or something of the like and put it above the populate indicators. 

They give these code snippets in the documentation, and I'm sure that for whoever wrote that stuff, and for lots of other people, it's obvious what to do with it. For me without the context of seeing it in a complete sample. I don't know where to put it or what else is necessary to make it work.

**Comment by xmatthias** [comment]
well you can use it in either of the 3 populate_ methods.

dp will be injected by freqtrade once the strategy is loaded, so it'll be available when you run it.

**Comment by beanofdoom** [comment]
Ah, I see!

So for that snippet of code you posted:

```
if self.dp:
    if self.dp.runmode.value in ('live', 'dry_run'):
        ob = self.dp.orderbook(metadata['pair'], 1)
        dataframe['best_bid'] = ob['bids'][0][0]
        dataframe['best_ask'] = ob['asks'][0][0]
```

I get now that can pop that-- or any of the chunks from that section in the documentation-- into the populate_indicators method and then use  dataframe['best_ask'] in my buy and sell signals now. That's huge! Thanks so much, it's like you've just given my species some super advanced alien tech we don't fully understand to do ourselves in with!

I'm trying to understand what it's doing, especially that first 'if' statement. Then the second if statement is saying something about the run mode? Basically it's checking to see if this is running 'live' or 'dry_run' and if it is then it'll do the stuff below, right? I don't get _self.dp.runmode.value in_

so then I get info from the order book for the pair and put that in 'ob', I'm assuming that 'bid' and 'ask' are in the order book but what's the _[0][0]_ all about?

**Comment by xmatthias** [comment]
Well checking what mode we're in, to prevent calling orderbook from backtesting / hyperopt (it's an active call against the exchange after all - so this should not be used with huge pairlists).

it's documented in ccxt (we don't touch this structure - just consume it)

You'll want to get the best bid / ask price - (hence the first [0]).
then, you'll want the price, not the volume (hence the 2nd [0])

**Comment by beanofdoom** [comment]
I very much appreciate your help, xmatthias. I hope I can return the favor someday!

**Comment by beanofdoom** [comment]
Hello to anyone seeing this: 

after receiving the wonderful advice given by xmatthias above, I copied the snippet of code:

```
if self.dp:
    if self.dp.runmode.value in ('live', 'dry_run'):
        ob = self.dp.orderbook(metadata['pair'], 1)
        dataframe['best_bid'] = ob['bids'][0][0]
        dataframe['best_ask'] = ob['asks'][0][0]
```

into the populate_indicators method and then attempted to use _dataframe['best_ask']_ in my sell signal. The bot will not run correctly. I keep getting an attribute error:

'stategyV1' object has no attribute 'dp'

Can anyone tell me what this is all about?

**Comment by xmatthias** [comment]
what version are you running?

**Comment by beanofdoom** [comment]
Not the most recent. I've been getting bad advice from this online course I've been taking. I'm going to delete everything and reinstall with the latest version of the main stable branch. Then I'll try re-coding everything from scratch. Thanks

**Comment by xmatthias** [comment]
it's problematic to use docs for one version, but the version you got is a different one, as obviously, the old version will not have the new stuff the docs explains.

You can select the proper version of the documentation in the bottom right corner of the documentation page though.

**Comment by beanofdoom** [comment]
Thank you, I will do. My plan is to start over again from the beginning and try to learn how to use this on my own using the documentation this time.
