### ISSUE TITLE
How to trade inverse contracts on bybit?

### ISSUE THREAD

**Issue by rnikitin** [freqtrade/freqtrade#4567]
* Operating system: max os
  * Python Version: 3.8.5
  * CCXT version: 1.42.66
  * Freqtrade Version: develop-79d4585d
  
## Your question

I want to trade inverse contracts on bybit, so I have, let's say, equivalent of $250 on each base coin (btc,eth,eos,xrp). I've set leverage X5, stake_amount to 1000$, stake_currency to "USD" and I want to trade btc/usd, eth/usd, eos/usd, xrp/usd pairs.

But when it's time to open a trade, I'm getting error:
Unable to create trade for BTC/USD: Available balance (0.0 USD) is lower than stake amount (1000 USD)
Which of course is not a surprise, USD is zero balance, since I want to trade inverse contracts and accumulate bitcoin. 

I found this issue, which defaults the coin to validate the wallet:
https://github.com/ccxt/ccxt/issues/6612

But this will not resolve an issue, since I still want to open an order higher then available balance and in the case above I'have to setup 4 instances of freqtrade for every pair.

So, how can I ignore the balance validation before opening the trade?

**Comment by xmatthias** [comment]
Freqtrade does not support margin / futures trading at the moment.
Freqtrade does not support bybit either (it should work for normal trading - but what you'll want to do for sure will not be possible, as it's a combination of using an unsupported exchange with features that don't exist with freqtrade yet).

The way i understand "inverse contracts" is that it's basically short trading - which put simply - is currently not supported on freqtrade.
