### ISSUE TITLE
/daily profit minus the loss of currently open trades

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4568]
## Describe your environment

Operating system: Debian 10
Python Version: Python 3.7.3
CCXT version: ccxt==1.42.66
Freqtrade Version: freqtrade develop-7e45af97
  
## Your question

This is a suggestion.

The /daily command shows the profit per day. It only considers closed trades though, not the currently open trades that might be -20% or -30%, which significantly affect the actual profit of the day.

An additional column on the /daily command, showing the closed trades profit, minus the loss of the currently open trades, might be beneficial. It would provide better clarity as to what the actual profit per day is.

**Comment by xmatthias** [comment]
in theory i don't disagree, but you can really only provide that for the current day, as we don't keep a history of all price-changes in the past in dry/live mode.
So adding this would only be effective for the latest day (all other days would have that column empty / show 0.0) - in which case you can also use `/profit` and get the same result.

**Comment by aristosv** [comment]
I was just thinking that at 00:00 when the bot wraps up the day and shows the profits, it could also take into consideration the status of the currently open trades. No need to keep historical data, just a snapshot of whats going on at 00:00.

(not sure what the RPC labels is, if this ticket can be closed, please go ahead and close it.)

**Comment by xmatthias** [comment]
RPC - related to telegram / rest-api.

at the moment, freqtrade does nothing special at 00:00 - all data comes by simply looking at the trade database (hence we don't know how much each open trade was worth yesterday).

**Comment by aristosv** [comment]
Great, thanks!
