### ISSUE TITLE
help.. Unable to initialize markets

### ISSUE THREAD

**Issue by deevirgie** [freqtrade/freqtrade#4572]
## Describe your environment

  * Operating system: win 10 64bit
  * Python Version: 3.9.2(`python -V`)
  * CCXT version: 1.43.27 (`pip freeze | grep ccxt`)
  * Freqtrade Version: docker-84ca9bd2 latest(`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

appdirs==1.4.4
distlib==0.3.1
filelock==3.0.12
six==1.15.0
virtualenv==20.4.3
## Your question

Please help what's wrong, 
- Unable to initialize markets
- BTC is not available as stake on Binance
[freqtrade.log](https://github.com/freqtrade/freqtrade/files/6168904/freqtrade.log)

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
sounds like you can't connect to binance for some reason ... 

usually, retrying works fine - but also check if you can get to the URL in the logs (https://api.binance.com/api/v3/exchangeInfo) from the machine where freqtrade is running.

You might also need to doublecheck your proxy settings ... if that applies, anyway

**Comment by deevirgie** [comment]
okay thanks for the help, I will try other provider networks
