### ISSUE TITLE
docker compose for pi image strategy with scipy error

### ISSUE THREAD

**Issue by tomismrkolj** [freqtrade/freqtrade#4576]
## Describe your environment

  * Operating system: _raspberryOS 64 bit___wirh docker
  * Python Version: _3.7____ (`python -V`)
  * CCXT version: __?___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade docker-0d5833ed__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
Tried to use strategy that uses scipy
*Explain the problem you have encountered*
freqtrade exits with error. On PC the same image (freqtrade develop) works ok in docker-compose.
### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
 freqtrade    | 2021-03-19 13:40:17,242 - freqtrade.freqtradebot - INFO - Starting freqtrade docker-0d5833ed
freqtrade    | 2021-03-19 13:40:17,300 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/mp.py due to 'No module named 'scipy''
freqtrade    | 2021-03-19 13:40:17,303 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/strategijaconsesus.py due to 'No module named 'technical''
freqtrade    | 2021-03-19 13:40:17,313 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'mp'. This class does not exist or contains Python code errors.
freqtrade    | 2021-03-19 13:40:17,313 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade    |     worker = Worker(args)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
freqtrade    |     self._init(False)
freqtrade    |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
freqtrade    |     self.freqtrade = FreqtradeBot(self._config)
freqtrade    |   File "/freqtrade/freqtrade/freqtradebot.py", line 66, in __init__
freqtrade    |     self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
freqtrade    |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 47, in load_strategy
freqtrade    |     extra_dir=config.get('strategy_path'))
freqtrade    |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 207, in _load_strategy
freqtrade    |     f"Impossible to load Strategy '{strategy_name}'. This class does not exist "
freqtrade    | freqtrade.exceptions.OperationalException: Impossible to load Strategy 'mp'. This class does not exist or contains Python code errors.

  ```

**Comment by xmatthias** [comment]
the raspberry docker image does not include scipy. 

it's a hyperopt dependency, and hyperopt is highly discouraged on a raspberry.

You can use the approach as documented [here](https://www.freqtrade.io/en/latest/docker_quickstart/#additional-dependencies-with-docker-compose) to install custom dependencies in your docker image.
