### ISSUE TITLE
Switch from Dev to Stable release

### ISSUE THREAD

**Issue by focamonca** [freqtrade/freqtrade#4577]
Operating system: Raspbian
Python Version: Python 3.7.3
Freqtrade Version: develop-0d5833ed
  
## Your question

I'd like to switch from dev to stable release.
How can I do?
Thanks

**Comment by xmatthias** [comment]
it depends on your installation method.
Either, you change the docker image tag from :develop_pi to :stable_pi - or you need to `git checkout stable` to get the stable branch.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
