### ISSUE TITLE
How to set up a bot using only tradingView webhooks for buying/selling

### ISSUE THREAD

**Issue by KaOzPoNs** [freqtrade/freqtrade#4582]
Hi guys, sorry for this basic question...

I'm new to freqtrade and I found a little confusing how to set up a bot...

My goal is to only use tradingview webhooks as sell and buy signals...
could you help me figure out how to run something like that?

where should tradingview be sending the messages?

in the documentations i found this example:
"webhook": {
        "enabled": true,
        "url": "https://maker.ifttt.com/trigger/<YOUREVENT>/with/key/<YOURKEY>/",
        "webhookbuy": {
            "value1": "Buying {pair}",
            "value2": "limit {limit:8f}",
            "value3": "{stake_amount:8f} {stake_currency}"
        },
        "webhooksell": {
            "value1": "Selling {pair}",
            "value2": "limit {limit:8f}",
            "value3": "profit: {profit_amount:8f} {stake_currency}"
        },
        "webhookstatus": {
            "value1": "Status: {status}",
            "value2": "",
            "value3": ""
        }
    },

but is not clear for me...
there is only limit type orders when using webhooks?

how should be filled the Json from tradingview to freqtrade? and what URL should i use on tradingView to send the alerts? 

Thanks for you help, and sorry for this dump question.

**Comment by xmatthias** [comment]
the webhooks freqtrade offers work the other way around.
Freqtrade will notify a webhook service about actions freqtrade took, but you cannot use webhooks to control what freqtrade does.

in short - freqtrade cannot consume tradingview webhooks, as explained in #2644.
