### ISSUE TITLE
Edge table is empty

### ISSUE THREAD

**Issue by jej** [freqtrade/freqtrade#4583]
* Freqtrade Version: develop

Hi,
Is there a known reason when edge returns an empty table? I tried different configurations but I always get the same result. What could be responsible of such situation?
Thx for your help.

edit: it seems Quickie is involved, as it works with another strategy. So the question becomes: what could avoid Quickie to work with edge test?

```

freqtrade edge --config myconf.json --timerange 20210215- --strategy Quickie

|       Pair |   Stoploss |   Win Rate |   Risk Reward Ratio |   Required Risk Reward |   Expectancy |   Total Number of Trades |   Average Duration (min) |
|------------+------------+------------+---------------------+------------------------+--------------+--------------------------+--------------------------|
|   BCH/BUSD |      -0.01 |       0.00 |                0.00 |                    inf |        -1.00 |                       39 |                       69 |
|   BTC/BUSD |      -0.01 |       0.00 |                0.00 |                    inf |        -1.00 |                       26 |                      137 |
|   BNB/BUSD |      -0.01 |       0.00 |                0.00 |                    inf |        -1.00 |                       35 |                      146 |
|     ...    |      -0.01 |       0.00 |                0.00 |                    inf |        -1.00 |                       50 |                       65 |

```

**Comment by xmatthias** [comment]
there's a ton of things that need to work right for edge to work (must use sell signal as primary sell method, ...).

Most likely, one of the parameters (expectancy, min-trades, ...) is too high / low - therefore edge determines to better not use this pair.

Edge can work great, but your strategy must be 100% compatible, otherwise it'll fail / simply not work.

**Comment by jej** [comment]
Ok, thanks for the explanations. Still have to go deeper in this freqtrade, it's great!!

**Comment by xmatthias** [comment]
Please consider edge an advanced feature - you'll need to fully (and thorowly) understand the edge documentation to be able to configure it to work with your strategy.

You'll also find it difficult to tune against a strategy you don't 100% understand / didn't write yourself ... at least that's my experience.

**Comment by jej** [comment]
Do you think it's better to look at hyperopts first? I have already a live bot running, just want to try to improve a bit and play with all of this...

**Comment by xmatthias** [comment]
in general, i'd say yes - edge will make almost every strategy act very conservative, as you'll end up with a very limited pairlist at most times (the pairlist is based on performance over the last few days).

it can work for some strategies, but will usually also make you miss on new opportunities - where a pair didn't show a particular pattern in the recent history.

**Comment by jej** [comment]
ok. really thanks for your explanations and great support everywhere here...
regards.
