### ISSUE TITLE
Preventing losses after a sudden drop of price during trailing_stop_loss

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#4587]
I had a trade on a casual trailing profit and suddenly it had a violent dump and the bot went on selling at that point with a very big loss (with reason 'trailing_stop_loss').

Can it be prevented by forcing it to never sell at a loss with reason 'trailing_stop_loss'?

PS. Order book was on

**Comment by epigramx** [comment]
I wonder if confirm_trade_exit() can do it, or if that too would go through with it in that case.

**Comment by xmatthias** [comment]
orderbook or not has nothing to do with it.

you can use a static stoploss until the pair is in profit, or has reached a certain trailing offset [as documented](https://www.freqtrade.io/en/latest/stoploss/#trailing-stop-loss-only-once-the-trade-has-reached-a-certain-offset).

It's a tradeoff (as always) - assuming it would then drop down to your real stoploss, then the loss will be substancially higher than what the trailing stop would've sold.

**Comment by epigramx** [comment]
Would confirm_trade_exit() prevent it from going through at a negative profit with trailing_stop_loss if it's set up accordingly? I really use trailing as a "bonus" and I explicitly never want it to sell at a loss. I have other ways to sell at a loss.

**Comment by xmatthias** [comment]
then keep stoploss stable until you reach a profit offset - so it's only starting to trail after 5% (with 3% offset for example).

**Comment by epigramx** [comment]
I want to sell with signaling, so I do not want to have anything selling by price action of only ticks unless it's a trailing profit.
To say it in practice: those massive dumps often recover immediately (e.g. in this case it recovered by 20% in seconds!).

**Comment by xmatthias** [comment]
in this case it might have - but always consider "what if it didn't".

price dropped below the trailing stop - so the bot sold. I consider this expected and correct behaviour.
Everything else (like - don't sell if it doesn't stay below for X minutes) will lead to missed stoplosses, and can mean 20% loss, instead of the stoploss that was set at 5%.

**Comment by epigramx** [comment]
I understand your way of thinking, but in this case I do have a way to exit at a loss and that's with technical analysis after a new candle.
I hope confirm_trade_exit() can do what I want (please let me know if it can't).

**Comment by xmatthias** [comment]
you don't want trailing stoploss - so simply don't enable trailing stoploss, or make sure it's only enabled once the trade is in profits.

**Comment by epigramx** [comment]
I may have been misunderstood. This was a trailing stop that was trailing at a profit and it was setup in custom_stoploss (only if there is profit). The problem occurred when a dump of the price within a few seconds caused the trailing_stop_loss to sell with a big loss (while in most other cases it would sell at a profit (albeit lower than the max)).

**Comment by xmatthias** [comment]
price broke below the stoploss - the bot did what it was supposed to do - sell.

it'll depend if you use stoploss on exchange or not  - if you do, then it's the exachange that did the right thing (They executed the stoploss order you placed).
If you don't - then freqtrade did what you told it to do - as price broke below the stop - it sold the pair.

**Comment by epigramx** [comment]
I do not think it was a bug hence it's in questions, just asking how to prevent it behaving like this. I've set up the function mentioned above and I hope it's enough.

**Comment by moinonin** [comment]
I have gone through the post and the comments. I know the problem you are experiencing. If indeed you have other ways to exit but somehow still want to use trailing positive loss, then you want to do the following:
1. Space well where the trailing starts.
2. Decide which order type to use for stop loss. If indeed 100% bounce back after a few seconds, then maybe limit orders might help. But markets are tricky, it might have been necessary to release the asset or it will get to the lowest limit price. In that case market orders are recommended.
3. If your intelligent method of selling with negative is perfect then why not set a crazy initial stop loss like 20%? Then ensure all these methods are working

**Comment by epigramx** [comment]
These flukes are not saved with a -20% since this example has an extremity of ~40% that quickly recovered by more than 20% within only seconds.
I think we're beyond the scope of this project talking about it but I think while the probability of it becoming worse isn't 0 it's likely <50%.
