### ISSUE TITLE
Some question about bot buying and selling behavior, why is it buying mid candle?

### ISSUE THREAD

**Issue by beanofdoom** [freqtrade/freqtrade#4588]
My bot seems to be buying mid candle and I don't know why. All the settings in the config (see below) seem to indicate that it should no longer be buying 30 seconds after the candle is formed. I've noticed this behavior when just starting the bot. Sometimes I'll notice buy orders initiating at h:03, for example, when it's on a 5m timeframe. Nothing in the buy signal could be creating this behavior, it's all based on close, open, high and low prices of the preceding candle and the one preceding it. 

I've also noticed this behavior when force selling. It'll immediately start buying into new positions based on my buy indicators.

For my strategy to work it needs to get in as close to the close of the previous candle as possible. the buy signal is no longer relevant 30 seconds after the candle closes, let alone 3 minutes!

I'm nervous about using process_only_new_candles because my sell signal uses data providers and actually is expected to occur mid-candle. 

I think my question is about the behavior of the thing. Why is it buying three minutes sometime after the new candle when I've told it to stop after 30 seconds and will the process_only_new_candles mess up my sell signal?

```
{
    "max_open_trades": 15,
    "stake_currency": "BTC",
    "stake_amount": 0.01,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "5m",
    "dry_run": true,
    "cancel_open_orders_on_exit": true,
    "process_only_new_candles": false,
    "unfilledtimeout": {
        "buy": 1,
        "sell": 30
    },
    "bid_strategy": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": true,
        "ignore_buying_expired_candle_after": 30
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
        "pair_whitelist": [
          "ETH/BTC",
          "LTC/BTC",
          "ETC/BTC",
          "DASH/BTC",
          "ZEC/BTC",
          "XLM/BTC",
          "POWR/BTC",
          "ADA/BTC",
          "XMR/BTC",
          "BCH/BTC",
          "BNB/BTC",
          "LINK/BTC",
          "DOT/BTC",
          "XRP/BTC",
          "UNI/BTC",
          "EOS/BTC",
          "AAVE/BTC",
          "GRT/BTC",
          "XTZ/BTC",
          "ALGO/BTC",
          "LUNA/BTC",
          "QTUM/BTC",
          "ATOM/BTC",
          "SNX/BTC",
          "YFI/BTC",
          "NEO/BTC",
          "SOL/BTC",
          "KNC/BTC",
          "THETA/BTC",
          "SXP/BTC",
          "SUSHI/BTC",
          "OMG/BTC",
          "EGLD/BTC",
          "IOTA/BTC",
          "FIL/BTC",
          "BAT/BTC",
          "BAND/BTC",
          "1INCH/BTC",
          "OCEAN/BTC",
          "RUNE/BTC",
          "REN/BTC",
          "CRV/BTC",
          "SKY/BTC",
          "WAVES/BTC",
          "XEM/BTC",
          "AVAX/BTC",
          "ZRX/BTC",
          "ICX/BTC",
          "ZIL/BTC",
          "MANA/BTC",
          "ALPHA/BTC",
          "BQX/BTC",
          "LSK/BTC",
          "TOMO/BTC",
          "SAND/BTC",
          "FET/BTC",
          "ONT/BTC",
          "COTI/BTC",
          "CVC/BTC",
          "DNT/BTC",
          "LTO/BTC",
          "BTG/BTC",
          "REP/BTC"
        ],
        "pair_blacklist": [
        ]
    },
    "pairlists": [
        {"method": "VolumePairList",
         "number_assets": 100,
         "sort_key": "quoteVolume",
         "refresh_period": 1800
       }
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": false,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "jwt_secret_key": "somethingrandom",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "SuperSecurePassword"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```

**Comment by xmatthias** [comment]
@beanofdoom first of all, you did copy your exchange API keys (and telegram keys) to the issue. I've now removed the info from above, however, Please make sure to **IMMEDIATELY** revoke the exchange keys - as they are still available in the message history for everyone to see (and i don't think i can prevent that from happening).

**Comment by xmatthias** [comment]
`process_only_new_candles` is not there to prevent buying intra-candle, but to prevent analyzing the same dataframe over and over again every 5 seconds for the whole duration of the candle.
It makes sense to use, unless you use real-time information like the orderbook, or a faster informative pair in your strategy.

What you are looking for is `ignore_buying_expired_candle_after`, which will make the bot ignore "late" buy signals (expired signals) [relevant docs](https://www.freqtrade.io/en/latest/configuration/#ignoring-expired-candles).

**Comment by beanofdoom** [comment]
> your exchange API keys (and telegram keys) to the issue. I've now removed the info from above, however, Please make sure to **IMMEDIATELY** revoke the exchange keys - as they are still available in the message history for everyone to see (and i don't think i can prevent that from happening).

aw man, that was really stupid! Thanks. I've deleted the API key. Will the telegram key be an issue? I don't even think I know how to delete that.

**Comment by beanofdoom** [comment]
> to prevent buying intra-candle, but to prevent analyzing the same dataframe over and over again every 5 seconds for the whole duration of the candle.
> It makes sense to use, unless you use real-time information like the orderbook, or a faster informative pair in your strategy.
> 
> What you are looking for is `ignore_buying_expired_candle_after`, which will make the bot ignore "late" buy signals (

okay thanks.

But i have the ignore buying expired candle after set to 30 seconds as you can see above, I'm still getting intra candle buys well after that 30 second window has closed.

**Comment by xmatthias** [comment]
then you might be at a version that doesn't support this yet.

When the bot starts, it'll include something like `Strategy using ignore_buying_expired_candle_after:` if it does support it.

Telegram might not be that much of an issue - but someone else could take control of your telegram bot and send you messages.
You should be able to delete the bot via botfather, and obviously you'll then need to recreate a new bot.

**Comment by beanofdoom** [comment]
okay. in that small amount of time I had the exchange keys here some psycho did initiate a a btc to doge trade. I lost almost a grand all said and done. That was an expensive lesson but one I'll certainly never make again.

**Comment by xmatthias** [comment]
I'm sorry to hear that. 
It'll not be a loss i guess - just that now you own doge, which you may or may not want to do ...

**Comment by beanofdoom** [comment]
No, even that would have given me a chance. This savage bought and immediately sold at a loss, market ordered all my btc in and then market ordered it all out. Buys averaged 0.00000101, sells averaged 0.00000100. $953 lost at current rate. It seems I got unlucky. It wasn't someone just playing around, it was someone being mean. Anyway I'm not above paying for an education this was an expensive but important one.

**Comment by beanofdoom** [comment]
as for the version, when I ask for that on the command line I'm getting:

freqtrade develop-76ca3c21

do I need a different version to make this work?

**Comment by beanofdoom** [comment]
deleted the telegram token too, btw, just to be on the safe side.

**Comment by xmatthias** [comment]
i'm sorry for that - i tried to "hide" it - but once it's out there ....

telegram can't have financial consequences (i think) - just anoying ones.

That version should have it - what does the (startup) log tell you?

**Comment by beanofdoom** [comment]
I'm just glad you found it and alerted me when you did. You did everything you could've; the mistake was mine. As bad as it was it could've been a lot worse. I'm just chalking it up to a valuable lesson learned therefore. I already knew those keys were sensitive, I just forgot to remove them. Dumb mistake. I don't imagine I'll ever forget that again. So that money wasn't completely wasted. 

As for the startup log, it's showing the expired candle rule rule to be in effect:

`2021-03-22 15:36:03,890 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_buying_expired_candle_after' with value in config file: 30.` 

Truth be told it seems to be back to behaving right now. I don't know what the problem was last night. Nothing's changed in terms of settings, it was just buying intra candle when it shouldn't have been. Now it's back to behaving normally. 

I guess for now I'll just keep testing and re-open if this issue if the intra-candle buying behavior returns.

Thanks!
