### ISSUE TITLE
Binance exceeded the API request limit while downloading backtesting data

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4595]
## Describe your environment

  * Operating system: Debian 10
  * Python Version: Python 3.7.3
  * CCXT version: ccxt==1.43.89
  * Freqtrade Version: freqtrade develop-7adfa0cf
  
## Your question

I want to do some backtesting, so I run this command to download pair data. There's 194 pairs in config.json.
`freqtrade download-data --c config.json --timeframes 5m --days 365`

After downloading data for about 15 pairs, I got his message. Obviously I've exceeded the API request limit.

```
2021-03-23 10:26:14,181 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "binance 429 Too Many Requests {"code":-1003,"msg":"Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API."}"
2021-03-23 10:26:14,181 - freqtrade.exchange.common - WARNING - retrying _async_get_candle_history() still for 4 times
2021-03-23 10:26:14,181 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 1
```

What can I do to successfully download this data? There's a suggestion for using websocket in the error. Would that work? Any guidelines on how to use it with freqtrade? Or any other alternatives?

Thanks

**Comment by aristosv** [comment]
I think this is relevant

```
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": false,
            "rateLimit": 500,
            "aiohttp_trust_env": false
```

**Comment by xmatthias** [comment]
You've got ratelimit disabled on async, so obviously you'll run into this error (downloading data uses async).
 
All example configurations we provide have it enabled, as it'll protect you from it.
Please reenable the ratelimit (at least for downloading data) or accept that it will not work.

with this configuration, you might also encounter problems in real trading ... depending on the number of pairs (and timeframe) you're using.

**Comment by aristosv** [comment]
Thanks for the information. I checked "config_full.json.example" and it's actually disabled. Maybe an oversight.

<img width="444" alt="Greenshot 2021-03-23 11 42 08" src="https://user-images.githubusercontent.com/528302/112126136-d0f15c00-8bcc-11eb-9ba0-3ed02c038f31.png">
