### ISSUE TITLE
Arbitrage trading possibility with Freqtrade

### ISSUE THREAD

**Issue by mathias5986** [freqtrade/freqtrade#4597]
Hello,

Does Freqtrade already support some trading between 2 exchanges (arbitrage trading) ? 
If it is not the case, which bot/software would you recommend to make this possible?

**Comment by xmatthias** [comment]
Freqtrade does not support this at the moment, and it's also not really planned - as the architecture needed for arbitrage trading would be rather different.

i also don't know any other bot which can do this - but i guess a simple google search for "arbitrage bot open source" should yield some results.
