### ISSUE TITLE
status table - show the number of days, not weeks

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4598]
## Describe your environment

Operating system: Debian 10
Python Version: Python 3.7.3
CCXT version: ccxt==1.43.89
Freqtrade Version: freqtrade develop-7adfa0cf
  
## Your question

At 10:46am this trade shows up as being open for a week.
<img width="962" alt="11" src="https://user-images.githubusercontent.com/528302/112310052-cad2ac80-8cac-11eb-9dbf-aabcc8d3078e.png">

Almost an hour later when selling it, it's actually shown that it's been open for more than 12 days.
<img width="963" alt="22" src="https://user-images.githubusercontent.com/528302/112310175-efc71f80-8cac-11eb-9f5a-99f443ef4a8f.png">

Is there a way to configure the bot to show the number of days on `/status table` instead of the weeks?

**Comment by xmatthias** [comment]
No, "humanization" of the timeperiods is handled by arrow, not by freqtrade directly.

while it seems to be possible to specify which granularity is used - this is not configurable - and will not make sense either - as you can be "stuck" in a trade for months (even though you don't expect to) - so picking a reliable format will be difficult.

Also, the first is actually displaying the "time ago" - while the 2nd shortens a duration - and i assume arrow uses slightly different algorithms for each of these.

**Comment by aristosv** [comment]
Just as an fyi, because i think its relevant. Even though its the third day running this new bot, the stats show that the first trade was opened a day ago. Not that its a big deal, i just thought it would be good to mention.

![8E2EFF0A-D4D4-40C7-9FF9-6DBE9A2DCAA7](https://user-images.githubusercontent.com/528302/112743314-04eac980-8f9f-11eb-85c5-96a84cb7845b.png)

![793030F4-8E6A-4665-BE7F-E5A9AE663A0A](https://user-images.githubusercontent.com/528302/112743319-12a04f00-8f9f-11eb-9faa-d8e8b2437f41.png)
