### ISSUE TITLE
Can't install using ./start -i without docker on a VPS

### ISSUE THREAD

**Issue by AceVik** [freqtrade/freqtrade#4599]
## Describe your environment

  * Operating system: Ubuntu Server 18.04
  * Python Version: 3.9
  * CCXT version: "command delivers empty string" (`pip freeze | grep ccxt`)
  * Freqtrade Version: not installed
 

### Steps to reproduce:

  1. Run `sudo add-apt-repository ppa:deadsnakes/ppa && apt update`
  2. Follow installation guide up here: https://www.freqtrade.io/en/latest/installation/#install-necessary-dependencies 
  (Using development branch)
  3. After executing command `./setup.sh -i` encounter bug:
  ```
  /usr/bin/python3.9
using Python 3.9
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 29, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 23, in <module>
    from pip.locations import (
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 9, in <module>
    from distutils import sysconfig
ImportError: cannot import name 'sysconfig' from 'distutils' (/usr/lib/python3.9/distutils/__init__.py)
pip not found (called as 'python3.9 -m pip'). Please make sure that pip is available for python3.9.
````
- Fix it using command: `apt install python3.9-distutils`
4. Reexecute `./setup.sh -i`
  
### Observed Results:

  * What happened?
  After this message, independend how you answer:
```
Reset git branch? (This will remove all changes you made!) [y/N]?
- Deleting your previous virtual env
```
I become the following error:
```
Error: Command '['/root/freqtrade/.env/bin/python3.9', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Could not create virtual environment. Leaving now
```

### Relevant code exceptions or logs
Node: This is the 3rd run of `./setup.sh -i`, on prev run it also compiled stuff.

  ```
 > ./setup.sh -i
/usr/bin/python3.9
using Python 3.9
-------------------------
Installing mandatory dependencies
-------------------------

Debian/Ubuntu detected. Setup for this system in-progress
OK:1 ftp://ftp.stratoserver.net/pub/linux/ubuntu bionic InRelease
OK:2 http://archive.ubuntu.com/ubuntu bionic InRelease
OK:3 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
OK:4 ftp://ftp.stratoserver.net/pub/linux/ubuntu bionic-updates InRelease
OK:5 ftp://ftp.stratoserver.net/pub/linux/ubuntu bionic-security InRelease
Paketlisten werden gelesen... Fertig
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
autoconf ist schon die neueste Version (2.69-11).
build-essential ist schon die neueste Version (12.4ubuntu1).
libtool ist schon die neueste Version (2.4.6-2).
make ist schon die neueste Version (4.1-9.1ubuntu1).
pkg-config ist schon die neueste Version (0.29.1-0ubuntu2).
git ist schon die neueste Version (1:2.17.1-1ubuntu0.8).
wget ist schon die neueste Version (1.19.4-1ubuntu2.2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
ta-lib already installed, skipping

----------------------------
Reseting branch and virtual env
----------------------------
Reset git branch? (This will remove all changes you made!) [y/N]?
- Deleting your previous virtual env

Error: Command '['/root/freqtrade/.env/bin/python3.9', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Could not create virtual environment. Leaving now
  ```

**Comment by xmatthias** [comment]
it's not clear to me why you would be getting this ... might be a permission issue.

You should try to create the virtualenv yourself with `python3.9 -m venv .env` (which is technically the command that's being executed).

Hopefully this will raise a few more errors / outputs - as the above is ... not quite telling...

**Comment by AceVik** [comment]
It seems, this command couses the error:

```
> python3.9 -m venv .env
Error: Command '['/root/freqtrade/.env/bin/python3.9', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

(Running as root all the time)

**Comment by xmatthias** [comment]
I honestly don't know. 

This sounds like a python installation problem to me - which we cannot support (as open source project, it's peoples free time that goes into supporting people - and this is simply not in scope for freqtrade).

As python3.9 is not natively on Ubuntu Server 18.04, i would think that you'll need to research this in combination with the way you used to install python3.9 on your machine.
Potentially, you'll need to use another method to install python3.9, or use a lower version (like python3.8).

**Comment by AceVik** [comment]
Yep, i am with you. I think purge python3.9 and use the distro default python3 version should work (i will try it out).

**Comment by xmatthias** [comment]
18.04 "might" be too old to have a supported python3 (we need at least 3.7 due to some dependency min-versions) - but i'm not sure as it's been a while i used ubuntu.
