### ISSUE TITLE
Can we move these 3 settings to the custom strategy file too? (make it optional) 

### ISSUE THREAD

**Issue by seansan** [freqtrade/freqtrade#460]
Can we move these 3 settings to the custom strategy file too? (make it optional) 

    "bid_strategy": {
        "ask_last_balance": 0.8
    },
        "use_sell_signal": true,
        "sell_profit_only": true

**Comment by glonlas** [comment]
Yes, I am thinking about it as well.

**Comment by shusso** [comment]
tracked in #848
