### ISSUE TITLE
Backtesting use of min_roi_reached_entry

### ISSUE THREAD

**Issue by werkkrew** [freqtrade/freqtrade#4600]
https://github.com/freqtrade/freqtrade/blob/ee82d36bef4cbfae910fa822b3ef2ab775d21bda/freqtrade/optimize/backtesting.py#L210

If I am reading this right, backtesting is essentially pulling the corresponding value from the ROI table if sell_reason is ROI.

Is this compatible with `ignore_roi_if_buy_signal = True`?

Let me elaborate:

Assume I have the following minimal_roi table:

```python
minimal_roi = {
    "0": 0.01
}

ignore_roi_if_buy_signal = True
```

And I am using a purposely sticking buy signal to take advantage of this.  To keep things simple lets pretend its an SSL Channel buy where if sslup > ssldown we buy.

A buy happens, trade profit goes up to +10% and does not sell to ROI due to the above setting, buy signal disappears because sslup < ssldown now - profit is +10%, roi table sells at 1%, so the sell happens.

In this case, does the backtesting module assume the profit for that trade was only 1% due to the layout of the ROI table?

If not, can you explain how it works?  If so, is there anything that can be done, such as using a current_profit calculation instead of the roi table?

**Comment by xmatthias** [comment]
This function got nothing to do with `ignore_roi_if_buy_signal`.

The function you linked is for getting the close rate in backtesting - which uses slightly different logic depending on the sell signal (if ROI is 5%, but candle high + close would be 6% - we don't want the sell to be registered as 6%, but as 5%, as ROI would realistically trigger there assuming the candle made a move from 4% to 6%).

it's only called once the (simulated) sell took place (in backtesting) - so you're already out of the trade by that point.

the logic if a sell should or should not happen is in `interface.py` - so if `ignore_roi_if_buy_signal` surpresses a ROI sell - then the sell simply will not happen (or rather, it'll be delayed until either the buy signal disappears, or ROI falls below the threshold again - or both) - so you'll never reach this method if the sell was surpressed.

**Comment by werkkrew** [comment]
Yes I think I understand that, but I am trying to sort out if the "close rate" or profit getting recorded by the backtest.  Is it taking anything into account related to the current profit or candle value or simply assuming the corresponding value in the ROI table is what the profit was for the purposes of the backtest?

**Comment by xmatthias** [comment]
for most sell types, it's pretty simple (it's the candle's open price).

for ROI however, it's slightly more complicated.
If ROI is -1 (always sell at this moment) - it'll use the candle's open price (imitating a sell signal).

if ROI came into effect at that candle open (so you're using `60: 0.05` and the closing candle is the 12th 5m candle (which means a trade duration of 60) - it'll use the candle's open rate.
This is to cover cases where ROI "drops down" to this level - for example - my ROI settings are `{0:0.1, 60:0.5}` - and the profit after 59 minutes is 7% - you'd expect a sell at 7% (5% roi came into effect at this moment) - not at 5% (which can even be below the candle - and would not be realistic).

The last "fallback" is the max between the profit (ROI) and the candle's low - to avoid sells below the candle. This case should however realistically not happen too often unless ROI is configured oddly abusing it as kindof a stoploss (like with `120: -0.5`).

Obviously, if you "prevent" ROI with buy signal and ride the trend higher, low will still be used (ROI didn't come into effect on this candle - and the profit may be 10% - 5% above the initial 5% roi) - so "low" will be used.

**Comment by werkkrew** [comment]
Okay, I think I understand.  So you are confident that backtest returns a reasonable realistic profit value for things sold by sell_reason "roi" but at a significantly higher price than the current ROI table would dictate in the case of a sticking sell?

**Comment by xmatthias** [comment]
yes(ish) ... it'll depend on how the "selling" candle looks like - if there's a long spike of low - it'll be down to "roi" again, even if open/close where up (but in reality, you wouldn't know where it sold either - as price could've dropped to that low 1s after the open price).

Otherwise (if the full candle is significantly above the ROI margin) - it is going to use low. as you said "significantly" - it'll not affect you much, as significant i'd say 10% above roi and up - in which case 2-3% (open to low) will not hurt you.

**Comment by werkkrew** [comment]
Ok, thanks for clarifying!
