### ISSUE TITLE
Odd behavior with get_tickers() and RequestTimeout

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#4604]
This is probably a quirk of ccxt but I don't want to use their tracker because I don't use their project directly: it appears that I was getting "WARNING - get_tickers() returned exception: "Could not load tickers due to RequestTimeout.[..]" while trading itself was continuing as normal with the exception that it was failing to print a representation in fiat (it was showing as '0'/null either in telegram or the web).  I was not very surprised because I was temporarily on a slow connection but it striked me as odd that wget'ing the exact same URL was working fine.

Now what is really odd is that apart from the fact wget'ing the exact same URL was working fine: after the connection was resolved ft kept returning the same error in the log ("WARNING - get_tickers() returned exception: "Could not load tickers due to RequestTimeout. ") but a /reload_config and then /start returned everything back to normal (!) which appears to imply that there is certain state in the software the has to clear with a reload/restart after OS networking changes otherwise it would have issues like that.

**Comment by xmatthias** [comment]
get_tickers is not related to FIAT display - but usually used for things like VolumePairlist and such.
If it fails it's usually non-critical and freqtrade will simply retry.

Fiat display is done via coingecko - which is however not done via ccxt, but with a seperate module.

Request-timeout is usually a problem at network level (which can either be their side having problems - potentially also in one region - so make sure to test from the VPS the bot is running) - or a generic network problem.

**Comment by epigramx** [comment]
Interesting; thanks; the default logging returned no warning/error for coingecko so I wouldn't suspect that easily so I guess it might deserve a place in the default log. I will close the issue now because I guess there's no much more I can add on this specific issue.

For what is worth: and for future reference of networking issues on very slow connections: I was also getting "WARNING - Telegram NetworkError: Timed out! Trying one more time." which did go through the second time indeed.

**Comment by xmatthias** [comment]
well, the combination (telegram + exchange + coingecko) suggests a network-problem with your host / connection.
Now that can also be unrelated to you directly - but to some system "kinda upstream" ... but that's usually difficult to debug if it returns back to normal after a bit.

**Comment by epigramx** [comment]
Yes; I was definitely not surprised because I was temporarily on a very slow/emergency connection. What I did keep as odd is that after linux got back to its fast connection: the software required a /reload_config and /start to stop giving the warning regarding get_tickets().

At this point though we might be talking about very low level issues with the linux networking itself so I'm not sure if it's even an issue with ccxt or this.

**Comment by epigramx** [comment]
Today it did something very similar: the linux routing table was temporarily changed to another gateway and afterwards returned to normal and it was stuck with periodically warning "fetch_l2_order_book() returned exception: "Could not get order book due to NetworkError"[..]"(in this topic it used to be "get_tickers() returned exception: "Could not load tickers[..]" and it was fixed again with a reload_config and the coingecko module was still failing (before the reload) since the software was returning 0 at fiat.

I haven't looked into the code but I suspect the practical cause is that certain connections in the software are "too persistent": meaning they connect ONCE at the launch (or very rarely reconnect) and then they have the problem that if the routing changes they need a total software restart: while the most critical connections that do trading are re-established when needed so those don't have that issue.

I'm not familiar with the codebase regarding networking but what I'd look into is to see how persistent network connections are for trading VS coingecko VS get_tickers/fetch_l2_order_book because I suspect the latter two cases are "too persistent" for its own good (alternatively it's an underlying OS issue (but I wouldn't expect a vanilla linux server to be the cause that easily)).

**Comment by xmatthias** [comment]
connections are handled by external libraries - either ccxt (fetch_orderbook) or coingecko.
Freqtrade does not actively open / close connections with either of these - so best investigate with these libraries directly.

Obviously a reload / restart will fix it as the modules are reloaded / new instances are created.
However i'm also not certain if handling network changes gracefully is something freqtrade will necessarily care about.

For trade mode, freqtrade should be run on a VPS - which usually has a stable connection (if it doesn't, you should switch provider ...).

**Comment by epigramx** [comment]
Theoretically we could assume perfect networking: because I see no issue here with that assumption: but that's unrealistic and while it's less unrealistic with a big dedicated provider it not unheard of there either (e.g. no place in the world doesn't go down about once every 6 months or a year) and some people could argue for security reasons they could avoid other providers (but that's less relevant due to the first reason).

You are right of course that if ft doesn't touch connectivity itself: then it should be making issue reports to its libraries: problem is I don't know exactly what to tell them.

If trading itself isn't affected with it but coingecko and get_tickers() and fetch_l2_order_book() are: what libraries specifically should we report to?

**Comment by epigramx** [comment]
Something relevant and different about it: the behavior may be different depended on the environment. I may have seen the issue less pronounced (or gone) when the software was running in debug mode in wsl2 via vscode on win10. But I stress "may" because I wasn't paying too much attention to that.

**Comment by xmatthias** [comment]
Honestly, so far, i see no problem that is worth reporting.
You didn't provide any logs with description what happened exactly at what time - so based on the current information, it's just a user claiming it's not working without any logs.

coingecko is not relevant for bot operations and is only there for convenience - if it bothers you, please remove the "fiat_display_currency" key from the configuration, so it's no longer instantiated.

In general, Libraries  (both ccxt and coingecko) usually create one session and reuse this.
How "network failure" is handled in this case i'm not sure - i assume most libraries will assume requests will handle this ... but this should be double-checked seperately.
it's best to create a separate testcase  (independent of freqtrade) to report to these projects - so they can verify the issue independently.


As i don't see this as a big problem at the moment, i'll for sure not spend my time on this at the moment.
So if you see this as a problem / think this must be fixed, please work on creating these issues yourself.

**Comment by epigramx** [comment]
It's unfair what you say about logs: I posted all the warnings/errors: I see no reason showing the non-errors and non-warnings of the trader.

By the way: regarding the previous comment: I bet wsl2 is not affected because in that case the routing (of wsl2) is unchanged.

That implies the issue is avoided even locally by isolating the trader in virtual OSes or regular OSes in an unaffected LAN.

But even in that case I do not believe FT should consider it irrelevant especially because parts of it are not affected by the issue while others are (so it's not even consistent with it): but I understand you don't want to deal with it so I will look at it independently: I will close the issue to relieve you from it and I will only reopen it if I find a very practical solution in code terms.

**Comment by xmatthias** [comment]
the "non-error" logs are relevant as it would show that it did work before, stopped working.
if you then correlate that with the network change, it would be visible when it happened, and what the impact was.

Only "single-line" errors (removing most information from it on top of it, as you did above)) will NOT work to properly debug an issue, and every other repository will tell you exactly the same.

It's not about relieving me from an issue or not (i can always just close it if that would be my reason for answers).
you are asking me to investigate and spend my free time on your issue, and open issues in other repositories, all while not providing sufficient logs (one line log is almost never enough - especially not if it's truncated as in your case).

In general, i don't mind to investigate things if it's really an issue.
For now, i doubt this however, as this seems to be related to your networking setup, not to a generic problem.

I do switch networks constantly while running the bot on my laptop without any issues, and all calls recover once networking is available again (obviously calls time out while network is not available).

**Comment by epigramx** [comment]
Even if you want to see everything the trader is doing the non-warning log would be unhelpful because you can't see in it the OS' rerouting which is the only thing out of the ordinary and the general cause of the different behavior in networking. 

I'm not asking you to do anything: I report issues that you may care or not care to help with: I now know you don't care about this so I closed it to not even show it to you anymore.

To add something on the topic before I go: I find it predictable that a laptop doesn't see the issue on 1 interface: this issue appears when a routing table switches between 2.

**Comment by xmatthias** [comment]
You mention routing table changes the first time this morning(without logs)- and that it must involve 2 interfaces the first time just now.

That makes it unclear if the same happened when you originally opened the issue (so the original, partial log is still relevant)- or if some other network-related change happened at that time, and now the error shown is slightly different.
Yes, the freqtrade logs will not contain the network switch - that's additional information which a system-log will have (with timestamp - which makes it correlatable to freqtrade logs).

---

While i would expect python in general to handle networking changes properly - connection persistance / keepalive is not something that freqtrade deals with directly - but is responsibility of the dependencies (ccxt and coingecko in this case).

As i don't encounter this problem (and with your given information, would take hours to try and replicate this), i'll also not be able to properly open issues and eventually follow up to confirm it's fixed.

**Comment by epigramx** [comment]
The point was the full FT log would be unhelpful. I did not know you meant to ask for full linux system logs too because I haven't noticed that happening a lot around here.

For the time being I believe the issue will be workarounded if one finds a way to bring down the routing of the previous interface entirely (yes: both cases had 2 ifaces).

**Comment by robcaulk** [comment]
I will add: something about my connection also leads to coingecko essentially not responding for long periods of time (5 minutes in some cases). This is actually quite a big issue, because during those 5 minutes, I assume freqtrade is hanging around not checking candles but instead waiting on coingecko. So this tip of "removing fiat_display_currency" from the config is quite valuable to me. The convenience of having a fiat converter does not outweigh the risk of missing trades just because I want to check trade status with the telegrambot.
