### ISSUE TITLE
backtesting is not working as expected

### ISSUE THREAD

**Issue by Vildnex** [freqtrade/freqtrade#4605]
## Describe your environment
  * Freqtrade Version: develop-8da7d5c0(`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I am implementing a strategy where in `populate_sell_trend` in order to calculate wether or not I should **sell** I am using something like this:

```
            sell_cond = (
                    (dataframe['close'] >= self.target_price[metadata['pair']]) |
                    (dataframe['high'].shift(1) >= dataframe['high'] + dataframe['high'] * self.minimal_roi[0])
            )
```
where **self.minimal_roi** and **self.target_price** both are updated on `custom_stoploss`. If I am running this code on a normal **dryrun** it's all good and working properly but in terms of backtesting is not working as expected because it will enter just once in `should_sell` when my values are not set already and after that is never going to enter it again. How can I change it in order to make my **backtesting** to work as it should in a normal case?

**Comment by xmatthias** [comment]
Updating minimal_roi per pair will not work reliably (not in live/dry, and absolutely not in backtesting).

Please familiarize yourself with [this part of the docs](https://www.freqtrade.io/en/latest/bot-basics/#backtesting-hyperopt-execution-logic) to understand the differences in execution between dry/live and hyperopt/backtesting.

in short - what you try to do will not work, as populate_sell_* is called for the whole dataframe before any trade is simulated - custom_stoploss is however called per trade - so the timing of the 2 will not allow you to use information from custom_stoploss in populate* methods.

**Comment by Vildnex** [comment]
I see... And if so is there anyway I'm which I can make this work?

The problem is that for my strategy to work I need to use a custom ROI and a custom target price which I can set them for the moment just on the customstoploss function. Is there anywhere a place that I can set them up and work?

In my testes in the dryrun is working almost properly with some exceptions that in some of the trades it just skip my ROI and sell signal for some reason, but they are not so many.

**Comment by xmatthias** [comment]
dynamic ROI is at the moment not supported.

You'll also probably encounter "roi leakage" between pairs - as the strategy object is global, not per pair, so once you set it for stoploss.

**Comment by Vildnex** [comment]
Oky I understand it now, but in this case if I am not able to use dynamic roi do you think it's an easy fix for me if I will only set my target price in my custom loss function and then if I am going to use it on populate_sell_ it should work? Or basically there is no way around in order to achieve something like this?

And if it's not possible to achieve something like this at the current moment, do you think it will be hard to implement an dynamic roi or to change the strategy object in order to be one per pair instead of one globally and multiple pairs?

**Comment by xmatthias** [comment]
using one strategy-object per pair is surely not possible.

well you can in theory work around it by using one bot instance  pair - but that won't scale for sure.

**Comment by Vildnex** [comment]
if so, is there any command that I can use at this moment that will generate me a list of dynamics pairs such as VolumePairList from pairlists? Or in other words, can I call a function or something such as for example `freqtrade download-data` or `freqtrade plot-dataframe` or anything of this nature that will give me a list, the same one which I am getting into the console when I am running the `freqtrade trade` bot and it will say 

> 2021-03-26 21:20:36,847 - VolumePairList - INFO - Searching 300 pairs: ['BTC/USDT', ..., 'ETH/USDT']

**Comment by xmatthias** [comment]
sure, either `freqtrade test-pairlist` (if you care about what your pairlist gave you) - or `freqtrade list-pairs --quote ...` 

[docs](https://www.freqtrade.io/en/latest/utils/#list-pairslist-markets)...

**Comment by Vildnex** [comment]
Ok, thx a lot, just one more question because I couldn't find in documentation this. If I am going to use either of them (I was thinking to use freqtrade list-pairs) is there any way that I can write the output automatically into a file? And when I am saying the output I mean just the list of pairs without writing all the content and then parse the file in order to get rid of all the useless stuff.

I mean the only parts that I've saw which are related to this are either:

>   -v, --verbose         Verbose mode (-vv for more, -vvv to get all messages).

This is going just to increase the number of information that I am going to receive

Or

> 
>  -c PATH, --config PATH
>                         Specify configuration file (default: `config.json`).
>                         Multiple --config options may be used. Can be set to
>                         `-` to read config from stdin.
>   -d PATH, --datadir PATH
>                         Path to directory with historical backtesting data.
>   --userdir PATH, --user-data-dir PATH
>                         Path to userdata directory.

Which none of them is related with the idea of just getting the list of pairs into a file.

**Comment by xmatthias** [comment]
if you look at the (above linked) documentation, you'll find that all "pair" commands have a `--print-json` - which will give you a valid json output. You can either copy that - or forward that to a file (`... --print-json > filename.txt`)

**Comment by Vildnex** [comment]
Thx for you answer this is really helping me a lot :)
