### ISSUE TITLE
Instance of MyStrategy has no member dp - DataProvider implementation

### ISSUE THREAD

**Issue by SoupBoris** [freqtrade/freqtrade#4607]
Bug

Operating System: Ubuntu 18.04.5 LTS
Pyhton Version: Python 3.6.9
CCXT Bersion: 1.18.119
Freqtrade Version: freqtrade 0.17.3

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Hello, I am trying to implement the use of DataProvider into my strategy to buy at the bid and sell at the ask **depending on the order book bid volume and ask volume** . However, when trying to call self.dp I get an error that self (The class MyStrategy) does not have a member "dp". I have been revising the documentation and I can find no information about how to fix this.

Please help.

+++CODE+++

import talib.abstract as ta
from pandas import DataFrame

import freqtrade.vendor.qtpylib.indicators as qtpylib
from freqtrade.strategy.interface import IStrategy

class MyStrategy(IStrategy):
    """
    Default Strategy provided by freqtrade bot.
    You can override it with your own strategy
    """

    # Minimal ROI designed for the strategy
    minimal_roi = {
    }

    # Optimal stoploss designed for the strategy
    stoploss = -0.02

    # Optimal ticker interval for the strategy
    ticker_interval = '1h'

    # Optional order type mapping
    order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'limit',
        'stoploss_on_exchange': False
    }

    # Optional time in force for orders
    order_time_in_force = {
        'buy': 'gtc',
        'sell': 'gtc',
    }

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        # Order Book
        
        **if self.dp:
            if self.dp.runmode.value in ('live', 'dry_run'):
                ob = self.dp.orderbook(metadata['pair'], 5)
                dataframe['best_bid'] = ob['bids'][0][0]
                dataframe['best_ask'] = ob['asks'][0][0]
                dataframe['bb_size'] = ob['bids'][0][1]
                dataframe['ba_size'] = ob['asks'][0][1]**  

        # RSI
        dataframe['rsi'] = ta.RSI(dataframe)

        

        # Bollinger bandsdef populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        # Order Book
        
        if self.dp:
            if self.dp.runmode.value in ('live', 'dry_run'):
                ob = self.dp.orderbook(metadata['pair'], 5)
                dataframe['best_bid'] = ob['bids'][0][0]
                dataframe['best_ask'] = ob['asks'][0][0]
                dataframe['bb_size'] = ob['bids'][0][1]
                dataframe['ba_size'] = ob['asks'][0][1]

               return dataframe

**Comment by xmatthias** [comment]
Please fill out the issue template (which includes info about your version, ...) - otherwise i'll have to close this issue without further notice.

**Comment by SoupBoris** [comment]
Where can I find the issue template and my version info? :) Ill be happy to comply!

**Comment by xmatthias** [comment]
When you open a issue and use one of the proposals (bug, feature or question) - you'll get the following question, which usually includes a lot of info that's necessary to help

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

**Comment by SoupBoris** [comment]
Bug (?)

Operating System: Ubuntu 18.04.5 LTS
Pyhton Version: Python 3.6.9
CCXT Bersion: 1.18.119
Freqtrade Version: freqtrade 0.17.3

**Comment by xmatthias** [comment]
Freqtrade 0.17.3 is a version that's around 3 years old now.
We no longer support this version.

I can't even tell you to upgrade, as you'll probably need to reinstall to get an uptodate version, as the python version you're using is no longer supported (we dropped support for 3.6 around half a year ago).

One note: you should definitely NOT put real money in with this version - i'm sure we fixed a ton of bugs in ~3 years ... so i'd consider your version no longer as safe to run.

**Comment by SoupBoris** [comment]
I will tell my grandkids about your generosity. Your help is much appreciated!

**Comment by xmatthias** [comment]
how times change :laughing: my grandparents did never use a PC, so had nothing in this regards to share ...
