### ISSUE TITLE
How to be ahead in a queue

### ISSUE THREAD

**Issue by BeppeMarnell** [freqtrade/freqtrade#4611]
Hi guys, I’ve been experimenting stuff with freqtrade for few weeks. The following may be a dumb question, but I cannot solve this. 
I recently tried a strategy, but I could not get to fulfil my order. For reference, I am trying the strategy on DREP/BTC, XVG/BTC and REEF/BTC, on Binance.
As far I have experimented there are a lot of orders and it is hard to stay ahead of the queue.
Is there something you could suggest to me? Anything is appreciated.

P.S. I’ve tried to put the order time limit to 1, but nothing.

**Comment by xmatthias** [comment]
you will have to learn how orderbooks wor - and understand how freqtrade [pricing](https://www.freqtrade.io/en/latest/configuration/#prices-used-for-orders) works.

By default, a limit buy order is placed at the best bid - and a sell order at the best ask. (you can inverse this for better fill rates - but you'll pay the spread).
Depending on your signals, price may move away from you and never return.
Queue position is not relevant in this case as price never even reaches your price - so you can be first or last in the queue, it will simply not matter.

**Comment by BeppeMarnell** [comment]
Thank you for your answer, I still do think my problem has something to deal with queue position. If I am wrong, I am sorry.
I will explain better:
If you have a look at one of these markets: DREP/BTC, XVG/BTC and REEF/BTC. Most of the times the price will oscillate between e.g. 44 and 45. Let suppose the price does not move outside 44-45. The idea would be to buy at 44 and sell at 45. In my experience, my order to buy at 44 does not get fulfilled. But at the same time, there are orders like mine that do get fulfilled. That is why I was concerned about queue position, especially because most of the volume is on the bid/ask top.

**Comment by xmatthias** [comment]
For these markets, you might be right - your best bet in this case will be to increase the unfilled-timeout so the order stays there "for longer". There is however no other way to influence order queue position, other than having been there longer.

These are VERY dangerous markets to trade in (in my opinion). one pip is more than 1% (in case of REEF/BTC, anyway) ...

**Comment by BeppeMarnell** [comment]
Alright so it is as I thought. Yes I'm already out of these markets too much effort. Thank you so much :)
