### ISSUE TITLE
The scan order of static pair_whitelist

### ISSUE THREAD

**Issue by quents** [freqtrade/freqtrade#4613]
## Describe your environment
(if applicable)

  * Operating system: macOS 11.2.3
  * Python Version: 3.9.3 (`python -V`)
  * CCXT version: 1.42.19 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.2 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

Hello, the following feature might already be in Freqtrade, but I couldn't find it. In my strategy, the possible candidates to buy generally consist of multiple pairs, and it reads the whitelist at the order of written in the pair_whitelist list in the config file. Is there a chance to change this order with a custom function that first scans the candidate pairs and chooses the best among them according to a filter that we can customize? If not, could there be any other way to accomplish that?

Thank you for your great efforts!

Yusuf

**Comment by xmatthias** [comment]
There's multiple different [pairlist handlers](https://www.freqtrade.io/en/latest/plugins/#available-pairlist-handlers) available, but you can't do custom sorting, really.

it'll also depend what exactly your parameters are - as either, you can do this by properly sorting your whitelist - or if it's dynamic, have the buy-signals only trigger for the "preferred" pairs.

**Comment by quents** [comment]
Thank you for the answer. That would be very useful if somehow pairs with buy signal are prioritized according to a rule. I will share it here if I can implement something like that.

**Comment by xmatthias** [comment]
there's no point, really (that's actually how it happens anyway) - if a pair has no buy signal, it'll simply be skipped after analysis - effectively as if it's moved to the back of the queue.
