### ISSUE TITLE
[Question/Docs] Asynchronicity of the software

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#4616]
I couldn't find an issue or doc that addresses this comprehensively so I guess it deserves a question (though point me towards the right place if it has already been answered): to what extend is the software asynchronous: are there any times during trading that is waiting for other jobs to finish before resuming trading?

There are certain points of interest because they give the impression the software is spending more time so it's interesting to know if it's fully asynchronous at those times:
1. Is it fully async during automatic filtering for pairs (i.e. will it do its 5-second interval checks and trading at approximately full speed while it's in mid-filtering)?
2. Is it asynchronous while it orders (a buy or sell) to the exchange VS checking the ticks every 5 seconds?
3. Is it async for trading while the user waits for heavy-duty telegram commands like /balance?

And something for the devs: what are the core technologies used to accomplish this: is ccxt code enough?

**Comment by xmatthias** [comment]
i'm not sure i understand your questions / they don't really make sense.

The only point python async / await is used is when downloading candle data (either as part of `download-data`, or as part of refreshing candles).

checking buys / sells is done syncroneously (as when freqtrade was started, async was not yet a mature technology).
The benefits of using async for many things in this regard are ... questionable - simply putting an "async" label on the methods and claiming "it's now async" will not really speed up anything, if it's still waiting for each thing in series as the architecture wasn't adapted to this.

**Comment by epigramx** [comment]
> i'm not sure i understand your questions / they don't really make sense.

It's simply asking if the software is **pausing** regular trading during certain operations (like filtering of pair lists) before it resumes.
This isn't a question from a dev perspective so it doesn't state how it is done though you could expand on it if you want to.
Not sure I understand what you mean it's not mature when the software uses asyncio from 2012's PEP 3156.

**Comment by xmatthias** [comment]
prior to python 3.6, asyncio was NOT mature (even though the pep may be older, and initial support was added around python 3.4). 
Also, ccxt only supported asyncio operations at a later point - and tools like sqlalchemy are only now starting to support asyncio. 
Without support for the major "waiting" points (i.e. networking operations) - there would've been little point in using asyncio as it would not give any benefit.

A mature implementation would be supported throughout the toolchain - which is simply not the case for asyncio at the moment.

freqtrade however opearates sequentially for the most part (only certain operations are async like candle download).

**Comment by epigramx** [comment]
So to summarize, it does pause during operations like filtering of pairs (if it doesn't let us know because that's what seems to be implied by "it only uses async when downloading candles").
Interesting; thanks (close this if you want to).

**Comment by xmatthias** [comment]
> if it doesn't let us know

this sentence does not really make sense. 
Freqtrade logs what it's doing (however we do try to minimize logs, as it's supposed to be running 24/7, so having 200 lines per minute will not make any sense) - but you can enable this with `-v` - so you can see what exactly happens at every step.


Also, define "pause" ... 
It does not pause, but is performing other tasks. 
obviously if you use certain pairlist filters, it'll take longer than for others (however the heaviest is the "AgeFilter" - which is doing the slow operations only once per bot execution (right on startup) - so it's not really "pausing" - but it's simply not fully started yet).

**Comment by epigramx** [comment]
What I imply from the start is that naturally it is not necessary to stop regular trading operations like the 5-second interval checks, during the time of satisfying longer-term goals of the system like filtering of pairs. 
I found it obvious that it would be a goal of development to avoid doing it that way but I don't want to be making feature requests to devs that don't have to do anything for free so I'll leave it as a question.

**Comment by xmatthias** [comment]
it's neither obvious, nor will it make sense (and doing this "out of band" is rather risky).

When checking for potential buys - freqtrade (and the user) expects a clearly defined pairlist.
By running an update to the pairlist "out of band" - you'd risk changing the pairlist after half of the pairs are checked, resulting in potentially strange behavior (some pairs would not be checked in this run, others twice).

So while you think it's obvious to do it "out of band" - it's actually not and will most likely cause more problems than it will solve.
It's also not like the bot would stop for minutes - we're talking 1-2 seconds to run pairlist refreshes (except for the initial startup) - and with the default "cycle" time of checking for buys + sells every 5 seconds, it's well within these bounds and will usually not result in longer times.

**Comment by epigramx** [comment]
On that filtering sub-topic: when you say 1-2 seconds of sequential execution, do you mean that it's much less than the total time the user sees in the log between the very start of filtering and the final printing in the log of a list by volume filtering? Because if yes: the delay does sound like a less important issue indeed.

**Comment by xmatthias** [comment]
I'm not sure what you mean by this.
Please show some logs on what you are seeing / what makes you think it's taking this long.

Checking my logs (non-debug) - i see the following:
```
2021-03-26 18:37:23,142 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-b57c1506', state='RUNNING'
2021-03-26 18:38:20,354 - VolumePairList - INFO - Searching 70 pairs: ['BTC/USDT', 'ETH/USDT', 'ADA/USDT', 'THETA/USDT', 'FIL/USDT', 'ANKR/USDT', 'XRP/USDT', 'CHZ/USDT', 'DOT/USDT', 'TRX/USDT', 'CAKE/USDT', 'QTUM/USDT', 'BTT/USDT', 'ONE/USDT', 'DENT/USDT', 'CHR/USDT', 'HOT/USDT', 'VET/USDT', 'ENJ/USDT', 'EOS/USDT', 'LUNA/USDT', 'LTC/USDT', 'NPXS/USDT', 'LINK/USDT', 'ANT/USDT', 'SXP/USDT', 'TFUEL/USDT', 'UNI/USDT', 'AUDIO/USDT', 'STORJ/USDT', 'COTI/USDT', 'ONT/USDT', 'AVAX/USDT', 'CRV/USDT', 'BCH/USDT', 'EGLD/USDT', 'OXT/USDT', 'MATIC/USDT', 'XLM/USDT', 'WIN/USDT', 'KSM/USDT', 'STMX/USDT', 'DOGE/USDT', 'SUSHI/USDT', 'GRT/USDT', 'AAVE/USDT', 'ALPHA/USDT', 'WAVES/USDT', 'ADAUP/USDT', 'SFP/USDT', 'SAND/USDT']
2021-03-26 18:38:20,405 - VolumePairList - INFO - Searching 50 pairs: ['BTC/USDT', 'ETH/USDT', 'ADA/USDT', 'THETA/USDT', 'FIL/USDT', 'ANKR/USDT', 'XRP/USDT', 'CHZ/USDT', 'DOT/USDT', 'TRX/USDT', 'CAKE/USDT', 'QTUM/USDT', 'BTT/USDT', 'ONE/USDT', 'DENT/USDT', 'CHR/USDT', 'HOT/USDT', 'VET/USDT', 'ENJ/USDT', 'EOS/USDT', 'LUNA/USDT', 'LTC/USDT', 'NPXS/USDT', 'LINK/USDT', 'ANT/USDT', 'SXP/USDT', 'TFUEL/USDT', 'UNI/USDT', 'AUDIO/USDT', 'STORJ/USDT', 'COTI/USDT', 'ONT/USDT', 'AVAX/USDT', 'CRV/USDT', 'BCH/USDT', 'EGLD/USDT', 'OXT/USDT', 'MATIC/USDT', 'XLM/USDT', 'WIN/USDT', 'KSM/USDT', 'STMX/USDT', 'DOGE/USDT', 'SUSHI/USDT', 'GRT/USDT', 'AAVE/USDT', 'ALPHA/USDT', 'WAVES/USDT', 'ADAUP/USDT', 'SFP/USDT']
2021-03-26 18:38:26,074 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-b57c1506', state='RUNNING'
```

While this seems to suggest that the refresh took from 18:37:23 to 18:38:20 - that's not the case.

The bot heartbeat is posted every 1 minute and is not related to refreshing (not to refresh start, nor anything else).
Between these 2 log messages, the bot probably checked for buy / sell possibilities multiple times ...

**Comment by epigramx** [comment]
Sorry I didn't expect a reply and I had closed it: let me clarify on that filtering thing: I'm seeing the filters taking a second or two indeed  but then after several seconds there's volume filtering which isn't explained by its refresh period.

Looking at it closely I realized that final volume filtering is a **second** volume filtering happening delayed  (which isn't explained by the refresh period) and I wonder what its purpose is (and I may even see a **third**).

Perhaps because there's also a range filter in the same interval?

**Comment by xmatthias** [comment]
i'd say it'll depend on your pairlist configuration details.
if you use multiple VolumePairLists in the same output - then sure, each VolumePairlist will show it's pairlist (so you'll see it multiple times, with different pairlists).

RangePairlist will require 1d candle data, which it does download async (however ALL APi calls are subject to exchange rate limits, so async cannot go as fast as technically possible).

You can also see similar behaviour in my logs above - where i first use a 70pair whitelist, and then reduce it to 50 pairs (with some filters in between)

**Comment by epigramx** [comment]
Oh I see what you mean: volume filter is shown 'full' at first and then it is printed again but reduced. 

A oddity here is that while the second one is indeed shorter the number in front shows same(!) (and it's correctly shorter in telegram too though there the number shows correctly shorter).

I suppose the 3rd I'm getting might be the range filter (which possibly unnecessarily happens as often).

**Comment by epigramx** [comment]
Every filter is only used once. I realized that the volume filter is printed a second time but the list is reduced by the other filters (not the count number in front of it but the literal list). 

The third time I'm seeing it printed and the extra delay: I wonder if they're caused by the ranged filter.

**Comment by epigramx** [comment]
Oh never mind: it's sillier than that. During one filter the volume filter may pop in to report a new reduced list but that filter to finish moments later with more deleted pairs and then volume is printed **again** with a further reduced list.

It's only worrisome that the whole thing doesn't take < 3 seconds (I guess I'll see if the range filtering causes it).
