### ISSUE TITLE
Reduce column width on /status table command

### ISSUE THREAD

**Issue by seansan** [freqtrade/freqtrade#462]
Currently when running /status table it eats up 2 lines and is just 1 or 2 chars too wide; see the example image. 

My suggestion is to reduce the width of the "Since" and "Profit" columns; but I just dont know where tabulate is getting it's column width from? (in short: how do I set it otherwise)

In the below example the Since column cna be reduced to 4 chars. Because hours ar max 24, then becomes days, days max 31 then become months ... 
Also the space between the "21 d" can be removed and become "21d"

In the below example Profit can be set to 1 digit

![image](https://user-images.githubusercontent.com/652395/35483404-e10be38c-0441-11e8-935c-cbc176963a26.png)

![image](https://user-images.githubusercontent.com/652395/35483444-57e0deae-0442-11e8-95ed-5d21ee5f07fd.png)

Hoping that someone who knows tabulate can add a simple fix

**Comment by jblestang** [comment]
We could also cut the “BTC_” prefix in the name of the pair

**Comment by jblestang** [comment]
If we could add a link on the pair name to ask for forcesell we would not need the ID in the table either.

**Comment by seansan** [comment]
​Thx! My main python question is: where is tabulate getting its width
marker from?

And if we are dealing with this table maybe also solve /profit abd bring it
back to a table (instead of multiline) - but maybe in separate ticket
​




Powered by Gmelius <https://gmelius.com?ref=mail>

**Comment by vertti** [comment]
Sidenote: I'm pretty sure one decimal is enough in profit percentage.

**Comment by shusso** [comment]
should be fixed
