### ISSUE TITLE
Add "unlimited" stake_amount option for hyperoptimization

### ISSUE THREAD

**Issue by atc93** [freqtrade/freqtrade#4627]
Hello,

As far as I can tell from reading the doc and trying it, the hyperoptimization does not permit to use an "unlimited" stake_amount, meaning there cannot be compounding profits. I definitely use compounding profit for my live trading strategies.

I wonder: is it something possible to add the "unlimited" feature to hyperoptimization?

Thanks!
A.

**Comment by xmatthias** [comment]
Using compounding (stake-amount=unlimited)  during hyperopt is possible just as it is with backtesting - however it'll only be possible with either develop or with the just released 2021.3.

**Comment by atc93** [comment]
This is fantastic news. Thank you!

**Comment by atc93** [comment]
Quick follow-up question: when using "unlimited" stake_amount with the hyperoptimization, what is the starting value for the staked amount (I am not connected to any account)?

**Comment by xmatthias** [comment]
[documentation](https://www.freqtrade.io/en/latest/backtesting/#starting-balance) is your friend ... :)

**Comment by atc93** [comment]
Gotcha. Thanks!
