### ISSUE TITLE
Total buy count different from profit and loss

### ISSUE THREAD

**Issue by CS0007** [freqtrade/freqtrade#4634]
Hi!

The total buy count (in this case 72) is different from profit + loss numbers (12 + 1 = 13) after backtesting. It's not the number of max_open_trades. What am I missing? Thank you
![buy count](https://user-images.githubusercontent.com/77737183/113007942-eccda280-9176-11eb-92bf-f80aefbd4e93.png)
!

**Comment by xmatthias** [comment]
Most likely - draws.

However, your output does not correspond to anything we've been using in the last (at least) half a year to a year (you can look at the format [here](https://www.freqtrade.io/en/stable/backtesting/#understand-the-backtesting-result) ) - so i'd recommend to upgrade.
For future issues - please also fill out the issue template which includes the version number - and will point out such things without thinking / knowing the ouptut from memory.

**Comment by CS0007** [comment]
Thank you!
