### ISSUE TITLE
trendlines error 

### ISSUE THREAD

**Issue by Nassiotrader** [freqtrade/freqtrade#4638]
hello 
would you please help me and let me know why im getting this error ? I want to use trendlines for my strategy but I get this error when i want to test it .

 % python3 scripts/plot_trendy.py -p BTC_USDT --live
Traceback (most recent call last):
  File "/Users/nassio/Downloads/freqtrade/scripts/plot_trendy.py", line 17, in <module>
    from freqtrade import exchange, analyze
  File "/Users/nassio/Downloads/freqtrade/freqtrade/analyze.py", line 12, in <module>
    from freqtrade.exchange import get_ticker_history
ImportError: cannot import name 'get_ticker_history' from 'freqtrade.exchange' (/Users/nassio/Downloads/freqtrade/freqtrade/exchange/__init__.py)

**Comment by xmatthias** [comment]
I don't know what you're trying to do - and a script called `plot_trendy.py` is not part of this repository (never has been as far as i know).

The error suggests that you're trying to import a function that doesn't exist (it's not part of the repository).
As it's unclear what you try to do, i also can't tell you where to look for a potential replacement.

**Comment by Nassiotrader** [comment]
I am new in python and I am trying to use trendlines in my strategy but I can not run it to see what will be the output and how to run it , Is there any chance you can help me and write the instruction ? Thank you

**Comment by xmatthias** [comment]
As mentioned above - the script you're trying to use is NOT part of this project, therefore we cannot provide support for it.

If it's just about plotting, then please look at the [plotting documentation](https://www.freqtrade.io/en/latest/plotting/).
If you want to run the script above, then please ask for help in the source you got that script from.
