### ISSUE TITLE
Please add new column in /status table to show USD profit or loss

### ISSUE THREAD

**Issue by devalias** [freqtrade/freqtrade#464]
Please add new column in /status table to show USD profit or loss

**Comment by seansan** [comment]
Lets fix https://github.com/gcarq/freqtrade/issues/462 first
After that maybe update all tables to 1 more consistent format and reduced data (width)

**Comment by seansan** [comment]
`'{value:0.2f}'.format(value=_FIAT_CONVERT.convert_amount(current_rate['amount'],_CONF['stake_currency'],_CONF['fiat_display_currency']))`
somethong wrong here, dont know what

error: TypeError: 'float' object is not subscriptable
