### ISSUE TITLE
Sell in other Markets

### ISSUE THREAD

**Issue by mablue** [freqtrade/freqtrade#4640]
## Describe the enhancement
Let assume that  my stake type is USDT.and sell trigger for xlm is actived
ADD this option to the config:
```
serial_sell: true,
serial_sell_markets: {'ETH', 'BTC', 'USDC'}
```

With this simple code:
```
if XLMUSDT < XLMBTC*BTCUSDT:
   sell XLM in XLMBTC maeket
   sell BTC in BTCUSDT market
else:
  sell XLM in XLMUSDT market
```

the algorythm will check other pairs too:(ETC,ETH,BCH,USDC,etc...)

and it can implement in buy orders too

**Comment by xmatthias** [comment]
Freqtrade is no arbitrage bot.
This is currently not possible, and there are no plans to implement it either.
