### ISSUE TITLE
Create strategy, help.

### ISSUE THREAD

**Issue by ArnoldS5** [freqtrade/freqtrade#4644]
Create strategy, help.

Hi, I've been programming in C#, python, and something in javascript for a short time. I am a newbie and I am learning
I would like to create a trading strategy to use with freqtrade.

This strategy would be to look for the highest and lowest points where the price is rejected, creating a wick in the candle, these points will be joined by a trend line, and when the price touches that trend line, enter buy or sell.
I would like to know if there is already a strategy of this type or similar to study it, or if you can help me, if you can give me advice to implement it.

Greetings and thanks.

**Comment by xmatthias** [comment]
you can look at the [strategy repository](https://github.com/freqtrade/freqtrade-strategies) for inspiration and samples of other strategies.

Alternatively, you might wanna join the [discord community](https://discord.gg/MA9v74M) to discuss this.
We generally don't provide strategy-help at this level via issues.
