### ISSUE TITLE
Trailing stoploss: reevaluate pair price after sell timeout

### ISSUE THREAD

**Issue by yagmot** [freqtrade/freqtrade#4645]
I noticed something funny today. A pair reached trailing stoploss, and a sell order was issued. The order timed out before it was filled, and a new sell order was placed. But during the few seconds between the timeout and the new sell order, the price of the pair rose. This new sell order also timed out, and a third order was placed, again at an even higher value.

If a sell order times out, the bot should check the current price to see if it is above the stoploss price before issuing a new sell order.

[freqtrade_stoploss-timeout.log](https://github.com/freqtrade/freqtrade/files/6247543/freqtrade_stoploss-timeout.log)

**Comment by xmatthias** [comment]
well what's your trailing stop settings / parameters look like?

price is actually checked again - and stoploss musst be "retriggered" based on this new price (so your pricing settings will also matter) since you don't seem to use stoploss on exchange.

**Comment by yagmot** [comment]
Thanks for your reply, Matthias!

KuCoin doesn't support stoploss on exchange, so I can't use it. If price is checked again, I really don't understand what happened here then.

> "trailing_stop": true,
    "trailing_stop_positive": 0.0025,
    "trailing_stop_positive_offset": 0.0125,
    "trailing_only_offset_is_reached": false,

I know you say 0.25% is too tight, but I'm working with 1m candles and the average candle size of the pairs I'm working with are about that size.

It also seems like something funky is going on with the calculations.

> 'open_rate': 9.027e-05, 'current_rate': 9.157e-05, 'profit_amount': 3.14e-06, 'profit_ratio': 0.01237447,

That's actually a profit ratio of 1.44%, not 1.23%. 1.23% would be 9.138e-05. Or does the calculation include fees?


And lastly, it looks like the price dropped below 9.157e-05 twice, ~8min and ~45min before the stoploss sell was triggered. 
<img width="1240" alt="ft_peak-to-sell" src="https://user-images.githubusercontent.com/2442238/113476185-e875f200-94b4-11eb-9edf-4717fee1f764.png">

**Comment by xmatthias** [comment]
the profit calculation does include fees - the "real" (applied) open fee - and the assumed close fee (assumption is that it'll be the same as open fee).

it'll depend on many things - for example also how many pairs you got in your pairlist.
If you use a ton of pairs on 1m candles (and a rather high rate-limit - not sure how that must be for kucoin) - it's possible that one iteration takes longer than 1 candle - so the bot does not "see" the "flick down" - and if it happens very quickly (down and back up) - it's very easily possible that the bot will simply miss these.

The same is possible if many trades are open in parallel, which will lead to the same effect.

**Comment by yagmot** [comment]
Thanks, I suppose that could be the case. I'll try adjusting the number of trades and pairs to see if that makes a difference.
