### ISSUE TITLE
strategy question: How to say "first cross" in strategy?

### ISSUE THREAD

**Issue by yaotian** [freqtrade/freqtrade#4647]
Hi,

Question as title.

For example,

condition1: rsi>=50
condition2: ma5 *first cross* ma20

How to make condition2?

Thanks.

**Comment by xmatthias** [comment]
"first cross" is quite unclear...
You can check for these 2 conditions (the way i understand it for now) as follows:

``` python

(dataframe['rsi'] >= 50) &
qtpylib.crossed(dataframe['ma5'], dataframe['ma20'])

```

but there's no "first" involved - and i'm not sure what you mean with this.

**Comment by yaotian** [comment]
> "first cross" is quite unclear...
> You can check for these 2 conditions (the way i understand it for now) as follows:
> 
> ```python
> (dataframe['rsi'] >= 50) &
> qtpylib.crossed(dataframe['ma5'], dataframe['ma20'])
> ```
> 
> but there's no "first" involved - and i'm not sure what you mean with this.

ma5 crossup ma20, then ma5 crossdown ma20, then ma5 crossup ma20 again. They all happened on "rsi>=50".
Want to only first crossup. Don't want to buy when second crossup.

qtpylib.crossed, for my understatnding, will both triger first and second crossup?

**Comment by xmatthias** [comment]
well i guess you can use some rolling window and count crosses. 
something like `dataframe['crosses'] = dataframe['cross'].rolling(10).sum()` - and then compare if crosses is 1 (or so) - in addition to checking that a cross actually happens in this place.

it'll be a fixed rolling window - so you still kinda risk of having this timedout after some time.

This is however mostly a pandas problem - not something we will be able to provide extended support on.
