### ISSUE TITLE
Why is filling the limit up of trades immediately after startup

### ISSUE THREAD

**Issue by eleyvapro** [freqtrade/freqtrade#4648]
## Describe your environment

  * Operating system: macOs 11.2.3
  * Python Version: 3.9.2
  * CCXT version: 1.43.89
  * Freqtrade Version: 2021.3
  
## Your question

Has been 2 week so far and I configured almost everything from the docs, Hyperopts blew my mind and now very excited to put it in production.
Im happy with my strategy at this time, but couple days ago I noticed that every time I start Freqtrade (dry-run), it buys all the pairs till filling the limit up `max_open_trades` in an instant. Is it normal behavior? I remember in my first tries, it could take hours to start trading for new pair. 
I see good performance in live but im afraid my configuration doesn't handle orders properly and lead into a trade just at the beginning of its drawdown unnecessarily.

What do you suggest me to check in the configurations?

_This is what I think it could be affecting after read many time the documentation, probably im missing something else._

**bid_strategy**
```
"bid_strategy": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": true,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": true,
            "bids_to_ask_delta": 1
        }
    }
```

**Too many pairs (up to 31) vs max_open_trades**
```
{
    "max_open_trades": 20,
    "amend_last_stake_amount": true,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "15m",
    "dry_run": true,
},
"pairlists": [
        {   "method": "StaticPairList" }
],
```
 
**Number of candles the strategy requires before producing valid signals and order types**

```
startup_candle_count: int = 30
order_types = {
        'buy': 'limit',
        'sell': 'limit',
 }
```

----
Also I take advantage of this question to comment that probably there is a simple mistake in documentation about Protections.

[Link](https://www.freqtrade.io/en/latest/plugins/#low-profit-pairs)

- Locks all pairs that had 4 Trades within the last 6 hours (6 * 1h candles) with a combined profit ratio of below 0.02 (<2%) (LowProfitPairs).

Referring to:
```
{
        "method": "LowProfitPairs",
        "lookback_period_candles": 6,
        "trade_limit": 2,
        "stop_duration_candles": 60,
        "required_profit": 0.02
}
```

**Comment by moinonin** [comment]
This might be a problem with the buy signal rather than the configuration. You might be buying too expensive assets. By this I mean not the actual price but where the buy indicator is placed, e.g. if you have RSI in the buy it might be too high and therefore the risk of blowing up your account might equally be high. Otherwise if its actually making even a moderate profit then you might have other problems. I say this because I have almost same settings as you do and I haven't experienced that problem.

**Comment by xmatthias** [comment]
Well the key is your strategy.

Freqtrade simply acts on the (buy) signal your strategy is giving. If your strategy tells it "buy" - it'll buy up to the "max_open_trades" limit.

so assuming with `max_open_trades=20` you have 50 or 80 pairs in your whitelist - and your strategy tells it to buy 20 of these - freqtrade will do that "one after the other".

Neither price configuration (nor anything else, really) can or should prevent this from happening - nothing other than your strategy, which is telling the bot to buy, not buy, or sell / not sell.

**Comment by eleyvapro** [comment]
Hi guys

Exactly like you said, it was nothing to do with the config, I found out that my docker-compose was using my temp_strategy.py which I used for testing against Hyperopts without mess my good one up. Now It acts with a reasonable behavior, thanks @moinonin and @xmatthias 

I wondering if `startup_candle_count`: takes in consideration all past candles in order to take a decision rather than taking the start date of the application, which is more advantageous and rational than I thought.

**Comment by xmatthias** [comment]
in live (and dry) modes - startup_candle_count is technically irrelevant, it's unly used for backtesting / hyperopt.

In live / dry - you have the latest 500(ish - depends on the exchange) candles available.
