### ISSUE TITLE
Add Pairlist Handler for Volatility 

### ISSUE THREAD

**Issue by Jay-ArBrouillard** [freqtrade/freqtrade#4650]
## Describe the enhancement

In some strategies, I would prefer to enter trades that have a higher historical volatility, so it would be nice if the pairlist was ranked by this with the first pair having the highest volatility. You should be able to define a time period this is calculated on (1 month, 2 month, 3 month, etc.). Some other parameters could be "number of assets" similar to VolumePairList and "minimum volatility" or "maximum volatility".

**Comment by xmatthias** [comment]
I'll mark this as enhancement, but will also leave it there as "good first issue" - as this will only touch a very limited part of Freqtrade, and is therefore great for first time contributors / beginners in contributing to freqtrade.

---

This should not be too difficult to do, and might be a copy / combination of `RangeStabilityFilter` and `VolumePairlist` - basically reversing the logic (and using it for sorting...).

I'm not sure if this should Provide the pairlist, or just sort an available pairlist by it (VolumePairlist  is a provider, most others are just Filters / sorters) 

We've also got a [developer section related to pairlists](https://www.freqtrade.io/en/latest/developer/#pairlists) which explains what each setion does / should be doing.
