### ISSUE TITLE
Depth of market compared to stoploss / roi

### ISSUE THREAD

**Issue by hippocritical** [freqtrade/freqtrade#4652]
## Describe the enhancement
At the moment there is the option that I would like to have it enhanced for short trade exchange
If it is a dumb idea please say it, I REALLY love your tool :)

Wouldn't it be awesome if you could only check the order book depth for a depth until the stoploss, the overall order book depth shouldnt matter imho if you specifically look for short trades (max 1 hour, average 30 minutes for example).

bid_strategy. check_depth_of_market.enabled
Do not buy if the difference of buy orders and sell orders is met in Order Book. Check market depth. Defaults to false.  Datatype: Boolean

*Explain the enhancement you would like*

Check for the order book depth but only for a specific delta in price. Compare both sides and then check which one is higher like normally.
The first picture shows a zoomed in view for the pair LOOM/BTW as an example.
The second picture shows the same pair but zoomed out with the overall depth of market. By the time the bot would reach the first big wall it would have been long gone from the deal even if it would have risen by 10% every minute. It would have already have the sold the coin by 3% roi (for example).
[https://i.imgur.com/Oz43lPY.png](url)
[https://i.imgur.com/9nj8wMO.png](url)

**Comment by xmatthias** [comment]
I would suggest to rephrase the above to make it clear what you're looking for.

I've read it now 3 times - but i still have no idea what you're trying to do or what you're looking for.

If you don't want to look at "order book depth" - then simply disable the config setting for it - so it will not look at this.

**Comment by hippocritical** [comment]
Hi, I would like to look at order book depth, but not at the full depth. For high frequency trading it would be more than enough to look at the height for (for example) 3% of price change in either direction and take that part of the order book only :)

to clarify it even further:
At the moment we only look at one number, the maximum order book depth.
If you trade pairs then you normally only trade them for a short time. The automatic stoplosses or buys on dramatic pumps / dumps would more than like not happen within this time frame.
In my opinion it would benefit more to see a zoomed in view and ignore all those high walls near the end of the eagle eye view.

The picture 1 shows a order book depth of 3.7% with much higher buy orders than sell orders.
The picture 2 shows the eagle eye view and it says that 3 sell orders are there for one buy order.

If we look at the buy order depth of 3.7% (for example) then we see much higher bids than sells.
The new function would result in a bid/sell ratio of 1.31m / 222k => 5.9

The "old view", the eagle eye view, would show a bid/sell ratio of roughly 100/472 => 0.25

If we could specify the cutoff view for the order book instead of being forced to use the whole order book we could make more fine grained decisions if it is worth it or not to invest at that point in time for ~1-2 hours.

And again : please say if that s a dumb idea, Im only a newb.

**Comment by xmatthias** [comment]
well you can get the [orderbook in your strategy](https://www.freqtrade.io/en/latest/strategy-customization/#orderbookpair-maximum) and do "whatever" calculation there.

I has the drawback of an "active" network call in the strategy (which can make pair analyzing slower than without it) - but i don't think it'll limit you.

What will limit you is the return value you get from the exchanges - for example from binance, you can only get up to 1000 orderbook steps on both sides.

Depending on the pair's price / pip balance, this can be 1% or 20% away from the pair's current price - so i don't think you'll be able to get this "zoomed out" view in all cases where you show the orderbook ranging for quite some.

It may work for low-priced pairs - but for pairs like BTC/USDT it may not work well anymore (you only get 1000 steps in the orderbook at the lowest level!).

Now i never looked if it would be possible to get "zoomed out" views - but i don't think it will - at least i haven't seen that anywhere yet.
