### ISSUE TITLE
telegram command "/performance" or "/status table" no message. 

### ISSUE THREAD

**Issue by yaotian** [freqtrade/freqtrade#4655]
As title.

looked at the logs. And it reports  "Message is too long".

I set 250 max trades. I guess it had too many opening trades?

Thanks.

**Comment by xmatthias** [comment]
I've moved this issue to the proper repository (it should be in the main repo, not in the strategies repo).

Also, this will depend on the version. As you get it with `/status table` - i know you're not on the latest version (2021.3) as it was fixed for that in #4593.

For `/performance` - i guess this will tie into #4519 ... should however not be too difficult to fix (max_open_trades will not matter for this if you use volumepairlist - as it's the total amount of pairs that's ever been traded that matter for /performance).
