### ISSUE TITLE
Telegram notification on triggered protections 

### ISSUE THREAD

**Issue by GerhardK90** [freqtrade/freqtrade#4657]
## Describe the enhancement
It would be nice to receive a notification via telegram if a protection is triggered.

**Comment by xmatthias** [comment]
I think this would lead to quite a lot of spam notifications - depending on your settings there can be 3-5 different locks activated at the same time - and i think the benefit you get from this is quite low.

Technically, Protections ONLY trigger after a sell did happen - so in theory you could simply run `/locks` after you get a sell notification, and you would see which protections are now active.

**Comment by GerhardK90** [comment]
I agree that this could be the case if you enable it per pair. If it is a global lock though, I guess it is one message. What do you think about a config parameter? 
I think it is really helpful as in case locks happen at certain times (for example at night) you would have to check the logs as the unlock could have happened before you checked with /locks.

Happy Easter and thank you!

**Comment by xmatthias** [comment]
well if the unlock happens before you wake up - the bot will simply not have made any trades. I don't see why this would be something that you'll need to be informed about.

**Comment by GerhardK90** [comment]
What you say is correct, but if you would have expected more trades you would like to know why they did not happen. A simple notification about a triggered protection could just help you in such a case to figure out what actually happened.

**Comment by krakowski** [comment]
+1 for getting a notification whenever a **global** protection is triggered. This would allow to assess the situation and stop the bot for a longer time if necessary.

**Comment by dj-crypto-rick** [comment]
+1 for getting a notification too. Thanks, xmatthias.

**Comment by abhiklodh** [comment]
I can give this a try as I too believe it will be a nice addition.
