### ISSUE TITLE
Technical Indicator Documentation

### ISSUE THREAD

**Issue by Jay-ArBrouillard** [freqtrade/freqtrade#4661]
## Your question

To preface this, I know that it is up to the user to research technical indicators on their own and then figure out how to implement them in their own strategies. Having said that, I've personally had a lot of trouble trying to understand what some of the technical indicators mean. For example, with Pattern Recognition indicators such as CDLENGULFING, they return some value, 0, -100, or 100 but I don't know if a negative means bearish or if positive means bearish. Therefore, I can't apply it to my strategy. I've tried looking into TA-Lib documentation for this but the docs there are abysmal. Anyways, I was hoping that someone would be able to explain how to work with Pattern Recognition indicators. Then maybe down the line, as an extension, it would be nice to have documentation on FreqTrade to explain simple ways to use the technical indicator. Could have an example for couple indicators from each type Momentum, Mean Reversion, Overlap Studies, Pattern Recognition, etc..

**Comment by xmatthias** [comment]
To be honest, i think having documentation of ta-lib indicators is WAY outside of the scope of this project.

Also for your question - you might wanna give the [ta-lib python](http://mrjbq7.github.io/ta-lib/doc_index.html) docs a try (it's the best ta-lib docs i know) - and if you can't find an answer there, maybe ask in the [repository](https://github.com/mrjbq7/ta-lib) for this - as your question is not strictly related to freqtrade, but to ta-lib in general - where the real experts will be found there.

That's also where eventual enhanced documentations should go - so it will benefit all projects using ta-lib - not just freqtrade.

**Comment by Jay-ArBrouillard** [comment]
I understand, I am closing the ticket.
