### ISSUE TITLE
Hyperopt --spaces (buy vs. sell)

### ISSUE THREAD

**Issue by djacky** [freqtrade/freqtrade#4662]
## Describe your environment

  * Operating system: MAC OS
  * Python Version: 3.8.2
  * CCXT version: ccxt==1.43.89
  * Freqtrade Version: freqtrade 2021.3
  
## Your question

I wasn't able to find this answer in the docs. Just had a quick question about the Hyperopt optimization and the "buy" and "sell" optimization options in --spaces

Since freqtrade cannot make short orders (yet), what is the purpose of putting the "sell" command in the `--spaces` option of Hyperopt? In other words, if I only select `--spaces sell`, what is the purpose of this if freqtrade can only long orders?
Does `--spaces sell` optimize for short selling?

**Comment by xmatthias** [comment]
most strategies have a buy and a sell signal (although some only rely on ROI / trailing stoploss).

If you are content with your buy signal - you will focus on your sell signal -> optimize for selling the trade again - while keeping the buy-signal static.

It's also beneficial as the search-space is smaller.

**Comment by djacky** [comment]
So how do you keep the buy signal static? Do you simply set fixed numbers for the buy signals (without setting any optimization variables)?

**Comment by xmatthias** [comment]
no, if you don't optimize for the buy signal - it's using the "regular" `populate_buy_trend()` method (usually from your strategy).
