### ISSUE TITLE
Dynamic Stoploss change before reaching the offset

### ISSUE THREAD

**Issue by quents** [freqtrade/freqtrade#4663]
## Describe your environment

  * Operating system: macOS Big Sur 11.2.3
  * Python Version: 2.7.16
  * CCXT version: 1.45.85
  * Freqtrade Version: 2021.3
  
## Your question

Hi,

I read all the documentation about trailing stoplosses and the examples about them, yet I miss a single point. I guess when `trailing_stop_positive_offset` is set and `trailing_only_offset_is_reached` is set to True, the actual stoploss value doesn't change according to the current profit. What I would want is this with the following settings:

```
 stoploss = -0.035
 trailing_stop = True
 trailing_only_offset_is_reached = True
 trailing_stop_positive = 0.01
 trailing_stop_positive_offset= 0.04
```

The bot buys an asset at a price of $100. If the price increases to $104, trailing_stop_positive is enabled and the asset is sold when the price decreases to $102.96 (1% stoploss from $104). However, if it never reaches $104, then the stoploss price is calculated based on the open price and never changes from $96.5 (3.5% stoploss from $100). Is it possible to dynamically change the stoploss price when the current profit between 0% and 4%? I mean, if the price increases to $102, the bot sells the asset when the price decreases back to $98.43 (3.5% stoploss from $102). I tried this with custom_stoploss because it always calculates the stoploss relative to the `current_rate` but I guess my thinking is wrong:

```
def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime, current_rate: float, current_profit: float, **kwargs) -> float:

      if current_profit < 0.04:
          return -0.035 #that should be calculated based on the current profit
     
      #if the price increases above 4%
      desired_stoploss = -0.01
      return desired_stoploss
```

Thank you for your great effort!

**Comment by xmatthias** [comment]
it'll work like that - but when using custom-stoploss, i'd recommend to disable trailing stop (otherwise the 2 will compete - and the "higher" stoploss value (closer to current profit) wins.

You'll also need to explicitly enable custom stoploss with `use_custom_stoploss=True`.

**Comment by quents** [comment]
I actually disabled all of them except for stoploss, which is mandatory. I couldn't decide on what stoploss variable should be for the above configuration to work. I also set it to -0.035.
