### ISSUE TITLE
Problem with HyperOpt ROI

### ISSUE THREAD

**Issue by salehhashemi1992** [freqtrade/freqtrade#4673]
Hi
I am using the HyperOpt system to optimize my TradingView PineScript.
Everything works great except ROI seach space system,
first of all I think there in no way to implement this system in pine script? (is it true)

So I tried to change roi to something like this: (Single Take profit)
```
    @staticmethod
    def generate_roi_table(params: Dict) -> Dict[int, float]:
        roi_table = {}
        roi_table[0] = params['roi_p1']

        return roi_table

    @staticmethod
    def roi_space() -> List[Dimension]:
        return [
            Real(0.025, 0.07, name='roi_p1'),
        ]
```

But the optimized value that is something like this:
```
 minimal_roi = {
        "0": 0.16762
    }
```

is not working! and not match the HyperOpt result at all and make a huge loss. 

  * Operating system: Windows 10 64bit
  * Python Version: Python 3.9.2
  * Freqtrade Version: freqtrade 2021.3

**Comment by xmatthias** [comment]
Please fill out the issue template. It'll let us know which version you're using and therfore help us support you.

As mentioned in the "open issue" templates - issues without that will be closed without further comment.

The main reason is - you might be using an uptodate version - or an outdated one that doesn't support custom ROI spaces - but without this info we might waste days (of both your and our time) trying to help you while the solution would be quite simple.

**Comment by salehhashemi1992** [comment]
> Please fill out the issue template. It'll let us know which version you're using and therfore help us support you.
> 
> As mentioned in the "open issue" templates - issues without that will be closed without further comment.
> 
> The main reason is - you might be using an uptodate version - or an outdated one that doesn't support custom ROI spaces - but without this info we might waste days (of both your and our time) trying to help you while the solution would be quite simple.

Excuse me for that.
Updated

**Comment by xmatthias** [comment]
And the above segments are part of the hyperopt file - are correctly indented (and the hyperopt-class in question is  the only class in the folder with the same name)?

We've had ... many cases where a wrong hyperopt file has been loaded due to name duplication ... 

the value you get seems strange indeed, as the space is not supposed to be > 0.07...

**Comment by salehhashemi1992** [comment]
Yes I am sure.
this was an example of what I get.

This will happen even when using the default strategies and HyperOpts.

Classes like HOSwingHighToSky and SwingHighToSky

And also I will thank if you answer my first question. is there anyway to implement this multiple roi system in TV pine script?
And also is there any standard way to implement single take profit point for HyperOpt?

**Comment by xmatthias** [comment]
I don't understand your problem and i'm sure it's something in your environment / in the setup of your hyperopt file.

If i copy/paste your above code into the Hyperopt file you mention (correct indentation, ...) - then i get the results exactly within the defined bounds - which suggests that there's some error involved (maybe the wrong file is loaded - or indentation / location of your code is wrong).


---

I don't care about TV pine script, it's not something i maintain nor support.
If you need support, best ask tradingview directly.

**Comment by salehhashemi1992** [comment]
Thank you
I will double check that.
But plz ask this one: 
Is this the official solution for implementing the single take profit?
using this roi:
```
minimal_roi = {
        "0": 0.16762
    }
```

**Comment by xmatthias** [comment]
yes, this way you'll use a ROI of 16% from the first moment onwards.

The "regular" default samples use a stepped approach which lowers ROI / Takeprofit over time - but that's not necessary.

**Comment by salehhashemi1992** [comment]
Thank you.
and is this true too for HyperOpt for optimizing single take profit?
```
    @staticmethod
    def generate_roi_table(params: Dict) -> Dict[int, float]:
        roi_table = {}
        roi_table[0] = params['roi_p1']

        return roi_table

    @staticmethod
    def roi_space() -> List[Dimension]:
        return [
            Real(0.025, 0.07, name='roi_p1'),
        ]
```

**Comment by xmatthias** [comment]
The result you get "kinda" confirms this - but i don't understand why you get values > 0.07 - which i didn't when i tested your code - which makes me think that maybe you've got the roi_space method in your file twice - or it's somehow wrongly placed so it's not used.
