### ISSUE TITLE
Wrong sell/open price when trading with HTBC exchange

### ISSUE THREAD

**Issue by raminhafezi** [freqtrade/freqtrade#4678]
Hi,
I installed latest version of the freqtrade and config it with the HTBC API. I tested freqtrade in a Dry-mode and see some strange buy/sell transactions. The strange thing is that there are some trade with duration < 1 minute  and gain profit >10%
I ended up double-checking OHLCV in the HTBC website with the exact same timeframe, and see that prices are wrong on freqtrade db and the coin-pair has never see that price. 

Would somebody help me to debug this issue?

**Comment by xmatthias** [comment]
Prices used for trades depend on your configuration - and it'll come either from the bid/ask price from `fetch_ticker()` - or from the `fetch_l2_orderbook()` if orderbook pricing is enabled.

if orders are made "off-price" - i suspect that `fetch_ticker()` does not return uptodate information - which will simply mean that you might get around this by enabling orderbook pricing.

To integrate / debug a new configuration, you should be rather familiar with python / using python functions explicitly - as you're the first person (i know off, anyway) using this exchange - so you might still encounter problems when trying to place "real" orders.
