### ISSUE TITLE
TelegramDeprecationWarning

### ISSUE THREAD

**Issue by yagmot** [freqtrade/freqtrade#4688]
## Describe your environment

  * Operating system: macOS 10.15.7
  * Python Version: python 3.9.1
  * CCXT version: 1.46.3
  * Freqtrade Version: develop-be3b6ab4
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

When starting freqtrade bot, we are presented with a warning about Telegram (message pasted below)

### Steps to reproduce:

  1. start freqtrade bot with Telegram enabled
  
### Observed Results:

  * A warning message is displayed (see below)
  * (changing the code at the designated line from `clean=True,` to `drop_pending_updates=True,` fixes the issue)

### Relevant code exceptions or logs

From log at startup: 

  ```
freqtrade/freqtrade/rpc/telegram.py:161: TelegramDeprecationWarning: The argument `clean` of `start_polling` is deprecated. Please use `drop_pending_updates` instead.
  ```

Sorry, I've never tried to submit a pull request, and I didn't want to screw it up. I'll learn how to do it properly and submit PR next time.

**Comment by yagmot** [comment]
Made a PR: https://github.com/yagmot/freqtrade/tree/yagmot-TelegramDepreciationWarning

**Comment by xmatthias** [comment]
It's a warning for now - as they are changing the setting name.

I'll have a look at it - but for now, it's nothing concerning until the upgrade to a new telegram version which removes this - which i don't think is even scheduled just yet.

either way, thanks for reporting! :+1:
