### ISSUE TITLE
Questions/feature: on the renewal of pair filtering in relation to the delay of each iteration and their refresh period

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#4689]
## Describe your environment

  * Operating system: ubuntu server
  * Python Version: 3.8.5
  * CCXT version: 1.46.38
  * Freqtrade Version: current develop
  
## Your question

It appears that one can not reliably start filtering at X minutes into a candle and then have the next candle renew exactly at X minutes into the candle again because there is a delay for filters to do their work which is a problem due to the partial unpredictability of it.

Hence I wonder if that is possible in a way I miss or if there should be a new feature that enforces that behavior (perhaps as a top-level variable of "pairlists" that enforces "refresh_all_filters_Y_percentage_into_a_candle"(percentage in relation to its full length so it's dynamic)).

A side-question that is related: if there are two volume filters (one at the start and one later) and both refresh every Y minutes: is either of the two completely irrelevant to refresh (and it could be set to a very large number) since they both seem to re-apply anyway?

**Comment by xmatthias** [comment]
> It appears that one can not reliably start filtering at X minutes into a candle and then have the next candle renew exactly at X minutes into the candle again because there is a delay for filters to do their work which is a problem due to the partial unpredictability of it.

I don't understand what you mean with this.
Pairlists refresh at thee startup, and then after a defined amount. candles / candle durations have very little to do with that - and no pairfilter we have at the moment (iirc) relies on the effective candles (in the timeframe used) for filters, so having this refresh at a "very specific" interval would have very little gain.

**Comment by epigramx** [comment]
> I don't understand 

It drifts because of the time it takes to process them all. For example you start 100 seconds into a new candle and the next it might start 102 seconds into the candle even if you clearly have set up the refresh intervals to align to 100 seconds.

After many candles it may drift so much that it's not only far from 100 seconds anymore but it may overcome the candle itself and start from 0.

**Comment by xmatthias** [comment]
Honestly, pairlists are not intended to be refreshed every 100 seconds, but more like every few hours.

the limit itself not actively checked / enforced (maybe it should be?), so in theory you can use any limit you desire - but i'd consider using a refresh rate of < half an hour as not supported - and runing pairlist refreshes "at exactly this time" is nowhere documented nor is that something that's supported.

The "refresh" interval is intended differently than how you understand it - it's not "it'll refresh after exactly 100 seconds - but it's "it'll keep your pairlist for 100 seconds - and refresh after that.

I don't see a point in refreshing "exactly at this point" - 24h volume uses the sum of 24 hours - so if it runs at 08:05 or 08:07 will not make any difference.

**Comment by epigramx** [comment]
I understand that it's not a feature: I guessed it probably isn't: that's why this is in questions and not in bugs. I also understand how it works technically (in terms of not enforcing an exact timing of renewal in terms of real-time; though it's still a bit unclear if it needs two volume filters to both have their refresh interval set up at the lowest desired interval (and not have one of the two on a very high interval) since I don't know if only one is refreshed it then refreshes the other too since it's the same filter type etc.).

Regarding why you would want that feature: well it can be part of strategically filtering "not too early and not too late" inside a candle and for long-enough timeframes that can make a big difference (e.g. the list will be very different 10 seconds into a 4h candle compared to 10 minutes before it ends) and it can be also a technical problem if you filter right at the start of a candle because as we had discussed the software is not fully asynchronous and it may stall it for a couple of seconds.

**Comment by epigramx** [comment]
> if it runs at 08:05 or 08:07 will not make any difference.

Regarding that: notice the problem of drifting. It may go to 8.07 after a few hours (or more or less depended on filtering load). But it may also go to 8.59 eventually or to 9.00 or to 11:15 etc. and it may throw off any preparation one may have done regarding their filtering inside their candle/timeframe,

**Comment by epigramx** [comment]
Dropping a note on the side question (final paragram of the first message): it appears that the code probably doesn't care at all if you re-use the same filter as a new instance so whatever each instance has as refresh interval setting it will be just used for each instance individually.

So I wonder if it should be a goal to unify all such instances of the same filter to the same refresh interval; but I'm not sure: maybe there are some use cases I didn't think about.

A problem that is probably the biggest I noticed on that part is that: sometimes(very rarely) a filter may give you X number of pairs at its \*final\* instance but the \*first\* instance to renew again \*moments\* later because of their refresh intervals being identical and give you a reduced number of pairs (because now the first instance returned different pairs) which is very puzzling on why it is happening and how it could be prevented because one would expect if they both have the same interval then the first instance of the filter should never be applied again right after the second instance (without the second one refreshing early-enough too) if they have a long enough refresh interval both (and equal).

**Comment by xmatthias** [comment]
for `VolumePairlist`, the refresh-interval (cache) is only applicable if the pairlist is the first in the list (the pairlist generator).

For "filtering" Volumepairlists (not the first position in the list of pairlists) - `refresh_interval` becomes irrelevant and is ignored.
so if you use VolumePairlist twice (at the start and at the end) - the latter one will never use cached candles, but will always return a fresh pairlist.

This is different for `RangeStabilityFilter` and `VolatilityFilter` - but neither of these can serve as pairlist generator, and there's little to no point in having either of these twice in the pairlist section, so i think that's a neglectible problem.

I'll update the docs to clarify this point.
