### ISSUE TITLE
External Pairlist for multiple bots

### ISSUE THREAD

**Issue by focamonca** [freqtrade/freqtrade#4691]
I'm running 6 bots, and they're running the same pairlist.
Since I update manually that pairlist on every config every week after some tests, it would be great if the bots could use a shared external parlist. Something the pairs.json used to download data.

**Comment by xmatthias** [comment]
pairlist.json cannot be used outside of data-download.

However - You can use multiple configurations per bot (`--config config.json --config config_pairlist.json`) - where the 2nd pairlist will only contain the pairlist.

You can then use the same `pairlist-config` (best use a regular config to create this, and remove everything other than the `exchange.pair_whitelist` / `exchange.pair_blacklist` structure). 

The "last" config in the command line will then overwrite everything that's before this.
