### ISSUE TITLE
Help needed with hyperopt/strategy. How do I access dataframe values?

### ISSUE THREAD

**Issue by gergokekesi** [freqtrade/freqtrade#4692]
## Describe your environment

  * Operating system: **Linux, 5.10.23-1-MANJARO** 
  * Python Version: **Python 3.9.2 (default, Feb 19 2021, 17:23:45)** 
  * CCXT version: **ccxt==1.42.19**
  * Freqtrade Version: **freqtrade 2021.2**
  
## Your question

Hi all,

I'm new to freqtrade and have been learning how it all works the past week or two. I have created a few strategies in the past on TradingView using PineScript and have something in mind that I wanted to implement in freqtrade. I don't have a huge amount of experience with Pandas and therefore I'm struggling to understand how to achieve the following in freqtrade:

I am calculating the SSL Channels using the technical package on a longer timeframe (lets say 2h) and resampling it back into the dataframe like this:
```
# Get all the different timeframe data into the dataframe
dataframe_long = resample_to_interval(dataframe, 120)
dataframe_long['sslDown_120'], dataframe_long['sslUp_120'] = SSLChannels(dataframe_long, 10)

# Combine the 2 dataframes
dataframe = resampled_merge(dataframe, dataframe_long, fill_na=True)
```

Then, I would like to run hyperopt to find what RSI values I should use when we are in an uptrend as per sslUp > sslDown and also when we are in a downtrend aka sslDown > sslUp. I'd also like my strategy to implement this. Here the problem though: I don't know how to get the values out from the dataframe. My current hyperopt buy strategy looks like this: 

```
 def populate_buy_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Buy strategy Hyperopt will build and use
            """
            conditions = []
            # GUARDS AND TRENDS

            if dataframe['sslUp_120'] > dataframe['sslDown_120']:

                conditions.append(dataframe['up-rsi'] > params['up-rsi-value'])

                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'buy'] = 1

                return dataframe

            elif dataframe.loc[dataframe['sslDown_120'] > dataframe.loc['sslUp_120']]:
                
                conditions.append(dataframe['down-rsi'] > params['down-rsi-value'])
                
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'buy'] = 1

                return dataframe

        return populate_buy_trend
```

This of course does not work as I can't access the dataframe like that. It returns the following error:

```
KeyError: 'sslDown_120'
```

How could I access the indicator value or maybe what would be a better way to write this optimisation/strategy? Basically all I am trying to achieve is use different rsi buy and sell values in an uptrend on a larger time-frame than what I use in a downtrend. Also, I'd like to be able to run this in hyperopt to find what would be the best value to use.

Thank you so much for reading and taking your time to answer!

**Comment by xmatthias** [comment]
columns from the resampled dataframe (out of `resampled_merge()`) will be prefixed with `resample_{timeframe_mins}_`.

so in your case, the column name should be `resample_120_sslDown_120` (the 120 is there twice as you already add this to the column name).

You should find a full example explaining the "renaming" that's going to happen in the [technical repository](https://github.com/freqtrade/technical#usage)

**Comment by gergokekesi** [comment]
Thanks a lot for the response. When I change the key I now get the following error: 

```
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```
This I think is because I'm accessing the dataframe the wrong way. How do I access the dataframe so I can get the indicator for the candle the hyperopt/strategy is currently processing?

**Comment by xmatthias** [comment]
you can't use `if` on dataframes the way you are. 

A dataframe is basically a table which contains multiple rows - so your "if" must apply to all rows at once (which it never will) - but pandas also prevents that from happening.

Your comparison should be vectorized ... so basically something around... (please verify yourself if this is fully correct, i just quickly copy/pasted your parts ...).

```

            dataframe.loc[
(
  (dataframe['sslUp_120'] > dataframe['sslDown_120']) & 
  (dataframe['up-rsi'] > params['up-rsi-value'])
) | 
(
  ( dataframe['sslDown_120'] > dataframe.loc['sslUp_120']) & 
  (dataframe['down-rsi'] > params['down-rsi-value'])
)
, 'buy'] = 1
```

**Comment by gergokekesi** [comment]
Thanks a lot, I was able to make it work like this!
