### ISSUE TITLE
Startup message display error

### ISSUE THREAD

**Issue by BigtoC** [freqtrade/freqtrade#4696]
https://github.com/freqtrade/freqtrade/blob/2cf36ca545d1df2bf5de50fa47afaea987ee5be6/freqtrade/rpc/rpc_manager.py#L93

`pairlist.short_desc()` cannot show my trade pair, it's displaying `{'StaticPairList': 'StaticPairList'}`. Suggest use `pairlist.whitelist` instead, for a quick fix.

**Comment by xmatthias** [comment]
It's very unclear what the problem is you're experiencing - or what you're even trying to do...

best refrase the initial post so others will understand what you mean with it too...
