### ISSUE TITLE
Fiat Display currency set to BTC wrong value

### ISSUE THREAD

**Issue by rylos** [freqtrade/freqtrade#4699]
## Describe your environment

  * Operating system: _ubuntu 20.04___
  * Python Version: _3.8____ (`python -V`)
  * CCXT version: __latest___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __develop__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

### Steps to reproduce:

I'm using USD as stake asset and BTC as fiat display currency and FTX exchange, this is the output of telegram balance command:
`Estimated Value:
 USD:  8763.62506112
 BTC: 0.42573691`

Correct value is USD.

**Comment by xmatthias** [comment]
Please fill out the issue template - as mentioned in the template (which you deleted) - i will otherwise close this issue without further comment.

**Comment by xmatthias** [comment]
well you're kinda using it backwards 😆 

the "fiat_convert" is mainly intended to convert crypto (BTC, ETH, ...) to a fiat (USD / EUR / ...).
By using USD as stake - and BTC as fiat - you're reversing this logic.

We're using coingecko for the conversion ... - and checking through their API, there is a (crypto) symbol with an "usd" id - which is "uniswap state dollar" - or "unified Stable Dollar" (which apparently is NOT the real dollar).

If i now convert this uniswap-state-dollar to usd, i get a rate of 2.83.
```
In [16]: [x for x in coinlistings if x['symbol'] == 'usd']
Out[16]:
[{'id': 'uniswap-state-dollar',
  'symbol': 'usd',
  'name': 'unified Stable Dollar'}]

In [18]: cg.get_price(ids='uniswap-state-dollar', vs_currencies='usd')
Out[18]: {'uniswap-state-dollar': {'usd': 2.83}}

# get uniswap -> btc conversion
In [19]: cg.get_price(ids='uniswap-state-dollar', vs_currencies='btc')
Out[19]: {'uniswap-state-dollar': {'btc': 4.886e-05}}
```

In the end, what you see as BTC is 8700 USD in BTC - but based on the assumption that the "USD" value is in "Uniswap state dollar" - not in "real US Dollars".

I don't believe this is something we can fix easily (other than by excluding BTC as fiat currency - or refusing to convert if USD is the stake currency) ... the best thing might be to not use BTC as fiat currency in this case, and rely on USD as fiat-currency instead.

**Comment by Fimap9to1** [comment]
Hello Matthias I get these logs sometimes since I put the giat display currency in eur (I use ftx), does this interfers with trading in dry run? 

2021-05-10 08:47:41,553 - freqtrade.rpc.telegram - INFO - Executing handler: _profit for chat_id: 604618814
2021-05-10 08:47:41,575 - freqtrade.rpc.fiat_convert - INFO - reversing Rates usd, eur
2021-05-10 08:47:41,579 - freqtrade.rpc.fiat_convert - WARNING - unsupported crypto-symbol eur - returning 0.0
2021-05-10 08:47:41,581 - freqtrade.rpc.fiat_convert - INFO - reversing Rates usd, eur
2021-05-10 08:47:41,582 - freqtrade.rpc.fiat_convert - WARNING - unsupported crypto-symbol eur - returning 0.0

Thanks for your help!

**Comment by xmatthias** [comment]
correct conversion assumes the market is available - which might not be the case for some currencies (especially for *DOWN / UP currencies).
Everything comming out of "fiat-convert" has no operational meaning and is only there for user reference.

**Comment by Fimap9to1** [comment]
Ok thanks! I actually use the bull and bear leveraged tokens. But it seems to work smoothly despite the "error". Thanks!
