### ISSUE TITLE
Missing buys when the whitelist is large

### ISSUE THREAD

**Issue by eleyvapro** [freqtrade/freqtrade#4701]
## Describe your environment

  * Operating system: macOs 11.2.3
  * Python Version: 3.9.2
  * CCXT version: 1.43.89
  * Freqtrade Version: 2021.3

## Your question
Hi guys, I noticed that when the whitelist is large _(47 pairs in my test case)_ many pairs are being ignored by `populate_buy_trend`, I found it when splitting in multiple docker instances with the same configuration, same strategy but distributed pairs, the behaviour started to be as expected in all of them. **(dry-run)**

I didn't find in the docs anything regarding a _"huge list of pairs could affect the bid strategy or something similar"_ but I understand, it could misbehave when more pairs are in place for monitoring.

- is there any advice or something what I can do in order to avoid this?
- assuming that I use the approach of splitting in multiples instances in **Live** with an exchange like Binance using the same _**IP address**_ and the same _**Binance account**_, might I get banned by the exchange? => [Check this out](https://www.freqtrade.io/en/latest/stoploss/#stoploss_on_exchange_interval)

## Confirmed, No apply these scenarios:
- no reached max_open_trades
- no protections were applied 
- no exceed stake_amount

## My config is simple like this:

```json
"max_open_trades": 12,
"amend_last_stake_amount": true,
"stake_currency": "USDT",
"stake_amount": "unlimited",
"tradable_balance_ratio": 0.99,
"fiat_display_currency": "USD",
"timeframe": "15m",
"dry_run": true,
"cancel_open_orders_on_exit": false
```

```json
"bid_strategy": {
    "price_side": "bid",
    "ask_last_balance": 0.0,
    "use_order_book": true,
    "order_book_top": 1,
    "check_depth_of_market": {
        "enabled": true,
        "bids_to_ask_delta": 1
    }
}
```

```python
dataframe.loc[
    (
            (qtpylib.crossed_above(dataframe['macd'], dataframe['macdsignal']))
            #& (dataframe['ema5'] < dataframe['ema10'])
           & (dataframe['ema5'] > dataframe['ema10'])
    )
    ,
    'buy'] = 1
```
## Some of the many missed pairs on the list

<img src="https://user-images.githubusercontent.com/66310922/114205241-c40d9000-9962-11eb-83a2-c7e55b31bb50.jpg" width="200" height="400">

<img src="https://user-images.githubusercontent.com/66310922/114206138-b7d60280-9963-11eb-9a9a-5e31b6a7ba17.jpg" width="200" height="400">

I appreciate any help!

**Comment by xmatthias** [comment]
buys will get ignored once your trade-slots (`max_open_trades`) are full.
As you specify 12 buys - the bot will stop checking for more buys once you're in 12 trades.

You can in theory run into timing issues if you run with many pairs on 1m candles - but for 5m or 15m candles, you'd have to do something pretty special to run into this (or have a insanely high ratelimit configured).


Without any logs - it'll be near impossible to help any further.

I would however doubt your signals - they don't trigger at the moments you show in the pictures ... 

in the "BNB" picture for example it would seem to me that on the MACD corss candle, eMA5 is above ema10 - so the 2nd line of your buy signal prevented the buy.

On the "luna" sample it's rather obvious that that's happening (yellow line is clearly above the Pink line).

**Comment by eleyvapro** [comment]
Sorry my bad, I was doing my tests before posting and this is the config from dry-run I meant:

```python
dataframe.loc[
(
        (qtpylib.crossed_above(dataframe['macd'], dataframe['macdsignal']))
        & (dataframe['ema5'] > dataframe['ema10'])
)
,
'buy'] = 1
```

So, do think that dealing with 15m timeframe shouldn't be an issue? Having some AI in `custom_stoploss` where the performance is not actually lightweight... could this affect `populate_buy_trend` ? this is all I need to know.

**Comment by xmatthias** [comment]
Make sure you're using the right strategy ... from all i know so far, it's very well possible that the same strategy is in the oflder twice, and the one that's actually running is NOT the one you think is.


"not actually lightweight" is quite broad - will analyzing this stoploss for one pair take more than a minute?
regular calculations should not have much of an impact ...

**Comment by eleyvapro** [comment]
what I can do is to run two instances with the same strategy and config etc, but one with `custom_stoploss` totally empty (return -1) and tracking if both of them are buying the same pars (also with high amount of max_open_trades, in order do not interfere) lets see if it custom_stoploss is responsible.

**Comment by xmatthias** [comment]
stoploss has nothing to do with buying.

As said, your badly copied sample suggests that you may have been running a different strategy than what you think you did.
Maybe you also have the same strategy-name twice in the strategy-folder - so the "first one" is loaded - whichever that is.
