### ISSUE TITLE
Changing pairlist while bot is running

### ISSUE THREAD

**Issue by johnwall293** [freqtrade/freqtrade#4702]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.9.2
  * CCXT version: 1.43.89
  * Freqtrade Version: 2021.3

  
## Your question

Hi, I want to change my bot pairlist while it running using some triggers. For example, due to lack of short positions, I want to  change my pairlist to buy only leverage coins which Binance offers. 
Something like, when the bot identify market going strong down, trade only *DOWN coins. 
Is there any way to do it?

**Comment by xmatthias** [comment]
well you can use `/reload_config` if you want to reload the config after having changed the pairlist.

An alternative is to "somehow" identify the conditions you're after, and then simply return no buy signal for the coins you're expecting.
that way it'll be "kinda" dynamic - based on your rules.

You can also see if one of the available [pairlist filters](https://www.freqtrade.io/en/latest/plugins/#available-pairlist-handlers) might help you accomplish what you want.
