### ISSUE TITLE
Documentation says I can use stake_amount="unlimited" in backtesting, when I try it gives me an error.

### ISSUE THREAD

**Issue by gergokekesi** [freqtrade/freqtrade#4704]
## Describe your environment

  * Operating system: Linux, 5.10.23-1-MANJARO
  * Python Version: Python 3.9.2 (default, Feb 19 2021, 17:23:45)
  * CCXT version: ccxt==1.42.19
  * Freqtrade Version: freqtrade 2021.2
  
## Your question

The documentation states that backtesting, dry run and hyperopt supports dynamic stake amount.

```
Dynamic stake amount
Backtesting supports dynamic stake amount by configuring stake_amount as "unlimited", 
which will split the starting balance into max_open_trades pieces. 
Profits from early trades will result in subsequent higher stake amounts, resulting in compounding of profits over the backtesting period.
```

However when I try to set the stake amount as unlimited, it does not work and gives me this error:
```
freqtrade - ERROR - The value of 'stake_amount' cannot be set as "unlimited" for backtesting
```

Does anyone know why this might be?

**Comment by xmatthias** [comment]
Please make sure to use the documentation corresponding to your version.

Support for unilmited stake in backtesitng was added in 2021.3 - you're using 2021.2 - so it's not available yet.

**Comment by gergokekesi** [comment]
Thanks! I'm using the docker image that came pre-setup. What's the easiest way to update the version so when I run a docker compose everything updated and it uses the latest freqtrade version?

**Comment by xmatthias** [comment]
depends on your compose definition i'd say.

IF you use `:stable` - use `docker-compose pull` - and then "up" it again ...
if you have the version in the compose file - then you need to change that first

**Comment by gergokekesi** [comment]
Docker-compose pull did the job :)
