### ISSUE TITLE
ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by WhoR3born** [freqtrade/freqtrade#4705]
https://pastebin.com/0dzg0NZN

i got this error can u help me
Failed installing dependencies
im running on digital ocean rdp

**Comment by xmatthias** [comment]
installing ta-lib will fail if the machine does not have ~2Gb of ram.

The error sounds like the compilation got killed as the machine ran out of memory. 
looking at the system logs (`journalctl`) should also show that a program was killed around that time.
