### ISSUE TITLE
Ta-Lib dependencies broken on Apple M1: Symbol not found: _TA_ACOS

### ISSUE THREAD

**Issue by tuomijal** [freqtrade/freqtrade#4712]
## Describe your environment

  * Operating system: macOS Big Sure Version 11.2.3
  * Python Version: Python 3.8.8
  * CCXT version: ccxt==1.46.38
  * Freqtrade Version: freqtrade develop-aaf9872e
 

## Describe the problem:

Ta-Lib dependencies don't work proprely on M1 Mac. Likely a ta-lib issue, please see discussion [here](https://github.com/mrjbq7/ta-lib/issues/408). Opening this in case setup.sh has to be updated. I tried installing as described below and also using conda with same results. I have:

```
▶ uname -a
Darwin Jalmari-MacBook-Air.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
```

### Steps to reproduce:

  1.  Have M1 Mac
  
  2. Install `freqtrade` by: 
 ```
git clone -b develop https://github.com/freqtrade/freqtrade.git 
cd freqtrade
./setup.sh --install
```

  3. Install Ta-Lib using
 ```
▶ brew --version
Homebrew 3.0.11

arch -arm64 brew install ta-lib
export TA_INCLUDE_PATH="$(brew --prefix ta-lib)/include"
export TA_LIBRARY_PATH="$(brew --prefix ta-lib)/lib"
```

4. Make sure there is `freqtrade/user_data/strategies/Strategy004.py`

5. `source .env/bin/activate`

4. `freqtrade backtesting --strategy Strategy004`
  
### Observed Results:
  
Terminal error, see logs below. Was expecting lots of virtual profit. 

### Relevant code exceptions or logs

  ```
2021-04-11 09:13:01,111 - freqtrade.resolvers.iresolver - WARNING - Could not import /Users/jalmarituominen/fun/freqtrade/user_data/strategies/fixed_riskreward_loss.py due to 'dlopen(/Users/jalmarituominen/fun/ta-lib/talib/_ta_lib.cpython-38-darwin.so, 2): Symbol not found: _TA_ACOS
  Referenced from: /Users/jalmarituominen/fun/ta-lib/talib/_ta_lib.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/jalmarituominen/fun/ta-lib/talib/_ta_lib.cpython-38-darwin.so'
2021-04-11 09:13:01,111 - freqtrade - ERROR - Impossible to load Strategy 'Strategy004'. This class does not exist or contains Python code errors.
  ```

This is likely out of `freqtrade`s scope and to-be-fixed on ta-lib side but take this as a FYI if nothing else. Works great on my other machines. Thank you @xmatthias for beautifully written software 👍🏼

**Comment by xmatthias** [comment]
Now to be honest, i don't particularily care about Apple M1 at the moment.
I don't own one, and i don't plan on owning one anytime soon - so if it happens to work, great - otherwise please consider it unsupported for now.

As far as i understand, M1 can run python in 2 modes, emulated or native ... while i understand the benefits / drawbacks - i think your experience installing will vary between the two.

You'll however also encounter further problems after having solved this - ta-lib is only the first issue - tables (another dependency) will probably also give you problems installing as wheels are missing - and i'd expect similar things with other repositories too.

---

It's a ta-lib issue for sure - but currently i don't see any changes (or which changes) that would need to happen to `setup.sh`.

installing ta-lib (the C dependency) from brew will result in a "slightly wrong" ta-lib (it will not work for most */BTC pairs due to a precision error - but shouldn't cause problems for USDT pairs ... ).

We therefore use a slightly modified version of ta-lib (see [this](https://github.com/freqtrade/freqtrade/blob/develop/build_helpers/install_ta-lib.sh) file on the modification done) ) - which needs to be compiled from source to work correctly.

---

your issue lacks the most important thing - which is the logs of it failing out of `./setup.sh --install`.
I understand ta-lib recommending brew as installation method - but that doesn't seem to work either, so i'd wait for the outcome / fix of the ta-lib issue before even looking any further.

**Comment by tuomijal** [comment]
Then only error that is thrown by `./setup.sh --install` is:

```
Fixing Python
-------------------------
Python 3.6 is not linked in your system. Fixing it...
Error: No such keg: /opt/homebrew/Cellar/python@3.9
```

Otherwise
```
Installing collected packages: freqtrade
  Running setup.py develop for freqtrade
Successfully installed freqtrade
pip install completed
```

Thank you for immediate response and keep up the good work 👍🏼

**Comment by JamesGDiaz** [comment]
@tuomijal How did you manage to install this on a M1 Mac?

I installed python3.9 via Brew (native M1 version) and I get the same warning as you, except mine doesn't error out.

```Installing mandatory dependencies
-------------------------
macOS detected. Setup for this system in-progress
ta-lib already installed, skipping
-------------------------
Fixing Python
-------------------------
Python 3.6 is not linked in your system. Fixing it...
Warning: Already linked: /opt/homebrew/Cellar/python@3.9/3.9.4
To relink:
  brew unlink python@3.9 && brew link python@3.9
```

TA_LIB installed without issues, but when it gets to installing python dependencies, it fails on pandas/numpy. 
I understand that there's no version of pandas or numpy compiled for the M1 chip, so I ran my terminal using Rosetta, but it still fails
```
ERROR: Could not find a version that satisfies the requirement pandas==1.2.3
ERROR: No matching distribution found for pandas==1.2.3
```

Maybe its wiser to do keep doing this on my Linux box though haha

**Comment by ghost** [comment]
I managed to get Freqtrade running natively on M1 via [Miniforge](https://github.com/conda-forge/miniforge), this is a modified version of Miniconda with many packages ready for ARM processors.

First install via Brew:
```
brew install hdf5
brew install c-blosc
brew install gcc
brew install wget
brew install --cask miniforge
conda init zsh # to activate conda on startup of terminal
```

TA-Lib had same dependency issues, and followed a mix of this [site](https://mikestaszel.com/2021/01/23/install-ta-lib-on-m1/) and recommendations in this issue https://github.com/freqtrade/freqtrade/issues/1158#issuecomment-413964232  :
```
wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
tar zxvf ta-lib-0.4.0-src.tar.gz
cd ta-lib
wget 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD' -O config.guess
wget 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' -O config.sub
sed -i.bak "s|0.00000001|0.000000000000000001 |g" src/ta_func/ta_utility.h
./configure --prefix=/usr/local
make
sudo make install
cd ..
rm -rf ta-lib
rm ta-lib-0.4.0-src.tar.gz
```
Then get Freqtrade from Github:
```
mkdir freqtrade
cd freqtrade
git clone https://github.com/freqtrade/freqtrade.git . # add the . to clone into current folder
git checkout stable
```
end then edit the environment.yml file with your preferred editor, note that I am not using the dev or plot section:
```
name: freqtrade
channels:
  - conda-forge
# - defaults
dependencies:
# 1/4 req main
    - python=3.9 # changed
    - numpy
    - pandas
    - pip
    - cython # added, not sure if really needed
    - aiohttp
    - SQLAlchemy
    - python-telegram-bot
    - arrow
    - cachetools
    - requests
    - urllib3
    - wrapt
    - jsonschema
#    - TA-Lib # this is moved to pip section
    - tabulate
    - jinja2
    - blosc
    - sdnotify
    - fastapi
    - uvicorn
    - pyjwt
    - colorama
    - questionary
    - prompt-toolkit
    - python-rapidjson # added
    - pytables # added

    # ============================
    # 2/4 req dev

#    - coveralls
#    - flake8
#    - mypy
#    - pytest
#    - pytest-asyncio
#    - pytest-cov
#    - pytest-mock
#    - isort
#    - nbconvert

    # ============================
    # 3/4 req hyperopt

    - scipy
    - scikit-learn
    - filelock
    - scikit-optimize
    - joblib
    - progressbar2
    # ============================
    # 4/4 req plot

 #   - plotly
 #   - jupyter

    - pip:
        - pycoingecko
        - py_find_1st
#        - tables # moved to first section
#        - pytest-random-order # not using dev version
#        - flake8-type-annotations # not using dev version
        - TA_Lib # added
        - blosc # added
        - ccxt
 #       - flake8-tidy-imports # not using dev version
        - -e .
```
Some notes about that:
- python can be fixed to 3.9, which i think is optimized for M1. It is much faster as 3.7
- I have added cython as I saw it in the Pi version, not sure if needed for M1
- TA-Lib is not ready on conda-forge for M1, so install via pip
- pytables is available on conda-forge for M1, so can move from pip section

blosc is shown both on first section and pip section, but in fact those are 2 different items:
- conda-forge blosc in first section refers to the library: https://anaconda.org/conda-forge/blosc/ with version 1.21.0 which is on github at https://github.com/Blosc/c-blosc
- pip blosc refers to the wrapper: https://pypi.org/project/blosc/ with version 1.10.2 which is at https://github.com/Blosc/python-blosc

Then create the conda environment, install technical library, and check version of Freqtrade:
```
conda env create -n ftc -f environment.yml
conda activate ftc
pip install git+https://github.com/freqtrade/technical
freqtrade -V
conda deactivate
```
I also managed to build a Docker image which runs a Linux ARM version under Docker for Mac and is very fast, i will post a bit later as I need to recheck the steps for that.

**Comment by ghost** [comment]
As mentioned in previous comment, i have a docker image working for M1 based on the ARM version of Linux. This also had same issue with broken dependencies for TA-Lib, as well as some further difficulties with tables and blosc.

First install Docker for Mac, the M1 version is now at RC3: https://docs.docker.com/docker-for-mac/apple-m1/

I use a separate folder to build the docker image:
```
mkdir ftm1
cd ftm1
git clone https://github.com/freqtrade/freqtrade.git . #(the . clones into current folder)
git checkout stable
```
modify the helper files for TA-Lib to fix the dependency issues:
```
cd build_helpers
tar zxvf ta-lib-0.4.0-src.tar.gz
cd ta-lib
rm config.guess
rm config.sub
wget 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD' -O config.guess
wget 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' -O config.sub
cd ..
tar czf ta-lib-0.4.0-src.tar.gz ta-lib
rm -rf ta-lib
cd ..
```
inside ftm1 folder create a file: Dockerfile.M1
```
FROM --platform=linux/arm64/v8 python:3.9-slim-buster as base

# Setup env
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1
ENV PATH=/root/.local/bin:$PATH

# Prepare environment
RUN mkdir /freqtrade
WORKDIR /freqtrade

# Install dependencies
FROM base as python-deps
RUN apt update \
    && apt-get -y upgrade \
    && apt-get -y install curl build-essential pkg-config libblosc-dev cmake libhdf5-dev libssl-dev git \
    && apt-get -y autoremove \
    && apt-get clean \
    && pip install --upgrade pip

# Install TA-lib
COPY build_helpers/* /tmp/
RUN cd /tmp && /tmp/install_ta-lib.sh && rm -r /tmp/*ta-lib*
ENV LD_LIBRARY_PATH /usr/local/lib

# Install dependencies
COPY requirements.txt requirements-hyperopt.txt /freqtrade/
RUN  pip install --user --no-cache-dir numpy==1.20.2 \
  && pip install --user --no-cache-dir h5py==3.2.1 \
  && pip install --user --no-cache-dir -r requirements-hyperopt.txt \
  && pip install git+https://github.com/freqtrade/technical


# Copy dependencies to runtime-image
FROM base as runtime-image
COPY --from=python-deps /usr/local/lib /usr/local/lib
ENV LD_LIBRARY_PATH /usr/local/lib

COPY --from=python-deps /root/.local /root/.local

# Install and execute
COPY . /freqtrade/
RUN pip install -e . --no-cache-dir \
  && mkdir /freqtrade/user_data/ \
  && freqtrade install-ui

ENTRYPOINT ["freqtrade"]
# Default to trade mode
CMD [ "trade" ]
```
in the ftm1 folder edit the docker-compose.yml file, remove the link to the image on docker hub, and set build context to the above Dockerfile.M1
```
---
version: '3'
services:
  freqtrade:
    build:
      context: .
      dockerfile: "./Dockerfile.M1"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
```
In Docker for Mac assign sufficient resources as the build process takes very long, it needs to compile several python packages.

Then issue command: `docker-compose build`

Then: `docker images` and it will show your docker image as ftm1_freqtrade

I use a separate folder for building the image and running freqtrade. For example create a folder: ftrun

Inside folder ftrun create a docker-compose.yml which links to the image built in previous steps:
```
---
version: '3'
services:
  freqtrade:
    image: ftm1_freqtrade:latest
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
```

Then check if its working: `docker-compose run --rm freqtrade -V`

Create the user_data folder: `docker-compose run --rm freqtrade create-userdir --userdir user_data`

Copy your config and strategies, and ready to go.

Did a hyperopt with -e 100 on my previous Macbook Pro 2014 (4 cores/8 threads):
- standard docker:  2m 20sec
- miniconda: 1m 40 sec

Now on the M1 (8 cores Mac Mini):
- AMD64 docker image as on Docker Hub Freqtrade: 9m 30s (extremely slow)
- miniforge as mentioned in previous comment with Python 3.9: 44 sec
- self built docker file Python 3:7: 1m 8 sec
- self built docker file Python 3:8: 46 sec
- self built docker file Python 3:9: 44 sec 

Did same test on a Google Cloud C2 (compute optimized VM) with 8 cores: 1m 7 sec

Python 3.9 on the new M1 is indeed very fast.

**Comment by xmatthias** [comment]
I'm ... sceptical about performance measurements in these cases ... 
as you've switched pc, your disk performance (for loading data) will also play a role.

I've however never claimed that M1 is slow ... only that it's currently difficult to support as many wheels are missing, which makes installation a pain (i'd therefore never have bought one - as i'd expect problems / investigations around every new package i'd want to install).

> I have added cython as I saw it in the Pi version, not sure if needed for M1

try it without that - if installation fails, you'd have needed cython :laughing: 
It's a build-dependency for a package (don't remember which one - sorry) ... and i assume wheels will not be available.

---

Now the problem is - the build (docker build) will need to be repeated for updates / dependency updates - which makes it still difficult to really support.
Giving the M1 architecture a year or two i hope most packages / wheels will catch up and support will be wider - but until then i'd consier it a "edge" architecture ... :)

**Comment by tuomijal** [comment]
I'm impressed by the work @boschje documented above. However, I do think that at least for now the most convenient way to get up and running is using Rosetta 2. So just in case someone else is willing to simply run `freqtrade` on M1 Mac but doesn't care about native M1 support: 

1. select `Terminal.app` on applications, press `cmd + I` and check "Open using Rosetta".
2. install brew and make sure you don't have a conflicting `arm64` version obscuring the namespace
3. `brew install ta-lib`
4. `cd freqtrade && ./setup.sh -i`

Closing this at least for a year or two 😉
