### ISSUE TITLE
install error on python 3.9 windows

### ISSUE THREAD

**Issue by HAGAI123** [freqtrade/freqtrade#4716]
Using cached tables-3.6.1.tar.gz (4.6 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\hagaybot\freqtrade-develop\freqtrade\.env\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\pip-install-6dlziuib\\tables_787f93fa7ad54ee6b85934228272c27d\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\pip-install-6dlziuib\\tables_787f93fa7ad54ee6b85934228272c27d\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Administrator\AppData\Local\Temp\2\pip-pip-egg-info-k5g35ihm'
         cwd: C:\Users\Administrator\AppData\Local\Temp\2\pip-install-6dlziuib\tables_787f93fa7ad54ee6b85934228272c27d\
    Complete output (9 lines):
    H5closenqdpftgf.c
    C:\Users\ADMINI~1\AppData\Local\Temp\2\H5closenqdpftgf.c(2): warning C4013: 'H5close' undefined; assuming extern returning int
    LINK : fatal error LNK1181: cannot open input file 'hdf5.lib'
    * Using Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)]
    * USE_PKGCONFIG: False
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2b/32/847ee3f521aae6a0be380d923a736162d698586f444df1ac24b98c65025c/tables-3.6.1.tar.gz#sha256=49a972b8a7c27a8a173aeb05f67acb45fe608b64cd8e9fa667c0962a60b71b49 (from https://pypi.org/simple/tables/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tables==3.6.1
ERROR: No matching distribution found for tables==3.6.

**Comment by xmatthias** [comment]
While you don't provide any information (usually i close issues that don't fill out the issue template, or even ask a question) - it seems like youre on 3.9 for windows.

You should downgrade to python 3.8 - one of the dependencies (pytables) doesn't have a wheel for python 3.9 yet - which means the installation will fail.

related: https://github.com/PyTables/PyTables/issues/823

**Comment by wr0ngc0degen** [comment]
@xmatthias I stumbled upon the same problem with creating the conda environment from environment.yml (I'm on Mac but since I'm using conda I'd say it's not very important). I "solved" it by changing a line in environment.yml from `python>=3.7` to `- python>=3.7,<3.9`. I can create a PR with this change if you think it's appropriate. Apologies in advance if it's not the right place to leave this comment

**Comment by xmatthias** [comment]
i guess for the time beeing that's a good approach - as conda is "mostly" used on windows (and mac) - i'd say that's a pretty safe solution.
