### ISSUE TITLE
I have new pairs to trade every 5 minutes. How can I trade a new list of tickers on each bot iteration?

### ISSUE THREAD

**Issue by aiforinvesting** [freqtrade/freqtrade#4727]
I have an external code that generates a new pairlist every 5 minutes and saves it on csv or txt file. how do I get the bot to update the pairlist. I actually have done it by updating the json.config's whitelist every 5 minutes and reloading the file /reload_config but this process takes 40 seconds and that's way to slow and unnecessary to load the whole bot just for changing the pair list. Please help.. I need an efficient way to trade newly selected pairs every 5 minutes?

**Comment by xmatthias** [comment]
This is currently not possible.

Feel free to track / subscribe to #4493 (or even give implementing that a try) - which aims to give such a possibility in the future - but work on it did not start yet as far as i know

**Comment by aiforinvesting** [comment]
def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        tickers = []
        with open('tickers.txt', 'r') as filehandle:
            for line in filehandle:
                # remove linebreak which is the last character of the string
                ticker = line[:-1]
                # add item to the list
                tickers.append(ticker)
        print(metadata['pair'])
        print(type(metadata['pair']))
        dataframe.loc[
            (
                # Signal: RSI 
                (dataframe['rsi'] > 0)  &
                (metadata['pair'] in tickers)
            ),
            'buy'] = 1

        return dataframe
