### ISSUE TITLE
Hyperopt custom_stoploss()

### ISSUE THREAD

**Issue by us** [freqtrade/freqtrade#4728]
## Environment

  * Operating system: osx and linux
  * Python Version: 3.9 
  * CCXT version: 1.45.44 
  * Freqtrade Version: develop-73ce266b
  
## Question

How can I hyperopt my `custom_stoploss` function?

custom_stoploss
```
 def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:

        if current_profit > 0.40:
            c_stoploss = stoploss_from_open(0.25, current_profit)
        elif current_profit > 0.25:
            c_stoploss = stoploss_from_open(0.15, current_profit)
        elif current_profit > 0.20:
            # setup price from buy trade buy price
            c_stoploss = stoploss_from_open(0.07, current_profit)

        if current_time - timedelta(minutes=120) > trade.open_date_utc:
            return -0.05
        elif current_time - timedelta(minutes=60) > trade.open_date_utc:
            return -0.10

        return c_stoploss

```

**Comment by xmatthias** [comment]
With the new [hyperopt interface](https://www.freqtrade.io/en/latest/hyperopt/#solving-a-mystery) (using strategy parameters) - you should be able to abuse either the buy or sell space and "sneak" a parameter in.

obviously you'll need to use that space then (e.g. the sell space) - but this parameters will then be optimized along the other sell parameters.
as you can enable / disable parameter optimization with a flag, this should work for now.

We'll probably add a "custom" hyperopt space in the future, which will simplify / streamline this behaviour - but for now, the above should work.
