### ISSUE TITLE
How to get just the buy actions of my strategy

### ISSUE THREAD

**Issue by AmirHoseinSafari** [freqtrade/freqtrade#4729]
## Your question

Hi,

I am looking for a way to see just the buy actions of my strategy.

In more details, when I run my strategies using the command below:
`freqtrade trade --strategy Strategy001
`
I will get the bunch of logs and etc. so my question is that how can I see just the "buy actions" and then report it via an API?

I will be very thankful if you can help me with this.

Sincerely,
Amir

**Comment by xmatthias** [comment]
freqtrade is a trading bot (executing buy / sell orders for you), not a signal bot (signaling you when to buy).

The logs are there mainly to help people report issues, and will therefore be slightly verbose in certain areas (especially around buys and sells).
You can use [webhooks](https://www.freqtrade.io/en/latest/webhook-config/) to get notifications of buy and sell actions - but freqtrade will execute these (either for real, or as simulated trades).
