### ISSUE TITLE
Notice to API Users on Delisting WAPI Endpoints

### ISSUE THREAD

**Issue by bendenn** [freqtrade/freqtrade#4731]
Notice to API Users on Delisting WAPI Endpoints

Fellow Binancians,

To optimize API performance and provide better trading services for our API users, Binance will delist all WAPI endpoints from the Binance API at 2021-08-01 2:00 AM (UTC). Information on WAPI endpoints will be removed from Binance API Documentation at approximately 2021-06-01 2:00 AM (UTC). 

To ensure your trading strategies are not affected, all API users are encouraged to upgrade trading bots to SAPI endpoints as soon as possible.

**Comment by xmatthias** [comment]
Thanks for the info - i got the email too.

i do not think freqtrade is affected by this, as we use the regular API endpoints, not WAPI endpoints.

If any, then changes will be needed at [ccxt](https://github.com/ccxt/ccxt) level ... but again, i don't think it'll affect us as we don't use any endpoint that uses Wapi as far as i am aware.

**Comment by xmatthias** [comment]
I'll close this as we do not use any ccxt endpoints which are currently using wapi.
