### ISSUE TITLE
Suggestion /stakeamount command

### ISSUE THREAD

**Issue by tutecode** [freqtrade/freqtrade#4733]
It could be great can modify the stake amount by a command Telegram.

**Comment by xmatthias** [comment]
The short answer is no.

the usual (assumed) need for this is to increase the stake if trades go well and the account increases, which can be done by setting `stake_amount` to unlimited (`stake_amount="unlimited"`).

It'd also not play well with other enhancements like #3886 or #4715 - which would be blocked / prevented by such a feature.
