### ISSUE TITLE
Strategies need a `custom_roi()` interface method (as there is a `custom_stoploss()`)

### ISSUE THREAD

**Issue by avibrazil** [freqtrade/freqtrade#4735]
Need to set different ROI parameters for each pair. This is currently impossible.
But would be possible if there is a `custom_roi()` interface to be implemented.

**Comment by xmatthias** [comment]
We will not implement a custom ROI interface, it would not make any sense (ROI is just an automated sell signal).


Best subscribe to #4276 which, if implemented according to my ideas, will give something similar to a "custom_stoploss" method but as sell signal, not as minimal ROI.

Obviously you can simulate something similar to ROI in that function - but a explicit "custom roi" method would be too limiting.

**Comment by avibrazil** [comment]
#4276 will work for me. Thanks.
