### ISSUE TITLE
hyperopt parameter to select single pair for execution

### ISSUE THREAD

**Issue by avibrazil** [freqtrade/freqtrade#4736]
I may be wrong, but it seems to me that it doesn't make sense to find best parameters (roi, stoploss etc) for all desired pairs at once. Each pair might have very different characteristics.

Either add a command line parameter for hyperopt to define the pair to run tests.
Or hyperopt should return a set of parameters (roi, stoploss etc) for each pair.

**Comment by xmatthias** [comment]
Please understand that this is a free, open source project, so please change your tone to not be demanding ("either add...") but instead requesting (or offering to implement things yourself). you're not paying for it, so you have little right to demand a feature - but obviously all rights to request features.

Please use the provided issue templates - and fill them out. Sometimes the information is not needed - but if it is, it creates unnecessary back and forth, and causes a waste of time on both sides.


Optimizing for one pair is generally a rather bad idea. It'll lead to overfitting, and the resulting strategy will then not generalize well and will be based on the assumption that the pair will behave exactly the same in the future (which is usually not the case).

You can also do this pretty easily already if you think it's a must.

Simply change your pair-whitelist to the one pair you'd like to optimize. You can also use multiple configurations (`--config config1.json --config config_xrp.json`) - with the second pair only having the structure for pair_whitelist contained - that way you don't have to change your "Main" configuration.

**Comment by avibrazil** [comment]
I was obviously not demanding anything, please forgive my tone. I was just trying to be the most objective possible.

I’ll think about your suggestions. I didn’t know about configuration stacking as you showed.

Although I understand what you are saying about overfitting, there might be strategies based on technical analysis that are pair-specific. Again, I might be wrong, but running the optimizer against multiple coins at once to find best RSI and Bollinger parameters would yield confusing results.

**Comment by xmatthias** [comment]
if your strategy is going to be pair-specific, you'll have to run one bot per pair anyway (or combine it within the strategy based on if/else conditions - which can get messy very soon).

You can get around this by using a `rsi_XRP` parameter which only applies for this pair - but you'll waste a lot of time hyperopting where that parameter is not even used for most of the pairs.

In short - i see this too easy/simple to get around by simply running one hyperopt per pair to complicate hyperopt creation and potentially breaking it for people who search strategies that are more ... general applicable.

**Comment by avibrazil** [comment]
I did it it in a different way, and your comment is raising doubts on me if I did it right.

My strategy has per-pair configs as:

```
pair_config = {
      "BTC/USDT": {
        'buy_params': ...
        'sell_params': ...
        'stoploss': -0.13735
      },
      "XRP/USDT": {
        'buy_params': ...
        'sell_params': ...
        'stoploss': -0.33
}
```

They were computed by multiple single-pair hyperopts runs.

Then my buy and sell trends are populated using the pair as parameter:

```
 def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        if self.pair_config[metadata['pair']]['buy_params']['buy-rsi-enabled']:
          dataframe.loc[
              (
                  (dataframe['rsi'] > self.pair_config[metadata['pair']]['buy_params']['buy-rsi-value']) &
                  (dataframe['close'] < dataframe[self.pair_config[metadata['pair']]['buy_params']['buy-trigger']])
              ),
              'buy'
          ] = 1
        else:
          dataframe.loc[
              (dataframe['close'] < dataframe[self.pair_config[metadata['pair']]['buy_params']['buy-trigger']]),
              'buy'
          ] = 1

        return dataframe

```

Note the use of `metadata['pair']`.
I started with freqtrade this week so I appreciate any suggestions and lectures.

Thank you in advance

**Comment by xmatthias** [comment]
if it works for you ... i'll not complain.


you'll however have to use custom_stoploss for the stoploss - the normal stoploss is global and cannot safely be changed per pair. 

As said above though - in my personal experience / view you'll end up with overfitted strategies that work well on how that pair performed in the past - but that's no guarantee that it'll work for the future where the pair moves ever so slightly differently - therefore a optimization over multiple / many pairs is usually better.

**Comment by avibrazil** [comment]
Yes, I have a `custom_stoploss()`.
Thank you
