### ISSUE TITLE
Custom stoplosses only when no active order

### ISSUE THREAD

**Issue by peacefulbadger** [freqtrade/freqtrade#4739]
## Describe your environment

  * Operating system: Windows 10 w/ WSL2
  * Python Version: Python 3.8.5 x64 (Conda) (`python -V`)
  * CCXT version: 1.47.66 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade docker-aaf9872e (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

I've been trying to write an ATR stoploss/take-profit test function for the past couple days that only updates while there is no current order active. After digging through the libs, I found the `Order.get_open_orders` function in `freqtradebot.py` which looks like it would do the trick. However, when trying to call it, I receive a `AttributeError: type object 'Order' has no attribute 'query'` error back. If I'm reading the documentation correctly, I shouldn't need to pass it an attribute. When I pass something random like `self` as a test, it returns back `TypeError: get_open_orders() takes 0 positional argument`. Am I overlooking something?

```
def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime, current_rate: float, current_profit: float, **kwargs) -> float:

        if self.custom_info and pair in self.custom_info and trade and not (len(Order.get_open_orders()) > 0):
            if self.dp and self.dp.runmode.value in ('backtest', 'hyperopt'):
                atr_sl = self.custom_info[pair].loc[current_time]['atr'] 
                sl = ((current_rate - atr_sl) / current_rate) - 1
                self.minimal_roi[0] = float(abs(sl))
                return sl
            else:
                dataframe, last_updated = self.dp.get_analyzed_dataframe(pair=pair, timeframe=self.timeframe)
                atr_sl = dataframe['atr'].iat[-1]
                sl = ((current_rate - atr_sl) / current_rate) - 1
                sl = round(sl, 5)
                self.minimal_roi[0] = float(abs(sl))
                return sl

```
Thank you for reading.

**Comment by xmatthias** [comment]
Orders are not relevant during backtesting - backtesting assumes all orders fill immediately. The method you "found" is not intended to be used in a strategy - especially not during backtesting).

the Order class is not documented for users - and should not be used either (it may change at any point in time without notice).

Instead, you can use the `trade.open_order_id` and `trade.stoploss_order_id`. They will be empty for backtesting (not relevant) - and will be filled when an order is placed.
`stoploss_order_id` is only used when "stoploss_on_exchange" is used.

**Comment by peacefulbadger** [comment]
Thanks for the response, this makes sense for live trading. I would guess it also applies to dry-runs. 

In that case is there anyway to stop the `custom_stoploss` from behaving like a trailing stoploss? Both the [custom ATR stoploss example documented](https://www.freqtrade.io/en/latest/strategy-advanced/#custom-stoploss-using-an-indicator-from-dataframe-example) and the version I currently have implemented keep updating the TP/SL variables after each candle.

My goal is to prevent `custom_stoploss` from recalculating every candle. I thought about setting a boolean like `self.stoploss_set = True` when setting the TP/SL, and then checking if the `self.stoploss_set == False` as an additional if condition. This works to prevent `custom_stoploss` from recalculating, but I can't figure out a way to set `self.stoploss_set = False` again once the trade is exited. I've tried using `confirm_trade_exit` but it only seems to work with exits generated by `populate_sell_trend`. Is there some other way or helper function that does X when an exit occurs by `roi`, `stoploss`, `trailing_stop` and `populate_sell_trend` during backtesting? A function like `buy_was_made_this_candle` would also work but I haven't seen anything like that yet. 

```
class test(IStrategy):
    INTERFACE_VERSION = 2
    minimal_roi = {"0": 100,}

    use_custom_stoploss = True    
    custom_info = {}   
    stoploss_set = False


    def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime, current_rate: float,
                        current_profit: float, **kwargs) -> float:

        if self.custom_info and pair in self.custom_info and trade and self.stoploss_set == False:
            if self.dp and self.dp.runmode.value in ('backtest', 'hyperopt'):
                atr_sl = self.custom_info[pair].loc[current_time]['atr'] 
                sl = ((current_rate - atr_sl) / current_rate) - 1
                self.minimal_roi[0] = float(abs(sl))
                self.stoploss_set = True
                return sl
            else:
                dataframe, last_updated = self.dp.get_analyzed_dataframe(pair=pair, timeframe=self.timeframe)
                atr_sl = dataframe['atr'].iat[-1]
                sl = ((current_rate - atr_sl) / current_rate) - 1
                sl = round(sl, 5)
                self.minimal_roi[0] = float(abs(sl))
                self.stoploss_set = True
                return sl

    def confirm_trade_exit(self, pair: str, trade: Trade, order_type: str, amount: float,
                           rate: float, time_in_force: str, sell_reason: str, **kwargs) -> bool:
        self.stoploss_set = False
        return True    

    def populate_buy_trend(self, dataframe: 'DataFrame', metadata: dict) -> 'DataFrame':
        dataframe['sslDown'], dataframe['sslUp'] = SSLChannels(dataframe, length=14)
        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['sslUp'], dataframe['sslDown'])) &            
            ), 'buy'] = 1
        return dataframe        

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        pass
        return dataframe      
```

**Comment by xmatthias** [comment]
well it the return value is made to make trailing simple (so it's a % below the current value the stop should be placed).
If you want it static, simply return a big value (bigger than the initial one) - stoplosses will never move lower, only higher.

Setting things to "self." will fail you as the strategy is not per pair (so the same `self.` is shared between all pairs )  and the data is not persisted, so a restart will cause the data to be gone.

an easy way is probably to compare trade.stoploss with trade.initial_stoploss - if the 2 are identical, the stop was never changed - if the 2 are different, the price "started to trail" at least once.

**Comment by peacefulbadger** [comment]
Setting a progressively bigger SL value works in practice but in theory doesn't really work. Since increasing the SL size would be the same as just increasing the risk.

I just ran a quick test with `Trade.stop_loss` and `Trade.initial_stop_loss` and they work perfectly in live trading but as expected don't work in backtesting/hyperopt (since they're empty). I guess this is just the side effects of having vectorized backtesting but event driven live-trading?

**Comment by xmatthias** [comment]
they may be empty in `populate*` methods (which are vectorized), but they will be populated in the custom_stoploss method.
