### ISSUE TITLE
2 and 4 hour candles.

### ISSUE THREAD

**Issue by chppppp** [freqtrade/freqtrade#474]
Add support for user defined candles e.g. `2` or `4`hour, that are not supported by the exchanges.

**Comment by glonlas** [comment]
You should express your request properly in the content of this issue. Otherwise, it will be ignored.

**Comment by chppppp** [comment]
Creating an issue of "using 2 and 4 hour candles doesnt work" seemed silly since the response would be "these do not exist from bittrex api". Regardless, I filled out the issue properly.

**Comment by kryofly** [comment]
Isn't there a github tag/label that says feature-request?
Anyway I guess a tick resampler should be useful, it could take on an adjustable stochastic property which I guess would make more sense in backtesting/hyperopt.

**Comment by shusso** [comment]
Edited the description and title. This is a valid enhancement. Thank you @chppppp

**Comment by cofibit** [comment]
Really hoping this gets pushed.

**Comment by gcarq** [comment]
When `feat/objectify-ccxt` is merged these are the supported ticker intervals:

```
TICKER_INTERVAL_MINUTES = {
    '1m': 1,
    '5m': 5,
    '15m': 15,
    '30m': 30,
    '1h': 60,
    '2h': 120,
    '4h': 240,
    '6h': 360,
    '12h': 720,
    '1d': 1440,
    '1w': 10080,
}
```

**Comment by xmatthias** [comment]
@berlinguyinca's technical repository https://github.com/berlinguyinca/technical/blob/master/technical/util.py has resample-methods available - which will allow indicators on resampled intervals which are not available directly from the exchange.

**Comment by shusso** [comment]
should be fixed
