### ISSUE TITLE
Stange difference of data between pair_whitelist and informative_pairs

### ISSUE THREAD

**Issue by Th0masL** [freqtrade/freqtrade#4745]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.8
  * CCXT version: 1.47.47
  * Freqtrade Version: 2021.3

## Describe the problem:

I've been testing and using the informative_pairs functionality to extract data about BTC/USDT pair, so I can verify how BTC behave compared to the current pair.

Out of curiosity I did a "stupid" test of using BTC/USDT as pair_whitelist at the same time as I use BTC/USDT as informative_pair.

I was expecting that the data between BTC/USDT from pair_whitelist and BTC/USDT from informative_pair would be the same, but after plotting the result there are some strange differences.

![Screenshot from 2021-04-16 01-40-12](https://user-images.githubusercontent.com/25387544/114948069-fdf4ff80-9e56-11eb-8ec6-fc55c14781c2.png)

### Steps to reproduce:

  1. Download the strategy below
  2. Set "USDT" as stack_currenty and pair_whitelist as "BTC/USDT" in config.json
  3. Run backtest and generate the plot with the commands below

### Observed Results:

  * What happened?
  For an identical pair, there are differences between the data from pair_whitelist and the data from informative_pairs
  * What did you expect to happen?
  The data to be identical

### Relevant code exceptions or logs

Strategy :

```
from freqtrade.strategy import IStrategy
from pandas import DataFrame
import freqtrade.vendor.qtpylib.indicators as qtpylib

class TestStrat(IStrategy):

	trailing_stop = True
	trailing_stop_positive = 0.02
	trailing_stop_positive_offset = 0.04
	trailing_only_offset_is_reached = True

	timeframe = "1h"

	use_sell_signal = False

	minimal_roi = {
		"0": 100
	}

	stoploss = -0.1

	plot_config = {
		'main_plot': {
			'bb_lowerband': {
				'color': 'rgba(255,255,255,0)',
				'fill_to': 'bb_upperband',
				'fill_label': 'BollingerBand20',
				'fill_color': 'rgba(0,176,246,0.2)'
			},
			'bb_upperband': {
				'color': 'rgba(255,255,255,0)',
			},
			'bb_middleband': {},
			'btc_bb_lowerband': {
				'color': 'rgba(255,255,255,0)',
				'fill_to': 'btc_bb_upperband',
				'fill_label': 'BTCBollingerBand20',
				'fill_color': 'rgba(0,176,246,0.2)'
			},
			'btc_bb_upperband': {
				'color': 'rgba(255,255,255,0)',
			},
			'btc_bb_middleband': {},
		},
		'subplots': {
			'bb_width': {
				'bb_width': {'color': 'blue'},
				'btc_bb_width': {'color': 'purple'},
			},
		}
	}

	def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

		if not self.dp:
			return dataframe

		# Get the informative data for BTC/stake_currency
		btc_informative = self.dp.get_pair_dataframe(pair=f"BTC/{self.config['stake_currency']}", timeframe=self.timeframe)

		# Bollinger Bands for Informative Pair (BTC/stake_currency)
		btc_bollinger = qtpylib.bollinger_bands(btc_informative['close'], window=20, stds=2)
		dataframe['btc_bb_lowerband'] = btc_bollinger['lower']
		dataframe['btc_bb_middleband'] = btc_bollinger['mid']
		dataframe['btc_bb_upperband'] = btc_bollinger['upper']
		dataframe['btc_bb_width'] = ((dataframe['btc_bb_upperband'] - dataframe['btc_bb_lowerband']) / dataframe['btc_bb_middleband'])

		# Bollinger Bands for the Current Pair
		bollinger = qtpylib.bollinger_bands(dataframe['close'], window=20, stds=2)
		dataframe['bb_lowerband'] = bollinger['lower']
		dataframe['bb_middleband'] = bollinger['mid']
		dataframe['bb_upperband'] = bollinger['upper']
		dataframe['bb_width'] = ((dataframe['bb_upperband'] - dataframe['bb_lowerband']) / dataframe['bb_middleband'])

		return dataframe

	def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
		dataframe.loc[
			(
				(dataframe['volume'] > 0)
				&
				(qtpylib.crossed_above(dataframe['close'], dataframe['bb_lowerband']))
			),
			'buy'] = 1

		return dataframe

	def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
		dataframe.loc[
			(
				(dataframe['volume'] > 0)
				&
				(dataframe['volume'] < 0) # Sell signal is disabled anyway
			),
			'sell'] = 1

		return dataframe
```

Config :
```
{
	"stake_currency": "USDT",
	...
	"exchange": {
		"pair_whitelist": [
			"BTC/USDT"
		],
		...
	}
	...
```

Commands used to run the strat and generate the plot :
```
freqtrade backtesting --strategy-list TestStrat --config user_data/config_binance.json --timeframe 1h --timerange 20210101-20210131 --export trades
freqtrade plot-dataframe --strategy TestStrat -p BTC/USDT --config user_data/config_binance.json --timeframe 1h --timerange 20210101-20210131
```

**Comment by xmatthias** [comment]
well the short version is - you're using it wrong.

`get_pair_dataframe` returns the full timerange for the informative pair in backtesting.
As you're not merging the 2 dataframes, but simply assigning the data of the informative pair to the "real" pair, you're assigning wrong indexes to each other.

assuming you've got data from 20200101- (but you only use 20210101- ), so your informative pair would be loaded with the full timerange still - so basically, your bollinger bands from the informative pair are from january 2020, while the bollingers from the "real" dataframe are from 2021 (pandas assigns per numeric index - and doesn't care about your date).

Now in live/dry-run, the same thing would happen (`get_pair_dataframe` returns the latest data).
Usually, it's not a problem (especially if the same timeframe is used) - but it CAN be a problem if a different timeframe is used, and there was a downtime that caused 1-2 candles to miss on one of the 2 dataframes (but not the other) , which will cause the missalignment again.

As shown in the documentation, you should use `merge_informative_pair` to combine the 2 dataframes, and not assume the 2 are identical length (the length can also be missmatched if one pair was listed later, for example).

**Comment by Th0masL** [comment]
I thought that `merge_informative_pair` was only needed when using different timeframes. Thanks for the explanation !

**Comment by xmatthias** [comment]
well you can technically merge it directly (`pd.merge()`) ... that's what happens in merge_informative_pair under the hood when the timeframes are identical.

**Comment by Th0masL** [comment]
Indeed. I'm asking that because I'm only interested by keeping/merging the "close" column of BTC, so I only need to keep the "date" and "close" column, and I'm trying to find a way to remove all the other columns.

**Comment by epigramx** [comment]
I've noticed this discussion and I get similar issues if I get_pair_dataframe() to receive a higher timeframe without merging it to the main timeframe. The problem is that merging it doesn't achieve what I want since the point was to use TA that starts before the main timeframe (before its maximum candles).
Is there a way to use the maximum length of the main timeframe and still do TA with a higher timeframe that starts before the main timeframe (or at least without resorting to odd hacks that are potentially also unstable)?

**Comment by xmatthias** [comment]
Remove all other columns before the merge step (`informative = informative.loc[:, ['date', 'close']]`) - nothing forces you to keep more than what you need.
