### ISSUE TITLE
Custom stake amount per crypto pair

### ISSUE THREAD

**Issue by smartorius** [freqtrade/freqtrade#4748]
## Describe your environment

  * Operating system: ___MacOS_
  * Python Version: __3.6___ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __latest stable__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

Hello,

Is there a way to limit stake amount for a risky pair to some percentage or dollar value of the available balance whilst say BTC pairs have the 'unlimited' stake?

Thank you

**Comment by xmatthias** [comment]
This is currently not possible, but there are efforts to enable this in the future (e.g. #3886 ).

I'm not sure if this PR will be merged or if another one will replace this (more likely due to many other changes).
