### ISSUE TITLE
Change to trade in forex.

### ISSUE THREAD

**Issue by HAGAI123** [freqtrade/freqtrade#4749]
Hello I have questions,  how I can change the bot to trade in forex.
Site like fxcm, or other forex broker. 

Thank you.

**Comment by xmatthias** [comment]
It's pretty simple - you can't, really.

Freqtrade uses ccxt to connect to exchanges, which is a cryptocurrency trading API framework, and freqtrade is a crypto trading bot.

It's possible that some exchanges support Forex pairs so it works "accidentally" (ftx has a few forex pairs ...) - but they usually don't move enough to make profits.
