### ISSUE TITLE
    self._datetime = dt_datetime( TypeError: integer argument expected, got float

### ISSUE THREAD

**Issue by evantoday** [freqtrade/freqtrade#4753]
## Describe your environment

  * Operating system: ubuntu
  * Python Version:  3,9 

### Steps to reproduce:

  1. freqtrade backtesting -s SomeStrat
  2. set timeframe on config.json 1h
  

    self._datetime = dt_datetime(
TypeError: integer argument expected, got float

**Comment by xmatthias** [comment]
Please provide
* your freqtrade version
* the full log (at few lines before the crash - and the full stacktrace).

**Comment by evantoday** [comment]
my bad
i just download 30 days data and it goes well
sorry :)

**Comment by piyush008gupta** [comment]
i have the same issue any solution

**Comment by nmenescardi** [comment]
I had a similar issue. Solved using the [Age ](https://www.freqtrade.io/en/stable/plugins/#agefilter)filter:
```
{"method": "AgeFilter", "min_days_listed": 30},
```
