### ISSUE TITLE
Using buy signal strength in a strategy

### ISSUE THREAD

**Issue by bshankar** [freqtrade/freqtrade#4756]
## Describe the enhancement

The buy column at the moment is either 0 (to avoid buying) or 1 (to buy). 
``` python
dataframe["buy"] = (some condition that returns 0 or 1)
```

But say we could return a real number which indicates buy signal strength. For example:
``` python
dataframe["buy"] = (100 - dataframe["rsi"])  # Just for illustrative purposes
```

Then, freqtrade can buy the pairs with the strongest buy signal instead of whatever pairs happen to be on the top in the whitelist.

**Comment by xmatthias** [comment]
This is not how freqtrade works - it checks the pairlist from top to bottom for buy signals.

It will also collide with proposals and ideas for #2183 - which might give the "Number" supplied a different meaning - but that discussion is not yet finished.
Strength of signal is however definitely not one that will be considered.

If you don't want one pair to buy - then best don't provide a buy signal, and do the logic of "which pair is strong enough" in the strategy.

**Comment by bshankar** [comment]
We can definitely say which pairs are good enough to buy at any give time through the strategy but there's no way to compare these buy signals among themselves. It is possible to miss a much better trading opportunity because the pair is "below another buy signal" in the pairlist. It is especially useful when you have a large pairlist. Many pairs can go into `buy` state at once.

Thanks for pointing to #2183. If I understand correctly, the number supplied will encode both side and size. Example:
``` python
dataframe['entry'] = -0.8  # Short with 80% stake
```
My proposal can still work with #2183 using an optional column. We can call it `entry_signal_strength`. If available it can sort buy signals and make the best trade.

**Comment by xmatthias** [comment]
I do currently not intend on changing the existing strategy dataframe interface (columns used) - apart from some callback functions, maybe.


You should simply increase the `max_open_trades` if you encounter many missed buys, which will give all trades similar possibilities.

You can also add it to #2183 so it's not missed, but i don't intend to spend time on that anytime soon - and i'm not certain we will consider this, as "pair sorting" in this format is not something that we aim to support.

**Comment by bshankar** [comment]
Okay thanks. 👍 I'll mention this in #2183.

Increasing `max_open_trades` to more than 2-5 makes a lot of strategies do much worse. So it makes sense to be able to sort the pairs this way.

**Comment by xmatthias** [comment]
Going to close this in favor of #2183 which discusses potential interfaces changes in depth.
