### ISSUE TITLE
convert to python code from pine script mha_close = security(heikinashi(tickerid), "D", hlc3) function

### ISSUE THREAD

**Issue by wahidanvary** [freqtrade/freqtrade#4765]
## Describe your environment

  * Operating system: WINDOWS10
  * Python Version: 3.9 64bit (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: latest (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

Hi, I want to develop my own strategy.  
how can i convert to python code from pine script mha_close = security(heikinashi(tickerid), "D", hlc3) function
Thanks for your patience and help...

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
I'm not very fluent in pinescript myself, so i won't be able to help you with this (i have to look up every word in this line...)

You might try to ask in the [discord community](https://discord.gg/MA9v74M) - maybe someone there knows pinescript and is able to help.

**Comment by xmatthias** [comment]
In general, we don't help with conversions from pinescript to python via issues unless it's a very specific question.

It's a different language - and in the end, it's a research topic.
Research the pine documentation on what each function does - and try to find something similar for python, either in the [strategy repository](https://github.com/freqtrade/freqtrade-strategies), or in the interwebs in general.

We (or the discord community) may be able to help with specific questions, but "do the work for me" questions will generally not be perceived well.
