### ISSUE TITLE
Bot only buys traded pairs while exchange outage and is stuck in fillup/blacklist loop

### ISSUE THREAD

**Issue by thraizz** [freqtrade/freqtrade#4770]
## Describe your environment

  * Operating system: docker image
  * Python Version: unknown, part of docker image
  * CCXT version: unknown, part of docker image
  * Freqtrade Version: 2021.3  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Since an outage on binance the bot seems stuck in a loop where it mentions missing data and then removes blacklisted pairs.

### Steps to reproduce:

  1. Have your exchange go down for maintenance
  2. ??
  3. Bot goes into a loop
  
### Observed Results:

I noticed that since Binance had an outage due to server maintenance yesterday, the bot only buys the pairs it was holding at this specific moment. While I used to have an average of 20+ trades a day, I had only 2 yesterday and not one this night.
I restarted the container, removed it and built a new one but nothing seems to help. The output of the logs is also weird:
It notifies me that it misses data fillup for a coin `before: 999 - after: 1029` and then removes blacklisted pairs. This occurs precisely every 5 seconds.

I cannot tell what causes this, as neither my configuration nor my bot version has changed, but somehow the bot is stuck.

### Relevant code exceptions or logs

```
[...]
freqtrade_binance    | 2021-04-21 06:00:50,007 - freqtrade.data.converter - INFO - Missing data fillup for XTZ/USDT: before: 999 - after: 1029
freqtrade_binance    | 2021-04-21 06:00:50,025 - freqtrade.data.converter - INFO - Missing data fillup for KMD/USDT: before: 999 - after: 1029
freqtrade_binance    | 2021-04-21 06:00:50,042 - freqtrade.data.converter - INFO - Missing data fillup for XEM/USDT: before: 999 - after: 1029
freqtrade_binance    | 2021-04-21 06:00:50,059 - freqtrade.data.converter - INFO - Missing data fillup for RLC/USDT: before: 999 - after: 1029
freqtrade_binance    | 2021-04-21 06:00:50,075 - freqtrade.data.converter - INFO - Missing data fillup for USDC/USDT: before: 999 - after: 1029
freqtrade_binance    | 2021-04-21 06:00:50,092 - freqtrade.data.converter - INFO - Missing data fillup for STPT/USDT: before: 999 - after: 1029
freqtrade_binance    | 2021-04-21 06:00:50,108 - freqtrade.data.converter - INFO - Missing data fillup for FIRO/USDT: before: 999 - after: 1029
freqtrade_binance    | 2021-04-21 06:00:50,125 - freqtrade.data.converter - INFO - Missing data fillup for UMA/USDT: before: 999 - after: 1029
freqtrade_binance    | 2021-04-21 06:00:50,140 - freqtrade.data.converter - INFO - Missing data fillup for LTO/USDT: before: 999 - after: 1029
freqtrade_binance    | 2021-04-21 06:00:50,156 - freqtrade.data.converter - INFO - Missing data fillup for SUSHI/USDT: before: 999 - after: 1029
freqtrade_binance    | 2021-04-21 06:00:50,172 - freqtrade.data.converter - INFO - Missing data fillup for RIF/USDT: before: 999 - after: 1029
freqtrade_binance    | 2021-04-21 06:00:50,188 - freqtrade.data.converter - INFO - Missing data fillup for ARDR/USDT: before: 999 - after: 1029
freqtrade_binance    | 2021-04-21 06:00:50,204 - freqtrade.data.converter - INFO - Missing data fillup for XLM/USDT: before: 999 - after: 1029
freqtrade_binance    | 2021-04-21 06:00:50,221 - freqtrade.data.converter - INFO - Missing data fillup for KEY/USDT: before: 999 - after: 1029
freqtrade_binance    | 2021-04-21 06:00:50,237 - freqtrade.data.converter - INFO - Missing data fillup for ANKR/USDT: before: 999 - after: 1029
freqtrade_binance    | 2021-04-21 06:00:50,254 - freqtrade.data.converter - INFO - Missing data fillup for EPS/USDT: before: 999 - after: 1029
freqtrade_binance    | 2021-04-21 06:00:54,251 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.3', state='RUNNING'
freqtrade_binance    | 2021-04-21 06:00:54,267 - freqtrade.plugins.pairlistmanager - WARNING - Pair DOGE/USDT in your blacklist. Removing it from whitelist...
freqtrade_binance    | 2021-04-21 06:00:54,268 - freqtrade.plugins.pairlistmanager - WARNING - Pair BTCUP/USDT in your blacklist. Removing it from whitelist...
freqtrade_binance    | 2021-04-21 06:00:54,268 - freqtrade.plugins.pairlistmanager - WARNING - Pair BTCDOWN/USDT in your blacklist. Removing it from whitelist...
[...]
```

**Comment by thraizz** [comment]
Rebooting the system somehow magically helped.
It still logs that it misses fillup data and removes blacklisted pairs every 5 seconds, but at least the bot buys again.

As there's no way to reproduce this I'll close this. Thanks for the awesome bot!

**Comment by xmatthias** [comment]
the "missing data fillup" is normal after exchange downtimes, and simply shows that data is missing. The output of this will change in the next version to be slightly less verbose.

Depending on the config (volumepairlist or staticpairlist) it's most likely that you had an empty pairlist (this happens if the pairlist reloads right in the downtime). It should usually resolve itself within a few hours (you should be able to check this with `/whitelist`) - however it's possible that it'll take up to 6 hours + the volumepairlist refresh time.

**Comment by thraizz** [comment]
Seems like this was the case, somehow it took unusually long to refresh the volumepairlist. I cannot think of any way to test an exchange become unreachable though, so I cant tell if this was system or code related.
