### ISSUE TITLE
strategy for 2 pairs

### ISSUE THREAD

**Issue by EnigmaticCrypt** [freqtrade/freqtrade#4771]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Is it possible two write a strategy based on two pair. Like if one pair behaves certain way, take buy and sell decisions on another. I think for live trading/dry run it can be written by using some workarounds. But backtesting and hyperopt seems to be challenge.

**Comment by tutecode** [comment]
I think you have to look in [https://www.freqtrade.io/en/latest/strategy-customization/] there you can.

You can code for example is BTC down sell all the cryptos. You have to use informative_pairs

**Comment by xmatthias** [comment]
adding a [working link](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-informative_pairs) to the above informative_pairs information. 

Informative pairs are definitely the way to go.

**Comment by EnigmaticCrypt** [comment]
Thanks a lot for such a prompt response. Looks like the informative_pairs is the way.
