### ISSUE TITLE
FTX resetting

### ISSUE THREAD

**Issue by tutecode** [freqtrade/freqtrade#4772]
Im running my bot on FTX Exchange and always is resetting. It started to do that when it buys his first cryptos. There are no logs.

**Comment by xmatthias** [comment]
Please fill out the issue template, otherwise i'll close this issue without further comment.

Also - please update and improve the description - as it's absolutely unclear what you mean with "resetting".

**Comment by tutecode** [comment]
My Bot in Telegram, is running correctly but few minutes later the bot status: died. And then its starts over again. I dont know what happend because there are no logs.

I have stop the bot because it's an infinite loop of turning on and off.

**Comment by xmatthias** [comment]
there will be logs. If they disappear, try to run it with `--log-file user_data/logs/logfile.log`.

I will however close this issue, as you did not provide the requested information about your versions.
