### ISSUE TITLE
How can I retreve the price that my order was filld on?

### ISSUE THREAD

**Issue by sapitamas96** [freqtrade/freqtrade#4773]
I want to use it for the sell signal

**Comment by xmatthias** [comment]
For now, you will need to query the trade manually [as shown here](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-trades) and use `trade.open_rate`.

This will however NOT work in backtesting (not at all).

While this is subject to change soon #4750 - it's currently not possible in any other way.

For the future - please do not delete the issue template. It's there for a reason (to simplify helping and reduce back and forth). Not having it may cause unnecessary back and forth in case some of the information is required.

**Comment by sapitamas96** [comment]
Thanks for the quick reply. I will try it out.
