### ISSUE TITLE
get recent data on hitbtc

### ISSUE THREAD

**Issue by saeedrss** [freqtrade/freqtrade#4778]
## Describe your environment

  * Operating system: ____ win 10 

  * Python Version: _____ Python 3.7.8

  * CCXT version: _____ ccxt 1.46.38

  * Freqtrade Version: ____ freqtrade develop

 
## Your question

hello  i use  hitbtc  exchange and i got :
 WARNING - Outdated history for pair BTC/USDT. Last tick is 3811501 minutes old

hitbtc by default send candle from beginning (not most recently)
in ccxt.hitbtc  fetch_ohlcv/fetchOHLCV   get candle from beginning and  fetchOhlcvc/fetchOHLCVC  get the recent

i can't set config file 

oder exchange  work fine

![Screenshot 2021-04-22 012639](https://user-images.githubusercontent.com/6265785/115623862-004fd180-a30f-11eb-8593-c1c456068641.png)

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
closed by #4788
