### ISSUE TITLE
Edge positioning fatal exception with empty whitelist / dynamic pairlist

### ISSUE THREAD

**Issue by leonardvdj** [freqtrade/freqtrade#4779]
## Describe your environment

  * Operating system: Ubuntu 20.04.1 LTS
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.3 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
Note: Not sure how to get python/ccxt version with docker, also tried freqtrade version 2021.2, and develop branch
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Whenever I run freqtrade trade with edge positioning enabled, an empty whitelist, and DynamicPairList, I get a list index out of range fatal exception.

### Steps to reproduce:

  1. Enable Edge 
  2. Have empty whitelist
  3. Have dynamic pairlist set up
  
### Observed Results:

  * What happened? Fatal exception
  * What did you expect to happen? Bot to start up properly

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

```
2021-04-22 00:23:50,285 - freqtrade.commands.trade_commands - ERROR - list index out of range
2021-04-22 00:23:50,285 - freqtrade.commands.trade_commands - ERROR - Fatal exception!       
Traceback (most recent call last):                                                           
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading          
    worker = Worker(args)                                                                    
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__                                
    self._init(False)                                                                        
  File "/freqtrade/freqtrade/worker.py", line 52, in _init                                   
    self.freqtrade = FreqtradeBot(self._config)                                              
  File "/freqtrade/freqtrade/freqtradebot.py", line 91, in __init__                          
    self.edge = Edge(self.config, self.exchange, self.strategy) if \                         
  File "/freqtrade/freqtrade/edge/edge_positioning.py", line 84, in __init__                 
    self.fee = self.exchange.get_fee(symbol=expand_pairlist(                                 
IndexError: list index out of range                                                          
```

Something I noted was, if I had just a single pair in my whitelist, despite not having StaticPairList in my pairlists array, it seemed to stop giving an error.

**Comment by leonardvdj** [comment]
Also tagging on a question, since I feel it doesn't warrant a new issue: Since edge filters out any pairs with less than min_trade_number trades, does this mean I have to first run the strategy without edge for a while?

**Comment by xmatthias** [comment]
no, actual prior trades do not matter for edge, it's ONLY looking at trades it simulates itself - so it'll work right away on fresh bots, can be activated later (however the strategy must be compatible with it - which means sell-signal must be the dominant selling method (not traling stop or similar)).
