### ISSUE TITLE
Integration with automated bot services

### ISSUE THREAD

**Issue by elja** [freqtrade/freqtrade#4783]
Hello there, 

Tried to find an answer on this but was unable to. Since we can't implement strategies that use pyramiding it's not possible to create DCA-like bots at this point. I like the idea of using freqtrade to do a TA and generate buy signals and post them to 3rd party software (via webhooks or whatever). My question is: is it really a good idea to use freqtrade for this case? I wrote a strategy and now planning to add some API module to integrate with 3rd party software, however, I'm still not sure if this will work well, because as I understand it won't generate multiple buy signals because it will place and track orders until they will be sold by another signal or stop-loss.

**Comment by xmatthias** [comment]
That's correct, freqtrade will open trades and track these trades until they are sold.

As you seem to have the knowledge, feel free to contribute and try and implement #1519 - which would enable position staking / DCA like trades.
It's probably the faster, simpler method than adding an API module, and developing another software to take care of the orders for you.
It will however not be a "5 line change" ... but some work that will need to go into to make this work - it would however help many people in the freqtrade community - not just your particular use case.

**Comment by elja** [comment]
thank you for the reply @xmatthias. I'm not trying to develop 3rd party software - there are a lot of solutions already like 3commas. writing API module is a quite simple task as it should just send HTTP request once we got a signal. Adding pyramiding/stacking is a complex thing for a non python developer like me as well as for a user without deep knowledge in trading. However, I think we can use the same concept as the Pine script does with their strategies.

**Comment by xmatthias** [comment]
Freqtrade supports [webhooks](https://www.freqtrade.io/en/latest/webhook-config/) for notifications about buys / sells that occured.

The generic freqtrade rules will still apply (only one open trade per pair) - so i don't think it'll give you what you need.

I am however not interested in adding a "signal only" mode.
