### ISSUE TITLE
Trade is not executed after buy/sell signal in dry-run mode

### ISSUE THREAD

**Issue by yongshen2020** [freqtrade/freqtrade#4784]
## Describe your environment

  * Operating system: ubuntu 18.04_
  * Python Version: python 3.8.0
  * CCXT version: ccxt==1.48.22
  * Freqtrade Version: freqtrade develop-75612496
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
I did a search in the issue list, to my best knowledge, no same issue reported before.
[issue 746 ](https://github.com/freqtrade/freqtrade/issues/746) might be relavent, but not exact the same

1. the trade is not executed after showing buy/sale signal. I have only one pair to trade, so it should always do buy action when there is no open trade after receiving buy signal, and sell when there is an open trade after sell signal. Please look at yellow circle, where the trade actions are missing after buy/sell signals in dry-run, but it works in backtest.
2. dry-run acts somewhat differently than backtest, see red circle, there is a buy which does not happen in backtest. could this be that process_only_new_candles flag is default to false, so the changing last candle triggered the unexpected behavior?
![issue](https://user-images.githubusercontent.com/12562295/115736637-b78a2e00-a38b-11eb-9778-a87804ab3401.png)

Appreciate your help!

**Comment by xmatthias** [comment]
with the information provided, it's quite difficult to determine what happens (no logs from the timeperiod, no strategy) ... 

Locks / protections can be in place, which are not shown, but will prevent buys from happening in both backtesting and dry-run - which can cause triangles to show up, but no buy taking place.

The "red" buy (top chart) looks like either a forcebuy (you bought it manually) - as there is no signal before this.

If that's not what happened, then i suspect your signals are not consistent, which means that they change based on something not available to backtesting / not calculated on historic data. this can be using orderbook prices, or using some indicators that calculate differently depending if there is future candles available or not (e.g. ta-lib's MACD does this if the 3rd parameter is 1, which creates a "randomized" buy signal in dry/live runs).

**Comment by yongshen2020** [comment]
@xmatthias thanks a lot for the prompt response to my issue, you are amazing :)
 Here is I try to provide more information to your questions.

> with the information provided, it's quite difficult to determine what happens (no logs from the timeperiod, no strategy) ...

My strategy is mainly based on MACD crossover and I will try to provide logs below.

> Locks / protections can be in place, which are not shown, but will prevent buys from happening in both backtesting and dry-run - which can cause triangles to show up, but no buy taking place.

To my best knowledge, I did not enable or config any locks and protections. As you can see, yellow circle trades happened in backtesting, as you said, if there are locks/protections, they shall not happen in backtesting.

> The "red" buy (top chart) looks like either a forcebuy (you bought it manually) - as there is no signal before this.

this is not the case, 'red' buy happened during my middle night time (about 01:15), no chance for me to buy it manually, I was sleeping :)
here is the log arround that time, it looks like the buy signal is there before the trade, however it is just the buy signal NOT showing up in the dry-run chart. if that is the case, it is definitely a bug, at least with the chart ploting.
```
2021-04-22 01:13:09,211 - freqtrade.worker - INFO - Bot heartbeat. PID=26926, version='develop-75612496', state='RUNNING'
2021-04-22 01:14:09,275 - freqtrade.worker - INFO - Bot heartbeat. PID=26926, version='develop-75612496', state='RUNNING'
2021-04-22 01:15:04,716 - freqtrade.data.converter - INFO - Missing data fillup for BTC/USDT: before: 999 - after: 1009 - 1.0 %
2021-04-22 01:15:04,769 - freqtrade.wallets - INFO - Wallets synced.
2021-04-22 01:15:04,772 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade for BTC/USDT with stake_amount: 963.6968626299999 ...
2021-04-22 01:15:04,772 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2021-04-22 01:15:05,074 - freqtrade.wallets - INFO - Wallets synced.
2021-04-22 01:15:05,074 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 4, 'type': buy, 'exchange': 'Binance', 'pair': 'BTC/USDT', 'limit': 54506.07, 'order_type': 'limit', 'stake_amount': 963.6968626299999, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'amount': 0.01768, 'open_date': datetime.datetime(2021, 4, 22, 1, 15, 5, 61545), 'current_rate': 54506.07}
2021-04-22 01:15:09,338 - freqtrade.worker - INFO - Bot heartbeat. PID=26926, version='develop-75612496', state='RUNNING'
2021-04-22 01:15:09,397 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=4, pair=BTC/USDT, amount=0.01768000, open_rate=54506.07000000, open_since=2021-04-22 01:15:05)
2021-04-22 01:15:09,399 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=4, pair=BTC/USDT, amount=0.01768000, open_rate=54506.07000000, open_since=2021-04-22 01:15:05) [buy]: 0.96366732 USDT - rate: 0.001
2021-04-22 01:15:09,399 - freqtrade.persistence.models - INFO - Updating trade (id=4) ...
2021-04-22 01:15:09,399 - freqtrade.persistence.models - INFO - LIMIT_BUY has been fulfilled for Trade(id=4, pair=BTC/USDT, amount=0.01768000, open_rate=54506.07000000, open_since=2021-04-22 01:15:05).
2021-04-22 01:16:09,398 - freqtrade.worker - INFO - Bot heartbeat. PID=26926, version='develop-75612496', state='RUNNING'
2021-04-22 01:17:09,458 - freqtrade.worker - INFO - Bot heartbeat. PID=26926, version='develop-75612496', state='RUNNING'
```

> If that's not what happened, then i suspect your signals are not consistent, which means that they change based on something not available to backtesting / not calculated on historic data. this can be using orderbook prices, or using some indicators that calculate differently depending if there is future candles available or not (e.g. ta-lib's MACD does this if the 3rd parameter is 1, which creates a "randomized" buy signal in dry/live runs).

orderbook prices? here is what in my config.json, I suppose it is not enabled. am I right?
```
"bid_strategy": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
```
indicators that calculate differently? that could be the case, but not with ta-lib, I am using qtpylib like below, do you have experience with it? does it also acts like ta-lib?
```
qtpylib.crossed_above(dataframe['macd'], dataframe['macdsignal'])
```
BTW, I did not configure `process_only_new_candles`, which should be in its default value 'false'. It should be configured to 'true', right? if I want deterministic behaviour in dry-run just like backtesting.

Cheers

**Comment by xmatthias** [comment]
The `qtpylib.crossed_above()` is just a function to detect the cross ... there's ... very little code involved in that, and fewer yet that can be wrong.

How do you calculate the MACD columns in the dataframe? (that's the more important point).

**Comment by yongshen2020** [comment]
> The `qtpylib.crossed_above()` is just a function to detect the cross ... there's ... very little code involved in that, and fewer yet that can be wrong.
> 
> How do you calculate the MACD columns in the dataframe? (that's the more important point).

I get your point. the macd code was actually from freqtrade repo. Yes, it is TA lib.
```
macd = ta.MACD(dataframe)
dataframe['macd'] = macd['macd']
dataframe['macdsignal'] = macd['macdsignal']
dataframe['macdhist'] = macd['macdhist']
```
this is the ta.MACD() defination:
```
macd, macdsignal, macdhist = MACD(close, fastperiod=12, slowperiod=26, signalperiod=9)
```
I only specified the first argument, the rest should be in its default value.
what do you mean in your last reply by saying "(e.g. ta-lib's MACD does this if the 3rd parameter is 1, which creates a "randomized" buy signal in dry/live runs)." ?
can flag "process_only_new_candles" being true stop MACD being randomized?

**Comment by xmatthias** [comment]
it's a bug in MACD we discovered - if signalperiod is 1 - it's an edge-case that's not considered / not correct for the "latest" candle.
As you're using MACD and experience "buys without buy signal" - this was one possibility i had to exclude.

As you're not specifying this, it shouldn't be a problem.

**Comment by yongshen2020** [comment]
right now, I am testing with 2 bots, one is with process_only_new_candles=false, one is with process_only_new_candles=true. Hopefully, it can proof that my issue was caused by the last candle random problem. And I will update later my findings.

**Comment by xmatthias** [comment]
as said, as you don't use that parameter, i don't think it was caused by that problem.

From a freqtrade point of view, i can only say that based on the logs, the bot acted on a buy signal.
Why that buy-signal disappears afterwards is ... difficult to say for me, and is tied to the strategy.

**Comment by yongshen2020** [comment]
OK, I will keep observing that buy-signal missing issue later on.
But so far, we still don't have an rough explanation of 2 places where yellow circles marked. buy/sell signals are there as expected, but bot did not follow the signals to trade. As I explained, I did not have locks or protections configured, what could be the cause? shall I switch to 'stable' branch to do dry-run?

**Comment by xmatthias** [comment]
Well the reason can be the same - maybe that buy-signal was not there during that candle, but only appeared afterwards somehow (the reverse case from the Red circle) - which would suggest a "lookahead" bias of your strategy.

The most likely cause however is that you're using a different strategy for the graph than what you're running live (maybe you changed strategy in the meantime, or you have 2 strategies with the same name in your strategy folder (but different files?) - so sometimes it's using one strategy, other times the other.

**Comment by yongshen2020** [comment]
@xmatthias  thanks for all the feedback. then lets close this issue. if I have more real findings, I will come back.
Cheers
Yong

**Comment by miguent** [comment]
Hi @yongshen2020 ,

did you find out what the root cause was of the inconsistencies between the buy / sell signals in the graph and actually performing the buys / sells?
I am facing some similar issues.

Thanks,
Michael

**Comment by krystian-blaszczyk** [comment]
I join the question, I have a similar problem

**Comment by stash86** [comment]
Please open a new issue if you have a problem
