### ISSUE TITLE
Binance Request Time Out

### ISSUE THREAD

**Issue by Bturan19** [freqtrade/freqtrade#4786]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: 3.8.3 (`python -V`)
  * CCXT version: 1.43.89 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.3 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I'm trying my strategy with dry-run. It is a very straight forward ML based approach. When I last tried a fre days ago it was all fine. But today when I check the logs I see these lines:

2021-04-22 22:33:27,817 - freqtrade.wallets - INFO - Wallets synced.
2021-04-22 22:33:28,121 - freqtrade.freqtradebot - INFO - Pair IOTA/USDT is still locked until 2021-04-22 20:00:00.
2021-04-22 22:33:28,527 - freqtrade.worker - INFO - Bot heartbeat. PID=17714, version='2021.3', state='RUNNING'
2021-04-22 22:34:50,069 - freqtrade.worker - INFO - Bot heartbeat. PID=17714, version='2021.3', state='RUNNING'
2021-04-22 22:36:09,692 - freqtrade.worker - INFO - Bot heartbeat. PID=17714, version='2021.3', state='RUNNING'
2021-04-22 22:36:46,407 - freqtrade.exchange.common - WARNING - get_tickers() returned exception: "Could not load tickers due to RequestTimeout. Message: binance GET https://api.binance.com/api/v3/ticker/24hr"
2021-04-22 22:36:46,407 - freqtrade.exchange.common - WARNING - retrying get_tickers() still for 4 times
2021-04-22 22:36:54,782 - freqtrade.exchange.common - WARNING - get_tickers() returned exception: "Could not load tickers due to RequestTimeout. Message: binance GET https://api.binance.com/api/v3/ticker/24hr"
2021-04-22 22:36:54,784 - freqtrade.exchange.common - WARNING - retrying get_tickers() still for 4 times
2021-04-22 22:37:31,392 - freqtrade.worker - INFO - Bot heartbeat. PID=17714, version='2021.3', state='RUNNING'

Do you think that the request time out causes from Binance, temporarily? Or is it something with my version?

When I check the UI, last data point is from 18.00. But it should be 22.00.

Thanks a lot in advance.

**Comment by xmatthias** [comment]
RequestTimeout is a network-level issue (usually happening during high load times at the exchange).
it simply means that the endpoint (even shown above) did not answer in time.

Freqtrade has a builtin retry-mechanism and will retry this call 4 times.
This is usually not something you can control (unless the network on your side was slow) - and as long as the retry works, the impact is minimal (it'll be slightly slower).

**Comment by thraizz** [comment]
I have these errors for Sells and Buys as well. The bot will create the order, the exchange will execute it and then the bot starts throwing the `ccxt.base.errors.OrderNotFound` error.

I suspect this to be due to some change in the binance api and that its rather related to the ccxt package but I will open another issue for this none the less.

EDIT:
#4462 explains this in detail. It seems like binance api is at fault for this, I dont know whether or not to change exchange because of this :thinking:

**Comment by xmatthias** [comment]
while it's a (temporary) problem - freqtrade should recover from this as it's a known problem, which happens in times of high volume on binance.

unfortunately, most exchange api's have some "quirks" - like - kraken has insane ratelimits - and does not provide historic ohlcv ...

**Comment by thraizz** [comment]
> unfortunately, most exchange api's have some "quirks" - like - kraken has insane ratelimits - and does not provide historic ohlcv ...
They do, but only via direct download and not via API: https://support.kraken.com/hc/en-us/articles/360047124832-Downloadable-historical-OHLCVT-Open-High-Low-Close-Volume-Trades-data :laughing: 

I cant see why these exchanges cant offer a subscription based pro api for bots. There seems to be some progression regarding the ratelimits when verifying your account but it still seems really low: https://support.kraken.com/hc/en-us/articles/360045239571-Trading-rate-limits

Anyhow this isnt the discord, i'll stop spamming the git-notifications for now :smile_cat:

**Comment by xmatthias** [comment]
While you can get lower rate-limits for kraken, these ONLY apply to private endpoints (creating orders, fetching orders) - not to public endpoints (ohlcv, trades) - which do not accept / respect any authentication.

**Comment by xmatthias** [comment]
Interrestingly, this seems to be a huge problem with the binance api at the moment. Their [dev forum](https://dev.binance.vision/) is full of complaints about the api returning old data (sometimes up to 3 months old ...).

**Comment by xmatthias** [comment]
Based on their dev forum, this issue should now be fixed (or at least improved) since the last update / downtime over the weekend.

Unfortunately, it's not something we can "really" do much for as it's a binance API problem - which we need to somehow work around (usually by retrying).

I'll close this for now - feel free to comment below or reopen should it reappear again within a few days (otherwise it's most likelly a new issue).
