### ISSUE TITLE
Config - Strategy priority issue

### ISSUE THREAD

**Issue by snussik** [freqtrade/freqtrade#4794]
As the config file located in root directory and strategy in nested (by default scheme) and we can have multiple strategies but one prime config -> so it'd more clear if local setting override globals (in config file). 
Current implementation is more confusing, imho.
As the example you can look at VSCode config system where user settings override global.

**Comment by xmatthias** [comment]
The config prevelance is 
cli arguments -> config -> strategy -> defaults if applicable (with the prior overwriting conflicting settings in the latter).

The intend behind this is to allow you to run / experiment with different strategies (also with shared ones) without being at the mercy of what the strategy author determined to be the best settings, but keeping your configuration settings.

You can easily give control over "overridable" settings to the strategy by removing them from the configuration - but the configuration is "tied to you"  as it contains the secrets / api keys, while a strategy can be shared / taken from a shared strategy repository.

As such, cli arguments are the "user wish" at this moment in time, while configs are the extended (persisted) user wish.
Strategies on the other hand are not tied to you but are often shared - and are therefore the least prevelant.

Therefore, the "local vs. global" point depends on the standpoint.
For me, config is the "local" settings (you call it root directory - but it's really the directory you are currently) - while strategy is something that can change (and will most likely change over time).

**Comment by snussik** [comment]
I see your point. But it opposites widely used conventions (local rewrites global: nginx, apache, php configs & python venvs) and may be confusing.

**Comment by xmatthias** [comment]
Your assumption is that a config is global, while a strategy is local - which i see as wrong.

My / freqtrade's assumption is that the config is local, and the strategy may be global (shared across many people).
With that - freqtrade is following common conventions just fine by having the config (local) overwrite the strategy (global / shared).
