### ISSUE TITLE
Working with Coinbase Pro?

### ISSUE THREAD

**Issue by Aphris-Karu** [freqtrade/freqtrade#4796]
Im running the docker version.
  
I know Coinbase pro is not listed as supported. Though I can get it to connect to the exchange and it appears to almost work.

When I try to backfill for back testing it fails with

"granularity too small for the requested time range. Count of aggregations requested exceeds 300"

Doing some simple testing with http requests to the coinbase pro API it appears to be the amount of time requested. 

For example, freqtrade request looks like this

https://api.pro.coinbase.com/products/BTC-USD/candles?granularity=60&start=2021-03-25T00%3A00%3A00.000Z&end=2021-03-25T08%3A19%3A00.000Z

but if you change it to 5 hour instead of the above 8 hours and 19 min, it works.

Example:
https://api.pro.coinbase.com/products/BTC-USD/candles?granularity=60&start=2021-03-25T00%3A00%3A00.000Z&end=2021-03-25T05%3A00%3A00.000Z

So is there a way in the config to set this timeframe?

**Comment by xmatthias** [comment]
it's (probably) not about timeframe, but about the amount of trades.

maybe look at `bybit.py` on how to subclass an exchange and set this setting.

Knowing users who tried coinbase pro:
their fees are insanely high (compared to other exchanges) - and i don't think placing orders works correctly...

**Comment by xmatthias** [comment]
That's now been fixed in 42453333bef8f600c29007e69bd5be508953a9a8

Make sure to also update dependencies, as it depends on the ccxt version to be correct.

Note: if you did download data for this exchange before - you'll need to delete the data, as the prior datadownload did not work correctly and caused "holes" in the data..
