### ISSUE TITLE
ERROR - No pair in whitelist. Only one pair available 123/456.

### ISSUE THREAD

**Issue by JohanVlugt** [freqtrade/freqtrade#4799]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: 3.8.5(`python -V`)
  * CCXT version: 1.43.89 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.3`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Yesterday I was backtesting and dryrunning on 2 seperate systems. This morning I wanted to backtest something and it gave me an error on both systems: freqtrade - ERROR - No pair in whitelist. 
I got this error both on my dry run and my backtesting, yesterday this didn't happen.

When I run "freqtrade show list-markets" I got only one pair, which is kind of weird.
Binance has 1 active market:
+--------+----------+--------+---------+----------+-----------+
|     Id |   Symbol |   Base |   Quote |   Active |   Is pair |
|--------+----------+--------+---------+----------+-----------|
| 123456 |  123/456 |    123 |     456 |     True |      True |
+--------+----------+--------+---------+----------+-----------+

### Steps to reproduce:

  1. Run like usual
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  It gave me an error on both systems
  * What did you expect to happen?
  To run normally

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
Binance is currently having a scheduled [downtime](https://www.binance.com/en/support/announcement/849160fe70214641baa6385619595aa1).

This means, neither market information nor fee information is available - so backtesting / hyperopt will not work when using binance at the moment.

It will start working again after binance is back.

**Comment by JohanVlugt** [comment]
Thank you, I wasn't aware that it would impact backtesting.
