### ISSUE TITLE
Is there a way to limit sells to a percentage of your position?

### ISSUE THREAD

**Issue by Aphris-Karu** [freqtrade/freqtrade#4800]
Ive heard this called laddering out of a position but that may not be what it is called. 

Im looking for a way to tell it to only sell a percentage of the total position held with each sell signal. 
For example:

If you have $1000 to work with and stake $500 at a time, on a time frame of 5m with a ladder of 10%. (BTC/USD)

First buy signal you buy $500 of BTC at $50,000 per BTC So you hold a position of 0.020 BTC.
At each sell order trigger you sell 10% of your position (0.002 btc) 

I doing this in the past I have found that when the market is going up, you turn a much better profit overall and it better handles the dips in the market. 

Is there a way to do this?

**Comment by xmatthias** [comment]
Neither position staking, nor position laddering (in or out) is currently supported.

Please subscribe to #1519 for updates on this topic - but don't expect soon / immediate progress on this.
