### ISSUE TITLE
Message for xmatthias

### ISSUE THREAD

**Issue by djacky** [freqtrade/freqtrade#4811]
Hello xmatthias, can you please contact me via email at: ***
I have something I want to discuss with you.
Thanks.

P.S: Sorry if this is not the appropriate place to make this request.

**Comment by xmatthias** [comment]
In general, i'd say it's better to drop me a message in discord than to share your email publicly ...

but it's not my email ... so it's not up to me to determine ;)

**Comment by djacky** [comment]
How can I reach you in the discord?
Are messages in the discord private?

**Comment by xmatthias** [comment]
You can send Direct messages in Discord - which are 1:1 messages (only visible to the 2 involved parties).

I'll also drop you a mail later as i think you'll prefer that.
