### ISSUE TITLE
Plotting profit from an old/achieved trading (sqlite)

### ISSUE THREAD

**Issue by kumkee** [freqtrade/freqtrade#4814]
## Describe your environment

  * Operating system: Ubuntu 20.04.2 LTS
  * Python Version: 3.8.5
  * CCXT version: 1.40.74
  * Freqtrade Version: 2021.3
  
## Your question
_Related documentation entry: [https://www.freqtrade.io/en/stable/plotting/](https://www.freqtrade.io/en/stable/plotting/)_
I am trying to plot the profits for several past trading experiments with their sqlite trades database.  I am using the plot-profit subcommand, but keep getting the following error.

`2021-04-27 10:37:48,227 - freqtrade - ERROR - No trades found, cannot generate Profit-plot without trades from either Backtest result or database.`

My command is
```
freqtrade plot-profit --db-url sqlite:////home/liang/workdir/archived_trades/tradesv3.LZ_7_5.sqlite --trade-source DB
```
I can open the sqlite database with sqlite browser and see the trades in the file.

**Comment by xmatthias** [comment]
plotting a profit graph needs multiple things

* a config that contains the pairs from the database (as you're not explicitly using a config file, it's using `user_data/config.json` or `config.json`.
* downloaded data for the timerange of the pairs

if either of the 2 is not fullfilled, plotting will not work.
The most likely cause is the pairs - maybe your database is for BTC pairs, but you since switched to USDT pairs (or whatever other change might be possible).

**Comment by kumkee** [comment]
> * downloaded data for the timerange of the pairs

Thank you, @xmatthias. If I am plotting the close trades, why would I need to have price data from the markets? All open and close rates as well as individual trade profits are within the sqlite database.

**Comment by xmatthias** [comment]
plot-profit is also plotting market change, and the whole plot is written with the basis of having the data available.

While it would not be an absolute necessity - that's the way it is implemented at the moment, and i have no plans to change this for now.

**Comment by kumkee** [comment]
> plot-profit is also plotting market change, and the whole plot is written with the basis of having the data available.
> 
> While it would not be an absolute necessity - that's the way it is implemented at the moment, and i have no plans to change this for now.

Thank you once again for the quick respond.
I've implemented my own plotting for archived trading, but that is only for closed trades.  
By the way, do you think plotting functions is a good entry point for new contributors?

**Comment by xmatthias** [comment]
sure - but it'll also depend what you did specifically ... if it's inversing the logic for plot-profit - sure

if it's introducing a new plot-command and different type of plot - i'd have to see what it provides and if it's worth the time (i don't see plotting being developed much further, but see the future of the "graphical" things more with freqUI, therefore i would not invest too much time into plotting other than fixing some bugs / inconsistencies.).
