### ISSUE TITLE
Cumulative profit of the Dashboard tab of the UI cuts off at an earlier date

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#4815]
This appears to go away if I use develop code from a couple of days ago so I suspect it's related to the profit graph cumulative profit change from yesterday (or something else that changed VERY recently).

I can't post personal info but it appears to happen if you have a dbase that is at least weeks-old and it doesn't show the latest dates at all (the daily graph of the same tab seems fine and current).

## Describe your environment

  * Operating system: linux dedicated server
  * Python Version: 3.8.5
  * CCXT version: 1.48.76
  * Freqtrade Version: develop current (**GOES AWAY IF REVERTED TO A COUPLE OF DAYS AGO**)

**Comment by xmatthias** [comment]
You should be able to use `freqtrade install-ui` to pull the latest version of freqUI (0.0.6), which will fix this.

The cause for it was that the freqUI release was missing - i pushed the code to master, but if it's not in a release, freqtrade will not automatically use it.

**Comment by epigramx** [comment]
Right: good to know. I did suspect at some point that it might be related to the frontend, but the default was still at 0.0.5 at the time so I didn't try the latest.

**Comment by xmatthias** [comment]
The only way to use a non-released version is through building it yourself / using yarn serve...

**Comment by epigramx** [comment]
Yes I know, e.g. I was using 'yarn build' for other issues. I just didn't expect recent ui code was a problem since 0.0.5 was the latest release at the time and the issue was reverting with reverting this repo.
