### ISSUE TITLE
Buy and Loss signals not placed correctly with a Trend Following Strategy

### ISSUE THREAD

**Issue by Zast996** [freqtrade/freqtrade#4816]
## Environment

  * Operating system: Ubuntu Linux 20.04
  * Python Version: 3.8.5
  * CCXT version: 1.43.89
  * Freqtrade Version: 2021.3
  
## Question

I have implemented a really simple Trend Following strategy.
Basically:
  * when the FastSimpleMovingAverage (FastSMA) intersect the SlowSimpleMovingAverage (SlowSMA) from below, there is a Buy signal --> FastSMA > SlowSMA = Buy
  * when the FastSimpleMovingAverage (FastSMA) intersect the SlowSimpleMovingAverage (SlowSMA) from above, there is a Sell signal --> FastSMA < SlowSMA = Sell

Here, there are the relative lines of code for completeness.

```python
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe["FastSMA"] = ta.SMA(dataframe, timeperiod=16)
        dataframe["SlowSMA"] = ta.SMA(dataframe, timeperiod=33)

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                    (dataframe["FastSMA"] > dataframe["SlowSMA"])
            ),

            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                    (dataframe["FastSMA"] < dataframe["SlowSMA"])
            ),

            'sell'] = 1

        return dataframe
```

However, analyzing the plot, it seems that the buy/sell signal aren't  executed with the correct timing.
![trad](https://user-images.githubusercontent.com/62074263/116219951-7cea1200-a74c-11eb-8334-96fa8e64babf.png)

In particular, in the image, the vertical black lines highlight the moment in which FastSMA intersect from above  SlowSMA, thus, if there is no open trade, the bot should place a buy order just after the intersection (I have max_open_trades = 1).
Instead, we see that after the first vertical line there is no cyan buy signal.
Only after the second black line, we see a cyan buy signal, but not immediately.
Same thing for the second cyan buy signal.

I suppose that this happens due to a config parameter, but studying the documentation, I can't figure out which one of them is the cause.
Here there is my config file:

```json
{
    "max_open_trades": 1,
    "stake_currency": "BTC",
    "stake_amount": 0.01,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "5m",
    "dry_run": true,
    "dry_run_wallet": 0.1,
    "cancel_open_orders_on_exit": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "price_side": "ask",
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "bid",
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
        "pair_whitelist": [
            "ALGO/BTC",
            "ATOM/BTC",
            "BAT/BTC",
            "BCH/BTC",
            "BRD/BTC",
            "EOS/BTC",
            "ETH/BTC",
            "IOTA/BTC",
            "LINK/BTC",
            "LTC/BTC",
            "NEO/BTC",
            "NXS/BTC",
            "XMR/BTC",
            "XRP/BTC",
            "XTZ/BTC"
        ],
        "pair_blacklist": [
            "BNB/BTC",
            "BNB/BUSD",
            "BNB/ETH",
            "BNB/EUR",
            "BNB/NGN",
            "BNB/PAX",
            "BNB/RUB",
            "BNB/TRY",
            "BNB/TUSD",
            "BNB/USDC",
            "BNB/USDS",
            "BNB/USDT",
            "BNB/<STAKE>"
        ]
    },
    "pairlists": [
        {"method": "StaticPairList"}
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -100,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": false,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "somethingrandom",
        "CORS_origins": [],
        "username": "",
        "password": ""
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```

Many thanks in advance and for this awesome project too.

**Comment by xmatthias** [comment]
It's quite simple - your trading slots (`max_open_trades`) are exhausted.

While you look at one pair - freqtrade will look at all pairs in your pairlist (which are far more than your max_open_trades) - so it's not guaranteed that every buy-signal is acted upon.

As your signals are "sticking" for the whole duration of the trend (which is dangerous in itself, but a different topic) - the buy happens at a later point - when a trade-slot became available, because some other pair sold.

**Comment by Zast996** [comment]
I got it.
My mistake was that I though that max_open_trades was relative only to a trade pair, thus with max_open_trades = 1 and 3 pairs, I'd have had 3 open trades, one for each pair.
I've tried to backtest only 1 pair and the signal placing is correct.

Thank you again.
