### ISSUE TITLE
Trailing stop loss adjusted to current price distance from purchase price

### ISSUE THREAD

**Issue by zavitax** [freqtrade/freqtrade#4817]
## Describe the enhancement

I would like to be able to adjust trailing stop loss price based on the current profit % (calculated using current price & purchase price).

I.e. if I purchased BTC for X USD, and the current profit % is 0.01%, I want to use a smaller trailing stop loss, but, if the market is bullish and current profit % is >1%, I'd like the trailing stop loss price to increase to allow for larger price amplitude.
Being able to define steps based on profit % & profit USD would be great (similar to minimal_roi).

**Comment by xmatthias** [comment]
Please make sure to read the documentation before opening issues.

This can easily be covered by using a [custom stoploss](https://www.freqtrade.io/en/stable/strategy-advanced/#custom-stoploss).
Freqtrade provides the means, implementing the functionality to your liking is then up to you.

You should be careful with too tight stoplosses - < 1% will probably not work properly in most markets, as they move more than 1% in a second ...
