### ISSUE TITLE
Buy/Sell signals according to Moving Average slope.

### ISSUE THREAD

**Issue by Sabritocaster** [freqtrade/freqtrade#4821]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.7.9
  * Freqtrade Version: 2021.3
  
## Your question

Hello everyone,
I want to create Buy/Sell signals according to 7 days moving average slope.
For example, when the slope become positive (while it was going down, it starts to go up), I want to buy and when it starts to go down I want to sell.  
I have tried
(qtpylib.crossed_above(dataframe['ema7'], dataframe['ema7'].shift(1)))
(dataframe['ema7'] > dataframe['ema7'].shift(1))
However, I'm not sure that these are what I'm searching for. Because when I use plotting, I see that freqtrade doesn't actually use slope of moving averages.

**Comment by xmatthias** [comment]
You're not using slope, but you're comparing the current value with the previous value - and your signal will be either when they cross (crossed_above) - or when one is bigger than the prior one.

While this is kindof a positive slope to some extend, it can also be an almost flat line - where they will cross consistently, so you'll need to calculate the slope explicitly.

**Comment by Sabritocaster** [comment]
Thanks for your answer. I think I need to substract previous candle price from current price in order to find if the slope is positive or negative.
