### ISSUE TITLE
Custom Buy Price

### ISSUE THREAD

**Issue by Arminova** [freqtrade/freqtrade#4822]
## Describe your environment

  * Operating system: __Linux 64 bit__
  * Python Version: _3.6.8____ (`python -V`)
  * Docker-Compose

## 

Hi

I wrote many strategies and tested many Freqtrade existing strategies and all of them create limit order on the high price (Candlewick). I read documents and changed values in the order book but it didn't change the entry price.

I have 2 questions:

1. is there any way to force the bot to create a limit order on the candle body, not the candlewick? (buy signal candle body)

2. in my strategy, if some conditions meet, I can predict the entry price,  1 to 3 candle before the buy signal candle. (I call it to get ready to buy function) I want to put it as a buy signal with the custom future price? is there any way to give buy signal a custom price to open it as a limit buy order?

Thanks

**Comment by xmatthias** [comment]
freqtrade makes a difference on how pricing is treated based on the mode.

for backtesting:
Open Prices are always the candle's open price. For closing, the price will differ a bit [and the logic is documented here](https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting).

For live trading:
the price will be based on the orderbook - so either on the ask or on the bid side (the default uses ticker, but it's values are also just the values from the orderbook).

If this price is in the wick or in the body is not relevant to freqtrade.
If you place the order too far away from the current price, it's VERY unlikely that your order will be filled.
If you place the other on the other side (ask for buy orders, bid for sell orders) - the order is very likely to be filled immediately.

It is currently not possible to define your own price (#848, #909).
