### ISSUE TITLE
huge cancel order on ftx

### ISSUE THREAD

**Issue by lulu-angry** [freqtrade/freqtrade#4823]
## Describe your environment

  * Operating system: Ubuntu 20.10 x64
  * Python Version: 3.8.6 (`python -V`)
  * CCXT version: Last Version (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-63c28b65 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

Hello Freqtrade team,
I search in issue how to avoid "cancel order" on ftx but i can't find anything what can help me, so i came here for help.

I created a strategy basedon HFT (High frequency Trading) in dry-run it work with efficiency !! so i decide to run it in real mode but in the work of this strategy is totaly different i encounter limitless cancel order (115 on 114 buy limit order) and when one are executed my trade are always lose.

I try to modify my *.json config file in bid_strategy and ask_strategy region but anything working for the orderbook it the same,
i tried to insert 'market' in my order type but i encounter another error : Market buy orders require bid_strategy.price_side = "ask".

So my question is : Ccan you help me to fix that or find the best way to have most of my order executed.

Thanks in advance for your help.

**Comment by xmatthias** [comment]
i will simply point you to the [pricing documentation](https://www.freqtrade.io/en/stable/configuration/#prices-used-for-orders).

It does explain how freqtrade determines the price to place an order with.

There's a seperate section for [market orders](https://www.freqtrade.io/en/stable/configuration/#market-order-pricing).

I would however strongly suggest that you do some research on how orderbooks / market filling of the different order-types on the exchange work in general to make an educated decision.

**Comment by lulu-angry** [comment]
ok i go take a look!

**Comment by lulu-angry** [comment]
If i use bid_strategy.order_book_top should i modify my stoploss?

**Comment by xmatthias** [comment]
i would not recommend to use order_book_top with any other number than 1, unless you intentionally want to place your order away from price and wait for the order to come to you.

As you're having problems with unfilled orders, this is absolutely the wrong setting to touch.

**Comment by lulu-angry** [comment]
i tried many option like :
            "bid_strategy": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": true,
        "order_book_top": 1,
        "order_book_max": 3,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": true,
        "order_book_min": 1,
        "order_book_max": 3,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },

i tried to inverse bid ask side, but nothing changed.
am I the only one having so much problem with my order?

I tried to modify my order types by market but when i execute freqtrade i encounter an error

**Comment by xmatthias** [comment]
The error you encounter when using market orders is covered and explained by the [market orders](https://www.freqtrade.io/en/stable/configuration/#market-order-pricing) section i also linked above.

Reversing price is as simple as using the same config - but sticking to limit orders (this way you'll not be impacted by slippage this much - but success will depend on the size of your orders).

You'll also need to be realistic - on a market that has 10k$ of volume per day, you can't expect a 1k$ order to be filled without problems - that's simply not how markets work.

**Comment by lulu-angry** [comment]
i finally understand where is the problem, my strategy are based on leverage token and these leverage have a very very low volume and liquidity and have high ask or bid for me who try to expose 200$ per stake it's impossible for my order tobe filled

thanks a lot xmatthias !

a last question do you think these market will change a day?

**Comment by xmatthias** [comment]
That's something that's impossible to answer. It might change - it might be better on other exchanges, or on selected pairs ... 

for FTX, the first 30 or 40 leveraged pairs seem to have a decent volume (100k$ in the last 24 hours) ... 
obviously you'll need to stay away from the bottom of the list - where tokens have 73$ (or 10$) volume in the last 24 hours.
