### ISSUE TITLE
Enable edge positioning in backtesting

### ISSUE THREAD

**Issue by cornytrace** [freqtrade/freqtrade#4826]
When running `` freqtrade edge `` it only considers its own buy and sell signals and not the ones of the strategy according to the documentation. The results of backtesting with edge enabled and disabled are currently identical, indicating edge positioning is not run in backtesting. Currently there seems to be no way to test the effect of edge positioning on different strategies and configuration without dry-running or testing live, both taking a long time. Enabling edge positioning in backtesting would make edge positioning much more feasible to explore and use.

**Comment by xmatthias** [comment]
It's quite simple - Edge requires a compatible strategy.
You should not use it with ROI or trailing stoploss - and when doing so, the results of `freqtrade edge` will reflect what will be done during trading.


If your strategy is not using a strong sell signal (80-90% of the sells are through sell-signal or stoploss) - then please consider your strategy as incompatbile with edge.

Using edge with a strategy that's using other sell-signals is very risky and clearly not recommended, as it would take decisions (pairs, stoploss, position size) based on strategy results you're not really running / having.

Including edge in backtesting is not planned, nor would it make much sense.

**Comment by cornytrace** [comment]
Thank you for your explanation. Why would it not make sense to include edge in backtesting? Do you mean that if the strategy is incompatible it almost always makes it worse, and when compatible almost always makes it better? Or does edge depend on something that makes backtesting results unrealistic?

**Comment by xmatthias** [comment]
if a strategy is incompatible (has no sell signal)  - it will simply return an empty pairlist in all cases.

the functioning of edge modifies the pairlist over time.
To properly simulate this, we'd need to run edge every few hours during backtesting (which will mean edge will itself run 1000ds of times during the course of backtesting).

While this is not a problem in dry-runs (you usually start the bot and leave it run for a few days) - backtesting you "wait" actively for a result - so every second / minute you have to wait more is wasted time.

---

Edge in itself (edge-cli) is a (reduced) form of backtesting - if you don't get any results there, then your strategy will for sure not work with edge anyway.
