### ISSUE TITLE
Can I change the parameters of the keltner channels indicator?

### ISSUE THREAD

**Issue by hisokacono** [freqtrade/freqtrade#4833]
* Operating system: UBUNTU
  * Python Version: python 3
  * CCXT version: pip
  * Freqtrade Version: freqtrade develop
  

Can I change the parameters of the keltner channels indicator? like the ATR lenght for example?

I was searching all over the place if i can do that but couldnt find it.

**Comment by xmatthias** [comment]
keltner (from qtpylib) has the following signature:
`def keltner_channel(bars, window=14, atrs=2)`

so you can call it with `qtpylib.keltner_channel(dataframe, window=14, atrs=2)`.

There's no other parameters possible.
