### ISSUE TITLE
Bittrex BTXCRD not updating

### ISSUE THREAD

**Issue by shimuldn** [freqtrade/freqtrade#4834]
Could not get rate for pair BTXCRD and not using to pay fee.
Is this normal?

```
2021-04-29 21:20:52 - freqtrade.worker - INFO - Bot heartbeat. PID=x, version='develop-5bc90887', state='RUNNING'
2021-04-29 21:21:01 - freqtrade.rpc.rpc - WARNING -  Could not get rate for pair BTXCRD.
```

**Comment by xmatthias** [comment]
I have no idea what BTXCRD is ... (never heared of it).

For the bot to get a rate - it must be listed in the markets section - if i look at bittrex, i can't - so it's not something that's listed on the exchange / can be traded.

That log is however ... way too reduced to say what the bot was trying to do  (why it needed this rate) - to determine anything more.

**Comment by shimuldn** [comment]
BTXCRD is Bittrex Credits.
Bittrex Credits is a customer rewards program enabling users to earn commission-free trades by trading on Bittrex Global. 

https://bittrexglobal.zendesk.com/hc/en-us/articles/360009625020-Learn-More-About-Bittrex-Credits

**Comment by xmatthias** [comment]
As it's not a tradable market - freqtrade is unable to get a price for it - so the message above is correct.

As your reduced log makes it unclear where / when this is happening - i have no further idea - as i don't think the bot is buying this coin (it's not a market ...).
