### ISSUE TITLE
How to check how many pairs were excluded by the filters

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#4835]
## Describe your environment

Operating system: Debian 10
Python Version: Python 3.7.3
CCXT version: ccxt==1.43.89
Freqtrade Version: freqtrade develop-8d01767a
  
## Your question

I am using VolumePairList, AgeFilter, PrecisionFilter, PriceFilter, SpreadFilter and RangeStabilityFilter. Is there a way to see a list of pairs that each of these filters excluded? Or maybe just a number? For example:

```
AgeFilter: excluded 10 pairs
PrecisionFilter: excluded 15 pairs
PriceFilter: excluded 20 pairs
SpreadFilter: excluded 15 pairs
RangeStabilityFilter: excluded 12 pairs
```

There are some indications in the log file of these filters working, but no easy way to see actual numbers of pairs excluded.

```
AgeFilter - INFO - Validated 208 pairs.
Removed COCOS/USDT from whitelist, because spread 0.572% > 0.5%
Removed GXS/USDT from whitelist, because spread 0.954% > 0.5%
Removed WNXM/USDT from whitelist, because spread 0.524% > 0.5%
Removed FIS/USDT from whitelist, because spread 0.508% > 0.5%
```

**Comment by xmatthias** [comment]
the logs will contain each pair that was removed.
freqtrade does not keep a log / count of which pairs were removed - and i'm also not quite sure it's relevant ... 

things like spreadFilter will change very rapidly, so it's possible that it'll change every few minutes ...

**Comment by aristosv** [comment]
I don't know if I am doing something wrong in my configuration but the only **filter** information I get in the log file is the one above. There is no mention of any other filters working.

I'm just trying to get an idea of how much work each filter does, tweak it, and see how it affects the whitelist.
