### ISSUE TITLE
Is there a way to log once that a dataframe column of booleans is not met as a buy signal?

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#4842]
For example I have `dataframe["not_this"]` while the actual buy signal is `dataframe["buy_signal"] = dataframe["I_want_this"] & dataframe["not_this"]`. Is there an easy way to log once that dataframe["not_this"] is False when it's time for `populate_buy_trend()`?

**Comment by xmatthias** [comment]
i'm not sure what you mean with "log once" ... you can for sure use `logger.info()` to log it - but it'll log this whenever that method is called.

**Comment by epigramx** [comment]
Hm yeah: I shouldn't have said 'once' since it's more confusing that not; I just meant to not have it spammed every 5 seconds if it's setup to only run once per candle; I guess I need a way to do `if (dataframe['not_this']  == True): logger.info()` inside `populate_buy_trend()` that works both in backtesting and live.

If I do in `populate_buy_trend()`:

```
        if (dataframe['not_this'] == True):
            logger.info(f"not_this detected for {metadata['pair']}")
```

I get a warning that it's not a bool() and I don't want to use .iat[-1] since I want it in backtesting too.

Do you have an example that works the expected way?

edit 1: A custom dict will be needed in backtesting I guess. Closing this, but let me know if there's a better way.

edit 2: Oh nevermind, there's no current_time in `populate_buy_trend()` in order for backtesting to be able to use a custom dict. Let me know if there's a way to do that in backtesting without hacking `populate_buy_trend()` itself or close the issue if it's dead end I guess.

edit 3: I mentioned that in discord: but for completion here, I guess a custom_buy() would be required for this for backtesting (unless I miss something) so that it provides a `current_time` for a custom dict (or directly for the dataframe), and since `custom_sell()` was recently added I guess `custom_buy()` could be a reasonable new feature.

**Comment by epigramx** [comment]
A custom dict will be needed in backtesting I guess. Closing this, but let me know if there's a better way.

**Comment by epigramx** [comment]
Oh nevermind, there's no current_time in `populate_buy_trend()` backtesting to be able to use a custom dict. Let me know if there's a way to do that in backtesting without hacking `populate_buy_trend() itself` or close the issue if it's dead end I guess.

**Comment by xmatthias** [comment]
for backtesting, populate_buy will only be called once (per pair) - so you can just log it i guess... (but it won't give you what you expect).

I'd suggest to read through the [Bot execution logic](https://www.freqtrade.io/en/latest/bot-basics/#bot-execution-logic) to understand how each method is executed in the different modes.

what you can use i guess is `confirm_trade_entry` - which will only fire when there is a buy happening...

**Comment by epigramx** [comment]
Oh `confirm_trade_entry()` is a good idea since it does run in backtesting too. I guess a custom_buy() is an idea for other issues.
But: how can I check dataframe['not_this'] in `confirm_trade_entry()`?

edit: I wonder if Trade.open_date is already set in it so that a custom dict can be used.

**Comment by xmatthias** [comment]
no - the trade object is not been created at that point yet (it's actually been developed for regular trading, and only later added to backtesting).

**Comment by epigramx** [comment]
So it became clear that only live/dryrun can do what I want with current features. 
There is a discussion in discord about a possible custom_buy() that could help 
PS Since that's another matter (a potential new feature) and I could possibly be fine personally with live-only functionality I will close this.
