### ISSUE TITLE
Missing data fill up for ...

### ISSUE THREAD

**Issue by juanjoayala01** [freqtrade/freqtrade#4846]
* Operating system: Windows 10
  * Python Version: Python 3.7.6
  * Freqtrade Version: 2021.4

Hello, i have a problem that i searched and did find it, but the problem is that i didnt understand it the answer. (Freqtrade - binance mode)

`freqtrade  | 2021-05-01 20:50:22,934 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
freqtrade  | 2021-05-01 20:50:22,935 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
freqtrade  | 2021-05-01 20:50:23,745 - freqtrade.worker - INFO - Changing state to: RUNNING
freqtrade  | 2021-05-01 20:50:23,745 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': 'Dry run is enabled. All trades are simulated.'}
freqtrade  | 2021-05-01 20:50:24,109 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `binance`\n*Stake per trade:* `unlimited BTC`\n*Minimum ROI:* `{'0': 0.165, '65': 0.075, '238': 0.026, '497': 0}`\n*Stoploss:* `-0.317`\n*Timeframe:* `15m`\n*Strategy:* `SampleOptimizedStrategy`"}
freqtrade  | 2021-05-01 20:50:24,477 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for BTC pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
freqtrade  | 2021-05-01 20:50:28,775 - freqtrade.data.converter - INFO - Missing data fillup for LTC/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 20:50:28,798 - freqtrade.data.converter - INFO - Missing data fillup for ETH/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 20:50:28,821 - freqtrade.data.converter - INFO - Missing data fillup for ALGO/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 20:50:28,853 - freqtrade.data.converter - INFO - Missing data fillup for BCH/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 20:50:28,877 - freqtrade.data.converter - INFO - Missing data fillup for XMR/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 20:50:28,903 - freqtrade.data.converter - INFO - Missing data fillup for XTZ/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 20:50:28,935 - freqtrade.data.converter - INFO - Missing data fillup for NEO/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 20:50:28,958 - freqtrade.data.converter - INFO - Missing data fillup for EOS/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 20:50:28,982 - freqtrade.data.converter - INFO - Missing data fillup for IOTA/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 20:50:29,003 - freqtrade.data.converter - INFO - Missing data fillup for LINK/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 20:50:29,025 - freqtrade.data.converter - INFO - Missing data fillup for NXS/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 20:50:29,050 - freqtrade.data.converter - INFO - Missing data fillup for BRD/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 20:50:29,072 - freqtrade.data.converter - INFO - Missing data fillup for ATOM/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 20:50:29,092 - freqtrade.data.converter - INFO - Missing data fillup for XRP/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 20:50:29,115 - freqtrade.data.converter - INFO - Missing data fillup for BAT/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 20:50:29,126 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
freqtrade  | 2021-05-01 20:50:29,879 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 20:51:07,819 - freqtrade.rpc.telegram - INFO - Executing handler: _status for chat_id: 855527873
freqtrade  | 2021-05-01 20:51:29,927 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 20:52:29,980 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 20:53:30,032 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 20:54:30,084 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 20:55:30,136 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 20:56:30,188 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 20:57:30,236 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 20:58:30,288 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 20:59:30,340 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 21:00:09,241 - freqtrade.data.converter - INFO - Missing data fillup for LTC/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:09,262 - freqtrade.data.converter - INFO - Missing data fillup for ETH/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:09,284 - freqtrade.data.converter - INFO - Missing data fillup for ALGO/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:09,307 - freqtrade.data.converter - INFO - Missing data fillup for BCH/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:09,327 - freqtrade.data.converter - INFO - Missing data fillup for XMR/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:09,347 - freqtrade.data.converter - INFO - Missing data fillup for XTZ/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:09,371 - freqtrade.data.converter - INFO - Missing data fillup for NEO/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:09,394 - freqtrade.data.converter - INFO - Missing data fillup for EOS/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:09,415 - freqtrade.data.converter - INFO - Missing data fillup for IOTA/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:09,438 - freqtrade.data.converter - INFO - Missing data fillup for LINK/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:09,461 - freqtrade.data.converter - INFO - Missing data fillup for NXS/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:09,481 - freqtrade.data.converter - INFO - Missing data fillup for BRD/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:09,500 - freqtrade.data.converter - INFO - Missing data fillup for ATOM/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:09,522 - freqtrade.data.converter - INFO - Missing data fillup for XRP/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:09,545 - freqtrade.data.converter - INFO - Missing data fillup for BAT/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:12,197 - freqtrade.data.converter - INFO - Missing data fillup for ALGO/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:12,220 - freqtrade.data.converter - INFO - Missing data fillup for XMR/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:12,244 - freqtrade.data.converter - INFO - Missing data fillup for IOTA/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:12,264 - freqtrade.data.converter - INFO - Missing data fillup for NXS/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:12,287 - freqtrade.data.converter - INFO - Missing data fillup for BRD/BTC: before: 999 - after: 1017 - 1.8%
freqtrade  | 2021-05-01 21:00:30,384 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 21:01:30,436 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 21:02:30,481 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 21:03:30,533 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 21:04:30,585 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 21:05:30,634 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 21:06:30,687 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
freqtrade  | 2021-05-01 21:07:30,736 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.4', state='RUNNING'
`

The typical error "Missing data fillup for ...". The thing is that according to the answer of the previously opened issues the data is missing some candles or values at some point or points, but i dont recall to read the solution. How can i fill the missing data? they only said that this happends often, specially with low volume trades. Anyway, maybe i misread the solution. Do i just have to wait? do i have to run a command to refill the data? Is it because im at weekend and (i think) its the downtime of binance?

Anyway, if someone can help me i would really appreciate it and if my question is non sense then im sorry.

**Comment by juanjoayala01** [comment]
![image](https://user-images.githubusercontent.com/42329001/116795260-95c63080-aa88-11eb-8ed9-f0b89771deb1.png)

*added image of cmd promt

**Comment by xmatthias** [comment]
Please read the [documentation](https://www.freqtrade.io/en/stable/faq/#im-getting-missing-data-fillup-messages-in-the-log) before asking questions covered by the docs.
