### ISSUE TITLE
Three questions regarding the ta-lib patch in build_helpers/

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#4864]
![image](https://user-images.githubusercontent.com/2960257/116849389-579b4f00-abf7-11eb-841c-4e7d05f99a5f.png)

I hadn't noticed that patch existed so I applied it and reinstalled the patched ta-lib to /usr/local and reinstalled the python ta-lib after doing that: however that raised the questions:

1. Is it normal that pytest on test_talib.py had both never failed before the patch and didn't fail after the patch?
2. In another system (where I didn't run pytests) at the stage of the python package reinstallation it immediately used a ready wheel for the python package after I reinstalled a patched ta-lib in /usr/local; is that enough or does it need a way to discard the wheel somehow?
3. I noticed that the test (test_talib.py) uses 8 decimal places but the patch deals with 18; then again I don't know if any exchange uses more than 8; is that normal?

## Describe your environment

  * Operating system: linux server in wsl2 (also dedicated but I didn't pytest there)
  * Python Version: 3.8.5
  * CCXT version: 1.48.76
  * Freqtrade Version: develop current and recently

**Comment by xmatthias** [comment]
1) in my understanding, the test should fail. However, ta-lib does some ... very opinionated (different) compilations based on the platform, so it's possible that this test only fails on certain platforms (like on 32bit systems, but not on 64bit). I've not written this test - so i'm not sure.
2) i honestly don't know - i'm no expert in ta-lib installation - and i'm always happy if it works as that means i'll not have to deal with it again :laughing: 
3) it's not about the decimals that you're using / the exchange is using, but about the decimals that the (intermediate?) result produces.
It's in the end similar to #4382 - if you navigate to the linked pandas issues - it's not that STD (Standard deviation) would become that low - but VAR (variance) (the intermediate result while calculating std) becomes too low to handle and is zeroed out.

**Comment by epigramx** [comment]
The heart of it might be what you mention about some systems having by default high precision. It's partly unclear but google easily reveals that "by default" python has 64bit precision on floating operations even on 32 bit systems (!) which might mean the patch is unneeded in most cases. Perhaps some of the slowest systems that people might run this on might have OSes that have python hacks that deviate from that default and drop that precision which might have prompted the patch.

**Comment by xmatthias** [comment]
what we're patching is not the python part - but the underlying C library.

`pip install ta-lib` only installs a python wrapper - the calculation (and potential calculation error) happens in the C backend - and there precision is a whole different topic i guess.

**Comment by epigramx** [comment]
I thought of that after I typed that: yeah it might be unrelated since the lib is C. But there's a chance it's still related since python precision might be affecting the input of the library.
One wouldn't know for sure without testing it closely and I guess few would bother to do it since it appears to not give problems patched or unpatched.

**Comment by xmatthias** [comment]
> it appears to not give problems patched or unpatched.

this will depend on your "usecase".
if you're using stable-coin pairs (*/USDT | ...) - then this is most likely irrelevant.
with */BTC pairs however this can become relevant, as these are often priced with 0.0000001 or similar ... which is where this precision becomes relevant (as the values / std will be "disappearing" - from a data perspective.

it's very similar to the pandas problem linked above - where it's the same case (no problem for USDT pairs, but potentially problematic for BTC pairs - depending on the pair).
