### ISSUE TITLE
Backtest discrepancy 5m vs 1h candles

### ISSUE THREAD

**Issue by tomwilms** [freqtrade/freqtrade#4866]
More of a question than an issue.

I am backtesting a very simple strategy, that uses simple moving average for buy decisions (see below). It uses the 1 hour candle, with 14 and 28 periods. Sell is done with trailing stoploss, and the strategy is profitable.

Now here's the thing: if I change timeframe to 5m, and increase the SMA periods 12x, to 168 and 366 respectively, this should give the same result right (?). It does not however, the backtest now predicts significant loss.

What am I missing?

`timeframe = '1h'

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # SMA - Simple Moving Average
        dataframe['fastMA'] = ta.SMA(dataframe, timeperiod=14)
        dataframe['slowMA'] = ta.SMA(dataframe, timeperiod=28)
        # dataframe.to_csv('user_data/dataframe.csv')
        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['fastMA'] > dataframe['slowMA'])
            ),
            'buy'] = 1

        return dataframe

**Comment by xmatthias** [comment]
your assumption is wrong. 
SMA 14 on 1h candles is not identical to SMA 14 * 12 on 5m candles.

All methods are rolling ... so you'll have different datapoints that will be used, causing a (slighlty) different result.

you can see this pretty easily side by side:

```
dataframe_long = resample_to_interval(dataframe, 60)  
dataframe_long['sma'] = ta.SMA(dataframe_long, 5)

dataframe['sma'] = ta.SMA(dataframe, 5 * 12)
dataframe = resampled_merge(dataframe, dataframe_long, fill_na=True)
dataframe[['date', 'open', 'high', 'low', 'close', 'sma', 'resample_60_sma']].tail(10)
```


![2021-05-03-194844_597x310_scrot](https://user-images.githubusercontent.com/5024695/116912490-94436680-ac48-11eb-8634-32ab42565687.png)

**Comment by tomwilms** [comment]
Thanks for your reply.

Think in the end it had to do with using a tight trailing stop, and the way this is evaluated while backtesting. On 5 min candles price will go back and forth continuously, triggering trailing stoploss earlier then when backtesting with 1h candles.

**Comment by xmatthias** [comment]
this is also true - but also your signals can be slightly different - and on 5m candles you can have 12x as many signals (they can fluctuate between 1 hourly candle) - so i don't think comparing the 2 and expecting a similar outcome will work.
