### ISSUE TITLE
Update most recent candle in real time

### ISSUE THREAD

**Issue by zavitax** [freqtrade/freqtrade#4867]
## Describe your environment

  * Operating system: Docker
  * Freqtrade Version: 2021.3
  
## Your question

I'm trying to build a strategy which takes into account changes in the most recent, not-yet-complete candle.

Having `populate_indicators` print out a message every time it's called, I fail to understand when freqtrade actually refreshes klines from the exchange: it *seems* that this happens once per a few minutes, but I am really not sure and can't find a configuration setting which would alter this behavior.

The strategy I'm currently trying is using `timeframe = '15m'`.

I would appreciate any information on this, and, whether there is an option to enable updating klines via a websocket (on Binance for example) in real time.

**Comment by xmatthias** [comment]
Freqtrade will only provide the strategy with closed candles.

There is no setting to change this behaviour - and using the unfinished candle will lead to repainting (a common problem in tradingview strategies) - and will make the signals unreliable (if you look at a chart after the candle, you'll not know why it triggered a buy).

**Comment by zavitax** [comment]
> Freqtrade will only provide the strategy with closed candles.
> 
> There is no setting to change this behaviour:

Seems that this is partially documented here:
https://www.freqtrade.io/en/stable/exchanges/#getting-latest-price-incomplete-candles
and here:
https://www.freqtrade.io/en/stable/developer/#incomplete-candles
However, it is not clear how often will the strategy will be pushed fresh data.

> using the unfinished candle will lead to repainting (a common problem in tradingview strategies) - and will make the signals unreliable (if you look at a chart after the candle, you'll not know why it triggered a buy).

Assuming some users are willing to live with this, and the project would accept such a change, where would one look to implement flexible sleep timeframes between partial candle updates and (hopefully) real-time updates via a websocket?

**Comment by xmatthias** [comment]
It's documented including the point that it will be removed from the data that will be provided to the strategy - so the strategy can rely on only receiving completed candles.
There is no documentation that this could be changed via a configuration - and there is none.

There's multiple levels where you'd need to change this - which is not suited for an initial contribution unless you are rather familiar with the codebase. 
The fact that you'll need to ask "where would one find this part" tells me that this is not a contribution you should be attempting to make.
You should however look for issues labeled "good first issue" to get started. 
Once you're familiar with the codebase (and the contribution process) - you can maybe return to this at a later point.


Also, freqtrade  does not use/support websockets (nor does ccxt free)- so you'd have to poll the exchange frequently, which will result in bans by the exchange (or would at least slow down operations and you'll risk being banned by the exchange when you try to place an order) - so it's not a good idea anyway at this point.
