### ISSUE TITLE
custom_stoploss function with indicator crash

### ISSUE THREAD

**Issue by rylos** [freqtrade/freqtrade#4870]
## Describe your environment

  * Operating system: __ubuntu focal__
  * Python Version: _3.8____ (`python -V`)
  * CCXT version: __1.49.30___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _develop___ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Using custom_stoploss function with indicator in a very similar way described in the docs, all is good in both hyperopting and backtesting but using it in live & dry modes produces an error.

### Steps to reproduce:

Using FTX exchange.
Of course `use_custom_stoploss = True
    trailing_stop = False`
Using 1h dataframe and calculating this 2h merge indicator:
  ```
dataframe_long = resample_to_interval(dataframe, 120)
        dataframe_long['ATR'] = pta.atr(dataframe_long["high"], dataframe_long["low"], dataframe_long["close"], length=14)
        dataframe = resampled_merge(dataframe, dataframe_long, fill_na=True)  
```
pta is pandas_ta lib.

and the custom_stoploss function is:
  ```
def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, dataframe: DataFrame,
                        **kwargs) -> float:
        # Default return value
        result = 1
        if trade:
            current_time = timeframe_to_prev_date(self.timeframe, current_time)
            current_row = dataframe.loc[dataframe['date'] == current_time].squeeze()
            if 'resample_120_ATR' in current_row:
                new_stoploss = (current_rate - (current_row['resample_120_ATR']*2.13)) / current_rate
                result = new_stoploss - 1
        return result
  ```

  
### Observed Results:

Backtesting works flawless and also hyperopting some other indicators. Live & dry mode raise this error:
  ```
2021-05-04 06:31:10,555 - numexpr.utils - INFO - NumExpr defaulting to 1 threads.
2021-05-04 06:31:12,058 - freqtrade.commands.trade_commands - ERROR - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2021-05-04 06:31:12,058 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/opt/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/opt/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/opt/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/opt/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/opt/freqtrade/freqtrade/freqtradebot.py", line 185, in process
    self.exit_positions(trades)
  File "/opt/freqtrade/freqtrade/freqtradebot.py", line 711, in exit_positions
    if trade.open_order_id is None and trade.is_open and self.handle_trade(trade):
  File "/opt/freqtrade/freqtrade/freqtradebot.py", line 823, in handle_trade
    if self._check_and_execute_sell(analyzed_df, trade, sell_rate, buy, sell):
  File "/opt/freqtrade/freqtrade/freqtradebot.py", line 959, in _check_and_execute_sell
    should_sell = self.strategy.should_sell(
  File "/opt/freqtrade/freqtrade/strategy/interface.py", line 559, in should_sell
    stoplossflag = self.stop_loss_reached(dataframe=dataframe, current_rate=current_rate,
  File "/opt/freqtrade/freqtrade/strategy/interface.py", line 644, in stop_loss_reached
    if stop_loss_value:
  File "/opt/freqtrade/.env/lib/python3.8/site-packages/pandas/core/generic.py", line 1442, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
  ```

Any clue?

**Comment by xmatthias** [comment]
The error suggests that you're "somehow" returning a series, not a single value.

Are you sure that the above function is what's actually called .. i don't really see a hint as to why this might be happening - at least not for now.

**Comment by rylos** [comment]
Yes I'm sure, it's just a copy/paste of my actual code. If you look I create the series dataframe['resample_120_ATR'] and it's ok like any other series in the populate indicator, if I print the dataframe I can see the correct values of ATR on 120minutes resampled.
The problem is in the custom_stoploss return but I used the method (it's pratically the same of yours apart the moltiplication added) that you put on the documentation example. 
Backtesting is working fine. Only in live/dry with an open trade (so custom_stoploss is called) the error is raised.
I've also tried deleting the database, start a dry run, forcebuy an asset, and immediately later the error arrives.
Can I try to print the result variable in dry run, will add here the output.

**Comment by rylos** [comment]
Actually the problem seems to be
`current_row = dataframe.loc[dataframe['date'] == current_time].squeeze()`
printing current_row I get an empty row.
I forget to say I've this setting also `"process_only_new_candles": true` 

More info (edit). 
Placing this `current_row = dataframe.loc[dataframe['date'] == current_time].squeeze()
            print(current_row)`

I get:

`
2021-05-04 13:32:09,841 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
Empty DataFrame
Columns: [date, open, high, low, close, volume, sma25, rsi2, rsi7, rsi14, wvf, rangeHigh, rangeLow, bottom, top, bull2, STOCHk, CCI4, CCI20, MOMma, CKSPl, CKSPs, ATR%, ATR, resample_120_open, resample_120_high, resample_120_low, resample_120_close, resample_120_ATR, buy, sell]
Index: []
2021-05-04 13:32:11,972 - freqtrade.commands.trade_commands - ERROR - The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
`

So I confirm, it is for some reason, empty.

**Comment by xmatthias** [comment]
Maybe try to print what `current_time` is (the one you're using to filter the dataframe with).

What's passed in will clearly not be at "timeframe" level (so it might be 10:03:22 - while the candle would be 10:00:00) - but `timeframe_to_prev_date` should take care of this.

you should however also be careful not to reassign to the same variable - that's rather confusing - especially when trying to help you.

**Comment by rylos** [comment]
Ok i've printed part of the populate indicators dataframe:
`
                          date     open     high      low    close        volume
1494 2021-05-04 06:00:00+00:00  0.19255  0.19620  0.19165  0.19335    1474.42405
1495 2021-05-04 07:00:00+00:00  0.19330  0.19730  0.18680  0.18680    1650.60115
1496 2021-05-04 08:00:00+00:00  0.18680  0.19105  0.18085  0.19075   15089.33670
1497 2021-05-04 09:00:00+00:00  0.19075  0.21910  0.19075  0.21070  100469.22590
1498 2021-05-04 10:00:00+00:00  0.21070  0.25120  0.21000  0.24440  181839.18555
`

and this is the current_time variable `2021-05-04 11:00:00+00:00`

So the current_time is 1 hour ahead of the dataframe populate_indicators last candle.
So `timeframe_to_prev_date` isn't getting the correct last candle time. Now I can workaround this of course, but it is not correct?

**Comment by rylos** [comment]
So I can confirm you that making this subtraction is working in live/dry mode but I don't think it is correct way timeframe_to_prev_date should work:
`
last_candle_time = timeframe_to_prev_date(self.timeframe, current_time) - timedelta(hours=1)
`

**Comment by rylos** [comment]
I have found also another problem, but with solution. There is a race condition when custom_stoploss is called (every cycle refresh) and the new candles dataframe from exchange (tested on ftx and binance).
For example, lets assume we are using 1h candles, lets take a current_time of 11:02.35, custom_stoploss is called BUT new candle dataframe isn't yet arrived from exchange (this time is the sum of exchange delay and complexity of populate_indicators). so the returnet row is empty.

Here is the final solution working (but i still think timeframe_to_prev_date needs to be fixed for the correct timezone):
```
def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, dataframe: DataFrame,
                        **kwargs) -> float:
        # Default return value
        result = 1
        if trade:
            last_candle_time = timeframe_to_prev_date(self.timeframe, current_time) - timedelta(hours=1)
            current_row = dataframe.loc[dataframe['date'] == last_candle_time].squeeze()
            if 'resample_120_ATR' in current_row and not current_row.empty:
                new_stoploss = (current_rate - current_row['resample_120_ATR']) / current_rate
                result = new_stoploss - 1
        return result
```
For the race condition the fix is to add this to the if: `and not current_row.empty`.

**Comment by xmatthias** [comment]
it's not a race condition, really - but simply the exchange not having the candle ready at 11:00:00, but maybe at 11:00:05 (whenever the first trade happens in this candle - so this will depend on the pair).
`11:02.35` seems excessive and i don't think it's a problem.

`timeframe_to_prev_date` is also not timezone-dependent - the 1h you're subtracting suggests that you're using 1h candles - which makes sense to some extend - as all candle dates are at the candle's open date - so the last date available at 11:02:35 will be 10:00:00-11:00:00 - with the date of 10:00.

**Comment by rylos** [comment]
Ok thank you for your time. Maybe it's better to polish the indicator custom_stoploss example in the documentations to make it all clear for other people.

**Comment by xmatthias** [comment]
the original example used `.iloc[-1]` in dry/live modes - and the "date filtering" for backtesting / hyperopt.

I suspect that's the "safe" variant to use this ...

**Comment by rylos** [comment]
Maybe I'm missing something, I'm watching this link [https://www.freqtrade.io/en/latest/strategy-advanced/#custom-stoploss-using-an-indicator-from-dataframe-example](https://www.freqtrade.io/en/latest/strategy-advanced/#custom-stoploss-using-an-indicator-from-dataframe-example)
I don't see the `.iloc[-1]`

**Comment by xmatthias** [comment]
i said the original example - which was modified by now .. :)

**Comment by rylos** [comment]
I've seen you have updated the logic behind this, so the new method in [https://www.freqtrade.io/en/latest/strategy-advanced/#custom-stoploss-using-an-indicator-from-dataframe-example](url)
I imagine is the new correct method. Very good! Thank you.
I think this can be closed now...

**Comment by cTatu** [comment]
I was looking at that example and I think the `.iloc[-1]` is a red flag that we shouldn't use. In the docs says using absolute values is essentially looking into the future and shouldn't use them. Is this still correct, and I am missing something or the example is wrong?

**Comment by xmatthias** [comment]
it is still correct - BUT depends on the location.
in `populate_*` methods, do NEVER use `.iloc[-1]`.

in callback methods, it depends. In new versions, the `get_analyzed_dataframe()` method will only return data "up to this point" - so using `.iloc[-1]` is safe. If you load different data though, you'll still need to be very careful.
