### ISSUE TITLE
VolatilityFilter is not one of ['VolumePairlist]

### ISSUE THREAD

**Issue by malcomZ** [freqtrade/freqtrade#4878]
## Describe your environment

  * Operating system: Debian 10
  * Python Version: 3.7.3 (`python -V`)
  * CCXT version: 1.41.78(`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hello,

when using the parameter VolatilityFilter does not work with VolumePairList.

After several searches I can't find a solution 
Here are the pictures:

https://ibb.co/zV11Lyq
https://ibb.co/dmj3TVR

**Comment by xmatthias** [comment]
You should update your version.
It's available in 2021.4 and in the latest develop. your ccxt version suggests that you're using a rather old version of freqtrade (you don't provide other  info - and "develop" is a moving target - so you'll need to make sure to keep updated.

**Comment by malcomZ** [comment]
Thank you very much for your time, the stable branch was up to date but not the develop.
An error occurs while for the telegram part it works before 
https://ibb.co/yVKySv8

**Comment by xmatthias** [comment]
Please follow the [update guide](https://www.freqtrade.io/en/latest/updating/) to also install requirements.

**Comment by malcomZ** [comment]
Thank you very much for your help and your time.
