### ISSUE TITLE
multi timeframe

### ISSUE THREAD

**Issue by HAGAI123** [freqtrade/freqtrade#4879]
Hello I have a question, is there such a possibility that the same strategy will trade in several timeframe at the same time? Without opening another different bot

and why when i try to connect to the bot web from other computer is tell me 
Internal Server Error

**Comment by xmatthias** [comment]
Freqtrade will trade based on one timeframe. You can use [informative pairs](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-informative_pairs) to get other timeframes, but  they can be used by the strategy to determine buy signals - the timeframe used is however only one per bot.

---

To help you with issues, please fill out the issue template.

**Comment by HAGAI123** [comment]
And if I open another bot I can't connect the telegram together ?

**Comment by xmatthias** [comment]
you have to use a different telegram bot - as explained [here](https://www.freqtrade.io/en/latest/advanced-setup/#running-multiple-instances-of-freqtrade).

**Comment by HAGAI123** [comment]
OK , and what about this 
and why when i try to connect to the bot web from other computer is tell me
Internal Server Error

**Comment by xmatthias** [comment]
> To help you with issues, please fill out the issue template.

You'll also need to provide some logs - and it's not related to this issue - so please open a new issue for this, filling out the info template - and providing the information necessary.
