### ISSUE TITLE
Collapsed Bollinger Bands

### ISSUE THREAD

**Issue by pdoorr** [freqtrade/freqtrade#4881]
Hi,
I'm experiencing a strange issue with Bollinger Bands that sometimes collapses i.e. middle, high and low have all the same value (pic below). Currently to avoid sell or buy when it happens, in the populate trend function I'm checking that the upper or lower differs from middleband, but it's clearly not optimal.

Is there some reason why it happens?

Thanks,
fabio
<img width="287" alt="CollapsedBB" src="https://user-images.githubusercontent.com/3625651/117169502-6fc2c800-adc9-11eb-8156-93c5b197e7ee.PNG">

**Comment by xmatthias** [comment]
The most likely reason is #4382 - assuming you're using BTC pairs.
once VAR (variance) becomes very small, it'll run into some issues in the current pandas version.

It's expected to be fixed with the next (mid) release ... but not yet out.

**Comment by pdoorr** [comment]
Ok thanks, in the meantime I've found the  same solution reported in #4382.
Thanks again, great work!

fabio
