### ISSUE TITLE
Backtesting - enrich result for better representation on many charting tools

### ISSUE THREAD

**Issue by mseld** [freqtrade/freqtrade#4883]
## Describe your environment
  * Operating system: macOs Big Sur v 11.2.2
  * Freqtrade Version: docker-da5e832a

## Describe the enhancement
Export backtesting results compatible with tradingview script v4 or any other charting tool

#### tradingview Script 
```
//@version=4
strategy("AwesomeStrategy", overlay=true, initial_capital=10000, commission_type=strategy.commission.percent, commission_value=0.0016)

strategy.order("0", 1, 0.093, 62483.33, when = time_close == 1618422300000)
strategy.close("0", when = time_close == 1618427700000)

strategy.order("1", 1, 0.092, 62690.27, when = time_close == 1618409700000)
strategy.close("1", when = time_close == 1618413300000)

strategy.order("2", 1, 0.091, 63928.57, when = time_close == 1618390800000)
strategy.close("2", when = time_close == 1618395300000)
```
Also many tools require information about candles with trades and indicators, So that I would recommend to add to exported results the following information 
- Candles (ohlcv)
- Trades
- indicators 

#### sample
```json
{
    "pair": "ETH/USDT",
    "amount": 10000,
    "candles": [
        [ 1555315200000, 5194.8, 5197.3, 5182.4, 5192, 129.53875463 ],
        [ 1555318800000, 5192, 5195.7, 5190, 5195.6, 90.52421995 ],
        [ 1555322400000, 5195.6, 5195.7, 5170, 5174.2, 233.89034995 ]
    ],
    "trades": [
        [
            1555315200000, 1, 4118.32 ]
    ],
    "indicators": [{
            "name": "EMA",
            "data": [
                [ 1543572000000, 4079.63478779 ],
                [ 1543575600000, 4076.0859579599996 ],
                [ 1543579200000, 4074.5101150399996 ]
            ]
        },
        {
            "name": "RSI",
            "data": [
                [ 1543644000000, 37.44767859168528 ],
                [ 1543647600000, 40.58994047209427 ],
                [ 1543651200000, 43.298594999255464 ]
            ]
        }
    ]
}
```

**Comment by xmatthias** [comment]
Freqtrade provides it's own set of plot scripts (`freqtrade plot-profit`, `freqtrade plot-dataframe`), and i'm working on backtesting support for [freqUI](https://github.com/freqtrade/frequi).

Tradingview support is therefore irrelevant (and not desired, as they do many indicators in a closed-source way that do not correspond to the original papers).

The above format is for sure not a format we will be exporting data in. 
Splitting candles from indicators is a "javascript" concept (as far as i've seen so far) - which is very prone to errors / exceptions should the lines mismatch for whatever reason.

while this might be a format that can be used by some graphing tools - loading this into a pandas dataframe is almost impossible, and is therefore not relevant to freqtrade.

Trades are already exported from backtesting `--export trades`.
If you think it's a must, exporting the dataframe *in a pandas-compatible format* (which means it should be a one-line pandas dump - and one-line pandas read), feel free to add support for this on an **optional** basis (must be enabled explicitly).

The big problem is - this can become rather large data (if you run backtesting for a year of 5m data for multiple pairs, you can fill up a disk pretty easily - and the usability of this data is quite limited.
