### ISSUE TITLE
how to install ta library with docker

### ISSUE THREAD

**Issue by EloutV** [freqtrade/freqtrade#4884]
Trying to run a backtest with recently upload strategy GodStra. Keep getting error messages with docker.

Error message:
2021-05-06 13:41:50,159 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/GodStra.py due to 'No module named 'ta''
2021-05-06 13:41:50,761 - freqtrade - ERROR - Impossible to load Strategy 'GodStra'. This class does not exist or contains Python code errors.

docker-compose.yml
# Build step - only needed when additional dependencies are needed
    build:
       context: .
       dockerfile: "/freqtrade/dockerfile.technical"

dockerfile.technical
FROM freqtradeorg/freqtrade:develop

RUN pip install ta
RUN pip install technical

Note: following these steps I was able to install technical library. E.g. to run the MultiRSI strategy. But apparently ta requires something else, or what I am doing wrong?

Thanks a lot!
Elout

**Comment by xmatthias** [comment]
we have [documentation](https://www.freqtrade.io/en/stable/docker_quickstart/#additional-dependencies-with-docker-compose) which covers installing dependencies.
This changed with the last release - so make sure to read the updated guide (technical is also builtin - so no additional installation is necessary).


Which dependencies are necessary for which strategy will differ - so you will need to adjust your Dockerfile accordingly ( i guess you'll need ta (`pip install --user ta`) for that strategy.

**Comment by EloutV** [comment]
Thanks for the quick reply. I followed up as suggested: pulled the latest version of freqtrade, changed the config, but still same error message. Also tried on raspberry pi with exactly same issues. 
Finally I also tried the Heracles strategy (also available in strategies folder using the same lib) with same result. 
Any suggestions?
Thanks again
Elout

**Comment by EloutV** [comment]
One additional finding. Pulled latest version of freqtrade on raspberry pi as well. Now I have following error message:
FT_GODSTRA_BTC | standard_init_linux.go:219: exec user process caused: exec format error

**Comment by xmatthias** [comment]
On a raspberry, you need to pull the `develop_pi` or `stable_pi` image. the regular images (`stable` / `develop`) are for x86 machines, not for raspberries
