### ISSUE TITLE
Sold cyrpto on Binance but it still appears on telegram status as current trade

### ISSUE THREAD

**Issue by jlartey10** [freqtrade/freqtrade#4888]
* Operating system: Ubuntu20.04
  * Python Version: Python 3.8.5
  * CCXT version: ccxt==1.47.4
  * Freqtrade Version: freqtrade develop-a7f8da4b

Sold crypto on Binance but it still appears on telegram status as current trade. Is there a way I could get rid of this pair? Is there a database I could remove this from? Thank you

**Comment by xmatthias** [comment]
If you manually sell assets, you'll always have to make sure the bot knows about it.

there is a [database ](https://www.freqtrade.io/en/stable/sql_cheatsheet/) for sure to keep track of trades.

The simpler solution will however be to issue a `/delete <tradeid>` command via telegram to remove the trade - but depending on your needs, you might also want to simply close the trade out properly with the sell-rates that were used.
