### ISSUE TITLE
Backtest results don't match the results from bot

### ISSUE THREAD

**Issue by Kaw11** [freqtrade/freqtrade#4889]
Operating system: Ubuntu 20.04.2.0
Python Version: Python 3.8.5
CCXT version: 1.42.19
Freqtrade Version: freqtrade 2021.2
  
## Your question

Hello! 
After a month of running the bot on dry_run I compared the results from bot (/profit) with backtesting results on my PC for the same period of data, and the information from both sources is completely different. Is this normal?

**Comment by xmatthias** [comment]
Please have a look at the [backtesting assumptions](https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting).

As backtesting only has 4 datapoints per candle avalable, it's expected to be slightly different.
Depending on how the strategy works / is made - alignment can be between almost perfect to not really - where only buy-signals align but the profit itself doesn't).

Obviously, the gap widens on wider timeframes - but again, it'll depend on how your strategy works (what the main sell-reasons are, ...).

**Comment by sinaban** [comment]
based on the backtesting documents" Sell-signal sells happen at open-price of the consecutive candle", I want to sell signal just on open price like backtesting data, how can set it to sell at the open price of the consecutive candle?

**Comment by xmatthias** [comment]
you can't - but while you may think it will give you better alignment, it really will not, as you will encounter many unfilled orders in that case - as you might be placing the order away from "current price".

**Comment by sinaban** [comment]
thank you for responding
