### ISSUE TITLE
Data for longer periods of time (30+)

### ISSUE THREAD

**Issue by Kaw11** [freqtrade/freqtrade#4890]
Operating system: Ubuntu 20.04.2.0
Python Version: Python 3.8.5
CCXT version: 1.42.19
Freqtrade Version: freqtrade 2021.2
  
## Your question

I tried to combine the candlestick data from 2 different months in one file manually,backtested it and it worked. Now I'm wondering if there is a way how to do this more automated?

**Comment by xmatthias** [comment]
I recommend to read the [documentation](https://www.freqtrade.io/en/stable/data-download/), or use the `--help` switch on the commands.

You can use `freqtrade download-data --days 200` or `freqtrade download-data --timerange 20200101-` to download more data.
