### ISSUE TITLE
Is Trend Intensity Index available?

### ISSUE THREAD

**Issue by Zast996** [freqtrade/freqtrade#4891]
## Environment

    Operating system: Ubuntu Linux 20.04
    Python Version: 3.8.5
    CCXT version: 1.43.89
    Freqtrade Version: 2021.3

## Question

Is Trend Intensity Index available in the talib library?

**Comment by xmatthias** [comment]
We do not provide support for the ta-lib library - and we will not do research for you.

Please investigate yourself by reading the [ta-lib documentation](http://mrjbq7.github.io/ta-lib/)

**Comment by Zast996** [comment]
I am sorry, I though that the library was implemented by freqtrade creators.
I searched before writing this post, but I didn't find anything, thus I wanted be sure asking directly to you.
