### ISSUE TITLE
PerformanceFilter improve ordering logic

### ISSUE THREAD

**Issue by severe-hed** [freqtrade/freqtrade#4893]
## Describe the enhancement

I've configured a new bot with static pair list and performance filter
It's totally new, so no trades yet (so no information about performance)
But when checking /whitelist command in telegram I can see that order is not the same like in my static whitelist
Sometimes user wants to presetup order that will be changed on performance
My suggestion is to make order like this:
1. Positive performance sorted
2. Zeroes based on static list
3. Negative sorted

Bonus suggestion here to set presorted static list as a parameter to PerformanceFilter and maybe some params how to use it (as described above/priority to presorted static/etc)

**Comment by xmatthias** [comment]
Feel free to submit a pull request changing this order.

You should however not go on "based on static list" - but based on the input to the filtering list - as it must be independent to using static or volume pairlists.
