### ISSUE TITLE
Strategies file : pointing which one to use

### ISSUE THREAD

**Issue by Oubaluna** [freqtrade/freqtrade#4895]
Hi everyone,

Hope you're well 👍  

I have really newbie question but I can't figure out how to run a specify strategy. I'm using 2 strategies file : Sample_strategy.py and AwesomeStrategy.py. 

Inside my docker-compose.yml, I put the following code : 
trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy AwesomeStrategy

However the bot keeep insisting on using the sample_strategy (I saw on terminal - log file) 

Anyway, I really don't know where I should point out to use the other python file I create. 

Thanks for reading me and for your help !! :D

**Comment by xmatthias** [comment]
You should make sure to stop the bot (`docker-compose down`) before changing the file.

You should then have a look at the complete (!) file to make sure it's not containing a different `--strategy` or `-s` flag.
Then you can start the bot again (`docker-compose up -d`) - and check the logs again (`docker-compose logs -f`).

**Comment by Oubaluna** [comment]
Yeay ! Thank you so much I succeed start another one strategy by using this command
