### ISSUE TITLE
Bot stopped trading

### ISSUE THREAD

**Issue by Novitec1** [freqtrade/freqtrade#4897]
Have you searched for similar issues before posting it?  Yes

## Describe your environment

  * Operating system: Ubuntu
  * Python Version:  3.8.5
  * CCXT version:  1.42.19
  * Freqtrade Version:  freqtrade-develop 0bb90d14 
  
## Your question

All already posted but, forgot to fill in the require fields, my bot just suddenly stopped working.  I have no idea why, I didnt make any changes to anything.  It was a very active bot up until recently and near the end before it stopped trading completely I also could not communicate with it on Telegram.  Ive tried re optimizing the strategy as I thought that may have been the issue but, that did not work.  Ive tried restarting the bot as well whenever I would lose communication with it and once restarted I would regain communication with it but, it would still not trade.  After these issues continued I stopped the bot and it showed that I had 10 active trades, except I didnt have any active traded showing on my Binance account.  I have no idea whats going on.  Any help would be greatly appreciated.

Thanks in advance!

**Comment by xmatthias** [comment]
trades are stored in the database. 
most likely, you've used a wrong / old database at some point - so now freqtrade thinks all slots (`max_open_trades`) are filled - preventing it from entering new trades.

Without logs however - it's impossible to investigate this further.

**Comment by Novitec1** [comment]
My apologize for the ignorant question but, how does one retrieve logs?  Or would it be best just to reinstall freqtrade and start from scratch?

**Comment by Novitec1** [comment]
Ya so when I hit the status button on my TG it shows 10 active trades.  Some that have auto sold and some I have manually sold on Binance itself.  Thats so weird.

**Comment by xmatthias** [comment]
If you manually sell your trades, you'll need to either close them out [manually](https://www.freqtrade.io/en/stable/sql_cheatsheet/) - or run `/delete <tradeid>` via telegram for these trades.

The logs will be in your terminal (where you start the bot) - or available via `docker-compose logs` if running with docker.

**Comment by Novitec1** [comment]
Oh wow, I did not know that needed to be done if selling manually.  Thank you for that information.  I have deleted all 'open' trades.  Just waiting now to see if that fixed the problem.

**Comment by Novitec1** [comment]
Got some buys.  Thank you very much, sir.  This is greatly appreciated.  You have saved my head from hitting the wall anymore lol.
