### ISSUE TITLE
Take profit on a percentage of the total position size

### ISSUE THREAD

**Issue by vic9t** [freqtrade/freqtrade#4898]
Hi! I can't find any information related to the sell of a partial size of the total position. For example, I want to take profits by selling 50% of my position when the price reaches +10%.
Do you know how this could be achieved?

Thank you for your work,
Victor

**Comment by xmatthias** [comment]
Position stacking (and selling partial positions) is currently not supported.

Feel free to subscribe to #1519 to get updated once this is added.
