### ISSUE TITLE
Stochastic Trigger 

### ISSUE THREAD

**Issue by Oubaluna** [freqtrade/freqtrade#4899]
Hi ! 

Thank you so much for the great program ! I've been enjoying it and testing around 👍 

I used one of the indicator suggest in here for reproduce stochastic of Trading View : 

#RSI
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
        #StochRSI 
        period = 14
        smoothD = 3
        SmoothK = 3
        stochrsi  = (dataframe['rsi'] - dataframe['rsi'].rolling(period).min()) / (dataframe['rsi'].rolling(period).max() - dataframe['rsi'].rolling(period).min())
        dataframe['srsi_k'] = stochrsi.rolling(SmoothK).mean() * 100
        dataframe['srsi_d'] = dataframe['srsi_k'].rolling(smoothD).mean()

And I'm trying to trigger buy and sell with it, however it seems to not work at all /:

buy signal : (dataframe['srsi_k'] > dataframe['srsi_d'] & dataframe['srsi_k'].shift(1) < dataframe['srsi_d'].shift(1) & dataframe['srsi_d'] < 20)

sell signal : (dataframe['srsi_k'] < dataframe['srsi_d']) & (dataframe['srsi_k'].shift(1) > dataframe['srsi_d'].shift(1)) & (dataframe['srsi_d'] > 80)

May be I'm wrong somewhere, also I might not be in the good place as it's more TA lib question I suppose

Thank you so much for your help ! :D

**Comment by xmatthias** [comment]
your buy-signal syntax is wrong - you'll need to have parenteses for each condition ... so
`(dataframe['srsi_k'] > dataframe['srsi_d'] & dataframe['srsi_k'].shift(1) < dataframe['srsi_d'].shift(1) & dataframe['srsi_d'] < 20)`
becomes 
`(dataframe['srsi_k'] > dataframe['srsi_d']) & (dataframe['srsi_k'].shift(1) < dataframe['srsi_d'].shift(1)) & (dataframe['srsi_d'] < 20)`

sell signal seems ok at first glance - but double-check that as well to be sure
