### ISSUE TITLE
Is it possible to have a sequence of vol filter -> other filters -> vol filter, AND add a pair statically at the front?

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#4900]
For example we have a pairlist like 

```
			{
				"method": "VolumePairList",
				"number_assets": 10,
				"sort_key": "quoteVolume",
				"refresh_period": 100
			},

			{"method": "SpreadFilter", "max_spread_ratio": 0.01},

			{
				"method": "VolumePairList",
				"number_assets": 3,
				"sort_key": "quoteVolume",
				"refresh_period": 100
			}
```

And it returns "Pair1", "Pair2, "Pair3" but **we want to prepend "Pair4"**.

The desired result would become "Pair4", "Pair1", "Pair2", "Pair3".

**Comment by xmatthias** [comment]
no, it's a "pick and choose".
if you use StaticPairlist at the front, volumePairlist will only act as a sorting / filter - not adding new pairs.

A possible approach is #4493 - but i don't think anyone is working at that at the moment.
