### ISSUE TITLE
Wrong duration of pairlocks with long timeframe

### ISSUE THREAD

**Issue by thekitaev** [freqtrade/freqtrade#4901]
## Describe your environment

  * Operating system: ubuntu
  * Freqtrade Version: docker-4d9dc2a2

## Describe the problem:

I have a `12h` timeframe. Recently I have added some protections to stop bot from buying after several stops.

Tonight some of them triggered. But after they must have gone bot didnt buy anything. I checked DB and seen that all of them was placed until the end of a candle instead of `now + stop_duration`. Here they are:

`136|*|3 stoplosses in 15 min, locking for 30 min.|2021-05-09 03:58:02.107578|2021-05-09 12:00:00.000000|1`
`137|VET/USDT|Auto lock|2021-05-09 03:58:02.592653|2021-05-09 12:00:00.000000|1`

### Steps to reproduce:

  1. Timeframe with candle bigger than `stop_duration`
  2. Triggered protection
  
### Observed Results:

In pairstop 136 I exspected to have `until = '2021-05-09 04:28:02.107578'` 
I think the reason of this behaviour is in `exchange.timeframe_to_next_date` function that is used to calculate `until`

**Comment by xmatthias** [comment]
What's the configuration of protections you're using?

Also - protections will never stop in the middle of a candle, and always lock until the end of the candle - so a 30min lock on a 12h timeframe will lock the pair anything between 30min and 12 hours.
This is intentional this way - as unlocking in the middle of a candle is usually dangerous and not what you want (you'd be buying 6h into the candle, based on a signal that appeared 6 hours ago).

**Comment by thekitaev** [comment]
I was using these settings. For now I don't use any of them.

`"protections": [
    {
      "method": "StoplossGuard",
      "lookback_period": 1,
      "trade_limit": 1,
      "stop_duration": 5,
      "only_per_pair": false
    },
    {
      "method": "StoplossGuard",
      "lookback_period": 15,
      "trade_limit": 3,
      "stop_duration": 30,
      "only_per_pair": false
    },
    {
      "method": "StoplossGuard",
      "lookback_period": 30,
      "trade_limit": 5,
      "stop_duration": 60,
      "only_per_pair": false
    },
    {
      "method": "StoplossGuard",
      "lookback_period": 30,
      "trade_limit": 10,
      "stop_duration": 120,
      "only_per_pair": false
    },
    {
        "method": "CooldownPeriod",
        "stop_duration": 10
    }
]`

**Comment by xmatthias** [comment]
I'd suggest using all values as `_candle` - not the time-based variant.
This is even more important when using long timeframes i think.

From what i can see, it behaved as expected and as documented:

> All protection end times are rounded up to the next candle to avoid sudden, unexpected intra-candle buys.

source: [documentation](https://www.freqtrade.io/en/latest/plugins/#protections)

**Comment by thekitaev** [comment]
Maybe we could add setting like `round_pairlocks_to_candle` with default `true` so we can avoid this behaviour? Because auto locks also lock pair till the end of a candle that can be up to 12 hours.

**Comment by xmatthias** [comment]
having buys mid-candle usually means it's based on old data (your signals are calculated on closed candles only).

If you require such a setting, then you either have wrong assumptions - or you're using a lower-level timeframe to "really" base your signals on (so you have intra-candle signas that can change) - in which case you should be using that lower timeframe as your strategy timeframe - not 12h.
