### ISSUE TITLE
get full detail of all hyperopt result not onlye last one

### ISSUE THREAD

**Issue by cyaxaress** [freqtrade/freqtrade#4903]
## Describe your environment

  * Operating system: windoes
  * Python Version: 3.9.5
  * Freqtrade Version: 2021.4 (last docker image)
  

It it possible to get full detailed result (what was rsi ... bb..  for this epoch)of all hyperopt epochs and not only the last one?
I searched in documentation and I did not found my answer... I know we have command like hyperopt-list or hyperopt-show buy only last epoch has full detail

**Comment by xmatthias** [comment]
You should read the [documentation for `hyperopt-show`](https://www.freqtrade.io/en/stable/utils/#show-details-of-hyperopt-results) more carefully, then.
By specifying `-n` you can pick any epoch and show the details of that epoch.
There's even an example showing how to pick one specific epoch.

**Comment by cyaxaress** [comment]
thank you :)
