### ISSUE TITLE
Missing data on visibly good series

### ISSUE THREAD

**Issue by snussik** [freqtrade/freqtrade#4904]
When I run a strategy backtesting on [this dataset](https://mega.nz/file/6p1g0DoC#evYpq9xh4e4sVIwZ3QHLB-zkTf62zwDeZ35LR-smIzc) which I made myself (assume, `freqtrade backtesting --strategy MYSTRATEGY --timeframe 1m --timerange 20170101-20211230 --export=trades`), I get the following warning:
`Missing data at start for pair ETH/USD, data starts at 2018-02-26 21:00:00`
`Missing data at end for pair ETH/USD, data ends at 2019-02-22 21:00:00`

Visibly this set doesn't differ from the previous (the data was exported from Freqtrade):
<img width="834" alt="Screenshot 2021-05-09 at 21 25 30" src="https://user-images.githubusercontent.com/16715490/117582940-411c5880-b10d-11eb-81ad-df45ff3695d3.png">

So what steps can I do to check the file validity and find out what's wrong?

**Comment by xmatthias** [comment]
well looking at your data - the first datapoint is from has the date of `1519678800000` - which corresponds to `2018-02-26 21:00:00` (UTC).

As you're passing in 20170101- as starting point - the message is perfectly fine - the data starts later than what you specified.

I assume the same is happening with the end date.
It also doesn't correspond to the screenshot - which shows earier data.
If that data is in the file, then it's not stored in a sorted way - which makes the data substancially differ from regular freqtrade data.

It should also be noted that data created manually is not supported with freqtrade - while it's pretty easy to do so, don't expect help if it caues issues.
