### ISSUE TITLE
erros on hyperopt

### ISSUE THREAD

**Issue by bchatelet** [freqtrade/freqtrade#4914]
After a git clone command,
pytest returns 25 errors on _hyperoptloss.py and hyperopt.py

**Comment by xmatthias** [comment]
Tests pass when freqtrade is installed correctly and a supported python version is used (you can look at this yourself in the "actions" tab of this repository).

Based on the data provided - this is probably not the case (but what is wrong is unknown, as you basically provide no information).

If you expect help, please resubmit this issue, filling out the issue template - and including the logs  / more information about what failed.
