### ISSUE TITLE
freqtrade bot stops working

### ISSUE THREAD

**Issue by alphaIT** [freqtrade/freqtrade#4916]
## Describe your environment

  * Operating system: Debian GNU/Linux 9
  * Python Version: Python 3.8.10
  * CCXT version: ccxt==1.49.80
  * Freqtrade Version: freqtrade develop-bcab4456
  
## Your question

I'm using conda to run freqtrade. I can start the bot and it seems to work. I've connected it to a Telegram bot.

After 30 minutes the bot seems to stop working, after I leave my terminal connection. I don't get any response any more on the telegram commands.

- How can I check if the bot is still running?
- How can I prevent this from happening?

**Comment by xmatthias** [comment]
It'll depend how you run freqtrade.
if you're running it simply in your terminal (`freqtrade trade ...`) - it's obvious that closing the connection / terminal will stop the bot (closing the terminal will usually terminate all programs - unless they've been started with means to prevent that).

There's multiple methods to prevent this - either by using screen / tmux (your terminal is then within one of these tools, and can programs within will continue to run).
you can also use [systemd](https://www.freqtrade.io/en/stabke/advanced-setup/#configure-the-bot-running-as-a-systemd-service) - which will also keep the bot running.

Alternatively, you can use docker - and by running with `docker-compose up -d` you're running it in "daemon" mode - so it'll stick around  even while you're not connected.

**Comment by alphaIT** [comment]
I've tried to get the service working but got this status:

`
● freqtrade.service - Freqtrade Daemon
   Loaded: loaded (/etc/systemd/user/freqtrade.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2021-05-11 14:56:50 CEST; 26s ago
  Process: 554 ExecStart=/usr/bin/freqtrade trade --config config.json --strategy SampleStrategy --logfile $h/freqtrade/user_data/logs/logs.log (code=exited, status=203/EXEC)
 Main PID: 554 (code=exited, status=203/EXEC)

May 11 14:56:50 freqtrade systemd[464]: freqtrade.service: Unit entered failed state.
May 11 14:56:50 freqtrade systemd[464]: freqtrade.service: Failed with result 'exit-code'.
May 11 14:56:50 freqtrade systemd[464]: freqtrade.service: Service hold-off time over, scheduling restart.
May 11 14:56:50 freqtrade systemd[464]: Stopped Freqtrade Daemon.
May 11 14:56:50 freqtrade systemd[464]: freqtrade.service: Start request repeated too quickly.
May 11 14:56:50 freqtrade systemd[464]: Failed to start Freqtrade Daemon.
May 11 14:56:50 freqtrade systemd[464]: freqtrade.service: Unit entered failed state.
May 11 14:56:50 freqtrade systemd[464]: freqtrade.service: Failed with result 'exit-code'.
`

What can I do to solve this?

**Comment by xmatthias** [comment]
the systemd service file acts as an example (which needs to be modfiied in basically all cases).

Enter the environment you run freqtrade with (probably the virtual environment) - and use `which freqtrade` to get the binary path.
this is your `ExecStart` before the ` trade ...`  command. `/usr/bin/freqtrade` is almost never the right path for this.

If you've never worked with systemd before, it might be better to use docker - which is simpler to get started usually.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
