### ISSUE TITLE
current_profit in custom_sell and custom_stoploss does not align with backtest sell value

### ISSUE THREAD

**Issue by werkkrew** [freqtrade/freqtrade#4920]
Since we discussed this in Discord I am skipping the usual bits of information and just opening this for tracking purposes.

Currently the "current_rate" and "current_profit" parameters fed into the custom_sell and custom_stoploss methods uses the current candle "high", but if a sell is triggered based on this profit value, it gets recorded in the backtest at the value of the next candles "open" price.

This causes a discrepancy between what the strategy thinks it is doing and what backtest / hyperopt are reporting.

I do not necessarily know a better/best way to do this but I we both seem to agree that the sell rate which is recorded should match the current_rate value at the time the sale is triggered.

**Comment by viktors1982** [comment]
I think not get from "open", but get data from previus candle close.
Sample from backtesting. Real profit calculating from next candle. (in sell_reason i save profit from custom_sell and value is 0.01502759) 
 {
                    "pair": "LUNA/USDT",
                    "stake_amount": 150,
                    "amount": 8.73362445,
                    "open_date": "2021-05-02 11:10:00+00:00",
                    "close_date": "2021-05-02 11:50:00+00:00",
                    "open_rate": 17.175,
                    "close_rate": 17.278,
                    "fee_open": 0.001,
                    "fee_close": 0.001,
                    "trade_duration": 40,
                    "profit_ratio": 0.0039871,
                    "profit_abs": 0.59866376,
                    "sell_reason": "profit_010.01502759",
                    "initial_stop_loss_abs": 0.17175000000000015,
                    "initial_stop_loss_ratio": -0.99,
                    "stop_loss_abs": 0.17175000000000015,
                    "stop_loss_ratio": -0.99,
                    "min_rate": 17.175,
                    "max_rate": 17.468,
                    "is_open": false,
                    "open_timestamp": 1619953800000.0,
                    "close_timestamp": 1619956200000.0
                }

**Comment by werkkrew** [comment]
So on current develop a random backtest:

```
========================================================== SELL REASON STATS ===========================================================
|            Sell Reason |   Sells |   Wins |   Draws |   Losses |   Avg Profit % |   Cum Profit % |   Tot Profit USD |   Tot Profit % |
|------------------------+---------+--------+---------+----------+----------------+----------------+------------------+----------------|
| intrend_pullback_noroi |      52 |     42 |       0 |       10 |           0.3  |          15.41 |           34.31  |           3.85 |
|   intrend_pullback_roi |      49 |     48 |       0 |        1 |           2.33 |         114.21 |          263.518 |          28.55 |
|              stop_loss |      22 |      0 |       0 |       22 |         -10.29 |        -226.33 |         -523.638 |         -56.58 |
|              trend_roi |       8 |      7 |       0 |        1 |           0.76 |           6.07 |           14.428 |           1.52 |
|             force_sell |       2 |      0 |       0 |        2 |          -5.7  |         -11.4  |          -21.747 |          -2.85 |
|            notrend_roi |       1 |      1 |       0 |        0 |           0.06 |           0.06 |            0.154 |           0.02 |
```

As per excel, looking at "average profit" 

intrend_pullback_noroi -> 0.0039  (0.39%)
intrend_pullback_roi -> 0.024 (2.4%)
trend_roi -> 0.0127 (1.27%)
notrend_roi -> 0.015 (1.5%)


Doing the same with this PR:

```
========================================================== SELL REASON STATS ===========================================================                                                              
|            Sell Reason |   Sells |   Wins |   Draws |   Losses |   Avg Profit % |   Cum Profit % |   Tot Profit USD |   Tot Profit % |
|------------------------+---------+--------+---------+----------+----------------+----------------+------------------+----------------|
| intrend_pullback_noroi |      59 |     59 |       0 |        0 |           0.38 |          22.48 |           49.694 |           5.62 |
|   intrend_pullback_roi |      47 |     47 |       0 |        0 |           1.56 |          73.19 |          165.886 |          18.3  |
|              stop_loss |      21 |      0 |       0 |       21 |         -10.29 |        -216.04 |         -484.571 |         -54.01 |
|              trend_roi |       3 |      3 |       0 |        0 |           0.86 |           2.57 |            6.24  |           0.64 |
|             force_sell |       2 |      0 |       0 |        2 |          -5.7  |         -11.4  |          -20.573 |          -2.85 |
|            notrend_roi |       1 |      1 |       0 |        0 |           1.36 |           1.36 |            3.366 |           0.34 |
```

As per excel, looking at "average profit" 

intrend_pullback_noroi -> 0.0038  (0.38%)
intrend_pullback_roi -> 0.01557 (1.56%%)
trend_roi -> 0.008557 (0.86%)
notrend_roi -> 0.0136297 (1.36%)



And so, with that, I can confirm that current_profit in custom_sell 100% matches backtest output!

Thanks so much for the quick turnaround!
