### ISSUE TITLE
How's timeframe affect bot actions?

### ISSUE THREAD

**Issue by snussik** [freqtrade/freqtrade#4921]
I decided to run strategy on `1d` timeframe for `5 symbols` and `4 max trades` open. On start the bot opened 4 trades and after a couple of hours it closed one trade cause of take_profit. Then it opened the other trade.
I thought, that bot moves on each candle of size, defined by timeframe, but it appeared that trades can be made inside the 1d candle period not just on close or open:
```
ROI: Closed trades
∙ 35.500 USD (2.89%) (14.45 Σ%)
∙ 35.500 USD
ROI: All trades
∙ 34.985 USD (2.37%) (14.22 Σ%)
∙ 34.985 USD
Total Trade Count: 6
First Trade opened: 19 hours ago
Latest Trade opened: 5 hours ago
Win / Loss: 4 / 1
Avg. Duration: 10:43:27
```
So, how it actually works?

**Comment by xmatthias** [comment]
Assuming the signal is still active (which is usually the case throughout the full candle) - then the bot will buy as soon as a slot becomes available.
It would've bought at the same time as the others, but was limited by `max_open_trades`.

You can prevent this by specifying a [buy signal timeout](https://www.freqtrade.io/en/stable/configuration/#ignoring-expired-candles) - specifying for how long after the start of a candle you want buy-signals to be respected.
Especially on longer timeframes this will usually make sense.

**Comment by karthikdatta** [comment]
Even after I use "ignore_buying_expired_candle_after" configuration the bot is executing buy signals from past 10 15 candles in dry run. The bot is buying using the buy signal from past even if the but condition is not satisfying on the present time frame. How can I make sure it ignores the past buy signals which are no longer valid.

**Comment by xmatthias** [comment]
Freqtrade will only buy while the buy-signal is active.
If it buys later, then either it's a new buy-signal - or you've got a sticking buy-signal (or an instable one, which changes mid-candle).

`ignore_buying_expired_candle_after` only works within one candle - so if your buy-signal is persistent for more than one candle, then you need to fix you buy-signal.
