### ISSUE TITLE
Setting up different ports for multiple strategies

### ISSUE THREAD

**Issue by szucsaaron2** [freqtrade/freqtrade#4924]
OS: Linux
Freqtrade: Latest version (Docker)
  
## Your question
My question is how can I set up the ports for the REST API server to be able to track the 2 strategies I am running.
This is what I have in my docker-compose.yml
ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"

For strategyA, in the configA.json I have 
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,

For strategyB, in the configB.json I have 
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8081,

After trying this, NONE of the dashboards can be reached.

Previously the dashboard was working with only 1 strategy and 1 port open.
I tried reaching them at localhost:8080 and localhost:8081

My question is how I can set it up to function correctly?

Thank you!

**Comment by xmatthias** [comment]
i'm running the same config and don't have this problem - so from a technical point of view, i'm sure it's working.

Maybe make sure you've not mixed the 2 (so the 8081 port is running with the 8080 config ...).

Also, maybe run `docker ps` and post the output here (it should show the mapped ports ...)

**Comment by szucsaaron2** [comment]
The PORTS are empty for both lines.
I have one question. Are you running your 2 strategies from separate ft_userdata folders with 2 docker compose files, or in the same one?

**Comment by xmatthias** [comment]
I use the same file / folders - but different configurations.

I think you're starting freqtrade wrongly. 

please make sure to configure 2 services in your docker-compose files, and to use `docker-compose up -d` to start the bot (do not use `docker-compose run` for that - this will ignore parts of the docker-compose file).

You'll obviously need to add your "start command" to the compose file's service - but that will make sure it'll restart the same way after a potential server reboot.

**Comment by szucsaaron2** [comment]
Oh, I see! You are right, I have been running it with `docker-compose run`, since that's what I have found at one of the other questions about running multiple strategies! 
I am not so familiar with setting up an extra service with the compose file. Could you please provide an example of how my docker-compose file should look like?

Thanks a lot, @xmatthias!

**Comment by xmatthias** [comment]
Well the service basically needs to be duplicated in the file

so it'll be like this (obviously you'll need to replicate everything below that).
```
services:
  freqtrade:
  ...

  freqtrade_2nd:
  ...
```

**Comment by szucsaaron2** [comment]
Thank you that is amazing! I followed your instructions and now it's up and running!
