### ISSUE TITLE
errors on hyperopt, hyperoptloss

### ISSUE THREAD

**Issue by bchatelet** [freqtrade/freqtrade#4929]
pytest returns 25 errors on my configuration: 
platform linux (ubuntu 20.10), Ubuntu 20.04 has Python 3.8.2 as the default version
Python 3.8.6, pytest-6.2.3, py-1.10.0, pluggy-0.13.1, 
FAILED tests/optimize/test_hyperoptloss.py
FAILED tests/optimize/test_hyperopt.py

**Comment by xmatthias** [comment]
most likely, you've either messed up the sourcecode, or your installation is faulty / missing some dependencies.

Without the errors (which errors / the output) that hyperopt reports, therewill be nothing we can do for you.

**Comment by bchatelet** [comment]
My errors with pytest are (tested with python versions in virtual env :3.10.0b1, 3.7.10, 3.8.10):
ERROR tests/optimize/test_hyperopt.py::test_log_results_if_loss_improves - SystemExit: usage: pytes...
ERROR tests/optimize/test_hyperopt.py::test_no_log_if_loss_does_not_improve - SystemExit: usage: py...
ERROR tests/optimize/test_hyperopt.py::test_save_results_saves_epochs - SystemExit: usage: pytest [...
ERROR tests/optimize/test_hyperopt.py::test_read_results_returns_epochs - SystemExit: usage: pytest...
ERROR tests/optimize/test_hyperopt.py::test_load_previous_results - SystemExit: usage: pytest [glob...
ERROR tests/optimize/test_hyperopt.py::test_roi_table_generation - SystemExit: usage: pytest [globa...
ERROR tests/optimize/test_hyperopt.py::test_format_results - SystemExit: usage: pytest [global_opts...
ERROR tests/optimize/test_hyperopt.py::test_has_space[spaces0-expected_results0] - SystemExit: usag...
ERROR tests/optimize/test_hyperopt.py::test_has_space[spaces1-expected_results1] - SystemExit: usag...
ERROR tests/optimize/test_hyperopt.py::test_has_space[spaces2-expected_results2] - SystemExit: usag...
ERROR tests/optimize/test_hyperopt.py::test_has_space[spaces3-expected_results3] - SystemExit: usag...
ERROR tests/optimize/test_hyperopt.py::test_has_space[spaces4-expected_results4] - SystemExit: usag...
ERROR tests/optimize/test_hyperopt.py::test_has_space[spaces5-expected_results5] - SystemExit: usag...
ERROR tests/optimize/test_hyperopt.py::test_has_space[spaces6-expected_results6] - SystemExit: usag...
ERROR tests/optimize/test_hyperopt.py::test_has_space[spaces7-expected_results7] - SystemExit: usag...
ERROR tests/optimize/test_hyperopt.py::test_has_space[spaces8-expected_results8] - SystemExit: usag...
ERROR tests/optimize/test_hyperopt.py::test_has_space[spaces9-expected_results9] - SystemExit: usag...
ERROR tests/optimize/test_hyperopt.py::test_has_space[spaces10-expected_results10] - SystemExit: us...
ERROR tests/optimize/test_hyperopt.py::test_has_space[spaces11-expected_results11] - SystemExit: us...
ERROR tests/optimize/test_hyperopt.py::test_has_space[spaces12-expected_results12] - SystemExit: us...
ERROR tests/optimize/test_hyperopt.py::test_populate_indicators - SystemExit: usage: pytest [global...
ERROR tests/optimize/test_hyperopt.py::test_buy_strategy_generator - SystemExit: usage: pytest [glo...
ERROR tests/optimize/test_hyperopt.py::test_sell_strategy_generator - SystemExit: usage: pytest [gl...

**Comment by xmatthias** [comment]
To be honest, this sounds like you're not running `pytest` - but try to run the tests directly.

that's not an error with the tests - but simply with the way you're executing them.
as it's however not the full log (messages are truncated at the right) - it's still not very helpful.

Please make sure to install the dev dependencies (`pip install -r requirements-dev.txt && pip install -e .`) - and run pytest with `pytest` from the projects' root directory.

Please run `pytest` - and post the full output of running that command, wrapping it in tripple backtics (```) so it's properly formatted
