### ISSUE TITLE
 indexed hyperoptable params

### ISSUE THREAD

**Issue by mablue** [freqtrade/freqtrade#4931]
It will be perfect if we have
An option to converting something like:
```
optimal_buy_timeframe0=IntParameter(4, 20, default=10, space="buy")
optimal_buy_timeframe1=IntParameter(4+10, 20+10, default=10+10, space="buy")
optimal_buy_timeframe2=IntParameter(4+20, 20+20, default=10+20, space="buy")
optimal_sell_timeframe0=IntParameter(4, 20, default=10, space="sell")
optimal_sell_timeframe1=IntParameter(4+10, 20+10, default=10+10, space="sell")
optimal_sell_timeframe2=IntParameter(4+20, 20+20, default=10+20, space="sell")

```
To:

```
for i in range(3):
   optimal_timeframe[i]=IntParameter(4+(10*i), 20+(10*i), default=10+(10*i), space="same")
   
```
Or for hyperopt defferent values for buy and sell:
```
for i in range(3):
   optimal_timeframe[i]=IntParameter(4+(10*i), 20+(10*i), default=10+(10*i), space="both")
   
```

And in 
Buy method:
It can undrestand which value will passed by location of calling.
For example if
```
buy_params = {
   "optimal_timeframe" =[10,20,30]
}
sell_params = {
    "optimal_timeframe" =[5,7,9]
}
```

In buy strategy method the value of self.optimal_timeframe[1] will equal to 20
And In sell strategy method the value of self.optimal_timeframe[2] will equal to 9

@xmatthias

**Comment by xmatthias** [comment]
Hyperoptable Parameters need to be class-level variables.
Using any nested structure (like a list or dict) would mean we need to iterate through every object in the strategy trying to find Parameters.

For now, i don't see a reason to do this. The shown case can easily be achived with `buy_signal = CategoricalParameter(operators, default="SMA", space='buy')` - using an index is completely pointless and will only complicate the rest of the strategy.

**Comment by mablue** [comment]
Think that if I have 3 hyperoptable params for buy
and 3for sell
one or two of them may have two lines of code
(2*2+1)*2 line of code can reduce to one line with indexing and multi spaces. and its very beautifull than writing repeadly a same code.
its get mind blowing when somebody(not me!) want to use a function to generate hyperoptable params.
in that point you cant use def to pass things and get your needs.
you just shoud write inside of def: 10times forall your params...
Its good to have normal python rules and functionalitys for hyperoptable params.
for example if I just add some normal hyperoptable param inside an if statment the hyperopt command cant find it!!:))why?!

**Comment by xmatthias** [comment]
Hyperoptable parameters need to be specified as class variables.

This will provide more clarity over the proposed solution - which will make the strategies simpler to read for new users (which honestly, is a particular problem with your strategies provided to the strategy repository).

Allowing nested structures here would not just make the detection of these parameters more difficult, but would also make it much more difficult to determine which parameters even exist within a strategy.

**Comment by mablue** [comment]
> Hyperoptable parameters need to be specified as class variables.
> 
> This will provide more clarity over the proposed solution - which will make the strategies simpler to read for new users (which honestly, is a particular problem with your strategies provided to the strategy repository).
> 
> Allowing nested structures here would not just make the detection of these parameters more difficult, but would also make it much more difficult to determine which parameters even exist within a strategy.

@xmatthias thanks 
I just want to know that is an array a variable or not?
I think the answer is yes.
so why we should need a line by line extra Interpreter to findout hyperoptable parameters when python itself is a very useful and standard interpreter that can work with array variables!
we are in a wrong way we cant limit things cuz of that we have not many people that wants to write advance strategies also yes 2file strategies have not problem with it but we need to find a way to make one file advance hyperoptable strategies.
its like that I say I need water. and you say no you cant find it in kitchen cuz no one drinks Water when there is coffes and juices! except you! :)))

**Comment by xmatthias** [comment]
As mentioned above - hyperoptable parameters must be class-level variables.
Arrays will therefore not work.

**Comment by mablue** [comment]
@xmatthias Thanks to your Response.
yes .It can make several problems...
and may its confusing for user.
but The main problem is that "Extra line by line interpretor" 
I think we will work on it to dont use and load normally the strategies inside freqtrade.
maybe something like moving main function of freqtrade inside strategies. like many other framworks (react js , angular js , etc) that just have the mainest runing place of the code in the user hands to take ablity to work with it. I mean that if we run the code from the strategy we can discribe easily that how freqtrade works and remove external interpretors.
Yes Its a big change but can done...I think will done I want to do that, but I think I cant :))))

**Comment by mablue** [comment]
Like regular variables, class variables can store data of any type. So, we could store a Python dictionary, a Python tuple, or a Python list in a class variable.
I checked that too:
```
class test:
    y=[]
    for x in range(10)
        y.append(x*x)
```
its work without any problem 
@xmatthias please watch "y" its a class level variable!
and works well!
I want to test some Idea on it.Im now free for a while and want to work on freqtrade main structure 😎 
st like that :
```
wights = IntParameter(0,100,default=[0]*10,space=buy)

#TODO: same for catagorical,real and decimal params

print(len(wights))
>> 10
```

**Comment by xmatthias** [comment]
I do understand this, however detecting Parameters would mean we will need to go down every object in the class.

Currently, we iterate the class and check if the parameter is of a specific type.
Supporting nested structures (dicts, lists, ...) would mean we need to descent to every one of these structures trying to detect if it might contain parameters.
As this can have unintended side-effects, please accept the decision that we will not support this.

**Comment by mablue** [comment]
@xmatthias I always accept that its a dengrus change.
but I will try for my own its just an adventure for me I want to just have some fun in my forked repo "patch-5"cuz I love this app.And at the end just will show you the results... 
also I will try to reduce confusing Code snippets in strategy files...
thanks.for your Patience🙏🙏
