### ISSUE TITLE
Pause and resume Hyperopt

### ISSUE THREAD

**Issue by snussik** [freqtrade/freqtrade#4939]
As I've learned from #4928 some Hyperopt jobs can be long and its nothing to do with. Considering, that each Hyperopt job creates additional file with its state: .pickle & .pkl - so: is it possible somehow to pause/resume the Ho job ( or at least terminate and start it again form break point)?

**Comment by xmatthias** [comment]
no, this is not possible. 
Whenever you start a new hyperopt - it will start from scratch with a new random state (unless you provide a random state explicitly, in which case it'll repeat the same hyperopt run again - yielding the same hyperopt results.
