### ISSUE TITLE
ask bid strategies - order type

### ISSUE THREAD

**Issue by Huskerss** [freqtrade/freqtrade#4940]
Hello Community!
I have the issue that most trades are only partially filled, after studying and changing the order types and the ask- and bid strategy I  still couldn't find out which settings guarantee that the orders are going to be completely filled. I know about the feature FOK however then i lose out on many orders.

I am using a 1m strategy and wanted to ask for some support regarding changes in the settings, I would risk losing a small percentage each trade for making sure that the whole amount is bought / sold.

Any help is highly appreciated.

Thank you very much!
Sincerely,
Huskerss

**Comment by xmatthias** [comment]
market orders will guarantee filling - but you'll cross the spread (pay the spread) - as well as a potential slippage (depending on the orderbook size and your trade size).

The alternative (and in my eyes better) approach is to use inverted bid/ask pricing with limit orders ([market-order pricing](https://www.freqtrade.io/en/stable/configuration/#market-order-pricing) - but without switching the order-type to limit (the configuration will be identical to market orders - but still using limit orders).

Depending on the ordersize, this will give you 90-98% fills (at least it does on my strategies - but i don't use 1m timeframes) - you will pay the spread - but you will not be subject to unreasonable slippage (you still control the worst price at which your order will fill).

**Comment by Huskerss** [comment]
Hi Matthias! 
Wow. I am truly amazed by the speed with which you answered. Thank you very much.
I am a novice so i hope i got your message correctly.
Is my interpretation correct to use the following order type:

_order_types = {
    "buy": "limit",
    "sell": "limit",
    "emergencysell": "market",
    "forcebuy": "market",
    "forcesell": "market",
    "stoploss": "market",
    "stoploss_on_exchange": False,
    "stoploss_on_exchange_interval": 60,
    "stoploss_on_exchange_limit_ratio": 0.99,
}_

And the ask and bis strategy i would keep the default settings, right?
Thank you for your time, Matthias!

**Comment by xmatthias** [comment]
well no, that would be the default settings.
What i'm personally running is inverted bid / ask sides (just as in the linked documentation page) - but i'm keeping order_types as is.

**Comment by Huskerss** [comment]
Alright! Thank you, Matthias. One more question that has interested me for a long time:

How do you (or freqtrade) generate income? I mean despite your own trading projects. Why would you make the platform open source?

I am looking forward to your answer!

**Comment by Huskerss** [comment]
And the sum of the spread and the potential slippage of market orders is probably less than 0.05% right?

**Comment by xmatthias** [comment]
Not every minute or action has to generate a profit. While i'm now accepting [sponsors](https://github.com/sponsors/xmatthias/) - i'm not here for that or to monetize freqtrade directly.

> Why would you make the platform open source

So others can benefit from it - contributing to open source is also a constant learning experience - you get to meet great people - and others help you make the project better by implementing and contributing their ideas (which will in turn, spark your own ideas and result in a constantly improving platform - which will in turn also improve my profits).

> And the sum of the spread and the potential slippage of market orders is probably less than 0.05% right

well - no
it'll heavily depend on the pairs you trade in - and on the order size (if you trade 20$ stakes, your slippage will be minimal - with 10.000$ stakes, you'll experience quite some slippage.
