### ISSUE TITLE
locks telegram command

### ISSUE THREAD

**Issue by markuznw** [freqtrade/freqtrade#4942]
Hello and thanks for this awesome project.
Just wanted to report that the /locks command in telegram doesn't work on develop while it works fine on the latest stable. In stable it printed an empty table even with no locks, in develop the command just doesn't seem to output anything

EDIT: I noticed now it returns locks when there is at least one, but I think returning empty table like the stable version is way more clear

**Comment by xmatthias** [comment]
Nice catch :+1:
