### ISSUE TITLE
[DOCKER] How to install external python libraries for docker version of freqtrade?

### ISSUE THREAD

**Issue by szucsaaron2** [freqtrade/freqtrade#4946]
## Describe your environment

  * Operating system: Linux
  * Freqtrade Version: latest
  
## Your question

Hi!

I would like to install some external python libraries (eg. statsmodels) for my freqtrade, but I didn't find anything online about how to do that.
I would really appreciate some help!

Best wishes,
Áron

**Comment by xmatthias** [comment]
I'd recommend to read [the documentation](https://www.freqtrade.io/en/latest/docker_quickstart/#additional-dependencies-with-docker-compose) - which does cover this part.

**Comment by szucsaaron2** [comment]
Thank you again for your quick and helpful response @xmatthias !
