### ISSUE TITLE
Buy or sell only once, before the opposite condition is met

### ISSUE THREAD

**Issue by vic9t** [freqtrade/freqtrade#4948]
Hello!

I am trying to write a strategy that uses several EMAs to find buy and sell signals. The condition looks like this:

BuyCond = ma1 > ma4 and ma2 > ma4 and ma3 > ma4
SellCond =  ma1 < ma4 and ma2 < ma4 and ma3 < ma4

My problem is that the bot will buy or sell multiple times after this conditions are met. I would like to code a condition that would buy/sell only one time until the opposite signal's condition is fulfilled.

**Comment by xmatthias** [comment]
In general, i'd say you define one of the conditions as your trigger (most likely ma1 > ma4 - assuming the numbers are increasing timeranges).

For that condition, you use `crossed_above(dataframe['ma1'], dataframe['ma4'])` (look at the samples for how to do that) .
The others remain simple ">` conditions (guards) - that way, you'll only have a signal right after they cross - and won't have consecutive signals.

If you have further questions relating to this, please use the [discord channel](https://discord.gg/MA9v74M) to get support / help from the community.
People there love to help assuming the documentation has been consulted first.
