### ISSUE TITLE
SKDecimal and DecimalParameter Hyperopt documentation lacking.

### ISSUE THREAD

**Issue by dmitryr117** [freqtrade/freqtrade#4949]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Docker Image freqtradeorg/freqtrade:latest
  DIGEST:sha256:c368fe6c084bee86e7a6108083a33f5994d1407edc05c295e395d359dc3a26ab
  
## Your question

*Hello there. I am unable to find any examples of usage of DecimalParameter and SKDecimal. Any help would be appreciated.*

**Comment by xmatthias** [comment]
I'm not sure what exactly you're missing (sure, they're not used - but it's only slightly different words - we surely also don't have examples for all the different indicators on the docs ...).

Usage of `DecimalParameter` is identical to `IntParameter` - except for the `decimals=3` parameter (and it doesn't have a .range property).

`SKDecimal` you shouldn't usually need - it's simply the underlying space of DecimalParameter - and a 1:1 replacement with `Real`.
