### ISSUE TITLE
Low Hanging Fruit

### ISSUE THREAD

**Issue by kryofly** [freqtrade/freqtrade#495]
Need some place to records ideas, loose stuff, and most valuable: signs of low-hanging-fruit.
Those are small changes that you just can't find time todo. But someone with a shallow or quick understanding of Freqtrade can fix.

**Comment by kryofly** [comment]
**Cleanup vocabulary**
There is alot of places where 'data' is used, where 'ticks' is more of a meaningful name
So:
data  --> ticks
   * rename function optimize.load_data
   * to              optimize.load_ticks

**Comment by kryofly** [comment]
**Cleanup vocabulary**
Both tick_interval and ticker_interval are used.
Suggestion, rename both into tick_interval or tickfreq
So:
tick_interval / ticker_interval  --> tick_interval or tickfreq

**Comment by kryofly** [comment]
dataframe  .. problematic, it just means 'matrix', name bear no hint of content
           signals? taframe?

**Comment by kryofly** [comment]
Investigate if possible underlying error in strategy fixture when running pytest:
pytest -s freqtrade/tests/optimize/test_backtesting.py  will output:
freqtrade/tests/optimize/test_backtesting.py pair       buy count    avg profit %    total profit BTC    avg duration    profit    loss
-------  -----------  --------------  ------------------  --------------  --------  ------
BTC_ETH            2           15.00          0.60000000           100.0         2       0
TOTAL              2           15.00          0.60000000           100.0         2       0
.......strategy.py                102 ERROR    Impossible to load Strategy 'user_data/strategies/<MagicMock name='mock.strategy' id='140639016196976'>.py'. This file does not exist or contains Python code errors
strategy.py                106 ERROR    The error is:
expected str, bytes or os.PathLike object, not MagicMock.

**Comment by gcarq** [comment]
I'm closing this because most of that is outdated
