### ISSUE TITLE
buy based on the risk

### ISSUE THREAD

**Issue by yaotian** [freqtrade/freqtrade#4951]
Cond1: i only take $100 risk for every trade
Cond2: i  know the price of stoploss for a trade

Can  i  make this in FT?
1. I tell Cond1 and Cond2 to FT and FT calculate how many to buy and set the stoploss. 
2. Strategy will triger the profit selling( for example, cross down MA20) or stop loss.

Why:
Every risk is $100. If i can make 1:2 or 1:3 trade and 50% possible. This will be a good strategy.

**Comment by xmatthias** [comment]
In general, i'd say this is not possible. Initial stoploss is global, not per pair (although you can work around this with `custom_stoploss`).
Stake however is currently fixed (either a % of your total account, or fixed to `stake_amount`).


You can have a look at [edge](https://www.freqtrade.io/en/stable/edge/) which does something smilar - but not in a very flexible way, so i doubt it'll give you exactly what you want.
