### ISSUE TITLE
Can i add/remove pairs from whitelists using telegram?

### ISSUE THREAD

**Issue by xang555** [freqtrade/freqtrade#4970]
## Describe your environment

  * Operating system:  ubuntu 20.04
  * Python Version: 3.9.4
  * CCXT version: 1.48.76
  * Freqtrade Version: 2021.4
  
## Your question

*Can i add/remove pairs from whitelists using telegram?*

**Comment by xmatthias** [comment]
No you can't.
You can however add pairs to the blacklist - which will also remove them from the whitelist automatically.

For the future: Please use the search to try and find similar issues (#4493 ) - although in this case, it's kinda difficult to identify the correct issue.

**Comment by xang555** [comment]
thank you

**Comment by shocker1185** [comment]
why is this the case?

**Comment by mahmoudeA** [comment]
def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
    """
    Based on TA indicators, populates the buy signal for the given dataframe
    :param dataframe: DataFrame populated with indicators
    :param metadata: Additional information, like the currently traded pair
    :return: DataFrame with buy column
    """
    tickers = []
    with open('tickers.txt', 'r') as filehandle:
        for line in filehandle:
            # remove linebreak which is the last character of the string
            ticker = line[:-1]
            # add item to the list
            tickers.append(ticker)

    dataframe.loc[
        (
            # Signal: RSI 
            (dataframe['rsi'] > 0)  &
            (metadata['pair'] in tickers)
        ),
        'buy'] = 1

    return dataframe
