### ISSUE TITLE
Any guide on how to install a docker version of ft on a vps?

### ISSUE THREAD

**Issue by frank01100110** [freqtrade/freqtrade#4973]
I installed freqtrade through docker, following the quick start guide. Now I'd like to transfer it to a vps, but I've no idea where to start. I would really like if you could give me some direction.

**Comment by xmatthias** [comment]
If you're running with docker, then you can simply transfer your whole directory to the remote host (or just the user_data directory and the compose file).

Assuming you got docker installed there too (if not, please do so), simply use the same commands to start the container there.

**Comment by frank01100110** [comment]
> If you're running with docker, then you can simply transfer your whole directory to the remote host (or just the user_data directory and the compose file).
> 
> Assuming you got docker installed there too (if not, please do so), simply use the same commands to start the container there.

It sounds really easy. Tomorrow I'll try it.
