### ISSUE TITLE
[BACKTEST] Difference between live mode and backtest result (timeframe difference?)

### ISSUE THREAD

**Issue by szucsaaron2** [freqtrade/freqtrade#4976]
## Describe your environment

  * Operating system: Linux
  * Freqtrade Version: latest version (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi!

Could you please help me understand something? 
The way I imagine backtests being run, is the following: Freqtrade downloads all the data based on a given timeframe, let's say 12h timeframe. It runs the strategy and generates buy and sell signals based on the indicators. After this, it compares the prices of coins based on these timeframes. So for example it tests the price difference between 2021.05.19. 00:00:00, and 2021.05.19. 12:00:00. If the price at 2021.05.19. 00:00:00 was let's say 12.5 USDT, and the price at 2021.05.19. 12:00:00 was 15.0 USDT, then it will look at stoploss, trailing stoploss, and also ROI table to determine if the trade should be closed.

Now what I don't understand is how come this is not done the same on live trading. When I am running my strategy, I get a buy signal. The price of the coin is updated in the dashboard every 30-60 seconds. If the stoploss, trailing stoploss or ROI is fulfilled then it sells based on this 30-60s timeframe. This might not be correct, but this is my observation.

The problem is if my strategy calculates that there should be a buy signal at a given moment based on the specified timeframe and the data downloaded for that timeframe, but then there is a change in the live price which triggers stoploss or trailing stoploss.

My question is, isn't there a difference between live trading and backtesting here because of this difference between the specified timeframe and the live data because of this? Or am I misunderstanding something?

Thank you for your time and support!

Bests,
Áron

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by szucsaaron2** [comment]
Maybe as a side note, my configs are set up correctly as far as I am aware of it, so I have 12h timeframe in the strategy and also in the config.json.

What I also discovered is that the backtest results also showed an average of 2 trades/day, but on the live mode, I had about 5/day. This also supports the observation I wrote earlier, so live mode and backtest somehow operate on different timeframes.
On the other hand, if I backtest with a 5m-15m timeframe the average number of trades is also about 5

**Comment by xmatthias** [comment]
The timeframe attribute defines the candles (historic data) you get.
Usually, a signal is open for the whole duration of a candle (assuming you're using standard technical indicators).

This is why we have the mandatory lock until the end of the candle - to avoid "re-buying" the same candle again for the same pair.

This timeframe is also used for sell-signals (sell-reason sell-signal).
ROI and stoploss / trailing stoploss is evaluated in trade mode (dry/live) against the current live price (fetched based on the pricing configuration) - and will trigger at any point intra-candle - whenever the defined price is triggered.

In backtesting, this behaviour is simulated based on the [backtesting assumptions](https://www.freqtrade.io/en/latest/backtesting/#assumptions-made-by-backtesting).

Per candle, we have 4 values available (open, high, low, close) - but we have no idea about intra-candle movements.
Backtesting takes certain assumptions on the movements within a candle, but obviously the longer the timeframe becomes, the less precise this will be. obviously, we'll then not know after how much time the signal happened - so the the bot won't reuse this trade-slot intracandle in backtesting.


Sells in trade-mode will always happen based on the current price - however you can prevent "late" buys with the [`ignore_buying_expired_candle_after` setting](https://www.freqtrade.io/en/latest/configuration/#ignoring-expired-candles) - so after X amount of minutes, a newly available buy-slot would be ignored, and buys only happen right after a new candle arrives.

Shorter timeframes will improve accuracy of the simulation - longer timeframes makes it worse, as the "black spot" will increase.

**Comment by szucsaaron2** [comment]
Thank you for the explanation!
So if I get it right, if I set the timeframe in backtesting, it simulates everything from the samples based on this timeframe, therefore the accuracy decreases because of the missing samples that would represent the intra-candle movements. Right?

But doesn't this, also mean that the timeframe defined in the config.json, that the strategy also uses is not going to be the same?
So, even if I set the timeframe in the live mode to be 12h, it's going to get a live trading price for each tick, and not for every 12h time periods.

If that is the case, could you tell me the exact frequency of the ticks for the live data?

**Comment by xmatthias** [comment]
timeframe is applied to the candle data. Real-time checks (ROI, stop) are based on tick-data - and are usually around process_throttle_secs (5s by default).
depending on the calculation effort for your strategy (in relation to your system / network connection) - the 5s is not guaranteed.

**Comment by szucsaaron2** [comment]
Right, I understand!
Thank you very much for the help and detailed explanation! You are incredibly helpful!

**Comment by fridary** [comment]
@xmatthias hi, is there any programming or comfortable way to compare live and backtest results? I have a quite different now, I can check trade-by-trade via frequi web dashboard, but there are 100+ trades and I can not scroll candlestick chart very past. How do you do that when you need to compare why backtest and live have different profit?
