### ISSUE TITLE
backtesting options

### ISSUE THREAD

**Issue by bchatelet** [freqtrade/freqtrade#4977]
The option when backtesting "-export-filename user_data/backtest_results/myresult.json"
needs also the declare  "--export trades", since no result is produces when only the first option is used . Consequently the  "--export trades" becomes mandatory for export and also unseless, because only "trades" option seems to be available. It would be more handy for the user  to include the option "--export trades" implicitly within the option  "-export-filename my_result.json"

**Comment by xmatthias** [comment]
to be honest - there is no reason to use `--export-filename` anymore (as the files are now stored with unique filenames).

using `--export trades` is enough and will produce the result with unique filenames.
The reason to have `--export trades` - and not just `--export` is that there might be additional data that can be exported in the future - so changing this to something else now would probably result in changing this back again in the future.

**Comment by doza62** [comment]
I agree with @baartch. I run backtest for each strategy so I have a dedicated json file with the name of the strategy+timeframe for each analysis. This gives me the liberty to arbitrarily stop the backtest and continue where it left later on.

A consideration could be to set `--export trades` as a default option 
>-e, --export  [opt];  export results on a .json file. Options can be: trades, settings, etc. [Default=trades]

Later on, if `--export` has more options in the future, it can be overrided by redefining it on the command.
