### ISSUE TITLE
Hyperopt - is it possible to put variables in time period indicators ?

### ISSUE THREAD

**Issue by NicolasGuigui** [freqtrade/freqtrade#4978]
## Describe your environment
  * Operating system: Ubuntu 20.10 and Windows 10 
  * Python Version: Python 3.8.6
  * CCXT version: ccxt==1.47.47
  * Freqtrade Version: freqtrade develop-09b6923e

  
## Your question

Hi,

I am currently working on the HyperOpt module and I wanted to know if it is possible to put a variable in the time period of some indicator.
Example: I want to buy if an EMA with a time period X crosses upwards an EMA with a time period of Y. I would like to declare X and Y as variable to be determined. Is this possible or do I have to declare several EMAs and do lots of trigger conditions to test everything?

I want to do this:
```
@staticmethod
    def populate_indicators(dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        This method can also be loaded from the strategy, if it doesn't exist in the hyperopt class.
        """
        dataframe['emaX'] = ta.EMA(dataframe, timeperiod=X)
        dataframe['emaY'] = ta.EMA(dataframe, timeperiod=Y)

        return dataframe
```
Instead of this:
```
@staticmethod
    def populate_indicators(dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        This method can also be loaded from the strategy, if it doesn't exist in the hyperopt class.
        """
        dataframe['ema3'] = ta.EMA(dataframe, timeperiod=3)
        dataframe['ema5'] = ta.EMA(dataframe, timeperiod=5)
        dataframe['ema10'] = ta.EMA(dataframe, timeperiod=10)
        dataframe['ema20'] = ta.EMA(dataframe, timeperiod=20)
        dataframe['ema50'] = ta.EMA(dataframe, timeperiod=50)
        dataframe['ema100'] = ta.EMA(dataframe, timeperiod=100)
        dataframe['ema120'] = ta.EMA(dataframe, timeperiod=120)
        dataframe['ema150'] = ta.EMA(dataframe, timeperiod=150)
        dataframe['ema180'] = ta.EMA(dataframe, timeperiod=180)
        dataframe['ema200'] = ta.EMA(dataframe, timeperiod=200)

        return dataframe
```
Is it possible ? I did not succeed in my tests, but maybe I did it wrong?

**Comment by xmatthias** [comment]
Please read the [hyperopt documentation](https://www.freqtrade.io/en/stable/hyperopt/#optimizing-an-indicator-parameter) - which includes a sample of this (even using exactly the same indicator - EMA).

**Comment by NicolasGuigui** [comment]
Ok, my bad, I hadn't seen it :/
Thank you for the direct link.
