### ISSUE TITLE
Question about hyperopt on vps and hardware requirements

### ISSUE THREAD

**Issue by frank01100110** [freqtrade/freqtrade#4980]
I'd like to try hyperopt, but I don't want to burn my old laptop. I was wondering if running it on a cheap vps, with 1 cpu, and some memory swap as ram expansion, could do the trick and how many hours could it take to generate an hyperopt result, considering the low specs.

**Comment by xmatthias** [comment]
Running hyperopt on low-end specs is not supported, nor will it lead to desired results.

There used to be a bug in skopt which had it fail if only 1 cpu was available - i never tested if that's still the case.

Hyperopt will run backtesting over and over again. having 1 cpu will make it run serially, which will make it take forever.
also, memory needs to fit in memory at least "once per core" (with some margin left) - and using swap will make it very slow again.
