### ISSUE TITLE
Bot commands and docker need help

### ISSUE THREAD

**Issue by frank01100110** [freqtrade/freqtrade#4983]
While my docker is running, let's say I want to check list-pairs or download historical data.

I've no idea how to do it on the dockerized version of freqtrade. It has something to do with appending code to "docker run -d \" right?

I would be really grateful if you could give me some examples.

**Comment by xmatthias** [comment]
You can use regular freqtrade commands - simply prefixing them with `docker-compose run --rm freqtrade ...` - so listing pairs;


`docker-compose run --rm freqtrade list-pairs `

**Comment by frank01100110** [comment]
> You can use regular freqtrade commands - simply prefixing them with `docker-compose run --rm freqtrade ...` - so listing pairs;
> 
> `docker-compose run --rm freqtrade list-pairs `

Thank you so much.
