### ISSUE TITLE
Analyzing live strategy data in jupyter (or any other method)

### ISSUE THREAD

**Issue by talhazan** [freqtrade/freqtrade#4989]

**Comment by xmatthias** [comment]
You can use the [strategy analysis](https://www.freqtrade.io/en/latest/strategy_analysis_example/) notebook to analyze your strategy on historic data in a notebook.

It's not possible against real-time data easily (for technical reasons) - but the benefit of this is not what you think it is - as the data changes, so you can't rely on your analysis (as the data changes while you think about it).

If you need real-time data with indicators, please use frequi.

If you need to reload your strategy - please use `/reload_conf` - eihter via telegram, or from freqUI.
