### ISSUE TITLE
stoploss_on_market failures: don't handle violently

### ISSUE THREAD

**Issue by bzed** [freqtrade/freqtrade#4999]
## Describe your environment

  * Operating system: Debian buster
  * Python Version: 3.7.3
  * CCXT version: 1.49.73
  * Freqtrade Version: develop

## Describe the problem:

FT is doing an emergency_sell in case stoploss_on_market fails. This can happen for various reasons, including issues on the exchange. Selling in a emergency way can lead to massive losses without a real reason. Freqtrade should handle this more gracefully by using the internal stoploss instead the stoploss on market. At least this should be a configurable option.

### Steps to reproduce:

  1. run live on binance with stoploss on market enabled
  2. wait
  3. see emergency sells happen
  
Stoploss on market is a nice to have thing, but if it doesn't work, please allow the bot to handle it.

**Comment by bzed** [comment]
argh. keyboard fail. sorry.

**Comment by xmatthias** [comment]
Emergency sells happens in one case - when the return-value from the exchange is `InvalidOrder`.

If the exchange has a problem (unavailable, ...) - then the error will be different, and no emergencysell will happen, but the stoploss -order placement will be retried.

Usually, when people see a lot of emergency sells, their stoploss / trailing stoploss is too tight - causing the current price to be below the "stop-price".
Technically, this means that stoploss triggered (current price is < stoploss price) - so selling is the correct way to go.

If you think that's not what happens, please provide logs that show this (the logs do include the reject reason).

>  Freqtrade should handle this more gracefully by using the internal stoploss instead the stoploss on market

It's unclear to me what you mean with this - as mentioned above - price crossed below your (current) stop - so selling is the right approach.
sure, staying in the trade is an alternative - but i don't consider this "more gracefully" - but worse as it can lead to a lot of losses should the market tank in that moment.


The sell order type (market vs. limit) can be configured as part of the [order-types](https://www.freqtrade.io/en/stable/configuration/#understand-order_types) setting with `emergencysell` (either market or limit).
