### ISSUE TITLE
analysis for BTC?

### ISSUE THREAD

**Issue by easyFishDev** [freqtrade/freqtrade#5001]
Hi, please forgive maybe stupid question as I am new to this community.

I cannot find how to make bot working with BTC currency.

BTC is my "stake" currency.
I have other currencies specified in config JSON, like ETH/BTC, ATOM/BTC, ... but it's not possible to add BTC/BTC.

I solved this by using WBTC/BTC but seems to me like weird solution.

Can anybody please help me how to include "pure" BTC into analysis?

**Comment by xmatthias** [comment]
if BTC is your stake - you cannot trade BTC (there is no market - the rate between BTC and BTC would not change (it'll also never change between USDT/USDT ... or any other pair where both sides are the same currency.

As such - what you're asking is simply impossible (and the exchange will also not allow you to trade this).

If you must include BTC, consider switching your stake-amount to USDT (or some other currency) - where you will have BTC/<yourstake> pairs on the exchange.

**Comment by easyFishDev** [comment]
thanks
