### ISSUE TITLE
Live Mode only analyse data since bot start?

### ISSUE THREAD

**Issue by ericrange** [freqtrade/freqtrade#5004]
Is it normal that the live mode, takes 2-3 days before the first trades were made?

The ram is increasing in this time, so i guess the live mode will only analyse that data, that comes from that moment when the bot is started?

Is this by design? I downloaded all available pair data before i started the bot.

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
no, in trade mode you'll always have the last 500-1000 candles available (right from the start) - and never more (freqtrade does not accumulate candles - as that would lead to a long-term memory leak).

There can be other reasons for 2-3 days of silence (like - a trend indicator used in the strategy that's preventing the bot from buying) - but other than that - no.

Obviously you can code a strategy in a way so it does this - but i would doubt that we have any samples around which cause this (other than with indicators preventing buys).

**Comment by ericrange** [comment]
ok thanks ;)
