### ISSUE TITLE
freqtrade cost me money because i didn't test my strategy properly

### ISSUE THREAD

**Issue by tesla-cat** [freqtrade/freqtrade#5006]
freqtrade, it cost me 20k in one day with the sample strategy, the same amount I can easily make via manual trading....

**Comment by xmatthias** [comment]
Please keep a clean language.

also - in all documentation we clearly state that a strategy should be evaluated very carefully.

I've seen the strategy you're using - which clearly showed that you didn't put any thought into it.
i'm sorry that freqtrade is not an automated money machine - but requires work to put in to be profitable - but that's simply a truth. 

Obviously, if you're not putting this work and thought in, you'll not be profitable. 
I don't think you should or can blame the tool for that.
