### ISSUE TITLE
Buy/Sell strategy based on time?

### ISSUE THREAD

**Issue by klara31** [freqtrade/freqtrade#5011]
## Describe your environment

  * Operating system: Linux (docker)
  * Freqtrade Version: 2021.4

## Your question
Is it possible to create a strategy where a buy or sell signal is based on time of day? E.g. I want to buy a pair each day at 16:00 (local time). Or I don't want to buy between midnight and 08:00 (local time).

I have tried something like the following, but this is not working (in backtesting at least):
```
def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
    now_UTC = datetime.utcnow() # Get the UTC time
    dataframe.loc[
        (
            (now_UTC.hour == 16)
        ),
        'buy'] = 1
    
    return dataframe
```

**Comment by xmatthias** [comment]
using `datetime.now()` will use the current time - so your results will vary depending on when you're running backtesting (which will clearly not work.

You can however use the date column ([`dataframe['date'].dt.hour`](https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.hour.html)) for this...

**Comment by klara31** [comment]
Thanks, I'm making some progress, but I am afraid I am still doing something wrong... I have populated the buy trend like:
```
    dataframe.loc[
        (
            (dataframe['date'].dt.hour == 16)
        ),
        'buy'] = 1
```
However, this results in a timerange of several weeks in just one buy. What am I missing, do I need to populate the indicator as well? 

Is the datetime in dataframe in UTC?

**Comment by xmatthias** [comment]
Datetime is in utc.
You'll need to be careful - is it  buy - or one buy signal... 

i assume it'll be 1 signal per day - but if you don't have a sell-signal - you'll not see sells -> future buys are ignored.
