### ISSUE TITLE
TA-Lib Install Error // develop-9465fd39

### ISSUE THREAD

**Issue by MrHumanRebel** [freqtrade/freqtrade#5017]
* Operating system: Linux Mint Latest
  * Python Version: Latest
  * CCXT version: 1.50.30
  * Freqtrade Version: freqtrade-develop-9465fd39
  
Installing collected packages: TA-Lib, jinja2, ccxt
  Attempting uninstall: TA-Lib
    Found existing installation: TA-Lib 0.4.19
    Uninstalling TA-Lib-0.4.19:
      Successfully uninstalled TA-Lib-0.4.19
    Running setup.py install for TA-Lib ... error
    ERROR: Command errored out with exit status 1:
     command: /home/trade/freqtrade/.env/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y9m_8_hr/ta-lib_41f82cebeba948c68ebe73c9830ae93c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y9m_8_hr/ta-lib_41f82cebeba948c68ebe73c9830ae93c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ofemhz__/install-record.txt --single-version-externally-managed --compile --install-headers /home/trade/freqtrade/.env/include/site/python3.8/TA-Lib
         cwd: /tmp/pip-install-y9m_8_hr/ta-lib_41f82cebeba948c68ebe73c9830ae93c/
    Complete output (25 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/talib
    copying talib/abstract.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/stream.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/test_abstract.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/deprecated.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/test_func.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/test_data.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/test_stream.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/test_pandas.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/__init__.py -> build/lib.linux-x86_64-3.8/talib
    running build_ext
    building 'talib._ta_lib' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/talib
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/home/trade/freqtrade/.env/lib/python3.8/site-packages/numpy/core/include -I/home/trade/freqtrade/.env/include -I/usr/include/python3.8 -c talib/_ta_lib.c -o build/temp.linux-x86_64-3.8/talib/_ta_lib.o
    talib/_ta_lib.c:6:10: fatal error: Python.h: No such file or directory
        6 | #include "Python.h"
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of TA-Lib
  Moving to /home/trade/freqtrade/.env/lib/python3.8/site-packages/TA_Lib-0.4.19.egg-info
   from /home/trade/freqtrade/.env/lib/python3.8/site-packages/~A_Lib-0.4.19.egg-info
  Moving to /home/trade/freqtrade/.env/lib/python3.8/site-packages/talib/
   from /home/trade/freqtrade/.env/lib/python3.8/site-packages/~alib
ERROR: Command errored out with exit status 1: /home/trade/freqtrade/.env/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y9m_8_hr/ta-lib_41f82cebeba948c68ebe73c9830ae93c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y9m_8_hr/ta-lib_41f82cebeba948c68ebe73c9830ae93c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ofemhz__/install-record.txt --single-version-externally-managed --compile --install-headers /home/trade/freqtrade/.env/include/site/python3.8/TA-Lib Check the logs for full command output.
Failed installing dependencies
trade@trade:~/freqtrade$

**Comment by xmatthias** [comment]
You'll need the `python-dev` package (most likely something around `apt install python38-dev` )...
although the precise package-name can / will vary depending on the system you're using.

**Comment by MrHumanRebel** [comment]
I installed python3 -m pip install python-dev-tools --user --upgrade, the error does not go away. :(
Also pip3 install python-dev-tools

**Comment by francesco-plt** [comment]
I solved the issue by running `sudo apt-get install libatlas-base-dev`

**Comment by MrHumanRebel** [comment]
Thank you! @plt-francesco

**Comment by shujaatak** [comment]
I have Python3.9.5 installed in my Ubuntu machine. I was receiving this error: `talib/_ta_lib.c:6:10: fatal error: Python.h: No such file or directory` and installing python3.9-dev package worked for me `sudo apt install python3.9-dev.`

**Comment by smnchoi** [comment]
> @shujaatak  Thanks a lot! It works for me!
