### ISSUE TITLE
confirm_trade_exit() and multiple active sell reasons

### ISSUE THREAD

**Issue by dudel** [freqtrade/freqtrade#5020]
When using confirm_trade_exit to cancel selling (e.g. because something indicates that the price will go up) only one sell reason is provided via the result of should_sell():

https://github.com/freqtrade/freqtrade/blob/df0928c8b54b83624e2ac90e77f1de117022b11f/freqtrade/strategy/interface.py#L601-L610

That snippet shows that ROI 'trumps' other reasons like sell signal or trailing stop loss and thus when minimal ROI is reached confirm_trade_exit() is always called with reason ROI irrespective of other sell reasons that are true at the same time. It seems that, looking at the code, also custom_sell is trumped by ROI. 

So what happens is if you customize your confirm_trade_exit() to reject a trade exit in case the sell reason is ROI the trailing stop is effectively disabled as long as sell reason ROI is active which may not be desired. Thus, it seems that there is no way to be able to distinguish within conform_trade_exit() between 'only ROI reached' and 'ROI + trailing stop/sell signal reached'.

Having access to all the sell reasons that occur at a point in time is in my opinion desirable because this allows strategies to not sell at minimal ROI when those strategies detect some up trend but still be able to take profit in case the trailing stop loss is hit. 

Although I am not very familiar with the code would it not be possible to enhance should_sell and confirm_trade_exit by:
- returning a list of all sell reasons from should_sell (e.g. in the order of the priority as it is currently) and
  - supplying all sell reasons to confirm_trade_exit(). (This could be problematic as we would not know which sell_reason actually was rejected and which was not unless returning an actual sell reason instead of a boolean from confirm_trade_exit().
  - or calling confirm_trade_exit() for each sell reason until either all return True or until the first returns False. This would also to allow to return the first sell reason that is confirmed as the sell reason seen by the user.

As a byproduct of the aforementioned change this would even allow advanced checks to e.g. skip trailing stop loss in case 3 indicators are positive but not skipping it when only 1 indicator is positive. 

Edit: I guess another way would be to enhance the clause in line 608 with a check for SellType.TRAILING_STOP_LOSS but this would basically only move the execution order around without providing the complete picture in confirm_trade_exit().

**Comment by rokups** [comment]
As a workaround you could add this:
```py
if rate < trade.stop_loss:
    return True
```
It will allow roi sells when price falls below stoploss.

**Comment by dudel** [comment]
> 
> 
> As a workaround you could add this:
> 
> ```python
> if rate < trade.stop_loss:
>     return True
> ```
> 
> It will allow roi sells when price falls below stoploss.

That's actually nice for trailing stop, but I guess for sell signals it is not as simple?

**Comment by rokups** [comment]
It will only work for stoploss.

**Comment by xmatthias** [comment]
This is now possible with #6870 - so the confirm_trade_exit callback is now called for every applicable exit reason (until the first reason is not rejected).
