### ISSUE TITLE
Acumulative max open trade [Feature]

### ISSUE THREAD

**Issue by Cazs03** [freqtrade/freqtrade#5021]
Can you implement a function to increase max Open trades, based on the cumulative profit?

**Comment by Hsgngr** [comment]
Do you mean dynamic stake amount ?  in other words The amount per stake increases with the available money ? Then you can do that by  changing the stake-amount as "unlimited".

 If you mean increasing the maximum trades when there is avaliable money by keeping the stake amount same you can just give a high number of max-open-trades. When there is available money the bot will use that trade slot to buy a new stake.

**Comment by Cazs03** [comment]
That is my idea that the max_open_trades parameter goes in increment as a function of the cumulative profit.
By having a limit and using a regular expression, you can lose buying opportunities with other pairs since you have a full queue.
For example, I use all available pairs for BTC with the expression `"pair_whitelist": [". * / BTC"].`
The fact is that when you have more BTC you can fill even more shitcoins.

**Comment by Cazs03** [comment]
The amount of money available would be maintained dynamically, in my case I use the parameter:
`  "stake_currency": "BTC",
  "stake_amount": "unlimited",`

**Comment by xmatthias** [comment]
You have to pick - either you have a dynamic stake amount (`"stake_amount": "unlimited"`) - or dynamix max-open trades (`"max_open_trades": -1`).

having both is not possible (freqtrade needs to roughly know what you need).

By using unlimited (or very high) max_open_trades with a static stake-amount, you can however archive that - once a new stake becomes "available" - your (implicit) max_open_trades will be raised by 1 stake.

**Comment by Cazs03** [comment]
I had thought of some parameter as `dynamicOpentrade = true`, using a formula similar to this:
If you have specified   `"max_open_trades": 15`, and each open trade has a value of $ 10.
When you get a cumulative profit of 10$ the maxOpenTrades virtually, increases to 16.
Even though in the configuration it is still marked 15

If you used the formula -1, it could happen that it did not open the position due to the warning stake to small

**Comment by xmatthias** [comment]
i don't think you'll get what you'll expect.

Let's assume a 20$ stake (10$ is too low for most exchanges) and a starting wallet of 100$ (so 5 open trades in total to start with).
the moment you have 20$ profits - you'll get 6 open trades with a stake of 20$.

Having both dynamic (both `max_open_trades` + `stake-amount` will have you lack an initial starting point (who / how would you determine that it's 20$ and 5 open trades) ... therefore that's not possible.

**Comment by Cazs03** [comment]
And what do you think of?  The limit of open positions could be established in the database, depending on the extra parameter is enabled or not, so that in case of any problem ej. Crash, you can obtain the value of open positions.  This in turn would allow the increase in CPU usage to be progressive.  Would not solve el who/how ?

**Comment by xmatthias** [comment]
it's not about storing that information or not (currently open positions are available at any time).

one of the 2 information (max-open-trades OR stake-amount) must be static - otherwise it's impossible to determine how much should be used as stake amount.
