### ISSUE TITLE
Setting pair whitelist in strategy class

### ISSUE THREAD

**Issue by berlin-29** [freqtrade/freqtrade#5022]
## Describe the enhancement

As of right now, I seem to be able to set the tradable pairs in the config JSON file. However, it would definitely be wonderful to also set the pairs inside a strategy class. 
For instance, I've programmed another method that returns the best-performing crypto pairs from Binance in the last 24h. 
I would like to take these cryptos and use only these ones for my buy signals.

**Comment by xmatthias** [comment]
you can provide this as a [Pairlist plugin/handler](https://www.freqtrade.io/en/latest/plugins/#available-pairlist-handlers) ([developer docs for pairlists](https://www.freqtrade.io/en/latest/developer/#pairlists)).

While having the configuration for pairlists come from the strategy (optionally) might be an option (similar to a ton of other settings) - it's not what you'd want - as this would simply be a replacement for the "pairlists" key in the configuration - but defined in the strategy.

Having the strategy define the pairlist is problematic to some degree - as it would be unclear if this pairlist would "overwrite" what the pairlists calculated - or should append to that list - or should be the base for the comming filters.
Also, how often should the strategy method be called to provide a new / switched list ... 

As such - i don't see us adding this at the moment, as it would cause a lot of confusion with very little benefit (over writing a Pairlist - which has a rather clear interface).

However, this might be added as (optional) part of #4493 ... but not so sure about that yet.
