### ISSUE TITLE
fees in database during dry run

### ISSUE THREAD

**Issue by thieme** [freqtrade/freqtrade#5023]
Hi,

I just realized that the fees during the dry run are not reported correctly. Since it writes a open/close fee of 0.001 for binance but calculates the profit_ratio with 0.002

e.g. I have 

close_rate= 2121,23
amount= 0,01256

the tool calculates a profit ratio of 0,0747111266750577 with a fee of 0.001 you will get 0,07578799. Do I miss something?

In addition to that I would like to ask if it is possible to use early stopping during the training?

Thanks for this nice framework.

Best,
Sebastian

**Comment by dudel** [comment]
You pay the fee on both buy and sell.

Regarding the stopping you can use CTRL-c, at least under linux and wsl.

**Comment by thieme** [comment]
Thx for the fast answer. 

With respect to early stopping I mean an algorithm which cancel the training if the loss is not decreasing significantly over the last x epochs. This would allow longer training runs e.g. 1k epochs without wasting time, because the model is jumping arround in a local minima.

**Comment by xmatthias** [comment]
while it might be a possibility - it'll heavily depend on the space if it makes sense or not (and in many cases, won't make sense).

Assuming a "rather normal" space with a few numerical parameters, and one Category "picking" an indicator.

The hyperopt can run within a local minima for quite some epochs (only changing the numerical values) - and then changes the categorical value, and suddenly it's in a completely different "valley" - trying to find the minima there.

I've seen hyperopts not change the loss for 100ds of epochs significantly, only to then suddenly have a breakthrough and begin getting better results (with a jump at the beginning).

I don't think early stopping is well suited for Baesian optimization (which is what hyperopt uses) - not if you have non-numerical / categorical spaces which can drastically change the result from one epoch to the next.

**Comment by thieme** [comment]
ah cool. thats quite interesting. Thanks for clarifying.

One more question. 
in optimize_reports you calculate total profit using profit_abs:

profit_total = result['profit_abs'].sum() / starting_balance

however in generate_sell_reason_stats you calculate it by using profit_ratio:

profit_sum = result['profit_ratio'].sum()
profit_total = profit_sum / max_open_trades

is there a reason for the different calculations for total profit %

Thx a lot.

Best,
Sebastian
