### ISSUE TITLE
Creat different buy signal for each pair in strategy class

### ISSUE THREAD

**Issue by metin02oktay** [freqtrade/freqtrade#5024]
## Describe your environment

  * Operating system: ____ Docker
  * Python Version: _____ 3.9.5
  * CCXT version: _____ 1.48.76
  * Freqtrade Version: ____ 2021.4
  
## Your question
Does such an if-condition in strategy class make sense?

       
        def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Based on TA indicators, populates the buy signal for the given dataframe
            :param dataframe: DataFrame populated with indicators
            :param metadata: Additional information, like the currently traded pair
            :return: DataFrame with buy column
            """
            if metadata["pair"]=="ETH/USDT":
                dataframe.loc[
                    (
                        # Signal: RSI crosses above 29
                        (qtpylib.crossed_above(dataframe['rsi'], self.buy_rsi.value)) &
                        (dataframe['tema'] <= dataframe['bb_middleband']) &  # Guard: tema below BB middle
                        (dataframe['tema'] > dataframe['tema'].shift(1)) &  # Guard: tema is raising
                        (dataframe['volume'] > 0)  # Make sure Volume is not 0
                    ),
                    'buy'] = 1
            
            if metadata["pair"]=="BTC/USDT":
                dataframe.loc[
                    (
                        # Signal: RSI crosses above 30
                        (qtpylib.crossed_above(dataframe['rsi'], self.buy_rsi.value)) &
                        (dataframe['tema'] <= dataframe['bb_middleband']) &  # Guard: tema below BB middle
                        (dataframe['tema'] > dataframe['tema'].shift(1)) &  # Guard: tema is raising
                        (dataframe['volume'] > 0)  # Make sure Volume is not 0
                    ),
                    'buy'] = 1
            if metadata["pair"]=="LTC/USDT":
                dataframe.loc[
                    (
                        # Signal: RSI crosses above 31
                        (qtpylib.crossed_above(dataframe['rsi'], self.buy_rsi.value)) &
                        (dataframe['tema'] <= dataframe['bb_middleband']) &  # Guard: tema below BB middle
                        (dataframe['tema'] > dataframe['tema'].shift(1)) &  # Guard: tema is raising
                        (dataframe['volume'] > 0)  # Make sure Volume is not 0
                    ),
                    'buy'] = 1

            return dataframe

This is exactly what I want to do:

Creating a different buy signal for each trading pair. The rsi value and macd values for "BTC / USDT" are very different from "ETH / USDT" or "LTC / USDT".

**Comment by xmatthias** [comment]
It's valid code (at least it seems to be - at first glance).

Now personally, i'd consolidate / refactor this a bit (extract common lines, ...).

you'll also want to use different values (now it's only a comment - `buy_rsi` will always have the same value).

---

If it makes sense is a different topic and will be highly opinionated.
While the values might be different - i suspect this will lead to overfitted strategies (fitted to the historic data too much) - so it's possible that it won't perform at all / won't perform well on future data, simply because the behaviour changed ever so slightly.

As mentioned above - this is my opinion - as we're talking about "how the future will be" - there's no 100% correct answer to this (at least not at this point in time...)

**Comment by metin02oktay** [comment]
Actually the strategy that I use is a little same from the one written below :)

```
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
            if metadata["pair"]=="ETH/USDT":
                dataframe.loc[
                (
                    (dataframe['macd'] <= -15) |
                    (
                    dataframe['macd'] > dataframe['macd'].shift(1) > dataframe['macd'].shift(2) #macd raising 
                    )
                    
                ),
                'buy'] = 1
            
            if metadata["pair"]=="BTC/USDT":
                dataframe.loc[
                (
                    (dataframe['macd'] <= -30) |
                    (
                    dataframe['macd'] > dataframe['macd'].shift(1) > dataframe['macd'].shift(2)
                    )
                    
                    
                ),
                'buy'] = 1
            if metadata["pair"]=="LTC/USDT":
                dataframe.loc[
                (
                    (dataframe['macd'] <= -0.4) |
                    (
                    dataframe['macd'] > dataframe['macd'].shift(1) > dataframe['macd'].shift(2)
                    )
                    
                ),
                'buy'] = 1


            return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
            if metadata["pair"]=="ETH/USDT":
                dataframe.loc[
                (
                    (dataframe['macd'] >= 15) |
                    (
                    dataframe['macd'] < dataframe['macd'].shift(1) < dataframe['macd'].shift(2) #macd falling
                    )
                    
                ),
                'sell'] = 1
            
            if metadata["pair"]=="BTC/USDT":
                dataframe.loc[
                (
                    (dataframe['macd'] >= 30) |
                    (
                    dataframe['macd'] < dataframe['macd'].shift(1) < dataframe['macd'].shift(2)
                    )
                    
                    
                ),
                'sell'] = 1
            if metadata["pair"]=="LTC/USDT":
                dataframe.loc[
                (
                    
                    (dataframe['macd'] >= 0.7) |
                    (
                    dataframe['macd'] < dataframe['macd'].shift(1) < dataframe['macd'].shift(2)
                    )
                    
                ),
                'sell'] = 1


            return dataframe
```

**Comment by metin02oktay** [comment]
By the way thank you @xmatthias. For your interest and answer...
