### ISSUE TITLE
Unable to run the docker file (wrong architecture)

### ISSUE THREAD

**Issue by Nullifii** [freqtrade/freqtrade#5026]
## Describe your environment

  * Operating system: Raspian (32-Bit)
  * Python Version: Python 2.7.16 & Python 3.7.3 
  * CCXT version: No output 
  * Freqtrade Version: freqtrade develop-8e89d3e6 
  
## Your question

Device is a Raspberry Pi 3b+

pi@raspberrypi:~/freqtrade $ sudo docker run --rm -v `pwd`/config.json:/freqtrade/config.json -it freqtradeorg/freqtrade:develop

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

standard_init_linux.go:219: exec user process caused: exec format error

**Comment by xmatthias** [comment]
We don't support / document running with docker (without compose) any longer.

The [docker installation documentation](https://www.freqtrade.io/en/stable/docker_quickstart/) has got the instructions on how to get running on a raspberry.

so by following the [docker install documentation](https://www.freqtrade.io/en/stable/docker_quickstart/) from top to bottom, you will discover that you are running the wrong image - and what to do to fix it.
