### ISSUE TITLE
Several Pairs are "locked", even though there are no live trades in the DB

### ISSUE THREAD

**Issue by rrrohit** [freqtrade/freqtrade#5029]
## Describe your environment

  * Operating system: Windows 10 pro with Ubuntu 20.04.2 LTS installed via Oracle VM Virtual Box Manager
  * Python Version: 3.8.5 (`python -V`)
  * CCXT version: 1.34.59 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop-d2111c08(`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
I am getting a large number of "Pair is currently locked" messages. I am trying to understand why this is so. Below are 
a) dump of log messages from screen
b) status table at the time that shows several of these are not in trade at the moment
c) mysql dump for the first 4 showing that there is no active trade for either of these in DB

What am I missing?

Thanks for your help!

**a) dump of log messages from screen**
021-05-26 17:07:18,722 - freqtrade.freqtradebot - INFO - Pair COTI/USDT is currently locked.
2021-05-26 17:07:18,739 - freqtrade.freqtradebot - INFO - Pair AKRO/USDT is currently locked.
2021-05-26 17:07:19,031 - freqtrade.wallets - INFO - Wallets synced.
2021-05-26 17:07:19,033 - freqtrade.freqtradebot - WARNING - Unable to create trade for ADAUP/USDT: Available balance (380.1632557460998 USDT) is lower than stake amount (400 USDT)
2021-05-26 17:07:19,303 - freqtrade.wallets - INFO - Wallets synced.
2021-05-26 17:07:19,304 - freqtrade.freqtradebot - WARNING - Unable to create trade for THETA/USDT: Available balance (380.1632557460998 USDT) is lower than stake amount (400 USDT)
2021-05-26 17:07:19,305 - freqtrade.freqtradebot - INFO - Pair YFII/USDT is currently locked.
2021-05-26 17:07:19,310 - freqtrade.freqtradebot - INFO - Pair SFP/USDT is currently locked.
2021-05-26 17:07:34,721 - freqtrade.wallets - INFO - Wallets synced.
2021-05-26 17:07:34,727 - freqtrade.freqtradebot - WARNING - Unable to create trade for ADAUP/USDT: Available balance (380.1632557460998 USDT) is lower than stake amount (400 USDT)
2021-05-26 17:07:34,799 - freqtrade.freqtradebot - INFO - Pair LTC/USDT is currently locked.
2021-05-26 17:07:34,891 - freqtrade.freqtradebot - INFO - Pair YFII/USDT is currently locked.
2021-05-26 17:07:35,146 - freqtrade.freqtradebot - INFO - Pair BNB/USDT is currently locked.
2021-05-26 17:07:35,587 - freqtrade.wallets - INFO - Wallets synced.
2021-05-26 17:07:35,606 - freqtrade.freqtradebot - WARNING - Unable to create trade for THETA/USDT: Available balance (380.1632557460998 USDT) is lower than stake amount (400 USDT)
2021-05-26 17:07:35,767 - freqtrade.freqtradebot - INFO - Pair ICX/USDT is currently locked.
2021-05-26 17:07:36,014 - freqtrade.wallets - INFO - Wallets synced.
2021-05-26 17:07:36,020 - freqtrade.freqtradebot - WARNING - Unable to create trade for BNBUP/USDT: Available balance (380.1632557460998 USDT) is lower than stake amount (400 USDT)
2021-05-26 17:07:36,373 - freqtrade.wallets - INFO - Wallets synced.
2021-05-26 17:07:36,377 - freqtrade.freqtradebot - WARNING - Unable to create trade for RAMP/USDT: Available balance (380.1632557460998 USDT) is lower than stake amount (400 USDT)
2021-05-26 17:07:36,493 - freqtrade.freqtradebot - INFO - Pair SOL/USDT is currently locked.
2021-05-26 17:07:36,493 - freqtrade.freqtradebot - INFO - Pair COTI/USDT is currently locked.
2021-05-26 17:07:36,498 - freqtrade.freqtradebot - INFO - Pair FET/USDT is currently locked.
2021-05-26 17:07:36,886 - freqtrade.wallets - INFO - Wallets synced.
2021-05-26 17:07:36,891 - freqtrade.freqtradebot - WARNING - Unable to create trade for 1INCH/USDT: Available balance (380.1632557460998 USDT) is lower than stake amount (400 USDT)
2021-05-26 17:07:36,892 - freqtrade.freqtradebot - INFO - Pair RSR/USDT is currently locked.
2021-05-26 17:07:36,981 - freqtrade.freqtradebot - INFO - Pair ALPHA/USDT is currently locked.
2021-05-26 17:07:37,397 - freqtrade.wallets - INFO - Wallets synced.
2021-05-26 17:07:37,398 - freqtrade.freqtradebot - WARNING - Unable to create trade for BLZ/USDT: Available balance (380.1632557460998 USDT) is lower than stake amount (400 USDT)
2021-05-26 17:07:37,507 - freqtrade.freqtradebot - INFO - Pair SFP/USDT is currently locked.
2021-05-26 17:07:37,778 - freqtrade.freqtradebot - INFO - Pair EGLD/USDT is currently locked.
2021-05-26 17:07:38,043 - freqtrade.freqtradebot - INFO - Pair AKRO/USDT is currently locked.

b) Status table
**1262  DGB/USDT    2 h      4.56% (18.25)
1272  CTSI/USDT   2 h      0.35% (1.40)
1276  FTT/USDT    2 h      -0.67% (-2.70)
1277  TRX/USDT    2 h      -0.89% (-3.57)
1285  COMP/USDT   2 h      2.16% (8.65)
1290  NANO/USDT   2 h      3.10% (12.42)
1292  LSK/USDT    2 h      1.12% (4.48)
1306  ADA/USDT    1 h      1.25% (5.02)
1308  EOS/USDT    1 h      0.82% (3.27)
1310  BTC/USDT    1 h      0.13% (0.53)
1313  DODO/USDT   1 h      5.58% (22.35)
1314  VET/USDT    1 h      2.65% (10.62)
1316  PAXG/USDT   1 h      -0.23% (-0.91)
1317  XLM/USDT    1 h      0.89% (3.58)
1318  TKO/USDT    1 h      -0.36% (-1.43)
1319  ENJ/USDT    1 h      3.11% (12.43)
1321  DASH/USDT   1 h      1.50% (5.99)
1325  TRB/USDT    37 min   2.77% (11.09)
1326  VTHO/USDT   35 min   -0.42% (-1.66)
1327  STRAX/USDT  35 min   1.60% (6.41)
1328  SRM/USDT    35 min   1.57% (6.30)
1329  ZIL/USDT    35 min   0.99% (3.96)
1330  BAND/USDT   35 min   1.94% (7.79)
1331  EOSUP/USDT  35 min   1.60% (6.40)
1332  REEF/USDT   35 min   3.09% (12.36)
1333  ATOM/USDT   35 min   2.32% (9.29)
1334  CELR/USDT   30 min   4.66% (18.64)
1335  NEO/USDT    30 min   1.36% (5.43)
1336  FTM/USDT    26 min   1.96% (7.84)**

Performance - not able to get a dump of performance from the telegram bot since the number of trades are now in the 1000s

c) mysql dump for the first 4 showing that there is no active trade for either of these in DB
COTI/USDT
sqlite> SELECT * from trades where pair="COTI/USDT";
82|binance|COTI/USDT|0|0.001|0.399994505|USDT|0.001|0.397342232|USDT|0.17645|0.17645|400.394499505|0.17528|0.17528|-0.00861553|-3.44960974|399.994505|2266.9|2266.9|2021-05-24 03:46:00.799009|2021-05-24 04:01:27.879501||0.1734894|-0.02|0.172921|-0.02|dry_run_sell_1621828060.937238|2021-05-24 03:46:39.347917|0.17703|0.17394|sell_signal|closed|HMStrategy|60
99|binance|COTI/USDT|0|0.001|0.399994392|USDT|0.001|0.39491752272|USDT|0.17702|0.17702|400.394386392|0.1747732|0.1747732|-0.01466499|-5.87178119|399.994392|2259.6|2259.6|2021-05-24 06:01:21.249655|2021-05-24 06:09:38.799417||0.1747732|-0.02|0.1734796|-0.02|dry_run_sell_1621836386.364444|2021-05-24 06:05:20.578794|0.17834|0.17446|trailing_stop_loss|closed|HMStrategy|60
137|binance|COTI/USDT|0|0.001|0.3999909|USDT|0.001|0.4239011854|USDT|0.1893|0.1893|400.3908909|0.2006158|0.2006158|0.05765964|23.08639331|399.9909|2113.0|2113.0|2021-05-24 07:16:03.695821|2021-05-24 07:47:58.504777||0.2006158|-0.02|0.185514|-0.02|dry_run_sell_1621842391.511425|2021-05-24 07:45:20.645973|0.20471|0.1893|trailing_stop_loss|closed|HMStrategy|60
289|binance|COTI/USDT|0|0.001|0.39999675|USDT|0.001|0.40779577524|USDT|0.1975|0.1975|400.39674675|0.2013508|0.2013508|0.01746076|6.99123271|399.99675|2025.3|2025.3|2021-05-24 12:01:24.319319|2021-05-24 13:51:11.456098||0.2013508|-0.02|0.19355|-0.02|dry_run_sell_1621863219.068054|2021-05-24 13:32:35.137902|0.20546|0.19749|trailing_stop_loss|closed|HMStrategy|60
597|binance|COTI/USDT|0|0.001|0.399987764|USDT|0.001|0.41120072056|USDT|0.20933|0.20933|400.387751764|0.2151982|0.2151982|0.02597924|10.40176808|399.987764|1910.8|1910.8|2021-05-24 21:01:43.262149|2021-05-24 21:41:31.008651||0.2151982|-0.02|0.2051434|-0.02|dry_run_sell_1621892256.639172|2021-05-24 21:36:18.193633|0.21959|0.20931|trailing_stop_loss|closed|HMStrategy|60
668|binance|COTI/USDT|0|0.001|0.399990556|USDT|0.001|0.39349547216|USDT|0.21101|0.21101|400.390546556|0.2075836|0.2075836|-0.01820365|-7.28856987|399.990556|1895.6|1895.6|2021-05-24 22:35:39.169366|2021-05-24 22:42:24.778408||0.2075836|-0.02|0.2067898|-0.02|dry_run_sell_1621895826.280583|2021-05-24 22:35:55.741868|0.21182|0.20742|trailing_stop_loss|closed|HMStrategy|60
722|binance|COTI/USDT|0|0.001|0.399985408|USDT|0.001|0.39541140352|USDT|0.22084|0.22084|400.385393408|0.2183146|0.2183146|-0.01341058|-5.36940129|399.985408|1811.2|1811.2|2021-05-25 00:28:25.917426|2021-05-25 00:46:18.922623||0.2183146|-0.02|0.2164232|-0.02|dry_run_sell_1621902657.018791|2021-05-25 00:29:52.487118|0.22277|0.21812|trailing_stop_loss|closed|HMStrategy|60
775|binance|COTI/USDT|0|0.001|0.399994333|USDT|0.001|0.40183959886|USDT|0.21421|0.21421|400.394327333|0.2151982|0.2151982|0.00260601|1.04343193|399.994333|1867.3|1867.3|2021-05-25 01:11:39.351098|2021-05-25 01:28:00.496831||0.2151982|-0.02|0.2099258|-0.02|dry_run_sell_1621905624.252194|2021-05-25 01:19:06.561963|0.21959|0.21421|trailing_stop_loss|closed|HMStrategy|60
940|binance|COTI/USDT|0|0.001|0.39998083|USDT|0.001|0.39674728464|USDT|0.2089|0.2089|400.38081083|0.2072112|0.2072112|-0.0100661|-4.03027347|399.98083|1914.7|1914.7|2021-05-25 17:01:22.206748|2021-05-25 17:17:44.065146||0.2072112|-0.02|0.204722|-0.02|dry_run_sell_1621962654.681584|2021-05-25 17:09:36.183257|0.21144|0.20664|trailing_stop_loss|closed|HMStrategy|60
981|binance|COTI/USDT|0|0.001|0.399991008|USDT|0.001|0.3959914812|USDT|0.20872|0.20872|400.390999008|0.206633|0.206633|-0.01197707|-4.79550929|399.991008|1916.4|1916.4|2021-05-25 18:01:37.164341|2021-05-25 19:04:15.587856||0.206633|-0.02|0.2045456|-0.02|dry_run_sell_1621968070.386237|2021-05-25 18:40:10.156699|0.21085|0.20643|trailing_stop_loss|closed|HMStrategy|60
1131|binance|COTI/USDT|0|0.001|0.399978891|USDT|0.001|0.44594946942|USDT|0.21411|0.21411|400.378869891|0.2387182|0.2387182|0.11270487|45.12465006|399.978891|1868.1|1868.1|2021-05-26 00:29:57.376868|2021-05-26 03:36:02.519251||0.2387182|-0.02|0.2098278|-0.02|dry_run_sell_1621999272.43702|2021-05-26 03:20:07.496538|0.24359|0.21411|trailing_stop_loss|closed|HMStrategy|60
1205|binance|COTI/USDT|0|0.001|0.39999494|USDT|0.001|0.39413100804|USDT|0.2606|0.2606|400.39493494|0.2567796|0.2567796|-0.01662873|-6.65805791|399.99494|1534.9|1534.9|2021-05-26 08:06:32.816882|2021-05-26 08:08:17.727028||0.2567796|-0.02|0.255388|-0.02|dry_run_sell_1622016477.955158|2021-05-26 08:06:53.661143|0.26202|0.25644|trailing_stop_loss|closed|HMStrategy|60
1307|binance|COTI/USDT|**0**|0.001|0.399993303|USDT|0.001|0.40203534112|USDT|0.26193|0.26193|400.393296303|0.2632672|0.2632672|0.00309698|1.24000948|399.993303|1527.1|1527.1|2021-05-26 10:28:28.364700|2021-05-26 11:01:38.993549||0.2632672|-0.02|0.2566914|-0.02|dry_run_sell_1622026149.384319|2021-05-26 10:48:01.637024|0.26864|0.26086|trailing_stop_loss|closed|HMStrategy|60
**NOTE: highlighted 0 indicates, it is not an active trade at the moment**

AKRO
sqlite> SELECT * from trades where pair="AKRO/USDT";
461|binance|AKRO/USDT|0|0.001|0.4|USDT|0.001|0.396428187197418|USDT|0.022308|0.022308|400.4|0.0221088|0.0221088|-0.01090969|-4.36824099|400.0|17930.7871615564|17930.7871615564|2021-05-24 16:18:56.434453|2021-05-24 16:23:38.259355||0.0221088|-0.02|0.02186184|-0.02|dry_run_sell_1621873368.186767|2021-05-24 16:21:46.864530|0.02256|0.022072|trailing_stop_loss|closed|HMStrategy|60
988|binance|AKRO/USDT|0|0.001|0.4|USDT|0.001|0.394917577873748|USDT|0.021766|0.021766|400.4|0.02148944|0.02148944|-0.01467867|-5.8773397|400.0|18377.2856749058|18377.2856749058|2021-05-25 18:01:46.634555|2021-05-25 19:06:55.386002||0.02148944|-0.02|0.02133068|-0.02|dry_run_sell_1621967474.677328|2021-05-25 18:30:13.458304|0.021928|0.021488|trailing_stop_loss|closed|HMStrategy|60
1217|binance|AKRO/USDT|0|0.001|0.4|USDT|0.001|0.392|USDT|0.0253|0.0253|400.4|0.024794|0.024794|-0.02195804|-8.792|400.0|15810.2766798419|15810.2766798419|2021-05-26 08:08:24.677157|2021-05-26 08:12:36.307213||0.024794|-0.02|0.024794|-0.02|dry_run_sell_1622016532.768894|2021-05-26 08:08:52.987027|0.0253|0.024663|stop_loss|closed|HMStrategy|60
1296|binance|AKRO/USDT|**0**|0.001|0.4|USDT|0.001|0.403451860696517|USDT|0.025125|0.025125|400.4|0.02534182|0.02534182|0.00661441|2.64840884|400.0|15920.3980099502|15920.3980099502|2021-05-26 10:09:16.151163|2021-05-26 11:03:09.611394||0.02534182|-0.02|0.0246225|-0.02|dry_run_sell_1622026614.915053|2021-05-26 10:55:49.880118|0.025859|0.025125|trailing_stop_loss|closed|HMStrategy|60
**NOTE: highlighted 0 indicates, it is not an active trade at the moment**

FYII
sqlite> SELECT * from trades where pair="YFII/USDT";
44|binance|YFII/USDT|0|0.001|0.39999886962|USDT|0.001|0.411068672077|USDT|1795.98|1795.98|400.39886848962|1845.683|1845.683|0.02562129|10.25873492|399.99886962|0.222719|0.222719|2021-05-22 21:01:21.362735|2021-05-22 22:09:18.239772||1845.683|-0.02|1760.0604|-0.02|dry_run_sell_1621720952.830437|2021-05-22 22:01:29.511709|1883.35|1792.54|trailing_stop_loss|closed|HMStrategy|60
153|binance|YFII/USDT|0|0.001|0.39999995694|USDT|0.001|0.3988473864102|USDT|1726.02|1726.02|400.39995689694|1721.0466|1721.0466|-0.00487367|-1.95141787|399.99995694|0.231747|0.231747|2021-05-24 08:01:44.379047|2021-05-24 08:28:01.758640||1721.0466|-0.02|1691.4996|-0.02|dry_run_sell_1621844026.932133|2021-05-24 08:12:39.930829|1756.17|1711.76|trailing_stop_loss|closed|HMStrategy|60
245|binance|YFII/USDT|0|0.001|0.39999932046|USDT|0.001|0.40547446707|USDT|1670.82|1670.82|400.39931978046|1693.69|1693.69|0.01166254|4.66967282|399.99932046|0.239403|0.239403|2021-05-24 09:48:04.099289|2021-05-24 10:01:34.225536||1662.717|-0.02|1637.4036|-0.02|dry_run_sell_1621850148.02144|2021-05-24 09:54:41.931255|1696.65|1667.15|sell_signal|closed|HMStrategy|60
321|binance|YFII/USDT|0|0.001|0.39999879584|USDT|0.001|0.403942808416|USDT|1740.76|1740.76|400.39879463584|1757.924|1757.924|0.00784236|3.14007097|399.99879584|0.229784|0.229784|2021-05-24 13:20:01.748696|2021-05-24 13:53:42.659742||1757.924|-0.02|1705.9448|-0.02|dry_run_sell_1621863776.613499|2021-05-24 13:41:39.369249|1793.8|1740.76|trailing_stop_loss|closed|HMStrategy|60
434|binance|YFII/USDT|0|0.001|0.39999976695|USDT|0.001|0.394236658116|USDT|1813.77|1813.77|400.39976671695|1787.6376|1787.6376|-0.016377|-6.55734526|399.99976695|0.220535|0.220535|2021-05-24 16:02:15.244385|2021-05-24 16:04:45.492542||1787.6376|-0.02|1777.4946|-0.02|dry_run_sell_1621872242.170379|2021-05-24 16:02:41.866622|1824.12|1782.33|trailing_stop_loss|closed|HMStrategy|60
494|binance|YFII/USDT|0|0.001|0.39999983625|USDT|0.001|0.4126300635744|USDT|1838.75|1838.75|400.39983608625|1896.8096|1896.8096|0.02951449|11.81759742|399.99983625|0.217539|0.217539|2021-05-24 18:01:46.423508|2021-05-24 20:17:02.203938||1896.8096|-0.02|1801.975|-0.02|dry_run_sell_1621886125.735536|2021-05-24 19:54:21.490197|1935.52|1828.53|trailing_stop_loss|closed|HMStrategy|60
616|binance|YFII/USDT|0|0.001|0.3999992223|USDT|0.001|0.396180665|USDT|1870.86|1870.86|400.3992215223|1853.0|1853.0|-0.01152534|-4.61473719|399.9992223|0.213805|0.213805|2021-05-24 21:41:51.711739|2021-05-24 22:01:26.282634||1834.952|-0.02|1833.4428|-0.02|dry_run_sell_1621893012.568343|2021-05-24 21:49:08.137909|1872.4|1836.45|sell_signal|closed|HMStrategy|60
1115|binance|YFII/USDT|0|0.001|0.3999998034|USDT|0.001|0.4100974233888|USDT|1814.7|1814.7|400.3998032034|1860.5104|1860.5104|0.02319562|9.28752276|399.9998034|0.220422|0.220422|2021-05-26 00:22:06.436926|2021-05-26 04:09:53.997664||1860.5104|-0.02|1778.406|-0.02|dry_run_sell_1622001385.959709|2021-05-26 03:54:58.128546|1898.48|1793.5|trailing_stop_loss|closed|HMStrategy|60
1322|binance|YFII/USDT|**0**|0.001|0.39999961485|USDT|0.001|0.3978343908|USDT|1919.43|1919.43|400.39961446485|1909.04|1909.04|-0.00740025|-2.96305806|399.99961485|0.208395|0.208395|2021-05-26 10:39:14.994520|2021-05-26 11:08:21.410511||1909.04|-0.02|1881.0414|-0.02|dry_run_sell_1622026156.381818|2021-05-26 10:48:08.642319|1948.0|1908.23|trailing_stop_loss|closed|HMStrategy|60
**NOTE: highlighted 0 indicates, it is not an active trade at the moment**

SFP
sqlite> SELECT * from trades where pair="SFP/USDT";
217|binance|SFP/USDT|0|0.001|0.39999339|USDT|0.001|0.3951666789|USDT|0.9018|0.9018|400.39338339|0.890918|0.890918|-0.01404087|-5.62187117|399.99339|443.55|443.55|2021-05-24 09:11:46.892364|2021-05-24 09:47:51.458483||0.890918|-0.02|0.883764|-0.02|dry_run_sell_1621847972.691211|2021-05-24 09:18:26.089228|0.9091|0.8865|trailing_stop_loss|closed|HMStrategy|60
392|binance|SFP/USDT|0|0.001|0.39999062|USDT|0.001|0.3943761472|USDT|0.986|0.986|400.39061062|0.97216|0.97216|-0.01600647|-6.40883957|399.99062|405.67|405.67|2021-05-24 15:01:47.199392|2021-05-24 15:09:42.067313||0.97216|-0.02|0.96628|-0.02|dry_run_sell_1621868637.036445|2021-05-24 15:02:56.086605|0.992|0.9711|trailing_stop_loss|closed|HMStrategy|60
430|binance|SFP/USDT|0|0.001|0.399999324|USDT|0.001|0.39317686632|USDT|0.9987|0.9987|400.399323324|0.981666|0.981666|-0.0190201|-7.61563387|399.999324|400.52|400.52|2021-05-24 16:02:09.358203|2021-05-24 16:04:43.903009||0.981666|-0.02|0.978726|-0.02|dry_run_sell_1621872239.948587|2021-05-24 16:02:39.873521|1.0017|0.98|trailing_stop_loss|closed|HMStrategy|60
634|binance|SFP/USDT|0|0.001|0.399992053|USDT|0.001|0.401901044|USDT|1.0267|1.0267|400.392045053|1.0316|1.0316|0.00276503|1.1070979|399.992053|389.59|389.59|2021-05-24 21:45:34.955537|2021-05-24 22:01:33.660895||1.017926|-0.02|1.006166|-0.02|dry_run_sell_1621893021.101685|2021-05-24 21:49:16.642490|1.0387|1.0252|sell_signal|closed|HMStrategy|60
786|binance|SFP/USDT|0|0.001|0.39999668|USDT|0.001|0.3919967464|USDT|1.1035|1.1035|400.39667668|1.08143|1.08143|-0.02195804|-8.79192703|399.99668|362.48|362.48|2021-05-25 01:23:47.048385|2021-05-25 01:35:58.918143||1.08143|-0.02|1.08143|-0.02|dry_run_sell_1621905852.763953|2021-05-25 01:24:13.012159|1.1035|1.0812|stop_loss|closed|HMStrategy|60
1149|binance|SFP/USDT|0|0.001|0.3999921|USDT|0.001|0.40294197048|USDT|1.0525|1.0525|400.3920921|1.060262|1.060262|0.00536208|2.14693641|399.9921|380.04|380.04|2021-05-26 02:39:53.105791|2021-05-26 04:08:34.114831||1.060262|-0.02|1.03145|-0.02|dry_run_sell_1622001593.564164|2021-05-26 03:58:28.595226|1.0819|1.0433|trailing_stop_loss|closed|HMStrategy|60
1226|binance|SFP/USDT|0|0.001|0.399998427|USDT|0.001|0.40175846172|USDT|1.1527|1.1527|400.398425427|1.157772|1.157772|0.00239331|0.95827783|399.998427|347.01|347.01|2021-05-26 08:09:11.362639|2021-05-26 08:48:07.297406||1.157772|-0.02|1.129646|-0.02|dry_run_sell_1622018206.690291|2021-05-26 08:35:38.968799|1.1814|1.1346|trailing_stop_loss|closed|HMStrategy|60
1299|binance|SFP/USDT|**0**|0.001|0.399994224|USDT|0.001|0.4332712888|USDT|1.1472|1.1472|400.394218224|1.24264|1.24264|0.08102964|32.44379929|399.994224|348.67|348.67|2021-05-26 10:09:41.091181|2021-05-26 11:01:56.175325||1.24264|-0.02|1.124256|-0.02|dry_run_sell_1622026714.828026|2021-05-26 10:57:28.007652|1.268|1.1472|trailing_stop_loss|closed|HMStrategy|60
**NOTE: highlighted 0 indicates, it is not an active trade at the moment**

**Comment by xmatthias** [comment]
Your version is from september 2020 ... when there was only two types of locks - the automatic "until the end of the candle" lock, and the manual lock (added by the strategy explicitly).

Assuming you're not using the latter - then each pair will be locked until the end of the sell-candle to avoid rebuys mid-candle (that'd be a conflicting signal, and is basically never desired).

Having an open trade does not matter for this - but the close date of the last trade, which "auto-locks" the pair until the candle it's sold on competes.

So taking your latest sample - SFP - the sell seems to happen at 2021-05-26 11:01:56 UTC -  - which means on 1h candles, the pair is locked until 2021-05-26 12:00:00 UTC.

Not knowing your timezone / the log timezone it's difficult to correlate this with the logs - but i assume it'll be locked until the next candle starts, where the pair will be eligible again.

**Comment by rrrohit** [comment]
This makes sense and the logs validate your explanation completely after accounting for 5.5hrs time difference between UTC and IST (India Standard Time). I had been racking my brain on this and trying to debug from logs and installing debuggers! Thanks @xmatthias - appreciate your help and quick resolution!
