### ISSUE TITLE
Standard_init_linux.go:219: exec user process caused: exec format error

### ISSUE THREAD

**Issue by videogamingeducation** [freqtrade/freqtrade#5033]
## Describe your environment

  * Operating system: Ubuntu Server 20.04.2 LTS
  * Python Version: Python 3.8.5
  * CCXT version: None yet
  * Freqtrade Version: None yet
  
I am trying to install freqtrade using the docker installation instructions as described in https://www.freqtrade.io/en/latest/docker_quickstart/ but when I get to the part that I execute docker compose, I encountered this:

ubuntu@ubuntu:~/ft_userdata$ docker-compose run --rm freqtrade create-userdir --userdir user_data
standard_init_linux.go:219: exec user process caused: exec format error
ubuntu@ubuntu:~/ft_userdata$

I apologize in advance if the question has been answered before but I am new to this so please bear with me. Thank you.

**Comment by xmatthias** [comment]
the error you get - `exec user process caused: exec format error` - is usually caused by an architecture mismatch (you're running a x86 image on an arm machine or viceversa).

Assuming it's a "Normal" ubuntu server (not ARM or such) - make sure you're not using the _pi  version of the images ...

**Comment by videogamingeducation** [comment]
I see. I am using this on Raspberry Pi 4B with 8GB of RAM.

**Comment by xmatthias** [comment]
Then please use the "raspberry" instruction (tab in the setup guide) - which tells you to change the docker-compose file from `stable` to `stable_pi` or `develop` to `develop_pi`.

**Comment by videogamingeducation** [comment]
Ok I'll do that and give you update thanks

**Comment by videogamingeducation** [comment]
So I followed the instructions mentioned in the tab for Raspberry Pi 4 and when I ran the docker-compose build command this is what I get:

ubuntu@ubuntu:~/freqtrade/freqtrade$ docker-compose build
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
ubuntu@ubuntu:~/freqtrade/freqtrade$

**Comment by xmatthias** [comment]
this sounds like your docker daemon is not running.

The instruction assumes that you've got docker (and docker-compose) setup and running.
You can try with `docker info` - and i assume it'll give you a similar response - which will mean that either docker is not started - or not even installed. 
In both cases, please use google to research how to setup docker correctly.

**Comment by xmatthias** [comment]
I'll assume you managed to get it working based on the instructions above.

Feel free to comment / reopen if that's not the case.
