### ISSUE TITLE
file `freqtrade_commit` is missing from docker image created from develop branch?

### ISSUE THREAD

**Issue by kamontat** [freqtrade/freqtrade#5036]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
No? 
what makes you think this? 

We'll need a little more details on what you do / what you're trying to do that makes you think the commit-file is missing.

**Comment by kamontat** [comment]
![CleanShot 2021-05-29 at 00 13 10](https://user-images.githubusercontent.com/14089557/120019612-ddea5b80-c012-11eb-8b5f-59e4810d6cea.png)

My running freqtrade return version only `develop`. But I just pull latest develop_plot and this file is appeared.

**Comment by kamontat** [comment]
My running freqtrade shown only `develop` as a version, but just now I pull latest from `develop_plot` file is appear again.

![CleanShot 2021-05-29 at 00 15 59](https://user-images.githubusercontent.com/14089557/120019933-40dbf280-c013-11eb-936f-b2f8dae3fd64.png)

**Comment by xmatthias** [comment]
The file is added only in CI, so if you custom-build your image, it will not appear.

that's intentional and desired as is. I'm also not aware that there was a "hickup" in Ci that caused this - but who knows...

Either way, i'll consider this as closed then.
