### ISSUE TITLE
Bundle multiple bots & use one database

### ISSUE THREAD

**Issue by x3-dev** [freqtrade/freqtrade#5038]
## Describe your environment

  * Operating system: UBUNTU
  * Python Version: 3.8.5
  * CCXT version: latest
  * Freqtrade Version: latest develop
  
## Your question

I was searching for the possibility to store trades/manage multiple bots in one database.
I think reuse "bot_name" from config to make unique bot id in database table "trades" to point the db queries to right records.
Just need a hint where all queries are to be modified.

Thanks

**Comment by cryptomeisternox** [comment]
You might want to build yourself something there is this script `rest_client.py` that returns json data. You could do little customization to put Json into a database and use this with a simple cron job which runs the script https://github.com/freqtrade/freqtrade/blob/develop/scripts/rest_client.py (need some customization) for all your slave job. Then transfers the data to the new master bot database every one minute. 
You will run the master job with `https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/DoesNothingStrategy.py`.

**Comment by x3-dev** [comment]
> You might want to build yourself something there is this script `rest_client.py` that returns json data. You could do little customization to put Json into a database and use this with a simple cron job which runs the script https://github.com/freqtrade/freqtrade/blob/develop/scripts/rest_client.py (need some customization) for all your slave job. Then transfers the data to the new master bot database every one minute.
> You will run the master job with `https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/DoesNothingStrategy.py`.

Thanks you @cryptomeisternox 

what i was thinking is a new feature with a little afford like:
- deploy a database, it could be surely a PostgreSQL or MySQL since freqtrade is using lib sqlalchemy
- run multiple bots against this database using same tables for all the stuff (trades, orders, locks)
 
What do you think guy's?

Just discovered new add in documentation about using postgresql and mysql with diffrent user or scheme
I think if it is going to be scheme option then it must be declared like declarative_base(metadata=MetaData(schema="MySuperBotName"))

**Comment by xmatthias** [comment]
I don't see any benefit to using the same database for multiple bots - other than making the code / queries more complex, therefore increase the maintenance burden and potentially slow down query performance).

For sqlite, there's definitely no (positive) benefit - and for postgres, you can simply use a different user in the same database (with a different login schema) - in postgres done with `create schema <schemaname> authorization <username>;`.

The schema / database can usually also be provided via the connect string - best search the sqlalchemy docs for this).

The data will not be stored in the same tables - but why would you want to do this anyway?
it will only complicate your life should you ever want to query something directly from the database.

**Comment by x3-dev** [comment]
> I don't see any benefit to using the same database for multiple bots - other than making the code / queries more complex, therefore increase the maintenance burden and potentially slow down query performance).
> 
> For sqlite, there's definitely no (positive) benefit - and for postgres, you can simply use a different user in the same database (with a different login schema) - in postgres done with `create schema <schemaname> authorization <username>;`.
> 
> The schema / database can usually also be provided via the connect string - best search the sqlalchemy docs for this).
> 
> The data will not be stored in the same tables - but why would you want to do this anyway?
> it will only complicate your life should you ever want to query something directly from the database.

Thank you @xmatthias i appreciate your work very much.

My considerations were because of 200+ instances running. I need it for analytic purposes.
Setting bot id in query wouldn't really do affect performance. Bot query anyway db for open trades if we pass bot id to the query it would be cleaner then to have 200+ databases, i think it as option would be for one or an other usefull.

**Comment by xmatthias** [comment]
that's not how databases work - and apparently you've never worked extensively with databases.

Assume you have 200 bots - all with 1000 trades. 
Adding a new column to the 200 tables will not affect performance for sure.

If you now however have one table with 200.000 lines (200 * 1000) - it WILL implicitly be slower - so it's in general not a good idea - and no index will help you with that in a way that makes it comparable with the other usage.
Also, it's not just the trade table, but also the Orders table, which will have at last 2 * trades orders - in case of stoploss on exchange (with trailing stop) potentially 10's or more per trade - so this table will blow up in your face.


---

Also - running 200 bots (actually, everything > 5) is not really a regular usecase, and sounds like a commercial usage (like you're selling services).

While that's not per se prohibited - please make sure you understand the license implications before doing so - as GPL forces you to provide the sourcecode you're running uppon request - and is generally seen as a liability for companies.

**Comment by x3-dev** [comment]
> that's not how databases work - and apparently you've never worked extensively with databases.
> 
> Assume you have 200 bots - all with 1000 trades.
> Adding a new column to the 200 tables will not affect performance for sure.
> 
> If you now however have one table with 200.000 lines (200 * 1000) - it WILL implicitly be slower - so it's in general not a good idea - and no index will help you with that in a way that makes it comparable with the other usage.
> Also, it's not just the trade table, but also the Orders table, which will have at last 2 * trades orders - in case of stoploss on exchange (with trailing stop) potentially 10's or more per trade - so this table will blow up in your face.
> 
> Also - running 200 bots (actually, everything > 5) is not really a regular usecase, and sounds like a commercial usage (like you're selling services).
> 
> While that's not per se prohibited - please make sure you understand the license implications before doing so - as GPL forces you to provide the sourcecode you're running uppon request - and is generally seen as a liability for companies.

Yes, you are right, maybe it is better to work with the PostgreSQL schemes in that case to separate that between bots, but there is no way at least i didn't found to pass schema in connection string. There is connection parameters and string to build like: engine = create_engine( 'postgresql+psycopg2://dbuser@dbhost:5432/dbname', connect_args={'options': '-csearch_path={}'.format(dbschema)})

I am running each bot with 10K USD and various strategies on 5 exchanges, nothing commercial at all, just like to diversify and minimize the risk.

**Comment by xmatthias** [comment]
Use different users - with the "authorization schema" approach.

alternatively (always using different users) - you should be able to use `alter role user1 set search_path = "user1", public` ... setting the search-path for each user explicitly.

**Comment by x3-dev** [comment]
> Use different users - with the "authorization schema" approach.
> 
> alternatively (always using different users) - you should be able to use `alter role user1 set search_path = "user1", public` ... setting the search-path for each user explicitly.

appreciate, i  will then do some researches and make a fork with a working code as "ThankYou" for community

**Comment by x3-dev** [comment]
Just ended to write and test that code extension available under: https://github.com/x3-dev/freqtrade/tree/psql-schemas

**Comment by xmatthias** [comment]
If you think this is a must have, feel free to submit it as pull request.

Please keep the code to a minimum, including documentation and tests.

As question - i'll consider this as answered.
