### ISSUE TITLE
Backtesting : sell signal not executed

### ISSUE THREAD

**Issue by top-dr** [freqtrade/freqtrade#5039]
## Describe your environment

  * Operating system: Macos
  * Python Version: ( Docker version )
  * CCXT version: ( Docker version )
  * Freqtrade Version: freqtrade 2021.4 ( Docker )
  
## Your question

Hi i am new to freqtrade and i tested my first strategy using backtesting but i dont know why some sell signals did not exeuted ( example attached below ). are there any conditions to ignore some sell signals ?

NB : config used in the test :
    minimal_roi = {
        "0": 100
    }
    stoploss = -0.3
    trailing_stop = True
    timeframe = '15m'
    process_only_new_candles = False
    use_sell_signal = True
    sell_profit_only = False
    ignore_roi_if_buy_signal = False
    startup_candle_count: int = 30
![Screen Shot 2021-05-27 at 9 50 03 PM](https://user-images.githubusercontent.com/64324800/119896552-174d9900-bf37-11eb-90aa-4ac9f1b59d2d.png)

**Comment by xmatthias** [comment]
It's difficult to say this "just like that" - without knowing how your strategy works specifically.

Maybe there's a `confirm_trade_exit()` that's preventing the sell from happening - or a "colliding" buy-signal at the same candle ... 
Also the settings you post seem to come from the strategy - maybe a config setting is overwriting some settings (check your logs for this) ...

**Comment by top-dr** [comment]
My strategy is very simple I buy when close <= lower Bollinger bands and sell when close >= upper Bollinger bands and using RSI as confirmation.
There is no confirm_trade_exit() in my strategy. I checked also the other option but there is no colliding buy-sell. Please can you help me where to start for debugging this problem  ? 

Here is my config in the log file (as expected) :

INFO - Override strategy 'timeframe' with value in config file: 15m.
INFO - Override strategy 'stake_currency' with value in config file: USDT.
INFO - Override strategy 'stake_amount' with value in config file: unlimited.
INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
INFO - Override strategy 'use_sell_signal' with value in config file: True.
INFO - Override strategy 'sell_profit_only' with value in config file: False.
INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
INFO - Strategy using minimal_roi: {'0': 100}
INFO - Strategy using timeframe: 15m
INFO - Strategy using stoploss: -0.3
INFO - Strategy using trailing_stop: True
INFO - Strategy using trailing_stop_positive_offset: 0.0
INFO - Strategy using trailing_only_offset_is_reached: False
INFO - Strategy using use_custom_stoploss: False
INFO - Strategy using process_only_new_candles: False
INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
INFO - Strategy using stake_currency: USDT
INFO - Strategy using stake_amount: unlimited
INFO - Strategy using startup_candle_count: 30
INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
INFO - Strategy using use_sell_signal: True
INFO - Strategy using sell_profit_only: False
INFO - Strategy using ignore_roi_if_buy_signal: False
INFO - Strategy using sell_profit_offset: 0.0
INFO - Strategy using disable_dataframe_checks: False
INFO - Strategy using ignore_buying_expired_candle_after: 0

If you need further information please let me know. Thanks

**Comment by xmatthias** [comment]
the most likely reason is quite often that backtest data was not exported - so the plot is using a new strategy for the signals - but the trade itself is not generated with the last version of the strategy.

**Comment by top-dr** [comment]
I always export trades when backtesting. I suspect the below scenario if you can confirm.

I have a condition in my strategy for selling if the blue line cross over the red line. As shown in the picture bellow this is the case for just a little amount of time. so I think that the signal was triggered but when trying to make the order the condition is no more valid.

Ca you confirm please or I mess something ?
![Screen Shot 2021-05-28 at 10 58 04 AM](https://user-images.githubusercontent.com/64324800/119967782-a218ad00-bfa4-11eb-9770-91995b58dc09.png)

**Comment by xmatthias** [comment]
Based on the information provided, it's impossible to say what you missed - and there's many possibilities.

Now to align backtesting and plotting, best make sure to use the same timeframe and timerange to exclude any potential issues with calculating indicators.
with your config (assuming you don't use any sell-preventing measures in your strategy), a sell signal will always be respected if it's been there while backtesting - so the best bet is that either backtesting wasn't exported, or something changed between backtest and plotting.
