### ISSUE TITLE
Multiple stake_currency

### ISSUE THREAD

**Issue by cabellop5** [freqtrade/freqtrade#5041]
Hello, is there any idea to implement that with a single bot you could trade different currencies, for example some pairs of BTC and some of USDT in the same bot?

**Comment by xmatthias** [comment]
No, at least not for the moment.

It's been looked at / discussed before - and the code complexity added would increase the maintenance effort / code complexity by too much - which will make it difficult to maintain (keep in mind that it's maintained for free, in people's free time).

Please use multiple bots for this usecase.
