### ISSUE TITLE
Integration of additional external data sources like APIs

### ISSUE THREAD

**Issue by AntonioBlago** [freqtrade/freqtrade#5044]
I would like to integrate additional datasources from external apis as a signal.
I do not know how i can merge them into my current signals. 

Has anyone tried that before? 

Thanks!

**Comment by xmatthias** [comment]
In principle, a strategy is simply a python file that's called over and over again - so nothing will be stopping you from querying an API for this.

How to properly merge this to get valid backtesting results i don't know (depends on the API - if it even gives you historic data) - and if it does, you'll need to be very careful to avoid lookahead biases - as that would show good backtesting results - but would obviously not perform well in live.

If you have further questions / want discussions relating to this, please use the [discord channel](https://discord.gg/MA9v74M) to discuss this in the community.
People there love to help assuming the documentation has been consulted first - and it's not a "i have this idea, please implement it for me"-type question.

**Comment by Hsgngr** [comment]
Hi Anotnoio, have you find a solution for this ?
