### ISSUE TITLE
Bot crashing after few hours of running (FTX)

### ISSUE THREAD

**Issue by Fimap9to1** [freqtrade/freqtrade#5045]
Hi Matthias,
I've started the bot live (dry run false), but it works just for a few hours and then it crashes (like 10/15h). Stoploss works smoothly. Don't know about sell orders yet because I had none. Fortunately stoploss orders remain on the exchange (FTX) after the crash, so risk is limited to that even if the bot crashes.

This happens just if dry run = false. In dry run = true everything works. 

Now, I don't get if this is my fault or is a bug, that's why I use the question label.
I have taken a screenshot of the logs but not so complete, before I've lost access to the page and it's gone.

Attach it here:
![a](https://user-images.githubusercontent.com/74922424/120065007-7c0c0f00-c06f-11eb-881a-c0595a22330a.png)

Thanks in advance for you kind response and sorry for the few information provided!

Pairlist is 30 leveraged token

`"order_types": {
        "buy": "limit",
        "sell": "limit",
        "emergencysell": "market",
        "stoploss": "limit",
        "stoploss_on_exchange": true,
        "stoploss_on_exchange_interval": 300

 "exchange": {
	"name": "ftx",
        "key": "",
        "secret": "",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
`

**Comment by xmatthias** [comment]
the logs (please copy/paste the text next time, don't use a screenshot - that keeps it searchable)  indicate that it's happening as part of the sell notification.

I don't see anything particularily wrong based on the info given - and i use a very similar (same order-types) configuration on FTX as well without problems.

**Comment by Fimap9to1** [comment]
Ok thanks, do you have any idea about what could be causing the crash and how to fix it? 

It crashes just in dry run = false

**Comment by xmatthias** [comment]
well yes - that's when exchange answers come in :laughing: 

not really - i mean - i can read the message and know what it means - but i'm not sure which field is empty.

**Comment by xmatthias** [comment]
Are you maybe able to provide some more logs (in text form ideally - basically a few minutes before the crash up to the crash)? 
The screenshot above only includes the crash itself - but often the logs leading up to that point will point to the real issue.

**Comment by Fimap9to1** [comment]
Ok got it. I will run it again and paste the logs once I get the error again! Thanks!

**Comment by Fimap9to1** [comment]
Hi, so it crashed again finally. The issue, I think, is tied to "stoploss on exchange = true". It seems that when stoplosses start to trigger the bot crashes. One thing i'm certain about, is that they are placed correctly, since even if the bot crashes they trigger (sell order is filled).

I'll try without stoploss on exchange and let you know.

The exchange i'm using is FTX. Just to let you know in case this is something that can be solved! Have a nice day!

**Comment by xmatthias** [comment]
Any new logs to provide ... ?

**Comment by Fimap9to1** [comment]
Unfortunately no because something went wrong with the log file creation. Anyway now I'm running without stoploss on exchange, but since I got no stoploss yet I can't tell if that have solved the problem.

**Comment by Fimap9to1** [comment]
Hi, it is the stoploss on exchange for sure. Once switched to =false, I didn't have the crash again despite a number of stoplosses hit. So on FTX the stoploss on exchange = true seems to cause some problems. I can only tell this, unfortunately I can't provide logs.

**Comment by xmatthias** [comment]
Should be fixed now in the latest develop.

**Comment by Fimap9to1** [comment]
Great thanks for your answer!
