### ISSUE TITLE
How do I implement chande kroll stop indicator into freqtrade?

### ISSUE THREAD

**Issue by frank01100110** [freqtrade/freqtrade#5047]
How do I implement chande kroll stop indicator into freqtrade?

**Comment by xmatthias** [comment]
First of all - i've never heared of this indicator (however google helps).

Then - you'll need to find a library (or implement the calculation yourself) - and then include that in your strategy.

Please understand however that this is an open source project, so we're not providing this kind of "implementation" support.

If you have further questions / need assistance, please use the [discord channel](https://discord.gg/MA9v74M) to get support / help from the community.
People there love to help assuming the documentation has been consulted first, and it's not a "i have this idea, implement it for me"-type question.
