### ISSUE TITLE
Add buy_reason to logs similar to sell_reason

### ISSUE THREAD

**Issue by BillGatesIII** [freqtrade/freqtrade#5058]
When a trade is closed the reason is in the rpc message.

For example:
2021-05-31 08:30:47 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell, 'trade_id': 41, 'exchange': 'Binance', 'pair': 'OGN/USDT', ... **'sell_reason': 'roi_target_1'** ...}

Please add the buy reason to the 'type': buy info.

**Comment by xmatthias** [comment]
The only reasons for buys are buy-signals or forcebuys.

While it's technically different - you'll not be using forcebuy frequently - so there is little to no value adding this.

**Comment by BillGatesIII** [comment]
Thanks for your answer. I realize I asked the wrong question. What I am looking for in the logs is the buy reason of a trade. So which signals did trigger the buy? With 'sell_reason' I know where to look in the strategy to find the find the condition why the trade was closed. I would like to do the same for trades open.

**Comment by xmatthias** [comment]
the new question is a duplicate of #3081.
