### ISSUE TITLE
PerformanceFilter - last x mins  

### ISSUE THREAD

**Issue by sephirot86** [freqtrade/freqtrade#5060]
Hi for the first time and thank you for this magnificent piece of software :) 

I just discovered PerformanceFilter for the pairlists. I am excited about it and I would like to share some thoughts about possible improvements to this. 

Idea is to give possibility of taking into account performance from last x mins, hours, days. It can happen that one of the pairs had bad streak in first hour losing f.e. -3% and other pairs winning 0.1%. Having 30 pairs and trading 10 best of them it would mean that for this pair it's impossible to move to top 10 before all other pairs will prove to be worse. It can actually never happen and this pair could be the best in 2nd hour.

**Comment by xmatthias** [comment]
i guess it could be added ... 

You'll need to be careful with your scenario though - assuming from the 30 pairs, 11 or 12 are "mostly" winners - you'll exclude most of the latter pairs "in principle" - just because they never got a chance to prove themselfs - so using this sorting method to reduce the number of pairs can be dangerous too.

**Comment by sephirot86** [comment]
I understand your concern. I was also thinking about it. My strategy is doing a lot of short trades on 1m timeframe and it is vulnerable to the local trends or price moving sideways. If all of my pairs are winning - I am happy enough :) 

Basically I think in case when this setting is not in place is even more risky that those pairs will never have chance to prove value. 

In my case I see it like this:
1. I would be using the sorting based on last 1hr performance.
2. If all the pairs have buy signal at the same time - best 10 will have priority. 
3. If not all from top 10 receive buy signal - pairs from the bottom have chance to prove themselves.
4. Pairs that didn't have chance to prove themselves in last period will have a chance over those losing in last period.

In my head it makes sense but maybe I am missing something :)
