### ISSUE TITLE
Less buy signals with more whitelisted pairs

### ISSUE THREAD

**Issue by ericrange** [freqtrade/freqtrade#5062]
is it possible that the more whitelisted coins the more the bot will have difficulties to find buy signals?

i have the feeling that less coins will have more! buy signals. is that possible?

**Comment by xmatthias** [comment]
buy-signals will solely depend on your strategy.

Obviously, the fewer pairs you have, the "easier" it is to tune the strategy onto the very specific conditions these pairs showed in the past - however, usually that results in a not well generalized strategy - so it's possible that it'll fail on future (or unseen) data.

Also, if you run on very short timeframes (1m) - you might encounter timing problems if your strategy is slow to calculate indicators.
