### ISSUE TITLE
ignore_buying_expired_candle_after not working as expected

### ISSUE THREAD

**Issue by karthikdatta** [freqtrade/freqtrade#5063]
Even after I use "ignore_buying_expired_candle_after" configuration the bot is executing buy signals from past 10 15 candles in dry run. The bot is buying using the buy signal from past even if the buy condition is not satisfying on the present time frame. 
How can I make sure it ignores the past buy signals which are no longer valid ?

**Comment by xmatthias** [comment]
`ignore_buying_expired_candle_after` works intra-candle, and will reset with each candle.

if your signal is "sticking" (active for more than one candle) - then your signal must be changed (most likely by using a "crossed" as signal). 
`ignore_buying_expired_candle_after` is not designed nor intends to prevent this from happening.
