### ISSUE TITLE
How do I put a daily indicator inside a 5m chart? 

### ISSUE THREAD

**Issue by frank01100110** [freqtrade/freqtrade#5064]
How do I put a daily indicator inside a 5m chart? I'd need a daily adx inside a 5m chart.

**Comment by xmatthias** [comment]
Please make sure to read the documentation, and research if it's covered by the documentation before opening pointless issues.

You can use [informative pairs](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-informative_pairs) for this.

**Comment by frank01100110** [comment]
> Please make sure to read the documentation, and research if it's covered by the documentation before opening pointless issues.
> 
> You can use [informative pairs](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-informative_pairs) for this.

It worked, thank you.
