### ISSUE TITLE
Display number of trades bought and sold on same candle

### ISSUE THREAD

**Issue by gergokekesi** [freqtrade/freqtrade#5068]
## Describe the enhancement

It would be very useful to output how many trades were executed within the same candle to try and improve the strategy and see how realistic it has been. As we know, backtesting has to make assumptions about the price and a strategy that ends up hyperopting to parameters which buy and sell the same candle might not be very realistic. We now have the zero minute trades but I sometimes end up having strategies that make few minute trades on 5m candles. Would it be possible to add the the backtesting output a variable that states how many trades were done shorter than the timeframe used?

**Comment by xmatthias** [comment]
This is available as `Zero Duration Trades` in the backtest summary report since 2021.5.

**Comment by gkekesi** [comment]
Oh really? So if a trade was made in 2 minutes on a 5m candle strategy it is considered as a "zero duration" in the output?

**Comment by gergokekesi** [comment]
Oh really? Could you please clarify that if a trade was opened and then closed 2 mins later on a 5m candle strategy it is considered as "zero duration"? The duration was 2 minutes not zero.

**Comment by xmatthias** [comment]
as we're talking about backtesting, times below the candle length are not available - or rather will always be assumed 0.
