### ISSUE TITLE
Backtest different if using stoploss vs custom stoploss (with the same setting)

### ISSUE THREAD

**Issue by Fimap9to1** [freqtrade/freqtrade#5072]
## Describe your environment

  * Freqtrade Version: freqtrade develop-8e44de7f
  
## Your question

Hi, I was trying a custom stoploss as this guy did here, so using data from the "trigger" candle to place a stoploss fixed. 
Link: https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/fixed_riskreward_loss.py

We've done like this in our strat:

```
def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:

        """
            custom_stoploss
        """
        result = -1
        custom_info_pair = self.custom_info.get(pair)
        if custom_info_pair is not None:
            # using current_time/open_date directly via custom_info_pair[trade.open_daten]
            # would only work in backtesting/hyperopt.
            # in live/dry-run, we have to search for nearest row before it
            open_date_mask = custom_info_pair.index.unique().get_loc(trade.open_date_utc, method='ffill')
            open_df = custom_info_pair.iloc[open_date_mask]
            # trade might be open too long for us to find opening candle
            if(len(open_df) != 1):
                return -1 # won't update current stoploss
            initial_sl_abs = open_df['stoploss_price']
            initial_sl = initial_sl_abs/current_rate-1
            result = initial_sl
       return result
```

Than used this in the populate indicator:

```
########### STOPLOSS ##############
        dataframe['stoploss_price'] = dataframe['close'] * 0.8944
        self.custom_info[metadata['pair']] = dataframe[['date', 'stoploss_price']].copy().set_index('date')
```

The strat is now using a normal stoploss of -0.1065. So in order to test if we get the same results with the custom stoploss (therefore test if it works properly) we used in populate indicator: dataframe['stoploss_price'] = dataframe['close'] * (1-0.1065). 

Since what we write after "dataframe['stoploss_price'] =" is the data coming from the trigger buy candle, they should work the same way.

And in the dry run mode it does.
Unfortunately it doesn't work on backtesting (we get very different results, in particular tot profit % and drawdonw % change a lot), making it difficult to test this custom stoploss for a reliable period of time.

Can you please help us understand the reason behing the issue? 

FURTHER INFORMATION
The number of trades is basically the same, winning trades and losing trades are equal in both cases (with and without custom stoploss). 
Avg profit for stoploss and sell signal are the same.
It happens with unlimited stake amount and fixed stake amount (in some cases it gets better with fixed stake amount and gets worse with unlimited stake amount)

So everything the same exept for the data reported above.

**Comment by xmatthias** [comment]
i can only point to the [backtesting assumptions](https://www.freqtrade.io/en/latest/backtesting/#assumptions-made-by-backtesting) page, which covers this (although not naming custom-stop specifically).

Backtesting will not use close.
As `custom_stoploss` is treated as a "dynamic trailing stop" adjusting to your needs - it's called with the candle's "high" price and profit.
The stoploss is then adjusted (if it's higher than the previous one) - and evaluated against the candle's low price.

As such - if your stop is too tight (tighter than the difference between high and low) - it'll trigger immediately.

Also for dry, using "close" will not be 100% correct - as your custom-stop will be evaluated multiple times within a candle with the current price / profit (which is not available in backtesting).

**Comment by Fimap9to1** [comment]
Ok thank you so much for the answer!
