### ISSUE TITLE
Problem importing custom indicator

### ISSUE THREAD

**Issue by frank01100110** [freqtrade/freqtrade#5074]
I followed the tutorial to import ichimoku and it worked. But I can't import trendlines and zema, or pivot points. 

I should write something like:
from techinnical.indicators import zema
from techinnical.indicators import trendlines
from techinnical.indicators import pivot_points

And then something like:
dataframe['trendlines'] = trendlines(dataframe)

Could you please help me?

**Comment by xmatthias** [comment]
You've got a typo in your imports - there is no module named `techinnical` (at least none i know) - but it's called `technical`.

You'll need to be careful with the trendlines (except for the fact that it's not imported from `technical.indicators`) - using it this way will apply it to the full dataframe, which will result in a lookahead bias during backtesting/hyperopt.

**Comment by frank01100110** [comment]
> You've got a typo in your imports - there is no module named `techinnical` (at least none i know) - but it's called `technical`.
> 
> You'll need to be careful with the trendlines (except for the fact that it's not imported from `technical.indicators`) - using it this way will apply it to the full dataframe, which will result in a lookahead bias during backtesting/hyperopt.

Apart from the typo, I didn't copypaste it from the code, on the code it was written correctly,  I still don't understand how do I import trendlines and other custom indicators. With ichimoku I followed the instruction and it worked , with these other indicators it doesn't work. Could you show me some code example for these, on how to impprt them?

**Comment by xmatthias** [comment]
You're importing from technical.indicators - but trendline / pivot_points are NOT in the indicators package - but kindof "standalone", so the import will be `from technical import trendline` and `from technical import pivot_points`.
You'll then have the packages - and can call the methods that are in these files.
