### ISSUE TITLE
What does the cumulative profit percentage say?

### ISSUE THREAD

**Issue by NielsHoogeveen1990** [freqtrade/freqtrade#5075]
When I do optimalization with HyperOpt the profit at a certain epoch says: 82 dollar (8.2 percent)

However, my stake_amount is 100 dollar. So if I would have 82 dollar profit, that would be 82% and not 8.2%. I don't get it how the profit percentage is calculated?

I only trade with BTC, ETH and BNB by the way.

These are my configs:

```
    "max_open_trades": 10,
    "stake_currency": "USD",
    "stake_amount": 100,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD"

        "pair_whitelist": [
            "BTC/EUR",
            "ETH/EUR",
            "BNB/EUR"
        ]

```

**Comment by xmatthias** [comment]
First of all - please don't remove the issue-template - but fill it out. 
Definitions / calculations may change over time - so the version you're using IS important even though you don't think so - and i'll start closing issues without further comment soon if the issue-template is not filled out.

That said ... 82% is the profit on ONE stake (100$) - your total account however is 100 * 10 (1000$) - so 8.2% on 1000$ is correct for 82$.

The definitions are in the [backtesting page](https://www.freqtrade.io/en/stable/backtesting/#summary-metrics) - and it corresponds to `Total profit %` (however the calculation for this in hyperopt has been changed in the last release).

**Comment by NielsHoogeveen1990** [comment]
@xmatthias alright! Thank you. Hence, when I want to trade and I set stake_amount to 100 dollar with 10 open trades, I should put 1000 dollar on my account (for example deposit 1000 dollar on Binance)?

Another question, though not related to this one: is it possible to also optimize the indicators parameters itself? For example: optimize the period for Bollinger Bands or the slow and fast period for the MACD?

I want to optimize the MACD itself. So with a range for the slow period for example (8,16).

**Comment by xmatthias** [comment]
Please [read the documentation](https://www.freqtrade.io/en/stable/hyperopt/#optimizing-an-indicator-parameter). Most questions you'll most likely have will be covered there.
