### ISSUE TITLE
No module named "freqtrade.indicator_helpers"

### ISSUE THREAD

**Issue by zepzeper** [freqtrade/freqtrade#5079]
Hi there, I tried running the bot for the first time I came across this error, couldn't find a solution 

![image](https://user-images.githubusercontent.com/79146984/120903845-d812fc80-c648-11eb-9364-0457b4d10fc3.png)

**Comment by xmatthias** [comment]
It's correct - freqtrade does not have a module `indicator_helpers` (and never had).

So very simply - your import is wrong.

**Comment by zepzeper** [comment]
That's what i thought, i cloned the most recent version of git why would it give that error

**Comment by xmatthias** [comment]
well the problem is in your strategy using something that doesn't exist, not in freqtrade.

**Comment by zepzeper** [comment]
Hmm that's weird i just downloaded it and wanted to use a default strategy to make sure everything is working fine

**Comment by xmatthias** [comment]
While i can understand that - BBRSI is not a default strategy... :)

**Comment by zepzeper** [comment]
I sort of fixed it i reinstalled the whole git rep. now there isn't a default strategy in the current version so I found one on the strategies git. It still doesn't seem to work. I added the file into the __init__ 
from freqtrade.strategy.test import Strategy001 
It gives the error that the class can't be found or contains errors (wich is kinda unlikely cause I copied it from the github pages)

**Comment by xmatthias** [comment]
We have some nice documentation containing  first steps [with](https://www.freqtrade.io/en/stable/docker_quickstart/#docker-quick-start) or [without](https://www.freqtrade.io/en/stable/installation/#initialize-the-configuration) docker, which will contain a command to `create-userdir` - which will install a sample strategy that can be used.

I have no idea what you're doing - but there exists no `freqtrade.strategy.test` - and there never has.

As such - i'd recommend to read the documentation (best from top to bottom - at least skimming the parts you're currently not interrested) - it'll include step by step installation instructions on getting started.

**Comment by WisangAnggoro** [comment]
Hi, I had the same problem before, it was solved by downgrading the python version used by env from 3.9 to 3.8

**Comment by xmatthias** [comment]
Well let me repeat what i said above - freqtrade does NOT expose a module called `freqtrade.indicator_helpers` (nor `freqtrade.strategy.test`).

The python version will not have any meaning / significance in that.

**Comment by zepzeper** [comment]
I managed to make it work nu reinstalling thanks Matthias!
