### ISSUE TITLE
CUDA processing for hyperopt

### ISSUE THREAD

**Issue by shocker1185** [freqtrade/freqtrade#5085]
## Describe your environment
(if applicable)

  * Operating system: win10x64
  * Python Version: 3.7/8 (`python -V`)
  * CCXT version: latest (`pip freeze | grep ccxt`)
  * Freqtrade Version: latest (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

Can we please implement this into hyperopt? 

https://developer.nvidia.com/how-to-cuda-python

**Comment by xmatthias** [comment]
The short answer: no.

freqtrade uses scikit-optimize / scikit-learn under the hood, so if you want GPU support, please talk to them first.
scikit-learn does however document their strategy around GPU [pretty clearly](https://scikit-learn.org/stable/faq.html#why-is-there-no-support-for-deep-or-reinforcement-learning-will-there-be-support-for-deep-or-reinforcement-learning-in-scikit-learn) -

It's normally a question of people not understanding the topic of GPU well, and have been told that "gpu's are faster". While that's true for VERY specific usecases, they do a very bad job at generalizing.

GPU's are good with floating point operations (and only that). Hyperopt spends most of the time running backtesting, which is regular python code, and calls the strategy again and again.
As such, it would not be possible to move that to the GPU without having users write compatible GPU code - which will mean you'll need to reimplement ALL indicators again (none of the TA libraries known to me are even remotely GPU compatible).

as such, i'll close this as "won't fix" - as that's what you'd get from the scikit-learn folks as well.
