### ISSUE TITLE
Any way to increase dynamic stake allocation?

### ISSUE THREAD

**Issue by algeronwaterschoot** [freqtrade/freqtrade#5087]
## Environment
  * Operating system: Linux
  * Python Version: 3.8.5
  * CCXT version: 1.50.30
  * Freqtrade Version: develop-a0893b29

## Configuration

`--dry-run-wallet 1000`
```
[...]
"max_open_trades": 10,
"tradable_balance_ratio": 0.99,
"stake_amount": "unlimited",
[...]
```

## Description

If I understand correctly, when using dynamic stakes, the allocated stake will be equal to `wallet * tradable_balance_ratio / max_open_trades = stake`. Following the abovementioned config, each of the 10 trades will stake out`1000 * 0.99 / 10 = 99`. So far so good.

To illustrate the edge-case, let's say I'm using a strategy that is so successful that my first trade returns 100% in profit. Several seconds later, it picks up a buy signal and starts a new trade.
According to the formula, the stake will consist of `1100 * 0.99 / 10 = 108.9`. Again, as expected.

However, this means (based on my newbie understanding) that there is now `91.1` unallocated budget sitting in the wallet. It would take another 9 trades for it to "catch up", at which point it won't just be lagging by 1 trade; it'll lag by 10 trades.

**Is there a way to add an additional parameter to the stake calculation, to allow it to exceed its allocated amount?** AKA `wallet * tradable_balance_ratio * stake_allocation / max_open_trades = stake`. In the previous example, a `stake_allocation` of `1.1` would result in `1100 * 0.99 * 1.1 / 10 = 119.79`.
This feature would allow the bot to integrate profits into its trading strategy much more rapidly.

Naturally, the default would be `1`, and it would only apply if `amend_last_stake_amount` is set to `true`.

If this is already possible, please let me know! I've been scouring the documentation but can't find anything.
Thanks!

**Comment by xmatthias** [comment]
you can simply change `tradable_balance_ratio` to reduce the amount of reserved capital. 
0.99 (1% reserved) is the default - but that is based on the assumption that many people will start with a smallish account (maybe 100-200$).

The moment you're on bigger accounts, you can very easily scale this parameter too (so using 0.999 will only reserver 0.1%, not 1%).
Having it as ratio has the benefit of not having to change it based on changing stake-currencies - however with bigger accounts, the default might not fit very well anymore.

your goal should be to have ~1$ per stake reserved (so 10$ in your case). 
If you're however on binance, and you will make sure yourself that you'll have BNB in your account at all times (and obviously use BNB to pay for trades) - you can use 1 here (so the full account balance will be used) - as this "reserve" is really there to cover eventual fees should they be deduced from the stake currency.

**Comment by algeronwaterschoot** [comment]
That's right, but you'd still be limited to asymptotically approaching 1. I guess another way to frame my initial question is: Can I make the bot behave as though `tradable_balance_ratio` is higher than 1?
I understand that's not how that parameter is intended to be used, nor would I want to recommend that approach. I'm just putting it out there in an attempt to clarify my use-case. :smile:

**Comment by xmatthias** [comment]
having `tradable_balance_ratio > 1` would mean you have a 1000$ account - and would like the bot to use 1100$ of these 1000$.

While currently freqtrade is "preventing" you from doing this - it will be the exchange that has the ultimate say and will tell you "you don't have enough money for that trade" - so the answer is no, and it also doesn't make sense.

**Comment by algeronwaterschoot** [comment]
I agree. Would a separate parameter make more sense?

**Comment by algeronwaterschoot** [comment]
Also, to clear up a potential point of confusion:
My goal isn't to trade more than I have in my wallet. My goal is to allow freqtrade to reinvest its earnings more efficiently. I'm running 10 trades at `"tradable_balance_ratio": 0.99`, yet I often see >10% of the total capital just sitting in the wallet, even though I'm at max open trades. This is because of the way in which dynamic stakes are currently calculated.
Rather than only looking at `tradable_balance_ratio` and `max_open_trades`, dynamic stakes should also factor in the current state of the wallet. The `amend_last_stake_amount` boolean is one attempt at solving this problem. I believe there is more low-hanging fruit left unpicked.

**Comment by xmatthias** [comment]
As mentioned above - there's nothing wrong with using a lower `tradable_balance_ratio` (like `0.999` - which will be 0.1% instead of the default 1%) if you're using higher stakes. 

I don't see what a new option can bring on top of that.

Please consider `tradable_balance_ratio` a hard limit.
As such, i'll surely not accept a modifier which can increase the tradable balance to be higher than what's configured here. If you need that, set `tradable_balance_ratio` to 1 so it'll trade all available balance.

**Comment by xmatthias** [comment]
i guess this can be covered with #5076 (where you can provide "whatever" you want as stake-amount) - so you can do your magic there (freqtrade will however not allow you to go over `tradable_balance_ratio` - it is however up to you to "properly" split the stakes so you get the maximum gain.

As such - i don't see why we should be needing an additional configuration - as that will only complicate (and possibly conflict) with #5076.
