### ISSUE TITLE
Use signal from pair 1 to trade pair 2

### ISSUE THREAD

**Issue by duquel** [freqtrade/freqtrade#5098]
Hello everyone. First of all I want to thank the original programmers and everyone else who has contributed to this project. It truly is a great trading platform.

This message is not really an issue. It's more of a question.
Is it possible in a strategy or a config to do the following?
Say I get a sell signal on BTCUSDT. The BTC gets sold off but I also want to buy half a position of BTCDOWN when this happens. When later I get a buy signal on BTCUSDT, I want it to sell that position of BTCDOWN and buy a full position of BTCUSDT.
If there would be a way, it would enable shorting.

**Comment by duquel** [comment]
Forget about it. There is no point in doing this. I just tried the same thing on tradingview and the results are not any better than just doing ta on the btcdown itself.
BTCDOWN is heavily skewed and weird. 
It would be great to have the ability to just short like one usually would in the normal trading world. I am not talking about using leverage or anything. Just good old 1x shorting.
The leveraged tokens on Binance like BTCDOWN or ETHDOWN are just weird tokens with weird dynamics. They are definitely not good for swing trading.

**Comment by bzed** [comment]
@duquel but in case you want to try it: https://www.freqtrade.io/en/latest/strategy-customization/#complete-data-provider-sample - add it as informative pair and merge the data for that pair additionally.

**Comment by duquel** [comment]
> @duquel but in case you want to try it: https://www.freqtrade.io/en/latest/strategy-customization/#complete-data-provider-sample - add it as informative pair and merge the data for that pair additionally.

Thanks! This is cool.
Still, shorting should really be supported like it is on any forex trading platform since the beginning of time like on Metatrader 4 and the other countless trading platforms. But whatever, I guess beggars can't be choosers.
