### ISSUE TITLE
Move from Hyperopt to scikit-optimize

### ISSUE THREAD

**Issue by vertti** [freqtrade/freqtrade#510]
Scikit-optimize is an alternative to Hyperopt. Benefits:

- what seems like trivial parallel execution (without MongoDB)
- more search algorithms
- seems to be actively maintained unlike Hyperopt
- plotting of objective function results (might allow for dropping bad indicators etc)

Like Hyperopt it has:
- dump/load for continuing previous executions

https://scikit-optimize.github.io/

**Comment by glonlas** [comment]
I like the idea, can we also refactor hyperopt file at the same time? Less global variable, less global functions

**Comment by MoonGem** [comment]
Have you guys checked out ray?

https://github.com/ray-project/ray

**Comment by vertti** [comment]
@MoonGem It's not about pure parallelization but instead coordinated search in parallel. So it needs to be in the core of the param hyperopt library, not a separate parallelization library.

**Comment by vertti** [comment]
@MoonGem scratch that.. And THANK YOU! Turns out Ray has a sub-project RayTune which is hyperopting project and it even has HyperOpt integration: http://ray.readthedocs.io/en/latest/tune.html#hyperopt-integration

**Comment by shusso** [comment]
fixed in #930
