### ISSUE TITLE
Custom stoploss helper stoploss_from_open() returning zero

### ISSUE THREAD

**Issue by theluxaz** [freqtrade/freqtrade#5107]
Stoploss must be negative for it to work for dry-run/live trading in my case, otherwise it often returns zero and shows an error for invalid stoploss amount.  Also if the "current profit" variable is negative, the function also returns 0.0 value during backtesting.

Here is an example showing stoploss, current profit and result respectively during backtesting:
```
2021-06-09 02:08:20,247 - freqtrade.strategy.interface - WARNING - CustomStoploss function did not return valid stoploss
failed result!!!!!!
-0.097 (SL)
-0.10141693 (CurrentP)
0.0 (Result)
```

result = stoploss_from_open(stoploss, current_profit)

**Comment by xmatthias** [comment]
Please keep in mind that the method you're using is calculating the stoploss from the trade's open - so the stoploss MUST be greater than the current profit (if profit is negative) for this to work.

your current profit is -10% - but you're trying to set the stoploss to -0.97% below open.
That stoploss cannot be placed (exchanges would reject it as it would trigger immediately).

the method implementation even has a comment about this:

```
# negative stoploss values indicate the requested stop price is higher than the current price
```

As such - returning 0.0 is the "safe" way - as it'll mean no change to the stoploss will be made - and the prior stoploss will be kept.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
