### ISSUE TITLE
Ignoring expired candles => bid or ask strategy ?

### ISSUE THREAD

**Issue by pascal00d** [freqtrade/freqtrade#5109]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: 3.8.5
  * CCXT version: 1.51.3
  * Freqtrade Version: develop-4512ece1
  
## Your question

Maybe I misunderstood the documentation, but the option "ignore_buying_expired_candle_after" should be in "bid_strategy" and not in "ask_strategy", right?

**Comment by xmatthias** [comment]
Yes that's correct, it was an oversight when it was introduced. it can however also be specified at strategy level - which i usually do, as the desired amount depends on the timeframe used ... (which i personally don't keep in the config).

we will probably revisit the location of these settings sometime in the future (as part of #2867) - but changing settings around is something we try to limit as much as possible - as it'll always cause some friction for the users.
