### ISSUE TITLE
Dry_Run + Webhooks results in Fatal Error

### ISSUE THREAD

**Issue by Gabriele-Sabatino** [freqtrade/freqtrade#5110]
Hello, I am having the same problem as this user was having: https://github.com/freqtrade/freqtrade/issues/2200#issue-487219275. I was wondering if anyone found a solution to this problem.

**Comment by xmatthias** [comment]
That issue ia 2 years old, so its unlikely you have the same problem.

Please fill out the issue template and include logs so we can have a look. Wothout that info, ill close this issue without further comment.

**Comment by Gabriele-Sabatino** [comment]
This is the issue I'm having:
![Screen Shot 2021-06-09 at 2 37 29 PM (2)](https://user-images.githubusercontent.com/50143943/121450825-75807000-c96a-11eb-8e7f-528deb347209.png)

**Comment by xmatthias** [comment]
Your version is 0.18.1. 
That version is almost 3 years old - and you probably didn't install it from this repository (it's quite difficult to get to that version here ...).


As open source project, we do not support versions that are more than 2 releases old.

As such - please either update to the latest version - or search help where you got that version from.

Thanks for your understanding.

**Comment by Gabriele-Sabatino** [comment]
What are the steps to updating to the latest version. Cant find a way to get the latest version.

**Comment by xmatthias** [comment]
I don't think you can safely update from this version (too much might have changed - also from a configuration perspective).

So best reinstall, eihter with [docker](https://www.freqtrade.io/en/stable/docker_quickstart/) or by using the [regular installation](https://www.freqtrade.io/en/stable/installation/).
