### ISSUE TITLE
Informative Pairs with Custom Stop loss

### ISSUE THREAD

**Issue by FahadAziz** [freqtrade/freqtrade#5111]
Hi

The question is self explanatory, How can I use indicators calculated from informative pairs in the custom stop loss?

Thanks

**Comment by xmatthias** [comment]
Quite simply by combining the instructions for [informative pairs](https://www.freqtrade.io/en/stable/strategy-customization/#complete-data-provider-sample) with the [custom stoploss](https://www.freqtrade.io/en/stable/strategy-advanced/#custom-stoploss-using-an-indicator-from-dataframe-example) example.

As you merge the informative pair dataframe to the "real" dataframe, it's columns will be available to custom_stoploss as well.
