### ISSUE TITLE
Max open trade for each pair

### ISSUE THREAD

**Issue by heysyam99** [freqtrade/freqtrade#5112]
## Describe your environment

  * Operating system: Mac OS Docker
  
## Your question

How can I set max open trade for each pair? For example, my max open trade is 20, and I have 10 whitelist pair, how can I set each pair only can have 2 open trades? Thank you

**Comment by xmatthias** [comment]
Freqtrade will open one trade per pair at the same time.

As such - your configuration will never open more than 10 trades at the same time.

While there's issues / proposals to change this #1519 - it's not possible at the moment.

**Comment by lazydroid** [comment]
@xmatthias could you please tell why we have `--enable-position-stacking` parameter for backtesting, but not for the actual trading?

**Comment by xmatthias** [comment]
It is a useful feature to pull out "hidden" signals - which is usually a sign of a badly designed strategy (one where the signal is active for a long period of time).

**Comment by lazydroid** [comment]
thank you very much for answering my question!

i understand the reasoning, but for some reason there are strategies that perform better with position stacking enabled. and however poorly designed are these strategies, is there any way to enable position stacking for the trading the same way it can be enabled for backtesting?

**Comment by xmatthias** [comment]
No there is currently not.
Feel free to subscribe to #1519 for updates on this topic.
