### ISSUE TITLE
Dyanmic open trades based on number of buy signals

### ISSUE THREAD

**Issue by szucsaaron2** [freqtrade/freqtrade#5113]
## Describe the enhancement

Hey!

I am interested if this would be possible to implement, or how would one go about implementing this. My strategy has right now 60 max_open_trades and what I realized is that it has different performances. On some days it only has 1-10 open trades and some other days it has even 60 open trades at once. My strategy is profitable in both circumstances. 
Although I believe it would be even more profitable if max open trades would be dynamically allocated.
Sure, I believe it would not be so easy to determine max_open trades easily because for the following reason: Let's say at a given time the bot finds 10 buy signals, so it allocates the capital in a way like capital/10. And then one would have to wait until those trades are closed to use the new max_open_trades parameter. Nevertheless, I look at this problem as a challenge to be solved and not a problem that could hold as back.
Perhaps could someone give me a hint where this section is coded into freqtrade, so I can modify it and post the code here in case someone else also needs it?

Best wishes,
Áron

**Comment by xmatthias** [comment]
what you can do is set `max-open-trades` to -1 - which will assume it to be "unlimited" - and open as many trades as it can based on your stake_amount (this must be fixed, then).

Having `max_open_trades` dynamic as well is not possible.
On top of that, i'm not sure it's a good idea, as it can lead to VERY unbalanced trades.
assuming you got 2 trades a 1000$ each open - and now you switch to more trades, so you start opening 100$ trades - your 1000$ trades will wipe the profits of 10 other trades easily.

If you need to change max_open_trades, best modify the configuration and use the `/reload_conf` option.

i will not consider this as a feature worth having **for now** - unless you can spec it very well (what you aim to do - how to use it) as it can be quite risky for users - and as such, it can lead to a lot of problems when users use it who don't understand the implications.

**Comment by szucsaaron2** [comment]
So let me explain my idea and the scenario where it would have a better performance than a static max_open_trades.
My strategy performs pretty well, it can predict winning trades pretty well, and based on the last 1-month backtesting it made 6500 trades with 60 open trades and from this, there were 500 losses and 600 wins. 
Although what I have observed is that the strategy makes trades in multiple scenarios. 

A: In scenarios when BTC has a big influence and thus generates a ripple effect, thus affecting multiple coins. In this case, my strategy has around 60 open trades. In this scenario, it's generally better to have a higher value for max open trades, as it can have a higher percentage of wins, from all these trades, and it can more or less follow the crypto market, by making positions in such a dynamic market.
B: In other market conditions, where BTC doesn't generate such a ripple effect, other coins also have their separate movement. In this scenario, my strategy usually makes around 5-10 open trades. In this scenario, my strategy also performs pretty well, but the profits are not so high, due to the stake amount being lower because of the high value set in max_open_trades. For example in the last 2 days, I had about 100% profit if I take the cumulative profit for each trade. (Eg. if I have 1 trade with 5% profit, and another trade with 10% profit, the cumulative profit is 15%, I am not sure if this is the correct term for this, but I hope you understand what I mean.)

And another idea which I was thinking about, is that max_open_trades should be based on buy signals, but not like max_open_trades = nr_buy_signals. Rather I was imagining it a way such that, if for example, there are 5-10 buy_signals found, then it would set max_open trades to 20 (a predefined number) and in case there are 30+ buy signals, it would automatically be set to 60-70. The predefined number (a little higher than the true nr of buy signals) would ensure that not all the profits would be wiped, and also that there would be "room" to make more trades from the remaining capital.
This could also be optimized with hyperopt to find the right values for the lower value of max_open_trades, the upper value of max_open_trades, and the condition that determines when should it be switched (eg. dataframe['buy'] > condition).


And this way, a strategy could take advantage of different scenarios, or at least the scenarios that I have given as examples above!

If you have any questions. feedback or you see any flaw in my logic, I am more than happy and grateful to hear from you @xmatthias!

**Comment by xmatthias** [comment]
So basically, what you really want / need is #5076.

We'll surely not do both (they'd conflict with each other) - and i see more flexibility in a dynamic stake approach, than in a dynamic trade slot approach.

**Comment by szucsaaron2** [comment]
Thank you for your response!

So so, but I think at its core the idea that I am suggesting is way simpler. We don't need to rely on TA-lib. I might be wrong on this one, as there might be good uses where TA-lib could give us good indicators on how we should make our positions, but it seems pretty complex to me to determine exactly which indicators could help here. I personally use about 250 indicators, and determining which exact indicator is responsible would require high performance to optimize that. Perhaps with other strategies it might be way simpler.
It also requires rewriting the logic which is used by freqtrade which is probably a pain in the ass, as other classes are probably also be affected by that.
To be honest I am not sure if I only feel this resistance towards the other topic because I don't fully understand it, or because there is something else as well.

On the other hand, I believe that my idea would be way simpler to implement and it could be beneficial. The pseudo-code for implementing it is as follows: 

1. The bot iterates through all the stakes listed on the pair_whitelist (as it already does)
2. Counts the number total number of buy signals ( dataframe['buy'].count() )
3. C: condition, L: Lower max_open_trades value, H: Higher max_open_trades value ( This is just an example, there could be more conditions, and also more values )
4. Decides on max open trades ( if dataframe['buy'].count() > C : max_open_trades = H else: max_open_trades = L
5. Done

This feature would also not require replacing any current feature, just optionally build on top of the current logic and it could potentially increase the performance of strategies. And it's also simple. Optimizing it with hyperopt would also be pretty simple as the number of parameters in the base case is low (only C, L, H).

I think #5076 might be a more advanced solution and you are right, it's also more flexible, but it's also more complex to test and implement.

What do you think about this?

**Comment by xmatthias** [comment]
To me, this will not work, and is taylored to your particular usecase.

Youre assuming that all buy signals happen on the same candle, which is very often not the case (even a delay of one candle will change your impact).
As such, the implementation / logic will fail for 90% of the strategies.

#5076 may seem complex because of the usecase, but using indicators for it is one usecase, you can also use your logic based on buy signals (or something else) to determine the individual stake amount.

As such, i dont see any benefit for this method that would generalize beyond your specific usecase.

**Comment by szucsaaron2** [comment]
I understand, thank you!
