### ISSUE TITLE
Problem running my multi timeframe startegy

### ISSUE THREAD

**Issue by frank01100110** [freqtrade/freqtrade#5114]
I'm trying to run, my multi timeframe strategy, but the bot won't start and it outputs:  `freqtrade.commands.trade_commands - ERROR - unhashable type: 'list'`

It must be something with the config file, the strategy in backtest works.

**Comment by xmatthias** [comment]
The issue template is there to be filled out. If you can't do that, i'll close this issue without further comment.

Also, please include not just the error - but the full exception stack (and a few lines before that as well, ideally).

**Comment by frank01100110** [comment]
> The issue template is there to be filled out. If you can't do that, i'll close this issue without further comment.
> 
> Also, please include not just the error - but the full exception stack (and a few lines before that as well, ideally).

Ok
