### ISSUE TITLE
How do I plot horizontal axes?

### ISSUE THREAD

**Issue by frank01100110** [freqtrade/freqtrade#5116]
How do I plot axes? I'd like to plot horizontal axes for my subplot indicators.

**Comment by xmatthias** [comment]
Everything that's possible is also covered in the [plotting documentation](https://www.freqtrade.io/en/latest/plotting/#advanced-plot-configuration).


If you have further questions like this, please consult the documentation first - and eventually use the [discord channel](https://discord.gg/p7nuUNVfP7) to get support / help from the community.

People there love to help _assuming the documentation has been consulted first_.
