### ISSUE TITLE
Reproducible hyperopt stop to work on some strategies

### ISSUE THREAD

**Issue by Pascal66** [freqtrade/freqtrade#5119]
## Describe your environment (not related to environment)
  * Freqtrade Version: last
  

### Steps to reproduce:

What I can reproduce since 2 ~ 3 weeks :
-downloading fresh strategy CombinedBinHV8
-hypertopt it -> **OK**
-downloading pairs datas
-hyperopt stop to work for a week, trying all possible test for config or command line parameters
-downloading another fresh strategy NostalgiaV3
-hyperopt it -> **OK**
-dowloading pairs data for the last week
-hyperopt stop to work
-erasing all olds hyperopts - olds pairs data
-downloading again pairs-data
- hyperopt for both CombinedBinH and Nostalgia -> **Not working**
- hyperopt Solispis CryptoFrog and some others -> OK each time

Look like this two strategies use a sort of hidden cache preventing hypertopt them again 
:slight_smile: But no, they are basics strat without externals lib or custom things

**Comment by xmatthias** [comment]
with the data / information provided - i'll not be doing any work on this - as you're only saying "it doesn't work - please fix" - without even providing basic logs of the errors.

Obviously i could go and search for these strategies "somewhere" - try to recreate what you're experiencing ... but that means this issue will get the lowest priority, as even trying to analyze it will take quite a long time - which i could spend more productive elsewhere.

---

To get help - Please provide the logs for one (or both if they are different?) of the cases where it's not working - as well as the exact command you're using and the strategy (eventually also hyperopt) code you're using for this.

without that, i'll simply assume it's broken strategies (it works for some strategies - so freqtrade works) - and neither of these is part of the strategy repository - so i don't see why it is something freqtrade can help with.

**Comment by Pascal66** [comment]
I understand, that talking about differents strategies is not the subject here.
I'll continue to investigate why I cant hyperopt some of the only when I download new pairs data.
Sorry

**Comment by xmatthias** [comment]
i think you missunderstood - i don't mind investigating - assuming information is provided to easily recreate a problem - but all you mention is "it does not work" (kindof)- without any exception or what exactly is not working ...

**Comment by Pascal66** [comment]
It's ok, I've explained a lot of time in detail, what doesnt work, what I do, with the help of some nice users on Discord.
Without success, and like you, I've not the time to search more what's happen.
I closed this issue, as I resolved it without using @iterativ strategies :D
