### ISSUE TITLE
Backtesting: Filter for Pairs with TotalProfit/Win%

### ISSUE THREAD

**Issue by cryptomeisternox** [freqtrade/freqtrade#5121]
## Describe your environment
(if applicable)

  * Operating system: Ubuntu SMP
  * Python Version: Python 3.8.5
  * CCXT version: not found
  * Freqtrade Version: freqtrade docker-e2bbc0aa

## Describe the enhancement

Extension for backtesting with additional pairlist filter parameters `--list-total-profit-percent="<0"` or `--list-win-percent=">95"` . The Filter could correspond to the Reportcolumns.

 This filters then outputs a pair list which could be easy transferred into the config as black or white list, depends on Filter.

Outputline could be look like this in den end of the Backtesting Report:

```
list-total-profit-percent: Choosen Pairlist Filter *Total Profit percent* corresponds "<0":
"BNB/BUSD",
"JUV/BUSD",
"OM/BUSD",
"ADA/BUSD",
"PERP/BUSD",
"AERGO/BUSD",
"AUCTION/BUSD"
```

**Comment by xmatthias** [comment]
To be honest, i don't think that'll gain you much (other than over-fitted strategies).

while pairlist selection IS important - throwing all pairs out that don't perform well usually means that your strategy doesn't generalize well, and looks too closely at how past movements played out - and will be thrown off quite quickly by very slight changes in the movements.

---

That said - i'd definitely not want to have this added to the backtesting command (you'll not want to re-run backtesting if you only want to change your filter) - but instead have a "show backtesting result" command (similar to `hyperopt-show`) - which will show / replay the last result (obviously you can then have a `--generate-pairlist --filter-on-whatever` options to output a pairlist if you need that).

it should be quite easy to code / write ... as the methods to load and show results should be there already - so ti's more a question of "tying it all together".

Let me know if you need some help in it (best once there is a basic PR with basic functionality - so it can be discussed on a "per line" basis where there's issues) ...

**Comment by cryptomeisternox** [comment]
This consideration makes sense, a seperates command that displays the pair. 
As for the extension, I'm still researching a bit, but it looks like I'm making good progress. At least I have now found the entry into the Freqtrade development and look what I can do there. Then once a draft exists we can always revise the code accordingly.

**Comment by xmatthias** [comment]
correct. 
to add a new command, you'll want to look at `freqtrade.commands` - as well as `arguments.py`.

Obviously that doesn't cover the command content - but i hope get's you going into the right direction...

**Comment by herculosh** [comment]
at the moment I am so far that I have built the command - this was strate forward. It is currently called backtestig-list I'm not sure yet if it would be better named with backtesting-filter? 
The command content currently reads the json file and reads the trades for the strategy. 
Next i will have to somehow convert this to a dataframe hopefully i will find a suitable prefab method 😉
more about this in the next days.

**Comment by cryptomeisternox** [comment]
at the moment I am so far that I have built the command. It is currently called backtestig-list I'm not sure yet if it would be better named with backtesting-filter? 
The command content currently reads the json file and reads the trades for the strategy. 
Next i will have to somehow convert this to a dataframe hopefully i will find a suitable prefab method 😉
more about this in the next days.
