### ISSUE TITLE
Translating my strategy to hyperopt

### ISSUE THREAD

**Issue by vic9t** [freqtrade/freqtrade#5125]
Hi everyone!

I am trying to translate my strategy into an hyperopt strategy, but I am struggling to understand how to do that.

I am using the latest version of Freqtrade.

My strategy is using specific Moving averages for specific volatility conditions (based on the value of NATR indicator):

              (
                    #Low volatility
                    (dataframe['natr'] <= 1) &
                    (qtpylib.crossed_above(dataframe['LEMAVeryShort'], dataframe['LEMAref']))

                ) |
                    #High volatility
                    ((dataframe['natr'] > 1) &
                    (qtpylib.crossed_above(dataframe['HEMAVeryShort'], dataframe['HEMAref']))
                ),

I would like to optimized the value of the moving averages, but not touching the values for the NATR. My problem is that I haven't found any example of hyperopt strategy with the | logic parameter, nor have I found example with 'hard coded' conditions (like dataframe['natr'] <= 1).

Thank you for your time.
Victor

**Comment by xmatthias** [comment]
Best use the new [inline hyperopt](https://www.freqtrade.io/en/latest/hyperopt/#optimizing-an-indicator-parameter) method - which won't require you to write a seperate hyperopt method - but allows you to use the parameters in your strategy.

It's then more a matter of deciding which parameters you'd like to optimize than how to write it in particular (and no further changes to the strategy are necessary.

i'd recommend to read the full hyperopt page again - as this is something rather new - but simplifies hyperopt a lot.

**Comment by vic9t** [comment]
Thanks Matthias!

I have read the documentation on that but I don't get where to put the def populate_buy_trend of my strategy in the new version. In the legacy version there were a distinction between the two by def buy_strategy_generator which I believe no longer exists. 
Or should I just adapt my def populate_buy_trend with conditions.append() only on the parameters I want to optimize:

    conditions = []
           (
                #Low volatility
                (dataframe['natr'] <= 1) &
                conditions.append(qtpylib.crossed_above(dataframe['LEMAVeryShort'], dataframe['LEMAref']))

            ) |
                #High volatility
                ((dataframe['natr'] > 1) &
                conditions.append(qtpylib.crossed_above(dataframe['HEMAVeryShort'], dataframe['HEMAref']))
            ),

Sorry for the noob question, I just feel stuck on this part...

**Comment by xmatthias** [comment]
there is only one populate_buy_trend - and it's in your strategy.
The key is to using the parameters (IntParameter, ...) - and their values to get hyperopt working correctly.

obviously you can also use the ".append()" syntax for your conditions - but it's usually difficult to build complex conditions with this.

**Comment by vic9t** [comment]
Oh ok! So I don't have to use conditions = [] at all then if I am sure about the structure of my strategy. I can just use the parameters for the EMAs defined in the class like buy_LEMAVeryShort = IntParameter(25, 50, default=25), and then in populate_indicator like this:
for val in self.buy_LEMAVeryShort.range:
            dataframe[f'LEMAVeryShort_{val}'] = ta.EMA(dataframe, timeperiod=val)

And then it should work without changing anything in the strategy?

**Comment by xmatthias** [comment]
the [documentation](https://www.freqtrade.io/en/latest/hyperopt/#optimizing-an-indicator-parameter) explains how to do it ... just read that from top to bottom ... :)
