### ISSUE TITLE
How to disabled info log?

### ISSUE THREAD

**Issue by kamontat** [freqtrade/freqtrade#5127]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I'm not sure is there anyway we can disabled info log? I found that it quite verbose and hidden warning log in the console.

**Comment by xmatthias** [comment]
info log cannot be disabled.

Hiding this would make investigating potential problems impossible - and as such we'll also not be adding this option.
If you find something "really" noisy - let us know, maybe the log-level for that case is wrong ... but in general, the log is intended this way.
