### ISSUE TITLE
Is heartbeat a good indicator to determine how much time my strategy needs to run each cycle?

### ISSUE THREAD

**Issue by szucsaaron2** [freqtrade/freqtrade#5133]
## Your question

Hi!

I read in the documentation that internals.heartbeat_interval controls how frequent bot heartbeat is printed to the console. By default, it's 60 s. In my case, it gets printed about every 4 minutes. Does that mean that a full cycle to analyze all the data needs 4 minutes?

Thank you!
*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
i'd not say that, no.
While it surely isn't normal so your strategy MAY take quite long ... - you can't determine the interval duration for sure from this information.

You can however enable debug logging (`-v` command line switch) which will print a log message at every iteration with "last iteration took ... (s)".
best also use `--log-file <whatevername>.log` so you can open and search through the file - as debug-log tends to be quite verbose - so you'll pretty surely miss the message in the flying by terminal ...

**Comment by szucsaaron2** [comment]
Thank you very much @xmatthias that helped a lot! Seems like my strategy needed 440 seconds ~ 7m, 20 s, which was definitely a bit high for the 5m timeframe.
