### ISSUE TITLE
stake_currency EUR possible with binance?

### ISSUE THREAD

**Issue by gcoskun** [freqtrade/freqtrade#5135]
Hi,
whenever I set the stake_currency to EUR and add BTC/EUR to the whitelist the backtest delivers no trades. When I set the stake_currency to BTC and whitelist e.g. ETH/BTC backtest works. I am using the exact same command to start the backtest. And the same problem occurs also with setting stake_currency to any stablecoin like USDT. What am I doing wrong?

This is the last part of the output

```
===================================================================== STRATEGY SUMMARY ====================================================================
|   Strategy |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit EUR |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |         Drawdown |
|------------+--------+----------------+----------------+------------------+----------------+----------------+-------------------------+------------------|
|      Scalp |      0 |           0.00 |           0.00 |                0 |           0.00 |           0:00 |     0     0     0     0 | 0.000 EUR  0.00% |
|       Zeus |      0 |           0.00 |           0.00 |                0 |           0.00 |           0:00 |     0     0     0     0 | 0.000 EUR  0.00% |
|        wtc |      0 |           0.00 |           0.00 |                0 |           0.00 |           0:00 |     0     0     0     0 | 0.000 EUR  0.00% |
|    Quickie |      0 |           0.00 |           0.00 |                0 |           0.00 |           0:00 |     0     0     0     0 | 0.000 EUR  0.00% |
|       hlhb |      0 |           0.00 |           0.00 |                0 |           0.00 |           0:00 |     0     0     0     0 | 0.000 EUR  0.00% |
|   BbandRsi |      0 |           0.00 |           0.00 |                0 |           0.00 |           0:00 |     0     0     0     0 | 0.000 EUR  0.00% |
===========================================================================================================================================================
```

**Comment by xmatthias** [comment]
most likely, you either have no data (use `freqtrade download-data` to download the corresponding data) - or your stake-amount is wrong (too low for stable coins).

Exchanges apply different limits to different coins. So while you'll be able to trade with 0.01 BTC - you will not be able to trade anything below 15-20$.
As backtesting is using these limits to know if a exchange could be executed, almost certainly all trades will be prevented.
The output per strategy would also contain information pointing to this (containing stake-amount + dry-run-wallet) - to help investigate this problem.


Therefore, simply switching BTC to USDT (or anything else) will not work, but you'll also need to adjust your stake-amount (and eventually stake-currency) to something that fits that currency.

**Comment by gcoskun** [comment]
Thank you very much. That solved my problem.
