### ISSUE TITLE
We need to be able to use in the United States 

### ISSUE THREAD

**Issue by USNeo** [freqtrade/freqtrade#5137]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*

**Comment by xmatthias** [comment]
Freqtrade does not prevent users from anywhere in the world to use it assuming a internet connection (or VPS) is available.

Some exchanges will limit their audience to certain countries - as such, it's up to the user to find an exchange which allows you to use it.
we support multiple exchanges, several of these have seperate "us" entities (ftx.us, binance.us - although binance.us is apparently somehow dodgy - so please do your research).
Other exchanges (kraken, bittrex(?) ) allow users directly onto their exchange.

Some US users also report nice results with kucoin...

As such - it's a question of picking the right exchange - not anything freqtrade would or would not allow you to use.

Best use the [discord channel](https://discord.gg/p7nuUNVfP7) to get support / help from the community, which should be able to point you to good, (hopefully) secure exchanges in the us.
