### ISSUE TITLE
"Using Protections:" message at bot startup omitted in release 2021.5?

### ISSUE THREAD

**Issue by hdkbouma** [freqtrade/freqtrade#5139]
## Describe your environment

  * Operating system: ____ubuntu 20.04
  * Python Version: _____ (`python -V`) 2.7.18
  * CCXT version: _____ (`pip freeze | grep ccxt`) 1.50.91
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  freqtrade develop-42b6d28b
## Your question
In Telegram, is the "Using Protections:" message at bot startup omitted in release 2021.5?
*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
No, if no protection message is sent, i'd assume you don't have them configured.

Best double-check your logs at startup-time for traces of this.

**Comment by hdkbouma** [comment]
Thank you.

**Comment by hdkbouma** [comment]
There was something wrong with the identation in the end of my strategy.
I removed a tab; solved.
