### ISSUE TITLE
Possible issue with freqtrade /forcesell not working + ask_last_balance setting < 1

### ISSUE THREAD

**Issue by seansan** [freqtrade/freqtrade#514]
## Step 1: Have you search for this issue before posting it?

Slack. See below.

## Step 2: Describe your environment

  * Python Version: 275
  * Branch: Develop
  * Last Commit ID: 3b11459a384760e7a4d079e79638158976f9817e
 
## Step 3: Describe the problem:

/forcesell ID not executing sell on existing order. Problem is that forcesell means to *force* a sell. But it does not do this. Orders that are affected have status limit_sell and were tried to sell before but with a partial order. I have "unfilledtimeout": 20, "ask_last_balance": 0.8 .... with these settings it does not cancel the current order, and thus does not create a new (force)sell order. 

The underlying problem seems to be the cancellation after 20 minutes does not occur. And digging deeper it seems ask_last_balance has something to do with it ...... 

Changing ask_last_balance = 1 cancelled the order immediately and created a new sell. (expected)

Only: why does this not occur when ask_last_balance = 0.8 ...... (does ask_last_balance only work for BUY maybe ... something seems wrong here)

![image](https://user-images.githubusercontent.com/652395/36089637-34913ab0-0fdd-11e8-86e1-f38773b671be.png)

### Steps to reproduce:

See above

**Comment by seansan** [comment]
Dupe of https://github.com/gcarq/freqtrade/issues/455

More info in this issue

**Comment by shusso** [comment]
closing for dupe
