### ISSUE TITLE
[BACKTESTING] Different number of trades from backtest and live on same timeinterval

### ISSUE THREAD

**Issue by szucsaaron2** [freqtrade/freqtrade#5141]
## Describe your environment

  * Operating system: Windows Server 2016
  * Freqtrade Version: latest stable
  
## Your question

Hey! :)

I am writing because I don't quite understand the following problem. According to the backtest, for the last 2 days of data, the bot was supposed to make 99 total trades. I was running the bot for the last 2 days also in live mode, but it only made 1 total trade.
I am running my strategy on 5m timeframe, and with the current config, one full cycle to process and analyze all the candle data, it takes about 3 minutes to finish, which should be enough right?
When I checked the FreqUI in the dashboard and looked for the pairs the backtest has listed as past trades for the last 1 day, it didn't show any buy signals, only sell signals.

Thank you for your support, I appreciate the help!

**Comment by barisengez** [comment]
is there any difference between the config.json s you are using for backtest and live?
another thing is to check whitelist on live if those pairs that were traded on backtest are also in whitelist of your live

**Comment by szucsaaron2** [comment]
@barisengez there is no difference, I have used the same config for backtest and live

**Comment by xmatthias** [comment]
Backtesting has access to all of the available data, and can as such have an unlimited lookback (and also look into the future).

live / dry only has something between 400 and 1000 candles (depending on the exchange).

so either your strategy uses too much historic data (looks into the past by more than the candles it's given in live) - or it's using future data (which would show signals - but only appearing after the candle is X  candles old).

**Comment by szucsaaron2** [comment]
I am using a classifier with AI in my strategy, but it's only trained on individual rows of values. In these single rows, I have several indicators, but the max lookback window is 100 for each indicator.  It also doesn't use data from the future, all the indicators are currently from TA, and I also just doubled checked to make sure I didn't make a mistake somewhere.

**Comment by eschava** [comment]
Just a quick idea: doesn't your strategy generate both buy and sell signals for the same bars?

**Comment by szucsaaron2** [comment]
@eschava No, basically the way it works is that it outputs a value between 0 and 1. And then in the populate_buy and populate_sell methods I assign generate buy or sell signals like this: 
```
dataframe.loc[
            (classifier > 0.8),
            'buy'] = 1

dataframe.loc[
            (classifier < 0.6),
            'sell'] = 1
```

As the buy and sell signals are determined based on the single value of the classifier, one candle can't have both buy and sell signals.

**Comment by szucsaaron2** [comment]
I have lowered the confidence interval for the buy signal, and it actually resulted in more frequent buys, but I still find it strange that with a higher number it showed a difference between the live and backtest results. And using a lower value also means making trades that are not so "confident" or less likely to be profitable.

**Comment by xmatthias** [comment]
that suggests that your algo is not just looking at what you think it does, but also at additional data (either more history, or future data).
I'd question every line of code before putting money into this ...

**Comment by szucsaaron2** [comment]
@xmatthias Maybe I don't understand something. Why does it suggest that it also does things that I don't think it does? Why did you come to that conclusion? And why would it use additional data?

**Comment by xmatthias** [comment]
Its your strategy, not mine.
Its a suspicion as its the most likely explanation.

It does happen within your strategy though, so its ultimately your responsibility to know and be sure of.

In theory it can be as easy as a volume.sum() check (or whatever else), which forgets rolling and is therefore using all available lines, which will be different between dry and backtest.

**Comment by BobbyBobbyTheBobBob** [comment]
Here's an idea that helped me greatly. Plot 'classifier' so you see what it is doing. Plot it on the bottom since it is a small value.

Almost surely from your description you'll be surprised by what you see.

**Comment by szucsaaron2** [comment]
@xmatthias Yeah sure, I understand, thanks for the tip, I am looking into the indicators, perhaps there is something going wrong there. 

@BobbyBobbyTheBobBob Thanks a lot mate! I will try and see what happens!

**Comment by BobbyBobbyTheBobBob** [comment]
@szucsaaron2 One more Pro-tip. If you're plotting stuff to see what your indicators are showing, you can skip the backtesting and just replot as you make changes. This saves me probably 30 seconds per iteration.  Also if you have not found it, it's better to throw everything on the plot, you can turn things off in the browser for readability. I guess that's two tips. ;-/

**Comment by szucsaaron2** [comment]
@BobbyBobbyTheBobBob Thank you for the legendary tip!
Plotting just makes things so much easier to analyze, I don't know how I could forget about that...
I think the problem is related to what @xmatthias wrote as well. I am not sure which indicator(s) was the problematic one, but I removed a bunch of them and kept only the most important features that according to my current knowledge should not produce such a data leak.

**Comment by szucsaaron2** [comment]
For example, I have been using indicators such as HT_DCPHASE - Hilbert Transform - Dominant Cycle Phase, HT_DCPERIOD - Hilbert Transform - Dominant Cycle Period, BOP - Balance of Power etc.
From the documentation on TA-lib, they are calculated on (close) or (low, high, open, close). This means that here they are calculated on the whole dataframe which in the case of backtesting would be a lot bigger than on the live and therefore could lead to differences. 
Whereas indicators such as EMA or SMA, or TRIX, and also oscillators are calculated on a given period/window, which probably works better on live trading where we have access to a limited amount of data.
Does this sound like a possible solution to you guys?

**Comment by xmatthias** [comment]
I'm not sure and not quite certain if they really use ALL available data, or if they use a rolling approach (but with a fixed amount) - but if they do, it would be an explanation for sure.

The detail to that would be in the C code of ta-lib ...

if it's a solution or not depends on yourself, considering it's you who opened this issue in the first place :laughing:

**Comment by szucsaaron2** [comment]
I just tested the indicators that didn't have window parameters in their functions and for example, Chaikin A/D Line and Hilbert Transform - Trend vs Cycle Mode, did calculate based on all available data and not using a rolling approach. 

Right now I define the solution that I am looking for as backtesting showing correct results with my strategy :D

I really appreciate all your help and support @xmatthias, you are truly an extraordinary individual who is an expert!
Thank you!

I will keep this issue opened for now until I am finished with testing on production/live mode

**Comment by szucsaaron2** [comment]
@xmatthias After running some tests, I am still at the conclusion that there is something wrong with the backtest.
Now I am using only indicators that are window-based and they are not calculated on the whole dataset.
I ran the backtest for the last 2 days, and it detected 152 trades.
Here is the top of the trades it made with each pair
![image](https://user-images.githubusercontent.com/74426786/122641145-a9465d00-d103-11eb-9bd2-d408738a3220.png)

When I plot my strategy with `from freqtrade.plot.plotting import  generate_candlestick_graph` with the same setting in the strategy, I get the following results:
![image](https://user-images.githubusercontent.com/74426786/122641173-dd218280-d103-11eb-9299-16f35806a953.png)
![image](https://user-images.githubusercontent.com/74426786/122641202-05a97c80-d104-11eb-8eac-2a0f2cc604b9.png)

This continues for more of the pairs listed in the trades generated by the backtest.
As we can observe on the backtest period (6.17. - 6.19.) There were no buy signals found.

Any ideas why this is the case?

**Comment by xmatthias** [comment]
no.
It seems to hint that your strategy is still using some absolute values (either via .iloc / similar, or by using averages/max/ ... over the whole timeframe) ... but it's difficult to tell for sure - and also not something we provide support for.

**Comment by szucsaaron2** [comment]
Thank you a lot @xmatthias!
Indeed you were right! There were some indicators that have the "timeperiod" parameter, but they still produced different results on rolling 500 data and the full database.
