### ISSUE TITLE
Remove useless messages from telegram /logs command

### ISSUE THREAD

**Issue by eschava** [freqtrade/freqtrade#5143]
## Describe your environment

  * Operating system: Raspbian
  * Python Version: 3.8.7
  * CCXT version: 1.51.3
  * Freqtrade Version: develop-ef208012
  
## Your question
Is it possible to filter out useless messages like below from telegram /logs command output? Otherwise, it's hard to see if something important happened recently
I'm talking about messages like
2021-06-16 17:52:34 freqtrade.worker: INFO - Bot heartbeat. PID=31246, version='develop-ef208012', state='RUNNING'
2021-06-16 17:59:57 freqtrade.rpc.telegram: INFO - Executing handler: _logs for chat_id: 265937817

**Comment by xmatthias** [comment]
We'll surely not filter the output for telegram /logs - as that would be highly missleading (one missed filter, and we filter the important info).

You can reduce the number of heartbeats by increasing `heartbeat_interval`.

the "Executing handler" logs are kindof there to let you know something requested info via telegram (should you have a wrong bot configured so someone else has control of your bot) - however i'm not sure about the "real" usage of this - so i won't mind if the log-level of that message is changed to debug (which will effectively hide them from this view).

**Comment by eschava** [comment]
Thanks!
