### ISSUE TITLE
Is it possible to determine inside populate_indicators() if the current pair is in an open trade?

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#5146]
If not it sounds useful. 
* Operating system: Linux
* Python Version: 3.8.5
* CCXT version:  1.51.40
* Freqtrade Version: current devel

**Comment by barisengez** [comment]
maybe this way below? havent tried myself
you will need to iterate on trades and compare with metadata['pair'] probably
and also to prevent call to this get_open_trades method, you might need to store it in a variable and use that one instead. otherwise it would be a huge performance hit i guess

```
from freqtrade.persistence import Trade

trades = Trade.get_open_trades()
```

**Comment by epigramx** [comment]
Oh: true: I forgot that object exists. I'll check it out. 
Yep they're indexed.

**Comment by epigramx** [comment]
> prevent call to this get_open_trades method, you might need to store it in a variable and use that one instead. otherwise it would be a huge performance hit i guess

Wait, why is that @barisengez ?

**Comment by barisengez** [comment]
sorry fixing the sentence as "prevent call to this get_open_trades method **for each and every pair**"
calling it in first pair and storing it in a variable will prevent calling get_open_trades method for each pair. just dont forget to refresh it each candle

**Comment by epigramx** [comment]
> sorry fixing the sentence as "prevent call to this get_open_trades method **for each and every pair**"
> calling it in first pair and storing it in a variable will prevent calling get_open_trades method for each pair. just dont forget to 

It appears that the populate_indicators function is run multiple times (for each pair). What prevents another function called inside it to be called more than once by only being assigned to a variable in there?

**Comment by barisengez** [comment]
if you store two variables like
1. current_candle_datetime (this probably has a variable already somewhere)
2. trades = Trade.get_open_trades()
then you can check if trades is not null and if current_candle_datetime is correct. if both conditions are true, then you dont need to call get_open_trades again and use the variable instead.
it s quite basic actually, i probably confused you with my explanations

**Comment by epigramx** [comment]
Why would it not be null? It would be a new variable assigned in a function that is called again for another pair. I don't get why that would be preferred behavior in the first place since one may want functions to be re-run and variables re-assigned each time in order for each populate_indicators run (each pair) to behave differently (for each pair).

**Comment by barisengez** [comment]
populate_indicators for each pairs will have the same open_trades, so for one cycle
- current_candle_datetime = null
- trades =null
- 1st pair populate_indicators method checks current_candle_datetime and trades are null so populates them by calling get_open_trades
- 2nd pair populate_indicators method checks current_candle_datetime and trades, they are populated and current_candle_datetime is good so doesnt call get_open_trades and just uses trades variable
- same for all other pairs in the same cycle
- next cycle 1st pair checks current_candle_datetime and trades. trades is not null but current_candle_datetime is now past so it calls get_open_trades again and assigns to trades variable plus updates current_candle_datetime
- 2nd pair populate_indicators method checks current_candle_datetime and trades, they are populated and current_candle_datetime is good so doesnt call get_open_trades and just uses trades variable, just as in first cycle

oh btw the variable will not be local in the function, it will be a class global variable. maybe that was the thing that caused confusion?

**Comment by epigramx** [comment]
Yes I realize now you meant a global-scope variable all this time while I was talking about a local scope.

I do get what you mean, even though I think you overstate the performance impact.

**Comment by barisengez** [comment]
i most probably do, but just a concern

**Comment by barisengez** [comment]
What do you think about fetching open orders and just storing the variable in this method? Then you can directly use it in populate_indicator. 
https://www.freqtrade.io/en/stable/strategy-advanced/#bot-loop-start-callback

**Comment by epigramx** [comment]
When it gets to optimizations of that sort (too streamlined), I can't help but wonder if optimizing compilers/interpreters of languages often do it automatically anyway. Some of the smartest people in the world work on them.
