### ISSUE TITLE
asyncio - ERROR 

### ISSUE THREAD

**Issue by graz68a** [freqtrade/freqtrade#5147]
hello

I have seen this in log today
```

freqtrade    | Exception ignored in: <function Exchange.__del__ at 0x7fc2772eb040>
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 162, in __del__
freqtrade    |     self.close()
freqtrade    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 167, in close
freqtrade    |     asyncio.get_event_loop().run_until_complete(self._api_async.close())
freqtrade    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 618, in run_until_complete
freqtrade    |     self._check_running()
freqtrade    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 578, in _check_running
freqtrade    |     raise RuntimeError('This event loop is already running')
freqtrade    | RuntimeError: This event loop is already running
freqtrade    | 2021-06-17 10:00:51,085 - ccxt.base.exchange - WARNING - binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
freqtrade    | 2021-06-17 10:00:51,086 - asyncio - ERROR - Unclosed client session
freqtrade    | client_session: <aiohttp.client.ClientSession object at 0x7fc270d687c0>
```
I'm lost , anyone can tell me how to fix this ?
Thank you

**Comment by barisengez** [comment]
asking just out of curiousity 
- have you changed `process_throttle_secs` by any chance?
- is it possible that your CPU or RAM is overloaded?

**Comment by graz68a** [comment]
no I didn't change it.
Regarding CPU I receive this everytime I start the strategy

freqtrade    | 2021-06-17 11:58:15,971 - numexpr.utils - INFO - Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
freqtrade    | 2021-06-17 11:58:15,972 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.

**Comment by graz68a** [comment]
BTW   RAM used is 240 MB and cpu usage is about 11% , no overload

**Comment by graz68a** [comment]
I closed the strategy I rebooted PC and restarted everything , the asyncio  error stopped.

**Comment by barisengez** [comment]
i should ve asked this first instead :)

![image](https://user-images.githubusercontent.com/18678845/122415199-00272780-cf88-11eb-8368-a228a5f65745.png)

**Comment by xmatthias** [comment]
it's a rather strange error - as the exception itself occurs if you try to start a nested asyncio loop (which freqtrade is not doing).
Now the log indicates that somehow the exchange class has been deleted - which usually only happens when you stop freqtrade (or use `/reload_conf`).
In neither of the cases it should be a problem ... but i'm yet to encounter this myself, so i'm pretty ... unclear what's causing this.

**Comment by lazydroid** [comment]
@xmatthias i regularly get this "this event loop is already running" error when I `/reload_config` using the telegram.

**Comment by rlanyi** [comment]
@xmatthias I have the same issue as @lazydroid , every time I `/reload_config` via telegram or run `python3 scripts/rest_client.py reload_config` I get the following. Using `develop` branch (commit `fbd64d7`).

```
Exception ignored in: <function Exchange.__del__ at 0x7fc824baa9d0>
Traceback (most recent call last):
  File "/home/user/freqtrade/freqtrade/exchange/exchange.py", line 169, in __del__
    self.close()
  File "/home/user/freqtrade/freqtrade/exchange/exchange.py", line 174, in close
    asyncio.get_event_loop().run_until_complete(self._api_async.close())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 618, in run_until_complete
    self._check_running()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 578, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
2021-12-05 22:05:35,286 - ccxt.base.exchange - WARNING - binance requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add exchange.close() to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
2021-12-05 22:05:35,286 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fc865e62d00>
```

Is it possible to reopen this issue or should I create another one? Thank you!

**Comment by stash86** [comment]
This is a normal error that can be ignored

**Comment by xmatthias** [comment]
If it is creating a problem, best open a new issue, describing also the consequences of this (i don't know of any).

In general though, i agree with @stash86, while it might be annoying, it's usually not causing a problem, at least not in cases i've observed so far.
