### ISSUE TITLE
CooldownPeriod for Both Buying and Selling

### ISSUE THREAD

**Issue by BobbyBobbyTheBobBob** [freqtrade/freqtrade#5148]
Hello, I'm new here and hope I'm doing this right.

I think a good feature to add would be creating a CooldownPeriod after buying as well as selling. I have a problem that after a big move there's a consolidation period that really is not profitable and often I lose a bit of ground. I want to buy the dip but not sell during consolidation.  I'd like to tell it to wait for a bigger move up (or down) before you waste fees trading. 

Also this might help people transition from dry-run mode to live if they could 'rate limit' the bot. 

-- So What Can I do To Help --

I would fork the repro and try to do it myself but I'd probably waste your dev team's time with a flawed pull request.

I would be willing to hire someone off upworks to do it if that helped the dev team.

Or I'd rather tip this dev team instead. If there's a patron or a btc address, I'd gladly support this.

Or maybe in true btc sprit, I could send someone two large pizzas. ;-)

Thanks for a great product and your consideration. 

(Also I searched for dupes and did not see any, if I missed it, apologies)

**Comment by barisengez** [comment]
i ll leave the cooldownPeriod comments to more experienced but here is the lead developer's page in case you want to sponsor
https://github.com/sponsors/xmatthias

**Comment by BobbyBobbyTheBobBob** [comment]
Awesome. I'll send some btc when I get to that computer. Thanks

**Comment by BobbyBobbyTheBobBob** [comment]
Thanks barisengez I sent 50 bucks and if my Strat does what it should, I'll send 10x that.

**Comment by xmatthias** [comment]
To be honest, from the above i'm not sure what you need / want exactly - but assuming i understood it (somehow) correctly - (please correct me if i'm wrong) - i don't think any change to freqtrade itself is necessary - but rather some ideas on how to implement this in your strategy with the available means - so for now, i'll treat this as question (should the below not get you what you need, please specify your requirements in more detail).

Cooldown period is there to prevent rebuying a pair immediately, which means Freqtrade will not buy the same pair again for the duration of this cooldown period.

"preventing" sells after the buy will depend on what your sell-signal / signals are - but might be dangerous for "crash" situations.

* For (static) stoploss - that's a no-go to me. It's there to protect your assets - so having it "not trigger" for the first 10 minutes (or however long) can result in serious losses (although you can also achive this with some of the below methods).
* for sell / roi / trailing stop - i would think that some combination of [custom-sell](https://www.freqtrade.io/en/latest/strategy-advanced/#custom-sell-signal), [custom-stoploss](https://www.freqtrade.io/en/latest/strategy-advanced/#custom-stoploss) and [exit-confirmation](https://www.freqtrade.io/en/latest/strategy-advanced/#trade-exit-sell-order-confirmation) will get you what you need - in a pretty flexible way.

Combining the different samples that are on this page (for example [time based stop](https://www.freqtrade.io/en/latest/strategy-advanced/#time-based-trailing-stop)) into the exit-confirmation should get you as much or little sell-protection as your strategy requires / needs.

Now personally, i'd exclude stoploss (maybe also trailing stop) from the exit-confirmation (always confirm these types) - but in the end, it's up to you to take this decision...

**Comment by BobbyBobbyTheBobBob** [comment]
Well, before your answer I thought I had read every page of the docs three times. But I missed the time based stoploss. Perhaps since somewhere you (or the writer) suggested a custom stoploss wasn't the best practice so I skipped over it. 

Nonetheless, it looks like a time bases stoploss will indeed give me the functionality I need and more. 

Many thanks

**Comment by xmatthias** [comment]
hah yeah -  docs are ... quite extensive - so it's sometimes hard to find the "right spot" :laughing:

**Comment by BobbyBobbyTheBobBob** [comment]
After noodling this thru it's not want I was looking for but I guess that's no big deal...

I guess one way to say what I'm looking for is 'ignore sell signal for n minutes.'   Now that's not to say a Stoploss or ROI or other condition could not override that... but to ignore my populate_sell_trend.

I'm pretty good at detecting when to get in and out but after I jump in I get 'false positives' to sell during consolidation.  I want to buy at the bottom but 'snooze' the sell signal for some time until the price climbs.

The use case is: Imagine the price drops and bounces off a lower level a few times before a true trend reversal.  I want to buy at the first floor but not sell on a mini bounce but to wait for the trend to reverse.

For me at least, finding the first bounce off the floor is fairly easy, finding -the last one- is impossible.

I can use a custom sell and wait for % profit to simulate it but it's not the same logic.  Can I do a time based custom sell? I could set that unrealistically high for n minutes.

thanks

**Comment by xmatthias** [comment]
if your sell-signal is kindof ok (you can rely on it after X minutes) - maybe look at `confirm_trade_exit()`.

Returning False will "prevent" the signal from being acted on - so you can filter on Sell signal reasons - and check how long the trade has been opened before "accepting" your sell signal.
while it'll be a bit noisy in the logs, it'll do exactly what you need if implemented correctly.
