### ISSUE TITLE
Hyperopt-list and Hyperopt-show crash WSL 2 Backend

### ISSUE THREAD

**Issue by wingchangwow** [freqtrade/freqtrade#5149]
## Describe your environment

  * Operating system: windows 10 w/ Docker
  * Python Version: Says not found, but everything works so I definitely have it. My guess is 3.8 (`python -V`)
  * CCXT version: Also not recognized (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2-21.5 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

So I've tried to do this on a linux virtual machine, as well as on my windows 10 machine using Docker. After running hyperopt on a strategy optimizing for sharpe ratio, I try to look through other results that were found by using the hyperopt-show and hyperopt-list commands, but after about a minute on the virtual machine it just prints the message "Killed", or on Windows 10 
I get "Windows named pipe error: the pipe has been ended. (code: 109)" as well as a windows notification saying that The WSL 2 Backend has stopped unexpectedly. This happens every time without fail, and I'm unable to view my hyperopt results.

### Steps to reproduce:

  1. Run hyperopt with a strategy optimizing for Sharpe ~5000 epochs
  2. When done, run hyperopt-list or hyperopt-show command
  
### Observed Results:

  * What happened?
  Process killed, or WSL 2 Backend Crash

  * What did you expect to happen?
  I expected to see my hyperopt results

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

Linux: "Killed".

Windows 10 w/ Docker: "Windows named pipe error: the pipe has been ended. (code: 109)"
Windows 10 Notification Popup: "The WSL 2 Backend has stopped unexpectedly."

**Comment by xmatthias** [comment]
best check how big the latest file in `user_data/hyperopt_results` is.

with 5000 epochs, it might get pretty large - so most likely, your pc is running out of memory...

**Comment by xmatthias** [comment]
Without further information, there is nothing we can do to support or investigate.

I hope this means that you were able to solve this issue - if not feel free to comment below / reopen with the information requested above.
