### ISSUE TITLE
Need assistance setting up freqUI with docker

### ISSUE THREAD

**Issue by r3nd4n** [freqtrade/freqtrade#5151]
Do you guys have step by step guide on how to run freqUI with docker? 
I just cant get it right 
Im with docker and VSCode

Thanks

**Comment by BobbyBobbyTheBobBob** [comment]
https://www.freqtrade.io/en/stable/docker_quickstart/

You could not ask for better docs.

Ya might just bookmark that site. You'll be there a lot after you get it running.

**Comment by r3nd4n** [comment]
Is it for FreqUI?

**Comment by xmatthias** [comment]
FreqUI is included in the docker images - so you can simply follow the documentation for [configuration with docker](https://www.freqtrade.io/en/stable/rest-api/#configuration-with-docker).


For next time - please get used to filling out the issue template - while it may not seem relevant to you, it might be (maybe you're on a version that doesn't have the UI yet?) ...

**Comment by dominiclapointe** [comment]
Sorry to jump on this closed one, felt better than opening the another one with the same issues.

I am using freqtrade docker (docker-compose) v2021.6 on windows 10.

Here is my docker-compoe file 
```
---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    ports:
      - "8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
```

and the config.json 
```
"telegram": {
        "enabled": true,
        "token": "1872073138:AAFmC3v30Cn8JcuuC7u3QqhmFuK7USdpaGs",
        "chat_id": "1847594530"
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": true,
        "jwt_secret_key": "8e06d93d232ebec883d7aa96b1f29b5a3a70a48ac6253ac63650f7d48c1e59f3",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "!Q2w3e4r5t"
    },
```

It seem that FreqUI is started and running as i can see in the log

> 
> 2021-07-12 20:05:38,458 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.api_server
> 2021-07-12 20:05:39,442 - freqtrade.rpc.api_server.webserver - INFO - Starting HTTP Server at 0.0.0.0:8080
> 2021-07-12 20:05:39,443 - freqtrade.rpc.api_server.webserver - WARNING - SECURITY WARNING - Local Rest Server listening to external connections
> 2021-07-12 20:05:39,443 - freqtrade.rpc.api_server.webserver - WARNING - SECURITY WARNING - This is insecure please set to your loopback,e.g 127.0.0.1 in config.json
> 2021-07-12 20:05:39,443 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.
> 2021-07-12 20:05:39,483 - uvicorn.error - INFO - Started server process [1]
> 2021-07-12 20:05:39,487 - uvicorn.error - INFO - Waiting for application startup.
> 2021-07-12 20:05:39,487 - uvicorn.error - INFO - Application startup complete.
> 2021-07-12 20:05:39,489 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)

but i keep getting connection refused with hitting http://127.0.0.1:8080...

Anyone can help?

Thank you

**Comment by xmatthias** [comment]
you'll need to be careful to use `docker-compose up -d` to start the container, and not `docker-compose run`.
Run is designed for "one-off" commands and will ignore certain parts of the dockerfile.

**Comment by aaronwbrown** [comment]
I am encountering this same error. 

Is frequi using Nginx as a web server? I get the Nginx splash page when navigating to 127.0.0.1:8080, but when I navigate to `/api/v1/ping`, I get an error stating the server returned no data. 

I checked to see if anything else was running on the port, but all I have is my docker process as expected. 

```
sudo lsof -i:8080                                                                                                                                                                                                                                                                             
COMMAND   PID       USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
com.docke   548     aaron  100u  IPv4 0x2af685b56f62dbd9      0t0  TCP localhost:http-alt (LISTEN)
```

Any assistance, or debugging paths are much appreciated. 👍

**Comment by xmatthias** [comment]
Freqtrade is not using nginx unless you're using the freqUI image (which you really shouldn't as there's no point anymore).

As such - you're connecting to "something" else.
please note:
While you THINK it's the same prolem, it really isnt, and is specific to errors in your configuration . Attaching yourself to this issue will ping everyone else, while they'll not be interrested in your issue.
As such - please open a new issue, filling out the information requested - so we can try to assist you properly.
