### ISSUE TITLE
Telegram group

### ISSUE THREAD

**Issue by graz68a** [freqtrade/freqtrade#5153]
Hello

could it possible have a Telegram group for freqtrade users ?

Thanks for considering.

**Comment by robcaulk** [comment]
My opinion would be no - the community is focused on discord already - no reason to split it in two.

**Comment by xmatthias** [comment]
The quick / short answer is no.

We have a [discord server](https://discord.gg/p7nuUNVfP7) that's quite active, as well as a slack community (which is not very active anymore).
As such - i'll surely not open a 3rd platform (letalone that telegram groups will get very messy once you reach a certain level.
