### ISSUE TITLE
freqtrade keeps crashing on vps after a few minutes, whenever hyperopt is run.

### ISSUE THREAD

**Issue by JasonObihara** [freqtrade/freqtrade#5154]
## Describe your environment

  * Operating system: _linux vps___
  * Python Version: _____ (`python -V` 3.8)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version:  latest dev____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*
Hyperopt continues crashing when run on vps. I upgraded to 2 core cpu, 80gb ssd, 4gb ram, 3tb bandwidth. The problem remains. Attached error report.

+--------+---------+----------+------------------+--------------+------------------------------+-----------------+------------------------------+-------------+
|   Best |   Epoch |   Trades |    Win Draw Loss |   Avg profit |                       Profit |    Avg duration |                 Max Drawdown |   Objective |
|--------+---------+----------+------------------+--------------+------------------------------+-----------------+------------------------------+-------------|
| * Best |   1/100 |    18769 |  11763 4718 2288 |        0.01% |    0.01916145 BTC    (0.00%) | 0 days 11:11:00 |   0.42080479 BTC (4,203.84%) |     50.0161 |
| * Best |   2/100 |     9757 |   4545 4675  537 |        0.13% |    0.12469927 BTC    (0.01%) | 0 days 13:05:00 |   0.28647067 BTC (2,861.84%) |    -7.68279 |
| * Best |   6/100 |    20507 |   8247 9312 2948 |        0.12% |    0.23778456 BTC    (0.02%) | 0 days 11:14:00 |   0.39343894 BTC (3,930.46%) |    -9.45348 |
 [Epoch 6 of 100 (  6%)] |█████|                                                                                              | [ETA:   0:52:25, Elapsed Time: 0:03:20]
2021-06-18 23:48:59,914 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/root/freqtrade/freqtrade/commands/optimize_commands.py", line 86, in start_hyperopt
    hyperopt.start()
  File "/root/freqtrade/freqtrade/optimize/hyperopt.py", line 437, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/root/freqtrade/freqtrade/optimize/hyperopt.py", line 350, in run_optimizer_parallel
    return parallel(delayed(
  File "/root/freqtrade/.env/lib/python3.9/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/root/freqtrade/.env/lib/python3.9/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/root/freqtrade/.env/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}
(.env) root@dsquantsFreqtrade:~/freqtrade#

**Comment by xmatthias** [comment]
the error-message is pretty clear - it's running out of memory.

Best read the relevant [documentation page](https://www.freqtrade.io/en/stable/hyperopt/#out-of-memory-errors) on how to approach this. 
Depending on the parameters you use, it's most likely simply undersized for the task at hand. 4GB is almost nothing for hyperopt unless you heavily limit pairlist and timerange, or run on a pretty large timeframe.

**Comment by JasonObihara** [comment]
Thanks xmatthias,
Makes sense, it got me looking into main.py file and other stuff.
