### ISSUE TITLE
Support cudf or Modin to improve HO performance

### ISSUE THREAD

**Issue by nuaimat** [freqtrade/freqtrade#5158]
## Describe the enhancement

*Explain the enhancement you would like*
reading https://developer.nvidia.com/blog/pandas-dataframe-tutorial-beginners-guide-to-gpu-accelerated-dataframes-in-python/ seems that for people who own a Cuda  supported GPU, there's a huge performance gain if freqtrade can use cudf as an alternative to pandas dataframe. 

other topic discussing Pandas vs cuDF vs Modin is also here: 
https://towardsdatascience.com/faster-pandas-with-parallel-processing-cudf-vs-modin-f2318c594084 
and it seems there's a huge potential benefit to performance, especially during HO

**Comment by xmatthias** [comment]
GPU acceleration will not help you as much as you think, as it will not work for 90% of the indicators.

It's assuming (the tutorial and your proposal) that the calculations will be done by pandas - however most indicators used in samples / strategies are done either via ta-lib - or via other libraries - so to even try to support this, you'd first have these dependent libraries support this.

As such - the benefit will not justify the complexity introduced.

--- 

For hyperopt - we're using scikit-optimize, which is built on top of scikit-learn.

Their statement about GPU support is [pretty clear](https://scikit-learn.org/stable/faq.html#why-is-there-no-support-for-deep-or-reinforcement-learning-will-there-be-support-for-deep-or-reinforcement-learning-in-scikit-learn) - so if you need GPU support, best go there and convince them to implement GPU support - but i see chances about that as pretty low - as i'm pretty certain others have tried and did not succeed (although i didn't search through their issue tracker).

It would also not help you near as much as you think.
Everyone hears "for ML, you need to use GPU" - but when you look into it - the usability of GPU's is limited to a very small usecase, where you're doing number-crunching only.
For hyperopt, we need the possibility to run python code (backtesting) there - which is not possible as far as i know.
As such - the speed increase for it would be almost 0.

**Comment by nuaimat** [comment]
The scikit-optimize lack of GPU is totally valid, and I am satisfied and thankful for your answer, but FYI I used https://github.com/twopirllc/pandas-ta in different projects, which seems like a good alternative to TA and is built on top of Pandas (hence it can be used with cuDF).  it might be something to consider for the future.

**Comment by xmatthias** [comment]
Nothing prevents you from converting the dataframe to some other dataframe and use that in your strategy as long as you convert it back to a dataframe before returning from the function.

It's however a very edge-case usecase to me - and one that's only really relevant if you use 1000ds of indicators.
