### ISSUE TITLE
maximum drawdown percentage seems to be cumulative drawdown

### ISSUE THREAD

**Issue by pascal00d** [freqtrade/freqtrade#5167]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: 3.8.5
  * CCXT version: 1.51.3
  * Freqtrade Version: develop-4512ece1
  
## Your question

In the documentation, explanation for drawdown seems correct, but in the backtesting summary metrics drawdown percentage seems to be cumulative drawdown, not not maximum drawdown.

*Drawdown: Maximum drawdown experienced. For example, the value of 50% means that from highest to subsequent lowest point, a 50% drop was experienced).*

| Starting balance      | 500.000 USDT        |

**| Drawdown              | 48.06%              |**
| Drawdown              | 339.300 USDT        |
| Drawdown high         | 1826.923 USDT       |
| Drawdown low          | 1487.623 USDT       |

Result for drawdown percentage should be : Drawdown / (Starting balance + Drawdown high) = 14,58%

**Comment by xmatthias** [comment]
Relative Drawdown is % of average Stake amount - not absolute drawown - so the 48% (with 339 USDT) suggests you've had an average stake-amount of ~700 USDT.

One can argue if the calculation is correct or wrong ... for relative values, it's always the relation that counts (% of what) - which makes implementation often subjective.

While you do provide a formula - is there an official source (links, etc.) that this is how drawdown should/ must be calculated or is defined - or is it how you think it should be?

**Comment by pascal00d** [comment]
I'm not sure if there is an official definition, but I found definitions like this:
[Maximum Drawdown (MDD) Definition](https://www.investopedia.com/terms/m/maximum-drawdown-mdd.asp)

So after your message i tried to use the % of average Stake amount, instead of the % of the peak value, but i didn't get the same result as you.

% of the peak value => -15%
![image](https://user-images.githubusercontent.com/50653843/123117903-732a1580-d442-11eb-9a6c-cb05bd988bed.png)

% of average Stake amount => -70%
![image](https://user-images.githubusercontent.com/50653843/123118013-8f2db700-d442-11eb-9f59-f107812787a1.png)

"_so the 48% (with 339 USDT) suggests you've had an average stake-amount of ~700 USDT._"
Avg. stake amount is 481.418 USDT, so drawdown (339 USDT) is not 48% of Avg. stake amount.

```
=============== SUMMARY METRICS ===============
| Metric                | Value               |
|-----------------------+---------------------|
| Backtesting from      | 2021-02-01 00:00:00 |
| Backtesting to        | 2021-03-01 00:00:00 |
| Max open trades       | 3                   |
|                       |                     |
| Total trades          | 189                 |
| Starting balance      | 500.000 USDT        |
| Final balance         | 2508.333 USDT       |
| Absolute profit       | 2008.333 USDT       |
| Total profit %        | 401.67%             |
| Trades per day        | 6.75                |
| Avg. stake amount     | 481.418 USDT        |
| Total trade volume    | 90987.985 USDT      |
|                       |                     |
| Best Pair             | RVN/USDT 76.11%     |
| Worst Pair            | XRP/USDT -36.42%    |
| Best trade            | RVN/USDT 46.82%     |
| Worst trade           | XRP/USDT -36.42%    |
| Best day              | 404.109 USDT        |
| Worst day             | -265.558 USDT       |
| Days win/draw/lose    | 24 / 0 / 4          |
| Avg. Duration Winners | 4:11:00             |
| Avg. Duration Loser   | 15:29:00            |
| Zero Duration Trades  | 0.00% (0)           |
| Rejected Buy signals  | 515132              |
|                       |                     |
| Min balance           | 441.147 USDT        |
| Max balance           | 2773.890 USDT       |
| Drawdown              | 48.06%              |
| Drawdown              | 339.300 USDT        |
| Drawdown high         | 1826.923 USDT       |
| Drawdown low          | 1487.623 USDT       |
| Drawdown Start        | 2021-02-23 14:55:00 |
| Drawdown End          | 2021-02-24 03:45:00 |
| Market change         | 76.02%              |
===============================================
```

Do you have the detail of your calculation of drawdown % ?
I am interested in understanding your view on this subject.

**Comment by pascal00d** [comment]
With the following modification I get the same result as on my graph:

/home/pascal/freqtrade/freqtrade/optimize/optimize_reports.py:
```
    try:
        #max_drawdown, _, _, _, _ = calculate_max_drawdown(
        #    results, value_col='profit_ratio')
        drawdown_abs, drawdown_start, drawdown_end, high_val, low_val = calculate_max_drawdown(
            results, value_col='profit_abs')
        strat_stats.update({
            #'max_drawdown': max_drawdown,
            'max_drawdown': drawdown_abs / (starting_balance+high_val),
```

On the following 2 screenshots, I am comparing a strategy with max_open_trades=1 and =2.

First, initial code, 2 drawdowns in yellow looks similar:
![image](https://user-images.githubusercontent.com/50653843/123139041-0caef280-d456-11eb-9662-9d4dc7d33d87.png)

Second, modified code, 2 drawdowns in yellow clearly shows that the strategy with max_open_trades=1 carries a greater risk of drawdown
![image](https://user-images.githubusercontent.com/50653843/123139197-3d8f2780-d456-11eb-8ec7-85b0b6c89c68.png)

But maybe it's not that simple and I missed something.
What is your opinion ?

**Comment by moinonin** [comment]
I have also been thinking that drawdown calculation could get better. In the current form it assumes that you are opening only one position throughout, or at least for it to make sense. I believe it should be aggregated (averaged by the maximum number of positions). This will cause less damage since it will still imply it's current form when a max_open_positions=1.

**Comment by Fimap9to1** [comment]
Hello, anybody have the formula of drawdown % calculation as it is used in backtest? Thanks in advance!

**Comment by pascal00d** [comment]
You will find the formula of drawdown % calculation as it is used in backtest in function "calculate_max_drawdown":
https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/data/btanalysis.py

But like I said above, I don't think the current calculation is the most relevant.

**Comment by Fimap9to1** [comment]
Thanks, I'll look at it!

**Comment by alexpunct** [comment]
Hello, any update on this?
