### ISSUE TITLE
Change Strategy by Telegram bot

### ISSUE THREAD

**Issue by Majid-Mahzarnia** [freqtrade/freqtrade#5171]
Hi,
Since the market is too sensitive and unstable, I need to make some different strategies and use them as fast as I can when the market behavior changed. I need to "Change Strategy" tool in telegram to list all my pre-defined strategies and re-run docker container with using selected the. strategy .
Thanks

**Comment by xmatthias** [comment]
You can change the strategy in your configuration and use the "/reload_config" telegram command.

We will however not implement a "change strategy" command - as telegram can't know valid strategy names, and a invalid strategy name (or a problem with loading that strategy) would stop the bot.

For future requests: You should work on your tone and consider the audience you're opening an issue with.
Your tone might work for a support location of a company you're paying money to, however, you're not paying to use freqtrade - as such you should be asking for things - not demanding for things (which "i need" implies).

**Comment by Majid-Mahzarnia** [comment]
Dear xmatthias ; 

Hello again and many thanks for information,
Firstly I'm so sorry for my bad English , as English is not my mother tongue and I'm a newly English speaker, I'm trying learn more and more. I hope I'll improve it soon to eliminate such problems, and I do appreciate your help and notice in terms of my bad tone .  I'll improve it soon. I know you and other guys here help people and its not a support group. I'm not demanding to do something or ... I just asked if its possible to make it in telegram or no.

About changing strategy tool in telegram, it's correct  I have to change it from my machine but in some cases when the market behavior changed in a blink of eyes, we need to change our strategy to prevent more loss, and in this situation each second is equal some lost. that's why I thought it could help anyone to make and use pre defined strategies from telegram.

More over, I'm a little bit familiar with python, please let me know if I can help this project to improve it.

Thank you

**Comment by xmatthias** [comment]
For sure, helping out is always apreciated.
We've got quite some open issues - i'd recommend to start with the "good first issue" labeled ones - as these are usually confined to just a few files - and won't require broad knowledge of the freqtrade codebase.
