### ISSUE TITLE
Option for Binance futures 

### ISSUE THREAD

**Issue by Jacksparrowoo1** [freqtrade/freqtrade#5173]
Is is possible to trade in Binance futures ,may be in future update. 
If it is possible then it would be great because not every time market is in uptrend or a bull run.
Trend following strategies perform better in up trending market situation. and full 24hrs of a day can be utilized by the Bot

**Comment by xmatthias** [comment]
Please use the search to find duplicate issues before posting new ones.

Duplicate of #2312, #902 and partially #2183.

**Comment by samgermain** [comment]
Working on it, #5157 

If you would like to contribute to the implementation, message me on discord samwow#2769
