### ISSUE TITLE
Add the percentage of the day in daily RPC telegram

### ISSUE THREAD

**Issue by TheForgotten69** [freqtrade/freqtrade#5175]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

It would be a nice to have, when doing the `daily` command in the freqtrade telegram part, to have the breakdown of the % change associated.

For instance, currently it's like this 
Day         Profit USDT    Profit EUR    Trades
----------  -------------  ------------  --------
2021-06-23  0.321 USDT     0.270 EUR     1 trades
2021-06-22  -14.923 USDT   -12.524 EUR   3 trades
2021-06-21  -13.039 USDT   -10.943 EUR   7 trades
2021-06-20  -23.322 USDT   -19.574 EUR   4 trades

it could be that now
Day         Profit USDT    Profit EUR    Trades
----------  -------------  ------------  --------
2021-06-23  0.321 USDT     0.270 EUR     1 trades (0.03%)
2021-06-22  -14.923 USDT   -12.524 EUR   3 trades (-5.03%)
2021-06-21  -13.039 USDT   -10.943 EUR   7 trades (-4.48%)
2021-06-20  -23.322 USDT   -19.574 EUR   4 trades (-7.85%)

**Comment by xmatthias** [comment]
The big problem with relative values is - you need some value the % refers to (a base for the relative calculation).

I'd not know what value this should be based on for daily so it isn't wrong in certain cases - as we don't keep "regular" balance snapshots - and even that would not guarantee correct results - depending if other dependent values (like tradable-balance) changes.

**Comment by TheForgotten69** [comment]
Yes, it's not possible to have the percentage when the balance is changed externally. But as we keep the trades and their results in the DB, I'm guessing here as I'm not familiar with the backend here, we can calculate the percentage only with what has been done that day relative to the previous one. That way each day only has a d-1 dependency.

We don't keep the regular balance snapshot but do we have the first balance before any trades? If yes, we can have a mean to have this information or is there other cases that would not fit this?

**Comment by xmatthias** [comment]
you can use "now" balance subtracting all absolute profits/losses to get to the starting balance.

For dry-run - it's configured so it's known.
However, it's unrealistic to assume that freqtrade gets to control the full account. This might be your usecase, but will result in broken calculations for many others (i can have a 10.000$ account, but only allow freqtrade to trade 1000$ of these by setting static stake amounts).

In the above case, all % gains would show up as "nonexistent" - as there's a difference if you make a 100$ gain on a 1000$ account, or on a 10.000$ account.

That said - i'm happy to accept a well done PR if you think you can find a way / formula to account for these problems and have it reliably be correct.
i haven't so far, and as such, will not be adding % gains to the /daily command - as it's better to not show information than to show wrong information.

**Comment by bibinvargheset** [comment]
Freqtrade can log the stake amount set from time to time for the particular bot and then use XIRR https://corporatefinanceinstitute.com/resources/excel/functions/xirr-function/ and display it as XIRR rather than percentage. the normal way is to be on daily baisis for mutual funds  but i think for crypto we need time based XIRR

**Comment by xmatthias** [comment]
@bibinvargheset the resource above does only use the excel function, but does not provide the underlying formula or calculation - as such, it's worthless for this project.

Feel fee to make a PR if you think you can solve this - tips on how to approach this (without logging unnecessary and potentially wrong data) are provided in the comment above (https://github.com/freqtrade/freqtrade/issues/5175#issuecomment-867336570).

**Comment by bibinvargheset** [comment]
I was not telling to integrate excel, to have a accurate represtation of percentage , we can use XIRR method like amount invested and time iin market to averge for the particular bot if the funds are ammended by adding more deposits or changinh stake amount other than the trade profit.

**Comment by xmatthias** [comment]
I am not doubting that - but the resource does not provide the formula - only shows how to USE the excel function - which makes it irrelevant.

**Comment by bibinvargheset** [comment]
The concept is time averages returns, this is the releavent metric for multple investmets  https://www.quora.com/What-is-the-mathematical-formula-to-calculate-XIRR
