### ISSUE TITLE
Create limit sell order for ROI price

### ISSUE THREAD

**Issue by eschava** [freqtrade/freqtrade#5176]
## Describe the enhancement

I think it would be useful if freqtrade will create (and update if needed) a limit order for ROI price. In this case, it could be fulfilled even if such a price happens inside a candle and isn't visible to the bot

**Comment by xmatthias** [comment]
I think this is based on a misunderstanding on how ROI / stoploss checking works.

Freqtrade checks for roi and stoploss every ~5 seconds (or whatever you set as your `throttle_process_secs`).
As such, intra-candle data is available during live / dry ... candle values / limitations as such do not apply to neither ROI nor stoploss (outside of backtesting, obviously).

Therefore, I don't really see a point in placing a sell-order right away - as it will lock up your funds.
The problem this creates is that in case of a crash / stoploss - you'll be a lot slower to place a stoploss as you first have to cancel the existing order to free the funds - to then place the sell order for loss (which in the worst case, is now for a bigger los as you're half a second (at least 1 rate-limited request) later.

**Comment by eschava** [comment]
Thanks. That sounds convincing :)

**Comment by eschava** [comment]
I think this still can work with exchange stop orders if the sell limit order is created as OCO (at least for binance)
