### ISSUE TITLE
bot_loop_start() is not run only once

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#5181]
If this isn't a bug: it appears counterintuitive in the way it works compared to its docs' description. The issue is that it can re-run on live before the software goes through the entire whitelist (e.g. bot_loop_start() may be re-run if the software sells a pair in the middle of the whitelist).
If it is intended: it's counterintuitive: it breaks methods that would rely on it running only before all pairs in the whitelist are processed once for each candle (e.g. a global variable may be re-set in bot_loop_start() that should only be re-set once for each candle).

  * Operating system: linux (dedicated)
  * Python Version: 3.8.5
  * CCXT version: 1.51.77
  * Freqtrade Version: current dev

**Comment by xmatthias** [comment]
The method is called (and documented) to be "bot loop start" - which means, it'll run once every "process_throttle_secs" (every bot loop)..

Based on the description, it sounds like you're using `process_only_new_candles=True` - which limits pair analyzing to once per candle (which can make sense for most strategies).

This setting has however no effect on `bot_loop_start()` (neither should it, in my opinion) - as that would break other usecases for `bot_loop_start` where you'd want /need it - like the custom sell/ stoploss callbacks - which are also called once every loop (for open pairs) - irrespective of `process_only_new_candles`.

**Comment by epigramx** [comment]
Oh alright: I see. The exact use case was relying on it in `populate_indicators()` to have run once before the whitelist is processed in whole (and yes: `process_only_new_candles` was enabled). Is there a method available that can do that?

**Comment by xmatthias** [comment]
no, not really.

Also - using `process_only_new_candles=True` is only good to reduce cpu load - it will not prevent intra-candle buys in case of a sell. You should look at `ignore_buying_expired_candle_after` for this - while not preventing analysis - it WILL stop intra-candle buys after X amount of seconds - which is usually what people mistake `process_only_new_candles` to be good for.

**Comment by epigramx** [comment]
Yeah I understand `process_only_new_candles` is mainly for cpu load reduction on slow systems. I guess I'll have to use a "hack" of some sort based on the `Trade` class  or other that makes `populate_indicators()` know it is the last (or first) time it is run for the current whitelist for the use case I had in mind. I guess there's no currently implemented method to do that.

**Comment by xmatthias** [comment]
i'm also not certain when you'd like that to run anyway. Is it once per candle - or once per refreshed whitelist? (which is not the same time by default - although the 2 may coincide ...).

**Comment by epigramx** [comment]
Once per candle is I believe the most intuitive approach for most methods. As we had discussed before: the whiltelist from the volume etc. filters can be erratic in its timing it will be refreshed anyway so I doubt many would want to do much at those random-ish times anyway (e.g. you set the volume filter to 1h and it may gradually drift by a few seconds every refresh).
I think it's very useful each candle because you can do analysis on all the pairs every once in a while and before new TA.
