### ISSUE TITLE
Intel(R) Extension for Scikit-learn*

### ISSUE THREAD

**Issue by a178235** [freqtrade/freqtrade#5186]
Will installing https://github.com/intel/scikit-learn-intelex and adding the following code to a strategy enable the Intel(R) Extension for Scikit-learn*, or does this need to be implemented elsewhere in code?

from sklearnex import patch_sklearn
patch_sklearn()

**Comment by xmatthias** [comment]
Freqtrade does not use scikit-learn directly, but through scikit-optimize - as such, you should investigate if they support this package or not.

It's the first time i've heared from this - so best give it a try and let us know how / if it works.

**Comment by SmirnovEgorRu** [comment]
If scikit-optimize uses some of algorithms ([list](https://intel.github.io/scikit-learn-intelex/algorithms.html)) accelerated in Intel(R) Extension for Scikit-learn - they should be accelerated as well.
