### ISSUE TITLE
How to use tradingview indicator for buy/sell strategies or is there a way to use the PineScript ????

### ISSUE THREAD

**Issue by kunwar-vikrant** [freqtrade/freqtrade#5187]

**Comment by xmatthias** [comment]
Freqtrade uses python for the strategies, so you can't use pinescript.

Samples of strategies can be found in the [documentation](https://www.freqtrade.io/) as well as in the [strategy repository](https://github.com/freqtrade/freqtrade-strategies).

If you're after a specific indicator, it might be implemented already in some library - alternatively you'll have to implement that indicator yourself.

We do however not provide support for this type of questions ("implement my idea for me") - you might wanna join the [discord channel](https://discord.gg/p7nuUNVfP7) to get support / help from the community.

People there love to help assuming the documentation has been consulted first, and people do their research before asking.

**Comment by kunwar-vikrant** [comment]
I just wanted to know IF there is a way …i didnot ask for a code or something….😓

**Comment by xmatthias** [comment]
it will solely depend on the indicator - and as such - your question is way too generic.

**Comment by kunwar-vikrant** [comment]
No worries.....I'll figure out a way.......anyone else can share some insights if possible....
