### ISSUE TITLE
Documentation miss for ARM64

### ISSUE THREAD

**Issue by renisha24** [freqtrade/freqtrade#5190]
## Describe your environment

  * Operating system: ____ MAC ARM 64
  * Python Version: _____ 3.9
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
Noticed a issue in documentation https://www.freqtrade.io/en/stable/docker_quickstart/
in the note "You have to change the docker image in the docker-compose file for your arm64 build to work properly."
```
image: freqtradeorg/freqtrade:custom_arm64
build:
  context: .
  dockerfile: "./docker/Dockerfile.aarch64"
```

Needs to be changed to 
```
    image: freqtradeorg/freqtrade:custom_arm64
    build:
      context: .
      dockerfile: "./docker/Dockerfile.armhf"
```

### Steps to reproduce:
With existing docker file 
error  while building
`Building freqtrade
[+] Building 0.0s (1/2)                                                                                                                                
 => [internal] load build definition from Dockerfile.aarch64                                                                                      0.0s
 => => transferring dockerfile: 2B                                                                                                                0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount260020038/Dockerfile.aarch64: no such file or directory
ERROR: Service 'freqtrade' failed to build : Build failed`
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

```
Building freqtrade
[+] Building 0.0s (1/2)                                                                                                                                
 => [internal] load build definition from Dockerfile.aarch64                                                                                      0.0s
 => => transferring dockerfile: 2B                                                                                                                0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount260020038/Dockerfile.aarch64: no such file or directory
ERROR: Service 'freqtrade' failed to build : Build failed
```

**Comment by xmatthias** [comment]
Please refresh the documentation page (assuming you've had it open for a while).

`Dockerfile.aarch64` has been removed and has been replaced with Dockerfile. Using `Dockerfile.armhf` might potentially not work for ARM64 architectures - and if it does, it'll probably use a 32bit architecture.
