### ISSUE TITLE
Using Trade information as an indicator itself.

### ISSUE THREAD

**Issue by Hsgngr** [freqtrade/freqtrade#5206]
## Enhacement
I would like to use trade information as an indicator. It would be nice to have the information about other trades that has been done. For example when we buy one currency we have a trade object like this:
```
self.trade = Trade(
                    pair=self.pair,
                    open_rate=self.status.open,
                    open_date=self.status.date,
                    stake_amount=self.stake_amount,
                    amount=self.stake_amount / self.status.open,
                    fee_open=self.fee,
                    fee_close=self.fee,
                    is_open=True)
 
```
Then we store this trade like this:
```

                self.trades.append({
                    "step": self.index,
                    "type": 'buy',
                    "total": self.status.open
                })
```
If I can give this indicator for my strategy I can say things like: "If you have Bitcoin and its is down 5%, increase the threshold for buying signal for Etherium"

**Comment by xmatthias** [comment]
There is access to historic trades via the [Trades](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-trades) object.

It's however not available in `populate_*()` methods during backtesting for architecture reasons, and it probably never will be as the speed penalty for that would be too big.

You can however use it safely in the callback methods documented in the [advanced strategy section of the docs](https://www.freqtrade.io/en/stable/strategy-advanced/).

**Comment by Hsgngr** [comment]
So we can create a strategy with them but not test them with backtesting since we populate all the indicators from the beginning ?

**Comment by xmatthias** [comment]
while backtesting, all `populate_*` methods get all data - and trade simulation only starts after that. As such, you can use it but it'll always return 0 trades.

A limited set of Trade* commands are available in callback methods - which should work for all documented methods except `Trade.get_trades`
