### ISSUE TITLE
How can I know via APIs or Telegram whether bot is on stop_buy mode?

### ISSUE THREAD

**Issue by kamontat** [freqtrade/freqtrade#5207]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
the `/show_config` (or `/show-config`) command will have a line at the bottom that says either "running" or "stopped".

**Comment by kamontat** [comment]
@xmatthias It's show only the status of bot right, when I try 

`stop_buy` mode, on show_config still say that it running. Maybe you can add another enum on mode said `stop_buy`?

<img width="1428" alt="CleanShot 2021-06-29 at 12 47 29@2x" src="https://user-images.githubusercontent.com/14089557/123743929-304fbe00-d8d8-11eb-8034-23335d9d138d.png">

**Comment by eschava** [comment]
/show_config shows the next line
Max open Trades: 0
in the stop buy mode

**Comment by xmatthias** [comment]
I agree - /stop_buy is not a specific mode, but it's simply setting the max-open-trades to 0 - therefore disallowing any new trade.

as max_open_trades is part of `/show_config` - i don't see any need to add that information again (it's already pretty long and difficult to digest quickly)

**Comment by kamontat** [comment]
Thank you.
