### ISSUE TITLE
Sell icon disappeared in WEB UI charts

### ISSUE THREAD

**Issue by Majid-Mahzarnia** [freqtrade/freqtrade#5216]
Hello all,
I have deployed Freqtrade with web UI and I have a problem in web UI charts.
I can see all icons but sell yellow diamond icon in charts and I'm sure the trade has been closed.
I think maybe I made a mistake in deployment steps.
Could you please help me to find out how to solve it.
Thanks

**Comment by xmatthias** [comment]
The Yellow diamond should be in the legent at the top - if you click it, it'll be disabled (this should however not be persisted across reloads).

if you don't see any icons on the page - check the "sellSignals" entry at the top - it'll show you how many to expect (if it shows 0, your strategy simply didn't output any signals).

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.

**Comment by Majid-Mahzarnia** [comment]
![Capture](https://user-images.githubusercontent.com/86295332/124352056-4086d680-dc13-11eb-9a57-c8aa6ab8dfe6.JPG)
Hi 
sorry for late. I was waiting for it to give you the resultes.
Finally it shows sell icon without any changes in configuration or strategy. I use default strategy with just 1 X 5000 hyperopt results.
But what do you think about it? why it does show just once ?
Thank you

**Comment by xmatthias** [comment]
it's very simple - there is only one sell signal for the pair / time period given.

Would there be more signals, they'd show up as well.
