### ISSUE TITLE
Telegram: hide/compact the list of currencies with a low balance (below dust level)

### ISSUE THREAD

**Issue by Merinorus** [freqtrade/freqtrade#5217]
Hi,

This is my first contribution!

When using the /balance command with the Telegram bot, having a lot of low-amount currencies will result in a insanely long list:

![Insade amount of dust currencies](https://user-images.githubusercontent.com/3023499/123959483-842cd680-d9ae-11eb-9980-6cfef537d836.png)

It happens quickly on Binance depending on your config, I don't know if it's the same for other exchanges.

Wouldn't it be simpler to regroup all these currencies in a line like this:
"72 Other currencies:
 Est. USDT: 133.967"

Or we could make an option to choose if we want to keep the list as it is for now, or if we want to compact this.

What do you think?

It looks like a minor modification, if you're interested by this one but it's not on the priority list I could learn how to contribute and make a PR.

Thank you!

**Comment by xmatthias** [comment]
to be honest, it'll only happen if you don't have BNB in your account (or have BNB fees disabled). 
Personal suggestion: convert all "dust" to BNB and use that to pay fees - it'll avoid this situation as well as allow you to pay lower fees.


I understand that this can however be a pain-point if you won't or can't use BNB for whatever reason - so for sure, if you feel for it, i'd be happy to receive a Pull Request which will improve this behaviour.

**Comment by Merinorus** [comment]
I remember a Binance account that was left with dust that were worth a few hundred dollars one or two years later. So I'm guessing it could be worth not converting dust coins, because one of them could shoot up...
Thank you for your advice anyway! I will look at it when I find time to do it.
