### ISSUE TITLE
Stake amount assigned on every trade.

### ISSUE THREAD

**Issue by fjl2020** [freqtrade/freqtrade#5218]
## Describe your environment

  * Operating system: docker version
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
I'm trying to implement my strategy. In this strategy I assign the amount to buy related to the stop loss. For example, if I have 100$ and my strategy allow 5% of loss. when I calculate the stop loss and the stop loss is >5% I have to use the stop loss calculated but the amount to buy is 5 * 100 / (stop loss calculated). There is a way to do that (assign an amount when the trade is attemp)?
*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
There is currently no way to manually assign the stake-amount you're trying to create.

There's however an enhancement for this already in #5076 - so it might be implemented sooner (#5189) or later.

**Comment by fjl2020** [comment]
Ok, this is useful because, it is a way to manage the position without close the trade prematurely . Thanks a lot
