### ISSUE TITLE
Hyperopt-loss Parameter content

### ISSUE THREAD

**Issue by Fimap9to1** [freqtrade/freqtrade#5223]
Dear Matthias, I've read the docs about the custom Hyperopt file and it says that the results data is the same available in the output file of the backtest if used with --export trades. 

results: DataFrame containing the result
The following columns are available in results (corresponds to the output-file of backtesting when used with --export trades):
pair, profit_ratio, profit_abs, open_date, open_rate, fee_open, close_date, close_rate, fee_close, amount, trade_duration, is_open, sell_reason, stake_amount, min_rate, max_rate, stop_loss_ratio, stop_loss_abs

I was wondering if this is "out-dated" and for example drawdown is now available as a column, if yes it is right to call it with "max_drawdown_abs" as it appears in the results file of the backtest?

**Comment by xmatthias** [comment]
I'm not quite sure i understand your question / what this is about (the title does not correspond to the content ...).

are we talking about the results that are sent to hyperopt Loss functions?

**Comment by Fimap9to1** [comment]
I'm sorry if the title is misleading if you want i'll change it. So yes the matter is the hyperopt loss function (custom file).

In the loss function I'd like to take into account the max drawdown of the strategy. But I didn't find how to call it in the custom hyperopt function in the custom hyperopt file.

**Comment by xmatthias** [comment]
The content you get is the trades data - with the following columns:

```
'pair', 'stake_amount', 'amount', 'open_date', 'close_date',
                   'open_rate', 'close_rate',
                   'fee_open', 'fee_close', 'trade_duration',
                   'profit_ratio', 'profit_abs', 'sell_reason',
                   'initial_stop_loss_abs', 'initial_stop_loss_ratio', 'stop_loss_abs',
                   'stop_loss_ratio', 'min_rate', 'max_rate', 'is_open',
```
which should be more or less aligned with the docs (although i didn't check them one by one).


If you need drawdown, you'll need to calculate this in the loss function.
we could for sure pass the whole backtest statistics in (they're calculated before the loss) - but it's currently not done - so it's not available.

**Comment by Fimap9to1** [comment]
Oh I see. Thanks, I'll calculate it myself. It would be nice for new users to pass the whole backtest statistics maybe. Have a nice day!

PS. please do you have any suggestion or file to see how you calculate drawdown maybe? :D

**Comment by Fimap9to1** [comment]
How about calculating it like this? 

# We are going to use a trailing day window
        window = results['open_date'].max() - results['open_date'].min()

#or use a fixed number of days 
window = 250

        # Calculate the max drawdown in the past window days for each day in the series.
        # Use min_periods=1 if you want to let the first 252 days data have an expanding window
        total_profit = results['profit_abs'].sum()
        Roll_Max = total_profit.rolling(window, min_periods=1).max()
        Daily_Drawdown = total_profit/Roll_Max - 1.0

        # Next we calculate the minimum (negative) daily drawdown in that window.
        # Again, use min_periods=1 if you want to allow the expanding window
        Max_Daily_Drawdown = Daily_Drawdown.rolling(window, min_periods=1).min()

**Comment by xmatthias** [comment]
The parameters that are now provided correspond to the calculation that is performed for backtesting.

how these are calculated is for sure not part of this issue (it's not been asked - and there's another issue about drawdown in particular in #5167 ).

**Comment by Fimap9to1** [comment]
Great thanks!
