### ISSUE TITLE
More setup switches.

### ISSUE THREAD

**Issue by a178235** [freqtrade/freqtrade#5224]
It would be nice to have command line switches to be able to automate these questions.

Reset git branch? (This will remove all changes you made!) [y/N]?
Do you want to install dependencies for dev [y/N]?
Do you want to install plotting dependencies (plotly) [y/N]?
Do you want to install hyperopt dependencies [y/N]?

**Comment by xmatthias** [comment]
The setup-script is intended to assist with manual installation, not with automation (it provides no benefit over running the commands manually). 

If you need to automate, best run the commands (`pip install -r ...`) manually, after initial installation it'll only be the pip and git commands anyway that matter.
