### ISSUE TITLE
Telegram chat request log

### ISSUE THREAD

**Issue by Majid-Mahzarnia** [freqtrade/freqtrade#5225]
Hello all
Before upgrading docker image (last week), I could see logs from telegram activity when telegram members send some usual requests like /performance or etc (this could help me to make sure bot is running). But now I can't see such logs when I use "docker-compose logs -f".
Maybe I made a mistake in upgrading the docker image.
Could you please help me to find out how to see telegram logs.
Thanks

**Comment by xmatthias** [comment]
These messages did not provide any benefit, therefore the log-level has been lowered to debug.

While you can use `-v` to get them back, i'd not recommend that as verbose mode will post quite some messages.

Also, by sending telegram messages, youll know that the bot is running by getting a response.
If its not running, you'll not get a response.

**Comment by Majid-Mahzarnia** [comment]
Thank You
