### ISSUE TITLE
Authentication error for binance

### ISSUE THREAD

**Issue by kaggrwal** [freqtrade/freqtrade#5226]
I tried running live on Binance,

I have provided key and secret both, but I'm getting the following error

"Could not get balance due to AuthenticationError. Message: requires `apiKey`"

how can I resolve this?

**Comment by xmatthias** [comment]
This simply means that your configuration is incorrect, and the keys have not been provided correctly (either swapped - or something else is wrong).

Best redo the configuration steps - and make sure you got them correct (and also make sure that this configuration is the one that's used if you have more than one configuration).

Debugging these things are pretty difficult, as you shall not post your config (the relevant section IS the keys - but do NOT share these!!)

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
