### ISSUE TITLE
Limited Active Pairs to trade

### ISSUE THREAD

**Issue by jyenoonan** [freqtrade/freqtrade#5230]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.7(`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade -V (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hello team,

When using my trying to load or back test my strategy there is limited pairs I can run it on. If I try add ADA/USDT to my whitelist - it says it is not on binance. I then used the sub command to show all active pairs. It comes back with "Exchange Binance has 20 pairs" and lists only BTC, LTC, BNB, TRX, and XRP coins. So back-testing and running the program only works with these coins

How do I load all coins / why is it only saying binance has 20 pairs available to trade???

**Comment by xmatthias** [comment]
It's unclear from the above which exchange you're using.
only having ~20 coins sounds a bit like you're using one of binances sub-sidiaries (binance.us, binance.uk?) - where this might be a possibility.

Freqtrade itself will not limit you to certain pairs (they have to be spot pairs - but that's about it) assuming they are available on the exchange.

**Comment by jyenoonan** [comment]
I don't think I am using one of the sub-sidiaries. I am located in Australia and have the Australian version, but I still have hundreds of pairs in the spot market when I log onto my Binance account. Do you have any suggestions how I could go about overcoming this? Because I cannot find anywhere on the internet with someone with a similar problem.

**Comment by jyenoonan** [comment]
Just for reference if anyone else has this issue. I have fixed it, it was because sandbox was = true. I changed it to false and it then got all data from Binance. Unsure if this is a bug or not, but this allowed me to connect and get all pairs within Binance for backtesting.

**Comment by xmatthias** [comment]
it's not a bug but intended behaviour.

Using the exchange's sandbox is however not recommended - as these have almost no volume - so results from there will not even remotely match to what you would encounter on the real exchange.

These sandboxes are mostly there to experiment (develop an API against it) - but not to test your strategy.
