### ISSUE TITLE
Difference backtest when select multiple pairs with one pair

### ISSUE THREAD

**Issue by quycmf8** [freqtrade/freqtrade#5233]
I wrote the new strategy and backtest it with 13 pairs. 
After that,  I backtest with one pair which pair still in the list of 13 pairs.
But the number of trade when I backtest in 13 pairs is less than I backtest 1 pair.
For ex: BTC/USDT when backtest 13 pairs at the same time. The number of trade is 13
BTC/USDT when backtest only BTC/USDT. The number of trade almost 20
Can you help me please?

**Comment by xmatthias** [comment]
the most likely explanation is that all trade-slots have been exhausted.

With a `max_open_trades` < pairlist size, pairs will influence each other, as they need to check if a new trade-slot is available or not.

Assuming you use static stake amount (with unlimited stake, prior results (from all pairs) will also impact trade size for future trades), you should get the same number of trades when using `max_open_trades: -1` - or set to 13 or higher (assuming a pairlist of 13 pairs).

**Comment by quycmf8** [comment]
Thank you.

**Comment by quycmf8** [comment]
I already tried to "max_open_Trades" = -1 and stake amount" = 300.
But when I test for 13 pairs, the actual trades always less than I test only 1 pair.
For ex. ALICE/USDT when test 13 pairs, trade 9 times.  When test only ALICE/USDT, trade 16 times.  Please help me

**Comment by xmatthias** [comment]
The scenario quite differs from an overall perspective and you need to make sure that all necessary ressources (trade-slots, capital) are available.
as such - please make sure that

* max_open_trades = >= pairlist number
* stake_amount * max_open_trades > dry_run_wallet * 1.1

**Comment by quycmf8** [comment]
Found it!!! Thank you Sir.
