### ISSUE TITLE
new PairFilter for offsetting pairlists

### ISSUE THREAD

**Issue by nightshift2k** [freqtrade/freqtrade#5241]
## Describe the enhancement

For some strategies it might make sense to split a larger pairlist on two bots, to speed up indicator and/or buy/sell calculation, therefor I'd like to propose a new filter OffsetFilter, which will offset the pairlist so a given amount of pairs can be skipped. For example a compute heavy strat could be split running on 100 pairs could be split into two bots one running on the first 50 pairs, the other running with an offset of 50 on pair 51-100. Or one could skip a certain amount of the usual topXX coins.

**Comment by xmatthias** [comment]
in principle, i don't see much that speaks against it.

especially for your usecase (2 bots) you'll need to be careful though (so we should have this documented too).

Depending on the filters (which can determine the order) timing might be important - so you can't really guarantee that you get the "1st 50" and "next 50" - as it's 2 different lists (in 2 different processes), which (depending on the pairlists) might be generated based of slightly different base data.

As such, especially around the 49-51 (maybe more?) area, you might see overlaps - so technically, i don't think this can guarantee that 2 bots never trade the same pair (there's also other reasons for this - like an already open trade for a pair that moves from one list segment to the other ...).

**Comment by nightshift2k** [comment]
Yes I thought about that. The first can be probably adressed with the enhancement to the volumefilter, when looking on longer ranges of quoteVolume but I agree that this should be documented as a warning for potential overlaps.

**Comment by xmatthias** [comment]
even then - assuming you use rolling 1h volume for the last 24h - a huge spike in the last hour might change things for a few pairs ... but the pairlists won't refresh in line ... 

but yeah - sure - overall sounds like a sound approach (i'm just pointing out potential flaws early ;) )
