### ISSUE TITLE
Binance Leveraged Tokens (BLVT) order limit implementation

### ISSUE THREAD

**Issue by rongybika** [freqtrade/freqtrade#5247]
Hi,

I've just read few days ago that Binance will introduce a different buy limit for few Leveraged Tokens.

Leveraged Tokens | Max. Position Limit (USDT)*
LTCUP | 5,000
LTCDOWN | 5,000
XLMUP | 5,000
XLMDOWN | 5,000
TRXUP | 5,000
TRXDOWN | 5,000
XTZUP | 5,000
XTZDOWN | 5,000
FILUP | 5,000
FILDOWN | 5,000

Is there a way to implement a solution to limit buy orders for this tokens according to their personal limits?

Thanx

**Comment by xmatthias** [comment]
first of all - source link please
then - we're currently not checking upper limits (on basically all exchanges they're insanely high - so there's been little reason for that so far).

with #5189 it'll become possible to control this in the strategy - but freqtrade itself has (currently) no logic to check for the upper bound.

**Comment by rongybika** [comment]
Hi,

Thank you for answer. This update will be what I'm looking for (I hope :) )

Source link for this news/info:

https://www.binance.com/en/support/announcement/6a1d2aedfd9c453591916c533fd26aeb

Thanx

**Comment by xmatthias** [comment]
Looking at this again, it seems like the exchange is (no longer?) returning this value in their API.
in https://github.com/ccxt/ccxt/issues/9996, we can see that it's clearly there as `MAX_POSITION` filter - but it's now missing in the exchange response.

If it's not available through the API, it's not something we can handle (limits will change over time - and we can't hard-code upper limits to this - and with that, it becomes something we can't automatically handle.

I'll therefore close this issue - but since the upstream issue is mine, i'll be notified when something changes - and can then apply appropriate measures in freqtrade if necessary.

(the "info" part is always identical, as ccxt keeps that as the raw response from the exchange).

```
{'id': 'LTCUPUSDT',
 'symbol': 'LTCUP/USDT',
 'base': 'LTCUP',
 'quote': 'USDT',
 'baseId': 'LTCUP',
 'quoteId': 'USDT',
 'active': False,
 'type': 'spot',
 'linear': None,
 'inverse': None,
 'spot': True,
 'swap': False,
 'future': True,
 'option': False,
 'margin': False,
 'contract': False,
 'contractSize': None,
 'expiry': None,
 'expiryDatetime': None,
 'optionType': None,
 'strike': None,
 'settle': None,
 'settleId': None,
 'precision': {'amount': 2, 'price': 4, 'base': 8, 'quote': 8},
 'limits': {'amount': {'min': 0.01, 'max': 920000.0},
  'price': {'min': 0.0486, 'max': 0.923},
  'cost': {'min': 10.0, 'max': None},
  'leverage': {'min': None, 'max': None},
  'market': {'min': 0.0, 'max': 343363.27451282}},
 'info': {'symbol': 'LTCUPUSDT',
  'status': 'BREAK',
  'baseAsset': 'LTCUP',
  'baseAssetPrecision': '8',
  'quoteAsset': 'USDT',
  'quotePrecision': '8',
  'quoteAssetPrecision': '8',
  'baseCommissionPrecision': '8',
  'quoteCommissionPrecision': '8',
  'orderTypes': ['LIMIT',
   'LIMIT_MAKER',
   'MARKET',
   'STOP_LOSS_LIMIT',
   'TAKE_PROFIT_LIMIT'],
  'icebergAllowed': True,
  'ocoAllowed': True,
  'quoteOrderQtyMarketAllowed': True,
  'allowTrailingStop': True,
  'cancelReplaceAllowed': True,
  'isSpotTradingAllowed': False,
  'isMarginTradingAllowed': False,
  'filters': [{'filterType': 'PRICE_FILTER',
    'minPrice': '0.04860000',
    'maxPrice': '0.92300000',
    'tickSize': '0.00010000'},
   {'filterType': 'LOT_SIZE',
    'minQty': '0.01000000',
    'maxQty': '920000.00000000',
    'stepSize': '0.01000000'},
   {'filterType': 'MIN_NOTIONAL',
    'minNotional': '10.00000000',
    'applyToMarket': True,
    'avgPriceMins': '5'},
   {'filterType': 'ICEBERG_PARTS', 'limit': '10'},
   {'filterType': 'MARKET_LOT_SIZE',
    'minQty': '0.00000000',
    'maxQty': '343363.27451282',
    'stepSize': '0.00000000'},
   {'filterType': 'TRAILING_DELTA',
    'minTrailingAboveDelta': '10',
    'maxTrailingAboveDelta': '2000',
    'minTrailingBelowDelta': '10',
    'maxTrailingBelowDelta': '2000'},
   {'filterType': 'PERCENT_PRICE_BY_SIDE',
    'bidMultiplierUp': '5',
    'bidMultiplierDown': '0.2',
    'askMultiplierUp': '5',
    'askMultiplierDown': '0.2',
    'avgPriceMins': '5'},
   {'filterType': 'MAX_NUM_ORDERS', 'maxNumOrders': '200'},
   {'filterType': 'MAX_NUM_ALGO_ORDERS', 'maxNumAlgoOrders': '5'}],
  'permissions': ['LEVERAGED'],
  'defaultSelfTradePreventionMode': 'NONE',
  'allowedSelfTradePreventionModes': ['NONE']},
 'percentage': True,
 'feeSide': 'get',
 'tierBased': False,
 'taker': 0.001,
 'maker': 0.001,
 'lowercaseId': 'ltcupusdt'}
```
