### ISSUE TITLE
exchange.validate_required_startup_candles only executes if startup_candle_count is defined in config.json?

### ISSUE THREAD

**Issue by octaviusgus** [freqtrade/freqtrade#5250]
Is this expected behavior? If I define startup_candle_count inside a strategy file, everything works fine, but if I define it in config.json, a message saying 

`This strategy requires 2400 candles to start. Binance only provides 1000 for 1h. `

Use case:
I have the data downloaded and want to use only 1h candles in the strategy, so I set startup_candle_count in the strategy to 2400. Everything works.
I want to do the same but in config.json, because I want one config file per strategy, so I define startup_candle_count:2400 and I get the mentioned message and an exception.

I commented this code for now to get everything working:
Line 152 exchange.py
```
            # self.validate_required_startup_candles(config.get('startup_candle_count', 0),
            #                                        config.get('timeframe', ''))
``` 
even though Binance might provide 1000 candles only, why not include downloaded data (assuming this is an actual problem in live/dry run), or **was the design in these situations to just download and use 1d candles?**

**Comment by xmatthias** [comment]
If you're not getting the warning that's a problem. you should get this warning / error either way - wherever you configure it.

dry/live will use the data for one exchange call - which is 500 or 1000 candles. If your strategy requires more than that - best use informative pairs with a longer timeframe.
A strategy that requires 2400 candles will 100% fail in dry/live - simply because this long lookback is not available.

**Comment by octaviusgus** [comment]
Will add the informative pair then. 



> If you're not getting the warning that's a problem. you should get this warning / error either way - wherever you configure it.

can confirm a bug then
_startup_candle_count defined inside a strategy file will not cause the required warning about exchange not providing that amount of candles_
startup_candle_count defined inside a config file on the other hand will cause the required warning

![image](https://user-images.githubusercontent.com/86911628/124983445-3d874e00-e038-11eb-8cf3-45876fb75ab1.png)
