### ISSUE TITLE
Pandas 1.3 Update Raises Several Warnings

### ISSUE THREAD

**Issue by grainz** [freqtrade/freqtrade#5251]
`/home/grainz/build/freqtrade/freqtrade/rpc/rpc.py:764: FutureWarning: casting datetime64[ns, UTC] values to int64 with .astype(...) is deprecated and will raise in a future version. Use .view(...) instead.
  dataframe.loc[:, '__date_ts'] = dataframe.loc[:, 'date'].astype(int64) // 1000 // 1000`

The change is referenced here:
https://github.com/pandas-dev/pandas/issues/33401
https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.3.0.html

**Comment by xmatthias** [comment]
Yeah - it's deprecation warnings.
for now - nothing to worry about - and will be changed before pandas removes this functionality.

**Comment by grainz** [comment]
It causes hyperopt, backtesting, and trade functions to spam warnings instead of seeing the normal output.

**Comment by spawnaga** [comment]
add this to the top of **/freqtrade/.env/lib/python3.8/site-packages/freqtrade/optimize/optimize_reports.py**


```

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

```
