### ISSUE TITLE
Importing Hyperopt results into the strategy.

### ISSUE THREAD

**Issue by Majid-Mahzarnia** [freqtrade/freqtrade#5256]
Hello all,
I ran 4 Freqtrade bots on different machines with different coin assets and same defaults sample strategy, then I started hyperopt to optimize sample strategy and improve it, 
"docker-compose run --rm freqtrade hyperopt --hyperopt SampleStrategy --hyperopt-loss OnlyProfitHyperOptLoss --strategy SampleStrategy -i 15m -e 5000 --spaces all"
After that I imported hyperopt results exactly into the default sample strategy. but there is no difference in trading results between before and after importing hyperopt results. I think I have a problem in importing results into the strategies. to clear this, I just copied and pasted Buy and Sell hyperspace params, at the end of this line:
# This class is a sample. Feel free to customize it.
class SampleStrategy(IStrategy):
then I replaced ROI and Trailing stop and Stoploss values in strategies .
I'm not sure if this is the correct way, and I haven't found any step by step how to helps to make sure this way is correct. that's why I got confused.
Could you please help me to make sure if this is the correct way to import hyperopt results.
Thanks

**Comment by xmatthias** [comment]
Please fill out the issue template.
It's there for a reason - and i've stopped answering issues of people who continuously delete it.

**Comment by Majid-Mahzarnia** [comment]
ok sorry I will write it again.
Thanks
