### ISSUE TITLE
NumExpr defaulting to 8 threads

### ISSUE THREAD

**Issue by mohammadmoth** [freqtrade/freqtrade#5258]
## Describe your environment

  * Operating system: Ubuntu 18.04 lts
  * Python Version: Python 3.8.0
  * CCXT version:ccxt==1.51.77
  * Freqtrade Version: freqtrade 2021.6
  
## Your question
-------------------Logs-------------------
2021-07-10 20:35:08,678 - numexpr.utils - INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2021-07-10 20:35:08,678 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
-------------------Logs-------------------

Hello all ,
I would like to ask how i can set 16 cores : is this safe and useful ? And how is that possible? 

thank you all

**Comment by xmatthias** [comment]
Freqtrade does not directly depend on numexpr.
It's some dependency (most likely hyperopt?) - but it's not something freqtrade uses directly - and as far as i know - this has no impact on freqtrade performance as far as i'm aware.

For hyperopt itself, you can control paralellism with `-j` - which by default uses all available cores.

**Comment by mohammadmoth** [comment]
Thank you 💯 

You are doing a great job  👍 👍
