### ISSUE TITLE
How can I limit cpu usage in dry-run/normal trading?

### ISSUE THREAD

**Issue by duquel** [freqtrade/freqtrade#5259]
Hello! Freqtrade is working flawlessly for what I do.
Only one thing, I monitor a lot of pairs on the 1D timeframe. I dont need it to check price every minute or update the database or something every minute. If I need to check it via the web interface its enough to let it be on demand.
Basically I am monitoring 200 coins and the cpu gets a little too hot for my liking.
I would be happy to sacrifice perhaps the heartbeat interval(?) instead of 1 minute to something like 5 minutes.
Will it change the cpu usage if I do this? Also, is this done in worker.py or is it somewhere else?
Are there other ways to sacrifice precision in search for lower cpu usage?

Thank you!

## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
the heartbeat interval is not relevant for cpu - it's only there to let you know via logs: "bot didn't die yet, it's still up and running".

To avoid recalculating signals every iteration, you can set `process_only_new_candles=True` - then the indicators will be calculated only once per candle (so on 1d candles, once per day).

you can also change `internals.process_throttle_secs` to something higher - this will determine how often open trades are checked. 
I'd however recommend to not set this to something insanely high (although 5s might be small for 1d candles) - as it's also implicitly the potential maximum delay you can see when downloading data (so assuming you'd set this to 1h - you might get the daily candles at 1am UTC if timing is against you).

**Comment by duquel** [comment]
I will definitely run with process_only_new_candles=True
I will run with 10secs for process_throttle_secs for a day. maybe set it to 15 later.
Thanks a lot for the quick answer!
