### ISSUE TITLE
Add Minimal Volume in Last x hours to VolumePairList

### ISSUE THREAD

**Issue by BillGatesIII** [freqtrade/freqtrade#5260]
I would like to filter out low volume pairs by volume in the last x hours. The result is that during more quiet hours, especially in the weekend, my pairlist will be shorter.

**Comment by xmatthias** [comment]
That's certainly not possible at the moment.

i guess depending on the definition of "quiet", you could use "RangeStabilityFilter" too - or better yet on `Volatilityfilter`. 
I'm however not sure you'll want to only look at volume alone - as with or without volume some pairs can show quite some volatility.

**Comment by nightshift2k** [comment]
Filtering by minimum volume should be possible IMHO if one can "live" with a static min_volume threshold...

https://github.com/freqtrade/freqtrade/blob/74a5cb3c21d33bcee48a64470c4d9117efa86fc3/freqtrade/plugins/pairlist/VolumePairList.py#L198-L202

The parameter `min_value` seems not to be documented yet though ...

**Comment by xmatthias** [comment]
That's actually a pretty nice catch - which turns this into a documentation task.
