### ISSUE TITLE
freqtrade error - 

### ISSUE THREAD

**Issue by momo3232** [freqtrade/freqtrade#5261]
HELLO
I have an error 
how can I solve it

  * Operating system: windows server 2016
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair YFII/USDT due to ExchangeNotAvailable. Message: binance GET https://api.binance.com/api/v3/klines?symbol=YFIIUSDT&interval=1m&limit=1000"

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
 
WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair YFII/USDT due to ExchangeNotAvailable. Message: binance GET https://api.binance.com/api/v3/klines?symbol=YFIIUSDT&interval=1m&limit=1000"

**Comment by xmatthias** [comment]
The error you're getting is "ExchangeNotAvailable".
This usually suggests that either the exchange is really not available (maybe just from your spot / area of the world) - or that you've got network problems.

It's an error that should go away with time - if it doesn't - it might be a regional block binance put in place.
As such - i'd not know how freqtrade can help you with this.

**Comment by momo3232** [comment]
> The error you're getting is "ExchangeNotAvailable".
> This usually suggests that either the exchange is really not available (maybe just from your spot / area of the world) - or that you've got network problems.
> 
> It's an error that should go away with time - if it doesn't - it might be a regional block binance put in place.
> As such - i'd not know how freqtrade can help you with this.

thank you
I have another question 
how can I filter pairs with profit percentage 
for example trade pairs with profit in one day < 15%

**Comment by xmatthias** [comment]
you can do that within your strategy by relying on the [Trade](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-trades) object.

You should be careful though - reaching 15% with one pair in a day will be rather difficult - so you'll most likely have all pairs in that list.
Also, profit will be show on the day of "realization" - that doesn't necessarily mean the pair moved 15% that day (if the trade spans for several days).

**Comment by momo3232** [comment]
⚠ Binance: Cancelling open sell Order for BEAM/USDT (#12). Reason: forcesold.
Created sell order for trade 12.

I always have this Cancelling problem in dry run
what should i do
I've used forcell after that but it didn't work
 it doesn't sell
