### ISSUE TITLE
No such file or directory: '.\\docker/docker-compose-jupyter.yml'

### ISSUE THREAD

**Issue by Sanmunew1** [freqtrade/freqtrade#5266]
Hi I am new to docker and freqtrade, and followed the exact steps on [https://www.freqtrade.io/en/stable/docker_quickstart/](https://www.freqtrade.io/en/stable/docker_quickstart/) to run freqtrade using docker. However, when I want to do data analysis on jupyter, and use "docker-compose -f docker/docker-compose-jupyter.yml up" as in the last part of the tutorial, I got 

No such file or directory: '.\\docker/docker-compose-jupyter.yml'
![image](https://user-images.githubusercontent.com/87329573/125326516-0b2c6800-e33a-11eb-9368-716718978cb0.png)

Folder structure:
![image](https://user-images.githubusercontent.com/87329573/125326765-4af34f80-e33a-11eb-865d-a01ea4f9b1c0.png)

I wonder how to solve this? I have already build the folder with docker-compose.yml and "user_data", all other things are working well except this part. If I download the 'docker-compose-jupyter.yml' from the repository it seems doesn't work that way.

Couldn't find the same problem in the issues. So appreciate it if you know the solution.

## Environment
  * Operating system: WIndows 10, VS code
  * Python Version: 3.8.5
  * Freqtrade Version: 2021.06

**Comment by xmatthias** [comment]
that part assumes (maybe implicitly) that you're using a cloned (checked out) version.

alternatively, you can simply download the relevant file from [here](https://github.com/freqtrade/freqtrade/blob/develop/docker/docker-compose-jupyter.yml).

**Comment by Sanmunew1** [comment]
> 
> 
> that part assumes (maybe implicitly) that you're using a cloned (checked out) version.
> 
> alternatively, you can simply download the relevant file from [here](https://github.com/freqtrade/freqtrade/blob/develop/docker/docker-compose-jupyter.yml).

Thank you for your reply. I did try to download the docker-compose-jupyter.yml file you mentioned with it's dockerfile.jupyter. I ran the above command, and it does enable a jupyter server, however it seems to creat an independent image and container with it's own file system, so I can't use the data, stragtegy and sample notebooks etc in my original folder.

I wonder what's the proper way to run freqtrade with docker while being able to use jupyter? 

Also when you say cloned version, does it mean not using docker to install, but using "git clone ..." instead?

Thanks for answering!

**Comment by xmatthias** [comment]
The container / image will be different for sure (that's intentional).

The jupyter compose file does mount the same user_data directory into the container (assuming you use it from the same location and didn't change the original mountpoints).
