### ISSUE TITLE
use (simple) indicator signals as well as certain price changes between these signals to trigger a trade

### ISSUE THREAD

**Issue by d4fuQQ** [freqtrade/freqtrade#5267]
## Describe your environment

  * Operating system: Win 10 (x64)
  * Python Version: 3.8.10 (`python -V`)
  * CCXT version: 1.51.25 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade docker-2f33b97b (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hey,
I thought my idea to create an own strategy was a simple one, but as a coding layman it turned out I quickly reached the limits of what I wanted to do – even by reading through a lot of the freqtrade documentation repeatedly.

I saw a lot of strategies are written up by only comparing candlestick data for the formulation of buy or sell triggers.
However, I was planning on using previous signals from a given indicator and comparing the price at this point with the current price in order to determine if buying or selling is actually feasible.
In other words, if we use an indicator that produces many signals (e.g. a simple MA crossover), I only want the strategy to trigger a buy when the price changed, let's say -10%, since the last signal and selling to occur (at the next signal) when the price went up by at least 10%.

After creating a few simple strategies (and getting them running smoothly), I tried around with some pseudo code. I'm afraid you probably couldn't call it much more than that 😅

```python
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
            # Some TA indicator
            dataframe['fastSMA'] = ta.SMA(dataframe, timeperiod=50)
            dataframe['slowSMA'] = ta.SMA(dataframe, timeperiod=200)

            # Define crossover buy signal (golden cross):
            if (dataframe['fastSMA'] > dataframe['slowSMA']) and (dataframe['fastSMA'].shift(1) <= dataframe['slowSMA'].shift(1)):
                dataframe['buy_signal'] = True

            # Define crossover sell signal (death cross):
            if (dataframe['slowSMA'] > dataframe['fastSMA']) and (dataframe['slowSMA'].shift(1) <= dataframe['fastSMA'].shift(1)):
                dataframe['sell_signal'] = True

            # Define previous buy signal:
            dataframe['last_buy_signal'] = dataframe['buy_signal'].tail()

            return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                # Check for a buy crossover depending on given indicators (fastSMA > slowSMA)
                (dataframe['buy_signal'] == True) &
                # Buy if price dropped by at least 10% since the last buy signal:
                ((dataframe['last_buy_signal'] / dataframe['close']) <= 0.9)
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                # Check for a sell crossover depending on given indicators (slowSMA > fastSMA)
                (dataframe['sell_signal'] == True) &
                # Sell if price increased by at least 10% since the last buy signal:
                ((dataframe['last_buy_signal'] / dataframe['close']) >= 1.1)
            ),
            'sell'] = 1

        return dataframe
```

As you can imagine this strategy would need to potentially open up many long positions without closing them (which is intended). It'd be great to have a strategy that works for backtesting (`--eps`) as well as in dry/live trading (`"max_open_trades": -1`).

I saw potentially helpful information in the docs, although I'm not quite sure if some of these considerations would actually the right way to go (speaking in terms of "keep it simple"):
- https://www.freqtrade.io/en/latest/strategy-customization/#get_analyzed_dataframepair-timeframe
- https://www.freqtrade.io/en/latest/strategy-advanced/#custom-sell-signal
- https://www.freqtrade.io/en/latest/strategy-advanced/#dataframe-access

Well, any help on how to work with previous signals in combination with buy/sell triggers is appreciated!

**Comment by xmatthias** [comment]
In general - your big problem is the usage of if statements.

Dataframes assume the usage of vectorized methods - as such - your "if" statements will not work.
Instead - you should use "direct" assignments (so when the contents are true, a

```
if (dataframe['slowSMA'] > dataframe['fastSMA']) and (dataframe['slowSMA'].shift(1) <= dataframe['fastSMA'].shift(1)):
                dataframe['sell_signal'] = True
```

becomes something around the following (untested, so syntax errors are free of charge :laughing:).

``` python
dataframe.loc[
    ((dataframe['slowSMA'] > dataframe['fastSMA']) & (dataframe['slowSMA'].shift(1) <= dataframe['fastSMA'].shift(1)))
    , 'sell_signal'] = 1
```

**Comment by d4fuQQ** [comment]
Thanks, that's valuable input for me!

This brings the strategy indeed a step further and according to the next error, I suppose, there is another issue with the "definition" of my `'last_buy_signal'`:

```python
2021-07-12 18:08:37,047 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'buy_signal'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 54, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 539, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 497, in backtest_one_strategy
    preprocessed = self.strategy.ohlcvdata_to_dataframe(data)
  File "/freqtrade/freqtrade/strategy/interface.py", line 716, in ohlcvdata_to_dataframe
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/freqtrade/freqtrade/strategy/interface.py", line 716, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair})
  File "/freqtrade/freqtrade/strategy/interface.py", line 733, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/MyStrategy.py", line 79, in populate_indicators
    dataframe['last_buy_signal'] = dataframe['buy_signal'].tail()
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 3455, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'buy_signal'
```

I read about the `.tail()` in the documentation but it's probably wrong in how I'm using it with:
`dataframe['last_buy_signal'] = dataframe['buy_signal'].tail()`

**Comment by xmatthias** [comment]
using `.tail()` will not work in backtesting for sure. It'll look at the very last row of the dataframe - but in backtesting context, that's looking into the future.

You'll need to use some `.rolling()` method to get this - but i'll leave research into "how to" to you ... the internet has pretty good tutorials for this.

**Comment by d4fuQQ** [comment]
Alright, thanks a lot!
I also had a typo which is why this error occured...

But yes, regarding the backtesting, there are indeed no buy or sell indicators populated:
![image](https://user-images.githubusercontent.com/20617933/125338540-9ca6d480-e350-11eb-94df-825b1ae99533.png)

So, I'll continue with my research for now.
Cheers :)

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
