### ISSUE TITLE
Backtest Summary - Total Fees

### ISSUE THREAD

**Issue by dominiclapointe** [freqtrade/freqtrade#5269]
## Describe the enhancement
Hi,

The backtest summary (summary metrics) could show the total fees applicable, could help for fees optimization.

Thank you

**Comment by xmatthias** [comment]
I'm not sure what you hope to gain from it.
All profits include fees - and use the "default" fee the exchanges use (0.001 for binance iirc).
Each fee will be applied twice per trade (on open / close) - so to optimize fees, you simply reduce the number of trades (which will however usually also reduce the amount of profit).

**Comment by dominiclapointe** [comment]
I might be wrong but fees for UP/DOWN spot symbol are not the same than normal spot right?

**Comment by xmatthias** [comment]
it's technically correct, but depends heavily on the holding times (only if you hold it overnight or so iirc) - and it's not considered in backtesting either (the exchange doesn't provide this info via api afaik).

As such - all pairs are currently treated equally - and have the same fee applied.

**Comment by dominiclapointe** [comment]
Is there an event or such (i come from c#, so events might not be the best word here in python world) in strategy that get executed when a new day is starting? 

Something similar to : https://www.quantconnect.com/docs/algorithm-reference/scheduled-events

From there, i could probably adjust manually the fees by querying the DB?

**Comment by xmatthias** [comment]
No.
day changes have no practical meaning for crypto - it's not like in regular markets, where a new day has new market open / close times.

**Comment by dominiclapointe** [comment]
Hum i wont argue but doesnt have the same feeling here. Even tough its true that crypto runs 24/7, having some triggered events (new days, new months, x amount of profit (+ or -) in automated process is quite always a good idea in order to do quick routine task, evaluations of the current state etc instead of having to process them on each iteration (tick) or outside of Freqtrade... For example, one could want to send an email everyday with the current profit for a specific bot, or update an in house DB to run BI on it (aggregating all the bots, for ex)... those entry points could be very relevant even tough our specific market doesn't stop... In general, those kind of trigger have not much CPU impact nor creates lag (depending on the implementation off course) and could allow for quite a few new possibilities... 

Being quite new to quant trading, ill take your word but in general, i cant agree with that sentence...

Anyways, thanks for your clear answer and good job for this awesome platform!

**Comment by xmatthias** [comment]
Each of the examples you point out should usually be ran from outside of the bot (maybe as a cron-job), as they are not required for bot operations - and as such, should not have the potential to slow the bot - which can potentially cost you money/profits.

While you could trigger a BI "whatever" - if that takes ~1 minutes to update - your bot will be blocked for that minute - potentially missing a (not on exchange) stoploss - or another sell.
 The same is with email (assuming the server is down / slow / unreachabel at that moment) - it would wait for the timeout.
