### ISSUE TITLE
Order book data for back testing

### ISSUE THREAD

**Issue by snussik** [freqtrade/freqtrade#5274]
Is it possible somehow to use order book data for backtesting? I’ve seen notice in [docs: ](https://www.freqtrade.io/en/stable/strategy-customization/#orderbookpair-maximum) but didn’t understand it. 
In what format should I modify data source to be able to use it in backtesting?

**Comment by xmatthias** [comment]
You cannot use orderbook data in backtesting.

The orderbook dataprovider gives you is data from the moment you call it - not from history.
As such - you'd be using current prices / current volumes in your strategy - which will obviously not reflect the situation from a few weeks (or more) ago.

Also, exchanges do not provide historic orderbook data - and as such - it's impossible to download and use this data in backtesting.
