### ISSUE TITLE
Binance: Cancelling open sell Order for BEAM/USDT (#12). Reason: forcesold.

### ISSUE THREAD

**Issue by momo3232** [freqtrade/freqtrade#5276]
## Describe your environment

  * Operating system: windows server 2016
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Binance: Cancelling open sell Order for BEAM/USDT (#12). Reason: forcesold.
Created sell order for trade 12.
I always have this Cancelling problem in dry run after forcesell 
what should i do
I've used several times forcell after that but it didn't work
it doesn't sell

and is it possible to create a sell order immediately after open buy order in 1% profit price?
thank you

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
forcesells are subject to regular [pricing configuration](https://www.freqtrade.io/en/stable/configuration/#prices-used-for-orders).
As such - they may or may not fill depending on your configuration (also in dry-run).

You can however also change forcesell reasons to market as [documented here](https://www.freqtrade.io/en/stable/configuration/#understand-order_types).

**Comment by momo3232** [comment]
thanks
before that i use forcesell 
i have this comment on telegram 

🔵 Binance: Buying CHR/USDT (#3)
Amount: 1299.60000000
Open Rate: 0.19233000
Current Rate: 0.19233000
Total: (249.961 USDT, 249.961 USD)

after 15 minutes i have 

⚠ Binance: Cancelling open buy Order for CHR/USDT (#3). Reason: cancelled due to timeout, fully cancelled.

how can i fix it?
this is my config

unfilledtimeout": {
        "buy": 15,
        "sell": 30
    },
    "bid_strategy": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": true,
        "ignore_roi_if_buy_signal": false

**Comment by xmatthias** [comment]
Please read and understand (!) the [pricing documentation](https://www.freqtrade.io/en/stable/configuration/#prices-used-for-orders) as linked above. Then you will understand why your orders do not fill.

If you have problems understanding how prices work, best do research on how orderbooks and order filling on exchanges work. Explaining this is not part of the freqtrade documentation, but there's 100ds of tutorials on the internet to learn that from.

Providing you with a "working" configuration will not help you understand this - nor will you understand the implications this will have.

**Comment by momo3232** [comment]
thanks
