### ISSUE TITLE
Implementation Buy Reason 

### ISSUE THREAD

**Issue by yari0757** [freqtrade/freqtrade#5280]
## Describe the enhancement

*Thanks to all contributors. Freqtrade is great! I learn a lot.
my feature request is simple and straight forward. is there any way to implement Buy reason some thing like sell reason? After using Freqtrade more than 4 month, I have more than 30 buy conditions in populate_buy_trend  function and it should be great idea to see why buying some coin in telegram  and witch condition triggered?*

**Comment by xmatthias** [comment]
Please use the search to look for similar issues before opening duplicates.

Duplicate of #3081.
