### ISSUE TITLE
Average win and Average loss for pair in backtest result

### ISSUE THREAD

**Issue by quantsirius** [freqtrade/freqtrade#5282]
* Operating system: Ubuntu 20.04 
  * Python Version: Python 3.8.5
  * CCXT version: ccxt==1.51.77
  * Freqtrade Version: freqtrade 2021.6
  
**Hey guys.
For analyze of the strategy performance I use Average win and Average loss meaning for every pair. It is important also when you special backtest of the exit signals.
In previous version of Freqtrade (2021.4) I simple implemented it by add some little changes in /freqtrade/freqtrade/optimize/optimize_reports.py.
Main is two line below and some little for output in table.**

**It stopped work after new update. I can`t find out the reason by error log below. I would be really appreciate for any help. File also included.** 

'avgwin': round(result['profit_abs'][result['profit_abs'] > 0].sum() / len(result[result['profit_abs'] > 0]), 2),
'avgloss': round(result['profit_abs'][result['profit_abs'] < 0].sum() / len(result[result['profit_abs'] < 0]), 2),

2021-07-17 18:20:23,074 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/user/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/user/freqtrade/freqtrade/commands/optimize_commands.py", line 54, in start_backtesting
    backtesting.start()
  File "/home/user/freqtrade/freqtrade/optimize/backtesting.py", line 540, in start
    store_backtest_stats(self.config['exportfilename'], stats)
  File "/home/user/freqtrade/freqtrade/optimize/optimize_reports.py", line 35, in store_backtest_stats
    file_dump_json(filename, stats)
  File "/home/user/freqtrade/freqtrade/misc.py", line 76, in file_dump_json
    rapidjson.dump(data, fp, default=str, number_mode=rapidjson.NM_NATIVE)
ValueError: Out of range float values are not JSON compliant

**[optimize_reports.zip](https://github.com/freqtrade/freqtrade/files/6835173/optimize_reports.zip)**

**Comment by xmatthias** [comment]
The error is pretty clear - you've got either a .NaN or .INF / -INF in your result.

As this is a customization (non default) freqtrade version, please understand that i'll not debug the problems you have with it for you.

**Comment by quantsirius** [comment]
> The error is pretty clear - you've got either a .NaN or .INF / -INF in your result.

That helped thank you
