### ISSUE TITLE
High sharp ratio And weird hyperopt results 

### ISSUE THREAD

**Issue by AhmedA94** [freqtrade/freqtrade#5283]
Operating system: _ ubuntu 20.04___
  * Python Version: __3.8.10___ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _freqtrade-V___ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker
 
#5136   
Hi,
I am having weird hyperopt results also. I am optimizing a strategy with using dataset of last 29 days, and I obtain a high value for the sharp ratio. Still, with little profits  ( sharp ratio = 12 and profit = 1.64$), especially after changing the main currency from BTC to USDT. I believe that the high sharp ratio prevents taking risks or considering a high value to stop loss. Does anyone face the same problem? 
![2BB89716-7D81-4D51-B909-8F78649808AC](https://user-images.githubusercontent.com/87586536/126051878-c3bfe2e4-a66b-4405-ae2e-b2051b10c395.jpeg)

**Comment by xmatthias** [comment]
Please don't use screnshots (especially not photos of screens that are slightly tilted) - but use text output - that makes reading it a lot easier.

the size of sharpe-ratio is not really relevant, it's only used to compare results within the hyperopt result.
As long as better results produce higher ratios that'll work out just fine.

As you're having almost no losses, you'll obviously have a pretty high sharpe-ratio - which is augmented by having a lot of draws. That's not per se a problem - and better results are showing better objective values.

**Comment by AhmedA94** [comment]
Thanks for your reply.
