### ISSUE TITLE
Accessing Informative pairs data in Strategy analysis

### ISSUE THREAD

**Issue by szucsaaron2** [freqtrade/freqtrade#5286]
## Describe your environment

  * Freqtrade Version: latest stable (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi!

I have downloaded InformativeSample strategy (untouched) from the official strategies and I tried running the strategy analysis notebook, but I get an error when trying to run `df = strategy.analyze_ticker(candles, {'pair': pair})`

I get KeyError: 'close_15m' when trying to run it.

My goal would be to have a dataframe that includes the 5m and 1h tf indicators and values. How can I achieve this?

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
the [documentation](https://www.freqtrade.io/en/latest/strategy-customization/#complete-data-provider-sample) has a full sample about this.

The example does work as long as it's left untouched (using 5m as timeframe, and 15m as informative pair).
If you change this, then candle-references in the other methods will also need to be changed.

**Comment by szucsaaron2** [comment]
I don't know what could be wrong on my side, but it doesn't work. :/

I left the code untouched, and it gives me the KeyError.
I tried running the Complete Data-provider sample now and also before, but it still gives the same error.
I was running NostalgiaForInfinityV7 by Iterative on my server as well, and it had no problem running in live/dry run mode, but if I try to open it in the strategy analysis notebook, I get an error at this line
`assert self.dp, "some test here"`


I also have the pairs downloaded for both timeframes so that should also not be a problem.

**Comment by xmatthias** [comment]
Best make sure that the correct strategy file is loaded (you're passing in a class, so duplicate classes will load the first available class - which might not be the one you think it is).

Also - carefully check the logs that lead to that point - maybe you've got the timeframe in your configuration file which will overwrite the timeframe from the strategy.

**Comment by szucsaaron2** [comment]
I checked, but I can't find anything unusual, no double classes.

This is the code for the strategy file (I added the populate_sell_trend to the Complete Data-provider sample from the documentation) :

```
from freqtrade.strategy import IStrategy, merge_informative_pair
from pandas import DataFrame
import freqtrade.vendor.qtpylib.indicators as qtpylib


class InformativeSample(IStrategy):
    # strategy init stuff...

    timeframe = '5m'

    # more strategy init stuff..

    def informative_pairs(self):

        # get access to all pairs available in whitelist.
        pairs = self.dp.current_whitelist()
        # Assign tf to each pair so they can be downloaded and cached for strategy.
        informative_pairs = [(pair, '15m') for pair in pairs]
        # Optionally Add additional "static" pairs
        informative_pairs += [("ETH/USDT", "5m"),
                              ("BTC/TUSD", "15m"),
                            ]
        return informative_pairs

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        if not self.dp:
            # Don't do anything if DataProvider is not available.
            return dataframe

        inf_tf = '15m'
        # Get the informative pair
        informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf)
        # Get the 14 day rsi
        informative['rsi'] = ta.RSI(informative, timeperiod=14)

        # Use the helper function merge_informative_pair to safely merge the pair
        # Automatically renames the columns and merges a shorter timeframe dataframe and a longer timeframe informative pair
        # use ffill to have the 1d value available in every row throughout the day.
        # Without this, comparisons between columns of the original and the informative pair would only work once per day.
        # Full documentation of this method, see below
        dataframe = merge_informative_pair(dataframe, informative, self.timeframe, inf_tf, ffill=True)

        # Calculate rsi of the original dataframe (5m timeframe)
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)

        # Do other stuff
        # ...
        print(dataframe)
        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['rsi'], 30)) &  # Signal: RSI crosses above 30
                (dataframe['rsi_1d'] < 30) &                     # Ensure daily RSI is < 30
                (dataframe['volume'] > 0)                        # Ensure this candle had volume (important for backtesting)
            ),
            'buy'] = 1

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['rsi'], 30)) &  # Signal: RSI crosses above 30
                (dataframe['rsi_1d'] > 30) &                     # Ensure daily RSI is < 30
                (dataframe['volume'] < 0)                        # Ensure this candle had volume (important for backtesting)
            ),
            'sell'] = 1

        return dataframe
```

And here is the code in jupyter notebook that I use to access the strategy. This is where I get the error.

```
from pathlib import Path
from freqtrade.configuration import Configuration


config = Configuration.from_files([])

config["timeframe"] = "5m"
config["strategy"] = "InformativeSample"
data_location = Path(config['user_data_dir'], 'data', 'binance')
pair = "BTC"+"_USDT"

from freqtrade.data.history import load_pair_history

candles = load_pair_history(datadir=data_location,
                                timeframe=config["timeframe"],
                                pair=pair)

print("Loaded " + str(len(candles)) + f" rows of data for {pair} from {data_location}")
candles.head()

from freqtrade.resolvers import StrategyResolver
strategy = StrategyResolver.load_strategy(config)

df = strategy.analyze_ticker(candles, {'pair': pair})

```

**Comment by szucsaaron2** [comment]
I also tried modifying the populate_buy and sell function rules to generate buy/sell signals if high>low, to see if the problem is with the indicators. After this, I got the error that the dataframe object is None type.

**Comment by xmatthias** [comment]
The jupyter samples do not provide the dataprovider - as such, you will not be able to use them with informative pairs.

strategy should be fine during backtesting / real runs though - at least at a quick glance.
