### ISSUE TITLE
Adding an option in config to disable forcesell, just like how we have an option for forcebuy

### ISSUE THREAD

**Issue by stash86** [freqtrade/freqtrade#5296]
## Describe your environment
(if applicable)

  * Operating system: Ubuntu 20
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: docker-7acbc9a5 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

A way to disabling forcesell in the config.json, similar to how we can do it for forcebuy. I have looking through documentation and issues here, and can't find any relevant mention about it, so I assume it's not possible to disable forcesell for now

**Comment by xmatthias** [comment]
No that's not possible, and i don't see any need for that.

`/forcesell` has the intend to allow you to forcefully sell (close) all open positions in case of a market crash.
There's no reason to disable this (disabling would be an increased risk ...) - which is quite different to forcebuy - where you need to have a specific usecase to require this.
