### ISSUE TITLE
Trailing stoploss and custom_stoploss() behaviour

### ISSUE THREAD

**Issue by perkmeister** [freqtrade/freqtrade#5297]
Hi Matthias, I have a question about custom_stoploss() and how it behaves. My undestanding is that the returned value replaces the stoploss setting and is equivalent to changing this setting manually and reloading the config, is this correct? I particularly want trailing stoploss to work in the same way it did before, but I came across this in the docs and now a bit confused as to what 'already been adjusted' means or whether this is even relevant to the custom_stoploss()method:

"Stoploss values cannot be changed if trailing_stop is enabled and the stoploss has already been adjusted, or if Edge is enabled (since Edge would recalculate stoploss based on the current market situation)."

My intention is to have a stoploss value calculated using the average true range (ATR) indicator then change it to a smaller stoploss value once in profit, but for this trailing stoploss should work as normal. Thanks!

**Comment by xmatthias** [comment]
`custom_stoploss` returns the relative value against the current position.

changing static stoploss has nothing to do with that - and you can only change stoplosses via the reload route if the stoploss didn't start trailing yet.

Also - stoploss can only ever go up - so once the stoploss was placed at 95$, it will never be lowered to 94$, even if custom_stoploss would return doing that.
This will simply result in a "standstill" stoploss, which will wait for price to fall below it to trigger.

**Comment by perkmeister** [comment]
OK, thanks. So if trailing stoploss is enabled, returning a value from custom_stoploss() that is below the changed trailed value will have no effect, but if that value is above that trailed value it will? The doc suggested it wouldn't.

**Comment by xmatthias** [comment]
you shouldn't mix/match trailing stoploss with `custom_stoploss()` (this might be disabled / prevented at a future time) - and the fact that mixing is not a good idea is documented in the custom stoploss page.

The 2 different stoploss methods will compete with each other - with the higher value (closer to current price) being the winner.
As you can't be sure which one is active at which point, it'll result in usually not what you want.

As such -  if you're using custom_stoploss - then disable trailing and have custom_stoploss handle everything.

**Comment by perkmeister** [comment]
I missed the warning! Thanks for explaining.
