### ISSUE TITLE
 negativ Drawdown low

### ISSUE THREAD

**Issue by momo3232** [freqtrade/freqtrade#5298]
## Describe your environment

  * Operating system: windows server 2016
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hello, in my result i have  negativ Drawdown low but total profit is 30% and Min balance is 718.882 USDT  what is the meaning of this ( is my strategy lossing?

Backtesting from       | 2021-05-09 00:00:00 |
| Backtesting to         | 2021-05-22 00:00:00 |
| Max open trades        | 1                   |
|                        |                     |
| Total/Daily Avg Trades | 49 / 3.77           |
| Starting balance       | 1000.000 USDT       |
| Final balance          | 1299.720 USDT       |
| Absolute profit        | 299.720 USDT        |
| Total profit %         | 29.97%              |
| Avg. stake amount      | 1119.581 USDT       |
| Total trade volume     | 54859.471 USDT      |
|                        |                     |
| Best Pair              | 1INCH/USDT 25.99%   |
| Worst Pair             | CVC/USDT -17.57%    |
| Best trade             | 1INCH/USDT 12.69%   |
| Worst trade            | AKRO/USDT -17.57%   |
| Best day               | 90.545 USDT         |
| Worst day              | -50.861 USDT        |
| Days win/draw/lose     | 9 / 3 / 2           |
| Avg. Duration Winners  | 1:18:00             |
| Avg. Duration Loser    | 19:54:00            |
| Rejected Buy signals   | 398744              |
|                        |                     |
| Min balance            | 718.882 USDT        |
| Max balance            | 1344.698 USDT       |
| Drawdown               | 52.7%               |
| Drawdown               | 557.041 USDT        |
| Drawdown high          | 275.923 USDT        |
| Drawdown low           | -281.118 USDT       |
| Drawdown Start         | 2021-05-16 14:25:00 |
| Drawdown End           | 2021-05-19 12:50:00 |
| Market change          | -43.42%

**Comment by xmatthias** [comment]
Your starting balance is 1000$.
the drawdown low is 281$ below 1000$ (at 718$).

All of this is explained in detail [in the documentation](https://www.freqtrade.io/en/stable/backtesting/#summary-metrics).

**Comment by momo3232** [comment]
in the documentation. is A negative low value means initial capital lost
what is the meaning of initial ( i think that mean i lost all of my 1000$ balance, is this correct? )

**Comment by momo3232** [comment]
> Your starting balance is 1000$.
> the drawdown low is 281$ below 1000$ (at 718$).
> 
> All of this is explained in detail [in the documentation](https://www.freqtrade.io/en/stable/backtesting/#summary-metrics).

in the documentation. is A negative low value means initial capital lost
what is the meaning of initial ( i think that mean i lost all of my 1000$ balance, is this correct? )
