### ISSUE TITLE
initial capital lost

### ISSUE THREAD

**Issue by momo3232** [freqtrade/freqtrade#5302]
## Describe your environment

  * Operating system: windows server 2016
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

in the documentation. is A negative low value means initial capital lost
what is the meaning of initial ( i think that mean i lost all of my 1000$ balance, is this correct? )

**Comment by xmatthias** [comment]
Please make sure to read the documentation (i'd recommend to go through it once from top to bottom).
Also - please do some research yourself on how trading and markets work to avoid asking questions that could be found easily with a simple web search.

Initial capital can be configured in the configuration.
It's normal that a strategy will experience up and down periods.

If your down-period is early in the timerange selected, you'll see a drawdown into your initial capital.
Having or not having that does not mean too much - as past returns will not guarantee future returns.

For questions such as this, please use the [discord channel](https://discord.gg/p7nuUNVfP7) to get support / help from the community.
People there love to help assuming the documentation has been consulted first / some research has been done upfront..
