### ISSUE TITLE
Configurable PrecisionFilter

### ISSUE THREAD

**Issue by bzed** [freqtrade/freqtrade#5304]
Hi,

as some strategies use `stoploss = 0.999`  or similar settings as they handle the stoploss completely in custom_stoploss/custom_sell, the PrecisionFilter does not work at all for those strategies.
Please provide a way to configure the PrecisionFilter in a way that it allows to assume a specific stoploss, defaulting to the stoploss in the strategy if the option has not been set.

Something like
```
{
     "method": "PrecisionFilter",
    "precision": "0.25"
}
```

Thanks,
Bernd

**Comment by xmatthias** [comment]
Running without stoploss means your whole capital is at risk.
I strongly advise against this - as it's usually a bad idea and will result in good performance in bull markets, and tears in bear markets.


`PrecisionFilters` only purpose is to prevent coins which would not allow setting stoplosses - protecting the bot from unexpected errors based on the configuration.
To filter out general low-value coins, best use `PriceFilter`.
