### ISSUE TITLE
Plotting Problem

### ISSUE THREAD

**Issue by Angel2298** [freqtrade/freqtrade#5306]
## Describe your environment

  * Operating system: ____ubuntu 64 bits
  * Python Version: _____ (`python 3.8.10
  * CCXT version: _____ (`ccxt 1.15.40 
  * Freqtrade Version: ____ freqtrade develop-b8de3270

  
## Your question

When I try to use plot-dataframe, I cannot plot the results, I received the same error message: 

**ValueError: Invalid property specified for object of type plotly.graph_objs.layout.Modebar: 'add'**

To run the plot-dataframe I used the following command: 

**(.env) angel@angel-VirtualBox:~/freqtrade$ freqtrade plot-dataframe -p LINK/BTC --export-filename user_data/backtest_results/backtest-results-2021-07-21_19-25-25.json -s ANIMO --config config_binance.json**

The complete error message goes like this: 
```
**2021-07-21 20:19:13,139 - freqtrade.plot.plotting - INFO - analyse pair LINK/BTC
2021-07-21 20:19:13,244 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/angel/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/angel/freqtrade/freqtrade/commands/plot_commands.py", line 24, in start_plot_dataframe
    load_and_plot_trades(config)
  File "/home/angel/freqtrade/freqtrade/plot/plotting.py", line 566, in load_and_plot_trades
    fig = generate_candlestick_graph(
  File "/home/angel/freqtrade/freqtrade/plot/plotting.py", line 376, in generate_candlestick_graph
    fig.update_layout(modebar_add=["v1hovermode", "toggleSpikeLines"])
  File "/home/angel/freqtrade/.env/lib/python3.8/site-packages/plotly/basedatatypes.py", line 1403, in update_layout
    self.layout.update(dict1, overwrite=overwrite, **kwargs)
  File "/home/angel/freqtrade/.env/lib/python3.8/site-packages/plotly/basedatatypes.py", line 5067, in update
    BaseFigure._perform_update(self, kwargs, overwrite=overwrite)
  File "/home/angel/freqtrade/.env/lib/python3.8/site-packages/plotly/basedatatypes.py", line 3862, in _perform_update
    raise err
ValueError: Invalid property specified for object of type plotly.graph_objs.layout.Modebar: 'add'

Did you mean "color"?

    Valid properties:
        activecolor
            Sets the color of the active or hovered on icons in the
            modebar.
        bgcolor
            Sets the background color of the modebar.
        color
            Sets the color of the icons in the modebar.
        orientation
            Sets the orientation of the modebar.
        uirevision
            Controls persistence of user-driven changes related to
            the modebar, including `hovermode`, `dragmode`, and
            `showspikes` at both the root level and inside
            subplots. Defaults to `layout.uirevision`.
        
Did you mean "color"?

Bad property path:
modebar_add
        ^^^**
```

**Comment by xmatthias** [comment]
Please make sure you updated freqtrade properly following the [update guide](https://www.freqtrade.io/en/stable/updating/) for your installation approach.

Your versions (freqtrade version vs. ccxt version) show a rather huge disconnect (the ccxt verison is multiple years old, freqtrade a bit over a month) - so i suspect you didn't update dependencies properly (in this case plotly that's causing the issue - but other things might cause "hidden" issues, too).
