### ISSUE TITLE
the buy and sell in the same pair not working properly?

### ISSUE THREAD

**Issue by userdz0** [freqtrade/freqtrade#5311]
hi ... i would like to know if the bot support this trade method or not?:
"the bot search for trading pair with custom volatility... we assume it find UQC/BTC pair... the bot now buy UQC with all BTC amount and then the bot sell UQC for BTC and take profit and then the bot search another time for trading pair with custom volatility and trade with the same method for the second pair..."
if the bot support this method how to configure it?
i test freqtrade bot with live mode and custom volatility pair filter but it not selling ... it just buy the first pair which it find and the second step is not selling the avaible balance but keep buying with BTC and the avaible amount of BTC is used in the first trade... how to make the bot permanent and make it trade with avaible balance asset?

**Comment by xmatthias** [comment]
Freqtrade has multiple ways to sell a pair, but its your strategy that tells it how and when.
You should also always use backtesting and dry-run before investing any real money to get a feel how (and be sure that) your strategy wkrks the way you expect it to.

I'd recommend to read the whole [documentation](https://freqtrade.io) at least once to get an overview on the offered functionalities of freqtrade.

**Comment by userdz0** [comment]
i read the documentation but i dont know how the strategy file should be... can you please guide me?
