### ISSUE TITLE
PR #5284 causing a spammy console log

### ISSUE THREAD

**Issue by samgermain** [freqtrade/freqtrade#5316]
## Describe your environment

  * Operating system: MacOS Big Sur 11.4
  * Python Version: Python 3.9.5 
  * CCXT version: ccxt==1.52.83
  * Freqtrade Version: freqtrade develop-b84a1d0c
  
## Describe the problem:

In the PR I mentioned that these changes were made
I'm not 100% sure if all these changes should be made, and people were complaining about a [spammy console log,](https://i.imgur.com/RPN1b0Y.png) so I reversed the second and third change in this table and will push a PR right away.

<table style="width:100%">
  <tr>
    <th>get_buy_rate</th>
    <th>get_sell_rate</th> 
    <th>update</th>
  </tr>
  <tr>
    <td>if bid_strategy.get('use_order_book', False) and ('use_order_book' in bid_strategy):</td>
    <td>if ask_strategy.get('use_order_book', False)</td>
    <td>if strategy.get('use_order_book', False) and ('use_order_book' in strategy) is now used for both</td>
  </tr>
  <tr>
    <td>logger.info(f"{name} price from orderbook {bid_strategy['price_side'].capitalize()}"
                        f"side - top {order_book_top} order book buy rate {rate:.8f}")</td>
    <td>/</td>
    <td>Both the bid_strategy and ask_strategy have this logger message now</td>
  </tr>
    <td>logger.info(f"Using Last {strategy['price_side'].capitalize()} / Last Price")</td>
    <td>/</td>
    <td>Both the bid_strategy and ask_strategy have this logger message now</td>
  </tr>
  <tr>
     <td>/</td>
     <td>if rate is None: raise PricingError(f"{name}-Rate for {pair} was empty.")</td>
     <td>Both raise this pricing error now</td>
  </tr>

</table>

### Steps to reproduce:

run `freqtrade trade`
  
### Observed Results:

https://i.imgur.com/RPN1b0Y.png

------------------

@xmatthias Maybe just double check the changes in the table and determine if they are all good changes

**Comment by xmatthias** [comment]
Well you closed this yourself in #5317 👍 💯
