### ISSUE TITLE
Crossed_above() missing 1 required positional argument: 'series2' and WARNING - Lengths must match to compare

### ISSUE THREAD

**Issue by eveli909** [freqtrade/freqtrade#5330]
I am trying to implement the code and have several questions. The idea is to spot when Bollinger Bands are inside Keltner Channels and to enter the trade when the Bollinger bands get out of Keltner Channels.
1. Have I correctly stated the buy requirements for Bollinger Bands crossing the Keltner Channels?
2. I tried the following options and got errors and warnings. Could anybody please point out where is a mistake?
First example:
```
import numpy as np  # noqa
 import pandas as pd  # noqa
 from pandas import DataFrame

  from freqtrade.strategy import IStrategy
  from freqtrade.strategy import CategoricalParameter, DecimalParameter, IntParameter

  import talib.abstract as ta
  import freqtrade.vendor.qtpylib.indicators as qtpylib

    class BPB(IStrategy):
    
    INTERFACE_VERSION = 2

    minimal_roi = {
        "60": 0.01,
        "30": 0.02,
        "0": 0.04
    }

    stoploss = -0.08

    trailing_stop = False

    # Hyperoptable parameters
    buy_rsi = IntParameter(low=1, high=50, default=30, space='buy', optimize=True, load=True)
    sell_rsi = IntParameter(low=50, high=100, default=70, space='sell', optimize=True, load=True)

    timeframe = '15m'

    process_only_new_candles = False

    use_sell_signal = True
    sell_profit_only = False
    ignore_roi_if_buy_signal = False

    startup_candle_count: int = 26

    order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }

    order_time_in_force = {
        'buy': 'gtc',
        'sell': 'gtc'
    }

    plot_config = {
        'main_plot': {
            'tema': {},
            'sar': {'color': 'white'},
        },
        'subplots': {
            "MACD": {
                'macd': {'color': 'blue'},
                'macdsignal': {'color': 'orange'},
            },
            "RSI": {
                'rsi': {'color': 'red'},
            }
        }
    }

    def informative_pairs(self):
      
        return []

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

            # Bollinger Bands
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband'] = bollinger['lower']
        #dataframe['bb_middleband'] = bollinger['mid']
        dataframe['bb_upperband'] = bollinger['upper']
        
            # Keltner Channel
  
        keltner = qtpylib.keltner_channel(dataframe, window=20, atrs=1.5)
        
        dataframe["kc_upperband"] = keltner["upper"]
        dataframe["kc_lowerband"] = keltner["lower"]
        dataframe["kc_middleband"] = keltner["mid"]

            # MACD
        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        dataframe['macdhist'] = macd['macdhist']

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        dataframe.loc[
            (
            (qtpylib.crossed_below(dataframe['bb_lowerband'], dataframe['kc_lowerband'])) &
            qtpylib.crossed_above(dataframe['bb_upperband'], dataframe['kc_upperband'])) &
            (dataframe["close"] > dataframe['bb_upperband']) &
            (dataframe['macd'] > 0)

            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        dataframe.loc[
            (
                (dataframe['macd'].shift(2) < dataframe['macd'].shift(3)) &
                (dataframe['macd'].shift(1) < dataframe['macd'].shift(2)) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'sell'] = 1
        return dataframe
```
For the code above I get following warning and error:

return self.populate_buy_trend(dataframe, metadata)
  File "/home/zxz/freqtrade/user_data/strategies/BBBB.py", line 221, in populate_buy_trend
    qtpylib.crossed_above(dataframe['bb_upperband'] > (dataframe['kc_upperband'])) &
TypeError: crossed_above() missing 1 required positional argument: 'series2'
2021-07-26 23:52:37,814 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair TOMO/BTC: crossed_above() missing 1 required positional argument: 'series2'
2021-07-26 23:52:37,897 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error crossed_above() missing 1 required positional argument: 'series2' calling <bound method IStrategy._analyze_ticker_internal of <BPB.BPB object at 0x7fd8bcb86490>>
Traceback (most recent call last):
  File "/home/zxz/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/home/zxz/freqtrade/freqtrade/strategy/interface.py", line 394, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/home/zxz/freqtrade/freqtrade/strategy/interface.py", line 374, in analyze_ticker
    dataframe = self.advise_buy(dataframe, metadata)
  File "/home/zxz/freqtrade/freqtrade/strategy/interface.py", line 747, in advise_buy
    return self.populate_buy_trend(dataframe, metadata)
  File "/home/zxz/freqtrade/user_data/strategies/BBBB.py", line 221, in populate_buy_trend

2. Second example:
```
def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

          dataframe.loc[
              (
              qtpylib.crossed_below(dataframe['bb_lowerband'],['kc_lowerband']) &
              qtpylib.crossed_above(dataframe['bb_upperband'],['kc_upperband']) &

              (dataframe["close"] > dataframe['bb_upperband']) &
              (dataframe['macd'] > 0)
              
              ),
              'buy'] = 1

          return dataframe
 ```

For the second example I get following warning:
2021-07-27 00:09:32,068 - freqtrade.strategy.strategy_wrapper - WARNING - Strategy caused the following exception: ('Lengths must match to compare', (999,), (1,))<bound method IStrategy._analyze_ticker_internal of <BPB.BPB object at 0x7f66359df580>>
2021-07-27 00:09:32,070 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair VET/BTC: ('Lengths must match to compare', (999,), (1,))

**Comment by xmatthias** [comment]
`qtpylib.crossed_above()` is a method which requires to functions.
based on the exception - you're using `qtpylib.crossed_above(dataframe['bb_upperband'] > (dataframe['kc_upperband']))` - which should be changed to `qtpylib.crossed_above(dataframe['bb_upperband'],  dataframe['kc_upperband'])`.

This does however not correspond to the provided methods ... (also the strategy name seems to be different - assuming strategy and filename match).


the 2nd case is similarily simple with `qtpylib.crossed_below(dataframe['bb_lowerband'],['kc_lowerband']) &` - which needs to be `qtpylib.crossed_below(dataframe['bb_lowerband'], dataframe['kc_lowerband']) &` (and other occurances as well, obviously.

I'd strongly recommend to use an editor with syntax highlighting like vscode with the python plugin, which will usually point out such errors right in the editor.

**Comment by eveli909** [comment]
Thanks a lot! If I understand correctly, the cause of the errors was uncorrect syntax?

**Comment by xmatthias** [comment]
yes it is - depending on the case, you're not passing in 2 arguments (or not passing in 2 series) - neither of which is correct syntax.
