### ISSUE TITLE
freqtrade trade liverun not buying

### ISSUE THREAD

**Issue by JasonObihara** [freqtrade/freqtrade#5331]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*
Freqtrade runs well in dry run. But a liverun doesn't give any buys, just error messages.  0.0 BTC available which is less than stake amount. Some other error messages too.  I'm from the UK, not sure if it has anything to do with UK withdrawal, deposit issues.

**Comment by xmatthias** [comment]
the error simply suggests that your account does not have any BTC available (or your configured `stake_amount` is higher than the available balance).
With the bot running in live - you can use `/balance` to check for the balance your account has.

I suspect that shows 0.0 for BTC - which means you've got no money in your account (or the API keys don't have permission to see the account funds).

**Comment by JasonObihara** [comment]
Thanks Matthias,
All of a sudden, when i tried it now it works perfect. Checked balance from telegram, and it states 35 pounds, which is the same amount it states on binance. I had thought of that idea earlier and changed the api and secret keys. I'm guessing it took time for the new key to kick in. Somehow the original key didn't work.

Jason 

    On Tuesday, 27 July 2021, 18:49:55 BST, Matthias ***@***.***> wrote:  
 
 


the error simply suggests that your account does not have any BTC available (or your configured stake_amount is higher than the available balance).
With the bot running in live - you can use /balance to check for the balance your account has.

I suspect that shows 0.0 for BTC - which means you've got no money in your account (or the API keys don't have permission to see the account funds).
