### ISSUE TITLE
Unable to understan

### ISSUE THREAD

**Issue by jayden11234** [freqtrade/freqtrade#5332]
## Describe your environment

  * Operating system: win 10
  * Python Version: _____ (`python -V`) 3.8
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker) latest
  
## Your question

error :
 Unable to analyze candle (OHLCV) data for pair BTC/USDT: name 'hma' is not defined

**Comment by xmatthias** [comment]
You will need to create the "hma" column in the dataframe as part of populate_indicators.

if that's not done, then obviously hma will not be available.

**Comment by jayden11234** [comment]
> You will need to create the "hma" column in the dataframe as part of populate_indicators.
> 
> if that's not done, then obviously hma will not be available.

I dont have much expertise can you please help ?

**Comment by xmatthias** [comment]
With the provided information - not really.

Best look at the existing / available strategies in the [strategy repository](https://github.com/freqtrade/freqtrade-strategies/) to understand how to write strategies for freqtrade.
We also strongly recommend to read through the [documentation](https://www.freqtrade.io/) - while it's quite long, it'll provide you with a good starting point in writing successfull strategies.

**Comment by jayden11234** [comment]
I am unable to understand how to create the "hma" column in the dataframe I have gone through the documentation multiple times still cant find anything. Is this how we add it to populate_indicators? dataframe['hma'] = qtpylib.hma()

**Comment by xmatthias** [comment]
almost

maybe use `dataframe['hma'] = qtpylib.hma(dataframe['close'], 9)` (this is for a hma with a lookback of 9).

Obviously, the lookback / timeperiod you're looking for will depend on your needs - so that's up for you to pick - and 9 is not a recommendation, just an example value.
