### ISSUE TITLE
Debug Freqtrade with vscode

### ISSUE THREAD

**Issue by tim-hari** [freqtrade/freqtrade#5333]
## Describe your environment

  * Operating system: Linux(Ubuntu 18)
  * Python Version: 3.7.5
  * CCXT version: 1.51.77
  * Freqtrade Version: 2021.6
  
## Your question

With the earlier version of freqtrade, it was easy to debug(vs code debugger) main.py as command-line arguments are directly supplied and can interfere within main.py.
However, with the latest version, I'm having a hard time understanding how "freqtrade trade --config config.json .." command is triggering main and by the time it reaches main sysargv -> None

Could you please help me understand how to debug main.py within vscode instead of calling freqtrade from the command line

**Comment by xmatthias** [comment]
`main.py` is still the main entrypoint to freqtrade (and probably will remain that)  - so supplying any arguments to this will still work.
this is no longer documented and for productive use, i'd always use the freqtrade command (it's also simpler for non-developer programmers, as it's just a command, not a file + path they need to get right) - but there's in practice no difference to using `python freqtrade/main.py ...` and `freqtrade ...` (or even `python -m freqtrade ...`).

the command (`freqtrade ...` ) is created using the [setuptools entrypoints](https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html) method - which automatically creates an executable file in the proper folder to enable the file in your path with activated virtual environment.
I'm not sure if debugging with the entrypoint directly will even work - usually it'll have to point to a file - where main.py will work perfectly fine.

**Comment by tim-hari** [comment]
> `main.py` is still the main entrypoint to freqtrade (and probably will remain that) - so supplying any arguments to this will still work.
> this is no longer documented and for productive use, i'd always use the freqtrade command (it's also simpler for non-developer programmers, as it's just a command, not a file + path they need to get right) - but there's in practice no difference to using `python freqtrade/main.py ...` and `freqtrade ...` (or even `python -m freqtrade ...`).
> 
> the command (`freqtrade ...` ) is created using the [setuptools entrypoints](https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html) method - which automatically creates an executable file in the proper folder to enable the file in your path with activated virtual environment.
> I'm not sure if debugging with the entrypoint directly will even work - usually it'll have to point to a file - where main.py will work perfectly fine.

Thank you for the swift reply, I got setup tools and how freqtrade command acting as an alias instead of calling main.py. 

The main point I got stuck at was, printing sysargv within main.py returning None, However, sys.argv is returning all command line args. 
This might be a potential bug, as calling main.py directly not returning desired output instead of the freqtrade command.

Please let me know if I'm missing something here.

**Comment by xmatthias** [comment]
I'm not sure i get your point.

i've never had a problem with this - and all argument parsing is done by argparse anyway.

**Comment by aziba353** [comment]
@xmatthias 
Is there anyway to have breakpoint in our strategy file in debug mode while using Docker and pycharm?

**Comment by xmatthias** [comment]
@aziba353 in that combination, probably no.

it might work with vscode with the remote extensions - but that's something you should research independently of freqtrade - as it's really a generic "does my editor do" question.
