### ISSUE TITLE
How to get optimized indicator parameter values

### ISSUE THREAD

**Issue by AetherWaves** [freqtrade/freqtrade#5337]
## Describe your environment

  * Operating system: Win10
  * Python Version: 3.8.10
  * CCXT version: 1.52.36
  * Freqtrade Version: freqtrade develop-791dfd9b
  
## Your question

If the same indicator parameter is being optimized for dataframe signal used for both buy and sell, which parameter space should be used for it?
If no space is explicitly defined like in the docs, the optimized value is not occuring in the hyperopt results.
I decided to use the "buy"-space for it, but not sure if then this parameter is optimized for "sell" too ?
Should i split the space into buy and sell in order to get the desired behaviour?
Hear the example:

   # Buy hyperspace params:
    buy_params = {
        "rsi_buy": 30,
        "rsi": 14,
        "bb_stds": 2.0,
    }

    # Sell hyperspace params:
    sell_params = {
        "rsi_sell": 70,
    }

    rsi_buy = IntParameter(low=5, high=50, default=30, space='buy', optimize=True, load=True)
    rsi_sell = IntParameter(low=50, high=95, default=70, space='sell', optimize=True, load=True)

    # these parameters are used at buy and sell simultaneosly, but which space to use here ???
    rsi = IntParameter(low=10, high=18, default=14, space='buy', optimize=True, load=True)
    bb_stds = DecimalParameter(low=1.5, high=2.5, decimals=1, default=2.0, space='buy', optimize=True, load=True)

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
         for i in self.rsi.range:
            dataframe[f'rsi_{i}'] = ta.RSI(dataframe, timeperiod=i)

        # Bollinger bands
        for i in self.bb_stds.range:
            bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=i)
            dataframe[f'bb_lowerband_{i}'] = bollinger['lower']

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                    (dataframe[f'rsi_{self.rsi.value}'] < self.rsi_buy.value) &
                    (dataframe['close'] < dataframe[f'bb_lowerband_{self.bb_stds.value}'])

            ),
            'buy'] = 1
        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                    (dataframe[f'rsi_{self.rsi.value}'] > self.rsi_sell.value)

            ),
            'sell'] = 1
        return dataframe

**Comment by xmatthias** [comment]
The split between buy and sell is really arbitrary (helps you to only optimize small spaces) - at least when using the new hyperopt interface (which you are using).

You could technically have all values in the buy space and use them in buy or sell - but i usually keep them in the space you're using it for.

Often, you'll also want the values optimized separately (if you use bb_std in buy and sell methods). 
Maybe a value of 2 std is good for buying, but selling would be better to use 2.5?

In your case, you're using it only for the buy signal, so for clarity, i'd keep it in the buy space for sure.

**Comment by xmatthias** [comment]
I hope the above gives you enough hints to get this working.

If you have further questions relating to this, please use the [discord channel](https://discord.gg/p7nuUNVfP7) to get support / help from the community.
People there love to help assuming the documentation has been consulted first.
