### ISSUE TITLE
ERROR: ICP is not available as stake on Binance.

### ISSUE THREAD

**Issue by knl** [freqtrade/freqtrade#5340]
## Describe your environment

  * Operating system: ____macOS
  * Python Version: _____ Python 3.9.5
  * CCXT version: _____ ccxt==1.53.72
  * Freqtrade Version: ____ freqtrade develop-a7b8de92
  
## Your question

I have some ICP coins that I want to trade for BTC. If I try setting `stake_currency` to `ICP` and `pair_whitelist` to `["ICP/BTC"]` I get the error from the subject. If I change the `stake_currency` to `BTC`, `freqtrade` is not doing any trades (after waiting for 30min), neither in the real mode, nor in the dry run.

I'm also puzzled by the error, since I'm able to trade/sell ICPs on Binance.

It might be the case that I'm not understanding the terminology here, and freqtrade should be able to do trades, but I need to be more patient?

**Comment by xmatthias** [comment]
Stake-currency equals to the quote currency, and is therefore BTC.
ICP is not a valid stake-currency on binance - so the message is correct.

For the "not doing trades" - please read the [faq entry](https://www.freqtrade.io/en/stable/faq/#i-have-waited-5-minutes-why-hasnt-the-bot-made-any-trades-yet) for this point. 
It'll solely depend on your strategy when / how many trades are made.

backtesting should tell you roughly what to expect from a strategy - there's strategies that do only a few trades per week - so 30 minutes means nothing.

You should also make sure to look at the log - if freqtrade receives buy signals (your strategy tells it to buy) and there's something wrong you will find that message there.
