### ISSUE TITLE
startup_candle_count does not load informative timeframes in the backtest/hyperopt (ie. 1h, 4h and 1d)

### ISSUE THREAD

**Issue by m1hah** [freqtrade/freqtrade#5342]
## Describe your environment
Operating system: Windows 11 (WSL)
Python Version: Python 3.8.10 
CCXT version: 1.52.4 
Freqtrade Version: docker-03a4ae46 and develop-3503fdb4

## Describe the enhancement
Currently, the `startup_candle_count` loads only the candles based on the main timeframe of the strategy. Some strategies use many informative timeframes, but the data is not properly loaded, and the results are not correct.

Example:
Buy signal of the strategy requires `rsi_5m` and `rsi_4h` to be below `30`.
We set the `startup_candle_count` to `14` as that's all we need for RSI calculation.

We start the backtest, but the data only loads 14x 5min candles before our `--timerange`.  There is a lot of time in the beginning of the backtest/hyperopt to not work as expected.

*Explain the enhancement you would like*
Backtest should load `startup_candle_count` of the informative timeframes as well.

This would make backtests more precise.
As hyperopt is using backtest, optimizing the strategies would be better as well.

**Comment by xmatthias** [comment]
> Describe your environment
Not applicable.

Please fill out the issue template properly. Even if you think it's not requried - it is.
Ohterwise i'll assume you're using an outdated version and simply close this issue.

A template so you can copy-paste and ifll in your environment:
  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

**Comment by m1hah** [comment]
> > Describe your environment
> > Not applicable.
> 
> Please fill out the issue template properly. Even if you think it's not requried - it is.
> Ohterwise i'll assume you're using an outdated version and simply close this issue.
> 
> A template so you can copy-paste and ifll in your environment:
> 
> * Operating system: ____
> * Python Version: _____ (`python -V`)
> * CCXT version: _____ (`pip freeze | grep ccxt`)
> * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

Sure, done.
Thank you!

**Comment by xmatthias** [comment]
The great news is - this was implicitly added in #5287.

Simply updating to an uptodate version (your's are 2 weeks and ~1 month old) will get you what you need.

All credits for this will have to go to @GeorgeMurAlkh - who provided this functionality

**Comment by m1hah** [comment]
Thank you, develop was successfully updated, and backtest results are quite different. 👍 
Apparently, there was not update to the develop_plot I was using.
