### ISSUE TITLE
Please, make the tradable_balance_ratio broader

### ISSUE THREAD

**Issue by potens1** [freqtrade/freqtrade#5344]
## Describe the enhancement

I would like the `tradable_balance_ratio` to be broader than it is defined into the schema, to be more explicit, I would like to setup my bot to use 4.5% of my account availability.

Right now 90% of my account in hodl, and I would like to run two strategies on the remaining part, each with 4.5%, but right now the schema required to use at least 10%. (I don't think there was a technical reason, just an arbitrary choice made to have a minimum value)

I don't know if this is useful for a lot of people, but, it does not cost either to implement it and gives more granularity with what we can do with the bot

Thanks a lot

**Comment by xmatthias** [comment]
Tthe "tradable_balance_ratio" acts against stake-amount only (not against the whole wallet) - so if it's in hodl - it's probably in other currencies as HODL - so your calculation would be wrong anyway.
Obviously you could be using BTC as stake, and hodl BTC at the same time - but then you'll encounter another problem with your configuration.


As you intend to use 2 different strategies, you'll be using 2 different bots on the same account.
This is not supported (and problematic when used) with `tradable_balance_ratio` and leads to problems (one bot will influence the trade sizes of the other bot and viceversa - as the 4.5% is always calculated against the remaining stake + what's in trades for the current bot - but it's not aware of the 4.5% of the account the other bot has in positions).


Instead, you should use the newly introduced [`available_capital` setting](https://www.freqtrade.io/en/stable/configuration/#assign-available-capital) when using more than 1 bot on the exchange.
This acts as starting capital (and will still allow you to compound gains).

An alternative way is to use static stake amounts - where the maximum investment for the bot is `stake_amount * max_open_trades`.

**Comment by potens1** [comment]
Hello, thank you for the time taken to answer.
I will have a try with this parameter,I'm just wondering if this written into the database, or if it is applied again each time restart freqtrade or reread the config.

Once again, thanks a lot

**Comment by xmatthias** [comment]
It's used as starting capital (similar to dry-run-wallet) - so it'll factor in closed profits to get to the "currently tradable" value (if you gave it 500$ at the start and made 50$ profit - the setting of 500 will still have 500$ as starting point.

**Comment by potens1** [comment]
Sorry, I'm not completely sure I understand what you mean.

Do you mean that:

A:
--
1) first run starting point is 500
2) it makes 50 profits
3) from now the bots work on 550
3) I reload/restart, the starting point is back to 500

or:

B:
--
1) first run starting point is 500
2) it makes 50 profits
3) from now the bots work on 550
3) I reload/restart, the starting point is still 550

Thank you.

**Comment by xmatthias** [comment]
Unless you modify the configuration (or your wallet is reduced below what the bot "assumes" by withdrawing or doing manual trades), the bot will use the "initially assigned capital" +/- eventual profits/losses as it's "current wallet size" - ignoring all other assets.
restarting the bot will not change this - as it'll still be aware of the profits so far - and of open positions at this point.

**Comment by potens1** [comment]
Great ! Thanks a lot for your answer !
