### ISSUE TITLE
`freqtrade webserver` doesn't recognize `-s` and `--strategy` parameters

### ISSUE THREAD

**Issue by TheJoeSchr** [freqtrade/freqtrade#5345]
## Describe your environment

  * Operating system: arch
  * Python Version: 3.9 (`python -V`)
  * Freqtrade Version: freqtrade develop-6d19b263e

## Describe the problem:
I ran `freqtrade webserver -c user_data/config.json --strategy dork_v4`
and instead of webserver starting with backtest as described in docs, freqtrade returned
```shell
usage: freqtrade [-h] [-V]
                 {trade,create-userdir,new-config,new-hyperopt,new-strategy,download-data,convert-data,convert-trade-data,list-data,backtesting,edge,hyperopt,hyperopt-list,hyperopt-show,list-exchanges,list-hyperopts,list-markets,list-pairs,list-strategies,list-timeframes,show-trades,test-pairlist,install-ui,plot-dataframe,plot-profit,webserver}
                 ...
freqtrade: error: unrecognized arguments: --strategy dork_v4

```

I'm not sure if either the docs should not contain the `-s` option or if it is a bug in freqtrade, otherwise I would have tried to do a PR

**Comment by xmatthias** [comment]
Docs were wrong.
there's no need (and reason) to pass in the strategy - instead, you can interactively pick the strategy in the UI and therefore compare different strategies.
