### ISSUE TITLE
Signal and then buy in specific price

### ISSUE THREAD

**Issue by DanielRoig** [freqtrade/freqtrade#5358]
## Your question

Hi, I would like to know if there ara any way to place an order in specific price when a signal appears. For example, if an EMA reach a specific price X then place an order when price is 2% above that EMA when the EMA reached that X price.
Thanks!

**Comment by xmatthias** [comment]
Defining order-prices is currently not possible - but will be implemented in #5347.

When you look at "above current price" however, you'll need to be very careful. 
Buy limit orders will act as market orders if placed with a price > current price - and as such will fill immediately (they're also called marketable limit orders).

You can however fetch the current price from the [orderbook via dataprovider](https://www.freqtrade.io/en/stable/strategy-customization/#orderbookpair-maximum) to fetch the price and only issue buy-signals once your target-price has been reached,

or use [confirm_trade_entry](https://www.freqtrade.io/en/stable/strategy-advanced/#trade-entry-buy-order-confirmation) to prevent orders from being placed before they reach your limit.

**Comment by DanielRoig** [comment]
So helpful answer. Thank you!
