### ISSUE TITLE
Installation on an M1 mac

### ISSUE THREAD

**Issue by hebawom** [freqtrade/freqtrade#5359]
I did the git clone and then used the setup.sh script.
This errored out on the tables requirement.
I figured out that I had to manually install HDF5 and BLOSC via macports since the homebrew version is not aarch64 compatible.
However, now when I run setup.sh it gets past the previous error install tables, but now it get stuck at numpy, with this error:

```
########### EXT COMPILER OPTIMIZATION ###########
    Platform      :
      Architecture: aarch64
      Compiler    : clang
  
    CPU baseline  :
      Requested   : 'min'
      Enabled     : NEON NEON_FP16 NEON_VFPV4 ASIMD
      Flags       : none
      Extra checks: none
  
    CPU dispatch  :
      Requested   : 'max -xop -fma4'
      Enabled     : ASIMDHP ASIMDDP
      Generated   :
                  :
      ASIMDHP     : NEON NEON_FP16 NEON_VFPV4 ASIMD
      Flags       : -march=armv8.2-a+fp16
      Extra checks: none
      Detect      : ASIMD ASIMDHP
                  : numpy/core/src/umath/_umath_tests.dispatch.c
    CCompilerOpt._cache_write[796] : write cache to path -> /private/var/folders/ld/pdcntnn15kv_hk9vf4zgqs4c0000gn/T/pip-install-tivb6zo2/numpy_e8ceb40ff0094b5dab7fcc069beb786c/build/temp.macosx-11-arm64-3.9/ccompiler_opt_cache_ext.py
  
    ########### CLIB COMPILER OPTIMIZATION ###########
    Platform      :
      Architecture: aarch64
      Compiler    : clang
  
    CPU baseline  :
      Requested   : 'min'
      Enabled     : NEON NEON_FP16 NEON_VFPV4 ASIMD
      Flags       : none
      Extra checks: none
  
    CPU dispatch  :
      Requested   : 'max -xop -fma4'
      Enabled     : ASIMDHP ASIMDDP
      Generated   : none
    CCompilerOpt._cache_write[796] : write cache to path -> /private/var/folders/ld/pdcntnn15kv_hk9vf4zgqs4c0000gn/T/pip-install-tivb6zo2/numpy_e8ceb40ff0094b5dab7fcc069beb786c/build/temp.macosx-11-arm64-3.9/ccompiler_opt_cache_clib.py
    ----------------------------------------
    ERROR: Failed building wheel for numpy
  Failed to build numpy
  ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
```

I looked around the internet for this type of error and someone suggested to run:
`pip install --upgrade pip setuptools wheel`
but still no beans.

Has anyone got this working on an M1 mac?

**Comment by valbtw** [comment]
Same problem at the exact same time 😅
Have you found any solutions?

**Comment by xmatthias** [comment]
What python version are you using?

(issues without the issue template filled out will be closed without warning in the future!).

---

Unfortunately, M1 (arm64) architecture is an edge-case, new architecture with very limited support in the python space (no wheels available for many packages - depending on the python version).
As such - you'll need to have all necessary build-dependencies for dependent projects available - which is often a "track down package after package".

Numpy does provide arm64 wheels for python 3.8 and 3.9 - so you're most likely on another python version (This is where the issue template comes into play - which now results in unnecessary back and forth).

the setup.sh script will currently not support arm64 - and there is currently no intend on doing so either.


Freqtrade provides a multi-arch docker image which includes arm64, which will therefore also work on a M1.

**Comment by hebawom** [comment]
https://www.freqtrade.io/en/latest/installation/#manual-installation
This worked for me
