### ISSUE TITLE
Buy timeout sometimes results in trade below minimum order quantity

### ISSUE THREAD

**Issue by stephendade** [freqtrade/freqtrade#536]
## Step 2: Describe your environment

  * Python Version: 3.5.2
  * Branch: Develop
  * Last Commit ID: b799445b1a690a3773cb4b0ab73947c382285f95
 
## Step 3: Describe the problem:
*Explain the problem you have encountered*

### Steps to reproduce:

  1. Have buy order timeout, with completed order amount less than minimum order quantity
  2. Attempt to sell
  3. Receive ``MIN_TRADE_REQUIREMENT_NOT_MET`` exception and ``retrying in 30 seconds`` in console
  4. Bot is now blocked from any further buy orders

Item 4 is due to, in ``_process`` in ``main.py`` the sell function being in the same exception catching as the buy. Thus when the the sell raises the ``MIN_TRADE_REQUIREMENT_NOT_MET``, the ``process_maybe_execute_buy`` section is never entered.

Would recommend:
 - The buy timeout never timing out if the minimum order quantity is no reached
 - The ``MIN_TRADE_REQUIREMENT_NOT_MET`` for sell not blocking the ``process_maybe_execute_buy`` part of ``_process``

**Comment by igal700** [comment]
The issue with trading will happened not only when you want to sell not fully filled order but also in initial buy order if stake amount defined in setup is less than order's minimum stake amount.
I have raised this issue in following comment
https://github.com/gcarq/freqtrade/pull/489#issuecomment-370151723

**Comment by shusso** [comment]
feel free to re open if not fixed yet
