### ISSUE TITLE
How to add the webserver to a online address? Not a local one

### ISSUE THREAD

**Issue by Vildnex** [freqtrade/freqtrade#5366]
I did read the documentation regarding `webserver `and there it saying how to connect my freqtrade to a local server via an IP and a PORT. But I could not find how to add the webserver to an online address. In other words, I do have my own server which I am accessing via browser "www.my_link_to_server.com:PORT". For this server, I am using https://cockpit-project.org/ in order to access it via an interface. 

Is there any way in which I can change the freqtrade configuration with something like that?

```
    "api_server": {
        "enabled": false,
        "listen_ip_address": "www.my_link_to_server.com",
        "listen_port": PORT,
        "verbosity": "error",
        "jwt_secret_key": "somethingrandom",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "SuperSecurePassword"
    },
```

I've tried to use it like this but I am getting errors.

**Comment by xmatthias** [comment]
You can use any non-local IP address (or 0.0.0.0) as listen-address for this.

I do however strongly recommend against that without further measures.
it will expose your bot to the internet - and all your communication to the bot will be unencrypted.

While it's password protected, that is usually not a sufficient protection - and the traffic itself will not be encrypted (which means that the password is practically transmitted in clear text).

On a local network - this might be fine - but when running on a VPS, i'd recommend to either look into a SSH Tunnel or into setting up a VPN (or wireguard) to connect to the server via secure tunnel - and therefore avoiding to expose the bot towards the internet.

**Comment by Vildnex** [comment]
thx for clarifications :D

**Comment by KalanaPerera** [comment]
How to do SSH tunnel?

**Comment by xmatthias** [comment]
@KalanaPerera please use your favorite search engine to research how to do this.
Documenting (as well as supporting this) is way beyond the scope of this project.
thanks for your understanding.
