### ISSUE TITLE
Where does custom_sell fit into the bot execution logic?

### ISSUE THREAD

**Issue by BillGatesIII** [freqtrade/freqtrade#5370]
Simple question with probably a simpel answer :)

Where does custom_sell belongs in the bot execution logic?

https://www.freqtrade.io/en/latest/bot-basics/#bot-execution-logic

**Comment by xmatthias** [comment]
Nice catch.

I've now added this to the documentation as well. Let me know if there's still something unclear with the latest version of the docs.

**Comment by BillGatesIII** [comment]
I am still a bit confused about custom_sell. Is it executed every few seconds? Like custom_stoploss? Or is it executed every new candle? Like the populate_buy/sell_trend functions?

**Comment by xmatthias** [comment]
on every iteration (by default every few seconds).

**Comment by BillGatesIII** [comment]
But, custom_sell is not being executed when there is a sell signal from populate_sell_trend. Right? And populate_sell_trend is only executed after each candle? So as long as the last time there was a sell signal from populate_sell_trend, custom_sell is not being called? So after a sell signal with from for example 15 minutes candles, custom_sell is not being executed for 15 minutes?

Or am I completely off track here?

**Comment by xmatthias** [comment]
if populate_sell_trend issued a sell signal in the current candle - the trade will be sold - so further calls are no longer relevant.

**Comment by BillGatesIII** [comment]
And what if confirm_trade_exit returns false? Then the trade will not be sold.

One other question about this. If the code in custom_sell takes a long time to execute, longer than process_throttle_secs, what will happen?

**Comment by xmatthias** [comment]
as long as the sell-signal is on (usually for the duration of the candle) - you'll be stuck in a "sell / don't sell" loop.

Personally, i'm not a huge proponent of the `confirm_trade_exit()` method - as it usually means that your signal wasn't good.
if you need to selectively "reject" the signal, i'd always assign 0 to "sell" in the populate_sell method, and instead use custom_sell without trade_exit confirmation. That way you fully control the signal from one method, instead of dividing the logic into 3.

**Comment by BillGatesIII** [comment]
Understood. Thanks. And totally agree on that last one.

What about my last question about the duration? If I do a lot of stuff in custom_sell you normally would do in popultate_sell_method. Because I have moved everything from populate_sell to custom_sell so I always have the sell_reaon in the trade. But all the computations are now done in custom_sell. Could that cause troubles?

**Comment by xmatthias** [comment]
it'll stop the bot loop for the duration.
Assuming it's not taking multiple seconds, i don't see much problems.
obviously if it's taking a very long time, it'll potentially influence other trades as well.

"big" calculations should always be done in populate_indicators in a vectorized way ... at least if that's possible.

**Comment by BillGatesIII** [comment]
Clear.

If I want to calculate my sell signals based on indicators and for example the open rate of the trade compared with the last closing price, the only way is to put everything in custom_sell, right? Because in populate_sell_trend I don't have the active trade like I have in custom_sell?

**Comment by xmatthias** [comment]
you will have the active trade in `populate_sell_trend` as well during dry/live runs - but you won't have access to that during backtesting, which is usually a dealbreaker.

**Comment by BillGatesIII** [comment]
Ok. I'll think about this for a while because it would be nice to have inidcators, current trade information, sell signals and sell reasons in the same time function.

Back to the documentation :) Should a sentence like this

> This step is only executed once per Candle

also be added under this bullet? To make it more clear it is only executed for new candles?

>- Analyze strategy per pair.
