### ISSUE TITLE
Possible miscalculation of dynamic stake

### ISSUE THREAD

**Issue by perkmeister** [freqtrade/freqtrade#5372]
I think I've found a possible error in the way dynamic stakes are calculated. I was running a strategy wth 2 max open trades, and there were 2 open trades meaning no stake left. I then stopped the bot, and restarted with 3 max open trades. Freqtrade printed some warnings about not enough stake as expected, then one of the open trades closed. At this point there was stake available and 2 free slots, so when another trade opened it should have used half the available stake, but it actually used a third. Freqtrade seems to have lost count of the number of free slots when restarting with a different max trades setting and some trades from the previous configuration are still open.

native Ubuntu install 
develop-dad98d43

**Comment by xmatthias** [comment]
The above is a nice tale - but unfortunately, it's not a good issue report.

this will need quite some more information about your configuration, and what happened (including numbers/values) - and most likely logs.

**Comment by xmatthias** [comment]
@perkmeister any chance to get more details about the above? otherwise i'll not be able to analyze this issue further - as the above is not enough to even try to recreate this issue.

**Comment by xmatthias** [comment]
Going to close this now. Feel free to reopen / comment below should you still be able to provide the requested information.

**Comment by perkmeister** [comment]
Sorry Matthias, I didn't see the reply. I  should have kept this updated. There was always going to be a bit of asymmetry in stakes when changing max open trades with open trades, it didn't quite do what I expected initially but it stabilised very quickly into using the new symmetrical stake amounts so I think there isn't an issue. Apologies again for not informing you.
