### ISSUE TITLE
Multi user

### ISSUE THREAD

**Issue by atabakhooshangi** [freqtrade/freqtrade#5390]
hi,
i wanna launch the bot on a server in which multiple users can access it via a web ui for starting and stoping bot .
is it possible to implement such a thing to support multiple users ?
thanks

**Comment by xmatthias** [comment]
I would not know why you would want to do this.
if it's REALLY someone you trust, you can give them the password you set in the configuration - having seperate users will be the same (and even if we were to support different users - they would all share the same permissions - so there'd be little point).
