### ISSUE TITLE
Gate-io-Question

### ISSUE THREAD

**Issue by liaowenjie02** [freqtrade/freqtrade#5401]
Hi, I'm getting this error when I want to start the bot (command: freqtrade trade). The exchange I want to access is gateio, please help me. Thank you!
![image](https://user-images.githubusercontent.com/77956388/129015944-54d931be-2aac-462d-aeb2-36cdda17538c.png)

**Comment by liaowenjie02** [comment]
Is the exchange not supported on ccxt?
If it is my problem, can you tell me how to fix it?
Thanks!

**Comment by liaowenjie02** [comment]
Is the exchange not supported on ccxt?
If it is my problem, can you tell me how to fix it?
Thanks!

**Comment by xmatthias** [comment]
First of all - please fill out the issue template - it does include usually required information (like the ccxt version).
Also, for log output we'd prefer it as text (in tripple backticks`) - so it can be easily searched through, and eventually copy/pasted.

The error you're getting seems to be correct based on the current version of ccxt.
Running `freqtrade list-exchanges --all` yields `gateio              False    missing: fetchOHLCV`.

This means one of 3 things
- gate.io doesn't have an OHLCV endpoint (doesn't seem like that's the case based on api documentation)
- ccxt does not implement the OHLCV endpoint yet
- or there's a small mistake in ccxt - with gate.io not listing fetchOHLCV in their `.has` list.

From a "very quick" glance, it looks like the 3rd option - but i lack the time at the moment to investigate this further.

edit: (asking will help: https://github.com/ccxt/ccxt/issues/9794)

**Comment by xmatthias** [comment]
After the ccxt issue was closed, gate.io should work now.

please run `pip install -U ccxt` (with activated virtual environment) and then retry the tests you did.
I've just tried, and gate.io now shows up again as "potentially working" exchange.

I've also version-bumpe this requirement in development now, so docker images should be fine in a few minutes.

Obviously you might encounter other issues with gate.io (it's an exchange that's not been tested yet as far as i know).
In these cases, best open an issue so we can look at it.

**Comment by liaowenjie02** [comment]
![image](https://user-images.githubusercontent.com/77956388/129167586-42fa2739-38c7-463d-9148-eb331811fff3.png)

Thank you very much for your help!
But I have another problem in the next, it says I need to configure the policy, but I think if I can not have to configure my own policy, I want to use your configured one directly.

**Comment by xmatthias** [comment]
While freqtrade does provide a builtin sample strategy - it should be treated as what it is - a sample strategy that will usually not work very well and will cause losses depending on current market conditions.
It's meant to inspire / serve as a template - not to be used directly.

I'd recommend to go through the [documentation](https://www.freqtrade.io/en/stable/) to understand the basics and learn the necessary commands.
