### ISSUE TITLE
How to get the value of the last candle and for previous candles?

### ISSUE THREAD

**Issue by eveli909** [freqtrade/freqtrade#5402]
## Describe your environment

  * Operating system: Ubuntu 20.04.2
  * Python Version: 3.8.10
  * CCXT version: 1.51.77
  * Freqtrade Version: 2021.6
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

I would like to make sure that the value of an indicator at last candle for 3 previous candles was less than 30. If I understand correctly, it should make sure that at the time of the previous candle, plus_di would have been less than 30 for 3 candles before that.
I am trying the following options but none returns correct results:

```
1. (dataframe['plus_di'].shift(1).rolling(3).max() < 30)
2. (dataframe['plus_di'].rolling(3).max().shift(1) < 30)
```

Second, is it possible to get the value of current candle? If I use the following to make sure that the current volume is 2 times greater than the volume of previous 10 candles, it compares the value of the previous candle, not the current candle:
`(dataframe['volume'] > dataframe['volume'].rolling(10)mean().shift(1) * 2)`

**Comment by xmatthias** [comment]
Freqtrade will only provide you with closed candles.
Unclosed candles usually result in repainting issues (which is a very common issues in tradingview strategies, and causes results to not reproduce).

So assuming a 1h timeframe, at 11:15, you will get the candle from 10:00-11:00.
The non-closed candle (11:00-12:00) will be available shortly after 12:00.

In your first question i'm not sure - either of the 2 should give you what you want (they should return the identical values).
When having such problems - best store the reuslt of this (`dataframe['plus_di'].shift(1).rolling(3).max()`) to a column and visualize this (either with `freqtrade plot-dataframe` or with freqUI).

That's usually the fastest way to understand what goes wrong (maybe it's not this part, but how you combine it with other indicators that causes the results to be different then what you expect...

**Comment by eveli909** [comment]
Thanks, Matthias!

Does it mean that assuming 1h timeframe, at 11:15 the following code:`(dataframe['plus_di'].shift(1).rolling(3).max() < 30)` would return the max result of plus_di of 3 candles before the candle at 9:00-10:00? Or would it be the candle from 9:00-10:00 and 2 candles before that? 
You wrote: "best store the reuslt of this (dataframe['plus_di'].shift(1).rolling(3).max()) to a column". What do you mean by storing the result to a column? How can I do that?

**Comment by xmatthias** [comment]
i'd assume it's the 9:00-10:00 candle + 2 prior.

As mentioned above - just plot it and analyze the result. You can assign columns as usual `dataframe['whatever'] = dataframe['plus_di'].shift(1).rolling(3).max()` ...
