### ISSUE TITLE
HyperOpt Strategy Buy/Sell Space Not Found

### ISSUE THREAD

**Issue by a178235** [freqtrade/freqtrade#5406]
## Describe your environment

  * Operating system: Ubuntu 21.04
  * Python Version: Docker Version
  * CCXT version: 1.54.62
  * Freqtrade Version: freqtrade docker-0b6aedbc

## Describe the problem:

freqtrade - ERROR - The 'buy' space is included into the hyperoptimization but indicator_space() method is not found in your custom Hyperopt class. You should either implement this method or remove the 'buy' space from hyperoptimization.

### Steps to reproduce:

Using: https://github.com/i1ya/freqtrade-strategies/blob/main/BigZ07/BigZ07.py

sudo docker-compose run --rm freqtrade hyperopt --strategy BigZ07 --timeframe 5m --timerange 20210501-20210801 --max-open-trades -1 --stake-amount 15.00 --fee 0.00075 --dry-run-wallet 1000.00 --epochs 1000 --spaces buy roi --random-state 1 --job-workers -1 --hyperopt-loss SharpeHyperOptLoss
  
### Observed Results:

freqtrade - ERROR - The 'buy' space is included into the hyperoptimization but indicator_space() method is not found in your custom Hyperopt class. You should either implement this method or remove the 'buy' space from hyperoptimization.

It contains the buy_ stuff such as below.

buy_condition_0_enable = CategoricalParameter([True, False], default=True, space='buy', optimize=False, load=True)

I'm probably missing something simple, and I believe it worked last month, but I'm just not sure.

**Comment by xmatthias** [comment]
At first glance, it looks like all parameters have `optimize=False`. 
This excludes them from the search space - which will result in empty spaces at the end.

**Comment by a178235** [comment]
Thanks for solving this.
