### ISSUE TITLE
ROI values in external file not refreshed after a config reload in Telegram

### ISSUE THREAD

**Issue by Spindirac** [freqtrade/freqtrade#5411]
## Describe your environment

  * Operating system: MACOS
  * Python Version: 3.8.7
  * CCXT version: 1.50.48
  * Freqtrade Version: 2021.5
  
## Your question

Hello, 
the minimal ROI values in my strategy are stored in an external file which is loaded in the strategy via a module import
If the ROI values are changed in the file and the /reload_config in Telegram is triggered, it seems that the import is not evaluated as the ROI values are still the old ones. 
Any workaround?
Many thanks
![Capture d’écran 2021-08-13 à 11 13 52](https://user-images.githubusercontent.com/50480822/129334454-f0ba9b20-db19-4680-a9c7-cbf90d97218b.png)

**Comment by Spindirac** [comment]
Solved... .By using the Python reload() function

**Comment by Spindirac** [comment]
Added the following code in the class

from importlib import reload  
reload(my_module)

**Comment by xmatthias** [comment]
this is not a supported use of the strategy - and in my experience, importlib's reload does not always reload values.
As such - this is not a supported way to run the bot  and we will not support in case of unexpected problems or issues.

As such - best put the files diretly in the strategy file as documented and used everywhere in Freqtrade to avoid problems.
