### ISSUE TITLE
The robot has been running without a deal

### ISSUE THREAD

**Issue by linliang123** [freqtrade/freqtrade#5412]
We have used the strategy Strategy001 provided by this platform, and the robot has been running normally, but there has been no transaction of currency

**Comment by xmatthias** [comment]
Please use the Documentation for this type of questions.

More specifically - we have a dedicated [FAQ point](https://www.freqtrade.io/en/stable/faq/#i-have-waited-5-minutes-why-hasnt-the-bot-made-any-trades-yet) for exactly this question.

Also - please fill out the issue template. Future issues with the issue-template removed will be closed without further comment.
