### ISSUE TITLE
can not backtest strategies //// freqtrade freeze

### ISSUE THREAD

**Issue by LucianPopaLVP** [freqtrade/freqtrade#5414]
## Describe your environment

  * Operating system: __Linux Ubuntu latest__
  * Python Version: ___3.8.11__ (`python -V`)
  * CCXT version: ___latest__ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ___latest_ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

The bot is freezing when I try 2 backtest. Installed everything from scratch, linux and everything else and I don't have anything else in that computer. ryzen 5 3600, 16gb ram . Nothing is shown on the console after the freeze. No errors or anything else.

Downloaded just data I need for my strategy, 5m and 1h for the last 60 days, but I can not run backtests....everything else works properly....dry run, live run etc, but when I try to back test it won't work and freeze. :( Tried to backtest on data for the last 5 days....won't work either...
I really need to backtest my strategies before running live.

Anyone has a suggestion or fix for this?
Thank you much!

  ```

**Comment by xmatthias** [comment]
Please post both the command you use to backtest, as well as the log up to the point of the freeze (thisnwill tell me where its freezing).

**Comment by LucianPopaLVP** [comment]
> Please post both the command you use to backtest, as well as the log up to the point of the freeze (thisnwill tell me where its freezing).

comand line : (.env) lvp@lvp-VirtualBox:~/freqtrade$ freqtrade backtesting -c config.json  --strategy AwesomeStrategy  --timeframe 5m

For the record, i do have set up the strategy in the file, it's not the default one...but that should work to for backtesting.

log:

![Untitled](https://user-images.githubusercontent.com/88782755/129472068-2059f7a1-a737-490f-9382-97a23f0f2860.jpg)

**Comment by xmatthias** [comment]
Logs are text - so please don't paste them as screenshots. That's pretty combersome to work with.

The message says "killed" - which suggests that it's probably a memory topic (your virtual machine is out of memory - and therefore "victimized" one of the offending processes).

**Comment by LucianPopaLVP** [comment]
> combersome

Sorry! I will post text next time.
Well , my virtual box has 10 gb allocated out of the 16 total I have...and freqtrade requires just 2 gb to run and I only run one terminal...how can this be the problem? the only thing I am using besides the freqtrade is Mozilla :(

Thanks for your reply !

**Comment by xmatthias** [comment]
I'd not run freqtrade from within pycharm, but in a "pure" terminal to make sure it's not pycharm that's killing your bot for "whatever" reason.

Also pycharm will require some memory (not sure how much - i think that'll depend a bit on the version and what is active).

**Comment by Foxel05** [comment]
I have the same problem
For me, it has often been the case that Freqtrade has spent up to 8gb ram when backtesting. If you use docker, you should see if you need to allocate more ram to docker, especially if you are backtesting "large" time spans, or complex strategies such as NostalgiaForInfinity.

I found these links that explain how to allocate more ram to docker:
Windows: https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig
Linux: https://phoenixnap.com/kb/docker-memory-and-cpu-limit

Since I allocated more ram to docker, everything works fine.
