### ISSUE TITLE
Profit incorrectly reported

### ISSUE THREAD

**Issue by nateemma** [freqtrade/freqtrade#5415]
## Describe your environment

  * Operating system: MacOS
  * Python Version: 3.9.6
  * CCXT version: ccxt==1.54.74
  * Freqtrade Version: develop-123971d2
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*
Profit is not correctly calculated, and this then messes up profit tracking.

### Steps to reproduce:

  1. Run bot for extended period of time
  2. About every 30 trades or so, profit is incorrectly reported 
  
### Observed Results:

  * What happened?

Sell issued successfully, with a profit. However, log shows a large loss (see below). I checked the exchange, and there was no real loss. I have seen this 4 times now (in the last 4 weeks). Functionality of bot is OK, but tracking of performance is really messed up.

 If you look at the freqtrade log, the first 'sell' RPC message (2021-08-14 09:15:28,547) is correct, but the final 'sell_fill' entry (2021-08-14 09:15:32,549) is wrong (look at profit_amount, it's now -$239 instead of +$7)

This was on Binance US, using BNB to pay fees (and yes there is plenty of BNB in the account)

I do not see any info on fees on the freqtrade/ccxt side, so not sure what's going on there

  * 
  * What did you expect to happen?
 Correct reporting/calculation of profit

Note: I found a similar issue: https://github.com/freqtrade/freqtrade/issues/3984 but that was supposedly fixed

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

From freqtrade log:

```
2021-08-14 09:15:27,023 - freqtrade.freqtradebot - INFO - Executing Sell for COMP/USD. Reason: roi
2021-08-14 09:15:28,032 - freqtrade.wallets - INFO - Wallets synced.
2021-08-14 09:15:28,547 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell, 'trade_id': 110, 'exchange': 'Binanceus', 'pair': 'COMP/USD', 'gain': 'profit', 'limit': 469.65, 'order_type': 'limit', 'amount': 2.14841, 'open_rate': 465.4598051582333, 'close_rate': None, 'current_rate': 469.65, 'profit_amount': 7.49562509, 'profit_ratio': 0.00749002, 'sell_reason': 'roi', 'open_date': datetime.datetime(2021, 8, 14, 10, 0, 24, 898029), 'close_date': datetime.datetime(2021, 8, 14, 16, 15, 28, 547875), 'stake_currency': 'USD', 'fiat_currency': 'USD'}
2021-08-14 09:15:30,043 - freqtrade.wallets - INFO - Wallets synced.
2021-08-14 09:15:30,049 - freqtrade.freqtradebot - INFO - Pair ALGO/USD is still locked until 2021-08-14 16:20:00 due to Auto lock.
2021-08-14 09:15:30,545 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=110, pair=COMP/USD, amount=2.14841000, open_rate=465.45980516, open_since=2021-08-14 10:00:24)
2021-08-14 09:15:32,545 - freqtrade.persistence.models - INFO - Updating trade (id=110) ...
2021-08-14 09:15:32,545 - freqtrade.persistence.models - INFO - LIMIT_SELL has been fulfilled for Trade(id=110, pair=COMP/USD, amount=2.14841000, open_rate=465.45980516, open_since=2021-08-14 10:00:24).
2021-08-14 09:15:32,545 - freqtrade.persistence.models - INFO - Marking Trade(id=110, pair=COMP/USD, amount=2.14841000, open_rate=465.45980516, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.
2021-08-14 09:15:32,549 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell_fill, 'trade_id': 110, 'exchange': 'Binanceus', 'pair': 'COMP/USD', 'gain': 'loss', 'limit': 469.64992715543116, 'order_type': '', 'amount': 2.14841, 'open_rate': 465.4598051582333, 'close_rate': 469.64992715543116, 'current_rate': None, 'profit_amount': -239.19791866, 'profit_ratio': -0.23901903, 'sell_reason': 'roi', 'open_date': datetime.datetime(2021, 8, 14, 10, 0, 24, 898029), 'close_date': datetime.datetime(2021, 8, 14, 16, 15, 32, 545823), 'stake_currency': 'USD', 'fiat_currency': 'USD'}
```

From sqlite database:

348|110|sell|COMP/USD|0|63898398|closed|COMP/USD|limit|sell|469.65|469.649927155431|2.14841|2.14841|0.0|1009.0006|2021-08-14 16:15:28.855000|2021-08-14 16:15:30.546748|2021-08-14 16:15:30.546751

From Binance US:

2021-08-14 09:15:28	COMP/USD	Limit Sell 469.65	469.65	2.14841	2	1009.01	–	Filled	

Trading total: 1009.01 USD

Date	                     Trading price  Executed	Transaction Fee:	Total
2021-08-14 09:15:28	469.65	    1.30000	0.00112011   BNB	610.54500000 USD
2021-08-14 09:15:28	469.65	    0.84840	0.00073449 BNB	398.45106000 USD
2021-08-14 09:15:29	469.65	    0.00001	0.00000844 BNB	0.00469650 USD

From CCXT:

{'info': {'symbol': 'COMPUSD', 'orderId': '63898398', 'orderListId': '-1', 'clientOrderId': 'x-R4BD3S825e760d5d64627bb012477', 'price': '469.6500', 'origQty': '2.14841000', 'executedQty': '2.14841000', 'cummulativeQuoteQty': '1009.0006', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'LIMIT', 'side': 'SELL', 'stopPrice': '0.0000', 'icebergQty': '0.00000000', 'time': '1628957728855', 'updateTime': '1628957729308', 'isWorking': True, 'origQuoteOrderQty': '0.0000'}, 'id': '63898398', 'clientOrderId': 'x-R4BD3S825e760d5d64627bb012477', 'timestamp': 1628957728855, 'datetime': '2021-08-14T16:15:28.855Z', 'lastTradeTimestamp': None, 'symbol': 'COMP/USD', 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': False, 'side': 'sell', 'price': 469.65, 'stopPrice': None, 'amount': 2.14841, 'cost': 1009.0006, 'average': 469.64992715543116, 'filled': 2.14841, 'remaining': 0.0, 'status': 'closed', 'fee': None, 'trades': [], 'fees': []}

**Comment by xmatthias** [comment]
> From sqlite database:

This seems to be from the orders table - not from the trade table (filtered on the trade id).
The orders-table is only there for informative (and some specific functions not relevant here) - but won't contain info necessary here.

Also - please check the logs (potentially below the log-output posted above) for messages like `Fee for Trade` for this trade.

Also, the ccxt output doesn't contain any fees ... which can happen from time to time, but freqtrade does have some logic to counter this.

**Comment by nateemma** [comment]
There were no messages with _Fee for Trade_ at all (I looked before I posted).

However, if I restart the bot I get messages like this at startup (not related to the trade(s) at issue):


>2021-08-20 18:31:22,027 - freqtrade.freqtradebot - INFO - Applying fee on amount for Trade(id=147, pair=STORJ/USD, amount=735.34000000, open_rate=1.36000000, open_since=2021-08-16 19:30:20) failed: myTrade-Dict empty found


&nbsp;&nbsp;
&nbsp;&nbsp;
The related issue I found asked for the _orders_ entry, but here is the entry from _trades_:

```
id   exchange   pair      is_open  fee_open       fee_open_cost  fee_open_currency  fee_close          fee_close_cost  fee_close_currency  open_rate         open_rate_requested  open_trade_value  close_rate        close_rate_requested  close_profit  close_profit_abs  stake_amount  amount   amount_requested  open_date                   close_date                  open_order_id  stop_loss  stop_loss_pct  initial_stop_loss  initial_stop_loss_pct  stoploss_order_id  stoploss_last_update        max_rate  min_rate  sell_reason  sell_order_status  strategy   buy_tag  timeframe
---  ---------  --------  -------  -------------  -------------  -----------------  -----------------  --------------  ------------------  ----------------  -------------------  ----------------  ----------------  --------------------  ------------  ----------------  ------------  -------  ----------------  --------------------------  --------------------------  -------------  ---------  -------------  -----------------  ---------------------  -----------------  --------------------------  --------  --------  -----------  -----------------  ---------  -------  ---------
110  binanceus  COMP/USD  0        0.00074994125  0.00184407     BNB                0.245242746666667  0.00186304      BNB                 465.459805158233  465.46               1000.74844012509  469.649927155431  469.65                -0.23901903   -239.19791866     1000.0        2.14841  2.14841           2021-08-14 10:00:24.898029  2021-08-14 16:15:32.545823                 310.02516  -0.343         305.807091988959   -0.343                 63873410           2021-08-14 15:22:31.411216  471.88    456.11    roi          closed             ComboHold           5 
```

&nbsp;&nbsp;
&nbsp;&nbsp;
Since I messed up the formatting in my original post (sorry), here is the equivalent entry from the Binance US web site again:

```
2021-08-14 09:15:28 COMP/USD Limit Sell 469.65 469.65 2.14841 2 1009.01 – Filled

Trading total: 1009.01 USD
```

Date |Price|Executed|Transaction Fee:|Total
|----------------------|---------|---------|-------------------|-----------------------|
2021-08-14 09:15:28   | 469.65   | 1.30000     | 0.00112011 BNB     |  610.54500000 USD
2021-08-14 09:15:28   | 469.65   | 0.84840    | 0.00073449 BNB    | 398.45106000 USD
2021-08-14 09:15:29   | 469.65   | 0.00001     | 0.00000844 BNB  |  0.00469650 USD



&nbsp;&nbsp;
&nbsp;&nbsp;
Actually, I found all of the erroneous entries:

```
id   exchange   pair      is_open  fee_open       fee_open_cost  fee_open_currency  fee_close          fee_close_cost  fee_close_currency  open_rate          open_rate_requested  open_trade_value  close_rate         close_rate_requested  close_profit  close_profit_abs  stake_amount  amount    amount_requested  open_date                   close_date                  open_order_id  stop_loss         stop_loss_pct  initial_stop_loss  initial_stop_loss_pct  stoploss_order_id  stoploss_last_update        max_rate  min_rate  sell_reason  sell_order_status  strategy   buy_tag  timeframe
---  ---------  --------  -------  -------------  -------------  -----------------  -----------------  --------------  ------------------  -----------------  -------------------  ----------------  -----------------  --------------------  ------------  ----------------  ------------  --------  ----------------  --------------------------  --------------------------  -------------  ----------------  -------------  -----------------  ---------------------  -----------------  --------------------------  --------  --------  -----------  -----------------  ---------  -------  ---------
19   binanceus  LTC/USD   0        0.00075        0.0002491      BNB                0.369990785        0.00026475      BNB                 117.419919214692   117.42               100.074499625     118.28977032549    118.29                -0.3657993    -36.6071823       100.0         0.85164   0.85164           2021-07-18 14:55:20.910805  2021-07-18 17:11:08.856092                 79.14622          -0.333         78.3190861161993   -0.333                                    2021-07-18 16:54:11.487188  118.66    116.7     roi          closed             ComboHold           5        
76   binanceus  COMP/USD  0        0.00074955     0.00106444     BNB                0.09727689         0.00109473      BNB                 482.736437551903   482.82               500.28690918951   483.609861140617   483.61                -0.09632093   -48.18810023      499.9122      1.03558   1.03558           2021-08-07 12:55:11.865932  2021-08-07 18:13:15.558135                 314.261420846289  -0.349         314.261420846289   -0.349                 58450640           2021-08-07 12:55:23.172837  490.58    470.5     roi          closed             ComboHold           5        
106  binanceus  ALGO/USD  0        0.0007484      0.00184212     BNB                0.0183551075       0.00183163      BNB                 0.942999966994988  0.943                1000.74799970064  0.950999816114933  0.951                 -0.01076776   -10.77581358      999.9996      1060.445  1060.445          2021-08-14 00:50:20.282119  2021-08-14 07:05:29.456202                 0.629406          -0.343         0.619550978315707  -0.343                                    2021-08-14 05:54:36.721758  0.958     0.932     roi          closed             ComboHold           5        
110  binanceus  COMP/USD  0        0.00074994125  0.00184407     BNB                0.245242746666667  0.00186304      BNB                 465.459805158233   465.46               1000.74844012509  469.649927155431   469.65                -0.23901903   -239.19791866     1000.0        2.14841   2.14841           2021-08-14 10:00:24.898029  2021-08-14 16:15:32.545823                 310.02516         -0.343         305.807091988959   -0.343                 63873410           2021-08-14 15:22:31.411216  471.88    456.11    roi          closed             ComboHold           5 
```

The _fee_close_ column looks suspicious (but I don't know what it means)

**Comment by xmatthias** [comment]
the fee_close column is for sure wrong - it's showing 24% fees on that 147 trade.

i do hope that you still have the (full) logs for at least one of the trades so we can try/hope to piece this together.
Otherwise it'll become a guessing game ... which is obviously a problem.

You can/could also use `exchange.log_responses=True` in the configuration. This will (very selectively) enhance the log by logging relevant exchange calls / responses.

That might help us piece together what's happening / why the fee is updated wrongly.

**Comment by nateemma** [comment]
sorry, I don't have logging back that far. Are the logs saved anywhere (I couldn't find any)?

I'll add the extra logging and add to this post if I see this again

**Comment by xmatthias** [comment]
the logs are saved IF you use `--logfile <filename>` - which is the default with docker.

**Comment by nateemma** [comment]
sorry, I'm not using docker - I couldn't get it to work on MacOS so I just update from git and run directly. Anyway, now saving to log :-)

My guess is that this is something to do with the lack of fee info from binanceus combined with the fact that I'm using BNB to pay fees (cheaper that way). If you could give me some clues as to where to look, I'll scan the code and see if I can spot anything

**Comment by xmatthias** [comment]
most people use BNB Fees - so that should be fine.

so far, i've only seen such cases with mixed fees (where part is paid in BNB, and another part in USDT (for example).
We do have a check in place to simply reject all fees > 2% (now in both relevant places - see commit linked above).
but obviously that'll not fix the problem / root cause - which i suspect is some odd return-value from the exchange (probably something you can't get again if you run the same query again).

**Comment by xmatthias** [comment]
Without further logs, i don't see any actionable points in this for now.

Should it reoccur (with exchange-logging on as explained above) please let me know below / reopen.
