### ISSUE TITLE
Backtest error and Partial trading about.

### ISSUE THREAD

**Issue by Umutrc** [freqtrade/freqtrade#5416]
Hello, thank you very much for this beautiful bot and  my question:
1-) I would like to add the following to the strategy.
before = when the conditions I specified are met, buy it at a rate of 3/1
then = if it falls below 17% of the price I bought, I want to make a conditional partial purchase such as 3/2 buy again.
2-) In my strategy, if the candle close is below the bolliinger band, buy and sell if it is above the bolliinger band, but when I test it backwards, it trades at the opening of the candle, not at the close of the candle?
I tried parameters such as "low" "high" "close" as an extra, but it still buys and sells from "open".
what is the problem?
this is photo my strategie and buy sell result;
![strateji](https://user-images.githubusercontent.com/24203648/129480687-c4814bc5-f7c8-4e2c-840a-967b53b4a5dd.png)
![satma](https://user-images.githubusercontent.com/24203648/129480691-4c95b72e-74f8-4f5a-a44b-b05b21c9995e.png)
![satın alma1](https://user-images.githubusercontent.com/24203648/129480692-f06b3433-a9d6-45e2-8056-6695541b6f8a.png)

**Comment by xmatthias** [comment]
Please familiarize yourself with the [backtest assumptions](https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting).

point 2 is explained pretty well there, and honestly, i do refuse to repeat things that are clearly stated in the documentation.

**Comment by Umutrc** [comment]
First of all, I would like to thank you for your feedback.
but I've read the topic you mentioned before, now I looked again, but I'm not sure exactly where the problem originates from.
I would be grateful if you explain the problem and solution a little more.

**Comment by xmatthias** [comment]
> Buys happen at open-price
> Sell-signal sells happen at open-price of the consecutive candle

it's the first and 3rd point in the list - pretty clearly formulated if you ask me.

**Comment by Umutrc** [comment]
yes it's clear enough but there is no solution for this?
and this strategy;
(dataframe['close'] <= dataframe['bb_lowerband'])
When I apply it, will it buy from the candle close in real time, or will it buy the candle at the lowest price in real time when I make the "close" part "low"?

**Comment by xmatthias** [comment]
> yes it's clear enough but there is no solution for this?

it's an assumption (backtesting won't have all data available) - but especially buying will almost always happen right after the new candle happens - (which will be closed to open).
Same for regular sell-signals, assuming you're not using "real-time" data - which you can't backtest anyway.

The signal will flip when a new candle arrives (when close drops below lowerband).
As such - the order will happen close to the next candle's open.

Pricing (what price the order is posted) in live is a different topic, and can be configured in [multiple different ways](https://www.freqtrade.io/en/stable/configuration/#prices-used-for-orders).

**Comment by Umutrc** [comment]
Thank you, my 2nd question has been solved thanks to you.
but my first question still remains

**Comment by xmatthias** [comment]
To be honest, i don't understand your first question.

**Comment by Umutrc** [comment]
Thank you for your sincerity :D
I mean;
To give an example, when it goes below the Bollinger band, it should buy with half ($500) of the money I have allocated (say, $1000), then go back under the Bollinger band and when the RSI value is below 20, it should buy with 4/1 of the money ($250) again. I want

**Comment by xmatthias** [comment]
Freqtrade does currently not support position staking (#1519), so once one trade is open, this size will remain until that trade is closed.

To define "half stake" - you can use [the `custom_stake_amount()` callback](https://www.freqtrade.io/en/stable/strategy-advanced/#stake-size-management).
