### ISSUE TITLE
Data analysis return an empty data frame

### ISSUE THREAD

**Issue by Matoutou27** [freqtrade/freqtrade#5418]
## Describe your environment

  * Operating system: Ubuntu 20.04.2 LTS
  * Python Version: 3.8.10
  * CCXT version: ccxt==1.55.4
  * Freqtrade Version: 2021.7 (Anaconda)
  

## Describe the problem:
Jupyter notebook returning an empty data frame when loading data

  1. download data: freqtrade  download-data --days 365 --pairs BTC/USD --exchange kraken
  2. tried backtesting and it is working
  3. Run the two first cell from the strategy_analysis_example file
  
### Observed Results:
returning an empty data frame. 

### Relevant code exceptions or logs

  ```
# Load data using values set above
from freqtrade.data.history import load_pair_history

candles = load_pair_history(datadir=data_location,
                            timeframe=config["timeframe"],
                            pair=pair,
                            data_format = "jsongz",
                          )

# Confirm success
print("Loaded " + str(len(candles)) + f" rows of data for {pair} from {data_location}")
candles.head()

OUTPUT:
Loaded 0 rows of data for BTC/USD from /home/freq/freqtrade/user_data/data/kraken/BTC_USD-trades.json.gz

  | date | open | high | low | close | volume
  ```

**Comment by xmatthias** [comment]
Your most likely cause of problem is the dataformat line (`data_format = "jsongz",`).

jsongz is not a default format, so unless you've changed this in your configuration, i think this is wrong and should be either json or hdf5 (if set explicitly in your configuration).

**Comment by Matoutou27** [comment]
Thanks a lot, i confused myself with the historical trades data.
