### ISSUE TITLE
FTX live connection help

### ISSUE THREAD

**Issue by aumcara** [freqtrade/freqtrade#5431]
## Describe your environment
(if applicable)

  * Operating system: Ubuntu 18
  * Python Version: 3.9
  * CCXT version: 1.55.6
  * Freqtrade version: 2021.7

## Describe the enhancement

Hello,

I am facing several issues with freqtrade …  that I did discover 2 days ago. What an amazing piece of Programming. Congrats ! 

My first test strategies come out with an average and incredible (for le) return between 4 and 8% a day!

All this in dry run modere :-(.

The very blocking part (for me as a beginner here) is the lack (as far as I know) of info to go live … I have probably and more certainly missed something and the frustrating part is that I see info about the Binance exchange :-(

But, do you have any info for me to use with FTX that I honestly warmly recommend !

After testing without bot the following exchanges: Bitstamp, Kraken and of course Binance … I was chocked after discovering  FTX ( https://ftx.com/#a=26543465 ) … whaow ! What a huge difference …. Cheapest cost in the crypto sphere … very professionnal interface … realy to discover. In brief very very pro interface a couple of days to get use to it and your are on the road with FTX.

I am for the moment strugeling to go live :-/ ..

Is there any full and complete example for FTX that I could use with my API keys .. etc of course ? 

For use with Spot trading.

And also, am I right with the fact that now future trading is possible with freqtrade ?
Any config example and help would be very appreciated to use with FTX.

Many thanks.P

**Comment by xmatthias** [comment]
Futures / margin trading is currently not possible with freqtrade - but work is being made in moving towards that

I'm honestly not entirely sure what the issue with FTX is - creating API keys there is pretty much straightforward ("key" and "secret" - identical to binance).

If you want to use subaccounts, please follow [the documentation](https://www.freqtrade.io/en/stable/exchanges/#using-subaccounts) - as that requires some more setup.

**Comment by aumcara** [comment]
Thanks for your reply Matthias, I will get back ... While tryng to fix/review this issue I got another error that I just reported.

**Comment by aumcara** [comment]
I did checked and I was fine with key and API ... just struggeling with Subaccount ... I belive I am close... :-)
