### ISSUE TITLE
Bot.py

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#5435]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*

**Comment by Anytka808** [comment]
A

**Comment by xmatthias** [comment]
Without any detail / text - there's no reason to have an issue open.

**Comment by Giahuynh1402** [comment]
> 
> 
> ## Describe your environment
> (if applicable)
> 
>   * Operating system: ____
>   * Python Version: _____ (`python -V`)
>   * CCXT version: _____ (`pip freeze | grep ccxt`)
>   * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
> 
> 
> ## Describe the enhancement
> 
> *Explain the enhancement you would like*
> 
>
