### ISSUE TITLE
stoploss not working

### ISSUE THREAD

**Issue by Umutrc** [freqtrade/freqtrade#5436]
hello, I want stoploss to occur at the values I specified, but when I look at localhost:8080, the stoploss value is -25.000% when I buy and sell. Is there a solution?
my settings are as follows:
strategy.py
``` python
    stoploss = -0.1
    trailing_stop=True
    trailing_stop_positive= 0.03
    trailing_stop_positive_offset= 0.05
    


    # Optimal timeframe for the strategy
    timeframe = '15m'

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = False
    # Optional order type mapping.
    order_types = {
    'buy': 'limit',
    'sell': 'limit',
    'emergencysell': 'market',
    'stoploss': 'market',
    'stoploss_on_exchange': False,
    'stoploss_on_exchange_interval': 10,
    'stoploss_on_exchange_limit_ratio': 0.99
    
    }





    # ... populate_* methods

    use_custom_stoploss = True


    def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:
                        

        # evaluate highest to lowest, so that highest possible stop is used
        if current_profit > 0.14:
            return stoploss_from_open(0.12, current_profit)
        elif current_profit > 0.13:
            return stoploss_from_open(0.10, current_profit)
        elif current_profit > 0.10:
            return stoploss_from_open(0.08, current_profit)
        elif current_profit > 0.06:
            return stoploss_from_open(0.03, current_profit)

        # return maximum stoploss value, keeping current stoploss price unchanged
        return 1
```

config.json ;

```
	"timeframe": "15m",
    "minimal_roi": {
        "0": 1
    },
    "unfilledtimeout": {
        "buy": 15,
        "sell": 15,
        "unit": "minutes"
    },
    "bid_strategy": {
        "price_side": "bid",
        "use_order_book": true,
        "ask_last_balance": 0.0,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": true,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": false,
        "sell_profit_only": true,
        "sell_profit_offset": 0.08,
        "ignore_roi_if_buy_signal": false
    },
    "order_types": {
        "buy": "limit",
        "sell": "limit",
        "emergencysell": "market",
        "forcesell": "market",
        "forcebuy": "market",
        "stoploss": "limit",
        "stoploss_on_exchange": false,
        "stoploss_on_exchange_interval": 30
    },
    "order_time_in_force": {
        "buy": "gtc",
        "sell": "gtc"
    },
    "protections": [
        {
            "method": "CooldownPeriod",
            "stop_duration_candles": 3
        }
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.6,
        "minimum_expectancy": 0.2,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    }
```
    
![Adsız](https://user-images.githubusercontent.com/24203648/129724309-a7508171-3999-4508-8648-15bd3069988f.png)

**Comment by xmatthias** [comment]
The most likely reason (almost always the case with such issues) is that you have the same strategy-name in your strategy-folder twice (in different files).

you can use `freqtrade list-strategies` to identify these.
If that's not the case, we'll need the log for these trades (when it opened, and when the order closed ... and a few minutes after that) to look at this further.

**Comment by Umutrc** [comment]
yes i had a copy with the same strategy name but the settings on it were the same but i deleted it now i will try again thanks.

**Comment by xmatthias** [comment]
What's the exchange you're using?

**Comment by Umutrc** [comment]
binance

**Comment by Umutrc** [comment]
```
use_custom_stoploss = True


    def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:
                        

        # evaluate highest to lowest, so that highest possible stop is used
        if current_profit > 0.14:
            return stoploss_from_open(0.12, current_profit)
        elif current_profit > 0.13:
            return stoploss_from_open(0.10, current_profit)
        elif current_profit > 0.10:
            return stoploss_from_open(0.08, current_profit)
        elif current_profit > 0.06:
            return stoploss_from_open(0.03, current_profit)

        # return maximum stoploss value, keeping current stoploss price unchanged
        return 1
```
and 

```
    stoploss = -0.1

    trailing_stop=True

    trailing_stop_positive= 0.03

    trailing_stop_positive_offset= 0.05
```
Can it be used with?

**Comment by Arlu6** [comment]
Enviado desde mi Samsung Mobile de Telcel
-------- Mensaje original --------De: Umutrc ***@***.***> Fecha: 18/08/21  4:51 a.m.  (GMT-06:00) A: freqtrade/freqtrade ***@***.***> CC: Subscribed ***@***.***> Asunto: Re: [freqtrade/freqtrade] stoploss not working (#5436) 
` use_custom_stoploss = True


def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                    current_rate: float, current_profit: float, **kwargs) -> float:
                    

    # evaluate highest to lowest, so that highest possible stop is used
    if current_profit > 0.14:
        return stoploss_from_open(0.12, current_profit)
    elif current_profit > 0.13:
        return stoploss_from_open(0.10, current_profit)
    elif current_profit > 0.10:
        return stoploss_from_open(0.08, current_profit)
    elif current_profit > 0.06:
        return stoploss_from_open(0.03, current_profit)

    # return maximum stoploss value, keeping current stoploss price unchanged
    return 1`  

and
    stoploss = -0.1 trailing_stop=True trailing_stop_positive= 0.03 trailing_stop_positive_offset= 0.05
Can it be used with?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/freqtrade/freqtrade/issues/5436#issuecomment-900978697",
"url": "https://github.com/freqtrade/freqtrade/issues/5436#issuecomment-900978697",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by xmatthias** [comment]
It can be used for the moment - but i strongly advise against mixing trailing_stop with custom_stoploss.

Both use the same fields, and basically work the same way - so the documentation highlights to not combine the 2 - and we'll probably be creating a blocking error when both custom_stoploss and trailing_stop is active at the same time.

**Comment by Umutrc** [comment]
I get an error when I delete thesection,

 `stoploss =-0.1`

Would it be better for me to do this? 
```
    stoploss = -0.1

    trailing_stop=False
    use_custom_stoploss = True


    def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:
                        

        # evaluate highest to lowest, so that highest possible stop is used
        if current_profit > 0.14:
            return stoploss_from_open(0.12, current_profit)
        elif current_profit > 0.13:
            return stoploss_from_open(0.10, current_profit)
        elif current_profit > 0.10:
            return stoploss_from_open(0.08, current_profit)
        elif current_profit > 0.06:
            return stoploss_from_open(0.03, current_profit)

        # return maximum stoploss value, keeping current stoploss price unchanged
        return 1

```

**Comment by xmatthias** [comment]
probably yes - although the behaviour will not be 100% identical.

**Comment by Umutrc** [comment]
Thank you, topic can be closed.

**Comment by ghost** [comment]
Echa un vistazo a "Samsung Internet": https://chrome.google.com/webstore/detail/samsung-internet/epejdmjgfibjaffbmojllapapjejipkh?hl=es-419&gl=MX&utm_source=gmailEnviado desde mi Samsung Mobile de Telcel
