### ISSUE TITLE
Backtest different after freqtrade update (exchange FTX)

### ISSUE THREAD

**Issue by Fimap9to1** [freqtrade/freqtrade#5437]
## Describe your environment

  * Operating system: ____
  * Python Version: Python 3.8.5
  * CCXT version: ccxt==1.55.6
  * Freqtrade Version: freqtrade develop-81715d0b9
  
## Your question

Hi, is there a way to reinstall previous version of freqtrade? 
Is there a way to know what was the latest version I was using?

I'd like to try it again, because after today's update to the latest version of freqtrade, the backtest results have changed considerably.

It know does more trades and the profit has decreased. The exchange I use is FTX.
I always do a backtest before and after every update, in order to confirm that nothing changes. This wasn't the case today. Last time I updated freqtrade was one week ago max.

**Comment by xmatthias** [comment]
In theory, you can go through the log and do `git checkout` - but that'll obviously only work if you're not using docker.
With docker, you should have the image still available (`docker images`) - so you can simply tag the relevant image again and run that.
In general - we don't support downgrades of develop images. If you prefer a stable version (with changelog) - best use `stable` - or the release versions.


The exchange will not matter - but one of the last versions will.
There's been some in regards to fixing an lookahead bias (#5391 and #5394).
if one of these reduces your backtest profits - then your strategy had a lookahead bias and will most likely not reproduce in dry/live runs.

**Comment by Fimap9to1** [comment]
So if the backtest after the update gives a decreased tot profit and nothing has changed in the strategy, it for sure is because it had a lookahead bias?

**Comment by Fimap9to1** [comment]
The buy changes? I only use buy & sell signals at close (no custom). When I went live a month ago it did the same trades as in backtesting, even if it was with the old version.

**Comment by Fimap9to1** [comment]
Now even if stoploss is fixed at -0.1065, in the sell reason stats, it shows stoploss average profit = -14.15%, maybe is the stoploss the error?

**Comment by xmatthias** [comment]
there's been a lot of changes - but none related to backtesting within the last week, but a lot longer ago (mainly related to how trailing-stop is handled - improving accuracy).

Feel free to scroll / investigate pull requests - best using [this filter](https://github.com/freqtrade/freqtrade/pulls?q=is%3Apr+is%3Aclosed+-label%3ADependencies+) which removes dependency-updates.

**Comment by Fimap9to1** [comment]
I checked and it does the same trades. The only difference is the stoploss which now even if in the strategy is set to -10.65% in the backtest is used a -14.15% don't have any idea why, it occurred after the update.

**Comment by xmatthias** [comment]
Best check (and provide) the log (especially the log up to the backtest results).

These often contain valuable information.
just doublechecked - results (including stoploss) are identical for me between stable and develop. therefore i guess it will be something on your side that changed.

**Comment by xmatthias** [comment]
Monitor this message (https://github.com/ccxt/ccxt/commit/d915d8ccb9e569a58d2a6564da91c297fbb5900d#r55038516) for details - it's a bug in ccxt that increased fees to 2%/7% ...

**Comment by Fimap9to1** [comment]
> 
> 
> Monitor this message ([ccxt/ccxt@d915d8c#r55038516](https://github.com/ccxt/ccxt/commit/d915d8ccb9e569a58d2a6564da91c297fbb5900d#r55038516)) for details - it's a bug in ccxt that increased fees to 2%/7% ...

This definetively make sense! I'll let you know if that's the reason.

**Comment by Fimap9to1** [comment]
Yes, it was that the reason! Thank you so much for your help Matthias!
