### ISSUE TITLE
the chart shows sales but no sell signal and does not sell

### ISSUE THREAD

**Issue by Umutrc** [freqtrade/freqtrade#5440]
hello, when I look at the graphic over localhost:8080, the buying signal is receiving from the place and the notification is coming from the telegram, there is no problem.
but where there is a sell signal on the chart, there is no sales signal, why does it not sell?

**Comment by aumcara** [comment]
hi, I noticed this also but maybe it's because of the ROI trigger and not a SELL trigger (that's the first thing that came to my mind but I might be wrong.)

**Comment by Umutrc** [comment]
Thank you for your comment, although there are more than one sell signal, no notification is received and the transaction does not take place.
![dasda](https://user-images.githubusercontent.com/24203648/129763492-c68e3fed-69ff-411e-bc11-b12f8cdc6dea.png)

**Comment by xmatthias** [comment]
Best check the logs for the identified time.

Also make sure that you have `use_sell_signal` set to true (best check the bot startup logs to ensure that what you think is used should be used).

If `use_sell_signal` is false, then the sell-signal will simply be ignored.
The same would happen in combination with a combination of `sell_profit_only` / `sell_profit_offset`- but unless you have that set pretty high, i don't see that happening here.

Also, if `confirm_trade_exit()` rejects the sell the trade would not be sold (this will depend on the strategy - and will be reflected in the logs).

**Comment by Umutrc** [comment]
my setting;
this is my config; and use_sell_signal " true"
```
`    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": true,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": true,
        "sell_profit_offset": 0.08,
        "ignore_roi_if_buy_signal": false
`
`        "notification_settings": {
            "status": "on",
            "warning": "on",
            "startup": "on",
            "buy": "on",
            "buy_fill": "on",
            "sell": "on",
            "sell_fill": "on",
            "buy_cancel": "on",
            "sell_cancel": "on"
        }`
```
this is my strategy;  not found "sell_profit_only"
and "confirm_trade_exit"  parts of it are not included in the comment line processing.
;
```
`    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = False
    # Optional order type mapping.
    order_types = {
    'buy': 'limit',
    'sell': 'limit',
    'emergencysell': 'market',
    'stoploss': 'market',
    'stoploss_on_exchange': False,
    'stoploss_on_exchange_interval': 10,
    'stoploss_on_exchange_limit_ratio': 0.99
    
    }`
```
```
` # def confirm_trade_exit(self, pair: str, trade: Trade, order_type: str, amount: float,
                           # rate: float, time_in_force: str, sell_reason: str, **kwargs) -> bool:
        # """
        # Called right before placing a regular sell order.
        # Timing for this function is critical, so avoid doing heavy computations or
        # network requests in this method.

        # For full documentation please go to https://www.freqtrade.io/en/latest/strategy-advanced/

        # When not implemented by a strategy, returns True (always confirming).

        # :param pair: Pair that's about to be sold.
        # :param order_type: Order type (as configured in order_types). usually limit or market.
        # :param amount: Amount in quote currency.
        # :param rate: Rate that's going to be used when using limit orders
        # :param time_in_force: Time in force. Defaults to GTC (Good-til-cancelled).
        # :param sell_reason: Sell reason.
            # Can be any of ['roi', 'stop_loss', 'stoploss_on_exchange', 'trailing_stop_loss',
                           # 'sell_signal', 'force_sell', 'emergency_sell']
        # :param **kwargs: Ensure to keep this here so updates to this won't break your strategy.
        # :return bool: When True is returned, then the sell-order is placed on the exchange.
            # False aborts the process
        # """
        # if sell_reason == 'force_sell':
            # return True
        
        # if trade.calc_profit_ratio(rate) < 0.05:
            # Reject force-sells with negative profit
            # This is just a sample, please adjust to your needs
            # (this does not necessarily make sense, assuming you know when you're force-selling)
            # return False
        # return True`


```
    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

       
        

        dataframe.loc[
                (
                    
                    
                   #((dataframe["macd"] < dataframe["macd_1"])) & 
                   #(self.current_profit > 0.01)&
                   # (dataframe['rmi'] > 80) &
                   (dataframe["ema13"] <= dataframe["close"]) 
                   #(dataframe["bb_upperband_4"]>=dataframe["close"]) 
                   #(dataframe["bb_upperband_3"]<=100000) 
                   
                    
                  
                ),
                'sell'] = 1


        return dataframe
```

**Comment by xmatthias** [comment]
> `"sell_profit_offset": 0.08,`

This disables the sell-signal until a profit of 8% is reached.
Based on your screenshot, you're at 0.8% profit - so it's correct in not selling.
