### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by maximebel** [freqtrade/freqtrade#5441]
Hello

On Fedora 34 with python 3.9, following manual installation, freqtrade doesn't start properly.

The reason is that uvloop is missing from requirements.txt

Just running pip install uvloop in .env makes freqtrade work properly.

Regards

**Comment by xmatthias** [comment]
uvloop is not a requirement / dependency of freqtrade.

There was an (overnight) bug due to the upgrade of uvicorn which was fixed in #5434.

As you didn't fill out the issue template, i'll assume you ran one of the vulnerable versions (which where the latest versions overnight).
