### ISSUE TITLE
Hyperopt with Informative pairs

### ISSUE THREAD

**Issue by NemanjaSRB91** [freqtrade/freqtrade#5442]
Guys, is it possible to use hyperopt if I am using informative pairs too? Informative pairs are used just for buy trigger, and I don't need to hyperopt anything related with informative pairs, I just need to hyperopt sell triggers and stop loss. So is it possible to optimize it with hyperopt? Thanks

**Comment by xmatthias** [comment]
I don't see why this should not be possible - otherwise it would be pretty pointless.

You will need historic data for the pairs/timeframe and corresponding timerange - otherwise loading informative pairs in backtesting/hyperopt will fail.

**Comment by NemanjaSRB91** [comment]
I do have historic data, but the timerange of informative pairs is 4h, and I am trading 1h timerange. Backtesting works perfectly, but when I try to optimize sell trigger with hyperopt file, it gives totally wrong results. Doesn't show any error, just it gives totally different results. 
I would try to optimize sell trigger with Strategy file, but I don't have a good example, so I can't figure out how it should be done. I checked documentation, it seems a bit confusing for my coding skills. If you have an example of optimization with Strategy file, using Bolinger bands or any kind of Categorical parameters, it could help me a lot.
And yes, can informative pair of different timerange be optimized too? 
Thanks

**Comment by xmatthias** [comment]
sell-side is not really different to buy side - so there's little point in having both sides documented identically.

for performance reasons, you should be loading informative pairs in `populate_indicators` - not in one of the `populate_<>_trend` methods.

**Comment by NemanjaSRB91** [comment]
I get that the sell side isn't at all different from the buy side, but there isn't a clear example of any of two sides in documentation how to use strategy for hyperopt. It was used an example for EMA, and no examples for categorical parameters. That's why I asked if there is any better example. 
I load informative pairs in populate_indicators, but I need to use them as a buy trigger. Is there a solution not to put it in populate_buy_trend and to use it as a buy trigger?
Thanks

**Comment by xmatthias** [comment]
we have a [full informative pair](https://www.freqtrade.io/en/stable/strategy-customization/#complete-data-provider-sample) example available. By merging it to the dataframe, the columns can be used as if they're originating from the original dataframe.

**Comment by NemanjaSRB91** [comment]
`

    def informative_pairs(self):

        # get access to all pairs available in whitelist.
        pairs = self.dp.current_whitelist()
        # Assign tf to each pair so they can be downloaded and cached for strategy.
        informative_pairs = [(pair, '4h') for pair in pairs]
        # Optionally Add additional "static" pairs
        return informative_pairs


    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Adds several different TA indicators to the given DataFrame

        Performance Note: For the best performance be frugal on the number of indicators
        you are using. Let uncomment only the indicator you are using in your strategies
        or your hyperopt configuration, otherwise you will waste your memory and CPU usage.
        :param dataframe: Dataframe with data from the exchange
        :param metadata: Additional information, like the currently traded pair
        :return: a Dataframe with all mandatory indicators for the strategies
        """
        if not self.dp:
            # Don't do anything if DataProvider is not available.
            return dataframe

        inf_tf = '4h'
        # Get the informative pair
        informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf)
        

        # Get the MACD for informative
        macdinformative = ta.MACD(informative)
        informative['macd'] = macdinformative['macd']
        informative['macdsignal'] = macdinformative['macdsignal']
        informative['macdhist'] = macdinformative['macdhist']

        # Use the helper function merge_informative_pair to safely merge the pair
        # Automatically renames the columns and merges a shorter timeframe dataframe and a longer timeframe informative pair
        # use ffill to have the 1d value available in every row throughout the day.
        # Without this, comparisons between columns of the original and the informative pair would only work once per day.
        # Full documentation of this method, see below
        dataframe = merge_informative_pair(dataframe, informative, self.timeframe, inf_tf, ffill=True)

        # MACD
        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        dataframe['macdhist'] = macd['macdhist']

        # Bollinger Bands
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband'] = bollinger['lower']
        dataframe['bb_middleband'] = bollinger['mid']
        dataframe['bb_upperband'] = bollinger['upper']
        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                (dataframe['macd_4h'] > 0) & # 'macd_1h' Dobija se tako sto freqtrade sam doda 4h na naziv macd
                (dataframe['macdsignal_4h'] > 0) & # 'macdsignal_1h' Dobija se tako sto freqtrade sam doda 4h na naziv macdsignal
                (dataframe['close'] <= dataframe['bb_lowerband'])


            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the sell signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with sell column
        """
        dataframe.loc[
            (
                (dataframe['close'] > dataframe['bb_upperband']) 
               

            ),
            'sell'] = 1
        return dataframe
`

This is the strategy. I have already done everything related to informative pairs, but I don't know how to optimize sell trigger. I want this to be taken in consideration as sell triggers:

 ```
   @staticmethod
    def sell_indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching sell strategy parameters.
        """
        return [
            Categorical([
                         'sell-bb_middle1-close',
                         'sell-bb_upper2-close',
                         'sell-bb_middle1-low',
                         'sell-bb_upper2-low'
                       ], name='sell-trigger')
        ]

    @staticmethod
    def sell_strategy_generator(params: Dict[str, Any]) -> Callable:
        """
        Define the sell strategy parameters to be used by hyperopt
        """
        def populate_sell_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Sell strategy Hyperopt will build and use
            """
            # print(params)
            conditions = []
            # GUARDS AND TRENDS

            # TRIGGERS
            if 'sell-trigger' in params:
                if params['sell-trigger'] == 'sell-bb_middle1-close':
                    conditions.append(dataframe['close'] > dataframe['bb_middleband1'])
            if 'sell-trigger' in params:
                if params['sell-trigger'] == 'sell-bb_upper2-close':
                    conditions.append(dataframe['close'] > dataframe['bb_upperband2'])
            if 'sell-trigger' in params:
                if params['sell-trigger'] == 'sell-bb_middle1-low':
                    conditions.append(dataframe['low'] > dataframe['bb_middleband1'])
            if 'sell-trigger' in params:
                if params['sell-trigger'] == 'sell-bb_upper2-low':
                    conditions.append(dataframe['low'] > dataframe['bb_upperband2'])




            # Check that volume is not 0
            conditions.append(dataframe['volume'] > 0)

            if conditions:
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'sell'] = 1

            return dataframe

        return populate_sell_trend


```

I have been using additional hyperopt file, and it doesn't give applicable results. I don't know how to run hyperopt just with strategy, and I needed an example for that. If you can help, I would be grateful :D

**Comment by xmatthias** [comment]
Please simply read the documentation - best from top to bottom.

You're better of to not use a seperate hyperopt file. Consider this interface as the "old" interface.
It'll require you to have conditions aligned throughout.

It's way simpler to simply use [strategy parameters - as documented in the hyperopt documentation](https://www.freqtrade.io/en/stable/hyperopt/).

That page also has a pretty clear example on how to use [categorical parameters](https://www.freqtrade.io/en/stable/hyperopt/#hyperoptable-parameters).
