### ISSUE TITLE
"SubAccount" and "enableRateLimit" in config.json

### ISSUE THREAD

**Issue by aumcara** [freqtrade/freqtrade#5448]
Operating system: Ubuntu 18
    Python Version: 3.9
    CCXT version: 1.55.6
    Freqtrade version: 2021.7
  
## My Question

Soon ready to go LIVE with Freqtrade.

I need to configure it to work in a Subaccount at FTX.

Almost set, I would like confirmation if the following statements are correct:

    "exchange": {
        "name": "ftx",
        "key": "MyKey",
        "secret": "MySecret",
        "ccxt_config": {"headers": {
            "FTX-SUBACCOUNT": "MySubAccountNAME",
            "enableRateLimit": true},
        "ccxt_async_config": {"headers": {
            "FTX-SUBACCOUNT": "MySubAccountNAME",
            "enableRateLimit": true,
        "rateLimit": 200
    },

I searched all over the manual and nowhere can I see an example with two occurrences (in my case Headers with SUBACCOUNT and "enableRateLimit") ... I would like to avoid errors/mistakes when launching Freqtrade into production. : - /

Am I correct with the above ?
(NB: Sorry, I am not a programmer)

Thank you for your understanding and possible help.

**Comment by xmatthias** [comment]
the [documentation](https://www.freqtrade.io/en/stable/exchanges/#using-subaccounts) has you covered.

You will however need to be careful, as the above contains json syntax errors (the "headers" section only contains the FTX subaccount key, not the rest).
Best use an editor with syntax highlighting (vscode, or similar) - which will highlight syntax errors like these (and also help formatting files).
Also, you'll not need it in the async config again - options from are automatically merged to the async config as well.
