### ISSUE TITLE
FTX, Money available for Trading in a specific Subaccount.

### ISSUE THREAD

**Issue by aumcara** [freqtrade/freqtrade#5449]
Operating system: Ubuntu 18
Python Version: 3.9
CCXT version: 1.55.6
Freqtrade version: 2021.7
  
## Your question

The manual explains the dry_run wallet for drymode trades...  It's very clear.

In production, I absolutely have to use a SUBACCOUNT with FTX for FreqTRade.

In production, I do not see anything concerning the amount available to carry out trades in a Subaccount: - /

IS = will FreqTrade automatically detect the amount of SUBACCOUNT?

Are there other precautions to be taken so that the amounts debited are only debited with the money available in the SUBACCOUNT for trading ?

It would be nice to add these details for exchanges allowing Subaccount like FTX.

Thank you in advance for the assistance.

**Comment by xmatthias** [comment]
If you configure an API key to only work with a subaccount, freqtrade can only see the money in the subaccount.

You'll however have to specify that subaccount [as specified in the documentation](https://www.freqtrade.io/en/latest/exchanges/#using-subaccounts).

I'd also kindly ask you to not open 2-3 issues for the same topic (that's now the 2nd or 3rd issue from yourself related to subaccounts). That's pretty much pointless and will result in pretty much the same answer again and again.
Also - for questions like this, best join the [discord server](https://discord.gg/p7nuUNVfP7) to get support / help from the community.
People there love to help assuming the documentation has been consulted first.
