### ISSUE TITLE
How does the "startup_candle_count" work?

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#5453]
## Describe your environment

* Operating system: Debian 10
* Python Version: Python 3.7.3
* CCXT version: ccxt==1.54.74
* Freqtrade Version: freqtrade develop-4f10a885
  
## Your question

I am using a strategy that is using these parameters

```
    # Optimal timeframe for the strategy.
    timeframe = '5m'
    inf_1h = '1h'

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = True

    # These values can be overridden in the "ask_strategy" section in the config.
    use_sell_signal = True
    sell_profit_only = False
    ignore_roi_if_buy_signal = True

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 400
```
My question is:

How exactly does the "startup_candle_count" work?

- Do I have to wait for 400 candles for the bot to make the first buy?
- Does the bot look up historical data on the exchange, going back 400 candles?
- Can I use the "freqtrade download-data" command so the bot has the data today and it can start buying?

I read the [Strategy Startup Period](https://www.freqtrade.io/en/stable/strategy-customization/#strategy-startup-period) but that mentions backtesting, not live trading.

**Comment by xmatthias** [comment]
`startup_candle_count` has no relevance to live trading (except that the bot checks that `startup_candle_count` is below the amount the exchange provides) - and the bot will not wait for this (also no download-data is necessary).

As you're always getting the exchange's default candle amount (~1000 for binance) - you'll be fine as long as your value is below 999.

**Comment by aristosv** [comment]
thanks for the clarification
