### ISSUE TITLE
setup.sh update can't install dependences and breaks installation

### ISSUE THREAD

**Issue by perkmeister** [freqtrade/freqtrade#5457]
@xmatthias I cannot update using setup.sh, my install is now broken and  can't run freqtrade. Here's the full error log, there appears to be missing first characters in the distribution names? Win10, WSL with Ubuntu. 

[setup_error.txt](https://github.com/freqtrade/freqtrade/files/7018240/setup_error.txt)

Edit: I restored the .env directory from last night's disk image backup and got things working again, and have successfully updated this time. I've no idea how this happened so don't panic, it was probably all my fault. Somehow... ;)

**Comment by xmatthias** [comment]
As it's windows 10 with WSL - i think you'll want to be carefull how you clone your install.

Proplems like this MAY happen if you do the clone from windows - and then use it from WSL / linux.
Windows (by default) does the checkouts with different line-endings (and potentially with different character sets) ... so my recommendation - if you're using it in WSL - do everything in that folder in WSL (and move it out of `/mnt/c/...` - as that is the slowest disk in the whole WSL linux system.

**Comment by ghost** [comment]
> - [ ] []()

**Comment by perkmeister** [comment]
Thanks Matthias. I'm trying not to use any WSL specific stuff and do everything in a bash shell to keep it identical to my miniPC running my live bot with Linux Lite, so far it has been flawless. This is probably finger trouble and I did something like you said. I think this can be closed now, all is working, at least I know how to recover it if it should happen again. This is not the first time Macrium Reflect has come to my aid ;)
