### ISSUE TITLE
Telegram translate commands?

### ISSUE THREAD

**Issue by Umutrc** [freqtrade/freqtrade#5458]
hello, thank you again for making such a beautiful boat with every angle thought out.
I want to edit the telegram bot, I want to translate the commands there into my own language.
For this "freqtrade-2021.7/freqtrade/rpc/telegram.py" I edit this file and restart the bot but nothing changes

**Comment by xmatthias** [comment]
Translating the commands is not supported (and i honestly doubt the usefulness of that - as all commands are available, or can be made available) on the "click of a button").

On top of that - by editing the files, you'll create problems for yourself when updating to the next version, which potentially has changes to this file - and will therefore probably cause conflicts.

Therefore, please understand that we'll not be supporting in this endavor - as you'll create a unmaintainable situation for yourself (which will result in more questions here).
