### ISSUE TITLE
negative shift == Wrong Hyperopt Result

### ISSUE THREAD

**Issue by mablue** [freqtrade/freqtrade#5460]
I checked two of my strats in Dry mode Dimond And MultiMa (Still Not Merged version but commited),
these two have very good result in hype and good signals but just in backtest and hyperopt.
Them cuz of using negative shift DF.shift(-7) cant generate a realtime buy and sell signal :) but in -7 candle befour have generated best signals :)))
there is a problam it make the hyperoption and backtest results fully fake!
I think the better way is not removing negative shift and blocking it inside strategies. Its Removing the face of problem.
The bot will work and calculate the result. For example if it want to calculate something in 2021/1/1 we will not let them to see datas of 2021/1/2 than check the quality of signals . I had wrote very well strategies and Im was happy for that.but now I undrestand I wrote just a shit! :)) and will change the negative shift to positive to let bot to generate signals in real time and buy something :)

Please show me the place that dataframe passing to optimize that I cut the DataFrame from there and let optimizer to optimize things without watching feature. cuz its make mistake. in live trading we have not this option to watch the feature and generate indicators and generate signals with them!

**Comment by xmatthias** [comment]
It's a pandas function - we can't really prevent users from using it.

It is however [pretty well documented](https://www.freqtrade.io/en/stable/strategy-customization/#common-mistakes-when-developing-strategies) - so the mistake is yours by not reading the documentation.

The mistake will be to merge a strategy with that to the strategy repository. 
As such - please look through all of your strategies, and remove the ones that are using shift(-1) - or one of the other "gotchas", thanks.

**Comment by mablue** [comment]
> It's a pandas function - we can't really prevent users from using it.
> 
> It is however [pretty well documented](https://www.freqtrade.io/en/stable/strategy-customization/#common-mistakes-when-developing-strategies) - so the mistake is yours by not reading the documentation.
> 
> The mistake will be to merge a strategy with that to the strategy repository.
> As such - please look through all of your strategies, and remove the ones that are using shift(-1) - or one of the other "gotchas", thanks.

yes I have mistake I know I will fix them. but the model or environment that we use to hyperopt have some problems.just df will cut like that somewhere(i think its inside hyperopt.py line 401):
```
dataframe.iloc[0: random buy place]
```
or I can do that inside my strategy if I know the buy signal where triggered in which row?is there any variable to findout?

**Comment by xmatthias** [comment]
Hyperopt is perfectly fine - but we can't prevent users from using data they should not (data from the future).

The documentation pretty clearly states that backtesting / hyperopt will get the full dataframe - so it's up to the strategy to prevent looking into the future.
While it'd be technically possible to prevent future data from passing in, it would make one single backtest take hours - which means hyperopt would be pointless as it'd take weeks to run 100 epochs.

for that reason - it's the responsibility of the user / strategy author to make sure they're not looking into the future - which is also clearly documented (it's not the frameworks fault if users fail to read the documentation).


---

Freqtrade also supports dry-run - which will properly test the strategy without the possibility to cheat, so it's not putting user's money at risk.

To be honest, my expectation for every contribution to the strategy repostiory is and was that it's a proven strategy that has been ran at least a week in dry-run. 

It's now apparent that you're not doing this, and rely solely on backtesting - so i'll need to think about ripping all of your strategies out - as you're relying on users to do the testing for you - which is not helping other users at all, but making them do the work you should've been doing.

**Comment by mablue** [comment]
Its true in this two strat cuz I like the results and want to show you my work but you know I used this strategies befour for real live but old versions not new updates. In old versions and all of other strategies I didnt used negative shift . and this day I used it and find the results very amazing and want to commit the new updates. you know dimond strat also maked from another one and them all two multima and dimond have one source at first that I used for real trading them!

**Comment by drakes00** [comment]
I was also expecting that the strategy was properly tested and I would have spent my afternoon trying to fix it if I knew :-(
When something looks too good to be true, it often is.

**Comment by Nathan-Kr** [comment]
i dont think u need to be that rude for a mistake guys, i did clone the strategy and didnt spot the mistake myself. No money was risked after all.

**Comment by mablue** [comment]
> i dont think u need to be that rude for a mistake guys, i did clone the strategy and didnt spot the mistake myself. No money was risked after all.

after some moments every thing will fix sorry for every thing its a big mistake I had...
multima is up to merge

**Comment by mablue** [comment]
> I was also expecting that the strategy was properly tested and I would have spent my afternoon trying to fix it if I knew :-(
> When something looks too good to be true, it often is.

Its still show very good results ! now its on hyperopt and backtesting after some moments will up

**Comment by Nathan-Kr** [comment]
> Its still show very good results ! now its on hyperopt and backtesting after some moments will up

i'm looking forward to test it ! Could u put it on your fork of freqtrade-strategies please ?

**Comment by mablue** [comment]
> > Its still show very good results ! now its on hyperopt and backtesting after some moments will up
> 
> i'm looking forward to test it ! Could u put it on your fork of freqtrade-strategies please ?

yes its up on Diamond branch in the fork... not very good but not much bad :))

**Comment by ghost** [comment]
~~**_[]()_**~~
