### ISSUE TITLE
Is there a benefit in using both "StaticPairList" and "VolumePairList"?

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#5464]
## Describe your environment

- Operating system: Debian 10
- Python Version: Python 3.7.3
- CCXT version: ccxt==1.54.74
- Freqtrade Version: freqtrade develop-4f10a885
  
## Your question

Is there a benefit in using both "StaticPairList" and "VolumePairList", when "pair_whitelist" is like this?

```
        "pair_whitelist": [
        ".*/BTC"
        ],
```

```
    "pairlists": [
        {"method": "StaticPairList"},
        {
            "method": "VolumePairList",
            "number_assets": 80,
            "sort_key": "quoteVolume",
            "refresh_period": 1800
        },
```

I mean, won't "VolumePairList" go though all BTC pairs anyway?

**Comment by xmatthias** [comment]
yes it would.

I don't really see a point in this particular configuration combination ... however when done slightly differently, you can keep in control of which pairs to trade (pair_whitelist) - and use volumepairlist to order / sort the pairs based on volume.

**Comment by 14790897** [comment]
There is no benefit because VolumePairList goes through all BTC pairs.
