### ISSUE TITLE
log file keeps showing messages of blacklisted pairs

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#5465]
## Describe your environment

- Operating system: Debian 10
- Python Version: Python 3.7.3
- CCXT version: ccxt==1.54.74
- Freqtrade Version: freqtrade develop-4f10a885
  
## Your question

Is it normal that the log file keeps showing messages of blacklisted pairs?

<img width="849" alt="2021-08-21 19_02_27-TAIL Aristos Freqtrade BTC - Royal TS" src="https://user-images.githubusercontent.com/528302/130327849-577d992e-806d-4271-9512-2639cea8e8a7.png">

**Comment by xmatthias** [comment]
With the version you're using, yes.
it's been changed to only log from time to time in more recent versions.

**Comment by aristosv** [comment]
I just upgraded to these versions

- Python 3.7.3
- ccxt==1.55.20
- freqtrade develop-56759cea

But I still get the same behaviour.

<img width="828" alt="2021-08-22 18_03_52-TAIL Aristos Freqtrade BTC - Royal TS" src="https://user-images.githubusercontent.com/528302/130360099-55f1b8e3-c1d6-40f1-a7d6-53945d5e55d8.png">

**Comment by xmatthias** [comment]
You're right, that's the message i didn't fix yet. Should be ok now.
