### ISSUE TITLE
Automated training, validation and test

### ISSUE THREAD

**Issue by daoudChami** [freqtrade/freqtrade#5474]
Hello,

First of all, thank you for your work.

My question is the following : is it possible to code in python a script to automate the hyperopt on a "train" period, a backtest on a "validation" period and a backtest on a "test" period ? My idea would be to test various strategies, losses and train/validation/test split sizes to understand which methodology works the best. 

Thank you !

**Comment by xmatthias** [comment]
in IT / software development, almost everything is possible.

For sure, this would also be a possibility - but it's not something that currently exists (or if it does, noone tried to contribute it back here).
Freqtrade also does not contain such a script or functionality, and we currently have no plans to develop such a thing.

**Comment by daoudChami** [comment]
Thank you very much for your quick answer.
How about the python package freqtrade ? Would it be possible to emulate the cli actions through it ? If it's the case, where could we fine documentation on this package and its usages ?

Thank you

**Comment by xmatthias** [comment]
while it's possible to import freqtrade and freqtrade commands (in theory) - running freqtrade commands that way is not supported, not documented, and cannot be relied upon to not change between version upgrades.

Obviously it's all open source so you can just look up what is called and how - but we'll not provide documentation for it - and also no change notes should any of this change between versions, as we don't consider this a user facing interface.
