### ISSUE TITLE
Help figuring out why bot does not open any trades in comparison with identical bot

### ISSUE THREAD

**Issue by aristosv** [freqtrade/freqtrade#5479]
## Describe your environment
**BOT1**
  * Operating system: Debian 10
  * Python Version: Python 3.7.3
  * CCXT version: ccxt==1.50.70
  * Freqtrade Version: freqtrade develop-f920c268
  
**BOT2**
  * Operating system: Debian 10
  * Python Version: Python 3.7.3
  * CCXT version: ccxt==1.55.28
  * Freqtrade Version: freqtrade develop-96915630
  
## Your question

These 2 bots use the exact same configuration and strategy. I literally copy/paste the strategy and configuration files from BOT1 to BOT2. I only changed API keys and Telegram information in the config file. Everything else is identical. They are also running on the same machine, connected on 2 separate Binance accounts. No other bots are running on that machine.

This is the log file of BOT1:
[BOT1.log](https://github.com/freqtrade/freqtrade/files/7044241/BOT1.log)

This is the log file of BOT2:
[BOT2.log](https://github.com/freqtrade/freqtrade/files/7044247/BOT2.log)

This is the strategy they are both using:
[strategy.txt](https://github.com/freqtrade/freqtrade/files/7044266/strategy.txt)

And this is the configuration they are both using:
[config.txt](https://github.com/freqtrade/freqtrade/files/7044276/config.txt)

This is the command used to run them, so I know they are using the specific strategy:
```
 freqtrade trade --strategy freqtrade_BTC_aristos
 freqtrade trade --strategy freqtrade_BTC_stella
```
Also, only one strategy file exists in user_data/strategies.

The problem is that BOT2 does not open any trades, while BOT1 is working as expected, opening trades quite frequently. I need help finding out what is the difference between these 2 bots, that is preventing BOT2 from opening any trades.

**Comment by xmatthias** [comment]
As the strategies are named differently i have my doubts that they are identical (you can claim they are, but maybe they are not on the server).

The most likely cause is that they are different, or the configuration is different.
Bot2 log does not contain any "Buy signal found" - which simply means that the strategy didn't ask the bot to buy, or that all trade-slots are filled (which does not appear to be the case, based on the remaining log).
As such  my conclusion is - your strategies are not identical - and the strategy used in bot2 does not generate buy signals.

Please understand that i'll not go through a 13Mb log file trying to find out why your strategies differ and you think they are identical.

**Comment by aristosv** [comment]
of course not, I just wanted to provide as much information as possible, in an effort to pinpoint the issue. These are screenshots of the strategies.

<img width="656" alt="1" src="https://user-images.githubusercontent.com/528302/130836327-42d3fb8a-8f82-46b6-936a-ec2099a3ec59.png">

<img width="663" alt="2" src="https://user-images.githubusercontent.com/528302/130836332-73d1b0b2-78c8-4d03-a9ec-dde9828a349f.png">

I tried many things to get the newer versions of the bot to work as the old one does, but nothing worked. I really do believe at some point you'll discover something in the newer versions that prevents the bot to open new trades under certain circumstances. I just don't have the knowledge to figure out what that is, and I was hoping to open a discussion where I would provide the necessary information to pinpoint the issue.

**Comment by xmatthias** [comment]
on strategies this simple -  i'd not know what it is.

By providing it as screenshot instead of text however you're also preventing any attempt to help you by trying to run your configuration.

**Comment by aristosv** [comment]
I just wanted to show that they are identical. Here it is.

```
import freqtrade.vendor.qtpylib.indicators as qtpylib
from pandas import DataFrame, DatetimeIndex, merge
from freqtrade.strategy.interface import IStrategy
from typing import Dict, List
from functools import reduce
import talib.abstract as ta
class freqtrade_BTC_aristos(IStrategy):

    stoploss = -0.4
    timeframe = '1m'
    trailing_stop = True
    trailing_stop_positive = 0.01
    trailing_stop_positive_offset = 0.02
    trailing_only_offset_is_reached = True

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=4)
        dataframe['bb_lowerband'] = bollinger['lower']
        dataframe['bb_middleband'] = bollinger['mid']
        dataframe['bb_upperband'] = bollinger['upper']
        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['rsi'] < 30) &
                (dataframe['close'] <= 0.98 * dataframe['bb_lowerband'])
            )
            ,
            'buy'] = 1
        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (),
            'sell'] = 1
        return dataframe
```

**Comment by xmatthias** [comment]
you can try to run the (2nd) bot with simple debug (`-v`). 
while the log will become more verbose - it'll also contain more messages (like colliding buy/sell messages).

**Comment by xmatthias** [comment]
Can you check your pandas version?

i suspect you run into #4382 - but in reverse - so your strategy is expecting the wrong bollinger band  (calculated as 0 depending on the variance...).
That's however been a bug - so the strategy will not work on newer pandas versions - and also on the older ones it was pure luck ... :laughing:

**Comment by aristosv** [comment]
BOT1: v1.2.4
BOT2: v1.3.2

**Comment by xmatthias** [comment]
yep, that explains it - BB was calculated differently (wrongly on BTC pairs) with the 1.2.x series of pandas.
