### ISSUE TITLE
About now datetimes accuracy.

### ISSUE THREAD

**Issue by neimad1985** [freqtrade/freqtrade#5486]
**Freqtrade version 2021.7**

Hi,

First of all deep thanks for this great package/framework !

I started to dive into the code because I want to understand better how things work and I am considering contributing if needed.
I have questions regarding datetimes. I think it is important as trading is all about timing, right ?...

I ran the following command from the top level of the package tree:
```
find . -name "*py" | xargs grep -e "now("
```

And found many different usages regarding how to retrieve the **'now'** datetime.
Here they are:
```
datetime.now()
datetime.now(timezone.utc)
datetime.utcnow()
arrow.utcnow()
arrow.Arrow.utcnow()
```

I find it quite weird (no harm intended) that there are this many ways of getting a **'now'** datetime. Sometimes naive datetimes are used, sometimes timezone aware ones, there also UTC and non UTC (e.g. local) ones.

From my personal (and up for discussion) experience datetimes should always represent the UTC time and be timezone aware. The idiom to do this is **datetime.now(timezone.utc)** as stated in this [warning](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow). If a local datetime is needed it can be obtained by converting with [datetime.astimezone()](https://docs.python.org/3/library/datetime.html#datetime.datetime.astimezone).

My questions:
- Are you sure that the code is accurate/bug free with these different function calls ?
- Don't you think the code should be factored to use only datetime.now(timezone.utc) ?
- Is the **arrow** package needed ? I don't have anything against it but I believe additional dependencies should be avoided when possible. From what I saw I think that the [datetime](https://docs.python.org/3/library/datetime.html) module can do the job even if I agree that it is poorly designed in some places.

I could take this task in charge if needed.

Regards.

(And thanks again for this golden framework)

**Comment by xmatthias** [comment]
The last 2 points (arrow related) are really identical - and are just different ways the library is imported.
It's also providing a native datetime (corresponding to `datetime.now(timezone.utc) `).

In my opinion, Arrow is needed as i'm yet to find a way to display relative timedifferences in a human friendly manner with the native datetime module (e.g. "5 minutes ago", "2 hours ago", ...) without developing that logic myself.
It's usage is however limited to mostly tests (`.shift()` is pretty convenient) and rpc - most other usages disappeared over time - or will disappear when time comes.



`datetime.utcnow()` should not be used in general - and the usages i know by memory are to compare it with itself at a later point (basically keep the timestamp of it in a variable, and look at it 5 minutes later to determine that 5 minutes have passed).
Timezone is not really relevant in that instance - but having it aligned would for sure be nice (but won't create problems i know about).

**Comment by neimad1985** [comment]
Ok thanks for the insights.
As long as you know that there is nothing buggy in those usages and do not seem in a hurry to align them I am closing the question.
Thanks for answering so quickly, that is much appreciable.

**Comment by xmatthias** [comment]
Especially for `datetime.utcnow()` usages, these could / should definitely be replaced. 

While i don't think they're buggy, it's a misalignment that's not really necessary - so if you're willing, PR's improving things are of course welcome 👍 

The same goes in principle for Arrow usages (as mentioned, except for `rpc/` modules - where usage is fully intentional).

**Comment by neimad1985** [comment]
All right. I'll get back to you. Do not hesitate to ping if not, I am quite busy.

**Comment by neimad1985** [comment]
Hi,

I have forked the freqtrade repo to start this PR.
From which branch should I branch, stable or develop (or any other) ?
Sorry for asking but not everybody works the same way and I didn't find this information in the contributing section of the documentation.

**Comment by xmatthias** [comment]
Develop is our main branch for work (so please start from that).

"stable" contains the latest release, which is merged from develop ~once a month.
