### ISSUE TITLE
`dry-run` and `live` simultaneously with same setup gives different results

### ISSUE THREAD

**Issue by tesla-cat** [freqtrade/freqtrade#5489]
- I am running two bots on two different computers, with exactly the same setup except for one is `dry run` and the other is `live`, that is the only difference
- the following is `live` 

![image](https://user-images.githubusercontent.com/28215638/131165099-85095803-ba28-4910-9289-c0be0897a27b.png)

- the following is `dry run`

![image](https://user-images.githubusercontent.com/28215638/131165196-e58eb35d-8116-4049-a5a5-385c27a6d275.png)

- I can understand that the profit is a bit different, that is ok
- but how come the pairs bought are different? the strategy should generate exact same signals at any time, (small timing difference can be ignored since the timeframe of `5m` is big enough)
- even if there is a difference, it should be the `dry run` bot having more buys rather than the `live` one, since in `dry run` orders are filled immediately whereas in `live` orders may not be filled, so one should have `numBoughtLive <= numBoughtDryrun`
- the config is default config expect for personal keys and pairlist

**Comment by xmatthias** [comment]
Dry-run orders can also be unfilled - and results are being simulated based on orderbook polling (as explained [in the docs](https://www.freqtrade.io/en/stable/configuration/#considerations-for-dry-run).

> the config is default config expect for personal keys and pairlist

if you're using different pairlists, you can't really expect alignment - as different pairs will produce different signals.

I'm doing the same test at the moment (more accidentally than on purpose) - and with pairlists aligned, buys/sells align almost perfectly (profits / entry points are off by a few .x%) - but the dry-run is on a kinda shitty server - so i blame the server for that :laughing: 

Your best bet is to compare the log of both - maybe there's other differences that prevent the bot from entering trades (maybe the dry-run bot is out of balance?).

**Comment by tesla-cat** [comment]
> the config is default config expect for personal keys and pairlist
- what I meant is that, I only changed personal keys and pairlist, as compared with the original config file that is autogenerated. 
- For `dry run` and `live` cases above the pair lists used are the same. So basically for the two cases the entire `ft_userdata` folder are the same except for one has `"dry_run": false` and the other has `"dry_run": true`
- I also noticed this by accident, originally I was just testing whether the server can handle the bot haha

anyways thanks for the comment, I will read through the logs and also observe longer

**Comment by xmatthias** [comment]
it's very difficult to get 100% alignment - especially on pretty active strategies.

Assume one bot stays in a trade 10 minutes longer (slow movement - and it entered "slightly" higher - so didn't reach profit yet).
Because of this 10min delay, you might be missing the next trade on another pair - as the trade-slot is not yet available (once the slot becomes available, the signal is gone).

**Comment by tesla-cat** [comment]
## the following is `live`

![image](https://user-images.githubusercontent.com/28215638/131202187-5ee3fbb0-79ae-419a-98f6-4d25e753865d.png)

---

## the following is `dry run`

![image](https://user-images.githubusercontent.com/28215638/131202215-c9b046b9-7dcc-4401-9979-1339008c3a5d.png)

**Comment by xmatthias** [comment]
Screenshots are pointless, with only this information i can also close this issue as itll not lead to anything other than you complaining without investing the time to investigate.

Its the log that counts, not the visualization.

Its however up to you to compare the single logs and figure out what creates the difference.

Itll either be different configs, unfilled orders, insufficient balance, or differences in the strategy.

It's however mostly strategy dependent (maybe the signal is not stable and produces random signals) - so also getting in touch with the author (i know you didn't write this strategy) might be an option.

It's however nothing freqtrade itself causes, but a combination of circumstances does.
