### ISSUE TITLE
RF is much better for hyperopt

### ISSUE THREAD

**Issue by squat0001** [freqtrade/freqtrade#5492]
I use freqtrade in/at devel.
I do use hyperopt .. and i know the endless discussion about how it finds its minima.

So .. i experimented with the Optimizer from skopt.
Using RF = Random Forest makes to optimization much bettter, and faster.

So .. please change the default, or add an option to choose the estimator for the Optimizer.

```
--- a/freqtrade/optimize/hyperopt.py
+++ b/freqtrade/optimize/hyperopt.py
@@ -375,7 +375,7 @@ class Hyperopt:
     def get_optimizer(self, dimensions: List[Dimension], cpu_count) -> Optimizer:
         return Optimizer(
             dimensions,
-            base_estimator="ET",
+            base_estimator="RF",
             acq_optimizer="auto",
             n_initial_points=INITIAL_POINTS,
             acq_optimizer_kwargs={'n_jobs': cpu_count},

```

**Comment by xmatthias** [comment]
It will depend on your searchspace and parameters.

In my tests, ET took 22m, while RF took 24 minutes for the same optimization (same strategy, same space, same number of epochs).

ET also got the better results than RF - so the results you see are not correct, or (more likely) only apply to your specific case / searchspace, but not in general.

I'm also not the first to come to this conclusion - if you search issues long enough through issues here you'll discover that others did similar tests, and came to the same conclusion.

**Comment by squat0001** [comment]
That's true, in my search space I use a lot categorical parameters, for which ET never reaches any stable point. But a switch for selecting would be nice.Am 28.08.2021 13:55 schrieb Matthias ***@***.***>:
It will depend on your searchspace and parameters.
In my tests, ET took 22m, while RF took 24 minutes for the same optimization.
ET also got the better results than RF - so the results you see are not correct, or only apply to your specific case.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/freqtrade/freqtrade/issues/5492#issuecomment-907616067",
"url": "https://github.com/freqtrade/freqtrade/issues/5492#issuecomment-907616067",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by xmatthias** [comment]
Feel free to submit a pull request for that if you think it's necessary (i think it's not so i'll not spend my time on this, but i'll surely not reject a well made PR introducing this).

Please also include documentation on when to include which estimator - so users can make an informed decision.

**Comment by Pascal66** [comment]
In my side, I always change it to 'GBRT', because I 'feel' it converging faster, with `-e` set to a lower value
It's certainly more a 'feeling' than a real optimization, but can be an option
