### ISSUE TITLE
Not same result on live and backtesting for same period

### ISSUE THREAD

**Issue by rongybika** [freqtrade/freqtrade#5494]
Hi,

Unfortunately I can't get same results on live and backtesting for the same period (aprox. half of the profit). The main difference is with the total trades. I have more trades on backtesting.
Maybe somebody can tell me which extra settings I should use to get the same results on live run.
I have no idea what I'm doing wrong.
I'm using GodStraNew strategy.

Thank you

**Comment by xmatthias** [comment]
This can have many reasons - often, strategies that underperform in live are simply looking into the future (at least partially) - which makes them great in backtesting, and work not so well (or not at all) in dry/live.


In GodStraNew's case, it's a pretty simple (hidden) lookahead bias.
If you look at the normalize function, you'll notice that it'll use the total dataframe's min/max to determine the range to factor.

As live will not have the full range available (only the last 1000 candles) - this range will be different. 
So depending on the pair (if it moved a lot or not in your backtest period) - results will be different and cannot be reproduced.

Another factor can be unfilled trades - but you should see these in the logs / messages.

**Comment by rongybika** [comment]
Thank you for quick answer.

I just noticed that is a different buy time in live and backtesting. I didn't noticed this until at this moment. 
I'm using market buy and sell so is not the situation with unfilled trades. 
I'm not a big python programmer, do you have any suggestion how I should fix this ,,issue" in this strategy?

Thanx

**Comment by xmatthias** [comment]
remove the normalize function? 

you can't really force indicators into a fixed window without knowing their range upfront - so normalizing can't be applied like this (it would be possible per indicator most likely - but that'll not work with that messy strategy.

Best bet is to use a better designed strategy - not one that's bruteforcing all possibilities.
Also - while freqtrade-strategies provides these strategies - almost all are community provided and we can't guarantee any profits.
