### ISSUE TITLE
Hyperopt reproducibility/brute forcing.

### ISSUE THREAD

**Issue by neimad1985** [freqtrade/freqtrade#5497]
**Freqtrade version 2021.7**

Hi,

I have a question regarding hyperopt results. Sorry if my vocabulary is wrong as I have no knowledge in mathematical optimization theories and do not hesitate to correct me.

Suppose I have a dumb strategy in which I buy when the RSI is above a given value.
I want to find the best value for my buying RSI threshold value so I use the hyperopt module and test the range say 70-80.

When I run hyperopt several times in a row I get a different result value for my optimal RSI threshold value from time to time.
**I don't understand this.**

From my understanding hyperopt picks a value randomly in the buy space for each round (epoch ?), runs backtesing, runs the loss-function and then tells me what was the best round and its corresponding RSI value.

First, I need to be sure of a few things so that I can ask my final question:
- Is it correct to say that an epoch is a round of backtesting ?
- If I have 100 epoch does it mean that the backtesting will be run 100 times with each time a different random RSI value ? (kind of the same question written differently)

In this is true I don't understand why my results vary between two runs of the hyperopt module.
I thought that if the optimization space size is more little than the number of epochs I may be in some kind of brute force scenario. I mean if I have 11 RSI values (70 to 80) and 100 rounds/epochs in the end all RSI values should be tested, randomness is not needed here, and I should have the same final result each time I run hyperopt.

I know that the random state helps reproducibility, I tested it and that's true, but in this case I thought it would be of no importance.
For me the random state should be relevant only in cases where my optimization space size is bigger than my epoch number. I mean if I have 1000 values to test and only 100 epochs to do so it is obvious that I cannot test everything and that two hyperopt runs will lead to different results as things are randomized.

So I went to the result json file and saw that not all values (70, 71,..., 79, 80) where tested each time. You may answer that this is normal because random means random and it is probabilistically possible that the same value can be picked 100 times for example, but at the same time it seems really dumb to me that not all values are tested in such a case. 

Can you tell me if I am missing something here ?
Is there a setting that I can enable when brute force is possible due to a little optimization space size ?

I hope my explanation was clear enough.

As I am new to the optimization field is there some relevant (and quite noob-oriented) documentation that you can point to me for reading so that I can get a better grasp on this ? I tried to read the skopt one but I lacking a lot of prior knowledge, I don't know what a bayesian search is, neither a noisy function, etc...

Thanks for your time.

**Comment by xmatthias** [comment]
One epoch is 1 backtest, that's for sure.

I think what you're missing is that hyperopt is not random / grid search, but baesian optimization.
So it'll not use "all" values and test each one of them, but it starts from a random point (30 random points in freqtrade's case) and tries to find local minima.

when you have a very small search-space, you'll soon get "objective has already been evaluated".
As you don't mention this, i assume that you're not reducing your space (`--space`). by default, ROI / stoploss spaces are included, which (while not infinitely large) - will have several 1000 possibilities each.

So your search-space wasn't 10 - but 10 + 1000 (from other spaces).

As each of these parameters has a random starting point, you'll probably get different results each time.

Assuming your "small" space is the only available sell parameter - you should then use `--spaces sell` to limit the search ONLY to that parameter to make your results more towards what you expect.

**Comment by neimad1985** [comment]
Sorry I forgot to mention that I set --space buy so there is no roi or whatsoever optimization. My search space size is indeed 10 (11 to be exact).

So my initial question remains.

Do you want me to provide the strategy, command lines I run, etc ?

And you are right I quickly get the "objective has already been evaluated" message.

**Comment by xmatthias** [comment]
Then i'm not sure i understand your question.

Running with a space of only 10 points (assuming everything else is identical) for say 100 epochs will result in 10 different results.

You can restart that hyperopt 200 times, you'll still only get the same 10 results (there's nothing more in it).

If that's not the case, then either your space is not 10/11 (maybe you're using `DecimalParameter` instead of `IntegerParameter`) or your strategy does not produce the same exact results with every run - which most likely means it's using some form of "now" data (like orderbook) - which is changing all the time - or you're providing a "non-supported" parameter to an indicator (iirc MACD had such a case with very low 3rd parameters).

**Comment by neimad1985** [comment]
Ok I am going double check everything from the start and post a complete example if the question remains.
Thank you.

**Comment by xmatthias** [comment]
I'll assume this worked out.

Feel free to reopen if you're still having trouble with this.
