### ISSUE TITLE
Question percentage performance in stake/fiat currency

### ISSUE THREAD

**Issue by heizie78** [freqtrade/freqtrade#5503]
Hi! Is there a possibility to see the "total percentage performance" for the full time freqtrade is currently running? With that I mean the difference between the starting balance (either dry_run_wallet or Binance) of the freqtrade run and the current balance (incl. value of open trades). It would be helpful to see this at a glance in the stake currency as well as in the fiat currency (including exchange rate changes).

I'm new to freqtrade and I spend a lot of time the last days with setting it up, (back)testing strategies and reading the docs. Also I was searching the issue tracker, but could not find an answer for below question. Neither I could find anything in the logs or on FreqUI. Sorry, if the answer was already given and this is a duplicate.

Thanks,

**Comment by xmatthias** [comment]
you can see that via telegram as `/profit` as explained [here](https://www.freqtrade.io/en/stable/telegram-usage/#profit).

**Comment by heizie78** [comment]
Thanks! Can I also see the same for the fiat currency somewhere? at least the current and starting balances in both currencies to calculate it? Reason behind is that I want to easily compare this investment to any other fiat investment (e.g. stoc/ETF portfolio)

EDIT: I think in /balance almost all is there. Only starting capital in fiat at starting time and the percentage calculation would be missing.

**Comment by xmatthias** [comment]
I'm not sure i understand your point / question - the 2nd row of the /profit output is FIAT currency (in the example 62 USD). 
There's no point in showing a relative profit for that again - as relative profits won't change with currency conversion.

**Comment by heizie78** [comment]
Looks like we're talking past each other a bit. ;-) Let me try to explain better what my question is. Example:

My stake currency is USDT. Fiat shall be EUR. Let's say I start trading today with 1000 USDT. So my balance today is 1000 USDT, or in fiat 849,44 EUR. Now each trade (hopefully) generates a positive profit in USDT. This profit goes to my USDT balance. 5 days and xx trades later I have lets say 1100 USDT (estimated in USDT and fiat = balance + current value of open trades). So my profit for the whole investment of 1000 USDT is 100 USDT or 10%, but inbetween the conversion rate for USDT has dropped from the inital 0,84944 EUR to 0,7955 EUR. So my 1100 USDT balance is worth 875,05 EUR. This would mean I still made 100 USDT or 10% profit, but in fiat just 3,01%. Can I see this already somewhere?

**Comment by xmatthias** [comment]
no. movements between fiat (USDT / EUR) are also usually pretty small - and the source for it is coingecko - which i trust with crypto pairs - but not necessarily with rates for fiat/fiat pairs.

**Comment by heizie78** [comment]
I agree. I would not not rely on it for fiat/fiat, but for crypto/fiat it should be fine. You're right, USDT is pretty stable, but for another stake currency it could be different. Especially over a long run time like a few weeks or months.

I think a small additional info like below could be useful (and similar on FreqUI). What do you think?

Conversion rate as in the example above for demonstration.
![grafik](https://user-images.githubusercontent.com/32620611/131499403-6e19a20b-60f8-428f-b0ad-c011d1231dce.png)
