### ISSUE TITLE
Split pot by controlled proportion across whitelist

### ISSUE THREAD

**Issue by simonmelouah** [freqtrade/freqtrade#5512]
Apologies if this is already available but it doesn't appear to be obvious in the documentation. It would be very useful if you had more granular control over how the pot was split across the whitelist i.e. that the whitelist could be either an array or hash table, where the latter allows you to define what proportion of the pot you want split across which coins
```
pot: "$100"
whitelist:
{
   "BTC": .3, # $30 for bitcoin
   "ETH": .4,
   "LTC": .4
}
```

**Comment by xmatthias** [comment]
This can be accomplished pretty easily by using the `custom_stake_amount()` callback ([Documentation page](https://www.freqtrade.io/en/stable/strategy-advanced/#stake-size-management)).

While it may seem more work at first, it provides the best flexibility to fulfill also more complex scenarios.

**Comment by simonmelouah** [comment]
Great, didn't realise this was something that could be done.
