### ISSUE TITLE
Custom notifications/webhooks

### ISSUE THREAD

**Issue by simonmelouah** [freqtrade/freqtrade#5513]
## Your question
Is it possible to get notifications upon a define price increase that's configurable and adjustable similar to a stoploss? The context is if the price has increased by x percent, execute this code, then change the x percent to a new value to send a notification for.

**Comment by xmatthias** [comment]
Freqtrade will send notifications on events that happen (startup, buys, sells, buy/sell fills and order cancels).

Freqtrade is however not (and doesn't try to be) a notification bot, which will alert you of price changes. 

While i guess it can be possible to implement something in the strategy - it's not supported / possible natively - and honestly, i don't see much reason for that either. 
You'll be spammed with notifications so you'll stop looking at them anyway (notification fatigue).
happens with buy/sell only notifications if you have a strategy with 20-30 trades per day already- so notifications on price changes will be even worse.

**Comment by simonmelouah** [comment]
The use-case I'm thinking about isn't to log the increase but to simply have a positive threshold percentage trigger that's configurable and changeable like the stoploss, ie so that you can change/decrease the stoploss potentially on an open trade if need be or to potentially train a basic regression model at runtime per change. If you set the value to be high enough you can assume notification fatigue is highly unlikely (+5% increase on btc for example definitely won't cause it)

**Comment by xmatthias** [comment]
The strategy will get "notifications" if you will for different purposes ([advanced docs](https://www.freqtrade.io/en/stable/strategy-advanced/)).
You can abuse one of these - maybe `custom_sell()` to trigger a webhook i guess.

That's however something VERY specific (you'll also need the endpoint to accept and act on that), so i doubt it'll provide much benefit to the overall userbase - and therefore i don't see it as something that should be built into freqtrade itself.
