### ISSUE TITLE
hyperopt loss function max draw down

### ISSUE THREAD

**Issue by squat0001** [freqtrade/freqtrade#5514]
Hi!

here a small addition to the loss functions already available.

```
from datetime import datetime
from freqtrade.data.btanalysis import calculate_max_drawdown
from freqtrade.optimize.hyperopt import IHyperOptLoss
from pandas import DataFrame

# optimize for max draw down and profit
# less max draw down more profit -> lower return value
class MaxDrawDownHyperOptLoss(IHyperOptLoss):
    @staticmethod
    def hyperopt_loss_function(results: DataFrame, trade_count: int,
                               min_date: datetime, max_date: datetime,
                               *args, **kwargs) -> float:

        max_drawdown = calculate_max_drawdown(results)
        max_drawdown_rev = 1 / max_drawdown[0]
        total_profit = results['profit_abs'].sum()
        ret = max_drawdown_rev * total_profit

        return -ret
```

**Comment by xmatthias** [comment]
The correct / proper way to contribute a new loss function is as Pull request.

pasting finished code into an issue, you're basically dumping it "someplace" - which somehow translates to "throwing it there - do the work to incorporate it properly" ...

---

About the function itself - i fear that with compounding, profit will dominate this function.
you might need to be careful with the return-values too - as you're using the relative profits from drawdown, comparing it to the absolute profit (in stake currency).

**Comment by squat0001** [comment]
Hi!The function calculates a multiplier from drawdown, the lower Drawdown is the higher the multiplier.Profit is just a factor, it does not matter if it is ratio or abs. The way here shown works fine. Some could include this kind of calculation also in the existing Sharpe/Sorting Loss functions.Why not a PR? I do not have a clean tree of freqtrade for this. The last time I tried I always messed up history.greetingsAm 31.08.2021 06:46 schrieb Matthias ***@***.***>:
The correct / proper way to contribute a new loss function is as Pull request.
pasting finished code into an issue, you're basically dumping it "someplace" - which somehow translates to "throwing it there - do the work to incorporate it properly" ...

About the function itself - i fear that with compounding, profit will dominate this function.
you might need to be careful with the return-values too - as you're using the relative profits from drawdown, comparing it to the absolute profit (in stake currency).

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.


Am 31.08.2021 06:46 schrieb Matthias ***@***.***>:
The correct / proper way to contribute a new loss function is as Pull request.
pasting finished code into an issue, you're basically dumping it "someplace" - which somehow translates to "throwing it there - do the work to incorporate it properly" ...

About the function itself - i fear that with compounding, profit will dominate this function.
you might need to be careful with the return-values too - as you're using the relative profits from drawdown, comparing it to the absolute profit (in stake currency).

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.


Am 31.08.2021 06:46 schrieb Matthias ***@***.***>:
The correct / proper way to contribute a new loss function is as Pull request.
pasting finished code into an issue, you're basically dumping it "someplace" - which somehow translates to "throwing it there - do the work to incorporate it properly" ...

About the function itself - i fear that with compounding, profit will dominate this function.
you might need to be careful with the return-values too - as you're using the relative profits from drawdown, comparing it to the absolute profit (in stake currency).

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/freqtrade/freqtrade/issues/5514#issuecomment-908895114",
"url": "https://github.com/freqtrade/freqtrade/issues/5514#issuecomment-908895114",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
