### ISSUE TITLE
Question Regarding Ratelimit

### ISSUE THREAD

**Issue by AAAAAAAM** [freqtrade/freqtrade#5517]
Im using it on docker,only 1 bot.

![image](https://user-images.githubusercontent.com/49510755/131464884-2293497f-3d63-4acf-b55c-322027052243.png)

my whole logs look like this

I've tried this with Ratelimit 1000 and I still get the same error.Anything I can do fix this?

**Comment by xmatthias** [comment]
First of all - please fill out the issue template. 
It's asking questions that are important for the answers - and filling it out avoids unnecessary back and forth.


This log is not from the exchange, but from coingecko. Ratelimit settings you make to the exchange class will not matter.

As you failed to fill out the issue template - i will assume you're using an old version (as some ratelimiting to coingecko was implemented a little while ago).
