### ISSUE TITLE
Inhibit sell flag

### ISSUE THREAD

**Issue by cpetra** [freqtrade/freqtrade#5521]
Hi,

Is there any way to postpone ROI handling? I know about the buy signal that, if set, will  postpone the sell, but I don't want that actually. If the close prices  are still rising I just want to postpone the sell until they fall again shortly - and I don't find a way to do this.

Thanks,
Costa

**Comment by xmatthias** [comment]
you're most likely looking for [trailing stop with positive offset](https://www.freqtrade.io/en/stable/stoploss/#trailing-stop-loss-custom-positive-loss).

alternatively, you can also prevent sells via the [trade-exit-confirmation](https://www.freqtrade.io/en/stable/strategy-advanced/#trade-exit-sell-order-confirmation) callback.
