### ISSUE TITLE
Handling of trade exits without stoploss_on_exchange

### ISSUE THREAD

**Issue by fadi-alkhoury** [freqtrade/freqtrade#5525]
## Describe your environment
Not relevant for this question
  
## Your question
Looking at the [exit_positions](https://github.com/freqtrade/freqtrade/blob/93c1dff71bbae773b922794f956013e0d0b9c908/freqtrade/freqtradebot.py#L674) function, it seems like only trades with stop-loss on exchange are handled. Is this intended? What about trades with a stop-loss that is not sent to the exchange but triggered internally within the bot?

**Comment by xmatthias** [comment]
I think you've missed the statements [2 lines below the one you linked](https://github.com/freqtrade/freqtrade/blob/93c1dff71bbae773b922794f956013e0d0b9c908/freqtrade/freqtradebot.py#L680) - which calls `handle_trades()` - which is handling open trades.

**Comment by fadi-alkhoury** [comment]
Thanks for the clarification. Yes, the condition
`trade.open_order_id is None and trade.is_open and self.handle_trade(trade)`
was not very obvious for me. Why is it required that open_order_id is None? Looking at [execute_entry](https://github.com/freqtrade/freqtrade/blob/93c1dff71bbae773b922794f956013e0d0b9c908/freqtrade/freqtradebot.py#L523), it seems that the order ID comes from the exchange.

**Comment by xmatthias** [comment]
`open_order_id` defines that an open buy (or sell) order is active - and is removed when it's filled.

this means you're either not in a trade yet (open buy order) - or a sell order is open (handle_trade created a sell already).
both cases require different handling than what handle_trade can provide.
