### ISSUE TITLE
Working offline

### ISSUE THREAD

**Issue by neimad1985** [freqtrade/freqtrade#5526]
Hi,

Is there any way to work with backtesting/hyperopt offline.
I have downloaded the data I need so I think I should be good to go but when freqtrade starts it seems to be contacting the exchange for some information and I get a network error.
Is there a way to avoid this ?I didn't see anything related to this in the documentation.
Thank you.

**Comment by xmatthias** [comment]
freqtrade needs the exchange's market information (which pairs exist, what are it's fees, what are the minimum tradable sizes, ...)) also for backtesting/hyperopt. 
This data that is downloaded with `download-data` is candlestick (ohlcv) data.

As such - working offline (also for backtesting/hyperopt) is not possible.

**Comment by neimad1985** [comment]
Ok thanks
