### ISSUE TITLE
Show average profit in overview

### ISSUE THREAD

**Issue by TheDigitalChef8** [freqtrade/freqtrade#5527]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
## Describe the enhancement

I would like to see (daily / monthly / yearly) average profit in the /profit RPC 

Example: 

ROI: Closed trades
∙ -
∙ -
ROI: All trades
∙ -
∙ -

Total Trade Count: -
First Trade opened: -
Latest Trade opened: 15 hours ago
Win / Loss: 68 / 12
Average Weekly Profit: -% (100 USDT)
Avg. Duration: TIME
Best Performing: PAIR

*Explain the enhancement you would like*

**Comment by xmatthias** [comment]
We do however have a `/daily` command - which can also be extended to work for multiple weeks (e.g. `/daily 30`).
Aggregations over longer timeperiods will probably raise more questions than it'll help (is it running current month? is it MTD, expected for the month if it continues as is? ...) - and in the end, you'll care more about the profit that was already realized.

If you think this is a must however, feel free to add this functionality via a Pull request. Should be pretty easy, and will probably only touch 2-3 files (excluding tests).

**Comment by noorbhtiti** [comment]
Can I work on this issue?

**Comment by TheDigitalChef8** [comment]
Yes I will have time only this weekend

**Comment by Merinorus** [comment]
Wouldn't it be more convenient to implement /weekly and /monthly commands?
It might make sense even if the bot was sometimes down. People would be free to use these commands or not, anyway.

**Comment by xmatthias** [comment]
As mentioned above - feel free to create a pull request adding these commands. It's explicitly marked as "Good first issue", which usually means 2 things: 
* It's low complexity
* it's intentionally left behind by experienced contributors - so new contributors get a chance to get into contributing.

**Comment by Merinorus** [comment]
Thank you, time to try my first PR then.

Currently I have done a "naive" /weekly and /monthly. They are based on rolling period:

```
/daily

Daily Profit over the last 7 days:
Month       Profit BUSD    Profit EUR    Trades
----------  -------------  ------------  --------
2021-11-04  0.000 BUSD     0.000 EUR     0 trades
2021-11-03  0.000 BUSD     0.000 EUR     0 trades
2021-11-02  0.000 BUSD     0.000 EUR     0 trades
2021-11-01  0.000 BUSD     0.000 EUR     0 trades
2021-10-31  0.000 BUSD     0.000 EUR     0 trades
2021-10-30  0.000 BUSD     0.000 EUR     0 trades
2021-10-29  0.000 BUSD     0.000 EUR     0 trades


/weekly

Weekly Profit over the last 8 weeks:
Week        Profit BUSD    Profit EUR    Trades
----------  -------------  ------------  --------
2021-11-04  0.000 BUSD     0.000 EUR     0 trades
2021-10-28  0.000 BUSD     0.000 EUR     0 trades
2021-10-21  0.000 BUSD     0.000 EUR     0 trades
2021-10-14  0.000 BUSD     0.000 EUR     0 trades
2021-10-07  0.000 BUSD     0.000 EUR     0 trades
2021-09-30  0.000 BUSD     0.000 EUR     0 trades
2021-09-23  0.000 BUSD     0.000 EUR     0 trades
2021-09-16  0.000 BUSD     0.000 EUR     0 trades


/monthly

Monthly Profit over the last 6 months:
Month       Profit BUSD    Profit EUR    Trades
----------  -------------  ------------  --------
2021-11-04  0.000 BUSD     0.000 EUR     0 trades
2021-10-04  0.000 BUSD     0.000 EUR     0 trades
2021-09-04  0.000 BUSD     0.000 EUR     0 trades
2021-08-04  0.000 BUSD     0.000 EUR     0 trades
2021-07-04  25.519 BUSD    22.114 EUR    2 trades
2021-06-04  0.000 BUSD     0.000 EUR     0 trades
```

What I suggest:

- For months: current month M, M-1, M-2... all months should start from the 1st
- For weeks: Week number starting from monday (ISO norm)? I don't want to overcomplicate things with a "starting day of the week" JSON field in the config file.

Thank you in advance for your feedback!

**Comment by xmatthias** [comment]
@Merinorus Looks good already.
Please create a pull request ([read here if you're unsure how to](https://guides.github.com/introduction/flow/)) for this (you can include the comment from above as pull request description) - so we can discuss on this on a code (or per line) basis where necessary.

as for how it's done, i'd for now leave that up to you (and eventually comment) - but please try and add the mode in the output (like - `Rolling Weekly Profit over the last 8 weeks:`) - so it's clear how it's calculated.

**Comment by Merinorus** [comment]
Thank you! 

Finally the commands behavior follow the same logic:
- `/daily` starts at midnight,
- `/weekly` starts Monday (ISO standard),
- `/monthly` starts the first day of the month.

```
/weekly

Weekly Profit over the last 8 weeks (starting from Monday):
Monday      Profit BUSD    Profit EUR    Trades
----------  -------------  ------------  --------
2021-11-01  0.000 BUSD     0.000 EUR     0 trades
2021-10-25  0.000 BUSD     0.000 EUR     0 trades
2021-10-18  0.000 BUSD     0.000 EUR     0 trades
2021-10-11  0.000 BUSD     0.000 EUR     0 trades
2021-10-04  0.000 BUSD     0.000 EUR     0 trades
2021-09-27  0.000 BUSD     0.000 EUR     0 trades
2021-09-20  0.000 BUSD     0.000 EUR     0 trades
2021-09-13  0.000 BUSD     0.000 EUR     0 trades


/monthly

Monthly Profit over the last 6 months:
Month    Profit BUSD    Profit EUR    Trades
-------  -------------  ------------  --------
2021-11  0.000 BUSD     0.000 EUR     0 trades
2021-10  0.000 BUSD     0.000 EUR     0 trades
2021-09  0.000 BUSD     0.000 EUR     0 trades
2021-08  26.109 BUSD    22.621 EUR    1 trades
2021-07  -0.591 BUSD    -0.512 EUR    1 trades
2021-06  0.000 BUSD     0.000 EUR     0 trades
```

Let's see how it goes in the pull request.
