### ISSUE TITLE
How to code the bot to make it buy when the rsi touch a certain RSI level?

### ISSUE THREAD

**Issue by castalia3** [freqtrade/freqtrade#5542]
* Operating system: RASPBERRY PI4 8GB - RASPBIAN
  * Python Version: python 3.7.3
  * CCXT version: 1.49.73
  * Freqtrade Version: develop-e1447f95
  
How to code the bot to make it buy when the rsi touch a certain RSI level? Right now it buy or sells only if the candle close over that certain level that i coded, not just when it reaches it.

```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)

        # Bollinger bands
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband'] = bollinger['lower']
        dataframe['bb_middleband'] = bollinger['mid']
        dataframe['bb_upperband'] = bollinger['upper']

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                    (dataframe['rsi'] < 27) &
                    (dataframe['close'] < dataframe['bb_lowerband'])
```

**Comment by xmatthias** [comment]
"touch" is not a very well defined term. 
Assuming a level of 30 ... is it touching if it's 30.1 before going up again? or will it have to go to 29.9, before going up again?

What you're most likely asking for is cross (must be below before, above after) - for which we have examples in the sample strategy (e.g. `qtpylib.crossed_above()`)

**Comment by castalia3** [comment]
Thanks for your quick reply.
I mean that: with the current setting, and candles at 15m, the RSI must remain below 27 for 15m (close of the candle) for the purchase to take place, I wish it was enough for it to reach the value of 27 for a second to determine the purchase. And the same for the sell

**Comment by xmatthias** [comment]
What you're talking about is called repainting (relying on values that only appear intra-candle).
It's a "feature" that many strategies on tradingview suffer from - so they show great in backtesting, but in live they repaint and therefore cause unexplainable signals (which are gone a few seconds later).

That's something that cannot be backtested, and is also not possible with freqtrade, as you'll only get access to closed candles.

**Comment by castalia3** [comment]
> What you're talking about is called repainting (relying on values that only appear intra-candle).
> It's a "feature" that many strategies on tradingview suffer from - so they show great in backtesting, but in live they repaint and therefore cause unexplainable signals (which are gone a few seconds later).
> 
> That's something that cannot be backtested, and is also not possible with freqtrade, as you'll only get access to closed candles.

thank you
