### ISSUE TITLE
How to get the current trade profit

### ISSUE THREAD

**Issue by evo11x** [freqtrade/freqtrade#5554]
How can I get the current open trade profit in example_strategy ?

**Comment by xmatthias** [comment]
that question lacks some important information, like where you're trying to use this data (in which function).

you should also please get accustomed to fill out the issue template, as i'll be closing issues without it very soon (it's simply pointless for me to ask for  information again if it's already in a template that people decided to delete).

**Comment by evo11x** [comment]
I have my own function in class SampleStrategy(IStrategy):

using the latest freqtrade develop, ccxt 1.55.13, Windows 10 64-bit, python 3.9

**Comment by xmatthias** [comment]
You can get use [the Trade object](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-trades) to get trades.

This will however not work in any `populate_*` method during backtesting, as trade simulation only starts after calling these. it'll only work in callbacks (documented in the advanced strategy section).

**Comment by evo11x** [comment]
My function is called at the end of populate_sell_trend from sample_strategy

**Comment by xmatthias** [comment]
As explained above - then it will not be available during backtesting (it'll always show 0).

**Comment by evo11x** [comment]
ok, thanks! I will take a look at the callbacks

**Comment by evo11x** [comment]
Can I get the current open trade profit in the **_bot_loop_start_** callback ? I mean is it called for each candlestick in backtesting or just at the beginning of it?

**Comment by xmatthias** [comment]
i'd say the [documentation has you covered](https://www.freqtrade.io/en/stable/bot-basics/#backtesting-hyperopt-execution-logic). It's called once per backtest.
