### ISSUE TITLE
Make the bot automatically stop at a certain profit reached.

### ISSUE THREAD

**Issue by KarimHP** [freqtrade/freqtrade#5557]
Hi

So im trying to kind of set a take profit for my freqtrade bot, but all im finding are stop loss functions. 

For example lets say my stake currency ist USDT and i start with 1000 USDT. Now i want the bot bot to automatically stop when i have 2000 USDT = a profit of 100% is reached. 

How would i achieve this? 

Im sorry if this is a stupid question im still trying to learn my ways around the bot. im really helpful for every Answer :)

**Comment by raphant** [comment]
One way is to get your entire wallet value:
`self.wallets.get_total_stake_amount()`

Then get your starting balance
`self.wallets.start_cap`

You can then override `confirm_trade_entry` in your strategy to utilize these
```python
def confirm_trade_entry(
    self,
    pair: str,
    order_type: str,
    amount: float,
    rate: float,
    time_in_force: str,
    current_time: datetime,
    **kwargs
) -> bool:
    value = self.wallets.get_total_stake_amount()
    sb = self.wallets.start_cap
    if value >= sb * 2:
        return False
```
This will prevent the bot from making trades once you've reached 100% profit

**Comment by xmatthias** [comment]
This is not possible via a builtin way, and i'm not sure why you'd want this.

If your strategy is good and working, made you 100% profit, why not let it run to make another 100% ?
