### ISSUE TITLE
Adding a short trading position feature

### ISSUE THREAD

**Issue by AhmedSakrr** [freqtrade/freqtrade#5563]
## Describe your environment
(if applicable)

  * Operating system: Latest Ubuntu Release.
  * Python Version: Python3
  * CCXT Exchange: Binance.com
  * Freqtrade Version: Latest Stable Version Branch.

## Describe the enhancement

* Adding new feature: Ability to Shorting trades positions while the market is in downtrending and while the market is in uptrend freqtrade use the long trading position the normal method.

Could we add the short trades positions feature to Freqtrade?

**Comment by xmatthias** [comment]
Work on that is ongoing - and there's multiple issues for this already (e.g. #892).

Please use the search before opening an issue to avoid duplicates.
