### ISSUE TITLE
Problems with load_trades_from_db since Update 2021.8

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#5568]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: Python 3.7.4
  * CCXT version: ccxt==1.55.28
  * Freqtrade Version: 2021.8
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Since the update from version 2021.7 to 2021.8 my script based on freqtrade.data.btanalysis / load_trades_from_db is not working anymore. Has something been changed in the DB structure or something else affecting this module?

### Steps to reproduce:

my code snippet which did work in 2021.7

```
import numpy as np
import pylab as plt
import quantstats as qs
from freqtrade.data.btanalysis import load_trades_from_db, load_backtest_data
from mc_sim_fin.mc import mc_analysis
from datetime import datetime

# Fetch trades from database
trades = load_trades_from_db("sqlite://///home/andreas/freqtrade/databases_hot/BinHV45_hot.sqlite").dropna()

"""
Computations and data preparations
"""

# MC and others
trades['cum_profit'] = trades['profit_abs'].cumsum()
trades['cum_profit_perc'] = trades['profit_ratio'].cumsum()
```

here I get a value error after my update to 2021.8:

```
ValueError                                Traceback (most recent call last)
<ipython-input-1-9f20ef138db9> in <module>
     41 
     42 # Monte Carlo Analysis
---> 43 mc_sims_results = mc_analysis((trades[['close_date', 'profit_abs']]), start_equity, ruin_equity)
     44 prob_profit_is_positive = mc_sims_results['prob_profit_is_positive']
     45 mc_risk_of_ruin_pct = mc_sims_results['risk_of_ruin_percent']

~/freqtrade/.env/lib/python3.7/site-packages/mc_sim_fin/mc.py in mc_analysis(results, start_equity, ruin_equity, **kwargs)
     10     sim_years_duration, nb_iterations = helpers.extract_extra_params(kwargs)
     11 
---> 12     nb_trades_for_sample = helpers.comp_nb_trades_for_sample(date_results, sim_years_duration)
     13 
     14     iter_params = {'nb_trades_for_sample': nb_trades_for_sample,

~/freqtrade/.env/lib/python3.7/site-packages/mc_sim_fin/utils/helpers.py in comp_nb_trades_for_sample(date_results, sim_years_duration)
    109     avg_trades_per_year_result = get_avg_trades_per_year(nb_trades_result, nb_years_result)
    110 
--> 111     return get_nb_trades_for_sample(avg_trades_per_year_result, sim_years_duration)

~/freqtrade/.env/lib/python3.7/site-packages/mc_sim_fin/utils/helpers.py in get_nb_trades_for_sample(avg_trades_per_year_result, sim_years_duration)
     19 def get_nb_trades_for_sample(avg_trades_per_year_result: float,
     20                              sim_years_duration: float) -> int:
---> 21     return round(avg_trades_per_year_result * sim_years_duration)
     22 
     23 

ValueError: cannot convert float NaN to integer
```

  
### Observed Results:

Checking the labels of the latest DBs I recognized a change, adjusting my code accordingly:

```
trades['cum_profit'] = trades['close_profit_abs'].cumsum()
trades['cum_profit_perc'] = trades['close_profit'].cumsum()

```

Now i get a key error:

see log below

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

```
KeyError                                  Traceback (most recent call last)
~/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3360             try:
-> 3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:

~/freqtrade/.env/lib/python3.7/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

~/freqtrade/.env/lib/python3.7/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'close_profit_abs'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-1-6470943509c4> in <module>
     23 
     24 # MC and others
---> 25 trades['cum_profit'] = trades['close_profit_abs'].cumsum()
     26 trades['cum_profit_perc'] = trades['close_profit'].cumsum()
     27 trades['count_label'] = 1

~/freqtrade/.env/lib/python3.7/site-packages/pandas/core/frame.py in __getitem__(self, key)
   3453             if self.columns.nlevels > 1:
   3454                 return self._getitem_multilevel(key)
-> 3455             indexer = self.columns.get_loc(key)
   3456             if is_integer(indexer):
   3457                 indexer = [indexer]

~/freqtrade/.env/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: 'close_profit_abs'
```

**Comment by xmatthias** [comment]
The only real change to the database structure between these 2 versions is that `buy_tag` was added - but i don't see how this should affect your code (you could've done the diff yourself - github is very nice in that regards -> https://github.com/freqtrade/freqtrade/compare/2021.7...2021.8).

Apart from that, i'd not know about that - but then i also don't see it as my task to debug key-errors in custom scripts.

`close_profit_abs` was NOT modified between 2021.7 and 2021.8 - if you need adjustments because of that, then your script was not working before or you used a older version.

In my opinion, your dburl is wrong (one too many slashes at the beginning) - but maybe sqlalchemy is flexible enough to ignore that.

Best print all columns you get, and a few of the lines you get.
maybe your `.dropna()` is dropping too much / everything (maybe because of an empty column) - so the rest runs on an empty dataframe (but it's a guess, really).

**Comment by Prossi79** [comment]
awesome! thanks for your quick support .... removing one / in the DB url and removing  .dropna() brought back the functionality ... really strange, same code was working around 14 days before, maybe I was still on 2021.6

one question ... despite the DB columns are labelled differently  then in my code, it seems to work and no error - why is that?

trades['cum_profit'] = trades['profit_abs'].cumsum()
trades['cum_profit_perc'] = trades['profit_ratio'].cumsum() 

vs.

'close_profit_abs' and 'close_profit'

**Comment by xmatthias** [comment]
magic? 
`close_profit_abs` is not really part of `load_trades_from_db()` (never really has been) - so it's unclear to me why you would get it working with that, unless you used something else to load the trades.

**Comment by Prossi79** [comment]
yeah it is working with 'profit_abs' and 'profit_ratio' ... not with 'close_profit_abs'  .... okay, never mind I think I just mix something up

:) but I like your magic, all good now and working - thanks again!
