### ISSUE TITLE
Freqtrade hyperopt --method cuda/cpu

### ISSUE THREAD

**Issue by mablue** [freqtrade/freqtrade#5573]
There is a way to change calculations to cuda but Im try and cant run this code
 I think if some body do that It will be usefull for us:
https://www.google.com/amp/s/www.geeksforgeeks.org/running-python-script-on-gpu/amp/

**Comment by xmatthias** [comment]
Please use the search before opening new issues
This has been asked several times in the past (#5085, #5158), each of which includes explanations as of why this will not work.

From one of the above issues:
> freqtrade uses scikit-optimize / scikit-learn under the hood, so if you want GPU support, please talk to them first.
scikit-learn does however document their strategy around GPU [pretty clearly](https://scikit-learn.org/stable/faq.html#why-is-there-no-support-for-deep-or-reinforcement-learning-will-there-be-support-for-deep-or-reinforcement-learning-in-scikit-learn).
