### ISSUE TITLE
startup candle count beyond 992 ? 

### ISSUE THREAD

**Issue by OreNoMochii** [freqtrade/freqtrade#5577]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  * Strategy: _____
  
Note: All bug reports will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

hello, 
I have a  strategy on 1m timeframe but I need to increase the number of entry point to increase the number of startup_candle_count so far I can only go max to 992 do you know how I could increase to 1440 ? So I can get 24h data on 1m timeframe as a ref ? 

### Steps to reproduce:

1. put timeframe to '1m'
2. put startup_candle_count
3. run the bot with the command sudo docker-compose up -d 

  
### Observed Results:

Not able to go beyond 992 startup_candle_count

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 992

**Comment by xmatthias** [comment]
for backtesting, also values of more than 992 should be possible - but without having a reason to do it that way (see below).

For real mode (trade, dry-run) - you'll be limited to "one ohlcv request"  - which will be different per exchange.
It'll be roughly ~1000 for binance (fewer if there was a downtime) - 1400 for FTX, and ~500 for bittrex.

If you need more than the available data, then [informative pairs](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-informative_pairs) on longer timeframes is usually the solution - as i doubt that you'll need the indicators on 1m data for that long of a period.

**Comment by OreNoMochii** [comment]
ok thanks the response is clear. I'll try to explore informative pairs in that case.
