### ISSUE TITLE
[risk management feature] Dynamic stake amount based on asset's volatility

### ISSUE THREAD

**Issue by Visionary1** [freqtrade/freqtrade#5585]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*

Hi,
I've been backtesting with freqtrade for a while, 
and I noticed that freqtrade support dynamic stake amount - which uses portion of a user's current capital.

But I think it'll be nice to have a feature to dynamically adjust the stake amount of each trade using asset's volatility (ATR). Just like Turtle Trading System (https://www.definedge.com/turtle-trading-system/)

For example, if an asset has high volatility (ATR, 1 hour, 20 length), the stake amount will small, if an asset has low ATR, the stake amount for each trade will be big. Having a dynamic position size based on ATR with 2 ATR stoploss would increase the stability of strategies, and the overall long-term performance.

**Comment by xmatthias** [comment]
Freqtrade also allows the strategy to [control the stake](https://www.freqtrade.io/en/stable/strategy-advanced/#stake-size-management) - so it's up to the strategy author to implement this.

If you think this is **the** way to size trades, best contribute that to the documentation in the form of an example.

**Comment by Visionary1** [comment]
oh, I didn't realized stake size management function exist. 
Will look up and see what I can contribute. Thank you
