### ISSUE TITLE
How to get a window of candles in live trading from custom strategy

### ISSUE THREAD

**Issue by evo11x** [freqtrade/freqtrade#5590]
* Operating system: Windows 10 64-bit
  * Python Version: 3.9.6
  * CCXT version: 1.56.34
  * Freqtrade Version: freqtrade 2021.8
  
I understand that populate_buy_trend and populate_sell_trend contains the full range of candlestick data in backtesting, but how can I get a rolling window of 50 candles in live trading for buy/sell signals?

**Comment by xmatthias** [comment]
This question is pretty broad and not very clear.

In general, it's just a pandas dataframe, so anything around `dataframe['close'].rolling(50).<whatever>` should work - although it'll  depend on the function you'll need to apply afterwards.

Most indicators (ta-lib for example) will already apply rolling windows implicitly - so this is not always necessary.

**Comment by evo11x** [comment]
the problem with the rolling is that it does a .sum, or .mean operation on that range, but I need the arrays of open, close and indicators.

**Comment by xmatthias** [comment]
i'm not sure your question makes sense (it's lacking detail and is too generic).

even having the last 50 candles, you'll need to so something with it. Depending what that is, you'll have different options available.

**Comment by evo11x** [comment]
My question is the dataframe from populate_buy_trend  and populate_sell_trend in live trading contains all the downloaded chart/history and the last candlestick? and are called at each new candlestick? So I can take out an array of the last 50 candlesticks, I need it for deep learning which will set the buy/sell signals for live trading

**Comment by xmatthias** [comment]
yes, you'll get the last 500-1000 (exchange-dependent) candles, with the new candle being the last candle.

**Comment by evo11x** [comment]
Thank you xmatthias! that was I wanted to know
