### ISSUE TITLE
new Hyperoptable strategy interface help guide 

### ISSUE THREAD

**Issue by GurhanP** [freqtrade/freqtrade#5596]
Hi 
  * Operating system: Ubuntu 20.4.3____
  * Python Version: Python 3.8.10
  * CCXT version: ccxt==1.55.28
  * Freqtrade Version: freqtrade develop-11f08b005
  
## Your question
Hi  to developers, 

Thanks for all new updates,  however it is sometimes very hard to understand how to implement the new changes, 

Can you please guide , how to convert existing Hyperopt  to new Hyperoptable strategy interface  ?

Thanks a lot

**Comment by xmatthias** [comment]
It's outlined in the [documentation](https://www.freqtrade.io/en/stable/hyperopt/).

in the end, it'll be a lot simpler with the new interface - you'll just need to take the time to read (and understand) the documentation.

**Comment by GurhanP** [comment]
Thanks a lot, 
I read it many times, but frankly, I am not a programmer and it is not so easy, 
Can you put some more examples?

How to unite old Hyperopt scripts to new hypertoptable strategies 

A + B = C
D+ E = F
That will be great.  
Thanks in advance
