### ISSUE TITLE
Profitable strategies during downtrends

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#5604]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hello, I have not described my environment, because my question is not related to it.
I was told, that the public strategy NotAnotherSMAOffsetStrategy.py may be advantageous in case of downtrends.
Are there additional methods or strategies / configs, which are common, as the value of coins gets smaller?
Would be great, to leave the bot running during those periods.
If you think, there is a good description available, feel free, just to post the link here.
Many thanks in advance.

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
there are quite some strategies that can work in both up or downtrends.

In the end, it's up to you (the user) to backtest them with the desired markets (some work better on USDT, BUSD or BTC markets) to determine if they work for your selected market-segment or not.

You might also want to consider joining our [discord server](https://discord.gg/p7nuUNVfP7) to discuss this further - there's an additional collection of strategies available there, as well as discussions around strategies in general.

**Comment by myNextCoder** [comment]
I thank you for your input. If I understand you correctly, there is a channel on the discord server under 'freqtrade', which contains strategies for 'difficult' markets. Have you got a name of the channel or a link to these strategies?
(Yes, I will discuss those topics right there. . .)

**Comment by Zamalazamala** [comment]
No l did not receive the name of the chanbel

**Comment by xmatthias** [comment]
> I thank you for your input. If I understand you correctly, there is a channel on the discord server under 'freqtrade', which contains strategies for 'difficult' markets. Have you got a name of the channel or a link to these strategies?
> (Yes, I will discuss those topics right there. . .)

It's called #strategy-collection - it's not for difficult market-conditions per se - simply strategies. If they work in the conditions you expect them to is usually up to you to test.
Don't ignore other channels though - there's strategies posted there too, all the time.

@Zamalazamala please only answer/post on issues where you can contribute something. 
This is considered as spam (both here and on the other issue) - so please stop answering with random, non-helping phrases, thanks.
