### ISSUE TITLE
IBKR

### ISSUE THREAD

**Issue by SadiqJafferSaleh** [freqtrade/freqtrade#5608]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Is there any possibility to add IBKR API (TWS) , so we can use freqtrade for trading stock as well . https://www.interactivebrokers.com/en/index.php?f=5041*

**Comment by xmatthias** [comment]
Freqtrade is a crypto trading bot.

As such, it has no means or knowledge about market open/close times, so the integration alone will not bring it further.
Integrating other types of assets (other than crypto) is currently not something we'll be investing time in.

**Comment by fridary** [comment]
@xmatthias maybe you can add environment where I can send custom API to place orders?  For IB it's simple:
```
ib = IB()
ib.connect('127.0.0.1', 7497, clientId=1)
ib.placeOrder(Stock('AAPL', 'SMART', 'USD'), **kwards)
```

**Comment by xmatthias** [comment]
Freqtrade is a crypto trading bot.

Integrating other types of assets (other than crypto) is currently not something we'll be investing time in.
