### ISSUE TITLE
trouble running docker-compose

### ISSUE THREAD

**Issue by eL-Squaz** [freqtrade/freqtrade#5611]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Unless you're able to provide more details, we'll be unable to help and will have to close this issue.

**Comment by eL-Squaz** [comment]
oh, weird i entered a whole bunch of information... anyways.

I am running the dev version  and have configured my config file properly and have double and triple checked my configurations, but i keep getting this error : 
2021-09-23 19:51:14,687 - freqtrade.commands.trade_commands - ERROR - No Pairlist Handlers defined
2021-09-23 19:51:14,687 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 82, in __init__
    self.pairlists = PairListManager(self.exchange, self.config)
  File "/freqtrade/freqtrade/plugins/pairlistmanager.py", line 42, in __init__
    raise OperationalException("No Pairlist Handlers defined")
freqtrade.exceptions.OperationalException: No Pairlist Handlers defined

and this is my file configurations:

{
	"max_open_trades": 15,
	"stake_currency": "USDT",
	"stake_amount": 75.0,
	"tradable_balance_ratio": 0.99,
	"fiat_display_currency": "USD",
	"dry_run": true,
	"trailing_stop": false,
	"unfilledtimeout": {
		"buy": 10,
		"sell": 30,
		"unit": "minutes"
	},
	"bid_strategy": {
		"ask_last_balance": 0.0,
		"use_order_book": false,
		"order_book_top": 1,
		"check_depth_of_market": {
			"enabled": false,
			"bids_to_ask_delta": 1
		}
	},
	"ask_strategy": {
		"price_side": "ask",
		"use_order_book": false,
		"order_book_min": 1,
		"order_book_max": 9
	},
	"exchange": {
		"name": "binanceus",
		"key": "",
		"secret": "",
		"ccxt_config": {
        "enableRateLimit": false,
        "ccxt_async_config": {
            "enableRateLimit": false
        },
        "pair_whitelist": [
            "SOL/USD",
            "ETH/USD",
            "BTC/USD",
            "ADA/USD",
            "HBAR/USD",
            "HBAR/USD",
            "ALGO/USD",
            "DOGE/USD",
            "ONE/USD",
            "XTZ/USD",
            "UNI/USD",
            "EGLD/USD",
            "VET/USD",
            "ATOM/USD",
            "MATIC/USD",
            "OMG/USD"
        ],
        "pair_blacklist": [
            ".*UP/BNB",
             ".*DOWN/BNB",
              "BNB/.*"
            ]
        },
    "pairlists": [
        {"method": "StaticPairList"}
    ]
	},
	"edge": {
		"enabled": false,
		"process_throttle_secs": 3600,
		"calculate_since_number_of_days": 7,
		"capital_available_percentage": 0.5,
		"allowed_risk": 0.01,
		"stoploss_range_min": -0.01,
		"stoploss_range_max": -0.1,
		"stoploss_range_step": -0.01,
		"minimum_winrate": 0.6,
		"minimum_expectancy": 0.2,
		"min_trade_number": 10,
		"max_trade_duration_minute": 1440,
		"remove_pumps": false
	},
	"telegram": {
		"enabled": true,
		"token": "",
		"chat_id": ""
	},
	"api_server": {
		"enabled": true,
		"listen_ip_address": "0.0.0.0",
		"listen_port": 8080,
		"verbosity": "error",
		"enable_openapi": true,
		"jwt_secret_key": "",
		"CORS_origins": [],
		"username": "freqtrader",
		"password": ""
	},
	"bot_name": "Jarvis",
	"initial_state": "running",
	"forcebuy_enable": false,
	"internals": {
		"process_throttle_secs": 5
	}
}

I have tried "whitelist", "StaticPairList", and have even tried some of "deprecated" options.. I am starting it by:

$ sudo docker-compose run --rm freqtrade trade --config user_data/config.json --strategy MyStrategy

I am running windows 11 pro dev Insiders Preview, I have the latest version of Docker/Docker engine/Docker dekstop, running Ubuntu WSL2... uhm..

if theres anything else you might be wondering let me know..

Thanks ahead!

Josh

**Comment by eL-Squaz** [comment]
oh yeah, I have ccxt.pro installed, but I am attempting this startup with virtual env activated per freqtrade instructions so i don't think that would have any affect. but thought I would mention it, in case.

**Comment by eL-Squaz** [comment]
nevermind I fixed it! ty
