### ISSUE TITLE
custom_sell before candle close

### ISSUE THREAD

**Issue by mosaadeh** [freqtrade/freqtrade#5619]
* Operating system: Ubuntu 20.04.2 LTS
  * Python Version: 3.8.10
  * CCXT version: 1.55.28
  * Freqtrade Version: 2021.8
  
Hello, here is my custom_sell function:

```
def custom_sell(self, pair: str, trade: Trade, current_time: datetime, current_rate: float,
                current_profit: float, **kwargs):

    dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)

    if trade.buy_tag == 'GG' and (current_profit > 0.03):
        return 'sell_signal_GG'

    if trade.buy_tag == 'GR' and (current_profit > 0.02):
        return 'sell_signal_GR'

    if trade.buy_tag == 'RG' and (current_profit > 0.015):
        return 'sell_signal_RG'

    if trade.buy_tag == 'RR' and (current_profit > 0.01):
        return 'sell_signal_RR'
```

the problem that i am facing is that the bot is selling after the candle has closed above the profit target.
How can i get it to sell when the price reaches the target not when it close above the target.

**Comment by xmatthias** [comment]
in backtesting - you really can't as this function is called once per candle (unless you use [detailed timeframe](https://www.freqtrade.io/en/latest/backtesting/#improved-backtest-accuracy) - where it's called once per detailed timeframe *_only available in develop for now_).
But even with that approach, it'll still only be an approximation with a resolution of max. 1m.

for live - it'll sell "whenever" that function is returning true, which may or may not be within a candle.
As you're not using anything from the dataframe, there's no reason it would wait unless current-profit is not above that level yet.

**Comment by mosaadeh** [comment]
My strategy is running on 1m timeframe, is there a way to look at intra-candle price in 1m timeframe?

**Comment by xmatthias** [comment]
no. 
Exchanges provide candle-data down to the 1m level. 
While it would work in theory with trades-data - it's not implemented and most likely not worth the effort (from a community / project perspective) - as there's not too many people working with the 1m timeframe, as that's quite challanging to work with (you'll need to keep a pretty short whitelist to not run into timing problems with 1m timeframes).
