### ISSUE TITLE
Get the timestamp till bot is running, programatically 

### ISSUE THREAD

**Issue by botzill** [freqtrade/freqtrade#5622]
Hi.

Is there a way to get the time till the bot is running from the strategy? 

Thanks.

**Comment by xmatthias** [comment]
`/profit` will tell you time of the first trade that's in the database.

In itself - Freqtrade will not keep runtime statistics - so if your first buy happened 3 days after startup, it'll not remember this time. There's another open issue fro this in #2885 ... but as far as i know, there's been no action taken in this regards.
