### ISSUE TITLE
[Kucoin] Ghost buys. Buys not going through. Order does not exist. 

### ISSUE THREAD

**Issue by stigmaknight123** [freqtrade/freqtrade#5624]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: _____ (`python -V`)
  * CCXT version:1.56.86 
  * Freqtrade Version: Lastest Dev at time of posting  
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Bot would show a buy and it would not fill. However the bot would record it in the database file though. Using market orders. 

### Steps to reproduce:

Have bot running. So far only happened with QRDO/USDT on Kucoin for some odd reason. 
  
### Observed Results:

To be able to buy and sell order. 

### Relevant code exceptions or logs

2021-09-25 18:38:17,071 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: QRDO/USDT id: None). Message: kucoin order not exist."

**Comment by stigmaknight123** [comment]
Found the cause. 

![image](https://user-images.githubusercontent.com/15849763/134803644-ac35b7cc-f24e-48e4-b82e-b79287d5b172.png)

**Comment by stigmaknight123** [comment]
Is there anyways to make a failsafe for this so the bot knows it failed to fill the order due to this?

**Comment by xmatthias** [comment]
Well yes - "usually" freqtrade detects these things - but it will depend on the response kucoin gives when creating the order.

If it records it as filled, then the response must somehow indicate this.

Please run the following and provide me with the response shown (assuming your account cannot buy QRDO for whatever reason):
**(Careful - if your account is able to place this order, it'll buy 20 QRDO)**

``` python
import ccxt
exchange = ccxt.kucoin({'apiKey': '<yourApiKey>', 'secret': '<yoursecret>' })
res = exchange.create_order('QRDO/USDT', 'market', 'buy', 20)
print(res)
```

The Response should give us enough indication as to how kucoin answers to this.

**Comment by stigmaknight123** [comment]
Here is one with force buy. I am not sure how to input those other commands. I am using docker on canonical Ubuntu oracle server and import keeps not being found. Can you make a python script with the commands I would need? WOO/USDT is also unbuyable for me. Just need a non KYC account on Kucoin for testing. Sorry about this, I am not a programer. 

`2021-09-28 19:59:59,756 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade for WOO/USDT with stake_amount: 21.97865544336 ...
freqtrade    | 2021-09-28 20:00:00,500 - freqtrade.wallets - INFO - Wallets synced.
freqtrade    | 2021-09-28 20:00:00,505 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 17, 'type': buy, 'buy_tag': None, 'exchange': 'Kucoin', 'pair': 'WOO/USDT', 'limit': 0.77136, 'order_type': 'market', 'stake_amount': 21.97865544336, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'amount': 28.4933, 'open_date': datetime.datetime(2021, 9, 28, 20, 0, 0, 194439), 'current_rate': 0.77136}`

**Comment by xmatthias** [comment]
You can simply run `docker-compose run --rm --entrypoint python freqtrade`  to get to a python shell with everything installed. The above is then the python script to run.

My account on kucoin is non-KYC, but i can buy QRDO just fine - so i think it might be location based.

**Comment by stigmaknight123** [comment]
You are right. I am from the US. I am blocked from trading some tokens. 

`>>> print(res)
{'id': None, 'clientOrderId': '814613', 'info': {}, 'timestamp': 1632949363885, 'datetime': '2021-09-29T21:02:43.885Z', 'lastTradeTimestamp': None, 'symbol': 'QRDO/USDT', 'type': 'market', 'side': 'buy', 'price': None, 'amount': 20.0, 'cost': None, 'average': None, 'filled': None, 'remaining': None, 'status': None, 'fee': None, 'trades': None}`

**Comment by xmatthias** [comment]
That's an interesting response for a rejected order (especially the missing `info` section).

Am i right in assuming that this order was not correctly placed on the exchange? (i'm asking because it got assigned a `"clientOrderId"` by the exchange.

what will the following yield for you now (querying the same trade again ...)

``` python
import ccxt
exchange = ccxt.kucoin({'apiKey': '<yourApiKey>', 'secret': '<yoursecret>', 'password': '<yourapipass>' })
res = exchange.fetch_order('814613', 'QRDO/USDT')
print(res)
```

It'd also be interresting to have the full logs of the original problem if they are still available (sorry for forgetting to ask before) ...

**Comment by raphant** [comment]
I'm in the US as well and also ran into this problem:
```python
res = exchange.create_order('QRDO/USDT', 'market', 'buy', 20)
print(res)
{'id': None, 'clientOrderId': '1d36b8a2-5d86-49df-90d3-0334d665b1e0', 'info': {}, 'timestamp': 1633426622776, 'datetime': '2021-10-05T09:37:02.776Z', 'lastTradeTimestamp': None, 'symbol': 'QRDO/USDT', 'type': 'market', 'side': 'buy', 'price': None, 'amount': 20.0, 'cost': None, 'average': None, 'filled': None, 'remaining': None, 'status': None, 'fee': None, 'trades': None}
```

```python
res = exchange.fetch_order('1d36b8a2-5d86-49df-90d3-0334d665b1e0', 'QRDO/USDT')
print(res)
```
Output:
`ccxt.base.errors.OrderNotFound: kucoin order not exist.`

> Am I right in assuming that this order was not correctly placed on the exchange?

Indeed

**Comment by xmatthias** [comment]
Can you try running the above again, but with a `exchange.verbose = True` before placing the order via ccxt?
It should output a "helluvalot" stuff - most of which will be for nothing - but still useful to debug. 

Best send me the output of this via DM in Discord, as it does contain Parts of the private key (a derivate of that) - and i'm not sure how secure kucoin implements this, and don't wanna risk...


The response from kucoin does not contain any hint that the order failed to place - which makes it pretty difficult to handle this correctly.
If it happened on a running bot - would you mind sharing the log of this buy? (basically from the buy signal until the bot thinks the order is filled).
Thanks in advance.

**Comment by bgi123** [comment]
I don't have the logs for this problem anymore since I just black listed all the banned USA tokens and tried some new bots.

**Comment by stigmaknight123** [comment]
I blacklisted all the tokens I needed and the bots on the vps doesn't record any logs at all.

**Comment by xmatthias** [comment]
you should be getting the heartbeat logmessage ... otherwise something will be wrong.

**Comment by raphant** [comment]
Sorry for the late response @xmatthias 
```
Request: POST https://openapi-v2.kucoin.com/api/v1/orders {'KC-API-KEY-VERSION': '2', 'KC-API-KEY': '', 'KC-API-TIMESTAMP': '', 'Content-Type': 'application/json', 'KC-API-PASSPHRASE': '', 'KC-API-SIGN': '', 'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate'} {"clientOid":"","side":"buy","symbol":"QRDO-USDT","type":"market","size":"20"}
Response: POST https://openapi-v2.kucoin.com/api/v1/orders 200 {'Date': 'Sat, 09 Oct 2021 18:11:09 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 'AWSALB=; Expires=Sat, 16 Oct 2021 18:11:09 GMT; Path=/, AWSALBCORS=; Expires=Sat, 16 Oct 2021 18:11:09 GMT; Path=/; SameSite=None; Secure, __cfruid=; path=/; domain=.kucoin.com; HttpOnly; Secure; SameSite=None', 'Strict-Transport-Security': 'max-age=9800; includeSubDomains; preload', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '', 'Content-Encoding': 'gzip'} {"code":"400500","msg":"Your located country/region is currently not supported for the trading of this token"}
{'id': None, 'clientOrderId': '0c7d1b73-6f1b-4390-8bc5-64e574ef1322', 'info': {}, 'timestamp': 1633803069346, 'datetime': '2021-10-09T18:11:09.346Z', 'lastTradeTimestamp': None, 'symbol': 'QRDO/USDT', 'type': 'market', 'side': 'buy', 'price': None, 'amount': 20.0, 'cost': None, 'average': None, 'filled': None, 'remaining': None, 'status': None, 'fee': None, 'trades': None}
```
I removed any potentially sensitive tokens.
Here it is:
```json
{"code":"400500","msg":"Your located country/region is currently not supported for the trading of this token"}
```

**Comment by xmatthias** [comment]
This should be working now with the very latest develop (as of #5706), thanks to the fix in CCXT.

Best comment below or reopen if you still encounter this with orders that are created with a version later than this.
The correct approach is obviously to have non-available tokens in your blacklist - otherwise it'll show errors in the log whenever you encounter a buy-signal for one of these tokens.
