### ISSUE TITLE
Not able to run Freqtrade container on heroku

### ISSUE THREAD

**Issue by devsmitra** [freqtrade/freqtrade#5625]
I'm trying to run freqtrade docker container on Heroku. I'm getting below error.

## Describe your environment

  * Operating system: ____
  * Python Version: 3.9  (`python -V`)
  * CCXT version: 1.56.86 (`pip freeze | grep ccxt`)
  * Freqtrade Version: lastest stable (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

I have added heroku.yml like below
```
build:
  docker:
    web: Dockerfile
```

Inside Dockerfile i have added
```
CMD "freqtrade trade --config /freqtrade/user_data/config.json --strategy EMACrossStrategy"
```

### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs
  ```
  // paste your log here
2021-09-26T12:10:42.279020+00:00 app[web.1]: Traceback (most recent call last):
2021-09-26T12:10:42.279036+00:00 app[web.1]: File "/home/ftuser/.local/bin/freqtrade", line 33, in <module>
2021-09-26T12:10:42.279138+00:00 app[web.1]: sys.exit(load_entry_point('freqtrade', 'console_scripts', 'freqtrade')())
2021-09-26T12:10:42.279148+00:00 app[web.1]: File "/home/ftuser/.local/bin/freqtrade", line 22, in importlib_load_entry_point
2021-09-26T12:10:42.279232+00:00 app[web.1]: for entry_point in distribution(dist_name).entry_points
2021-09-26T12:10:42.279242+00:00 app[web.1]: File "/usr/local/lib/python3.9/importlib/metadata.py", line 524, in distribution
2021-09-26T12:10:42.279471+00:00 app[web.1]: return Distribution.from_name(distribution_name)
2021-09-26T12:10:42.279480+00:00 app[web.1]: File "/usr/local/lib/python3.9/importlib/metadata.py", line 187, in from_name
2021-09-26T12:10:42.279617+00:00 app[web.1]: raise PackageNotFoundError(name)
2021-09-26T12:10:42.279636+00:00 app[web.1]: importlib.metadata.PackageNotFoundError: freqtrade
2021-09-26T12:10:42.412187+00:00 heroku[web.1]: Process exited with status 1
2021-09-26T12:10:42.584748+00:00 heroku[web.1]: State changed from starting to crashed
  ```

**Comment by xmatthias** [comment]
First of all - please fill out the issue template - other issues will be ignored.

The message simply states that freqtrade is not installed. 
Based on your description - i could close that issue, as there's nothing more to be said.

As you're trying to do something we're not really supporting (don't have documentation for) - you'll also have to provide us with what you're doing, what you did to actually install freqtrade on heroku.

You'll also see that you won't be able to run freqtrade on heroku (free) reliably, as it'll shutdown your container after half an hour of no inbound connections.

**Comment by xmatthias** [comment]
i never used heroku for freqtrade myself - but to me the error  sounds like heroku is not using the docker-container - or the docker-file itself is faulty.

Your best bet will be to try the docker-file offline (on your pc) to see if it contains errors.
I suspect your CMD might be wrong ... but without knowing the rest of the file, it's difficult to tell

**Comment by devsmitra** [comment]
@xmatthias I'm using this same image in my local, It's working but only on the Heroku container it gives 
```
importlib.metadata.PackageNotFoundError: freqtrade
```

**Comment by xmatthias** [comment]
the error simply says that freqtrade is not installed, or rather, it's installed but the files it expects to find are not there.

using the same command on the same image should give you the same error locally.
Maybe make sure that your Docker-image used is really the one you think is - and that it's also commited and pushed to heroku.

**Comment by samgermain** [comment]
I use these commands to get freqtrade running on an Ubuntu20 ec2, maybe the same would work using Ubuntu on Heroku

```
sudo apt-get update
sudo apt-get install python3.9 gcc
git clone https://github.com/freqtrade/freqtrade
cd ./freqtrade
./setup.sh -i
```

**Comment by xmatthias** [comment]
I don't think heroku will work without a docker image ... (it's not a VPS, but an application platform).

That said - i think the problematic part might be the command (if it is, it should however also show up locally).
The freqtrade image uses `freqtrade` as Entrypoint - which means a proper command must omit `freqtrade`.

The segment you shared above
```
CMD "freqtrade trade --config /freqtrade/user_data/config.json --strategy EMACrossStrategy"
```

would therefore become `freqtrade freqtrade trade <...>`. 

The [documentation](https://devcenter.heroku.com/articles/build-docker-images-heroku-yml#getting-started) also points out the possibility to add a command to the container, so maybe that can be a way to go about this.

**Comment by xmatthias** [comment]
A very simplistic / simplified example for this can be archived with the following combination:

``` Docker
FROM freqtradeorg/freqtrade:develop

ENV PYTHONUSERBASE="/home/ftuser/.local"

COPY user_data /freqtrade/user_data
# Reset Entrypoint due to a bug in heroku, always attaching `/bin/sh -c` to the command that's run
# This causes the end-command to be `freqtrade /bin/sh -c trade ...` - which is obviously wrong.
ENTRYPOINT /bin/sh
```



`heroku.yml`:

``` yml
setup:
  addons:
    - plan: heroku-postgresql
      as: FREQTRADE__DB_URL

build:
  docker:
    web: Dockerfile.heroku

run:
    web: freqtrade trade --config config.json --strategy SampleStrategy


```


The key is the exporting of `PYTHONUSERBASE` - as heroku changes the user the container runs as to a random u<number> string - so the pythonPath is no longer working as expected.

This obviously assumes that you have a (working) config available in `user_data/config.json` - as well as strategy etc. all stored (and commited!).

It should also be noted that freqtrade will not work on heroku free tier out of the box without problems - as heroku will terminate the container when no requests are inbound.
