### ISSUE TITLE
How to buy inside candle?

### ISSUE THREAD

**Issue by botzill** [freqtrade/freqtrade#5627]
I'm new to freqtrade and I noticed that does buy only when the candle is closed. If we have a 1h timeframe it will buy at the start of a new hour, is that possible to buy inside the candle it all the conditions from `populate_buy_trend` are met and `buy` is set to 1:

```
dataframe.loc[
            (
                    ...
            ),
            'buy'] = 1
``` 

Thanks.

**Comment by xmatthias** [comment]
Freqtrade works based on closed candles (all candles the strategy recieves are closed).

So assuming you only use data from the dataframe, then you'll have a new candle once every hour (assuming 1h timeframe).

This signal is then also active for the whole candle (the content of the candle will not change), so buys can happen intra-candle

* if no trade-slot is available at the start
* a trade is sold mid-candle (either due to stoploss, roi, ...)
* `ignore_buying_expired_candle_after` is not expired yet

**Comment by botzill** [comment]
Hi @xmatthias, thanks for the answer. Is there a way to buy inside candle at will, maybe I can configure this somehow and experiment with it on my own risk? 

thanks.

**Comment by xmatthias** [comment]
The strategy will receive only complete candles from freqtrade.
Using unfinished candles will lead to repainting - which you can neither backtest, nor can you recheck this in the future (you'll see buys without buy signals when looking at a chart afterwards).

You can use [real time data](https://www.freqtrade.io/en/stable/strategy-customization/#orderbookpair-maximum)  like orderbook through `dataprovider` - but if that'll work will depend on the strategy - and it automatically makes this part of the strategy non backtestable.

**Comment by botzill** [comment]
Yes we are aware that backtesting will not work on this, we are just doing some experiments now and we want to try smth. And yes we are using `self.dp.ticker` to get live data but the prob is that it only buy on new candle but we want to buy like instant, is that possible ?

**Comment by xmatthias** [comment]
Freqtrade will buy the moment the signal arrives.
When using dataframes, a signal flip will only be possible at a new candle. 

Using `dp.ticker` (or orderbook) will however make this possible, so freqtrade will (assuming default configuration) buy whenever the signal flips (also intra-candle).
there are settings that will prevent analysis of the same candle, but these are off by default.

**Comment by botzill** [comment]
Can you point to the config which will help me to achieve this? Or some
hints in the code where it does check for only new candle to do buy/sell
signals?

**Comment by xmatthias** [comment]
Relevant settings are `ignore_buying_expired_candle_after` - and `process_only_new_candles`.
Assuming the first isn't set, and the 2nd is set to `False` (which is the default) - nothing will prevent intra-candle buys assuming your strategy is "flipping" the signal (set buy=1) mid-candle.

**Comment by botzill** [comment]
I see, for me `ignore_buying_expired_candle_after` is not set and `process_only_new_candles=false` in config. Not that I also want to sell mid-candle, but no buy no sell is triggered. But when I log the last item from dataframe I see that `sell=1`.

**Comment by xmatthias** [comment]
a sell-signal is only relevant when you're in a  trade.

I'd strongly recommend to start with a simple strategy (to understand the basics) before moving to advanced things.
