### ISSUE TITLE
Limit Buy orders on a given timestamp

### ISSUE THREAD

**Issue by rajith-git** [freqtrade/freqtrade#5628]
As most of the coins behave in a similar way, sometime more that one pair gets the buy signal on the same dateframe (timestamp). It there a way to limit this?

For example if I have `"max_open_trades": 6` with no active trades and when the strategy finds a buy signal on the same dataframe for 5 pairs I want the bot only to buy 2. Is this possible?

**Comment by xmatthias** [comment]
I guess you can limit this in the strategy somehow (most likely by [rejecting further trades](https://www.freqtrade.io/en/stable/strategy-advanced/#trade-entry-buy-order-confirmation), but it's not something that's built into freqtrade. 
Freqtrade will follow the "command" of the strategy to buy, so if there's 6 signals, there'll be 6 buys (assuming 6 trade-slots are available)
