### ISSUE TITLE
How can we send telegram messages from strategy?

### ISSUE THREAD

**Issue by botzill** [freqtrade/freqtrade#5638]
I want to send an extra message to the telegram channel in the strategy, is that possible?

**Comment by xmatthias** [comment]
No it's not.
Freqtrade does not expose messaging capabilities to the strategy - and it's also not something i'm interrested in adding - as it'll end up with people being spammed by strategies (especially considering that many people run shared strategies "blindly" - sometimes without even really backtesting them).
