### ISSUE TITLE
Incorrect return value in Hyperopt Protection sample code

### ISSUE THREAD

**Issue by Obad94** [freqtrade/freqtrade#5639]
Hello Team,

I have been working with Hyperopt and found an incorrect return value in **Hyperopt Protection** sample code.
It should be **prot** instead of **protection**.
I'm also attaching a picture and documentation [link](https://www.freqtrade.io/en/stable/hyperopt/) for you reference.
![Capture](https://user-images.githubusercontent.com/29942077/135112053-361024fa-d887-42be-994e-2135cbe55390.PNG)

**Comment by xmatthias** [comment]
This has already been fixed in develop ([or latest documentation](https://www.freqtrade.io/en/latest/hyperopt/#optimizing-protections) - and will be moved to the "stable" part of the documentation with the next release.

Anyhow thanks for reporting :+1:
