### ISSUE TITLE
Feature Request: Include mongodb setup in Dockerfile or docker-compose.yaml

### ISSUE THREAD

**Issue by JustinHop** [freqtrade/freqtrade#564]
Hello, 

Setting up hyperopt is kind of a pain in the neck for what it is doing. Do you think you could either include the mongodb setup and config in the main Dockerfile, make another Dockerfile that has mongodb builtin, or make a docker-compose.yaml to crate a few containers, one of them being mongodb. Maybe use a system packaged instance of mongodb, started up like a normal service. I've been messing with it for a while and feel like I'm reinventing the wheel here.

Thanks

**Comment by gcarq** [comment]
I think a docker-compose.yaml would be the way to go. There you could have 3 services, one uses the official mongodb image and the other two are using the freqtrade image, but with a different entrypoint: `freqtrade/scripts/start-hyperopt-worker.py`and  `freqtrade hyperopt ...`.

This would also mean that the `start-hyperopt-worker.py` script needs some adjustments to make the ip address configurable (or as a workaround it would be also possible to just bind all containers to the same network).

**Comment by JustinHop** [comment]
You can do dns resolution based on container names in docker-compose, if that helps. 
In the docker-compose.yaml you could have something like 
db:
  image: mongo

and in the configuration for the database connection it would be able to resolve db to the ip of the mongo container. Maybe having the mongodb connection information passed as an environment variable, that could then also be set in the docker-compose.yaml for the freqtrade workers, would be an option.

**Comment by xmatthias** [comment]
Honestly, with @vertti removing the mongo dependency and moving to RayTune (see #510 for details) - i think we can close this issue.

Any issues feel free to reopen
