### ISSUE TITLE
Customize return message for custom_stoploss function 

### ISSUE THREAD

**Issue by MichaelMacca96** [freqtrade/freqtrade#5641]
## Describe your environment

  * Operating system: Windows 10
  * Freqtrade Version: 2021.8
  
## Your question

Hi Guys,

is it possible to customize the exit message from the custom_stoploss function as the custom_sell?
It would be nice to return or set information in the message displayed on freqtradeUI.

Here is an example of what I mean:
The first is a custom_sell message

![image](https://user-images.githubusercontent.com/91595678/135243250-ebdce31a-1b5a-4f05-994e-21dcca302acf.png)

thanks!

**Comment by xmatthias** [comment]
No, this is not possible.

`custom_stoploss` behaves like a regular trailing stoploss - even if your custom-stop set the new loss, it's not guaranteed to be the final exit reason (it might run into ROI, a sell signal, ...).

If you need custom sell reasons, please use `custom_sell`.
