### ISSUE TITLE
RSI divergence - high and low prices in dataframe

### ISSUE THREAD

**Issue by straj-granicy** [freqtrade/freqtrade#5643]
## Describe your environment

  * Operating system: Ubuntu 21.04
  * Python Version: 3.9.5. (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.7 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi.
I'm newbie in Freqtrade and trying to implement my first strategy.
So my goal is to implement RSI bullish and bearish divergence.
Pls adive me whether I can access high price in dataframe using dataframe ["high"] and low prices using dataframe ["low"].
Is it correct?
Sorry if this issue was discussed already. In this case I'd be grateful if you can give me a link.
BTW Is RSI divergence is implemented in Freqtrade? 
Does anyone has already has implemented this kind of strategy?

Thank you for all advices and assistance.

**Comment by xmatthias** [comment]
you'll have t columns on the datarame, 'open', 'high', 'low', 'close', 'volume' (and date, but that's usually not relevant).
Each column corresponds to one datapoint for closed candles on the candle chart.

Freqtrade itself does not offer divergence detection - but you can import many technical libraries which may have this (although i've never seen a reliable approach so far).


You may also want to look at our [discord server](https://discord.gg/p7nuUNVfP7) for this topic, maybe someone in the comunity has a shared (or is willing to share) an implementation of divergence detection.
