### ISSUE TITLE
Can't install freqtrade on raspberry, instalation error

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#5645]
* Operating system: Ubuntu/Ubuntu Server for raspberry pi 4
  * Python Version:3.9.5
  
  * Freqtrade Version: latest
  

**When i run "./setup.sh -i" I get this error:**

 Using cached tables-3.6.1.tar.gz (4.6 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/malina/Desktop/freqtrade/.env/bin/python3.9 -c 'import io, o                                                     s, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1ra9l1a3/table                                                     s_ff2b17b3cf3d41b4886d862501957feb/setup.py'"'"'; __file__='"'"'/tmp/pip-install                                                     -1ra9l1a3/tables_ff2b17b3cf3d41b4886d862501957feb/setup.py'"'"';f = getattr(toke                                                     nize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.String                                                     IO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"                                                     '\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"')                                                     )' egg_info --egg-base /tmp/pip-pip-egg-info-5bp8cyzh
         cwd: /tmp/pip-install-1ra9l1a3/tables_ff2b17b3cf3d41b4886d862501957feb/
    Complete output (12 lines):
    /tmp/H5close5c2pr5vw.c: In function ‘main’:
    /tmp/H5close5c2pr5vw.c:2:5: warning: implicit declaration of function ‘H5clo                                                     se’ [-Wimplicit-function-declaration]
        2 |     H5close();
          |     ^~~~~~~
    /usr/bin/ld: cannot find -lhdf5
    collect2: error: ld returned 1 exit status
    * Using Python 3.9.5 (default, May 11 2021, 08:20:37)
    * USE_PKGCONFIG: True
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2b/32/847ee3f521aae6                                                     a0be380d923a736162d698586f444df1ac24b98c65025c/tables-3.6.1.tar.gz#sha256=49a972                                                     b8a7c27a8a173aeb05f67acb45fe608b64cd8e9fa667c0962a60b71b49 (from https://pypi.or                                                     g/simple/tables/) (requires-python:>=3.5). Command errored out with exit status                                                      1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tables==3.6.1 (fr                                                     om versions: 2.3, 2.3.1, 2.4.0, 3.0.0, 3.1.0, 3.1.1, 3.2.0rc1, 3.2.0rc2, 3.2.0,                                                      3.2.1.1, 3.2.2, 3.2.3, 3.2.3.1, 3.3.0, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.5.1,                                                      3.5.2, 3.6.1)
ERROR: No matching distribution found for tables==3.6.1
Failed installing dependencies
![Screen](https://user-images.githubusercontent.com/91674891/135461125-2a01eeb5-f801-48c0-a658-591e2df93b2e.jpg)

**Comment by xmatthias** [comment]
Freqtrade only supports raspbian or docker when running on a raspberry pi.

Raspbian uses python 3.7 - for which piwheels provides pre-build sources. Running on another python version means you'll have to have all build-dependencies installed for dependencies. 
As this is a "non-standard" install (not using raspbian) - we'll not be supporting this approach - however it's technically possible by installing the build-dependencies necessary (basically - google the errors as they fail and install necessary dependencies).

If you're not familiar with this process however, it's best to use a supported method to run freqtrade on a raspberry.

**Comment by BOOKSHELF22** [comment]
> Freqtrade only supports raspbian or docker when running on a raspberry pi.
> 
> Raspbian uses python 3.7 - for which piwheels provides pre-build sources. Running on another python version means you'll have to have all build-dependencies installed for dependencies. As this is a "non-standard" install (not using raspbian) - we'll not be supporting this approach - however it's technically possible by installing the build-dependencies necessary (basically - google the errors as they fail and install necessary dependencies).
> 
> If you're not familiar with this process however, it's best to use a supported method to run freqtrade on a raspberry.

Oh, thanks, then i will try the raspbian, is the instalation the same? just ./setup.sh -i?
