### ISSUE TITLE
How to get market change for protections

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#5650]
Is there a method of **getting the market change on a special time range** so i can protect myself from **market crashes** ?
If no, that would be a nice feture for "protections" function, or even to transfer all coins in USDT and wait while market is crashing

**Comment by xmatthias** [comment]
Please get used to fill out the issue template (also for questions).
As mentioned there - issues without it filled out will be closed without further question (especially if it's the same people over and over again).

Protections work based on previous trades, not on random data.
You're free to implement protections in your strategy.
Usually, that's done via a Informative pair against BTC/USDT (or something similar) - but it's up to the user/strategy to determine the right parameters for this.

Having this as protection would be highly limiting (you'd only get the settings others decided are useful) - so this is not something we'll consider for protections as it can easily be implemented in the strategy.
