### ISSUE TITLE
docker-compose ports not exposing after updating to freqtrade-2021.9

### ISSUE THREAD

**Issue by devsmitra** [freqtrade/freqtrade#5654]
## Describe your environment

  * Operating system: __Macos__
  * Python Version: __3.9.7___ (`python -V`)
  * CCXT version: __1.55.28___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __2021.9__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the problem:

I have updated freqtrade stable to the latest(2021.9) and using docker-compose to run. I have exposed port 8080 but not able to access it from the browser.

I followed the same steps provided here https://www.freqtrade.io/en/stable/docker_quickstart

### docker-compose.yml
```
---
version: "3"
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    ports:
      - "8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
```

### Relevant code exceptions or logs

  ```
freqtrade    | 2021-10-03 06:37:25,995 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.9', state='RUNNING'
freqtrade    | 2021-10-03 06:38:26,010 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.9', state='RUNNING'
freqtrade    | 2021-10-03 06:39:26,021 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.9', state='RUNNING'
freqtrade    | 2021-10-03 06:40:26,027 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.9', state='RUNNING'
freqtrade    | 2021-10-03 06:41:26,039 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.9', state='RUNNING'
freqtrade    | 2021-10-03 06:42:26,044 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.9', state='RUNNING'
  ```
###  Browse
<img width="1215" alt="Screenshot 2021-10-03 at 12 14 10 PM" src="https://user-images.githubusercontent.com/31248807/135743176-eae12ac9-a0d4-4d87-8d1f-1a17aca7a333.png">
r

**Comment by xmatthias** [comment]
What's your config look like (specifically the `api_server` section)?

Simply exposing the port will not help if you're not also enabling the api-server - AND have it listen on 0.0.0.0 (which the logs don't indicate).

**Comment by devsmitra** [comment]
Thanks, @xmatthias 
 I have updated it to 0.0.0.0 it started working. I was not aware of that 

Before
```
"api_server": {
        "enabled": true,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        ...
    },
  ```
  
After
  ```
  "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
       ...
    },
   ```

**Comment by xmatthias** [comment]
It's part of the [rest api docs](https://www.freqtrade.io/en/stable/rest-api/#configuration-with-docker) ... 
will have a look if we can link the two ...

**Comment by devsmitra** [comment]
Thanks, @xmatthias  
I Will also have a look

Closing this issue.
