### ISSUE TITLE
Can deep reinforcement learning algorithms or neural networks be used in your code? 

### ISSUE THREAD

**Issue by Mahdiehdn** [freqtrade/freqtrade#5656]
Hi, I'm glad to see your code. Thank you for sharing the code.
There are several articles on the use of machine learning methods in the field of cryptocurrency trading.
Have you used the machine learning algorithm and it is possible that neural network or deep reinforcement learning will replace it?

**Comment by xmatthias** [comment]
You should  take the time to read the [documentation](https://freqtrade.io).

There's nothing preventing you from using machine learning in your strategy - and as far as i know, it's also been done - but most likely, that code is not available.
Freqtrade provides the framework to test and run strategies - so usage of either of these techniques would have to happen in your strategy.

Freqtrade uses hyperparameter tuning (also a form of machine learning) to improve strategies.
