### ISSUE TITLE
somerandomnumber

### ISSUE THREAD

**Issue by USNeo** [freqtrade/freqtrade#5657]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*

**Comment by xmatthias** [comment]
Without description (not even a meaningful header) - there's nothing we can do for you.
