### ISSUE TITLE
Hyperopt documentation

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#566]
## describe your environment:
python3.6
Branch develop 
last commit: ebe1d3647f2547243b5a064775d82f0833ca60a6
## Describe the problem:
The documentation for [hyperopt](https://github.com/gcarq/freqtrade/blob/develop/docs/hyperopt.md) seems outdated.
It mentiones changing / adding the hyeropt spaces in the strategy file - however the links to the related code in the test-strategy don't point to the correct lines, which seem to have been refactored / removed from the test-strategy in commit [30abebf](https://github.com/gcarq/freqtrade/commit/30abebfe65badbd5083f0d0b7b07a082afad7667).

Also, the `spaces` seems to have been moved into the hyperopt file (https://github.com/gcarq/freqtrade/blob/develop/freqtrade/optimize/hyperopt.py) - which i think should not be changed as part of user optimization of a strategy. If i understood hyperopt correctly, then spaces should be adjusted to match the lines used in your strategy - which is impossible without modifying a core / commited file.

The code in hyperopt does not seem to load spaces from any other user-data file other than hyperopt_optimize_conf - which is only the configuration and does not contain spaces or other hyperopt modifieable parameters.

**Comment by MoonGem** [comment]
+1 Basically, having a ton of trouble getting hyperopt working with mongodb

**Comment by hashtagex** [comment]
+1 - also agree and having issues myself. Thanks for pointing this out.

**Comment by MoonGem** [comment]
I'd like to note, that well, I think hyperopt is nice but currently pickling a thread will never be supported as long as python lives.

I think there is a hyperopt bug somewhere with mongodb, but I'm falling back to a single thread now at this rate. Not much I can do about it.  

However, I think a template for the output I'd be getting here later tonight for the hyperopt results that somehow go in some strategy somewhere? What confuses me is the signaling > < and == >= stuff. As, my only real reference for that is almost nowhere but deep hidden in some history of the test_strategy that had some items removed lol

**Comment by vertti** [comment]
Hyperopt has not been actively developed for a long time (I think are back now though) and the whole "multitasking with MongoDB" is a horrible overkill solution I would like to just get rid of, as it adds unnecessary complexity to the bot. Unfortunately Hyperopt seems best by far when it comes to specifying the kind of search spaces we need.

**Comment by xmatthias** [comment]
I'm going to close this as #930 changes both the functioning of hyperopt, and also improves / corrects the documentation, thanks @vertti.
