### ISSUE TITLE
data exchanges shared

### ISSUE THREAD

**Issue by anakein** [freqtrade/freqtrade#5669]
in linux.
I want to share data/binance directory to 3 Raspberry.
Now i can sync data with rsync, but i want unique directory and share/mount with sshfs, but i want each RP3 with own user directory and only data/binance shared. 

Only 1 RP3 download data and the rest use this data.

is this possible?

thanks.

**Comment by xmatthias** [comment]
I guess it'll be possible by mounting a remote-directory from one raspberry to the other.
You should be able to define the correct mount-point yourself, so you can mount directories into `user_data/data/` as you wish.
Not sure how performance will be - but you'll see that soon enough i guess..

In general, this is however not something freqtrade (as application/tool) can assist you with (as long as it's a directory with the right content, freqtrade will not care) - and we'll not be able to provide you additional support in this - as we try to focus on freqtrade functionality - so support in other areas should be sought from the respective expert comunities.

You're best off either searching the internet for this (should be easy enough to find, mounting directories is something quite standard in the linux world) - or maybe try asking on the [discord server](https://discord.gg/p7nuUNVfP7) if someone did something similar in the past.
