### ISSUE TITLE
Cooldown period after buying

### ISSUE THREAD

**Issue by mejiafabiandj** [freqtrade/freqtrade#5672]
Hello All, I wonder if it is possible to set any kind of cooldown period to avoid buying several coins at the "same" time.

As you all know, in some cases general trends on BTC affect major alts; it means buy signals can occur almost at the same time in several pairs, which causes multiple buys (till max_oppen_tades limit is reached).

I would like to set a custom cooldown period to avoid entering into a new buy for a few minutes if the Bot just bought any alt. _Similar to sell cooldown but applying for all other pairs._

Any suggestions? Thanks in advance

**Comment by xmatthias** [comment]
Freqtrade itself will not lock after buys - but it should be possible pretty easily from within the strategy.

best look at [trade entry confirmation](https://www.freqtrade.io/en/stable/strategy-advanced/#trade-entry-buy-order-confirmation).

you can reject buys there based on whatever logic you can come up with.
