### ISSUE TITLE
Processus died - 

### ISSUE THREAD

**Issue by stakepoolplace** [freqtrade/freqtrade#5681]
## Describe your environment

  * Operating system: Debian 10
  * Python Version: Python 2.7.16
  * CCXT version: ccxt==1.55.28
  * Freqtrade Version: freqtrade 2021.8
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

The processus of freqtrade die sometimes, and it happens the most part of time just before opening a trade.

### Steps to reproduce:

  1. Start it with Binance or Kraken
  2. Wait about 1 hour
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Oct  7 01:19:55  freqtrade[15426]: 2021-10-07 01:19:55,805 - freqtrade.commands.trade_commands - ERROR - 'ask_last_balance'
Oct  7 01:19:55  freqtrade[15426]: 2021-10-07 01:19:55,806 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Oct  7 01:19:55  freqtrade[15426]: Traceback (most recent call last):
Oct  7 01:19:55  freqtrade[15426]:   File "/home/debian/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
Oct  7 01:19:55  freqtrade[15426]:     worker.run()
Oct  7 01:19:55  freqtrade[15426]:   File "/home/debian/freqtrade/freqtrade/worker.py", line 74, in run
Oct  7 01:19:55  freqtrade[15426]:     state = self._worker(old_state=state)
Oct  7 01:19:55  freqtrade[15426]:   File "/home/debian/freqtrade/freqtrade/worker.py", line 111, in _worker
Oct  7 01:19:55  freqtrade[15426]:     self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
Oct  7 01:19:55  freqtrade[15426]:   File "/home/debian/freqtrade/freqtrade/worker.py", line 132, in _throttle
Oct  7 01:19:55  freqtrade[15426]:     result = func(*args, **kwargs)
Oct  7 01:19:55  freqtrade[15426]:   File "/home/debian/freqtrade/freqtrade/worker.py", line 145, in _process_running
Oct  7 01:19:55  freqtrade[15426]:     self.freqtrade.process()
Oct  7 01:19:55  freqtrade[15426]:   File "/home/debian/freqtrade/freqtrade/freqtradebot.py", line 183, in process
Oct  7 01:19:55  freqtrade[15426]:     self.enter_positions()
Oct  7 01:19:55  freqtrade[15426]:   File "/home/debian/freqtrade/freqtrade/freqtradebot.py", line 383, in enter_positions
Oct  7 01:19:55  freqtrade[15426]:     trades_created += self.create_trade(pair)
Oct  7 01:19:55  freqtrade[15426]:   File "/home/debian/freqtrade/freqtrade/freqtradebot.py", line 440, in create_trade
Oct  7 01:19:55  freqtrade[15426]:     return self.execute_entry(pair, stake_amount, buy_tag=buy_tag)
Oct  7 01:19:55  freqtrade[15426]:   File "/home/debian/freqtrade/freqtrade/freqtradebot.py", line 482, in execute_entry
Oct  7 01:19:55  freqtrade[15426]:     proposed_buy_rate = self.exchange.get_rate(pair, refresh=True, side="buy")
Oct  7 01:19:55  freqtrade[15426]:   File "/home/debian/freqtrade/freqtrade/exchange/exchange.py", line 1044, in get_rate
Oct  7 01:19:55  freqtrade[15426]:     balance = conf_strategy['ask_last_balance']
Oct  7 01:19:55  freqtrade[15426]: KeyError: 'ask_last_balance'

**Comment by xmatthias** [comment]
First of all, i'd recommend using the [orderbook ](https://www.freqtrade.io/en/stable/configuration/#buy-price-with-orderbook-enabled) for prices. It's a "cheaper" (from a rate-limit perspective) call than the tickers call you're using (when orderbook is disabled).

It then also seems that you removed the `ask_last_balance` key from your configuration - which is causing this.
As such, it's a misconfiguration - it should however not crash the bot.

**Comment by xmatthias** [comment]
Closed by 29863ad2bf7d364e0bc17dc5c3506e24f20b31b4
