### ISSUE TITLE
How to use the latest data?

### ISSUE THREAD

**Issue by huyphung1** [freqtrade/freqtrade#5687]
I'm using a strategy that uses timeframe 4h. So if lastest completed candle is 8h00 so from 8h00 to 11h59 the dataframe passed to populate_buy_trend is the old one. 
If it's 10h00, I want to use the incompleted candle from 8h00 to 10h00.
So please tell me how to config that or how to change the code.

thx for your Patience

**Comment by xmatthias** [comment]
Freqtrade will only make complete candles available to strategies.
using incomplete candles will lead to repainting, and as such, to non-deterministic strategies.


You can use the [dataprovider](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-dataprovider) to get current data (orderbook, tickers) - which will however not work in backtesting.

I've also clarified this in the FAQ now (basically with the same words than above).
