### ISSUE TITLE
Support multiple timeframes in a single backtesting run

### ISSUE THREAD

**Issue by naderelshehabi** [freqtrade/freqtrade#5688]
## Describe the enhancement

Backtesting multiple strategies in the same run (using the --strategy-list arg) at the moment supports only one timeframe. Perhaps it's worth it to allow multiple timeframes across strategies, and even for the same strategy would be very helpful.

Allowing this, and potentially showing the summary table for how various strategies performed (mentioning their timeframes), and how the same strategy across multiple time frames stack up against each others.

**Comment by xmatthias** [comment]
`--strategy-list` is still there for one reason - to allow loading data once and then running it across all strategies in a fast manner.
It's been proposed multiple times in the past to remove support for `--strategy-list` completely - and this "load data once" is the only reason it's still in there.

supporting multiple timeframes would void this feature and make the whole process very slow - so we could also remove support for this completely.

It'd also (probably) complicate the code by quite some (to keep it fast when possible) - so i don't see this as an enhancement worthwile of pursuing, but rather as a downgrade of an existing feature.

**Comment by naderelshehabi** [comment]
I understand this feature might not be helpful in rapid iterative development of a single strategy. However, it serves a different purpose.

From a user perspective I found that very helpful when I was comparing multiple strategies at the same time. Having all results in one file, and the summary table at the very end was very informative, and gives a different perspective to how:
- Multiple strategies comparison when all other testing parameters are fixed -like time range, pairs lists, protections, etc.
- How a single strategy perform in different timeframes

It adds another dimension to the backtesting process. I understand speed might be an issue, but computing power is not lacking. It's an understandable tradeoff. It took my PC -an average one- about a couple of hours comparing 10 strategies, 5m timeframe across 6 months. For the purpose I was using it for, that wasn't bad. It's not something I'd do everyday.

I agree with the code complexity, and understand if this feature wouldn't be a priority for development. Thanks for the reply though.

Cheers!

**Comment by xmatthias** [comment]
Feel free to contribute this feature if you think it's a must (if it's only a few lines of clean code, doesn't break existing behaviour, and is well tested). 

Please also take care to not keep the data in memory (and to not reload the same data again and again, so you'll need to intelligently sort strategies).

If it's however a 200 line change, adding a lot of complexity, please understand that we'll not be able to accept it.

Also, maybe look at #4401 - and ensure it'll not block development of that - as THAT is a feature i think will really be useful - which for this one - i strongly doubt, as it'll onlyl support the "phishing for random strategies" approach - not a proper development or selection of strategies.
