### ISSUE TITLE
Able to have adjustable dynamic stakes with a tiered volume pairlist?

### ISSUE THREAD

**Issue by stigmaknight123** [freqtrade/freqtrade#5690]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

Able to define dynamic stakes for ranges of the volume pairlist. Say I have 100,000 USD for the bot. I use 60 top volume pairlist. I want the top 10 volume pair to be able to use 100% of the dynamic stake (max count trade of 5) and be able to adjust the percentage of the dynamic staking in ranges doing down the list. Say 20 - 40 uses 50% of the dynamic stake and 40 - 60 uses 20%. 

Using large amounts of money have greater slippage and this helps mitigate the slippage problem.

**Comment by xmatthias** [comment]
Freqtrade supports [dynamic stakes](https://www.freqtrade.io/en/stable/strategy-advanced/#stake-size-management) in the form of a callback, where the strategy defines the trade size.

In combination with other methods available (To get the current pairlist), you'll be able to compile this pretty easily.
Sure, it'll require some coding and thinking in your strategy - but it allows for full flexibility (what you're asking would only fit your particular usecase, and probably not the one for most other users, which would want completely different rules, which cannot be satisfied by a "setting" option).

**Comment by stigmaknight123** [comment]
Thanks man. I am not sure if I can code it myself but I'll try, and also ask some other community members if they see merit in it. This function would be useful no matter how much stake size or initial principal you have since you can then open the volume pairlist range even wider.
