### ISSUE TITLE
[Kucoin] {"code":"429000","msg":"Too Many Requests"}. Able to ignore this error and prevent DDOS protection?

### ISSUE THREAD

**Issue by stigmaknight123** [freqtrade/freqtrade#5700]
## Describe your environment

  * Operating system: Canonical Ubuntu
  * Python Version: 
  * CCXT version: 1.56.86
  * Freqtrade Version: 
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

{"code":"429000","msg":"Too Many Requests"} error triggering DDOS protection delay. 

### Steps to reproduce:
Randomly effect pairs on Kucoin

### Observed Results:

DDOS protection triggering when it doesn't need to which may cause unintended and financially ruinous behavior in the bot. 

Admin on telegram says we can retry the request instantly without fear of DDOS protection triggering. 

![image](https://user-images.githubusercontent.com/15849763/136735376-37c1bcb2-d49a-4ca5-b314-1d4a1f2a9eed.png)

### Relevant code exceptions or logs

freqtrade    | 2021-10-11 04:55:04,274 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "kucoin GET https://openapi-v2.kucoin.com/api/v1/market/candles?symbol=DYDX-USDT&type=5min&startAt=1633778101&endAt=1633928101 429 Too Many Requests {"code":"429000","msg":"Too Many Requests"}"
freqtrade    | 2021-10-11 04:55:04,275 - freqtrade.exchange.common - WARNING - retrying _async_get_candle_history() still for 4 times
freqtrade    | 2021-10-11 04:55:04,275 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 1

**Comment by xmatthias** [comment]
freqtrade applies a "retry" mechanism (including incremental backoff) - so as long as it won't happen 4 times in a row, you should be fine (although it'll slow you down some).

What's your rateLimit settings for the bot look like?

**Comment by stigmaknight123** [comment]
I have a rate limit of 100 for 45 volume pairlist.

**Comment by xmatthias** [comment]
ccxt recommends a ratelimit of 334 - which seems VERY specific - so is probably the correct value.

We've recently moved to using the ccxt defaults for ratelimits - while it may be slower in some instances - it will also be safer (and also faster in some instances) - so i'd probably recommend the same (you can do this by removing the "rateLimit" key from the config).

**Comment by b-zig** [comment]
I tried increasing API Retry count in common.py and rebuilding to remediate this to none avail. Does anyone have any other recommendations? Doesn't look like my local docker build worked, as it still shows 4 retries in the logs. 

-----freqtrade/exchange/common.py
API_RETRY_COUNT = 8
API_FETCH_ORDER_RETRY_COUNT = 5

**Comment by wizrds** [comment]
> ccxt recommends a ratelimit of 334 - which seems VERY specific - so is probably the correct value.
> 
> We've recently moved to using the ccxt defaults for ratelimits - while it may be slower in some instances - it will also be safer (and also faster in some instances) - so i'd probably recommend the same (you can do this by removing the "rateLimit" key from the config).

Several users have tried changing the rate limit to as high as 1000, with no fixes. A Kucoin admin admitted they are currently throttling that public endpoint for a while they work on optimization. However it can be retried as many times as you want, with no fear of being locked out.

**Comment by xmatthias** [comment]
if it's a generic API problem - then i'd not rely on the responses anyway - as it can be rejected (error above) - or potentially can also return false results.

Updating the Retry-count will make your bots a LOT slower (it's incremental backoff - waiting for seconds between each call) - so i can only clearly  clearly advise against that.

it's better to not get the new candle in this iteration, but instead get it the "next round" - at least giving other pairs a try.

**Comment by xmatthias** [comment]
> A Kucoin admin admitted they are currently throttling that public endpoint for a while they work on optimization

I'm happy to look into this issue if kucoin is officially stating this (put it on their API documentation page). Otherwise, i'll treat this as rumor - and a kucoin problem they have to try and solve.

**Comment by edthepurple** [comment]
I'm still getting the 421 error, and they said this to me:
![image](https://user-images.githubusercontent.com/37901886/138390640-1a4a7484-8576-4f11-842d-f10e3e747c2d.jpeg)

**Comment by abhi1010** [comment]
I had the same problem and asked them about it. I got the same response from Aaron (supposedly their official API contact).
I told him that I was probably trying to access a lot of market data (due to higher number of pairs) but got this response in return. Just in case, it is useful, I will add it here. Only applies to Kucoin. 

```
WEBSOCKET
Number of Connections
Number of connections per user ID: ≤ 50

Connection Times
Connection Limit: 30 per minute

Number of Uplink Messages
Message limit sent to the server: 100 per 10 seconds

Topic Subscription Limit
Maximum number of batch subscriptions at a time: 100 topics

Subscription limit for each connection: 300 topics
You can use multiple sub-accounts and you won’t encounter this situation. This is public market data
---------------------------------
In fact, you can also use multiple sub-accounts to call the api/v1/market/ candles endpoint
```

**Comment by edthepurple** [comment]
How do we do this?
![image](https://user-images.githubusercontent.com/37901886/139566771-44a88d3c-21ca-4ee3-b710-71fe4ef915f5.png)

**Comment by xmatthias** [comment]
As mentioned above, best ask support to document it officially in their documentation.

**Comment by arvandiii** [comment]
I am getting this error too. This is my config:

`"ccxt_config": {
            "enableRateLimit": true,
            "rateLimit": 6800
        },
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 6800
        },`

`"pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 10,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 5800
        }
    ],`

What else should I do? Is refresh_period related?

**Comment by b-zig** [comment]
> 
> 
> I am getting this error too. This is my config:
> 
> `"ccxt_config": { "enableRateLimit": true, "rateLimit": 6800 }, "ccxt_async_config": { "enableRateLimit": true, "rateLimit": 6800 },`
> 
> `"pairlists": [ { "method": "VolumePairList", "number_assets": 10, "sort_key": "quoteVolume", "min_value": 0, "refresh_period": 5800 } ],`
> 
> What else should I do? Is refresh_period related?

there's nothing to be done on the freqtrade side of the house. The issue is on Kucoin rate limiting the API endpoint for candle data.

**Comment by arvandiii** [comment]
Is it possible to get data from Binance and do the trades in Kocoin?

**Comment by xmatthias** [comment]
> Is it possible to get data from Binance and do the trades in Kocoin?

no. 
As mentioned above, best pressure kucoin support to officially stand by the fact that they got a problem and add it to their API documentation.

**Comment by abhi1010** [comment]
@xmatthias  meanwhile, can you provide a simple guideline on what needs to change and where? That might be very helpful

**Comment by xmatthias** [comment]
> @xmatthias meanwhile, can you provide a simple guideline on what needs to change and where? That might be very helpful

I've not looked into this - and i won't - as all provided information is inofficial.
the official information is in their API documentation, which does NOT mention this error code at all.

**Comment by b-zig** [comment]
> 
> 
> @xmatthias meanwhile, can you provide a simple guideline on what needs to change and where? That might be very helpful

take a look at https://github.com/frequentcat/kucoin-proxy
It's not done yet, but there's potential to possibly use a websocket for candle data through this.

**Comment by abhi1010** [comment]
FWIW, kucoin has mentioned this issue here:  https://docs.kucoin.com/#request-rate-limit
The only difference is - they call it `429` instead of `429000`:

> When a rate limit is exceeded, a status of 429 will be returned.

Even `klines`, their suggested solution, is not without pitfalls:

> Klines data may be incomplete. No data is published for intervals where there are no ticks.
> Klines should not be polled frequently. If you need real-time information, use the trade and book endpoints along with the websocket feed.

But I think if they are going to release a high-throughput API this week then might be worthwhile to just wait for that.

**Comment by xmatthias** [comment]
> FWIW, kucoin has mentioned this issue here: https://docs.kucoin.com/#request-rate-limit
> The only difference is - they call it `429` instead of `429000`:

This is incorrect. the "real" 429 exception has a different meaning - and retrying immediately will get you blocked.
To quote from that same page:
> Once the rate limit is exceeded, the system will restrict your use of your IP or account for 10s.

I think i've mentioned it before - i see this problem as overstated, and is blown up by people looking at it  (and discussing / suggesting on it) who don't understand the real impact.
in my tests, freqtrade's retrys were successful with the first retry - so there will be only a minimal delay. It's anoying to have it in the logs - but will not have a real impact on trading.
