### ISSUE TITLE
is there a buy stop limit feature to trigger the buy order only when some price is reached?

### ISSUE THREAD

**Issue by GluTbl** [freqtrade/freqtrade#5712]
## Describe your environment

  * Operating system:  Ubuntu 20.04
  * Python Version: Python 3.7.5
  * CCXT version: 1.53.72
  * Freqtrade Version:freqtrade 2021.7

**Comment by xmatthias** [comment]
Freqtrade does support market or limit orders for trade entries.

That said, you should be able to use some combination of [enter confirmation](https://www.freqtrade.io/en/stable/strategy-advanced/#trade-entry-buy-order-confirmation) and [custom order pricing](https://www.freqtrade.io/en/stable/strategy-advanced/#custom-order-price-rules) to prevent a buy signal from buying until your desired price is reached.

It's however up to the strategy (speak, the user) to come up with a solution for this (it's also something you can't really backtest ...).
