### ISSUE TITLE
Bitcoin  Algorithm

### ISSUE THREAD

**Issue by ctyrihan2434** [freqtrade/freqtrade#5715]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Without any more detail, there is nothing we can do for you to help.

If you're looking for strategies, then please join the [discord server](https://discord.gg/p7nuUNVfP7), where strategies (and questions related to strategies) are best suited.
