### ISSUE TITLE
error Mysql and RPC

### ISSUE THREAD

**Issue by anakein** [freqtrade/freqtrade#5719]
Hello;

 * Operating system: ____Raspian
  * Python Version: _____ 3.7.3
  * CCXT version: _____ 1.55.28
  * Freqtrade Version: ____ 2021.8
  External MYSQL
  freqtrade trade -c config.json -s Strategy001 --db-url mysql+pymysql://user:password@192.168.1.100:3306/fbot

At first I thought the problem was freqUI, but I tried the frogtrade9000 script and the same thing happens.

When I use freqtrade with mysql database, the rpc does not work correctly, it does not update data to freqUI, the bot seems to work correctly, but not the transfer of information through the RPC.

I have not caught any errors in mysql either.

The failure occurs in both LIVE and DRY-RUN.

If I exit the bot and initialize it again, the data is updated with FreqUI. But I do not think that the error is due to FreqUI, because it does not work for me in other applications that retrieve the data by RPC

**Comment by xmatthias** [comment]
is thee "anything" in the logs (anything with warning or higher) that might point to an issue?
otherwise this will be very difficult to investigate.

Also, what about telegram, does telegram report correctly?

**Comment by anakein** [comment]
Hi;
Looking in telegram, dont work too. All RPC is out when use mysql., bot work fine, don´t report errors, mysql work fine too and save data, but don´t update trades and in few time dont update candles too in RPC systems (FreqUI, Frogtrade9000, Telegram)

**Comment by xmatthias** [comment]
i think i'm onto it ... but a fix might need "a bit" more time :laughing:
