### ISSUE TITLE
Fails with error on downloading histrorical data from Binance

### ISSUE THREAD

**Issue by T-i-m-m** [freqtrade/freqtrade#5720]
## Describe your environment

  * Operating system: ____Raspbian
  * Python Version: _____ 3.9.2
  * CCXT version: _____ 1.57.38
  * Freqtrade Version: ____ freqtrade develop-482f4418c
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Unable to download Binance (international) historical data with sample Binance file.
Bot quits with error.
This happens with any token, timeframe and timerange tried.

### Steps to reproduce:

  1. freqtrade download-data -c config_binance.example.json --timerange 20210901- -t 1m 5m 15m 30m 1h 6h
  
### Observed Results:

  * What happened?
  Aborts with error message, no data is downloaded.
  * What did you expect to happen?
  Historical data to be downloaded. Works successfully with other exchanges

### Relevant code exceptions or logs

Example (any token and timeframe gives equivalent error):
  ```
freqtrade.data.history.history_utils - ERROR - Failed to download history data for pair: "DOGE/EUR", timeframe: 6h.
Traceback (most recent call last):
  File "/home/dietpi/cryptoBots/freqTrade/bot/freqtrade/data/history/history_utils.py", line 196, in _download_pair_history
    new_data = exchange.get_historic_ohlcv(pair=pair,
TypeError: get_historic_ohlcv() got an unexpected keyword argument 'is_new_pair'  
 ```

**Comment by xmatthias** [comment]
Best update to the latest develop version. 
I can't reporduce it there (this particular bug was present ONLY in that commit, and reverted the commit after).

**Comment by T-i-m-m** [comment]
Solved the problem. Thanks!
