### ISSUE TITLE
plot chat differances in time and candle

### ISSUE THREAD

**Issue by DBVG** [freqtrade/freqtrade#5723]
Hi i have been noticing this for quite a long time now that there is always a difference between plot chart generated from freqtrade then on exchange or trade views even when data is from the same place and also the time displayed on candle is different then the time i see on my exchange (binance)

## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  ** i am using latest Docker image and windows venv both and it works fine for its usage
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
the time is most likely a timezone issue - most exchanges use UTC in their charts (although sometimes you can change this).

The numbers themselfs will align if pair and timeframe is aligned (assuming the exchange reports the same values via their API - but if that were not the case, it'd not be a good exchange).
