### ISSUE TITLE
how to use session vwap?

### ISSUE THREAD

**Issue by Armando0z** [freqtrade/freqtrade#5728]
I´m working on latest docker version to this date ( freqtrade docker-dcefb3eb) 

I´m trying to use intraday vwap as indicator:

`dataframe['vwap'] = qtpylib.vwap(dataframe)`

But when I plot the dataframe to check the strategy, I realize the vwap line is being calculated  using the whole timerange (it's not reseting at the start of the day)

I don't know if I'm calling the vwap correctly, 
thanks in advance for your help!

**Comment by xmatthias** [comment]
qtpylib is not a freqtrade invention, but it's a vendored file (copied from qtpylib).

Regarding vwap usage - you should never ever use `qtpylib.vwap(dataframe)`, it's got a nasty lookahead bias in backtesting.

there's `qtpylib.rolling_vwap(dataframe)` - which is calculating vwap in a rolling way - so it avoids lookahead bias (looking into the future). 
it'll however not be "session" based (where it resets once per day) - as most indicators on exchanges/tradingview does. 

It also seems that pandas_ta has a "session" based vwap - but i've never used that for cryptos.

I'm however also not sure about the application of the "daily" reset to crypto markets - as this concept was developed for traditional markets where the reset means "market closed" - which does not really apply to crypto markets.

**Comment by xmatthias** [comment]
As this seems to be a common source of confusion - i've now removed the possibility to use VWAP with a warning pointing to `rolling_vwap`.

Potentially, this will break a few peoples strategies, but ...

**Comment by Armando0z** [comment]
Thanks a lot for your answer! I´ll the other options you mentioned.
