### ISSUE TITLE
Strategy line

### ISSUE THREAD

**Issue by zorann** [freqtrade/freqtrade#5730]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```
Why is line like (dataframe['close'].shift(1)-dataframe['open']shift(1))>0 not accepted in strategy.

**Comment by xmatthias** [comment]
This is way too little information to be able to help you.

From a syntax point of view - it's kindof OK on it's own, but it'll depend on how you use it if it's really ok, or produces a syntax error.

**Comment by zorann** [comment]
Hello,

thanks for your response. I solved the problem and now is working. I just
have problem connecting from pc inside the network. I use docker-compose
and i have 0.0.0.0:8080:8080 in docker-compose.yml and 0.0.0.0:8080 in
config json. Can you help me?

Best regards

V ned., 17. okt. 2021 14:59 je oseba Matthias ***@***.***>
napisala:

**Comment by xmatthias** [comment]
You should make sure to not use this configuration on the internet directly (not on a VPS or similar).

From your local network, you should be able to connect by using the IP address of your pc - however it'll not work from outside of your network.
