### ISSUE TITLE
Question:  Alternative sampling periods?

### ISSUE THREAD

**Issue by ppkantorski** [freqtrade/freqtrade#5735]
Is it possible to load alternative sampling periods, like 3h for instance?  I know it is simple enough to compute using Pandas from 1m data.  I've built my own bot as well over the years, very similar to freqtrade with multiple apis, backtesting, ML calibration, programable strategies, etc.. but a bit more simplistic in design.  I never knew something like this already existed 🥲, so I'm here to play around with it and figure out its caveats.  My best ML optimized trading strategy works on a 3h time frame with PSAR and a few other indicators that I derived from PSAR.  I wanted to play around with freqtrade and see if I could implement the same strategy.   Is there an easy way to load alternative sampling periods?

**Comment by xmatthias** [comment]
First of all - please get used to fill out the issue template, even if you think it's irrelevant.
Repeated issues without it will be closed without further comment.

Freqtrade can load all timeframes available on the exchange via [informative pairs](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-informative_pairs).

as 3h is usually not available on exchanges, you'll not get far via that way, so you'll have to rely on resampling.

For 3h candles, i'd however not go the 1m route - but the 1h route (that way you get more lookback out of your data).
with [technical](https://github.com/freqtrade/technical#usage) we do provide some pre-made tools for this - it's then up to research if pandas allows to easily resample to 3h times (i guess so, but never tried).

**Comment by ppkantorski** [comment]
alright sorry about that.
