### ISSUE TITLE
add custom markers to plot

### ISSUE THREAD

**Issue by GluTbl** [freqtrade/freqtrade#5745]
I want to mark some candle like that of buy or sell signall which is mark as red or grren triangle. is there any way to mark some candle which is marked in dataframe of  at "populate_indicators()".

**Comment by GluTbl** [comment]
So, there is no option other than editing the "freqtrade/plot/plotting.py"????

**Comment by xmatthias** [comment]
Please make sure to fill out the issue template next time.

Based on your question, i'm not sure what you're after.
buy/sell signals are shown in plots as triangles - so if you're not seeing them, then buy/sell columns are not correctly assigned.

**Comment by GluTbl** [comment]
> Please make sure to fill out the issue template next time.
> 
> Based on your question, i'm not sure what you're after. buy/sell signals are shown in plots as triangles - so if you're not seeing them, then buy/sell columns are not correctly assigned.

I see the buy / sell signal..... 
i want to add more, like that of buy or sell signal's traingle sign
[like this]-> marking the first candle crossing the lower of bollingerband etc.

**Comment by xmatthias** [comment]
in the main chart, i'd not know how to do this, as it's something very custom (and will most likely only work in very specific circumstances).

You can use boolean's and display them in a sub-plot (so they show up as "spikes up" - but i don't think that's precisely what youre after.

Please note:
We'll not be investing time in improving the plotting module at this point, as the future is in freqUI (which also allows plotting).

**Comment by GluTbl** [comment]
Okey... Thank You
i will modify "freqtrade/plot/plotting.py" to fullfill my condition.
i was asking to sure that i was not reinventing the wheel. :+1:
