### ISSUE TITLE
Expired discord links?

### ISSUE THREAD

**Issue by huytrvan** [freqtrade/freqtrade#5753]
Hi there, it seems that discord links expired.

After I clicked 'accept invite', either it says ``connecting`` and nothing happens or it would send a blank screen with ``No Text Channels``

Note: I could still join other channel just fine and this is my first time joining freqtrade channel.

Can you renew the invite link or am I missing something? Thanks!

**Comment by xmatthias** [comment]
Which link exactly did you use (where did you find it?)?

The invite shared in the documentations [discord channel](https://discord.gg/p7nuUNVfP7) is still a valid invitation link.

Please note: to view all channels in discord, you'll need to pass the verification bot (for spam protection), which will ask you a captcha you'll need to respond to.
Only after passing that you'll be able to see the full freqtrade server.

**Comment by huytrvan** [comment]
hmm strange, must be a discord bug, let me ask their support. This happens on both PC and mobile app.

https://user-images.githubusercontent.com/62534513/137724715-60e857d0-08a8-4883-9c04-25599ea0acff.MP4

**Comment by inforeincluder** [comment]
Wait there are no more comments???? This is annoying
