### ISSUE TITLE
force pair_whitelist even when VolumePairList is used

### ISSUE THREAD

**Issue by gorgitko** [freqtrade/freqtrade#5754]
Hello, would it be possible to use (force) `pair_whitelist` even when [VolumePairList](https://www.freqtrade.io/en/stable/plugins/#volume-pair-list) is used?

Currently:

> When used in the leading position of the chain of Pairlist Handlers, the `pair_whitelist` configuration setting is ignored.
> Instead, `VolumePairList` selects the top assets from all available markets with matching stake-currency on the exchange.

What I mean is: `VolumePairList` would do its job (select top N pairs), plus other filters could be applied then, resulting in a list of whitelisted pairs. And to this list, pairs from `pair_whitelist` would be appended. Or another parameter could be used for this forced whitelist, e.g. `pair_whitelist_forced`.

Thanks for looking into this!

**Comment by xmatthias** [comment]
This is currently not possible, but an approach for this has been outlined in #4493.

Your proposal would simply be a reduced version of that issue, without the possibility to add flexibility (adding/removing pairs via rpc methods).
If you think it should be done differently (other than outlined in #4493), best leave a comment in that issue.

**Comment by gorgitko** [comment]
I think that the simplified version would be enough for now, and also (probably) much easier to implement. But anyway I like the proposal given in #4493 :slightly_smiling_face:

**Comment by xmatthias** [comment]
It might be enough for your particular idea at this moment.
The moment you'll then see another "want this in my pairlist" coin and have to change the config, add that pair, ... - you'll not be satisfied.

so it might be easier to implement - but will only give you short-term gain. also,  having both will only lead to confusion (which one should i pick).

I'm also not sure what usecase you'd have for this - you either trust the Volume - or you pick pairs yourself.
i don't think doing one on top of the other will give you many benefits - as you'll then use a pre-selected list - where "high volume" pairs will skew your results (most likely to the negative, looking at "top-volume" pairs of late).

**Comment by gorgitko** [comment]
My idea was to whitelist pairs (symbols) which I think/believe might rise in the near future (like "on XX we are releasing this feature for our coin" etc.), but their current volume is not sufficiently high to pass the `VolumePairList` at the moment. So to catch a probable uptrend.

**Comment by xmatthias** [comment]
so you'd simply use a volumepairlist - followed by a staticpairlist which appends the "few new" pairs at the bottom?

**Comment by gorgitko** [comment]
Unfortunately, that's not allowed - I am getting this error:
```
freqtrade - ERROR - StaticPairList can only be used in the first position in the list of Pairlist Handlers.
```

**Comment by xmatthias** [comment]
it was a question if that's what you'd be after ... - not claiming it works at the moment ;)

**Comment by gorgitko** [comment]
Ahh, I see :sweat_smile: That would definitely solve this problem/enhancement.

**Comment by xmatthias** [comment]
will be available in develop (docker in ~20 minutes, once ci finishes).

**Comment by gorgitko** [comment]
Nice, thank you very much! :blush:
