### ISSUE TITLE
Support for custom entry-prices and exit-prices during backtesting.

### ISSUE THREAD

**Issue by GluTbl** [freqtrade/freqtrade#5755]
Custom order entry and exit price is good.
and i can set the trade price directly. 

This thing work only in "trade" mode. but not in "backtesting"

**Comment by xmatthias** [comment]
This is correct, and was an explicit decision at the time of implementing custom entry/exit pricing.

As backtesting always fills orders, we'll need to be very careful to only allow "sane" values (which is not necessarily the whole candle).
 
Obviously i can always buy at "candle low" during backtesting - but will that get filled realistically? probably not.  backtesting does not have the data necessary to simulate "unfilled" orders,  so we'll have to assume that everything that's between high/low of a candle will fill.

That's however not how reality will work (low might have already happened) - so allowing a (even remotely) realistic simulation of entry prices is not as easy as it sounds.

**Comment by GluTbl** [comment]
Okey. But the price decision for the backtesting should be decided in the Strategy.

My idea behind this changes is that, the stratagy creator can return the default price during the backtest, [ or maybe he can do something for backtesting].

The stratagy creator can know if it is "backtesting" or "trade" mode by using "self.dp" [DataProvider] and check if the exchange in DataProvider is None or not.[by calling `ticker()`.
So he can return the original candle's open value as entry price during the backtest mode or can use some logic to make the custom price. (Helpfull for making some strategy which feature stop buy limit.)

**Comment by GluTbl** [comment]
> This is correct, and was an explicit decision at the time of implementing custom entry/exit pricing.
> 
> As backtesting always fills orders, we'll need to be very careful to only allow "sane" values (which is not necessarily the whole candle).
> 
> Obviously i can always buy at "candle low" during backtesting - but will that get filled realistically? probably not. backtesting does not have the data necessary to simulate "unfilled" orders, so we'll have to assume that everything that's between high/low of a candle will fill.
> 
> That's however not how reality will work (low might have already happened) - so allowing a (even remotely) realistic simulation of entry prices is not as easy as it sounds.

You are right.
But in some stratagy which want to create stop limit buy order,[where the price is always higher than the candle's open], the result of backtest will always wrong. So let the price for backtest be decide inside the Strategy.

it will be great if the Strategy can know if the mode is "backtest" or "trade" . currently i call `self.dp.ticker()` to know if it is backtest or not.

**Comment by xmatthias** [comment]
The strategy can know the mode via `if self.dp.runmode.value in ('live', 'dry_run'):` (which will obviously be backtesting for backtesting).
it's part of the [documentation](https://www.freqtrade.io/en/stable/strategy-customization/#get_analyzed_dataframepair-timeframe) - but not explicitly listed as option - but used in multiple examples.
