### ISSUE TITLE
Run freqtrade in different timezone

### ISSUE THREAD

**Issue by SmartManoj** [freqtrade/freqtrade#5757]
Summary  of Similar issue  #217 
Adding a timezone param in config would be better

**Comment by xmatthias** [comment]
From a general perspective - please get used to fill out the issue template. 
It's there for a reason, not filling it out is showing disrespect to the people trying to answer your issues.

Also, please don't simply link to an issue that's 3 years old, but explain what you'd want (which telegram endpoints you think it would impact, ...).

**Comment by SmartManoj** [comment]
Used feature request template only.

Describe the enhancement - One shouldn't remove this line ?

**Comment by SmartManoj** [comment]
So the frequi reflects the userzone

**Comment by xmatthias** [comment]
with the provided information, there is nothing for me to help you with.

The timezone of the system freqtrade is running on does not matter (as long as the UTC time is correctly set).
For RPC methods, we're almost exclusively using relative identifies (`1 hour ago`, ...) - so timezones will not play a role there.

As such, i don't see a need for a timezone parameter, unless  you can describe in detail where you think that would be needed (please comment below in such a case).
