### ISSUE TITLE
Conflict in Edge positioning error checks 

### ISSUE THREAD

**Issue by adarkforce** [freqtrade/freqtrade#5758]
## Environment

  * Operating system: MacOS Catalina 10.15.7
  * Python Version: Python 3.9.4
  * CCXT version: ccxt==1.55.13
  * Freqtrade Version: freqtrade develop-7dba45d89
 

## Problem:

Hi guys. 

I wanted to try the edge positioning feature and in the console it shows the message: 'CRITICAL - max_open_trades should be -1 in config', but when i set the max open trades to -1 it says that you cannot have unlimited stake_amount and max_open_trades to unlimited.

I've checked the code and there is a validate_config_consistency function in edge_cli.py which checks for stake_amount and max_open trades to not be both unlimited. Also in the Edge constructor in edge_positioning.py there is a check for stake_amount and max_open_trades to be unlimited. 

### Steps to reproduce:

  1.  Running 'freqtrade edge' with max_open_trades = -1 and stake_amount = finite_number gives 'ERROR - `max_open_trades` and `stake_amount` cannot both be unlimited.'
  2. Running with stake_amount = 'unlimited' and max_open_trades = finite_number gives 'CRITICAL - max_open_trades should be -1 in config' but it completes the execution 
  3. Running with both unlimited gives 'ERROR - `max_open_trades` and `stake_amount` cannot both be unlimited.'

**Comment by xmatthias** [comment]
well it's intended this way - stake-amount cannot be unlimited when max-open-trades is unlimited, as then we'd have no reference to trade size.

For edge, please use a fixed stake_amount.
