### ISSUE TITLE
PR #5580 changed random hyperopt iterations to 5

### ISSUE THREAD

**Issue by SelfBiasedCode** [freqtrade/freqtrade#5760]
Just an oddity I noticed: Pull Request #5580 added support for custom Hyperopt estimators. In the first [commit ](https://github.com/freqtrade/freqtrade/pull/5580/commits/994c3c3a4c5f36c02d249f4c13466b284c4991af) it also changed the number of random iterations from 30 to 5 though, and there is no explanation given as to why. The documentation also still mention 30 iterations being the default. Was this intended?

**Comment by xmatthias** [comment]
nice catch ... it's not intended, but i sometimes change it to be able to test things quickly :laughing: this time, i added it to the commit :scream:
