### ISSUE TITLE
Manually adding already existed trades through telegram?

### ISSUE THREAD

**Issue by GluTbl** [freqtrade/freqtrade#5761]
## Describe 

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Manually adding already existed trades through telegram?

I use freqtrade to assist my trading through dry run mode.
i manually execute the trade to exchange after i got buy/sell signal frm freqtrade.

So, sometime i face problem,like the trade is executed succesfully in at exchange but the dry run mode did not executed.

It will be sove if i can manually filled/execute/add a trade forcefully through telegram at a specific price[if possible at specefic time]. i also want the same for exiting the trade.

I tried the `/forcebuy` and `/forcesell` . but i think the trade doesnot entry/exit immidiatly at specific price. Is there anyway?

This will also help to add pre existing trades in freqtrade without editing the database.

**Comment by xmatthias** [comment]
This is not possible - and is also not a usecase we're trying to support, as a successful trade entry requires quite some more information (other than price) than what you can provide via telegram.

You can use `/forcebuy` - obviously the numbers will be slightly off depending on the values your order fills.

A better (and supported) approach would be to use a "noaction" strategy (without buy/sell signals) in live-mode, and use `/forcebuy` to enter your live trades as well.
This will give you freqtrade's "tracking" ability - but potentially (if desired) also additional support, in automatically handling stoplosses / ROI sells without further interaction.

**Comment by GluTbl** [comment]
> This is not possible - and is also not a usecase we're trying to support, as a successful trade entry requires quite some more information (other than price) than what you can provide via telegram.
> 
> You can use `/forcebuy` - obviously the numbers will be slightly off depending on the values your order fills.
> 
> A better (and supported) approach would be to use a "noaction" strategy (without buy/sell signals) in live-mode, and use `/forcebuy` to enter your live trades as well. This will give you freqtrade's "tracking" ability - but potentially (if desired) also additional support, in automatically handling stoplosses / ROI sells without further interaction.

I think only the price was neccessory because the stack amount is constant...........
....
Okey if it is a problem..........

But what about force fill a trade open/exit by freqtrade via Telegram?

eg, send `/forcefill [some_trade_id]` from telegram and fill the order, for dry-runs?

**Comment by xmatthias** [comment]
The purpose of dry-runs is to try and simulate real market behaviour as much as possible, not to track your "non-freqtrade" trades.

Simulating this also includes taking volume (and current orderbook) into account. 
Circumventing this is not forseen, and will also not make sense, as it'll hinder and obfuscate proper dry-run results.

I understand you'd need this for your usecase, but freqtrade is not intended / designed for this.

As your stake-amount is always constant, best use freqtrade to handle your live-trades (via the above proposed method).
