### ISSUE TITLE
Do not ignore pairs in pair_whitelist even in VolumePairList.

### ISSUE THREAD

**Issue by Dat1606** [freqtrade/freqtrade#5764]
Do not ignore pairs in pair_whitelist even in VolumePairList.

Say you are using VolumePairList for filtering pairs but you got some exceptions. You still want to trade some specific pairs.

**Comment by xmatthias** [comment]
This has been added yesterday to the [staticpairlist](https://www.freqtrade.io/en/latest/plugins/#static-pair-list) - and is available in develop.

basically, you configure staticpairlist after volumepairlist to append a static list of pairs to the volumepairlist (if they don't exist already).
