### ISSUE TITLE
Questions about the bot.

### ISSUE THREAD

**Issue by morsine** [freqtrade/freqtrade#5765]
## Describe your environment

  * Operating system: Debian 11
  * Python Version: 3.9
  * Freqtrade Version: 2021.9
  
## Your question

Hello.! I have a few questions

When the bot buys a coin, it notifies me about it but it doesn't get picked up (when running balances command, it doesn't show up) and after a restart of the bot it gets picked up, is this normal or is this a bug?
Sometimes I also receive warnings that the buying procedure times out (probably due to rate limitations?)

After restarting the bot, it tells me to handle open trades manually but open trades still show up in the telegram bot and UI, will the bot handle selling automatically after restart or I should sell manually as the bot says?

I'm using KuCoin, and there are lots of warnings about me getting rate limited, I tried to increase and decrease the rate limit in configurations, from 10 to 1000 yet this still happens, what value do I need to set to avoid this happening?

**Comment by xmatthias** [comment]
Freqtrade notifies you of a buy - but that doesn't mean the order filled, so until it fills, /balances will not show this coin.
You can check for this using the `/status table` command - which will show a sign for open orders (* (buy) and ** ( sell)).

The timeout you're getting is probably an order timeout (your order was placed, but not filled). 

> After restarting the bot, it tells me to handle open trades manually but open trades still show up in the telegram bot and UI, will the bot handle selling automatically after restart or I should sell manually as the bot says?

this warning is shown in case you're not starting freqtrade back up (which freqtrade won't know when it's terminating). As long as you leave the database in place, it'll continue where it left of.

kucoin is currently experiencing API issues (#5700) - there's nothing you can do about that until thei fix their infrastructure.

**Comment by morsine** [comment]
> Freqtrade notifies you of a buy - but that doesn't mean the order filled, so until it fills, /balances will not show this coin. You can check for this using the `/status table` command - which will show a sign for open orders (* (buy) and ** ( sell)).
> 

The thing is, order is filled (can see it in my assets on kucoin) but the bot doesn't pick it up unless I restart it.

**Comment by xmatthias** [comment]
well without logs, there is little i can do to try and help you.

**Comment by morsine** [comment]
> well without logs, there is little i can do to try and help you.

Thank you so much for your help! It got solved on it's own and new orders are being picked up by the bot without the need of restarting it! I hope #5700 gets patched soon ^^

Thank you so much.
