### ISSUE TITLE
Strategy xx% profit a day

### ISSUE THREAD

**Issue by medilane1** [freqtrade/freqtrade#5767]
I want to implement a strategy that detects the xx% profit on the day.
There is already a discussion on the topic opened by fintaro123.

```
def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
    
    now_datetime = datetime.datetime.now()
    end_of_day = now_datetime.replace(hour=23, minute=59, second=59, microsecond=999999)

   if self.config['runmode'].value in ('live', 'dry_run'):
            trades = Trade.get_trades([Trade.pair == metadata['pair'],
                                       Trade.open_date > end_of_day - timedelta(days=1),
                                       Trade.is_open.is_(False),
                                       ]).order_by(Trade.close_date).all()

    curdayprofit = sum(trade.close_profit for trade in trades)

        dataframe.loc[
            (
              (dataframe['open'] > dataframe['close']) &
              (curdayprofit < 1)
            ),
            'buy'] = 1

        return dataframe
```

freqtrade does not launch with this code

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
First of all, please fill out the issue template! it's there for a reason, even if you think it doesn't concern you.

your indentation seems to be off (strongly) ... 
Fixing that, i don't see why it woulnd't work (although your `curdayprofit` check seems strange - as it's unrealistic to get 100% profits per day - so it'll simply always trigger).

as such, i'm not quite certain where you're seeing / encountering problems. 

In general, i'd say use the  [discord server](https://discord.gg/p7nuUNVfP7) for this type of support - as it'll require constant back and forth - and maybe someone in the community there already has something like this available.

**Comment by medilane1** [comment]
I corrected the indentation is it working
Thanks for your help ! :)

**Comment by xmatthias** [comment]
Great to hear :+1:
