### ISSUE TITLE
Error " unsupported operand type(s) for &: 'float' and 'float'" with multiple timeframes

### ISSUE THREAD

**Issue by malcomZ** [freqtrade/freqtrade#5768]
## Describe your environment

  * Operating system:  Debian 10.8
  * Python Version: Python 3.7.3
  * CCXT version: 1.49.30
  * Freqtrade Version: freqtrade develop-6c50157c
  
## Your question

Hello,

First of all, thank you in advance for your time.

I am trying to make a strategy with several timeframes, with sma, stoch and rsi indicators.
The desired timeframes are 15 min and 1 hour, the initial timeframe is 5min and the multipliers to get to the desired timeframes are *3 and *12.

During the execution, errors are present "Unable to analyze candle (OHLCV) data for pair ...: unsupported operand type(s) for &: 'float' and 'float'" and I can't find and solve the source of this problem.

In addition, once the errors are finished, the following message is displayed "freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair..."

Once again, thank you for your time and help

--------------------------------

```
# --- Do not remove these libs ---
from freqtrade.strategy.interface import IStrategy
from typing import Dict, List
from functools import reduce
from pandas import DataFrame
# --------------------------------
import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib
from technical.util import resample_to_interval, resampled_merge

class MultiTimeFrame(IStrategy):

    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi"
    minimal_roi = {
        "0":  0.0075
    }

    # Optimal stoploss designed for the strategy
    # This attribute will be overridden if the config file contains "stoploss"
    stoploss = -0.018

    # Optimal timeframe for the strategy
    timeframe = '5m'

    def get_ticker_indicator(self):
        return int(self.timeframe[:-1])

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe['sma5'] = ta.SMA(dataframe, timeperiod=5)
        dataframe['sma200'] = ta.SMA(dataframe, timeperiod=200)
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
        stoch = ta.STOCH(dataframe)
        dataframe['slowk'] = stoch['slowk']


        # resample our dataframes
        dataframe_short = resample_to_interval(dataframe, self.get_ticker_indicator() * 3)
        dataframe_long = resample_to_interval(dataframe, self.get_ticker_indicator() * 12)

                # compute our RSI's
        dataframe_short['rsi'] = ta.RSI(dataframe_short, timeperiod=14)
        dataframe_long['rsi'] = ta.RSI(dataframe_long, timeperiod=14)

        # compute our SMA
        dataframe_short['sma5'] = ta.SMA(dataframe_short, timeperiod=5)
        dataframe_short['sma200'] = ta.SMA(dataframe_short, timeperiod=200)
        dataframe_long['sma5'] = ta.SMA(dataframe_long, timeperiod=5)
        dataframe_long['sma200'] = ta.SMA(dataframe_long, timeperiod=200)

        #compute our RSI
        dataframe_short['rsi'] = ta.RSI(dataframe_short, timeperiod=14)
        dataframe_long['rsi'] = ta.RSI(dataframe_long, timeperiod=14)

        #compute our Stochastic
        stoch = ta.STOCH(dataframe_short)
        dataframe_short['slowk'] = stoch['slowk']
        stoch = ta.STOCH(dataframe_long)
        dataframe_long['slowk'] = stoch['slowk']

                # merge dataframe back together
        dataframe = resampled_merge(dataframe, dataframe_short)
        dataframe = resampled_merge(dataframe, dataframe_long)

        dataframe.fillna(method='ffill', inplace=True)

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (
               (dataframe['resample_{}_sma5'.format(self.get_ticker_indicator() * 3)] >= dataframe['resample_{}_sma200'.format(self.get_ticker_indicator() * 3)] & dataframe['resample_{}_slowk'.format(self.get_ticker_indicator() * 3)] > 50 )&
                (dataframe['resample_{}_sma5'.format(self.get_ticker_indicator() * 12)] >= dataframe['resample_{}_sma200'.format(self.get_ticker_indicator() * 12)] & dataframe['resample_{}_slowk'.format(self.get_ticker_indicator() * 12)] > 50)
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (
                 (dataframe['rsi'] > dataframe['resample_{}_rsi'.format(self.get_ticker_indicator()*3)]) &
                (dataframe['rsi'] > dataframe['resample_{}_rsi'.format(self.get_ticker_indicator()*12)])
	    ),

            'sell'] = 1
        return dataframe
```

**Comment by xmatthias** [comment]
Best get used to having one comparison per line, and wrap lines at the `&` or `|`.

```python
(dataframe['resample_{}_sma5'.format(self.get_ticker_indicator() * 3)] >= dataframe['resample_{}_sma200'.format(self.get_ticker_indicator() * 3)] & dataframe['resample_{}_slowk'.format(self.get_ticker_indicator() * 3)] > 50 )&
```
is invalid syntax, and should be rewritten to 

```
(dataframe['resample_{}_sma5'.format(self.get_ticker_indicator() * 3)] >= dataframe['resample_{}_sma200'.format(self.get_ticker_indicator() * 3)]) &
(dataframe['resample_{}_slowk'.format(self.get_ticker_indicator() * 3)] > 50 )&
```

Personally, i'd recommend to not go a "such dynamic" route which will make things easier

`self.get_ticker_indicator()` is a very dangerous and buggy function, and will not work correctly if you change your timeframe from `5m` to `1h` (nor from 5m to 15m, because your multipliers will be wrong) - so the whole "make it dynamic" is pretty pointless, and only wastes brainpower to try and understand "which indicator did i want again"?.

a better approach might be to use a variable `inf_tf1 = '15m'` and `inf_tf2 = '1h'` at class level, and use these as `self.inf_tf` and `inf_tf2` directly.

i'd then also suggest to use f-strings instead of `.format()` - as it's more leggible 

`'resample_{}_rsi'.format(self.inf_tf1)` becomes `f'resample_{self.inf_tf1}_rsi'` ... which i personally find more readable (and it's also shorter, so you'll see the rest of the line where you had your error.

**Comment by malcomZ** [comment]
Thank you very much for your feedback and your time @xmatthias .

I just did some research with "inf_tf1", but I can't quite figure out how to use it, and despite the documentation and google I can't find any examples, especially on the class level, and to use them directly as self.inf_tf and inf_tf2.

Would it be possible to have a small example of its use?

Thank you again for your time.

**Comment by xmatthias** [comment]
google will turn up a LOT of information if you search for `python class attribute` (or similar).

Just put it alongside your `    timeframe = '5m` (same indentation) ... which makes it a class level attribute.
