### ISSUE TITLE
Buy/sell as market order

### ISSUE THREAD

**Issue by mkdah90** [freqtrade/freqtrade#5769]
## Describe your environment

  * Operating system: ____ linux 18.4
  * Python Version: _____ Python 3.8.12
  * CCXT version: _____ ccxt==1.57.94
  * Freqtrade Version: ____ develop-59ed11358
 
## Your question
I'm new to the bot, thanks a lot for the amazing work
My question is, Why I can't buy market order when i use 

order_types": {
    "buy": "market",
    "sell": "market"
    // ...
  },
  "
The bot answer is
ImportError: Impossible to load Strategy 'MovAvr'. Order-types mapping is incomplete.

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
The [documentation](https://www.freqtrade.io/en/stable/configuration/#understand-order_types) explains this quite clearly:

> If this is configured, the following 4 values (`buy`, `sell`, `stoploss` and `stoploss_on_exchange`) need to be present, otherwise, the bot will fail to start.

**Comment by mkdah90** [comment]
Many thanks
