### ISSUE TITLE
using the current price in buying strategy

### ISSUE THREAD

**Issue by revelationsz** [freqtrade/freqtrade#5775]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I am trying a new strategy and I wanted it to only buy when the price is below an ema, but to do that I need to access the price, but I cannot find anywhere how to access the actual price in the strategies. If I could get some help on how to access it that would be great. Thanks.

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by GluTbl** [comment]
use this `self.dp.ticker()` but make sure the ticker in the exhange class return the current price. if it doesnot, then just overrive the method related to the ticker in Exhange class.

**Comment by xmatthias** [comment]
personally, i'd use [`self.dp.orderbook()`](https://www.freqtrade.io/en/stable/strategy-customization/#orderbookpair-maximum) for this - as that's the faster (and most likely more accurate) way to get the latest price.

Please note that neither of the 2 methods will work in backtesting - and both cause an active exchange network call - so usage may slow the bot down some.
