### ISSUE TITLE
Misleading sentence in Docs

### ISSUE THREAD

**Issue by JackBananas** [freqtrade/freqtrade#5794]
In the Data Downloading chapter, in the tip: "Updating existing data", it is stated:

> If you already have backtesting data available in your data-directory and would like to refresh this data up to today, do not use --days or --timerange parameters. Freqtrade will keep the available data and only download the missing data. [...]

I think it is misleading, but I may be wrong. Souldn't it be as follows? (Changes in bold)

> If you already have backtesting data available in your data-directory and would like to refresh this data up to today, **do not use --timerange parameter, use --days.** Freqtrade will keep the available data and only download the missing data. [...]

**Comment by xmatthias** [comment]
neither `--timerange` - nor `--days` is necessary, and both are ignored if data for a pair is already available.

both commands (`--timerange`, `--days`) are converted to a timerange ... and the only thing you really need to pay attention on subsequent downloads is to not have the start-date before the previously downloaded data.

This means, assuming you got data from 20210101- - and run `--timerange 20201001` (2 additional months at the start) - then this would cause all data to be downloaded again.
In all cases where start-date is AFTER the available start-date - the parameter is ignored, and the download happens from "latest available point" until "now".

In the end, the wording can surely be improved - but your proposal is not correct - and not necessary.

**Comment by JackBananas** [comment]
Thanks for the response! Now I fully understand it, if you just want to keep your data updated you don't need to use any of --days or --timerange options, just execute download-data.

**Comment by xmatthias** [comment]
exactly ... if you have a better wording, please let me know ... ;)

**Comment by JackBananas** [comment]
Sorry for re open the issue. What do you think about this sentence? (Changes highlighted in **bold**):

> If you already have backtesting data available in your data-directory and would like to refresh this data up to today, **Freqtrade will automatically calculate the data missing for the existing pairs and the download will occur from the latest available point until "now". Neither --days or --timerange parameters are required.** Freqtrade will keep the available data and only download the missing data. If you are updating existing data after inserting new pairs [...]

Instead of:

> If you already have backtesting data available in your data-directory and would like to refresh this data up to today, do not use --days or --timerange parameters. Freqtrade will keep the available data and only download the missing data. If you are updating existing data after inserting new pairs [...]

**Comment by xmatthias** [comment]
For sure, that looks great!
Are you able (and willing) to make a quick PR for this? (editing docs should be pretty easy ...)

Thanks in advance

**Comment by JackBananas** [comment]
Done! It's my very first Pull Request (and hopefully not the last) and I expect to have done the whole process correctly.
