### ISSUE TITLE
Different results between HO and backtest

### ISSUE THREAD

**Issue by raftersvk** [freqtrade/freqtrade#5799]
## Describe your environment

  * Operating system:  Ubuntu 20.04.2 LTS
  * Python Version: 3.8.10
  * CCXT version: 1.59.2
  * Freqtrade Version: develop-029ddd23c
  
## Your question
I have created my own strategy with hyperoptable parameters. I followed the documentation as far as I could.
All seemed pretty good until I compared results between HO and backtest...
I know that HO is supposed to be just a backtest so I have double checked all my parameters and what I might have done wrong but I must admit that I still don't understand the reason behind the difference

Here is what I am doing :
1. Run HO with the following
`freqtrade hyperopt -s MyOwnStrat_v1 --hyperopt-loss SharpeHyperOptLoss --spaces buy sell -e 50 -j 7 --timerange 20210901-20211012 --random-state 31078 --logfile user_data/hyperopt_results/MyOwnStrat_v1_0.log`

2. Choose a specific epoch
`freqtrade hyperopt-show -n 48`

3. Run backtest of this epoch parameters
`freqtrade backtesting --strategy MyOwnStrat_v1 --timerange 20210901-20211012`

Result of HO gives me :
| Backtesting from       | 2021-09-01 00:00:00 |
| Backtesting to         | 2021-10-12 00:00:00 |
| Max open trades        | 4                   |
|                        |                     |
| Total/Daily Avg Trades | 130 / 3.17          |
| Starting balance       | 100.000 USDT        |
| Final balance          | 117.442 USDT        |
| Absolute profit        | 17.442 USDT         |

but result of backtest is that :
| Backtesting from       | 2021-09-01 00:00:00 |
| Backtesting to         | 2021-10-12 00:00:00 |
| Max open trades        | 4                   |
|                        |                     |
| Total/Daily Avg Trades | 694 / 16.93         |
| Starting balance       | 100.000 USDT        |
| Final balance          | 85.324 USDT         |
| Absolute profit        | -14.676 USDT        |

Attached are the detailed log of each step + my strat
[MyOwnStrat_v1_0.log](https://github.com/freqtrade/freqtrade/files/7420092/MyOwnStrat_v1_0.log)
[epochshow_MyOwnStrat_v1.log](https://github.com/freqtrade/freqtrade/files/7420094/epochshow_MyOwnStrat_v1.log)
[backtest_MyOwnStrat_v1_0.log](https://github.com/freqtrade/freqtrade/files/7420096/backtest_MyOwnStrat_v1_0.log)
[MyOwnStrat_v1.zip](https://github.com/freqtrade/freqtrade/files/7420097/MyOwnStrat_v1.zip)

**Comment by ppkantorski** [comment]
same issue for me on docker macos.

**Comment by xmatthias** [comment]
There is nothing obviously wrong with the strategy - and it works for me on other strategies.

the only unknown to me is finta - which i've never used (and 1 or 2 of the indicators used).

Best exclude them one by one and repeat the process until results align (it should suffice to run hyperopt for 3-4 epochs for this test).
Obviously it'll be a slightly different strategy - but the way this shows (completely different results) is for sure strange.
please note: i only optimized the buy space - which also shows the same effect.

**edit** 
upon further looking at the strategy i noticed that the "populate_indicators" section is wrong.

`populate_indicators()` is only executed once during hyperopt (with the default parameters) - so all changes to these parameters (`signal_*`) will never be applied to hyperopt.

To do this properly, you'll need to generate all columns upfront - as explained [in the documentation](https://www.freqtrade.io/en/stable/hyperopt/#optimizing-an-indicator-parameter).

**Comment by raftersvk** [comment]
ok so I have to generate all columns for each parameter space possible values.
I might have to reduce the number of parameters / spaces ;)

Thank you

**Comment by xmatthias** [comment]
in theory, you can move the generation of these indicators to `populate_buy_space()` - which will calculate them as part of the epoch.
this can however lead to the same indicator (with the same parameter) to be calculated multiple times (maybe RSI30 is calculated for 10 epochs ...).

It's a decision - depending on available CPU / RAM balance ...
