### ISSUE TITLE
A few changes into webhook actions and format

### ISSUE THREAD

**Issue by nicolaspapp** [freqtrade/freqtrade#5800]
## Describe the enhancement

Hi there,
I am trying to send my freqtrade bots buy/sell signals into an endpoint (https://bitcoinvsalts.com/addyourstrat) that tracks my trades. I have been looking at this [guide](https://www.freqtrade.io/en/stable/webhook-config/), but I am running into 2 limitations with current Webhook setup.
1. Only JSON objects can be configured into the Webhooks section, and in this case I just simply need to send a text line.
2. There is a slight difference between the pair denomination in the framework and TradingView (BTC/USDT -> BTCUSDT)

I  know implementing this little differences makes no sense inside your framework, but It would be interesting to have some sort of interface or code hook where we could define our custom hooks, or wrap current implementation

**Comment by xmatthias** [comment]
You're right, having this in freqtrade makes no sense.
However, also designing a framework to allow people to use hooks is way too niche to invest any time in.

There's maybe 10 people in total i know using webhooks (as is) - which simply doesn't justify the time (neither to implement, nor to maintain) any bigger addition to this.
It'll benefit single individuals - whereas other features can benefit a wider community, which means time is simply better spent there.

Best use an intermediary service (e.g. IFTTT) doing the conversion of formats.
