### ISSUE TITLE
Upgrade to new Hyperopt template structure

### ISSUE THREAD

**Issue by picozzimichele** [freqtrade/freqtrade#5801]
* Operating system: mac os (using docker)
  * Python Version: Python 2.7.16
  * Freqtrade Version: 2021.9
  
Hi All,

I have upgraded to the new 2021.9 release and I am trying to understand how to properly use the Hyperopt. So far I had different files, my understanding is that now that eveything I want to test goes into the strategy file. 

Is there a guide that shows a conversion from an old model (two separate files) to a new model, one single file? Apologies but I cannot make sense from the docs only, for instance I would like to test all the different Bollinger bands

This is my old Hyperopt file, how do I make sure I can achieve the same within the new configuration? 

Wouldnt have all this code into one single Strategy file make things more complex? Is there an alternative to maintain the two separate files?

class BBRSIHyperopt(IHyperOpt):
   
    @staticmethod
    def populate_indicators(dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi-buy'] = ta.RSI(dataframe)
        dataframe['rsi-sell'] = ta.RSI(dataframe)

        # Bollinger bands
        bollinger_1sd = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=1)
        dataframe['bb_lowerband_1sd'] = bollinger_1sd['lower']
        dataframe['bb_middleband_1sd'] = bollinger_1sd['mid']
        dataframe['bb_upperband_1sd'] = bollinger_1sd['upper']

        bollinger_2sd = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband_2sd'] = bollinger_2sd['lower']
        dataframe['bb_middleband_2sd'] = bollinger_2sd['mid']
        dataframe['bb_upperband_2sd'] = bollinger_2sd['upper']

        bollinger_3sd = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=3)
        dataframe['bb_lowerband_3sd'] = bollinger_3sd['lower']
        dataframe['bb_middleband_3sd'] = bollinger_3sd['mid']
        dataframe['bb_upperband_3sd'] = bollinger_3sd['upper']

        bollinger_4sd = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=4)
        dataframe['bb_lowerband_4sd'] = bollinger_4sd['lower']
        dataframe['bb_middleband_4sd'] = bollinger_4sd['mid']
        dataframe['bb_upperband_4sd'] = bollinger_4sd['upper']

        return dataframe

    @staticmethod
    def indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching buy strategy parameters.
        """
        return [
            Integer(5, 50 , name='rsi-value'),
            Categorical([True, False], name='rsi-enabled'),
            Categorical(['tr_bb_lower_1sd', 'tr_bb_lower_2sd', 'tr_bb_lower_3sd', 'tr_bb_lower_4sd'], name='buy-trigger')
        ]

    @staticmethod
    def buy_strategy_generator(params: Dict[str, Any]) -> Callable:
        """
        Define the buy strategy parameters to be used by Hyperopt.
        """
        def populate_buy_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Buy strategy Hyperopt will build and use.
            """
            conditions = []

            # GUARDS AND TRENDS
            if params.get('rsi-enabled'):
                conditions.append(dataframe['rsi-buy'] > params['rsi-value'])

            # TRIGGERS
            if 'buy-trigger' in params:
                if params['buy-trigger'] == 'tr_bb_lower_1sd':
                    conditions.append(dataframe['close'] < dataframe['bb_lowerband_1sd'])
                if params['buy-trigger'] == 'tr_bb_lower_2sd':
                    conditions.append(dataframe['close'] < dataframe['bb_lowerband_2sd'])
                if params['buy-trigger'] == 'tr_bb_lower_3sd':
                    conditions.append(dataframe['close'] < dataframe['bb_lowerband_3sd'])
                if params['buy-trigger'] == 'tr_bb_lower_4sd':
                    conditions.append(dataframe['close'] < dataframe['bb_lowerband_4sd'])

            # Check that the candle had volume
            conditions.append(dataframe['volume'] > 0)

            if conditions:
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'buy'] = 1

            return dataframe

        return populate_buy_trend

    @staticmethod
    def sell_indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching sell strategy parameters.
        """
        return [
            Integer(30, 100, name='sell-rsi-value'),
            Categorical([True, False], name='sell-rsi-enabled'),
            Categorical(['sell_tr_bb_lower_1sd',
                         'sell_tr_bb_mid_1sd',
                         'sell_tr_bb_upper_1sd'], name='sell-trigger')
        ]

    @staticmethod
    def sell_strategy_generator(params: Dict[str, Any]) -> Callable:
        """
        Define the sell strategy parameters to be used by Hyperopt.
        """
        def populate_sell_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
            """
            Sell strategy Hyperopt will build and use.
            """
            conditions = []

            # GUARDS AND TRENDS
            if params.get('sell-rsi-enabled'):
                conditions.append(dataframe['rsi-sell'] > params['sell-rsi-value'])

            # TRIGGERS
            if 'sell-trigger' in params:
                if params['sell-trigger'] == 'sell_tr_bb_lower_1sd':
                    conditions.append(dataframe['close'] > dataframe['bb_lowerband_1sd'])
                if params['sell-trigger'] == 'sell_tr_bb_mid_1sd':
                    conditions.append(dataframe['close'] > dataframe['bb_middleband_1sd'])
                if params['sell-trigger'] == 'sell_tr_bb_upper_1sd':
                    conditions.append(dataframe['close'] > dataframe['bb_upperband_1sd'])

            # Check that the candle had volume
            conditions.append(dataframe['volume'] > 0)

            if conditions:
                dataframe.loc[
                    reduce(lambda x, y: x & y, conditions),
                    'sell'] = 1

            return dataframe

        return populate_sell_trend

**Comment by xmatthias** [comment]
It's actually a lot simpler than the "2 file" approach - but you'll need to read the whole hyperopt documentation, and treat it as "something new" - not "i know 90% of this, just get me the new things".

Simply put - you take the content of `populate_buy_trend` - and move that to the strategy (using the strategy header for the function!).
You can then replace ` params['']` with `self.buy_trigger.value` to get this working.

alternatively, you can even do something like this:

``` python
dataframe.loc[
    (self.buy_trigger.value == 'whatever') & (dataframe['close'] > dataframe['bb_lowerband_1sd'])) |           
    (self.buy_trigger.value == 'somethingelse') & (dataframe['close'] > dataframe['bb_lowerband_2sd'])) 
    <...>
    : 'buy'] = 1
```

**Comment by picozzimichele** [comment]
@xmatthias thanks a lot for the quick turnaround I appreciate the help, I will follow this approach and come back if I have any further questions

**Comment by xmatthias** [comment]
Sure, feel free to comment below / reopen if you got additional questions.

You might also want to join our [discord server](https://discord.gg/p7nuUNVfP7) to get support / help from the community, which is usually a faster / more interactive way to get help than through issues.

**Comment by kushagra2204** [comment]
Hi, I cant seem to get the below file working in hyperopt, any suggestions would be appreciated.
Thanks 

```
class BBRSICOPY2(IStrategy):
    """
    This is a sample strategy to inspire you.
    More information in https://www.freqtrade.io/en/latest/strategy-customization/

    You can:
        :return: a Dataframe with all mandatory indicators for the strategies
    - Rename the class name (Do not forget to update class_name)
    - Add any methods you want to build your strategy
    - Add any lib you need to build your strategy

    You must keep:
    - the lib in the section "Do not remove these libs"
    - the methods: populate_indicators, populate_buy_trend, populate_sell_trend
    You should keep:
    - timeframe, minimal_roi, stoploss, trailing_*
    """
    # Strategy interface version - allow new iterations of the strategy interface.
    # Check the documentation or the Sample strategy to get the latest version.
    INTERFACE_VERSION = 2

    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi".
    minimal_roi = {
        "60": 0.01,
        "30": 0.02,
        "0": 0.04
    }

    # Optimal stoploss designed for the strategy.
    # This attribute will be overridden if the config file contains "stoploss".
    stoploss = -0.1

    # Trailing stoploss
    trailing_stop = False
    # trailing_only_offset_is_reached = False
    # trailing_stop_positive = 0.01
    # trailing_stop_positive_offset = 0.0  # Disabled / not configured

    # Hyperoptable parameters
    buy_rsi = IntParameter(low=1, high=50, default=30, space='buy', optimize=True, load=True)
    sell_rsi = IntParameter(low=50, high=100, default=70, space='sell', optimize=True, load=True)
    buy_trigger = CategoricalParameter(["bb_lowerband2", "bb_lowerband3"], default="bb_lowerband2", space="buy")
    # Optimal timeframe for the strategy.
    timeframe = '15m'

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = False

    # These values can be overridden in the "ask_strategy" section in the config.
    use_sell_signal = True
    sell_profit_only = False
    ignore_roi_if_buy_signal = False

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 30

    # Optional order type mapping.
    order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }

    # Optional order time in force.
    order_time_in_force = {
        'buy': 'gtc',
        'sell': 'gtc'
    }

    plot_config = {
        'main_plot': {
            'tema': {},
            'sar': {'color': 'white'},
        },
        'subplots': {
            "MACD": {
                'macd': {'color': 'blue'},
                'macdsignal': {'color': 'orange'},
            },
            "RSI": {
                'rsi': {'color': 'red'},
            }
        }
    }



    def informative_pairs(self):
        """
        Define additional, informative pair/interval combinations to be cached from the exchange.
        These pair/interval combinations are non-tradeable, unless they are part
        of the whitelist as well.
        For more information, please consult the documentation
        :return: List of tuples in the format (pair, interval)
            Sample: return [("ETH/USDT", "5m"),
                            ("BTC/USDT", "15m"),
                            ]
        """
        return []

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Adds several different TA indicators to the given DataFrame

        Performance Note: For the best performance be frugal on the number of indicators
        you are using. Let uncomment only the indicator you are using in your strategies
        or your hyperopt configuration, otherwise you will waste your memory and CPU usage.
        :param dataframe: Dataframe with data from the exchange
        :param metadata: Additional information, like the currently traded pair
        :return: a Dataframe with all mandatory indicators for the strategies
        """

        # Momentum Indicators
        # ------------------------------------

        # RSI
        dataframe['rsi'] = ta.RSI(dataframe)

        # Bollinger Bands

        bollinger2 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband2'] = bollinger2['lower']

        dataframe['bb_upperband2'] = bollinger2['upper']

        bollinger3 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=3)
        dataframe['bb_lowerband3'] = bollinger3['lower']

        dataframe['bb_upperband3'] = bollinger3['upper']


        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Buy strategy Hyperopt will build and use
        """
        conditions = []
        # GUARDS AND TRENDS


        # TRIGGERS
        if self.buy_trigger.value == 'bb_lower2':
            conditions.append(dataframe['close'] < dataframe['bb_lowerband2'])
        if self.buy_trigger.value == 'bb_lower2':
            conditions.append(dataframe['close'] < dataframe['bb_lowerband3'])

))


       if conditions:
        dataframe.loc[
            reduce(lambda x, y: x & y, conditions),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the sell signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with sell column
        """
        dataframe.loc[
            (
                 (dataframe["close"] > dataframe['bb_middleband'])
            ),
            'sell'] = 1
        return dataframe
```

**Comment by xmatthias** [comment]
> Hi, I cant seem to get the below file working in hyperopt, any suggestions would be appreciated.
> Thanks

@kushagra2204 please don't highjack other issues, but instead open a proper issue (including the issue template, and a description what's actually failing.
We can only provide help with some description (what did you try, what didn't work, are there any errors, ...) - but we will definitely not provide help on questions where a strategy file is dumped with "help me make this work" - without even mentioning what's failing.
