### ISSUE TITLE
 Running setup.py install for TA-Lib ... error

### ISSUE THREAD

**Issue by petehe** [freqtrade/freqtrade#5808]
I have the following error installing TA-Lib, can anyone help?
===================================================== 
   Running setup.py install for TA-Lib ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ph/freqtrade/.env/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c48s8t_o/ta-lib_29069b687ed843b3988292ac771f14e9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c48s8t_o/ta-lib_29069b687ed843b3988292ac771f14e9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-w_t9xyk2/install-record.txt --single-version-externally-managed --compile --install-headers /home/ph/freqtrade/.env/include/site/python3.8/TA-Lib
         cwd: /tmp/pip-install-c48s8t_o/ta-lib_29069b687ed843b3988292ac771f14e9/
    Complete output (27 lines):
    /tmp/pip-install-c48s8t_o/ta-lib_29069b687ed843b3988292ac771f14e9/setup.py:76: UserWarning: Cannot find ta-lib library, installation may fail.
      warnings.warn('Cannot find ta-lib library, installation may fail.')
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/talib
    copying talib/test_stream.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/test_pandas.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/abstract.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/test_func.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/deprecated.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/stream.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/__init__.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/test_abstract.py -> build/lib.linux-x86_64-3.8/talib
    copying talib/test_data.py -> build/lib.linux-x86_64-3.8/talib
    running build_ext
    building 'talib._ta_lib' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/talib
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/home/ph/freqtrade/.env/lib/python3.8/site-packages/numpy/core/include -I/home/ph/freqtrade/.env/include -I/usr/include/python3.8 -c talib/_ta_lib.c -o build/temp.linux-x86_64-3.8/talib/_ta_lib.o
    talib/_ta_lib.c:613:10: fatal error: ta-lib/ta_defs.h: No such file or directory
      613 | #include "ta-lib/ta_defs.h"
          |          ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ph/freqtrade/.env/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c48s8t_o/ta-lib_29069b687ed843b3988292ac771f14e9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c48s8t_o/ta-lib_29069b687ed843b3988292ac771f14e9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-w_t9xyk2/install-record.txt --single-version-externally-managed --compile --install-headers /home/ph/freqtrade/.env/include/site/python3.8/TA-Lib Check the logs for full command output.
Failed installing dependencies

**Comment by xmatthias** [comment]
In short - you'll have to have ta-lib (the c dependency) installed before installing the python modules (where ta-lib is only a wrapper for the python modules).

As you fail to fill out the issue template, as well as provide information HOW you're installing, the rest will be guessing.

Using setup.sh, this will be taken care of for you. Otherwise, best use `build_helpers/install_ta-lib.sh` to install ta-lib, or use the ta-lib documentation to get this installed.

**Comment by petehe** [comment]
thanks xmatthias, the issue is somehow now fixed after manually install ta-lib
