### ISSUE TITLE
Notification overhaul

### ISSUE THREAD

**Issue by shusso** [freqtrade/freqtrade#581]
There is multiple slack/sms/.. etc support questions flying around. I think the first stab is to refactor the bot to be controlled in command line while supporting Telegram. Then we have a easier base to add more notifications.

**Comment by xmatthias** [comment]
Eventually using a module like [notifiers](http://notifiers.readthedocs.io/en/latest/index.html) would make sense, as it supports multiple notification methods, including but not limited to Telegram, Slack, email and SMS (using Twilio).

**Comment by crypdick** [comment]
Here's  a repo that implemented the notifiers module route:

https://github.com/CryptoSignal/crypto-signal/tree/master/app/notifiers

(MIT license)

**Comment by xmatthias** [comment]
after looking at notifiers a bit more in detail - i'm not sure if notifies will bring what we need (controlling the bot over telegram does not seem possible with it unless I missed that part in the docs)

**Comment by xmatthias** [comment]
I think i'll close this since we've done huge refactorings to RPC, and integrating a new handler is now pretty straightforward (#1863).
