### ISSUE TITLE
Plotting Trade Frequency from backtest result

### ISSUE THREAD

**Issue by aezomz** [freqtrade/freqtrade#5811]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

Hi, I was looking at https://www.freqtrade.io/en/stable/plotting/#plot-profit

I think this is the least used feature, but do we have a way to plot trade count frequency over time?
Will be interesting to see the strategy trade frequency over the year for example (any seasonality) . 

I am new to contributing to open source, willing to read through the docs. If this feature is feasible to look at,
I will try my best for to create a PR. Any guidance will be appreciated, I will read the contributing docs for a start.

**Comment by xmatthias** [comment]
If you look at freqUI, you'll see that the "tradesLog" view does something very similar (but not exactly the same).

I think it would be a great improvement to have that "switchable" - so you can look at it from both ways (and adding things to freqUI is more future-proof, as i'm not sure the plotting module in freqtrade itself makes sense much longer (freqUI allows basically the same thing - but in an interactive way).

**Comment by aezomz** [comment]
Got it, I went through FreqUI repo. Didn't know it was there (since its alpha). 

I will consider exploring further since its in Vue and typescript. 

Thanks!

**Comment by donjonson** [comment]
does freqUI work with backtests?  I thought it only worked with live trading/dryruns?

**Comment by xmatthias** [comment]
@donjonson you can use webserver mode [`freqtrade webserver`](https://www.freqtrade.io/en/stable/utils/#webserver-mode) to start only the webserver. if you then connect to the UI, it'll have a "backtesting" tab - which will give you the same information than regular backtesting.
Doing iterative backtesting (while changing a strategy) is faster this way too - as it'll not load the data every time as long some parameters (timeframe, timerange) are not changed.

**Comment by aezomz** [comment]
@xmatthias , just to check. I managed to connect Freqtrade api server and web. Freqtrade Web looks pretty similar to FreqUI Web. 

I assume FreqUI is the matured version of Freqtrade Web (definitely more features/ future-proof etc...)

To develop on FreqUI, I run FreqUI & Freqtrade webserver? Where do I get dummy data to development?

So I can use Freqtrade webserver back test for dummy data and do development? 

I already have FreqUI running, just unsure how to connect and do testing.

**Comment by xmatthias** [comment]
personally - i start freqtrade in webserver mode, run one backtest - and then use the "load backtest result" to get the data into freqUI.
that way, there's no "real" dummy data - but "your" dummy data. It's not ideal for sure - but so far, time has not allowed for proper dummy/mock data (which would surely be awesome - especially when thinking about e2e tests ...).

I'm not sure what you're talking about with "freqtrade web" ... there's never been such a thing - it's always been called FreqUI ...

**Comment by aezomz** [comment]
Ahhh my bad. I will try to run Freqtrade for only the API. 
Ok, I will try the load backtest result to get some data into FreqUI.  Thanks!

I was referring to this by "freqtrade web", I guess they are the same thing. I was running it off docker.  
`Once the bot is started in trade / dry-run mode (with freqtrade trade) - the UI will be available under the configured port below (usually http://127.0.0.1:8080).`
