### ISSUE TITLE
Save buy price in a variable and use it in sell_trend

### ISSUE THREAD

**Issue by KarimHP** [freqtrade/freqtrade#5812]
If i want to safe the price where i bought in a variable and use it as a condition in the sell_trend to say something like:

```
sell if: condition 1 && if (dataframe["close"] > original_buy_price 
```

how do i achieve this?

thx in advance for any help

**Comment by xmatthias** [comment]
First of all, please fill out the issue template.
We ask very specific questions we expect answered - just as you expect an answer to your questions.


then, please make sure to use the documentation to search for issues / solutions before asking questions in issues.
While we do like to help, we don't like to answer questions that could've been found in the documentation.

in `populate_sell_trend`, you cannot get access to the trade without breaking backtesting/hyperopt support for your strategy.

If you need the trade object for your sell signal, you'll have to use [custom_sell](https://www.freqtrade.io/en/stable/strategy-advanced/#custom-sell-signal).
