### ISSUE TITLE
Get trade indicators in log file

### ISSUE THREAD

**Issue by antonino-git** [freqtrade/freqtrade#5814]
Would it be possible to include per each completed trade the value of various indicators in the log file? 

For example: 

{"pair":"FORTH/USDT","stake_amount":99.884096,"amount":6.34991074,"open_date":"2021-10-2702:30:00+00:00","close_date":"2021-102706:20:00+00:00","open_rate":15.73,"close_rate":15.533,"fee_open":0.001,"fee_close":0.001,"trade_duration":230,"profit_ratio":-0.01449682,"profit_abs":-1.44944968,"sell_reason":"trailing_stop_loss","initial_stop_loss_abs":15.414,"initial_stop_loss_ratio":-0.02,"stop_loss_abs":15.533,"stop_loss_ratio":-0.02,"min_rate":15.53,"max_rate":15.85,"is_open":false,"buy_tag":null,"open_timestamp":1635301800000.0,"close_timestamp":1635315600000.0,**"rsi":23**}

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

The short answer to your question is no.

Each strategy will be different and require different indicators (and potentially has 10s of indicators it's not actively using). As such, it's impossible for us to provide this in the logs.
There's however nothing preventing you from printing / logging within the strategy, which will make sure that you're logging the indicators that are important to your particular strategy.

**Comment by antonino-git** [comment]
Thanks for your quick answer and sorry for not using the template. I'm new to the community, and I wasn't aware of the rule. 

I understand that it's impossible to log indicators in the backtesting log. So I'm thinking of the best way to log trade results and indicators together in the strategy. The confirm_trade_exit callback seems to be the best place to log the trade results however, the indicators are not available within the function's scope. So it seems that the only solution is to log indicators and trade results in two different places and then combine them. Is this correct or is there a better way to do it?

**Comment by xmatthias** [comment]
To be honest, i'm not sure why you'd want to log the indicators in the first place.
You can use `plot-dataframe` or freqUI to visualize all indicators, where you can (interactively) see each indicators as line.
the fact that RSI was 30 is most often irrelevant, but the fact that it's crossing from below or from above (so where it's moving from/to) is much more important - which you'll not be able to see with only 1 value.

**Comment by antonino-git** [comment]
@xmatthias, this enables me to run some statistical analysis on trade results and indicators. For example, by creating a histogram with an indicator and the trade results I could discover things like: when rsi>30 at the purchasing time the trade fails in 80% of the cases. This helps to improve the strategy and select the more meaningful indicators.

**Comment by xmatthias** [comment]
Nothing prevents you from doing so - all data is available (trade entry/exit time, candles) - so it's simply a question of combining the information. We have some samples on loading the data in [the documentation](https://www.freqtrade.io/en/stable/strategy_analysis_example/) - it's then up to the user to combine it in a way that you see fit.

For freqtrade, this is however not possible to do automatically for you, as there can be 100ds of indicators in a strategy, but only 5 might be used (or all 100 might be used).

**Comment by antonino-git** [comment]
Got it. Thanks!
