### ISSUE TITLE
Cancel order after limited time

### ISSUE THREAD

**Issue by mkdah90** [freqtrade/freqtrade#5817]
## Describe your environment

Operating system: ____ linux 18.4
Python Version: _____ Python 3.8.12
CCXT version: _____ ccxt==1.57.94
Freqtrade Version: ____ develop-59ed11358

## Your question
Actually I have 2 questions, 
the first one is >>> when I use a day chart and have maximum orders of 3, if in middle of the day one of the 3 opened order was fulfilled and sold, it open's a new order if it matches the strategy but it's the middle of the day and the price already is high

so how I can prevent this from happening, I only want it to buy in the few minutes after the opening of new candle
----------------------
the second question is >>> I have another running strategy that uses hour chart
how can I prevent buying order after a big pump 
I already use volatility but it's over the last few days and I want something to prevent buying in the next few hours after 10% percent increase in token price

thaaaaaaanks again 
I wan 

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
the documentation points out a very handy feature, [`ignore_buying_expired_candle_after`](https://www.freqtrade.io/en/stable/configuration/#ignoring-expired-candles), which was introduced to specifically handle this scenario (which obviously becomes worse with longer candle sizes).


You can combine any indicator you want to prevent buying after big pumps  (even as simple as comparing current and previous close prices)... it's however a question of believe if that's a good or bad approach, and what indicators / limits to use for this.

Best research this independently of freqtrade, as it's more a trading advise than a "how to do it with freqtrade" - and you'd only get opinions (how i'd do it), not real facts about this.

**Comment by mkdah90** [comment]
thanks for the first one
about the second one, I only want a code that exclude any coin that hast 10% PERCENT increase in price in last 24 hours

**Comment by xmatthias** [comment]
You have a simple idea in mind, great.
then implement this as part of your strategy :) 

it's a simple "guard" - basically another condition in your strategy.
