### ISSUE TITLE
"Outdated history for pair xxx" - Update Output Please

### ISSUE THREAD

**Issue by qkum** [freqtrade/freqtrade#5819]
## Describe the enhancement

Please change the output text from:
`2021-10-31 10:22:50,241 - freqtrade.strategy.interface - WARNING - Outdated history for pair ASD/USDT. Last tick is 142 minutes old`

*Explain the enhancement you would like*

To:
`2021-10-31 10:22:50,241 - freqtrade.strategy.interface - WARNING - Inactive pair ASD/USDT. No trades for 142 minutes`

*Why change it?*

So everybody who uses this lovely bot does not have to use hours on finding out that it has nothing to do with an API problem but just a barely traded pair.

I have taken me days to find out by a lucky 5th google search. (when you refuse to give up you google every day until you get lucky) 

I even gave KuCoin some bad rap for their API sucking - that I now have to delete. 

Let's make life easier for everybody frens.

Thanks for your hard work as always.

**Comment by qkum** [comment]
I seriously did not have the imagination that KuCoin would have pairs not traded for hours.

It is not logical at all.

And funny enough you can be lucky that a trade occurs while you pause the bot for 5 min and try to manually download the missing data and suddenly you are convinced that it must be an API problem lol.

**Comment by xmatthias** [comment]
I'm marking this as question and Documentation - as it's not something we intend to change.
The only thing we can do is add it to our FAQ - so it's easily findable.

Your proposal does make an assumption about the reason - which might be true in your case, but can also be totally wrong.

The message appears if the latest received candle is outdated.

This can however have multiple reasons:
* Barely traded pair
* Exchange downtime
* API problem (returning old candles)
* System problem (your system clock is not set correctly).

An inactive pair (your proposed wording) is incorrect - as an inactive pair is a delisted pair - which this one isn't as far as i can tell (i can still be the first to trade it today ...).

Note: almost every exchange has some barely traded pairs - they are usually good candidates for delisting at some future point - unless volume picks up again.
