### ISSUE TITLE
Behavior of assigning trade.sell_reason in confirm_trade_exit differs between backtest and dry/live

### ISSUE THREAD

**Issue by leonardvdj** [freqtrade/freqtrade#5828]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: 3.9.7 (`python -V`)
  * CCXT version: 1.59.77 (`pip freeze | grep ccxt`)
  * Freqtrade Version: docker-7ae9b901 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the problem:

In backtesting, `trade.sell_reason` can be altered in `confirm_trade_exit`. In dry run however, the sell reason stays unaltered from its original reason.

I believe this is because in [backtesting.py](https://github.com/freqtrade/freqtrade/blob/e8f85aed6b45c8af61474fceb7a9bfab956784dc/freqtrade/optimize/backtesting.py#L362), `trade.sell_reason` is assigned before `self.strategy.confirm_trade_exit` is run.
But in [freqtradebot.py](https://github.com/freqtrade/freqtrade/blob/5f23af580248a86a56d60e050bd5d0a7f5424236/freqtrade/freqtradebot.py#L1143), `trade.sell_reason` is assigned *after* `self.strategy.confirm_trade_exit` is run, which results in any custom set sell reason being overridden.

### Steps to reproduce:

  1. Set `trade.sell_reason` in `confirm_trade_exit` (Example test strategy attached)
  2. Run backtest and observe custom sell reason is displayed in `sell reason stats`
  3. Run dry run and observe custom sell reason is not displayed in `sell_reason`
  
### Observed Results:

  * What happened? Original unaltered sell reason was displayed
  * What did you expect to happen? Custom sell reason to be displayed

### Relevant code exceptions or logs

No relevant errors or logs.
[CTETest.txt](https://github.com/freqtrade/freqtrade/files/7462824/CTETest.txt)

**Comment by xmatthias** [comment]
I'm not quite sure i consider this a bug / problem, but rather wrong usage.

Where in the documentation did you find that it's possible / acceptable to change sell-reasons in `confirm_*` methods?
The place to assign / set sell-reason is in either `custom_sell()` - or (starting with #5756) in `populate_sell_signal()`.
Other methods serve other purposes.
On top of that, assigning things (no matter what attribute) directly to the trade object should not be done / is not allowed and can lead to unwanted behavior or bugs or database corruption (maybe the type you assign is wrong, ...) - none of which will be double-checked - as the object should be considered read-only (i'll have to investigate if it's easily possible to make the trade-object read-only ...).

**Comment by leonardvdj** [comment]
You're right, it may not exactly be a bug nor meant to be used in this fashion. The root of the problem is that I cannot set buy tag from the confirm trade entry method, so I'm left with adding attributes to the sell reason in confirm trade exit (custom sell would not let me do this to sell reasons outside sell signal). My use case is creating a trailing buy, without having to use process only new candles, so confirm trade entry would be the place to do that, and I could do that fine but I'd also like to keep some statistics on offset, what percentage I entered at etc.
If there's a better way of doing this, I'm all open for it, but I could not see a way to do so.

**Comment by xmatthias** [comment]
I'm not sure what you're trying to do - but it's definitely not something that's supported / documented - which means it's something that can break with every commit (you're using/abusing freqtrade internals - which may change at any time) - so you will want to be VERY careful with every update you take.

To be honest, i'm not sure i understand your usecase ... `process_only_new_candles` got nothing to do with tags - nor with "confirm entry/exit" methods.
trailing buy is not really supported, but you should be able to (kindof) simulate that by simply blocking `confirm_trade_entry` until the price suits you.
I don't understand however how/why you'd want to set buy-tag there - you already have a buy signal - just add your tag there ?

**Comment by leonardvdj** [comment]
The content I want in the buy tag is dependent on the rate it buys in at, so I cannot set it in populate_buy_trend, it has to be set from confirm_trade_entry.
Your 2nd last line, that is exactly what I'm doing.

**Comment by leonardvdj** [comment]
```py
custom_info = {}
trailing_entry = 0.0005

def confirm_trade_entry(self, pair: str, order_type: str, amount: float, rate: float, time_in_force: str, current_time: datetime, **kwargs) -> bool:
  dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
  last_candle = dataframe.iloc[-1].squeeze()

  pct = (rate - last_candle['close']) / last_candle['close']

  if not pair in self.custom_info:
    self.custom_info[pair] = {
      'offset': self.trailing_entry,
      'pct': pct
    }
  else:
    self.custom_info[pair]['pct'] = pct

  if pct > self.custom_info[pair]['offset']:
    return True
  else:
    self.custom_info[pair]['offset'] = min(pct + self.trailing_entry, self.custom_info[pair]['offset'])

  return self.config['runmode'].value not in ('live', 'dry_run')

def confirm_trade_exit(self, pair: str, trade: Trade, order_type: str, amount: float, rate: float, time_in_force: str, sell_reason: str, current_time: datetime, **kwargs) -> bool:
  trade.sell_reason = f'{sell_reason} ({self.custom_info[pair]["pct"]:.2%} - {self.custom_info[pair]["offset"]:.2%})'
  del self.custom_info[pair]
  return True
```
Here's exactly what I'm doing / trying to do. The pct & offset properties are what I'd like to keep a log of, and preferably I'd like to do that with buy_tag as that makes most sense, but there's no way to set that from confirm_trade_entry.
That's why I resorted to sell_reason as that seemed the only possible option while including it in roi, stoploss etc. also.

**Comment by xmatthias** [comment]
this has a few problems at first glance - and will fail should you ever restart a bot with an open trade (your `custom_info` will be empty - which you're not checking for in `confirm_trade_exit()`.

because of this, i think your approach is pretty dangerous and potentially not working (apart from the possibility that you're crashing the database / bot with too long sellreasons ...).

That said - i think your whole approach to this issue (how your question / issue is stated) is wrong. 
I guess your real problem is not how `confirm_trade_exit` is called, but that you can't dynamically change buy_tag once the entry happens, so what you'd really need is an additional callback "entered trade" or something similar, which can can be used/abused for this.

Please note: direct assignment to the trade-object will be prevented in the near future as you've now made me aware of this, so the call sequence for this is irrelevant (and if any, the change will be in backtesting as freqtradebot is the correct way for this in my opinion)

**Comment by leonardvdj** [comment]
Yeah trade object thing is fair, it doesn't work anyways ^^ And yeah, the custom_info stuff I haven't really gotten further with, I first wanted to see if it was a feature worth pursuing, but was unable to do so because I had no way of seeing the pct/offset properties. Some kind of callback would do the trick yeah.
So there's no way of currently doing what I'm attempting to do, without editing freqtrade itself? Even if it potentially is a hacky way, just so I can at least test out the feature, see if its worth pursuing.
Seems I can do `trade.buy_tag` in confirm_trade_exit, so that'll work for now just so I can test it. But of course, it's not ideal nor intended. Any ideas for how else to do this are welcomed.
