### ISSUE TITLE
Customize Dashboard

### ISSUE THREAD

**Issue by GregBreak** [freqtrade/freqtrade#5829]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

How to replace the default dashboard? I've found grafana templates but I have no idea how to replace it
https://grafana.com/grafana/dashboards/14632

Thanks

**Comment by xmatthias** [comment]
The official visualization for freqtrade is FreqUI.
Some people use grafana from what i've heared, but it's not something we support officially, or through this channel.

Best get in touch with the authors of the dashboard if you have questions.
