### ISSUE TITLE
support for multiple partial take profit points for a single trade. 

### ISSUE THREAD

**Issue by donjonson** [freqtrade/freqtrade#5830]
currently freqtrade only allows sale of the complete trade value. I would like to set it up so that it can take X% profit at X points.

perhaps this could be implemented in the custom_sell function.

**Comment by xmatthias** [comment]
Freqtrade currently does not support position staking (neither when entering, nor when exiting).

This is already available / requested as issue - so progress can be found here: #1519 

Closing as duplicate of that issue.
