### ISSUE TITLE
in custom_sell what is the proper way to get an indictors value at trade.open_date?

### ISSUE THREAD

**Issue by donjonson** [freqtrade/freqtrade#5837]
## Describe your environment

  * Operating system: ____Ubuntu 20.4
  * Python Version: _____ (`python -V`) 3.9.4-1
  * CCXT version: _____ (`pip freeze | grep ccxt`)  1.59.2
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  freqtrade develop-c7edffb
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

My strategy wants to set a trade specific sell point of open_rate + (2*ATR) at trade.open_date.

I saw some information regarding a buy tag in the populate_buy_trend function but that is not exactly what I need here.  
I have tried many ways to do this.  some have partially worked.  what is the correct/most efficient way to do this? Should I save the value to a variable of the strategy object?  if so how do I get the value of the an indicator in the current candle?  the way the populate_buy_trend function is written it seems to be unaware of the current candle.  it just operates on the entire dataframe in one operation. 

I know my issue here is ignorance so please be patient with me :)  thank yo so much!

**Comment by xmatthias** [comment]
You should be able to get pretty far by combining the information on [custom_sell](https://www.freqtrade.io/en/stable/strategy-advanced/#custom-sell-signal) with the examples of [custom-stoploss](https://www.freqtrade.io/en/stable/strategy-advanced/#custom-stoploss) - and maybe with [dataframe access](https://www.freqtrade.io/en/stable/strategy-advanced/#dataframe-access).

A combination of these 3 will give you everything you'll need (use a value from the trade-open candle to determine sell points).

**Comment by donjonson** [comment]
thank you that got me on the right track!
