### ISSUE TITLE
Hyperopt merge with stategy

### ISSUE THREAD

**Issue by Trance98** [freqtrade/freqtrade#5839]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: __3.9___ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.10 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
How to merge Hyperopt files with strategy since using separate Hyperopt files is now not supported?
*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Please read the [hyperopt documentation](https://www.freqtrade.io/en/stable/hyperopt/) on how to write Parametrized strategies. It contains all the information you'll need.

The concept is completely different, but you will see that its a lot easier to get hyperopt and strategy to combine.
You might be able to copy some parts of your hyperopt file (with modifications) - but in general, consider it a rewrite of the hyperopt file.
