### ISSUE TITLE
Can I "withdraw" money from the bots available_capital after it has been trading for a while?

### ISSUE THREAD

**Issue by donjonson** [freqtrade/freqtrade#5841]
* Operating system: ____ Ubuntu 20.4
  * Python Version: _____ (`python -V`) 3.9.4.1
  * CCXT version: _____ (`pip freeze | grep ccxt` 1.59.2)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  freqtrade develop-c7edffb
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

If I want to extract some profits from my bot but don't want to shut it down.  Is it possible to reduce its available capital so I cant transfer some money out?

**Comment by xmatthias** [comment]
it'll depend on how you've configured your bot, but in general, it's not an issue as long as you withdraw the capital in stake-currency (you're not stealing the bots trades).

Assuming you use a standard config (the bot get's all money in the account in stake currency) - simply reducing this stake-currency will cause the bot to either open fewer trades (static stake-amount - it won't have enough money to buy anymore) - or use fewer stake per trade (dynamic stake - 100/5 is smaller than 1000/5).

Now if you configured `available_capital` - it becomes tricky - as you've limited the bot to a certain amount (say 50%) of the total wallet.
If you then withdraw, the bot will still assume the same amount to be "his" - and eat into the other 50% you wanted to keep away from the bot.
You can certainly change `available_capital` mid-run - but i THINK that's going to mess with your profit stats - as it's assumed as the basis for the starting capital - and therefore used for total profit calculations.
