### ISSUE TITLE
Temporary blacklist pair request

### ISSUE THREAD

**Issue by spc789** [freqtrade/freqtrade#5845]
## Describe your environment

  * Operating system: Ubuntu18/20
  * Python Version: Python 3.7.5 
  * CCXT version: 1.60.36 
  * Freqtrade Version:  develop-335412a3a 

## Describe the enhancement

Telegram command to temporarely blacklist a pair for a defined period. For example /tempblacklist AVA 5h
Sometimes with certain strategies one sees in the ui that a coin which was bought was pumped hours before the buy. One can manually /forcesell that pair if one is quick enough but many times some strategy keep buying it even after the /forcesell

A command to temporarely blacklist a coin for some defined time could be handy in those cases. 
The above fictive command could blacklist AVA/STAKE for 5 hours and after that auto whitelist it again. (where STAKE is taken from the config file.
One could do the same with minutes (m) or days (d) instead of editting the config and reloading it or temporarely stopping the bot.

*Or* ... one could split this feature request in two separate feature requests :
- the feature of having a dynamically temporary blacklist besides the blacklist in the config files, which can be populated by strategies and/or rpc commands (one could populate it with anti-pump functions "to-be" in strategies or other needs)
- the feature of populating or depopulating that dynamicaly blacklist by rpc command(s)

**Comment by xmatthias** [comment]
I'd not use blacklist for temporary locking (unless you want to unlock yourself) - but the locking mechanism (which has times builtin).
This can already happen from within the strategy - so to have somewhat reproducible results, you should consider implementing this logic in your strategy instead.


You can also populate blacklist with rpc methods already (`/blacklist <pair>` - what you can't do is remove pairs from that - but that would also fill part of what you need i guess.

**Comment by spc789** [comment]
Major thx ! 
I didn't know the main functionallity of dynamically blacklisting was allready in Freqtrade. Any chance on adding the 'temporary' part in Freqtrade so the unlocking of "temporary" blacklisted pairs can be auto-unlocked depending on a timer/timing value ?

**Comment by xmatthias** [comment]
as said - the "unlocking" is problematic as it's not implemented (you can however `/reload_conf` to get your original blacklist back).

Temporary locking (with time) will not be added as part of /blacklist for sure. As mentioned above - i can imagine it via some `/lock` mechanism (which already accepts time - but only from within the strategy).
