### ISSUE TITLE
Hyperopt Error

### ISSUE THREAD

**Issue by bobysp7** [freqtrade/freqtrade#5852]
## Describe your environment

  * Operating system: windows 10
  * Python Version: python 3.9
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: stable
  
When I run hyperopt, i receive warning, /home/ftuser/.local/lib/python3.9/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated " over and over

this is the log, 
[Documentation](https://www.freqtrade.io/en/latest/)*
[error.txt](https://github.com/freqtrade/freqtrade/files/7491083/error.txt)

i'm new to this stuff, i appreciate your help

**Comment by xmatthias** [comment]
That warning simply means that you ran out of new values to test (or it ran into a deep local minima it cant get out of).

Basically, your test space is smaller than the number of epochs.

Itll depend on the strategy how to work on that, but can be as simple as accepting it (results wont get better, bigger space makes no sense) or add more Parameters / wider margins on the parameters.

**Comment by bobysp7** [comment]
thank you very much, i'll try add more Parameters and wider margins on the parameters and test it out
