### ISSUE TITLE
Changing Stoploss  and Trailing Stop Paramaters During Active Trade

### ISSUE THREAD

**Issue by AliSertanYaka** [freqtrade/freqtrade#5854]
## Describe your environment

Operating system: Linux - Ubuntu
Python Version: 3.8
CCXT version: ccxt==1.57.3
Freqtrade Version: 2021.9
  
## Your question

Hello, I have question that I can not find an answer. And sorry for this long message 😦

I want to change trailing stop and stoploss parameters during the active trade, is there anyway to do that or similar things?

Explanatory Example:

    #  Stoploss
    stoploss = -0.10

    # Trailing stoploss
    trailing_stop = True
    trailing_only_offset_is_reached = True
    trailing_stop_positive = 0.03
    trailing_stop_positive_offset = 0.05

The bot buys an asset at a price of 100$,

after the asset price reached to to 111$ I want to adjust the parameters like below

    # stoploss

     stoploss = +0.10 ( !! sign is positive )

    # Trailing stoploss
    trailing_stop = True
    trailing_only_offset_is_reached = True
    trailing_stop_positive = 0.05
    trailing_stop_positive_offset = 0.15

My main aim is that if the trade reach 11% profit, fixing % 10 profit and at the same time letting the profit goes on if the asset price continues to goes up by following that profit 5% from behind.
if trade can not reach 10% profit, the parameters should stay same.

**Comment by xmatthias** [comment]
Then you didn't look very far ... 

Using parameters alone, you cannot do this - there, stoploss-values are as configured (and identical for all pairs).


You can however use whatever method you want by using [custom stoploss](https://www.freqtrade.io/en/stable/strategy-advanced/#custom-stoploss).

Samples for things similar to what you want to archive are available in that documentation segment, too.
