### ISSUE TITLE
Possible to backtest (and trade) using sub-minute timeframes (e.g. 5 seconds) / candlesticks?

### ISSUE THREAD

**Issue by drewclifton** [freqtrade/freqtrade#5865]
Hello! My strategy/approach happens to be optimized for 5s-15s candlestick charts.

As such I'm curious to understand what might be involved in backtesting, and trading, based on sub-minute level timeframes. (So far I haven't found anything in my searching around this topic)

Thanks so much!

Kindly 😀

**Comment by xmatthias** [comment]
I know no exchange that's providing candlestick data at a sub-1m level. 
Without data - no backtest. 
Obviously you can still use dry-run to validate your strategy - but with a timeframe this small, you'll need to use a very small set of pairs to not run into performance problems (where analysis / decision takes longer than the candle is).

**Comment by drewclifton** [comment]
Thanks so much. Yes I did notice that exchanges provide minimum 1m.

Ok - Perhaps to test this concept out I will need to see about pointing Freqtrade at my own data source then.

I will create a separate question on that topic, I hope that is ok!

All the best.

**Comment by xmatthias** [comment]
While you can for sure use your own datasource, it's not something we support (nor provide support / help to get working).

Your best bet will be by resampling raw trade data (the only datasource exchanges provide that's lower than 1m) ... but be careful with that, as you will not reliably be able to get this data in live mode - as exchanges often delay this data by multiple minutes before making it available via rest api - so your signals MUST be based on something else (basically the only thing you got left is orderbook data - or `np.random`).
