### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by edthepurple** [freqtrade/freqtrade#5867]
## Describe your environment

  * Operating system: CentOS 8
  * Python Version: 3.9 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: latest (docker) (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Telegram

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Can we set more than one chatid for the bot to respond to? or make the bot respond to "any" chatid? or better, invite the bot to a group/channel and let it post updates there?

**Comment by xmatthias** [comment]
chat-id is a string, not a list, so you can only have one.
You should also consider a bot to be something private / personal - if someone can receive messages from the telegram bot connected to freqtrade, that person can then also control the bot - and potentially cause you losses.

While you can use `group_id` [see docs here](https://www.freqtrade.io/en/stable/telegram-usage/#use-group-id) - i strongly advise against that, as it'll allow everyone in the group to fully control the bot (including force-selling trades, as well as deleting trades while they're still open).
