### ISSUE TITLE
Telegram /stats Kucoin Error

### ISSUE THREAD

**Issue by V-tin** [freqtrade/freqtrade#5869]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: 3.9.7
  * CCXT version: 1.60.11
  * Freqtrade Version: develop-6267678ca & stable-2021.10

## Describe the problem:

When using Telegram command "/stats" with Kucoin as exchange, there is no results.
Log error:

> 2021-11-09 12:26:24,709 - freqtrade.rpc.telegram - WARNING - Telegram NetworkError: Message is too long! Trying one more time.

> 2021-11-09 12:26:24,951 - freqtrade.rpc.telegram - WARNING - TelegramError: Message is too long! Giving up on that message.

### Steps to reproduce:

  1. start freqtrade with NFI strategy [https://github.com/iterativv/NostalgiaForInfinity](NostalgiaForInfinity) on Kucoin exchange
  2. use /stats command in Telegram
  3. check the log
  
### Observed Results:

  * No results or response after the /stats command
  * Expected to receive response on stats result
  * With Binance exchange, it works as expected

**Comment by xmatthias** [comment]
i assume this strategy makes excessive use of sell reasons - making the message become too big.

I don't really see this as a generic problem, but one limited to this strategy (never seen it anyplace else).
That makes it very low priority (which basically means, i'll not work on it for the moment)... so to get this fixed, best report this to the original strategy author, who can then either use fewer different sell reasons, or submit a Pull request here fixing the issue.
It also shouldn't be too hard to fix as there's multiple samples in `telegram.py` to split a message up - so it's obviously "free game" for anyone looking to contribute.
