### ISSUE TITLE
PerformanceFilter seems not to affect whitelist

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#5870]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Miniconda 3 x64 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.9 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

The config.json with VolumePairList part and uniquly the PerformanceFilter added, does not show any difference in sorting and concerning the amount of pairs in the whitelist, as this filter is present or removed. As an additional test, I started the bot with the the unrealistic PerformanceFilter values of "minutes": 1, "min-profit": 1. Still the pairs are listed in the same order and amount.
What configuration is needed to activate the PerformanceFilter correctly?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
PerformanceFilter relies on past performance of the bot based on it's database - so you can effectively not use it on a "new" bot - but it'll only become active after the bot did some pairs.

In the end, it's probably a filter you can only activate after a few 10/100 trades - otherwise you risk filtering out pairs based on 1 bad trade.

**Comment by myNextCoder** [comment]
Many thanks, very important to know. I was sure, that the data is built on global statistics of the exchange. Now everything is clear :)

**Comment by myNextCoder** [comment]
With version 2021.9 on Windows Server 2022 within Miniconda x64 I still have an issue with PerformanceFilter. The bot is running since 2 days, with nearly 400 trades. No matter what values I declare with this filter, the whitelist remains the same. "pairlists" follows the white and the black list in the json file. Is this a position issue? What else could affect the filter in this way?

**Comment by xmatthias** [comment]
best check the logs if that filter has been loaded - maybe you're configuring it in the wrong place (wrong config file, wrong key in the configuration) - so it's not even loaded.
