### ISSUE TITLE
ERROR - VolumePairList 

### ISSUE THREAD

**Issue by marvix** [freqtrade/freqtrade#5872]
Hi,

I just installed the latest version, when I'm trying to do backtesting  with`freqtrade backtesting --datadir user_data/data/binance/ --stake-amount 100 -s MyStrategy -i 15m`, I'm getting this error `ERROR - VolumePairList not allowed for backtesting.`

I could not find the reason, would some kindly help.

Thanks,

**Comment by xmatthias** [comment]
For next time - please get used to filling out the issue template. 
It's there for a reason - and often avoids unnecessary back and forth.

---

For your question - it's pretty simple - Volumepairlist cannot be used in backtesting - as it'll contain the pairs that had the highest volume in the last 24 hours.
As such - your pairlist would be "future-biased" already (pairs that currently have high volume - which might be different pairs than a month ago).

you can use `freqtrade test-pairlist` to extract the current list and use it as [static pairlist](https://www.freqtrade.io/en/stable/plugins/#available-pairlist-handlers) - however i'd advise to also carefully consider the pairs - and if they did exist at the start of your backtesting period.

**Comment by florisherman** [comment]
Hi how do you populate this list, whats the format of the file and where should it be located.
Thanks

**Comment by xmatthias** [comment]
Static pairlist is configured in `exchange.pair_whitelist` - and it's a simple list of pairs.

**Comment by florisherman** [comment]
Thanks! in the config.json file got it!
