### ISSUE TITLE
gateio does not support market orders?

### ISSUE THREAD

**Issue by dapao111** [freqtrade/freqtrade#5873]
![image](https://user-images.githubusercontent.com/57710416/141053285-7439c301-f6b5-4cfd-ab07-659c4dd7de7a.png)

**Comment by xmatthias** [comment]
First of all - fill out the issue template, issues without it will be closed.

Then - please follow the instructions in the template - which clearly states: "logs as text - no screenshots".

Also - please try to search through the documentation, it's very likely to be covered there already.

---

For your issue - it's quite simply what the message says. You cannot use market orders on gate.io (not with the bot, not when trading manually in spot markets).
This is also covered in [the FAQ](https://www.freqtrade.io/en/stable/faq/#im-getting-the-exchange-xxx-does-not-support-market-orders-message-and-cannot-run-my-strategy).
