### ISSUE TITLE
New version of bot not generating buy

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#5876]
## Describe your environment

  * Operating system: Fedora 34
  * Python Version:  3.9
  * CCXT version: 1.60.68
  * Freqtrade Version: 2021.10 (docker), current (git)
  
## Your question

Hi,

I created some strategies and I am successfully running them on 2021.08 version bot. However, with 2021.10 they are not generating any buy orders in backtesting. I am trying both vanilla github current version and docker one. Also, the strategy executes in 1/10th of second so it's not doing really anything at all. And every strategy does that.

I have pretty much generic config file with minimal changes, see attached.

[config.json.txt](https://github.com/freqtrade/freqtrade/files/7512237/config.json.txt)

**Comment by moinonin** [comment]
The failure not to buy usually is an issue with the populate buy section of the strategy. The way you present some indicators might have changed between version. Other than that I don't see any problem in the config a part from the fact you are using 1 USD as the stake amount :dagger: which could be the actual problem. Try increasing it to around 16-17 if you are using binance as your exchange. I don't know about other exchanges.

**Comment by ghost** [comment]
Oh, thatks, that worked on 20 USDT :)
