### ISSUE TITLE
buy by Volume

### ISSUE THREAD

**Issue by mkdah90** [freqtrade/freqtrade#5877]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
thanks in advance for you help and rapid response 
I have a question,
I want it to buy if the "15m" volume more than last "1h candle" volume

let's say 14:00 "hour candle" showed 15 million volume
15:00 "15m candle" showed 6 million, 15:15 showed 8 million
15:30 showed 20 million

I want it to buy at 15:45 because last 15m volume was more than last hour candle (14:00-15:00) and not the last hour (14:30-15:30)

thanks again

**Comment by xmatthias** [comment]
You should be able to get to this by using [1h informative pairs](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs).
By merging this to the 15m candle, you get the 1h information available for each candle ... which allows you to directly compare volume with something around `dataframe['volume_1h'] > dataframe['volume']`.

The documentation also has a [full informative sample](https://www.freqtrade.io/en/stable/strategy-customization/#complete-data-provider-sample) a little lower on that page, which should help you get started.

**Comment by mkdah90** [comment]
I am sorry but it doesn't work for me

here is my code
---------------------
	# Optimal timeframe for the strategy
   	timeframe = '15m'

	def informative_pairs(self):

        # get access to all pairs available in whitelist.
        pairs = self.dp.current_volumepairlist()
        # Assign tf to each pair so they can be downloaded and cached for strategy.
        informative_pairs = [(pair, '1h') for pair in pairs]
        return informative_pairs
    
        def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:      
        """ Adds several different TA indicators to the given DataFrame
        """
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=6)

        dataframe['sma24'] = ta.SMA(dataframe, timeperiod = 24 )
        
        # Bollinger bands
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=3)
        dataframe['bb_upperband'] = bollinger['upper']

        return dataframe

 	def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        if not self.dp:
            # Don't do anything if DataProvider is not available.
            return dataframe

        inf_tf = '1h'
        # Get the informative pair
        informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf)
        # Get the 14 day rsi
        informative['rsi'] = ta.RSI(informative, timeperiod=14)
        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (
                (
                (dataframe['volume'] > dataframe['volume_1h'].shift(1)*2)&
                (dataframe['close'] > dataframe['open'])&
                (dataframe['volume'] > 0)  
                )
            ),
            'buy'
        ] = 1

        return dataframe

**Comment by mkdah90** [comment]
and another problem
I want it to lock the pair for x candles after sell, I know it has autolock for the same candle but I want it for next candles as well

**Comment by xmatthias** [comment]
Please read the documentation **carefully**, and try to follow it as well.

your return value for `informative_pairs` is clearly wrong (should be a tuple of pairs you need) ... 

**edit** on 2nd thought - your whole strategy seems to be a mess. You've got indentation errors, combined with duplicate method names ...

best use an editor (like vscode with python plugin) which will highlight simple syntax errors like this for you - as this is not something i'll provide support for via github issues.

**Comment by mkdah90** [comment]
the mess is because I tried the informative_pairs
the original strategy is here, I need to autolock pairs after sell

        def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:      
        """ Adds several different TA indicators to the given DataFrame
        """
       dataframe['sma24'] = ta.SMA(dataframe, timeperiod = 24 )
        
        # Bollinger bands
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=3)
        dataframe['bb_upperband'] = bollinger['upper']

        return dataframe
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (
                (
                (dataframe['volume'] > dataframe['volume'].shift(1)*3)&
                (dataframe['close'] > dataframe['open'])&
                (dataframe['close'] > dataframe['open'].shift(1))&
                (dataframe['close'] > dataframe['close'].shift(1))&
                (dataframe['close'].shift(1) > dataframe['sma24'].shift(1))&
                (dataframe['close'].shift(2) > dataframe['sma24'].shift(2))&
                (dataframe['close'].shift(3) > dataframe['sma24'].shift(3))&
                (dataframe['close'].shift(4) > dataframe['sma24'].shift(4))&
                (dataframe['close'].shift(5) > dataframe['sma24'].shift(5))&
                (dataframe['close'].shift(6) > dataframe['sma24'].shift(6))&
                (dataframe['close'].shift(7) > dataframe['sma24'].shift(7))&
                (dataframe['close'].shift(8) > dataframe['sma24'].shift(8))&
                (dataframe['volume'] > 0)  
                )
            ),
            'buy'
        ] = 1

        return dataframe
