### ISSUE TITLE
Problem with download-data from gate.io

### ISSUE THREAD

**Issue by tqdpham96** [freqtrade/freqtrade#5880]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.5
  * CCXT version: 1.59.2 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.10 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
First, thanks for a fantastic bot. I'm new here. 
I tried to download the data from gateio such as BTC/USDT. However, I received an error message, as shown in the picture below.

![image](https://user-images.githubusercontent.com/94131790/141345371-7c620478-56be-4fb6-8519-ee84a7d7bf89.png)

**Besides, the bot is able to download the data from other CEX, i.e., binance, bybit, etc.**
I used the following command to download the data, which is similar to the document from the website.

`docker-compose run --rm freqtrade download-data --exchange gateio --pairs BTC/USDT -t 30m`

I wonder how to deal with this error, or my region is restricted to gateio? Any suggestion is highly appreciated. Thank you for considering my question.

**Comment by xmatthias** [comment]
Seems like a rate-limit problem with gate.io at the moment.
you can set rate-limites manually as [documented here](https://www.freqtrade.io/en/stable/exchanges/#setting-rate-limits) for downloading data.

**edit** it's not rate-limit but a different problem. Investigating, but at the moment, you'll not be able to download from gateio.

**Comment by tqdpham96** [comment]
@xmatthias Yes, it is really weird. Others site works fine, only Gateio appears this problem. 
Thanks for answering my question. Can you notice me if you found that problem?.
I'm really appreciated your helping.

**Comment by xmatthias** [comment]
You can run `pip install -U ccxt` to get the latest ccxt version - with this version it'll work fine again.
