### ISSUE TITLE
accessing price which share bought

### ISSUE THREAD

**Issue by revelationsz** [freqtrade/freqtrade#5881]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
hopefully my title is clear enough, but is the a way to access the price the share of the coin was bought as to use in our sell method,
or is this currently not possible. Thanks you.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
you will not be able to access the trade object in `populate_sell_trend()` (not in backtesting, anyway) - but you'll be able to use it in strategy callbacks that provide the trade object - and can there access that price using `trade.open_rate`.
