### ISSUE TITLE
Default db directory for containers.

### ISSUE THREAD

**Issue by driv** [freqtrade/freqtrade#5882]
## Describe the enhancement

Currently if you don't define the db-url in the configuration you get:
```
sqlite:///tradesv3.sqlite` for Live Run mode, `sqlite:///tradesv3.dryrun.sqlite` for Dry Run)
```

Which is a useful feature since you can test in dry-run and afterwards just switch to `"dry-run": false` (or use the env var) and be sure that a different DB will be used.

The only problem is that when using the bot in a container you **can't** have the db in it's own volume without defining `--db-url` and losing the automatic "dryrun db switch".

Would it make sense to have a `--db-dir` parameter that defaults to `./`?

I guess changing the default directory to **not** be in the `./` dir would be too much of a breaking change.

**Comment by xmatthias** [comment]
that's a question one can debate for sure.

in principle, I'd like to have it default to `user_data/<whatever>.sqlite` (or even `user_data/db/*.sqlite` - as it's really user_data - however as you correctly point out - that'd be breaking - and in the worst possible manner, breaking for users who never took an explicit decision about it (or never learned how to configure a different database), and simply left it "default".

It might be possible to move some compatibility layer in between (basically moving the database file if it's found in cwd, and the db-url is not configured) ... but I'm not certain it justifies both the time investment and complexity (not for what it'll provide - read below).

For docker, you might be able to get around this by using variables (assuming you use docker compose) - so your settings happen in `.env` - and your compose-file then takes these, and switches the db file as desired.
It'll however not be this automatic.

You'll anyway be very limited with this "automatism" in the docker context - assuming you're testing 2 strategies (`Strat1` and `Strat2`) - both with the same compose file (as different services) - you'll most likely use the same user_data directory - which will require an explicit database configuration anyway (one that contains the strategy name, for example).
