### ISSUE TITLE
Include more details in _FILL telegram notifications

### ISSUE THREAD

**Issue by ethanopp** [freqtrade/freqtrade#5883]
## Describe the enhancement
When running strategies on market orders, slippage can occur, rendering all of the information in the buy/sell notifications inaccurate.

*Explain the enhancement you would like*
Please include the same information that is in the buy/sell order notifications in the buy/sell FILL notifications. This way user can see the **actual** profit %. It is not enough to only show the price the order was filled at, as user then needs to do math to calculate what the actual result is after slippage

Something along the lines of this:
🔵 Kucoin: **Filled Buy** OMG/USDT (#4)
Buy Tag: 46 
Amount: 63.89690000
Open Rate: 13.35900000
Current Rate: 14.35900000
Slippage: 1 (7.69%)
Total: (853.599 USDT, 853.599 USD)

✳ Kucoin: **Filled Sell** OMG/USDT (#4)
Profit: 4.85% (profit: 41.19867642 USDT / 41.199 USD)
Sell Reason: sell_profit_u_bear_4_1 ( 46 )
Duration: 0:09:28 (9.5 min)
Amount: 63.89690000
Open Rate: 13.28000000
Current Rate: 13.95200000
Close Rate: 13.95200000
Slippage: XX (x.x%)

**Comment by xmatthias** [comment]
Pull requests are welcome for this.
This shouldn't be too hard, either - and changes should be mostly limited to `telegram.py`.
