### ISSUE TITLE
The webapge for `Note for binance users` doesn't render properly and displays a 404

### ISSUE THREAD

**Issue by 1nF0rmed** [freqtrade/freqtrade#5886]
## Describe your environment

  * Operating system: Mac OS Big Sur
  * Python Version: NA
  * CCXT version: NA
  * Freqtrade Version: NA

## Describe the problem:

The page related to the issues with support for Binance platform provides a link that seems to be a not properly rendered page with a `404` message.

![image](https://user-images.githubusercontent.com/21278205/141646202-dec8acd1-f8ed-4216-834c-4f985c933a00.png)

### Steps to reproduce:

  1. Go to the freq tade [homepage](https://www.freqtrade.io/en/stable/)
  2. Scroll to the `Supported exchange marketplaces` section and click on the `Note for binance users` link
  3. This will take you to the following URL where the issue occurs: https://www.freqtrade.io/en/stable/docs/exchanges.md#binance-blacklist
  
### Observed Results:

  * What happened?
     Page does not render and displays a 404 at the bottom.
  * What did you expect to happen?
     Should display a page with details about the Binance blacklist details.

### Relevant code exceptions or logs

NA

**Comment by xmatthias** [comment]
Thanks for reporting. this has been fixed ~1 week ago in develop (you can check that out [here](https://www.freqtrade.io/en/latest/) - which will become stable with the next release.
