### ISSUE TITLE
Add positive percent change to dynamic whitelist

### ISSUE THREAD

**Issue by cofibit** [freqtrade/freqtrade#589]
The --dynamic-whitelist auto generates whitelist based on 24hr volume but is it possible to filter only those with positive net change? this is to avoid markets having large volume but are going down. Please see attached.

![screen shot 2018-03-28 at 8 08 17 am](https://user-images.githubusercontent.com/7797999/38001472-8dfb8fac-325f-11e8-9b7f-113d2d5f9c38.png)

**Comment by cofibit** [comment]
Wondering if this will suffice the enhancent.
```
def _gen_pair_whitelist(self, base_currency: str, key: str = 'BaseVolume') -> List[str]:
        """
        Updates the whitelist with with a dynamically generated list
        :param base_currency: base currency as str
        :param key: sort key (defaults to 'BaseVolume')
        :return: List of pairs
        """
        summaries = sorted(
            (s for s in exchange.get_market_summaries() if
             s['MarketName'].startswith(base_currency) and (((s['Last']/s['PrevDay'])/s['Last'])*100>3),
            key=lambda s: s.get(key) or 0.0,
            reverse=True
        )
 
        return [s['MarketName'].replace('-', '_') for s in summaries]
 
```

**Comment by sshchmod777** [comment]
hoping this can be implemented on latest freqtrade version

**Comment by jblestang** [comment]
Having this separate from buy/sell events might keep the strategy cleaner. By the way managing the list of coins is IMHo a different task from managing buy/sells events. They are certainly ways to keep a compatibility with already existing strategies by using the current existing way of selecting coins if no method to select the list of coins is given by the strategy.

**Comment by sshchmod777** [comment]
how can i insert it on the strategy? sorry, im not good in python.

**Comment by hashtagex** [comment]
Moving averages or trend indicators. Start off with that, this would get you going into weeding out some of those coins.

**Comment by Alocaly** [comment]
I'm not a huge fan of adding it to the bot.
It looks easy to do in the strat ( one liner, something like dataframe['close'].shift(12*24)< dataframe['close'] ).
and people that want to work on a strat that also works sideways or in bear trend wouldn't be affected.
