### ISSUE TITLE
Blacklist regex defined wrongly

### ISSUE THREAD

**Issue by zorann** [freqtrade/freqtrade#5903]
## Describe your environment

  * Operating system: ____Ubuntu
  * Python Version: _____2.7.18 (`python -V`)
  * CCXT version: _____1.56.30 (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____freqtrade docker-acb00cd0 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
Why do i get:
2021-11-15 09:12:32,621 - freqtrade.plugins.pairlistmanager - ERROR - Pair blacklist contains an invalid Wildcard: Wildcard error in *UP/USDT, nothing to repeat at position 0

My Blacklist is defined like:

        "pair_blacklist": [
			"TUSD/USDT",
			"CUSD/USDT",
			"BUSD/USDT",
			"USDP/USDT",
			"USDC/USDT",
			"SUSD/USDT",
			"*UP/USDT",
			"*DOWN/USDT",
			"EUR/USDT",
			"GBP/USDT",
			"AUD/USDT",
			"SLP/USDT",
            "BNB/BTC",
            "BNB/BUSD",
            "BNB/ETH",
            "BNB/EUR",
            "BNB/NGN",
            "BNB/PAX",
            "BNB/RUB",
            "BNB/TRY",
            "BNB/TUSD",
            "BNB/USDC",
            "BNB/USDS",
            "BNB/USDT",
        ]

Regards

**Comment by xmatthias** [comment]
`*UP/USDT` is not a valid regex.
What you want/need is `.*UP/USDT` (`.` is an "all" character, which is repeated).

By starting the regex with `*`, you're telling the regex to "repeat" - but there's nothing there to repeat, so it does not work.
