### ISSUE TITLE
A RULE IDEA FOR MAX_OPEN_TRADES

### ISSUE THREAD

**Issue by themiralay** [freqtrade/freqtrade#5904]
## Describe your environment
(if applicable)

  * Operating system: Windows 10 Pro 10.0.19043 Build 19043 (With Docker WSL 2)
  * Python Version: 3.7
  * Freqtrade Version: 2021.10

hello, I am actively working on developing my own strategy by using freqtrade. There are a few issues I would like to raise.

1. An Unlimited strategy sometimes opens multiple trades at once, and sometimes opens a single trade. It cannot be predicted how many trades will be opened in the future markets. So it might be better if we make the `max_open_trades` part reconfigurable ourselves according to a certain rule. For example, if `max_open_trades` is "four" at first, if any order comes within 5 minutes after the first buy order, it can be said to buy a quarter of the remaining three-unit slot. or when there are quick buy orders that will fill all the slots in a row, it may be nice to follow a way of placing a buy order for 1/2 of the remaining slots within x minutes after the first order.

2.  429 DDos Protection(IP Ban) Causes when multiple bots are run over a ip over Freqtrade. I can't get above a single bot on the Kucoin exchange. I have to use 3rd party proxy tools For example (binance-proxy by @abanchev). Can we integrate these proxy tools on Freqtrade in the future?

3.  There is a big difference between backtest and dry/live run. There are no lines in the strategy that contain tricks or predictions of the future, and even though I don't use trailing, it doesn't give much of an idea whether I should work on it. I usually only look at Avg profit and drawdown. I would like you to include the simple steps that can be done for freqtrade on freqtrade.io before going to the dry/live stage on backtest.

**Comment by xmatthias** [comment]
1) you can [control stake amount](https://www.freqtrade.io/en/stable/strategy-advanced/#stake-size-management) from within your strategy - so to be honest, i think you can handle this completely on your own from within the strategy, assuming you set max_open_trades high enough.

2) we're not going to hunt in other peoples repositories for pieces we can "steal" for freqtrade - even if it's been developed for freqtrade.
Should people decide to want to contribute things, we'll evaluate the contribution (either as issue proposing a future PR, or a Pull request itself) in both technical terms as well as if it makes sense to integrate it in a bigger perspective.
Kucoin specifically has an API problem currently which can also be trigger on a single bot. They promised a fix for last week - apparently that's not been delivered yet. 
While the errors are noisy, they can be ignored (subsequent retries always succeeded in my tests).

3) Both freqtrade and the documentation is open source. Feel free to contribute to the documentation what you think is missing.
Your text does not really point out what steps you'd like to see here ... so i'm not sure what you think should happen based on this.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
