### ISSUE TITLE
How to calculate moving average slope with ta.LINEARREG_ANGLE correctly?

### ISSUE THREAD

**Issue by Niqnil** [freqtrade/freqtrade#5905]
## Describe your environment

  * Operating system: Docker image: freqtradeorg/freqtrade:develop_plot
  * Python Version: Python 3.9.7
  * Freqtrade Version: freqtrade docker-63f4221f
  
## Your question

I am trying to use the slope of EMA to screen out trade entries but it seems the results using `ta.LINEARREG_ANGLE` are too sensitive.
Please see screenshot of plot where EMA slope is plotted at the bottom. [https://i.ibb.co/FqdWzKZ/image.png](url) It pretty much always jumps from extreme top to extreme bottom.

What is the correct way to calculate the slope of EMA for last value and second last value?
```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe['adx'] = ta.ADX(dataframe)
        dataframe['plus_di'] = ta.PLUS_DI(dataframe)
        dataframe['minus_di'] = ta.MINUS_DI(dataframe)
        dataframe['ema_fast'] = ta.EMA(dataframe, timeperiod=5)
        dataframe['ema_mid'] = ta.EMA(dataframe, timeperiod=15)
        dataframe['ema_slow'] = ta.EMA(dataframe, timeperiod=30)
        dataframe['sar'] = ta.SAR(dataframe)
        dataframe['rvwap'] = qtpylib.rolling_vwap(dataframe, window=50)

        dataframe['ema_fast_slope'] = ta.LINEARREG_ANGLE(dataframe['ema_fast'], timeperiod=2)
        dataframe['ema_mid_slope'] = ta.LINEARREG_ANGLE(dataframe['ema_mid'], timeperiod=2)

        return dataframe
```

**Comment by xmatthias** [comment]
purely from looking at the relevant [ta-lib docs](http://mrjbq7.github.io/ta-lib/func_groups/statistic_functions.html) - i'd probably go with `LINEARREG_SLOPE` ...

I've never used neither of the two, so i can't tell you for sure what you should expect to receive back. It's very well possible that a timeperiod of 2 is simply not enough value for the ta-lib functions - as a linear regression is usually trying to fit a line between all the points - and ta-lib is known to not handle certain edge-cases (like 2 points only) very well.

You should be able to calculate the slope of 2 points easily yourself by applying the Pythagorean theorem to the dataframe - using `.shift(1)` to get the value of the previous candle.

**Comment by Niqnil** [comment]
Actually I tried that before trying `LINEARREG_ANGLE` but got an error. 

```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        # ...
        dataframe['ema_fast'] = ta.EMA(dataframe, timeperiod=5)
        dataframe['ema_mid'] = ta.EMA(dataframe, timeperiod=15)
        dataframe['ema_slow'] = ta.EMA(dataframe, timeperiod=30)
        dataframe['ema_fast_slope'] = math.atan((dataframe['ema_fast'] - dataframe['ema_fast'].shift(1)) / 1) * 180 / math.pi
        dataframe['ema_mid_slope'] = math.atan((dataframe['ema_mid'] - dataframe['ema_mid'].shift(1)) / 1) * 180 / math.pi

        return dataframe
```

# Traceback
```
2021-11-16 02:29:02,273 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 54, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 670, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 625, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/freqtrade/freqtrade/strategy/interface.py", line 833, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 833, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 856, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/TripleMA.py", line 163, in populate_indicators
    dataframe['ema_fast_slope'] = math.atan((dataframe['ema_fast'] - dataframe['ema_fast'].shift(1)) / 1) * 180 / math.pi
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'float'>
```

# Shell run in docker container
```
ftuser@d4362f51e739:/freqtrade$ python
Python 3.9.7 (default, Oct 12 2021, 02:54:29) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import math
>>> ema_fast_slope = math.atan(123.4 - 101.1 / 1) * 180 / math.pi
>>> ema_fast_slope
87.43240267081222
>>> print(isinstance(ema_fast_slope, float))
True
```

**Comment by xmatthias** [comment]
well the 2 are clearly not the same - math assumes it receives a float, but you're passing in a series.

You should look if numpy has a similar method to apply it against a series.

**Comment by Niqnil** [comment]
Thanks for pointing that out. I feel stupid for not realising that I was trying to pass a series.

`dataframe['ema_fast_slope'] = np.arctan((dataframe['ema_fast'] - dataframe['ema_fast'].shift(1)) / 1) * 180 / np.pi` works although it still jumps from extreme top to extreme bottom.

`dataframe['ema_fast_roc'] = ta.ROC(dataframe['ema_fast'], timeperiod=1)` works better to produce a useable result.
