### ISSUE TITLE
backtesting  symbol results equal zero error 

### ISSUE THREAD

**Issue by tabwnymhmd** [freqtrade/freqtrade#5906]
## Describe your environment

  * Operating system: ____(Microsoft Windows [Version 10.0.19042.1237])
  * Python Version: ____(python 3.10.0 64 bit)
  * Freqtrade Version: ____ (`freqtrade 2021/10)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**hello 
I have a problem when I backtested my strategy the symbol results equal zero. why?
but when I tested my strategy on the dry mode it was worked without any problem**

**testing result**

> 
Microsoft Windows [Version 10.0.19042.1237]
(c) Microsoft Corporation. All rights reserved.

C:\Users\tabwn>cd ft_userdata/

C:\Users\tabwn\ft_userdata>docker-compose run freqtrade backtesting --datadir user_data/data/binance --export trades --stake-amount 1000 -s SmaStrategy -i 1h
Creating ft_userdata_freqtrade_run ... done
2021-11-15 09:41:36,336 - freqtrade.configuration.configuration - INFO - Using config: user_data/config.json ...
2021-11-15 09:41:36,342 - freqtrade.loggers - INFO - Verbosity set to 0
2021-11-15 09:41:36,342 - freqtrade.configuration.configuration - INFO - Parameter -i/--timeframe detected ... Using timeframe: 1h ...
2021-11-15 09:41:36,342 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2021-11-15 09:41:36,342 - freqtrade.configuration.configuration - INFO - Parameter --stake-amount detected, overriding stake_amount to: 1000.0 ...
2021-11-15 09:41:36,677 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2021-11-15 09:41:36,680 - freqtrade.configuration.configuration - INFO - Using data directory: user_data/data/binance ...
2021-11-15 09:41:36,680 - freqtrade.configuration.configuration - INFO - Overriding timeframe with Command line argument
2021-11-15 09:41:36,681 - freqtrade.configuration.configuration - INFO - Parameter --export detected: trades ...
2021-11-15 09:41:36,681 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-11-15 09:41:36,705 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-11-15 09:41:36,705 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-11-15 09:41:36,706 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-11-15 09:41:36,717 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2021-11-15 09:41:36,717 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-11-15 09:41:36,717 - freqtrade.exchange.exchange - INFO - Using CCXT 1.59.2
2021-11-15 09:41:36,761 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-11-15 09:41:38,828 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-11-15 09:41:38,891 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SmaStrategy from '/freqtrade/user_data/strategies/sma_strategy.py'...
2021-11-15 09:41:38,893 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2021-11-15 09:41:38,893 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2021-11-15 09:41:38,894 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2021-11-15 09:41:38,895 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2021-11-15 09:41:38,896 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 1h.
2021-11-15 09:41:38,896 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2021-11-15 09:41:38,896 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 1000.0.
2021-11-15 09:41:38,896 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30, 'unit': 'minutes'}.
2021-11-15 09:41:38,896 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2021-11-15 09:41:38,896 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1h
2021-11-15 09:41:38,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.2
2021-11-15 09:41:38,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2021-11-15 09:41:38,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2021-11-15 09:41:38,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2021-11-15 09:41:38,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2021-11-15 09:41:38,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-11-15 09:41:38,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2021-11-15 09:41:38,897 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-11-15 09:41:38,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2021-11-15 09:41:38,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 1000.0
2021-11-15 09:41:38,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2021-11-15 09:41:38,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2021-11-15 09:41:38,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30, 'unit': 'minutes'}
2021-11-15 09:41:38,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-11-15 09:41:38,898 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2021-11-15 09:41:38,899 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2021-11-15 09:41:38,899 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
2021-11-15 09:41:38,899 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-11-15 09:41:38,899 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2021-11-15 09:41:38,899 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-11-15 09:41:38,912 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2021-11-15 09:41:39,613 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 30 ...
2021-11-15 09:41:47,146 - freqtrade.optimize.backtesting - INFO - Loading data from 2021-10-15 22:00:00 up to 2021-11-14 19:00:00 (29 days).
2021-11-15 09:41:47,146 - freqtrade.configuration.timerange - WARNING - Moving start-date by 30 candles to account for startup time.
2021-11-15 09:41:47,147 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2021-11-15 09:41:47,148 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy SmaStrategy
2021-11-15 09:41:47,771 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2021-10-17 04:00:00 up to 2021-11-14 19:00:00 (28 days).
2021-11-15 09:41:51,164 - freqtrade.misc - INFO - dumping json to "/freqtrade/user_data/backtest_results/backtest-result-2021-11-15_09-41-51.json"
2021-11-15 09:41:51,171 - freqtrade.misc - INFO - dumping json to "/freqtrade/user_data/backtest_results/.last_result.json"
Result for strategy SmaStrategy
=========================================================== BACKTESTING REPORT ===========================================================
|        Pair |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
|-------------+--------+----------------+----------------+-------------------+----------------+----------------+-------------------------|
|    ACM/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ADA/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   AION/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   ALGO/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|  ALICE/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   ANKR/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ANT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   ARDR/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   ARPA/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|     AR/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ASR/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ATA/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ATM/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   ATOM/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   AUTO/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    AVA/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   AVAX/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    AXS/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ADX/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   BAND/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    BAR/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    BAT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    BCH/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    BLZ/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    BTC/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    BTG/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    BTT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   CELO/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   CELR/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    CFX/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    CHR/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    CHZ/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    CKB/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|  COCOS/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    COS/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   COTI/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    CTK/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   CTSI/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   CTXC/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    CVC/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    CVP/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   DASH/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   DATA/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    DCR/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   DEGO/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   DENT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    DGB/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    DIA/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    DNT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   DOCK/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   DOGE/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    DOT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   DREP/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   DUSK/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   EGLD/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ELF/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ENJ/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    EOS/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ERN/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ETC/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ETH/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    FET/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    FIL/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    FIO/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   FIRO/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   FLOW/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|  FORTH/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    FTM/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   GALA/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    GBP/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    GRT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    GTC/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    GTO/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    GXS/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   HBAR/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   HIVE/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    HNT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    HOT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ICP/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ICX/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   IOST/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   IOTA/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   IOTX/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   IRIS/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   KEEP/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    KEY/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   KLAY/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    KMD/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    KSM/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   LINA/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   LINK/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    LIT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    LSK/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    LTC/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    LTO/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   LUNA/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   MANA/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   MASK/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|  MATIC/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    MDT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    MDX/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   MINA/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   MITH/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    MTL/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   NANO/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   NEAR/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    NEO/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    NKN/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    NMR/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   NULS/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|     NU/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|  OCEAN/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    OGN/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|     OG/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    OMG/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ONE/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ONG/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ONT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    OXT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   PAXG/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    PHA/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    PNT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   POLY/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   POND/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    PSG/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
| PUNDIX/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    QNT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   QTUM/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    REQ/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    RIF/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    RLC/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    RSR/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    RVN/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   SAND/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|     SC/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    SFP/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    SKL/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    SLP/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    SOL/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   STMX/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|  STORJ/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   STPT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|  STRAX/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    STX/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    SXP/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    SYS/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    TCT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|  TFUEL/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|  THETA/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    TLM/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   TOMO/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    TRB/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|  TRIBE/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    TRX/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    TVK/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    TWT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    UTK/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    VET/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   VIDT/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   VITE/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   VTHO/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    WAN/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|  WAVES/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   WAXP/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    WRX/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    WTC/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|   WNXM/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    XEM/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    XEC/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    XLM/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    XMR/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    XRP/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    XTZ/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    XVG/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    YGG/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ZEC/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ZEN/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ZIL/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    ZRX/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|       TOTAL |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
===================================================== SELL REASON STATS =====================================================
|   Sell Reason |   Sells |   Win  Draws  Loss  Win% |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |
|---------------+---------+--------------------------+----------------+----------------+-------------------+----------------|
====================================================== LEFT OPEN TRADES REPORT ======================================================
|   Pair |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
|--------+--------+----------------+----------------+-------------------+----------------+----------------+-------------------------|
|  TOTAL |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
==================================== SUMMARY METRICS =====================================
No trades made. Your starting balance was 1000.000 USDT, and your stake was 1000.000 USDT. ==========================================================================================
>

**Comment by xmatthias** [comment]
> No trades made. Your starting balance was 1000.000 USDT, and your stake was 1000.000 USDT. 

Your configuration does not make sense - you're configuring a stake_amount of 1000$ - but with 10 open trades (`max_open_trades=10`).
Based on this, your dry-run-wallet should be configured to 10.000$ (10 x 1000$).

It'd still work (roughly) fine with 1000$(it'd simply start with 1 open trade) - but `tradable_balance_ratio` (defaulting to 99%) will reduce your available capital to 990$ to start with - causing your backtest to never have enough capital available to enter even one trade.

These parameters all need to align to make sense (especially `max_open_trades`, `stake_amount` and `dry_run_wallet`).

**Comment by tabwnymhmd** [comment]
Thank you for helping it was worked
