### ISSUE TITLE
create a strategy hyperopt file error 

### ISSUE THREAD

**Issue by tabwnymhmd** [freqtrade/freqtrade#5907]
## Describe your environment

  * Operating system: ____(Microsoft Windows [Version 10.0.19042.1348])
  * Python Version: _____ (`python -3.10.0 64 bit`)
  * Freqtrade Version: ____ (`freqtrade -2021/10`)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

** hello 
I have a problem when I'm trying to create a strategy hyperopt file I got an error. why?**

>
Microsoft Windows [Version 10.0.19042.1348]
(c) Microsoft Corporation. All rights reserved.

C:\Users\tabwn>cd ft_userdata/

C:\Users\tabwn\ft_userdata>docker-compose run freqtrade new-hyperopt --hyperopt SMAHyperopt
Creating ft_userdata_freqtrade_run ... done
usage: freqtrade [-h] [-V]
                 {trade,create-userdir,new-config,new-strategy,download-data,convert-data,convert-trade-data,trades-to-ohlcv,list-data,backtesting,backtesting-show,edge,hyperopt,hyperopt-list,hyperopt-show,list-exchanges,list-markets,list-pairs,list-strategies,list-timeframes,show-trades,test-pairlist,install-ui,plot-dataframe,plot-profit,webserver}
                 ...
freqtrade: error: argument command: invalid choice: 'new-hyperopt' (choose from 'trade', 'create-userdir', 'new-config', 'new-strategy', 'download-data', 'convert-data', 'convert-trade-data', 'trades-to-ohlcv', 'list-data', 'backtesting', 'backtesting-show', 'edge', 'hyperopt', 'hyperopt-list', 'hyperopt-show', 'list-exchanges', 'list-markets', 'list-pairs', 'list-strategies', 'list-timeframes', 'show-trades', 'test-pairlist', 'install-ui', 'plot-dataframe', 'plot-profit', 'webserver')
ERROR: 2

**Comment by xmatthias** [comment]
Freqtrade now uses Strategy parameters, which allow the same thing than hyperopt files, but in one file (no conversion problems) - and a simpler interface.

We therefore removed support for separate hyperopt files a few versions ago. 
`new-hyperopt` has therefore become obsolete, and will no longer be supported.

Best read the [hyperopt documentation](https://www.freqtrade.io/en/stable/hyperopt/) to learn how to create a parametrized strategy.
