### ISSUE TITLE
WARNING - Could not import /root/freqtrade/user_data/strategies/sh001.py due to 'cannot import name 'BooleanParameter' from 'freqtrade.strategy'

### ISSUE THREAD

**Issue by straj-granicy** [freqtrade/freqtrade#5908]
## Describe your environment

  * Operating system: Ubuntu 21.04.
  * Python Version: Python 3.9.5
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2021.7 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
Hi,
I'm trying to use hyperoptable parameters in strategy.
The code is the following:

`from pandas import DataFrame
from functools import reduce

import talib.abstract as ta

from freqtrade.strategy import (BooleanParameter, CategoricalParameter, DecimalParameter, 
                                IStrategy, IntParameter)
import freqtrade.vendor.qtpylib.indicators as qtpylib

# This class is a sample. Feel free to customize it.
class SH001(IStrategy):

    INTERFACE_VERSION = 2

    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi".
    minimal_roi = {
        "60": 0.01,
        "30": 0.02,
        "0": 0.04
    }

    # Optimal stoploss designed for the strategy.
    # This attribute will be overridden if the config file contains "stoploss".
    stoploss = -0.10

    # Trailing stoploss
    trailing_stop = False
    # trailing_only_offset_is_reached = False
    # trailing_stop_positive = 0.01
    # trailing_stop_positive_offset = 0.0  # Disabled / not configured

    #Optimal timeframe for the strategy.
    timeframe = '1m'

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = False

    # These values can be overridden in the "ask_strategy" section in the config.
    use_sell_signal = True
    sell_profit_only = False
    ignore_roi_if_buy_signal = False

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 30

    # Optional order type mapping.
    order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }

    # Optional order time in force.
    order_time_in_force = {
        'buy': 'gtc',
        'sell': 'gtc'
    }

    plot_config = {
        'main_plot': {
            'tema': {},
            'sar': {'color': 'white'},
        },
        'subplots': {
            "MACD": {
                'macd': {'color': 'blue'},
                'macdsignal': {'color': 'orange'},
            },
            "RSI": {
                'rsi': {'color': 'red'},
            }
        }
    }

     
    
    
    def informative_pairs(self):
        """
        Define additional, informative pair/interval combinations to be cached from the exchange.
        These pair/interval combinations are non-tradeable, unless they are part
        of the whitelist as well.
        For more information, please consult the documentation
        :return: List of tuples in the format (pair, interval)
            Sample: return [("ETH/USDT", "5m"),
                            ("BTC/USDT", "15m"),
                            ]
        """
        return []
        
        #hyperoptable parameters

    #BUY PARAMETERS

    buy_adx = IntParameter(20, 40, default=30, space="buy") #ADX
    buy_fastd = IntParameter(15, 45, default=30, space='buy') # Stochastic Fast
    buy_fastk = IntParameter(15, 45, default=26, space='buy') # Stochastic Fast
    buy_rsi = IntParameter(10, 60, default=30, space='buy') #RSI
    buy_cci = IntParameter(-100, -200, default=-183, space='sell') #CCI
    buy_trigger = CategoricalParameter(["macd_cross_signal","tr_bb_lower_1sd", "tr_bb_lower_2sd", "tr_bb_lower_3sd", "tr_bb_lower_4sd", "ao"], default="bb_lower", space="buy")

    buy_adx_enabled = BooleanParameter(default=True, space='buy') #ADX
    buy_fastd_enabled = BooleanParameter(default=True, space='buy') # Stochastic Fast
    buy_rsi_enabled = BooleanParameter(default=False, space='buy') #RSI
    buy_cci_enabled = BooleanParameter(default=True, space='buy') #CCI

    #SELL PARAMETERS

    sell_adx = IntParameter(50, 100, default=53, space='sell')#ADX
    sell_cci = IntParameter(100, 200, default=183, space='sell')#CCI
    sell_fastd = IntParameter(50, 100, default=79, space='sell')# Stochastic Fast
    sell_fastk = IntParameter(50, 100, default=70, space='sell')# Stochastic Fast
    sell_rsi = IntParameter(60, 100, default=70, space='sell') #RSI

    sell_adx_enabled = BooleanParameter(default=False, space='sell') #ADX
    sell_cci_enabled = BooleanParameter(default=True, space='sell') #CCI
    sell_fastd_enabled = BooleanParameter(default=True, space='sell') # Stochastic Fast
    sell_fastk_enabled = BooleanParameter(default=True, space='sell') # Stochastic Fast
    sell_rsi_enabled = BooleanParameter(default=True, space='sell') #RSI
   

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Adds several different TA indicators to the given DataFrame
        Performance Note: For the best performance be frugal on the number of indicators
        you are using. Let uncomment only the indicator you are using in your strategies
        or your hyperopt configuration, otherwise you will waste your memory and CPU usage.
        :param dataframe: Dataframe with data from the exchange
        :param metadata: Additional information, like the currently traded pair
        :return: a Dataframe with all mandatory indicators for the strategies
        """

        # Momentum Indicators
        # ------------------------------------

        # ADX
        dataframe['adx'] = ta.ADX(dataframe, timeperiod=14)

        # # Plus Directional Indicator / Movement
        dataframe['plus_dm'] = ta.PLUS_DM(dataframe)
        dataframe['plus_di'] = ta.PLUS_DI(dataframe, timeperiod=25)

        # # Minus Directional Indicator / Movement
        dataframe['minus_dm'] = ta.MINUS_DM(dataframe)
        dataframe['minus_di'] = ta.MINUS_DI(dataframe, timeperiod=25)

        # Awesome Oscillator
        dataframe['ao'] = qtpylib.awesome_oscillator(dataframe)

        # Commodity Channel Index: values [Oversold:-100, Overbought:100]
        dataframe['cci'] = ta.CCI(dataframe)

        # RSI
        dataframe['rsi'] = ta.RSI(dataframe)

        # Stochastic Slow
        stoch = ta.STOCH(dataframe)
        dataframe['slowd'] = stoch['slowd']
        dataframe['slowk'] = stoch['slowk']

        # Stochastic Fast
        stoch_fast = ta.STOCHF(dataframe)
        dataframe['fastd'] = stoch_fast['fastd']
        dataframe['fastk'] = stoch_fast['fastk']

        # # Stochastic RSI
        # Please read https://github.com/freqtrade/freqtrade/issues/2961 before using this.
        # STOCHRSI is NOT aligned with tradingview, which may result in non-expected results.
        # stoch_rsi = ta.STOCHRSI(dataframe)
        # dataframe['fastd_rsi'] = stoch_rsi['fastd']
        # dataframe['fastk_rsi'] = stoch_rsi['fastk']

        # MACD
        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        dataframe['macdhist'] = macd['macdhist']

        # MFI
        dataframe['mfi'] = ta.MFI(dataframe)

        # # ROC
        # dataframe['roc'] = ta.ROC(dataframe)

        # Overlap Studies
        # ------------------------------------

        # Bollinger Bands
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband'] = bollinger['lower']
        dataframe['bb_middleband'] = bollinger['mid']
        dataframe['bb_upperband'] = bollinger['upper']
        dataframe["bb_percent"] = (
            (dataframe["close"] - dataframe["bb_lowerband"]) /
            (dataframe["bb_upperband"] - dataframe["bb_lowerband"])
        )
        dataframe["bb_width"] = (
            (dataframe["bb_upperband"] - dataframe["bb_lowerband"]) / dataframe["bb_middleband"]
        )

        # Bollinger Bands - Weighted (EMA based instead of SMA)
        # weighted_bollinger = qtpylib.weighted_bollinger_bands(
        #     qtpylib.typical_price(dataframe), window=20, stds=2
        # )
        # dataframe["wbb_upperband"] = weighted_bollinger["upper"]
        # dataframe["wbb_lowerband"] = weighted_bollinger["lower"]
        # dataframe["wbb_middleband"] = weighted_bollinger["mid"]
        # dataframe["wbb_percent"] = (
        #     (dataframe["close"] - dataframe["wbb_lowerband"]) /
        #     (dataframe["wbb_upperband"] - dataframe["wbb_lowerband"])
        # )
        # dataframe["wbb_width"] = (
        #     (dataframe["wbb_upperband"] - dataframe["wbb_lowerband"]) /
        #     dataframe["wbb_middleband"]
        # )

        # # EMA - Exponential Moving Average
        # dataframe['ema3'] = ta.EMA(dataframe, timeperiod=3)
        # dataframe['ema5'] = ta.EMA(dataframe, timeperiod=5)
        # dataframe['ema10'] = ta.EMA(dataframe, timeperiod=10)
        # dataframe['ema21'] = ta.EMA(dataframe, timeperiod=21)
        # dataframe['ema50'] = ta.EMA(dataframe, timeperiod=50)
        # dataframe['ema100'] = ta.EMA(dataframe, timeperiod=100)

        # # SMA - Simple Moving Average
        # dataframe['sma3'] = ta.SMA(dataframe, timeperiod=3)
        # dataframe['sma5'] = ta.SMA(dataframe, timeperiod=5)
        # dataframe['sma10'] = ta.SMA(dataframe, timeperiod=10)
        # dataframe['sma21'] = ta.SMA(dataframe, timeperiod=21)
        # dataframe['sma50'] = ta.SMA(dataframe, timeperiod=50)
        # dataframe['sma100'] = ta.SMA(dataframe, timeperiod=100)

        # Parabolic SAR
        dataframe['sar'] = ta.SAR(dataframe)

        # TEMA - Triple Exponential Moving Average
        dataframe['tema'] = ta.TEMA(dataframe, timeperiod=9)
        dataframe['tema5'] = ta.TEMA(dataframe, timeperiod=5)
        dataframe['tema20'] = ta.TEMA(dataframe, timeperiod=20)

        # Cycle Indicator
        # ------------------------------------
        # Hilbert Transform Indicator - SineWave
        hilbert = ta.HT_SINE(dataframe)
        dataframe['htsine'] = hilbert['sine']
        dataframe['htleadsine'] = hilbert['leadsine']

        # Pattern Recognition - Bullish candlestick patterns
        # ------------------------------------
        # # Hammer: values [0, 100]
        # dataframe['CDLHAMMER'] = ta.CDLHAMMER(dataframe)
        # # Inverted Hammer: values [0, 100]
        # dataframe['CDLINVERTEDHAMMER'] = ta.CDLINVERTEDHAMMER(dataframe)
        # # Dragonfly Doji: values [0, 100]
        # dataframe['CDLDRAGONFLYDOJI'] = ta.CDLDRAGONFLYDOJI(dataframe)
        # # Piercing Line: values [0, 100]
        # dataframe['CDLPIERCING'] = ta.CDLPIERCING(dataframe) # values [0, 100]
        # # Morningstar: values [0, 100]
        # dataframe['CDLMORNINGSTAR'] = ta.CDLMORNINGSTAR(dataframe) # values [0, 100]
        # # Three White Soldiers: values [0, 100]
        # dataframe['CDL3WHITESOLDIERS'] = ta.CDL3WHITESOLDIERS(dataframe) # values [0, 100]

        # Pattern Recognition - Bearish candlestick patterns
        # ------------------------------------
        # # Hanging Man: values [0, 100]
        # dataframe['CDLHANGINGMAN'] = ta.CDLHANGINGMAN(dataframe)
        # # Shooting Star: values [0, 100]
        # dataframe['CDLSHOOTINGSTAR'] = ta.CDLSHOOTINGSTAR(dataframe)
        # # Gravestone Doji: values [0, 100]
        # dataframe['CDLGRAVESTONEDOJI'] = ta.CDLGRAVESTONEDOJI(dataframe)
        # # Dark Cloud Cover: values [0, 100]
        # dataframe['CDLDARKCLOUDCOVER'] = ta.CDLDARKCLOUDCOVER(dataframe)
        # # Evening Doji Star: values [0, 100]
        # dataframe['CDLEVENINGDOJISTAR'] = ta.CDLEVENINGDOJISTAR(dataframe)
        # # Evening Star: values [0, 100]
        # dataframe['CDLEVENINGSTAR'] = ta.CDLEVENINGSTAR(dataframe)

        # Pattern Recognition - Bullish/Bearish candlestick patterns
        # ------------------------------------
        # # Three Line Strike: values [0, -100, 100]
        # dataframe['CDL3LINESTRIKE'] = ta.CDL3LINESTRIKE(dataframe)
        # # Spinning Top: values [0, -100, 100]
        # dataframe['CDLSPINNINGTOP'] = ta.CDLSPINNINGTOP(dataframe) # values [0, -100, 100]
        # # Engulfing: values [0, -100, 100]
        # dataframe['CDLENGULFING'] = ta.CDLENGULFING(dataframe) # values [0, -100, 100]
        # # Harami: values [0, -100, 100]
        # dataframe['CDLHARAMI'] = ta.CDLHARAMI(dataframe) # values [0, -100, 100]
        # # Three Outside Up/Down: values [0, -100, 100]
        # dataframe['CDL3OUTSIDE'] = ta.CDL3OUTSIDE(dataframe) # values [0, -100, 100]
        # # Three Inside Up/Down: values [0, -100, 100]
        # dataframe['CDL3INSIDE'] = ta.CDL3INSIDE(dataframe) # values [0, -100, 100]

        # # Chart type
        # # ------------------------------------
        # # Heikin Ashi Strategy
        # heikinashi = qtpylib.heikinashi(dataframe)
        # dataframe['ha_open'] = heikinashi['open']
        # dataframe['ha_close'] = heikinashi['close']
        # dataframe['ha_high'] = heikinashi['high']
        # dataframe['ha_low'] = heikinashi['low']

        # Retrieve best bid and best ask from the orderbook
        # ------------------------------------
        """
        # first check if dataprovider is available
        if self.dp:
            if self.dp.runmode.value in ('live', 'dry_run'):
                ob = self.dp.orderbook(metadata['pair'], 1)
                dataframe['best_bid'] = ob['bids'][0][0]
                dataframe['best_ask'] = ob['asks'][0][0]
        """

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        conditions = []

        
            
        #GUARDS & TRENDS
        # Fast TEMA crossed slow TEMA
        # (qtpylib.crossed_above(dataframe['tema5'], dataframe['tema20'])) &
        if self.buy_fastd_enabled.value:
            conditions.append(dataframe['fastd'] < self.buy_fastd.value)
        if self.buy_fastk_enabled.value:
            conditions.append(dataframe['fastk'] < self.buy_fastk.value)
        if self.buy_adx_enabled.value:
            conditions.append(dataframe['adx'] > self.buy_adx.value)
        if self.buy_cci_enabled.value:
            conditions.append(dataframe['cci'] < self.buy_cci.value)
        if self.buy_rsi_enabled.value:
            onditions.append(dataframe['rsi'] > self.buy_rsi.value)
        #TRIGGERS
        if 'buy-trigger' in params:
            if params['buy-trigger'] == 'tr_bb_lower_1sd':
                conditions.append(dataframe['close'] < dataframe['bb_lowerband_1sd'])
            if params['buy-trigger'] == 'tr_bb_lower_2sd':
                conditions.append(dataframe['close'] < dataframe['bb_lowerband_2sd'])
            if params['buy-trigger'] == 'tr_bb_lower_4sd':
                conditions.append(dataframe['close'] < dataframe['bb_lowerband_4sd'])
            if params['buy-trigger'] == 'ao':
                conditions.append(dataframe['ao'] > 0)                                   
                   # Check that volume is not 0
            conditions.append(dataframe['volume'] > 0)

        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
                'buy'] = 1

        return dataframe

        
           

        

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        conditions = []

        
            
        #GUARDS & TRENDS
        # Fast TEMA crossed slow TEMA
        # (qtpylib.crossed_above(dataframe['tema5'], dataframe['tema20'])) &
        if self.buy_fastd_enabled.value:
            conditions.append(dataframe['fastd'] > self.sell_fastd.value)
        if self.buy_fastk_enabled.value:
            conditions.append(dataframe['fastk'] > self.sell_fastk.value)
        if self.buy_adx_enabled.value:
            conditions.append(dataframe['adx'] < self.sell_adx.value)
        if self.buy_cci_enabled.value:
            conditions.append(dataframe['cci'] > self.sell_cci.value)
        if self.buy_rsi_enabled.value:
            onditions.append(dataframe['rsi'] < self.sell_rsi.value)
        #TRIGGERS
        if 'sell-trigger' in params:
            if params['sell-trigger'] == 'tr_bb_lower_1sd':
                conditions.append(dataframe['close'] > dataframe['bb_lowerband_1sd'])
            if params['sell-trigger'] == 'tr_bb_lower_2sd':
                conditions.append(dataframe['close'] > dataframe['bb_lowerband_2sd'])
            if params['sell-trigger'] == 'tr_bb_lower_4sd':
                conditions.append(dataframe['close'] > dataframe['bb_lowerband_4sd'])
            if params['sell-trigger'] == 'ao':
                conditions.append(dataframe['ao'] < 0)                                   
                   # Check that volume is not 0
            conditions.append(dataframe['volume'] > 0)

        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
                'sell'] = 1

        return dataframe
        
  But it while I try to run the strategy or hyperopt in terminal it shows me the following error
 
WARNING - Could not import /root/freqtrade/user_data/strategies/sh001.py due to 'cannot import name 'BooleanParameter' from 'freqtrade.strategy'

But it seems to me that I'm importing BooleanParameter in this line
from freqtrade.strategy import (BooleanParameter, CategoricalParameter, DecimalParameter, 
                                IStrategy, IntParameter)

What could be the issue?

Thanks for any comments.
               
                
`

**Comment by xmatthias** [comment]
Booleanparameter was introduced in 2021.8. As you're using 2021.7 - it'll not be available.
Best update to the latest version (2021.10 at the time of writing) and the import should work fine.

**Comment by straj-granicy** [comment]
Hi. Thanks for feedback.
I tried to update freqtrade using
./setup.sh --update
Everything went fine, but it uninstalled version 2021.7 and installed it again.

Attempting uninstall: freqtrade
    Found existing installation: freqtrade 2021.7
    Uninstalling freqtrade-2021.7:
      Successfully uninstalled freqtrade-2021.7
  Running setup.py develop for freqtrade
Successfully installed freqtrade-2021.7
pip install completed

Checking the version of freqtrade with freqtrade-V and it also shows me the previous version.

**Comment by xmatthias** [comment]
you will need to run a `git pull` first - to pull the latest version i assume.
