### ISSUE TITLE
Startegy version

### ISSUE THREAD

**Issue by yoori85** [freqtrade/freqtrade#5909]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

I looked through the issues, but didn't find anything like it.

It would be nice to have  STRATEGY_VERSION in Strategy class. That version would show up in logs and freqUI.
It could be added to backtest results for easy comparison, etc.

Recently while working on my strategy and maintaining NFI live bot, I noticed that when updating strategy to a newer version and reloading config, I have no visual confirmation that the bot is running the new version. 

I can of course add the version in the comment to check if the file is updated and fully restart the bot to make sure it run the new file. 
But it would still be nice to be able see which version is runnning and possibly use it some data processing  / analysis.

**Comment by xmatthias** [comment]
In general, I'd suggest using `<strategyname>v1` (and also a different file) for this - that way you can use backtesting against both strategies at the same time, to get proper comparability.

I do however judge this as a mostly useless "feature" almost no-one would use - as in 99% of the cases, you'll forget to increment the version number anyway - so you'd only "update" it with the 2nd restart to be sure it's the new strategy.

It would also only have informative character - so freqtrade would still treat it as the same strategy. This has technical reasons, as the class-name must be unique - and we cannot go on random other features to determine the correct class to load - which will make it mostly useless for backtesting.

Also, to archive comparability with older backtest results you'll need the strategy content as well - which you'd have overwritten if you always use the same file. Without that, you'd compare V2 with V4 ... but what exactly changed is up to your memory - and therefore might not be 100% accurate (at least mine would not be).
While you can mitigate this with proper usage of git to some extend, you'll not have the backtest comparability - as you'll only have one strategy version available - not both.

**Comment by yoori85** [comment]
Perhaps you're right, this feature has not much value. I'l figure something out for my purposes. I have some ideas already. 

Thanks for taking the time to respond. If you're thinking this has no future than please close the issue. If you're open to strategy management changes than please leave it open and I'll come back if/when I have more defined idea and some code behind it.

**Comment by xmatthias** [comment]
It depends what you think about when saying "strategy management changes" ...

your proposal was to add a variable / property - which will be shown in the logs and is available to freqUI.
that's not strategy management, at maximum it's strategy versioning ... but even there you'll encounter shortfalls (see above) - where usability of it will be very limited.

to me, that's got nothing to do with "strategy management" - it's simply a variable that's shown "someplace". It can be informative - but nothing more.
You can probably even work around this at this moment with a strategy parameter (set load and optimize to false) - and increment that manually.
IIRC, this should be logged as well ... :)
