### ISSUE TITLE
docker-compose.yml download ERROR

### ISSUE THREAD

**Issue by suhail1142r** [freqtrade/freqtrade#5910]
## Describe your environment

  * Operating system: ____Microsoft Windows [Version 10.0.19043.1348]
  * Python Version: _____ (`python -3.10.0`)
  * Freqtrade Version: ____ (`2021.10)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
**hello**
**when I'm trying to download (docker-compose.yml), I got an error what is the problem ?**

>
Microsoft Windows [Version 10.0.19043.1348]
(c) Microsoft Corporation. All rights reserved.

C:\Users\NADawa15June14>cd C:\Users\NADawa15June14\Desktop\freqtrade_bot\ft_userdata

C:\Users\NADawa15June14\Desktop\freqtrade_bot\ft_userdata>curl https://raw.githubusercontent.com/freqtrade/freqtrade/stable/docker-compose.yml -o docker-compose.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

C:\Users\NADawa15June14\Desktop\freqtrade_bot\ft_userdata>docker-compose pull
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml
>

**Comment by xmatthias** [comment]
well your curl command fails ... 
that's a system configuration problem - nothing we can help you with, really.

you can work around that pretty easily by simply downloading the file directly (and storing it as `docker-compose.yml`), and then continue as documented.

**Comment by suhail1142r** [comment]
Thanks for helping
