### ISSUE TITLE
Why is the indicators time out of phase with candles time?

### ISSUE THREAD

**Issue by gdominoni** [freqtrade/freqtrade#5911]
* Operating system: ubuntu 
  * Python Version: 3.8
  * CCXT version: 1.59.2
  * Freqtrade Version: 2021.10
  
First of all I would like to point out that the OS time zones are properly set for Tradingview and Ubuntu.

Check this out, and pay attention to the selected green candle (it is at 21:00), and the position of the upper BB and macd.
![Screenshot from 2021-11-16 21-22-57](https://user-images.githubusercontent.com/24521096/142051870-2f63a1c8-0cc8-4059-8a97-44b461327c39.png)

And now check this from Tradingview:
![Screenshot from 2021-11-16 21-13-04](https://user-images.githubusercontent.com/24521096/142050406-2ab78fdc-d3e3-4c5b-837f-f141ffc4a20c.png)
As you can see, the same green candle is now set at 23:00, while the position of the indicators (BB and Macd) seem to be in line with the ones in the plotting...

What has happened? Why are they out of phase?

Here is my strategy:
```
`import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame

from datetime import datetime

from freqtrade.strategy import (BooleanParameter, CategoricalParameter, DecimalParameter,
                                IStrategy, IntParameter)

import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib
from freqtrade.persistence import Trade

class MACDLONGBULLISH(IStrategy):

    INTERFACE_VERSION = 2

    # ROI table:
    minimal_roi = {
        "0": 100
    }

    # Stoploss:
    stoploss = -0.10

    # Trailing stop:
    trailing_stop = False


    timeframe = '1h'

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 51

    def informative_pairs(self):
        return []

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        # Macd
        # macd = ta.MACD(dataframe, fastperiod=12, slowperiod=26, signalperiod=9)
        # dataframe['macd'] = macd['macd']
        # dataframe['macdsignal'] = macd['macdsignal']
        # dataframe['macdhist'] = macd['macdhist']
        dataframe['ema12'] = ta.EMA(dataframe, timeperiod=12)
        dataframe['ema26'] = ta.EMA(dataframe, timeperiod=26)
        dataframe['macd'] = dataframe['ema12'] - dataframe['ema26']
        dataframe['ema9'] = ta.EMA(dataframe['macd'], timeperiod=9)
        dataframe['macdsignal'] = dataframe['ema9']
        dataframe['macdhist'] = dataframe['macd'] - dataframe['macdsignal']
        # WMA
        dataframe['wmaSlow'] = ta.WMA(dataframe, timeperiod=50)
        dataframe['wmaFast'] = ta.WMA(dataframe, timeperiod=9)

        # Bollinger bands
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=3)
        dataframe['bb_lowerband'] = bollinger['lower']
        dataframe['bb_middleband'] = bollinger['mid']
        dataframe['bb_upperband'] = bollinger['upper']

        dataframe['atr'] = ta.ATR(dataframe)

        return dataframe

    use_custom_stoploss = True

    def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:

        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = dataframe.iloc[-1].squeeze()

        stoploss_price = last_candle['atr'] * 3

        if stoploss_price < current_rate:
            return (stoploss_price / current_rate) - 1

        # return maximum stoploss value, keeping current stoploss price unchanged
        return 1

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['macd'], dataframe['macdsignal'])) |
                (qtpylib.crossed_above(dataframe['close'], dataframe['bb_lowerband']))
            )  ,
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['wmaSlow'], dataframe['wmaFast']))
            ),
            'sell'] = 1
        return dataframe`


```

**Comment by xmatthias** [comment]
The 2 bollinger bands are not calculated the same way - that's quite clear when you look at the extension a few candles after your highlighted candle.

Your strategy uses typical price - i don't think that's how tradingview calculates it (instead it uses close) ...

**Comment by gdominoni** [comment]
> The 2 bollinger bands are not calculated the same way - that's quite clear when you look at the extension a few candles after your highlighted candle.
> 
> Your strategy uses typical price - i don't think that's how tradingview calculates it (instead it uses close) ...

Sorry but there is only one way to calculate BBs. And in both cases I'm using the same StDev multiplier and lenght. Instead, how do I set the strategy to use close, please?

**Comment by xmatthias** [comment]
there is multiple ways to calculate BB's (the calculation is the same, but the source data will be different) and tradingview (if you use it on their site) allows you to pick different sources (close, open, high, low, ...).

I've also seen different picks in how the MA is calculated (SMA, EMA, ) ... but it doesn't seem that tradingview is offering that possibility at the moment.

Your strategy is using `typical_price` - which is hlc3. you'll simply have to pass in `dataframe['close']` to calculate bollinger-bands differently.

**Comment by gdominoni** [comment]
> there is multiple ways to calculate BB's (the calculation is the same, but the source data will be different) and tradingview (if you use it on their site) allows you to pick different sources (close, open, high, low, ...).
> 
> I've also seen different picks in how the MA is calculated (SMA, EMA, ) ... but it doesn't seem that tradingview is offering that possibility at the moment.
> 
> Your strategy is using `typical_price` - which is hlc3. you'll simply have to pass in `dataframe['close']` to calculate bollinger-bands differently.

Sorry, I don't understand, will this solve the problem of the candles, or will it just make the "plotting BB" more consistent with "Tradingview BB"? (as the latter wasn't really the scope of my post)

And how do I pass in dataframe['close']? I'm quite a self-made in the field of programming (and a newcomer), and I am missing most of the basics, I guess, so I apologise. Also, with backtesting isn't it, actually, automatic that Freqtrade calculates only complete candles, and therefore at "close" (unless of course you specify a different option)?

p.s.: yes, Tradingview does not give you the chance of using WMA to calculate the BB's basis, but it's pretty easy to code it in Pine editor, and you gave me a pretty good hint here, I never thought of using WMA (or even EMA) for BB, thanks.

**Comment by xmatthias** [comment]
change 
`bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=3)` 
to 
`bollinger = qtpylib.bollinger_bands(dataframe['close'], window=20, stds=3)` to calculate bollingerbands on the close price instead of ohl3.

Now i've however understood what you mean - all plots freqtrade generates will be made in UTC timezone (the data is in UTC, too), so to get time alignment, simply change the timezone in tradingview to UTC.

**Comment by gdominoni** [comment]
Ok, I did what you told me. 
So now MACD corresponds, and candles too. Even if for some reason they are not aligned in the plotting (so for example the 12 November 00:00 is all correct, but I get the reading 3 steps backwards for the candles... but it's only a graphic issue, numbers are fine, so I don't care).

The problem with BB, instead, remains and therefore I missed some entry points. It looks like BB is switched 3 candles backwards.

![Screenshot from 2021-11-17 10-44-43](https://user-images.githubusercontent.com/24521096/142167012-69c9e4af-c8ea-4759-ad8f-77995f297539.png)
![Screenshot from 2021-11-17 10-43-52](https://user-images.githubusercontent.com/24521096/142167031-0a4bb061-d99f-422e-8d5f-768dee8fcf9e.png)

**Comment by xmatthias** [comment]
It's quite simple - you'll need to make sure that you're using the same parameters.
The tradingnview chart does not seem to use std=3 - which you got in your strategy.
there might be other parameters that are different (like not using sma, but some other MA calculation) - which is in the end up to you to inestigate why it's different.
Freqtrade / `plot-dataframe` will only visualize what you calculate - if your strategy calculates stuff wrong, then that wrong thing is what will be visualized.

**Comment by gdominoni** [comment]
> It's quite simple - you'll need to make sure that you're using the same parameters. The tradingnview chart does not seem to use std=3 - which you got in your strategy. there might be other parameters that are different (like not using sma, but some other MA calculation) - which is in the end up to you to inestigate why it's different. Freqtrade / `plot-dataframe` will only visualize what you calculate - if your strategy calculates stuff wrong, then that wrong thing is what will be visualized.

yes, you are right, I was using the worn parameters this time! Thank you!
