### ISSUE TITLE
Order get stuck in kucoin

### ISSUE THREAD

**Issue by bibinvargheset** [freqtrade/freqtrade#5912]
Some times orders get stuck in kucoin, some orders do not cancell after timeout and get stuck in kucoin and even force sell is not possible, if there was an option to cancell open order on the selected item. so that it is controllable from the api/up/telegram/ or the bot itself regain control it would be better

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.


Also, when reporting problems, please include logs of what happened, as well as other information that you think can help us investigating the problem (in this case, probably screenshots of the orders you see stuck, and the information from the database related to these orders).


With the information provided, we will have to close this issue, as there is 0 information other than someone complaining about something without any data showing what happens - which makes it a tale - not an issue worth investigating.

**Comment by xmatthias** [comment]
Closing due to lack of details.

Feel free to comment below / reopen (or open a new issue)  if you are able to provide the information requested. without that information, there is nothing we can do in order to assist you.
