### ISSUE TITLE
Check stake size against volume

### ISSUE THREAD

**Issue by Niqnil** [freqtrade/freqtrade#5913]
## Describe your environment

  * Operating system: Docker image: freqtradeorg/freqtrade:develop_plot
  * Python Version: Python 3.9.7
  * Freqtrade Version: freqtrade docker-63f4221f
  
## Your question

To ensure trade stake size is not too big with reference to volume for thinly traded pairs, I want to keep it below 0.5% of the candle.

Am I using `custom_stake_amount` correctly here? 
Does the tip "You do not have to ensure that min_stake <= returned_value <= max_stake. Trades will succeed as the returned value will be clamped to supported range and this acton will be logged." at [[](https://www.freqtrade.io/en/stable/strategy-advanced/#stake-size-management) ](https://www.freqtrade.io/en/stable/strategy-advanced/#stake-size-management) mean I don't have to check `if proposed_stake > min_stake`?. 
```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        dataframe['vol_sma'] = ta.SMA(dataframe['volume'], timeperiod=30)
        # ...

def custom_stake_amount(self, pair: str, current_time: datetime, current_rate: float,
                            proposed_stake: float, min_stake: float, max_stake: float,
                            **kwargs) -> float:

        dataframe, _ = self.dp.get_analyzed_dataframe(pair=pair, timeframe=self.timeframe)
        last_candle = dataframe.iloc[-1].squeeze()
        
        if proposed_stake > last_candle['vol_sma'] * 0.005:
            proposed_stake = last_candle['vol_sma'] * 0.005
            if proposed_stake > min_stake:
                return proposed_stake
            elif proposed_stake <= min_stake:
                return None
        
        return proposed_stake
```

**Comment by xmatthias** [comment]
if your proposed stake is lower than the minimum stake amount, it'll be increased to the minimum (assuming your function returns 12$ - it'll be raised to 15$ - assuming the 15$ is the calculated minimum trade size.

This "increase" is capped at 30% increase though to limit the increase to some degree.

**Comment by Niqnil** [comment]
There is another tip "Returning 0 or None will prevent trades from being placed." at https://www.freqtrade.io/en/stable/strategy-advanced/#stake-size-management. 
So `elif proposed_stake <= min_stake: return None` will stop the trade entry? That is what I want, instead of having proposed stake increase by 30%.

**Comment by xmatthias** [comment]
If it's written there as a tip already - what's the purpose of the question? obviously you can doubt anything written in the documentation - but i'd ask you to assume it's correct unless you discover a problem.

yes, that's correct. it's a "simple way out" if you don't like the result of your calculations / logics.
