### ISSUE TITLE
Performance on raspberry pi3 with docker image of FT

### ISSUE THREAD

**Issue by oldgitdaddy** [freqtrade/freqtrade#5917]
## Describe your environment

  * Operating system: raspbian
  * Python Version: 3.9.2 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.10 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I use the latest image of FT and run the NFI strategy. The bot is running, but the strategy does not buy anything. FT always just keeps one core busy. Some of the network calls, when using the UI run in timeout. Any advice would be helpful.

Hardware is raspberry pi3+. FT runs from the docker image.

htop look like this:
![image](https://user-images.githubusercontent.com/4282985/142292223-9a168077-691d-403e-aa16-40ab0fe98c69.png)

**Comment by xmatthias** [comment]
Different strategies have different requirements on on the hardware.
if 1 core is always at 100%, that probably means that your strategy is too compute heavy for the hardware you're using.

Usually, this is a sign that indicators used are not vectorized (or at least optimized), but use python loops - but that's a suspicion and will depend on the strategy (and it's also something that's up to the user to investigate further).

Best try running a lighter strategy if you're having problems with this - or contact the original strategy author about it.
