### ISSUE TITLE
How get available_pairs on class level?

### ISSUE THREAD

**Issue by mablue** [freqtrade/freqtrade#5921]
## Describe your environment

  * Operating system: Arch Linux
  * Python Version: Python 3.9.6 
  * CCXT version: ccxt==1.57.3
  * Freqtrade Version: freqtrade develop-51c6eb201 
  
## Your question
How get available_pairs on class level?
I need to know which pairs are in my whitelist and use them in class level how can I do that? I need something like that:
```
    pair1 = CategoricalParameter(Config["pair_whitelist"],default="BTC/USDT",space='buy')
```
Sorry For #5920

**Comment by xmatthias** [comment]
quite simply - you cannot.
This line is executed while loading the strategy class - not when it's running - so it's executed before some of these things are actually determined.

Access to bot data is only available from within instance methods.

**Comment by mablue** [comment]
> quite simply - you cannot. This line is executed while loading the strategy class - not when it's running - so it's executed before some of these things are actually determined.
> 
> Access to bot data is only available from within instance methods.

I think we can have access to self variable inside the hyperoptable params functions. For example inside Catagorical param. So can I send pairlists as a list to this param with some hacks?!?

**Comment by xmatthias** [comment]
no, you cannot. You keep asking repeatedly the same questions (not just in this issue - but also in other, older issues). 
Please learn to accept answers you are given, this is wasting my time.

As i know already that you'll continue to ask the same again and again below, i'm locking this issue, as the question has been answered.
