### ISSUE TITLE
ERROR - No pair in whitelist. when backtesting

### ISSUE THREAD

**Issue by laclance** [freqtrade/freqtrade#5922]
## Describe your environment

  * Operating system:  docker on Windows 10
  * Python Version: 3.1)
  * CCXT version: 1.59.2
  * Freqtrade Version: 2021.10

## Describe the problem:

exits with `ERROR - No pair in whitelist.`

### Steps to reproduce:

  1. `docker-compose run --rm freqtrade download-data --timerange=20210101- --config /freqtrade/user_data/config.json -t 5m --pairs BTC/USDT ETH/USDT`
  2. `docker-compose up -d`

### Relevant code exceptions or logs

docker-compose
```
    command: >
      backtesting
      --timerange=20210101-
      --strategy NostalgiaForInfinityV7
      --config /freqtrade/user_data/config.json
  ```

config
```
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {
            "enableRateLimit": true
        },
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
        "pair_whitelist": ["BTC/USDT, ETH/USDT"],
        "pair_blacklist": [
            ".*BULL",
            ".*BEAR",
            ".*UP",
            ".*DOWN",
            ".*USD/USDT"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList"
        }
    ],
```

logs
```
2021-11-19 08:15:12,594 - freqtrade.configuration.config_validation - INFO - Validating configuration ...

2021-11-19 08:15:12,600 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...

2021-11-19 08:15:12,612 - freqtrade - ERROR - No pair in whitelist.
  ```

**Comment by laclance** [comment]
Working with docker-compose run --rm ...

**Comment by xmatthias** [comment]
you should be using `docker-compose run --rm ...` for oneoff-commands (like backtesting, ...) - and `docker-compose up -d` only for long-running tasks (basically only for `freqtrade trade`).

**Comment by laclance** [comment]
yeah I realized, thank you.
