### ISSUE TITLE
Dynamic stake amount multiple bots

### ISSUE THREAD

**Issue by JHDE** [freqtrade/freqtrade#5928]
**Describe your environmen**t

    Operating system: Debian 4.19.0.14 amd64
    Python Version: 3.9
    CCXT 1.54.74
    Freqtrade Version: develop-e03784d9

**Your question**
I have two bots running live on the same exchange with different pairs and strategy.
tradable_balance_ratio bot 1 is 65% .
tradable_balance_ratio bot 2 is 25%.
So every bot is using a part of the available total account balance.
When bot 1 makes a profit this profit will also be used by bot 2 and vice versa.

Is it possible to assign a starting amount for each bot and only use the profit  for them selves?
Like it works in the dry run.

**Comment by xmatthias** [comment]
Please read the Warning boxes in the corresponding [documentation](https://www.freqtrade.io/en/stable/configuration/#tradable-balance) - using `tradable_balance_ratio` when running more than one bot on the same account is neither supported (we know it'll not work how you'd expect it to) nor recommended.

One section down you'll also find [this part about `available_capital`](https://www.freqtrade.io/en/stable/configuration/#assign-available-capital) - which will allow you to define the starting balance for each bot.

**Comment by JHDE** [comment]
Thanks XMatthias !!
I am sorry, overlooked the part about available_capital.

I think this is exactly what i was looking for.

**Comment by robert-negreanu** [comment]
Hi,

What happening if I'm running one strategy at the moment, I  have open trades, but I want to start a second strategy and to use available_capital option?
Can this work like this?
I mean how the capital will be used by the bots?
What amount of capital I should set for every bot?

Thank you

**Comment by rongybika** [comment]
Hi,

Let's say now I'm using one strategy and I have open orders. But I want to run another strategy with same account and I want to ,,split" the balance with available_capital setting without closing the current open trades.
What is your opinion, how I should do this without adding funding the account with extra money?

Thank you

**Comment by xmatthias** [comment]
@rongybika the above answer about `available_capital` will still be valid.

Obviously your desire is probably to "reduce" the amount the running bot has - so you'll need to change the settings - and reload the configuration. 
The (full) capital for the 2nd bot might not be available until the "first" bot has closed out the open positions (assuming you have your capital maxed out) - but it'll improve over time.
The "first" bot will also not have enough capital to open new trades until "enough" (more than half, probably) trade-slots are available in this original bot.

**Comment by rongybika** [comment]
Thank you :)
