### ISSUE TITLE
I want to buy on exact percentage 

### ISSUE THREAD

**Issue by suhail1142r** [freqtrade/freqtrade#5931]
## Describe your environment

  * Operating system: ____(`Microsoft Windows [Version 10.0.19043.1348]`)
  * Python Version: _____ (`python - 3.10.0`)
  * Freqtrade Version: ____ (`freqtrade - 2021.10`)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**HELLO 
I create a strategy and I want to know how can I code it to sell on 5% profit**

**Comment by xmatthias** [comment]
the [documentation](https://www.freqtrade.io/en/stable/strategy-customization/#minimal-roi) is your friend.

you can use something like `minimal_roi = {'0': 0.05}` to sell whenever you reach 5% profits.
