### ISSUE TITLE
Is there a way to have cooldown after buy?

### ISSUE THREAD

**Issue by saikou999** [freqtrade/freqtrade#5934]
## Describe your environment

  * Operating system: MacOS
  * Python Version: python - 3.10.0
  * CCXT version: N/A
  * Freqtrade Version: freqtrade - 2021.10
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hi,

I know there's a cooldown option for a trade after sell, but is there a cooldown option after buy? For example, I want my bot to not do anything for 10 minutes in one of my conditions like below. Is is possible?

```
def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (
                   (dataframe['ma_30m'] > dataframe['close'])
                   &
                   **Cooldown 10 mins** 
               )
                |
                   (dataframe['con2''] > dataframe['close'])
            ),
            'sell'] = 1
        return dataframe
```

**Comment by xmatthias** [comment]
Please use [the documentation](https://www.freqtrade.io/en/stable/plugins/#cooldown-period) to find answers to your questions before posting. We have Protections for this (documentation linked above).


You can also join our [discord server](https://discord.gg/p7nuUNVfP7) to get support / help from the community.
People there love to help - however assuming the documentation has been consulted first.

**Comment by saikou999** [comment]
Hi @xmatthias 

I can find protections after selling but I can't seem to find protections after buying in the documentation .... Please can you point me in the right direction as to where in the documentation has that information? Thank you.

**Comment by xmatthias** [comment]
You can manually [lock pairs](https://www.freqtrade.io/en/stable/strategy-customization/#prevent-trades-from-happening-for-a-specific-pair) - or all (with `*`) ...

I'm not sure why you'd have this for buy signals though - it's either a good signal (should be acted on), or it isn't (should not be a signal at all) ... 
i don't think that having other pairs influence a signal is good - as you're probably missing on more than what you think this'll gain you.
