### ISSUE TITLE
Rule applying only to the first candle after entry

### ISSUE THREAD

**Issue by gdominoni** [freqtrade/freqtrade#5937]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.8
  * CCXT version: CCXT version: 1.59.2
  * Freqtrade Version: 2021-10
  
## Your question

Hi!

I was trying to make a rule to exit the strategy when the first candle of the trade closes lower than the lowest point of the entry candle. So the rule must apply only to the first candle after the entry point.

I thought you can index with negative numbers (calling -1 the last value of the array, hence the entry point, and -2 the the first candle after) but apparently, it is not working:

```
entryPriceLow = low[-1]
firstCandleClose = close[-2]
exitRule = firstCandleClose < entryPriceLow
```

any idea?

Thank you!

UPDATE:
I tried this, but it's not working (it applies the rule on any candle, not just the first one)

```
hourspassed = ta.barssince(strategy.position_size > 0)
exit3 = close < low[1]

if hourspassed <= 1
    if (exit3 and inTrade)
        strategy.close(id="long")
```

**Comment by ghost** [comment]
Dataframe is different from array. For dataframe you have to use .shift() - for example dataframe['close'].shift(1) to get previous close.

**Comment by gdominoni** [comment]
Sorry, I actually posted this on the wrong website :D I was referring to
Pine script, that is why I closed it :)
