### ISSUE TITLE
How to use current_rate for buying / need for custom_buy

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#5938]
Sometimes there are sudden price drops during a candle.
I wonder if there is a way to perform buying at market price if price drops below a certain level like method custom_sell, but for buying - that could be used to catch these price drops?
As far as i understand the bot can only use past data from closed candles, not incomplete candles - so it would be impossible to catch these price drops, however it would be really nice to have such a thing because to me this seems like easy profit
![1](https://user-images.githubusercontent.com/91958753/142771595-1003d232-2c6f-4686-aa42-ad8f4056797d.png)

**Comment by xmatthias** [comment]
these price-drops usually last seconds - so the moment you notice it, you're already too late to the party.
while it is a bot, it's still subject to 2 things:
* network latency
* exchange rate limits

While you can buy away the first (more power) - you can't do that with the second - so with the current freqtrade architecture, this is neither possible, nor supported, nor will it work (from a timing perspective).

Freqtrade is based around technical analysis - basing buys on top of that. It neither tries nor aims to be a bot that's "the quickest" - or even a market making bot.
