### ISSUE TITLE
Open Orders

### ISSUE THREAD

**Issue by kraken-jar** [freqtrade/freqtrade#5947]
I am using Bollinger and Rsi strategy means buying at the lower band with RSI >30 and selling at middle band. I tried to use the default volume list but it is not taking any order... I also tried to change the time interval within the range of  5m to 1h but it is still not taking any order. 😢

OS - Ubuntu

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Please read the documentation before asking questions that are covered by our [faq](https://www.freqtrade.io/en/stable/faq/#i-have-waited-5-minutes-why-hasnt-the-bot-made-any-trades-yet).
