### ISSUE TITLE
Custom stoploss not working as it should

### ISSUE THREAD

**Issue by gdominoni** [freqtrade/freqtrade#5948]
* Operating system: Ubuntu
  * Python Version:3.8
  * CCXT version: 
  * Freqtrade Version: 2021-10

The idea is to split the custom stoploss in 2 parts:

- Within the first hour from the entry point, it should trigger when the value falls below the lowest point of the previous candle (low, not close or open).
- After that, stoploss is set at close - 3*ATR

why is this code not working? It basically always closes whenever it wants...
```
def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:

        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = dataframe.iloc[-1].squeeze()
        stoploss_price1 = last_candle['low']
        stoploss_price2 = last_candle['close'] - (last_candle['atr'] * 3)

        # VALID ONLY FOR 1H INTERVAL!!!
        if current_time - timedelta(minutes=60) < trade.open_date_utc:
            #assuming previous candle is always green, due to entry conditions
            return abs((last_candle['close'] - last_candle['low']) / last_candle['low'])

        return 1-(stoploss_price2 / last_candle['close'])
```

**Comment by xmatthias** [comment]
i don't think your calculation for the first hour is correct.

`custom_stoploss` is assumed to return a relative value **from the current price** - you seem to return the relative change between previous close and low ... which will ultimately result in a trailing stop that's trailing at the returned value (might be 1%, might be 5%, or 0.1% - depends solely on the prior candle length).



Freqtrade offers a helper method for this in [`stoploss_from_absolute`](https://www.freqtrade.io/en/latest/strategy-callbacks/#stoploss-percentage-from-absolute-price). (i'm intentionally not linking directly to that page, but to the explanation on how custom stoploss shall work).

**Comment by gdominoni** [comment]
> i don't think your calculation for the first hour is correct.
> 
> `custom_stoploss` is assumed to return a relative value **from the current price** - you seem to return the relative change between previous close and low ... which will ultimately result in a trailing stop that's trailing at the returned value (might be 1%, might be 5%, or 0.1% - depends solely on the prior candle length).
> 
> Freqtrade offers a helper method for this in [`stoploss_from_absolute`](https://www.freqtrade.io/en/latest/strategy-callbacks/#stoploss-percentage-from-absolute-price). (i'm intentionally not linking directly to that page, but to the explanation on how custom stoploss shall work).


to be honest, most of the problems I have happen after the hour... The stoploss gets triggered much before it reaches the level of close - 3 * ATR

**Comment by xmatthias** [comment]
well the problem doesn't change, really - what you return must be relative to `current_rate`, which your calculation clearly isn't.

so if your calculation yields 2% (0.02) - it'll not be 2% below the trade entry, but 5% below the current rate.

**Comment by gdominoni** [comment]
> i don't think your calculation for the first hour is correct.
> 
> `custom_stoploss` is assumed to return a relative value **from the current price** - you seem to return the relative change between previous close and low ... which will ultimately result in a trailing stop that's trailing at the returned value (might be 1%, might be 5%, or 0.1% - depends solely on the prior candle length).
> 
> Freqtrade offers a helper method for this in [`stoploss_from_absolute`](https://www.freqtrade.io/en/latest/strategy-callbacks/#stoploss-percentage-from-absolute-price). (i'm intentionally not linking directly to that page, but to the explanation on how custom stoploss shall work).


> well the problem doesn't change, really - what you return must be relative to `current_rate`, which your calculation clearly isn't.
> 
> so if your calculation yields 2% (0.02) - it'll not be 2% below the trade entry, but 5% below the current rate.

assuming you meant 2%, not 5%, it is exactly what I want to do. I want to calculate on the previous candle the ATR*3, subtract is from the close, and use that value as stoploss for the candle after. So, if the previous candle closed  at 10, and the ATR was 1, then the stoploss should be set at 7, and change on every candle.

EDIT: and the same applies for the first hour, only instead of using ATR, I want to use the size of the candle (from close to low)

**Comment by xmatthias** [comment]
Your thinking about "candle after" is wrong. custom stoploss is called for every iteration - not only once, so you'll need to think about this in a continuous manner.

While you can place your stoploss to the low of the previous candle - your code does NOT do that. It takes the difference between close and low - and uses that as stoploss - current rate might be above the prior close - so your stoploss will potentially be placed above the prior low.

Also, stoplosses never move down (in an absolute / price way) - so once your stoploss has risen to a certain level (say 50$), it'll never go down to 49$ again.

The linked documentation above contains all the information you need i think.

**Comment by gdominoni** [comment]
> Your thinking about "candle after" is wrong. custom stoploss is called for every iteration - not only once, so you'll need to think about this in a continuous manner.
> 
> While you can place your stoploss to the low of the previous candle - your code does NOT do that. It takes the difference between close and low - and uses that as stoploss - current rate might be above the prior close - so your stoploss will potentially be placed above the prior low.
> 
> Also, stoplosses never move down (in an absolute / price way) - so once your stoploss has risen to a certain level (say 50$), it'll never go down to 49$ again.
> 
> The linked documentation above contains all the information you need i think.

Thank you, you're of great help, but I still do not understand something. If stoploss can never go down (which is logical for a normal trailing stoploss) what sense does it make for something like this? https://www.freqtrade.io/en/stable/strategy-advanced/#custom-stoploss-using-an-indicator-from-dataframe-example. As I understand from your info (and from the documentation, which I have already read, but I misunderstood), basically if the stoploss calculated with SAR would increase from 0.5% to 0.6%, that would not apply in Freqtrade. If that is so, what is the point of even proposing to use SAR at all? Basically what is called "custom stoploss" is just an advanced "trailing stoploss". Do I understand it well?

I actually took the idea of my stoploss from this SAR example, only I wanted to use ATR instead of SAR.

**Comment by xmatthias** [comment]
One can argue if SAR is a good example or not - but it's as good as any if you ask me - as the individual user's indicator(s) will almost always differ. 

You can also use ATR in different ways - usually you set a stoploss at 3x ATR below the trade entry, not below the prior candle.
Think about manual trading - if you defined your stoploss at -3x ATR below your entry -  you'll not be moving the stoploss lower if your trade starts losing after 2 candles ... but that's what a stoploss that is allowed to be set lower than a previous stop would mean.


it's just an awareness topic - stoploss will "remain static" if your gap increases, or "pull tighter" if the calculated gap decreases.

Would a stoploss ever be allowed to move down, then it would no longer be a stoploss, as it would move in parallel to your trade (including going down all the way in parallel, potentially), and would probably never trigger.

If you want to dynamically exit, maybe custom_sell_signal is what you're looking for - but that's usually not how atrx3 is applied ...

**Comment by gdominoni** [comment]
> One can argue if SAR is a good example or not - but it's as good as any if you ask me - as the individual user's indicator(s) will almost always differ.
> 
> You can also use ATR in different ways - usually you set a stoploss at 3x ATR below the trade entry, not below the prior candle. Think about manual trading - if you defined your stoploss at -3x ATR below your entry - you'll not be moving the stoploss lower if your trade starts losing after 2 candles ... but that's what a stoploss that is allowed to be set lower than a previous stop would mean.
> 
> it's just an awareness topic - stoploss will "remain static" if your gap increases, or "pull tighter" if the calculated gap decreases.
> 
> Would a stoploss ever be allowed to move down, then it would no longer be a stoploss, as it would move in parallel to your trade (including going down all the way in parallel, potentially), and would probably never trigger.
> 
> If you want to dynamically exit, maybe custom_sell_signal is what you're looking for - but that's usually not how atrx3 is applied ...

great, I think custom_sell_signal will work.

And I tried using this one for the stoploss:

> One can argue if SAR is a good example or not - but it's as good as any if you ask me - as the individual user's indicator(s) will almost always differ.
> 
> You can also use ATR in different ways - usually you set a stoploss at 3x ATR below the trade entry, not below the prior candle. Think about manual trading - if you defined your stoploss at -3x ATR below your entry - you'll not be moving the stoploss lower if your trade starts losing after 2 candles ... but that's what a stoploss that is allowed to be set lower than a previous stop would mean.
> 
> it's just an awareness topic - stoploss will "remain static" if your gap increases, or "pull tighter" if the calculated gap decreases.
> 
> Would a stoploss ever be allowed to move down, then it would no longer be a stoploss, as it would move in parallel to your trade (including going down all the way in parallel, potentially), and would probably never trigger.
> 
> If you want to dynamically exit, maybe custom_sell_signal is what you're looking for - but that's usually not how atrx3 is applied ...

I hope I am not abusing of your patience, but I have more questions...

custom_sell_signal is a great idea, but I do not understand it fully.

First of all, what do I do with the "unclog" part in the example?
https://www.freqtrade.io/en/stable/strategy-advanced/#custom-sell-signal
How do I "tell" freqtrade that this means to sell? I suppose my programming knowledge is not sufficient to understand these instructions.

Also, what are "last_candle" and "trade_candle" in the example referring to exactly?
https://www.freqtrade.io/en/stable/strategy-advanced/#dataframe-access
Last candle is the equivalent of dataframe().shift(1), or the current one? And the trade_candle? In general, I need to refer to the candle before the order was called, and the current one, but I'm not sure how to, using this method. 
Something like this (but of course this code is not working)
```
    def custom_sell(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, **kwargs):
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = dataframe.iloc[-1].squeeze()

     #(dataframe('close').shift(1) - dataframe('low').shift(1)) is always positive
      if (current_time - trade.open_date_utc).days <= 0.041 and (dataframe('open') > dataframe('close')) and (dataframe('open') - dataframe('close')) > (dataframe('close').shift(1) - dataframe('low').shift(1)):
            return 'unclog'
```

**Comment by xmatthias** [comment]
returning anything other than "None" (or False) will result in an immediate sell. 
if you provide a string, this will serve as "sell_reason" - if it's True, sell_signal will be used as sell-reason.

last_candle and trade_candle are just variable names - what they signify will depend on what you assigned to them in the first place.

**Comment by gdominoni** [comment]
> last_candle and trade_candle are just variable names - what they signify will depend on what you assigned to them in the first place.

Yes, sure, that I knew, but I was not sure how to assign the correct values. I made a try but, guess the unguessable, the code is still not working... 

```
def custom_sell(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, **kwargs):
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        previous_candle = dataframe.iloc[-2].squeeze()

        if (current_time - trade.open_date_utc).days <= 0.041 and (current_rate < previous_candle('low')):
                return 'PreventiveExit'
```

2021-11-23 14:29:22,270 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'Series' object is not callable calling <bound method MACD1HTEST.custom_sell of <MACD1HTEST.MACD1HTEST object at 0x7fe81612f280>>
Traceback (most recent call last):
  File "/home/trading1/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "/home/trading1/freqtrade/user_data/strategies/MACD1H.py", line 345, in custom_sell
    if (current_time - trade.open_date_utc).days <= 0.041 and (current_rate < previous_candle('low')):
TypeError: 'Series' object is not callable

Of course, what I am trying to do is always the same: if, within the first hour (with timeframe = 1h), the rate drops below the lowest rate of the previous candle, sell.

I hope I a getting closer to the solution

**Comment by xmatthias** [comment]
you're now going back 2 candles - so assuming 1h candles , and it's now 12:30 - your last "closed" candle is the one from 11:00-12:00 - and the one you're using is 10:00-11:00.

your parentheses are wrong - use `previous_candle['low']` instead of `previous_candle('low')` (and wherever else you've used that).

**Comment by gdominoni** [comment]
> you're now going back 2 candles - so assuming 1h candles , and it's now 12:30 - your last "closed" candle is the one from 11:00-12:00 - and the one you're using is 10:00-11:00.
> 
> your parentheses are wrong - use `previous_candle['low']` instead of `previous_candle('low')` (and wherever else you've used that).

great, thanks
