### ISSUE TITLE
Pairlistfilters in backtesting mode

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#5955]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.10 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

According to the online documentation more than one pairlist filter is supported in backtesting: Are the filters related to the past data, or only to the presence?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Filters usually use current data - so they should be used with care - and i'd recommend using a static pairlist (maybe one with random order) for repeatable backtesting results.

For some (like spreadfilter), it wouldn't even be possible to simulate this with historic data (historic spread info is not available).
others might have that possibility - but to "really" simulate proper behaviour, we'd need to recalculate the pairlist every few candles - which would be a huge resource hog (making backtesting slow) - as well as make the code a lot more complex than what it already is.

**Comment by myNextCoder** [comment]
I thank you for your information. In fact, I even got a repeated runtime error during backtesting (Windows Server 2022 and Miniconda), with active pairlistfilters. Since now I know, that they use current data, it makes no sense anymore for me, to use them for backtesting.

**Comment by stash86** [comment]
I assume this can be closed because question has been answered, and don't see any improvement idea.
