### ISSUE TITLE
Add --days arg to Backtest and Hyperopt

### ISSUE THREAD

**Issue by briankudera** [freqtrade/freqtrade#5962]
## Describe your environment
N/A

## Describe the enhancement
To assist with automation, I would like to schedule data downloading, hyperopting, and backtesting. In order to automate this entire workflow, I am requesting the --days arg be added to the hyperopt and backtesting commands, just like it works in data-download.

**Comment by xmatthias** [comment]
Backtesting and hyperopt support the `--timerange` argument, which allows you to define the timerange to backtest.
It can be used for downloading data as that is an incremental process - backtesting/hyperopt however should be ran against a defined timerange.

Using `--days` for backtesting/hyperopt would not give you a stable period (it'll change if you run the same thing tomorrow) - and will therefore cause non-repeatable backtests/hyperopts.


You should also note that using `--days` for downloading data is to support simple incremental downloads - and is not recommended for an initial download as you'll have to calculate the precise starting date yourself (even though it works there as well).

You can however use "open end" timeranges (`--timerange 20211101-`) to backtest from begining of november until "current date".

Proper automation should control the timerange as well (which --days does only to a very limited degree) - therfore i don't consider this as valid request.

**Comment by briankudera** [comment]
Using open ended time ranges will also cause non-repeatable backrests/hyperopts so I don't think that's a valid reason to dismiss my idea.

Therefore, we could say the same for download-data command and the - - days arg should essentially be deprecated and instead use the open ended time range arg just as hyperopts or backresting requires.

It's all about consistency

**Comment by xmatthias** [comment]
Download-data does incremental downloads.
If you run `download-data` every day with `--days 5` - it'll not download the last 5 days of data, but only what's missing (which will be the last 24h - assuming your scheduling works right).

Backtesting is not working like this (it cannot and should not) - so i don't see this as inconsistency - but as 2 parameters that serve a different purpose.
