### ISSUE TITLE
Add ability to hyperopt max_open_trades

### ISSUE THREAD

**Issue by briankudera** [freqtrade/freqtrade#5963]
## Describe your environment
N/A

## Describe the enhancement
Currently it seems the max_open_trades can have significant impact on profit. The only way I have been able to find a good number is to run several backtests one at a time and changing the setting and then comparing the results.
I'm wondering about the likelihood of adding this as a new hyperopt space. I realize HO is all strategy specific, and max_open_trades is bot specific, so this might be a lot of work.

**Comment by xmatthias** [comment]
it actually isn't (not really, anyway) - as `max_open_trades` is a parameter to backtesting - hyperopting it should be pretty easy.

The only "real" problem i see is that `max_open_trades` is currently only configurable from within the configuration (not from the strategy) - so the configuration will (in backtesting) always overwrite what you assigned.
This can obviously be changed, but as almost everyone will have `max_open_trades` in the config (it's a must, really) - we must be clear in documenting this (and at the same time, enabling it to be set from the strategy).

I'd encourage you to try working on this yourself and creating a PR (which i can then assist  in case of problems in the PR comments).

you can take the changes done in #5360 for protection hyperopt as an example (although you'll need to ignore certain things as it also adds a new parametertype).
