### ISSUE TITLE
dynamic max open trades

### ISSUE THREAD

**Issue by SmartManoj** [freqtrade/freqtrade#5966]
## Describe the enhancement

divide the stake amount by 2 if only one slot available unless it is less than twice the min stake amount. So there would be a slot will be open mostly.

**Comment by SmartManoj** [comment]
for max_open_trades=2

https://github.com/freqtrade/freqtrade/blob/ce2aa1dc698f30a84345f1b3a2bd6cf7cd928056/freqtrade/wallets.py#L177-L188
 changing  
 ```
       if available_amount<30:
            possible_stake= available_amount
        else:
            possible_stake = (available_amount) / self._config['max_open_trades']```
```

https://github.com/freqtrade/freqtrade/blob/ce2aa1dc698f30a84345f1b3a2bd6cf7cd928056/freqtrade/freqtradebot.py#L233-L239
and changing `min(2 ,int(self.wallets.get_available_stake_amount()//15))` in this function will do the trick for now?

**Comment by xmatthias** [comment]
I don't see why this should be necessary. stake-amount can be [controlled by the strategy](https://www.freqtrade.io/en/stable/strategy-advanced/#stake-size-management) - where you can do whatever calculation necessary.

However, i also don't really see why you'd like to always keep 1 stake untouched - that seems like lost opportunity. 

if you want the bot to not touch a certain capital, you should instead look at [tradable balance](https://www.freqtrade.io/en/stable/configuration/#tradable-balance) or [available capital](https://www.freqtrade.io/en/stable/configuration/#assign-available-capital) instead, which will keep a certain % of capital untouched, or only use a certain amount of capital in the first place, respectively.

**Comment by SmartManoj** [comment]
This can reduce the number of missing buy signals.
That one stake will be used if it is near min_stake_amount.

**Comment by SmartManoj** [comment]
https://www.freqtrade.io/en/stable/strategy-advanced/#:~:text=freqtrade%20will%20fall%20back%20to%20the%20proposed_stake%20value%20should%20your%20code%20raise%20an%20exception.%20the%20exception%20itself%20will%20be%20logged.

Grammatical error.
Freqtrade will fall back to the proposed_stake value should your code raise an exception. The exception itself will be logged.

Fix
Freqtrade will fall back to the proposed_stake value ifyour code raise an exception. The exception itself will be logged.

Also iin that strategy the else part and proposed_stake is same?

**Comment by xmatthias** [comment]
> This can reduce the number of missing buy signals.
> That one stake will be used if it is near min_stake_amount.

I don't see why you should not be able to accomplish this with a combination of `custom_stake_amount()`, and `max_open_trades=-1`.
You'll obviously have to control the stake amount yourself - but it gives you the most flexibility.

As for the "reduction of missed buy signals" - a better approach for this is probably the use of a sane, pretty tight stoploss, to avoid remaining stuck in a trade for too long. Otherwise you've simply moved the missed buy-signals by one - as you're now stuck in the 5th trade instead of the 4th.

**Comment by SmartManoj** [comment]
how max_open_trades=-1 wil work as max is used?

https://github.com/freqtrade/freqtrade/blob/ce2aa1dc698f30a84345f1b3a2bd6cf7cd928056/freqtrade/freqtradebot.py#L239
