### ISSUE TITLE
Using a 'fixed time of day' price in strategy

### ISSUE THREAD

**Issue by arnecodebase** [freqtrade/freqtrade#5969]
## Describe your environment

  * Operating system: Debian GNU/Linux 10 (buster)
  * Python Version: 3.7.5 
  * CCXT version: 1.60.77 
  * Freqtrade Version: 2021.10 
  
## Your question

Hi, after searching through the archive on Github and example strategies I found online, I spend countless hours testing and trying, but I can't seem to find the answer. 

I have a strategy that is relying on the daily open of a specific symbol, it's running on a 1H timeframe. I realise a 'daily open price' can be subjective, so I am defining it as a fixed time (UTC midnight). 

The 1D candles from Binance are lagging by 2 days, so even though the strategy compiles, I can't use that data unfortunately. I tried creating a dataframe with 1H candles, and am able to locate and store the UTC midnight open, however I can't get it to be available to the subsequent 23 candles in the day. I tried copying it by using .loc (dataframe.loc[dataframe.date==[var that stores the UTC open], 'open'])) to no success either. I know I'm missing something, but can't figure it out.

Is there anyone that has a different approach, but in the end managed to get a 'fixed time of day' price integrated into their strategy? For example a custom indicator/function that is using the Asian/European open or something similar, that would work as an example too. And if so, are you willing to help me locate the right approach? 

Thank you in advance.

**Comment by xmatthias** [comment]
you should be able to do this with something like the following (untested, potential syntax errors are provided free of charge):

``` python
dataframe['daily_open'] = dataframe.loc[(dataframe['date'].dt.hour ==0), 'open']
# You'll have gotten this far - this will give you a "sparse" array, with 23 hours of the day being empty.

# now forward-fill this value for the remainder of the day.
dataframe['daily_open'] = dataframe['daily_open'].ffill()

```

**Comment by arnecodebase** [comment]
Thank you, that worked perfectly.
