### ISSUE TITLE
Cancelled due to timeout

### ISSUE THREAD

**Issue by kraken-jar** [freqtrade/freqtrade#5971]
After 5-10 mins of entering into a trade, I always got ..... cancelling Open Buy orders for XXX/USDT. 
Reason: Cancelled due to timeout, fully cancelled.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

This is quite simply a order timeout, which is quite common with limit markets.

You should think very carefully about how you [price your orders](https://www.freqtrade.io/en/stable/configuration/#prices-used-for-orders), as this will determine at what price the order is placed, and will therefore also determine the probability of filling an order (or not).

**Comment by kraken-jar** [comment]
Thankyou bro for helping me out...and sorry for not filling template
