### ISSUE TITLE
Out of memory errors after ~4000 epochs

### ISSUE THREAD

**Issue by ArthurVerstraete** [freqtrade/freqtrade#5972]
Hi,

I'm hyperopting my strategy on an old computer where the process can only 5GB of RAM, but after approximately 4000 epochs it goes out of memory. Would it help to increase this to 12GB or should I go further and increase it to 25GB? I want to know if I should update the computer and just add 8GB of RAM or update both RAM slots to 16GB.
And maybe just another question: if I'm hyperopting, it saves the results to ./user_data/hyperopt_results. If I restart the hyperopt process, will it take into account these results or will it ignore them?
Thanks in advance!

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

This is covered explicitly by our [documentation](https://www.freqtrade.io/en/stable/hyperopt/#out-of-memory-errors) - as it's a common error.

Restart will start from a new random location, unless you specify the same random value - in which case the process would be repeated.
