### ISSUE TITLE
Add `unlock all` command

### ISSUE THREAD

**Issue by Theagainmen** [freqtrade/freqtrade#5973]
## Describe the enhancement
Add an `/unlock all` command for the Telegram.

Right now when a _global_ protection kicks in, I usually set it to a time that high I can make sure I look within that certain time period on my bot data, and manually check if I want to continue the bot or stop it. However if I want to let the bot continue, I have to unlock the pairs one by one which takes pretty long. That's why I think `/unlock all` is a nice feature where you can simply unlock all pairs at once and let the bot continue!

**Comment by xmatthias** [comment]
global protections lock all pairs with `*` - will be shown as `* - reason` in the `/locks` output and can be unlocked with `/unlock *`. As such, i don't really see a need for `/unlock all` - as that can have negative side-effects (you often want to unlock all pairs except for that very bad performing one ...) - and will therefore be less useful than you think it is.

you should however note that protections may come back with the next sell - as the lock condition might still be true.

**Comment by Theagainmen** [comment]
> global protections lock all pairs with `*` - will be shown as `* - reason` in the `/locks` output and can be unlocked with `/unlock *`. As such, i don't really see a need for `/unlock all` - as that can have negative side-effects (you often want to unlock all pairs except for that very bad performing one ...) - and will therefore be less useful than you think it is.

Thanks! I guess `/unlock *` will do the job for me, I can then simply lock the pair(s) that I want to lock, that's not really a problem. 

> you should however note that protections may come back with the next sell - as the lock condition might still be true.

Ye that's something I need to think about indeed mhm..

**Comment by xmatthias** [comment]
The new release (2021.11) will also have a `unlock_reason()` method (to be called from the strategy) - so you can unlock all pairs at once.
