### ISSUE TITLE
How to cancel a trade if it's the X'th opened trade within a certain time

### ISSUE THREAD

**Issue by Theagainmen** [freqtrade/freqtrade#5974]
## Your question
**How can I cancel a trade if it's the X'th opened trade within a certain time?**

For example:
I have a `max_open_trades` configured of 10, I want my bot to buy at max 5 trades within 1 hour. All other trades it tries to open within that hour, should be denied. Reason for this is to reduce risk, since every strategy I have ever used has those weird hours where your bot just fills up all slots within an hour or less! Which I want to try to avoid by denying trades if it's used 5 slots (50% of `max_open_trades`) within a specified time. 

Now I have to use this function for it, somewhat like this (docs https://www.freqtrade.io/en/latest/strategy-callbacks/#trade-entry-buy-order-confirmation):
```py
    def confirm_trade_entry(self, pair: str, order_type: str, amount: float, rate: float,
                            time_in_force: str, current_time: datetime, **kwargs) -> bool:
        
        # if 50% of self.config['max_open_trades'] is opened within the last 1 hour, return False
        return True
```

I'm not sure what to add to that function to get what I want. 

Besides this, is there anything I might miss, that this function I want, will not work as how I intend it to work?

Thanks for any help :)

**Comment by xmatthias** [comment]
the idea should work

your best bet is probably to query the [trade object](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-trades) and try to fetch all currently open trades, maybe filtering on open-time to only get the ones in the period of interest.

All other things will not give you the "opened within" - but just the current state, which is not really what you're looking for i guess.

**Comment by Theagainmen** [comment]
Thanks that looks good indeed, would this work? I'm not sure if `len(open_trades)` really returns the amount of open_trades as I intend it to though.

```py
    def confirm_trade_entry(self, pair: str, order_type: str, amount: float, rate: float,
                            time_in_force: str, current_time: datetime, **kwargs) -> bool:

        # Do not buy a trade, if in the past hour you have already opened 50% of your slot trades (max_open_trades)
        if self.config['runmode'].value in ('live', 'dry_run'):
            open_trades = Trade.get_trades([Trade.open_date > (datetime.utcnow() - timedelta(hours=1)),
                                       Trade.is_open.is_(True),
                                       ]).all()

            if len(open_trades) > int(self.config['max_open_trades'] * 0.5):
                # Log something?
                return False

        return True

**Comment by xmatthias** [comment]
i'd not use datetime.utcnow() (which might give you the wrong time due to timezones), but `current_time` - but on a quick glance, it looks okish.

**Comment by Theagainmen** [comment]
Thanks again, I changed it and also imported a math function for another calculation (round up numbers), is it ok to import the math library into a strategy file? Or will this break things/not recommended?

**Comment by xmatthias** [comment]
you can import whatever you want as long as it's not overwriting existing imports.
