### ISSUE TITLE
Range Stability Filter, max roc + 1d Informative Pairs causes Pairs to get Filtered after Pairlist Refresh without Reason

### ISSUE THREAD

**Issue by Bloodhunter4rc** [freqtrade/freqtrade#5978]
## Describe your environment

  * Operating system: Debian Docker
  * Freqtrade Version: latest stable
 
## Describe the problem:

When using a strategy with 1d Informative candles and using a rangestability filter with max_rate_of_change configured, after the first pairlist refresh all pairs get filtered with abnormal values +5500% change of rate etc. 

Most people report this since its happening with NFI which uses 1d candles.

### Steps to reproduce:

  1. Run a Strategy which uses 1d Informative Pairs
  2. Use Max Range Stability Filter, with "max_rate_of_change" configured
  3. After a Pairlist Refresh pairs get filtered with abnormal large values

**https://discord.com/channels/700048804539400213/824719649417199646/914101962159570974**
> 2021-11-27 10:31:16,705 - RangeStabilityFilter - INFO - Removed BTC/USDT from whitelist, because rate of change over 3 days is 17.798, which is above the threshold of 1.1.
> 2021-11-27 10:31:16,706 - RangeStabilityFilter - INFO - Removed ETH/USDT from whitelist, because rate of change over 3 days is 55.605, which is above the threshold of 1.1.

Proposed Fix from @ apyr on NFI Discord Channel (he does not have a github account)
```
diff --git a/freqtrade/plugins/pairlist/rangestabilityfilter.py b/freqtrade/plugins/pairlist/rangestabilityfilter.py
index 3e5a002ff..66302a133 100644
--- a/freqtrade/plugins/pairlist/rangestabilityfilter.py
+++ b/freqtrade/plugins/pairlist/rangestabilityfilter.py
@@ -98,8 +98,9 @@ class RangeStabilityFilter(IPairList):
 
         result = False
         if daily_candles is not None and not daily_candles.empty:
-            highest_high = daily_candles['high'].max()
-            lowest_low = daily_candles['low'].min()
+            tail = daily_candles.tail(self._days)
+            highest_high = tail['high'].max()
+            lowest_low = tail['low'].min()
             pct_change = ((highest_high - lowest_low) / lowest_low) if lowest_low > 0 else 0
             if pct_change >= self._min_rate_of_change:
                 result = True
```

apyr — 25.09.2021
apparently there is missing candle filter in https://github.com/freqtrade/freqtrade/blob/b4d869e8c4653a62d9c018e26564e0a277dcfc87/freqtrade/plugins/pairlist/rangestabilityfilter.py#L77
refresh_latest_ohlcv returns data from years ago, so that's why range is so high 

### Observed Results:

Pairs get filtered with abnormal roc numbers.

Maybe you can have a look, i am not actually experiencing this issue anymore since i am not actively running a strat with 1d informative, but theres users which are running NFI (issue is not strat dependant it seems) which happen to have that issue, not sure if i can be of any more help here, i had this issue before ;-)

**Comment by xmatthias** [comment]
Please provide a _minimal_ strategy where this is happening so it can be easily recreated.

This can very well also be caused by the strategy itself in some way or form - and i don't intend to
a) search for the strategy that's causing it
b) read through a strategy that's potentially 100ds of lines long.

**Comment by Bloodhunter4rc** [comment]
sure understand that, i was able to verify this with this example, after 5 minutes of running the rangestabilityfilter refresh kicks in and:

> freqtrade     | 2021-11-27 16:21:16,318 - RangeStabilityFilter - INFO - Removed CHZ/USDT from whitelist, because rate of change over 10 days is 247.658, which is above the threshold of 1.0.
> freqtrade     | 2021-11-27 16:21:16,318 - RangeStabilityFilter - INFO - Removed HIVE/USDT from whitelist, because rate of change over 10 days is 2.929, which is above the threshold of 1.0.
> freqtrade     | 2021-11-27 16:21:16,319 - RangeStabilityFilter - INFO - Removed SFP/USDT from whitelist, because rate of change over 10 days is 1.126, which is above the threshold of 1.0.
> freqtrade     | 2021-11-27 16:21:16,319 - RangeStabilityFilter - INFO - Removed THETA/USDT from whitelist, because rate of change over 10 days is 445.820, which is above the threshold of 1.0.
> freqtrade     | 2021-11-27 16:21:16,320 - RangeStabilityFilter - INFO - Removed VET/USDT from whitelist, because rate of change over 10 days is 177.804, which is above the threshold of 1.0.
> freqtrade     | 2021-11-27 16:21:16,320 - RangeStabilityFilter - INFO - Removed POND/USDT from whitelist, because rate of change over 10 days is 6.260, which is above the threshold of 1.0.
> freqtrade     | 2021-11-27 16:21:16,321 - RangeStabilityFilter - INFO - Removed JST/USDT from whitelist, because rate of change over 10 days is 10.589, which is above the threshold of 1.0.
> freqtrade     | 2021-11-27 16:21:16,321 - RangeStabilityFilter - INFO - Removed KEEP/USDT from whitelist, because rate of change over 10 days is 4.722, which is above the threshold of 1.0.
> freqtrade     | 2021-11-27 16:21:16,322 - RangeStabilityFilter - INFO - Removed COCOS/USDT from whitelist, because rate of change over 10 days is 8.703, which is above the threshold of 1.0.
> freqtrade     | 2021-11-27 16:21:16,322 - RangeStabilityFilter - INFO - Removed CVC/USDT from whitelist, because rate of change over 10 days is 100.135, which is above the threshold of 1.0.
> freqtrade     | 2021-11-27 16:21:16,323 - RangeStabilityFilter - INFO - Removed ALGO/USDT from whitelist, because rate of change over 10 days is 34.908, which is above the threshold of 1.0.
> freqtrade     | 2021-11-27 16:21:16,323 - RangeStabilityFilter - INFO - Removed MITH/USDT from whitelist, because rate of change over 10 days is 3.247, which is above the threshold of 1.0.
> freqtrade     | 2021-11-27 16:21:16,324 - RangeStabilityFilter - INFO - Removed AXS/USDT from whitelist, because rate of change over 10 days is 1659.900, which is above the threshold of 1.0.
> freqtrade     | 2021-11-27 16:36:32,135 - freqtrade.freqtradebot - INFO - Active pair whitelist is empty.

```
import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame

from freqtrade.strategy.interface import IStrategy
from freqtrade.strategy import IStrategy, merge_informative_pair, informative

import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib

class example(IStrategy):
    INTERFACE_VERSION = 2

    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi".
    minimal_roi = {
        #"4320": 0.01,
        #"300": 0.01,
        #"60": 0.04, # 0.01
        #"30": 0.06, # 0.02
        "0": 0.50 # 0.04
    }

    # Optimal stoploss designed for the strategy.
    # This attribute will be overridden if the config file contains "stoploss".
    stoploss = -0.06 # -0.05

    # Trailing stoploss
    trailing_stop = True
    trailing_only_offset_is_reached = True
    # trailing_stop_positive = 0.005
    trailing_stop_positive = 0.0005
    trailing_stop_positive_offset = 0.015
    #trailing_stop_positive_offset = 0.015

    # Optimal timeframe for the strategy.
    timeframe = '5m'

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = False

    # These values can be overridden in the "ask_strategy" section in the config.
    use_sell_signal = False
    sell_profit_only = True
    ignore_roi_if_buy_signal = True

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 200

    # Optional order type mapping.
    order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }

    # Optional order time in force.
    order_time_in_force = {
        'buy': 'gtc',
        'sell': 'gtc'
    }

    plot_config = {
        # Main plot indicators (Moving averages, ...)
        'main_plot': {
            'tema': {},
            'sar': {'color': 'white'},
        },
        'subplots': {
            # Subplots - each dict defines one additional plot
            "MACD": {
                'macd': {'color': 'blue'},
                'macdsignal': {'color': 'orange'},
            },
            "RSI": {
                'rsi': {'color': 'red'},
            }
        }
    }

    @informative('1d')
    def populate_indicators_1d(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)

        return dataframe

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Adds several different TA indicators to the given DataFrame

        Performance Note: For the best performance be frugal on the number of indicators
        you are using. Let uncomment only the indicator you are using in your strategies
        or your hyperopt configuration, otherwise you will waste your memory and CPU usage.
        :param dataframe: Dataframe with data from the exchange
        :param metadata: Additional information, like the currently traded pair
        :return: a Dataframe with all mandatory indicators for the strategies
        """

        # Momentum Indicators
        # ------------------------------------

        dataframe['rsi'] = ta.RSI(dataframe)

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[ # Breakout: TEMA crosses over longer TEMA
            (
                (dataframe['rsi'] > 80) & (dataframe['rsi_1d'] > 80)
            ),
            'buy'] = 1
 
        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the sell signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                (dataframe['rsi'] < 1) & (dataframe['rsi_1d'] < 1)
            ),
            'sell'] = 1
        return dataframe

```

config:
```
{
    "max_open_trades": 2,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio":0.9,
    "dry_run_wallet":100.0,
    "fiat_display_currency": "USD",
    "timeframe": "5m",
    "dry_run": true,
    "stoploss": -0.347,
    //"stoploss": "market",
    //"stoploss_on_exchange": true,
    //"stoploss_on_exchange_interval": 60,
    //"stoploss_on_exchange_limit_ratio": 0.99,

    "cancel_open_orders_on_exit": false,
    "unfilledtimeout": {
        "buy": 5,
        "sell": 1
    },
    "bid_strategy": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": false
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
        "pair_whitelist": [
            "BTC/USDT"
        ],
        "pair_blacklist": [
            //"BNB/BTC",
            //"TFUEL/BTC",
            "BUSD/USDT",
            "BNBUP/USDT",
            "USDC/USDT",
            "FIL/USDT",
            "WIN/USDT",
            //"ONE/BTC",
            //"ATOM/BTC",
            //"XMR/BTC",
            "NPXS/USDT",
            "BNB/BUSD",
            "BNB/BTC",
            "BNB/ETH",
            "BNB/EUR",
            "BNB/NGN",
            "BNB/PAX",
            "BNB/RUB",
            "BNB/TRY",
            "BNB/TUSD",
            "BNB/USDC",
            "BNB/USDS",
            "BNB/USDT",
            "EUR/USDT",
            ".*UP/USDT",
            ".*DOWN/USDT",
            ".*BEAR/USDT",
            ".*BULL/USDT",
            "DOGE/USDT",
            "BRD/BTC", // blacklist added worst pair
        ]
    },


    "pairlists": [
    {
      "method": "VolumePairList",
      "number_assets": 70,
      "sort_key": "quoteVolume",
      "refresh_period": 1800
    },
    {
      "method": "AgeFilter",
      "min_days_listed": 10
    },
    {
      "method": "PrecisionFilter"
    },
    {
      "method": "PriceFilter",
      "min_price": 0.005,
      "low_price_ratio": 0.01
    },
    {
      "method": "SpreadFilter",
      "max_spread_ratio": 0.005
    },
    {
      "method": "PerformanceFilter"
    },
    {
      "method": "RangeStabilityFilter",
      "lookback_days": 10,
      "min_rate_of_change": 0.01,
      "max_rate_of_change": 1.0,
      "refresh_period": 300
    },
    {
        "method": "VolatilityFilter",
        "lookback_days": 10,
        "min_volatility": 0.013,
        "max_volatility": 0.50,
        "refresh_period": 86400
    },
    {
      "method": "VolumePairList",
      "number_assets": 50,
      "sort_key": "quoteVolume",
      "refresh_period": 1800
    },
  ],

    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8088,
        "verbosity": "error",
        "jwt_secret_key": "somethingrandom",
        "CORS_origins": [],
        "username": "admin",
        "password": "admin"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}`
```

**Comment by ghost** [comment]
I don't know how many times I tried to opt out this b*******

Al Berg

**Comment by xmatthias** [comment]
@jberg18671982 your email actually contains an "unsubscribe" link - so i guess simply clicking that will unsubscribe you.

You can also click the "unwatch" button on the github page of this repository to no longer be notified on changes in this repository.
It's however up to you - we can do nothing for you in this regards (notification settings are user-based - not repository based) - so from our end, we got no way to remove you from any subscriptions.

**Comment by swelbyboy** [comment]
Hi, 

Was this issue resolved with: https://github.com/freqtrade/freqtrade/commit/409a80176320a7d934eb5159faf35cb2a1ae9989?

I am still seeing this issue today (with NFI strategy) after I pulled the latest develop image this morning

Thanks
