### ISSUE TITLE
[HELP] Unable to connect to localhost:8080

### ISSUE THREAD

**Issue by 5ean4cademic** [freqtrade/freqtrade#5986]
yes

## Describe your environment

  * Operating system: _Win11___
  * Python Version: ___3.8__ (`python -V`)
  * CCXT version: _(docker, idk)____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _2021.11___ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
I setup the docker installation from the quick-start guide and tried to connect to the localhost at port 8080 but it failed to connect.
My config is as following:
  ? File user_data/config.json already exists. Overwrite? Yes
  ? Do you want to enable Dry-run (simulated trades)? Yes
  ? Please insert your stake currency: USDT
  ? Please insert your stake amount (Number or 'unlimited'): 100
  ? Please insert max_open_trades (Integer or 'unlimited'): unlimited
  ? Tim Have the strategy define timeframe.
  ? Please insert your display Currency (for reporting): USD
  ? Select exchange binance
  ? Do you want to enable Telegram? No
  ? Do you want to enable the Rest API (includes FreqUI)? Yes
  ? Insert Api server Listen Address (0.0.0.0 for docker, otherwise best left untouched) 127.0.0.1
  ? Insert api-server username freqtrader
  ? Insert api-server password ******
container freqtrade started

docker-compose.yml:
[docker-compose.txt](https://github.com/freqtrade/freqtrade/files/7613432/docker-compose.txt)
config.json:
[config.txt](https://github.com/freqtrade/freqtrade/files/7613435/config.txt)

do I need to do something with the firewall?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Based on your answers, i'd say your listen address is wrong.
Your config has this correct  ... but without logs, it's difficult to tell.

You should however make sure to follow the [docker quickstart](https://www.freqtrade.io/en/stable/docker_quickstart/#docker-quick-start) guide  - and start the container with `docker-compose up -d`. `docker-compose run will by default NOT expose any ports.

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.

**Comment by hoangtruong2412** [comment]
Hi! I have the same problem, can someone help me, I use raspberry Pi4

**Comment by xmatthias** [comment]
@hoangtruong2412 The answer didn't change, neither did the documentation link.
