### ISSUE TITLE
can i to know buy tag in confirm_trade_entry()

### ISSUE THREAD

**Issue by anakein** [freqtrade/freqtrade#5987]
I would like to know if it is possible to know the buy tag before confirming the purchase in the confirm_trade_entry () function.

the buy_tag is previously recorded in the purchase conditions.

thanks

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

The [buy tag](https://www.freqtrade.io/en/stable/strategy-advanced/#buy-tag) documentation shows that you can access the buy-tag on a trade-object via `trade.buy_tag`.

For `confirm_trade_entry()` this will not work as the trade-object is not yet available. You can however combine this knowledge with the [dataframe access](https://www.freqtrade.io/en/stable/strategy-advanced/#dataframe-access) method, retrieve the latest candle and get the buy-signal from there
 with `last_candle['buy_tag']`.
