### ISSUE TITLE
strategy run error

### ISSUE THREAD

**Issue by tabwnymhmd** [freqtrade/freqtrade#5988]
## Describe your environment

  * Operating system: ____`Microsoft Windows [Version 10.0.19042.1348]`
  * Python Version: _____ (`python -3.10.0`)
  * Freqtrade Version: ____ (`freqtrade - 2021.10`)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**HELLO
when I am trying to run this strategy, I get wrong how can I fix it 
this  the strategy**
>
    # pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement
    # flake8: noqa: F401
    # isort: skip_file
    # --- Do not remove these libs ---
    import numpy as np  # noqa
    import pandas as pd  # noqa
    from pandas import DataFrame
    
    from freqtrade.strategy import (BooleanParameter, CategoricalParameter, DecimalParameter,
                                    IStrategy, IntParameter)
    
    import pandas_ta as pt
    import talib.abstract as ta
    import freqtrade.vendor.qtpylib.indicators as qtpylib
    
    
    # This class is a sample. Feel free to customize it.
    class rsi2Strategy(IStrategy):
    
        # Strategy interface version - allow new iterations of the strategy interface.
        # Check the documentation or the Sample strategy to get the latest version.
        INTERFACE_VERSION = 2
    
        # Minimal ROI designed for the strategy.
        # This attribute will be overridden if the config file contains "minimal_roi".
        minimal_roi = {
            "60": 0.01,
            "30": 0.02,
            "0": 0.04
        }
    
        # Optimal stoploss designed for the strategy.
        # This attribute will be overridden if the config file contains "stoploss".
        stoploss = -0.10
    
        # Trailing stoploss
        trailing_stop = False
        # trailing_only_offset_is_reached = False
        # trailing_stop_positive = 0.01
        # trailing_stop_positive_offset = 0.0  # Disabled / not configured
    
        # Hyperoptable parameters
    
        # Optimal timeframe for the strategy.
        timeframe = '5m'
    
        # Run "populate_indicators()" only for new candle.
        process_only_new_candles = False
    
        # These values can be overridden in the "ask_strategy" section in the config.
        use_sell_signal = True
        sell_profit_only = False
        ignore_roi_if_buy_signal = False
    
        # Number of candles the strategy requires before producing valid signals
        startup_candle_count: int = 30
    
        # Optional order type mapping.
        order_types = {
            'buy': 'limit',
            'sell': 'limit',
            'stoploss': 'market',
            'stoploss_on_exchange': False
        }
    
        # Optional order time in force.
        order_time_in_force = {
            'buy': 'gtc',
            'sell': 'gtc'
        }
    
        plot_config = {
            'main_plot': {
                'tema': {},
                'sar': {'color': 'white'},
            },
            'subplots': {
                "MACD": {
                    'macd': {'color': 'blue'},
                    'macdsignal': {'color': 'orange'},
                },
                "RSI": {
                    'rsi': {'color': 'red'},
                }
            }
        }
    
        def informative_pairs(self):
            return []
    
        def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
            dataframe["change"] = dataframe["close"].shift() - dataframe["close"]
            dataframe["max"] = max(dataframe["change"],0)
            dataframe["min"] = - min(dataframe["change"],0)
            dataframe["up"] = pt.rma(dataframe["max"],2)
            dataframe["down"] = pt.rma(dataframe["min"],2)
            dataframe["ma5"] = ta.SMA(dataframe["close"],5)
            dataframe["ma200"] = ta.SMA(dataframe["close"],200)
    
            if dataframe["down"] == 0 :
                dataframe["rsi"] = 100
            else :
                if dataframe["up"] == 0 :
                    dataframe["rsi"] = 0
                else :
                    dataframe["rsi"] = 100 - (100/(1+(dataframe["up"]/dataframe["down"])))
    
            return dataframe
    
        def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
            dataframe.loc[
                (
                    (dataframe["close"]>dataframe["ma200"])
                    &(dataframe["close"]<dataframe["ma5"])
                    &(dataframe["rsi"]<10)
                ),
                'buy'] = 1
    
            return dataframe
    
        def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
            dataframe.loc[
                (
                    (dataframe["close"]<dataframe["ma200"])
                    &(dataframe["close"]>dataframe["ma5"])
                    &(dataframe["rsi"]>90)
                ),
                'sell'] = 1
            return dataframe
>    

**and this is the wrong**

>
    2021-11-28 13:33:28,552 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
    2021-11-28 13:33:28,553 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy rsi2Strategy
    2021-11-28 13:33:28,557 - freqtrade - ERROR - Fatal exception!
    Traceback (most recent call last):
      File "/freqtrade/freqtrade/main.py", line 37, in main
        return_code = args['func'](args)
      File "/freqtrade/freqtrade/commands/optimize_commands.py", line 54, in start_backtesting
        backtesting.start()
      File "/freqtrade/freqtrade/optimize/backtesting.py", line 655, in start
        min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
      File "/freqtrade/freqtrade/optimize/backtesting.py", line 610, in backtest_one_strategy
        preprocessed = self.strategy.advise_all_indicators(data)
      File "/freqtrade/freqtrade/strategy/interface.py", line 822, in advise_all_indicators
        return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
      File "/freqtrade/freqtrade/strategy/interface.py", line 822, in <dictcomp>
        return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
      File "/freqtrade/freqtrade/strategy/interface.py", line 845, in advise_indicators
        return self.populate_indicators(dataframe, metadata)
      File "/freqtrade/user_data/strategies/rsi_2_strategy.py", line 121, in populate_indicators
        dataframe["max"] = max(dataframe["change"],0)
      File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 1537, in __nonzero__
        raise ValueError(
    ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
>

**Comment by xmatthias** [comment]
This is now covered by the [documentation](https://www.freqtrade.io/en/stable/strategy-customization/#dataframe), which explains how to do comparisons with dataframes.

Simply put - you cannot use `if` as you are (more details and explanation in the linked documentation section).
