### ISSUE TITLE
Volume pairlist with lookback days doesn't work on Gate.io

### ISSUE THREAD

**Issue by dnuno89** [freqtrade/freqtrade#6003]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.10
  * CCXT version:1.61.92 
  * Freqtrade Version: 2021.11 

## Describe the problem:

When using a volume pairlist with lookbackdays on Gate.io the CLI shows many exceptions like this:
freqtrade.exchange.exchange - WARNING - Async code raised an exception: RuntimeError

A pairlist is obtained with very low pairs, and lacking some high volume pairs as BTC/USDT or ETH/USDT, so I consider it totally erroneous. The same configuration with other exchanges works fine, and clearing the lookback days configuration for Gate.io delivers a correct pairlist.

### Steps to reproduce:

1.- Add lookback days to volume pairlist configuration with Gate.io exchange.

  
### Observed Results:

Incorrect pairlist and warning.

### Relevant code exceptions or logs

Error seen in CLI:

freqtrade.exchange.exchange - WARNING - Async code raised an exception: RuntimeError

My pairlist configuration (as it fails on Gate.io) is:

"pairlists": [
        {
			"method": "VolumePairList",
			"number_assets": 135,
			"sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 86400,
            "lookback_days": 4
		},
		{"method": "AgeFilter", "min_days_listed": 27},
		{
			"method": "RangeStabilityFilter",
			"lookback_days": 3,
			"min_rate_of_change": 0.05,
			"refresh_period": 86400
		},
		{
			"method": "VolatilityFilter",
			"lookback_days": 4,
			"min_volatility": 0.015,
			"max_volatility": 0.75,
			"refresh_period": 86400
		},
        {"method": "ShuffleFilter"}
    ],

**Comment by xmatthias** [comment]
simply put - gate.io has too many pairs (1300+ USDT pairs alone).

A fix is not 100% straightforward, as that's simply a LOT of pairs.
you should however be able to work around this for now by applying a filter to reduce the amount of potential pairs to < 1000 before using the VolumePairlist with lookback.

**Comment by xmatthias** [comment]
I've tested your configuration with the commit that closed this PR and it does work fine now.
Would be great if you could let me know if that works for you, too (you'll need the develop version/branch, obviously).

**Comment by dnuno89** [comment]
It does work now, thanks!

However, I still think there is something wrong, I did a 150 pairlist with 4 lookbackdays and some pairs like Shiba Inu and Sand, which I expect should be there, aren't, while a lot of really low volume pairs are (I don't see this in kucoin with the same config).

I'll try to get more info and open a new issue if I find anything.

Best regards.
