### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by Ylelmon** [freqtrade/freqtrade#6004]
## Describe your environment

  * Operating system: _windows___
  * Python Version: _____3.7.0 (`python -V`)
  * CCXT version: ___1.62.54__ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __4.2.0 docker __ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

```
 Building wheel for py-find-1st (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\dell\appdata\local\programs\python\python37\python.exe' 'c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\DELL\AppData\Local\Temp\tmphoswvl46'
       cwd: C:\Users\DELL\AppData\Local\Temp\pip-install-tykvxffu\py-find-1st_e007d07d53174cba8d03b6461893cd6d
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\utils_find_1st
  copying utils_find_1st\__init__.py -> build\lib.win-amd64-3.7\utils_find_1st
  running build_ext
  building 'find_1st' extension
  C:\Users\DELL\AppData\Local\Temp\pip-build-env-e23yqpus\overlay\Lib\site-packages\setuptools\dist.py:720: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    % (opt, underscore_opt)
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for py-find-1st
Failed to build py-find-1st
ERROR: Could not build wheels for py-find-1st, which is required to install pyproject.toml-based projects
*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
```

**Comment by xmatthias** [comment]
Your issue does not really make sense. you seem to point out that you're running with docker, but the installation is from a native installation.

Both should work in theory (but i'd not recommend a native installation on windows unless you know what you're doing.
Exactly this error is also covered in the [windows installation guide](https://www.freqtrade.io/en/stable/windows_installation/#error-during-installation-on-windows) - simply following this should get you going.

One additional point - i'd recommend to go with a more recent version of python than 3.7. While we still support it, i can't guarantee for how long - so i'd recommend using python 3.8.

**Comment by Ylelmon** [comment]
Okay thx
