### ISSUE TITLE
Some warnings in backtesting

### ISSUE THREAD

**Issue by zorann** [freqtrade/freqtrade#6006]
## Describe your environment

  * Operating system: ____Linux
  * Python Version: _____2.7.18 - 3.8.10 (`python -V`)
  * CCXT version: _____1.56.30 (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____freqtrade docker-acb00cd0 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
I got this and error 156 from backtesting.
freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/CombinedBinHAndClucV4WS.py due to 'cannot import name 'Client' from 'binance' (/home/ftuser/.local/lib/python3.9/site-packages/binance.py)'

**Comment by xmatthias** [comment]
It's quit simple - the strategy you seem to use - `CombinedBinHAndClucV4WS` - is using something that's not installed.

As this is not an import from freqtrade, nor a strategy from our repository - please get in touch with the original source of this strategy for assistance on this.
