### ISSUE TITLE
Error 137 - killed by signal - SIGKILL

### ISSUE THREAD

**Issue by zorann** [freqtrade/freqtrade#6007]
## Describe your environment

  * Operating system: ____Linux
  * Python Version: _____3.8.6 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
I get this error by backtesting Error 137
freqtrade.optimize.backtesting - INFO - Backtesting with data from 2021-11-01 00:00:00 up to 2021-11-29 18:47:00 (28 days).
ERROR: 137

**Comment by xmatthias** [comment]
Please fill out the issue template.
The version can be important here.

"error 137" really only means that the process "was killed" (via SIGKILL) - which suggests that you probably ran out of memory (strange with this little timerange, but maybe its 1m timeframe and a lot of pairs?) and the system killed the process - but it's a suspicion (system level logs (journalctl, ...) should contain this information.

**Comment by zorann** [comment]
Ok thanks. But till now i never had this kind of problems. Last backtest run yesterday and today nothing, Only this error. Strange.

**Comment by xmatthias** [comment]
Operating systems usually kill processes that consume a lot of memory. backtesting CAN do that depending on the strategy, timerange and timeframe - so if memory becomes tight, it's usually a "first" target to kill to safe the system itself.
