### ISSUE TITLE
quiet argument. silence loggers `freqtrade -q`

### ISSUE THREAD

**Issue by innateessence** [freqtrade/freqtrade#6008]
Seems like a duplicate of https://github.com/freqtrade/freqtrade/issues/2408

I'd like it if the verbosity level was set to 1 by default, but if you appended a `-q` argument it would set the verbosity to 0 and silence all the loggers (or maybe 0 and -1)

It's possible I'll make a PR for this, but I might just live without it instead

**Comment by xmatthias** [comment]
To be honest, the loglevel is intentionally the way it is, so i don't currently see us changing this.

It might seem like a good idea to silence the logs while you're running without problems - but the moment you run into problems, you'll be glad you've had the logs - as there will be no support without logs (we can't support without that).

I think freqtrade is pretty well battle-tested - but from time to time there can be edge-cases which happen (either with different exchanges, or for other reasons) - so not having the logs will mean we'll have no possibility to investigate it further, and simply have to "hope it won't happen again".
While this same hope is true if users don't report problems - having the logs the way they are at least gives users the possibility to report the problem, and help with that.

Many of these edge-cases will only happen once every few weeks - so i don't really see any gain in having such an argument, only downsides.
