### ISSUE TITLE
`HealthCheck` API endpoint

### ISSUE THREAD

**Issue by MNThomson** [freqtrade/freqtrade#6009]
## Describe the enhancement

In the docs, I'm not seeing any `/api/v1/healthcheck` endpoint or whatnot (heartbeat specific, not referencing `ping`). Potentially returning the time of last heartbeat and any errors (if present).

This would be highly useful for monitoring and ensuring nothing crazy is going wrong. This would make monitoring from another server much easier and with some simple scripts, could alert the user immediately if either the server or the bot is down.

**Comment by xmatthias** [comment]
It's unclear what you'd expect about "crazy going wrong".
if something is "crazy going wrong" - the bot will stop working, which means ping will stop responding.
obviously it could check for the database connection - but that's about it.

Other errors (like exchange errors, api key errors, whatever else ...) are pretty difficult to reliably detect, as they can come in quite many different forms, and (if known) are also handled appropriately to avoid crashing the bot - so they won't bubble up to an overarching exception handler.

**Comment by MNThomson** [comment]
Fair point. Would be nice for peace of mind to get the last heartbeat time.

**Comment by eeddaann** [comment]
@xmatthias, what do you think about creating Prometheus exporter which will expose vital metrics?
I'm not sure if I should instrument the source code or should I decouple it and develop the exporter as a different project which will query the api.
what do you think?

**Comment by xmatthias** [comment]
I've got no idea what a "prometheus exporter" would imply - which makes it quite difficult to make an informed decision.
