### ISSUE TITLE
Trade fees and profit caclualtions incorrect when paying with POINTS on Gate

### ISSUE THREAD

**Issue by arcsur** [freqtrade/freqtrade#6013]
## Describe your environment

  * Operating system: Ubuntu 20.1
  * Python Version: 3.8.10
  * CCXT version: 1.61.92
  * Freqtrade Version: 2021.11
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

- When paying fees with POINT (gate prepaid fees) the calculated fee by freqtrade is ZERO.  This makes profit calcs off.
- It is noted that POINTS were purchased at a discount price (1 point = $1, however they are bought at a discount price)
- In addition, POINTS do not show up in the balance (This may or may not be desirable as they are not tradable back to other currencies.

### Steps to reproduce:

  1. Buy points on Gate.io
  2. Ensure paying with GT is *disabled* so that points are used
  3. Conduct trades and inspect the results
  
### Observed Results:

Extract from DB for an example trade:
```sql
sqlite> select * from trades where id=296;
                   id = 296
             exchange = gateio
                 pair = MBOX/USDT
              is_open = 0
             fee_open = 0.0
        fee_open_cost = 0.0
    fee_open_currency = USDT
            fee_close = 0.0
       fee_close_cost = 0.0
   fee_close_currency = MBOX
            open_rate = 13.35
  open_rate_requested = 13.352
     open_trade_value = 758.45355
           close_rate = 13.501
 close_rate_requested = 13.501
         close_profit = 0.01131086
     close_profit_abs = 8.578763
         stake_amount = 758.45355
               amount = 56.813
     amount_requested = 56.813
            open_date = 2021-12-01 06:15:31.493941
           close_date = 2021-12-01 07:21:12.025062
        open_order_id =
            stop_loss = 0.1335
        stop_loss_pct = -0.99
    initial_stop_loss = 0.1335
initial_stop_loss_pct = -0.99
    stoploss_order_id =
 stoploss_last_update = 2021-12-01 06:15:33.031400
             max_rate = 14.361
             min_rate = 12.769
          sell_reason = sell_profit_t_0_1 ( 38 )
    sell_order_status = closed
             strategy = NostalgiaForInfinityX
              buy_tag = 38
            timeframe = 5
```
### Relevant code exceptions or logs

```python
2021-12-01 06:15:31 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=None, pair=MBOX/USDT, amount=56.81300000, open_rate=13.35000000, open_since=2021-12-01 06:15:31) [buy]: 0 USDT - rate: 0.0
```
```python
2021-12-01 07:21:11 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=296, pair=MBOX/USDT, amount=56.81300000, open_rate=13.35000000, open_since=2021-12-01 06:15:31) [sell]: 0 MBOX - rate: 0.0
```
```python
2021-12-01 08:07:08 - freqtrade.rpc.rpc - WARNING -  Could not get rate for pair POINT.
```

**Comment by xmatthias** [comment]
> It is noted that POINTS were purchased at a discount price (1 point = $1, however they are bought at a discount price)

> 2021-12-01 08:07:08 - freqtrade.rpc.rpc - WARNING -  Could not get rate for pair POINT.

These 2 points do confirm what's happening.
Freqtrade correctly detects that you're using POINT to pay for fees.
It however can't determine a rate for POINT (there is apparently no POINT/USDT pair) - and therefore cannot convert this and assumes the fee to be free (if you look at kraken "points" - they were never available for purchase (nor sell), but were given out for free, so trading with them is effectively with 0 fees).

While we could assume a static rate for all "non-exchangable" currencies  (say 1)- this would be heavily error-prone - as it might be 1$ between POINT/USDT - but it would not be 1 for POINT/BTC (if your stake is BTC), and is therefore not scalable in a reliable way, especially since these rates may also change in the future (not sure how gate handles this, but i assume price is tied to USDT, not to BTC).

So for the moment, I'd not know how to properly handle this without introducing potentially more problems.
So unless you have some great idea how we can handle this (in a scalable way!), i think this will become something we'll simply note in the documentation for Gate.io.

**Comment by arcsur** [comment]
@xmatthias perhaps allow a static config parameter to define the rate for a pair that has an unknown rate? This would leave the problem of the rate cost in the user hands. It would still not be perfect but it is better than profit calcs being completely off.

**Comment by xmatthias** [comment]
I'm not sure that's a good approach - as it'll have a fixed rate for something that might change over time, so you'd have to constantly tweak that.

Profit calcs are also not "completely off" - they don't include fees - which are however usually around 0.2% (or even lower), so i'd call them "slightly off" at best.

**Comment by arcsur** [comment]
OK so perhaps "completely off" was a bit overly strongly worded. That said I would rather be able to minimise the innacuracy. If there was a way to configure it, it would be the end user's issue as to by how accurate the rate translation would be.

For myself, I would probably just set it at $1 per point. This would calculate fees correctly based on point deduction amounts for myself.

**Comment by mahmoudeA** [comment]
sqlite> select * from trades where id=296;
                   id = 296
             exchange = gateio
                 pair = MBOX/USDT
              is_open = 0
             fee_open = 0.0
        fee_open_cost = 0.0
    fee_open_currency = USDT
            fee_close = 0.0
       fee_close_cost = 0.0
   fee_close_currency = MBOX
            open_rate = 13.35
  open_rate_requested = 13.352
     open_trade_value = 758.45355
           close_rate = 13.501
 close_rate_requested = 13.501
         close_profit = 0.01131086
     close_profit_abs = 8.578763
         stake_amount = 758.45355
               amount = 56.813
     amount_requested = 56.813
            open_date = 2021-12-01 06:15:31.493941
           close_date = 2021-12-01 07:21:12.025062
        open_order_id =
            stop_loss = 0.1335
        stop_loss_pct = -0.99
    initial_stop_loss = 0.1335
initial_stop_loss_pct = -0.99
    stoploss_order_id =
 stoploss_last_update = 2021-12-01 06:15:33.031400
             max_rate = 14.361
             min_rate = 12.769
          sell_reason = sell_profit_t_0_1 ( 38 )
    sell_order_status = closed
             strategy = NostalgiaForInfinityX
              buy_tag = 38
            timeframe = 5
