### ISSUE TITLE
Volume in different units depending on exchange

### ISSUE THREAD

**Issue by dnuno89** [freqtrade/freqtrade#6015]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.10 (`python -V`)
  * CCXT version: 1.61.92(`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.11 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

The volume as given in Gate.io is in USD, while in KuCoin it is in amount of coins. I would expect to be all equal.

### Steps to reproduce:

Check the volume seen in freqtrade UI vs the exchange web.
  
### Observed Results:

I have selected some currencies with values different than 1, and compare the volume seen in freqtrade UI and what is shown in each web. KuCoin is clearly giving the value in amount while Gateio in USD, so some currencies display a huge change in volume.

For example, ETH/USD had a peak volume at 19:20 UT of approx 2.2 M$, which is correctly shown in my freqtrade bot operating on Gate.io. However, the bot operating in KuCoin shows a volume at the same time of only 1000 (which using the price of ETH is arround 4.5 M$, which is the value I would expect instead of 1000)

**Comment by xmatthias** [comment]
I'd encourage you to show this with screenshots (bot + exchange, for each exchange). 
You're pointing out "at 19:20" - but without a day/date, this could be any day. 
While it might be clear today (i assume you mean yesterday evening, but i'm honestly not sure) - if looked at tomorrow, it'd be completely different patterns..

Volume shown will ALSO depend on the timeframe - so please make sure to have that correct (and visible) as well.

---

in general though, i would say this is clearly a possibility
Freqtrade uses/shows volume "as provided" by the exchanges / ccxt.

I don't really see this as a big problem, as what you describe seems to be aligned to how the exchange is showing volume as well.

[gate.io](https://www.gate.io/docs/apiv4/en/#market-candlesticks) does not explain the unit of the volume field, [kucoin](https://docs.kucoin.com/#get-klines) on the other hand seems to contain both volume volume values.

This is also visible on the webpage - where one shows volume in millions (i assume that's USD/USDT) - and the other in 1000nds (i assume that's ETH). 

If any, this _could_ be a bug in ccxt's kucoin implementation (which however should then be reported to ccxt) - as their documentation states the following:
> // (V)olume (in terms of the base currency), float

[source](https://docs.ccxt.com/en/latest/manual.html#ohlcv-structure)

**Comment by dnuno89** [comment]
Sorry for the poorly documented issue. I now see that this is clearly related to CCXT, should I open an issue there?

I have temporarily corrected my volume stats by multiplying them with the price for kucoin, but I do not touch the original "volume" column as I understand it is updated periodically. Anyone interested in the "fix" i use:
if self.dp._config['exchange']['name']=='kucoin':
     informative['meanVol']=informative['volume'].rolling(window=4).mean()*typPrice
else:
     informative['meanVol']=informative['volume'].rolling(window=4).mean()



Picture from kucoin, Volume for a 5 minutes timeframe is 2476 ETH.

![image](https://user-images.githubusercontent.com/11979371/144489323-dc7c8a3c-e6a1-47de-a452-a27649e75e3a.png)

Picture from gateio, same timeframe, strategy, and exact moment... Here it shows a volume of 3.5 M USD.

![image](https://user-images.githubusercontent.com/11979371/144489383-98d5e755-4920-41ed-8695-7f5fcee1f0ed.png)

**Comment by xmatthias** [comment]
I'll leave further discussion about this to the ccxt issue, as there's really nothing freqtrade can do for this case.

Further testing shows that this is most likely happening for several different exchanges. 
I don't see it as a problem though, as it's 
a) aligned to how the exchange webpage displays the data
b) you're only comparing data from within one exchange 
c) you shouldn't use absolute volume values anyway - as that can/will change between values - and comparing a volume-MA with current volume should yield the same results, independent of the absolute value of the volumes.
