### ISSUE TITLE
Sensitive data is logged to the console for exchanges with extra ccxt_config parameters

### ISSUE THREAD

**Issue by samgermain** [freqtrade/freqtrade#6016]
## Describe your environment

  * Operating system: MacOS Monteray v12.0.1
  * Python Version: 3.9.5
  * CCXT version: 1.61.92
  * Freqtrade Version: develop-c0cc3f5f9
  
## Describe the problem:

Sensitive data is logged to the console for exchanges that take extra ccxt_config parameters in config.json. This could be a problem if anyone ever copies and pastes their console output and posts it online, or even if someone places their `apiKey` and `secret` in the wrong place in the configuration file

### Steps to reproduce:

  1. Create an ndax account
  2. Fill out the config file with the required credentials for NDAX

```
"exchange": {
    "name": "ndax",
    "ccxt_config": {
      "apiKey": "...",
      "secret": "...",
      "uid": "...",
      "login": "...",
      "password": "...",
      "twofa": "...",
      "enableRateLimit": true
    },
    "ccxt_async_config": {
      "enableRateLimit": false
    },
    "pair_whitelist": [],
    "pair_blacklist": []
  },
```
   3. Start a live trade using this config `freqtrade trade -c ./uncommon_exchange_config.json -s your_strategy`

### Observed Results:

```
2021-12-01 22:03:46,756 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {
'apiKey': '...', 'secret': '...', 'uid': '...', 'login': '...', 'password': '...', 'twofa': '...', 'enableRateLimit': True}
```

**Comment by xmatthias** [comment]
There is no reason to place `apiKey`, `secret`, `uid` or `password` into `ccxt_config` - and we're not recommending this anywhere in the documentation.

Freqtrade has seperate fields outside of `ccxt_config` for this which should be used, especially to avoid this problem, so if you don't want these secrets logged, please follow the documentation to configure these fields ([here](https://www.freqtrade.io/en/stable/configuration/#configuration-parameters) - search for `exchange.` for the full list))

This leaves `twofa` and `login` - which I've however not seen on any exchange so far.
While i trust you in knowing that it's required for NDAX - i don't see this as a problem at this point for two reasons:
* out of 6 fields, we're at maximum logging 2 fields - which is not enough for takeover.
* i strongly doubt ndax will work out of the box - while most exchanges should - it's rare that they "really" do without at least a little bit of configuration/tuning (like defining the max candle amount it gives per call).

Should we ever add this exchange to the supported exchanges (either community supported, or project supported) - we can provide the same method we do for the other 4 fields.

As NDAX is not even listed on coinmarketcap under exchanges (it exists, but without any data) - i doubt we'll be adding it anytime soon, as i simply consider it a non-relevant exchange at this point.


**edit**
i've just realzed that "uid" is missing from the documentation - which i'll obviously add.
I'll also add a warning to the "ccxt_config" section, to not put secrets there, but use the correct fields.
