### ISSUE TITLE
"load=False" is not restricted to hyperopt

### ISSUE THREAD

**Issue by algeronwaterschoot** [freqtrade/freqtrade#6022]
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.8
  * CCXT version: 1.56.30
  * Freqtrade Version: develop-57ff7e8fe
  
## Describe the problem:

Strategy parameters (`IntParameter`, `DecimalParameter` etc) have a `load` property which determines whether the value of a parameter should be loaded from file (`True`) or resort to the default value for that parameter (`False`). I use `load=random() < 0.95` and `optimize=random() < 0.5` to iteratively optimize a large set of parameters while introducing some level of "forgetfulness" to avoid overfitting.
However, the behavior of the `load` property also gets expressed during backtesting.
Maybe I misunderstood the intent or use-case of using `load` in a strategy, but given that `optimize` is specific to the context of hyperopting, I was surprised to discover that this is not the case for `load`.

### Steps to reproduce:

  1. Add `load=False` to all strategy parameters
  2. Run hyperopt once
  3. Run backtest once
  
### Observed Results:

  * What happened?
  Backtest uses default parameter values.

  * What did you expect to happen?
  Backtest uses parameter values from file.

**Comment by xmatthias** [comment]
The behavior of "load" is intended to be this way, and you should look at it disconnected from the "optimize" parameter, as it only has limited meaning for hyperopt.

Setting `load=False` during  hyperopt only makes sense in one case - if you do not want to optimize this value -  and don't want to use the value from the file, but use the "standard" that's defined for the parameter.
To iterate over parameters one by one, load is not really relevant (and should probably not be used) - if you do use it, you'd ignore all prior results - which i somehow doubt is what you desire to do.
If you want to optimize one parameter after the other - you should instead use optimize (enabled for that parameter) - but leave "load" for all others to true.
As you move through the parameters, prior results will be applied for the already optimized parameters.


for backtesting/live however, setting `load=False` can allow you to manually try different values (by changing the default value) without loading it from the settings / file.

Now it'll obviously change results from hyperopt to backtesting (assuming the parameter was optimized, and is now excluded) - but this way you can easily determine the impact of each parameter.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
