### ISSUE TITLE
protections custom activate

### ISSUE THREAD

**Issue by anakein** [freqtrade/freqtrade#6032]
## Describe your environment

  * Operating system: ____raspberry buster
  * Python Version: _____ (`3.9`)
  * CCXT version: _____ (`1.63`)
  * Freqtrade Version: ____ last develop branch
  
Hello;

In my own strategy, I have the protections plugins active.
    @property
    def protections(self):
        return [
            {
                "method": "CooldownPeriod",
                "stop_duration": 144
            },
            {
                "method": "StoplossGuard",
                "lookback_period": 90,
                "trade_limit": 2,
                "stop_duration": 90,
                "only_per_pair": False
            },
..........
reading protections docs, say:  StoplossGuard considers all trades with the results "stop_loss", "stoploss_on_exchange" and "trailing_stop_loss" if the resulting profit was negative. trade_limit and lookback_period will need to be tuned for your strategy.

I have also custom_sell() function, one of the options is to detect a deadfish trade and sell it at a loss, and I would like it to activate protections stoploss and when i have 2 trade at loss ( stop trade for 90 minutes). 

How could it be done?.

thanks

**Comment by xmatthias** [comment]
You can either manually [lock pairs](https://www.freqtrade.io/en/stable/strategy-customization/#locking-pairs-from-within-the-strategy) - or use one of the above mentioned results as sell reason (just name it exactly the same).

using custom sell signal names with this protection is not supported.

**Comment by anakein** [comment]
and then understand i have to put into custom_sell function
return "stop_loss"

**Comment by xmatthias** [comment]
That's correct.
it will however make this sell show up as regular stoploss.

**Comment by anakein** [comment]
ok, but...
An extension to freqtrade could be considered, that stop_loss_xxxxx can be used in the future to activate the protection plugin and also we can save it as a tag.

thank you very much
