### ISSUE TITLE
How to maintain disc usage 

### ISSUE THREAD

**Issue by KaanRF** [freqtrade/freqtrade#6036]
## Describe your environment

  * Operating system: openhabian(debian-buster)
  * Python Version: 3.7 (Python 3.8 is available but had a problem with TA-Lib 0.4.21 during installation then I have used the version of TA-Lib 0.4.18 with python3.7)
  * CCXT version: --
  * Freqtrade Version: 2021.11
  
## Your question
Hi, 
I am running the freqtrade on my raspberry pi and currently with dry_wallet option. I just curious that is there any automatic disc usage maintanence exist on the freqtrade, so far I did not see. 
And I want to also sum here the ideas in which location cached the informations, for an example my user_data/data/binance folder is completly empty. 

I was also wondering whether if some already know about the libraries what we used like TA or pandas are cache a lot information ?  
Since I am also using the virtual env maybe there is also some cached/unused/old data that I can autoamatically clean to have free disc space for long term. 

BR

**Comment by xmatthias** [comment]
When running freqtrade in dry-run mode, it'll not write anything to disk other than the database (and eventually log files, which do however rotate by default).

data in `user_data/data/` are used for backtesting/hyperopt, not for dry/live runs.

you can obviously delete these files if you require diskspace, but that will limit your ability to run longer-term backtests. 
As this data is intended to be built up over time (so you have more history available) - freqtrade does not provide any cleanup methods.
