### ISSUE TITLE
VolumePairList not allowed for backtesting. Please use StaticPairlist instead.

### ISSUE THREAD

**Issue by jethob24** [freqtrade/freqtrade#6039]
Please help me to resolve this issue. i am currently following the video tutorial about crypto bot, Chapter 10, lesson 5, 04:28 on video course on Udemy, I got an error : VolumePairList not allowed for backtesting. Please use StaticPairlist instead.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

I'm not aware of an official "video tutorial" - so it's unclear what you're following (maybe provide a link ?)

I think the message is very clear - you're not allowed to use VolumePairlist, and should use StaticPairlist instead.
Instructions for configuration can be found in the [documentation](https://www.freqtrade.io/en/stable/plugins/#static-pair-list).

**Comment by jethob24** [comment]
Thank you for responding.
A video from Udemy Course.
https://www.udemy.com/course/build-a-crypto-bot-100-functional-algorithmic-trading-freqtrade/
![image](https://user-images.githubusercontent.com/90668749/145565909-3b52d233-602b-4b17-b0e7-05126ac391f2.png)

**Comment by xmatthias** [comment]
mmh interresting (new to me though).

I think the best approach is then to get support from the course author (apparently it's not well explained - so it should be something they should probably change) - or stick to the documentation linked above.

**Comment by ksyao2002** [comment]
You need to change the "pairlists" field in config.json in user_data/ to StaticPairList like below:

"pairlists": [
        {
            "method": "StaticPairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],

**Comment by xmatthias** [comment]
@ksyao2002 the only valid key for "StaticPairList" is method. All other entries you have there will be ignored.
