### ISSUE TITLE
Protections - MaxDrawDown

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#6054]
very quick and short question regading the "Stoploss Guard" - it is documented, but just to be sure that I got the right understanding.

The max DD is being calculated as simple cumulative loss? e.g. my bot is running two times with two trades in a stop loss of -10% = -20% in total, means the "max_allowed_drawdown": 0.2 condition is true, correct?

What about the "trade_limit": 20 condition ... this would not be true as I just have two trades, correct? Two have the protection being active I would need for example 20 x -1% trades having 20 trades and a DD of 20% ... is this the right understanding?

```
The below sample stops trading for 12 candles if max-drawdown is > 20% considering all pairs - with a minimum of trade_limit trades - within the last 48 candles. If desired, lookback_period and/or stop_duration can be used.

@property
def protections(self):
    return  [
        {
            "method": "MaxDrawdown",
            "lookback_period_candles": 48,
            "trade_limit": 20,
            "stop_duration_candles": 12,
            "max_allowed_drawdown": 0.2
        },
    ]
```

**Comment by xmatthias** [comment]
The guard will only trigger if you had `trade_limit` pairs closed within `lookback_period_candles`.

So in your sample - it'd be 20 trades within the last 48 candles.

Drawdown is calculated identically to the way the relative value is calculated for backtesting.

**Comment by Prossi79** [comment]
okay, clear - thank you Matthias!
