### ISSUE TITLE
PerformanceFilter 'min_profit' example value in the docs should be a percentage not a ratio

### ISSUE THREAD

**Issue by perkmeister** [freqtrade/freqtrade#6056]
The docs show "min_profit": 0.01 for PerformanceFilter as an example, but it should actually be a percentage not a ratio. The Trade.get_overall_performance() method that this filter uses returns a percentage not a ratio. I think some explanation should be there as I think most people would assume 0.01 is a ratio as 0.01% is tiny.

**Comment by xmatthias** [comment]
The correct fix is actually to change the used field to `profit_ratio` instead of `profit` (this is how it was originally).

`profit` changed quite recently (about a month ago) to be multiplied by 100 - , and apparently this dependency was overlooked.

**Comment by perkmeister** [comment]
OK, thanks Matthias.
