### ISSUE TITLE
[ccxt] Fee calculation causes Binance selling to fail

### ISSUE THREAD

**Issue by enenn** [freqtrade/freqtrade#606]
### The problem
When running the bot on Binance using the ccxt library (#230) and BNB fees disabled, the bot will show an InsufficientFunds error when trying to sell a previously opened trade.

This is caused by the difference in fee calculation between Binance and Bittrex. The bot is programmed assuming that the fees are subtracted from the currency you are exchanging **from**. On Binance and most other exchanges, fees are subtracted from the currency  you are exchaning **to** For instance, say you have 1 ETH and are buying 0.5 LTC at a rate of 1 LTC/ETH, with 1% fees. 

**On Bittrex (expected and actual):**
1 ETH -> (buy 0.5 LTC) -> 0.495 ETH, 0.5 LTC ->  (sell 0.5 LTC)  -> 0.99 ETH

**On Binance (expected):**
1 ETH -> (buy 0.5 LTC) -> 0.5 ETH, 0.495 LTC ->  (sell 0.495 LTC)  -> 0.99005 ETH (0.5 + (1-0.01)*0.495)

**On Binance (actual):**
1 ETH -> (buy 0.5 LTC) -> 0.5 ETH, 0.495 LTC ->  (sell 0.5 LTC)  -> **Insufficient funds**

**On Binance with BNB fees (expected and actual):**
1 ETH, 1 BNB -> (buy 0.5 LTC) -> 0.5 ETH, 0.5 LTC, 0.99... BNB ->  (sell 0.5 LTC)  -> 1 ETH, 0.98... BNB

This issue is also a more general problem that will affect other exchanges, and the fee handling/calculation should be overhauled to make fewer assumptions.

The function `calculate_fee` from ccxt returns information about where the fee was subtracted, but does not seem to handle BNB fees. For example, selling 0.5 LTC to ETH with 0.1% fees correctly gives the below output, which shows that fees are subtracted from LTC when buying and ETH when selling. But it does not make any request to Binance and so does not know if you have BNB fees enabled.

```
>>> import ccxt
>>> bin = ccxt.binance()
>>> bin.load_markets()
>>> bin.calculate_fee(symbol='LTC/ETH', type='limit', side='buy', amount=0.5, price=1)

{
  'type': 'taker',
  'currency': 'LTC',
  'rate': 0.001,
  'cost': 0.0005
}

>>> bin.calculate_fee(symbol='LTC/ETH', type='limit', side='sell', amount=0.5, price=1) 

{
  'type': 'taker', 
  'currency': 'ETH',
  'rate': 0.001, 
  'cost': 0.0005
}
```

### Environment
Branch: feat/objectify-ccxt

### Steps to reproduce:

  1. Disable BNB fees on your account on Binance
  2. Run the bot normally (not in dry run mode) and wait until it tries to make a sell
  3. Insufficient funds error

  ```
2018-04-11 12:39:31,695 - freqtrade - INFO - DEBUG: Tyring to sell pair NEO/BTC... 
2018-04-11 12:39:31,861 - freqtrade - WARNING - Got Insufficient funds to create limit sell order on market NEO/BTC.Tried to sell amount 0.59 at rate 0.007882 (total 0.00465038).Message: binance {"code":-2010,"msg":"Account has insufficient balance for requested action."} in _process(), retrying in 30 seconds...
  ```

### Intended outcome

The bot should compensate for any amount lost for fees after the buy order is fully filled, no matter where the fees come from (target, base, or elsewhere, like BNB).

### Possible solutions

The fee could possibly be extracted from the order object, but this is incomplete so far. See [ccxt docs](http://ccxt.readthedocs.io/en/latest/manual.html#order-structure)

Since you are not sure until after the trade where the fees came from, the closed buy order could be queried and the correct amount updated in the bot database. For BNB fees this is particularily true, since there is no way to know if the user is running BNB fees enabled or not, or if there is sufficient BNB in the account, before the order is placed.

`calculate_fee` could also be used in some way to prevent making requests on exchanges where it makes sense, but is less bulletproof than actually checking after the order is filled.

**Comment by enenn** [comment]
@xmatthias is working on a fix for this https://github.com/xmatthias/freqtrade/tree/cxt_obj_sellfix

Suggestions and ideas on the best way to deal with this problem is appreciated

**Comment by xmatthias** [comment]
I had an idea for this - but I think it will require a DB change.
With the current Database structure, we only have `open_rate`, `amount` and `fee` (which are related to this, anyway). 
The problem with that is that we won't know if the fee was applied on sell even if we update the amount to the correct value after the trade has been executed as shown [here](https://github.com/xmatthias/freqtrade/blob/cxt_obj_sellfix/freqtrade/freqtradebot.py#L365-L410).
The only way I see with this structure would be to update the `fee` column to the half of the original fee (if it was applied) - but I don't think that makes sense as it obfuscates the fee.

I would split the fee-column into 2 - `fee-buy` and `fee-sell` - and use these for the calculation (some exchanges may different fees for buy and sell - not sure if that's really the case, but it would avoid the hacky way above).

**slippage detect**
As a DB change will require a migration / resetup of databases anyway, I'd also like to propose a 2nd column `open_rate_orig` to detect / analyze slippage (maybe the same for `close_rate_orig`?).
Initially, this rate would default to the `open_rate` column, which currently is updated to the real buy value to account for slippage. While correct for most calculations, it removes the possibiity to detect if a strategy / coin is heavily impacted by slippage. 

**slippage 2**
as a 2nd step, we could then add a script (or command or sql query) to analyze slippage, as i expect different exchanges/markets to behave quite differently in this regard, and it would be nice to analyze the bot for this behaviour.

While i don't like to combine these 2 changes, and the slippage one is not "really" related to ccxt, I think it does make sense to have them combined for the merge to develop (basically using 2 PR's against the ccxt branch) - as the DB change will require users to re-setup their DB (we don't have a sqlalchemy-migrate currently - and i would not introduce this as part of CCXT work).

**Comment by xmatthias** [comment]
i gave the above proposed solution a try - 
branch [obj_ccxt_fiat_fix](https://github.com/xmatthias/freqtrade/tree/obj_ccxt_fiat_fix) contains a draft of the proposed changes (only part one - not slippage).

branch [obj_ccxt_fiat_fix_drymode](https://github.com/xmatthias/freqtrade/tree/obj_ccxt_fiat_fix_drymode) is what i currently run in dry-mode to test both stability and function / calculations. it fake-mocks the result of `get_trades_for_order` to fake a real result from the exchange. 
This will not be merged into the main repository, as it is 
a) not the correct approach for all exchanges
b) only a simple static test to test this in the long run.

work is not complete yet (therefore no PR so far) - it's missing a few tests and the function `maybe_update_real_amount` is probably not needed (it's currently not called from anywhere other than a few tests).

**Comment by xmatthias** [comment]
#623 fixed this issue
