### ISSUE TITLE
Startup Log is showing sensitive information (database string connection user/password)

### ISSUE THREAD

**Issue by mejiafabiandj** [freqtrade/freqtrade#6069]
## Describe your environment

  * Operating system: ____UBUNTU 20.4
  * Python Version: _____python3.9
  * CCXT version: _____ ccxt==1.61.92
  * Freqtrade Version: ____ freqtrade 2021.11
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I’m using postgresql+psycopg2 database, when an instance is started up or config is reloaded, log shows all string connection including raw sensitive information (username, password, port, and database name)
  
### Observed Results:

log shows raw sensitive information related to database string connection.

### Relevant code exceptions or logs

Following log has been modified to hide sensitive information

  ```
2021-12-13 22:35:21 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2021-12-13 22:35:21 - apscheduler.scheduler - INFO - Scheduler has been shut down
2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Using config: /freqtrade/user_data/config.json ...
2021-12-13 22:35:45 - freqtrade.loggers - INFO - Verbosity set to 0
2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2021-12-13 22:35:45 - freqtrade.configuration.configuration - WARNING - `forcebuy` RPC message enabled.
2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Using DB: "postgresql+psycopg2://<USERTNAME>:<MYSECRETPASSWORD>@<HOSTNAME>:<PORT>/<DATABASENAME>"
2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 25 ...
2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2021-12-13 22:35:45 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-12-13 22:35:45 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-12-13 22:35:45 - freqtrade.freqtradebot - INFO - Starting freqtrade develop
  ```
  ![image](https://user-images.githubusercontent.com/3708192/145900816-5930454b-6936-4347-8f1b-db32b0770c85.png)

**Comment by xmatthias** [comment]
Freqtrade has a method in `parse_db_uri_for_logging()` to obfuscate the password in the database string.

so `'postgresql+psycopg2://scott123:scott123@host:1245/dbname'` becomes `'postgresql+psycopg2://scott123:*****@host:1245/dbname'` - hiding the sensitive information in the url.

If this is not working for your URL, best provide a (modified) url (please test that it's still logged in clear text) so we can test your case specifically (i suspect it could happen with some characters in the password, but i'm not sure).

I've just tested this again (with a postgres url with port, as shown above) and it works just fine.

I'd honestly not consider the remaining information (username, hostname, port, database) as sensitive information, as that will at best give you security by obscurity - which you should definitely not rely on.

The logs are also not intended to be "publicly available" in general, and you should prevent that for sure.

On higher log-levels (`-vv` / `-vvv`), they will potentially also contain other sensitive information that could be used to connect to the exchange (because this log-level will be logging all requests made to the exchange api).

**Comment by Bat3an** [comment]
Wow

**Comment by Shahnavazi1985** [comment]
Re: [freqtrade/freqtrade] Startup Log is showing sensitive information (database string connection user/password) (Issue #6069)

**Comment by Shahnavazi1985** [comment]
lssue#6069

**Comment by Shahnavazi1985** [comment]
> 
> 
> ## Describe your environment
> 
>   * Operating system: ____UBUNTU 20.4
>   * Python Version: _____python3.9
>   * CCXT version: _____ ccxt==1.61.92
>   * Freqtrade Version: ____ freqtrade 2021.11
>   
> Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.
> 
> ## Describe the problem:
> 
> I’m using postgresql+psycopg2 database, when an instance is started up or config is reloaded, log shows all string connection including raw sensitive information (username, password, port, and database name)
>   
> ### Observed Results:
> 
> log shows raw sensitive information related to database string connection.
> 
> ### Relevant code exceptions or logs
> 
> Following log has been modified to hide sensitive information
> 
>   ```
> 2021-12-13 22:35:21 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
> 2021-12-13 22:35:21 - apscheduler.scheduler - INFO - Scheduler has been shut down
> 2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Using config: /freqtrade/user_data/config.json ...
> 2021-12-13 22:35:45 - freqtrade.loggers - INFO - Verbosity set to 0
> 2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
> 2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
> 2021-12-13 22:35:45 - freqtrade.configuration.configuration - WARNING - `forcebuy` RPC message enabled.
> 2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Dry run is enabled
> 2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Using DB: "postgresql+psycopg2://<USERTNAME>:<MYSECRETPASSWORD>@<HOSTNAME>:<PORT>/<DATABASENAME>"
> 2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 25 ...
> 2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
> 2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
> 2021-12-13 22:35:45 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
> 2021-12-13 22:35:45 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
> 2021-12-13 22:35:45 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
> 2021-12-13 22:35:45 - freqtrade.freqtradebot - INFO - Starting freqtrade develop
>   ```
>   ![image](https://user-images.githubusercontent.com/3708192/145900816-5930454b-6936-4347-8f1b-db32b0770c85.png)
>  
>

**Comment by Shahnavazi1985** [comment]
Chek my phone device

**Comment by xmatthias** [comment]
@Shahnavazi1985 please stop - this is not leading anywhere - and will have to lead to a ban, simply to avoid having our issue(s) cluttered.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
