### ISSUE TITLE
Missing Import and Module Source in strategy.py

### ISSUE THREAD

**Issue by ggould11** [freqtrade/freqtrade#6071]
-- Missing Import for numpy, freqtrade.strategy, talib.abstract, and freqtrade.vendor.qtpylib.indicators
-- Missing Source Module for pandas

These are underlined with the yellow warning line in both the sample-strategy.py file and my strategy file. 
I am using Python 3.10.1 64-bit in VSCode to interpret and that is the reason for the issue, but I don't know how to resolve this.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

your most likely cause is a wrongly selected interpreter in vscode. You can change interpreters in vscode by clicking on the Python version at the bottom - assuming a regular install (.setup.sh) - you should select the .venv within the freqtrade directory.

**Comment by ggould11** [comment]
Apologies. 

## Describe your environment

  * Operating system: _____ Windows 10 Home Build 19043
  * Python Version: _____ Python 3.9.7 64-bit
  * CCXT version: _____ ( `pip freeze | grep ccxt` )
  * Freqtrade Version: _____ 2021.9
  
## Your question

I have sinee switched from Python 3.10.1 to 3.9.7 because I saw that freqtrade did not yet support 3.10.x. I still have the warning lines after updating the freqtrade file using...
`docker-compose pull`
`docker-compose up -d`

Also, I don't know how to find the ccxt version using the line above. I am writing this line into the vscode terminal, and downloaded freqtrade using docker desktop.

**Comment by xmatthias** [comment]
VSCode will continue to highlight these imports. 
That's however not an issue, as it's vscode which cannot find the freqtrade files (they are in docker, not directly on your system).

Once you run your strategy within the docker-container, this will work fine.
