### ISSUE TITLE
Webhooks : add {coin} parameter

### ISSUE THREAD

**Issue by Sungray** [freqtrade/freqtrade#6075]
Right now it's impossible to get the coin only for webhook params. I can get the pair, the stake-currency, but not the coin.

This would allow us for instance to add this to the config :

```
    "webhook": {
        "enabled": true,
        "url": "https://api.telegram.org/bot<BOTTOKEN>/sendMessage",
        "webhookbuy": {
            "chat_id": "<CHATID>",
            "text": "https://trade.kucoin.com/trade/{coin}-{stake_currency}"
        }
    }
```
and get immediately an URL to follow the coin live on any exchange.

**Comment by xmatthias** [comment]
Freqtrade does not currently provide separate coin/stakecurrency variables for webhooks, and i honestly don't really see that happening anytime soon.

While it is possible and freqtrade has ways to correctly determine both sides of the coin - i don't see the effort for it justified (not for the implementation, and mainly not for running it as that would have to run for every user, even those that don't use webhooks, which in itself is only a very small portion).

**Comment by Sungray** [comment]
> Freqtrade does not currently provide separate coin/stakecurrency variables for webhooks, and i honestly don't really see that happening anytime soon.
> 
> While it is possible and freqtrade has ways to correctly determine both sides of the coin - i don't see the effort for it justified (not for the implementation, and mainly not for running it as that would have to run for every user, even those that don't use webhooks, which in itself is only a very small portion).

Actually Freqtrade does provide {stake_currency}, even {fiat_currency}. Why provide these and not {coin_currency} ?

https://www.freqtrade.io/en/2020.7/webhook-config/#webhookbuy

    trade_id
    exchange
    pair
    limit
    amount
    open_date
    stake_amount
    stake_currency
    fiat_currency
    order_type
    current_rate

**Comment by xmatthias** [comment]
`stake_currency` and `fiat_currency` are static configuration parameters, which cannot change unless you use `/reload_config`. as such, handling them is a lot easier.

**Comment by Sungray** [comment]
Thanks @xmatthias !
