### ISSUE TITLE
Finding out the database that was set with --db-url

### ISSUE THREAD

**Issue by gdominoni** [freqtrade/freqtrade#6078]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.8
  * CCXT version: 1.59.2
  * Freqtrade Version: 2021-10
  
Hi, I cannot find anywhere in the documentation how to find out the name of the database that was used (when you have set a different database with --db-url). That would be useful, I guess, when your computer crashes and you have not saved anywhere the name of the database you have used and you have like 20 trades open and don't know what to do with them...

**Comment by xmatthias** [comment]
Freqtrade logs the database-url during startup, so it's probably in your logs.

You can also store the database in your configuration as `db_url` - so it's "persisted" and you can look it up again / start freqtrade with the same database again without hastle.

**Comment by gdominoni** [comment]
> Freqtrade logs the database-url during startup, so it's probably in your logs.
> 
> You can also store the database in your configuration as `db_url` - so it's "persisted" and you can look it up again / start freqtrade with the same database again without hastle.

Thank you, but, sorry, how do I check the logs if the terminal got closed?  (this might be a terribly basic question, but what can I do...)

"You can also store the database in your configuration as `db_url` - so it's "persisted" and you can look it up again / start freqtrade with the same database again without hastle." this is great, for the future, but what if I have already lost the database?

**Comment by xmatthias** [comment]
It depends a bit on the way you run freqtrade.
Our docker-files log to file by default - otherwise it'll depend if you ran freqtrade with `--log-file <whatever>` - otherwise it'll not be persisted, and therefore not available.

otherwise, your best bet might be to search your system for `*.sqlite` files (assuming you used the default).

**Comment by gdominoni** [comment]
> otherwise, your best bet might be to search your system for `*.sqlite` files (assuming you used the default).

Thank you, yes, I could not find the database by simply looking for it, but I finally found it, and it was in the most obvious place...
