### ISSUE TITLE
Problem with timestamp 1000ms request

### ISSUE THREAD

**Issue by HenBaliti** [freqtrade/freqtrade#6080]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.10 (`python -V`)
  * CCXT version: ccxt 1.61.92(`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.11 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Getting the Error : requests.exceptions.HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1639781552860&recvWindow=5000&signature=.....%SIAGNTURE%.....

Hey Everyone ,

**This is the ERROR I got  :**

--------------------------
```
Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/exchange/exchange.py", line 354, in reload_markets
freqtrade  |     self._markets = self._api.load_markets(reload=True)
freqtrade  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1422, in load_markets
freqtrade  |     currencies = self.fetch_currencies()
freqtrade  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 990, in fetch_currencies
freqtrade  |     response = self.sapiGetCapitalConfigGetall(params)
freqtrade  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 459, in inner
freqtrade  |     return entry(_self, **inner_kwargs)
freqtrade  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4551, in request
freqtrade  |     response = self.fetch2(path, api, method, params, headers, body, config, context)
freqtrade  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 504, in fetch2
freqtrade  |     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
freqtrade  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 631, in fetch
freqtrade  |     self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
freqtrade  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4531, in handle_errors
freqtrade  |     self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
freqtrade  |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 522, in throw_exactly_matched_exception
freqtrade  |     raise exact[string](message)
freqtrade  | ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
```
----------------

I have tried to figure  the problem on this guide: 
https://www.opentechguides.com/how-to/article/windows-10/121/windows-10-internet-time.html .

The problem was fixed by this guide but the problem is back when it get to time zone 12PM \ 00:00 on my computer every day , so I need to change the settings again and restart my computer for this every time .
How can I fix the problem ? 

Thank You all !

**Comment by xmatthias** [comment]
based on your URL's - i assume youre running in wsl2 (not natively on windows).

There's a (still open) issue on WSL2 (https://github.com/microsoft/WSL/issues/4114).
In the end, the problem is that time from your windows is not correctly passed to the linux subsystem.

You should be able to fix this by setting up a time daemon in wsl2 (there are several instruction in that issue ...) to have the time correct on your WSL2 environment.

for example as explained in this comment: https://github.com/microsoft/WSL/issues/4114#issuecomment-733754629

**Comment by HenBaliti** [comment]
Hey I just got there to a "quick fix" , that was told me to put those lines:

**sudo apt-get install ntpdate
sudo ntpdate pool.ntp.org**

I just now figured where to put these lines because I use a docker and this is all new for me .
I put these lines on my docker-file.costume , and also I take the freqtrade file and I paste this there :

**RUN apt-get install ntpdate \
 && ntpdate pool.ntp.org**


Then I try to run the docker with this : 

**docker-compose build --pull**

and I got this ERROR :

**=> ERROR [python-deps 5/6] COPY --chown=ftuser:ftuser requirements.txt requirements-hyperopt.txt /freqtrade/                                                                                         0.0s**

**[python-deps 5/6] COPY --chown=ftuser:ftuser requirements.txt requirements-hyperopt.txt /freqtrade/:**

**failed to solve: rpc error: code = Unknown desc = failed to compute cache key: "/requirements-hyperopt.txt" not found: not found**



I will be happy If you could help me to fix this .

**Comment by xmatthias** [comment]
Running ntp inside the docker container is (unfortunately) the wrong approach, and will not work correctly (i think it'll crash - but i'm not sure about that).

In practice, the ntp daemon needs to run on the underlying linux os - which in case of docker for windows is however not visible / exposed, and therefore not a viable approach.

All workarounds posted in the above linked WSL issue are NOT automatic, and rely on restarting docker every now and then.
Unfortunately, We can therefore not recommend docker on windows windows for production usages (you should be fine for dry-run - as well as backtesting/hyperopt / ... ).

A better approach is either using WSL2 directly (you can run the ntpd daemon there - installation via the regular [linux installation ](https://www.freqtrade.io/en/stable/installation/) will work there (obviously you'll still need to setup ntpd).


If you must work around this issue for some reason without changing your installation method (no possibility to run natively in wsl2 or on a VPS) - please try the following configuration snippet (it goes into the "exchange" key of your configuration):

``` jsonc
// ... 
"ccxt_config": {
    "options": { "adjustForTimeDifference": true }
}
```

It'll adjust for time differences - however it will do so by sacrificing your communication security (between your pc and the exchange).

**Comment by Shahnavazi1985** [comment]
How are you

**Comment by Shahnavazi1985** [comment]
Tanks
