### ISSUE TITLE
Is it possible to specify buy/sell price for limit orders?

### ISSUE THREAD

**Issue by oliviera9** [freqtrade/freqtrade#6085]
Given a strategy, and a buy signal, is it possible to let the bot open a buy limit order at a specific price?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

It is also good practice to consult the [documentation first](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-price-rules).
