### ISSUE TITLE
refs/tags/studio-3.0 - assets/android-studio-ux-assets - Git at Google"refs/tags/studio-3.0 - assets/android-studio-ux-assets - Git at Google" https://android.googlesource.com/assets/android-studio-ux-assets/+/refs/tags/studio-3.0cameraservicehttps://android.googlesource.com/assets/android-studio-ux-assets/+/refs/tags/studio-3.0

### ISSUE THREAD

**Issue by Bat3an** [freqtrade/freqtrade#6096]
"refs/tags/studio-3.0 - assets/android-studio-ux-assets - Git at Google" https://android.googlesource.com/assets/android-studio-ux-assets/+/refs/tags/studio-3.0

**Comment by Bat3an** [comment]
Disposable it is but not replacement for other so never give up

**Comment by xmatthias** [comment]
This issue is clearly not for this repository (if you even intended to open an issue).
