### ISSUE TITLE
recording events as series dataframe

### ISSUE THREAD

**Issue by canz** [freqtrade/freqtrade#6097]
Hi All
This is probably more of a Pandas question that I have not been able to find the answer to.

I would like to record events into the dataframe with a function such as high/low the function im using just adds null/0 to all fields except the first, I believe this is because I need to process the data frame differently "return series is probably the issue", how can I call a function for each 5min bar and input the result into the dataframe
example:

(dataframe['hlc']=self.hilow_mf(dataframe)

    def hilow_mf(self, df):
        hlc = 11
        return Series(hlc, name='hlc')

while the above function is try's to add 11 to every 5min tick of the dataframe the end result would be more like
3,3,3,3,3,3,-1-1-1-1-1,4,4,4,-2,-2,-2,-2,6,6,1,1,7,7,7,3,3

would this work or is there a better way
    def hilow_mf(self, df):
        hlc = "11"
        return hlc 

many thanks in advance
links to relevant technical articles appreciated

**Comment by xmatthias** [comment]
What you're doing appears to be a simple assignment, and can be accomplished with `dataframe['hlc'] = 11` (or more correctly by using loc, `dataframe.loc[:, 'hlc'] = 11`). Both will work identically on freqtrade's dataframes.


in general, the "technical articles" are probably simply the pandas documentation.

Freqtrade also has a segment about this [here](https://www.freqtrade.io/en/stable/strategy-customization/#dataframe) - but it mainly covers why/how to use vectorization.
