### ISSUE TITLE
Hyperopt result (Max Drawdown)

### ISSUE THREAD

**Issue by rongybika** [freqtrade/freqtrade#6099]
Hi,
Let's say I have this kind of result after hyperopt:

|   Best |   Epoch |   Trades |    Win Draw Loss |   Avg profit |                        Profit |    Avg duration |                  Max Drawdown |      Objective 

|   Best | 108/150 | 14423 | 9515 4758  150 | 2.32% |     27555.867 USDT  (734.82%) | 1 days 20:38:00 |   34869.928 USDT (10,395.46%) |    -397.748 |

My question is about Max Drawdown. How I should understand the result when the Max Drawdown is higher than Profit amount.
At the first look is not a good result but the Objective is relative high(I mean is low enough).
So is this a good result or not?

Thank you

**Comment by xmatthias** [comment]
The best way to understand max-drawdown is to run backtesting on this result (if this was the "best" result - you can simply follow the command up by changing the command to backtesting (with the same timerange/config settings, and with `--export trades`).
Backtesting resuts will already contain some more details on drawdown (like the maximum / minimum wallet position).

You can then use `freqtrade plot-profit` - which will plot the profit curve (the graph in the middle) of this (including the maximum drawdown).

The remainder is speculation only (and you might come to other conclusions based on your profit graphs):

The result suggests that "probably" - you're still in the middle of drawdown (did not fully recover yet) - and that your strategy would've made more money - assuming the end-date would've been earlier.
to me, this suggests that favors of the strategy turned, and it's no longer working well in current market conditions

**Comment by rongybika** [comment]
Hi,

Your answer was very helpfully. :)

Thank you
