### ISSUE TITLE
Y

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#6101]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
This issue does not make any sense.
if you require some help, please add some text / description for that in the issue.
