### ISSUE TITLE
https://www.facebook.com/profile.php?id=100056087389793

### ISSUE THREAD

**Issue by Bilal1422** [freqtrade/freqtrade#6102]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docke[https://www.facebook.com/profile.php?id=100056087389793](https://www.facebook.com/profile.php?id=100056087389793) r-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*

**Comment by Bilal1422** [comment]
my Facebook account all issu delete

**Comment by xmatthias** [comment]
This issue does not make any sense.
if you require some help, please add that to the issue, don't post links.
