### ISSUE TITLE
What to do if crypto asset is removed from exchange?

### ISSUE THREAD

**Issue by fridary** [freqtrade/freqtrade#6104]
* Operating system: Mac OS 11.6
  * Python Version: 3.8.12
  * CCXT version: 1.61.92
  * Freqtrade Version: 2021.11
  
This error persists:
`2021-12-23 12:34:08 WARNING root.get_rate() Sell Price at location 1 from orderbook could not be determined. Orderbook: {'symbol': 'BZRX/USDT', 'bids': [], 'asks': [], 'timestamp': None, 'datetime': None, 'nonce': 555108284, 'updated': 1640252045}`

When I start bot I see `BZRX/USDT` open trade:
```
2021-12-23 12:33:50 INFO freqtrade.rpc.rpc_manager.send_msg() Sending rpc message: {'type': startup, 'status': "Searching for USDT pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
2021-12-23 12:33:50 INFO freqtrade.persistence.models.stoploss_reinitialization() Found open trade: Trade(id=3, pair=BZRX/USDT, amount=59.12495073, open_rate=0.25370000, open_since=2021-12-17 01:02:14)
```

When I check https://www.binance.com/ru/trade/BZRX_USDT, I see 404. So I guess this asset is removed from `binance` exchange where I trade.
The problem is the bot does not handle work, because of infinite ordebook and fetch candle history error. I can not even view previous stat history on web:
![Снимок экрана 2021-12-23 в 12 49 58](https://user-images.githubusercontent.com/3791864/147222802-a71d91d8-6004-42f3-854e-fe16ac30b0df.png)

**Comment by xmatthias** [comment]
your best bet will be to `/delete <tradeid>` the trade.

Unfortunately, exchanges don't provide the delisting date via API - therefore these are often cases where you'll simply remain "stuck" in a trade which you can't really do anything with (you'll probably also be unable to sell that asset on the exchange ...).

**Comment by fridary** [comment]
@xmatthias Maybe we can make some changes in code in order not to block bot work? I mean al least even with removed asset from exchange bot will keep working.

**Comment by xmatthias** [comment]
your log doesn't suggest that it's blocked - but simply that this trade-slot is blocked - which is expected, and i'd not know how to work around that.
