### ISSUE TITLE
single pair previous positions data recall for hedging and new order executions

### ISSUE THREAD

**Issue by SavvyEngineer** [freqtrade/freqtrade#6106]
## Describe your environment
(if applicable)

  * Operating system: ____`ubuntu LTS 20.04`
  * Python Version: _____ (`python -V3.8`)
  * CCXT version: _____ (`ccxt==1.64.42`)
  * Freqtrade Version: ____ (`freqtrade develop-1cbc4da72`)

## Describe the enhancement

hi first of all thanks for the amazing job with this repo I'm trying to develop my strategy and the first thing I need is to know the previous order entry price to execute my new buy or sell order I tried every possible scenario and I tried 
using trade history from DB
accessing data frame in callback methods was not possible for me because the Trade parameter is not set in custom_entry_price() callback and there is no callback for executing sell order, only for entry or exit scenarios and using trade history is not good for me because I cannot run backtesting or hyperopt

**Comment by xmatthias** [comment]
Once you are in a trade, you currently cannot buy the same pair again, which is why `custom_entry_price` does not need a Trade.

>  there is no callback for executing sell order

it's unclear what you mean with this - there is  `custom_sell`, `custom_exit_price`, as well as `confirm_trade_exit()` - all called as part of the exit flow.
each of these 3 methods will include the trade object.

**Comment by SavvyEngineer** [comment]
> Once you are in a trade, you currently cannot buy the same pair again, which is why `custom_entry_price` does not need a Trade.
> 
> > there is no callback for executing sell order
> 
> it's unclear what you mean with this - there is `custom_sell`, `custom_exit_price`, as well as `confirm_trade_exit()` - all called as part of the exit flow. each of these 3 methods will include the trade object.
In my explanation, my intent of using sell is not closing my buy position; I meant entering short sell order without the need to close my previous buy order
What I need is to be able to open multiple buy (long) and sell (short) orders at the same time on single pair and execute them based on data and information of previous open order.

**Comment by SavvyEngineer** [comment]
In my explanation, my intent of using sell is not closing my buy position; I meant entering short sell order without the need to close my previous buy order
What I need is to be able to open multiple buy (long) and sell (short) orders at the same time on single pair and execute them based on data and information of previous open order.

**Comment by xmatthias** [comment]
Please refer to our [FAQ](https://www.freqtrade.io/en/stable/faq/#can-i-open-short-positions) about short positions.

you can also subscribe to #892 to get informed when margin/short positions is implemented.

Freqtrade also currently does not support multiple positions on the same pair, you can subscribe to #1519 for updates on this.
