### ISSUE TITLE
Question about checking historic candle data for strategy

### ISSUE THREAD

**Issue by jackman105** [freqtrade/freqtrade#6108]
* Operating system: Ubuntu 20.04
  * Python Version: 3.8.10
  * CCXT version: 1.63.55
  * Freqtrade Version: develop-c12f2378d

Good day and Merry Christmas!

I'm currenlty configuring a hyperopt strategy file, but I haven't been able to implement some of my ideas by just following the documentation and I'm hoping that someone could assist me.

On the buy side, I would like to use "conditions.append" to add a condition which only issues a buy signal when no more than 5 candles (not necessarily in succession) have been below a certain closing price within the previous 10 candles.

On the sell side, I would like to use similar logic, but this time check whether 10 candles in the previous 15 are below and then sell immediately, ignoring all other conditions.
I know from the documentation that I cannot use an if statement with pandas dataframes (to clear the conditions array and then append only one condition), but I haven't seen a way to check conditions with dataframes in the documentation other than sending the actual buy/sell signal using dataframe.loc[ ,"buy"] = 1

If anyone could assist me, this would be greatly appreciated. :)

**Comment by xmatthias** [comment]
In general, pandas tutorials are a good way to learn how to work with dataframes, as the dataframe you're getting is a standard pandas dataframe.

To look back a candle, you can use `.shift(1)`. 
An alternative method for 5 candles could be `dataframe['close'].rolling(5).max()` - checking if all were below a certain threshold.

Maybe you can also combine the two with something like the following:

``` python
dataframe['is_below'] = dataframe['close'] < 200 ## Will return a boolean flag
dataframe['mycoolcheck'] = dataframe['is_below'].rolling(10).sum()  # Sum boolean flags will count the "True" values
```

Note: This is just to give you ideas - not necessarily exactly how you need the code to be.
