### ISSUE TITLE
how to load buy_params and sell_params from config file

### ISSUE THREAD

**Issue by ahmadie** [freqtrade/freqtrade#6109]
Thank you for this amazing tool !! I have looked up freqtrade github but could not find an answer. I would appreciate if you can answer following question:

How do I load buy_params or sell_params into my strategy  from config.json file ?

I tried adding this to my config.json:
```
"params": {
  "buy":{
    param3: 3
  }
}
"buy_params": {
  "param1": 1
},
"param2":2
```

but could not find value inside my strategy using:
```
self.param1.value 
self.param2
self.param3.value
```

I also added:
```
buy_param = {
   param1: -1
   param3: -1
}
param2 = -1
```
at the top of my strategy

I asked because inside hyperopt document there was a note about buy_params and sell_params as follow:
Values in the configuration file will overwrite Parameter-file level parameters - and both will overwrite parameters within the strategy. The prevalence is therefore: config > parameter file > strategy

**Comment by xmatthias** [comment]
the parameter file is not the configuration file.
it's a file that's automatically created when you use hyperopt (or `hyperopt-show`) - and will be created alongside the strategy (`MyAweSomeStrategy.py` -> `MyAweSomeStrategy.json`.

You cannot load these parameters from the configuration - this would create too much confusion as we'd then have 3 (actually 4) locations where a parameter can come from.

**Comment by ahmadie** [comment]
Thank you for confirmation !

**Comment by italodamato** [comment]
It's technically possible by doing something like this within the `__init__` method of the strategy class 
```
# Load strategy parameters   
        for name, settings in config['params'].items():
            if settings['type'] == 'int':
                setattr(self, name, IntParameter(**settings))
            if settings['type'] == 'bool':
                setattr(self, name, BooleanParameter(**settings))
```
but, unfortunately, the hyperopt doesn't detect them. The reason is that [these methods](https://github.com/freqtrade/freqtrade/blob/7f20f6834bc8c386aabbd28ab66b144957c49445/freqtrade/strategy/hyper.py#L331) have been decorated as `@classmethod` hence the __init__ method doesn't run when they get called.

**Comment by xmatthias** [comment]
@italodamato There's little point in loading parameters from the configuration, as freqtrade will automatically [apply parameters to the strategy](https://www.freqtrade.io/en/stable/hyperopt/#automatic-parameter-application-to-the-strategy) from a separate configuration file.
