### ISSUE TITLE
detect_parameters & detect_all_parameters class methods?

### ISSUE THREAD

**Issue by ZerGo0** [freqtrade/freqtrade#6110]
Is there any specific reason why these 2 methods mentioned above are specifically class methods?

This makes it impossible to create hyperoptable class properties in runtime. (For example pair specific parameters)

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Yes there is. this allows `freqtrade list-strategies` to show if parameters are used without having to initialize the strategy.

There's also no good reason i can think of to generate parameters at runtime - that will only lead to problems down the road.

Parameters should be deterministic - not dynamically generated based on whatever randomness you chose to apply, as that would invalidate and be problematic for all parameter load methods (all parameter files we write would be invalid), as freqtrade could not rely on the strategy to have the same parameters the next round.
