### ISSUE TITLE
sell_profit_offset units

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#6115]
Very quick question

Is ""sell_profit_offset" a percentage  value as a float i.e. 1% = 0.01 ?

The unit was not stated in the Docs.

Many thanks for a great project.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.


The docs do actually contain this [here](https://www.freqtrade.io/en/stable/configuration/):
> Datatype: Float (as **ratio**)
