### ISSUE TITLE
Allow custom_sell when buy tag is active

### ISSUE THREAD

**Issue by slipx06** [freqtrade/freqtrade#6126]
## Describe the enhancement

I have a buy signal defined in `populate_buy_trend()` that triggers based on a DB lookup (pymongo). The DB would contain a row with both the pair and the signal i.e. BUY or SELL which is populated independent of the bot. I use `populate_indicators()` to return the latest row data every bot loop. The buy signal remains active as long as the data returned in the signal is BUY. When a SELL signal is received the buy condition fails and is no longer active. The signal that is pushed to the DB (BUY or SELL) can take hours and it is often the case that the buy tag will remain active for a given pair for an extended period (even after the initial buy). I would like to trigger my `custom_sell()` conditions once the trade is open even if the buy column is populated. If I understand correctly, currently `custom_sell()` is not triggered if the buy is active. (line 689)

https://github.com/freqtrade/freqtrade/blob/2917cc1f2e03045cdbcbbb9b3b827391d87fe525/freqtrade/strategy/interface.py#L680-L705

Can we create an additional configuration parameter similar to `ignore_roi_if_buy_signal` for example `ignore_custom_sell_if_buy_signal` that can be set to false so that `custom_sell()` can be triggered whilst there is an active buy?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Having a sell signal while the buy-signal is still active is a sign of a badly designed strategy, as the signal is "undecided" (it's saying both buy and sell).

The end-result would be that your bot will sell - and immediately (at the next candle) buy again - causing nothing but fees (and potentially lost profits, as the pair might raise further while you're out of the position).

As such - this is not something we'll be adding. 
Best work on improving your strategy to have the buy-signal no longer active once your strategy says "sell".

**Comment by slipx06** [comment]
Thank you for the response. This was not logged as a bug but a feature requests, but perhaps it should have been logged as a question. The only part of the template that I chose to delete as I did not feel it was applicable was:

```
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement
```
The signal could be better described as "its ok to enter your trade price is expected to rise" I'd like to take profits whilst this "signal" is active. I don't see this as a bad strategy apart from the fee impact. There is a possibility for multiple entries (the bot will buy the same pair after the sell) which is not ideal, but since the signal is still active it should theoretically still result in a profitable trade.  I'll have to look at other options.

**Comment by xmatthias** [comment]
your "take profits" will always include the full trade - so it's not a "take some profits" - but take it all.

if you think about what you just wrote - you assume that the buy signal is still active - so the assumption is that entering at this point would still result in a profitable trade. 
Translated, this means, your sell signal is technically wrong - and will result in lost profits (not losses per se, but lost/wasted additional profit) - as the rest of your strategy assumes that price will still raise.
