### ISSUE TITLE
How to replace strategy params depending on asset?

### ISSUE THREAD

**Issue by fridary** [freqtrade/freqtrade#6131]
* Operating system: Mac OS 11.6
  * Python Version: 3.8.12
  * CCXT version: 1.61.92
  * Freqtrade Version: 2021.11
  
Have not found an answer here, although someone could ask. I have 300+ assets trading with 1 bot, but with hyper opt script I got different params for each. How can I start 1 bot, but with different params for each asset? Something like this:

```
class AwesomeStrategy(IStrategy):
    buy_params = {
        'rsi': 70,
    }
    minimal_roi = {
        "0": 0.05,
        "10": 0.025,
    }

class AwesomeStrategy_ETH(AwesomeStrategy):
    buy_params = {
        'rsi': 80,
    }
    minimal_roi = {
        "0": 0.1,
        "20": 0.01,
    }
```

**Comment by xmatthias** [comment]
Out of the box, you cannot. 
One set of parameters will apply to all pairs identically - so the "simple" solution is to run one bot per pair.

I guess you can code up something within the strategy to use different parameters per pair - but i'd strongly advise against that.

If you hyperopted against individual pairs, your results are almost certainly overfitted - which will mean they'll probably fail in a real world scenario.
While not all pairs move identically - your approach assumes that ETH (or any other individual pair) will behave exactly as it did in the past - which i'm certain will not happen (and if it does, it's pure randomness).
As such, the strategy does not generalize well - and can also react strangely to unseen (or slightly different) data.

**Comment by fridary** [comment]
@xmatthias thank you for answer. `trailing_stop`/`trailing_stop_positive`/`trailing_stop_positive_offset` I can set in `custom_stoploss(pair, ...)`, `buy_params['rsi']` set in `populate_indicators()` with `metadata['pair']`. Is it possible also make custom condition for `minimal_roi` and `stoploss`?

**Comment by xmatthias** [comment]
i don't think that setting `buy_params['rsi']` within `populate_indicators()` will work correctly (unless you use it as `buy_parameters['rsi']` - and not via the strategy parameters.

trailing parameters will not be properply set via `custom_stoploss` (setting them would not work and will "leak" to other pairs) - but will be implemented as custom_stoploss.

You can do the same with regular stoploss, by simply starting to trail only once offset is reached.
