### ISSUE TITLE
List of "Trading Fees " or "Deposit/Withdrawal" Fees of each exchange

### ISSUE THREAD

**Issue by john012343210** [freqtrade/freqtrade#6137]
Is it provided in this package? would like to retrieve such list

**Comment by xmatthias** [comment]
deposit/withdrawal fees are irrelevant to freqtrade. 
While i understand that they are relevant when picking an exchange - freqtrade's purpose is not to help people pick an exchange.

Trading fees would be relevant for freqtrade, but there are too many options to create a useful output of this (depending on the exchange, fees will depending on verification level, trading volume, "exchange coin holdings", ...).

You might be able to retrieve a basic list by writing some script with [ccxt](https://github.com/ccxt/ccxt) (maybe they also have an example for this) - but freqtrade does not have such functionality.

**Comment by john012343210** [comment]
@xmatthias   So freqtrade doesn't consider Trading fees?  Since freqtrade don't know my verification level, etc,  there is no way it could get the correct trading fee of that exchange.

**Comment by xmatthias** [comment]
Freqtrade does use the exchange default as provided by ccxt for dry runs and backtesting, and uses the fees from the real trades in live mode.

Dry fees are therefore potentially higher.
