### ISSUE TITLE
Backtest sells via ROI instead of sell-signal in case of simultaneous occurrence

### ISSUE THREAD

**Issue by ttmdebugger** [freqtrade/freqtrade#6139]
## Describe your environment

  * Operating system: macOS 11.6.2
  * Python Version: 3.7.9
  * CCXT version: 1.61.92
  * Freqtrade Version: 2021.11
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

Backtest sells on the simultaneous occurrence of a sell-signal and a ROI signal via the ROI signal. 

### Steps to reproduce:

  1. Run an arbitrary backtest that produces a sell-signal and triggers the ROI at the same time.
  2. Plotting helps to visualise the issue.
  
### Observed Results:

  * What happened?
  Backtest trade sold by ROI instead of the sell signal.
![Ohne Titel 2](https://user-images.githubusercontent.com/96880297/147769843-fc743c0e-86ae-4359-b5ca-7a57d98b878a.jpg)
  * What did you expect to happen?
  Backtest trade should be sold at the 'open' price, as the process time is ideally very small and this value is closer to reality; the ROI execution takes place intra-candle.

### Relevant code

https://github.com/freqtrade/freqtrade/blob/bd98637ae934db16968d921f560e9a05a04b1549/freqtrade/strategy/interface.py#L708-L721

Thanks for your support!

**Comment by xmatthias** [comment]
This is actually intended behavior, and documented in the [backtesting assumptions](https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting) (last point).

I don't see it as a bug for the moment (it's documented, therefore expected behavior).

Now it's obviously arguable which sell-reason should be preferred (you're probably right that changing the sequence might be better - there's also a TODO a few lines above the linked relevant code) - but the change is non-trivial (not from a code perspective) - and can potentially have quite an impact on strategy results (depending on how the strategy works).

**Comment by ttmdebugger** [comment]
Thank you very much for your quick reply. I have seen the post in the documentation and thought that was taken accordingly. However, since it is consistent, it is of course not a bug in the proper sense, you are right.

In live I have always seen significant deviations from the backtest, in my specific case the reverse order is much closer to live. What was the reason to define exactly this order at that time? And in which cases would the reverse implementation be disadvantageous for a strategies (long process times,...)?

Probably addressing the TODO would be the right approach, using an option flag would satisfy both cases.

**Comment by xmatthias** [comment]
I've added the TODO as part of a refactor that brought the whole logic to the form (or a similar format, anyway) than it is now - keeping the original logic for this.

I'm not entirely sure why the logic was the way it was - but doing a refactor AND reversing some logics at the same time is rarely a good idea.

As said - it's potentially the right approach (hence the TODO) - but it's not a change i'd want to take lightly - without considering potential downsides (if there are any).

**Comment by ttmdebugger** [comment]
Great, the approach is totally understandable, refactor AND reversing some logics at the same time is not a good idea in any case.

Many thanks for the immediate opening of the PR, I think it will be beneficial to some in the freqtrade community.

**Comment by xmatthias** [comment]
While the PR is there (as said, technically it's a small change i've been putting off) - i'm not decided yet if it's the right approach.

it sure seems like it - but it's quite dangerous to be biased by "the latest issue pointing out X", overlooking cases where this will create negative impacts.

**Comment by ttmdebugger** [comment]
Your thoughts are valid and important, a detailed review is always mandatory.
