### ISSUE TITLE
How to plot Heikin Ashi candles as subplot?

### ISSUE THREAD

**Issue by Niqnil** [freqtrade/freqtrade#6158]
## Describe your environment

  * Operating system: Ubuntu 21.04
  * Python Version: 3.9.9
  * CCXT version: 1.63.1
  * Freqtrade Version: freqtrade docker-decaa24f
  
How can I plot Heikin Ashi candles as subplot? When I use the code below, they show up as lines, which are not very readable as a chart. 
Also, is there a way to set the scale for a subplot like Bollinger band percent and width?

```
from pandas_ta.candles import ha  # Heikin-Ashi

    @property
    def plot_config(self):
        return {
            "main_plot": {
            },
            "subplots": {
                "BollingerBand": {
                    f"bb-{self.bb_length.value}-{self.bb_std.value}_percent": {
                        "color": "Purple"
                    },
                    f"bb-{self.bb_length.value}-{self.bb_std.value}_width": {
                        "color": "Plum"
                    },
                },
                "HEIKIN_ASHI": {
                    "ha_open": {"color": "Gold"},
                    "ha_high": {"color": "green"},
                    "ha_low": {"color": "red"},
                    "ha_close": {"color": "GoldenRod"},
                },
            },
        }

def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        heikinashi = ha(
            open_=dataframe["open"],
            high=dataframe["high"],
            low=dataframe["low"],
            close=dataframe["close"],
        )
        dataframe["ha_open"] = heikinashi["HA_open"]
        dataframe["ha_high"] = heikinashi["HA_high"]
        dataframe["ha_low"] = heikinashi["HA_low"]
        dataframe["ha_close"] = heikinashi["HA_close"]
# ...etc
```

**Comment by xmatthias** [comment]
Subplots will be scaled automatically to the values which are visible, so manually setting the "visible range" is not necessary.

Currently, you're limited to lines when using `plot-dataframe` - and to lines and bar charts when using freqUI (best use FreqUI to configure the chart in that case, and then export the generated configuration).

Your best bet will probably be picking one (or 4?) lines for it in different colors.
We'll also not be adding this functionality to `plot-dataframe` - which should be considered as "in maintenance mode" - and will potentially be removed in favor of freqUI.

For FreqUI - it's something that can be discussed - but i've honestly never really seen a chart where heikinashi-candles have been plotted in a subplot (usually they replace the original plot ...).

**Comment by Niqnil** [comment]
Yes I am using `plot-dataframe` and Heikin Ashi show up as lines, which are not easy to tell apart. [Screenshot](https://ibb.co/fCS9gw4) I suppose I can do a work-around by passing `dataframe["open"] = heikinashi["HA_open"]` etc somehow and make two plots - original price candles and HA candles. Then open them side by side. But zooming and panning to see different periods would be a pain.

As you said, I think few people will want to see both candle types side by side. So you don't need to make it a priority or even add this feature at all.

I understand the scaling for subplot now. BB-percent and BB-width need to be separated for it to auto-scale correctly. Feel free to close this unless you want to discuss further.

**Comment by xmatthias** [comment]
Be careful when reassigning open, high, low and close (the original candles).
In backtesting, these prices will be used, so you can manipulate the results quite well with this, with difficulty understanding the reasons for things.

You can probably do it selectively, but i'd do it only for plotting mode, and only after generating sell signals.
