### ISSUE TITLE
backtesting - exit_tag doesn't populate sell_signal

### ISSUE THREAD

**Issue by italodamato** [freqtrade/freqtrade#6159]
## Describe your environment

  * Operating system: MacOS 12.0.1
  * Python Version: Python
  * CCXT version: 1.58.70
  * Freqtrade Version: freqtrade docker-f3784f21
  
## Your question

Do you know why the `sell_signal` doesn't get populated with the `exit_tag` in the backtesting results table? This is how the dataframe looks.

The `buy_tag` is working correctly.

I'm using the docker image: freqtradeorg/freqtrade:latest

![image](https://user-images.githubusercontent.com/45588475/147926560-7f4cdc6b-59de-4eff-a5d2-69d7d6ae4268.png)
![image](https://user-images.githubusercontent.com/45588475/147926570-51e7ba34-fbcb-46ee-9924-8fba54722bea.png)

Edit: use question template

**Comment by xmatthias** [comment]
Please fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

**Comment by italodamato** [comment]
@xmatthias I've updated the question. I thought it wasn't relevant since I'm using the latest docker image.

**Comment by xmatthias** [comment]
most think that - but if that were the case, we'd not ask it ... so i stopped reading most issues if the template is missing (it's nothing personal, or about this issue in particular).
Especially with "latest develop docker image" it's a moving target. You say it's "latest" - but it's 2 days old, so no longer "really latest" (not that it'd matter for THIS issue) - for that, having the correct version will help - especially if you consider that an answer may also take a bit.

---

it works for me on a test ...

```
===================================================== SELL REASON STATS =====================================================
|   Sell Reason |   Sells |   Win  Draws  Loss  Win% |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |
|---------------+---------+--------------------------+----------------+----------------+-------------------+----------------|
|     stop_loss |     131 |      0     0   131     0 |          -5.19 |        -679.87 |         -1891.57  |        -135.97 |
|      whatever |      35 |     29     0     6  82.9 |          27.78 |         972.31 |          2326.83  |         194.46 |
|    force_sell |       5 |      5     0     0   100 |          22.07 |         110.33 |           314.151 |          22.07 |
```

So the most likely cause is that the sells that actually cause the `sell_signal` output are not the ones you show above.
Best make sure you filter on "sell=1" - not on "exit_tag != None" ... and that the strategy you're backtesting is actually the one you're working with (you can find duplicate strategies with `freqtrade list-strategies`).

**Comment by italodamato** [comment]
![image](https://user-images.githubusercontent.com/45588475/147982285-079fbff4-13a5-4a6c-b8f3-aa2f96697bf5.png)
As you can see
-  there's no row where sell = 1 and exit_tag is None
- the tot num of rows with sell=1 is equal to the tot num of rows with sell=1 and exit_tag not none

I don't have any callbacks implemented besides custom_stake but it doesn't apply any change to either the exit_tag or the sell signal

**Comment by xmatthias** [comment]
There's 2 ways we can try to move further in this.
Either you try and get this reproduced in a sample as small as possible (basically eliminating almost everything and do a very simple signal (like MA Cross), or you share your strategy with me (if you want to keep it private, via DM in discord).

It's working for me (with strategies i have), so i suspect it's something in the strategy that's causing this.

Maybe something can be improved which is causing what you're seeing - but for the moment, i'm unable to recreate what you're seeing with the strategies I've been trying this with, obviously with the latest develop version.

**Comment by italodamato** [comment]
I think I've found the problem: if you pass the `--timeframe-detail` parameter when you run the backtest, the `exit_tag` doesn't get populated in the results.

**Comment by xmatthias** [comment]
see, and that's the problem :laughing: nothing above included info on the usage of "timeframe-detail" - so that's not how i tested it when it worked.

with this information, it's quite easy to reproduce (and with that, usually also to fix).

Fix should be available in develop docker images in ~half an hour.

**Comment by italodamato** [comment]
Thank you so much for your help!
