### ISSUE TITLE
get bid ask values to use in strategy 

### ISSUE THREAD

**Issue by FlockrushAdmin** [freqtrade/freqtrade#6160]
## Describe your environment

  * Operating system: Mac
  * Python Version: 3.8 (`python -V`)
  * CCXT version: 1.55.56 (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-01b5fe9f9 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

How can we retrieve the the value of bid and ask value before the buy or sell signal is set in the strategy. 

For getting value of bid and ask before the buy or sell signal is set in the strategy. I found this         ob = 
       self.dp.orderbook(metadata['pair'], 1) 
       dataframe['best_bid'] = ob['bids'][0][0]
       dataframe['best_ask'] = ob['asks'][0][0]

Referencing best_ask or best_bid throws an error.

Thank you!!!

**Comment by xmatthias** [comment]
Without knowing which error it throws (and in which mode - like backtesting/live), it's pure guesswork.

**Comment by FlockrushAdmin** [comment]
In backtesting mode. 

I used the following as.

 a reference.
```
if self.dp:
    if self.dp.runmode.value in ('live', 'dry_run'):
        ob = self.dp.orderbook(metadata['pair'], 1)
        dataframe['best_bid'] = ob['bids'][0][0]
        dataframe['best_ask'] = ob['asks'][0][0]
else:
         dataframe['best_bid'] = 0
        dataframe['best_ask'] = 0
```

Print (f 'best bid is {[dataframe["best_bid"]}') - throws an error

**Comment by xmatthias** [comment]
You should indent the "else" by 4 more spaces to have this as "0" - as `dp` is usually available - the check that's failing is the `runmode` one.

You could also simply change it to `if self.dp and self.dp.runmode.value in ('live', 'dry_run'):` - then you can keep the else as is.

as the note/warning at the bottom of the [orderbook section](https://www.freqtrade.io/en/stable/strategy-customization/#orderbookpair-maximum) explains - this will use uptodate info (how price is now) - so has an automatic lookahead bias when used in backtesting.

As you're assigning 0 - make sure to properly account for this when using these values

**Comment by FlockrushAdmin** [comment]
freqtrade backtesting --strategy StrategyOne --timeframe 1m --dry-run-wallet 10000 --fee 0.001

If I remove the ELSE all together and change the IF to:

(in the def populate_indicators, after if is 4 space indented)
if self.dp and self.dp.runmode.value in ('live', 'dry_run'):
    ob = self.dp.orderbook(metadata['pair'], 1)
    dataframe['best_bid'] = ob['bids'][0][0]
    dataframe['best_ask'] = ob['asks'][0][0]


(and then print, in the populate_buy_trend logic)
Print (f 'best bid is {[dataframe["best_bid"]}') - still throws an error

**Comment by xmatthias** [comment]
The else will still be needed, as you will need some alternative for backtesting.

**Comment by FlockrushAdmin** [comment]
Thank you!!! Sending lots of love and blessings!!!
