### ISSUE TITLE
Backtesting multiple Strategies finnished without Strategy Summary

### ISSUE THREAD

**Issue by thanatchon36** [freqtrade/freqtrade#6162]
## Describe your environment

  * Operating system: Docker version 20.10.11, build dea9396 (on Macbook m1)
  * Freqtrade Version: freqtrade 2021.11
  
## Describe the problem:

When I backtest multiple strategies on lots of white pair list (80+) sometimes there is Strategy Summary that printed out when finished but sometimes there is no Strategy Summary at the end.

### Steps to reproduce:

  1. docker-compose run --rm freqtrade download-data -t 5m 1d 1h 15m --exchange binance --timerange=20211201-20220101
  2. docker-compose run --rm freqtrade backtesting -c user_data/config.json -v --timerange=20211201-20211231 --timeframe 5m --timeframe-detail 1m --max-open-trades 6 --strategy-list NostalgiaForInfinityX NostalgiaForInfinityNext 
  
### Observed Results:

1. When testing one strategy, it is okay to print result: docker-compose run --rm freqtrade backtesting -c user_data/config.json --timerange=20211201-20211231 --timeframe 5m --timeframe-detail 1m --max-open-trades 6 -s NostalgiaForInfinityNext 
2. Sometimes when I tested 50 strategies by specifying all 50 strategies in --strategy-list, it will lead to backtesting finnished with no Strategy Summary; however, when I split big cmd in sub cmds in 3 parts for 15, 10, and 25 strategies, it can print Strategy Summary, including all 3 tables.
3. When I specify -vvv in cmd, it can incease the chance to print out Strategy Summary correctly. 
4. When I reduce backtest white pair list from 80 paris to 40 paris, I can print Strategy Summary. As the white pair list increases, it will reduce the chance to print out strategy summary.

### Relevant code exceptions or logs
This is strategy summary (comparing multiple strategies) that can be printed out when finnish:
<img width="1214" alt="Screen Shot 2565-01-04 at 13 08 12" src="https://user-images.githubusercontent.com/10392423/148016631-d1a6a76c-3f28-4632-b084-8bfa57ce1daa.png">
from running: docker-compose run --rm freqtrade backtesting -c user_data/config.json --timerange=20211201-20211231 --timeframe 5m --timeframe-detail 1m --max-open-trades 6 --strategy-list NostalgiaForInfinityV1 NostalgiaForInfinityV2 NostalgiaForInfinityV3 NostalgiaForInfinityV4 NostalgiaForInfinityV5

There is no strategy summary (comparing multiple strategies) when backtest finnished:
<img width="1420" alt="Screen Shot 2565-01-04 at 13 13 50" src="https://user-images.githubusercontent.com/10392423/148017039-3b6d63b7-efc3-4680-87e6-448bc380bd2d.png">
from running: docker-compose run --rm freqtrade backtesting -c user_data/config.json --timerange=20211201-20211231 --timeframe 5m --timeframe-detail 1m --max-open-trades 6 --strategy-list NostalgiaForInfinityV6 NostalgiaForInfinityV7 NostalgiaForInfinityNext NostalgiaForInfinityX

My main issues is that I don't know why Backtesting multiple Strategies finnished without Strategy Summary for unknown reasons. I would like to get 100% Strategy Summary output when the backtest finnished.

**Comment by xmatthias** [comment]
The fact that you're missing all strategy output suggests that your system is running out of memory.

With docker, the message might be surpressed as its the container thats being killed, not the freqtrade process directly.

You should be able to find messages about this in your system log.
Recommendations from hyperopt apply also here -> reduce timerange, pairs, or in this case, amount of strategies.

Also using lighter strategies (with fewer informative pairs) can help this.

**Comment by thanatchon36** [comment]
> The fact that you're missing all strategy output suggests that your system is running out of memory.
> 
> With docker, the message might be surpressed as its the container thats being killed, not the freqtrade process directly.
> 
> You should be able to find messages about this in your system log. Recommendations from hyperopt apply also here -> reduce timerange, pairs, or in this case, amount of strategies.
> 
> Also using lighter strategies (with fewer informative pairs) can help this.

Thank you for your quick response. I will take your setup recommendations for my further backtesting and this is very reasonable for my previous observed results.
