### ISSUE TITLE
Trade duration in backtesting does not depend on market/limit order?

### ISSUE THREAD

**Issue by JonastenHaaf** [freqtrade/freqtrade#6167]
## Describe your environment

  * Operating system: Ubuntu 20.04.3 LTS
  * Python Version: Python 3.8.12
  * CCXT version: ccxt==1.65.57
  * Freqtrade Version: freqtrade develop-09f5f80
  
## Your question

I developed a strategy for which the trade duration (time between sell/buy signal and trade closing) is critical. It should be less than 10 minutes, therefore a worse price for selling/buying is acceptable.

Now I run a strategy with 1m candles and the following config in backtest:

`freqtrade backtesting --datadir user_data/data/binance --export trades -s MyStrategy -i 1m`

`    "order_types": {
        "buy": "market",
        "sell": "market",
        "emergencysell": "market",
        "forcebuy": "market",
        "forcesell": "market",
        "stoploss": "market",
        "stoploss_on_exchange": false,
        "stoploss_on_exchange_interval": 60,
        "stoploss_on_exchange_limit_ratio": 0.99
    },
    "bid_strategy": {
        "price_side": "ask",
        "ask_last_balance": 1.0,
        "use_order_book": true,
        "order_book_top": 5,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "bid",
        "use_order_book": true,
        "bid_last_balance": 1.0,
        "order_book_top": 5
    },`

with the result

`========================================================= BACKTESTING REPORT ========================================================
|    Pair |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit EUR |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
|---------+--------+----------------+----------------+------------------+----------------+----------------+-------------------------|
| ETH/EUR |    886 |           0.01 |          11.53 |           96.902 |           9.69 |        0:47:00 |   400     0   486  45.1 |
|   TOTAL |    886 |           0.01 |          11.53 |           96.902 |           9.69 |        0:47:00 |   400     0   486  45.1 |`

so on only one pair, ETH/EUR and get an average trade duration of 47 minutes. Is this value plausible?

More over, I tested limited orders with the config

`    "order_types": {
        "buy": "limit",
        "sell": "limit",
        "emergencysell": "market",
        "forcebuy": "market",
        "forcesell": "market",
        "stoploss": "market",
        "stoploss_on_exchange": false,
        "stoploss_on_exchange_interval": 60,
        "stoploss_on_exchange_limit_ratio": 0.99
    },
    "bid_strategy": {
        "price_side": "bid",
        "ask_last_balance": 1.0,
        "use_order_book": true,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": true,
        "bid_last_balance": 1.0,
        "order_book_top": 1
    },`

and got 

`========================================================= BACKTESTING REPORT ========================================================
|    Pair |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit EUR |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
|---------+--------+----------------+----------------+------------------+----------------+----------------+-------------------------|
| ETH/EUR |    886 |           0.01 |          11.53 |           96.902 |           9.69 |        0:47:00 |   400     0   486  45.1 |
|   TOTAL |    886 |           0.01 |          11.53 |           96.902 |           9.69 |        0:47:00 |   400     0   486  45.1 |`

which is exactly the same results. The config is not overridden in the strategy.
Did I miss something? How exactly is the order book defined in backtesting and how is Avg Duration computed? How can the trade time be reduced?

Thanks,
Jonas

**Comment by xmatthias** [comment]
[backtesting assumptions](https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting) explains this quite nicely and clearly:

> All orders are filled at the requested price (no slippage, no unfilled orders)

As such, order-type does not have any impact to backtesting, as all orders fill immediately (therefore market/limit order does not matter for backtesting). 

historic orderbook data is not available (and would be huge, as it can change multiple times per second) - therefore any assumption we'd be making about historic orderbooks would be automatically wrong.
