### ISSUE TITLE
hyperopt drawdown reference should be max_rate instead of profit_abs

### ISSUE THREAD

**Issue by italodamato** [freqtrade/freqtrade#6171]
## Describe your environment

  * Operating system: MacOS 12.0.1 
  * Python Version:  n/a
  * CCXT version: n/a
  * Freqtrade Version: freqtrade docker-7adb7f90
  
## Your question

I've noticed we compute the drawdown using the cumulative profit of the trades over time ([link](https://github.com/freqtrade/freqtrade/blob/addba6597a6ac6908d552ddf957708a7b9ee249f/freqtrade/data/btanalysis.py#L359)) but I think the definition of the drawdown references the peak reached by the investment, which in this case should be the max_rate reached by a trade. This represents the cost we incurred since we sold too late. By taking the actual profit we'll never know what we left on the table.

Is there a specific reason why we are doing it in this way?

**Comment by xmatthias** [comment]
Drawdown calculation just changed today in develop (#6165), which completely changes how this metric should be interpreted.


What you're talking about is unrealized profits. drawdown only considers realized profits (the result of the trade).

While in general, i don't see tradingview as "the source of truth" - in this case they are [correct](https://www.tradingview.com/support/solutions/43000561856-how-are-strategy-tester-report-values-calculated-and-what-do-they-mean/) (search for Drawdown, it's about 1/4th down the page) - and the new method (currently in develop) is doing the same math.


>  This represents the cost we incurred since we sold too late. By taking the actual profit we'll never know what we left on the table.

Drawdown is not intended to show you this (and never will) - and it's also not intended to be used to determine "how late have we sold" by any definition i've ever seen.
There might be other metrics/calculations for this - but drawdown is surely the wrong calculation for this - as it'll show the biggest drop from the highest point (which may or may not be lost profit depending on trade-movements).
This would be calculated as max_rate vs. close-rate - which should be easily doable in a [notebook](https://www.freqtrade.io/en/stable/strategy_analysis_example/#plotting-daily-profit-equity-line) if you think this metric is important for yourself.

**Comment by italodamato** [comment]
Makes sense sorry for the confusion. I guess I combined the run-up and drawdown definition in my head (the definitions at the bottom of the page - not the max drawdown value).
