### ISSUE TITLE
okex  how can i fix this?

### ISSUE THREAD

**Issue by WANGLULU9802** [freqtrade/freqtrade#6176]
when i use okex exchange, the error occur with this error message：
Message: okex {"error_message":"Please change to port v1 when you are using v1 apiKey. If you wish to use port v3, please register a v3 apiKey.","code":30016,"error_code":"30016","message":"Please change to port v1 when you are using v1 apiKey. If you wish to use port v3, please register a v3 apiKey."}

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

Also, please provide a comprehensive log - not just one message, which makes it difficult to properly assist you.

**Comment by WANGLULU9802** [comment]
> when i use okex exchange, the error occur with this error message： Message: okex {"error_message":"Please change to port v1 when you are using v1 apiKey. If you wish to use port v3, please register a v3 apiKey.","code":30016,"error_code":"30016","message":"Please change to port v1 when you are using v1 apiKey. If you wish to use port v3, please register a v3 apiKey."}
