### ISSUE TITLE
Less epochs more random states or inverse?

### ISSUE THREAD

**Issue by rongybika** [freqtrade/freqtrade#6186]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.7.4 (`python -V`)
  * CCXT version: 1.59.2 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.10 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hi,

What's your opinion it's better to run hyperopt more times, to try with as many as possible different random states, with less epochs or run less times with ,,huge" epoch number?

Thank you

**Comment by xmatthias** [comment]
We do have a [FAQ](https://www.freqtrade.io/en/stable/faq/#how-many-epochs-do-i-need-to-get-a-good-hyperopt-result) entry, which answers exactly this question.

In the end, it'll also depend on the parameter space in general, so a definitive, generally applicable answer is not possible.
