### ISSUE TITLE
Wrong starting capital after changing stake_currency from USDT to BTC

### ISSUE THREAD

**Issue by fukit0** [freqtrade/freqtrade#6207]
## Describe your environment

  * Operating system: CentOS 8.1.1911
  * Python Version:
  * CCXT version: 
  * Freqtrade Version: 2021.12 (freqtrade in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

My bot was using USDT as stake currency with an unlimited stake amount. I changed my currency as BTC and some other configurations as well. I also deleted `tradesv3.sqlite` to clear the status table since I manually handled the coins for the previous configuraion. After restart, starting capital shows 5 BTC. So I cannot calculate the real profit. 

Configuration: **live**

### Steps to reproduce:
config before change:

```
    "max_open_trades": 15,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD"
```

config.json after change:
```
    "max_open_trades": 2,
    "stake_currency": "BTC",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
```  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
Assuming you correctly deleted/moved the database, and this is a live configuration - then the value (5 BTC) will be pulled from the exchange (you can check this with `/balance`).

As you didn't specify anything to limit starting capital - freqtrade will be using everything that's reported from the exchange as your balance in stake currency (BTC, in this case).

If this is dry-run - then `dry_run_wallet` would apply - but a value of `5` would not make sense in any case, not for USDT, and not for BTC (too much for one, too little for the other).

**Comment by fukit0** [comment]
_I updated my question and added the configuration information._ 

The bot is running in live mode and I had approximately 1000 USD in my account when I started it.

`/balance` (ETH/BTC pair in my blacklist):

```
Starting capital: 5.2095544799999995 BTC 217868.77790807997 USD.
BTC:
 Available: 0.00680392
 Balance: 0.00680392
 Pending: 0.00000000
 Est. BTC: 0.00680392
ETH:
 Available: 1.26292600
 Balance: 1.26292600
 Pending: 0.00000000
 Est. BTC: 0.09499729
BNB:
 Available: 0.06244947
 Balance: 0.06244947
 Pending: 0.00000000
 Est. BTC: 0.00065566
COS:
 Available: 12582.00000000
 Balance: 12582.00000000
 Pending: 0.00000000
 Est. BTC: 0.00654264

Estimated Value:
 BTC: 0.10899951 (-97.91%)
 USD: 4558.469 (-97.91%)
```

I am not sure I did delete the database correctly. Is there a specific way to remove it?

**Comment by xmatthias** [comment]
you can use `/profit` (or most other "statistical" endpoints) to check if the database has been emptied or not.

in general, stopping the bot and moving/removing the file will suffice.
If you didn't stop the bot (/reload_conf may or may not suffice) it's possible that the bot still has the file-handle from the previous file.

The calculated starting capital suggests that the database was not empty (otherwise this value would not make any sense). The calculation is pretty simple as `available_balance - tot_profit + open_stakes`.
Available balance can also be seen above (as available BTC) - the rest comes from the database.

**Comment by fukit0** [comment]
`/balance` started to show real capital values after stopping the bot and removing the database with your advice. However, I think there is still a bug somewhere to identify.

Thanks for your help.

**Comment by xmatthias** [comment]
> However, I think there is still a bug somewhere to identify.

I'd honestly not know what you mean. 
You were using a database with different stake - so profits of that got added into the calculation (which is expected).

changing stake currency within the same database is not supported - so it's not a bug, but a usage error, unless you've encountered something else that isn't mentioned here/above.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.

**Comment by fukit0** [comment]
My issue got fixed, thanks for that. However, what I want to point out is that I deleted the database in the first place. Starting capital was wrong then. I did not understand how this was resolved on the second try. 

Let's assume I changed the stake currency without deleting the database. Where is that 5 BTC starting capital come from?

**Comment by xmatthias** [comment]
starting capital is calculated based as current balance - current profit (it's a little bit more complex than that, but in principle it's that).
So if you simply change stake without restarting the database, your 5$ profits  (or loss) will make appear like you started with 5 BTC.
