### ISSUE TITLE
Gate.io config and strategy

### ISSUE THREAD

**Issue by mojito228** [freqtrade/freqtrade#6216]
Is there anyone who can share his/her Gate.io config and strategy files or code?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

You can quite simply generate a configuration file for gate.io by following the documentation (the command you're looking for is `freqtrade new-config --config config.json`, and selecting gate.io.

For strategy - we have a [strategy repository](https://github.com/freqtrade/freqtrade-strategies/) with some open-source strategies which people contributed.


If you have further questions relating to this, please use the [discord channel](https://discord.gg/p7nuUNVfP7) to get support / help from the community.
People there love to help assuming the documentation has been consulted first.
