### ISSUE TITLE
Forcebuy [Pair] [Price] [Amount]

### ISSUE THREAD

**Issue by mroodschild** [freqtrade/freqtrade#6223]
First of all, I want to congratulate you for the great work you do.

## Describe the enhancement

*Explain the enhancement you would like*

Would it be possible to add one more parameter to the "forcebuy" command? 

When you need to execute a manual trade, I thought it would be useful to set the amount of money to be used in each trade.

For example:

/forcebuy [Pair] [Price] [Amount]

**Comment by xmatthias** [comment]
in theory, there's nothing against this - but I think we'd be only adding such a possibility via the API/freqUI, not via telegram.

Having tons of arguments is quite confusing (and dangerous) in telegram, and will potentially lead to quite some "buy fails".
what if you'd like to use "freqtrade pricing" for it? 
you can't "skip" the price argument, so you MUST provide a price as well, so usability of telegram commands with lots of (optional) arguments is not going to work out.

**Comment by mroodschild** [comment]
I agree with you, many parameters are difficult to manage in Telegram.On the other hand, the amount of money per trade defines the risk one wants to take, so it should be considered.

As for the parameter difficulty, maybe adding a new function like:

/forcebuy_manual [Pair] [Price] [Amount].

I also think that it is necessary to add a SL according to the trade id

/stoplimit <trade_id> 
(especially for binance)

Adding these two features, Freqtrade becomes a great tool for manual trading.

**Comment by xmatthias** [comment]
To be honest, freqtrade does not aim to be a tool for manual trading, but for automated trading. 
you can use your exchange's website  / app to do manual trading.

As said above, if any, then we can add additional fields to the API (and therefore also to freqUI).
For telegram, i don't see us adding any telegram endpoint with 4+ parameters, as this will cause quite some errors/mistakes.

Eventually, something with inline-keyboards could be created, where you're asked for additional info.
But i don't see this as necessity and will not spend my time with this anytime soon (you're obviously free to create a PR which will add a usable (!) workflow for this if you think this is a must - but an endpoint with more than 2 parameters will not be accepted).

**Comment by mroodschild** [comment]
I see your point, thank you very much for responding xmatthias
