### ISSUE TITLE
gateio does not work with volumepairlist

### ISSUE THREAD

**Issue by hippocritical** [freqtrade/freqtrade#6232]
## Describe your environment

  * Operating system: ubuntu-based
  * Python Version: docker
  * CCXT version: docker
  * Freqtrade Version: docker-bb29c444 (same result with 2021.11, errors out at 2021.12)
  
## Describe the problem:

When trying to do the working config on gateio it errors out and the cpu is pegged at 100% but it boots up.
(2021.12 does just error out)

### Steps to reproduce:

  1. this method was the last effort of trying to fix the error, added lookback_period to all those there, same result without for the 2ndary filters / volumepairlist.
```json
  {
	"pairlists":
	[
        	{
			"method": "VolumePairList",
			"number_assets": 60,
			"sort_key": "quoteVolume",
			"refresh_period": 20000,
			"lookback_timeframe": "4h",
			"lookback_period": 42
		},
		{
			"method": "AgeFilter",
			"min_days_listed": 1,
			"refresh_period": 20000,
			"lookback_timeframe": "4h",
			"lookback_period": 42
		},
	        {
			"method": "SpreadFilter",
			"max_spread_ratio": 0.999,
			"refresh_period": 20000,
			"lookback_timeframe": "4h",
			"lookback_period": 42
		},
	        {
                	"method": "RangeStabilityFilter",
                	"min_rate_of_change": 0.00,
			"refresh_period": 20000,
			"lookback_timeframe": "4h",
			"lookback_period": 42
        	},
        	{
			"method": "VolatilityFilter",
			"min_volatility": 0.00,
			"max_volatility": 0.9999,
			"refresh_period": 20000,
			"lookback_timeframe": "4h",
			"lookback_period": 42
		},
        	{
		        "method": "VolumePairList",
		        "number_assets": 50,
		        "sort_key": "quoteVolume",
	        },
	],
}
```
2. boot container for gateio

  
### Observed Results:

  * What happened?
freqtrade boots up, but errors appeared a ton saying that >1k candles were used but only defined 42 via volumepairlist and other filters as shown above.

```python
freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair NFTB/USDT due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Candlestick range too broad. Maximum 1000 data points are allowed per request"}". Retrying still for 1 times.
```

  * What did you expect to happen?
freqtrade booting up without screaming out errors

### Relevant code exceptions or logs

```python
freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair NFTB/USDT due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Candlestick range too broad. Maximum 1000 data points are allowed per request"}". Retrying still for 1 times.
```

then

```python
freqtrade.exchange.exchange - WARNING - Async code raised an exception: RuntimeError('No active exception to reraise')
```

**Comment by xmatthias** [comment]
Please make sure to not test with intermediate docker images (some version X days ago) - but either with a release, or with the latest version.

This has been fixed several days ago in ccxt (https://github.com/ccxt/ccxt/issues/11162), which is now also a pinned version for the latest develop version.

Unless this can be verified with the latest develop, i'll consider this as fixed.

**Comment by hippocritical** [comment]
weird, did a pull build ... gonna check again then

**Comment by xmatthias** [comment]
The version you're listing above (bb29c444) is from jan 6th ... that's 10 days ago ;)

**Comment by hippocritical** [comment]
seems the issue was twofold:
the version was old (as you discussed on the discord and there it had the issue)

The cpu was pegged at 100% since I was using ccxt_config ratelimit from ages ago and not ccxt_async_config ratelimit. maybe ccxt changed that internally too, freqtrade itself didnt return anything error-like regarding that.

**Comment by xmatthias** [comment]
with "newer" ccxt versions, you shouldn't configure rate-limit at all in freqtrade - ccxt has defaults that usually work quite well (and for some exchanges like gate.io - has a better way to detect the weight per endpoint), so i'd recommend to remove all rateLimit settings for gate.IO from freqtrade and rely on the new way ccxt handles this (setting rateLimit in freqtrade will disable the new way).

**Comment by zlov137** [comment]
leaving it ccxt_async_config's enableRateLimit to false on KuCoin is getting a lot of banned messages in the logs as of late.
