### ISSUE TITLE
How to use “adjust trade position”?

### ISSUE THREAD

**Issue by umutrcc** [freqtrade/freqtrade#6239]
hello, the relevant part is clearly written here, but unfortunately I still could not grasp it and since this topic is new, I could not come across people who use it. Can you please open this code a little more to help me and for those who are looking for an example on this subject, for example, what I want is as follows.  When the rsi falls below 20 and is below the bollinger band, I want 0.01 btc to buy, and if this drops 10% again from the price I bought, and if it meets the conditions again, this time I want 0.02 btc to buy again.

`` 
from freqtrade.persistence import Trade

class DigDeeperStrategy(IStrategy):

    position_adjustment_enable = True

    # Attempts to handle large drops with DCA. High stoploss is required.
    stoploss = -0.30

    # ... populate_* methods

    # Example specific variables
    max_dca_orders = 3
    # This number is explained a bit further down
    max_dca_multiplier = 5.5

    # This is called when placing the initial order (opening trade)
    def custom_stake_amount(self, pair: str, current_time: datetime, current_rate: float,
                            proposed_stake: float, min_stake: float, max_stake: float,
                            **kwargs) -> float:

        # We need to leave most of the funds for possible further DCA orders
        # This also applies to fixed stakes
        return proposed_stake / self.max_dca_multiplier

    def adjust_trade_position(self, trade: Trade, current_time: datetime,
                              current_rate: float, current_profit: float, min_stake: float,
                              max_stake: float, **kwargs):
        """
        Custom trade adjustment logic, returning the stake amount that a trade should be increased.
        This means extra buy orders with additional fees.

        :param trade: trade object.
        :param current_time: datetime object, containing the current datetime
        :param current_rate: Current buy rate.
        :param current_profit: Current profit (as ratio), calculated based on current_rate.
        :param min_stake: Minimal stake size allowed by exchange.
        :param max_stake: Balance available for trading.
        :param **kwargs: Ensure to keep this here so updates to this won't break your strategy.
        :return float: Stake amount to adjust your trade
        """

        if current_profit > -0.05:
            return None

        # Obtain pair dataframe (just to show how to access it)
        dataframe, _ = self.dp.get_analyzed_dataframe(trade.pair, self.timeframe)
        # Only buy when not actively falling price.
        last_candle = dataframe.iloc[-1].squeeze()
        previous_candle = dataframe.iloc[-2].squeeze()
        if last_candle['close'] < previous_candle['close']:
            return None

        filled_buys = trade.select_filled_orders('buy')
        count_of_buys = len(filled_buys)

        # Allow up to 3 additional increasingly larger buys (4 in total)
        # Initial buy is 1x
        # If that falls to -5% profit, we buy 1.25x more, average profit should increase to roughly -2.2%
        # If that falls down to -5% again, we buy 1.5x more
        # If that falls once again down to -5%, we buy 1.75x more
        # Total stake for this trade would be 1 + 1.25 + 1.5 + 1.75 = 5.5x of the initial allowed stake.
        # That is why max_dca_multiplier is 5.5
        # Hope you have a deep wallet!
        if 0 < count_of_buys <= self.max_dca_orders:
            try:
                # This returns first order stake size
                stake_amount = filled_buys[0].cost
                # This then calculates current safety order size
                stake_amount = stake_amount * (1 + (count_of_buys * 0.25))
                return stake_amount
            except Exception as exception:
                return None

        return None
``

**Comment by stash86** [comment]
Or you can join the discord server and come across people who already use it?

**Comment by umutrcc** [comment]
Okey thanks

**Comment by xmatthias** [comment]
Quite simply - you return the desired "incremental" stake whenever you'd like to buy more.

so whenever a condition you'd like is met, you return 0.01 (or 0.02 or whatever - must be in stake currency!) to buy more.
Be careful not to run into a endless loop of buying immediately everything (or buying 0.01 every 10 seconds) - as this callback will be called roughly every 5 seconds for every open trade.

For the remainder i'd suggest to read through the documentation. It's a callback like any other, and there's a multitude of examples for these available, also comparing different indicators.
