### ISSUE TITLE
formatting issue with ._ files created in Mac

### ISSUE THREAD

**Issue by harshadvekariya** [freqtrade/freqtrade#6253]
## Describe your environment

  * Operating system: macOS Monterery 12.1
  * Python Version: 3.9.9
  * CCXT version:  1.68.25
  * Freqtrade Version: freqtrade 2021.12
  
## Describe the problem:

I am not able to use backtesting, and hyperopt in Mac OS. It works fine on linux machine. After some digging I found that it is issue with formatting of the file as mentioned here https://github.com/freqtrade/freqtrade/issues/2901. 

### Steps to reproduce:

  1. Install docker
  2. Get the image
      `mkdir ft_userdata`
      `cd ft_userdata/`
      # Download the docker-compose file from the repository
      `curl https://raw.githubusercontent.com/freqtrade/freqtrade/stable/docker-compose.yml -o docker-compose.yml`
      
      # Pull the freqtrade image
      `docker-compose pull`
      
      # Create user directory structure
      `docker-compose run --rm freqtrade create-userdir --userdir user_data`
      
      # Create configuration - Requires answering interactive questions
      `docker-compose run --rm freqtrade new-config --config user_data/config.json`

  3. Start docker `docker-compose up -d` (In this command itself it gives the ValueError.)
  4. Get logs `docker-compose logs -f`
  5. Download the data  `docker-compose run freqtrade download-data --erase --exchange binance -t 15m --days 1000`
  6. `docker-compose run freqtrade backtesting --config user_data/config.json --datadir user_data/data/binance --export trades --stake-amount 100 -s Strategy002 -i 15m` This command may work on first time , when I run it the second time it gives me the error.

  * Mac OS is automatically  creating ._ files which is causing the issue. If I run dot_clean, and then run the backtesting then it works, however, I have to do dot_clean after each command else it will give following error. I can't get it to work with hyperopt though. 

  * The command should ignore ._ files that is generated by the Mac OS, else it will take duplicate data. For example, when I download data for BTC/USDT pair, it downloads a file named BTC_USDT-15m.json. later when I run a backtesting command the OS will automatically generate a file named ._BTC_USDT-15m.json. It is generating this ._* files for all data, config, stratergy and prettypuch all the files that it uses. This will cause error in the next backtesting command I run, and hyperopt is not usable at all.

 * I have to run `dot_clean` everytime before running backtesting to clear the ._* files.

### Relevant code exceptions or logs
  ```
  2022-01-18 05:00:17,404 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 102, in start_hyperopt
    hyperopt = Hyperopt(config)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 90, in __init__
    self.custom_hyperoptloss = HyperOptLossResolver.load_hyperoptloss(self.config)
  File "/freqtrade/freqtrade/resolvers/hyperopt_resolver.py", line 42, in load_hyperoptloss
    hyperoptloss = HyperOptLossResolver.load_object(hyperoptloss_name,
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 149, in load_object
    found_object = cls._load_object(paths=abs_paths, object_name=object_name,
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 120, in _load_object
    (module, module_path) = cls._search_object(directory=_path,
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 102, in _search_object
    obj = next(cls._get_valid_object(module_path, object_name), None)
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 66, in _get_valid_object
    spec.loader.exec_module(module)  # type: ignore # importlib does not use typehints
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ValueError: source code string cannot contain null bytes
  ```

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

It's also unclear if you're using the default docker-compose file, or some changes, and which command you're actually using to run the command that causes the problem.

**Comment by harshadvekariya** [comment]
> Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment. We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.
> 
> It's also unclear if you're using the default docker-compose file, or some changes, and which command you're actually using to run the command that causes the problem.

I am really sorry, I am posting issue for first time on GitHub, I was unaware of the tamplates and mistakenly deleted it. I updated the disctiption. Please go through the same, Thanks!

**Comment by xmatthias** [comment]
> Mac OS is automatically creating ._ files which is causing the issue.

Do you have any background / additional information about this? 
I know quite some macOS users (also with M1) - and this is the first time i hear this reported. 
This suggests that it might be some setting in your system that's causing this.

with the way you're running freqtrade (using docker) - freqtrade is not actually running natively on macOS, but in a linux container.
If the `._` files are macOS specific files, then they are created by docker, not by freqtrade.

Which version of docker are you using, and is it running natively, or via rosetta (if you're on a M1)?

---

The files in `user_data/data/` will not matter (freqtrade will not even notice they're there).
the error suggests that these files are created in `user_data/hyperopts` ... but it's not freqtrade that's generating these files.

if possible, can you share the output of the tree command (`tree user_data/hyperopts`)? (i hope it includes these files ...)

**Comment by harshadvekariya** [comment]
> > Mac OS is automatically creating ._ files which is causing the issue.
> 
> Do you have any background / additional information about this? I know quite some macOS users (also with M1) - and this is the first time i hear this reported. This suggests that it might be some setting in your system that's causing this.
> 
> with the way you're running freqtrade (using docker) - freqtrade is not actually running natively on macOS, but in a linux container. If the `._` files are macOS specific files, then they are created by docker, not by freqtrade.
> 
> Which version of docker are you using, and is it running natively, or via rosetta (if you're on a M1)?
> 
> The files in `user_data/data/` will not matter (freqtrade will not even notice they're there). the error suggests that these files are created in `user_data/hyperopts` ... but it's not freqtrade that's generating these files.
> 
> if possible, can you share the output of the tree command (`tree user_data/hyperopts`)? (i hope it includes these files ...)

These files are generated by macOS, I finally got it working. The problem was that I was running all the command in my external hard drive. I moved all the folders to the internal drive, and it is sorted. It seems that macOS creates a backup file for files that are being used from external drives, in case of crash it can be used for recovery. 

I won't be able to provide the output you asked as I already migrated all the files, and it is working now. 

Thank you very much for your help!

**Comment by xmatthias** [comment]
> I won't be able to provide the output you asked as I already migrated all the files, and it is working now.

That's perfectly fine - that would've been required to help you further - by having it fixed now - all is fine :+1:
