### ISSUE TITLE
Buy candle ROI trap

### ISSUE THREAD

**Issue by rokups** [freqtrade/freqtrade#6261]
(So we do not forget)

I bumped into a backtesting trap related to roi getting filled on buy candle. Consider this situation:
![image](https://user-images.githubusercontent.com/19151258/150093172-23d256ee-bd2b-434d-a61e-cdc5d1b3748b.png)

Current behavior:
1. Fist candle requests an order placement below candle close using `custom_entry_price()`.
2. Second candle does reach said level and order is considered filled.
3. Second candle fell by more than active ROI, which means there is enough room for price to go up and get filled by ROI.

ROI (on second candle) essentially considers price to move like so: open -> low (order fill) -> high (roi) -> close. This is too optimistic and hardly ever happens.

How it should work:
If buy (second, in the example above) candle hits ROI target:
* Only consider a successful exit for longs on red candle, if entry price >= open.
* Only consider a successful exit for shorts on green candle, if entry price <= open.

This would always assume the pessimistic outcome:
  * Red candles move open->high(only chance for ROI of longs on entry candle, or try stoploss first for shorts)->low->close
  * Green candles move open->low(only chance for ROI of shorts on entry candle, or try stoploss first for longs) ->high->close

**Comment by rokups** [comment]
A temporary workaround can be added after `self.strategy.should_sell()` call in `backtesting.py`:
```py
        if sell.sell_type in (SellType.ROI, SellType.SELL_SIGNAL):
            order = trade.select_order('buy', is_open=False)
            assert order is not None
            if order.order_filled_date == sell_row[DATE_IDX]:
                # Longs can only hit roi on red candle if trade is opened and closed in top wick.
                if sell_row[OPEN_IDX] > sell_row[CLOSE_IDX]:
                    if trade.open_rate < sell_row[OPEN_IDX]:
                        sell.sell_type = SellType.NONE
                        sell.sell_reason = None
```

**Comment by xmatthias** [comment]
wouldn't an easier "workaround" to this be to handle this as special case in `_get_close_rate`  (there's 0 length handling anyway) - and return None (basically rejecting the sell right there)?

obviously that'll need some handling "outside" ... but it actually seems quite easy to accomplish

**Comment by rokups** [comment]
I did not look into `_get_close_rate` actually. If it can reject a trade then its perfect 👍🏻

**Comment by xmatthias** [comment]
> I did not look into `_get_close_rate` actually. If it can reject a trade then its perfect 👍🏻

it's code - it can do whatever we teach it to ...
