### ISSUE TITLE
error dumping backtesting JSON - stop_loss_ratio: nan

### ISSUE THREAD

**Issue by italodamato** [freqtrade/freqtrade#6263]
## Describe your environment

  * Operating system: MacOS 12.1
  * Python Version: Python 3.9.8
  * CCXT version: ccxt==1.68.20
  * Freqtrade Version: freqtrade develop-fb0413c

## Describe the problem:

Error when exporting the backtesting results since the stop_loss_ratio is set to nan in the trade. It's due to the position adjustment (https://github.com/freqtrade/freqtrade/pull/6079) being triggered on the same candle of the open_date (i.e. `trade.open_date == current_time`).

### Steps to reproduce:

  1. create a strategy where the position gets adjusted on the same candle the trade was created
  2. run a backtest
  3. stop_loss_ratio in the trade will be `nan` which is not supported in JSON
  
### Observed Results:

 Adding 
```
if trade.open_date == current_time:
            return None
```
at the beginning of `adjust_trade_position` fixes the problem

### Relevant code exceptions or logs

  ```
2022-01-20 12:02:51,154 - freqtrade.misc - INFO - dumping json to "***/Users/italodamato/Documents/GitHub/freqtrade***/user_data/backtest_results/backtest-result-2022-01-20_12-02-51.json"
2022-01-20 12:02:51,154 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/Users/italodamato/Documents/GitHub/freqtrade-1/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/Users/italodamato/Documents/GitHub/freqtrade-1/freqtrade/commands/optimize_commands.py", line 54, in start_backtesting
    backtesting.start()
  File "/Users/italodamato/Documents/GitHub/freqtrade-1/freqtrade/optimize/backtesting.py", line 800, in start
    store_backtest_stats(self.config['exportfilename'], self.results)
  File "/Users/italodamato/Documents/GitHub/freqtrade-1/freqtrade/optimize/optimize_reports.py", line 42, in store_backtest_stats
    file_dump_json(filename, stats)
  File "/Users/italodamato/Documents/GitHub/freqtrade-1/freqtrade/misc.py", line 79, in file_dump_json
    rapidjson.dump(data, fp, default=str, number_mode=rapidjson.NM_NATIVE)
ValueError: Out of range float values are not JSON compliant  
```

**Comment by xmatthias** [comment]
if you're buying twice within the same candle in backtesting, then i would think there is a problem anyway - as it suggest a programming error (that's usually not what you want - as you can't be sure on how the candle behaved anyway.

While freqtrade should not crash - think the right fix here has to happen within the strategy (not just by excluding this first candle).

@xataxxx sorry for pinging you - is there a reason why we do this (in backtesting) before checking for sells instead of after? The problem clearly is that the initial stoploss is only assigned once the `should_sell` method is called for the first time - that's a known behaviour - but i didn't think of it creating a problem in this combination.

**Comment by italodamato** [comment]
@xmatthias  I'd argue it depends on the strategy. In my case, the initial open trade was probably triggered in the pre-period candles which then created this issue. If I extend the timeframe I don't get the issue. 

While I agree that it's technically a strategy issue, I think the pos adjustment signal should be ignored in this case as we do for candles with buy/sell signals happening together.

**Comment by xmatthias** [comment]
so what you're proposing is that the position adjustment will only start **after** the initial candle in backtesting (it'll only be called for the next candle).

This will not really align to live - where position-adjustment will start after the order is filled (which may or may not be within the opening candle).
It's however also difficult to argue against it - as we'll not really be sure when/where the trade was filled within the candle in the first place (hence we assume it fills at open - at open price at the moment).

**Comment by italodamato** [comment]
Alternatively, we can make it explicit in the docs that the timing should be handled explicitly within the `adjust_trade_position` method by setting conditions between the `trade.open_date` and the `current_time` according to their needs (e.g. cooldown period after entry etc.).

Another option is to trigger the adjustment at the average rate between open and close if it gets triggered on the open candle.

**Comment by xmatthias** [comment]
I think it might be possible to work around this by adding `trade.adjust_stop_loss(trade.open_rate, self.strategy.stoploss, initial=True)` right after creating the LocalTrade object (should be line ~524 in `backtesting.py`.

@italodamato would you mind giving that a try with the strategy that caused this problem as i can't really replicate that behaviour "ad hock" at the moment?

**Comment by italodamato** [comment]
@xmatthias Yep that fixes it good idea
