### ISSUE TITLE
is it possible to get short selling signals without actually passing short sell trades ? 

### ISSUE THREAD

**Issue by OreNoMochii** [freqtrade/freqtrade#6265]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*
I'd like to use freqtrade for receiving short sell signals but not necessarily passing those short sell trades (as it is not a feature yet). 
Is it possible to use freqtrade as a trade signal provider for short sell ? 

Kindest regards, 

Farrabi.

**Comment by xmatthias** [comment]
As you correctly point out - freqtrade does not support short selling at the moment (it's a work in progress).

it's also a trading bot - not a signal provider, so i'd not know how you'd act on these short signals.

Obviously, you can assign whatever column you want to the dataframe (also for shorts) - but current freqtrade code will simply ignore these columns - so it'll work IF your strategy is also providing the signal to "whatever".

**Comment by OreNoMochii** [comment]
ok understood. 
Thanks for your reply 
Kindest regards, 
Farrabi.
