### ISSUE TITLE
Webserver, Informative Decorator breaks "Visualize Results" Chart Display

### ISSUE THREAD

**Issue by Bloodhunter4rc** [freqtrade/freqtrade#6267]
## Describe your environment

  * Operating system: Windows WSL(Debian) Docker
  * Freqtrade Version: freqtrade docker-bb1d8fb5 (develop)
  
## Describe the problem:

Once the informative decorator is used within a strategy, you can not visualize results anymore in the Webserver, a exception is thrown.

### Steps to reproduce:

  1. Define a Informative Pair inside the Strategy with the Decorator (you dont have to actively use it)
  
```
    @informative('1h')
    def populate_indicators_1h(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)

        return dataframe
```

  2. Start the Webserver
  3. Start the Backtest
  4. Click on Visualize Results
  5. Click on one of the Pairs were a Trade happened
  
### Observed Results:

  * What happened?

Upon clicking on "Visualize Results" and after that on a pair where a trade happened, a exception is thrown, and the chart is not displayed.

  * What did you expect to happen?

Display the Chart with the candles and the result :)

### Relevant code exceptions or logs

> 2022-01-21 15:32:10,551 - uvicorn.error - ERROR - Exception in ASGI application
> Traceback (most recent call last):
>   File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
>     result = await app(self.scope, self.receive, self.send)
>   File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
>     return await self.app(scope, receive, send)
>   File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
>     raise exc from None
>   File "/home/ftuser/.local/lib/python3.9/site-packages/uvicorn/middleware/message_logger.py", line 78, in __call__
>     await self.app(scope, inner_receive, inner_send)
>   File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/applications.py", line 211, in __call__
>     await super().__call__(scope, receive, send)
>   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
>     raise exc
>   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
>     await self.app(scope, receive, _send)
>   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
>     await self.app(scope, receive, send)
>   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
>     raise exc
>   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
>     await self.app(scope, receive, sender)
>   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
>     await route.handle(scope, receive, send)
>   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
>     await self.app(scope, receive, send)
>   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
>     response = await func(request)
>   File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
>     raw_response = await run_endpoint_function(
>   File "/home/ftuser/.local/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
>     return await run_in_threadpool(dependant.call, **values)
>   File "/home/ftuser/.local/lib/python3.9/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
>     return await anyio.to_thread.run_sync(func, *args)
>   File "/home/ftuser/.local/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
>   File "/home/ftuser/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
>     return await future
>   File "/home/ftuser/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
>     result = context.run(func, *args)
>   File "/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 225, in pair_history
>     return RPC._rpc_analysed_history_full(config, pair, timeframe, timerange)
>   File "/freqtrade/freqtrade/rpc/rpc.py", line 1015, in _rpc_analysed_history_full
>     df_analyzed = strategy.analyze_ticker(_data[pair], {'pair': pair})
>   File "/freqtrade/freqtrade/strategy/interface.py", line 513, in analyze_ticker
>     dataframe = self.advise_indicators(dataframe, metadata)
>   File "/freqtrade/freqtrade/strategy/interface.py", line 880, in advise_indicators
>     dataframe = _create_and_merge_informative_pair(
>   File "/freqtrade/freqtrade/strategy/informative_decorator.py", line 83, in _create_and_merge_informative_pair
>     market = strategy.dp.market(asset)
>   File "/freqtrade/freqtrade/data/dataprovider.py", line 204, in market
>     raise OperationalException(NO_EXCHANGE_EXCEPTION)
> freqtrade.exceptions.OperationalException: Exchange is not available to DataProvider.

**Comment by xmatthias** [comment]
This is correct - there is no exchange in webserver mode at this moment.

For the moment, best switch to regular informative pairs (Without decorator).
