### ISSUE TITLE
Take-profit/Stop-loss

### ISSUE THREAD

**Issue by adelghaenian** [freqtrade/freqtrade#6269]
## Describe your environment
  * Operating system: Ubuntu 21.10
  * Python Version: 3.9 
  * CCXT version: 1.65.25 
  * Freqtrade Version: 2021.12 
  
## Your question
Is there any way to populate a buy order with its take profit and stop-loss? Like as I see in the documentation, we can set stop-loss percentage and ROI. However, what if we want to buy when the price reaches X, and sell if the price reaches Y (taking profit) or Z (stop loss). Something like this on Binance:
![image](https://user-images.githubusercontent.com/16430950/150607703-432387e0-8abd-409f-a147-826445fb96d7.png)

**Comment by xmatthias** [comment]
Freqtrade currently does not support this.

While you can partially get around this with `custom_sell` in combination with `custom_exit_price` - i'd strongly advise against that, as it'll mean you'll have a take profit order "lying" there until the timeout - but no stoploss order protecting you from that, so you "could" get filled on that quick swing up - but you could also lose it all as you're not having a stoploss in place.
