### ISSUE TITLE
Modify stoploss value from confirm_trade_exit function

### ISSUE THREAD

**Issue by rongybika** [freqtrade/freqtrade#6277]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.7.4 (`python -V`)
  * CCXT version: 1.59.2 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.10 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hi,

I'm trying to find out how I can set the stoploss value let's say to -1 (-100% of the actual price) in confim_trade_exit function if some condition are not meet.

I know that exist a custom_stoploss function but I don't know how to connect the two functions. Or maybe I can change it directly in confirm_trade_exit?

Thank you

**Comment by xmatthias** [comment]
`confirm_trade_exit` returns True if you want to "confirm" the exit, or False when you want to stay in the trade.

It's not supposed to modify anything else.
if you need to modify the stoploss, please use `custom_stoploss` - which will return the new stoploss relative to current price.

They're not supposed to be connected, as they technically do something else.

both of the above can also be found in the [callback documentation](https://www.freqtrade.io/en/stable/strategy-callbacks/).
