### ISSUE TITLE
How to get correct dates on the dataframe using informative decorator

### ISSUE THREAD

**Issue by souuu** [freqtrade/freqtrade#6285]
## Describe your environment

  * Operating system: macOS Big Sur 11.5.2
  * Python Version: Python 3.10.1 (`python -V`)
  * CCXT version: ccxt==1.66.32 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop-cf077b15c (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
I am using informative decorator to get information of the candles on different timeframes.
I have noticed that the candle dates are not matching in the dataframe.
Using this code snippet, I have visualised the dataframe. 

```
 @informative('15m')
 @informative('1h')
 @informative('4h')
 def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
         #RSI
         dataframe['rsi'] = ta.RSI(dataframe, timeperiod=4)
         dataframe.to_csv('test.csv')
         return dataframe
```

I am getting these results:
<img width="1363" alt="Screenshot 2022-01-23 at 23 56 58" src="https://user-images.githubusercontent.com/17356470/150701831-e7e184de-bfba-4e5f-911d-1efad924c430.png">
Is it expected to have the candle of 15m different from the candle of 1h ?
Thank you.

**Comment by stash86** [comment]
Yes because you are porcessing only closed candles.

**Comment by xmatthias** [comment]
All dates are candle open dates.
Freqtrade takes care of this in it's merging method, and merges them against the candle that closes.


So a 1h candle at 16:00 goes from 16:00-17:00 (it's available at 17:00) - so the correct 15m candle to merge it to is 16:45-17:00 - as the candle closes at 17:00 as well. 
Obviously that same 1h candle will then stay there for 4 15m candles (1 hour) - until the next candle is used.

As such - the merged dates are correct as they are.
