### ISSUE TITLE
How to access a custom indicator(values from a list)?

### ISSUE THREAD

**Issue by eveli909** [freqtrade/freqtrade#6297]
Hello,

I am struggling to use a custom indicator that would access the values from a list .
```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

      if self.dp:
              inf_tf = '1h'
              informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf)

              levels = []
              max_lines = []
              min_lines = []
              for i in range(5, len(informative)-5):

                  high_range = informative['high'][i-5:i+4]
                  current_max = high_range.max()
                  if not current_max in max_lines:
                     max_lines = []
                  max_lines.append(current_max)
                  ave = np.mean(informative['high'] - informative['low'])

                  if len(max_lines)==5 and np.sum([abs(current_max-level)<ave for _,level in levels])==0:
                     levels.append((high_range.idxmax(), current_max))

                  low_range = informative['low'][i-5:i+5]
                  current_min = low_range.min()
                  if not current_min in min_lines:
                    min_lines = []
                  min_lines.append(current_min)
                  ave = np.mean(informative['high'] - informative['low'])

                  if len(min_lines)==5 and np.sum([abs(current_min-level)<ave for _,level in levels])==0:
                     levels.append((low_range.idxmin(), current_min))
              informative['levels'] = levels
              dataframe = merge_informative_pair(dataframe, informative, self.timeframe, inf_tf, ffill=True)

      return dataframe
```

The plan is to use the values of that "levels" indicator that are stored in a list. However executing the code leads to the following warning:

```
2022-01-24 19:09:10,122 - freqtrade.strategy.strategy_wrapper - WARNING - Strategy caused the following exception: Length of values (17) does not match length of index (999)<bound method IStrategy._analyze_ticker_internal of <srsfalsebr.srsfalsebr object at 0x7f5a56cf3b50>>
```
As I understand the problem is that the "levels" list has less values than the dataframe, but I cannot find the way to solve that.
Can anybody help with pointing out how to:
1) Make that indicator (apparently, values from the list adding to the dataframe?
2) How to access these values later in buy signal?
I believe `qtpylib.crossed_above(dataframe['close'], dataframe['levels'])` would provide access to all values that are stored in "levels"!? But how would it be possible to access any value (any level) from that "levels" list?

**Comment by xmatthias** [comment]
I'd recommend [this section](https://www.freqtrade.io/en/stable/strategy-customization/#dataframe) in the docs which explains how to think vectorized, as well as some pandas tutorial to understand how to properly use this.

You'll need to think about a dataframe like it's a table (think excel table).

An access of `dataframe['columnname']` as something that gives you  whole column (so you also assign a whole column, not just one cell).

So if you need different levels (and each level should be there for each row) - you'll need to have `n` (levels, in your case) columns - basically assigning these as `dataframe[f'levels{n}'] = ...`  .

You'll also need to be very careful with your row level indexing.
You're using `i + - 5` - but and i think that'll look 5 rows into the future automatically - which automatically means you'll cheat backtesting.
 (you look at the last row of the dataframe) in backtesting - which will result in

**Comment by eveli909** [comment]
Thanks, I already had checked that section in Freqtrade docs, but I do not completely get that. I understand that dataframe is like a table but I do not really understand how to access the values of "levels" list in the last row of the dataframe, so I can further assess if the "close" or "high'' is above that level. Is there an option to use this type of indicator?

**Comment by xmatthias** [comment]
i'd strongly advise against using lists within one dataframe cell. 
That's usually difficult to understand as you'll have different indexes mean different things - and pandas also struggles with inference of what you're trying to do (using `informative['levels'] = levels` seems to assign levels to one level per row - not the whole list into the cell.

it's better to split it up into different columns - as also explained above.

**Comment by eveli909** [comment]
Thanks! Does that mean that an additional column in the dataframe should be created for each value from the "levels" list? So that in case if "levels" list contains 15 values, there are 15 columns added to the dataframe?

**Comment by eveli909** [comment]
When I try to print ` informative[f'levels{n}'] = levels`
I get the following error:
NameError: name 'n' is not defined

**Comment by stash86** [comment]
well, what is `n`? I can't find `n` in your snippet above

**Comment by xmatthias** [comment]
> When I try to print ` informative[f'levels{n}'] = levels` I get the following error: NameError: name 'n' is not defined

This was an example on how to create this - not intended to be "used as is" without further modification.
You'll have to change your code to use this approach instead of using a list - which is however a basic python task which can easily be researched by using google.
