### ISSUE TITLE
Execute sell protections after force sell an unfilled order 

### ISSUE THREAD

**Issue by dnuno89** [freqtrade/freqtrade#6298]
Sometimes I may want to cancel a buy order that has not been filled yet. However, this makes the bot to create a new buy order at a new and higher price, which will probably be filled. I have a candle delay protection, which does not execute as a sell hasn't been done. I've tried adding the pair to the blacklist and then either force selling or deleting the trade and manually cancelling the order, but if a buy signal exists the bot will create a new order. 

I think it would be better to execute the sell protections configured in the strategy every time that a Force sell is called, providing a way to cancell unfilled orders.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

You can [expire candles](https://www.freqtrade.io/en/stable/configuration/#ignoring-expired-candles) - so the buy-signal is only valid for the first X seconds of a candle.
Obviously if you have a sticking signal (one that's active for more than one candle) the next candle will still initiate another buy - but that's something you should fix at the strategy level.

Protections will execute once a trade closes. 
Cancelling a trade will not trigger them - and the intended behavior for canceled orders is to re-place the order if the buy signal is still active.
