### ISSUE TITLE
How to debug my stratergy with editors such as pycharm/vs_code?

### ISSUE THREAD

**Issue by harshadvekariya** [freqtrade/freqtrade#6300]
## Describe your environment

Operating system: macOS Monterery 12.1
Python Version: 3.9.9
CCXT version: 1.68.25
Freqtrade Version: freqtrade 2021.12

## Your question

I am currently running the freqtrade through docker from terminal. How can I use editors like pycharm/vs code to develope my own stratergy and debug it?

Running from terminal just gives me error that stratergy does not exist or there is error in stratergy. I would like to debug the code and get to the specific portion that is causing the error. Thank you in advance for your time!

**Comment by kelly323** [comment]
Maybe you could try and reboot the system

**Comment by xmatthias** [comment]
vscode has a plugin (remote / docker) which will connect vscode to containers (freqtrade also provides a dev-container configuration for this, and vscode will "offer" to open the repository in a dev-container if that plugin is installed).

I don't think that's supported by pycharm, at least it wasn't last time i checked a few months ago.

in general, if you're not very familiar with containers and debugging, you might be better of to install freqtrade natively in a virtual environment to debug, as that removes the "container complexity" - allowing you to focus on what you actually want to accomplish.

**Comment by 0xKoios** [comment]
Pycharm feature docker in professional version only https://www.jetbrains.com/help/pycharm/docker.html

**Comment by xmatthias** [comment]
I'd say a regular user will not have pycharm professional.
