### ISSUE TITLE
Run `advise_all_indicators` in parallel

### ISSUE THREAD

**Issue by italodamato** [freqtrade/freqtrade#6301]
## Describe your environment

- Operating system: MacOS 12.1
- Python Version: Python 3.9.8
- CCXT version: ccxt==1.68.20
- Freqtrade Version: freqtrade develop-fb0413c

## Describe the enhancement

Would it be possible to run`advise_all_indicators` in parallel for each pair when hyperopting? It can take quite a long time when hyperopting on many pairs with parameters with large ranges. I've tried to implement it with both `joblib` and `multiprocessing` but I get that it's not possible to pickle `self.advise_indicators`. Not sure if there's a workaround. 
https://github.com/freqtrade/freqtrade/blob/2e2b1e24701dffa172eea685952abec240ee48d9/freqtrade/strategy/interface.py#L897

**Comment by xmatthias** [comment]
It's clearly not possible at the moment - and the real improvement it'll give you will heavily depend on the indicators used. Usually, a good selection of "performant" implementations will give you more benefit than parallelizing this.
ta-lib is usually quite good at this (except for pattern recognition stuff) - some pure python libraries (pandas_ta, technical, ...) will sometimes suffer from algorithms that require looping. 

if you're waiting "a long time" for it to calculate (quite undefined, actually) -it's quite likely that you'll run out of memory anyway once the data needs to be spawned out across the worker processes, unless you've got an insane amount of memory.

**Comment by italodamato** [comment]
Aren't all the datasets loaded in memory anyways when running the hyperopt itself in parallel? The memory consumption during the initialization stage is pretty low. 

Another solution would be to cache the results of the initialization somehow, in case the strategy hasn't changed since the last run.

**Comment by xmatthias** [comment]
> Another solution would be to cache the results of the initialization somehow, in case the strategy hasn't changed since the last run.

that's done for backtest results now - but for indicators that can be problematic i think, as the calculated indicators/columns can depend on the selected spaces (if you're using `.range`).
so the only way to have that reliably run is if everything is exactly the same (same config, same spaces, same strategy) ... which is probably not what most people are after, so the benefits are very slim (you'll usually want to run with `--spaces buy` - then `--spaces sell`, ...) - which would have to evict results each time.

---

to run in parallel you've got quite some complexity i think - as you can't really know which data is used (in theory, you could require the data for the full pairlist to analyze every pair (for example to analyze if it's the "biggest raiser"). 
It's pretty simple to have that work for one strategy - but to have it work reliably for all possibilities we don't think of will be pretty difficult, if not impossible (you can't pickle all objects as you've encountered already - which means that possibilities will become limited, potentially removing current possibilities).

**Comment by xmatthias** [comment]
This can now be accomplished by using the newly introduced `--analyze-per-epoch` hyperopt option.

it'll no longer resolve the whole `.range` at startup - but will run `populate_indicators()` at each epoch - just calculating the indicator for the value that's been selected at that point.

this will make indicator calculation in fact parallel - as `populate_indicators()` will now be running in parallel, right before backtesting.

**Comment by popperwin** [comment]
I wish to compute advise_all_indicators in parallel for each pairs during Backtesting to speed up the backtests. I'm not Hyperopting.  

@xmatthias When you says  
> this will make indicator calculation in fact parallel - as `populate_indicators()` will now be running in parallel, right before backtesting.

Does it mean it's also executed in parallel in Backtest?  However I looked at the code and I can see it's not done in parallel:
https://github.com/freqtrade/freqtrade/blob/c4a0910908601cb7ae63645e41353123d0c4916f/freqtrade/strategy/interface.py#L1313-L1324

Do you have any approach to do it in parallel? I try to used concurrent.futures  ProcessPool without any success; ThreadPool is working but it's really slow and return the same pair multiple times.

Thanks

**Comment by xmatthias** [comment]
The way multiprocessing works in python at the moment, it's unlikely that we'll be supporting parallel analysis.

It's something i did look at in the past, but would remove a ton of features freqtrade strategies have - and is therefore not worth to look into further.

**Comment by fnwtv** [comment]
I see, thanks for your reply !
