### ISSUE TITLE
Telegram.error.timedout() : Timed out

### ISSUE THREAD

**Issue by abd011** [freqtrade/freqtrade#6313]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: 3.8.10

  * Freqtrade Version: Docker 

Question:
Hi, I just installed the freqtrade using docker, everything is working alright, but the problem arising is when i enable telegram, it give me an error something like Telegram.error.timedout() : timed out, and if I disable telegram from config.json then the bot works fine. I am pasting below all the lines of code appears when I run the bot through command "docker-compose up" (with telegram enabled). And yes, chat_id, token, everything is entered correctly.

Copy-pasted material is long so i am attaching the text file.
[message.txt](https://github.com/freqtrade/freqtrade/files/7961233/message.txt)

**Comment by xmatthias** [comment]
A timeout is basically always at network level.

in telegram's case, this is usually one of 2 things
* your host is blocked from accessing telegram (for example on some ISP's in russia, but not limited to that)
* telegram has an outage in your region.

While the 2nd will fix itself if you retry a little later - there is no real fix for the first issue other than moving your host to another country. In that case, it should also be consistent, and the problem should persist over multiple days.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
