### ISSUE TITLE
Time to calculate dataframe in backtesting much too long for develop-e7409e74c

### ISSUE THREAD

**Issue by perkmeister** [freqtrade/freqtrade#6314]
## Describe your environment
  * Operating system: Windows 10 Pro, WSL
  * Python Version: 3.8.10
  * CCXT version: 1.68.20
  * Freqtrade Version: develop-e7409e74c
  
## Describe the problem:
Latest develop-e7409e74c appears to have severe performance degradation during the dataframe calculation part of backtesting. The previous version develop-bb1d8fb54 seems to be OK.

### Steps to reproduce:
1. Run the attached Backtest1.py strategy with backtesting using 1 pair and any exchange. That simply loops through the dataframe once to put signals into the dataframe which are then used with .loc to generate buy and sell signals. Use a timerange of 10 days. Do this test with develop-e7409e74c and with develop-bb1d8fb54.

  ### Observed Results:
You should see with develop-bb1d8fb54 that the time delay between the `Running backtesting for Strategy` log and `Backtesting with data from` log is very short (less than a second on my system), but with develop-e7409e74c it is much longer (35 seconds on my system). 

 
[Backtest1.py.TXT](https://github.com/freqtrade/freqtrade/files/7962395/Backtest1.py.TXT)

**Comment by xmatthias** [comment]
The way this strategy is created is quite bad from a performance perspective in general (independent of the version).

You're looping through the whole dataframe (which is always slow) - this logic could very easily be done in a vectorized way (for example with `np.where()`.
The approach you take does n (actually n + 1) `.iloc[]` calls requests - so for each candle, it'll have to do a `.iloc`.

---

The strategy itself does not run and causes an exception (on neither of the 2 versions) - therefore please provide a working example - as i'll not spend my time debugging why your strategy is failing before actually trying to look at the problem.

---

Purely judging from your description (the provided strategy does not run):

The difference you probably see happens within the strategy - not in freqtrade code.
As such, nothing in freqtrade would cause these differences, as it's pure strategy code, and the only thing that could be relevant is the update of pandas from 1.3.5 to 1.4.0.

A quick look through their [issue tracker](https://github.com/pandas-dev/pandas/issues) doesn't show anything known at a first glance.

---

In my opinion, this is nothing freqtrade changed or can fix - so please create a freqtrade independent script to show the problem (basically just a simple script that shows the performance degradation between pandas versions) and open an issue against pandas.

**Comment by perkmeister** [comment]
OK, thanks. This was a very simple test strategy just to show looping through the dataframe, in my use case I'm creating a state machine that is effectively iterative and can't be vectorised so I created the simplest test program I could that showed the error. It is also fast in live as I don't need to iterate through the whole dataframe to get the next state, only the last row is really necessary to calculate the next state. 

The strategy does actually backtest without errors on both versions with the following config file and with this backtest command:
`freqtrade backtesting --datadir user_data/data/kucoin --export trades --timerange 20220117-20220124 -c user_data/config_backtest.json --strategy-list Backtest1 -i 5m`

It seems to be a pandas issue. Pandas has changed from 1.3.5 to 1.4.0 between the two versions, and I put some code in to time the loop. I've attached that updated test code, with these results:

With pandas 1.3.5: `total time taken this loop:  0.1792912483215332` 
With pandas 1.4.0: `total time taken this loop:  36.673600912094116`

When I used `pip install pandas==1.3.5` on the latest develop-e7409e74c the problem went away and I was back to the fast loop again. This is at least 2 orders of magnitude performance change between pandas versions.

[config_backtest.json.TXT](https://github.com/freqtrade/freqtrade/files/7963472/config_backtest.json.TXT)
[Backtest1.py.TXT](https://github.com/freqtrade/freqtrade/files/7963473/Backtest1.py.TXT)

**Comment by xmatthias** [comment]
I know that issue :laughing:  you try to throw something together "quickly" :laughing: 

backtesting either version  results in the following exception immediately - but i don't think that matters.

```
2022-01-29 13:44:24,341 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy Backtest1
2022-01-29 13:44:24,342 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/xmatt/devel/cryptos/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/xmatt/devel/cryptos/freqtrade/freqtrade/commands/optimize_commands.py", line 54, in start_backtesting
    backtesting.start()
  File "/home/xmatt/devel/cryptos/freqtrade/freqtrade/optimize/backtesting.py", line 798, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/home/xmatt/devel/cryptos/freqtrade/freqtrade/optimize/backtesting.py", line 719, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/home/xmatt/devel/cryptos/freqtrade/freqtrade/strategy/interface.py", line 898, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/home/xmatt/devel/cryptos/freqtrade/freqtrade/strategy/interface.py", line 898, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/home/xmatt/devel/cryptos/freqtrade/freqtrade/strategy/interface.py", line 921, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/xmatt/devel/cryptos/xmatt/strategies/Backtest1.py", line 86, in populate_indicators
    dataframe['buy_1'].iloc[row] = 1
  File "/home/xmatt/.pyenv/versions/3.9.7/envs/trade_397/lib/python3.9/site-packages/pandas/core/indexing.py", line 716, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/home/xmatt/.pyenv/versions/3.9.7/envs/trade_397/lib/python3.9/site-packages/pandas/core/indexing.py", line 1690, in _setitem_with_indexer
    self._setitem_single_block(indexer, value, name)
  File "/home/xmatt/.pyenv/versions/3.9.7/envs/trade_397/lib/python3.9/site-packages/pandas/core/indexing.py", line 1935, in _setitem_single_block
    self.obj._check_is_chained_assignment_possible()
  File "/home/xmatt/.pyenv/versions/3.9.7/envs/trade_397/lib/python3.9/site-packages/pandas/core/series.py", line 1263, in _check_is_chained_assignment_possible
    self._check_setitem_copy(t="referent", force=True)
  File "/home/xmatt/.pyenv/versions/3.9.7/envs/trade_397/lib/python3.9/site-packages/pandas/core/generic.py", line 4028, in _check_setitem_copy
    raise com.SettingWithCopyError(t)
pandas.core.common.SettingWithCopyError: 
A value is trying to be set on a copy of a slice from a DataFrame
```

---

As mentioned above - this is an issue with upstream pandas (as you also did confirm already) - therefore please report your usecase / problem to the pandas repository (otherwise it's unlikely it'll be fixed).
Searching through issue a bit will surely yield a quick way to generate some fake data - as a minimum reproduction will have to be detached from freqtrade for pandas to react.

**Comment by perkmeister** [comment]
Oh boy, it seems the behaviour of  `dataframe['buy_1'].iloc[row] = 1` has changed from pandas 1.3.5 to 1.4.0! I don't get any errors though (even if I remove my SettingWithCopyWarning warning suppression copied from another file, but I do get the warnings not errors now with 1.4.0, but not it seems with 1.3.5). 

There is an alternative way to set a column and that's with using `.at`, i.e. `dataframe.at[row, 'buy_1'] = 1`, so I tried that instead, and 1.4.0 is now happy, back to fast loops.

FYI here's the updated test code if you're interested (a bit academic now though ;) )

Really sorry to have messed you about here Matthias, and thank you for looking into it. It seems 1.4.0 is OK after all and it was me using an unreliable way to set a column even though it appeared to work and no indication it didn't in 1.3.5. 

[Backtest2.py.TXT](https://github.com/freqtrade/freqtrade/files/7963855/Backtest2.py.TXT)

**Comment by xmatthias** [comment]
using `dataframe['buy_1'].iloc[row] = 1` is problematic overall (and pandas also documents it as ambiguous iirc).

the first part `dataframe['buy_1']` is selecting a column. I know this as i know your intend.
Pandas does however not automatically know that you try to get a column, so it'll have to go look at both columns and rows, and select the "better matching".
`dataframe[1]` would for example select the 2nd row (python indexing starts at 0).

For freqtrade's dataframes, it's usually not a problem (we don't use string indexes for the rows) - but it can still cause odd behaviour if you're not aware of it.

This ambiguity obviously causes additional calculation steps internally, to determine the right index to use.

---


the same goes for assigning ... our samples do not use the "100% correct" syntax (for simplicity's sake, really).
`dataframe['sma'] = ta.SMA(dataframe)` should really be written as `dataframe.loc[:, 'sma'] = ta.SMA(dataframe)` - to remove all doubt for pandas.

It's not a problem as long as you don't use numbers as index - but then it would cause "odd" errors (e.g. `dataframe[0] = ta.SMA(dataframe)` could mean "assign SMA to the first row - or assign SMA to the column 0 (so replace the date). neither of the 2 is correct, or what you intended to do - but using `dataframe.loc[:, 0] = ` - it's at least clear we're talking about the column, not the row.

**Comment by perkmeister** [comment]
Nice, thanks for that, learning more about the nuances of pandas, always a good thing ;) I didn't know dataframe['sma'] would search both rows and columns for the 'sma' string, this is very useful information.
