### ISSUE TITLE
Telegram /status table # of buys

### ISSUE THREAD

**Issue by Pit-CL** [freqtrade/freqtrade#6317]
## Describe your environment

  * Operating system: Debian 11
  * Python Version: Python 3.9
  * CCXT version: 1.70
  * Freqtrade Version:  develop-e7409e74c,
  
## Describe the problem:

When you use /status table on telegram you get wrong number of total buys permited by the robot.
I think that the numer of buys must be 4/5 that means 4 buys over 5 total (1 buy plus 4 rebuys) instead of 4/0 as the example below.

### Steps to reproduce:

/status table
  
### Observed Results:

kucoin, [29-Jan-22 8:33 AM]
  ID  Pair      Since    Profit (USD)    # Buys
----  --------  -------  --------------  --------
  58  FKX/USDT  19 h     -3.23% (-6.42)  4/0

**Comment by xmatthias** [comment]
This will solely depend on your configuration - and the `/0` part will only be correct if you've configured `max_entry_position_adjustment`.

If that property is not configured, then it defaults to -1 - which results in `0` being displayed (as it's not configured - we don't know how many you'd like).

**Comment by Pit-CL** [comment]
Thanks, gotcha!

**Comment by xmatthias** [comment]
We'll no longer show the `/0` if that property is not configured.
