### ISSUE TITLE
How to add external data sources in real time algorithms?

### ISSUE THREAD

**Issue by mllamazares** [freqtrade/freqtrade#6335]
I have an external API endpoint with sentiment data that I would like to implement in my bot logic.

For testing purposes, the process is quite straightforward: I simply merge the main dataframe with a pre-downloaded one using the timestamp as a key, and then the algorithm has access to the additional columns.

However, can I use a similar approach in a live environment (real-time)? My idea is to add the external API request to in the `populate_indicators()` function, like this:

```python
self.dataframe['sentiment'] = apihandler.SuperCoolAPIEndPoint(n_candles=30, type='avg')
```

Any advice on how to handle these scenarios? Thanks!

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

A strategy is just python - so whatever you can code, you can usually also implement, given sufficient skill.

That said - you might need to be careful on how you approach this.

Your call looks to be a "generic" call (not pair specific) - so a better approach might be to place it in `bot_loop_start` - which runs only once per iteration (which is still roughly once every 5 seconds in ideal circumstances) - and then store the result in a `custom_info` object.

`populate_indicators` runs once for every pair (again, every 5s by default).

Especially in the latter case - you'll be hammering the API (if it ain't your API - you may get rate-limited) for no good reason, so i'd also recommend good error handling as well as timeouts (the bot should not stop if the api is down), as well as some caching (so it's not calling every 5 seconds, when the data only changes once per hour or whatever).

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.
