### ISSUE TITLE
Use indicators from another timeframe in a strategy

### ISSUE THREAD

**Issue by chacha0101** [freqtrade/freqtrade#6347]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: python 3.7 (`python -V`)
  * CCXT version: 1.65.25 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2021.12 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi!!

First of all thank you for this awesome project!

I'm trying to develop a new strategy and I would like to use indicators from another timeframe.
For instance, I would like to get RSI from 30m timeframe while my strategy is developed for a 5m timeframe.

`def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:'
'       # RSI'
'       dataframe['rsi'] = ta.RSI(dataframe) # how to specify the timeframe?'
'      return dataframe'

I haven't found anything on this subject. Do you think this is possible?

Thank you for your help :)

**Comment by xmatthias** [comment]
In general, i'd recommend to read the documentation (or at least fly over it) to get a grasp what is possible with freqtrade and how.
This topic is clearly (and extensively covered by the documentation).

It's called [informative pairs](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs).

We also have a [full example](https://www.freqtrade.io/en/stable/strategy-customization/#complete-data-provider-sample) covering exactly your usecase (calculating RSI).

a simpler/more modern way for this is through the [`@informative` decorator](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs-decorator-informative) - which again - has a sample calculating RSI in another timeframe.
