### ISSUE TITLE
recover the purchase value and the value of ema25 and ema50 at the time of the purchase

### ISSUE THREAD

**Issue by malcomZ** [freqtrade/freqtrade#6351]
## Describe your environment

  * Operating system: Debian 10
  * Python Version: Python 3.7.3
  * CCXT version: 1.49.52
  * Freqtrade Version: freqtrade develop-6c50157c
  
## Your question
Hello,

For the realization of a strategy I would need to recover the purchase value and the value of ema25 and ema50 at the time of the purchase (potentilly 20 minutes after for the example), but I do not find information to do it.
Is this possible?

Thank you in advance for your help and your time

**Comment by xmatthias** [comment]
Our documentation pretty much covers this in the [callback section](https://www.freqtrade.io/en/stable/strategy-callbacks/).

for all callbacks that are relevant for sells - you'll get a trade-object with it.
The trade-object contains `open_rate` (as well as `open_date_utc`) - which will give you the entry rate.

Combine this with some [advanced strategy topics](https://www.freqtrade.io/en/stable/strategy-advanced/#dataframe-access) - and you should be able to get whatever you need.

**Comment by malcomZ** [comment]
Hello,

Thank you once again for your time.

I will read up and if I have any further questions I will come back to you.

Thank you again for your time.

**Comment by dnuno89** [comment]
Hello,

I have a similar use case. In the confirm_trade_exit() callback, I do:

```
tdelay = int((current_time - trade.open_date)/timedelta(minutes=5))
dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
dfTrade = dataframe.shift(tdelay)
```

This will give you all the data as was known when the bought was done.
However, this works fine for me for backtesting but not in live or dry-run. Hope this helps.

**Comment by xmatthias** [comment]
The correct way is in the [documentation](https://www.freqtrade.io/en/stable/strategy-advanced/#dataframe-access) i've linked to above.


``` python
        # In dry/live runs trade open date will not match candle open date therefore it must be 
        # rounded.
        trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
        # Look up trade candle.
        trade_candle = dataframe.loc[dataframe['date'] == trade_date]
        # trade_candle may be empty for trades that just opened as it is still incomplete.
        if not trade_candle.empty:
            trade_candle = trade_candle.squeeze()
```

**Comment by malcomZ** [comment]
Hello, I want to come back to you because during the implementation I find myself with errors more precisely the variable ratio does not exist whereas I return it well.
Can you help me?

Thanks in advance
```
# --- Do not remove these libs ---
from freqtrade.strategy.interface import IStrategy
from pandas import DataFrame
# --------------------------------
import talib.abstract as ta
from technical.util import resample_to_interval, resampled_merge


class Ratio1(IStrategy):
    """

    author@: Gert Wohlgemuth

    based on work from Creslin

    """
    minimal_roi = {
        "0": 0.01
    }

    # Optimal stoploss designed for the strategy
    stoploss = -0.05

    # Optimal timeframe for the strategy
    timeframe = '5m'

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe['ema25'] = ta.SMA(dataframe, timeperiod=25)
        dataframe['ema50'] = ta.SMA(dataframe, timeperiod=50)
        dataframe['ema100'] = ta.SMA(dataframe, timeperiod=100)      
        dataframe['average'] = (dataframe['close'] + dataframe['open'] + dataframe['high'] + dataframe['low']) / 4
        return dataframe

    def confirm_trade_exit(self, pair: str, trade: 'Trade', order_type: str, amount: float,
                           rate: float, time_in_force: str, sell_reason: str,
                           current_time: 'datetime', **kwargs) -> bool:
        trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
        trade_candle = dataframe.loc[dataframe['date'] == trade_date]
        trade_candle50 = dataframe.loc[dataframe['date']['ema50'] == trade_date]
        if not trade_candle.empty:
            trade_candle = trade_candle.squeeze()
        if not trade_candle50.empty:
            trade_candle50 = trade_candle50.squeeze()
        ratio = (trade_candle - trade_candle50) * 1.5
        return ratio, trade_candle50

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                    ////
            ),
            'buy'] = 1
        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe["average"] >= ratio) |
                (dataframe["average"] <= trade_candle50)
            ),
            'sell'] = 1
        return dataframe
```

**Comment by xmatthias** [comment]
Well yes - ratio does not exist - it's in a different function.

Please also familiarize yourself with the [bot execution logic](https://www.freqtrade.io/en/stable/bot-basics/#bot-execution-logic) - which will show you that whatever you do in confirm-trade-exit will not be available in `populate_sell_trend` - as `populate_sell_trend` is called way earlier.
