### ISSUE TITLE
API blacklist: not returning extra added pairs

### ISSUE THREAD

**Issue by ePascalC** [freqtrade/freqtrade#6355]
When using the API v1/blacklist, I only get the initial BNB/* back and not the ones that were added in the UI. I checked both the 'blacklist' and 'blacklist_expanded'

From the UI:
![image](https://user-images.githubusercontent.com/18325208/152646392-713f993b-abf8-4359-8339-6ce6d3a8380e.png)

From the API GET:
![image](https://user-images.githubusercontent.com/18325208/152646415-c02b6799-d8d6-406b-ad91-a74e2aaba5e9.png)

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Also - please try to describe your issue in a way so it's clear what you expected (it's absolutely not from the above).
I assume you'd like to have the "expanded" blacklist shown in the list (but i'm really not sure if that's what you're asking ...).

**Comment by ePascalC** [comment]
Understood. Closing for now.
