### ISSUE TITLE
hyperopt `max_entry_position_adjustment`

### ISSUE THREAD

**Issue by italodamato** [freqtrade/freqtrade#6356]
## Describe the enhancement

Is it possible hyperopt `max_entry_position_adjustment`?

**Comment by xmatthias** [comment]
No it's not, but i'm also not sure it makes too much sense, as it's really a value that'll depend on your account-size (and max-open-trades) - so the possible values are very very small in almost all instances.

Adding a "hyperopt possibility" for all parameters is really pointless and will only make things more confusing without providing any real benefit - so for the moment, i'm also not considering adding this.

**Comment by xmatthias** [comment]
One thing you could try is the "property" approach - similar to how optimizing protections works (basically you change `max_entry_position_adjustment` to be a property and return the `int()` of the result.

It's untested, but i don't see anything that would prevent this at the moment (there's no real need to have a separate space for this).

Would be great if you could report back if that idea works.

**Comment by italodamato** [comment]
Yes, it seems to be working! Good idea :)
```python
@property
def max_entry_position_adjustment(self):
	return self.max_epa.value
    
max_epa = CategoricalParameter([0, 1, 3, 5, 10, 999], default=1, space="buy", optimize=True)
```
