### ISSUE TITLE
How to backtest multiple config files

### ISSUE THREAD

**Issue by sabatale** [freqtrade/freqtrade#6357]
## Describe your environment

  * Freqtrade Version: Latest
  
## Your question

Based on the documentation, I understand the backtesting can handle multiple strategies and configuration files within the same run: [https://www.freqtrade.io/en/stable/backtesting/#backtesting-multiple-strategies](https://www.freqtrade.io/en/stable/backtesting/#backtesting-multiple-strategies).

However I am unable to see the results from multiple configurations when running something similar to:
`docker-compose run --rm freqtrade backtesting --config user_data/config1.json --config user_data/config2.json --strategy-list ABC --timeframe 5m --enable-protections`

I get a single result when I was expecting two (one per config) so I'm assuming only the second config was tested.

Did I misunderstand what "Multiple --config options may be used." means the documentation?

<img src="https://user-images.githubusercontent.com/50220345/152652143-ea36c27e-0cf0-4a66-a48c-4a83c449bde1.png" width="250" height="200" />

**Comment by xmatthias** [comment]
you can provide multiple config files as you're doing above (via multiple `--config` flags). 
The configurations will be merged together [as explained here](https://www.freqtrade.io/en/stable/configuration/#multiple-configuration-files) - so in the end, you'll have one configuration.


You can backtest multiple strategies with `--strategy-list` - and certain parameters (the ones that can be set [via strategy](https://www.freqtrade.io/en/stable/configuration/#parameters-in-the-strategy)) can be different between the strategies (but they must be set by the strategy, not from the configuration file).
