### ISSUE TITLE
Hyperopt trailing_stop_positive_offset and minimal_roi

### ISSUE THREAD

**Issue by sabatale** [freqtrade/freqtrade#6359]
## Describe your environment

  * Freqtrade Version: Latest
  
## Your question

I'm trying to understand this bit from the documentation: `Make sure to have this value (trailing_stop_positive_offset) lower than minimal ROI, otherwise minimal ROI will apply first and sell the trade.`

During my tests (e.g., with [this one](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/BinHV45.py)), the hyperopt often gives me trailing values higher than the minimal ROI that don't make much sense to me.

For example, I've been using `--spaces all trailing` with `SortinoHyperOptLossDaily` and a thousand executions:

```
**freqtrade hyperopt-show -n 300 --print-json --no-header**

{
"params":
  {
    "buy_bbdelta":15,
    "buy_closedelta":19,
    "buy_tail":23
  },
  "minimal_roi":
  {
    "0":0.20500000000000002,
    "35":0.042,
    "87":0.028,
    "206":0
  },
  "stoploss":-0.08
  "trailing_stop":true,
  "trailing_stop_positive":0.311,
  "trailing_stop_positive_offset":0.312,
  "trailing_only_offset_is_reached":true
}
```

Is this something that should not happen during hyperopt? Or am I right to assume it's getting lost because of the `all` space?

I'm not completely clear on how this works yet, but I'm guessing this would happen during live trading:

- the bot buys an asset at a price of 100$
- the stop loss is defined at -8%
- the stop loss would get triggered once the asset drops below 92$
- stoploss will remain at 92$ unless asset increases to or above the configured offset
- assuming the asset now increases to 131.2$ (where we have the offset configured)
- the stop loss will now be -31.1% of 131.2$ = 90.3968$
- but none of it matters because minimal_roi sells at 20.5% profit or less? so no trailing stop ever applies

**Comment by xmatthias** [comment]
The above result effectively disables trailing_stop (if you look at the backtest results for this configuration, you'll not have any "trailing_stop" sells).

Hyperopt is using Bayesian search to find good values, which means it's usually better than simple brute-forcing of every value, as it uses some logic to move to the right area.

Unfortunately, scikit-optimize doesn't allow for nested spaces.
This means, hyperopt could spend 100 epochs optimizing `trailing_stop_positive` - while having `trailing_stop = False` - getting the same result all the time (maybe it's also changing ROI - but it never notices that the changes to `trailing_stop_positive` have no effect).
This is a similar problem in the end. 
We've required the user to manually transfer the results to the strategy until quite recently to require "thinking about the result" - so the user will detect "this result does not make sense as is".


While freqtrade allows to hyperopt all spaces at once - that will rarely yield a good result - as the space becomes too big very soon (and 1000nds of epochs will usually have you "stuck" in a local minima after a while, never finding better results).
A usually better approach is to go "step by step" - so you first have a good buy signal (obviously with sane defaults for the remaining spaces) - and then go on to optimize the different sell signals (like ROI and trailing stop).

We also have a [FAQ entry](https://www.freqtrade.io/en/stable/faq/#how-many-epochs-do-i-need-to-get-a-good-hyperopt-result) about this - explaining that too many epochs usually don't make much sense.

**Comment by sabatale** [comment]
Thanks for the detailed explanation! I completely agree with having users manually transfer the results as I would have probably missed it otherwise. Not sure if you ever thought of implementing some basic warning rules (e.g., offset superior to minimal_roi) - although it's up to the user in the end.

So, in summary, it's best to set conservative default values in the strategy and then come up with a bat file executing something like:

```
freqtrade hyperopt --spaces buy sell --hyperopt-loss SortinoHyperOptLossDaily --strategy SampleStrategy -e 600
(repeat *16)
pause

freqtrade hyperopt --spaces roi stoploss --hyperopt-loss SharpeHyperOptLossDaily --strategy SampleStrategy -e 600
(repeat *16)
pause

freqtrade hyperopt --spaces trailing --hyperopt-loss SharpeHyperOptLossDaily --strategy SampleStrategy -e 600
(repeat *16)
pause
```

**Comment by xmatthias** [comment]
personally, i'd combine stoploss and trailing spaces.

I'm not sure if a bat-file will give you what you want. 
While freqtrade will select the "best" epoch - that's often not the desired one (maybe you have others with higher profits but fewer trades (or viceversa) ... so objective values (what's sorted on) are always objective - meaning they'll usually not cover 100% of what you'd like (and it's also difficult to say that first - would you prefer 1000 trades with 100% profit (drawdown of 20%) - or 500 trades with 99% profit (but a drawdown of 10%) ...

As such, i'd recommend to manually investigate each result before continuing with the next space.

**Comment by sabatale** [comment]
Yes, the bat file was just to semi-automate hyperopt in some way when working on a strategy.

But I'll have to think about it more. The whole process as such does take some time!

I'm running it over 3 months usually but maybe I'll just switch to 30 days.
