### ISSUE TITLE
Advertise in Freqtrade?

### ISSUE THREAD

**Issue by newsum** [freqtrade/freqtrade#6372]
Hi - Do you offer banner advertisements in freqtrade? I am interested in purchasing a placement.

**Comment by xmatthias** [comment]
we currently do not.

Where would you imagine to show this?
in the documentation, in frequi, ... ? 
and what format would you imagine this to have (one thing will be for sure - we will NOT be showing anything that's not hosted and vetted by ourselfs).

**Comment by xmatthias** [comment]
Let's discuss further in discord.
