### ISSUE TITLE
Sell&buy amount

### ISSUE THREAD

**Issue by KaanRF** [freqtrade/freqtrade#6376]
## Describe your environment

  * Operating system: raspian lite
  * Python Version: 3.9 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Hi 
I have one silly question which is about sell and buy amount. In case if i use exchange which i have some holding, like below scenario makes me confuse and i could not find a documentation about it. 

E.g;

I have 50 foo coin on my spot account and the bot bought 20 foo coin more then on my spot account will 70 foo coin, when the bot sell the foo coin he will not touch my first 50 foo coin and sells only 20  ? 

Second question

I have 50 foo coin on my spot account and the bot bought 20 foo coin more then on my spot account will 70 foo coin, and then price is decreased sharply, to adjust my position he bought 20 more foo coin.  Total the bot bought 40 foo coin with 2 rebuy, when the bot sells the foo coin he will not touch my first 50 foo coin and sells only 40  ? And he will calculate loss and profit only what he bought right ?

**Comment by xmatthias** [comment]
Freqtrade will not touch your coin holdings except for the holdings in stake-currency (where you can however [define](https://www.freqtrade.io/en/stable/configuration/#assign-available-capital) how much will be used), and will only sell coins which it "owns" itself (which are part of it's database - so the bot itself bought).

It does not matter how it bought them (all at once, or in multiple steps). the "coin" that was available prior to freqtrade starting will not be touched - except if it's in stake_amount.
