### ISSUE TITLE
Two services on a pi4 using different strategies

### ISSUE THREAD

**Issue by batikiotis** [freqtrade/freqtrade#6377]
## Describe your environment

  * Operating system: Linux raspberrypi 5.10.92-v7l+
 
  
## Your question
Hello all, keep the nice work.
i'm trying to run 2 services in a single pi4. i have two config files in my freqtrade dir  (config.json and configA.json ) with different strategies (SampleStrategy and Diamond) and two different user data directories (user_data and user_dataA -> added  "user_data_dir":"user_dataA" in configA.json). Then i have created two freqtrade services files and added them in /etc/systemd/system.
The first one has a normal behaviour communicating with my telegram bot. The second one, the one with A on the suffix is enabled and seems to running but i get timeouts every 2 minutes and messages to my second bot like starting.

```
Feb 08 13:55:50 raspberrypi freqtrade[3264]: 2022-02-08 13:55:50,769 - freqtrade.wallets - INFO - Wallets synced.
Feb 08 13:55:50 raspberrypi freqtrade[3264]: 2022-02-08 13:55:50,770 - freqtrade.plugins.protectionmanager - INFO - No protection Handlers defined.
Feb 08 13:55:50 raspberrypi freqtrade[3264]: 2022-02-08 13:55:50,951 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
Feb 08 13:55:52 raspberrypi freqtrade[3264]: /home/pi/freqtrade/.env/lib/python3.9/site-packages/telegram/ext/dispatcher.py:250: UserWarning: Asynchronous callbacks can not be processed without at least one worker thread.
Feb 08 13:55:52 raspberrypi freqtrade[3264]:   warnings.warn(
Feb 08 13:55:52 raspberrypi freqtrade[3264]: 2022-02-08 13:55:52,955 - apscheduler.scheduler - INFO - Scheduler started
Feb 08 13:55:53 raspberrypi freqtrade[3264]: 2022-02-08 13:55:53,251 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['forcebu>
Feb 08 13:55:53 raspberrypi freqtrade[3264]: 2022-02-08 13:55:53,251 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.api_server
Feb 08 13:55:54 raspberrypi freqtrade[3264]: 2022-02-08 13:55:54,831 - freqtrade.rpc.api_server.webserver - INFO - Starting HTTP Server at 127.0.0.1:8081
Feb 08 13:55:54 raspberrypi freqtrade[3264]: 2022-02-08 13:55:54,831 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.
Feb 08 13:55:54 raspberrypi freqtrade[3264]: 2022-02-08 13:55:54,875 - uvicorn.error - INFO - Started server process [3264]
Feb 08 13:55:54 raspberrypi freqtrade[3264]: 2022-02-08 13:55:54,876 - uvicorn.error - INFO - Waiting for application startup.
Feb 08 13:55:54 raspberrypi freqtrade[3264]: 2022-02-08 13:55:54,876 - uvicorn.error - INFO - Application startup complete.
Feb 08 13:55:54 raspberrypi freqtrade[3264]: 2022-02-08 13:55:54,877 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)
Feb 08 13:55:54 raspberrypi freqtrade[3264]: 2022-02-08 13:55:54,891 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/home/pi/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py'...
Feb 08 13:55:55 raspberrypi freqtrade[3264]: 2022-02-08 13:55:55,648 - VolumePairList - INFO - Pair BNB/EUR in your blacklist. Removing it from whitelist...
Feb 08 13:55:55 raspberrypi freqtrade[3264]: 2022-02-08 13:55:55,665 - VolumePairList - INFO - Searching 20 pairs: ['BTC/EUR', 'ETH/EUR', 'LUNA/EUR', 'SHIB/EUR', 'ADA/EUR', 'XRP/EUR', 'SOL/EUR', 'MATIC/EUR', 'AVAX/EUR', 'DOGE/EUR', 'DOT>
Feb 08 13:55:55 raspberrypi freqtrade[3264]: 2022-02-08 13:55:55,675 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
Feb 08 13:55:55 raspberrypi freqtrade[3264]: 2022-02-08 13:55:55,956 - freqtrade.worker - INFO - Changing state to: RUNNING
Feb 08 13:55:55 raspberrypi freqtrade[3264]: 2022-02-08 13:55:55,957 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': 'Dry run is enabled. All trades are simulated.'}
Feb 08 13:55:56 raspberrypi freqtrade[3264]: 2022-02-08 13:55:56,077 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `binance`\n*Stake per trade:* `20 EUR`\n*Minimum ROI:* `{'0': 0.242,>
Feb 08 13:55:56 raspberrypi freqtrade[3264]: 2022-02-08 13:55:56,157 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for EUR pairs to buy and sell based on [{'VolumePairList': 'VolumePair>
Feb 08 13:55:56 raspberrypi freqtrade[3264]: 2022-02-08 13:55:56,250 - freqtrade.persistence.models - INFO - Found open trade: Trade(id=1, pair=THETA/EUR, amount=6.80000000, open_rate=2.92000000, open_since=2022-02-08 10:55:12)
Feb 08 13:55:56 raspberrypi freqtrade[3264]: 2022-02-08 13:55:56,250 - freqtrade.persistence.models - INFO - Found open trade: Trade(id=2, pair=LTC/EUR, amount=0.16800000, open_rate=118.60000000, open_since=2022-02-08 11:10:13)
Feb 08 13:55:56 raspberrypi freqtrade[3264]: 2022-02-08 13:55:56,251 - freqtrade.persistence.models - INFO - Found open trade: Trade(id=3, pair=SOL/EUR, amount=0.20000000, open_rate=99.76000000, open_since=2022-02-08 11:15:14)
Feb 08 13:55:56 raspberrypi freqtrade[3264]: 2022-02-08 13:55:56,251 - freqtrade.persistence.models - INFO - Found open trade: Trade(id=4, pair=SXP/EUR, amount=15.10000000, open_rate=1.32000000, open_since=2022-02-08 11:15:17)
Feb 08 13:55:56 raspberrypi freqtrade[3264]: 2022-02-08 13:55:56,251 - freqtrade.persistence.models - INFO - Found open trade: Trade(id=5, pair=EOS/EUR, amount=8.70000000, open_rate=2.27600000, open_since=2022-02-08 11:15:18)
Feb 08 13:56:01 raspberrypi freqtrade[3264]: 2022-02-08 13:56:01,358 - freqtrade.worker - INFO - Bot heartbeat. PID=3264, version='develop-a733a74dd', state='RUNNING'
Feb 08 13:57:01 raspberrypi freqtrade[3264]: 2022-02-08 13:57:01,393 - freqtrade.worker - INFO - Bot heartbeat. PID=3264, version='develop-a733a74dd', state='RUNNING'
Feb 08 13:57:15 raspberrypi systemd[1]: freqtradeA.service: start operation timed out. Terminating.
Feb 08 13:57:15 raspberrypi systemd[1]: freqtradeA.service: Failed with result 'timeout'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit freqtradeA.service has entered the 'failed' state with result 'timeout'.
Feb 08 13:57:15 raspberrypi systemd[1]: Failed to start Freqtrade bot.
-- Subject: A start job for unit freqtradeA.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit freqtradeA.service has finished with a failure.
--
-- The job identifier is 5963 and the job result is failed.
```

**Comment by xmatthias** [comment]
> Feb 08 13:57:15 raspberrypi systemd[1]: freqtradeA.service: start operation timed out. Terminating.

the message simply states that it could not start.
this suggests that most likely, the executable cannot be found (but that's a guess, really).

You should also be able to find more with `journalctl -u freqtradeA.service` - which should include only the logs for this service.

**Comment by batikiotis** [comment]
matthias thank you for your answer. actually the service fully fuctional. i get messages of selling/buying in dry mode as i have set it.

**Comment by xmatthias** [comment]
so you have both services fully functional?

Are you using the regular setup, or the watchdog one?

**Comment by batikiotis** [comment]
Feb 08 11:44:34 raspberrypi systemd[5588]: freqtradeA.service: Failed to locate executable /root/freqtrade/freqtrade/main.py: No such file or directory
Feb 08 11:44:34 raspberrypi systemd[5588]: freqtradeA.service: Failed at step EXEC spawning /root/freqtrade/freqtrade/main.py: No such file or directory
Feb 08 11:44:34 raspberrypi systemd[1]: Started Freqtrade Daemon.
Feb 08 11:44:34 raspberrypi systemd[1]: freqtradeA.service: Main process exited, code=exited, status=203/EXEC
Feb 08 11:44:34 raspberrypi systemd[1]: freqtradeA.service: Failed with result 'exit-code'.
Feb 08 11:44:34 raspberrypi systemd[1]: freqtradeA.service: Scheduled restart job, restart counter is at 1.
Feb 08 11:44:34 raspberrypi systemd[1]: Stopped Freqtrade Daemon.


we have a clue!

**Comment by xmatthias** [comment]
Based on this, it's clear that the `exec` command  is wrong (which is what i suspected originally, too).

Best copy the one from the intial bot (up to ` trade`) - that should then work.

**Comment by batikiotis** [comment]
that's the first with no problem

```[Unit]
Description=Freqtrade bot
[Service]
WorkingDirectory=/home/pi/freqtrade
ExecStart=/home/pi/freqtrade/.env/bin/freqtrade trade --config /home/pi/freqtrade/config.json
Restart=always
RestartSec=10
Type=notify
NotifyAccess=all
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=freqtrade
User=root
Group=root
Environment=NODE_ENV=production
[Install]
WantedBy=multi-user.target
```


and this is the second

```[Unit]
Description=Freqtrade bot
[Service]
WorkingDirectory=/home/pi/freqtrade
ExecStart=/home/pi/freqtrade/.env/bin/freqtrade trade --config /home/pi/freqtrade/configA.json --strategy Diamond  --db-url sqlite:///strategyA.sqlite
Restart=always
RestartSec=10
Type=notify
NotifyAccess=all
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=freqtrade
User=root
Group=root
Environment=NODE_ENV=production
[Install]
WantedBy=multi-user.target```

**Comment by xmatthias** [comment]
The error clearly says it:
```
/root/freqtrade/freqtrade/main.py
```

Make sure that your systemd is uptodate (basically - that you ran `systemctl daemon-reload` ... otherwise it may use a cached systemd file (and make sure that you're editing the file that's used - check with `systemctl status freqtradeA`

**Comment by batikiotis** [comment]
> The error clearly says it:
> 
> ```
> /root/freqtrade/freqtrade/main.py
> ```
> 
> Make sure that your systemd is uptodate (basically - that you ran `systemctl daemon-reload` ... otherwise it may use a cached systemd file (and make sure that you're editing the file that's used - check with `systemctl status freqtradeA`

i tried many things today about debugging this but haven't managed to make the service not killed after a timeout. Unfortunately i can't see anymore /root/freqtrade/freqtrade/main.py on my logs!

**Comment by xmatthias** [comment]
Without logs / proper information, there is not much we can do to help you with.

you can try to:
stop both bots
start the one that's failing now first, and then the 2nd (is now the 2nd failing?)

You can also try to have freqtrade write logs to a file (`--log-file <file>`) - if you do that with 2 different files, you have 2 options:
either one file is not generated (then your Exec path is wrong) - or if freqtrade actually starts but fails to start - then the file contains information.


you should also make sure that you're following the [multiple instances](https://www.freqtrade.io/en/stable/advanced-setup/#things-to-consider) documentation (using different ports/different telegram bots). Having this wrong can cause the 2nd bot to not start.

---

If the above doesn't help - please provide me with the output of `systemctl status <service>` for both services.
that will contain a .service file name - i'd need the content of these files, too.


In general, i'd consider running freqtrade as systemd service as quite advanced. If you're not familiar with systemd services (and how to debug problems with them) - then this way of running freqtrade is probably not for you (we only provide limited support for systemd).

The recommended way to run freqtrade is via [docker](https://www.freqtrade.io/en/stable/docker_quickstart/) -  which is usually easier to run and maintain.

**Comment by batikiotis** [comment]
xmatthias you are pretty right, i should try something else or from scratch. 
i had separate service files/configuration files/ user data folders/ dbs / bots for each of them. the 2nd was always restarting every about two minutes, whether the first was started or stopped. my service files were built regarding this https://www.youtube.com/watch?v=FNtV3zRWf2U&ab_channel=DutchCryptoDad

**Comment by xmatthias** [comment]
that'll not help much - as I'm sure it works in the video.
As it doesn't work for you, this will mean that "something" will be slightly different between your <configuration/files/...> and what the video used - so if i watch the video, that will not help your case.

I've given you several hints what to try - but without any further information from your side (requested above), it'll be impossible to assist you further.

You may also attempt to get help from the video author. he tried to teach this method - so he should be able to point out potential pitfalls.
I've personally never ran multiple bots via systemd myself (i don't use systemd to run freqtrade).

Alternatively, I'd also suggest the [discord server](https://discord.gg/p7nuUNVfP7) - where you might find other people which run a similar setup - and people there are generally quite helpful (but you'll have to provide the informations that are requested - otherwise people will simply think "he doesn't want help, just complaining it ain't working" - and will simply stop helping you, and help others instead.

**Comment by batikiotis** [comment]
i went with docker, thank you for your help xmatthias
