### ISSUE TITLE
Error coming: telegram.error.NetworkError: urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:1129)

### ISSUE THREAD

**Issue by abd011** [freqtrade/freqtrade#6378]
Have you searched for similar issues before posting it? YES
Did you have a VERY good look at the [documentation](https://www.freqtrade.io/en/latest/) and are sure that the question is not explained there
YES

## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.10.2
  * Freqtrade Version: Docker version, latest
  
Question:

when I execute the sample strategy in terminal, all goes good, binance connects, dry run enabled & everything goes good but this error comes in :

raise NetworkError(f'urllib3 HTTPError {error}') from error

telegram.error.NetworkError: urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:1129)

When i run the command with telegram disabled, bot works fine, but when I enable the Telegram, this error comes in, I have rechecked the chat id and token and created a completely new bot too, but after all still this error is coming?
 Also my internet connection is fine and Telegram app is working fine too.

I am attaching the complete message in the file, as the code is big so better to attach a file.

Thankyou
[error.txt](https://github.com/freqtrade/freqtrade/files/8024415/error.txt)

**Comment by xmatthias** [comment]
The message is a network level problem (when doing the SSL handshake).

As it's with telegram, the most likely cause is a local telegram outage (local to the region you're in).
It's however also possible that something in your network is blocking Telegram access (as is reported to happen from time to time / on some ISP's in russia, but also other countries).

The last possibility is that it's something in your network (maybe a misconfigured pihole or some proxy that's messing with your communication.

**Comment by xmatthias** [comment]
I'll assume this as answered by the above.

Feel free to comment below / reopen if that's not the case.

**Comment by abd011** [comment]
I have just found out there is some issue of telegram in my region, it is not banned or blocked but some sort of server issue is there, so what could be the possible solution to this should i use some sort of vpn to connect the ft bot?

**Comment by xmatthias** [comment]
you can use a vpn or proxy - or better yet, simply rent a VPS in another region where it's not having problems.
