### ISSUE TITLE
Probit exchange doesn't work

### ISSUE THREAD

**Issue by lukasgor** [freqtrade/freqtrade#6379]
## Describe your environment

  * Operating system: ubuntu
  * Python Version: 3.8.10 (`python -V`)
  * CCXT version: 1.72.36 (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-f1cc1d9 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Starting the bot on probit exchange doesnt work

### Steps to reproduce:

  1. Start the live version of the bot on probit exchange (dry works fine)
  
### Observed Results:

Bot doesn't start and error is shown

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
freqtrade.exceptions.TemporaryError: Could not get balance due to AuthenticationError. Message: probit access token expired, call signIn() method
  ```
Any ideas? I'm ppretty sure key and secret are correct

**Comment by xmatthias** [comment]
The message says they are not.
Now some exchanges require a 3rd argument like a password.
You should also make sure that the entries are not inverted, or contain a leading/trailing space in the configuration.

**Comment by xmatthias** [comment]
Seems like probit requires some extraneous calls which need to happen at least every 15 minutes (based on https://github.com/ccxt/ccxt/issues/7295).

As that's the first (and currently only) exchange that seems to require this - it will not work with freqtrade.
I'd suggest to try one of the other supported exchanges instead. 
I'll also add this exchange to the "non-working" exchanges - so others won't stumble into the same issue.
