### ISSUE TITLE
use multiple stakes on the same config file and same backtest/optimization

### ISSUE THREAD

**Issue by joselao** [freqtrade/freqtrade#6380]
I don't know the reason that it's not possible to backtest/optimize/live.trade with multiple and different stakes coins.

It could be useful for minimizing processes (and not having to optimize twice: XXX/BTC & YYY/USDT) and it could allow Freqtrade to do trading with Arbitrage strategies (if AAADOWN/BBB are allowed in the exchange).

The idea could be to allow that option in the config file:

```
"tradable_balance_ratio": [ 0.99, 0.5, 0.99],
"stake_currency": ["BTC","USDT","ETH"]
"stake_amount": [0.0023, 1000, 0.032],
"dry_run_wallet": 0.075,
"pair_stakelist": [
      "BTC/USDT",
      "-ETH/BTC",
],
```

We can see 3 stake coins in a list in the `stake_currency` param, that will be traded in the same run, each with different `tradable_balance_ratio`, and `stake_amount`. The `dry_run_wallet` refers always to the first stake in the list, so all the backtest and optimization results will report all balances and profits in BTC. To do that Freqtrade will need the `pair_stakelist` that will allow converting all the stakes in the `stake_currency` list into the first one. in case that is not possible to find the BTC/ETH in your exchange you can add a minus "-" sign to do the inverse.

Finally, you will be able to add in your `pair_whitelist` all the combinations that you want:

```
"pair_whitelist": [

    "ETH/BTC",
    "SOL/BTC",
    "BNB/BTC",
    "LUNA/BTC",

    "BTC/USDT",
    "ETH/USDT",
    "BUSD/USDT",
    "SOL/USDT",

    "LUNA/ETH",
    "BNB/ETH",
    "SOL/ETH",
    "ADA/ETH"
],
```

I hope you will find it interesting.

And thanks for the effort in improving Freqtrade!!

Jose

**Comment by xmatthias** [comment]
This has been proposed several times before - but we've decided to not go down this path for now.

The effort and complexity for both configuration (from a user perspective) as well as from a maintenance perspective is not worth it.
The bigger problem is that you usually cannot use the same strategy on different pairs (a /USDT strategy will almost never work in /BTC markets and viceversa). 
These different markets move too different to efficiently optimize, so while you think it would be an improvement, it actually wouldn't be, as you'll still need different strategies (and then, why not use 2 different bots you can also control separately).

You'll also run into problems with the amount of pairs (say 50 /USDT pairs, 50 /BTC pairs, ...) - which will have a quite severe impact on performance (we must respect exchange ratelimits - so you'd get a new candle X seconds (or even minutes) after the candle actually completed.
As such, using multiple processes has speed/performance advantages as well, as you can decide yourself how to scale out.

The only advantage it'd bring is for arbitrage strategies, but these would also require different exchanges, which would again be a whole other level of complexity.

As such, my opinion on this did not change - the effort this would need is not worth the outcome. 
Therefore we'll rather focus on other improvements (futures/margin/short trading, and scaling in and out of a position).

**Comment by joselao** [comment]
Ok thanks for your explanation!! seems logical what you said!!
