### ISSUE TITLE
Multibot installation chown problem directory user_data does not exist Docker on Windows

### ISSUE THREAD

**Issue by shalb2018** [freqtrade/freqtrade#6382]
## Describe your environment

  * Operating system: Windows 10 Docker
  * Python Version: from Docker 
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.1 
  
## Your question

I have been running Freqtrade with single bot for over a month and wanted to test now with multiple bots. I followed the instructions in the Freqtrade documentation exactly. When I try to start the containers I get an error "Directory `/opt/freqtrade/user_data` does not exist." and before a warning "Could not chown /opt/freqtrade/user_data". 
I have the folders user_data, the correct databases and configuration files. The containers are created, but continuesly start, exit and restart.

**Comment by xmatthias** [comment]
please provide us with the full logs that are output when starting the bot.

The provided information is unclear - and makes us guess if the error is shown from freqtrade or from docker itself (or maybe from the operating system).

**Comment by shalb2018** [comment]
Here my Log File
[freqtrade1.log](https://github.com/freqtrade/freqtrade/files/8035219/freqtrade1.log)

**Comment by xmatthias** [comment]
that's clearly not a default docker-compose file.

I assume you're setting `user_data_dir` somewhere to `/opt/freqtrade/user_data` (either in the configuration, or via `--userdir <...>` - which is an incorrect, nonexistant direcory in the docker container.

**Comment by shalb2018** [comment]
Hi thank you for such fast reply!
I copied the code for two bots (docker-compose.yml) from here: https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade, changing only the strategy names. The rest I did not touch.

In the config.json the code line actually is: "user_data_dir": "/opt/freqtrade/user_data/", (I got that from some tutorial)
What must have to be the correct way? So: ./user_data/  ?

**Comment by xmatthias** [comment]
that'd be fine - but `/opt/freqtrade/user_data` will not work with docker (unless you mess with the volumes)

The default is to simply leave it unconfigured - which will default it to `/freqtrade/user_data`.
The way the image is setup, docker will mount the volume to that location.

**Comment by shalb2018** [comment]
Great, now it works. Thanks a lot!
