### ISSUE TITLE
Binance keeps small amounts in the wallet

### ISSUE THREAD

**Issue by zahngott** [freqtrade/freqtrade#6383]
Hello,

i just saw that if i am trading with the Bot, Biance keeps small amounts left in the Wallet. After 2 Days my wallet is full with these small amounts.

did i make a mistake ?
Regards

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.


---

Please read the [documentation](https://www.freqtrade.io/en/stable/faq/#why-does-my-bot-not-sell-everything-it-bought) before opening an issue. The FAQ entry linked explains your case exactly - and how to eventually mitigate it.

**Comment by zahngott** [comment]
wirklich sehr freundlich, danke….
