### ISSUE TITLE
OpenAPI endpoint returns empty page

### ISSUE THREAD

**Issue by sabatale** [freqtrade/freqtrade#6387]
## Describe your environment

  * Freqtrade Version: Latest
  * Environment: Docker latest
  
## Your question

Are there any static Swagger docs available or some logs I could look at to figure out why my /docs endpoint is not working? I'm trying to access /docs but the server returns "**404 Error.**" with the following config:

```
  "api_server": {
      "enabled": true,
      "listen_ip_address": "0.0.0.0",
      "listen_port": 8080,
      "verbosity": "error",
      "enable_openapi": true,
      "jwt_secret_key": "abc",
      "CORS_origins": ["http://localhost:8080", "http://127.0.0.1:8080", "http://localhost:8081", "http://127.0.0.1:8081"],
      "username": "abc",
      "password": "abc"
  }
```

I tried the rest_client.py instead (although I don't plan on using it) and it also seems to work only if I change the listen_ip_address to localhost in a separate config file:

{
  "api_server": {
    "enabled": true,
    "listen_ip_address": "localhost",
    "listen_port": 8080,
    "verbosity": "error",
    "enable_openapi": false,
     "jwt_secret_key": "abc",
    "CORS_origins": ["http://localhost:8080", "http://127.0.0.1:8080", "http://localhost:8081", "http://127.0.0.1:8081"],
     "username": "abc",
     "password": "abc"
  }
}

**Comment by xmatthias** [comment]
Swagger docs actually work fine for me (just used them yesterday).

can you maybe share some more information (like a screenshot where the URL as well as the network tab of the browser dev tools (f12) are visible) ? 
thanks

**Comment by sabatale** [comment]
I'm closing this since what I had in mind is overly complicated.

For reference, the URL is http://127.0.0.1:8080/docs and there are no errors in console logs.
