### ISSUE TITLE
Unlimited stake produces different profit results if run with the same strategy via `--strategy-list`

### ISSUE THREAD

**Issue by TheJoeSchr** [freqtrade/freqtrade#6388]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.10
  * CCXT version: unrelated
  * Freqtrade Version: develop
  

## Describe the problem:

Running the exact same strategy produces different results for total profit USD.

![image](https://user-images.githubusercontent.com/8218910/153464237-7ef8af5d-f40f-4922-ae4c-59d04d9aff80.png)

### Steps to reproduce:

  1. clone example `Strategy001` and name it `Strategy001_clone`
  3. create config using `"stake_amount": "unlimited", `
  3. run backtest with `--strategy-list Strategy001_clone Strategy001 --cache none`
  4. compare Total Profit USD columns
  
### Observed Results:

  * What happened?: Profits are not the same
  * What did you expect to happen? Profits being the same

### Relevant code exceptions or logs

I boiled it down to using different stake_amounts for each run.

This is the offending line, returning different values for `max_stake_amount`:
https://github.com/freqtrade/freqtrade/blob/af984bdc0d1c2dee3e88b7d3ea28bdb1a2a65b56/freqtrade/optimize/backtesting.py#L526-L527

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```python

# optimize/backtesting/_enter_trade()
        min_stake_amount = self.exchange.get_min_pair_stake_amount(pair, propose_rate, -0.05) or 0
        max_stake_amount = self.wallets.get_available_stake_amount()

        pos_adjust = trade is not None
  ```

**Comment by TheJoeSchr** [comment]
Example config with which to reproduce:

```json
{
    "unfilledtimeout": {
        "buy": 45,
        "sell": 30
    },
  "max_open_trades": 20,
  "stake_currency": "USDT",
  "dry_run_wallet": 10000,
  "stake_amount": "unlimited",
  "tradable_balance_ratio": 0.99,
  "fiat_display_currency": "USD",
  "dry_run": true,
  "pairlists": [{ "method": "StaticPairList" }],
  "exchange": {
    "ccxt_config": { "enableRateLimit": true },
    "ccxt_async_config": {
      "enableRateLimit": true,
      "rateLimit": 500,
      "aiohttp_trust_env": false
    },
    "name": "binance",
    "pair_whitelist": [
      ".*UP/USDT",
      ".*DOWN/USDT",
      "BTC/USDT",
      "ETH/USDT",
      "ADA/USDT",
      "LINK/USDT",
      "BNB/USDT",
      "XTZ/USDT",
      "EOS/USDT",
      "TRX/USDT",
      "XRP/USDT",
      "DOT/USDT",
      "LTC/USDT",
      "UNI/USDT",
      "SXP/USDT",
      "FIL/USDT",
      "YFI/USDT",
      "BCH/USDT",
      "AAVE/USDT",
      "SUSHI/USDT",
      "XLM/USDT",
      "1INCH/USDT"
    ],
    "pair_blacklist": []
  },
  "dataformat_ohlcv": "hdf5",
  "dataformat_trades": "hdf5"
}
```

**Comment by xmatthias** [comment]
Thanks for reporting - will be fixed with the next commit.
