### ISSUE TITLE
On `/forcebuy`, the pairlist in Telegram can be improved

### ISSUE THREAD

**Issue by Heistergand** [freqtrade/freqtrade#6389]
### Environment
  * Freqtrade Version: docker-b6943f3b

# Enhancement
When using a Volumepairlist or a long whitelist, the handling of the /forcebuy command in Telegram gets unhandy. 
- The list is long
- it is not sorted
- it has no cancel option.

## The list is long
- [x] use pagination.
*We could provide the List of InlineKeyboardButtons as a dynamic paged list, where the user sees e.g. 9 buttons with pairs and two additional buttons to flip the pages. 
This is an improvement because it increases the user experience.*

## The list is not sorted
- [x] sort the list
*This is an improvement because users tend to find things in sorted lists faster.*

## The `/forcebuy` command lacks a cancel option.
- [x] add a cancel button to the end of the list, e.g. between the page flipping buttons (see above)
*This is an improvement, because when you want to forcebuy a specific pair but it turns out the that pair is filtered out by the Volumepairlist, you might want to abort the attempt to force a buy. But the Buttons will remain in Telegram and the bot will internally keep a reference to that unanswered message open. One could accidentally touch a button e.g. while scrolling through old messages and instantaneous trigger a forcebuy.*

**Comment by xmatthias** [comment]
the use of pagination will not make UX better, but worse - as you'll now need way more clicks to get to what you need.
A 9 element pagination will take me 5+ "tabs" to get to XRP/USDT on a 50 pair whitelist - so this is not something i'd consider adding.

Sorting might be an option for sure - but in the end, this display is just a helper in case you forget to pass in the pair, so i don't plan on spending too much time on this (freqtrade's main purpose is algo trading, not manual trading).


if you know what pair you're buying, using `/forcebuy XRP/USDT` will get you faster to your goal than `/forcebuy` and then paginating to the last page to find XRP (assuming a sorted, paginated list).

This syntax also supports additional arguments with price `/forcebuy XRP/USDT 0.5` (which obviously only applies if you're using limit orders).

**Comment by Heistergand** [comment]
I have to disagree.

The long syntax is just not meant to be the scope of this feature request. The scope of this feature request is all about improving *the buttons* for *manual trading*. I understand it has no priority though. Using the full syntax is indeed a fast way as long as you're sitting in front of a keyboard and not being on the go using the bot on your smartphone. 

That said, pagination or maybe cascading *will* improve the UX. You can get over 30-40 pairs or more - that should be accessible without scrolling. You can also cascade the menu via alphabetical clusters like e.g. `[a-h][i-n][o-s][t-z]`. UX is not decreasing by counts of clicking/tapping but by opportunities to make errors. 

More importantly, *if* using the buttons, there should be a cancel button.

**Comment by xmatthias** [comment]
you can just ignore the message - which acts as a cancel button.
there's no explicit cancel - but is that really a problem?

**Comment by Heistergand** [comment]
Yes, it is, like I already pictured. Ignoring the message will technically leave a hook open at side of the bot and when you're scrolling up to older messages - which users actually do now and then - it is possible that you accidently push a button in the pairs list which then immediately would cause a force-buy even if the message was already days old. It is a dead-end in user guidance and simply not state of the art. 

I also don't understand why you're closing the ticket? Leave it open for years, there's no need to close it: _you can just ignore it_, can't you?

**Comment by xmatthias** [comment]
If you look at the commit that closed this ticket, then you'd notice that the latest develop version does now have a cancel button, as well as a sorted pairlist.

We'll not be adding pagination - so there's little point in leaving this ticket open, as the other 2 points that were mentioned have been closed.

> I also don't understand why you're closing the ticket? Leave it open for years, there's no need to close it: _you can just ignore it_, can't you?

I could - but there's no point.
aving many tickets open makes it difficult for both experienced and new contributors to find things/issues that still need doing. This is especially true for tickets that have been solved - like this one.

**Comment by Heistergand** [comment]
Oh. I apologize. I've read the thread as "_there's no explicit cancel_" -> _closing ticket with no action_

I was wrong, sorry.

**Comment by xmatthias** [comment]
Comments don't always align with actions 😆 (sorry for that - but i know already it'll happen again in other tickets).

that's for sure not ideal, but i've looked at the sorting part, and figured that an additional cancel button won't hurt - but then forgot to comment - in the end however i think the outcome is the "Important" part - not the comment
