### ISSUE TITLE
How to get DAY OPEN HIGH CLOSE LOW IN TIMEFRAME

### ISSUE THREAD

**Issue by lovehedy24** [freqtrade/freqtrade#6390]
**## Describe your environment**

  Freqtrade Version: Latest
  Environment: Docker latest
  
**## Your question**

Hello 

if I want design a function(name Filter_MY_V3) 
that wants to optimize the pattern vars

Strategy run timeframe is H1(or any time frame)
How to get DAY OPEN HIGH CLOSE LOW?

opend0= dtatframe['open'].shift(0)
opend1=  dtatframe['open'].shift(1) 
opend2= 
opend3=     
 
def Filter_MY_V3(pattern):
    if pattern==1:
	
        ret=opend0>opend1
    
	if pattern==2:

        ret=opend0>opend2

    if pattern==3:

        ret=opend0>opend3

    if pattern==4:

        ret=opend0>opend4

    if pattern==5:
      ret=opend0>opend5 

    return ret

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

Your most reliable bet is probably using the [informative](https://www.freqtrade.io/en/latest/strategy-customization/#informative-pairs-decorator-informative) approach - where you can request 1d candles to get the prior day's candle (it'll always be the last candle in the dataframe).

While you can in theory use some odd logic to get to 1d candles from 1h candles - it's most often a rolling approach - so it'll not be 00:00-00:00 - but "-24h-now".

**Comment by lovehedy24** [comment]
> 

sorry i already edit the post
thanks you

**Comment by lovehedy24** [comment]
> Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment. We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.
> 
> Your most reliable bet is probably using the [informative](https://www.freqtrade.io/en/latest/strategy-customization/#informative-pairs-decorator-informative) approach - where you can request 1d candles to get the prior day's candle (it'll always be the last candle in the dataframe).
> 
> While you can in theory use some odd logic to get to 1d candles from 1h candles - it's most often a rolling approach - so it'll not be 00:00-00:00 - but "-24h-now".

HI 
Still don't know how to write
opend0=?

**Comment by xmatthias** [comment]
something like `dataframe['date'].dt.hour == 0` might work (assuming you're on 1h candles)...

i'd however strongly advise against regular `if` statements, as also explained [in the documentation](https://www.freqtrade.io/en/latest/strategy-customization/#dataframe).
They tend to break backtesting support unless you use them only in callbacks.

**Comment by lovehedy24** [comment]
> something like `dataframe['date'].dt.hour == 0` might work (assuming you're on 1h candles)...
> 
> i'd however strongly advise against regular `if` statements, as also explained [in the documentation](https://www.freqtrade.io/en/latest/strategy-customization/#dataframe). They tend to break backtesting support unless you use them only in callbacks.

HI xmatthias
Maybe I didn't express clearly
I want to get the daily open high and low close in 1h(or 30min)

see https://www.freqtrade.io/en/latest/strategy-customization/#informative-pairs-decorator-informative
use merge_informative_pair function?

**Comment by xmatthias** [comment]
You can use informative pair - or you can also use the filter posted above.

Please understand that i'll not write the strategy for you - but with the help given above you will get to the candle at 00:00 - from there it's just a matter of retrieving the prices you need.

**Comment by lovehedy24** [comment]
> You can use informative pair - or you can also use the filter posted above.
> 
> Please understand that i'll not write the strategy for you - but with the help given above you will get to the candle at 00:00 - from there it's just a matter of retrieving the prices you need.

thanks your help :)
I will try it
