### ISSUE TITLE
Get open trades in the database don't return open trades

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#6395]
## Describe your environment

Freqtrade docker image
Version : docker-08803524

## Describe the problem:

`Trade.get_trades([Trade.is_open is True]).all()` seems not at give the list of open trades (seems like a breaking change between change version as i use the code is previous versions)

### Steps to reproduce:

```
 if self.dp and self.dp.runmode.value in ('live', 'dry_run'):
     trades = Trade.get_trades([Trade.is_open is True]).all()
     for trade in trades:
          logger.info('current open trade pair is : '+trade.pair)

```
  
### Observed Results:

 trades object is empty

Have a nice day.

**Comment by xmatthias** [comment]
`Trade.is_open is True` is invalid syntax for an sqlalchemy query iirc (and always has been ... even though it may have worked "accidentally" in some older versions of sqlalchemy).

It MAY work on some database backends (or may have worked in older versions) - the correct way to query a boolean field is with `Trade.get_trades([Trade.is_open.is_(True)])`.

**Comment by gaugau3000** [comment]
@xmatthias many tks (my bad) !
