### ISSUE TITLE
Partial sell in DCA

### ISSUE THREAD

**Issue by SmartManoj** [freqtrade/freqtrade#6413]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

As it is in todo, the feature will be implemented like the following?

If we sell the last rebuy, the profit is subtracted from the previous buy total and new open price will be calculated from that and for the first buy.

**Comment by xmatthias** [comment]
Currently partial selling through DCA is not supported, and it's also not actively developed as far as i know.

As such - it is too early to communicate detail information as the above, but we will obviously make sure that profit calculations still align (probably by splitting the profit into "realized" and "unrealized" profit).

Also, please don't expect work on this in the immediate future, as it's currently pretty low on the priority list.

For further updates, please refer to the original DCA ticket (#1519) - which was only filled partially with the addition of DCA buys.
