### ISSUE TITLE
populate_buy_trend is called around 10 times for same pair / tick

### ISSUE THREAD

**Issue by 010011x** [freqtrade/freqtrade#6415]
## Describe your environment

  * Operating system: Ubuntu 20.04.3 LTS
  * Python Version: Python 3.8.10
  * CCXT version: ccxt==1.71.20
  * Freqtrade Version: freqtrade develop-e7409e74
  
## Your question

My strategy is using binance (which has ohlcv_candle_limit: 1000).
My strategy has startup_candle_count set to 730.
timeframe is 15m.

When buy order is happening, I can see via logs that populate_buy_trend is called about 10 times for the same pair / time. Why is this happening ?

**Comment by xmatthias** [comment]
all `populate_*trend` methods are called once per iteration (which is roughly every 5s with default settings).

You can change this by setting `process_only_new_candles` to true [documented in the parameters list](https://www.freqtrade.io/en/latest/configuration/#configuration-parameters) - then all populate_*_trend methods will only be called once per candle.

This is usually fine - but can be unexpected if you're using live exchange data (like orderbook data).
