### ISSUE TITLE
Take profit target is not working

### ISSUE THREAD

**Issue by ryhnm** [freqtrade/freqtrade#6419]
## Describe your environment

  * Operating system: macOS Monterey 12.2
  * Python Version: 3.9.7
  * CCXT version: 1.72.98
  * Freqtrade Version: 2022.1

## Describe the problem:

I have used the `custom_stoploss` function to set a static stoploss at an absolute price based on an indicator and a take profit at a fixed 1.5 risk to reward ratio. In 90% of the trades the stoploss and take profit work perfect, however sometimes the take profit does not get triggered even though the price has moved past that target. 

## This is my custom_stoploss function
```
def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime, current_rate: float, current_profit: float, *kwargs) -> float:
        #Start at next second candle to let prices stabilise
        if current_time - datetime.timedelta(minutes=60) > trade.open_dateutc:

            # Obtain pair dataframe.
            dataframe,  = self.dp.get_analyzed_dataframe(pair, self.timeframe)

            # In dry/live runs trade open date will not match candle open date therefore it must be rounded
            trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
            trade_candle = dataframe.loc[dataframe['date'] == trade_date]

            if not trade_candle.empty:

                # Get stoploss price of the trade candle
                stoploss_price = trade_candle['stoploss_price'].iloc[0]

                # Get risk and reward distances
                risk_distance = trade.open_rate-stoploss_price
                reward_distance = risk_distance*1.5

                # Calculate absolute and percentage profits
                take_profit_price_abs = trade.open_rate+reward_distance
                take_profit_pct = take_profit_price_abs/trade.open_rate-1

                # Return takeprofit target if current profit higher than takeprofit
                if (current_profit >= take_profit_pct):
                    takeprofit_sl = take_profit_price_abs/current_rate-1
                    return takeprofit_sl

                # Else return stoploss
                return (stoploss_price / current_rate) - 1
        # If first candle has not formed return original stoploss
        return 1
```
  
### Observed Results:

The first image shows that the stoploss is set at 28642.149 and the take profit is set at 35355.775. The second image shows that the price went beyond that price target of 35355.775 but did not sell until 6 months later. The third image shows another example where this happened.

<img width="460" alt="Screen Shot 2022-02-15 at 11 32 30 AM" src="https://user-images.githubusercontent.com/99715402/154014033-748cab8e-f4d5-41b0-9246-e323b032b8d8.png">

<img width="1348" alt="Screen Shot 2022-02-15 at 11 42 59 AM" src="https://user-images.githubusercontent.com/99715402/154015446-927fc6c0-1a38-469d-9eed-4e33961ff9ed.png">

<img width="429" alt="Screen Shot 2022-02-15 at 11 45 31 AM" src="https://user-images.githubusercontent.com/99715402/154015778-8d08c4e0-bc46-4618-9638-0d73a7f1fe89.png">

**Comment by xmatthias** [comment]
You're in `custom_stoploss` - the return value will be the relative value below the current price.

Even if you are returning a positive number, it's still a stoploss. Freqtrade will assume you made a mistake and invert the sign.
As such, a stop is always below current price.

Your 2nd picture is missing the axis - so it's difficult to tell where the assumed "take-profit" price is
however, custom-stoploss is not designed to act as take profit - it'll sell when price returns to that level, not when it reaches some assumed level above current price.
 
from the 2nd picture, it appears that that's what happened (assuming your "take-profit" logic triggered in the middle of the long green candles). It's selling the moment price returns to the level you set your stoploss to.

**Comment by ryhnm** [comment]
I see, thank you for your fast response Matthias. How would I go about doing this the correct way? I.e. setting a static stoploss based on an indicator as well as a fixed risk to reward take profit target?

**Comment by xmatthias** [comment]
Don't mix the two?

You can use [custom sell signal](https://www.freqtrade.io/en/latest/strategy-callbacks/#custom-sell-signal) for this - where the strategy decides "sell now".

Alternatively, you can use a different (closer) stop to trail price once your take-profit is reached. That way you're not limiting yourself from further profits.
Your mistake here is that your stoploss remains static (it remains at price X) - where it should either be pulled closer (to 1% or so) and trail price at 1% - or forced to sell immediately (don't abuse stoploss for this - it may work but can also fail).

**Comment by ryhnm** [comment]
Thanks, I used your second alternative which works perfectly! Once the price reaches take profit the stoploss moves just below the take profit target. One final question however, if the price moves to take profit and suddenly dips, it could happen that the stoploss did not get filled and the trade is then suddenly without a stoploss. 

What would be the best way to integrate an 'emergency sell' (where the trade is immediately sold against market price) in the case the price goes to take profit and then crashes down past the stoploss without it getting filled?

**Comment by xmatthias** [comment]
In general, i'd recommend using stoploss-on-exchange if we support that for your exchange.

Should the stop fail to be placed (e.g. price dips exactly while we're adjusting the stop) - it'll trigger an emergency sell.
I'd however not use it with a stop-margin < 1% - otherwise emergency-sells will take over as in many pairs, moves of 0.5% happen in seconds ...

**Comment by ryhnm** [comment]
So just for my understand, with the aforementioned stoploss approach and the following config settings:

`order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'emergencysell': 'market',
        'stoploss': 'market',
        'stoploss_on_exchange': True,
        'stoploss_on_exchange_interval': 60,
        'stoploss_on_exchange_limit_ratio': 0.99
    }`,

in case a trade hits the stoploss, it will sell against market. In case a trade hits take profit, the stoploss moves to just below take profit and sells once the price dips back through this new stoploss/take profit target. In case the price dips exactly when the stop is being adjusted, the 'emergencysell' is triggered and the trade is sold immediately.

Is this all correct or is there anything I should change to make sure the strategy behaves like the 3 aforementioned cases? Thanks in advance, really appreciate the help!

**Comment by xmatthias** [comment]
it sounds correct like this.
one note:
not many exchanges support stoploss-market orders - so the stoploss will most likely be a stoploss-limit (assuming binance).
In that case, `stoploss_on_exchange_limit_ratio` becomes relevant, which defines how much below the stoploss the limit order is placed. the default is 1% - which in very sudden dips, can be problematic.

**Comment by quents** [comment]
Hello @ryhnm, if you have time, can you please share the final code snippet where you implemented trailing stoploss when profit is reached?

**Comment by stash86** [comment]
luckily it's available in the documentation
https://www.freqtrade.io/en/latest/strategy-callbacks/#custom-stoploss

Try reading the whole documentation. Helps in your money-making journey
