### ISSUE TITLE
Backtesting ignoring experimental flags

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#642]
## Step 1: Have you search for this issue before posting it?
yes

## Step 2: Describe your environment

  * Python Version: Python 3.6.5 (`python -V`)
  * Branch: Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
 
## Step 3: Describe the problem:
Changing one of the experimental flags (`sell_profit_only`, `use_sell_signal`) does not change the result. The flags are read from the config in [backtesting.py:L254-L255](https://github.com/gcarq/freqtrade/blob/develop/freqtrade/optimize/backtesting.py#L254-L255) - but not utilized after.

### Steps to reproduce:

  1. Run backtesting
  2. change one or both experimental flags
  3. run backtesting again
  
### Observed Results:

  * What happened?
    * Results did not change
  * What did you expect to happen?
    * Different results depending on the experimental flags

**Comment by timhilliard** [comment]
Looks like this line is mean to check if buy signal is true (which the comment above mentions) but never actually checks.

**Comment by xmatthias** [comment]
Closing as i just found out that experimental flags are evaluated.

**Comment by pnmartinez** [comment]
Hello @xmatthias, having a similar problem here in the far future of 2020.

It seems to me that `sell_profit_only` is not used in the backtesting, as I am getting negatives (even very negative, `stop_loss` forced sells).

Can you elaborate a bit about what you found out?

**Comment by xmatthias** [comment]
the flags are used correctly - but sell_profit_only only applies to sell_signal - but NEVER to stoploss (that would be a severe bug).

Please open a new issue if this does not answer your question.
