### ISSUE TITLE
Add alerts on telegram based on trade's condition

### ISSUE THREAD

**Issue by StephaneMangin** [freqtrade/freqtrade#6433]
## Describe your environment
(if applicable)

  * Operating system: ____ Debian
  * Python Version: _____ freqtrade standard
  * CCXT version: _____ freqtrade standard
  * Freqtrade Version: ____ latest version

## Describe the enhancement
I face sometimes the need to override the bot in certain cases (on binance which does not sell when profit is acceptable and especially on kucoin which sold too much quickly once positive profit is reach). I mean, not waiting to sell a trade in a certain situation or waiting a little bit much longer depending of the situation.
For this i need to go regularly on the interface or telegram to know where are the trade state (positive or negative).
I suggest to include the ability to have alerts for certain conditions (in this case when trade comes from negative to positive)
Should it be a good functionnality for you or just a specific and custom need from myself ?

It could be text based as the hold function does to avoid too much development i think.

Thanx for this wonderfull open work @xmatthias ! Worth it so much !!!

**Comment by xmatthias** [comment]
I think this is very specific to your needs, and i don't think it will scale to others (neither do i think it's a good functionality overall, as the need for "i need this in this very specific case" will make it too difficult to actually configure).


You'll discover that you will end up spamming yourself quite regularly.
price can (and will) fluctuate between 2 values eventually 100ds of times, if you get a notification each time you'll soon discover that this is not a good approach.
As it would however be your custom rule, freqtrade would not be able to determine to "not send this notification" - therefore you'll get all 100 notifications - without any actual information gain as you'll have turned this functionality off after the 10th notification.

**Comment by StephaneMangin** [comment]
I understand this point of course, thanx. I think i can forget this idea then.
