### ISSUE TITLE
Disabling populate_sell_trend() fills less buys

### ISSUE THREAD

**Issue by dantokem** [freqtrade/freqtrade#6438]
## Describe your environment

  * Operating system: macOS 11.6
  * Python Version: 3.9.10
  * CCXT version: 1.71.73
  * Freqtrade Version: 2022.1
  
## Your question

Playing around with the Scalp strategy from https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/strategies/berlinguyinca/Scalp.py

When I disable selling in populate_sell_trend() with assigning 0 instead of 1 only about half of the buy signals get filled in backtesting during a period of around three months. How can this be? Report shows for 'Left open trades report' 0, 'Max open trades' 1

Thanks!
[config.json.txt](https://github.com/freqtrade/freqtrade/files/8104399/config.json.txt)
[backtesting report.txt](https://github.com/freqtrade/freqtrade/files/8104397/backtesting.report.txt)

**Comment by xmatthias** [comment]
you need to differentiate - it's not "half buy signals get filled" - but "fewer trades happen".

This is expected if you consider that the average trade duration changes from 30m to 11h. (considering this difference, it's actually surprising that you still get this many trades).

When a trade for a pair is already open, subsequent buy signals for this pair will be ignored until the trade is closed.

**Comment by dantokem** [comment]
Huh completely missed this, makes all sense. Thank you very much for your help and answering so diligently all questions here, great service to the community!
