### ISSUE TITLE
How to get traded candle in custom_sell()?

### ISSUE THREAD

**Issue by fridary** [freqtrade/freqtrade#6450]
* Operating system: Mac OS
  * Python Version: 3.8.12
  * CCXT version: 1.67.31
  * Freqtrade Version: 2022.1
  
How to get candle that was when we entered trade? This is needed to check additional information for exiting trade.
```
def custom_sell(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, **kwargs):
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = dataframe.iloc[-1].squeeze()
        trade_candle = dataframe.loc[dataframe['date'] == trade.open_date_utc].squeeze()
```
The problem is it works on backtest, but during live trade I get empty `trade_candle`.

**Comment by fridary** [comment]
This works
```
dataframe.set_index('date', inplace=True)
trade_candle = dataframe.iloc[dataframe.index.get_loc(trade.open_date_utc, method='ffill')]
```

**Comment by xmatthias** [comment]
We have a better method (from an efficiency perspective) for this in the [advanced strategy documentation](https://www.freqtrade.io/en/stable/strategy-advanced/#dataframe-access) - by rounding the entry date to the correct candle.
