### ISSUE TITLE
How to compare pairs between themselves (ranking for instance) based on specific indicator ? 

### ISSUE THREAD

**Issue by celec29** [freqtrade/freqtrade#6452]
I am relatively new to freqtrade and my idea is to use the price change in percentage as indicator to rank the pairs relative to each other. 
In a first step, I compute the desired indicator (rocp) from a list of informative pairs.
In a second step, I would like to rank the pairs relative to each other. I tried informative_p['rank'] = stats.zscore(informative_p['rocp'][1:]), however I am not sure this is comparing pairs between themselves. 
It seems that freqtrade allows to trade assets based on their time-series data (directional movement) and independently from each other.

Many thanks for your help and comments. 
ps: my question can be related to an old one (#4011) but I couldn't figure out the right solution from the that discussion.

def informative_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame: 
        assert self.dp, "DataProvider is required for multiple timeframes."
        
        # Get the informative pair
        informative_p = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=self.info_timeframe)
        # ROCP indicator
        informative_p['rocp'] = ta.ROCP(informative_p, timeperiod=1)

        return informative_p

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

you can get the full pairlist via dataprovider - so you can just load the informative pair for all of them and then compare based on that (maybe use `bot_loop_start()` for that).

Freqtrade itself does currently not allow the strategy to rank or modify the pairlist - so you'll have to take the decision in the strategy if a buy signal should be issued for this pair or not.

**Comment by celec29** [comment]
Thanks for your comments. I will try to make this work. Will be careful with issue template.
