### ISSUE TITLE
TA_EMA function failed with error code 2: Bad Parameter (TA_BAD_PARAM)

### ISSUE THREAD

**Issue by mert-donmez** [freqtrade/freqtrade#6454]
## Describe your environment

  * Operating system: Ubuntu 20.04 LTS
  * Python Version:  3.8.10
  * CCXT version:  1.72.29
  * Freqtrade Version: freqtrade develop
  
## Your question

`df[value_]=ta.EMA(df , length)`
I calculate value_ by giving value to the length, but when I give the 1, I get the error in the title
There is no problem when I give a value greater than 2 but i have to give 1

error log:
```
File "/home/root_ubuntu/Desktop/freqtrade-feat-short/user_data/strategies/moststratejiSon.py", line 87, in MOST
    df[mavalue]=ta.EMA(df , length)
  File "talib/_abstract.pxi", line 427, in talib._ta_lib.Function.__call__
  File "talib/_abstract.pxi", line 472, in talib._ta_lib.Function.__call_function
  File "/home/root_ubuntu/Desktop/freqtrade-feat-short/.env/lib/python3.8/site-packages/talib/__init__.py", line 64, in wrapper
    result = func(*_args, **_kwds)
  File "talib/_func.pxi", line 2936, in talib._ta_lib.EMA
  File "talib/_common.pxi", line 47, in talib._ta_lib._ta_check_success
Exception: TA_EMA function failed with error code 2: Bad Parameter (TA_BAD_PARAM)
```

**Comment by stash86** [comment]
You do know what EMA stands for right? Exponential Moving Average. By Average, it means you need to give it more than 1 data. If you want to give it length = 1, then what average do you want it to calculate?

Length = 1 is equal to no average at all, so I'm not sure what do you want to do with it

**Comment by mert-donmez** [comment]
> 



> You do know what EMA stands for right? Exponential Moving Average. By Average, it means you need to give it more than 1 data. If you want to give it length = 1, then what average do you want it to calculate?
> 
> Length = 1 is equal to no average at all, so I'm not sure what do you want to do with it

you are right but it can be set to 1 in tradingview or binance chart. I was working on a strategy for someone, he gave me the parameters. The indicator works in tradingview with the given parameters. 

I just don't know how to make a strategy with these parameters, he said it's good. All i know is making a precision strategy that will work on that 1 minute chart

**Comment by stash86** [comment]
TV and Binance app won't complain because its users will be from all sorts of profession. So non-programmer/non-TA-savvy users might not understand why length=1 is wrong. And if you see the line drawn, they are just a line connecting the close of each candles, which like what I said.

**Comment by mert-donmez** [comment]
Thanks for reply now i understand

By the way this indicator is used for trending and giving the length 1 or 2 changes a lot because there will be other indicators working with this indicator.
And now i will deal with minimizing this change
```
def MOST(dataframe,  percent, length, MAtype=1):
    import talib.abstract as ta
    df = dataframe.copy()
    mostvalue = 'MOST_' + str(length) + '_' + str(percent)
    mavalue = 'MA_' + str(length) + '_' + str(percent)
    trend = 'Trend_' + str(length) + '_' + str(percent)
    # Compute basic upper and lower bands
    if MAtype==1:
        df[mavalue]=ta.EMA(df , timeperiod = length)
    elif MAtype==2:
        df[mavalue]=ta.DEMA(df , timeperiod = length)
    elif MAtype==3:
        df[mavalue]=ta.T3(df , timeperiod = length)
    df['basic_ub'] = df[mavalue] * (1+percent/100)
    df['basic_lb'] = df[mavalue] * (1-percent/100)
    # Compute final upper and lower bands
    df['final_ub'] = 0.00
    df['final_lb'] = 0.00
    for i in range(length, len(df)):
        df['final_ub'].iat[i] = df['basic_ub'].iat[i] if df['basic_ub'].iat[i] < df['final_ub'].iat[i - 1] or df[mavalue].iat[i - 1] > df['final_ub'].iat[i - 1] else df['final_ub'].iat[i - 1]
        df['final_lb'].iat[i] = df['basic_lb'].iat[i] if df['basic_lb'].iat[i] > df['final_lb'].iat[i - 1] or df[mavalue].iat[i - 1] < df['final_lb'].iat[i - 1] else df['final_lb'].iat[i - 1]
    # Set the MOST value
    df[mostvalue] = 0.00
    for i in range(length, len(df)):
        df[mostvalue].iat[i] = df['final_ub'].iat[i] if df[mostvalue].iat[i - 1] == df['final_ub'].iat[i - 1] and df[mavalue].iat[i] <= df['final_ub'].iat[i] else \
                        df['final_lb'].iat[i] if df[mostvalue].iat[i - 1] == df['final_ub'].iat[i - 1] and df[mavalue].iat[i] >  df['final_ub'].iat[i] else \
                        df['final_lb'].iat[i] if df[mostvalue].iat[i - 1] == df['final_lb'].iat[i - 1] and df[mavalue].iat[i] >= df['final_lb'].iat[i] else \
                        df['final_ub'].iat[i] if df[mostvalue].iat[i - 1] == df['final_lb'].iat[i - 1] and df[mavalue].iat[i] <  df['final_lb'].iat[i] else 0.00
    # Mark the trend direction up/down
    df[trend] = np.where((df[mostvalue] > 0.00), np.where((df[mavalue] < df[mostvalue]), 'down',  'up'), np.NaN)
    # Remove basic and final bands from the columns
    df.drop(['basic_ub', 'basic_lb', 'final_ub', 'final_lb'], inplace=True, axis=1)
    df.fillna(0, inplace=True)
    return df
```
