### ISSUE TITLE
Emergency sell failed, with previous sell order is partially filled

### ISSUE THREAD

**Issue by popperwin** [freqtrade/freqtrade#6457]
## Describe your environment

  * Operating system: `Ubuntu 18.04.03`
  * Python Version: `3.8.8` (`python -V`)
  * CCXT version: `1.61.92` (`pip freeze | grep ccxt`)
  * Freqtrade Version: `2022.1` (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  * Exchange: `kucoin`
  

## Describe the problem:

*Explain the problem you have encountered*

I had an emergency sell failure, and it seems like it's because the previous sell order have been only partially executed.
The log reports this line: `WARNING - Unable to emergency sell trade BASIC/USDT: Not enough amount to sell. Trade-amount: 3254.21, Wallet: 2.953e-05` .

Here are the logs showing the steps leading to the error : 

  1. Sell with a limit price: `2022-02-24 20:21:14,075 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell, 'trade_id': 256, 'exchange': 'Kucoin', 'pair': 'BASIC/USDT', 'gain': 'profit', 'limit': 0.00404, 'order_type': 'limit', 'amount': 3254.21, 'open_rate': 0.003933618028338675, 'close_rate': None, 'current_rate': 0.00404, 'profit_amount': 0.29429362, 'profit_ratio': 0.02294433, 'buy_tag': None, 'sell_reason': 'sell_signal', 'open_date': datetime.datetime(2022, 2, 24, 17, 31, 18, 87721), 'close_date': datetime.datetime(2022, 2, 24, 19, 21, 14, 75044), 'stake_currency': 'USDT', 'fiat_currency': 'USD'}` 

  2. Watch the sell order been partially filled:`2022-02-24 20:26:19,728 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell_cancel, 'trade_id': 256, 'exchange': 'Kucoin', 'pair': 'BASIC/USDT', 'gain': 'profit', 'limit': 0.00404, 'order_type': 'limit', 'amount': 3254.21, 'open_rate': 0.003933618028338675, 'current_rate': 0.00404, 'profit_amount': 0.29429362, 'profit_ratio': 0.02294433, 'buy_tag': None, 'sell_reason': 'sell_signal', 'open_date': datetime.datetime(2022, 2, 24, 17, 31, 18, 87721), 'close_date': datetime.datetime(2022, 2, 24, 19, 26, 19, 728272, tzinfo=datetime.timezone.utc), 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'reason': 'partially filled - keeping order open'}`

  3. Emergency sell order is triggered: `2022-02-24 20:26:19,850 - freqtrade.freqtradebot - WARNING - Emergencyselling trade Trade(id=256, pair=BASIC/USDT, amount=3254.21000000, open_rate=0.00393362, open_since=2022-02-24 17:31:18), as the sell order timed out 1 times.`

  4. Emergency order fails: `2022-02-24 20:26:20,063 - freqtrade.freqtradebot - WARNING - Unable to emergency sell trade BASIC/USDT: Not enough amount to sell. Trade-amount: 3254.21, Wallet: 2.953e-05`

When this happened, I checked my account on Kucoin and I saw that the limit sell order was still opened for the amount 3254.21 . So I presume that's why the emergency sell failed.  
If I'm right and this is the reason, it means that the `sell_cancel` message failed. Is this possible, or is it because I misconfigured emergency sell mechanism? Here is what I used as conf:

```
"unfilledtimeout": {
        "buy": 60,
        "sell": 5,
        "unit": "minutes",
        "exit_timeout_count": 1
    },
    "order_time_in_force": {
        "buy": "gtc",
        "sell": "gtc"
    }
```

Thanks in advance for your help !

### Steps to reproduce:

  1. Enable emergency sell by setting `"exit_timeout_count": 1`  in the conf
  2. Sell with a limit order which will be partially filled
  2. Have the order partially filled
  3. Emergency sell fails
  
### Observed Results:

  * What happened? Emergency sell failed.
  * What did you expect to happen? Emergency sell succeed.

**Comment by xmatthias** [comment]
The message in 2 is quite clear - `partially filled - keeping order open`.

So freqtrade didn't cancel (and didn't intend to cancel) the order, either.

It appears to be an edge-case (cancel rejected - but maximum timeout reached) - which apparently no-one encountered so far. 
I'll need to have a look why this happens - but i don't think it'll be difficult to fix.

**Comment by popperwin** [comment]
Indeed, now that you say it, the message in 2 is pretty obvious. 
I hope you'll be able to fix it then.
If it happens again I'll post it in this issue.

Thanks again , I am really impressed with your ability to respond to all issues so quickly.

**Comment by xmatthias** [comment]
should be good now with the latest develop.
it'll however not be included in the next release (2022.2) - as it's too close to release to include it (and it's a rare edge-case - so it might not happen for another month).

**Comment by popperwin** [comment]
Wow you're so quick. Thanks!

**Comment by popperwin** [comment]
Hi @xmatthias 
I've patch the code using the commit but now the emergency sell is not triggered.
Here is what I have in the log:
` Sending rpc message: {'type': sell_cancel, 'trade_id': 270, 'exchange': 'Kucoin', 'pair': 'FLAME/USDT', 'gain': 'profit', 'limit': 0.304, 'order_type': 'limit', 'amount': 1140.0468, 'open_rate': 0.2927, 'current_rate': 0.304, 'profit_amount': 11.52199699, 'profit_ratio': 0.03445995, 'buy_tag': None, 'sell_reason': 'sell_signal', 'open_date': datetime.datetime(2022, 3, 1, 17, 25, 40, 679328), 'close_date': datetime.datetime(2022, 3, 1, 21, 56, 36, 65390, tzinfo=datetime.timezone.utc), 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'reason': 'partially filled - keeping order open'}` 

And in Telegram I have this notification:
`⚠ Kucoin: Cancelling open sell Order for FLAME/USDT (#270). Reason: partially filled - keeping order open.`

**Comment by xmatthias** [comment]
this is correct / expected behaviour for the moment.
Your sell-order filled partially. 
This is something that's currently not implemented - therefore freqtrade is keeping the order open (it's more complicated than just canceling the order and placing a new one as we need to properly keep track of profits, ... ).
There's a TODO in the corresponding line (see below) - it's been there since quite some time - as this handling is quite complex to get right - and the gain it'll bring is not that high (this can usually be worked around by using a different pricing strategy).

https://github.com/freqtrade/freqtrade/blob/b18256c231da99f36593bb5b09498dd370e45ede/freqtrade/freqtradebot.py#L1113

**Comment by popperwin** [comment]
Oh ok I understand, that's too bad.  I should have paid more attention to the commit name, it's pretty clear that was the expected behavior when I read it. 

As I trade a lot of shitecoins, I prefer to avoid market orders, I've already had bad surprises using it. But my current pricing strategy is pretty flexible I think:

```
"bid_strategy": {
    "price_side": "ask",
    "ask_last_balance": 0.0,
    "use_order_book": true,
    "order_book_top": 2,
    "check_depth_of_market": {
        "enabled": false,
        "bids_to_ask_delta": 1
    }
},
"ask_strategy": {
    "price_side": "bid",
    "use_order_book": true,
    "order_book_top": 3
}
```

From your experience, do you recommend a better pricing strategy that can limit spread and slippage?

**Comment by xmatthias** [comment]
well you can always increase the "top" part ... but based on the config, almost all orders should fill pretty much immediately.

Market orders are a bad idea in general.

You can simulate market order behaviour with limit orders by using custom-pricing (implement the callbacks) - and raise/lower the price by - say - 1%. That way you get the "price-safety" of limit orders, but the hopefull execution of up to 1% slippage.

**Comment by popperwin** [comment]
Ok thanks, I'll go this way then. 
Here the function I will implement, I hope I'm right:

```
def custom_exit_price(self, pair: str, trade: Trade,
                          current_time: datetime, proposed_rate: float,
                          current_profit: float, **kwargs) -> float:

    dataframe, last_updated = self.dp.get_analyzed_dataframe(pair=pair,
                                                            timeframe=self.timeframe)
    new_exitprice = dataframe['close'].iloc[-1]*0.99

    return new_exitprice
```

Thanks for your help. It's really awesome to have that level of support with a free product :)
