### ISSUE TITLE
When using custom_entry_price cause roi to be too optimistic

### ISSUE THREAD

**Issue by adrianceding** [freqtrade/freqtrade#6470]
## Describe your environment

  * Operating system: __Ubuntu__
  * Python Version: __3.9.10___ (`python -V`)
  * CCXT version: __~___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _2022.2.1___ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

* Question 1:
When using `custom_entry_price`,
The low price of the first kline does not meet the fill price.
Enter the judgment of the second kline. The low price meets the buy price of the order. At this time, it should have timed out and canceled the order. However, since [5. Cancel expired buy/sell orders`.](https://github.com/freqtrade/freqtrade/blob/fdbd75501f1015218fc96fe5b390cf0aa323664b/freqtrade/optimize/backtesting.py#L808)  is after [# 2. Process buy orders.](https://github.com/freqtrade/freqtrade/blob/fdbd75501f1015218fc96fe5b390cf0aa323664b/freqtrade/optimize/backtesting.py#L781) So this order has been filled.

* Question 2: Based on the situation of question 1
In BT, ROI will handle the case where the duration_tf_time is 0. But it uses open_time instead of filled_time. After adding the timeout mechanism, the most ideal situation will appear. Buy at low and sell at high

### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

KLINES:
```
[
    1645921800000(2022-02-27 00:30:00+00:00),
    "76.8040",
    "77.1540",
    "76.4080",
    "77.0100",
    "272751",
    1645922099999,
    "20915192.1600",
    16769,
    "134562",
    "10323370.0560",
    "0"
],
[
    1645922100000(2022-02-27 00:35:00+00:00),
    "77.0110",
    "77.2600",
    "75.8030",
    "75.8490",
    "307304",
    1645922399999,
    "23488328.7300",
    17947,
    "127697",
    "9764874.4170",
    "0"
],
[
    1645922400000(2022-02-27 00:40:00+00:00),
    "75.8490",
    "76.2270",
    "75.6750",
    "76.1930",
    "203368",
    1645922699999,
    "15450506.8900",
    12807,
    "112208",
    "8526131.8780",
    "0"
],
```
BT trade
```
{
    "pair": "LUNA/USDT",
    "stake_amount": 14000.0,
    "amount": 184.12340687,
    "open_date": "2022-02-27 00:30:00+00:00",
    "close_date": "2022-02-27 00:35:00+00:00",
    "open_rate": 76.03596,
    "close_rate": 76.85747697478992,
    "fee_open": 0.0004,
    "fee_close": 0.0004,
    "trade_duration": 5,
    "profit_ratio": 0.009996,
    "profit_abs": 140.0,
    "sell_reason": "roi",
    "initial_stop_loss_abs": 72.9945216,
    "initial_stop_loss_ratio": -0.04,
    "stop_loss_abs": 73.0529406886254,
    "stop_loss_ratio": -0.05139602539084798,
    "min_rate": 75.803,
    "max_rate": 77.26,
    "is_open": false,
    "buy_tag": null,
    "open_timestamp": 1645921800000.0,
    "close_timestamp": 1645922100000.0
}
```

unfilledtimeout: `5m`
timeframe: `5m`

**Comment by xmatthias** [comment]
Regarding point 2 - there is special handling in place which will prevent this behavior, and only allow ROI sells at candle 0 if buy/ROI happens within the same wick (so either in the top portion or the bottom portion of the candle).

To be fair - also in live the ROI is calculated starting with the trade open date (assuming you use multiple steps), not the order fill date.

@rokups you looked at this problem more in detail than i did ... maybe you got something to add here?

**Comment by xmatthias** [comment]
I do think that behavior for this is correct as is - ROI will count from the `trade.open_date`.
I'll be adding a note to the docs that clarifies this.

If different behavior is necessary, then that'd need a custom_exit function, where you can base your logic on "whatever".
