### ISSUE TITLE
Similares

### ISSUE THREAD

**Issue by sokarblue** [freqtrade/freqtrade#6480]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Please stop opening Empty issues like this and #6479.
This is considered spam - and will have to lead to a ban from our side.

If you have questions / problems, please properly ask the question (which means the issue should also have content), thanks.
