### ISSUE TITLE
Multiple buy levels

### ISSUE THREAD

**Issue by evo11x** [freqtrade/freqtrade#6482]
## Describe your environment

  * Operating system: _Windows 11___
  * Python Version: __Python 3.9.8___ 
  * CCXT version: __1.60.68_
  * Freqtrade Version: __ 2022.1__
  
Is there a way to have multiple buy levels in backtesting and in live mode?
I did not find anything about this in the documentation.

**Comment by xmatthias** [comment]
Freqtrade is not a grid trading bot, so you'll always only have one order open per pair.

That said - once you're in a trade, you can modify the position via the [`adjust_trade_position` callback](https://www.freqtrade.io/en/latest/strategy-callbacks/#adjust-trade-position).

This will allow you to get entries at multiple levels (say at 100, 99 and 97) - and (hopefullly) then exit at 110 :laughing:

**Comment by evo11x** [comment]
I don't need a grid bot, just that having an order split in 2-3 buy levels can help a lot.

**Comment by xmatthias** [comment]
Then the above should help you sufficiently (although the 2nd order won't be placed until the first is filled).
