### ISSUE TITLE
During docker-compopse installation on Synology: "Error response from daemon: Bind mount failed"

### ISSUE THREAD

**Issue by buis12** [freqtrade/freqtrade#6485]
## Describe your environment

  * Operating system: Synology DSM 7.0.1 using Docker-compose
  * Python Version: /
  * CCXT version: /
  * Freqtrade Version: /
  
## Describe the problem:

Following the steps in https://www.freqtrade.io/en/stable/docker_quickstart/#docker-quick-start gives an error.

### Steps to reproduce:

  1. Using ssh to connect to the Synology.
  2. Executing `mkdir ft_userdata`.
  3. Executing `cd ft_userdata/`.
  4. Executing `curl https://raw.githubusercontent.com/freqtrade/freqtrade/stable/docker-compose.yml -o docker-compose.yml`.
  5. Executing `sudo docker-compose pull`.
  6. Executing `sudo docker-compose run --rm freqtrade create-userdir --userdir user_data` gives an Error.

  
### Observed Results:

This gives an error.

### Relevant code exceptions or logs

  ```
Creating network "ft_userdata_default" with the default driver
Creating ft_userdata_freqtrade_run ... done
Error response from daemon: Bind mount failed: '/.../apps/freqtrade/ft_userdata/user_data' does not exists
ERROR: 1
  ```

**Comment by xmatthias** [comment]
The error suggests that you modified the compose file, changing the mountpoint to something different than the default.

Another possibility is that your location (output of `pwd`) is a strange, synology-specific mountpoint (containing `/.../apps/`...).
In the latter case, you should be able to change the volume from `./user_data` to an absolute path.

**Comment by buis12** [comment]
The compose file hasn't been changed after running the "curl" command. However, I've slightly edited the error log. The part of `/.../apps/` was originally `/volume1/apps/`.

I've noticed that if I manually created the directory of ./userdata the following error is raised:
```sudo docker-compose run --rm freqtrade create-userdir --userdir user_data
Creating ft_userdata_freqtrade_run ... done
2022-03-02 13:45:19,682 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/deploy_commands.py", line 26, in start_create_userdir
    userdir = create_userdata_dir(args["user_data_dir"], create_dir=True)
  File "/freqtrade/freqtrade/configuration/directory_operations.py", line 68, in create_userdata_dir
    if not subfolder.is_dir():
  File "/usr/local/lib/python3.9/pathlib.py", line 1439, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/usr/local/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: 'user_data/backtest_results'
ERROR: 1
```

I'm also noticing that the command changed the owner of the manually created "user_data" directory has another owner running `ls -l`.
From `drwxrwxrwx+ 1 [my_username] users   0 Mar  2 14:44 user_data`
To `drwxrwxrwx+ 1 1000  1000   0 Mar  2 14:44 user_data`

On my device there is no user:group 1000:1000.

**Comment by xmatthias** [comment]
this refers to the internal docker user (the one within docker) - so having 1000:1000 should not be a problem.

i do notice however that you have a `+` next to the directory - which usually means that there is an additional ACL attached (which may prevent creation / writing of files).
Freqtrade needs to own the user_data directory - and have full permissions on it to work properly.

you should be able to list the acl with `getfacl <directory>` ...

**Comment by buis12** [comment]
I find it weird that I would see the 1000:1000 outside the "docker terminal".

The getfacl command unfortunately doesn't work on the Synology.

**Comment by xmatthias** [comment]
1000:1000 is the user-account within the docker container. 
While the files will have these permissions - this should not matter for freqtrade within docker.

This avoids using root (which can be used to extend permissions to the host in some instances).

Maybe it's a problem of the location - if it's managed by synology - it may get the permissions from there. That's however just a suspicion - my synology can't run docker, therefore i can't really support that any further.

**Comment by benbarnett02** [comment]
It's been a while since this thread was last active, but I've recreated this issue on a syno DS920+ running DSM 7.1.1-42962 Update 1.

```
username@hostname:/volume1/pcbackup-1/ft_userdata$ sudo docker-compose run --rm freqtrade create-userdir --userdir user_data
Creating network "ft_userdata_default" with the default driver
Creating ft_userdata_freqtrade_run ... done
Error response from daemon: Bind mount failed: '/volume1/pcbackup-1/ft_userdata/user_data' does not exists
ERROR: 1
```

Happy to do testing etc if needed.

**Comment by xmatthias** [comment]
@benbarnett02 i'd suspect that the message says it all.

docker failed to bind-mount the volume specified.
that's not really freqtrade specific - but a docker specific problem - where you'll bet get support in docker/synology supprot channels.

**Comment by nimalouk** [comment]
I fixed it! ChatGPT is magical. Just do this one:
sudo chmod -R 775 /volume1/nk/ft_userdata/user_data

_This will give read, write, and execute permissions to the owner (nk) and group (users) for all files and directories within the "user_data" directory. Then, try running the "create-userdir" command again._

**Comment by nimalouk** [comment]
I fixed it. Just ask ChatGPT, it will explain everything. Just copy and paste everything. It will give you a command to give permissions.

**Comment by celsiusxxx** [comment]
> It's been a while since this thread was last active, but I've recreated this issue on a syno DS920+ running DSM 7.1.1-42962 Update 1.
> 
> ```
> username@hostname:/volume1/pcbackup-1/ft_userdata$ sudo docker-compose run --rm freqtrade create-userdir --userdir user_data
> Creating network "ft_userdata_default" with the default driver
> Creating ft_userdata_freqtrade_run ... done
> Error response from daemon: Bind mount failed: '/volume1/pcbackup-1/ft_userdata/user_data' does not exists
> ERROR: 1
> ```
> 
> Happy to do testing etc if needed.

@benbarnett02 hi, did you manage to resolve this issue ? because I am having the same one and can't find a solution...
