### ISSUE TITLE
Using custom_stoploss to get same result as trailing stop

### ISSUE THREAD

**Issue by rongybika** [freqtrade/freqtrade#6488]
## Describe your environment

  * Operating system: windows
  * Python Version: 3.8.10 (`python -V`)
  * CCXT version: 1.73.70 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.2.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hi,

I'm trying to get same tariling_stop result using this custom_stoploss method:
```
def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                    current_rate: float, current_profit: float, **kwargs) -> float:

       if current_profit < 0.013:
            return -1 
       return 0.01

```

I don't know why I'm getting different result while backtesting.
How I should modify the method to gget the same result?

This is what I'm trying to ,,clone":

trailing_stop = True
trailing_stop_positive = 0.01
trailing_stop_positive_offset = 0.013
trailing_only_offset_is_reached = True

I wish to use same trailing stop setting but with extra conditions.

Thank you

**Comment by xmatthias** [comment]
Did you actually enable custom_stoploss? (and disable the trailing settings, too)?
otherwise they will compete with each other - and potentially cause unwanted jumps.

There's nothing obvious that's wrong - but without seeing the actual difference, it's also quite difficult to tell.

**Comment by rongybika** [comment]
Hi,

What I'm saying is that even with this custom_stoploss simple code from above, I wasn't able to achieve same  result like with the trailing stoploss as well from above. Using same configurations and everything. 

Today after checking and using some logic(stop_loss_reached) from interface.py file I was able to reproduce a very close result (example: with normal trailing stop I've got 16 USDT profit and with custom_stoploss function 12 USDT profit).

Now I'm trying to figure out from where comes that difference.

The main thing what I'm trying to develop is to fire different trailing stoploss settings depending on buy_tags.

Thank you

**Comment by xmatthias** [comment]
In backtesting - i'm not sure you can archive exactly the same result.

trailing-stoploss is something we "know" how it behaves (freqtrade controls 100% of that code) - so we can cheat and use candle's high/low values for certain adjustments (flipping which value is used mid-function) to get more realistic results.

This is unknown for custom-stoploss code, therefore the "current_profit" value you get will be calculated based on the candle's open values - while freqtrade can "adjust" based on high - and check "if hit" based on low.

**Comment by rongybika** [comment]
Ok, I understand.

I just noticed that in the new version of code on hyperopt result the max drawdown percent represents the percent of account drawdown.
If I remember correct before was an average profit  percent situation of the open trades in the end of the tested period.
For me was more useful representation of the situation for the tested period.
Can you tell me please, how can I add back this (at least for myself)?

Thank you

**Comment by rongybika** [comment]
The solution is to use an older version of hyperopt_tools.py file.

I think we can close this.

Thank you

**Comment by xmatthias** [comment]
The previous drawdown was only correct when using fixed stake, not when using compounding.
It's been the drawdown of % (so you aggregate all relative values) - which will not work the moment stake amounts are different (custom-stake / unlimited stake).

This has been changed to "account drawdown" - which will use absolute values and will show you how much of your overall account you lost.

You can obviously look for the commit and roll it back - but it's something you'll need to be very careful with as i think it was flawed in too many instances.

**Comment by rongybika** [comment]
Hi,

I'm using unlimited stake and the result was the sum of all left open trades profit percent.
I'm sure that you know better the bot but this number was for what I'm looking for. Because I'm looking for strategy settings where in a ,,bear" market situation there are not many and high negative trades are left open.
Any way I'm gone use this ,,old" file just for backtesting in a different virtual env.

What I'm think about and I'm still not sure if it's better to hyperopt for higher number of max open trades or for lower's one.
You are more experienced, do you what to share some thoughts about this?

Now I have to write a new HyperOptLoss method to check firstly sum of the left open trades percent (to be low as possible) and if there is not open trades left to take in count the profit.

Thank you

**Comment by xmatthias** [comment]
Don't overestimate "left open trades". you'll have "left open" at any point - it's purely the trades that have not been closed when the backtest-period stops.

> the result was the sum of all left open trades profit percent.

No, it was absolutely not that value - drawdown used to be the sum of the % stops.
however, if you sum a 5% win with 100$ stake and a 5% loss of 200$ stake - this did equal to 0% - which is clearly not true - and therefore the value was simply wrong - and the way you describe the usage, i think it's not showing you what you'd like it to.

**Comment by rongybika** [comment]
I know that at any point I'm gonna have some left open trades, I'm just interested in actual profit percentage of those open trades. Because in my opinion is very hard to jump from -60% into positive region easily even in crypto market.
In the next picture I'm showing which column interested me (marked with red) to be not so ,,low":

![image](https://user-images.githubusercontent.com/14143598/156885860-420d5c9f-6e35-4983-b1a5-ded8cf9566cc.png)

Thank you

**Comment by xmatthias** [comment]
It's been combined to the Profit column iirc.
