### ISSUE TITLE
How implement --timeframe-detail in Hyperopt

### ISSUE THREAD

**Issue by aziba353** [freqtrade/freqtrade#6490]
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.9.9
  * CCXT version: 1.73.70  
  * Freqtrade Version: 2022.2.1
## Your question

Hi. My strategy strictly need to use --timeframe-detail and fortunately we have it in backtest mode but in Hyper-opt it doesn't work. Is there any solution to have in in the Optimization process.  Main timeframe is 1h but I need "1m" also.

**Comment by stash86** [comment]
Then do the other way round. Main tf of 1m, and informative tf of 1h.

**Comment by xmatthias** [comment]
`--timeframe-detail` is not supported for hyperopt at the moment - and probably never will be.

It's impact on both memory and performance/runtime quite high, so hyperopt will become ineffective.
if one epoch takes too long, hyperopt will no longer be able to get to any meaningful results.

If i look at problems people face, it's already problematic from a memory perspective, and detailed mode will require even more memory - and is therefore not viable.
