### ISSUE TITLE
A worker process managed by the executor was unexpectedly terminated.

### ISSUE THREAD

**Issue by s-stolz** [freqtrade/freqtrade#6491]
## Describe your environment

  * Operating system: Docker on macOS Monterey
  * Python Version: 2.7.18
  * CCXT version: 
  * Freqtrade Version: freqtrade docker-d4fbb785
  
## Your question

I am trying to run a Hyperopt for my strategy for 7 pairs, one year of 1H candles.

But I am getting a ERROR: 1

I already tried to reduce the number of parallel workers with the -j 5 command.

Any Idea to fix this Error?

**Comment by stash86** [comment]
1. reduce the workers more. More workers = more memory needed. Less workers = less memory needed.
2. reduce the timerange

**Comment by xmatthias** [comment]
It's quite a simple "out of memory" error.
the [hyperopt documentation page](https://www.freqtrade.io/en/stable/hyperopt/#out-of-memory-errors) describes some things you can do about that - but in the end it all comes down to reducing the necessary memory.

**Comment by s-stolz** [comment]
Thank you for the fast reply. I have reduced it to 3 parallel workers. Now I am getting this error message:

> TypeError: '<' not supported between instances of 'str' and 'int'

Is this still a memory problem or is there something wrong in my code?

I try to optimize a MACD-EMA strategy. For this I create the following parameter ranges:

`    #buy    
    buy_ema= IntParameter(150, 250, default=200, space="buy")

    buy_macd_fast = IntParameter(7, 20, default=12, space="buy")
    buy_macd_slow = IntParameter(20, 30, default=26, space="buy")
    buy_signal_smothing = IntParameter(5, 15, default=9, space="buy")
    
    buy_cross_below_enabled = BooleanParameter(default=True, space="buy")

    #sell
    sell_macd_fast = IntParameter(7, 20, default=12, space="sell")
    sell_macd_slow = IntParameter(20, 30, default=26, space="sell")
    sell_signal_smothing = IntParameter(5, 15, default=9, space="sell")
`

In `populate_indicators` I create the following df:

`        frames = [dataframe]

        for val1 in self.buy_macd_fast.range:
            for val2 in self.buy_macd_slow.range:
                for val3 in self.buy_signal_smothing.range:
                    frame = DataFrame()

                    macd = ta.MACD(dataframe, fastperiod=val1, slowperiod=val2, signalperiod=val3)
                    frame[f'macd_{val1}_{val2}'] = macd['macd']
                    frame[f'macdsignal_{val1}_{val2}_{val3}'] = macd['macdsignal']
                    frames.append(frame)
        

        # # EMA - Exponential Moving Average
        for emaLength in self.buy_ema.range:
            frame = DataFrame()
            frame[f'ema{emaLength}'] = ta.EMA(dataframe, timeperiod=emaLength)
            frames.append(frame)
            
        merged_frame = pd.concat(frames, axis=1)
`

And these are my buy and sell trend functions:

`    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        conditions = []

        # EMA Condition
        conditions.append(dataframe['close'] > dataframe[f'ema{self.buy_ema.value}'])

        # MACD Condition
        conditions.append(qtpylib.crossed_above(dataframe[f'macd_{self.buy_macd_fast.value}_{self.buy_macd_slow.value}'], dataframe[f'macdsignal_{self.buy_macd_fast.value}_{self.buy_macd_slow.value}_{self.buy_signal_smothing.value}']))

        if self.buy_cross_below_enabled.value:
            conditions.append(dataframe[f'macdsignal_{self.buy_macd_fast.value}_{self.buy_macd_slow.value}_{self.buy_signal_smothing.value}'] < 0)
        
        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
                'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the sell signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with sell column
        """
        conditions = []
        conditions.append(qtpylib.crossed_above(dataframe[f'macdsignal_{self.sell_macd_fast.value}_{self.sell_macd_slow.value}_{self.sell_signal_smothing.value}'], dataframe[f'macd_{self.sell_macd_fast.value}_{self.sell_macd_slow.value}']))

        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
                'sell'] = 1

        return dataframe
`

Thank you for your help.

**Comment by stash86** [comment]
well, it seems your buy_trend crossed above check is the problematic one, esp the first variable.

Don't ask me what, you would need to debug it. All I know is first input is str, second input is int. So check the first input

**Comment by xmatthias** [comment]
You should be able to use backtesting (with a smaller timerange?) to get to this error.
It's no longer a memory error, but a invalid comparison  (`< between string and int`).

Please note:
posting logs as screenshots is quite bad - as it takes away the possibility to copy/paste the error and either search or quote it here.
