### ISSUE TITLE
Non crypto data

### ISSUE THREAD

**Issue by devanshmak** [freqtrade/freqtrade#6514]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*

Option to add and use non crypto data for backtesting.

**Comment by xmatthias** [comment]
Freqtrade itself is a crypto trading bot, not one for traditional markets.

It's backend works based on ccxt (which is a crypto library).
There's nothing preventing you from writing traditional data to the default freqtrade format (which is just a json file in the end, with open,high,low,close,volume as columns (without headers)).
looking at the proper file should get you to "how to" write this from a pandas dataframe quite easily.

For freqtrade itself, this will however not make sense.
As you'd not be able to use these great backtesting results in live, there's little point in adding support for backtesting this, as freqtrade's backtesting is made to backtest freqtrade strategies, not as generic backtesting framework.
