### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by elestranobaron** [freqtrade/freqtrade#6515]
Docker raspberry here

I don't know if it's already available i command the bot via telegram but im not used to webui

Id like to see statictics some sort of like "u did most of your profit between 12PM and 2 am"

If i have to do it myself which database i have to look for ? i belive you use a sqlite2 one but i'm not sure

**Comment by elestranobaron** [comment]
Or to make simpler

Where do i connect apache superset to see data

**Comment by xmatthias** [comment]
FreqUI does have a dashboard view, which will give you certain graphs.

We've removed the "between hours" graph again - as it's not really relevant in crypto space.
You can obviously connect with whatever means to the sqlite3 database directly and do whatever analysis you desire, either via some tools (it's however up to you to figure out how to connect these tools to an sqlite3 database) - or via the [data analysis notebook](https://www.freqtrade.io/en/stable/data-analysis/) - which allow you to do interactive analysis of the data.

**Comment by elestranobaron** [comment]
ok, i know there are two main tool for seeing data

One will have his own engine to make the warehouse real fast to request

the other, the interactive one need a fast database.

Is it possible for me, like in frameworks sorts of Django, replace sqlite3 from freqtrade by mariadb columnstore ?

**Comment by elestranobaron** [comment]
Or, say it another way is, can i make the bot use my own database ?

**Comment by xmatthias** [comment]
I'd encourage you to look through the full documentation. It will show you the possibilities of freqtrade.

This is possible - and is [covered by the documentation](https://www.freqtrade.io/en/latest/sql_cheatsheet/#use-a-different-database-system).
