### ISSUE TITLE
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by Faiz-datascientist** [freqtrade/freqtrade#6516]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
First of all, you should fill out the issue template - and the content itself as well.
It's rare that having a title is enough - and the below is therefore speculation based on previous issues with similar wording.

It's an installation missmatch - most likely between ta-lib and numpy.

Your best bet is to remove both libraries, and install from scratch - as this will usually fix the issue.

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered and we've had no further feedback.

Feel free to comment below / reopen if it's still unclear.
