### ISSUE TITLE
What happen if I add a pair to the blacklist in case of open trades?

### ISSUE THREAD

**Issue by TEuler27** [freqtrade/freqtrade#6520]
Suppose i have an open trade for a pair (eg ETH/USDT) and i add this pair to the blacklist using the REST Api or the telegram bot. Then i reload the config file to update it. Will my trade be closed immediately or will it wait for the roi/sell signal? Does the blacklist only inhibit new buys?

**Comment by xmatthias** [comment]
all open pairs will be "force-added" to the pair whitelist - which will circumvent the blacklist, so open trades will be handled accordingly - but no new trades would be opened for this pair.
