### ISSUE TITLE
freqtrade.rpc.fiat_convert WARNING while using UI

### ISSUE THREAD

**Issue by ketank1000** [freqtrade/freqtrade#6541]
Iam constantly seeing this log when I access the UI

freqtrade      | 2022-03-15 09:56:56,415 - freqtrade.rpc.fiat_convert - WARNING - Found multiple mappings in goingekko for usdt.
freqtrade      | 2022-03-15 09:56:56,418 - freqtrade.rpc.fiat_convert - WARNING - unsupported crypto-symbol usdt - returning 0.0

Even the daily profit on Dashboard is blank.
I tried to find why it is causing issue, but wasnt able to.

is this a know issue or is something wrong from my side

**Comment by DBVG** [comment]
same here and don't receive usdt to usd amount
I tried the solution > https://github.com/freqtrade/freqtrade/issues/6518#issuecomment-1064333380 but it dose not seem to work still don't get the usd value when i trigger /balance on telegram( running
 (2021.8-dry run-rasPI-Docker)

**Comment by ketank1000** [comment]
Its working for me in develop (even /balance on telegram), I guess you need to pull your image again and test it out,

Have to wait till the the fix appears in stable branch

Thank you @DBVG

**Comment by xmatthias** [comment]
duplicate of #6519  and #6518 - both of which contain more information
