### ISSUE TITLE
Edge: Winrate = 1 if all trades are losses

### ISSUE THREAD

**Issue by 1amcord** [freqtrade/freqtrade#6546]
## Describe your environment

  * Operating system: Ubuntu Linux
  * Python Version: 3.8.10
  * latest docker image
  * Freqtrade Version: freqtrade 2022.2.1

## Describe the problem:

If I run edge for a pair that has only losses, the result is: expectancy = inf and winrate = 1. This leads to maximum stoploss value.
In this case I expected winrate = 0 because pair should be removed from whitelist.

### Steps to reproduce:

  1. Run freqtrade for a pair with only losses in a row
  
### Observed Results:

  * winrate = 1 -> pair is on whitelist -> stoploss set to max stoploss value
  * Expectation: pair with only losses should not be on whitelist

### Relevant code exceptions or logs
```
|     Pair |   Stoploss |   Win Rate |   Risk Reward Ratio |   Required Risk Reward |   Expectancy |   Total Number of Trades |   Average Duration (min) |
|----------+------------+------------+---------------------+------------------------+--------------+--------------------------+--------------------------|
| DOGE/USD |      -0.24 |       1.00 |                 inf |                   0.00 |          inf |                        5 |                      924 |

```

**Comment by xmatthias** [comment]
To be honest, i can't really verify this result - not with the explanation provided.
 
looking at both the code - as well as attempting to write a test (apparently my strategies can't only lose - they always win "a bit") - i can't get to this result.

the win-rate is calculated as `df['winrate'] = df['nb_win_trades'] / df['nb_trades']` - so assuming 0 wins - that'd be `0 / 5` - which comes out as 0.

Now obviously win-rate will influence all other calculations - but for the moment - the only way i could get to this (from a logic / math perspective) is by having all winning trades - where you'd have 5/5 = 1.

As you're not losing - you can't really calculate a reasonable RR  (that's average win / average loss - but we didn't lose - so it is "inf").

**Comment by 1amcord** [comment]
Thank you for the quick reply and of course you are right.

I guess my downloaded OHLCV-Data were corrupt. I have removed them and fetched them again. Now the win rate is as bad as expected.

One thing I can see but I don't know if it is an error.
I looks like Expectancy is inf if there is not enough input data.

I got this warning for pair XRP/USD

```
WARNING - Missing data at start for pair XRP/USD at 15m, data starts at 2022-02-14 21:30:00
```
and this row in the edge result for that pair. All other pairs have proper values, no inf.
```

|      Pair |   Stoploss |   Win Rate |   Risk Reward Ratio |   Required Risk Reward |   Expectancy |   Total Number of Trades |   Average Duration (min) |
|-----------+------------+------------+---------------------+------------------------+--------------+--------------------------+--------------------------|
|   XRP/USD |      -0.16 |       1.00 |              inf    |                   0.00 |       inf    |                        4 |                     2550 |
```

**Comment by xmatthias** [comment]
well it's winning all trades.
inf is not worse than any other randomly assigned value - and it simply means that your expectancy is infinitely high (you didn't lose a trade for that pair in that timerange - so you can expect "infinite profits"). That's obviously not true - but the data doesn't suggest any losses.

**Comment by 1amcord** [comment]
I see. If I run backtest for one of these inf coins I got 0 buys.

Thank you for clarification!

**Comment by xmatthias** [comment]
backtesting and edge work slightly differently. 
The fact that edge detects buys however means that there must be buy signals (which may no be acted on as they collide with sell signals for backtesting).
