### ISSUE TITLE
Freqtrade does not trade and returns this message, docker-compose

### ISSUE THREAD

**Issue by luizpaulonievola** [freqtrade/freqtrade#6554]
## Describe your environment

  * Operating system: Gentoo
  * Python Version: 3.9 (`python -V`)
  * CCXT version: 1.76.5 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.2.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

bot1_binance    | 2022-03-19 12:05:20,865 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-73fc344e', state='RUNNING'
bot1_binance    | 2022-03-19 12:05:47,504 - freqtrade.rpc.rpc - WARNING -  Could not get rate for pair LDBAT.
bot1_binance    | 2022-03-19 12:05:47,504 - freqtrade.rpc.rpc - WARNING -  Could not get rate for pair LDBRL.
bot1_binance    | 2022-03-19 12:05:47,505 - freqtrade.rpc.rpc - WARNING -  Could not get rate for pair LDSFP.

I don't use proxy, 
"max_open_trades": 1,
    "stake_currency": "USDT",
    "stake_amount": 150,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "1m",
    "dry_run": false,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 10,
        "unit": "minutes"

**Comment by xmatthias** [comment]
Freqtrade will enter trades based on the strategy's signals.

The messages themselvs happen because you have "non-tradable" assets in your account. they're however no problem and will not impact trading operations.

see #5575 or #6302 for details on what these are (look at the savings pool ...)
