### ISSUE TITLE
Gate.io: -99% directly after Trade Enter

### ISSUE THREAD

**Issue by mac-88** [freqtrade/freqtrade#6556]
When i enter a Trade on Gate.io, i gives me directly -99% back and sell it. 

  * Operating system: Kali Linux
  * Python Version: _____Python 3.9.10
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-3133be19e

When i enter a Trade on Gate.io, it gives me directly -99% back and sell it. But on trade history i have the correctly price from the trade. It looks like on active Trade i dont have the correct candle data.

I had an old version of Freqtrade and everything works fine with gate. Then i updated to the newest develop and have this problem. Only on Gate. Now when i go back to older version of freqtrade, i have the same problem. maybe some updated dependencies are the problem?
I cant use gate anymore. Some Ideas whats the problem is? Thanks so much for help

**Comment by xmatthias** [comment]
with the provided information, there is nothing we can do for you.

Please provide the ccxt version - as well as some logs on what's happening, if necessary, excerpts / lines from the database.

**Comment by xmatthias** [comment]
After sleeping about this issue i think it's pretty clear.

ccxt had an issue with gateio pricing - assigning "cost" to average price.

So assuming you buy 100 XRP at a rate of 2$ - your average would be expected to be 2$.
The response we received did however contain cost - so 100*2 = 200 - so the new assumed entry-price was 200$.
Based on this - you're obviously immediately at -99% - as all other methods know that "price" is 2$.


The version you're using (3133be19e) is from last sunday - the ccxt version fixing this was pinned on monday.

As such - please update your bot to the latest version - and make sure to also update all dependencies according to the [updating guide](https://www.freqtrade.io/en/stable/updating/) matching your installation method.

---

if you still have a trade open with this problem - you should be able to work around it with the following steps:
* stop freqtrade
* Update freqtrade
* Open the database (sqlitebrowser / sqlite3), and modify the column "ft_is_open" in the orders table from False to True for the affected trade(s).
* Start freqtrade

Freqtrade will detect the orders as "assumed open" - and will update them based on the exchange response.
As the new version returns correct values - the price will be updated to the correct value.

**Comment by mac-88** [comment]
it works after update. Thank you so much.

Have a nice day and keep your amazing work on, its fantastic!
