### ISSUE TITLE
inheritance strategy can not load  parameter file shared from base class

### ISSUE THREAD

**Issue by BourneSuper** [freqtrade/freqtrade#6557]
<!-- 

## Describe your environment

  * Operating system: ubuntu
  * Python Version: 3.8.10`
  * CCXT version: _1.74.63
  * Freqtrade Version: fraqtrade develop
  

## Describe the problem:

if StragegyA derived from StragegyB written in same .py file, 
then both of them share the same json file generated by Hyperopt.

They would could conflict with each other when using Hyperopt to optimize one of them after the other Strategy was optimized.

### Steps to reproduce:

  1. StragegyB derived from  StragegyA and they are in one .py file
  2. optimize StragegyA using Hyperopt ( get file A.json)
  3. optimize StragegyB using Hyperopt 
  4. switching step3 and step2 is the same result
  
### Observed Results:
load file A.json as StragegyB  parameter file, then ERROR

### Relevant code exceptions or logs

2022-03-20 00:59:44,224 - freqtrade.optimize.hyperopt_tools - INFO - Dumping parameters to /home/bourne/freqtrade-develop/user_data/strategies/AStrategy.json

...

2022-03-20 01:01:06,082 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy BStrategy from '/home/bourne/freqtrade-develop/user_data/strategies/AStrategy.py'...
2022-03-20 01:01:06,082 - freqtrade.strategy.hyper - INFO - Loading parameters from file /home/bourne/freqtrade-develop/user_data/strategies/AStrategy.json
2022-03-20 01:01:06,082 - freqtrade - ERROR - Invalid parameter file provided.

**Comment by BourneSuper** [comment]
all the words gone...

**Comment by BourneSuper** [comment]
## Describe your environment

  * Operating system: ubuntu
  * Python Version: 3.8.10
  * CCXT version: 1.74.63
  * Freqtrade Version:  freqtrade develop
  


## Describe the problem:

if BStrategy derived from AStrategy written in the same .py file, then they are sharing the same parameter json file.

Confilct happens when loading paremter file.
 

### Steps to reproduce:

  1. BStrategy derived from AStrategy written in the same .py file
  2. optimize AStrategy ( get json file )
  3. optimize BStrategy. it loads json file of AStrategy and goes error.
  
### Observed Results:
it loads json file of AStrategy and goes error.

it should not share parameter file or load carefully


### Relevant code exceptions or logs


  ```
2022-03-20 00:59:44,224 - freqtrade.optimize.hyperopt_tools - INFO - Dumping parameters to /home/bourne/freqtrade-develop/user_data/strategies/StrategyA.json

...
2022-03-20 01:01:06,082 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy StrategyB from '/home/bourne/freqtrade-develop/user_data/strategies/StrategyA.py'...
2022-03-20 01:01:06,082 - freqtrade.strategy.hyper - INFO - Loading parameters from file /home/bourne/freqtrade-develop/user_data/strategies/StrategyA.json
2022-03-20 01:01:06,082 - freqtrade - ERROR - Invalid parameter file provided.
  ```

**Comment by xmatthias** [comment]
strategy parameter files are named according to the strategy file - so the file "StrategyXX.py" will have the parameter file "StrategyXX.json".

The load will succeed if the parameter file corresponds to the strategy you're loading (so if the parameter file is for `strategyB` (it's the content, not the name that counts).

in your case it seems like it's not - your parameter file is for strategy `StrategyA` - while you're loading `StrategyB` - therefore the load fails (as the parameters are wrong for your strategy.
Simply put - run optimization for `StrategyB` before loading `StrategyB`.


There's little we can do for this i think - this sounds like intended behaviour - with the "protection" against running a wrong parameter file working.
The "error" you're running into is to avoid loading a non-matching parameter file - which is there intentionally.

Every fix i can think of would remove the "invalid parameter file provided" protection - leading to either simply ignoring an available, but wrong parameter file - or to loading a wrong parameter file. Neither of the 2 are options i'm comfortable with.

In general, i would recommend to have one file per strategy to avoid this behavior.

**Comment by BourneSuper** [comment]
` one file per strategy`  is not good solution for me，I get 30 sub class files to write.

During i tried the solution, another error occured.
`freqtrade.resolvers.iresolver - WARNING - Could not import /home/bourne/freqtrade-develop/user_data/strategies/StrategyA.py due to 'No module named 'samplestrategy''`

# Steps to reproduce:
1. prepare StrategyA.py
```
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).parent))

from samplestrategy import SampleStrategy

class StrategyA(SampleStrategy): pass
```
2. optimize StrategyA

**Comment by xmatthias** [comment]
We can fix this pretty easily by improving how imported strategies work.

after #6560 - you'll no longer have to mess with "path" - and freqtrade will only detect strategies that are defined in that file.
Therefore, there'll no longer be false-positives (your case would currently also be flagged as "duplicate" when using `list-strategies`).

We'll therefore recommend to use separate files per strategy - and the docs will include a warning about potential problems when using 2 strategies in the same file.

**Comment by BourneSuper** [comment]
Thanks
It's something about class loading and config loading. Even a backup file with .py extension can mess with the loading.

**Comment by xmatthias** [comment]
> Even a backup file with .py extension can mess with the loading.

The problem is that for python, there's no difference if it's a regular file (`strategy.py`) - or a backup file (`strategy_bak.py`) - as long as they have the ".py" extension, they'll be loaded.
it's dependant on the name - freqtrade will load the first alphabetical (from the file perspective).

As mentioned above - `list-strategies` will identify duplicates - and we will probably make this check mandatory (and fail to load a strategy if duplicates exist) to avoid wrong strategies from loading.
