### ISSUE TITLE
Mac M1 arm64 docker-compose installation halts

### ISSUE THREAD

**Issue by sabrieker** [freqtrade/freqtrade#6562]
### **Describe your environment**

Operating system: macOS Monterey arm64 using Docker-compose
Python Version: /
CCXT version: /
Freqtrade Version: /

### **Describe the problem:**

Following the steps in https://www.freqtrade.io/en/stable/docker_quickstart/#docker-quick-start gives an error.

### **Steps to reproduce:**

Executing mkdir ft_userdata.
Executing cd ft_userdata/.
Executing curl https://raw.githubusercontent.com/freqtrade/freqtrade/stable/docker-compose.yml -o docker-compose.yml.
Executing sudo docker-compose pull.
Executing sudo docker-compose run --rm freqtrade create-userdir --userdir user_data doesn't give an error or creates directory structure.

Terminal halts with this command and doesn't continue. It doesn't creates user_data folder or prints any error on terminal. Also docker desktop shows container status as Created and only logs as 'Attaching to' 

Any ideas? 

Relevant code exceptions or logs

```
ft_userdata % docker-compose run --rm freqtrade create-userdir --userdir user_data

Creating network "ft_userdata_default" with the default driver
Creating ft_userdata_freqtrade_run ... done
```
Docker logs only 

`Attaching to`

Also following command doesn't show a user interaction for the questions. 
`docker-compose run --rm freqtrade new-config --config user_data/foo.json`

**Comment by xmatthias** [comment]
this sounds like a problem with docker itself - not with freqtrade.

did you run docker on this system before and it did work? or did you install it for freqtrade - so this is your first container attempt?

**Comment by sabrieker** [comment]
I have running dockers which are postgres:alpine, mcr.microsoft.com/azure-sql-edge and redis.
I didn't catch the part that I have no logs. My terminal seems halt status. Doesn't respond anything, just waiting.

**Comment by xmatthias** [comment]
the most likely reason is some problem with mounting `ft_userdata` (but honestly, your's is a problem i've never heared about before).
Is it on an internal drive - or on some external / exotic file system?

**Comment by sabrieker** [comment]
No nothing is exotic. The path is as below that I created with mkdir command. I received the docker-compose.yml with curl command but following steps didn't work. 

`/Users/my_user_name/ft_userdata`

**Comment by xmatthias** [comment]
what's the output of the following commands?

`docker-compose ps`
`docker ps`
`docker-compose logs`

**Comment by sabrieker** [comment]
```
ft_userdata % docker-compose ps
Name   Command   State   Ports
------------------------------
```

```
ft_userdata % docker ps
CONTAINER ID   IMAGE                              COMMAND                  CREATED      STATUS      PORTS                              NAMES
87d9c79e142f   postgres:alpine                    "docker-entrypoint.s…"   6 days ago   Up 6 days   0.0.0.0:5432->5432/tcp             posttest
5250c9921d2e   hldev8                             "/bin/sh -c bash"        6 days ago   Up 6 days                                      running
e790a629aa32   mcr.microsoft.com/azure-sql-edge   "/opt/mssql/bin/perm…"   6 days ago   Up 6 days   1401/tcp, 0.0.0.0:1433->1433/tcp   sql

```

```
ft_userdata % docker-compose logs
Attaching to
```

I also tried but all the containers are in CREATED status. my I should try to build freqtradeorg/freqtrade:develop in local to see if it works. Sorry taking your time. 
` docker run -d --name devtest -v /Users/sabri/ft_userdata/user_data:/freqtrade/user_data freqtradeorg/freqtrade:stable create-userdir --userdir user_data`

**Comment by sabrieker** [comment]
I think it is related with M1 ARM64 chipset because I successfully run the same commands on MacBook Air with Intel chipset  and both of the machines has same Operating System. 
Maybe I should checkout the docker image and investigate it. It probably halt at some point.

**Comment by xmatthias** [comment]
is your docker instance running natively, or in "rosetta mode"?

We do build arm64 images as well - and i know from others that they do run on M1's, too.
even if your docker installation decided to download the "wrong" multi-arch image - you'd get an exception about missmatching architecures, so this is not really something i can explain at the moment.

obviously building yourself is an option to try out.

**Comment by sabrieker** [comment]
It is got resolved. I just restarted the Docker Desktop. 
It turns out, containers looked like in Running status but they were not when I try to work with one of CLI of them.
Restart fixed Docker Desktop and all your commands run smoothly. 

Sorry for inconvenience.

**Comment by xmatthias** [comment]
I was suspecting a docker-level issue from the getgo - as it's a VERY uncommon error.

Thanks for confirming that it's fixed now 👍
