### ISSUE TITLE
failed to plot on docker when I USE the BBandsRSI strategy

### ISSUE THREAD

**Issue by Klasticrypto** [freqtrade/freqtrade#6564]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/plot_commands.py", line 24, in start_plot_dataframe
    load_and_plot_trades(config)
  File "/freqtrade/freqtrade/plot/plotting.py", line 626, in load_and_plot_trades
    fig = generate_candlestick_graph(
  File "/freqtrade/freqtrade/plot/plotting.py", line 481, in generate_candlestick_graph
    fig = add_indicators(fig=fig, row=1, indicators=plot_config['main_plot'], data=data)
  File "/freqtrade/freqtrade/plot/plotting.py", line 112, in add_indicators
    plot_type = conf.get('type', 'scatter')
AttributeError: 'set' object has no attribute 'get

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by not filling out the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

BBandsRSI is not a strategy that is available in the [official freqtrade strategies repository](https://github.com/freqtrade/freqtrade-strategies).

While there's strategies with similar names - it'd be a waste of time to investigate without knowing for sure.

The error suggests that the plot-config is faulty/wrong (wrong format, basically).
Without the strategy (or at least the plot_config part) - it's however impossible to investigate further.

**Comment by xmatthias** [comment]
Closing this assuming you found the answer.

Feel free to comment below or reopen if that's not the case.
