### ISSUE TITLE
High and lows

### ISSUE THREAD

**Issue by Tarsock** [freqtrade/freqtrade#6577]
384 / 5.000

Good day

I have a few questions:
maybe someone can help
I tried to get ta.MIN(Low and high) with ta.MIN
Unfortunately, ubuntu does not know the function
is there a way to get the highs and lows of each candlestick so i can do my own calculations?
is there an example how to calculate the last high and low of say 150 candles?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---


The freqtrade dataframe looks as [described in the documentation](https://www.freqtrade.io/en/stable/strategy-customization/#dataframe).
You can get the high and low of each candle using standard pandas column referencing (e.g. `dataframe.loc[:, 'high']`).

Calculating a rolling min/max should be pretty easy - as it's just a pandas dataframe - so using `.rolling(window).min()` and `.rolling(window).max()` on the appropriate columns should get you running.
For detailed instructions regarding this best refer to the pandas documentation - or to the ta-lib documentation if you'd like to use ta.MIN and ta.MAX.

**Comment by Tarsock** [comment]
very much thanks
