### ISSUE TITLE
How does freqtrade deal with filterType: MARKET_LOT_SIZE? 

### ISSUE THREAD

**Issue by thanatchon36** [freqtrade/freqtrade#6579]
According to Binance Exchange Info:

Symbol, maxQty MARKET_LOT_SIZE (As-is BTC Worth)
PROMBTC , 0.573570141462135
FLMBTC , 0.5679084474912659
MOVRBTC , 0.56226305882488
MDABTC , 0.5551352566504255
WOOBTC , 0.550690997831025
BNXBTC , 0.5415230872645199
QUICKBTC , 0.53345241231034
OAXBTC , 0.5248463292847095
FORTHBTC , 0.521943465386906
EPSBTC , 0.5044972909937301
MLNBTC , 0.5011197603760801
AUTOBTC , 0.500966687715
PHBBTC , 0.49321757126198235
KDABTC , 0.48172974260768203
GNOBTC , 0.42432694310363

In case when placing the market order within the above symbol list, if we take the market order of 1 BTC Worth within 1 order, the binance would not allow to place the order because the maximum volume must not exceed 0.42 - 0.57 BTC.

Regarding with this config setting:
    "order_types": {
        "buy": "limit",
        "sell": "limit",
        "emergencysell": "market",
        "forcebuy": "market",
        "forcesell": "market",
        "stoploss": "market",
        "stoploss_on_exchange": true,
        "stoploss_on_exchange_interval": 60
    },
    "bid_strategy": {
        "price_side": "ask",
        "ask_last_balance": 0,
        "use_order_book": false
    },
    "ask_strategy": {
        "price_side": "bid",
        "use_order_book": false
    },
    "exchange": {
        "name": "binance",
    }, ...

My quesiton is how freqtrade would circumvent with this situation:
If strategy decides to place a Stoploss Order on PROMBTC with 0.57 maxQty MARKET_LOT_SIZE, 

My first assumption is that the freqtrade break the main market order into 2 sub-orders: 0.57 and  0.43 BTC-worth market orders and then execute them.

My second assumption is that the freqtrade is aware of the MARKET_LOT_SIZE issues and then would place traditional stop limit orders until 1 BTC was fulfilled with 60-second-interval stop loss order updates.

Or the freqtrade would take the other assumptions, Please advise.

**Comment by xmatthias** [comment]
This falls into a very similar category than #5247 - basically both about max limits.

Technically, we don't handle this at the moment - and so far it's not been a problem - as the overall total limits used to be high enough (higher than what people are comfortable with having the bot automatically trade in one position).

Freqtrade will most likely fail placing the order (but already the buy order - stoploss is then no longer a problem as you never entered the trade in the first place).
The most likely behaviour will be to simply top-cap the order at that value (- a few % room, so it can be sold even if it's raising).

Behaviour of this will however change with #6552 - which will start validating the max amounts - and will reduce the amount once you reached the max.

**Comment by thanatchon36** [comment]
> This falls into a very similar category than #5247 - basically both about max limits.
> 
> Technically, we don't handle this at the moment - and so far it's not been a problem - as the overall total limits used to be high enough (higher than what people are comfortable with having the bot automatically trade in one position).
> 
> Freqtrade will most likely fail placing the order (but already the buy order - stoploss is then no longer a problem as you never entered the trade in the first place). The most likely behaviour will be to simply top-cap the order at that value (- a few % room, so it can be sold even if it's raising).
> 
> Behaviour of this will however change with #6552 - which will start validating the max amounts - and will reduce the amount once you reached the max.

Thank you so much. I appreciate your answer.
