### ISSUE TITLE
download-data problems

### ISSUE THREAD

**Issue by volumeman** [freqtrade/freqtrade#6580]
## Describe your environment

  * Operating system: Ubuntu 20.04.3 LTS
  * Python Version: Python 2.7.18 (`python -V`)
  * CCXT version: 1.70.31 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2022.2.2 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi there,
I'm trying to load the current pairs with the following command:
screen -dS btc -m freqtrade download-data --exchange binance --pairs "BTC/USDT" -v --logfile /var/log/freq &

This also works, the log file fills up with the corresponding entries.

Unfortunately, the files BTC_USDT-1m.json, BTC_USDT-5m.json and BTC_USDT-trades.json.gz as well as BTC_USDT-trades.json under /user_data/data/binance are NOT updated

Where's the mistake? If I remove the files from the directory, they are created again, but apparently not updated

**Comment by xmatthias** [comment]
`*.trades.*` files should not be read/updated - if they are created for binance, then you're using freqtrade wrong (basically with the `--dl-trades` option, or by defining the corresponding entry in the configuration).


json in general will NOT be appended, but will always be completely rewritten (that's a limitation of JSON, really)- even when appending data (Freqtrade will load the data, and then append new rows to it in memory).

Without seeing the logs it's however unclear if they are appended to, or if freqtrade downloads the full data again.

**Comment by volumeman** [comment]
Thank you for your feedback,
my idea was to use the above command to download all the data for the last 30 days. Then every day for the last day via Cron.
Whenever I want to do backtesting, he always says he doesn't have any data for the period
My command for this:
freqtrade backtesting -s SmoothScalp --timerange=20220320- --timeframe 5m 

![grafik](https://user-images.githubusercontent.com/102139728/159653820-700b375b-a325-4870-b8d0-ddb80dca1f76.png)

**Comment by xmatthias** [comment]
please provide logs as text wrapped in tripple backticks (`) - so it can be copy/pasted.
Also, judging problems from one line of log is usually not possible.

The most likely reason is what it says - there's no data available.
Maybe your download-data command downloaded the data someplace else, or for a different timeperiod or different exchange.
Without logs (from both download-data, as well as backtesting) that'll be impossible to determine for certain - and will leave us fishing around without really knowing.

**Comment by xmatthias** [comment]
I'll assume this as closed.

Feel free to comment below if that's not the case.

**Comment by wesley66888** [comment]
when i run the bot, latest data is not downloaded, while, when i use download data command, i can download latest data, can anyone tell why and how i can fix this issue? thanks a lot!

**Comment by xmatthias** [comment]
@wesley66888 Please refer to the [documentation](https://www.freqtrade.io/).

If that still leaves open questions, please open a new issue.
highjacking old issues (like - 2 years old) with random comments (other than the topic, this is not related at all) is both bad practice (everyone in this conversation will be pinged), and will leave more questions about what you're actually trying to do.

thanks for your understanding.
