### ISSUE TITLE
Indicators not present in dataframe until a random number of candles later

### ISSUE THREAD

**Issue by winginitau** [freqtrade/freqtrade#6586]
* Operating system: linux
  * Python Version:  3.8
  * CCXT version: 1.74.63
  * Freqtrade Version:  freqtrade develop-f571fee89
  
Sorry to bother you on this one - have been bug searching and reading everything for 2x days and I'm still stuck and now out of options. This started as a sideline curiosity re integration of a deep learning process I am using, however the most ordinary part is a problem. 

I am using an external library "zigzag" to find peaks and valleys. "pip intslall zigzag" for the original version, plus some variations I have modified - all with same issue. I have separatley validated and debug traced the operations of these libraries and they work as expected.

The indicator is produced as follows in populate_indicators:
```
        cust_X = dataframe['close']
        cust_pivots = peak_valley_pivots(cust_X.values, 0.005, -0.005)
        dataframe['zigzag'] = pd.Series(cust_pivots)
```
The indicators are -1 for a valley, 1 for a peak, 0 for none. 

To aid debug i am using:
```
    startup_candle_count: int = 0
    process_only_new_candles=True
```
To detect peaks and valleys (in dry-run and live), the trend must pivot to the opposite direction therefore buy and sell signals can only be detected in the second-last candle, not the most recent. 

To avoid looking into the future for backtesting and necessary for live, the buy (and similarly the sell) is detected as follows:
```
    dataframe.loc[ (dataframe['zigzag'].shift(1) == -1), ['buy', 'buy_tag']] = (1, 'buy_signal_zigzag')
```
The problem:
- The buy/sell signal is not detected and traded. (no signal in log)
- The buy/sell symbol does not appear in the plot until a _random_ number of candles later. It does appear in the right location, however anywhere between 3 and 12 candles later (observed so far). 
- Debug code written into the populate* functions also show the indicator randomly appearing in the dataframe tail at location 3-12 when it does eventually pop into existence.

I initially concluded that the zigzag code must therefore be buggy, however in every test and step through I have performed it seems robust. I even timed the execution in case that was an issue - not. 

Any insights would be greatly appreciated. 

Screen shots attached. (note this is without the shift(1) in the signal detection for debugging purposses). 
 
![8Capture](https://user-images.githubusercontent.com/31975164/159910186-3a4c64b0-70d0-44e3-b089-9c46cdc10273.PNG)

![9Capture](https://user-images.githubusercontent.com/31975164/159910213-0d84d492-65aa-4321-b155-8c1d9aa0c790.PNG)

**Comment by xmatthias** [comment]
The general problem with peak/valley detections is real-time.

It's easy to determine that afterwards (basically looking at a chart and saying "this was a valley".
Usually, this peak/valley will change around for a few candles (if you observe it on a running window), before stabilizing on "this was a valley".

The same thing happens when you look at a chart - if i hide all futures candles, it'll be pretty difficult to determine if the last/2nd to last candle was a valley, or if if it an additional downswing is to follow.

I guess the same thing will happen here - so the library can confidently determine "this was a valley" after 3 confirmation candles (but not before).
As such, you're seeing the signals "late".
Backtesting won't suffer from this, as it'll see the "whole" dataframe.

You should be able to see this in action during backtesting by applying this decorator to your `populate_indicators()` method (just move all code there, and simply use `return dataframe` in populate_buy / populate_sell). while that'll not work for hyperopt - it'll serve well for the purpose of this demonstration.

It'll iterate through the dataframe line by line (with a lookback window of 500) - and only use the "very last" candle as signal - simulating behaviour live will show.


```python
def analyze_df_in_batches(f, window=500):

    @wraps(f)
    def wrapper(df, *args, **kwargs):
        lines = []
        for i in range(len(df) - window):
            slice = df[i:i + window]
            res = f(slice, *args, **kwargs)
            lines.append(res.iloc[[-1]])

        return pd.concat(lines)

    return wrapper
```


It'll be VERY slow (the populate method is called `candle_nr - 500` times - so your "peak detection" will be called this many times) - but will emulate live "candle analysis" behaviour as much as possible.

best use it on a short timerange - and only on one pair you know should make trades in the timerange.

**Comment by winginitau** [comment]
Thank you so much @xmatthias. I will explore this in detail over the weekend and come back with my learnings. I understand your point on the 3 candle settle-down. I'll look at the zigzag code again to see if is doing that. My simplistic requirement (and I've started coding this myself) is that a peak (+ve) is detected when (candle[-2].close >= up-threshold-change-from-last-peak) and (candle[-1].close < candle[-2].close). Similarly in the -ve form. Optionally with a tolerance (which complicates the code). Edge cases to be handled: opening pivot; zero value (for a strict peak-peak signal detection, ie not just +ve asset value); and consecutive candle swing from exceeding +ve threshold to exceeding -ve threshold (and the opposite). TBD is to mark the peak on candle[-2] and detect with shift(1) or mark it on candle[-1] (ie most recent) for buy/sell detection one candle past peak. Regardless it would be deterministic and the information would be available asap (1 candle) after the peak for trade action in live. After protoyping in python I'll dust off my C skills and learn cython for a performance version. Thoughts?

**Comment by winginitau** [comment]
Oh. :) On third revision of my own peak/valley analysis code and I'm seeing the issues as you described. And gaining increasing respect for the fundamentalists! :)

**Comment by winginitau** [comment]
Apologies @xmatthias my python decorator knowledge is insuffient to work out how to use the above code. If I decorate populate_indicators with @analyze_df_in_batches I get errors about name "wraps" not being defined.

**Comment by xmatthias** [comment]
you can just import it with `from functools import wraps`.

a good editor will help you doing that (vscode + python extension, pycharm)... as it's a pretty standard import ;)

**Comment by winginitau** [comment]
Self taught python, lots of knowledge gaps. Using pydev eclipse plugin (and mostly ignore its suggestions as there seems to be waaay too many. Brainless on decorators - even after some online tutorials, no idea why you are decorating the wrapper itself (and with an (f) argument). Answers to those obviously not for here, but would still appreciate some explicit direction on usage. Where am I placing this function (and its interal wrapper)? Currently have it outside populate_idicators and am decorating as follows:
```
    @analyze_df_in_batches
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
```
Which is breaking.....

**Comment by xmatthias** [comment]
using `@wraps(f)` is just a convention - making sure the docstring remains correct.
You could safely remove it, too.
Your usage doesn't appear wrong at first glance - what's the error you get?

**Comment by winginitau** [comment]
for i in range(len(df) - window):
TypeError: object of type 'Dev1StrategyBuild' has no len()

**Comment by xmatthias** [comment]
ah - then change `def wrapper(df, *args, **kwargs):` to `def wrapper(_, df, *args, **kwargs):`.
it's a instance method, so the first argument is the strategy object itself.

as said, it's an idea, nothing even remotely finished.

**Comment by winginitau** [comment]
done. 

res = f(slice, *args, **kwargs)
TypeError: populate_indicators() missing 2 required positional arguments: 'dataframe' and 'metadata'

apologies, just dont have a mental model for decorator calls....

**Comment by winginitau** [comment]
ok, this works.... but now trying to work out where I tap into the pd.concat(lines) return..... (as I don't know whats calling populate_indicators.....
```    
    def analyze_df_in_batches(f, window=500):

        @wraps(f)
        def wrapper(_, df, meta):
            lines = []
            for i in range(len(df) - window):
                slice = df[i:i + window].copy()
                res = f(_, slice, meta)
                lines.append(res.iloc[[-1]])
            return pd.concat(lines)

        return wrapper

    @analyze_df_in_batches
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
```

**Comment by xmatthias** [comment]
> `res = f(_, slice, meta)`

This does.

---

the point here is:
during backtesting - `populate_indicators` is called exactly nonce.
Now this decorator will take the dataframe, slice it into pieces a 500 (shifting by 1 candle at a time) - calculate the indicators for everything - and then use the very last candle of this (just as live would).

So i'm not sure where you'd want to tap in ... just run backtesting with this (and be patient) - if there's no trades, then there will be no trades in live either.

**Comment by winginitau** [comment]
Right! ok. Many thanks, fully understrood now. I'll hold off hacking interface and backtesting code. 

Possibly relevant: aside from the decorator calling args (fixed in the wrapper code above). I included a .copy() on tjhe slice. otherwise, without the .copy() i get the following for every indicator:
```
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['zigzag'] = pd.Series(cust_pivots)
/home/user/freqtrade/user_data/strategies/Dev1StrategyBuild.py:287: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
```
Assumung the sliced copy will get returned, rather than the whole frame, not sure if this will break the backtesting logic... ? Should I ignore the warnings or will the .copy() be ok?

Incidentally, the debugging integration under eclipse with pydev on linux does not look into decorators. ie. a breakpoint set on the wrapper code (or even in the decorator def with a superfluous _blah=1+1) does not trigger an interactive debug session. What IDE environment do you use @xmatthias? Is it normal for debug wrappers not to see into python3 decorator code?

**Comment by xmatthias** [comment]
copy won't matter - it's probablyb etter to copy - but i'm not sure that'll make much difference.

i'm using vscode. if you set a breakpoint - then it should also be hit if that line is executed, - no matter if it's in a decorator or not (a decorator is just syntactic sugar, really, there would be other ways to accomplish the same, too).

**Comment by winginitau** [comment]
Wow Microsoft gone open source! Well free at least ... not sure how open the github resource is. Windows or linux?

Re backtesting runs: without analyze_df_in_batches it makes profit. With decorator on: zero as expected (with and without .copy()). 

Hey a real big thanks for following this one down the rabbit hole with me. 

I ended up cludging a bunch of debug prints into populate* - filtering last 10 or so on dataframe - which is where I first discovered the peak/valley inidcators popping into existence further back in the frame. Horrible process just sitting watching repeat dumps until the live data triggered the conditions etc. webUI just confirmed it visually. 

Happy to continue being your test on the decorator if you want to continue development on the idea - certainly an option to run backtesting in live simulation would be useful, and to prune out the myraid future looking strategy questions.

Thanks again!

**Comment by xmatthias** [comment]
> Happy to continue being your test on the decorator if you want to continue development on the idea - certainly an option to run backtesting in live simulation would be useful, and to prune out the myraid future looking strategy questions.

Maybe at a later point - i've written this about a year ago iirc - but it's unfinished and usage is pretty painful if you don't know what to look for (as you've also encountered).

If any, it should not be a decorator, but a builtin functionality - but i never got around to this so far.

anyway, happy i could help you identify the problem.

**Comment by TheJoeSchr** [comment]
> > Happy to continue being your test on the decorator if you want to continue development on the idea - certainly an option to run backtesting in live simulation would be useful, and to prune out the myraid future looking strategy questions.
> 
> Maybe at a later point - i've written this about a year ago iirc - but it's unfinished and usage is pretty painful if you don't know what to look for (as you've also encountered).
> 
> If any, it should not be a decorator, but a builtin functionality - but i never got around to this so far.
> 
> anyway, happy i could help you identify the problem. 

@xmatthias 
using `analyze_df_in_batches` once again, I'm wondering, how far, if any, this builtin functionality has come. 

I would be willing to take it over and see how far I can run with it towards a PR, if you still got it lying around and haven't gotten around to it

**Comment by xmatthias** [comment]
it's never been a PR - and probably never will be.
the performance impact of it makes it near impossible to actually use.

**Comment by TheJoeSchr** [comment]
I see it as very valuable for debugging and/or as last step before going live. Kind of like timeframe-detail. But ideally with trades data. Better to run one long backtesting round than losing money

**Comment by TheJoeSchr** [comment]
> it's never been a PR - and probably never will be.
I meant that I would try to bring it to a form that's PR ready
