### ISSUE TITLE
Conflicting filename wit 1m and 1M for case insensitive filesystems

### ISSUE THREAD

**Issue by trocololo** [freqtrade/freqtrade#6591]
Hi,

When case insensitive filesystem is used, there is a conflict with filenames for 1 minute and 1 month historical data.

For example, filename "BTC_USDT-1m.json" and "BTC_USDT-1M.json" are the same when using Windows with NTFS.

Thanks

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

That's probably correct.
For the moment, the only thing you can do is to use a case sensitive filesystem, on windows most likely by using WSL2.

While we may fix this eventually at some point, it's unlikely it will be fixed quickly.
