### ISSUE TITLE
For backtesting how often was `populate_buy_trend()`  called ?

### ISSUE THREAD

**Issue by BourneSuper** [freqtrade/freqtrade#6605]
## Describe your environment
  * Operating system: ubuntu
  * Python Version:3.8.10
  * CCXT version: 1.74.63
  * Freqtrade Version: freqtrade develop
  
## Your question

For backtesting how often was `populate_buy_trend()`  called ?
It seems  that `populate_buy_trend()` is not called every timeframe.

**Comment by xmatthias** [comment]
`populate_buy_trend` will be called once per pair during backtesting, as documented in the [bot basics documentation](https://www.freqtrade.io/en/stable/bot-basics/#backtesting-hyperopt-execution-logic).

**Comment by BourneSuper** [comment]
How many timeframes are passed into `populate_buy_trend()`  in dryrun or live mode?

**Comment by stash86** [comment]
There will only be 1 dataframe that are passed to populate_buy/sell functions

If you have several timeframes, process them during populate_indicators function

**Comment by BourneSuper** [comment]
I mean how many rows of dataframe that are passed to populate_buy/sell functions

**Comment by xmatthias** [comment]
however many your timeframe specifies - and are available.

**Comment by BourneSuper** [comment]
> however many your timeframe specifies - and are available.

In backtesting it can be specified by the `--timerange` . And all  timeframes are passed and processed just once.
How about in live mode ? How many rows of dataframe that are passed to populate_buy/sell functions in live mode?
