### ISSUE TITLE
price_to_precision truncates price for FEG/USDT

### ISSUE THREAD

**Issue by SmartManoj** [freqtrade/freqtrade#6606]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 9aa821a9535784ab9d9ba109cf4526df3f320b60(`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

[FEG/USDT](https://www.gate.io/trade/FEG_USDT) has 12 digit in decimal part. The following function truncates to 10 digit.
https://github.com/freqtrade/freqtrade/blob/9aa821a9535784ab9d9ba109cf4526df3f320b60/freqtrade/exchange/exchange.py#L527-L550

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
You can easily work around this for now by either blacklisting this pair, or by using a [pricefilter](https://www.freqtrade.io/en/stable/plugins/#pricefilter) to set a minimum price.

it's an edge-case for sure - but coins this low-priced are usually disappearing soon.

Even with the rounding in this method increased, i'm not sure freqtrade will handle coins with more than 10 decimals without problems, so adding support for such low-priced coins will most likely not be a one-line fix - or at least not something where we can guarantee it'll work after fixing this method.

**Comment by xmatthias** [comment]
This is not an issue that we will be able to solve quickly (if at all).

Already the precision is problematic - trying to convert this to decimal results in a odd rounding error.

```
In [1]: from decimal import Decimal

In [2]: Decimal(1e-12)
Out[2]: Decimal('9.9999999999999997988664762925561536725284350612952266601496376097202301025390625E-13')
```

Trying to convert the calculation to use Decimals (to kindof support this level of precision) yields unexpected results - rounding numbers it shouldn't (from 0.000000003483 to 0.000000003484).

Therefore please consider coins with a precision > 1e-10 as currently unsupported by freqtrade.

I'll probably add a note about this to the documentation - as well as the workaround with pricefilter as explained above.

This won't mean we'll never support this - but definitely not short-term. As such - it's a `won't fix` for the moment.

**Comment by samgermain** [comment]
[CCXT is gradually making the transition away from floats](https://github.com/ccxt/ccxt/issues/522)

@xmatthias will freqtrade require any sort of customization once it's completely switched over?

**Comment by xmatthias** [comment]
I'm aware of this - but in my understanding, this is quite far from finished, and not something we can or should currently rely on (the property to switch the mode is not part of the ccxt documentation last time i checked).

Obviously it'd be a huge breaking change should ccxt suddenly start returning strings instead of decimals - but i doubt this will be a breaking change, at max, the default will change - which would have us revert it back for the time beeing.

It's also not a ccxt bug (this is not something that needs fixing in CCXT) - therfore the ccxt label is inappropriate.

i'm however aware of this - and i'm also aware of the Precise class in ccxt - which would be a requirement to support such low numbers.
