### ISSUE TITLE
KeyError: 'dry_run_sell_1648513504.349602'

### ISSUE THREAD

**Issue by tef-github** [freqtrade/freqtrade#6609]
develop branch

```
  File "/root/workspace/freqtrade/freqtrade/exchange/exchange.py", line 741, in fetch_dry_run_order
    order = self._dry_run_open_orders[order_id]
KeyError: 'dry_run_sell_1648513504.349602'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/workspace/freqtrade/freqtrade/freqtradebot.py", line 966, in check_handle_timedout
    order = self.exchange.fetch_order(trade.open_order_id, trade.pair)
  File "/root/workspace/freqtrade/freqtrade/exchange/common.py", line 125, in wrapper
    return f(*args, **kwargs)
  File "/root/workspace/freqtrade/freqtrade/exchange/exchange.py", line 887, in fetch_order
    return self.fetch_dry_run_order(order_id)
  File "/root/workspace/freqtrade/freqtrade/exchange/exchange.py", line 746, in fetch_dry_run_order
    raise InvalidOrderException(
freqtrade.exceptions.InvalidOrderException: Tried to get an invalid dry-run-order (id: dry_run_sell_1648513504.349602). Message: 'dry_run_sell_1648513504.349602'
```

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

Develop branch is NOT a version, but a moving target that can (and will) change regularily, sometimes multiple times per day.
As such, i'll have to consider this as being an outdated, or potentially modified version.

---

Also - a restart will reset open dry-run orders - so the error would go away and a new order will be opened.

It's still questionable why this happens - but the truncated log will not tell this - for that a more extensive log (containing a lot more messages prior to the actual exception) will be needed to further investigate.

**Comment by xmatthias** [comment]
Closing as this lacks further information.

Feel free to comment below / reopen if you are able to provide more information to help us investigate this issue further.
