### ISSUE TITLE
How to force exclusive orders for each pair?

### ISSUE THREAD

**Issue by mllamazares** [freqtrade/freqtrade#6611]
## Describe your environment

  * Operating system: Linux 5.10.63-v7l+ armv7l GNU/Linux (inside Docker)
  * Python Version: Python 3.9.9 
  * CCXT version: ccxt==1.76.65 
  * Freqtrade Version: freqtrade 2022.3
 
## Your question

My strategy has _different_ thresholds for buy and sell. Then, the buy signal is triggered several times before the sell signal. 

I want to omit the rest of the buy signals until I sell the current open trade. In other words, I want to force exclusive orders for each pair.

I've thought about the following workarounds (but I would like to know what's the best practice):

1. Using [the storing information approach](https://www.freqtrade.io/en/stable/strategy-advanced/#storing-information). Inside the `populate_buy_trend` I would check if `self.metadata['open_trade']` is True at the top, if not, I would execute the rest of the code and I'd set that variable if applies. 
2. [Querying the freqtrade database](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-trades) inside the `populate_buy_trend` function to check if there are any trades open for the current pair.

This is what the chart looks like:

![image](https://user-images.githubusercontent.com/5461023/160573056-a5c84ffc-ddef-4e46-9aad-9d5105950c6b.png)

This is the current code:
```python
def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
    dataframe.loc[
        (
            (qtpylib.crossed_below(dataframe['rsi'], 30)) &  # Signal: RSI crosses below 30
            (dataframe['volume'] > 0)  # Make sure Volume is not 0
        ),
        'buy'] = 1

    return dataframe

def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
    dataframe.loc[
        (
            (qtpylib.crossed_above(dataframe['rsi'], 70)) &  # Signal: RSI crosses above 70
            (dataframe['volume'] > 0)  # Make sure Volume is not 0
        ),
        'sell'] = 1
    return dataframe
```

**Comment by xmatthias** [comment]
Freqtrade does only allow one open trade per pair - so if you're in a trade for this pair, further buy signals will be ignored. This is implicit behavior and not optional.

If it's about cross-pair locking (you only want one open trade at any time) - then best use `max_open_trades=1`

**Comment by mllamazares** [comment]
Thanks for the clarification, @xmatthias! Then I find the preloaded chart a little confusing since some of those entries that I highlight would not be executed because of the restriction you've pointed out.

**Comment by xmatthias** [comment]
which "preloaded chart" are you talking about? 

your screenshot is showing buy signals (and sell signals) - but no trades.

**Comment by mllamazares** [comment]
By "preloaded chart" I mean the chart that you see in /trade by clicking on a crypto pair. It shows the buy and sell signals, and I interpreted them as "potential trades that would have taken place". However, it's also interesting to see when the signal is triggered, plus you've confirmed that freqtrade just processes one order per pair. So fair enough. Thanks again!
