### ISSUE TITLE
How to get always last candle in adjust_trade_position?

### ISSUE THREAD

**Issue by devilsinthedetail** [freqtrade/freqtrade#6612]
I am using a strategy which adjusts buy using adjust_trade_position and I want to access the candle from which the last buy occured, and not only the initial buy. 

I have found [this](https://www.freqtrade.io/en/stable/strategy-advanced/#dataframe-access) to get the last candle, but this only works for the first buy order. How would I get the candle for the always last executed buy order? I tried
`filled_buys[0].open_date_utc` 
but the adjusted trade order does not seem to have an open_date_utc field. Any ideas how to do this? Thank you.

Edit: Sorry just noticed there is a field called order_date. Is it correct to use this?
```python
trade_date = timeframe_to_prev_date(self.timeframe, filled_buys[-1].order_date)
trade_candle = dataframe.loc[dataframe['date'] == trade_date]
```

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

it would work in theory  but will fail in practice as the dates would have a missaligned timezone (in live), so you'd have to replace the timezone with utc yourself.

A better way is to use `order_date_utc` (which does exist on the order object).

You might also want to be careful with naming - calling it `trade_date` might be missleading.
Please also handle "no candle found" cases to avoid crashes. 
During the "new entry" candle (and once you reached the candle threshold) - you might not get a row back from the dataframe.
