### ISSUE TITLE
hyperopt Do I have to generate all indicators data in the populate_indicators method?

### ISSUE THREAD

**Issue by wrule** [freqtrade/freqtrade#6613]
## Describe your environment

  * Operating system: macOS
  * Python Version: 3.9.10
  * CCXT version: 1.73.70
  * Freqtrade Version: freqtrade 2022.2.1
  
## Your question

https://www.freqtrade.io/en/stable/hyperopt/#optimizing-an-indicator-parameter
In the example provided in the documentation, I found that method populate_indicators uses for in to generate all the indicator columns in the dataframe.

`    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """Generate all indicators used by the strategy"""

        # Calculate all ema_short values
        for val in self.buy_ema_short.range:
            dataframe[f'ema_short_{val}'] = ta.EMA(dataframe, timeperiod=val)

        # Calculate all ema_long values
        for val in self.buy_ema_long.range:
            dataframe[f'ema_long_{val}'] = ta.EMA(dataframe, timeperiod=val)

        return dataframe`

And I need to optimize the SRSI indicator, SRSI input four parameters to generate two columns.

Because SRSI is not a one-to-one relationship like EMA, So I don't know how to exhaustively enumerate the four parameter spaces of SRSI and store them in the columns of the dataframe.In fact I don't have that much memory to store millions of dataframe columns.

Can the required columns be generated on demand just before one round of backtesting? Where should I put the on-demand column code if this feature is already supported?

thanks.

**Comment by devilsinthedetail** [comment]
You can implement it directly in the populate_buy_trend function, just use `self.buy_ema_short.value` wherever needed. Note though that this will result in a longer backtesting time, but less memory consumption than generating all data across all parameters in populate indicators.

**Comment by xmatthias** [comment]
As the above is a perfect answer - i'll assume this as answered :+1: 

Thanks a lot for jumping in and helping @devilsinthedetail :100:
