### ISSUE TITLE
How to use unlimited stake amount with unlimited trades?

### ISSUE THREAD

**Issue by mllamazares** [freqtrade/freqtrade#6616]
## Describe your environment

- Operating system: Linux 5.10.63-v7l+ armv7l GNU/Linux (inside Docker)
- Python Version: Python 3.9.9
- CCXT version: ccxt==1.76.65
- Freqtrade Version: freqtrade 2022.3

## Your question

I want to split the total portfolio balance into the number of currency pairs that trigger a buy signal.
This is the desired behaviour:
* 1 buy signal -> 100% portfolio
* 2 buy signals -> 50% each
* 3 buy signals -> 33.33% each
* ...

According to the documentation, I need to set three parameters:
1. [**max_open_trades**](https://www.freqtrade.io/en/stable/configuration/#configuring-amount-per-trade): Number of open trades your bot is allowed to have. Only one open trade per pair is possible, so the length of your pairlist is another limitation that can apply. If -1 then it is ignored (i.e. potentially unlimited open trades, limited by the pairlist).
2. [**dynamic_stake_amount**](https://www.freqtrade.io/en/stable/configuration/#dynamic-stake-amount): Amount of crypto-currency your bot will use for each trade. Set it to "unlimited" to allow the bot to use all available balance.
3. [**tradable_balance_ratio**](https://www.freqtrade.io/en/stable/configuration/#dynamic-stake-amount): Ratio of the total account balance the bot is allowed to trade.

I think the logical config should be the following:

```json
{
    "max_open_trades": -1,
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    ...
```

However, it raises the following error:
```
freqtrade.exceptions.OperationalException: `max_open_trades` and `stake_amount` cannot both be unlimited.
```

Then, I see two possible workarounds:
1. Set `max_open_trades` to 5. However, if just one signal is triggered, it will just use 20% of the total balance.
2. Set a fixed `stake_amount` to 200. However, if the size of my portfolio is big enough, eventually, I would end up not using 100% of the balance.

So is there an alternative approach to putting 100% of my money working? What's your take on this dilema?

I've seen that this has been briefly addressed by @xmatthias on https://github.com/freqtrade/freqtrade/issues/5758#issuecomment-947329434

> well it's intended this way - stake-amount cannot be unlimited when max-open-trades is unlimited, as then we'd have no reference to trade size.

I think that's because the orders are processed async, but if we add an extra step that waits for all the calculations, we could set the trade size accordingly. Something like:
1. New candle is completed (`process_only_new_candles` set to true).
2. Populate indicators and buy signals for each pair asynchronously.
3. Once all of them have finished, get the N number of buy signals.
4. Fetch the total portfolio balance and divide it by N (ideally, we could also set `max_open_trades`).
5. Send the buy orders to the exchange with the corresponding calculated amount.

**Comment by xmatthias** [comment]
I think you're missing/forgetting the time component in your concept.

You're assuming that 1-5 trades are entered on the same candle. 
While possible in theory - that's happening VERY rarely on most decent strategies.
If you now assume an average holding time of 5-10 candles - then you entered with 100% capital on the very first signal (either on one pair, or on 5 pairs).
You're now blocked for the duration of these trades - as your capital is maxed out (no capital left).

usually, you might have 1 signal at 10:00, and one at 11:00. If you enter with 100% of the capital on the 10:00 trade, you'll miss the 11:00 trade of the other pair completely (there's no capital left).

Entry signals on different pairs should therefore be treated independently.

---

`process_only_new_candles ` will guarantee that processing will only run once per pair.
It'll however not guarantee that this will happen on the same bot iteration, so even if you look at "all" signals at the end of the loop - you're not guaranteed that 100% of the pairs got the new candle yet (that's a timing problem, really - as candles do not always happen at 10:00:00, but sometimes at 10:00:01, depending on their volume etc...).

As such - a "wait for all signals to complete" step is pointless.

**Comment by mllamazares** [comment]
OK, that's a fair point. Maybe the solution is just to increase my pairlist size.
However, I'm afraid I still don't know exactly how the position sizing works. 

This is my current config:

```json
{
    "max_open_trades": 5,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "available_capital": 10000,
    ....
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [".*/USDT"],
        "pair_blacklist": [
            "BNB/.*",
            ".*UP/.*",
            ".*DOWN/.*",
            ".*BULL/.*",
            ".*BEAR/.*",
            ".*PREMIUM/.*",
            ".*PERP/.*"
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 100,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 3600,
            "lookback_timeframe": "1h",
            "lookback_period": 72
        },
        {
            "method": "AgeFilter",
            "min_days_listed": 10
        }
    ],
    ...
```

It has opened 3 trades with 33% each:
![image](https://user-images.githubusercontent.com/5461023/160809514-c69e0e39-588e-4f5b-913d-c66e04830fba.png)
![image](https://user-images.githubusercontent.com/5461023/160811536-43e4f803-4f54-4202-ba6a-bddccb987ccc.png)


According to your explanation, it would leave room for the rest of the potential trades, in this case, as `max_open_trades` is set to 5, it would assign 20% of the portfolio for each trade (not the 33%).

Also, as you can see in my config, `available_capital` is set to 10000, but Freqtrade just has a 1000 starting portfolio balance.

**Comment by mllamazares** [comment]
Thanks, that's a fair point. Maybe the solution is just to increase my pairlist size. 😄

**Comment by xmatthias** [comment]
Well nothing prevents you from using [custom-stake-amount](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stake-size) for custom sizing.

I'd however still recommend against 100% in one position - IF that goes against you (and you missed 3 winning opportunities in the meantime) you'll not be a happy trader...
