### ISSUE TITLE
Question to Trailing stoploss

### ISSUE THREAD

**Issue by thieme** [freqtrade/freqtrade#6621]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ 3.8.12
  * CCXT version: _____ ccxt==1.71.73
  * Freqtrade Version: ____ freqtrade 2022.1
  
## Your question
Hi, 

I have a question with respect to trailing stop loss. 

My config is:

"stoploss": {
      "stoploss": -1.0
    },
"trailing": {
      "trailing_stop": true,
      "trailing_stop_positive": 0.01,
      "trailing_stop_positive_offset": 0.011,
      "trailing_only_offset_is_reached": true
    }

- the bot buys an asset at a price of 100$
- the stop loss is defined at -1% meaning that it is set to 100%
- the stop loss would get triggered once the asset drops 0$
- stoploss will remain at 0$ unless asset increases to or above the configured offset
- assuming the asset now increases to 101.1$ (where I have the offset configured)
- the stop loss will now be -1% of 101.1$ = 100.11$
- if the value increase further the stoploss will be adjusted to be always be -1% of the highest observed price.

However, I observed an intersting thing during traiding BNB/EUR on binance.

yesterday it was:

*Trade ID:* 20 (since a month ago)
*Current Pair:* BNB/EUR
*Amount:* 0.386 (146.0238 EUR)
*Open Rate:* 378.3000000
*Current Rate:* 396.800000
*Current Profit:* 4,73%
*Inital Stoploss:* 379.2690000 (-1.00%)
*Stoploss:* 399.0690000 (-1.00%)
*Stoploss distance:* 2.26900000 (0.57%)

today I reach: 

*Trade ID:* 20 (since a month ago)
*Current Pair:* BNB/EUR
*Amount:* 0.386 (146.0238 EUR)
*Open Rate:* 378.3000000
*Current Rate:* 389.600000
*Current Profit:* 2.83%
*Inital Stoploss:* 379.2690000 (-1.00%)
*Stoploss:* 400.85100000 (-1.00%)
*Stoploss distance:* 11.25100000 (2.89%)

In the meanwhile I had a profit of 7.8% but the trailing stoploss was not set properly or sold respectively. Where is my error? Why is the distance postitive and the Stoploss bigger than the Current Rate?

Thank you for the support.

Best,
Sebastian

**Comment by xmatthias** [comment]
Without logs, that's pretty difficult to determine reliably - so most of the below will be guessing.

As stoploss did not trigger i see  2 possibilities, either you use stoploss_on_exchange - and the offset to the limit order (`stoploss_on_exchange_limit_ratio`) was too small, so your stoploss was missed (this should be quite noisy in the logs - at least around the time this happened).

Alternatively, you're using the `confirm-trade-exit` callback, which is preventing the stoploss from being placed.

The logs should contain information about both occurances.

**Comment by thieme** [comment]
Hi,

thank you for the fast answer. I figured out, that the issue is, that the amount differs somehow. In the DB the amount is 0.368 but on binance it is 0.366. Explaining also the weird behavior. This might be because of an delay between buy order and the order execution. Would it be meaningful to compare the DB entry with the balance in the wallet after buy execution? This would avoid such issues.

Thank you for your help.

Best,
Sebastian

**Comment by xmatthias** [comment]
that's happening either due to a partially filled order (should be handled properly) - or due to fees (should also be handled properly).

To further investigate this, we'll need the logs from when the order filled (and a little after that), as well as the entries for this trade from the database (basically the output of the following command):
```
freqtrade show-trades --print-json --trade-ids 20
```

you may need to specify the database file explicitly if you're not using the default database name.

**Comment by thieme** [comment]
Hi,

thanks a lot. I have currently no access to the bot itself, but will post the information as soon as I have it. Thanks a lot.

Best,
Sebastian

**Comment by xmatthias** [comment]
Any news? or did this somehow solve itself? ;)

**Comment by xmatthias** [comment]
I'll assume that you've been able to figure this out.

Feel free to comment below / reopen if that's not the case.
