### ISSUE TITLE
Telegram bot - Unrealized profit, daily profit, performance, ROI

### ISSUE THREAD

**Issue by straj-granicy** [freqtrade/freqtrade#6631]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hi everyone.
Just started to run my first strategy (it runs for 5 days) and have some questions about how the performance of bot and profits/balance etc. are displayed in the bot.
So as for now the total performance looks like this

Performance:
1.  TKO/USDT 1.306 USDT (2.62%) (1)
2.  COS/USDT 1.096 USDT (2.19%) (1)
3.  ACM/USDT 1.008 USDT (2.05%) (1)
4.  ALPACA/USDT 0.882 USDT (1.77%) (1)
5.  MITH/USDT 0.731 USDT (1.46%) (1)
6.  UMA/USDT 0.675 USDT (1.37%) (1)
7.  OGN/USDT 0.593 USDT (1.20%) (1)
8.  FIRO/USDT 0.506 USDT (1.03%) (1)
9.  CVC/USDT 0.462 USDT (0.93%) (1)
10.  GTO/USDT 0.449 USDT (0.90%) (1)
11.  SAND/USDT 0.180 USDT (0.38%) (1)
12.  AUTO/USDT 0.162 USDT (0.33%) (2)
13.  ARDR/USDT 0.121 USDT (0.24%) (1)
14.  SUSHI/USDT 0.082 USDT (0.17%) (1)
15.  SUN/USDT 0.079 USDT (0.16%) (1)
16.  DCR/USDT 0.055 USDT (0.11%) (1)
17.  FORTH/USDT 0.029 USDT (0.06%) (1)
18.  PERL/USDT 0.027 USDT (0.05%) (1)
19.  OXT/USDT 0.020 USDT (0.04%) (1)
20.  ONT/USDT 0.010 USDT (0.02%) (1)
21.  MBL/USDT 0.008 USDT (0.02%) (1)
22.  ASR/USDT 0.000 USDT (0.00%) (1)

And daily profit looks like this:

Daily Profit over the last 7 days:
Day         Profit USDT    Profit USD    Trades
----------  -------------  ------------  --------
2022-04-03  0.000 USDT     0.000 USD     0 trades
2022-04-02  1.074 USDT     0.000 USD     5 trades
2022-04-01  1.032 USDT     0.000 USD     3 trades
2022-03-31  3.770 USDT     0.000 USD     8 trades
2022-03-30  1.569 USDT     0.000 USD     5 trades
2022-03-29  1.035 USDT     0.000 USD     2 trades
2022-03-28  0.000 USDT     0.000 USD     0 trades

So from the first glance it looks not really bad for the first strategy, but. 
The total profit after 5 days should be 8.479 USDT acc to /profit command

ROI: Closed trades
∙ 8.479 USDT (0.74%) (8.01 Σ%)
∙ 0.000 USD
ROI: All trades
∙ 2.287 USDT (0.19%) (2.16 Σ%)
∙ 0.000 USD
Total Trade Count: 25
First Trade opened: 4 days ago
Latest Trade opened: 7 hours ago
Win / Loss: 23 / 0
Avg. Duration: 4:31:48
Best Performing: TKO/USDT: 2.62%

But as my balance on Binance didn't change in this way, I'd like to ask you to specify how to interpet the table above? What figure shows the real profit?

Moreover, as I started to look thrugh all the sells, I noticed the phrase "Unrealized profit" and couldn't find the information about it in documentation (if the information exists, please give the link).

Moreover, I decided to check the profit of all trades. And the result surprized me. The thing is that figures in daily profit don't match with the figures, which I got after some math.
E.g. I'll show the figures on 2022-03-30  

2022-03-30  1.569 USDT     0.000 USD     5 trades
The total profit should be 1.569 USDT.
But when I did made calculations the result was -0.05 USDT.
Is this possible?

P.S. I don'ts say that Freqtrade is lying. You software is fantastic and I'm just starting to learn and to use it. But it would be great to find out my situation.

Thanks in advance for assistance.

**Comment by xmatthias** [comment]
> 2022-03-30 1.569 USDT 0.000 USD 5 trades
> The total profit should be 1.569 USDT.
> But when I did made calculations the result was -0.05 USDT.
> Is this possible?

Without more details on what your calculation is based - i'd assume your assumptions for the calculation are wrong.

daily profit accounts for sells that closed on that day. If a trade opened on that day, it'll NOT counted towards this.

Your "final profit" on binance will also not be 8$ - but 2$ (you've apparently got some trades open which are quite negative).

The "unrealized" part is simply because your message is when the sell order is placed - not when it's filled (there's a separate notification for that). As the order could also time out / be canceled - it's considered unrealized until it's actually filled.

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear, or if you're able to provide some details on how you did the "validating" calculations.
