### ISSUE TITLE
How to slow down bot executing frequency

### ISSUE THREAD

**Issue by BourneSuper** [freqtrade/freqtrade#6634]
## Describe your environment

* Operating system: ubuntu
* Python Version:3.8.10
* CCXT version: 1.74.63
* Freqtrade Version: freqtrade develop
  
## Your question

I want to slow down bot executing frequency. 
For example I use **timeframe ='1h'**, and I don't want bot to run `populate_buy_trend()` in very short time . If bot can run `populate_buy_trend()` in every 10min , that's ok.
I tried to configure `internals.process_throttle_secs`, but it seems not a right configuration item.

**Comment by stash86** [comment]
set process_only_new_candles to true, then populate_ functions would only be run when a new closed candle available

**Comment by stash86** [comment]
I strongly recommend you to read the entire docs. But for the part you asked, it's here https://www.freqtrade.io/en/latest/configuration/#configuration-parameters

**Comment by BourneSuper** [comment]
> process_only_new_candles

Thinks. I read docs for at 5 times, but there is a lot of stuffs and hard to grab
