### ISSUE TITLE
 TypeError: populate_indicators() missing 1 required positional argument: 'metadata'

### ISSUE THREAD

**Issue by Elmata2** [freqtrade/freqtrade#6637]
## Describe your environment

  * Operating system: windows
  * Python Version: _____ (`python -newest`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
When i am using this docker-compose run freqtrade hyperopt --config /freqtrade/user_data/config.json --hyperopt-loss SharpeHyperOptLoss --strategy BBRSINaiveStrategy -e 500 --spaces all in mine cmd i get this error
![image](https://user-images.githubusercontent.com/100527759/161441197-019a5f07-9a2b-42e3-b7f7-efb6a65acf60.png)
I followed everthing but i dont know how to help this issue? could you maybe help me? On mine github acc is also the repo for this, so you could look at that to
[https://github.com/Elmata2/Algo-trading](url)

**Comment by xmatthias** [comment]
Your strategy seems to use a mix of old (using the buy_generator approach)  and new syntax (using  - which is clearly not supported).

Please follow the [hyperopt documentation](https://www.freqtrade.io/en/stable/hyperopt/) for this implementation - and remove all legacy code (e.g. `buy_strategy_generator()` - but there's for sure others).


I'd suggest to restart with the strategy - and only move things to your new file which is also documented as such - that's probably the fastest way.

**Comment by Elmata2** [comment]
Do you suggest to start completely over or alone with the hyperopt section? Therefore the hyperopt dataset need to be in the normal strategy right?

**Comment by xmatthias** [comment]
You can try and remove sections related to hyperopt - but the strategy seems to be a mix between old and new hyperopt syntax/methodology, and if you're uncertain with that, the best way will be to start from a working strategy - and work through the hyperopt documentation.

**Comment by Elmata2** [comment]
He man thanks again, you can close this one

**Comment by xmatthias** [comment]
as author of issues, you can also close the issues yourself once they're done ;)
