### ISSUE TITLE
quick question AttributeError: 'tuple' object has no attribute 'space'

### ISSUE THREAD

**Issue by Elmata2** [freqtrade/freqtrade#6638]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
![image](https://user-images.githubusercontent.com/100527759/161447423-028bfb1d-321a-4c64-94a7-3c926fc2a7e8.png)
that is the error i keep on getting
![image](https://user-images.githubusercontent.com/100527759/161447448-e0c4fabf-4f3a-4d09-9f84-c4078ab04f17.png)

this is my new self made code but i know it had something to do with the range of values(5 to 50) but i cannot find a quick en discreet answer of how i need to transform my code. could you please help me agaain?

**Comment by xmatthias** [comment]
Please avoid using screenshots of code or text, but use tripple backticks (`) and copy code into the issue.

Your issue is quite simple - by having a trailing `,` in your line - python takes this as a tuple.

Remove the trailing comma in the "parameter definition" lines to fix this problem.
