### ISSUE TITLE
Pair XXX is not available at XXX

### ISSUE THREAD

**Issue by macd2** [freqtrade/freqtrade#664]
* Python Version: 3.6 (`python -V`)
  * Branch: Develop

  Since now that the bot supports many exchanges with many different coins, I propose that the bot does not stop when when getting this error:
Pair XXX/BTC is not available at EXCHANGE-NAME

I propose to just ignore the pair and maybe dumb a file which contains all pairs that are not supported at the particular exchange. 

But especially for back testing it is a pain in the *** to adjust the pair-list manually all the time.

**Comment by shusso** [comment]
feel free to re open if not fixed already
