### ISSUE TITLE
"not every buy signal generates a trade" - Why?

### ISSUE THREAD

**Issue by ma-lalonde** [freqtrade/freqtrade#6649]
This statement can be found in [plotting.md](https://github.com/freqtrade/freqtrade/blob/develop/docs/plotting.md).
I understand there may be some reasons why a trade won't execute:
- When there is already an open trade;
- When the maximum number of open trades is reached;
- If there is a sell signal on the same candle.

What are the other possible reasons? While plotting, I see many "enter_long" and "enter_short" arrows, and none of the previously mentioned reasons seem to explain why the bot is not opening a trade. See below, where I'm backtesting for BTC/USDT on 15 minutes timeframe with the latest progress on 'develop' branch:
![image](https://user-images.githubusercontent.com/52324318/161666260-25133d4d-35d5-4d43-a3be-5f366db28808.png)

We can see the bot taking both short and long positions from time to time, but ignoring most signals. 

I could not find why no trade is opened in these cases in the docs or by searching the previous issues here on github, which surprises me since apparently it is somewhat expected. Maybe I'm not using the right words to describe my issue. Thanks for pointing me in the right direction - I'd be happy to collect answers here and add them to the documentation afterwards, if that has not already been done in a place I couldn't find.

**Comment by xmatthias** [comment]
unless you run backtesting with only this one pair - other pairs can always exhaust your trade slots.

Short signals will be ignored in spot markets (Although plotting will probably show them) - so without logs and more information it's difficult to tell if you're running this against futures or spot.
Also, backtesting is running separately (you run `freqtrade backtesting` - followed by `freqtrade plot-dataframe`) - so changes to the strategy in the meantime might reflect in the plot - but not in the trades.

Other advanced features (custom pricing, timeouts) can also affect this and attempt a trade (but not enter that) - but only if you're using this (backtesting results would show timed out trades).

The "signal covering" has however also changed slightly with the introduction of long/short - you can read about the [blocking collisions](https://www.freqtrade.io/en/latest/strategy-customization/#colliding-signals) in the documentation.

**Comment by ma-lalonde** [comment]
Thanks for answering so quickly. It turns out I made / saved modifications between the moment I ran backtesting and plot-dataframe. So that explains what I'm seeing and I'm left feeling dumb. After re-running both commands, the abnormalities disappeared. All entry signals left that do not generate trades are either due to a collision or to a trade already being in progress.
