### ISSUE TITLE
docker-compose pull stuck

### ISSUE THREAD

**Issue by iokbay** [freqtrade/freqtrade#6650]
## Describe your environment

  * Operating system: macOS 12.3.1
  * Python Version: 3.8.13
  * CCXT version: 1.77.36
  * Freqtrade Version: 2022.2.2
  
## Your question

docker-compose pulls be stuck randomize

```
(Test) iokbay@MacBook-Pro freqtrade % !992
docker-compose pull
[+] Running 7/11
 ⠴ freqtrade Pulling                                                    1211.4s
   ⠿ a2abf6c4d29d Already exists                                           0.0s
   ⠿ 27003db43ed4 Already exists                                           0.0s
   ⠿ eba080ca5a70 Already exists                                           0.0s
   ⠿ 00ceeca3d803 Already exists                                           0.0s
   ⠿ 8980b900ecd2 Already exists                                           0.0s
   ⠿ 3f82f48e4e50 Already exists                                           0.0s
   ⠿ d6762658abf3 Already exists                                           0.0s
   ⠴ d83e81a2f868 Downloading      5.389MB/81.4...                      1209.3s
   ⠴ 61e34f50eda5 Download complete                                     1209.3s
   ⠴ 667cdd5faa29 Download complete                                     1209.3s
```

**Comment by xmatthias** [comment]
Please also avoid creating duplicate issues (https://github.com/freqtrade/technical/issues/259) - also cross-project.
The response you get won't significantly change unless the information provided changes.

---

sometimes it helps to restart the pull.

it's however not something we can assist you with, as it's related to either your docker installation - or your network (causing the download to abort).

**Comment by iokbay** [comment]
I can't restrart but pulling complete succesfully.
```
(Test) iokbay@MacBook-Pro freqtrade % docker-compose pull restart
no such service: restart

```

**Comment by iokbay** [comment]
I can't restrart but pulling complete succesfully.

**Comment by xmatthias** [comment]
so if pulling completed successfully, then this issue is solved ?
