### ISSUE TITLE
Account Drawdown is not calculated correctly if drawdown is at start of simulation

### ISSUE THREAD

**Issue by nicolaspapp** [freqtrade/freqtrade#6655]
## Describe your environment

  * Operating system: Windows 10
  * Python Version:  Python 3.8
  * CCXT version: 1.57.38
  * Freqtrade Version: develop-973107c
 
## Describe the problem:

When a strategy start on loss, that initial loss doesn't seem to be counted for the account drawdown calculation
Simulation conditions: 
Initial Balance = 1000 USDT 
Minimal Balance = 496.588 USDT (50% drawdown)
Accused Drawdown = 9%

```
 =============== SUMMARY METRICS ================
| Metric                 | Value               |
|------------------------+---------------------|
| Backtesting from       | 2019-01-01 00:00:00 |
| Backtesting to         | 2021-09-30 23:55:00 |
| Max open trades        | 1                   |
|                        |                     |
| Total/Daily Avg Trades | 617 / 0.62          |
| Starting balance       | 1000 USDT           |
| Final balance          | 12034.484 USDT      |
| Absolute profit        | 11034.484 USDT      |
| Total profit %         | 1103.45%            |
| Trades per day         | 0.62                |
| Avg. daily profit %    | 1.10%               |
| Avg. stake amount      | 1775.784 USDT       |
| Total trade volume     | 1095658.453 USDT    |
|                        |                     |
| Best Pair              | BTC/USDT 288.07%    |
| Worst Pair             | BTC/USDT 288.07%    |
| Best trade             | BTC/USDT 31.93%     |
| Worst trade            | BTC/USDT -13.74%    |
| Best day               | 1354.786 USDT       |
| Worst day              | -583.621 USDT       |
| Days win/draw/lose     | 194 / 574 / 236     |
| Avg. Duration Winners  | 18:34:00            |
| Avg. Duration Loser    | 8:49:00             |
| Rejected Entry signals | 0                   |
| Entry/Exit Timeouts    | 0 / 0               |
|                        |                     |
| Min balance            | 496.588 USDT        |
| Max balance            | 12034.484 USDT      |
| Drawdown (Account)     | 9.13%               |
| Drawdown               | 656.284 USDT        |
| Drawdown high          | 6191.971 USDT       |
| Drawdown low           | 5535.688 USDT       |
| Drawdown Start         | 2021-07-07 11:25:00 |
| Drawdown End           | 2021-07-17 04:10:00 |
| Market change          | 1065.27%            |
================================================
```

Attaching the profit plot for better visualization:

![image](https://user-images.githubusercontent.com/11711684/161794568-b2f3c732-7143-4fac-86ed-d7b3566ba680.png)

### Steps to reproduce:

  1. Have your strategy loose a lot of trades at first
  2. Pickup profit
  3. Observe drawdown at the end of the simulation
  
### Observed Results:

  * What happened? Drawdown accused was 9%, while my account was 50% under at some point
  * What did you expect to happen? My conception for drawdown is to be the loss you would initially have if you enter at the worst possible time. That, of course, could also happen with your initial stake before you start having any profits.

**Comment by xmatthias** [comment]
The calculation is using the maximum absolute loss (in your case 656$) - and calculates the percentage of it against the previous high (6191.971$). that'll come up to the 9% you're seeing.


I'm open to suggestions (or PR's) improving this behaviour - but i'm not sure what the correct behavior is.
I don't think absolute drawdown and relative drawdown should show 2 different drawdown periods - but i also don't think that the maximum absolute drawdown should be hidden (basically the 656$ - even though the 500$ you had before were bigger in relative terms).


A quick sample showing this could be the with the following profit numbers: (1000$ starting capital)
`[0, -500, 500, 10000, -1000]`.
The maximum drawdown used here will be 1000$ - even though the initial 500$ drawdown is the bigger in relative terms (it's drawdown of 50% after the 2nd step, while the 1000$ drawdown on the 11000$ account is only ~9%).

**Comment by nicolaspapp** [comment]
Oh I see. I think it depends on the way you are using the strategy. I normally set a starting capital an unlimited staking to compound earnings.
The problem of using absolute drawdowns in this cases is that drawdown will be tied to the point of your simulation where you get the latest "pullback" rather than how big that pullback is (in the case that the strategy is consistently making profits).

What do you think if we leave the relative drawdown as a measure for hyperopts and drawdown measurements and also add absolute drawdown as another metric?

**Comment by xmatthias** [comment]
well, we do have both absolute and relative drawdown already (as percentage and as absolute value).

If we have 2 drawdowns - then it needs to be crystal clear which one is which - and where we're using which drawdown metric.

**Comment by nicolaspapp** [comment]
I see. I have been looking at the code and it looks that `calculate_max_drawdown` might need some adjustments to calculate relative max drawdown on `profit_ratio`. Something like the following:
```
max_drawdown_rel = 0.0
if value_col == 'profit_ratio':
    max_drawdown_rel = (high_val - low_val)
elif high_val + starting_balance != 0:
    max_drawdown_rel = (high_val - low_val) / (high_val + starting_balance)
```
Either way I have been taking a little more though on this, and even though I like the idea of measuring account relative drawdown for optimizations, it seems a bit difficult to do with current implementation. Correct me if I'm wrong but `profit_ratio` seems to be rather Trade PNL and not portfolio PNL. Dividing that by `max_open_trades` could give a fair estimate, but will not be completely accurate in the case of a dynamic stake. Another better idea will be to have another column with the ratio according to stake when trade is closed (not sure if that is being done already)

I would like to hear your feedback on this since I am not very familiarized with the code yet. So far, It looks to me that drawdown optimizations would simply be better be done while having a "static stake" configuration even though that might not be the intended use case.

**Comment by xmatthias** [comment]
> calculate relative max drawdown on profit_ratio

Using `profit_ratio` is simply wrong. we used to use this in the past, and it's leading to very wrong results with dynamic stake.
obviously the calculation is easier with static stake - but simple is not fun :laughing: 

i think the "correct" value should be pretty easy to calculate:
* use absolute profit to calculate highs (and subsequent drawdowns) (so you have the underwater series).
* calculate the relative difference between each previous high and the subsequent low (basically the account drawdown calculation - but for every drawdown period)

Currently - we take the max of the absolute drawdowns to get the correct period - and calculate relative drawdown against prior high.
to get the biggest relative drawdow, we'd simply need to take the max of the above calculated relative differences.

with the basic example from above - you'd then have something like this:

```
[0,      -500,   500,  10000, -1000] # starting point
[1000, 500,  1000, 11000, 10000] # absolute results
[1000, 50%,  0%,   0%,       ~9%]   # Relative drawdowns
```

Currently - we pick profits from "absolute_results" (and derive the date from this).
The "relative" approach should pick from relative drawdowns (but they need to be calculated here, against the prior high - not `profit_ratio`).

I've not looked at this in detail (or rather, in code) so far - but i think it should be pretty straightforward to implement, maybe even just 1-2 lines of code.

**Comment by nicolaspapp** [comment]
ok gotcha. I can prepare the code and send you a PR when I get some free time for this approach.

Not sure what the best decision is regarding absolute/relative drawdowns in backtest metrics, but a HyperLoss calculation based on relative drawdown will definitely be useful. A relative drawdown underwater plot could also be interesting

**Comment by xmatthias** [comment]
That'd be great! :+1: 
I'm not against having both either - if you read carefully above - what i said is:

> If we have 2 drawdowns - then it needs to be crystal clear which one is which - and where we're using which drawdown metric.

And i stick to this - so we CAN have both - as long as we have the documentation clear on where which one is used.

**Comment by nicolaspapp** [comment]
@xmatthias I have a PR with some initial changes, please take a look at it and we'll iterate it until we are both happy with the changes.
