### ISSUE TITLE
Supported_fiat constant improvement

### ISSUE THREAD

**Issue by PseudoIoannes** [freqtrade/freqtrade#6657]
So you can work with fiats supported by coingecko but constant is missing few, I care only about UAH support so may there be extensions of this constant at least for UAH?

https://api.coingecko.com/api/v3/simple/supported_vs_currencies

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

In theory, there's nothing against adding missing currencies to the supported_fiat constant.
