### ISSUE TITLE
questions on controlling the bot

### ISSUE THREAD

**Issue by teboozas** [freqtrade/freqtrade#6660]
## Describe your environment

  * Operating system: 
  * Python Version: 3.8.12
  * CCXT version: ccxt==1.71.73
  * Freqtrade Version: freqtrade 2022.1
  
## Your question

Hi, I have some questions on controlling the bot:

- How long is the window size to apply strategies (especially for `1m` time frame)?
- Can I specify the length of the window size of dataframe to apply strategies?
- Is it possible to automatically put a specific pair to blacklist after the sell (or buy) signal occurred, and remove the pair from blacklist after pre-defined time length (e.g. 24h)?

**Comment by xmatthias** [comment]
you'll get something between 200 and 2000 candles. This varies greatly by exchange - and you cannot rely on the precise number to be available at all times, so make sure to also handle cases where you get a few missing candles (especially after exchange downtimes).
A common guideline is usually ~1000 (for binance).

You can define [`startup_candle_count`](https://www.freqtrade.io/en/stable/strategy-customization/#strategy-startup-period). Please familiarize yourself with the documentation (especially the warning boxes around this).


You can use [protections](https://www.freqtrade.io/en/stable/plugins/#protections) to prevent immediate rebuys. In your case, most likely the `CooldownPeriod` one.

You're also not using the very latest version, so make sure to use the correct version of the documentation to make sure that the features you read about are actually available in your version yet.
