### ISSUE TITLE
Cant close previous position and open new position in same candle

### ISSUE THREAD

**Issue by furkanbr** [freqtrade/freqtrade#6666]
## Describe your environment

  * Operating system: Mac
  * Python Version: 3.9.10
  * CCXT version: ccxt==1.77.98
  * Freqtrade Version: freqtrade docker-cbbbe8a5
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Im new to FT and trying to create basic MACD strategy. I want to make this for futures trading. Just want to trade with MACD indicator like when histogram cross below 0 open short position, when histogram cross above 0 open long position. But problem is when i create strategy this strategy, it cant make changes as i want. It only open and close short positions and there is no any long position at all. FT doesnt create something like close long position and open short position at same candle. 

### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs
This is end of my strategy;

```    
def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the entry signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with entry columns populated
        """
        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['macdhist'], 0)) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'enter_long'] = 1
        # Uncomment to use shorts (Only used in futures/margin mode. Check the documentation for more info)
        
        dataframe.loc[
            (
                (qtpylib.crossed_below(dataframe['macdhist'], 0)) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'enter_short'] = 1
        

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the exit signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with exit columns populated
        """ 
        dataframe.loc[
            (
                (qtpylib.crossed_below(dataframe['macdhist'], 0)) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'exit_long'] = 1
        # Uncomment to use shorts (Only used in futures/margin mode. Check the documentation for more info)
        
        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['macdhist'], 0)) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'exit_short'] = 1
        
        return dataframe```

**Comment by furkanbr** [comment]
<img width="1018" alt="Screen Shot 2022-04-09 at 01 00 26" src="https://user-images.githubusercontent.com/53065065/162537804-9576bf00-bac3-4275-8837-35608eb55e32.png">

This is how it looks like on backtesting, only short trades.

**Comment by xmatthias** [comment]
Freqtrade will only allow one position per pair at a time (so you can't be long and short at the same time).

It'll also auto-lock a pair until the end of a candle - to protect from buy/sell cycles (where the signal is still open, and you run into a stop again and again - so the earliest a position "switch" can happen is at the next candle (you sell at 10:00, enter the next position at 11:00 (one candle later)).

You may also wanna look at the [colliding signals](https://www.freqtrade.io/en/latest/strategy-customization/#colliding-signals) section of the docs.

At a quick glance, i didn't find anything that would suggest why longs would be prevented other than "in a trade already" - which counts until the end of the exit candle.
Best look at this in a chart (freqUI?) to identify how the signals fall - most likely, you're in a short whenever a buy signal happens.

**Comment by furkanbr** [comment]
I just saw someone elses question on discord that you answered;
https://discord.com/channels/700048804539400213/888978375882977350/961929244542390302

Is there any estimated time for when it can be possible? Thank you for your great work!

**Comment by xmatthias** [comment]
that's a different question i think. Your signals are colliding (at least mostly) - the question was about not locking the pair until candle end for the "other" direction.

Either way - it'll for sure not happen for the initial release (i'd not be accepting contributions that add this before the release).

Apart from that - as open source project, we're not giving timelines. It'll depend on people's time and interest.

**Comment by furkanbr** [comment]
Yes its same thing with my problem, i want to exit position and open new one to opposide direction. But when i tried that FT only create positions to one direction (like only short), i can see exit_short and enter_long icons at same candle on plot but not creating that positions, there is 0 long position on backtesting.

**Comment by xmatthias** [comment]
you can try to set `enter_short = 0` - if you get long positions then it might be the problem (i'm not 100% convinced it is yet).

**Comment by furkanbr** [comment]
Yes if i set `enter_short = 0` FT only creates long positions.

**Comment by xmatthias** [comment]
Freqtrade won't allow you to reverse a position within the candle a trade closed - signals for this will be ignored for the rest of the closing candle.

If all your signals are based on this logic - then you'll only get the "very first" entry - and all others will be ignored because they already had a trade open for this pair in this candle.

**Comment by avra911** [comment]
You can use 2 instances of same bot, one to go longs and one to go short.
This way, one instance enters when the other one exits. The only downside is that you will have different amounts for each.

my 2 cents.
