### ISSUE TITLE
error when run freqtrade bot in windows server 2022 in AWS

### ISSUE THREAD

**Issue by emamheba** [freqtrade/freqtrade#6667]
I get an instance with windows server 2022 in AWS then i install vs code and docker and copy all files  for freqtrade 
when i run it and open the container 
 i get an error  that shown in picture

what should i do
![error](https://user-images.githubusercontent.com/37589111/162504995-12b5b61d-2267-421c-a04d-ad88d4797483.png)

**Comment by xmatthias** [comment]
The error looks to be an error with your setup - not related to freqtrade directly - so we're unable to provide support for this setup.

You're best off looking for support for this in the vscode / vscode remote channels.

in general, i think this setup is quite odd - running a windows server in the cloud will cost you a lot more than an equivalent linux server - and installing docker on it will not be straightforward either (leaving the docker windows licensing out of the picture for now).

I'd therefore recommend a setup as follows:
* linux server (with or without docker installed)
* vscode on your local machine - connecting via remote extensions to the VPS

You can also run vscode on the linux host (if you install a desktop environment) if that's a must have (i don't think it is).

**Comment by emamheba** [comment]
thans for your reply
so i must use linux server instead off windows server 
and connect to the server via remote esxtention

**Comment by xmatthias** [comment]
it's not an absolute requirement - but the setup looks strange for sure as it currently is.
