### ISSUE TITLE
Entry feature

### ISSUE THREAD

**Issue by omararturo** [freqtrade/freqtrade#6669]
Trade ID: 19 (since 2 days ago)
Current Pair: VLX/USDT
Amount: 3154.6546 (800.02739582 USDT)
Entry Tag: 34 
Number of Entries: 5
Open Rate: 0.25360222
Open Date: 2022-04-06 13:21:52
Current Rate: 0.23410000
Current Profit: -8.06%
Stoploss: 0.00263800 (-99.00%)
Stoploss distance: -0.23146200 (-98.87%)
  
Entry #1:
Entry Amount: 1639.558 (432.51540040 USDT)
Average Entry Price: 0.2638
  
Entry #2: at -7.73% avg profit
(2 days 17 hours and 35 minutes ago)
Entry Amount: 630.3077 (153.41689418 USDT)
Average Entry Price: 0.2434 (-7.73% from 1st entry rate)
Order filled at: 2022-04-06 16:25:51
(0d 3h 3m 40s from previous entry)
  
Entry #3: at -4.62% avg profit
(0 days 4 hours and 58 minutes ago)
Entry Amount: 281.0823 (69.20246226 USDT)
Average Entry Price: 0.2462 (-6.67% from 1st entry rate)
Order filled at: 2022-04-09 05:02:51
(2d 12h 37m 0s from previous entry)
  
Entry #4: at -5.77% avg profit
(0 days 3 hours and 24 minutes ago)
Entry Amount: 294.8968 (71.36502560 USDT)
Average Entry Price: 0.242 (-8.26% from 1st entry rate)
Order filled at: 2022-04-09 06:37:06
(0d 1h 34m 15s from previous entry)
  
Entry #5: at -6.73% avg profit
(0 days 3 hours and 21 minutes ago)
Entry Amount: 308.8098 (73.52761338 USDT)
Average Entry Price: 0.2381 (-9.74% from 1st entry rate)
Order filled at: 2022-04-09 06:39:35
(0d 0h 2m 29s from previous entry)

I think it is a problem, should not make another entry lower than a previous entry, entry 2 in -7.73% entry 3 in -4.62%

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Also - your "question" doesn't really make sense (it's no question, really). 
it's the strategy that determines when the bot will buy / increase the stake. if you think it should behave differently - then you'll need to change this in your strategy to the way of your liking.
