### ISSUE TITLE
How to utilize the balance information in backtesting

### ISSUE THREAD

**Issue by fuzihaofzh** [freqtrade/freqtrade#6676]
## Your question
If I want to implement a Two-assets re-balance strategy that always makes USDT and BTC the same value. How can I implement this in freqtrade? Currently, freqtrade only executes populate_indicators, populate_buy_trend, and populate_sell_trend once. However, the buy or sell signal depends on the balance information which should be calculated at each tick. Any suggestions how I can implement this strategy for backtesting and dry run?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

For sell signals, you can look at [strategy callbacks](https://www.freqtrade.io/en/stable/strategy-callbacks/) - where existing balance will be available.

That said - freqtrade is not designed for such a strategy, but mostly for a strategy based on TA.
