### ISSUE TITLE
error during hyperopt

### ISSUE THREAD

**Issue by CARTEROO1** [freqtrade/freqtrade#6682]
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

I'd also encourage you to look at the documentation before opening issues. Many common topics are covered there.

---

This is quite simply a out of memory error. our [Documentation](https://www.freqtrade.io/en/stable/hyperopt/#out-of-memory-errors) has a segment about this.
