### ISSUE TITLE
Futures API Trading Restricted Notification

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#6683]
## Describe your environment

  * Operating system: Linux Mint Una
  * Python Version: python 3.10
  * CCXT version: 1.78.62
  * Freqtrade Version: develop-baefda80d
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Has anyone trying the futures market experienced this problem? and how did you workaround? anything to add to the config?

```
As you have violated our Futures API Quantitative Trading Rules(DR exceeds 0.9000), ETCUSDT of your Futures account (xxx@mail.com) has been banned from trading, the restriction will automatically end upon the expiration, estimated time 2022-04-11 16:11:42(UTC). 

Your trading on Reduce-only orders for ETCUSDT or other symbols that do not violate the rules will not be affected.  For details about Binance Futures API Trading Quantitative Rules, please visit our support center.
```

**Comment by xmatthias** [comment]
seems like it's [these rules](https://www.binance.com/en/support/faq/4f462ebe6ff445d4a170be7d9e897272).

reading the above (DR exceeds 0.9000) - it sounds like you're trading with too little volume (<50$ - if i read the link correctly).
There's little we can do - in the end, you'll probably have to trade with bigger size (it sounds like that, anyway).

The rules are however not really clear - so in the DR example - is that 50$ with or without leverage ... ?

**Comment by moinonin** [comment]
Thanks @xmatthias this was the case

**Comment by xmatthias** [comment]
I've added a note about this to the docs now - hoping that people look at the docs (Or at least allowing us to point to the docs).
