### ISSUE TITLE
Error while using multiple timeframe on EMA

### ISSUE THREAD

**Issue by topcumustafa** [freqtrade/freqtrade#6687]
* Operating system: Windows 10 (DOCKER)
  * Python Version: 3.10.2
  * CCXT version: 1.77.98
  * Freqtrade Version: 2022.3

*I am trying to build new strategies to improve myself. But I am getting this error while trying to use multiple timeframe:
```
df['ema_3'] = ta.ema(df, timeperiod = 1)

freqtrade    |   File "talib/_func.pxi", line 2936, in talib._ta_lib.EMA

freqtrade    | Exception: TA_EMA function failed with error code 2: Bad Parameter (TA_BAD_PARAM)
```

And here is my populate indicators func:

```python
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        ha_df = heikinashi(dataframe)
        dataframe['ha_reversal'] = ha_df['reversal']

        dataframe['sma'] = ta.SMA(dataframe, timeperiod = 35)

        df = resample_to_interval(dataframe, self.get_ticker_indicator() * 12)
        df['ema_3'] = ta.EMA(df, timeperiod = 1)
        dataframe = resampled_merge(dataframe, df)    

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['resample_{}_ema_3'.format(self.get_ticker_indicator() * 12)] > dataframe['sma']) &
                (dataframe['ha_reversal'] == 1)
            ),
            'buy'] = 1

        return dataframe

```
Am I defining wrongly?

**Comment by mert-donmez** [comment]
I had the same error before. EMA1 value actually means candle close. So If you want to give 1 to the timeperiod value you can use: `df['ema_3'] = dataframe['close']`

**Comment by xmatthias** [comment]
Using a timeperiod of 1 is usually an edge-case - which unfortunately is not always handled correctly in ta-lib - therefore you'll need to be a bit cautious with this.

EMA apparently captures this and warns/errors about it - but I've seen other indiators which then used future data for the calculation - which is absolutely not obvious from using the indicator alone.
