### ISSUE TITLE
Hyperopt single parameter not backtesting within populate_buy_trend

### ISSUE THREAD

**Issue by abbaselmas** [freqtrade/freqtrade#6690]
## Describe your environment

  * Operating system: Ubuntu 20.04.4 LTS
  * Python Version: Python 3.8.10
  * CCXT version: ccxt==1.78.62
  * Freqtrade Version: freqtrade develop-b1a6db8d2
  
## Describe the problem:

I want to hyperopt a single parameter. I have put the parameter under buy_params. Below is the range config of that param.

```
min_profit = DecimalParameter(0.70, 1.20, default=buy_params['min_profit'], space='buy', decimals=2, optimize=True)
```

There is no other option to be hyperopted, I have changed all optimize values to false for other parameters.

Problem is when I run hyperopt command, it effectively changed that parameter (i can confirm with hyperopt-show -n command) but does not calculate backtesting for that specific config. Only shows the first epoch results. (example result below)

By the way when i manually changed the parameter and backtest, there are different results, so yeah that paarameter effects backtesting results.

Parameter is used within populate_buy_trend.

My guess is maybe populate_buy_trend is not calculated at every epoch. Just a guess. Docs say it should.

> For every new set of parameters, freqtrade will run first populate_entry_trend() followed by populate_exit_trend(), and then run the regular backtesting process to simulate trades.

Other than this single parameter other buy sell roi or stoploss hyperopts are working fine.

### Relevant code exceptions or logs

```
+--------+---------+----------+------------------+--------------+-------------------------------+-----------------+-------------+-------------------------------+
|   Best |   Epoch |   Trades |    Win Draw Loss |   Avg profit |                        Profit |    Avg duration |   Objective |           Max Drawdown (Acct) |
|--------+---------+----------+------------------+--------------+-------------------------------+-----------------+-------------+-------------------------------|
| * Best |   1/400 |     1021 |    819  122   80 |        0.72% |       366.952 USDT   (36.70%) | 0 days 01:59:00 |    -366.952 |        37.078 USDT    (2.92%) |
| *      |   2/400 |     1021 |    819  122   80 |        0.72% |       366.952 USDT   (36.70%) | 0 days 01:59:00 |    -366.952 |        37.078 USDT    (2.92%) |
| *      |   3/400 |     1021 |    819  122   80 |        0.72% |       366.952 USDT   (36.70%) | 0 days 01:59:00 |    -366.952 |        37.078 USDT    (2.92%) |
| *      |   4/400 |     1021 |    819  122   80 |        0.72% |       366.952 USDT   (36.70%) | 0 days 01:59:00 |    -366.952 |        37.078 USDT    (2.92%) |
| *      |   5/400 |     1021 |    819  122   80 |        0.72% |       366.952 USDT   (36.70%) | 0 days 01:59:00 |    -366.952 |        37.078 USDT    (2.92%) |
| *      |   6/400 |     1021 |    819  122   80 |        0.72% |       366.952 USDT   (36.70%) | 0 days 01:59:00 |    -366.952 |        37.078 USDT    (2.92%) |
| *      |   7/400 |     1021 |    819  122   80 |        0.72% |       366.952 USDT   (36.70%) | 0 days 01:59:00 |    -366.952 |        37.078 USDT    (2.92%) |
| *      |   8/400 |     1021 |    819  122   80 |        0.72% |       366.952 USDT   (36.70%) | 0 days 01:59:00 |    -366.952 |        37.078 USDT    (2.92%) |
| *      |   9/400 |     1021 |    819  122   80 |        0.72% |       366.952 USDT   (36.70%) | 0 days 01:59:00 |    -366.952 |        37.078 USDT    (2.92%) |
```

**Comment by stash86** [comment]
where is the snippet of where and how that min_profit being used?

**Comment by abbaselmas** [comment]
its within populate_buy_trend

```
        dont_buy_conditions = []

        dont_buy_conditions.append(
            (
                (dataframe['close_1h'].rolling(24).max() < (dataframe['close'] * buy_params['min_profit'] ))
            )
        )

        if dont_buy_conditions:
            for condition in dont_buy_conditions:
                dataframe.loc[condition, 'buy'] = 0
```

**Comment by stash86** [comment]
buy_params would never be changed during hyperopt. To use it, write `self.min_profit.value`. Look at some of the examples on how to define hyperopt variables and how to use it

**Comment by abbaselmas** [comment]
self.min_profit.value works 
my bad sorry for taking your time.
