### ISSUE TITLE
TypeError: 'Order' object is not subscriptable

### ISSUE THREAD

**Issue by Maxsoborov** [freqtrade/freqtrade#6691]
* Operating system: Windows 11 (console Ubuntu 20.04)
  * Python Version: python 3.8.10
  * CCXT version: ccxt==1.77.72
  * Freqtrade Version: freqtrade develop-c57d80784
  
## TypeError: 'Order' object is not subscriptable

Hi! I took the code from this instruction:
https://www.freqtrade.io/en/latest/strategy-callbacks/#custom-order-timeout-example-using-additional-data
But unfortunately there is such an error:
`TypeError: 'Order' object is not subscriptable`
How can this be fixed?

```
from datetime import datetime
from freqtrade.persistence import Trade

    def check_entry_timeout(self, pair: str, trade: 'Trade', order: dict,
                            current_time: datetime, **kwargs) -> bool:
        ob = self.dp.orderbook(pair, 1)
        current_price = ob['bids'][0][0]
        # Cancel buy order if price is more than 2% above the order.
        if current_price > order['price'] * 1.03:
            return True
        return False

    def check_exit_timeout(self, pair: str, trade: 'Trade', order: dict, current_time: datetime, **kwargs) -> bool:
        ob = self.dp.orderbook(pair, 1)
        current_price = ob['asks'][0][0]
        # Cancel sell order if price is more than 2% below the order.
        if current_price < order['price'] * 0.96:
            return True
        return False
```

```
2022-04-15 21:24:50,703 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=1, pair=EUR/BUSD, amount=13.91465677, is_short=False, leverage=1.0, open_rate=1.07800000, open_since=2022-04-15 17:58:44)
2022-04-15 21:24:51,663 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'Order' object is not subscriptable calling <bound method Beta.check_entry_timeout of <Beta.Beta object at 0x7f5005659e50>>
Traceback (most recent call last):
  File "/home/max/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 21, in wrapper
    return f(*args, **kwargs)
  File "/home/max/freqtrade/user_data/strategies/Beta.py", line 122, in check_entry_timeout
    if current_price > order['price'] * 1.03:
TypeError: 'Order' object is not subscriptable
```

**Comment by xmatthias** [comment]
You're right, the documentation in this area is slightly wrong now - as the type of order changed from being a dictionary to an Order object.

You can simply use `order.price` for this.
if you change the type-hint in the header to `'Order'` you should also get code completion in your editor.

I'll update the documentation asap (linked to this issue) - so you have a reference for this.

**Comment by Maxsoborov** [comment]
Another question on this topic, can I write 1.0003, in a line to get 0.0003%?
`if current_price > order['price'] * 1.0003:`

**Comment by Maxsoborov** [comment]
Another question on this topic, can I write 1.0003, in a line to get 0.0003%?
`if current_price > order['price'] * 1.0003:`

**Comment by xmatthias** [comment]
well sure - nothing prevents you from modifying numbers you desire.

that said - 1.0003 is not 0.0003% - but 0.03%. going lower than that will however not make much sense for most pairs.
