### ISSUE TITLE
CategoricalParameter does not work

### ISSUE THREAD

**Issue by Maxsoborov** [freqtrade/freqtrade#6693]
* Operating system: Windows 11 (console Ubuntu 20.04)
  * Python Version: python 3.8.10
  * CCXT version: ccxt==1.77.72
  * Freqtrade Version: freqtrade develop-c57d80784
  
## CategoricalParameter does not work

Hi! Is it possible to use the range() parameter in the strategy? If it is still impossible, then the best replacement for range(), it seems to me, is CategoricalParameter:
`CategoricalParameter([65.05, 65.1, 65.15, 65.2....75.05], default=65.1, space="buy")`
But for some reason the program check only the default value, ignoring the other values. Entry does not occur because the value is equal to the default: 65.1, even if the best bid is 65.15. How to fix this?
Or is there another option to entry, with a step every 0.05?

```
    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['best_bid'] == range(65.05, 75.05, 0.05))
            ),
            'enter_long'] = 1
        return dataframe
```
```
2022-04-16 22:53:24,762 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'float' object cannot be interpreted as an integer calling <bound method IStrategy._analyze_ticker_internal of <Alfa.Alfa object at 0x7f07e76b6d00>>
Traceback (most recent call last):
  File "/home/max/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 21, in wrapper
    return f(*args, **kwargs)
  File "/home/max/freqtrade/freqtrade/strategy/interface.py", line 622, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/home/max/freqtrade/freqtrade/strategy/interface.py", line 602, in analyze_ticker
    dataframe = self.advise_entry(dataframe, metadata)
  File "/home/max/freqtrade/freqtrade/strategy/interface.py", line 1118, in advise_entry
    df = self.populate_entry_trend(dataframe, metadata)
  File "/home/max/freqtrade/user_data/strategies/Alfa.py", line 202, in populate_entry_trend
    (dataframe['best_bid'] == range(65.05, 75.05, 0.05))
TypeError: 'float' object cannot be interpreted as an integer
```
```
    buy_pricebid = CategoricalParameter([65.05, 65.1, 65.15, 65.2....75.05], default=65.1, space="buy")
    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (self.buy_pricebid.value == dataframe['best_bid'])
            ),
            'enter_long'] = 1
        return dataframe
```

**Comment by xmatthias** [comment]
> (dataframe['best_bid'] == range(65.05, 75.05, 0.05))

this is not valid pandas syntax. 
i'd suggest to learn how pandas works - usually the [pandas getting started](https://pandas.pydata.org/docs/user_guide/10min.html) guide is okish for most parts - otherwise the pandas documentation will help.

---

I don't think you understood how [strategy parameters](https://www.freqtrade.io/en/latest/hyperopt/#parameter-types) work. 

in regular mode (all modes except hyperopt):
Each Strategy parameter will use the defined value (either the default, or the one provided in the hyperopted file)

All other defined values in a parameter will only be used while running hyperopt - where each parameter is tested one after the other (resulting in different epochs / different backtests).
As such - your whole range will never be available within the same backtest run.

---

It's however also unclear what you're trying to do ... 
Assuming your intend is to enter if price is 65.05 - but not if it's 65.06 ... then you can probably write this a lot simpler.

simply do a "between" for your range - and a "mod" (modulo) with 0.05 (or whatever step size

something like the below (untested)

```
dataframe.loc[
            (
                (dataframe['best_bid'].between(65.05, 75.05)) &
                (dataframe['best_bid'].mod(0.05))
            ),
            'enter_long'] = 1
```

**Comment by Maxsoborov** [comment]
Now I realized that Categorical Parameter is not suitable for my strategy(
But now, I can't understand why it doesn't work: The bot is running and there is a heartbeat, but no order openings, nothing, although with an ugly code, everything worked, albeit slowly.

```
    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['best_bid'].between(0.0002, 0.5002)) &
                (dataframe['best_bid'].mod(0.0002))
            ),
            'entry_long'] = 1
        return dataframe
```
ugly code:

```
    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['best_bid'] == 0.0012) |
                (dataframe['best_bid'] == 0.001) |
                (dataframe['best_bid'] == 0.0008) |
                (dataframe['best_bid'] == 0.0006) |
                (dataframe['best_bid'] == 0.0004) |
                (dataframe['best_bid'] == 0.0002)
            ),
            'entry_long'] = 1
        return dataframe
```

**Comment by xmatthias** [comment]
You will have to think / understand what your code does - not just copy/pasting it blindly.

you'll most likely have to compare the result of `.mod()` to something (most likely `==0.0`). It's a mathematical function, so it will return a number - not a boolean just because you thought about it that way at that moment.

**Comment by Maxsoborov** [comment]
I thought that the first line is responsible for the range of bestbid hits in this interval, and the second line defines the step. Now I realized that I need to pull a number out of this range in order to later compare it with bestbid. But it doesn't work out, so far I can't understand why. I'm still just learning, I'm getting more and more immersed in python and how it works, so there may be too obvious questions) Below are code examples of how I tried to solve this problem, but so far without success.

```
    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['best_bid'].between(0.0103, 0.0503) == (dataframe['best_bid'])) &
                (dataframe['best_bid'].mod(0.0002) == 0)
            ),
            'enter_long'] = 1
```
```
    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['best_bid'].between(0.0103, 0.0503)) &
                (dataframe['best_bid'].mod(0.0002) == (dataframe['best_bid'])
            ),
            'enter_long'] = 1
```
```
    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['best_bid'].between(0.0103, 0.0503)) &
                (dataframe['best_bid'].mod(0.0002) == 0) == (dataframe['best_bid'])
            ),
            'enter_long'] = 1
```
```
    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['best_bid'], dataframe['best_bid'].between(0.0103, 0.0503).mod(0.0002)))
            ),
            'enter_long'] = 1
```

**Comment by xmatthias** [comment]
Again - please look at the pandas documentation for the methods you're using. While we can provide some help - we also assume that people do their own research - as it's our spare time that goes into supporting this project.

`between()` will return a boolean (True or False) - so you can use it "as is".
`mod()` will return a number - so you need to compare it to 0.0 (you want the one that returns no rest).

as such, a combination of the first 2 is probably correct.

**Comment by xmatthias** [comment]
I'll assume this as answered for now.

Feel free to comment below / reopen if that's not the case.
