### ISSUE TITLE
informative pairs not properly resampling OHLC data

### ISSUE THREAD

**Issue by jcnance1** [freqtrade/freqtrade#6695]
Hello
I'm using the 1d for my initial timeframe and using @informative 1w to look at the weekly.
![@informative](https://user-images.githubusercontent.com/61568997/163714441-de527caf-7f62-48d0-bfd7-24cdde05eb2e.png)
![mergedbtc](https://user-images.githubusercontent.com/61568997/163714719-251c5504-006e-4ec0-9cf2-0bdb3614588c.png)
You can see from the log of BTC/USDT it looks to be grouping 2022-03-23 to 2022-03-29 as the weekly timeframe, but if you look at the daily high candle log on the right the high was actually 48195.20. So why isn't it using the actually high of that entire span from 2022-03-23 to 2022-03-29 for the weekly high ? It appears that all the weekly data is skewed. What am I doing wrong? This is using kucoin exchange.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

The point you're (probably) missing is that all dates/times are candle open times.

the weekly candle merged onto the dates 03-23 until 03-29 is the one from the week prior  - 2022-03-17 (the last closed candle). It's merged as soon as the candle close dates (open-date + timeframe) aligns.

As a consequence - the value shown is correct - the weekly high of week 2022-03-17 is the one from March 22nd, which is 43343.0.

---

Using the weekly data from the running week would use the unfinished candle. While for backtesting, this may work (it actually isn't - see below) - in live this would lead to fluctuating signals - as the high / low / close are not static, and can change throughout the week.

This would also create an implicit lookahead bias in backtesting - as the daily monday candle would "see" the weekly high (which may only happen on thursday). 
While that would spark great backtesting results - it's also impossible to archive these results in real live.

**Comment by jcnance1** [comment]
That makes perfect sense, not sure why I missed that. Thanks for the help!

**Comment by xmatthias** [comment]
it's something we spent a lot of time thinking and analyzing about - it's not obvious at first glance - and you'll need to be very aware that all times are candle open times - otherwise it'll seem to make no sense

**Comment by jcnance1** [comment]
Once  you answered the first thought was duh! Pretty embarrassing, thanks for the polite response. You guys are doing great work.
