### ISSUE TITLE
sell signal not working with one pair

### ISSUE THREAD

**Issue by AmirMassou94** [freqtrade/freqtrade#6703]
* Operating system:  Ubuntu
  * Python Version:  3.6.9
  * CCXT version:  1.76.65
  * Freqtrade Version: 2022.3
  

couple days ago I have changed my strategy which just trade one pair so i changed the config file (which had been working for a while) "max_open_trades": 1,
"tradable_balance_ratio": 0.99,
after running the bot freq couldnt buy as showed insufficient money, then I figured out that I have to delete "available_capital" so the bot can handle the postion size... 
btw the bot could buy after that but, the problem now is despite of sellSignal that shown in freqUi the bot has not been closing the trade!!!! the point is that once worked with trailing stop!
I did not find any error in logs neither the populate_sell_trend msg!!!!
I don't know what should I check now to fix this!
![not selling](https://user-images.githubusercontent.com/64456212/163835549-e1089ee5-8c3b-460b-8829-f5401068f216.png)

**Comment by xmatthias** [comment]
Freqtrade has several settings that can impact this - most likely `use_sell_signal`, `sell_profit_only` - and potentially `sell_profit_offset`.

You may also have [colliding signals](https://www.freqtrade.io/en/stable/strategy-customization/#colliding-signals) - so if the sell-signal collides with the buy signal, it'd also not be selling.

**Comment by AmirMassou94** [comment]
> Freqtrade has several settings that can impact this - most likely `use_sell_signal`, `sell_profit_only` - and potentially `sell_profit_offset`.
> 
> You may also have [colliding signals](https://www.freqtrade.io/en/stable/strategy-customization/#colliding-signals) - so if the sell-signal collides with the buy signal, it'd also not be selling.

I checked this several times and `use_sell_signal: true , sell_profit_only: false` so no problem here, also in  `populate_sell_trend` I have I use this `&   ( dataframe["buy"] != 1) ` with sell condition to prevent `Colliding signals` I even export the DF to check buy and sell...
I didnt set `sell_profit_offset` as the document say 

> Sell-signal is only active above this value. Only active in combination with sell_profit_only=True
and my sell_profit_only is false!

I am using trail stop but I think it doesn't matter, does it?
`    trailing_stop = True
    trailing_stop_positive = y
    trailing_stop_positive_offset = x 
    trailing_only_offset_is_reached = True`

**Comment by xmatthias** [comment]
these settings seem so far - especially if `sell_profit_only` is false, then the offset won't matter.

The most likely scenario in this case is that either, you're using a different strategy than the one you're analyzing (duplicate strategyname?) - or that your sell-signal is unstable / has a lookahead bias. 

The latter case would mean that your signals show up on freqUI - but not as the "very last" candle. So your strategy would look at additional candles in the future to determine sells.
Obviously freqUI will show this signal as it's present now - but it would not act on it as it's not there when it matters.

**Comment by AmirMassou94** [comment]
the only possible reason could be the last case which you mentioned.
I know it has no lookahead  bias but I'll change the `populate_sell_trend` on the running live bot for testing this idea.
just for further information I wanna add that I get and csv export after sell condition on `populate_sell_trend` and I saw that in dataframe Sell was equal to 1, from this could we be sure that the problem could be something else that this case?

**Comment by xmatthias** [comment]
Assuming the settings are as you describe above (and the log also shows them this way - so they're not overwritten from the configuration) - and the log has nothing out of the ordinary (like - the order wasn't filled at that time yet, or there's other errors while selling) - then it'll be the strategy that's posting a late signal which is not available at  the time of the candle.

It's all theory though, as we have neither the strategy, nor any logs from the execution.

You should look very carefully at the "startup logs" - which will post the applied settings. Often people have a "forgotten" setting in the configuration (just to try something some time ago ...) - which is then messing with what people think is set for the strategy.

**Comment by AmirMassou94** [comment]
everything in backtest or even on live mode on freqUi is ok but I did change the `populate_sell_trend`  to be sure, although its odd because I checked TF and Sell was filed but I'm waiting for another buy to see if the problem was sell logic.
sure I'll check the startup logs too to be sure about the config.
I'll post the result soon
 Thank you for helping

**Comment by AmirMassou94** [comment]
Hi again 
I checked the "startup logs" and they are as they should be.
I changed a little the populate_sell_trend to be sure not having a lookahead bias!
and nothing has been fixed! down here I give my code related to sell signal and I'd be appreciate if you may take a look and if there is something wrong.
```python
dataframe['jma_shib_plus_direction'] = False 
dataframe['jma_shib_minus_direction'] = False      

dataframe["jma_shib"] = 0
for i in range(2,len(dataframe)-1):

    dataframe["jma_shib"].iat[i] = ((dataframe['jma'].iat[i] - dataframe['jma'].iat[i-2]) /dataframe['jma'].iat[i-2]) * 10000
    if(dataframe["jma_shib"].iat[i] >0):
        dataframe["jma_shib_plus_direction"].iat[i] = True
    if(dataframe["jma_shib"].iat[i] <=0):
        dataframe["jma_shib_minus_direction"].iat[i] = True

dataframe['jma_raising'] = 0
dataframe['jma_falling'] = 0
dataframe['jma_raising'] =dataframe['jma_shib_plus_direction'].rolling(window=self.raising_jma_shib_win, axis="rows").apply(lambda x: min(x))
dataframe['jma_falling'] =dataframe['jma_shib_minus_direction'].rolling(window=self.falling_jma_shib_win, axis="rows").apply(lambda x: min(x))

```
up here I fill my dataframe and  I don't think have any problem, does it? 

and my sell now is this:

```python
        dataframe.loc[
            (
                (
                    ( (dataframe['jma_raising'] == 1) & (self.jma_shib_sell_low < dataframe['jma_shib']) & (dataframe['jma_shib'] < self.jma_shib_sell_high) )
                    |
                    (dataframe['jma_falling'] == 1)
                    
                )
            ),
            'sell'] = 1
```
and `jma_shib_sell_low` or ... are constants which has been declared upper...

**Comment by AmirMassou94** [comment]
opps I found it!
it was sth wrong with myself
thanks for your time
