### ISSUE TITLE
use name also if id and name are different

### ISSUE THREAD

**Issue by SmartManoj** [freqtrade/freqtrade#6705]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: 1.78.63 (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

`{'id': 'R-USDT', 'symbol': 'R/USDT', 'base': 'R', 'quote': 'USDT', 'baseId': 'R', 'quoteId': 'USDT', 'active': True, 'type': 'spot', 'linear': None, 'inverse': None, 'spot': True, 'swap': False, 'future': False, 'option': False, 'margin': False, 'contract': False, 'contractSize': None, 'expiry': None, 'expiryDatetime': None, 'optionType': None, 'strike': None, 'settle': None, 'settleId': None, 'precision': {'amount': 4, 'price': 5}, 'limits': {'leverage': {'min': None, 'max': None}, 'amount': {'min': 0.1, 'max': 10000000000.0}, 'price': {'min': None, 'max': None}, 'cost': {'min': 0.01, 'max': 99999999.0}}, 'info': {'symbol': 'R-USDT', 'name': 'REV-USDT', 'baseCurrency': 'REV', 'quoteCurrency': 'USDT', 'feeCurrency': 'USDT', 'market': 'USDS', 'baseMinSize': '0.1', 'quoteMinSize': '0.01', 'baseMaxSize': '10000000000', 'quoteMaxSize': '99999999', 'baseIncrement': '0.0001', 'quoteIncrement': '0.00001', 'priceIncrement': '0.00001', 'priceLimitRate': '0.1', 'minFunds': '0.1', 'isMarginEnabled': False, 'enableTrading': True}, 'percentage': True, 'tierBased': True, 'taker': 0.001, 'maker': 0.001, 'tiers': {'taker': [[0.0, 0.001], [50.0, 0.001], [200.0, 0.0009], [500.0, 0.0008], [1000.0, 0.0007], [2000.0, 0.0007], [4000.0, 0.0006], [8000.0, 0.0005], [15000.0, 0.00045], [25000.0, 0.0004], [40000.0, 0.00035], [60000.0, 0.0003], [80000.0, 0.00025]], 'maker': [[0.0, 0.001], [50.0, 0.0009], [200.0, 0.0007], [500.0, 0.0005], [1000.0, 0.0003], [2000.0, 0.0], [4000.0, 0.0], [8000.0, 0.0], [15000.0, -5e-05], [25000.0, -5e-05], [40000.0, -5e-05], [60000.0, -5e-05], [80000.0, -5e-05]]}}`

Here id is 'R/USDT' and symbol is 'REV/USDT'.

On March 26, 2020, the company swapped R for REV tokens due to the difficulty of integrating the former into other blockchains. [Source](https://coinmarketcap.com/currencies/revain/#:~:text=however%2C%20on%20march%2026%2C%202020%2C%20the%20company%20swapped%20r%20for%20rev%20tokens%20due%20to%20the%20difficulty%20of%20integrating%20the%20former%20into%20other%20blockchains)

**Comment by xmatthias** [comment]
I'm not sure what you're expecting based on this issue (it doesn't contain any question or so).

the term "REV" does only appear within the info section (which contains the raw exchange response).
Freqtrade will be using `symbol` - or `base` and `quote` for it's operations. Using anything else would only lead to problems (ccxt would reject (certain) requests that come with REV/USDT, as that's not a valid market, or fail in other cases).

So if you think the mapping is wrong (symbol should be REV/USDT, not R/USDT) - then you'll have to open an issue on CCXT, not on freqtrade.
