### ISSUE TITLE
The buy tags are not displayed on graph 

### ISSUE THREAD

**Issue by Souti** [freqtrade/freqtrade#6708]
Hello

I'm not sure it's the right place to ask that, but since few days the "buy tag" aren't displayed.
In the image there is 9 buy signals but none is visible.
(I updated recently but no improvments) 

![image](https://user-images.githubusercontent.com/33179191/164481729-1cec9d18-81e3-4248-9b8d-c428e549080a.png)

  * Operating system: Linux mint
  * Python Version: 3.8.10
  * CCXT version: 1.79.81
  * Freqtrade Version: develop-e4629a273

**Comment by xmatthias** [comment]
what's your freqUI version (visible in the menu at the top right corner).
The screenshot looks somewhat outdated (new versions are darker) - so i think you can fix this pretty easily by updating freqUI.

**Comment by Souti** [comment]
Thanks a lot

It works with freqtrade install-ui
