### ISSUE TITLE
fetch_ohlcv  called unnecessarily

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#6709]
## Describe your environment

  * Operating system: ubuntu LTS
  * Python Version: 3.8.10
  * CCXT version: both FT's (1.79.81) and latest
  * Freqtrade Version: e4629a273 (I wasn't seeing the issue ~10 days ago)
  
## Describe the problem:

It appears to currently re-download candles unnecessarily with fetch_ohlcv (the latest version of ccxt doesn't change behavior) in a partly predictable manner. It downloads them fine (once) the first time it runs. Then on the following iteration it downloads some of them (not all) twice or more (instead of once) and it slows the whole process down (it may take a minute or so under certain conditions).

### Steps to reproduce:

  1. Monitor the _async_get_candle_history function for candles downloaded for each pair (either with verbose messaging or some manual printing in there) (use a volumepairlist of a lot of pairs I guess to see it more clearly but I can reproduce it even with 10 pairs)
  2. Start the bot (e.g. on 5min candles) and see pairs downloaded normally once (at this point nothing is wrong)
  3. On the next iteration (e.g. ~5min later): some of them (not all) are downloaded twice or more (instead of once) slowing down the whole process.

That wasn't happening about ~10 days ago; It's not a critical bug but it can slow down the whole process so signals may be handled late; people may never notice if they don't monitor _async_get_candle_history and there's no error or warning by default.

**Comment by epigramx** [comment]
I realize there's a chance it's expected behavior, if it tries to download pairs that the exchange hasn't had new candles for it yet, and it might be exchange related.

**Comment by xmatthias** [comment]
I think you'll need to treat this as 2 separate processes (even though they call the same function in the end).

One - you have the volumepairlist (and other pairlists) data - which is usually not cached, and by default `1d` data.
this will be downloaded "when required" - which is usually once per refresh interval for the first pairlist - and potentially more often in subsequent pairlists.
These calls are NOT cached (#6528), so they'll always go to the exchange. The logs should have them as "1d" candles (or whatever you configured).

The 2nd part is the "regular" candles, which will appear in "timeframe" and eventually "informative-timeframe" (and whatever additional pairs the strategy specifies there).
This part will be cached - so the API call itself will only happen once (chaching is visible in debug logging).

Requests CAN be repeated here (usually only once) - if the initial request was too early, and the exchange didn't issue a new candle yet (so we still get the old, unfinished candle). This is however timing related, and the first request would be VERY close to the candle start date (usually < 1s - but it'll depend on the pair's volume).

There's been no change to this I'm aware of within the last month - so it's unclear why you think it worked 10 days ago - this is most likely related to either changes in the strategy - or to changes in ccxt (again, none i'm aware of except of a bug with FTX in this regard)

Are you able to provide some logs on how you see this? (ideally with as few pairs as possible - and with the exchange you're using so we can limit it down as much as possible ...).

**Comment by epigramx** [comment]
Ok I realize there's something very odd happening with the exchange today, since even doge appears to not produce candles regularly (e.g. no 1min candles for 3min(!) which sounds just wrong for any popular asset). I'll close this for now and I'll reopen it only if I'm sure it's not the exchange because right now it appears very clear that it is.

**Comment by xmatthias** [comment]
out of interest - is that binance? or some other exchange that's doing this?
