### ISSUE TITLE
Web Ui Not available 

### ISSUE THREAD

**Issue by Dumnersm580** [freqtrade/freqtrade#6710]
## Describe your environment

  * Operating system: windows
  * Python Version: 3.9-3.10 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2022.3(`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

So every time I start the bot nothing shows up in the web UI and yes it is enabled

**Comment by stash86** [comment]
more info would be needed. What do you mean nothing shows up? Any screenshot?

**Comment by Dumnersm580** [comment]
![image](https://user-images.githubusercontent.com/80608783/164862361-2746b7a7-1448-488a-a207-3e5e56418bfd.png)

**Comment by Dumnersm580** [comment]
> more info would be needed. What do you mean nothing shows up? Any screenshot?

here

**Comment by Dumnersm580** [comment]
using the docker way on windows

**Comment by stash86** [comment]
upload your config here

**Comment by Dumnersm580** [comment]
[config.txt](https://github.com/freqtrade/freqtrade/files/8545880/config.txt)

**Comment by Dumnersm580** [comment]
i changed the port back to 8080

**Comment by Dumnersm580** [comment]
![image](https://user-images.githubusercontent.com/80608783/164864036-a03c6bbd-95d3-4919-af90-e4104539a6f3.png)

**Comment by stash86** [comment]
https://www.freqtrade.io/en/latest/rest-api/#configuration-with-docker

**Comment by Dumnersm580** [comment]
![image](https://user-images.githubusercontent.com/80608783/164864512-f9f3570e-f8f7-45de-a6ba-e7a5429b0d60.png)
correct?

**Comment by Dumnersm580** [comment]
![image](https://user-images.githubusercontent.com/80608783/164864934-b570dfe2-f5fe-4a14-9189-81247ad2f0e6.png)
same problem

**Comment by stash86** [comment]
```
"api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "username": "Freqtrader",
        "password": "SuperSecret1!",
        //...
    },
```

**Comment by Dumnersm580** [comment]
//... 

this makes it restart over and over

**Comment by Dumnersm580** [comment]
![image](https://user-images.githubusercontent.com/80608783/164865540-91960943-5f22-45cf-88ae-408f51d55f52.png)

**Comment by Dumnersm580** [comment]
![image](https://user-images.githubusercontent.com/80608783/164865566-81b70214-ba4d-4ccd-bd62-2382b0d21a9a.png)

**Comment by stash86** [comment]
you do know that that `//...` is placeholder and not to be copied to config, right?

**Comment by Dumnersm580** [comment]
place holder for what?

**Comment by Dumnersm580** [comment]
its doing this over and over agin
![image](https://user-images.githubusercontent.com/80608783/164865917-40112e1e-4c20-4e92-8f4e-074f360d0267.png)

**Comment by Dumnersm580** [comment]
please verify this section

**Comment by stash86** [comment]
upload your current config

**Comment by Dumnersm580** [comment]
freqtrade.exceptions.OperationalException: Parse error at offset 2060: The document root must not be followed by other values.

**Comment by stash86** [comment]
I'm asking for the config, not the error message

**Comment by Dumnersm580** [comment]
{
    "max_open_trades": 3,
    "stake_currency": "BTC",
    "stake_amount": 100,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "cancel_open_orders_on_exit": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "bid_strategy": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": true,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port":  "8080",
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "8fd5b37dc6337b9748b0704174cd5fa834bab6f7c07bea8e52a0bf8f0f65e0e4",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "admin"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

**Comment by stash86** [comment]
upload the file, because I want to see the indentation

**Comment by Dumnersm580** [comment]
[config1.txt](https://github.com/freqtrade/freqtrade/files/8546031/config1.txt)

**Comment by stash86** [comment]
`"listen_port": 8080,`

**Comment by Dumnersm580** [comment]
changed that let me test it

**Comment by Dumnersm580** [comment]
hey you want me to cash app you a thx tip it worked

**Comment by Dumnersm580** [comment]
just let me know

**Comment by stash86** [comment]
There is no need to. And you can close this issue if it has been resolved

**Comment by Cazs03** [comment]
I have the same problem in windows with docker compose

**Comment by xmatthias** [comment]
@Cazs03 following the [documentation](https://www.freqtrade.io/en/latest/docker_quickstart/) will make freqUI available automatically on localhost (127.0.0.1) - assuming you also followed the `new-config` points - which explicitly state that for docker, the listen address should be set to 0.0.0.0.

If it's still not working, i'd suggest to open a new issue - otherwise the points in this issue (or the documentation) will provide sufficient things to get freqUI working.

**Comment by giuliodz** [comment]
Same problem here but on Ubuntu. 
I run exactly what was on this guide [here](https://www.freqtrade.io/en/stable/docker_quickstart/#docker-quick-start) enabling the FreqUI but once I run the container with docker-compose the UI is not available on `localhost:8080`
I am attaching the config file. Please note that now I set the address to 0.0.0.0 because 127.0.0.1 was not working (but that was not the problem apparently)
[config.txt](https://github.com/freqtrade/freqtrade/files/9042079/config.txt)

**Comment by xmatthias** [comment]
You'll need to set the listen address to 0.0.0.0 for docker environments - otherwise docker cannot connect.

Please note that docker-compose exposes ports ONLY when started with `docker-compose up` (or `docker-compose up -d`) - but not when using `docker-compose run ...` - which is the most common issue when using docker.

**Comment by giuliodz** [comment]
Thank you [xmatthias](https://github.com/freqtrade/freqtrade/issues/6710#issuecomment-1174647356) I didn't know about docker-compose only exposing ports after `docker-compose up -d` and apparently I forgot to run that.

I'm still learning about docker-compose :sweat_smile:

**Comment by xmatthias** [comment]
you CAN use `docker-compose run ` - but then you need to explicitly state ports again ... which is usually not what you'd want.

**Comment by stend89** [comment]
Hey guys, I have been following the issues above and have followed the exact same resolution process to make sure I was doing everything right (right listen address (0.0.0.0) with right indentation, used "docker-compose up") but I receive the following message when I run localhost:8080

"localhost didn’t send any data."

Anyone would have any idea what I should review/modify?

Thanks a lot

**Comment by xmatthias** [comment]
best check the logs to determine if the server actually started (should say "listening on 0.0.0.0:8080"

**Comment by stend89** [comment]
Hi xmatthias, can you tell me what is the exact process to find this information? 

Here is what I did after searching on the internet:  I opened the windows command line and typed "netstat -na" where a list of number where displayed, the closest I've found was "127.0.0.1:8080" and status was "listening". "0.0.0.0:8080" was not listed. Not sure though if this was the right place to check this information

Secondly, I also opened VS code and went into logs>freqtrade.log where the closest thing I've found was:
2022-08-31 16:17:15,212 - freqtrade.rpc.api_server.webserver - INFO - Starting HTTP Server at 127.0.0.1:8080
2022-08-31 16:17:15,214 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.

Hope this helps, I'm a complete noob in coding so may not ease the process for a resolution : p 

Thank you again for your help

**Comment by xmatthias** [comment]
> Starting HTTP Server at 127.0.0.1:8080

Well this means your configuration does NOT use `0.0.0.0` as listening address as pointed out in the [docs](https://www.freqtrade.io/en/latest/rest-api/#configuration-with-docker).

**Comment by stend89** [comment]
I have reviewed the freqtrade docs but I don't see where my inputs would be incorrect. Can you check at my 2 files to let me know if all is correctly set up?
[dockercompose.txt](https://github.com/freqtrade/freqtrade/files/9468024/dockercompose.txt)
[configjson.txt](https://github.com/freqtrade/freqtrade/files/9468025/configjson.txt)

**Comment by xmatthias** [comment]
make sure to restart the container when changing the configuration.
best run `docker-compose down` followed by `docker-compose up -d` to restart the whole flow.

**Comment by stend89** [comment]
I have tried but it's not working :/ I've also stopped the firewall of my antivirus - just in case - but localhost:8080 still displays the same info:
"This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE"

I continue to go over freqtrade user guide but can't find for now what is the blocking point.. I may otherwise raise a ticket :/

**Comment by xmatthias** [comment]
As this is a closed issue from someone else (which means everyone contributing here will get notifications) - please open a new issue for your case.
Please don't forget to fill out the issue template - as well as providing the "startup logs" from the bot.
