### ISSUE TITLE
Separate stoploss_on_exchange & trailing_stoploss_on_exchange

### ISSUE THREAD

**Issue by Yodolescrypto** [freqtrade/freqtrade#6731]
Hello team,

Using latest version (develop-b40c017af ).
I'd like to add a new parameter to freqtrade which would enhance security without impairing trade performances.
I like having the possibility to have the SL set directly on the exchange in case the bot burns down and I loose my trade to liquidation. But I don't like the fact that trailing stoploss are also set, which in some cases where trailing_stop is really close to trailing_stop_offset the order fails and end in a -kind of random- emergency exit.

I see it can be done quite easily, I might do the PR myself if you think the idea is ok:
#freqtradebot.py #line 988
    def handle_stoploss_on_exchange(self, trade: Trade) -> bool:
    # check if param trailing_stop_on_exchange is true
    # yes -> call handle_trailing_stoploss_on_exchange
    # no -> do nothing yay

Let me know if I can bring any other usefull information to that topic.
Yodo

**Comment by xmatthias** [comment]
To be honest, i'm not quite sure what the benefit of this would be, other than increased risk, and supporting bad trailing-stop settings.

considering your scenario of using a very tight stop:
your stoploss would be cancelled - and a limit order would be placed.
That sell-order would potentially be "stuck" on the exchange (assuming price moves further away from your exit price).

If you're not VERY careful with your timeouts - you can blow through your initial stoploss easily, as that's no longer evaluated until the sell order is cancelled / filled.

As such - while it sounds like a nice enhancement, i think it is not what you want, and you should rather work on using a different, not so tight trailing-stop setup.

you can on the other hand also simulate trailing stops to some degree by using `custom_sell()` - which would already have the behaviour your expect (stoploss would remain static - and you decide yourself when to sell).
You'll still have the same drawbacks - but without adding more complexity to the bot-configuration for an edge-case scenario.

**Comment by Yodolescrypto** [comment]
Thanks for your answer ! 

My very goal would be to avoid the emergency exit - meaning if it can't exit and it timeouts - the trade resumes and waits for another trailing_stop_loss trigger.

Live trades proved that it is indeed quite risky - but to me it would be the intended behaviour and to my strategy for example - it's the safest bet.

Then you might be right and I'm in an edge case looking for the wrong solution - then I still find it useful for security/granularity, preventing early/unwanted exits if the exchange or client becomes unresponsive whilst trying to create the new stop-loss.

For test purposes, I'll just remove the condition that edits the trailing stoploss every minute see how that changes the behavior.

If you don't find it useful, I think we can close that one and go on, as it is anyway a minor change that ain't really critical to anyone.

**Comment by xmatthias** [comment]
you'll discover that your proposed approach will (potentially) have 2 problems - so it'll not be as simple as it sounds/looks at first
* when stoploss on exchange is on - stoploss orders will not be placed as regular sell orders
* when your sell order is cancelled - your new stoploss will be at the trailing stop location

So be VERY careful with this ... as i  think you severely underestimate the effort needed to get this to work even remotely in a safe way.

**Comment by Yodolescrypto** [comment]
To my understanding the process would be: 

1. Trade is created
2. SL is created on exchange
3. Trailing stop offset is reached
4. The bot calculates the trailing is not hit as it would with no stoploss_on_exchange
5. Trailing SL is hit, bot places a market sell order - initial SL still exists

In that way I don't see where it is dangerous, so either I don't know the process well or we weren't talking about that specific process.
Thanks for taking the time answering me, your advice is not to be ignored.

**Comment by xmatthias** [comment]
> 5\. Trailing SL is hit, bot places a market sell order - initial SL still exists

Freqtrade can't assume it's a market sell order - so the logic will also have to work for limit sell orders - which it doesn't.

Funnily - if you're using a market sell order, then there's little difference between your process and the "feared" emergency exit - which is also just a market order that's placed if placing the trailing order failed.

**Comment by Yodolescrypto** [comment]
You mean that trailing SL does place a limit sell whatever the setting is and does not issue a market sell while simulating the trailing SL within the bot process? In that case yes, it would make no difference.
The only difference I spotted between the two behaviors (SL on exchange and no SL on exchange) is actually 2 seconds of processing, which can mean a lot with some leverage but should definitely be accounted for in the strategy.

**Comment by xmatthias** [comment]
> 5. Trailing SL is hit, bot places a market sell order - initial SL still exists

Your logic will not work (for example on binance). The initial SL will tie up the amount you bought - preventing you from selling the same amount again UNLESS the stoploss is canceled.
FTX works slightly differently (allowing you to place 20 trigger orders for the same amount) - but that's an exception - not something we can or should rely on.

In a way - trailing stoploss would then become a regular exit (cancel stoploss, place new order) - which you can also simulate by using the [custom_exit](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-exit-signal) callback (simply compare `trade.max_rate` with `current_rate`) to determine your exit point.
