### ISSUE TITLE
Wrong number of trades in daily

### ISSUE THREAD

**Issue by zorann** [freqtrade/freqtrade#6734]
## Describe your environment

  * Operating system: ____Linux
  * Python Version: _____ 3.8(`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ 2022.03(`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
Hello,

why is trade count different from report in daily. When i viewed daily trades it stated 17 but i manually counted 23. Why is that?

best regards

**Comment by xmatthias** [comment]
Daily trades are counted based on the trade close date.

If a trade opened yesterday, but closed today, it'd not be counted towards yesterday's trades.

**Comment by zorann** [comment]
All trades were opened and closed today. It was in dry run.

**Comment by zorann** [comment]
And earnings were also different.

**Comment by xmatthias** [comment]
i don't fully understand what you intend with this issue with the provided information.

Without providing any information (no logs, not even outputs of what you're seeing) - there will be very little we can do.
`/daily` works fine for me - so the best thing will be to compare the results you get with the trades directly. The best way for this is probably through freqUI.

**Comment by xmatthias** [comment]
With the provided information, there is nothing i can do here.

Feel free to reopen / comment below if you're able to provide logs / trade lists + daily outputs of what you're seeing, so we can compare what you expect vs. what's happening..
