### ISSUE TITLE
How to change the binance's api url prefix to my custom url prefix such as : https://testnet.binance.vision/

### ISSUE THREAD

**Issue by 61go** [freqtrade/freqtrade#6736]
I wanto to test freqtrade bot. so i don;t want to use the real binance api url .
so I want to know wether there is a way to config the url prefix of binance api.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Please also consult the [documentation](https://www.freqtrade.io/en/stable) - in this particular case the [sandbox testing](https://www.freqtrade.io/en/stable/sandbox-testing/) documentation.

Be warned though - test-nets usually have VERY low volume - so they can usually only be used to test some new functionalities, not to verify strategy results.

Freqtrade offers dry-run mode for strategy forward validation (also explained in the documentation) - which will simulate trades (without using your exchange keys) against the real markets.
