### ISSUE TITLE
how to add a new exchange?

### ISSUE THREAD

**Issue by tradeswitcher** [freqtrade/freqtrade#6737]
I'm new to freqtrade. 
how to add a new exchange?  like stock exchange.

**Comment by xmatthias** [comment]
Freqtrade is using [ccxt](https://github.com/ccxt/ccxt) to connect to exchanges.
As such, any exchange supported by ccxt can work in theory (given it provides all necessary methods).

As ccxt is a crypto library - they do not support a regular stock exchange - so neither does freqtrade.
Feel free to ask there to integrate a regular exchange - but i don't think this will have success, as their direction is clearly to be a crypto library.

If the exchange is supported by ccxt, and you'd like to test an exchange noone else tested, please follow the steps in the [developer documentation](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip) for this. 
It's not 100% complete, but should get a non-tested exchange there by ~90%.
