### ISSUE TITLE
Custom (entry-tag) for trade position adjustment entry

### ISSUE THREAD

**Issue by cce15** [freqtrade/freqtrade#6738]
## Describe the enhancement

I noticed that (adjust_trade_position) callback function is not supporting to pass an entry custom tag  so it can be used later for strategy analysis . It is very important to test and analyze the DCA logic in the back-testing results and it will help also in plotting and pointing where the DCA events are happening. 

Thanks,

**Comment by cce15** [comment]
Is it possible to get all the adjustment entries orders ?

**Comment by xmatthias** [comment]
entry-tags are stored per trade, therefore only the first one makes sense to keep - so adding such functionality to `adjust_trade_position` does not make sense.

all orders are stored in the database - so you can get them from the database (or via `freqtrade show-trades`).

Backtesting will not store single orders for the moment.

**Comment by cce15** [comment]
> entry-tags are stored per trade, therefore only the first one makes sense to keep - so adding such functionality to `adjust_trade_position` does not make sense.
> 
> all orders are stored in the database - so you can get them from the database (or via `freqtrade show-trades`).
> 
> Backtesting will not store single orders for the moment.

Thanks , It is clear to me now .

**Comment by xmatthias** [comment]
for completeness maybe: we'll probably be adding single order output to backtesting results (it makes absolute sense there)
as for tagging individual orders - that's neither quick/simple to implement - nor will it be very usable (where would you visualize this ...).

**Comment by cce15** [comment]
> for completeness maybe: we'll probably be adding single order output to backtesting results (it makes absolute sense there) as for tagging individual orders - that's neither quick/simple to implement - nor will it be very usable (where would you visualize this ...).

But what if i want for example to calculate the average number of safety orders when position adjustment happening in trades and other calculations for deep and further strategy analysis specially when the training strategy is dependant to DCA.

**Comment by xmatthias** [comment]
i'm not entirely sure i understand this point.
prior orders are available from within the strategy. 

The orders are just currently not saved as it's "redundant" information (except if you're using DCA).
