### ISSUE TITLE
Problem implementing custom_stoploss in the latest stable release

### ISSUE THREAD

**Issue by shakeel-appyhigh** [freqtrade/freqtrade#6740]
## Describe your environment

  * Operating system: Windows with Docker
  * Python Version: Python 3.9.9
  * CCXT version: 1.80.61
  * Freqtrade Version: `freqtrade develop` (when `freqtrade -V` is executed inside docker container in bash shell) and  `freqtrade docker-44000ae0` (when `docker-compose run --rm freqtrade -V` is executed in windows powershell) 
  
## Your question
Hi, has the custom_stoploss function been removed in the current release? I can find the documentation in an earlier release [documentation.](https://www.freqtrade.io/en/2021.2/strategy-advanced/#custom-stoploss-examples) but not in the current release [documentation](https://www.freqtrade.io/en/stable/strategy-advanced)

I have used the following code:
```
    use_custom_stoploss = True
    custom_info = {}
    def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:
        
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        return dataframe['atr']
```
But I get the error `AttributeError: 'RSICrossOverEmaSma' object has no attribute 'stoploss'`

I also tried to store it in custom_info dictionary both as `self.custom_info["stoploss"]` and  `self.custom_info["cust_stoploss"]` but got the same error.

Is the way different in the current release? It is not clear from the documentation how to implement it.

**Comment by xmatthias** [comment]
documentation can [move around](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stoploss) - and callbacks are now on a separate page.

The error itself doesn't really look to be tied to the custom-stoploss - but to the regular stop (but it's hard to tell for sure without the full stacktrace).

Even with custom stoploss, you'll still have to assign a regular stoploss  (e.g. `stoploss = 0.2`) - which serves as initial stop (and a hard-stop - so it should be the maximum risk your willing to take).

**Comment by shakeel-appyhigh** [comment]
thank you for your help. it worked.

A suggestion for updating documentation, maybe the compulsory assignment of a regular stoploss can be added to the documentation code examples for implementing custom stoploss.

**Comment by xmatthias** [comment]
the problem with that is - that would technically apply to every attribute in the strategy (but if we have the full strategy there, you'll no longer see what's relevant).
stoploss is by far the only mandatory attribute - but i'll have a look if we can improve the errormessage users receive.

**Comment by shakeel-appyhigh** [comment]
Agreed. But in this case the user is under the impression that stoploss is being already defined by him. Hence the confusion.

A better error message will be helpful to the user too.
