### ISSUE TITLE
Is a Buy and Hold strategy available somewhere?

### ISSUE THREAD

**Issue by yassinsameh** [freqtrade/freqtrade#6742]
I'd like to compare my results with a Buy and Hold for certain periods of time for certain assets, is that possible given the current system or must i write custom code?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me always question why we should chose to answer your questions.

---

Backtesting provides the `market change` value - which is technically a buy&hold metric across all pairs in the pairlist.
while that doesn't include fees - that's also not really relevant as you'll only do 2 operations per pair - so fees are neglectible.

i'm not aware of other such strategies - but it would be pretty easy to write one if you'd only want it for very specific pairs.
