### ISSUE TITLE
Very long time showing Pairs Combined after normal refresh Browser

### ISSUE THREAD

**Issue by mkajnar** [freqtrade/freqtrade#6743]
It occured in new version  FreqTradeUI in Chrome - over 30 - 60 seconds (sometimes more).

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

With the provided information (no versions, no porper description) - there is little we can do.

If it's about freqUI - we'll (in addition to the regular issue template) also need the freqUI version (visible in the top right corner, once you click the icon).

**Comment by mkajnar** [comment]
## Describe your environment

  * Operating system: Debian GNU/Linux 11 (bullseye).
  * Python version: python 3.9.10
  * CCXT version: ccxt==1.81.1
  * Freqtrade Version: freqtrade 2022.3 - FreqUI Version says V:DEV
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is removed or not filled in.

## Describe the issue:

Normal refresh in the browser (F5) or CTRL R results in not rendering the currency list in Pairs Combined for 30-90 seconds

### Steps to reproduce:

  1. switch Freqtrade on the Trade page in Pairs Combined
  2. press Ctrl F5 or Ctrl R
  
### Observed results:

  * Currency list is cleaned and then does not refresh for 30-60 seconds, sometimes more
  * in earlier versions the list refreshed almost immediately

**Comment by xmatthias** [comment]
This was fixed in freqUI some days ago - i've just created a release, so using `freqtrade install-ui` will update to a fixed version (freqUI 0.3.3)

**Comment by mkajnar** [comment]
I tried it, but now is every page i UI empty and black. I will try make new build Freqtrade from Github now again, than reinstall UI.  JavaScript is enabled of course.

Here is actual page source:

<html>
<body>


<!DOCTYPE html>
--
  | <html lang="en" data-theme="dark">
  | <head>
  | <meta charset="utf-8">
  | <meta http-equiv="X-UA-Compatible" content="IE=edge">
  | <meta name="viewport" content="width=device-width,initial-scale=1.0">
  | <link rel="icon" href="/favicon.ico">
  | <title>FreqUI</title>
  |  
  | <script type="module" crossorigin src="/assets/index.18c4e77e.js"></script>
  | <link rel="stylesheet" href="/assets/index.85b239f6.css">
  | </head>
  | <body>
  | <noscript>
  | <strong>We're sorry but FreqUI doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
  | </noscript>
  | <div id="app"></div>
  |  
  | </body>
  | </html>


</body>
</html><!DOCTYPE html>
<html lang="en" data-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="[/favicon.ico](http://65.21.192.30:8090/favicon.ico)">
    <title>FreqUI</title>

    <script type="module" crossorigin src="[/assets/index.18c4e77e.js](http://65.21.192.30:8090/assets/index.18c4e77e.js)"></script>
    <link rel="stylesheet" href="[/assets/index.85b239f6.css](http://65.21.192.30:8090/assets/index.85b239f6.css)">
  </head>
  <body>
    <noscript>
      <strong>We're sorry but FreqUI doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    
  </body>
</html>

**Comment by xmatthias** [comment]
The only reason i can potentially imagine this is that you're using an older browser (whereas 
The asset you're seeing (18c4e77e.js) is the same i get with the latest freqUI, so the installation appears to be fine.

in modern browsers (recent few versions of chrome, edge, firefox) freqUI will work fine.

**Comment by mkajnar** [comment]
I am using 
![image](https://user-images.githubusercontent.com/5566514/166163572-894a0846-1138-4f82-a993-11a3b17fdd0a.png) in Windows OS. I tested it with Chrome on Android and problem is the same. I will test it tommorow with latest chrome. Thanks.
