### ISSUE TITLE
Mexc and VolumePairList

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#6751]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.2.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

The exchange Mexc is currently not on your offitially supported exchange list. But I let you know, that in my case only a StaticPairList works. Any VolumePairList generates a whitelist with zero entries.
I thank you for your hint.

(Personally I see Mexc as powerful, because one can split the huge amount of coins into multiple groups, running in different bots)

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
Please try to use volumepairlist in [advanced mode](https://www.freqtrade.io/en/stable/plugins/#volumepairlist-advanced-mode).

mexc does not seem to provide proper volume-data via `fetch_tickers()` endpoint.
As such - it should be considered as "unsupported" (see "tip" box "unsupported exchanges in the above link) by regular volumepairlist configuration, and will need to use advanced mode (which downloads candles).

While testing this - please compare the resulting pairlist with realistic volumes - as we've seen some exchanges report volume in USDT, while others report volume in "coin" (making it impossible to properly compare).

That'd be something that's easy to fix - but will needs investigation first.

**Comment by myNextCoder** [comment]
Great, I let you know about my testing-results.

**Comment by xmatthias** [comment]
A quick test shows that their data seems to be quite messed up

for example, the `load_markets()` response cointains a pair, TOKEN/USDT ... their webpage shows that as ASAP/USDT (with the URL for TOKEN/USDT - https://www.mexc.com/exchange/TOKEN_USDT) ...
but you can't fetch candles for TOKEN/USDT, neither ASAP/USDT due to this mismatch.

Unfortunately, that's a good sign of an exchange that'll not be supportable / usable by freqtrade - as their API seems to be messed up ...

**Comment by myNextCoder** [comment]
According to your post, I even don't test this exchange, I would have loved their amount of coin choice.

**Comment by xmatthias** [comment]
It's not a good sign - i didn't test this in depth though - and maybe getting in touch with the exchange about these differences can also help (it may only impact this one pair - so you could just exclude these ).

so far, i've seen it with TOKEN/USDT, ROCKS/USDT, CRING/USDT MCC1/USDT.
These seem to be listed as active, but you can't get candle data for them.

all it **really** means is that it may require some work to get it working (obviously always with questionable results).
Exchanges like gate.io have also quite a nice coin selection (more than binance, anyway), too - but that's an exchange we know working.

**Comment by myNextCoder** [comment]
Ok, I see, I may have generalized your previous post to much. I still should have a look at this exchange more in detail, beginning by excluding your posted coins - I thank you for this hint. Contacting the exchange is a good option, as soon as I discover further exchange related issues.
Yes, gate.io is an exchange with a huge amount of coins, I am using it already.

**Comment by xmatthias** [comment]
we do have some guidance on how to approach this in the [developer docs](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip) - which covers the common points to check on a new exchange.

**Comment by myNextCoder** [comment]
Many thanks for this link :)

**Comment by samgermain** [comment]
@myNextCoder Let me know if you can get MEXC working
