### ISSUE TITLE
If bot finds a good entry but all slots are full with red bags then better Force exit one slot

### ISSUE THREAD

**Issue by JhorAVi** [freqtrade/freqtrade#6754]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

If bot finds a good entry but all slots are full with red bags then better Force exit one slot

When slots are full, the bot misses a lot of opportunity of the current volatility. It might be a good idea to free one slot if Bot finds a good new entry. Ofcourse the freed slot should be a red bag that's unlikely to recover soon.

**Comment by xmatthias** [comment]
There is little preventing you from either doing this manually via `/forcesell` - or implement something in the `custom_exit()` flag.

In general, i'd not exit "when it finds a good, alternative opportunity".
if you assume a red trade unlikely to recover - then you should've exited that trade already by the regular strategy logic. 
I'd not make this dependent on "other opportunity" though - but as proper trade/risk management.
it either is a still valid opportunity (so you stay in the trade) - or it isn't and you should be out of that trade anyway.
