### ISSUE TITLE
No entries at the report

### ISSUE THREAD

**Issue by eldargoren** [freqtrade/freqtrade#6756]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.5
  * CCXT version: Haven't found (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.4 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
I tried changing the `populate_entry_trend` function as such:
collecting all the candles which I was supposed to buy, then adding each one the value 1 at the column `enter_long`.
But there is no buy when I ran the strategy.

**Comment by xmatthias** [comment]
the `enter_long` column just symbols a enter signal. 

If freqtrade is able to act on it will depend on several other things - like open positions, available capital, ...

you can have 1000 signals, but only 2 trades - if these 2 trades take for the whole duration of the period.

If you get no trades at all, then the log output (assuming this is backtesting) will provide the best starting point to analyze what's happening.

**Comment by eldargoren** [comment]
So I have both buy signals and sell signals.
The report shows no trade at all.
Where I do wrong?

**Comment by xmatthias** [comment]
without logs / the output you're getting, it's fishing in the dark.

You may have [colliding signals](https://www.freqtrade.io/en/stable/strategy-customization/#colliding-signals) - or some configuration error so there is no balance available for the trade-size you've configured.

That's the most likely reasons, but by far the only ones.

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.
