### ISSUE TITLE
strategy runs backtest but gets error in dry run.

### ISSUE THREAD

**Issue by donjonson** [freqtrade/freqtrade#6757]
## Describe your environment

  * Operating system: ____  Ubuntu
  * Python Version: _____ (`python -V`) 3.9.5
  * CCXT version: _____ (`pip freeze | grep ccxt`) 1.76.65
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  2022.3
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
I have a strategy that uses resample_to_interval to generate multiple timeframes.  Also I get informative pairs and resample those before I gernerate indicators.

the strategy runs in backtest mode without error.  But in dry run it encounters the following error.  

### Steps to reproduce:

  1. _____run dry run using the strategy.
  2. _____
  3. _____
  
### Observed Results:

  * What happened: Strategy works in backtest but fails in dry run.
  * What was expected: dry run to run without error.

### Relevant code exceptions or logs
The goal is to trade the 3L and 3S tokens in kucoin but generate indicators and buy signals from the standard version of the 3L and 3S coins.  I want multiple timeframes that the exchange does not support so I generate the informative and then resample it and then calculate the indcators and then merge the informative.   As said before in backtest this seems to work.  in dry run it generates the error listed in the log section below.  Am I going about this the wrong way?  All I am looking for is the generate indicators from multiple exchange unsupported timeframes of informative pairs. 

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """     
        create informative for base timeframe
        create base timeframe indicators

        for each timeframe multiplier, create informate and indicators.

        merge it all together.
        """
        #--------------------------------------
        # Get Informatives into DF
        #--------------------------------------
        current_pair = metadata['pair']
        if '3S/' in current_pair:
            current_pair = current_pair.split('3S/')[0] + '/' + current_pair.split('3S/')[1]
        if '3L/' in current_pair:
            current_pair = current_pair.split('3L/')[0] + '/' + current_pair.split('3L/')[1]
        informative = self.dp.get_pair_dataframe(current_pair , timeframe=self.timeframe)

        for TF in self.timeframe_resample_list:
            if TF != 1:
                current_pair = metadata['pair']
                if '3S/' in current_pair:
                    current_pair = current_pair.split('3S/')[0] + '/' + current_pair.split('3S/')[1]
                if '3L/' in current_pair:
                    current_pair = current_pair.split('3L/')[0] + '/' + current_pair.split('3L/')[1]
                informative = self.dp.get_pair_dataframe(current_pair , timeframe=self.timeframe)

                dataframe_TF = resample_to_interval(dataframe, TF)

                informative_TF = resample_to_interval(informative, TF)

                ## cust_populate_indicators will generate the indicators on both  dataframe 
                ## and the informative then merge the informative with dataframe and returen that.
                dataframe_resampled = self.cust_populate_indicators(dataframe_TF,informative_TF, metadata, current_pair)

                #merge the derived indicators from merged resampled dataframe and informative back into the main dataframe
                print("\n\n##### MERGING dataframe with " + str(TF) + "\n")
                dataframe = resampled_merge(dataframe, dataframe_resampled, fill_na=True)

            else:
                dataframe = self.cust_populate_indicators(dataframe,informative, metadata, current_pair)
        return(dataframe)

    def cust_populate_indicators(self, dataframe: DataFrame, informative: DataFrame,  metadata: dict, current_pair) -> DataFrame:
        

        #current_pair = metadata['pair']
        # ------------------------------------
        # HEIKEN_ASHI
        # ------------------------------------

        heikinashi = qtpylib.heikinashi(informative)
        informative[current_pair + '_ha_open'] = heikinashi['open']
        informative[current_pair + '_ha_close'] = heikinashi['close']
        informative[current_pair + '_ha_high'] = heikinashi['high']
        informative[current_pair + '_ha_low'] = heikinashi['low']
       
       dataframe = merge_informative_pair(dataframe, informative, self.timeframe, self.timeframe, ffill=True)
        return dataframe

Note: Please copy/paste text of the messages, no screenshots of logs please.
```
2022-05-01 19:36:36,470 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "kucoin GET https://openapi-v2.kucoin.com/api/v1/market/candles?symbol=BTC-USDT&type=30min&startAt=1650533794&endAt=1651433794 429 Too Many Requests {"code":"429000","msg":"Too Many Requests"}". Retrying still for 4 times.
2022-05-01 19:36:37,589 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error inputs are all NaN calling <bound method IStrategy._analyze_ticker_internal of <strategy_spaghetti_01.strategy_spaghetti_01 object at 0x7f9bd6723ac0>>
Traceback (most recent call last):
  File "/mnt/blockstorage/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 21, in wrapper
    return f(*args, **kwargs)
  File "/mnt/blockstorage/freqtrade/freqtrade/strategy/interface.py", line 544, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/mnt/blockstorage/freqtrade/freqtrade/strategy/interface.py", line 523, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/mnt/blockstorage/freqtrade/freqtrade/strategy/interface.py", line 921, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/mark/freqtrade/bot_spaghetti_01/user_data/strategies/strategy_spaghetti_01.py", line 508, in populate_indicators
    dataframe_resampled = self.cust_populate_indicators(dataframe_TF,informative_TF, metadata, current_pair)
  File "/home/mark/freqtrade/bot_spaghetti_01/user_data/strategies/strategy_spaghetti_01.py", line 409, in cust_populate_indicators
    informative[current_pair + '_vwap_diff4_' + str(tf)]] = self.indicator_spaghetti_cipher(informative[current_pair + '_ha_close'], informative[current_pair + '_ha_high'], informative[current_pair + '_ha_low'], tf)
  File "/home/mark/freqtrade/bot_spaghetti_01/user_data/strategies/strategy_spaghetti_01.py", line 238, in indicator_spaghetti_cipher
    vwap_d3 = sp3_scale * ta.EMA(vwap_d2.diff(periods=sp3_len),  sp3_emalen)
  File "/mnt/blockstorage/freqtrade/.env/lib/python3.9/site-packages/talib/__init__.py", line 64, in wrapper
    result = func(*_args, **_kwds)
  File "talib/_func.pxi", line 2931, in talib._ta_lib.EMA
  File "talib/_func.pxi", line 68, in talib._ta_lib.check_begidx1
Exception: inputs are all NaN
```

**Comment by xmatthias** [comment]
Based on the exception, the error is in line `vwap_d3 = sp3_scale * ta.EMA(vwap_d2.diff(periods=sp3_len),  sp3_emalen)` - which is not part of the above strategy codesample.

I also don't think that ` return(dataframe)` is valid code - it should be ` return dataframe` ... and it might be the problem just as well - as your code will not return the dataframe - so the subsequent inputs will be None.

**Comment by donjonson** [comment]
ok thanks for the feedback.  I have made the problem more clear and will close this and create a new one.
