### ISSUE TITLE
Change stop loss before entry

### ISSUE THREAD

**Issue by wahyubiman** [freqtrade/freqtrade#6767]
Its possible to change stoploss on every entry signal?

Let say i have set config "stoploss" = -0.10, then my strategy trigger a populate_entry_signal and change stoploss inside that funtion before placing an order

It is possible?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

the regular stoploss attribute is static, and will apply for all trades identically, and will be the initial stoploss applied (think about it as the maximum overall risk).

you can however use the [custom stoploss](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stoploss) callback to modify the stoploss per pair (or based on whatever other logic you think makes sense).

**Comment by stash86** [comment]
Remember that stoploss can only go up can can't go down. So if the "basic" stoploss is set at -10% for example, you won't be able to set any individual custom stoploss lower than -10%.

**Comment by wahyubiman** [comment]
> Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment. We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.
> 
> the regular stoploss attribute is static, and will apply for all trades identically, and will be the initial stoploss applied (think about it as the maximum overall risk).
> 
> you can however use the [custom stoploss](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stoploss) callback to modify the stoploss per pair (or based on whatever other logic you think makes sense).

So i can only change the stoploss after trade happen with custom stoploss callback and the value must be go up from stoploss static value?

**Comment by xmatthias** [comment]
That's correct - and is there as safety measure.

As said above, think about the regular `stoploss` property as the maximum stoploss you're going to have - and which will be in place should your custom stoploss logic fail for some reason.

**Comment by wahyubiman** [comment]
> That's correct - and is there as safety measure.
> 
> As said above, think about the regular `stoploss` property as the maximum stoploss you're going to have - and which will be in place should your custom stoploss logic fail for some reason.

Its clear now & thanks for the explanation 👍

Closed
