### ISSUE TITLE
Log flooded with message: freqtrade.freqtradebot - INFO - No stake amount to enter a trade for {pair}

### ISSUE THREAD

**Issue by klara31** [freqtrade/freqtrade#6768]
## Describe your environment

  * Operating system: Debian 11
  * Freqtrade Version: 2022.04.1 in a docker container

## Your question
I just updated Freqtrade from 2022.03 to 2022.04.1 and noticed that the log is being flooded with messages:
```
...
2022-05-02 16:11:47,119 - freqtrade.freqtradebot - INFO - No stake amount to enter a trade for MANA/BTC.
2022-05-02 16:11:49,036 - freqtrade.freqtradebot - INFO - No stake amount to enter a trade for AVAX/BTC.
2022-05-02 16:11:50,254 - freqtrade.freqtradebot - INFO - No stake amount to enter a trade for LTC/BTC.
2022-05-02 16:11:50,794 - freqtrade.freqtradebot - INFO - No stake amount to enter a trade for AXS/BTC.
2022-05-02 16:11:52,249 - freqtrade.freqtradebot - INFO - No stake amount to enter a trade for ATOM/BTC.
...
```
It actually is going through all active pairs and keeps doing this. 

Did I miss something during migrating from 2022.03 to 2022.04.1?

**Comment by xmatthias** [comment]
For spot bots - no migration steps are actually necessary at this moment - so a "non-migrating" update would've also worked - at least for now.

The message is shown if you've  encountered a entry signal (buy or sell) - but have no stake-amount left.

If you're seeing this for all pairs, then that would mean that you have a buy-signal for all pairs (unlikely, but possible).
No stake amount left can be a miss-configuration of stake (nothing changed in this regard) - like too high stake, or no balance in the wallet - or all available assets are in trades (but max_open_trades would still allow additional trade-slots).

without knowing the stake-amount config, it'll be difficult to determine what is causing it (please look into the "all have a signal" first).

**Comment by klara31** [comment]
Weird... I changed config.json to get rid of the 'buy' and 'sell' errors during startup. I haven't changed my strategy file (yet). Just checked the old logs again, they do not have this message. 

This is my config.json:
```
{
    "max_open_trades": 15,
    "stake_currency": "BTC",
    "stake_amount": 0.005,
    "tradable_balance_ratio": 0.99,
    "amend_last_stake_amount": true,
    "fiat_display_currency": "EUR",
    "dry_run_wallet": 1,
    "dry_run": false,
    "strategy": "xxxx",
    "strategy_path": "user_data/strategies/",
    "db_url": "sqlite:////freqtrade/user_data/tradesv3.sqlite",
    "timeframe": "4h",
    "cancel_open_orders_on_exit": false,
    "exit_profit_only": true,
    "unfilledtimeout": {
        "entry": 10,
        "exit": 30
    },
    "entry_pricing": {
        "price_last_balance": 0.0,
        "use_order_book": true,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing": {
        "use_order_book": true
    },
    "order_types": {
        "entry": "limit",
        "exit": "limit",
        "emergency_exit": "market",
        "force_exit": "market",
        "force_entry": "market",
        "stoploss": "market",
        "stoploss_on_exchange": false,
        "stoploss_on_exchange_interval": 60,
        "stoploss_on_exchange_limit_ratio": 0.99
    },
    "exchange": {
        "name": "binance",
        "key": "xxxx",
        "secret": "xxxx",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [],
        "pair_blacklist":  []
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 25,
            "sort_key": "quoteVolume",
            "refresh_period": 1800
        },
        {
            "method": "SpreadFilter",
            "max_spread_ratio": 0.005
        },
        {
            "method": "AgeFilter",
            "min_days_listed": 30
        },
        {
            "method": "PriceFilter",
            "low_price_ratio": 0.015
        },
        {
            "method": "RangeStabilityFilter",
            "lookback_days": 7,
            "min_rate_of_change": 0.05,
            "refresh_period": 1440
        },
        {
            "method": "ShuffleFilter"
        }
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.6,
        "minimum_expectancy": 0.2,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "xxxxx",
        "chat_id": "xxxx"
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "jwt_secret_key": "personalftapi",
        "CORS_origins": [
            "http://app-server:8080"
        ],
        "username": "freqtrader",
        "password": "xxxxxx"
    },
    "bot_name": "ft2",
    "initial_state": "running",
    "force_entry_enable": true,
    "internals": {
        "process_throttle_secs": 5
    }
}
```

> If you're seeing this for all pairs, then that would mean that you have a buy-signal for all pairs (unlikely, but possible).
No stake amount left can be a miss-configuration of stake (nothing changed in this regard) - like too high stake, or no balance in the wallet - or all available assets are in trades (but max_open_trades would still allow additional trade-slots).

It's only for the pairs I do not already have. Wallet has no BTC left to buy a new pair, all assets are in (9) trades, which is less than the allowed 15.

**Comment by xmatthias** [comment]
> Wallet has no BTC left to buy a new pair,

well this explains the messages for sure.

Now why it's trying to buy every pair is another topic - one that's tied to the strategy i'd say.

**Comment by klara31** [comment]
I get that, but why did this not happen on 2022.03? The wallet content hasn't changed...

**Comment by xmatthias** [comment]
What changed is at maximum the message - which might now be more verbose (we can look at that).
The behavior itself won't have changed in this regard.
