### ISSUE TITLE
DollySue

### ISSUE THREAD

**Issue by DollySue** [freqtrade/freqtrade#6770]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*

**Comment by DollySue** [comment]
go

**Comment by xmatthias** [comment]
Please post reasonable issues (with description / title) - or leave it be, thanks.

This issue is unfortunately pointless.
