### ISSUE TITLE
Support `bot_loop_start` when calling `plot-dataframe`

### ISSUE THREAD

**Issue by markdregan** [freqtrade/freqtrade#6776]
## Describe your environment
(if applicable)

  * Operating system: MacOS Monterey 12.3.1 (21E258)
  * Python Version: 3.8.9 (`python -V`)
  * CCXT version: 1.80.61 (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-4d5cdf0b8 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

TLDR: Suggest making the `bot_loop_start` callback work when using `plot-dataframe' CIL command. 

Motivation: 
- I use `bot_loop_start` to import external informative signals for my strategy
- This works well for live trading and backtesting
- A key requirement of workflow is to export dataframe-plots for inspection of the backtest

Ask:
- Perhaps this is already supported and just my bad. PLMK.
- When running `plot-dataframe` on a strategy that uses `bot_loop_start` an error is returned indicating that none of the external informative signals were defined and hence not available in `populate_indicators`. Note: backtests and trading live work without error for this. 

PLMK if anything else I could provide. And if there is a simple fix - a code pointer and I could look into implementing. 

Many thanks

**Comment by xmatthias** [comment]
If it's a one-time load (also in live) - maybe look at `bot_start()` - a new callback which is called only once when the strategy loads.

That said - `bot_loop_start()` should obviously be called there, too. 
If you're looking for a pointer - just look at plotting.py - and search for `bot_start()` - `bot_loop_start()` should be called right after that.

**Comment by markdregan** [comment]
Thanks Matthias. I'll plan to submit this PR for this.
