### ISSUE TITLE
Message in Telegram about Revoked API

### ISSUE THREAD

**Issue by lulu-angry** [freqtrade/freqtrade#6783]
## Describe your environment
(if applicable)

  * Operating system: ____Ubuntu 22.04
  * Python Version: _____ (3.4)
  * CCXT version: _____ (last)
  * Freqtrade Version: ____ (`develop last)

## Describe the enhancement

I'm here to submit to Freqtrade team an idea, who can help many user.
I describe my problem : Very often i forget to check about my API (Binance which remains valid for only 90 days).
And my order can stay locked (entry / exit) for 3/4 days.
This problem can kill stoploss or custom_exit.

I happened to find after relaunching my api positions at -89%
while my stop loss is configured at 25%.

It can kill a balance.

what do I suggest :
( I already know, i can see in the log than my API has revoked)
But i think too add a warning in telegram messaging can help user to know than their API was revoked and than Freqtrade can proced on any operation (of entry and exit on their account)

**Comment by xmatthias** [comment]
What would you expect freqtrade to do in that case? 
The only reasonable course of action would be to enter into "stopped" state - where your ROI / stoploss would again not be handled.
it can obviously alert you about it - but it's really a misconfiguration from the user side, i'm not 100% sure is worth the hastle to handle it (we'd probably have to properly handle this for every (authenticated) call we make to the exchange.


Based on the [binance dev forum](https://dev.binance.vision/t/permission-expired-for-api/6719) you can simply add a IP restriction to the key so the key does not expire after 90 days.

Assuming the bot runs for 90+ days, it's pretty safe to assume that the IP is static (it's a VPS), therefore putting an IP restriction on the key is the most reasonable thing to do, which will also increase the security as a positive side-effect.

You can always register additional keys for other purposes from other machines.

**Comment by lulu-angry** [comment]
"You can always register additional keys for other purposes from other machines." 
I'll keep in mind

Tanks Mathias

**Comment by xmatthias** [comment]
The above is a personal suggestion for API key handling. 

I'm not entirely decided on the feature per se - so if you believe it's anyway useful please leave this open for now.
