### ISSUE TITLE
Plotting Custom trailing stoploss similar to plotting an indicator

### ISSUE THREAD

**Issue by shakeel-appyhigh** [freqtrade/freqtrade#6784]
## Describe your environment

  * Operating system: Windows
  * Python Version:  3.9.9(`python -V`)
  * CCXT version: ccxt==1.80.61 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Is there any way to plot the stoploss as an indicator in the plot-dataframe function? I am implementing a custom trailing stoploss function where the trailing happens only when the closing price has moved atleast 2 times the ATR. I would like to verify if the trailing is happening properly or not, from the graph.

**Comment by xmatthias** [comment]
If your stoploss is an indicator - then this would be possible.

if it's dependent on the trade's entry price (which it usually is) - you'll not be able to plot this - as that part won't really be available during the `plot_*` methods.
