### ISSUE TITLE
Upgrade to latest version which includes shorts using PG

### ISSUE THREAD

**Issue by botzill** [freqtrade/freqtrade#6794]
## Describe your environment

  * Operating system: Mac OS
  * Python Version: 3.9.8 (`python -V`)
  * CCXT version: 1.63.55 (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

How can I upgrade to the latest version, migration script, I get the following error:

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) column "is_short" is of type boolean but expression is of type integer
LINE 38:             0 is_short, 0.0 interest_rate,
                     ^
```

Is there anyway I can set this to bool for postgres?

**Comment by botzill** [comment]
I did manually set `false is_short` in migration and it worked. is there a way to make this work for PG as well automatically?

**Comment by xmatthias** [comment]
Nice catch - unfortunately CI migrations are not running against postgres (it's pretty difficult to setup reliably in CI).

Fixed in develop.
