### ISSUE TITLE
Recursive list-strategies

### ISSUE THREAD

**Issue by WildOrangutan** [freqtrade/freqtrade#6795]
## Describe your environment

  Freqtrade Version: docker-c9498d01

## Describe the enhancement

I think `list-strategy` could use recursive search, to also search in sub-directories.

Context: 
I'm playing around with [freqtrade-strategies](https://github.com/freqtrade/freqtrade-strategies/tree/master/user_data/strategies) repo and they have strategies in sub-folders.

**Comment by WildOrangutan** [comment]
Hm, I just found out that there is a setting `recursive_strategy_search` in `config.json`. Would it be possible to maybe update [list-strategies](https://www.freqtrade.io/en/stable/utils/#list-strategies) documentation to mention that?

**Comment by xmatthias** [comment]
The most uptodate documentation will always be `freqtrade <command> --help`.

We try to keep other documentation uptodate - but the first reference point should still be --help (also because it's the easiest to reach).
