### ISSUE TITLE
Please add support for DIFX exchange.

### ISSUE THREAD

**Issue by mitulmlakhani** [freqtrade/freqtrade#6807]
Website URL: https://difx.com
Docs URL: https://docs.difx.com

**Comment by xmatthias** [comment]
A key requirement for freqtrade to support any exchange is existing support via [CCXT](https://github.com/ccxt/ccxt).

As it's currently not available (and the available PR https://github.com/ccxt/ccxt/pull/13171 will not be accepted as is, as it's violating their Contributing guidelines) - we will not be able to support this exchange at this point.

Once it's available via ccxt - best go through the [new exchange checklist](https://www.freqtrade.io/en/stable/developer/#implement-a-new-exchange-wip) yourself to see if it's working or what's missing if you're interested in this exchange.

Most likely (if the ccxt integration is done well - and if the API supports it) - there will be not many changes for this needed in freqtrade.
We can then look at individual issues as they come up - but there's no point in this until it's supported in ccxt.
