### ISSUE TITLE
Stoploss order status after unfilled sell order

### ISSUE THREAD

**Issue by aziba353** [freqtrade/freqtrade#6808]
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.9.9
  * CCXT version: 1.73.70  
  * Freqtrade Version: 2022.2.1
  
## Your question

Hi, I have a question about the procedure of the Freqtrade about handling of a trade that has an unfilled sell order and suddenly price drops to the stop-loss before timeout. As I know Binance can not get take-profit and stop-loss limit order at the same time, and if the limit order for selling is sent to the exchange, stop-loss can not be handled if price changes faster than timeout.
It would be appreciated if you can answer me.

**Comment by xmatthias** [comment]
your strategy decided to place a limit sell order - as such that order takes precedence until the order times out (or is cancelled by the corresponding callback).

As you correctly point out - the stoploss order will have been cancelled before placing the regular limit sell order - therefore you're obviously "at risk" in this stage.
if price falls below stoploss during that time, you'll most likely end up with an emergencysell at whatever price the coin is at that point - which can potentially be below your defined stoploss.

I'd recommend to look at the [pricing section](https://www.freqtrade.io/en/stable/configuration/#prices-used-for-orders) of the docs - which can help you determine a better sell price for your order, increasing chances of filling the order asap (which should be the goal for sell orders).

**Comment by aziba353** [comment]
Thanks @xmatthias for your kind consideration. As I understand Freqtrade only consider time-out function for cancelling a sell limit order if it didn't receive any request from rpc??? I mean it doesn't consider the space/gap that is in the order and current price to cancel an order or to initiate stoploss?

And does emergencysell will be executed automatically or we should do it with rpc?
Do you have any experience with IOC (Immediate Or Canceled) order that maybe can solve my issue? and finally have you ever seen such situation in your trades?

**Comment by xmatthias** [comment]
callbacks can [cancel orders](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-timeout-rules) based on whatever rule you define.

Freqtrade only uses timed timeouts (after X minutes/seconds) without callbacks.
An emergencysell will be triggered for stoploss sell orders which are placed above the current price (and therefore fail to be placed). It'll however only apply when using stoploss on exchange, in "non-exchange" scenarios, a regular stoploss order (market or limit, whatever you define) will be placed.

**Comment by aziba353** [comment]
Thanks a lot.

**Comment by aziba353** [comment]
@xmatthias 
Hi, If I enable stoploss-on-exchange for Binance or Kucoin, is it possible to have stoploss and take-profit together?

**Comment by xmatthias** [comment]
no. most exchanges only allow one order, which means your stake is then locked up - disallowing a second order with the same balance.

While there are exceptions (OCO on binance) - it's an edge-case we currently don't support.
