### ISSUE TITLE
enter_tag for long position is not working

### ISSUE THREAD

**Issue by lamantrra** [freqtrade/freqtrade#6809]
## Describe your environment

  * Operating system: Ubuntu 20.04.4 LTS
  * Python Version: 3.9.9
  * CCXT version: 1.80.61
  * Freqtrade Version: 2022.4.2
  

## Describe the problem:

After updating to version "2022.4.1", enter_tag does not showing properly in real transactions and backtest simulation and print "None" tag in telegram. But this option works well for exit_tag postion.

**Comment by stash86** [comment]
working fine on my bots. Without any more information/codes, we can't help you

**Comment by lamantrra** [comment]
Thanks to reply @stash86 
I founding the main problem. In the new version of freqtrade, I using [strategy migration checklist](https://www.freqtrade.io/en/stable/strategy_migration/) and rename all method to the new name. After rename one by one them To find the current problem, I came to the conclusion that the problem arises when the name of the "buy_tag" method is changed.
Every things like "exit_tag" and others working perfectly but when i changed "buy_tag" to "entry_tag" entry name it becomes empty and print "None".  
I have several strategies for entering a position, exactly when I change "buy_tag" to "entry_tag", the entry name of any of them does not work.

**Comment by stash86** [comment]
`enter_tag` is the correct one, not `entry_tag`

**Comment by lamantrra** [comment]
Yes. This was my problem and I'm really sorry. Everything worked fine. Thank you very much for your help @stash86

**Comment by pr0vieh** [comment]
> `enter_tag` is the correct one, not `entry_tag`

difficult change in structure ? maybe it should be made more consistent? to avoid mistakes ?

i had the same problem... but i spent a few hours trying to see the difference

I'm not sure but I haven't managed to do it until now at hyperopt is currently ignoring the new tags ?
its only working with buy and sell at parameters and the tags not found at strategy json files...

**Comment by xmatthias** [comment]
What's your reference point for this? 

Considering that the column is called `enter_long` and `enter_short` - i find `enter_tag` better than `entry_tag` - as it's better aligned.

**Comment by pr0vieh** [comment]
the enter tag sounds good at all
