### ISSUE TITLE
Bot not taking trades

### ISSUE THREAD

**Issue by ketank1000** [freqtrade/freqtrade#6810]
My environment 

  * Operating system: Ubuntu 22.04 (aws)
  * Freqtrade Version: 2022.3 (docker develop image)
  
Question:
I ran my bot for complete day but still no trades were taken. but in chart it shows all buy/exit signals.

<img width="1283" alt="Screenshot 2022-05-10 at 8 43 35 AM" src="https://user-images.githubusercontent.com/11884142/167536315-44c8b4a9-df2b-4f87-991d-57d82bf6c066.png">

Im running scalping strategy, where it takes around 200-250 trades per day. but non of the trade was taken in last 24 hrs. I checked for complete logs, there were no errors, only heartbeats and filter logs were visible.

This is my config file.

```
{
    "max_open_trades": 3,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "INR",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "use_exit_signal": true,
    "exit_profit_only": false,
    "ignore_roi_if_entry_signal": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "timeframe": "5m",
    "unfilledtimeout": {
      "entry": 10,
      "exit": 10,
      "exit_timeout_count": 0,
      "unit": "minutes"
    },
    "entry_pricing": {
      "price_side": "other",
      "use_order_book": true,
      "order_book_top": 1,
      "price_last_balance": 0.0,
      "check_depth_of_market": {
        "enabled": false,
        "bids_to_ask_delta": 1
      }
    },
    "exit_pricing": {
      "price_side": "other",
      "use_order_book": true,
      "order_book_top": 1
    },
    "exchange": {
      "name": "binance",
      "key": "",
      "secret": "",
      "ccxt_config": {
        "enableRateLimit": true
      },
      "ccxt_async_config": {
        "enableRateLimit": true,
        "rateLimit": 50
      },
      "pair_whitelist": [],
      "pair_blacklist": [
         "(BTCUSDT_.*|ETHUSDT_.*)",
         "(GT|HT)/.*",
         "(WBTC|BSV|BTCDOM|DEFI)/.*",
         ".*(_PREMIUM|BEAR|BULL|DOWN|HALF|HEDGE|UP|[1235][SL])/.*",
         "(AUD|BRZ|CAD|CHF|EUR|GBP|HKD|IDRT|JPY|NGN|RUB|SGD|TRY|UAH|USD|ZAR|UST)/.*",
         "(BUSD|CUSDT|DAI|PAX|PAXG|SUSD|TUSD|USDC|USDT|VAI|USDN)/.*",
         "(ACM|AFA|ALA|ALL|APL|ASR|ATM|BAR|CAI|CITY|FOR|GOZ|IBFK|LEG|LOCK-1|NAVI|NMR|NOV|OG|PFL|PSG|ROUSH|STV|TH|TRA|UCH|UFC|YBO)/.*"
          ]
    },
    "pairlists": [
      {
        "method": "VolumePairList",
        "number_assets": 100,
        "sort_key": "quoteVolume",
        "refresh_period": 1800
      },
      {"method": "AgeFilter", "min_days_listed": 14},
      {"method": "SpreadFilter", "max_spread_ratio": 0.005},
      {
        "method": "PriceFilter",
        "min_price": 0.001
      },
      {
        "method": "RangeStabilityFilter",
        "lookback_days": 3,
        "min_rate_of_change": 0.05,
        "refresh_period": 1800
      },
      {
        "method": "VolatilityFilter",
        "lookback_days": 3,
        "min_volatility": 0.02,
        "max_volatility": 0.75,
        "refresh_period": 43200
      },
      {"method": "ShuffleFilter"}
    ],
    "edge": {
      "enabled": false,
      "process_throttle_secs": 3600,
      "calculate_since_number_of_days": 14,
      "allowed_risk": 0.01,
      "stoploss_range_min": -0.01,
      "stoploss_range_max": -0.1,
      "stoploss_range_step": -0.01,
      "minimum_winrate": 0.60,
      "minimum_expectancy": 0.20,
      "min_trade_number": 3,
      "max_trade_duration_minute": 1440,
      "remove_pumps": false
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "internals": {
        "process_throttle_secs": 5
    }
  }
```

My strategy works perfectly in backtesting. but when in live/dryrun it fails to take trade. Is it because there are so many buy/exit signals ? or is my config file is miss configured ?

Other strategies with 30-40 trades per day works perfect normally.

**Comment by xmatthias** [comment]
The config doesn't seem too suspect - at least not at first glance - although you'll need to be careful with versions.

if anything is wrong/missing, then the logs would show that.

Your configuration seems to be made for futures - which 2022.3 (the version you specify) does not support yet (the current version, 2022.4 does).
This also means, if you're using `enter_long` as column in your strategy, then the bot will not know about this column (older versions used different namings).

---
 
One thing that can cause such things are [colliding signals](https://www.freqtrade.io/en/latest/strategy-customization/#colliding-signals) - which you'll really only be able to spot when you hide one or the other and look at specific spots on the chart (They'll overlap).

In general, strategies that work fine in live, but fail in backtesting often have one of the [strategy mistakes](https://www.freqtrade.io/en/latest/strategy-customization/#common-mistakes-when-developing-strategies) contained - using future data which is not available for the "latest" candle.
Your chart will look normal at first glance, but you'll never have a signal at the "very last" candle - therefore there'll never be any buys.

**Comment by ketank1000** [comment]
Damm ! you are right. after a long debug I found out my signals weren't generated at last candle.
Thanks for point it out.
