### ISSUE TITLE
Additional stats on /profit

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#6816]
I would like to suggest adding in `/profit` command for telegram the following information: avg, daily profit, profit factor, drawdown.
Follow an example as reference:
```
ROI: Closed trades
∙ 1552.482 USD (3.20%) (7.76 Σ%)
∙ 1552.482 USD
ROI: All trades
∙ 1451.769 USD (2.37%) (7.26 Σ%)
∙ 1451.769 USD
Total Trade Count: 9
First Trade opened: 3 days ago
Latest Trade opened: 14 hours ago
Win / Loss: 7 / 1
Avg. Duration: 11:29:21
Avg. daily profit: 1.8%
Profit Factor: 2.1
Absolute Drowdown: 0.5%
Best Performing: AAVE/USD: 10.03%
```

New parts would effectively be:
* Avg. daily profit
* Profit Factor
* Absolute Drawdown

**Comment by xmatthias** [comment]
I've slightly adapted the above  (bottom list) to better show what would be the change to the current version.

**Comment by xmatthias** [comment]
The only thing #6987 will not provide is "Avg. daily profit".

I'm however also not entirely sure if we're going to provide this. 
Calculating this correctly is quite difficult with dynamic stakes. It works "mostly" for `/daily` and `/monthly` - but that's for limited time-ranges.
Doing the same calculation "forever" might delay the command beyond being useful / interactive.

**Comment by ghost** [comment]
Thank you, much appreciated.
I also noticed the line "Trading volume", nice.

**Comment by xmatthias** [comment]
Hope you're ok with me closing this one now. 

The relative daily profit is available in `/daily` (and `/weekly`, ...) - providing it here as well is currently not planned.
