### ISSUE TITLE
where to load scikit machine learning model in freqtrade ?

### ISSUE THREAD

**Issue by rubyrailsninja** [freqtrade/freqtrade#6818]
Hi !

first at all, thanks for this wonderful tool :D

I would like to know where is the best place to load a machine learning model in freqtrade ? 
Not in strategy since it would load the model every timeframe I choose ...

```
loaded_model = pickle.load(open(filename, 'rb')) => where to use this ??
result = loaded_model.score(X_test, Y_test) => will be used in strategy file to determine if place order or not
```

thanks for your kind reply :)

**Comment by xmatthias** [comment]
well the strategy is still the right place - just don't place it in the `populate_*()` methods.

Most likely, using [`bot_start()`](https://www.freqtrade.io/en/latest/strategy-callbacks/#bot-start) is the right place - it's running once on startup. 
You can then save that model in the strategy (`self.loaded_model= ...`) - and access it from other locations in the strategy.

**Comment by rubyrailsninja** [comment]
thanks for your reply ;)

**Comment by slowdive42** [comment]
> well the strategy is still the right place - just don't place it in the `populate_*()` methods.
> 
> Most likely, using [`bot_start()`](https://www.freqtrade.io/en/latest/strategy-callbacks/#bot-start) is the right place - it's running once on startup. You can then save that model in the strategy (`self.loaded_model= ...`) - and access it from other locations in the strategy.

I saved my models in user_data/models, but it returns no such file.
```
    def bot_start(self, **kwargs) -> None:
        """
        Called only once after bot instantiation.
        :param **kwargs: Ensure to keep this here so updates to this won't break your strategy.
        """
        # if self.config['runmode'].value in ('live', 'dry_run'):
            # Assign this to the class by using self.*
            # can then be used by populate_* methods
        self.loaded_model = []
        for i in range(10):
            model = joblib.load(f'user_data\\models\\btc_1m_lgbm_models\\lgb_clf{i}.pkl')
            self.loaded_model.append(model)
```
returns:
2024-05-13 06:23:35,346 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error [Errno 2] No such file or directory: 'user_data\\models\\btc_1m_lgbm_models\\lgb_clf0.pkl' calling <bound method btc_1m_lgbm_strategy.bot_start of <btc_1m_lgbm_strategy.btc_1m_lgbm_strategy object at 0x7f3464e407a0>>
Traceback (most recent call last):
  File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/user_data/strategies/btc_1m_lgbm_strategy.py", line 119, in bot_start
    model = joblib.load(f'user_data\\models\\btc_1m_lgbm_models\\lgb_clf{i}.pkl')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'user_data\\models\\btc_1m_lgbm_models\\lgb_clf0.pkl'
2024-05-13 06:23:35,347 - freqtrade - ERROR - [Errno 2] No such file or directory: 'user_data\\models\\btc_1m_lgbm_models\\lgb_clf0.pkl'
