### ISSUE TITLE
Pairlist OffsetFilter

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#6824]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

With OffsetFilter one can set the position of the first pair in the list, Freqtrade will use to trade. The documentation describes the functionality as a "pairlist splitter".
If I have two bots, the first one with offset 10, the second one with offset 20, I guess, that the first bot will have identical pairs, the ones after the position 20. Can I set an endpoint in addition to eliminate this?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
That's currently only possible by placing a volumepairlist after the offset filter (with 10 records).

That's however less than ideal, so enhancing the offsetFilter by a "limit" method does make sense.
