### ISSUE TITLE
Enter signal/tag bug

### ISSUE THREAD

**Issue by quantsirius** [freqtrade/freqtrade#6826]
* Operating system: Ubuntu
  * Python Version: Python 3.8.10
  * CCXT version: ccxt==1.80.61
  * Freqtrade Version: freqtrade 2022.4.2

## Describe the problem:

I don't know really what is going on. The signal is disabled (sma_long) as picked zero but it is work. It appears when I change the sequence of the signals (longs and shorts). Maybe I'm missing something in the syntax, but can not find the problem.

![image](https://user-images.githubusercontent.com/67390955/168426662-2a166527-7fa5-4c99-9533-f71cf2a7eb46.png)

```
> def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
>         """
>         Based on TA indicators, populates the entry signal for the given dataframe
>         :param dataframe: DataFrame
>         :param metadata: Additional information, like the currently traded pair
>         :return: DataFrame with entry columns populated
>         """
> 
>         dataframe.loc[
>         (
>             (dataframe['rand'] == 5)
>         ),
>         ['enter_long', 'enter_tag']] = (0, 'random_long')
> 
> 
>         dataframe.loc[
>         (
>             (dataframe['rand'] == 5)
>         ),
>         ['enter_short', 'enter_tag']] = (1, 'random_short')
>         
> 
>         dataframe.loc[
>         (
>             (qtpylib.crossed_above(dataframe['sma7'], dataframe['sma20']))
>         ),
>         ['enter_long', 'enter_tag']] = (0, 'sma_long')
> 
>         return dataframe
```

**Comment by xmatthias** [comment]
there's nothing obviously wrong with your code.

The most common case in such scenarios is that you are backtesting a different strategy/file than the one backtesting uses.

You can use `freqtrade list-strategies` to see strategies - it'll also point out potential problems (duplicate strategies).

**edit** actually there IS something wrong with your code.

whenever `(qtpylib.crossed_above(dataframe['sma7'], dataframe['sma20']))` is true - you'll assign the `enter_tag` column (even if you assign 0 to the `enter_long` column - you'll still assign `enter_tag`).

The above result simply means that you've had 22 "collisions" between the "random_short" - and "sma_long" signals.

to properly disable a signal, either comment out the whole sequence  or add a "always false" condition there (something around `& False` - maybe).

**Comment by jxbzwnqv** [comment]
There are no any problem with duplicate strategies. 
I checked for other signals, the collision happens when two signals come true at the same time.
I don't know is it a bug or only the note we need to know. Thanks for explanation.

**Comment by quantsirius** [comment]
> there's nothing obviously wrong with your code.
> 
> The most common case in such scenarios is that you are backtesting a different strategy/file than the one backtesting uses.
> 
> You can use `freqtrade list-strategies` to see strategies - it'll also point out potential problems (duplicate strategies).
> 
> **edit** actually there IS something wrong with your code.
> 
> whenever `(qtpylib.crossed_above(dataframe['sma7'], dataframe['sma20']))` is true - you'll assign the `enter_tag` column (even if you assign 0 to the `enter_long` column - you'll still assign `enter_tag`).
> 
> The above result simply means that you've had 22 "collisions" between the "random_short" - and "sma_long" signals.
> 
> to properly disable a signal, either comment out the whole sequence or add a "always false" condition there (something around `& False` - maybe).

There are no any problem with duplicate strategies.
I checked for other signals, the collision happens when two signals come true at the same time.
I don't know is it a bug or only the note we need to know. Thanks for explanation.

**Comment by quantsirius** [comment]
For clearer understanding. This does not affect the result of the strategy, since there are not long trades was opened on the sma_long. Just broken ENTER TAG STATS

**Comment by xmatthias** [comment]
think about it the "excel" way - a dataframe is really just a table (with rows and columns).
You assign 2 columns at a time - but only certain rows (whichever rows are filtered at that time).

If you now assign one row twice ("enter_tag") - you might end up overwriting the prior tag.
Obviously, you're not overwriting every row - just a few (22, in your case). 

What counts for freqtrade is the endresult (the dataframe you return). 
Freqtrade will not know about any intermediate state - only about the end-result - and how it was assigned.

As your strategy is reassigning certain rows - both enter-tags can appear.

deactivating signals with `0` works without assigning  enter_tag - but with enter_tag, this will not fully disable that line (there will be no operational difference, but the tags will be assigned anyway).
