### ISSUE TITLE
populate_indicators runs randomly after init

### ISSUE THREAD

**Issue by mosquitotrip** [freqtrade/freqtrade#6829]
## Describe your environment

  * Operating system: Debian 
  * Python Version: 3.9.12 (`python -V`)
  * CCXT version: 1.82.40 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop-8e9384e8e (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I'm running optimization in populate_indicators which I assume will run a single time on boot, for some reason after a while the populate_indicators loop is running again, forcing new parameters on the indicator, this can occur within the trade and can cause missing a sell signal. 

1. The indicators optimization process for parameters is running inside populate_indicators, if no parameters are defined, there will be an exception and freqtrade will try again until suitable parameters are met.

It's a straightforward process but I cannot find why populate_indicators run after the first initialization, every once in a while.

### Steps to reproduce:

  1. The only way to reproduce it is by adding a simple logger.info() inside populate_indicators, it will appear after a while in the logs or freqtrade.strategy.interface - DEBUG - Populating indicators for pair appears in logs
  
### Observed Results:

  * What happened?
  Indicators parameters were changes on-the-fly
  * What did you expect to happen?
  populate_indicators to run only once

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2022-05-15 08:31:39 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 0.00 s, last iteration took 11.94 s.
2022-05-15 08:31:39 - freqtrade.worker - DEBUG - ========================================
2022-05-15 08:31:39 - freqtrade.exchange.exchange - DEBUG - Refreshing candle (OHLCV) data for 1 pairs
2022-05-15 08:31:39 - freqtrade.exchange.exchange - DEBUG - Using cached candle (OHLCV) data for LUNA/USDT, 1m, spot ...
2022-05-15 08:31:39 - freqtrade.strategy.interface - DEBUG - TA Analysis Launched
2022-05-15 08:31:39 - freqtrade.strategy.interface - DEBUG - Populating indicators for pair LUNA/USDT.
  ```
and
  ```
2022-05-15 08:34:11 - freqtrade.worker - DEBUG - ========================================
2022-05-15 08:34:11 - freqtrade.exchange.exchange - DEBUG - Refreshing candle (OHLCV) data for 1 pairs
2022-05-15 08:34:11 - freqtrade.exchange.exchange - DEBUG - one_call: 90000000 msecs (a day)
2022-05-15 08:34:11 - freqtrade.exchange.exchange - DEBUG - Fetching pair LUNA/USDT, interval 1m, since 1652423700000 (2022-05-13T06:35:00+00:00) ...
2022-05-15 08:34:11 - freqtrade.exchange.exchange - DEBUG - Fetching pair LUNA/USDT, interval 1m, since 1652513700000 (2022-05-14T07:35:00+00:00) ...
2022-05-15 08:34:12 - freqtrade.exchange.exchange - DEBUG - Done fetching pair LUNA/USDT, interval 1m ...
2022-05-15 08:34:13 - freqtrade.exchange.exchange - DEBUG - Done fetching pair LUNA/USDT, interval 1m ...
2022-05-15 08:34:13 - freqtrade.data.converter - DEBUG - Converting candle (OHLCV) data to dataframe for pair LUNA/USDT.
2022-05-15 08:34:13 - freqtrade.data.converter - DEBUG - Dropping last candle
2022-05-15 08:34:13 - freqtrade.strategy.interface - DEBUG - TA Analysis Launched
2022-05-15 08:34:13 - freqtrade.strategy.interface - DEBUG - Populating indicators for pair LUNA/USDT.
  ```

logger.info:
  ```
kucoin3    | 2022-05-15 09:04:02,984 - root - INFO - (567, 627)
kucoin3    | 2022-05-15 09:07:33,783 - root - INFO - (567, 627)
  ```
and logger.info proves populate_indicators runs in loop (which cause the opt'd parameters to change)
  ```
kucoin3    | 2022-05-15 09:08:14,090 - root - INFO - (437, 672)
  ```
after disabling process_only_new_candles:
  ```
kucoin3    | 2022-05-15 09:51:33,627 - freqtrade.freqtradebot - INFO - Updating 0 open orders.
kucoin3    | 2022-05-15 09:51:56,733 - root - INFO - (447, 627)
kucoin3    | 2022-05-15 09:52:01,872 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='develop-8e9384e8e', state='RUNNING'
kucoin3    | 2022-05-15 09:52:17,516 - root - INFO - (447, 627)
kucoin3    | 2022-05-15 09:53:04,745 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='develop-8e9384e8e', state='RUNNING'
kucoin3    | 2022-05-15 09:53:18,519 - root - INFO - (447, 627)
kucoin3    | 2022-05-15 09:54:05,530 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='develop-8e9384e8e', state='RUNNING'
kucoin3    | 2022-05-15 09:54:18,985 - root - INFO - (447, 627)
kucoin3    | 2022-05-15 09:55:05,910 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='develop-8e9384e8e', state='RUNNING'
kucoin3    | 2022-05-15 09:55:22,093 - root - INFO - (447, 627)
kucoin3    | 2022-05-15 09:56:15,987 - root - INFO - (447, 627)
kucoin3    | 2022-05-15 09:56:20,341 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='develop-8e9384e8e', state='RUNNING'
kucoin3    | 2022-05-15 09:57:41,412 - root - INFO - (447, 627)
kucoin3    | 2022-05-15 09:57:43,423 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='develop-8e9384e8e', state='RUNNING'
kucoin3    | 2022-05-15 09:58:18,502 - root - INFO - (457, 637)
kucoin3    | 2022-05-15 09:58:45,439 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='develop-8e9384e8e', state='RUNNING'
kucoin3    | 2022-05-15 09:59:23,717 - root - INFO - (447, 627)
  ```
As a workaround i did an 'if in' loop turning the parameters to global vars, currently testing it with single pair, will it have an effect when running with multiple pairs?

**Comment by xmatthias** [comment]
Please make sure to read the documentation before opening an issue, especially the [bot basics](https://www.freqtrade.io/en/stable/bot-basics/#bot-execution-logic) page - which quite clearly summarizes which method is running when/where.

`populate_indicators()` is expected to be running roughly every 5 seconds (once per iteration) - unless you specify `process_only_new_candles=True` - which will run the analysis only once per candle (not necessarily right after the candle arrives - depending on the state of open trades (for that pair, and globally).

As such - the above is not a bug, but expected behavior.

On 1m candles you'll need to be rather careful with timing - if you're running some non-optimized (speak slow) indicators, you might see quite some delays.

**Comment by mosquitotrip** [comment]
Thank you @xmatthias, Maybe I should rephrase my question

As I'm running a calculation inside populate_indicators() I would need to perform it a single time.

What would be the best approach to avoid re-processing? 

I would be thinking of a global var of some sort, but that doesn't support f-string, even if I use unique identified to the series (i.e dataframe[f'something_{quote}'] one the next iteration the dataframe won't consist of the unique identifier to use as a rule.

Optimization time is less then 10 seconds for 1000x1000 parameters so the bot still operates in the proper window.

**Comment by xmatthias** [comment]
To run something a single time, consider `[bot_start()](https://www.freqtrade.io/en/stable/strategy-callbacks/#bot-start)` or [bot_loop_start()](https://www.freqtrade.io/en/stable/strategy-callbacks/#bot-loop-start) ... 

You can in theory also [store information](https://www.freqtrade.io/en/stable/strategy-advanced/#storing-information) - but be sure to not store too much data there (and it'll not be persisted -> gone once you restart the bot.

**Comment by mosquitotrip** [comment]
Brilliant, Thanks much.

bot_start() and bot_loop_start() cannot process dataframes, right?

Would it make sense to change the iteration throttle? or it will affect populate_buy/sell as well?

**Comment by xmatthias** [comment]
it'll affect everything - including stoploss / roi checking.

**Comment by mosquitotrip** [comment]
Looking good!
```
binance1    | 2022-05-15 15:17:40,153 - root - INFO - BTCUP/USDT Optimizing
binance1    | 2022-05-15 15:17:48,610 - root - INFO - (2, 152)
binance1    | 2022-05-15 15:17:48,626 - root - INFO - ETHUP/USDT Optimizing
binance1    | 2022-05-15 15:17:49,133 - root - INFO - (317, 347)
binance1    | 2022-05-15 15:17:49,149 - root - INFO - ADAUP/USDT Optimizing
binance1    | 2022-05-15 15:17:49,727 - root - INFO - (207, 217)
binance1    | 2022-05-15 15:17:49,744 - root - INFO - LINKUP/USDT Optimizing
binance1    | 2022-05-15 15:17:50,247 - root - INFO - (72, 147)
binance1    | 2022-05-15 15:17:50,262 - root - INFO - BNBUP/USDT Optimizing
binance1    | 2022-05-15 15:17:50,770 - root - INFO - (67, 117)
binance1    | 2022-05-15 15:17:50,785 - root - INFO - TRXUP/USDT Optimizing
binance1    | 2022-05-15 15:17:51,360 - root - INFO - (47, 122)
binance1    | 2022-05-15 15:17:51,375 - root - INFO - XRPUP/USDT Optimizing
binance1    | 2022-05-15 15:17:51,881 - root - INFO - (27, 162)
binance1    | 2022-05-15 15:17:51,897 - root - INFO - DOTUP/USDT Optimizing
binance1    | 2022-05-15 15:17:52,398 - root - INFO - (317, 347)
```
and
```
kucoin3     | 2022-05-15 15:20:07,597 - root - INFO - LUNA/USDT Already Optimized
kucoin3     | 2022-05-15 15:20:07,597 - root - INFO - (972, 1072)
binance1    | 2022-05-15 15:20:12,625 - root - INFO - BTCUP/USDT Already Optimized
binance1    | 2022-05-15 15:20:12,626 - root - INFO - (2, 152)
binance1    | 2022-05-15 15:20:12,645 - root - INFO - LINKUP/USDT Already Optimized
binance1    | 2022-05-15 15:20:12,645 - root - INFO - (72, 147)
binance1    | 2022-05-15 15:20:12,659 - root - INFO - BNBUP/USDT Already Optimized
binance1    | 2022-05-15 15:20:12,659 - root - INFO - (67, 117)
binance1    | 2022-05-15 15:20:12,673 - root - INFO - TRXUP/USDT Already Optimized
binance1    | 2022-05-15 15:20:12,673 - root - INFO - (47, 122)
binance1    | 2022-05-15 15:20:12,687 - root - INFO - XRPUP/USDT Already Optimized
binance1    | 2022-05-15 15:20:12,687 - root - INFO - (27, 162)
binance1    | 2022-05-15 15:20:12,701 - root - INFO - DOTUP/USDT Already Optimized
binance1    | 2022-05-15 15:20:12,701 - root - INFO - (317, 347)
binance1    | 2022-05-15 15:20:16,599 - root - INFO - ETHUP/USDT Already Optimized
binance1    | 2022-05-15 15:20:16,599 - root - INFO - (317, 347)
binance1    | 2022-05-15 15:20:16,614 - root - INFO - ADAUP/USDT Already Optimized
binance1    | 2022-05-15 15:20:16,614 - root - INFO - (207, 217)
```

**Comment by mosquitotrip** [comment]
![image](https://user-images.githubusercontent.com/105578390/168812294-799b8b6c-24d5-48cb-9246-f2805983d0d1.png)

Fix works ;p

Thanks fellas.

(roi set to 99%)
