### ISSUE TITLE
Force run populate_indicators after successful exit (trade)

### ISSUE THREAD

**Issue by mosquitotrip** [freqtrade/freqtrade#6830]
## Describe your environment
(if applicable)

  * Operating system: Debian
  * Python Version: 3.9.12 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

add 'populate_indicators_after_exit = True/False' in strategy configuration

This functionality will allow users to re-run populate_indicators after a successful trade, as optimization can occur on-the-fly, the only loop possible to run this is populate_indicators, which need to be re-run is after a successful trade.

Thank you

**Comment by xmatthias** [comment]
It's unclear what your trying to archive - or why you think this is even necessary.

Unless you set `process_only_new_candles=True` - freqtrade will run all `populate_*` methods for every iteration (roughly every 5 seconds by default) - so the maximum delay between "closed trade" and "populate_*" will be roughly 5 seconds. 

I currently don't see what a new option would bring on top of that.

**Comment by mosquitotrip** [comment]
@xmatthias You cleared this in another thread #6829 

This can be closed, Thank you
