### ISSUE TITLE
How to check for a successful trade in previous candle

### ISSUE THREAD

**Issue by mosquitotrip** [freqtrade/freqtrade#6831]
## Describe your environment

  * Operating system: Debian
  * Python Version: 3.9.12 (`python -V`)
  * CCXT version: 1.82.40 (`pip freeze | grep ccxt`)
  * Freqtrade Version: develop-8e9384e8e (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi,

This suppose to be quite simple, I would like to access previous candle trade data, I assume "freqtrade.persistence.Trade" is the direction, but can't find any example in the documentation (https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-trades)

To be more specific, I need to build a rule which is based on successful trade exit in the previous candle.

Thank You!

**Comment by xmatthias** [comment]
Using Trade data in `populate_*` methods is not possible during backtesting.

While you can do that for live mode - you'll be taking away your possibility to backtest.
callbacks can use Trade data just fine (prior trades).

**Comment by mosquitotrip** [comment]
I'm not backtesting/hyperopt'ing with FT so I should be good.

**Comment by xmatthias** [comment]
Then the link you posted above will give you what you need - which is a way to query the database for trades.

It's then up to you / the strategy to determine the proper way to find the information you need.

**Comment by mosquitotrip** [comment]
Thanks @xmatthias, I just used custom_info method, I think clearing the values is possible in confirm_trade_exit() 

That can be also an option, I assume the calls are sequential so confirm_trade_exit() is performed after populate_sell...() and on the next populate_indicators() the values should be cleared.

I couldn't find where 'sell' signals are stored, dataframe['sell'] is not visible in populate indicators()

There is no post trade helper right?

**Comment by xmatthias** [comment]
no - and honestly, i also don't see a need for this.

Once a trade is closed, it's done and over with. Future signals should not directly depend on the prior trade (other than maybe avoiding this pair for a while - which can be accomplished with [protections](https://www.freqtrade.io/en/stable/plugins/#protections)

populate_indicators gets a clean dataframe each time. 
Prior signals will not be there - and they shouldn't be.
by relying a particular sequence of events (which involves both populate* and callbacks) - you'll be running into problems in certain cases (bot restart, for example) - so i'd strongly advise to properly think through what you're really after.

**Comment by mosquitotrip** [comment]
Problem solved with clearing self.custom_info[f"{pair}"] inside confirm_trade_exit()

**Comment by moinonin** [comment]
> no - and honestly, i also don't see a need for this.
> 
> Once a trade is closed, it's done and over with. Future signals should not directly depend on the prior trade (other than maybe avoiding this pair for a while - which can be accomplished with [protections](https://www.freqtrade.io/en/stable/plugins/#protections)
> 
> populate_indicators gets a clean dataframe each time. Prior signals will not be there - and they shouldn't be. by relying a particular sequence of events (which involves both populate* and callbacks) - you'll be running into problems in certain cases (bot restart, for example) - so i'd strongly advise to properly think through what you're really after.

I could see how this can be applied. Especially with futures markets. For instance, you can loop back and say if the immediate out-going asset was a short-trade, you would want to enter long in the next candle. Of course you may want to add some other momentum indicators.
