### ISSUE TITLE
Gate.io Futures candle amount

### ISSUE THREAD

**Issue by ZerGo0** [freqtrade/freqtrade#6849]
Hey,

I was wondering if there is a candle limit for Gate.io? FreqUI only shows 100 candles, but I have checked the docs and checked the code and couldn't find any limit like that. 

Start-up candle count also doesn't seem to change anything.

Using latest dev version.

**Comment by xmatthias** [comment]
None that i'm aware off - but a quick test with ccxt shows that it's in fact the case (although it doesn't appear to be a limitation of the api).

I'll look into this - it'll however have to be fixed in ccxt.

https://github.com/ccxt/ccxt/issues/13298

**Comment by TMBPRocks** [comment]
Hey, 
i had the same 100 candle problem in dry/live. 
Just found some workaround to get more candles.
You have reduce the value "ohlcv_candle_limit" to 400 in "./freqtrade/exchange/gateio.py".
After the change i get 799 candles in debugger and my bot started trading.

**Comment by xmatthias** [comment]
Latest ccxt does fix this.
