### ISSUE TITLE
Backtest signals

### ISSUE THREAD

**Issue by vdun** [freqtrade/freqtrade#6852]
## Describe the enhancement
Add the ability to import signals from a file (e.g. csv) and backtest them.

Example template:
Date, Pair, Direction, Entry, TakeProfit_1, TakeProfit_2, TakeProfit_3, Stoploss
2021-01-01 00:55:41 UTC, BTC/USDT, long, 30000, 31000, 32000, 33000, 25000 
2021-01-01 00:55:41 UTC, ETH/USDT, short, 3500, 3400, 3300, 3200, 4000
...

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Freqtrade's concept is based on calculating the signals as part of the strategy, not to import them from some random source.
That said - there's nothing preventing you from importing signals, combining them with the dataframe and use the signals as part of that. It's a regular python class - where you can do (almost) everything you desire, assuming proper python knowledge (or the will to experiment).

Freqtrade is also not a "backtest only" application as such - but backtesting is part of the preparation steps for regular trading operatoins. I also doubt that you will be able to run with external signals in live - although i guess that depends on the external source.

I don't see this as "builtin" functionality though - as everyone will have a different format.
