### ISSUE TITLE
Show current ROI in Freqtrade UI Trade Detail

### ISSUE THREAD

**Issue by medenlin** [freqtrade/freqtrade#6855]
## Describe your environment
(if applicable)

  * Operating system: any
  * Python Version: any (`python -V`)
  * CCXT version: any (`pip freeze | grep ccxt`)
  * Freqtrade Version: any (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

I think it would be good to show the current ROI (percent and rate) in Freqtrade UI -> Trade Detail tab. As a current stoploss now.

**Comment by xmatthias** [comment]
Current profit is shown in the trade detail tab already.

it's unclear what you'd expect from a ROI visualization - i think it'd mostly be missleading - as ROI can jump around (depending on settings) - and exits can come at any point in time due to other scenarios (like custom-sell, or other sell types).

**Comment by xmatthias** [comment]
Going to close this as the requirement is unclear and we got no further feedback.

**Comment by medenlin** [comment]
For example, I use a minimal_roi table for minimize a long-time order losses in my strategy:
`minimal_roi = {
        "0": 0.20, 
        "1440": 0.05, 
        "2880": 0.00, 
        "5760": -0.05, 
        "6480": -0.10, 
        "7200": -0.15, 
        "7920": -0.20, 
        "8640": -0.25, 
        "9360": -0.30, 
        "10800": -0.40, 
        "12240": -0.50, 
        "13680": -0.60, 
        "15120": -0.70, 
        "16560": -0.80, 
    }`
And, I think it would be good to show the current ROI (percent and rate) in Freqtrade UI or Telegram bot (by "status <n>" command)
