### ISSUE TITLE
What's the difference between 'forcesell limit' and forcesell market'?

### ISSUE THREAD

**Issue by lmy931** [freqtrade/freqtrade#6860]
Hi,

I find two options in the front UI: 'forcesell limit' and forcesell market'. I want to know the difference between these two options.

Please see my screenshot below.

<img width="667" alt="Screen Shot 2022-05-18 at 11 20 48 pm" src="https://user-images.githubusercontent.com/38743605/169058815-11e4795f-b76b-4dee-aff6-005423716ba3.png">

**Comment by froggleston** [comment]
They will create a sell order on the exchange, with certain properties. I suggest you read up on the differences between limit and market orders: https://www.investopedia.com/ask/answers/100314/whats-difference-between-market-order-and-limit-order.asp

**Comment by xmatthias** [comment]
That's exactly the case. Limit order vs. market order.

they behave differently on the exchange (market orders always fill immediately, but at an undefined price.

**Comment by lmy931** [comment]
Thanks for your explanation!
