### ISSUE TITLE
Trade class discrepancy between trade and backtesting modules

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#6863]
## Describe your environment

  * Operating system: linux
  * Python Version: 3.10.4
  * CCXT version: 1.82.61
  * Freqtrade Version: d5486f17d8ad8261f109ccb400ecc59eac9affa8
  
## Describe the problem:

I noticed that in a dryrun the `Trade` object's datetimes in custom_stoploss couldn't be compared directly with df.date with error: `Invalid comparison between" dtype=datetime64[ns, UTC] and datetime`.

It could be fixed with wrapping the `Trade`'s datetimes with `pytz.utc.localize()` because Trade's datetimes were apparently naive.

But backtesting had another idea because it gave `Not naive datetime (tzinfo is already set)` after that change.

**Comment by epigramx** [comment]
So it appears a fix is (apart from using different code in our strategies for both modules), the trade module's `Trade` class datetimes to have a set `tzinfo`, because it would both avoid that discrepancy and they should have a set `tzinfo` anyway. 

Do I miss something (other than "old strategies may break")?

**Comment by xmatthias** [comment]
The trade object provides a property in `open_date_utc` which is to be used for comparisons, which is aligned across both backtesting and regular runs.

**Comment by epigramx** [comment]
Hrm ok. Why doesn't the trade module include it in the datetime by default btw? Performance or legacy?

**Comment by xmatthias** [comment]
Neither - it's a sqlalchemy limitation with how it works with timezone-aware timestamps.
if your DB supports timezone-aware timestamps, it MAY be in the correct timezone when it comes back out.
for sqlite - that's not the case - therefore the only safe way is to use the property.

**Comment by epigramx** [comment]
It makes sense, and I guess they can't help it much either, because they'd want to use only the underlying db to hold data.
