### ISSUE TITLE
[low prio] h11._util.RemoteProtocolError: illegal request line, right after accessing frequi, after it's been idle for a while

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#6867]
## Describe your environment

  * Operating system: linux
  * Python Version: 3.8.10
  * CCXT version: 1.82.61
  * Freqtrade Version: d5486f17d8ad8261f109ccb400ecc59eac9affa8
  
## Describe the problem:

This is probably benign because it never crashes the software or the web ui but I wondered what it is because it's pretty cryptic and I've been seeing it for months so it's not a new issue.

Basically if frequi was not used for a while (e.g. several hours): the log may drop this kind of unhandled exception (on browser connection) that repeats about 4 times(immediately) before it stops:

```
2022-05-21 06:19:29,469 - uvicorn.error - WARNING - Invalid HTTP request received.
Traceback (most recent call last):
  File "/home/asdf/freqtrade/.env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 129, in handle_events
    event = self.conn.next_event()
  File "/home/asdf/freqtrade/.env/lib/python3.10/site-packages/h11/_connection.py", line 485, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/home/asdf/freqtrade/.env/lib/python3.10/site-packages/h11/_util.py", line 77, in _reraise_as_remote_protocol_error
    raise self
  File "/home/asdf/freqtrade/.env/lib/python3.10/site-packages/h11/_connection.py", line 467, in next_event
    event = self._extract_next_receive_event()
  File "/home/asdf/freqtrade/.env/lib/python3.10/site-packages/h11/_connection.py", line 409, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/home/asdf/freqtrade/.env/lib/python3.10/site-packages/h11/_readers.py", line 81, in maybe_read_from_IDLE_client
    raise LocalProtocolError("illegal request line")
h11._util.RemoteProtocolError: illegal request line
```

I can only guess it's some kind of caching from the browser or the server handling the http site being out of date and then self-correcting itself but it appears the exception should be handled because it doesn't look right for the log to show errors that originate from default code.

PS It never happens near the time the software is first launched, so it appears to be related either to caching of some sort, or in general to some kind of state produced a while after the launch.

**Comment by xmatthias** [comment]
unless you have logs from the browser (network tab) which has a correlated request to this - i think it's something else in your network "trying" to connect to this port via a non-http protocol.

Obviously the webserver will still receive this request (even though it's not http) - and then fail with this error.


This can be some odd device searching for "friends" (like a sonos or something similar) - or anything else that has a network plug.

**Comment by epigramx** [comment]
It is only happening at the exact moment the browser tries to connect to /dashboard. I see that what you say could be related though; there could be a plethora of intermediaries messing it up; though there's nothing immediately obvious like and it goes away anyway less than a second later and 4X of that exception (and it's fine the first time it connects too).

My main suspicion it related to the cryptography/login technology of it; perhaps there is some kind of temporary hash that must be kept on the browser and it times out after hours (and after the initial error it is corrected and no error occurs again); but I know nothing about the login technology of it to understand it.

**Comment by epigramx** [comment]
It is only happening at the exact moment the browser tries to connect to /dashboard (maybe the rest pages too but definitely on that). I can see though that what you say could be related; there could be a plethora of intermediaries messing it up (e.g. a proxy); though there's nothing immediately obvious like that and it goes away anyway less than a second later and 4X of that exception (and it's fine the first time it connects too).

My main suspicion is related to the cryptography/login technology of it; perhaps there is some kind of temporary hash that must be kept on the browser and it times out after a certain amount of time (and after the initial error: it is corrected and no error occurs again); but I know nothing about the login technology of it to understand it. 

---

I think I might have figured it out. It's most probably the browser extensions that try to gauge for **HTTPS** and use that as a priority; the exception (X4) is most probably during the attempt of the browser to gauge if there is the tech; then it gives up and goes on normally (and it probably keeps a cache of that for the medium-term future).

I realized that error (`h11._util.RemoteProtocolError: illegal request line`) is a generic error that could be easily googled; the very first googled answer had HTTPS as a reason; trying to connect with https manually: generates the same exception.

---

@xmatthias you can most probably reproduce it with manually trying to connect  with HTTPS instead of HTTP. Not sure if the exception can be common in other cases, but maybe it can be caught with a warning message (e.g. "maybe you're trying to connect with HTTPS while  it's not supported").

**Comment by epigramx** [comment]
@xmatthias you can most probably reproduce it with manually trying to enter with https instead of http. Not sure if the exception can be common in other cases, but maybe it caught with a message ("maybe you're trying to connect with https and it's not supported?".

**Comment by xmatthias** [comment]
The exception is raised (and captured) within uvicorn. 

Freqtrade never receives (nor sees) this exception other than from the logs - so we can also not handle it differently.
Now probably we can turn logging for uvicorn off completely - but that'll also hide other errors that might pop up (ones we don't know about yet) - so that's not a route i'd like to go.

**Comment by epigramx** [comment]
If their handling is spamming the traceback to their users, and preventing them entirely from handling it themselves, then their handling is bad.
