### ISSUE TITLE
Ability to use data from one exchange to trade on another

### ISSUE THREAD

**Issue by henryj** [freqtrade/freqtrade#6872]
Use case:

- Small exchanges do not have long enough or the best historical data to train the bot. 
- If the bot is trained with the bigger exchange data, it doesn't always reflect small exchange situations, especially volume related indicators.
- If there is a way to train the bot and use the live data from the big exchange, then do the actual trading on small exchange, it probably makes sense, coz the data from big exchange is richer and represents the trend better.

Happy to contribute if this sounds like a reasonable and feasible feature. Thanks for the great lib. ;)

**Comment by xmatthias** [comment]
This has been requested before (#1710) - but is not implemented at the moment.

By using "informative" data from other exchanges, this would be possible (what you base your signals on is really the topic of the strategy, and irrelevant for freqtrade).
the current approach is however to have one exchange class per instance - which implicitly prohibits using data from multiple exchanges. 
While i appreciate the suggestion / offer for contribution - i think this is a quite difficult feature to implement "as a starter" - as it'll require quite some architectural understanding of freqtrade to avoid breaking 200 other things in the process.

---

I also think you'll need to be slightly careful (from a trading perspective). Pairs move quite different between exchanges (use a well-working strategy from binance on the same pairs on another exchange and you'll know what i mean - it simply will not work) - so i do have severe doubts that trading based on "exchange moved X - so i enter a trade on Y" will be a profitable model.

**Comment by henryj** [comment]
Yea, I've seen #1710. I agree it is a bit complex to have multiple exchanges in the informative data. It's most likely an architectural change to introduce another dimension to the informative pairs. 

I was thinking a small step before that. For example in the config, if we can separate data exchange for getting the data and ccxt exchange for trading. This way we should have a good start to decouple the data source and the trading exchange. Or is this even harder/worse than the multiple exchange idea?

It will probably be only useful for some special strategies. Definitely won't recommend for general use. :P 

I guess I'll start to read some code first to understand how this part works. Thanks.

**Comment by xmatthias** [comment]
we'll not decouple "data exchange" from "trading exchange".  It's the same thing - really, and that'll also be the case for your "small" exchange usecase.
The impact/benefit vs. effort is clearly not there for this approach, as it's too inflexible and will only try to fullfill this particular, very niche need.

If #1710 is available - then you can base your signals on an informative pair (which in that case, would come from a different exchange). 
As such - there is nothing to be gained from the proposed decoupling, and while it may seem like a small step - it's really a pointless step, too, which will only introduce more maintenance burden, while not providing benefit to most users.

**Comment by henryj** [comment]
Thanks for the info. That makes sense. I'll close this one and wait for #1710 then. Thanks again for your quick reply. Cheers.
