### ISSUE TITLE
Webhookexitfill not triggering when SL is on exchange

### ISSUE THREAD

**Issue by nicolaspapp** [freqtrade/freqtrade#6873]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: _____ Python 3.8
  * CCXT version: _____ ccxt==1.78.23
  * Freqtrade Version: ____freqtrade develop-3359ac6
  
## Your question

I normally use Webhookexitfill to send enter and exit signals into a webserver. Recently I have been trying futures trading, and setting up `stoploss on exchange` option. I see that in the that the trade exits because of a stop loss I never get the exit signal for that trade.
Should I use a different webhook to be able to log that exit? Or is it some way to generate a similar signal when the bot notices that the trade has exited due to reaching an SL?
Thanks

**Comment by xmatthias** [comment]
it should be working - although a quick review showed that a filled stoploss actually triggers the "exit" notification, not the "exit_fill" notification.

That's however a quick fix - which will be fixed in develop in a few minutes.
