### ISSUE TITLE
Build Dockerfile error for freqtrade-2022.4:devalop

### ISSUE THREAD

**Issue by pok1800** [freqtrade/freqtrade#6884]
## Describe your environment

  * Operating system: linux/ubuntu x86
  * Python Version: Python 3.10
  * CCXT version: 1.83.12
  * Freqtrade Version:  freqtrade :develop  v.2022.4
  
## Your question
I'm build new freqtrade :develop  v.2022.4 for Dockerfile. What is system required library? Please you help me. 

Collecting orjson==3.6.8
  Downloading orjson-3.6.8.tar.gz (549 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 549.2/549.2 kB 3.0 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      💥 maturin failed
        Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
        Caused by: `cargo metadata` exited with an error: error: failed to parse manifest at `/tmp/pip-install-2wb1eb3d/orjson_bbd1546884a249b9aea4ed233861c8bd/Cargo.toml`

      Caused by:
        feature `resolver` is required

        consider adding `cargo-features = ["resolver"]` to the manifest
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/tmp/pip-modern-metadata-03rm3w83', '--interpreter', '/usr/local/bin/python']' returned non-zero exit status 1.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory /tmp/pip-modern-metadata-03rm3w83 --interpreter /usr/local/bin/python`
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
The command '/bin/sh -c pip3 install --user --no-cache-dir numpy   && pip3 install --user --no-cache-dir -r requirements-hyperopt.txt' returned a non-zero code: 1

Thank you
AdisakP.
*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Freqtrade provides pre-built [docker-images](https://hub.docker.com/r/freqtradeorg/freqtrade) which do build just fine in the latest versions (on different architectures).

This means our image is working fine - and you're probably trying to add an additional library (which is also documented).

it's however unclear what additional library you're trying to add - and the provided log does not include sufficient information to derrive that information.

**Comment by pok1800** [comment]
> Freqtrade provides pre-built [docker-images](https://hub.docker.com/r/freqtradeorg/freqtrade) which do build just fine in the latest versions (on different architectures).
> 
> This means our image is working fine - and you're probably trying to add an additional library (which is also documented).
> 
> it's however unclear what additional library you're trying to add - and the provided log does not include sufficient information to derrive that information.

I'm new build docker because my architectures i386. The freqtrade ver 2022.1 can build success.

**Comment by xmatthias** [comment]
We're not really able to support [legacy architectures](https://en.wikipedia.org/wiki/I386) - which are out of production since 2012 (or 2007, depending on the system).

You're obviously free to try and build an image for this anyway - but we'll not be able to provide you with much support other than hints where to look further.

---

At the moment, your problem seems to be `orjson` - which does not provide wheels for i386 (probably most other libraries won't either).
You might get lucky installing build-dependencies for this project - but expect further problems with additional dependencies.
