### ISSUE TITLE
Waiting period after trade exit before new trade entry

### ISSUE THREAD

**Issue by ryhnm** [freqtrade/freqtrade#6885]
## Describe your environment

Operating system: macOS Monterey 12.2
Python Version: 3.9.7
CCXT version: 1.72.98
Freqtrade Version: 2022.1
  
## Your question

How can I have a candle - where nothing happens - between trade exit and a new trade entry? For example let's say I exit a trade on the hourly timeframe at 18:40, I want to make sure the first possible trade is made at 20:00 and never at 19:00.

**Comment by xmatthias** [comment]
freqtrade has [protections](https://www.freqtrade.io/en/stable/plugins/#protections) - which allow locking of pairs (or of all pairs) for a defined period.

In your case, [CooldownPeriod](https://www.freqtrade.io/en/stable/plugins/#cooldown-period) seems to be what you're looking for.

Your freqtrade version also seems to be slightly outdated (uptodate is 2022.4.2) - so make sure to use the documentation page that fits your freqtrade version (or update freqtrade).
