### ISSUE TITLE
freqtrade 'hyperopt' method 

### ISSUE THREAD

**Issue by Smalltarget108** [freqtrade/freqtrade#6889]
## Describe your environment

  * Operating system: Ubuntu20.04
  * Python Version: _____ (`python -V`)
  * CCXT version: _____  (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade docker-e3beaae8 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hello,

Good day.
I am confused about the parameters tuning ,
I have tried the freqtrade 'hyperopt', but can only use one month data for it on my 64G CPU-memory PC,
It turns out that it can fit the used data, but get really bad performance on the non-seen data.

**Comment by stash86** [comment]
More info needed. How many are the columns of your dataframe? How many pairs? How many job counts?

As comparison, I can do 410 days hyperopt on 230 pairs on 24GB VPS. But to do that, I would have to limit how many indicators I used, I can only use 2 job counts, which make it took 2 days to complete 500 epochs.

**Comment by xmatthias** [comment]
Most likely, you're running into "out of memory" errors. The amount of memory usually scales mostly linearly, and the more parallel workers you allow, the more memory you need.

some [common receipts against that are in the documentation](https://www.freqtrade.io/en/stable/hyperopt/#out-of-memory-errors)
