### ISSUE TITLE
Use Open Date (Time) and Open price as my entry price

### ISSUE THREAD

**Issue by dennislau25** [freqtrade/freqtrade#6891]
* Operating system: Windows 11
  * Python Version: 3.9.13
  * CCXT version: 1.82.61
  * Freqtrade Version: 3549176
  

I have used populate_entry_trend() and populate_exit_trend() to define my entry and exit strategy - comparing a price prediction from an external ML model to today's closing price - a pretty simple strategy.

The issue is, when there is an entry signal (model price > closing price), freqtrade will take my next close price (not the next open price) as my entry price. Since the price frequency is 1 day for my case, that means there is a one day delay in entry point (and price). i.e. if I have an entry signal based on today's price the entry price will be tomorrow's closing price.

Is there any method to change the entry price to 'Immediate'? Or at least tomorrow's 'open' price instead of 'close' price?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

your issue is very unclear - are you talking about backtesting or live runs?

**Comment by dennislau25** [comment]
I've updated my question in the templated format.

I am running freqtrade backtesting. Basically I have a dataframe of open, high, low and close price, and a model predicted price. I wanted the backtest to compare the model and the close price, and if model price is higher then enter into a position at the next open price (instead of the next close price that I am getting now)

**Comment by xmatthias** [comment]
Please consider that all candle dates are candle open dates - so the moment you have a signal (say on candle 10:00) - the entry will by default be at the open of the next candle (11:00).
Everything else would lead to lookahead - especially considering that most indicators use the candle's close price - therefore the first  moment the signal is available is 11:00 (even though it's generated based on data from the 10:00-11:00 candle).

freqtrade will never use close prices during backtesting (unless you use custom pricing).

Freqtrade will follow these [backtesting assumptions](https://www.freqtrade.io/en/latest/backtesting/#assumptions-made-by-backtesting), so (exit) prices may vary based on the exit type.

**Comment by xmatthias** [comment]
Assuming this as answered.

Feel free to comment below / reopen if that's not the case.
