### ISSUE TITLE
Telegram messages at bot start up

### ISSUE THREAD

**Issue by chriswck** [freqtrade/freqtrade#6892]
## Describe your environment

Operating system: Windows 10 Home Version 21H1
Python Version: Python 3.10.0
CCXT version: ccxt==1.79.94
Freqtrade Version: freqtrade 2022.3
  
## Your question

[Screenshot here](https://i.imgur.com/btfiWfO.jpg)

Hello,
With reference to the telegram messages screen captured, MKR buy was fulfilled yesterday, with an accompanying stoploss order placed on the exchange. Today, when bot starts up, there is that Bought message - I believe it is attempting to show all open orders? Looking at the open rate, it looks like it is the open stop loss order. The message can seem a bit confusing. Can this be updated to reflect better that it is a stop loss order?

**Comment by xmatthias** [comment]
It's unclear which message you think is wrong (i'd also appreciate if you could upload the picture to the github issue - so it's tied to this without linking to external sites).

Without logs it's unclear what's happening.
the last "bought" message is simply a repetition of the one from 8:00 the prior day - so the order wasn't closed properly in the database (it was still marked as open).

Stoplosses will not show as "bought" - but would be a "sell" message - and your position would then be closed.

**Comment by chriswck** [comment]
Hi Matthias, thanks for the reply.

Apologies for the lack of description previously - to clarify
1. Buy order placed and fully filled on day 26th May
2. Stoploss order placed on the exchange immediately after
3. Manually shutdown bot / kill process
4. Start up bot on day 27th May
5. "Bought" message (with open rate equivalent to the expected stoploss price configured) shows during startup - corresponding to the very last message in the screenshot.

Let me know if there is any other information that would be helpful.


## Logs
[logs_extract.txt](https://github.com/freqtrade/freqtrade/files/8790924/logs_extract.txt)


## Screenshot of TG messages - 
![WhatsApp Image 2022-05-27 at 8 07 12 AM](https://user-images.githubusercontent.com/8623159/170810868-221fc2e5-8ada-4011-8886-601f64008181.jpeg)


## Screenshot of SQLite DB
![image](https://user-images.githubusercontent.com/8623159/170821883-16cefdfb-bdb1-4900-84af-684d5ffc58f1.png)

**Comment by xmatthias** [comment]
from the sqlitedb , i'd also need the trades table please (for this entry)

**Comment by chriswck** [comment]
### Orders Table
row id: 4, 5
[orders.csv](https://github.com/freqtrade/freqtrade/files/8791119/orders.csv)

### Trades Table
row id: 2
[trades.csv](https://github.com/freqtrade/freqtrade/files/8791120/trades.csv)

**Comment by xmatthias** [comment]
Based on your version - and the report - i'm now confident that you ran into a bug i fixed a few days ago in 1315d024372d2d284f5b8fbd84f420104bf1220c.

Best update to 2022.5 (which includes the above commit) - so it'll no longer happen.
