### ISSUE TITLE
How to start freqtrade with a new / custom strategy?

### ISSUE THREAD

**Issue by vaha6** [freqtrade/freqtrade#6905]
I have added my new strategy via new-strategy and it is located in my strategy directory.
When I run docker- compose up -d, it starts with sample strategy.could you please provide me a solution to overcone this issue.

**Comment by xmatthias** [comment]
You'll have to edit the docker-compose file, adjusting the command (last few lines) to the strategy name you've used.

**Comment by vaha6** [comment]
I have already done that

**Comment by xmatthias** [comment]
maybe try to stop the bot `docker-compose down` - and then start it again.

if you have a different strategy in your compose file - then that strategy WILL be used.
