### ISSUE TITLE
Is it necessary to analyze data frame every `process_throttle_secs`?

### ISSUE THREAD

**Issue by mhmdhoseinzade** [freqtrade/freqtrade#6910]
* Operating system: windows 10
  * Python Version: 3.9.9
  * CCXT version: 1.83.12
  * Freqtrade Version: freqtrade develop-734803aa4
  
I use 5m timeframe and process_throttle_secs =5 seconds
bot reanlyze the dataframe every process_throttle_secs 
I checked the hash sum of dataframe (https://pandas.pydata.org/docs/reference/api/pandas.util.hash_pandas_object.html)
and got same value every time until next candle
is there any logic behind this ?

**Comment by xmatthias** [comment]
There's a setting - `process_only_new_candles` - which defaults to true now - which will ensure that the dataframe is only analyzed once.

Setting this to false is only really useful if you use additional data (like orderbook data) - which will refresh more often.

you can read more about that in the [documentation](https://www.freqtrade.io/en/stable/configuration/#configuration-parameters).
