### ISSUE TITLE
backtest issue with timeframe-detail and custom_entry_price

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#6911]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.9.13
  * CCXT version: 1.82.61
  * Freqtrade Version: develop-3e7bf6a9e
  
## Describe the problem:
Running a backtest with `--timeframe-detail 1m` results are weird since stoploss in strategy is not respected and few open trades also stay open forever. Stoploss in strategy set with `stoploss = -0.06` in backtest summary metrics I get `Worst trade -79.72%`. Running the backtest for the same strategy without `--timeframe-detail 1m` works correctly.

sample trade ignoring stoploss:
```
                {
                    "pair": "SECO/USD",
                    "stake_amount": 1851.87234599,
                    "amount": 79.29131058,
                    "open_date": "2021-09-06 23:35:00+00:00",
                    "close_date": "2021-12-31 23:55:00+00:00",
                    "open_rate": 23.3553,
                    "close_rate": 17.6868,
                    "fee_open": 0.0007,
                    "fee_close": 0.0007,
                    "trade_duration": 167060,
                    "profit_ratio": -0.24376669,
                    "profit_abs": -451.74079135,
                    "exit_reason": "force_exit",
                    "initial_stop_loss_abs": 21.953982,
                    "initial_stop_loss_ratio": -0.06,
                    "stop_loss_abs": 22.686379751859025,
                    "stop_loss_ratio": -0.025917571839457865,
                    "min_rate": 23.0789,
                    "max_rate": 24.495,
                    "is_open": true,
                    "enter_tag": "generic_ema9_cross_sma20 1_star",
                    "is_short": false,
                    "open_timestamp": 1630971300000.0,
                    "close_timestamp": 1640994900000.0
                }
```

### Steps to reproduce:

  1. `freqtrade backtesting --max-open-trades 3 --strategy-list zond_0_5_3_1 --timerange 20210501-20220101 -c conf_zond_BT.json --fee 0.0007 --timeframe-detail 1m --cache none`
  
### Observed Results:
I noticed this is happening when using in `custom_entry_price` `return current_candle['close'] * 1.003` or `return current_candle['close']` simulating slippage with marketable orders (see lines 1085 and 1090 in /wip/zond_0_5_3_1).
If using for example `return min(current_candle['close'] * 2, proposed_rate)` backtesting with 1m detail, is running correctly.

### Relevant code exceptions or logs
No errors/warnings printed in logs during backtest.

**Comment by xmatthias** [comment]
the reason this appears with `--timeframe-detail` is in the strategy - not in the code that's causing the bug.

Only with detail is a new order placed (and then canceled) - the `open_order_id` is however not reset - causing the trade to never be checked for sells again.

You can check the commit linked here (and the one prior) - it's a pretty simple - yet dangerous bug.
