### ISSUE TITLE
Difference from documentation and behavior for amount parameter of confirm_trade_entry callback

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#6913]
Hi,

In the documentation, it say the value for amount is quote currency, but it seems to be base currency when i make test.

Is it a bug or the documentation in wrong ?

Get the amount from base currency i think is better because you can compare the value to other pair (a kind of relative)

```
def confirm_trade_entry(self, pair: str, order_type: str, amount: float, rate: float,
                            time_in_force: str, current_time: datetime, entry_tag: Optional[str],
                            side: str, **kwargs) -> bool:
        ...
        :param amount: Amount in target (quote) currency that's going to be traded.
       ....
        return True

```

Have a nice day.

**Comment by xmatthias** [comment]
The amount will be in the currency you're buying (XRP, in the case of XRP/USDT).
the USDT amount we call stake_currency in freqtrade - but that'd correspond to quote currency.

will have a look at fixing the documentation.

I'm not sure what you'd compate there though - there's quite some difference in buying 100 XRP, or 100 BTC ... at least for my account 😆
