### ISSUE TITLE
Display the candle analyzed in telegram 

### ISSUE THREAD

**Issue by FlockrushAdmin** [freqtrade/freqtrade#6915]
## Describe your environment
(if applicable)

  * Operating system: macos big sur 11.2.3
  * Python Version:3.9 (`python -V`)
  * CCXT version: 1.66.66 (`pip freeze | grep ccxt`)
  * Freqtrade Version: eee337c (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

Show the actual candle analyzed in telegram.

Personally I found it to be a challenge to see which candle was used to buy and sell.  I use an enhanced charting software and this has helped me tremendously. 

*Explain the enhancement you would like*

Show the actual candle analyzed in telegram.

I have forked the repo and made the changes, I can further refine the display if that helps and make it configurable if you would like. I have a deep understanding of the codebase and I have a few other changes which at some stage I can share which may help others. 

https://github.com/Surfableio/freqtrade/commit/84638496bb3c8330baa57fb00d152731bf2ee4e5

Thank you again, you guys have done an amazing job!!!

**Comment by xmatthias** [comment]
If you think it can benefit others - please create a [Pull request](https://docs.github.com/en/get-started/quickstart/github-flow) to add it to the repository (please also include a screenshot of how the new output will look like).

It's difficult to decide if / determine how it'll look like from a single commit, and as such, it's also difficult to say if it needs configuration ... 

Please understand that i'll not go "hunting other people's forks for changes" trying to add these to freqtrade.
if it's a worthy change (you think it can benefit others) - a Pull request is the best way. 

Especially if it's not a major change which needs discussion first.

**Comment by FlockrushAdmin** [comment]
Got it. Will do.

**Comment by FlockrushAdmin** [comment]
Sorry it took a bit of time, the merge with all required tests and a copy of them attached to the pull request:

https://github.com/freqtrade/freqtrade/pull/6916

Thank you again. Have an amazing day!!!
