### ISSUE TITLE
using talib CDL functions as features

### ISSUE THREAD

**Issue by shayan775** [freqtrade/freqtrade#6917]
## Environment

  * Freqtrade Version: freqtrade develop-45f4f0f60 (freqai branch)
  
## Question
I've been using freqai branch for a while. i wonder if there is better way to use talib CDL functions than this:

```python
            informative[f'%-{coin}CDLDOJI'] = ta.CDLDOJI(open, high, low, close)
            informative[f'%-{coin}CDLOJISTAR'] = ta.CDLDOJISTAR(open, high, low, close)
```

it doesn't seem quite right! 
i suggest to add an example of using these functions in ```FreqaiExampleStrategy.py``` file ❤️‍🔥

**Comment by xmatthias** [comment]
i'm not entirely sure what the question is, or what you see wrong/bad with this.

the call suggests that you're not using the abstract interface (depends how you import)  - as then you'd probably have to call `ta.CDLDOJI(dataframe)` ...

**Comment by shayan775** [comment]
imagine we want to use all CDL functions, and we add them all to list of feature columns (a column for each one of the function results, like what we would naturally do if we don't want to use machine learning, and just creating a normal strategy ). it consumes a lot of memory, and slow down the whole process so much, what i meant was is there a way to do it in a better way? for example the first idea that came to my mind was to make the dataframe something like this:
```
date        open        high        ...        %-candle-type
....        ....       ....         ...        DOJI 
....        ....       ....         ...        DOJI 
....        ....       ....         ...        OJSTAR
....        ....       ....         ...        3INSIDE
....        ....       ....         ...        3OUTSIDE
....        ....       ....         ...        DOJI 
....        ....       ....         ...        3INSIDE
```
we calculated the candle types and represented all candles type in one column( in front of each candle, in its row)

but now if you pass this column as feature, you will run into errors because its data type is string, im not sure if the CatboostRegressor supports string features but in preprocessing stage(normalizing features in ```FreqaiDataKitchen``` for example) i didn't see an algorithm to split strings and numeric data types from each other, it treat's the features all as numeric data types (preforming max() & min() functions) so you will run into errors (and beside that i don't think having string features in case of financial decisions is a good idea in the field of ML) . so whats the best way to use CDL functions as training features and not giving them to the Regressor in seprate columns? :)

**Comment by robcaulk** [comment]
>it in a better way? 

No. If you want to feed categorical data as features, you need to use a binary representation which means each of your categorical features is a column in the data set. You can look into using something like a one hot encoder to expedite the process. 

Cheers,

Robert
