### ISSUE TITLE
CCXT PRO support in Q3?

### ISSUE THREAD

**Issue by AlgoQ** [freqtrade/freqtrade#6920]
Since CCXT PRO is going to be added to CCXT in Q3 are there any plans to add WebSockets support? It would be nice to stream data in real-time.

**Comment by xmatthias** [comment]
We will eventually support Websockets through ccxt.pro - but several (bigger) changes for that are necessary.

Our aim is certainly to support this in a timely manner, however, as open source project, we'll not be providing timing for this - as it'll depend on both available time as well as other important tasks that need our attention.
