### ISSUE TITLE
Is there a supposed way to run an Indicator recursively

### ISSUE THREAD

**Issue by yodsan-b** [freqtrade/freqtrade#6921]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.9.9
  * CCXT version: ccxt==1.80.61
  * Freqtrade Version: freqtrade docker-7b02114a
  
## Your question

Hello everybody! I'm new to freqtrade.io an very impressed but what has been achieved so far, especially the optimization. 
I have tried to implement some indicators that are inherently recursive and computing intensive.  I got it done by returning the filter_object and keeping it in self. But it is far from pretty.
Is there an elegant way to keep filter Objects persistent - a way to use some kind of "next"? 

 ![Screenshot from 2022-06-01 18-21-56](https://user-images.githubusercontent.com/85258179/171454827-972ae6c3-50ec-4ffb-8e9d-eac2f4cff789.png)

Apparently 'populate_indicators' gets called multiple times within a set timeframe. Is there a way to avoid this? The strategy is run with one pair and "1m".

**Comment by xmatthias** [comment]
you can (or should) set `process_only_new_candles` to true (the new default) - then the `populate_*()` methods are only called once per candle.

Obviously on 1 minute, you'll still need to make sure that the indicator can calculate within that 1 minute.

The question itself - (how to run an indicator recursively) is pretty unclear though - if the indicator itself is recursive, there's little to do other than just run it and have it calculate i guess?

**Comment by yodsan-b** [comment]
The quick answer is highly appreciated, Matthias! Thanks for the heads up regrading the process_only_new_candles.
Sorry for the not being clear enough. Filter which run inherently recursive, step by step, are not easy to speed up. Like a bootstrap filter that relies on the A priori state and pseudorandom numbers at each step. Here it's preferable to keep the Filter object and and run a Fiter.update() at each new candle, instead over a slice of 999. The wouldn't finish in a reasonable time over the complete 999 array.

**Comment by yodsan-b** [comment]
But I consider the question as answered, it is doable via returning the filter object and keeping it in self. Thank you very much.
