### ISSUE TITLE
Making freqtrade essentially take in ""user input"" by using already existing order for basing multiple new ones on it.

### ISSUE THREAD

**Issue by n8an** [freqtrade/freqtrade#6926]
## Describe your environment

  * Operating system: latest freqtrade docker image
  * Python Version: latest freqtrade docker image
  * CCXT version: latest freqtrade docker image
  * Freqtrade Version: freqtrade 2022.5
  
## Your question

How should I go about making my freqtrade bot scan for an **already existing position** then **use it's price** level to be ready to execute **multiple** market orders one after the other, at **different** prices that are **reliant on the first** existing order that was found on the account at the start of the bot?

A logic timeline:

1. Start freqtrade
2. Freqtrade checks for open positions on a given crypto pair
3. If it doesn't exist, shutdown or restart
4. Based on this position's (price level - some percentage) be ready to execute a market order if price comes down to that level
5. Then be ready to execute another market order if the price comes back up to the first position's level
6. Repeat steps 4 and 5 maximum of 14 times with the order size getting bigger each time
7. Exit positions on a takeprofit or stoploss that were set inside the exchange (binance for example)
8. Or exit after a command to shut down

**Comment by xmatthias** [comment]
This is clearly not a usecase we'll be supporting. Freqtrade is designed to be kept running, and to manage only it's own trades (trades it opened itself).


Freqtrade will only handle positions itself opened.
There is no functionality to read existing positions - and i don't think there should be, either.
Alone the logic to get the initial entry price correct (assuming it's a slightly more complex position with multiple existing entries/ and exits) will not be without dangers - and is not worth the complexity it would add to the codebase.

Many exchanges don't allow subaccounts by default (binance?) - which means freqtrade will have to "blend in" with people's trading, people's HODLing, and other usages of that account.
The above functionality would assume "everything is freqtrade's to manage" - which is simply wrong, and not how freqtrade should operate.

---

Your steps 4-6 should be possible from within the strategy.
Best start the position with `/forceenter` (eihter via telegram or via freqUI). After that, it's a simple question of creating a strategy that [adjusts the position](https://www.freqtrade.io/en/latest/strategy-callbacks/#adjust-trade-position).

Please note that currently only increasing the position is possible - partial exits will be added at a later time.

7 is again the "danger zone" - where you have a mixed mode between what the user defines, and what freqtrade defines - which is not a supported mode.
The strategy can define stoplosses and take profits (ROI) from within the strategy - either statically, or via `custom_stoploss()` / `custom_exit()` callbacks.
