### ISSUE TITLE
scripts/rest_client.py forceenter... doesn't work

### ISSUE THREAD

**Issue by liaogx** [freqtrade/freqtrade#6927]
* Operating system: CentOS Linux release 7.9.2009 (Core)
  * Python Version: 3.8.5
  * CCXT version: 1.84.39
  * Freqtrade Version: 2022.5.1
  
I'm running a command with linux terminal to **force entry a trade**, live trading mode, futures trading on OKX. I've tried two different commands.

1. `docker-compose exec freqtrade python3 scripts/rest_client.py force_enter SOL/USDT:USDT short -c user_data/config.json`

it returns `{"detail": "Method Not Allowed"}`

2. `docker-compose exec freqtrade python3 scripts/rest_client.py force_enter {"pair": "SOL/USDT:USDT", "side": "short"} -c user_data/config.json `

it returns 
```bash
Traceback (most recent call last):
  File "/freqtrade/scripts/rest_client.py", line 440, in <module>
    main(args)
  File "/freqtrade/scripts/rest_client.py", line 435, in main
    print(json.dumps(getattr(client, command)(*args["command_arguments"])))
TypeError: FtRestClient.force_enter() takes from 3 to 4 positional arguments but 5 were given
```

**Comment by robcaulk** [comment]
The correct command is `forceenter`.

https://www.freqtrade.io/en/stable/rest-api/#available-endpoints

**Comment by liaogx** [comment]
> The correct command is `forceenter`.
> 
> https://www.freqtrade.io/en/stable/rest-api/#available-endpoints

NO! The document is wrong. I've tried that, it's `force_enter`

**Comment by xmatthias** [comment]
Neither - the command was renamed from force_enter to forceenter - and the script was missed.
calling force_enter in the script called a non-existant endpoint. It's now aligned to `forceenter`.
