### ISSUE TITLE
How to use leverage?  I didn't find a place to set it

### ISSUE THREAD

**Issue by frankeson** [freqtrade/freqtrade#6928]
How to use leverage?  I didn't find a place to set it

**Comment by stash86** [comment]
Open browser, open https://freqtrade.io/, open the search bar, type "leverage", and there is your answer

**Comment by frankeson** [comment]
> 

I can't find it
For example, I want to set the leverage to 5 X, how should I operate

I don't find in  https://www.freqtrade.io/en/stable/leverage/

**Comment by frankeson** [comment]
OH,I find it  in class

**Comment by pok1800** [comment]
> class



> OH,I find it in class

Hi frankeson
Where did  set the leverage ?  I need to setting leverage to 10 X, Mode future

**Comment by xmatthias** [comment]
The documentation is your friend. it's implemented as a [callback](https://www.freqtrade.io/en/stable/strategy-callbacks/#leverage-callback), which you need to implement in your strategy.

**Comment by pok1800** [comment]
> The documentation is your friend. it's implemented as a [callback](https://www.freqtrade.io/en/stable/strategy-callbacks/#leverage-callback), which you need to implement in your strategy.

Thank Sir xmatthias,
I'm low developer. implement in FSupertrendStrategy. Please advise. 

Sample edit my strategy 
```
class FSupertrendStrategy(IStrategy):
        def leverage(self, pair: str, current_time: 'datetime', current_rate: float,
                 proposed_leverage: float, max_leverage: float, side: str,
                 **kwargs) -> float:
        return 1.0
        max_leverage = 10
```

**Comment by xmatthias** [comment]
You should not use high leverage unless you're sure your strategy is working well.
Any demo strategy is what it is - a demonstration which may or may not provide gains. Simply adding 10x leverage can also amplify your losses.

**Comment by pok1800** [comment]
Thank Sir xmatthias, I understand.
I have a little money for expectation.
