### ISSUE TITLE
Additional entry_tag argument on IStrategy leverage method

### ISSUE THREAD

**Issue by Chrisvandr** [freqtrade/freqtrade#6929]
## Describe the enhancement
It would be nice to be able to allow changing the leverage for specific signals/new orders. Currently I have entry signals that each have their own custom stoploss configured, for some of these signals I would like to increase their leverage since I'm more confident about their success. Currently it seems leverage is retrieved through `get_valid_enter_price_and_stake`, where `self.strategy.leverage` is called. Since leverage is set on the strategy level in the method, it is the same for all new trades.

Would it be possible to add the `enter_tag` argument to the leverage method, this can then be passed through in `get_valid_enter_price_and_stake`, this would make it easier to see for which signal/entry_tag the leverage is being retrieved, allowing for some additional logic to change the leverage return value.

**Comment by xmatthias** [comment]
Great catch - will be added to the develop version shortly.
