### ISSUE TITLE
why IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by ExpressGit** [freqtrade/freqtrade#6930]
## Describe your environment

  * Operating system: __centos__
  * Python Version: ___3.10.4__ (`python -V`)
  * CCXT version: __1.84.39___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __2022.5.1__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
![image](https://user-images.githubusercontent.com/11694747/171982144-7e83e2df-644c-4901-9289-cf98dfafadb4.png)
![image](https://user-images.githubusercontent.com/11694747/171982165-a29ca70f-8274-438d-93b6-cde7e993e777.png)

pip list:
Package               Version     Editable project location
--------------------- ----------- -------------------------
aiodns                3.0.0
aiofiles              0.8.0
aiohttp               3.8.1
aiosignal             1.2.0
anyio                 3.6.1
APScheduler           3.6.3
arrow                 1.2.2
asgiref               3.5.2
async-timeout         4.0.2
attrs                 21.4.0
blosc                 1.10.6
cachetools            4.2.2
ccxt                  1.84.39
certifi               2022.5.18.1
cffi                  1.15.0
charset-normalizer    2.0.12
click                 8.1.3
colorama              0.4.4
cryptography          37.0.2
fastapi               0.78.0
filelock              3.7.0
freqtrade             2022.5.1    /freqtrade
frozenlist            1.3.0
greenlet              1.1.2
h11                   0.13.0
idna                  3.3
Jinja2                3.1.2
joblib                1.1.0
jsonschema            4.5.1
MarkupSafe            2.1.1
multidict             6.0.2
numexpr               2.8.1
numpy                 1.22.4
orjson                3.6.8
packaging             21.3
pandas                1.4.2
pandas-ta             0.3.14b0
pip                   22.1.2
progressbar2          4.0.0
prompt-toolkit        3.0.29
psutil                5.9.1
py-find-1st           1.1.5
pyaml                 21.10.1
pycares               4.1.2
pycoingecko           2.2.0
pycparser             2.21
pydantic              1.9.1
PyJWT                 2.4.0
pyparsing             3.0.9
pyrsistent            0.18.1
python-dateutil       2.8.2
python-rapidjson      1.6
python-telegram-bot   13.12
python-utils          3.3.3
pytz                  2022.1
pytz-deprecation-shim 0.1.0.post0
PyYAML                6.0
questionary           1.10.0
requests              2.27.1
schedule              1.1.0
scikit-learn          1.1.1
scikit-optimize       0.9.0
scipy                 1.8.1
sdnotify              0.3.2
setuptools            62.3.2
six                   1.16.0
sniffio               1.2.0
SQLAlchemy            1.4.36
starlette             0.19.1
ta                    0.10.1
TA-Lib                0.4.24
tables                3.7.0
tabulate              0.8.9
technical             1.3.0
threadpoolctl         3.1.0
tornado               6.1

**Comment by xmatthias** [comment]
Please don't post log output as images - but as text. That makes it way easier to read and help.

The error is from within your strategy. The "highlight-line" (in the screenshot) partially obscures the faulty line, but it seems like you're using index 0 twice in that row, so one of these will be an empty array.

The backtrace also indicates that it comes from a call to `add_all_ta_features()` - which is either a method you wrote - or a method you imported from a 3rd party library/packages.
So either you need to debug it yourself (if it's your code) - or ask in the corresponding library support channels what can cause this problem.

**Comment by stash86** [comment]
From the method name, I believe it's that ta 0.10.1

**Comment by xmatthias** [comment]
pretty sure it is, yeah. 
They'll know what input will cause such an error.

**Comment by ExpressGit** [comment]
thank you,the problem has beed solved.

add config:
startup_candle_count: int = 30
