### ISSUE TITLE
Additional order with VolumePairList?

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#6931]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Since quoteVolume now is the only order using VolumePairList, I ask you, if there is still a different option to sort the list (beside ShuffleFilter, which wouldn't be "sorting"): My idea is to generate a list, which is built on a additional sort-criteria, to give other coins a top-position. A second bot using such a second list, would most likely not generate the same SLs at the same time. In my case I would not like to switch to a different strategy, and if possible, not split the PairList.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
without being (at least a bit) specific about the "sort criteria" - it's pretty difficult to determine if this possibility exists (or how easy/difficult it would be to add).

You're correct, `quoteVolume` is now the only order - the only other, previously available alternative was `baseVolume` - but you can't compare a volume of 20 BTC (in btc) with 100_000 XRP (in XRP) - it's simply not comparable, and would always strongly favor low-value coins.

**Comment by xmatthias** [comment]
Closing this as no further info was provided.
