### ISSUE TITLE
have backtest and hyperopt results (or even all output files generally) compressable out of the box

### ISSUE THREAD

**Issue by hippocritical** [freqtrade/freqtrade#6932]
## Describe the enhancement
got masses of backtest data, >60GB and they swallow up a lot of data.
Others might have masses of backtest data too and they might even pay for extra drive space which would not be necessary if the files were compressed.
Currently doing a daily cronjob compressing produced backtest / hyperopt files into a 7zip archive to not expand the drive space and then have to pay for it additionally.
Backtest / hyperopt output data is highly compressible, tried 7zip with ultra settings and produced the following with it:
![grafik](https://user-images.githubusercontent.com/41228167/172043365-0dc9249f-db79-4f1d-927c-c73ad161fd75.png)

a mechanic like jsongz could produce a similar result.

*Explain the enhancement you would like*
Either have an option for data to be generally compressed into gzip'ed files (for example)
Or have that option at least activatable for hyperopt and backtest output files.

**Comment by xmatthias** [comment]
i'm not sure why you'd want to keep backtest results (or even hyperopt results) for very long (it either works - or it doesn't. if you go back more than 2 weeks, you'll probably not know what exact version of the strategy created this anyway), so a properly setup "remove job" might also work just fine.

I've been thinking about this myself - but compression is not really relevant i think - a "clear everything older than X days" will be a cleaner method.

**Comment by hippocritical** [comment]
you'll probably not know what exact version of the strategy created this anyway

oooooh yes I do all got edited with markers ;)

well k, got it solved manually by 7zipping anyways. np closing

**Comment by xmatthias** [comment]
it's not ... plain rejection - i'm just questioning this (i do have my doubts if you'll EVER reload a hyperopt file you made 2 months ago).
