### ISSUE TITLE
Strategy failure

### ISSUE THREAD

**Issue by vaha6** [freqtrade/freqtrade#6942]
I have run freqtrade and almost tested all the strategies (dry run).
I need a strategy that make 1.5% in shortest possiblr time.
I am also suffering from this issue that when it make a sell order, it fails and looses the chance of selling it and even worse it goes negative in some cases and no sell. Could any one help?

**Comment by xmatthias** [comment]
For unfilled orders, best read through the [pricing documentation](https://www.freqtrade.io/en/latest/configuration/#prices-used-for-orders). It'll explain how to change your pricing strategy to have a better chance of filling your orders (it will however also assume some due diligence in understanding how markets work).

> I need a strategy that make 1.5% in shortest possiblr time.

It's up to you, the user, to come up with a strategy that fits your needs (expected profits, in the expected markets). 
We'll not be providing guaranteed winning strategies.
