### ISSUE TITLE
no buy order with the remaining balance

### ISSUE THREAD

**Issue by vaha6** [freqtrade/freqtrade#6953]
## Describe your environment

  * Operating system: ____ Ubuntu 20.04
  * Python Version: _____ (`python -V`) python 3
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker) docker-compose run --rm freqtrade
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
Dear friends, 
I am a beginner and I would like to apologize  asking maybe detailed  questions.
I have adjusted all the configurations and set every thing up in my strategy.  I have started with USD1000 and max open trade is 10, and stake amount is unlimited, the problem I am facing here is that it has 3 buy orders and do nothing with the remaining balance which is around 700USD for almost 5-6 hours or longer even. is there any part I need to change or adjust limitation to make the buy order for the remaining balance?
thanks

**Comment by stash86** [comment]
read your strategy, read the entry/buy logic. The bot will only buy when a coin fulfilled its buy logic. It's not a race of who is faster to burn the balance

**Comment by xmatthias** [comment]
There is little to add  to this. your 10x max_trade_amount is a maximum - which may or may not be reached depending on your signals.

Depending on the strategy, the goal can be to always have 100% of your positions filled (you risk missing other, more profitable opportunities) and have a higher overall market exposure - or to be in and out of positions quickly (your capital will "lay" around for longer, as only a fraction of your capital is used at any time).

By backtesting your strategy - you should get a feel on how it behaves with different stakes. 
maybe your strategy / pairlist combination does not justify having 10 parallel trades open - but it's up to you (and heavily dependent on your configuration and desires) if that's correct or wrong  (there is no correct or wrong, really).
