### ISSUE TITLE
Limit buy implementation

### ISSUE THREAD

**Issue by ahmadie** [freqtrade/freqtrade#6954]
* Freqtrade Version: developer branch
  
## Your question

Hello, I have been using freqtrade for more than 6 months now. Thank you for this amazing tool. The learning curve has been rather hard due to new feature being added constantly.

I would like to implement a limit sell order so I created this sample strategy. Then I realise my code will only work for backtesting and I have to change highlighted rows for dry run / production. My question will be I am right ? or are there any better approach?

```
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['atr'] = pta.atr(dataframe['high'], dataframe['low'], dataframe['close'], 14)
        dataframe['limit_sell'] = dataframe['close'].shift() + dataframe['atr'].shift() * 1

        return dataframe

    def custom_exit(self, pair: str, trade: Trade, current_time: datetime, current_rate: float,
                    current_profit: float, **kwargs) -> Optional[Union[str, bool]]:
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
        #shift to get prev candle to get signal candle
        signal_candle = dataframe.shift()[dataframe['date'] == trade_date]

        if not signal_candle.empty:
            signal_candle = signal_candle.squeeze()
            limit_sell = signal_candle['limit_sell']
            if(signal_candle['high'] > limit_sell): # Enable this line for backtesting
            # if(current_rate > limit_sell): # Enable this line for dry run / production
                return "limit_sell"

    # Remove below for dry run / production
    def custom_exit_price(self, pair: str, trade: Trade,
                          current_time: datetime, proposed_rate: float,
                          current_profit: float, exit_tag: Optional[str], **kwargs) -> float:

        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
        signal_candle = dataframe.shift()[dataframe['date'] == trade_date]

        if not signal_candle.empty:
            signal_candle = signal_candle.squeeze()
            return signal_candle['limit_sell']

        return proposed_rate

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['buy'] =  (dataframe['close'] > dataframe['close'].shift())
        return dataframe


    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        return dataframe
```

Specificly change below code when moving from backtesting to dry run
```
if(signal_candle['high'] > limit_sell): # Enable this line for backtesting
# if(current_rate > limit_sell): # Enable this line for dry run / production
```

**Comment by xmatthias** [comment]
when it comes to candle access, i can only recommend to stick to the [examples in the docs](https://www.freqtrade.io/en/stable/strategy-advanced/#dataframe-access).

That method is known to work for both live and dry.

you may also want to be careful with using `.shift()` - i don't see why that should be necessary, and you'll most likely use the wrong candle with that approach (one too early).

**Comment by ahmadie** [comment]
Then my question would be if there are any example that you can point me, that shows how to sell equity at specific price, (limit sell)

Thank you for fast response.

**Comment by xmatthias** [comment]
you can use the [exit pricing callback](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-entry-and-exit-price-example) for that.

It's then up to you to combine it in a meaningful way (meaningful to your strategy).

**Comment by ahmadie** [comment]
Thank you for the great work
