### ISSUE TITLE
Trade always open on the next candle of the enter_long

### ISSUE THREAD

**Issue by carlolt** [freqtrade/freqtrade#6956]
## Describe your environment

  * Operating system: CentOS 7.9
  * Python Version: 3.9.9
  * CCXT version: 1.80.61
  * Freqtrade Version: 2022.4.2 [docker version]
  
## Your question

Hi All,
  I'm running dry-run with 5minutes timeframe and I've noticed that freqtrade is always starting the trade 5 minute after the "enter_long" signal.
I've already checked and there were few open trades (< max_open_trades ) . I've also tried to increase the max_open_trade to an high value, but the behavior is always the same.
Is this expected? Is there a way to buy at the same time that the enter_long is verified?

![image](https://user-images.githubusercontent.com/81958445/172886873-1a052430-8327-4733-8a57-9e95009b36cc.png)

Thanks!

**Comment by xmatthias** [comment]
The "delay" you're seeing is not really there once you think about it a bit more (there's a time component involved).

Most indicators are based on the candle's close price. 
This price is only available (without further modification) once the candle closes, hence the earliest possible point you can enter a trade with that is the next candles open time (usually a few seconds later - considering processing time etc).

assume 1h candles for simplicity - so the 1h candle from 10:00 (to -11:00) would have it's close posted not before 11:00.
your signal is (for example) based on macd (which is an ema of the candle close by default) - then the first possible signal-time is 11:00:01 - which is the next candle.
