### ISSUE TITLE
 Impossible to load Strategy

### ISSUE THREAD

**Issue by par3** [freqtrade/freqtrade#6959]
## Describe your environment

  * Operating system: win 10
  * Python Version: _____ (`python -3.10`)
  * CCXT version: _____ (`pip freeze | grep ccxt 22`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
freqtrade - ERROR - Impossible to load Strategy 'sample_strategy'. This class does not exist or contains Python code errors.

i made strategy by minimal template

![image](https://user-images.githubusercontent.com/10708347/172946823-1f8783b1-ae7d-437f-a678-c69c382357cd.png)

**Comment by mert-donmez** [comment]
The class name of the strategy can be SampleStrategy. Can you try `--strategy SampleStrategy` ?

**Comment by xmatthias** [comment]
If it's not `SampleStrategy` - then please look at the file - and use the class name (`class <nameyougaveit>(IStrategy)`) - and use that as terminology.

Alternatively you can also use `freqtrade list-strategies` to visualize all available strategies - and use the name that's displayed there.

**Comment by par3** [comment]
the name is correct
How can I make sure Python is installed correctly ?
with all dependecies ..

**Comment by xmatthias** [comment]
Based on the logs in the initial message - freqtrade is installed correctly - but the strategy is not found under this name.

For installation - we do have the installation documentation for [docker](https://www.freqtrade.io/en/stable/docker_quickstart/) - or the one for [native installs](https://www.freqtrade.io/en/stable/windows_installation/).
You seem to be using docker based on the output above - where installation will be correct automatically (it's built in our ci).

**Comment by par3** [comment]
--strategy SampleStrategy 

docker-compose run --rm freqtrade backtesting --config user_data/config.json --strategy SampleStrategy --timerange 20220606-20220606 -i 1h

![image](https://user-images.githubusercontent.com/10708347/173239371-8432b301-ad2a-4cd3-81cf-342fe3577523.png)

**Comment by mert-donmez** [comment]
> --strategy SampleStrategy
> 
> docker-compose run --rm freqtrade backtesting --config user_data/config.json --strategy SampleStrategy --timerange 20220606-20220606 -i 1h
> 
> ![image](https://user-images.githubusercontent.com/10708347/173239371-8432b301-ad2a-4cd3-81cf-342fe3577523.png)

VolumePairList cannot be used for backtesting. I suggest you to use StaticPairList . 
```
"pairlists": [
        {
            "method": "StaticPairList",
            "number_assets": 40,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
```
