### ISSUE TITLE
freqtrade - ERROR - DEPRECATED: Using 'sell_profit_only' moved to 'exit_profit_only'.

### ISSUE THREAD

**Issue by jbrepogmailcom** [freqtrade/freqtrade#6961]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.9 (`python -V`)
  * CCXT version: 1.86.21 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.5 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*
freqtrade - ERROR - DEPRECATED: Using 'sell_profit_only' moved to 'exit_profit_only'.

### Steps to reproduce:

  1. command freqtrade backtesting --strategy Strategy002
  2. 
  3. 
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
In 2022.4, we did a strategy interface update - which requires migration IF you're using futures / a futures configuration.

As Strategy002 is not made for futures, that's most likely a missconfiguration. If you're still trying to use that strategy with futures, you'll have to follow the [strategy migration guide](https://www.freqtrade.io/en/stable/strategy_migration/).
