### ISSUE TITLE
Add dry/live indicator and average entry/exit price to telegram notifications

### ISSUE THREAD

**Issue by robcaulk** [freqtrade/freqtrade#6962]
## Describe the enhancement

@froggleston and I were talking a bit and we noticed that there are two issues in the freqtrade discord that may hurt new users:
1) people fabricating results by deleting bad trades from their databases
2) people purporting dry runs as live runs

This false information may lead to two problems:
1) it may demoralize new/old users who are honest and trying their best
2) worse: it may lead new users to purchase bad strategies from the users who are falsifying results. Ultimately getting scammed and feeling resentment toward the FT community. 

In an attempt to clarify result sharing on discord, I think it would be nice to have additional information indicating if the results are live or dry, the slippage that occurred for that particular entry/exit, and the number of deleted trades in the DB. This will not completely solve the issue but it will help the discord community identify those who are falsifying information. 

Do y'all think this would help? Or is it a waste of space and will just clutter the telegram messages? I want to hear your thoughts.

**Comment by xmatthias** [comment]
the main purpose of notifications is to inform the user - not to serve as a mirror for your trades to the community.

I understand they're shared - but i am very reluctant to put a lot of useless information there (useless to the user) just so others see if it's live or dry.
I find the notifications already contain too much information to see "at a glance" how a trade went - you'll need to look at it quite in detail quite often.

The problem is - no matter how much info you put there - it'll not prevent anyone from falsifying that information if they have that intend.


> and the number of deleted trades in the DB

I wonder how you would track that reliably. 
while we can increment a counter whenever `/delete` is called - nothing prevents you from deleting the trades directly via database.

**Comment by robcaulk** [comment]
Yeah I understand the point about cluttering messages. But I do think having slippage reported in the message would serve a dual purpose of being useful and protecting against falsified information.

**Comment by xmatthias** [comment]
I've been mainly talking about live/dry detection (or fake detection) - not so much about slippage / other useful metrics.

---

slippage ... you mean the difference between rate requested and rate filled? sure, that's a viable option to display (and not one i was talking about above).

That will not improve reliability of the reports though - as you'll still not know if it's live, dry, or fake.

There's also #6916 - which will fill part of the above (show the candle / make it more difficult to fake) - but you have to be honest - not many people will compare the values from a screenshot posted with the real values on exchange - so i doubt this will give much visibility.

---

For dry/live
What i could imageine for example would be something along these lines - which is not adding much clutter, but should still enhance what you need):

```
✳ Binance (dry): Exiting BAND/USDT (#130)
Unrealized Profit: 3.68% (profit: 5.47911150 USDT / 5.479 USD)
Enter Tag: clork_bear
Exit Reason: roi_custom_bbw
Duration: 5:14:53 (314.9 min)
Direction: Long
Amount: 77.10000000
Open Rate: 1.93000000
Current Rate: 2.00500000
Close Rate: 2.00500000
```

adding the `(dry)` to the initial line, you'll know this is just a dry run.
it's obviously still easy to fake / remove - but with open source - everything will be - as it's all just a small change away.

**Comment by robcaulk** [comment]
How would there be slippage in dry? It seems to me slippage would kill two birds with one stone since it would be harder to fake for people who run dry but want to pretend to be live - Bird number 1. 

Also slippage is just very useful information - bird number 2 ;)

Just looked at #6916 . I agree it helps add the “fingerprint” because, presumably, dry close rates will be identical to the candle finger print and live close rates shouldnt be the same due to the slippage. Right?

**Comment by xmatthias** [comment]
depending on the order type, you will have slippage (or you don't) - both in live and dry.

limit orders will fill at the desired rate (or better) (the "better" is not possible for limit orders - but it's rare unless you fake market orders on live, too).

for market orders - they can slip just as much (up to 5%) on dry-run as they are on live.

Using "has slippage" as a detection for live is therefore not really applicable - as it'll depend on the order configuration for both modes - not on "live or dry" ...

**Comment by xmatthias** [comment]
The `(dry)` part is now in.

i'm not sure about the rest though - as i don't think it can be detected reliably enough to be useful

**Comment by robcaulk** [comment]
Thanks a lot
