### ISSUE TITLE
error installing freqtrade

### ISSUE THREAD

**Issue by Inkz2097** [freqtrade/freqtrade#6965]
root@localhost:/# pip3 install freqtrade
Collecting freqtrade
  Using cached https://files.pythonhosted.org/packages/f5/8f/085589449ec6b795f00f02b8c4b74fa27ddfce2804f81b1bfd2441cf5f91/freqtrade-2022.4.2-py3-none-any.whl
Requirement already satisfied: tables in /usr/lib/python3/dist-packages (from freqtrade)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from freqtrade)
Collecting cachetools (from freqtrade)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/ea/c1/4740af52db75e6dbdd57fc7e9478439815bbac549c1c05881be27d19a17d/cachetools-4.2.4-py3-none-any.whl
Requirement already satisfied: jinja2 in /usr/lib/python3/dist-packages (from freqtrade)
Collecting python-telegram-bot>=13.4 (from freqtrade)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/04/cc/f80083270fdab8ba8da3fb89679055dad6f9eb5a060ad63737804cbf1919/python_telegram_bot-13.12-py3-none-any.whl (511kB)
    100% |████████████████████████████████| 512kB 2.8MB/s
Collecting uvicorn (from freqtrade)
  Downloading https://files.pythonhosted.org/packages/a0/bb/1f93757efc22e6e047021dd10255ae471e7930cfc1676ad18b9c70de48e5/uvicorn-0.17.0-py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 13.3MB/s
Collecting python-rapidjson (from freqtrade)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/d1/0c/29abea52b39d3a48bffe3f3722bcd250fa3d3eef279775d73e49020ee7c8/python-rapidjson-1.6.tar.gz (221kB)
    100% |████████████████████████████████| 225kB 5.8MB/s
Collecting orjson (from freqtrade)
  Using cached https://files.pythonhosted.org/packages/92/97/895dfe0c2e7820fd5453d0efab6a9036de7f97b4edfd157a6a414dd3b0ee/orjson-3.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-09j_tn7x/orjson/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-09j_tn7x/orjson/

I am trying to install freqtrade but keep getting the error. Could anybody help with this please?

**Comment by xmatthias** [comment]
The paths suggest that you're using python 3.6 - which reached it's end of life in 2021.

Freqtrade does not support (nor will it run) on python 3.6 (nor python 3.7). This most likely also applies to dependencies, although we do not check for these explicitly - as it's really irrelevant if a dependency works on 3.6 if freqtrade doesn't.

Therefore, please retry an installation with a supported version of python (python 3.8, 3.9 or 3.10).
