### ISSUE TITLE
calculate signals on current candle open price

### ISSUE THREAD

**Issue by jvrodrisan** [freqtrade/freqtrade#6966]
## Describe your environment

  * Operating system: MacOS 12.4
  * Python Version: Python 3.9.12
  * CCXT version: 1.84.43
  * Freqtrade Version: Docker
  
## Your question

I am running some systems in backtrader, where one of the requisites is to calculate signals on the candle open price, using the previous candle close price. If the signal is successful,  the system buys using market price as closes as possible to the open price of the current candle. In backtrader, there is a mode called "cheat_on_open" to achieve this behaviour and also works on live (https://www.backtrader.com/blog/posts/2017-05-01-cheat-on-open/cheat-on-open/) , is this something supported by freqtrade. I am fascinated by the possibilities of freqtrade and would like to port these systems. I've been looking into the documentation but I haven't found it. Thanks in advance.

**Comment by xmatthias** [comment]
Freqtrade will provide you with closed candles only. 
non-closed candles are not available to the strategy in live.

The main reason for this is repainting and backtest cheating (as well as API call reductions).
Using a non-finished candle on an indicator would lead to the close value being used (almost all indicators use the candle's close value by default) - so it would use the current candle's close (which is obviously not the real close, and is constantly changing with every trade).

You could probably cheat on backtesting by using the open candle - but it would not transfer to live (although i guess you could use the orderbook price to "simulate" the candle open price for that ...).
