### ISSUE TITLE
bot can't use HO file's protect params and use the python file default value.

### ISSUE THREAD

**Issue by ssssi** [freqtrade/freqtrade#6977]
hi team.i had put HO file and strategy file together. but when i reload config.i find my bot always use python file default value of protection.not use HO file value.

this is telegram send to me:
Using Protections: 
CooldownPeriod - Cooldown period of 5 candles.
MaxDrawdown - Max drawdown protection, stop trading if drawdown is > 0.2 within 12 candles.
StoplossGuard - Frequent Stoploss Guard, 3 stoplosses within 12 candles.

this is logs of my bot.it looks normal in use HO file.but in telegram it send python file default value.
![image](https://user-images.githubusercontent.com/11401775/173339401-15f0356e-1a2b-4653-9076-7146a45f3acc.png)

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.


Also, please provide the complete log output (up to this point) as text (no screenshot).

**Comment by ssssi** [comment]
> Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment. We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.
> 
> Also, please provide the complete log output (up to this point) as text (no screenshot).

ok.got it
