### ISSUE TITLE
Add a current position side to custom_exit()

### ISSUE THREAD

**Issue by cryptenshtein** [freqtrade/freqtrade#6980]
## Describe your environment

  * Operating system: MacOS
  * Python Version: 2.7.18
  * CCXT version: 1.85.57
  * Freqtrade Version: docker-0a801c02

## Describe the enhancement

Im new to FT and coding.
And I miss the functionality in **custom_exit()**
for my strategy. It would be great to be able to use inside **custom_exit()** values of **side** so that such code would work.

```
        if current_profit < -0.02:
            if (dataframe['ema_short'] < dataframe['ema_long']):
                if side = 'long':
                    return 'switch_to_short'
```

Is it possible to implement this any other way maybe or is it possible to add **side** to **custom_exit()**?
Thanks for attention.

**Comment by moinonin** [comment]
A quick solution if I understood correctly is to use 'enter_tag'. Which means you have to tag the original buys. So supposing you tagged the buy signal as ['enter_long', 'enter_tag']] = (1, 'some_buy'):  
Then you would do:  
```
        if current_profit < -0.02:
            if (last_candle['ema_short'] < last_candle['ema_long']):
                if trade.enter_tag = 'some_buy':
                    return 'switch_to_short'
```

**Comment by xmatthias** [comment]
I'd not rely on the enter_tag for this (unless you need further differentiation within one trade side).

`custom_exit()` (as well as all other, non entry related callbacks) provide you with the `trade` object.

You can use `trade.is_short`  (`True` for Shorts, `False` for Longs) to determine if it's a sort - or `trade.entry_side` (buy/sell) - or `trade.trade_direction` (long/short) for this detection
