### ISSUE TITLE
Max leverage on backtest

### ISSUE THREAD

**Issue by mert-donmez** [freqtrade/freqtrade#6981]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.10.4
  * CCXT version: 1.83.62
  * Freqtrade Version: develop-d1f61c4cf
  
## Your question

There is a leverage limit set by Binance.
And that limit is 400,000$ for ETH with 10x leverage (400k $ * 10x = 4M $). 

While looking at the trades in frequi, I saw that there were some problems after 400 thousand dollars. There are some issues in the stake amount and eth amount part.

((Stake amount * 10x) / Amount) not equal to Open rate.

I don't know is it a major bug that needs to be fixed , I just noticed and wanted to say

Thanks.

![Screenshot from 2022-06-15 02-38-43](https://user-images.githubusercontent.com/83416622/173708229-61e7acff-67bc-4adf-a4fd-5e2beb9de5a0.png)

**Comment by xmatthias** [comment]
Freqtrade is aware of the limts (on binance - based on a cached leverage tiers file) - and will adjust your leverage to the actual possible value.

So even if you return 10x all the time (for all trades) - your trade may only be allowed to use 5x leverage based on your stake size - therefore your leverage will be adjusted to that.

I've only done the math for the first trade - where your calculation is correct if you use 5x leverage (the allowed value for this leverage tier bracket) - based on [this link](https://www.binance.com/en/futures/trading-rules/perpetual/leverage-margin) - make sure to filter on ETH/USDT. (`1_210_000$ / 5x`).

As such - i don't see this as a problem - but as an actual feature - as freqtrade is aware of these limits, and respects them as well.
