### ISSUE TITLE
does freqtrade works on binance future test net (sandbox)

### ISSUE THREAD

**Issue by Orbazz** [freqtrade/freqtrade#6982]
## Describe your environment

  * Operating system: __win 10__
  * Python Version: __3.9___ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __2022.5__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
please does freqtrade works on binance future test net (sandbox) prefectly , because have check some issues and am not seeing solution in questions.
*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
orbbotfreq   | 2022-06-15 11:55:18,322 - freqtrade.worker - INFO - Starting worker 2022.4.2
orbbotfreq   | 2022-06-15 11:55:18,323 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/config.json ...
orbbotfreq   | 2022-06-15 11:55:18,356 - freqtrade.loggers - INFO - Verbosity set to 0
orbbotfreq   | 2022-06-15 11:55:18,362 - freqtrade.configuration.configuration - INFO - Runmode set to live.
orbbotfreq   | 2022-06-15 11:55:18,368 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
orbbotfreq   | 2022-06-15 11:55:18,376 - freqtrade.configuration.configuration - INFO - Dry run is disabled
orbbotfreq   | 2022-06-15 11:55:18,383 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
orbbotfreq   | 2022-06-15 11:55:18,460 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
orbbotfreq   | 2022-06-15 11:55:18,925 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
orbbotfreq   | 2022-06-15 11:55:18,942 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
orbbotfreq   | 2022-06-15 11:55:18,953 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
orbbotfreq   | 2022-06-15 11:55:19,147 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
orbbotfreq   | 2022-06-15 11:55:19,153 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
orbbotfreq   | 2022-06-15 11:55:19,161 - freqtrade.freqtradebot - INFO - Starting freqtrade 2022.4.2
orbbotfreq   | 2022-06-15 11:55:19,847 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy FSupertrendStrategy from '/freqtrade/user_data/strategies/f_supertrend_strategy.py'...
orbbotfreq   | 2022-06-15 11:55:19,858 - freqtrade.strategy.hyper - INFO - Found no parameter file.
orbbotfreq   | 2022-06-15 11:55:19,865 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_m1 = 4
orbbotfreq   | 2022-06-15 11:55:19,870 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_m2 = 7
orbbotfreq   | 2022-06-15 11:55:19,878 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_m3 = 1
orbbotfreq   | 2022-06-15 11:55:19,886 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_p1 = 8
orbbotfreq   | 2022-06-15 11:55:19,895 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_p2 = 9
orbbotfreq   | 2022-06-15 11:55:19,903 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_p3 = 8
orbbotfreq   | 2022-06-15 11:55:19,912 - freqtrade.strategy.hyper - INFO - Strategy Parameter: sell_m1 = 1
orbbotfreq   | 2022-06-15 11:55:19,922 - freqtrade.strategy.hyper - INFO - Strategy Parameter: sell_m2 = 3
orbbotfreq   | 2022-06-15 11:55:19,933 - freqtrade.strategy.hyper - INFO - Strategy Parameter: sell_m3 = 6
orbbotfreq   | 2022-06-15 11:55:19,941 - freqtrade.strategy.hyper - INFO - Strategy Parameter: sell_p1 = 16
orbbotfreq   | 2022-06-15 11:55:19,949 - freqtrade.strategy.hyper - INFO - Strategy Parameter: sell_p2 = 18
orbbotfreq   | 2022-06-15 11:55:19,956 - freqtrade.strategy.hyper - INFO - Strategy Parameter: sell_p3 = 18
orbbotfreq   | 2022-06-15 11:55:19,962 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
orbbotfreq   | 2022-06-15 11:55:19,972 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 1h.
orbbotfreq   | 2022-06-15 11:55:19,977 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.   
orbbotfreq   | 2022-06-15 11:55:19,983 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 100.
orbbotfreq   | 2022-06-15 11:55:19,989 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
orbbotfreq   | 2022-06-15 11:55:19,997 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.1, '30': 0.75, '60': 0.05, '120': 
0.025}
orbbotfreq   | 2022-06-15 11:55:20,004 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1h
orbbotfreq   | 2022-06-15 11:55:20,012 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.265
orbbotfreq   | 2022-06-15 11:55:20,019 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
orbbotfreq   | 2022-06-15 11:55:20,028 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.05
orbbotfreq   | 2022-06-15 11:55:20,034 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.1
orbbotfreq   | 2022-06-15 11:55:20,042 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
orbbotfreq   | 2022-06-15 11:55:20,048 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
orbbotfreq   | 2022-06-15 11:55:20,058 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
orbbotfreq   | 2022-06-15 11:55:20,098 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
orbbotfreq   | 2022-06-15 11:55:20,125 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'gtc', 'exit': 'gtc'}   
orbbotfreq   | 2022-06-15 11:55:20,138 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
orbbotfreq   | 2022-06-15 11:55:20,148 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 100
orbbotfreq   | 2022-06-15 11:55:20,156 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
orbbotfreq   | 2022-06-15 11:55:20,162 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 18
orbbotfreq   | 2022-06-15 11:55:20,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
orbbotfreq   | 2022-06-15 11:55:20,174 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
orbbotfreq   | 2022-06-15 11:55:20,180 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
orbbotfreq   | 2022-06-15 11:55:20,189 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
orbbotfreq   | 2022-06-15 11:55:20,252 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
orbbotfreq   | 2022-06-15 11:55:20,281 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
orbbotfreq   | 2022-06-15 11:55:20,289 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
orbbotfreq   | 2022-06-15 11:55:20,299 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
orbbotfreq   | 2022-06-15 11:55:20,305 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
orbbotfreq   | 2022-06-15 11:55:20,311 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
orbbotfreq   | 2022-06-15 11:55:20,340 - freqtrade.exchange.exchange - INFO - Using CCXT 1.80.61
orbbotfreq   | 2022-06-15 11:55:20,348 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
orbbotfreq   | 2022-06-15 11:55:20,508 - freqtrade.exchange.exchange - INFO - Enabled Sandbox API on binance
orbbotfreq   | 2022-06-15 11:55:20,518 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
orbbotfreq   | 2022-06-15 11:55:20,590 - freqtrade.exchange.exchange - INFO - Enabled Sandbox API on binance
orbbotfreq   | 2022-06-15 11:55:20,596 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
orbbotfreq   | 2022-06-15 11:55:20,615 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
orbbotfreq   | Traceback (most recent call last):
orbbotfreq   |   File "/freqtrade/freqtrade/exchange/exchange.py", line 457, in _load_markets
orbbotfreq   |     self._markets = self._api.load_markets()
orbbotfreq   |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1545, in load_markets
orbbotfreq   |     currencies = self.fetch_currencies()
orbbotfreq   |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 1254, in fetch_currencies
orbbotfreq   |     response = self.sapiGetCapitalConfigGetall(params)
orbbotfreq   |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 496, in inner
orbbotfreq   |     return entry(_self, **inner_kwargs)
orbbotfreq   |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 5039, in request
orbbotfreq   |     response = self.fetch2(path, api, method, params, headers, body, config, context)
orbbotfreq   |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 542, in fetch2
orbbotfreq   |     request = self.sign(path, api, method, params, headers, body)
orbbotfreq   |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4910, in sign
orbbotfreq   |     raise NotSupported(self.id + ' does not have a testnet/sandbox URL for ' + api + ' endpoints')
orbbotfreq   | ccxt.base.errors.NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints
orbbotfreq   | 2022-06-15 11:55:20,674 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
orbbotfreq   | 2022-06-15 11:55:20,691 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
orbbotfreq   | Traceback (most recent call last):
orbbotfreq   |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
orbbotfreq   |     worker = Worker(args)
orbbotfreq   |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
orbbotfreq   |     self._init(False)
orbbotfreq   |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
orbbotfreq   |     self.freqtrade = FreqtradeBot(self._config)
orbbotfreq   |   File "/freqtrade/freqtrade/freqtradebot.py", line 67, in __init__
orbbotfreq   |     self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
orbbotfreq   |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
orbbotfreq   |     exchange = ExchangeResolver._load_exchange(exchange_name,
orbbotfreq   |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
orbbotfreq   |     exchange = ex_class(**kwargs)
orbbotfreq   |   File "/freqtrade/freqtrade/exchange/exchange.py", line 184, in __init__
orbbotfreq   |     self.validate_stakecurrency(config['stake_currency'])
orbbotfreq   |   File "/freqtrade/freqtrade/exchange/exchange.py", line 492, in validate_stakecurrency
orbbotfreq   |     raise OperationalException(
orbbotfreq   | freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.orbbotfreq   | 2022-06-15 11:55:40,678 - freqtrade.worker - INFO - Starting worker 2022.4.2
orbbotfreq   | 2022-06-15 11:55:40,678 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/config.json ...
orbbotfreq   | 2022-06-15 11:55:40,703 - freqtrade.loggers - INFO - Verbosity set to 0
orbbotfreq   | 2022-06-15 11:55:40,708 - freqtrade.configuration.configuration - INFO - Runmode set to live.
orbbotfreq   | 2022-06-15 11:55:40,713 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
orbbotfreq   | 2022-06-15 11:55:40,719 - freqtrade.configuration.configuration - INFO - Dry run is disabled
orbbotfreq   | 2022-06-15 11:55:40,724 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
orbbotfreq   | 2022-06-15 11:55:40,731 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
orbbotfreq   | 2022-06-15 11:55:41,317 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
orbbotfreq   | 2022-06-15 11:55:41,327 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
orbbotfreq   | 2022-06-15 11:55:41,332 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
orbbotfreq   | 2022-06-15 11:55:41,505 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
orbbotfreq   | 2022-06-15 11:55:41,517 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
orbbotfreq   | 2022-06-15 11:55:41,525 - freqtrade.freqtradebot - INFO - Starting freqtrade 2022.4.2
orbbotfreq   | 2022-06-15 11:55:42,514 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy FSupertrendStrategy from '/freqtrade/user_data/strategies/f_supertrend_strategy.py'...
orbbotfreq   | 2022-06-15 11:55:42,526 - freqtrade.strategy.hyper - INFO - Found no parameter file.
orbbotfreq   | 2022-06-15 11:55:42,533 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_m1 = 4
orbbotfreq   | 2022-06-15 11:55:42,539 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_m2 = 7
orbbotfreq   | 2022-06-15 11:55:42,550 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_m3 = 1
orbbotfreq   | 2022-06-15 11:55:42,556 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_p1 = 8
orbbotfreq   | 2022-06-15 11:55:42,564 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_p2 = 9
orbbotfreq   | 2022-06-15 11:55:42,578 - freqtrade.strategy.hyper - INFO - Strategy Parameter: buy_p3 = 8
orbbotfreq   | 2022-06-15 11:55:42,590 - freqtrade.strategy.hyper - INFO - Strategy Parameter: sell_m1 = 1
orbbotfreq   | 2022-06-15 11:55:42,598 - freqtrade.strategy.hyper - INFO - Strategy Parameter: sell_m2 = 3
orbbotfreq   | 2022-06-15 11:55:42,652 - freqtrade.strategy.hyper - INFO - Strategy Parameter: sell_m3 = 6
orbbotfreq   | 2022-06-15 11:55:42,664 - freqtrade.strategy.hyper - INFO - Strategy Parameter: sell_p1 = 16
orbbotfreq   | 2022-06-15 11:55:42,677 - freqtrade.strategy.hyper - INFO - Strategy Parameter: sell_p2 = 18
orbbotfreq   | 2022-06-15 11:55:42,686 - freqtrade.strategy.hyper - INFO - Strategy Parameter: sell_p3 = 18
orbbotfreq   | 2022-06-15 11:55:42,755 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
orbbotfreq   | 2022-06-15 11:55:42,786 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 1h.
orbbotfreq   | 2022-06-15 11:55:42,798 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.   
orbbotfreq   | 2022-06-15 11:55:42,805 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 100.
orbbotfreq   | 2022-06-15 11:55:42,817 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
orbbotfreq   | 2022-06-15 11:55:42,823 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.1, '30': 0.75, '60': 0.05, '120': 
0.025}
orbbotfreq   | 2022-06-15 11:55:42,870 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1h
orbbotfreq   | 2022-06-15 11:55:42,892 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.265
orbbotfreq   | 2022-06-15 11:55:42,918 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
orbbotfreq   | 2022-06-15 11:55:42,939 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.05
orbbotfreq   | 2022-06-15 11:55:42,946 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.1
orbbotfreq   | 2022-06-15 11:55:42,954 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
orbbotfreq   | 2022-06-15 11:55:42,960 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
orbbotfreq   | 2022-06-15 11:55:43,017 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
orbbotfreq   | 2022-06-15 11:55:43,023 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
orbbotfreq   | 2022-06-15 11:55:43,033 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'gtc', 'exit': 'gtc'}
orbbotfreq   | 2022-06-15 11:55:43,047 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
orbbotfreq   | 2022-06-15 11:55:43,053 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 100
orbbotfreq   | 2022-06-15 11:55:43,062 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
orbbotfreq   | 2022-06-15 11:55:43,068 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 18
orbbotfreq   | 2022-06-15 11:55:43,150 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
orbbotfreq   | 2022-06-15 11:55:43,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
orbbotfreq   | 2022-06-15 11:55:43,174 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
orbbotfreq   | 2022-06-15 11:55:43,182 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
orbbotfreq   | 2022-06-15 11:55:43,189 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
orbbotfreq   | 2022-06-15 11:55:43,257 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
orbbotfreq   | 2022-06-15 11:55:43,280 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
orbbotfreq   | 2022-06-15 11:55:43,287 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
orbbotfreq   | 2022-06-15 11:55:43,296 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
orbbotfreq   | 2022-06-15 11:55:43,314 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
orbbotfreq   | 2022-06-15 11:55:43,381 - freqtrade.exchange.exchange - INFO - Using CCXT 1.80.61
orbbotfreq   | 2022-06-15 11:55:43,405 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
orbbotfreq   | 2022-06-15 11:55:43,636 - freqtrade.exchange.exchange - INFO - Enabled Sandbox API on binance
orbbotfreq   | 2022-06-15 11:55:43,647 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
orbbotfreq   | 2022-06-15 11:55:43,859 - freqtrade.exchange.exchange - INFO - Enabled Sandbox API on binance
orbbotfreq   | 2022-06-15 11:55:43,870 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
orbbotfreq   | 2022-06-15 11:55:43,888 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
orbbotfreq   | Traceback (most recent call last):
orbbotfreq   |   File "/freqtrade/freqtrade/exchange/exchange.py", line 457, in _load_markets
orbbotfreq   |     self._markets = self._api.load_markets()
orbbotfreq   |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1545, in load_markets
orbbotfreq   |     currencies = self.fetch_currencies()
orbbotfreq   |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 1254, in fetch_currencies
orbbotfreq   |     response = self.sapiGetCapitalConfigGetall(params)
orbbotfreq   |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 496, in inner
orbbotfreq   |     return entry(_self, **inner_kwargs)
orbbotfreq   |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 5039, in request
orbbotfreq   |     response = self.fetch2(path, api, method, params, headers, body, config, context)
orbbotfreq   |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 542, in fetch2
orbbotfreq   |     request = self.sign(path, api, method, params, headers, body)
orbbotfreq   |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4910, in sign
orbbotfreq   |     raise NotSupported(self.id + ' does not have a testnet/sandbox URL for ' + api + ' endpoints')
orbbotfreq   | ccxt.base.errors.NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints
orbbotfreq   | 2022-06-15 11:55:43,972 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
orbbotfreq   | 2022-06-15 11:55:43,982 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
orbbotfreq   | Traceback (most recent call last):
orbbotfreq   |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
orbbotfreq   |     worker = Worker(args)
orbbotfreq   |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
orbbotfreq   |     self._init(False)
orbbotfreq   |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
orbbotfreq   |     self.freqtrade = FreqtradeBot(self._config)
orbbotfreq   |   File "/freqtrade/freqtrade/freqtradebot.py", line 67, in __init__
orbbotfreq   |     self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
orbbotfreq   |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
orbbotfreq   |     exchange = ExchangeResolver._load_exchange(exchange_name,
orbbotfreq   |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
orbbotfreq   |     exchange = ex_class(**kwargs)
orbbotfreq   |   File "/freqtrade/freqtrade/exchange/exchange.py", line 184, in __init__
orbbotfreq   |     self.validate_stakecurrency(config['stake_currency'])
orbbotfreq   |   File "/freqtrade/freqtrade/exchange/exchange.py", line 492, in validate_stakecurrency
orbbotfreq   |     raise OperationalException(
orbbotfreq   | freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details.orbbotfreq exited with code 0
PS C:\myfreqbot\freq1>

**Comment by AntonioRitucci** [comment]
Hi there! I faced the same error.
After reading the suggested ccxt issue.
I found that:

Here is method [set_sandbox](https://github.com/freqtrade/freqtrade/blob/1d2b89bc138ce6d187b054845a8e765c79f86133/freqtrade/exchange/exchange.py#L261) 
called at the end of  method  [_init_ccxt ](https://github.com/freqtrade/freqtrade/blob/1d2b89bc138ce6d187b054845a8e765c79f86133/freqtrade/exchange/exchange.py#L228)

Working with Binance I did like that:
```
api = getattr(ccxt_module, name.lower())(ex_config)
            if exchange_config.get('sandbox'):
                api.set_sandbox_mode(True)
```

I plan to use only Binance for now, do you think it is fine?

**Comment by stash86** [comment]
please open new issue if you have any question. As said above, testnet gonna gives you a very limited candles. You won't get whatever you want with it. You can just use freqtrade dry run mode
