### ISSUE TITLE
/fe command not working at all

### ISSUE THREAD

**Issue by stash86** [freqtrade/freqtrade#6985]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

According to /help command, /fe is an alias to /forceexit. In reality, /fe <trade_id> does nothing

### Steps to reproduce:

  1. Have open trade
  2. Type /fe <trade_id> in the telegram bot
  3. Nothing happened
  
### Observed Results:

  * What happened?
  
![image](https://user-images.githubusercontent.com/13656154/174417621-96b47467-ec3f-44de-a148-fa4f8de74dd4.png)

  * What did you expect to happen?
/fe 25 should have trigger the bot to exit the trade

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by stash86** [comment]
gonna look into this later, working on something else, hence I opened the issue as reminder

**Comment by xmatthias** [comment]
i think the documentation / help is wrong - the proper command is `/fx`. `/fe` is ambiguous - and could be "**F**orce**E**xit" - or "**F**orce**E**ntry"

**Comment by MonishLokhande** [comment]
For me the /fx and /forceexit both commands are not working, the version I am running is Version: 2022.10

**Comment by xmatthias** [comment]
@MonishLokhande that's not related to this issue - Therefore please open a new issue for your problem (obviously including logs and stuff). Simply "is not working" is not something we will be able to assist you with.
