### ISSUE TITLE
What to use instead of .iloc[-1] to populate indicator?

### ISSUE THREAD

**Issue by Niqnil** [freqtrade/freqtrade#6986]
## Describe your environment

  * Operating system:  Ubuntu 21.10
  * Python Version: Python 3.9.9
  * CCXT version: ccxt==1.77.45
  * Freqtrade Version: freqtrade docker-34a44b9d
  
I am trying to get the gradient using numpy [polynomial](https://numpy.org/doc/stable/reference/routines.polynomials.html) and saw not to use .iloc[-1] from https://www.freqtrade.io/en/stable/strategy-customization/#common-mistakes-when-developing-strategies. What is the correct way to get the x-latest values?

```
def informative_1h_indicators(
self, dataframe: DataFrame, metadata: dict
) -> DataFrame:

assert self.dp, "DataProvider is required for multiple timeframes."
informative_1h = self.dp.get_pair_dataframe(
pair=metadata["pair"], timeframe=self.info_timeframe_1h
)

        # ...etc

        x = np.arange(7)
        y = np.array(
            [
                informative_1h["ema"].iloc[-7],
                informative_1h["ema"].iloc[-6],
                informative_1h["ema"].iloc[-5],
                informative_1h["ema"].iloc[-4],
                informative_1h["ema"].iloc[-3],
                informative_1h["ema"].iloc[-2],
                informative_1h["ema"].iloc[-1],
            ]
        )
        informative_1h["gradient"], _ = np.polynomial.Polynomial.fit(x, y, deg=1)

        return informative_1h
```

**Comment by xmatthias** [comment]
it's not about `.iloc[-x]` - but about the concept of using the "last" rows of the dataframe.

in all `populate_*`  methods, backtesting will have the full dataframe available. by using absolute referencing (last X candles of the dataframe) - you're automatically looking into the future.

An alternative is usually `.shift()` - which will allow you to get the row prior to the "current" row (but in a vectorized way).
It will however give you a series of "dataframe length" - so you will have to rethink on what you're trying to do here.

**Comment by Niqnil** [comment]
Thanks for your explanation. I was trying to get the gradient of the best fit line over last x values. `.shift()` does not work because polynomial requires 2 arrays of same length. I used `.rolling().apply()` and it works in backtesting.

```
# in populate_*
informative_1h["ema_gradient"] = (
            informative_1h["ema"].rolling(window=7).apply(get_gradient, raw=False)
        )

def get_gradient(s: pd.Series, window: int = 7) -> pd.Series:
    x = np.arange(window)
    gradient, _ = np.polynomial.Polynomial.fit(x, s, deg=1)
    return gradient
```
