### ISSUE TITLE
When a trade is still open ,can we open another trade on the same pair?

### ISSUE THREAD

**Issue by BourneSuper** [freqtrade/freqtrade#6992]
## Describe your environment

  * Operating system:  ubuntu
  * Python Version: 3.8.10
  * CCXT version:1.74.63
  * Freqtrade Version: freqtrade 2022.5.1
  
## Your question

Is there a way of opening multiple trades on the same pair?

For example, the market price goes down from 10 to 9  , then goes up to 11.
buy it when price is 10.0, 9.5 , 9.0,   sell  it  when price is 9.5, 10.0, 10.5.

When a trade is still open ,can we open another trade on the same pair?
Can we go long and go short at the same time?

**Comment by xmatthias** [comment]
Freqtrade only allows one trade per pair.

You can however use use [callbacks](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position) to increase your position (decreasing is still WIP).

You cannot go long and short at the same time.
