### ISSUE TITLE
Partial Profit-Booking for Risk Management

### ISSUE THREAD

**Issue by shakeel-appyhigh** [freqtrade/freqtrade#6993]
## Describe your environment
(if applicable)

  * Operating system: Ubuntu 18.04
  * Python Version: 3.8.10
  * CCXT version: 1.81.81
  * Freqtrade Version: freqtrade develop-a27f4a5 

## Describe the enhancement

Can we have a way where we can book partial profits on a certain position as a part of risk management? Basically I am requesting for an enhancement in the roi parameter where we can close a certain percentage of the position when a particular roi is reached and keep the rest of it open so as to minimize risk but also keep an avenue of further profit open.

**Comment by xmatthias** [comment]
Please subscribe to #1519  for this, where this was requested initially.

This is currently being worked on in #6545 - but for now, I'd not advise anyone to use this branch, even though it seems advanced based on the number of commits.

A side-comment: it'll not be done via ROI parameter, but via callback, where you can size down (the one where you can currently increase your position size).
It'll provide more flexibility - where the take-profit is not based on ROI, but based on other metrics / methods.
