### ISSUE TITLE
Custom docker image sample potentially misleading

### ISSUE THREAD

**Issue by ntziolis** [freqtrade/freqtrade#6994]
Not 100% sure, but shouldn't the switch to `ftuser` happen prior to any call to `pip install --user`?

https://github.com/freqtrade/freqtrade/blob/eebd624baf13eabb170bc10070a7af164eaa360f/docker/Dockerfile.custom#L10

**Comment by xmatthias** [comment]
it's a comment for convenience. 
If you look 2 (significant) lines above this (or widen the range a bit)

https://github.com/freqtrade/freqtrade/blob/eebd624baf13eabb170bc10070a7af164eaa360f/docker/Dockerfile.custom#L5-L10

You'll notice that we're not setting the value to root by default (that line is commented, too).
As the comment states - this is an example - maybe you'll not need to install via pip - but your installation must happen via apt-get first (which must be done as root) - where you need to switch to the root user.

you're correct that the switch should happen before installing with `--user` - but if you change the USER lines, you're most likely also modifying the "pip" lines - so you'll need to reevaluate all actions this custom docker file is taking.
