### ISSUE TITLE
Empty candle, lengths must match to compare error

### ISSUE THREAD

**Issue by infiniteneurotech** [freqtrade/freqtrade#6997]
## Describe your environment

  * Operating system: ____Windows 10
  * Python Version: _____ 3.10.5
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ 0.3.6
  
Hi,

I'm getting this error when I start FreqTrade:

2022-06-22 08:17:50,844 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair MATIC/USDT: ('Lengths must match to compare', (999,), (1,))
2022-06-22 08:17:50,852 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair LTC/USDT

If I print the dataframe in the populate_indicators method it shows the indicators have correctly populated so I assume this is something to do with my strategy logic in the populate_entry_trend method. I've tried many different permutations and searched extensively, but can't solve it. Here's an example of my strategy logic for the indicators I've created:

(dataframe['close'] > dataframe['ema12']) &
                (dataframe['ema12'] > ['ema24']) &
                (dataframe['roc'] > 0.2)

As far as I can tell my logic follows other examples so it's driving me nuts. What causes this problem and how can I fix it?

Many thanks!

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
I think the middle row is wrong - instead of `(dataframe['ema12'] > ['ema24']) &` - you might want to have `(dataframe['ema12'] > dataframe['ema24']) &` - adding a "dataframe".

you can't compare a dataframe column with a list of 1 element (which is the right `['ema24']`) - and that's what the error effectively says.

**Comment by infiniteneurotech** [comment]
I cannot believe I missed that, I think I need to book in to see my optometrist.

Thanks so much for your help, it's working perfectly now.
