### ISSUE TITLE
How to programmatically get balance?

### ISSUE THREAD

**Issue by avibrazil** [freqtrade/freqtrade#6998]
I know how to see it in the bot, but that's not what I mean. But how to get current balance in USD from command line or as a SQL statement or with some python snippet?

Balance I mean including currently open trades converted to USD by current coin price.

I investigated the SQLite DB, which only has trade and orders information, no balance, not even at some specific point in time. And it is quite difficult to compute current balance for open trades.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

From within the strategy you can get the balance via the [wallets](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-wallets) option.

There's no possibility to do it directly via command line, SQL or some "python snippet" - although i guess you can use the [rest api](https://www.freqtrade.io/en/stable/rest-api/#rest-api) to get the info from a running bot.

**Comment by avibrazil** [comment]
Perfect solution. And I'm sorry to not follow the template. I will in the future.

Snippet would be:

```shell
python rest_client.py --config same-freqtrade-config-with-api-part.json balance | python -m json.tool
```
