### ISSUE TITLE
1month Backtesting time frame 1min

### ISSUE THREAD

**Issue by vaha6** [freqtrade/freqtrade#6999]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: python -3
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
Dear Friends,
when I start to run backtesting of my strategy for 1 month with time frame of 1min, in the middle of backtesting it cancels and before it shows me the results it gives up and give me back the shell with no error.
what can be done to overcome this problem?

**Comment by xmatthias** [comment]
Without logs (where exactly did it interupt) - it's difficult to tell.

most likely - your system is running out of memory. you should be able to see this in the system log.

in principle - the [hyperopt suggestions](https://www.freqtrade.io/en/latest/hyperopt/#out-of-memory-errors) apply to backtesting as well - especially with 1m data.

**Comment by vaha6** [comment]
I also tough the same when back testing and started monitoring as below:
I have used command " sar -u -r 2 99999", and the memory is 14g free out of 16g. and cpu idle is 84% on all cores.
however, when I use "top", all the process is done only by one(1) core and the rest of cores are free. and the only used core is engaged 100%. 
I also ask you please help me balance the cpu load

**Comment by xmatthias** [comment]
Backtesting will not be using more than one core.

Without logs - (up to the point where it stops) - there'll be nothing we can do to help you further - as it's unclear where exactly it stops.

you mention "in the middle" - but from a program perspective, there's no such term - it's a line which usually can be identified from the logs.

You may also wanna run backtesting with debug logs - which should show this even better - (there however please only provide the last few lines ...).

**Comment by vaha6** [comment]
[test.log](https://github.com/freqtrade/freqtrade/files/8977668/test.log)
here is the log.
good to know that when I do the same with my amazon (AWS) web server even for 6 months there is no problem. but when I do it with my server (core I 5 Intel 11400 2.6g) it will abort after a while. please check the log file as attached.
I also need to know does dry run use one core again? same as backtesting.

**Comment by xmatthias** [comment]
with 2.6g you're almost certainly running into memory problems when using 1m data.

1m data is rather big - also for 1 month - as such - please refer to the [hyperopt suggestions](https://www.freqtrade.io/en/latest/hyperopt/#out-of-memory-errors) - suggestions how to decrease the amount of data are valid for backtesting as well.

**Comment by vaha6** [comment]
sir memory is 16g and 14 g is free

**Comment by vaha6** [comment]
there is no memory problem here. as I already mentioned.
2.6 g hz is the cpu info i provided.

**Comment by xmatthias** [comment]
Freqtrade will not stop without message unless the process is killed externally.
please check your system log (journalctl or similar) for errors (you might see a OOM error there).

maybe also try to run in verbose mode (`-v`) - which should log a lot and show us how far the bot comes.

**Comment by stash86** [comment]
Just want to add, 16GB isn't huge. I can even get OOM error on 128GB memory. It's all about how many pairs, how many indicators, how many timeframes used

**Comment by vaha6** [comment]
I am still checking the logs.
 meanwhile may I ask your help for load balancing please? what command or what changes are required to be done to achieve this task.

**Comment by vaha6** [comment]
could you please let me know where can i access to the engine source code to adjust it.

**Comment by vaha6** [comment]
you were right. this is memory problem.

**Comment by vaha6** [comment]
> Just want to add, 16GB isn't huge. I can even get OOM error on 128GB memory. It's all about how many pairs, how many indicators, how many timeframes used

you were right. I ran and run out of memory
