### ISSUE TITLE
Strategy Hyperopt question

### ISSUE THREAD

**Issue by lovehedy24** [freqtrade/freqtrade#7000]
## Describe your environment

  * Operating system: Ubuntu 20.04.4 LTS 
  * Python Version: Python 3.9.9
  * CCXT version: ccxt==1.80.61
  * Freqtrade Version: freqtrade 2022.4.1
  
## Your question
Hyperopt question
I am a beginner in PYTHON

I wrote a donchian strategy 
want optimization donchian ch parameter
but why have error 

```
import pandas_ta as pd_ta
  
# Donchian parametros optimizar
 buy_dc_upper_len = IntParameter(20, 60, default=20, space="buy")
 sell_dc_lower_len = IntParameter(20, 60, default=20, space="sell")

for val in self.buy_dc_upper_len.range:
            donchian_df = pd_ta.donchian(dataframe['close'], dataframe['close'],    lower_length=dc_lower_len,
                                     upper_length=val)
            dataframe['DC_lower'] = donchian_df[f"DCL_{dc_lower_len}_{val}"]
            dataframe['DC_upper'] = donchian_df[f"DCU_{dc_lower_len}_{val}"]
            dataframe['DC_mid'] = donchian_df[f"DCM_{dc_lower_len}_{val}"]
       
 for val_X in self.sell_dc_lower_len.range:
            donchian_df_X = pd_ta.donchian(dataframe['close'], dataframe['close'], lower_length=val_X,
                                     upper_length=dc_upper_len)
            dataframe['DC_lower_X'] = donchian_df_X[f"DCL_{dc_upper_len}_{val_X}"]
            dataframe['DC_upper_X'] = donchian_df_X[f"DCU_{dc_upper_len}_{val_X}"]
            dataframe['DC_mid_X'] = donchian_df_X[f"DCM_{dc_upper_len}_{val_X}"]

```

```
===================Error MSG=================
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 419, in start
    self.prepare_hyperopt_data()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 400, in prepare_hyperopt_data
    preprocessed = self.backtesting.strategy.advise_all_indicators(data)
  File "/freqtrade/freqtrade/strategy/interface.py", line 1075, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 1075, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 1098, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/workspaces/ft_userdata/user_data/strategies/7_0_Donchian_Opt_H1.py", line 165, in populate_indicators
    dataframe['DC_lower_X'] = donchian_df_X[f"DCL_{dc_upper_len}_{val_X}"]
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/ftuser/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'DCL_99_41'
```

**Comment by xmatthias** [comment]
First off, i don't think you use it right (you're passing in `'close'` twice - the function seems to expect high and low (https://github.com/twopirllc/pandas-ta/blob/2a24fdc1b69110332db39eda9723a628f75eaf7a/pandas_ta/volatility/donchian.py#L6) - so your channels are most likely wrong / not what you'd expect.

---

the problem though: Your parameters in the second segment are reversed - pandas_ta always assigns 'xxx_{lower}_{upper}'. (https://github.com/twopirllc/pandas-ta/blob/2a24fdc1b69110332db39eda9723a628f75eaf7a/pandas_ta/volatility/donchian.py#L42-L50)

So while you do calculate something - the actual key that would be present is DCL_41_99 (instead of `DCL_99_41`) - as the dynamic part (`val_X`) in the second iteration is "lower" - not "upper" (so you should be using `donchian_df_X[f"DCL_{val_X}_{dc_upper_len}"]` instead).

**Comment by lovehedy24** [comment]
> First off, i don't think you use it right (you're passing in `'close'` twice - the function seems to expect high and low (https://github.com/twopirllc/pandas-ta/blob/2a24fdc1b69110332db39eda9723a628f75eaf7a/pandas_ta/volatility/donchian.py#L6) - so your channels are most likely wrong / not what you'd expect.
> 
> the problem though: Your parameters in the second segment are reversed - pandas_ta always assigns 'xxx_{lower}_{upper}'. (https://github.com/twopirllc/pandas-ta/blob/2a24fdc1b69110332db39eda9723a628f75eaf7a/pandas_ta/volatility/donchian.py#L42-L50)
> 
> So while you do calculate something - the actual key that would be present is DCL_41_99 (instead of `DCL_99_41`) - as the dynamic part (`val_X`) in the second iteration is "lower" - not "upper" (so you should be using `donchian_df_X[f"DCL_{val_X}_{dc_upper_len}"]` instead).

Thank you for your reply, I will try again

**Comment by lovehedy24** [comment]
Thanks your help
it's my code
https://github.com/lovehedy24/TRADING/blob/main/Donchian.py

use command 
freqtrade hyperopt -s Donchian_Opt_MY -p ETH/USDT --hyperopt-loss SharpeHyperOptLoss  -e 1000 -j 16 --spaces buy sell

can optimization 
but have two question
1.warnings.warn("The objective has been evaluated " 
2. no sell exit !!!

**Comment by xmatthias** [comment]
You may want to use the new strategy interface for new strategies. 
While not officially deprecated yet, you can assume that prior versions of the strategy will stop to work at some point - so using the latest version is always recommended.

You're using some mixed form (methods from the new version - most other things from the old version) - which can become a dangerous mix.

You can find details in the [migration guide](https://www.freqtrade.io/en/stable/strategy_migration/).
Simply looking for "deprecated" messages in the startup logs will also help.

>  1.warnings.warn("The objective has been evaluated "

your space contains 55 + 55 - 110 values.
so in theory - after 110 epochs your space is exhausted. In reality - it'll take a bit longer as hyperopt is using bayesian search - but you'll still not have new values for 1000 epochs with the selected spaces.

> 2

it's unclear what you mean - you use no stoploss and no ROI - so you solely rely on exit_signal (which i'd recommend to explicitly enable via `use_exit_signal=True`).

**Comment by lovehedy24** [comment]
> 您可能希望將新策略界面用於新策略。 雖然尚未正式棄用，但您可以假設該策略的先前版本將在某個時候停止工作 - 因此始終建議使用最新版本。
> 
> 您正在使用一些混合形式（新版本中的方法 - 舊版本中的大多數其他東西） - 這可能會成為危險的組合。
> 
> 您可以在[遷移指南](https://www.freqtrade.io/en/stable/strategy_migration/)中找到詳細信息。 只需在啟動日誌中查找“已棄用”消息也會有所幫助。
> 
> > 1.warnings.warn("目標已評估"
> 
> 您的空間包含 55 + 55 - 110 個值。 所以理論上 - 在 110 個 epoch 之後，你的空間已經耗盡。實際上 - 由於 hyperopt 使用貝葉斯搜索，它會花費更長的時間 - 但您仍然沒有選擇空間的 1000 個 epoch 的新值。
> 
> > 2
> 
> 不清楚你的意思是什麼——你沒有使用止損和投資回報率——所以你完全依賴 exit_signal （我建議明確啟用 via `use_exit_signal=True`）。

thanks for answer
