### ISSUE TITLE
Strategy Hyperopt question(donchian CH)

### ISSUE THREAD

**Issue by lovehedy24** [freqtrade/freqtrade#7002]
## Describe your environment

  * Operating system:Ubuntu 20.04.4 LTS
  * Python Version: Python 3.9.9
  * CCXT version: ccxt==1.80.61
  * Freqtrade Version: freqtrade 2022.4.1Freqtrade running in docker)
  
## Your question
MY CODE:
https://github.com/lovehedy24/TRADING/blob/main/DD.py

thanks for your previous answer
I changed my strategy to the new version
But there are still some problems with optimization

Trades  Number =1 or <10
why?

**Comment by xmatthias** [comment]
Every scenario of running a strategy can be slightly different, so without context, your question does not make sense.

Please describe what you see / mean a bit more in detail, maybe / ideally with logs.

**Comment by lovehedy24** [comment]
> 運行策略的每個場景都可能略有不同，因此如果沒有上下文，您的問題就沒有意義。
> 
> 請更詳細地描述您所看到的/意思，也許/理想情況下使用日誌。
thanks for your reply
LOG in github
https://github.com/lovehedy24/TRADING/blob/main/LOG.txt
I mean my optimization strategy
optimization  Trades Number <10
Is the strategy wrong?

**Comment by xmatthias** [comment]
You use only one pair, so the maximum parallel trade count can never be greater than 1 (no more than one trade per pair at a time).

You get few trades, but that's because of the strategy / signal, which seems to trigger rarely.

**Comment by lovehedy24** [comment]
> You use only one pair, so the maximum parallel trade count can never be greater than 1 (no more than one trade per pair at a time).
> 
> You get few trades, but that's because of the strategy / signal, which seems to trigger rarely.
