### ISSUE TITLE
How do I get funding rates in my strategy?

### ISSUE THREAD

**Issue by redrabbit007** [freqtrade/freqtrade#7015]
I'm doing a crypto futures strategy and would like to use funding rates in this strategy. How would I access the funding rates for my pairs?

**Comment by xmatthias** [comment]
You can specify the candle type as part of getting [informative pairs](https://www.freqtrade.io/en/latest/strategy-customization/#informative-pairs) (the collapsed box at the bottom).
This also works for the decorator via the candletype argument.

The biggest limitation here is that fetching funding rates is only possible if you're trading futures (but you can't get spot rates there) - so the candle type must remain within the same trading type).

**Comment by redrabbit007** [comment]
Thanks, I'm getting closer, but I think there's something I'm not quite understanding yet. With the informative decorator and the futures candle_type, should that add the funding rate to the dataframe?

```
@informative('15m', candle_type="futures")
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
    print(dataframe.to_string())
```

```
                         date                    open     high      low     close      volume

0   2022-05-31 16:30:00+00:00  0.9881  0.9940  0.9831  0.9905   510313.0
...

                         date    open    high     low   close     volume                  date_15m  open_15m  high_15m  low_15m  close_15m  volume_15m

0   2022-05-31 16:30:00+00:00  0.9881  0.9940  0.9831  0.9905   510313.0 2022-05-31 16:30:00+00:00    0.9881    0.9940   0.9831     0.9905    510313.0
...
```

**Comment by xmatthias** [comment]
Futures is just the regular candle you get when you use futures data.
What you're looking for is `funding_rate`, which should have the funding rate in open (iirc).

**Comment by redrabbit007** [comment]
Got it, thank you. How do I download funding rate data for backtesting?

``2022-06-27 20:16:18,557 - freqtrade.data.history.idatahandler - WARNING - No history for 1INCH/USDT, funding_rate, 15m found. Use `freqtrade download-data` to download the data``

Edit: Hmm, I ran it in dry run mode, instead of backtesting and I'm still missing the funding rates, or maybe I'm trying to access it the wrong way.

```
@informative('15m', candle_type="funding_rate")
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
    print(dataframe.to_string())
```

```
                         date    open    high     low   close      volume                  date_15m  open_15m  high_15m  low_15m  close_15m  volume_15m

0   2022-06-17 12:45:00+00:00  0.5852  0.5898  0.5842  0.5868    675267.0 2022-06-17 12:45:00+00:00  0.000000       0.0      0.0        0.0         0.0
...
```

**Comment by xmatthias** [comment]
Funding rates are downloaded when downloading futures data for the required timeframe (usually 4 or 8 hours, depending on the exchange).

You currently cant download these explicitly.

In your dry, it would be the open_15m. Funding rates are quite small numbers, so pandas will not show values which start with  more than 6 or 8 zeros.
