### ISSUE TITLE
place buy order if price is above certain value

### ISSUE THREAD

**Issue by bartek666666** [freqtrade/freqtrade#7026]
## Your question

Is it possibile to place buy order after current price gets higher than e.g. previous open? 

Example 1 - we do not place buy order after entry signal (gren arrow) because price is lower than previous open (yellow line)
![qqq](https://user-images.githubusercontent.com/25506118/176876474-c58b8486-ca4e-4fc9-ad44-8bafb9c11358.png)
 Example 2 - we place buy order after entry signal (gren arrow) when current price hits previous open (yellow line)
![qqq2](https://user-images.githubusercontent.com/25506118/176877292-510c060f-50f2-4c2b-93f8-8bbec7d9efdb.png)

**Comment by xmatthias** [comment]
You can use the [confirm entry](https://www.freqtrade.io/en/stable/strategy-callbacks/#trade-entry-buy-order-confirmation) callback to prevent entries you dont like. It may be a bit verbose in the logs if the signal is repeatedly rejected.

Alternatively you can use the dataprovider to get the current [orderbook](https://www.freqtrade.io/en/stable/strategy-customization/#orderbookpair-maximum) and use that as part of your signal.

You will however need to implement some backtesting alternative for this, as orderbook is not available during backtesting.

**Comment by bartek666666** [comment]
confirm entry seems to do the trick

    def confirm_trade_entry(self, pair: str, order_type: str, amount: float, rate: float, time_in_force: str, current_time: datetime, side: str, **kwargs) -> bool:

        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)   
   
        if rate < dataframe['open'].iat[-1]:
            return False

        return True
