### ISSUE TITLE
Issue with migration on PG

### ISSUE THREAD

**Issue by botzill** [freqtrade/freqtrade#7038]
## Describe your environment

  * Operating system: Mac OS
  * Python Version:  3.10.4 (`python -V`)
  * CCXT version: 1.89.96(`pip freeze | grep ccxt`)
  * Freqtrade Version: develop (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Describe the problem:

Upgrading to the latest version gives this error on PG

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) operator does not exist: boolean = integer
LINE 4:                 where ft_is_open = 1 and (ft_trade_id, order...
                                         ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```
I guess is related to #6794.

Maybe there is a way to set up a CI for PG and make sure it works there as well.

**Comment by xmatthias** [comment]
Freqtrade's main sql engine is sqlite (for it's simplicity from a user perspective). While we aim to maintain compatibility with Postgres/mysql - that cannot be guaranteed at this point.

Feel free to submit a PR running specific tests (the ones with migrations, most likely) / CI against postgres/mysql if you have some knowledge about this - i myself have no experience with running pytest against postgres in github actions (it should be selective, only running in ci there to not require a local Postgres to run tests), but i'd be more than happy to have that if it's not adding too much time to CI, or too much complexity to tests.
