### ISSUE TITLE
I have tested this, and seems that the "SampleStrategy" doesn't work with "plot-dataframe"

### ISSUE THREAD

**Issue by n8an** [freqtrade/freqtrade#7040]
Latest image of freqtrade for docker.
On creation using the "quick start with docker" example commands.
"SampleStrategy" is created.
Loading data is fine.
Backtesting with "SampleStrategy" works too.
But "plot-dataframe" results for this strategy always gives an error.

BUUUT!

Using "new-strategy --strategy AwesomeStrategy"
And using it with "plot-dataframe" suddenly works.

Seems like the prebuilt Sample strategy is faulty and differs from "new-strategy" generator result.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Please provide logs / the error you're experiencing.
Otherwise it's just a tale, really.

**Comment by n8an** [comment]
... I have provided all the steps required. It's a basic error to test for yourself and see it immediately.
anyways...

1 - curl https://raw.githubusercontent.com/freqtrade/freqtrade/stable/docker-compose.yml -o docker-compose.yml
2 - docker-compose pull
3 - docker-compose run --rm freqtrade create-userdir --userdir user_data
4 - docker-compose run --rm freqtrade new-config --config user_data/config.json

**Pulling freqtrade ... done
Creating ft_userdata_freqtrade_run ... done
Creating ft_userdata_freqtrade_run ... done
? Do you want to enable Dry-run (simulated trades)? Yes
? Please insert your stake currency: USDT
? Please insert your stake amount (Number or 'unlimited'): 100
? Please insert max_open_trades (Integer or -1 for unlimited open trades): 3
? Time Have the strategy define timeframe.
? Please insert your display Currency (for reporting): USD
? Select exchange binance
? Do you want to trade Perpetual Swaps (perpetual futures)? No
? Do you want to enable Telegram? No
? Do you want to enable the Rest API (includes FreqUI)? Yes
? Insert Api server Listen Address (0.0.0.0 for docker, otherwise best left untouched) 0.0.0.0
? Insert api-server username freqtrader
? Insert api-server password 1111
2022-07-04 07:58:14,873 - freqtrade.commands.build_config_commands - INFO - Writing config to `user_data/config.json`.
2022-07-04 07:58:14,873 - freqtrade.commands.build_config_commands - INFO - Please make sure to check the configuration contents and adjust settings to your needs.**

5 - docker-compose run --rm freqtrade download-data --pairs btc/usdt ETH/BTC eth/usdt xmr/btc xmr/usdt ftm/usdt ftm/btc --exchange binance -t 1m
6 - docker-compose run --rm freqtrade backtesting -v --strategy SampleStrategy
7 - docker-compose run --rm freqtrade plot-dataframe --strategy SampleStrategy --export-filename user_data/backtest_results/backtest-result.json

**Creating ft_userdata_freqtrade_run ... done
2022-07-04 09:49:39,998 - freqtrade.configuration.configuration - INFO - Using config: user_data/config.json ...
2022-07-04 09:49:40,003 - freqtrade.loggers - INFO - Verbosity set to 0
2022-07-04 09:49:40,079 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2022-07-04 09:49:40,082 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2022-07-04 09:49:40,082 - freqtrade.configuration.configuration - INFO - Storing backtest results to user_data/backtest_results/backtest-result.json ...
2022-07-04 09:49:40,083 - freqtrade.configuration.configuration - INFO - Limiting plot to: 750
2022-07-04 09:49:40,083 - freqtrade.configuration.configuration - INFO - Using trades from: file
2022-07-04 09:49:40,083 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-07-04 09:49:40,113 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2022-07-04 09:49:40,113 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-07-04 09:49:40,113 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-07-04 09:49:40,171 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SampleStrategy from '/freqtrade/user_data/strategies/sample_strategy.py'...
2022-07-04 09:49:40,171 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/plot_commands.py", line 24, in start_plot_dataframe
    load_and_plot_trades(config)
  File "/freqtrade/freqtrade/plot/plotting.py", line 604, in load_and_plot_trades
    strategy = StrategyResolver.load_strategy(config)
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 44, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 201, in _load_strategy
    strategy = StrategyResolver._load_object(paths=abs_paths,
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 127, in _load_object
    return module(kwargs)
TypeError: Can't instantiate abstract class SampleStrategy with abstract methods populate_buy_trend, populate_sell_trend
ERROR: 1**

BUT now if we do the following.

8 - docker-compose run --rm freqtrade new-strategy --strategy AwesomeStrategy
9 - docker-compose run --rm freqtrade backtesting --config user_data/config.json --strategy AwesomeStrategy -i 1m
10 - docker-compose run --rm freqtrade plot-dataframe --strategy AwesomeStrategy --export-filename user_data/backtest_results/backtest-result.json -i 1m

NOW! Everything works perfectly fine.

Which leads me to believe that the "SampleStrategy" generated on creation, for some reason doesn't work with "Plotting", UNLIKE the "AwesomeStrategy" generated by the "NEW-STRATEGY" generator, making it work just fine out of the box with plot.

Hope that THIS time it's not just a "tale" for you.
And if not. I'm damn well fine with dumping the whole log on you and waiting for you to figure everything out without my explanations, leads and guesses.

**Comment by xmatthias** [comment]
> And if not. I'm damn well fine with dumping the whole log on you and waiting for you to figure everything out without my explanations, leads and guesses.

There's no reason to become offensive while expecting support from an open source project, where people try to help in their free time.

---

> ... I have provided all the steps required. It's a basic error to test for yourself and see it immediately.
> anyways...

i did and it works for me (with uptodate versions)- which is why i asked for more information.

`freqtrade create-userdir --userdir user_data` will only write a new file when there was no file existing previously.

Your steps are however incomplete - as the standard image (without modification of the docker-compose file) does not include plot modules - but ":stable_plot" does.

Assuming you switched to that version once you ran the "plot" functionalities - i have to assume that you didn't pull a new ":stable_plot" image. The error you get is only possible with a version prior to 2022.4 - if the strategy was taken/written from a newer version.

So what i think happened:

* You pulled a new stable image
* you created the userdir with that
* you updated the image to stable_plot (but didn't pull this image again)
* now it fails as the version is <2022.4
* you use `new-strategy` with this version - which now obviously works as it's writing the image with the OLD strategy interface (it's now using the :stable_plot image).


The only real fix is to do a "docker-compose pull" after swapping the image "stable" with "stable_plot" - which will then have plotting work just fine (i just tested this again - with the "stable" image) - and there is no issue with the sample strategy.

**Comment by n8an** [comment]
Hmmmm... DockerCompose has a commented out "image: freqtradeorg/freqtrade:develop_plot" so I just uncommented it and did all the steps described above.
Plus I have checked it just now, the AwesomeStrategy(created from new-strategy) is be default different from the SampleStrategy.
I've noticed they use different interface-version parameters for some reason.
I have done all this from clean slate, deleting all previous folders and files created.
I do not understand why would the built in SampleStrategy have a different interface_version to the example strategy created by new-strategy function.

**Comment by xmatthias** [comment]
the "sample" strategy generated from uptodate images (assuming no prior file was present) is this:
https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/templates/sample_strategy.py - which is the new version of the strategy interface - which will however fail to load on older freqtrade versions.

I suspect that the "awesomeStrategy" is using the V2 interface - which confirms my suspicion of usage of different images.

you can also check the version of freqtrade (in the container) by running `docker-compose run --rm freqtrade -V`.

**Comment by n8an** [comment]
Well, it's the newest one.
PS D:\FREQTRADE\ft_userdata> docker-compose run --rm freqtrade -V
Creating ft_userdata_freqtrade_run ... done
freqtrade docker-301b2e8a

You said something about a ":stable_plot", maybe it's because of me using ":develop_plot"??

**Comment by xmatthias** [comment]
`freqtrade docker-301b2e8a` is a version from january - so you're using an outdated image (as explained above already).

You can verify this by searching for this commit in this repository 301b2e8a - clicking on the link will show you a commit from january 18th - which means that your image is from january 18th.

if you're using develop_plot or stable_plot does not really matter as long as the versions are are decently uptodate - which in your case - they are not.

You can however easily resolve this by running `docker-compose pull` again - which will pull the latest image - either develop_plot or stable_plot (whichever version you've got in your compose file).

**Comment by n8an** [comment]
But how can this happen? I copied all the commands from the "Quick Start with Docker" page.
And did a "Pull" just an hour ago.
Could you please show a reliable way of loading everything from a clean machine with docker?

**Comment by xmatthias** [comment]
it's no longer possible to pull a old develop (or develop_plot) version from dockerhub (intentionally).

this means, you've had an old image on your machine (which means it's not a clean machine) and did the "docker-compose pull" before changing the image to the "_plot" version.

on a clean machine (with no docker image available) this will not happen, as docker-compose will do an implicit pull once you run the image for the first time.
The instructions on the page are reliable **on a clean machine**. 
On machines with months-old images, you may need to run a "docker-compose pull" after changing the image to "_plot". 
Your "pull" was before changing to the "plot" version - which resulted in the behavior you're seeing.

You can list the images on your system with `docker images` - and remove old ones with `docker rmi <imageid>`.
I'd suggest to remove all images related to freqtrade and then follow the instructions again - you'll see that everything will be working just fine.

**Comment by n8an** [comment]
This is exactly what I did today two times just to make sure. Deleting everything beforehand.
I'm not getting how could I have a old version of freqtrade if I deleted my compose file, and grabbed it from git?

Download the docker-compose file from the repository
curl https://raw.githubusercontent.com/freqtrade/freqtrade/stable/docker-compose.yml -o docker-compose.yml

Pull the freqtrade image
docker-compose pull

Create user directory structure
docker-compose run --rm freqtrade create-userdir --userdir user_data

Create configuration - Requires answering interactive questions
docker-compose run --rm freqtrade new-config --config user_data/config.json

**Comment by xmatthias** [comment]
this will be correct IF you edit the compose file to the _plot tag before the docker-compose pull.

If you do that after this point - it may use an already existing docker image.

if you just run the following 3 commands (without any modification to files) you'll get an uptodate version

```
curl https://raw.githubusercontent.com/freqtrade/freqtrade/stable/docker-compose.yml -o docker-compose.yml

docker-compose pull
docker-compose run --rm freqtrade  -V

```

**Comment by n8an** [comment]
I have done as you said. Seems to work now.
I'm sorry for my misunderstanding in the beginning.
I thought I have found a bug, and figured out a general direction where it was coming from.
Thanks for the help!
