### ISSUE TITLE
Building wheel for TA-Lib (setup.py) ... error

### ISSUE THREAD

**Issue by atanu2531** [freqtrade/freqtrade#7044]
## Describe your environment

  * Operating system: _windows10___
  * Python Version: 3.10_____ (`python -V`)
  * CCXT version: _____  pip (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ current version (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
Building wheel for TA-Lib (setup.py) ... error  -  unable to install TA-Lib
*Explain the problem you have encountered*
pip install TA-Lib
Collecting TA-Lib
  Using cached TA-Lib-0.4.24.tar.gz (269 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in c:\python310\lib\site-packages (from TA-Lib) (1.22.3)
Building wheels for collected packages: TA-Lib
  Building wheel for TA-Lib (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [519 lines of output]
### Steps to reproduce:

  1. _____ run pip install TA-Lib
  2. _____
  3. _____
  
### Observed Results:

  * What happened? install failed 
  * What did you expect to happen? install success 

### Relevant code exceptions or logs
pip install TA-Lib
Collecting TA-Lib
  Using cached TA-Lib-0.4.24.tar.gz (269 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in c:\python310\lib\site-packages (from TA-Lib) (1.22.3)
Building wheels for collected packages: TA-Lib
  Building wheel for TA-Lib (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [519 lines of output]
Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
To install ta-lib on windows (assuming this is native windows, not WSL) - please follow the [instructions for windows](https://www.freqtrade.io/en/stable/windows_installation/#2-install-ta-lib) related to this.
I'd suggest to install ta-lib first by using the wheels provided in the build _helpers folder

Simply running the setup will only work if you have all necessary compilers available - which is a package of ~4Gb (documentation on what exactly is needed will be on the same page).

**Comment by navillanueva** [comment]
Hello,

Im currently running the same set up but get this error:

ERROR: Could not build wheels for TA-lib, which is required to install pyproject.toml-based projects

I have already installed pyproject.toml but still can´t build the wheel. Any ideas as to why?

**Comment by xmatthias** [comment]
ta-lib installation does not work purely on python dependencies at the moment - but requires special steps.

if you're not using the setup script or docker, please follow the [installation guide](https://www.freqtrade.io/en/latest/installation/#install-ta-lib) on how to install ta-lib.
