### ISSUE TITLE
EXE file

### ISSUE THREAD

**Issue by Abdulhadi77** [freqtrade/freqtrade#7046]
Hi,

Could you please support an exe file to install it on windows?

**Comment by xmatthias** [comment]
Freqtrade's main mode of operation is a command line tool. 
While it also offers a UI, full control over it is not possible for all instances.

To use it fully / properly, you will therefore need to familiarize yourself with the command line anyway.

As such - it is aligned to also have the installation via command line.

Installing on Windows is really no problem anymore if the [windows installation guide](https://www.freqtrade.io/en/stable/windows_installation/) is followed properly - and the provided ta-lib wheel file is used.

The only prerequisites are an installed git (or github client) - as well as python (which can be installed from the windows store).

A installer will almost in all cases also clutter the system with other stuff (registry entries, uninstall entires, ...) - which are auto-generated by installation modules - which are however unnecessary for freqtrade (you can just delete the directory and it's gone - assuming everything is installed and used from one directory).

It would also need to take certain assumptions about the system (like - installed python version) - or provide it's own python version) - both of which are not great options in my opinion.

As such - i don't currently see any benefit to having an exe installer.
