### ISSUE TITLE
Send leverage to custom_stake_amount() callback

### ISSUE THREAD

**Issue by medenlin** [freqtrade/freqtrade#7047]
## Describe your environment
(if applicable)

  * Operating system: Docker
  * Python Version: Docker (`python -V`)
  * CCXT version: Docker (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.6 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

What about to send setted in leverage() callback leverage value to custom_stake_amount() callback? 
I think it would be useful in some cases.

**Comment by xmatthias** [comment]
You're right, that's kindof missing but important for this callback.

it's available in develop (give ci about an hour if you're using docker).
