### ISSUE TITLE
Add take profit order

### ISSUE THREAD

**Issue by fridary** [freqtrade/freqtrade#7049]
I have strategies where roi is 0.2-0.3%. I noticed sometimes price is reached exactly profit value, but freqtrade does not exit position, because then price immediately goes down, although `process_throttle_secs` is 5. Can we add take profit order just like custom stop loss? The best thing will be if we choose before what percent we can send take profit order. For example, I set roi 0.3% and `before_percent=0.1%`. So, when profit is up to 0.2%, freqtrade will create take profit order to catch roi fast.
Or, at least, make `order_types = {'takeprofit_on_exchange': True}` for binance as stoploss.

**Comment by xmatthias** [comment]
i don't think you'll have much success with freqtrade if 0.1% moves decide about your strategy's destiny. order placement, network latency, ... play an important role in such tight windows.

>  although process_throttle_secs is 5

5s is not 1s - so everything within this 5s window will be "not seen".
Also lowering this won't guarantee it'll see all 0.1% swings - not if you have more than 1 trade open - as then it'll need to check them one after the other (for ratelimit reasons).

That said - a "proper" take profit order has the problem that it'll block your assets. 
Assuming you place your "take profit" order at 0.3% - but it barely doesn't reach that, and instead goes the other direction (to your stoploss or beyond).
Your asset is now blocked - meaning to place a (now losing) sell order, you'll be slower (need to cancel / reset the selling order). 

we aim to protect users assets first (so stoploss will take priority over take-profit) - therefore this is not an apporach we'll be taking.

While OCO orders can be an option for this - that's currently not something we support.

In theory, i guess you can use custom order pricing (with tight timeouts to avoid sell problems if it isn't reached) to set the sell rate 0.1% above suggested sell rate (and therefore set your ROI 0.1% lower) to get the desired effect.

I still think that with ranges of 0.1% - you'll not have much luck on most pairs - as they move 0.5% (or often more) with a single trade (on the trade book) - therefore low profit scalping (which i suspect you're doing) is probably not going to work properly - at least not at this point.
