### ISSUE TITLE
Exchange "binance"  will not work with Freqtrade. Reason: missing: loadMarkets

### ISSUE THREAD

**Issue by esf0** [freqtrade/freqtrade#7050]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.10.0
  * CCXT version: 1.90.31
  * Freqtrade Version: 2022.6 
  
## Describe the problem:

Hi!
I installed freqtrade with conda.
After creation the default config file  
```
freqtrade new-config --config config.json
? Do you want to enable Dry-run (simulated trades)? Yes
? Please insert your stake currency: USDT
? Please insert your stake amount (Number or 'unlimited'): 1000
? Please insert max_open_trades (Integer or -1 for unlimited open trades): 10
? Time Have the strategy define timeframe.
? Please insert your display Currency (for reporting): USD
? Select exchange binance
? Do you want to trade Perpetual Swaps (perpetual futures)? No
? Do you want to enable Telegram? No
? Do you want to enable the Rest API (includes FreqUI)? No
```
and adding a simple pair list  
```
"pair_whitelist": [
            "BTC/USDT",
            "ETH/USDT"
        ],
```
I got the following error:  
```
freqtrade download-data --config config.json --days 9 -t 5m
2022-07-07 20:24:53,947 - freqtrade.configuration.load_config - INFO - Using config: config.json ...
2022-07-07 20:24:53,947 - freqtrade.loggers - INFO - Verbosity set to 0
2022-07-07 20:24:53,948 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/esf0/freqtrade/user_data ...
2022-07-07 20:24:53,948 - freqtrade.configuration.configuration - INFO - Using data directory: /home/esf0/freqtrade/user_data/data/binance ...
2022-07-07 20:24:53,948 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['5m']
2022-07-07 20:24:53,948 - freqtrade.configuration.configuration - INFO - Detected --days: 9
2022-07-07 20:24:53,948 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-07-07 20:24:53,955 - freqtrade - ERROR - Exchange "binance"  will not work with Freqtrade. Reason: missing: loadMarkets
```

I tried a different pair list or running the trade, but I had the same error.

### Steps to reproduce:

```
git clone https://github.com/freqtrade/freqtrade.git
cd freqtrade/
conda env create -n ft -f environment.yml
conda activate ft
git checkout stable
python3 -m pip install -e .
freqtrade create-userdir --userdir user_data
freqtrade new-config --config config.json
freqtrade download-data --config config.json --days 9 -t 5m
```

I tried to use an example config for binance, but the error is the same.

Any ideas about what it can be?

**Comment by Hungryarie** [comment]
Same error here!
Operating system: Ubuntu 20.04 LTS (via WSL2)
Python Version: 3.8.10
CCXT version: 1.90.30
Freqtrade Version: 2022.6 (installed via PiPy)

When digging into the problem I tried commenting out EXCHANGE_HAS_REQUIRED.loadMarkets to see where it goes. The next error gives me: 
```
freqtrade.exceptions.OperationalException: Exchange Binance does not support market orders.
```
which makes me believe something is changed on ccxt??

**Comment by xmatthias** [comment]
it's correct, something changed in ccxt - once we support that ccxt version - freqtrade will work as expected.

In basically all install instructions, we use `pip install -r requirements.txt` to install dependencies, which pins dependencies to supported versions.
not doing that can obviously lead to temporary non-supported states.

I've not found the precise code you've ran (with missing `requirements.txt`) in our docs - so i guess it's a "based on experience" install - it's however wrong to not use requirements. other dependencies could break, too - and we'll only "max-pin" versions if we know of incompatibilities which will persist over a longer period of time.

Now unfortunately, conda environment files can not be automatically updated (https://github.com/dependabot/dependabot-core/issues/2227) - which means we can't hard-pin dependencies there without a huge manual effort.

**Comment by Hungryarie** [comment]
Thanks Matthias
```pip install -r requirements.txt ``` worked for me

**Comment by esf0** [comment]
Thank you, Matthias!
Yeah, I used installation instruction for [conda](https://www.freqtrade.io/en/stable/installation/#installation-with-conda). 
`pip install -r requirements.txt` worked.

**Comment by AssetOverflow** [comment]
pip3 install -r  requirements.txt
 did not work for me (MACOS Monterey M1 Pro chip) (was running stable version) -- doesn't seem so stable.
did a git pull to update and it now switches over to "Binance" and states "freqtrade.exchange.binance  INFO" when downloading data... is this binanceus data or all-other-country Binance?

can't have reliable backtesting and optimization with incorrect data :(

**Comment by stash86** [comment]
Use docker. Conda isn't too reliable

**Comment by AssetOverflow** [comment]
not using conda. using local setup

**Comment by xmatthias** [comment]
@AssetOverflow You'll need to have dependencies and freqtrade aligned (so the version needs to match pinned dependencies).
If that's not the case - there may be incompatibilities.

The best approach is to follow the [update docs](https://www.freqtrade.io/en/latest/updating/) when updating - to ensure dependencies are kept uptodate.
