### ISSUE TITLE
Can't download funding rate 4h for OKEX (future market)

### ISSUE THREAD

**Issue by popperwin** [freqtrade/freqtrade#7053]
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.8.8 (`python -V`)
  * CCXT version: 1.89.14 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2022.6 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Describe the problem:

Hello,
I cannot download funding rate for 4h timeframe for okex.
I have this error when downloading

```_async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair BTC/USDT due to BadRequest. Message: okex {"code":"51000","data":[],"msg":"Parameter instId  error"}". Retrying still for 4 times. ```

### Steps to reproduce:

  1. Set up 
  ```
  "trading_mode":"future",
  "margin_mode": "isolated",
  ``` 
in the config.
  2. Use this command to download data   ```freqtrade download-data --exchange okex --pairs BTC/USDT -t 4h --timerange 20220610- -c config.json```

### Observed Results:

  * What happened?
Downloading funding rate fails; so impossible to do any backtest.
  * What did you expect to happen?
Downloading funding rate to not fail.

**Comment by xmatthias** [comment]
`BTC/USDT` is not a futures pair (so there's no funding rates for it) - but `BTC/USDT:USDT` is.

I've just attempted this with the correct pairname (an actual futures pair, according to the CCXT naming convention) - and it's working just fine.

**Comment by popperwin** [comment]
You're right; thanks for your help :+1:
