### ISSUE TITLE
Make freqtrade using more cpu cores

### ISSUE THREAD

**Issue by vaha6** [freqtrade/freqtrade#7069]
## Describe your environment
Ubuntu 21.02 live server
  * Operating system: 
  * Python Version: 3 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
hello friends. kindly i would like to know how can i make freqtrade bot use more resources while backtesting. by saying this I mean the freqtrade involves only one core cpu and now that I have upgraded my hardware system and do not have any resource limit, thats making me slow. so where and how can I make changes in freqtrade to use more resource while doing backtest. (instead of one core 100%, using more cores with lower load balance)
*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
The way freqtrade backtesting works makes it near impossible to parallelize efficiently (without having a "sync" step every other line), which will make the endresult slower than the 1 core version.
it would also implicitly break hyperopt - so this is not a route we will pursue for now.

Maybe you're looking for [hyperopt](https://www.freqtrade.io/en/latest/hyperopt/) - which will use all cores of a system (given enough memory is available).
