### ISSUE TITLE
Add openpyxl library to the official image so we can use dataframe.to_excel() for Excel 2010 xlsx files

### ISSUE THREAD

**Issue by dobremha** [freqtrade/freqtrade#7071]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

https://openpyxl.readthedocs.io/en/stable/

*Explain the enhancement you would like*

**Comment by xmatthias** [comment]
Well no.
We will not add random dependencies to official images to satisfy some edgecase need.

You can however build your own image based on the official images by following the [Custom docker file documentation](https://www.freqtrade.io/en/stable/docker_quickstart/#additional-dependencies-with-docker-compose), adding any dependency your strategy needs.
