### ISSUE TITLE
Opened trade closed due to unfilledtimeout

### ISSUE THREAD

**Issue by mohsenjavidpanah** [freqtrade/freqtrade#7074]
**Situaltion**:

  * Operating system: Ubuntu 20.04
  * Python Version: 3.8.10
  * CCXT version: 1.89.14
  * Freqtrade Version: develop-48ff2eedc
  
**Problem**:

When my strategy buy signal fire in dry-run mode, a trade create and shown in "Open Trades" section by 0.0% profit, But when market is bullish this percent don't change and after some seconds this trade disappear from "Open Trades".

Attention: If Market not grow up immediately this problem not occurred.

**Comment by xmatthias** [comment]
Without logs - everything below will be educated guessing.

What you're seeing is most likely unfilled orders (will have log messages saying so) - which can happen with limit orders.
You can either change timeouts ([`unfilledtimeout`](https://www.freqtrade.io/en/stable/configuration/#configuration-parameters)), use market orders or you can adjust your [pricing](https://www.freqtrade.io/en/stable/configuration/#prices-used-for-orders).

**Comment by mohsenjavidpanah** [comment]
This image show multiple unfilled orders:

![f2](https://user-images.githubusercontent.com/28291175/178636222-f52919af-3f72-46c0-927a-d0fd9818aafe.png)

**Comment by xmatthias** [comment]
you might wanna consider disabling http logging - it clutters the log very much.
We also recommend to not expose the API directly over the internet without further protection (firewall, ...) - but instead use either SSH Tunnels, or a VPN / Wireguard setup to connect to the bot in private.


Unfortunately, the provided log is useless as it has no trades (not even attempted ones).

**Comment by mohsenjavidpanah** [comment]
Okay, related logs in my previous comment removed

**Comment by xmatthias** [comment]
if you got logs from times around trade entries  we can confirm it's the timeouts (although from the description, i'm 99% sure that's the case).

best read through the documentation linked above and reconfigure the bot according to your preferences to get more fills.
