### ISSUE TITLE
Stop Loss of low value token

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#7077]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.5 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I case of stop losses with a high amount of loosing % I often see, that the token is of a very low value, like for example DOS with a close rate of 0.0006848, which closes at -43%, while hardly no other coin reaches this level of loss. It seems not to be strategy-specific, if I'm not wrong. PrecisionFilter is active. Of course it is still always possible, that this result is simply related to the strategy and config. Is it a known fact, that such events could possibly happen more often with very low valued coins, and is it a good idea to think about blacklisting them?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
this is kindof expected - and a property of these markets.
If you think about what a low-value token is - it's usually / often a very young project (not always but quite often). - which often have quite low trading volume.

This means implicitly that relatively low-volume orders (a few 10k$) can move the market by quite some.
This makes these markets susceptible to pump/dump schemes - as the market can easily be moved.
They often show high yields (i've seen a 1000+% in a day) - but also are high-risk - so you should obviously be aware of this.

If you should or should not trade these will heavily depend on the strategy - but i guess more often than not - strategies are not "really" designed for these - as they often are new projects - listed days or weeks ago - which (hope) to gain traction - and if they do, they'll spike up (often followed by a dump ...).

**Comment by myNextCoder** [comment]
A big thank you for this important information. I should have taken into account this little thing with big impact much earlier.

**Comment by xmatthias** [comment]
Well using a Trading bot doesn't replace using knowing at least some fundamentals about the pairs you're trading.
While the bot may take away the monitoring / entering/exiting - the pair selection is still a point that can greatly impact a strategy's performance - even though it's often overlooked.

**Comment by myNextCoder** [comment]
You are absolutely right. Is there a simple way, to eliminate coins below a certain price, or to check all coins below a certain price? If I do it manually on gate.io, it takes a very long time. Since I am not yet a Python programmer, it helps me, if you just paste me the line, which compares the price of the coin with a price. Of course, I set the level of the price by my own.

**Comment by stash86** [comment]
Or... you know, read the docs?

https://www.freqtrade.io/en/stable/includes/pairlists/#pricefilter

**Comment by myNextCoder** [comment]
Just too great. I thank you, very easy solution ;)
