### ISSUE TITLE
Freqtrade API access

### ISSUE THREAD

**Issue by lulu-angry** [freqtrade/freqtrade#7079]
## Describe your environment

  * Operating system: ____ Ubuntu (Last)
  * Python Version: _____ (Last)
  * CCXT version: _____ (Last)
  * Freqtrade Version: ____ (freqtrade develop-6f0721ae2)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hello there i have a problem about Freqtrade server API,
I try to develop and simply (HTML and JS) apps for manage my bot.

I'm learn about : https://www.freqtrade.io/en/stable/rest-api/
I firstly try to master the API server with Curl and done it successfuly,
Now is the problem i want actually to use GET with fetch() but the response is alwaws 401.
I try with the basic authentication method before bearer.

![Screenshot from 2022-07-13 17-48-15](https://user-images.githubusercontent.com/83360121/178776493-b76efa97-b422-43ae-936f-51becf05319e.png)

Here is my code : 

    function fetchAuth () {
      // (A) URL & CREDENTIALS
      var url = "http://127.0.0.1:8080/api/v1/performance"
      usr = "usr"
      psw = "psw"

      // (B) FETCH WITH HTTP AUTH
      fetch (url, {
        mode: 'no-cors',
        method: "GET",
        credentials: 'include',
        headers: {
          'Access-Control-Request-Method': 'GET',
          'Access-Control-Allow-Headers': 'Authorization',
          'Access-Control-Allow-Origin' : "*",
          'Access-Control-Allow-Credentials': 'true',
          'Accept': 'application/json',
          'Content-Type': 'application/json',
    	    'Authorization': 'Basic' + btoa(`${usr}:${psw}`)
        }
      })

I looking everywhere to understand why i always encount 401 but i can't found any solution.

**Comment by lulu-angry** [comment]
Here is my config file for CORS

  "api_server": {
    "enabled": true,
    "listen_ip_address": "0.0.0.0",
    "listen_port": 8080,
    "verbosity": "info",
    "jwt_secret_key": "somethingrandom",
    "CORS_origins": ["localhost:8080"],
    "username": "usr",
    "password": "psw"
  },

**Comment by xmatthias** [comment]
CORS errors will show up in the network tab, not in the console.

your configuration works fine only if your application is running on port 8080 - which it cannot as the bot is running there - so most likely, your configuration is wrong - or the bot cannot start as the port is already "occupied".

---


In general, i'd encourage you to look at [freqUI](https://github.com/freqtrade/frequi) - which does implement authentication in JS.
While we do provide the API - it's main purpose is to supply data to freqUI - as such, we do not actively support problems with alternative implementations.

although you're obviously free to start something from scratch - usually a more productive solution is to contribute what you think is missing to an existing solution. This will then also benefit the whole community - as everyone will get the (hopefully great) improvements you have in mind and find missing in the current UI.
