### ISSUE TITLE
Add a switch in hyperopt to compute indicators at each epoch instead of at the start

### ISSUE THREAD

**Issue by SpeedJack** [freqtrade/freqtrade#7080]
## Describe your environment

  * Operating system: Gentoo Linux 5.10.61
  * Python Version: 3.10.15
  * CCXT version: 1.89.14
  * Freqtrade Version: 2022.6

## Describe the enhancement

I've developed a strategy that makes use of some indicators (expecially MACD, which has 3 parameters: meaning there are 3 nested loops in `populate_indicators`) and informative pairs (with other indicators).

When I run hyperopt, it quickly wipes out my entire RAM + swap (16GB + 20GB) and forces Linux to kill freqtrade's processes. I can't even run it with `-j 1` for more than a bunch of pairs or too large timerange. Anyway, using `-j 1`, of course, slows down the process (balancing out the speedup that comes from precomputing all indicators before starting the first epoch). Moreover, I think that accessing a very large dataframe is probably (not verified - just an intuition) much more slower than accessing a small dataframe (at least for the principle of locality, I think): so creating a large dataframe in `populate_indicators` may slows down the entire hyperopt in complex strategies.

Actually, I've come to a workaround: compute indicators in `populate_entry/exit_trend` instead of in `populate_indicators` (I compute indicators 2 times: one for entry and one for exit, but just for the needed values instead of the entire ranges of values). This is the only way I can run my strategy. Memory consumption is negligible, and execution time seems to be lower (again: not verified numerically, it just seems faster to me - probably due to the reduced access time with a smaller dataframe and in the parallelization of the computation of indicators, since `populate_*_trend` are executed in parallel).

So, I would like to have a switch in the `hyperopt` command to make the call to `populate_indicators` at each epoch instead of computing all indicators at the start. At least, this allows to hyperopt more complex strategies that otherwise would consume too much memory (sometimes even with `-j 1`) or force the user to use only one core slowing down the entire process.

**Comment by xmatthias** [comment]
I'm not sure how you'd imagine this to work - but i think such a parameter would be quite misleading to users, as the strategy would also have to define the indicator differently (not as loop using `.range`, but using the "final" value).
As it'd be a simple "switch" - (which would however require quite some code-changes in the strategy, potentially) - it'd be a very dangerous premise - one which would most likely lead to very wrong / misleading results. (if you use `.value` without the switch - the written hyperopt results file may be different from the actually used parameters).


Moving indicators to the "populate_entry / exit" method is the correct approach for this in my opinion.

you should however be aware that this will lead to have the same indicator (with the same parameters) indicated multiple times. 
Hyperopt is using Bayesian search - so it's not guaranteed that the methods will only be called once with the same parameter (especially with several parameters it's very likely that MACD 14 is calculated several times, which could be avoided by using the default approach.

**Comment by SpeedJack** [comment]
> I'm not sure how you'd imagine this to work - but i think such a parameter would be quite misleading to users, as the strategy would also have to define the indicator differently (not as loop using `.range`, but using the "final" value).

Actually, I don't know much of the internals of freqtrade, but when the strategy is run in backtesting instead of hyperopt the `.range` property _acts like_ the `.value` property, giving only one value. So I think that the strategy implemented using `.range` can work both with the switch enabled or disabled making the `.range` property act like `.value` when the switch is enabled. Strategies should the be written always using `.range` in `populate_indicators` in order to support both modes of operation (this does not add work to the strategy developer, as he already has to keep in mind that `.range` may return a single value or a list of values, to support both hyperopt and backtesting).

> Moving indicators to the "populate_entry / exit" method is the correct approach for this in my opinion.

And it works, but since often the same indicators with same parameters are used in both the `entry` and the `exit` method, this causes the same computations 2 times: `populate_indicators` would be instead called just once before the calls to `populate_entry/exit_trend`.

> you should however be aware that this will lead to have the same indicator (with the same parameters) indicated multiple times.

Of course this is an advantage of the default approach, but it is sometimes unfeasible due to memory consumption. The switch would allow to implement a strategy, try the default preferred approach to hyperopt first (calculating indicators before start), then, if it consumes too much memory, just add the switch to the command to make the `populate_indicators` call at each epoch (making `.range` act like `.value`) **without** modifying anything in the strategy's code.

Recently I'm trying various different strategies: I start with a strategy with a small subset of indicators computed in `populate_indicators`. Then I try to figure out what goes wrong with the strategy analyzing its trades and I often add other indicators to the strategy. When there are too many indicators that make hyperopt run out of memory, I'm actually forced to rewrite strategy's code in the other way (and I often make some errors rewriting the code that then gives me wrong results).

**Comment by xmatthias** [comment]
> And it works, but since often the same indicators with same parameters are used in both the `entry` and the `exit` method, this causes the same computations 2 times: `populate_indicators` would be instead called just once before the calls to `populate_entry/exit_trend`.

if the parameter is the same, having it in `populate_entry` will be sufficient, and the indicator will also be available in `populate_exit_trend`.

the usage of `.range` is tied to the run mode (hyperopt or not). 
Changing the whole structure to allow both modes is most likely not an easy endeavor - and maintenance of such "double-feature" is usually quite cumbersome. As such - i'm not convinced if this brings the benefit you hope - not compared to the investment (time and future maintenance).

You're obviously free to submit a PR if you think this is a must, which i'll gladly review - but for the moment, i don't think this is something we'll be looking at short to mit-term unless we receive a community contribution for it.

**Comment by SpeedJack** [comment]
> if the parameter is the same, having it in `populate_entry` will be sufficient, and the indicator will also be available in `populate_exit_trend`.

That's good! I did not know.

> Changing the whole structure to allow both modes is most likely not an easy endeavor - and maintenance of such "double-feature" is usually quite cumbersome. As such - i'm not convinced if this brings the benefit you hope - not compared to the investment (time and future maintenance).
> 
> You're obviously free to submit a PR if you think this is a must, which i'll gladly review - but for the moment, i don't think this is something we'll be looking at short to mit-term unless we receive a community contribution for it.

I may try in the future to add it without adding too much complexity: learning to tune freqtrade at a deeper level may be useful, so I will probably engage in the development when I have more time.

Thank you.

**Comment by xmatthias** [comment]
This actually turned out to be a great enhancement, simplifying some usages in this realm! :+1:
