### ISSUE TITLE
jupyter notebook doesn't load json downloaded data by default

### ISSUE THREAD

**Issue by vaidab** [freqtrade/freqtrade#7084]
In strategy_analysis_example.ipynb -> Setup we have:
```
candles = load_pair_history(datadir=data_location,
                            timeframe=config["timeframe"],
                            pair=pair,
                            data_format = "hdf5",
                            )
```
It should be:
```
candles = load_pair_history(datadir=data_location,
                            timeframe=config["timeframe"],
                            pair=pair,
                            data_format = "json",
                            candle_type = config['candle_type_def']
                            )
```
Rationale:
- data is downloaded as json
- we sometimes need the /futures/ subdirectory

**Comment by froggleston** [comment]
This will then only work for those with JSON formatted data and not HDF5, so this should be refactored into explicit options, like the data_location field.

**Comment by xmatthias** [comment]
I actually prefer to be explicit here (use the Enum). Using "candle_type_def" infers some implicit logic in the config, which will not make it obvious which candles are actually loaded.
