### ISSUE TITLE
howww

### ISSUE THREAD

**Issue by walido0z** [freqtrade/freqtrade#7086]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Assuming this got away from you early, or you found whatever you were trying to ask.

Feel free to open another issue with actual content (or ask in our discord server) should there be questions ...
