### ISSUE TITLE
ERROR - Could not load FIAT Cryptocurrency map for the following problem: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by anylayer** [freqtrade/freqtrade#7087]
## Describe your environment

  * Operating system: ubuntu21.10
  * Python Version: 3.6.8
  * CCXT version: 1.89.14
  * Freqtrade Version: freqtrade 2022.6

  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```
![image](https://user-images.githubusercontent.com/46556817/179186714-c67d6255-4a41-422b-8b9f-1548d7b262aa.png)

**Comment by anylayer** [comment]
exchange: binance

**Comment by anylayer** [comment]
proxy is required?

**Comment by anylayer** [comment]
ERROR - Could not load FIAT Cryptocurrency map for the following problem: HTTPSConnectionPool(host='api.coingecko.com', port=443): Max retries exceeded with url: /api/v3/coins/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fec298f9f60>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by anylayer** [comment]
There is no interface to set the proxy

**Comment by anylayer** [comment]
can we consider uniformly configuring the proxy in freqtrade, such as ccxt,telegram?

**Comment by stash86** [comment]
Your bot can't connect to coingekko. No proxy required. It could be a temporary connection issue. Check again later. Bot's functionality won't be affected by it

**Comment by stash86** [comment]
From your screenshot, seems like the connection problem has gone

**Comment by xmatthias** [comment]
For the future, please post log output as text, not as screenshots. That makes it searchable - and simpler to use for everyone.

This certainly looks like a (temporary) issue with coingecko. As mentioned above - it'll not affect trading operations beyond these messages - you'll simply not be seeing the FIAT currency in messages.
They're informative anyway and could be disabled.

If you require to use a proxy for your network - you can configure such by following the [corresponding documentation](https://www.freqtrade.io/en/stable/configuration/#using-proxy-with-freqtrade).

**Comment by jeus1609** [comment]
> 

Excuse me, how can I disable it?

**Comment by xmatthias** [comment]
leave `"fiat_display_currency"` empty / remove that key from the configuration.

it's however almost always a temporary problem that'll go away soon enough.
