### ISSUE TITLE
ValueError: The truth value of a Series is ambiguous.

### ISSUE THREAD

**Issue by mert-donmez** [freqtrade/freqtrade#7089]
## Describe your environment

  * Operating system: ubuntu 22.04
  * Python Version: 3.10.04
  * CCXT version: 1.89.96
  * Freqtrade Version: develop-b39508f64
  
## Your question
Hi! I get valueError when I use custom_enter_price.
 `ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().` 
 How should i return custom_price?

```
def custom_entry_price(self, pair: str, current_time: datetime, proposed_rate: float,
                           entry_tag: Optional[str], side: str, **kwargs) -> float:

        dataframe, last_updated = self.dp.get_analyzed_dataframe(pair=pair,timeframe=self.timeframe)
                                                                
        short_price = dataframe['ema']*1.05
        long_price = dataframe['ema']*0.95
        
        if (side =="short"):
            return short_price
            
        elif(side == "long"):
            return long_price
            
        return None
```

**Comment by xmatthias** [comment]
a full stacktrace would clearly help more than a single value - as that would help identify where the error actually comes from.

one thing to note: `self.dp.get_analyzed_dataframe()` returns a dataframe (basically a table) - so the "long_price" you're returning is not a float (one number) - but a series of 500-1000 values.

what you're probably missing is the ` last_candle = dataframe.iloc[-1].squeeze()` step (as explained in the [documentation](https://www.freqtrade.io/en/stable/strategy-advanced/#dataframe-access)).

**Comment by mert-donmez** [comment]
Thanks xmatthias
