### ISSUE TITLE
Post Only trailing stop

### ISSUE THREAD

**Issue by Muzzie3** [freqtrade/freqtrade#7104]
Hi, the docs only differentiate between market and limit trailing stops. How do I set the trailing stop to Post Only?
I want to chase my profits with a post-only limit order to take profit. Is that possible?

**Comment by xmatthias** [comment]
I'm not aware of any exchange which allows post only stoploss orders.

by definition - a stoploss order is there to protect your money - and a post-only order would be canceled if placing it as post only is impossible.

Assuming you have a stop order that triggers at 99$.

once this order triggers, it'll place a regular order (limit or market). but the "post-only" placement fails. 
What'd be the expectation from the exchange? (ignore bot for now, assume manual order placement). 

It cannot really retry the placement - as the desired price has already passed - so while you expected profits to be protected, they really were not.

On binance for example - the moment you select a "stop" ordertype, the "post only" button disappears - which means this ordertype is not supported.

**Comment by Muzzie3** [comment]
hm, I see thanks for the explanation.
I was trying to do some discretionary scalping with post only limits. The goal is always to get out at 0.05 or more. Market orders are just not suitable for this and placing manual limits does not guarantee a fill and can leave me offside. Thats why I want to chase with post only. It guarantees me a fill and allows for more profits as opposed to just setting it always at 0.05.

**Comment by xmatthias** [comment]
> It guarantees me a fill

i  think you misunderstood how _post-only orders_ work. they will be force-placed into the orderbook - if that's not possible (for example because price is below your buy limit) the order placement will be cancelled - so there's no guaranteed fill here.

**Comment by Muzzie3** [comment]
I see thanks, I will just take the 0.05 then^^
