### ISSUE TITLE
add dark theme to plots

### ISSUE THREAD

**Issue by vaidab** [freqtrade/freqtrade#7106]
Having dark themes in plots is very helpful to prevent strain on the eyes and also easier for people who also use TradingView's dark theme.

Plotly has themes for this: https://plotly.com/python/templates/
Sample usage for plotly:
```
    fig = px.scatter(df_2007,  
                     x="gdpPercap", y="lifeExp", size="pop", color="continent",  
                     log_x=True, size_max=60,  
                     template="plotly_dark", title="Gapminder 2007: '%s' theme" % template)  
    fig.show()
```

How I'd expect it to look like in freqtrade:

```
   plot_config = {    
       'main_plot': {},
       'subplots': {},
       'plotly': {"template": "plotly_dark"}
   }
```

(or something similar to this)

**Comment by xmatthias** [comment]
While i do understand the request - we'll not be adding any new features to plotly plots.
Their performance (especially with bigger datasets) is not good.

They should be considered deprecated, and will be removed as soon as all functionality is in freqUI.

For general plots (candle plots) - freqUI is already the better solution (better performance, interactive indicator addition/removal). 
there is no alternative to `plot-profit` just yet - but once there is, plotly based plot modules will definitely be considered deprecated.

**Comment by vaidab** [comment]
I understand. Then it should be able to generate plots from backtests, not only live trades.

**Comment by xmatthias** [comment]
> Then it should be able to generate plots from backtests, not only live trades.

If you start `freqtrade webserver [-c config.json]` and navigate to the URI - you'll get a new backtesting tab - which allows you to either load existing backtests or run a new backtest - including seeing the plots off of this.

**Comment by vaidab** [comment]
Is it possible to run it along the frequi live mode from the same docker-compose?
The issue is that user_data/config.json contains the listen_port which is used by both interfaces.
It would be great if it would be integrated into the main interface (frequi) but if it's not possible, selecting a listen_port_backserver= would be helpful.

**Comment by xmatthias** [comment]
There's nothing preventing you from creating a second (webserver) service in docker-compose for this - which exposes a different port (you can reuse the same configuration - assuming it's backtest-compatible) - as the internal port won't change.

a sample of this can be found [in the documentation](https://www.freqtrade.io/en/stable/advanced-setup/#multiple-instances-using-docker).
