### ISSUE TITLE
freqtrade list-data should have an option to display the available daterange

### ISSUE THREAD

**Issue by vaidab** [freqtrade/freqtrade#7110]
Sample scenario: I want to know if I have all the data for a pair from date X to date Y.
I should be able to use list-data for this, maybe something like: "--display-timerange"

freqtrade list-data --trading-mode futures -vvv --userdir user_data -p BTC/USDT --data-format-ohlcv hdf5 --exchange binance --display-timerange

I know some files will contain data that's not in a range, and maybe that can also be shown in the output.

PS: I know download-data can download data before a timerange and after (so it's easy to download the missing data), yet sometimes it's important to see if you have it available before backtesting a period instead of downloading it.

**Comment by xmatthias** [comment]
This is not incorrect - but problematic from a performance perspective.

knowing the timerange requires to load the file (depending on the used format the complete file). in unfortunate cases (multi-year 1m data) this will load several GB from disk (my binance dir is ~8Gb) - which will obviously take a rather long time.

in general, i'd recommend to keep the data aligned across pairs (if you have a specific range, have that same range for all pairs). That'll avoid such problems via a different way.

I've now added it as enhancement - but don't expect any action on this soon - unless someone decides to pick this up and provide a PR for it.
