### ISSUE TITLE
Mark adjustment orders on chart

### ISSUE THREAD

**Issue by medenlin** [freqtrade/freqtrade#7112]
## Describe the enhancement

What about to mark adjustment (DCA) orders on chart (as Enter and Exit orders)? Or, tell me a way to do it yourself in a strategy if possible.

**Comment by xmatthias** [comment]
This is currently not possible - but on the roadmap for freqUI.

It'll however still take a while - as my focus is currently elsewhere.

**Comment by xmatthias** [comment]
Added in https://github.com/freqtrade/frequi/pull/1023.

will be part of the next release.
