### ISSUE TITLE
Documentation typo's

### ISSUE THREAD

**Issue by gaardiolor** [freqtrade/freqtrade#7115]
## Describe your environment

  * Operating system: N/A
  * Python Version: N/A
  * CCXT version: N/A
  * Freqtrade Version: N/A
  
## Describe the problem:
On https://www.freqtrade.io/en/stable/stoploss/, it states: the stop loss will now be -2% of 103$ = 101.42$
I think that this is incorrect, and it should state: the stop loss will now be -2% of 103.5$ = 101.43$

### Steps to reproduce:
1. Read the documentation
2. Find the line
3. Observe that the line is used in the context of `trailing_stop = True`
4. Conclude that the stop should 'trail' to -2% of 103.5 instead of -2% of 103
5. Calculate -2% of 103.5, and conclude that this is 101.43 instead of 101.42 (although when calculated using floats, it will be 101.42999999999999)
  
### Observed Results:

  * What happened?
I've read the documentation, read the line, didn't understand the line. Almost cried.

  * What did you expect to happen?
Understand the line

**Comment by xmatthias** [comment]
If you find a typo - i'd encourage you to attempt a fix on it yourself (i've fixed this now in the develop version though) next time.

Especially for the documentation, this can easily be done online (no need to checkout) - and github will enable you to automatically propose a Pull request with the proposed fixes.
