### ISSUE TITLE
Add CAGR information to webserver backtesting Analyze Result window

### ISSUE THREAD

**Issue by vaidab** [freqtrade/freqtrade#7116]
At this point Analyze Results doesn't show the CAGR value (even though the commandline version shows it). This metric is very useful when comparing strategies.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

We may eventually add it to freqUI when time allows.
Alternatively, you're obviously free to submit a pull request to [freqUI](https://github.com/freqtrade/frequi) adding this yourself.

**Comment by xmatthias** [comment]
This is now available in the main branch of freqUI - and will be included in the next release.
