### ISSUE TITLE
Exchange "huobi"  will not work with Freqtrade. Reason: missing: loadMarkets

### ISSUE THREAD

**Issue by avibrazil** [freqtrade/freqtrade#7117]
## Environment

  * Operating system: Fedora Linux 35
  * Python Version: 3.10.4
  * CCXT version: 1.91.20
  * Freqtrade Version: 2022.6

## Problem

Bot was frequently and unexpectedly dying, only with Huobi. But worked for a few hours. I noticed it use to die when posting a buy order, or while waiting for the order to fill, or when the order was partially filled. I had `entry_pricing.use_order_book=True` and thought this was the problem. I disabled this feature to use the strategy default (`false`), but it dies too, not always though. Telegram reports:

* Status: process died
* ⚠ Huobi: Cancelling enter Order for LBL/USDT (♯3). Reason: cancelled on exchange, partially filled.

To try to fix, I upgraded CCXT to 1.91.21 (latest given by pip). Now I can't even start the bot, I get this when trying to start it:

`freqtrade.commands.trade_commands - ERROR - Exchange "huobi"  will not work with Freqtrade. Reason: missing: loadMarkets`

Note: I'm mentioning 2 different problems here — bot dying and bot not starting. Let's focus on the bot not starting problem for now.

### Relevant code exceptions or logs

```
Traceback (most recent call last):
  File "/home/avibrazil/.local/lib/python3.10/site-packages/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/home/avibrazil/.local/lib/python3.10/site-packages/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/home/avibrazil/.local/lib/python3.10/site-packages/freqtrade/worker.py", line 49, in _init
    self._config = Configuration(self._args, None).get_config()
  File "/home/avibrazil/.local/lib/python3.10/site-packages/freqtrade/configuration/configuration.py", line 42, in get_config
    self.config = self.load_config()
  File "/home/avibrazil/.local/lib/python3.10/site-packages/freqtrade/configuration/configuration.py", line 101, in load_config
    check_exchange(config, config.get('experimental', {}).get('block_bad_exchanges', True))
  File "/home/avibrazil/.local/lib/python3.10/site-packages/freqtrade/configuration/check_exchange.py", line 50, in check_exchange
    raise OperationalException(f'Exchange "{exchange}"  will not work with Freqtrade. '
freqtrade.exceptions.OperationalException: Exchange "huobi"  will not work with Freqtrade. Reason: missing: loadMarkets
```

```
    "entry_pricing": {
        "price_side": "other",
        "use_order_book": false,
        "order_book_top": 5,
        "price_last_balance": 0.0,
        "check_depth_of_market": {"enabled": false, "bids_to_ask_delta": 1},
    },
```

**Comment by xmatthias** [comment]
Your ccxt version and freqtrade versions are missaligned - and in this case, unfortunately incompatible. 
If you wanna use a cutting edge ccxt version, best also use the develop version of freqtrade (where this problem has been fixed some weeks ago).

Alternatively, use the correct ccxt version corresponding to your freqtrade version (as it's defined in the corresponding requirements.txt file), or wait for the next update of freqtrade, which will include the fix from develop, as well as a new ccxt version.

I do understand that this is the "easy" problem - but the fix is just as simple.

for the "real" problem - please open a new issue with the corresponding logs - otherwise we'll not be able to assist.

**Comment by avibrazil** [comment]
Yes, I just noticed other bots won't start too, not just Huobi.

**Comment by xmatthias** [comment]
Yeah, ccxt changed their approach on this (they now assume all exchanges support load_markets) - which is fair enough.
We've adjusted - and as the ccxt version for stable freqtrade versions is pinned, there's little reason for us to get crazy. Newer ccxt versions will only be supported on freqtrade - it's however difficult/impossible to guarantee future versions to work without adjustment at any point in time.
