### ISSUE TITLE
Positive percent change to dynamic whitelist

### ISSUE THREAD

**Issue by sshchmod777** [freqtrade/freqtrade#712]
The --dynamic-whitelist auto generates whitelist based on 24hr volume but is it possible to filter only those with positive net change? this is to avoid markets having large volume but are going down. Please see attached.

Reference: https://github.com/gcarq/freqtrade/issues/589
@cofibit
![38001472-8dfb8fac-325f-11e8-9b7f-113d2d5f9c38](https://user-images.githubusercontent.com/38970077/40275868-32d06c8a-5c2e-11e8-916d-e45e182043fa.png)

**Comment by jblestang** [comment]
I’m concerned that not everybody has the same requirement about dynamic whitelist. Maybe it is a sign that the list of pairs to be traded should be left to the strategy and not to the core of the bot.

**Comment by xmatthias** [comment]
closing in favor of #589
