### ISSUE TITLE
Is it possible to separate the start and end of buy/sell by long and short?

### ISSUE THREAD

**Issue by JiSeopHyun** [freqtrade/freqtrade#7121]
I am testing Futures with the “FSupertrendStrategy” strategy applied. 
 However, there are frequent entry longs at highs and shorts at lows.  To prevent this, I want to control it in the Telegram bot.
  1) stop_enter_long
  2) stop_enter_short
  3) start_enter_long 
  4) start_enter_short

If possible, we may also need:
  1) stop_exit_long
  2) stop_exit_short
  3) start_exit_long
  4) start_exit_short

I am very fortunate to have encountered Freqtrade while developing an automated trading program by myself.  I hope that a good projector can study and be useful for many people.  thank you

<!-- 
Note: this section will not show up in the issue.
Have you search for this feature before requesting it? It's highly likely that a similar request was already filed.

  * Operating system: docker-78f77f6d in Synology
  * Python Version: seam in docker image
  * CCXT version: seam in docker image
  * Freqtrade Version:  seam in docker image

**Comment by xmatthias** [comment]
This is not possible - and also not something we'll be looking into integrating anytime soon.

Such logic should be built into the strategy itself, via some guards - which detect (and thus prevent) the signals from appearing.

**Comment by JiSeopHyun** [comment]
Thank you!.
I will think about it and add it.
I will end this issue.
