### ISSUE TITLE
Access to current liquidation price (futures trading)

### ISSUE THREAD

**Issue by medenlin** [freqtrade/freqtrade#7129]
How to access the trade liquidation price on exchange from strategy, if possible?
I see it in the docs: "Currently Freqtrade is able to calculate liquidation prices" (https://www.freqtrade.io/en/stable/leverage/#understand-liquidation_buffer).  But, is it possible to access the current liquidation price via 'Trade' object or else?

**Comment by xmatthias** [comment]
I guess you can use `trade.liquidation_price` for this.

In dry-run, this will contain the calculated price - in live the one from the exchange - including the `liquidation_buffer` (in both dry and live).

So assuming `liquidation_buffer` will be 0.05 (5%) - you'd get a liquidation_price 5% higher than what is really on the exchange.

**Comment by medenlin** [comment]
Please clarify, in live mode does Freqtrade take this value once when opening a trade or does update it every tick/candle or when new orders (DCA) are added?

**Comment by xmatthias** [comment]
The value will currently be updated whenever a new entry order fills. If that's the first, or the 3rd is irrelevant for this calculation.
As such - liquidation prices will adapt / change if you're increasing your position.

**Comment by medenlin** [comment]
It's very good, thank you
