### ISSUE TITLE
OKX and volumepairlist

### ISSUE THREAD

**Issue by Mehrancode2** [freqtrade/freqtrade#7130]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by Mehrancode2** [comment]
Exchange does not support dynamic whitelist in this configuration. Please edit your config and either remove Volumepairlist, or switch to using candles
that's my error what should I do?

**Comment by xmatthias** [comment]
Volumepairlist has an [advanced mode](https://www.freqtrade.io/en/stable/plugins/#volumepairlist-advanced-mode) - which is the one to be used with OKX. 

Be aware that it'll be slower than the regular mode mode - but with some exchanges - you must take what the exchange gives you.

Alternatively, you can also use a StaticPairlist - it's totally up to you in the end.
