### ISSUE TITLE
Problems with KuCoin API

### ISSUE THREAD

**Issue by avibrazil** [freqtrade/freqtrade#7137]
## Describe your environment

  * Operating system: Fedora Linux 35
  * Python Version: 3.10
  * CCXT version: 1.89.14
  * Freqtrade Version: 2022.6
  
## Your question

This is an issue for me, but since I confirmed that other users don't have this problem, I'm posting as a question.

Two KuCoin bots have been working perfectly for weeks with an [exchange-proxy](https://github.com/mikekonan/exchange-proxy). Then suddenly stopped working. I also tested one of them without proxy: same problem. I changed VM external IP, got new API key, nothing seems to work.

I can see the bot successfully fetching open orders from KuCoin, but later a simple `/status table` command from Telegram reports NaNs while I can see the following in the log:

```
freqtrade.exchange.common - WARNING - fetch_ticker() returned exception: "Could not load ticker due to NotSupported. Message: kucoin no auth". Giving up.
```

I tested my keys with an independent Python program that talks directly to KuCoin API (no CCXT) and I was able to fetch my balances.

I opened a ticket on KuCoin, they pointed me to the @KuCoin_API_Aaron_Wang Telegram user, but he is unresponsive so far (I think he is in a timezone ≈12h shifted from me).

Any ideas?

**Comment by avibrazil** [comment]
Tested [this simple CCXT example](https://github.com/ccxt/ccxt/blob/master/examples/py/tickers.py).
Output shows a list for pairs but then:
```
NotSupported ('kucoin no auth',) kucoin no auth
```

**Comment by xmatthias** [comment]
Are all bots using the same exact version - and same exact source ip / source ip country (could be a country level ban for whatever reason ...).

best try using the latest ccxt version - they're usually quick to spot and fix such problems...
fetch_tickers is a non-authenticated call though - so api keys should not really mater for this.

**Comment by avibrazil** [comment]
You are saying that suddenly they changed their API in a way that my old CCXT doesn't work anymore?

I tested in different computers, different countries and IPs. Brazil and Taiwan

**Comment by avibrazil** [comment]
Upgraded to latest CCXT. 1.91.35

Problem persists.

**Comment by avibrazil** [comment]
I opened a ticket on CCXT for this: https://github.com/ccxt/ccxt/issues/14505

**Comment by xmatthias** [comment]
No not really.
But if you confirm yourself that others dont have that problem.

Now i'll not support anything that goes through some proxy, where you'll not know what it does to requests, so assuming the non-proxy apporch below.

So you have a limited set of options.
Either something on your end changed (system dependency, ccxt version, network level something ...), Or something in the other side changed.

Now kukoin is known for their instable API (the main reason we don't officially support them fully).
Maybe something on their and changed, can be as simple as a cloudflare setting, or a change of cdn which now responds differently to certain scenarios like heavy load.
That would potentially not be communicated, just the dns records would change.

**Comment by avibrazil** [comment]
I tested without proxy in order to have more transparent results.

I tested with exact same versions of CCXT installed by pip, no virtualenv nor docker, just plain Linux.

I can reproduce the problem with a simple test script from CCXT repository, as mentioned above. Freqtrade and this script deliver same results.

I appreciate if someone can test it. You just have to run “python tycker.py kucoin”.

**Comment by stash86** [comment]
No issues on my kucoin bots, all not using proxy

**Comment by stash86** [comment]
Have you tried running a dry bot on a fresh install?

**Comment by xmatthias** [comment]
No problem with that script (it's actually `python tickers.py kucoin`).

As expected api.kucoin.com resolves to cloudflare - so geographical location will matter and will potentially get different results.
cloudflare may also keep your IP(s) as "previous offender" (for example) - and apply different, stricter rules to it after X calls within Y time - and eventually request a captcha or similar.

**Comment by avibrazil** [comment]
Problem solved.

I had a too generic `./.netrc` file which was making Python's requests or urllib connect to KuCoin using some unrelated password.

More here: https://github.com/ccxt/ccxt/issues/14505

**Comment by xmatthias** [comment]
Thanks for letting us know! 
honestly this is a problem cause i didn't really expect ... i guess for python it's a feature to use/support this file - obviously such generic config changes can have wide-ranging effects unfortunately.

great you were able to find out though! 👍

**Comment by avibrazil** [comment]
I guess not even CCXT folks know about it. I’ll open a new report in their repo to let them know that KuCoin API can be affected by this old UNIX file.

**Comment by avibrazil** [comment]
I guess not even CCXT folks know about it. I’ll open a new report in their repo to let them know that KuCoin API can be affected by this old UNIX file.

**Comment by xmatthias** [comment]
I dont think its linited to kucoin, but will most like affect most exchanges
