### ISSUE TITLE
Activate bot trading during predefined hours

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#7138]
Not sure if there is any better solution than cron job to start/stop the docker daemon? Can you please advise what is the best approach to keep the bot active only during predefined hours on daily basis?

**Comment by xmatthias** [comment]
I've transferred this to the main repository, as it's really not related to the technical library.

I'm not sure what your aim is with this - but freqtrade is really designed to be continuously running.
Assuming you stop freqtrade every day at a certain time - it may or may not have positions open, which it'll then no longer follow (until the restart). You might therefore miss potential exit opportunities (or stoplosses)- so i really think this approach is wrong.


Most likely, what you want is a date-based guard  - which prevents entering at certain times of the day. This can be easily accomplished by comparing the dataframe date with something else (for example `dataframe['date'].dt.hour < 20` (in UTC) - _untested_)

**Comment by darioneto** [comment]
Thanks for your reply. As long as the stop loss is sent to the exchange I'm not concerned with switching it off for a certain amount of hours. What would be the difference between dataframe validation or calling via API to stop/start?

**Comment by xmatthias** [comment]
As said above - stop stops all bot operations - so the bot evaluation will no longer run.
if you physically stop it (kill the process) - or call `/stop` is equivalent.
the only difference is that you can restart it remotely from `/stop` - which you can't if you kill the process. Then you need "something" to bring the process back up.

This includes not just stoploss - but also take profits - so if your pair had a 50% profit overnight - dropping back to -5% when you switch it on - it's as if that never happened - but you missed 50% profits.

**Comment by darioneto** [comment]
I understand, So in this case the best approach would be to use dataframe. So let's say for example that I need to turn off the bot between 1 am and 2 am UTC every day would this work? 
                 ............
                (dataframe['volume'] > 0) &
                ( dataframe['date'].dt.hour > 2) & (dataframe['date'].dt.hour < 1  )

In the  populate_entry_trend validation formula

**Comment by xmatthias** [comment]
you should change your wording / thinking from "turn it off" to "disable entry signals". That'll make your goal clearer - and will help in formulating your statement.

from afar (without really testing it) - it will work. 
i'd recommend to backtest this (maybe also with a wider range) - so you can see the effects on this (i assume this is based on "big whales trade mostly at this point ..." or "My signal is weak at that time ..."

**Comment by darioneto** [comment]
yes, you are correct, disable entry signals and also disable exit signals while maintaining the SL logic. I went ahead with `(dataframe['date'].dt.hour != 2)` as the previous formula would also catch the minutes after the full hour effectively disabling it for 2 hours. Ideally if it can be done with something including minutes like `dataframe['date'].dt.hour.minutes > 2.30` but that probably would not work

**Comment by xmatthias** [comment]
i think `.dt.minute` should exist - and run from 0-59 ... The [pandas documentation](https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.minute.html) will be your friend on such topics

**Comment by darioneto** [comment]
So running some testing with this method and it seems after I upgraded the Docker image to the docker-573964b1  develop the time restrictions only for the exits stopped working correctly for some reason 
for example, the statement works with entries but not for exits. This statement is executed at the full hour (dataframe[‘date’].dt.hour != 5) at 05:00:00 UTC which effectively closing up trades. 
It seems coincidental that the logic has changed after the upgrade of the image. 
Is this because the string in pandas has to be converted to the date/time type to validate acurately?

**Comment by xmatthias** [comment]
The dataframe freqtrade provides to the strategy has the ['date'] column as datetime, and this is nothing that changed anytime within the last 2-3 years.

**Comment by darioneto** [comment]
Would you have any suspicion of what could be causing it? 
As the conditions are chained with & therefore all of them should participate in validating. 
The following statement` (dataframe[‘date’].dt.hour != 5) `should invaidate and exclude any other condifion in the .loc[] in reference to time  starting from 05:00:00 to 05:59:00 UTC if I understand correctly. 

   ```
     dataframe.loc[
            (
                (dbtc_4["pc"][0] > 40) &
                (dbtc_4["round"][0] <= 0.0025) &
                (dbtc_4["round"][0] > 0.0015) &
                (dataframe['volume'] > 0) &
                (dataframe['date'].dt.hour != 5)
            ),
            ['exit_short', 'exit_tag']] = (1, 'Test')
 
```
Just to add to this, a Very similar statement is located at the entry which works. The new trades are not being opened. It doesn't work only at the exits ignoring the time restrictions.

**Comment by darioneto** [comment]
I was thinking if this formula can be implemented instead ?
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.between_time.html
Tested with this statement 
`(dataframe['date'].dt != DataFrame.between_time('10:15', '11:45'))`
but for some reason errors out with :
 NDFrame.between_time() missing 1 required positional argument: 'end_time'

**Comment by xmatthias** [comment]
i don't think you can use between_time this way (as a filter) - but i'm not an expert in pandas date filtering - not in this format, anyway.

**Comment by farmage** [comment]
I'm wrote my own Protection class to implement this:
```
    def protections(self):
        return [
            {
                "method": "TradingTime",
                "lookback_period_candles":1,
                "start_time": "04:00", # UTC
                "end_time": "20:05" # UTC
        ]
  ```
  to use this feature you can check my fork at [https://github.com/farmage/freqtrade]( https://github.com/farmage/freqtrade)
 I'm keeping this fork up to date with the main branch, so it possible to use it in production
  I'll be glad if team accept it to main code

**Comment by darioneto** [comment]
Thanks, @farmage , Any chance this request can be merged @xmatthias?

**Comment by xmatthias** [comment]
@farmage you're obviously free to submit a pull request. (please not from a repository's main branch).


If it's just a protection, then i doubt this will work properly - protections are only triggered once a trade closes, and will lock a pair (or the whole bot).
it'll however not trigger at random places (if i start my bot now - and it does no trades until tomorrow - then the start/end time will NOT be respected).
