### ISSUE TITLE
Support for API client with Prometheus Exporter

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#7141]
## Describe your environment

  * Operating system: __Docker__
  * Python Version: __3___ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Any recommendation for official integrations with API client & Prometheus Exporter?

**Comment by xmatthias** [comment]
Prometeus is a Log / application performance platform.
so assuming you're using docker, you should be able to pipe logs there somehow.
this should probably also work with some logfile analyzer, assuming you're not using docker and use `--log-file` instead.

For freqtrade trading metrics themselves - i don't think prometeus is made for such a thing.
all integrations i've seen with a quick look are around platform performance (like - how many requests were served by nginx) - not how good or bad a bot is doing in current market situations.

**Comment by darioneto** [comment]
I'm planning on exporting metrics related to the trading performance like the ones which are presented in the freqUI. If this is something that can be extracted from the logs I will try to explore further this path.

**Comment by xmatthias** [comment]
i don't think you'll get much from the logs in this regard, at least not easily.

i do however doubt that prometheus is the right tool to analyze trade performance.

**Comment by darioneto** [comment]
Yes, logs are not good for that. Prometheus could be not ideal in terms of query flexibility however one of the easier to integrate. Do you recommend any other method for exporting those trade/accounts metrics?

**Comment by xmatthias** [comment]
Well freqtrade uses a sqlite (or other) database. using a  log analysis tool is clearly the wrong approach to get to the trade data.

We have a data analysis section [in the docs](https://www.freqtrade.io/en/stable/data-analysis/) with some samples - but nothing prevents you from connecting directly to the database.

Prometheus however does not make sense - at least not for the purpose you're trying to use it - as such i'll close this issue - as this is not something we'll invest time into.

**Comment by darioneto** [comment]
Thanks for your suggestions, ok, I see, in regards to trade data, probably the easiest is just to cron the sqlite3 dump to postgres tables. As those files live outside of containers scraping those files shouldn't affect the docker internal sqlite db processes.

**Comment by darioneto** [comment]
Oh I just found on the docs postgress can be used as a default DB. Awesome, no need for pgloader then!
