### ISSUE TITLE
Further option to min_days_listed

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#7145]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

For volume pairlists, one might want to whitelist coins, which are ‘older’ than a specific date. To avoid unexpected behavior, for example. With min_days_listed we have to edit the value regularly. Would it make sense, giving the option, to enter a specific date as a second option?

*Explain the enhancement you would like*

**Comment by xmatthias** [comment]
[AgeFilter](https://www.freqtrade.io/en/stable/plugins/#agefilter)  does filter pairs which are younger than "X".


Pairs are listed/delisted all the time - and the purpose of having a pair older than "X" days is to only have pairs with sufficient history.
I don't really understand why you'd want a fixed date. i don't see a reason for that if i'm honest.

**Comment by myNextCoder** [comment]
I thank you for your answer, I absolutely understand, what you tell me. I try to explain: I would like to be sure, that no brandnew coin appears in my whitelist, which I have not backtested, or which for any reason could have a trend, leading to loss in hardly any case. Finally I don't know, if one day a leverage token appears, that does not meet the common syntax conventions like 3L, 5S, etc. With lookback days, such a coin may suddenly appear in the whitelist. Currently I avoid this, by regularly increment the min_days_listed value.

**Comment by xmatthias** [comment]
> no brandnew coin appears in my whitelist, which I have not backtested

For this - best use a static pairlist with your backtested pairs. You can still use volumepairlist at a later point in the pairlist to provide sorting (and removal of X+ coins).



> Finally I don't know, if one day a leverage token appears, that does not meet the common syntax conventions like 3L, 5S,

A static date would only protect you so far - assuming an exchange renames a coin - that coin would have history available - so your protection would not really have worked. The only way to be 100% sure about this is using a static pairlist.

**Comment by myNextCoder** [comment]
In that case I start some tests with static pairlists. Even we do not talk about a specific strategy here, I changed to volume pairlist, because for NostalgiaForInfinityX this is recommended.
