### ISSUE TITLE
Freqtrade UI Black Screen

### ISSUE THREAD

**Issue by Roboticol** [freqtrade/freqtrade#7147]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: 3.10
  * CCXT version: latest
  * Freqtrade Version: latest
  
## Describe the problem:

I have been trying to get freqtrade's web UI by following [this](https://www.freqtrade.io/en/stable/rest-api/#openapi-interface) guide. However, when I get to http://localhost:8080/trade all I get is a black screen with no text in it. Note that I did this while the bot is on.
Also, in the website's console I get this error:
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

### Steps to reproduce:

  1. Follow [this guide](https://www.freqtrade.io/en/stable/rest-api/#openapi-interface) to get freqtrade's UI.
  2. `freqtrade trade --dry-run --strategy MyStrategy`
  3. Go to http://localhost:8080/trade with javascript on in this website.
  
### Observed Results:

  * What happened: Got a black screen website
  * What did I expected to happen: Get the actual FreqUI as shown in freqtrade's docs website.

### Relevant code exceptions or logs

Here is the website console log I got from inspect element:

  ```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
  ```

**Comment by xmatthias** [comment]
"latest" is not a valid version - and will outdated whenever someone looks at this. Please specify a proper version of freqtrade - which can be retrieved via `freqtrade --version`.

also - what's your installation method (docker, native, wsl, ...)

**Comment by Roboticol** [comment]
> "latest" is not a valid version - and will outdated whenever someone looks at this. Please specify a proper version of freqtrade - which can be retrieved via `freqtrade --version`.
> 
> also - what's your installation method (docker, native, wsl, ...)

oh ok, my freqtrade version is freqtrade develop-68974b0
and my installation method is native

**Comment by xmatthias** [comment]
68974b0 is not a commit of this Repository (the 2nd part of the version is a commit - if it were a valid commit, github would show it as a link)- so i'm wondering where you've installed that / got that version from.

if you're unaware of this - you can try to run `git reset --hard origin/develop` to get inline with the main repository again (Please note that this will remove all changes you did to the bot).

Also - is this your first installation, or did you have prior installs - which were updated recently?

**Comment by ziiiliu** [comment]
I ran into the exact same problem, but with version "develop-f3ef6e1". I previously installed with Docker but recently switched to native install on Windows. Everything else works just fine except for the UI, which used to work with the Docker setup

**Comment by stash86** [comment]
> I ran into the exact same problem, but with version "develop-f3ef6e1". I previously installed with Docker but recently switched to native install on Windows. Everything else works just fine except for the UI, which used to work with the Docker setup

Check your config. Frequi port setting for docker and non-docker is different. Check the docs

**Comment by xmatthias** [comment]
this is also similar/identical to https://github.com/freqtrade/frequi/issues/878.
There's no solution to that topic - and i've been unable to recreate it too.
my suspicion is that there's outdated dependencies - hence the information if it's a fresh install - or something that's been updated from an old installation might make a difference.

Please also provide me with the output of `pip freeze` (you can wrap this into tripple backticks (`` `) for readable formatting)

@ziiiliu f3ef6e1 is another version we've got no commit for in this repository - which is something i don't understand.

**Comment by ziiiliu** [comment]
Thanks for the reply! 
The version thing is baffling me deeply as well. Inside the freqtrade directory when I run `freqtrade --version`, it gives me `freqtrade develop-369c6da5d`, but when I run the same command anywhere else in the system, it shows the odd version (f3ef6e1) that does not appear in the repo commit. I have checked that both times the command points to the same exe file in `freqtrade/.env/Scripts`.

I am pretty sure that I removed the previous docker installation (unless I missed anything there), and I have uninstalled-reinstalled freqtrade a couple of times, but the problem persists. 

And here's the pip freeze output:
```
aiodns==3.0.0
aiofiles==0.8.0
aiohttp==3.8.1
aiosignal==1.2.0
anyio==3.6.1
APScheduler==3.6.3
arrow==1.2.2
async-timeout==4.0.2
attrs==22.1.0
backports.zoneinfo==0.2.1
blosc==1.10.6
cachetools==4.2.2
ccxt==1.91.29
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.1.0
click==8.1.3
colorama==0.4.5
cryptography==37.0.4
fastapi==0.79.0
-e git+https://github.com/freqtrade/freqtrade.git@369c6da5d8e90475a39583a6c53fd86d2222bfa5#egg=freqtrade
frozenlist==1.3.0
greenlet==1.1.2
h11==0.13.0
idna==3.3
importlib-resources==5.9.0
Jinja2==3.1.2
joblib==1.1.0
jsonschema==4.7.2
MarkupSafe==2.1.1
multidict==6.0.2
numexpr==2.8.3
numpy==1.23.1
orjson==3.7.8
packaging==21.3
pandas==1.4.3
pandas-ta==0.3.14b0
prompt-toolkit==3.0.30
psutil==5.9.1
py-find-1st==1.1.5
pycares==4.2.1
pycoingecko==2.2.0
pycparser==2.21
pydantic==1.9.1
PyJWT==2.4.0
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
python-rapidjson==1.8
python-telegram-bot==13.13
pytz==2022.1
pytz-deprecation-shim==0.1.0.post0
questionary==1.10.0
requests==2.28.1
schedule==1.1.0
scikit-learn==1.1.1
scipy==1.9.0
sdnotify==0.3.2
six==1.16.0
sklearn==0.0
sniffio==1.2.0
SQLAlchemy==1.4.39
starlette==0.19.1
TA-Lib @ file:///D:/CS/trade_bot/trading_apps/freqtrade/build_helpers/TA_Lib-0.4.24-cp38-cp38-win_amd64.whl
tables==3.7.0
tabulate==0.8.10
technical==1.3.0
threadpoolctl==3.1.0
torch==1.12.0
tornado==6.2
typing_extensions==4.3.0
tzdata==2022.1
tzlocal==4.2
urllib3==1.26.10
uvicorn==0.18.2
wcwidth==0.2.5
yarl==1.7.2
zipp==3.8.1
```

**Comment by xmatthias** [comment]
within the freqtrade environment (with activated venv) - can you try to run the following in a python window ( `python` and copy the below into it)

``` python
import mimetypes
mimetypes.guess_type('hello.js')
```

please share the output of this.

**Comment by ziiiliu** [comment]
The output is pasted below
```
>>> import mimetypes
>>> mimetypes.guess_type('hello.js')
('text/plain', None)
```

I suppose this is the root of the problem?

**Comment by xmatthias** [comment]
it for sure is - but it's python internals, i'm not sure this is fixable from our end...

What's your python version? and what's the windows system language you're running this from?

**edit** seems like this is based on windows settings ... see [this python bug report](https://bugs.python.org/issue32462)

**Comment by ziiiliu** [comment]
Thanks for the information! I have fixed the issue now. 

Apparently `guess_type` method obtains the type from my local windows registry, and according to this [bug report](https://bugs.python.org/issue43975), we need to edit the `HKEY_CLASSES_ROOT\.js\Content Type` entry from `text/plain` to `application/javascript` manually. 

This is probably a devious fix, but it did solve the problem in my case.

**Comment by xmatthias** [comment]
It's as [this bug report](https://bugs.python.org/issue32462) says - it's a system configuration issue. 
while we could enforce a type for specific types - i'm not sure we should.
That would mean we'd override the OS - which could lead to other problems (maybe in other cases).

there'll have been a reason this has been changed in the first place - as having this set to text/plain is not a windows default.

**Comment by xmatthias** [comment]
This is clearly a system configuration issue - so everyone encountering this so far should carefully look at the configuration - and fix that (it could have other consequences to other programs, too).

for freqtrade, we'll force the type for JS files to avoid such problems for our userbase.
