### ISSUE TITLE
Support for dYdX

### ISSUE THREAD

**Issue by KonScanner** [freqtrade/freqtrade#7149]
## Support for dYdX
Decentralized trading spot + futures, [dYdX](https://trade.dydx.exchange/). No need for KYC.

**Comment by hippocritical** [comment]
https://github.com/ccxt/ccxt/

freqtrade has to go through ccxt. if it doesnt support some exchange then first have ccxt implement it.
I doubt that they will do it since afaik this one is not a classic exchange but a decentralized one.

**Comment by xmatthias** [comment]
for Freqtrade it does not make sense to pursue this before support for an exchange is in ccxt.

There's a PR in progress (https://github.com/ccxt/ccxt/pull/11643) - but it's seen little action recently.
Feel free to reopen this / open a new issue once ccxt adds support for the exchange (it's listed on their documentation page [here](https://docs.ccxt.com/en/latest/exchange-markets.html).
