### ISSUE TITLE
leverage applies to PNL not with the actual price

### ISSUE THREAD

**Issue by mhgutier** [freqtrade/freqtrade#7163]
## Describe your environment

  * Operating system: windows 11
  * Python Version: 3.10.5
  * CCXT version: 1.76.65
  * Freqtrade Version:2022.7
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

hi, does the leverage applies to the PNL and not with the actual price change?

config:
stoploss = -0.265
minimal_roi = {"0": 0.1}
stake amoint=10

expected profit:
no leverage:
minimal_roi = 1USDT (10% of 10 stake amount)

with leverage:10x
minimal_roi = 10USDT (10%x10% of 10 of stake amount)

actual profit:
no leverage:
minimal_roi = 1 USDT (10% of 10 stake amount)

with leverage:
minimal_roi= 1 USDT ( 1% x 10 leverage of 10 stake amount)

im expecting the bot to exit at 100% PNL (10% x10 leverage).
but it actually exited at 1% price diff

however take profit was triggered with 1% price change.

so do i need to multiply the minimal_roi and stoploss to the leverage i use to achieve same results when trading on binance UI?

**Comment by xmatthias** [comment]
stoploss defined defines the risk you're willing to take on your invested capital, not the price change.
Without leverage, the two will be the same - but with leverage, this obviously changes.
This is also covered in the [documentation](https://www.freqtrade.io/en/stable/stoploss/#stoploss-and-leverage) as a separate point.

Imagine a trade you specified a stoploss of 10% - but freqtrade then shows a profit of -50% - you'll be surprised and think it's not working / broken (you actually lost 50% of your invested capital).


Obviously the same applies to ROI.

**Comment by mhgutier** [comment]
Thank you for the very quick response and clarification
