### ISSUE TITLE
Download all FTX pairs

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#7164]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Currently FTX has over 400 USD pairs to list. As soon as I download them all with ".*/(USD)", there are only 46 pairs.
I thank you for your help.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Most likely, you've got some blacklist in your configuration which is blocking off most of the pairs (something around BULL/BEAR most like).
If you're able to provide the log Up to the first pair that'll be downloaded - we will be able to confirm this 

using `freqtrade download-data --exchange ftx --pairs ".*/(USD)"` (the parenteses are not necessary, `.*/USD` would suffice) does download 416 pairs for me.

**Comment by myNextCoder** [comment]
Next time I complete the template at the top.
It was my own little syntax issue, I discovered thanks to your command line. I thank you for your help. All 416 pairs are currently downloading. . .
