### ISSUE TITLE
Difference between relative drawdown and underwater?

### ISSUE THREAD

**Issue by popperwin** [freqtrade/freqtrade#7166]
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.8.8  (`python -V`)
  * CCXT version: 1.89.14 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2022.6 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Until now I thought the relative drawdown was the same as underwater, but I saw that we have two separate functions `calculate_underwater` and `calculate_max_drawdown` with the relative boolean set to true .
What are the differences between those two concepts? 

Thanks,

**Comment by xmatthias** [comment]
Taken from the [summary metrics documentation page](https://www.freqtrade.io/en/stable/backtesting/#summary-metrics)

> Max % of account underwater: Maximum percentage your account has decreased from the top since the simulation started. Calculated as the maximum of (Max Balance - Current Balance) / (Max Balance).

> Drawdown: Maximum, absolute drawdown experienced. Difference between Drawdown High and Subsequent Low point.


The difference is what you relate it to. 
One is the biggest (absolute) drawdown - while the other is the biggest relative drawdown.

Assuming you start with an 1000$ account - which later grows to 10.000$.
If you lose 500$ on your first few trades - you'd be down 50% on the account right away.
you now go to a winning streak - winning a ton in a row, raising the account to 10.000$.
Your next few trades are losers again - reducing the account to 9000$ - which is a 1000$ drop - but (relative to the 10.000$ - only a 10% drop.

So you have the biggest absolute drawdown (1000$ | 10%) - and the biggest relative drawdown - which is the initial 500$ - or 50% of the account.
Usually, the biggest relative drawdown will hurt you more - and most likely, you'd have stopped the strategy after the 50% loss (maybe even earlier).

**Comment by popperwin** [comment]
Thanks for your reply!
I understood it, and that what I was looking for in the code.
Reading the code, I first thought that `calculate_max_drawdown`[function](https://github.com/freqtrade/freqtrade/blob/9df10c6b5b0ac22fef55584e91bd56d6facffafd/freqtrade/data/metrics.py#L119) with the relative parameter set to true is equivalent to underwater definition; and then I saw `calculate_underwater` without understanding why there is 2 functions for this.

**Comment by xmatthias** [comment]
the 2 functions do something slighlty different.
`calculate_max_drawdown` gives you the drawdown (a handful of numbers) - while underwater returns  a series for plotting.
The base calculations are identical/similar - but the outcome is a different one.

**Comment by popperwin** [comment]
Thanks , I should have paid more attention to the return of the two functions :)
