### ISSUE TITLE
How to debug a freqtrade strategy using PyCharm ?

### ISSUE THREAD

**Issue by dhairyagada** [freqtrade/freqtrade#7167]
## Environment

  * Operating system: Windows
  * Python Version: 3.10.5 
  * CCXT version: 1.89.14
  * Freqtrade Version: 2022.6
  
## Question

Hi, I am trying to debug a strategy while backtesting it using PyCharm but I cannot figure out how to do so.

I have installed Freqbot using docker and use PyCharm's docker plugin to start the container, which works as expected and the container is live and running.

<img width="659" alt="image" src="https://user-images.githubusercontent.com/10364716/182433284-0c5190d6-e8dc-427b-aeac-f0d101cd52cf.png">

<img width="929" alt="image" src="https://user-images.githubusercontent.com/10364716/182433451-1412eca4-e562-461b-a71d-2d92f228fcf4.png">

However, I don't know how to debug the strategy because I don't have the location to start script of the bot which is running inside the container.

I also tried doing 
```
command: > 
      backtesting
      --strategy SampleStrategy
      --dry-run-wallet 1000
      --max-open-trades 1
```
 
in the docker-compose.yml to see if I can hit a breakpoint in this manner, but it does not seem to work.

**Comment by xmatthias** [comment]
if i'm honest, then it's new to me that pycharm allows you to debug within containers.

In theory, it should allow you to attach the process to the (only) process running within the container - at least if it's done well - but as i've never used it, there'll be little help on this.

**Comment by dhairyagada** [comment]
@xmatthias is it possible to debug it in VSCode?

**Comment by xmatthias** [comment]
it sure is - but again, i'm not sure about container debugging. 

it **may** work if you start vscode in a devcontainer - but i don't think it'll work in a random container vscode starts - at least i don't know how as that's a way i never used.

**Comment by napent** [comment]
![image](https://github.com/freqtrade/freqtrade/assets/6579596/13952868-74be-4332-bfb2-357a4091ecd5)
