### ISSUE TITLE
Partial exit with custom exit prices

### ISSUE THREAD

**Issue by Axel-CH** [freqtrade/freqtrade#7171]
## Describe the enhancement
The feature https://github.com/freqtrade/freqtrade/pull/6545 "adjust trade position" is great because it is allowing traders to have better risk management and secure some profits early. This feature could be even more useful coupled with custom order price, for multiple reason:

- With limit / market making order you pay less trading fees
- Order already in order book, will be filled immediately if price moove in that direction.

This will allow traders to have a strategy on a trade secure a part of profit first, and then keep the position open to get more of it. 
OR if the trade maket move in opposite direction to leave the trade with some profit or at break heaven.

One of the main challenge of trading using custom entry or exit prices is that there is a high probability that the order you placed won't be filled if too far away. However is you place your limit order too close to entry price you will not earn a significant profit. Coupling  custom prices with partial position management could be a good combination to set close and ambitious targets taking advantage of both situations.

**Exemple**
Current price is 10 position is LONG

Trade take profit reduce position of:
25% of at price 11
25% at price 12

Both of those are limit orders placed on exchange
If the price move up, they will be filled and trade position size will be reduced to 50%.

Exit at market for the rest of position if specific exit signal is triggered

**Comment by xmatthias** [comment]
There is nothing preventing you from using `custom_exit_price` with partial sells.

while `custom_entry_price` is not called for partial entries - the exit callback is called - and will/would be used to specify the exit price.

Now having more than one open order on the exchange ain't possible - but i don't see why that would be necessary either. 

I'm however not a huge fan of the "place take profit orders early" - as it'll effectively disable your stoploss handling (the locked amount cannot be in a stoploss order) - and make your processing slow in case of a drop - so if you place them early, you'll need to have good, custom timeout rules that cancel the order if price moves towards the stoploss.

**Comment by alirezahdry** [comment]
Hello, suppose I have a position and I want to close half of it if the price reaches a specific number, and if the price moves again, I will close 25% and the final 25% after that, and at each stage, I will set my stop-loss. Put on the previous price. How can I implement it with freqtrade?

**Comment by xmatthias** [comment]
@alirezahdry best look at the [callback](https://www.freqtrade.io/en/stable/strategy-callbacks) documentation page.

you'll have to combine several callbacks (custom_stop, adjust_trade_position, ...) to get to that scenario.

**Comment by fdoooch** [comment]
> Hello, suppose I have a position and I want to close half of it if the price reaches a specific number, and if the price moves again, I will close 25% and the final 25% after that, and at each stage, I will set my stop-loss. Put on the previous price. 

Hi, mate! Did you manage to implement your idea with freqtrade?

**Comment by xmatthias** [comment]
@fdoooch please refer to the documentation (linked above) on how to implement this, instead of commenting on 2 year old issues, thanks
