### ISSUE TITLE
Please add Trade ID Telegram command

### ISSUE THREAD

**Issue by choepru** [freqtrade/freqtrade#7172]
Please add Trade ID Telegram command entrylong or entryshort, for entry and exit from tradingview.

**Comment by xmatthias** [comment]
It's completely unclear what you're after (i got no clue what you'd like). 

Please describe your request a bit more in detail, so it becomes clear.

**Comment by choepru** [comment]
yes Sir,...

**Comment by choepru** [comment]
can I entry and exit signal the Bot by means of Tradingview Webhook with TelegramAPI?

**Comment by choepru** [comment]
I have a problem for exit orders using TelegramAPI, exit orders have a trade_id, while tradingview doesn't know the trade_id yet /fx <trade_id>

**Comment by xmatthias** [comment]
Please use the edit button instead of posting multiple answers in a row. That will make the conversation easier to follow.

I'm not sure how tradingview fits into this picture. 
In telegram, you'll have the `/status` or `/status table` commands, which will show you the open trades, as well as the tradeid used for the exit command.

You can also use `/forceexit` without parameter to get an interactive list of open trades - which you can click onto to sell these.

**Comment by stash86** [comment]
What I think they mean, they want to use signal generated by Tradingview for enter and exit on FT bot. The issue is they want to use Telegram API for that, when I assume they should be using REST API for it

**Comment by choepru** [comment]
can the REST API control the entry and exit signals from TradingView?

**Comment by xmatthias** [comment]
Freqtrade does not explicitly support tradingview - but you can read about the rest api [here](https://www.freqtrade.io/en/stable/rest-api/) - or about the possibilities for telegram [here](https://www.freqtrade.io/en/stable/telegram-usage/)

**Comment by choepru** [comment]
I want freqtrade as a manual strategy, and entry with restAPI or with Telegram, with keywords for entry: forceentry <pair> <trade_id>. and for exit: forceexit <trade_id>. can you help me add <trade_id> for API entry?

**Comment by xmatthias** [comment]
Trade_id's are given by the database (in a sequential manner). 
You can't know from the outside what the next id is - and it's not the purpose of an API consumer to know this.
So the command you're asking does not make sense, and might lead to duplicate entries - and therefore potential database corruption.


as such, that's nothing we'll be adding, or even support you in adding yourself.

Use `forcentry <pair>` - which will then return the trade-id in the response (assuming the trade was successfully placed).

**Comment by choepru** [comment]
Thank's Sir...
