### ISSUE TITLE
Post Only orders - order_time_in_force

### ISSUE THREAD

**Issue by alisalama** [freqtrade/freqtrade#7175]
## Describe your environment
(if applicable)

  * Operating system: Mac OS Monterey
  * Python Version: 3.9.7 (`python -V`)
  * CCXT version: ??? (`pip freeze | grep ccxt` - comes up with nothing - perhaps needs to be run in docker?)
  * Freqtrade Version: freqtrade 2022.7 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

Hi, thanks for this amazing bot! Truly excellent stuff!

Would it be possible to implement Post Only orders? I mostly use FTX and I can see that they are available as an order type on the latest CCXT for FTX.  Would there be any issue with the bot not being aware of the potentially cancelled order on the exchange, although I would imagine the exchange API would return an unsuccessful response so I think would be fine, or is it implementable?

This would be in order to ensure that orders are maker orders and not have to pay taker fees. I have experimented with the following settings, which helps prevent most maker orders but I still do pay maker fees fairly regularly.

```
"price_side": "same",
"use_order_book": true,
"order_book_top": 1,

```

I am a javascript programmer really, but I can have a go at a PR if you think it is implementable.

Thanks,
Ali

**Comment by xmatthias** [comment]
The cancellation would for sure not be a problem. it'd act similar to a IOC order - which will be visible as canceled via the api - which freqtrade supports for several exchanges.

if it were a simple `order_time_in_force` (sent as IOC, for example) - then it'd be easy to support.
It's however a separate parameter to ccxt - which means we'll need to first investigate how the interface for such a parameter is for other exchanges (assuming they support it) - and then decide if we'll add it as additional "order_time_in_force" - or if it needs to be a separate parameter.
