### ISSUE TITLE
Profit calculation on /profit is wrong for partial exit trade

### ISSUE THREAD

**Issue by stash86** [freqtrade/freqtrade#7178]
## Describe your environment

  * Operating system: ubuntu 22.04
  * Python Version: 3.10 (`python -V`)
  * CCXT version: 1.91.29 (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
After a trade closed with multiple entry adjustments and partial exits, the profit shown on /profit command is different

```
ROI: Closed trades
∙ -0.953 BUSD (-0.23%) (-1.47 Σ%)
∙ -0.955 USD
ROI: All trades
∙ -0.181 BUSD (-0.23%) (-0.28 Σ%)
∙ -0.181 USD
Total Trade Count: 1
First Trade opened: 0 days 0 hours and 50 minutes ago
Latest Trade opened: 0 days 0 hours and 50 minutes ago
Win / Loss: 0 / 1
Avg. Duration: 0:48:22
Best Performing: BTC/BUSD: -0.23%
Trading volume: 836.031 BUSD
Profit factor: 0.00
Max Drawdown: 0.00% (0 BUSD)
Updated: Thu Aug  4 15:42:26 2022
```

### Steps to reproduce:

  1.Use test_dca strategy, attached config.json (attached)
  2. Let the bot do the automatic entries and exits
  3. Once the bot stop its extra entries, forceexit the trade, then check /profit on Telegram bot
[part_exit.zip](https://github.com/freqtrade/freqtrade/files/9264193/part_exit.zip)

  
### Observed Results:

  * What happened?
  The Closed Trades ROI and All Trades ROI are different

  * What did you expect to happen?
  Both have same values

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by stash86** [comment]
Gonna look at the sqlite myself, and do manual calculation to see which ROI is the correct one

**Comment by stash86** [comment]
According to simple math (there is a xls file attached in the .zip) of using `cost` column and do simple math (sum of sell - buy), the end profit is -0.11746, which is close to the All Trades ROI (I assume the Cost column exclude fees?). So that would mean the Closed Trades ROI is the wrong one. Gonna look into it now

**Comment by stash86** [comment]
So the breakdown of the calculations that I traced

**For All trades ROI**
Profit is count from close_trade_value - open_trade_value. Close_trade_value is calculated from last exit rate * last exit amount. Open_trade_value is last exit amount * last average open rate. So it's just coincidence that the All profit ROI is close to my simple profit calculation. If the price ranging more, the calculation will have big difference.

**For Closed trades ROI**
Profit is calculated with sum of smaller profit calculation on every partial exit orders. The profits are calculated from exit rate of that time compared to average entry price (which will keep changing before the trade finally closed)

Gonna test a version using orders' cost to calculate profit, since that should be the best indicator for it

**Comment by xmatthias** [comment]
-0.953 is the correct, absolute value - based on the calculation used (see example in [the docs](https://www.freqtrade.io/en/latest/strategy-callbacks/#position-adjust-calculations).

FreqUI confirms this - and since there's only one trade - the profits should align with `/profit` reports.


![image](https://user-images.githubusercontent.com/5024695/183002766-9e62c98a-6a97-4fc0-bc22-5b6020669bc0.png)


If you do the calculation in excel, you'l need to be quite careful how the avg. rate is calculated - as sells will not modify the average - but an additional buy (after a sell) must correctly weight the prior amounts.

**Comment by stash86** [comment]
My excel calculation is very simple. Sum of sell costs - sum of buy costs, which show a far difference with close profit value. Average rate has no influence in it

**Comment by xmatthias** [comment]
cost in the order table does not include fees (or rather not correctly in all cases depending how fee was deduced) - and therefore cannot "really" be used for that

**Comment by stash86** [comment]
ah okay, after adding fee to the cost, the profit is -0.9535, which is the same as Closed trade ROI. So the issue now is to fix All trades ROI

**Comment by stash86** [comment]
Just checked the updated develop. Both ROI now gives same value. Thanks matthias

**Comment by xmatthias** [comment]
What you didn't realize is that there's another bug hidden in your database file.

calling `/status 1` will not send the message - as the message becomes too long.
I'll be fixing that anyway - just so you're aware why i didn't set the commit to auto-close the issue ;)

**Comment by stash86** [comment]
Actually I'm aware of that, but that's another issue that I'm still thinking how to fix it 😁

**Comment by xmatthias** [comment]
it's fixed since this morning ...

**Comment by stash86** [comment]
I haven't check today's commits. Thanks a lot
