### ISSUE TITLE
Binance Futures Trading in Backtesting

### ISSUE THREAD

**Issue by dennislau25** [freqtrade/freqtrade#7179]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: Python 3.10.5
  * CCXT version: 1.91.55
  * Freqtrade Version:  freqtrade docker-9df10c6b
  
## Your question

Hi! I have tried to do futures trading on the Binance Exchange (since it says futures trading are experimental in the documentation), but it seems like it's not available yet:

2022-08-05 00:24:44,099 - freqtrade - ERROR - Freqtrade does not support  futures on Binance

So is futures trading not live yet for Binance or did I not have the correct verion?

**Comment by xmatthias** [comment]
The version seems correct - but most likely it's some configuration error.

best use `freqtrade new-config` - selecting futures for binance to ensure that the configuration is complete.

**Comment by xmatthias** [comment]
Assuming this got fixed by following the advise above.

Feel free to comment below / reopen if that's not the case.
