### ISSUE TITLE
Error when calculating Bollinger bands in informative_pairs

### ISSUE THREAD

**Issue by JiSeopHyun** [freqtrade/freqtrade#7185]
## Describe your environment

  * Operating system:  docker-29e41cc8
  * Python Version: in to docker-29e41cc8
  * CCXT version: in to docker-29e41cc8
  * Freqtrade Version: in to docker-29e41cc8

```python 

    def informative_pairs(self):
        return [(f"BTC/USDT", '1h'),("ETH/USDT", "1h")]
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        frames = [dataframe]     
        if self.dp:
                    informative =[]
                    inf_tf = '1h'
                    informative_BTC = self.dp.get_pair_dataframe(pair=f"BTC/USDT", timeframe=inf_tf)

                    bollinger_BTC = ta.BBANDS(informative_BTC['close'],timeperiod=20, nbdevup=2.0, nbdevdn=2.0)
                    informative_BTC['BTC_bb_lowerband'] = bollinger_BTC['lowerband']
                    informative_BTC['BTC_bb_middleband'] = bollinger_BTC['middleband']
                    informative_BTC['BTC_bb_upperband'] = bollinger_BTC['upperband']
```

### Relevant code exceptions or logs
```
2022-08-06 04:00:41 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error list indices must be integers or slices, not str calling <bound method IStrategy._analyze_ticker_internal of <FCciRsiUpDn.FCciRsiUpDn object at 0x7f5ca5ccda50>>
Traceback (most recent call last):
  File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/strategy/interface.py", line 680, in _analyze_ticker_internal
    dataframe = self.analyze_ticker(dataframe, metadata)
  File "/freqtrade/freqtrade/strategy/interface.py", line 659, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/freqtrade/freqtrade/strategy/interface.py", line 1160, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/FCciRsiUpDn.py", line 257, in populate_indicators
    informative_BTC['BTC_bb_lowerband'] = bollinger_BTC['lowerband']
TypeError: list indices must be integers or slices, not str
```

**Comment by xmatthias** [comment]
The error got nothing to do with using informative pairs or not, but with how BBANDS is used.

ta.BBANDS has different return types, depending on the input (if the input is a dataframe or a series).

As you're passing in a series, `ta.BBANDS` returns a tuple of 3 items, not a dataframe with multiple columns (like qtpylib does).

As such - the correct usage for `ta.BBANDS()` will be something around `upper, middle, lower = ta.BBANDS(dataframe['close'], ...)` - and then assigning `upper`, `middle` and `lower` directly to the informative dataframe.

Alternatively, you can omit the `['close']` in your line - and the rest of the assignments should work.

**Comment by JiSeopHyun** [comment]
Okay. thank you!
It seems that the error form in "populate_indicators" and "if self.dp:" is slightly different.
  close must be omitted so that there is no error.
Is it possible to apply a strategy applied according to the variable by declaring a variable that depends on the market situation in the class?
  Hyperopt is going to take a lot of time.

**Comment by xmatthias** [comment]
everything you can code in python, you should be able to do within the strategy.

How you're detecting which market situation is then up to you - and opinions on that will widely vary.

**Comment by JiSeopHyun** [comment]
A bearish or bullish signal in a market is one record in a pandas dataframe. How can I remember this as a value after that record?
Do I have to put the loop inside "populate_indicators" if I want to count and record it? Is "populate_indicators" executed at the beginning of the program, so it can't be reflected later? Should I put it inside "populate_entry_trend" or "populate_exit_trend"?

**Comment by xmatthias** [comment]
The [documentation](https://www.freqtrade.io/en/stable/bot-basics/#bot-execution-logic) has you covered - and will explain how things work in live and in backtesting (and how they differ).

I'd recommend to read through the documentation once from top to bottom at least once (or at least fly over the sections to roughly know what the documentation covers). This will help you in the long run - as you'll know where to find the answers already.
