### ISSUE TITLE
Active pair whitelist is empty (gateio)

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#7186]
* Operating system: __Docker__
  * Python Version: _3____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __ docker-4c68bec1__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Attempting to trade futures on gateio return log "Active pair whitelist is empty"

**list the market suggest entering "ETH_USDT"**

```
Exchange Gate.io has 1 active market with ETH as base currency and with USDT as quote currency:
+----------+----------+--------+---------+----------+--------+----------+----------+------------+
|       Id |   Symbol |   Base |   Quote |   Active |   Spot |   Margin |   Future |   Leverage |
|----------+----------+--------+---------+----------+--------+----------+----------+------------|
| ETH_USDT | ETH/USDT |    ETH |    USDT |     True |   Spot |   Margin |          |          1 |
+----------+----------+--------+---------+----------+--------+----------+----------+------------+
```
    "trading_mode": "futures",
    "margin_mode": "isolated",
....

    "exchange": {
        "name": "gateio",
        "key": "xxx",
        "secret": "xxx",
        "ccxt_config": {},
        "pair_whitelist": ["ETH_USDT"
        ],
        "pair_blacklist": [
        ]
    },

Any idea what is causing this? Is that mean the trading will be disabled for this pair on gateio?

**Comment by xmatthias** [comment]
Your pair definition is wrong.
For futures - you'll need to use `base/quote:settle` - therefore your pair definition becomes `ETH/USDT:USDT`.

You can try this yourself by using `freqtrade list-markets --exchange gate --trading-mode futures --quote USDT --base ETH ` (note the `--tradeing-mode futures` flag to show you futures markets).
Without this flag, you'll get spot markets - as your output also shows - it doesn't list this pair as futures market.

While `ETH_USDT` is the exchange ID - we're using the Symbol of the output.


```
+----------+---------------+--------+---------+----------+--------+----------+----------+------------+
|       Id |        Symbol |   Base |   Quote |   Active |   Spot |   Margin |   Future |   Leverage |
|----------+---------------+--------+---------+----------+--------+----------+----------+------------|
| ETH_USDT | ETH/USDT:USDT |    ETH |    USDT |     True |        |          |   Future |          1 |
+----------+---------------+--------+---------+----------+--------+----------+----------+------------+
```

**Comment by darioneto** [comment]
that works, thanks much
