### ISSUE TITLE
ccxt.base.errors.DDoSProtection: binance 418 I'm a teapot 

### ISSUE THREAD

**Issue by tainger2** [freqtrade/freqtrade#7187]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

{"code":-1003,"msg":"Way too much request weight used; IP banned until 1659761931230. Please use the websocket for live updates to avoid bans."}

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting/not filling out the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Most likely, you're using a config which defines (a wrong) `rateLimit`.
current versions do not require rateLimit - and especially for binance, it shouldn't be set, as ccxt does a good job of using the proper weight.

If you're using multiple bots from the same IP - you'll need to scale out horizontally - and use multiple source IP's for your requests.

**Comment by xmatthias** [comment]
Assuming you got this figured out with the pointers above.

Feel free to comment below if that's not the case.
