### ISSUE TITLE
exit trand by ema

### ISSUE THREAD

**Issue by par3** [freqtrade/freqtrade#7188]
## Describe your environment

  * Operating system: ____win10
  * Python Version: _____3.10.5 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ 2022.07 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

i need to exit trend when ema7 bigger than ema25
but the folowing code strategy does not work

        dataframe.loc[
            (
                # Signal: EMA7 crosses above 25
                (qtpylib.crossed_above(dataframe['ema7'], dataframe['ema25'])) |
                (dataframe['ema7'] > dataframe['ema25']) 
            ),
            'exit_short'] = 1

i need or condition

**Comment by xmatthias** [comment]
The code itself looks fine - and this will be an OR condition (although this combination of OR does not make sense - as only the 2nd condition is really relevant.

You're however only exiting shorts with that code (only exit_short is set) - so this will not apply to long trades.

**Comment by par3** [comment]
```
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)

        # # EMA - Exponential Moving Average
        dataframe['ema7'] = ta.EMA(dataframe, timeperiod=7)
        dataframe['ema21'] = ta.EMA(dataframe, timeperiod=21)
        dataframe['ema25'] = ta.EMA(dataframe, timeperiod=25)

        return dataframe   


 def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
 
         dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['ema7'], dataframe['ema21'])) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'enter_long'] = 1

         dataframe.loc[
            (
                (qtpylib.crossed_below(dataframe['ema7'], dataframe['ema21'])) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'enter_short'] = 1

         return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (
                # Signal: EMA7 crosses below 25
                (qtpylib.crossed_below(dataframe['ema7'], dataframe['ema25'])) |
                (dataframe['ema7'] < dataframe['ema25']) 
            ),
            'exit_long'] = 1

        dataframe.loc[
            (
                # Signal: EMA7 crosses above 25
                (qtpylib.crossed_above(dataframe['ema7'], dataframe['ema25'])) |
                (dataframe['ema7'] > dataframe['ema25']) 
            ),
            'exit_short'] = 1
        return dataframe
        
```
1-the exit does not work at all
2-entry has misstake samo times, i need to enter trend when closed candle had condition

**Comment by xmatthias** [comment]
Your enter conditions are "crossed" - so it'll enter whenever the 2 lines cross (actually on the next candle).
for exits - you'll have to make sure that flags like "use_exit_signal" are active. 

Technically there's nothing wrong with the signals - although they may collide (entry and exit) - causing the entry signal to be ignored.

Best use some plotting (freqUI, plot-dataframe) to look at the signals in detail to determine what you don't like about them.

**Comment by par3** [comment]
in many cases bot position  reach up to 5% profit
is there any way to save profit?
for example profit reach 12% and exit_signal event fire when profit decrease to 3% 
i think roi does not support this case

**Comment by xmatthias** [comment]
It's up to you to develop a strategy that fit's your needs.

you can obviously use ROI to take profit once you reach a certain profit level. 
alternatives are trailing stoploss - which triggers once the trade drops down from a certain prior high.

If this will really suit your strategy or not is up to you.
You can also invent some more detailed exit strategies by using [callbacks](https://www.freqtrade.io/en/latest/strategy-callbacks/) - where you get to decide yourself where /how to place a trailing stop - or when exactly to exit.
with the develop version, you can also use partial exits through the [adjus_trade_position callback](https://www.freqtrade.io/en/latest/strategy-callbacks/#adjust-trade-position).

It's however often dangerous to look at a trade and say "oh, i lost 3% on this trade as i didn't sell at 12%" (what the above comment sounds like) - but the next trade will drop down from 11.8% - and therefore would not fall into this category.

**Comment by par3** [comment]
let me explain with example
bot opened a position at 09:48 am
at 10:07 am profit was 26%
at 10:16 exit_signal fire event and position close with 7% profit

i need to detect when its losing profit close position with 25% profit

**Comment by xmatthias** [comment]
The links above do provide you with the information to do this.
It's however up to you to come up with a strategy that fits your desires - and such changes should be thoroughly tested to ensure you're not tuning for one trade - while then losing out on 20 others.

**Comment by par3** [comment]
thants a lot, could you give me additional link
how could i calculate that i'm loosing my current profit pls (using as a exit_signal)

**Comment by xmatthias** [comment]
That's up to you to determine (what defines "i'm now losing profit").

As mentioned above - there's several ways to approach this (all are documented in the links above) - but you'll need to take the time to research these. 

You'll however not find a solution where it'll sell at the "high point" - as that would mean a pretty tight trailing stop - which will have triggered LONG before you reached the profit you do now.
