### ISSUE TITLE
Turn off strategy.

### ISSUE THREAD

**Issue by BatmanPDX** [freqtrade/freqtrade#719]
Is there a way to just use the config file for my strategy? I don't want to use any default strategy file or any other strategy indicators.  I Just want to buy at this ask price and sell for whatever percent.

**Comment by xmatthias** [comment]
so you would like to insert a certain (hardcoded) price for 1 specific pair - and sell for X times that price?

**Comment by BatmanPDX** [comment]
yes exactly

**Comment by BatmanPDX** [comment]
yes exactly, I want to set a buy-limit, based on current price and then just have it sell for whatever sell-limit

**Comment by xmatthias** [comment]
technically, you could write a specific strategy for this case - and hardcode the price into the strategy.
this however is not very dynamic as you'd need to change the strategy very often ... 

The bot is made for frequency trading - which would not work like this (you have 1 fixed price - and ROI sell limits...).

**Comment by gcarq** [comment]
I'm closing this
