### ISSUE TITLE
conda: Failed building wheel for py_find_1st in conda

### ISSUE THREAD

**Issue by AchmadFathoni** [freqtrade/freqtrade#7193]
## Describe your environment

  * Operating system: ArchLinux
  * Python Version: 3.10.0 (`python -V`)
  * CCXT version: 1.91.55 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 78e129034 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. Install freqtrade using conda by following documentation
  2. Run `conda env create -n freqtrade-conda -f environment.yml`

  
### Observed Results:

```
Pip subprocess error:
  error: subprocess-exited-with-error
  
  × Building wheel for py_find_1st (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      /tmp/pip-build-env-xew6hzkw/overlay/lib/python3.10/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/utils_find_1st
      copying utils_find_1st/__init__.py -> build/lib.linux-x86_64-cpython-310/utils_find_1st
      running build_ext
      check for clang compiler ... no
      building 'find_1st' extension
      creating build/temp.linux-x86_64-cpython-310
      creating build/temp.linux-x86_64-cpython-310/utils_find_1st
      gcc -pthread -B /opt/miniconda3/envs/freqtrade/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/miniconda3/envs/freqtrade/include -fPIC -O2 -isystem /opt/miniconda3/envs/freqtrade/include -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_13_API_VERSION -I/tmp/pip-build-env-xew6hzkw/overlay/lib/python3.10/site-packages/numpy/core/include -I/opt/miniconda3/envs/freqtrade/include/python3.10 -c utils_find_1st/find_1st.cpp -o build/temp.linux-x86_64-cpython-310/utils_find_1st/find_1st.o
      g++ -pthread -B /opt/miniconda3/envs/freqtrade/compiler_compat -shared -Wl,-rpath,/opt/miniconda3/envs/freqtrade/lib -Wl,-rpath-link,/opt/miniconda3/envs/freqtrade/lib -L/opt/miniconda3/envs/freqtrade/lib -Wl,-rpath,/opt/miniconda3/envs/freqtrade/lib -Wl,-rpath-link,/opt/miniconda3/envs/freqtrade/lib -L/opt/miniconda3/envs/freqtrade/lib build/temp.linux-x86_64-cpython-310/utils_find_1st/find_1st.o -o build/lib.linux-x86_64-cpython-310/utils_find_1st/find_1st.cpython-310-x86_64-linux-gnu.so
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: /usr/lib/libm.so.6: unknown type [0x13] section `.relr.dyn'
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: skipping incompatible /usr/lib/libm.so.6 when searching for /usr/lib/libm.so.6
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: /usr/lib/libm.so.6: unknown type [0x13] section `.relr.dyn'
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: skipping incompatible /usr/lib/libm.so.6 when searching for /usr/lib/libm.so.6
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: cannot find /usr/lib/libm.so.6
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: /usr/lib/libm.so.6: unknown type [0x13] section `.relr.dyn'
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: skipping incompatible /usr/lib/libm.so.6 when searching for /usr/lib/libm.so.6
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: /usr/lib/libm.so.6: unknown type [0x13] section `.relr.dyn'
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: skipping incompatible /usr/lib/libm.so.6 when searching for /usr/lib/libm.so.6
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: /usr/lib/libmvec.so.1: unknown type [0x13] section `.relr.dyn'
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: skipping incompatible /usr/lib/libmvec.so.1 when searching for /usr/lib/libmvec.so.1
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: /usr/lib/libmvec.so.1: unknown type [0x13] section `.relr.dyn'
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: skipping incompatible /usr/lib/libmvec.so.1 when searching for /usr/lib/libmvec.so.1
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: cannot find /usr/lib/libmvec.so.1
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: /usr/lib/libmvec.so.1: unknown type [0x13] section `.relr.dyn'
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: skipping incompatible /usr/lib/libmvec.so.1 when searching for /usr/lib/libmvec.so.1
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: /usr/lib/libmvec.so.1: unknown type [0x13] section `.relr.dyn'
      /opt/miniconda3/envs/freqtrade/compiler_compat/ld: skipping incompatible /usr/lib/libmvec.so.1 when searching for /usr/lib/libmvec.so.1
      collect2: error: ld returned 1 exit status
      error: command '/usr/bin/g++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for py_find_1st
ERROR: Could not build wheels for py_find_1st, which is required to install pyproject.toml-based projects

failed

CondaEnvException: Pip failed

```

Conda uses ArchLinux  new 12.1.1 `/usr/bin/g++`

### Possible Fix
Use older g++ in `cxx-compiler` package from conda-forge. Version 11.3.0 is working fine.

**Comment by stash86** [comment]
or use this .yml
```
name: freqtrade
channels:
  - conda-forge
# - defaults
dependencies:
# 1/4 req main
#    - python>=3.7
    - python=3.9
    - pip
    - numpy
    - pandas
    - cryptography
    - aiohttp
    - SQLAlchemy
    - python-telegram-bot
    - arrow
    - cachetools
    - requests
    - urllib3
    - wrapt
    - jsonschema
#    - TA-Lib
    - tabulate
    - jinja2
    - python-blosc
    - blosc
    - sdnotify
    - fastapi
    - uvicorn
    - pyjwt
    - colorama
    - questionary
    - prompt-toolkit
    - pytables
    - python-rapidjson

    # ============================
    # 2/4 req dev


    # ============================
    # 3/4 req hyperopt

    - scipy
    - scikit-learn
    - filelock
    - scikit-optimize
    - joblib
    - progressbar2
    - psutil
    # ============================
    # 4/4 req plot

    - plotly
    - jupyter

    - pip:
        - pycoingecko
        - py-find-1st
        - ccxt==1.53.72
        - TA-lib
        - freqtrade==2021.7 # comment this line for dev version
        - technical
        - pandas-ta
        - ta
        - finta
        # - -e . # use this line for dev version, need to use first: git clone https://github.com/freqtrade/freqtrade.git .
   
```

Moving py-find-1st and ta-lib to pip installation. Working fine for me last time I'm using it

**Comment by xmatthias** [comment]
To be honest, i don't think we can fix this from a freqtrade point of view.

Moving the dependency to pip will work as long as build dependencies are installed - but if they're not (or the wrong ones) - it'll fail just as much.

it's py_find_1st which is failing in a conda environment - so this should most likely be reported to the maintainer of py_find_1st in the corresponding [github repository](https://github.com/roebel/py_find_1st/issues).

---

@stash86 do we have more problems with conda installs? to me, it's hardly used by anyone - so if we have more problems, i'm tempted to remove support for that completely as it seems to not provide the stability it promises.

**Comment by stash86** [comment]
> To be honest, i don't think we can fix this from a freqtrade point of view.
> 
> Moving the dependency to pip will work as long as build dependencies are installed - but if they're not (or the wrong ones) - it'll fail just as much.
> 
> it's py_find_1st which is failing in a conda environment - so this should most likely be reported to the maintainer of py_find_1st in the corresponding [github repository](https://github.com/roebel/py_find_1st/issues).
> 
> @stash86 do we have more problems with conda installs? to me, it's hardly used by anyone - so if we have more problems, i'm tempted to remove support for that completely as it seems to not provide the stability it promises.

Personally, I have moved to docker now, since there isn't much benefit to use conda for me. Don't think anyone still using it as well. It was used when people started using the oracle free ARM vps because the script installation always failed back then (I haven't test it again recently). But hey we have docker now.

**Comment by AchmadFathoni** [comment]
I use conda because I never use docker. I will not complain if conda support removed. I'm not sure about other people. You can close this issue.

**Comment by xmatthias** [comment]
To me, there's better alternatives to conda on linux (specifically pyenv) - which allows you to have multiple versions of python - while still using a standard python installation.
That said - you can also use the manual install method within a conda environment (basically using `pip install -r requirements.txt` - followed by `pip install -e .` - without using the environment file (which is specifically tailored to be working for windows installations).

---

As mentioned above - i'm not sure how this issue could be fixed at the `environment.yml` level (i'm not a regular conda user ...).
To me, such a decision (who get's to compile my stuff) needs to be taken at the library level (in the libraries setup / pyproject.toml files) - which makes this the wrong place to report issues about this - as `py_find_1st` is just a dependency of freqtrade - not a project we have influence in (no more than as user, anyway).

It's also difficult for us to report it - as you're the one who can reproduce the issue easily with your configuration / setup - and i think it's pretty specific to the setup you have.

It might even be a conda level problem - as it seems like g++ is used from the system (no conda env prefix) - while ld is used from a conda environment - which could lead to a missmatch in versions / compatibility.

**Comment by xmatthias** [comment]
I'm on Archlinux also - and just tried a miniconda install (miniconda3, 4.7.12) with the command you provided.
You're right that it fails - but it seems to be a conda problem (when running from within a conda python).

Creating the wheel outside of conda works just fine, so the toolchain of archlinux can clearly install this - unless conda is messing with it.


@AchmadFathoni if you're familiar with conda (and it's problems) - maybe you can help in finding a solution to this?
It seems like the problem is indeed the usage of "ld" from the conda environment, but g++ from the system, leading to a miss-matched installation somehow (the key seems to be `freqtrade-conda/compiler_compat/ld: cannot find /usr/lib/libm.so.6`).

It seems like conda somehow has problems with this - but the internet seems sparse on information for this.
The only issue i've found is https://github.com/conda/conda-build/issues/2803 - where the solution seems to be to use a different library - which is not really an actionable help.

**Comment by xmatthias** [comment]
Installing py-find-1st from conda forge seems to work around this problem.

**Comment by AchmadFathoni** [comment]
I found another solution without changing the py-find-1st source:

Just delete or rename the `compiler_compat/ld`.

[Source](https://github.com/ContinuumIO/anaconda-issues/issues/11152) (different error but same culprit)

**Comment by AchmadFathoni** [comment]
> I found another solution without changing the py-find-1st source:
> 
> Just delete or rename the `compiler_compat/ld`.
> 
> [Source](https://github.com/ContinuumIO/anaconda-issues/issues/11152) (different error but same culprit)

Or from developer side, putting "gcc_linux-64" in the list of dependencies of the environment.yml solves the problem.

**Comment by xmatthias** [comment]
trying to put that into the environment.yml file did not yield a successful install.

however having `py-find-1st` install from conda-forge seems to work just fine, so we'll keep it as is now.

**Comment by AchmadFathoni** [comment]
I've same error with ta-lib from 2022.9 when running `pip install -U -r requirements-dev.txt` in clean conda environment. The 'gcc_linux-64' doesn't fix it so I guess I just remove `compiler_compat/ld` & get done with it.
