### ISSUE TITLE
[Errno 2] No such file or directory: '/freqtrade/user_data/logs/freqtrade.log'

### ISSUE THREAD

**Issue by Mo7mud** [freqtrade/freqtrade#7195]
## Describe your environment

  * Operating system:  windows 10 and docker
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2022.7
  

## Describe the problem:

Container keeps restarting

### Steps to reproduce:

  Just followed the get starting with docker guide 
  
### Observed Results:

Container keeps restarting
Container continue to work.
### Relevant code exceptions or logs

  ```
  2022-08-07 07:50:51,550 - freqtrade.worker - INFO - Starting worker 2022.7
2022-08-07 07:50:51,550 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/config.json ...
2022-08-07 07:50:51,551 - freqtrade.commands.trade_commands - ERROR - [Errno 2] No such file or directory: '/freqtrade/user_data/logs/freqtrade.log'
2022-08-07 07:50:51,552 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 49, in _init
    self._config = Configuration(self._args, None).get_config()
  File "/freqtrade/freqtrade/configuration/configuration.py", line 42, in get_config
    self.config = self.load_config()
  File "/freqtrade/freqtrade/configuration/configuration.py", line 84, in load_config
    self._process_logging_options(config)
  File "/freqtrade/freqtrade/configuration/configuration.py", line 120, in _process_logging_options
    setup_logging(config)
  File "/freqtrade/freqtrade/loggers.py", line 123, in setup_logging
    handler_rf = RotatingFileHandler(logfile,
  File "/usr/local/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/local/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
   FileNotFoundError: [Errno 2] No such file or directory: '/freqtrade/user_data/logs/freqtrade.log'
  ```

**Comment by xmatthias** [comment]
on windows, you'll need to be careful how your docker installation is configured.

The default compose file assumes to expose the directory "user_data" - located within the directory of the compose file.
This directory should be auto-created as part of the guide (after running the `create-userdir` command).

If this was not created, then this would hint at a problem with the mount directories (the most common problem on windows).

Docker for windows requires you to enable this directory to be "mountable". The default for this is i think located in the user's home directory - so the most likely problem here is that the mount fails / is prevented - which will lead to this problem.

**Comment by moinonin** [comment]
I have encountered this issue before and I solved by manually creating the logfile by running:
`
touch ./user_data/logs/freqtrade.log
`
In the relevant directory

**Comment by Mo7mud** [comment]
> on windows, you'll need to be careful how your docker installation is configured.
> 
> The default compose file assumes to expose the directory "user_data" - located within the directory of the compose file. This directory should be auto-created as part of the guide (after running the `create-userdir` command).
> 
> If this was not created, then this would hint at a problem with the mount directories (the most common problem on windows).
> 
> Docker for windows requires you to enable this directory to be "mountable". The default for this is i think located in the user's home directory - so the most likely problem here is that the mount fails / is prevented - which will lead to this problem.

Directory auto created and the file exists and not in home directory, it's in another partition.
It was permissions problem.

Now it's running but front end doesn't work although I enabled it.
This is my config:

```

{
    "max_open_trades": 3,
    "stake_currency": "USDT",
    "stake_amount": 100,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "cancel_open_orders_on_exit": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "bid_strategy": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": true,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "570f6110d9fe9800537f43f6e17fc6cc80395bad5bd90ccf7f4c83bfd4b637ad",
        "CORS_origins": [],
        "username": "trader",
        "password": "821975"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```
When I click on OPEN IN BROWSER   I get this page:

![image](https://user-images.githubusercontent.com/12565380/183311262-d9efc3ec-077a-4c8d-b13d-db91c959e3b9.png)

**Comment by stash86** [comment]
Are the docs not clear enough?

https://www.freqtrade.io/en/stable/rest-api/#configuration-with-docker

**Comment by xmatthias** [comment]
For docker installations - `"listen_ip_address": "127.0.0.1",` needs to be `"listen_ip_address": "0.0.0.0",`, otherwise the port won't be correctly exposed.

**Comment by Mo7mud** [comment]
> Are the docs not clear enough?
> 
> https://www.freqtrade.io/en/stable/rest-api/#configuration-with-docker

Sorry didn't see it


@xmatthias 
> For docker installations - `"listen_ip_address": "127.0.0.1",` needs to be `"listen_ip_address": "0.0.0.0",`, otherwise the port won't be correctly exposed.

Thank you very much

**Comment by AlanTrudor** [comment]
`mkdir -p ./user_data/logs/ ` solved it for me

**Comment by badrul1** [comment]
Windows user here. I just created the folder and an empty log file and it worked for me. Just took me on to the next problem about missing SampleStrategy file...Get ready for that one!
