### ISSUE TITLE
Enhancement:  Auto Reload Configuration

### ISSUE THREAD

**Issue by moosylog** [freqtrade/freqtrade#72]
Reload configuration files itself periodically without restarting would be a very interesting feature.

I'm running on an ARM Cubox and it takes quite some time to reload the complete Python stack.

**Comment by shusso** [comment]
@moosylog would you prefer periodically polling the configs or could adding an telegram option for reloading the config e.g. `/reload_conf` be viable?

**Comment by moosylog** [comment]
Hi Samuel,

Cool. Think a /reload_conf would probably be best so it's not impact
performance and io is minimized.

Cheers,

Moosy

**Comment by gcarq** [comment]
In addition to `/reload_conf` I would also like to use the `SIGHUP` signal. That way you could also set up a cronjob to reload the config periodically

**Comment by xmatthias** [comment]
Closing this now as #886 implements a `/reload_conf` switch.
