### ISSUE TITLE
Suggestion about multiple entry exit conditions  

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#7205]
Could you please advise what would be the most efficient config approach with multiple conditions of entry and exit? At the moment I validate it in the one  dataframe.loc[]  pandas statement with the OR operator however the outcome of each time the trade is recorded results with the one and same tag for either of the conditions. What would be a better-recommended method of the same approach which would return the corresponding tag with each trade condition taking place? 

For example 

```
def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
    dataframe.loc[
        (
            Condition1 

        ),

        ['sell', 'exit_tag']] = (1, 'some_exit_tag1')
OR
        (
            Condition2
        ),
        ['sell', 'exit_tag']] = (1, 'some_exit_tag2')
OR
        (
            Condition3

        ),
        ['sell', 'exit_tag']] = (1, 'some_exit_tag3')
    return dataframe
```

**Comment by xmatthias** [comment]
You can use `.loc[]` multiple times in a row with different masks (conditions) - so different conditions have different exit tags.
The mask (condition) will filter the rows - and only write to the rows the mask covers - leaving all other rows "as they were".

This is only problematic if the signals collide (more than one signal is active at any time) - in which case the "last" tag would win. I'm not sure it's relevant though. For example - condition2 and condition3 were active, you'd only get `some_exit_tag3`.

**Comment by darioneto** [comment]
Thanks for your reply, I've added as you suggested and that seems to work so far :-)
