### ISSUE TITLE
Gateio AUTO_INITIAL_SIZE_OVER_RANGE

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#7206]
Freqtrade was unable to close the trade. The only solution was to close it manually on exchange. Error log below:

## Describe your environment

  * Operating system: _Docker___
  * Python Version: __3.10.6___ (`python -V`)
  * CCXT version: __1.91.55___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __docker-e48e8223__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
 

```
Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1156, in stoploss
    order = self._api.create_order(symbol=pair, type=ordertype, side=side,
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/gate.py", line 2950, in create_order
    response = getattr(self, method)(self.deep_extend(request, params))
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 497, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2621, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2618, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 633, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ftuser/.local/lib/python3.10/site-packages/ccxt/gate.py", line 4407, in handle_errors
    raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: gateio {"label":"AUTO_INITIAL_SIZE_OVER_RANGE","message":"invalid argument: initial.size out of range"}
```
Any idea what is this related to?

**Comment by xmatthias** [comment]
not really (never seen this error) - and  the provided log is too truncated contain at anything useful (it's not even the full exception traceback).

We'll need the full error - as well as several lines before that.

Also - if the error repeats itself (or is repeating constantly) - please enable `exchange.log_responses = true` to get a better glimpse on the exchange responses (most likely prior to this error).

**Comment by darioneto** [comment]
The error kept on looping with the same content I sent out before. I've deleted the orphaned trade so will have to wait until I get this again and capture it with "exchange.log_responses"

**Comment by xmatthias** [comment]
As the log is incomplete - and the error is also not mentioned on the [gateio documentation page](https://www.gate.io/docs/developers/apiv4/en/#label-list) - this will be near impossible to investigate further at this point.

The whole internet doesn't seem to know about "AUTO_INITIAL_SIZE_OVER_RANGE" - aside from this issue.

One possibility is to contact gateio support about this (asking for this specific error) - but for now, the most likely cause is some experimentation / gone wrong deployment on their side, which was causing this error.

Feel free to reopen / comment below if the error reappears (please with complete log).
