### ISSUE TITLE
Callback after order canceled

### ISSUE THREAD

**Issue by medenlin** [freqtrade/freqtrade#7207]
## Describe the enhancement

I think that in some cases a callback after canceling an entry or exit order would be useful. Sometimes the strategy needs to know that the order has been cancelled (or may be not fulfilled).
Or does the Freqtrade already have an easy way to keep track of this?

**Comment by xmatthias** [comment]
i'm not sure what the strategy would do with this information.

If it's a simple callback (just informative, no return value) - there's no action you can take. So i wonder what the strategy would do with the canceled information.
Usually (assuming the sell signal is still there) - you'll replace the order with a new one.

Also - all past orders (cancelled or filled) are available in trade-based callbacks (callbacks that have a `trade` argument) via `trade.orders` (it's an array) - so the information is there for "actionable" callbacks to actually use this information.

**Comment by medenlin** [comment]
Yes, I use this for informative purposes, or rather, to transfer this event to another software through a file. Right now I'm tracking canceled orders via a `Trade.get_trades()` function in `bot_loop_start()` callback. I understand that this is a very difficult and not optimal solution. But with such a callback, it would be more convenient to do it.

**Comment by xmatthias** [comment]
That's an edge-case usecase which will only serve you / your usecase - but is not really applicable to a wider audience.

i don't see us adding this unless we have some compelling reason for it (your's is not, sorry).

you could also use the "cancel_exit" callback, and log when you initiate the cancellation - You may obviously get a partially filled order - but that'd be another point of discussion for a callback - should such an order be sent or not (it's not fully cancelled - so maybe not).
