### ISSUE TITLE
Limit trailing stop loss timeout unfilled

### ISSUE THREAD

**Issue by sbmnk** [freqtrade/freqtrade#7208]
Hello, I am having a problem with a behaviour when an exit order times out.

Context:
I am using a trailing stop loss to exit a trade in dry run with a limit stop loss order. 

Current behaviour:
Once the price hits trailing stop loss the bot places an exit limit order at a price say of 10%. The price drops to 8% and the order times out. A new exit order is placed again at 10%. 

Problem:
This leads to unrealistic orders being constantly spammed by a bot without any chance of having them filled rather than making its best effort to exit the trade. This results in my telegram looking like this 
![image](https://user-images.githubusercontent.com/32957648/183691704-f5c71e9d-e454-465c-be2f-d0751961a0e3.png) 
Notice that all of the exits are at the same price even though in status table this order is way off the exit price 
12 S      UNI/USDT**  4 h      24.15% 

The current way it works makes the timeout simply redundant, it is as good as if it was just the initial order all the way. 

Expected behaviour:
Once the price hits trailing stop loss the bot places an exit limit order at a price say of 10%. The price drops to 8% and the order times out. A new exit order is placed again at 8%. (i.e. the second order after timeout is placed based on current conditions rather than just repeating the initial order) 

I am currently submitting this as a question since there may be some config that I have missed but potentially this could be a bug.

**Comment by sbmnk** [comment]
Also, similar behaviour has happened with a normal stoploss (i.e. the price would slip but the orders keep getting placed exactly at stop loss even after timeout instead of constantly updating)

**Comment by xmatthias** [comment]
This will only happen for dry-runs that use stoploss-on-exchange (a mostly pointless setup which is there mostly for compatibility - as the filling of this still happens within freqtrade).

Regular stoplosses (trades started without stoploss on exchange active) will not encounter this - and neither will live.

The guilty lines are here.
https://github.com/freqtrade/freqtrade/blob/8a18609be4b7ce9c7c0edf7ab5fa885d6f202815/freqtrade/freqtradebot.py#L1475-L1477

**Comment by sbmnk** [comment]
Thanks a lot ! have been puzzling myself over this problem for a long time !
