### ISSUE TITLE
Hyperopt can't find 'buy' and 'sell' parameters to optimize, but strategy runs perfectly

### ISSUE THREAD

**Issue by BuddhiLW** [freqtrade/freqtrade#7210]
## Describe your environment

  * Operating system: Artix Linux, V5.18.16
  * Python Version: 3.10.5 (`python -V`)
  * CCXT version: no version, using docker (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.7 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Context**, the strategy is well-written python:
I'm using a strategy that runs smoothly on dry-run. Also, I have used it two ago with real money, successfully. Now, I'm back making updates to my algorithms etc.

**What happened** is:
When I try to optimize the parameters, I get that I do not use 'buy' and 'sell' parameters (which is nonsense).

**Command:**
```shell
sudo docker-compose run --rm freqtrade hyperopt -s bbrsi7sortino --hyperopt-loss SharpeHyperOptLoss -e 10 -j 4
```

Strategy =bbrsi7sortino= **snippet of buy and sell** declaration on my strategy (bbrsi7sortino),
```python
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                (dataframe['rsi'] > 20) &
                (dataframe["close"] < dataframe['bb_lowerband'])
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the sell signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                (dataframe['rsi'] > 50) &
                (dataframe["close"] > dataframe['bb_middleband1'])
            ),
            'sell'] = 1

        return dataframe
```

Error:
```shell
2022-08-10 05:57:37,351 - freqtrade - ERROR - The 'buy' space is included into the hyperoptimization but no parameter for this space was not found in your Strategy. Please make sure to have parameters for this space enabled for optimization or remove the 'buy' space from hyperoptimization.
2022-08-10 05:57:37,427 - freqtrade.exchange.exchange - INFO - Closing async ccxt session.
```

If I use my old hyperopt file, by:
```shell
sudo docker-compose run --rm freqtrade hyperopt -s bbrsi7sortino --hyperopt bbrsiopt --hyperopt-loss SortinoHyperOptLossDaily -i 15m -j 6 -e 20
```

 I receive the error:
```
2022-08-10 06:14:26,223 - freqtrade - ERROR - Using separate Hyperopt files has been removed in 2021.9. Please convert your existing Hyperopt file to the new Hyperoptable strategy interface
```

I read the documentation and couldn't understand how I can "convert your existing Hyperopt file to the new Hyperoptable strategy interface"; didn't find it anywhere.

I used to use any hyperopt, with no problem, with this exact command. What should I rewrite and how - help?

**Comment by xmatthias** [comment]
You'll need to define [parameters](https://www.freqtrade.io/en/stable/hyperopt/#hyperoptable-parameters) for the spaces you'd like to optimize (they obviously need to be used within the strategy to make a difference).

I'd strongly suggest to read through the whole [hyperopt documentation page](https://www.freqtrade.io/en/stable/hyperopt/) - and approach it as a new way to do hyperoptimization (a lot easier, with no manual work to transfer "result" from hyperopt to the strategy).

As you correctly point out - separate hyperopt files have been removed in 2021.9 (almost a year ago) - and have been deprecated several months prior to that.

Your parameters seem to simply be the "50" and "20" - the documentation covers this case specifically.

**Comment by BuddhiLW** [comment]
Perfectly, I spent like 6 hours, more or less, reading and testing and I already got back in track.

Thank you. Wish you a great reward for such an amazing project.

**Comment by KaiZheng2020** [comment]
What is the current state? There is no space in the following parameters from [hyperopt documentation page](https://www.freqtrade.io/en/stable/hyperopt/):

```
    buy_ema_short = IntParameter(3, 50, default=5)
    buy_ema_long = IntParameter(15, 200, default=60)
```
also there is no clear way how to hyperopt without the space definition.

**Comment by stash86** [comment]
Please open new issue instead of posting on old issue
