### ISSUE TITLE
freqtrade/setup.sh fails on install - Oracle VPS

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#7212]
## Describe your environment

  * Operating system: Ubuntu 22.04
  
## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  $ bash freqtrade/setup.sh -i
   
### Observed Results:

I ran freqtrade/setup.sh both as bash and sudo and it failed both times. It also failed the same way on another Oracle VPS instance I have running a separate copy of Freqtrade that I successfully installed from Docker.  On both VPS's it has installed the build_helpers directory but fails regardless. 

### Relevant code exceptions or logs

  ```
freqtrade/setup.sh: line 112: cd: build_helpers: No such file or directory
Quitting. Please fix the above error before continuing.
  ```

**Comment by xmatthias** [comment]
This has nothing to do with the VPS provider (oracle, or another one) - but with using the script from a wrong path.

`setup.sh` assumes the current path to be at the freqtrade repository level.

you'll therefore need to "cd" into the freqtrade directory first, and then run `bash setup.sh -i`.

This is also how it's in the [documentation](https://www.freqtrade.io/en/stable/installation/#script-installation).
Running `bash freqtrade/setup.sh -i` is not supported - and will not be working.
