### ISSUE TITLE
Run Bot on Margin Mode in Kucoin

### ISSUE THREAD

**Issue by mohammadhosseinzavvar** [freqtrade/freqtrade#7217]
freqtrade.exchange.exchange - INFO - Using Exchange "KuCoin"
freqtrade.commands.trade_commands - ERROR - Freqtrade does not support cross margin on KuCoin
freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'margin'}}

## Describe your environment
  * Freqtrade Version: 2022.7
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
While freqtrade does support kucoin as community effort - this is only true for spot markets.

Also, freqtrade does not support margin markets - only futures markets for selected exchanges.
The kucoin api is not very stable (the futures api is worse from what i hear) - unless that improves (complain to kucoin support?) and kucoin is moved to the fully supported exchanges - we will not be working on introducing additional modes (margin, futures) for kucoin - but will work on supported exchanges first.
