### ISSUE TITLE
Can the direction of entry exit be reversed?

### ISSUE THREAD

**Issue by JiSeopHyun** [freqtrade/freqtrade#7220]
Can the direction of entry exit be reversed?

  * Operating system:  docker-b427c7ff

-------------------------------------------------------
✳️ Binance: Exited 1000SHIB/USDT (#568)
Profit: 1.91% 
Enter Tag: SwingHighToSky2_Up_InL
Exit Reason: SwingHighToSky2_Up_OutS                                              <-------
Direction: Long                                                                                      <-------
Leverage: 
Amount: 
Open Rate: 0.01254300
Exit Rate: 0.01261300
Duration: 0:22:29 (22.5 min)

---------------------------------------------------------
strategy code

        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions), ['exit_short','exit_tag']
            ] = ( 1 , 'SwingHighToSky2_Up_OutS' )

Entered as long, but exited as short.

**Comment by xmatthias** [comment]
Trade direction can not be reversed.

While you can use partial exits now - the trade direction will stay the same - and a call to `adjust_trade_position()` which returns more than the amount you're owning will return in the position being fully closed.
