### ISSUE TITLE
How can I add the absolute stoploss to the dataframe ?

### ISSUE THREAD

**Issue by gaardiolor** [freqtrade/freqtrade#7223]
## Describe your environment

  * Operating system: Docker
  * Python Version: 3.10
  * CCXT version: 1.90.88
  * Freqtrade Version: docker-7075b00e
  
## Your question
Hello,

I have  a custom_stoploss function. When backtesting, I would like to add the resulting calculated absolute stoploss in the dataframe, in order to be able to plot this and visually see how this function behaves. For this, in the function `plot_config`, I've added `'stoploss': {'color': 'red'},` to `main_plot`. 

In the custom_stoploss function, I'm trying to update the dataframe. I've tried various methods, like `dataframe.loc[dataframe['date'] == last_candle['date'], 'stoploss'] = stoploss_absolute`

This does not seem to have any effect, I think because the dataframe I'm getting (with `dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)`) is a copy. So I can update the dataframe, but it has no effect - it does not end up in the 'original' dataframe that gets saved to disk at the end of the backtest.

Is there another way to update the dataframe ? I could save the stoplosses in a custom_info of some sorts. But how can I add it to the dataframe before it gets saved to disk ?

Thanks

**Comment by xmatthias** [comment]
assigning values to the dataframe (so they are visible in plotting functions) is only possible during `populate_*_trend` methods (you don't have access to the trade objects from there though - especially/mainly not during backtesting).

custom-stoploss is a callback - which is called during live / backtesting - but not for plotting (which reuses the results from backtesting). This is the same for all callbacks, as they rely on the trade being open / in process - which is a slow operation to simulate (see backtesting) - and is therefore only done when explicitly asked for (backtesting) - but not when not needed (plotting).

As such - the assignment MIGHT work in live (i think it will not) - but will definitely not work in other modes.

**Comment by gaardiolor** [comment]
I eventually got this to work the dirty way, by logging the stoplosses to a csv in the backtest, and loading it when plotting. Might be useful to some who want to analyze custom_stoploss.

In the custom_stoploss:
```
        # Declare self.custom_stoploss_csv at the top of strategy. 
        # If not already open, open file for writing. 
        if self.dp.runmode == RunMode.BACKTEST and pair not in self.custom_stoploss_csv:
            self.custom_stoploss_csv[pair] = open(f"{self.config['user_data_dir']}/backtest_results/custom_stoploss-{pair.replace('/', '_').replace(':', '_')}.csv", 'w')
            self.custom_stoploss_csv[pair].write('date,pair,stoploss\n')
        if self.dp.runmode == RunMode.BACKTEST:
            self.custom_stoploss_csv[pair].write(f"{last_candle['date']},{pair},{stoploss_absolute}\n")
```

Then I declared `analyze_ticker` in the strategy (I know, shouldn't be done, have to pay attention when a new version of freqtrade is released, not supported, etc):
```
    def analyze_ticker(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Parses the given candle (OHLCV) data and returns a populated DataFrame
        add several TA indicators and entry order signal to it
        :param dataframe: Dataframe containing data from exchange
        :param metadata: Metadata dictionary with additional data (e.g. 'pair')
        :return: DataFrame of candle (OHLCV) data with indicator data and signals added
        """
        dataframe = self.advise_indicators(dataframe, metadata)
        dataframe = self.advise_entry(dataframe, metadata)
        dataframe = self.advise_exit(dataframe, metadata)
        csv = f"{self.config['user_data_dir']}/backtest_results/custom_stoploss-{metadata['pair'].replace('/', '_').replace(':', '_')}.csv"
        if os.path.exists(csv):
            print(f'{csv} exists')
            stoploss = pd.read_csv(csv)
            stoploss['date'] = pd.to_datetime(stoploss['date'])
            stoploss = stoploss.drop('pair', axis=1)
            dataframe = dataframe.drop('stoploss', axis=1)
            dataframe = pd.merge(dataframe, stoploss, on='date', how='outer')
        return dataframe
```

Would be nice to be able to save some custom_* (stoploss, stake_amount, etc) info (like this) to the backtest_results though, would be cleaner.

**Comment by xmatthias** [comment]
You should move it to one of the populate methods. (Each should work).
Theres little reason to override an internal method.

**Comment by gaardiolor** [comment]
Ah yes! I'll move it to one of the populate methods and check for plotting with `if self.dp.runmode == RunMode.PLOT`. Thanks!
