### ISSUE TITLE
Buying And Selling candle 

### ISSUE THREAD

**Issue by Darkredmoon** [freqtrade/freqtrade#7233]
Operating system: Docker
Python Version: _Python 3.10.6 (python -V)
CCXT version: _____ (pip freeze | grep ccxt)
Freqtrade Version: docker-573964b1__ (freqtrade -V or docker-compose run --rm freqtrade -V for Freqtrade running in docker)

Hi, I'm new to freqtrade, I read the docs and I can't find solution, the problem is I want my strategy to buy at the opening of the candle my strategy seems to be working as intended but it buys and sells at the closing of the candle, does freqtrade support buying at the opening of the candle.

**Comment by xmatthias** [comment]
Freqtrade does buy at the candle's open - but most likely not how you expect.

most indicators are based on the candle's closing price (or at least include it as part of the calculation) - so the earliest point the signal can be generated reliably (without repainting) is once the candle is complete (the next candle's open).

If you're using `dataframe['open']` - then the signal will be delayed by 1 candle (freqtrade will provide the strategy with closed candles only). 
You'll however almost certainly not only use the candle's open price - but maybe rsi, macd, or some other additional indicator - which is in fact using the candle's close price (in default configurations).

**Comment by Darkredmoon** [comment]
Is my code not right as you can see in the screenshots it's buying on open and the same thing for selling?
thank you for your time, I appreciate it

<img width="1201" alt="Screen Shot 2022-08-17 at 4 30 52 PM" src="https://user-images.githubusercontent.com/42255844/185182553-72640b7c-4100-42c2-8a7a-429d8a6f8062.png">
185182430-c7dec09b-6342-434f-a85b-298ca41a122c.png">

<img width="1201" alt="Screen Shot 2022-08-17 at 4 36 58 PM" src="https://user-images.githubusercontent.com/42255844/185182631-aaae94da-813f-4ff9-a8a9-3453365bf38b.png">

Here is the code I'm using in this instance

```
from freqtrade.strategy import IStrategy, merge_informative_pair
from pandas import DataFrame
import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib
import numpy  # noqa


class Ilyes(IStrategy):

    """
    SimpleEmaCrossovertest
    author@: Nacer
    How to use it?
    > freqtrade download-data --timeframes 1h --timerange=20180301-20200301
    > freqtrade backtesting --export trades -s DoubleEMACrossoverWithTrend --timeframe 1h --timerange=20180301-20200301
    > freqtrade plot-dataframe -s DoubleEMACrossoverWithTrend --indicators1 ema200 --timeframe 1h --timerange=20180301-20200301
    """

    minimal_roi = {
    "0": 100
}

    # This attribute will be overridden if the config file contains "stoploss"
    stoploss = -1

    # Optimal timeframe for the strategy
    timeframe = '1h'

    # trailing stoploss
    #trailing_stop = False
    #trailing_stop_positive = 0.03
    #trailing_stop_positive_offset = 0.04

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe['ema8'] = ta.EMA(dataframe, timeperiod=8)
        dataframe['ema21'] = ta.EMA(dataframe, timeperiod=21)
        

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

         dataframe.loc[
            (
                (
                (dataframe['ema8'] > dataframe['ema21']) &
                (dataframe['ema8'].shift(1) <= dataframe['ema21'].shift(1))
                )
            ),
            'buy'] = 1
         return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

         dataframe.loc[
            (
                (
                (dataframe['ema21'] > dataframe['ema8']) &
                (dataframe['ema21'].shift(1) <= dataframe['ema8'].shift(1))
                )
            ),
            'sell'] = 1
         return dataframe

```

**Comment by xmatthias** [comment]
well i don't really see anything wrong with the screenshots (or the code).

It seems to work nicely - and as expected.

The candle you see the signal on must be completed (ema is using the candle's close value) - after which the buy can take place. 
Implicitly, this means that  the earliest point the buy (or sell) can take place once the candle is closed - which is effectively after the next candle opened.

**Comment by Darkredmoon** [comment]
thank you, xmatthias I really appreciate your assistance.
