### ISSUE TITLE
Unable to create trade | Available balance is lower than stake amount

### ISSUE THREAD

**Issue by baptiste314** [freqtrade/freqtrade#7238]
Have you searched for similar issues before posting it?

Yes

  * Operating system: Ubuntu 18.04
  * Python Version: 3.6.9
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version:  2022.4.2

## Describe the problem:

Hi,

Everything works fine en dry mode.
But when I switch to production mode, I get this error when the bot tries to trade :

`2022-08-14 23:50:14,049 - freqtrade.freqtradebot - WARNING - Unable to create trade for LINKDOWN/USDT: Available balance (7.722e-07 USDT) is lower than stake amount (100 USDT)`
`2022-08-14 23:50:19,070 - freqtrade.wallets - INFO - Wallets synced.`
`2022-08-14 23:50:19,080 - freqtrade.freqtradebot - WARNING - Unable to create trade for LINKDOWN/USDT: Available balance (7.722e-07 USDT) is lower than stake amount (100 USDT)`
`2022-08-14 23:50:24,109 - freqtrade.wallets - INFO - Wallets synced.`

However, I have 210 usd in binance : 

<img width="243" alt="Capture d’écran 2022-08-16 170857" src="https://user-images.githubusercontent.com/59293428/184914328-a318ef2f-1a6c-4a9a-a18c-0bce6a813335.png">

And here is the config.json file:
```
{
    "max_open_trades": 2,
    "stake_currency": "USDT",
    "stake_amount": 100,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": false,
    "dry_run_wallet":210,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
                "LINKDOWN/USDT"
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 80,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "",
        "CORS_origins": [],
        "username": "",
        "password": ""
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```

Thank you

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

Please also put some content in the description field - just a title is not sufficient to actually try and help you.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.


---

The screenshot is quite descriptive - you've got 210 EUR in your account.

Since your stake-currency is USDT - the actual balance is 0.0.
So you'll either need to reconfigure your bot to use EUR as stake-currency (which implies using EUR pairs - and most likely new testing - as EUR markets most likely behave different to USDT markets...) - or you'll need to convert (some of) your EUR to USDT to have the bot use USDT as stake currency.

**Comment by baptiste314** [comment]
Yes sorry I forgot to uncomment.
Ok thank you very much, I'll try to convert the EUR to USDT in binance

**Comment by xmatthias** [comment]
> Yes sorry I forgot to uncomment.

it's not so much the commenting than the "Leaving out the freqtrade version id" - which is helping us understand what functionalities your version might have - or which bugs we've fixed since.

**Comment by baptiste314** [comment]
Ok I'll think about that next time
