### ISSUE TITLE
custom_entry_price and replicating backtest results

### ISSUE THREAD

**Issue by FahadAziz** [freqtrade/freqtrade#7240]
Hi all 

As I understand backtesting it will always open trades at the open price of the candle whenever entry signal is triggered so I want the bot to always open trades at the open of the current candle or (close price of the last candle). I used the below code:

```
    def custom_entry_price(self, pair: str, current_time: datetime, proposed_rate: float,
                           entry_tag: Optional[str], side: str, **kwargs) -> float:

        dataframe, last_updated = self.dp.get_analyzed_dataframe(pair=pair,
                                                                timeframe=self.timeframe)
        new_entryprice = dataframe['close'].iat[-1]

        return new_entryprice
```

But it does not produce the same result when I remove the code. Any ideas are welcome.

Thanks

**Comment by FahadAziz** [comment]
I ran the bot in dry mode and open rate is current rate on exchange as if this code did not do anything.

**Comment by stash86** [comment]
Are you using limit or market order?

**Comment by FahadAziz** [comment]
limit orders

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

The price you're using will be the price of the prior candle close.
Assuming the strategy analyzes pretty quickly (and the buy is then produced a few seconds into the new candle) - then the price is most likely quite close to the prior candle's close price - so you might not notice a difference (as it's only a few ticks).

I don't see why this would not work though - unless you're using a version that doesn't support this callback yet.
As you thought it's a good idea to delete the issue template - that's for now the most likely cause.
I'll therefore assume that you're running an outdated, no longer supported version.

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.
