### ISSUE TITLE
How can I sell only part of token amount?

### ISSUE THREAD

**Issue by mohsenjavidpanah** [freqtrade/freqtrade#7242]
**Situation**:

  * Operating system: Ubuntu 20.04
  * Python Version: 3.8.10
  * CCXT version: 1.89.14
  * Freqtrade Version: develop-48ff2eedc
  

## My question:

Is it possible for strategies to **sell only part of token amount** instead of total? and is it possible to exit a trade by multiple sells?

Thank You

**Comment by xmatthias** [comment]
The version you're using (48ff2eedc) is not a version known to this project (this number is a shorthand for a commit - which is not part of this repository based on git history).
As such - i have no idea if your version might support this or not.

In general, what you're asking is possible with the latest develop version - and is described in the [documentation](https://www.freqtrade.io/en/latest/strategy-callbacks/#adjust-trade-position).

You'll however need to ensure that you're on a very recent develop version.
