### ISSUE TITLE
Huge difference between backtest and dry run results with resampled timeframe

### ISSUE THREAD

**Issue by infiniteneurotech** [freqtrade/freqtrade#7248]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.10.4 (`python -V`)
  * CCXT version: 1.84.39 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.05.1 
  * Strategy: _____
  
Note: All bug reports will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Hi,

I'm developing a strategy and am failing at the first stage... I've found dramatic differences between dry run and backtesting. In backtesting, the strategy makes trades that don't appear to exist when looking at the charts, most trades have impressive gains, and there are almost no losing trades, so I suspect the strategy is looking ahead somehow.

I think I've narrowed the problem down to the fact that I've resampled a 1m timeframe to a 1h timeframe using resample_to_interval. I followed the example in the documentation, and others I found online so I'm not sure what's going wrong. I'm relatively new to Python and Freqtrade, but am an experienced trader. I'm not using a stoploss or any ROI exits.

Here is the relevant section of code:
```
        #1hr Keltner Channel
        dataframe_1h = resample_to_interval(dataframe, 60)
        keltner = qtpylib.keltner_channel(dataframe_1h, window=16, atrs=2) 
        dataframe["kc_upperband"] = keltner["upper"]
        dataframe["kc_lowerband"] = keltner["lower"]
        dataframe["kc_middleband"] = keltner["mid"]

        #1m Bollinger Bands
        bollinger = ta.BBANDS(dataframe, timeperiod=16, nbdevup=2.0, nbdevdn=2.0) 
        dataframe["bb_upperband"] = bollinger["upperband"]
        dataframe["bb_lowerband"] = bollinger["lowerband"]
        dataframe["bb_middleband"] = bollinger["middleband"]
            
        dataframe = resampled_merge(dataframe, dataframe_1h, fill_na=True)
           
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
       
        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['bb_lowerband'], dataframe['kc_lowerband'])) &
                (dataframe['volume'] > 0)
            ),

            'enter_long'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the exit signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with exit columns populated
        """
        dataframe.loc[
            (               
                
                
                (qtpylib.crossed_above(dataframe['close'], dataframe['kc_upperband'])) &
                (dataframe['volume'] > 0)
            ),

            'exit_long'] = 1

       
        return dataframe
```
The strategy executes fine, with no errors. I want to expand on the strategy, but can't move ahead until I can resolve this. Does anything stand out that would explain the weird results I'm getting, and if so how can I fix it?

I would appreciate any guidance, thank you in advance.

**Comment by xmatthias** [comment]
Moved to the main repository - as it's not really related to a strategy in the strategy repository.

The most likely reason is a problem with resampling.
Backtesting has the whole timerange available - so the resample will work just fine.

live on the other hand get's data in chunks of (the most recent) 500-1000 candles (depending on the exchange).
Since you're using 1m candles, and resample to 1h candles, you'll need to take this into consideration.

Resampling to 1 1h candle, you'll need 60 1m candles. your strategy need at least 16 1h candles - so you'll need **at least** 960 (more likely 1020 - as often indicators require one additional candle) 1m candles - which brings you over what most exchanges provide out of the box.
That's just an assumption though - maybe a window of 16 means it'll require 32 candles - that will need to be verified per indicator.


---

You'll have 2 options for this - either you specify `startup_candle_count` according to how many 1m candles you REALLY need - or (which i'd prefer) - you use the 1h dataframe as [informative pair](https://www.freqtrade.io/en/latest/strategy-customization/#informative-pairs-decorator-informative) - instead of using resampling - which will implicitly and automatically solve this issue.

**Comment by infiniteneurotech** [comment]
Thanks for taking the time to reply. I'm using a start up count of 960, but I'll check the indicator requirement too. I've come across the informative pair option in my research while trying to solve this, and must admit I'm having a hard time getting my head around it. Following the documentation you've linked, should it look like this:

```
@informative('1h')
def populate_indicators_1h(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        keltner = qtpylib.keltner_channel(dataframe, window=16, atrs=2)
        dataframe["kc_upperband"] = keltner["upper"]
        dataframe["kc_lowerband"] = keltner["lower"]
        dataframe["kc_middleband"] = keltner["mid"]
        return dataframe
```

Do I need to specify the timeframe in there somewhere, or is the decorator sufficient? 

Thanks again

**Comment by xmatthias** [comment]
if you use the decorator this way (only specifying the timeframe) - freqtrade will automatically

* pull 1h data for every pair in your whitelist
* calculate the indicators given in this method before calling `populate_indicators()`
* merge the dataframe to the original dataframe - so the columns will be available as `kc_upperband_1h`, `kc_lowerband_1h`, ... in the dataframe `populate_indicators()` receives.

It's basically the simplest way to use informative pairs - as most things are taken care of for you.

**Comment by infiniteneurotech** [comment]
OK I've tried a few more things. I changed the window for the 1h Keltner to 15, so that way I could use a startup_candle_count of 960. It didn't appear to make any difference to the accuracy of the backtests vs live trades, they were still terrible. I did some more reading about the informative_pairs approach, and came up with the following code:

 def informative_pairs(self):
        pairs = self.dp.current_whitelist()
        # Assign tf to each pair so they can be downloaded and cached for strategy.
        informative_pairs = [(pair, '1h') for pair in pairs]
        return informative_pairs
    
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        if not self.dp:
            # Don't do anything if DataProvider is not available.
            return dataframe
            
        inf_tf = '1h'
        # Get the informative pair
        informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf)
        # Get the 1h 15 period Keltner
        keltner = qtpylib.keltner_channel(informative, window=15, atrs=2)
        informative["kc_upperband"] = keltner["upper"]
        informative["kc_lowerband"] = keltner["lower"]
        informative["kc_middleband"] = keltner["mid"]

        dataframe = merge_informative_pair(dataframe, informative, self.timeframe, inf_tf, ffill=True)

       
        #1m Bollinger Bands
        bollinger = ta.BBANDS(dataframe, timeperiod=15, nbdevup=2.0, nbdevdn=2.0) 
        dataframe["bb_upperband"] = bollinger["upperband"]
        dataframe["bb_lowerband"] = bollinger["lowerband"]
        dataframe["bb_middleband"] = bollinger["middleband"]
            
        #dataframe = resampled_merge(dataframe, dataframe_1h, fill_na=True)
           
        return dataframe


    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
       
        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['bb_lowerband'], dataframe['kc_lowerband_1h'])) &
                (dataframe['volume'] > 0)
            ),

            'enter_long'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the exit signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with exit columns populated
        """
        dataframe.loc[
            (               
                
                
                (qtpylib.crossed_above(dataframe['close'], dataframe['kc_upperband_1h'])) &
                (dataframe['volume'] > 0)
            ),

            'exit_long'] = 1

This code runs without errors, and backtests appear to be a closer match to live results. However I have no clue if I've done it right so can you please let me know if there are any glaring errors in my code? And does this mean that I now change my startup_candle_count to match my 1m timeframe indicator (Bollinger bands, 15 candles)?

I just saw your reply as I was typing this out, it looks like my first solution would have probably worked too. I'll try that as well, but can you please comment on my code above? I'd still like to know if it's correct.

Thanks so much for your help, I really appreciate it.

**Comment by xmatthias** [comment]
at a quick glance - the solutions are identical.
the `@informative()` decorator doesn't really do much else - it's just meant to be quicker for the user.

if the expressive form is clearer for you, that'll for sure also work.

**Comment by infiniteneurotech** [comment]
Excellent, I can get to work refining the strategy and I'll keep both approaches in mind for the future. Freqtrade has so many functions and I'm still scratching the surface. Thanks again for your help!
