### ISSUE TITLE
E-Mail emergency service

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#7249]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

In some seldom cases - it was on gate.io on some of my bots today - a bot may stop for any reason after running for weeks.
What about adding a config part, to optionally input SMTP server, from- and to-address, for very important notifications? One could even add a part with the cases, the system needs to send the message. I know, in some situations the bot would stop to early for sending the message. But often it can probably help, not to loose money during a bad issue.

*Explain the enhancement you would like*

**Comment by xmatthias** [comment]
If the bot stops, you will receive a telegram notification (assuming you have telegram configured).

you can also configure [webhooks](https://www.freqtrade.io/en/latest/webhook-config/#webhookstatus) to send status messages (the message type status will be used for "process died").
Combining this with a service like IFTTT, you can also configure this for emails i guess - but most of the configuration would need to happen in IFTTT.

we'll however not be adding SMTP directly to freqtrade. 
Sending emails _reliably_ is very hard (especially via SMTP) unless you have a private (and trusted and properly configured) mailserver available - and is therefore not something we'll be aiming to support.

**Comment by myNextCoder** [comment]
I understand the problem, sending e-mails. Finally it is not really related to the functionality of a trading bot. The thing with telegram and notifications is, that with the switch to "on", I receive to many notifications, in fact for all messages generated.

**Comment by xmatthias** [comment]
You can control [telegram noise](https://www.freqtrade.io/en/latest/telegram-usage/#control-telegram-noise) quite selectively - to receive most notifications either not at all, or as  `silent` (won't generate a "ding") - and only the ones you care about (status) as "on" - which will make them "ding" you.
