### ISSUE TITLE
Problems importing futures data into Notebook

### ISSUE THREAD

**Issue by HeinrichHaller** [freqtrade/freqtrade#7252]
## Describe your environment

  * Operating system: ubuntu stable
  * Python Version: 3.10
  * Freqtrade Version: freqtrade develop
  
## Your question

I do have problems importing future data into the notebook instead of the spot data.
```
from pathlib import Path
from freqtrade.configuration import Configuration
from freqtrade.configuration import TimeRange
import numpy as np
import pandas as pd


config = Configuration.from_files(["user_data/configs/config_RSI_future.json"])

The config is setup with the utility function, so 

'trading_mode': <TradingMode.FUTURES: 'futures'>,
and 
'candle_type_def': <CandleType.FUTURES: 'futures'>,
are correct

config["timeframe"] = "15m"
config["strategy"] = "RSI_Futures_usdt"
config["timerange"] =  TimeRange(starttype="20220610", stoptype="20220625")
data_location = Path(config['user_data_dir'], 'data', 'binance', 'futures')
pair = "BTC/USDT"

from freqtrade.data.history import load_pair_history

candles = load_pair_history(datadir=data_location,
                            timeframe=config["timeframe"],
                            pair=pair,
                            data_format = "json",
                            candle_type=config["candle_type_def"],
                            timerange=config["timerange"]
                            )
print("Loaded " + str(len(candles)) + f" rows of data for {pair} from {data_location}")
candles.head().append(candles.tail())
```
Leads to an empy dataframe:
Loaded 0 rows of data for BTC/USDT from /freqtrade/user_data/data/binance/futures

Path is correct, data are there:
ftuser@d98e962969d4:/freqtrade/user_data/data/binance/futures$ ls | grep BTC_USDT-15m-futures.json 
BTC_USDT-15m-futures.json

What am I missing? 
Thanks!

**Comment by xmatthias** [comment]
data-path should always point to the exchange directory.
you're adding `/futures` to that path - which means freqtrade will try to load futures data from `binance/futures/futures` - which obviously doesn't exist.

removing the "futures" part from `data_location` should make this work.

we might need to change the sample in this case (this seems to be a point of confusion). The proper data-location is also available as `config['datadir']` - which should point to the proper directory - assuming the configuration is setup with the correct user_data_dir.

**Comment by HeinrichHaller** [comment]
Thanks for the heads up! In regard of the documentation it would maybe make sense to keep the parameter
candle_type=config["candle_type_def"]
in the example to show it is needed in case of future data.
I encountered another problem, the timerange seems to be ignored.

config["timerange"] =  TimeRange(starttype="20220510", stoptype="20220625")
candles = load_pair_history(datadir=data_location,
                            timeframe=config["timeframe"],
                            pair=pair,
                            data_format = "json",
                            candle_type=config["candle_type_def"],
                            timerange=config["timerange"]
                            )
Loaded 24137 rows of data for BTC/USDT from /freqtrade/user_data/data/binance

Without timerange:
candles = load_pair_history(datadir=data_location,
                            timeframe=config["timeframe"],
                            pair=pair,
                            data_format = "json",
                            candle_type=config["candle_type_def"]
                            )
Loaded 24137 rows of data for BTC/USDT from /freqtrade/user_data/data/binance

**Comment by HeinrichHaller** [comment]
For spot it seems to be the same. load_pair_history() returns the same length no matter the timerange.

**Comment by xmatthias** [comment]
your timerange generation is simply wrong. 
the easiest way to create a proper timerange is `Timerange.parse_timerange('20220101-20220501')` - but directly assigning it to stoptype is incorrect (stoptype should contain either date or nothing - not a timestamp - least of all - the one you're passing in.).
