### ISSUE TITLE
Can we support COIN-margined Perpetual Futures?

### ISSUE THREAD

**Issue by liaogx** [freqtrade/freqtrade#7254]
I know how to trade USDT perpetual futures with Freqtrade, is that possible to trade COIN-margined Perpetual Futures? 
like `BTCUSD` [https://www.binance.com/en/delivery/btcusd_perpetual](https://www.binance.com/en/delivery/btcusd_perpetual).
- Binance Futures’ COIN-margined perpetual contracts are Bitcoin-margined, which means Bitcoin is used as the base currency.

In this case, it may need to set `"stake_currency": "BTC",` and `"trading_mode": "futures", "margin_mode": "isolated"`, so bots could only trade one _COIN-margined Perpetual Futures_ pair. It's still good anyway, one bot keeps accumulating one coin in the long term.

**Comment by xmatthias** [comment]
Coin margined futures are currently not supported, and it's currently not planned to do so, at least not mid-term.

I've not looked at what that would entail in detail, but i assume some/several of the calculations for fees, liquidation prices, ... might be different (most likely not all though) - and some may even require additional data.

especially on binance - this is currently also not possible due to the way ccxt is naming pairs - so i don't see this as even possible before ccxt migrates to the common naming scheme of base/quote:settle (which would then result in a pair of BTC/USDT:BTC).

**Comment by liaogx** [comment]
> Coin margined futures are currently not supported, and it's currently not planned to do so, at least not mid-term.
> 
> I've not looked at what that would entail in detail, but i assume some/several of the calculations for fees, liquidation prices, ... might be different (most likely not all though) - and some may even require additional data.
> 
> especially on binance - this is currently also not possible due to the way ccxt is naming pairs - so i don't see this as even possible before ccxt migrates to the common naming scheme of base/quote:settle (which would then result in a pair of BTC/USDT:BTC).

Good news! The [latest ccxt version](https://docs.ccxt.com/en/latest/manual.html#perpetual-swap-perpetual-future) does  have a common naming scheme of base/quote:settle for perpetual futures

```python
'BTC/USDT:BTC'  // BTC/USDT inverse perpetual swap contract funded in BTC
'BTC/USDT:USDT' // BTC/USDT linear perpetual swap contract funded in USDT
'ETH/USDT:ETH'  // ETH/USDT inverse perpetual swap contract funded in ETH
'ETH/USDT:USDT' // ETH/USDT linear perpetual swap contract funded in USDT
```

That's would be awesome if inverse perpetual swap contracts are supported.

**Comment by xmatthias** [comment]
the naming scheme has been this way since months - but not for binance - and as far as i know, that's still not the case.

Even if they were - we have currently no plans on supporting coin margined perpetual futures.

**Comment by liaogx** [comment]
> the naming scheme has been this way since months - but not for binance - and as far as i know, that's still not the case.
> 
> Even if they were - we have currently no plans on supporting coin margined perpetual futures.

I'm not familiar with FT architect and source codes, could you give me some hint. If I checkout a new branch to develop a version that only for trading coin margined perpetual futures, as simple as one bot trades one coin margined perpetual pair, which files should I change?

I just reviewed the project's directory, it seems like `../freqtrade/exchange/exchange.py` and `../freqtrade/exchange/binance.py` are related. Is there a simple way to only replace ccxt to exchange trade function, ignore calculations for fees, liquidation prices. I just want to make it workable in live trading.

**Comment by xmatthias** [comment]
I'll not provide support or hints for this.
