### ISSUE TITLE
Hyperopt: Exhaustive space search

### ISSUE THREAD

**Issue by emiliobasualdo** [freqtrade/freqtrade#7259]
Hi guys. 
I currently only use 2 categorical params with 18+- categories each.
```
ndtr = CategoricalParameter([300, 330, 350, 380, 400, 450, 500, 600, 700, 900, 1000, 1100, 1500, 2000], space="buy")
sigma_multiplier = CategoricalParameter(
        [0.05, 0.1, 0.2, 0.3, 0.5, 0.6, 0.7, 1, 1.2, 1.5, 1.7, 2, 3, 4, 5, 7, 8, 9, 10], space="buy")
```
During hyperopt I set the epoch count to 
```
config["epochs"] = len(strategy.ndtr.opt_range) * len(strategy.sigma_multiplier.opt_range)
```
And im getting the `UserWarning: The objective has been evaluated at this point before.` warning.

As my search space is not _that_ big (252),  I was wondering if there is any way to exhaust the search space during hyperopt

I thank you guys for your time.

**Comment by froggleston** [comment]
Hyperopt uses Bayesian search to find optimal paths through that space. If you're seeing that output, it simply means that epoch has found no lower objective than one seen previously. There isn't anything "wrong" here IMO.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Bayesian search is not random / grid search - where you're guaranteed to hit every point in the space once.

More recent versions of freqtrade do have a builtin mechanism to use new random points if already seen points are detected - to improve the possibility of getting out of a so-called local minima.
The warning will however still show up (this point is however most likely not used, but a new one is generated).

It's however still no guarantee that every point in the space will be hit.
