### ISSUE TITLE
"No such file or directory" after a hyperopt run doesn't show the results

### ISSUE THREAD

**Issue by vaidab** [freqtrade/freqtrade#7264]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * freqtrade 2022.7
  * ccxt==1.91.29
  * Python 3.10.5

## Describe the problem:

I run this command:
> time docker-compose run --rm freqtrade hyperopt --hyperopt-loss CalmarHyperOptLoss -j -1 -e 500  --strategy MyStrat --spaces buy stoploss roi trailing --timerange 20210807-20220106 -i 4h --timeframe-detail 30m --strategy-path user_data/strategies/production

After finishing the run:
> [Epoch 500 of 500 (100%)] ||| [Time:  1:03:11, Elapsed Time: 1:03:11]

Epochs are saved:
> 2022-08-20 16:42:25,222 - freqtrade.optimize.hyperopt - INFO - 500 epochs saved to '/freqtrade/user_data/hyperopt_results/strategy_MyStrat_2022-08-20_15-37-32.fthypt'.

But I get this error:

  ```
2022-08-20 16:42:25,229 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 573, in start
    HyperoptTools.try_export_params(
  File "/freqtrade/freqtrade/optimize/hyperopt_tools.py", line 77, in try_export_params
    fn = HyperoptTools.get_strategy_filename(config, strategy_name)
  File "/freqtrade/freqtrade/optimize/hyperopt_tools.py", line 44, in get_strategy_filename
    strategy_objs = StrategyResolver.search_all_objects(
  File "/freqtrade/freqtrade/resolvers/iresolver.py", line 197, in search_all_objects
    for entry in directory.iterdir():
  File "/usr/local/lib/python3.10/pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: 'user_data/strategies/production'                                                                                                   
 ```
And hyperopt exits with ERROR: 1.

Correct behavior would have been to give a warning (since the fact that the directory doesn't exist didn't affect the run) and show the results.

Note that the /production directory doesn't contain the strategy, the strategy was in user_data/strategies, that's why the hyperopt command worked.

**Comment by xmatthias** [comment]
honestly - this error suggests that you've got something odd going on in your strategies directory.

What's `user_data/strategies/production` precisely?
You seem to say that it's a directory - but listing the contents of that directory fails with "no such file". So what is it? it sounds somewhat like a broken symlink at first glance - but that's a suspicion ...

**Comment by vaidab** [comment]
This happens when the directory does not exist (at all).

**Comment by xmatthias** [comment]
Where would it have gotten this name from, then? 
Its not a default path freqtrade is checking (no subdir is).

Maybe its something that is part of your configuration which links it to this invalid directory ( lika a misconfigured strategy_path).

As is, i can't recreate this - so i suspect its something either in your environment, or in the config you've got.
Please provide the startup logs (everything until hyperopt starts for real), as well as the full configuration (remove keys!), the compose file used, and the listing of `ls -ltr user_data/strategies` (assuming thats the volume linked in the compose file) to investigate this further.

Also, please try if running `hyperopt-show -n <someepoch>` right after hitting the above will also cause this.
If yes, please the full log of this, thanks.

**Comment by vaidab** [comment]
I have a backtesting server with multiple processors and a production / live server with 1 CPU.
On the backtesting server I have multiple strategies. Once a strategy is good enough it moves to the live server and I move them to the user_data/strategies/production directory on the backtesting server. Note that I have created that directory.
On the live server user_data/strategies/production doesn't exist, and my strategy stays in the user_data/strategies folder (while on the backtesting one it stays in the production).

So when I tested I (mistakenly) used: "--strategy-path user_data/strategies/production" on the server where the directory didn't exist. The hyperopt ran for x hours and then failed before showing results. It should've either failed in the beginning or, since the strategy was outside the dir and hyperopt worked, it could've only warned about the nonexistant dir.

hyperopt-show -n 1 works correctly.

**Comment by xmatthias** [comment]
The initial command didn't have the `--strategy-path` - and without that, i couldn't imagine how this error would come out, as we do have recursive strategy loading - but if the directory doesn't exist - then it would never descend into that dir in the first place.

It now makes more sense - will look at it when i find the time.
