### ISSUE TITLE
API Calls To Be Able Override Stake Amount

### ISSUE THREAD

**Issue by Fatman2142** [freqtrade/freqtrade#7265]
Hi Guys,

Looking to Make Freqtrade more of a slave to execute my strategy defined in TradingView. Hence it will take commands via WebhookRelay.Com and Execute on Request. WebhookRelay has a agent that makes this secure, and i have written a Python Connector Script that makes this all possible.

The Roadblock to this dream is API Calls get tripped up by the following : 

1. Freqtrade adjusts the stake-amount to this value, unless it's > 30% more than the calculated/desired stake-amount - in which case the trade is rejected
2. To limit this calculation in case of large stoploss values, the calculated minimum stake-limit will never be more than 50% above the real limit._

Typical Command used : 

python rest_client.py --config rest_config.json forceenter ETH/USDT long 500

Command Syntax for quick reference : 

forceenter
    Force entering a trade

        :param pair: Pair to buy (ETH/BTC)
        :param side: 'long' or 'short'
        :param price: Optional - price to buy

Feature Request : 

Can we add an override for API calls to be able to make whatever Stake Amount it wants? Since we are defining the amount via a Command, it would be assumed that the initializer is happy with that amount to be purchased on the exchange. 

Thanks! 
Great work btw!! All the hours and effort put into this is much appreciated! 

Light Reading : 

**Minimum trade stake[¶](https://www.freqtrade.io/en/stable/configuration/#minimum-trade-stake)**

_The minimum stake amount will depend on exchange and pair and is usually listed in the exchange support pages.

Assuming the minimum tradable amount for XRP/USD is 20 XRP (given by the exchange), and the price is 0.6\(, the minimum stake amount to buy this pair is 20 * 0.6 ~= 12. This exchange has also a limit on USD - where all orders must be > 10\) - which however does not apply in this case.

To guarantee safe execution, freqtrade will not allow buying with a stake-amount of 10.1$, instead, it'll make sure that there's enough space to place a stoploss below the pair (+ an offset, defined by amount_reserve_percent, which defaults to 5%).

With a reserve of 5%, the minimum stake amount would be ~12.6$ (12 * (1 + 0.05)). If we take into account a stoploss of 10% on top of that - we'd end up with a value of ~14$ (12.6 / (1 - 0.1)).

To limit this calculation in case of large stoploss values, the calculated minimum stake-limit will never be more than 50% above the real limit._

**Warning

Since the limits on exchanges are usually stable and are not updated often, some pairs can show pretty high minimum limits, simply because the price increased a lot since the last limit adjustment by the exchange. Freqtrade adjusts the stake-amount to this value, unless it's > 30% more than the calculated/desired stake-amount - in which case the trade is rejected.**

**Comment by Fatman2142** [comment]
Ignore : 

:param price: Optional - price to buy is the actual Price per Coin to buy

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

This is available via for freqUI - and as such also through the API for other applications.

You can see the current API specification by enabling the [openAPI interface](https://www.freqtrade.io/en/latest/rest-api/#openapi-interface) and looking at the documentation page there.

---

It's not implemented in the rest_client script - and i currently don't intend to include this functionality there, as you can't have optional arguments in the current form (it's meant as a small crutch anyway, and may be removed in favor of freqUI in the future).
This limitation means that if you want to define additional arguments - you MUST provide all prior arguments (so when defining the stake-amount, ordertype or leverage, you'll be forced to also provide the price).

To enable optional parameters, the whole client script would need to be reworked, completely changing how it works, including hard-defining all available parameters for each subcommand, so each parameter can be passed as `--stake_amount 100` (or however else).

As this functionality is however available both via the API, as well as through freqUI, i currently see this as wasted effort spent into a script that's barely used, and that may be removed in the future.

---

Alternatively, you can simply implement the [`custom_stake`-callback](https://www.freqtrade.io/en/latest/strategy-callbacks/#stake-size-management) - where you can do calculations of the stake amount based on your own likings.
