### ISSUE TITLE
Getting error USDTUSDT is not available as stake on Binance. Available currencies are: BUSD, USDT while running

### ISSUE THREAD

**Issue by xsaad67** [freqtrade/freqtrade#7268]
## Describe your environment

  * Operating system: Win10
  * Python Version: _____ (`python 3.10.6`)
  * CCXT version: _____ (`1.91.29`)
  * Freqtrade Version: ____ (2022.7)
  
I've been trying to find the solution of this error but couldn't find anywhere on internet, My stake currency is USDT and exchange is Binance. I'm simply trying to run the composer image with it but it keeps throwing the error  **USDTUSDT is not available as stake on Binance. Available currencies are: BUSD, USDT while running**

**Comment by xsaad67** [comment]
this is my exchange config.json which comes by default

"```
exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
```

**Comment by xsaad67** [comment]
This is my default configuration 
`"exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },`

I've added blacklist pair USDT too thinking might be it's creating the problem but no luck
`"pair_blacklist": [
            "BNB/.*",
            "USDT/.*"
        ]`

**Comment by stash86** [comment]
Paste the full config minus any keys

**Comment by xsaad67** [comment]
{
    "max_open_trades": 33,
    "stake_currency": "USDTUSDT",
    "stake_amount": 100100,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "8fdc19c6d5b2b65b2c7b56c908a7922c82ce0b1f4ac280ab2e3e0d659d613b60",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "test"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

**Comment by xsaad67** [comment]
Okay my mistake I was using USDTUSDT just saw it now while pasting the whole config

**Comment by stash86** [comment]
You need to fix the stake amount as well
