### ISSUE TITLE
mpmath not found

### ISSUE THREAD

**Issue by adsjr1** [freqtrade/freqtrade#7271]
I installed mpmath module (pip install mpmath) in a docker container in Windows and I had no issues. I moved my strategy to a Raspberry Pi I have and also installed mpmath there, but when I try to run my instrategy I get this error:

freqtrade.resolvers.iresolver - WARNING - Could not import /home/pi/freqtrade/user_data/strategies/nadwats.py due to 'No module named 'mpmath''

Any idea of what could have happened?

$ pip freeze
mpmath==1.2.1

> for path in sys.path:
     print(path)

/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/home/pi/.env/lib/python3.9/site-packages

(.env) pi@bot:~/freqtrade $ sudo find / | grep mpmath | grep site-packages | more
/home/pi/.env/lib/python3.9/site-packages/mpmath-1.2.1.dist-info
/home/pi/.env/lib/python3.9/site-packages/mpmath-1.2.1.dist-info/WHEEL
/home/pi/.env/lib/python3.9/site-packages/mpmath-1.2.1.dist-info/RECORD
/home/pi/.env/lib/python3.9/site-packages/mpmath-1.2.1.dist-info/INSTALLER
/home/pi/.env/lib/python3.9/site-packages/mpmath-1.2.1.dist-info/LICENSE
/home/pi/.env/lib/python3.9/site-packages/mpmath-1.2.1.dist-info/top_level.txt
/home/pi/.env/lib/python3.9/site-packages/mpmath-1.2.1.dist-info/METADATA
/home/pi/.env/lib/python3.9/site-packages/mpmath-1.2.1.dist-info/REQUESTED
/home/pi/.env/lib/python3.9/site-packages/mpmath
...

I can import mpmath inside python bash without issues:
$ python
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
> import mpmath
> print(help(mpmath))
Help on package mpmath:

NAME
    mpmath

PACKAGE CONTENTS
    calculus (package)
    ctx_base
    ctx_fp
...

**Comment by xmatthias** [comment]
Transferred this to the main freqtrade repo, as it's not related to technical at all.

---

most likely - one module is installed in the virtual environment, while the other isn't.
you should be able to test for this by importing both mpmath, as well as freqtrade in the same shell.

Installing additional packages should happen with the virtual environment activated.

**Comment by adsjr1** [comment]
Thanks, @xmatthias.

I feel like when my car has a problem, I take it to the mechanic and the vehicle is okay...

I installed it inside the virtual environment before, but after seeing your reply I did another heck with "pip list" and it was not there. I installed mpmath (again) and now it works...oh well...
