### ISSUE TITLE
Hyperopt KeyError: 'lowerband'

### ISSUE THREAD

**Issue by TR111** [freqtrade/freqtrade#7272]
## Describe your environment

  * Operating system: Ubuntu on Workstation 16
  * Python Version: 3.10.4 (`python -V`)
  * CCXT version: 1.91.93 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.8.dev-7075b00e2 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi all,

I just cannot figure our why freqtrade gives me a KeyError: 'lowerband'. My code is the following (at least imo the important parts):

```
# Strategy parameters
    buy_rsi = IntParameter(10, 40, default=30, space="buy")
    sell_rsi = IntParameter(60, 90, default=70, space="sell")
    buy_rsi_enabled = CategoricalParameter([True, False], default=False, space="buy")
    sell_rsi_enabled = CategoricalParameter([True, False], default=False, space="sell")
    buy_trigger = CategoricalParameter(["bb_lower1", "bb_lower2", "bb_lower3", "bb_lower4"], default="bb_lower2", space="buy")
    sell_trigger = CategoricalParameter(["bb_middle1", "bb_middle2", "bb_middle3", "bb_middle4"], default="bb_middle2", space="sell")

def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        # RSI
        dataframe['rsi'] = ta.RSI(dataframe)
	
	# Bollinger Bands
        bollinger1 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=1)
        dataframe['bb_lowerband1'] = bollinger1['lowerband']
        dataframe['bb_middleband1'] = bollinger1['middleband']
        dataframe['bb_upperband1'] = bollinger1['upperband']
        
        bollinger2 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband2'] = bollinger2['lowerband']
        dataframe['bb_middleband2'] = bollinger2['middleband']
        dataframe['bb_upperband2'] = bollinger2['upperband']
        
        bollinger3 = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=3)
        dataframe['bb_lowerband3'] = bollinger3['lowerband']
        dataframe['bb_middleband3'] = bollinger3['middleband']
        dataframe['bb_upperband3'] = bollinger3['upperband']
        
        dataframe["bb_percent"] = (
            (dataframe["close"] - dataframe["bb_lowerband2"]) /
            (dataframe["bb_upperband2"] - dataframe["bb_lowerband2"])
        )
        dataframe["bb_width"] = (
            (dataframe["bb_upperband2"] - dataframe["bb_lowerband2"]) / dataframe["bb_middleband2"]
        )

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        conditions = []
        
        if self.buy_rsi_enabled.value:
            conditions.append(dataframe['rsi'] < self.buy_rsi.value)
            
        if self.buy_trigger.value == 'bb_lower1':
            conditions.append(dataframe['close'] < dataframe['bb_lowerband1'])
        if self.buy_trigger.value == 'bb_lower2':
            conditions.append(dataframe['close'] < dataframe['bb_lowerband2'])
        if self.buy_trigger.value == 'bb_lower3':
            conditions.append(dataframe['close'] < dataframe['bb_lowerband3'])
            
        conditions.append(dataframe['volume'] > 0)

        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
                'enter_long'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
       
        conditions = []
        
        if self.sell_rsi_enabled.value:
            conditions.append(dataframe['rsi'] > self.sell_rsi.value)
            
        if self.sell_trigger.value == 'bb_middle1':
            conditions.append(dataframe['close'] > dataframe['bb_middleband1'])
        if self.sell_trigger.value == 'bb_middle2':
            conditions.append(dataframe['close'] > dataframe['bb_middleband2'])
        if self.sell_trigger.value == 'bb_middle3':
            conditions.append(dataframe['close'] > dataframe['bb_middleband3'])
            
        conditions.append(dataframe['volume'] > 0)

        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
                'enter_long'] = 1

        return dataframe
```

This results in the following Error:

2022-08-21 19:53:02,092 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/tobias/freqtrade/.env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'lowerband'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tobias/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/tobias/freqtrade/freqtrade/commands/optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "/home/tobias/freqtrade/freqtrade/optimize/hyperopt.py", line 478, in start
    self.prepare_hyperopt_data()
  File "/home/tobias/freqtrade/freqtrade/optimize/hyperopt.py", line 414, in prepare_hyperopt_data
    preprocessed = self.backtesting.strategy.advise_all_indicators(data)
  File "/home/tobias/freqtrade/freqtrade/strategy/interface.py", line 1142, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/home/tobias/freqtrade/freqtrade/strategy/interface.py", line 1142, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/home/tobias/freqtrade/freqtrade/strategy/interface.py", line 1160, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/tobias/freqtrade/user_data/strategies/BBRSI.py", line 149, in populate_indicators
    dataframe['bb_lowerband1'] = bollinger1['lowerband']
  File "/home/tobias/freqtrade/.env/lib/python3.10/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/tobias/freqtrade/.env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'lowerband'

Does anyone have an idea? Just running into errors, regardless of what I am doing.

Thanks!
Tobi

**Comment by xmatthias** [comment]
Well the return value of `qtpylib.bollinger_bands` is  a dataframe with "upper", "lower" and "mid".

As such - you can't access it via `lowerband` - but must use `lower` instead.

**Comment by TR111** [comment]
Oh man, thank you so much! Had some other stuff to fix but now it's working! Amazing!
