### ISSUE TITLE
How do i loop through each pair in Pairlist for each timeframe and output results of each loop of the timeframe

### ISSUE THREAD

**Issue by Walexero** [freqtrade/freqtrade#7280]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.10
  * CCXT version: 1.92.20
  * Freqtrade Version: freqtrade 2022.7
  
## Your question
I am trying to create a function whereby i loop through the Pairlist in my config.json and each pair is hyperopted against a list of Timeframe provided, and for each timeframe, the best result from the hyperopt is logged to a file document, and till the loop of the timeframe is completed, the results are appended to that document. After this is done, i want to filter the best result from that file document, is there a way to achieve this

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Optimizing timeframe is not possible - as that would require to load/reload data for every epoch - and would have a very high performance penalty (too high to justify the invested time to implement such functionality).

Loading data (among creating the indicators) is one of the things that's taking the longest in a backtesting.

You'll therefore have to manually swap timeframes around (you can also use the `--timeframe 5m` command line argument to do this more efficiently).

**Comment by Walexero** [comment]
Okay, what of a scenerio where i have :
Pairs = ['BTC/USDT','ETH/USDT']
what if i dynamically generate a strategy that inherits from my strategy and specify the time frame on it like: 
class SampleStrategy1m(SampleStrategy):
     timeframe: str =  '1h'

is there a way to have the results logged for each pair per running it against the strategy so i have an hyperopt-list --best for each of the two pairs, without them having to overwrite the json file

**Comment by xmatthias** [comment]
All freqtrade commands (except for backtesting with `--strategy-list` run against one strategy.

**Comment by Walexero** [comment]
okay, thanks for the timely response and the help
