### ISSUE TITLE
how can i variable leverage with custom stop loss?

### ISSUE THREAD

**Issue by batuhanhazarguler** [freqtrade/freqtrade#7283]
## Describe your environment

  * Operating system: Ubuntu 22.04.1 LTS
  * Python Version: 3.10.4 (`python -V`)
  * CCXT version: 1.92.48 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.7 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hello my friends,

how can i variable leverage with custom stop loss?

this is my solution manual leverage but not enough
because my leverage is determined by an indicator. so the leverage changes with each trade.

How can I access the leverage it traded in this def custom_stoploss? Or is there another method?
Because custom_stoploss can't multiply by leverage.

`````````
def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:

        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = dataframe.iloc[-1].squeeze()

        # Use parabolic sar as absolute stoploss price
        # stoploss_price = last_candle['sar']

        # Use alphatrend k1 value
        stoploss_price_long = last_candle['k1']
        stoploss_price_short = last_candle['k1']


        positionSide = last_candle['signal'] 

        # Convert absolute price to percentage relative to current_rate
        if positionSide == 'buy':
            if stoploss_price_long < current_rate:
                return ((stoploss_price_long / current_rate) - 1) * self.manual_leverage
        elif positionSide == 'sell':
            if stoploss_price_short > current_rate:
                return ((current_rate / stoploss_price_short) - 1) * self.manual_leverage
        

        # return maximum stoploss value, keeping current stoploss price unchanged
        return 1

**Comment by xmatthias** [comment]
`self.manual_leverage` is clearly wrong and will fail once you have more than one pair open (assuming it'll contain the last value that you assigned it in `def leverage()` ...).

You can (and should) use the pair's attribute `trade.leverage` to get the leverage applied for this trade.

**Comment by batuhanhazarguler** [comment]
so can i do that(return ((stoploss_price_long / current_rate) - 1) * trade.leverage))

**Comment by xmatthias** [comment]
i think `((stoploss_price_long / current_rate) - 1) / trade.leverage))` is more appropriate, assuming you want to control risk.

Assuming  a very crude example using mostly recent btc prices:
`((20_000 / 21_000) -1) * 3` would yield 14.2% - increasing leverage to 5x would yield 23% (so you could lose 23% of your invested capital.

With higher leverage, you'll usually want to pull the stoploss closer to the open price - as you usually want to keep the risk the same (you'd still expect 14.2% risk - even on a 5x trade).

**Comment by batuhanhazarguler** [comment]
Thank u very much
