### ISSUE TITLE
Freqtrade Remote Debug on WSL  by VsCode

### ISSUE THREAD

**Issue by can-acar** [freqtrade/freqtrade#7284]
## Describe your environment

  * Operating system: Windows 11 (WSL - Ubuntu 22)
  * Python Version: 3.10
  * CCXT version: 1.92.20
  * Freqtrade Version: freqtrade 2022.8.dev-85b43ec1a
  
## Your question
 This is not a question, just to provide information on how to do remote debugging with vscode:  
  

> After the installations on wsl are completed, wsl vscode is installed. Then the path where the project is located is opened with the linux shell. 
On the screen that opens, **"`code .`"**
 The project is opened by typing vs code. 
Again, the terminal is run on the VS Code screen and the module is installed with **"`pip install debugpy`".**
Then the same screen ran **"`source .env/bin/activate`"** command 
then **"`python -m debugpy --listen 127.0.0.1:5678 ./freqtrade/main.py trade --config ./user_data/config.json --strategy "SampleStrategy`"** is written with this method Strategy

![image](https://user-images.githubusercontent.com/644199/185949455-58324873-b60a-496a-a3ec-381abaaed83a.png)

**Comment by xmatthias** [comment]
i think a simpler way would be to use the [newly created debug configuration doc section](https://www.freqtrade.io/en/latest/developer/#debug-configuration) - and start freqtrade via that route.
I don't see why this shouldn't work for WSL installations, too.

It'll be easier / simpler than using debugpy manually (as vscode will take care of dependencies,...).

**Comment by can-acar** [comment]
@xmatthias  thanks mate. 
The idea came to my mind with the resource you shared. I can debug in Pycharm
