### ISSUE TITLE
Space values in populate_entry_trend during hyperopt(Future mode)

### ISSUE THREAD

**Issue by JiSeopHyun** [freqtrade/freqtrade#7288]
When optimizing a futures strategy, can only hyperopt spaces "buy" exist in the "populate_entry_trend()" function? The futures strategy file on github consists of "buy" in the long direction and "sell" in the short direction. But the documentation tells me that only "buy" needs to be inside "populate_entry_trend()" to be optimized.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
This is also true for questions where you think it's irrelevant - as it often isn't and will lead to unnecessary back and forth.

---

The separation of spaces is really arbitrary, allowing you to optimize one space only.
in practice you can use any space in any method.

I'd see "buy" more as "entry" - and "sell" more as "exit"  (and i usually suggest to not optimize entry and exit signals at the same time as that would result in a very big result space).
hyperopt spaces have not been renamed / aligned to new terminology - and i'm not sure they will be anytime soon. 
However it's clearly safe to use the spaces where you see fit.

**Comment by JiSeopHyun** [comment]
Thank you.
Let's keep the template going forward.
If you are optimizing in gift mode, what is the best way to do it in 5 steps?
1. long entry
2. long exit
3. Short entry
4. short exit
5. roi stoploss trailing protection
Is this 5 optimization ideal?

**Comment by xmatthias** [comment]
depends a bit on the strategy - but yes, either this way - or optimizing both side's entry signals at once (heavily depends how your signals actually look like).

just make sure to set "sane" defaults for the other parameters before their optimization to avoid surprises (you can't start with no stoploss, to then optimize stop to 5% ... )

**Comment by JiSeopHyun** [comment]
I understood that all Space values affect the result, but I understood the program to consist of "buy" for populate_entry_trend() and "sell" for populate_exit_trend(). Is that right?

**Comment by xmatthias** [comment]
no - in recent versions (basically all versions that can use the Parameters feature) - all parameters can be used in all methods (be that `populate_*_trend()` methods, as well as callbacks.
`populate_indicators()` works slightly differently as it's only called once by default - but the documentation does have details for this.
