### ISSUE TITLE
Downloading futures data + no history for pairs

### ISSUE THREAD

**Issue by vaidab** [freqtrade/freqtrade#7290]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * freqtrade 2022.7
  * ccxt==1.91.29
  * Python 3.10.5

## Describe the problem:

I run this command:
> docker-compose run --rm freqtrade backtesting --strategy MyStrat --timerange 20220820-20220823 -p XRP/USDT --data-format-ohlcv hdf5 --data-format-trades hdf5 -i 5m

And get:
  ```
freqtrade.data.history.idatahandler - WARNING - No history for XRP/USDT, futures, 5m found. Use `freqtrade download-data` to download the data
freqtrade - ERROR - No data found. Terminating.
  ```
(config file contains data-format-ohlcv hdf5 and data-format-trades hdf5, and this output happens with or without adding data-format to the command, just illustrating it's hdf5)

If I try to (re)download the data:
> docker-compose run --rm freqtrade download-data --trading-mode futures --exchange binance --data-format-ohlcv hdf5 -t 5m 1h  --prepend --timerange 20220601- -p XRP/USDT
  ```
Logs show:
Download history data for "XRP/USDT"... futures, mark and 
5m + 1h, the informative timeframe, with length 0 (it's all up-to-date)
  ```

And I get the same error when I run backtesting again.

Then I have to remove from futures all these 3 files: funding-data, mark and the 5m data (doesn't work by removing only the 5m data or any other 1 file) and re-download using the same command.

And then it works.

So somehow the files get corrupted and this already happened a second time.
Here are the 3 files for XMR, another pair with the same issue: https://we.tl/t-e1xTBEutjo

**Comment by xmatthias** [comment]
If a file would get corrupted, then it can't be red at all - which will generate different log entries.
As you're however choosing to only  show one logline, it's impossible to tell if that really happens.

if it were file corruption though, then it would mean one of 2 things:
* you're using some other tool that's messing with the files
* your disk is about to fail and data-corruption can also appear in other areas

I do however doubt that the files are corrupted - as you'd not get this far if the file was really corrupted.
It's more likely that the files can't be found for some reason - which can have many reasons - but are not visible without the full log.

---

Using the XMR files you've provided, they do read just fine - so they're clearly not corrupted.
with the develop version (this supports --show-timernage) - and `freqtrade list-data --userdir ../freq_userdata/ --exchange binance --trading-mode futures --data-format-ohlcv hdf5 --show-timerange` - i get the following output:

```
Found 3 pair / timeframe combinations.
+----------+-------------+--------------+---------------------+---------------------+
|     Pair |   Timeframe |         Type |                From |                  To |
|----------+-------------+--------------+---------------------+---------------------|
| XMR/USDT |          5m |      futures | 2020-02-03 08:00:00 | 2022-08-16 16:05:00 |
| XMR/USDT |          8h | funding_rate | 2020-01-19 16:00:00 | 2022-08-04 00:00:00 |
| XMR/USDT |          8h |         mark | 2020-02-03 08:00:00 | 2022-08-04 00:00:00 |
+----------+-------------+--------------+---------------------+---------------------+
```

why the data for funding and mark candles stops earlier is not clear to me though - but suggests a (maybe?) interrupted download on the 16th.

Running the download of this pair again (on top of these files) does update the data correctly - and up to today.
`
freqtrade download-data --userdir ../freq_userdata/ --exchange binance --trading-mode futures --data-format-ohlcv hdf5 --pairs XMR/USDT -t 5m
`

```
+----------+-------------+--------------+---------------------+---------------------+
|     Pair |   Timeframe |         Type |                From |                  To |
|----------+-------------+--------------+---------------------+---------------------|
| XMR/USDT |          5m |      futures | 2020-02-03 08:00:00 | 2022-08-25 12:20:00 |
| XMR/USDT |          8h | funding_rate | 2020-01-19 16:00:00 | 2022-08-25 00:00:00 |
| XMR/USDT |          8h |         mark | 2020-02-03 08:00:00 | 2022-08-25 00:00:00 |
+----------+-------------+--------------+---------------------+---------------------+
```

---

**edit** Reading your download command again, why are you using `--prepend`? 
that's made to update data **before** the existing timerange (in the above case - before 2020).
the timerange you specify filters for a start date "after" the starting date - so there's nothing to do for the download tool.

By using that - you're basically telling freqtrade "download data before my data starts - starting with 20220601" - to which freqtrade responds "nothing to do - goodbye".

I get this log line when donwloading with `--prepend`.
```
2022-08-25 12:32:39,107 - freqtrade.data.history.history_utils - INFO - (1/1) - Download history data for "XMR/USDT", 5m, futures and store in user_data/data/binance. From start to 2020-02-03T08:00:00
```


A full log would show this quite easily - while one extracted line will not. For the future, please try to not single out log-lines - they feel lonely, taken out of context, and often only show part of the problem.

**Comment by vaidab** [comment]
To answer the questions:
- not using any other tool for the files, only download-data to get them and I've rm-ed manually and downloaded again
- it's a VPS, and there weren't any other issues with the disks (clean dmesg, logs)

I am always using --prepend so that I don't miss any ranges by any chance. I'm understanding from the docs that it allows data prepending (so it also appends the data). After removing --prepend it worked. I'm not sure if it worked because of that or because of an additional download-data command.

**Comment by xmatthias** [comment]
ultimately, the files were not broken anyway - you've just been selecting a timerange outside of the available data - while using the wrong option for download-data.

---

I find the docs [here](https://www.freqtrade.io/en/stable/data-download/#download-additional-data-before-the-current-timerange) pretty clear if i'm honest - and not really saying that it'll also append data - at least if you include the "note" - which says:

> Freqtrade will ignore the end-date in this mode if data is available, updating the end-date to the existing data start point.

**Comment by vaidab** [comment]
It's my bad there for not reading the note. I thought I understood from the "  --prepend             Allow data prepending." that it allows it, it doesn't download only that.

Would recommend:
"  --prepend             Only do data prepending." (or something like that).

But ideally it should download the data in the timerange, no matter what's missing.

**Comment by xmatthias** [comment]
> But ideally it should download the data in the timerange, no matter what's missing.

That's actually intentionally not the case - as prepending is something that should be done very intentionally.

**Comment by LAMBOBLACK666** [comment]
23-11-07 11:41:08,127 - freqtrade.data.history.history_utils - INFO - About to download pairs: [], intervals: ['1m', '5m'] to /freqtrade/user_data/data/binance

**Comment by stash86** [comment]
Please open a new issue. Although I can predict you are using wrong pair naming. The pair naming above is obsolete and wrong for futures pairs

**Comment by LAMBOBLACK666** [comment]
> Please open a new issue. Although I can predict you are using wrong pair naming. The pair naming above is obsolete and wrong for futures pairs

APE/USDT:USDT ? too not worked

**Comment by LAMBOBLACK666** [comment]
> Please open a new issue. Although I can predict you are using wrong pair naming. The pair naming above is obsolete and wrong for futures pairs

Thx bro I love u worked I don't know why first not worked
