### ISSUE TITLE
Using Funding Rate in Futures trading.

### ISSUE THREAD

**Issue by Adilzade** [freqtrade/freqtrade#7302]
I have researched about this topic but unfortunately did not find anything. I want to know if it is possible to use funding rate of ETH/USDT as an indicator like MA(moving average)? Exactly saying i want to sell cryptocurrency if it is positive and buy it when negative. So i will be very grateful if someone show me code example so i can simply copy and paste to test it.

**Comment by xmatthias** [comment]
Transferred to the main repo - as this is not really a strategy request.

---

The [documentation](https://www.freqtrade.io/en/stable/) has several references for this, as you have several ways.
You can either define it as a regular [informative pair](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs) - and use `get_pair_dataframe()` to get the funding rate.

Alternatively (and most likely simpler) - you can use the [@informative decorator](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs-decorator-informative).

**Comment by Adilzade** [comment]
> Transferred to the main repo - as this is not really a strategy request.
> 
> The [documentation](https://www.freqtrade.io/en/stable/) has several references for this, as you have several ways. You can either define it as a regular [informative pair](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs) - and use `get_pair_dataframe()` to get the funding rate.
> 
> Alternatively (and most likely simpler) - you can use the [@informative decorator](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs-decorator-informative).

I have read that documentation but could not figure out how get that :(

**Comment by xmatthias** [comment]
the decorator will just be `@informative('8h', candle_type='funding_rate')` - the value you're looking for will be in the `open` column (all other columns are 0.0 or NAN for funding rates).

How to apply the decorator can be found [here](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs-decorator-informative).

**Comment by Adilzade** [comment]
> the decorator will just be `@informative('8h', candle_type='funding_rate')` - the value you're looking for will be in the `open` column (all other columns are 0.0 or NAN for funding rates).
> 
> How to apply the decorator can be found [here](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs-decorator-informative).

It sounds good but i don't think it will help in this case, because the value of funding rate which is stored at 'open' column is average of values within 8 hours. Funding rate can change its value every second. So, the value at the end of 8h does not reflect its' real meaning. I hope I expressed myself clearly.

**Comment by robcaulk** [comment]
> > the decorator will just be `@informative('8h', candle_type='funding_rate')` - the value you're looking for will be in the `open` column (all other columns are 0.0 or NAN for funding rates).
> > How to apply the decorator can be found [here](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs-decorator-informative).
> 
> It sounds good but i don't think it will help in this case, because the value of funding rate which is stored at 'open' column is average of values within 8 hours. Funding rate can change its value every second. So, the value at the end of 8h does not reflect its' real meaning. I hope I expressed myself clearly.

That is not true, it depends on exchange but the funding rate is only updated once every 8 hours for example on binance. 

Perhaps you are confusing funding rate with open interest?

**Comment by Adilzade** [comment]
> > > the decorator will just be `@informative('8h', candle_type='funding_rate')` - the value you're looking for will be in the `open` column (all other columns are 0.0 or NAN for funding rates).
> > > How to apply the decorator can be found [here](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs-decorator-informative).
> > 
> > 
> > It sounds good but i don't think it will help in this case, because the value of funding rate which is stored at 'open' column is average of values within 8 hours. Funding rate can change its value every second. So, the value at the end of 8h does not reflect its' real meaning. I hope I expressed myself clearly.
> 
> That is not true, it depends on exchange but the funding rate is only updated once every 8 hours for example on binance.
> 
> Perhaps you are confusing funding rate with open interest?

Nope. It is not true. You can go to BInance website and navigate to Futures market and look closely for 24 hours. You will see that it changes a lot within 8 hours. At the end of 8 hours it takes average value and stores it in database.

**Comment by xmatthias** [comment]
this means history of this data is not available - so you can't backtest such a strategy.

Freqtrade is using the "historic funding rates" endpoint for this - and that data is available through the above methods.

up to the minute funding rates are not relevant to freqtrade's operations, and are not available (there's also no unification at ccxt level for this afaik).
you're obviously free to code retrieving uptodate funding rates as part of the strategy - but it's not data that freqtrade is currently providing to the strategy (that data is limited to what's available as historic funding rates).

**Comment by Adilzade** [comment]
> this means history of this data is not available - so you can't backtest such a strategy.
> 
> Freqtrade is using the "historic funding rates" endpoint for this - and that data is available through the above methods.
> 
> up to the minute funding rates are not relevant to freqtrade's operations, and are not available (there's also no unification at ccxt level for this afaik). you're obviously free to code retrieving uptodate funding rates as part of the strategy - but it's not data that freqtrade is currently providing to the strategy (that data is limited to what's available as historic funding rates).

One more question. is it possible to get funding rate synchronously through websockets(binance api) and then pass it every 3 second to freqtrades' dataframe for buy and sell condition?

**Comment by xmatthias** [comment]
Freqtrade does not currently support websockets.

We may do so later this year - but "every 3 seconds" will for sure not be something we can guarantee.

**Comment by Adilzade** [comment]
I know Freqtrade does not support websockets. I have another seperate script that gets real time funding rate every 3 seconds. I am not that good at programming(i'm sorry), so i wonder is it possible somehow pass the output from another script(output is in json format) to Freqtrade in dataframe format for further buy and sell calculations?

**Comment by xmatthias** [comment]
freqtrade strategies are python code - you can load any file you want (obviously you'll have to do appropriate error handling to avoid crashes) - but i don't see why that shouldn't be possible.
