### ISSUE TITLE
Cancelled market orders

### ISSUE THREAD

**Issue by oguzhanpn** [freqtrade/freqtrade#7317]
## Describe your environment

  * Operating system: Mac OS
  * Python Version: 3.9 (`python -V`)
  * CCXT version: 1.92.86 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.7 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
Hi, I am trying to trade on FTX API. However, some of my market orders are cancelled even though there are open orders in the order book. I couldn't figure out why is that happening while some of the orders were executed. I have included a screenshot of my order history. Could you please help me with this issue?

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/68432409/187209387-4175556f-de34-46e4-a0de-82508c697702.png">

Thanks in advance,

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
best look at the log output for when the orders have been created.
I guess there'll be a reason - but i've never seen plain market orders cancelled - unless the market was offline at that time (but then it shouldn't even accept the orders).

**Comment by xmatthias** [comment]
maybe also try to check either via api (see query below)  - or with FTX support on how this is possible.

``` python
import ccxt
exchange = ccxt.ftx({'apiKey': '<yourApiKey>', 'secret': '<yoursecret>' })
res = exchange.fetch_order(order_id, pair)
# Alternatively 
# res = exchange.fetch_orders(pair)

print(res)
```

Maybe the output of that contains something useful.

**Comment by xmatthias** [comment]
Without further info (and info on what happened on the exchange) - we'll not be able to do anything here.

Feel free to reopen with the info above if this is still a problem.
