### ISSUE TITLE
Wrong profit calculation (futures on Okex, dry run) 

### ISSUE THREAD

**Issue by popperwin** [freqtrade/freqtrade#7318]
## Describe your environment

- Operating system: Ubuntu 18.04
- Python Version: 3.10.4 (python -V)
- CCXT version: 1.92.48 (pip freeze | grep ccxt)
- Freqtrade Version: freqtrade 2022.8.dev (commit a6d78a8615a91e18d9adc830bd615bca0f1faa72) (freqtrade -V or docker-compose run --rm freqtrade -V for Freqtrade running in docker)

  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
Sometimes the profit calculated for an open trade is wrong. It doesn't happen all the time, so it's very difficult to spot why.
Even if the stoploss is reached with this wrong profit calculation, it's not triggered. However I'm not sure that roi would be trigger at the real expected. profit  

*Explain the problem you have encountered*
Profit showed in Telegram and UI is wrong.

### Steps to reproduce:

  1. Open a trade on Okex and wait it to happen - sorry I don't know why it happens.

### Observed Results:

  * What happened?
  Profit estimated is wrong
  * What did you expect to happen?
  Profit estimated should be good.
### Relevant code exceptions or logs
<img width="848" alt="Capture d’écran 2022-08-29 à 16 42 47" src="https://user-images.githubusercontent.com/100386956/187231311-4844e093-f20e-491b-9dde-64a26d5c0ffa.png">

**Comment by xmatthias** [comment]
That may sound bad now - but you're using a 2 week old version. Many things changed in the last 2 versions in that regards - so i'll only really look at this if it's also happening with an uptodate version - as it's more likely fixed than not.

Please update to the latest develop version and let me know if it still happens with the new version (on new trades, obviously).

**Comment by popperwin** [comment]
Ok :) 
I've just pulled the new version, I'll tell you if it happens again. Thanks!
