### ISSUE TITLE
stoploss_last_update behaviour in backtest

### ISSUE THREAD

**Issue by gaardiolor** [freqtrade/freqtrade#7319]
## Describe your environment

  * Operating system: Docker
  * Python Version: 3.10
  * CCXT version: 1.92.52
  * Freqtrade Version: docker-39a739ea
  
## Your question

The trade object contains information when the stoploss was last updated, in `trade.stoploss_last_update` . This can be useful for time-based stoploss adjustments.

Now this should work in dry and live mode, but it doesn't in backtesting mode, because (in freqtradebot.py, handle_stoploss_on_exchange) it's set to `datetime.utcnow()`. Is it an idea to, at least in `Runmode.BACKTEST`, set it to `trade.current_time` ?

**Comment by xmatthias** [comment]
It's an internal field - while it's there - there's
* no guarantee it'll stay there
* no guarantee it's filled in all instances

so this can break without any notice - as it's not part of the public interface.

`stoploss_last_update` is only updated if you're using a stoploss on exchange - to track when the last order was issued.


that's irrelevant to backtesting (there's no stoploss on exchange there) - and you can't rely on it in live either, as it'll depend on the setting of "stoploss_on_exchange".

**Comment by gaardiolor** [comment]
Ah yes, ok. I have stoploss_on_exchange enabled, so it would in my specific use-case. But I get the internal field argument, and if you would make it part of the public interface, you of course would want it to work in all cases.

thanks :)
