### ISSUE TITLE
Is there an option to download 1 second historical data?

### ISSUE THREAD

**Issue by TheWCKD** [freqtrade/freqtrade#7326]
Hello @xmatthias,

I was wondering if there is a possibility to download 1 SECOND historical data for backtesting a strategy. From the documentation, I saw that the lowest interval I could set was 1 MINUTE. I've been playing with a bot, trying to get 1s historical data, but the outputs seem pretty significant. Also, the Binance API is not that generous regarding requests per second, as I'd like to retrieve multiple markets for this 1s interval. 

Do you plan on adding the 1-second interval to the script? I appreciate any help you can provide.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

I'm not aware of any exchange API that provides 1s data. 

As such - it's not something freqtrade has the power to add.

**Comment by TheWCKD** [comment]
Thank you for the response and I'm sorry about not filling the question template, I was previously browsing some other questions and didn't notice any template so I didn't think they were mandatory. I'm sorry again, they must've been a little bit old. 

Regarding your reply, binance supports retrieving 1s candles from stream websockets, I just tested them today. They are real time data streams though. 

However I just tested and it seems like it doesn't support 1s historical data, so you're right, the minimum is 1 minute.

**Comment by xmatthias** [comment]
there's many issues without template - most people think it's just there for fun and doesn't impact them...

We've started to require it / ask new users for it - as it's a question of being used - if you've always filled it out - you'll also not delete it when you've got a real issue...

---

livestream, you may get more than 1s data - and they'll surely not guarantee 1 datapoint per second.
Most likely, it's live trade data (not candlestick data) ...

It's not historic data though (traffic cost alone would probably cost a fortune) - so there'd be no backtesting, or other such "fun" stuff ...

**Comment by TheWCKD** [comment]
Thank you so much again for the reply! And I'm sorry again for not filling the template, will make sure to do it next time. I tried multiple markets today and binance offers 1s websocket streams with oclhv data (surprisingly!), indeed it's real time data, not historical. Thank you again!
