### ISSUE TITLE
Light blue icon for re-buy orders

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#7330]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

This is far less than a feature request, just a little visual thing, to distinguish the default enter-orders from the position adjustment orders faster: What about adding a light blue icon only for re-buys? In that case one can see the difference to the first-time buy-order-default-blue at the first sight.

*Explain the enhancement you would like*

**Comment by xmatthias** [comment]
Additional orders are currently not shown. As such - they can't be mistaking with initial orders.

we'll pick matching / appropriate colors and symbols once adjustment orders will be shown.

Tracking of this will be through #7112. Feel free to subscribe to that issue for updates on this.

**Comment by myNextCoder** [comment]
Perfect, I thank you very much.
