### ISSUE TITLE
Filter low marketcap coins

### ISSUE THREAD

**Issue by Mo7mud** [freqtrade/freqtrade#7332]
Is there anyway to filter low marketcap coins?
I searched filters and configuration in docs but didn't find anything related.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

market cap is not an information that exchanges provide via their API - at least not the ones i'm using.

While there's 3rdparty services that provide this info - they're usually heavily rate-limited - making an efficient implementation near impossible.

**Comment by Mo7mud** [comment]
I'm so sorry for deleting issue template, I thought it's required only in case of issues not questions.

Thank you for your answer.
Is there any workaround we can make with pair list filters?

**Comment by xmatthias** [comment]
not really, no (at least not automatically).

you can obviously use staticpairlist, and maintain the list yourself - but that's clearly not what you're after.

With the available info, you'll at max. know what was traded on the exchange in the last X days - but you won't know what the overall available supply is.
