### ISSUE TITLE
Hyperopt: A task has failed to un-serialize/ ModuleNotfoundError

### ISSUE THREAD

**Issue by HeinrichHaller** [freqtrade/freqtrade#7335]
## Describe your environment

  * Operating system: Ubuntu LTS
  * Python Version: Python 3.10.5
  * CCXT version: ccxt==1.87.12
  * Freqtrade Version: freqtrade docker-bb61250b

  
## Your question

I do get an ModuleNotFoundError and joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize error during hyperopt
## Describe the problem:
I do get this problem exclusevly## Describe your environment

  * Operating system: Ubuntu LTS
  * Python Version: Python 3.10.5
  * CCXT version: ccxt==1.87.12
  * Freqtrade Version: freqtrade docker-bb61250b

  
## Your question

I do get an 
ModuleNotFoundError and 
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize 
error during hyperopt exclusively. So the I assume the ModuleNotfoundError is not the culprit.  
Background is I am using custom indicators located in user_data. Originally I thought the custom indicators are somehow not pickable. But the error is reproducible as follows.
### Steps to reproduce:

  1. copy working indicators  "freqtrade.vendor.qtpylib.indicators" into user_data/strategies as qtpylib2 for instance.
  2. replace the imports in a standard strategy
  3. # import freqtrade.vendor.qtpylib.indicators as qtpylib
      import qtpylib2 as qtpylib
  everything like backtesting and plotting works as expected. But the hyperopt fails.

```
docker exec freqtrade-jupyter1 freqtrade hyperopt --config user_data/configs/config_RSI_future.json --strategy RSI_Futures_usdt  -i 15m --dry-run-wallet 1000 --hyperopt-loss OnlyProfitHyperOptLoss  -p BTC/USDT -e 10 --timerange 20220515-20220615 --stake-amount 950
```
```
2022-09-02 11:48:15,468 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 4
2022-09-02 11:48:20,017 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 48, in _reconstruct_wrapper
    obj = loads(_pickled_object)
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 679, in subimport
    __import__(name)
ModuleNotFoundError: No module named 'qtpylib2'
"""


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 523, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 389, in run_optimizer_parallel
    return parallel(delayed(
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```
running the backtesting with the same strategy works

```
docker exec freqtrade-jupyter1 freqtrade backtesting --config user_data/configs/config_RSI_future.json --strategy RSI_Futures_usdt  -i 15m --dry-run-wallet 1000 -p BTC/USDT --timerange 20220515-20220615 --stake-amount 950
```

Thanks for having a look at it!

**Comment by HeinrichHaller** [comment]
import freqtrade.vendor.qtpylib.indicators as qtpylib, 
is simply out-commented! replaced by the same indicator file in user_data/strategies

**Comment by xmatthias** [comment]
Hyperopt is quite sensitive when it comes to unserializing data - as the modules you load must be importable.

Hyperopt scales out into multiple sub-processes - which means the module must be pickled - and must then be unpickled.
To unpickle python modules - these modules must be available in the python path of that subprocess (basically of the interpreter you're running).
if you start a plain python shell (`docker exec freqtrade-jupyter1 --entrypoint python freqtrade`) - then your import will fail if you import as `import qtpylib2` - as `qtpylib2` is not available in this location.

It may work in the strategy context as it's relative to the strategy - this relative import is however not reliably resolvable.
one way is to either make the indicator an installable package (you can run `pip install .` in the custom indicators directory) - or to load it from a "packable" directory relative to the base directory (basically you import as `from userdata.strategies import qtpylib2`).
This will only work if all subdirs are packages - and it's something that's brittle as well - and can have other negative side-effects, too.

---

All that said and explained - we did some work in recent versions which should improve behavior around this (mainly regarding derived strategies) - which may work also for this problem.

Your version is however too old, and therefore not benefiting from that work (your version is from June - we've worked on this in july or august). - so you'll want to update  and attempt this with the latest version.

**Comment by HeinrichHaller** [comment]
That answer speed is unreal.. Thanks. 
-Can I disable the pickling process during optimization? Only run it on one thread? Just to get an general impression?
-update via: docker-compose -f docker/docker-compose-jupyter.yml build --no-cache
mit: FROM freqtradeorg/freqtrade:develop_plot  in the Dockerfile.jupyter is behind the  freqtradeorg/freqtrade:develop?

So build with the newest freqtradeorg/freqtrade:develop and imports relative to the base directory first?

Thanks

**Comment by xmatthias** [comment]
I guess you can run with `-j 1` - which limit the optimization to one process only.



if your build step does not include a `--pull` - then docker will not pull a new upstream image.
`--no-cache` will only prevent using previously built layers (which is unnecessary,usually) - but won't pull new upstream images.

You can verify this with `docker images` - which will show you an outdated date related to `freqtradeorg/freqtrade:develop_plot`.

**Comment by HeinrichHaller** [comment]
Thanks for the heads up! I should have seen the missing --pull. 
The newest version does not solve the problem with the basic qtpylib2 example. 
Reducing the number of threads to 1 solves the problem(Perfectly fine documented as well, thanks for the patience), but is obviously not the ideal. 
I give the local pip install a shot in the morning.
With putting the custom indicator into freqtrade/vendor, changing the requirements.txt - and execute something like: 
docker build . -t test 
the path problem should be resolved as well? But it would break the update mechanism via --pull too?(I need to look up how docker really works)
Thanks

**Comment by xmatthias** [comment]
the main difference will be HOW you import stuff.

copy/pasting the qtpylib file to the strategy directory works just fine for me with `import qtpylib2` with the latest version (stable or develop won't matter).

if you're doing a relative import (leading .) will most likely not work - as the relation to the directory will be broken.

**Comment by HeinrichHaller** [comment]
Avoiding the relative imports does the trick. The custom indicators based upon statsmodels work as well.

**Comment by HeinrichHaller** [comment]
Just a quick follow up, the most stuff written in statsmodels can be written in tensorflow probability as well - results are the same, but quite a bit faster. While reading about pickling tensorflow, it says pickling is replaced by something tensorflow specific. Do you have any experience here? It probably breaks the hyperopt mechanism?

**Comment by xmatthias** [comment]
no experience.
In the end, you'll need to make sure that the strategy remains picklable, as hyperopt will be using that.
combinding hyperopt with tensorflow will probably fail - but is nothing we have experience with, nor something we can provide support for.
