### ISSUE TITLE
Help me with a full list of btc spot pairs of FTX exchange

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#7338]
## Describe your environment

  * Operating system: Linux Mint Una
  * Python Version: 3.10.4
  * CCXT version: 1.92.20
  * Freqtrade Version: freqtrade 2022.8.dev-f2a356a80
  
## Your question

Can someone help me with a direct link to all BTC pairs on FTX exchange. I would be happy if you can copy from your config file. Apparently I couldn't get to know which pairs whitelist to add to my config.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
you can use `freqtrade list-pairs --exchange FTX --quote BTC` for this, as explained [in the docs](https://www.freqtrade.io/en/latest/utils/#list-pairslist-markets).
there's also different output options available - best check these via `--help`.

**Comment by moinonin** [comment]
thank you very much
