### ISSUE TITLE
Use alternative candle indicators Heikin Ashi 

### ISSUE THREAD

**Issue by xarthurx** [freqtrade/freqtrade#7369]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.9.12 
  * CCXT version: 1.92
  * Freqtrade Version: 2022.08 
  
## Your question

It seems `freqtrade` does not recommend modifying the `open`, `close`, `high`, `low` bar in the dataframe, but the `TA-Lib` is using those columns to generate indicators, correct?

Then, if I want to use an alternative candle indicator, such as [Heikin Ashi](https://www.investopedia.com/trading/heikin-ashi-better-candlestick/) candles, how should I generate indicators such as `RSI` of that?

**Comment by stash86** [comment]
`dataframe['rsi']=ta.RSI(dataframe['ha_close'], 14)`

**Comment by xarthurx** [comment]
Sorry for bothing that I re-open the question.
Can I then plot using the new candle?

**Comment by xmatthias** [comment]
You cannot use them for plot-dataframe (not as candles - but you can obviously use them as lines).
freqUI has a builtin heikin ashi mode (which however transfers the columns internally).
