### ISSUE TITLE
backtesting not using `max_open_trades`

### ISSUE THREAD

**Issue by xarthurx** [freqtrade/freqtrade#7371]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.9.12
  * CCXT version: 1.92
  * Freqtrade Version: 2022.8
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

![image](https://user-images.githubusercontent.com/1921878/188917386-b1263739-5d31-43f9-aa71-8fbe58342b8c.png)
I'm debugging a strategy and with this figure, it seems that the backtesting is not using the `max_open_trades` parameter from the config, or `  --max-open-trades INT`?

By zooming in:
![image](https://user-images.githubusercontent.com/1921878/188918011-08121ef0-e774-4620-abc8-0d20be0cbfbb.png)

There are multiple `enter_long` or `enter_short` consecutively, while I set the `max_open_trades = 1`.

The total number of signals generated also matches the diagram.
```
pair       exit_reason
ATOM/USDT  exit_signal    48
           force_exit      1
Name: exit_reason, dtype: int64
```
I tested the same strategy on TradingView, and compared the signals:
![image](https://user-images.githubusercontent.com/1921878/188918610-0c0932ec-6b9a-4172-accb-e4ca1b816b9b.png)

The timestamp that enters `long` or `short` in two systems matches.
However, `freqtrade` has more signals due to the issue I described above.

Is there any setting that I missed?

### Steps to reproduce:

  1. Use a strategy that generate long/short signals
  2. set `max_open_trades = 1`
  3. backtesting the strategy
  
### Observed Results:

  * multiple consecutive `long`/`short` signals appears.
  * When setting `max_open_trades=1`, there should be only 1 trade.

**Comment by xmatthias** [comment]
You're looking at signals - not trades.
Signals may or may not be acted on, depending on circumstances (like max_open_trades, among others).

your chart does not contain a single trade (so either you didn't specify a database / backtesting file - or there was no trade executed for this pair during this timeframe).

**Comment by xarthurx** [comment]
> You're looking at signals - not trades. Signals may or may not be acted on, depending on circumstances (like max_open_trades, among others).
> 
> your chart does not contain a single trade (so either you didn't specify a database / backtesting file - or there was no trade executed for this pair during this timeframe).

So you mean there's a separate label for trades? 

I do specify a backtesting file, and cmd log shows there are PnL.
But it is not drawn on the chart.

**Comment by xmatthias** [comment]
then either your timerange is wrong - or the trades were on a different pair.
the log should tell you...

Trades will be circles / squares - as shown in the [plotting docs](https://www.freqtrade.io/en/latest/plotting/#plot-dataframe-basics)

**Comment by xarthurx** [comment]
Then under this circumstance, if I have multiple pairs to trade, and `max_open_trades = 2`:

- Will there be a chance that `freqtrade` place two orders on the same pair?
- Can I limit each pair to only one trade (in the same direction)?

**Comment by xmatthias** [comment]
Freqtrade will never place 2 trades in parallel on the same pair (unless you use `--eps` - which is only available in backtesting).

You can however increase/decrease trade positions via the [`adjust_trade_position()`](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position) callback.

**Comment by xarthurx** [comment]
> Freqtrade will never place 2 trades in parallel on the same pair (unless you use `--eps` - which is only available in backtesting).
> 
> You can however increase/decrease trade positions via the [`adjust_trade_position()`](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position) callback.

Do you mean 2 trades in the same direction or 2 trades in whatever direction?
I'm currently testing my system using freqtrade, and found that when setting the entry/exit of both long/short to the same condition, i.e. 

**when the signal is `long`, I want to exit the previous `short` and make another `long` order, it seems `freqtrade` will only use the `long` to finish the "previous" short -- though I'm not sure if this is the result of `exit signal` or `long signal`.**

If using "limit order", does that mean this violate the "one trade on one pair" rule? -- I need to use either "market order" or `--eps`?

So in general, if I want to operate both `long` and `short` on the same pair, should I manually set the initial position to "half-stake-size", and use `freqtrade` to do the work afterwards? 

It seems `freqtrade` have the mechanism for the "exit-entry" operation, but I don't have a very clear clue of how to do that.

**Comment by xmatthias** [comment]
The direction is not important - it's one position per pair.
You can enter a new position the candle after your prior trade closes - unless you are using protections which may limit this further.

Please read through the [documentation](https://freqtrade.io) for full details on how freqtrade works.
