### ISSUE TITLE
How do I load more previous data on the FreqUI?

### ISSUE THREAD

**Issue by glowwormX** [freqtrade/freqtrade#7385]
I spent some time looking for parameters to tune the Timerange of freqUI, but couldn't find any. 
Can I load more previous data at freqUI's Trade page.

**Comment by xmatthias** [comment]
FreqUI  (in trade mode) is getting the data from the freqtrade instance in trade mode.
it's therefore limited to the data freqtrade has - which is ~500-1000 candles at once - or more if you set startup_candles to something higher. That'll however also have a performance impact on regular operations - so be careful with that.
