### ISSUE TITLE
Trading on both directions with long/short entry/exit signal the same.

### ISSUE THREAD

**Issue by xarthurx** [freqtrade/freqtrade#7386]
This question is related to this question: https://github.com/freqtrade/freqtrade/issues/7371
because the question was not clearly answered. 

# Q1:
**when the signal is long, I want to exit the previous short and make another long order, and vice versa.**
which means, the exit of the `long` signal is the same as entering the `short` signal.

I scrutinize the doc and cannot find the answer. It seems this is related to the [Colliding signals](https://github.com/freqtrade/freqtrade/issues/7371)
But the rule described there was unclear to me.

![image](https://user-images.githubusercontent.com/1921878/189354997-f0fa3f6f-e73a-48b6-8c4a-1babaafd2891.png)

While the signal of `exit_long` and `enter_short` seems to overlap (which is correct), the `trade` is only operated on the `long` signal...
How should I avoid this and achieve the goal described above?

using `callback`?

# Q2:
With the cmd output:
```powershell
========================================================== BACKTESTING REPORT ==========================================================
|      Pair |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
|-----------+--------+----------------+----------------+-------------------+----------------+----------------+-------------------------|
|  BTC/USDT |    123 |           0.30 |          36.41 |            18.186 |           1.82 |        2:03:00 |    45     0    78  36.6 |
|     TOTAL |    123 |           0.30 |          36.41 |            18.186 |           1.82 |        2:03:00 |    45     0    78  36.6 |
```

Is the `Buys` means `Trades` and count for both `long` and `short` orders?

----------
makeup for the template.
  * Operating system: Windows
  * Python Version: 3.9.12
  * CCXT version: 1.92
  * Freqtrade Version: 2022.8 (stable)

**Comment by xarthurx** [comment]
One of the example strategy, FSampleStrategy: https://github.com/freqtrade/freqtrade-strategies/blob/main/user_data/strategies/futures/FSampleStrategy.py

Also use this type of enter/exit rule.

**Comment by xarthurx** [comment]
If I understand the doc correctly, one way to do it seems to be:

1. place an initial order with half-stake size;
2. place `long`/`short` sequentially using the full-stake-size.

If this is correct, then question:

![image](https://user-images.githubusercontent.com/1921878/189367786-543a8738-222d-448e-9b60-c7b72c121a40.png)

The `initial order` here means the very first order or each order if `long` and `short` change sides?
(If I place a `short` order of 100, on a current 50 `long` position, does this belong to a `initial order`?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

You should also use the edit button instead of posting multiple responses to yourself. that makes an issue very difficult to read.

---

Once freqtrade exits a trade - that pair will be locked until the next candle.
You can therefore not exit and enter on the same candle. the earliest you can enter a new trade (in the same or different direction) is the next candle.


This is exactly the same answer i gave you in https://github.com/freqtrade/freqtrade/issues/7371#issuecomment-1240491193.
you may not like the answer - but it was still clearly answered - and the content of the answer will also not change.

in your case (long exit and short enter signal on the same candle) will therefore act differently depending on the situation.
* if you're in a long trade
  * exit the long trade
  * ignore the short entry
* if you're in no trade
  * ignore the exit signal (there's nothing to exit)
  * enter a short trade

Callbacks won't help you archive this goal (at least not directly), as  DCA will not allow you to switch a position from long to short.

---

Q2: yes, "buys" here is really trades. we'll update the output of this.

**Comment by xarthurx** [comment]
Thank you for the answer and sorry about the template. I'll follow this in the future.


> Once freqtrade exits a trade - that pair will be locked until the next candle. You can therefore not exit and enter on the same candle. the earliest you can enter a new trade (in the same or different direction) is the next candle.
> 
This is clear now.
I was expecting this can be done within the bot's `throttling iteration`, at least for the market order -- close one and place the other immediately.

> in your case (long exit and short enter signal on the same candle) will therefore act differently depending on the situation.
> 
> * if you're in a long trade
>   
>   * exit the long trade
>   * ignore the short entry
> * if you're in no trade
>   
>   * ignore the exit signal (there's nothing to exit)
>   * enter a short trade
> 
> Callbacks won't help you archive this goal (at least not directly), as DCA will not allow you to switch a position from long to short.

This means I cannot use the same condition for long_enter / short_exit or short_enter / long_exit, unless with special ROI or stoploss.

The example [FSampleStrategy](https://github.com/freqtrade/freqtrade-strategies/blob/main/user_data/strategies/futures/FSampleStrategy.py) is a bit misleading...

**Comment by xarthurx** [comment]
Sorry for my bothering you, as I really want to tackle this question properly.
After backtesting, delaying the entry of an order has am impact of the performance.
Thus, I came up with the idea of using two bots, each only doing long/short separately.

However, this needs the exchange to support a "hedge mode". The doc says OKX support that:
![image](https://user-images.githubusercontent.com/1921878/189397890-a5a6bed8-8671-47c2-9079-01c7aeaa3276.png)

As  I use Binance, I can confirm that Binance also support this mode:
![image](https://user-images.githubusercontent.com/1921878/189397807-b10d0856-fd1a-44a4-8351-49ec42cc77f3.png)

But the documentation does not mention anything about this.

I briefly tried but failed. 

I'm not sure if this is because `freqtrade` not supporting it, or there's some parameter I didn't set correctly.

Does `freqtrade` support `hedge mode` for Binance?

**Comment by xmatthias** [comment]
No we don't - and we're unlikely to support this in the near future.

The docs also clearly state that in futures mode - freqtrade assumes to have full control of the (sub)account. Running 2 bots against the same account is not supported.
 Failing to do so may lead to severe losses - as some calculations (liquidation, ...) will no longer work correctly.

you should be able to get around this by using multiple subaccounts - if you're lucky to have that feature enabled ...


the strategy repo is also not "the futures sample strategy" - but a bunch of strategies people contributed.
It's another strategy (i believe the regular sample strategy) - which has simply had it's condition reversed.
They're not meant to be used as is - and it's unfortunate that it shows something that makes you expect a certain behavior.

Freqtrade will however never guarantee to execute on all signals - there's several conditions that can cause a signal to be ignored.

**Comment by xarthurx** [comment]
Very well explained.
Thank you so much for your time and effort.

**Comment by gm10hour** [comment]
> 

can i ask why the hedging model of Binance is not supported, it is very important to us，Thx

**Comment by yazbuz** [comment]
hi. i found something on discord channel by Crypto营长. he said it works. but i couldnt run it. if it works, how can i use it? 
       
       def bot_loop_start(self, **kwargs) -> None:
        """
        Called at the start of the bot iteration (one loop).
        Might be used to perform pair-independent tasks
        (e.g. gather some remote ressource for comparison)

        For full documentation please go to https://www.freqtrade.io/en/latest/strategy-advanced/

        When not implemented by a strategy, this simply does nothing.
        :param ** kwargs: Ensure to keep this here so updates to this won't break your strategy.
        """
        pairs = self.dp.current_whitelist()
        for pair in pairs:
            trades = Trade.get_trades(Trade.pair == pair).order_by(Trade.id).all()
            dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
            last_candle = dataframe.iloc[-1].squeeze() if len(dataframe) > 0 else {'enter_long': 0, 'enter_short': 0}
            # close short -> unlock -> open long
            if self.is_pair_locked(pair=pair) and last_candle['enter_long'] == 1 \
                    and trades and trades[-1].is_short and (not trades[-1].is_open):
                self.unlock_pair(pair=pair)
            # close long -> unlock -> open short
            if self.is_pair_locked(pair=pair) and last_candle['enter_short'] == 1 \
                    and trades and (not trades[-1].is_short) and (not trades[-1].is_open):
                self.unlock_pair(pair=pair)
