### ISSUE TITLE
Shell auto-completion

### ISSUE THREAD

**Issue by vdun** [freqtrade/freqtrade#7387]
For Bash, Zsh, ...

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

While it may be thought as a feature request - i'll not keep an issue open that only consists of 3 words.

We will also not be providing this - as that would require us to hook into your terminal setup. 
Freqtrade installations aim to be contained (non-intrusive to your system) - so tab completion is clearly not something we will aim to provide.

As a side note: python default programs like pip also don't provide this - most likely for the same reasons.
