### ISSUE TITLE
Looks like use_exit_signal = False is not honored all the time.

### ISSUE THREAD

**Issue by doublefx** [freqtrade/freqtrade#7413]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: 3.10.0
  * CCXT version: 1.93.3
  * Freqtrade Version: 2022.9.dev

## Describe the problem:

Setting `use_exit_signal = False` while having logic in `populate_exit_trend` still affects the backtest result.

### Steps to reproduce:

  1. Use this reproducer: https://gist.github.com/doublefx/0301c55c96b671d0d7dcc335c7d59773
  2. Run a backtest (I've been using LUNC/BUSD from 31/08/2022) / Check the result
  3. Uncomment `populate_exit_trend` logic,  lines  72/73
  4. Run a backtest / Check the result
  5. Set use_exit_signal = True
  6. Run a backtest / Check the result
  
### Observed Results:

  * What happened?
 First run, with commented logic:
![image](https://user-images.githubusercontent.com/1222171/190058101-3b6a0a8d-cbea-47b1-b007-e347261501f4.png)

Second run with uncommented logic: 
![image](https://user-images.githubusercontent.com/1222171/190058525-2f898c4f-9012-4de1-a610-237704279ad0.png)

With `use_exit_signal = True`:
![image](https://user-images.githubusercontent.com/1222171/190058684-fd1f1479-0675-4a0d-b7b0-26426096e4c3.png)

  * What did you expect to happen?
I expect `use_exit_signal` to be honored and get a coherent result.
From the doc: https://www.freqtrade.io/en/latest/strategy-customization/#exit-signal-rules
I understand the exit_signal won't be used if use_exit_signal is set to False.

**Comment by xmatthias** [comment]
`use_exit_signal` basically only means that `exit_long` / `exit_short` column content will be ignored for exits.
you'll notice that the detailed exit reasons won't have `jma_has_crossed_below` as exit reason when `use_exit_signal=False`.

the [signal collision](https://www.freqtrade.io/en/latest/strategy-customization/#colliding-signals) rules do however still apply - which is why not having the signal and having the signal in the dataframe still causes differences, even though `use_exit_signal` doesn't change.

now the signal collision doesn't happen too often either (there's only a few trades difference) - but it's obviously causing a difference still.

Personally, i doubt the use of `use_exit_signal` - signals can just as well be disabled by setting the column to 0 - and it always felt like a cheap workaround against poor exit signals.

**Comment by doublefx** [comment]
-- there's only a few trades difference --
In this reproducer, the difference is low, in my real Strat., it's about 150%

What would be the down side of making FT to totally honor `use_exit_signal`?

If it cannot be done, I guess the doc. could be updated to highlight / link to [colliding-signals](https://www.freqtrade.io/en/latest/strategy-customization/#colliding-signals) from [exit-signal-rules](https://www.freqtrade.io/en/latest/strategy-customization/#exit-signal-rules) to reflect this weirdness (unexpected when reading at the doc).

What do you think?

-- signals can just as well be disabled by setting the column to 0 --
Hmm, should I check I have an entry_signal before setting an exit_signal? if yes, what's the proper way of coding that?

Actually, doing that is enough but looks like once again that `use_exit_signal` is not honored :D
```
        if self.use_exit_signal:
            dataframe.loc[dataframe.jma_has_crossed_below,
                          ['exit_long', 'exit_tag']] = (1, 'jma_has_crossed_below')
```

**Comment by xmatthias** [comment]
you'll have to consider what a colliding signal really means.

your strategy is telling the bot "buy - no wait sell" ... so the only safe way is do nothing.

you can probably easily see this by setting an unconditional exit signal (always 1) - which will cause 0 trades in both backtesting and live.

> What would be the down side of making FT to totally honor use_exit_signal?

I'd rather deprecate `use_exit_signal` - i see it as a pointless setting if i'm honest.

the downside (to both deprecating/removing, but more so to changing behavior here) would be a dangerous breaking change (behavior changes unexpectedly - without failing if you use it accidentally).


---

now if i'm honest - the exit-signal doc also doesn't really  say that setting `use_exit_signal=False` means that it got no influence on the bot - just that it ain't going to be used for exits.
a little clarity / explicitly is never wrong though.

**Comment by doublefx** [comment]
I totally agree that either it should do what it describes or be deprecated / removed as one can create it's own boolean variable and use it in the `populate_exit_trend` method.

At the moment it is very confusing.

**Comment by doublefx** [comment]
Thanks for making me understand this!!
