### ISSUE TITLE
Options/Ideas for fixed TP/SL (take profit/stoploss) ratio at trade-entry 

### ISSUE THREAD

**Issue by valentijnk007** [freqtrade/freqtrade#7414]
Hi All,

First I want to thank all the contributors, this is a great trading bot supporting a lot of functionality!!! Below my situation and my research that I have done on the freqtrade website (places links to info that I already found), there is a lot of content the website also many thanks to all those contributors!!! 

Looking forward to anyone's respons, maybe we can open an discussion how we could handle these kind of trades.

## The TP and SL style that I use
I have done some manual trading and I try to convert my trading rules to a strategie in freqtrade. One of the things that I do manualy after entering is the following:

1. Calculate stoploss price, based on ATR multiplier / SAR / last pivot low + ATR
2. Place a sell/stopmarket order on my stoploss price
3. Calculate difference between entry price and my stoploss price
4. Multiply this difference by 2 and use this value to calculate the take profit target
5. Place a sell/stopmarket order on my takeprofit price (because it need a stopprice to be triggerd it will stay until that price is triggers, see attachment)
6. Result fixed TP/SL ration of 2:1

result see picture (i didn't the calculation for take profit target on this one)
![afbeelding](https://user-images.githubusercontent.com/84038998/190074701-a2bd226c-ca62-42f0-8bf5-10c367e1c642.png)

## My environment

  * Operating system: ubuntu server 22.04 (docker)
  * Python Version: Python 3.10.6 (in docker-container)
  * CCXT version: ccxt==1.92.20 (I use kucoin as an exchange)
  * Freqtrade Version: freqtrade docker-16af10a5 
  
## My question
_Has anyone experience with the way of using stoploss and take profit as described by above "TP and SL style"?_ Below are my suggestions I think I have a solution for the "fixed" stoploss, but for the "fixed" take profit I don't have complete idea. I also placed links to the freqtrade website with the information.

**Possible solution fixed stoploss on start of trade (I think):**  
[custom_stoploss](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stoploss): this will be triggered continuously so the ATR values also continuously changed. I think I can fix this by check the time in trade, if it is grater than 1m I won't adjust the price anymore (did not test this).

This would be a combination of [time based trail stop ](https://www.freqtrade.io/en/stable/strategy-callbacks/#time-based-trailing-stop) and [trail stop on SAR](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stoploss-using-an-indicator-from-dataframe-example) and [example ATR from stoplos_from_absolut](https://www.freqtrade.io/en/stable/strategy-customization/#stoploss_from_absolute)

**My idea of realising fixed take profit:**  
Option 1a:
I think I need to use the [custom exit signal](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-exit-signal). But the dataframe is continuously changing, so also the ATR/SAR values... so also my TP/SL ratio. _Does anyone know if you can request the SL price and entry price in that function?_ If that is accessible in that function, I could do the same calculation as above and use helper [stoploss_from_absolute ](https://www.freqtrade.io/en/stable/strategy-customization/#stoploss_from_absolute) to calculate the percentage ratio for generationg the exit signal.

Option 1b:
_Use custom exit, but maybe we can save custom variables at the start of the trade and request them in the custom exit function?_

Option 2:
_Another solution would be to place a second sell/stopmarket order on the exchange at the start of the trade. Does any one know if this is possible? Or are the more supporters for this function?_ Maybe we could figure something out together.

**Comment by xmatthias** [comment]
for stoploss, using custom-stop is clearly the right (and only) approach.
you do get the trade object - so you can compare the open date with the candle date - and only act if they are close enough together.

take-profit you can do something similar using custom_exit - the open rate / values are available as part of the trade object (`trade.open_rate`, `trade.stop_loss`, ...).

You may want to look at the [advanced strategy](https://www.freqtrade.io/en/stable/strategy-advanced/#dataframe-access) part - which should contain exactly what you need.

Now the take-profit order will not be on exchange - but freqtrade will take care of cancelling the stoploss and placing the take-profit order.

**Comment by valentijnk007** [comment]
@xmatthias  thanks for your fast response!!

nice to hear freqtrade can cancel the stoplos order, going to try that.

I am experimenting with the custom_exit, i have downloaded the example advanced template strategy  
(`freqtrade new-strategy xxxx --template advanced`)

But I get an error on the trade: 'Trade', see below. Did I miss something?
![afbeelding](https://user-images.githubusercontent.com/84038998/190115253-8ebcbadc-cad3-4134-a191-03a87615cb8e.png)

**Comment by xmatthias** [comment]
you should be able to import Trade (and Order) from persistence

add `from freqtrade.persistence import Trade, Order` to the imports section.

There's however a difference between a pylance warning - and an actual error.
you'll notice that the strategy will run just fine.

**Comment by valentijnk007** [comment]
@xmatthias thanks again for your fast response!!!! warnings are gone 👍

**Comment by valentijnk007** [comment]
@xmatthias or someone else,

Is it possible to accesss the custom information (descibed [here](https://www.freqtrade.io/en/stable/strategy-advanced/#storing-information)) in the custom_stoploss and custom_exit functions?

I want to use the custom info for the TP/SL targets and reqeust them in those functions.

to se the custom info i think you need metadata, se below example
![afbeelding](https://user-images.githubusercontent.com/84038998/190387398-ccef1b66-6d64-48e4-8a4d-6827af8da059.png)

But this is only accessible in below functions.
![afbeelding](https://user-images.githubusercontent.com/84038998/190387634-6e38d4dc-00b8-4e37-8652-aa2e9aa63bfa.png)


Is it possible to access the custom_info in other functions?

Thanks in advance!!

**Comment by xmatthias** [comment]
access won't change based on the method - it's still a property of the instance (self.custom_whatever).
you don't need metadata though - you can just use "trade.pair" - or `pair` (depending on the callback.

You'll need to be aware however that this info is NOT persisted - so handle non-existence gracefully (as the docs also mention) - for example after you restart your bot - this data might be empty.

**Comment by valentijnk007** [comment]
@xmatthias  thank you very much. Sounds ovious hehe, sorry for the question.

I want to share my code, see below examples. At the confirm trade entry, I calculate the tp and sl for that pair. And in the custom stoploss and exit I request those values again.
![afbeelding](https://user-images.githubusercontent.com/84038998/190490830-a0026711-d6d6-4c05-9b3a-b86765b680b2.png)
![afbeelding](https://user-images.githubusercontent.com/84038998/190490898-61107cd6-d664-4492-a71a-d664c021a977.png)

**Comment by xmatthias** [comment]
If you restart the bot with this code and an open trade, your stoploss / exit will crash with KeyError (although the bot will handle this - and simply act as if the methods were not implemented).

The [documentation](https://www.freqtrade.io/en/latest/strategy-advanced/#storing-information) for this is quite clear - and requires checking if the content is actually there.

**Comment by valentijnk007** [comment]
Thanks for the tip and will keep that in mind! Thanks again for your fast response!!!

I have enough info to figure something out! This was very helpfull!!

Enjoy your day!!

**Comment by Alirezaadham** [comment]
> Thanks for the tip and will keep that in mind! Thanks again for your fast response!!!
> 
> I have enough info to figure something out! This was very helpfull!!
> 
> Enjoy your day!!

Hi, could you please share your code for the sl and tp part? My question is as same as yours but I couldn't figure out a way to set custom sl and tp based on ATR. I come from a poor background of coding and it's hard for me to work things out.

**Comment by asuiu** [comment]
Here's a working code snippet of the latest CCXT (2023.1) that works to simulate OCO orders:

```python
# Create market SELL order
market_buy_order = binance.create_market_order(symbol, side='sell', amount=amount, params={'reduceOnly': False})

# Create SL/TP orders with reduceOnly. Note: TP order is a LIMIT order, that would benefit of the Taker fees (which on Binance are hlaf of the Maker)
sl_order = binance.create_order(symbol, "STOP_MARKET", 'buy', amount=amount, params={"stopPrice": stop_loss_price, 'reduceOnly': True, 'timeInForce': 'GTC'})
tp_order = binance.create_limit_order(symbol, side='buy', amount=amount, price=take_profit_price, params={'reduceOnly': True, 'timeInForce': 'GTC'})

# And close all the orders.
# Note - if in the meantime the position will be closed by the one of the SL/TPorders, this Market order won't affect our positions as it's reduceOnly.
market_close_order = binance.create_market_order(symbol, side='buy', amount=amount, params={'reduceOnly': True})

try:
    binance.cancel_order(id=sl_order['id'], symbol=symbol)
except ccxt.base.errors.OrderNotFound:
    print('Order not found')

# Note: the TP order, will be canceled automatically by Binance after the position is closed by Market order. I'm not sure why this happens, but it does, so we cancel the TPorder just for an extra safety.
try:
    binance.cancel_order(id=tp_order['id'], symbol=symbol)
except ccxt.base.errors.OrderNotFound:
    print('Order not found')
```

**Comment by xmatthias** [comment]
Creating a take oco order through ccxt directly is neither a problem, nor the problem stated here.

as this code is not compatible with freqtrade (if you place this in a strategy - freqtade will lose track of orders created directly). 
Because of this, i'll be hiding this comment to avoid people fall into the trap of assuming it's actually working with freqtrade.
