### ISSUE TITLE
Sell order partially

### ISSUE THREAD

**Issue by bartek666666** [freqtrade/freqtrade#7417]
## Your question

How to sell order partially? what i want to do is when the bot gets exit signal it sells 50% of order and the remaining gets new stop loss (equal to buy price) and new profit target (2x previous).

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Position adjustments can be made via the strategy callback [adjust_trade_position()](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position).

Coding the logic you desire is obviously up to you.
