### ISSUE TITLE
Reduce trade size based on win rate of previous trades

### ISSUE THREAD

**Issue by harisec** [freqtrade/freqtrade#7418]
Thank you very much for writing Freqtrade.
A lot of popular traders are reducing their trade position size when they have multiple consecutive losses.

I'm trying to achieve the same in a Freqtrade strategy.

I'm using the custom stake hook and using Trade.get_trades to get a list of previous trades to calculate the win rate and reduce or increase the stake amount based on percentage of winning vs losing trades.

Unfortunately wallets/Trade is not accessible in Backtesting mode.

Is there another way to achieve this without using Trade so I can backtest my assumptions?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Position adjustments can be made via the strategy callback [adjust_trade_position()](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position).

you can use `Trade.get_trades_proxy` in backtesting for now. It's currently (intentionally) undocumented, and may disappear in the future should we find a better way to handle backtesting performance - but it's unlikely to disappear.
For backtesting, it'll only really work in callbacks, but not in `populate-*` (it'll not fail, but return empty lists) - as no trade is available during populate_* methods - but that shouldn't prevent your usecase.

**Comment by harisec** [comment]
Thank you very much for the answer.
Sorry about not filling the issue template, i was thinking it's not relevant to my question. I will fill it in the future.

**Comment by xmatthias** [comment]
> i was thinking it's not relevant to my question.

that's what everyone thinks - but if you're on an old version, the answer would have to be different (most likely - "please update") - but we could at least warn about the fact that "may not be available with your version" ;)

**Comment by harisec** [comment]
Got it, sorry again!
