### ISSUE TITLE
Price action

### ISSUE THREAD

**Issue by frla18cz** [freqtrade/freqtrade#7419]
Hello, 

is possible to use entry/exit orders by using price action (high, low, close)? I found in doc examples only using indicators.

Thank oyu

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

You can query the orderbook as part of your strategy - and have that define orders.

This method can however not be backtested - and will do an active network call fetching the latest data - so be careful with the pairlist size (as that will increase processing time).
