### ISSUE TITLE
Use case for Encoding strategy file as BASE64

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#7420]
## Describe your environment

  * Operating system: Linux mint Una
  * Python Version: Python 3.10.4
  * CCXT version: ccxt==1.92.20
  * Freqtrade Version: freqtrade 2022.9.dev-fac8f1955
  
## Your question

I have a quick question on the use case of encoding strategy file to base64. 
What is the exact purpose of it? My thinking was that I then don't need to have the same strategy file in the strategies directory. But when I embedded to the config file as detailed in the documentation. I still won't be able to backtest it without the strategy file in the strategies directory. Is it intended for live and dry-run use so that I won't need to have the normal strategy file in the user dir?

Highly appreciate a clarification on this.

**Comment by xmatthias** [comment]
it's initial purpose is live use - yes.
I'm not sure why it shouldn't work for backtesting - but i've never actively used this - as i prefer to see my strategy.

I do however strongly doubt it's usefulness - and am strongly considering the removal of this - as I'm not aware of anyone actively using this (or for what purpose) - and i don't really see any usecase where this could be really useful.

**Comment by moinonin** [comment]
Thanks @xmatthias I will try with dry-run and maybe live if it works. As of considering for removal, I think it can be useful for those who value a little bit of obfuscation.

**Comment by xmatthias** [comment]
base64 is not obfuscation at all - it can be decoded online - and it's visible from far away that it's actually base64 - so it's really not giving you anything in this regards.

Now i'm not sure what errors you're seeing when using this for backtesting ?

**Comment by moinonin** [comment]
Yes, still not working. Here is part of my config file
```
    "initial_state": "running",
    "force_entry_enable": true,
    "internals": {
        "process_throttle_secs": 5,
        "heartbeat_interval": 60
    },
    "disable_dataframe_checks": false,
    "strategy": "StrategyName\":\"longbase64stringhere",
    "strategy_path": "user_data/strategies/",
    "dataformat_ohlcv": "json",
    "dataformat_trades": "jsongz",
    "dry_run_wallet": 3600.0
```
The following error is thrown:
```
dockerdevel  | 2022-09-15 17:27:08,428 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'StrategyName'. This class does not exist or contains Python code errors.
dockerdevel  | 2022-09-15 17:27:08,428 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
dockerdevel  | Traceback (most recent call last):
dockerdevel  |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
dockerdevel  |     worker = Worker(args)
dockerdevel  |   File "/freqtrade/freqtrade/worker.py", line 35, in __init__
dockerdevel  |     self._init(False)
dockerdevel  |   File "/freqtrade/freqtrade/worker.py", line 52, in _init
dockerdevel  |     self.freqtrade = FreqtradeBot(self._config)
dockerdevel  |   File "/freqtrade/freqtrade/freqtradebot.py", line 64, in __init__
dockerdevel  |     self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
dockerdevel  |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 47, in load_strategy
dockerdevel  |     strategy: IStrategy = StrategyResolver._load_strategy(
dockerdevel  |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 267, in _load_strategy
dockerdevel  |     raise OperationalException(
dockerdevel  | freqtrade.exceptions.OperationalException: Impossible to load Strategy 'StrategyName'. This class does not exist or contains Python code errors.
```

Any help is appreciated

**Comment by xmatthias** [comment]
does it work for starting in trade mode?
I actually think that your syntax is worng - `"StrategyName\":\"longbase64stringhere",` should be `"StrategyName:longbase64stringhere",`

**Comment by moinonin** [comment]
OK. That is one issue with the Json I fixed to "StrategyName": "string". The documentation says it should contain base64 string, I have tried both just the string without b' and as a byte object. But I deliberately excluded the strategy file in the path. It didn't work at least in the dry run, throwing the same error as above.

**Comment by xmatthias** [comment]
The [documentation](https://www.freqtrade.io/en/latest/strategy-advanced/#encoding-a-string-as-base64) is quite clear - and exactly the way as documented does work.

Maybe the test case will help you see where you went wrong
https://github.com/freqtrade/freqtrade/blob/8a236c3c4f891bd8ee14d978bfcc4faf11d9ee32/tests/strategy/test_strategy_loading.py#L67-L70

**Comment by xmatthias** [comment]
Closing as i assume you've got this working with the above snippet.

Feel free to comment below / reopen if it's still unclear.
