### ISSUE TITLE
Wrong value parsed as amount parameter in confirm_trade_entry callback during backtesting.

### ISSUE THREAD

**Issue by rixmit** [freqtrade/freqtrade#7423]
* Operating system: Ubuntu 18.04
  * Python Version: 3.9.13 (`python -V`)
  * CCXT version: 2022.8 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.8 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  

##  Problem:

When backtesting the stake amount is passed as value for the 'amount' parameter in the 'confirm_trade_entry' callback.
The correct value (as per the docs) should be the target amount.

### Relevant code exceptions or logs

In backtesting.py:
  ```
            if not strategy_safe_wrapper(self.strategy.confirm_trade_entry, default_retval=True)(
                    pair=pair, order_type=order_type, amount=stake_amount, rate=propose_rate,
                    time_in_force=time_in_force, current_time=current_time,
                    entry_tag=entry_tag, side=direction):
                return trade
  ```

**Comment by xmatthias** [comment]
Great catch 👍
