### ISSUE TITLE
Support stoploss order of "trigger price + market price" on Binance

### ISSUE THREAD

**Issue by liaogx** [freqtrade/freqtrade#7426]
## Describe your environment

 * Operating system: MacOS Monterey 12.5.1
 * Python Version: 3.8.5
 * CCXT version: 1.92.20
 * Freqtrade Version: freqtrade 2022.8 stable

## Describe the problem

Maybe it's a bug, but no. It works okay just not accurate. Here is my config

```python
  "order_types": {
    "entry": "market",
    "exit": "market",
    "trailing_stop_loss": "market",
    "stoploss": "market",
    "emergency_exit": "market",
    "force_exit": "market",
    "force_entry": "market",
    "stoploss_on_exchange": true,
    "stoploss_on_exchange_interval": 60,
    "stoploss_on_exchange_limit_ratio": 0.9998
  },
  "order_time_in_force": {
    "entry": "gtc",
    "exit": "gtc"
  },
```
I set `"stoploss": "market"` and `"trailing_stop_loss": "market"`, but in live trading, the stoploss order is `trigger price + limit price`. eg, picture below

![image](https://user-images.githubusercontent.com/49523956/190837009-d2dbd4f8-c9d2-426f-a38d-de4711475e7d.png)

## Describe the enhancement

Binance futures support three kinds of stoploss order
- trigger price + limit price, as the bot now is. But, I think it should work when set ``"stoploss": "limit"` and `"trailing_stop_loss": "limit"``

- trigger price + market price, I think it should work when set ``"stoploss": "market"` and `"trailing_stop_loss": "market"``
![image](https://user-images.githubusercontent.com/49523956/190837090-9512a0d1-30ed-48e7-8740-c8c95c5954ce.png)

- position stoploss. If the above two options are usable, then this one is not necessary.
![image](https://user-images.githubusercontent.com/49523956/190837099-b5c14c5e-3fb2-4f46-9049-e208dab00324.png)

`trigger price + limit price` and `trigger price + market price` have serious difference, `trigger price + market price` will sure be executed once price are triggered, while `trigger price + limit price` could get cancelled (or we say invalid) if prices move fast and orderbook have intraday spreads. You may set smaller ` "stoploss_on_exchange_limit_ratio` and use `"price_side": "other"` in entry/exit_pricing, but it will risk more loss and still possible to get cancelled if that pair lack lack of liquidity.

**Comment by xmatthias** [comment]
that's quite a simple request - which results in "we need stoploss market for binance futures" :laughing:

**Comment by liaogx** [comment]
> that's quite a simple request - which results in "we need stoploss market for binance futures" 😆

Last time it took me several days to explain to you a bug, so now there are shadows in my heart, afraid not to articulate clearly.
