### ISSUE TITLE
How to configure buy for Dry/live to have "same" results like backtesting?

### ISSUE THREAD

**Issue by naujoks-stefan** [freqtrade/freqtrade#7433]
## Your question
 I already understood that backtesting and dry/live are different in results, because in live/dry every tick is taken into account and of course this cannot be taken into account in backtesting ( except simulation via --timeframe-detail ). 
 How can I set the configuration for live/dry so that the bot behaves the same way for buy in backtesting?
 
 Best
 Stefan

**Comment by xmatthias** [comment]
buy is a signal - so it will be behaving identically (ticks won't matter here in normal cases).

The trade itself may be handled slightly differently - however backtesting tries hard to mirror live results.
This means for backtesting - ROI will take the candle's high into account - while stoplosses consider the candle's low (just as dry/live would).

There is no configuration to ignore ticks for roi/stop- and there shouldn't be either - as that would make live behave quite different to backtesting.
You can read more about the assumptions backtesting takes in the [documentation](https://www.freqtrade.io/en/latest/backtesting/#assumptions-made-by-backtesting).

**Comment by stash86** [comment]
Backtest entry won't ever be replicable because backtest don't have slippage. Either you accept slippage (by using market order), or use limit order and face possibilities of partial filled or even unfilled entries. Either way, both won't guarantee a 100% matching backtest result
