### ISSUE TITLE
Range Stability filter: Pairs under the minimum range are accepted when setting both minimum and maximum ranges 

### ISSUE THREAD

**Issue by dnuno89** [freqtrade/freqtrade#7447]
## Describe your environment

  * Operating system: Windows
  * Python Version:  3.8.10
  * CCXT version: 1.93.66(`pip freeze | grep ccxt`)
  * Freqtrade Version:  freqtrade 2022.9.dev-0c01b23cb (Last update)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

When setting both minimum and maximum ranges, the maximum range is the second checked and overwrites the result of the minimum range result.

### Steps to reproduce:

It is easily seen in the code of rangestabilityfilter.py. From the current file in github, lines 108 to 118 read:

```
if pct_change >= self._min_rate_of_change:
    result = True
else:
    self.log_once(f"Removed {pair} from whitelist, because rate of change "
                  f"over {self._days} {plural(self._days, 'day')} is {pct_change:.3f}, "
                  f"which is below the threshold of {self._min_rate_of_change}.",
                  logger.info)
    result = False
if self._max_rate_of_change:
    if pct_change <= self._max_rate_of_change:
        result = True
```

This last 'result = True' overwrites the False that could have been obtained before, if the pair has a rate change under the minimum.

### Observed Results:

As a result, pairs with stability range under the minimum are accepted.

**Comment by xmatthias** [comment]
Sometimes - i don't understand (...)- you're basically opening a nice report, basically telling us the line the error happens (which is great, don't get me wrong) - which means you got some knowledge, and spent the time investigating.

I'd encourage you to next time attempt to submit a pull request fixing the error - you'll see it's not that difficult - and would help us out some, too.

either way - fixed in develop.

**Comment by dnuno89** [comment]
I'm sorry, I just never used github for anything more than a git pull. I really appreciate the effort done to maintain and develop this project, I'll try doing a pull request next time.

Thanks

**Comment by xmatthias** [comment]
No worries, it's ok this way, too

but with all the work you clearly put in to investigate the error - you should also get the attribution of having a commit and therefore showing up as contributor :)
