### ISSUE TITLE
Script Install Failure :: No module named `wheel`

### ISSUE THREAD

**Issue by eclipsed4utoo** [freqtrade/freqtrade#7452]
## Describe your environment

  * Operating system: MacOS 12.2.1 (M1 Mac)
  * Python Version: 3.8.9 (`python -V`)
  * CCXT version: 1.93.87 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.8 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I'm attempting to install the bot and all of the dependencies. I'm going through the script installation from the documentation by running the `./setup.sh -i` command. After running that command, and after the script checks/installs a bunch of dependencies, it fails out when it gets to the `bdist_wheel`.

### Steps to reproduce:

  1. Clean install
  2. Run `./setup.sh -i`
  
### Observed Results:

  * What happened? Script errors
  * What did you expect to happen? The script to not error.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  Collecting progressbar2==4.0.0
  Using cached progressbar2-4.0.0-py2.py3-none-any.whl (26 kB)
Collecting catboost==1.0.6
  Using cached catboost-1.0.6-cp310-none-macosx_10_6_universal2.whl (22.0 MB)
Collecting lightgbm==3.3.2
  Using cached lightgbm-3.3.2.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/z_/7fjfs5sd20jg1vjw2nt2y6640000gn/T/pip-install-_dm_ygwh/lightgbm_aa381f0549c04c028c5a5a1bc94b6095/setup.py", line 17, in <module>
          from wheel.bdist_wheel import bdist_wheel
      ModuleNotFoundError: No module named 'wheel'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Failed installing dependencies
  ```

**Comment by xmatthias** [comment]
lightgbm doesn't provide wheels for your platform - and apparently configure their package wrongly so wheel is not installed prior to installation.

while we don't directly depend on wheel - it would also not help as that would install wheel at the same time / after lightgbm (both would become first level dependencies to freqtrade).


You can either skip installing freqai / dev dependencies in the script - or (a probably better solution) - use the pre-built docker images we provide (which will also work on M1).

**Comment by xmatthias** [comment]
one thing you can certainly do is install freqtrade via install-script without dev/freqai dependencies - and then install these dependencies afterwards manually via `pip install -r requirements-dev.txt`.

you can also manually install dependencies beforehand - but since i lack the ability to test on an M1 machine - this will most likely not be something we'll be fixing directly.

**Comment by eclipsed4utoo** [comment]
Thanks. I'll give that a try

**Comment by nartes** [comment]
@eclipsed4utoo it's better to use either linux virtual machine, or some package manager with precompiled binaries
for M1, like conda, here's some tutorial on lightgbm for osx m1 - https://towardsdatascience.com/install-xgboost-and-lightgbm-on-apple-m1-macs-cb75180a2dda.

**Comment by alisalama** [comment]
I am on a Mac M1. I was struggling to get installed via native Python, I switched to Conda and it's worked flawlessly since.
