### ISSUE TITLE
entry price using alternative candle strategy

### ISSUE THREAD

**Issue by xarthurx** [freqtrade/freqtrade#7453]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.10 
  * CCXT version: 1.92.52
  * Freqtrade Version: 2022.08
 
### Q1:
The question is related to: https://github.com/freqtrade/freqtrade/issues/7369

I'm testing a strategy using the `Heikin Ashi` candle.
However, the backtesting results seem to use the normal candle to decide the `entry/exit` price.

I'm currently using 
```
        # # Heikin Ashi Strategy
        heikinashi = qtpylib.heikinashi(dataframe)
        dataframe['ha_open'] = heikinashi['open']
        dataframe['ha_close'] = heikinashi['close']
        dataframe['ha_high'] = heikinashi['high']
        dataframe['ha_low'] = heikinashi['low']
```
and compute indicators from these values.
Do I need to overwrite the default `ochlv` columns in the dataframe? Or there's a way to tell `freqtrade` to use these column instead of the normal candle?

### Q2: orderbook
From what I read here:
https://www.freqtrade.io/en/stable/configuration/#entry-price-with-orderbook-enabled

If the `orderbook` is enabled for future trading, does that mean even for `limited` price entry, the `orderbook` will be used rather than the price calculated from the candle?
How frequent is the `orderbook` info retrieved? Same as the candle (for instance, `1m` or `5m`) or more frequent?

**Comment by xmatthias** [comment]
Freqtrade will use the regular OHLCV candle for backtesting - and i'd strongly advise to not mes with these columns.

if you need custom pricing, best use the [pricing callbacks](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-price-rules). Orders will then fill (or time out) depending on the prices selected.

The orderbook is retrieved as needed - which means once every iteration while a trade is open - and otherwise whenever a trade is about to be opened.

**Comment by xarthurx** [comment]
> Freqtrade will use the regular OHLCV candle for backtesting - and i'd strongly advise to not mes with these columns.
> 
> if you need custom pricing, best use the [pricing callbacks](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-price-rules). Orders will then fill (or time out) depending on the prices selected.
> 
> The orderbook is retrieved as needed - which means once every iteration while a trade is open - and otherwise whenever a trade is about to be opened.

Thanks. This is very helpful.
I'm closing the issue.
