### ISSUE TITLE
Exit signal does not seem to be respected in dry run mode

### ISSUE THREAD

**Issue by DianaIonita** [freqtrade/freqtrade#7456]
## My environment

  * Operating system: Ubuntu 22.04 LTS
  * Python Version: 3.9.12
  * CCXT version: 1.92.52
  * Freqtrade Version: using Docker image built from `freqtradeorg/freqtrade:2022.8_pi`
 
## The Question

Hi,

I'm running a bot in dry run mode and observing its trades.
Today it started a trade which it should have completed, based on its exit rule, which is simply to sell when the close price is greater than the value of the upper bollinger band.

I had a look at FreqUI and the trade started at the green arrows and should have exited at the arrow I drew:

![image](https://user-images.githubusercontent.com/2750493/191864806-e4421447-1967-4358-bc5a-493ee2ac599e.png)

I confirmed with TradingView that it was indeed an exit point:

![image](https://user-images.githubusercontent.com/2750493/191864949-a439797e-e2c7-438a-aa0c-9ba7c539b44e.png)

It's a bit difficult to tell whether it the candle closed outside of the Bollinger band, but the values confirm:
![image](https://user-images.githubusercontent.com/2750493/191866318-ff3bf061-c44f-42b1-8295-5fb745efdb97.png)

Then, I plotted the sqllite database using the strategy on this pair, and it also says it should be an exit point:

![image](https://user-images.githubusercontent.com/2750493/191865163-04ea6c95-65f3-4316-9f92-7715d2484c81.png)

However, the exit signal wasn't triggered. Is there anything I might be missing?
The exit configuration is a market sell.

Also, is there a way to plot indicators in freq-ui?

Thank you.

**Comment by xmatthias** [comment]
you can configure indicators/plots via the small settings wheel at the top right of the chart.

One thing you'll need to be careful is however to compare your signals with tradingview. Most indicators there are not open source - so the precise parameters and methods used are not always known (there's about 10 different ways to calculate EMA - and tradingview uses different ones.

FreqUI and plot-dataframe will align (unless you disabled the exit-signals in the freqUI plots) - however the freqUI plot shows no exit signal - which suggests that a different version of the strategy has been used (again - unless exits are disabled above).

**Comment by DianaIonita** [comment]
Hi @xmatthias

Thank you for your help. I was able to trace the discrepancy to a bug in the code that I forgot I had fixed.
I was also able to add indicators to freq-ui, that's very useful.

Thanks again.
