### ISSUE TITLE
Can't connect to the message websocket endpoint

### ISSUE THREAD

**Issue by stash86** [freqtrade/freqtrade#7461]
## Describe your environment

  * Operating system: Ubuntu 22
  * Python Version: 3.10.8 (`python -V`)
  * CCXT version: 1.93.xx (`pip freeze | grep ccxt`)
  * Freqtrade Version: custom latest dev (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
I'm using docker with tailscale. Frequi works just fine. I can also ping the API using `http://<tailscale IP>:8082/api/v1/ping` and get the pong response. But when I tried `http://<tailsclae IP>:8082/api/v1/message/ws?token=<my token>`, the response was `{"detail":"Not Found"}` which I assume means there is no message websocket running on port 8082 (because I got the same response when I tried to ping port 8085 which has no bot running there). Tried changing the port to 8081, same issue

How I set the bot
the producer have this config
```
{
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8081,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "00",
        "CORS_origins": [<my frequi cors>],
        "username": "11",
        "password": "22",
        "ws_token": "<token>"
    },
}
```

For the consumer, the config is
```
{
   "external_message_consumer": {
        "enabled": true,
        "producers": [
            {
                "name": "default", // This can be any name you'd like, default is "default"
                "host": "<tailscale IP>", // The host IP address from your producer's api_server config
                "port": 8082, // since the bot is on 8082 port inside docker
                "ws_token": "<token>" // The ws_token from your producer's api_server config
            }
        ],
        // The following configurations are optional, and usually not required
        // "wait_timeout": 300,
        // "ping_timeout": 10,
        // "sleep_time": 10,
        "remove_entry_exit_signals": false,
        // "message_size_limit": 8
    }
}
```

the consumer bot got this message `2022-09-24 01:36:37,485 - freqtrade.rpc.external_message_consumer - ERROR - Connection Refused - server rejected WebSocket connection: HTTP 403 retrying in 10s`

Is there any extra config that I missed? Like I said, frequi and the ping command are both working fine, so not sure where is the issue. Any way to check whether the websocket part working, apart from the ping command?

**Comment by xmatthias** [comment]
> Freqtrade Version: custom latest dev

We're not supporting custom versions. We won't know what is modified in such a version - and also can't be sure if it actually contains features you're trying to use.
Please try with the lastet develop version from this repository - and provide us with the precise version.

---

You can't connect to a websocket like this - it needs a websocket connection (where the only real accepted regular  connection is an upgrade request - which needs very specific headers set).

what i noticed is that your producer config shows port 8081 - but everywhere else, you're using 8082 ... the ports will obviously need to match.

---

we also will need proper logs from both the server and the follower. the error you get - 403 - suggests that it did connect to "something" (probably another bot running on 8082...) - but that something rejected the connection.
Not connecting at all would cause a different error.

**Comment by stash86** [comment]
The same config works for frequi and the ping command, so I assume it should work as well for the websocket?

**Comment by xmatthias** [comment]
my current assumption based on the configs is that your ports are missmatched, or that your verison is outdated and doesn't contain websocket code (no version number shared).

**Comment by stash86** [comment]
fixed. It was how I assign the port for the containers.
So previously, I assign the port for the containers to `<Ip>:8081:8081`, `8082:8081`, `8083:8081`, and set the listen port to 8081 for all, and they works for frequi. But it seems websocket requires them to have separate port externally. So have to do `<Ip>:8081:8081`, `8082:8082`, `8083:8083`

Not sure if it worth mentioning in the docs

**Comment by xmatthias** [comment]
you need to be careful if you use docker - and you're on the same host.
your configuration / mapping will definitely work if you connect from a different host.

from the same host however - you can use `containername:internalport` - (so the communication stays within the docker network).
in that case, the containername identifies the destination - and the port can be identical for all connections.

if you use the external IP + the external port, i'm not sure how docker will react precisely - as it may detect it's internal traffic and "attempt" to redirect it.
