### ISSUE TITLE
Please support self.dp.send_msg() to webhook.url

### ISSUE THREAD

**Issue by liaogx** [freqtrade/freqtrade#7464]
## Describe your environment

 * Operating system: MacOS Monterey 12.5.1
 * Python Version: 3.8.5
 * CCXT version: 1.92.20
 * Freqtrade Version: freqtrade 2022.8 stable

## Describe the enhancement

Currently `self.dp.send_msg()` can be used for Telegram bot notification, hope it can also send message to `webhook.url`

**Comment by xmatthias** [comment]
It really isn't - and i currently have no plan to expand webhook support further.

I don't really see what usecase webhooks would fill (especially for custom messages).

**Comment by liaogx** [comment]
For example, send msg about trades number, winrate, total profit, current maxDD to discord.

**Comment by xmatthias** [comment]
As mentioned above, i see no benefit in this.

I've marked it as "good first issue" for now - as it'll only entail a few lines of code-change.
If nobody picks it up (and submits a PR) within a month or two i'll take that as a sign that it's a usecase not worth pursuing.

**Comment by robcaulk** [comment]
I would like to see someone make this PR as well.
