### ISSUE TITLE
Multiple hyperopt runs without recalculation of populate_indicators() or How to save the dataframe locally as csv?

### ISSUE THREAD

**Issue by sanoj2021** [freqtrade/freqtrade#7467]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.10.0
  * CCXT version: 1.92.60
  * Freqtrade Version: 2022.8.dev
  
## Your question

Let's say I have a strategy for which populating the indicators takes up very long time (e.g. 10-100 min. per single pair depending on the timerange). And it's impossible to utilize any of the faster pandas functionalites.

Is there a workaround to get multiple hyperopt runs with different random states after have the poor CPU to run populate_indicators() only once?

Alternative (better) question would be if it's possible to get the dataframe saved locally after populating indicators is done and reuse this in next hyperopt run?
Can I simply save the dataframe for each pair at the end of populate_indicators() with something like dataframe.to_csv() and name the file according to the current pair using metadata['pair']. Then being able to check for existing csv files at the top of populate_indicators() to load and merge it with the new empty dataframe. Will this work as expected?

Couldn't find anything like this in the issues/documentation.
The 'Print created dataframe' section looks like touching something else.

**Comment by xmatthias** [comment]
freqtrade strategies allow you almost everything that python does - and as such, also what pandas allows.

Freqtrade itself however doesn't provide functionality for this, not least because you will run into situations where this will no longer work - and you'll try a change for hours to realize WHY it doesn't apply.

if populate_indicators runs for 10-100 minutes per pair, that's almost certainly going to be a huge problem for live  - as your indicators will not be ready "on time" - so one calculation iteration for all pairs would take longer than the strategy.
You should therefore work strongly on optimizing this, unless it's caused by huge parameter spaces - in which case you might wanna use `--analyze-per-epoch` to only calculate the value that's actually going to be used for the epoch.

**Comment by sanoj2021** [comment]
(((The problem with the timing is potentially manageable by applying the following two steps.
It's possible to set the `internals.process_throttle_secs` to something like 10min.
The runtime of populate_indicators is only that long with using long backtest/hyperopt timeranges. E.g. with 1h timeframe - at least in my case - it should be enough time in live mode for the calculations to take place during the 10min.
Is it possible to work like this?)))
Ok, I won't erase my original proposed solution, because it could be helpful to have this figured out also.

But: I would say that this problem completely vanishes anyway: In Live Mode the indicators are only calculated for the optimal parameters and additionally only for the latest candle (as far as I know). So it should be fast enough and no problem.

Regarding the optimization of the `populate_indicators()` execution speed - like I pointed out in my question - it is not possible to speed this up in my case. All I can tell is that I'm using a custom for-loop (yes, I know this is highly not recommended) to calculate the indicators and while execute a lengthy calculation at each step. And unfortunately it's not possible to do this differently and this only partly is caused by the size of the parameter space (I will try the `--analyze-per-epoch` though).

Kindly I would like to ask you and everyone in question to reconsider my original question about saving the dataframe for later usages with 'df.to_csv()' or something else(?). Who knows, this may also be of interest for others' use cases. So please re-open my issue. Thank you very much

**Comment by xmatthias** [comment]
`process_throttle_secs` (mainly) controls how often open we check on open trades, you shouldn't change that i think (it's also not relevant to this problem).

You will be 10 minutes late to the party (your signal would be acted on 10 minutes into the 1h candle).
That's not necessarily a problem - but can be.

---

`--analyze-per-epoch` assumes you use the Hyperoptable `.range` magic. If you don't - it'll probably not work.

There's nothing preventing you from saving the dataframe from within the strategy.
The responsibility to get that right (and evict existing data should something change) falls then to you, obviously.

It's however not a feature we'll consider for freqtrade - as it's pretty hard to reliably determine if a change done is relevant to the generated features or not - and is therefore too prone to introduce bugs and errors.

**Comment by sanoj2021** [comment]
Ok, so 'process_throttle_secs' is not an option. And yes, I use the '.range' magic, so the second approach is an option.

I totally understand that this is not going to be a feature of freqtrade and this is a very specific problem - probably no one will face any time soon, too. The more I am happy if anyone gives me useful hints on this.

Nevertheless, saving the dataframe with 'dataframe.to_csv("filename.csv")' at the bottom of 'populate_indicators()' did not work.
Where will the file end up? 
Is the dataframe object actually an original pandas dataframe?

**Comment by xmatthias** [comment]
depends on the path you use - without anything specific or absolute paths, in CWD (which is the directory you run the bot from).

yes, it's a regular pandas dataframe, without any magic ...

**Comment by sanoj2021** [comment]
Great, thanks. It failed to save the csv file on my first try, because I did specify a non-existent subfolder. Now it's working.

I will take care of the saving and reloading of the dataframe by myself and may post my results here later on for everyone curious

**Comment by sanoj2021** [comment]
Here is one working implementation of a locally saved dataframe with very simple logic to check for an existing saved csv. Also one have of course make sure by themself that there are saved dataframes for all needed pairs to run the current hyperopt run on the temp csv files successfully. The if-else logic sorts out whether the hyperopt Timerange matches the csv-file (but not the timeframe) and fires a complete new run of populate_indicators() otherwise. (And the folder - saved_dataframe under user_data in this case - has to exist before running the code.)
```
import logging
logger = logging.getLogger(__name__)
class WhatYouLike(IStrategy):
        ...
        dataframe_file_path = 'user_data/saved_dataframe/'
        ...
        populate_indicators(...):
        file_str = metadata['pair'] + '.csv'
        file_str = self.dataframe_file_path + file_str.replace("/", "_")
        if os.path.exists(file_str):
            logger.info('Attempting to load Dataframe from file.')
            df_csv = pd.read_csv(file_str)
            df_csv.date = pd.to_datetime(df_csv.date)
            df_csv.sort_index(inplace=True)

            if df_csv.index.equals(dataframe.index):
                dataframe = df_csv
                logger.info('Successfully loaded existing Dataframe from file ' + file_str)
            else:
                logger.info('Failed to load Dataframe from file: Timerange missmatch.')

        if not os.path.exists(file_str) or (not df_csv.index.equals(dataframe.index) and os.path.exists(file_str)):
            if not os.path.exists(file_str):
                logger.info('Failed to load Dataframe from file: No such file at ' + file_str)

            "Do your indicator calculation here"
            dataframe.to_csv(file_str)
            logger.info('Saving Dataframe to ' + file_str)
```

**Comment by xmatthias** [comment]
timeframe missmatches are the least of your problems.
if you look at this strategy in a few weeks time (without looking at it in the meantime) - you'll have forgotten about this logic - and minimal changes you do won't have an effect, driving you mad until you remember this...

**Comment by sanoj2021** [comment]
Yes I'm familiar with this type of problem and usually get by it quite well by documentation of the strategy's logic.
This code snippet has to be used with care and everyone is invited to understand things first before using them.
Now this is the working for me, in a few weeks it may be already outdated.
