### ISSUE TITLE
Backtest Informative Pair not in sync with Live process

### ISSUE THREAD

**Issue by alisalama** [freqtrade/freqtrade#7468]
## Describe your environment

Operating system: macOS Monterey 12.2
Python Version: 3.9.7
CCXT version: 1.93.66
Freqtrade Version: freqtrade docker-71e6c54e
  
## Describe the problem:

I have a strategy running on the minute timeframe. I am adding some BTC and ETH daily data to a strategy using informative pairs.

For the live setup everything is working fine, but on the backtest for the current day (as in the last day) the daily data seems to be a day behind what it should be.

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/7068759/192145206-7f5cf5b8-fdcc-45e5-8acd-902438ed63d7.png">

In the screengrab, the Backtest was ran after the Live process, so presume the more recent data must be available. I've tried clearing and re-downloading the daily data numerous times to no avail.

### Steps to reproduce:

  1. Create strategy on minute timeframe.
  2. Add code below to strategy
  3. Run in Live and Backtest.
  
```  #  I have tired without this.
    def informative_pairs(self):
        return [('ETH/USD', '1d'), ('BTC/USD', '1d')];

    # CREATE A DAILY HEIKEN ASHI TRIGGER
    @informative('1d', 'BTC/{stake}')
    @informative('1d', 'ETH/{stake}')
    def populate_indicators_btc_1d(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        # create the heiken-ashi candles
        heikinashi = qtpylib.heikinashi(dataframe);
        dataframe['ha_open'] = heikinashi['open'];
        dataframe['ha_close'] = heikinashi['close'];
        dataframe['ha_high'] = heikinashi['high'];
        dataframe['ha_low'] = heikinashi['low'];
        dataframe['ha_change'] = (dataframe['ha_close'] / dataframe['ha_open'] - 1);
        dataframe['ha_green_or_red'] = (dataframe['ha_close'] >= dataframe['ha_open']);
        
        return dataframe[['date', 'ha_green_or_red']]; # we only really need these two columns from here

```

### Observed Results:

  * What happened? For the current day, Backtest informative pairs are one day behind what they should be.
  * What did you expect to happen? Bot to be in sync for both Live and Backtest on informative pairs

### Relevant code exceptions or logs

[dataframe - backtest - FTM.xlsx](https://github.com/freqtrade/freqtrade/files/9640807/dataframe.-.backtest.-.FTM.xlsx)

No exception or log issues.

**Comment by xmatthias** [comment]
informative pairs (as well as regular pairs) will only use complete candles.

backtesting as such will always lag behind slightly - as we need to ensure that only complete candles will be used.

**Comment by alisalama** [comment]
Thanks Matthias. These tests were ran on the 25th September, and so the 1d candle of the 24/09 should be included in the backtest as it is a complete candle.

**Comment by xmatthias** [comment]
for backtesting, you'll most likely have a (security) delay of 2 candles - one will be removed on download - and one on loading the data.

The merging itself is therefore correct - it's the data that's not available yet.
you'll see that tomorrow, the data for the 24th will be available.

**Comment by alisalama** [comment]
Thanks. Yeah I know it works the following day. I spotted the issue yesterday and found it corrected itself today (for yesterday).

Seems an odd assumption to remove two candles. I get removing the current candle on download, but why a 2nd one on attachment?

Especially on the longer time frames this can cause long lags for the informative pairs. For daily can be up to two days behind, for weekly can be two weeks behind, monthly up to two months...

**Comment by xmatthias** [comment]
the assumption on load is that the data might not be sourced from freqtrade - but from different sources.
so by default, we don't trust the fact that the last candle stored is complete.

One can argue that we should assume freqtrade downloads - but it's really an edge-case that only impacts backtests with very recent data - and only on rather long timeframes.

**Comment by alisalama** [comment]
Thanks. That assumption makes quite a lot of sense.

Counter arguments 
1. Arguably the concern of proper "cleaning" of the data should be with the user who is attempting to use external data. By using a separate data load process rather than the internal mechanics, they are taking on that liability for that.

2. Could easily argue the misalignment of the way Backtester vs Live uses the internally loaded data is less of an edge case/issue, than users using externally loaded data. Anyone using any informative pairs within 2 bars will hit this issue.
