### ISSUE TITLE
FreqAI - model performance summary/ exploring model(s) performance and insights in notebooks

### ISSUE THREAD

**Issue by konradsemsch** [freqtrade/freqtrade#7471]
Hi! Thanks a lot for the great work you brought in the FreqAI addition - really love the new setup! I have a question though: is there already a way (perhaps outside the main branch?) to get a summary of model(s) performance after training? Ideally, that could be somehow doen through a notebook, in order to understand how models are performing and how to improve the strategy. Is that already available somewhere/ on the radar?

**Comment by robcaulk** [comment]
Hello, I don't think there are any notebooks currently floating around. I personally do not use them - but the community would certainly welcome the contribution if you would like to make one. 

We have tensorboard integration into the RL branch for tracking [training performances](https://github.com/freqtrade/freqtrade/blob/09e834fa2124258e1ec0c9527d8fdd4c9133db47/docs/freqai.md#using-tensorboard). Using it with catboost is identical - a simple flag addition to `model_training_parameters`. I just havent documented it officially for catboost yet. Would welcome that contribution as well. 

Besides that - there is the trading performance metrics available via typical means (FreqUI). We also provide you with the entire prediction history dataframe in the model folder to analyze as you see fit (historic_predictions.pkl).

Better performance metrics would be a welcome contribution if you have the ability/interest. We have some other people thinking about better ways to report this information - best to join the freqAI discord and join the discussion if you are looking to get involved in that:

https://discord.gg/xE4RMg4QYw

Mention your intentions when you get there so I can connect you to the right people. 

Cheers,
Rob

**Comment by konradsemsch** [comment]
Thanks Rob, I'll join the channel and we'll take it from there :)
