### ISSUE TITLE
assigning plotting names on the fly

### ISSUE THREAD

**Issue by HeinrichHaller** [freqtrade/freqtrade#7483]
## Describe your environment

  * Operating system: Ubuntu LTS
  * Python Version: Python 3.10.7
  * CCXT version: ccxt==1.93.35
  * Freqtrade Version: freqtrade docker-8a236c3c
  
## Your question

I wanted for documentation/presentation show how certain filter are behaving with different parameter and wrote a loop in populate_indicators similar to this:
```
R = np.arange(1, 30, 3)
for i in R:
    res, _ = bii.ema(dataframe, R=i)
    name = f'ema_R_{i}'
    print(name)
    self.plot_config['main_plot']  = {name: {}}
    dataframe[name] = res
```
With trying to directly change the plot_config as well.

self.plot_config['main_plot']  = {name: {}}, 
does not throw an error, but does not work either because of the @property decorator  I think. 
Is there a workaround?

**Comment by xmatthias** [comment]
you don't HAVE to use a property - although that's the recommended way now - as it allows for flexible assignment from within the property.

best assign `self._plot_config` - and return that within the property.

alternatively remove it as property but keep it directly as attribute - which will also work (but will be overwritten if the config also has plot_config).

**Comment by HeinrichHaller** [comment]
I got it done - very plain - via the attribute approach. Replacing the @property with plot_config = {}. Out of curiosity, how to assign self._plot_config within the property?

**Comment by xmatthias** [comment]
well within a property - you usually don't.
a Property should not have side-effects - but only return data as requested (without modifying other things)

you could define a setter for a property (mostly a java pattern, but also available in python) - but i don't see why you'd do that - assigning `self._plot_config` from the strategy is not incorrect (the _ marks this as private by convention).
