### ISSUE TITLE
strategy reload

### ISSUE THREAD

**Issue by xarthurx** [freqtrade/freqtrade#7488]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.10
  * CCXT version: 1.92
  * Freqtrade Version: 2022.08
  
## Your question

I notice there's a feature for reloading `config` when a bot is running, and I was wondering if we can reload strategy or at least parameters that can be exposed.

Currently, if I want to run a opt / refitting process for the parameters of my strategy, I need to stop the bot and restart it again. 
However, this will lose time for re-collecting data. Is there a way to do it on the fly?
For instance, using `callback` to load a file?

**Comment by xmatthias** [comment]
reloading the configuration automatically also reloads the strategy.

That's implicit, as the strategy could be defined in the configuration - and as such could also have changed.
In fact, it performs an almost complete shutdown / restart - only leaving the outermost shell and restarting everything else, so you can change almost everything this way.
