### ISSUE TITLE
How to close a half position

### ISSUE THREAD

**Issue by byte-flylf** [freqtrade/freqtrade#7490]
## Describe your environment
Operating system: centos7
Python Version: Python 3.10.5___ (python -V)
CCXT version: _ccxt==1.93.66 (pip freeze | grep ccxt)
Freqtrade Version: freqtrade 2022.9.dev-873eb5f__ (freqtrade -V or docker-compose run --rm freqtrade -V for Freqtrade running in docker)
  
## Your question

If leverage is used, half of the closing position here is actually only half of the initial value

    def adjust_trade_position(self, trade: Trade, current_time: datetime,
                              current_rate: float, current_profit: float,
                              min_stake: Optional[float], max_stake: float,
                              current_entry_rate: float, current_exit_rate: float,
                              current_entry_profit: float, current_exit_profit: float,
                              **kwargs) -> Optional[float]:

        filled_entries = trade.select_filled_orders(trade.entry_side)
        count_of_entries = trade.nr_of_successful_entries

        if current_profit > 0.05 and trade.nr_of_successful_exits == 0:
            # Take half of the profit at +5%
            return -(trade.stake_amount / 2)

Orders generated from partial back testing：

          "profit_abs": 421.4452752,
          "exit_reason": "roi",
          "initial_stop_loss_abs": 1388.71,
          "initial_stop_loss_ratio": -0.198,
          "stop_loss_abs": 1368.52,
          "stop_loss_ratio": -0.198,
          "min_rate": 1315,
          "max_rate": 1340.69,
          "is_open": false,
          "enter_tag": "down >= 0.8",
          "is_short": true,
          "open_timestamp": 1663710300000,
          "close_timestamp": 1663711200000,
          "orders": [
            {
              "amount": 31.3,
              "safe_price": 1335.81,
              "ft_order_side": "sell",
              "order_filled_timestamp": 1663710300000,
              "ft_is_entry": true
            },
            {
              "amount": 3.1,
              "safe_price": 1316.39,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1663711200000,
              "ft_is_entry": false
            },
            {
              "amount": 28.2,
              "safe_price": 1322.41,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1663711200000,
              "ft_is_entry": false
            }
          ]
        },

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
yes, that seems to be the case - you should be able to get around that by multiplying that with `trade.leverage`.

i'm not sure if this might be better changed - it'd be a breaking change in behavior - one that could cause full exits accidentally ...

**edit** this will be changed soon with #7491 - which will be merged after creating the next release.
