### ISSUE TITLE
Please support futures trading on Bybit

### ISSUE THREAD

**Issue by liaogx** [freqtrade/freqtrade#7493]
## Describe your environment

 * Operating system: MacOS Monterey 12.5.1
 * Python Version: 3.8.5
 * CCXT version: 1.92.20
 * Freqtrade Version: freqtrade 2022.8 stable

## Describe the enhancement

`freqtrade.exceptions.OperationalException: Freqtrade does not support isolated futures on Bybit`

I got the above error when config futures bot on Bybit, hope futures trading is supported with Bybit.

**Comment by xmatthias** [comment]
Freqtrade supports binance, bittrex, ftx, gate, huobi, kraken and OKX for spot markets.
We also supports futures trading on binance, gateio and okx.

Should we aim to support further exchanges for futures trading, then it'll be for sure be exchanges we already support for spot trading.

We currently have no plans (nor capacity) to widen the range of supported exchanges for spot markets - so this is not something we'll consider anytime soon.

**Comment by liaogx** [comment]
Oh, but, why there is a file `bybit.py` under `../freqtrade/exchange/`. I think adding Bybit is nice for our community, now it has over 10 million users and all spot pairs has 0 trading fees. Also, I just searched  `bybit` on freqtrade discord, 224 discussions 😄

**Comment by xmatthias** [comment]
in theory, all exchanges ccxt supports will work with freqtrade - but that won't mean they're tested. Sometimes minor adjustments are necessary - which will go in such files.
having a file there doesn't mean it's supported, just that someone at least attempted to use it sometime in the past.

Popularity will not make more time in the day. 

You're however more than welcome to fully [test the exchange](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip) (start with spot - everything you need there is a prerequisite to even look at futures), provide eventually needed fixes in the form of PR's - and as such provide (ongoing?) community support for bybit.
Stoploss won't be necessary (but is obviously nice if easily possible).

Once we're sure spot trading works flawlessly - look at implementing the liquidation price formula for bybit (maybe it's identical to an existing one like okx/gate - maybe it's completely different) - and with that - we can have have futures support for bybit :)

**Comment by golosoff** [comment]
> Oh, but, why there is a file `bybit.py` under `../freqtrade/exchange/`. I think adding Bybit is nice for our community, now it has over 10 million users and all spot pairs has 0 trading fees. Also, I just searched `bybit` on freqtrade discord, 224 discussions 😄

HI? did u test bybit spot?

**Comment by xmatthias** [comment]
bybit spot doesn't provide historic candles - you're therefore limited to live trading (backtesting won't have data available).

**Comment by xmatthias** [comment]
Bybit spot should work in theory - although it doesn't support backtesting, as they don't provide historic ohlcv data via API.

**Comment by golosoff** [comment]
> Bybit spot should work in theory - although it doesn't support backtesting, as they don't provide historic ohlcv data via API.

Thx for your reply.

**Comment by djienne** [comment]
of course historical ohlcv data is available in the bybit API. It is also known as kline data.

https://bybit-exchange.github.io/docs/spot/v3/#t-querykline

I tried to naively update the FreqTrade source to skip the error "historic Kline data not available for Bybit" and it could download the last 1000 candles and work fine. It is possible to download any historical period but with max 1000 candles per call. But that's similar to Binance or other, so probably not very hard to fix for someone better than me.

**Comment by xmatthias** [comment]
> of course historical ohlcv data is available in the bybit API. It is also known as kline data.

This is wrong - the link you provided highlights this:
>  It only returns the results from latest 3500 candles regardless of what interval is specified 

![grafik](https://user-images.githubusercontent.com/5024695/208915708-e7a231df-fd1f-4f9e-9bf2-b0cd4be262dc.png)


As such - you can not really backtest, as you're limited to the last few days of data.

**Comment by djienne** [comment]
In daily that's almost 10 years of data (and Bybit has been there since 2018 or so). So I don't see the problem as long as the starting date is clearly specified in the backtest.

Without mentioning that Backtest and hyperopts with more than a few 1000s candles use tremendous amounts of RAM and are quite slow to run.
Also using short time frames (in my experience below H4) usually leads to unprofitable strategies on the long run. (the chance of being profitable is proportional to the size of your time frame). Of course you can always overfit your datasets and get profitable backtests for any timeframe using Hyperopt, that will miserably fail in live run (forward testing).

So yeah it is not really necessary / useful to have access to more than 3500 candles anyways

**Comment by xmatthias** [comment]
> So yeah it is not really necessary / useful to have access to more than 3500 candles anyways

This might be true for your usecase - but is clearly not generally applicable.

The most common timeframe i've seen in strategies is 5m - which would give you ~12.5 days of backtesting - in which you can't test anything.

**Comment by djienne** [comment]
I can guarantee nobody can be profitable  trading 5 min TF. (Long term, can be lucky on the short term of course).

**Comment by wizrds** [comment]
> I can guarantee nobody can be profitable trading 5 min TF. (Long term, can be lucky on the short term of course).

That's not necessarily for you to decide, and absolutely not enough of a reason to put further work into making sure Bybit works all around.

**Comment by djienne** [comment]
Also it is possible that the V1 version of the spot by it rest api is not affected by this limitation. At least I did not see it written like in the V3.

**Comment by djienne** [comment]
To be comprehensive, the only proven way to be profitable trading low time frames is to do market making strategies, having access to a high fee tier (VIP) and to be paid for it (market making service) by an exchange.
