### ISSUE TITLE
Callback returning from an error interpreted as True (rather than fail-safe) - can this convention be changed?

### ISSUE THREAD

**Issue by winginitau** [freqtrade/freqtrade#7494]
* Operating system: Ubuntu 22.04 server fully patched
  * Python Version: 3.10.6
  * CCXT version: 1.93.35
  * Freqtrade Version: 2022.9.dev-92a32ab31
  
## Your question

An error in my cutom code called from confirm_trade_exit was interpreted by freqtrade as "True" (selling everything!). Is there some way to change the default behviour or a better approach, or is it really just python convention and needing to test my code better? 

My pattern:
- Custom tensorflow ML model generates enter and exit signals (integrated like a TA in populate_*)
- DCA-like position entries via adjust_trade_position, including step-wise unwinding of positions with -ve adjustments
- confirm_trade_exit simply returns boolean from call to my PositionKeeper module. 
- exit nornally denied (unless it is the last position to exit). Instead adjust_trade_position fires orders via -ve position adjust unless it is the last one where confirm_trade_exit closes the trade.

In this case an error in my code occurred. The exception was not caught. confirm_trade_exit returned the result (the error exception?) which freqtrade interpreted as "True"? and exited the trade. 

I went to dinner for my son's birthday. When arrived back, the whole portfolio had been sold! :) Good excuse for a reset.

It all makes sense from a code perspective, however it is the opposite to a "fail-safe" situation. 

Suggestions for alternate approach very welcome. 

Many thanks in advance. 

Calling code that ran:
```
    def confirm_trade_exit(self, pair: str, trade: 'Trade', order_type: str, amount: float,
                           rate: float, time_in_force: str, exit_reason: str,
                           current_time: 'datetime', **kwargs) -> bool:
        """
        """
        dataframe, _ = self.dp.get_analyzed_dataframe(trade.pair, self.timeframe)
        return pk.confirm_exit(pair, exit_reason, dataframe, rate)
```
pk is instance of PositionKeeper (my own module).

Manually promoted from dev, I missed one argument change 'amount'.

Last line of calling code should have been:
```
        return pk.confirm_exit(pair, exit_reason, dataframe, rate, amount)
```

Result (repeated for every open trade - 12x of them in this case with only toy money for live testing). 

```
2022-09-28 10:12:13,307 - freqtrade.freqtradebot - INFO - Exit for LINK/BUSD detected. Reason: exit_signal Tag: sell_signal_tann
2022-09-28 10:12:13,840 - freqtrade.wallets - INFO - Wallets synced.
2022-09-28 10:12:13,841 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error PositionKeeper.confirm_exit() missing 1 required positional argument: 'amount' calling <bound method Prod3.confirm_trade_exit of <Prod3.Prod3 object at 0x7ffb935d87c0>>
Traceback (most recent call last):
  File "/home/brendan/git/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
    return f(*args, **kwargs)
  File "/home/brendan/git/freqtrade/user_data/strategies/Prod3.py", line 712, in confirm_trade_exit
    return pk.confirm_exit(pair, exit_reason, dataframe, rate)
TypeError: PositionKeeper.confirm_exit() missing 1 required positional argument: 'amount'
2022-09-28 10:12:14,119 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 147, 'exchange': 'Binance', 'pair': 'LINK/BUSD', 'leverage': 1.0, 'direction': 'Long', 'gain': 'profit', 'limit': 7.935, 'order_type': 'market', 'amount': 2.02, 'open_rate': 7.884, 'close_rate': 7.935, 'current_rate': 7.935, 'profit_amount': 0.07902034, 'profit_ratio': 0.0049581, 'buy_tag': 'buy_signal_tann', 'enter_tag': 'buy_signal_tann', 'sell_reason': 'sell_signal_tann', 'exit_reason': 'sell_signal_tann', 'open_date': datetime.datetime(2022, 9, 28, 10, 6, 12, 52238), 'close_date': datetime.datetime(2022, 9, 28, 10, 12, 14, 119667), 'stake_amount': 15.92568, 'stake_currency': 'BUSD', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0}
2022-09-28 10:12:14,119 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=147, pair=LINK/BUSD, amount=2.02000000, is_short=False, leverage=1.0, open_rate=7.88400000, open_since=2022-09-28 10:06:12)
2022-09-28 10:12:14,296 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=147, pair=LINK/BUSD, amount=2.02000000, is_short=False, leverage=1.0, open_rate=7.88400000, open_since=2022-09-28 10:06:12) [sell]: 4.437e-05 BNB - rate: 0.0007509
2022-09-28 10:12:14,296 - freqtrade.persistence.trade_model - INFO - Updating trade (id=147) ...
2022-09-28 10:12:14,296 - freqtrade.persistence.trade_model - INFO - MARKET_SELL has been fulfilled for Trade(id=147, pair=LINK/BUSD, amount=2.02000000, is_short=False, leverage=1.0, open_rate=7.88400000, open_since=2022-09-28 10:06:12).

... etc ...
```

**Comment by xmatthias** [comment]
The convention could be changed - but we will not be changing this - as this would represent an increased risk to user capital.

The way the bot worked is perfect and as designed and documented.

---

If you don't implement this callback, then you implicitly accept all exit signals (so the default is True).

Now the strategy get's control to prevent exits via this callback. 
To actually reach this callback, your strategy will have produced an exit signal (either via exit signal, or as ROI / stoploss).

This callback is however not defined to "prevent all exits unless i like them". It's often used this way - but there will have been a reason for the strategy to generate an exit signal - and if you encounter many situations where you block the exit, you should rethink your exit signals in general.

If your strategy now fails to process this signal properly - we will assume the default for the callback as "accept exit".

The alternative (default to `False`) would represent a much higher risk - as that would effectively block ALL exits due to a strategy error.

Imagine the same situation - but the market tanks. 
You'll expect your stoplosses to be acted on - protecting your capital (so there's actual capital left to reenter trades at potentially better prices).

The changed default would mean that your strategy fails - and the strategy/bot holds on to all positions - causing losses of 50%, 70%or 90% (or however much...). It'll also miss the stoploss you set at 10% - so your whole risk management will no longer work - and you're effectively risking 100% of your capital all the time (you can always make a mistake).

What happened to you is a perfect demonstration that freqtrade - as trading framework - did it's job exactly as it was expected to (also handling faulty strategies in a correct manner).

---

You can catch errors yourself within the callback (a generic try/catch block will do) - but if you encounter the above scenario, it's your fault as strategy author - not the fault of a framework using wrong defaults, and therefore risking all of the user's capital.

**Comment by winginitau** [comment]
_"The way the bot worked is perfect and as designed and documented."_

I love you guys, yes it did and it is very good! 

_"To actually reach this callback, your strategy will have produced an exit signal"_
Yes. 

_"if you encounter many situations where you block the exit, you should rethink your exit signals in general."_

Agree if strategy is algo only. My signals are generated from an esemble of deep learning models, and, as is the nature of deep learning ML, they are not precise (and arguably will never be). However they produce useful trade "indicators" that then need to be filtered through trading logic, thus the extended position keeping logic. 

_"The alternative (default to False) would represent a much higher risk - as that would effectively block ALL exits due to a strategy error.
Imagine the same situation - but the market tanks.
You'll expect your stoplosses to be acted on - protecting your capital (so there's actual capital left to reenter trades at potentially better prices).:
... and you're effectively risking 100% of your capital all the time (you can always make a mistake)."_

Ok understood. This makes sense and I now see your logic in this being the better fail safe. 

_"You can catch errors yourself within the callback (a generic try/catch block will do) - but if you encounter the above scenario, it's your fault as strategy author - not the fault of a framework using wrong defaults, and therefore risking all of the user's capital."_

Yes, new prototype code not fully protected. 

Many thanks for reply. There is always so much more to learn about freqtrade! I certantly did not mean any disrespect to freqtrade and the great work you do.

In fact it is a good and refreshing lesson for me (and certainly more exiting than the market doldrums of the last 1.5 weeks!) 

Many thanks
Brendan

**Comment by winginitau** [comment]
![image](https://user-images.githubusercontent.com/31975164/192790846-b2033214-38b4-4405-af65-3985d8d9af92.png)

**Comment by xmatthias** [comment]
> I certantly did not mean any disrespect to freqtrade and the great work you do.

never took it this way. 
What you expect is usually dependent on the outcome - in this case, staying in the trades might've been the better alternative (market went your way) - but we always have to assume the worst case - where a failure (especially in this callback) would lead to excessive losses way beyond an eventually configured stoploss.


---

On a side-note - you might want to check out freqAI - specifically #7289 - which aims to integrate RL support directly into freqtrade.

**Comment by winginitau** [comment]
_"What you expect is usually dependent on the outcome - in this case, staying in the trades might've been the better alternative (market went your way) - but we always have to assume the worst case - where a failure (especially in this callback) would lead to excessive losses way beyond an eventually configured stoploss."_

Fully understand. Getting out is priority. Re: what you would expect - its a constant battle between psychology, confirmation bias, FOMO .... and reality! 

_"On a side-note - you might want to check out freqAI - specifically https://github.com/freqtrade/freqtrade/pull/7289 - which aims to integrate RL support directly into freqtrade."_

Looks interesting. I'll will reach out to get involved. Saw the FreqAI feature and had a cursory look but set it aside as I'm already 6 months into my own framework with 20k lines of code, most of it wrapped around tensorflow, keras and freqtrade.
Willing, but not a competent git collaborator and embarressed about my code. 
CompSci in 1994 with cryptanalysis and ANN specialties but only tinkered professionally. Competent ANSI C embedded from a later revisit/adventure. But Python - like putting a sovereign military in the hands of a 12 year old!

Thanks again for all the work you do on this project.
