### ISSUE TITLE
Reasons why exit orders doesn't get executed

### ISSUE THREAD

**Issue by italodamato** [freqtrade/freqtrade#7496]
## Describe your environment

  * Operating system: MacOS 12.4
  * Python Version: 3.10.4
  * CCXT version: 1.92.20
  * Freqtrade Version: 2022.9.dev-191344e
  
## Your question

What are the possible reasons why an exit long order doesn't get executed? I have entry long order and exit long but the first sell order doesn't work. The exit gets executed only at a later signal.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/45588475/192898140-b554f04b-3a98-4e03-b27e-16ab0d5871d1.png">

**Comment by xmatthias** [comment]
there's several parameters that can influence this - based on your chart - i'd say the most likely one is `    `exit_profit_only` - and / or `exit_profit_offset`.

Colliding long-entry signal could also cause this - the chart would show this though - at least if you hide sells.

you could obviously also have the  `confirm_exit` callback implemented - but since you're asking i'd doubt this.
custom order pricing, and as consequence, order timeouts can also cause this  ...

**Comment by italodamato** [comment]
I have the following:
- `exit_profit_only = False` 
- `confirm_exit` is not implemented
- no entry signals triggered near the exit signal

Can you expand on what you mean by "custom order pricing"?

**Comment by xmatthias** [comment]
well - [custom order pricing](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-price-rules) - which could cause timeouts.

What i've otherwise often seen when signals are not respected when they clearly should be is that the strategy used to generate the plot doesn't 100% correspond to the strategy used to create the trades (either database or backtesting file).

**Comment by italodamato** [comment]
> well - [custom order pricing](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-price-rules) - which could cause timeouts.

I haven't implemented either of those methods.

>What i've otherwise often seen when signals are not respected when they clearly should be is that the strategy used to generate the plot doesn't 100% correspond to the strategy used to create the trades (either database or backtesting file).

What do you mean exactly? Also the backtesting results show a single trade instead of 2

Is there anything I could log to help troubleshoot where the selling logic gets stopped?

**Comment by xmatthias** [comment]
plotting assumes that backtesting was ran "right before" - and that the same parameters (timerange, ...) has been used.
if that's not the case, indicator values may differ (which is a different problem with the indicators per se).
The point here is that the circumstances for backtesting and plotting changed.

> `exit_profit_only`

This setting could also come from the config ... usually "full logs" from the backtesting run will help with such generics - as it clears these things out.

there's also `use_exit_signal` - which i'd however assume you have set to true, based on the executed exit.

**Comment by italodamato** [comment]
Yes I've double checked the logs: 
- exit_profit_only = False
- use_exit_signal = True

>plotting assumes that backtesting was ran "right before" - and that the same parameters (timerange, ...) has been used.
if that's not the case, indicator values may differ (which is a different problem with the indicators per se).
The point here is that the circumstances for backtesting and plotting changed.

I use a custom function to backtest and plot at once so that's not an issue
```
function back_plot_pair2() {
    source ~/Documents/GitHub/freqtrade-1/.env/bin/activate
    freqtrade backtesting \
        --userdir ~/Documents/GitHub/freqtrade/user_data \
        --strategy-path ~/Documents/GitHub/freqtrade/user_data/strategies \
        --strategy-list MyStrategy \
        --timerange 20200101- \
        --config ~/Documents/GitHub/freqtrade/user_data/configs/config.json \
        --config ~/Documents/GitHub/freqtrade/user_data/configs/binance-usdt-static.json \
        --export trades \
        -p $1/USDT
    freqtrade plot-dataframe \
        --userdir ~/Documents/GitHub/freqtrade/user_data \
        --strategy-path ~/Documents/GitHub/freqtrade/user_data/strategies \
        --strategy MyStrategy \
        --timerange 20200101- \
        --config ~/Documents/GitHub/freqtrade/user_data/configs/config.json \
        --config ~/Documents/GitHub/freqtrade/user_data/configs/binance-usdt-static.json \
        -p $1/USDT
}
```

**Comment by xmatthias** [comment]
if you can isolate the backtest to this one trade (basically via timerange/pair filters) - you could run backtesting with `-v` to get verbose logs - which might help identify the actual exit signal triggerings.
Running that with multiple trades may get messy  (especially if it's parallel trades), and would probably not lead to much new leads.

I still think that the most likely cause is a colliding signal - but plotting should show this with exit-signals disabled.

**Comment by xmatthias** [comment]
Did you find anything new in this regards?

Otherwise i guess we can close this issue - as all reasons have been outlined above - and we received no logs - so there's nothing on my side to check further.

**Comment by italodamato** [comment]
Hey sorry, I got caught up with other stuff. I don't have time to look into this but I can guarantee there are no colliding signals in my strategy by design.

**Comment by xmatthias** [comment]
I can guarantee the only reasons for a "non-actioned" signal are the ones outlined in this thread.

If you suspect that's not the case, please provide
* full logs of the backtest run (they often tell secret tales ...)
* a minimal strategy / config combination (and the exact command run) that will show this behavior

Without this, i see this issue as "non actionable and answered" - as there's nothing further we can provide you with in that case.

**Comment by xmatthias** [comment]
I'm gonna close this issue for now.
feel free to reopen / comment below should this still be an issue and you find time to update us with the requested info above.
