### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by moooaaazzz** [freqtrade/freqtrade#7501]
## Describe your environment

  * Operating system: 64-bit operating system, x64-based processor
  * Python Version:  3.10.5
  * CCXT version:  1.93.111
  * Freqtrade Version:  freqtrade 2022.8 (Docker)
  
## Your question
I have downloaded the docker image and able to run it. However, it is showing me import errors in the strategy file. How can I resolve it?

![image](https://user-images.githubusercontent.com/114662506/193019868-080bcf94-60a0-4fe9-b9b4-340960df2735.png)

**Comment by xmatthias** [comment]
well you'll basically have to tell vscode to use an environment where freqtrade is installed.

With docker, that's "slightly" tricky - but i think with the vscode remote extension this should be possible - so vscode connects to the docker-container.
