### ISSUE TITLE
No update with docker 2022.9

### ISSUE THREAD

**Issue by batuhanhazarguler** [freqtrade/freqtrade#7503]
* Operating system: Ubuntu 22.04.1 LTS
  * Python Version: 3.10.4 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.8 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi my friends

docker compose pull doesnt work, still the version has not changed.
can i update it another way? Or do I need to update?

thanks..

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by stash86** [comment]
If you are on stable, then I think 2022.9 hasn't been released yet. Just wait

**Comment by xmatthias** [comment]
CI takes a bit to complete. 
The image will be available now.
