### ISSUE TITLE
Exit order is canceled due to a timeout 

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#7504]
## Describe your environment

  * Operating system: _Docker___
  * Python Version: ___3.10.7
  * CCXT version: ___1.93.35
  * Freqtrade Version: ___docker-8116ca84
  
What solution would you recommend for a situation where an exit order is canceled due to a timeout and the exit condition is not met/triggered post this period?
Is there any method for "chase orders" maybe?

**Comment by stash86** [comment]
1. Use lower rate for long exit, or higher rate for short exit (custom_exit_price)
2. Use orderbook, get 2nd or 3rd price
3. Use market order

**Comment by xmatthias** [comment]
in usual cases, using `"price_side"="other"` is sufficient to get almost instant fills - as such orders will react similar to market orders, and will almost always (although not 100% of the time) fill immediately.

there's also `exit_timeout_count` - which triggers an emergency exit (defaults to market) should an exit be canceled for X amounts of time. I guess you could set that to 1 to have it trigger after the first cancel.

in general though, you'll have to think if it's really what you want - assuming the exit is a regular exit signal - then the strategy decided to "no longer sell".

**Comment by darioneto** [comment]
ok great, thanks guys, exit_timeout_count seems like the best option at this time for exits. 
As for the entry equivalent. Is there anything similar?

**Comment by xmatthias** [comment]
no - but there's no point. 

If your entry fails and the signal is gone - the trade will be deleted (your strategy considers it no longer a good trade).

**Comment by darioneto** [comment]
The order fils fails due to the fact the exchange rejects the order at the first attempt at the limit. It doesn't mean it's a bad trade.  It would be preferable to enter at limit else at the market. The analogical approach of "entry_timeout_count" would enter the market if the limit fails.  I haven't seen any other better methods in the documentation though.
The ideal situation would be the execution of chase limit orders if it's on the roadmaps in the foreseeable future.

**Comment by xmatthias** [comment]
you get to control pricing - as well as the possibility to replace orders (just read through the whole [callbacks docs](https://www.freqtrade.io/en/latest/strategy-callbacks/) - so you are obviously free to retry at a higher price.

If an order is cancelled - and the entry signal is gone - it's correct to not retry (otherwise the strategy would still signal to still enter).

**Comment by stash86** [comment]
You can also use short limit timeout, for example 5s. If your limit entry doesn't get filled within 5s, the bot would retry with new current price, assuming you are still on the same candle that has entry signal

**Comment by darioneto** [comment]
@stash86 , are you referring to unfilledtimeout (entry/exit)? Those I have set to 2 min so there is a chance to retry within a relatively short window, the signals are still active. Typically I see about 40% of orders are canceled by the exchange. Some of them are filled after retry but some are missed. Missing the entry signal is not as bad as exit though.
