### ISSUE TITLE
CCXT Pro - Websocket

### ISSUE THREAD

**Issue by minhluu0907** [freqtrade/freqtrade#7510]
CCXT Pro is merging to free version. Can you consider to integrate websocket data into live trading mode, because polling approach is not efficient enough when pairlist gets bigger and bigger
https://github.com/ccxt/ccxt/pull/15085

**Comment by xmatthias** [comment]
It's not yet merged - therefore it's not relevant at this moment.

We will eventually also utilize further capabilities of ccxt - but it's pointless to ask before it's actually available.

**Comment by minhluu0907** [comment]
It's merged. Waiting for this big change

**Comment by popperwin** [comment]
Hello,
Is there any update on the use of Websocket to fetch live OHLCV data? It would be very useful for larger pairlist with a lot of timeframes.
Thanks :)

**Comment by tolgakaratas** [comment]
Hello,
"What is the current status of websocket integration in CCXT PRO?"
