### ISSUE TITLE
Strange trade result(positive trade counted like loss) on backtesting

### ISSUE THREAD

**Issue by rongybika** [freqtrade/freqtrade#7513]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.8.10 (`python -V`)
  * CCXT version: 1.92.52 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.8(`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Hi,
I'm trying to backtest some strategy. When I'm looking to the plotted dataframe more closer I'm noticed that looks something strange/wrong.
How we can see on the screenshot, there is a simulated trade that must be Profit-Exit. And is more like that on the dataframe.

I've searched for the trade:

{"pair":"BTC/BUSD",
"stake_amount":318.7698848,
"amount":0.01489,
"open_date":"2022-07-17 08:45:00+00:00",
"close_date":"2022-07-17 09:00:00+00:00",

"open_rate":21408.32,
"close_rate":21447.92,

"fee_open":0.001,"fee_close":0.001,"trade_duration":15,
"profit_ratio":-0.00015194965188560067,
"profit_abs":-0.04848541,
"exit_reason":"exit_signal",

"initial_stop_loss_abs":214.09,
"initial_stop_loss_ratio":-0.99,
"stop_loss_abs":214.09,"stop_loss_ratio":-0.99,"min_rate":21387.32,"max_rate":21468.34,"is_open":false,"enter_tag":null,"is_short":false,"open_timestamp":1658047500000,"close_timestamp":1658048400000,"orders":[{"amount":0.01489,"safe_price":21408.32,"ft_order_side":"buy","order_filled_timestamp":1658047500000,"ft_is_entry":true},{"amount":0.01489,"safe_price":21447.92,"ft_order_side":"sell","order_filled_timestamp":1658048400000,"ft_is_entry":false}]},

Maybe I couldn't notice something but for me looks like something wrong with the result because was counted like a loss.
Is this happening for anybody else?

Thank you

### Steps to reproduce:

  1. Backtesting

  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

![image](https://user-images.githubusercontent.com/14143598/193466855-3993c35c-b5b2-4ce0-8021-25570460a2d0.png)
  ```
  
  ```

**Comment by xmatthias** [comment]
The observed pricechange (from open to close) **change** here is ~0.1%.

Backtesting takes fees [into account](https://www.freqtrade.io/en/stable/bot-basics/#fee-handling) - and will be using the exchange's default fees. 

For binance, that'd be 0.1% (exactly your profit) _per order_ - so once fees are subtracted twice (once for the entry, once for the exit) - your trade is slightly losing - even though price moved in your favor.

Trading without fees would be simple - but does not reflect reality.
