### ISSUE TITLE
From which library can I import 'Optional' module?

### ISSUE THREAD

**Issue by pizzidellamaremma** [freqtrade/freqtrade#7514]
Hi! I'm trying to use `custom_exit_price` but i don't know where to import `Optional` from. 

I think it should be added to the page: https://www.freqtrade.io/en/2022.9.1/strategy-callbacks/#custom-order-entry-and-exit-price-example

**Comment by xmatthias** [comment]
The import is `from typing import Optional`.

if you use either the `new-strategy` command, or use the sample strategy, the symbol will already be imported.

As such, it's unnecessary to include this in all examples - as it'll bloat the example code - drawing focus away from what is actually important.
