### ISSUE TITLE
Cant use custom_entry_price - bot stoppes 

### ISSUE THREAD

**Issue by Arivadis** [freqtrade/freqtrade#7531]
Hi everybody,

I tried to use custom_entry_price - but bot does not even start( 3 first seconds only)
The bot takes strategy without this funktion (do not know if it works as strategy) but container keeps running.
Seems, something wrong with my setting or anything alse.

I'v been tring to reach the problem, but have no chance to get what is wrong.

The strategy cant be ranned even with empty custom_entry_price condition that returns float number.
strategy --- 

# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement
# flake8: noqa: F401
# isort: skip_file
# --- Do not remove these libs ---
import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame

from freqtrade.strategy import (BooleanParameter, CategoricalParameter, DecimalParameter,
                                IStrategy, IntParameter)

# --------------------------------
# Add your lib to import here

from datetime import datetime, timedelta, timezone
from freqtrade.persistence import Trade
import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib

# This class is a sample. Feel free to customize it.
class SampleStrategy(IStrategy):

    INTERFACE_VERSION = 3
    can_short: bool = False
    minimal_roi = {
        "0": 100
    }

    stoploss = -0.015
    trailing_stop = True
    trailing_stop_positive = 0.03
    trailing_stop_positive_offset = 0.05

    timeframe = '1m'
    process_only_new_candles = True
    use_exit_signal = False
    exit_profit_only = False
    ignore_roi_if_entry_signal = True
    buy_rsi = IntParameter(low=1, high=50, default=30, space='buy', optimize=True, load=True)
    sell_rsi = IntParameter(low=50, high=100, default=70, space='sell', optimize=True, load=True)
    short_rsi = IntParameter(low=51, high=100, default=70, space='sell', optimize=True, load=True)
    exit_short_rsi = IntParameter(low=1, high=50, default=30, space='buy', optimize=True, load=True)
    startup_candle_count: int = 30
    order_types = {
        'entry': 'limit',
        'exit': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }
    order_time_in_force = {
        'entry': 'gtc',
        'exit': 'gtc'
    }
    plot_config = {
        'main_plot': {
            'tema': {},
            'sar': {'color': 'white'},
        },
        'subplots': {
            "MACD": {
                'macd': {'color': 'blue'},
                'macdsignal': {'color': 'orange'},
            },
            "RSI": {
                'rsi': {'color': 'red'},
            }
        }
    }

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        if self.dp:
            if self.dp.runmode.value in ('live', 'dry_run'):
                ob = self.dp.orderbook(metadata['pair'], 1)
                dataframe['best_bid'] = ob['bids'][0][0]
                dataframe['best_ask'] = ob['asks'][0][0]

        hilbert = ta.HT_SINE(dataframe)
        dataframe['htsine'] = hilbert['sine']
        dataframe['htleadsine'] = hilbert['leadsine']
        dataframe['sar'] = ta.SAR(dataframe)
        dataframe['tema'] = ta.TEMA(dataframe, timeperiod=9)
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband'] = bollinger['lower']
        dataframe['bb_middleband'] = bollinger['mid']
        dataframe['bb_upperband'] = bollinger['upper']
        dataframe["bb_percent"] = (
                (dataframe["close"] - dataframe["bb_lowerband"]) /
                (dataframe["bb_upperband"] - dataframe["bb_lowerband"])
        )
        dataframe["bb_width"] = (
                (dataframe["bb_upperband"] - dataframe["bb_lowerband"]) / dataframe["bb_middleband"]
        )
        dataframe['mfi'] = ta.MFI(dataframe)

        stoch_fast = ta.STOCHF(dataframe)
        dataframe['fastd'] = stoch_fast['fastd']
        dataframe['fastk'] = stoch_fast['fastk']
        dataframe['rsi'] = ta.RSI(dataframe)
        dataframe['adx'] = ta.ADX(dataframe)

        dataframe['direction_1'] = self.supertrend(dataframe, multiplier=1, period=10)['ST']
        dataframe['direction_0.5'] = self.supertrend(dataframe, multiplier=0.5, period=10)['ST']

        return dataframe

     def custom_entry_price(self, pair: str, current_time: datetime, proposed_rate: float,
                            entry_tag: Optional[str], side: str, **kwargs) -> float:
     
         dataframe, last_updated = self.dp.get_analyzed_dataframe(pair=pair,
                                                                  timeframe=self.timeframe)
         lalst_candle_1 = dataframe['direction_1'].iat[-1]
         candle_before_1 = dataframe['direction_1'].iat[-2]
         lalst_candle_05 = dataframe['direction_1'].iat[-1]
         candle_before_05 = dataframe['direction_1'].iat[-2]
         new_entryprice = dataframe['low'].iat[-1]
         my_price = 0.0
     
         if lalst_candle_1 < 0 < candle_before_1 and lalst_candle_05 < 0 < candle_before_05:
             my_price = new_entryprice + (new_entryprice * 0.005)
     
         return my_price

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (dataframe['direction_1'] < 0) &
            (dataframe['direction_1'].shift(1) > 0) &
            (dataframe['direction_0.5'] < 0) &
            (dataframe['direction_0.5'].shift(1) > 0)
            ,
            "enter_long"] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (dataframe['direction_1'] > 0) &
            (dataframe['direction_1'].shift(1) < 0) &
            (dataframe['direction_0.5'] > 0) &
            (dataframe['direction_0.5'].shift(1) < 0)
            ,
            "exit_long"] = 1

        return dataframe

    def supertrend(self, dataframe: DataFrame, multiplier, period):
        df = dataframe.copy()

        df['TR'] = ta.TRANGE(df)
        df['ATR'] = ta.SMA(df['TR'], period)

        st = 'ST_' + str(period) + '_' + str(multiplier)
        stx = 'STX_' + str(period) + '_' + str(multiplier)

        # Compute basic upper and lower bands
        df['basic_ub'] = (df['high'] + df['low']) / 2 + multiplier * df['ATR']
        df['basic_lb'] = (df['high'] + df['low']) / 2 - multiplier * df['ATR']

        # Compute final upper and lower bands
        df['final_ub'] = 0.00
        df['final_lb'] = 0.00
        for i in range(period, len(df)):
            df['final_ub'].iat[i] = df['basic_ub'].iat[i] if df['basic_ub'].iat[i] < df['final_ub'].iat[i - 1] or \
                                                             df['close'].iat[i - 1] > df['final_ub'].iat[i - 1] else \
                df['final_ub'].iat[i - 1]
            df['final_lb'].iat[i] = df['basic_lb'].iat[i] if df['basic_lb'].iat[i] > df['final_lb'].iat[i - 1] or \
                                                             df['close'].iat[i - 1] < df['final_lb'].iat[i - 1] else \
                df['final_lb'].iat[i - 1]

        # Set the Supertrend value
        df[st] = 0.00
        for i in range(period, len(df)):
            df[st].iat[i] = df['final_ub'].iat[i] if df[st].iat[i - 1] == df['final_ub'].iat[i - 1] and df['close'].iat[
                i] <= df['final_ub'].iat[i] else \
                df['final_lb'].iat[i] if df[st].iat[i - 1] == df['final_ub'].iat[i - 1] and df['close'].iat[i] > \
                                         df['final_ub'].iat[i] else \
                    df['final_lb'].iat[i] if df[st].iat[i - 1] == df['final_lb'].iat[i - 1] and df['close'].iat[i] >= \
                                             df['final_lb'].iat[i] else \
                        df['final_ub'].iat[i] if df[st].iat[i - 1] == df['final_lb'].iat[i - 1] and df['close'].iat[i] < \
                                                 df['final_lb'].iat[i] else 0.00
        # Mark the trend direction up/down
        df[stx] = np.where((df[st] > 0.00), np.where((df['close'] < df[st]), 'down', 'up'), np.NaN)

        # Remove basic and final bands from the columns
        df.drop(['basic_ub', 'basic_lb', 'final_ub', 'final_lb'], inplace=True, axis=1)

        df.fillna(0, inplace=True)

        return DataFrame(index=df.index, data={
            'ST': df[st],
            'STX': df[stx]
        })

config -----

{
    "max_open_trades": 1,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 51,
        "exit": 51,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "bbdfb79e89a568231ca479c01108d4d5bade0693fa44c6cefbc715bd93a8a8da",
        "ws_token": "Hrblr-5wWpyYiuUPJViWJAk50jMvcpTPbA",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "123456789"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

yml -------

---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy

- log

2022-10-03 18:39:39,613 - freqtrade - INFO - freqtrade 2022.9.1
2022-10-03 18:39:39,878 - freqtrade.worker - INFO - Starting worker 2022.9.1
2022-10-03 18:39:39,878 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/config.json ...
2022-10-03 18:39:39,886 - freqtrade.loggers - INFO - Verbosity set to 0
2022-10-03 18:39:39,888 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2022-10-03 18:39:39,889 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2022-10-03 18:39:39,890 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2022-10-03 18:39:39,891 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
2022-10-03 18:39:39,892 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 1 ...
2022-10-03 18:39:39,943 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2022-10-03 18:39:39,945 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2022-10-03 18:39:39,946 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-10-03 18:39:39,961 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2022-10-03 18:39:39,962 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-10-03 18:39:39,996 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/sample_strategy.py due to 'name 'Optional' is not defined'
2022-10-03 18:39:39,997 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'SampleStrategy'. This class does not exist or contains Python code errors.
2022-10-03 18:39:39,998 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 36, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 62, in __init__
    self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 47, in load_strategy
    strategy: IStrategy = StrategyResolver._load_strategy(
  File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 266, in _load_strategy
    raise OperationalException(
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'SampleStrategy'. This class does not exist or contains Python code errors.

What the problem is it?
Could You please help me to solve the problem?

I You will find any additional mistakes or have a piece of advice for me - I will be happy.

Have a nice day!

**Comment by xmatthias** [comment]
> 2022-10-03 18:39:39,996 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/sample_strategy.py due to 'name 'Optional' is not defined'

Your strategy file is invalid.
You can import optional from the typing module (`from typing import Optional` at the top of the file).

This is also already included when creating a new strategy via `new-strategy` command (basically when following the [documentation](https://freqtrade.io/)

**Comment by Arivadis** [comment]
I told you, my mistake 100%
