### ISSUE TITLE
after hyperparameter optimization, i got market change 0.00%

### ISSUE THREAD

**Issue by finchatftm** [freqtrade/freqtrade#7532]
## Describe your environment

  * Operating system: WIN10 X64
  * Python Version: 3.10.7
  * CCXT version: 1.93.3
  * Freqtrade Version: 2022.9.dev
  
## Your question
![Snipaste_2022-10-04_11-07-39](https://user-images.githubusercontent.com/69079511/193727141-65320898-40a1-4080-9b5b-42cb169dbe4d.png)
After hyperparameter optimization, i run 'freqtrade hyperopt-show -n 8' , and got market change 0.00% in SUMMARY METRICS， and the backtest result which used recommand parameters, i got a different results from hyperparameter optimization.

**Comment by xmatthias** [comment]
market change is not a metric that's calculated during hyperopt - therefore it'll show as 0.

if you use backtesting - it'll show correctly.

**Comment by finchatftm** [comment]
> 
but i also got a different total profit

**Comment by finchatftm** [comment]
![Snipaste_2022-10-04_13-38-52](https://user-images.githubusercontent.com/69079511/193743788-b1bc2905-d5f7-4547-9616-00e3f1f068cf.png)
![Snipaste_2022-10-04_13-39-14](https://user-images.githubusercontent.com/69079511/193743800-c3591cdc-bb2c-4152-9e3b-ab27a4690f70.png)
11.54% is hyperopt results, and 7.59% is my backtest results

**Comment by xmatthias** [comment]
`freqtrade hyperopt-show -n 8` will show you the results for epoch 8.

if epoch 8 was not the best epoch - it's parameters not be used for backtestin, but the parameters for the best epoch will be used instead.
You should therefore use 
`freqtrade hyperopt-show -n 8` - followed by `freqtrade backtesting ...` (using the same parameters you used for hyperopt, obviously) to align results. (hyperopt-show will re-write the parameters file).

You'll need to be slightly careful if "protections" was one of the parameters - as that automatically sets `--enable-protection` - so you need to make sure backtesting uses that parameter, too (it will not by default).
