### ISSUE TITLE
customize_exit_price not working with hyperopt

### ISSUE THREAD

**Issue by xarthurx** [freqtrade/freqtrade#7533]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.10 (`python -V`)
  * CCXT version: 1.93 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.9 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
When using the example of `custom_exit_price` from the website:
https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-entry-and-exit-price-example
in `backtesting` or `trade`, everything is fine.

But when using it with `hyperopt`, I got the error:
```
Could not import <strategy> due to 'name 'Trade' is not defined'
```

How should I correctly use `customize_exit_price` with `hyperopt`?

**Comment by xmatthias** [comment]
The error implies that you're missing the import (`from freqtrade.persistence import Trade`). That'd also mean / suggest that the same strategy will not work in other modes.

If that's not the case, we'll need a full log/exception to know where and when the error happens.

**Comment by xarthurx** [comment]
Ah damit, I just copy/past the function and forgot about the imports...
Sorry for nothing, my silly fault.
