### ISSUE TITLE
Leverage not considered when entering/executing trade

### ISSUE THREAD

**Issue by mciepluc** [freqtrade/freqtrade#7534]
## Describe your environment

  * Operating system: All
  * Python Version: All
  * CCXT version: 1.93.90
  * Freqtrade Version: 2022.9

## Describe the problem:

Leverage is not used correctly when ```check_order_replace```/```replace_order``` is called. Provided code snippet fixes this behavior.

### Observed Results:

  * Observed change in stake amount when leverage used
  * Stake amount should not change

### Relevant code exceptions or logs

  ```Python
--- a/freqtrade/freqtradebot.py
+++ b/freqtrade/freqtradebot.py
@@ -1308,7 +1308,7 @@ class FreqtradeBot(LoggingMixin):
                     # place new order only if new price is supplied
                     self.execute_entry(
                         pair=trade.pair,
-                        stake_amount=(order_obj.remaining * order_obj.price),
+                        stake_amount=(order_obj.remaining * order_obj.price / trade.leverage),
                         price=adjusted_entry_price,
                         trade=trade,
                         is_short=trade.is_short,
diff --git a/freqtrade/optimize/backtesting.py b/freqtrade/optimize/backtesting.py
index e942bdfeb..cb57614ed 100644
--- a/freqtrade/optimize/backtesting.py
+++ b/freqtrade/optimize/backtesting.py
@@ -1045,7 +1045,7 @@ class Backtesting:
             if requested_rate:
                 self._enter_trade(pair=trade.pair, row=row, trade=trade,
                                   requested_rate=requested_rate,
-                                  requested_stake=(order.remaining * order.price),
+                                  requested_stake=(order.remaining * order.price / trade.leverage),
                                   direction='short' if trade.is_short else 'long')
                 self.replaced_entry_orders += 1
             else:
  ```

**Comment by xmatthias** [comment]
you should consider converting this to a pull request.

I understand this can be challenging if you never did, but it's not that difficult, and pretty well documented in various parts, for example:
[create a pull request](https://opensource.com/article/19/7/create-pull-request-github)

---

Alternatively (should also be in the PR description) - please provide a proper issue (which includes logs - and shows the problem).
I'll not take diffs from issues and apply them without even fully understanding the problem.

**Comment by mciepluc** [comment]
Sure @xmatthias, no problem. Just wanted to report the issue as maybe the designer knows more places where something may be wrong.

**Comment by xmatthias** [comment]
well you fixed it  ( :100: )- so i think you should get attribution for that (which wouldn't happen if i take your diff and do the commit myself).
