### ISSUE TITLE
No more than 3 trading in each pair per 24 hours

### ISSUE THREAD

**Issue by JeromeWilson6** [freqtrade/freqtrade#7536]
hello,I need help, I want to prevent the bot from trading some of the pairs more frequently. No more than 2 trading in each pair per 24 hours.Is there any code example for reference,thank you very much.

**Comment by stash86** [comment]
Use custom dict, like how I'm using custom_info here https://github.com/stash86/MultiMA_TSL/blob/main/user_data/strategies/MultiMA_TSL.py

**Comment by xmatthias** [comment]
There's multiple ways to go with this - the most simple is probably to "abuse" the [low profit pairs protection](https://www.freqtrade.io/en/stable/plugins/#low-profit-pairs) with a very high profit level so all trades hit - locking pairs for 24h once they had 2 trades.

Alternatively, you could build something via [trade confirmation callback](https://www.freqtrade.io/en/stable/strategy-callbacks/#trade-entry-buy-order-confirmation), in combination with selecting [past trades](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-trades).
