### ISSUE TITLE
Override configuration exit price setting for an exit_tag 

### ISSUE THREAD

**Issue by pizzidellamaremma** [freqtrade/freqtrade#7539]
I was wondering if it's possible to change the exit price for a single tag (e.g. from limit to market) inside the strategy.
Probably with `custom_exit_price` but I don't know how to refer to the actual market price.
Haven't found anything like this inside the docs.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

`custom_exit_price` is definitely the way to go.
If you carefully look at the [corresponding documentation](https://www.freqtrade.io/en/latest/strategy-callbacks/#custom-order-price-rules) - you'll notice that it has a parameter `proposed_rate` - which will contain the current rate (that's the rate it would sell if you don't change anything).

This rate is calculated based on your exit_pricing strategy - and will by default be the first spot in the orderbook, either on the same, or other side (depending on the configuration).

If you need more information - you can also use the [orderbook](https://www.freqtrade.io/en/latest/strategy-customization/#orderbookpair-maximum) directly - HOWEVER - it'll make an active network call to the exchange - will therefore be a slow call to make.

**Comment by pizzidellamaremma** [comment]
I'm sorry, I'll never delete the template again. 

I know that method should be the way to go, I was asking where to find limit and market price to use it in the `custom_exit_price`. The `proposed_rate` returns the price by configuration file, in my case the limit price.

Not well informed about the order book. I need to study it before use it.

**Comment by xmatthias** [comment]
for market orders (or rather, marketable limit orders), the price _detail_ is irrelevant.

you can probably use `proposed_rate * 0.99` - which would mean you'll accept a price 1% below the proposed price (or something higher to get more certainty about fills).

Obviously the lower you go, the lower the chances of the order to not fill (it'll not fill at that price - but at the best orderbook price at that point in time).
If you trade with sufficient volume (or on low volume markets) - this will obviously result in slippage (your order pushes the market price) - but that's the case with all market orders - so your price really defines "how far am i willing to push the market should it come to that".
