### ISSUE TITLE
Multiplying Stake Amount 2x When Stoploss Triggered

### ISSUE THREAD

**Issue by bleriot14** [freqtrade/freqtrade#7540]
## Describe your environment

Operating system: Windows 10
Python Version: Python 3.10.4
CCXT version: ------
Freqtrade Version: 2022.9.1

## Your question

I wounder İf it is possible to multiplying next order's stake amount 2x when stoploss triggered.

**Comment by xmatthias** [comment]
you can use the [stake-size callback](https://www.freqtrade.io/en/stable/strategy-callbacks/#stake-size-management) to size your trades.

one warning though - while such approaches are often used in literature, they assume near unlimited capital.
If you assume limited amount of capital, you will run out of cash with this pretty soon, as "double amount" can equal  "all in" after a losing streak.

**Comment by bleriot14** [comment]
Yes you are right ! But if you risk just 1 dolar with 75x leverage at the beginning and set stoploss 0.45 dollar and stop limit 0.30 dolar, you should be very unlucky lose 9 or 10 times in a strike isnt it ? Evet if choose long or short randomly. I am doing it manually and works great.

**Comment by xmatthias** [comment]
i don't think your calculation will work - not with this type of leverage.

At 75x leverage, you'll have an effective stoplosss of  0.7% to risk 55c (of your own capital) per trade (That's a 55% stoploss at 1x).

so a move of 0.7% against your direction (freqtrade calculations includes fees - so you start with -0.3% or so by default) will trigger the stoploss - which you will hit far more often than you'd like.

That's however something that's up to you to determine / experiment with - all i can do is warn against high leverage - as you will have to be VERY correct (without margin for short swings against you) for that to work out properly.
