### ISSUE TITLE
trailing stop unexpected behavior Realtime vs Backtesting 

### ISSUE THREAD

**Issue by farmage** [freqtrade/freqtrade#7546]
I found interesting behavior of trailing stop. During backtest using the trailing stop in strategy I got promising results. But in live trading, it works a different way. I understand, in backtesting mode, we have only OHLC data, so the trailing stop function works according to these parameters. During a live session, the price can significantly move between these data, so it triggers a trailing stop accidentally.

Now I see the only solution is to implement the own trailing stop functionality in custom_stop callback.
But it would be great to add a feature like like update_trailing_only_on_new_candle, to simulate backtesting behavior, just to have the same picture in testing results and in live trading

just in case, here is my trailing stop configuration
```
    minimal_roi = {"0": 0.3}
    leverage_value = 2.0
    stoploss = -0.4
 
    trailing_stop = True
    trailing_stop_positive = 0.01
    trailing_stop_positive_offset = 0.05
    trailing_only_offset_is_reached = True
```

**Comment by stash86** [comment]
you can do so by not using current profit supplied by the custom_stoploss function, but calculating your own current_profit based of last candle's close price, which would make your backtest and dry/live results more closer, but still won't be identical, because backtest don't take into account sudden dip, which can happen

**Comment by xmatthias** [comment]
If you carefully read through the [backtesting assumptions](https://www.freqtrade.io/en/latest/backtesting/#assumptions-made-by-backtesting) you'll notice that it does not take just "open" for trailing stop adjustments.

If a trailing stop is too tight - you'll have it trigger at the same candle than it's adjusted (not necessarily a problem).
Now too tight will depend ...

the trailing stop should always be > the expected movement per candle - so a 1% trailing stoploss on 5m candles may still work - while on 4h candles it's probably too tight (the high/low difference will be more than 1%).

**Comment by farmage** [comment]
Thanks for the suggestions, I'll try to make some tests and share the results with the community. Maybe this will help someone else.
