### ISSUE TITLE
Is It Possible to Set Roi and Stoploss Smaller Than %1

### ISSUE THREAD

**Issue by bleriot14** [freqtrade/freqtrade#7547]
## Describe your environment
Operating system: Windows 10
Python Version: Python 3.10.4
CCXT version: ------
Freqtrade Version: 2022.9.1

## Your question

Hi again, I read all documantations (custom_exit and custum_stoploss). Due to minimum row and stoploss is 0.01(%1), I couldnt figure out how I can set roi and stoploss smaller than %1. 

Can I set stoploss and roi using price value by means of custom_exit and custom_stoploss ?

**Comment by xmatthias** [comment]
you can set values lower than that (for example 0.001 for 0.1%).
freqtrade won't enforce limits in this area - but the way prices in crypto markets work - they'll not work in reality - as the price will usually move faster than this in splitseconds ...

Also using a stoploss < 1% (which is already pretty tight) is not recommended - keep in mind that you start with a "fee penalty" of 2x the entry fee (we assume identical entry and exit fees) - so you usually start a position at -0.2% - without the price having moved yet.

**Comment by bleriot14** [comment]
I dont encounter that much fees in binance futures. I need minimum_roi=0.006, stoploss=0.004 which you said possible to set.

When I use 1 dollar with 75X in binance future, I give nearly 0.06+0.06=0.12 dolar at the end. 

My strategy is aiming 0.45 dolar, with setting stoploss at 0.30 dolar. My gain/risk ratio is 0.45/0.30 + 0.12 = 1 nearly.  If I hit stoploss, I use 2 dolar (2x). When I hit roi, I set stake size 1 dollar again.

**Comment by xmatthias** [comment]
Please double-check your settings - using 0.006 is wrong when using leverage.
This is explained in the [documentation section about stoploss and leverage](https://www.freqtrade.io/en/latest/stoploss/#stoploss-and-leverage).
the same applies to ROI, too.
