### ISSUE TITLE
Can't Enter Position Momentary.

### ISSUE THREAD

**Issue by bleriot14** [freqtrade/freqtrade#7553]
Describe your environment
Operating system: Windows 10
Python Version: Python 3.10.4
CCXT version: ------
Freqtrade Version: 2022.9.1

Your question
Hi again. My problem is, I cant enter position momentary(just tried dry-run). I mean, When I use 5m candle, bot enters new trade when time is 12:30, 35, 40 ... 

I wounder if it is possible to make bot enter a position when conditions satisfy the entry rules regardless 5m period.

**Comment by xmatthias** [comment]
If you're using 5m candles, then the condition will usually only change when a new candle arrives (at the candle time). This is the time when the signal changes.

Freqtrade does not enforce this - it's your strategy that does this implicitly by calculating indicators on 5m candles - and basing the signals off of this.

While you can have signals that "flicker" throughout a candle - these are usually not backtestable (use live data) - and are near impossible to actually analyze - as you'll not reliably see the "flickered" signal when looking at a historic chart (you look at 5m candles, but the signal was active from :31-:33 - so it's gone by the time the next candle arrives).
