### ISSUE TITLE
Analyse backtest results of individual trades

### ISSUE THREAD

**Issue by infiniteneurotech** [freqtrade/freqtrade#7556]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.10.7 (`python -V`)
  * CCXT version: 1.93.98 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.8 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi all, I'm wondering if it's possible to analyse the results of individual backtest trades? I've found the backtesting-analysis options, but they appear to only provide summaries from what I can tell. I'd like to be able to look at each backtest trade for each pair individually and see if it's a profit or loss. I have a very simple strategy that only uses one entry condition and one exit condition. Ideally I'd love to be able to use the indicator value function for individual trades too to be able to see which indicators gave which signals and which signals lead to profit or loss. Is there a way to do this?

Thanks!

**Comment by xmatthias** [comment]
You can use [`freqtrade webserver`](https://www.freqtrade.io/en/stable/utils/#webserver-mode) to start freqtrade, which will allow you an interactive environment to
* start backtests
*  load historic backtests
* analyze backtests on a trade by trade basis

You can obviously customize the plots in freqUI - showing you the indicators on the chart you're most interested in.
