### ISSUE TITLE
Configuration if fetchTickers() is not implemented for some exchanges (Ex : NDAX)

### ISSUE THREAD

**Issue by abinavrameshs** [freqtrade/freqtrade#7559]
## Describe your environment

  * Operating system: Linux
  * Python Version: Python 3.10.7 (`python -V`)
  * CCXT version: 1.93.98(`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2022.9.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I am using the exchange NDAX for setting up automatic trading using freqtrade.
ndax is one of the exchanges that is supported by ccxt, however the function `fetchTickers()` is not implemented in ccxt for ndax exchange. Because of this, I am unable to use NDAX to trade.
Can I please know what could be the workaround that I must perform to make `fetchTickers()` work with ndax?

**Comment by xmatthias** [comment]
Freqtrade doesn't depend on fetchTickers directly  (purely for trading) - but uses it for additional modules (where it becomes non-optional), and will stop if the endpoint is used while it's not implemented.

If the exchange doesn't provide a "one call -> get prices for all pairs" endpoint, you'll find it difficult to emulate this efficiently- as the expectation for this data is a response that contains all pairs that could potentially be traded (or which are owned).
Your best bet is to research the API endpoints the exchange offers to see if a suitable endpoint can be implemented by ccxt (and then open or update the corresponding issue in ccxt).


we might be able to improve behavior slightly (don't fail but return empty response) - but i'm not sure it's worth the effort, as (especially the /balance problem) is quite limiting.

---

Without this endpoint - you should be able to use freqtrade just fine if you avoid all pairlists that set "needstickers" to true (from memory, at least StaticPairlist, and VolumePairlist in it's [advanced mode](https://www.freqtrade.io/en/latest/plugins/#volumepairlist-advanced-mode) should work.

you can't use freqUI, as that will be using the balance endpoint, which relies on (quickly) getting rate data for all pairs.

telegram should work fine (so you can control the bot) - with the exception of the `/balance` endpoint (same problem than with the api).

---
That said - nothing guarantees that the exchange itself will work aside from this. 
While ccxt support is a requirement - it's no guarantee an exchange will work (exchanges often have subtle differences in behavior).

you're almost certainly the first to try this exchange with freqtrade - so be prepared for eventual problems.
While we can support you with eventual problems - it'll still require at least some knowledge in reading python exceptions - and in reading python code.

Before having freqtrade trade unsupervised (without looking at the logs after every trade action) - best go through the [adding a new exchange](https://www.freqtrade.io/en/stable/developer/#implement-a-new-exchange-wip) guide.

**Comment by xmatthias** [comment]
After having quickly looked at the exchange volume (no trades for minutes at their "highest volume" pair BTC/CAD), 
and in combination with the response to your ccxt ticket (https://github.com/ccxt/ccxt/issues/15231), we'll not be spending our time supporting this exchange.

You're obviously free to investigate yourself and make PR's trying to add support (which we'll surely have a look at) - but their volume does not justify spending our time on this point.

You'd see that you'll also have severe problems having your orders filled in any reasonable time.
