### ISSUE TITLE
Allow freqai to pull prediction_models from user_data

### ISSUE THREAD

**Issue by Silur** [freqtrade/freqtrade#7570]
Currently, only classes present in `freqai/prediction_models` are available for backtesting/trading.
Allowing the user to define a custom model to be used with `--freqaimodel` would allow more flexibility.

**Comment by xmatthias** [comment]
that's not really true.

Models placed in `user_data/freqaimodels` will be loading just fine.
It's however missing from the docs ...

**Comment by Silur** [comment]
did not notice this feature, then my relevant PR - https://github.com/freqtrade/freqtrade/pull/7569 may also be obsolete

**Comment by xmatthias** [comment]
i see that as a different topic, really (which should be looked at from a different perspective) - if you aim to have others benefit from your implementation / the use of xgb random forests - i do think that does provide value.

**Comment by robcaulk** [comment]
> Currently, only classes present in `freqai/prediction_models` are available for backtesting/trading.
> Allowing the user to define a custom model to be used with `--freqaimodel` would allow more flexibility.

@xmatthias already pointed out the custom folder to use.

But I’d like to say that FreqAI is designed explicitly to let users create custom `—freqaimodels`. This is central to the design - and has been since conception.
