### ISSUE TITLE
Hyperopt fails with "Could not pickle the task to send it to the workers" on 2022.9/2022.9+

### ISSUE THREAD

**Issue by Bloodhunter4rc** [freqtrade/freqtrade#7575]
## Describe your environment
  * Operating system: Debian WSL docker 2022.9
  * Freqtrade Version: freqtrade 2022.9
  
## Describe the problem:

Running Hyperopt (not for freqai) fails when using 2022.9/2022.9+ version
Running the same Hyperopt on 2022.8 version works.

### Steps to reproduce:

  1. Run a hyperopt on freqtrade v2022.9

### Observed Results:

  * What happened?
  * After starting hyperopt fails to pickle the task, cant pickle the task -> traceback
  *docker-compose run --rm freqtrade hyperopt --hyperopt-loss SharpeHyperOptLossDaily --spaces buy --strategy Test --config user_data/backtestconfig.json -e 100 --disable-param-export --timerange 20220101- -j 16

  * What did you expect to happen?
  * 
### Relevant code exceptions or logs

```
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/loky/backend/queues.py", line 125, in _feed
    obj_ = dumps(obj, reducers=reducers)
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/loky/backend/reduction.py", line 211, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/loky/backend/reduction.py", line 204, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 15, in __reduce__
    _pickled_object = dumps(self._obj)
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_thread._local' object
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 39, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 608, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 418, in run_optimizer_parallel
    return parallel(delayed(
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
_pickle.PicklingError: Could not pickle the task to send it to the workers.
ERROR: 1

 ```
  
```
2022-10-11 15:26:03,640 - freqtrade.optimize.hyperopt - INFO - Hyperopting with data from 2022-01-01 00:00:00 up to 2022-10-11 02:40:00 (283 days)..
2022-10-11 15:26:04,422 - freqtrade.optimize.hyperopt - INFO - Found 32 CPU cores. Let's make them scream!
2022-10-11 15:26:04,422 - freqtrade.optimize.hyperopt - INFO - Number of parallel jobs set as: 16
2022-10-11 15:26:04,422 - freqtrade.optimize.hyperopt - INFO - Using estimator ET.
2022-10-11 15:26:04,444 - freqtrade.optimize.hyperopt - INFO - Effective number of parallel workers used: 16
  ```

Could be related to changes in https://github.com/freqtrade/freqtrade/pull/7363 which made it work with freqai.

**Comment by xmatthias** [comment]
i can't really recreate / reproduce this behavior with the strategies i tried so far.

please provide a (minimal) strategy that's causing this behavior so we can investigate further.

i can exclude that it's been caused by #7363 - as none of the (relevant) lines that touched will affect a non-freqAI strategy.

**Comment by Bloodhunter4rc** [comment]
Seems to be related to my usage of Categorical Parameters, heres a minimal strategy which causes this on 2022.09+ 

```
from freqtrade.strategy.interface import IStrategy
from typing import Dict, List
from functools import reduce
from pandas import DataFrame

import talib.abstract as ta
import numpy as np
import freqtrade.vendor.qtpylib.indicators as qtpylib
import datetime
from technical.util import resample_to_interval, resampled_merge
from datetime import datetime, timedelta
from freqtrade.persistence import Trade
from freqtrade.strategy import stoploss_from_open, merge_informative_pair, DecimalParameter, IntParameter, CategoricalParameter, informative

class Test(IStrategy):

    # Optimal timeframe for the strategy
    timeframe = '5m'

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = True
    startup_candle_count = 30
    can_short = True

    # Disabled
    stoploss = -0.1

    # ROI table:  # value loaded from strategy
    minimal_roi = {
        "0": 0.99
    }

    base_cdl_buy = IntParameter(2, 90, default=60, space='buy', optimize=True)
    base_cdl_sell = IntParameter(2, 90, default=52, space='buy' , optimize=True)
    low_offset = DecimalParameter(0.5, 0.99, default=0.94, space='buy' , optimize=True)
    high_offset = DecimalParameter(0.5, 1.1, default=0.836, space='buy' , optimize=True)
    buy_trigger = CategoricalParameter([ta.SMA,ta.EMA,ta.DEMA], default=ta.SMA, space='buy' , optimize=False)
    sell_trigger = CategoricalParameter([ta.SMA,ta.EMA,ta.DEMA], default=ta.EMA , space='sell' , optimize=False)

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['ma_offset_buy'] = self.buy_trigger.value(dataframe, int(self.base_cdl_buy.value)) * self.low_offset.value
        dataframe['ma_offset_sell'] = self.sell_trigger.value(dataframe, int(self.base_cdl_sell.value)) * self.high_offset.value

        dataframe.loc[
            (
                (dataframe['close'] > dataframe['ma_offset_buy']) &
                (dataframe['rsi'] < 30) &
                (dataframe['volume'] > 0)
            ),
            'enter_long'] = 1

        dataframe.loc[
            (
                (dataframe['close'] > dataframe['ma_offset_sell']) &
		(dataframe['rsi'] > 60) &
                (dataframe['volume'] > 0)
            ),
            'enter_short'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['rsi'] > 70) &
                (dataframe['volume'] > 0)
            ),
            'exit_long'] = 1

        dataframe.loc[
            (
                (dataframe['rsi'] < 30) &
                (dataframe['volume'] > 0)
            ),
            'exit_short'] = 1

        return dataframe
```

**Comment by Bloodhunter4rc** [comment]
`
from freqtrade.strategy.interface import IStrategy
from typing import Dict, List
from functools import reduce
from pandas import DataFrame

import talib.abstract as ta
import numpy as np
import freqtrade.vendor.qtpylib.indicators as qtpylib
import datetime
from technical.util import resample_to_interval, resampled_merge
from datetime import datetime, timedelta
from freqtrade.persistence import Trade
from freqtrade.strategy import stoploss_from_open, merge_informative_pair, DecimalParameter, IntParameter, CategoricalParameter, informative

class Test(IStrategy):

    # Optimal timeframe for the strategy
    timeframe = '5m'

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = True
    startup_candle_count = 30
    can_short = True

    # Disabled
    stoploss = -0.1

    # ROI table:  # value loaded from strategy
    minimal_roi = {
        "0": 0.99
    }

    base_cdl_buy = IntParameter(2, 90, default=60, space='buy', optimize=True)
    base_cdl_sell = IntParameter(2, 90, default=52, space='buy' , optimize=True)
    low_offset = DecimalParameter(0.5, 0.99, default=0.94, space='buy' , optimize=True)
    high_offset = DecimalParameter(0.5, 1.1, default=0.836, space='buy' , optimize=True)
    buy_trigger = CategoricalParameter([ta.SMA,ta.EMA,ta.DEMA], default=ta.SMA, space='buy' , optimize=False)
    sell_trigger = CategoricalParameter([ta.SMA,ta.EMA,ta.DEMA], default=ta.EMA , space='sell' , optimize=False)

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['ma_offset_buy'] = self.buy_trigger.value(dataframe, int(self.base_cdl_buy.value)) * self.low_offset.value
        dataframe['ma_offset_sell'] = self.sell_trigger.value(dataframe, int(self.base_cdl_sell.value)) * self.high_offset.value

        dataframe.loc[
            (
                (dataframe['close'] > dataframe['ma_offset_buy']) &
                (dataframe['rsi'] < 30) &
                (dataframe['volume'] > 0)
            ),
            'enter_long'] = 1

        dataframe.loc[
            (
                (dataframe['close'] > dataframe['ma_offset_sell']) &
		(dataframe['rsi'] > 60) &
                (dataframe['volume'] > 0)
            ),
            'enter_short'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['rsi'] > 70) &
                (dataframe['volume'] > 0)
            ),
            'exit_long'] = 1

        dataframe.loc[
            (
                (dataframe['rsi'] < 30) &
                (dataframe['volume'] > 0)
            ),
            'exit_short'] = 1

        return dataframe
`

**Comment by xmatthias** [comment]
It's most likely caused by the ta-lib update - which made ta-lib threadsafe (prior to that, values could leak between threads ...).
While that's not a problem that's affecting hyperopt itself - it's still a problem.

I've not been aware that skopt even supports function objects as part of a space - but that's pure luck that it worked - as it's not something that is documented as supported in their documentation, so skopt updates could break that just as easily.

While it worked before - it's never been a documented method - and therefore we cannot guarantee working now or in the future (it's not a supported pattern, not in the past, and not now).


you can however easily work around this by using the following pattern:

```
    buy_trigger = CategoricalParameter(
        ['SMA', 'EMA', 'DEMA'], default='SMA', space='buy', optimize=False)
    ...
    if self.buy_trigger.value == 'EMA':
        ema = ta.EMA
    elif ...
    ...
    dataframe['ma_offset_buy'] = ema(
            dataframe, int(self.base_cdl_buy.value)) * self.low_offset.value
            
    # or even using getattr if you must combine it in one line.
    dataframe['ma_offset_buy'] = getattr(ta, self.buy_trigger.value)(
            dataframe, int(self.base_cdl_buy.value)) * self.low_offset.value
```

**Comment by Bloodhunter4rc** [comment]
yes i can work around it like that, thought it may be some bigger problem, but in the end just my unconventional usage :) thanks for the help!
