### ISSUE TITLE
How start more then one strategies?

### ISSUE THREAD

**Issue by favoritesG** [freqtrade/freqtrade#7591]
Hi
I am not very good with code so sorry if I ask a stupid question :)

I managed to install freqtrade in linux cloud server Vulter.

Operating system: Ubuntu 20.04.5LTS
connected with Binance
connected with Telegram

I have hyperoptimized strategy for 3 different pars. I know how to start bot for one pair but I dont know how to start all 3. All strategies have different config.json but same telegram. Is this even possible?

Now I start bot with this: freqtrade trade --config config.json --strategy MACDStrategyBNB

How could I start all 3? Do I need different telegram channels? Do i need to start each bot separately? Do I need to include all strategies in docker-compose.yml file and start this file?

Stategys:
(Same but with different hyperoptimization)
MACDStrategyBNB
MACDStrategyADA
MACDStrategyETH

(Same but with different pair_whitelist)
configBNB
configADA
configETH

Thanks :)

**Comment by stash86** [comment]
Assuming you are using non-docker way, use screen or tmux to create multiple sessions for each of the bots. Each bots have to have separate telegram bots, separate databases and logs

**Comment by favoritesG** [comment]
Thanks
so I run it separete like this:

freqtrade trade --config configBNB.json --strategy MACDStrategyBNB
freqtrade trade --config configADA.json --strategy MACDStrategyADA
Freqtrade trade --config configETH.json --strategy MACDStrategyETH

I need to create two more telegram bots.

**Comment by xmatthias** [comment]
Yes correct.
We also have this covered in [this segment of the documentation](https://www.freqtrade.io/en/latest/advanced-setup/#running-multiple-instances-of-freqtrade).
