### ISSUE TITLE
Backtest incorrectly processes timed out orders

### ISSUE THREAD

**Issue by iprogger** [freqtrade/freqtrade#7592]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.10.8 
  * CCXT version: 1.93.98
  * Freqtrade Version: 2022.9.1

## Describe the problem:

I wrote a simple strategy that places limit orders every candle. Price calculations are based on previous candles (such indicators as ATR, Supertrend, nPOC, etc.) So the basic idea is to place a long order below the current price and wait for it to be filled. If it doesn't fill during the current candle then cancel it. On new candle make recalculations and place a new order. Strategy uses 1 pair and opens max 1 trade.
During backtesting I noticed that orders were placed every two candles, so some orders were skipped. This issue doesn't depend on the timeframe.

### Steps to reproduce:

test_strategy.py:
```
import logging
from datetime import datetime
from functools import reduce
from typing import Optional

from pandas import DataFrame

from freqtrade.strategy import (IStrategy)

logger = logging.getLogger(__name__)


class TestStrategy(IStrategy):

    startup_candle_count = 10
    stoploss = -0.03
    minimal_roi = {"0": 100}
    can_short: bool = False

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        long_conditions = [dataframe['volume'] > 0]
        if long_conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, long_conditions),
                'enter_long'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        return dataframe

    def custom_entry_price(self, pair: str, current_time: datetime, proposed_rate: float,
                           entry_tag: Optional[str], side: str, **kwargs) -> float:
        message = f'>>> ENTRY >>> time: {current_time}'
        logger.info(message)
        return 1000.0
```

test-config.json:
```
{
  "dry_run": true,
  "initial_state": "running",
  "trading_mode": "futures",
  "margin_mode": "isolated",
  "futures_funding_rate": 0.0,
  "process_only_new_candles": true,
  "max_open_trades": 1,
  "stake_currency": "USDT",
  "stake_amount": "unlimited",
  "tradable_balance_ratio": 0.99,
  "fiat_display_currency": "USD",
  "stoploss": -0.03,
  "timeframe": "1m",
  "order_types": {
    "entry": "limit",
    "exit": "limit",
    "stoploss": "market",
    "stoploss_on_exchange": false
  },
  "ignore_buying_expired_candle_after": 10,
  "unfilledtimeout": {
    "entry": 50,
    "exit": 50,
    "unit": "seconds"
  },
  "exchange": {
    "name": "okx",
    "pair_whitelist": [
      "BTC/USDT:USDT"
    ]
  },
  "entry_pricing": {
    "use_order_book": true,
    "order_book_top": 1,
    "price_side": "other",
    "price_last_balance": 0.0,
    "check_depth_of_market": {
      "enabled": false,
      "bids_to_ask_delta": 1
    }
  },
  "exit_pricing": {
    "use_order_book": true,
    "order_book_top": 1,
    "price_side": "other"
  },
  "pairlists": [
    {
      "method": "StaticPairList"
    }
  ]
}
```

backtest command:
`freqtrade backtesting -c ./user_data/test-config.json --strategy TestStrategy -p BTC/USDT:USDT --timeframe 1m --timerange=20221013-`
  
### Observed Results:

  * What happened?
 Strategy uses 1m timeframe. Look at the orders time, they were placed every 2 minutes instead of 1.
```
test_strategy - INFO - >>> ENTRY >>> time: 2022-10-13 07:09:00+00:00
test_strategy - INFO - >>> ENTRY >>> time: 2022-10-13 07:11:00+00:00
test_strategy - INFO - >>> ENTRY >>> time: 2022-10-13 07:13:00+00:00
```

  * What did you expect to happen?
```
test_strategy - INFO - >>> ENTRY >>> time: 2022-10-13 07:09:00+00:00
test_strategy - INFO - >>> ENTRY >>> time: 2022-10-13 07:10:00+00:00
test_strategy - INFO - >>> ENTRY >>> time: 2022-10-13 07:11:00+00:00
test_strategy - INFO - >>> ENTRY >>> time: 2022-10-13 07:12:00+00:00
test_strategy - INFO - >>> ENTRY >>> time: 2022-10-13 07:13:00+00:00
```

### Results
In trade mode everything works fine, so I started to debug backtesting and found the reason of such behavior. When the backtest cancels the order, it [only decrement the open_trade_count](https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/optimize/backtesting.py#L1126), but later uses [open_trade_count_start to check for available trading slots](https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/optimize/backtesting.py#L1138). As a result, it always gets one slot less than actually available (zero in my case). 
I just added `open_trade_count_start -= 1` to the _Close trade_ block (after line 1126) and now it works as expected. All tests passed successfully and I wrote another test for the described case.

Please check everything I wrote in this bug report. And if this is really a bug, then I have a ready-to-commit code with a fix and a test:)

**Comment by xmatthias** [comment]
without looking at it in full details (just glance over the code so far). 
i'd say please submit the PR so we can look at the code, and play with it / compare results without re-implementing the same logic you already have.

`open_trade_count_start` is a workaround from a time we didn't have order cancellation in backtesting (we actually didn't have orders in backtesting, just trades) - so it's very likely that this was overlooked.

**Comment by iprogger** [comment]
done
