### ISSUE TITLE
The cpu usage of the hyperopt

### ISSUE THREAD

**Issue by glowwormX** [freqtrade/freqtrade#7594]
## Describe your environment

  * Operating system: macos12.3
  * Python Version: 3.10.6
  * CCXT version: 1.92.52
  * Freqtrade Version: 2022.8
  
## Your question

My computer has 8cpu. When I was doing hyperopt, I observed the cpu situation on docker desktop. 
The cpu usage reaches 800% only for about 1 second and remains 100% for the remaining 20 seconds. 
It's been in that cycle ever since.
How to explain this phenomenon?
Can I make better use of cpu?

My strategy has about 10 buy optimization parameters
My command to run hyperopt is:

`docker-compose run --rm freqtrade hyperopt -j 8 --config user_data/config-test.json --timeframe=15m --hyperopt-loss SharpeHyperOptLossDaily -p BTC/USDT --strategy Long5Strategy --timerange 20220701-20220801 --spaces buy roi stoploss -e 500`

**Comment by xmatthias** [comment]
while hyperopt runs 8 backtests in parallel, the determination of the next points to try is not.

That's a limitation of scikit-optimize (or rather, the underlying Bayesian search algorithm, which is not parallelizable (or at least not parallelized in scikit-learn).

there's a similar question in the scikit-optimize repository (https://github.com/scikit-optimize/scikit-optimize/issues/768) - which attempts to somewhat explains the different steps.

**Comment by glowwormX** [comment]
Thank you for your answer, I have another question.
Can dataframe from different time periods be analyzed in the same strategy?
For example, I want to use 4h to determine the trend and 15m to determine whether to enter.

**Comment by xmatthias** [comment]
You can use [informative pairs](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs) for this.

There's also a bigger sample on the same page a bit further down than the link above.
