### ISSUE TITLE
Cancelled order messages repeated hundreds of times

### ISSUE THREAD

**Issue by Junumboxo** [freqtrade/freqtrade#7608]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.10.6 (`python -V`)
  * CCXT version: 1.93.98 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade docker-873eb5f2 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I am running the bot live on Binance. For some reason, only when the trade is exited because it **was cancelled on an exchange**, I receive tens of messages, some duplicates, and some with slightly **different** profit/loss. Find more details in the attachments
![Screenshot from 2022-10-18 20-26-48](https://user-images.githubusercontent.com/44647094/196517806-45728fe5-dfb9-4835-be12-df5bed85d7b0.png)
![Screenshot from 2022-10-18 20-03-54](https://user-images.githubusercontent.com/44647094/196517800-f2039f13-54c5-4cd5-a2a0-e59ea65df3d2.png)
Here is a snippet of the log file too 
[logs.txt](https://github.com/freqtrade/freqtrade/files/9814155/logs.txt)

config.json
```
{
    "max_open_trades": 10,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.5,
    "fiat_display_currency": "USD",
    "dry_run": false,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "**",
        "secret": "**",
        "ccxt_config": {},
              "ccxt_async_config": {},
        "pair_whitelist": [
                ".*/USDT"
        ],
        "pair_blacklist": [
        "LUNA/.*",
        "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList", 
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "**",
        "chat_id": "**"
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "**",
        "CORS_origins": [],
        "username": "**",
        "password": "**"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```

Pairs for which this behavior was observed: FTT/USDT, TRX/USDT, ETH/USDT, HBAR/USDT

**Comment by xmatthias** [comment]
You will want to run the bot with `exchange.log_responses` set to True, we should be able to investigate this problem with the logs that generates.

with the provided log - all i can say is that the messages you get are aligned to the logs - which simply says
* placed an exit order (successfully)
* exit order has a "canceled" state on the exchange

Profits will differ as price moves on the exchange.

the only 2 cases i've seen this so far is if you either cancel the order on exchange manually - or if you use a non-default time-in-force setting (which would have the exchange auto-cancel the orders if the condition is not met).

**Comment by Junumboxo** [comment]
@xmatthias thank you for your reply, I updated the config file and reloaded it, I will let you know when I have any updates. And yes indeed there is non-default time-in-force setting (probably I copied the wrong config file, as I have several bots running), so the actual config file is different from what I attached with only this
```
"order_time_in_force": {
    "entry": "gtc",
    "exit": "fok"
},
```

**Comment by xmatthias** [comment]
a time in force of `fok` means ["full or kill"](https://academy.binance.com/en/glossary/fill-or-kill-order) - so basically - if the exchange is not able to fill your order immediately - it'll cancel your order.
With the pricing you use for the exit side (same side) - it's unlikely that you'll get many fills this way.
it should really only be used with "other" pricing if you ask me - but obviously if this is what you expect - then this time in force is the right one for you.

so with this time in force - this behavior is expected.

**Comment by Junumboxo** [comment]
I actually put this to avoid the problem of partial orders not being able to be fulfilled because of insufficient balance, there was one issue like that. But now that I am not trading BNB, if this is not the behavior I want, I should just remove it?

**Comment by xmatthias** [comment]
i think this type CAN work fine if you use "other" side pricing (which however makes you cross the spread).

You can also set it to "gtc" - which leaves the order there until the bot cancels it (after 10 minutes, based on your settings).
you should however aim to understand the implications of the settings you're using to avoid problems - there is no "this is right / this is wrong" setting, really - but a "with this, we can expect the following behavior ... "
