### ISSUE TITLE
Error by hyperopt

### ISSUE THREAD

**Issue by zoknoteplus** [freqtrade/freqtrade#7609]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by zoknoteplus** [comment]
```
2022-10-19 11:23:26,125 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 39, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 605, in start
    asked, is_random = self.get_asked_points(n_points=current_jobs)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 478, in get_asked_points
    asked = unique_list(self.opt.ask(n_points=n_points * 5))
  File "/home/ftuser/.local/lib/python3.10/site-packages/skopt/optimizer/optimizer.py", line 395, in ask
    x = opt.ask()
  File "/home/ftuser/.local/lib/python3.10/site-packages/skopt/optimizer/optimizer.py", line 367, in ask
    return self._ask()
  File "/home/ftuser/.local/lib/python3.10/site-packages/skopt/optimizer/optimizer.py", line 434, in _ask
    return self.space.rvs(random_state=self.rng)[0]
  File "/home/ftuser/.local/lib/python3.10/site-packages/skopt/space/space.py", line 900, in rvs
    columns.append(dim.rvs(n_samples=n_samples, random_state=rng))
  File "/home/ftuser/.local/lib/python3.10/site-packages/skopt/space/space.py", line 157, in rvs
    samples = self._rvs.rvs(size=n_samples, random_state=rng)
  File "/home/ftuser/.local/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py", line 467, in rvs
    return self.dist.rvs(*self.args, **kwds)
  File "/home/ftuser/.local/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py", line 3335, in rvs
    return super().rvs(*args, **kwargs)
  File "/home/ftuser/.local/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py", line 1066, in rvs
    raise ValueError(message)
ValueError: Domain error in arguments. The `scale` parameter must be positive for all distributions, and many distributions have restrictions on shape parameters. Please see the `scipy.stats.randint` documentation for details.
```

**Comment by zoknoteplus** [comment]
I have Linux with latest freqtrade developer

**Comment by zoknoteplus** [comment]
How can i solve this. It is only when i enable spaces buy!

**Comment by xmatthias** [comment]
please use the edit function if you have something to add to a prior message.

"latest freqtrade develop" is also not a valid version - as what's "latest" for you will change potentially multiple times per day.

---

At first glance, it looks like some issue with the space you're feeding hyperopt with (if you say it's with the buy space, problably with that space).

Without seeing which parameters are part of the buy space, it's however impossible to assist you further.

**Comment by zoknoteplus** [comment]
I have only this:

        dataframe.loc[
            (
                # Signal: RSI crosses above 70
                (((dataframe['close'] - dataframe['open'] < 0) &
                ((dataframe['high'] - dataframe['open']) > dataframe['height']*2)) |
                ((dataframe['close'] - dataframe['open'] > 0) &
                ((dataframe['high'] - dataframe['close']) > dataframe['height']*2))) &
                (dataframe['close_1h'] > dataframe['sma20_1h']) &
                (dataframe['ema800'] < dataframe['ema800'].shift(1)) &
                (qtpylib.crossed_above(dataframe['rsi'], self.short_rsi.value)) &
                (dataframe['tema'] > dataframe['bb_middleband']) &  # Guard: tema above BB middle
                (dataframe['tema'] < dataframe['tema'].shift(1)) &  # Guard: tema is falling
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            ['enter_short', 'enter_tag']] = (1, 'Short_RSI_70')

        return dataframe

with 
    short_rsi = IntParameter(low=51, high=100, default=70, space='sell', optimize=True, load=True)

**Comment by zoknoteplus** [comment]
My call is:
dcr freqtrade hyperopt --config user_data/f1h_config.json --strategy SampleStrategy --hyperopt-loss SharpeHyperOptLoss --spaces buy --timerange 20220601- -e 100 --enable-protections

**Comment by xmatthias** [comment]
your provided parameter (the one) suggests that you got no buy parameter - which would cause a different error if you're using the buy space.

We'll need the buy space parameter that is used / detected.

**Comment by zoknoteplus** [comment]
sorry
short_rsi = IntParameter(low=1, high=50, default=30, space='buy', optimize=True, load=True)

**Comment by zoknoteplus** [comment]
wrong again
    short_rsi = IntParameter(low=51, high=100, default=70, space='buy', optimize=True, load=True)
    exit_short_rsi = IntParameter(low=1, high=50, default=30, space='sell', optimize=True, load=True)

**Comment by xmatthias** [comment]
are you getting this error right at the start or at a later point?

please provide the full logs up to the exception for further analysis.

**Comment by xmatthias** [comment]
I'll assume this as answered  / fixed.
If it's not, please provide the information requested above.
