### ISSUE TITLE
Performance Warning during hyperopt

### ISSUE THREAD

**Issue by jack97p** [freqtrade/freqtrade#7610]
# 
PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataframe[f"supertrend_2_buy_{multiplier}_{period}"] = self.supertrend(
# 
I dont know what this error means, and how i can resolve it.

**Comment by xmatthias** [comment]
It's a warning from pandas.

Freqtrade will copy the dataframe after the fact - it's just an (anoying!) warning with little impact on actual performance.

we do have some recommendation on how to work around this in [the docs](https://www.freqtrade.io/en/stable/strategy-advanced/#performance-warning) - it will however complicate simple code quite some - so make sure you still understand the outcome.

**Comment by jack97p** [comment]
thank you i will now look the docs. But this message appears me in continuation for ever, is it normal?

**Comment by xmatthias** [comment]
it will be shown once for every new column - after a certain amount of columns have been added.
It may seem to be forever, but it really isn't.

Depending on the mode you're running, it can also show up in the middle of hyperopt - where it's obviously potentially problematic.

**Comment by jack97p** [comment]
So if i've understood, if i leave my hyperopt running it will come to an end whit the results?
ps. im using the FSupertrendStrategy

**Comment by xmatthias** [comment]
as said, it's a warning. 
it will potentially slow down hyperopt though - as it'll force output (terminal sync is pretty slow).

You should also be able to disable the output by putting the following at the top of your strategy - which will filter the warnings (it won't fix the problem though).

```
import warnings
warnings.simplefilter(action='ignore', category=pd.errors.PerformanceWarning)
```

https://github.com/pandas-dev/pandas/issues/42477#issuecomment-1048001693 shows a nice example on the impact.
it's however usually not relevant on actual bot performance outside of hyperopt.
