### ISSUE TITLE
adjust_trade_position misbehavior

### ISSUE THREAD

**Issue by farmage** [freqtrade/freqtrade#7617]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.11 (`python -V`)
  * CCXT version: 1.95 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2022.10.dev (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Describe the problem:

I implemented a strategy with position adjustment, just like in example with little changes. During the dry run test, I noticed misbehavior with position adjustment.
For example:
```
Trade ID: 27 (since 9 hours ago)
Current Pair: RUNE/USDT
Direction: Long
Leverage: 20.0
Amount: 7258.0 (512.6561 USDT)
Enter Tag: long_bn_sup
Number of Entries: 2/2
Open Rate: 1.41266492
Open Date: 2022-10-20 21:01:21
Current Rate: 1.41300000
Current Profit: -1.13%
Stoploss: 1.37100000 (-80.00%)
Stoploss distance: -0.04200000 (-2.97%)
  
Entry #1:
Amount: 1400.0 (1999.20000000 USDT)
Average Price: 1.428
  
Entry #2: at -1.33% avg profit
(0 days an hour and 23 minutes ago)
Amount: 5858.0 (8253.92200000 USDT)
Average Entry Price: 1.409 (-1.33% from 1st entry rate)
```
and the code

```python

    def custom_stake_amount(self, pair: str, current_time: datetime, current_rate: float,
                            proposed_stake: float, min_stake: Optional[float], max_stake: float,
                            leverage: float, entry_tag: Optional[str], side: str,
                            **kwargs) -> float:

        # print(f"{pair}:{proposed_stake}")
        return proposed_stake

    def adjust_trade_position(self, trade: Trade, current_time: datetime,
                              current_rate: float, current_profit: float,
                              min_stake: Optional[float], max_stake: float,
                              current_entry_rate: float, current_exit_rate: float,
                              current_entry_profit: float, current_exit_profit: float,
                              **kwargs) -> Optional[float]:

        if current_profit >= 0.11 and trade.nr_of_successful_exits == 0:
            # Take half of the profit at +5%
            # print(f"{trade.pair}: Take partial profit {trade.stake_amount / 2}")
            return -(trade.stake_amount*2 / 3)

        # if current_profit > 0.08 and trade.nr_of_successful_exits == 1:
        #     # Take half of the profit at +5%
        #     # print(f"{trade.pair}: Take partial profit {trade.stake_amount / 2}")
        #     return -(trade.stake_amount / 3)


        if current_profit > -0.2:
            return None

        # Obtain pair dataframe (just to show how to access it)
        dataframe, _ = self.dp.get_analyzed_dataframe(trade.pair, self.timeframe)
        # Only buy when not actively falling price.
        last_candle = dataframe.iloc[-1].squeeze()
        previous_candle = dataframe.iloc[-2].squeeze()

        if not (last_candle['enter_long']==1 or last_candle['enter_short']==1):
            return None

        filled_entries = trade.select_filled_orders(trade.entry_side)
        count_of_entries = trade.nr_of_successful_entries

        # print(f"{trade.pair}:{'short' if trade.is_short else 'long'} {count_of_entries} {last_candle['enter_long']}/{last_candle['enter_short']}")
        try:
            # This returns first order stake size
            stake_amount = filled_entries[0].cost
            # This then calculates current safety order size
            # stake_amount = stake_amount * (1 + (count_of_entries * 0.25))

            stake_amount = stake_amount / 2
            print(f"{trade.pair}: Current lose:{current_profit} Adjust position to {stake_amount}")

            return stake_amount
        except Exception as exception:
            return None

        return None
```

The stake amount is 100$ the leverage is x20 (just testing)
So, here we see the first entry processed as expected  100$ *x20 ~2000$
But the second entry, according to the code, should be only stake_amount/2 it's 50$ and in the debug print it shows the right value ~50$
In the entry record, we see a much bigger amount (8253.92200000 USDT) even if divided by leverage it will be 412$ stake

Could someone pinpoint what's I'm doing wrong, or it's just a bug in the engine?

Thank you in advance

**Comment by xmatthias** [comment]
considering you're using 2022.10.dev  - we'll need the exact version for this - as things in develop change quickly - so you could have any version between the first and today's version of develop.

Depending on this version - the following behavior will have changed for exits (but was always the case for entries).

> Modifications to leverage are not possible, and the stake-amount is assumed to be before applying leverage.

[source](https://www.freqtrade.io/en/latest/strategy-callbacks/#adjust-trade-position)

**Comment by farmage** [comment]
I had a version from October 20 and updated it to the most recent. I'll test and back to this topic with the results.

**Comment by xmatthias** [comment]
I think the conceptual error you got is when using the order's cost.

`filled_entries[0].cost` will be the cost of the first order ( `amount received * price paid` - which will be ~2k$ in your case).

The adjustment (`stake_amount = stake_amount / 2`)  will then be 1k$ - which will be multiplied by the leverage (20x)

Without logs it's difficult to tell - but most likely, your account / dry-run account doesn't have 20k$ available, therefore the bot adjusts this value to the maximum available amount (~8000$ / 20).

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.
