### ISSUE TITLE
trading position management  on Strategy

### ISSUE THREAD

**Issue by yaotian** [freqtrade/freqtrade#762]
## Step 3: Describe the problem:

Now buy all or sell all. Is there any way to do trading position management?
On buy signal, my strategy need to buy 10%  of stake_amount first, then 30%, 30%,30% later.
On sell signal, sell them all or 50% first, 50% later.
Any way to do this?

**Comment by xmatthias** [comment]
This behavior is currently not supported in freqtrade.

However, there are multiple proposals / ideas in place trying to move more logic into the strategy.
we also have a PR in review to trade "all available" stake - which is similar (but different) than your request.

**Comment by shusso** [comment]
should be possible after #1007

**Comment by yaotian** [comment]
@shusso How? #1007 was merged but how to make the position mangement？
