### ISSUE TITLE
Using PyPy or Python 3.11

### ISSUE THREAD

**Issue by mpmic** [freqtrade/freqtrade#7620]
## Describe the enhancement

Is it a good idea to use pypy or python 3.11 in hopes of speeding Freqtrade up? 

*Explain the enhancement you would like*

Currently, freqtrade uses 99% of my CPU on average, and I was looking into ways that I can improve the performance of the bot without having better hardware. I've read that PyPy is much faster than CPython, is this a viable option? The new version of Python (3.11) also seems to be "between 10-60% faster than Python 3.10".

**Comment by xmatthias** [comment]
Freqtrade is tested against cpython only.
pypy has quite severe constraints for what it can run - but as far as i'm aware, it hasn't been tested.

python 3.11 is not out yet, but will be released on monday.

freqtrade will probably support that out of the box (don't think 3.11 has many breaking changes) - however we'll not start testing against 3.11 actively before most of freqtrade's dependencies provide wheels for 3.11,which (based on experience from past updates) will take a few weeks.
