### ISSUE TITLE
Where is exit_reason = liquidated information ?

### ISSUE THREAD

**Issue by bleriot14** [freqtrade/freqtrade#7623]
Operating system: Windows 10

Python Version: Python 3.10.4

CCXT version: ------

Freqtrade Version: 2022.9.1

When a position is liquidated, it doesn't enter the confirm_trade_exit. So I cant take exit_reason which is one of the parameter of confirm_trade_exit function. How can my bot know wheter last position liquidated or not before entering the custom_stake_amount function ?

**Comment by xmatthias** [comment]
liquidations are not a reason to be confirmed - (nor to get custom pricing) - therefore it'll skip these callbacks - as they have no actionability.

you also shouldn't use callbacks to save this - they're NOT guaranteed to be called (as you've seen above).
Instead, you can use the [trade object](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-trades) to retrieve what you need - when you need it.

**Comment by bleriot14** [comment]
Thank you. Trade class solve my problem very well. 

But Trade class cant be used in backtesting Mode. How can I reach recent trade's profit when I use backtesting Mode?

**Comment by xmatthias** [comment]
Technically, there's `Trade.get_trades_proxy()` - which takes named arguments and also works in backtesting (only in callbacks!).

It's not really documented, and therefore kinda inofficial - but i suspect we'll be adding this to the documentation soon - as it's a feat that's often requested - and the only thing it's missing is really the documentation part.
