### ISSUE TITLE
Are funding fees correctly calculated using available_capital?

### ISSUE THREAD

**Issue by luyiming** [freqtrade/freqtrade#7624]
To run multiple bots on the same exchange account, documemtation suggests that we use `available_capital` configuration. https://www.freqtrade.io/en/stable/configuration/#assign-available-capital

Then, all profits and losses will be calculated and accumalated on `available_capital`, including funding fees. However, after reading the code, it seems that funding fees are not correctly calculated. For example, if we have +10 position on BTC/USDT in one bot and +20 position on BTC/USDT in another bot, then funding fees are calculated on the total +30 position in each bot. The calculation of profits in each bot may not be correct. The relavant code is listed here:

freqtrade/exchange/exchange.py
```python
    def get_funding_fees(
            self, pair: str, amount: float, is_short: bool, open_date: datetime) -> float:
        """
        Fetch funding fees, either from the exchange (live) or calculates them
        based on funding rate/mark price history
        :param pair: The quote/base pair of the trade
        :param is_short: trade direction
        :param amount: Trade amount
        :param open_date: Open date of the trade
        :return: funding fee since open_date
        :raies: ExchangeError if something goes wrong.
        """
        if self.trading_mode == TradingMode.FUTURES:
            if self._config['dry_run']:
                funding_fees = self._fetch_and_calculate_funding_fees(
                    pair, amount, is_short, open_date)
            else:
                funding_fees = self._get_funding_fees_from_exchange(pair, open_date)
            return funding_fees
        else:
            return 0.0
```

freqtrade/exchange/exchange.py
```python

    @retrier
    def _get_funding_fees_from_exchange(self, pair: str, since: Union[datetime, int]) -> float:
        """
        Returns the sum of all funding fees that were exchanged for a pair within a timeframe
        Dry-run handling happens as part of _calculate_funding_fees.
        :param pair: (e.g. ADA/USDT)
        :param since: The earliest time of consideration for calculating funding fees,
            in unix time or as a datetime
        """
        if not self.exchange_has("fetchFundingHistory"):
            raise OperationalException(
                f"fetch_funding_history() is not available using {self.name}"
            )

        if type(since) is datetime:
            since = int(since.timestamp()) * 1000   # * 1000 for ms

        try:
            funding_history = self._api.fetch_funding_history(
                symbol=pair,
                since=since
            )
            return sum(fee['amount'] for fee in funding_history)
        except ccxt.DDoSProtection as e:
            raise DDosProtection(e) from e
        except (ccxt.NetworkError, ccxt.ExchangeError) as e:
            raise TemporaryError(
                f'Could not get funding fees due to {e.__class__.__name__}. Message: {e}') from e
        except ccxt.BaseError as e:
            raise OperationalException(e) from e
```

The problem is that we calculate funding fees using `sum(fee['amount'] for fee in funding_history)` without considering the actual position (amount) of our trade.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

I'll refer you to the [short/leverage](https://www.freqtrade.io/en/stable/leverage/) documentation (the main reference when it comes to futures trading with freqtrade) - which clearly states:

> You can't run 2 bots on the same account with leverage. For leveraged / margin trading, freqtrade assumes it's the only user of the account, and all liquidation levels are calculated based on this assumption

in this regard - you're correct - it's using the full position - but for futures, we assume there is only freqtrade making trades - as such, this is not a problem.

Funding fees are your least problem - liquidation prices will also change - as your risk per position is now completely different.
While you can use `availlable_capital` to limit your position sizing - it'll not work properly for futures.

This is therefore an unsupported way of running freqtrade - and not something we'll be changing - as this limitation will become even more prevalent should we support cross futures.

If you want to run multiple bots (or trade manually) - please either use spot trading (or one spot bot, and one futures bot) - or use subaccounts if your exchange/ account supports this.

**Comment by luyiming** [comment]
Thanks for your response. 🙂

Since freqtrade supports multiple bots on spot trading, I would hope it also supports multiple bots on leveraged / margin trading. The problem is that, I really need multiple bots but I can't have subaccount in the exchange. Do you think this feature can be implemented (in theory)? for example, maybe we can implement subaccounts by ourselves? If it is possible, I would consider spending some time implementing this feature in my fork.

Do you have any suggestions or directions on my problem? Thanks.

**Comment by xmatthias** [comment]
in theory, everything can be implemented - but that doesn't mean that it's a good idea.

your whole risk-profile changes if you have competing positions open - which will change liquidation prices "at random" (at least at random for one bot, whenever someone else closes or opens a position).

at the moment, it's not something freqtrade supports - and it's not something we're currently working towards either
