### ISSUE TITLE
Running multiple bot instances

### ISSUE THREAD

**Issue by moooaaazzz** [freqtrade/freqtrade#7625]
Hi, 

I want to run multiple instances of the bot at the same time. According to the documentation I can deploy multiple instances with docker. May I know if there is another way around without docker? What would be your recommendation?

Thank you.

**Comment by stash86** [comment]
use screen or tmux, run multiple sessions on them. You can use 1 venv for all of them

**Comment by moooaaazzz** [comment]
Alright, thanks! so basically as long as I run multiple sessions using tmux, it won't create any issues even if I am sharing same config and Strategy file?

**Comment by stash86** [comment]
some things on the docs still applies. You need separate database, separate telegram bots, etc

**Comment by moooaaazzz** [comment]
Alright, got it. Thanks a lot!

**Comment by xmatthias** [comment]
there's a dedicated section in the [docs](https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade) about this. If you're not using docker, ignore the docker paragraph - the remainder will still apply.
