### ISSUE TITLE
How to blacklist tokens start with some letters?

### ISSUE THREAD

**Issue by Mo7mud** [freqtrade/freqtrade#7636]
## Describe your environment

  * Operating system:  windows 10
  * Python Version: 3.10.7
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.9.1
  
## Your question

I'm trying to blacklist tokens that starts with `HI`
I tried many formats but none of them worked.

**Comment by xmatthias** [comment]
it's a simple regex - as explained in the [docs](https://www.freqtrade.io/en/stable/plugins/#pair-blacklist).

Now regex is not "simple" per se if you've never used it - for your usecase, you'll need to use `HI.*` - which will blacklist (or whitelist, depending on the location you put this) all pairs that start with HI.

the binance blacklis in our template  (the one used to generate a config via `new-config` subcommand) uses a very similar (actually the same) pattern to blacklist all BNB pairs.

https://github.com/freqtrade/freqtrade/blob/7b7bb06291fe8c5af471fe70499f71dcb3adbe23/freqtrade/templates/subtemplates/exchange_binance.j2#L9-L12

**Comment by Mo7mud** [comment]
Thank you very much, I'm not familiar with regex actually.
