### ISSUE TITLE
High CPU load on database (postgres) calling all the order table.

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#7639]
Hi,

I have high CPU load in my postgres database because of the request (i am a bit **behond the freqtrade use case as i have thousands of orders as i use in this case freqtrade as market making tool**) :

What i use in my strat that call database :
-> `Trade.get_trades([Trade.is_open.is_(True)]).all()` witch should not call the order table ?
-> `check_entry_timeout(order: "Order")` witch should call only open orders ?

User | Query | Database | Schema | Tables | Node Types | Count | Duration(Avg-ms) | Rows Returned(Avg) | nScanned | Read Impact | nModified | Write Impact
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
freqtrade | SELECT trades.id AS trades_id, trades.exchange AS trades_exchange, trades.pair AS trades_pair, trades.base_currency AS trades_base_currency, trades.stake_currency AS trades_stake_currency, trades.is_open AS trades_is_open, trades.fee_open AS trades_fee_open, trades.fee_open_cost AS trades_fee_open_cost, trades.fee_open_currency AS trades_fee_open_currency, trades.fee_close AS trades_fee_close, trades.fee_close_cost AS trades_fee_close_cost, trades.fee_close_currency AS trades_fee_close_currency, trades.open_rate AS trades_open_rate, trades.open_rate_requested AS trades_open_rate_requested, trades.open_trade_value AS trades_open_trade_value, trades.close_rate AS trades_close_rate, trades.close_rate_requested AS trades_close_rate_requested, trades.realized_profit AS trades_realized_profit, trades.close_profit AS trades_close_profit, trades.close_profit_abs AS trades_close_profit_abs, trades.stake_amount AS trades_stake_amount, trades.amount AS trades_amount, trades.amount_requested AS trades_amount_requested, trades.open_date AS trades_open_date, trades.close_date AS trades_close_date, trades.open_order_id AS trades_open_order_id, trades.stop_loss AS trades_stop_loss, trades.stop_loss_pct AS trades_stop_loss_pct, trades.initial_stop_loss AS trades_initial_stop_loss, trades.initial_stop_loss_pct AS trades_initial_stop_loss_pct, trades.stoploss_order_id AS trades_stoploss_order_id, trades.stoploss_last_update AS trades_stoploss_last_update, trades.max_rate AS trades_max_rate, trades.min_rate AS trades_min_rate, trades.exit_reason AS trades_exit_reason, trades.exit_order_status AS trades_exit_order_status, trades.strategy AS trades_strategy, trades.enter_tag AS trades_enter_tag, trades.timeframe AS trades_timeframe, trades.trading_mode AS trades_trading_mode, trades.amount_precision AS trades_amount_precision, trades.price_precision AS trades_price_precision, trades.precision_mode AS trades_precision_mode, trades.contract_size AS trades_contract_size, trades.leverage AS trades_leverage, trades.is_short AS trades_is_short, trades.liquidation_price AS trades_liquidation_price, trades.interest_rate AS trades_interest_rate, trades.funding_fees AS trades_funding_fees, orders_XXX.id AS orders_XXX_id, orders_XXX.ft_trade_id AS orders_XXX_ft_trade_id, orders_XXX.ft_order_side AS orders_XXX_ft_order_side, orders_XXX.ft_pair AS orders_XXX_ft_pair, orders_XXX.ft_is_open AS orders_XXX_ft_is_open, orders_XXX.order_id AS orders_XXX_order_id, orders_XXX.status AS orders_XXX_status, orders_XXX.symbol AS orders_XXX_symbol, orders_XXX.order_type AS orders_XXX_order_type, orders_XXX.side AS orders_XXX_side, orders_XXX.price AS orders_XXX_price, orders_XXX.average AS orders_XXX_average, orders_XXX.amount AS orders_XXX_amount, orders_XXX.filled AS orders_XXX_filled, orders_XXX.remaining AS orders_XXX_remaining, orders_XXX.cost AS orders_XXX_cost, orders_XXX.stop_price AS orders_XXX_stop_price, orders_XXX.order_date AS orders_XXX_order_date, orders_XXX.order_filled_date AS orders_XXX_order_filled_date, orders_XXX.order_update_date AS orders_XXX_order_update_date, orders_XXX.funding_fee AS orders_XXX_funding_fee, orders_XXX.ft_fee_base AS orders_XXX_ft_fee_base FROM trades LEFT OUTER JOIN orders AS orders_XXX ON trades.id = orders_XXX.ft_trade_id WHERE trades.is_open IS false ORDER BY orders_XXX.id | mm_strat | public | trades, orders | Sort, Hash Join, Seq Scan, Hash, Seq Scan | 1446 | 28 | 7763 | 8040 | 11625840 | 0 | 0

Does freqtrade need to get all orders on every process_throttle (or my startegy is in reponsability) ? Can it be optimized with an index ?

Many thanks and have a nice day.

PS : you can tell me it is out of the scope of the project as it is borderline use case.

**Comment by xmatthias** [comment]
> `Trade.get_trades([Trade.is_open.is_(True)]).all()` witch should not call the order table ?

This will return full `Trade` objects, which includes all orders attached to this object.
This will run on every throttle operation (and once again - most likely per pair - if you call it within your strategy) - and is also a requirement - so not querying the orders table is not an option (in theory loading of this can be postponed to "when it's used" - but that'll only delay execution, it'll still need to query the orders table.

As far as I'm aware, indexes should be in place for the relevant columns (`ft_trade_id` on the Orders table)
https://github.com/freqtrade/freqtrade/blob/dd45a3f5008e827290afd66db71d977c6cc1f550/freqtrade/persistence/trade_model.py#L44

The filter  on "is_open" is clearly pushed into the database (` WHERE trades.is_open IS false ORDER `) (which is also an indexed column) - so this will only return the rows that actually match this.


> `check_entry_timeout(order: "Order")` witch should call only open orders ?

It's unclear what you mean with this if i'm honest. is this the location of your `get_trades()` call? - if so - then it'll run once per open order .. how many these are are obviously dependent on your strategy.

---

You say "thousands of orders" - how many is that - 2000? 10.000? more? 
i must admit, i never tested freqtrade with more than a low 3 digit number (i think something around 3000 trades - on sqlite) - which still worked fine, so my assumption would be that with postgres, it'll perform  much better than on sqlite.

can you do a timing on one call (basically wrap the request to  `Trade.get_trades([Trade.is_open.is_(True)]).all()` in `time.time()` calls - to estimate how much time one of the requests is actually taking?

---

you could/should also send me a database dump of the 2 tables in question (trades,order) - maybe via discord? - so i can test this myself - as I'm curious how freqtrade behaves with very high numbers of realistic trades (not just fake/dummy trades).

**Comment by xmatthias** [comment]
with the provided dump (299 trades, ~6151 orders) - i can't really see a slowdown.

`Trade.get_trades([Trade.is_open.is_(False)]).all()` returns in <0.5s (that's 6000+ objects sqlalchemy needs to create) - and this is a query that's only running when `/trades` is called (Or artificially via the strategy). 

for only open trades, it's a LOT faster at roughly 0.006 - barely measurable at any rate.
in short - the database is bored at something between 0.5% and 0.1% CPU load on my system (which is just a laptop, not some overpowered CPU monster).


> `check_entry_timeout(order: "Order")` witch should call only open orders ?

This part remains a mistory to me - that won't call anything in the database (unless you do) - the trade object for the open trade will have been retrieved with a trades query (for open trades) - and the order object is then updated with the live order info (if necessary).

**Comment by xmatthias** [comment]
Gonna close this based  on some private discord conversation, which showed that it's been queries initiated from within the strategy that have been causing this delay.
