### ISSUE TITLE
Candles stored on bot loop

### ISSUE THREAD

**Issue by alisalama** [freqtrade/freqtrade#7641]
## Describe your environment

  * Operating system: Mac OS Monterey
  * Python Version: 3.9
  * CCXT version: 2.0.58
  * Freqtrade Version: docker-2022.10.dev-dd45a3f5
  
## Your question

Is it possible to download the the candles stored as json during the bot loop? I'm fairly sure they are not being stored locally, as I can't find them and they don't seem to land in the same "user_data/ftx" folder that they do from the download-data script.

Currently I am running a cron job where I separately use the download-data command to download all the candles for the pairs I am running in my bot, and then run my own analysis on those candles. This is repeating the data download process, and obviously the more coins I target the more resources/api limit issues I hit.

**Comment by xmatthias** [comment]
candles downlaoded in "live" runs are not stored.

This would have several side-effects and complications - where suddenly, a live bot becomes responsible to make sure there'll be no holes in the data (this is currently the task of download-data).

Assuming you use Volumepairlist - and you run the bot for several months at a time - you could have no data for a month -after which the pair "reappears" in the pairlist.
now the live bot would need to download the missing data from the last available datapoint up to today - which (depending on the exchange used) can mean a several minute delay.

On top of that, it'd be almost constant writes (at least on low timeframes) - which are clearly unnecessary.

As such - this is currently not possible - and really, also not something we're looking into.

**Comment by alisalama** [comment]
Thanks Matthias. I figured it was something along those lines, but thought I'd ask.

I'll continue with the cron jobs.
