### ISSUE TITLE
HyperOpt.roi_space() missing 1 required positional argument: 'params'

### ISSUE THREAD

**Issue by Arivadis** [freqtrade/freqtrade#7643]
Hello,
I need some help to figure out how to use Overriding pre-defined spaces.

I try to hyperopt strategy with this spaces:
```
class vadim(IStrategy):
    class HyperOpt:

        def stoploss_space():
            return [DecimalParameter(-0.050, -0.001, decimals=3, default=-0.02, name='stoploss')]

        def generate_roi_table(params: Dict) -> Dict[int, float]:

            roi_table = {}
            roi_table[0] = params['roi_p']

            return roi_table

        # # Define custom ROI space
        def roi_space(params: Dict) -> list[DecimalParameter]:

            return [
                DecimalParameter(0.01, 0.20, decimals=3, default=1.0, name='roi_p')
            ]
```
It means i need only one static time(0) in pos ROI and space of %.
but i get this ERROR : TypeError: vadim.HyperOpt.roi_space() missing 1 required positional argument: 'params'.

If i delete it from function parameter i get another one error: Name is determined by parameter field name and can not be specified manually.

Can You please explain me, what I'm doing wrong?

If You need any additional information, please let me know.

Thank You for help!

**Comment by xmatthias** [comment]
well yes - not sure where you got the above values from - but that way it'll not work.

the [advanced hyperopt docs](https://www.freqtrade.io/en/latest/advanced-hyperopt/#overriding-pre-defined-spaces)  have a working example. 

you then also can't use parameters, but you'll have to use the skopt spaces for this.
you can import these from `from freqtrade.optimize.space import Integer, SKDecimal` (i'll add the import to the documentation).


a working sample (completely ignoring your sample, but built from the docs:
``` python
        def stoploss_space():
            return [SKDecimal(-0.05, -0.01, decimals=3, name='stoploss')]

        # Define custom ROI space
        def roi_space():
            return [
                Integer(10, 120, name='roi_t'),
                SKDecimal(0.01, 0.04, decimals=3, name='roi_p'),
            ]

        def generate_roi_table(params: Dict) -> Dict[int, float]:

            roi_table = {}
            roi_table[0] = params['roi_p']

            return roi_table
```

interrestingly, the non-documented function was correct, but the 2 that could be copied from the documentation you got wrong :laughing:

**Comment by Arivadis** [comment]
I had imported this: from freqtrade.optimize.space import Categorical, Dimension, Integer, SKDecimal, Real
But it always ask me for expected type int(Expected type 'int', got 'float' instead) when i used SKDecimal.
I thought it would not work(will try first next time)

It was completely mixed with several code-examples. Experiment is so experimental=)

It is working now.
Thank You!
