### ISSUE TITLE
Class name does not match with  py file name

### ISSUE THREAD

**Issue by rd-mg** [freqtrade/freqtrade#7645]
There is an error when trying to use this class from the command line, error says the Class doesn't exist, actually, it's needed to change the Class name to match the file name to solve the error

https://github.com/freqtrade/freqtrade/blob/1f5e92c0e7ed79ad33567c0ff331075ef2acd3a4/freqtrade/templates/FreqaiHybridExampleStrategy.py#L15

**Comment by xmatthias** [comment]
you'll need to provide us with the actual command you used to load this - and eventually with some output on what happened.

The above is non-conclusive - and therefore suggests an usage-error.
When loading anything dynamically (strategy, model, ...) - you'll always need to use the class name. The filename is irrelevant as long as it is a`.py` file - and is in the appropriate location.
