### ISSUE TITLE
FreqaiHybridExampleStrategy doesn't work using Classification models

### ISSUE THREAD

**Issue by rd-mg** [freqtrade/freqtrade#7646]
## Describe your environment

  * Operating system: Linux. Pop_os 22.04
  * Python Version: running  docker imagefreqtradeorg/freqtrade:develop_freqai
  * CCXT version: running freqtradeorg/freqtrade:develop_freqai docker image
  * Freqtrade Version: freqtrade docker-c3d4fb9f
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. Configure docker compose to use FreqaiHybridExampleStrategy and config_freqai_example.json
  2.  Add a send-to-csv instruction to debug populate-indicators returned dataframe, line 188 : `        dataframe.to_csv('/freqtrade/user_data/populate_indicators.csv', sep=',', encoding='utf-8')`
  3.  Change `set_generalized_indicators=True`

  4. run docker compose command on my end I execute this: `$ docker compose run --rm freqtrade trade --config config_examples/config_freqai.example.json --strategy FreqaiHybridExampleStrategy --freqaimodel XGBoostClassifier --strategy-path templates`

  5. wait until a coin is trained and populate_indicators.csv is created, 
  6. stop the bot
  7. open the csv file
  
[populate_indicators.csv](https://github.com/freqtrade/freqtrade/files/9865208/populate_indicators.csv)

### Observed Results:

  * What happened?
**df['&s-up_or_down']**  column and related columns has 0 value in resulting dataframe, see csv file

  * What did you expect to happen?

'**up**' and '**down**' inferenced values as evaluated in line 155 of the strategy, and needed in entry and exit functions

### Relevant code exceptions or logs

- No errors found
-  documentation read twice and compared with files, line by line

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by rd-mg** [comment]
Log:

Updated docker image to freqtrade docker-2022.10.dev-d831d7d3
Same Issue

@xmatthias could you send me an example strategy that works (inference) with classification models? Maybe, in this way, I can compare them and find the error?

**Comment by xmatthias** [comment]
for freqAI issues, i'm the wrong person to ping, but @robcaulk would be your man.

That said - for general issues, i'd recommend the [discord server](https://discord.gg/p7nuUNVfP7). You'll get help from people that are running (or in this case, have developed) this model - which will be able to tell you why you're observing what you are.

**Comment by robcaulk** [comment]
What does that mean that you “change `set_generalized_indicators` to true?” You changed the default value in the function arguments to true? That will cause undefined behavior no doubt. I’m not sure for what reason you’d change the default arguments of a function…
