### ISSUE TITLE
download-data command with unexpected output 

### ISSUE THREAD

**Issue by moooaaazzz** [freqtrade/freqtrade#7649]
## Describe your environment

  * Operating system: 64-bit operating system, x64-based processor
  * Python Version:  Python 3.10.7
  * CCXT version:  ccxt==1.93.98
  * Freqtrade Version:  2022.10.dev
  
## Your question

Hi, I have been specifying my timerange as 20220101-20220103. Therefore, I am expecting to download only 3 days of data. However, the app downloads around 6 months or random number of days of data. Is this the expected behavior? Why is not only downloading as per specified request? Would really appreciate, any leads that may help with the issue.

I am using Binance as exchange and have tried different symbols and timeframes to test it out. 

My example command: freqtrade download-data --exchange binance --timerange 20220201-20220203 -p BTC/USDT --timeframe 1h
Result: from 2022-02-02 00:00:00 to 2022-03-14 14:00:00

**Comment by xmatthias** [comment]
Exchanges don't provide "all" data in one request - but we need to batch requests (on binance, in lots of 1000).

So while the download will not stop "exactly" at the date you requested (why would it - that'd waste the already downloaded data) - but at the nearest (later) point.
on 1h candles, that's 1000 hours - so in your case, it's most likely only doing exactly one request - which gives you 1000 candles - which are 41 days - and roughly what you see.

**Comment by moooaaazzz** [comment]
> Exchanges don't provide "all" data in one request - but we need to batch requests (on binance, in lots of 1000).
> 
> So while the download will not stop "exactly" at the date you requested (why would it - that'd waste the already downloaded data) - but at the nearest (later) point. on 1h candles, that's 1000 hours - so in your case, it's most likely only doing exactly one request - which gives you 1000 candles - which are 41 days - and roughly what you see.

Alright, got it. Thanks for the explanation Xmatthias.
