### ISSUE TITLE
Exit profit only

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#7650]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.9.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

In the earlier days of Freqtrade, I was able to exit on profit only, simply by setting "exit_profit_only" to true. Currently the system exits on loss as well, with this configuration, I have to turn off the exit signal, and I need to work with ROI only, for exiting with only with profit.
What is currently the correct configuration, for exiting with profit only with the exit signal?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
`exit_profit_only` is still valid and applicable - but it's now accompanied with `exit_profit_offset` (which however defaults to 0 to maintain existing behavior).
Please note that both settings ONLY apply to regular exit signas (assigned to the dataframe as `exit_long` or `exit_short`).

Callbacks can still exit trades with this setting - and always could.

**Comment by myNextCoder** [comment]
I thank you. I have already changed my configs, this works fine for 'simple' strategies, but some complex ones, are now exiting with negative exits from the strategy itself. Since this is not custom_stoploss, but a different part of the exit trend code: Can I generally disable such negative exits within the config? Those exits seem not to be protected by exit_profit_only and exit_profit_offset.

**Comment by xmatthias** [comment]
If you're using `custom_exit` - then no - then it's the responsibility of the custom exit code to check for this (you can always dump a "if profit < 0" condition at the top of such a function ...

i think the general approach of "not taking losses" is a dangerous one - it's in many cases better to take a 1% loss (your strategy told you so) - than to hold on to it, and eat the 10% stoploss a few hours later ...
that's just a personal opinion / experience ... but maybe have a think about this.

**Comment by myNextCoder** [comment]
Many thanks, I have a look at these publicly available strategies, concerning custom_exit. And I also take into account, to test SL at 10%. According to my experience, a crypto-asset quite often may go to less than -10% first, before growing positive. What I sometimes do, is a 'time-bombed' SL, by setting for example the last ROI value to "8640": -0.1. In that case, the trade has a long time, to pass zero and then can exit with profit, if possible.

**Comment by xmatthias** [comment]
whatever you thinks makes profit is obviously valid. As i explicilty pointed out - the above is my personal opinion / trading style - not trading advise - so if your strategy aims for something different, different means can be appropriate.

**Comment by myNextCoder** [comment]
Absolutely, and I am always open to test new config-combinations. I appreciate your input :)
