### ISSUE TITLE
How to write a strategy that count when specific condition happens second time

### ISSUE THREAD

**Issue by VietnameseRick** [freqtrade/freqtrade#7652]
Hi, 

For example, if my strategy is place order when EMA8 and EMA9 cross over the 2nd time and the stop-loss price will be the lowest low (LL) between the first cross over and the 2nd cross over. Are there any way to write a strategy that can "COUNT" for situations like my example ?

**Comment by xmatthias** [comment]
freqtrade uses pandas under the hood - which in turn converts this into a pandas question.

so what you could do is something around the following (untested, partially conceptual only to give an example how this could work - do your own tests!)

```python
dataframe['emashort'] = ta.EMA(dataframe, 8)
dataframe['emalong'] = ta.EMA(dataframe, 9)

# This will populate "cross" with 1 or 0 - depending if it crossed or not
dataframe['cross'] = qtpylib.crossed_above(dataframe['emashort'], dataframe['emalong'])

# Do a rolling cross sum - each successful cross will increase "crosses" by 1
dataframe['crosses'] = dataframe.rolling(int(self.buy_rolling.value), min_periods=0)['cross'].sum()

dataframe['between_1_and_2'] = dataframe[(dataframe['crosses'] > 1) & dataframe['crosses'] < 3]
```

Now it's clearly not 100% what you need - but it should give you enough direction to implement your precise requirements.

**Comment by VietnameseRick** [comment]
Thank you. I am writing it, will feedback when it ran successfully 👍
