### ISSUE TITLE
Inconsistent profit with high starting capital vs low starting capital in backtesting.

### ISSUE THREAD

**Issue by xMattC** [freqtrade/freqtrade#7654]
## Describe your environment

  * Operating system: ubuntu
  * Python Version: 3.10.4
  * CCXT version: Using CCXT 1.92.20
  * Freqtrade Version: 2022.9.1 dev
  
## Describe the problem:

I noticed when re back-testing a specific time period where the bot previously perform well I observed a different profit curve. 

It seems as if the bot behaves differently when the account balance is large (>5M).

I did some further tests to confirm this behaviour:

### Steps to reproduce:

  1. Run a simple strategy several times with increasing starting capital.
  2. Should notice inconstancies when comparing high starting capital vs low starting capital. 
  
### Observed Results:
Same strat ran with different starting capital:

![image](https://user-images.githubusercontent.com/73446602/198577547-a24d50ee-aa52-4595-9f70-5cb33d5b3125.png)

Easy to avoid, but thought I would still log it!

**Comment by xmatthias** [comment]
we'll need a bit more details on the used configuration here.
for example max_open_trades, stake-amount, - best the whole used config (without keys, obviously) - so we can have an actual comparison.

Also, is this on spot or futures markets - if futures, with leverage?

**Comment by xMattC** [comment]
I didn't save the config sorry. The top of the file was

    "max_open_trades": 5,
    "stake_currency": "USDT",
    "fiat_display_currency": "GBP",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 1,
    "amount_reserve_percent": 0,
    "amend_last_stake_amount": true,
    "last_stake_amount_min_ratio": 0.5,
    "cancel_open_orders_on_exit": false,
    "dry_run": false,
    "dry_run_wallet": 100000,
    "timeframe": "5m",

In the strat I turned of all custom functions.

It was spot markets, long only no leverage.

**Comment by xmatthias** [comment]
After thinking and playing with this a bit - it's quite clear why this happens.
Exchanges have [trading limits](https://www.freqtrade.io/en/latest/backtesting/#trading-limits-in-backtesting).

These limits are there in several directions (Price, amount) - and usually apply on both sides (minimum amount, maximum amount).
for ETH/BTC  (and a few other "high marketcap"pairs) - the upper limits are quite high.
for other pairs, that's not the case.

I've done a test with a handful of random pairs ... (ADA/USDT being one of these, but also BTC/USDT and ETH/USDT).
now ADA/USDT is interesting as it has an upper limit of 900_000 ADA.
At current prices (~0.4) - that's a maximum stake of 360_000.0$.

now your configuration does the starting capital / 5.
as long as this results in a number *lower* than the smallest pair's maximum stake - that's no problem and values will align (unless you hit the lower limit, obviously).
once you get to 5m and 10M though - your stake is 1M and 2M each - which is clearly WAY above the 360k you're allowed to trade on this pair.

Freqtrade live (as well as backtest) aims to respect these limits, and will therefore adjust your stake-amount to these values. 

Obviously, this will change results with higher stakes (not just absolute values, but also relatives) - as now your positions are no longer "roughly" equally sized, but ADA (maybe a highly profitable one, maybe a losing one) - will have far lower stakes - and therefore count far less in the final relative value (which is the change in account size - not a simple sum of percentages).
It's however not wrong to do so, as it corresponds to how a live bot would trade.

---

In general, i do however advise to backtest with realistic wallets (if you're willing to risk 100$ - try with this - as it will influence the max_open_trades you are able to use).
Surely i could backtest with 100M$ - but that's unrealistic - at least for me. Results would be aligned to how it woudl work out in reality - and i'd probably be using 200 open trades in parallel (probably more) - but that's not realistic either - as i'll not be having 100M$ on the exchange to trade ...

**Comment by xMattC** [comment]
Thanks for looking at this! All makes perfect sense, now at least I know it's not something I'm doing.
