### ISSUE TITLE
Quiet mode still present?

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#7656]
## Describe your environment

  * Operating system: Windows Server 2022____
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.9.1____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

According to the older ticket #2408 there is a quiet mode, I can activate for example with the switch -qq
Since it is not recognized as a valid command, the notation may have changed, yes?
(Under "start the bot" on the website, I see no information)

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
it's been a proposal - but there's no point in running the bot in "silent" mode.

In regular (non-verbose) mode - it's not that verbose - and silencing it would mean we get 0 information in case of problems - which also means we get 0 chance of helping anyone that's running such a mode.

As such - it would have to come with the warning "don't even attempt to open an issue when running in quiet mode" - which i find would be bad from a community / support perspective.

**Comment by myNextCoder** [comment]
It makes absolutely no sense, to mute important information, I just wanted to make a test, with "no message", because some months ago I discovered a difference in CPU usage between -v and -vvv. So I was thinking, just let's see what happens, if no messages at all are generated. But you are right, there are to many disadvantages.

**Comment by xmatthias** [comment]
well -vvv will generate several 100 messages per second (if you're unlucky) ... 

so that WILL have an impact - simply because the terminal will be slow to process these.

**Comment by myNextCoder** [comment]
absolutely, I do it very seldom
