### ISSUE TITLE
Partial Exit Values

### ISSUE THREAD

**Issue by batuhanhazarguler** [freqtrade/freqtrade#7664]
## Describe your environment

  * Operating system: Ubuntu 22.04.1 LTS
  * Python Version: 3.10.6 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.9.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

**Breaking change partial exit values will now be assumed to be stake_amount without leverage.**
Will I continue to use this solution in the next update(2022.10)?

`
     if current_profit > self.safety_profit_deviation and trade.nr_of_successful_exits == 0 and count_of_entries > 1:
         return -(trade.stake_amount / 2)*trade.leverage
`

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
I'm not sure what's unclear about "stake_amount without leverage".

The [documentation](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position) describes the new behavior, too - which is now aligned between entries and exits, and takes the stake amount you'd try to exit (if you are in a 5x trade, and your function returns -100 ($) - the order will be for 100 x 5 = 500$).
