### ISSUE TITLE
NOOB QUESTION

### ISSUE THREAD

**Issue by dotpedro** [freqtrade/freqtrade#7669]
Gotcha.

## Describe your environment

  * Operating system: Raspbian____
  * Python Version: __Python 3.9.2___ (`python -V`)
  * CCXT version: __2.0.58___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __2022.10__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
Hey, I apologize in advance if this a noob type of question.

However, I would like to fully understand why the missing data fillup message keeps showing up in the time frame that I've set.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
![2022-10-30-214827_1920x1080_scrot](https://user-images.githubusercontent.com/117044847/198903278-3b62768c-d151-4e4b-aeba-21b63a6a047e.png)
![2022-10-30-215012_1920x1080_scrot](https://user-images.githubusercontent.com/117044847/198903279-d341718d-4f86-4cab-be21-69c3ebe145b6.png)

**Comment by dotpedro** [comment]
I thought I solved it but the issue persists.

![2022-10-30-224053_1920x1080_scrot](https://user-images.githubusercontent.com/117044847/198905241-8a65e65f-ab32-4c28-b7fb-c2a7a9683051.png)
![2022-10-30-224030_1920x1080_scrot](https://user-images.githubusercontent.com/117044847/198905245-3821520c-ea8f-403a-8273-98e8f6c9ad1b.png)

**Comment by xmatthias** [comment]
For the future, please don't post screenshots of logs - but post the logs as text. That'll make them searchable for the future, and greatly improves handling of the data.


---

coinbasepro is not really a supported exchange - as such i'm not sure how well their data is (and if they actually provide historic data).
Your datafillup is just a few candles - so it might be allright (exchange downtime, ...) - but it may also show that the pair either has very low volume - or that the data you get from this exchange is not 100% correct.
