### ISSUE TITLE
Should I use ,,load=True" for hyperoptoptable parameters when generated json is used?

### ISSUE THREAD

**Issue by rongybika** [freqtrade/freqtrade#7670]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.8.10 (`python -V`)
  * CCXT version: 1.93.98 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.9.1(`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi,

Sorry but I'm bit confused.
Should I use  in live mode ,,load=True" or ,,load=False" option for hyperoptable parameters (buy, sell, protection) when I'm using auto generated json file by hyperopt? Or every parameter is loaded from this json file not matter if this ,,load" option is present or not?

Maybe in the future can be added a new tab to the UI with all used configuration information? To be sure if the ,,correct" one is used.

Thank you

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
"load" defines if the parameter should be loaded (this includes the parameter file - but also parameter values defined as `buy_params = {}` ... - basically everything that's not the default.

The used parameters are shown in the logs - if a parameter is disabled, you'll get a clear warning that "parameter exists but is disabled, using default value of xxx" (with slightly different wording).
