### ISSUE TITLE
is there any mothed to put a sub order when submit a order?

### ISSUE THREAD

**Issue by gitscamI** [freqtrade/freqtrade#7682]
freqtrade the bot loop runs every few seconds to Fetch open  OHLCV data , then to decide submit sell and buy order or close order, now I want to when submit sell or buy order,at the same time submit a take profit orders or stop-loss order to replace it detect and submit close order. is there any method?? thanks Very Much!!!

**Comment by xmatthias** [comment]
Please post basic question to the freqtrade repository (where they belong).

The strategy repository is a source for strategies / inspiration (and eventually detail queestions about the strategies there)  - but not a primary place for generic questions.
You should either use issues on the main repository - or preferrably, the [discord server](https://discord.gg/p7nuUNVfP7) to get support / help from the community.
People there love to help assuming the documentation has been consulted first.


---

Freqtrade does support [stoploss on exchange](https://www.freqtrade.io/en/latest/stoploss/#stop-loss-on-exchangefreqtrade) - 
Please consult the documentation how to configure this (I'd strongly recommend to read through the documentation at least once - so you're aware on what functionalities freqtrade offers).

There is an open issue about take profit orders (#7499) - but that's unlikely to be implemented anytime soon.

**Comment by gitscamI** [comment]
sorry about that .  stoploss_on_exchange  can resolve the stop loss order problem, but i dont found it  can resolve take profit orders . means when open a order by Long or Short Signal ,at the same time I want to submit a more higher or lower price order to take profit close order.   how to deal with such situation?? thanks
