### ISSUE TITLE
custom_stoploss: In backtesting -> current_profit only considering body of the candle, not the wicks

### ISSUE THREAD

**Issue by the-master006** [freqtrade/freqtrade#7684]
## Describe your environment

  * Operating system: Ubuntu 22.04.1 LTS
  * Python Version: 3.10 (`python -V`)
  * CCXT version: CCXT 1.93.98 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 22.9.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

When using custom_stoploss in a risk reward ratio, (like the example strategy in the strategy repositry) I see everytime that my breakeven stoploss is not triggered while the candle is certainly higher then x times the risk.
After debugging I found out that current_profit (and current_rate) only show the open value, and I believe they only use the body of the candle to see if the current_rate is in that range. So if I say that: if  current_profit > break_even_profit_pct:
And break_even_profit false in the wick of the candle than the condition is not met.

### Steps to reproduce:

  1. Backtest the strategy: FixedRiskRewardLoss.py on some data and find a trade with a candle with a high wick in it: if the break_even_profit_distance falls within the wick it will not be triggered.

![Risk_reward_custom_stoploss](https://user-images.githubusercontent.com/65864740/199331957-f2c2275f-59f7-4a40-af42-882eedb8dd02.JPG)  

![Risk_reward_custom_stoploss1](https://user-images.githubusercontent.com/65864740/199333022-424b3d81-43ec-4e89-a773-aa656c19f928.JPG)

### Observed Results:

  * What happened?
      The absolute or initial stoploss got triggered instead of the "break-even" stoploss which should fall in the wick. 
  * What did you expect to happen?
      That the "break-even" stoploss got triggered which is stopping the trade at the open-rate + fees.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
            initial_sl_abs = low * self.sell_stop_abs_fact.value ##/self.sell_stop_abs_fact.value

            # calculate initial stoploss at open_date
            initial_sl = initial_sl_abs / current_rate - 1

            # calculate take profit treshold
            # by using the initial risk and multiplying it
            risk_distance = high * self.buy_limit_abs_fact.value - initial_sl_abs * self.sell_stop_abs_fact.value
            reward_distance = risk_distance * self.custom_info['risk_reward_ratio']
            # take_profit tries to lock in profit once price gets over
            # risk/reward ratio treshold
            take_profit_price_abs = trade.open_rate + reward_distance
            # take_profit gets triggerd at this profit
            take_profit_pct = take_profit_price_abs / trade.open_rate - 1

            # break_even tries to set sl at open_rate+fees (0 loss)
            break_even_profit_distance = risk_distance * self.custom_info['set_to_break_even_at_profit']
            break_even_price_abs = break_even_profit_distance + trade.open_rate
            # break_even gets triggerd at this profit
            break_even_profit_pct = (break_even_profit_distance + current_rate) / current_rate - 1

            result = initial_sl
            if (current_profit >= break_even_profit_pct):
                break_even_sl = (trade.open_rate * (1 + trade.fee_open + trade.fee_close) / current_rate) - 1
                break_even_sl_abs = trade.open_rate * (1 + trade.fee_open + trade.fee_close)
                result = break_even_sl

            if (current_profit >= take_profit_pct):
                takeprofit_sl = take_profit_price_abs / current_rate - 1
                result = takeprofit_sl

        return result
  ```

**Comment by xmatthias** [comment]
This is correct and was intentional behavior in versions prior to 2022.10.

This changed in [2022.10](https://github.com/freqtrade/freqtrade/releases/tag/2022.10) - where custom_stoploss is now being called with "high" instead of open.

**Comment by the-master006** [comment]
Ok clear, Thanks @xmatthias!
