### ISSUE TITLE
Permission issue - docker freqtrade on raspberry pi 3

### ISSUE THREAD

**Issue by ComradeSerg** [freqtrade/freqtrade#7687]
Hello,
I tried to install Freqtrade docker version on Raspberry Pi 3 Model B Rev 1.2. But I can't because of permissions error:

pi@raspberrypi:/freqtrade $ docker compose run --rm freqtrade create-userdir --userdir user_data
2022-11-02 12:57:21,359 - freqtrade - INFO - freqtrade 2022.10
sudo: error in event loop: Operation not permitted
sudo: unexpected child termination condition: 0
2022-11-02 12:57:21,410 - freqtrade.configuration.directory_operations - WARNING - Could not chown user_data

I tried to do the same using sudo, but there is no difference, outcome the same. I tried to give all permissions chmod 777 user_data, but it doesn't help also.
Issue  #4917 looks like in my case, but there are no solutions can help me.

My configuration
OS:
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Docker
pi@raspberrypi:/freqtrade $ docker version
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 17:59:34 2022
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:57:24 2022
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by xmatthias** [comment]
who (which user) owns the current directory (`/freqtrade`) - as well as the user directory? 

Please post the output of `ls -l /freqtrade` - this should include both information above.

**Comment by ComradeSerg** [comment]
Current owner is user pi, I tried to change owner to root but it doesn't help

pi@raspberrypi:/freqtrade $ ls -la /freqtrade/
total 16
drwxrwxrwx  3 pi   root 4096 Nov  2 14:57 .
drwxr-xr-x 20 root root 4096 Nov  2 01:31 ..
-rw-r--r--  1 pi   pi    937 Nov  2 14:41 docker-compose.yml
drwxr-xr-x 11 pi   pi   4096 Nov  2 14:57 user_data


pi@raspberrypi:/freqtrade $ ls -la user_data/
total 44
drwxr-xr-x 11 pi pi   4096 Nov  2 14:57 .
drwxrwxrwx  3 pi root 4096 Nov  2 14:57 ..
drwxr-xr-x  2 pi pi   4096 Nov  2 14:57 backtest_results
drwxr-xr-x  2 pi pi   4096 Nov  2 14:57 data
drwxr-xr-x  2 pi pi   4096 Nov  2 14:57 freqaimodels
drwxr-xr-x  2 pi pi   4096 Nov  2 14:57 hyperopt_results
drwxr-xr-x  2 pi pi   4096 Nov  2 14:57 hyperopts
drwxr-xr-x  2 pi pi   4096 Nov  2 14:57 logs
drwxr-xr-x  2 pi pi   4096 Nov  2 14:57 notebooks
drwxr-xr-x  2 pi pi   4096 Nov  2 14:57 plot
drwxr-xr-x  2 pi pi   4096 Nov  2 14:57 strategies

**Comment by xmatthias** [comment]
You should try to run the command - 
`docker compose run --rm freqtrade create-userdir --userdir user_data` - but deleting the existing user_data directory before this (better rename it to avoid data loss - if it already has contents).

please run `ls -la user_data/` on this again - which should show us the permissions for the newly created directory.

**Comment by ComradeSerg** [comment]
No worries about data, this is fresh raspbian install, we can delete everything or install raspbian anew.
I created new root folder, because I played with old one with chown and chmod

sudo mkdir /freqtrade1
cd /freqtrade1
sudo curl https://raw.githubusercontent.com/freqtrade/freqtrade/develop/docker-compose.yml -o docker-compose.yml
pi@raspberrypi:/freqtrade1 $ docker compose run --rm freqtrade create-userdir --userdir user_data
[+] Running 1/1
 ⠿ Network freqtrade1_default  Created 0.3s
2022-11-02 18:53:29,979 - freqtrade - INFO - freqtrade 2022.10
sudo: error in event loop: Operation not permitted
sudo: unexpected child termination condition: 0
2022-11-02 18:53:30,034 - freqtrade.configuration.directory_operations - WARNING - Could not chown user_data

pi@raspberrypi:/freqtrade1 $ ls -la /freqtrade1
total 16
drwxr-xr-x  3 root root 4096 Nov  2 20:53 .
drwxr-xr-x 21 root root 4096 Nov  2 20:49 ..
-rw-r--r--  1 root root  947 Nov  2 20:52 docker-compose.yml
drwxr-xr-x 11 pi   pi   4096 Nov  2 20:53 user_data

pi@raspberrypi:/freqtrade1 $ ls -la user_data/
total 44
drwxr-xr-x 11 pi   pi   4096 Nov  2 20:53 .
drwxr-xr-x  3 root root 4096 Nov  2 20:53 ..
drwxr-xr-x  2 pi   pi   4096 Nov  2 20:53 backtest_results
drwxr-xr-x  2 pi   pi   4096 Nov  2 20:53 data
drwxr-xr-x  2 pi   pi   4096 Nov  2 20:53 freqaimodels
drwxr-xr-x  2 pi   pi   4096 Nov  2 20:53 hyperopt_results
drwxr-xr-x  2 pi   pi   4096 Nov  2 20:53 hyperopts
drwxr-xr-x  2 pi   pi   4096 Nov  2 20:53 logs
drwxr-xr-x  2 pi   pi   4096 Nov  2 20:53 notebooks
drwxr-xr-x  2 pi   pi   4096 Nov  2 20:53 plot
drwxr-xr-x  2 pi   pi   4096 Nov  2 20:53 strategies

**Comment by xmatthias** [comment]
why is your parent folder (`/freqtrade1`) owned by root? i think that should be owned by pi, too... I'm not sure permissions of a subdir can be changed if the parent is owned by root ...

**Comment by ComradeSerg** [comment]
This is because on raspberry I can't create folder without sudo. But before I reported issue, I changed owner to pi for root folder and all subfolders, but it doesn't have impact, error the same. If you wish, I can open SSH session to my raspberry, you can check it by yourself. Nothing important there, fresh install, you can modify/delete what you want.

**Comment by xmatthias** [comment]
the funny thing is - i use a raspberry myself, and haven't had this problem ever (but i'm not using /freqtrade - but `/home/pi/freqtrade` as root dir - so i CAN create directories on the regular directory

**Comment by ComradeSerg** [comment]
Just tried your configuration with the same outcome. May be issue related to docker version.
![image](https://user-images.githubusercontent.com/68647213/199594195-42594b96-e46a-4a12-bd79-6843f6eeedf5.png)

**Comment by xmatthias** [comment]
i'm using the same docker-version than you do.

What i noticed though is that your image is "VERSION="10 (buster)"" - which the raspberry page defines as "raspberry OS - legacy".
Please retry with the latest raspberry version (11 / bullseye) - as this may have something to do with ti

**Comment by ComradeSerg** [comment]
Thanks, you are right. I installed 11 / bullseye and the problem is gone.

**Comment by xmatthias** [comment]
Docker is sometimes odd with outdated OS's ... strange - but don't really know why ...
