### ISSUE TITLE
Forceexit only positive positions

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#7696]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

Let's say, someone wants to get all current profits, and wants to be sure, that the sum of the current gains, won't go down anymore. For example, as the status table on the attached picture takes place. Why not give the possibility, to end all trades, which are currently positive, like for example '/forceexit all positive'. After such a command, only the negative ones, which have a chance to grow above zero, would stay active. All other ones would be closed.

*Explain the enhancement you would like*
![Screenshot_1](https://user-images.githubusercontent.com/34372534/199774733-78316993-0442-438f-98d4-c6847e705e11.jpg)

**Comment by xmatthias** [comment]
You can use `/forceexit <tradeid>` to forcesell single trades - in your case, the ones that are positive.

We'll not be implementing custom / random commands like this one - as it is not generally applicable - and everyone will have a different opinion on how exactly it should work (with offset, without offset, only if it's open for longer than X amount of time, ...).

**Comment by myNextCoder** [comment]
Yes, with the tradeid, this scenario can be done manually
