### ISSUE TITLE
How to map port so people in my LAN can access to freqUI inside docker ?

### ISSUE THREAD

**Issue by VietnameseRick** [freqtrade/freqtrade#7698]
How to map port (sorry if I use wrong word) so people in my LAN can access to freqUI inside docker ?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Your docker-compose file has the following segment:
```
    ports:
      - "127.0.0.1:8080:8080"
```

This tells the bot to only listen on localhost (only accessible from your computer).

You can change this to 

```
    ports:
      - "0.0.0.0:8080:8080"
```

which will make it accessible for the whole network (everyone who knows your IP / hostname and port).

This should only be done on a trusted network (!) and you should never do this without further protections on a VPS or similar.
