### ISSUE TITLE
History and real-time bars on OKX are using Hong Kong timezone instead of UTC

### ISSUE THREAD

**Issue by yul** [freqtrade/freqtrade#7700]
## Describe your environment

  * Operating system: Linux Ubuntu
  * Python Version: Python 3.10.6
  * CCXT version: <whatever is in the stable container image I guess?>
  * Freqtrade Version: 2022.9.1
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

My history data and live dry trades using OKX futures market on 1d (daily) timeframe are using 16:00UTC as bar end time, which is midnight in Hong Kong time. OKX API supports both Hong Kong and UTC timezone, here is an extract from their API docs:

```
Bar size, the default is 1m
e.g. [1m/3m/5m/15m/30m/1H/2H/4H]
Hong Kong time opening price k-line：[6H/12H/1D/1W/1M/3M/6M/1Y]
UTC time opening price k-line：[/6Hutc/12Hutc/1Dutc/1Wutc/1Mutc/3Mutc/6Mutc/1Yutc]
```

links: 
https://www.okx.com/docs-v5/en/#rest-api-market-data-get-candlesticks
https://www.okx.com/docs-v5/en/#rest-api-market-data-get-candlesticks-history

For example, compare these requests:
https://www.okx.com/api/v5/market/candles?instId=BTC-USDT-SWAP&bar=1D
https://www.okx.com/api/v5/market/candles?instId=BTC-USDT-SWAP&bar=1Dutc

I think for consistency we should always use UTC timezone, or at least give user a choice?

### Steps to reproduce:

  1. Add OKX futures in config.json
  2. Add BTC/USDT:USDT to white list
  3. run freqtrade download-data to download price data with 1d timeframe

OR 
  3b. run strategy on 1d timeframe
  
### Observed Results:

  * You can see that downloaded price data has 16:00 UTC component in their timestamps when coverted to date/time
  * I expected them to have 0:00 in UTC timezone

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  I don't think there are important log messages for this issue.
  ```

**Comment by xmatthias** [comment]
i think this issue is wrong in this repository, but should be raised against OKX.

Freqtrade will not make this distinction, but will consume whatever ccxt provides via `fetch_ohlcv()` call.

In general, my assumption was that ccxt will be providing data with UTC timestamps (that's the case for all other exchanges) - if that's not the case, then this is most likely a bug in ccxt.
There is also handling for this in the okx class (to some degree) - and as far as i can tell, the default is UTC.

The timestamps for 1d candles are indeed not in UTC timezone - and i think i've already identified the bug in the ccxt code - so i'll open an issue there.

**edit** https://github.com/ccxt/ccxt/issues/15565

**Comment by yul** [comment]
Thank you, @xmatthias, can you tell me when this update will get into development/stable docker images? I'm not sure what is your delivery schedule is...

**Comment by xmatthias** [comment]
it's in development now (will be in docker images as soon as CI completes).
Stable is usually released towards the last few days of the month - and will obviously include this release as well.

**Comment by yul** [comment]
hmm, is is possible that when trading it still uses Hong Kong time zone? I have updated my server's image:
```
REPOSITORY               TAG            IMAGE ID       CREATED      SIZE
freqtradeorg/freqtrade   develop_plot   62f9a12e789c   5 days ago   1.05GB
```

and backtests are now working in UTC as expected, however on dry trading orders are still issued at 16:00UTC (on 1d timeframe):
 
```
2022-11-10 17:28:08,532 - freqtrade - INFO - freqtrade docker-2022.11.dev-820aad67
2022-11-10 17:28:08,538 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2022-11-10 17:28:08,545 - freqtrade.loggers - INFO - Verbosity set to 0
2022-11-10 17:28:08,546 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2022-11-10 17:28:08,644 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2022-11-10 17:28:08,646 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/okx ...
2022-11-10 17:28:08,648 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2022-11-10 17:28:08,674 - freqtrade.exchange.check_exchange - INFO - Exchange "okx" is officially supported by the Freqtrade development team.
2022-11-10 17:28:08,677 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-11-10 17:28:08,678 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-11-10 17:28:08,692 - freqtrade.commands.list_commands - INFO - Using DB: "sqlite:///user_data/tradesv3.sqlite"
2022-11-10 17:28:08,797 - freqtrade.commands.list_commands - INFO - Printing 8 Trades: 
Trade(id=1, pair=YFII/USDT:USDT, amount=0.10000000, is_short=False, leverage=1.0, open_rate=1892.10000000, open_since=2022-11-09 16:00:17)
Trade(id=2, pair=BSV/USDT:USDT, amount=148.00000000, is_short=True, leverage=1.0, open_rate=39.43000000, open_since=2022-11-10 16:00:21)
Trade(id=3, pair=NYM/USDT:USDT, amount=6809.00000000, is_short=True, leverage=1.0, open_rate=0.21570000, open_since=2022-11-10 16:00:22)
Trade(id=4, pair=AGLD/USDT:USDT, amount=8269.00000000, is_short=True, leverage=1.0, open_rate=0.25630000, open_since=closed)
Trade(id=5, pair=GMT/USDT:USDT, amount=277.00000000, is_short=True, leverage=1.0, open_rate=0.41900000, open_since=2022-11-10 16:00:32)
Trade(id=6, pair=JST/USDT:USDT, amount=1400.00000000, is_short=True, leverage=1.0, open_rate=0.02391000, open_since=2022-11-10 16:00:33)
Trade(id=7, pair=SC/USDT:USDT, amount=19700.00000000, is_short=True, leverage=1.0, open_rate=0.00263200, open_since=2022-11-10 16:00:37)
Trade(id=8, pair=SRM/USDT:USDT, amount=28.00000000, is_short=True, leverage=1.0, open_rate=0.39900000, open_since=2022-11-10 16:00:38)
```

**Comment by xmatthias** [comment]
the version in your (new) logs (820aad67) is from prior to he fix.
that's also confirmed by the container - which is 5 days old - the fix was added to develop 4 days ago.

best update to the latest version - and make sure that ccxt shows up as 2.1.33 or above.

**Comment by yul** [comment]
@xmatthias weird, I have updated it right after I asked you when it will get to the image... Also I wonder why backtests were working correctly, perhaps because I switched from stable to development... 
Anyway, I have updated image, it is using CCXT 2.1.54, hope it works. 
Thanks for your help.

**Comment by xmatthias** [comment]
As i mentioned - 

> (will be in docker images as soon as CI completes).

that usually takes something between 25 and 60 minutes ... ;)
