### ISSUE TITLE
StoplossGuard with lookback_period '0' for 'right now'?

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#7705]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.10 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I want to take effect the StoplossGuard immediately after one stoploss. Does '0' works for lookback_period, which should mean "right now", and even not one minute?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
I'm not sure what you're going after - but no matter what you try to do, using `lookback_period=0` seems wrong.

This defines how far back we look to consider a trade. setting this to 0 would mean we look at "right now" only - which might seem correct for humans - but the computer will have a few ms ticket further between closing the trade, and checking for protections - and as such, would find 0 trades.

Guessing on what your actual goal is, i suspect setting `trade_limit=1` and lookback_period to a small value (bigger than 0!) should work.

**Comment by myNextCoder** [comment]
I thank you, I was thinking, that a timerange under lookback_period fits best, if we have trade_limit more than one trade. One SL on one trade is a timerange of almost nothing. But I understand the way, Freqtrade can handle the event, so 0 cannot be used a the trigger, according to your text. I test my scenario with 1.

**Comment by xmatthias** [comment]
assuming you use a "per pair" guard (with a limit of 1, it doesn't really make sense to lock globally i think) - using 1 would mean 1 closed trade for this pair within the last minute.

Since we don't support sub-minute timeframes, it'd be impossible to have more than one trade per pair close within the last minute - so this will exactly fill your need.
