### ISSUE TITLE
High price since the last candle

### ISSUE THREAD

**Issue by schmip** [freqtrade/freqtrade#7721]
Hi. I did read some issues about incomplete candles and freqtrade does not support that. So I've got that point. My question is similar to that (sorry for this), but maybe something being possible. I work with 4hour candles. Is it possible somehow to know the maximum price in the current 4hour candle? I know you do not have incomplete candles. I am thinking if it's possible to use minute candles parallel to the 4 hour candles and check the price based on the time since the last 4h candle close on minutes level... Is it possible somehow?

Thank you.
Peter

**Comment by stash86** [comment]
You can use custom_dict to store that value, taken from ticker data

**Comment by stash86** [comment]
Use whatever minute timeframe you want as the main timeframe, and 4h as informative timeframe

**Comment by xmatthias** [comment]
Please get used to fill out the issue template.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions . . . 

---

in theory, you can also use informative pairs with 1m for that - you just can't merge them - as that would split a 4h candle into 60*4 rows. You can however use them to determine "whatever" at an aggregated state.

The signals based on this would however become repainting (they appear/disappear at random throughout the candle) - and could therefore no longer be relied upon for future analysis on a chart.

**Comment by schmip** [comment]
Hi xmatthias and stash86. Sorry not using the Github properly. I will be more careful in the future. Thank you for your answers it really helps! 

I did find the informative time frame finally on the site (my fault) and I feel that it's something I can use. I will test it and let you know if I see issues. Thank you!

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.
