### ISSUE TITLE
can I set a extra orderinfo??

### ISSUE THREAD

**Issue by gitscamI** [freqtrade/freqtrade#7725]
for example ,I make a order with freqtrade in binance,  when making order, I want to add a newClientOrderId info in binance orders whice supply it. how to do it ?? thanks

**Comment by xmatthias** [comment]
Let me repeat this one last time: this is the wrong repository to ask such questions - please ask in the freqtrade main repo (as also explained in #7682).

This will be the last time i'll be moving your issue - next time i'll simply close it, asking you to repost your question in the right location.

---

This is not possible - and i honestly don't understand the purpose of this.
Maybe if you explain your usecase (why you need this) - we can see if there's methods to accomplish what you're after.

**Comment by xmatthias** [comment]
Feel free to comment below / reopen if you're willing to share your usecase of why this would be necessary.
