### ISSUE TITLE
docker-compose run returns and error

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#7729]
## Describe your environment

  * Operating system: ____ Ununtu 20.04
  * Python Version: _____ (`python -V`) 3.10
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker) latest
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

When I run docker-compose run it returns and error

### Steps to reproduce:

  1. _____ run docker-compose run --rm freqtrade -reload_config
  2. _____
  3. _____
  
### Observed Results:

  * What happened? returns @instance-20220819-1716:~/ft_userdata$ docker-compose run --rm freqtrade -reload_config ERROR: No such service: freqtrade
  * 
  * What did you expect to happen? I've tried several different commands

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
It's unclear what you're trying to accomplish.

There's no real output - and the only hint at what is going on is the command - which is not a valid bot command line argument.

So what exactly are you trying to accomplish?

It also seems like you've modified the compose file (freqtrade IS a valid service if using the default compose file) - therefore we'll need the compose file as well.

**Comment by tomjrtsmith** [comment]
Here's my compose file, it won't seem to run any command line

---
version: '3'
services:
  freqtrade1:
    image: freqtradeorg/freqtrade:develop_freqai
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqai2
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "80:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config_freqai.example.json
      --strategy FreqaiExampleStrategy
      --freqaimodel LightGBMRegressor

**Comment by tomjrtsmith** [comment]
Ah, I see the problem I've renamed the service in the compose file. Thanks Matthias.
