### ISSUE TITLE
MaxDrawDown on forceexit

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#7731]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.10 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Using forceexit I discovered, that MaxDrawDown might be activated, if the conditions fit. As forceexit does not follow market changes,  I ask you, if it makes sence, to trigger MaxDrawDown after artificial exits. In fact the protection reacts on human interaction in that case.
I look forward to your feedback.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by stash86** [comment]
MaxDrawDown reacts to Drawdown, simple as that. Drawdown don't care why you suffered the loss. Drawdown =/= market change.

**Comment by xmatthias** [comment]
Just as @stash86 said - it's a question of drawdown. 
WHY you encounter this drawdown is not relevant (and shouldn't be). 

It's simple math without exclusions (why would we? you still lost money).
