### ISSUE TITLE
how can I sell only half of assets

### ISSUE THREAD

**Issue by emamheba** [freqtrade/freqtrade#7732]
## Describe your environment
Hello,
I do not want to sell all my assets so,
How can I sell half of the asset instead of all assets during trading??
  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by stash86** [comment]
Read the docs, look for adjust_trade_position

**Comment by xmatthias** [comment]
the [adjust_trade_position](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position) documentation has this part covered.

I'd in general ask you to
* fill out the issue template
* try to search for answers in the documentation

before opening issues.

**Comment by emamheba** [comment]
> ## Describe your environment
> Hello, I do not want to sell all my assets so, How can I sell half of the asset instead of all assets during trading??
> 
> * Operating system: ____
> * Python Version: _____ (`python -V`)
> * CCXT version: _____ (`pip freeze | grep ccxt`)
> * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
> 
> ## Your question
> _Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)_



> the [adjust_trade_position](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position) documentation has this part covered.
> 
> I'd in general ask you to
> 
> * fill out the issue template
> * try to search for answers in the documentation
> 
> before opening issues.

thank you for your reply 
but [adjust_trade_position]
is for perform additional order I want in each order to determine the amount of stock 
how can i do this... there is any example

**Comment by xmatthias** [comment]
Changing your Trade size (e.g. sell half of the BTC the bot bought) will always involve a separate, discrete order, which is placed on the exchange.
this order can increase your size (you're buying more BTC) - or decrease your size (you're selling part of the BTC you own).

Both are possible with adjust_trade_position.
