### ISSUE TITLE
Freqtrade won't install - setup.sh: line 43: 665071 Killed

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#7734]
## Describe your environment

  * Operating system: ____ Ubuntu 20.04
  * Python Version: _____ (`python -V`) 3.10.6
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I'm having an identical problem on 2 Oracle AMD chip vps's. The setup script errors out at line 43 on both of them. Both have existing docker installations but nothing else of note.

### Steps to reproduce:

  1. _____ cd freqtrade
  2. _____ bash setup.sh -i
  3. _____ answer yes for all dependencies except Freqai
  
### Observed Results:

  * Script errors. 
  * What did you expect to happen? Script not error. 

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  Collecting xgboost==1.7.1
setup.sh: line 43:  6066 Killed                  ${PYTHON} -m pip install --upgrade -r ${REQUIREMENTS} ${REQUIREMENTS_HYPEROPT} ${REQUIREMENTS_PLOT} ${REQUIREMENTS_FREQAI}
Failed installing dependencies
  ```

**Comment by stash86** [comment]
How about you say no to all of the dependancies? Will FT be installed succesfully?s

**Comment by stash86** [comment]
From what I remember, Oracle AMD vps has low memory. In order to install freqtrade using setup.sh, I had to setup swapfile first, before running the script.

**Comment by tomjrtsmith** [comment]
That worked thankyou Stefano.

**Comment by xmatthias** [comment]
for the "low memory" VPS's (1GB and lower), i'd in general recommend using docker - which will have dependencies preinstalled.

**Comment by tomjrtsmith** [comment]
I can't seem to get SSL working with docker, which makes the prospect of
turning them into consumer bots pretty difficult. Not much else I can think
of to do with them,

**Comment by xmatthias** [comment]
i've only ever seen ssl problems on windows - where it's actually network problems (no access to the net) - not ssl problems.

**Comment by tomjrtsmith** [comment]
I've spent twice as long trying to get SSL to work than I've ever spent on
freqtrade. Every time I get it out of dummy run and try to go live it
knocks out docker and IPtables.

**Comment by stash86** [comment]
Well, what I have tried is opening the docker to the external world completely. That means you need to set strong password, and use less-popular port number. Not recommended I know, but that's how I set up my dry producer bot

**Comment by tomjrtsmith** [comment]
The road to hell is paved with middleware. I'm clinging on to hope that I
can get it organised with nginx.
