### ISSUE TITLE
The best resources

### ISSUE THREAD

**Issue by boyitnew** [freqtrade/freqtrade#7754]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

I do not know Python programming.
But because of freqtrade I am interested in learning it.
My intention is only to write and work with strategies.
Please let me know if you have a specific resource for teaching freqtrade strategy.

For example, I am going to compare the price of the previous candle with the current price, can you guide me?

**Comment by xmatthias** [comment]
We do assume that people have some basic knowledge about python - which is not a difficult language to learn, and can usually be learned in a short amount of time from some online tutorial.

you might also wanna have a look at some pandas basics - which is what freqtrade uses for operations on the data.

you might want to look at the [strategy repository](https://github.com/freqtrade/freqtrade-strategies) for inspiration on strategies.


you should also consider joining the [discord server](https://discord.gg/p7nuUNVfP7) to get support / help from the community.
People there love to help assuming the documentation has been consulted first, and some research has been done before asking a question (people don't like to google for other people).
