### ISSUE TITLE
Keep constant stoploss in custom_stoploss callback - short trading

### ISSUE THREAD

**Issue by italodamato** [freqtrade/freqtrade#7755]
## Describe your environment

  * Operating system: MacOS 13.0
  * Python Version: 3.10.8
  * CCXT version: 1.92.84
  * Freqtrade Version: 2022.11.dev-cca5a2f
  
## Your question

How can I keep the value of the stop loss in a short position constant using the custom_stoploss callback? I used to return 1 for long positions but 1 is technically a valid value for short positions so it changes my stop loss with respect to the current close value. I want it to depend only on the open rate. What value should I return?

This guide maybe should provide some clarity on it https://www.freqtrade.io/en/latest/strategy_migration/#helper-methods

**Comment by italodamato** [comment]
it seems like returning a very high, unrealistic value works

**Comment by xmatthias** [comment]
The value you return will not change depending on the trade direction - so i don't really see how migration would matter here.

The return value is the relative distance (percent) in the losing direction.

so if you return 0.1 - it'll be trailing at 10%.

**Comment by italodamato** [comment]
Yes the trick is that with long positions, returning 1 means the resulting stoploss is always invalid because it's lower than the previous value, which keeps it constant. With shorts, a 100% loss from the current rate could happen at a value that is valid in respect to the previous stoploss, hence moving it.

**Comment by xmatthias** [comment]
that's not really true - and will only happen if the prior value happened to be > 1 - which it shouldn't be.

**Comment by italodamato** [comment]
if the price moves downwards in a short position, the 100% loss from that would move down as well, which is a valid stoploss value. Let's say we enter at $100, stoploss=-0.9 ==> stoploss_rate = 100 * 1.9 = $190. Then the rate decreases to $50, the custom_stoploss callback returns 1 ==>  new stoploss_rate = 50 * 2 = $100 which is a valid stoploss hence the stoploss value is trailing behind the current rate if the function returns 1

**Comment by xmatthias** [comment]
ah yeah - i guess that's true but it's not limited, so nothing prevents a number that's a lot higher than 1

**Comment by italodamato** [comment]
Do you have a better recommendation to achieve the same result? Returning None throws an error which is unfortunate.

**Comment by stash86** [comment]
`trade.is_short` to see if the trade is long or short, then you can return 1 for long or 100 for short

**Comment by italodamato** [comment]
Thanks! I'm returning a value higher than 100 just to be on the safe side (i.e. 1e8). Also, I'm not sure returning a different value is strictly necessary as a value higher than 1 would work for long trades as well I imagine.

**Comment by xmatthias** [comment]
i honestly think that your scenario above (a 50% pricedrop) is unrealistic if you keep in mind how custom_stoploss is called - which is on every iteration (every 5 seconds by default).

if the bot was offline for a time (it shouldn't be - especially not for a short) - then this might be possible - but i still think it's a theoretical problem more than anything.

**Comment by italodamato** [comment]
Is it though? DOGE down 50% in 4 days. 
<img width="890" alt="Screenshot 2022-11-16 at 10 44 14" src="https://user-images.githubusercontent.com/45588475/202159784-0c84adf9-2850-427a-bcae-9b0c05b7863e.png">

**Comment by xmatthias** [comment]
over a period of 4 days - yes.

but not within 5 seconds - which is the default for process-throttle - and the interval at which the custom_stoploss callback will be called for open trades.

**Comment by italodamato** [comment]
my use case is to define the stoploss using the dataframe once when entering a trade, without updating it over time. I'm just saying that there's no easy way to be 100% sure that happens for short trades, while you can just return 1 for long trades to have that effect.
