### ISSUE TITLE
Global stoploss set first, then custom_stoploss

### ISSUE THREAD

**Issue by mciepluc** [freqtrade/freqtrade#7760]
## Describe your environment

  * Operating system: Does not matter
  * Python Version: Does not matter
  * CCXT version: 1.93.90
  * Freqtrade Version: 22.10
  
## Your question

It seems that after trade is open, firstly the global stoploss is set. Then, after few seconds it is updated with the custom stoploss (if it is lower). Is that correct understanding of this function? Would it be possible to set the custom stoploss faster?
Thanks

**Comment by xmatthias** [comment]
Yes that's correct  and intended. 
The [documentation](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stoploss) also points this out:

> The traditional stoploss value serves as an absolute lower level and will be instated as the initial stoploss (before this method is called for the first time for a trade), and is still mandatory.

**Comment by maciekczwa** [comment]
The option to change this behaviour would be quite useful for strategies which use different initial stoploss per pair.

Maybe we should call custom_stoploss callback when handling the initial stoploss and set lower of these two?

The handling here: https://github.com/freqtrade/freqtrade/blob/436b314c80d2dd1ac8a38a6806d71213f5540d18/freqtrade/freqtradebot.py#L1150

Could be changed to:
```
            if self.strategy.use_custom_stoploss:
                custom_stop = strategy_safe_wrapper(self.custom_stoploss, default_retval=100)(pair = trade.pair, trade = trade, current_time=datetime.now(timezone.utc),current_rate=trade.open_rate, current_profit = 0.0)
            else:
                custom_stop = 100
            stoploss = (
                self.edge.stoploss(pair=trade.pair)
                if self.edge else
                self.strategy.stoploss / trade.leverage
            )
            stoploss = min(stoploss, custom_stop)
```

**Comment by xmatthias** [comment]
that location is clearly wrong - as it's a place where it's not hit when stoploss on exchange is disabled.

In that location, changing this to `trade.stop_loss` might be correct (for different reasons), but will NOT change behavior on which stoploss is set first.

---

in current behavior - nothing prevents having different stoplosses per pair (either static or trailing - or following some other logic that's not directly trailing).
The stoploss may be set initially to the static stoploss, but will be updated within 1 iteration to the new stoploss.

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.
