### ISSUE TITLE
returned exception: "okx {"msg":"Requests too frequent.","code":"50011"}". Retrying still for 4 times.

### ISSUE THREAD

**Issue by gom7745** [freqtrade/freqtrade#7761]
## Describe your environment

  * Operating system: MacOS
  * Python Version: Python 3.8.9 (`python -V`)
  * CCXT version: ccxt==2.0.58 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2022.10 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
<img width="757" alt="Screen Shot 2022-11-18 at 6 33 51 PM" src="https://user-images.githubusercontent.com/6310423/202682643-b970e196-6f78-400f-9769-21400331aa5b.png">

The exception happens when I am downloading futures data but not for spot data.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Okx implements very tight rate limit constraints - which this is a warning about.
CCXT does respect them (https://github.com/ccxt/ccxt/issues/13883) - however it's dependent not only on settings there, but also on network connectivity, speed etc (read the issue for more details).

I've also got the suspicion that it'll depend on geographical location as well as load on their systems.

It's no problem to get this message - the "retrying for 4 times" is fine - it's only problematic should that number got to 0 - which it doesn't seem to do in your case.
