### ISSUE TITLE
About futures on Kraken

### ISSUE THREAD

**Issue by elestranobaron** [freqtrade/freqtrade#7763]
Hello, any plans about that ? Thanks ,

**Comment by xmatthias** [comment]
ccxt does not currently support kraken futures.

While there seems to be a PR for it available - it's not merged - and another PR has been pulled / removed before - which suggests that the API is not very stable (has to be a reason they remove support for something).

Feel free to reopen / re-request once it's been incorporated with ccxt, after which we can have a look at it.

**Comment by elestranobaron** [comment]
I'm just putting the link to follow it https://github.com/ccxt/ccxt/pull/11920

**Comment by xmatthias** [comment]
Then let's at least keep the right link ;)
https://github.com/ccxt/ccxt/pull/15133

**Comment by elestranobaron** [comment]
You had to know exactly the keyworkd krakenfutures sorry for that

**Comment by elestranobaron** [comment]
Up !

**Comment by xmatthias** [comment]
seems like they apply regional restrictions to futures - which are also affecting me.

therefore don't expect any progress on this anytime soon (basically unless legislation changes, or someone contributes that part - including the commitment to maintain that part going forward).

**Comment by elestranobaron** [comment]
Maybe i can let them see your comment on this

**Comment by elestranobaron** [comment]
Oh un less you talk about kraken itself

**Comment by elestranobaron** [comment]
what should i ask their support for ? for instance

regions we need to work etc ...
