### ISSUE TITLE
function for buy and holding percentage for crypto coin 

### ISSUE THREAD

**Issue by faiadtayfour** [freqtrade/freqtrade#7764]
Hi 

I wonder if can you give me function in strategy that can make option to  buy for example (5 coin crypto then sell 3 coin from it ) when sell order true

**Comment by faiadtayfour** [comment]
Hi 
I wonder if can you give me function in strategy that can make option to  buy for example (5 coin crypto then sell 3 coin from it ) when sell order true

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

You can do partial entries / exits via the [adjust_trade_position](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position) callback.

In general, i'd recommend to read through (or at least fly over) the documentation from top to bottom at least once to know the capabilities freqtrade offers.
