### ISSUE TITLE
when staking multiple unfilled entries, only the first entry gets autocancelled after entry timeout, rest doesn't get autocancelled

### ISSUE THREAD

**Issue by ShahAnuj2610** [freqtrade/freqtrade#7765]
## Describe your environment

  * Operating system: _oracle linux_
  * Python Version: _3.6.8_ (`python -V`)
  * CCXT version: _running on docker_ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __Running Freqtrade 2022.8__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

#### config
```json
{
  "position_adjustment_enable": true,
  "unfilledtimeout": {
    "entry": 30,
    "exit": 30,
    "exit_timeout_count": 0,
    "unit": "minutes"
  },
}
```

#### bug

when opening multiple positions of the same coin, all of them without getting filled

1. /forcelong BTC/USDT 10000 (does not get filled)
2. /forcelong BTC/USDT 10000 (does not get filled)
3. /forcelong BTC/USDT 10000 (does not get filled)

only the first position gets auto-cancelled after entry timeout, the rest remains open 
  
### Observed Results:

  * What happened? - only first order gets autocancelled
  * What did you expect to happen? - all unfilled orders should get cancelled

### Relevant code exceptions or logs

no error logs

**Comment by xmatthias** [comment]
The problematic behavior here is the actual creation of a 2nd order - which should not be happening (the 2nd call to forcelong should be rejected).

at this point, you cannot have more than one order open in parallel for the same pair.

**Comment by ShahAnuj2610** [comment]
But isn't this a valid use-case where you want to stake orders at multiple prices?

**Comment by xmatthias** [comment]
you can place new orders once the first order fills.
it might be a valid usecase per se - but it's not possible at the moment - and is therefore a bug.
