### ISSUE TITLE
/forcelong change from vers. 2022.6 to 2022.10

### ISSUE THREAD

**Issue by dobremha** [freqtrade/freqtrade#7767]
## Describe your environment

  * Operating system: Ubuntu 22.04 LTS
  * Python Version: 3.10.6
  * CCXT version: 2.0.58
  * Freqtrade Version: 2022.10
  * Freqtrade running in docker
  
## Your question

*Migrating from Freqtrade Version: 2022.6 to 2022.10, I have a problem with the /forcelong telegram command.
In 2022.6 "max_open_trades" parameter from config file it was not checked when using /forcelong "pair". It will simply buy the pair and add it to existing trades even if open trades >= "max_open_trades".
In 2022.10 , when using /forcelong "pair", I get "Maximum number of trades is reached" and it will NOT make the buy.

Can I override somehow forcelong function in my strategy file to ignore "max_open_trades" parameter ? Or other method by which I get old 2022.6 behavior back ?

Thanks,
Mikel

**Comment by xmatthias** [comment]
No. the ignoring of the `max_open_trades` parameter in the RPC section was a bug that was fixed.

forced open trades count towards the max_open_trades parameter - and that's how it was intended from the getgo.
There will be no override - as `max_open_trades` is a very important parameter when using dynamic stake/compounding. - ignoring this parameter would lead to problems / errors in the calculation of the new stake.

You can read the original bug report here: https://github.com/freqtrade/freqtrade/issues/7489
