### ISSUE TITLE
Backtest vs dryrun difference

### ISSUE THREAD

**Issue by schmip** [freqtrade/freqtrade#7768]
Operating system: Windows Server 2016
Python Version: Python 3.8.3
CCXT version: I did try thi, but could not get a result when entered pip freeze (there was no ccxt on the list)
Freqtrade Version: 2022-08
  
I did run some backtesting and hyperopting on 4h candle strategies. I did use following options for hyperopt and backtesting to make sure I sue 1 minute details on top of the 4h data. 
               "--timeframe-detail", 
               "1m", 

I had the 1m and 4h data on downloaded from Binance. My entry was at 97.9% price of the previous closed 4h candle. I did run the dryrun trading and also backtested the same period afterwards. I face the following issue. The strategy I used purchased BONDUSDT based on the closed candle of 2022-11-12 8pm. It bought on 4.283 at 2022-11-13 00:06. In the dryrun mode it could not sell for more than 4 days. BUT the backtest results said that it could sell at 4.337 rate. I did manually check it and see that the price never went up to 4.337 after 2022-11-13 00:06. How could it that the backtest says that it could sell (we had 1m timedetail used in the backtest).

I did try to find similar case here, but could not. Thank you!

Thank you for your help in advance.
Peter

**Comment by stash86** [comment]
Assuming you meant 2022-11-12 8 PM UTC, I believe it went up to 4.8 at one point
![FFBFFB99-78DF-4856-823C-E3F3A82126BE](https://user-images.githubusercontent.com/13656154/202898973-907237e6-a5b6-40f8-b287-f61b11261859.png)
Even the red candle after that have high of 4.381.

So, not sure which chart are you looking at, unless the time you give isn't on UTC, at which please provide the timezone

**Comment by stash86** [comment]
Btw, it could be also a bug with how freqtrade look at custom proce currently. Currently, timeframe details only affect exits. There is an open PR to make it look at custom entry as well. So it might solve the issue

**Comment by stash86** [comment]
In case you want to help test it

https://github.com/freqtrade/freqtrade/pull/7707

**Comment by xmatthias** [comment]
we continually fix bugs / problems. 
Please try to recreate your (backtest) results with the latest version (2022.10) (which will probably succeed).

The most likely cause here is a missconception on how orders fill in backtesting.
in the current version - backtesting will assume an entry order filled immediately if the price is within the low/high range.
This means, your backtest order is placed at :00 - and will also fill at :00 (even though 1m price reaches your level later).

It then starts to check for exits - which might happen at 00:06 (by which your live order wasn't filled yet).

#7707 aims to fix this - but is not merged as it still needs some more tests. I'd be curious to know your experience with it - and how it will influence this trade (as it seems to be the perfect example for this).

**Comment by schmip** [comment]
> Btw, it could be also a bug with how freqtrade look at custom proce currently. Currently, timeframe details only affect exits. There is an open PR to make it look at custom entry as well. So it might solve the issue

> we continually fix bugs / problems. Please try to recreate your (backtest) results with the latest version (2022.10) (which will probably succeed).
> 
> The most likely cause here is a missconception on how orders fill in backtesting. in the current version - backtesting will assume an entry order filled immediately if the price is within the low/high range. This means, your backtest order is placed at :00 - and will also fill at :00 (even though 1m price reaches your level later).
> 
> It then starts to check for exits - which might happen at 00:06 (by which your live order wasn't filled yet).
> 
> #7707 aims to fix this - but is not merged as it still needs some more tests. I'd be curious to know your experience with it - and how it will influence this trade (as it seems to be the perfect example for this).

Thank you very much for your help to both of you! It seems that my price was max 4.291 at 00:06 (which is 01:06 in my screenshot) and it never went up to 4.33. I am happy to join into the testing, but not sure what's the best way for this. I have several 4h strategies and I feel that most of them seem to be working nice in hyperopt and backtesting, but not in real life.  
<img width="1182" alt="Screenshot 2022-11-20 at 13 19 19 copy" src="https://user-images.githubusercontent.com/35523152/202901668-a8f91675-e993-43cf-b57f-7564320cccfe.png">

What is strange to me is that I never see 1 minute data in the bactest result file (json converted to xlsx) but always the 4h candle times. Is it normal or can it happen that I did something wrong with my backtest setup? 
[backtest-result-2022-11-20_10-42-41.xlsx](https://github.com/freqtrade/freqtrade/files/10049653/backtest-result-2022-11-20_10-42-41.xlsx)

Thank you.
Peter

**Comment by xmatthias** [comment]
As mentioned above - your signal is from :00 - so your open rate will be "accepted" as "filled immediately as long as it's within the low/high range (which yours clearly is, see below).

![image](https://user-images.githubusercontent.com/5024695/202978571-8872e3c2-bcca-4446-a53f-8af3613b2976.png)

It'll then start to process the 1m timeframe to check for exits (assuming there's no log warnings about missing data, or whatnot) - and will determine an "immediate" close date (you're encountering an edge case where Trailing-stop triggers within the first candle - which makes it fill at "high - stoploss".

The 1m candle confirms this happening - so it adjusts the stoploss on the :00 candle and fills 1 or 2 candles later

![image](https://user-images.githubusercontent.com/5024695/202979744-692b8256-9cc8-4520-bb89-8ede5f25c1f0.png)

best give this backtest a try with https://github.com/freqtrade/freqtrade/pull/7707, which is most likely fixing this.

**Comment by schmip** [comment]
Thank you very much Matthias. Is my understanding correct that I just need to manually (backup and then) override the 3 files mentioned here and run the backtest? https://github.com/freqtrade/freqtrade/pull/7707/files

Thank you!

**Comment by xmatthias** [comment]
You're not using docker - 
so you've probably followed one of the regular installation guides (Not using docker).
This means, the best way is probably to run `git checkout bt/full_detail`.

Please note that this assumes you're at current develop - and have current develop dependencies installed.
If you're not - best run `pip install -r requirements.txt` first - to ensure dependencies are uptodate.

**Comment by schmip** [comment]
Hi Matthias. Thank you for your feedback. I was trying to install it and pretty sure that I do something wrong, but I get this error when try to update. What do I do wrong? 
![image](https://user-images.githubusercontent.com/35523152/203404392-90bfb4f6-d8eb-4f9f-baac-da1834931730.png)


Thank you!

**Comment by xmatthias** [comment]
can you try `git fetch`  first?
if it doesn't work - please the output of `git remote -v` (to see what the upstream is you're at).

**Comment by schmip** [comment]
It worked. Thank you. I've got this. Should I validate somehow if my setup update was correct?
![image](https://user-images.githubusercontent.com/35523152/203406776-d6c04130-eb83-4cbc-83aa-dee0177a5ce1.png)

**Comment by xmatthias** [comment]
After fetch, you should be able to run the checkout command from above.

**Comment by schmip** [comment]
Sorry for not answering earlier. We've got sick in the past 10 days. I am back and did test the changes and see different results in my backtests so I hope it will work from now. Using this version on all instances now. Thank you.

**Comment by xmatthias** [comment]
well in the meantime, it's been merged to develop - so i guess you should be fine with that version anyway.
