### ISSUE TITLE
jsonschema.exceptions.ValidationError: 'timeframe' is a required property

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#7770]
## Describe your environment

  * Operating system: ____MacOS
  * Python Version: _____ (`python -V`) 3.10.4
  * CCXT version: _____ (`pip freeze | grep ccxt`) 2.1.75
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker) 2022.11.dev-12b471c64
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered* 

Running Freqai from my laptop instead of docker, says "timerframe is a required property" however Freqai timeframes are entered in config.json

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
The message is not talking about freqAI `include_timeframes` - but about the base level `timeframe` (the main timeframe your bot is running on).

That's mandatory, and can be set in either strategy or configuration (or via --timeframe as command line argument).

The freqAI example strategy is a bit of an exception in this case - as it's the only sample strategy that doesn't define this as strategy property.

**Comment by tomjrtsmith** [comment]
I tried setting "timeframe": "5m", in config.json but that didn't help. Its
not the example strategy but I can't find a direct reference to "timeframe"
in any of the strategies other than self.config ["timeframe"] which is in
all of them.

**Comment by tomjrtsmith** [comment]
Sorry, forgot to save file its working now.
