### ISSUE TITLE
Is it possible to manage multiple bots on the same server with one FreqUI?

### ISSUE THREAD

**Issue by yul** [freqtrade/freqtrade#7784]
## Describe your environment

  * Operating system: Linux Ubuntu
  * Python Version: 3.10.6
  * CCXT version: 2.1.54
  * Freqtrade Version: docker-2022.11.dev-7147f52e
  
## Your question

I have two bots on the same server, using docker and I want to manage them in one FreqUI (e.g. bot1's). For bot2 I copied config of bot1, so they have the same secrets and tokens (not sure if this is required).

I mapped bot1 to port 8080, bot2 to 8081 with docker-compose.yaml.
Then I am using nginx to reverse proxy 8080 to port 80 and 8081 to port 81 so they can be used from outside. I mapped bot2 to check that it works, I was planning to use bot1's FreqUI to manage both.

I can access both bots via external_ip:80 and external_ip:81 from outside and see their FreqUIs separately.

However, I cannot add bot2 to bot1's FreqUI to manage it, if I try to add external_ip:81 to bot on external_ip:80 (or vise-versa), I just get error "API Url required" and suggestion to check ping URL (which works fine) and CORS documentation, which mentions that
> This whole section is only necessary in cross-origin cases (where you multiple bot API's running on localhost:8081, localhost:8082, ...), and want to combine them into one FreqUI instance.

Which is exactly what I need, however it doesn't mention what else I need to do to achieve that.

I've tried putting

```CORS_origins: ["http://external_ip:80", "http://external_ip:81"]```

in config.json for both bots, then I tried to put 
```CORS_origins: ["http://external_ip:80"]```
to first bot and 
```CORS_origins: ["http://external_ip:81"]```
to second bot.
and vise-versa.
But neither config works. 
Is that even possible? 
What should I put to CORS_origins in bot1 and bot2 config.json to be able to add bot2 to bot1's FreqUI?

**Comment by xmatthias** [comment]
first off - we clearly don't recommend to have the freqtrade API available directly via the internet.

We recommend some tunnel (vpn, ssh tunnel, ...) to connect your server before accessing the UI.
It's obviously your server/bots, so we can only recommend in this case.

your case is complicated by the use of nginx - which double-maps the ports - if i understood this correctly as follows:
<externalIP>:80 -> localhost:8080 -> dockerinternal:80
<externalIP>:81 -> localhost:8081 -> dockerinternal:81

in the end, that's not really relevant anyway.
what really counts is (as the [documentation](https://www.freqtrade.io/en/stable/rest-api/#cors) mentions) - the URL you see in your browser's address bar.
that URL will not be `http://external_ip:80` - but `http://external_ip` (without port, as 80 is the default).

**Comment by yul** [comment]
Huh, removing :80 from url actually worked, thanks. While 80 port is default, I didn't expect that adding it would break things, since this is a ligitimate part of URL and I didn't know port is not required in case bot runs on non-standard port.

**Comment by xmatthias** [comment]
the key part is not "legitimate" port or not.
it's the browser that determines "cross origin url" - which is everything in the url bar of the browser up to the first (but excluding) `/` .
all browsers i use remove :80 and :443 - so the correct url becomes the one without `:80`.
