### ISSUE TITLE
Trade profit is always -0.25% when entering a position 

### ISSUE THREAD

**Issue by fronty77** [freqtrade/freqtrade#7785]
## Describe your environment

  * Operating system: __Ubuntu 22__
  * Python Version: ___3.11__ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

This is happening when I run /status table on telegram I should see 0.00% or a reasonable number. Is this a bug or should I change something in the configuration ??

**Comment by xmatthias** [comment]
Neither - this is intended as is, reflecting reality of trading.
if you were to buy 1 BTC at 15.000$ - and immediately sell this 1 BTC at 15.000$ - then your result will not be 0 (no profit, no loss) - but you will have lost ~0.2% in fees (assuming a 0.1% fee for buying, and the same for selling). You'll therefore not get 15.000$ out - but 14.970$ (you paid 30$ in fees). 

Freqtrade does account for this - in dry-run based on the fee the exchange reports as "lowest/worst tier" - and in real mode based on the fees paid for the entry - assumed the same fees apply also for the trade exit.
Special offers like 0 fee trading for certain pairs is accounted for in live trading - but usually not in dry-run trading, as that information is not available via API.
