### ISSUE TITLE
Hyperopt results/export feature enhancement request

### ISSUE THREAD

**Issue by vuvuzelka** [freqtrade/freqtrade#7789]
Hyperopt is a great tool and I would like to be able to see/export some additional values from epochs (for comparison/filter purposes), such as:

- **leverage value** (I am hyperopting leverage value) but am unable to see it in the results (it is there in the csv export tho)
- **win/loss ratio** (right now it shows number of trades won/lost, but not the ratio (so I have to use calculator manually for interesting epochs). For some reason this data (number of win/loss trades) is **not there in the csv export** either. Ideally this should be a separate column value
- **stoploss** value (best hyperopt results tend to use longest stoploss available, which does not show the whole picture) - should be a separate column value (is present in csv export)
- **number of longs/shorts trades** (and their ratio ideally)

Ideally I would like to see these values in the table format of hyperopt-list results, and/or in the csv export

![image](https://user-images.githubusercontent.com/12335988/203466011-21bde313-d007-454e-bb6a-c105096b5148.png)

Thank you, really appreciate this tool!

**Comment by xmatthias** [comment]
The hyperopt table is already too wide, and is wrapping on way too many screens - so adding additional columns is out of the question.

As a consequence, adding additional data will not be possible without removing other things - however all information is somewhat useful / important - therefore i currently don't see us doing any change to this table.

the only 2 values i can imagine to be added if we find something else we can remove is long/short trades and win/loss ratio.
For the moment, i'd not know what column can be removed though - but i'm obviously open for suggestions.


Hyperoptable values (like leverage, stoploss, ...) are wrong in this table for sure, and only relevant to a very small amount of people (if you're actually hyperopting leverage). 
They'll therefore for sure not be included in this table. Why would stoploss be in this table, while your buy/sell features are not.

---

All values are in the .fthypt - and can be viewed with `hyperopt-show`  (as a full backtest report) individually.

export-csv for hyperopt is really pointless - and something we should consider removing.

If you think it's necessary / useful and needs improvement, you're absolutely welcome to submit a PR adding additional columns to the csv file.

**Comment by vuvuzelka** [comment]
I appreciate your explanation and agree that extra columns won't look good. 
I will be happy to use csv export (with leverage, win-loss ration, stoploss columns instead) which I think is quite useful (as at a glance you can see the dynamics in trades considering these parameters across epochs.

Personally I'd swap "Draw" column (between win n loss) for their ratio, as generally there are no "draws", at least in my tests

I do use hyperopt-show to see full details, but it is only limited to 1 at a time (after running say 500 epochs I want to compare the top 20-50, after filtering them out with commands to pick the most interesting ones for dry/live runs, taking into account ratio, long/short, leverage, stoploss values which can dramatically alter the actual results in real life in a live market)

Only just learning python so I'm afraid no PR incoming from me for now... I would also appreciate any specific easy-to-understand content for me to learn from about this topic, then perhaps I can do that PR :)

**Comment by xmatthias** [comment]
long/short and win/loss ratio can be added (the first only to the csv file, the other to the output, too).

all other values are either part of the space - or (in case of leverage) - a value that can be different per pair / trade (depending on whatever values). 
if you hyperopt that - you'll get 1 value out (depending how you do it multiple) - but it'll not be conclusive / generally applicable.
