### ISSUE TITLE
How to use hyperopt for future trading ? 

### ISSUE THREAD

**Issue by VietnameseRick** [freqtrade/freqtrade#7793]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.10 (`python -V`)
  * CCXT version: 2.1.96 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2022.9.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
Hi, I am currently writing a hyperopt strategy but I am stuck at 
`if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
                'enter_long'] = 1`

My strategies depends on Indicator for entry and roi for exit
I understand that both `enter_long` and `enter_short` must be included in `populate_entry_trend` but from the code example (https://www.freqtrade.io/en/stable/hyperopt/#optimizing-an-indicator-parameter) already reduce lambda function for `enter_long`, how do I write `enter_short` ? 

Also, are there any way to get the high/low of previous candle to prevent the bot from jumping into close price of candles with huge body ? 

Furthermore, how to prevent the bot from trading on weekend / holidays ? 

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by VietnameseRick** [comment]
I tried with 
```
long_conditions = []
short_conditions = []
long_conditions.append(qtpylib.crossed_above(
            dataframe['close'], dataframe[f'ema_{self.ema_timeperiod.value}']
        ))
long_conditions.append(dataframe['volume'] > 0)

short_conditions.append(qtpylib.crossed_below(
            dataframe['close'], dataframe[f'ema_{self.ema_timeperiod.value}']
))

short_conditions.append(dataframe['volume'] > 0)

if long_conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, long_conditions),
                'enter_long'] = 1

if short_conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, short_conditions),
                'enter_short'] = 1
```

But I wonder if it would work correctly 🤔

**Comment by xmatthias** [comment]
it's just lists you're combining into **and** combined conditions.
you can use one list - 2 lists - i've seen more than that, too.

you can also not use the List approach at all, but do the logic in the `dataframe.loc` call as the sample strategy demonstrates.

https://github.com/freqtrade/freqtrade/blob/c963fd720b01e111f46e1c7fb136bcb9e5621f75/freqtrade/templates/sample_strategy.py#L353-L371

It's just python / pandas code - it's the endresult that counts (your columns need to be assigned correctly - and the dataframe must be returned).

**Comment by VietnameseRick** [comment]
``

> it's just lists you're combining into **and** combined conditions. you can use one list - 2 lists - i've seen more than that, too.
> 
> you can also not use the List approach at all, but do the logic in the `dataframe.loc` call as the sample strategy demonstrates.
> 
> https://github.com/freqtrade/freqtrade/blob/c963fd720b01e111f46e1c7fb136bcb9e5621f75/freqtrade/templates/sample_strategy.py#L353-L371
> 
> It's just python / pandas code - it's the endresult that counts (your columns need to be assigned correctly - and the dataframe must be returned).

Ah i see, so the List condition is not really necessary nor important but the `enter_long` and `enter_short` of the dataframe are which freqtrade hyperopt process. Thanks 👍

**Comment by xmatthias** [comment]
yeah it's just helpers to assist with the logic - not things that are necesary.
