### ISSUE TITLE
Heikin Ashi candles OHLC QTPyLib

### ISSUE THREAD

**Issue by Arivadis** [freqtrade/freqtrade#7796]
Hi,

I've read this - https://github.com/freqtrade/technical/issues/152 and this https://github.com/freqtrade/technical/pull/154.
As i get - this could make Heikin Ashi works like on Tradingview. How can i update this?

I compare OHLC in freqtrade Heikin Ashi chart and ohlc QTPyLib calculates. Does this use different lib/data/anything else?
These do not much at all. How can i call Heikin Ashi that use Freqtrade on its chart?

**Comment by Arivadis** [comment]
I mean - it has really different values.
freqtrade calculates      ha_open 16270.067308  ...  ha_low 16609.550
UI shows                       ha_open 16408.15               ha_low 16450.0

**Comment by xmatthias** [comment]
frequi's haikin Ashi and the ones calculated by qtpylib have been aligned a few months ago, based on the assumption that the qtpylib one is correct (it is, comparing the formula to investopedia).

The only doubtful point is the first candle - which can be calculated in several ways - as that's not "really" properly defined iirc.

**Comment by Arivadis** [comment]
Have a look.
o 16270.067308  h 16800.000000  l 16270.067308  c 16609.550
![photo_5190789438794482872_y](https://user-images.githubusercontent.com/105313584/204052818-20c315a9-aeea-41c0-9982-2956d2a3164f.jpg)

**Comment by Arivadis** [comment]
As i got - it is only about UI.
qtpylib calculates good(for 99.999%)

**Comment by xmatthias** [comment]
I'm not sure what you're trying to show above - with an unclear screenshot without any comment other than "have a look".

**Comment by Arivadis** [comment]
Sorry, my bad.


I use qtpylib for calculating heikin Ashi candles.
So It is working fine.

But later i compared freqtrade chart UI with qtpylib for Heiking Ashi plot.

This is qtpylib calculation Heikin Ashi for 1day timeframe 2022-11-11 BTC/USDT pair:
ha_open 17713.415365  ha_high 17713.415365  ha_low 16343.000000  ha_close 17166.825
This is the same candle and pair i took from UI chart 
ha_open 16746.5 ha_high 17678.0 ha_low 16343.0 close 17166,825

This candle must be red and with no upper wick.

But here it is.


Could you check please?

Thank You!

**Comment by Arivadis** [comment]
![photo_5192842312902885811_w](https://user-images.githubusercontent.com/105313584/204100909-4ff51bff-9628-466c-b71c-30c37e7bb05c.jpg)

**Comment by xmatthias** [comment]
Your image shows nothing that would allow us to compare heikinashi candles calculated in the frontend with the backend (the backend columns are not shown).


Using a very simple strategy snippet

``` python
# ...
        heikinashi = qtpylib.heikinashi(dataframe)
        dataframe['ha_open'] = heikinashi['open']
        dataframe['ha_close'] = heikinashi['close']
        dataframe['ha_high'] = heikinashi['high']
        dataframe['ha_low'] = heikinashi['low']
```

and then configuring plotting properly - it's clearly visible that heikin ashi candles align 100% with the open/close calculated in the backend (i've removed the high/low comparisons as they clutter the picture quite some).


![image](https://user-images.githubusercontent.com/5024695/204140542-a9260bfc-2671-4d44-89e2-ad76eef7697d.png)

If you think that's not the case, please do a similar comparison than the one i did above.
if you're not using docker - please make sure to update to the latest UI version before attempting (and provide the UI version you're using).

**Comment by Arivadis** [comment]
Seems i had the old UI. Now it is just fine

You were right, as every time.

**Comment by xmatthias** [comment]
> You were right, **as every time**.

I'd never claim that ... :) Glad it's working for you now.
