### ISSUE TITLE
Downloading non-exchange data, say from an API

### ISSUE THREAD

**Issue by dclipca** [freqtrade/freqtrade#7797]
Is there a way to download data that is not-OHLCV candles at the specified exchange? Say I want to add weather data along the OHCLV data. How can I do this?

**Comment by xmatthias** [comment]
I doubt any exchange will provide weather data :laughing: 

At any rate - freqtrade strategies are pure python - so you can basically use whatever you can express in python.

To be able to properly backtest this (maybe you don't need this - then skip this section) - you'll have to implement two paths - one to load historic data (which you'll have to make sure is properly dated, and has been available at the time of the date) - and one for uptodate data.
you'll then merge both into the freqtrade dataframe (again, careful to not produce forward-looking backtests).

**Comment by dclipca** [comment]
> I doubt any exchange will provide weather data 😆
> 
> At any rate - freqtrade strategies are pure python - so you can basically use whatever you can express in python.
> 
> To be able to properly backtest this (maybe you don't need this - then skip this section) - you'll have to implement two paths - one to load historic data (which you'll have to make sure is properly dated, and has been available at the time of the date) - and one for uptodate data. you'll then merge both into the freqtrade dataframe (again, careful to not produce forward-looking backtests).

I didn't mean I would fetch it from an exchange though. My bad.
Yes, I want to backtest the strategy with that fetched non-OHCLV data included but in a freqtrade-native way. That is, in a similar way freqtrade would download OHLCV data every time it is needed according to the strategy timeframe, both in backtest and live. Are there any code examples of doing that? Thank you very much for your input.

**Comment by xmatthias** [comment]
Not really - and there is no "native" way for this.
Every non-exchange datasource is different. The main point is that you'll get the data as a timeseries (data points with regular timestamps).
you'll then have to mangle that data into something that roughly fits your timeframe.

**Comment by dclipca** [comment]
> Not really - and there is no "native" way for this. Every non-exchange datasource is different. The main point is that you'll get the data as a timeseries (data points with regular timestamps). you'll then have to mangle that data into something that roughly fits your timeframe.

I see. This makes sense. Are there any code samples I can check out? I can't find in the docs how freqtrade makes sure data is downloaded, what functions/callbacks are responsible for this and so on.

**Comment by robcaulk** [comment]
> > Not really - and there is no "native" way for this. Every non-exchange datasource is different. The main point is that you'll get the data as a timeseries (data points with regular timestamps). you'll then have to mangle that data into something that roughly fits your timeframe.
> 
> I see. This makes sense. Are there any code samples I can check out? I can't find in the docs how freqtrade makes sure data is downloaded, what functions/callbacks are responsible for this and so on.

There are a couple guys in the FreqAI discord who are doing this with fear and greed index/yahoo s&p 500 stuff:

https://discord.gg/9zJGRQDS

It is more straightforward than you might imagine.

**Comment by dclipca** [comment]
> > > Not really - and there is no "native" way for this. Every non-exchange datasource is different. The main point is that you'll get the data as a timeseries (data points with regular timestamps). you'll then have to mangle that data into something that roughly fits your timeframe.
> > 
> > 
> > I see. This makes sense. Are there any code samples I can check out? I can't find in the docs how freqtrade makes sure data is downloaded, what functions/callbacks are responsible for this and so on.
> 
> There are a couple guys in the FreqAI discord who are doing this with fear and greed index/yahoo s&p 500 stuff:
> 
> https://discord.gg/9zJGRQDS
> 
> It is more straightforward than you might imagine.

Joined the server. Thank you. Will ask people in there.
