### ISSUE TITLE
Trailing (or custom) stop loss pessimism in backtest

### ISSUE THREAD

**Issue by mciepluc** [freqtrade/freqtrade#7800]
## Describe the enhancement

My understanding of current implementation of trailing / custom stop loss is the following. Only *high* and *low* values of the candle are considered. It means, that always when candle span between high and low is higher than trailing stop loss distance, the stop loss will be executed. It is OK, but it is a pesimistic assumption. 
It would be useful to have an option to enable "optimistic" stop loss, so the one that is called when comparing candle *open* with *low* (or *high* for short). It is not going to cover pessimistic scenarios, but for some strategies analysis it is going to be more relevant.

Example:
- entered the long trade, trailing stop loss is set to 1%
- price is increasing with each next candle
- there appears a candle at which price increases by 2%
- pessimistic stop loss will be always executed at this candle
- optimistic stop loss will not be executed if candle *low* is not 1% below candle *open*

I know that partial solution for it is using a detailed-timeframe, but having such option would be beneficial in my opinion.

**Comment by xmatthias** [comment]
even a green candle with a open/close diff of 2% could go from 
open to high, to low, to close - triggering the stoploss just as well (which would make the above option an unrealistic one).

You simply can't know.

You can use `--timeframe-detail 1m`  to get a more realistic view of what happens within the candle, and it'll be rare to find a 2% 1m candle (they happen for sure - but if you expect to remain in such a trade, then your trailing stop was too tight anyway).

I don't see us maintaining an alternative mode for this for multiple reasons
* more maintenance effort for very questionable gains
* makes it unclear with what logic a strategy result was archived (thinking about shared backtest results)
* Will allow you to game yourself (assuming a user doesn't fully understand the implication of this feature - he'll pick this as "this makes me more money" ...).

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.
