### ISSUE TITLE
use order book

### ISSUE THREAD

**Issue by boyitnew** [freqtrade/freqtrade#7803]
Hello
Are these two configurations different?

------------
config 1:
"entry_pricing": {
"price_side": "other",
"use_order_book": true,
}

------------

config 2:
"entry_pricing": {
"price_side": "other",
"use_order_book": false,
}

-------------
Because I considered 5 test bots for my strategy, one of them used the second config, and only that bot had a different entry price.

Four bots with this entry :

-------------
Kucoin (dry): Long GGG/USDT (#5)
Enter Tag: force_entry
Amount: 17368.25630000
Open Rate: 0.09000000
Current Rate: 0.09000000
Total: (1563.143 USDT, 1564.706 USD)

-----------

Different bot with this entry:

----------------
Kucoin (dry): Long GGG/USDT (#1)
Enter Tag: force_entry
Amount: 23094.68820000
Open Rate: 0.04550000
Current Rate: 0.04330000
Total: (1050.808 USDT, 1051.859 USD)

------------

Shouldn't "same" be used for the second configuration?

**Comment by xmatthias** [comment]
Why would it? 
`"price_side": "other",` is set for both configs.

use_order_book determines which endpoint on the exchange is used - and i'd recommend to use the orderbook - as that's usually the faster way to get pricing rates.

**Comment by boyitnew** [comment]
tnx
I plan to place an order 5% below the current price when I use the forcelong order.
That's why I went to custom_entry_price.
But since I am a beginner, I could not do it

Can you help me ?

```
def custom_entry_price(self, pair: str, entry_tag: Optional[str], current_time: 'datetime', proposed_rate: float, side: str, **kwargs) -> float:
	if (entry_tag == 'force_entry'):
            new_entryprice = dataframe['last_price'] * 0.95
            return new_entryprice
```

**Comment by xmatthias** [comment]
i assume your problem is the usage of `last_price` - which is not a regular dataframe column.
so unless you actually populate this column beforehand - it'll not be available.

Instead - you can use `proposed_rate` - which will be the current rate on the exchange based on pricing (unless the force_entry specified an explicit rate, then it's that rate).

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.
