### ISSUE TITLE
Summarizing the trades

### ISSUE THREAD

**Issue by zoknoteplus** [freqtrade/freqtrade#7825]
## Describe your environment

  * Operating system: ____Linux
  * Python Version: _____ 3.9(`python -V`)
  * CCXT version: _____ 2.1.9(`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ 2022.11(`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
Is there a way to show summarizing results of trades. I'd like to make custom exit on some profit. So idea is when you get some % total profit with open and closed trades, you close all trades.
Thanks.
*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
you can use `/profit` via telegram for this.
The UI will also show you similar results in the "general" tab.

**Comment by zoknoteplus** [comment]
Yes i know that but i want to use it automatically. Is it possible via custom_exit in strategy?

**Comment by xmatthias** [comment]
well you can use the [trade query](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-trades) to somehow summarize profits.
rpc methods are not available to the strategy - and it's really made for reporting only.

setting an overall profit target is not really something that makes sense if you think about it. If it's going well, you'll usually keep it running - nobody will argue against more profits.
Now stopping a losing bot  is a different topic - and can be done via protections - although that won't force you out of any trades.

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.
