### ISSUE TITLE
Adding fees makes agent profitable in RL's BaseEnvironment 

### ISSUE THREAD

**Issue by mrzdev** [freqtrade/freqtrade#7829]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: Python 3.9.15
  * CCXT version: ccxt==1.95.2
  * Freqtrade Version: freqtrade 2022.12.dev-3c322bf7d

## Describe the problem:

I noticed something fishy going on while trying to set the fee in the config to 0.005 and training my agent with MaskablePPO. Trade duration is 0-1 all the time and the agent becomes very profitable. This made me suspect the fee calculation is the cause of this.  For longs in the `get_unrealized_profit` method of `BaseEnvironment` this is the calculation for example:

```py
current_price = 1 * (1 + 0.005) 
last_trade_price = 1 / (1 + 0.005)
print((current_price - last_trade_price) / last_trade_price)
#result of this actually equals: 0.010024999999999758
```

### Steps to reproduce:

  1. Set the fee in config to 0.005
  2. Run the Base5ActionRLEnv basic example strategy
  3. Check the results of the `get_unrealized_profit` calls in the reward and then check the config with the fee set to 0.0
  
### Observed Results:

  * What happened?
  The total_profit becomes unrealistically high, fees skyrocket the profit.
  * What did you expect to happen?
  The agent is punished instead of rewarded with fees.

### Relevant code exceptions or logs
This is the info of the last env.step (I train in the jupyter notebook):

  ```
{'tick': 2346, 'action': array(4), 'total_reward': 190043.2034635906, 'total_profit': 14445.964005378966, 'position': 0.5, 'trade_duration': 0, 'current_profit_pct': 0.0, 'episode': {'r': 190043.203464, 'l': 1946, 't': 9175.401548}}
  ```

**Comment by xmatthias** [comment]
> I train in the jupyter notebook

which "the jupyter notebook" ? I don't think we provide a freqAI notebook (though it might be an interesting addition ...)
As this seems to be a good way to "quickly" test this - are you able to share a (working) notebook or similar - so we don't have to waste time trying to replicate your testcase?

**Comment by robcaulk** [comment]
You are right, I’m not sure why we reversed the fees. Looking at the history they were reversed toward the end of the PR for some reason, by me…i guess this was a response to some comment in the PR suggesting the fees were incorrect originally - but in fact, they were originally correct.

I’ll revert that commit asap. Thanks for reporting this.

**Comment by mrzdev** [comment]
Yeah, exactly, I was just preparing the minimal reproduction and saw it is indeed reversed. After fixing, it looked correct because episodes were terminated fast with a max drawdown during training set to 0.02. Thanks for looking into that too! Since it's acknowledged I think we can close so that I don't waste your time with some irrelevant stuff to install in that notebook of mine.
