### ISSUE TITLE
Restart FreqAI with RL model from sb3_contrib

### ISSUE THREAD

**Issue by hlasco** [freqtrade/freqtrade#7832]
## Describe your environment

  * Operating system: MacOS
  * Python Version: 3.9.15
  * CCXT version: None
  * Freqtrade Version: docker-2022.12.dev-3c322bf7

## Describe the problem:

I noticed that restarting Freqtrate with an existing RL model from sb3_contrib will return an error.

### Steps to reproduce:

  1. Run Freqtrade in trading mode using RL agent with `RecurrentPPO` policy and `MlpLstmPolicy` network
  2. Stop freqtrade after training
  3. Restart Freqtrade with the same config
  
### Observed Results:

  * What happened ? The `FreqaiDataDrawer` tried to reload the pre-trained policy from the `stable_baselines3` lib
  * What did you expect to happen? The `FreqaiDataDrawer` should reload the pre-trained policy / networks from the `sb3_contrib` or `stable_baselines3` lib

### Relevant code exceptions or logs

  ```
...
freqtrade    |   File "/freqtrade/freqtrade/freqai/data_drawer.py", line 574, in load_data
freqtrade    |     MODELCLASS = getattr(mod, self.freqai_info['rl_config']['model_type'])
freqtrade    | AttributeError: module 'stable_baselines3' has no attribute 'RecurrentPPO'
  ```

**Comment by xmatthias** [comment]
Can you please provide the full exception (as well as logs from startup up to that point).

**Comment by robcaulk** [comment]
That’s a nice find, thank you. Looks like @aemr3 has it covered for you :-)
