### ISSUE TITLE
'Invalid machine command' after updating Freqtrade

### ISSUE THREAD

**Issue by Qwertzi01** [freqtrade/freqtrade#7839]
## Describe your environment

  * Operating system: Debian 11
  * Python Version: 3.9.2
  * CCXT version: 1.91.29
  * Freqtrade Version: 2022.7

## Describe the problem:

After updating Freqtrade to latest version 2022.11 (with setup script, also tried manual with git pull etc)
I get a 'Invalid machine command' failure if I try to use Freqtrade. _Note: 'stable' branch is used_

### Steps to reproduce:

  1.) ./setup.sh --update
  2.) source .env/bin/activate
  3.) freqtrade install-ui
  
### Observed Results:

  * What happened?
  * Invalid machine command failure when trying to use Freqtrade

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
...  
Building wheels for collected packages: freqtrade
  Building editable for freqtrade (pyproject.toml) ... done
  Created wheel for freqtrade: filename=freqtrade-2022.11-0.editable-py3-none-any.whl size=20071 sha256=986a4db3092ea70867eeb4e79f09e6c1a20944b17632ca271a92a8cd0311237f
  Stored in directory: /tmp/pip-ephem-wheel-cache-zsfleiw6/wheels/76/01/e7/9425d60eac220c9a79cb9e70605769942143ba4c6bd9bf738a
Successfully built freqtrade
Installing collected packages: freqtrade
Successfully installed freqtrade-2022.11
(.env) tradingbot@server:~/freqtrade$ freqtrade install-ui
Invalid machine command
(.env) tradingbot@server:~/freqtrade$ freqtrade
Invalid machine command
  ```

**Comment by xmatthias** [comment]
is that full / unmodified output? (without missing lines in between) ? 

It seems odd because that would be missing the environment activation - so i'll assume for now that you've omitted that (as well as some other, regular output).

You might also want to try to disable the environment - and then reenable it.
If that doesn't help - what does `pip show freqtrade` output?

**Comment by Qwertzi01** [comment]
> is that full / unmodified output? (without missing lines in between) ?

No, I shortened the output a little. However, venv is activated. I tried also a fresh install, nothing changed.


> If that doesn't help - what does pip show freqtrade output?

```
(.env) tradingbot@server:~/freqtrade$ pip show freqtrade
Name: freqtrade
Version: 2022.7
Summary: Freqtrade - Crypto Trading Bot
Home-page: https://github.com/freqtrade/freqtrade
Author: Freqtrade Team
Author-email: freqtrade@protonmail.com
License: GPLv3
Location: /home/tradingbot/freqtrade/.env/lib/python3.9/site-packages
Requires: aiofiles, arrow, blosc, cachetools, ccxt, colorama, fastapi, jinja2, jsonschema, numpy, orjson, pandas, pandas-ta, prompt-toolkit, psutil, py-find-1st, pycoingecko, pyjwt, python-rapidjson, python-telegram-bot, questionary, requests, schedule, sdnotify, SQLAlchemy, TA-Lib, tables, tabulate, technical, urllib3, uvicorn
Required-by:
(.env) tradingbot@server:~/freqtrade$
```

**Comment by Qwertzi01** [comment]
> is that full / unmodified output? (without missing lines in between) ?

No, I shortened the output a little. However, venv is activated. I tried also a fresh install, nothing changed.


> If that doesn't help - what does pip show freqtrade output?

```
(.env) tradingbot@server:~/freqtrade$ pip show freqtrade
Name: freqtrade
Version: 2022.11
Summary: Freqtrade - Crypto Trading Bot
Home-page: https://github.com/freqtrade/freqtrade
Author: Freqtrade Team
Author-email: freqtrade@protonmail.com
License: GPLv3
Location: /home/tradingbot/freqtrade/.env/lib/python3.9/site-packages
Requires: aiofiles, arrow, blosc, cachetools, ccxt, colorama, fastapi, janus, jinja2, joblib, jsonschema, numpy, orjson, pandas, pandas-ta, prompt-toolkit, psutil, py-find-1st, pyarrow, pycoingecko, pydantic, pyjwt, python-rapidjson, python-telegram-bot, questionary, requests, schedule, sdnotify, SQLAlchemy, TA-Lib, tables, tabulate, technical, urllib3, uvicorn, websockets
Required-by:
(.env) tradingbot@server:~/freqtrade$
```

**Comment by xmatthias** [comment]
what does `which freqtrade` output?

**Comment by Qwertzi01** [comment]
```
(.env) tradingbot@server:~/freqtrade$ which freqtrade
/home/tradingbot/freqtrade/.env/bin/freqtrade
(.env) tradingbot@server:~/freqtrade$
```

**Comment by xmatthias** [comment]
independent of the branch (stable / develop) - i can install freqtrade with the install script on a debian 11 system just fine.

I suspect it's somehow related to your system (searching for this particular output gives basically 0 useful information...).
what's the output of the following commands:
`uname -a`
`cat /etc/os-release`
(with activated venv):
` python3 --version`
`python3 -m freqtrade -V`

**Comment by Qwertzi01** [comment]
That are not good news ... strange thing is I can reinstall and use Freqtrade up to version 2022.7 without any problems.
All newer versions results in the same error (by the way - I translated it from non-eng console output, maybe different in english).

> uname -a

`Linux server 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux`

> cat /etc/os-release

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

> python3 --version

`Python 3.9.2`

> python3 -m freqtrade -V

`Invalid machine command`

But I looked now also in the **kernel log** and found this messages which are logged if I try to start Freqtrade:

`Dec  3 17:01:08 server kernel: [617405.716600] traps: freqtrade[584823] trap invalid opcode ip:7f848859ae22 sp:7ffee55e2750 error:0 in libarrow.so.1000[7f84884a2000+189e000]`

**Comment by xmatthias** [comment]
that sounds like you've hit some incompatibility with pyarrow.

with activated virtual environment - can you run `python3` - and then (within the console):

```
import pyarrow
pyarrow.__version__
```

Based on the error above - that should fail - at which point, you're best off with pyarrow support - as it seems you hit some incompatibility with their wheel.

**Comment by Qwertzi01** [comment]
Yes, it fail ... with `import pyarrow`

```
(.env) tradingbot@server:~/freqtrade$ python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
Invalid machine command
```

But how do you know if libarrow.so have a problem with pyarrow or vice versa!?

**Comment by xmatthias** [comment]
Libarrow is the c dependency of pyarrow.

I suspect / hope their support channels have more commands to investigate what went wrong with that install.

**Comment by Qwertzi01** [comment]
Ok, is there a fix/workaround so I can use newer Freqtrade versions?

**Comment by xmatthias** [comment]
Please look in the pyarrow support channels for help on your installation problem. They're the experts on this.

From afar (from what i've seen so far), it seems like they have a problem / limitation with the wheel they provide.
i can't however assist further as it's not happening to me / on my systems.

**Comment by Qwertzi01** [comment]
It turns out, that Arrow requires POPCNT which is part of SSE4; My Intel D2700 has that extension not. SSE3 yes, but not SSE4.

**Comment by xmatthias** [comment]
Technically, freqtrade core does not hard-depend on pyarrow, so you should be able to use freqtrade without it (you cannot use dataformats feather or parquet).

you should be able to remove pyarrow from a finished install (`pip uninstall pyarrow`) to use freqtrade without this dependency.

FreqAI may depend on this (either now or in the future) - but on an old CPU, it's questionable if you'll be able to use these methods efficiently anyway.

Hope this helps

**Comment by Qwertzi01** [comment]
Thank you for your help. Got managed it to run latest version (core) with your hint of uninstalling pyarrow at the end.

**Comment by TheoBrigitte** [comment]
## Environment

- Operating system: Debian 11
- Python Version: 3.9.2
- CCXT version: 2.7.45
- Freqtrade Version: [e8dc3dd59](https://github.com/freqtrade/freqtrade/commits/e8dc3dd59a86716400d70c7d3a37c2afa5a49631)

## Problem

I recently faced the same problem.

After installing freqtrade on a Intel Atom N2800 (sse3: yes, sse4: no), I hit the same error :
```
kernel: traps: freqtrade[82537] trap invalid opcode ip:7ff60499aec8 sp:7ffdc5fda410 error:0 in libarrow.so.1100[7ff60488e000+18d3000]
```
This was fixed by uninstalling pyarrow with `.env/bin/pip uninstall pyarrow`

## Suggestion

As more people might hit the same issue, I think it might be worth mentioning this issue somewhere, or just linking this issue in the requirements.txt

**Comment by xmatthias** [comment]
i don't consider "once every quarter" to be worth of extra mentioning. If it becomes more frequent - sure - but otherwise i feel this issue is sufficient (it's an easy find through github search).

it's pretty edge-case, and will only happen on outdated CPU's.

**Comment by TheoBrigitte** [comment]
Ok fine then
