### ISSUE TITLE
Multiple bots with containers/instances 

### ISSUE THREAD

**Issue by Arivadis** [freqtrade/freqtrade#7844]
Hi, 

I used to run Freqtrade installed on Linux mashine.
But if want to run multiple bots with docker there are 2 ways -

1. Put different(or the same) .yml images in different folders, create 2 containers and run each of them. So they will be separeted.
2. Append to the main .yml data from second .yml and run as 2 instances as one container. If I down it - both will be stopped.(https://www.freqtrade.io/en/stable/advanced-setup/)

Am i right?

**Comment by xmatthias** [comment]
yes that's correct.

in the 2nd case, you'll have to make sure you're using different names for things (as the doc you linked yourself includes).
you can however stop individual bots (`docker-compose stop <servicename>` ) to only stop one bot.

personally, i use one compose-file per host - otherwise it can become messy with ports very quickly.

**Comment by Arivadis** [comment]
Can i make changes in strategy if i stopped one of them?
If docker unblock files to edit - than seems good.

But anyway, if i need to add new one bot, I should stop container to edit .yml?

**Comment by xmatthias** [comment]
docker will not block any files.
you can also add new services, and simply run `docker-compose up -d` again, and it'll stop the new service (assuming no changes were done to the existing services).

**Comment by Arivadis** [comment]
Hi, 

I've run in docker on Ubuntu according to the plan with 2 bots in one .yml, but getting this:



2022-12-03 23:21:36 freqtrade.exceptions.OperationalException: Config file "/ft_userdata/user_data/config2.json" not found! Please create a config file or check whether it exists.
![Screenshot from 2022-12-03 23-27-21](https://user-images.githubusercontent.com/105313584/205464674-5d7642da-4d6d-43f5-8caf-6625d1e9ca2b.png)
But here it is.

I have no such a problem when i used docker on windows.
Have no idea why does not it see configuration files. 
The same problem for both containers

Probably i should configure something else or i forget to put path somewhere else?

**Comment by xmatthias** [comment]
most likely, your mounts are somewhat wrong.

please provide the content of your compose file - as well as the output of the `tree` command, ran in the directory the docker-compose file is in.

**Comment by Arivadis** [comment]
```
freqtrade.exceptions.OperationalException: Config file "/freqtrade/user_data/yml_HA_51/user_data/config_Heikin_Ashi1D51.json" not found! Please create a config file or check whether it exists.
root@cs-freqtrade-dev:~/freqtrade/user_data/yml_HA_51# cd ..
root@cs-freqtrade-dev:~/freqtrade/user_data# ls -l
total 588
-rw-r--r-- 1 freqtrade freqtrade   3187 Dec  9 18:16 Heikin_Ashi1D51.json
-rw-r--r-- 1 root      root        3187 Dec  9 18:17 Heikin_Ashi1D511.json
-rw-r--r-- 1 root      root        3187 Dec  9 18:17 Heikin_Ashi1D512.json
drwxr-xr-x 2 freqtrade freqtrade   4096 Nov  8 23:11 backtest_results
-rw-r--r-- 1 freqtrade freqtrade   2423 Oct 31 10:56 config-bt.json
-rw-r--r-- 1 freqtrade freqtrade   2407 Nov 21 10:27 config-ne.json
-rw-r--r-- 1 freqtrade freqtrade   2406 Oct 31 08:48 config-nt.json
-rw-r--r-- 1 freqtrade freqtrade   2428 Nov 21 16:05 config.json
-rw-r--r-- 1 root      root        3187 Dec  9 18:38 config_Heikin_Ashi1D51.json
-rw-r--r-- 1 root      root        3187 Dec  9 18:38 config_Heikin_Ashi1D511.json
-rw-r--r-- 1 root      root        3187 Dec  9 18:39 config_Heikin_Ashi1D512.json
-rw-r--r-- 1 freqtrade freqtrade   2428 Nov 21 16:05 config_ne.json
drwxr-xr-x 3 freqtrade freqtrade   4096 Nov  8 21:40 data
drwxr-xr-x 2 freqtrade freqtrade   4096 Nov  8 21:40 freqaimodels
drwxr-xr-x 2 freqtrade freqtrade   4096 Oct 13 18:33 hyperopt_results
drwxr-xr-x 2 freqtrade freqtrade   4096 Oct 13 18:33 hyperopts
drwxr-xr-x 2 freqtrade freqtrade   4096 Dec  9 18:25 logs
drwxr-xr-x 2 freqtrade freqtrade   4096 Oct 13 18:33 notebooks
drwxr-xr-x 2 freqtrade freqtrade   4096 Nov  8 23:11 plot
drwxr-xr-x 2 freqtrade freqtrade   4096 Dec  8 18:23 strategies
-rw-r--r-- 1 freqtrade freqtrade  57344 Nov 21 10:20 tradesv3-ne.sqlite
-rw-r--r-- 1 freqtrade freqtrade 307200 Dec  9 15:02 tradesv3.sqlite
-rw-r--r-- 1 freqtrade freqtrade 106496 Dec  8 13:24 tradesv3_ne.sqlite
-rw-r--r-- 1 freqtrade freqtrade  32768 Dec  9 15:59 tradesv3_ne.sqlite-shm
-rw-r--r-- 1 freqtrade freqtrade      0 Dec  9 15:59 tradesv3_ne.sqlite-wal
drwxr-xr-x 4 freqtrade freqtrade   4096 Dec  9 19:08 yml_HA_51
root@cs-freqtrade-dev:~/freqtrade/user_data# cd ..
root@cs-freqtrade-dev:~/freqtrade# nano docker-compose.yml 
root@cs-freqtrade-dev:~/freqtrade# cd userdata
-bash: cd: userdata: No such file or directory
root@cs-freqtrade-dev:~/freqtrade# cd user_data
root@cs-freqtrade-dev:~/freqtrade/user_data# cd yml_HA_51/
```

```
root@cs-freqtrade-dev:~/freqtrade/user_data/yml_HA_51# tree
.
├── docker-compose.yml
├── logs
│   ├── freqtrade51.log
│   ├── freqtrade511.log
│   └── freqtrade512.log
└── user_data
    ├── config_Heikin_Ashi1D51.json
    ├── config_Heikin_Ashi1D511.json
    └── config_Heikin_Ashi1D512.json

2 directories, 7 files
root@cs-freqtrade-dev:~/freqtrade/user_data/yml_HA_51# 
```

docker file
```
version: '3'
services:
  freqtrade_51:
#    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade_51
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:8090:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/yml_HA_51/freqtrade51.log
      --db-url sqlite:////freqtrade/user_data/tradesv51.sqlite
      --config /freqtrade/user_data/yml_HA_51/user_data/config_Heikin_Ashi1D51.json
      --strategy Heikin_Ashi1D51
  freqtrade_51LONG_ONLY:
    #    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade51LONG_ONLY
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:8091:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/yml_HA_51/freqtrade51.log
      --db-url sqlite:////freqtrade/user_data/tradesv51_long.sqlite
      --config /freqtrade/user_data/yml_HA_51/user_data/config_Heikin_Ashi1D511.json
      --strategy Heikin_Ashi1D51LONG_ONLY
  freqtrade_51SHORT_ONLY:
    #    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade51SHORT_ONLY
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:8092:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/yml_HA_51/freqtrade51.log
      --db-url sqlite:////freqtrade/user_data/tradesv51_short.sqlite
      --config /freqtrade/user_data/yml_HA_51/user_data/config_Heikin_Ashi1D512.json
      --strategy Heikin_Ashi1D51SHORT_ONLY
```

**Comment by Arivadis** [comment]
if i put /root/ to its path - getting access denied

**Comment by Arivadis** [comment]
I found this -https://github.com/freqtrade/freqtrade/issues/3318
So the problem was - volumes:- "./user_data:/freqtrade/user_data", i suppose in .yml file.


Now this does not see strategy class:
Impossible to load Strategy 'Heikin_Ashi1D51'. This class does not exist or contains Python code errors.
I've just tried to run it on my installed freqtrade - it is working without exceptions.
![Screenshot from 2022-12-09 23-24-30](https://user-images.githubusercontent.com/105313584/206805450-e79c33e3-871f-463b-bed4-4b8cc41d1963.png)
Seems this is also cant find files in userdir, or Idn.
file:///home/arivadis/ft_userdata/user_data/strategies/Heikin_Ashi1D51.py

If it works with installed freqtrade but not with docker - seems still getting problem with docker.
I do not think it is because of imported modules, but send you strategy file to make sure it is not in it.


Here is full exception
freqtrade51               | 2022-12-09 22:12:17,973 - freqtrade.worker - INFO - Starting worker docker-2022.12.dev-1da8ad69
freqtrade51               | 2022-12-09 22:12:17,973 - freqtrade.configuration.load_config - INFO - Using config: /ft_userdata/user_data/Heikin_Ashi1D51.json ...
freqtrade51               | 2022-12-09 22:12:17,975 - freqtrade.loggers - INFO - Verbosity set to 0
freqtrade51               | 2022-12-09 22:12:17,976 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
freqtrade51               | 2022-12-09 22:12:17,977 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
freqtrade51               | 2022-12-09 22:12:17,978 - freqtrade.configuration.configuration - INFO - Dry run is enabled
freqtrade51               | 2022-12-09 22:12:17,979 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////ft_userdata/user_data/tradesv51.sqlite"
freqtrade51               | 2022-12-09 22:12:17,979 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
freqtrade51               | 2022-12-09 22:12:17,988 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
freqtrade51               | 2022-12-09 22:12:17,989 - freqtrade.configuration.directory_operations - INFO - Created data directory: None
freqtrade51               | 2022-12-09 22:12:17,990 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
freqtrade51               | 2022-12-09 22:12:17,991 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
freqtrade51               | 2022-12-09 22:12:18,001 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
freqtrade51               | 2022-12-09 22:12:18,002 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
freqtrade51               | 2022-12-09 22:12:18,003 - freqtrade.commands.trade_commands - ERROR - Impossible to load Strategy 'Heikin_Ashi1D51'. This class does not exist or contains Python code errors.
freqtrade51               | 2022-12-09 22:12:18,004 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade51               | Traceback (most recent call last):
freqtrade51               |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade51               |     worker = Worker(args)
freqtrade51               |   File "/freqtrade/freqtrade/worker.py", line 37, in __init__
freqtrade51               |     self._init(False)
freqtrade51               |   File "/freqtrade/freqtrade/worker.py", line 53, in _init
freqtrade51               |     self.freqtrade = FreqtradeBot(self._config)
freqtrade51               |   File "/freqtrade/freqtrade/freqtradebot.py", line 62, in __init__
freqtrade51               |     self.strategy: IStrategy = StrategyResolver.load_strategy(self.config)
freqtrade51               |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 48, in load_strategy
freqtrade51               |     strategy: IStrategy = StrategyResolver._load_strategy(
freqtrade51               |   File "/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 267, in _load_strategy
freqtrade51               |     raise OperationalException(
freqtrade51               | freqtrade.exceptions.OperationalException: Impossible to load Strategy 'Heikin_Ashi1D51'. This class does not exist or contains Python code errors.

**Comment by Arivadis** [comment]
file:///home/arivadis/Desktop/Upwork%20+%20Fiverr/Freqtrade_Heikin_Ashi(20.11.2022)/1/Heikin_Ashi1D51.py

**Comment by Arivadis** [comment]
[strategy.txt](https://github.com/freqtrade/freqtrade/files/10198556/strategy.txt)

**Comment by xmatthias** [comment]
` --config /freqtrade/user_data/yml_HA_51/user_data/config_Heikin_Ashi1D51.json` is clearly wrong.
your mount is `- "./user_data:/freqtrade/user_data"` - which means that:

`user_data` is available at `/freqtrade/user_data` within the container.

if you change that to `--config user_data/config_Heikin_Ashi1D51.json` it will find the configuration file.

---

your "tree" output doesn't show any strategy - so based on the above output - that's expected.
I don't think the content is the problem - but the location of the file.

Assuming you don't change the mount points - then the container will see anything that's within your host's `user_data/`   level (relative to the docker-compose file).
Since there is not even a strategy folder (based on the tree output from above) - there will be no strategy available to the bot - you'll therefore need to move the strategy to `user_data/strategies` (where it belongs).

there's other options (like changing your mounts) - but if you're unfamiliar with that i'd clearly advise against that.

**Comment by Arivadis** [comment]
I forget this way, i've push all bots in the main .yml, bot is working.

Thank You
