### ISSUE TITLE
Bot Comparison Partially Hidden on the Freqtrade UI Dashboard

### ISSUE THREAD

**Issue by kcyarn** [freqtrade/freqtrade#7845]
## Describe your environment

  * Operating system: Ubuntu Ubuntu 22.04.1 LTS 64-bit
  * Browser: Firefox 107.0
  * Python Version: Python 3.10.6
  * CCXT version: 2.2.45
  * Freqtrade UI Version: 0.5.0
  
 ## Describe the problem:
  
 The bot comparison card is too large for the given space, causing half the card to slide underneath the Profit Distribution graph. This occurs in both Firefox and Chrome.
  
 ### Steps to reproduce:
  
 Run Freqtrade with the UI enabled on a 1920 x 1080 display and navigate to the dashboard.
  
 ### Relevant code exceptions or logs
  
As this is a css layout issue, the following code is pulled from inspect element in the web browser. Freqtrade itself did not throw any errors.
  
 This is the Bot Comparison div.
  
 ```
  <div data-v-d8a6cc52="" class="vue-grid-item cssTransforms" style="transform: translate3d(5px, 5px, 0px); width: 1222px; height: 325px; position: absolute;">
 ```
  
I don't know what the CSS standard is for Freqtrade. This "fix" is likely not suitable for production use, but it's what works to view the entire element in my browser.

```
<div data-v-d8a6cc52="" class="vue-grid-item cssTransforms" style="transform: translate3d(10px, 5px, 0px); width: 33%; height: 325px; position: absolute; left: 33%;">
```
  
I shrunk the width and changed it to percentage, added 5px to the left transform, and shifted the element to left by the same amount as the width.

Please see [https://github.com/kcyarn/Freqtrade_Issue](https://github.com/kcyarn/Freqtrade_Issue) for screenshots. Due to their width, you'll need to right click and open them in a new tab.

**Comment by xmatthias** [comment]
your layout is customized (you can drag the boxes around at will).

The following is the default layout, which works just fine.

![image](https://user-images.githubusercontent.com/5024695/205456521-1ff4825a-eb88-4842-8dae-154bc7325191.png)

You can return to the default layout by using the "reset layout" button at the top right - behind the "FT" button.
