### ISSUE TITLE
Adjusting amount to trade.amount as it is higher with adjust_trade_position

### ISSUE THREAD

**Issue by rg687** [freqtrade/freqtrade#7846]
version freqtrade 2022.10 with binance futures in dry mode

i opened an eth short worth 1000$
Trade(id=1, pair=ETH/USDT, amount=0.78700000, is_short=True, leverage=1.0, open_rate=1269.43000000, open_since=2022-12-03 18:49:36)

then I want to add 1000$ (with self.stake_amount in adjust_trade_position) to the short but i have this message in the logs
2022-12-03 22:50:23,224 - freqtrade.freqtradebot - INFO - Adjusting amount to trade.amount as it is higher. 0.788 > 0.787
2022-12-03 22:50:23,224 - freqtrade.freqtradebot - INFO - Remaining amount of 0.0 would be smaller than the minimum of 7.5
and none of the trade happen

it seems eth has been going slightly down (current_rate=1268.15) so i would take a larger position than the one I opened with? is there a reason i cant keep adding 1000$ to the short?

Thanks

**Comment by xmatthias** [comment]
>  Remaining amount of 0.0 would be smaller than the minimum of 7.5

This message will only appear with negative adjustments - so you're trying to reduce your position by 1000$ - which will result in an (almost 0$) position (lower than what you are able to trade on binance).

If you want to **increase** your position - your return from the callback must be positive - negative adjustments will be treated as reduction.

**Comment by rg687** [comment]
perfect thanks
