### ISSUE TITLE
Is roi only set based on minutes?

### ISSUE THREAD

**Issue by boyitnew** [freqtrade/freqtrade#7848]
Is roi only set based on minutes? Or can it be set based on seconds?

**Comment by xmatthias** [comment]
it's in minutes.

seconds would imply that we could guarantee "to the second" execution, which we can't (network / strategy delays can get in the way of this).
so setting something to "30s" can mean anything between 30s to 35s (for example).

If you need different logic - please use the [custom exit signal callback](https://www.freqtrade.io/en/latest/strategy-callbacks/#custom-exit-signal) - which is called once per iteration (~every 5 seconds per default).

**Comment by boyitnew** [comment]
excellent
What variable can I use to get the exact elapsed time since entering?

if current_profit > 0.2:
----  if elapsed_time < 5s:
-------  return 'elapsed_time_5s'

**Comment by xmatthias** [comment]
i guess what you're looking for is `trade.open_date_utc` - from which you can calculate the difference off of.
