### ISSUE TITLE
Produce image from plot

### ISSUE THREAD

**Issue by moooaaazzz** [freqtrade/freqtrade#7863]
Hello,

I am trying to generate an image along with an html file for plotting. Therefore, I am providing the arguments to plot function as shown in the screenshot below. However, that does produce any image. Any help would be appreciated.  Thanks!

![image](https://user-images.githubusercontent.com/114662506/205846123-b2ed8f3a-14c2-470f-b473-cae0a4c952ec.png)

**Comment by moooaaazzz** [comment]
Hi, changing auto_open to True makes it work. Thanks!

**Comment by xmatthias** [comment]
`auto_open` is just opening the file for you. leaving that as false will store the file - but you'll have to open it yourself.

**Comment by moooaaazzz** [comment]
Thanks xmatthias, but if I don't open the html file in browser by setting it to true, it does not download the image file.

**Comment by xmatthias** [comment]
well "download" depends - it's stored in `user_data/plots` by default.
if that's in a docker container (or someplace else) - then sure, it'll not be downloaded.
