### ISSUE TITLE
Specifying a path to a 2nd/3rd config file from a config file

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#7864]
## Describe your environment

  * Operating system: ____Ubuntu 22.04
  * Python Version: _____ (`python -V`) 3.10.4
  * CCXT version: _____ (`pip freeze | grep ccxt`) ccxt==2.1.96
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker) freqtrade 2022.12.dev-320535a22
  
## Your question

I tried specifying a path to a 2nd config file from the main config file with no success. I couldn't find the right format in the docs, what I did and got an error was as follows. 

"add_config_files": "/path/to/config2.json",

That got an error so, I wondered if there was a command to specify a path?

**Comment by xmatthias** [comment]
there's 2 ways to specify multiple configs (both with slightly different behavior).

`add_config_files` is the method in the configuration - which assumes that the config specified is in a relative location to the "parent" config. you can therefore for example use `["./config2.json", "config3.json", "../configoutside.json"]` - which all would load - assuming the last config one level higher.
This doesn't support absolute paths - but i'm not sure it should be - as a freqtrade user-data directory should be seen as something that can be "Moved around" with ease - which absolute paths would prevent / break.

alternatively, you can specify multiple `--config` paths. These can be relative paths (relative to the current location) - or absolute paths.

the first method will assume a "parent/child" relationship between the configurations (childs can't override parent settings if they are already defined).
`--config` assumes all as equal - where the specified key would win. 
this is equivalent to a minimal configuration that ONLY specifies `add_config_files`  - where again the last one would win as they are all on the same level.
e.g.:

``` json
{
"add_config_files": [
    "config1.json",
    "config-private.json"
]
}
```

**Comment by tomjrtsmith** [comment]
Thanks! I tried it with an absolute path which would have been the problem I think.
