### ISSUE TITLE
Data update error | Binance: Way too much request weight used

### ISSUE THREAD

**Issue by OleksandrMyronchuk** [freqtrade/freqtrade#7865]
* CCXT version: 2.0.58
* Freqtrade Version: freqtrade 2022.10

Every time when I try to update data for backtesting I get the following message: _{"code":-1003,"msg":"Way too much request weight used; IP banned until 1670409655566. Please use the websocket for live updates to avoid bans."}_

This is the command I use to update the data
`freqtrade download-data --exchange binance --pairs .*/BUSD --timeframes 1m 5m 15m 30m 1h 2h 4h 6h 12h 1d --days 730`

My question is, can I connect to the socket as written in this message from Binance? (If so, how to do it?)
Or can I set a request limit so I don't get banned for updates?

The error is _“freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair GHST/BUSD due to ExchangeNotAvailable. Message: binance GET https://api.binance.com/api/v3/klines?interval=15m&limit=1000&symbol=GHSTBUSD&startTime=0 403 Forbidden <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">”_

**Comment by xmatthias** [comment]
The error-message binance provides is wrong / missleading. 
websockets work for live updates - though you're trying to download historic data - which is NOT available through websockets.


Based on the error - you're most likely using a custom exchange configuration which disables the builtin ccxt `rateLimit`.
CCXT defaults are usually fine and work as expected - though they CAN be disabled - which would cause the above error.

Freqtrade will load any file that's named `config.json` in either your current directory, or in `user_data/config.json`.

We have a recommendation for binance (see the sample config for biannce) - which can also be generated with `freqtrade create-config --config user_data/config.json`  - while selecting binance as exchange.

**Comment by froggleston** [comment]
The docs also cover the setting of rate limits for exchanges: https://www.freqtrade.io/en/stable/exchanges/#setting-rate-limits
