### ISSUE TITLE
How to place a stop-limit or stop-market order?

### ISSUE THREAD

**Issue by glowwormX** [freqtrade/freqtrade#7869]
## Describe your environment

  * Operating system: macos12.3
  * Python Version: 3.10.6
  * CCXT version: 1.92.52
  * Freqtrade Version: 2022.8
  
## Your question
If the current price is 18000 and it will continue to rise beyond 18500 according to indicators, how can I place a stop-limit or stop-market order? I've read the relevant callback functions, such as custom_stoploss() custom_entry_price() and custom_exit_price(), but they don't seem to meet my needs.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

you can place a stoploss on exchange via [configuration](https://www.freqtrade.io/en/stable/stoploss/#stop-loss-on-exchangefreqtrade).
this will work identically for both longs or shorts.
the availability of stop-limit or stop-market orders will depend on exchange support.

`custom_stoploss()` (or static stoploss configurations) will define the price the stop is placed - and in case of stop-limit `stoploss_on_exchange_limit_ratio` will define how much distance will be between the stop and the limit order.

**Comment by glowwormX** [comment]
Sorry, I already filled it in. Because just now I think my problem has nothing to do with my system environment.

I also think stoss or custom_stoploss will solve the problem of closing orders, but it probably won't open orders. In the above example, I want to open a long position after 18500.

**Comment by xmatthias** [comment]
Entries happen as limit or market order, not as advanced orders.
