### ISSUE TITLE
Export backtest analysis to csv

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#7870]
## Describe your environment

  * Operating system: Linux mint Una
  * Python Version: 3.10.4
  * CCXT version: 2.0.96
  * Freqtrade Version: 2022.11.dev-2c1330a4e
  
## Your question

How do we export backtesting analysis to csv file with command `freqtrade backtesting-analysis`? I would like to have my exit-reasons and indicators in a spreadsheet.

Thanks in advance

**Comment by froggleston** [comment]
You can copy paste from the terminal and ctrl-shift V to paste special into a spreadsheet.

If you want to wait a little longer, I've got a PR in progress that will add `--analysis-to-csv`: https://github.com/freqtrade/freqtrade/pull/7861

**Comment by moinonin** [comment]
OK, I see the PR has not passed some tests. I will be waiting to try this.

**Comment by froggleston** [comment]
> OK, I see the PR has not passed some tests. I will be waiting to try this.

There's nothing failing in the code itself. The failed test is an intermittent build issue.

**Comment by moinonin** [comment]
Alright. My apologies. I probably wait for the build so I can try with develop_plot docker image

**Comment by froggleston** [comment]
Nice!
