### ISSUE TITLE
Ichimoku indicator usage

### ISSUE THREAD

**Issue by Sniitch** [freqtrade/freqtrade#7872]
Hey,

Question: How do I use the ichimoku indicator as declared here https://github.com/freqtrade/technical/blob/57ee5d001b922b883fb2fea8aa29101faf6cb037/technical/indicators.py#L670-L706 ?

What my imports looks like:

```
import numpy as np
import pandas as pd
from pandas import DataFrame
from datetime import datetime
from typing import Optional, Union

from freqtrade.strategy import (BooleanParameter, CategoricalParameter, DecimalParameter,
                                IntParameter, IStrategy, merge_informative_pair)

import talib.abstract as ta
import pandas_ta as pta
from technical import qtpylib
from technical import indicators

```
What my code looks like:

```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe['tenkan'] = ta.ichimoku['tenkan_sen']
        dataframe['kijun'] = ta.ichimoku['kijun_sen']
        dataframe['senkou_a'] = ta.ichimoku['senkou_span_a']
        dataframe['senkou_b'] = ta.ichimoku['senkou_span_b']
        dataframe['cloud_green'] = ta.ichimoku['cloud_green']
        dataframe['cloud_red'] = ta.ichimoku['cloud_red']

```
When I try backtesting my strategy, I get the following error: _AttributeError: module 'talib.abstract' has no attribute 'ichimoku'_

I just started using freqtrade so I may have missed something but I looked for hours before posting here.

Thanks for help

**Comment by xmatthias** [comment]
you're looking at "technical" code - and your import for technical is `from technical import indicators` - so it's most likely `indicators.ichimoku()`.

your code won't work however - as it's returning a dict - not single dataframes.

Instead - you can use the following:

``` python
from technical.indicators import ichimoku
# ...        
        ichi = ichimoku(dataframe)
        dataframe['tenkan'] = ichi['tenkan_sen']
        dataframe['kijun'] = ichi['kijun_sen']
        dataframe['senkou_a'] = ichi['senkou_span_a']
        dataframe['senkou_b'] = ichi['senkou_span_b']
        dataframe['cloud_green'] = ichi['cloud_green']
        dataframe['cloud_red'] = ichi['cloud_red']

```

You shouldn't use `chikou_span` for anything other than visualization - as it's a forward-looking line (displaced by 26 candles by default)  and would taint your backtset results.
