### ISSUE TITLE
Invalid Profit Calculated For Short Orders

### ISSUE THREAD

**Issue by mohsenjavidpanah** [freqtrade/freqtrade#7874]
## Environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.10.6
  * CCXT version: 1.93.3
  * Freqtrade Version: 2022.12.dev-1da8ad69d
  
## Problem:

I used Freqtrade by custom stoploss(that is dynamic and change by conditions) and adjustment positions, I ran my strategy as dry-run, chart show me success short order but Freqtrade show me negative profit.

![Screenshot from 2022-12-08 18-57-13](https://user-images.githubusercontent.com/28291175/206569875-8dc547b5-d9f6-4dae-8b68-5d18a06b4e78.png)

![Screenshot from 2022-12-08 18-57-22](https://user-images.githubusercontent.com/28291175/206569904-3ad0cdd0-f248-45c4-bc45-77f89dbcc4f2.png)

**Comment by xmatthias** [comment]
well this trade is clearly not profitable (not once you account for fees).

you can do the math pretty easily yourself  purely looking at USD values (cost).

doing a (rough) calculation below:

your entry are for 4376.81$ (0.26 * 16833.9).
exit for 2185.976 and 2186.99 (0.13 * 16815.2 and 0.13 * 16823 respectively).

2185.976 + 2186.99 = 4372.966 - which is ~3$ below your actual cost (so your gain is 3$).
you'll however need to divide this by 10 (you used a leverage of 10) - so you're now 3$ / 10 = 0.3$ (still profit).
there's however still 1.09$ in fees - which will draw you down into negatives (0.3$ - 1.09$ - 1.09$).

Now this calculation is slightly simplified (correctly, leverage is applied at each step, as well as fees) - but it's clearly a losing trade - even though it would've been profitable if you'd not be paying fees.

---

we can obviously look at the details if you think it's wrong - but from the above, rough estimate, i would seem like the trade was losing more than the above.

For that, please provide the output of the following command:

`freqtrade show-trades --db-url sqlite:///<trades.sqlite> --print-json --trade-ids <tradeid>`

**Comment by mohsenjavidpanah** [comment]
Hi @xmatthias
Why Binance calculator show me different/profitable result?

https://www.binance.com/en/futures/BTCUSDT_PERPETUAL/calculator

**Comment by xmatthias** [comment]
Binance calculator is ignoring fees.

each order will have a [fee](https://www.binance.com/en/fee/futureFee) - depending on the order type and market - which the calculator is simply ignoring (which is misleading in my opinion - but i'm sure it's better for profit of binance this way).

you can easily see this by using round numbers (even if they're not related to the actual price) in the calculator (see below).

![image](https://user-images.githubusercontent.com/5024695/206853277-e1236081-18c0-4d70-b34d-ca6e0d4679ed.png)

In reality - your profit in such a round case will not be 10% - but it'll be 9.xx% - as each order will deduct fees from your balance.

Freqtrade on the other hand aims to show you reality. 
We don't benefit from you trading by hiding fees from you - but from you being successful with the bot (we don't directly profit unless you decide to sponsor - but having a happy user is better than a user that felt cheated)

**Comment by mohsenjavidpanah** [comment]
Thank you very much @xmatthias for your product, and your road

This is correct that this calculator not subtract exchanges fee from received profit, but in the while not divide profit to the leverage.

Suppose exchange fee is 0.05% for every transaction, that in this order I have 3 transaction 0.05 * 3 = 0.15%
and order gain 1.11% non-pure profit, then I have 1.11 - 0.15 = 0.96% pure profit.

Also in formula you considered 4376.81as investment value but the value is smaller and is ~ 437.68

My friend did a order and gave profit by smallest change in price and this is also is positive

![photo1670662498](https://user-images.githubusercontent.com/28291175/206855126-e8f4448a-bf53-4931-a9b5-f8fadc6d70c9.jpeg)

**Comment by xmatthias** [comment]
> Also in formula you considered 4376.81as investment value but the value is smaller and is ~ 437.68

as i mentioned above - the formula is simplified - and only extracts leverage at the end.
your leverage is 10x - so 437.68 * 10 ~= 4376.81.

You can also assume amount as "0.26 / 10" and do the same calculation - you'll notice that it will not change.

you can obviously remove leverage immediately - but the fact that this will not turn into a green result will remain.

---

Posting unrelated profit screenshots will not help any (this is unrelated as it's from a different exchange, as well as using different price - while not stating any amounts).

**Comment by mohsenjavidpanah** [comment]
Thank you very much @xmatthias, I do more investigation and I know Freqtrade work perfect and fine
