### ISSUE TITLE
Long and short compute order opportunity lead to long/short trades imbalance ?

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#7876]
Hi,

When i backtest a strategy i got the feeling that the long opportunity is compute first then the short (not sure at what level) witch can lead to imbalance in long/short trades ratio (and long will be dominant and limit hedge/neutral capability) ?

Here with 5 trades open at the same time :
Long / Short                | 4782 / 1475 (0,76%)

Here with 50 trades open at the same time :
Long / Short                | 5923 / 4987 (0,54%)

Have a nice day.

**Comment by moinonin** [comment]
The long opportunity will definitely be computed first if it comes before the short opportunity in the strategy file. The real question is do you have overlapping signals that are true for both short and long trades? IMO this is likely the case. If you want overlap-prove strategy, you will have to test the combined strategy, note how many shorts and longs were executed within the backtesting period, then run with "canShort" option disabled, and then with this option enabled but with all "enter_long" tags commented. Now the count of shorts + longs (in the separated tests) should = The total number of trades (in the combined strategy). In addition, the shorts and the longs in the combined strategy should each equal to their counterparts in the separated strategy. This is a NOT so easy to achieve pattern for a good strategy but give it a shot. Of course a "good" strategy is subjective here. For me a good strategy is a positively consistent one. I rather have a strategy that returns a positive value of profit everyday however small it is, than one that make big losses and big profits when directions change. To achieve this, I calculated the coefficient of variability on daily profits for the entire backtesting period and aim at bringing it to unity (1).

**Comment by xmatthias** [comment]
freqtrade does not judge the order of "long or short" - both are treated equally (assuming you're in futures markets), and evaluated at the same time.

if both long and short entry signals are present, then that's a signal collision (your strategy is undecided if price will move up or down). consequently, **both** of signals are ignored (explained in the [colliding signals section](https://www.freqtrade.io/en/latest/strategy-customization/#colliding-signals)).

It's very well possible that your strategy has a long bias (maybe market dependent, maybe purely based on luck if it's a random strategy) - but freqtrade itself will not care as long as signals don't overlap / collide.
