### ISSUE TITLE
installing or docker?

### ISSUE THREAD

**Issue by Arivadis** [freqtrade/freqtrade#7878]
Hi,

I would like to ask You if there is aswer for my question.

What would use less RAM memory and less CPU load - using docker or simple installing(for case of multiple bots)?

Bots the same, system last ubuntu, for example.

Thank You!

**Comment by xmatthias** [comment]
Docker is another abstraction layer - so it will have a slight overhead.

It's nothing you'll notice though - and personally, i prefer the easy of installing with docker than the native maintenance, especially when running multiple bots.

In the end, i think it will come down to what you're more comfortable with - as both options work - and we have documentation for both approaches.
