### ISSUE TITLE
Current Version

### ISSUE THREAD

**Issue by naujoks-stefan** [freqtrade/freqtrade#7879]
I have a simple question.

I opened a "bug question" few hours ago and you explained me that I'm working with an old version (Unexpected behavior / exception #7877).

You're right, but I don't know what I did wrong? When I download 

1.) git clone -b 2022.11 https://github.com/freqtrade/freqtrade.git, change into freqtrade directory, freqtrade -V = 2022.10.dev-77826ebf7 (<-- same version like #7877)

2.) download zip file from https://github.com/freqtrade/freqtrade/tags 2022.11 zip file, extract and freqtrade -V = 2022.10.dev-21ff3b5

Now I'm confused. Expected 2022.11xxxxx but both are 2022.10.xxxx. What is the current version?

**Comment by xmatthias** [comment]
this will depend on how you run / install freqtrade.

by default, a `pip install .` will copy the sourcecode into the python site_packages.

it's therefore crucial to ensure that you're following the [updating docs](https://www.freqtrade.io/en/latest/updating/).

i've just tried a `git checkout 2022.11` (which will switch to that head) - which shows the correct output to me.

![image](https://user-images.githubusercontent.com/5024695/206750594-396d0701-692d-4b34-951c-4f71246da08c.png)

`2022.10.dev-21ff3b5` is a curious version - the commit 21ff3b5  is not part of this repository at all - so i wonder what you've actually gotten with that download (the download contains 2022.11 for me).
