### ISSUE TITLE
Can not connect to UI server

### ISSUE THREAD

**Issue by Arivadis** [freqtrade/freqtrade#7880]
Hello, 

Im stacked trying to connect to the sever.

I added new up new container, bot is working.
But can not connect to the bot with FreqUI.
The main problem - another one bot, which was before - is working fine. i can connect to server using port 80.
But the second bot with port 90 - cant connect.
Configs has the same API config
"listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxXXXXXXXXXXXXXX",
        "ws_token": "xxxxxxxxxxxxxxxxxxxxxXXXXXXXXXXXXXXX",
        "CORS_origins": ["http://128.XXX.XX.XX"],

.yml ports - ports:
      - "127.0.0.1:8080:8080"
and 
ports:
      - "127.0.0.1:8090:8080"
both ports are opened 
tcp        0      0 127.0.0.1:8090          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN

So, I can connect to post 80 and can't connect to 90

**Comment by Arivadis** [comment]
thank You for any help

**Comment by Arivadis** [comment]
affa5cd69f14   freqtradeorg/freqtrade:develop_plot   "freqtrade trade --l…"   36 seconds ago   Up 34 seconds   127.0.0.1:8090->8080/tcp   freqtrade_51
11877abb7d7d   freqtradeorg/freqtrade:develop_plot   "freqtrade trade --l…"   51 minutes ago   Up 51 minutes   127.0.0.1:8080->8080/tcp   freqtrade
Each is running. 
The only one difference - usernames and password

**Comment by xmatthias** [comment]
assuming you want to see both in the same UI - then you'll need to properly configure [cors](https://www.freqtrade.io/en/latest/rest-api/#cors) - according to the documentation.

Assuming you inserted `"CORS_origins": ["http://128.XXX.XX.XX"],` - then that's wrong - and it should probably be `"CORS_origins": ["http://128.XXX.XX.XX:8080", "http://128.XXX.XX.XX:8090"],` .

In reality, only the _Main_ url of the two (the one you navigate to) will be required - this way will simply make sure that you can use both URL's eventually.

**Comment by Arivadis** [comment]
Hello,

It was Nginx.
Thank You!

**Comment by xmatthias** [comment]
That's .... another possibility :laughing:
