### ISSUE TITLE
scikit-optimize ExtraTreesRegressor out of sync with sklearn: deprecation of 'mse' criterion

### ISSUE THREAD

**Issue by froggleston** [freqtrade/freqtrade#7896]
## Describe your environment

  * Freqtrade Version: `develop` since https://github.com/freqtrade/freqtrade/commit/61592e76b00462eae89d63dfc68e273339462b51
  

## Describe the problem:

scikit-optimize ExtraTreesRegressor uses the default criterion of 'mse' which is deprecated in sklearn 1.2. Since the bump of sklearn from 1.1.3 to 1.2 in `requirements-hyperopt.txt`, this is a breaking change.

### Steps to reproduce:

  1. install ft develop branch from source by any means
  2. hyperopt with the 'ET' estimator default
  
### Observed Results:

![image](https://user-images.githubusercontent.com/1872302/207356514-351a4952-9f24-4dbf-9dfd-a3ef186a0bec.png)
From `@ctnx` in the discord server.

### Relevant code exceptions or logs

https://github.com/scikit-optimize/scikit-optimize/issues/1137

**Comment by xmatthias** [comment]
It's unfortunate that scikit-optimize seems to be unmaintained.

every year, someone claims "I've now taken over, it'll be better" - does 3 commits, until it dies off again for another year or 3 ... 

Nice catch though :+1:

**Comment by chrisk314** [comment]
@xmatthias does [Optuna](https://github.com/optuna/optuna) serve your needs? I'm using it in my package (proprietary lib at a big corp) for optimising simulation models. It works well and is actively maintained. I for one am dropping support for `scikit-optimize` on account of it being unmaintained.

**Comment by xmatthias** [comment]
@chrisk314 i'm happy to accept a contribution in this regards - but one requirement is that we can keep compatibility to the existing strategy-parameters - so from a user perspective, it's a non-breaking change.

**Comment by xmatthias** [comment]
Further pinged the maintainers of scikit-learn inhttps://github.com/scikit-optimize/scikit-optimize/issues/847 - hoping to get either some time allocated for that project - or a clear statement that it's no longer maintained.
