### ISSUE TITLE
freqtrade.strategy.interface - WARNING - Outdated history for pair SOL/BTC. Last tick is 17 minutes old

### ISSUE THREAD

**Issue by Tizianop82** [freqtrade/freqtrade#7900]
## Describe your environment

  * Operating system: ____docker on fedora 35
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _202211___ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
binance spot market.
from abount 2 weeks, in log freqtrade report all outdated data, but on binance the volume is present for that coins.
freqtrade.strategy.interface - WARNING - Outdated history for pair SOL/BTC. Last tick is 17 minutes old.

**Comment by xmatthias** [comment]
if you're sure that the volume on exchange is valid - then you'll need to provide (a lot more) logs than one line.

This line is just telling us the symptom (last tick is 17 minutes) - but not the cause.

**Comment by Tizianop82** [comment]
for example I checked the previous 5min candles and the volume was there.
there are no other errors in the log, just "outdated history" on all pairs
How can I do other checks on freqtrade?

**Comment by xmatthias** [comment]
Errors only are not relevant - and also this is no error but a warning.

please provide several (unmodified, and without missing) log-lines from around this error (even if you think they are irrelevant)  - which will allow us to analyze this further.

**Comment by Tizianop82** [comment]
the problem is that even if it activates the entry event it doesn't enter the market

**Comment by xmatthias** [comment]
Yes, that's there to protect you / your bot.
 If the signal is 17 minutes old - then this is clearly outdated information.

Without the requested logs there is however nothing i can do for you.

**Comment by xmatthias** [comment]
Can't help without the requested logs.

Feel free to comment below (with the logs requested) if it's still an issue you'd like us to look at.
