### ISSUE TITLE
Is there a way to get a callback after the trade has  exited?

### ISSUE THREAD

**Issue by ashwinprasadme** [freqtrade/freqtrade#7903]
I have a certain strategy specific persistent metadata that I maintain for each pair that is active in trade. 

After the trade is complete, I want to make sure that I update my state accordingly. 

I was wondering if there are any strategy callbacks that are triggered after the trade is fully closed.

I see that [check_exit_timeout()](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-timeout-rules) could be used, but this is still not after the trade is closed and may not be called for all order types.

I'm now trying to use `_notify_exit` from `freqtradebot.py` and calling a custom strategy callback for this purpose.

Is there something better that I could be doing here?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

There is not - and i don't really see why it would be necessary either - at least not for the usecase you're trying to use it.
Prior trade data is available via [`Trade` queries](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-trades) - so tracking data for each active trade individually seems redundant.

Obviously, data there is limited in backtesting - but i assume that's not your usecase, as the same limit will apply to you manually tracking the same thing again.

**Comment by ashwinprasadme** [comment]
I see, okay. Let me try to tell you more about the use case. 

I have certain metadata about the trade that I want to persist when the trade is entered. I use this data to make decisions throughout the lifetime of that trade. This is managed entirely on the strategy side without messing with the core logic.

However, on exit, I want to delete the persisted data for that trade. This is where I need the exit callback to do some cleanup operations on the strategy side.

If you think that this makes sense, I can create a pull request with this functionality.

**Comment by stash86** [comment]
you can do so on boot_loop_start function. Check whether the pair still have an open trade. If not, delete the data

**Comment by ashwinprasadme** [comment]
Thank you. This can work indeed. Let me look into that. But do you still think such an exit callback is redundant?

**Comment by stash86** [comment]
yes because 99% of users won't need it, and for the 1% we have the workaround for it.

**Comment by ashwinprasadme** [comment]
Yeah, makes sense. Thanks for the tip.

**Comment by xmatthias** [comment]
> If you think that this makes sense, I can create a pull request with this functionality.

i'm not per se against a well made PR that adds such a callback - as it can have other uses (like a manual but more dynamic setup of protections) - and is the callback that's kinda missing when we think about the lifecycle of a trade.

we'll however need to very carefully consider where/when we expect this to be called - especially for live.

**Comment by ashwinprasadme** [comment]
That is indeed true. Let me actually give this a shot and create a PR soon. Maybe we can discuss it further there. Thanks for your help!

**Comment by spaceandtrade** [comment]
I'd also be interested in this. I'd like to lift the auto-lock on a pair, depending on the exit reason.

My usecase: I have a strategy that can go short as well as long. It exits on a contradicting signal. E.g. when in a long position, it exits when getting a short signal.
Problem: on the next full candle, my indicator often still gives the same signal, and the bot will only then enter the counter trade. In my case this is 8hrs later, which reduces profitability. When backtesting I get the best results when I act immediately on an indicator.

So my usecase is actually the same as #7386.

I'm not a great programmer but if I can help think about this problem functionally or can help testing, writing docs, do let me know.

**Comment by stash86** [comment]
As wrote above, `bot_loop_start`, although as said by matthias in another post, such "hack" won't be backtestable

**Comment by stash86** [comment]
And your backtest actually behaving the same way as how FT currently working, which is no immediate short entry after long exit or vice versa, so your statement above is wrong

**Comment by spaceandtrade** [comment]
@stash86 you are of course right about backtesting the exact same behaviour (immediate counter trade). When I delay _all_ my entry signals by one candle I have about ˜50% less average daily profit. So my hypothesis is that profitability is also reduced for counter trades, when the trade entry is delayed by one candle like it is now.

If I understand correctly, having an actual exit callback, instead of having to rely on the `bot_loop_start` workaround would enable me to properly (back)test my assumption. And would also improve code performance, since the logic I need will not have to be executed in each loop checking all pairs.

Hope this clarifies.

**Comment by xmatthias** [comment]
> If I understand correctly, having an actual exit callback, instead of having to rely on the `bot_loop_start` workaround would enable me to properly (back)test my assumption. And would also improve code performance, since the logic I need will not have to be executed in each loop checking all pairs.

This is a false assumption.
the "auto" lock in backtesting is implicit based on the execution logic of backtesting.
there is no auto-lock in backtesting - so you will not be able to get around this for backtesting (this would only help for live - where i'd also discourage disabling the auto-lock).

**Comment by spaceandtrade** [comment]
@xmatthias thanks for explaining.

> this would only help for live - where i'd also discourage disabling the auto-lock

There will be risks involved indeed. Especially since it seems I cannot backtest it. I will have to dry-test it very well before putting the strategy live. An `exit_trade` callback would help me oversee and limit risk better than having to implement more logic in the `bot_loop_start` callback.

**Comment by seanmavley** [comment]
@spaceandtrade 
> An exit_trade callback would help me oversee and limit risk better than having to implement more logic in the bot_loop_start callback.

I agree. 

Alternatively, you could use the order filled callback: https://www.freqtrade.io/en/stable/strategy-callbacks/#order-filled-callback and target only the `exit` and `stoploss` reasons
