### ISSUE TITLE
 import freqtrade.strategy as fs missing?

### ISSUE THREAD

**Issue by Immortality-IMT** [freqtrade/freqtrade#7909]
## Describe your environment

  * Operating system: Linux Mint
  * Python Version: 3.8.10 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2022.11 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

I have a script that calls, import freqtrade.strategy as fs 
It appears it cannot be found,     class AdvancedStrategy(fs.BaseStrategy):
AttributeError: module 'freqtrade.strategy' has no attribute 'BaseStrategy'

The BaseStrategy class is defined in the freqtrade.strategy module of the freqtrade library.

Where has it gone?

**Comment by xmatthias** [comment]
Freqtrade never had a `BaseStrategy` - it's always been called `IStrategy`.

Please don't blindly use code chatGPT generated - it's not really intelligent code - it just looks that way until you look close enough.
