### ISSUE TITLE
jsonschema.exceptions.ValidationError: 'USDT' is not one of ['AUD', 'BRL', 'CAD'....]

### ISSUE THREAD

**Issue by dekacypher** [freqtrade/freqtrade#7910]
## Describe your environment

  * Operating system: MacOS 12.6.1
  * Python Version: 3.11.1 (`python -V`)
  * CCXT version: 2.4.17 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.11 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
I've tried editing coingecko_mapping in fiat_convert.py to include USDT in all caps and searched for similar errors without finding a solution that works. How can i solve this?

`coingecko_mapping = {
    'eth': 'ethereum',
    'bnb': 'binancecoin',
    'sol': 'solana',
    'usdt': 'tether',
}
`

This is the errormessage i get when running docker-compose logs --f in my terminal after starting Docker. 

`Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade  |     worker = Worker(args)
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 37, in __init__
freqtrade  |     self._init(False)
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 53, in _init
freqtrade  |     self.freqtrade = FreqtradeBot(self._config)
freqtrade  |   File "/freqtrade/freqtrade/freqtradebot.py", line 65, in __init__
freqtrade  |     validate_config_consistency(config)
freqtrade  |   File "/freqtrade/freqtrade/configuration/config_validation.py", line 96, in validate_config_consistency
freqtrade  |     validate_config_schema(conf, preliminary=preliminary)
freqtrade  |   File "/freqtrade/freqtrade/configuration/config_validation.py", line 66, in validate_config_schema
freqtrade  |     raise ValidationError(
freqtrade  | jsonschema.exceptions.ValidationError: 'USDT' is not one of ['AUD', 'BRL', 'CAD', 'CHF', 'CLP', 'CNY', 'CZK', 'DKK', 'EUR', 'GBP', 'HKD', 'HUF', 'IDR', 'ILS', 'INR', 'JPY', 'KRW', 'MXN', 'MYR', 'NOK', 'NZD', 'PHP', 'PKR', 'PLN', 'RUB', 'UAH', 'SEK', 'SGD', 'THB', 'TRY', 'TWD', 'ZAR', 'USD', 'BTC', 'ETH', 'XRP', 'LTC', 'BCH']`

**Comment by xmatthias** [comment]
why would you wanna use USDT as FIAT currency?

it's supposed to be a FIAT currency (as the name implies) - which USDT is not.

**Comment by dekacypher** [comment]
I'm not trying to, I'm new to freqtrade and I'm just trying to get it up and running. If you look at the fiat_convert.py, it's  supposed to convert crypto to fiat, and sorry I meant I edited the class to include USDT and not usdt in small caps.

`coingecko_mapping = {
    'eth': 'ethereum',
    'bnb': 'binancecoin',
    'sol': 'solana',
    'usdt': 'tether',
}
`

**Comment by xmatthias** [comment]
well this mapping is there for duplicate coins in coingecko (where the symbol exists multiple times).

you'rs is a configuration error - `fiat_display_currency` is supposed to be your fiat currency (USD, EUR, ...) depending on where you live.

USDT will (most likely) be your stake currency.

**Comment by dekacypher** [comment]
Thank you for clarifying that, but I dont quite understand the problem as the error is stating, USDT shouldn't be a fiat currency, which is correct. Then why is this error arising?

**Comment by xmatthias** [comment]
The error is a configuration validation error.
it's raising because your configuration contains `"fiat_display_currency": "USDT"` .

**Comment by dekacypher** [comment]
Alright, I'll try to fix that

**Comment by dekacypher** [comment]
It solved the problem! Thank you so much!
