### ISSUE TITLE
No results in backtesting

### ISSUE THREAD

**Issue by r6965** [freqtrade/freqtrade#7911]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.8
  
## Your question

I have problem with backtesting my strategy. Backtesting dose not show any results.
Strategy is based on comparing OHLC of two candles.
4 cases despite of the type of candles.

Code:

```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        global long
        long = 0

        ### [0] Green Candle, [1] Green Candle ###
        if (dataframe.iat[0, 4] > dataframe.iat[0, 1] and dataframe.iat[1, 4] > dataframe.iat[1, 1]):
            if dataframe.iat[0, 4] > dataframe.iat[1, 4]:
                long  =  long  + 1
            else:
                pass


        ### [0] Red Candle, [1] Green Candle ###
        elif (dataframe.iat[0, 1] > dataframe.iat[0, 4] and dataframe.iat[1, 1] > dataframe.iat[1, 4]):
            if dataframe.iat[0, 1] > dataframe.iat[1, 4]:
                long  =  long  + 1
            else:
                pass

        ### [0] Green Candle, [1] Red Candle ###
        elif (dataframe.iat[0, 4] > dataframe.iat[0, 1] and dataframe.iat[1, 4] < dataframe.iat[1, 1]):
            if dataframe.iat[0, 4] > dataframe.iat[1, 1]:
                long  =  long  + 1
            else:
                pass

        ### [0] Red Candle, [1] Red Candle ###
        elif (dataframe.iat[0, 4] < dataframe.iat[0, 1] and dataframe.iat[1, 4] < dataframe.iat[1, 1]):
            if dataframe.iat[0, 1] > dataframe.iat[1, 1]:
                long  =  long  + 1
            else:
                pass
        else:
            pass

def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
       if long > 0:
          dataframe.loc['enter_long'] = 1
       else:
           pass
           
       return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
       if long == 0:
            dataframe.loc['exit_long'] = 1
       else:
           pass
           
       return dataframe
```

Results:
```
========================================================== BACKTESTING REPORT =========================================================
|     Pair |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
|----------+--------+----------------+----------------+-------------------+----------------+----------------+-------------------------|
| BTC/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
|    TOTAL |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
========================================================= ENTER TAG STATS ==========================================================
|   TAG |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
|-------+--------+----------------+----------------+-------------------+----------------+----------------+-------------------------|
| TOTAL |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
===================================================== EXIT REASON STATS =====================================================
|   Exit Reason |   Exits |   Win  Draws  Loss  Win% |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |
|---------------+---------+--------------------------+----------------+----------------+-------------------+----------------|
====================================================== LEFT OPEN TRADES REPORT ======================================================
|   Pair |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
|--------+--------+----------------+----------------+-------------------+----------------+----------------+-------------------------|
|  TOTAL |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
================================ SUMMARY METRICS ================================
No trades made. Your starting balance was 1000 USDT, and your stake was 100 USDT.
=================================================================================
```
Any ideas what I am doing wrong?

**Comment by xmatthias** [comment]
Your strategy is looking at one single candle - the first and 2nd in the dataframe (and with that - in the backtesting period).

This is one of the gotchas listed in the [common mistakes](https://www.freqtrade.io/en/latest/strategy-customization/#common-mistakes-when-developing-strategies) section - though you're not looking into the future, but into the past.

Your whole concept will not work for a freqtrade strategy.
please familiarize yourself with the [bot execution logic](https://www.freqtrade.io/en/latest/bot-basics/#bot-execution-logic).

We also recommend to at least fly over the documentation at least once - so you have a rough idea what freqtrade can do for you and what it can't.

**Comment by froggleston** [comment]
> ## Describe your environment
> 
>     * Operating system: Ubuntu
> 
>     * Python Version: 3.8
> 
> 
> ## Your question
> 
> I have problem with backtesting my strategy. Backtesting dose not show any results. Strategy is based on comparing OHLC of two candles. 4 cases despite of the type of candles.
> 
> Code:
> 
> ```
> def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
>         global long
>         long = 0
> 
>         ### [0] Green Candle, [1] Green Candle ###
>         if (dataframe.iat[0, 4] > dataframe.iat[0, 1] and dataframe.iat[1, 4] > dataframe.iat[1, 1]):
>             if dataframe.iat[0, 4] > dataframe.iat[1, 4]:
>                 long  =  long  + 1
>             else:
>                 pass
> 
> 
>         ### [0] Red Candle, [1] Green Candle ###
>         elif (dataframe.iat[0, 1] > dataframe.iat[0, 4] and dataframe.iat[1, 1] > dataframe.iat[1, 4]):
>             if dataframe.iat[0, 1] > dataframe.iat[1, 4]:
>                 long  =  long  + 1
>             else:
>                 pass
> 
>         ### [0] Green Candle, [1] Red Candle ###
>         elif (dataframe.iat[0, 4] > dataframe.iat[0, 1] and dataframe.iat[1, 4] < dataframe.iat[1, 1]):
>             if dataframe.iat[0, 4] > dataframe.iat[1, 1]:
>                 long  =  long  + 1
>             else:
>                 pass
> 
>         ### [0] Red Candle, [1] Red Candle ###
>         elif (dataframe.iat[0, 4] < dataframe.iat[0, 1] and dataframe.iat[1, 4] < dataframe.iat[1, 1]):
>             if dataframe.iat[0, 1] > dataframe.iat[1, 1]:
>                 long  =  long  + 1
>             else:
>                 pass
>         else:
>             pass
> 
> def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
>        if long > 0:
>           dataframe.loc['enter_long'] = 1
>        else:
>            pass
>            
>        return dataframe
> 
>     def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
>        if long == 0:
>             dataframe.loc['exit_long'] = 1
>        else:
>            pass
>            
>        return dataframe
> ```
> 
> Results:
> 
> ```
> ========================================================== BACKTESTING REPORT =========================================================
> |     Pair |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
> |----------+--------+----------------+----------------+-------------------+----------------+----------------+-------------------------|
> | BTC/USDT |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
> |    TOTAL |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
> ========================================================= ENTER TAG STATS ==========================================================
> |   TAG |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
> |-------+--------+----------------+----------------+-------------------+----------------+----------------+-------------------------|
> | TOTAL |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
> ===================================================== EXIT REASON STATS =====================================================
> |   Exit Reason |   Exits |   Win  Draws  Loss  Win% |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |
> |---------------+---------+--------------------------+----------------+----------------+-------------------+----------------|
> ====================================================== LEFT OPEN TRADES REPORT ======================================================
> |   Pair |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
> |--------+--------+----------------+----------------+-------------------+----------------+----------------+-------------------------|
> |  TOTAL |      0 |           0.00 |           0.00 |                 0 |           0.00 |           0:00 |     0     0     0     0 |
> ================================ SUMMARY METRICS ================================
> No trades made. Your starting balance was 1000 USDT, and your stake was 100 USDT.
> =================================================================================
> ```
> 
> Any ideas what I am doing wrong?

Did you use ChatGPT to create this strategy? If so, it's unsurprising you aren't seeing expected behaviour. Please read the extensive *human created* documentation and examples available to you.

**Comment by r6965** [comment]
I have read the documentation.
This is only the one part of whole strategy, there is no problem with strategy but with proper implementation of it and correct writing indicator.
I have not found pattern recognition examples so that is why I am asking for help.

**Comment by froggleston** [comment]
There are lots of pattern recognition functions in talib which might be of help: https://mrjbq7.github.io/ta-lib/func_groups/pattern_recognition.html

**Comment by r6965** [comment]
Thanks, I have seen that. 
I am sure that def populate_indicators is not correct but still do not know how to fix it.

**Comment by stash86** [comment]
well, you need to learn pandas it seems. Also read matthias' reply. They already pointed out why it doesn't work

**Comment by xmatthias** [comment]
> I am sure that def populate_indicators is not correct but still do not know how to fix it.

The documentation is clearly the place to start. You'll need to understand how a freqtrade strategy works.
You're assigning signals to global variables - which simply will not work.

Effectively, you're doing exactly [this](https://www.freqtrade.io/en/latest/strategy-customization/#dataframe) - which is a known and documented anti-pattern. This doc-page also contains how to generally fix this - it's obviously up to you to implement this against your actual strategy.
