### ISSUE TITLE
Inconsistent HyperOpt and Backtesting Results

### ISSUE THREAD

**Issue by holycacao** [freqtrade/freqtrade#7912]
## Describe your environment

  * Operating system: Ubuntu 22.04.1 LTS
  * Python Version: Whatever is provided by `freqtradeorg/freqtrade:stable 2022.11`
  * CCXT version: 2022-12-17 04:41:44,236 - freqtrade.exchange.exchange - INFO - Using CCXT 2.1.96
  * Freqtrade Version: 2022.11
  
## Describe the problem:

Hyperopt and backtesting (using values from a hyperopt epoch) results are not the same.

### Steps to reproduce:

  1. Run hyperopt
  2. Fill in strategy values from hyperopt epoch
  3. Run backtest

### Observed Results:
Observe results are different between the selected hyperopt epoch and the backtest result. I first thought this was due to me not using `--analyze-per-epoch` in hyperopt since indicator parameters were being hyperopt'ed. But even with using that, the results are still not the same and I can't seem to find any other differences in config. I am using the `--timeframe-detail` option - maybe there is a bug there?

HyperOpt logs
[20220901-20221101.ShortTradeDurHyperOptLoss.mamappocrosstest.roi_10pct_noexit_b_sl.log](https://github.com/freqtrade/freqtrade/files/10252504/20220901-20221101.ShortTradeDurHyperOptLoss.mamappocrosstest.roi_10pct_noexit_b_sl.log)

HyperOpt Epoch Used
[hyperopt-epoch-368.txt](https://github.com/freqtrade/freqtrade/files/10252521/hyperopt-epoch-368.txt)

Backtest logs
[backtest-results.log](https://github.com/freqtrade/freqtrade/files/10252508/backtest-results.log)

### Relevant code exceptions or logs
`user_data/strategies/basestrategy.py`
```py
from freqtrade.strategy import IStrategy


class BaseStrategy(IStrategy):
    # Strategy interface version - allow new iterations of the strategy interface.
    # Check the documentation or the Sample strategy to get the latest version.
    INTERFACE_VERSION = 3

    # Can this strategy go short?
    can_short: bool = False

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = False

    # These values can be overridden in the "ask_strategy" section in the config.
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False

    # Optional order time in force.
    order_time_in_force = {"entry": "gtc", "exit": "gtc"}
```

`user_data/strategies/mamappocrosstest.py`
```py
# most imports omitted
from basestrategy import BaseStrategy

class MAMAPPOCrossTest(BaseStrategy):
    class HyperOpt:
        def stoploss_space():
            return [SKDecimal(-0.05, -0.01, decimals=3, name="stoploss")]

    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi".
    minimal_roi = {"0": 0.1}

    # Optimal stoploss designed for the strategy.
    # This attribute will be overridden if the config file contains "stoploss".
    # Stoploss:
    stoploss = -0.025

    # Trailing stop:
    # trailing_stop = True
    # trailing_stop_positive = 0.021
    # trailing_stop_positive_offset = 0.022
    # trailing_only_offset_is_reached = False

    # Optimal timeframe for the strategy.
    timeframe = "1h"

    # if this is false, return the unchanged dataframe in populate_exit_trend
    use_exit_indicators = False

    # entry mama
    mama_src = "close"
    entry_mama_fast_limit = CategoricalParameter(
        categories=[0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80],
        default=0.75,
        space="buy",
        optimize=True,
    )
    entry_mama_slow_limit = CategoricalParameter(
        categories=[0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35],
        default=0.20,
        space="buy",
        optimize=True,
    )
    entry_mama_ind = MAMA(entry_mama_fast_limit.value, entry_mama_slow_limit.value, mama_src)

    # exit mama
    # exit_mama_fast_limit = entry_mama_fast_limit
    exit_mama_fast_limit = CategoricalParameter(
        categories=[0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80],
        default=0.60,
        space="sell",
        optimize=True,
    )
    # exit_mama_slow_limit = entry_mama_slow_limit
    exit_mama_slow_limit = CategoricalParameter(
        categories=[0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35],
        default=0.15,
        space="sell",
        optimize=True,
    )
    exit_mama_ind = MAMA(exit_mama_fast_limit.value, exit_mama_slow_limit.value, mama_src)

    # ppo for entry signals
    entry_ppo_fast_per_param = CategoricalParameter(
        categories=[6, 12, 18, 24],
        default=12,
        space="buy",
        optimize=True,
    )
    ppo_period_map = {
        6: 13,
        12: 26,
        18: 39,
        24: 52,
    }
    entry_ppo_fast_per = entry_ppo_fast_per_param.value
    entry_ppo_slow_per = ppo_period_map[entry_ppo_fast_per_param.value]
    entry_ppo_signal_per = 9
    entry_ppo_threshold = DecimalParameter(
        low=-3, high=0, default=-0.45, decimals=2, space="buy", optimize=True
    )
    entry_ppo_carry_forward_pers = IntParameter(
        low=1, high=5, default=5, space="buy", optimize=True
    )
    entry_ppo_ind = PPO(entry_ppo_fast_per, entry_ppo_slow_per, entry_ppo_signal_per)

    use_custom_stoploss = False

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count = 26
```

**Comment by froggleston** [comment]
a) You haven't stated what you *expect* to see vs what you *actually* see. Please post up evidence that your hyperopts (which are simply iterative backtests) are different from your backtests with exact configuration.
b) `process_only_new_candles = False` are you sure you want to do this? It only becomes relevant if you're using ticker data in your strategy. Candle data remains the same each bot loop if you use this as False or True, as per the docs.
c) What do PPO and MAMA functions do?

**Comment by xmatthias** [comment]
Hyperopt is just calling backtesting under the hood - it's technically impossible to have values mismatch assuming things are done correctly.

at a first glance - are you sure your parameters are correct?

they're not exported from hyperopt ... 
`2022-12-17 04:41:44,229 - freqtrade.configuration.configuration - INFO - Parameter --disableparamexport detected: True ...` 

---

At a second glance i assume your assignments are wrong.
While the strategy is not complete - you cannot use strategy parameters at the class level (outside of `populate_*` or callbacks).

as such -  the following segment will not work - and will always use the initial value (most likely the default) throughout the hyperopt run - since `exit_mama_slow_limit.value` (and `exit_mama_fast_limit.value`) will never change.

```
    exit_mama_slow_limit = CategoricalParameter(
        categories=[0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35],
        default=0.15,
        space="sell",
        optimize=True,
    )
    exit_mama_ind = MAMA(exit_mama_fast_limit.value, exit_mama_slow_limit.value, mama_src)
```

it's not the only segment that will not work above - but you should get the idea.

**Comment by holycacao** [comment]
Thanks @xmatthias. It must be that. I was often doing some additional logic for each indicator calculated and each time I tweaked that logic, it meant I'd need to update every strategy that was using that indicator, so I made shared functions. Will move this logic into the `populate_*` funcs and try again.

**Comment by xmatthias** [comment]
in short - it must be in code that runs as part of backtesting.
the strategy is initialized only once - so your method only runs once - so the parameter will never change (it changes, but the indicator is never redefined).

you MIGHT get around it by using a function that returns that indicator config - but obviously you'll have to call that from within one of the populate_* methods.
