### ISSUE TITLE
Now backtesting is supporting unlimited stake amount, but does it compound the profits

### ISSUE THREAD

**Issue by amgad-muhammad** [freqtrade/freqtrade#7913]
## Describe your environment

  * Operating system: MacOS M1
  * Freqtrade Version: freqtrade 2022.11
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

In the documentation it says that unlimited stake amount is supported in backtesting, my question is in the results of the backtesting are you compounding to show the absolute profits...etc 

I would apprecaite if you can exmplain the relationship between total profit%, CAGR% and avg daily profit%

**Comment by xmatthias** [comment]
unlimited stake amount logics are explained in it's own [configuration section](https://www.freqtrade.io/en/stable/configuration/#dynamic-stake-amount) - while 
Backtesting metrics are explained in the [backtesting metrics section of the documentation](https://www.freqtrade.io/en/stable/backtesting/#summary-metrics) page.
