### ISSUE TITLE
Force exit doesn't close trade

### ISSUE THREAD

**Issue by simwai** [freqtrade/freqtrade#7928]
## Describe your environment

  * Operating system: Ubuntu 18.04 LTS
  * Python Version: 3.10.8 (`python -V`)
  * CCXT version: 2.2.36 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2022.12.dev (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. Use freqtrade trade to start telegram bot instance
  2. Sell manually after a trade get opened
  3. Try to run /forceexit with Telegram bot
  
### Observed Results:

  * What happened?
Nothing
  * What did you expect to happen?
The trade should exit even if the sell amount is too low, in order to avoid a wrong open trade

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/freqtrade/.env/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File "/root/freqtrade/.env/lib/python3.10/site-packages/telegram/ext/handler.py", line 199, in handle_update
    return self.callback(update, context)
  File "/root/freqtrade/freqtrade/rpc/telegram.py", line 1045, in _force_exit_inline
    self._force_exit_action(trade_id)
  File "/root/freqtrade/freqtrade/rpc/telegram.py", line 1028, in _force_exit_action
    self._rpc._rpc_force_exit(trade_id)
  File "/root/freqtrade/freqtrade/rpc/rpc.py", line 738, in _rpc_force_exit
    self.__exec_force_exit(trade, ordertype, amount)
  File "/root/freqtrade/freqtrade/rpc/rpc.py", line 707, in __exec_force_exit
    self._freqtrade.execute_trade_exit(
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 1558, in execute_trade_exit
    amount = self._safe_exit_amount(trade, trade.pair, sub_trade_amt or trade.amount)
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 1502, in _safe_exit_amount
    raise DependencyException(
freqtrade.exceptions.DependencyException: Not enough amount to exit trade. Trade-amount: 90.8, Wallet: 0.02116427
```

**Comment by xmatthias** [comment]
> Sell manually after a trade get opened

I'll read this as "sold the amount manually on the exchange" for the rest of this post. 
Please let me know if this is not the case.

---

Freqtrade assumes that it owns 90.8 of COIN (whatever coin).
this amount is however no longer present on the exchange (which can have multiple reasons).
freqtrade tracks all orders it created, and will in case of this error - try to identify which order is causing the mismatch walking through all prior orders it created.
so most likely, it was sold manually on the exchange (this is my assumption based on your description, but also the most likely reason).

If you manually sold on the exchange - then this is an unknown operation to freqtrade - and you'll also need to manually handle the trade accordingly. 

Freqtrade will not "forget" this amount - and it has no information how to treat it.
calling `/forceexit` will attempt to sell the amount - if that fails - it won't know how to react - leaving the trade open - and further action up to the user.

Freqtrade will not take assumptions based on orders it didn't take itself - as we support both multiple bots - as well as bot & manual trading on the same account (the account doesn't have to be exclusively used by freqtrade).
Taking such assumptions would make this a necessity - which we don't want to enforce as many don't have access to subaccounts (binance stopped giving out subaccounts to low-VIP users a while ago).


if you manually interfered with bot operations - you can either manually delete the trade `/delete <tradeid>` - or follow the [sql cheatsheet](https://www.freqtrade.io/en/stable/sql_cheatsheet/#fix-trade-still-open-after-a-manual-exit-on-the-exchange) to close the trade manually - based on the order(s) you used to exit the trade manually.

**Comment by simwai** [comment]
Didn't know about the delete command. That was what i wanted. IMO don't call the command force exit if it doesn't force exit. Just confuses people. Force exit means to exit in any circumstance (including missing balance).

**Comment by stash86** [comment]
You can't exit when the existing balance is below allowed minimum exchange size. You can try to force exit on that one. Just because a command named "force exit" doesn't mean it has to be 100% successful

**Comment by xmatthias** [comment]
Can't agree more.

You force an exit (overriding the regular strategy). it'll however still have to submit to exchange rules - including "can't sell what you don't have".
