### ISSUE TITLE
best way to change position at minimum maxima in populate_entry/exit_trend

### ISSUE THREAD

**Issue by HeinrichHaller** [freqtrade/freqtrade#7930]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: Python 3.10.6
  * CCXT version: ccxt==2.4.27
  * Freqtrade Version: freqtrade 2022.12.dev-3012c55ec
  
## Your question

How to elegantly change to long/ short when an oscillator ascends/ decreases in futures/ margin mode with consequently being invested.  

![etherum-decompose-ex](https://user-images.githubusercontent.com/78827281/209009708-9a4769f9-c48c-4887-8ec6-86d838fb36fd.png)
```
a = np.array([1,-1,-2,-3,4,5, 3, 2])
zeichen = np.append([0], np.sign(np.diff(a)))
wechsel =  ((np.roll(zeichen, 1) - zeichen) != 0).astype(int)
wechsel[0] = 0```

array([0, 1, 0, 0, 1, 0, 1, 0])

And afterwards confirming the direction(long, short) via a Guard and turning the ROI off?
 Thanks

**Comment by xmatthias** [comment]
You can't switch positions from long to short / short to long at the moment.

Once the prior trade exits, the pair will be auto-locked until the end of the candle.
During live, you can (somewhat) circumvent this (manually unlocking) - but for backtesting the auto-lock is implicit, which you can't get around - so your strategy would not be backtestable.

**Comment by HeinrichHaller** [comment]
Here it'd be nice to check the usefulness of an oscillator ceteris paribus without relying on multiple pairs. Workaround would be to sell the long-positon on the short signal, and sell again after the auto-lock has expired, one candle later?

**Comment by xmatthias** [comment]
yes correct - that's the default behavior (assuming your signal is still present on the next candle).

**Comment by HeinrichHaller** [comment]
No it wouldn't, because the sell and buy coincide. The signal needs to carried over to the next candle then. At the moment means it's planned?

**Comment by xmatthias** [comment]
exit short and enter long are not collision checked - so that's not the problem - the locking is though - so it'll not "switch".

**Comment by HeinrichHaller** [comment]
> exit short and enter long are not collision checked - so that's not the problem - the locking is though - so it'll not "switch".

Thanks, I get it. Is the locking here needed because of the "opportunistic" behavior of freqtrade(looking for entries over multiple pairs)? This is surely the strong suit of freqtrade, though. 
But it doesn't foster necessarily the coding from paper or development of new indicators.

**Comment by xmatthias** [comment]
the auto-lock feature is to 
a) replicate backtesting behavior - where the lock is implicit
b) avoid buy/sell loops as the signal is actually present for the duration of the candle (so the bot enters 2/3/4 times within 1 candle - and exits them all with stoploss).
c) avoid late entries - a stoploss can happen 58 minutes into a 1h candle - you usually don't want the bot to react on that signal 59 minutes late.

Now for long/short behavior it's unfortunate (shorts were not possible when this was added) - but i'd not know how to support this in backtesting (in theory, the same pair could swap position 3/4/5 times - so we'd need to check every pair on every candle a potentially indefinite times - while still making sure the other pairs also get a fair chance).

**Comment by HeinrichHaller** [comment]
> the auto-lock feature is to a) replicate backtesting behavior - where the lock is implicit b) avoid buy/sell loops as the signal is actually present for the duration of the candle (so the bot enters 2/3/4 times within 1 candle - and exits them all with stoploss). c) avoid late entries - a stoploss can happen 58 minutes into a 1h candle - you usually don't want the bot to react on that signal 59 minutes late.
> 
> Now for long/short behavior it's unfortunate (shorts were not possible when this was added) - but i'd not know how to support this in backtesting (in theory, the same pair could swap position 3/4/5 times - so we'd need to check every pair on every candle a potentially indefinite times - while still making sure the other pairs also get a fair chance).

Thanks for answer! Makes sense in regard how the position is usually closed in freqtrade - via the ROI or stoploss. And especially backtesting is tricky. When trading a hedged portfolio(easiest case some kind of pair-trading), it is (usually) neither of the two. Just in case something like this is on the roadmap, an alternate mode, where you can 'toggle' the position would be something to consider.     
*rather market neutral instead hedged and not "toggle" but get into a target position to stay market neutral.

**Comment by xmatthias** [comment]
for the moment, there's no change planned in this regards.
