### ISSUE TITLE
I get the following error when I set startup_candle_count: int = 5000

### ISSUE THREAD

**Issue by gitscamI** [freqtrade/freqtrade#7931]
"ERROR - This strategy requires 5000 candles to start, which is more than 5x the amount of candles Binance provides for 5m."
how  can I  get 5000 candles data ?? thanks very much

**Comment by xmatthias** [comment]
you can't - at least not at the moment.
the limit is currently 5x the request size -1 - so it's 4999.

It's an arbitrary limit, really - but we're talking network calls here - so every further call will slow down your bot further - therefore 5x the request size has been taken as limit for now.

**Comment by gitscamI** [comment]
can I use DataProvider'function historic_ohlcv() to get 5000 candles ?

**Comment by xmatthias** [comment]
no not really.
that is data loaded from disk. it'll work initially - but the data will age out as it's not updating.
it's also not designed to be used in live mode - so it can have unintended side-effects.
