### ISSUE TITLE
Using same config for 2 different API keys

### ISSUE THREAD

**Issue by edancr7** [freqtrade/freqtrade#7933]
hey, there is any way to use same strategy for more than 1 key in same time ?

## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
why? / for what purpose?



Freqtrade will run 1 strategy against 1 (combined) configuration against one account.

You therefore cannot use multiple exchange keys in the same configuration.
you can however reuse 99% of the configuration - and have a minimal configuration just containing the keys (explained [here](https://www.freqtrade.io/en/stable/configuration/#multiple-configuration-files).

an alternative way is to use [environment variables ](https://www.freqtrade.io/en/stable/configuration/#environment-variables) - which will have the same effect - but it always assumes you're running 2 bot instances.
