### ISSUE TITLE
BTCST/BUSD - Exit Price at location 1 from orderbook could not be determined

### ISSUE THREAD

**Issue by OleksandrMyronchuk** [freqtrade/freqtrade#7934]
I received many such messages in the log
`2022-12-22 19:01:41 - freqtrade.exchange.exchange - WARNING - BTCST/BUSD - Exit Price at location 1 from orderbook could not be determined. Orderbook: {'symbol': 'BTCST/BUSD', 'bids': [], 'asks': [], 'timestamp': None, 'datetime': None, 'nonce': 242211855}`

`2022-12-22 19:04:05 - freqtrade.freqtradebot - WARNING - Unable to exit trade BTCST/BUSD: `

`2022-12-22 19:04:05 - freqtrade.strategy.interface - WARNING - Outdated history for pair BTCST/BUSD. Last tick is 614 minutes old`

I also have one open trade that says -100%
![image](https://user-images.githubusercontent.com/21970565/209215613-8f0b8867-b510-4db9-8c6d-a80fc74c7336.png)

Please explain what this means. Is this pair no longer traded?

**Comment by xmatthias** [comment]
Yes that's correct.
Assuming you're on binance - then there's "no data here" messages across the board, as well as a nice, fat warning that reads:

> Risk Warning: The price of this token is subject to high volatility. The BTCST project team has stopped all public communication and has been uncontactable. Please understand the risks involved and trade with caution. Binance will not be held responsible for any trading losses. 

![image](https://user-images.githubusercontent.com/5024695/209277275-075f2ee9-889d-41ce-97ed-9bafc2405155.png)

You'll also see that there is no orderbook (it's been delisted / is no longer active).

I'm sure searching binance news for this will also reveal a blogpost about it.

you can see if binance allows you to use "convert dust" on the ownings (Or some other action) - or if it's simply a "100% loss" trade.

---

from a freqtrade perspective, you can either delete the trade `/delete <tradeid>` (or via ui) - or update the trade entry in the database as explained in the [sql cheatsheet](https://www.freqtrade.io/en/latest/sql_cheatsheet/#fix-trade-still-open-after-a-manual-exit-on-the-exchange).

**Comment by OleksandrMyronchuk** [comment]
Thanks for the answer! I would like to clarify whether I correctly understood how to protect it from such losses.
For example: I want to trade all BUSD pairs except TRIBE/BUSD and BTCST/BUSD because they will be deleted (delisted)

I need to set in the config
```
...
  "exchange": {
    "pair_whitelist": [ ".*/BUSD" ],
    "pair_blacklist": [ "TRIBE/BUSD" , "BTCST/BUSD" ]
  }
...
```

That is, I need to view the news of binance and according to the "delisting news", add new pairs to "pair_blacklist" settings

Is it right ?

**Comment by xmatthias** [comment]
yeah that's correct.

You can safely remove the coins once they've actually been delisted - as they will then no longer show up as "active" through the API.

A proper "delisted" date is however not available.
