### ISSUE TITLE
Add new exchange bingx

### ISSUE THREAD

**Issue by leoric1721** [freqtrade/freqtrade#7935]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*

**Comment by xmatthias** [comment]
freqtrade connects to exchanges through [ccxt](https://github.com/ccxt/ccxt). 
once ccxt supports an exchange - there's a mid to high likelyhood that the exchange will work without much fuss.

there is a pr there for it (https://github.com/ccxt/ccxt/pull/14540) - but based on comments, it seems like it's not going well.

Best subscribe to the pull request above - once that has been merged, best simply give it a try.
we have some docs on [what should be tested](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip) early on - and we can provide limited support (assuming you do most of the work - and there's just a few questions left).

We'll however not look at integrating an  exchange ourselfs (that's what we have ccxt for) - nor do we have plans to actively support or integrate an exchange that's not even showing up on [coinmarketcap rankings](https://coinmarketcap.com/rankings/exchanges/).
