### ISSUE TITLE
./setup.sh -i fails 

### ISSUE THREAD

**Issue by okwunnaanyaoku** [freqtrade/freqtrade#7944]
## Describe your environment

  * Operating system: Debian 10 x64
  * Python Version: 3.7.3-1 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

When i run ./setup.sh - i i get the error below 

root@freqtrade-bot:~/latest/freqtrade# ./setup.sh -i
No usable python found. Please make sure to have python3.8 or newer installed.

am i doing something wrong

**Comment by xmatthias** [comment]
well the error is pretty clear - `Please make sure to have python3.8 or newer installed.`.

Freqtrade no longer supports python 3.7 - which is also no longer a maintained / supported version of python.
Most dependencies dropped support for 3.7 as well - so it's not even "really" our decision to no longer support 3.7.

The simplest road will be to use a more uptodate system (debian 11, for example).
Alternatively, you can attempt to update python in-place (this might break the installation - as that would update the system python - be careful if you use this system for anything else) - or use something like pyenv to install a newer version of python.
At any rate, you'll need a python version between 3.8 and 3.10 installed and available for the install script to work.

**Comment by okwunnaanyaoku** [comment]
Thanks :D using a debian 11 works
