### ISSUE TITLE
PCA behaviour in freqai

### ISSUE THREAD

**Issue by HeinrichHaller** [freqtrade/freqtrade#7948]
## Describe your environment

  * Operating system: ubuntu 
  * Python Version: Python 3.10.6
  * CCXT version: ccxt==2.4.60
  * Freqtrade Version: freqtrade 2022.12.dev-882e68c68
  
## Your question

* Haven't read the documentation properly, in case it's in just delete the question
In freqai with ```principal_component_analysis": true``` is only a subset of features forwarded to the next iteration?

**Comment by robcaulk** [comment]
Hello, 

I don't know what "next iteration" means. But in any case, no, PCA simply reduces the dimension (i.e. number of features) during each training. 

Cheers,

Robert
