### ISSUE TITLE
Price data randomization

### ISSUE THREAD

**Issue by italodamato** [freqtrade/freqtrade#7956]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

I know there's an [open issue](https://github.com/freqtrade/freqtrade/issues/2821) about implementing a robust Montecarlo simulation feature, but I was thinking if there could be an easy way to quickly test the strategy by applying a certain degree of randomization on the candles. For instance, I was thinking of applying this transformation to the dataset.
``` python
 rand_arr = np.random.uniform(low=0.95, high=1.05, size=(len(df),))
 for col in ['close', 'high', 'low']:
     df[col] *= rand_arr
 df.loc[1:len(df), 'open'] = df.close.shift()
```
I've tried a rough implementation putting that code within the `populate_indicators` function but trades don't get executed correctly for some reason.

I was thinking that this could be the first step to having a more robust backtesting/hyperopting process. What do you think?

**Comment by xmatthias** [comment]
well your method creates potentially invalid candles (high < low).
That's neither something we test for - nor is it something we even closely aim to support - as it's simply impossible to have such candles - and a clear sign of (badly) fabricated data.

If you want to have a look at how to "properly" create fake data, look at the `conftest.py` file - we have a method for that there. (it's still just fake "valid candles" - it's not realistic timeseries).

---

While you correctly point to the monte carlo simulation feature - you'll notice that the discussion there basically rejects the randomization of the candle data (for several reasons).
While trade signals are often treated as fully random series - they are not (not really).

Returns (what you really want to randomize) are not normal / uniform distributed. Assuming that will mean you'll miss all "large" candles.
your sample has a max movement of 5% in one candle - but depending on the timeframe, the average movement is a lot bigger (or a lot smaller) - but you can still have a 10% 1m candle (especially in weak markets) - so you can't realistically simulate this.

As such - i think this would be a missleading feature.
it'd make you think your strategy works on "surely unseen data" (also the markets haven't seen it) - but in reality, it's on unrealistic data - as i'm yet to encounter even one market that follows a default distribution (be that normal or whatever other distribution).

**Comment by italodamato** [comment]
In my opinion, it's just a quick way to reveal basic overfitting, but it doesn't guarantee the opposite if the returns are still positive i.e. that strategy is NOT overfitting. In other words, it's a necessary but not sufficient condition to prove the strategy is not overfitting.

**Comment by froggleston** [comment]
This isn't a good way to determine overfitting by itself IMO
