### ISSUE TITLE
Hyperopt for time parameters 

### ISSUE THREAD

**Issue by Nayefuk** [freqtrade/freqtrade#7965]
## Describe your environment

  * Operating system: Ubuntu 22.04 / Linux5.15
  * Python Version: 3.10.6
  * CCXT version: CCXT 1.92.20
  * Freqtrade Version: 2022.8.dev-686b72a82
  
## Your question

How do I run hyperopt on time parameters? this is the code ive come up with thus far, but it doesnt seem to be working. 

```py

    # Strategy parameters
    buy_open_hour = IntParameter(0, 23, default=23, space="buy")
    buy_open_minute = IntParameter(0, 59, default=58, space="buy")

    sell_open_hour = IntParameter(0, 23, default=23, space="sell")
    sell_open_minute = IntParameter(0, 59, default=58, space="sell")

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = False

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 0

    # Optional order type mapping.
    order_types = {
        'entry': 'market',
        'exit': 'limit',
        'stoploss': 'limit',
        'stoploss_on_exchange': False
    }

    # Optional order time in force.
    order_time_in_force = {
        'entry': 'gtc',
        'exit': 'gtc'
    }

    def leverage (self, pair: str, current_time: datetime, current_rate: float, proposed_leverage: float, max_leverage: float, entry_tag: Optional[str], side: str, **kwargs) -> float:
        """
        Customize leverage for each new trade. This method is only called in futures mode.

        :param pair: Pair that's currently analyzed
        :param current_time: datetime object, containing the current datetime
        :param current_rate: Rate, calculated based on pricing settings in exit_pricing.
        :param proposed_leverage: A leverage proposed by the bot.
        :param max_leverage: Max leverage allowed on this pair
        :param entry_tag: Optional entry_tag (buy_tag) if provided with the buy signal.
        :param side: 'long' or 'short' - indicating the direction of the proposed trade
        :return: A leverage amount, which is between 1.0 and max_leverage.
        """
        return 20.0

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Adds several different TA indicators to the given DataFrame

        Performance Note: For the best performance be frugal on the number of indicators
        you are using. Let uncomment only the indicator you are using in your strategies
        or your hyperopt configuration, otherwise you will waste your memory and CPU usage.
        :param dataframe: Dataframe with data from the exchange
        :param metadata: Additional information, like the currently traded pair
        :return: a Dataframe with all mandatory indicators for the strategies
        """

        """Generate all indicators used by the strategy"""

        current_hour = dataframe['date'].dt.hour
        current_minute = dataframe['date'].dt.minute

        # Calculate all hour values
        for val in self.buy_open_hour.range:
            dataframe[f'hour_{val}'] = dataframe['date'].dt.hour

        # Calculate all minute values
        for val in self.buy_open_minute.range:
            dataframe[f'minute_{val}'] = dataframe['date'].dt.minute

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        conditions = []
        conditions.append(dataframe[f'hour_{self.buy_open_hour.value}'])
        conditions.append(dataframe[f'minute_{self.buy_open_minute.value}'])
        conditions.append(dataframe['volume'] > 0)

        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
                'enter_long'] = 1
        return dataframe

**Comment by xmatthias** [comment]
it's unclear what you're trying to do in the first place.

The conditions don't seem to work (or rather - they'll always trigger) - so hyperopt has little effect.

```
        conditions.append(dataframe[f'hour_{self.buy_open_hour.value}'])
        conditions.append(dataframe[f'minute_{self.buy_open_minute.value}'])
```

The "selected" hour will always be assigned the dataframe hour (there's no selection taking place).
the endresut will be that you've got 100% buy signals - which makes hyperopt / parameters pointless here.



You're also not describing anything like "i tried this but it didn't work" or "i got this error when running the following comand".

As such, it'll be impossible to help you without more information.

**Comment by Nayefuk** [comment]
Im testing a hypothesis:

"is there a specific hour/minute of the day that I can be long on this asset and have +EV'

im not testing stoploss, ROI or any other parameters at this point. Just the above, which i will build on depending on the results i get. It seems Freqtrade hyperopt might be a great tool to test a hypothesis over an excel sheet :) 

to expand on what im trying to do, is populate a range of hours from 0-23 and minutes from 0-59 and test entries against those, with the results giving an indication if i might be onto something or not. for example, if i enter long at 3:35pm and exit long at 5:10pm every day. What does that look like? is there any positive expectancy over tested period?  

Then further developing this (play around with stop loss, ROI, sizing, etc.) based on results. a strategy that only looks at time for entries and exits, no other indicators. 

I tried both example formats in the documentation (https://www.freqtrade.io/en/stable/hyperopt/). I am an beginner coder and likely my syntax just doesnt make sense, as you alluded to.

**Comment by xmatthias** [comment]
well your columns don't really make sense - you're creating a ton of columns - all have duplicated content (it's just the minutes - copied to 60 columns ...).

what you're looking is something around the following (no need to actually duplicate the columns).

```python
 def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        conditions = []
        conditions.append(dataframe['date'].dt.hour == self.buy_open_hour.value)
        conditions.append(dataframe['date'].dt.minute == self.buy_open_minute.value)
        conditions.append(dataframe['volume'] > 0)

        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
                'enter_long'] = 1
        return dataframe
```

(untested).

Best look at the result in a freqUI chart (start `freqtrade webserver <...>` with enabled API - and look at the chart output).

You'll only see the "default" values for your strategy - however it'll show you if the logic is correct or not.

**Comment by Nayefuk** [comment]
that worked perfectly, thank you!
