### ISSUE TITLE
Is there a way to hyperopt from dryrun results? (probably been asked before... I did search)

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#7968]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by stash86** [comment]
I think you misunderstood what hyperopt really is. Hyperopt is just a series of backtests done to find the best loss value. So hyperopt and dry/live run aren't meant to be connected

**Comment by stash86** [comment]
What you want probably is hyperopt that run automatically on defined interval. For that, you need to learn about automating task on linux. Google is your friend

**Comment by tomjrtsmith** [comment]
Some way to analyse hyperparams off live trade data ...

**Comment by xmatthias** [comment]
It's unclear what you're trying to analyze.

well your live results will come based on some applied parameters.

changing these would change the result (trades may not be entered, or entered earlier/later - obviously with potentially largely different results).
That's what backtesting is for (if you change the parameters manually) - or hyperopt to do this automatically.

Applying this to dry-run is not possible (it's also unclear WHAT you're trying to analyze in the first place).
the used parameters are visible in the logs (when the strategy is loaded) - so they should be available for you to replicate.

**Comment by stash86** [comment]
What you need to do first is check whether a backtest over same period of your dry/live bot gonna give similar result. When you have similar result, then you can use backtest to test different values of params as much as you want.

Other than that, there is no analyze to be done, because you can't predict what happened with your dry run if you change value of A just based of your dry run results

**Comment by tomjrtsmith** [comment]
Ah, I think that is the bit I was looking for. Thanks Stefano.
