### ISSUE TITLE
doubt on funding fees calculation

### ISSUE THREAD

**Issue by italodamato** [freqtrade/freqtrade#7969]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I have a doubt about the fund fees calculation as I believe the fund rate gets charged depending on the direction of the trade. Specifically, long positions get charged when the funding rate is positive and vice versa. I believe the calculation should be the following: https://github.com/freqtrade/freqtrade/commit/12aabde7cd1c470f2d2384c812aff835af5f2ede

Some reference articles 
https://www.bybit.com/en-US/help-center/bybitHC_Article?id=000001056&language=en_US
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/45588475/210361156-ba614ee6-5ae6-4ac4-a999-6828f22a19c5.png">

https://www.binance.com/en/support/faq/introduction-to-binance-futures-funding-rates-360033525031
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/45588475/210361269-4ef3c9ab-aa98-4e56-a2e7-485763cfb97e.png">

**Comment by xmatthias** [comment]
You're not wrong with this - funding fees are trade direction dependent - and that's how they're applied in freqtrade.
your "fix" applies the direction twice (once on calculation, once on application) - and is therefore wrong - as this is already happening here:

the biggest mistake however is the removal of the "other" direction (through `clip()` in your commit) - as that way - you're ignoring fees you're receiving - which should also be factored in, impacting your result in a positive manner.

https://github.com/freqtrade/freqtrade/blob/91d8370909f59531fd0a768019d3704a61f23173/freqtrade/persistence/trade_model.py#L813C22-L820
