### ISSUE TITLE
Funding fee explodes with --timeframe-detail option

### ISSUE THREAD

**Issue by raphaelstar** [freqtrade/freqtrade#7978]
## Describe your environment

  * Operating system: linux
  * Python Version: 3.10 
  * CCXT version: 1.93.66 
  * Freqtrade Version: 2012.12 
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

The trade's funding fee is miscalculated in back-testing when trade adjustment is enabled and --timeframe-detail option is used.

The assumption made here:
https://github.com/freqtrade/freqtrade/blob/8e5b4750d64c265c138f14f420d79c39627afa75/freqtrade/persistence/trade_model.py#L204

doesn't hold true when using --timeframe-detail because `is_first` is not always True here:
https://github.com/freqtrade/freqtrade/blob/8e5b4750d64c265c138f14f420d79c39627afa75/freqtrade/optimize/backtesting.py#L699

This results in wrong calculation of the funding fees and produces overflow in trades with many adjustments.

**Comment by xmatthias** [comment]
For us to look at - please don't provide your conclusion - but something to actually look at - so we can reproduce it.

This can be logs (if you see this it in logs) - a minimal strategy that reproduces the problem (including a hint where you see it's shown, ...).

> doesn't hold true when using --timeframe-detail because is_first is not always True here:

at a first glance, i disagree with this (keep in mind, no data to actually look at, so this is theoretical only). 
`close_bt_order()` is called whenever an order closes. This has nothing to do with the timeframe (base or detail). It's irrelevant if the order fills at 10:00 or 10:30. it'll impact the fees - but not the calculation of it, as each individual order will only close exactly once.


--- 

asside from that - you should make sure to follow the [updating guideline](https://www.freqtrade.io/en/latest/updating/).
Your ccxt version seems outdated by several versions - and is clearly misaligned with 2022.12.

**Comment by raphaelstar** [comment]
This line, where the order funding fee value is set:
https://github.com/freqtrade/freqtrade/blob/8e5b4750d64c265c138f14f420d79c39627afa75/freqtrade/persistence/trade_model.py#L205

Assumes `trade.funding_fees` has been computed from this line:
https://github.com/freqtrade/freqtrade/blob/8e5b4750d64c265c138f14f420d79c39627afa75/freqtrade/optimize/backtesting.py#L700

As per the comment:
https://github.com/freqtrade/freqtrade/blob/8e5b4750d64c265c138f14f420d79c39627afa75/freqtrade/persistence/trade_model.py#L204

But when using timeframe details, the variable `is_first` becomes false as shown here:
https://github.com/freqtrade/freqtrade/blob/8e5b4750d64c265c138f14f420d79c39627afa75/freqtrade/optimize/backtesting.py#L1194

This result in `trade.funding_fees` being calculated from orders funding fee instead in `recalc_trade_from_orders`:
https://github.com/freqtrade/freqtrade/blob/8e5b4750d64c265c138f14f420d79c39627afa75/freqtrade/persistence/trade_model.py#L892

This creates a feedback loop where `order.funding_fee` is updated with `trade.funding_fees`, `trade.funding_fees` itself being set to the sum of all orders `order.funding_fee`, etc... the funding fee for the trade explodes.

Step to reproduce:
A strategy on futures making trades with adjustments happening on timeframe details time steps.

Side note:
This line:
https://github.com/freqtrade/freqtrade/blob/8e5b4750d64c265c138f14f420d79c39627afa75/freqtrade/persistence/trade_model.py#L910
is shadowed by this line:
https://github.com/freqtrade/freqtrade/blob/8e5b4750d64c265c138f14f420d79c39627afa75/freqtrade/persistence/trade_model.py#L922

**Comment by xmatthias** [comment]
>is shadowed by this line:

this is correct and intentional as is, since the functions that are called between these are using these partial fees.

---

As mentioned above - please provide a **reproducible example** (best a minimal strategy that causes this - with the command used to run it) for us to investigate.

As you've clearly reproduced this, you will have this readily available. 
It'll therefore  waste our time to reproduce the exact scenario where you're seeing this.


---

You're obviously also free to submit a PR fixing this issue (Which will however also have to contain some sample strategy that allows us to reproduce this).

**Comment by xmatthias** [comment]
I've tried to recreate this now - but the strategy i used (3x rebuys per trade, ...) to test this didn't cause what you're claiming.

with and without `--timeframe-detail`, the funding-fees are identical (obviously unless the trade duration changes, where they're very slightly higher/lower in some instances - but nothing that wouldn't be expected).

As such - i cannot really confirm that what you're claiming is happening.
maybe it needs some very special scenario / combination in the strategy for this to happen - (which is where the reproducible example comes in).

For now (pending a reproducible example) - i don't see what you're seeing.

**Comment by xmatthias** [comment]
@raphaelstar any news on the reproduction?

**Comment by raphaelstar** [comment]
Hi, here is the reproduction procedure (tested on develop branch `cd2a41e76e9847383d3b14099a76a1df4204bf5a`) :

**config.json**
```json 
{
    "max_open_trades": 1,
    "stake_currency": "USDT",
    "stake_amount": 100,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "5m",
    "dry_run": true,
    "dry_run_wallet": 1000000,
    "position_adjustment_enable": true,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "okx",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
          "LTC/USDT:USDT"
        ],
        "pair_blacklist": [
        ]
    },
    "pairlists": [
      {
        "method": "StaticPairList"
      }
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": false,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "5aa0bcb1cce1dfa0f789dd0b573998e4856f66a55c2d14192deb7613f9a9845b",
        "ws_token": "GP3YNhFO47R_J0o7iix9R5xL5HhQLaapPw",
        "CORS_origins": [],
        "username": "",
        "password": ""
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }

```
**sample_strategy.py**

```python
# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement
# flake8: noqa: F401
# isort: skip_file
# --- Do not remove these libs ---
import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame
from typing import Optional, Union

from freqtrade.strategy import (BooleanParameter, CategoricalParameter, DecimalParameter,
                                IStrategy, IntParameter)

# --------------------------------
# Add your lib to import here
import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib


# This class is a sample. Feel free to customize it.
class SampleStrategy(IStrategy):
    INTERFACE_VERSION = 3

    can_short: bool = False
    minimal_roi = {
        "600000": -1
    }
    stoploss = -1.0
    # Trailing stoploss
    trailing_stop = False
    timeframe = '5m'
    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = True

    # These values can be overridden in the config.
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 30

    # Optional order type mapping.
    order_types = {
        'entry': 'limit',
        'exit': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }

    # Optional order time in force.
    order_time_in_force = {
        'entry': 'GTC',
        'exit': 'GTC'
    }

    def informative_pairs(self):
        return []

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            :,
            'enter_long'] = 1

        dataframe.loc[
            :,
            'enter_short'] = 0

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            :,

            'exit_long'] = 0

        dataframe.loc[
            :,
            'exit_short'] = 1

        return dataframe

    def adjust_trade_position(self, trade, current_time,
                              current_rate: float, current_profit: float,
                              min_stake: Optional[float], max_stake: float,
                              current_entry_rate: float,
                              current_exit_rate: float,
                              current_entry_profit: float,
                              current_exit_profit: float, **kwargs) -> Optional[
      float]:
      print(current_time, "profit", current_profit)
      return 100
```

Commands:
`freqtrade download-data --config config.json --days=40 -t 1m`

`freqtrade backtesting --config config.json --strategy-path user_data/strategies --strategy SampleStrategy --timeframe 5m --timeframe-detail 1m --cache none --timerange=20221219-20221220`

Output:
```
...
2022-12-19 23:56:00+00:00 profit -3.572903498646509e+225
2022-12-19 23:57:00+00:00 profit -7.140814563254032e+225
2022-12-19 23:58:00+00:00 profit -1.4271659775920735e+226
2022-12-19 23:59:00+00:00 profit -2.852340237530208e+226
2022-12-20 00:00:00+00:00 profit 0.00188886
2023-01-19 10:01:42,232 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "****/projects/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "****/projects/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "****/projects/freqtrade/freqtrade/optimize/backtesting.py", line 1348, in start
    results = generate_backtest_stats(
  File "****/projects/freqtrade/freqtrade/optimize/optimize_reports.py", line 575, in generate_backtest_stats
    strat_stats = generate_strategy_stats(pairlist, strategy, content,
  File "****/projects/freqtrade/freqtrade/optimize/optimize_reports.py", line 451, in generate_strategy_stats
    'cagr': calculate_cagr(backtest_days, start_balance, content['final_balance']),
  File "****/projects/freqtrade/freqtrade/data/metrics.py", line 194, in calculate_cagr
    return (final_balance / starting_balance) ** (1 / (days_passed / 365)) - 1
OverflowError: (34, 'Numerical result out of range')

```

**Comment by xmatthias** [comment]
quite a nice find - thanks for the reproduction, that helped a lot  :+1:

**Comment by raphaelstar** [comment]
> quite a nice find - thanks for the reproduction, that helped a lot +1

Thanks, glad it helped!
Unfortunately the fix makes the backtesting much slower, is there a better approach?

**Comment by xmatthias** [comment]
not really, no (at least i'd not know one for now).

if you have multiple orders within one (main) candle - then no.

I've thought about this for quite some time - as i didn't like the fix (as i was aware that it'll increase backtesting time for certain scenarios) - all ideas i had for other fixes are too error-prone.

i guess in theory, it would be possible to compute the time diff between the last 2 orders - and fix this elsewhere (e.g. move fees only to the first order within one main candle).
it would introduce other edge-cases where this isn't fixed (for example if the main timeframe is > funding fee period - or if the order is placed in one long candle, but fills 2 long candles later, ...).

It'd also require not so straightforward logic (involving quite some date math) - so it's questionable if that would improve performance by much.

---

From my expectation, it'll only impact strategies which have positions open most of the time (where backtesting is implicitly slower already). 
strategies that trade rarely will not be impacted by this at all.
