### ISSUE TITLE
Is there a way to run a piece of code after bot stops in backtesting

### ISSUE THREAD

**Issue by infoginx** [freqtrade/freqtrade#7984]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.10.2
  * Freqtrade Version:   docker-2023.1.dev-798438df
  
## Your question

I have a piece of code that generates some plots. I want to run that function after strategy backtesting finishes. Is there a callback just like bot_start() which allows me to run a code after backtesting finishes using 'freqtrade backtesting --strategy MyStratClass'?

**Comment by xmatthias** [comment]
no there is not. That'd be a pretty pointless callback (only available to backtesting - tailored to a very specific need).

in backtesting (unless you use webserver mode) - the freqtrade process will exit - so you can basically use something around `freqtrade backtesting <...> && <yourcustomcomand>` - to execute them in sequence.

**Comment by ks228** [comment]
Thanks @xmatthias
