### ISSUE TITLE
New function after trade is open and another after trade is closed.

### ISSUE THREAD

**Issue by adsjr1** [freqtrade/freqtrade#7986]
In some strategies I need to execute actions after a trade is confirmed to be opened and after a trade is confirmed to be closed.

In my specific case, I was creating a table of take profit levels based on the trade open rate. This can only be accurate after receiving confirmation of an entry fill.

Similarly, I need to reset some parameters after a trade is closed and a trade can only be confirmed as closed after a response from the exchange. Many times I see limit orders that time out so trade is not yet confirmed and can lead to inaccuracies.

Before submitting this request I asked in the discord chat
[https://discord.com/channels/700048804539400213/702584639063064586/1059624290053521418]

**Comment by stash86** [comment]
You can always use custom_exit or custom_stoploss as the place to calculate such table. And you can store the trade info in a dict, then when do check on bot_loop_start whether that trade is still open or not

**Comment by adsjr1** [comment]
The table is created at the moment the trade is confirmed to be open. How would creating a table in custom_exit, which is associated with closing the trade, would help?
I don't use custom_stoploss function because of the lack of flexibility with its fixed percentage, but this is a separate discussion. In any case, custom exit or custom stoploss are functions called before the order is submitted. What if the order times out? The ask is to have a function called after the order is confirmed as filled.

**Comment by stash86** [comment]
all you want to create the table only after the trade is open, right? custom_exit or custom_stoploss only entered once the trade confirmed to be open, so it fit your need. I don't see why it won't work

**Comment by stash86** [comment]
and regarding the exit part, as said above, use bot_loop_start

**Comment by adsjr1** [comment]
Ok. Now I see your point. Thanks!
