### ISSUE TITLE
freqtrade.rpc.api_server.ws.channel - INFO - Disconnected from channel - WebSocketChannel

### ISSUE THREAD

**Issue by MohamedDhouib** [freqtrade/freqtrade#7992]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.10.6 (`python -V`)
  * CCXT version: 2.5.51 (pip freeze | grep ccxt)
  * Freqtrade Version: freqtrade 2022.12 

## Describe the problem:

I'm on an EC2 t2.micro AWS Machine and i have deployed a 5min freqtrade dry run strategy. I have the excact same strategy on my computer running for several days and I didn't had an issue with it. But the dry run bot on AWS is having an impotant delay due to this error:

freqtrade.rpc.api_server.ws.channel - INFO - Disconnected from channel - WebSocketChannel

I have no idea why but i guess that's related to the config to the aws server? or maybe the size of the the server?
The error is quit regular, like every 5min it would occur.

### Steps to reproduce:

  1. Run bot on T2.micro EC2 server
  

### Relevant code exceptions or logs

  ```
freqtrade    | 2023-01-08 22:34:11,334 - freqtrade.rpc.api_server.ws.channel - INFO - Disconnected from channel - WebSocketChannel(xxx, ('xxx', xxx))
freqtrade    | 2023-01-08 22:34:11,335 - uvicorn.error - INFO - connection closed
freqtrade    | 2023-01-08 22:34:12,773 - uvicorn.error - INFO - ('xxx', xxx) - "WebSocket /api/v1/message/ws?token=xxx" [accepted]
freqtrade    | 2023-01-08 22:34:12,774 - freqtrade.rpc.api_server.ws.channel - INFO - Connected to channel - WebSocketChannel(xxx, ('xxx', xxx))
freqtrade    | 2023-01-08 22:34:12,893 - uvicorn.error - INFO - connection open
  ```

**Comment by stash86** [comment]
Any lag isn't due to that, but the fact that AWS t2.micro is just bad

**Comment by MohamedDhouib** [comment]
In that case what is the minimum required to run it on an asw server without an issue?

**Comment by stash86** [comment]
well it all depends on your strategy. Look at the heartbeat prints on the log, esp on the timeframe interval. It should be (more or less) printed on 1m intervals. If you see more than 1 min interval, esp if you are on 5m timeframe, then you would need to use better tier.

I don't use AWS, so I can't comment, but from what I heard, their low tiers are bad.

**Comment by MohamedDhouib** [comment]
Ok ok, thank you very much. Yes my strategy is on a 5min timeframe. What is the minimum ram/processor power required for a 5min strategy? 4gb? or is a 2gb enough?

**Comment by stash86** [comment]
again, it's depends on your strategy and how much bots you run. Check the usage of memory

**Comment by xmatthias** [comment]
Unless you're using producer/consumer mode (i assume you're not for now) - this message might also mean nothing.

The UI connects to the bot via websockets - every time you close the webpage, you might get this message.
obviously, you could also get the same message if the vps is at 100% cpu, as the server is then not able to respond to ping's.
this can be a sign of problems - but it can just as well just be a sign of "i closed the UI tab".

---

a T2.micro has different problems - at 1gb ram with 1 vcpu, that 1 cpu will be busy whenever it's calculating indicators (so the bot won't be responding to anything else).
We recommend at least 2 vcpu's  - as well as 2 gb ram (more if the strategy is "heavy" - uses a ton of indicators). 

While a limited amount of very lightweight strategies (only very few indicators - which are very efficient to calculate) might be able to run on lower tier machines (less memory) - but with 1 vcpu you'll never be happy i think - it's not something we can support.
