### ISSUE TITLE
New variable in Strategy class that can be changed via telegram when bot is running

### ISSUE THREAD

**Issue by dobremha** [freqtrade/freqtrade#8011]
Variable name :
market_direction = "long" , "short" , ("even" or "side" - one of these 2, which you think fits better as description when market doesn't have a clear direction) 
Default startup value will be set in the strategy class, with one of the above 3 parameter.

Access and change value (in running instance) via telegram through command:
/marketdir long
/marketdir short
/marketdir side
so methods that will use market_direction or self.market_direction variable will get the updated (via telegram) value.

This will allow to easy change strategy behavior from phone when you don't have access to PC, when market condition are changing.

**Comment by xmatthias** [comment]
while i understand the intend - i don't think that's something we'll be adding / implementing - at least not anytime soon.

The way you propose fits exactly your needs (which is understandable) - but i don't see that generalize well for most strategies.

it will be too restricted for most usecases (maybe i'd like to change this more fain-grained), or a pointless feature for most others.

If any - it'll be strategy parameters that can be modified remotely - though not via telegram, but via the UI (it's way too complex to use through telegram efficiently).

**Comment by dobremha** [comment]
I don't agree with your statements about utility of this feature; but if you exclude telegram usage for it from the start, it makes no sense for me to debate about benefits of this feature.

**Comment by moinonin** [comment]
I see the benefit of that feature. There are times the market direction changes suddenly and you just wish you could switch the strategy that has worked well in a certain direction. This particularly because it is kinda difficult to find a balanced strategy that works in both directions.

**Comment by xmatthias** [comment]
You think it's beneficial - but you'll soon discover how limited it is - and find it effectively useless as it won't cover most cases.
It's a variable with 2 values - 90% of the strategies will want more.

It's also something that cannot be tested upfront - so all strategies using that will automatically fly blind (you can't rely on backtests for strategies that use this).

I've marked it as "good first issue" for now - so i'm happy to get a Pull Request for it - but i'll definitely not look at this myself - and will close this issue if we're not getting a PR (which someone also intends to finish) within a 3 months - as i'll read that as "there is no interest".

**Comment by dobremha** [comment]
it would be an easy and safe way to make a change inside a running strategy when you don't have a PC available...the limitation depends on each skill to build around it...like all other methods and parameters

**Comment by froggleston** [comment]
It could be argued that "market_direction" isn't a "real" thing. It's a value based on a human hunch or external information, and it should presumably be better served by TA or some other quantitative indicator. I see other problems with it, e.g. you forget that you changed it from long to short and bad trades start to happen. Making changes to something as complex as a running strategy without easy access to a PC sounds dangerous to me.

**Comment by dobremha** [comment]
Then you should not use it. It's not mandatory. Should not affect actual strategies that people are using.
All other methods and parameter have same problem..if used wrong..you get bad trades.

**Comment by LangLazy** [comment]
Hey! 

I'm new to open source and would like to take on this issue. Is it currently open?

**Comment by xmatthias** [comment]
sure is, feel free to give it a go.

**Comment by LangLazy** [comment]
I am confirming some things to ensure I'm on the right track. I've added a new var to the `interface.py` file which keeps track of the market direction, is this the correct place to do this? Also, I have added a new enum type to signify the market direction. Currently, I have 4 values of the enum which map to "long", "short", "even", and "none". I think a "none" option should be included, as setting any of the other values as the default seems wrong as they may not apply to the user and the market state at the time.

**Comment by xmatthias** [comment]
>  I've added a new var to the interface.py file which keeps track of the market direction, is this the correct place to do this

probably yes - you should however be VERY careful with naming - as freqtrade will NOT automatically determine / assign this - and i'd want this to become VERY clear from the variable naming.

I'd leave the rest to you for now ... the best thing will be to look at what you got - then we can comment per line :)
