### ISSUE TITLE
Roi and timeout cancels

### ISSUE THREAD

**Issue by Junumboxo** [freqtrade/freqtrade#8012]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.10.6 (`python -V`)
  * CCXT version: 1.93.98 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade docker-f9460c80 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I was playing around with different values of `unfilledtimeout` for both entry and exit in the config file. The docs says that after the timeout is reached, the order will be cancelled and repeated at current (new) price, as long as **there is a signal.** The question is how do we handle a situation if an exit was triggered by roi and then cancelled due to timeout? Since roi, as I understand it, is not an exit singnal in itself. How can we place another order? I thought either of `unfilledtimeout.exit_timeout_count` or of `custom_exit()` or other callbacks, but would appreciate any ideas.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Well it's a simplified description, really - depending on how you define "signal".

A canceled order simply returns the bot to "regular" state - after which all signas are evaluated again.
If a signal is still there (either a normal, candle based signal, or a roi/stoploss state) - then a new order is placed (most likely at a new price).

as such - ROI is also signal (as is a stoploss - once price crossed the stop) - but not one you control yourself, but one that's automatically set evaluated based on price. - which is automatically triggered if price is > X.

If price is still > X - the signal will still be present and a new order will be placed.

Obviously if price dropped below X again, the signal is gone, so the order won't be placed again.

`exit_timeout_count` could be used to some extend - but it'll result in an emergency sell (usually a market order) - so you shouldn't exclusively rely on this unless that's what you want.
