### ISSUE TITLE
adjust_entry_price callback always cancels open orders even if no price change happen inside this method

### ISSUE THREAD

**Issue by dobremha** [freqtrade/freqtrade#8013]
## Describe your environment
Operating system: Ubuntu 22.04 LTS
Python Version: 3.10.6
CCXT version: 2.0.58
Freqtrade Version: 2022.11
Freqtrade running in docker

## Describe the problem:

Why after calling adjust_entry_price callback and returning current_order_rate (so no change in price from prev. call), open order is still canceled and a new order with same price is created.
Can't be good regarding exchange traffic to create and cancel hundreds of orders every minute unnecessary, if I run a config with 100 open trades for ex.

And a lot of telegram messages if "entry_cancel": "silent" or "entry_cancel": "on" even only for 1 trade.

Log attached.
[adjprice.txt](https://github.com/freqtrade/freqtrade/files/10418662/adjprice.txt)

**Comment by xmatthias** [comment]
i think you'll need to be careful with what you are returning and assuming as "same price".

assuming the `FuturesLongDcaDry` log entries are what is actually returned - then:
`2023-01-14 18:56:33,872 - FuturesLongDcaDry - INFO - >>ADJ_ENTRY_PRICE_1 APT/USDT : 7.4872805`

i assume 7.4872805 is returned. 

This is a price that no order will ever be placed at APT/USDT.
That market is limited to 4 decimals - therefore your price is automatically different from the order price.
Since the price is different (even if only slightly) - freqtrade will replace the order (which is what you requested - but by looking at this issue - not intended).

you can pretty easily test this with `return current_order_rate`  - which will return the "rounded" price - after which the order isn't created again.

**Comment by dobremha** [comment]
Thanks, I can round the number to needed digits ............ but different pair's have different digit numbers. How can I get what digit size is needed for current pair ?
EGLD/USDT 40.12 - "2  digit's"
APT/USDT 7.5323 - "4  digit's" 
DOGE/USDT 0.08591 -  "5  digit's" 
and so on.

.........
I figured it out by myself , I will try to check current_order_rate for how many digit's the pair have. If it's more I try to cut all "0" from the end.

**Comment by xmatthias** [comment]
you can't (and the strategy shouldn't worry about such details).

i think your intend is to not modify the price - so `return current_order_rate` is the correct approach

> Returning current_order_rate will keep the order on the exchange "as is". Returning any other price will cancel the existing order, and replace it with a new order.

[source](https://www.freqtrade.io/en/latest/strategy-callbacks/#adjust-entry-price)

**Comment by dobremha** [comment]
what is the point of this method if you **always** return current_order_rate unchanged ?

**Comment by xmatthias** [comment]
well you shouldn't.

If you intend to keep the price the same (which your intend seems to have been in your question / logs) - then you return current_order_rate.
if you need the price changed (via whatever logic you use) - you return a different price - which the order will then be changed to.

**Comment by dobremha** [comment]
I change the price for my DCA order (limit), in this case only 1 DCA order. 
My problem was that it didn't cancel the order only once when price was changed , but a thousand times after that although price remains unchanged, until order is fulfilled or canceled (timeout). Now it's working fine after hint from you with digit number.

    def adjust_entry_price(self, trade: Trade, order: Order, pair: str,
                           current_time: datetime, proposed_rate: float, current_order_rate: float,
                           entry_tag: str, side: str, **kwargs) -> float:

        count_of_buys = len(trade.select_filled_orders('buy'))
        
        if count_of_buys != 1:
            return current_order_rate

        price_last_buy = trade.select_filled_orders('buy')[-1].price
        new_price = price_last_buy - price_last_buy * 1.5 / 100
        # Get the number of digits after the decimal point of current_order_rate
        with localcontext() as ctx:
            ctx.prec = len(str(current_order_rate).split('.')[1])
            new_price = round(new_price, ctx.prec)

        if count_of_buys == 1 and trade.nr_of_successful_exits == 0:
            logger.info(f">>ADJ_ENTRY_PRICE_{count_of_buys} {pair} : {new_price}")
            return new_price
        else:
            return current_order_rate

**Comment by xmatthias** [comment]
i ... don't think your way actually works - at least not correctly.

you could accidentally place the initial DOGE order at 0.0800000 - so your precision will be 2 decimals - but that doesn't mean that the next possible step is 0.09 or 0.07.

Instead, you should compare the existing and newly created price - and only return the changed price if it changed by a big enough margin.

i doubt that you'll want to place a new DOGE order at 0.08592 if the prior price was 0.08591 a few seconds ago (so the calculated change is 1 tick). 
you'll instead want to replace the order if it changed by X% between the prior price and the current price - to actually have the change be "worth it".

**Comment by dobremha** [comment]
It's working..even if i place a 0.08 limit order my realized price will be different. I already have some (around 10) orders in dry mode and price is ok.
Trigger is exactly how you have described, but in adjust_trade_position, not here.
