### ISSUE TITLE
Binance futures upgrade doesn't appear to work

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#8032]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

This is using the precision filter so no static whitelist or blacklist. I don't know where else in my config I could change anything?

an 16 19:07:04 instance-20221009-1127 freqtrade_a[756827]: 2023-01-16 19:07:04,742 - SpreadFilter - INFO - Removed 1INCH/USDT:USDT from whitelist due to invalid ticker data: {'symbol': '1INCH/USDT:USDT', 'timestamp': 1673895994601, 'datetime': '2023-01-16T19:06:34.601Z', 'high': 0.5116, 'low': 0.4701, 'bid': None, 'bidVolume': None, 'ask': None, 'askVolume': None, 'vwap': 0.4932, 'open': 0.497, 'close': 0.4876, 'last': 0.4876, 'previousClose': None, 'change': -0.0094, 'percentage': -1.891, 'average': 0.4923, 'baseVolume': 77921114.0, 'quoteVolume': 38427076.89, 'info': {'symbol': '1INCHUSDT', 'priceChange': '-0.0094', 'priceChangePercent': '-1.891', 'weightedAvgPrice': '0.4932', 'lastPrice': '0.4876', 'lastQty': '204', 'openPrice': '0.4970', 'highPrice': '0.5116', 'lowPrice': '0.4701', 'volume': '77921114', 'quoteVolume': '38427076.8900', 'openTime': '1673809560000', 'closeTime': '1673895994601', 'firstId': '218359312', 'lastId': '218496048', 'count': '136737'}}

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
Spreadfilter is using the `fetch_tickers()` method - which results in quite incomplete data on binance futures (their futures API doesn't provide the data in this format).

this will have never worked - as the result didn't really change any more than the symbol. 
(i've just tested the same call on a non-updated ccxt version, and got the same result).

```
{'symbol': '1INCH/USDT',
 'timestamp': 1673896862361,
 'datetime': '2023-01-16T19:21:02.361Z',
 'high': 0.5116,
 'low': 0.4701,
 'bid': None,
 'bidVolume': None,
 'ask': None,
 'askVolume': None,
 'vwap': 0.4931,
 'open': 0.4976,
 'close': 0.4857,
 'last': 0.4857,
 'previousClose': None,
 'change': -0.0119,
 'percentage': -2.391,
 'average': 0.49165,
 'baseVolume': 78365223.0,
 'quoteVolume': 38638121.49,
 'info': {'symbol': '1INCHUSDT',
  'priceChange': '-0.0119',
  'priceChangePercent': '-2.391',
  'weightedAvgPrice': '0.4931',
  'lastPrice': '0.4857',
  'lastQty': '987',
  'openPrice': '0.4976',
  'highPrice': '0.5116',
  'lowPrice': '0.4701',
  'volume': '78365223',
  'quoteVolume': '38638121.4900',
  'openTime': '1673810460000',
  'closeTime': '1673896862361',
  'firstId': '218360166',
  'lastId': '218497652',
  'count': '137487'}}

```

Note that both on your and my result, bid/ask are empty - which are required settings for SpreadFilter to work.

**Comment by tomjrtsmith** [comment]
So what is the solution? Is there a way for Spreadfilter to call the data?
Do I need to move to static pairlists?

**Comment by xmatthias** [comment]
i did some more tests, and found what's missing (it's "old" responses from ccxt on one endpoint).

For now, best remove `SpreadFilter` from your configuration to work around this issue (shouldn't prevent you from using a regular VolumePairlist though).

We'll work on getting this back - and will update / close this issue once it's functional again.

**Comment by tomjrtsmith** [comment]
So are Binance futures going to stop anytime soon on bots that are running?

**Comment by xmatthias** [comment]
Spreadfilter (and other filters using tickers data) will be workig again with the latest update.
