### ISSUE TITLE
docker hyperopt and data-download

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#8037]
## Describe your environment

  * Operating system: docker
  * Python Version: _____ 3.8.10
  * CCXT version: _____ no output from 'pip freeze | grep ccxt'
  * Freqtrade Version: ____ 2022.12
  
## Your question
I am trying to download data https://www.freqtrade.io/en/stable/data-download/ using a .json pair list, but there is no download, i can only download when specifying the pairs in the command line. 

tetsing freqtrade hyperopts but it seems to change my stoploss and 'minimal_roi box' as it appears to be different in the command line output than in the strategy file, even though it does seem to be choosing the correct strategy file. Also, trailing_stop is set to 'true' in the strategy file although it appears false in the command output.

2023-01-19 18:45:56,485 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
whereas in the strategy .py file :
Trailing stoploss
trailing_stop = True

 I am not specifying 'minimal roi', 'stop loss' and 'trailing stop' in the config file, only in the .py strategy file

**Comment by stash86** [comment]
write the command you were using to download the data

**Comment by xmatthias** [comment]
On top of the download data command used - we'll also need some more logs.

one line won't tell us anything - but the full startup logs will contain details as to what was loaded from the configuration and what wasn't.

**Comment by ghost** [comment]
do you mind if I follow it up in the discord server?

**Comment by xmatthias** [comment]
absolutely not.
discord is ... a lot more interactive when it comes to back and forth questions.
That's what the community is for :)

**Comment by ghost** [comment]
thanks!

**Comment by xmatthias** [comment]
Closing this, as the discussion was moved to discord.
