### ISSUE TITLE
Price difference in result from trade.select_filled_orders('buy')[-1].price

### ISSUE THREAD

**Issue by dobremha** [freqtrade/freqtrade#8042]
Describe your environment
Operating system: Ubuntu 22.04.1 LTS
Python Version: 3.10.6
Freqtrade 2022.11
CCXT 2.1.96
Freqtrade running in docker : docker-compose up -d
Echange: Binance

Dont know if this is a bug or issue in my code but I get a different price from trade.select_filled_orders('buy')[-1].price:

2023-01-22 03:31:42,322 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=95, pair=WOO/USDT, amount=1223.00000000, is_short=False, leverage=5.0, open_rate=**0.20625000**, open_since=2023-01-21 22:28:45)

def adjust_trade_position...
price_last_buy = trade.select_filled_orders('buy')[-1].price
price_last_buy is printed as **0.20432** in logger

I have only 1 buy (count_of_buys = len(trade.select_filled_orders('buy')) is 1) in this trade

**Comment by xmatthias** [comment]
please be a bit more specific on what you're doing exactly (more specifically, which mode freqtrade is running in).

is this dry-run? live? backtesting?

**Comment by dobremha** [comment]
Dry-run.

**Comment by xmatthias** [comment]
the price of an order corresponds to the price you placed the order at (not necessarily where it filled).
Based on the above prices - i assume you're using market orders - which can potentially push the price (which freqtrade tries to follow).

the trade's `open_rate` will correspond to the order's `average`.

Now average can go both ways - in case of limit buy orders, it'll be "price or lower" - and in case of market orders usually, price or higher (depending on size, orderbook volumes...).


this is also listed in the [trade object](https://www.freqtrade.io/en/stable/trade-object/#order-available-attributes) documentation.

**Comment by dobremha** [comment]
I see this as a issue on "market", but much more in "limit" orders where I get big differences.
It's important to know the mid price at which an order has been filled (assuming it's split in more chunks), not initially posted price.
When using "market" orders difference (posted vs filled) are negligible (I have checked hundreds of examples futures and spot - and values are correct), but width "limit" I get up to 1% difference.

**Comment by xmatthias** [comment]
Fill prices in dry-run will depend on how you're pricing your orders (just as it would in real trades).

i'm however not entirely sure what your point is with this last comment.

what's preventing you from using `.average`  (with the same logic)? it'll contain the fill price - (or nothing - if the order is still open / didn't fill yet).

**Comment by dobremha** [comment]
Thanks, somehow I didn't see this in the documentation.
