### ISSUE TITLE
Post Only Orders - Binance

### ISSUE THREAD

**Issue by alisalama** [freqtrade/freqtrade#8044]
## Describe your environment

  * Operating system: Mac OS Monterey
  * Python Version: 3.9.7
  * CCXT version:  2.6.39
  * Freqtrade Version: docker-2023.1.dev-95987663

## Describe the enhancement

Hi Matthias,

Is it possible to add the Post Only order type to Binance? It looks like it is already there in CCXT (https://github.com/ccxt/ccxt/blob/4f601bf7f1c8090889d493f4e483767bd838afe4/python/ccxt/binance.py#L3253).

Similar to this previously requested one on FTX (https://github.com/freqtrade/freqtrade/issues/7175), so hopefully similar solution.

Thanks,
Ali

**Comment by xmatthias** [comment]
ccxt doesn't fully support Post Only orders for binance yet (see linked issue) - therefore this won't be possible at this point (https://github.com/ccxt/ccxt/issues/14742).

I'll keep this around for about a week - if there's no response to that issue by then, i'll close this and would ask you to subscribe to the ccxt issue for updates.

**Comment by alisalama** [comment]
Hi Mattthias,  Thanks for chasing up with ccxt guys. Does this not fix the issue? https://github.com/ccxt/ccxt/pull/16508

**Comment by xmatthias** [comment]
no

**Comment by xmatthias** [comment]
We've implemented a workaround for this for now. 
it should be noted that binance only supports post-only orders on spot - but on futures, there's no such functionality. As such - we've followed that approach as well.
