### ISSUE TITLE
Cancel stoploss_on_exchange after the position is closed

### ISSUE THREAD

**Issue by dpuyosa** [freqtrade/freqtrade#8045]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: Python 3.10.7
  * CCXT version: 2.6.47
  * Freqtrade Version: docker-2023.1.dev-81349c2a
  
## Describe the problem:
When the bot generates an exit signal it creates a limit exit and directly cancels the stoploss on the exchange. The stoploss should be in place until the position is closed.

**Comment by xmatthias** [comment]
while this sounds sensible in theory - it's unfortunately, that's not possible on all exchanges i've tested so far.

taking binance as example (as the most popular exchange):
A stoploss order ties up the amount the stoploss is for ( -> the full stake amount) - so the moment a stoploss is placed, no limit order for the same amount can be placed, as both would try to tie up the same amount - resulting in the limit order placement to fail with "no free amount" (or whatever the wording will be).

it's therefore correct behavior to cancel the stoploss BEFORE the limit exit is placed.

**Comment by dpuyosa** [comment]
It is not possible to move the ``cancel_stoploss_on_exchange`` after checking ``confirm_trade_exit``? (Moving FreqtradeBot.py line 1563 to 1583)
Right now I get a loop of removing and placing the stoploss every 5 seconds until the exit is accepted. That is 100s of cancelled orders in the exchange log.
