### ISSUE TITLE
A pair appear both blacklist and whitelist

### ISSUE THREAD

**Issue by LeCmnGend** [freqtrade/freqtrade#8054]
## Describe your environment

  * Operating system: WSL2 on W10
  * Python Version:  3.10
  * CCXT version: ""
  * Freqtrade Version: newest by git pull
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1.  My config.json
https://pastebin.com/riv750Kc
  2. My blacklist pair
https://pastebin.com/GKbeGntW
 
### Observed Results:
I ran telegram bot command "/whitelist" and HBAR/USDT apear
then /blacklist and HBAR/USDT is still here too
  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
Blacklist will be ignored if there's a position for a pair.

If that's not the case - please provide us with the logs (the whitelist / blacklist added to the logs).
It's usually best to have the full startup logs.
Please don't use a 3rd party hosting service, but use github for that, either by wrapping it in tripple ticks (`) - or by uploading it as txt file to github.

Please note: `Freqtrade Version: newest by git pull` is NOT a valid version. That's something that can change within minutes - and doesn't tell us anything. Please use `freqtrade -V` to provide us with the real version of your bot.

**Comment by LeCmnGend** [comment]
yeah, thank you. it gone after order done. thank for your support
version='2023.1.dev-1e43154bc'
but i got new error when force close bot right after buy order open (not filled yet)
i have to remove 
        if 'timestamp' in order and order['timestamp'] is not None:
            self.order_date = datetime.fromtimestamp(order['timestamp'] / 1000, tz=timezone.utc)
to make it work again, when i change to 
            self.order_date = datetime.fromtimestamp(int(order['timestamp']) / 1000, tz=timezone.utc)
it show 
valueError: invalid literal for int() with base 10: '2023-01-23T13:16:17.499Z'

here is log
```
2023-01-23 21:21:29,740 - freqtrade.commands.trade_commands - ERROR - unsupported operand type(s) for /: 'str' and 'int'
2023-01-23 21:21:29,740 - freqtrade.commands.trade_commands - ERROR - Fatal exception!

Traceback (most recent call last):
  File "/root/tc/bot/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/root/tc/bot/freqtrade/worker.py", line 75, in run
    state = self._worker(old_state=state)
  File "/root/tc/bot/freqtrade/worker.py", line 96, in _worker
    self.freqtrade.startup()
  File "/root/tc/bot/freqtrade/freqtradebot.py", line 192, in startup
    self.startup_update_open_orders()
  File "/root/tc/bot/freqtrade/freqtradebot.py", line 348, in startup_update_open_orders
    self.update_trade_state(order.trade, order.order_id, fo,
  File "/root/tc/bot/freqtrade/freqtradebot.py", line 1758, in update_trade_state
    trade.update_order(order)
  File "/root/tc/bot/freqtrade/persistence/trade_model.py", line 744, in update_order
    Order.update_orders(self.orders, order)
  File "/root/tc/bot/freqtrade/persistence/trade_model.py", line 230, in update_orders
    oobj.update_from_ccxt_object(order)
  File "/root/tc/bot/freqtrade/persistence/trade_model.py", line 140, in update_from_ccxt_object
    self.order_date = int(datetime.fromtimestamp(order['timestamp'] / 1000, tz=timezone.utc))
TypeError: unsupported operand type(s) for /: 'str' and 'int' 
```

**Comment by LeCmnGend** [comment]
im in cctx Using CCXT 2.6.58

**Comment by xmatthias** [comment]
What's unclear now is if using version 2.6.58 fixed the last problem - or not ... ?

**Comment by LeCmnGend** [comment]
> What's unclear now is if using version 2.6.58 fixed the last problem - or not ... ?

Sorry for my English.
the pair appear bot white and black are fixed now. but the new problems appear when i update to 2.6.58

**Comment by xmatthias** [comment]
Yeah - that's been fixed in the "very latest" version ...
