### ISSUE TITLE
Display GMT in the nav bar of Frequi

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#8057]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

This is really born from looking at the open and close time of trades and then realising that I have to work out the time and date in GMT as that is what all the VPS's are set to. I thought it might be handy for everyone to display the servers time (which is usually GMT) in the nav bar or somewhere else handy.

**Comment by xmatthias** [comment]
GMT (or rather UTC) is the timezone the exchanges work at.
It's got little to do with the time of the VPS (other than for logs).

You can however control the time freqUI is showing you trades / charts in the settings - and should impact all visible dates (except the ones in logs).

![image](https://user-images.githubusercontent.com/5024695/214220800-3c41b34b-09bf-4f7f-850d-7f9c0ce7b279.png)

**Comment by tomjrtsmith** [comment]
Genius thankyou!
