### ISSUE TITLE
trying to make a braid filter indicator help

### ISSUE THREAD

**Issue by mathlabelle** [freqtrade/freqtrade#8060]
## Describe your environment

  * Operating system: __ubuntu__
  * Python Version: __3.10.06___ (`python -V`)
  * CCXT version: __ccxt==2.4.60___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade 2022.12__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        # # EMA - Exponential Moving Average
        # dataframe['ema21'] = ta.EMA(dataframe, timeperiod=21)
        # dataframe['ema50'] = ta.EMA(dataframe, timeperiod=50)
        dataframe['ema200'] = ta.EMA(dataframe, timeperiod=200)

        dataframe['atr']= tt.ATR(dataframe['high'], dataframe['low'], dataframe['close'],timeperiod=1)
        dataframe['upperband'] = ((dataframe['high'] + dataframe['low'])/2) + (2 * dataframe['atr'])
        dataframe['lowerband'] = ((dataframe['high'] + dataframe['low'])/2) - (2 * dataframe['atr'])
        
        dataframe['ema3'] = ta.EMA(dataframe['close'], timeperiod=3)
        dataframe['ema7'] = ta.EMA(dataframe['open'], timeperiod=7)
        dataframe['ema40'] = ta.EMA(dataframe, timeperiod=40)
        dataframe['max'] = max(max(dataframe['ema3'], dataframe['ema7']), dataframe['ema40'])
        dataframe['min']= min(min(dataframe['ema3'], dataframe['ema7']), dataframe['ema40'])
        dataframe['dif'] = dataframe['max'] -dataframe['min']
        dataframe['filter'] = tt.ATR(dataframe['high'], dataframe['low'], dataframe['close'],timeperiod=14) * 60 / 100
        dataframe['braidbuy'] =  dataframe['ema3'] > dataframe['ema7'] and dataframe['dif']> dataframe['filter']
        dataframe['braidsell']=dataframe['ema7'] > dataframe['ema40'] and dataframe['dif'] < dataframe['filter']

```
i get ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
anybody can help me. i also tryed with np.maximum but still doesn't work 
not sure how to add float -- fmax 

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
`dataframe['ema3'] > dataframe['ema7'] and dataframe['dif']> dataframe['filter']` is clearly wrong.
A quick pandas search will reveal that the correct syntax would be `(dataframe['ema3'] > dataframe['ema7']) && (dataframe['dif']> dataframe['filter'])`


this is (in principle) also described in the [dataframe docs](https://www.freqtrade.io/en/latest/strategy-customization/#dataframe) - though it doesn't exactly cover your case.

**Comment by mathlabelle** [comment]
thanks a lot.

**Comment by mathlabelle** [comment]
File "/home/mathieu/mathieu/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/home/mathieu/mathieu/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/home/mathieu/mathieu/freqtrade/freqtrade/optimize/backtesting.py", line 1336, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/home/mathieu/mathieu/freqtrade/freqtrade/optimize/backtesting.py", line 1237, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/home/mathieu/mathieu/freqtrade/freqtrade/strategy/interface.py", line 1203, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/home/mathieu/mathieu/freqtrade/freqtrade/strategy/interface.py", line 1203, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/home/mathieu/mathieu/freqtrade/freqtrade/strategy/interface.py", line 1221, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/mathieu/mathieu/freqtrade/user_data/strategies/test.py", line 164, in populate_indicators
    dataframe['max'] = max(max(dataframe['ema3'], dataframe['ema7']), dataframe['ema40'])
  File "/home/mathieu/mathieu/freqtrade/.env/lib/python3.10/site-packages/pandas/core/generic.py", line 1527, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

problem seems to come from the dataframe['max'] = max(max(dataframe['ema3'], dataframe['ema7']), dataframe['ema40'])

**Comment by xmatthias** [comment]
Please read the above linked doc section - and then research how to work with pandas.

You're using the builtin max (which is intended to be used on a value) on a series.

**Comment by mathlabelle** [comment]
am i on the right track? 
 a =pd.Series([dataframe['ema3'], dataframe['ema7']])
        b= a.max()
        c=pd.Series([dataframe['ema40'], b])
        dataframe['max']=c.max(skipna = True)
        e =pd.Series([dataframe['ema3'], dataframe['ema7']])
        f= e.min()
        g=pd.Series([dataframe['ema40'], f])
        dataframe['min']=g.min(skipna = True)

**Comment by xmatthias** [comment]
not really.
with pandas, you'll always need to consider which direction a function should be applied (maximum per column vs. maximum per row).

something around `df[['ema8', 'ema9', 'ema10']].max(axis=1)` should work - but it's best to always consult the documentation for things like this (and have a generic understanding on how pandas dataframes work).

**Comment by mathlabelle** [comment]
thanks a lot . have a good one
