### ISSUE TITLE
freqtrade.freqai.data_kitchen - INFO - dropped 20 training points due to NaNs in populated dataset 4319.

### ISSUE THREAD

**Issue by medenlin** [freqtrade/freqtrade#8061]
## Describe your environment

  * Operating system: Docker image
  * Python Version: Docker image
  * CCXT version: Docker image
  * Freqtrade Version: docker-2023.1.dev-bd913bc2
  
## Your question

I keep getting a message while FreqAI running:
```freqtrade.freqai.data_kitchen - INFO - dropped 20 training points due to NaNs in populated dataset 4319.```
I try to set a ```startup_candle_count``` parameter to 40 and to 80, but no effect.
If I set a ```label_period_candles``` to 30, then freqtrade says ```freqtrade.freqai.data_kitchen - INFO - dropped 30 training points due to NaNs in populated dataset 4319.```
Freqai running in dry-run mode on gateio exchange, using a sample config and strategy.
Why it happens?

**Comment by xmatthias** [comment]
Depending on the indicators (and pairs) used, this can happen (for example) on 0 volume candles (most prevalent on lower volume pairs) (happened to me as well).

The sample strategy has this calculation: `dataframe["volume"] / dataframe["volume"].rolling(period).mean()` - which divides / 0 in case of 0 volume candles - resulting in a NaN (iirc, for the whole rolling period).

It's slightly unfortunate that the message doesn't contain the pairname - as that would help look at the data in particular - but you'll see that looking through the pairs, you'll find one with 0 volume for sure (unless you're only using 2-3 pairs - which is unlikely, too).

**Comment by wagnercosta** [comment]
Another very likely cause is that these numbers are generated by your targets. Since you cannot look into the future, it is normal that the most recent candles are excluded because in the example strategy we used .shift(-) when defining the targets. 

```py
         dataframe["&-s_close"] = (
             dataframe["close"]
             .shift(-self.freqai_info["feature_parameters"]["label_period_candles"])
             .rolling(self.freqai_info["feature_parameters"]["label_period_candles"])
             .mean()
             / dataframe["close"]
             - 1
             )
```

An evidence is when you change `label_period_candles` the drop_numbers changes too. This is a normal behavior when you use `.shift(-n)` when defining a target.
