### ISSUE TITLE
 Asynchronous resampled_merge and resample_to_interval operation

### ISSUE THREAD

**Issue by bleriot14** [freqtrade/freqtrade#8064]
Operating system: Windows 10

Python Version: Python 3.10.4

CCXT version: ------

Freqtrade Version: 2022.9.1

I have searched all docs but I couldn't find the solution.
How can I sync 5m timeframe and 15m timeframe with `resampled_merge` and `resample_to_interval` functions. I can't merge `dataframe` and `dataframe_long `synchronous (I mean I want to see changes at 15:15, 15:30, 15:45 not at 15:20, 15:35, 15:50 )

```
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe_long = resample_to_interval(dataframe, 15)  # 240 = 4 * 60 = 4h
        df_shifted =  dataframe_long.shift()
        dataframe_long['ha_open'] = (df_shifted['open'] + df_shifted['close']) / 2
        dataframe_long['ha_close'] = (dataframe_long['open'] + dataframe_long['high'] + dataframe_long['low'] + dataframe_long['close']) / 4
        dataframe_long['ha_high'] = dataframe_long[['high', 'open', 'close']].max(axis=1)
        dataframe_long['ha_low'] = dataframe_long[['low', 'open', 'close']].min(axis=1)
        dataframe_long['dema20'] = ta.DEMA(dataframe_long['ha_close'], timeperiod=20)
        dataframe_long['dema30'] = ta.DEMA(dataframe_long['ha_close'], timeperiod=30)
        dataframe_long['dema100'] = ta.DEMA(dataframe_long['ha_close'], timeperiod=100)
        dataframe = resampled_merge(dataframe, dataframe_long, fill_na=True)
        dataframe['shifted_ema20'] = dataframe['resample_15_dema20'].shift()
        dataframe['fake_dema20'] = dataframe['resample_15_dema20'] - (2 * ((dataframe['close'] * 1/8 ) + (dataframe['resample_15_dema20'] * (1 - (1/8)))))

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the entry signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with entry columns populated
        """
        dataframe.loc[
            (   
                (dataframe['fake_dema20'] >= dataframe['resample_15_dema100']) &  
                (dataframe['shifted_ema20'] < dataframe['resample_15_dema100']) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            ['enter_long', 'enter_tag']] = (1, 'yukseliyooooor')
        dataframe.loc[
            (
                (dataframe['fake_dema20'] <= dataframe['resample_15_dema100']) &  
                (dataframe['shifted_ema20']> dataframe['resample_15_dema100']) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            ['enter_short', 'enter_tag']] = (1, 'Dusuyoooooor')
        

        return dataframe
```

**Comment by xmatthias** [comment]
there's nothing asynchronous to it.

resampled_merge has 2 modes - with `ffill=True` and `ffill=False`.

with `ffill=True`:
![image](https://user-images.githubusercontent.com/5024695/215149358-ec1b40bb-5046-4b7d-a0f0-fe2fb7fb65f7.png)


with `ffill=False`, you'll get the following:
![image](https://user-images.githubusercontent.com/5024695/215149267-f786fb76-6876-493e-a48b-c505ad02faee.png)

both are correct - as the first simply fills the 15m value to the "non-15m" rows, while the latter leaves that empty.

i suspect your code causes "sticking" signals - where the same signal is active for not just the 1st candle, but for multiple 5m candles.
That's however depending on how you make your conditions.

You'll usually want to look at "when this condition happened" - which can be accomplished with the simple "crossed" helpers
e.g. `qtpylib.crossed_above(dataframe['ema_short'], dataframe['ema_long']) `.

This will trigger whenever there's an actual cross - compared to `(dataframe['ema_short']< dataframe['ema_long'])` - which would be active whenever the short ema is below the long ema.

**Comment by bleriot14** [comment]
![image](https://user-images.githubusercontent.com/83162265/215279331-9f905cb6-bafd-4f1b-abcd-4eb810e9c3fe.png)

If you look at these two photos and my drawings, you can see that 08:25 and 08:30 candle's resample_15_dema100 are same. It shoul be changed every :30, :45 and :60 , not :20, :35 and :50.

**Comment by xmatthias** [comment]
i think you're ignoring the fact that the timestamps we're talking here are candle open timestamps.

so the candle dated 08:25 (5m) is really 08:25-08:30. As such - the earliest time it's available is at 08:30 (:01).
Implicitly, this also means that the 08:15 (15m) candle is from 08:15-08:30.

Both of these candles are available at 08:30 - therefore the 08:15 15m candle is merged onto the 08:25 (5m) candle (both candle's end date is 08:30).

you can also see this in the screenshots i posted above (though with 15m/1h candles) - but the fact doesn't change.

Hope this helps.

**Comment by bleriot14** [comment]
@xmatthias  , 
8:25 5m candle is in 8:15-8:30 15m candle.
8:30 candle is in 8:30-8:45 15m candle.

Isn't it ? So why this two candles have same resample_15_dema_100. 

I am sorry that,  I miss something but I can't see somehow.

**Comment by bleriot14** [comment]
Oh, I was missing frequi show us close timeframe, not open. Thank you so much.

**Comment by xmatthias** [comment]
no it doesn't - freqUI shows the same timestamp than the dataframe (and exchanges) - which is the candle's open timeframe.

your screenshots don't show anything else than what i explained above, really :)

**Comment by bleriot14** [comment]
Yeah sometimes I am being very thick :D
