### ISSUE TITLE
Getting "AttributeError: 'MyStrategyClass' object has no attribute 'freqai'" error in jupyter notebook

### ISSUE THREAD

**Issue by huytrvan** [freqtrade/freqtrade#8066]
## Describe your environment

  * Operating system: Ubuntu 22.4
  * Python Version: 3.10-dev
  * CCXT version: 2.6.65
  * Freqtrade Version: freqtrade 2023.1.dev-020dc3c6e

## Describe the problem:

I am trying to run StrategyResolver in jupyter notebook to debug and I keep getting the error `AttributeError: 'MyStrategyClass' object has no attribute 'freqai'`. 

Here is the code (note that I run exactly the same code as mentioned [in the documentation](https://www.freqtrade.io/en/stable/strategy_analysis_example/#load-and-run-strategy))

```
# Load strategy using values set above
from freqtrade.resolvers import StrategyResolver
from freqtrade.data.dataprovider import DataProvider
config['strategy'] = 'BoringStratFreqaiV2'
strategy = StrategyResolver.load_strategy(config)
strategy.dp = DataProvider(config, None, None)

# Generate buy/sell signals using strategy
df = strategy.analyze_ticker(candles, {'pair': pair})
df.tail()
```

### Steps to reproduce:

  1.  Use either Docker installation or python installation (using setup.sh)
  2.  Run all the code in jupyter notebook mentioned in [this documentation page](https://www.freqtrade.io/en/stable/strategy_analysis_example/)
  3. All code cells will work except the code cell (mentioned above) and throw error, regardless of what installation method you use.
  
### Observed Results:

  * **What did you expect to happen?**
 * I expect this to be installation issue but apparently it's due inheritance issue with StrategyResolver with regards to freqai.

### Relevant code exceptions or logs
  ```
  ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[12], line 9
      6 strategy.dp = DataProvider(config, None, None)
      8 # Generate buy/sell signals using strategy
----> 9 df = strategy.analyze_ticker(candles, {'pair': pair})
     10 df.tail()

File ~/freqtrade/freqtrade/strategy/interface.py:824, in IStrategy.analyze_ticker(self, dataframe, metadata)
    816 """
    817 Parses the given candle (OHLCV) data and returns a populated DataFrame
    818 add several TA indicators and entry order signal to it
   (...)
    821 :return: DataFrame of candle (OHLCV) data with indicator data and signals added
    822 """
    823 logger.debug("TA Analysis Launched")
--> 824 dataframe = self.advise_indicators(dataframe, metadata)
    825 dataframe = self.advise_entry(dataframe, metadata)
    826 dataframe = self.advise_exit(dataframe, metadata)

File ~/freqtrade/freqtrade/strategy/interface.py:1319, in IStrategy.advise_indicators(self, dataframe, metadata)
   1315 for inf_data, populate_fn in self._ft_informative:
   1316     dataframe = _create_and_merge_informative_pair(
   1317         self, dataframe, metadata, inf_data, populate_fn)
-> 1319 return self.populate_indicators(dataframe, metadata)
...
    150 def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
--> 151     dataframe = self.freqai.start(dataframe, metadata, self)
    153     return dataframe

AttributeError: 'BoringStratFreqaiV2' object has no attribute 'freqai'
  ```

Here's the [link to the jupyter notebook file](https://cdn.discordapp.com/attachments/983285489299779645/1068595147056631900/test.ipynb)

**Comment by xmatthias** [comment]
i don't think running freqAI through a notebook is tested - nor am i sure that'll work (ignoring the fact that it might not be a good idea).

freqAI is not loaded because `strategy.ft_bot_start()` is not called.

you can try to add that call in right after the assignment of `strategy.dp`.

That's however no guarantee that other things around freqAI will work in a notebook - best let me know if that works for you.

**Comment by huytrvan** [comment]
Yes, your suggestion worked. Thank you

**Comment by huytrvan** [comment]
Hi again [Matthias](https://github.com/xmatthias), after further testing, it gave this error:
```
KeyError: 'do_predict'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[10], line 12
      8 strategy.dp = DataProvider(config, None, None)
      9 # strategy.ft_bot_start()
     10 
     11 # Generate buy/sell signals using strategy
...
   3807     #  InvalidIndexError. Otherwise we fall through and re-raise
   3808     #  the TypeError.
   3809     self._check_indexing_error(key)

KeyError: 'do_predict'
```

The dataframe only returned ohclv columns in `populate_entry_trend()` without indicators and `do_predict` column. It meant freqai was not loaded and didn't call `feature_engineering_expand_*` methods. 

I guess your suggestion didn't work, sorry for claiming it was working earlier. 

Anyways, I will just test manually outside of jupyter notebook for now.
