### ISSUE TITLE
(Futures) Trades are not executed during backtesting when the `stake_amount` is too low

### ISSUE THREAD

**Issue by raphaelstar** [freqtrade/freqtrade#8067]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.10
  * CCXT version: 2.5.39
  * Freqtrade Version: develop branch
  
## Describe the problem:

In backtesting, when the stake amount is adjusted to the minimum stake amount, the trade is not entered because of strict inequality test `>` instead of non-strict test `>=` , here:

https://github.com/freqtrade/freqtrade/blob/020dc3c6e13baaedd43715126ec689d878b35a53/freqtrade/optimize/backtesting.py#L803

### Steps to reproduce:

Run a backtesting with a low `stake_amount` configuration for a bot trading on futures.
  
### Observed Results:

  * What happened?
    No trade is executed
  * What did you expect to happen?
   Trades with adjusted `stake_amount` should be exectuted.

**Comment by xmatthias** [comment]
Nice spot :+1:  will be fixed shortly
