### ISSUE TITLE
Order Type based upon the Current profit Rate

### ISSUE THREAD

**Issue by alisalama** [freqtrade/freqtrade#8068]
## Describe your environment
(if applicable)

  * Operating system: Mac OS Monterey
  * Python Version: 3.9.7
  * CCXT version: 2.6.39
  * Freqtrade Version: docker-2023.1.dev-95987663

## Describe the enhancement

Hi Matthias,

Is it possible to change the order type based upon the current profit rate?

For example:
Trade is <1% in profit use Limit order
Trade is >=1% in profit use Market order

Would be a useful feature for scalping where for some trades I am willing to pay the market fees for a larger profit takes, but if the profit take is relatively small I don't want to pay a high percentage of that as a fee.

Thanks,
Ali

**Comment by xmatthias** [comment]
no you cannot - but it's not relevant as you'll see.

If you think about what a market order really is, then you'll realize that it's not a useful feature. 
With a market order, you give up complete control on pricing to the market's ability to fill you at "whatever" price.

this means - a trade that's 1% in profit, could in reality then fill for 2% loss - as you could get 3% slippage (not uncommon, especially in smaller coins / smaller exchanges when using anything > 100$ stake).

I'd therefore strongly advise against using market orders (don't use them at all).

Instead - you can fake a market order by using a price from the opposite site of the spread (but you still remain in control of the worst possible trade.
It'll still be named a limit order - but will fill immediately - and will incur market order fees on all exchanges I've tested so far.

It's up to you to define the price of an order via [custom_exit_price](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-entry-and-exit-price-example) callback - so you can take whatever you want as metric to determine the price (i'd suggest 1-2% below the suggested price - that'll ensure an immediate / marketable limit order fill.
