### ISSUE TITLE
Are there any logic for producing entry signal every 5 second like using custom_exit() callback for exiting trades ?

### ISSUE THREAD

**Issue by bleriot14** [freqtrade/freqtrade#8077]
Operating system: Windows 10

Python Version: Python 3.10.4

CCXT version: ------

Freqtrade Version: 2022.9.1

Hey, I want to open a position as fast as possible. 1m, 5m and 15m are slow for my strategy. Are there any method to open positions that much fast ? 

I know it won't work with backtest and AI things.

**Comment by xmatthias** [comment]
in theory - you can have a buy signal that's always set to 1.

You won't be able to use traditional exit signals (that'd be colliding signals).
Also, pairs will lock until the end of the candle, but given enough pairs (with limited positions), you'll be able to switch through pairs easy enough.
If the entry still needs to be conditional, you can prevent / control that with the confirm_trade_entry callback - though performance will probably suffer with this approach.

**Comment by bleriot14** [comment]
I got it, thank you.
