### ISSUE TITLE
 Running setup.py install for gym did not run successfully.

### ISSUE THREAD

**Issue by skeep83** [freqtrade/freqtrade#8078]
Running setup.py install for gym ... error
  error: subprocess-exited-with-error

  

## environment

  * Operating system: ubuntu-22.04.1-live-server
  * Python Version: python3
  
## Describe the problem:
Hello ! 
I try to setup freqtrade on ProxmoxVM-ubuntu-22.04.1-live-server

get this error :

× Running setup.py install for gym did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> gym

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
Failed installing dependencies

**Comment by xmatthias** [comment]
To be honest - i think `note: This is an issue with the package mentioned above, not pip.` says it all.

We'll need some more info though - for example the output of `python3 --version`  and `python -m pip --version` - as well as the system architecture (arm/amd64, ...).

There's a bug report for this in the gym repo already: https://github.com/openai/gym/issues/3176

**Comment by codewithmuh** [comment]
The error message indicates that the value of the extras_require argument in the setup.py file for the gym package is not formatted correctly.

To resolve the issue, you need to make sure the extras_require argument is a dictionary where the keys are the feature names and the values are strings or lists of strings representing the required packages. The strings should contain valid project and version requirement specifiers (e.g. "package_name>=version").

Here's an example of a correctly formatted extras_require argument:


extras_require = {
    "feature_A": ["package_A>=1.0"],
    "feature_B": ["package_B>=2.0", "package_C>=3.0"],
}
Once you have corrected the extras_require argument, try running the setup.py install command again to see if the error is resolved.

**Comment by xmatthias** [comment]
@rashiddaha yes - but that change needs to happen in gym (not freqtrade) - which is an old version (because sb3-baseline didn't update to a newer gym release yet).

I suspect this issue will now ripple through the different chains - ultimately ending with either pinning setuptools to a lower version - or a new minor release of gym==0.21.x - fixing this issue.

**Comment by codewithmuh** [comment]
@xmatthias Yes, You can Try By Changing the Version as well. 
I have shared this solution on Upwork (Muhammad Rashid).

**Comment by dragon7210** [comment]
Hello
I can solve this solutuin.

**Comment by dragon7210** [comment]
please reply

**Comment by awesomePC** [comment]
Hi, I can do it

**Comment by Masmar25** [comment]
The following is a notice in the homepage of Gym repo.
Isn't it recommended to update the dependency to [Gymnasium](https://github.com/Farama-Foundation/Gymnasium)?
Sorry if I am missing something.
<img width="647" alt="image" src="https://user-images.githubusercontent.com/76812422/215818105-965d425f-325d-4326-85ac-7c7520d7fcb4.png">

**Comment by xmatthias** [comment]
freqtrade doesn't depend directly on gym.

We'd love to update - but https://github.com/DLR-RM/stable-baselines3/pull/780 stands in our way.
