### ISSUE TITLE
Torch won't install on an intel linux VM

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#8081]
## Describe your environment

  * Operating system: ____Ubuntu 22.04 Oracle VM
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Collecting torch==1.13.1
  Downloading torch-1.13.1-cp310-cp310-manylinux1_x86_64.whl (887.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 887.4/887.5 MB 22.8 MB/s eta 0:00:01setup.sh: line 43: 515749 Killed

it needs this version for some reason, won't install from darts either.... 

pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by stash86** [comment]
never have such issue. Although `killed` could mean out of memory, esp if you are using the AMD free vps. Either use docker on that, or use swapfile to increase your memory.

**Comment by xmatthias** [comment]
What's your system specs for this system? (i suspect out of memory as well).
You can also check the system logs (`journalctl`) for this - which should tell you something about an OOM error.

assuming the free AMD vps (Who'd pay oracle for a VM? :laughing: )  - then forget installing freqAI.
It'll not be powerfull enough to run it.

freqtrade itself (without freqAI) MAY work if you have a very lightweight strategy - but we don't support that and our minimum system requirements specify 2Gb of RAM - which the free AMD vps simply doesn't provide.
Even on a regular, lightweight strategy, you'll want to very carefully look at system load and timings - as that VPS is VERY lowpowered .

**Comment by tomjrtsmith** [comment]
Its an oracle vm had lying around, didn't specify Freqai though just dev
and hyperopt.

I'll try it again with a swap file.

**Comment by stash86** [comment]
you can't use that vps for any dev. It's just for running bots.

For any dev, use the ARM vps

**Comment by xmatthias** [comment]
dev dependencies installs ALL other dependencies as well (implicitly also freqAI).

Unless your aim is to do development on that (you'll get frustrated on a low powered VPS) - there's little need to have the dev dependencies installed.

I'll consider this an unsupported configuration - as the machine is underpowered - and below the minimum requirements (please note that requirements for freqAI are a lot higher than for freqtrade itself).
