### ISSUE TITLE
[Backtesting][Docker][Binance][Futures] freqtrade - ERROR - No pair in whitelist.

### ISSUE THREAD

**Issue by Seb90258** [freqtrade/freqtrade#8087]
## Describe your environment

  * Operating system: Ubuntu 22.04.1 LTS
  * Python Version: Python 3.10.6
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.1
    
## Your question

I'm getting the following error and I was wondering what I did wrong :-)
2023-02-01 09:31:05,555 - freqtrade - ERROR - No pair in whitelist.
ERROR: 2

I tried doing a backtest on Binance futures within Docker using the following command:
`sudo docker-compose run --rm freqtrade backtesting --config /freqtrade/user_data/config.json --datadir user_data/data/binance --export trades --stake-amount 1000 --strategy testStrategy -i 1h --timeframe-detail 5m --timerange=20210101-20221231`

The config file specified in the the docker-compose.yml is the default one (--config /freqtrade/user_data/config.json)

My config file uses the StaticPairList on Binance Futures

```json
{
  "max_open_trades": 10,
  "stake_currency": "USDT",
  "stake_amount": "unlimited",
  "tradable_balance_ratio": 0.99,
  "fiat_display_currency": "USD",
  "dry_run": true,
  "dry_run_wallet": 20000,
  "cancel_open_orders_on_exit": false,
  "trading_mode": "futures",
  "margin_mode": "isolated",
  "unfilledtimeout": {
    "entry": 10,
    "exit": 10,
    "exit_timeout_count": 0,
    "unit": "minutes"
  },
  "entry_pricing": {
    "price_side": "same",
    "use_order_book": true,
    "order_book_top": 1,
    "price_last_balance": 0.0,
    "check_depth_of_market": {
      "enabled": false,
      "bids_to_ask_delta": 1
    }
  },
  "exit_pricing": {
    "price_side": "same",
    "use_order_book": true,
    "order_book_top": 1
  },
  "exchange": {
    "name": "binance",
    "key": "myKey",
    "secret": "mySecret",
    "ccxt_config": {},
    "ccxt_async_config": {},
    "pair_whitelist": [
    "1INCH/USDT",
    "AAVE/USDT",
    "ADA/USDT",
    "ALGO/USDT",
    "ATOM/USDT",
    "AVAX/USDT",
    "AXS/USDT",
    "BAT/USDT",
    "BNB/USDT",
    "CHZ/USDT",
    "CRV/USDT",
    "DASH/USDT",
    "DOGE/USDT",
    "DOT/USDT",
    "EGLD/USDT",
    "ENJ/USDT",
    "EOS/USDT",
    "ETC/USDT",
    "ETH/USDT",
    "FIL/USDT",
    "FTM/USDT",
    "GRT/USDT",
    "HBAR/USDT",
    "HOT/USDT",
    "ICP/USDT",
    "KAVA/USDT",
    "KLAY/USDT",
    "LINK/USDT",
    "LRC/USDT",
    "LTC/USDT",
    "MANA/USDT",
    "MATIC/USDT",
    "NEAR/USDT",
    "NEO/USDT",
    "ONE/USDT",
    "RUNE/USDT",
    "SAND/USDT",
    "SNX/USDT",
    "SOL/USDT",
    "THETA/USDT",
    "TRX/USDT",
    "UNI/USDT",
    "VET/USDT",
    "XLM/USDT",
    "XMR/USDT",
    "XRP/USDT",
    "XTZ/USDT",
    "ZEC/USDT",
    "ZIL/USDT"
    ],
    "pair_blacklist": ["BTC/USDT"]
  },
  "pairlists": [
    {
        "method": "StaticPairList",
        "number_assets": 100,
        "sort_key": "quoteVolume",
        "min_value": 0,
        "refresh_period": 1800
    }
```

The strategy is running in frequi with the whitelisted symbols 
![image](https://user-images.githubusercontent.com/102753975/216009339-e859f1aa-e8e4-44e3-8584-50870eba7ae9.png)

I'll attach the log in case it's helpful
[freqtrade.log](https://github.com/freqtrade/freqtrade/files/10555705/freqtrade.log)

**Comment by xmatthias** [comment]
your symbols are wrong for futures markets.
BTC/USDT != BTC/USDT:USDT  ... you'll need to use the 2nd  format.

This changed in the last release for binance - and was listed in the [release log](https://github.com/freqtrade/freqtrade/releases/tag/2023.1).

**Comment by Seb90258** [comment]
Ahhh... thanks :-)
