### ISSUE TITLE
Telegram exiting notification cannot turn off

### ISSUE THREAD

**Issue by LeCmnGend** [freqtrade/freqtrade#8092]
## Describe your environment

  * Operating system: WSL2 on Windows 10
  * Python Version: 3.10
  * CCXT version: 2.7.12
  * Freqtrade Version:2023.2.dev
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
My config.json for telegram notification:
```
		"notification_settings": {
			"status": "silent",
			"warning": "on",
			"startup": "on",
			"entry": "off",
			"entry_fill": "on",
			"entry_cancel": "off",
			"exit": {
				"roi": "off",
				"emergency_exit": "off",
				"force_exit": "off",
				"exit_signal": "off",
				"trailing_stop_loss": "off",
				"stop_loss": "silent",
				"stoploss_on_exchange": "off",
				"custom_exit": "off",
				"partial_exit": "on"
			},
			"exit_cancel": "off",
			"exit_fill": "on",
			"protection_trigger": "off",
			"protection_trigger_global": "off",
			"strategy_msg": "off",
			"show_candle": "off"
		},
```
*Explain the problem you have encountered*
Notification about exit signal is still appear

### Steps to reproduce:

  1. _____

  2. _____
  3. _____
  
### Observed Results:
```
✳ Binance: Exiting CTXC/USDT (#660)
Unrealized Profit: 0.30% (profit: 0.07478789 USDT / 0.075 USD)
Enter Tag: #8 Smooth Scalp##############
Exit Reason: #6 MACD Cross##################
Direction: Long
Amount: 112.00000000
Open Rate: 0.22080000
Current Rate: 0.22180000
Exit Rate: 0.22180000
Duration: 0:16:59 (17.0 min)
```
  * What happened?
Exiting notification still appear
  * What did you expect to happen?
Only  exited notification appear
### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
the key that's used is the exit-reason - so in your case - `#6 MACD Cross##################` (or something like this, ignore spelling / copy/paste errors).

If you wan't selective disabling of exit notifications  (your partial exit is on) - you'll need to switch them off for every exit-reason you got in your strategy.

Alternatively, you can also replace the exit dict (`"exit": {...}`) with a string (`"exit": "off"`) - which will disable all exit messages at once.

**Comment by LeCmnGend** [comment]
> the key that's used is the exit-reason - so in your case - `#6 MACD Cross##################` (or something like this, ignore spelling / copy/paste errors).
> 
> If you wan't selective disabling of exit notifications (your partial exit is on) - you'll need to switch them off for every exit-reason you got in your strategy.
> 
> Alternatively, you can also replace the exit dict (`"exit": {...}`) with a string (`"exit": "off"`) - which will disable all exit messages at once.

thank for your suggestion, now i know the idea,
