### ISSUE TITLE
Socks5 proxy per config implementation

### ISSUE THREAD

**Issue by abdellahaski** [freqtrade/freqtrade#8097]
## Describe your environment

  * Operating system:  Ubuntu 22.04 (Docker Compose)
  * Python Version:  3.10.7
  * CCXT version: 2.4.60
  * Freqtrade Version: 2022.12
  
## Your question

I have multiple bots running with the same IP and I reach the Binance API threshold, so I want to use a Socks5 proxy, 

How can we implement a Socks5 proxy on the config file (I have a config per bot)

HTTP proxies are working fine using the cctx_config on the config.json file
like this:

`{ 
  "exchange": {
    "ccxt_config": {
    "aiohttp_proxy": "http://addr:port",
    "proxies": {
      "http": "http://addr:port",
      "https": "http://addr:port"
    },
  }
}`

But this  can't seems to work with a Socks5 proxy,
Reading the CCTX documentation I found how I can use Socks file like this way:

`connector = aiohttp_socks.ProxyConnector.from_url('socks5://user:password@127.0.0.1:1080')
    session = aiohttp.ClientSession(connector=connector)

    exchange = ccxt.binance({
        'session': session,
        # ...
    })`

I tested this method on a test python file on the Freqtrade docker and it worked.
Now how can I implement this in FreqTrade?

Thanks guys for helping.

**Comment by xmatthias** [comment]
The above section will only work for the async version - but not for the sync exchange (freqtrade currently uses both - and will most likely do so for quite some time).
So if ccxt doesn't provide a solution for the sync / requests method - you're probably out of luck.

Now from a freqtrade perspective I'm not sure what benefit you're hoping to gain by using a socks proxy over a http proxy.
you'll still have the same amount of calls - just using a different IP - so assuming you run 5 bots on one server - you'd need 2-3 different proxy hosts - which begs the question - why not simply use 2-3 hosts in the first place?

---

Unless it's a config only setup (similar to the current http setup) - which it doesn't appear to be - then i doubt this is something we'd aim to support - simply to keep the maintenance effort of this low (it's something i have no use for, and wouldn't know how to write automated tests for - so it's VERY likely to break).

There's enough local proxy implementations (squid, ...)  around you can use to translate between a http proxy and an socks proxy - so freqtrade can simply connect to a (local) http proxy - having an external tool handle the downstream proxy connection protocols.

**Comment by abdellahaski** [comment]
Thank you @xmatthias for the fast reply.
I'll be using NordVPN as a proxy and they only support Socks5 (they dropped http proxy support long time ago) 
and on each session I'll be having a different IP address, so I think that'll allow me to run more bots.

I will look into the local proxy implementations ways, I hope it can work for me

**Comment by Mandark-droid** [comment]
Did you have a look at this is says it has support for Socks proxy https://docs.ccxt.com/#/Install?id=python-aiohttp-socks-proxy

**Comment by xmatthias** [comment]
if you initialize the session manually - sure.
it'd however require a change to freqtrade. 
but in all honesty (and as mentioned above) - i see that as an edge-case usecase - which i don't see as worth supporting at this point.

**Comment by oliver-zehentleitner** [comment]
https://medium.lucit.tech/how-to-connect-to-binance-com-websockets-using-python-via-a-socks5-proxy-3c5a3e063f12
