### ISSUE TITLE
adjust-trade-position : how to implement it the right way?

### ISSUE THREAD

**Issue by naif824** [freqtrade/freqtrade#8098]
## Describe your environment

  * Operating system: ____ Ubunto 22
  * Python Version: _____ (`python -V`): 3.10.7
  * CCXT version: _____ (`pip freeze | grep ccxt`): 2.7.12
  * Freqtrade Version: 2023.1(`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
Apologize if the question is basic but I have been messing with position adjustment to split order into smaller order based on the below breakdown:

![image](https://user-images.githubusercontent.com/40152762/216352033-d2671f15-ffc3-496f-8bec-0984f76b2fda.png)

1st order is okay but second order will consume the whole allocated budget, am I heading the right way? Appreciate if you can guide me through implementing this split into the function: [adjust-trade-position](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position)
*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Well we'll not be converting an excel-sheet (screenshot) to code for you.

so far - the biggest problem is that there's no code - so it's supposed to not work 😆 
Best show what you have so far - so we can try and assist where potential problems lie.

**Comment by xmatthias** [comment]
Closing this for now - we're not providing "strategy writing" services.

if you still have a question about why YOUR code does not work, best share what you got and we can then try and analyze what's missing.
