### ISSUE TITLE
can you combine 2 model type in RL?

### ISSUE THREAD

**Issue by mathlabelle** [freqtrade/freqtrade#8110]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

hi, i was wondering if you can simultaniously use a combination of 2 model type for rl ?

**Comment by xmatthias** [comment]
Well you're welcome / encouraged to write your own, custom model.
What you're doing within that model is clearly up to you. we'll neither limit you to the 3 libraries we currently implement - nor to the model types.

Best look at the existing models - and then write your own, implementing `fit()`, `train()` and `predict()`  (as explained in the [docs](https://www.freqtrade.io/en/latest/freqai-configuration/#using-different-prediction-models).

the overwriting part is the last paragraph before the next header.
