### ISSUE TITLE
Docker installation under Windows Server 2022

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8122]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I am about to install Freqtrade based on docker, by Docker Desktop. This one is up and running. Linux subsystem is active. I don't use Hyper-V, but WSL 2. I have checked, if docker works fine, like this: docker-compose --version. I get version 2.15.1. And Docker Desktop has the current version.
The yml file (non-edited) is in the correct folder. With PowerShell I have navigated to this folder. I am a local admin.
docker compose pull works, however the Powershell text is red, with this leading message:

`docker-compose : freqtrade Pulling 
At line:1 char:1
+ docker-compose pull
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (freqtrade Pulling :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError`
    
 For testing I was curious, if the remaining part works.
 After this command:
 docker compose run --rm freqtrade create-userdir --userdir user_data
 
 . . .I get this error:
 
 `docker : Network a1_default  Creating
At line:1 char:1
+ docker compose run --rm freqtrade create-userdir --userdir user_data
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Network a1_default  Creating:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Network a1_default  Created
2023-02-05 17:47:34,047 - freqtrade - INFO - freqtrade 2023.1`

At least, the folder structure was created by the script. But the installation stopped. 

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
I've never really used docker desktop on windows server - and i'm not sure that's a good idea.
for one, it'll require a license - and will be much less efficient than running a linux server, which has a lot less going on in the background.

For a production setup - i can only recommend to not go this direction. 
Docker on windows is (at least in my experience) sometimes flaky - and unless you have a very good understanding of how it "tries" to operate (mainly on a networking level) - it's better not do go this route.

---

Freqtrade's docker containers will run on docker for windows just fine - but assume a properly configured docker instance (the contianer won't actually care if it's running on a windows or linux host).

Please do understand however that we cannot provide support for docker installations - and will have to mostly refer you to the docker help channels.

A quick search for your error leads to this issue https://github.com/docker/compose/issues/5222 - which suggests this to be a windows / powershell related issue that's "out of our hands".

I'll therefore follow suite with this expression - and would ask you to try the solutions proposed in the linked issue / corresponding stackoverflow issue. 
if these don't work - best open a new issue on the docker / docker compose repository. The same error will occur independent of a freqtrade docker image /  compose file - or any other file.

**Comment by myNextCoder** [comment]
I thank you. If I understand you correctly, it is better to have Linux as basic OS? You wouldn't work productively with Freqtrade, where Windows is a part of the configuration?

**Comment by xmatthias** [comment]
me personally - no.

it's both an experience (bad experience with docker on windows), as well as efficiency question (also, VPS usually cost more if it's a windows system). 
You'll struggle to run windows with 1Gb of RAM - but the combination of docker on linux with a rather light strategy works perfectly fine for that.
now depending on the strategy, you'll need more (or much more, when freqAI is involved) - but especially for minimal usecases, windows brings quite some overhead.

You'll also need to be careful with licensing - as you'll technically need to both license windows - as well as docker desktop (which is not free for windows server afaik).

**Comment by myNextCoder** [comment]
You won't believe me: The issue has taken place, due to my usage of Powershell ISE, instead of the default PowerShell Window: By placing all commands identically in the default app, it worked instantly. ISE seems to have slight (but big) differences in accessing the system. Before this, I never had issues with ISE.
