### ISSUE TITLE
freqtrade - ERROR - No pair in whitelist.

### ISSUE THREAD

**Issue by Daviko290** [freqtrade/freqtrade#8124]
Until 3 days ago I had freqtrade installed without any problem, now I have installed it, I have downloaded data for futures and when doing backtesting it tells me: freqtrade - ERROR - No pair in whitelist. but of course I have the data in the whitelist I use docker in windows 11 when I try it in spot it does not give any if someone can help me thanks
this is my configuration:
{
    "max_open_trades": 5,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 55,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
            "MANA/USDT",
            "NEAR/USDT",
            "SOL/USDT",
            "GALA/USDT",
            "WAVES/USDT"
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": true,
        "token": "I",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "63758a9402d1829da067b03d4c4f0ce218d70a2a9f6c12ec82402f7bd1ecf5b9",
        "ws_token": "qra1pdU694cKiU5Y7tazvoeGbPc6BYXPIg",
        "CORS_origins": [],
        "username": "Daviko29",
        "password": "Master100"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

**Comment by stash86** [comment]
Please join the discord server to get up-to-date announcement. There is a change with how futures pairs on binance are written. It's now (for example) BTC/USDT:USDT

**Comment by Daviko290** [comment]
> Únase al servidor de discordia para obtener un anuncio actualizado. Hay un cambio en la forma en que se escriben los pares de futuros en binance. Ahora es (por ejemplo) BTC/USDT:USDT

Thank you very much I thought the installation was wrong you saved me a lot of time

**Comment by xmatthias** [comment]
The same announcement is also part of the [release notes](https://github.com/freqtrade/freqtrade/releases/tag/2023.1) - which i'd suggest everyone to read before switching to a new version.
