### ISSUE TITLE
how to get Symbol name in strategy file? 

### ISSUE THREAD

**Issue by sionex-code** [freqtrade/freqtrade#8131]
## Describe your environment

  * Operating system: Win 11
  * Python Version: 3.9
  * CCXT version: 2.0.71
  * Freqtrade Version: freqtrade 2022.12
  
## Your question

```
last6rows = dataframe['enter_long'].iloc[-6:]
last6rows = last6rows[::-1]
requests.get('https://xxxxx.site/data/entry.php?q='+str(last6rows.to_json()))
```

So this is my code. I am trying to ping this URL upon an entry signal. I am attempting to send a signal to this URL if the last 6 rows contain "enter_long = 1", but I am unsure of how to obtain the current symbol name. I tried to export the dataframe to a CSV, but I was unable to find the symbol name.

i am sorry for making this stupid useless question,

**Comment by sionex-code** [comment]
i found the solution: 

`print(self.dp.ticker(metadata['pair'])['symbol'])`

**Comment by xmatthias** [comment]
Depending on which method you're using this - it's either [metadata](https://www.freqtrade.io/en/stable/strategy-customization/#metadata-dict) (all `populate_*_trend` methods) - or `pair` / `trade.pair` for callbacks.
