### ISSUE TITLE
Network path notation on command line

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8133]
## Describe your environment

  * Operating system: Windows Servert 2022 with Docker Desktop
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

What is the correct notation on command line for config.json files, which are situated on a network share, let's say, the file-server is named Server1?

The notation 'docker compose run --rm freqtrade trade --config //Server1/config.json. . .' seems not to work.
We might need different leading characters for the path?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
I don't think this will work - especially not in combination with docker.

in reality, the only premise for the file to be found is that it's available as file through the regular file system driver.

If you're using a share on a windows PC, then this usually assumes some form of user authentication.
This authentication is not available within the docker container, so it'll obviously not work (even without authentication, you can't access a file "like this").
You'd need some samba drivers in the container (which are not installed on the default image).

You can try to somehow mount the file / path into the container (look for docker mounts) - but that's WAY beyond anything we'll be helping you with.
