### ISSUE TITLE
Long one pair, short another

### ISSUE THREAD

**Issue by SergeySypalo** [freqtrade/freqtrade#8140]
## Describe your environment

  * Operating system: Win11
  * Python Version: 3.11.2
  * CCXT version: 2.7.65
  * Freqtrade Version: 2023.2.dev-3d22ad36b
  
## Your question

As hedge mode is not supported I wanted to ask if it's possible to long one pair (for example ETH) and short another (BTC)?
From the docs, I got that I need to set short to true and market to futures, but how to enter only long trades on one pair and only short on another? Is it something I need to code myself in the populate entry?

**Comment by xmatthias** [comment]
I'd strongly suggest to read the documentation once from top to bottom to get a grasp what's possible with freqtrade.

> Is it something I need to code myself in the populate entry?

you'll find the particular information (how to enter longs / shorts) in the [strategy documentation](https://www.freqtrade.io/en/stable/strategy-customization/#entry-signal-rules) (watch out for info boxes ...).

the definition on how to create a signal (long on btc, short on ETH or viceversa) is then fully up to your discgression.
