### ISSUE TITLE
Why is FreqAI not working with feature_engineering? "Could not find any features!"

### ISSUE THREAD

**Issue by EugenioBuffo** [freqtrade/freqtrade#8143]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: Python 3.10.9
  * CCXT version: ccxt==1.93.1
  * Freqtrade Version: freqtrade 2023.1.dev-fae83bbcb
  
## Your question

**Why is FreqAI not working with feature_engineering?** 

I'll always receive `freqtrade - ERROR - Could not find any features!` as error.

I'm using the template "FreqaiExampleStrategy.py" present inside "freqtrade/templates" folder.
In the documentation is mentioned the use of `feature_engineering_*` methods, but the backtest/dryrun doesn't work and return the following error:
**freqtrade - ERROR - Could not find any features!**

I've tried instead an old FreqAI template with the previous `populate_all_indicators` method and it works.
I've also tried to switch to FreqAI branch, but nothing changed.

**What am I missing?**

Thank You,
Eugenio

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
To help you with this, please provide us with:
* the exact command used
* the freqai part of your configuration
* the logs freqtrade issues up to the error / problem.

Also - it should be noted that fae83bbcb is not a valid version of this repository.
Please understand that we will not support versions unknown to us (or that contain unknown versions) - so the logs you'll provide above will be made with an unmodified version from this repository.

**Comment by EugenioBuffo** [comment]
Hi,

I apologize for the inconvenience.

I've noticed that I'm behind on commits due to an incomplete merge with upstream on my fork.

My bad, I will close this thread.

Thank you
