### ISSUE TITLE
Stopping the Bot properly

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8151]
## Describe your environment

  * Operating system: Windows Server 2022, Docker Desktop
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.1 stable (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Is it possible, to properly stop a Bot at the Freqtrade prompt (Looking like this: ftuser@0ad884742804:/freqtrade$), to have one only db file again at the end? My previous installation under Minicoda has merged the db, as I was pressing Ctrl-C just in the running log window, which now works different in the container.
If you think, that I can just stop the container, having the *shm and *wal files at termination: Do I loose information, by only taking the *.sqlite file, in case I want to run the Bot on a different machine, in a different container?
(As I just stop the container, Telegram does not send the message 'process died')

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
pressing ctrl+c once will usually suffice. Pressing ctrl+c multiple times will kill the bot - which is clearly not what you'd want.

Depending on the configuration, it may take a bit to actually, properly shut down (especially telegram can cause quite some delays).

**Comment by myNextCoder** [comment]
I thank you, obviously I have a 'Powershell thing', since in the running log (comparing to my Miniconda-days) no key is accepted. But this one I cannot resolve in this Freqtrade Forum.

**Comment by xmatthias** [comment]
well not sure - considering you're using docker, the correct way to start the bot (in trade mode) would be `docker-compose up -d` (the executed command will be whatever is defined as `command:` in the compose file) - and stopping it is `docker-compose stop` or `docker-compose down`.
