### ISSUE TITLE
Sockets and using signals dataframe in custom stop loss

### ISSUE THREAD

**Issue by MohamedDhouib** [freqtrade/freqtrade#8154]
## Describe your environment

 * Operating system: wsl2 w10
 * Python Version: 3.10
 * CCXT version: 2.7.66
 * Freqtrade Version: 2023.dev2
  
## Your question

I have a 5min scalp strategy using trailing stop loss but i' having an issue with the download of OHLC candles of 80 coins, it's taking so much time. So i searched if it is possible to use sockets but apperently **it's not ready for freqtrade yet so can you confirm that please**?

Next i tried to find a workaround to make my live exec do the same thing as my live exec, because when i have a diffrent entry than my backtest, a winning trade can become a VERY loosing one easily. So i wanted to code my own trailing stop loss function by customizing a stop loss to calculate my trailing offset (trailing trigger) based on the backtest entry price so if everything go as planned i'll be limiting my gains but i'll be having the same result as in the backtest.
Example: Backtest entry: 50$. Live entry 52$. backtest exit: 55$(+10%). Then my live exit should be 55$ too and not 57.2$ (52$ + 10%).

The problem is that I'm not able to get the dataframe with signals in the custom stop function. And it seems like there isn't a way to do such thing:
**def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime, current_rate: float, current_profit: float, \*\*kwargs) -> float**

Can you suggest anything please?

Thank's in advance

**Comment by xmatthias** [comment]
Once websockets are available, we'll be anouncing that.

For the rest - please refer to the Documentation - specifically to the [dataprovider docs](https://www.freqtrade.io/en/latest/strategy-customization/#get_analyzed_dataframepair-timeframe).

while the link leads you exactly to the method used, best read through the whole document - it'll contain a lot of information you'll find to be helpful.
