### ISSUE TITLE
Add ta-lib in container

### ISSUE THREAD

**Issue by Tony2k** [freqtrade/freqtrade#8168]
Most of strategies need ta-lib, in fact I have this error: 
`2023-02-13 08:10:44,388 - freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/Heracles.py due to 'No module named 'ta''`

I think that add ta-lib in container at this point is needed.

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

`ta-lib` is part of the freqtrade image.

you're looking at "ta" - which is a different module entirely.
There's probably 100ds of indicator libraries (ta-lib, pandas-ta, finta, ta, technical, ...). 

Most libraries provide very similar functionality / indicators (at least the most common ones), often with a slightly different interface, or with a slightly varying calculation.

Freqtrade images include the most common libraries (ta-lib, pandas-ta, technical) - but we will not force all possibilities for all users.

if your strategy requires additional, non-standard dependencies, please follow the [additional dependencies](https://www.freqtrade.io/en/stable/docker_quickstart/#additional-dependencies-with-docker)
