### ISSUE TITLE
Stop Loss on exchange(adjusted position)

### ISSUE THREAD

**Issue by Arivadis** [freqtrade/freqtrade#8169]
Hello,

Could You please help me to figure out how stoploss on exchange works in pair with adjusted position?

I am wondering if it puts stoploss on exchange, and then request the infrmation from exchange if stoploss has closed /// or it just put stoploss and anyway will close trade if stoploss is reached on freqtrade, but not on exchange(for case if position is adjusted - https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position).

I am looking for best way to get stoploss with AVG position. Maybe there is easy way not to use custom_exit with computing everything inside it.

Thank You for any thoughts.

**Comment by xmatthias** [comment]
Freqtrade will obviously request information about the fact if the stoploss order has been filled or not.

Whenever you do a position adjustment, the prior stoploss on exchange will be canceled either
* before placing a partial exit order
* after a partial entry order fills

This cancellation causes a new placement of the stoploss order.
both actions are necessary (in this sequence) so the placed stoploss order is for the correct order size (and in case of partial exits - that placing a new order won't fail).

**Comment by Arivadis** [comment]
Ok, lets say, strategy opened a trade, stoploss 10%, and make one partial entry for 100% of entry amount at the moment of current profit -5%.

If freqtrade calculate the stoploss from first entry - price should fall 10% - so the losses will be 10% of entry amount + some % from adjusted position.
But if we place stoploss on exchange the same order, stoploss and partial entry - it going to loose 10% of avg price as binance comput stoploss from avg?
Will Freqtrade ignore its own stoploss call and be waiting till binance filled stoploss?

**Comment by xmatthias** [comment]
I'm not sure what you're talking about ... 
placing orders manually on the exchange is not supported (freqtrade won't know about your order) - and will definitely lead to errors.

To quote the [stoploss-callback documentation](https://www.freqtrade.io/en/latest/strategy-callbacks/#custom-stoploss):
> Stoploss is still calculated from the initial opening price, not averaged price. Regular stoploss rules still apply (cannot move down).

As such - if the initial stoploss was placed at 90$ - it'll remain at 90$ - even if your additional entry was at 95$.

**Comment by xmatthias** [comment]
knowing that you're usually pretty responsive - can i assume that the above answers your question?

**Comment by Arivadis** [comment]
I forgot to responce, sorry!

From your ansver I see freqtrade place stoploss using price point, not %, so if freqtrade put stoploss on exchange it will be the same as not on exchange(would it put using % - the exchange stoploss would have bigger distance in case of adjusting position).

I think this question is result of my ignorance what values exchange using to place stoploss(as exchanges allow to use both - price and % in manual trading).

Now this is pretty clear, thank You!
