### ISSUE TITLE
Why my adjustment buy request not meet?

### ISSUE THREAD

**Issue by mohsenjavidpanah** [freqtrade/freqtrade#8174]
## Describe your environment

  * Operating system: Ubuntu 22.04.1
  * Python Version: 3.10.6
  * CCXT version: 2.2.67
  * Freqtrade Version: develop branch
  
## question

I used `adjust_trade_position` method for increasing stake amount, but in market rush conditions, this request not meet.  
What I must do For success adjustment buy in rush times?

Notice: My strategy is based on Futures trade.

Thanks

**Comment by stash86** [comment]
seems like you need to learn about limit and market order. Do google on them

**Comment by xmatthias** [comment]
If your orders don't fill (i assume that's what this is about) - then your prices are not allowing them to.

Freqtrade allows different ways to [price your orders](https://www.freqtrade.io/en/stable/configuration/#prices-used-for-orders).
A simple answer can be "use 'other' pricing" - but you shouldn't do that without understanding the impact of this.

It however assumes some basic market understanding (more in detail - how limit orders behave in the market / orderbook depending on the price that's used).
It's beyond the scope of freqtrade documentation to educate users in detail about this - but information about this is generally available on both exchange documentation pages, as well as on independent pages (like investopedia).

**Comment by mohsenjavidpanah** [comment]
Thank you

This is possible to use different method for buys in **adjust**-entry?

my current config is same as below:

```
...
    "entry_pricing": {
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1
    }
...
```

**Comment by xmatthias** [comment]
You can use [custom order pricing](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-price-rules) for this.

if you set your price to 1-2% above (for buys) or 1-2% below (for sells) the price, you'll get almost guaranteed fills - assuming price didn't move by the 1-2% in the 2nd it takes to determine the price and to place the order (very unlikely).

**Comment by mohsenjavidpanah** [comment]
In other word this link is my answer:

https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-entry-price
