### ISSUE TITLE
json file with comments?

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8179]
## Describe your environment

  * Operating system: Windows Server 2022 with Docker Desktop
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Generally a json file seems not to accept comments, according to online information, but there are some config.json examples for Freqtrade on GitHub with comments by two forward slashes. Are such comments in the config file ok for Freqtrade, does it really ignore them? 

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
while not 100% plain json standard - comments are somewhat common in json files.

as such - freqtrade does accept (or rather ignore) comments in config files.

**Comment by myNextCoder** [comment]
Great, some hints as comments are useful
