### ISSUE TITLE
Wiki update: expand explanation on custom strategy

### ISSUE THREAD

**Issue by moshlp** [freqtrade/freqtrade#818]
I'd like the page to go step by step from default strategy describing what every line does.

thanks,

**Comment by glonlas** [comment]
Hi,

Good request, for that we will have to improve this documentation page: https://github.com/gcarq/freqtrade/blob/develop/docs/bot-optimization.md

The only thing not explained in our current documentation is what is (even if the comment in the code explain it):
- minimal_roi
-  stoploss
- ticker_interval

What is today unclear to you?
