### ISSUE TITLE
Use of Trade count, open and closed trades profit in backtest

### ISSUE THREAD

**Issue by pizzidellamaremma** [freqtrade/freqtrade#8186]
Environment:
  * Operating system: Windows 10 / Python venv
  * Python Version: 3.9.10
  * CCXT version: 1.89.14
  * Freqtrade Version: freqtrade develop
  
In strategy I start using the `Trade` class inside `custom_exit` method to build a custom protection saving data inside a custom class dict. What I'm trying to achieve is to use current open trades profit and closed trades profit to evaluate an emergency exit.
The code look like this:
```
class NF_Strategy_C2(IStrategy):
    def bot_start(self, **kwargs) -> None:
            self.cust_data = {
                    "long_safe_exit": {
                        "active": False,
                        "timestamp": None,
                        "closed_trade_profit": 0.0,
                        "open_trade_profit": 0.0,
                        "wait_until": timedelta(hours=6)
                    }
                }

    def bot_loop_start(self, **kwargs) -> None:
        active = self.cust_data.get('long_safe_exit').get('active')
        start_date = self.cust_data.get('long_safe_exit').get('timestamp')
        timedelta = self.cust_data.get('long_safe_exit').get('wait_until')
        if active and datetime.utcnow() > start_date+timedelta:
            self.cust_data['long_safe_exit']['timestamp'] = None
            self.cust_data['long_safe_exit']['active'] = False


    def custom_exit(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, **kwargs):
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = dataframe.iloc[-1].squeeze()
        live = self.config['runmode'].value in ('live', 'dry_run')
        safe_exit_enabled = self.cust_data.get('long_safe_exit').get('active')
        if (
                live and
                safe_exit_enabled is False and  ### ADD CONDITIONS AFTER THIS
                last_candle[f'mc_{self.timeframe}'] < -0.5
                ):
            ### catch closed trades
            order_by = Trade.close_date.desc()
            trades = Trade.get_trades([Trade.is_open.is_(False), Trade.is_short.is_(False)]).order_by(order_by)
            closed_trades = []
            for t in trades:
                dummy = ast.literal_eval(t.to_json())
                closed_trades.append(dummy['close_profit_pct'])
            closed_trades = sum(closed_trades)

            ### catch open trades
            trades = Trade.get_trades([Trade.is_open.is_(True), Trade.is_short.is_(False)])
            open_trades = []
            for t in trades:
                dummy = ast.literal_eval(t.to_json())
                current = self.dp.market(t['pair'])
                open_trades.append(current/dummy['open_rate'])
            open_trades = sum(open_trades)
            if closed_trades/2 > sum(open_trades):
                self.cust_data['long_safe_exit']['active'] = True
                self.cust_data['long_safe_exit']['timestamp'] = current_time
                self.cust_data['long_safe_exit']['closed_trade_profit'] = closed_trades
                self.cust_data['long_safe_exit']['open_trade_profit'] = open_trades
                logger.warning(f'Entered in safe exit at {current_time}')

        if live and safe_exit_enabled and trade.is_short is False:
            return "cext_long_safe"
```

Regardless any error inside the `custom_exit` part, is there a way to backtest it? Because from what I understand `Trade` cannot be used except for live and dry-run mode but it's time consuming waiting for the right conditions. 
Is there a way to return open trades profit and closed trades profit without database access that can be also used in backtest?

**Comment by xmatthias** [comment]
first of all - using `datetime.now()` (or any deviation of that) makes things automatically non backtestable - as that will yield "now" - not "backtest time" - at least if the actual time that yields is used for anything meaningful.

Most/all callbacks have a `current_time` argument which should be used instead.

---


You should also read the [this doc page about the trade object](https://www.freqtrade.io/en/latest/trade-object/#get_trades_proxy) - which will show you that using `get_trades` will break backtesting - while using `get_trades_proxy()` (while limited in the conditions you can pass in) will be actually backtestable - as long as it's only used within callbacks.

so with a few, minor adjustments - i don't see why this shouldn't be backtestable.


there's a few additional oddities (`dummy = ast.literal_eval(t.to_json())` doesn't seem to make sense??) - why not use close_profit_pct directly? (again - read the above page from top to bottom, not just the section i explicitly linked).

**Comment by pizzidellamaremma** [comment]
As always, thank you for pointing me in the right direction. 
I wasn't aware about using `current_time` inside `bot_loop_start()` and `get_trades_proxy()`, I should RTFM a bit more. 

Is there any way to access the current profit for an open trade? Using `self.dp.ticker(pair)` (to calculate it) returns the current ticker from exchange, is there a similar option that does not break the backtest?

**Comment by xmatthias** [comment]
`bot_loop_start` doesn't have that argument though :laughing: 

> Is there any way to access the current profit for an open trade

again (as above), all callbacks (that run in a trade context) will have a `current_profit` argument - which will contain the current profit.

**Comment by pizzidellamaremma** [comment]
> `bot_loop_start` doesn't have that argument though 😆

I tried in backtest, it's probably included in `**kwargs` because it seems to work...

> again (as above), all callbacks (that run in a trade context) will have a `current_profit` argument - which will contain the current profit.

Yes, but I need the current profit for all the open trades, not just the current one inside the loop.

**Comment by xmatthias** [comment]
> I tried in backtest, it's probably included in **kwargs because it seems to work...

err ... no - it's not there ...

current profit is not stored as part of the trade object. it's something that constantly moves - and would therefore cause a lot of strain on the database for no good reason

**Comment by pizzidellamaremma** [comment]
> err ... no - it's not there ...

I'll be honest... why it should not be there? :grinning:

> current profit is not stored as part of the trade object. it's something that constantly moves - and would therefore cause a lot of strain on the database for no good reason

Yeah, there's no sense to store it inside the Trade object. 
Anyway, I can try with `self.dp.get_pair_dataframe(pair)` but it will be quite heavy to just squeeze the last row to obtain one float value... per each informative pair. I need to dive into the docs.

**Comment by froggleston** [comment]
It's not "heavy" to do so IMO, and I'm not sure why using current_time is a problem here?

**Comment by xmatthias** [comment]
`current_time` is not passed to `bot_loop_start()` - but it's also irrelevant, really.

[`bot_loop_start()` is only called once in backtesting](https://www.freqtrade.io/en/latest/bot-basics/#backtesting-hyperopt-execution-logic) - so whatever you do there will only happen once in backtesting.

---

For prices, there's no other way, really.
Callbacks are designed to run in the trade context (for one trade). While we do support querying for other trades - it's a niche usecase.

You should however consider if you really want/need that. 
It's usually better to see trades as independent. 
There's little reason to buy more BTC (or sell BTC) because random coin dumped/bumped (and the same is true viceversa). It may seem like one coin is pulling them all, but lately, that's clearly not the case.

**Comment by pizzidellamaremma** [comment]
> You should however consider if you really want/need that.
> It's usually better to see trades as independent.
> There's little reason to buy more BTC (or sell BTC) because random coin dumped/bumped (and the same is true viceversa). It may seem like one coin is pulling them all, but lately, that's clearly not the case.

This is not the case, my consideration is to exit every trade if a certain ratio (to be defined) is reached between closed trade profit and open trade profit, then stop it for some hours. It's a safe measure vs market crashes. The most important coins (per volume) are evaluated and these can cause (or show) a market crash. 
It will work 100%? No. But in my mind (if well tuned) it can save the bot from some big drawdowns. 

Anyway, I made the changes but yes, it will not work because `bot_loop_start()` is called only once. 
So there are no places where to run that piece of code every time at the beginning of the loop with all the arguments needed.
Could work well in live mode, but cannot be used in backtest.

> and I'm not sure why using current_time is a problem here?

There's no problem. I misunderstood some parts of the bot logic. `bot_loop_start()` is called once so it has no reason to have `current_time`.

**Comment by xmatthias** [comment]
The main goal with `bot_loop_start()` is/was to allow the injection of time-dependent data (like - request something from an external API that's valid for all pairs).
For backtesting, the assumption is that you'd have the data available in a historic form - and therefore only need to load it once.

Using it to query trade information is not how it's intended - and therefore isn't really working in backtesting.
