### ISSUE TITLE
NixOS Flake file

### ISSUE THREAD

**Issue by Industrial** [freqtrade/freqtrade#8188]
## Describe your environment
NixOS (Linux)

## Describe the enhancement
This is a Flake file for running Freqtrade with NixOS. It's a declarative functional reproducible environment.

```nix
{
  description = "Flake for Freqtrade";
  inputs = {
    nixpkgs.url = "nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };
  outputs = {
    self,
    nixpkgs,
    flake-utils,
    ...
  }:
    flake-utils.lib.eachDefaultSystem (system: let
      pkgs = nixpkgs.legacyPackages.${system};
    in {
      devShell = pkgs.mkShell {
        buildInputs = with pkgs; [
          python310
          ta-lib
        ];

        shellHook = ''
          export LD_LIBRARY_PATH=${pkgs.stdenv.cc.cc.lib}/lib/
          rm -rf .venv
          virtualenv --no-setuptools .venv
          source .venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt
          pip install -r requirements-plot.txt
          pip install -r requirements-hyperopt.txt
          pip install -r requirements-freqai.txt
          pip install -r requirements-freqai-rl.txt
          pip install -r requirements-dev.txt
          pip install -e .
        '';
      };
    });
}
```

**Comment by xmatthias** [comment]
i'm ... not entirely sure what we're supposed to do with this?

I guess it'll work just fine, but i'm also not sure if you now expect us to incorporate this somehow, or if it's just informative for users searching for this in the future.

i don't think adding receipt files for edge-case systems - which (i'm sorry if someone feels offended) - this for sure is - is a good idea, as that'll usually end up in unmaintained blobs - which we then discover at some later point is no longer working for whatever reason.

**Comment by froggleston** [comment]
I suggested raising an issue in case it was something that could be included in the docs, but I do agree that NixOS is somewhat of a niche case.

**Comment by xmatthias** [comment]
Let's keep this here as reference for people searching for it in the future.

for now, we'll not be adding this to the docs - as i fear future changes to that protocol (or whatever this is) will not be updated - as it's simply a too niche usecase.

**Comment by serpent213** [comment]
This is a slightly improved version with different shells for installation and development; also the original version did not work for me. The functionality basically resembles the `Dockerfile`. I'm new to NixOS myself, this might not be the most idiomatic way to do it.

In case interest in Nix rises, it might be an option to adopt a library like [dream2nix](https://nix-community.github.io/dream2nix/intro.html), which should be able to process the requirements files and map their contents to proper Nix packages. But like many other similar libraries it doesn't feel stable yet, couldn't get it to work.

In general NixOS doesn't feel mature to me as a beginner. There's not a single book in print AFAIK, that might be an indicator.  😉  For development work in different languages expect a little setup work for each and better learn the Nix language anyway. It certainly is fun and powerful – and I expect the learning curve to flatten a bit again in the years to come.

The Nix package manager is also available stand-alone for many systems, MacOS, Debian etc. This flake should work in that environment as well (be sure to enable flakes).

`flake.nix`:
```nix
# Run                                                                                                                                                                             
#                                                                                                                                                                                 
#   nix develop .#setupShell                                                                                                                                                      
#                                                                                                                                                                                 
# to install packages via pip initially (and stay in shell).
# Deletes your `.venv`!
#
# Run                                                                                                              
#                                                                                                                                                                                 
#   nix develop                                                                                                                                                                   
#                                                                                                                                                                                 
# to get a development shell afterwards.

{
  description = "Freqtrade crypto trading bot";
  inputs = {
    nixpkgs.url = "nixpkgs/nixos-23.05";
    # or for unstable
    # nixpkgs.url = "nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };
  outputs = {
    self,
    nixpkgs,
    flake-utils,
    ...
  }:
    flake-utils.lib.eachDefaultSystem (system: let
      pkgs = nixpkgs.legacyPackages.${system};
      buildInputs = with pkgs; [
        python311
        python311Packages.pip
        python311Packages.virtualenv
        ta-lib
      ];
    in {
      devShells.default = pkgs.mkShell {
        inherit buildInputs;
        shellHook = ''
          export LD_LIBRARY_PATH=${pkgs.stdenv.cc.cc.lib}/lib/
          source .venv/bin/activate
        '';
      };
      devShells.setupShell = pkgs.mkShell {
        inherit buildInputs;
        shellHook = ''
          export LD_LIBRARY_PATH=${pkgs.stdenv.cc.cc.lib}/lib/
          rm -rf .venv
          virtualenv --no-setuptools .venv
          source .venv/bin/activate
          pip install -r requirements-dev.txt
          pip install -e .
        '';
      };
    });
}
```

**Comment by xmatthias** [comment]
> In general NixOS doesn't feel mature to me as a beginner.

well that's the point - i understand it's a chicken-egg problem (not many "flakes" available, hence more difficult for beginner users).
but - we talk here about a fraction of a fraction of a fraction when it comes to userbase (pretty lowish linux users, only a fraction of these will be using NixOS - and only a fraction of these will be interested in freqtrade).

If it'd be something mainstream, no issue to add such a file - but - it'll move maintenance of that script to the maintainers of this repository - which is difficult if you don't actually use that system  or are interested in it - which means it'll be outdated very soon - and potentially broken (not sure if NixOS flakes actually break) ...

It's great to have it this here in the issue as a reference though :+1:

**Comment by serpent213** [comment]
> It's great to have it this here in the issue as a reference though 👍

Yes, from my point of view that's good enough for now. Flakes itself are still marked as *experimental* within Nix, yet they seem to be the de-facto standard already. That's analogue to many other corners of the ecosystem right now.

Also, if anyone feels a calling to maintain this/a flake, it's common practice to host it in its own repo and have it reference this one to pull in the Freqtrade sources.

**Comment by AchmadFathoni** [comment]
Just for the record, to apply ta-lib patch to pass the test, change `ta-lib` to ` 
```
 (ta-lib.overrideAttrs (finalAttrs: previousAttrs: {
   prePatch = ''sed -i.bak "s|0.00000001|0.000000000000000001 |g" src/ta_func/ta_utility.h'';
 }))`
```
