### ISSUE TITLE
Daisy-chaining consumers delays dataframe over time

### ISSUE THREAD

**Issue by enshoe** [freqtrade/freqtrade#8197]
## Describe your environment
  * Operating system: DEBIAN GNU/LINUX 10
  * Python Version: 2.7.1.6
  * CCXT version: 2.6.65
  * Freqtrade Version: docker-2023.2.stable
  
## Describe the problem:
I have a setup with 4 producers, feeding one consumer (Consumer1) which does additional calculations and determines enter/exit.
Since both the producers and Consumer1 have a heavy workload and a long bootloop, I want to use a second consumer to handle the buying and selling on exchange. This would also make it possible to scale out of one set of producers/consumer if you wanted to run more instances with the same settings. For instance to cater running  multiple clients managing different exchange accounts without having to multiply the overhead of 4 producers and 1 consumer.

Producer1: 5m
Producer2: 5m
Producer3: 5m
Producer4: 1m

Consumer1: 1m
process_only_new_candles = false
ffill = false

Consumer2: 1m
process_only_new_candles = false
ffill = false

[Image explaining the setup](https://imgur.com/qjGwN2P)

### Steps to reproduce:

  1. Create a producer/consumer setup, no boot loop exceeding 45s in worst case.
  2. Daisy chain a consumer on top of the fist consumer.
  
### Observed Results:

  * Over time the dataframes reaching consumer2 becomes delayed and does not catch up
  * The issue gets worse over time, up to a point where there is a constant delay
  * Exporting the dataframe of consumer2 confirms that there is no data
  * Running consumer 1 & consumer 2 in verbose does not give any indication the data is not sent.
  * Decreasing the workload by severely limiting the pairlist on consumer 1 and 2 does not help the situation, which is why I think we have a "real" bug on our hands.

### Relevant code exceptions or logs

Running verbose does not indicate any delay or issue.

### Possible workarounds
I have been thinking about how to work around the issue.
Possibility 1:
Convert entries on consumer 1 to force entries on Consumer 2-X using the REST API. This will most likely work, but you will loose the entry tag data.

Possibility 2:
Find a way to only send entries/exits & their respective tags between instances using the websocket. It looks like you should be able to subscribe to entries if you look at: https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/enums/rpcmessagetype.py

**Comment by xmatthias** [comment]
I don't think traffic will be your issue. 

freqtrade will only transfer the very last candle (* unless it detects missing candles between candles), so unless you're using 1000nds of columns, that won't be an issue.

with 45s botloop on a 1m candle, you're  almost certainly too slow.

so assuming you have 45s botloop on each of the 1m bots (both on producer1 and consumer1) - then the candle that'll get to consumer2 will be delayed by 1.5m.

As such - a candle with the timestamp of 10:00:00 (available at 10:01:0x) will get to consumer1 at 10:01:45 - and to consumer2 at 10:02:30
That's clearly a "late" candle - and also not a signal I'd be wanting my bot to act on.

There's no catching up, really (and i don't think the delay will increase much over time) - but it's there basically by design of your setup - so that's not really anything that can be done for that.

**Comment by enshoe** [comment]
I have seen the delay increase over time myself on several occasions. So it most certainly does, but stops at around 10 minutes delay.
It also does not seem to be tied to he workload, since reducing the amount of pairs drastically I can still force this effect, which is why I thought it could be a "real" bug.

Also, as for my other possible solutions to the setup, could you recommend one based on your knowledge?
Or is the some other way to share entries between instances?

**Comment by xmatthias** [comment]
well what's your timing like when you reduce the amount of pairs? (what amount of pairs are we talking about??)
instead of trying to reduce pairs, try to reduce the amount of work your bot does?

Now freqtrade will log (warning level) whenever it can't use the websocket message (so it requests either a partial, or a full dataframe) - so checking the logs in detail should reveal any info there.


can you reproduce it on a 1m bot that does "nothing" (no indicator calculations)? 
Messages passed between bots after the initial catchup are single lines (per pair) - so as said, i'm not sure where a bottleneck would be.

You can also use the "ws" script to debug these things - which is located in the scripts folder - and is quite handy in these cases, as it'll log when a new websocket message is actually coming in.

Also be aware that behavior might differ depending on the host (same host / different host / different host with slowish connection to the producer).

**Comment by enshoe** [comment]
**well what's your timing like when you reduce the amount of pairs? (what amount of pairs are we talking about??)**
**instead of trying to reduce pairs, try to reduce the amount of work your bot does?**
When trying with a reduced amount of pairs (20) the slowest producer is 20s (5m), and consumer 1 is done within 3 seconds.

**Now freqtrade will log (warning level) whenever it can't use the websocket message (so it requests either a partial, or a full dataframe) - so checking the logs in detail should reveal any info there.**
Is this warning level showed in "regular" logs, or do I need to be in verbose? I have not seen any warnings of that nature so far, except for on startup when a request for historic candles are done.

**can you reproduce it on a 1m bot that does "nothing" (no indicator calculations)?
Messages passed between bots after the initial catchup are single lines (per pair) - so as said, i'm not sure where a bottleneck would be.**
I will test this out and report back.

**You can also use the "ws" script to debug these things - which is located in the scripts folder - and is quite handy in these cases, as it'll log when a new websocket message is actually coming in.**
Is there any documentation on how I can use this for further debugging?

**Also be aware that behavior might differ depending on the host (same host / different host / different host with slowish connection to the producer).**
They are all on the same system, running in different docker containers. Typical ping time is 1-5 ms.

**Comment by xmatthias** [comment]
> Is this warning level showed in "regular" logs,

it's log-level "warning". Debug logs won't help you here - i don't think we do much debug-logging in the websocket space.

> Is there any documentation on how I can use this for further debugging?

not really - but it's just a `python scripts/ws_client.py --config <config with consumer entries>` ... 
Depending on what you'll look for - you might need to modify the output of the script slightly, depending on what you're looking for precisely.

**Comment by enshoe** [comment]
Thanks for the reply, I will see what I can do with the ws_client. My skills are limited, but I am determined to make this work one way or another.

Do you have any other suggestion for sharing entires between instances, if so, which one would make the most sense?

**Comment by enshoe** [comment]
This is the log from the ws_client, running 20 pairs and with the issue present.
ws client is using the config of consumer2, making it connect to consumer 1.

[ws_client.log](https://github.com/freqtrade/freqtrade/files/10783678/ws_client.log)

This is what I see in FreqUI:
![image](https://user-images.githubusercontent.com/27415969/220088196-f7763f85-5430-438f-ad28-538470693d01.png)

**Comment by xmatthias** [comment]
The end of the log shows the problem quite well:

```
2023-02-20 12:00:29,203 - WebSocketClient.Protocol - INFO - ['HIGH/BUSD', '1m', 'spot']
2023-02-20 12:00:29,204 - WebSocketClient.Protocol - INFO - Last analyzed datetime: 2023-02-20T10:59:56.997548+00:00
2023-02-20 12:00:29,204 - WebSocketClient.Protocol - INFO - Latest candle datetime: 2023-02-20 10:58:00+00:00
```

Your producer is not behind by 45s - but by 56s. 
On other pairs, like ICP - it's worse with 80s offset or more 

```
2023-02-20 12:00:28,001 - WebSocketClient.Protocol - INFO - ['ICP/BUSD', '1m', 'spot']
2023-02-20 12:00:28,001 - WebSocketClient.Protocol - INFO - Last analyzed datetime: 2023-02-20T11:00:20.815988+00:00
2023-02-20 12:00:28,002 - WebSocketClient.Protocol - INFO - Latest candle datetime: 2023-02-20 10:58:00+00:00
```

if you think times are increasing - are you sure that it's not the strategy itself that's increasing  times? 

> Do you have any other suggestion for sharing entires between instances, if so, which one would make the most sense?

Using producer/consumer mode is the correct way.
From what i've seen so far it's your strategy that's causing the problem. If your strategy is too slow, then no other transfer method will improve your results - as you're looking at the wrong part of the code.

**Comment by enshoe** [comment]
Sorry about that, I am working on two parallell systems and got them mixed up. I have redone the test with 20 active pairs.
Decreasing the workload by reducing the pairs should be a good enough anology to a slimmed down code.


Spikes to 10s are from where there are new information to be had.
Bootloop for consumer1:
```
2023-02-20 13:37:24,458 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 0.00 s, last iteration took 3.60 s.
2023-02-20 13:37:27,853 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 0.00 s, last iteration took 3.39 s.
2023-02-20 13:37:31,389 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 0.00 s, last iteration took 3.54 s.
2023-02-20 13:37:34,763 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 0.00 s, last iteration took 3.37 s.
2023-02-20 13:37:38,180 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 0.00 s, last iteration took 3.42 s.
2023-02-20 13:37:41,710 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 0.00 s, last iteration took 3.53 s.
2023-02-20 13:37:52,467 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 0.00 s, last iteration took 10.76 s.
```
Botloop for consumer2:
```
2023-02-20 13:38:32,475 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 0.00 s, last iteration took 6.24 s.
2023-02-20 13:38:38,250 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 0.00 s, last iteration took 5.77 s.
2023-02-20 13:38:43,850 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 0.00 s, last iteration took 5.60 s.
2023-02-20 13:38:49,310 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 0.00 s, last iteration took 5.46 s.
2023-02-20 13:38:54,778 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 0.00 s, last iteration took 5.43 s.
2023-02-20 13:39:00,295 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 0.00 s, last iteration took 5.51 s.
2023-02-20 13:39:05,298 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 0.00 s, last iteration took 4.99 s.
2023-02-20 13:39:15,428 - freqtrade.worker - DEBUG - Throttling with '_process_running()': sleep for 0.00 s, last iteration took 10.13 s.
```
And here is the log:
[ws_client.log](https://github.com/freqtrade/freqtrade/files/10785062/ws_client.log)

```
2023-02-20 14:45:57,101 - WebSocketClient.Protocol - INFO - ['MATIC/BUSD', '1m', 'spot']
2023-02-20 14:45:57,101 - WebSocketClient.Protocol - INFO - Last analyzed datetime: 2023-02-20T13:45:56.757948+00:00
2023-02-20 14:45:57,102 - WebSocketClient.Protocol - INFO - Latest candle datetime: 2023-02-20 13:44:00+00:00
```

As we can see, even with a maximum of ~10s botloop on consumer 1 and 2, we are getting delayed.
The full chain in this example is (Worst case): producer 15s, consumer1 10s, consumer2 10 s. So I dont understand why we are getting delayed dataframes. If I were to re-run the ws_client in 5 minutes time the avg. delay per pair would be longer, and tops out at round 10m and stays constans from that point on.

**Comment by xmatthias** [comment]
you're only looking at the consumers - not at the producer.
so the above is  pretty much pointless - as it's just showing that the consumers do not much. You'll however not see if the producer(s) are not keeping up.

You're also merging dataframes (your original diagram used 4 producers for consumer1)  - maybe wrongly, causing dropped candles(??) - and doing who knows what else that can cause problems.

Try your test with empty strategies which don't do any work at every level. 

The fact that it evens out after ~10m is unlogical - unless it's something data-related.
What are you restarting to reset that delay?

**Comment by enshoe** [comment]
> The full chain in this example is (Worst case): producer 15s, consumer1 10s, consumer2 10 s.

**The full chain here is ~35s, including the worst case producer.**

> What are you restarting to reset that delay?

a reload_config gets it caught up

Incorrectly merging dataframes could be a thing. This is the code I use for consumer 1 and consumer 2 (Both are 1m strats):
Code for consumer 1:
```
#######
    _producers = ['NFIX', 'Cluc', 'BB_RPB', 'Elliot']
    _producer_tfs = {
        'NFIX': '5m',
        'Cluc': '1m',
        'BB_RPB': '5m',
        'Elliot': '5m'
    }

    _columns_to_expect = {}

    for producer in _producers:
        _columns_to_expect[producer] = [
            f'enter_long_{producer}',
            f'enter_long_{producer}',
            f'enter_long_{producer}',
            f'enter_long_{producer}'
        ]

    def populate_indicators(self, df: DataFrame, metadata: dict) -> DataFrame:

        pair = metadata['pair']
        timeframe = self.timeframe
        producer_pairs = self.dp.get_producer_pairs()

        for producer in self._producers:

            producer_timeframe = self._producer_tfs[producer]
            producer_df, _ = self.dp.get_producer_df(pair, timeframe=producer_timeframe, producer_name=producer)

            if not producer_df.empty:

                df = merge_informative_pair(df, producer_df, timeframe,
                                                    producer_timeframe,
                                                    append_timeframe=False,
                                                    suffix=producer, ffill=False)

            else:
                df[self._columns_to_expect[producer]] = np.nan
        return df
```

Code for consumer 2:
```
    _columns_to_expect = ['enter_long_Cluc_Consumer', 'enter_long_NFIX_Consumer', 'enter_long_BB_RPB_Consumer', 'enter_long_Elliot_Consumer', 'enter_long_Consumer', 'enter_tag_Consumer']
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        pair = metadata['pair']
        timeframe = self.timeframe

        producer_pairs = self.dp.get_producer_pairs()
        producer_dataframe, _ = self.dp.get_producer_df(
            pair,
            producer_name="Consumer"
            )

        if not producer_dataframe.empty:
            merged_dataframe = merge_informative_pair(dataframe, producer_dataframe,
                                                      timeframe, timeframe,
                                                      append_timeframe=False,
                                                      suffix='Consumer', ffill=False)

            return merged_dataframe
        else:
            dataframe[self._columns_to_expect] = np.nan
        return dataframe
```

**Comment by xmatthias** [comment]
well that log doesn't really show anything delayed. 

```
2023-02-20 14:45:51,876 - WebSocketClient.Protocol - INFO - Time since last message: 0:0.771
2023-02-20 14:45:51,876 - WebSocketClient.Protocol - INFO - ['SHIB/BUSD', '1m', 'spot']
2023-02-20 14:45:51,877 - WebSocketClient.Protocol - INFO - Last analyzed datetime: 2023-02-20T13:45:51.515846+00:00
2023-02-20 14:45:51,877 - WebSocketClient.Protocol - INFO - Latest candle datetime: 2023-02-20 13:44:00+00:00
```

Last analyzed -> the current timestamp is less than 1 second apart. Assuming the log time is the host time in +1 timezone, and the last analyzed is "utc".

**Comment by enshoe** [comment]
A fresh log and accompanying image. In the image the latest available dataframe is XX.32, while the system shows XX.37.
[ws_client.log](https://github.com/freqtrade/freqtrade/files/10785766/ws_client.log)
![image](https://user-images.githubusercontent.com/27415969/220148834-249cc492-1ac9-4482-b704-6b7e2207fe85.png)

**Comment by enshoe** [comment]
![image2](https://user-images.githubusercontent.com/27415969/220161488-93ac6cd8-e89e-4c18-a412-bdd6f618baea.png)
Just captured, system time was XX:39. Even though its not the same pair they all behave roughly the same.

**Comment by xmatthias** [comment]
well the wsclient log still has practically no delay between "analyzed" and "received" timestamps (it's however also unclear where it's actually pointing to).

For now (based on the logs provided) i see no evidence of an actual delay.
if there is one - it's caused by the strategy. Try this with a minimal strategy (one indicator calculated only or using the sample strategy - no fancy logic) - and compare results to that.

**Comment by enshoe** [comment]
> (it's however also unclear where it's actually pointing to).

Its using the config of consumer2, which makes it connect to consumer1.


I will reduce the consumer 1 strategy to barebone, but the logic above (Where it gets the information from the producers) will stay. It was provided by paranoidandy and I am not savvy enough to alter it.

After that I will restart the experiment.

I am not expecting any different results though, my gut feeling tells me something is off with the dataframe at this point.
We see no actual delay in the ws log, meaning if the data is in the right place its sent.

Perhaps the merging of the different timeframes is the culprit after all. I can provide dataframe dumps from all the steps if that helps?

As I said, I am determined to figure this out and it will help other people trying the consumer/producer setup as extensively as I am :)

**Comment by xmatthias** [comment]
So in essence, you're pointing the client to consumer1 - and freqUI to consumer2?
So consumer2 might have a problem (waiting for "whatever" never happens) ... consumer1 can produce happily - but that's not what we're seeing anyway.

i know paranoidandy's setup works - as he was playing a key part in designing and testing this in the first place - and 
found multiple performance problems in the process.


In my opinion, your best bet is to start with empty strategies to observe behavior there. 
It'll reproduce - you can provide the full setup to reproduce this and we can have a look (i'll however not look at a scenario involving 1000 line strategies).

I know most of the strategies in your config (at least roughly) to know that they are quite heavy - and can take a lot longer than the timeframe if running them with too many pairs or configured poorly and/or on an undersized system.

**Comment by enshoe** [comment]
> So in essence, you're pointing the client to consumer1 - and freqUI to consumer2?

Correct

I have had no issues on consumer1, served by the 4 producers so far. It is acting fully as expected.

I can exclude NFIX too, thats no issue. Even though I cant proove it yet, something fishy is going on.
I will start with the dataframes because they are easy to get now. After that I will move to a barebone setup.

**Comment by enshoe** [comment]
Just noticed this on **consumer1**, I have not read through those logs in detail since I always thought that consumer2 was the culprit:
```
023-02-20 18:54:31,225 - freqtrade.strategy.interface - DEBUG - Populating enter signals for pair AGIX/BUSD.

2023-02-20 18:54:31,238 - freqtrade.strategy.interface - DEBUG - Populating exit signals for pair AGIX/BUSD.
2023-02-20 18:54:31,241 - freqtrade.rpc.rpc_manager - DEBUG - Forwarding message to rpc.telegram
*2023-02-20 18:54:31,243 - freqtrade.rpc.telegram - DEBUG - Unknown message type: analyzed_df*
2023-02-20 18:54:31,243 - freqtrade.rpc.rpc_manager - DEBUG - Forwarding message to rpc.apiserver
2023-02-20 18:54:31,243 - freqtrade.rpc.rpc_manager - DEBUG - Forwarding message to rpc.telegram
*2023-02-20 18:54:31,244 - freqtrade.rpc.telegram - DEBUG - Unknown message type: new_candle*
2023-02-20 18:54:31,244 - freqtrade.rpc.rpc_manager - DEBUG - Forwarding message to rpc.apiserver

2023-02-20 18:54:31,244 - freqtrade.strategy.interface - DEBUG - Loop Analysis Launched
2023-02-20 18:54:31,245 - freqtrade.strategy.interface - DEBUG - TA Analysis Launched
2023-02-20 18:54:31,245 - freqtrade.strategy.interface - DEBUG - Populating indicators for pair SOL/BUSD.
2023-02-20 18:54:31,340 - uvicorn.error - DEBUG - > TEXT '{"type":"new_candle","data":["AGIX/BUSD","1m","spot"]}' [54 bytes]
2023-02-20 18:54:31,418 - uvicorn.error - DEBUG - > TEXT '{"type":"analyzed_df","data":{"key":["AGIX/BUSD...8:54:31.241390+00:00"}}' [8186 bytes]
```


```
2023-02-20 18:58:08,182 - freqtrade.data.converter - DEBUG - Converting candle (OHLCV) data to dataframe for pair STX/BUSD.
*2023-02-20 18:58:08,195 - freqtrade.data.converter - DEBUG - Dropping last candle*
```

Highlighted with * I dont know if this means anything to you?

**Comment by enshoe** [comment]
Dataframes from:
Consumer1 1m (Merged from 4 producers, 3x 5m & 1x 1m strats)
Consumer2 1m (Merged from consumer1)
**These dataframes are taken early after restart, and should be in sync. Will update with new ones once they diverge.**
https://docs.google.com/spreadsheets/d/1x8lUJW2CdJgF34uI7ojPZq_hCGoNB0WJB1OrQGxcmAM/edit?usp=sharing

**Comment by xmatthias** [comment]
I guess since there has been no update, they didn't diverge after all ? 

At any rate (and as mentioned above) - you're best off looking at the dataframes before merging (on each step). So far, this feels like "fishing in the dark" - where you won't know what you're actually looking at other than "i feel something is off".
