### ISSUE TITLE
Indent and key error in the reinforcementlearner example in the latest branch

### ISSUE THREAD

**Issue by HeinrichHaller** [freqtrade/freqtrade#8199]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.10.6
  * CCXT version: ccxt==2.7.93
  * Freqtrade Version: freqtrade 2023.2.dev-a11f081d2
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. copy and paste the MyCoolRLModel in https://www.freqtrade.io/en/latest/freqai-reinforcement-learning/, four lines  don't have the right indent
  2. the string here generated: `# you can use feature values from dataframe
            rsi_now = self.raw_features[f"%-rsi-period-10_shift-1_{self.pair}_"
                              f"{self.config['timeframe']}"].iloc[self._current_tick]`
leads to a key error. `2023-02-21 00:06:25,604 - freqtrade.freqai.freqai_interface - WARNING - Training ALGO/USDT:USDT raised exception KeyError. Message: '%-rsi-period-10_shift-1_ALGO/USDT:USDT_3m', skipping.`
RSI is not tagged with raw_features here anyways?
Thanks

**Comment by xmatthias** [comment]
i don't think it's just 4 lines - most likely, the complete "if" block below is dedented too much (up to the `return 25 *`).

https://github.com/freqtrade/freqtrade/blob/352f4962dafde5e92f92ba1174605607caf031ea/docs/freqai-reinforcement-learning.md?plain=1#L179-L190

It'll depend a bit on the intend here though .... 
@robcaulk, mind to take a look at this, please? I'm not entirely sure what the intend here is, which will change how much needs to be indented differently.

**Comment by robcaulk** [comment]
> i don't think it's just 4 lines - most likely, the complete "if" block below is dedented too much (up to the `return 25 *`).
> 
> https://github.com/freqtrade/freqtrade/blob/352f4962dafde5e92f92ba1174605607caf031ea/docs/freqai-reinforcement-learning.md?plain=1#L179-L190
> 
> It'll depend a bit on the intend here though .... @robcaulk, mind to take a look at this, please? I'm not entirely sure what the intend here is, which will change how much needs to be indented differently.

Two things:

Firstly, OP is right that there is an indentation issue in the sample code of the doc. To be precise, lines 179 - 190 need indentation.

Secondly, for the `KeyError` does depend on the user having added the feature. This feature is included in the `FreqaiExampleStrategy.py`, but it is true that some other users may not have this feature and would be confused. 

If you are worried this will confuse users, then we can comment the example usage out (would need commenting in the below `if` statement as well in that case). Personally, I would prefer to leave it uncommented.

Cheers,

Robert

**Comment by HeinrichHaller** [comment]
I did run the standard FreqaiExampleStrategy.py (with the proposed changes for RL) with the feature expansion untouched. And I left `indicator_periods_candles`:
10 and 20 in the config as well. 
Maybe you could consider to explain the naming scheme to access the current value of one or more of the generated features. Especially with moving on from `populate_any_indicators` to hard wired expansion.
Are all features expanded under self.raw_features?

**Comment by HeinrichHaller** [comment]
The error from the beginning still exists for me. The reason is a missing colon:
`
_ALGO/USDTUSDT_1h', '%-rsi-period_10_BTC/USDTUSDT_3m', '%-rsi-period_20_BTC/USDTUSDT_3m', '%-rsi-period_10_shift-1_BTC/USDTUSDT_3m', '%-rsi-period_20_shift-1_BTC/USDTUSDT_3m', '%-rsi-period_10_shift-2_BTC/USDTUSDT_3m', '%-rsi-period_20_shift-2_BTC/USDTUSDT_3m', '%-rsi-period_10_BTC/USDTUSDT_15m', '%-rsi-period_20_BTC/USDTUSDT_15m', '%-rsi-period_10_shift-1_BTC/USDTUSDT_15m', '%-rsi-period_20_shift-1_BTC/USDTUSDT_15m', '%-rsi-period_10_shift-2_BTC/USDTUSDT_15m', '%-rsi-period_20_shift-2_BTC/USDTUSDT_15m', '%-rsi-period_10_BTC/USDTUSDT_1h', '%-rsi-period_20_BTC/USDTUSDT_1h', '%-rsi-period_10_shift-1_BTC/USDTUSDT_1h', '%-rsi-period_20_shift-1_BTC/USDTUSDT_1h', '%-rsi-period_10_shift-2_BTC/USDTUSDT_1h', '%-rsi-period_20_shift-2_BTC/USDTUSDT_1h', '%-rsi-period
`
in self.raw_features.
Whereas the string generated presents the pair as 'BTC/USDT:USDT'
`1INCH/USDT:USDT raised exception KeyError. Message: '%-rsi-period-10_shift-1_1INCH/USDT:USDT_3m`
And I actually updated via ./setup -u to 
freqtrade 2023.3.dev-108a57877

**Comment by HeinrichHaller** [comment]
But I am quite insecure about my updating skills tho.

**Comment by xmatthias** [comment]
`'%-rsi-period-10_shift-1_1INCH/USDT:USDT_3m` should be `'%-rsi-period-10_shift-1_1INCH/USDTUSDT_3m`.
we're replacing ":" for columns as that created problems with lightgbm models.

**Comment by HeinrichHaller** [comment]
Thanks for the answer,
MyCoolRLModel still genreates the colon:
`rsi_now = self.raw_features[f"%-rsi-period-10_shift-1_{self.pair}_"
                            f"{self.config['timeframe']}"].iloc[self._current_tick]`

**Comment by xmatthias** [comment]
well as said above - we replace ":" with "", so something around `pair.replace(':', '')` should work.

**Comment by HeinrichHaller** [comment]
`ing 1INCH/USDT:USDT --------------------
2023-03-05 14:48:37,133 - freqtrade.freqai.data_kitchen - INFO - dropped 0 training points due to NaNs in populated dataset 7199.
2023-03-05 14:48:37,917 - freqtrade.freqai.RL.BaseReinforcementLearningModel - INFO - Training model on 573 features and 4823 data points
['%-rsi-period_10_1INCH/USDTUSDT_3m', '%-rsi-period_20_1INCH/USDTUSDT_3m', '%-rsi-period_10_shift-1_1INCH/USDTUSDT_3m', '%-rsi-period_20_shift-1_1INCH/USDTUSDT_3m', '%-rsi-period_10_shift-2_1INCH/USDTUSDT_3m', '%-rsi-period_20_shift-2_1INCH/USDTUSDT_3m', '%-rsi-period_10_1INCH/USDTUSDT_15m', '%-rsi-period_20_1INCH/USDTUSDT_15m', '%-rsi-period_10_shift-1_1INCH/USDTUSDT_15m', '%-rsi-period_20_shift-1_1INCH/USDTUSDT_15m', '%-rsi-period_10_shift-2_1INCH/USDTUSDT_15m', '%-rsi-period_20_shift-2_1INCH/USDTUSDT_15m', '%-rsi-period_10_1INCH/USDTUSDT_1h', '%-rsi-period_20_1INCH/USDTUSDT_1h', '%-rsi-period_10_shift-1_1INCH/USDTUSDT_1h', '%-rsi-period_20_shift-1_1INCH/USDTUSDT_1h', '%-rsi-period_10_shift-2_1INCH/USDTUSDT_1h', '%-rsi-period_20_shift-2_1INCH/USDTUSDT_1h', '%-rsi-period_10_BTC/USDTUSDT_3m', '%-rsi-period_20_BTC/USDTUSDT_3m', '%-rsi-period_10_shift-1_BTC/USDTUSDT_3m', '%-rsi-period_20_shift-1_BTC/USDTUSDT_3m', '%-rsi-period_10_shift-2_BTC/USDTUSDT_3m', '%-rsi-period_20_shift-2_BTC/USDTUSDT_3m', '%-rsi-period_10_BTC/USDTUSDT_15m', '%-rsi-period_20_BTC/USDTUSDT_15m', '%-rsi-period_10_shift-1_BTC/USDTUSDT_15m', '%-rsi-period_20_shift-1_BTC/USDTUSDT_15m', '%-rsi-period_10_shift-2_BTC/USDTUSDT_15m', '%-rsi-period_20_shift-2_BTC/USDTUSDT_15m', '%-rsi-period_10_BTC/USDTUSDT_1h', '%-rsi-period_20_BTC/USDTUSDT_1h', '%-rsi-period_10_shift-1_BTC/USDTUSDT_1h', '%-rsi-period_20_shift-1_BTC/USDTUSDT_1h', '%-rsi-period_10_shift-2_BTC/USDTUSDT_1h', '%-rsi-period_20_shift-2_BTC/USDTUSDT_1h', '%-rsi-period_10_ETH/USDTUSDT_3m', '%-rsi-period_20_ETH/USDTUSDT_3m', '%-rsi-period_10_shift-1_ETH/USDTUSDT_3m', '%-rsi-period_20_shift-1_ETH/USDTUSDT_3m', '%-rsi-period_10_shift-2_ETH/USDTUSDT_3m', '%-rsi-period_20_shift-2_ETH/USDTUSDT_3m', '%-rsi-period_10_ETH/USDTUSDT_15m', '%-rsi-period_20_ETH/USDTUSDT_15m', '%-rsi-period_10_shift-1_ETH/USDTUSDT_15m', '%-rsi-period_20_shift-1_ETH/USDTUSDT_15m', '%-rsi-period_10_shift-2_ETH/USDTUSDT_15m', '%-rsi-period_20_shift-2_ETH/USDTUSDT_15m', '%-rsi-period_10_ETH/USDTUSDT_1h', '%-rsi-period_20_ETH/USDTUSDT_1h', '%-rsi-period_10_shift-1_ETH/USDTUSDT_1h', '%-rsi-period_20_shift-1_ETH/USDTUSDT_1h', '%-rsi-period_10_shift-2_ETH/USDTUSDT_1h', '%-rsi-period_20_shift-2_ETH/USDTUSDT_1h']
pair notation: 1INCH/USDTUSDT
2023-03-05 14:48:37,926 - freqtrade.freqai.freqai_interface - WARNING - Training 1INCH/USDT:USDT raised exception KeyError. Message: '%-rsi-period-10_shift-1_1INCH/USDTUSDT_3m', skipping.
2023-03-05 14:48:39,443 - freqtrade.freqai.RL.BaseReinforcementLearningModel - INFO - --------------------Starting training ALGO/USDT:USDT --------------------
2023-03-05 14:48:39,569 - freqtrade.freqai.data_kitchen - INFO - dropped 0 training points due to NaNs in populated dataset 7199.
2023-03-05 14:48:40,425 - freqtrade.freqai.RL.BaseReinforcementLearningModel - INFO - Training model on 573 features and 4823 data points
['%-rsi-period_10_ALGO/USDTUSDT_3m', '%-rsi-period_20_ALGO/USDTUSDT_3m', '%-rsi-period_10_shift-1_ALGO/USDTUSDT_3m', '%-rsi-period_20_shift-1_ALGO/USDTUSDT_3m', '%-rsi-period_10_shift-2_ALGO/USDTUSDT_3m', `

thanks, a hyphen has to replaced with a underscore as well.

**Comment by HeinrichHaller** [comment]
`rsi_now = self.raw_features[f"%-rsi-period_10_shift-1_{self.pair.replace(':','')}_"
                            f"{self.config['timeframe']}"].iloc[self._current_tick]`
after the period
