### ISSUE TITLE
how to incorporate custom features the best way with FreqaiExampleStrategy

### ISSUE THREAD

**Issue by HeinrichHaller** [freqtrade/freqtrade#8200]
## Describe your environment

  * Operating system:  Ubuntu LTS
  * Python Version:  3.10.6
  * CCXT version:  ccxt==2.7.93
  * Freqtrade Version: freqtrade 2023.2.dev-a11f081d2
  
## Your question

With the new hardwired layout in the new FreqaiExampleStrategy with:
 `    def feature_engineering_expand_all(self, dataframe: DataFrame, period: int,
                                       metadata: Dict, **kwargs):
def feature_engineering_expand_basic(self, dataframe: DataFrame, metadata: Dict, **kwargs):
def feature_engineering_standard(self, dataframe: DataFrame, metadata: Dict, **kwargs):
`
and the hiding of the loops, it gets in my opinion harder to add custom features that for instance rely on a custom nested loop.
Or even easier I want the ema's from 10 to 100 added but not the rest.
Where to put the custom features in with the new layout?
Thanks

**Comment by xmatthias** [comment]
best read through the [defining features](https://www.freqtrade.io/en/latest/freqai-feature-engineering/#defining-the-features) table in the documentation - it explains which function is best used for what and how (often) it's called.

Based on your description, i get you don't want any "automatic" expansion - just a function that's called once, and allows you to add whatever features.

`feature_engineering_standard` will be your way to go.

> This optional function will be called once with the dataframe of the base timeframe. 
> ...
> This function is also a good place for any feature that should not be auto-expanded upon

**Comment by robcaulk** [comment]
Hello,

Although @xmatthias is exactly right, for archival purposes, I'd like to point to the variety of places in the documentation that all repeat what Matthias has said:

A clear table in the documentation:
https://www.freqtrade.io/en/latest/freqai-feature-engineering/#defining-the-features

Docstrings in the FreqaiExampleStrategy:
https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/templates/FreqaiExampleStrategy.py#L154

And even a migration documentation highlighting this:
https://www.freqtrade.io/en/latest/strategy_migration/#freqai-strategy

Thanks for, next time, taking the time to refer to which parts of these documentations are confusing to you. This will allow us to further improve the documentation. 

Cheers,

Robert

**Comment by HeinrichHaller** [comment]
Thanks, that what I assumed.
For me was def populate_any_indicators way more intuitive, because the naming and loops are directly visible and it fosters the in-cooperation of new features. The hard-wiring of the expansion tugs an important feature away.  
Now I have to put the loops in 'feature_engineering_standard'. Makes it for me not less messy.

**Comment by HeinrichHaller** [comment]
> Hello,
> 
> Although @xmatthias is exactly right, for archival purposes, I'd like to point to the variety of places in the documentation that all repeat what Matthias has said:
> 
> A clear table in the documentation: https://www.freqtrade.io/en/latest/freqai-feature-engineering/#defining-the-features
> 
> Docstrings in the FreqaiExampleStrategy: https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/templates/FreqaiExampleStrategy.py#L154
> 
> And even a migration documentation highlighting this: https://www.freqtrade.io/en/latest/strategy_migration/#freqai-strategy
> 
> Thanks for, next time, taking the time to refer to which parts of these documentations are confusing to you. This will allow us to further improve the documentation.
> 
> Cheers,
> 
> Robert

Just as follow up, do you have good results with the this way of generating features? Based upon talib that itself is based on subtracting EMAs and SMAs. And all the oscillators are quite redundant.
Replacing `self.freqai_info["feature_parameters"]["indicator_periods_candles"]` with
`metadata["period"], adds a layer of complexity. How to access new parameters? 

Generally speaking the new approach makes feature creation more difficult. Just have a look at Kaggle to see the importance of new features in ts modeling.

Best Regards

**Comment by robcaulk** [comment]
Hello,

I don't follow the logic. You have the same capabilities now with
`feature_engineering_standard()` as you had with
`populate_any_indicators()` before.

> Replacing
self.freqai_info["feature_parameters"]["indicator_periods_candles"] with
`metadata["period"], adds a layer of complexity. How to access new
parameters?

`self.freqai_info` is not replaced by `metadata`. You can still add any
parameters you want to your freqai config, and you can still access those
the same way as you did before with `self.freqai_info`. `metadata` is
providing information about which pair/timeframe is entering the
`feature_engineering_expand_*` functions so users can use flags to
add/avoid features based on these parameters.

You seem upset that we have cleaned up and simplified the code for casual
users (and we also improved backtesting accuracy with this paradigm). You
miss that we provide you with the ability to make as much of a mess with as
many loops as you want, inside `feature_engineering_standard`. Your
approach doesnt change between before and after, as far as I can tell. Your
point about losing access to `self.freqai_info` is just incorrect, you can
access that with the same exact `self.freqai_info` as before.

Please elaborate what is the problem?

Cheers,

Robert

p.s.

> Just have a look at Kaggle to see the importance of new features in ts
modeling.

? I turn the statement back to you: "Just have a look" at our documentation
to see the features of the software you are using.

**Comment by HeinrichHaller** [comment]
You are surely correct with `self.freqai_info` not being replaced. Sorry for that. As far as my problem goes, it is the over-reliance on talib. So much that it is even hardwired into the example function. 

Let's say you get inspired by https://towardsdatascience.com/aifortrading-2edd6fac689d#f039 Fig.6 and you want to add EMAs over more periods. Or add the MACD over more than the  existing12,16, 9 in a nested loop. These examples already improve the end result quite a bit
Or you want to run the never old FFT over multiple timeframes(via numpy, no extra imports needed.)
All the needed loops for such easy improvements (for making more money) are now hidden away.

Are you improving your results with simply adding more timeframes, periods and shifts based on the standard talib features? Because this is what people end up with.  

And sorry for coming around as upset... I value your work and it indeed brings me and a lot of other people closer to the fancy AI stuff.

**Comment by HeinrichHaller** [comment]
I am probably quite annoying.. 
`metadata in expand_all: {'pair': 'ALGO/USDT:USDT', 'tf': '1h'}
metadata in expand_bsic: {'pair': 'ALGO/USDT:USDT', 'tf': '1h'}
metadata in standard: {'pair': 'ALGO/USDT:USDT'}
metadata in expand_all: {'pair': 'BTC/USDT:USDT', 'tf': '3m'}
metadata in expand_all: {'pair': 'BTC/USDT:USDT', 'tf': '3m'}
metadata in expand_bsic: {'pair': 'BTC/USDT:USDT', 'tf': '3m'}`


I figured quite lately, that in `feature_engineering_standard(self, dataframe: DataFrame, metadata: Dict, **kwargs):`
the correlation pairs are not in the metadata. How would it look like to run a loop over the traded and correlation pairs? I've seen in data_kitchen.py to run the correlation pairs last? 


` dataframe = strategy.feature_engineering_standard(dataframe.copy(), metadata=metadata)
        # ensure corr pairs are always last
        for corr_pair in corr_pairs:
            if pair == corr_pair:
                continue  # dont repeat anything from whitelist
            if corr_pairs and do_corr_pairs:
                dataframe = self.populate_features(dataframe.copy(), corr_pair, strategy,
                                                   corr_dataframes, base_dataframes, True)`



Is there some way to get the imports into `feature_engineering_standard(self, dataframe: DataFrame, metadata: Dict, **kwargs):` 

like in 
`def populate_any_indicators(
        self, pair, df, tf, informative=None, set_generalized_indicators=False
    ):`
covering all the general config parameters and the freqai related with `self.freqai_info`?
Without breaking `feature_engineering_standard(self, dataframe: DataFrame, metadata: Dict, **kwargs):`



How to get for instance the percentage change over different periods(not the standard 10, 20 in the config) like in `DataFrame.pct_change(periods=1, fill_method='pad', limit=None, freq=None, **kwargs)` for all pairs? Could I do this in `feature_engineering_expand_basic(self, dataframe: DataFrame, metadata: Dict, **kwargs):`?

Or better put everything in populate_indicators?

Thanks
