### ISSUE TITLE
docker vs ./setup.sh install and pathes needed for hyperopt 

### ISSUE THREAD

**Issue by HeinrichHaller** [freqtrade/freqtrade#8201]
## Describe your environment

  * Operating system: Ubuntu LTS
  * Python Version:  3.10.6
  * CCXT version:  ccxt==2.7.93
  * Freqtrade Version: freqtrade 2023.2.dev-a11f081d2
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

I got a setup now where I have a freqtrade install via ./setup.sh in VS so I can debug the code with additional dependencies. Then some second user_data with another git and everything that is needed for docker in a subsequent folder.
For docker in combination wit hyperopt I ended up with something like:

`from user_data.strategies import ssm`,

whereas for the ./setup.sh only somethong like:
`import ssm`,  
works.

How to solve this? 
Maybe you can even recommend a setup for developing and deploying afterwards when additional dependencies are used?
Thanks

**Comment by xmatthias** [comment]
Hyperopt is using multiple processes - which means the strategy needs to be pickled (and then unpickled).
While that's a technical detail that's mostly uninteresting for the user, it leaves one base premise - which is that the module needs to be resolvable as part of the available python import path.

The easiest and best way is to have whatever extra dependency you need installable (`pip install ...`) - that's the easiest way to go about this - leaving python to do the hard work.

Based on your description, i assume that `ssm` is either a single file, or a package (directory containing a `__init__.py` file), that's residing in `user_data/strategies`.

`import ssm` is most likely the wrong approach, as it's relying on some implicit path magic that python does (but depending on HOW you start freqtrade, does not do reliably).

For the rest, it'll depend on what exactly `ssm` is (file, package, ...) - and where it's actually located - and what the actual problem / error is you're seeing.
The way you ask this question leaves a lot of guesswork, which makes it near impossible to actually help you.

**Comment by HeinrichHaller** [comment]
Thanks for the answer!
when I copy qtpylib to user_data/strategies as qtpylib2 and import it as 
`import qtpylib2 as qtpylib`,
within the ExampleStrategy
everything works under a ./setup.sh install. The pickleing(?) as well.

This does not work when I run it in a docker container.
There I need to declare the import as
`from user_data.strategies import qtpylib2 as qtpylib`,
to make the hyperopt working.

The question is how to get the imports the same way, regardless the environment.
ssm is are just some state space models. In a single file located in user_data/strategies/ssm with additional imports, so I get everything back as pd.Series in the actual strategy.

**Comment by HeinrichHaller** [comment]
Or just having another file under user_data/strategies/MACDVariotions.py with switched filters to DEMA or so, without additional dependencies. The import would be inconsistent for me.

**Comment by HeinrichHaller** [comment]
Without testing it, putting for instance MACDVar.py in another folder like user_data/additional_indicators/MACDVar.py
and importing it from the root consistently should work?

**Comment by xmatthias** [comment]
> Without testing it, putting for instance MACDVar.py in another folder like user_data/additional_indicators/MACDVar.py and importing it from the root consistently should work?

no - that's not how python importing works. It works if you do some extra work (ensure all directories alongside are packages) - but not with JUST the file in the directory structure.

**Comment by xmatthias** [comment]
doing some tests with this:
Doing the import as `from user_data.strategies import qtpylib2 as qtpylib` works perfectly fine - **assuming** it's actually in the right directory (the user_data directory mounted to the docker-compose folder, and using `--userdir user_data` (or nothing)).

the most likely problem you'll encounter with this is that it assumes the import is `./user_data/strategies/qtpylib2`.
this works fine on both docker and natively (obviously assuming the path remains identical - and no `--user-dir` is used.

---

the actually correct way is `import qtpylib2` or `import qtpylib2 as qtpylib`.
This is documented [here](https://www.freqtrade.io/en/latest/strategy-advanced/#derived-strategies) for derived strategies, but also works for all other "file-based" imports.

This assumes the files are alongside each other within the strategies directory.
```
├── strategies
    ├── qtpylib2.py
    └── sample_strategy.py

```

I've tested this in 3 scenarios: 
* docker-compose hyperopt
* native hyperopt with `--userdir <someotherdir>`
* native hyperopt in `user_data` (no `--userdir` passed in.

all of these work just fine.
