### ISSUE TITLE
How to disable force_exit?

### ISSUE THREAD

**Issue by sebastianmacias** [freqtrade/freqtrade#8206]
## Describe your environment

  * Operating system: MacOs
  * Python Version: 3.10.10
  * CCXT version: 2.7.93
  * Freqtrade Version: 2023.2.dev
  
## Your question

I'm testing a strategy that requires to no stop loss. I noticed that when I disable the stop loss there is a force_exit listed as exit_reason on the backtesting results. The force_exit seems to happen when an open position reaches a profit ratio of -0.48.

How can I disable this force_exit?

**Comment by xmatthias** [comment]
You cannot - it's simply the trades that are open at the end of the backtest period.

the [documentation](https://www.freqtrade.io/en/stable/backtesting/#left-open-trades-table) explains this too, including the why it's included.

**Comment by sebastianmacias** [comment]
Understood, thanks
