### ISSUE TITLE
Downloaded Binance data prices do not match Binance prices

### ISSUE THREAD

**Issue by sebastianmacias** [freqtrade/freqtrade#8208]
## Describe your environment

  * Operating system: MacOS
  * Python Version: 3.10.10
  * CCXT version: 2.7.93
  * Freqtrade Version: 2023.2.dev
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Downloaded Binance data prices do not match Binance prices

### Steps to reproduce:

  1. config.json
  ```
{
    "max_open_trades": 1,
    "stake_currency": "BTC",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.90,
    "fiat_display_currency": "BTC",
    "dry_run": true,
    "dry_run_wallet": 10000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "xxxx",
        "secret": "xxxx",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
            "ETC/BTC"
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList",
            "number_assets": 1,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": true,
        "token": "xxxx",
        "chat_id": "xxxx"
    },
    "api_server": {
        "enabled": false,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "xxxx",
        "ws_token": "xxxx",
        "CORS_origins": [],
        "username": "",
        "password": ""
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```
 
 2. Download data
  ```
$ freqtrade download-data -t 1d --timerange 20230220-20230221
```

  3. Check downloaded data
  ```
  [
    [
        1676851200000,
        0.000928,
        0.000952,
        0.000913,
        0.000933,
        78659.33
    ],
    [
        1676937600000,
        0.000935,
        0.000974,
        0.00092,
        0.000934,
        216078.51
    ]
]
  ```
  3. Check Binance ETC/BTC prices
  
  ```
20230220 = 0.0678
 ```
  
### Observed Results:

  * What happened?
  
  The downloaded price for 20230220 is 0.0009... and the Binance price is 0.0678.. The price do not math.
  
  * What did you expect to happen?
  
  Prices should be approximately the same

**Comment by xmatthias** [comment]
checking your first entry - which is for 20230220:
 [
      1676851200000,
      0.000928,
      0.000952,
      0.000913,
      0.000933,
      78659.33
  ],

![image](https://user-images.githubusercontent.com/5024695/220748370-4e23a8bf-694c-481a-9916-d51d0bfdd531.png)


now i'm not sure what you looked at (maybe wrong pair?) - but ETC/BTC price wasn't <0.009 (nor above 0.0012) within months ... not on binance, anyway ("a bit" of the months are covered in the screenshot above).

every single number in the screenshot exactly matches the data on exchange - except for volume, which the exchange shows in 78.659k - omitting the .33 BTC which you got in the data.

**Comment by sebastianmacias** [comment]
Thanks for your quick reply:

Here is the price of ETH/BTC on Binance for 20230220. It's 0.067809

<img width="1120" alt="ETCBTC" src="https://user-images.githubusercontent.com/167750/220782004-1693679b-f97c-43b2-8cf6-c3cca96fab73.png">

And the price Freqtrade downloaded for ETC/BTH running:

```
$ freqtrade download-data -t 1d --timerange 20230220-20230221

```

```
  [
    [
        1676851200000,
        0.000928,
        0.000952,
        0.000913,
        0.000933,
        78659.33
    ],
    ....
]
  ```

It doesn't match

**Comment by stash86** [comment]
Look at your config again. You are downloading ETC/BTC data, not ETH/BTC data. And I just checked binance, that data matched ETC/BTC price

**Comment by stash86** [comment]
![Uploading 5F38EBB9-53EF-4849-928A-8D8C86556E27.jpeg…]()

**Comment by stash86** [comment]
![2D548BFC-0C35-49C4-8B5D-E5EC2B72A919](https://user-images.githubusercontent.com/13656154/220791524-e825ebcc-807f-4a32-9343-fcad3fb7e4dd.jpeg)

**Comment by sebastianmacias** [comment]
My bad, thanks for your help.
