### ISSUE TITLE
Memory leak when using ReinforcementLearner_multiproc. Endless Python processes generation.

### ISSUE THREAD

**Issue by dblyzniuk** [freqtrade/freqtrade#8213]
## Describe your environment

  * Operating system: Linux Mint 21.1
  * Python Version: 3.10.10(`python -V`)
  * CCXT version: 2.8.17 (`pip freeze | grep ccxt`)
  * Freqtrade Version: docker-2023.2.dev-e56bf067 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

When using the _**ReinforcementLearner_multiproc.py**_ model, over time, a large number of Python instances are launched, which are closed only if the container is stopped or manually killed.

### Steps to reproduce:

1. Start container using appropriate config and strategy using **_ReinforcementLearner_multiproc_**
2. Open System Monitor.
3. Watch how Python instances are created when training starts, but not deleted when it ends.
  
### Observed Results:

When training starts for a particular ticker, a large number of Python instances are added, as expected.
When the training of the next ticker starts, new Python instances are added additionally, while the old ones are not deleted, although they show 0% CPU load.
In my opinion, Python instances should be deleted after training is complete, before new ones are added.

### Relevant code exceptions or logs

I was able to fix the issue on my setup by adding the following lines of code to the **_set_train_and_eval_environment_** method of the **_ReinforcementLearner_multiproc_** class, before the functions that create the training environments.

```
if self.train_env :
    self.train_env.close()
if self.eval_env :
    self.eval_env.close()
```

**Comment by robcaulk** [comment]
Thanks for the report. Two points: you say "memory leak" but we havent observed a memory leak with `ReinforcementLearner_multiproc` running 1 month without interruption. 

So is it in-fact the RAM that you are seeing going up, or is it only the htop process list that is increasing? 

Thanks,

Robert

**Comment by dblyzniuk** [comment]
> Thanks for the report. Two points: you say "memory leak" but we havent observed a memory leak with `ReinforcementLearner_multiproc` running 1 month without interruption.
> 
> So is it in-fact the RAM that you are seeing going up, or is it only the htop process list that is increasing?
> 
> Thanks,
> 
> Robert

I may have misused the terms, I'm a little new to PC programming. Each process that I see in your top individually works fine, there is no memory leak for a particular one process.

However, I see endless creation of python processes, each taking up roughly the same amount in the range of 200-400MB of RAM, depending on the strategy.


An example of how this happens, for this I used `rl_config: cpu_count: 12`:
1. Bot start. (The freqtrade process appears, everything is ok with it)
2. Message: --------------------Starting training SUSHI/USDT:USDT --------------------
3. Python processes are added one by one
4. Added 12 python processes 347.2MB each
5. Added 12 python processes 328.1MB each
6. Message: -------------------done training SUSHI/USDT:USDT--------------------
7. All 24 python processes remain in memory, CPU usage for them: 0%
8.Message: --------------------Starting training DOGE/USDT:USDT --------------------
9. The old 24 processes are still in memory, new ones are starting to be added.
10. Added 12 python processes 347.2MB each
11. Added 12 python processes 328.1MB each
12. Message: --------------------done training DOGE/USDT:USDT--------------------
13. All 48 Python processes remain in memory, CPU usage for them: 0%
14. Message: --------------------Starting training SUSHI/USDT:USDT --------------------
15. Old 48 processes are still in memory, new ones are starting to be added
16. Added 12 python processes 347.2MB each
17. Added 12 python processes 328.1MB each
.
.
.
And so on, until all my installed 64 GB of RAM are occupied by python processes.

I hope this clarified the situation.

Thank you for your interest

**Comment by robcaulk** [comment]
> > Thanks for the report. Two points: you say "memory leak" but we havent observed a memory leak with `ReinforcementLearner_multiproc` running 1 month without interruption.
> > So is it in-fact the RAM that you are seeing going up, or is it only the htop process list that is increasing?
> > Thanks,
> > Robert
> 
> I may have misused the terms, I'm a little new to PC programming. Each process that I see in your top individually works fine, there is no memory leak for a particular one process.
> 
> However, I see endless creation of python processes, each taking up roughly the same amount in the range of 200-400MB of RAM, depending on the strategy.
> 
> An example of how this happens, for this I used `rl_config: cpu_count: 12`:
> 
>     1. Bot start. (The freqtrade process appears, everything is ok with it)
> 
>     2. Message: --------------------Starting training SUSHI/USDT:USDT --------------------
> 
>     3. Python processes are added one by one
> 
>     4. Added 12 python processes 347.2MB each
> 
>     5. Added 12 python processes 328.1MB each
> 
>     6. Message: -------------------done training SUSHI/USDT:USDT--------------------
> 
>     7. All 24 python processes remain in memory, CPU usage for them: 0%
>        8.Message: --------------------Starting training DOGE/USDT:USDT --------------------
> 
>     8. The old 24 processes are still in memory, new ones are starting to be added.
> 
>     9. Added 12 python processes 347.2MB each
> 
>     10. Added 12 python processes 328.1MB each
> 
>     11. Message: --------------------done training DOGE/USDT:USDT--------------------
> 
>     12. All 48 Python processes remain in memory, CPU usage for them: 0%
> 
>     13. Message: --------------------Starting training SUSHI/USDT:USDT --------------------
> 
>     14. Old 48 processes are still in memory, new ones are starting to be added
> 
>     15. Added 12 python processes 347.2MB each
> 
>     16. Added 12 python processes 328.1MB each
>         .
>         .
>         .
>         And so on, until all my installed 64 GB of RAM are occupied by python processes.
> 
> 
> I hope this clarified the situation.
> 
> Thank you for your interest

Thanks for the clarification, how are you tracking the number of processes in this log?

With the associated #8216 you dont see the increase in process number anymore (it is simply the code you suggested in the original post)?

Cheers,

Robert

**Comment by dblyzniuk** [comment]
> > > Thanks for the report. Two points: you say "memory leak" but we havent observed a memory leak with `ReinforcementLearner_multiproc` running 1 month without interruption.
> > > So is it in-fact the RAM that you are seeing going up, or is it only the htop process list that is increasing?
> > > Thanks,
> > > Robert
> > 
> > 
> > I may have misused the terms, I'm a little new to PC programming. Each process that I see in your top individually works fine, there is no memory leak for a particular one process.
> > However, I see endless creation of python processes, each taking up roughly the same amount in the range of 200-400MB of RAM, depending on the strategy.
> > An example of how this happens, for this I used `rl_config: cpu_count: 12`:
> > ```
> > 1. Bot start. (The freqtrade process appears, everything is ok with it)
> > 
> > 2. Message: --------------------Starting training SUSHI/USDT:USDT --------------------
> > 
> > 3. Python processes are added one by one
> > 
> > 4. Added 12 python processes 347.2MB each
> > 
> > 5. Added 12 python processes 328.1MB each
> > 
> > 6. Message: -------------------done training SUSHI/USDT:USDT--------------------
> > 
> > 7. All 24 python processes remain in memory, CPU usage for them: 0%
> >    8.Message: --------------------Starting training DOGE/USDT:USDT --------------------
> > 
> > 8. The old 24 processes are still in memory, new ones are starting to be added.
> > 
> > 9. Added 12 python processes 347.2MB each
> > 
> > 10. Added 12 python processes 328.1MB each
> > 
> > 11. Message: --------------------done training DOGE/USDT:USDT--------------------
> > 
> > 12. All 48 Python processes remain in memory, CPU usage for them: 0%
> > 
> > 13. Message: --------------------Starting training SUSHI/USDT:USDT --------------------
> > 
> > 14. Old 48 processes are still in memory, new ones are starting to be added
> > 
> > 15. Added 12 python processes 347.2MB each
> > 
> > 16. Added 12 python processes 328.1MB each
> >     .
> >     .
> >     .
> >     And so on, until all my installed 64 GB of RAM are occupied by python processes.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope this clarified the situation.
> > Thank you for your interest
> 
> Thanks for the clarification, how are you tracking the number of processes in this log?
> 
> With the associated #8216 you dont see the increase in process number anymore (it is simply the code you suggested in the original post)?
> 
> Cheers,
> 
> Robert

Most often I use the default for Gnome graphical `System Monitor v42.0`, I also use the `htop` to monitor processes using the terminal, the results are the same. To clarify: I also see an actual increase in the percentage of used memory over time and if I do not manually intervene and stop, I see 100% used memory including swap and related problems in the operation of the OS.

With the added lines, everything works fine, all old processes are removed before new ones are created, and I don't see more than 24 python processes while running (for the same settings I specified earlier). I tested this on my system for about 48 hours. On the same settings I previously ran out of memory in less than 2 hours.

Here is an example of how it works with added lines:

```
1. Bot start.
2. Message: --------------------Starting training SUSHI/USDT:USDT --------------------
3. Python processes are added one by one
4. Added 12 python processes 347.2MB each
5. Added 12 python processes 328.1MB each
6. Message: -------------------done training SUSHI/USDT:USDT--------------------
7. All 24 python processes are deleted. The System Monitor shows the absence of processes and the falling graph of the used RAM.
8.Message: --------------------Starting training DOGE/USDT:USDT --------------------
9. New python processes are starting to be added.
10. Added 12 python processes 347.2MB each
11. Added 12 python processes 328.1MB each
12. Message: --------------------done training DOGE/USDT:USDT--------------------
13. All "new" 24 python processes are deleted. The System Monitor shows the absence of processes and the falling graph of the used RAM.
14. Message: --------------------Starting training SUSHI/USDT:USDT --------------------
15. New python processes are starting to be added.
16. Added 12 python processes 347.2MB each
17. Added 12 python processes 328.1MB each
.
.
.
```

Cheers,

Dmytro
