### ISSUE TITLE
custom stoploss function did not return valid stoploss

### ISSUE THREAD

**Issue by naujoks-stefan** [freqtrade/freqtrade#8218]
## Describe your environment

  * Operating system: mac osx
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hello everyone. I'm facing the problem that with a custom_stoploss under hyperopt I get the warning function did not return valid stoploss. I followed your advice and implemented it that way. at least i thought so. here is my implementation. Can you help me?

    def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:

        # hard stoploss profit
        HSL = self.pHSL.value
        PF_1 = self.pPF_1.value
        SL_1 = self.pSL_1.value
        PF_2 = self.pPF_2.value
        SL_2 = self.pSL_2.value

        # For profits between PF_1 and PF_2 the stoploss (sl_profit) used is linearly interpolated
        # between the values of SL_1 and SL_2. For all profits above PL_2 the sl_profit value
        # rises linearly with current profit, for profits below PF_1 the hard stoploss profit is used.

        if (current_profit > PF_2):
            sl_profit = SL_2 + (current_profit - PF_2)
        elif (current_profit > PF_1):
            sl_profit = SL_1 + ((current_profit - PF_1) * (SL_2 - SL_1) / (PF_2 - PF_1))
        else:
            sl_profit = HSL

        # Only for hyperopt invalid return
        if (sl_profit >= current_profit):
            #print('sl profi: '+str(sl_profit)+' current profit: '+str(current_profit))
            return -1
        
        return stoploss_from_open(sl_profit, current_profit)

**Comment by xmatthias** [comment]
best check what you insert to `stoploss_from_open` ...

in certain scenarios, it can (mathematically) yield a stoploss higher/lower than the current price - which would result in an invalid stoploss - so it's set to 0 (intentionally) - which is obviously an invalid stop.

**Comment by naujoks-stefan** [comment]
i tried to catch this with the if statement and return -1. Have I to return 0 instead -1?

**Comment by xmatthias** [comment]
well that's the point - `0` / `None` are what cause the above log message.

This is intentional - as returning 0 is usually not desired- and a sign of a problem.
