### ISSUE TITLE
Run multiple bots with different configurations and strategies

### ISSUE THREAD

**Issue by owlswaper** [freqtrade/freqtrade#8219]
I want to use five strategies in separate bots and view them all in one url in frequi .
How can I do this?

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Best start by reading the [running multiple bots documentation page](https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade).

You'll then need to configure [cors](https://www.freqtrade.io/en/stable/rest-api/#cors). 
You can either define one "UI" instance (that's the url you need to enter into all other bots) - or simply put all URL's into each config - so you can switch UI's around at will (state will be per URL you navigate to - so don't do this too often).
With that configuration, you can then add the additional bots to the configuration.
