### ISSUE TITLE
Problem adding bots to frequi

### ISSUE THREAD

**Issue by owlswaper** [freqtrade/freqtrade#8222]
When I want to add other bots to the main url, I get this error 

Login failed.
Please verify that the bot is running, the Bot API is enabled and the URL is reachable.
You can verify this by navigating to http://myip:5001/api/v1/ping to make sure the bot API is reachable 
 Please also check your bot's CORS configuration: [Freqtrade CORS documentation](https://www.freqtrade.io/en/latest/rest-api/#cors)

But when I send request to this api (http://myip:5001/api/v1/ping) it returns me pong

This problem only occurs when the api url port is different from the domain port and I want to add multiple bots to the same domain.

I have entered the url in CORS origins but the problem is not resolved

![Screenshot from 2023-02-25 09-23-25](https://user-images.githubusercontent.com/117394732/221341174-07cff297-11b8-4ac4-a2f2-c3e259fcbb3e.png)

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

the trailing `/` is clearly wrong - so the 2nd entry is irrelevant.

What's the URL you navigate (the one shown in your browser navbar) to when logging in?
The best appoach for this will be to share a screenshot of the login page (once the error occurs) - including the address bar (so we can see the URL you navigate to).

**Comment by owlswaper** [comment]
> 
![Screenshot from 2023-02-25 11-33-45](https://user-images.githubusercontent.com/117394732/221346263-f7064194-0303-49e9-91e2-42fb34e0a04e.png)


![Screenshot from 2023-02-25 11-34-24](https://user-images.githubusercontent.com/117394732/221346275-fa7a1474-2b4e-452a-a00c-86f15fd71ef3.png)

**Comment by xmatthias** [comment]
best make sure that the cors settings are actually live (like - that you did stop / restart the bot after changing the CORS settings).

there's nothing obviously wrong (though i didn't check the IP for typos) ...

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered and we've had no further feedback.

Feel free to comment below / reopen if it's still unclear.
