### ISSUE TITLE
warning on all strategies: freqtrade.strategy

### ISSUE THREAD

**Issue by Daviko290** [freqtrade/freqtrade#8226]
now in all my strategies I get a warning "freqtrade.strategy" the error is: Import "freqtrade.strategy" could not be resolvedPylance, before it didn't show up but I updated freqtrade and now I get this warning

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

the most likely reason is that your interpreter in vscode is wrong.
you can select that via `select interpreter` from the vscode command pallete.

If the correct interpreter is selected, restart vscode.
