### ISSUE TITLE
Order {trade.open_order_id} for {trade.pair} not cancelled, as the filled amount of {filled_val} would result in an unexitable trade.

### ISSUE THREAD

**Issue by huytrvan** [freqtrade/freqtrade#8229]
## Describe your environment

  * Operating system: Ubuntu 22.04.1 LTS (in VPS)
  * Python Version: Python 3.10.6
  * CCXT version: ccxt==2.7.66
  * Freqtrade Version: freqtrade 2023.2.dev-8d156b277 (installed using setup.sh)

## Describe the problem:

- Freqtrade refuses to exit trade and warns user with error: 
```freqtrade.freqtradebot - WARNING - Order {trade.open_order_id} for {trade.pair} not cancelled, as the filled amount of {filled_val} would result in an unexitable trade.```
(I copied this error from `freqtradebot.py`, for sample message, view below).
- The error happens to all crypto pairs using the strategies I mentioned below.

### Steps to reproduce:

  1. Load any one of the strategies I am using:
  * [strategy-A](https://drive.google.com/file/d/1dOYqAHtjoKhNMTyyw-ahyxQ0Lya57CTz/view?usp=sharing)
  * [strategy-B](https://drive.google.com/file/d/1zLddrYH2ZpV5AI7j29YLzttAH0_c33cB/view?usp=sharing)
  2. Load the [config I am using](https://drive.google.com/file/d/13T-Mdk3jJmoMxE4cCqDAJj-Il9QukBC8/view?usp=sharing)
  
### Observed Results:

  What happened?
  - `Strategy-A` would enter trades but wouldn't exit any, while producing the error below.
  - `Strategy-B` works but as soon as you turn on trailing stoploss, same error appears.
  
What did you expect to happen?
  1. I expected there was problem with my config (as mentioned). However, using the same config in dry-run: `strategy-A` will produce error but `strategy-B` (with trailing stoploss turn off) will work as expected.
  2. So I suspected the problem to be `strategy-A` itself. However, when I turned on trailing stoploss for `strategy-B` (which normally works), the error happened again.

### Relevant code exceptions or logs
Sample of the logs I got:
  ```
2023-02-26 09:44:09,749 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=2, pair=YFDAI/USDT, amount=0.59450000, is_short=False, leverage=1.0, open_rate=102.08684272, open_since=2023-02-26 06:30:59)
2023-02-26 09:44:09,771 - freqtrade.freqtradebot - WARNING - Order dry_run_sell_1677404478.863213 for YFDAI/USDT not cancelled, as the filled amount of 0.5945 would result in an unexitable trade.
2023-02-26 09:44:09,927 - freqtrade.strategy.interface - WARNING - Outdated history for pair ASTRA/USDT. Last tick is 74 minutes old
  ```
## Additional Info:
- I have only tested these strategies in dry-run using [kucoin proxy](https://github.com/mikekonan/exchange-proxy)
- `Strategy-B` has DCA in it but works fine if you turn off trailing stoploss.
- Problem only happened in `strategy-A` (either with or without DCA), and `strategy-B` if trailing stoploss was turned on.
- I ran both strategies in parallel and with different settings and some worked, other didn't, so I highly doubt if the proxy or config was the culprit.

The problem seemed to be with `minstake` ([as seen in `freqtradebot.py`](https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/freqtradebot.py#L1443)).
I have tried to fix with different settings and looked at Freqtrade source code but no clue. Thanks if you have any input.

**Comment by xmatthias** [comment]
depending on the selected [pricing](https://www.freqtrade.io/en/stable/configuration/#prices-used-for-orders) - orders may fill, or may fill partially, or may not fill.
A quick fix is usually to use "pricing=other" - which will place the order at a spot that's more likely to be filled.
Especially on low volume markets - that's usually a good idea to prevent unfilled orders.


seems like you're experiencing partial fills - which, in combination of timeout settings, will produce this message.
it simply means "your order was filled for X% - would this order be canceled, then the remaining amount is too small to be placed as new order".

This is not a problem - but a protection. trying to circumvent this will result in "stuck" trades, which will fail with "order amount is too small".

**Comment by xmatthias** [comment]
Just noticed it's dry-run on kucoin - which (due to some "oddity" in the kucoin API) - has a fix forcing create-order to return "status=open".
Now on dry-run - that's not necessarily correct behavior - and (for market orders) will cause wrong behavior.

will be fixed in a few minutes on develop.

**Comment by huytrvan** [comment]
Thanks alot @xmatthias.
Yes, I was thought it was a bug because I tried your suggestion but didn't work. Glad you found the bug!
