### ISSUE TITLE
kraken futures

### ISSUE THREAD

**Issue by elestranobaron** [freqtrade/freqtrade#8230]
Hello , here some news about it: 

#7763

**Comment by xmatthias** [comment]
As mentioned in #7763, kraken futures is not available in my region/country - therefore there will be no work on this for now (unless the situation regarding this changes).

I'm happy to review a PR submitting support for kraken futures (given it's from a known contributor, where i know they'll stick around to support this going forward).

**Comment by elestranobaron** [comment]
I would be happy to do that but first i'd need to know how their api work. Maybe it's beyond my understanding at the moment
