### ISSUE TITLE
Freqtrade wallets backtesting

### ISSUE THREAD

**Issue by Arivadis** [freqtrade/freqtrade#8235]
Hello!

I just noticed this:
"Note

Wallets is not available during backtesting / hyperopt."

I compared backtests using 
1. Wallets with custom_stake_amount(some different not defoult amount using self.wallets.get_total_stake_amount() * %), 
2. Simple capital/max_trades
3. custom_stake_amount: return proposed_stake.
 
Second and third backtests match, but the first one has different result.
It does not seem like custom_stake_amount with self.wallets. returns not valid value or something like that, therefore this entails custom_stake_amount returns proposed_stake.
 
 How does it works in this case?
 
 Thank You!

**Comment by xmatthias** [comment]
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

I'm not sure i understand your point / question.

Backtesting/hyperopt does track your wallet for the duration of the backtesting simulation. Hyperopt won't be any different - as it's just using backtesting under the hood.
it'll not be available (it will not be correct) during `populate_*` methods - but in callbacks, wallets will be what they should be.

**Comment by Arivadis** [comment]
Thank You!

As I see, this is because of populate_* methods calculated once per backtest, but callbacks called every candle. And backtest shows wallets is avalible in callbacks during backtest.

I am asking because "Wallets is not available during backtesting / hyperopt." sounds like not available at all and even in callbacks(sounds like callback should make exception and use proposed_stake.)

Thanks for help!

**Comment by xmatthias** [comment]
yeah - documentation was from before we had callbacks - i've updated it now to be a bit clearer.
