### ISSUE TITLE
RPC tests fail on Windows with local TimeZone UTC+2

### ISSUE THREAD

**Issue by asuiu** [freqtrade/freqtrade#8244]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: Python 3.10.9 (`python -V`)
  * CCXT version: 2.8.17 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.3.dev-44b100507 
 

## Describe the problem:

Two tests related to RPC fail on Windows where local timezone is set to UTC +X, where X>=2

### Steps to reproduce:

  1. Run tests on Windows 11 with TimeZone UTC +X, where X>=2
  
### Observed Results:

  * Tests fail

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

`rpc.test_rpc.test_rpc_health` with next log:
```python
tests\rpc\test_rpc_apiserver.py:1796 (test_health)
botclient = (<freqtrade.freqtradebot.FreqtradeBot object at 0x000001E75CA2F9A0>, <starlette.testclient.TestClient object at 0x000001E75CC9ACB0>)

    def test_health(botclient):
        ftbot, client = botclient
    
>       rc = client_get(client, f"{BASE_URI}/health")

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = tzlocal(), dt = datetime.datetime(1970, 1, 1, 0, 0, tzinfo=tzlocal())

    def _naive_is_dst(self, dt):
        timestamp = _datetime_to_timestamp(dt)
>       return time.localtime(timestamp + time.timezone).tm_isdst
E       OSError: [Errno 22] Invalid argument

C:\Users\ASU\miniconda3\envs\freqtrade\lib\site-packages\dateutil\tz\tz.py:260: OSError
```

and `rpc.test_rpc.test_rpc_health` with log:
```python
tests\rpc\test_rpc.py:1249 (test_rpc_health)
mocker = <pytest_mock.plugin.MockerFixture object at 0x00000240AB91AFE0>
default_conf = {'amend_last_stake_amount': False, 'cancel_open_orders_on_exit': False, 'candle_type_def': <CandleType.SPOT: 'spot'>, 'datadir': WindowsPath('D:/Work/freqtrade/tests/testdata'), ...}

    def test_rpc_health(mocker, default_conf) -> None:
        mocker.patch('freqtrade.rpc.telegram.Telegram', MagicMock())
    
        freqtradebot = get_patched_freqtradebot(mocker, default_conf)
        rpc = RPC(freqtradebot)
>       result = rpc._health()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = tzlocal(), dt = datetime.datetime(1970, 1, 1, 0, 0, tzinfo=tzlocal())

    def _naive_is_dst(self, dt):
        timestamp = _datetime_to_timestamp(dt)
>       return time.localtime(timestamp + time.timezone).tm_isdst
E       OSError: [Errno 22] Invalid argument

C:\Users\ASU\miniconda3\envs\freqtrade\lib\site-packages\dateutil\tz\tz.py:260: OSError
```

**Comment by asuiu** [comment]
This issue referenced in https://github.com/freqtrade/freqtrade/pull/8231

**Comment by xmatthias** [comment]
I'm surprised it's happening with positive timezone offsets, too.
in my tests, it only happened with negative offsets.

the problem is (almost certainly) due to a limitation in windows to not properly handle dates < 1970. 
shifting the epoch 0 by the timezone results in a negative epoch - which linux/macos handles just fine, but windows fails to handle.- therefore causing this.

**Comment by asuiu** [comment]
Hi @xmatthias,
I have posted a fix to this, but I don't know the clients of the `/health` endpoint, so would appreciate if you can validate that's ok to change that contract:
https://github.com/freqtrade/freqtrade/pull/8245

Thank you for your time and help!

**Comment by asuiu** [comment]
On Windows - it actually looks to work according to the Python documentation. The Python [`time.localtime()`](https://docs.python.org/3/library/time.html#time.localtime) function doc says:
> It’s common for this to be restricted to years between 1970 and 2038.

so passing a negative value to this function would lead to year 1969, that's expected to raise an exception on some systems.
Implementation on Linux of the `localtime()` looks to be able to go further in the past with negative values and it can generate timestamps from 1969 and below, while Windows looks to stick to the strict meaning of Unix timestamp - "number of seconds that have passed since Epoch".

**Comment by LembaGang** [comment]
```markdown
Flagging a related live issue worth noting here.

US DST shifted March 8. UK/EU doesn't shift until March 29. For the next 13 days, any freqtrade setup using hardcoded UTC offsets for exchange schedule logic will be off by exactly 1 hour — the "phantom window" where US and EU clocks are desynchronised.

If your bot uses exchange open/close times for trade windows, cooldown periods, or any schedule-based logic, it's worth verifying the offset is being calculated dynamically rather than hardcoded.

Built a demo that reproduces the failure mode: **removed link** — runs in under 5 seconds and shows exactly where the offset breaks during DST transitions.

Not a freqtrade-specific bug, but given the previous UTC+2 timezone issues here it seemed worth flagging before March 29 when EU clocks change and the window resets.
```

**Comment by xmatthias** [comment]
@LembaGang please don't revive 3 year old  issues (unrelated to what you have to say, too). Open a new issue if you think it's something important so we can look at your problem more specifically.

I've also removed your link - as your whole comment looks pretty much like spam - and i'd not want unsuspecting users to run your unverified, potentially dangerous / malicious code.
