### ISSUE TITLE
Cooldown specific pair after a successful trade.

### ISSUE THREAD

**Issue by naif824** [freqtrade/freqtrade#8246]
YES.

## Describe your environment

  * Operating system: Ubuntu 22.10
  * Python Version: Python 3.10.7 (`python -V`)
  * CCXT version: ccxt==2.7.12 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.2.dev-1d6738778 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hello,
I have been looking for ways to stop trading certain pair after a successful trade, example, after getting 5% profit on LINK/USDT I want to wait for 30 min before getting into it again while long or short signal is still valid.

Problem is some times it runs after a pair even after harvesting the profit and get hanged into the peak, especially with spikes, I want to cool down after every successful trade.

Getting exit signals is good but I want this to be a layer of protection, I went through (https://github.com/freqtrade/freqtrade/issues/2968, https://github.com/freqtrade/freqtrade/issues/1841, and to some degree https://github.com/freqtrade/freqtrade/issues/1091) but all seems to stop trading for all pairs/bot, what i'm looking for is specific pair cool down in minutes.

Any thoughts/Ideas? Help is appreciated in advance.

**Comment by xmatthias** [comment]
use the protection protection [cooldownPeriod](https://www.freqtrade.io/en/latest/plugins/#cooldown-period)

It'll not make a distinction between different trade results - but it will lock just one pair - with the main intend of giving other pairs the chance to be entered upon.

**Comment by naif824** [comment]
Apologizes, a friend just told me that its doable through config:
https://www.freqtrade.io/en/stable/plugins/#cooldown-period
