### ISSUE TITLE
Custom Telegram notifications

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#8247]
## Describe your environment

  * Operating system: ___Docker_
  * Python Version: _Python 3.10.7____ 
  * CCXT version: __ccxt==2.7.12
  * Freqtrade Version: ___freqtrade docker-2023.2.dev-a7fec1f8
## Your question

My strategy timeframe is set to 5 min
timeframe = '5m'

I'm trying to send the entry signal to the Telegram channel whenever TRUE condition is met inside of an entry trend section. To accomplish this I'm using  this code:

```
populate_entry_trend
        if conditions:
            dataframe.loc[reduce(lambda x, y: x & y, conditions),['enter_long', 'enter_tag']] = (1, ' BTC LONG')
            entry_message = (f"{metadata['pair']} just got hot!")
            self.dp.send_msg(entry_message)
        return dataframe
```

Also, I've added this part of the code to the config :
```
        "allow_custom_messages": true,
        "notification_settings": {
            "status": "on",
            "warning": "on",
            "startup": "on",
            "entry": "on",
            "entry_fill": "on",
            "entry_cancel": "on",
            "exit": {
                "roi": "on",
                "emergency_exit": "on",
                "force_exit": "on",
                "exit_signal": "on",
                "trailing_stop_loss": "on",
                "stop_loss": "on",
                "stoploss_on_exchange": "on",
                "custom_exit": "on",
                "partial_exit": "on"
            },
            "exit_cancel": "on",
            "exit_fill": "on",
            "protection_trigger": "on",
            "protection_trigger_global": "on",
            "strategy_msg": "on"}
```

The (entry signal) messages (BTC/USDT:USDT just got hot!) are sent every 5 min. Is this expected? 
The intention is to send out only when the buy signal is formed. Regardless if the position is already filled or not.

**Comment by xmatthias** [comment]
assuming the above code is in one of the `populate_*` methods - then you'll blindly send out notifications.
that's kindof expected from the above code - whenever this method is called - a notification will be sent out.

You'll want to check the last candle (`df.iloc[-1]['enter_long'] ==1` ?? ) to detect if there's an actual signal.
now don't use this for anything else  to avoid backtesting problems - but just for sending this message, that'll be the way to go.

**Comment by darioneto** [comment]
Thanks for your suggestions, 
I've edited this as:

```
        if conditions:
            dataframe.loc[reduce(lambda x, y: x & y, conditions),['enter_long', 'enter_tag']] = (1, ' BTC LONG')
            if dataframe.iloc[-1]['enter_long'] == 1:
                entry_message = (f"{metadata['pair']} just got hot!")
                self.dp.send_msg(entry_message)
```

No signal generated yet so waiting to see if this is going to work :-)
