### ISSUE TITLE
Discrepancy of backtest results with live trades

### ISSUE THREAD

**Issue by kiarash-shams** [freqtrade/freqtrade#8248]
## Describe the problem:

I just started working with Freqtrade and based on my strategy, I received this backtest result from Freqtrade.

Also, I used Hyperopt and set minimal_roi, stoploss, and trailing_stop based on Hyperopt, but my profit and loss ratio is completely different compared to backtest.

## Observed Results

========================= SUMMARY METRICS =========================
Backtesting from            | 2023-02-01 03:30:00
Backtesting to              | 2023-02-19 15:00:00
Max open trades             | 10                 

Total/Daily Avg Trades      | 344 / 19.11        
Starting balance            | 1000 USDT          
Final balance               | 20755.297 USDT     
Absolute profit             | 19755.297 USDT     
Total profit %              | 1975.53%           
CAGR %                      | 51103231917663024407348510720.00% 
Sortino                     | 179.03                            
Sharpe                      | 183.34                            
Calmar                      | 74099.14                          
Profit factor               | 5.22                              
Expectancy                  | 0.56                              
Trades per day              | 19.11                             
Avg. daily profit %         | 109.75%                           
Avg. stake amount           | 604.804 USDT                      
Total trade volume          | 208052.747 USDT                   

Long / Short                | 138 / 206                         
Total profit Long %         | 570.53%                           
Total profit Short %        | 1405.00%                          
Absolute profit Long        | 5705.339 USDT                     
Absolute profit Short       | 14049.958 USDT                    

Best Pair                   | ALGO/USDT:USDT 245.54%            
Worst Pair                  | SAND/USDT:USDT 56.44%             
Best trade                  | BTC/USDT:USDT 34.17%              
Worst trade                 | SXP/USDT:USDT -30.05%             
Best day                    | 3528.954 USDT                     
Worst day                   | -83.314 USDT                      
Days win/draw/lose          | 15 / 2 / 2                        
Avg. Duration Winners       | 0:39:00                           
Avg. Duration Loser         | 0:35:00                           
Rejected Entry signals      | 126                               
Entry/Exit Timeouts         | 0 / 136                           

Min balance                 | 1008.502 USDT                     
Max balance                 | 20945.778 USDT                    
Max % of account underwater | 11.83%                            
Absolute Drawdown (Account) | 2.83%                             
Absolute Drawdown           | 561.423 USDT                      
Drawdown high               | 18840.177 USDT                    
Drawdown low                | 18278.754 USDT                    
Drawdown Start              | 2023-02-19 13:15:00               
Drawdown End                | 2023-02-19 13:15:00               
Market change               | 15.66%                            

## Your question

![Untitled](https://user-images.githubusercontent.com/71229590/221573913-6dad0f4e-3eac-4a22-af4c-43f6f6409265.jpg)
![Untitled1](https://user-images.githubusercontent.com/71229590/221574159-b1be57b7-de2e-42b9-8d4c-ba415adfa78d.jpg)

In simulator mode, this result changes completely and I can't understand where the problem comes from! Has anyone encountered this problem and how can I fix this discrepancy?

**Comment by xmatthias** [comment]
best ensure you're familiar with the [backtesting assumptions](https://www.freqtrade.io/en/latest/backtesting/#assumptions-made-by-backtesting), especially with the following sentence: 

> However, backtesting will never replace running a strategy in dry-run mode. Also, keep in mind that past results don't guarantee future success.

---

we also have the [common strategy mistakes](https://www.freqtrade.io/en/latest/strategy-customization/#common-mistakes-when-developing-strategies) section - which should also contain some pointers.

To be any more specific, you're providing WAY too little information.
