### ISSUE TITLE
need help saving highs and lows in dataframe

### ISSUE THREAD

**Issue by mathlabelle** [freqtrade/freqtrade#8250]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
i am using the folowing command so save highs to the dataframe :  dataframe['upper'] = dataframe['high']shift(1).rolling(30).max().

so technicaly the highest high of the 30 last bar is dataframe['upper']. now my question is how do i delete duplicate if i want dataframe['upper'].shift(1) to be the previous high and not the last bar' high which would be the same as the current highest high.

i have try ; df.drop_duplicates(subset=['upper']) but still doesnt work.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
i'd suggest to use frequi's charting functionality to look at the data you're working with - otherwise it can often be confusing what the output of a command actually looks like.

your code will yield the maximum over 30 candles - so i'm not sure why you'd want to drop duplicates - it's a straight, horizontal line (until the next high appears) - or the prior high "ages out".

**Comment by mathlabelle** [comment]
i am trying to access the previous max to compare with the recent one ( to target double tops) kinda  guard= dataframe['upper'] >=dataframe['upper'].shift(1) and trigger = hammer pattern.


 i am also trying to figure out in pandas doccumentation how to access the close data of when the candle printed the new high . so i could add in my guard that this close data must be bellow the high.

## found answer in issue7782 ### also is it possible in custom stoploss to get the trade open candle ? i tried with the dataframe.query function but couldn't match the trade.open.rate to a close value to get the same row value for high and low

**Comment by mathlabelle** [comment]
i do get this:
Traceback (most recent call last):
  File "/home/math/mathieu/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
    return f(*args, **kwargs)
  File "/home/math/mathieu/freqtrade/user_data/strategies/support.py", line 280, in custom_exit
    if (last_candle['close'] < (price - (shortr* self.risks.value ))):
ile "/home/math/mathieu/freqtrade/.env/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 3931, in __bool__
    raise TypeError("Boolean value of this clause is not defined")

with the folowing custom exit though:
```
   def custom_exit(self, pair, trade, current_time, current_rate, current_profit):

        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)

        trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
        # Look up trade candle.
        trade_candle = dataframe.loc[dataframe['date'] == trade_date]
        last_candle = dataframe.iloc[-1].squeeze()

        # trade_candle may be empty for trades that just opened as it is still incomplete.
        price= Trade.open_rate
        shortr= trade_candle['uppernow'] - price
        longr= trade_candle['lowernow'] + price


        if  trade.is_short == False:
            if (last_candle['close'] > (price + (longr* self.riskl.value ))):
                return 'takeprofitlong'
        if  trade.is_short == True:
            if (last_candle['close'] < (price - (shortr* self.risks.value ))):
                return 'takeprofitshort'
  def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)

        trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
        # Look up trade candle.
        trade_candle = dataframe.loc[dataframe['date'] == trade_date]
        # trade_candle may be empty for trades that just opened as it is still incomplete.
        price=trade.open_rate

        if not trade_candle.empty:
            trade_candle = trade_candle.squeeze()
            if  trade.is_short==False:
                return stoploss_from_absolute(trade_candle['lowernow'] , current_rate, is_short=False)
            if  trade.is_short==True:
                return stoploss_from_absolute(trade_candle['uppernow'] , current_rate, is_short=True)
        return 100
```

**Comment by xmatthias** [comment]
`shortr` and `longr` are series, not scalars / single values, since you're assigning it from the non-squeezed variable.

you need to be VERY careful with what each variables is / what type it is.


You should also be careful as we can't guarantee that the open candle is still available (if the trade is open over a longer period of time) - so you should have a fallback for `if len(trade_candle) == 0`.


> i am also trying to figure out in pandas doccumentation how to access the close data of when the candle printed the new high . so i could add in my guard that this close data must be bellow the high.

your best bet will be something around `dataframe['highchanged'] = dataframe['upper'] >=dataframe['upper'].shift(1)` (or compare for <>) ... (which will be a boolean column - showing you when the actual high changed).
that'll give you a way to filter for the relevant close values, which you can then compare to whatever.

**Comment by mathlabelle** [comment]
Thanks.
Now one last question if you don’t mind.
As i dropped duplicate, it doesn’t work live as it deleted rows of the dataframe which is not good. Is there a way to create a completely separate diferently name dataframe and import it in populate entry trend?
i have been reading the pandas documentation but could’nt find info about running 2 dataframe parallel.
Ex:
Regular dataframe (dataframe [‘close’] etc..)
Separate dataframe nammed xx where i can save last 30 bars min(low) and max(high) or spicy maxima and minima then drop dupplicate so i can call like (xx[‘recentlows’] > xx[‘recentlows’].shift(1)) the .shift(1) been the last different from present lower valus as i dropped the duplicate.
Mainly to code uptrend and downtrend without using the technical.trendline( which you mention in previous issues that is lookahead bias)

i would like to then use the bouce funtion from technical to use with that xxdataframe. 


If you think of any documentation that might help me let me know. I was also looking at documentation for worse case if the dual dataframe isn’t possible to log those different lows in a csv file and then call the most recent entry and previous entry in populate entry trend 
Thanks again 
Cheers

**Comment by xmatthias** [comment]
within one function, you can always create different variables. They'll obviously not transition between functions - but nothing prevents you from merging that (shortened) dataframe back to the original - to have the values in the correct place (that way they're also available for plotting, ...).

there's most likely better ways than dropping rows - but freqtrade is not in itself prefenting this (as long as you return a non-dropped dataframe - which effectively means merging the other dataframe back.

**Comment by shuten** [comment]
I want to save the data shown in the figure,like this:
![screenshot-20230717-112930](https://github.com/freqtrade/freqtrade/assets/7748335/dcb4d591-2b89-4556-a06f-fba03ba042e6)
how can i do it,thank you very mach!!!
