### ISSUE TITLE
conda cann't create ENV

### ISSUE THREAD

**Issue by andona** [freqtrade/freqtrade#8260]
## Describe your environment

  * Operating system:  ubuntu18.04
  * Python Version: _3.9 (`python -V`)
  * CCXT version: _grep ccxt (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
input:
conda env create -n freqtrade-conda -f environment.yml
result
Collecting package metadata (repodata.json): done
Solving environment: \ Killed

**Comment by xmatthias** [comment]
on ubuntu, there's little to no reason to use conda.

It's usually slow as hell, and not very reliable. I'd recommend an installation through the `setup.sh` script - which will create a virtual environment, or the use of docker containers.

The error itself seems to be a simple "killed" command - which can happen if the system runs out of memory (i guess while conda is resolving the environment ...), or if someone in another shell issued a "kill" comand.

you should also consider using a system that's supported - we no longer run tests for ubuntu 18.04 - and it's regular support runs out in April 2023.
best use 20.04 or 22.04.

**Comment by andona** [comment]
ok,I get it ,thks very much
