### ISSUE TITLE
Enable Copy Trading Order Creation

### ISSUE THREAD

**Issue by yclai** [freqtrade/freqtrade#8262]
## Describe your environment
(if applicable)

  * Operating system: Linux
  * Python Version: 3.8 (`python -V`)
  * CCXT version: 2.0.96 (`pip freeze | grep ccxt`)
  * Freqtrade Version: stable version (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

Hi dear developers,

I am a self-learning algo trader and would like to ask if there is any possibility to let the bot execute a copytrading order as a master trader on Bybit instead of my own private futures order? Is there anywhere I can change the "/contract/v3/private/order/create" to "/contract/v3/private/copytrading/order/create" when the bot is executing a trade? And also when exiting the trade (to make the bot completely functionable trading my copy trading master account). Appreciate if anyone could help me! Thank you. 

For reference: 
https://bybit-exchange.github.io/docs/category/copy-trade

**Comment by xmatthias** [comment]
The quick answer to that is no.

It may be possible with some experimentation (assumes some programming / debugging experience)  - but it would be messing with ccxt internals - which will probably break soon (bybit's api was updated to v5 - so ccxt internals in that regard may slightly change).
Maybe ccxt has a flag you can set to change the endpoint (most likely not just for create-order, but for others, too)- but so far i don't see that in their bybit file - so i assume it's not supported - therefore neither will we.

On top of that - it's also unclear (without doing further analysis / tests) if the endpoint returns the same structure, or a slightly different one (which would make ccxt parsing fail) - and if the orders created through this endpoint would show up in the regular `fetch_order` requests or not (if they don't, then freqtrade would never be able to find the order again if it doesn't fill immediately - basically limiting you to market orders only).


For now - I'd see this as not possible (and also not supportable going forward). Best raise an issue against [ccxt](https://github.com/ccxt/ccxt/issues/) to see if this is easily possible or can be integrated.
Feel free to let me know below if they have (or once they have integrated) such a configuration) - so we can look at this again.
