### ISSUE TITLE
Error with installation 

### ISSUE THREAD

**Issue by ParaPuffer** [freqtrade/freqtrade#828]
I've looked at some similar issues but none of the solutions worked for me.

I've cut some off the top, but I can post it if needed: 

Installing collected packages: idna, multidict, yarl, attrs, async-timeout, char
det, idna-ssl, aiohttp, cchardet, urllib3, certifi, requests, pycares, aiodns, c
cxt, SQLAlchemy, future, python-telegram-bot, six, python-dateutil, arrow, cache
tools, wrapt, numpy, pytz, pandas, scikit-learn, scipy, jsonschema, TA-Lib, py,
more-itertools, colorama, pluggy, atomicwrites, pytest, pytest-mock, coverage, p
ytest-cov, nose, pymongo, decorator, networkx, hyperopt, tabulate, requests-cach
e, coinmarketcap
  Running setup.py install for idna-ssl ... done
  Running setup.py install for SQLAlchemy ... done
  Running setup.py install for future ... done
  Running setup.py install for arrow ... done
  Running setup.py install for wrapt ... done
  Running setup.py install for TA-Lib ... error
    Complete output from command "c:\program files\python36\python.exe" -u -c "i
mport setuptools, tokenize;__file__='C:\\Users\\Ahmad\\AppData\\Local\\Temp\\pip
-build-s59w7qm6\\TA-Lib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);c
ode=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'
))" install --record C:\Users\Ahmad\AppData\Local\Temp\pip-hqb244h8-record\insta
ll-record.txt --single-version-externally-managed --compile:
    C:\Users\Ahmad\AppData\Local\Temp\pip-build-s59w7qm6\TA-Lib\setup.py:79: Use
rWarning: Cannot find ta-lib library, installation may fail.
      warnings.warn('Cannot find ta-lib library, installation may fail.')
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\talib
    copying talib\abstract.py -> build\lib.win-amd64-3.6\talib
    copying talib\deprecated.py -> build\lib.win-amd64-3.6\talib
    copying talib\stream.py -> build\lib.win-amd64-3.6\talib
    copying talib\test_abstract.py -> build\lib.win-amd64-3.6\talib
    copying talib\test_data.py -> build\lib.win-amd64-3.6\talib
    copying talib\test_func.py -> build\lib.win-amd64-3.6\talib
    copying talib\test_pandas.py -> build\lib.win-amd64-3.6\talib
    copying talib\test_stream.py -> build\lib.win-amd64-3.6\talib
    copying talib\__init__.py -> build\lib.win-amd64-3.6\talib
    running build_ext
    building 'talib._ta_lib' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual
C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command ""c:\program files\python36\python.exe" -u -c "import setuptools, tokeni
ze;__file__='C:\\Users\\Ahmad\\AppData\\Local\\Temp\\pip-build-s59w7qm6\\TA-Lib\
\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r
\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\
Users\Ahmad\AppData\Local\Temp\pip-hqb244h8-record\install-record.txt --single-v
ersion-externally-managed --compile" failed with error code 1 in C:\Users\Ahmad\
AppData\Local\Temp\pip-build-s59w7qm6\TA-Lib\

**Comment by xmatthias** [comment]
on Windows, you need to have ta-lib installed before running the bot installer.

[Documentation](https://mrjbq7.github.io/ta-lib/install.html)
make sure to unzip it to `c:/ta-lib/` or it will have trouble finding it.

**Comment by ParaPuffer** [comment]
Issue was that I was running python 64 bit and TA-Lib does automatically generate 64 libraries. If you have 32 bit its fine but if not you can find (or build) your own 64 bit libraries. 

Solved

**Comment by xmatthias** [comment]
hope you don't mind me following up - i think this is a common issue (i've seen tons of issues with Windows already) and we should improve the documentation for Windows.

to clarify - fix is to use python 32bit on windows, or build ta-lib for 64bit yourself?

**Comment by ParaPuffer** [comment]
So that solution I tried didnt end up working. I tried building my own and downloading a prebuilt library but neither one resolved the issue. 

I ended up just going back to python 32bit on windows and that resolved that issue. Everything works up until I enter the "python main.py" command. It returns a FileNotFoundError: [Errno 2] No such file or directory: "config.json". Am I doing something wrong? The steps were: unzip freqtrade-develop -> copy config.json to freqtrade -> then opening up cmd and entering the commands specified in windows installation.

**Comment by ParaPuffer** [comment]
(.env) C:\Users\Ahmad\Documents\tradebot\freqtrade-develop\freqtrade>python main
.py
Config file "config.json" not found. Please create your config file
Fatal exception!
Traceback (most recent call last):
  File "c:\users\ahmad\documents\tradebot\freqtrade-develop\freqtrade\configurat
ion.py", line 61, in _load_config_file
    with open(path) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 38, in main
    config = Configuration(args).get_config()
  File "c:\users\ahmad\documents\tradebot\freqtrade-develop\freqtrade\configurat
ion.py", line 209, in get_config
    self.config = self.load_config()
  File "c:\users\ahmad\documents\tradebot\freqtrade-develop\freqtrade\configurat
ion.py", line 34, in load_config
    config = self._load_config_file(self.args.config)
  File "c:\users\ahmad\documents\tradebot\freqtrade-develop\freqtrade\configurat
ion.py", line 68, in _load_config_file
    exit(0)
  File "C:\Program Files (x86)\Python36-32\lib\_sitebuiltins.py", line 26, in __
call__
    raise SystemExit(code)
SystemExit: 0

**Comment by glonlas** [comment]
You must go one level above and run python freqtrade/main.py

**Comment by ParaPuffer** [comment]
I've been using admin cmd. Is there something else I should be doing here? Same error

**Comment by xmatthias** [comment]
could you check the docs again  please - i've updated the windows documentation a bit - hope this will help fix your issue
[Windows documentation](https://github.com/freqtrade/freqtrade/blob/develop/docs/installation.md#windows)

**Comment by gcarq** [comment]
I'm closing this. Feel free to reopen
