### ISSUE TITLE
How do I produce entry/exit at same time ? 

### ISSUE THREAD

**Issue by eromoe** [freqtrade/freqtrade#8288]
I haven't found a way to produce entry/exit at same time . 
Since I have a model , `model.predict` simply produces entry and exit signals immediately.
But according to docs, I have to write `populate_entry_trend` and `populate_exit_trend` , such as below code

```python
class DemoStrategy(IStrategy):
    ....

    def bot_start(self, **kwargs) -> None:
        self.model = dload_obj('my_large_lgb.pkl')

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the entry signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with entry columns populated
        """
        
        entries = self.model.predict(dataframe)
        dataframe['enter_long'] = entries

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the exit signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with exit columns populated
        """
        
        entries = self.model.predict(dataframe)
        dataframe['enter_long'] = ~entries

        return dataframe

```

Is there any way to avoid this overhead, just call my model once?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

From a freqtrade perspective, we only require that the method is implemented and returns the dataframe.
The dataframe must contain at least the enter_long column.

you can also implement empty populate_*_ methods, and do everything in `populate_indicators()` - or assign both enter and exit signals in `populate_entry_trend()`. 
Where you implement this will depend a bit on your requirements - assuming you'll not hyperopt, it's really irrelevant - as long as the above conditions are satisfied.

**Comment by eromoe** [comment]
OK, I got it, thank you!
