### ISSUE TITLE
Show the value of future on telegram and freqUI

### ISSUE THREAD

**Issue by pnpn1212** [freqtrade/freqtrade#8292]
We need to change the display value after using ft with x2 or x20 leverage but the stake value is still the amount we originally set it to. Just need to fix on how it's displayed.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Apart from that - it's also unclear what you're actually asking.

the Stake value that's shown corresponds to the own capital invested.
so a trade with 100$ own capital at 2x (200$ worth of tokens) - or at 20x (2_000$ worth of tokens) will still show 100$ as stake (that's the capital that's taken (or reserved) from your wallet).

As such (unless you mean something different) i think that freqtrade is displaying the correct information.
