### ISSUE TITLE
How to Act based on current price not closed candle? 

### ISSUE THREAD

**Issue by naif824** [freqtrade/freqtrade#8293]
## Describe your environment

    Operating system: Ubuntu 22.10
    Python Version: Python 3.10.7 (python -V)
    CCXT version: ccxt==2.7.12 (pip freeze | grep ccxt)
    Freqtrade Version: freqtrade 2023.2.dev-1d6738778 (freqtrade -V or docker compose run --rm freqtrade -V for Freqtrade running in docker)

  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hello,
I have been looking everywhere to find answer before posting my question here, I have a very good strategy that runs 5m timeframe, entry condition sample is:
`(qtpylib.crossed_above(dataframe["close"], dataframe["trend"]))&`

Problem is, sometimes is enters late, after the close, is there a way to take action based on the current candle price and activate condition within the candle when the cross happens? looking to replace "close" with current or price.

**Comment by xmatthias** [comment]
Freqtrade will provide you with the candles once they are closed (no incomplete candles).

what you're asking for is repainting. 

It's a very dangerous premise, as it can lead to false/disappearing signals (signals that are there for a second, but gone at the candle close). You'll never know why the bot actually entered, as no chart will show you that there was an actual cross.
It'll seem like it's "late" - but anything that would be based on repainting cannot be backtested (by definition) as the signal may no longer be there at candle close.

You can obviously do some logic with [current prices](https://www.freqtrade.io/en/latest/strategy-customization/#orderbookpair-maximum) - but that's automatically no longer available to backtest - and will also impact performance quite heavily (depending on the pair, obviously).
