### ISSUE TITLE
Trading Futures on Bitget

### ISSUE THREAD

**Issue by yclai** [freqtrade/freqtrade#8294]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.8 (`python -V`)
  * CCXT version: 2.8.98  (`pip freeze | grep ccxt`)
  * Freqtrade Version: stable (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Is there any possibility the bot will work if I were to start it to trade futures on Bitget?

**Comment by xmatthias** [comment]
there's a good chance bitget will work for trading spot.


futures will not work out of the box.
There's additional work to be done - as every futures exchange seems to be using slightly different liquidation formulas, as well as different logics for other things and sometimes completely different endpoints.

Some parts are mostly about collecting info and configuring things - other things may involve implementing non-unified endpoints (not unified by ccxt) to have some random info available that the liquidation formula needs.

All in all, it's quite some work and testing.
Bitget is not a supported exchange for spot - and we currently have no plans on adding support for additional futures exchanges (for time/capacity reasons).

I'm happy to review a PR that's adding support for additional exchanges (don't expect the review to be quick, as it involves a lot of testing) - but i'd not recommend to start contributing through that - as it requires quite some understanding of both freqtrade, as well as how futures trading (on that particular exchange) works.

**Comment by xmatthias** [comment]
We're happy to let you know that freqtrade will support bitget futures as of version 2025.10.

you can also check it out before this version is released by using the develop version.
