### ISSUE TITLE
How can I do so that when I exit a trade I don't re-enter until the next signal?

### ISSUE THREAD

**Issue by Daviko290** [freqtrade/freqtrade#8299]
I have a supertrend strategy which enters long and short according to the supertrend signal. The problem is that, for example, if it is long and closes a trade for 5% ROI in the next candle, it enters long again and I would like it to do so in the next signal short this is the code of populate_entry_trend and populate_exit_trend thanks :

```
def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe.loc[
            (
                (dataframe['ST_long'] < dataframe['close'] ) & 
                (dataframe['volume'] > 0)
            ),
            'enter_long'] = 1
                

        dataframe.loc[
            (
                (dataframe['ST_short'] > dataframe['close']) 
            ), 
            'enter_short'] = 1 

        print(dataframe)    

        return dataframe 

def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame: 

        dataframe.loc[
            (
                (dataframe['ST_short'] > dataframe['close'] ) &
                (dataframe['volume'] > 0)
            ),
            'exit_long'] = 1         

        dataframe.loc[
            (
                (dataframe['ST_long'] < dataframe['close'] ) &
                (dataframe['volume'] > 0)
            ),
            'exit_short'] = 1

        return dataframe 
        ```

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Your best bet is probably the [trade_entry_confirmation](https://www.freqtrade.io/en/stable/strategy-callbacks/#trade-entry-buy-order-confirmation) callback - where you can reject trades that don't fit your current direction.

combine that with [querying for trades](https://www.freqtrade.io/en/latest/strategy-customization/#additional-data-trades) you should get to what you want/need with just a few lines of code.
