### ISSUE TITLE
Installation in Google Colab

### ISSUE THREAD

**Issue by deciphercypher** [freqtrade/freqtrade#8304]
What is the recommended installation method and the recommended way of running the current version of freqtrade in google colab?

**Comment by xmatthias** [comment]
We have [extensive](https://www.freqtrade.io/en/stable/installation/) [documentation](https://www.freqtrade.io/en/stable/docker_quickstart/) on how to install freqtrade.
Each method documented there should be considered supported.


Colab is not a supported platformat this point  (and probably never will be) - but feel free to share your method should you have success with it.
As colab would be stopping your bot within 6 (or 12)h - it's anyway not really a suitable platform for running a bot anyway.
For trade mode - the base assumption is that the bot is constantly running.

**Comment by deciphercypher** [comment]
Thank you for your quick reply!

**Comment by tc3oliver** [comment]
I was able to successfully install freqtrade using the following method:

```python
!wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
!tar -xzvf ta-lib-0.4.0-src.tar.gz
%cd ta-lib/
!./configure --prefix=/usr
!make
!sudo make install
!pip install TA-Lib
!pip install freqtrade
```

Although it is possible to install it on Colab, as @xmatthias mentioned, running a bot on Colab is impractical. Colab stops the execution after 6 (or 12) hours, making it unsuitable for running a bot continuously. Personally, I installed it on Colab to test and use the same technical indicators.

You can refer to my testing results in this notebook: https://github.com/tc3oliver/StratLabFreq/blob/main/freqtrade.ipynb.

**Comment by ekoshv** [comment]
But if it can be installed then the optimization would be so much easier.
