### ISSUE TITLE
Use FreqAI prediction as input to RL

### ISSUE THREAD

**Issue by Silur** [freqtrade/freqtrade#8305]
I'd be nice to combine XGBoostRegressors/Classifiers and Reinforcement learning in a way to supply the prediction of any user-supplied target from `set_freqai_targets` as another state variable for RL learners.

Basically `feature_engineering_expand_all` whould have to somehow get the inferred prediction of another freqai instance target.

Currently this can be hacked together by training a regressor freqai model, saving it using pickle and calling the model by hand inside `feature_engineering_expand_all` but it's super unefficient

**Comment by robcaulk** [comment]
Hello, can you please explain why our producer/consumer functionality is insufficient for you? 

https://www.freqtrade.io/en/stable/producer-consumer/

Thank you,

Robert

**Comment by robcaulk** [comment]
Closing this issue, feel free to reopen it if you have questions or comments.

**Comment by demoh2019** [comment]
> Здравствуйте, не могли бы вы объяснить, почему наша функциональность производителя/потребителя недостаточна для вас?
> 
> https://www.freqtrade.io/en/stable/producer-consumer/
> 
> Спасибо,
> 
> Роберт

But then it won't be possible to conduct backtesting.
