### ISSUE TITLE
Is 'max trades in life time' possible?

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8310]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.2 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Can Freqtrade limit the total amount of trades, which will ever be opened, not with stop enter, but unattended? In one case, I don't want to open a trade, even when after max_open_trades is reached, one or more trades are closed.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by stash86** [comment]
By default, no. But it's possible. Supposed to be quite easy to add that to your strat

**Comment by xmatthias** [comment]
I don't really see this as a good usecase (therfore it's quite unlikely we'll be adding such functionality in the future).
Either you think your strategy is good - or it's not.

Having a strategy that'll "only work for the next 10 trades" is kindof pointless.
It may fail after trend turns - but there's NO way to say that trend will change after 10, 20 or 50 trades.


While we don't provide anything builtin - you can pretty easily accomplish something around this with the [confirm-entry](https://www.freqtrade.io/en/stable/strategy-callbacks/#trade-entry-buy-order-confirmation) callback.

**Comment by myNextCoder** [comment]
Many thanks :)
