### ISSUE TITLE
Pairs lock

### ISSUE THREAD

**Issue by Arivadis** [freqtrade/freqtrade#8312]
Hello,

I am using Ubuntu 22.04.2 LTS Freqtrade last version.

I try to lock every pair using some condition(not separatly, but for every pair in current whitelist) using this:

        if self.config['runmode'].value in ('live', 'dry_run'):
            pairs = self.dp.current_whitelist()
            for pair in pairs:
                self.lock_pair(pair, until=datetime.now(timezone.utc) + timedelta(minutes=self.cust_time_block))

in def bot_loop_start or populate_* method.

But getting this error(file attached).
[lock_pairs.txt](https://github.com/freqtrade/freqtrade/files/10951681/lock_pairs.txt)

I also tried to use example from documentation - the same error appears.

if self.config['runmode'].value in ('live', 'dry_run'):
   # fetch closed trades for the last 2 days
    trades = Trade.get_trades([Trade.pair == metadata['pair'],
                               Trade.open_date > datetime.utcnow() - timedelta(days=2),
                               Trade.is_open.is_(False),
                ]).all()
    # Analyze the conditions you'd like to lock the pair .... will probably be different for every strategy
    sumprofit = sum(trade.close_profit for trade in trades)
    if sumprofit < 0:
        # Lock pair for 12 hours
        self.lock_pair(metadata['pair'], until=datetime.now(timezone.utc) + timedelta(hours=12))

Could You please check what it could be?

Thank You!

**Comment by xmatthias** [comment]
from afar, it'd seem like reason is mandatory (it's not in the database) - or at least not designed to be not provided in some areas.
i know all internal usages do provide a proper reason - and i suspect nobody ever tried to use it without that - as it really makes sense to provide (potentially different) reasons to identify why something happened later.

now the error is from the api server, so i suspect the lock will work just fine - just won't show in the UI correctly.
