### ISSUE TITLE
Failed Installing dependencies

### ISSUE THREAD

**Issue by Elezyrus** [freqtrade/freqtrade#8330]
Collecting xgboost==1.7.4
```
./setup.sh: line 43: 72883 Killed                  ${PYTHON} -m pip install --upgrade -r ${REQUIREMENTS} ${REQUIREMENTS_HYPEROPT} ${REQUIREMENTS_PLOT} ${REQUIREMENTS_FREQAI} ${REQUIREMENTS_FREQAI_RL}
Failed installing dependencies
```

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

The error message suggests that the installation process was killed.

This is common on low-powered systems, where the installation takes too much memory.
if you encounter this error on installation - then it's clearly not well suited to run freqAI.
