### ISSUE TITLE
exit_long / exit_short is not selling or buying

### ISSUE THREAD

**Issue by decado87** [freqtrade/freqtrade#8339]
Hi all,

i'm sorry if i'm asking dummy question, but i'm new here and cannot find answer to this.

I have strategy where I open long and short positions. In my case, exit_short is called, but trade is not closed and I don't know why. I was trying to find answer on google but didn't find anything. How can I close position immediately when condition is fulfilled. Am I doing it wrong? I'm attaching screen from my code and plot, where you can see exit_short shown but trade is not closed. (fifth candle from left is trade entry)

Thanks in advance for your answer

![Screenshot 2023-03-17 at 15 34 48](https://user-images.githubusercontent.com/24208798/225936734-95369699-d8cb-47e7-8f41-4eea508ed1e7.png)
![Screenshot 2023-03-17 at 15 38 10](https://user-images.githubusercontent.com/24208798/225936742-9b15c5ed-2205-48d9-9a05-a3d8b14dbc2e.png)

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

well with only the above plot - the only thing we can do is guess.

one thing is the value of `exit_profit_only` - which would prevent a sell in this case (it's a short - which went up, so it's negative).
you're also using plotting - which takes results from a prior backtest - but with the current strategy.

We don't know if the strategy changed between calls - or if the strategy is somehow instable, generating semi-random signals (now that's a long / unrealistic shot - but not impossible / not something we didn't see before).

**Comment by decado87** [comment]
Thank you for your response. 
Okay, I will remain headers in future, thought that is needed with installation problems or something like that. 

I have used backtest and then plot without any changes in code. It is confusing that in plot it is shown as `short_exit` but short is not closed. Now I'm looking at strategy and I have explicit `exit_profit_only = False`. I will try to find more informations. Thanks

**Comment by xmatthias** [comment]
> Now I'm looking at strategy and I have explicit exit_profit_only = False.

The strategy content may not be what's used (config values would overwrite this). 
The best source for "what's actually used" is almost always the backtest logs - which contain what's the effectively used settings.
now depending on the strategy, there can also be callbacks preventing exits (`confirm_trade_exit()` in particular) - but i'd assume that if you use that callback, you'll also be aware of it ...

**Comment by decado87** [comment]
Okay, thanks. I will try to print data during backtest to debug where is a problem.

**Comment by xmatthias** [comment]
well it's more about the logs - which are always outputted :)

**Comment by xmatthias** [comment]
One sidenote - make sure you don't have [colliding signals](https://www.freqtrade.io/en/stable/strategy-customization/#colliding-signals).
the screenshot above looks like it has a hidden "enter_short" behind the "exit_long" - which makes this an invalid signal, which freqtrade would ignore.

**Comment by decado87** [comment]
@xmatthias thank you very much for your assistance! It really helped me.

Yes, there was a problem - colliding signals. If someone else will need, I just added these 2 lines:
 
```
def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['long_exit'] == False) &
                (dataframe['long_signal'])
            ),
            'enter_long'] = 1
        dataframe.loc[
            (
                (dataframe['short_exit'] == False) &
                (dataframe['short_signal'])
            ),
            'enter_short'] = 1

        return dataframe
```
