### ISSUE TITLE
Import "freqtrade.strategy" could not be resolvedPylancereportMissingImports (vscode)

### ISSUE THREAD

**Issue by eromoe** [freqtrade/freqtrade#8342]
## Describe your environment

  * Operating system:  win 10
  * Python Version: 3.8
  * CCXT version: ccxt==2.9.4
  * Freqtrade Version: freqtrade 2023.3.dev-5d9868b54
   
## Your question

python interprator setting is correct,  and code can run in fact.

It is strange that , I tried to installed by pip and git :
- `pip install freqtrade`
- `git clone ...  && cd freqtrade && pip install -e .`

Both installation can't resolve the freqtrade in vscode : 
![image](https://user-images.githubusercontent.com/3938751/226082340-00677f52-5331-457d-b696-dc11f8bb8df0.png)

Because only happen on freqtrade, I am not sure is by vscode / pylance or freqtrade . 

My current workaround , may help someone has same issue : 

create `.vscode/settings.json` , and put in the freqtrade source path.
```
{
    "python.analysis.extraPaths": ["E:/Workspace/github_me/quant_learning/freqtrade"]
}
```

**Comment by xmatthias** [comment]
Vscode itself is working fine with the correct interpreter selected (this is running from a folder parallel to the freqtrade installation) where freqtrade is not available, but is only installed in the venv.

![image](https://user-images.githubusercontent.com/5024695/226090513-82fb159e-8670-4ba7-9c8d-0740da91de30.png)

The most likely bet is therefore still a bad / wrongly selected virtual environment.
If you're sure that's not the case, then your best bet is to look at the "output" tab for pylance (should be Python Language Server) - to see why it ain't detecting your installation.

pylance can also be restarted without restarting vscode ("Python: Restart language server")

Adding `python.analysis.extraPaths` is wrong for sure - and with the correct interpreter selected, is clearly not necessary (i don't have this configured at all).

**Comment by eromoe** [comment]
No clue for now,  env is corret and no error in pylance logs.  Even vscode debug same file is fine. 
Strange but at least add `python.analysis.extraPaths` can solve .. leave it be.

**Comment by xmatthias** [comment]
might be a pylance error / bug then.
i'd not know how to change "anything" to have pylance detect a package - it's either installed (and therefore can be found), or it isn't. There's no real middle-ground...
