### ISSUE TITLE
Multiple bots with different strategies on the same Binance account

### ISSUE THREAD

**Issue by wiltodelta** [freqtrade/freqtrade#8345]
## Your question

I will run multiple bots with different strategies on the same Binance account. I know how to make and run freqtrade with different databases and configs in parallel. So the question is about something other than that. 

Question regarding freqtrade settings. Is it enough to use the available_capital setting? Perhaps some tags separate assets and orders?

**Comment by xmatthias** [comment]
If possible, i'd recommend to use subaccounts - but i think binance is not giving that away that easily anymore.

`available_capital` will limit each bot to a subset of the capital.
each bot will "know" (have it in the database) which asset it owns - so as long as you don't interfere manually, there should be no problem with this.

**Comment by wiltodelta** [comment]
That is such a quick response. Thank you!

Will there be no problems even if the bots use the same pairs?

**Comment by xmatthias** [comment]
each bot knows how much it bought - and therefore how much it can sell.
it'll not try to sell 100 ETH if it only bought 50 ETH.

**Comment by keithorange** [comment]
> If possible, i'd recommend to use subaccounts - but i think binance is not giving that away that easily anymore.
> 
> `available_capital` will limit each bot to a subset of the capital. each bot will "know" (have it in the database) which asset it owns - so as long as you don't interfere manually, there should be no problem with this.

I also want to do this, this should **most definitely** be a **standard feature** and in the docs, because running a diversified set of strategies is common-sense. So how would I set this up like you have in your succesful experience? Just have each use the same `config.json` file with `available_capital = total / num_strategies` and then execute `freqtrade run-strategy StrategyX`  for all strategies? Is there a way to launch them all at once? Thank you!!

**Comment by xmatthias** [comment]
we have documentation for things to consider when using multiple instances.

The most straightforward / aligned way to start multiple bots at once is through docker - by configuring each as a separate compose service [as shown in the docs](https://www.freqtrade.io/en/latest/advanced-setup/#multiple-instances-using-docker).

**Comment by moinonin** [comment]
I have been doing this for years. But the catch is different stake currencies. I have always had one bot for each of the following ETH, BTC, BNB, USDT spot, and USDT futures

**Comment by xmatthias** [comment]
well yeah - in that case, the bots will not compete for the same capital, so it's not really comparable (though a neat solution - if you have strategies that work in each of these markets).
