### ISSUE TITLE
Optimizing indicator inputs with hyperopt

### ISSUE THREAD

**Issue by owlswaper** [freqtrade/freqtrade#8363]
Is there a way to optimize the best inputs of the indicator using hyperopt in addition to the outputs?

For example, RSI indicator uses 14 by default and I want to check it in the range of 10 to 20 with the default value of 14.
Is this possible?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

This is covered (exactly with the same questioning) in the [hyperopt documentation](https://www.freqtrade.io/en/stable/hyperopt/#optimizing-an-indicator-parameter).

I'd strongly suggest to read through the whole documentation page at least once, so you get a grasp of what freqtrade can do.
