### ISSUE TITLE
How to configure freqtrade if SL/TP does not buy/sell again in the same direction?

### ISSUE THREAD

**Issue by debian007** [freqtrade/freqtrade#8366]
I have the problem that when reaching an SL/TP, if the bot detects a new signal, it re-enters in the same direction, looking at other posts and the following solution occurred to me, I hope someone can validate it for me

```
def confirm_trade_exit(self, pair: str, trade: Trade, order_type: str, amount: float, rate: float, time_in_force: str, exit_reason: str, 
                                               current_time: datetime, **kwargs) -> bool:

      if exit_reason == "stoploss_on_exchange" and direction == "long":
             return False
       elif exit_reason == "stoploss_on_exchange" and direction == "short":
              return False
        elif exit_reason == "roi" and direction == "long":
              return False
        elif exit_reason == "roi" and direction == "short":
             return False
return True
```

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

you're implementing `confirm_trade_exit` - which (as the name implies) would prevent exits of open trades.

for one - you CANNOT block stoploss_on_exchange exits (the trade already exited, the strategy get's nothing to say in this case).

The above seems therefore clearly wrong - and absolutely not what you're after.
you may want to look at [`confirm_trade_entry`](https://www.freqtrade.io/en/stable/strategy-callbacks/#trade-entry-buy-order-confirmation) - but you'll not be provided with the exit direction of the previous trade - you'll have to get that yourself (read the [strategy documentation](https://www.freqtrade.io/en/latest/strategy-customization/) on how to do that).

I'm also not quite sure why you'd want to prevent an entry to a trade depending on the previous trade direction. 
It's a signal that tells you to go long - why would it be valid once - but not valid the 2nd time (maybe a a day or a week later??)
You'd get a strategy that's going to be heavily limited in a trending market - if the entry signal is good - preventing tons of good (trending) entries.
if the signal is bad obviously - having the direction change on each entry won't really make a difference either :laughing:

**Comment by escanoro** [comment]
@xmatthias : I'm not able to locate the option to tell freqtrade to 'pause' for X time in case of multiple stop losses, this may be a solution to this issue (Or an improvement).
Maybe i'm mistaken, but i think i read it somewhere on the doc.

Cheers,
Escanor

**Comment by escanoro** [comment]
@xmatthias : I'm not able to locate the option to tell freqtrade to 'pause' for X time in case of multiple stop losses, this may be a solution to this issue (Or an improvement).
Maybe i'm mistaken, but i think i read it somewjere on the doc.

Cheers,
Escanor

**Comment by xmatthias** [comment]
what you mean is [stoploss guard](https://www.freqtrade.io/en/stable/plugins/#stoploss-guard)

**Comment by escanoro** [comment]
Exactly, thanks!
