### ISSUE TITLE
Hyperopt is producing results where Trailing Stop Positive Offset is less than Trailing Stop Positive leading to backtest failure

### ISSUE THREAD

**Issue by scribbleee** [freqtrade/freqtrade#8367]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: Python 3.10.10
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: Freqtrade running in docker
 

## Describe the problem:
When running hyperopt it produces results where the trailing stop positive offset is less than the trailing stop positive i.e.
(trailing_stop_positive>trailing_stop_positive_offset_p1). 
Also, have observed, this column trailing_stop_positive_offset_p1 was previously just called trailing_stop_positive_offset without the p1 at the end, has the implementation of this column changed in hyperopt?

### Steps to reproduce:

  1. docker compose run --rm freqtrade hyperopt --hyperopt-loss SharpeHyperOptLossDaily --strategy BB --config user_data/configBB.json --timerange 20170817-20171231 -e 50 --spaces buy trailing stoploss
  2. docker compose run --rm freqtrade hyperopt-list --hyperopt-filename 50e15mstrategy.fthypt --export-csv user_data/BB50e.csv --best
  3. docker compose run --rm freqtrade backtesting --strategy BB --timerange 20200901-20201231  --config user_data/configBB.json  --cache none
  
### Observed Results:
Using the parameters from hyperopt results to run backtest, it fails with the following error. 

### Relevant code exceptions or logs

  ```
  //  freqtrade - ERROR - The config trailing_stop_positive_offset needs to be greater than trailing_stop_positive in your config.
  ```

**Comment by xmatthias** [comment]
Well i don't get a parameter of `trailing_stop_positive_offset_p1` shown when i test this with one of my strategies.

Can you please show a bit more details - like - the output of the hyperopt run (you can probably use `freqtrade hyperopt-show -n <someepoch>` to avoid re-running hyperopt).

The content of the .json file (same name as the strategy file) would also help - but will probably correspond to the output of the above command.

---

In default configurations - freqtrade has logic in place to add `trailing_stop_positive_offset_p1` on top of `trailing_stop_positive` - to avoid exactly the behavior you're describing above.

https://github.com/freqtrade/freqtrade/blob/8cf3e9f91b50fd7d615822e87a51aa997548dd59/freqtrade/optimize/hyperopt_interface.py#L155-L165


`trailing_stop_positive_offset_p1` is however not shown to the user / written to files - _unless_ a method of the hyperopt interface is overwritten (wrongly).

**Comment by scribbleee** [comment]
This is the output of a hyperopt which shows column trailing_stop_positive_offset_p1 as well as it's value being lesser than trailing_stop_positive. Can confirm that any method of the hyperopt interface was not touched.

![offset_p1](https://user-images.githubusercontent.com/128563600/226832257-954591e8-032b-4be6-8946-4c8112b50e00.JPG)
[configBB.txt](https://github.com/freqtrade/freqtrade/files/11037630/configBB.txt)


[BB.txt](https://github.com/freqtrade/freqtrade/files/11037631/BB.txt)

**Comment by xmatthias** [comment]
There's a difference between looking at the hyperopt file directly - and at the output.
Internally, this value will for sure be used - but the hyperopt file itself is NOT designed to be used directly. 
What counts is the output you get - as well as the `.json` file that's written.

can you please provide the content of `freqtrade hyperopt-show -n <someepoch>` - and/or the actual content of the file `BB.json` (assuming the strategy class is in a file called `BB.py`).

**Comment by scribbleee** [comment]
This is the result of the hyperopt list command, where you can see the column with the P1  heading. 
[BBhyperoptRESULT15m22e.csv](https://github.com/freqtrade/freqtrade/files/11039372/BBhyperoptRESULT15m22e.csv)

configBB.json and BB.py  was uploaded above in .txt format, as .json and .py files could not be uploaded. Content is the same.

**Comment by xmatthias** [comment]
I'm not interested in the .csv file - but in the output of `freqtrade hyperopt-show -n <someepoch>`, and in the output of the content `BB.json` file.

The CSV file is for reference only - and not relevant for actual operations.

please note:
I've asked for this same information now for the 3rd time.
i'll not ask a 4th time, and will close this issue if the requested information is not provided.

**Comment by scribbleee** [comment]
This is the BB.json generated after completing a hyperopt.
```
{
  "strategy_name": "BB_hyperopt",
  "params": {
    "roi": {
      "0": 100
    },
    "max_open_trades": {
      "max_open_trades": 10
    },
    "buy": {
      "buy_rsi": 28,
      "buy_rsi_enabled": false,
      "buy_trigger": "bb_lower2"
    },
    "sell": {},
    "protection": {},
    "stoploss": {
      "stoploss": -0.137
    },
    "trailing": {
      "trailing_stop": true,
      "trailing_stop_positive": 0.06,
      "trailing_stop_positive_offset": 0.106,
      "trailing_only_offset_is_reached": true
    }
  },
  "ft_stratparam_v": 1,
  "export_time": "2023-03-23 03:20:42.388261+00:00"
}
```

this is the freqtrade hyperopt-show -n <17>

[BBhyperoptshown17.txt](https://github.com/freqtrade/freqtrade/files/11047190/BBhyperoptshown17.txt)

thanks for assistance

**Comment by xmatthias** [comment]
this data confirms what i said above - the values are correctly resolved (added one on top of the other).
`trailing_stop_positive_offset_p1` does not show up in either of the two outputs, and using the values you see here will not cause backtesting to fail starting.

I therefore think that your problem is by using a odd (and honestly, non-necessary) manual step.
You might have noticed that running `freqtrade hyperopt-show -n 17` re-wrote the `BB.json` file (it'll do that for every epoch - as long as you don't specify `--disable-param-export`.

When backtesting (or running freqtrade in trade mode), freqtrade will automatically detect and load the parameters from BB.json file - thus making all manual work to transfer parameters into either configuration or strategy obsolete.

**Comment by xmatthias** [comment]
As the provided data shows that the behavior is correct when used according to the documentation, i'm going to close this issue.
