### ISSUE TITLE
Can we use market orders on Gateio via freqtrade in 2023? 

### ISSUE THREAD

**Issue by stspinu** [freqtrade/freqtrade#8368]
Hi team,

This question is a follow-up on this work item -> https://github.com/freqtrade/freqtrade/issues/6005

The exchange **Gateio** now **supports market orders** (starting with v4.34.0), as shown on their documentation below:
[GateIO Developer Documentation link](https://www.gate.io/docs/developers/apiv4/en/#changelog)

![image](https://user-images.githubusercontent.com/46924453/226857863-c0a8aa46-ddfb-47b4-ac70-cb3534012101.png)

Can we somehow use the market order in freqtrade (maybe with the development branch)? If not yet, are there any plans in introduce support for Market Orders?

Thank you!

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

you can use market orders for gate futures markets without problems (that's been available for quite some time).
for spot markets - it's not available at this point - and i don't plan on implementing a workaround for gate spot markets.

the correct way is to have this fixed / added in ccxt therefore best open an issue there. 
Once ccxt has this value updated, we can remove our current futures workaround, which should enable this for gate spot markets, too.

https://github.com/ccxt/ccxt/blob/eaf415341690c4700ed1a6d8f6d70a0aa89cdfe9/ts/src/gate.ts#L75

You can let me know in this issue once ccxt has updated / implemented spot orders for spot markets.

**Comment by stspinu** [comment]
> Please get used to filling out the issue template. Those who frequently omit the template may have their issues closed without comment. We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.
> 
> Filling out the template helps reduce our workload, and we greatly appreciate that.
> 
> you can use market orders for gate futures markets without problems (that's been available for quite some time). for spot markets - it's not available at this point - and i don't plan on implementing a workaround for gate spot markets.
> 
> the correct way is to have this fixed / added in ccxt therefore best open an issue there. Once ccxt has this value updated, we can remove our current futures workaround, which should enable this for gate spot markets, too.
> 
> https://github.com/ccxt/ccxt/blob/eaf415341690c4700ed1a6d8f6d70a0aa89cdfe9/ts/src/gate.ts#L75
> 
> You can let me know in this issue once ccxt has updated / implemented spot orders for spot markets.

hi Matthias, my apologies for not respecting the template. I will surely keep that in mind from now on and use the template format on my very next post. 

Great, I raised this problem with CCXT -> https://github.com/ccxt/ccxt/issues/17304

They confirmed they are already working on this -> https://github.com/ccxt/ccxt/pull/17306

Once they complete that task, will we be able to use market orders out of the box on freqtrade? I will naturally let you know once that is fully fixed. 


Thank you!
