### ISSUE TITLE
Inquiry regarding Node.js conversion project for freqtrade

### ISSUE THREAD

**Issue by Seungwoo321** [freqtrade/freqtrade#8370]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hello,

I'm interested in contributing to the freqtrade project by converting it to Node.js + TypeScript. I was wondering if there's already a Node.js + TypeScript conversion project in progress on the freqtrade issue tracker. If there is, I would love to participate and help with the conversion work. If not, I would like to express my interest and inquire about the possibility of starting a new project.

**Comment by xmatthias** [comment]
Freqtrade is a project written in python.
there is neither a reason, nor incentive to convert it to node.js / typescript.

Performance (as well as library support), especially in regards to data analysis will be WAY worse in node / typescript, considering that most indicator libraries use the python/c interface, running calculations in C.

the UI side ([freqUI](https://github.com/freqtrade/frequi)) on the other hand is written in vue/typescript.

contributions to both projects are more than welcome - but an approach to "change the language" will not be accepted nor supported in any form.
