### ISSUE TITLE
Issue with custom_exit and backtesting results

### ISSUE THREAD

**Issue by popperwin** [freqtrade/freqtrade#8371]
## Describe your environment

   * Operating system: Ubuntu 18.04
   * Python Version: 3.8.8 (python -V)
   * CCXT version: 1.89.14 (pip freeze | grep ccxt)
   * Freqtrade Version: freqtrade 2022.6 (freqtrade -V or docker-compose run --rm freqtrade -V for Freqtrade running in docker)

  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

My trading strategy involves defining a stop loss and take profit for each trade. To implement this strategy, I use `custom_stoploss` for stoploss and `custom_exit` for take_profit in Freqtrade. However, while backtesting my strategy, I have observed that the take_profit in custom_exit is not behaving as expected.

During backtesting, if the close of the candle is significantly above my specified take profit level, the trade is considered a winning trade at that close price. This is not ideal as I want to simulate the close at the specified take profit level during backtesting.

For example, if my take profit level is set at 5%, but the close of the candle is at +30%, the backtest will show the trade as a winning trade at +30%. I would like to simulate the close at the specified take profit level (i.e., 5%) during backtesting.

I am considering using `custom_exit_price` to force the price to correspond to the specified take profit and stop loss levels. 
My calculation would be would be:  
```
new_exitprice = trade.open_rate * (1+target_profit)
```
However, I am unsure if this is the best approach, and I am also uncertain how to account for fees when using custom_exit_price. 

Could you please provide guidance on how to correctly simulate custom_exit in backtesting, taking into account fees? Any advice or alternative approaches would be greatly appreciated.

Thank you for your help.

**Comment by xmatthias** [comment]
a signal from `custom_exit()` will be treated as a regular exit signal.
Freqtrade has no information on the price - and will therefore use "close".

You can read more about these assumptions [here](https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting).

In general, i'd encourage you not to go through lengths just to have backtesting satisfy if you then don't plan on using the same feature/functionality in live. That will probably lead to quite different backtest results than what reality would look like.

Instead, you can use `--timeframe-detail 1m` (or any other timeframe that's smaller than your main timeframe)  to simulate actual intra-candle movements. It'll still use the close (for the 1m candle) - but will probably closer to the actual result - without doing custom profit calculations.

**Comment by francisnahmnwtv** [comment]
I see. I believed that custom_exit_price would be useful because I came across this information in the documentation:

```
For exits based on exit-signal, custom-exit and partial exits: Call custom_exit_price() to determine exit price (Prices are moved to be within the closing candle).
```

https://www.freqtrade.io/en/stable/bot-basics/

Thus, I inferred that custom_exit_price could be used to set a price within the candle, and the order would execute at that price.

**Comment by xmatthias** [comment]
well yes that's correct - but i still find it dangerous to use `custom_exit_price` for backtesting - but then not use it for live - as you might get completely different results if you use completely different pricing versions.

**Comment by popperwin** [comment]
Thanks, issue closed!
