### ISSUE TITLE
Multiple bots UI nginx

### ISSUE THREAD

**Issue by Arivadis** [freqtrade/freqtrade#8372]
## Describe your environment

  * Operating system: Debian 5.10
  * Python Version: Python 3.9
  * Freqtrade Version: _2023.2
  
Hello!

I hope You are doing fine!

I am trying to set up freqUI via nginx on server, but getting problem with the second instance.

I tried both variants - mapped bots 1 and 2 with 8080 and 8081, pushed to nginx sites-enabled and sites-available link and file with property ports. Changed in docker property ports 80 and 81, and tried both variants using  CORS_origins: ["http://external_ip:80"] and "http://external_ip"] in both configs.
And nothing changed - I have acces to the first bot external_ip:80(or external_ip with no port) but cant connect to the second one.
The second external_ip:81 does not receive a response/request and hangs indefinitely trying to reach the page.
I guess I missed something in nginx/docker settings as external_ip:80 becomes external_ip(checked on another server - there is no such port disappearing, external_ip:80 connects to external_ip:80), but configs of nginx/docker.yml/config.json on both servers look similar:

```
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "",
        "ws_token": "",
        "CORS_origins": ["http://xx.xx.xx.xx"],
        "username": "123",
        "password": "1234"
    },
```
docker second port

```
# Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:8081:8080"
```
Nginx is active, both ports Listen
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      3674/docker-proxy   
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      3220/nginx: master  
tcp        0      0 127.0.0.1:8081          0.0.0.0:*               LISTEN      3688/docker-proxy   
tcp6       0      0 :::80                   :::*                    LISTEN      3220/nginx: master  
tcp6       0      0 :::81                   :::*                    LISTEN      3220/nginx: master  
```
Have no idea what else I need to use here. Open to any wariant(without Nginx, else).
Shoul I send any additional information - let me know, please.
PS. I know You do not recommend to have the freqtrade API available directly via the internet, I need UI time by time to be open.

Thank You for any help!
Have a nice day!

**Comment by Arivadis** [comment]
Git made a mess of my message... Sorry

**Comment by xmatthias** [comment]
nothing that a small edit can't fix. :)

i suspect the error is in the nginx config file (so we'll definitely need that config).
you'll need to proxy_pass the 81 port to 8081 ... if that's somehow messed up, i guess you won't have success connecting.

Even with nginx though, i'd strongly suggest to NOT run freqtrade in the open internet, but only run it in an internal network (look at tailscale / vpn / proxy tunnels for this).

**Comment by Arivadis** [comment]
Here are all configs
[2configs.txt](https://github.com/freqtrade/freqtrade/files/11054789/2configs.txt)
[default1.txt](https://github.com/freqtrade/freqtrade/files/11054790/default1.txt)
[docker-compose.txt](https://github.com/freqtrade/freqtrade/files/11054792/docker-compose.txt)

[nginx.txt](https://github.com/freqtrade/freqtrade/files/11054795/nginx.txt)


If I missed somethis - I can send it fast

**Comment by Arivadis** [comment]
Nevermind. I forgot to set ufw.
Who spend 2 hours looking in files? It is me.

**Comment by xmatthias** [comment]
ups :laughing:
