### ISSUE TITLE
Incorrect calculation of MaxDrawdown in MaxDrawdown protection plugin

### ISSUE THREAD

**Issue by popperwin** [freqtrade/freqtrade#8373]
## Describe your environment
    * Operating system: Ubuntu 18.04
    * Python Version: 3.8.8 (python -V)
    * CCXT version: 1.89.14 (pip freeze | grep ccxt)
    * Freqtrade Version: freqtrade 2022.6 (freqtrade -V or docker-compose run --rm freqtrade -V for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I am experiencing an issue with the MaxDrawdown protection plugin.
I have set the MaxDrawdown threshold to 15% in the plugin. 
According to backtest results, my strategy's account drawdown and drawdown percentage are only at 9.14%. 
However, upon inspecting the results json of the backtest, I noticed that there were several locks triggered due to the drawdown exceeding the limit of 15%.

Upon further examination of the trades section in the "locks" object, I realized that my drawdowns never reached 15%. In fact, they matched exactly what was displayed in the backtest summary in the console. 
After checking the "max_drawdown_protection.py" file, I found a suspicious TODO comment which could explain this issue: 
`# TODO: This should use absolute profit calculation, considering account balance.` located at "https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/plugins/protections/max_drawdown_protection.py#L59"

I am wondering if this issue is related to the TODO comment, and if so, how to address it. Would replacing the value_col parameter from 'close_profit' to profit_abs fix the issue?

Thank you for your help.

*Explain the problem you have encountered*

### Steps to reproduce:

  1. Run a backtest with MaxDrawdown protection plugin
  2. Check the drawdown in BT results
  3. Check the lock object in trades of BT json
  
### Observed Results:

  * What happened?
  MaxDrawdown protection is executed but drawdown limit is not reach

  * What did you expect to happen?
Drawdown protection to be accurate

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
> I am wondering if this issue is related to the TODO comment, and if so, how to address it. Would replacing the value_col parameter from 'close_profit' to profit_abs fix the issue?

No - unfortunately the calculation function for max_drawdown is heavily overloaded - and returns  a tuple of X (what feels like 20) records - each of which have a different meaning.
To actually switch this, you'll need to use one of the other values, too.

Now the TODO is there for multiple reasons - one - as it MAY need to be changed (as we changed the calculation for the backtest result - which however ALSO calculates the old method).
but more importantly - it's a breaking change - breaking people's expectations of current behavior - and therefore needs to be handled with care.


---

You should however also be careful as your version is now almost a year old - so i'd consider that version clearly unsupported.

**Comment by popperwin** [comment]
Sorry for the version, I copy pasted from an old issue 😅 The current version I use is freqtrade 2023.1

So what can be the approach to fix the behaviour of the maxdrawdown plugin ? If you have any insights about this, I would be happy to try to work on it and may be make a PR if I succeed to fix it

**Comment by xmatthias** [comment]
well in theory - look at how it's used elsewhere (`optimize_reports.py`?) - and use the correct parameters / value.

The docstring contains all the information as to what is needed - and to be sure, best have a look at what's used in optimize_reports (so it's aligned).

**Comment by popperwin** [comment]
Based on my analysis, the issue with the protection plugin seems to be related to the calculation of `max_drawdown` without specifying the `starting_balance` parameter in the `calculate_max_drawdown` function. It appears that the computation is not entirely accurate when the `starting_balance` is missing, as noted in the code comments at this link: https://github.com/freqtrade/freqtrade/blob/150c5510c74390641fd723f6a70b5f67f53ec9cf/freqtrade/data/metrics.py#L88-L94.

I have tried to find a way to obtain the current balance inside the protection plugin, but I have not been successful so far. Do you have any suggestions on how to achieve this? My plan is to calculate the current balance and withdraw the sum of profits from the trades to obtain the correct starting balance for the computation.

As a workaround, I have implemented the calculation directly in the strategy and it seems to be working fine. However, unfortunately, the results obtained with this corrected protection are consistently worse than the incorrect implementation, so may be I will keep using the incorrect one after all  😅

**Comment by xmatthias** [comment]
That's the problem i see with changing this (which is why this remaines a TODO ...) - depending on the strategy, it may make results better or worse - but it's potentially / probably changing most eoples expectation.

**Comment by popperwin** [comment]
I understand yes. Thanks. 
I can close this issue then
