### ISSUE TITLE
position stacking question

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#8377]
## Describe your environment

  * Operating system: __Docker__
  * Python Version: ___Python 3.10.10
  * CCXT version: ____ccxt==3.0.23
  * Freqtrade Version: _freqtrade docker-2023.3.dev-150c5510
  
## Your question

When "max_open_trades" is set to a 3 in the config file and strategy below :

```
buy_price_drop = DecimalParameter(0.0001, 1, decimals=4, default=0.1, space='buy')
    def custom_buy_condition(self, pair: str, current_rate: float, metadata: Dict) -> bool:
        open_trades = Trade.get_open_trades()
        pair_trades = [trade for trade in open_trades if trade.pair == pair]
        num_pair_trades = len(pair_trades)

        # Retrieve the buy_price_drop value from the strategy
        buy_price_drop = self.buy_price_drop.value

        if num_pair_trades < 3:
            last_buy_price = pair_trades[-1].open_rate if pair_trades else None
            if last_buy_price is None or current_rate <= last_buy_price * (1 - buy_price_drop):
                return True

        return False
        if conditions:
            combined_conditions = reduce(lambda x, y: x & y, conditions)
            custom_buy_condition = dataframe.apply(lambda x: self.custom_buy_condition(metadata['pair'], x['close'], metadata), axis=1)
            dataframe.loc[(combined_conditions & custom_buy_condition), ['enter_long', 'enter_tag']] = (1, 'ENTRY LONG')
```
my expectation is that I would receive more entries from the backtesting rather than in the scenario where max_open_trades" is set to 1.
The only difference between "max_open_trades"  (1 | 3)  is the profit mark where the other metrics are unchanged. I'm not sure if this is expected and what is the best method to troubleshoot position stacking. When I backtest and plot those 2 for comparison on the plot I see no difference in terms of the trade position. So not sure if this is expected or if I'm doing something wrong.

**Comment by xmatthias** [comment]
`max_open_trades` refers to trades (basically how many different open trades you can have in parallel). think about it as "how many parallel trade slots" you can have.

it does however NOT impact position movements - which change the size of a position (unless it sells everything, which would close out a position).
It'll therefore in general not impact the available positions.

**Comment by darioneto** [comment]
Thanks for your response. Ok, then there will be nothing related to the method, and the result should be expected. Shame, I was hoping for improvement in the % return terms, but as always the mind was falsely assuming the opposite :-)

**Comment by xmatthias** [comment]
it'll depend on the strategy  / number of pairs ... 
but unless your strategy benefits from tons of parallel open trades (if there's very few trades far apart, there's not much to gain from this), it's not changing results drastically.

**Comment by darioneto** [comment]
The strategy trades only one pair BTC/USDT. To my understanding, this is meant to provide a position build of additional value if there is a predefined price % drop. As from the backtesting the % return was much worst post-stacking implementation this may only suggest that there are a number of trades where this could work in favor however overall those few which are fully filled at the first entry signal and take off pay off much bigger than otherwise would waiting for the position stacking conditions to be met.

**Comment by xmatthias** [comment]
if `max_open_trades` is > the number of pairs (and you use `stake_amount=unlimited`) - then you're forcing your bot to only use part of your stake  (1/2 or 1/3 (or whatever the max_open_trade setting is).

while not a problem technically - that's clearly not going to optimize your results.
you may want to limit the total stake per pair to allow for additional rebuys - but this is then "details of your strategy".

**Comment by darioneto** [comment]
Correct this was my intention for this method and I was interested to see how it performs when I split the stake into 3 portions while hyperoting for the price % drop. I only trade one pair and made changes as described earlier however the results were much, much worst which was opposite to the expectations of this approach. Wasn't sure if this was also reflected in the number of entries that we clarified earlier as not related. It was just something that was not easy to verify via backtesting or plotting.

**Comment by stash86** [comment]
I assume what you actually need to look at is adjust_trade_position function, and not max_open_trades config

**Comment by darioneto** [comment]
oh ok, I thought I need position stacking for some reason to achieve this sort of controlled DCA. Thanks for your suggestion. I will look into it.
