### ISSUE TITLE
Exchange offline not handled gracefully

### ISSUE THREAD

**Issue by winginitau** [freqtrade/freqtrade#8378]
Somewhat unprecedented event. First thought was that freqtrade should handle an exchange problem gracefully (albeit with lots of warnings). 

Though perhaps its worthy of rolling exceptions and tracebacks. 

Mar 24 12:15:21 wusdutu ft_service_prod4.sh[10812]: ccxt.base.errors.OnMaintenance: binance System is under maintenance.
Mar 24 12:15:21 wusdutu ft_service_prod4.sh[10812]: 2023-03-24 12:15:21,339 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
Mar 24 12:15:21 wusdutu ft_service_prod4.sh[10812]: 2023-03-24 12:15:21,339 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Mar 24 12:15:21 wusdutu ft_service_prod4.sh[10812]: Traceback (most recent call last):

< lots of traceback messages>

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.


---

also - i don't see how we can help with "lots of traceback messages". based on the level of detail provided - i could close this issue with the explanation below  (in short - it'll recover once the exchange is back).

These are kindof expected as the exchange is offline (and there's no reliable way across exchanges to determine if an exchange is in maintenance mode, or which parts of it).
Once the exchange comes back online though - freqtrade will continue to operate normally.
