### ISSUE TITLE
Can we train a model on past data and then use the mode during live data ?

### ISSUE THREAD

**Issue by escanoro** [freqtrade/freqtrade#8381]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: _____ N/A
  * CCXT version: _____ N/A
  * Freqtrade Version: docker: freqtradeorg/freqtrade:stable (Current stable version as of 03 25 2023)
  
## Your question

Hi,

I'm using the last freqtrade stable version.
I started some model training using FreqAI using historical data:
`freqtrade backtesting ... --freqaimodel CatboostRegressor`
This generates a new model (defined by the model ID) (See screenshot)
![image](https://user-images.githubusercontent.com/128816061/227706707-0550fcd7-f6d9-447e-b3d6-aba8d2d7e5da.png)

Keep in mind that training data was available for all PAIRS (Screenhost is for reference)

When the training completed, i tried to put it directly in live mode (dry-run mode) using the same strategy and the same model ID:
`freqtrade trade... --freqaimodel CatboostRegressor`

**What i was expecting**
I expected that Freqtrade will use the existing model and improves it

**What happened**
Freqtrade shows messages that no model was ready for PAIR X

> 2023-03-25 08:31:36,247 - freqtrade.freqai.freqai_interface - WARNING - No model ready for MATIC/USDT:USDT, returning null values to strategy.

In the same time, the model folder was reset (Existing files were removed) and new folders and files started getting created.
It's like freqtrade started the training from scratch.

**Question**
- Is this supported ? I mean re-using a trained model (I assume yes, this is the goal)
- What am i missing ?
Here the freqai config:
```
    "freqai": {
        "enabled": true,
        "purge_old_models": 2,
        "train_period_days": 30,
        "backtest_period_days": 7,
        "continual_learning": true,
        "identifier" : "bb_ai_05",
        "feature_parameters" : {
            "include_timeframes": ["1h", "4h", "6h","1d"],
            "include_corr_pairlist": [
                "BTC/USDT:USDT",
                "ETH/USDT:USDT"
            ],
            "label_period_candles": 24,
            "include_shifted_candles": 2,
            "DI_threshold": 0.9,
            "weight_factor": 0.9,
            "principal_component_analysis": false,
            "use_SVM_to_remove_outliers": true,
            "indicator_periods_candles": [10, 20]
        },
        "data_split_parameters": {
            "test_size": 0.33,
            "random_state": 1
        },
        "plot_feature_importances": 1,
        "model_training_parameters": {
            "n_estimators" :  1000
        }
    }
```

**NB**: I used the question form instead of the Bug form because i wanted to know first if my scenario is supported

Thanks for your help

**Comment by escanoro** [comment]
There is one point that may be improved from my side, which is the **purgemodel** option.
I may have to increase it or switch it to **False**, but my original question is untouched: Can we train a model on historical data and use the model in live run. In that case, is there any 'required' options to be aware of (To be set on the config file)

Like` **save_backtest_models = true**`

Thanks

**Comment by escanoro** [comment]
There is one point that may be improved from my side, which is the **purgemodel** option.
I may have to increase it or switch it to **False**, but my original question is untouched: Can we train a model on hitroical data and use the model in live run. In that case, is there any 'required' options to be aware of (To be set on the config file)

Thanks

**Comment by robcaulk** [comment]
Hello, 

FreqAI concepts are quite well detailed in the docs, it appears you may benefit from reading them. Here I will paste the most relevant pieces to you with associated links so you can improve your understanding of how freqai automates real-time adaptive modeling for you.

“To save the models generated during a particular backtest so that you can start a live deployment from one of them instead of training a new model, you must set save_backtest_models to True in the config.”

https://www.freqtrade.io/en/latest/freqai-running/#saving-prediction-data_1

Keep in mind that doing this is typically not very useful unless you are training very few extremely large models. Based on your note here, you appear to be retraining quite often (which is good, and it is the expected use case of FreqAI). So this means that you will retrain a model quite quickly anyways as soon as you go live, and your backtest generated model becomes obsolete immediately. 

“This is especially true if you are trying to backtest on some timerange from long ago and then you try to set it dry or live at the present moment. FreqAI will still check to see how much time has elapsed since the model was trained (your last backtest trained model). If a full `live_retrain_hours` has elapsed since the end of the loaded model, FreqAI will start training a new model.”

https://www.freqtrade.io/en/latest/freqai-running/#live-deployments

cheers,

Robert

**Comment by escanoro** [comment]
Greetings

Thank you very much for your prompt and clear answer.
I have spend great time reading the doc, but since i started with back testing (I thought save_backtest_models = true has no effect, i was confused i think with **purge_old_models**), i was confused about its role in live/dry mode, but you have confirmed my thoughts now (you can see that i mentioned it on my previous reply before yours). 

I'm curious and  have a question though: What do you mean by : Keep in mind that doing this is typically not very useful unless you are training very few extremely large models --> What do you mean by **Large** models ? and do freqai uses always the last best model for prediction ? I want to understand how freqai works (or maybe the underlying library and modules)?
- Does all the kept models are good ?
- Or do the last models are the best ?
- What about `purge_old_models` ? It will immediately erase all my historical models generated by backtesting, so does it work with` save_backtest_models = true` ?



> and your backtest generated model becomes obsolete immediately.

- Why ? Why my models trained on 3 years historical data becomes obsolete ? (Maybe i'm missing important info here) ?

I'm continuing exploring all the parameters related to freqai, i'm experimenting playing on many params and hyper optimizing them, but i want to understand if my understandingg of the theory is correct


Thank you  @xmatthias  @robcaulk for your excellent work and patience.
Cherrs,
Escanor

**Comment by escanoro** [comment]
Greetings

Thank you very much for your prompt and clear answer.
I have spend great time reading the doc, but since i started with back testing (where save_backtest_models = true has no effect), i was confused about its role in live/dry mode, but you have confirmed my thoughts now (you can see that i mentioned it on my previous reply before yours). 

I'm curious and  have a question though: What do you mean by : Keep in mind that doing this is typically not very useful unless you are training very few extremely large models --> What do you mean by **Large** models ? and do freqai uses always the last best model for prediction ? I want to understand how freqai works (or maybe the underlying library and modules)?
- Does all the kept models are good ?
- Or do the last models are the best ?

I'm continuing exploring all the parameters related to freqai, i'm experimenting playing on many params and hyper optimizing them, but i want to understand if my undertaing of the theory is correct


Thank you  @xmatthias  @robcaulk for your excellent work and patience.
Cherrs,
Escanor

**Comment by robcaulk** [comment]
Hello,

A large model would be one that takes a long time to train. And one that you do not wish to retrain very frequently. For example, say your model takes a few days to train, and you only want to retrain it once per month. In this case, it could make sense to start from the final model of a backtest. 

A small model is one that does not take a long time to train. And one that you wish to retrain frequently. For example, say your model takes 60 seconds to train, and you want to train it as often as possible. In this case, it doesnt really matter if you start from backtest or from clean slate. You have a new model after 60 seconds anyways.

>Does all the kept models are good ?

Only the latest trained model is used for inference. All previous models are obsolete. You decide how often and when to train your models using `live_retrain_hours` and `expiration_hours`. Please have a look at our parameter table for more details than I am able to rewrite to you here https://www.freqtrade.io/en/stable/freqai-parameter-table/

>What about purge_old_models ? It will immediately erase all my historical models generated by backtesting, so does it >work with save_backtest_models = true ?

`purge_old_models` deletes all old models up to `purge_old_models` number of model folders. If you are running dry on a folder, it purges those. That would mean if you take a backtest created folder and then start dry with purge_old_models, it will purge old models up to `purge_old_models` number of model folders.

`save_backest_models` is to activate saving the models during a backtest.

>Why ? Why my models trained on 3 years historical data becomes obsolete ? (Maybe i'm missing important info here) ?

FreqAI makes no decisions for you on when to retrain and delete old models. That is decided by you, the user, with `live_retrain_hours`. If you want your model to continue being used for 6 months, then put 6 months of hours in that user configured location of your config.

I hope this helps you.

Cheers,

Robert

**Comment by escanoro** [comment]
Really Thanks! You know how to explain things! I understand better now.

The only non technical thing that is not yet clear to me (sorry to bother you, i like too much this stuff) is why should one keep more than 1 model if only the last one is used for inferencing and predictions?
This may be used to compare models ? But how do i know which model is the best ? Is it auto-selected by freqai ?

I hope this is my last question but this is getting interesting.
I beg you patience.

Regards,
Escanor
