### ISSUE TITLE
"buffer_train_data_candles" should be Integer instead of boolean ?

### ISSUE THREAD

**Issue by escanoro** [freqtrade/freqtrade#8384]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: _____ N/A
  * CCXT version: _____ N/A
  * Freqtrade Version: docker: freqtradeorg/freqtrade:stable (Current stable version as of 03 25 2023)
  

## Describe the problem:

The [doc](https://www.freqtrade.io/en/stable/freqai-parameter-table/) says that a **Boolean** should be used on the `freqai.feature_parameters.buffer_train_data_candles`

![image](https://user-images.githubusercontent.com/128816061/227731455-347cf88b-feb0-4481-945c-8d6aa10a27c6.png)

But i'm receiving an error stating that it should be integer
### Steps to reproduce:

  1. Set the `freqai.feature_parameters.buffer_train_data_candles` to false
  2. Run a Backtesting command
  
```
      backtesting
        --timeframe '15m'
        --timerange 20210101-20230315
        --data-format-ohlcv json
        --max-open-trades 20
        --stake-amount 1000
        --starting-balance 20000
        --strategy-list pivot_ai
        --config "/user_data/trading/freq/files/configs/config-static-ai_06.json"
        --userdir /user_data
        --strategy-path "/user_data/trading/freq/strategies/tests/ai"
        --freqaimodel CatboostRegressor
```
  
Here is the freqai conf:

```
    "freqai": {
        "enabled": true,
        "identifier" : "strategy_ai_06",
        "train_period_days": 30,
        "backtest_period_days": 7,
        "live_retrain_hours": 0,
        "expiration_hours": 0,
        "purge_old_models": 20,
        "save_backtest_models": true,
        "fit_live_predictions_candles": 0,
        "continual_learning": true,
        "write_metrics_to_disk": false,
        "data_kitchen_thread_count" : 0,        
        "feature_parameters" : {
            "include_timeframes": ["1h", "4h", "6h","1d"],
            "include_corr_pairlist": [
                "BTC/USDT:USDT",
                "ETH/USDT:USDT"
            ],
            "label_period_candles": 24,
            "include_shifted_candles": 2,
            "weight_factor": 0.9,
            "indicator_periods_candles": [10, 20],
            "principal_component_analysis": false,
            "plot_feature_importances": 0,
            "DI_threshold": 0.9,    
            "use_SVM_to_remove_outliers": true,
            "svm_params" : {},
            "use_DBSCAN_to_remove_outliers": true,
            "inlier_metric_window":0,
            "noise_standard_deviation":0,
            "outlier_protection_percentage":30,
            "reverse_train_test_order": false,
            "buffer_train_data_candles": false,
            "shuffle_after_split": false
            
            
        },
        "data_split_parameters": {
            "test_size": 0.33,
            "shuffle": false
        },

        "model_training_parameters": {
            "n_estimators" :  1000
        }
    },
```
### Observed Results:

  * An error is thrown indicating the parameter should be **int** instead of **bool**
  * I expected it to work correctly

### Relevant code exceptions or logs

  ```
freqtrade-train_ai  | 2023-03-25 16:58:56,152 - freqtrade.configuration.config_validation - CRITICAL - Invalid configuration. Reason: False is not of type 'integer'
freqtrade-train_ai  | 
freqtrade-train_ai  | Failed validating 'type' in schema['properties']['freqai']['properties']['feature_parameters']['properties']['buffer_train_data_candles']:
freqtrade-train_ai  |     {'default': 0, 'type': 'integer'}
freqtrade-train_ai  | 
freqtrade-train_ai  | On instance['freqai']['feature_parameters']['buffer_train_data_candles']:
freqtrade-train_ai  |     False
freqtrade-train_ai  | 2023-03-25 16:58:56,153 - freqtrade - ERROR - Fatal exception!
freqtrade-train_ai  | Traceback (most recent call last):
freqtrade-train_ai  |   File "/freqtrade/freqtrade/main.py", line 42, in main
freqtrade-train_ai  |     return_code = args['func'](args)
freqtrade-train_ai  |   File "/freqtrade/freqtrade/commands/optimize_commands.py", line 52, in start_backtesting
freqtrade-train_ai  |     config = setup_optimize_configuration(args, RunMode.BACKTEST)
freqtrade-train_ai  |   File "/freqtrade/freqtrade/commands/optimize_commands.py", line 21, in setup_optimize_configuration
freqtrade-train_ai  |     config = setup_utils_configuration(args, method)
freqtrade-train_ai  |   File "/freqtrade/freqtrade/configuration/config_setup.py", line 25, in setup_utils_configuration
freqtrade-train_ai  |     validate_config_consistency(config, preliminary=True)
freqtrade-train_ai  |   File "/freqtrade/freqtrade/configuration/config_validation.py", line 96, in validate_config_consistency
freqtrade-train_ai  |     validate_config_schema(conf, preliminary=preliminary)
freqtrade-train_ai  |   File "/freqtrade/freqtrade/configuration/config_validation.py", line 66, in validate_config_schema
freqtrade-train_ai  |     raise ValidationError(
freqtrade-train_ai  | jsonschema.exceptions.ValidationError: False is not of type 'integer'
  ```

**Comment by xmatthias** [comment]
you're right, the docs will need updating. Using a boolean here is clearly wrong.

**Comment by escanoro** [comment]
Thanks. Can you also explain (here or in the doc) the role of it? I did not well understood its impact. I did not understood how and why shoud i use it.

Thanks,
Cheers,
Escanor

**Comment by th0rntwig** [comment]
Allow me to hop on to try to clarify what the docs are saying:

- If you are using any kind of windowing to define your targets, such as numpy's argrelextrema which identifies extrema inside a sliding window, there is no way of knowing if the identified targets at the edges (start/end of the data set) are correct or not since we do not have access to data before/after. Not using the data inside this "buffer zone" to train the model ensures that we do not give spurious targets to the model. 

- If you are not using a target-setting method that relies on knowledge outside of your data set, you do not need this buffer. The example in the docs is to simply shift the price. In this case, the target entries at the end of the dataframe will be NaN and FreqAI will automatically remove the corresponding  rows.

I hope this makes the use of the buffer more clear.

**Comment by escanoro** [comment]
> Allow me to hop on to try to clarify what the docs are saying:
> 
> - If you are using any kind of windowing to define your targets, such as numpy's argrelextrema which identifies extrema inside a sliding window, there is no way of knowing if the identified targets at the edges (start/end of the data set) are correct or not since we do not have access to data before/after. Not using the data inside this "buffer zone" to train the model ensures that we do not give spurious targets to the model. 
> 
> - If you are not using a target-setting method that relies on knowledge outside of your data set, you do not need this buffer. The example in the docs is to simply shift the price. In this case, the target entries at the end of the dataframe will be NaN and FreqAI will automatically remove the corresponding  rows.
> 
> I hope this makes the use of the buffer more clear.

Thanks, your explanations are clear, but my lack of knowledge about some terms is what is unclear for me. I will learn it untile i understand it.

Thanks for your contribution.
Cheers,
Escanor
