### ISSUE TITLE
want to understand drawdown high and drawdown low.

### ISSUE THREAD

**Issue by mdnaimul22** [freqtrade/freqtrade#8385]
Min balance                 | 998.068 USDT       
Max balance                 | 1397.973 USDT      
Max % of account underwater | 4.65%               
Absolute Drawdown (Account) | 4.65%               
Absolute Drawdown           | 50.381 USDT         
Drawdown high               | 82.618 USDT         
Drawdown low                | 32.237 USDT

Hi matthias please can you explain me, i am little confuse about drawdown high and drawdown low.

I hope Drawdown high is max position open unrealized pnl. is it right?

Another Question Drawdown high metric which is better to be low or high?

**Comment by xmatthias** [comment]
Backtesting metrics are explained [in the documentation](https://www.freqtrade.io/en/latest/backtesting/#summary-metrics).
