### ISSUE TITLE
Backtesting ignores can_short = False when used with existing freqai model

### ISSUE THREAD

**Issue by escanoro** [freqtrade/freqtrade#8387]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: _____ N/A
  * CCXT version: _____ N/A
  * Freqtrade Version: docker: freqtradeorg/freqtrade:stable (Current stable version as of 03 25 2023)
  

## Describe the problem:

- I have a strategy with `can_short = True`
- I started training a model using Backtesting
- After the training was completed i noticed that the model loses badly on Short positions
- I switched `can_short `to `False` on the Strategy
- I restarted the back testing
- The results always shows Short positions, it's like the setting is ignored

I suspect the following settings : 
```
 "live_retrain_hours": 0,
 "expiration_hours": 0,
```

But what is not clear to me is why freqtrade ignored totally to strategy content (apart from feature_engineering which is stated that freqtrade will restart training if modified)

### Steps to reproduce:

  1. Create a freqai enabled Strategy with `can_short = True`
  2. Backtest it with freeqai enabled (Ex: --freqaimodel CatboostRegressor)
  3. Switch can_short to False
  4. Backtest again with the same configuration
  
### Observed Results:

  * Same results as is `can_short = True` was set
  * I expected only Long positions

### Relevant code exceptions or logs

Freai config

  ```
    "freqai": {
        "enabled": true,
        "identifier" : "strategy_ai_06",
        "train_period_days": 30,
        "backtest_period_days": 7,
        "live_retrain_hours": 0,
        "expiration_hours": 0,
        "purge_old_models": 20,
        "save_backtest_models": true,
        "fit_live_predictions_candles": 0,
        "continual_learning": true,
        "write_metrics_to_disk": false,
        "data_kitchen_thread_count" : 0,        
        "feature_parameters" : {
            "include_timeframes": ["1h", "4h", "6h","1d"],
            "include_corr_pairlist": [
                "BTC/USDT:USDT",
                "ETH/USDT:USDT"
            ],
            "label_period_candles": 24,
            "include_shifted_candles": 2,
            "weight_factor": 0.9,
            "indicator_periods_candles": [10, 20],
            "principal_component_analysis": false,
            "plot_feature_importances": 0,
            "DI_threshold": 0.9,    
            "use_SVM_to_remove_outliers": true,
            "svm_params" : {},
            "use_DBSCAN_to_remove_outliers": true,
            "inlier_metric_window":0,
            "noise_standard_deviation":0,
            "outlier_protection_percentage":30,
            "reverse_train_test_order": false,
            "shuffle_after_split": false
            
            
        },
        "data_split_parameters": {
            "test_size": 0.33,
            "shuffle": false
        },

        "model_training_parameters": {
            "n_estimators" :  1000
        }
    }
  ```

**Backtest Results**

```
...
...
 Long / Short                | 253 / 258  
...
...
```

**Comment by xmatthias** [comment]
Don't think this is related to freqAI at all.
the check for "can_short" in backtesting is currently only checking for the mode (futures / spot) - but not for the flag in the strategy.

will be fixed shortly

**Comment by escanoro** [comment]
Seems fair. Will use **spot** instead for that particular case, as i'm not using leverage.

Thanks

**Comment by escanoro** [comment]
Seems fair. Will use **spot** instead for that particular case, as i'm not using leverage.

Thanks

**Comment by xmatthias** [comment]
be careful as that means that 
* your pairs are different
* and consequently, might behave slightly different
* need a new data-download - as it's new / different pairs.

**Comment by escanoro** [comment]
You're correct, thanks for the point

**Comment by escanoro** [comment]
I didn't catch it, i had just to comment/remove the Short Entries and Exits.
