### ISSUE TITLE
Freq UI does not refresh on its own

### ISSUE THREAD

**Issue by dpd123** [freqtrade/freqtrade#8403]
## Describe your environment

  * Operating system: Linux (Gentoo/Docker)
  * Python Version: 3.10.10
  * CCXT version: 2.8.17
  * Freqtrade Version: 2023.2

*Explain the problem you have encountered*

I would like to display the FreqUI ticker as my strategy runs. Sometimes the screen updates with every candle. Other times it does not, and I have to hit the refresh button myself.

Auto refresh is checked. The problem seems to be intermittent, and based on some detail of the strategy file, as it breaks at some point while I'm developing the strategy, but I have not found a cause or correlation.

### Steps to reproduce:

  1. Load my strategy in FreqUI
  2. Wait for automatic update
  3. Doesn't happen 
  
### Observed Results

  * What happened? No auto update
  * What did you expect to happen? Auto update

### Relevant code exceptions or logs

Nothing unusual in logs, everything else working, but if you want a log snippet please let me know.
Thanks for a VERY excellent open source project, it has been a lot of fun so far!

**Comment by xmatthias** [comment]
it's pretty much unclear what you're trying to do.

automatic refreshes will work for trade mode - and will refresh the visible pair (if the bot is determined as active at that point) whenever a new candle arrives / is published.
FreqUI will not reload the chart mid-candle unless you either change pair or manually request a refresh.

But then you talk about strategy development, which would sound more like webserver mode - in which there are no refreshes - but a chart refresh MUST be triggered manually (you could be asking for 1 year of data, which might take a long time to generate / analyze).

**Comment by dpd123** [comment]
Thanks for your reply, I will clarify. I am trying to watch the FreqUI in trade mode, that is all.

I am in trade mode, and the visible pair is not refreshing on an incoming candle. The bot is active, with heardbeats and INFO messages coming in on the throttle interval, just no updates to the FreqUI screen until I press the refresh button.

If I am set to 1 minute candles, I wait many minutes without a refresh, no chart updates until I press the manual refresh button. Then after pressing it, the missing candles are drawn, along with entry and exit signals and other chart features I'm rendering.

I do have api_server enabled. I mention strategy development because I am testing the strategy I'm developing, in trade mode, viewing the freqUI in real time to make sure it's making the right moves. Reloading config to reload changes to the strategy class file.

It would be nice if there was auto refresh of incoming candles without manually pressing refresh, especially when I leave the bot running all day, viewing through a grafana panel or some such. I've had the auto update work before, but after some changes to the stategy file, it no longer updates on its own. Then, when I reload a different strategy, it might work.


config.json:
{
    "max_open_trades": 10,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "1m",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": true,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist":   [
            //"BTC/USDT:USDT",
            "LTC/USDT:USDT",
            //"MATIC/USDT:USDT",
            //"ETH/USDT:USDT"
            ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    // "pairlists": [
    //     {
    //         "method": "VolumePairList",
    //         "number_assets": 20,
    //         "sort_key": "quoteVolume",
    //         "min_value": 0,
    //         "refresh_period": 1800
    //     }
    // ],

    "pairlists": [
        {
            "method": "StaticPairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": true,
        "token": "6234541856:AAF0rnRUrA8vMlOi3yiFAXfQ0PQwDuc3qPw",
        "chat_id": "DrunkenTrailorBot"
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "5cdae564da262c65ee6234483dd724a4ec2c758e8d60b0cf8e4eaf5c7690e436",
        "ws_token": "WI0dDfz1nYjPJ4TfWaI44FDnzCK70FBDVg",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "freaqy69"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

**Comment by xmatthias** [comment]
auto-update works fine for me, and is based on 
* having an uptodate UI version (visible in the top right corner of the UI)
* having a more or less recent freqtrade version
* websocket connections to be working

to have automatic updates working, the websocket connection needs to be up. (this will also cause a message entry in freqtrade itself on connect/disconnect - something like `freqtrade.rpc.api_server.ws.channel - INFO - Connected to channel 
 ... `)), and avoids unnecessary traffic.
If a refresh of the UI does not cause this - then you've either got an old UI version (update) - or you're using some non-default setup involving reverse proxies (or something else) that's preventing websocket connections from working.

Best check the browser dev tools window - the network tab should show a websocket connection - and the console may have details if the connection failed.

**Comment by dpd123** [comment]
Everything should be reasonably up to date, UI says V: 0.6.7
The websocket appears to be fine, no disconnect messages or other anomalies.
No proxy or firewall between my browser and docker container, just regular docker iptables.

I'll keep an eye on it and try to figure out what the correlation is between strategy file changes, and failure to UI update. Maybe I can find the pattern. Backtesting works fine so the strategy file is OK. If no one else is reporting the same problem then I'll keep your tips in mind and see what I can figure out, thanks again!

**Comment by xmatthias** [comment]
Please try with 0.6.8.
There's been some odd behavior if no pair has been selected explicitly (by clicking it on the left box) - which has been fixed weeks ago in 0.6.8.

you can update your UI version with a simple `freqtrade install-ui` (you don't seem to use docker - which simplifies this).

**Comment by dpd123** [comment]
Great, thanks! I am using docker (I hid it in the OS field of the issue template) so I will update immediately.

**Comment by dpd123** [comment]
Still having the same problem in 0.6.8
In the time since I opened the issue, I have had it updating automatically, and not, still not sure of the reason.

However, I realized I gave bad info before: when it is not updating automatically I can't see a websocket getting connected in the log. At the time, it was working, so I was going from memory.

When it skips establishing the websocket connection, it seems I can make it open one by clicking on the bigger refresh button, Auto Refresh All Bots. (The checkmark is always checked) so if this always works to force a websocket open that didn't start on its own, I have a workaround. 

Definitely good enough for now, and I'll keep fooling around to see if I can find a pattern around when it does and doesn't start a websocket automatically.

**Comment by xmatthias** [comment]
most likely, your bot is determined to be offline, then.
once it comes back, it'll try to connect the websocket - but when it's offline, it doesn't even try (it'll however do pings every minute or so).

**Comment by dpd123** [comment]
Indeed! The top status bar indicates "Offline" until I press the big reset, then it flips to "Online" and the websocket connects in the log.

I mentioned earlier but should re-iterate, I'm pressing reload-config a lot and this might have something to do with starting up in offline state.

Regardless, now that I have a way to always kick it on, no issue.

**Comment by xmatthias** [comment]
> The top status bar indicates "Offline" until I press the big reset

while it's offline - you should see regular fetch-requests to `/ping` once every minute.

so your maximum offline time would be 1m after a restart of the bot.

**Comment by dpd123** [comment]
I'll see if I can figure out why it doesn't go online on its own. If I leave it for 1000 candles without connecting manually, it will fail to draw 1000 candles until I refresh. Simple workaround though, so I'll post more if I discern any more pattern.

**Comment by xmatthias** [comment]
While the bot is offline - you'll see this every minute - which is the bot trying to reconnect.

![image](https://user-images.githubusercontent.com/5024695/228729668-1a648e11-918b-4135-ad2e-0721a0b7c532.png)

**Comment by xmatthias** [comment]
Improved recovery in freqUI 0.7.0 should help this behavior.

**Comment by dpd123** [comment]
Can confirm, with 0.7.0 no more issues with this. Thanks and well done!
