### ISSUE TITLE
Failed installing dependencies: catboost

### ISSUE THREAD

**Issue by sinak7** [freqtrade/freqtrade#8404]
## Describe your environment

  * Operating system: raspberry pi OS bullseye
  * Python Version: Python 3.9.2
  * CCXT version: ccxt==3.0.37
  * Freqtrade Version: New installation
  
## Describe the problem:
Hello, 

I followed the instructions for installing freqtrade on RaspberryPI here: https://www.freqtrade.io/en/stable/installation/ and when I run ./setup.sh -i and I'm getting 

```
ERROR: Could not find a version that satisfies the requirement catboost==1.1.1 (from versions: none)
ERROR: No matching distribution found for catboost==1.1.1
Failed installing dependencies

```
Thanks!

**Comment by xmatthias** [comment]
catboost does not provide wheels for arm distributions - so it would require a compilation on device (which is usually not feasible on a raspberry).

I'm also not entirely sure if you really need freqAI dependencies on a raspberry - it's most likely not powerfull enough to run any model (you can skip this by selectiong "N" on the develop and freqAI dependency questions).

We'll be adding an exclusion for catboost on arm32 later on (it's already excluded for 64bit distributions).
