### ISSUE TITLE
Shifted RSI indicator 

### ISSUE THREAD

**Issue by NL647** [freqtrade/freqtrade#8406]
Hello, 
I m using Freqai RL and following the documentation for the learner , 
I want to know how should shifted RSI indicator properly  generated in the strategy to match the example?

[https://www.freqtrade.io/en/latest/freqai-reinforcement-learning/#creating-a-custom-reward-function](url)

`                # you can use feature values from dataframe
                # Assumes the shifted RSI indicator has been generated in the strategy.
                rsi_now = self.raw_features[f"%-rsi-period-10_shift-1_{pair}_"
                                f"{self.config['timeframe']}"].iloc[self._current_tick]`

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Best read through the [feature engineering](https://www.freqtrade.io/en/stable/freqai-feature-engineering/#feature-engineering) documentation, which explains the whole process of how features are generated, which are then used in subsequent parts of the freqAI documentation.
