### ISSUE TITLE
Freqtrade is not recognizing my model files and throwing errors:  Unexpected error [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by escanoro** [freqtrade/freqtrade#8407]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: _____ N/A
  * CCXT version: _____ N/A
  * Freqtrade Version: docker: freqtradeorg/freqtrade:stable (Current stable version as of 03 28 2023)
  
## Your question

I used the question form because i don't know if this is a bug or an error from my part
I have 2 machines:
- Machine 1: for training ai models on historical data (Years) and for hyper-opt (Resource intensive tasks)
- Machine 2: for live and dry mode

After training a model on historical data, i copied the models/model-id folder to the Machine 2 under /models
I used exactly the same configuration file with zero modification
**NB: I tested the 'trade' mode on Machine 1 prior to switching to Machine 2, the trade starts and the training continued**

When i start the bot on Machine 2, i receive errors stating that no files were found under models/model-id.
I can confirm that the files exist under the correct path.

![image](https://user-images.githubusercontent.com/128816061/228218169-cfab8660-0153-4b1b-b370-3754a5a1d7f3.png)

**If for example, i rename my model folder (strategy_ai_07 --> strategy_ai_07_old) and launch the bot, i can confirm that a new folder strategy_ai_07 is being created under the '/user_data/models/)**

> FileNotFoundError: [Errno 2] No such file or directory: '/user_data/models/strategy_ai_07/sub-train-BCH_1678406400/cb_bch_1678406400_metadata.json'
> freqtrade-ai_07  | 2023-03-28 10:28:01,001 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair BCH/USDT:USDT: [Errno 2] No such file or directory: '/user_data/models/strategy_ai_07/sub-train-BCH_1678406400/cb_bch_1678406400_metadata.json'
> freqtrade-ai_07  | 2023-03-28 10:28:01,032 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error [Errno 2] No such file or directory: '/user_data/models/strategy_ai_07/sub-train-FIL_1678406400/cb_fil_1678406400_metadata.json' calling <bound method IStrategy._analyze_ticker_internal of <ai_07.ai_07 object at 0x7f6e20532a10>>
> freqtrade-ai_07  | Traceback (most recent call last):
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
> freqtrade-ai_07  |     return f(*args, **kwargs)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/strategy/interface.py", line 850, in _analyze_ticker_internal
> freqtrade-ai_07  |     dataframe = self.analyze_ticker(dataframe, metadata)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/strategy/interface.py", line 828, in analyze_ticker
> freqtrade-ai_07  |     dataframe = self.advise_indicators(dataframe, metadata)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/strategy/interface.py", line 1336, in advise_indicators
> freqtrade-ai_07  |     return self.populate_indicators(dataframe, metadata)
> freqtrade-ai_07  |   File "/freqtrade/user_data/repos/trading/freq/run/dry-run/strategies/ai/ai_07.py", line 251, in populate_indicators
> freqtrade-ai_07  |     dataframe = self.freqai.start(dataframe, metadata, self)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 147, in start
> freqtrade-ai_07  |     dk = self.start_live(dataframe, metadata, strategy, self.dk)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 409, in start_live
> freqtrade-ai_07  |     self.model = self.dd.load_data(metadata["pair"], dk)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/freqai/data_drawer.py", line 517, in load_data
> freqtrade-ai_07  |     with open(dk.data_path / f"{dk.model_filename}_metadata.json", "r") as fp:
> freqtrade-ai_07  | FileNotFoundError: [Errno 2] No such file or directory: '/user_data/models/strategy_ai_07/sub-train-FIL_1678406400/cb_fil_1678406400_metadata.json'
> freqtrade-ai_07  | 2023-03-28 10:28:01,033 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair FIL/USDT:USDT: [Errno 2] No such file or directory: '/user_data/models/strategy_ai_07/sub-train-FIL_1678406400/cb_fil_1678406400_metadata.json'
> freqtrade-ai_07  | 2023-03-28 10:28:01,064 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error [Errno 2] No such file or directory: '/user_data/models/strategy_ai_07/sub-train-XLM_1678406400/cb_xlm_1678406400_metadata.json' calling <bound method IStrategy._analyze_ticker_internal of <ai_07.ai_07 object at 0x7f6e20532a10>>
> freqtrade-ai_07  | Traceback (most recent call last):
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
> freqtrade-ai_07  |     return f(*args, **kwargs)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/strategy/interface.py", line 850, in _analyze_ticker_internal
> freqtrade-ai_07  |     dataframe = self.analyze_ticker(dataframe, metadata)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/strategy/interface.py", line 828, in analyze_ticker
> freqtrade-ai_07  |     dataframe = self.advise_indicators(dataframe, metadata)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/strategy/interface.py", line 1336, in advise_indicators
> freqtrade-ai_07  |     return self.populate_indicators(dataframe, metadata)
> freqtrade-ai_07  |   File "/freqtrade/user_data/repos/trading/freq/run/dry-run/strategies/ai/ai_07.py", line 251, in populate_indicators
> freqtrade-ai_07  |     dataframe = self.freqai.start(dataframe, metadata, self)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 147, in start
> freqtrade-ai_07  |     dk = self.start_live(dataframe, metadata, strategy, self.dk)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 409, in start_live
> freqtrade-ai_07  |     self.model = self.dd.load_data(metadata["pair"], dk)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/freqai/data_drawer.py", line 517, in load_data
> freqtrade-ai_07  |     with open(dk.data_path / f"{dk.model_filename}_metadata.json", "r") as fp:
> freqtrade-ai_07  | FileNotFoundError: [Errno 2] No such file or directory: '/user_data/models/strategy_ai_07/sub-train-XLM_1678406400/cb_xlm_1678406400_metadata.json'
> freqtrade-ai_07  | 2023-03-28 10:28:01,065 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair XLM/USDT:USDT: [Errno 2] No such file or directory: '/user_data/models/strategy_ai_07/sub-train-XLM_1678406400/cb_xlm_1678406400_metadata.json'
> freqtrade-ai_07  | 2023-03-28 10:28:01,096 - freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error [Errno 2] No such file or directory: '/user_data/models/strategy_ai_07/sub-train-VET_1678406400/cb_vet_1678406400_metadata.json' calling <bound method IStrategy._analyze_ticker_internal of <ai_07.ai_07 object at 0x7f6e20532a10>>
> freqtrade-ai_07  | Traceback (most recent call last):
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/strategy/strategy_wrapper.py", line 27, in wrapper
> freqtrade-ai_07  |     return f(*args, **kwargs)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/strategy/interface.py", line 850, in _analyze_ticker_internal
> freqtrade-ai_07  |     dataframe = self.analyze_ticker(dataframe, metadata)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/strategy/interface.py", line 828, in analyze_ticker
> freqtrade-ai_07  |     dataframe = self.advise_indicators(dataframe, metadata)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/strategy/interface.py", line 1336, in advise_indicators
> freqtrade-ai_07  |     return self.populate_indicators(dataframe, metadata)
> freqtrade-ai_07  |   File "/freqtrade/user_data/repos/trading/freq/run/dry-run/strategies/ai/ai_07.py", line 251, in populate_indicators
> freqtrade-ai_07  |     dataframe = self.freqai.start(dataframe, metadata, self)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 147, in start
> freqtrade-ai_07  |     dk = self.start_live(dataframe, metadata, strategy, self.dk)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/freqai/freqai_interface.py", line 409, in start_live
> freqtrade-ai_07  |     self.model = self.dd.load_data(metadata["pair"], dk)
> freqtrade-ai_07  |   File "/freqtrade/freqtrade/freqai/data_drawer.py", line 517, in load_data
> freqtrade-ai_07  |     with open(dk.data_path / f"{dk.model_filename}_metadata.json", "r") as fp:
> freqtrade-ai_07  | FileNotFoundError: [Errno 2] No such file or directory: '/user_data/models/strategy_ai_07/sub-train-VET_1678406400/cb_vet_1678406400_metadata.json'
> freqtrade-ai_07  | 2023-03-28 10:28:01,096 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair VET/USDT:USDT: [Errno 2] No such file or directory: '/user_data/models/strategy_ai_07/sub-train-VET_1678406400/cb_vet_1678406400_metadata.json'

What can this be ?
Is this permissions issue ?

Thanks,
Escanoro

**Comment by xmatthias** [comment]
Well transferring model directories is not really something we do support.
As such, this is clearly no bug - as i'm sure it'll work fine when used according to the documentation (training on the same system with a new identifier).

Transferring manually can be quite error-prone (as you can see). freqAI is storing the path to the model files - so to have this work - you'll basically need to have the same exact directory structure on both systems.

the error is quite clear i think - it's loading from `/user_data/models/` (default for docker installations would be `/freqtrade/user_data/models/`).
This suggests that either one of the system is not a docker installation (and therefore has different paths), or you have somehow messed with one of the docker-compose filse (specifically the mounts), and are using different directories between the two environments.

**Comment by escanoro** [comment]
I solved it finally.
The **pair_dictionary.json** (under models/model-id) contains a hard path to the data file
`"ALGO/USDT:USDT":{"model_filename":"cb_algo_1677801600","trained_timestamp":1677801600,"data_path":"/user_data/models/strategy_ai_07/sub-train-ALGO_1677801600","`

Since my Machine 1 and Machine 2 does not mount the same path for user Data (in the docker file), it was unable to find the file:

My Current Docker File : /freq/user_data is the root path (volumes)
```
  freqtrade-ai_07:
    image: freqtradeorg/freqtrade:stable_freqai
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: "no"
    container_name: freqtrade-ai_07
    ports:
      - "0.0.0.0:9090:9090"
    volumes:
      - "/home/sam/ft_userdata/user_data:/freq/user_data"
    command: >
        trade
          --logfile /freq/user_data/logs/freqtrade-ai_07.log
          --db-url sqlite:////freq/user_data/tradesv3-ai_07.sqlite
          --config /freq/user_data/repos/trading/freq/run/dry-run/configs/config-StaticPairList-ai_07.json
          --strategy-path "/freq/user_data/repos/trading/freq/run/dry-run/strategies/ai"
          --userdir /freq/user_data
          --strategy ai_07
          --freqaimodel CatboostRegressor
```

**After modifying the path so that /user_data is the root, it worked**

```
  freqtrade-ai_07:
    image: freqtradeorg/freqtrade:stable_freqai
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: "no"
    container_name: freqtrade-ai_07
    ports:
      - "0.0.0.0:9090:9090"
    volumes:
      - "/home/sam/ft_userdata/user_data:/user_data"
    command: >
        trade
          --logfile /user_data/logs/freqtrade-ai_07.log
          --db-url sqlite:////user_data/tradesv3-ai_07.sqlite
          --config /user_data/repos/trading/freq/run/dry-run/configs/config-StaticPairList-ai_07.json
          --strategy-path "/user_data/repos/trading/freq/run/dry-run/strategies/ai"
          --userdir /user_data
          --strategy ai_07
          --freqaimodel CatboostRegressor
```

That was hard to find, but at least i found it.
So for future folks that encounters this issue, you have two options:
- Set **/user_data** as the root path on your docker file
- Or, with a script, replace all **/user_data** occurrences with your **root path** for all files under the model folder

**Comment by escanoro** [comment]
> Well transferring model directories is not really something we do support. As such, this is clearly no bug - as i'm sure it'll work fine when used according to the documentation (training on the same system with a new identifier).
> 
> Transferring manually can be quite error-prone (as you can see). freqAI is storing the path to the model files - so to have this work - you'll basically need to have the same exact directory structure on both systems.
> 
> the error is quite clear i think - it's loading from `/user_data/models/` (default for docker installations would be `/freqtrade/user_data/models/`). This suggests that either one of the system is not a docker installation (and therefore has different paths), or you have somehow messed with one of the docker-compose filse (specifically the mounts), and are using different directories between the two environments.

I saw your answer just after my reply, indeed, that was the issue.
