### ISSUE TITLE
Backtest to only trade on weekend

### ISSUE THREAD

**Issue by yclai** [freqtrade/freqtrade#8410]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi, I would like to ask if it is possible to backtest a strategy to only enter trades on weekend (Saturday and Sunday) while ignoring weekdays?

**Comment by xmatthias** [comment]
you get a pandas dataframe in [this format](https://www.freqtrade.io/en/latest/strategy-customization/#dataframe).

the date column is of type pd.Timestamp - so you get access to all the pandas date functionality (`dataframe['date'].dt.xxx`).
With that, it should be pretty simple to filter either on weekdays - or on specific hours of the day.

The precise details however - i'll leave to you to find out. 
The pandas documentation is quite good, so it should be pretty simple to find what you need.
