### ISSUE TITLE
Freqtrade extend predefined whitelist pairs

### ISSUE THREAD

**Issue by le8888e** [freqtrade/freqtrade#8411]
Hi, why do freqtrade extend whitelist pairs which are predefined in the config file with active open trade pairs? And what is the proper way to configure whitelist pairs if I only want to trade 'BTC/USDT' and 'ETH/USDT'？Thanks : )
![791679993431_ pic](https://user-images.githubusercontent.com/34771253/228296658-76a8ec5a-e092-43ca-9517-f4100b338353.jpg)
![371679901094_ pic](https://user-images.githubusercontent.com/34771253/228296820-ed1feada-4aec-40f7-a618-3d20684d9697.jpg)

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Open trades will always be added to the pairlist. 
They're open trades and you expect them to be handled properly, which means the bot needs to have them in the pairlist (only pairs in the pairlist get their data actually refreshed).

Your configuration is fine as is - and once the open trades are closed these pairs will no longer be in the pairlist, leaving you what is actually configured.

---

The question itself implies that you're on a dry-run and would like to start fresh - which you can do by deleting the existing database file - or by using a different database file by specifying that via `--db-url`.
