### ISSUE TITLE
ignore_roi_if_entry_signal

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8413]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.2 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I have not entirely understood the switch 'ignore_roi_if_entry_signal'. So, if an entry signal is active, an open position won't be closed, even when the profit target is met. Is this true? 
(Because I forgot to set this config item, my trade was open at 6%, even it should have been closed at 2% profit).
Since you never implement a config entry without sense, the meaning of ignore_roi_if_entry_signal may be slightly different to my description.
I look forward to your explanation.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
that's pretty much exactly what it does.
well the idea is to "save fees", essentially.

If your bot shows "roi reached" - but it also still has a entry signal open (which effectively means "i expect this pair to go in the right direction") - then the ROI entry can be skipped - as it would exit - and (immediately / at the next candle) reenter again.
one premise here is also that ROI is something pretty much static (2% above the entry) - while the market may be doing "whatever" - and other parts of the strategy may know more.

now obviously this can be wrong (as every entry signal can be wrong) - and the whole flag is originating from a time where freqtrade had no protections (which would prevent the immediate re-entry eventually).

it's a flag, which defaults to false - so it's inactive unless you explicitly enable it.

**Comment by myNextCoder** [comment]
I see, in many cases the flag might be a good idea. (In my case, the flag was true in the strategy, so it needs to be present in the config).

**Comment by xmatthias** [comment]
well if it's present in the strategy, then clearly you (or the strategy author) thought it's necessary (it's explicitly configured).

The freqtrade default will be false - obviously things that ARE set in the strategy will be respected.
