### ISSUE TITLE
Base5ActionRLEnv some incorrect code comments ?

### ISSUE THREAD

**Issue by escanoro** [freqtrade/freqtrade#8415]
## Describe your environment

  * Operating system: N/A
  * Python Version: N/A
  * CCXT version: N/A
  * Freqtrade Version: N/A but i'm discussing the Develop Branch of Freqtrade
  

## Describe the problem:

In [Base5ActionRLEnv ](https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/freqai/RL/Base5ActionRLEnv.py), the step definition seems to have incorrect comments.

In the **is_tradesignal(action)** condition, for example, it's stating that : 
```
"""
 Action: Neutral, position: Long ->  Close Long
 Action: Neutral, position: Short -> Close Short
"""
```

But the **is_tradesignal** function returns '**False**' for these cases:

![image](https://user-images.githubusercontent.com/128816061/228513158-2738a5ad-5a4b-407f-90d9-a3a166d1804c.png)

In addition, we don't see any action like described in the comments:

![image](https://user-images.githubusercontent.com/128816061/228537384-bc7ac9f8-a796-4cae-af59-48ed55bbe571.png)

If my understating is correct, maybe i can update these comments and send a PR.

Regards,
Escanor

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

Please note that we have quite clear instructions how to get the freqtrade version.
Filling it out with "NA" (or the docker digest) do NOT count as filled out - and "latest develop" is a moving target - which is also considered as not filled out.

---

I'm not entirely sure why it would be incorrect to allow entering a long, short or do nothing (neutral) if you're currently neutral.

You'll notice that the whole condition is negated (`not` right after the return statement).

If this would be wrong, then no trade would EVER be entered (you start from a neutral position).

**Comment by robcaulk** [comment]
I think you are right, the docstring is incorrect. Please feel free to make a PR with a corrected docstring. You could even improve the rest of the docstring while you are there.

**Comment by escanoro** [comment]
> Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
> We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.
> 
> Filling out the template helps reduce our workload, and we greatly appreciate that.
> 
> Please note that we have quite clear instructions how to get the freqtrade version.
> Filling it out with "NA" (or the docker digest) do NOT count as filled out - and "latest develop" is a moving target - which is also considered as not filled out.
> 
> ---
> 
> I'm not entirely sure why it would be incorrect to allow entering a long, short or do nothing (neutral) if you're currently neutral.
> 
> You'll notice that the whole condition is negated (`not` right after the return statement).
> 
> If this would be wrong, then no trade would EVER be entered (you start from a neutral position).  

I have used the template, but since i was discussing the content of a file (pointing the develop branch )other information are not relevant.

I was indeed discussing the doc strings

**Comment by escanoro** [comment]
> I think you are right, the docstring is incorrect. Please feel free to make a PR with a corrected docstring. You could even improve the rest of the docstring while you are there. 

Okay, will try to improve the docstring and PR it.

Regards,
Escanor
