### ISSUE TITLE
Can we hyperopt rewards when working with FreqAI RL ?

### ISSUE THREAD

**Issue by escanoro** [freqtrade/freqtrade#8416]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: N/A
  * CCXT version:  N/A
  * Freqtrade Version: freqtradeorg/freqtrade:stable (Current stable version as of 03 29 2023)
  
## Your question

The calculate rewards function goal is to reward and/or punish the agent by providing positive or negative reward points.
So the reward base itself (In the below example: -2, 25, -1 ...) have a huge importance on the model performance: What seems important to us (human) by providing greater reward or punishment, may not be true.

Example:

```
def calculate_reward(self, action: int) -> float:
            """
            An example reward function. This is the one function that users will likely
            wish to inject their own creativity into.
            :param action: int = The action made by the agent for the current candle.
            :return:
            float = the reward to give to the agent for current step (used for optimization
                of weights in NN)
            """
            # first, penalize if the action is not valid
            if not self._is_valid(action):
                self.tensorboard_log("invalid", category="actions")
                return -2

            pnl = self.get_unrealized_profit()
            factor = 100.

            # reward agent for entering trades
            if (action == Actions.Long_enter.value
                    and self._position == Positions.Neutral):
                ²
            if (action == Actions.Short_enter.value
                    and self._position == Positions.Neutral):
                return 25
            # discourage agent from not entering trades
            if action == Actions.Neutral.value and self._position == Positions.Neutral:
                return -1
```

Can we hyperpot values like : 

- return -2
- return 25
- return -1
- factor = 100

Something like
 Factor = IntParameter(low=80, high=120, default=100, space='??', optimize=True, load=True)

Regards,
Escanor

**Comment by froggleston** [comment]
If you have a lot of questions, you might find it useful to ask in the FreqAI discord instead of raising issues here: https://discord.gg/ptRZHGbUhg

**Comment by robcaulk** [comment]
Hello,

No, the FT hyperopt module is not compatible with the RL reward.

That said, there are people who have used tools like optuna to hyperopt these kinds of hyperparameters. Details about that can be found more in the discord that frog links to there.

Cheers,

Robert
