### ISSUE TITLE
Config external_message_consumer.remove_entry_exit_signals does not work as described in the doc

### ISSUE THREAD

**Issue by matthieu-hm** [freqtrade/freqtrade#8419]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version: 3.10.6
  * CCXT version: 2.9.12
  * Freqtrade Version: freqtrade 2023.3.dev-d808dd49e
  
## Describe the problem:

In the documentation "**Producer/Consumer mode**", the config `remove_entry_exit_signals` is described as:

> Remove signal columns from the dataframe (set them to 0) on dataframe receipt.
> Defaults to `10`.
> **Datatype**: Integer - in seconds.

That's great because it means that we can set a Time-To-Live for signals using this parameter.

In reality, this parameter is only a boolean (default: False).

### Steps to reproduce:

`config.json`
```js
{
  // ...
  "external_message_consumer": {
    "enabled": true,
    "producers": [
      // ...
    ],
    "remove_entry_exit_signals": 240 // 4min (timeframe: 5m)
  },
}
```
  
### Observed Results:

2 possibilities: 
 * Error in the documentation
 * Bug in the code

Personally, I would prefer to have `remove_entry_exit_signals` as a TTL parameter. This would provide security in case my consumer gets disconnected for too long. I would not want it to initiate a trade that the producer started hours or days ago.

**Comment by xmatthias** [comment]
Will update the documentation to account for this. This is not a TTL - but a boolean flag - which either removes the data - or won't.

You don't really need a TTL approach here either.
You'll merge the upstream dataframe to the "local" dataframe.
if the upstream dataframe has not been updated in X hours - you'll have missing candles at the end, so unless you use some ffilling (you really shouldn't in this case) - no "late" entries will be happening after the current candle is completed.

Now if you're on a higher timeframe - (this is still irrelevant btw) - you'll only get one dataframe per pair transferred per candle - so it's either uptodate (and freqtrade can take a trade off of it) - or it can't.

If you're afraid of late entries in general (independent of producer/consumer mode) - then maybe [`ignore_buying_expired_candle_after`](https://www.freqtrade.io/en/latest/configuration/#ignoring-expired-candles) is for you - which will ignore entries after X seconds into a candle (don't set this too low - if your strategy takes 10s to analyze all pairs, and this is at 5 - you'll not get ANY entries).
