### ISSUE TITLE
HitBTC Exchanger v2 working correctly on live trading, should be added to the list of supported exchangers.

### ISSUE THREAD

**Issue by ZeroCool940711** [freqtrade/freqtrade#842]
Hi there, I was testing freqtrade with HitBTC and I found that the v2 ("name": "hitbtc2") works perfectly, the v1 ("name": "hitbtc") do not work as freqtrade get stuck downloading the data for the pairs and some time start throwing error 404 or 503, I recommend you to add "HitBTC V2" to the list of supported exchangers on the readme.md next to Bittrex and Binance. I tested hitbtc v2 on windows 10 using bash on windows which is technically an ubuntu vm machine and it was running perfectly, the python version was python 3.6, I would like to recommend you to add support for python 2.7 as many people still use it and it will increase the amount of people that will use freqtrade. Have a good day and thanks for this awesome bot.

**Comment by xmatthias** [comment]
Did you run HitBTC2 wet (not in backtest or dry-mode)? any issues / exceptions / errors in the logs?

I don't think adding python 2.7 makes sense (and i doubt you'll find someone willing to work on it) - it is deprecated and will be stop being supported in less than 2 years (December 2020) [source](https://www.python.org/dev/peps/pep-0373/#id2).
several major projects (django, pandas, ..) did drop support for python 2.7 already (or intend on doing so by the end of this year) - mainly as it is a real pain to support both versions.

Especially [pandas](https://pandas.pydata.org/pandas-docs/stable/install.html#plan-for-dropping-python-2-7) is important for this project - as freqtrade relies heavily on pandas - so we would spend time on something which would break within 6 months.

**Comment by xmatthias** [comment]
did the bot also make sells on HitBTC2? (so a full buy / check / sell cycle is complete)? 

i'm the wrong person for hyperopt - but i'm sure others will jump in

**Comment by ZeroCool940711** [comment]
I will leave it running for a few hours and see what happen, so far it bought but didn't sell, for what I see it bought too high, it may be problem with the strategy so its not something that cant be fixed, I see a lot this on the console tho.
2018-06-04 06:36:01,054 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again..
2018-06-04 06:36:05,569 - freqtrade.freqtradebot - INFO - Found no sell signals for whitelisted currencies. Trying again..

I will get some sleep and when i wake up I will start working on a good strategy and see if I can understand how everything work on freqtrade so I can give better feedback and see if I can do something myself, had the idea of creating a visual editor that cna be used to create strategies using blocks on a UI.

**Comment by xmatthias** [comment]
well - sells depend on the strategy / rate - not the bot / exchange - so that's fine i guess (even though bad for you if it bought too high).

Log messages as the one you see are absolutely normal - just means that ROI is not reached (probably course dropped after buying) ...
```
freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again..
```

sounds good to be honest

**Comment by vertti** [comment]
Thank you for the info on HitBTC, great to hear the bot is working.

As for Python 2, that will never happen. We use plenty of Python3 features in the bot and rely on libraries that also require it.

**Comment by ZeroCool940711** [comment]
Hi guys, I have an update for you regarding Hibtc2, I just woke up and saw that Freqtrade had successfully completed a buy and sell cycle, for one of the two currencies pair I have it using, so, its working correctly.

**Comment by ZeroCool940711** [comment]
Hey, I was testing the backtester on HitBTC and I found a problem there check #845 for more info.

**Comment by xmatthias** [comment]
i'll close this ticket for now, since #845  explains why hitbtc2 is not ready yet.

we'll keep #845 open to track progress on hitbtc2.
