### ISSUE TITLE
Are the strategies guaranteed to be profitable?

### ISSUE THREAD

**Issue by brijagstu7** [freqtrade/freqtrade#8425]
I only know from the docs that the strategies are generated by some machining learning algorithms, but there is no clue whether the best strategy is good enough. By the way I'm thinking of introducing this project into arbitrage theory.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

There are no guarantees to have a profitable strategy - and results based on historic data will never guarantee future success.
You can improve a strategy for a long time - but you'll not get any guarantees.

there's also a TON of variables at play (selected markets, general trend direction, ...) - so a strategy that won't work for one scenario, may very well work a month later on slightly different markets (or market conditions) or viceversa.

---

based on the nativity of this question, i do have to warn you to only trade with capital/money you can afford to lose.
there's no guarantees to trading, and trading (while it CAN be rewarding) is and will remain a high risk topic.
