### ISSUE TITLE
Hyperoptable parameters in custom loss function

### ISSUE THREAD

**Issue by yclai** [freqtrade/freqtrade#8428]
## Describe your environment

  * Operating system: ____
  * Python Version: 3.11 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: stable (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Greetings,

I was trying to create my own loss function, is there any way to obtain the current information of hyperopt-able parameters in the loss function? 

`def hyperopt_loss_function(results: DataFrame, trade_count: int,
                               min_date: datetime, max_date: datetime,
                               config: Config, processed: Dict[str, DataFrame],
                               backtest_stats: Dict[str, Any],
                               *args, **kwargs) -> float:`
                               
Seems like none of them allow me to obtain the hyperspace params of the current epoch. Appreciate if anyone can help, thanks!

**Comment by xmatthias** [comment]
You don't - but i'm also not sure why you'd need that.

A loss function should interpret the results the strategy generates - not the parameters used directly.

**Comment by yclai** [comment]
> You don't - but i'm also not sure why you'd need that.
> 
> A loss function should interpret the results the strategy generates - not the parameters used directly.

I have my risk reward ratio hyperopt-ed in my strategy, that is why I need it. I have found a way to obtain it in my custom loss function, that is by passing the value into dataframe and then refer it in the loss function using processed: Dict. Thanks for the swift reply anyway!! Good luck to everyone!
