### ISSUE TITLE
Whitelist with 0 pairs: [ ]

### ISSUE THREAD

**Issue by le8888e** [freqtrade/freqtrade#8430]
## Describe your environment

  * Operating system: Amazon Linux
  * Python Version: 3.9.16 (`python -V`)
  * CCXT version: 3.0.48 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.3 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi, I'm trying to run freqtrade on AWS EC2 and I'm on the stable branch. When the bot started to trade, it found empty whitelist even if I have defined pair_whitelist in config file.
![231680450007_ pic](https://user-images.githubusercontent.com/34771253/229363562-b428bcf6-2e21-414b-be52-d7815cf914bd.jpg)
![241680450258_ pic](https://user-images.githubusercontent.com/34771253/229363716-d80426ee-0509-46d0-b87d-b7a233751f03.jpg)

**Comment by xmatthias** [comment]
Futures pairs are named `base/quote:settle`, as is also [documented](https://www.freqtrade.io/en/latest/leverage/#pair-namings).

Your pairs are therefore invalid for futures markets - and correctly rejected from the pairlist.

I'd also STRONGLY recommend to read through the full documentation at least once - so you get familiar with how things work in general.
