### ISSUE TITLE
HitBTC2: Backtest downloading not working reliably - live suffering from outdated tickers

### ISSUE THREAD

**Issue by ZeroCool940711** [freqtrade/freqtrade#845]
## Step 2: Describe your environment

  * Python Version: python 3.6
  * Branch: Develop
  * Last Commit ID: 15fb81da92ebb258133a50a80201cccd1907493d
 
## Step 3: Describe the problem:

 When using the option --days freqtrade do not download or use the data from previous days and only uses the data from 2018-06-01 to the current day or only the data for the last 24 hours, because freqtrade do not download the data from previous days the option --timerange do not work either. This bug is happening on Hitbtv2. 

### Steps to reproduce:

  1. python3 scripts/download_backtest_data.py --exchange hitbtc2 --timeframes 1m --days 30
  2. python3.6 freqtrade/main.py backtesting --timerange=20180528-
  3. _____
  
### Observed Results:

  * What happened?
Freqtrade did not download the data from previous days so the backtesting started only for the last 24 hours and some times it could go back 3 or 4 days but not more than that.

  * What did you expect to happen?
I expected Freqtrade to download the data from the days I specified on the "--days" command and then the backtester would start normally from that day until today.

### Relevant code exceptions or logs:

  ```
2018-06-04 21:26:00,784 - freqtrade.configuration - INFO - Log level set to INFO
2018-06-04 21:26:00,785 - freqtrade.configuration - INFO - Using max_open_trades: 5 ...
2018-06-04 21:26:00,786 - freqtrade.configuration - INFO - Parameter --timerange detected: 20180528- ...
2018-06-04 21:26:00,786 - freqtrade.configuration - INFO - Using data folder: user_data/data/hitbtc2 ...
2018-06-04 21:26:00,786 - freqtrade.optimize.backtesting - INFO - Starting freqtrade in Backtesting mode
2018-06-04 21:26:00,787 - freqtrade.strategy.resolver - INFO - Using resolved strategy DefaultStrategy from '/home/zerocool/freqtrade/freqtrade/strategy'
2018-06-04 21:26:00,787 - freqtrade.strategy.resolver - INFO - Override strategy 'minimal_roi' with value in config file.
2018-06-04 21:26:00,787 - freqtrade.strategy.resolver - INFO - Override strategy 'ticker_interval' with value in config file: 1m.
2018-06-04 21:26:00,787 - freqtrade.exchange - INFO - Instance is running with dry_run enabled
2018-06-04 21:26:00,792 - freqtrade.exchange - INFO - Using Exchange "HitBTC v2"
2018-06-04 21:26:02,508 - freqtrade.optimize.backtesting - INFO - Using stake_currency: USDT ...
2018-06-04 21:26:02,508 - freqtrade.optimize.backtesting - INFO - Using stake_amount: 50 ...
2018-06-04 21:26:02,509 - freqtrade.optimize.backtesting - INFO - Using local backtesting data (using whitelist in given config) ...
2018-06-04 21:26:02,513 - freqtrade.optimize.backtesting - INFO - Ignoring max_open_trades (realistic_simulation not set) ...
2018-06-04 21:26:02,636 - freqtrade.optimize.backtesting - INFO - Measuring data from 2018-06-05T02:27:00+00:00 up to 2018-06-05T04:22:00+00:00 (0 days)..
2018-06-04 21:26:02,699 - freqtrade.optimize.backtesting - INFO -
==================================== BACKTESTING REPORT ====================================
| pair     |   buy count |   avg profit % |   total profit USDT |   avg duration |   profit |   loss |
|:---------|------------:|---------------:|--------------------:|---------------:|---------:|-------:|
| BTC/USDT |           0 |            nan |          0.00000000 |            nan |        0 |      0 |
| ETH/USDT |           0 |            nan |          0.00000000 |            nan |        0 |      0 |
| ZEC/USDT |           0 |            nan |          0.00000000 |            nan |        0 |      0 |
| TOTAL    |           0 |            nan |          0.00000000 |            nan |        0 |      0 |
  ```

I really hope this problem can be fixed as its the only problem Ive found with HitBTC, if this is fixed I think HitBTC can be added to the list of working exchangers, the live trading works perfectly and its making profit with the default strategy, tho im using different pairs than the one im trying to backtest xD

**Comment by creslinux** [comment]
Good Morning. 
download_backtest_data.py requires a pairs file to read to know what to download. 

I would suggest any the following

1)  running (without the download_backtest_data.py)
> python3.6 freqtrade/main.py backtesting --refresh-pairs-cached --timerange=20180528-
This will create user_data/hitbtc2 and download ticker files into there 

2) create the download directory and add a default pairs.json file here to be read. 
> mkdir user_data/data/hitbtc2 
     Add a default pairs.json file here for hitbtc
     edit user_data/data/hitbtc2/pairs.json and add the pairs youre interested in, as example format

> [
>     "ETH/BTC",
>     "BCH/BTC"
> ]
    then run 

> scripts/download_backtest_data.py --exchange hitbtc2 --timeframes 1m --days 30

3) or pass scripts/download_backtest_data.py a pairs file location to read at a runtime argument 
> /download_backtest_data.py --pairs-file "mypairsfile.json"

**Comment by ZeroCool940711** [comment]
Hey, thanks for the answer I do have a pairs.json file on the folder for hitbtc2 (user_data/data/hitbtc2/) it is downloading the data for a day and according to the console output it goes back to 2018/06/01 for data but that data is not been downloaded, none of the commands you mention worked for me, with all I get the same amount of data. My pairs.json file has these pairs, all of them present on hitbtc and all of them has data enought to get more than 1 or 2 days:

> [
>     "BANCA/USDT",
> 	"ETH/USDT",
> 	"BTC/USDT",
> 	"EJOY/USDT",
> 	"MTC/USDT",
> 	"XMR/USDT",
> 	"B2G/USDT",
> 	"ZEC/USDT",
> 	"DOGE/USDT"
> ]
>

**Comment by ZeroCool940711** [comment]
I noticed something that could be the problem, if you look at the logs you'll see that its trying to get the data from 2018-06-05T02:27:00+00:00 up to 2018-06-05T04:22:00+00:00, the date is just wrong, its one day ahead of the current date, the starting day should be 2018-06-04 and not 2018-06-05, somewhere the date is not been taken correctly and thats could be what is making the exchanger not give the right information, it cant give you the data for tomorrow as it doesnt have it so what it is probably doing is returning the latest data it has available which is the one for today.

**Comment by creslinux** [comment]
2018-06-05 is today yyyy/mm/dd UTC timezone 
Can you send first record from user_data/data/hitbtc/BANCA_BTC-1m.json 
It will look something like this
"[[1527552000000, 0.1244, 0.1259, 0.1244, 0.1259, 6.59830743]"

**Comment by creslinux** [comment]
also the last record too!

**Comment by creslinux** [comment]
Also, im curious, to rule out another area please try passing the stop argument as well as start, see if makes any difference. 

python3.6 freqtrade/main.py backtesting --refresh-pairs-cached --timerange=20180528-20180604

**Comment by ZeroCool940711** [comment]
@creslinux here is the [BANCA_USDT-1m.json](https://pastebin.com/cEx2A1NW) file on pastebin for easy reading, using your command I get the next output now.

> (.env) root@SandboxServer:/home/zerocool/freqtrade# python3.6 freqtrade/main.py backtesting --refresh-pairs-cached --timerange=20180528-20180604
> 2018-06-05 00:52:34,285 - freqtrade.configuration - INFO - Log level set to INFO
> 2018-06-05 00:52:34,286 - freqtrade.configuration - INFO - Using max_open_trades: 5 ...
> 2018-06-05 00:52:34,286 - freqtrade.configuration - INFO - Parameter --timerange detected: 20180528-20180604 ...
> 2018-06-05 00:52:34,286 - freqtrade.configuration - INFO - Using data folder: user_data/data/hitbtc2 ...
> 2018-06-05 00:52:34,286 - freqtrade.configuration - INFO - Parameter -r/--refresh-pairs-cached detected ...
> 2018-06-05 00:52:34,286 - freqtrade.optimize.backtesting - INFO - Starting freqtrade in Backtesting mode
> 2018-06-05 00:52:34,288 - freqtrade.strategy.resolver - INFO - Using resolved strategy DefaultStrategy from '/home/zerocool/freqtrade/freqtrade/strategy'
> 2018-06-05 00:52:34,288 - freqtrade.strategy.resolver - INFO - Override strategy 'minimal_roi' with value in config file.
> 2018-06-05 00:52:34,288 - freqtrade.strategy.resolver - INFO - Override strategy 'ticker_interval' with value in config file: 1m.
> 2018-06-05 00:52:34,288 - freqtrade.exchange - INFO - Instance is running with dry_run enabled
> 2018-06-05 00:52:34,293 - freqtrade.exchange - INFO - Using Exchange "HitBTC v2"
> 2018-06-05 00:52:36,012 - freqtrade.optimize.backtesting - INFO - Using stake_currency: USDT ...
> 2018-06-05 00:52:36,012 - freqtrade.optimize.backtesting - INFO - Using stake_amount: 50 ...
> 2018-06-05 00:52:36,012 - freqtrade.optimize.backtesting - INFO - Using local backtesting data (using whitelist in given config) ...
> 2018-06-05 00:52:36,017 - freqtrade.optimize - INFO - Download data for all pairs and store them in user_data/data/hitbtc2
> 2018-06-05 00:52:36,017 - freqtrade.optimize - INFO - Download the pair: "BANCA/USDT", Interval: 1m
> dumping json to "user_data/data/hitbtc2/BANCA_USDT-1m.json"
> 2018-06-05 00:52:38,989 - freqtrade.optimize - INFO - Download the pair: "DOGE/USDT", Interval: 1m
> dumping json to "user_data/data/hitbtc2/DOGE_USDT-1m.json"
> 2018-06-05 00:52:48,345 - freqtrade.optimize - WARNING - No data for pair: "BANCA/USDT", Interval: 1m. Use --refresh-pairs-cached to download the data
> 2018-06-05 00:52:48,345 - freqtrade.optimize - WARNING - No data for pair: "DOGE/USDT", Interval: 1m. Use --refresh-pairs-cached to download the data
> 2018-06-05 00:52:48,345 - freqtrade.optimize.backtesting - INFO - Ignoring max_open_trades (realistic_simulation not set) ...
> Traceback (most recent call last):
>   File "freqtrade/main.py", line 70, in <module>
>     main(sys.argv[1:])
>   File "freqtrade/main.py", line 31, in main
>     args.func(args)
>   File "/home/zerocool/freqtrade/freqtrade/optimize/backtesting.py", line 305, in start
>     backtesting.start()
>   File "/home/zerocool/freqtrade/freqtrade/optimize/backtesting.py", line 242, in start
>     min_date, max_date = self.get_timeframe(preprocessed)
>   File "/home/zerocool/freqtrade/freqtrade/optimize/backtesting.py", line 61, in get_timeframe
>     return min(timeframe, key=operator.itemgetter(0))[0], \
> ValueError: min() arg is an empty sequence
>

**Comment by creslinux** [comment]
The JSON file only has data from :

> Monday, June 4, 2018 10:10:00 PM
> To
> June 5, 2018 5:56:00 AM

There are a few issues in that. But  first please run this to see if it works on the data you do have

`python3.6 freqtrade/main.py backtesting --refresh-pairs-cached --timerange=1528150200000-1528178160000`

**Comment by ZeroCool940711** [comment]
Nope, it didnt work, almost the same output as before.

> (.env) root@SandboxServer:/home/zerocool/freqtrade# python3.6 freqtrade/main.py backtesting --refresh-pairs-cached --timerange=1528150200000-1528178160000
> 2018-06-05 01:32:53,354 - freqtrade.configuration - INFO - Log level set to INFO
> 2018-06-05 01:32:53,355 - freqtrade.configuration - INFO - Using max_open_trades: 5 ...
> 2018-06-05 01:32:53,355 - freqtrade.configuration - INFO - Parameter --timerange detected: 1528150200000-1528178160000 ...
> 2018-06-05 01:32:53,355 - freqtrade.configuration - INFO - Using data folder: user_data/data/hitbtc2 ...
> 2018-06-05 01:32:53,355 - freqtrade.configuration - INFO - Parameter -r/--refresh-pairs-cached detected ...
> 2018-06-05 01:32:53,356 - freqtrade.optimize.backtesting - INFO - Starting freqtrade in Backtesting mode
> 2018-06-05 01:32:53,357 - freqtrade.strategy.resolver - INFO - Using resolved strategy DefaultStrategy from '/home/zerocool/freqtrade/freqtrade/strategy'
> 2018-06-05 01:32:53,357 - freqtrade.strategy.resolver - INFO - Override strategy 'minimal_roi' with value in config file.
> 2018-06-05 01:32:53,357 - freqtrade.strategy.resolver - INFO - Override strategy 'ticker_interval' with value in config file: 1m.
> 2018-06-05 01:32:53,357 - freqtrade.exchange - INFO - Instance is running with dry_run enabled
> 2018-06-05 01:32:53,362 - freqtrade.exchange - INFO - Using Exchange "HitBTC v2"
> 2018-06-05 01:32:55,171 - freqtrade.optimize.backtesting - INFO - Using stake_currency: USDT ...
> 2018-06-05 01:32:55,171 - freqtrade.optimize.backtesting - INFO - Using stake_amount: 50 ...
> 2018-06-05 01:32:55,171 - freqtrade.optimize.backtesting - INFO - Using local backtesting data (using whitelist in given config) ...
> 2018-06-05 01:32:55,173 - freqtrade.optimize - INFO - Download data for all pairs and store them in user_data/data/hitbtc2
> 2018-06-05 01:32:55,174 - freqtrade.optimize - INFO - Download the pair: "BANCA/USDT", Interval: 1m
> dumping json to "user_data/data/hitbtc2/BANCA_USDT-1m.json"
> 2018-06-05 01:32:56,632 - freqtrade.optimize - INFO - Download the pair: "DOGE/USDT", Interval: 1m
> dumping json to "user_data/data/hitbtc2/DOGE_USDT-1m.json"
> 2018-06-05 01:32:58,160 - freqtrade.optimize - WARNING - No data for pair: "BANCA/USDT", Interval: 1m. Use --refresh-pairs-cached to download the data
> 2018-06-05 01:32:58,161 - freqtrade.optimize - WARNING - No data for pair: "DOGE/USDT", Interval: 1m. Use --refresh-pairs-cached to download the data
> 2018-06-05 01:32:58,161 - freqtrade.optimize.backtesting - INFO - Ignoring max_open_trades (realistic_simulation not set) ...
> Traceback (most recent call last):
>   File "freqtrade/main.py", line 70, in <module>
>     main(sys.argv[1:])
>   File "freqtrade/main.py", line 31, in main
>     args.func(args)
>   File "/home/zerocool/freqtrade/freqtrade/optimize/backtesting.py", line 305, in start
>     backtesting.start()
>   File "/home/zerocool/freqtrade/freqtrade/optimize/backtesting.py", line 242, in start
>     min_date, max_date = self.get_timeframe(preprocessed)
>   File "/home/zerocool/freqtrade/freqtrade/optimize/backtesting.py", line 61, in get_timeframe
>     return min(timeframe, key=operator.itemgetter(0))[0], \
> ValueError: min() arg is an empty sequence
>

**Comment by creslinux** [comment]
I'll build a conf and do some testing this side, see if i can dig in to it any further.

**Comment by yevgeny-z** [comment]
It's not bag. hitbtc provide only 100 last candels, not provide history data
See description on [ccxt](https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts) and [hitbtcv2 api](https://github.com/hitbtc-com/hitbtc-api/blob/master/APIv2.md#candles)

**Comment by ZeroCool940711** [comment]
@yevgeny-z there is a limit on how many candles you can get at once but on the same link you provide there is a workaround on how to bypass that limit, also the limit for hitbtc is not 100 but 1000 candles, here is what ccxt says about that and how to bypass that problem.

> There's a limit on how far back in time your requests can go. Most of exchanges will not allow to query detailed candlestick history (like those for 1-minute and 5-minute timeframes) too far in the past. They usually keep a reasonable amount of most recent candles, like 1000 last candles for any timeframe is more than enough for most of needs. You can work around that limitation by continuously fetching (aka REST polling) latest OHLCVs and storing them in a CSV file or in a database.

**Comment by xmatthias** [comment]
the download-scripts apply this fix too - making multiple requests to get all candles (if available) for the specified time period

**Comment by xmatthias** [comment]
honestly - the times seem very ... randomly distributed (some pairs 10 minutes, some pairs 79 minutes) ... 

knowing that you use HITBtc (2) - i would assume that their api gives old results ... this is known to happen with bittrex too sometimes ...

**Comment by ZeroCool940711** [comment]
I think the problem is not with the API or the exchanger I think the problem is with the way the bot is getting the data, the reason im saying this is because I had another bot before and it was working correctly, right now I just tested that other bot with hitbtc to see if it was getting the data correctly and it was working without any problem, I went and tested another bot too with a different strategy and structure and that one was also working without any problem and placing orders correctly, I think the bot is requesting the data and receiving it but somewhere the data is lost or the wrong one is read and that may be whats giving troubles, a few commit back freqtrade was placing orders with a few minutes in between but it was placing orders on hitbtc, now it has placed almost no orders for quite some time and the few orders that it placed gave only losses selling lower than the last bough price.

**Comment by xmatthias** [comment]
### point a:
@creslinux  the command you specified above is syntactically wrong
`python3.6 freqtrade/main.py backtesting --refresh-pairs-cached --timerange=1528150200000-1528178160000` does not get parsed as a date - but
`python3.6 freqtrade/main.py backtesting --refresh-pairs-cached --timerange=1528150200-1528178160` will (the regex specifies 10 long ... so microsecond epoch times won't work.

--timerange=20180601-20180605 however does seem to work (also for hitbtc).

### point b:
downloading 1m frames from hitbtc2 does not seem to go back farther ~ 2 days (i can currently get data starting with 2018-06-04T02:30:00.
it's nothing we can do in this case - apart from catching the exception which occurs due to an empty dataframe and returning a "sensible" error ... 

if you specify a range which the exchange does not have data for ... sorry .

this can be easily tested via ccxt:
``` python
import ccxt
import arrow
ct = ccxt.hitbtc2()
# general initialisation
mark = ct.loadMarkets()
symbol = "BANCA/USDT"
# shift today - 6 days...
date = arrow.now().shift(days=-6)
ticker = ct.fetch_ohlcv(symbol, timeframe='1m', limit=1000, since=int(date.datetime.timestamp()) * 1000)

cols = ['date', 'open', 'high', 'low', 'close', 'volume']
frame = DataFrame(ticker, columns=cols)

frame['date'] = to_datetime(frame['date'],
                                    unit='ms',
                                    utc=True,
                                    infer_datetime_format=True)
frame.sort_values('date', inplace=True)

print(frame.head(1))
print(frame.tail(1))
```

**Comment by xmatthias** [comment]
after analyzing this a bit further, i think this is a bug in [ccxt](https://github.com/ccxt/ccxt/issues/2937)

trying to move the "since" parameter around does not give the desired result.

If the same thing is tested against binance (and a pair supported there) i can archive a sliding window (which is what we implement on get).

i don't think it makes more sense to dig into hitbtc2 any further until this bug is fixed.

**Comment by shusso** [comment]
feel free to re open if it doesn't work after the ccxt upstream fix
