### ISSUE TITLE
Stop loss in live trading

### ISSUE THREAD

**Issue by armindev1383** [freqtrade/freqtrade#8450]
All my closed live trades have roi and exit_signal written for closing reason.
I think that the robot does not use the stoploss and trailing stop that I created.
Is there a part in the config or strategy file that caused this or is there no problem?

**Comment by stash86** [comment]
As much as we would like to be a mind reader, sadly we are not capable of such thing. Upload your strategy file and config file.

**Comment by xmatthias** [comment]
On top of the above:


Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

**Comment by xmatthias** [comment]
Closing this, as we didn't further feedback on a question that's not saying anything, and contains 0 information.
