### ISSUE TITLE
Invalid parameter file format questions

### ISSUE THREAD

**Issue by bukowa** [freqtrade/freqtrade#8452]
## Describe your environment
  * Python Version: Python 3.11.0rc2
  * CCXT version: 3.0.51
  * Freqtrade Version: freqtrade 2023.3
  *
## Your question
When running backtesting after running hyperopt with `"max_open_trades": -1` in `config.json`:
```
2023-04-04 18:54:22,659 - freqtrade.strategy.hyper - WARNING - Invalid parameter file format.
```
```json
{
  "strategy_name": "NewStrategy",
  "params": {
    "roi": {
      "0": 10.0
    },
    "stoploss": {
      "stoploss": -0.239
    },
    "max_open_trades": {
      "max_open_trades": Infinity
    },
````
    
Two questions:
1. I think that populating max_open_trades with `Infinity` value is a bug. This is causing the error above.
2. I think that exception should be thrown, not a warning when parameter file is in incorrect format i am right?

**Comment by xmatthias** [comment]
not really - it's intentionally warning - maybe the file you got there is not a parameter file, but something different - not intended to be loaded.
that'd make it a random failure i'd think.

now in this particular case, it should clearly load the file - which it doesn't - but can be fixed quite easily.
