### ISSUE TITLE
Getting an unclosed trade during backtesting

### ISSUE THREAD

**Issue by yclai** [freqtrade/freqtrade#8455]
## Describe your environment

  * Operating system: Window 10
  * Python Version: 3.8.11 (`python -V`)
  * CCXT version: 2.0.96 (`pip freeze | grep ccxt`)
  * Freqtrade Version: stable (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I designed my own custom_exit function to exit with loss based on recent low/high and exit with profit when it reach a certain risk reward ratio (might be useful for anyone who want to exit trades the same way), code is as below:

```
def custom_exit(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, **kwargs):
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        current_candle = dataframe.iloc[-1].squeeze()
        trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
        # Look up trade candle.
        trade_candle = dataframe.loc[dataframe['date'] <= trade_date]

        # trade_candle may be empty for trades that just opened as it is still incomplete.
        if trade.is_short == 1:
            maxdf = trade_candle['high'].rolling(self.rsishift.value).max()
            # print("maxdf")
            # print(maxdf)

            if len(trade_candle)!=0:
                stoplossPrice = (maxdf.iloc[-1])*(1+self.lossbuffer.value)
                loseratio = stoplossPrice - trade.open_rate
                if current_rate > stoplossPrice:
                    return "short_failed"
                if current_rate < (trade.open_rate - (loseratio*self.RRR.value)):
                    return "short_success"
                #stoplossPrice = trade.open_rate*1.015


        if trade.is_short == 0:
            mindf = trade_candle['low'].rolling(self.rsishift.value).min()
            # print("mindf")
            # print(mindf)

            if len(trade_candle)!=0:
                stoplossPrice = (mindf.iloc[-1])*(1-self.lossbuffer.value)
                loseratio = trade.open_rate - stoplossPrice
                if current_rate < stoplossPrice:
                    return "long_failed"
                if current_rate > (trade.open_rate + (loseratio*self.RRR.value)):
                    return "long_success"
```

The problem is when I run backtesting, I get an unclosed trade for 2-3 months and not sure what the problem is. The custom_exit clearly stated when to exit the trade regardless of profit or loss.

```
`======================= MONTH BREAKDOWN ========================
|      Month |   Tot Profit USDT |   Wins |   Draws |   Losses |
|------------+-------------------+--------+---------+----------|
| 31/01/2022 |            -7.409 |      8 |       0 |       19 |
| 28/02/2022 |         -1189.12  |      6 |       0 |       22 |
| 31/03/2022 |           494.31  |     11 |       0 |       22 |
| 30/04/2022 |         -3446.26  |      6 |       0 |       29 |
| 31/05/2022 |         -2786.79  |      4 |       0 |       22 |
| 30/06/2022 |          2028.29  |     10 |       0 |       22 |
| 31/07/2022 |           281.848 |     10 |       0 |       26 |
| 31/08/2022 |          1008.38  |      9 |       0 |       23 |
| 30/09/2022 |          -986.69  |      7 |       0 |       20 |
| 31/10/2022 |          1987.73  |      9 |       0 |       16 |
| 30/11/2022 |          -557.06  |      6 |       0 |       16 |
| 31/12/2022 |         -1360.36  |      3 |       0 |       14 |
| 31/01/2023 |             0     |      0 |       0 |        0 |
| 28/02/2023 |             0     |      0 |       0 |        0 |
| 31/03/2023 |             0     |      0 |       0 |        0 |
| 30/04/2023 |         34654.8   |      1 |       0 |        0 |
================== SUMMARY METRICS ==================
| Metric                      | Value               |
|-----------------------------+---------------------|
| Backtesting from            | 2022-01-02 00:00:00 |
| Backtesting to              | 2023-04-05 09:40:00 |
| Max open trades             | 1                   |
|                             |                     |
| Total/Daily Avg Trades      | 341 / 0.74          |
| Starting balance            | 15000 USDT          |
| Final balance               | 45121.691 USDT      |
| Absolute profit             | 30121.691 USDT      |
| Total profit %              | 200.81%             |
| CAGR %                      | 140.53%             |
| Profit factor               | 1.56                |
| Trades per day              | 0.74                |
| Avg. daily profit %         | 0.44%               |
| Avg. stake amount           | 6773.475 USDT       |
| Total trade volume          | 2309754.907 USDT    |
|                             |                     |
| Long / Short                | 169 / 172           |
| Total profit Long %         | 196.25%             |
| Total profit Short %        | 4.57%               |
| Absolute profit Long        | 29436.836 USDT      |
| Absolute profit Short       | 684.855 USDT        |
|                             |                     |
| Best Pair                   | BTC/USDT 282.22%    |
| Worst Pair                  | BTC/USDT 282.22%    |
| Best trade                  | BTC/USDT 347.20%    |
| Worst trade                 | BTC/USDT -15.55%    |
| Best day                    | 34654.815 USDT      |
| Worst day                   | -943.445 USDT       |
| Days win/draw/lose          | 77 / 207 / 175      |
| Avg. Duration Winners       | 1 day, 7:05:00      |
| Avg. Duration Loser         | 4:27:00             |
| Rejected Entry signals      | 0                   |
| Entry/Exit Timeouts         | 0 / 0               |
|                             |                     |
| Min balance                 | 5850.759 USDT       |
| Max balance                 | 45121.691 USDT      |
| Max % of account underwater | 64.78%              |
| Absolute Drawdown (Account) | 64.78%              |
| Absolute Drawdown           | 10763.106 USDT      |
| Drawdown high               | 1613.865 USDT       |
| Drawdown low                | -9149.241 USDT      |
| Drawdown Start              | 2022-01-21 15:35:00 |
| Drawdown End                | 2022-06-10 09:20:00 |
| Market change               | -39.89%             |
=====================================================
`
```

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

The output doesn't really show that a particular trade is remaining open - so i'm not sure where you're reading this out from - it's not part of the output you posted.

> The custom_exit clearly stated when to exit the trade regardless of profit or loss.

This is not really how your custom_exit works - if a trade remains relatively static (doesn't win much, doesn't lose much) - you'll not be exiting.
If you're unlucky (or got a stable-coin in your pairlist) - then this is very easily possible.

**Comment by yclai** [comment]
> Please get used to filling out the issue template. Those who frequently omit the template may have their issues closed without comment. We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.
> 
> Filling out the template helps reduce our workload, and we greatly appreciate that.
> 
> The output doesn't really show that a particular trade is remaining open - so i'm not sure where you're reading this out from - it's not part of the output you posted.
> 
> > The custom_exit clearly stated when to exit the trade regardless of profit or loss.
> 
> This is not really how your custom_exit works - if a trade remains relatively static (doesn't win much, doesn't lose much) - you'll not be exiting. If you're unlucky (or got a stable-coin in your pairlist) - then this is very easily possible.

Sorry for skipping the template question, I just answered by editing my previous post. You can view the monthly breakdown to see that there is still a trade going on with very high profit because of the trade has been running for months.

I'll provide some extra info/logs to prove that, you can look at the left open trades report, the trade has been opened for 95days:
```
========================================================== BACKTESTING REPORT ===========================================================
|     Pair |   Entries |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
|----------+-----------+----------------+----------------+-------------------+----------------+----------------+-------------------------|
| BTC/USDT |       341 |           0.83 |         282.22 |         30121.691 |         200.81 |       11:28:00 |    90     0   251  26.4 |
|    TOTAL |       341 |           0.83 |         282.22 |         30121.691 |         200.81 |       11:28:00 |    90     0   251  26.4 |
=========================================================== ENTER TAG STATS ===========================================================
|   TAG |   Entries |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
|-------+-----------+----------------+----------------+-------------------+----------------+----------------+-------------------------|
| TOTAL |       341 |           0.83 |         282.22 |         30121.691 |         200.81 |       11:28:00 |    90     0   251  26.4 |
===================================================== EXIT REASON STATS =====================================================
|   Exit Reason |   Exits |   Win  Draws  Loss  Win% |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |
|---------------+---------+--------------------------+----------------+----------------+-------------------+----------------|
|   long_failed |     127 |      0     0   127     0 |          -3.28 |        -416.37 |          -28327.9 |        -416.37 |
|  short_failed |     124 |      0     0   124     0 |          -3.19 |        -395.19 |          -25544.5 |        -395.19 |
| short_success |      48 |     48     0     0   100 |           8.38 |         402.4  |           26229.4 |         402.4  |
|  long_success |      41 |     41     0     0   100 |           8.39 |         344.17 |           23109.9 |         344.17 |
|    force_exit |       1 |      1     0     0   100 |         347.2  |         347.2  |           34654.8 |         347.2  |
========================================================== LEFT OPEN TRADES REPORT ==========================================================
|     Pair |   Entries |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |      Avg Duration |   Win  Draw  Loss  Win% |
|----------+-----------+----------------+----------------+-------------------+----------------+-------------------+-------------------------|
| BTC/USDT |         1 |         347.20 |         347.20 |         34654.815 |         231.03 | 95 days, 15:40:00 |     1     0     0   100 |
|    TOTAL |         1 |         347.20 |         347.20 |         34654.815 |         231.03 | 95 days, 15:40:00 |     1     0     0   100 |
```

**Comment by xmatthias** [comment]
You might think you're always exiting - but you're not.

if `if len(trade_candle)!=0:` is 0 for whatever reason (quite possible in live - not sure how you'd get that in backtesting but i assume is possible) - then you'd no longer exit (assuming what's provided is your only exit condition).

**Comment by yclai** [comment]
> You might think you're always exiting - but you're not.
> 
> if `if len(trade_candle)!=0:` is 0 for whatever reason (quite possible in live - not sure how you'd get that in backtesting but i assume is possible) - then you'd no longer exit (assuming what's provided is your only exit condition).

Actually what is the reason that causes len(trade_candle) to be 0 during live? I am quite curious about this but can't figure it out. Does that means my strategy will probably not work in live trading?

**Comment by stash86** [comment]
Freqtrade only store a fixed number of candles (1000 if I'm not mistaken). So if your trade go past the 1000 candles, the bot won't be able to find that trade candle anymore.

Now, to debug the behavior on backtest, you can easily add print lines on the custom_exit, to see where the issues are

**Comment by yclai** [comment]
> Freqtrade only store a fixed number of candles (1000 if I'm not mistaken). So if your trade go past the 1000 candles, the bot won't be able to find that trade candle anymore.
> 
> Now, to debug the behavior on backtest, you can easily add print lines on the custom_exit, to see where the issues are

I did print out the error when len(trade_candle)==0, but can't figure out how to fix this. Now your answer is good enough for me to understand why that happened.

Is there any way I can increase the number of candles stored to any number higher than 1000?

**Comment by stash86** [comment]
Store the max and min values inside a dict variable. The downside is if your bot restarted for some reasons, those values are gone.

Personally, I would add additional exit logic that exit the trade once the trade go past x candles (let's say for example 900 candles). That gonna mean your strat still backtestable, no issue with bot restarting, and no issue with the loss of trade candle.

**Comment by stash86** [comment]
To answer your question, no you can't increase the limit without changing the source code

**Comment by yclai** [comment]
> To answer your question, no you can't increase the limit without changing the source code

Yea I am trying to ask if I can change it anywhere in the source code.

**Comment by xmatthias** [comment]
you can change the limit to 5x what the exchange provides (by using startup_candle_count).
it's 1000 for binance, but 300 for okx (each x5) - so while it's a higher limit - it's still a limit you could be hitting.

Depending on the exchange, it might also not be providing historic candles (e.g. kraken, but there's for sure others) - so even a source-code change wouldn't mean that you can't hit this scenario.
