### ISSUE TITLE
Is there a feature to exit a trade after certain minutes even if the trade is current at loss?

### ISSUE THREAD

**Issue by xingxing67** [freqtrade/freqtrade#8463]
Hi,

I know that there is Minimal_roi that could you force exit a trade after certain minutes when the trade is non-loosing, and I know that there is custom stoploss. 
But what I'm looking for is exit a trade after a certain amount of time (even if the trade is loosing). For example, I want to exit a trade after 180 mins even if the trade is currently at loss. 

Is there a feature like that? Or can someone give me a little hint how to develop a strategy that can do it?

Thank you

**Comment by stash86** [comment]
You can always set the roi to negative value, for example -1, so the trade wil exit if the profit > -100%

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

the following setting will have the bot exit any trade after 180 amount of minutes, ignoring it's state completely.

```
minimal_roi = {
    "180": -1
}
```

**Comment by 14790897** [comment]
useful information
