### ISSUE TITLE
Postgres backend caps string lengths for entry_tag and exit_tag, leading to table insertion errors

### ISSUE THREAD

**Issue by quant5** [freqtrade/freqtrade#8486]
## Describe your environment

  * Operating system: Ubuntu 20
  * Python Version: 3.10 (`python -V`)
  * CCXT version:  (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.2 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the problem:

If using Postgres as backend, many table columns are not long enough to support longer strings.
As one example, enter and exit tags are capped at 100 characters e.g.: https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/persistence/trade_model.py#L1266
There is no corresponding cap on the enter/exit tag length within IStrategy or any validation / checkers.

This leads to the following error when trying to write:
```
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(100)
```

### Steps to reproduce:

  1. Have freqtrade running with Postgres backend
  2. Write a strategy with a long enter_tag or exit_tag
  3. Attempt to insert a trade

Suggested solution is to have VARCHAR without string length limit for anything that can be entered by the user.

**Comment by xmatthias** [comment]
> Suggested solution is to have VARCHAR without string length limit for anything that can be entered by the user.

we'll not be using varchar columns without string limit. 
This can cause problems with other db systems - and is generally bad practice if you look at it from a database design perspective, and can in extreme cases lead to a DoS by filling up your database host's disk with unlimited character columns.

You should really just limit the length of your tags.
To me, this sounds like an artificially created issue (probably identified after looking at the created column) - which will have little to no real world implications.

What would be a real world tag (entry or exit) with over 100 characters that you'd ACTUALLY use in your strategy?

If any (unless we get a convincing real world example of this) - the "fix" for this will be either by truncating the column - or by simply documenting that tags shouldn't be longer than 100 characters.

**Comment by quant5** [comment]
Ok, understood. Could we at least push the limit to 255 instead of 100? I have tags that are very long due to an ensembling of many technicals. I want to know exactly which ones were triggered. For example, one tag is

![image](https://user-images.githubusercontent.com/4811862/231001644-555f123d-31dd-4f4f-bd57-5df974f49258.png)

Trying to write this into the db caused the entire system to crash, which is why I diagnosed and raised the issue. I would not have raised the issue otherwise.

**Comment by quant5** [comment]
I'd also note that the default persistence layer, sqlite, ignores length restrictions which may be why most freqtrade users have not come across this particular issue.

**Comment by xmatthias** [comment]
I've bumped the limit to 255 now, truncating tags that are longer.
the update will NOT trigger a database migration (it's an edge-case issue that nobody will really hit) - therefore either update the field lengths manually, or drop the table/database to let freqtrade recreate it correctly.

**Comment by quant5** [comment]
Thank you very much (I had done the former already on my instances).
