### ISSUE TITLE
Order Types

### ISSUE THREAD

**Issue by Arivadis** [freqtrade/freqtrade#8489]
* Operating system: Ubuntu
  * Python Version: 3.9
  * Freqtrade Version: last release
  

Hello,

I just want to make sure I am not missing something.
"
On futures, Binance supports both stop-limit as well as stop-market orders
"

And this 
"
The order_types configuration parameter maps actions (entry, exit, stoploss, emergency_exit, force_exit, force_entry) to order-types (market, limit, ...) as well as ...
"

Makes me think that Freqtrade supports stop or stop-limit entry orders(especially this dots (market, limit, ...)).

Does Freqtrade support any order tipe except for market, limit for entry position?

Thank You!

**Comment by xmatthias** [comment]
for entries, you can use limit or market orders.

The "binance futures" note refers exclusively to stop orders - where support (from an exchange perspective) is all over - with binance spot supporting only stop-limit orders, and futures supporting both types (other exchanges are similar ... or worse).

When stoploss on exchange is enabled - you can select the appropriate stop-type via "stoploss" order_types - by setting that to either market - or limit.
If stoploss is enabled, then this ordertype will be used directly (without the conditional / stoploss order).

**Comment by Arivadis** [comment]
Thank You!
