### ISSUE TITLE
stoploss_on_exchange is supported for Okx

### ISSUE THREAD

**Issue by superXR** [freqtrade/freqtrade#8492]
## Describe your environment

  * Operating system:Ubuntu 20.04.1 LTS
  * Python Version: Python 3.9.16
  * CCXT version: ccxt==3.0.37
  * Freqtrade Version: freqtrade 2023.3

## Describe the enhancement

**Now stoploss_on_exchange is not seem to be supported for okx in [FT](https://www.freqtrade.io/en/stable/stoploss/#stoploss_on_exchange-and-stoploss_on_exchange_limit_ratio:~:text=Stoploss%20on%20exchange,will%20not%20work).** 
But looks like OKX stop orders are implemented: https://github.com/ccxt/ccxt/pull/13440
So I hope this could be implemented in FT.Stoploss on exchange is supported for OKx in FT

**Comment by xmatthias** [comment]
Stoploss support for OKX was introduced in 2023.3, and should therefore be readily available to you.

I'm therefore not sure where you get the information from that okx would not support stoploss on exchange.

**Comment by superXR** [comment]
> Stoploss support for OKX was introduced in 2023.3, and should therefore be readily available to you.
> 
> I'm therefore not sure where you get the information from that okx would not support stoploss on exchange.

Sorry,I missed the Hightlight change in 2023.3, now I see it, thx! 
I got the information that okx would not support stoploss on exchange in [FT docs](https://www.freqtrade.io/en/stable/stoploss/#stoploss_on_exchange-and-stoploss_on_exchange_limit_ratio:~:text=Stoploss%20on%20exchange,will%20not%20work.) 
Before I noticed that okx was not mentioned in the [documentation](https://www.freqtrade.io/en/stable/stoploss/#stoploss_on_exchange-and-stoploss_on_exchange_limit_ratio:~:text=Stoploss%20on%20exchange,will%20not%20work.), so I thought okx didn't support it yet.
