### ISSUE TITLE
Dead link to TAlib official site on Manual installation part of freqtrade.io

### ISSUE THREAD

**Issue by aviavee** [freqtrade/freqtrade#8497]
[TA-Lib manual installation](https://www.freqtrade.io/en/stable/installation/#ta-lib-manual-installation)

**Official webpage: https://mrjbq7.github.io/ta-lib/install.html**

Github link above is dead, have not been able to locate site.

**Comment by xmatthias** [comment]
Great spot - fixed in develop (the correct link is https://ta-lib.github.io/ta-lib-python/).
