### ISSUE TITLE
When deploying project, I can't connect to localhost:$port

### ISSUE THREAD

**Issue by mpaya5** [freqtrade/freqtrade#8500]
I have read and searched my  issue in the documentation. This is my environment:

  * Operating system:  Ubuntu20.04
  * Python Version: python3.10.6
  * CCXT version:  3.0.37
  * Freqtrade Version: freqtrade 2023.4.dev
  

I have well configurated my firewall, this needs to be modify in my Hosting and is working cause I can make connections from my own machine to the server.

I have two bots running on my server, one running in localhost:8081 and the other one in localhost:8082.

I have a domain in my server: freqtrade.example.com, and is making a proxy_pass to frequi that is running in my localhost:3000.

If I go to my localhost:3000 I can easily connect my bots (8081 and 8082). But if I try to connect my bots in freqtrade.example.com I cannot make connections.

My config looks like this:

```
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8081,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "....",
        "ws_token": "...",
        "CORS_origins": ["IP_OF_MY_SERVER:3000", "https://freqtrade.examplecom"],
        "username": "...",
        "password": "..."
    },

```

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.


---

With the provided info, all we can do is guess - and the best assumption is that your CORS is missconfigured (even though you mention it's not - it's the most likely reason, assuming your firewall is somewhat ok).

it'll need to contain the exact url you navigate to (if your url runs on https://frequi.netlify.app - then `https://frequi.netlify.app` must be in your CORS setting).

**Comment by mpaya5** [comment]
Sorry for make a wrong commit. I have changed the issue. Take a look please

**Comment by xmatthias** [comment]
assuming `https://freqtrade.examplecom` is really `https://freqtrade.example.com` - then it would mean that you acccess frequi by going to `https://freqtrade.example.com` (EXACTLY this url, no different suburl).


your "listen_ip_address" is concerning - as 0.0.0.0 means it's listening on all interfaces - which means it might also be external facing (you don't seem to use docker, where this would be correct).
it's not necessarily a problem - but you need to be aware of it, and take other measures (like, prevent access via firewall).

Now assuming you go to `https://freqtrade.example.com` - and click the `login` button in freqUI - you'll insert `http://localhost:8081` - what's the error message you get when trying to login (a screenshot might work best)?

**Comment by mpaya5** [comment]
Yes, `https://freqtrade.examplecom` is really `https://freqtrade.example.com`.

It is no right to put "0.0.0.0" in my "listen_ip_address"? What should I do ?

I am using docker to run frequi.

When I click login and I insert `http://IP_OF_MY_SERVER:8081" I receive:

```
Login failed.
Please verify that the bot is running, the Bot API is enabled and the URL is reachable.
You can verify this by navigating to http://IP_OF_MY_SERVER:8081/api/v1/ping to make sure the bot API is reachable 
 Please also check your bot's CORS configuration: [Freqtrade CORS documentation](https://www.freqtrade.io/en/latest/rest-api/#cors)
```

Then, if I go to `http://IP_OF_MY_SERVER:8081/api/v1/ping` I receive: `{"status":"pong"}`

My NGINX configuration for `freqtrade.example.com`:

```
server {

        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";

        listen 80;
        listen [::]:80;

        server_name freqtrade.example.com;

        location / {
                # Do not allow connections from docker 1.5 and earlier
                # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
                if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
                        return 404;
                }

                proxy_pass                          http://localhost:3000;
                proxy_set_header  Host              $http_host;   # required for docker client's sake
                proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
                proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header  X-Forwarded-Proto $scheme;
                proxy_read_timeout                  900;
        }
        listen [::]:443 ssl http2;
        listen 443 ssl http2; # managed by Certbot

        ssl_certificate /etc/letsencrypt/live/freqtrade.example.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/freqtrade.example.com/privkey.pem; # managed by Certbot

        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot

        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    listen 80;
    server_name freqtrade.example.com www.freqtrade.example.com;
    return 301 https://freqtrade.example.com$request_uri;
}


```

**Comment by xmatthias** [comment]
well the error suggests CORS - which means the bot got "some" response - just not a proper one.

now on some platforms, chrome (on windows iirc) prevents CORS requests from https to http. 

You should be able to disable this (per page) in the page's security settings - though i've never had to do this myself.

In the end - running freqUI/freqtrade behind a reverse proxy is not a standard setup - so we assume you know how to work around such things.

Please try to run a default setup (without reverse proxy) - if you encounter problems there, that's something we can actually assist you with.
Due to bandwidth constraints - we can't however support more complex, custom scenarios - as there's too many variables in play in such a case.

**Comment by xmatthias** [comment]
What you can try however is to also proxy the API requests - that way, both frontend and client will use https - which should solve that browser constraint.

**Comment by mpaya5** [comment]
Sorry for my late answer, 

I decided to run frequi like the way is explained in [the repository](https://github.com/freqtrade/frequi).

You're right about the CORS Policy, if i check the console it shows this error: `Mixed Content: The page at 'https://freqtrade.example.com/login?redirect=/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:8081/api/v1/token/login'. This request has been blocked; the content must be served over HTTPS`

The problem of Proxying the API requests is to have so much bots running... I will need to create so much subdomains.

**Comment by xmatthias** [comment]
> I decided to run frequi like the way is explained in [the repository](https://github.com/freqtrade/frequi).

That's really the develop setup - you can also just navigate to one of the existing bots and use that.
Irrelevant on HOW you run it - keep in mind that we do recommend to not expose the freqtrade API directly over the internet - but it should be additionally (on top of the logins) protected at the network level from unauthorized access.
