### ISSUE TITLE
freqtrader help for a noob

### ISSUE THREAD

**Issue by neelam25a** [freqtrade/freqtrade#8504]
I am trying to run and use freqtrade on windows 10 computers with 64 bit processor and i keep getting the following error: Building wheels for collected packages: py-find-1st
  Building wheel for py-find-1st (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for py-find-1st (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\utils_find_1st
      copying utils_find_1st\__init__.py -> build\lib.win-amd64-cpython-38\utils_find_1st
      running build_ext
      building 'find_1st' extension
      C:\Users\fatis\AppData\Local\Temp\pip-build-env-2umslael\overlay\Lib\site-packages\setuptools\dist.py:788: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for py-find-1st
Failed to build py-find-1st
ERROR: Could not build wheels for py-find-1st, which is required to install pyproject.toml-based projects

(freqtrade-env) C:\Users\fatis\freqtrade>
any help to get going and running would be greatly appreciated

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

We also have the [windows troubleshooting guide](https://www.freqtrade.io/en/stable/windows_installation/#error-during-installation-on-windows) - which does cover exactly this error, including the solutions for it.
