### ISSUE TITLE
Hyperopt Parameters

### ISSUE THREAD

**Issue by Arivadis** [freqtrade/freqtrade#8513]
* Operating system: ubuntu 22.04
  * Python Version: 3.9
  * Freqtrade Version: 2023.3
  
Hello!
Hope You are doing fine!

I need a literacy campaign regarding Hyperopt and dynamic number of hyperopt parameters.
This (https://github.com/freqtrade/freqtrade-strategies/blob/main/user_data/hyperopts/GodStraHo.py) is the old interface version of hyperopt.

And part of code:
```
@staticmethod
    def indicator_space() -> List[Dimension]:
        """
        Define your Hyperopt space for searching buy strategy parameters.
        """
        gene = list()

        for i in range(DNA_SIZE):
            gene.append(Categorical(GodGenes, name=f'buy-indicator-{i}'))
            gene.append(Categorical(GodGenes, name=f'buy-cross-{i}'))
            gene.append(Integer(-1, 101, name=f'buy-int-{i}'))
            gene.append(Real(-1.1, 1.1, name=f'buy-real-{i}'))
            # Operations
            # CA: Crossed Above, CB: Crossed Below,
            # I: Integer, R: Real, D: Disabled
            gene.append(Categorical(["D", ">", "<", "=", "CA", "CB",
                                     ">I", "=I", "<I", ">R", "=R", "<R"], name=f'buy-oper-{i}'))
        return gene
```
        
makes me think it could be multiple not predefined parameters for optimizing depended on loop and DNA_SIZE = 1 value. Not sure if this code works with DNA > 1 and works the right way - does not matter.

For actual interface version parameters must be predefined like buy_/sell...

The question is - Is it possible to have such flexible number of parameters in actual version?

Lets say we have something like this:
buy_N = IntParam(1, 3, def=2, space="buy)
and the loop above (like in old version) creates parameters for optimizing, lets say in range 2(2 parameters used). The next iteration for 1 parameter, the next 3 parameters.
So i could use different N of parameters.

For now I see this working this way:
We have to predefine maximal number of parameters that could be used in hyperopt and use only part of them if buy_N less than maximal of range value.
But this case all other parameters that not used in strategy on current epoch and do not effect the result - symply make hyperopt look for what is not.

Is it possible to implement this in another way without pre-defining the parameters in advance?

Thanks for any thoughts

**Comment by xmatthias** [comment]
I'd be careful with strategies of this author. they're known to often use forward-looking indicators (sometimes in a quite hidden way).
I do however think that you're just taking this as an example - not the actual strategy...


you can use [dynamic parameters](https://www.freqtrade.io/en/stable/advanced-hyperopt/#dynamic-parameters)  - but the syntax is now slightly different.
The result must still be deterministic (running the strategy twice without changing parameters must yield the same result) - but there's nothing that would prevent this method from working per se.

The only caveat is that you can't really depend the count of parameters on top of another parameter (you can, but it'll not change dynamically) - as the optimized parameters are only loaded once - and the definition of parameters MUST take place beforehand.

**Comment by Arivadis** [comment]
Thank You for answer - that was what i wanted!

Have a nice day!
