### ISSUE TITLE
Having a stake amount higher than wallet content using leverage

### ISSUE THREAD

**Issue by Axel-CH** [freqtrade/freqtrade#8519]
## Current situation
Currently with the bot we have the possibility to set a custom leverage, then a custom stake amount.
It is great but the stake amount is still limited to the available capital in the wallet, this configuration is preventing the advanced user to take full advantage of the leverage principle to have access to more capital than available in his wallet in one position.
So the current benefit of leverage is limited to borrowing money to trade by spreading between multiple trades and within the limit of wallet capital.

## Describe the enhancement
Ability to combine custom stake amount and leverage to be able to have a stake amount higher than wallet size.
To do that It could be required to call "strategy.custom_stake_amount" before "strategy.leverage" in order to let the user choose the correct leverage according to the target stake amount.

Note that obviously using more capital than available on the wallet without proper risk management is a good way to be quickly liquidated, so proper warning and documentation will be required.

**Comment by xmatthias** [comment]
While we're talking about dry-run (i assume) - i'm not entirely sure how you think this would work in real live - and doing a dry-run that isn't possible in live is rather pointless.

Exchanges do require us to have the capital available for the liquidation - so assuming a wallet of 10$ (to keep numbers small) - i can do 50x - and enter a trade of 10$ * 50x  - or 500$ (so i can buy 500 coins for a price of 1$).
Once i'm in this trade (no matter if it's at 50x or 5x) - the exchange will NOT allow me to enter another trade - as the 10$ i have in my wallet are already "tied up".

Available balance will decrease (now the below screenshot is for a 10$ subaccount (created for this demonstration), with a 5x order open on ETH).

![image](https://user-images.githubusercontent.com/5024695/232673691-b1ff1a87-0cea-463e-b1e4-eb7ad5d3d939.png)

we can clearly see that the "available balance" decrased to 1$ (ETH has rather odd "steps" on bybit).
The exchange will NOT allow me to enter another trade with this same 10$ as collateral. I can use the 1.6$ i still have in my account - but the remaining 8$ are tied up - and can't be used for a BTC trade.


This is simply how isolated futures work (at least in my experience across the exchanges we support) - and it's the only type of futures freqtrade supports at this moment.
If you can point me to a documentation page for isolated futures on an exchange where your approach is supported - i can sure have a look at it - but based on my knowledge of exchange mechanics - your logic would not make sense for the modes we support at this moment.

While supporting cross-futures would be nice - the actual mechanics behind that are not as simple as "allow to use the same capital more than once" - and it's not something i'm currently working on.

**Comment by Axel-CH** [comment]
I'm 100% agreed with the explanation you gave about how future work and I was aware of that. The part that maybe I'm misunderstanding is this one:

> Exchanges do require us to have the capital available for the liquidation - so assuming a wallet of 10$ (to keep numbers small) - i can do 50x - and enter a trade of 10$ * 50x - or 500$ (so i can buy 500 coins for a price of 1$).

From what I've tested if I try to do that on freqtrade the retained stake amount will be 10$ instead of 500$

Your example is actually the expected behavior, and what I aim for. but while testing on dryrun , with a custom stake amount even for entering only in one trade the function "wallet.validate_stake_amount" is capping the position stake to the max available capital.

**Comment by Axel-CH** [comment]
I'm double checking my files versions to see if there is no issue here

**Comment by xmatthias** [comment]
> Your example is actually the expected behavior, and what I aim for. but while testing on dryrun , with a custom stake amount even for entering only in one trade the function "wallet.validate_stake_amount" is capping the position stake to the max available capital.

Then i've got no idea what you're talking about 😆 
that's how it's supposed to work - and it's how it does seem to work in my tests (i do quite some dry-run trades while testing stuff...).

maybe you can then describe it as "this is what i'm seeing / experiencing - this is WHERE i'm seeing this behavior" - in a "bug-report" kinda fashion?

the above is stated as feature request - but apparently it's none - so you seem to encounter some unexpected behavior ... 
i'd also ask you to verify this with an unmodified version (stable or develop will both work fine) - we can't really support modified versions - as we don't know what problems custom changes may have introduced.

**Comment by Axel-CH** [comment]
What I will do:
-Create a clean develop test environment
-Reproduce the context that lead to the issue in a unit test
-If the issue is confirmed create a PR to work on a fix

**Comment by xmatthias** [comment]
> -If the issue is confirmed create a PR to work on a fix

or at least, describe the actual problem and what you observed ;)

**Comment by Axel-CH** [comment]
So I wrote a simple integration test to validate the bug:

```
def test_trade_stake_amount_higher_than_avlb_capital(default_conf_usdt, ticker_usdt, fee, mocker) -> None:

    default_conf_usdt['max_open_trades'] = 1
    default_conf_usdt['trading_mode'] = 'futures'
    default_conf_usdt['margin_mode'] = 'isolated'
    default_conf_usdt['stake_amount'] = 125
    default_conf_usdt['dry_run_wallet'] = 10 # TEST is passing only if this is set over 500

    freqtrade = get_patched_freqtradebot(mocker, default_conf_usdt)

    mocker.patch.multiple(
        EXMS,
        fetch_ticker=ticker_usdt,
        get_fee=fee,
        amount_to_precision=lambda s, x, y: y,
        price_to_precision=lambda s, x, y: y,
    )
    mocker.patch(f'{EXMS}._dry_is_price_crossed', return_value=False)
    mocker.patch(f"{EXMS}.get_max_leverage", return_value=70)
    mocker.patch(f"{EXMS}.get_funding_fees", return_value=0)
    mocker.patch(f"{EXMS}.get_maintenance_ratio_and_amt", return_value=(0, 0))

    leverage = 55
    custom_stake_amount = 500

    patch_get_signal(freqtrade)
    freqtrade.strategy.custom_stake_amount = MagicMock(return_value=custom_stake_amount) 
    freqtrade.strategy.leverage = MagicMock(return_value=leverage)


    # WE Should be able to enter position
    # as custom_stake_amount < post_leverage_available_amount
    
    # SHOULD be able to take a position of 500 USDT with 10 USDT available capital with 55 leverage
    freqtrade.enter_positions()

    assert len(Trade.get_trades().all()) == 1 # can't make a trade, test to fix

    trade: Trade = Trade.get_trades().first()

    assert trade.leverage == leverage
    assert trade.stake_amount == custom_stake_amount
```

**Could you confirm that this is a bug?**

**Comment by pnmice** [comment]
I have the same problem. How I know, Margin Calls. I don't have logs right now. My static stake per trade: 150 USDT with DCA 5 around total stake (8.923 USDT, 8.923 USD)
First CELR is ok
Second HOOK is weird with Total: (187.219 USDT, 187.219 USD)
Third CELR DCA with huge amount Total: (187.257 USDT, 187.257 USD)

<img width="387" alt="Screen Shot 2023-04-18 at 9 02 45 PM" src="https://user-images.githubusercontent.com/8248571/232963992-0e5625d9-037c-4a1d-af3b-dd5c5b0bbf36.png">

**Comment by xmatthias** [comment]
All i can confirm based on the above is that your test makes no sense / doesn't correspond to how stake_amount works.

the return value of `custom_stake_amount` will be `stake_amount` - which corresponds to "own capital" or "collateral" - so your test is trying to open a position of 500$ * 55x  = 27500$ - on an account with 10$.

This will fail - and will fail on any exchange i know - therefore the test confirms that this part (respect available balance with leverage) is working (but it's not what you tried to assert).

While your asserts at the end (`stake_amount == custom_stake_amount`) seem to be aware of this (amount would be `stake_amount * leverage * open_price`) - the overall test is not - and therefore misaligned.

A correct test here might use a custom_stake_amount of 5$ - and attempt to open a 2nd position - but from a (manual) test through the UI, this seems to work just fine.

Maybe this is something where the documentation could be improved - but for now - i don't see a bug (at least not based on the things shown above).

**Comment by Axel-CH** [comment]
Now I see the problem, If the stake_amount mean collateral (or position
cost), which variable determine the position size?
From my understanding
position_size = collateral * leverage


What I understood is that stake_amount mean position size, not collateral.
The collateral is automatically determined by the exchange with your
leverage and target position size.

Correct me if I'm wrong

**Comment by Axel-CH** [comment]
> the return value of `custom_stake_amount` will be `stake_amount` - which corresponds to "own capital" or "collateral" - so your test is trying to open a position of 500$ * 55x = 27500$ - on an account with 10$.

This is not true as I'm getting this warning explaining why test test failed

![Screenshot from 2023-04-19 07-28-27](https://user-images.githubusercontent.com/7593404/233061404-016c68f6-480f-4b85-bbe4-54fc91656c7c.png)

As you can see the bot is not trying to open a 27500$ position, but a 500$ one.

That test should work as post leverage available capital is `10 * 55 = 550 USDT`
The collateral associated with this position should be equal to
` (target_position_size / post_leverage_available_capital) * wallet`
`(500 / 550) * 10 = 9.09 USDT`
Than mean 9.09 USDT form 10 is collateralized for the position, and of course it is not possible to open the same position with the 0.89 USDT left in wallet

**Comment by xmatthias** [comment]
> As you can see the bot is not trying to open a 27500$ position, but a 500$ one.

well no not really - stake-amount is 500$ for this message (which is what you had in the test) - the position size would be 500 * 55x - which is not displayed (and really, irrelevant for this message).
The message (assuming it's from the above test) is correct - and simply says "you have a balance of 9.9$ - but you tried to use 500$ of these - which i disallowed".
Leverage is not really relevant for this.

As a user / strategy - you never really deal with the actual position size (27_000$) - and it's not something you define explicitly (you can use it, obviously - but what the strategy RETURNS must be the collateral, NOT the expected position size.

> position_size = collateral * leverage

This is correct (roughly) - and is a calculation freqtrade does under the hood.

**Comment by Axel-CH** [comment]
Ok I see, I saw where the real position size amount is set, in "execute_entry" with 
`amount = (stake_amount / enter_limit_requested) * leverage`
I will do live tests and I let you know if I'm able to have a position size higher than wallet content.

**Comment by Axel-CH** [comment]
Did the test and it is working as expected, thanks @xmatthias for the clarification
