### ISSUE TITLE
杠杆的倍率是否可以增加到15-20%，我们来验证一下。

### ISSUE THREAD

**Issue by zhaoxiang-com** [freqtrade/freqtrade#8522]
所以我写了一个简单的集成测试来验证这个错误：

def test_trade_stake_amount_higher_than_avlb_capital(default_conf_usdt, ticker_usdt, fee, mocker) -> None:

    default_conf_usdt['max_open_trades'] = 1
    default_conf_usdt['trading_mode'] = 'futures'
    default_conf_usdt['margin_mode'] = 'isolated'
    default_conf_usdt['stake_amount'] = 125
    default_conf_usdt['dry_run_wallet'] = 10 # TEST is passing only if this is set over 500

    freqtrade = get_patched_freqtradebot(mocker, default_conf_usdt)

    mocker.patch.multiple(
        EXMS,
        fetch_ticker=ticker_usdt,
        get_fee=fee,
        amount_to_precision=lambda s, x, y: y,
        price_to_precision=lambda s, x, y: y,
    )
    mocker.patch(f'{EXMS}._dry_is_price_crossed', return_value=False)
    mocker.patch(f"{EXMS}.get_max_leverage", return_value=70)
    mocker.patch(f"{EXMS}.get_funding_fees", return_value=0)
    mocker.patch(f"{EXMS}.get_maintenance_ratio_and_amt", return_value=(0, 0))

    leverage = 55
    custom_stake_amount = 500

    patch_get_signal(freqtrade)
    freqtrade.strategy.custom_stake_amount = MagicMock(return_value=custom_stake_amount) 
    freqtrade.strategy.leverage = MagicMock(return_value=leverage)

    # WE Should be able to enter position
    # as custom_stake_amount < post_leverage_available_amount
    
    # SHOULD be able to take a position of 500 USDT with 10 USDT available capital with 55 leverage
    freqtrade.enter_positions()

    assert len(Trade.get_trades().all()) == 1 # can't make a trade, test to fix

    trade: Trade = Trade.get_trades().first()

    assert trade.leverage == leverage
    assert trade.stake_amount == custom_stake_amount

**Comment by stash86** [comment]
English please

**Comment by xmatthias** [comment]
If you think this is important, please resubmit it in english, and include a question or description.

We'll not be using translators, while trying to guess what you're trying to tell us.
