### ISSUE TITLE
How to set the position size in Freqtrade?

### ISSUE THREAD

**Issue by t5862755** [freqtrade/freqtrade#8528]
## Describe your environment

  * Operating system:  Windows
  * Python Version: 3.9
  * Freqtrade Version: freqtrade docker-2023.4.dev-8dbe6b1c

  
## Your question

I just would like to ask where can I find the argument or setting about position size. I can't find that neither in function of "populate_entry_trend", nor the parameter in class "SampleStrategy". 

I want to backtest my strategy which need to adjust the size of position. For example, if I want to open two position, first position need 20% of my total assets, and second position need 25% of my total assets, what can I do?

**Comment by xmatthias** [comment]
Please consult the [documentation](https://www.freqtrade.io/) for very basic questions.

what you're looking for is the [`custom_stake_amount` callback](https://www.freqtrade.io/en/stable/strategy-callbacks/#stake-size-management) - where you can return whatever you'd like as position size.
