### ISSUE TITLE
pyup-bot and coveralls not working anymore since repository move

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#853]
## Describe the problem:

* Coveralls check fails with "Couldn't find a repository matching this job." error.
* pyup-bot does not update libraries anymore

### Observed Results:

* Noticed the missing coveralls last night while waiting for travis to complete to check code coverage.
* Noticed no new PR's from pyup-bot since we moved to the organization 

### Most likely problem

either permissions on the new repository, or the links need to be adjusted in these external services

- [x] fix pyup-bot
- [x] fix coveralls

### Relevant code exceptions or logs:

coveralls error from one of the last builds on Travis:
  ```
The command "pytest --cov=freqtrade --cov-config=.coveragerc freqtrade/tests/" exited with 0.
cache.2
store build cache
0.00s
2.00snothing changed, not updating cache
after_success
1.29s$ coveralls
Submitting coverage to coveralls.io...
Coverage submitted!
Couldn't find a repository matching this job.
'url'
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coveralls/cli.py", line 75, in main
    log.info(result['url'])
KeyError: 'url'

  ```

**Comment by vertti** [comment]
I have added the new repo to coveralls now.

**Comment by vertti** [comment]
![coveralls](https://user-images.githubusercontent.com/557751/41021877-9eb926cc-6970-11e8-8774-d875c8aa9560.jpg)

coveralls works now.

**Comment by gcarq** [comment]
I've added pyup to the new repo. Right now it is configured to create one PR which contains all update per day. I will open a PR to exclude networkx in the config for now.

**Comment by vertti** [comment]
There was 4 updates incoming in the initial PR #862 but as that was not merged we didn't get subsequent PR's. Is it broken or just slow to make the next ones?

**Comment by gcarq** [comment]
@vertti I think it will take up to 24hrs before we get the next PR

**Comment by xmatthias** [comment]
pyup works too (see #867).

i did like the previous configuration more ... with one PR per updated dependency ...

**Comment by gcarq** [comment]
@xmatthias I have still mixed feelings. I also like the one PR per dependency more, but ccxt bumps so many versions it got already very noise in the old repo. Maybe it makes sense to lower the schedule a bit, to half a day or hourly.

**Comment by xmatthias** [comment]
can it do daily (but one PR per dependency)?

**Comment by gcarq** [comment]
No unfortunately not, the schedule is still a beta feature, maybe they will add it in the future

**Comment by xmatthias** [comment]
then i'd leave it as is for now
