### ISSUE TITLE
Estimated Value and Profit percentage calculation is wierd when assets already exist in spot wallet

### ISSUE THREAD

**Issue by BurningSpy** [freqtrade/freqtrade#8532]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.9.7
  * CCXT version: 3.0.43 
  * Freqtrade Version: freqtrade docker-2023.4.dev-19e112f3
  

## Describe the problem:

Hi, 
So yesterday I first time started a bot on live binance. 
In my Telegram I can see when I checked the "/balance" right after startup, since I already had some coins like BAT and UFT lying around, it would see 211 BUSD as "Starting capital" and then at the end of the message added the other assets together for the estimated value of ~320. 

So far so good, but after the first trade was done and it made 1.8 BUSD in that trade from a 1.2% profit trade, it then took the Starting capital BUSD of 211 and compared that to the new estimated value, showing an astounding 51.98% profit. 
Which doesn't make sense. 

Wouldn't it be better for this scenario to use the estimated value at the start as the starting capital, if that is what we are comparing future values with?

I mean i'd love to have 52% profit, but i'd prefer that to be a real number :D 

### Steps to reproduce:

  1. Start bot on live with different coins already in wallet
  2. ask for balance
  3. wait for one trade
  4. ask for balance again
  
### Observed Results:

Wrong profit percentage

### Relevant code exceptions or logs

-

**Comment by xmatthias** [comment]
Nice spot - will have a look :+1:
