### ISSUE TITLE
Multiple pair

### ISSUE THREAD

**Issue by onthetunnel** [freqtrade/freqtrade#854]
Hello can i know freqtrade can auto monitoring multiple btc pair on one strategy ? if can do , can anyone teach me how to setting/config , Thanks You!

**Comment by xmatthias** [comment]
yes, you can.

best have a look at the config example - it defines a whiltelist of ~10 pairs which it monitors.

https://github.com/freqtrade/freqtrade/blob/fb49d706d04501479aff8bc3935d216c8c7743af/config.json.example#L16-L27

**Comment by onthetunnel** [comment]
xmatthias Thanks You for teaching me ! i try add other coin on it , Thanks!
