### ISSUE TITLE
Opening transactions at different points than in the past

### ISSUE THREAD

**Issue by bit-storm** [freqtrade/freqtrade#8540]
Operating system: linux ubuntu 20
Python Version: 3.8
CCXT version: 2.5.12
Freqtrade Version: 2022.12

Hello, thank you for your good library.
I have a problem that has made all my trades lose.
When the robot is in live run form, it opens trades at points that appear to be wrong.
I have seen this case a lot and to make sure I ran the robot on live mode for a while and memorized all its entry points, then I deleted its database and ran it again in live mode. When I checked the chart of the previous entry points, the robot did not enter the trade in any of the points.
How can I fix this problem? Or what reasons can cause this problem?

**Comment by stash86** [comment]
Fix your entry logics? Bot enter a trade based of your logics, so if you think the entries are bad, that means your entry logics are bad.

**Comment by bit-storm** [comment]
> Fix your entry logics? Bot enter a trade based of your logics, so if you think the entries are bad, that means your entry logics are bad.

I don't expect the bot to do magic and come in at a point that goes against my logic.
I have a specific and absolute condition to enter.
My problem is that when the robot is in the form of a live run, it enters the trade at points that do not exist in the past after the re-run or in the backtest.
Of course, this can sometimes happen due to the rapid changes of candles, but I am sure that this is not the reason for this issue.

**Comment by xmatthias** [comment]
You should carefully review the log (when was the actual order placed? when was it filled)?
most likely, you're having issues with unfilled orders / late fills. you should check both your order type, pricing, as well as the timeout you're using (should ideally be < candle length to avoid very late entries based on outdated signals).

If you see entries / order placements (with a timeout < candle length), then your strategy is almost certainly making one of the [common strategy mistakes](https://www.freqtrade.io/en/stable/strategy-customization/#common-mistakes-when-developing-strategies) - which means that your signals behave differently if they get more more (future) data.

**Comment by bit-storm** [comment]
> You should carefully review the log (when was the actual order placed? when was it filled)? most likely, you're having issues with unfilled orders / late fills. you should check both your order type, pricing, as well as the timeout you're using (should ideally be < candle length to avoid very late entries based on outdated signals).
> 
> If you see entries / order placements (with a timeout < candle length), then your strategy is almost certainly making one of the [common strategy mistakes](https://www.freqtrade.io/en/stable/strategy-customization/#common-mistakes-when-developing-strategies) - which means that your signals behave differently if they get more more (future) data.

According to your statement, I found the reason for this problem in the following way: I had to use qtpylib.cross instead of > and < in several conditions.
With the previous method of entering the trade, a range was considered, not a point, and with this, the problem seems to be solved, although I still need to check the results to be sure.
