### ISSUE TITLE
how to handle df['date'] during backtesting?

### ISSUE THREAD

**Issue by thunderwin** [freqtrade/freqtrade#8551]
## Your question

I noted that there is a saying from DOC

` To avoid problems and unexpected differences between Backtesting and dry/live modes, please be aware that during backtesting the full time interval is passed to the populate_*() methods at once. It is therefore best to use vectorized operations (across the whole dataframe, not loops) and avoid index referencing (df.iloc[-1]), but instead use df.shift() to get to the previous candle.
`

but my order only executes during my personal time range.

that is why I am doing this.  I write a function "doWhat" to determine LONG or SHORT base on the ticker's timestamp. but seems 
not to be working on backtesting.  how should I do it...

I have tried `dataframe.shift(0)["date"]`  `dataframe["date"].shift()` `dataframe['date']`. but they all return me a series rather than timeValue..  
```

   dataframe.loc[
            (
                 (self.doWhat(dataframe.shift()["date"]) == 'long')
            ),
            "enter_long",
        ] = 1
```

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

the [dataframe freqtrade provides](https://www.freqtrade.io/en/stable/strategy-customization/#dataframe) is really just a regular pandas dataframe. 
If you expect your workings to be quick - you'll want to vectorize your operations (so they apply to all rows in the dataframe at once).

If that's not possible, then you will want to loop through the dataframe, or use something like `.apply()` (which also really just loops).
Best refer to the pandas documentation for details on how to implement that for your usecase (though you'll definitely want to attempt a vectorized approach first).

**Comment by thunderwin** [comment]
hi but why `dataframe["date"]` not return me an time during backtesing..

**Comment by xmatthias** [comment]
`dataframe.shift()["date"]` (or `dataframe["date"]`) refers to a whole column (all dates in the dataframe).

it will return you every single row in the dataframe (either shifted, or "as is").
As mentioned above - please familiarize yourself with how pandas dataframes work.

**Comment by thunderwin** [comment]
with due respect.  but I using dateframe["date"] at  dataframe.loc.

```
 dataframe.loc[
        (
            (dataframe['date']  = what ? )
           & (dataframe['volume'] > 0)  # Make sure Volume is not 0
        )
```

if dataframe['volume'] return int.. why dataframe['date'] return a series..  

it;s not pandas dataframes problem for my understanding.. 

sorry If I'm wrong

**Comment by xmatthias** [comment]
you're wrong.

`dataframe['date']` returns a series, just like `dataframe['volume']` does.
the comparison works because `dataframe['volume']` is a series of type float - for which pandas implements comparison operators.

the same will work for `dataframe['date']` - but that's a series of type `pd.TimeStamp` - which will have different comparisons (but will still work, given the right hand type is correct).

We have documentation on how the [freqtrade dataframe looks like](https://www.freqtrade.io/en/stable/strategy-customization/#dataframe) - and for more detailed "how to compare pandas series" information, please refer to the pandas documentation.

**Comment by thunderwin** [comment]
thank you, you are my hero,  I would just use apply()
