### ISSUE TITLE
okx stoploss order dont have the key:"stopLossPrice" in dry-run

### ISSUE THREAD

**Issue by superXR** [freqtrade/freqtrade#8555]
## Describe your environment

  * Operating system: linux
  * Python Version: Python 3.9.16
  * CCXT version: ccxt==3.0.75
  * Freqtrade Version: freqtrade 2023.5.dev-1df01a263
  
## Your question

Dry-run on okx. I set 'stoploss_on_exchange': True, 'stoploss_on_exchange_interval': 60. But I find FT bot update the stoploss order every minute. Although the stoploss price did not change.I find the stoploss order that dont have the key "stopLossPrice" by debugging.The stoploss order have "stopPrice",but the default stop_price_param is "stopLossPrice".
![image](https://user-images.githubusercontent.com/57396498/234168156-397f6e97-fb6a-4235-bf96-520124baef51.png)
![image](https://user-images.githubusercontent.com/57396498/234168260-57b71d7f-bda3-4fe7-b2a1-66e12207c919.png)
Could you tell me what is the reason for this? Is there "stopLossPrice" in the stoploss order in okx live?

**Comment by xmatthias** [comment]
Nice spot - will be fixed shortly.
