### ISSUE TITLE
API Url for FreqUI Login

### ISSUE THREAD

**Issue by dkuci99** [freqtrade/freqtrade#8556]
Environment:
  * Freqtrade Version (Docker): freqtrade 2023.3
  
## Unable to get the API Url working for login into the FreqUI

I'm trying to get the localhost UI to set up the bot account and details, I have the bot working and its details are entered in my `user_data` but it's not setting up the account stating that the URL doesn't show a bot API.

I'm using `localhost:8080` for the API Url. Is this the right URL, I looked through the documentation about FreqUI but didn't see anything helping in how to setup a login correctly.

**Comment by xmatthias** [comment]
this is explicitly covered in the [docker documentation](https://www.freqtrade.io/en/stable/docker_quickstart/#accessing-the-ui).

Generic API / UI setup is in it's dedicated [documentation section](https://www.freqtrade.io/en/stable/rest-api/)
