### ISSUE TITLE
How to prevent opening "intra-candle" positions?

### ISSUE THREAD

**Issue by sebastianmacias** [freqtrade/freqtrade#8558]
## Describe your environment

  * Operating system: MacOs
  * Python Version: 3.10.10
  * CCXT version: ccxt==3.0.37
  * Freqtrade Version: freqtrade 2023.3
  
## Your question

I have a strategy that employs a 30-minute timeframe, with a maximum of 6 open trades and the setting "process_only_new_candles" enabled. Under this configuration, a new position will open at 1:36 if the "enter_long" or "enter_short" criteria are still met, following the closure of a previous position at 1:36.

However, in some cases, this approach may prove suboptimal, as market price may have shifted unfavorably in the interim. I have consulted related issues such as #4078 and #2423, but remain uncertain as to the most effective approach for incorporating these considerations into my strategy.

**Comment by xmatthias** [comment]
you can [ignore expired candles](https://www.freqtrade.io/en/stable/configuration/#ignoring-expired-candles) - which in your case, you could set to 5m - so all entries after 5 minutes into a candle will be ignored.

**Comment by sebastianmacias** [comment]
I appreciate it
