### ISSUE TITLE
Get the close/open value of candle, where last (MFI value was 100)

### ISSUE THREAD

**Issue by ghalibbajwa** [freqtrade/freqtrade#8559]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.8
  * CCXT version:  3.0.59
  * Freqtrade Version: freqtrade 2023.4.dev-501a290f8 | python installation
  
## Your question
I am trying to achieve the strategy defined in [this blog](https://tradingstrategyguides.com/day-trading-crypto/).

Here's a summary of the strategy.

- set MFI length to 3.
- check if MFI == 100
- ignore the first and second time MFI ==100
- on third MFI == 100, check if the close of previous  MFI == 100 candle is on the same level as the upper level of the current MFI == 100
- Close the trade after 1 hour 

I have successfully achieved the following in my freqtrade strategy:

- check if MFI == 100
- open trade if MFI == 100

I am facing problems trying to achieve the following:

- Check if already 3 MFI == 100 condition is met
- Get close/open of the last MFI == 100
- Match the upper level on the current MFI == 100 candle with the last MFI == 100 candle.

Here is the Code I have implemented:

```
class AaAAa(IStrategy):


   stoploss=-0.275
    # Define the indicators and parameters
    minimal_roi = {
        "0": 0.03
    }


    timeframe = "5m"

    mfi_period = 3
    buy_mfi = 100
    sell_mfi = 0
    buy_rsi = 30

    # Define the indicators to be used
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['mfi'] = ta.MFI(dataframe, self.mfi_period)
  
        self.MFI = list(dataframe['mfi'])

        return dataframe

    # Define the buy and sell signals
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        # Wait for the third MFI reading above 100
        dataframe.loc[
            (
                (dataframe['mfi'].shift(1) < self.buy_mfi) &
                (dataframe['mfi'].shift(2) < self.buy_mfi) &
                (dataframe['mfi'] == self.buy_mfi) 
                
            ),
            'buy'] = 1

        # Check if the subsequent candle is bullish
        dataframe.loc[
            (
                (dataframe['close'].shift(-1) > dataframe['open'].shift(-1)) &
                (dataframe['buy'] == 1)
            ),
            'buy'] = 1
        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        # # Sell when MFI falls below sell_mfi
        # dataframe.loc[
        #     (
        #         (dataframe['mfi'].shift(1) > self.sell_mfi) &
        #         (dataframe['mfi'] <= self.sell_mfi)
        #     ),
        #     'sell'] = 1

        return dataframe
    
    def custom_sell(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, **kwargs):
        # Get the datetime of the trade entry
        entry_time = trade.open_date_utc
        
        # Calculate the time difference between the trade entry and current time
        time_difference = current_time - entry_time
        
        # If the time difference is more than 1 hour, return True to sell the trade
        if time_difference >= timedelta(minutes=30) :
            return 'dontfuckaround'
     

```

here is a backtest result for 1 day:
![Screenshot 2023-04-26 221247](https://user-images.githubusercontent.com/81489058/234652244-7f811e42-1159-4586-a437-8c9f88da073e.png)

**Comment by xmatthias** [comment]
> `self.MFI = list(dataframe['mfi'])`

don't do that - just ... don't. The strategy is a global object (shared between pairs) - so you'll overwrite that over and over again - and can't really rely on it's content. apart from that, you also don't need that...

You also seem to be writing an outdated strategy format - which shouldn't be used for new strategies.
While it's still supported for now, it should be considered deprecated - and for new work, it's clearly not recommended.
 best check our docs on the uptodate format (or use the new template  you get with `freqtrade new-strategy`).

---

You can probably do something around this:

``` python
# You want crosses - not when it's exactly 100
dataframe['mfi_cross'] = qtpylib.crossed_above(dataframe['mfi'], self.buy_mfi)

# you can then rolling count this - i'm now using 24 candles (assuming 1h candles, that's 24 hours), not sure what the actual value should be
dataframe['crosses'] = dataframe.rolling(24)['mfi_cross'].cumsum()

# signal 
# ...
(dataframe['crosses'] >= 3)
# ... 
```

Now i'm not sure if cumsum or sum is correct - but plotting the column should reveal this pretty quickly.

---

i'm not sure i understand your last 2 points - and i don't intend to read some random blog article to get what you mean.

**Comment by ghalibbajwa** [comment]
> > `self.MFI = list(dataframe['mfi'])`
> 
> don't do that - just ... don't. The strategy is a global object (shared between pairs) - so you'll overwrite that over and over again - and can't really rely on it's content. apart from that, you also don't need that...
> 
> You also seem to be writing an outdated strategy format - which shouldn't be used for new strategies. While it's still supported for now, it should be considered deprecated - and for new work, it's clearly not recommended. best check our docs on the uptodate format (or use the new template you get with `freqtrade new-strategy`).
> 
> You can probably do something around this:
> 
> ```python
> # You want crosses - not when it's exactly 100
> dataframe['mfi_cross'] = qtpylib.crossed_above(dataframe['mfi'], self.buy_mfi)
> 
> # you can then rolling count this - i'm now using 24 candles (assuming 1h candles, that's 24 hours), not sure what the actual value should be
> dataframe['crosses'] = dataframe.rolling(24)['mfi_cross'].cumsum()
> 
> # signal 
> # ...
> (dataframe['crosses'] >= 3)
> # ... 
> ```
> 
> Now i'm not sure if cumsum or sum is correct - but plotting the column should reveal this pretty quickly.
> 
> i'm not sure i understand your last 2 points - and i don't intend to read some random blog article to get what you mean.

Thank you for the reply, I'll remove the unnecessary code and update the strategy with the current freqtrade docs. 
About the last two points, here is a diagram, if it helps:

![Screenshot 2023-04-26 225918](https://user-images.githubusercontent.com/81489058/234663189-46e4b28f-9ce3-452f-b1e4-52b4e74253fe.png)

**Comment by xmatthias** [comment]
i guess the .rolling() approach can work for this too - assuming you can just do a rolling max on high (or open/close?) to get the next top.

that's what it looks like from the screenshot anyway.
