### ISSUE TITLE
table status takes too long

### ISSUE THREAD

**Issue by jblestang** [freqtrade/freqtrade#856]
## Step 1: Have you search for this issue before posting it?

The issue  https://github.com/freqtrade/freqtrade/issues/278 is back, the caching mechanism that was introduced in https://github.com/freqtrade/freqtrade/pull/293 has been removed when migrating to CCXT

## Step 2: Describe your environment

  * Python Version: 3.6
  * Branch: Develop

**Comment by xmatthias** [comment]
noticed it getting slower as well - but didn't know it was faster before ... will have a look prolly tonight

**Comment by jblestang** [comment]
No problem, I saw the refresh parameter was still present ... never have thought the cache had been removed (the cached version is only used from RPC). 
The same is true for the profit command also that will benefit from reverting this deletion.

**Comment by gcarq** [comment]
Should be fixed on `develop`
