### ISSUE TITLE
Freqtrade does not support isolated futures on Bybit

### ISSUE THREAD

**Issue by bit-storm** [freqtrade/freqtrade#8579]
Operating system: linux ubuntu 20
Python Version: 3.8
CCXT version: 2.5.12
Freqtrade Version: 2022.12

error : 
freqtrade.exceptions.OperationalException: Freqtrade does not support isolated futures on Bybit

What is the reason for this error? I used this exchange without any problems for this type of transactions

**Comment by stash86** [comment]
Update your freqtrade

**Comment by xmatthias** [comment]
Freqtrade added support for bybit futures only this year - so a 6 month old version will not have support for this exchange enabled yet.
