### ISSUE TITLE
Ichimoku and RSI strategy

### ISSUE THREAD

**Issue by onthetunnel** [freqtrade/freqtrade#858]
Hello can someone implement ichimoku combine rsi or ichimoku combine SAR strat for long term trading please .. Thanks You !

**Comment by glonlas** [comment]
Hi,

For getting help, you have to provide a very detailed strategy workflow.

What indicator are needed, how they work.
What is the strategy to buy and the strategy to sell.

In other words describe in detail the help you are looking for.

**Comment by vertti** [comment]
I'm sorry, I don't think this is the service/tool you are looking for. You are welcome to join our chat to learn more but no one will program the bot for you and it takes considerable time and effort to learn to use the bot effectively. If you are not interested in doing that then you need to find a paid service or a commercial product.
