### ISSUE TITLE
Multibot setup - Please verify that the bot is running, the Bot API is enabled and the URL is reachable

### ISSUE THREAD

**Issue by IgnacioGoldman** [freqtrade/freqtrade#8581]
## Environment

  * Operating system: Ubuntu 22.04.1
  * Python Version: Python 3.10.6 (`python -V`)
  * Freqtrade Version: 2023.1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Problem

Multibot setup is not working. 

*freqtrade1 config.json*
```
"api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "SomeSecretKey",
        "username": "myuser",
        "password": "mypwd"
    },
```

*freqtrade2 config.json*
```
"api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8081,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "SomeSecretKey",
        "CORS_origins": ["http://<public-ip-aws-instance>:80", "http://<public-ip-aws-instance>:8080", "http://0.0.0.0:8080", "http://localhost:8080", "http://localhost:8080"]
        "username": "testuser",
        "password": "testpwd"
    },
```

*docker-compose config.json*
```
services:
  freqtrade1:
    ...
    ports:
      - "0.0.0.0:80:8080"
    ...
  freqtrade2:
    ...  
    ports:
      - "0.0.0.0:81:8081"
    ....
```

I'm able to access the first instance, but not the one with the CORS configured. I've tried with:
```
Bot Name: freqtrade2
API url: http://<public-ip-aws-instance>:8081 (tried also with http://<public-ip-aws-instance>)
Username: testuser
Password: testpwd
```

Error
```
Login failed.
Please verify that the bot is running, the Bot API is enabled and the URL is reachable.
You can verify this by navigating to http://<public-ip-aws-instance>:8081/api/v1/ping to make sure the bot API is reachable 
 Please also check your bot's CORS configuration: [Freqtrade CORS documentation](https://www.freqtrade.io/en/latest/rest-api/#cors)
```

Really appreciate your help :)

**Comment by xmatthias** [comment]
pretty detailed issue :+1: 

Unfortunately, I think the most important question in this case is left unanswered.
What's the actual URL (also obfuscate as you did above if public IP) you're navigating to in your browser when logging in?

As the [CORS documentation](https://www.freqtrade.io/en/latest/rest-api/#cors) points out - that's the precise url (including protocol, without any trailing slashes) that needs to be in the CORS setting.

**Comment by IgnacioGoldman** [comment]
In order to access my instances, i'm using this url:
`http://<public-ip-aws-instance>`

Which it works for the first instance (freqtrade1, myuser, mypwd) but not for the 2nd one.

I've configured CORS within the 2nd instance config file as you suggested: including protocol, without any trailing slashes:
`"CORS_origins": ["http://<public-ip-aws-instance>", "http://0.0.0.0:8080", "http://localhost:8080", "http://localhost:8080"]`

I tried with and without the port at the end, neither works. Does this setting needs to be configured also in the first instance? Or any other suggestion why this could not be working?

Thank you!

**Comment by stash86** [comment]
try accessing your second bot using `http://<public-ip-aws-instance>:81`

**Comment by IgnacioGoldman** [comment]
I cannot access but discovered the issue.

I needed to add 81 in the security group. Fixed now. 

Thank you guys!!!
