### ISSUE TITLE
Help with DMI/ADX indicator to match TV

### ISSUE THREAD

**Issue by naif824** [freqtrade/freqtrade#8584]
## Describe your environment

  * Operating system: Ubontu
  * Python Version: Python 3.10.7 (`python -V`)
  * CCXT version: ccxt==3.0.37 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.4.dev-6833059c7 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hello,
This is a strategy help with indicator question, i'm trying to match TradingView DMI indicator on 28 period and 14 ADX smoothing, cant get the same results despite having multiple tries, my indicators definitions are:
```

`        dataframe['adx'] = ta.ADX(dataframe, timeperiod=28)

        dataframe['dmi_minus'] = ta.MINUS_DI(dataframe, timeperiod=28 , smooth=14)

        dataframe['dmi_plus'] = ta.PLUS_DI(dataframe, timeperiod=28, smooth=14)`
```

TV setting i'm trying to match:
![image](https://user-images.githubusercontent.com/40152762/235529515-7580e465-0200-4d64-850a-db2f4455c1f6.png)

I also tried to use:
```
`        # dmi = fta.DMI(dataframe, period=28)

        # dataframe['dmi_plus'] = dmi['DI+']

        # dataframe['dmi_minus'] = dmi['DI-']

        # dataframe['adx'] = fta.ADX(dataframe, period=28, smooth=14)`
```

But landed no where, am I missing something?

**Comment by stash86** [comment]
We really have no idea how TV calculate ADX and DMI. Those ta and finta open their codes on how the indicators are calculated. So unless you can get TV's formula for DMI and ADX, nothing can be done.

**Comment by naif824** [comment]
TV is calculating it this way.
[TV.txt](https://github.com/freqtrade/freqtrade/files/11369604/TV.txt)


```

//@version=5
indicator(title="Directional Movement Index", shorttitle="DMI", format=format.price, precision=4, timeframe="", timeframe_gaps=true)
lensig = input.int(14, title="ADX Smoothing", minval=1, maxval=50)
len = input.int(14, minval=1, title="DI Length")
up = ta.change(high)
down = -ta.change(low)
plusDM = na(up) ? na : (up > down and up > 0 ? up : 0)
minusDM = na(down) ? na : (down > up and down > 0 ? down : 0)
trur = ta.rma(ta.tr, len)
plus = fixnan(100 * ta.rma(plusDM, len) / trur)
minus = fixnan(100 * ta.rma(minusDM, len) / trur)
sum = plus + minus
adx = 100 * ta.rma(math.abs(plus - minus) / (sum == 0 ? 1 : sum), lensig)
plot(adx, color=#F50057, title="ADX")
plot(plus, color=#2962FF, title="+DI")
plot(minus, color=#FF6D00, title="-DI")
```

**Comment by xmatthias** [comment]
If you're after tradingview alignment, then pandas-ta is probably the best bet.
their goal is to have their indicators aligned to tradingview as much as possible.

with just a quick look, i'd assume the "breaking point" might be the use of `ta.rma` - which is often not implemented this way, and many libraries are using different moving average calculation.

Considering it's a "pure" TA question though, i think your best bet will be the respective indicator library issue trackers. These are the experts with their library - we're effectively just users.

**Comment by naif824** [comment]
Many thanks Stefano and Matthias,
I'm gonna do some research and update later.
