### ISSUE TITLE
The 'adjust trade position' function is not working

### ISSUE THREAD

**Issue by thkwon9474** [freqtrade/freqtrade#8585]
Operating system: Ubuntu 22.04
Python Version:  python -V 3.11
CCXT version:  ccxt==2.6.26
Freqtrade Version: freqtrade 2023.1.dev-7092212ed
  
## Your question

Hello Team:)

I have a question about 'adjust_trade_position'

1. Despite setting 'position_adjustment_enable = True', my backtesting results do not reflect this feature.

2. what is the tag when adjust_trade_postion activated?

As following code is for adjust_trade position and custom exit.

It would be very helpful to me if you could tell me why.

##################################################################

    def adjust_trade_position(self, trade: Trade, current_time: datetime,
                              current_rate: float, current_profit: float,
                              min_stake: Optional[float], max_stake: float,
                              current_entry_rate: float, current_exit_rate: float,
                              current_entry_profit: float, current_exit_profit: float,
                              **kwargs) -> Optional[float]:       
        filled_exits = trade.select_filled_orders(trade.exit_side)
        count_of_exits = trade.nr_of_successful_exits
        if trade.is_short:
            if current_rate < (trade.stop_loss - trade.open_rate) * 2 - trade.open_rate :
                return (- trade.max_stake_amount)

            elif (current_rate < (trade.stop_loss - trade.open_rate) - trade.open_rate) and (count_of_exits == 0) :
                return (- trade.stake_amount / 2)
                        
        else:                        
            if current_rate > (trade.open_rate - trade.stop_loss) * 2 + trade.open_rate :
                return (- trade.max_stake_amount)

            elif (current_rate > (trade.open_rate - trade.stop_loss) + trade.open_rate) and (count_of_exits == 0) :
                return (- trade.stake_amount / 2)

    def custom_exit(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, **kwargs):
        if int(current_time.strftime('%M')) % 5 == 0:
            dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
            last_candle = dataframe.iloc[-1].squeeze()
            prev_candle = dataframe.iloc[-2].squeeze()

            if trade.is_short:
                #if last_candle[f'supertrend_1_sell'] == 'up' and prev_candle[f'supertrend_1_sell'] == 'down':
                #    return 'S1_EXIT'
                #if last_candle[f'supertrend_2_sell'] == 'up' and prev_candle[f'supertrend_2_sell'] == 'down':
                #    return 'S2_EXIT'
                if last_candle[f'supertrend_3_sell'] == 'up' and prev_candle[f'supertrend_3_sell'] == 'down':
                    return 'S3_EXIT'

            else:
                #if last_candle[f'supertrend_1_buy'] == 'down' and prev_candle[f'supertrend_1_buy'] == 'up':
                #    return 'L1_EXIT'
                #if last_candle[f'supertrend_2_buy'] == 'down' and prev_candle[f'supertrend_2_buy'] == 'up':
                #    return 'L2_EXIT'
                if last_candle[f'supertrend_3_buy'] == 'down' and prev_candle[f'supertrend_3_buy'] == 'up':
                    return 'L3_EXIT'

**Comment by xmatthias** [comment]
`position_adjustment_enable` can be set in many places (strategy, config). 

The (startup) logs will have info on what is actually being used.

You should also be careful with your version - we continuously update and improve - however we're unable to support older versions (your version is outdated by 3-4 stable versions).

**Comment by thkwon9474** [comment]
Thank u for response:)

U mean after update the freqtrade version. Does that mean it works the way I designed it?

like below the code 

        if current_rate < (trade.stop_loss - trade.open_rate) * 2 - trade.open_rate :
            return (- trade.max_stake_amount)

        elif (current_rate < (trade.stop_loss - trade.open_rate) - trade.open_rate) and (count_of_exits == 0) :
            return (- trade.stake_amount / 2)

**Comment by xmatthias** [comment]
well your intend is not clear if i'm honest - and i don't intend to review the actual logic applied (the intend can vary, so there's no actual "correct").

returning `-trade.max_stake_amount` will most certainly fail - as that'd result in a complete exit, which is considered as "user error" - and therefore ignored. 
If you intend to exit completely, that code should go to custom_exit instead.

**Comment by thkwon9474** [comment]
I apologize for asking this question multiple times.

What I'm trying to implement is that when I hit a certain point, I want to sell a half.

Custom_exit returns the full amount due to the nature of the function.

I'm sorry, but is there any other way to buy and sell halves?

**Comment by xmatthias** [comment]
the "selling half" portion should work this way (assuming your condition is correct - which i did explicitly NOT check).
If your first condition triggers first, then you'd always end in the wrong portion of the IF - resulting in the logic to be broken.

To exit completely, you'll need to use the [`custom exit` callback](https://www.freqtrade.io/en/latest/strategy-callbacks/#custom-exit-signal).

**Comment by thkwon9474** [comment]
Thank u for ur response:)
