### ISSUE TITLE
The trade go through even if the entry conditions are not met. 

### ISSUE THREAD

**Issue by thkwon9474** [freqtrade/freqtrade#8586]
Operating system: Ubuntu 22.04
Python Version: python -V 3.11
CCXT version: ccxt==2.6.26
Freqtrade Version: freqtrade 2023.1.dev-7092212ed
  
## Your question

Hello Team:)

I'm wondering that the difference entry Algorithm and test result.
What I would like to say....

As shown in the code below, my entry conditions are twofold: the moment the stochastic RSI ⓐgoes below 20 and ⓑthe golden cross above 20.

As you can see from the yellow shading in the attachment, I am entering despite not meeting these conditions.

If you could comment on this, it would be very helpful for development.

![image](https://user-images.githubusercontent.com/123524953/235568002-cd69096f-0b85-4343-b517-ed5e414bcdbe.png)

as following the code is for qtpylib crossed.
As I understand it, the signal is only occured at the point of intersection.
![image](https://user-images.githubusercontent.com/123524953/235578584-5e79c869-9ccc-48ee-b619-31b5ce6975f8.png)

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        stoch_rsi = ta.STOCHRSI(dataframe, timeperiod=14, fastk_period=3, fastd_period=3)
        dataframe['fastk_rsi'] = stoch_rsi['fastk']
        dataframe['fastd_rsi'] = stoch_rsi['fastd']

    return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        #Trending
        dataframe.loc[
            (   
                #(dataframe.shift(1)['difference'] < 700) #TH, Eliminate candles that show rapid changes in an instant. In Future, variable will be optimize
                (dataframe['macd'] > 0) 
                & (dataframe['close'] > dataframe['ema240'])#TH, This line means long trending 
	            & (
                    qtpylib.crossed_above(dataframe['fastk_rsi'],20) |
                    ( 
                        qtpylib.crossed_above(dataframe['fastk_rsi'],dataframe['fastd_rsi']) 
                        & dataframe['fastk_rsi'] > 20
                    )
                  )
                & (dataframe['close'] > dataframe['sar'])
                & ((dataframe['ema5'] > dataframe['ema10']) & (dataframe['ema10'] > dataframe['ema15']) & (dataframe['ema15'] > dataframe['ema25']))                
            ),
            ['enter_long', 'enter_tag']] = (1, 'arrangement')

**Comment by xmatthias** [comment]
Just looking at that 1st yellow line in your excel file, it CAN be ok (it's missing prior lines, so can't tell).

your fastk_rsi signals are with an or condition - so either fastk_rsi crosses above 20, or the 2 lines cross, with fastk_rsi > 20.

`qtpylib.crossed_above(dataframe['fastk_rsi'],20)`

what this really means is that the value in the prior row was <20, and now it's >20.
without context on what the prior line actually was, it's impossible to tell if they did cross or not.

**Comment by thkwon9474** [comment]
Here's what I'm wondering

Despite the declaration below, the 'Crossed_above' function seems to behave as a range, not as an attachment.

For example, 

qtpylib.crossed_above(dataframe['fastk_rsi'],dataframe['fastd_rsi']) 
                    & dataframe['fastk_rsi'] > 20

means I should buy when fastk_rsi is above 20 and a golden cross occurs.

However, I review the log, it buys whenever it is above 20.

**Comment by xmatthias** [comment]
> Despite the declaration below, the 'Crossed_above' function seems to behave as a range, not as an attachment.

this statement doesn't make any sense if i'm honest.
we're working with pandas dataframes - what you pass in is a series (one column of the dataframe) - and we expect to get the result as a series again - comparing all rows in the 2 values with each other.

Comparing to scalars (single values) works as well - which would convert the "20" to a series internally.

You can pretty easily verify / doublecheck this yourself by using `dataframe['crossed_fastk'] = qtpylib.crossed_above(dataframe['fastk_rsi'],20)` - and looking at this in freqUI.

**Comment by thkwon9474** [comment]
I think my question was unclear.

Actually 'qtpylib.crossed_above(dataframe['fastk_rsi'],20) work properly.
But, qtpylib.crossed_above(dataframe['fastk_rsi'],dataframe['fastd_rsi'])
It work like fastk_rsi>fastd_rsi, rather than crossed above.

**Comment by xmatthias** [comment]
well - no.

neither the code, nor past experience suggests that's the case.

**Comment by froggleston** [comment]
> I think my question was unclear.
> 
> Actually 'qtpylib.crossed_above(dataframe['fastk_rsi'],20) work properly. But, qtpylib.crossed_above(dataframe['fastk_rsi'],dataframe['fastd_rsi']) It work like fastk_rsi>fastd_rsi, rather than crossed above.

I've never seen any such behaviour in over 2 years of using that function.

**Comment by thkwon9474** [comment]
@xmatthias @froggleston 
Thank u for your response:) Still i'm wondering, 

Set that condition to

dataframe.loc[
    (qtpylib.crossed_above(dataframe['fastk_rsi'],20))
    | (qtpylib.crossed_above(dataframe['fastk_rsi'],dataframe['fastd_rsi']))
      &(dataframe['fastk_rsi'] > 20)
]

will it work as a series?
In that case, it would be output as if it were a value.

Also, when comparing via shift without calling the qtpylib.crossed function, the value is calculated correctly.

And Here's the process to get the same Stocharsi as the Binance app.
Please note
https://github.com/freqtrade/freqtrade/issues/2961


Thanks for always answering my questions.
Have a great day

**Comment by xmatthias** [comment]
I don't see how alignment with tradingview is relevant to this issue.

It's plain (pandas) math we're talking about - and as said above - you can pretty easily assign each column/comparison  individually and look at the results in freqUI (or plot-dataframe, after configuring that newly added column) to ensure the result of that comparison is what you expect it to be (and then combine these columns individually with different operators).


Now when we talk about using `qtpylib.crossed_above` - then my assumption is that it's imported either from freqtrade (`import freqtrade.vendor.qtpylib.indicators as qtpylib`) or from technical (`from technical import qtpylib`) - which use a patched version of this function.

qtpylib itself is however also a (outdated) pypi module - which uses a slightly buggy implementation - with the fix (https://github.com/ranaroussi/qtpylib/pull/160) being never merged.

**Comment by froggleston** [comment]
> will it work as a series?

Yes, everything in the vectorised operations in pandas, e.g. `.loc` works on Series.

**Comment by thkwon9474** [comment]
For #2961, I confused it with another question and posted an answer.

For the rest, I've solved all of them with the advice you gave, and thank you again.
