### ISSUE TITLE
freqtrade - ERROR - No pair in whitelist.

### ISSUE THREAD

**Issue by muhammetacar** [freqtrade/freqtrade#8592]
backtesting doesn't run what can i do?

$ freqtrade backtesting --strategy SampleStrategy -i 1h

###config.json###
...
"exchange": {
        "name": "binance",
        "key": "filled",
        "secret": "filled",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
            "1INCH/USDT",
            "AAVE/USDT",
            "ACH/USDT",
            "ADA/USDT",
            "AGIX/USDT",
            "ALGO/USDT",
            "ALICE/USDT",
            "ALPHA/USDT",
            "AMB/USDT",
            "ANKR/USDT",
            "ANT/USDT",
            "APE/USDT",
            "API3/USDT",
            "APT/USDT",
            "AR/USDT",
            "ARB/USDT",
            "ARPA/USDT",
            "ASTR/USDT",
            "ATA/USDT",
            "ATOM/USDT",
            "AUDIO/USDT",
            "AVAX/USDT",
            "AXS/USDT",
            "BAKE/USDT",
            "BAL/USDT",
            "BAND/USDT",
            "BAT/USDT",
            "BCH/USDT",
            "BEL/USDT",
            "BLZ/USDT",
            "BNB/USDT",
            "BNX/USDT",
            "BTC/USDT",
            "C98/USDT",
            "CELO/USDT",
            "CELR/USDT",
            "CFX/USDT",
            "CHR/USDT",
            "CHZ/USDT",
            "CKB/USDT",
            "COCOS/USDT",
            "COMP/USDT",
            "COTI/USDT",
            "CRV/USDT",
            "CTK/USDT",
            "CTSI/USDT",
            "CVX/USDT",
            "DAR/USDT",
            "DASH/USDT",
            "DENT/USDT",
            "DGB/USDT",
            "DOGE/USDT",
            "DOT/USDT",
            "DUSK/USDT",
            "DYDX/USDT",
            "EDU/USDT",
            "EGLD/USDT",
            "ENJ/USDT",
            "ENS/USDT",
            "EOS/USDT",
            "ETC/USDT",
            "ETH/USDT",
            "FET/USDT",
            "FIL/USDT",
            "FLM/USDT",
            "FLOW/USDT",
            "FTM/USDT",
            "FXS/USDT",
            "GAL/USDT",
            "GALA/USDT",
            "GMT/USDT",
            "GMX/USDT",
            "GRT/USDT",
            "GTC/USDT",
            "HBAR/USDT",
            "HFT/USDT",
            "HIGH/USDT",
            "HOOK/USDT",
            "HOT/USDT",
            "ICP/USDT",
            "ICX/USDT",
            "ID/USDT",
            "IMX/USDT",
            "INJ/USDT",
            "IOST/USDT",
            "IOTA/USDT",
            "IOTX/USDT",
            "JASMY/USDT",
            "JOE/USDT",
            "KAVA/USDT",
            "KLAY/USDT",
            "KNC/USDT",
            "KSM/USDT",
            "LDO/USDT",
            "LEVER/USDT",
            "LINA/USDT",
            "LINK/USDT",
            "LIT/USDT",
            "LPT/USDT",
            "LQTY/USDT",
            "LRC/USDT",
            "LTC/USDT",
            "MAGIC/USDT",
            "MANA/USDT",
            "MASK/USDT",
            "MATIC/USDT",
            "MINA/USDT",
            "MKR/USDT",
            "MTL/USDT",
            "NEAR/USDT",
            "NEO/USDT",
            "NKN/USDT",
            "OCEAN/USDT",
            "OGN/USDT",
            "OMG/USDT",
            "ONE/USDT",
            "ONT/USDT",
            "OP/USDT",
            "PEOPLE/USDT",
            "PERP/USDT",
            "PHB/USDT",
            "QNT/USDT",
            "QTUM/USDT",
            "RDNT/USDT",
            "REEF/USDT",
            "REN/USDT",
            "RLC/USDT",
            "RNDR/USDT",
            "ROSE/USDT",
            "RSR/USDT",
            "RUNE/USDT",
            "RVN/USDT",
            "SAND/USDT",
            "SFP/USDT",
            "SKL/USDT",
            "SNX/USDT",
            "SOL/USDT",
            "SPELL/USDT",
            "SSV/USDT",
            "STG/USDT",
            "STMX/USDT",
            "STORJ/USDT",
            "STX/USDT",
            "SUSHI/USDT",
            "SXP/USDT",
            "T/USDT",
            "THETA/USDT",
            "TLM/USDT",
            "TOMO/USDT",
            "TRB/USDT",
            "TRU/USDT",
            "TRX/USDT",
            "UNFI/USDT",
            "UNI/USDT",
            "USDC/USDT",
            "VET/USDT",
            "WAVES/USDT",
            "WOO/USDT",
            "XEM/USDT",
            "XLM/USDT",
            "XMR/USDT",
            "XRP/USDT",
            "XTZ/USDT",
            "XVS/USDT",
            "YFI/USDT",
            "ZEC/USDT",
            "ZEN/USDT",
            "ZIL/USDT",
            "ZRX/USDT"
        ],
        "pair_blacklist": [
        ]
    },
 "pairlists": [
        {
            "method": "StaticPairList",
            "number_assets": 50,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
...

**Comment by froggleston** [comment]
If you're using futures, your pair naming needs to be `coin/stake:settle` - https://www.freqtrade.io/en/stable/leverage/#pair-namings

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.
