### ISSUE TITLE
confirm_trade_entry >> 'candle_in_progress'

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8593]
I just made a basic test for confirm_trade_entry, by using candle_in_progress = dataframe.iloc[0].squeeze(). If I am not wrong, the code is accessing the current candle, which is not yet closed. Do you agree with me? The small def looks like this, while the condition, which does not make sense, just opens the trade asap, for testing reasons:

`    def confirm_trade_entry(self, pair: str, order_type: str, amount: float, rate: float,
                            time_in_force: str, current_time: datetime, entry_tag: Optional[str],
                            side: str, **kwargs) -> bool: 
       

        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)

        if ((len(dataframe) < 2) | (dataframe.index[-1] < 1) | (dataframe.index[-2] < 1)): return False

        candle_in_progress = dataframe.iloc[0].squeeze()
        candle_shift_1 = dataframe.iloc[-1].squeeze()
        candle_shift_2 = dataframe.iloc[-2].squeeze()

        if (candle_in_progress['open'] != candle_shift_1['open']):
            return True

        return False`

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

I'm not entirely sure what your question is about (in detail) - but in general, it's safe to assume that freqtrade works on closed candles only (throughout all different callbacks).
Open candles are non-static, and can (and will) change over time - which will create repainting issues (indicators will start to have "ghost" signals, ...) - which is something that's very difficult to track / investigate.

current price for callbacks (where applicable) - and for evaluating stoploss / roi does come from the orderbook (based on the pricing configuration) - or from the "ticker" endpoint (which is usually less precise / slower).

**Comment by myNextCoder** [comment]
I thank you for your answer.

(This information in braces, since it does not concern Freqtrade: As I opened the ticket, I was wondering, why the usual template was not visible, but only the empty editor window. If the template is present next time, I will fill it out)

**Comment by xmatthias** [comment]
You've probably used a direct link to the new issue (afaik, this can't be prevented) - going to "issues" and clicking "new issue" will show the template.

**Comment by myNextCoder** [comment]
I usually push 'issues' at the top left, then the green button at the right 'new issue', and 'question', using Microsoft Edge Browser. I guess, this was a one time issue.
