### ISSUE TITLE
FreqAI and VolumePairList

### ISSUE THREAD

**Issue by blastbeng** [freqtrade/freqtrade#8594]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.10.11
  * CCXT version: 3.0.85
  * Freqtrade Version: docker-2023.5.dev-e3ff2ccc
  
## Your question

Hello,
I am currently using freqAI but i don't understand how pairlist works.
Is it possible to make freqAI use my generated pairlist from **VolumePairList** instead of setting each coin inside the config entry **include_corr_pairlist** ?

Thanks

```
"pairlists": [{
	"method": "VolumePairList",
	"number_assets": 50,
        "sort_key": "quoteVolume",
        "refresh_period": 1800
    },
```

**Comment by robcaulk** [comment]
Hello,

You may be mistaking how the components of FreqAI work.

FreqAI does not support any pairlist that *adds* new pairs during runtime. 

FreqAI supports lists that change *order* only or *remove* pairs. 

`include_corr_pairlist` is a separate component that helps you add informative information to a model. You build a model of ADA, but you want informative info from BTC and ETH to be included as features in your model. This is the purpose of `include_corr_pairlist`.

Please have a look in our documentation where we describe all this and much more [here](https://www.freqtrade.io/en/stable/freqai-parameter-table/#feature-parameters).

**Comment by robcaulk** [comment]
Unless I missed something, this issue seems closed. Feel free to reopen if necessary.
