### ISSUE TITLE
dry_run_order-stopPrice

### ISSUE THREAD

**Issue by superXR** [freqtrade/freqtrade#8597]
## Describe your environment

  * Operating system: linux
  * Python Version: Python 3.9.16
  * CCXT version: ccxt==3.0.75
  * Freqtrade Version: stable
  
## Your question
When create dry_run stoploss order,why not use self._ft_has['stop_price_param'] ? I notice that "stop_price_param" is "stopLossPrice" in okx.py, not "stopPrice"
![image](https://user-images.githubusercontent.com/57396498/236624136-ccb85d0f-53e5-403f-ad37-1fd7e8857297.png)
![image](https://user-images.githubusercontent.com/57396498/236624621-44626a90-1c48-4034-8416-46b02b4f7808.png)

**Comment by xmatthias** [comment]
Please check the code of develop before opening issues.
this has been changed about 2 weeks ago.
