### ISSUE TITLE
Multi-bot dashboard shows duplicate statistics for different bots

### ISSUE THREAD

**Issue by abel-tefera** [freqtrade/freqtrade#8612]
## Describe your environment

  * Operating system: __CentOS7__
  * Python Version: __3.8__ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade 2023.4__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Why is my multi-bot dashboard duplicating the statistics from one bot?

Hello, I started experimenting with freqtrade recently and I'm really enjoying it. I'm running five dry-run instances of the bot, with different databases, logs, config files, and strategies for each, using docker containers hosted on a VPS. 

I've set up the containers to have different port mapping for the freqUI, and I've created an ssh tunnel to access all 5 instances of the UI using different ports. I've not directly exposed the freqUI to the internet for security reasons. The problem I encountered is, on the main dashboard, I see the list of bots but the statistics are showing me the same data on all 5. The first bots data is being duplicated on all 5 rows of the table, and I'm not sure whether this is a bug or an error in my configuration. 

![Screenshot](https://drive.google.com/uc?export=view&id=11hoCl1S9_GwPOMvPjK0PXm1iGuYWSKN-)

I can still separately access the UI instances using different ports, but it would be nice if I could see a summary on the dashboard. 

I've followed the docs properly to create multiple instances of the bot, by creating different services on my docker-compose.yml file. I've set different port mappings, different telegram, strategy for each. I'm using an `.env` file to set the variables.

Here's my docker-compose.yml file: 
```
version: '3'
services:
  freqtrade1:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade1
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/${LOG_1}
      --db-url sqlite:////freqtrade/user_data/${DB_1}
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/${CONFIG_1}
      --strategy ${STRATEGY_1}
  freqtrade2:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade2
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8081:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/${LOG_2}
      --db-url sqlite:////freqtrade/user_data/${DB_2}
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/${CONFIG_2}
      --strategy ${STRATEGY_2}
  freqtrade3:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade3
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8082:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/${LOG_3}
      --db-url sqlite:////freqtrade/user_data/${DB_3}
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/${CONFIG_3}
      --strategy ${STRATEGY_3}
  freqtrade4:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade4
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8083:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/${LOG_4}
      --db-url sqlite:////freqtrade/user_data/${DB_4}
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/${CONFIG_4}
      --strategy ${STRATEGY_4}
  freqtrade5:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade5
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8084:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/${LOG_5}
      --db-url sqlite:////freqtrade/user_data/${DB_5}
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/${CONFIG_5}
      --strategy ${STRATEGY_5}
```

Here's the api_server entry in my config file:
```
  "api_server": {
    "enabled": true,
    "listen_ip_address": "0.0.0.0",
    "listen_port": 8080,
    "verbosity": "error",
    "enable_openapi": false,
    "jwt_secret_key": "somesecret",
    "CORS_origins": ["http://localhost:8080"],
    "username": "someuser",
    "password": "somepassword"
  },
```

Thanks for your time. Everyone's work on this project is highly appreciated. 

_Note: I haven't shared any sensitive data_

**Comment by xmatthias** [comment]
well your setup has a lot of points of failure.

to summarize ... 
`freqUI -> ssh tunnel -> docker -> freqtrade`


The first one you can check quite easily via tooltip (hover over each botname in the main page for a bit)  - which is if you've added all bots correctly, or if you've used the same port for each of the bots (except for the first, according to the screenshot).

![image](https://user-images.githubusercontent.com/5024695/236875741-16df5983-8ce0-4c74-aa2a-063544dac2df.png)

Your next step will be the ssh tunnels - which could obviuously be "misslinked" - all pointing to the same Port.


Docker itself looks good at first glance.

> I can still separately access the UI instances using different ports, 

Based on this, i'd assume that SSH is correct as well - which leaves the "bot addition" to be the most likely "faulty point".

let me know if this helps / solves your problem, or if we need to think further

**Comment by abel-tefera** [comment]
I figured out the problem was caused by my configuration. I put the `api_server` entry in the main config file and shared it across the bots, which means I was using the same values for `jwt_secret_key` and `ws_token`. So I made different entries for each bot, and now it's working as expected displaying different statistics for each bot on the dashboard.  So it's all good, thanks for the help!

**Comment by tomjrtsmith** [comment]
I've had the same issue happening forever and never figured out how to solve it. Thanks!
