### ISSUE TITLE
Forceenter input and error message seems not working 

### ISSUE THREAD

**Issue by polyvios-bc** [freqtrade/freqtrade#8621]
## Describe your environment

  * Operating system:  OSX
  * Python Version: 3.9.6
  * Freqtrade Version:  latest stable
  
## Your question

Trying to do a /forceenter rest api call to a running bot passing just the pair and direction that I want but seems its failing with no obvious reason.

Input payload: 
`{'pair': 'JASMY/USDT', 'side': 'short', 'price': None}
`

Response:
` {'detail': [{'loc': ['body'], 'msg': 'field required', 'type': 'value_error.missing'}]}`

According with the documentation here:
(https://www.freqtrade.io/en/stable/rest-api/#available-endpoints)

forceenter
    Force entering a trade

        :param pair: Pair to buy (ETH/BTC)
        :param side: 'long' or 'short'
        :param price: Optional - price to buy

It should work

**Comment by xmatthias** [comment]
you can omit price (not send it) - but i don't think sending `None` is valid.

While i don't remember how i did it - you might wanna check the implementation in [freqUI](https://github.com/freqtrade/frequi) - where i know this is working fine.

**Comment by polyvios-bc** [comment]
Yeah first i tried and without the price same error unfortunately.

**Comment by polyvios-bc** [comment]
Seems like on freqUI you are using forcebuy -->

```
 async forceentry(payload: ForceEnterPayload) {
        if (payload && payload.pair) {
          try {
            // TODO: Update forcebuy to forceenter ...
            const res = await api.post<
              ForceEnterPayload,
              AxiosResponse<StatusResponse | TradeResponse>
            >('/forcebuy', payload);
            showAlert(`Order for ${payload.pair} created.`, 'success');

            return Promise.resolve(res);
          } catch (error) {
            if (axios.isAxiosError(error)) {
              console.error(error.response);
              showAlert(`Error occured entering: '${error.response?.data?.error}'`, 'danger');
            }
            return Promise.reject(error);
          }
        }
```

**Comment by polyvios-bc** [comment]
Also forgot to mentioned I am just using the rest_client.py from your scripts  https://github.com/freqtrade/freqtrade/blob/develop/scripts/rest_client.py#L272

**Comment by froggleston** [comment]
This sounds like a similar problem to the `limit` argument for pair_candles, where a check needed to be added to ensure the None isn't passed: https://github.com/freqtrade/freqtrade/blob/develop/scripts/rest_client.py#L335

**Comment by polyvios-bc** [comment]
> This sounds like a similar problem to the `limit` argument for pair_candles, where a check needed to be added to ensure the None isn't passed: https://github.com/freqtrade/freqtrade/blob/develop/scripts/rest_client.py#L335

I tried and without sending the price before I got the same error

**Comment by xmatthias** [comment]
I'm not entirely sure about this issue - if i run `python scripts/rest_client.py --config api.json forceenter XRP/USDT long` - it enters the trade just fine - also without having a price specified?

What's the actual command you're using for this?

**Comment by polyvios-bc** [comment]
So I am using the RestClient inside a webhook handler and I am just calling the function forceenter passing the pair and the side. So nothing special it should work

**Comment by polyvios-bc** [comment]
Also forgot to mentioned that the bot is in dry mode

**Comment by polyvios-bc** [comment]
Seems was an issue on my side , sorry for that
