### ISSUE TITLE
Can I use redis at the strategy build part? 

### ISSUE THREAD

**Issue by thunderwin** [freqtrade/freqtrade#8627]
Can I use redis at the strategy build part? 
here is my code goes.

```

def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        self.redis_cli = redis.Redis(host='host', port=6379, db=0)
        self.redis_data = self.redis_cli.get('my_data_key')
        dataframe['my_data'] = self.redis_data`
```

is this the right way to approach it?

**Comment by xmatthias** [comment]
A strategy is really just python code - so whatever is valid in python will work here, too.

From an efficiency standpoint, you'll most likely not want to establish the connection over and over again (and most likely, never close it).

You should therefore probably split this up into different methods - best have a look at the [strategy callbacks](https://www.freqtrade.io/en/stable/strategy-callbacks/) - which provide you with some lifecycle events (bot-start / bot_loop_start) - which would probably be more appropriate to get the actual data.

---

Now this won't be backtestable (unless you can provide historic data) - but i guess you're aware of that.

**Comment by thunderwin** [comment]
So there is nothing wrong here,right?

**Comment by thunderwin** [comment]
cause I m facing a error

```
Strategy caused the following exception: encoding with 'idna' codec failed (UnicodeError: label empty or too long)<bound method IStrategy._analyze_ticker_internal of <simple.chongAgain object at 0x7fb63fd5d5a0>>
2023-05-11 16:37:09,562 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair APT/USDT:USDT: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
```

**Comment by xmatthias** [comment]
It's not obviously wrong - but might be problematic still (needs more knowledge on how the client you're using works).

however, it **could** be leaking open connections, as you're overwriting the `self.redis_cli` object for each pair - most likely opening a new connection for every pair/iteration.
Depends a bit how redis works - which i'm not going to investigate for you.

**Comment by BsL7771438gfG8643215590** [comment]
Bonjour

Ahcene Annaba Bounour

**Comment by thunderwin** [comment]
ok....   I will do it myself see how it works.. I m surprised no one mentioned Redis in the community,

**Comment by xmatthias** [comment]
i'm not entirely sure what the use case for that would be (though as said, it's python code, so it'll work).

You'll need to have some other setup to actually populate the redis store with - in which case you can almost always replace redis with actually connecting to the "generating" service - and with that greatly simplify your setup.

**Comment by thunderwin** [comment]
I'm using Redis now, and it works like a charm!    I m using Redis to connect with third-party Data. like other AI, data sources, and change the Strategy dynamically.    by saying,for example, some breaking news happening, my bot can react in time!!
