### ISSUE TITLE
Parameter 'rate' in confirm_trade_entry

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8629]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Latest Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.2 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I am working with limit orders: Is the parameter 'rate' in confirm_trade_entry equal to the current price? If not: How do I get the current price within the def confirm_trade_entry?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
It's the current rate at which the trade will be placed  - which one (ask / bid, ...) - is determined by the actual configuration, and eventually callbacks (if used).
"rate" is the rate your [pricing configuration](https://www.freqtrade.io/en/stable/configuration/#prices-used-for-orders) specifies (including eventual price callbacks).
