### ISSUE TITLE
Add the option to shuffle timeframes when downloading, based on load for the exchange (for faster downloads overall)

### ISSUE THREAD

**Issue by hippocritical** [freqtrade/freqtrade#8633]
Hi, I wrote myself a little something that shuffles the timeframes and wondered if others would need a --shuffle - option too or something like that.

Other users have reported that they have to throttle downloads - when we would have a --shuffle option it would maybe eleviate some of those issues and allow faster downloading.

(usually users do ascending / descending orders of which 3m and 1m are the most taxing, so the load for the exchange is leaning heavily to one side of the downloads, not at all to the others)

Again, just a suggestion / question if this would be of any need - nothing more.

The function of mine downloads all timeframes of the exchange, it could be easily adapted to just shuffle

        def reorder_timeframes():
            # --- start preparing timeframes
            # get timeframes and shuffle them around so it s first last ... to avoid being blocked by the exchange
            bashCommand_get_timeframes = f"freqtrade list-timeframes " \
                                         f"--config={config_baseline} " \
                                         f"--config={config_pairlist}"
            # Run the command and redirect output to /dev/null
            output = subprocess.check_output(bashCommand_get_timeframes, shell=True, stderr=subprocess.DEVNULL)
            last_line = output.decode().splitlines()[-1]
            # print(last_line)

            # Split the string at the colon and get the second part
            timeframes_part = last_line.split(":")[1]

            # Split the timeframes into a list, remove whitespaces
            timeframes_list = [tf.strip() for tf in timeframes_part.split(",")]

            # Print the filtered list of timeframes
            # print(timeframes_filtered)

            # Define the order of timeframes
            timeframes_order = ['3m', '15m', '30m',
                                '5m', '1h', '2h', '4h', '6h', '8h', '12h',
                                '1d', '3d', '1w', '1M', '1m']

            # Remove any timeframes that contain the letter "s"
            timeframes_filtered = [tf for tf in timeframes_list if "s" not in tf]

            # Create a dictionary with the timeframes as keys and their indices as values
            timeframes_indices = {tf: timeframes_order.index(tf) for tf in timeframes_filtered if
                                  tf in timeframes_order}

            # Sort the filtered timeframes based on their indices in the timeframes_order list
            timeframes_sorted = sorted(timeframes_filtered,
                                       key=lambda tf: timeframes_indices.get(tf, len(timeframes_order)))

            # Append any timeframes not in the timeframes_order list to the end of the sorted list
            timeframes_reordered = timeframes_sorted + [tf for tf in timeframes_filtered if tf not in timeframes_order]

            # make list unique, can't be bothered to look why it s sometimes multiple...
            timeframes_reordered = list(set(timeframes_reordered))

            # Print the reordered list of timeframes
            # print(timeframes_reordered)
            return " ".join(timeframes_reordered)

**Comment by xmatthias** [comment]
i'm not entirely sure i understand your point here (or what you're trying to actually achive).

how would load on/against the exchange change if i'm loading `1h 30m 5m 3m 1m` - vs. `1m 3m 5m 30m 1h` ? 
it's still the same exact number of calls ... and the exchange will still apply the same ratelimit (they won't care about the sequence of calls).
As a consequence - if the download for the 1st variant took 1h - then the 2nd order will take exactly the same hour (obviously assuming nothing else has been changed).
smaller timeframes will feel slower (there's more calls to download 1month of 1m candles, vs. 1 month of 1h candles) - but for the exchange / exchange load - the sequence is really irrelevant.


within a freqtrade process, you can do that with probably 3 lines - but that's beyond the point, as i'm not sure why it would be useful.

**Comment by hippocritical** [comment]
> how would load on/against the exchange change if i'm loading 1h 30m 5m 3m 1m - vs. 1m 3m 5m 30m 1h ?

You just flipped the timeframes, this will not have any effect, your example is not the point I wanted to make.

The point is that you distribute the load evenly, assuming you are using a ccxtRate of 100 you might run into bottleneck of the vps. A timeframe of 1m is much more taxing than a timeframe of 1d for the exchange.

I am using this generally to enable lower ccxtRate values since if you chain 1m 3m 5m 15m then the exchange will set you back and freqtrade will wait for the exchange to be able to send data again (throttling)

If you alternated with timeframes of  high low high low then you will produce an average load for the exchange 

Yes both methods are overall producing the same load for the exchange, but the 1 minute weight limit (example binance = 1200) will be triggered if you blast first through 1m them 3m then 5m within the same minute, comparably to 1m 1d 30m ... then not.

The target would just be that you could lower the ccxtRate comparably a little more, from let's say 100 to 50 without the exchange arguing about you pestering it too much within the same 1 minute timeframe (where most exchanges limit the query amounts generally)

Again, if you say no then np - was just an idea to introduce --shuffle or something like that :)

**Comment by xmatthias** [comment]
the best way with rate-limit is to remove it from the configuration altogether.
This changed sometime last year iirc - but is now the recommended way.

If it's not present, then the ccxt dynamic weight logic will kick in - which will (in almost all cases i've seen so far) have way better performance than any manually set value.

---

Can you back this up with some data (and corresponding command lines to reproduce)? (it should work just fine with different `-t` sequences).
like - if i run it like "this" - then it'll be 5 minutes, if i run it like "that" - then it'll be done in 2 minutes.

Best use different `--data-dir` settings, which will use a new datadir each - avoiding messing of existing data.

Obviously the assumption here is to use no rateLimit (or a very low ratelimit) - which is NOT modified between tests - otherwise you're testing something entirely different.

**Comment by hippocritical** [comment]
| shuffled, no ccxtRate | Non-shuffled, no ccxtRate
-- | -- | --
start(seconds from full hour) | 2073 | 2669
end(seconds from full hour) | 2545 | 3118
result | 472 | 449


In the previous experiments that lead to this it was not producing any errors anymore while fixating the ccxtRate to a specific value.
This seems in the non-scientific test with a sample size of 1 not to be anymore, which is weird.

Before (with default order ascending) with higher ccxtRates I had issues, with the shuffling I could go lower ccxtRate while not even getting any errors anymore.

I will still keep using ccxtRate while shuffling it since the backtest downloader then puts out a more flat load on the server and the dry runs will not get denied queries.

The test was done on my home pc with 20MBit download only while watching youtube videos so ... yeah

**Comment by xmatthias** [comment]
well that was my expectation.
load is a different topic - but (unless you run out of cpu/ram) for the exchange, i wouldn't see a difference in what you actually request.
