### ISSUE TITLE
Different timezones for current_time and trade.open_date_utc in adjust_trade_position

### ISSUE THREAD

**Issue by yperfanov** [freqtrade/freqtrade#8635]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version:  whatever is in the docker image
  * CCXT version:  whatever is in the docker image
  * Freqtrade Version: freqtrade docker-2023.5.dev-081a8b0e
  * Database: postgres

## Describe the problem:

__current_time__ and __trade.open_date_utc__ have different timezones in __adjust_trade_position__ callback method. 

### Steps to reproduce:
Add logging in the __adjust_trade_position__ method:
```
logger.info(f"current_time={current_time} trade.open_date_utc={trade.open_date_utc}\n")
```

### Observed Results:
__trade.open_date_utc__ timezone is not correct. It should be either 2023-05-13 17:11:24.700282+00:00 (UTC) or 2023-05-13 20:11:24.700282+03:00 (my timezone)

### Relevant code exceptions or logs

  ```
2023-05-13 17:39:15,466 - freqtrade.wallets - INFO - Wallets synced.
2023-05-13 17:39:27,840 - my_strategy - INFO - current_time_=2023-05-13 17:39:27.839913+00:00 trade.open_date_utc=2023-05-13 20:11:24.700282+00:00
  ```

![Screenshot from 2023-05-13 21-13-51](https://github.com/freqtrade/freqtrade/assets/21334461/baf51b25-9577-49a4-a9e9-7e7e75f4fa1b)
![Screenshot from 2023-05-13 21-12-46](https://github.com/freqtrade/freqtrade/assets/21334461/6b9776fa-b6ff-477d-a74d-3b620b6bafd6)

**Comment by yperfanov** [comment]
Digging a bit more on the issue it seems the problem is because Trade object date types in postgres are __timestamp__ and not __timestamptz__. What would be solution to this?

**Comment by xmatthias** [comment]
Please try how this behaves with sqlite (our main database backend)?

i've never noticed problems in this regards with sqlite - and if it's an oddity with postgres which can't be fixed in 1-2 lines, we'll probably simply drop support for postgres.

Now the actual database type type is really determined by sqlalchemy - we're simply using the new (default/recommended) syntax for sqlalchemy with `Mapped[datetime] = mapped_column()`.
If sqlalchemy is creating this as "without timezone" - then i'd assume it's converting the date to utc first. If it doesn't, i suspect it's a problem in sqlalchemy.

I couldn't however find much documentation if this maps to with or without timezone - but my base assumption would be that it's with timezone - as python datetimes also have timezones.

**Comment by yperfanov** [comment]
![Screenshot from 2023-05-13 21-49-06](https://github.com/freqtrade/freqtrade/assets/21334461/1b55a54b-bb3f-4fd7-ad0b-259045d0babf)

The above makes me think that even the date from freqtrade is sent with timezone postgres ignores it and stores it in UTC. In my case postgres receives __2023-05-13 20:11:24.700282+03:00__ but the open_date is timestamp and not timestamptz type and it will save __2023-05-13 20:11:24.700282+00:00__.

I don't wanna move to another db now so I will play with timezones in the strategy code whenever I need dates.

EDIT 1: I also have problem with canceling orders on unfilledtimeout (they cancel several hours after they should have been canceled) and exiting positions based on ROI settings (they never exit on that criteria). Now I think is clear why this is happening and  there are probably more bugs related to wrong timezones. So I am moving away from postgres.

EDIT 2: The more I look the more problems I see - telegram has entry times (Since column) wrong as well:
![Screenshot from 2023-05-13 22-31-41](https://github.com/freqtrade/freqtrade/assets/21334461/5245223f-cd04-493d-aaa1-b15eaba12258)
The entries above are 15 minutes ago not 2 hours.

You should definitely not only remove support for postgres but also strongly advice against using it unless the timezones issue is fixed.

**Comment by xmatthias** [comment]
Well as mentioned above, we're using sqlalchemy to handle with the database - and my assumption is/was that it's handling this properly - which apparently it isn't.

I'll look at this when i find time - but it's not really a priority at the moment.
if there's a quick fix, i'll try to apply it - if it isn't we'll no longer support postgres.

**Comment by yperfanov** [comment]
I think I've found a [solution](https://docs.sqlalchemy.org/en/14/core/custom_types.html#store-timezone-aware-timestamps-as-timezone-naive-utc). Will try to implement it and make a pull request.

EDIT: @xmatthias I just checked the [commits](https://github.com/yperfanov/freqtrade/commit/66a97ff45de3e3ba39bf54a94657c8f52ba88536) and saw you made open and close date aware of the timezone which may solve the problem.

**Comment by xmatthias** [comment]
these commits don't have anything to do with your problem - they just treat a similar topic - but won't change how data is stored.

I also don't like / think the linked solution is an appropriate solution. All timestamps we store are in UTC format already.
without further investigation, my suspicion is that sqlalchemy is "forgetting" this when storing in postgres - and is applying the timezone offset again on the timestamp.

**Comment by yperfanov** [comment]
I've switched to sqlite for the moment. Everything works fine and will not look more into this issue for now.

**Comment by xmatthias** [comment]
This is actually not a problem i can recreate at the moment.

![image](https://github.com/freqtrade/freqtrade/assets/5024695/5d343c01-7af5-47ad-a3ab-13139c45ac05)

![pgadmin screenshot](https://github.com/freqtrade/freqtrade/assets/5024695/e5e7c3c2-890a-4a3f-b476-f80eedc79f4e)

All timestamps used here are correct (i opened the trade at 19:36 UTC+2) 

Using your log-statement above also uses the correct dates (though it's now a few minutes later, both timestamps are aligned).

![image](https://github.com/freqtrade/freqtrade/assets/5024695/746a44c6-a427-4b19-89c1-87018cd57af1)

---

I've tried to mess with timezones in the postgres container - but it doesn't seem to change anything - times are correct and "as desired". While they're not stored with timezone - it's also not relevant, as all times freqtrade uses are in tz=UTC anyway.

You might have a problem if the actual time setting between the server and the bot is different (so one of the clocks has the wrong UTC time) - but that's not a scenario we aim to support - as it's a misconfiguration of one of the 2 systems (timezone can be different - but the actual time cannot).
