### ISSUE TITLE
No module named 'ta'

### ISSUE THREAD

**Issue by 2morowMan** [freqtrade/freqtrade#8638]
Hi, im trying a few strategies (right now its TrixV15Strategy) , but i keep getting No module named 'ta'
i installed python 3.11, and did pip install pandas
if i now try pip install ta i get:
requirement already satisfied: ta in c:...

what am i doing wrong, please?

windows 10..........
numpy==1.24.3
pandas==2.0.1
python-dateutil==2.8.2
pytz==2023.3
six==1.16.0
ta==0.10.2
tzdata==2023.3

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

I've got no clue what `TrixV15Strategy` is. it's not a strategy provided in the official strategy repository - and i won't go hunting for random strategies someone mentions due to some random issue.

If you expect help - please provide the strategy / source (or at least the imports that cause the failure) - so we have an actual chance to look at this.

**Comment by 2morowMan** [comment]
i do apologise for not filling in your lengthy template in the right order. i assumed everyone would see the 'general' problem and maybe add some tips in solving this 'general' error. i have since discovered on another site that *many, common* strategies have recently started to fail due to changes in code structure, and the fix is to simply rewrite the import as "import talib.abstract as ta". 
Thank you for replying. i hope my solution helps others. (it already has on the other site).

**Comment by xmatthias** [comment]
There's not really such a thing as a "general" problem - and "no module named ta" can have multiple reasons - using `ta-lib.abstract as ta` is one solution, but not necessarily the right one (there's also a different, standalone ta module - which might or might not need to be installed).

I'm happy that you found a solution to this.

I do however wonder where you've found that "many common" strategies fail - as i'm not aware of any recent change in this regards - and it might be interesting / important to be aware of such changes, and what specifically triggered these changes.

**Comment by 2morowMan** [comment]
good point. but i am new to freqtrade - the problem strategies seem to all be just a year old (or more). 
Ive been getting them from github, but some from https://www.freqst.com/ (nearly all from there no longer work).

for example, trying a 24h dry run, with a 15m timeframe...
+)apollo11 = deprecated commands, doesn't work !!
+)ClucMay72018  = worked for an hour !?!?!?!?
+)CombinedBinHAndCluc  = no errors, but nothing happens !!
+)HyperStra_SMAOnly = deprecated commands, doesn't work !!
+)ichiV1 = deprecated commands, doesn't work !!
+)NotAnotherSMAOffSetStrategy_V2 = deprecated
+)NotAnotherSMAOffsetStrategyHOv3 = deprecated 
+)SwingHighToSky = no errors, but after 14 hours no trades.
+)TrixV15Strategy = No module named 'ta'    ['pandas' & 'ta' are installed, but not found. redo? with suggested fix.

hope it helps someone.

**Comment by xmatthias** [comment]
you might want to report these things to the maintainer of freqst.com (no clue who that is, sorry).

It's not a project / page we maintain, nor have any affiliation with.
they're obviously using freqtrade, which is perfectly fine - but it could maybe be clearer that it's not a direct offering of the freqtrade open source project.
