### ISSUE TITLE
Pairlist Handlers

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8649]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.2 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Let's say, this is part of my pairlist handler:

`    {
      "method": "RangeStabilityFilter",
      "lookback_days": 2,
      "max_rate_of_change": 0.15,
      "refresh_period": 1800
    },`
    
I would only have pairs with a max. rate of change of 15% within the last 2 days.

I my understanding this following element at the end of the file has no additional impact, since I don't care, what took place in the last 5 minutes within the same range. I already know the development of the whole last 2 days in the range:

`    {
      "method": "RangeStabilityFilter",
      "lookback_timeframe": "1m",
      "lookback_period": 5,
      "max_rate_of_change": 0.15,
      "refresh_period": 300
    }`
    
In fact this element reduces my whitelist with about 50% of the pairs.
I look forward to your feedback.

Last minute update:
(I just made the test with lookback timeframe of 1h, period of 5, in the same range, and it reduces the whitelist by the same amount of pairs)

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
I'm not entirely sure what your question is in this issue.

you've got 2 different pairlists - and they behave differently? (i'd assume they do - it's a different config) ? 
or what exactly is the question?

**Comment by myNextCoder** [comment]
I have one volume pairlist. And I checked the last 2 days with a range stability filter. And then I added a shorter range stability period with a different lookback timeframe, but for testing, I took the same range. Due to this same range, and even a shorter lookback time (less than 2 days in total), this should not have any influence on the resulting whitelist. But it has reduced my whitelist by about 50% of the elements.

**Comment by xmatthias** [comment]
well RangeStabilityFilter has a  default for min_rate_of_change of 0.01 - which is applied whenever this item is missing in the config.

A configuration of `"lookback_timeframe": "1m", "lookback_period": 5` (your second setting) will therefore throw out every pair that didn't move by at least 1% in the last 5 minutes.

It's kindof expected that this will be fewer pairs than pairs that moved at least 1% in the last 48 hours (your first config) - and i'm honestly surprised it's only reducing your pairlist by 50% and not more.

**Comment by myNextCoder** [comment]
Currently I am about to test, since "lookback_days": and "lookback_timeframe": "1d" with the corresponding number of days, does not give the same amount of pairs in the whitelist, even with a range number higher than 0.01. I let you know, as soon as I gather out 'the missing link'.

**Comment by myNextCoder** [comment]
I send you two files, only with the pairlist handler. Both are managing the volatility filter for the last 8 days. With two different notations. In my case, the whitelist generated with the first version is not equal with the one generated with the second one. What do you think is the reason for the difference?

[jsonfiles.zip](https://github.com/freqtrade/freqtrade/files/11485082/jsonfiles.zip)

**Comment by xmatthias** [comment]
I'd apreciate to not use zip files if it's really just a partial config that can be incorporated as code block here.
That'll simplify working with it a lot (no download / unzip / ...).

---

Are you sure you know **what** you're actually asking?

until now - we've looked at RangeStabilityFilter - now in the files, the only thing different is VolatilityFilter.
On top fo that - it's using `lookback_timeframe` - which is neither documented (nor supported) by VolatilitFilter.

You're however using filters like SpreadFilter and ShuffleFilter.

`SpreadFilter` is based on up to the second ticker data (so a subsequent entry will have different data as it's base as orderbooks constantly move).
`ShuffleFilter` will shuffle pairs - so having the pairlist filtered diferently is by design in this case.

**Comment by myNextCoder** [comment]
The only important thing in my questions is the notation of the look back time. It seems after my tests, that the system does not filter out pairs equally for lookback_days versus lookback_period, even when the amount of time in total is the same. So my files are containing 8 lookback_days versus timeframe 1d (with period 8). Each of the files contain one kind of the notation. Both files are looking 8 days into the past. The remaining part oft the files is the same, as well as my remaining config. I have not yet understood, why the two resulting whitelists do not contain the same amount of elements. The two versions are simply looking 8 days into the past 'in a different way', as mentioned above.

**Comment by xmatthias** [comment]
You're focusing on the **wrong**  element of your pairlist. You also can't reliably do such a test with 5 different filters applied. Unless you understand how each works (you apparently don't) - you should focus on one filter at a time, trying to understand the impact it has).

`lookback_timeframe` is **not** a relevant element of `VolatilityFilter`. It's not configurable, and will always be 1d.
You can put it on VolatilityFilter 100 times (or set it to 1h - it'll still be ignored - as it's not a setting this filter has).

Based on your config, it's most likely the `SpreadFilter` that will cause pairs to be filtered out differently (look at any orderbook, spread will change every other second) - and it's ShuffleFilter that will cause different sorting.

**Comment by myNextCoder** [comment]
If lookback_timeframe is not configurable for VolatilityFilter (or even for RangeStabilityFilter), everything is clear. As I work with Freqtrade, using an element in a context, which I cannot use, the bot usually stops. Since the system was running in our example, I was sure, it works. So I will only use lookback_days from now on.

**Comment by xmatthias** [comment]
Not all Filters support the same settings necessarily. 
we have the  [pairlist documentation](https://www.freqtrade.io/en/stable/plugins/#available-pairlist-handlers) - which documents all possible keys per pairlist handler. 
If a key is NOT there - it'll not be available. We aim to have keynames to be mostly aligned - but can't guarantee every key is used by every handler.

---

while we do validate the configuration for valid settings - we don't actually restrict the configuration to only contain settings that are valid - which would restrict some usecases where additional keys are kept in the configuration and red by the strategy.

you could (for example) add `"hello":"world"` at any point in the configuration - as long as the syntax is still valid jsonc (json with comments) - it'll load and work.

That's different from setting `"stake_currency": "world"`. stake_currency is a known setting - and `"world"` is not a valid entry for this.

**Comment by myNextCoder** [comment]
I understand, usually my configs are 'clean', since I copy and paste them, by only alter the required part.
