### ISSUE TITLE
Place an order at a different price

### ISSUE THREAD

**Issue by bit-storm** [freqtrade/freqtrade#8655]
Operating system: linux ubuntu 20
Python Version: 3.8
CCXT version: 2.5.12
Freqtrade Version: 2022.12

Is it possible for me to place my order at a price other than the current price?
For example, I receive a buy signal. The current price is 100, but I want to place an order at the price of 95.
How can this be done?

Also, I want my order to be closed after 10 minutes of not being filled. Do this with:

"ccxt_config": {
        "enableRateLimit": true,
      },
      "unfilledtimeout.entry": 600,

I will do . is it right ?

thank you

**Comment by xmatthias** [comment]
you can use [pricing callbacks](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-price-rules) to define custom prices (for both entry/exit, or just for one side).

Your timeout config is definitely wrong. the "." means it's a sub-dictionary, so the key  is not `unfilledtimeout.entry`.

something like the following should work (unit can be in minutes or seconds - but numbers need to obviously match that).

```
"unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    }
```

For custom timeouts (depending on "whatever" condition) - there's [timeout callbacks](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-timeout-rules)
