### ISSUE TITLE
FreqaiRL custom loss function completely ignored

### ISSUE THREAD

**Issue by Silur** [freqtrade/freqtrade#8657]
## Describe your environment

  * Operating system: Arch linux
  * Python Version: Python 3.10.10
  * CCXT version: ccxt==3.0.106)
  * Freqtrade Version: freqtrade docker-2023.5.dev-2ab73248
  

## Describe the problem:

Creating a custom RL loss function as per the documentation:

```python
from freqtrade.freqai.prediction_models.ReinforcementLearner import ReinforcementLearner
from freqtrade.freqai.RL.Base5ActionRLEnv import Actions, Base5ActionRLEnv, Positions

    class MyCoolRLModel(ReinforcementLearner):
        class MyRLEnv(Base5ActionRLEnv):
            def calculate_reward(self, action: int) -> float:
                return 0.0
```

and running it with 
```bash
freqtrade trade --freqaimodel MyCoolRLModel --config config.json --strategy SomeCoolStrat
```

Still uses the `calculate_reward`, function from the parent `Base5ActionRLEnv` model, as seen in tensorboard and the training logs (episode rewards are constantly varying to non-zero values)

**Comment by xmatthias** [comment]
I hope your indentation is actually different?

having the class indented as shown above should pretty much lead to not being able to load that file.


another common problem is with duplicate classnames.
what's the output of `freqtrade list-freqaimodels`? (it'll show if a duplicate name is used, see below).

![image](https://github.com/freqtrade/freqtrade/assets/5024695/52cf841b-5dc4-4eaa-810e-ec6b6cef29f0)

**Comment by xmatthias** [comment]
Using your file (fixing indents) - i get this, which seems correct (output is always 0).

![image](https://github.com/freqtrade/freqtrade/assets/5024695/f420fcb5-9ee8-448a-977b-d11c4ec47c8d)


the file now looks like this (fixed indents only): 

``` python
from freqtrade.freqai.prediction_models.ReinforcementLearner import ReinforcementLearner
from freqtrade.freqai.RL.Base5ActionRLEnv import Actions, Base5ActionRLEnv, Positions

class MyCoolRLModel(ReinforcementLearner):
    class MyRLEnv(Base5ActionRLEnv):
        def calculate_reward(self, action: int) -> float:
            return 0.0

```

And the output of the command i asked above:

![image](https://github.com/freqtrade/freqtrade/assets/5024695/9b8388b6-c2cc-4cb4-83b6-1356e1644d15)
(output actually continues below but is irrelevant)

**Comment by xmatthias** [comment]
I can't really recreate your problem (it's working fine when i try) - and we didn't have any further response, i'll therefore close this.

Feel free to comment below / reopen if it's still unclear.
