### ISSUE TITLE
how can I save kline status while placing an order or exist an order.

### ISSUE THREAD

**Issue by thunderwin** [freqtrade/freqtrade#8662]
how can I save kline status while placing an order or exist an order.
cause I need to check the details of DateFrame..

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

This also applies to questions - as the answer can vary if you're using an old version.

---

In theory, you can store it in the strategy as shown [in the documentation](https://www.freqtrade.io/en/stable/strategy-advanced/#storing-information).
It's volatile, so a restart will start empty with this (therefore handle this case appropriately).

In practice, you should use the above very carefully, as it can lead to a memory leak if not done carefully.

In almost all cases, the method shown for [dataframe access](https://www.freqtrade.io/en/stable/strategy-advanced/#dataframe-access) will work just fine.
While the "opening" candle can age out - it's more reliable than the "storing information" part.
