### ISSUE TITLE
Use all available capital

### ISSUE THREAD

**Issue by Cazs03** [freqtrade/freqtrade#8663]
I am reviewing the documentation, but it is not very clear to me, how to use all the available capital
  "stake_amount": "unlimited",?
  These are the parameters I have now
   _"max_open_trades": 5,
  "stake_currency": "USDT",
  "stake_amount": 0.05,
  "tradable_balance_ratio": 0.99,
  "fiat_display_currency": "USD",
  "amount_reserve_percent": 0.05,
  "available_capital": 1000,
  "amend_last_stake_amount": false,
  "last_stake_amount_min_ratio": 0.5,
  "dry_run": true,
  "dry_run_wallet": 1000,_

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

For your case (dry-run),  the default options will most likely suffice.
As the [documentation](https://www.freqtrade.io/en/stable/configuration/#assign-available-capital) points out - `available_capital ` is incompatible with `tradable_balance_ratio`.

``` jsonc
{
  "max_open_trades": 5,
  "stake_currency": "USDT",
  "stake_amount": "unlimited",
  "tradable_balance_ratio": 0.99,
  "fiat_display_currency": "USD",
  "dry_run": true,
  "dry_run_wallet": 1000,
// ...
}
```

that simple config will give you 5 open trades, which will split the 1000$ (so each trade is ~200$ to start with - but stake-sizes will grow if your bot makes profits).
it'll keep 1% spare (`"tradable_balance_ratio": 0.99` -> so you'll trade 990$) for eventual fees. 
now in dry-run that's not relevant - but it can be for live, so i'd suggest to keep this at the default of 1%.

`available_capital` should only be set if you're running multiple bots (or would like the bot to restrict to a fixed value in the account).
