### ISSUE TITLE
SaxoBank API integration

### ISSUE THREAD

**Issue by jothi-devhub** [freqtrade/freqtrade#8665]
## Describe your environment
  * Operating system: ubuntu 18.0
  * Python Version: 3.6
  * CCXT version: 2 
  * Freqtrade Version: 0.17.1
  
## Your question
I am trying integrate Saxo Open API to FreqTrade.As part of this I need to add the api to CCXT library need help Please review here [Forked_ccxt](https://github.com/jothi-devhub/ccxt) and provide your suggestions.

**Comment by xmatthias** [comment]
As a quick pointer / headsup - ccxt's python version is transpiled (in recent versions from typescript) - so to have any change accepted to ccxt, it'll have to be the typescript version. 
the Python version is auto-generated by CI, and contributors doing changes to the python files directly are usually asked to remove these, and do the changes in the typescript version, so all users can benefit from the changes done.

That's however as far as i'll go with this topic.

---

If you're trying to contribute something to the ccxt library and have problems / need help, then please ask for help in the [ccxt repository](https://github.com/ccxt/ccxt).
You should also open an issue there before doing any work, to see if they're actually interested in getting non-crypto exchanges added, which will avoid frustration and wasted work if they are not interested.

I don't have the capacity nor interest to review random changes (on exchanges i never heard about), which may (or may not) actually be contributed to the actual upstream project.

**Comment by jothi-devhub** [comment]
Hi @xmatthias  

They trade Cryptos as well please refer below link 

https://www.home.saxo/campaigns/cryptocurrencies

https://www.home.saxo/products/crypto

Its a European thinggy

**Comment by xmatthias** [comment]
Even better - that makes it spot-on for ccxt.

doesn't change the fact that this is the wrong repository for that :laughing:
