### ISSUE TITLE
Bots sharing same sub account on futures

### ISSUE THREAD

**Issue by polyvios-bc** [freqtrade/freqtrade#8666]
## Your question

Can you have multiple bots sharing the same sub-account on Binance Futures (same api key)? 
Tried something like that and i think orders are messed up between bots.

**Comment by stash86** [comment]
I have done that for months and never have issues. Of course, be careful that the liquidation calculation might be slightly wrong, hence in the docs, it's not recommended to use more than 1 bot on single futures account

**Comment by xmatthias** [comment]
If you have access to subaccounts, theres not really a reason why you should do that.
An additional subaccount wont cost you anything, while keeping everything separate.

If you do, you need separate databases, separate telegram bots (if you use telegram), and you need to configure `available_capital` so the bots dont touch the other balances.


> Of course, be careful that the liquidation calculation might be slightly wrong, hence in the docs, it's not recommended to use more than 1 bot on single futures account

That will be true only when more than one bot holds the same asset. If you use completely separate pairlists, that shouldn't be an issue.

**Comment by polyvios-bc** [comment]
Yes i am talking for bots sharing the same sub-account and also trading same assets on binance futures. So what i have noticed is that when they have positions open for the same pair there is probably an issue with positions. plus i see an order that belong on lets say bot-a been on bot-b order table. So wanted to clarify if thats expected . I am going to use different sub accounts from now on

**Comment by xmatthias** [comment]
> plus i see an order that belong on lets say bot-a been on bot-b order table

Then you've probably misconfigured your bots and are using the same database.
We have a [guide to run multiple instances of freqtrade](https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade) - which should help with this.

**Comment by polyvios-bc** [comment]
No they are not using the same database they are running on different servers and each one is using its own sqlite database . I will give you an example with what i mean because i have the feeling is caused because of positions been messed up so when you try to force exit you see unexpected behavior and orders that seems dont belong to original trade.

**Comment by polyvios-bc** [comment]
[a1_01_orders.csv](https://github.com/freqtrade/freqtrade/files/11523972/a1_01_orders.csv)
[a1_01_trades.csv](https://github.com/freqtrade/freqtrade/files/11523973/a1_01_trades.csv)
[a1_02_orders.csv](https://github.com/freqtrade/freqtrade/files/11523974/a1_02_orders.csv)
[a1_02_trades.csv](https://github.com/freqtrade/freqtrade/files/11523975/a1_02_trades.csv)
[a1_03_orders.csv](https://github.com/freqtrade/freqtrade/files/11523976/a1_03_orders.csv)
[a1_03_trades.csv](https://github.com/freqtrade/freqtrade/files/11523977/a1_03_trades.csv)

So those are the db files from three bots for a specific pair  "TRX/USDT:USDT" they all use the same sub-account. So pay attention on trade_id 232 on a1_02 bot. There is an order id = 523 with ft_amout = 392791.0 which seems as amount is from bot a1_01 with trade_id = 112. 
Similarly you can see on bot a1_03 that the trade_id =28 has amount 356850.0 and again that amount appears on a1_02 order with id 523

So what I am saying is that amounts seems to be messed up because of positions been wrong and sharing the same sub-account

**Comment by xmatthias** [comment]
please use show-trades to provide trade data. Reading through csv files is quite cumbersome, and won't allow to import it back again.

Please provide the output of the following command for the affected trade:
`freqtrade show-trades --db-url sqlite:///<trades.sqlite> --print-json --trade-ids <tradeid>` 
Please use a "details block" to keep the issue itself kindof readable (see below for details on how to do that). 

<details>
<summary>Expand to see how to do details blocks</summary>

```
<details>
<summary>Expand full </summary>
(wrap in tripple ticks `)
Trades output ...
</details>
```
</details>

**Comment by xmatthias** [comment]
> I have done that for months and never have issues. Of course, be careful that the liquidation calculation might be slightly wrong, hence in the docs, it's not recommended to use more than 1 bot on single futures account

Thinking about this again, i think you've been very lucky that no trades overlapped (in opposing direction).
I think you'll have problems in this scenario if one bot goes long, and the other short on the same pair - where they'd "eat" into each other's positions - so your final position will be something in between - with neither bot being able to sell.

It'll depend on the strategies, obviously - but it's not something i'd recommend or try to support (there's a good reason we put the message to the docs - liquidation calculation is just one of these reasons)

**Comment by stash86** [comment]
Agree, hence I put 1 account for long only and another for short only

**Comment by polyvios-bc** [comment]
Here are the outputs from the command you said. However I can see that outcome doesn't show ft_amount which is also something that shows the issue between trade_id 112 and trade_id 232. My csv files are showing this.

<details>
<summary>a1_01 trade 112</summary>

```
[{
	"trade_id": 112,
	"pair": "TRX/USDT:USDT",
	"base_currency": "TRX",
	"quote_currency": "USDT",
	"is_open": false,
	"exchange": "binanceusdm",
	"amount": 392791.0,
	"amount_requested": 392791.66986684,
	"stake_amount": 5536.781936,
	"max_stake_amount": 27683.90968,
	"strategy": "Anton1",
	"enter_tag": null,
	"timeframe": 60,
	"fee_open": 0.00027037037037037036,
	"fee_open_cost": 7.4849089134814815,
	"fee_open_currency": "USDT",
	"fee_close": 0.0003,
	"fee_close_cost": 8.313398460000002,
	"fee_close_currency": "USDT",
	"open_date": "2023-05-16 22:29:13",
	"open_timestamp": 1684276153839,
	"open_rate": 0.07048,
	"open_rate_requested": 0.07048,
	"open_trade_value": 27691.39458891,
	"close_date": "2023-05-17 03:18:47",
	"close_timestamp": 1684293527284,
	"realized_profit": 11.69703957,
	"realized_profit_ratio": 0.0021120351184268312,
	"close_rate": 0.07055,
	"close_rate_requested": 0.07056,
	"close_profit": 0.0021120351184268312,
	"close_profit_pct": 0.21,
	"close_profit_abs": 11.69703957,
	"trade_duration_s": 17373,
	"trade_duration": 289,
	"profit_ratio": 0.0021120351184268312,
	"profit_pct": 0.21,
	"profit_abs": 11.69703957,
	"exit_reason": "force_exit",
	"exit_order_status": "closed",
	"stop_loss_abs": 0.06626,
	"stop_loss_ratio": -0.3,
	"stop_loss_pct": -30.0,
	"stoploss_order_id": null,
	"stoploss_last_update": null,
	"stoploss_last_update_timestamp": null,
	"initial_stop_loss_abs": 0.06626,
	"initial_stop_loss_ratio": -0.3,
	"initial_stop_loss_pct": -30.0,
	"min_rate": null,
	"max_rate": 0.0,
	"leverage": 5.0,
	"interest_rate": 0.0,
	"liquidation_price": 0.0578424065,
	"is_short": false,
	"trading_mode": "futures",
	"funding_fees": 0.0,
	"open_order_id": null,
	"amount_precision": 0.0,
	"price_precision": 5.0,
	"precision_mode": 2,
	"orders": [{
			"amount": 392791.0,
			"safe_price": 0.07048,
			"ft_order_side": "buy",
			"order_filled_timestamp": 1684293377088,
			"ft_is_entry": true,
			"pair": "TRX/USDT:USDT",
			"order_id": "9667183921",
			"status": "closed",
			"average": 0.07048,
			"cost": 27683.90968,
			"filled": 392791.0,
			"is_open": false,
			"order_date": "2023-05-16 22:29:13",
			"order_timestamp": 1684276153835,
			"order_filled_date": "2023-05-17 03:16:17",
			"order_type": "limit",
			"price": 0.07048,
			"remaining": 0.0
		},
		{
			"amount": 392791.0,
			"safe_price": 0.07058,
			"ft_order_side": "sell",
			"order_filled_timestamp": null,
			"ft_is_entry": false,
			"pair": "TRX/USDT:USDT",
			"order_id": "9669926380",
			"status": "open",
			"average": 0.07058,
			"cost": 23890.34188,
			"filled": 338486.0,
			"is_open": true,
			"order_date": "2023-05-17 03:18:02",
			"order_timestamp": 1684293482269,
			"order_filled_date": null,
			"order_type": "limit",
			"price": 0.07058,
			"remaining": 54305.0
		},
		{
			"amount": 392791.0,
			"safe_price": 0.07055,
			"ft_order_side": "sell",
			"order_filled_timestamp": 1684293527034,
			"ft_is_entry": false,
			"pair": "TRX/USDT:USDT",
			"order_id": "9669932969",
			"status": "closed",
			"average": 0.07055,
			"cost": 27711.32852,
			"filled": 392791.0,
			"is_open": false,
			"order_date": "2023-05-17 03:18:47",
			"order_timestamp": 1684293527036,
			"order_filled_date": "2023-05-17 03:18:47",
			"order_type": "market",
			"price": 0.07055,
			"remaining": 0.0
		}
	]
}]
```

</details>

<details>
<summary>a1_02 trade 232</summary>

```
[{
	"trade_id": 232,
	"pair": "TRX/USDT:USDT",
	"base_currency": "TRX",
	"quote_currency": "USDT",
	"is_open": true,
	"exchange": "binanceusdm",
	"amount": 35941.0,
	"amount_requested": 406050.42404381,
	"stake_amount": 510.649728,
	"max_stake_amount": 28845.792,
	"strategy": "Anton1",
	"enter_tag": null,
	"timeframe": 60,
	"fee_open": 0.00016818181818181835,
	"fee_open_cost": 0.4294099985454549,
	"fee_open_currency": "USDT",
	"fee_close": 0.00025897435897435884,
	"fee_close_cost": 5.7848062,
	"fee_close_currency": "USDT",
	"open_date": "2023-05-17 02:00:09",
	"open_timestamp": 1684288809455,
	"open_rate": 0.07104,
	"open_rate_requested": 0.07104,
	"open_trade_value": 2553.67805,
	"close_date": null,
	"close_timestamp": null,
	"realized_profit": -176.78619666,
	"realized_profit_ratio": -0.03520125,
	"close_rate": null,
	"close_rate_requested": 0.07057,
	"close_profit": -0.03520125,
	"close_profit_pct": -3.52,
	"close_profit_abs": -178.50474059,
	"trade_duration_s": null,
	"trade_duration": null,
	"profit_ratio": -0.03520125,
	"profit_pct": -3.52,
	"profit_abs": -178.50474059,
	"exit_reason": "trailing_stop_loss",
	"exit_order_status": "",
	"stop_loss_abs": 0.07277,
	"stop_loss_ratio": -0.002,
	"stop_loss_pct": -0.2,
	"stoploss_order_id": null,
	"stoploss_last_update": null,
	"stoploss_last_update_timestamp": null,
	"initial_stop_loss_abs": 0.06678,
	"initial_stop_loss_ratio": -0.3,
	"initial_stop_loss_pct": -30.0,
	"min_rate": 0.06993,
	"max_rate": 0.07279,
	"leverage": 5.0,
	"interest_rate": 0.0,
	"liquidation_price": 0.0578704065,
	"is_short": false,
	"trading_mode": "futures",
	"funding_fees": 0.0,
	"open_order_id": null,
	"amount_precision": 0.0,
	"price_precision": 5.0,
	"precision_mode": 2,
	"orders": [{
			"amount": 406050.0,
			"safe_price": 0.07104,
			"ft_order_side": "buy",
			"order_filled_timestamp": 1684288828133,
			"ft_is_entry": true,
			"pair": "TRX/USDT:USDT",
			"order_id": "9669192365",
			"status": "closed",
			"average": 0.07104,
			"cost": 28845.792,
			"filled": 406050.0,
			"is_open": false,
			"order_date": "2023-05-17 02:00:09",
			"order_timestamp": 1684288809451,
			"order_filled_date": "2023-05-17 02:00:28",
			"order_type": "limit",
			"price": 0.07104,
			"remaining": 0.0
		},
		{
			"amount": 13259.0,
			"safe_price": 0.0712,
			"ft_order_side": "sell",
			"order_filled_timestamp": 1684350704062,
			"ft_is_entry": false,
			"pair": "TRX/USDT:USDT",
			"order_id": "9673979039",
			"status": "closed",
			"average": 0.0712,
			"cost": 944.0408,
			"filled": 13259.0,
			"is_open": false,
			"order_date": "2023-05-17 19:11:44",
			"order_timestamp": 1684350704063,
			"order_filled_date": "2023-05-17 19:11:44",
			"order_type": "limit",
			"price": 0.07119,
			"remaining": 0.0
		},
		{
			"amount": 356850.0,
			"safe_price": 0.07057,
			"ft_order_side": "sell",
			"order_filled_timestamp": 1684592006656,
			"ft_is_entry": false,
			"pair": "TRX/USDT:USDT",
			"order_id": "9689708114",
			"status": "closed",
			"average": 0.07057,
			"cost": 25182.9045,
			"filled": 356850.0,
			"is_open": false,
			"order_date": "2023-05-19 18:43:35",
			"order_timestamp": 1684521815169,
			"order_filled_date": "2023-05-20 14:13:26",
			"order_type": "limit",
			"price": 0.07057,
			"remaining": 0.0
		}
	]
}]
```

</details>


<details>
<summary>a1_03 trade 28</summary>

```
[{
	"trade_id": 28,
	"pair": "TRX/USDT:USDT",
	"base_currency": "TRX",
	"quote_currency": "USDT",
	"is_open": true,
	"exchange": "binanceusdm",
	"amount": 356850.0,
	"amount_requested": 356850.94561401,
	"stake_amount": 5048.7138,
	"max_stake_amount": 25243.569,
	"strategy": "Anton1",
	"enter_tag": null,
	"timeframe": 60,
	"fee_open": 0.00020434782608695656,
	"fee_open_cost": 5.158468447826087,
	"fee_open_currency": "USDT",
	"fee_close": 0.00020434782608695656,
	"fee_close_cost": null,
	"fee_close_currency": null,
	"open_date": "2023-05-19 15:27:30",
	"open_timestamp": 1684510050733,
	"open_rate": 0.07074,
	"open_rate_requested": 0.07074,
	"open_trade_value": 25248.72746845,
	"close_date": null,
	"close_timestamp": null,
	"realized_profit": 0.0,
	"realized_profit_ratio": null,
	"close_rate": null,
	"close_rate_requested": null,
	"close_profit": null,
	"close_profit_pct": null,
	"close_profit_abs": null,
	"trade_duration_s": null,
	"trade_duration": null,
	"profit_ratio": null,
	"profit_pct": null,
	"profit_abs": null,
	"exit_reason": null,
	"exit_order_status": null,
	"stop_loss_abs": 0.07293,
	"stop_loss_ratio": -0.002,
	"stop_loss_pct": -0.2,
	"stoploss_order_id": null,
	"stoploss_last_update": null,
	"stoploss_last_update_timestamp": null,
	"initial_stop_loss_abs": 0.0665,
	"initial_stop_loss_ratio": -0.3,
	"initial_stop_loss_pct": -30.0,
	"min_rate": 0.07016,
	"max_rate": 0.07295,
	"leverage": 5.0,
	"interest_rate": 0.0,
	"liquidation_price": 0.057756312,
	"is_short": false,
	"trading_mode": "futures",
	"funding_fees": 0.75422798,
	"open_order_id": null,
	"amount_precision": 0.0,
	"price_precision": 5.0,
	"precision_mode": 2,
	"orders": [{
		"amount": 356850.0,
		"safe_price": 0.07074,
		"ft_order_side": "buy",
		"order_filled_timestamp": 1684510070906,
		"ft_is_entry": true,
		"pair": "TRX/USDT:USDT",
		"order_id": "9689146780",
		"status": "closed",
		"average": 0.07074,
		"cost": 25243.569,
		"filled": 356850.0,
		"is_open": false,
		"order_date": "2023-05-19 15:27:30",
		"order_timestamp": 1684510050727,
		"order_filled_date": "2023-05-19 15:27:50",
		"order_type": "limit",
		"price": 0.07074,
		"remaining": 0.0
	}]
}]
```

</details>

**Comment by xmatthias** [comment]
I'm not entirely sure what i'm looking for as you're saying that the "issue" is showing in csv files.

if i compare trades 112 and 232, then they both have 3 orders (1 buy, 2 sells).

for 112, all orders are for an amount of 392791 (ft_amount, as well as the effective amount). The decimals are rounding, which will be removed once on the exchange, so they're really irrelevant.

for 232, the buying amount is 406050 - which is also part of the first sell order which  only filled for 13259.
the 3rd order is then for 392791 TRX, which corresponds exactly to 406050 - 13259 - or "initial amount - filled sell order.

The amounts (and/or ft_amount) therefore seems perfectly fine - so i don't really see how the orders are messed up exactly (your csv files include orders for 2 trades each, so maybe that's what caused some confusion??)

---

The only thing that's slightly odd is the fact that the trade 112 still has an open order (while there's no assets anymore) - but i it's not really clear if that's due to running 2 bots on the same account - but rather something else (logs from around that time would tell what caused this).

If you've still got the logs from that trade (112, around the time (and a bit before / after) when these 2 sell orders happened) - i'd be happy to look at it.

---

Despite that - the restriction of "one bot per futures account" still holds, and is not something we'll go away from.
it WILL cause problems if one bot goes long, while the other goes short on the same pair (as explained above) - so the statement in the docs is valid, and this issue / thinking about it further, strengthens this point.

**Comment by polyvios-bc** [comment]
Yes I see what you mean and I guess the issue is what you said sharing the same account on futures and thats why the order been still open when it shouldnt . Thanks for checking this and will follow that restriction
