### ISSUE TITLE
any extension to support bitget trading

### ISSUE THREAD

**Issue by vst212** [freqtrade/freqtrade#8668]
any extension to support bitget, many thanks as seldom saw that

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

In theory, freqtrade supports every exchange ccxt supports, which would also include bitget.

Now you're the first to ask for that (at least as far as i remember), so you're probably the first to have a look at this.
we have a rough guideline on things to check in the [contributors section of the documentation](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip).
While it's probably not complete, it should give you a good idea if the exchange will work for spot trading.

If you encounter specific problems, we're happy to assist up to a certain point - but the expectation for new exchanges is that you're doing the legwork / most of the testing work - which also assumes that you're somewhat familiar with python / testing/debugging things in python.
If you're new to python / development - you're probably better of with one of the supported exchanges.
