### ISSUE TITLE
New modifications breaks the binance/or any other futures trading capability

### ISSUE THREAD

**Issue by richardjozsa** [freqtrade/freqtrade#8680]
The issue itself:

I'm using freqtrade standard docker images with the develop image, it can not find Binance as exchange so it is using a general one instead ( and lately it will break the bot cuz the general resolver does not support futures). 
![image](https://github.com/freqtrade/freqtrade/assets/38407205/7349450d-0e56-48d6-86b3-6475af712be9)

If I use the same setup, but with stable docker image, the error is not there, so I assume the changes what has been made lately broken the futures resolving. 

https://github.com/freqtrade/freqtrade/blob/5b29e710dcb033cf9edeef2bd943725e75b3749d/freqtrade/resolvers/exchange_resolver.py#L39-L42

-----------Issue template

## Describe your environment

  * Operating system: Docker , original freqtradeorg/freqtrade:develop and than freqtradeorg/freqtrade:stable
  * Python Version: _____ (`python -V`)
  * CCXT version: 3.1.5
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

See above.

### Steps to reproduce:

  1. Use isolated futures on binance in LIVE mode, in dry run you won't see it. :) 
  2. Use the original freqtrade image from docker hub, try the develop -> it will break.
  3. Than try the stable image -> it will work
  
### Observed Results:

  * What happened? - It breaks because it can not resolve the exchange.
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2023-05-22 19:31:12,384 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-05-22 19:31:12,388 - freqtrade.exchange.exchange - INFO - Using CCXT 3.1.5
2023-05-22 19:31:12,388 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'enableRateLimit': False}
2023-05-22 19:31:12,394 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'enableRateLimit': False}
2023-05-22 19:31:12,399 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-05-22 19:31:18,187 - freqtrade.resolvers.exchange_resolver - INFO - No Binance specific subclass found. Using the generic class instead.
2023-05-22 19:31:18,188 - freqtrade.exchange.exchange - INFO - Using CCXT 3.1.5
2023-05-22 19:31:18,188 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'enableRateLimit': False}
2023-05-22 19:31:18,194 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'enableRateLimit': False}
2023-05-22 19:31:18,199 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2023-05-22 19:31:24,258 - freqtrade.commands.trade_commands - ERROR - Freqtrade does not support isolated futures on Binance
2023-05-22 19:31:24,259 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
  ```
Config:

```{
    "trading_mode": "futures",
    "new_pairs_days": 30,
    "margin_mode": "isolated",
    "max_open_trades": 10,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "dry_run_wallet": 10000,
    "tradable_balance_ratio": 1,
    "fiat_display_currency": "USD",
    "dry_run": false,
    "candle_type_def": "futures",
    
    "timeframe": "5m",
    "dataformat_ohlcv": "json",
    "cancel_open_orders_on_exit": true,
    "unfilledtimeout": {
        "entry": 5,
        "exit": 5
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {
            "enableRateLimit": false
            
        },
        "ccxt_async_config": {
            "enableRateLimit": false


            },
       "pair_whitelist": [
        
            
            "SOL/USDT:USDT",



            "SXP/USDT:USDT",

            "BAT/USDT:USDT",

            "ADA/USDT:USDT",
            "1INCH/USDT:USDT",
            "AXS/USDT:USDT",
            "LTC/USDT:USDT",

            "NEO/USDT:USDT",
            "ETC/USDT:USDT",

            "DASH/USDT:USDT"
            
            
           
            
            
        ],
        "pair_blacklist": []
    },
    "entry_pricing": {
        "price_side": "other",
        
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing": {
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1
    },
    "pairlists": [
        {
            "method": "StaticPairList"
        }
    ],
    "api_server": {
        "enabled": true,
        "listen_ip_address": ",
        "listen_port": ,
        "verbosity": "error",
        "enable_openapi": true,
        "jwt_secret_key": "",
        "CORS_origins": [""],
        "username": "", 
        "password": "", 
        "ws_token": ""
    },
    
    "force_entry_enable": true,
    "initial_state": "running",
    "internals": {
        "process_throttle_secs": 5
    },
    "telegram": {
        "enabled": true,
        "token": "",
        "chat_id": "",
          "notification_settings": {
            "status": "on",
            "warning": "on",
            "startup": "on",
            "buy": "silent",
            "sell": {
                "roi": "on",
                "emergency_sell": "on",
                "force_sell": "on",
                "sell_signal": "on",
                "trailing_stop_loss": "on",
                "stop_loss": "on",
                "stoploss_on_exchange": "on",
                "custom_sell": "on"
            },
            "buy_cancel": "on",
            "sell_cancel": "on",
            "buy_fill": "on",
            "sell_fill": "on",
            "protection_trigger": "off",
            "protection_trigger_global": "on"
        },
        "reload": true,
        "balance_dust_level": 0.01
    },
    
    "external_message_consumer": {
        "enabled": true,
        "producers": [
            {
                "name": "", // This can be any name you'd like, default is "default"
                "host": "", // The host from your producer's api_server config
                "port": , // The port from your producer's api_server config
                "secure": false, // Use a secure websockets connection, default false
                "ws_token": "" // The ws_token from your producer's api_server config
            }
        ],
        // The following configurations are optional, and usually not required
        // "wait_timeout": 300,
        // "ping_timeout": 10,
        // "sleep_time": 10,
        // "remove_entry_exit_signals": false,
        // "message_size_limit": 8
    },
    "bot_name": ""
}
```

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

The above info (your precise version) is interesting in 2 ways.
Resolving is working for me (both on local installation and with the latest develop image) - and it's initializing the exchange just once (yours is initializing the exchange twice - which clearly is not how freqtrade works, at least not on it's own).

For the moment, the base assumption therefore might be that it's something in your environment (either the strategy doing something odd, the config doing something odd - although i don't see how the config could cause this, or both) - as i cannot really recreate this.

**edit** It's also interesting that the first time, resolving seems to work fine and is using the correct exchange class (the "non-shown" log message is not from the exchange resolver).
so i assume the freqtrade internal version of initializing is working fine (which is also what i'm seeing) - so it'll be something in your environment/strategy/eventual modifications that cause this, most likely by initializing the exchange without having adapted to changes.
Please note: the exchange resolver is NOT a public / documented interface, so we'll not document / list changes to it, nor support it's use - as having 2 exchange instances around can cause problems, and is therefore an unsupported configuration.

**Comment by richardjozsa** [comment]
I added the issue template and my logs and config, if it helps. 

Sorry if I missunderstand the logs but: 

`freqtrade.exchange.exchange - INFO - Using Exchange "Binance"` <- this line in my logs says ,it is coming from exchange.exchange so it is this line -> https://github.com/freqtrade/freqtrade/blob/9ffdaceef3bbac11cff7078791c7667e3f513d73/freqtrade/exchange/exchange.py#L182

which means it is initialized once, it is just fails the resolver initialization `freqtrade.resolvers.exchange_resolver - INFO - No Binance specific subclass found. Using the generic class instead.`  
Which comes from here: https://github.com/freqtrade/freqtrade/blob/9ffdaceef3bbac11cff7078791c7667e3f513d73/freqtrade/resolvers/exchange_resolver.py#L46

So this check, fails because I don't get the log below` logger.info(f"Using resolved exchange '{exchange_name}'...")` : 
https://github.com/freqtrade/freqtrade/blob/9ffdaceef3bbac11cff7078791c7667e3f513d73/freqtrade/resolvers/exchange_resolver.py#L60C1-L64

**Comment by xmatthias** [comment]
the fact that you're getting to "Using Exchange" means you'll not hit the "specific subclass" case - not from this call, anyway - which suggests that the resolver is called twice - once with a "wrong" configuration.

As freqtrade (trade mode) does not do that - i'd suspect that it's due to something in the strategy - but that's obviously a suspicion.

**Comment by zafbangash** [comment]
Issue duplicated on new install / fresh install 
Both devel and stable 
On local machine and on digitalocean cloud Both running Ubuntu. 
dry run runs fine.  

Config and strategy are from the repo here. 

I don't have access to previous release(s) to compare. 

checked after commenting out the relevant section of exchange.py (line 691 - 703) :  the error went away but all pairs are removed .. ("Removed XXX/USDT:USDT from whitelist due to invalid ticker data: .... ) 

Please let me know if there is anything I can do to help isolating the problem.

**Comment by xmatthias** [comment]
Seems like a recent change in ccxt changed this - removing `fapiPrivateGetPositionsideDual`, and only keeping `fapiPrivateGetPositionSideDual`. We used the former - though the latter is available both in current and prior versions.

It's not breaking old versions as the "uppercase" variant was available there too.
