### ISSUE TITLE
Trading forex currency pairs

### ISSUE THREAD

**Issue by bit-storm** [freqtrade/freqtrade#8682]
Hello, thanks for your useful library.

My question is not directly related to the library and I am sorry for that because I did not find an answer for it.

Any way or idea to trade currencies like EUR/USD
GBP/USD
USD/JPY

Is there with your library?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Freqtrade does not directly provide ANY assets / pairs. 
It's therefore strongly dependent on the exchange you're using.

In theory, all exchanges that ccxt supports, will be viable for freqtrade as well (at least to some degree).
It's however focused around crypto markets / exchanges - so your success with this will depend on having one of the supported exchanges support such currencies.
While i know that some do - i don't think these markets are designed to actually be used for forex trading - but rather as "exchange coins to trade crypto" (they don't allow leverage, and as such, profits are WAY too low to be profitable on forex pairs.
