### ISSUE TITLE
Inquiry about adjust_stop_loss algorithm

### ISSUE THREAD

**Issue by thkwon9474** [freqtrade/freqtrade#8683]
Operating system: Ubuntu 22.04
Python Version: python -V 3.11
CCXT version: ccxt==2.6.26
Freqtrade Version: freqtrade 2023.1.dev-7092212ed
  
## Your question

Hello Team,

I'm wondering about adjust stoploss algorithm under 'trade_model.py'

As shown in the code below, there is a process of calculating leverage by dividing stoploss.

I think it need to calculating by multiplying, not dividing.

![image](https://github.com/freqtrade/freqtrade/assets/123524953/51436b51-99c1-458e-92e7-5da6076ae4c4)

**Comment by xmatthias** [comment]
No, why would it?

as the [stoploss documentation](https://www.freqtrade.io/en/stable/stoploss/) explains regarding leverage:

> Stoploss should be thought of as "risk on this trade" - so a stoploss of 10% on a 100$ trade means you are willing to lose 10$ (10%) on this trade - which would trigger if the price moves 10% to the downside.

the variable for stoploss in this case is a ratio (0.1 -> 10%).
if we assume we're trading at 10x leverage, then we'll need an effective stoploss of 1% (the pair moves 1% to the downside) to allow for a risk of 10% on the position.


 Dividing is therefore correct with 10% / 10x = 1% (it's actually `0.1 / 10 = 0.01`).

**Comment by thkwon9474** [comment]
Thank you for reply

I'm still wonder,,
For instance, assume the entry price is 100$ and the stop-loss price is 95$.

Applying x10 leverage and calculating on a price basis, the stop-loss price is $99.5.

(I know the current algorithms that work with the ratios stated in the manual, but I've calculated them with prices for convenience)

**Comment by xmatthias** [comment]
That's correct.
As defined in the documentation, it's a definition of risk on the invested stake, not about "price movement".

so let's assume you bought 1 COIN for 100$ at 10x. your actual position size is 1000$ (100$ * 10x).
to risk 5% - you'll need to get out of the trade when your loss exceeds 5$ of the invested capital - at which point, you'll be left with 95$ of your own capital (you lost 5$).

you'll therefore need to exit the trade once the value of the trade is <=995$ (value with leverage)- which at 10x leverage for 1 coin, is 99.5$ (price)
from a price perspective, that's a movement of 0.5% movement - or 0.005 - which comes out at a price of 99.5$.

This logic is also explained in the documentation - including a warning that tight stoplosses may be problematic with high leverage - as a 0.5% price movement is really "nothing" in most markets, and will probably shake you out pretty quickly.

**Comment by thkwon9474** [comment]
Thank u so much:)
