### ISSUE TITLE
Shorter informative timeframe than default one?

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8684]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.2 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Does Freqtrade handle a shorter informative timeframe correctly?
Let's say, my timeframe is 5m, can I place an informative timeframe of 1m in the same way, as I code a 1h version?
(In the common usage, this makes not to much sense, the reason is, that I have a complex 5m strategy template, so by adding 1m informative pairs, I am free to even trade the 1m timeframe without reinventing the wheel)

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Freqtrade itself won't limit this - but you'll have to handle the "dataframe combination" logic yourself - as you're effectively multiplying the base timeframe by 5 (going from 5m to 1m) (which will raise warnings / invalid dataframe modification errors).

If you can handle this (and compress the 5x 1m information into 1 line) - then sure - but it's up to you / the strategy to come up with that way - as it really doesn't make much sense.

if you're REALLY trying to run on 1m data, your base-timeframe should be 1m - then it's a common usecase, and something that can be easily accomplished with builtin functionality (including the informative decorator, or the helpers we provide for informative pair usage).

**Comment by myNextCoder** [comment]
I have a look, probably it isn't to much work, to implement my basic template as a real 1m version in addition, seems to be better, according to your post.

**Comment by xmatthias** [comment]
if you're using the `@informative` decorator, you can most likely just move your logic to a informative pair method (decorated wiht 5m) - and then use the 1m data for your further logic.

**Comment by myNextCoder** [comment]
I thank you for your input. Currently I have not used the decorator. I can probably replace my current 5m with the new 1m part. It seems, that I won't use a 5m informative part, but I have to take a look exactly.
