### ISSUE TITLE
ProfitDrawDownHyperOptLoss - Not corresponding to expectation

### ISSUE THREAD

**Issue by keithorange** [freqtrade/freqtrade#8685]
### Describe the problem:
This class does not optimize because a) it is multiplying dropdown by profit instead of subtracting it. Its much easier for if you take it to just subtract absolute drawdown from total_profit. b) calculate_max_drawdown()[5] is the relative_drawdown, while [0] is the absolute. 
```"""
ProfitDrawDownHyperOptLoss

This module defines the alternative HyperOptLoss class based on Profit &
Drawdown objective which can be used for Hyperoptimization.

Possible to change `DRAWDOWN_MULT` to penalize drawdown objective for
individual needs.
"""
from pandas import DataFrame

from freqtrade.data.metrics import calculate_max_drawdown
from freqtrade.optimize.hyperopt import IHyperOptLoss


# higher numbers penalize drawdowns more severely
DRAWDOWN_MULT = 0.075


class ProfitDrawDownHyperOptLoss(IHyperOptLoss):
    @staticmethod
    def hyperopt_loss_function(results: DataFrame, trade_count: int, *args, **kwargs) -> float:
        total_profit = results["profit_abs"].sum()

        try:
            max_drawdown_abs = calculate_max_drawdown(results, value_col="profit_abs")[5]
        except ValueError:
            max_drawdown_abs = 0

        return -1 * (total_profit * (1 - max_drawdown_abs * DRAWDOWN_MULT))
````

### Solution
Instead, this alternative achieves the intended results much better and can immeditley train a model from scratch instead of running into issues like before.
```# higher numbers penalize drawdowns more severely
DRAWDOWN_MULT = 0.5


class ProfitMinusDropdownHyperOptLoss(IHyperOptLoss):
    @staticmethod
    def hyperopt_loss_function(results: DataFrame, trade_count: int, *args, **kwargs) -> float:
        total_profit = results["profit_abs"].sum()

        try:
            max_drawdown_abs = calculate_max_drawdown(results, value_col="profit_abs")[0] # abs_drawdown
        except ValueError:
            max_drawdown_abs = 0

        return -1 * (total_profit -(max_drawdown_abs * DRAWDOWN_MULT))```

**Comment by xmatthias** [comment]
It may not fit your particular expectation of an optimized result - but that doesn't make it wrong - so i don't really see it that way.


Your "fix" is actually off completely (at least in a generalized context that extends beyond your particular strategy).
it's using the legacy method of drawdown calculation - which fails the moment you're no longer using uneven stakes (either through stake_amount=unlimited, and also when using custom_stake_amount (or position adjustments).


It's implementation (or rather, all usages of this) is deprecated, and should not be used as it's known to be wrong.
While i know it's still used in some places - these are known, and either marked as deprecated, or marked with a TODO to update to a different value.

---

The implementation is using [5] - which is `max_drawdown_rel`.
this is a relative profit (ratio) - so it'll return for example 0.2 (20%).

As such, the usage of `profit * (1 - 0.2)` (assuming no identifier) seems correct to me.
