### ISSUE TITLE
Missing 'orjson' import

### ISSUE THREAD

**Issue by richardjozsa** [freqtrade/freqtrade#8691]
We have a missing import here: 

https://github.com/freqtrade/freqtrade/blob/d4183b3fcbfba2977c19de1440c9e87885642d00/freqtrade/misc.py#LL10C1-L10C1

We use orjson to serialize dataframes to json (dataframe_to_json function), but it hasn't been imported. If it will be called it will cause very strange issues. I added the `import orjson` line to the file and the error is gone.

**Comment by xmatthias** [comment]
i'm not sure what error you've got - but misc.py (or `dataframe_to_json()`) is no longer using orjson, but it's been reverted to `pandas.to_json(orient='split')`.

The "orjson" need here was to workaround a memory leak only - so i'm not sure what exact error you're seeing, with what exact version - but i can't really follow why this might be a problem.

Maybe you have a stacktrace and version to look at this further?
