### ISSUE TITLE
Binance  PNL is incorrect 

### ISSUE THREAD

**Issue by yili1992** [freqtrade/freqtrade#8693]
## Describe your environment

  * Operating system: Ubuntu 20.04.4 LTS
  * Python Version: Python 3.10.10 (`python -V`)
  * CCXT version: ccxt==3.0.37 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.3 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  

## Describe the problem:

I found I get pnl from freqtrade is different with exchange pnl  in trade order.
from my image , Checking  TRX/USDT, freqtrade pnl is 1.005USDT, Binance pnl is 2.528USDT
![image](https://github.com/freqtrade/freqtrade/assets/3176589/c478fe06-bf31-4563-8dce-8c1c47d399b8)
![image](https://github.com/freqtrade/freqtrade/assets/3176589/1febb727-5034-4e75-bc98-643e3e073a39)

### Steps to reproduce:

  1. open Position History  in Binance,  Get Closing PNL for Each close order
  2. Compared with the close order profit in freqtrade

**Comment by xmatthias** [comment]
The most likely reason is fees - which binance is (in my opinion intentionally) hiding from the user, and is NOT factoring in into the pnl calculation (you're still paying them though).

Freqtrade's calculations do include fees - and on binance, it'll be something around 0.04% (per order) in the worst case (assuming you're not a vip user). [source](https://www.binance.com/en/fee/futureFee).

In the UI, the trade detail pane will include a "fee" section, which will show these explicitly.

 
---

To look at this further, please provide the output of the following command for the affected trade:
`freqtrade show-trades --db-url sqlite:///<trades.sqlite> --print-json --trade-ids <tradeid>` 
Please use a "details block" to keep the issue itself kindof readable (see below for details on how to do that). 

<details>
<summary>Expand to see how to do details blocks</summary>

```
<details>
<summary>Expand full </summary>
(wrap in tripple ticks `)
Trades output ...
</details>
```
</details>

**Comment by yili1992** [comment]
> 

Thanks your reply, you're right. binance position history not includes fee.  The fee is really expensive
