### ISSUE TITLE
if (pl.get('method') == 'StaticPairList' AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by peteblank** [freqtrade/freqtrade#8695]
## Describe your environment

  * Operating system: windows 11/wsl
  * Python Version: python 3.9.11 (`python -V`)
  * CCXT version: ccxt==3.1.5(`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.4(`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hello, I tried to run freqtrade, I made sure I put in the all the information in the config file but it's giving me errors. I don't want to post the entire config file obviously but this line in particular is giving me issues:
`
"pair_whitelist": [
            "BTC/USDT",
            "ETH/USDT",
            "LTC/USDT"
        ]
    },
    "pairlists": {
        "method": "StaticPairList",
        "pairs": [
            "BTC/USDT",
            "ETH/USDT",
            "LTC/USDT"
        ]
    },`
    I got the error in the title
    ` if (pl.get('method') == 'StaticPairList' AttributeError: 'str' object has no attribute 'get'`
    Thank you

**Comment by xmatthias** [comment]
pairlists is supposed to be an array of dictionaries, not a dictionary (as shown in the [documentation](https://www.freqtrade.io/en/latest/plugins/#full-example-of-pairlist-handlers).

so it should be something around ` "pairlists": [{ "method": "StaticPairList"},]` - assuming you're only using one pairlist.

i've added some different handling for this - so the error becomes clearer.

**Comment by peteblank** [comment]
I fixed it I think, I added the following to the pairlist:
`  "pairlists": [
        {"method": "StaticPairList"},
        {"method": "AgeFilter", "min_days_listed": 10},
        {"method": "PrecisionFilter"},
        {"method": "PriceFilter", "low_price_ratio": 0.01, "min_price": 0.00000010},
        {"method": "SpreadFilter", "max_spread_ratio": 0.005},
        {
            "method": "RangeStabilityFilter",
            "lookback_days": 10,
            "min_rate_of_change": 0.01,
            "refresh_period": 1440
        }
    ],`
    Based on one the examples, thank you. I think that's what fixed it.

**Comment by xmatthias** [comment]
You shouldn't use random pairlists - but use the pairlists you actually think you'll want to be using.
the example combines most available pairlists for demonstrative purposes - which doesn't necessarily make sense.
