### ISSUE TITLE
Issue with VolatilityFilter

### ISSUE THREAD

**Issue by ShaneOss** [freqtrade/freqtrade#8698]
Issue with the VolatilityFilter
VolatilityFilter - INFO - Removed KLAY/USDT from whitelist, because volatility over 3 days is: **nan** which is not in the configured range of 0.01-0.75

VolatilityFilter - INFO - Removed SUN/USDT from whitelist, because volatility over 3 days is: **nan** which is not in the configured range of 0.01-0.75

Config:
        {
            "method": "VolatilityFilter",
            "lookback_days": 3,
            "min_volatility": 0.01,
            "max_volatility": 0.75,
            "refresh_period": 43200
        },

Tested on Binance and Kucoin. It's causing no pairs to be added to whitelist to trade.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

**Comment by ShaneOss** [comment]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.10.9
  * CCXT version: ccxt==3.0.97
  * Freqtrade Version: freqtrade 2023.6.dev-df5e6409a
  
## Describe the problem:
VolatilityFilter was working and not recently.

*Explain the problem you have encountered*
Freqtrading stopped trading across multiple instances I have running that are using the VolatilityFilter.

### Steps to reproduce:
Enable dynamic pairlist with volatility filter.

Config:
{
"method": "VolatilityFilter",
"lookback_days": 3,
"min_volatility": 0.01,
"max_volatility": 0.75,
"refresh_period": 43200
},
  
### Observed Results:

  * What happened? Nothing gets added to the whitelist because of the nan result in the volatility filter.
  * What did you expect to happen? Volatility was calculated, result returned and depending on the result the pair may be added to the pair list.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
VolatilityFilter - INFO - Removed KLAY/USDT from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.01-0.75

VolatilityFilter - INFO - Removed SUN/USDT from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.01-0.75
  ```

**Comment by ShaneOss** [comment]
The NaN result is likely being produced by the line calculating the returns:

returns = (np.log(daily_candles.close / daily_candles.close.shift(-1)))

The shift(-1) method is shifting the close prices one day forward. This means that the last day's return is calculated as the log of (last day's close price / NaN), which results in a NaN value. This NaN value then propagates through the subsequent calculations.

To fix this, you should shift the data one day backward using shift(1), so that the last day's return is calculated as the log of (last day's close price / second to last day's close price), which will be a valid number.

Here's the corrected line of code:

returns = (np.log(daily_candles.close / daily_candles.close.shift(1)))

You should also adjust the line where NaN values are filled with 0:

returns.fillna(0, inplace=True)

You might want to drop the NaN values instead of replacing them with 0 because 0 could potentially affect the standard deviation calculation. Here's the adjusted line:

returns.dropna(inplace=True)

You should then check the code for further usage of the returns variable and make sure it can handle the NaN values correctly.

**Comment by xmatthias** [comment]
The direction of the shift is really irrelevant, as in the end, the average over all lines is taken (which implicitly ignores Na values).

the problem is a wrongly applied days offset - which caused the filter to only have 2 days of data, instead of the 3 required - resulting in a NaN calculation.
While i've also reversed the shift direction (shifting forward instead of back) - it's not something that makes any difference to this issue.

**Comment by ShaneOss** [comment]
Thanks @xmatthias
