### ISSUE TITLE
custom_stoploss logic unclear

### ISSUE THREAD

**Issue by IgnacioGoldman** [freqtrade/freqtrade#8699]
## Environment

  * Operating system: Ubuntu 22.04.1
  * Python Version: Python 3.10.6 (python -V)
  * Freqtrade Version: 2023.1 (freqtrade -V or docker compose run --rm freqtrade -V for Freqtrade running in docker)
  
## Question

For [this](https://www.freqtrade.io/en/2021.2/strategy-advanced/#time-based-trailing-stop) example, when it says that it will use the "initial" stoploss, is it because it has been initially set to 1? I.e.:
```
class myStrat(IStrategy):
...
stoploss = 1
...
```
Or when the function `custom_stoploss` returns 1, it logically means that it will keep using the initial?

Hopefully i'm being clear :D and thank you!

**Comment by froggleston** [comment]
The docs you are referencing are very outdated. The most recent docs: https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stoploss

`The stoploss price can only ever move upwards - if the stoploss value returned from custom_stoploss would result in a lower stoploss price than was previously set, it will be ignored. The traditional stoploss value serves as an absolute lower level and will be instated as the initial stoploss (before this method is called for the first time for a trade), and is still mandatory.`

**Comment by IgnacioGoldman** [comment]
Hi @froggleston,

I've also read that piece of documentation you've shared with me but still doesn't answer my question.

**Comment by xmatthias** [comment]
in all fairness, your question doesn't make too much sense, and the docs do explain behavior that custom-stoploss enacts.


the initial stoploss is always used as starting value.
custom-stop will only ever move the stoploss towards the current price (up for longs).
So returning a value like 1 from custom_stoploss will act as "no action" - as it only has the "power" to move the stoploss towards the current price (From a prior location).
