### ISSUE TITLE
Backtest Result Differs

### ISSUE THREAD

**Issue by as-ka-sha** [freqtrade/freqtrade#8709]
## Describe your environment

  * Operating system: Ubuntu 22.04 LTS
  * Python Version: 3.10.6
  * CCXT version: 3.0.103
  * Freqtrade Version: 2023.3

## Your question
I had a **static pair** list containing 34 crypto currency pairs. It was in a **random alphabetical order** , the fact that I'm unable to understand is that I ran the **exact same backtest** with **same data-range** (Downloaded) with the random alphabetical order and then again after sorting it in **alphabetical order**, the backtest results **differ** from each-other. 
Total Number of trades, win %, Loss, average profit %, Drawdown (everything in short) , which felt abnormal to me.
The **alphabetical order** decrised the total number of trades while increased the **WinRate and Dradown**
Can anyone here **help me understand** whats the actual fact is going on behind this abnormal behaviour?
Thanks in Advanced.

**Comment by as-ka-sha** [comment]
**SS1: (1st Photo) is the Alphabetical Order**
![SS1](https://github.com/freqtrade/freqtrade/assets/132288306/56aa1ea8-ace2-4028-b4e3-ca625c7b32ba)
**SS2: (1st Photo) is the Random Order**
![ss2](https://github.com/freqtrade/freqtrade/assets/132288306/d77cdb20-dbc2-423c-be72-aba3231e9f1d)

**Comment by perkmeister** [comment]
Not enough information to know, and appears to be compounding giving totally unrealistic results where even a small difference would amplify the results. My guess though is if more than one pair had a buy signal the first in the pair list gets opened and the others never got opened because of the max open trades limit had been reached. That would give different results depending on the order of the list.

**Comment by as-ka-sha** [comment]
> Not enough information to know, and appears to be compounding giving totally unrealistic results where even a small difference would amplify the results. My guess though is if more than one pair had a buy signal the first in the pair list gets opened and the others never got opened because of the max open trades limit had been reached. That would give different results depending on the order of the list.

Not greedy about the result although the dry_run for a month and Live run for two weeks showed somewhat similar winrates and pretty high gains. However, during those time, it opend multiple (up to 4) trades at a time in 4 different pairs from the whitelist. so, I'm still confused about the result that the backtest gave me after sorting the StaticPairList in Alphebetical Order. Shouldn't be a issue there with downloaded (static) data. 
If the bot reacts differently with the statatic pair list, it's impossible to optimize for better performance of the strategy.

The config i'm using:, 
{
    "max_open_trades": 4,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.96,
    "fiat_display_currency": "USD",
    "dry_run": false,
    "dry_run_wallet": 100,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 5,
        "exit": 5,
        "exit_timeout_count": 1,
        "unit": "minutes"
    },

    "entry_pricing": {
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },

    "exit_pricing":{
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 3
    },

**Comment by xmatthias** [comment]
you're using 34 pairs (so on every candle, you have 34 possibilities to enter a trade).

You're however at the same time limiting the bot to 4 parallel trades, with an average duration of ~70 minutes (duration numbers make me assume you're probably using 1m timeframe).

If you've got a pretty active strategy (one that generates many signals) - it's VERY likely that you're in 4 trades (each for ~70 minutes) - while you get signals on one of the other 34 pairs (you've got 70 * 29 = 2030 possibilities for that to happen).
To completely prevent pairlist sequence from impacting your results, you'd need to have 1 trade-slot per pair (obviously also with sufficient capital) - only then will the pair sequence make no difference at all - in all other cases, it'll probably impact results - the severity of that will very strongly depend on the actual strategy (if you have 2 trades a month, it's unlikely to impact results).

---

Now the smallest change (change in sequence of pairs) can cause one open trade to be shifted from XXX/USDT to YYY/USDT - which keeps the trade open for 2 minutes longer, causing the very next trade to be with a slightly different pair again.

I find the overall difference not that bad if i'm honest - your win-rate only takes a rather small hit by changing pair sequence, which is usually a not so bad sign.

**Comment by as-ka-sha** [comment]
> you're using 34 pairs (so on every candle, you have 34 possibilities to enter a trade).
> 
> You're however at the same time limiting the bot to 4 parallel trades, with an average duration of ~70 minutes (duration numbers make me assume you're probably using 1m timeframe).
> 
> If you've got a pretty active strategy (one that generates many signals) - it's VERY likely that you're in 4 trades (each for ~70 minutes) - while you get signals on one of the other 34 pairs (you've got 70 * 29 = 2030 possibilities for that to happen). To completely prevent pairlist sequence from impacting your results, you'd need to have 1 trade-slot per pair (obviously also with sufficient capital) - only then will the pair sequence make no difference at all - in all other cases, it'll probably impact results - the severity of that will very strongly depend on the actual strategy (if you have 2 trades a month, it's unlikely to impact results).
> 
> Now the smallest change (change in sequence of pairs) can cause one open trade to be shifted from XXX/USDT to YYY/USDT - which keeps the trade open for 2 minutes longer, causing the very next trade to be with a slightly different pair again.
> 
> I find the overall difference not that bad if i'm honest - your win-rate only takes a rather small hit by changing pair sequence, which is usually a not so bad sign.

Thanks for the reply and effort. As this is the very first time ever I've asked a question, I've come to know what sort of information is needed to get appropriate answers. Although I'm not fully convinced as the Dry-Run for over a month and the Live account running for over a month (2months in total) with almost 500 entries (opend-closed), I noticed that the bot / strategy hardly opend more than 3 trades at a time. However, for your information, the strategy was backtested on 499 (500) days of 5m candle data where most of the pairs in the list are newly listed (10-30days of data).

As per final thought, I don't think the bot should differ the result as it only takes entries and exits based on the condition i set in my strategy, therefore, for a static data in a json file will not create different backtest result when the pair list are sorted differently as the data will  / should generate the same entry and exit plan.
regards,
Mr_ak

**Comment by xmatthias** [comment]
> hardly opend more than 3 trades at a time

it's sufficient to have a few times where all trade-slots are occupied to have results vary.

As mentioned above, it'll strongly depend on your strategy (which we don't have to try and recreate your scenario).
the expectation of "a change in a json fill will not create different backtest result" is correct under only one condition- if the configuration allows all trades to enter - which implies a max-open-trades setting identical to the pairlist length.
