### ISSUE TITLE
did i miss something?

### ISSUE THREAD

**Issue by fachos** [freqtrade/freqtrade#871]
2018-06-08 05:28:36,283 - freqtrade.analyze - WARNING - Outdated history for pair XRP/BTC. Last tick is 6 minutes old

hi... this always happen to me... can you guide me.. thanks

**Comment by gcarq** [comment]
Which exchange and ticker_interval are you using?

**Comment by fachos** [comment]
bittrex 1m

**Comment by fachos** [comment]
is there a custom strategy then default strategy? im not good at this... just try and error.. a poor start with 0.013BTC... thanks

**Comment by gcarq** [comment]
Take a look at the [docs](https://github.com/freqtrade/freqtrade/wiki), there are links to custom strategies and how to define them.
I would recommend to start with `dry_run: true` and get a feel for it first. Best would be to also join our slack channel if you have questions.

**Comment by fachos** [comment]
i run main.py --strategy DefaultStrategy and have some profit but it minus back to the fees... or i need more fund to use the default strategy? ok will try read the docs...  thanks
