### ISSUE TITLE
No trade occurs on the live run.

### ISSUE THREAD

**Issue by thkwon9474** [freqtrade/freqtrade#8710]
Operating system: Ubuntu 22.04
Python Version: python -V 3.11
CCXT version: ccxt==2.6.26
Freqtrade Version: freqtrade 2023.1.dev-7092212ed

## Your question

Hello Team:)

In Backtesting, the result occurs, but in liveRun at the same time, no trade occurs.

I checked the 'Common mistake' as described in the manual and here is the code that seems to be related.

![image](https://github.com/freqtrade/freqtrade/assets/123524953/a399fc5e-b4eb-4fcd-aacd-edc731477080)

'dataframe.iloc[-1].squeeze' is only used in custom_stoploss as shown above.

Please give some thip.... Thank u so much

**Comment by xmatthias** [comment]
If no trades happen, then the stoploss code is not relevant - as it's dead code, really.
To get trades, you'll need to have entry signals (which are not colliding / covered by other signals).

Also, in callbacks, this behavior will be fine, it's in populate_* methods, where it can be problematic.

Your version is also half a year old. While most likely not relevant for this - it's still worth noting that we only actively support the current stable version (2023.5 at time of writing) as well as the latest develop version.

**Comment by thkwon9474** [comment]
@xmatthias Thank you for always answering my inquiry.

First, Is there a way to be notified when the version has been updated?

And Second,,
As following the code is my populate_entry_trend.
When I exclude the custom loss function, trading works normally.
Are there any foreseeable issues related to this?

![image](https://github.com/freqtrade/freqtrade/assets/123524953/4f6c8996-5e7f-45a9-a6c3-9e294815e148)

**Comment by xmatthias** [comment]
Then it's unclear what your question is.
a custom-stop function will NEVER impact trade entries. 
It may/will influence how a trade is treated once it's open - but not opening.
As you say "no trades occur" - my assumption is that no entries occur.
It's impossible for the loss function to impact this - unless you insert it wrongly,causing the strategy to fail to load.


Nothing immediately obvious - but then it's a screenshot - so rest assured that i didn't attempt to look at this in detail other than flying over the code looking for VERY obvious errors).

---

We post new releases in the discord's announcement channel - alternatively you can subscribe to the repository (there's a new releases option).

**Comment by thkwon9474** [comment]
I got it! Thank u so much :)
