### ISSUE TITLE
Checking candle closes and placing orders quickly

### ISSUE THREAD

**Issue by bit-storm** [freqtrade/freqtrade#8711]
Operating system: linux ubuntu 20
Python Version: 3.8
CCXT version: 2.5.12
Freqtrade Version: 2022.12

How can I set the bot to check the strategy as soon as a candle closes?

The volatility of a candle is high and can trigger my entry if things have changed by the time it closes.

I used to refer to the previous candle in each candle using shift(1) in the current candle and check the entry condition in it.

But this causes late entry and also adds calculations, for example, in an hourly candle, the previous candle should be checked many times if the information does not change.

That's why I want to know if there is a method or a method that after closing a candle, I can immediately check the conditions and place the order at its closing.

**Comment by xmatthias** [comment]
Your question is not really clear if i'm honest, therefore some generic information.

Freqtrade provides the strategy with candles as soon as they close (usually within seconds). The actual timing will depend on the exchange, ratelimit settings (we recommend no explicit ratelimit setting), as well as pairlist length.

Using the non-shifted candle will therefore contain the information of the last closed candle. 
assume it's 11:00:05 (we're on 1h candles)
the last candle would be the 10:00 candle (closed at 11:00), while the shift(1) candle would be the 09:00 candle - so the candle that closed at 10:00.

Hope this makes sense.
