### ISSUE TITLE
reload markets frequently

### ISSUE THREAD

**Issue by superXR** [freqtrade/freqtrade#8714]
## Describe your environment

  * Operating system: linux
  * Python Version: 3.9.16
  * CCXT version: ccxt==3.1.5
  * Freqtrade Version: 2023.5
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

In freqtrade/exchange/exchange.py, self._last_markets_refresh is dt_ts(), it's a int(dt_now().timestamp() * 1000), but self.markets_refresh_interval is seconds.This caused reload markets frequently.
![image](https://github.com/freqtrade/freqtrade/assets/57396498/89f2e97a-49ff-4bbb-af48-4abd76474d53)
![image](https://github.com/freqtrade/freqtrade/assets/57396498/f2e340a2-eeb6-461c-9529-b45332cca8b5)
![image](https://github.com/freqtrade/freqtrade/assets/57396498/bec071df-e953-4ac4-9794-65ce738e2c9a)
Another question,I noticed that the logs output ”httpx - INFO - HTTP Request: POST https://api.telegram.org/bot60....“  **every 20 seconds**.I did use the telegram.Is this output frequency normal?

### Observed Results:

  * What happened?
      * reload markets frequently.
  * What did you expect to happen?
      * reload markets normally

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
Nice catch :+1: 
Will be fixed shortly.
