### ISSUE TITLE
how to receive buying/selling signals from tradingview？

### ISSUE THREAD

**Issue by Hotsunrize** [freqtrade/freqtrade#8719]
I searched all over the documentation, but I didn't find an api that can accept external signals
pls

**Comment by stash86** [comment]
Because
1. It's not something freqtrade is built to do
2. It's a simple python programming issue. If you can't do it, that means you need to study python more to be able to add it to your freqtrade bot


Good luck on the learning journey

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Asside from that - it's not something we currently support (at least not directly), nor something we aim to support anytime soon.

**Comment by Hotsunrize** [comment]
> Because
> 
> 1. It's not something freqtrade is built to do
> 2. It's a simple python programming issue. If you can't do it, that means you need to study python more to be able to add it to your freqtrade bot
> 
> Good luck on the learning journey

i see , tks bro i will try ::>
