### ISSUE TITLE
Possible profit calculation error? or BTC/TUSD Spot & Margin Pair maybe not available?

### ISSUE THREAD

**Issue by Cazs03** [freqtrade/freqtrade#8720]
## Describe your environment

  * Operating system: ____ win10
  * Python Version: _____ 3.10.0
  * Freqtrade Version: ____ freqtrade 2023.5.dev-c23a045de
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Possible profit calculation error?
I am using the api :
/api/v1/forcebuy
/api/v1/forcesell

### Steps to reproduce:

  1. forcebuy
  2. forcesell
  3. Observed Results
  
### Observed Results:

  * If I'm not mistaken in the following image that I present
  * Let's see the image:
We observe 3 force exit
Everyone presents a negative loss, is this really so?
id: 3 open 26893.95 close 26894.3 profit-0.20
id: 2 open 26862.63 close 26906.63 profit-0.04
id: 1 open 26862.96 close 26850.56 profit-0.25
![proof](https://github.com/freqtrade/freqtrade/assets/6555389/1095e7e4-b7da-43e1-9c4d-0ee53077785b)

Except case ID 1
Cases 2 and 3 present a loss but the open rate and close rate indicate a positive profit although it shows a negative profit

in config:
"unknown_fee_rate": 0
Using :
https://www.binance.com/en/fee/trading
BTC/TUSD Spot & Margin Pair
0% Fee

More info:
freqtrade test-pairlist --config .\config_examples\config.json --quote TUSD

 ###log
 
 INFO - Markets were not loaded. Loading them now..
2023-06-01 15:37:51,734 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 0 pairs: []
Pairs for TUSD: 
[]
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021A8CECD750>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

**Comment by Cazs03** [comment]
Its posible BTC/TUSD Spot & Margin Pair
Not are available in freqtrade?

**Comment by stash86** [comment]
First of all, there is no such config `unknown_fee_rate`, so the bot would use default fee (0.2% on binance) if you are on dry-run mode

**Comment by Cazs03** [comment]
> First of all, there is no such config `unknown_fee_rate`, so the bot would use default fee (0.2% on binance) if you are on dry-run mode
u can fin this config on config_full.example.json
apart of this i'm test with fee: 0:
In binance:
BTC/TUSD Spot & Margin Pair
0% Fee
has 0 fees that's my finality 
But when try  use appear another error

**Comment by xmatthias** [comment]
> First of all, there is no such config `unknown_fee_rate`, so the bot would use default fee (0.2% on binance) if you are on dry-run mode

Well that's not true - that setting does exists, but it's not relevant for binance (binance fee currencies are always tradable). This applies mainly to Gate - where fees are sometimes deduced in gate points (GT iirc) - which are not a tradable pair, and therefore don't have a rate.

---

Freqtrade's dry-run will use the fees as returned by ccxt's `calculate_fee()` method - which usually returns the default fee - which is 0.1%.
As far as i know, it doesn't consider special actions like 0 fee pairs or different VIP fee reductions - also because the exchanges (at least binance) don't make fees per pair available through the API.

Live will use the actual fees which are applied on a trade (in this case, it might be 0 fees) - but that's information that's unavailable to ccxt (and in consequence freqtrade) - and is therefore not considered.

**Comment by Cazs03** [comment]
ccxt support BTC/TUSD Spot & Margin Pair?
In binance says has 0 fees
And it's available to download tickers

**Comment by xmatthias** [comment]
If it's available via the API, i don't currently see why it wouldn't be available in ccxt or freqtrade.
you keep mentioning "spot & Margin Pair" - please bear in mind that freqtrade will only support spot trading, not margin trading.

**Comment by Cazs03** [comment]
> If it's available via the API, i don't currently see why it wouldn't be available in ccxt or freqtrade.
> you keep mentioning "spot & Margin Pair" - please bear in mind that freqtrade will only support spot trading, not margin trading.

I'm open question in cctx seems not available:
More info:
  "trading_mode": "spot",
  "margin_mode": "",
freqtrade test-pairlist --config .\config_examples\config.json --quote TUSD

###log

INFO - Markets were not loaded. Loading them now..
2023-06-01 15:37:51,734 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 0 pairs: []
Pairs for TUSD:
[]
Exception ignored in: <function _ProactorBasePipeTransport.del at 0x0000021A8CECD750>
Traceback (most recent call last):
File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in del
File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed


But it's available ej:
[https://api.binance.com/api/v3/klines?symbol=BTCTUSD&interval=1m&limit=1](https://api.binance.com/api/v3/klines?symbol=BTCTUSD&interval=1m&limit=1)

**Comment by xmatthias** [comment]
You might be either using a config that eliminates that pair from the pairlist.

running `freqtrade list-pairs --quote TUSD --exchange binance` shows about 19 active pairs - which you can obviously also trade with.
