### ISSUE TITLE
Entry order has been fill property available way API?

### ISSUE THREAD

**Issue by Cazs03** [freqtrade/freqtrade#8723]
## Describe your environment

  * Operating system: ____ win10
  * Python Version: _____ 3.10.0
  * Freqtrade Version: ____ freqtrade 2023.5.dev-c23a045de
  

## Your question
I have a question. I am reviewing the data returned by an entry to verify via API if that trade has actually been made.
It is true that when an order is launched it has an entry period until it is executed in the exchange order book.
If a period passes the order is cancelled.
Here comes my question.
At the moment I am in dryrun
My configuration:
```
   "unfilledtimeout": {
     entry: 1,
     "exit": 1,
     "exit_timeout_count": 0,
     "unit": "minutes"
   },
   "order_time_in_force": {
     "entry": "IOC",
     "exit": "IOC"
   },
   ```
And I'm checking the JSON
```
{
   "trade_id": 5,
   "pair": "BTC/TUSD",
   "base_currency": "BTC",
   "quote_currency": "TUSD",
   "is_open": true,
   "is_short": false,
   "exchange": "binance",
   "amount": 0.03647,
   "amount_requested": 0.03647136,
   "stake_amount": 989.2994433,
   "max_stake_amount": 989.2994433,
   "strategy": "iaimmachine",
   "enter_tag": "force_entry",
   "time frame": 5,
   "fee_open": 0,
   "fee_open_cost": 0,
   "fee_open_currency": "TUSD",
   "fee_close": 0,
   "fee_close_cost": null,
   "fee_close_currency": null,
   "open_date": "2023-06-02 08:45:07",
   "open_timestamp": 1685695507333,
   "open_rate": 27126.39,
   "open_rate_requested": 27125.23,
   "open_trade_value": 989.2994433,
   "close_date": null,
   "close_timestamp": null,
   "close_rate": null,
   "close_rate_requested": null,
   "close_profit": null,
   "close_profit_pct": null,
   "close_profit_abs": null,
   "profit_ratio": -0.00001917,
   "profit_pct": 0,
   "profit_abs": -0.0189644,
   "profit_fiat": -0.0189536661496,
   "realized_profit": 0,
   "realized_profit_ratio": null,
   "exit_reason": null,
   "exit_order_status": null,
   "stop_loss_abs": 271.27,
   "stop_loss_ratio": -0.99,
   "stop_loss_pct": -99,
   "stoploss_order_id": null,
   "stoploss_last_update": null,
   "stoploss_last_update_timestamp": null,
   "initial_stop_loss_abs": 271.27,
   "initial_stop_loss_ratio": -0.99,
   "initial_stop_loss_pct": -99,
   "min_rate": 27125.87,
   "max_rate": 27126.39,
   "open_order_id": null,
   "orders": [
     {
       "pair": "BTC/TUSD",
       "order_id": "dry_run_buy_1685695507.099788",
       "status": "closed",
       "remaining": 0,
       "amount": 0.03647,
       "safe_price": 27126.39,
       "cost": 989.2994433,
       "filled": 0.03647,
       "ft_order_side": "buy",
       "order_type": "market",
       "is_open": false,
       "order_timestamp": 1685695507099,
       "order_filled_timestamp": 1685695507333
     }
   ],
   "leverage": 1,
   "interest_rate": 0,
   "liquidation_price": null,
   "funding_fees": 0,
   "trading_mode": "spot",
   "amount_precision": 5,
   "price_precision": 2,
   "precision_mode": 2,
   "stoploss_current_dist": -26854.6,
   "stoploss_current_dist_pct": -99,
   "stoploss_current_dist_ratio": -0.98999958,
   "stoploss_entry_dist": -979.4062264,
   "stoploss_entry_dist_ratio": -0.98999978,
   "current_rate": 27125.87,
   "total_profit_abs": -0.0189644,
   "total_profit_fiat": -0.0189536661496,
   "total_profit_ratio": -0.000019169524584730956,
   "open_order": null
}
```
It is known that in dryrun the orders always enter, but when you are in live mode, things change and first I want to check with an api call if the order has entered before executing another event.
sems :
  "open_order": null
maybe has been related with this?

**Comment by xmatthias** [comment]
You'll get the status for each order as part of the orders list.
If the very first entry is cancelled (timeout, manually) - then the whole trade will disappear (deleted), and most likely, the id will be reused (depends on the database used, as well as some other factors).

open_order is really irrelevant (and may disappear soon, as there's no good reason to keep it).
if any, you might look at `open_order_id` - but in general, the information in the orders list is what you want to look for on information for individual orders.

> It is known that in dryrun the orders always enter,

This is not true, and will solely depend on your selected pricing strategy.

**Comment by Cazs03** [comment]
The suggestion would be to save the order and then check the id if it is in the list?

**Comment by xmatthias** [comment]
without knowing what you're trying to do - i can't suggest anything.

Freqtrade will handle cancellations for you - so i'm not sure what you're looking for.

**Comment by Cazs03** [comment]
I am trying to generate an application in react to manage from a graphical interface with two buttons, forcebuy forcesell.
The issue is as follows, it may be that I forcebuy in dryrun, the order will enter immediately and then forcesell to sell right after.
That I intend to add an "intermediary" to disable the forcesell button, until I identify that the order has actually been executed.
This is "important" at the point when you are running Freqtrade on "real"

What am I going to do if I don't have that option? Buy, save the result. Just before selling, verify, consult that trade with the get /v1/trade method and verify some of its properties.
Right now I am using:
profit_ratio

But it would be ideal to have something more than that like entrycomplete or something like that

**Comment by xmatthias** [comment]
You might be able to go with open_order_id (if that's empty, there's no open order).

---

Freqtrade has an UI  available with [freqUI](https://github.com/freqtrade/frequi), which offers both force-enter, as well as force-exit functionalities (among many others).
You're more than welcome to contribute and improve that project.

I'll however not waste my time on yet another "i want to do it from scratch" implementation. While this might sound harsh - i've seen it often enough that such projects are abandoned after only a few weeks - leading to a ton of wasted talent, simply because of the "i want to do it from scratch" mentality.

Thanks for your understanding.

**Comment by Cazs03** [comment]
I can understand it, I just wanted to know if there is a way, for now I'm going to use the approach I'm using until I can try the binance api on dryrun off
