### ISSUE TITLE
Question - When I have an open trade for a pair, the entry signal appears at this time, can I buy again

### ISSUE THREAD

**Issue by yili1992** [freqtrade/freqtrade#8724]
## Describe your environment

  * Operating system: linux
  * Freqtrade Version: docker image v2023.5
  
## Your question

When I have an open trade for a pair, the entry signal appears at this time, can I buy again?
or in the adjust_trade_position function, how do I know that there is currently an entry signal

**Comment by perkmeister** [comment]
Yes, with `adjust_trade_position()` but you'll need some code to detect a new candle to stop multiple buys, see this post on freqtrade Discord:
https://discord.com/channels/700048804539400213/824719649417199646/1114246980311453786
