### ISSUE TITLE
Question about stake amount configuration

### ISSUE THREAD

**Issue by thunderwin** [freqtrade/freqtrade#8726]
here is my config.json set up.

` "available_capital": 1000,
  "stake_amount": "unlimited",
  "stake_currency": "USDT",
  "max_open_trades": 1,
  "tradable_balance_ratio": 0.99,
`

but why does the bot only uses 835USD to place an order..  why not 1000, also later, the bot made some money, my total balance increased to 1200, it still uses 800usd to place an order..  how can I make it always use all the fund ???  always full positon.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Please carefully read through the [stake amount](https://www.freqtrade.io/en/stable/configuration/#configuring-amount-per-trade) documentation.
It should contain all the information you need.

If it doesn't, then YOU need to provide us with more information (like the issue template, as well as trade modes, pairs you observed certain behavior, ...).

**Comment by thunderwin** [comment]
I have copied all code running on the dry-run model,  everything works as excepted.  I have read through all the doc.  no luck,  I guess if I clean the DB, and restart it, it will be fine, But I wanna find the reason.

**Comment by thunderwin** [comment]
i will post the reason here, if I found any..

**Comment by Cazs03** [comment]
this is my config:
  "stake_amount": "unlimited",
  "tradable_balance_ratio": 0.99,
  "fiat_display_currency": "USD",
  "amount_reserve_percent": 0.05,
  "amend_last_stake_amount": true,
  "last_stake_amount_min_ratio": 0.5,

**Comment by stash86** [comment]
> this is my config:
> "stake_amount": "unlimited",
> "tradable_balance_ratio": 0.99,
> "fiat_display_currency": "USD",
> "amount_reserve_percent": 0.05,
> "amend_last_stake_amount": true,
> "last_stake_amount_min_ratio": 0.5,

Smells like chatgpt

**Comment by xmatthias** [comment]
@thunderwin With the provided information, it's impossible to assist you further.

If you expect help, please provide the info requested in the above comment.
Otherwise, i'll have to assume that you don't want/ need help (we can't provide help if we don't know more details).
Thanks for your understanding.
