### ISSUE TITLE
difference between Aforcebuy and forceenter

### ISSUE THREAD

**Issue by Cazs03** [freqtrade/freqtrade#8728]
## Describe your environment

  * Operating system: ____ win10
  * Python Version: _____ 3.10.0
  * Freqtrade Version: ____ freqtrade 2023.5.dev-c23a045de
  
## Your question
According to the documentation:
I don't understand the difference between these two methods

https://www.freqtrade.io/en/stable/rest-api/#available-endpoints
Aforcebuy
    Buy an asset.

        :param pair: Pair to buy (ETH/BTC)
        :param price: Optional - price to buy

forceenter
    Force entering a trade

        :param pair: Pair to buy (ETH/BTC)
        :param side: 'long' or 'short'
        :param price: Optional - price to buy
        
PD:
      One detail, is it possible that some configuration in config.json overrides the price parameter?

**Comment by xmatthias** [comment]
force_buy is a (deprecated) endpoint, which is a shortcut for forceenter with side=long.

Price is optional, and if not provided, it'll use the configured price.
