### ISSUE TITLE
Backtest: 'Stable' results?

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8729]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.2 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Running multiple backtesting sessions with exactly the same configuration can produce in my case a significant difference concerning the final balance. Is there a parameter / flag, so the results would be more consistent?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
backtesting of the same exact configuration / strategy / timerange / pairlist will produce identical results.

if they don't, then you 
* either have some element of randomness in your result (ShuffleFilter, something in the strategy?)
* you're using data you shouldn't (data from "now" - for example the orderbook, which will always use the CURRENT price - as it's not available historically)
* or you're using an "unstable indicator configuration" (we observed this with an [edge-case in ta.MACD](https://brookmiles.github.io/freqtrade-stuff/2021/03/29/why-theforce-doesnt-work/).
Now obviously, the above is just an example for an indicator, in theory, every indicator can be impacted by this - if you have such a case, best reduce the indicators by as much as possible, so you can limit it to 1-2 indicators.

**Comment by myNextCoder** [comment]
I am sorry: The shufflefilter ;) I should have discovered it myself. The only reason, why I added it some days ago is, because the pairs, with which the system was trading, always belonged to the beginning of the alphabet. So I wanted to give a chance to all pairs. Bad idea in that case. I probably have to shuffle the list prior to the backtest.

**Comment by xmatthias** [comment]
Shuffle filter has an option - ["seed"](https://www.freqtrade.io/en/latest/plugins/#shufflefilter) - setting it is recommended in backtesting to avoid exactly this problem (it's gonna be ignored in live).

It'll still shuffle pairs - but will always shuffle them the same way unless the actual pairlist changes - giving you randomness, but still repeatability.

**Comment by myNextCoder** [comment]
I searched the documentation page of backtest for 'seed' prior to my post here, for a reason, you only included it on the hyperopt page. I am happy to read here, that 'seed' is valid also for backtesting.

**Comment by xmatthias** [comment]
it's a configuration of the pairlist, and is therefore on the pairlist documentation page.
