### ISSUE TITLE
How to enable Binance API and Freqtrade to buy leveraged coins like BTCUP? 

### ISSUE THREAD

**Issue by QingzhiHu** [freqtrade/freqtrade#8744]
Hi! I have agreed on Binance that I could trade leveraged coins and acknowledged the potential risks, however, with trading spot being spot or margin, my bot does not seem to be able to buy leveraged coins. Is there a minimum amount of BTCDOWN/USDT I need to place the order? How shall I setup my Binance API and Freqtrade bot to enable buying and selling leveraged coins (automatically)? 

Thank you!

**Comment by stash86** [comment]
Trading BTCUP or DOWN should just be the same as other spot pairs. But judging from your name, I assume you are chinese, hence extra limitation might be imposed on your account due to that fact.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

if i remember correctly, then this needs to be acknowledged for every (leveraged) coin you'd like to trade.

If your account can trade that coin on exchange, itll also work through the API, obviously the same minimum trading limits will still apply.

**Comment by QingzhiHu** [comment]
> Please get used to filling out the issue template. Those who frequently omit the template may have their issues closed without comment. We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.
> 
> Filling out the template helps reduce our workload, and we greatly appreciate that.
> 
> if i remember correctly, then this needs to be acknowledged for every (leveraged) coin you'd like to trade.
> 
> If your account can trade that coin on exchange, itll also work through the API, obviously the same minimum trading limits will still apply.

——————————-
Hi! Thanks! That resolves my issues. I will follow the template next time I raise with a new issue!
