### ISSUE TITLE
RSI Strategy implementation problem

### ISSUE THREAD

**Issue by aborawaa1** [freqtrade/freqtrade#8746]
## question
I want a code based on freqtrade as follows:
1: Buy if the rsi is less than 30
2: Sell if the RSI is greater than 80
Take profit to buy:
1: In the case of buying, reap a profit of 1% with half the quantity, 50%
2: In the case of purchase, reap a profit of 2% with the rest of the quantity
Take profit for sale:
1: In case of selling, take a profit of 1% with half of the quantity, 50%.
2: In case of selling, reaping a profit of 2% with the rest of the quantity

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

It should also be clearly highlighted that this is an open source project, run and supported by people in their free time.
We'll however not accept "please write this strategy for me" requests.
We will assist in case of problems to some degree (assuming most of the work is coming from you)  - but we'll not do the work of implementing a strategy based on some random description. 


Please consult the [documentation](https://www.freqtrade.io/en/stable/) for problems first. It contains all information to completely fulfill the above request.

The general entry/exit signals are so basic i doubt they'll be profitable - but they can be copy/pasted together from the samples in the [strategy documentation](https://www.freqtrade.io/en/stable/strategy-customization/).

For the custom take-profit logic, you can implement this in the [`adjust_trade_position()`](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position) callback.

You can also refer to the [strategy repository](https://github.com/freqtrade/freqtrade-strategies/) for ideas on how to implement certain things.
