### ISSUE TITLE
Defining the number of historical candles

### ISSUE THREAD

**Issue by pouyaGit** [freqtrade/freqtrade#8750]
* Operating system: Ubuntu 22
  * Python Version: 3.10.6
  * CCXT version: 2.7.66
  * Freqtrade Version: 2023.2.dev-8d156b277
  
Is there a way to force the number of historical candles before running the strategy?
My TSI calculations is in need of 200 historical candles and it seems that freqtrade is providing much less.

**Comment by stash86** [comment]
Please read the whole docs.

https://www.freqtrade.io/en/stable/strategy-customization/#strategy-startup-period
