### ISSUE TITLE
Hyperopt for all spaces

### ISSUE THREAD

**Issue by Corfucinas** [freqtrade/freqtrade#8751]
Is it possible to Hyperopt for all spaces without needing to be explicit?

I want to optimize the `informative pairs timeframe`,  this can be done with 

```python
   informative_timeframe = CategoricalParameter(
        [
            "15m",
            "30m",
            "1h",
            "2h",
            "4h",
            "6h",
            "8h",
            "12h",
            "1d",
        ],
        default=timeframe,
        space="buy", # mmmm ?
    )
````

However, this will ignore the value for selling (I understand that if an indicator has found a new value while "buying", it will be changed if another space overrides it (correct me if I'm wrong).

However, knowing which spaces are getting Hyperopt within the informative pairs function without additional context is impossible.

If we have additional context (do we?), we can select the timeframe based on the space.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

you'll need to be rather careful with where you USE this - as the values are only changed within methods (i'm not sure on decorators if i'm honest).

i'm however not sure i understand the problem.

Each parameter is assigned to exactly one space, and will have exactly one assigned value at a time (Which can change during hyperopt).
the "space" itself however is really just a grouping logic. if a "buy" parameter is actually used for buys (long entries, short exits) - or for longs only - is really irrelevant from a technical perspective.
Think about it more as "i select this part of parameters, or the other - or both.

if you need different values per context (different parameter for buys and sells) - just create 2 different variables that can be optimized independent from each other ?

**Comment by Corfucinas** [comment]
Thanks @xmatthias  for the reply and clarification
