### ISSUE TITLE
Backtesting: Price jump

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8752]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.2____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

What exactly is the reason, for putting information into the log during backtesting for asset price-jumps? Do we interpret them somehow as a warning for possibly to volatile?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Please refer to the [FAQ](https://www.freqtrade.io/en/stable/faq/#im-getting-price-jump-between-2-candles-detected) for this.

It explains what it's for - including a known pair where this has happened.
