### ISSUE TITLE
getting a covariance matrix in case of a static pairlist

### ISSUE THREAD

**Issue by HeinrichHaller** [freqtrade/freqtrade#8753]
## Describe your environment

  * Operating system: Ubuntu LTS
  * Python Version: 3.10.6
  * CCXT version: 3.1.23
  * Freqtrade Version: freqtrade 2023.6.dev-fc8c6b06a
  
## Your question

Hope it is no duplicate, but I haven't found it. How to get for instance a running covariance matrix over the last 20 periods over a static pairlist(including "include_corr_pairlist")? 
Thanks

**Comment by xmatthias** [comment]
a rolling covariance matrix is really just a call to `df.rolling(20).cov()`.

Now the more problematic point here is that you'll need to combine 1 value for each pair into one dataframe to actually run this.

You can probably use informative pairs functionalities for this - though i don't think we have something like this pre-made - it should be pretty easy through a combination of [get_pair_dataframe](https://www.freqtrade.io/en/stable/strategy-customization/#get_pair_dataframepair-timeframe) with `merge_informative_pair()` - and then applying a filter to that.
