### ISSUE TITLE
usage of the optimize.hyperopt_loss outside the optimization

### ISSUE THREAD

**Issue by HeinrichHaller** [freqtrade/freqtrade#8754]
## Describe your environment

 * Operating system: Ubuntu LTS
  * Python Version: 3.10.6
  * CCXT version: 3.1.23
  * Freqtrade Version: freqtrade 2023.6.dev-fc8c6b06a

  
## Your question

Can I use the performance metrics in the optimize package outside the optimization, for instance in the reward_function? 
In case I wanna access the sql database, is it more advisable to to use sqlalchemy like you did in the freqtrade.persistance or do it via plain sql statement? How to access the database in this case? To get for instance some rolling performance metric?
Thanks

**Comment by xmatthias** [comment]
You can get access to the database via the [documented functions](https://www.freqtrade.io/en/stable/trade-object/).

While in theory, you can use also plain sql statements, we won't provide support for that, and consider the table names as implementation detail which can change without notice (the sqlalchemy objects however can have fallbacks, allowing us to deprecate certain functions in case of renamings).

---

you can obviously import everything (it's just python after all).

Things/methods you'll find as part of the documentation are usually public / user facing interfaces, and are treated as such (changes to the interface will be listed in the changelog, ...).

Things not in the documentation should be considered as private/implementation details.
This doesn't mean you can't use them, but they can be changed without notice (or even mention in the changelog, as we consider them as "not relevant to the user") - and it's up to you to do your due diligence and ensure that non-documented functionalities will not break with updates (either through careful testing, or by reading through the diff between versions).
