### ISSUE TITLE
adjust_trade_position

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8759]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.2 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

According to the documentation beside other functionality adjust_trade_position is looking for partial exits. In that case, unlike the name of the def, this function is also exiting, or is it only a pre-exiting phase, and will custom_exit do the job?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
`adjust_trade_position()` does what the name implies - which is adjusting the position.

Adjustments to a position can be both increases and decreases in position size (positive or negative return value).
 I therefore find the name of the function exactly right.

if the result of a negative adjustment would become an unsellable trade (below the tradable limit), that position adjustment is ignored. This also applies to full exits - where custom_exit has to be used.

**Comment by myNextCoder** [comment]
I thank you for your information. I agree with you, that the name of the def tells us about the way, the code works. But how is the def looking then for partial exits - according to the documentation?

**Comment by xmatthias** [comment]
> Position adjustments will always be applied in the direction of the trade, so a positive value will always increase your position (negative values will decrease your position), no matter if it's a long or short trade.

source: [the documentation](https://www.freqtrade.io/en/latest/strategy-callbacks/#adjust-trade-position).

**Comment by myNextCoder** [comment]
Ok, many thanks.
Is there a way to access the pricing levels directly, where the filled entries have been placed? (Like we can access the stake size with filled_entries[0].cost)

**Comment by xmatthias** [comment]
i'd **strongly** recommend you read the documentation once from top to bottom at least once.

your answers can pretty easily be found in [the documentation](https://www.freqtrade.io/en/stable/trade-object/#order-object) (which makes me assume your questions here are pure lazyness) - and i don't really like to waste my time reading the documentation to you.

**Comment by myNextCoder** [comment]
The documentation is the 'basic lecture' when it comes to Freqtrade. Knowing new parts of the software can be challenging, especially, when the puzzle-parts are not at a place, where expected. It is up you, as an important person of the Software, to use words like 'lazyness' or 'waste of time' right away. Online politeness is a thing, I appreciate, and it helps in addition to keep the desired web reputation.
