### ISSUE TITLE
Strategy base on curren Ask and Bid rates. Is it possible to acces this data in strategy.

### ISSUE THREAD

**Issue by mombip** [freqtrade/freqtrade#8762]
I'm using current develop branch. I try to develop my custom strategy. I need access to current ask and bid prices. I need spread but also ask and bid.
I've spent some time on debuging robot. I've found code which gave me access to ticks in Exchange or DataProvider classes (ask and bid is included) but in `IStrategy` class . I manage to get proper Ticker object filled with data I need (ask and bid) but I cant get right way to make it visible in Strategy object. I was thinking about merging dataFrame obtained from DataProvider (using method `self.dp.ohlcv`in IStrategy.analyse_pair() ) but I don't like this solution. Is there any official (designed) way to get current ask and bid rates together with currently available candle data?

**Comment by stash86** [comment]
https://www.freqtrade.io/en/stable/strategy-customization/#orderbookpair-maximum

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

When using the above it should be clear that this is an active call against the exchange, which means

* it'll slow the bot loop down some, as exchange calls are impacted by rate limits
* backtesting won't have this data

**Comment by mombip** [comment]
Thank you for your support and patience. Please accept my apologies for not filling the form out. I'll do better next time.
Thank you stash86 for link and xmatthias for remarks to potential solution. I'll try with your suggestions. I think it will work.
