### ISSUE TITLE
Reinfocment Learning model failed to run trade on train data with continual_learning

### ISSUE THREAD

**Issue by CryptoRahino** [freqtrade/freqtrade#8763]
## Describe your environment

  * Operating system: ubuntu 22
  * Python Version: 3.10.0 (`python -V`)
  * CCXT version: ccxt==3.0.97 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.5 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

after running RL training on backtest, trade is failing with error `Observation spaces do not match` 
this happens only when using  continual_learning=true.

 

### Steps to reproduce:

  1. configure continual_learning=true
  2. run backtest on RL
  3. run trade on RL
  

```2023-06-12 05:24:56,332 - freqtrade.freqai.freqai_interface - ERROR - Training ADA/USDT:USDT raised exception ValueError. Message: Observation spaces do not match: Box(-1.0, 1.0, (1, 185), float32) != Box(-1.0, 1.0, (1, 188), float32), skipping.
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/freqai/freqai_interface.py", line 242, in _start_scanning
    self.extract_data_and_train_model(
  File "/opt/freqtrade/freqtrade/freqai/freqai_interface.py", line 640, in extract_data_and_train_model
    model = self.train(unfiltered_dataframe, pair, dk)
  File "/opt/freqtrade/freqtrade/freqai/RL/BaseReinforcementLearningModel.py", line 129, in train
    model = self.fit(data_dictionary, dk)
  File "/opt/freqtrade/freqtrade/freqai/prediction_models/ReinforcementLearner.py", line 75, in fit
    model.set_env(self.train_env)
  File "/home/rahino/anaconda3/envs/freqtrade_orig1/lib/python3.10/site-packages/stable_baselines3/common/base_class.py", line 500, in set_env
    check_for_correct_spaces(env, self.observation_space, self.action_space)
  File "/home/rahino/anaconda3/envs/freqtrade_orig1/lib/python3.10/site-packages/stable_baselines3/common/utils.py", line 230, in check_for_correct_spaces
    raise ValueError(f"Observation spaces do not match: {observation_space} != {env.observation_space}")
ValueError: Observation spaces do not match: Box(-1.0, 1.0, (1, 185), float32) != Box(-1.0, 1.0, (1, 188), float32)```

**Comment by CryptoRahino** [comment]
when changed `add_state_info` to be `false`. the issue solved.
if this causing such a problem, maybe it should be off by default with RL

**Comment by robcaulk** [comment]
Please do have a read through the parameter table (RL will take you approximately 2 minutes to read). It is automatically handled for you. Have a nice day.

![image](https://github.com/freqtrade/freqtrade/assets/20807672/a90e5436-d010-42ed-bbde-bcc19209d569)

**Comment by xmatthias** [comment]
@robcaulk isn't this automatic handling which causes the actual error of `ValueError: Observation spaces do not match`  when "migrating" from backtest to live (without resetting the model directory) ? 

That's neither documented (nothing says a RL model trained by backtesting can't be used in live ), nor is the current behavior (it's failing if i run backtest, followed by "trade") really expected.

The fix mentioned in the comment is to disable `add_state_info` for trade mode - which i assume will align the parameters again.

**Comment by robcaulk** [comment]
@xmatthias this is user responsibility - the only way this can occur is if a user A) ignores warning messages that we've posted to them in their backtest logs, B) ignores the RL parameters that they are blindly setting and C) doesnt realize that a model trained with 10 features cannot be inferenced used with 13 features. A) Is our attempt to help the user understand there is a warning here, with keywords to help them investigate further by searching doc or discord. B) we have extensive documentation regarding this. I can do nothing about C), this is not an ML knowledge base/course.

The "fix" proposed by @CryptoRahino  actually would not help. Say we set `add_state_info` to false by default, but someone uses a config with `add_state_info: true` for backtesting - we would automatically turn that off for them during backtesting, then when they move to dry it would be true again and the same issue would arise. 

The only two "fixes" I would accept are:

Catching this error and raising an exception with a message saying "you are likely trying to add_state_info to a previously trained model that did not include state_info. Please deactivate state info if you wish to use this model. <URL to add_state_info parameter description>" 

or

Add this information to the global_metadata.json at the moment of training about if this was active during training or not. But to me that is just more unnecessary if statements which end up bogging down the flexibility and extensibility of the RL component of FreqAI, all in exchange for helping *only* the users who ignore helpful log warnings and ignore helpful docs.

**Comment by CryptoRahino** [comment]
additional suggestion maybe to print in the warning reference to the flag. to notice the user.
