### ISSUE TITLE
problem about Custom stoploss : "the truth value of a series is ambiguous"

### ISSUE THREAD

**Issue by thkwon9474** [freqtrade/freqtrade#8764]
## Describe your environment

Operating system: Ubuntu 22.04.2 LTS
Python Version: 3.11.2 (python -V)
CCXT version: 3.1.23 (pip freeze | grep ccxt)
Freqtrade Version: 2023.6.dev-fd940dbba (freqtrade -V)
  
## Your question

Hello Team:)

My strategy sets the indicator's value to Stop Loss on Entry and Trade.
The trade closes at 1x and 2x the stop loss and it was implemented using a custom loss.

Actually there is no problem with backtesting, But On Dry and Live Run I get the following error:

![image](https://github.com/freqtrade/freqtrade/assets/123524953/aee766c1-0a37-46bf-8d53-f1ca5d3cd7fd)

as following the code is custom loss

    def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:  
        if trade.is_short :
            result = 1
        else :
            result = -1
        #TF_Tolerance = self.TF / 2
        
        #if int(current_time.strftime('%M')) % self.TF == 0:
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)     
        last_candle = dataframe.iloc[-1].squeeze()
        
        if current_time > trade.open_date_utc:
            if trade.is_short:
                stoploss_price = dataframe.loc[ (dataframe["date"] == trade.open_date_utc) , "Short_SL"].squeeze() # set stop loss (supertrend value of previous candle)           
                result = (((stoploss_price)/current_rate) - 1) * trade.leverage
                
                if (last_candle['close'] < (trade.open_rate - abs(stoploss_price - trade.open_rate))) :
                    new_stoploss_price = (trade.open_rate - abs(stoploss_price - trade.open_rate)) * 1.01      
                    result = (((new_stoploss_price)/current_rate) - 1) * trade.leverage
                
            else:
                stoploss_price = dataframe.loc[ (dataframe["date"] == trade.open_date_utc) , "Long_SL"].squeeze()                    
                result = (((stoploss_price)/current_rate) - 1) * trade.leverage
                
                if (last_candle['close'] > (abs(trade.open_rate - stoploss_price) + trade.open_rate)) :
                    new_stoploss_price = (abs(trade.open_rate - stoploss_price) + trade.open_rate) * 0.99               
                    result = (((new_stoploss_price)/current_rate) - 1) * trade.leverage

        return result

I know this isn't a freqtrade issue, I'm guessing it's probably Pandas related.
But, Please give me any advice...!

**Comment by xmatthias** [comment]
The error itself is exactly the one we highlight in the [dataframe gotchas](https://www.freqtrade.io/en/latest/strategy-customization/#dataframe) - but the usage is not as simple as shown in the docs.

i suspect it COULD be the type of `stoploss_price` that's the problem here - as i'm not sure what happens if a series (not a dataframe) is squeezed.
The pandas docs might have some hints on that - otherwise you can simply print something around `type(stoploss_price)` (or one of the other variables).

**Comment by thkwon9474** [comment]
I found it. 

The Problem is the difference btw open date and current date seconds.
Thank u so much

![image](https://github.com/freqtrade/freqtrade/assets/123524953/89837c02-9917-4fa7-8513-8121e372b403)

**Comment by froggleston** [comment]
stoploss_price as you have coded it will likely not return a scalar. If you want the trade candle, use code such as:

```
        trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
        trade_candle = df.loc[(df['date'] == trade_date)]
        if trade_candle.empty:
            return 1
        trade_candle = trade_candle.squeeze()
```

**Comment by perkmeister** [comment]
I think it's the missing `timeframe_to_prev_date` thing, as that equality as stands will almost always fail and produce an empty `stoploss_price` object.

**Comment by thkwon9474** [comment]
> I think it's the missing `timeframe_to_prev_date` thing, as that equality as stands will almost always fail and produce an empty `stoploss_price` object.

Thank to u, I've solve the problem.

In the dataframe, only the correct values ​​are entered, but the actual open date have a different values ​​in seconds.

I fixed this by giving tolerances to the front and back of the previously uploaded conditional statement.

**Comment by thkwon9474** [comment]
> stoploss_price as you have coded it will likely not return a scalar. If you want the trade candle, use code such as:
> 
> ```
>         trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
>         trade_candle = df.loc[(df['date'] == trade_date)]
>         if trade_candle.empty:
>             return 1
>         trade_candle = trade_candle.squeeze()
> ```

Thank u so much
