### ISSUE TITLE
Raspberry pi zero w

### ISSUE THREAD

**Issue by Lebweuh** [freqtrade/freqtrade#8777]
can i run this code on my raspberry pi zero w?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

In principle, it's just python, so it will  run on a raspberry (tested on a rpi3/rpi4 without issues).

we do have some [recommended specs](https://www.freqtrade.io/en/stable/#requirements) - which is the minimum we're able to actively support.
in practice, you can often get away with less - but it'll almost exclusively depend on the strategy you're going to run, as different strategies can have a completely different load profile, and with that, completely different requirements.
If you have a very calculation heavy strategy, the minimum requirements will probably not be sufficient, either.

**Comment by stash86** [comment]
Try it and see
