### ISSUE TITLE
Qtalib compatibility

### ISSUE THREAD

**Issue by thkwon9474** [freqtrade/freqtrade#8778]
## Your question

Hello Team:)

Is it not possible to use Qtalib in Freqtrade?

During the installation process, it need to install yum and gcc.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

I've never heard of qtalib, and therefore also never used it.

Assuming it's a python library that's accepting pandas / Numpy series as arguments, it'll probably work (though i'll not read the documentation of a random library for you to figure out what the correct arguments will be).
You're however almost certainly the first to try (at least to my knowledge).

Best report back if you find that the library works well and provides some unique indicators (though the first few look like regular SMA's).

If you're having problems installing that library however, it's best to get in touch with that library / library author.
