### ISSUE TITLE
The leverage of ETH/USDT does not work despite allowed on Binance

### ISSUE THREAD

**Issue by peterphan1996** [freqtrade/freqtrade#8780]
## Describe your environment

  * Operating system: Oracle-Linux-Cloud-Developer-8.4-aarch64
  * Python Version: 3.6.8
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.5.1
  * Running on Docker
  
## Your question
I'm on dry-run mode and setting leverage 100 for BTC/USDT and ETH/USDT. But received leverage 75 for ETH/USDT. BTC/USDT works fine though
![image](https://github.com/freqtrade/freqtrade/assets/28189578/ea3c8117-839e-4005-8bc0-e4ab89d30224)

This is BTC/USDT 
![image](https://github.com/freqtrade/freqtrade/assets/28189578/70e6dc9c-1e28-45c8-bc4e-d2d10c798473)

This is ETH/USDT
![image](https://github.com/freqtrade/freqtrade/assets/28189578/30514f5a-1ba9-47a5-9b54-13c1ebc4eee5)

When I check on Binance they can be both leverage 100, not sure what's the problem here?

**Comment by xmatthias** [comment]
Leverage works in tiers, and i assume your order falls into the higher tier with your order.
the first level (up to 100.000) is 100x - but after that, it drops to 75x.
Your stake amount comes out at ~108.000 UDST (1742 * 64) - which clearly falls into the next tier.

![image](https://github.com/freqtrade/freqtrade/assets/5024695/3f00531c-7ead-49e3-bad5-1fc279d52a55)

While the tiers are constantly updated (though for dry run, we use a cached version) - i don't think they changed recently, at least not at the lower levels for ETH.
