### ISSUE TITLE
Adding Custom Data to Freqtrade Dataframe for Strategies

### ISSUE THREAD

**Issue by alexrmacleod** [freqtrade/freqtrade#8782]
Hello Freqtrade community! I'm working on a project and would like to incorporate some custom data into the Freqtrade dataframe to be used in my strategies. After going through the documentation, I couldn't find a specific example for this scenario. Could you please help me understand how I can add my custom data correctly to the dataframe, considering the appropriate time frame?

Additionally, if there are any specific functions or methods from the Freqtrade documentation that I should refer to for this task, please let me know. Your guidance would be greatly appreciated. Thank you!

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

A "freqtrade dataframe" is really just a pandas dataframe - so all pandas methods will work for this (most likely, you'll want to look at `merge` - usually by date).
there's no docs for this - and it's also not that easy to have a commonly applicable documentation, as in my experience, every "external" dataset is slightly different, which means it'll need different treatment.

Things to look out for if you want/need backtesting support:
* frequency (what do you have to do to match it onto a dataframe of your selected timeframe)
* date/timestamps (is the reference date in your data an open or close date?)

for live, you'll want to know if the data is available "on time"

say - a 1h candle that starts at 10:00 will be available at 11:00:01 (roughly). At what point exactly will the data be available? and what timestamp will that carry?

**Comment by alexrmacleod** [comment]
## Describe your environment

  * Operating system: osx Monterey 
  * Python Version: Python 3.9.13
  * CCXT version: No installed yet
  * Freqtrade Version:Not installed yet
  
## Your question


Thank you for your reply it has already helped me a lot! 

I have a specific requirement where I need to add a new column to the downloaded 4h OHLCV data. This new column will contain a normalized value derived from the historical trade data's cumulative volume deltas (CVD).

To utilize your backtesting and hyperopt ML improvement functionality, I would appreciate some guidance on the steps I should take. Here's my proposed approach:

1. Download the 4h OHLCV data from Freqtrade using the 'download-data' command.
2. Ensure the timestamps from the Freqtrade data align with my custom data, and verify the matching of the column I want to add and merge the data.
3. Create a function to merge my custom column to the dataframe. Could you please advise where I should place this function?
4. Update my strategy to incorporate the new column.
5. Run backtesting, following the examples provided in the Freq YouTube tutorials.

Would you kindly review these steps and let me know if I'm on the right track? Additionally, if there are any specific considerations or alternative approaches I should be aware of, please share your insights.

Thank you for your support and expertise!

**Comment by froggleston** [comment]
There is an example available for the Fear and Greed index: https://github.com/freqtrade/freqtrade/issues/6130

**Comment by xmatthias** [comment]
overall, it looks fine. 
in the end, it's "just" indicator - but this time not one calculated based off of the ohlcv data, but from external data.
For freqtrade though - it doesn't matter, and will just be another column (obviously assuming you don't "break" the existing dataframe).

As such, the `populate_indicators()` should be your place to start.
