### ISSUE TITLE
Extending freqtrade for a stock exchange

### ISSUE THREAD

**Issue by curiousHG** [freqtrade/freqtrade#8783]

**Comment by froggleston** [comment]
A complete rewrite and re-implementation of the exchange communication modules. So.... highly unlikely.

**Comment by curiousHG** [comment]
I am not requesting you to implement it. I want to create it on my own. Was just asking to know what are the key points in the exchange module I should think of and implement.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Freqtrade relies on ccxt to connect to exchanges - and as such, also on the structure ccxt provides.
I've directed everyone with this question to ccxt to ask if they'd be accepting a non-crypto exchange. If they do - it can be supported.
If they don't - then your best bet is to implement the ccxt interface anyway, so most of the things work out of the box.

You'll probably also have to look at other things like market open times - which for crypto markets are neglectible as markets are always open.

Please understand that from a capacity perspective, we'll not be able to provide much guidance in this.
I'd recommend to first be very familiar with freqtrade as it is - most likely by having contributed or worked on the code for some time (maybe look at the open issues / enhancements - maybe there's one that you feel like tackling).

**Comment by collinsherriff** [comment]
Can this be re-opened?

**Comment by xmatthias** [comment]
I don't see why if i'm honest.

ccxt doesn't support stock exchanges - and our stance on this topic didn't change - and won't change, either.

So unless you can say "yes, ccxt supports stock exchanges", i don't see any reason to open this issue - as it's not something we'll be working on, or will even consider adding should a PR be provided - not unless it's through ccxt (which unifies exchange access for us to use).
