### ISSUE TITLE
Previous candle opening/closing price

### ISSUE THREAD

**Issue by EmelyanovDev** [freqtrade/freqtrade#8784]
Guys, please tell me how to get the opening/closing price of the previous candle?

**Comment by froggleston** [comment]
In which function?

In populate_indicators, populate_entry_trend or populate_exit_trend:
`df['open'].shift(1)`

In custom_* functions:
```
df, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
candle1 = df.iloc[-1].squeeze()
prev_candle_open = candle1['open']
```

**Comment by perkmeister** [comment]
I think the OP was looking for the previous candle open, so actually `.iloc[-2]` needed.
In custom_* functions:
```
df, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
if(len(df)) <2
    return None
previous_candle = df.iloc[-2].squeeze()
previous_candle_open = previous_candle['open']
```

**Comment by froggleston** [comment]
I presumed they meant the current candle being the unfinished candle that isn't available yet, so "previous" is one back.

**Comment by perkmeister** [comment]
OK, but `df['open'].shift(1)` is that previous candle

**Comment by froggleston** [comment]
Well I hope that the OP can work out that shift(1), shift(2), iloc[-1] or iloc[-2] will fit their needs as appropriate.

**Comment by EmelyanovDev** [comment]
Thank you guys
