### ISSUE TITLE
Producer / Consumer question

### ISSUE THREAD

**Issue by dobremha** [freqtrade/freqtrade#8786]
Describe your environment
Operating system: Ubuntu 22.04.1 LTS
Python Version: 3.10.6
Freqtrade develop
CCXT 3.1.23
Freqtrade running in docker
Exchange: Binance
Question is for Dry/Live run, not backtesting.
Using ProducerPairList param in consumer bots.

I want to run 10 or more consumer bot's that are using same dataframe's from 1 producer bot (1m tf, let's say 50 pairs).
How can I disable that my consumer bot's download OHLCV data every loop ? They should use only OHLCV data from producer, inclusive entry/exit signals. Only producer should download OHLCV data every loop.
So I don't exceed the rate limits of Binance API, through downloading same data 10 times with 10 different consumer bot's.
Thanks!

**Comment by xmatthias** [comment]
You don't / can't.

producer / consumer mode is not made to replace downloading the data - but to spread signals (most likely also signals in a timeframe that's different to the original timeframe).

From a system perspective, there's no guarantee for the consumer that 
* the producer is always there
* the producer provides data all pairs
* the producer provides the data in time

If you therefore carefully look at the example in the [documentation](https://www.freqtrade.io/en/stable/producer-consumer/) - then you'll notice that the code there accounts for each of these scenarios by checking if the producer actually provided a dataframe.
