### ISSUE TITLE
I would like to set up Trailing_stop in production mode to be activated in 15 minute increments.

### ISSUE THREAD

**Issue by shio2345** [freqtrade/freqtrade#8787]
## Describe your environment

  * CCXT version: ccxt 2.1.96
  * Freqtrade Version: freqtrade 2022.11
  
## Your question
I am currently trading in production mode with Bybit.
trade mode : Derivatives (futures isolated)
timeframe : 15m
pairs : ETH/USDT

Traililng_stop is incorporated into the logic developed by myself.
I would like to set this position close (by trailing_stop) to operate in 15 minute increments, not in real time.
*If possible, we would like to set up ROI in a similar way.↑

The ideal behavior is for the trade close decision by Trailing_stop to be made only every 15 minutes, with price changes during that 15-minute period not contributing to the decision.

Please let us know if you have a configration setting that allows the above settings.

**Comment by xmatthias** [comment]
trailing stop works the way it's described in the documentation.
You can define price offsets, and different values to trail price while the trade is still below that offset - but nothing more.


if you need more flexibility - you will have to implement this in the [custom stoploss](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stoploss) documentation.

it behaves similarly to trailing stop - but allows you to define your own logic, which can be whatever you can imagine and implement.

**Comment by shio2345** [comment]
Thanks for the reply.
Try to set it up by referring to 'custom stoploss'.
Does the 'stoploss_on_exchange_interval' that can be set in the strategy file work the same way for trailing_stop?
Can stoploss and trailing_stop settings be handled the same way?

**Comment by xmatthias** [comment]
stoploss_on_exchange_interval doesn't impact the movement of the prices - but how often the physical order is replaced.
it's not tied to candles (it's just 1m starting "whenever" the first stop order is placed).

the default is 1m - but lower values can make sense if your stop moves in very quick / small increments.
