### ISSUE TITLE
Producer / Consumer "Get" log

### ISSUE THREAD

**Issue by dobremha** [freqtrade/freqtrade#8788]
Describe your environment
Operating system: Ubuntu 22.04.1 LTS
Python Version: 3.10.6
Freqtrade develop
CCXT 3.1.23
Freqtrade running in docker
Exchange: Binance
Question is for Dry/Live run, not backtesting.

Can I disable this log ?
2023-06-15 04:38:18,248 - ConsumerDry - INFO - [XRP/USDT:USDT] Get dataframe from producer "ProducerDry"

**Comment by xmatthias** [comment]
I don't think this log message is produced by freqtrade - but rather by the strategy itself.

The 2nd column is kinda a giveaway for this - as `ConsumerDry` is probably your strategy name.
if it were a freqtrade log message, then it would also start with `freqtrade.` .

**Comment by dobremha** [comment]
o man, bin ich doof
