### ISSUE TITLE
environment.yml is empty

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8789]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

For a reason the file environment.yml of the last few stable versions is empty.
The version 2023.2, I last installed, was around the usual 76 lines long.
My download source is GitHub.

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
The file was removed in #8220, but you're right, we should probably remove that file completely (i didn't really realize that we left an empty shell behind).

The [install with conda](https://www.freqtrade.io/en/stable/installation/#installation-with-conda) instructions changed, and are now installing everything via pip (so the installation is aligned, independent of the python distribution used).

A mixed installation between conda and pip does in general not work well, as there can be undetected version conflicts between the 2 types of packages (undetected by conda, you then see it when it fails).

The conda environment file did provide more problems than it solved, was almost always outdated (as well as not having dependencies pinned).

**Comment by myNextCoder** [comment]
I thank you, I would have read the docu, if I would have supposed a changement on your side. Since the file was empty, I was thinking of a small mistake, or even of a zip / unzip issue.

**Comment by xmatthias** [comment]
yeah that's not wrong - i've removed the file since on develop to avoid further confusion (github PR view doesn't make it straightforward to distinguish between a removed file, and a file that's been emptied but has been left there).
