### ISSUE TITLE
New miniconda installation

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8793]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.5.1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

The old way installing Freqtrade with environment.yml resulted in a Windows user profile (without any different software) of more than 6 GB. 
It was easy to install the solution according to your newly updated description in the documentation under Miniconda. Finally I got the usual messages, how to start Freqtrade and how to leave it. Without any errors during installation time. But the user profile in total is only about 600 MB. It is not possible to start the solution in my case. It seems, it is necessary to enroll an additional part, which used to be within environment.yml

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Profile size is irrelevant, and not something we can start to even try to help you.

the ONLY information you provide is "user profile size is now smaller". 
Based on that - all i can say is "yes, that's possible". 

If you get some errors or output, please share that.
otherwise, my answer is "yes, maybe windows cleaned some things up", or you're no longer using conda, but miniconda, which is by default a LOT smaller.

**Comment by myNextCoder** [comment]
The profile size may be somehow relevant, since I see the difference on one only machine. So we are sure, not comparing different Windows with different update states. Prior to install Freqtrade, I always delete the profile, never install any additional software. It is a Freqtrade-only machine. The difference in size comes due to huge difference of the size of the .conda folder in the user-folder. That means, the old-fashioned installation made .coda grow 10 times bigger than the new way. I gladly give you more information about the content / difference of the folder, if this may help. If you think, that the folder .coda is not the defining factor, I will inspect further, hoping to find the source of the problem, letting you know more asap.
Currently with the new installation I can start with 'conda activate freqtrade'. Now I have the freqtrade prompt. But sending then 'freqtrade -V' prints: 'freqtrade' is not recognized as an internal or external command, operable program or batch file. The freqtrade-folder stucture under the freqtrade folder, at which level I am, is present.

Not directly related:
You may want to add one step for Windows users, prior to send git clone https://github.com/freqtrade/freqtrade.git:
Download the Git installer for Windows from the official Git website and install it: https://git-scm.com/download/win
. . .this step makes the installation possible, but does not resolve the described issue.

**Comment by xmatthias** [comment]
> But sending then 'freqtrade -V' prints: 'freqtrade' is not recognized as an internal or external command, operable program or batch file. The freqtrade-folder stucture under the freqtrade folder, at which level I am, is present.

So you're missing the last step in the installation - which is `python3 -m pip install -e .`.


> You may want to add one step for Windows users, prior to send git clone https://github.com/freqtrade/freqtrade.git:
> Download the Git installer for Windows from the official Git website and install it: https://git-scm.com/download/win
> . . .this step makes the installation possible, but does not resolve the described issue.

we do have this - it's part of the [minimum requirements](https://www.freqtrade.io/en/stable/installation/#install-guide).
i don't see why windows users should need extra threatment. This section is valid for everyone  independent of the used operating system.

**Comment by xmatthias** [comment]
@myNextCoder did the above help you get your miniconda problem fixed?

**Comment by myNextCoder** [comment]
Very nice, to read your question, I thank you.
(My delay is due to a non-ticket relevant reason, I am about to entirely replace my hardware)
Since you and me already had discussions in February about a Miniconda-related issue, which prevented me from my work with the bots, I guess, the best thing is, to permanently switch to the container-model. I was changing back to Miniconda, because usually the handling is very easy. As Miniconda seems not to be the common way, for running Freqtrade, I might better resign of the easy Miniconda usability. The container-technology in addition, is an important knowledge-booster for me.

**Comment by xmatthias** [comment]
well miniconda is a supported way of installing python, but it will not replace the other prerequisites (never did), nor will it replace following all installation commands (you've almost certainly missed the above step).

**Comment by myNextCoder** [comment]
I was about to install all requirements, but the system asked me an innumerable amount of small substeps, which can not anymore be handled, as I want to have up and running multiple bots. With containers, I can update Freqtrade in seconds.
