### ISSUE TITLE
Trailing stop loss for different pair 

### ISSUE THREAD

**Issue by thunderwin** [freqtrade/freqtrade#8795]
since different pair has their own Volatility, we need each Trailing stop-loss for different pair. , isn't it? 
or ?  we can adjust leverage for different pair to achieve this goal?

**Comment by stash86** [comment]
search for `custom_stoploss` in the docs

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

[`custom_stoploss`](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stoploss) will allow you to do this.
