### ISSUE TITLE
Cross check coins in the backtest

### ISSUE THREAD

**Issue by MohamedDhouib** [freqtrade/freqtrade#8797]
## Describe your environment

  * Operating system: windows
  * Python Version: 3.8 (python -V)
  * CCXT version: ccxt==3.0.50 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.03 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Already searched on internet/doc a lot but coudln't find anything helpful.
So the logic is very simple, i have a n indicator and i want to check the max value of this indicator (among all coins values) and get into a trade on the coin that has this max.

Dummy example: imagine i want to get into the coin that has the max volume in the last candle from my tokens_list. how can i compare between all candle to get that info before deciding buy/sell trend?

Thanks in advance!

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
you can probably use [informative pairs](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs)
or [`get_analyzed_dataframe()`](https://www.freqtrade.io/en/stable/strategy-customization/#get_analyzed_dataframepair-timeframe) for this.

The first will always provide an empty dataframe, while the latter will provide analyzed dataframes - but may return old candles if a pair was not analyzed in this candle yet.

**Comment by MohamedDhouib** [comment]
So if i understand well what you suggest is to use get_analysed_dataframe(token) and cast token with my static list elements (for loop for ex) and get the values of the column i need in populate_indicators in order to get the max?

**Comment by xmatthias** [comment]
more or less, yes
as said, there's caveats with `get_analyzed_dataframe` - but all the info is on the strategy-customization documentation page (even if it's not directly linked here).

**Comment by MohamedDhouib** [comment]
I have done something like this, do you see an issue? I'm still having doubts about it. I suppose that once it get in populate_buy_indicators all dataframes have been populated with indicators (is that true?)
`

        class test(IStrategy):

                all_dataframes = {}

                def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                    dataframe['super_indicator'] = ...
                    self.all_dataframes[metadata['pair']] = dataframe

                def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

                        dataframe['buy'] = 0

                        # Get all pairs' dataframes with populated 'super_indicator'
        
                        super_df = pandas.concat({pair: df['super_indicator'] for pair, df in self.all_dataframes.items()}, axis=1)
        
                        # Compute the maximum 'super_indicator' for each row (time) across all pairs
                        dataframe['super_indicator_max'] = super_df.max(axis=1)
                        # Assign 1 to 'super_decision' where 'super_indicator' equals 'super_indicator_max'
                        dataframe['super_decision'] = 0
                        dataframe.loc[dataframe['super_indicator'] == dataframe['super_indicator_max'], 'super_decision'] = 1

                        dataframe.loc[
                            (dataframe['super_decision'] == 1)
                            , 'buy'] = 1

                return dataframe


`
Thank's in advance @xmatthias!

**Comment by xmatthias** [comment]
well all_dataframes is never assigned, really so that'll not work (but i assume that's a copy/paste and remove error).

>  I suppose that once it get in populate_buy_indicators all dataframes have been populated with indicators (is that true?)

No, that's wrong, and not something you can rely on.

**Comment by MohamedDhouib** [comment]
Sorry, just updated it, forgot about `self.all_dataframes[metadata['pair']] = dataframe` in the populate indicators.

**Comment by xmatthias** [comment]
In general, i'd not recommend doing this.
it's implicitly a memory leak - and you can't rely on this to be there for every pair.

you can completely replace this with something around this:

``` python
for pair in self.dp.current_whitelist():
    other = self.dp.get_pair_dataframe(pair=pair, timeframe=self.timeframe)
    # Do some logic like calculating indicators
```

you can also use get_analyzed_dataframe, but as mentioned above - you can't rely on all pairs being there (you can't do that with your method, either).

**Comment by MohamedDhouib** [comment]
Thanks, i'll trt something like that, i'll close this issue in the meanwile.
