### ISSUE TITLE
why my time  cant sync

### ISSUE THREAD

**Issue by ricohrh** [freqtrade/freqtrade#8811]
![time1](https://github.com/freqtrade/freqtrade/assets/103866925/14265db7-888d-4116-8f70-5bbfe9c33405)
![time2](https://github.com/freqtrade/freqtrade/assets/103866925/2857b828-76d4-44ce-a6d2-208777b97e03)
![time3](https://github.com/freqtrade/freqtrade/assets/103866925/07cb52af-f440-4cda-a624-e4037a6415ef)

My PC time is timestamp ctl timesync status. Why is my Telegram bot not synchronized

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.
