### ISSUE TITLE
Why is the time and telegram bot not synchronized

### ISSUE THREAD

**Issue by ricohrh** [freqtrade/freqtrade#8812]
## Describe your environment

  * Operating system: debian
  * Python Version: python3.9  (`python -V`)
  * CCXT version: 1.60.92+ (`pip freeze | grep ccxt`)
  * Freqtrade Version:  freqtrade 2023.5.1
  
 question
My PC time has already been synchronized. Why cannot I synchronize with the telegram bot
![time1](https://github.com/freqtrade/freqtrade/assets/103866925/a2d37aa4-166a-48cf-904f-fa94a7ffd047)
![time2](https://github.com/freqtrade/freqtrade/assets/103866925/3e259e67-e25e-4ca6-a10f-058f588261fa)
![time3](https://github.com/freqtrade/freqtrade/assets/103866925/6ba376fd-534f-4195-a67a-a7ea34c154a1)

**Comment by xmatthias** [comment]
Are you using docker, or a native installation?

In general (though i didn't check for this specific occurrence) - most of freqtrade is using UTC timestamps (aligned with almost all exchanges).

**Comment by ricohrh** [comment]
hi  i use docker ..
Does the log time of freqtrader differ from that of the local machine, which has an impact on transactions
![date1](https://github.com/freqtrade/freqtrade/assets/103866925/b7f36d45-a587-47fb-8c1f-47fb03b86314)
![date2](https://github.com/freqtrade/freqtrade/assets/103866925/d03656e1-402e-4cbf-96a0-662e9b77e8bf)

**Comment by xmatthias** [comment]
The log-time will be in system time / timezone.
As you're using docker, this corresponds to the date / timezone within the docker-container.

you can probably use something around `docker compose exec freqtrade date` to see the date within the container - which should correspond to the log messages.

As long as the time is set correctly, it'll be fine (which means the timestamp in UTC is correct). The Timezone is a "user visibility only" part - which is really irrelevant.

If you want the timezone within the container to be aligned with the host, you'll have to mount the relevant information into the docker-container.

instructions for this vary a bit depending on where you look for (and what the host OS is).
you can try adding the following mount points to your compose file 

```
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
```

**Comment by ricohrh** [comment]
ok thank
