### ISSUE TITLE
ModuleNotFoundError with custom indicators in hyperopt execution

### ISSUE THREAD

**Issue by djwatt3** [freqtrade/freqtrade#8813]
## Describe your environment

  * Operating system: Unix (Debian 11)
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.5.1 (`docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Already searched on internet/doc a lot but coudln't find anything helpful.

getting error `ModuleNotFoundError: No module named 'indicators'` when try to hyperopt parameters because I developed some custom indicators in the strategy folder, they work when execute backtesting or trade, not when execute hyperopt.

`docker compose run --rm freqtrade hyperopt --config user_data/config.json --strategy CM_Braid --epochs 10 --spaces buy roi --hyperopt-loss OnlyProfitHyperOptLoss --timerange=20230517-`

Error Ouput:
![image](https://github.com/freqtrade/freqtrade/assets/6772297/f89e9c3c-12de-4352-8925-7cf7cd957de6)

my folders tree
![image](https://github.com/freqtrade/freqtrade/assets/6772297/ada5d291-27af-4fd0-976d-4be11ec98d6a)

import custom indicators in strategy file
![image](https://github.com/freqtrade/freqtrade/assets/6772297/fb2ea92d-a821-4909-b7c9-8c6430ffbff9)

what is the best practice to include custom indicators in the strategies?
my goal is to write more custom indicators, then import them in the strategy file and optimize the parameters before to run the bot in live mode

**Comment by xmatthias** [comment]
your imports (`from indicators.*`) suggest that it's an installed package (or at least a package), but it's not.

it'll work in regular mode as python appends the current path to the searchpath automatically - but that's unavailable (and unreliable) during hyperopt, where all modules must resolve from cwd (you can open a python console from your regular execution directory and run `from indicators.xxx import XXX`, and you'll see it will not work).

You can try to create an empty `__init__.py` file there  to see if that helps - otherwise i'd recommend to actually make it installable (and move it out of the strategy folder).

**Comment by djwatt3** [comment]
@xmatthias Thanks for your quickly answer.

I tried but both solution didn't work,
also installed freqtrade from scratch without docker but still don't work with custom external methods or as local package installed.

TEMP SOLUTION: 
- currently I solved with the rudimental method to include custom indicators class inside the strategy file.


I think we can leave the question open and waiting if anyone has or finds a better and scalable solution.
Thanks and compliments for your work.

**Comment by xmatthias** [comment]
> as local package installed.

The assumption is that it's installed in the environment freqtrade is running.
if you're running docker, that install must happen within docker (obviously).

The base for this is simple - the module must be resolvable.
so with activated virtual environment, you can switch to ANY other directory and import that module (`from customindicators import whatever`). 
that's the definition of an installed module.
if that doesn't work, then your "installation" didn't work properly.

**Comment by djwatt3** [comment]
I tried with docker building a custom image with my package installed and in virtual environment from scratch,
maybe I wrong something with package build and installation because I'm not expert python developer but js/ts dev

pip3 freeze: 
![image](https://github.com/freqtrade/freqtrade/assets/6772297/51c884e7-65bc-4770-a465-669e51c3439f)

folder tree:
![image](https://github.com/freqtrade/freqtrade/assets/6772297/f5fd14a9-6780-44ee-91a6-9e6dd69046d6)

trying to import in python3 console:
![image](https://github.com/freqtrade/freqtrade/assets/6772297/3cd87d64-b350-496b-807a-5265634b461d)

**Comment by xmatthias** [comment]
don't do this from within the strategy directory - but from a dedicated repository / project outside of the freqtrade directory ;)
Freqtrade will (optionally recursively) parse through that directory on startup - so you may end up with slow startup times for no good reason.

---

It's ... difficult to look at this from that perspective - as a lot of info is missing (contents of setup.py, ...).
you may need to import directly from indicators - (that's the actual package name, even though setup defines it as "customindicators").

Eventually, you may want to look at [technical](https://github.com/freqtrade/technical) for how we have set this up (it'll just be python functions after all).

**Comment by xmatthias** [comment]
Closing this assuming the above helped you get this sorted.

let me know if that's not the case and you still need help.
