### ISSUE TITLE
Is it possible to trade on multiple exchanges at the same time?

### ISSUE THREAD

**Issue by akatasonov** [freqtrade/freqtrade#8815]
## Describe your environment

  * Operating system: Ubuntu 22
  * Python Version: 3.11
  * CCXT version: 3.1.17
  * Freqtrade Version: 2023.5
  
## Your question

Is it possible to trade on multiple exchanges at the same time? One example would be a delta neutral strategy.

**Comment by xmatthias** [comment]
You can use [multiple instances of freqtrade](https://www.freqtrade.io/en/latest/advanced-setup/#running-multiple-instances-of-freqtrade) to trade on multiple exchanges (or different strategies).

Each bot instance will be per exchange.
