### ISSUE TITLE
Stochastic fast vs slow

### ISSUE THREAD

**Issue by zeytindali83** [freqtrade/freqtrade#8816]
Hello,

What is the difference between stochastic slow and fast?

Also, when I open the stochastic indicator on TradingView, which one appears?

In the default settings, it shows %K length 14, %K smoothing 1, and %D smoothing 3.

What is the exact translation of these terms?

Thank you in advance.

**Comment by stash86** [comment]
Please get used to filling out the issue template. Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

----------------------------------------------

Your question isn't related to freqtrade, but trading in general. Google might be able to help you for that.

**Comment by xmatthias** [comment]
we're not tradingview support, but we're trying to support freqtrade here.

clearly the wrong support channel.
