### ISSUE TITLE
Regarding the use of the forceenter API and the issue of position adjustment

### ISSUE THREAD

**Issue by Hotsunrize** [freqtrade/freqtrade#8817]
## Describe your environment

  * Operating system:  latest freqtrade docker image
  * Python Version:  latest freqtrade docker image
  * CCXT version:  latest freqtrade docker image
  * Freqtrade:2023.5.1
  
## Your question
First question:
Does the callback function in the strategy, such as custom_stoploss, also affect the positions opened using api forceenter?，I have found that the positions opened using the forceenter API are not affected by the Leverage Callback function.

Second question:
How to adjust positions? For example, if I have a position in the BTC/USDT:USDT CONTRACT market and it has doubled in profit, I want to close half of the position. How can I do this? Do I have to do it in the adjust_trade_position callback? Does the Trade object  or somthing have a method to directly close half positions? 

such as 

```
 def custom_stoploss(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,current_profit: float, **kwargs) -> float: dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        last_candle = dataframe.iloc[-1].squeeze()
        flag_s_l = -1
        if trade.is_short:
            flag_s_l = 1
        atr = last_candle['atr']
        open_rate = trade.open_rate
        atr_swing = ((atr * 2 )/open_rate)

        if current_profit >= atr_swing and current_profit < atr_swing * 3
            return stoploss_from_absolute(open_rate, current_rate, is_short=trade.is_short) * flag_s_l * trade.leverage
        elif current_profit >= atr_swing * 3:
            //Close half of the position directly here.  trade.stake_amount = trade.stake_amount/2 dose it work？？
        return atr_swing * flag_s_l
```

**Comment by xmatthias** [comment]
forceenter accepts leverage as parameter. If that's set, then that'll be used (if supported, obviously). 
If it's not provided, the regular callbacks will be used.
If a position is already open - the force_enter will act as a "double position"- in which case leverage will NOT be changed (aligned with regular behavior, as stated in the documentation), and "side" (long / short) will be adjusted to the direction the trade is already open (forceenter will always buy on long positions, even if the call was "short").


Same goes for exiting - that endpoint accepts an optional "amount" parameter, which can be used for partial exits.
