### ISSUE TITLE
Hyperopt question about diff. trade count

### ISSUE THREAD

**Issue by EmelyanovDev** [freqtrade/freqtrade#8820]
Guys, please tell me why my number of trades changes during hyperopt if my hyperopt only changes minimal_roi, stoploss and trailing_stop? This only applies to exiting a trade, not entering. ![image](https://github.com/freqtrade/freqtrade/assets/86175307/c4a1a445-0961-4581-a44c-1d9b1269d59f)

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Different exit levels will result in different trade duration - subsequently freeing up capital earlier / later - which will cause subsequent entries on the same / different pairs to be different.
