### ISSUE TITLE
Rename and home RPC structure proposal 

### ISSUE THREAD

**Issue by creslinux** [freqtrade/freqtrade#884]
Good Morning!

I would like to refactor the existing RPC directory, classes, defs as below. 
This is to better reflect the nature of the files/classes/defs to support other clients - such as rest

> freqtrade/rcp/ - rpc.py
> ......................- rpc_manager.py
> ......................- telegram.py 
> 
to: 
> freqtrade/clients/client_manager.py  (was rpc_manager
> ......................-common/client.py    (was rpc.py - but is agnostic to what client calls)
> ......................-rpc/telegram.py
> ......................-rpc/*discord.py    (example future RPC client
> ......................-rest/*cmd line.py  (example future rest cmdline rest client
> ......................-rest/*web.py          (example future rest web client
>

**Comment by gcarq** [comment]
I agree that `rpc` is a little bit misleading, but would prefer to hold all logic in one package and just rename that. For example:
```
some_package/rpc.py
                         __init__.py
                         rpc_manager.py
                         telegram.py
                         discord.py
                         rest.py
                         ...
```

Clients which consume the REST interface should be in own repositories IMO (i.e.: freqtrade/web-ui, freqtrade/cli).

**Comment by xmatthias** [comment]
i agree on the proposed structure @gcarq - even though i would probably not use "some_package" ... ;)

not sure about own repos for clients - web-ui yes, definitely - but a script to control the bot from the comandline could be included as "basic" script ... i did miss that a few times already

**Comment by gcarq** [comment]
Yea the CLI could also be a simple script within the repo, as we have all dependencies already included (only `requests` should be required).

**Comment by creslinux** [comment]
Scrap the PR and build a rest cmdline client server in rpc/rest_srv.py and rest_cmd.py?

**Comment by xmatthias** [comment]
`RPC` is not that wrong if we consider it's meaning as [Remote Procedure Call](https://en.wikipedia.org/wiki/Remote_procedure_call).

Also, we've now got the rest-server and rest-client (in `scripts/`- since it can be run without installing freqtrade).


I don't think we'll rename this in the forseeable future, so i'll close this issue.
