### ISSUE TITLE
Can I turn off bot candles retrieval, when acting as Consumer?

### ISSUE THREAD

**Issue by dpd123** [freqtrade/freqtrade#8840]
## Describe your environment

  * Operating system: Linux/docker
  * Python Version: 3.10.11
  * CCXT version: 3.1.5
  * Freqtrade Version: 2023.5
  

I am working on a strategy concept that uses multiple dry-run bot instances running my strategy. The dry-run bots run forever, so that I can analyze their Trades continuously, to maintain a list of top performing pair:parameter sets, over time. Graceful and immediate adaptation, to macro-market-conditions, is the goal. 

When one dry-run bot is statistically outperforming another recently, and they were hyper-optimized on different optimization theories, I can pick pairs as they emerge as better performers on whatever bot. I don't have to choose which risk approach to embrace, as the stats will pick the best optimization for me.

I think this is using the Producer/Consumer feature, with N:1 configuration, in a great way... possibly one of the reasons this feature was implemented by some clever person!

In reality, I am planning this on a large scale, running a bot army of e.g. 32 dry-run bots, each with their own optimization theory. Each bot is running on 100 futures pairs. API limits are exceeded WAY before this is possible, and I'm trying to find a way around it.

I would like to create a relationship like this:

![image](https://github.com/freqtrade/freqtrade/assets/15114181/d7a1f08b-6114-4b3f-9780-e9bed6e5ee6c)

From this diagram, hopefully you can understand that only ONE bot needs to be asking Binance for candles, the Candle Producer bot. Everyone else can throttle fast and consume away, with acceptable lag as the dataframe propagates forward. CPU and memory issues are my own problem. 1 second throttle is fine in this diagram, for 3 seconds total latency from candles to live trading signals, I'm fine with this.

All of this seems quite possible with the awesome Producer/Consumer functionality.
The problem is that I have 5 bots in the diagram, making identical and redundant Binance API calls to populate totally identical candles, for no reason. In reality, it might be 34 bots on 1 minute candles, which Binance is not OK with. If I have to throttle down to a 60 second interval, to preserve API weight, stoploss goes wrong obviously.

My actual question is quite simple:
----------------------
Can I disable candle retrieval from the exchange, for a running bot, and simply loop on the throttle interval to process incoming Producer dataframes, which already contain the pair candles anyway?
----------------------

Any trick or hack will do, or just some ideas on how to make this happen elegantly.
This will eliminate API-call-compromises, and ease up on the Binance servers and network traffic by a huge amount.

Any ideas most welcome, thank you!

**Comment by xmatthias** [comment]
Short answer, no.

Producer / consumer mode was implemented for heavy indicators (e.g
 Freqai producer), sharing its data around and reducing the calculation to one bot.

We cant however rely on the upstream bot to be always present, so a stoppage of the producer would mean that open trades are no longer processed.
Candles are therefore the base for the bot, and any producer (one or multiple) can provide additional indicators (columns) to the strategy.

As the documentation points out, you should also cover cases where the upstream dataframes are missing without crashing your strategy.

Your best way is to scale horizontally to multiple machines to work around api limits.

**Comment by dpd123** [comment]
> Short answer, no.

Too bad, but thanks for the reply!

> We cant however rely on the upstream bot to be always present, so a stoppage of the producer would mean that open trades are no longer processed. 

I understand the logic for this design, for safety, for the use cases you designed Producer/Consumer about. I am outside of the designed use, with middle-layer dry-run bots that aren't doing anything more important than compiling win/loss stats...so I understand why you don't prioritize my statistical-bot-army case.

> Your best way is to scale horizontally to multiple machines to work around api limits.

I think I have to do more than scale across multiple machines (or containers)...I have to distribute docker containers across IP routes and use additional static IPs, as Binance's errors in the freqtrade log are IP-based limits. More computers won't fix IP limits, unless you're talking about more cloud instances with unique IPs? But I get what you mean.

This does give me an idea, however: configure the dry-run instances (middle layer), whose only job is to run strategy code on Producer candles (first layer) for informative purposes, to use additional non-relevant exchanges! 

Since I am only using the Producer's dataframe (including Binance OHLCV) for statistical analysis, I'm hoping there be no problem getting OHLCV data from ByBit, throwing it away, and consuming the Producer's data from Binance instead. Instead of merging the informative dataframe, I just use it directly. Then I forward the real Binance-based processed dataframe, to the final consumer (3rd layer).

I understand this is terrible practice for any live-trading bot. But I will fetch REAL Binance candles like a normal person, on the final, live-trading consumer bot in the chain (3rd layer). So that bot runs normally, with real Binance fetches, to implement safety measures as designed. I'll have 2 bots fetching candles instead of 34, which will work fine.

I'll be hitting random exchanges with traffic, but they can afford it :) So I'll run out of exchanges that can successfully fetch_OHLCV for trivial use, before I have to purchase more static IPs and cloud instances :)

**Comment by xmatthias** [comment]
All actual prices will then however be based on these "irrelevant" exchanges, so your results will not be comparable (diff. Moves, diff. Prices at the same point in time).
Thats just as wrong as that a strategy working on binance works somewhere else or viceversa, which is clearly not true (at least not for short timeframe strategies).
Macro-movements are mostly similar, but micro movemets are not, leading to completely different prices.


Yes, scale horizontally assumes more vps's to me, which automatically gives you more ips, which dont necessarily need to be static.

**Comment by dpd123** [comment]
Looking at this code from the producer/consumer docs:
```
producer_dataframe, _ = self.dp.get_producer_df(pair)
        if not producer_dataframe.empty:
            merged_dataframe = merge_informative_pair(dataframe, producer_dataframe,
                                                      timeframe, timeframe,
                                                      append_timeframe=False,
                                                      suffix="default")
```
I haven't actually tried it yet, so I'm sorry if I'm getting the logic wrong.
But I'm supposing that this is a synchronous call to the producer, which retrieves the producer's DF in its entirety? Including OHLCV. 

Is there a reason I can't use the producer dataframe directly (producer's OHLCV included) and return it to the rest of the bot loop? I guess there could be a length discrepancy causing errors, so I'll fix that in code to make sure it is the same number of candles, and make sure container clocks are synced (all containers are on the same computer.)

I agree, I can't use ByBit price data to inform a strategy using Binance pairs, that won't work well. I'm talking about replacing the ByBit candles with Binance candles instead of using the merge function, just to get around the hard requirement to do a additional candle fetch for 100 pairs, when I already have that data and API limits are a problem. Thanks for humouring me!

**Comment by xmatthias** [comment]
Pricing data for trades is not candle data.

**Comment by dpd123** [comment]
I'm not sure what your reply means, but lots of the terminology is new to me so I think I'm just not expressing myself clearly. 

I'm talking about configuring a freqtrade bot to retrieve ByBit candles, and then ignoring them, to proceed directly with the Producer's candles (from Binance) in the Consumer to inform trades. The exchange is Binance, the candles I work with are Binance (from the Producer's DF), the trades are on Binance.

Using ByBit as the fetchOHLCV target, is just a kludge to get around API limits since the Consumer bot can't function without real exchange data, even though I don't use it for anything.

(Personally, I would rather change "binance" to "bybit" in the config file, than buy more cloud instances, maintain them all, etc., it's a lot less work for the same result, but agree to disagree about that!)

Ideally for my case, there would be a "dummy" exchange allowed in config, that does no network operations but returns a meaningless dataframe so that Producer/Consumer chains can run without duplicating FetchOHLCV calls that bring in data that isn't needed. Until I try putting this stub in the codebase myself (I must be the only one that would benefit?) "ByBit/Huobi/Kraken" may as well be "Dummy" in practice.

You might think it's weird, but this general concept seems to be working:

- dry-run 3,000 pair-parameter sets on a big computer, running 30 freqtrade containers constantly
- each bot is focused on a different "optimization theory" that works better in certain market phases than others (pairs all have their own independent parameters that are optimized in a loop)
- use the REST API to analyze and choose the best 20, that have stayed in profit recently (e.g. 72 hours)
- use this to make a RemotePairlist for the real trading consumer
- trade for real, with the top 20 running winners, copying the dry-run trades, because they mysteriously maintain great returns, and I might never know why :)

The only reason I'm pursuing this, is that I noticed that the top 20 performers in dry-run, STAY in the top 20, for a surprisingly long time, with a surprising number of positive trades, while the losers keep losing. This keeps happening in a highly statistically significant way, enough that I can't ignore it.

This is looking very promising so far, and is providing edge that I can't replicate with backtests and walk-forward backtesting, I've tried and it's just not the same as this awful brute force concept, in dry-run... but it works and that's what matters! My immediate block moving forward with this, is API limits, so I'll do whatever it takes to side step the problem.

It's not the typical use for Freqtrade, OR the way it was designed, but AFAIK it's the only platform that can make this work because of some very cool features that plug together, and happen to make this all possible! Nothing else I've tried even comes close.

**Comment by xmatthias** [comment]
your "sidestep" is wrong, not considering (or knowing) how trading actually works.

pricing for trades (trade entry price, trade exit price) is **NOT** using candle data (except for backtesting), but is using exchange data (usually orderbook).

You'll get that from bybit, which WILL differ from binance, therefore your approach is in my opinion wrong.

Canldes themselfs are irrelevant for actual bot operations for anything other than defining a signal, which means caculating indicators in one method, and assigning signals (enter_long, exit_long, ...) in another method (where it all could be consolidated into one method, too  - but the separation helps people wrap their head around it.

There's other methods around api limits if you look around carefully (proxy projects for different exchanges). We'll neither support operation with these, nor help you by linking to it (if the proxy has a problem, the "world" stops for the bot) - but that should be you way to approach this.

---

Quite honestly, in my experience, people saying "i can deal with the consequences of xxx" are the first to complain when their approach fails (in your case it would be "not using native candles", but i know the upstream will always be there).
It's probably fine for dry-run to not have "native" candles - but on live, you can lose real money- so this is not an approach  i see us supporting.

If you think otherwise, you're free to contribute such a feature via Pull Request (obviously with the assumption that it's either very minimal / no maintenance). 
We'll still have a look and decide if it's really worth the added maintenance effort (if there's good tests covering that case, and the diff is not large, it's probably ok, but no guarantees).

Pending a PR from you, i consider this topic as finished with this - so don't expect any further answer from my side.

**Comment by dpd123** [comment]
Ah, I see. You're right, I had not considered the order book data, thinking the OHLCV was the whole issue when there's more to consider. Thanks for the tip, it indeed makes the "side step" a bad approach altogether.
I'm not the type to find creative misuses, and then complain "it's broken!!!", but I am grateful that you're willing to discuss why a conceptual idea is misguided. Thanks for your time!
