### ISSUE TITLE
Hyperopt param combinations

### ISSUE THREAD

**Issue by Arivadis** [freqtrade/freqtrade#8844]
* Operating system: ____Ubuntu 22
  * Python Version: _____ 3.10
  * CCXT version: _____ 3.1.44
  * Freqtrade Version: ____ 2023.2
  
Hello!

Hope You are doing fine!

I have a question regarding hyperopt parameters combination.

Lets imagine we have 3 parameters like:
buy_1 = IntParameter(5, 20, default=10, space="buy", optimize=True)
buy_2 = IntParameter(5, 20, default=10, space="buy", optimize=True)
buy_3 = IntParameter(5, 20, default=10, space="buy", optimize=True)

Let's say we somehow compute an indicator using this hyperopt values and the indicator returns true or false(buy/sell, 1 or 0, or...), so the entry condition does not need any additional values in populate_entry method to compare with.

If we want to use all 3 computed indicators to buy/sell - that is pretty clear and described in documentation, as well as if we want to use different combinations of this paramas - just add new param to each like 
`buy_1_enabled = BooleanParameter(default=True, space="buy", optimize=True)`
 and optimize it. This way we can get all combinations **of these 3 parameters = 8(+1 where false,false,false).**

My question - is there an elegant way to limit N of parameters used in entry/exit condition? Such as **Itertools.combinations()** provides, so we can set N of params we want be used as current epoch combination, for example, N=2 =>[(true, false, true) or (false, true, true) or...], where we will get combination of 2 parameters only, from N parameters max(in this case from 3 max).

For now I could only come up with 1 solution such as:
Push all current epoch params to list in populate_entry 
`current_list_of_params = list(self.buy_1.value, ...)`,
 make a constant with all possible combintations 
**list_of_comb** N=2 =>[(true, false, true), (false, true, true), ...],
 create new hyperopt space in range of max possible combinations - 
**buy_max_comb** = IntParameter(0, 2, default=1, space="buy", optimize=True) - where this integer will generate what combination(index) of params to use form list **list_of_comb**.

So every new epoch we  => get the index of combination as self.**buy_max_comb**.value in **list_of_comb**=> append to entry_cond = [] only params with value "true" in **list_of_comb**[self.**buy_max_comb**.value] => reduce()= append to df =>done.

All this seems cumbersome and hard-won to me. Perhaps there is an easier way to do this kind of manipulation?

I would be grateful for any thoughts.

**Comment by xmatthias** [comment]
If i understood you right - you can probably use [dynamic parameters](https://www.freqtrade.io/en/stable/advanced-hyperopt/#dynamic-parameters) as shown in the documenation.

Parameters for hyperopt **must** however be pre-defined, so hierarchical spaces (only optimize RSI if RSI_enable is True) is unfortunately impossible (so even if RSI is disabled, it'll always check for all RSI values eventually, even if they have 0 impact).

As such, you also cannot have one parameter saying "use 5 parameters" - and then dynamically generate 5 parameters.
while that's possible, and that value will eventually change as part of hyperopt (if it's part of the space, obviously), it will NOT generate 7 parameters for one epoch, and 2 for the next epoch, even if you generate these parameters as part of a list.

Hope this helps anyway.

**Comment by Arivadis** [comment]
Hello!

Thanks for answer!
"""
Parameters for hyperopt must however be pre-defined, so hierarchical spaces (only optimize RSI if RSI_enable is True) is unfortunately impossible (so even if RSI is disabled, it'll always check for all RSI values eventually, even if they have 0 impact).
"""
We discussed it before [https://github.com/freqtrade/freqtrade/issues/8513], it is pretty clear.



My purpose is to use only 2 of N possible parameters for entry condition(different 2 values combination of possible, as combination(not permutation) every new epoch), and I know I cant just generate 2 of them, so all N predefined params will be always in hyperoptimization, even if they have 0 impact.
That is looks like:
If we have param1, param2, param3 => we get all possible 2 values combinations: param1+param2, param1+param3, param2+param3. Each epoch we can use 1 combination only to make entry consition.
the 4-th space will choose what combination to use in current epoch by number like:
`buy_comb = IntParam(0,2,def=0) `=> by defoult will use the very first combination(param1+param2) as entry condition(for example by indexing in possible combinations list.

Thank You!

**Comment by xmatthias** [comment]
Id you're **only** looking for combinations, you may also use categorical.
It may give you more control over the actual parameter combinations, if you know already that param1+param3 doesn't make sense, for example.

What youll loose is the actual direction.
With ints, its pretty easy for the optimization to work in one direction lnly (param1 -> higher is better).
Categorical features will not really have this i think, as theres no clear direction in explicit comparisons.

Best think about the parameters as actual parameters that all change independent from each other, how its beat for _your_ usecase is difficult to determine, as there are usually several ways to get what you need.

**Comment by Arivadis** [comment]
I thought about categorical parameters, the only problem I see - a lot of combinations have to be hardcoded in case if there are 10+ parameters.

"""
Categorical features will not really have this i think, as theres no clear direction in explicit comparisons.
"""
Ok, I did not think this way, but I see it makes sense. 

Thank You!

**Comment by xmatthias** [comment]
You can always use range or list comprehensions to generate the lists in a categorical parameter.
As long as the result does not contain random elements (reproduces the same output every time), it should be fine.

Might become tricky at some point, but python will allow that for sure

**Comment by Arivadis** [comment]
Ah, I see now. Just generate list and past it to categorical parameter as range, so easy.
Good idea, thank You!
