### ISSUE TITLE
Informative Pair Question

### ISSUE THREAD

**Issue by erhangunay** [freqtrade/freqtrade#8845]
Hello,

I would like to trade with only BTC/USDT:USDT futures pair using BTC/USDT Spot data.

Is it possible via @Informative?

Since I have written "futures" in my config, I could not manage to access BTC spot data.

**Comment by froggleston** [comment]
No. You have one exchange object per bot instance, and this is tied to the market type, i.e. futures or spot.

**Comment by xmatthias** [comment]
it actually depends a bit.
`@informative` has an (optional) kwargument parameter candle_type - which you can set to spot or futures (and a few other values you didn't ask for). It's in the  collapsed "full documentation" section of the [`@informative`](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs-decorator-informative) documentation.

Depending on the exchange, you MAY be able to get spot data on futures bots and viceversa. 

It's however untested for which exchanges this actually works reliably - but in theory, it should be working for most exchanges, and should fail for other exchanges, but a test / comparison between the provided dataframes shouldn't be a problem to confirm if it works for your choosen exchange.

**Comment by froggleston** [comment]
Ah good to know - I wasn't aware of this!

**Comment by erhangunay** [comment]
Thank you all
