### ISSUE TITLE
Wrong price in dry run, do not even close to order book

### ISSUE THREAD

**Issue by Bgsolid** [freqtrade/freqtrade#8846]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: latest 3.10.6.
  * CCXT version: 3.1.44
  * Freqtrade Version: 2023.6.dev, not using docker
  
## Your question

Hello!

I have a problem that persist and cant make it right alone with myself.
Installed everything been told, downloaded data, adjusted config.json and strategy, succesfully backtested it and hyperopt, then by backtesting again the results of hyperopt and backtest aligned.
So it seemed proper.
But then I started trading in dry-run mode, with the below config, and everything goes wrong, do not match the price with the real order book.
Like for a short positio  entry i got 6.54 price instead of somewhere close to a 6.17 mark price (the highest of those candles were 6.18), but i receive a totally different price, so my openings are already in loss.
I tried to switch from 'other' to 'same' in price side, did not make the process better. 

What I want is to have the bot calculate on each candle close, and act upon it, not in the midterm.
Like if I use 15 min candles, analyze on 0:00, 0:15, 0:30...etc., and act upon the result it got, if it found entry logic valid, open a position. But not on every minutes, therefore using 15 min data is totally misleading.

So, I think I understand that the answer relates to the selected interval and the fetch interval difference, just dont understand how and why.
Please help me to know this logic better. 

My config.json is below (using 'blablabla' intentionally in this ticket to hide my personal data)

Thank you,
Gabor

--------

{
    "max_open_trades": 15,
    "stake_currency": "USDT",
    "stake_amount": 60,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 30,
        "exit": 30,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1
    },

    "exchange": {
        "name": "binance",
        "sandbox": true,
        "key": "blablabla",
        "secret": "blablabla",
        "ccxt_config": {
            "enableRateLimit": true
        },
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 50
        },
        "pair_whitelist": [
             "APT/USDT:USDT","AR/USDT:USDT","ARB/USDT:USDT","ARPA/USDT:USDT","ASTR/USDT:USDT","ATA/USDT:USDT","ATOM/USDT:USDT","AUDIO/USDT:USDT","AVAX/USDT:USDT","AXS/USDT:USDT","BAKE/USDT:USDT","BAL/USDT:USDT","BAND/USDT:USDT","BAT/USDT:USDT","BCH/USDT:USDT","BEL/USDT:USDT","BLUEBIRD/USDT:USDT","BLUR/USDT:USDT","BLZ/USDT:USDT","BNB/USDT:USDT","BNX/USDT:USDT","BTC/USDT:USDT","BTCDOM/USDT:USDT","C98/USDT:USDT","CELO/USDT:USDT","CELR/USDT:USDT","CFX/USDT:USDT","CHR/USDT:USDT","CHZ/USDT:USDT","CKB/USDT:USDT","COMBO/USDT:USDT","COMP/USDT:USDT","COTI/USDT:USDT","CRV/USDT:USDT","CTK/USDT:USDT","CTSI/USDT:USDT","CVX/USDT:USDT","DAR/USDT:USDT","DASH/USDT:USDT","DEFI/USDT:USDT","DENT/USDT:USDT","DGB/USDT:USDT","DOGE/USDT:USDT","DOT/USDT:USDT","DUSK/USDT:USDT","DYDX/USDT:USDT","EDU/USDT:USDT","EGLD/USDT:USDT","ENJ/USDT:USDT","ENS/USDT:USDT","EOS/USDT:USDT","ETC/USDT:USDT","ETH/USDT:USDT","FET/USDT:USDT","FIL/USDT:USDT","FLM/USDT:USDT","FLOW/USDT:USDT","FOOTBALL/USDT:USDT","FTM/USDT:USDT","FXS/USDT:USDT","GAL/USDT:USDT","GALA/USDT:USDT","GMT/USDT:USDT","GMX/USDT:USDT","GRT/USDT:USDT","GTC/USDT:USDT","HBAR/USDT:USDT","HFT/USDT:USDT","HIGH/USDT:USDT","HOOK/USDT:USDT","HOT/USDT:USDT","ICX/USDT:USDT","ID/USDT:USDT","IDEX/USDT:USDT","IMX/USDT:USDT","INJ/USDT:USDT","IOST/USDT:USDT","IOTA/USDT:USDT","IOTX/USDT:USDT","JASMY/USDT:USDT","JOE/USDT:USDT","KAVA/USDT:USDT","KEY/USDT:USDT","KLAY/USDT:USDT","KNC/USDT:USDT","KSM/USDT:USDT","LDO/USDT:USDT","LEVER/USDT:USDT","LINA/USDT:USDT","LINK/USDT:USDT","LIT/USDT:USDT","LPT/USDT:USDT","LQTY/USDT:USDT","LRC/USDT:USDT","LTC/USDT:USDT","LUNA2/USDT:USDT","MAGIC/USDT:USDT","MANA/USDT:USDT","MASK/USDT:USDT","MATIC/USDT:USDT","MINA/USDT:USDT","MKR/USDT:USDT","MTL/USDT:USDT","NEAR/USDT:USDT","NEO/USDT:USDT","NKN/USDT:USDT","OCEAN/USDT:USDT","OGN/USDT:USDT","OMG/USDT:USDT","ONE/USDT:USDT","ONT/USDT:USDT","OP/USDT:USDT","PEOPLE/USDT:USDT","PERP/USDT:USDT","PHB/USDT:USDT","QNT/USDT:USDT","QTUM/USDT:USDT","RAD/USDT:USDT","RDNT/USDT:USDT","REEF/USDT:USDT","REN/USDT:USDT","RLC/USDT:USDT","RNDR/USDT:USDT","ROSE/USDT:USDT","RSR/USDT:USDT","RUNE/USDT:USDT","RVN/USDT:USDT","SAND/USDT:USDT","SFP/USDT:USDT","SKL/USDT:USDT","SNX/USDT:USDT","SOL/USDT:USDT","SPELL/USDT:USDT","SSV/USDT:USDT","STG/USDT:USDT","STMX/USDT:USDT","STORJ/USDT:USDT","STX/USDT:USDT","SUI/USDT:USDT","SUSHI/USDT:USDT","SXP/USDT:USDT","T/USDT:USDT","THETA/USDT:USDT","TOMO/USDT:USDT","TRB/USDT:USDT","TRU/USDT:USDT","TRX/USDT:USDT","UMA/USDT:USDT","UNFI/USDT:USDT","UNI/USDT:USDT","USDC/USDT:USDT","VET/USDT:USDT","WAVES/USDT:USDT","WOO/USDT:USDT","XEM/USDT:USDT","XLM/USDT:USDT","XMR/USDT:USDT","XRP/USDT:USDT","XTZ/USDT:USDT","XVS/USDT:USDT","YFI/USDT:USDT","ZEC/USDT:USDT","ZEN/USDT:USDT","ZIL/USDT:USDT","ZRX/USDT:USDT"
         ],
        "pair_blacklist": [
            "BNB/.*",
            "(BTC/USDT:USDT_.*|ETH/USDT:USDT_.*)",
            "(GT|HT)/.*",
            "(WBTC|BSV|BTCDOM|DEFI)/.*",
            ".*(_PREMIUM|BEAR|BULL|DOWN|HALF|HEDGE|UP|[1235][SL])/.*",
            "(AUD|BRZ|CAD|CHF|EUR|GBP|HKD|IDRT|JPY|NGN|RUB|SGD|TRY|UAH|USD|ZAR|UST)/.*",
            "(BUSD|C/USDT:USDT|DAI|PAX|PAXG|SUSD|TUSD|USDC|/USDT:USDT|VAI|USDN)/.*",
            "(ACM|AFA|ALA|ALL|APL|ASR|ATM|BAR|CAI|CITY|FOR|GOZ|IBFK|LEG|LOCK-1|NAVI|NMR|NOV|OG|PFL|PSG|ROUSH|STV|TH|TRA|UCH|UFC|YBO)/.*"
        ]
    },
    "pairlists": [
        
        {
            "method": "StaticPairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        },
          {"method": "AgeFilter", "min_days_listed": 7},
          {
                  "method": "VolatilityFilter",
                  "lookback_days": 10,
                  "min_volatility": 0.05,
                  "max_volatility": 0.70,
                  "refresh_period": 3600
          },
          {
              "method": "RangeStabilityFilter",
              "lookback_days": 7,
              "min_rate_of_change": 0.05,
              "refresh_period": 3600
          },
          {
        "method": "ShuffleFilter"
          }
        
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 14,
        "allowed_risk": 0.015,
        "stoploss_range_min": -0.05,
        "stoploss_range_max": -0.25,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.70,
        "minimum_expectancy": 0.025,
        "min_trade_number": 10,
        "max_trade_duration_minute": 240,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": false,
        "token"blablabla",
        "chat_id": "blablabla",
        "keyboard": [
            [
              "/daily",
              "/stats",
              "/balance",
              "/profit"
            ],
            [
              "/status table",
              "/performance",
              "/whitelist"
            ],
            [
              "/reload_config",
              "/count",
              "/logs"
            ]
          ]
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "blablabla",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "blablabla",
        "ws_token": "blablabla",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": ""
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
   	 "process_throttle_secs": 5
    }
}

**Comment by Bgsolid** [comment]
The issue keep staying whether I change price side to 'same'

**Comment by xmatthias** [comment]
Pricing in dry run uses the current order book price. 
Either same side, or other, as you correctly discovered.

It will NOT use candle open or close price, at least not intentionally, and orderbook pricing will change multiple times per second, so its unlikely to accidentally match.

You can use a pricing callback to force a specific price, but you will find that entries are then either late or cancelled, as the order needs to wait for price to reach it again (if it ever does before the timeout).

**Comment by stash86** [comment]
That can happen when you are trading low demand coin and using market order. In order to fulfil your request, based of the orderbook, it would need to eat several levels of sell orders.

"why the highest price is only 6.18?" Well, because you are on dry run, so your sell don't get registered to the exchange. If it was live, you would see the candle's high go up to 6.54.

**Comment by stash86** [comment]
And I find your example kinda wrong. If you are on short trade and you got entry rate of 6.54 instead of 6.17, that means you are in profit after you enter the trade.

**Comment by Bgsolid** [comment]
Hello Xmatthias!

Do you know a method to override parameters to calculate and act only on candle close?
Although I have good backtest results, it is not working based on dry-run and trying to find a solution to utilize the strategy. 

Thank you!

**Comment by Bgsolid** [comment]
> That can happen when you are trading low demand coin and using market order. In order to fulfil your request, based of the orderbook, it would need to eat several levels of sell orders.
> 
> "why the highest price is only 6.18?" Well, because you are on dry run, so your sell don't get registered to the exchange. If it was live, you would see the candle's high go up to 6.54.



> Pricing in dry run uses the current order book price. Either same side, or other, as you correctly discovered.
> 
> It will NOT use candle open or close price, at least not intentionally, and orderbook pricing will change multiple times per second, so its unlikely to accidentally match.
> 
> You can use a pricing callback to force a specific price, but you will find that entries are then either late or cancelled, as the order needs to wait for price to reach it again (if it ever does before the timeout).
--------


Hello Xmatthias!

Do you know a method to override parameters to calculate and act only on candle close?
Although I have good backtest results, it is not working based on dry-run and trying to find a solution to utilize the strategy.

Thank you!

**Comment by stash86** [comment]
Populate_ functions already working only on candle close. So not sure what your issue is

**Comment by Bgsolid** [comment]
> Populate_ functions already working only on candle close. So not sure what your issue is

Stash, sorry, I asked Matthias. Can you please dont comment this thread? Thank you!

**Comment by stash86** [comment]
Well, if trying to solve your issue faster is not preferred, suit yourself.

**Comment by Bgsolid** [comment]
> Well, if trying to solve your issue faster is not preferred, suit yourself.

Stash, 

You totally mixed things up (short vs. long), did not give me specific instructions in which file I need to see and which part, where to override and what to consider.
General assumptions they can't be used, are not welcome from another user especially!
I was asking the admin, in order to get specific instructions, and want to talk with him. With him!
I dont see the problem in this, this is not a chat, not an argument forum, but a ticketing system to help users. 
Users can decide from whom they ask: normally from the admin, who have been involved in the development of the application and knows everything better then other people.
I also work in IT sector, what I represent here is the stable version of solving issues and anwering questions, so I dont see why did you felt you were offended, actually you attacked this chat with unsolicited opinions I never asked from you.
Easy... this forum is not to argue with each other, I opened the question, and there is an admin, I personally dont want to see anybody who distracts attention from what I was asking and from whom I was asking it.

Appreciate your answers, but I decided to please step back based on your answers. 
So before you think you help anybody, be sure that your answer is valid and you understand the question (dont mixing short vs. long, dont provide specifics, etc.), but dont be offended, this is the function of the admin/admins, not simple users.

Thank you for your understanding!

**Comment by perkmeister** [comment]
LOL, Stash is not just a 'simple user', he's an OG and a helper in the Discord and one of the most knowledgeable users out there. And no, he didn't mix up longs and shorts, you did when you said `Like for a short positio entry i got 6.54 price instead of somewhere close to a 6.17 mark price (the highest of those candles were 6.18), but i receive a totally different price, so my openings are already in loss`, because a short position entry is a SELL, and you apparently got higher price than expected which would not put you in a losing position on entry, you'd be in a better position. BTW I'm a helper too in that Discord before you complain about others answering your non-sensical question.

**Comment by Bgsolid** [comment]
> LOL, Stash is not just a 'simple user', he's an OG and a helper in the Discord and one of the most knowledgeable users out there. And no, he didn't mix up longs and shorts, you did when you said `Like for a short positio entry i got 6.54 price instead of somewhere close to a 6.17 mark price (the highest of those candles were 6.18), but i receive a totally different price, so my openings are already in loss`, because a short position entry is a SELL, and you apparently got higher price than expected which would not put you in a losing position on entry, you'd be in a better position. BTW I'm a helper too in that Discord before you complain about others answering your non-sensical question.

Guys, Im feeling a little tired of this conversation at the moment.
So there are 2 guys I never asked anything from them, but receive so much arrogance without any proper instruction on my question.
Im not here to argue, or anything like that, you guys make this conversation very frustrating which i dont want to continue with you guys.
Can we please close this conversation with you guys Perkmeister and Stach, or is there any reason you want to spit on me?
I only asked from Matthias, until he can answer, let him make it please. 
Thank you for your understanding!

**Comment by Bgsolid** [comment]
Guys, Im not that amateur arrogant that you think of me right now.
I just like order of things, and sorry for that, but I do not know any of you, but know there is an admin.
I have never said I feel doubt any of your words, but lets first instruct me Matthias.
I have gone through many issues and find his answer so good and well thought.

And yes, im new to this app, my question can be seemed non-sensical to anybody, no problem, but Im pretty sure this ticketing system can be maintained on a professional level instead of spitting shit on each other without any valid reason.

Thank you!

**Comment by Bgsolid** [comment]
> Pricing in dry run uses the current order book price. Either same side, or other, as you correctly discovered.
> 
> It will NOT use candle open or close price, at least not intentionally, and orderbook pricing will change multiple times per second, so its unlikely to accidentally match.
> 
> You can use a pricing callback to force a specific price, but you will find that entries are then either late or cancelled, as the order needs to wait for price to reach it again (if it ever does before the timeout).

Hi xMatthias!

Can you help me with the basic of the question furthermore?
I understand that orders work on order book basis. What I dont understand (if it matters) with which depth step this was calculated?
Manually I use - on Binance 0.0001 depth step to analyze te order book.
This provide also good liquidity, so I never missed a trade based on order book quantity.

But actually i do think there several factors to consider, just dont know which and why them.
Why I think it?
Let me give you a couple of example, and I hope you can help me find out what went wrong and how I can adjust it.

Timezone: UTC + 2h (as per Tradingview)
Exchange: Binance (EU, not USA)
Product: USDT perpetual pairs
Examples with ticker, time, direction, mark price, order price: 
- ZIL/USDT, short, 2023.06.30.15:46, 0.2020, 0.2049 - if price is 0.2020 why the bot initiated an order "based on order book" at 0.2049? 
- MKR/USDT, short, 2023.06.30.15:46, lowest price 750, order price is 691.5 - it is just too much diff., candle high or low did not hit close to 691.5, the lowest of any candles nereby was 705 at its minimum

And I have so many examples, like 100-200, with MANA, ATOM, YFI, ENJ, SOL, IOTA, COMP, VET, XRP, etc., so there are not the smallest tickers, they have huge liquidity in their order book, on 0.0001 order book depth step it is sooooo easy to enter a trade anytime day and night.

So my question not relates to if it is short or long, the direction is totally dont matter to me, what matters to me why the bot place order so far from the current market price and/or so far from the latest open and close price? 

Why the bot dont go to the current price and place order on it or somewhere close to it?
Like in the top1 order book depth, which is kinda very close if depth step is 0.0001 what is default in Binance.
Like if order book with 0.0001 depth step, mark price is 0.4069, the top1 bid and ask are 0.4070 and 0.4068.
With this example (0.4069) i just received 0.3790 for an order. How did this happened? This is totally not the top1 of the order book, not close to it, nor the above other examples. To be honest, i have never seen a fair priced order running dry-run. 

Thank you for your help to understand better what and how I should adjust it within the config or in the strategy file.

**Comment by froggleston** [comment]
Just a word of advice - you're posting an open question on an open support forum. You *will* get others asking you for clarification or trying to answer your question. This is not a bad thing, and your defensiveness over not getting preferential personal support from the lead maintainer of the project is unreasonable. Please consider that people develop and support this project for free. You are not obligated to get one-on-one support.

As for the "spitting on you" comment, I fail to see how you've come to this conclusion that you've somehow been mistreated despite multiple people trying to help you. Please stop harassing the lead maintainer because you feel you deserve their sole and undivided attention. This is a great community with multiple knowledgeable people who are helping you for free. Please respect their knowledge and desire to help you.

**Comment by Bgsolid** [comment]
This will be my last anwser to any chat/letter if it is not sticking to the main topic of the question!
It is totally enough to spend days with guys I dont know, they dont shared anything, just misleaded with their answers.
If their answers would have been good, my question had to be closed, but this is totally not the case.
Please dont repeat again, dont write again if your writing is not related to the topic!
It is totally a provocation i want to close ASAP!

Finish this conversation in this personal way please, I have asked it, now I ask it again.

Stick to the topic please.

Thank you!

**Comment by froggleston** [comment]
Their answers may be based on incomplete information that you have provided, or misunderstandings, or both. This isn't necessarily their fault or malicious, so I ask you again to respect that people in this community wish to help you. Your attitude towards community members is poor, so if you continue to force your way into conversations with the lead mantainer when others may be able to help, and also continue to disrespect them here, I will close this issue and consider temporarily restricting you from opening issues.

**Comment by froggleston** [comment]
You are asking a question openly on the internet. Anyone is free to reply.
Your demanding attitude towards community members with good standing is
disrespectful.

I am a member of the core 13 committers of this project, so yes, I am able
to make these decisions about how the community is run, the code that gets
written, and the support people get.

Nobody has disrespected what you asked, nobody is maliciously misleading
you, and you are asking a question in an open internet forum that I,
amongst others, maintain and moderate. You cannot simply act however you
like to get your way.

**Comment by froggleston** [comment]
I will always help protect the members of this community that help others. Your attitude is not helping you. Due to your fairly rude email, I'm closing this issue.

**Comment by Bgsolid** [comment]
Robert
(and not because i want to intimidate anybody, but because in my country we respect people with their name if we know it)

I never told that their answer was not from their very heart.
I just used to rely on admin, if we talk about ticketing system.
I did not know this is a sooo open forum anybody can chat with each other.
In IT this is not allowed normally, in order to end conversations with good result, only the admin or admins can help and their name is including their role.
This is normal in IT, and I used to it. 
I told everyone in this chat I am new and I might wrong, but that doesn't mean I wanted to be disrespectful to anyone or would have been, I simply asked the members to let me wait for the admin's answer. 
Not because i dont receive help from others or not because i dont appreciate their time they invest to my question.
It is because I used to stricter ticketing system management and never find this "open thing" working.

I consider this a first and good step, ask the admin.
Also, I don't know the members, I don't know who's who, let me be wrong and let's move on without it being pointed out to me every day and again and again every single day by someone else: bg you were wrong, you were wrong, you were wrong.
I did not know I was wrong, I admit if I knew I was, but did not know.
After receiving such feedbacks, my mood is changing.
Nobody likes repeating above their head day to day for days 'you were wrong'.

Cant we just please move on and stick to the question?
Is it so harsh and rude asking? 
Why?

I never wanted to be disrespectul to anybody, just because I am used to other ticketing system management, dont mean I wanted to hurt anyones feelings.
If I hurt anybody, sorry for that, but please try to understand and accept what I was writing because people are different and accustomed to different roles and rules based on what they work / job is.

Thank you!

**Comment by Bgsolid** [comment]
> I will always help protect the members of this community that help others. Your attitude is not helping you. Due to your fairly rude email, I'm closing this issue.

Please read what I wrote to David, I hope that highlight this case for you as well. 
Thank you!

**Comment by froggleston** [comment]
I'm not sure who David is, but you addressed your rude email to me and I presume sent it privately because you felt like you could simply intimidate me. That isn't going to work here. I'm not sure what your experience is with IT help, but open source communities do things differently. We are all volunteers here, and your argument that others don't have the knowledge to answer your questions because they're not "an admin" is incorrect.

You are *not* able to act in the way you have and continue to think it's acceptable. So, this issue will remain closed for at least a few days so you can consider your actions.

**Comment by Bgsolid** [comment]
> I'm not sure who David is, but you addressed your rude email to me and I presume sent it privately because you felt like you could simply intimidate me. That isn't going to work here. I'm not sure what your experience is with IT help, but open source communities do things differently. We are all volunteers here, and your argument that others don't have the knowledge to answer your questions because they're not "an admin" is incorrect.
> 
> You are _not_ able to act in the way you have and continue to think it's acceptable. So, this issue will remain closed for at least a few days so you can consider your actions.

I have read your name incorrectly (Davey > David).
I never wanted to intimidate anybody. Jesus christ! In my country we talk people with their names, basic attention to respect the other human being by calling them on their names. 
You guys are so agressive in this site, so yes, keep this question closed and dont open it again, i will never ask anything from you.
You are just ignoring everything I write, although I said if i was wrong I admit it.
Okay.

**Comment by Bgsolid** [comment]
Dear Froggleston, Perkmeister, Stash!

Now I am officially and explicitly want to say sorry for the last day conversation style if I made it hard for you to stay gentleman with me.
My intention was really not about making your days hard, or be disrespectful, what I see is that we totally misunderstood each other, I misunderstood how it works the Github (im very new to it), and you didn't find the human behind my words.

Sorry for it, I have never had any intention to hurt your feelings!
These lines are not about to open this question again, but Im a human and feel terrible for how this conversation happened in here.

**Comment by xmatthias** [comment]
I've taken the time now to clean this issue up a bit, marking all off-topic comments as such, leaving only the ones that may be beneficial to future readers.

One last word about the above topic (from the "admin", as you asked):

>  Im pretty sure this ticketing system can be maintained on a professional level instead of spitting shit on each other without any valid reason.

I do absolutely agree with this comment - so i have to ask you (@Bgsolid)  specifically to also follow what you said.
Everyone involved in this thread has a track record of helping people, either on discord or on github (the platform won't matter).

> I was asking the admin, in order to get specific instructions, and want to talk with him. With him!

that's not how github issues (or communities in general) work. Everyone (knowledgable) is more than welcome to try and answer questions. 
Would every question fall back to me, trust me, i'd have stopped working on this project a **long** time ago.

> I consider this a first and good step, ask the admin.

That's the wrong approach. From your comments - i assume you work in a medium/large size company with a decent IT department.
If you need a new mouse or a new PC - you will get that from the 1st level support - not from the CIO (highest level).
you can ask for it - but the likelyhood of the CIO walking to your desk with your new mouse is 0 (unless the CIO is the only IT person in that company).
(On the contrary, i will answer a question i see nobody has had an answer for).

---

My assumption (based on your last comment) is that we have now understood that this is not a "company ticketing system" (you pay for this or are employed to have access to such a thing) - but an open issue tracker from a community.
i therefore see this sub-topic as closed (and have hidden all related comments to this).

**Comment by xmatthias** [comment]
To answer your actual question (please make sure to read my above hidden answer for clarification on the above).

When filling an order (market order, or limit order with price across the orderbook) - that order must walk the Orderbook.
Based on the prices you talk about, you're almost certainly using market orders.

This respects the [considerations for dry run](https://www.freqtrade.io/en/stable/configuration/#considerations-for-dry-run) - most importantly "Market orders fill based on orderbook volume the moment the order is placed.".

For simplicity's sake i'll assume the orderbook situation as present in the [pricing documentation](https://www.freqtrade.io/en/stable/configuration/#enter-price-side) 

```
...
103
102
101  # ask
-------------Current spread
99   # bid
98
97
...
```


Now let's assume volume for coin is 2 (coin) at each level of the above orderbook - and you're about to place a market sell order (irrelevant if entry or exit) for 10 coins.

Your initial price assumption will be 99 - which will fill 2 coin - then move to 98 (fill another 2 coin) (and so forth).
The final price for that order will then be the average of all the above individual fills.
This is emulating how live works - HOWEVER - in live, YOU would be the one to cause a new low at 97.
in dry - this is not happening, so the candle's low might be at 99 (nobody sold lower during this time) - but your order simulated STILL filled at 97 - just the market / exchange doesn't know about that.
the steps (99, 98, 97) are defined not by 0.0001 steps - but by where the actual orders are in the orderbook at that moment (it could very well be that there's 0 liquidity at 98 - so this level is "skipped").

This same situation can also happen in actual markets - and caused BTC to spike to >100k a few years ago on a thin market (don't remember the exchange, sorry) for a splitsecond (and iirc a gap down on binance.us a little while ago) - and is the reason why i personally would never use plain market orders.
You give up control of the price in favor of "whatever the market liquidity is at that point".

If you're still looking for "immediate" fills like market orders, my recomendation is (and will remain) to use limit orders, with price side "other".
You can play with `order_book_top` - where 1 will correspond to 99 and 101 (above example) - 2 will correspond to the next spot in the orderbook where there's actual orders - be that 98, 97, or 5 (if nobody want's to buy this token for more than 5$).
