### ISSUE TITLE
Retrieve dataframe who opened the trade in populate_exit_trend

### ISSUE THREAD

**Issue by M-t-t-h** [freqtrade/freqtrade#8848]
## Describe your environment

  * Operating system: Docker on Synology
  * Python Version: 3.8.12 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: last stable (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
Hy everybody.
I presume my question is simply but i didn't find answer in docs or other searchs... (maybe my english is responssible for it :s )

I'd like to retrieve dataframe who raised the trade in populate_exit_trend.
More specificly, the bot open trade with a RSI = X
After some time, other populate_entre_trend have rise "enter_long = 1" so i can' t juste ask freqtrade to give me dataframe where open_long = 1...
I have the same probleme to populate custom_info (the last value will be erase by next entry_long = 1).

So, how to know the value of my RSI when the trade raised in populate_exit_trend ? ?

Thanks in advance,

**Comment by froggleston** [comment]
Use custom_exit instead if you need to know the enter_tag of an open trade and handle different exits for different entry tags. `populate_` functions only generate signals - they don't know about trades.

**Comment by xmatthias** [comment]
We have samples for this in the [advanced documentation](https://www.freqtrade.io/en/stable/strategy-advanced/#dataframe-access).

You should only be using this in callback functions which provide the trade object.
the sample also includes a part for the "trade open date". You will however always need to also double-check for existence of that candle (as shown in the example) - as the trade open date can "age out" of the available dataframe, which would leave you with this frame being empty.

**Comment by M-t-t-h** [comment]
hello ! thanks for yours answers. i just tried some works with yours returns. i m close of what i desire. hoppe finish this part this week and, if it s work, i will provide full sample of custom_exit to have full answer.

again, thanks for you replies

**Comment by M-t-t-h** [comment]
Hy,

Sorry for timing...

Here i small code for retrieve RSI From opened trade time.
It's come from custom_stop_loss but should work with lot of "custom" function:

```
# Obtain pair dataframe.
dataframet, DataFrame= self.dp.get_analyzed_dataframe(pair, self.timeframe)
#get trade time to retrieve the candle
trade_date = trade.open_date_utc
#get candle who oppened the trade
trade_candle = dataframet.loc[(dataframet['date'] == trade_date) & (dataframet['enter_long']==1.0)]
#check if candled were found
if not trade_candle.empty :
	#check if candle is different than candle registred as "in" ( = check if candle is from a new trade)
	if (not trade_candle.equals(self.custom_info[pair]['currTradeDT'])) :
		# get RSI at time of trade opened
		self.custom_info[pair]['RSIatOpen'] = trade_candle['rsi'].iloc[0]
	#do stuff with self.custom_info[pair]['RSIatOpen']
```

sould works... 

Have a nice day !
