### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by chrisdonreynolds** [freqtrade/freqtrade#8859]

**Comment by stash86** [comment]
Try to specify timerange

**Comment by chrisdonreynolds** [comment]
same error

**Comment by stash86** [comment]
Upload the config you are using

**Comment by chrisdonreynolds** [comment]
[config.txt](https://github.com/freqtrade/freqtrade/files/11941631/config.txt)

**Comment by chrisdonreynolds** [comment]
I have no idea how formatting works on github :(
but my config is pasted now

**Comment by chrisdonreynolds** [comment]
> I have no idea how formatting works on github :( but my config is pasted now

okay fixed the formatting

**Comment by xmatthias** [comment]
Closing as both title and description have been edited to be empty.
