### ISSUE TITLE
what's the different between forceenter and forcebuy ??  from restAPI

### ISSUE THREAD

**Issue by thunderwin** [freqtrade/freqtrade#8861]
what's the different between forceenter and forcebuy ??  or forceexit and forcesell..    from restAPI

I m confusing....

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---


Forcebuy is the old, compatibility layer, which corresponds to forceenter with "side=long".
