### ISSUE TITLE
adjust position order cancel

### ISSUE THREAD

**Issue by Arivadis** [freqtrade/freqtrade#8875]
* Operating system: Ubuntu
  * Python Version:3.9

  * Freqtrade Version: stable(08.07.2023 updated)

Hello!

I need a bit help to get logic how some functions are working together.

I use adjust_trade_position with limit orders.
I made dataframe['enter_long'] = 1 to get immediate entry position and all farther computing using adjust_trade_position only.

I don't quite see how adjust_trade_position working along with custom_entry_price, custom_exit_price and adjust_entry_price.
As I see it now - after adjust_trade_position returns value custom_entry_price must return rate for new limit order. If there is a new candle - adjust_entry_price called and limit price must be changed.
If adjust_trade_position returns negative value - custom_exit_price sets limit order price?
If adjust_trade_position returns new positive value - it should increase existing limit orderm, opposite for new negative value.

If I'm wrong somewhere, please help me figure it out.

The second question - Is it possible to track cancel previous order before adjust_trade_position returns new value.
I guess it could be done by using check_entry_timeout/check_exit_timeout, but not sure.

Thank You!

**Comment by xmatthias** [comment]
you're quire very wrong.

**Comment by xmatthias** [comment]
[`adjust_trade_position()`](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position) returns the amount to adjust in stake currency.
so returning `-50` would reduce your position by 50 USDT - and `+25` would buy coin for another 25 USDT.

Price has nothing to do with this in the first instance, and will be determined by the regular pricing logic - which will either use whatever you've got cofigured, or the corresponding entry/exit price callbacks (entry for positive adjustments, exit for negative adjustments).

[`adjust_entry_price()`](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-entry-price) has little to do with this initially - and acts on unfilled open orders only - allowing you to adjust the price (maybe your price was too far from spot ...).

Now this obvioulsy assumes that
* your price was far enough off-spot for the order to not fill (which effectively includes the 2 below points).
* your order is not filling immediately
* your order didn't fill partially beyond the non-cancelable limit
* your order is an entry order

`adjust_trade_position()` will not cancel an order, and will not be called as long as an order is open.

canceled orders (by adjust_entry_price) are available in most callbacks via [`trade.orders`](https://www.freqtrade.io/en/stable/trade-object/) - usually with the state "canceled".

**Comment by Arivadis** [comment]
Let me please sum up all of these:
1. After `adjust_trade_position()` returnes the amount -  bot uses callbacks methods `custom_entry_price()` - entry for positive adjustments or `custom_exit_price()` exit for negative adjustments.

2. If order created by `adjust_trade_position()` is not filled for any reason, `adjust_trade_position()` method has stopped till the order is filled/canceled. However `adjust_entry_price()` called for cancel order or edit price till order's timeout/filled/canceled.
From documentation I see "**The adjust_entry_price() callback may be used by strategy developer to refresh/replace limit orders upon arrival of new candles.**", thus this method is not called every throttling iteration, but new candle only, is it?

3. Since the order was filled bot returnes to the main logick with callback `adjust_trade_position()` and so on. 
Does opened by `adjust_trade_position()` order stopes `custom_exit()`callback till the order is filled, as well as this order stopes `adjust_trade_position()`method?

4 The same question for `custom_exit()` - """This method is not called when exit signal is set already""" - from documentation, so I suppose it to ignore callbacks `adjust_trade_position()` and `custom_exit()` until limit exit order is canceled/filled, and adjust_entry_price() will change this exit limit price every new candle if order is not filled yet.

If I'm wrong somewhere, please let me know.
Thanks a lot!

**Comment by xmatthias** [comment]
1 - yes
2 - correct - once per candle. But you get the [custom order timeout](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-timeout-rules) callbacks, which are called more often.
3 - Having an open order (entry or exit) does stop all other processing (except for order checking of "filled" and "timed out") for that trade at the moment. This may change in the future - but currently, we assume an order to be short-lived, so an open order means "wait for that order to fill or cancel".
4 - Included in answer 3, contained in "other processing"

**Comment by Arivadis** [comment]
Best answer,

Thank You so much!
