### ISSUE TITLE
ERROR: Could not build wheels for TA-Lib, py_find_1st, psutil, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#8893]
## Describe your environment

  * Operating system: ____ Ubuntu 22.0.4
  * Python Version: _____ (`python -V`) 3.10.6 / 3.11
  * CCXT version: _____ (`pip freeze | grep ccxt`) ccxt==4.0.14
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker) freqtrade 2023.7.dev-9505f380b
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

Seem to have a venv issue, my venv is running 3.10.6 yet I've upgraded to 3.11 which is present on the system and when I upgrade with bash setup.sh -u the following happens...

### Steps to reproduce:

  1. _____ run bash setup.sh -u
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
      copying psutil/tests/test_unicode.py -> build/lib.linux-aarch64-cpython-311/psutil/tests
      running build_ext
      building 'psutil._psutil_linux' extension
      creating build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/psutil
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=595 -DPy_LIMITED_API=0x03060000 -DPSUTIL_LINUX=1 -I/usr/include/python3.11 -c psutil/_psutil_common.c -o build/temp.linux-aarch64-cpython-311/psutil/_psutil_common.o
      psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
          9 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      psutil could not be installed from sources. Perhaps Python header files are not installed. Try running:
        sudo apt-get install gcc python3-dev
      error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
Failed to build TA-Lib py_find_1st psutil
ERROR: Could not build wheels for TA-Lib, py_find_1st, psutil, which is required to install pyproject.toml-based projects
Failed installing dependencies
  ```

**Comment by xmatthias** [comment]
The solution is in the middle of your error, suggesting what might be wrong.

`sudo apt-get install gcc python3-dev`

**Comment by tomjrtsmith** [comment]
I tried that and it tries to install the 3.10.6 version and it's
running 3.11

***@***.***:~/freqtrade$ sudo apt-get install gcc
python3-dev Reading package lists... Done Building dependency tree... Done
Reading state information... Done gcc is already the newest version
(4:11.2.0-1ubuntu1). python3-dev is already the newest version
(3.10.6-1~22.04). python3-dev set to manually installed. 0 upgraded, 0
newly installed, 0 to remove and 5 not upgraded.

**Comment by xmatthias** [comment]
That would suggest you have both 3.10 and 3.11 installed?

ubuntu 22.04 comes with 3.10 by default, not 3.11. This suggests that you manually installed 3.11 (which is not per se a problem) - but simply means that you need to follow the same to get the corresponding headers.

**Comment by tomjrtsmith** [comment]
I upgraded from 3.10 a while back so I am guessing yes it has both, can't
understand why it installs everything else for 3.11 and just this for 3.10
though.

**Comment by xmatthias** [comment]
python 3.10 is the default on ubuntu.
the package name for python 3.11 is `python3.11-dev`. Our assumption is that users who use custom setups (non-default python version for their system) also know how to use it. otherwise, it's best to stay on the default setup.
