### ISSUE TITLE
Getting Dynamic WinRate to adjust other parameters (such as leverage)

### ISSUE THREAD

**Issue by erhangunay** [freqtrade/freqtrade#8896]
Hello,

I would like to know if it is possible to get the number of winning trades in a variable in my strategy file so I can create a condition in leverage callback saying if winrate<50% use double leverage?

I have seen that I can get the number of total trades but I could not find how to filter them by profit.

Also if possible, can I backtest this?

**Comment by xmatthias** [comment]
You can get all (closed) trades via [`get_trades_proxy()`](https://www.freqtrade.io/en/latest/trade-object/#get_trades_proxy`) - which will work in all callbacks (it'll work in populate_* methods, too - but will return empty during backtesting).

You can then use some filter (e.g. `profit_trades = [t for t in closed_trades if t.close_profit > 0]` to filter based on your individual needs.

**Comment by erhangunay** [comment]
Thank you very much Matthias!

Can you think of an idea on how to have dynamic leverage based on winrate that would work on backtesting?

**Comment by xmatthias** [comment]
well leverage is a callback (so `get_trades_proxy()` is available), not something you assign in a populate_* method - so i don't really understand your question?

**Comment by erhangunay** [comment]
Ah i misunderstood your previous comment. 

Once again, thanks Matthias!
