### ISSUE TITLE
backtesting-analysis  - show signal candle indicators for exit signals

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#8902]
## Describe your environment

  * Operating system: _Docker___
  * Python Version: __Python 3.11.4
  * CCXT version: __ccxt==3.1.44
  * Freqtrade Version: __docker-2023.6.dev-e16c433c
  
In reference to backtesting analysis I can only see signal candle indicators for buy signals. Is it possible to extract also signal candle indicators for sell signals (indicator values on signal candles)?

**Comment by xmatthias** [comment]
it's .. not immediately clear what you're looking for if i'm honest.

`backtesting-analysis` is looking at enter-reasons - and you can do the same for exit-reasons if that's what you're asking
If not - then please try to phrase your question differently, or more in detial what you're getting on the entry side, but not on the exit side.

**Comment by froggleston** [comment]
backtesting-analysis won't currently store exit signal candle data, only entry signals. This might be implemented in future.

**Comment by darioneto** [comment]
I was referring to this doc: https://www.freqtrade.io/en/stable/advanced-backtesting/
running freqtrade backtesting-analysis with --exit-reason-list appears to provide only parameters in detail with entry for each indicator not exits. (each value for every indicator where the trade was taken) indeed a useful feature.

**Comment by froggleston** [comment]
Yes, that's correct.

**Comment by xmatthias** [comment]
Seems like something worth pursuing.
Marking it as enhancement for now - shouldn't be too difficult to implement, either.

**Comment by darioneto** [comment]
Appreciate your input on this, It would be a very useful feature in the toolset if possible to integrate.

**Comment by jainanuj94** [comment]
Hey @xmatthias / @froggleston : i was thinking of picking up this enhancement. Although would like to get some suggestions. 

Currently while backtesting with --signals parameter two files are generated:
- rejected.pkl
- signals.pkl
Here signals.pkl just consists the indicator values against the entry signals. I am planning to create another .pkl file exited.pkl or something which holds indicator values against the exit signals. 
The same will be used in backtesting analysis. 

To start with i am planning to run the same set of analysis on this exited.pkl file that runs for signals.pkl. 

Let me know if this sounds good!  Anyways will be raising the PR soon as i am trying to analyse the same with one of my strategies. Although not a data or statistics guy so struggles a bit.

**Comment by froggleston** [comment]
That's been on my list for a long time and I've never got round to it. Sure - I'm happy to take a look at any code you produce and work together to get it developed! 👍

**Comment by xmatthias** [comment]
> Here signals.pkl just consists the indicator values against the entry signals. I am planning to create another .pkl file exited.pkl or something which holds indicator values against the exit signals.

Either this, or enhance signals.pkl to also contain the exit data (i'm not sure we'll need a separate file - but i didn't look at the precise format (or format required), either.

**Comment by jainanuj94** [comment]
Have created a draft PR: https://github.com/freqtrade/freqtrade/pull/10485

We can discuss some more technical details there. @xmatthias i understand your point and have provided the reasons on the PR.
