### ISSUE TITLE
get trades to return last X trades according with  the close date

### ISSUE THREAD

**Issue by polyvios-bc** [freqtrade/freqtrade#8904]
The current trades endpoint works like this: 

trades
    Return trades history, sorted by id
        :param limit: Limits trades to the X last trades. Max 500 trades.
        :param offset: Offset by this amount of trades.

However this is a bit inefficient if you are interested to get last trades that happened in the last 1 hour lets say. The reason that doesnt work very well is because you can have a trade with a trade_id lets say 100 that remains open for a while. Current trade_id lets say is 1200 . Now lets say that trade with trade_id =100 gets closed. That means I wont be able to get that from last trades because is sorted via id and max trades is 500. So the offset to get that recent closed trade should be < 100, otherwise you cant get that from trades. This is forcing someone to keep using /trades/<trade_id> endpoint

## Describe the enhancement

Be able to get last trades using a time period maybe

**Comment by xmatthias** [comment]
Such an endpoint doesn't exist (as you've found already) - and i currently can't see any actual usecase where this might be useful and provide benefit (maybe you can elaborate WHY you think this is needed). 
I'll treat this as question for now - but this can obviously change if you can provide a good usecase as to why this is actually necessary.

for any type of UI i can think of (not just freqUI), you'll want all trades anyway, so you can show
* total amount of trades
* random statistics over all trades
* fast, in-ui filtering and searching

As such, i don't really see why only the last X closed trades would be necessary.

Without having clear benefit, it's just another piece of dead code probably only 2-3 people use, but which we'd still need to maintain and ensure it doesn't break going forward.

**Comment by polyvios-bc** [comment]
The reason is basically what i explained. If you have an open trade for a while and many closed trades happen before that gets closed. When that gets closed calling get trades by using the offset you have been storing lets say on your side so you wont keep processing all of them again wont return you that trade because its offset (id) is before. Hope that makes sense.
So its just more convenient to have a parameter for time period as well and not just the offset, because then you guaranteed that you wont lose any trade update by calling this. Thats if you want to avoid calling from offset 0 every time

**Comment by xmatthias** [comment]
i think you misunderstood my question.
i am fully aware of the conditions when trades ordered like this might make sense (we do it this way for telegram).

For telegram (which is directly user-facing) - it's clear why this has benefits.
What's unclear to me is what the usecase might be to have this type of ordering for the API, as I fail to see a benefit as to when you'd want to call "just the last X closed trades" - it's an API - not an interface a user will be seeing directly?

**Comment by polyvios-bc** [comment]
A use case for us is this. We have a centralised db and we have a process that is connecting to all the bots we have and is querying them via the rest api in order to get and store those closed trades. We have a workaround to do that without the thing i asked, but i think a time based api to get those trades would be very useful and more straight forward for cases like this.

**Comment by xmatthias** [comment]
If you think it's something we must/should have, please submit a pull request adding this.

It should be pretty straightforward, as the actual sorting logic is available, it's just not exposed via the API endpoint.
Please make sure that 
* existing logic remains in place and doesn't break
* include a quick unit-test ensuring correct behavior

**Comment by polyvios-bc** [comment]
Thank you , will do
