### ISSUE TITLE
How to get backtesting to work in Docker?

### ISSUE THREAD

**Issue by keithfawcett** [freqtrade/freqtrade#891]
## Step 1: Have you search for this issue before posting it?
Yes

## Step 2: Describe your environment

  * Ubuntu 18.04
  * Python Version: 3.6.5 (`python -V`)
  * Branch: Master
  * Last Commit ID: 8c73fd6e5945b967b12e8ba602857a9e3d0b269b (`git log --format="%H" -n 1`)

  * Also used automatic install instructions for Docker from [https://github.com/freqtrade/freqtrade/blob/develop/docs/installation.md#automatic-installation---docker](https://github.com/freqtrade/freqtrade/blob/develop/docs/installation.md#automatic-installation---docker)

I would expect for everything to work after following above instructions without the need to do anything else. Is this not the case? Currently only the normal running, using config file and default strategy, works. But unable to get backtesting to work. 
 
## Step 3: Describe the problem:
Unable to get backtesting to work. Tried mutiple commands with no success. System always throws some error that I'm unable to understand why. 

Here's trying to use the instructions provided:
`
1vcpu-2gb-nyc1-01:~/freqtrade$ python3.6 ./freqtrade/main.py --strategy Strategy003               Traceback (most recent call last):
  File "./freqtrade/main.py", line 10, in <module>
    from freqtrade import OperationalException
ModuleNotFoundError: No module named 'freqtrade'
`
Here's adding PYTHONPATH
`1vcpu-2gb-nyc1-01:~/freqtrade$ PYTHONPATH=../ python3.6 ./freqtrade/main.py --strategy Strategy003Traceback (most recent call last):
  File "./freqtrade/main.py", line 10, in <module>
    from freqtrade import OperationalException
ImportError: cannot import name 'OperationalException'
`

**Comment by xmatthias** [comment]
from the name of the server (1vcpu-2gb-nyc1-01) i would assume that this is not run within the server, but outside, in which case you need to install first requirements, and then the bot itself using `pip install -e .` .

I don't think there is a documentation on how to run backtesting in the container - but it should be as easy as 

``` bash
docker run --rm -v /etc/localtime:/etc/localtime:ro -v `pwd`/config.json:/freqtrade/config.json -it freqtrade -s StrategyWhichever backtesting 
```

**Comment by xmatthias** [comment]
Hi there, 
did you get the bot to work successfully?

**Comment by xmatthias** [comment]
good point - will be added, thanks
