### ISSUE TITLE
save section candle high and low data

### ISSUE THREAD

**Issue by shuten** [freqtrade/freqtrade#8915]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I want to save the data shown in the figure,like this:
![screenshot-20230717-112930](https://github.com/freqtrade/freqtrade/assets/7748335/59e132d4-819d-40d0-897c-25b8d6cd8410)

how can i do it,thank you very mach!!!

**Comment by xmatthias** [comment]
usually, something around `dataframe['high'].rolling(x).max()` (and the corresponding min for lows) should get you to something like that.

"x" is the critical part, as it'll define how far back you intend to look.

**Comment by shuten** [comment]
@xmatthias okey, "x" value is hard to choose,I try other methods,thank you again！

**Comment by froggleston** [comment]
Be very careful with peak finding methods as they nearly all will exhibit lookahead in backtesting.

**Comment by shuten** [comment]
@froggleston okey,thank you very much!!!

**Comment by xmatthias** [comment]
You can check for lookahead bias via the [lookahead-analysis](https://www.freqtrade.io/en/stable/lookahead-analysis/) subcommand - which will show you if some of your indicators seem to look into the future.

**Comment by shuten** [comment]
thank you !!! I need this very much.
