### ISSUE TITLE
StopLoss limited to last orderbook price - exposed to flash/crash - shakeouts

### ISSUE THREAD

**Issue by creslinux** [freqtrade/freqtrade#893]
The stoploss in Freqtrade is set to trigged on last price on the order book 
This is valid, and many strategies will want this. 

Other strategies will want to stop on last bar close, or OHC/3 as example. 
This is to avoid being shaken out, or falling foul to a flash crash 

In the chart image attached OHLC are plotted as lines separately. 
The green box contains a orderbook dip/low. It is a indicative of MM dipping order-book price to shakeout stops - this happens frequently before a big lift. 

A stoploss set to bar close would not have been be hit. 

Ideally Freqtrade should support both: 
 - stop loss triggered on last order book 
 - stop loss triggered on desired bar, with both resolution to use and OHLC
 -  -  - as example  bar[1][1m][c]  would use the last bar, on 1 minute resolution, and the close value.

<img width="539" alt="screen shot 2018-06-10 at 8 15 34 am" src="https://user-images.githubusercontent.com/34645187/41200364-d9625b48-6c92-11e8-888c-080e2a8d97cf.png">

**Comment by xmatthias** [comment]
#1341 will cover this by using "stoploss on exchange".
It's only there for binance ATM - but extending this logic to another exchange should be simple - and the root problem is solved.

Feel free to reopen if you think differently.
