### ISSUE TITLE
Control of the bot according with some criteria

### ISSUE THREAD

**Issue by polyvios-bc** [freqtrade/freqtrade#8933]
Hello have two questions:

1. Is it possible to call stop from the strategy itself given some criteria on specific orders?
2. Is it possible if you dont want to close an existing position but you want to keep trading in some other coins to prevent trading only for that specific coin?

**Comment by stash86** [comment]
Please don't delete the template

1. The bot will only buy if populate entry says so. So put your logic in populate entry
2. That's where pair_whitelist and max_open_trades work

**Comment by polyvios-bc** [comment]
Thanks for the reply:

2. So if i am holding a position if I black_list that pair it wont exit the position even if it hits the stoploss?

**Comment by xmatthias** [comment]
pairs with open position will always be added to the whitelist, ignoring all other settings (no longer in the whitelist, blacklist).

Once that position / trade is closed - it'll start respecting the new presence in the blacklist.

**Comment by polyvios-bc** [comment]
ok so that means there is no way to block completely a bot from trading a specific pair that holds a position if the bot is in running or paused mode?

**Comment by stash86** [comment]
not sure what you mean. Once it enter a trade, it won't re-enter it unless you specify it in adjust_trade_position. If you don't want any extra entry, don't use adjust_trade_position. Or is there something else I'm missing here?

**Comment by xmatthias** [comment]
No.
That'd be considered a severe bug - as it means you suddenly have 100% risk on this pair (you do no longer manage the position, so it could go to 0, ignoring all stoploss settings).

there is a "stopped" mode - which will completely stop the bot (for all pairs). 
That should be seen as similar to stopping the process - as the only option you then have is to start the bot again.

**Comment by polyvios-bc** [comment]
ok thanks for the info
