### ISSUE TITLE
Trailing stop loss 

### ISSUE THREAD

**Issue by polyvios-bc** [freqtrade/freqtrade#8936]
* Operating system:  debian 10
  * Python Version: 3.10
  * Freqtrade Version: latest
  
## Your question

We had a position on a coin  (MATIC) and there was a trigger for trailing stop loss. A limit order was created and if was getting filled the position would be closed with a profit. However the limit order was never filled and the unfilledtimeout kicked in after 20min. The limit order cancelled successfully. The price has moved but the bot was still detecting a trailing stop loss but this time the order would exit with a loss. I am trying to understand why it exit the position with a loss when it shouldnt

 <details>
<summary>trade record</summary>

```
[{
	"trade_id": 285,
	"pair": "MATIC/USDT:USDT",
	"base_currency": "MATIC",
	"quote_currency": "USDT",
	"is_open": false,
	"exchange": "binanceusdm",
	"amount": 81295.0,
	"amount_requested": 25733.1527746,
	"stake_amount": 59635.34444,
	"max_stake_amount": 59635.34444,
	"strategy": "Jafar2",
	"enter_tag": "kumo_breakout_short",
	"timeframe": 15,
	"fee_open": 0.0001,
	"fee_open_cost": 5.963534444,
	"fee_open_currency": "USDT",
	"fee_close": 0.00010000000000000002,
	"fee_close_cost": 6.01339114,
	"fee_close_currency": "USDT",
	"open_date": "2023-07-07 08:30:06",
	"open_timestamp": 1688718606161,
	"open_rate": 0.7335671866658466,
	"open_rate_requested": 0.7964,
	"open_trade_value": 59629.38090556,
	"close_date": "2023-07-18 17:16:01",
	"close_timestamp": 1689700561432,
	"realized_profit": -452.72291995,
	"realized_profit_ratio": -0.007592279394398631,
	"close_rate": 0.7397,
	"close_rate_requested": 0.7397,
	"close_profit": -0.007592279394398631,
	"close_profit_pct": -0.76,
	"close_profit_abs": -452.72291995,
	"trade_duration_s": 981955,
	"trade_duration": 16365,
	"profit_ratio": -0.007592279394398631,
	"profit_pct": -0.76,
	"profit_abs": -452.72291995,
	"exit_reason": "trailing_stop_loss",
	"exit_order_status": "closed",
	"stop_loss_abs": 0.7316,
	"stop_loss_ratio": -0.002,
	"stop_loss_pct": -0.2,
	"stoploss_order_id": null,
	"stoploss_last_update": null,
	"stoploss_last_update_timestamp": null,
	"initial_stop_loss_abs": 1.1379,
	"initial_stop_loss_ratio": -0.72,
	"initial_stop_loss_pct": -72.0,
	"min_rate": 0.6601,
	"max_rate": 0.8927,
	"leverage": 1.0,
	"interest_rate": 0.0,
	"liquidation_price": 1.4181739833332923,
	"is_short": true,
	"trading_mode": "futures",
	"funding_fees": 57.82106564,
	"open_order_id": null,
	"amount_precision": 0.0,
	"price_precision": 4.0,
	"precision_mode": 2,
	"orders": [{
			"amount": 25733.0,
			"safe_price": 0.6616,
			"ft_order_side": "sell",
			"order_filled_timestamp": 1688718606161,
			"ft_is_entry": true,
			"pair": "MATIC/USDT:USDT",
			"order_id": "26679318641",
			"status": "closed",
			"average": 0.6616,
			"cost": 17024.9528,
			"filled": 25733.0,
			"is_open": false,
			"order_date": "2023-07-07 08:30:07",
			"order_timestamp": 1688718607668,
			"order_filled_date": "2023-07-07 08:30:06",
			"order_type": "limit",
			"price": 0.6616,
			"remaining": 0.0
		},
		{
			"amount": 11688.0,
			"safe_price": 0.7284,
			"ft_order_side": "sell",
			"order_filled_timestamp": 1689009953383,
			"ft_is_entry": true,
			"pair": "MATIC/USDT:USDT",
			"order_id": "26721071666",
			"status": "closed",
			"average": 0.7284,
			"cost": 8513.5392,
			"filled": 11688.0,
			"is_open": false,
			"order_date": "2023-07-10 17:25:53",
			"order_timestamp": 1689009953385,
			"order_filled_date": "2023-07-10 17:25:53",
			"order_type": "limit",
			"price": 0.7283,
			"remaining": 0.0
		},
		{
			"amount": 11294.0,
			"safe_price": 0.75754,
			"ft_order_side": "sell",
			"order_filled_timestamp": 1689126533347,
			"ft_is_entry": true,
			"pair": "MATIC/USDT:USDT",
			"order_id": "26745701962",
			"status": "closed",
			"average": 0.75754,
			"cost": 8555.6307,
			"filled": 11294.0,
			"is_open": false,
			"order_date": "2023-07-12 01:48:53",
			"order_timestamp": 1689126533351,
			"order_filled_date": "2023-07-12 01:48:53",
			"order_type": "limit",
			"price": 0.7537,
			"remaining": 0.0
		},
		{
			"amount": 11058.0,
			"safe_price": 0.7698,
			"ft_order_side": "sell",
			"order_filled_timestamp": 1689243226795,
			"ft_is_entry": true,
			"pair": "MATIC/USDT:USDT",
			"order_id": "26766883760",
			"status": "closed",
			"average": 0.7698,
			"cost": 8512.4484,
			"filled": 11058.0,
			"is_open": false,
			"order_date": "2023-07-13 10:13:43",
			"order_timestamp": 1689243223793,
			"order_filled_date": "2023-07-13 10:13:46",
			"order_type": "limit",
			"price": 0.7698,
			"remaining": 0.0
		},
		{
			"amount": 10834.0,
			"safe_price": 0.78612,
			"ft_order_side": "sell",
			"order_filled_timestamp": 1689262846409,
			"ft_is_entry": true,
			"pair": "MATIC/USDT:USDT",
			"order_id": "26774090600",
			"status": "closed",
			"average": 0.78612,
			"cost": 8516.8709,
			"filled": 10834.0,
			"is_open": false,
			"order_date": "2023-07-13 15:40:46",
			"order_timestamp": 1689262846411,
			"order_filled_date": "2023-07-13 15:40:46",
			"order_type": "limit",
			"price": 0.7857,
			"remaining": 0.0
		},
		{
			"amount": 10688.0,
			"safe_price": 0.7964,
			"ft_order_side": "sell",
			"order_filled_timestamp": 1689263094641,
			"ft_is_entry": true,
			"pair": "MATIC/USDT:USDT",
			"order_id": "26774346607",
			"status": "closed",
			"average": 0.7964,
			"cost": 8511.9232,
			"filled": 10688.0,
			"is_open": false,
			"order_date": "2023-07-13 15:44:51",
			"order_timestamp": 1689263091546,
			"order_filled_date": "2023-07-13 15:44:54",
			"order_type": "limit",
			"price": 0.7964,
			"remaining": 0.0
		},
		{
			"amount": 81295.0,
			"safe_price": 0.7397,
			"ft_order_side": "buy",
			"order_filled_timestamp": 1689700561172,
			"ft_is_entry": false,
			"pair": "MATIC/USDT:USDT",
			"order_id": "26890410911",
			"status": "closed",
			"average": 0.7397,
			"cost": 60133.9115,
			"filled": 81295.0,
			"is_open": false,
			"order_date": "2023-07-18 17:09:03",
			"order_timestamp": 1689700143947,
			"order_filled_date": "2023-07-18 17:16:01",
			"order_type": "limit",
			"price": 0.7397,
			"remaining": 0.0
		}
	]
}]
```

</details>
 
 Logs:
 
[trail-logs.txt](https://github.com/freqtrade/freqtrade/files/12088559/trail-logs.txt)

**Comment by xmatthias** [comment]
you don't seem to be using stoploss on exchange - so what happens is when the bot detects the crossing of the stoploss, it'll place an exit order based on the configured pricing.

As the order didn't fill, you're most likely using "same" for exit pricing (or custom pricing via callbacks...) - which means the order waits for price action to "come back" to you - which in this case, didn't happen.

Now price is moving away from you for 20 minutes (it would  seem). 
Once the order cancels, price is still across the imaginary stoploss line - so it'll trigger again - this time, price moves in your favor and exits the trade.

if an exchange supports stop on exchange, i'd strongly recommend to also use it.
It'll place a trigger order at the stop price - with limit price set to a 1% offset (by default) to this stop price - so unless your pair gaps >1% without any volume in the orderbook, it'll fill almost certainly.

Alternatively, rethink your pricing for exit orders - or use market orders to get a guaranteed fill. obviously both options have some downsides which you'll need to weight accordingly.

**Comment by polyvios-bc** [comment]
Hmm what i am still not getting is on first stoploss that got triggered the order would exit with a profit as you can also see from the logs. 20min passed and order gets cancelled because we never got filled. 
So till this point everything works just fine and I understand this. 

Now what I dont get is why since the price moved against the first order that got cancelled there was again a stop limit trigger but this time exit with a loss. What i would expect is the second one to not get triggered at all since the price moved against. Am I missing something here?

**Comment by xmatthias** [comment]
Stoploss is an absolute value, that can only ever move into the profit direction.

For a long - that's up, for a short, that's down.

Now assuming your initial stop (for a long) triggered at a value of 90 - but price dropped to 80 in the meantime, it'll mean that once the order at 90$ is cancelled, a new one is placed at 80$.

80$ is clearly below the stoploss value - and it'll therefore attempt an exit, which this time succeeds.

if it's in profit or not doesn't matter - you didn't get the exit you wanted - and price moved against you. That's quite simple market basics - which can be avoided with proper market understanding (how do markets / trading work) - as well as proper configuration of the different exit methods.

**Comment by polyvios-bc** [comment]
ok thanks for the explanation

**Comment by polyvios-bc** [comment]
Reopening it since I have few more questions here. What you describe is the stoploss our issue is related to trailing stoploss after the positive offset.

**Comment by xmatthias** [comment]
trailing is your scenario - but it's basics of how stoploss behaves (if trailing or not), independent of trailing stop (though without trailing stop, you'll usually not have the trade swap from profit to loss, but from loss to "more loss".

Trailing moves the stoploss price towards the profit side (up on long, down on short) - but the stoploss price itself always exists.

**Comment by polyvios-bc** [comment]
Thanks for the info. Today I saw another case which i am trying to understand why that didnt work. So on a bot I added something like that:

```   
def confirm_trade_exit(self, pair: str, trade: Trade, order_type: str, amount: float,
                           rate: float, time_in_force: str, exit_reason: str,
                           current_time: datetime, **kwargs) -> bool:

        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        if exit_reason != 'force_exit' and trade.calc_profit_ratio(rate) < 0:
            # Reject selling with negative profit - exit manually
            return False
        return True
```

I tested that and I saw that it works was preventing some positions to exit with a loss. However today there was a case where although the profit_ratio was negative it managed to enter the position. Here is the trade exit:

`| 2023-07-20 08:24:09,307 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 771, 'exchange': 'Bybit', 'pair': 'AGLD/USDT:USDT', 'leverage': 1.0, 'direction': 'Short', 'gain': 'loss', 'limit': 1.024, 'order_rate': 1.024, 'order_type': 'limit', 'amount': 18388.0, 'open_rate': 0.6975329165760279, 'close_rate': 1.024, 'current_rate': 1.024, 'profit_amount': -6453.93516928, 'profit_ratio': -0.50337111, 'buy_tag': 'tow_mater_short', 'enter_tag': 'tow_mater_short', 'sell_reason': 'stop_loss', 'exit_reason': 'stop_loss', 'open_date': datetime.datetime(2023, 7, 13, 8, 4, 3, 866110, tzinfo=datetime.timezone.utc), 'close_date': datetime.datetime(2023, 7, 20, 8, 24, 9, 307642, tzinfo=datetime.timezone.utc), 'stake_amount': 12826.23527, 'stake_currency': 'USDT', 'base_currency': 'AGLD', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0}`

According with that message the confirm_trade_exit should return false right since i can see the profit_ratio: -0.50337111.

Am I missing something else here?

**Comment by froggleston** [comment]
First thing would be to print out what `trade.calc_profit_ratio(rate)` actually is. You should see some form of message in the logs that you aborted the exit.

**Comment by polyvios-bc** [comment]
yeah i saw the abort on previous trades and i was expecting to work and on this one but it didnt. And from the trade message after you can see that 'profit_ratio': -0.50337111 So I assume that should be the case and on confirm. I will add the print for sanity check. But wondering if there is any race condition here

**Comment by xmatthias** [comment]
first off - don't call `get_analyzed_dataframe` if you're not gonna use it's result. It's wasted time for something you'll not be using.

Then - be sure the function is actually used. There can be a ton of things going wrong - like indentation that's wrong - causing this function to no longer be part of the strategy - or a doubly-named strategy - and the one used by the bot is not the one you're editing (i've seen all most instances of this in the past).

**Comment by polyvios-bc** [comment]
indentation is def correct and there is no doubly named strategy from what i can see , so I am still very sceptical what else could cause that

**Comment by xmatthias** [comment]
Well quite honestly, other than "i use this callback, and got this, but expect something else", there's little to no information to help you any further.

The best suspicion is that the callback isn't used - reasons for that have been explained above.
You can best test for this by adding a print statement (and as suggested above, print the profit you're calculating as filter, too).

**Comment by stash86** [comment]
one thing that function can't overcome is a slippage. When a red candle went down fast, the rate that confirm_trade_exit saw and the actual rate being posted to the exchange would be different, which is often happens. I have few cases like this myself. I have a winning exit that ended up at -0.x% due to volatile price movements. You can't overcome it.
