### ISSUE TITLE
No history data when run hyperopt

### ISSUE THREAD

**Issue by godshades** [freqtrade/freqtrade#8938]
## Describe your environment

  * Operating system: ubuntu arm 20.04
  * Python Version: Python 3.8.10
  * CCXT version: 3.1.44
  * Freqtrade Version:  freqtrade 2023.6
  
## Your question

i already download data
```docker-compose run --rm freqtrade download-data --timeframes 1h --exchange binance --pairs BTC/USDT:USDT```
=> file BTC_USDT_USDT-1h-futures.json downloaded

but when run hyperopt
```docker-compose run --rm freqtrade hyperopt --hyperopt-loss SharpeHyperOptLossDaily --spaces buy sell roi stoploss trailing trades --strategy Bins --config user_data/config2.json -e 100```

i have this error:
```
freqtrade.data.history.idatahandler - WARNING - No history for BTC/USDT, futures, 1h found. Use freqtrade download-data to download the data
freqtrade.data.dataprovider - WARNING - No data found for (BTC/USDT, 1h, futures).
```

help me please

**Comment by xmatthias** [comment]
> No history for BTC/USDT, futures, 1h found

BTC/USDT is not a futures pair, and hasn't been for over half a year now.
use BTC/USDT:USDT as you did for downloading data (translated to - fix your config).

**Comment by godshades** [comment]
thanks, i'm understand
