### ISSUE TITLE
Export trades not working

### ISSUE THREAD

**Issue by mirono** [freqtrade/freqtrade#8939]
## Describe your environment

  * Operating system: macOS/Docker
  * Python Version: run inside docker
  * CCXT version: run inside docker
  * Freqtrade Version: freqtrade 2023.6
  
## Describe the problem:
Backtest runs ok, but when I added --export trades and --export-filename trades.txt the trades file is not created.
Also tried --export=trades and --export-filename=trades.txt

The backtest was run with:
docker compose run --rm freqtrade backtesting --config user_data/config.json --strategy MediumAdxStrategy --timerange 20230601-20270715 -i 5m --export trades --export-filename trades.txt

**Comment by xmatthias** [comment]
please provide the log from your run, so we can look at what's actually happening / where the file is written.

As you're using docker, the most likely reason is that the file is created in the container, so you'll not see it - as it'll disappear once the container is destroyed.

**Comment by mirono** [comment]
This is very reasonably what's happening. So the file path should be the path inside the container? What should I give it to  have it written into the mapped user_data folder(s)?
[logs.txt](https://github.com/freqtrade/freqtrade/files/12110200/logs.txt)

Logs attached.

**Comment by xmatthias** [comment]
well the way you provide it, it's written to "cwd" - which is `/freqtrade` within the image.
Assuming a (mostly) unmodified compose file - you should be able to use ` --export-filename user_data/trades.txt` to write it into the user directory - which is mounted from the host - and will therefore be persisted.

Please note:
`--export trades` is enabled by default - and will write a dated file into `user_data/backtest_results`. 
if you're using `freqtrade webserver` - you can load historic results from this directory.

**Comment by mirono** [comment]
Thanks, I verified that if I give it `user_data/backtest_results` it writes the file to the user_data folder, and also if I omit the filepath it will be part of the backtest results file. I'll check the UI later on.

**Comment by mirono** [comment]
Closing as it works ok.
