### ISSUE TITLE
Order Slicing or Time-Weighted Average Price Orders in Freqtrade

### ISSUE THREAD

**Issue by soleiljy** [freqtrade/freqtrade#8942]
Hi, 

I'm trying to open positions with a large amount of money (>$100,000), so looking for a way to mitigate slippage concerns when executing market orders. In such case, typically the following approaches are used in practice:

1. Order Slicing: Instead of placing a single large order, divide it into smaller orders of equal size. This strategy is known as order slicing. By doing so, you can execute the smaller orders at different times or using different strategies, reducing the risk of significant slippage. 
2. Time-Weighted Average Price (TWAP) Orders: A TWAP oder breaks up a large order into smaller parts and executes them at regular intervals over a specified time period. This strategy helps reduce the impact of executing a large order all at once, potentially minimizing slippage. 

Is there any way to use such strategies in Freqtrade? Thanks!

**Comment by xmatthias** [comment]
It's not builtin - but you can use the [`adjust_trade_position()`](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position) callback to place orders split however you'd like, or rather place an initial stake, and then adjust however you like).

Now no matter the size, i'd never recommend to use market orders (no matter the size, really) as you give control over the execution price to the exchange - but that's an entirely different topic.

**Comment by soleiljy** [comment]
Thanks for your response. Interesting to hear that you never recommend to sue market orders (no matter the size). I think in some strategies marker order would be better than limit order (for example, high-frequent trading where positions must be open based on signals). 

Can you explain more why you think using market orders is never recommended?

**Comment by stash86** [comment]
Personally, I would advise limit order for entry and market order for exit.

**Comment by xmatthias** [comment]
with a market order, you give away control of the fill price - allowing the market/exchange to fill you at whatever price.
It's got nothing to do with freqtrade by the way - but it's simply how markets work. 
You can do / get the same by manual trading - obviously assuming sufficient size for the market you're trading in (difficult to get the below on BTC/USDT).

Say current bid/spread is 99/101 - and you place a market buy (numbers are exagerated for math simplicity).

initially, you'd expect to get filled for 101 - but in reality, you don't know and have no way to control it - and depending on the orderbook depth, it could "eat" into the orderbook and fill for 105 or 110 just as well.
This process is called slippage - and is pretty normal for market orders.

Normally you'll have <1% slippage - but it'll depend on the market.

What's worse - you've now moved the market to 110 - your signal said "enter at 101, exit at 109".

No matter what strategy you're using - an entry at 105 or 110 was NOT what the signal said.
This is not as bad if you're trading a longer-term strategy on a pretty long timeframe (expected holding time at least a few days, and moves > 10%) - but for HFT strategies - where you expect to exit within a few hours - a slippage of 1-2% probably means your profit opportunity is gone already.

---

you can still get (almost) guaranteed fills without this risk, by using a "marketable limit order".
In the situation above, you may want to accept slippage up to 102 - so you place a limit buy order with a price of 102.
If there's enough liquidity in the orderbook, you'll get filled immediately, most likely at 101 or 102.

Sure, if there's not enough liquidity, the order will stay open - but i'd prefer a half-filled (half sized) position that entered at 102, than one that entered at 105 - which is rather far away from my expected entry.

**Comment by zhaohui-yang** [comment]
> with a market order, you give away control of the fill price - allowing the market/exchange to fill you at whatever price. It's got nothing to do with freqtrade by the way - but it's simply how markets work. You can do / get the same by manual trading - obviously assuming sufficient size for the market you're trading in (difficult to get the below on BTC/USDT).
> 
> Say current bid/spread is 99/101 - and you place a market buy (numbers are exagerated for math simplicity).
> 
> initially, you'd expect to get filled for 101 - but in reality, you don't know and have no way to control it - and depending on the orderbook depth, it could "eat" into the orderbook and fill for 105 or 110 just as well. This process is called slippage - and is pretty normal for market orders.
> 
> Normally you'll have <1% slippage - but it'll depend on the market.
> 
> What's worse - you've now moved the market to 110 - your signal said "enter at 101, exit at 109".
> 
> No matter what strategy you're using - an entry at 105 or 110 was NOT what the signal said. This is not as bad if you're trading a longer-term strategy on a pretty long timeframe (expected holding time at least a few days, and moves > 10%) - but for HFT strategies - where you expect to exit within a few hours - a slippage of 1-2% probably means your profit opportunity is gone already.
> 
> you can still get (almost) guaranteed fills without this risk, by using a "marketable limit order". In the situation above, you may want to accept slippage up to 102 - so you place a limit buy order with a price of 102. If there's enough liquidity in the orderbook, you'll get filled immediately, most likely at 101 or 102.
> 
> Sure, if there's not enough liquidity, the order will stay open - but i'd prefer a half-filled (half sized) position that entered at 102, than one that entered at 105 - which is rather far away from my expected entry.

Thanks for sharing, and I wonder is there any document introducting the  "marketable limit order" in freqtrade.

**Comment by xmatthias** [comment]
"marketable limit orders" is not a new concept freqtrade invented or introduced (i didn't even invent the term - binance calls it that in their docs, or at least used to in the past).

We assume somewhat decent market understanding from users - knowing how a limit order works (and what happens if you place a limit order that crosses the spead) is assumed as such basic knowledge - and as such, out of scope for the freqtrade docs.
