### ISSUE TITLE
Protections did not take effect

### ISSUE THREAD

**Issue by yili1992** [freqtrade/freqtrade#8956]
## Describe your environment

  * Operating system: Ubuntu 20.04.4 LTS
  * Python Version: Python 3.11.4 (python -V)
  * CCXT version: ccxt==3.1.44 (pip freeze | grep ccxt)
  * Freqtrade Version: freqtrade 2023.6 (freqtrade -V or docker compose run --rm freqtrade -V for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
I have used protections
```
    @property
    def protections(self):
        return [
            # {
            #     "method": "CooldownPeriod",
            #     "stop_duration_candles": 1
            # },
            {
                "method": "MaxDrawdown",
                "lookback_period_candles": 48,
                "trade_limit": 2,
                "stop_duration_candles": 12,
                "max_allowed_drawdown": 0.3,
            },
            {
                "method": "StoplossGuard",
                "lookback_period_candles": 24,
                "trade_limit": 2,
                "stop_duration_candles": 12,
                "only_per_pair": True,
                "only_per_side": True
            }
        ]
```
It has triggered a lock for all pairs.
<img width="463" alt="截屏2023-07-24 16 07 02" src="https://github.com/freqtrade/freqtrade/assets/3176589/87b2b982-becc-4d2e-80cf-04f8278c3947">
but , I found that freqtrade still make orders 
<img width="483" alt="截屏2023-07-24 16 07 24" src="https://github.com/freqtrade/freqtrade/assets/3176589/0261a67b-0a14-42f1-b94d-245c6e2ea22d">

**Comment by shawnli957** [comment]
@yili1992 Hi, do you run live trade with VPN?

**Comment by yili1992** [comment]
> 
@shawnli957 
No

**Comment by shawnli957** [comment]
@yili1992 How do you request data from Binance (or other exchanges) then? We both from China : )

**Comment by yili1992** [comment]
> 

@shawnli957  If you want to request data from Binance , you need  to set your config.json , such as 
```
    "ccxt_config": {
          "aiohttp_proxy": "http://127.0.0.1:1087",
          "proxies": {
            "http": "http://127.0.0.1:1087",
            "https": "http://127.0.0.1:1087"
          }
      }
```

**Comment by shawnli957** [comment]
@yili1992 Thank you. Do you mind check your 163 mailbox?

**Comment by yili1992** [comment]
> @yili1992 Thank you. Do you mind check your 163 mailbox?
@shawnli957 
What happened?

**Comment by shawnli957** [comment]
@yili1992 I was wondering if you could add my WeChat for further discussion.
My WeChat: 517466340

**Comment by xmatthias** [comment]
Please don't use github issues for private, 1:1 conversation, (or to exchange contact details), or for other communication that's not related to the issue topic, thanks.

---

Unfortunately, the info provided doesn't really paint a clear picture at all, as it's lacking a great deal of details which will be necessary to look at this.

Please provide the logs (unmodified) from the corresponding day - to give us a clear picture of what actually happened.
screenshots are very patient - and almost never conclusive.

**Comment by xmatthias** [comment]
@yili1992 any update on this?

Without logs, we'll have to close this issue, as it doesn't contain any actioanble information for us to investigate further.

**Comment by xmatthias** [comment]
Closing this as we had no further feedback.

If this is still an issue for you, feel free to comment below (with the requested logs) - so we can reopen this issue.
