### ISSUE TITLE
How to monitor two bots running on the same server through freqUI?

### ISSUE THREAD

**Issue by shawnli957** [freqtrade/freqtrade#8957]
## Describe your environment

  * Operating system: _Amazon Linux___
  * Python Version: __3.9.16___ (`python -V`)
  * CCXT version: __3.0.37___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __2023.3__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi, I'm trying to run two bots to trade on different accounts on one AWS EC2 server. I created different virtualenvs for the two bots. I ran **bot1** in **env1** with **'listen_ip_address=0.0.0.0'** and **'listen_port=8080'**. The bot ran smoothly and I could monitor its performance through freqUI. Then I ran **bot2** in **env2** with **'listen_ip_address=0.0.0.0'** and **'listen_port=8081'**. The logs in terminal said it found open trade created by **bot1**, which seemed not proper. And I didn't see **bot2** open any trades for account2. Also there were only open trade created by bot1 shown ob freqUI (**PUBLIC_IP_OF_EC2:8081**) .

My question is how to run another bot in a completely isolated env and monitor it through webUI. The question may seem dumb cuz I'm new to this.

**Comment by xmatthias** [comment]
First off - you shouldn't really expose your bot's directly to the internet without further restrictions (ip whitelisting, VPN, wireguard, ...).

Everyone can try to connect to the bot. 
While we try to keep things safe - it's still a risk i'd not be willing to take (considering that server will usually have your Exchange Keys on it).
It's quite likely ossible to DoS the bot with enough traffic - and cause other issues we didn't identify yet. Our API docs are pretty clear in this regard - exposing towards the internet directly is not considered safe.

---

For FreqUI, you'll need to refer to the [CORS](https://www.freqtrade.io/en/stable/rest-api/#cors) documentation - which will help you configure the bot correctly, so one UI instance can show both bots.

For the rest - you seem to be using the same database file - please refer to the [running multiple instances](https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade) docs to learn what needs to be changed for such a setup.

**Comment by shawnli957** [comment]
Thanks @xmatthias , that solved my problem.
