### ISSUE TITLE
Add support for the bot to use real HFT and use the orderbook to place limit orders with different position on the orderbook.

### ISSUE THREAD

**Issue by ZeroCool940711** [freqtrade/freqtrade#896]
One of the thing the bot really needs is support for HFT using the orderbook to place orders with different positions so we can buy and sell no matter what is the price for the currency pair we are using, it will also allow the bot to do MM (market making) as some exchange pay you per every position you open on the market an we can get more money from that, right now the bot is only buying and selling using the top bid/ask order on the orderbook, its not managing positions or anything, for some currencies like B2G/USDT the bot could make a lot of money in a single trade but right now its making almost no money as its not using the orderbook at all, take as an example the next screen capture, the bot could perfectly buy at 155.8 USDT and sell at 174.0 USDT or even higher and get a lot of money from a single trade but instead the bot is buying at 156.30 USDT and selling at 169.98 USDT which are the top orders on each side, its still making money but it could be making more, on the other side if the bot bought at 170 USDT and the price went down a bit and its not like in that picture the bot wont be able to sell right now because if it sells at the price the top order has it will lose money, if it could place an order at any position on the orderbook it could sell perfectly at 174.0 or 175 USD and get profit from that trade, this would be good for markets where the spread between each order on the orderbook is high, the bot could make in a day what its making now in a month, it would also allow you to sell what you bough in case a downtrend starts and you need to sell fast. I think if the bot has something like what I commented above it would be a lot better and will be making way more profit. If you have anything to add to what I said before just place a comment down. Thanks for the time you took to read this.

![untitled](https://user-images.githubusercontent.com/5977640/41202554-4f9ca732-6c7f-11e8-8062-6ff5f2543db9.jpg)

**Comment by xmatthias** [comment]
Honestly, i think the post lacks formatting which makes it difficult to read - at least to me.

Also - i would like to see a more precise specification ... would i get down to programming right now - i wouldn't know what to do based on the thing above, except "something with orderbook".

This may sound blunt - but remember that we're not all traders, and for me as a hobby-trader (at best ...) it's very difficult to understand the precise logic except that it would give us a ton more money than we get now ... 😉

**Comment by ZeroCool940711** [comment]
I understand @xmatthias , I will try tomorrow to make this issue/post better, im too lazy to do that right now, I have posted more information about that on slack so, probably will copy/paste some of those things here and make sure they are easy to read.

**Comment by xmatthias** [comment]
i think this was addressed in #1125.

please check https://github.com/freqtrade/freqtrade/blob/develop/docs/configuration.md on how to correctly configure this.

feel free to reopen if i misunderstood the connection between the issue and the pr.

**Comment by amjad-12** [comment]
Hello please is there any thing new to implement the MM with freqtrade

**Comment by xmatthias** [comment]
@amjad-12 please use the documentation to learn about what features were added in the last 5(!!) Years.

Asking in a random, old issue (which also contains an answer, btw) is not the right way.
