### ISSUE TITLE
how to use stake_amount as certain %  of total wallet balance instead of static value?

### ISSUE THREAD

**Issue by mhgutier** [freqtrade/freqtrade#8961]
## Describe your environment

  * Operating system: Mac OS 13.2.1
  * Python Version: 3.8.13
  * CCXT version: 1.93.60
  * Freqtrade Version: freqtrade 2023.6 (using docker stable image)
  
## Your question

is there a way to use 2% of total balance as stake amount?
how can i call total balance (not balance managed by bot) in custom_stake_amount?

```
    def custom_stake_amount(self, pair: str, current_time: datetime, current_rate: float,
                            proposed_stake: float, min_stake: Optional[float], max_stake: float,
                            leverage: float, entry_tag: Optional[str], side: str,
                            **kwargs) -> float:

        dataframe, _ = self.dp.get_analyzed_dataframe(pair=pair, timeframe=self.timeframe)

        return wallet_balance * .02
```

or is there a parameter to use percentage "stake_amount": instead of static value?

my option is to use 
"tradable_balance_ratio": unlimited
"max_open_trades": x - however i may need to change max open trades regularly to match 2% of wallet balance.,

**Comment by xmatthias** [comment]
> "tradable_balance_ratio": unlimited

That's an invalid setting. you'll probably want this to 1 or unconfigured - so everything in the account is used.
Setting this to 0.5 (50%) would mean that the bot will only use 50% of the balance - so for an account with 1000$ balance, it will use 500$ - and split this by max_open_trades.


> "max_open_trades": x - however i may need to change max open trades regularly to match 2% of wallet balance.,

Not really - to get 2% of the account balance - you'll always need 50 open trades - that'll always be "100% / 50", no matter the actual wallet balance.

Now I'm not sure if that's really what you're after (2% of the account balance) - as 50 parallel trades seem pretty much unrealistic.

**Comment by mhgutier** [comment]
thanks @xmatthias , so if i want to use only 50% of my total balance,
this will still give me 2% right? and it will only open 50 trades as balance will be insufficient due to .5 tradable balance?

    "max_open_trades": 100,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "dry_run_wallet" : 1000,
    "tradable_balance_ratio": .5,

**Comment by xmatthias** [comment]
well 2% of what?

your 1000 wallet will now be divided in 2 - so the bot will use 500$ - and will split that into 100 different trades a 5$ (which is too small for most markets, and will resut in a non-operational bot). 

That's not 2% of anything, really (not of 1000$, not of 500$) - so i don't think your math is correct.

Aside from that, everything where your final stake comes out <20$ will probably not work unless your exchange specifically allows this.

---

Personally, i think you read somewhere a suggestion to **risk 2% of your account per trade** - but you took some wrong assumptions on how to get to that (i've never seen "trade 2%")

Your calculations / approach however won't give you 2% _risk per trade_ unless you assume you'll be using no stoploss (or 100% stoploss), and therefore have a risk exposure of 100% per trade.

Assuming a pretty sane 10% stoploss, your (desired) calculation will be risking 0.2% per trade. Your position will be 2% of the account - but you can only lose ~10%.
to actually **risk** 2% per trade, your 1000$ account should be split into 5 trades - with a stoploss of 10%, your calculation will then be 1000$ / 5 (trades) / 10 (stoploss/risk) - which will give you a risk (amount you can lose per trade) of 20$ (or 2%) - but a position size of 200$.

**Comment by moinonin** [comment]
Right @xmatthias many people are ignorant about this fact. Whenever you read "you should not risk more than 2% in a trade", it means these equations must be true:
1. stoploss/max_open_trades <= risk, which is 0.02
2. tradeable_balance/max_open_trades = stake_amount, and of course,
3. stake_amount = tradeable_amount * risk/stop_loss

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.
