### ISSUE TITLE
Why AutoLock?

### ISSUE THREAD

**Issue by shawnli957** [freqtrade/freqtrade#8966]
## Describe your environment

  * Operating system: __Windows 11__
  * Python Version: _3.10.12__   
  * CCXT version: _4.0.26____
  * Freqtrade Version: __2023.6__ 
  
## Your question
Hi, I noticed after one trade was closed, the pair was auto locked for one time frame. What is the rationale for designing this mechanism？ How could I disable it? Thank you.

**Comment by xmatthias** [comment]
Autolock will prevent repeat entries on the same signal.
That's actually a quite prevalent problem with ROI / stoploss exists, which exit within the opening candle.
As a consequence - the entry signal is still open, and would be acted on, potentially causing a dead spiral, causing several stoplosses in a row within the same candle.


Now likelyhood of this happening increases with higher timeframes - but it's not optional, and we have currently no plans on making it optional, either.

If you experience an exit, and would like to re-enter immediately, you'll only incur fees without real reason - as the exit / entry won't differ much, as the entry signal was already active during the exit, and would therefore happen seconds after the actual exit.

It'll also ensure backtesting alignment, where this is prevented for technical / logic reasons (therefore this lock won't show up in backtest reports).

**Comment by shawnli957** [comment]
@xmatthias What if I trade futures and I am in long position. At the beginning of one timeframe, my strategy generate signal exit long and enter short simultaneously. The bot would exit long, then auto lock. So I would miss the enter short signal in this timeframe.

**Comment by xmatthias** [comment]
Thats correct. Switching positions is currently not supported.

You also can't backtest that, therefore its a risk we'll currently not support.
