### ISSUE TITLE
pip install ta - normal site-packages is not writeable

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#8967]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Version of freqtrade container below (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.6 stable under Docker Desktop (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Sending the command docker exec -it freqtrade pip install ta generates this message:
Defaulting to user installation because normal site-packages is not writeable

Then the process begins:

Collecting ta
  Using cached ta-0.10.2-py3-none-any.whl
Requirement already satisfied: numpy in /home/ftuser/.local/lib/python3.11/site-packages (from ta) (1.24.3)
Requirement already satisfied: pandas in /home/ftuser/.local/lib/python3.11/site-packages (from ta) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ftuser/.local/lib/python3.11/site-packages (from pandas->ta) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/ftuser/.local/lib/python3.11/site-packages (from pandas->ta) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /home/ftuser/.local/lib/python3.11/site-packages (from pandas->ta) (2023.3)
Requirement already satisfied: six>=1.5 in /home/ftuser/.local/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->ta) (1.16.0)

Unfortunately I still get the Freqtrade message "no module named ta", after starting the bot.
Tell me, if you need more details.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Libraries that are installed by default are listed in the [strategy documentation](https://www.freqtrade.io/en/stable/strategy-customization/#indicator-libraries).

For Docker, we have a separate segment about [additional dependencies with docker](https://www.freqtrade.io/en/stable/docker_quickstart/#additional-dependencies-with-docker) - including a link to an example Dockerfile, which will show you how to install additional dependencies.

**Comment by myNextCoder** [comment]
Fantastic, it works :)
