### ISSUE TITLE
How to modify the number of klines data each request from Binance?

### ISSUE THREAD

**Issue by shawnli957** [freqtrade/freqtrade#8970]
## Describe your environment

  * Operating system: _Windows_11_
  * Python Version: _3.10.12_ 
  * CCXT version: _4.0.26_ 
  * Freqtrade Version: _2023.6_ 
  
## Your question

Hi, I found the number of klines data each request from Binance (also the rows of dataframe which to generate enter/exit signals) is **1000** no matter what the timeframe is. I would like to try high frequency trading, in which excessive number of klines data may slow down the computation. Actually, there are only few rows of data needed. Also it may incur rate limit error from Binance.  So I am wondering how to modify the default number of klines data each request from Binance.

**Comment by xmatthias** [comment]
1000 is the default for binance. This can be increased via `startup_candle_count` up to ~5x of one request - but it cannot be reduced.

your fear of rate limits is also unjustified - it's exactly 1 call per pair - so binance will treat your request always the same, no matter if you're requesting 1 candle, or 1000 candles.
