### ISSUE TITLE
RemotePairList doesn't recognise comments and doesn't load pairs

### ISSUE THREAD

**Issue by vaidab** [freqtrade/freqtrade#8971]
**FreqUI Version**

- Version of freqUI: 0.9.5
- version of freqtrade: docker-2023.7.dev-68741239

**Describe the bug**
Loading a local file via RemotePairList doesn't recognise comments.

**To Reproduce**
1. Go to Freqtrade UI -> Pairlist Config
2. Use URL: file:////freqtrade/user_data/config/pairlist-static-binance-usdt.json
3. Click on Evaluate
4. See error + remove comments
5. Even with the corrected errors you get an empty "[]" as a result.

**Expected behavior**
It should load a functional pairlist file without an issue.

**Desktop:**
 - OS: MacOSX
 - Browser Safari 
 - Version 16.5.2
 
<img width="2296" alt="Screenshot 2023-07-26 at 20 52 40" src="https://github.com/freqtrade/frequi/assets/19855026/dd651ebc-c44a-44c2-81f9-82e2c2992851">

pairlist-static-binance-usdt.json:
```
{
	"exchange": {
		"pair_whitelist": [
			"DYDX/USDT:USDT",
			"OP/USDT:USDT",
			"MANA/USDT:USDT",
			"LTC/USDT:USDT",
			"THETA/USDT:USDT",
			"SOL/USDT:USDT",
			"RDNT/USDT:USDT",
			"MKR/USDT:USDT",
			"KAVA/USDT:USDT",
			"MATIC/USDT:USDT",
			"GALA/USDT:USDT",
			"PEOPLE/USDT:USDT",
			"WRX/USDT:USDT",
			"TOMO/USDT:USDT",
			"LINK/USDT:USDT",
			"TRX/USDT:USDT",
			"ARB/USDT:USDT",
			"DOGE/USDT:USDT",
			"T/USDT:USDT",
			"APT/USDT:USDT",
			"ETH/USDT:USDT",
			"CFX/USDT:USDT",
			"LDO/USDT:USDT",
			"NEAR/USDT:USDT",
			"INJ/USDT:USDT",
			"COMP/USDT:USDT",
			"ARPA/USDT:USDT",
			"LINA/USDT:USDT",
			"ROSE/USDT:USDT",
			"VET/USDT:USDT",
			"AAVE/USDT:USDT",
			"XMR/USDT:USDT",
			"SUI/USDT:USDT",
			"FET/USDT:USDT",
			"RNDR/USDT:USDT",
			"SNX/USDT:USDT",
			"MAGIC/USDT:USDT",
			"AGIX/USDT:USDT",
			"DOT/USDT:USDT",
			"EOS/USDT:USDT",
			"APE/USDT:USDT",
			"ALPHA/USDT:USDT",
			"ETC/USDT:USDT",
			"EGLD/USDT:USDT",
			"AVAX/USDT:USDT",
			"KNC/USDT:USDT",
			"UNI/USDT:USDT",
			"ICX/USDT:USDT",
			"WAVES/USDT:USDT",
			"ANKR/USDT:USDT",
			"EDU/USDT:USDT",
			"XRP/USDT:USDT",
			"SAND/USDT:USDT",
			"FIL/USDT:USDT",
			"STX/USDT:USDT",
			"ATOM/USDT:USDT",
			"ZIL/USDT:USDT",
			"FLOW/USDT:USDT",
			"BCH/USDT:USDT",
			"GRT/USDT:USDT",
			"FTM/USDT:USDT",
			"MTL/USDT:USDT",
			"MASK/USDT:USDT",
			"CRV/USDT:USDT",
			"BTC/USDT:USDT",
			"ADA/USDT:USDT",
			"AXS/USDT:USDT",
			"LRC/USDT:USDT"
		]
	},
	"pairlists": [
		{"method": "StaticPairList"},
		{
			"method": "PriceFilter",
			"low_price_ratio": 0.003
		},
		{
			"method": "SpreadFilter",
			"max_spread_ratio": 0.0075
		},
		{
			"method": "RangeStabilityFilter",
			"lookback_days": 3,
			"min_rate_of_change": 0.03,
			"refresh_period": 1800
		},
		// {
		//     "method": "VolatilityFilter",
		//     "lookback_days": 3,
		//     "min_volatility": 0.01,
		//     "max_volatility": 0.75,
		//     "refresh_period": 43200
		// },
		{
            "method": "ShuffleFilter",
            "seed": 13 // for backtesting compatibility
        }
	]
}

```

**Comment by xmatthias** [comment]
I've moved this to freqtrade, as it's not really an issue with freqUI, but with your pairlist file.

The format you're trying to load is a configuration - but [remotepairlist](https://www.freqtrade.io/en/latest/plugins/#remotepairlist) specifies a separate format, specifically designed for this usecase.

It's correct that the pairlist definition doesn't allow comments - but that doesn't change the fact that your fileformat isn't valid for this usecase. 
The main point for the RemotePairlist is via an API / webservice, where you'd expect to get a correctly formatted json - so i i'm not entirely sure if trying to support non-standard json (json with comments) makes sense for this.

**Comment by vaidab** [comment]
I understand.
I think it would make sense to modify StaticPairList to be able to get the files from another config.
To add a field: "Config file to fetch pairlist from".
That would provide a solution to my use case (a config file containing pairlists)

As a workaround, I'll duplicate that config file and fit it for RemotePairList format.

**Comment by vaidab** [comment]
Update:
Using the suggested file:

```
{
    "pairs": ["XRP/USDT", "ETH/USDT", "LTC/USDT"],
    "refresh_period": 1800,
}
```
Gives error:

> Expecting property name enclosed in double quotes: line 4 column 1 (char 81)

Note that it's property name, not value, so unrelated to 1800 (but I've also tried quoting 1800)

<img width="2001" alt="Screenshot 2023-07-27 at 09 55 51" src="https://github.com/freqtrade/freqtrade/assets/19855026/34c853ce-001c-41b0-ab88-c12b033b2d65">

**Comment by xmatthias** [comment]
If you use a good editor (vscode, for example) - it'll highlight the syntax error in the file for you - which in this case, is the trailing comma on refresh_period.

> I think it would make sense to modify StaticPairList to be able to get the files from another config.

You can use [multiple configuration files](https://www.freqtrade.io/en/stable/configuration/#multiple-configuration-files) for this.
it's not dynamic from a webserver perspective, but there's no plans to complicate staticpairlist with this, as it'll serve no real purpose (there's multiple ways for this already, don't see why we need to add yet another one to accomplish the same exact task).

**Comment by vaidab** [comment]
Sorry for that, even with the "," taken out, the results tab is empty: "[]"

**Comment by Bloodhunter4rc** [comment]
> Sorry for that, even with the "," taken out, the results tab is empty: "[]"

make sure you are in the correct market "XRP/USDT" naming is for spot, but previously you posted a futures configuration which would be "XRP/USDT:USDT"

**Comment by xmatthias** [comment]
Using a properly formatted pairs file - with the correct, matching exchange works fine
Obviously you can't use spot pairs on futures and viceversa - as these will be filtered out.

![image](https://github.com/freqtrade/freqtrade/assets/5024695/03fc6a89-0eda-4006-b399-9b0f45f20dfc)
