### ISSUE TITLE
Incorrect data from freqtrade dataprovider

### ISSUE THREAD

**Issue by Ajay-2007** [freqtrade/freqtrade#8972]
## Describe your environment

  * Operating system: 20.04.1-Ubuntu
  * Python Version: 3.9.5
  * CCXT version: ccxt==4.0.36 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.7.dev-d638a4a0f (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*
While using self.dp.get_pair_dataframe(), freqtrade is returning incorrect data for monthly timeframe also the dates in date column is not consistent with the monthly timeframe it should be first day of the month

### Steps to reproduce:

  1. freqtrade trade --strategy StrategyName --config config.json
  
### Observed Results:

  * What happened? 
  * What did you expect to happen?
getting informative data for monthly timeframe returns incorrect data
It should return monthly data till June but it's returning the data till May

### Relevant code exceptions or logs
```python

  def informative_pairs(self):

      pairs = self.dp.current_whitelist()

      # _1d_informative_pairs = [(pair, '1d') for pair in pairs]
      _1w_informative_pairs = [(pair, '1w') for pair in pairs]
      _1M_informative_pairs = [(pair, '1M') for pair in pairs]

      # informative_pairs = _1d_informative_pairs +
      informative_pairs = _1w_informative_pairs + _1M_informative_pairs

      return informative_pairs


  def populate_indicators(self, df_1d: DataFrame, metadata: dict) -> DataFrame:
      """
      # first check if dataprovider is available
      if self.dp:
          if self.dp.runmode.value in ('live', 'dry_run'):
              ob = self.dp.orderbook(metadata['pair'], 1)
              df['best_bid'] = ob['bids'][0][0]
              df['best_ask'] = ob['asks'][0][0]
      """
      start_time = time.time()
      if not self.dp:
          return df

      _1d_inf_tf = '1d'
      _1w_inf_tf = '1w'
      _1M_inf_tf = '1M'
      is_backtesting=False

      # df_1d = self.dp.get_pair_dataframe(
      #     pair=metadata['pair'], timeframe=_1d_inf_tf)

      df_1w = self.dp.get_pair_dataframe(
          pair=metadata['pair'], timeframe=_1w_inf_tf)

      df_1mo = self.dp.get_pair_dataframe(
          pair=metadata['pair'], timeframe=_1M_inf_tf)
      print(df_1mo.tail())
```
Note: Please copy/paste text of the messages, no screenshots of logs please.

  // paste your log here
  ```
2023-07-27 07:15:27,403 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USDT pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
                        date     open     high      low    close        volume
41 2023-01-13 00:00:00+00:00  23119.5  25347.6  21338.0  23129.6  1.502520e+07
42 2023-02-12 00:00:00+00:00  23129.7  29184.8  19521.6  28454.9  2.331746e+07
43 2023-03-14 00:00:00+00:00  28454.8  31059.0  26919.3  29223.0  1.465421e+07
44 2023-04-13 00:00:00+00:00  29223.0  29840.0  25751.0  27201.1  1.332816e+07
45 2023-05-13 00:00:00+00:00  27201.1  31500.0  24777.0  30460.2  1.409930e+07
  ```

**Comment by xmatthias** [comment]
What exchange are you getting this output from (and what trading-mode)?

Trying your code with binance, i get the following output, which seems correct to me (filtered to BTC only)..

```
BTC/USDT 1w
                         date      open      high       low     close        volume
305 2023-06-19 00:00:00+00:00  26339.98  31431.94  26256.61  30462.66  408189.22942
306 2023-06-26 00:00:00+00:00  30462.67  31282.00  29500.00  30617.03  294881.44198
307 2023-07-03 00:00:00+00:00  30617.02  31500.00  29701.02  30160.71  244056.69119
308 2023-07-10 00:00:00+00:00  30160.71  31804.20  29900.00  30231.99  269249.39031
309 2023-07-17 00:00:00+00:00  30232.00  30417.46  29512.00  30083.75  180919.27148
BTC/USDT 1mo
                        date      open      high       low     close        volume
67 2023-02-01 00:00:00+00:00  23125.13  29184.68  19549.09  28465.36  1.815888e+07
68 2023-03-03 00:00:00+00:00  28465.36  31000.00  26942.82  29233.21  1.626746e+06
69 2023-04-02 00:00:00+00:00  29233.20  29820.00  25811.46  27210.35  1.302000e+06
70 2023-05-02 00:00:00+00:00  27210.35  27210.35  27210.35  27210.35  0.000000e+00
71 2023-06-01 00:00:00+00:00  27210.36  31431.94  24800.00  30472.00  1.387207e+06
```

**Comment by Ajay-2007** [comment]
Hey @xmatthias, thanks for the quick response, I've running the code for Binance futures, In the monthly output you provided, should't all the date index start with yyyy-mm-01?, Although it's way clear output than I got, I'll run the code again and let you know if I see any inconsistency.

**Comment by Ajay-2007** [comment]
@xmatthias, here's the output I just ran, I am getting correct data for weekly timeframe but inconsistent output for Monthly data, 
![image](https://github.com/freqtrade/freqtrade/assets/32496279/2900ea03-9233-43b9-837d-64b5f35673c3)

**Comment by xmatthias** [comment]
Nice spot - seems like nobody really ever used >1W data - or at least nobody looked at the data carefully.

Will be fixed shortly.

**Comment by Ajay-2007** [comment]
Thanks @xmatthias, for looking into the issue.

**Comment by Ajay-2007** [comment]
Thanks @xmatthias for resolving the issue, I've tested the latest release on freqtrade and it's working fine.
