### ISSUE TITLE
adjust_entry_price() being called for exit order

### ISSUE THREAD

**Issue by dnuno89** [freqtrade/freqtrade#8973]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: 3.8.10 and 3.11.4
  * CCXT version: 3.11.44 (and others before that)
  * Freqtrade Version: 2023.4 and 2023.6
  

## Describe the problem:

After a limit exit order is placed, when the next candle arrives, the order is cancelled and replaced by an entry order, thus increasing the trade instead of decreasing it. After that, if exit conditions are still fulfilled, the same exit, cancel, entry bucle is repeated until an exit is fully filled before the next candle. 
This has happened many times in Gate.io, and also in kucoin (which is not officially supported so i'll stick to gate.io). This has happened even though I have max_entry_position_adjustment = 1. I have checked that adjust_trade_position() is not called in such case (i have print statements). The messages I receive in telegram make me think that adjust_entry_price() is being called for an exit order, thus replacing it with an entry order. I do not have adjust_entry_price() implemented in my strategy, so the default function applies.

Given this is a new feature, and the lack of other issues related to this, I worry is something related to my configuration. I did update python, create a new virtual environment, and install from 0 the 2023.6 freqtrade version, with no changes. Maybe I lack something in my config that creates this? Anyway, I thought this is a bug since adjust_entry_price() should never be called for an exit order.

This is all related to spot with no leverage markets, at 5 minute candles.

A capture from my telegram:

![image](https://github.com/freqtrade/freqtrade/assets/11979371/c830da58-9568-4c90-9b23-5f014c750402)

### Steps to reproduce:

1. Exit a trade on gate.io, which should be partially filled (I think, at least it was always partially filled when it happened to me)
2. Wait for the next candle.
  

Thanks

**Comment by xmatthias** [comment]
Logs, the only thing that will help us to look at this are logs.

At least from the time of the initial exit order (basically when you get the "exit" message) until the order replacement - but usually, having more logs is better.

**Comment by xmatthias** [comment]
It's a nice find - and is pretty easily reproducible.
Will look into fixing this soon
