### ISSUE TITLE
Lookahead_analysis - TimeRange.parse_timerange(self.local_config['timerange'])

### ISSUE THREAD

**Issue by sabatale** [freqtrade/freqtrade#8995]
## Describe your environment

202307 on Docker.

## Describe the problem:

Testing the new lookahead-bias command gives the following error.

How do I troubleshoot this? It looks like this is coming from the analysis initialization rather than the strategy?

```
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 146, in start_lookahead_analysis
    LookaheadAnalysisSubFunctions.start(config)
  File "/freqtrade/freqtrade/optimize/lookahead_analysis_helpers.py", line 188, in start
    LookaheadAnalysisSubFunctions.initialize_single_lookahead_analysis(
  File "/freqtrade/freqtrade/optimize/lookahead_analysis_helpers.py", line 158, in initialize_single_lookahead_analysis
    current_instance.start()
  File "/freqtrade/freqtrade/optimize/lookahead_analysis.py", line 233, in start
    self.fill_full_varholder()
  File "/freqtrade/freqtrade/optimize/lookahead_analysis.py", line 163, in fill_full_varholder
    parsed_timerange = TimeRange.parse_timerange(self.local_config['timerange'])
                                                 ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'timerange'
```

### Steps to reproduce:

`docker-compose run --rm freqtrade lookahead-analysis --config user_data/config.json --dry-run-wallet 0.03 --strategy-list strategyname`

**Comment by perkmeister** [comment]
I looks like `lookahead-analysis` requires the `--timerange` parameter in the command. In backtesting you can leave that out and it will default to all available data. Try adding that to the command.

**Comment by sabatale** [comment]
Oh that's what the timerange was! Thanks a lot!

**Comment by xmatthias** [comment]
> In backtesting you can leave that out and it will default to the last 30 days (I believe)

The default is to use all available data for backtesting (unconstraint), not 30 days.

Now this is not really desired for lookahead-analysis - as it can lead to long backtest times (where we backtest multiple times).

We'll however look into improving behavior around this

**Comment by hippocritical** [comment]
One solution would be to dynamically see how many min-trades it needs and run a backtest with let's say 30 days first and then 

- figure out where it should go according to that result and the available timerange
- just use all data
- throw a proper error message that the user is forced to specify a timerange

I d prefer solution 3  to just throw errors, 1 and 2 would turn this into a little more of a flexible thing, but edge cases might ruin the whole thing again.

**Comment by perkmeister** [comment]
> The default is to use all available data for backtesting (unconstraint), not 30 days.

OK, sorry (I was sure a long time ago it did that. Oh well, my mistake).
