### ISSUE TITLE
Add self.market_direction to the custom exit method

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#8999]
## Describe your environment
(if applicable)

  * Operating system: Linux mint Una
  * Python Version: Python3.10
  * CCXT version: 4.0.12
  * Freqtrade Version: 2023.7.dev-f020daa35

## Describe the enhancement

*Explain the enhancement you would like*

It would be nice to reverse a direction of a trade right on the custom exit. Meaning that it will exit and enter the opposite direction immediately, assuming you are not using plugins like cool down. Any ideas on how this can be done?

**Comment by xmatthias** [comment]
You can't reverse a trade at the moment.

While this MAY come in the future, it's not something that's being actively looked at for now.

It'll definitely not be done through the `custom_exit` callback - but will have to be considered as a "new" signal i'd think - but the implications for backtesting are non neglectible, and i doubt it'll be looked at before a ton of other, more useful enhancements have been looked at.

---

I'm not entirely sure how `self.market_direction` plays into this - as there's nothing preventing you from using that (as is) in any callback or method - so the actual title of the question is already possible.
Adding it as a parameter is pointless / wrong - as you'd then have 2 ways to access the same information.
