### ISSUE TITLE
The setup/installation instructions are very confusing.

### ISSUE THREAD

**Issue by 2morowMan** [freqtrade/freqtrade#9000]
## Describe your environment

  * Operating system: ____win10
  * Python Version: _____ 3.11.4
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * certifi==2023.5.7
charset-normalizer==3.1.0
idna==3.4
numpy==1.24.3
panda==0.3.1
pandas==2.0.1
python-dateutil==2.8.2
pytz==2023.3
requests==2.30.0
six==1.16.0
ta==0.10.2
tzdata==2023.3
urllib3==2.0.2
  * Freqtrade Version: ____ 2023.7
  
## Your question
The setup/installation instructions....

Quickstart with docker
  install docker desktop - done
  follow script instructions: make ft_userdata, pull, make default script - done

docker-compose up 
  AND ERRORS !!!!!!!!!!!!
  using default 0.0.0.0 is insecure, WARNINGS...

So should this be 127.0.0.1 ??? from the many pages i've read i am just confused as each is used in different circumstances - but i seem to have both requirements using docker on windows ?!?!?!

Also do i need to install Python ?? how about ta-lib ??
  one link regarding python goes straight to installing chocolaty!?!?!?!? and *really* confusing documentation...

So please can you clarify the start. i bet more people would join ...

Answers re python --- (this should be clearly stated, like at the start before directing people to docker)
install python.
goto python.org, download and install python, tick all options.
then open powershell and type >pip  install ta,  >pip install pandas
THESE two lines would have saved in hours !!

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Stick to ONE installation method and you'll be fine.
We support multiple methods (as well as multiple operating systems) - and will continue to do so. 
This can be confusing if you start to hop around between the installation methods -  but if you actually stick to one, you'll find that it's not.


If you're using docker - great. ignore the windows installation
Not using docker but on windows? also great - use the windows installation documentation.

The great thing is - this is open source, you're more than welcome to help improve the documentation if you think it could be improved :) 

You're right about the Warning of 0.0.0.0 being insecure, we'll hide that from docker users in the future, as it's really unnecessary in that case.

**Comment by 2morowMan** [comment]
Thanks for the reply,
i DID stick to one installation - and nothing works as expected/required...
This is a classic example of the 'experts' not recognising whats the noobs
require.
Ive known quite a few people to give up completely on this project because
the instructions are so confusing.

AND a couple of years back when i tried to improve the documentation all
edits were rejected.

Maybe i try again, but i still need answers - should it be 127.0.0.1 - the
default settings 0.0.0.0 dont work ?!?!?!?!

**Comment by xmatthias** [comment]
> Maybe i try again, but i still need answers - should it be 127.0.0.1 - the default settings 0.0.0.0 dont work ?!?!?!?!

127.0.0.1 is correct for local deployments - 0.0.0.0 is correct for docker deployments.
A description for the correct configuration with docker can be found [here](https://www.freqtrade.io/en/stable/rest-api/#configuration-with-docker).

There is no "correct" in regards to listening address beyond that - as it'll depend on your network setup.
Setup may be different for a VPS / Server, where it'll depend on the actual network configuration - and the availability (or non-availability) of a VPN or wireguard tunnel - and the willingness to use an SSH tunnel.

All of these concepts may be complicated for a beginner - but are also out of scope of what the freqtrade documentation aims to / should cover.

**Comment by jackchalat** [comment]
Really appreciate @xmatthias for his patience with everyone here.

@BigJonMMXX You need to learn the basic of docker first. Using docker to install Freqtrade is the easiest method for non-coders. It looks like you used docker so `0.0.0.0` should be correct. If you got it wrong, you can change it in `user_data/config.json` under `api_server`.

I'd suggest you spend more time experimenting on your own. If you already have trouble setting up Freqtrade, developing a profitable strategies will be much harder. Personally, I think Freqtrade documentation is very clear  and has many examples.

**Comment by 2morowMan** [comment]
Thankyou for your opinion, but i disagree with your assumptions, and your
conclusions.

I have spent over two years playing around with freqtrade, and over thirty
years in programming and IT - just how long are we supposed to be involved
before you accept others have beneficial insight ?!
i suggest you spend more time accepting more experienced experts
might actually have something to say...

The documentation may be clear to you. And i guess you write similar. But
*decades* of experience tells me there is plenty of room for improvement.
Here's a little test - on a clean computer, go through the documentation,
without using any prior experience or knowledge, and you will see for
yourself there are many confusing and contradictory steps.

as for using 0.0.0.0...
warnings appear when container is started "warning  - security warning -
this is insecure..."
this is unnecessary and disturbing for newbies. Being dismissive is not the
best response!


Ive never understood the reply "it works for me...". If people say its not
clear, or it doesnt work, then there is room for improvement.

Disclaimer: there is no personal criticism in my posts.

**Comment by 2morowMan** [comment]
Thank you for the reply.
yes, knowing docker is solution to this. i didnt realise docker binds to
containers... so sticking with 0.0.0.0 allows connections from all eth0

And of course there was a windows gotcha of needing a restart !
Thanks again.
Love the project.

**Comment by xmatthias** [comment]
> as for using 0.0.0.0... warnings appear when container is started "warning - security warning - this is insecure..." this is unnecessary and disturbing for newbies. Being dismissive is not the best response!

If you read my above comment very carefully (last sentence of my first answer) and look at the linked commit - you'll notice that this message has been removed when running in a docker environment.

---

As for the rest - as mentioned above - if you think there's improvements to be made to the documentation, feel free to submit a Pull Request (also called PR). 
Expert view IS clearly a problem, and for learners, the best way to ensure it'll stick is by trying to explain it to someone else - by contributing to the documentation of that project, we can combine both.

As you seem to have negative experiences with this (not with this project, based on your github account history), here are some tipps for this to get a change accepted:

* do small, concise Pr's (Don't rework 20 pages and expect it to be accepted). Rewrite a paragraph / section at once, and see to have this accepted instead.
* Nobody likes to spell-check someone elses text, as that's really pointless work that can be automated - best use a spell-checker to ensure your spelling is correct.
* Be open to "request for change". Don't treat this as "i did it wrong" - but as positive feedback "this area could be improved". 
* In case of change requests, don't abandon the PR, but either answer to the comments or implement the changes 
* Don't expect immediate review. Depending on the size, reviews take time - time people usually devote their free time to (at least in this project).

---


I'll be closing this Issue - as it don't think it leads anywhere. Docs can always be improved - there won't be a need for an explicit issue for this.

**Comment by 2morowMan** [comment]
Thank you very much for your time. These tips are useful.
