### ISSUE TITLE
It would be nice to have a 'trade' arg in confirm_trade_entry

### ISSUE THREAD

**Issue by pine2023** [freqtrade/freqtrade#9002]
## Describe your environment
(if applicable)

  * Operating system: ____ Linux
  * Python Version: _____ 
  * CCXT version: _____ 
  * Freqtrade Version: ____ freqtrade docker-2023.7.dev-ead9e6f1

## Describe the enhancement

Hi,

I want to avoid a situation where the entire trade is overly long or overly short.
Specifically, I would like to control the ratio of total longs and shorts in order to hedge against equal sharp movements of the entire pair. (My goal is long:short ratio = 1:1)

I expected it to be resolved in confirm_trade_entry() and I wanted to call the currently open trade, but there is no 'trade' argument in that method.
(But it exists in confirm_trade_exit())

If my approach is correct, I'd really appreciate adding a feature.
Also let me know if there is another way

**Comment by xmatthias** [comment]
By the time `confirm_trade_entry()` is called, there is no "trade" object yet.
no order was placed, all we have so far is a signal, and a price we MAY place the order (depenending on the outcome of this method).
As such, a "trade" object at this point in time does not make sense, and would be almost completely empty (and may behave unpredictably, as several fields cannot be filled yet).

---

I'm not entirely sure i understand what you're trying to do - but "length of the trade" is always 0 when `confirm_trade_entry()` would be called. It's not called for trade adjustments - so it's safe to say that "0" is the correct answer for trade duratin when `confirm_trade_entry()` is called.

As a side note:
All callbacks that are "trade-specific" contain the trade argument, unless they

**Comment by pine2023** [comment]
Then, it seems that the function I want to do is not suitable for confirm_trade_entry().

What would be my approach if I wanted to ensure that all trading slots had an equal number of longs and shorts?

(For example)
If the existing remaining positions are 2 longs, I want to ignore all new long signals until 2 shorts are filled.

**Comment by xmatthias** [comment]
`confirm_trade_entry()` is that function - but getting the actual trade object wouldn't help - as a trade object does not contain information about OTHER trades.

You can get infos about [other trades ](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-trades) in your callback.

**Comment by tomjrtsmith** [comment]
Someone, maybe @nilux, wrote this which tries to do the same thing but
didn't work, maybe bc of the trade object but maybe there is another way

def max_open_trades(self, pair: str, order_type: str, amount: float, rate:
float,
time_in_force: str, current_time: datetime, entry_tag: Optional[str],
side: str, **kwargs) -> bool:
open_trades = Trade.get_trades(trade_filter=Trade.is_open.is_(True))

total_shorts, total_longs = 0, 0
for trade in open_trades:
if trade.enter_tag == 'enter_short':
total_shorts += 1
elif trade.enter_tag == 'enter_long':
total_longs += 1

recent_shorts, recent_longs = 0, 0
for recent in open_trades:
if recent.enter_tag == 'enter_short' and current_time - timedelta(minutes=10)
< recent.open_date_utc:
recent_shorts += 1
elif trade.enter_tag == 'enter_long' and current_time - timedelta(minutes=10)
< recent.open_date_utc:
recent_longs += 1

# Limit 50% of max_open_trades by side
if side == "long" and total_longs >= (float(self.config['max_open_trades'])/
2):
print('ENTRY DENIED: Max number of LONG Position reached')
return False

if side == "short" and total_shorts >= (float(self.config['max_open_trades'
])/2):
print('ENTRY DENIED: Max number of SHORT positions reached')
return False
# Limit 25% of max_open_trades by interval (10min)
if side == "long" and recent_longs >= (float(self.config['max_open_trades'])
/4):
print('ENTRY DENIED: Max number of LONG positions per INTERVAL reached')
return False
if side == "short" and recent_shorts >= (float(self.config['max_open_trades'
])/4):
print('ENTRY DENIED: Max number of SHORT positions per INTERVAL reached')
return False
return True

**Comment by xmatthias** [comment]
using `Trade.get_trades` is discouraged - and will make sure it'll not work in backtesting (the above link contains the correct call).

Aside from that - you shouldn't rely on tags to determine the side of a trade - that'll easily break if you use more than 1 tag. `trade.is_short` is the correct way to go for that.

**Comment by pine2023** [comment]
Thanks for the reply.
I hope my code is the right approach
(fixed) It works

```python

def confirm_trade_entry(self, pair: str, order_type: str, amount: float, rate: float,
                        time_in_force: str, current_time: datetime, entry_tag: Optional[str],
                        side: str, **kwargs) -> bool:
    
    trades = Trade.get_trades_proxy(is_open=True)
    long_count = len([trade for trade in trades if not trade.is_short])
    short_count = len([trade for trade in trades if trade.is_short])
    long_short_diff = long_count - short_count

    if long_short_diff >= 0 and side == 'short':
        return True
    elif long_short_diff <= 0 and side == 'long':
        return True
    else:
        logger.info(f'{pair} - long_short_diff: {long_short_diff} | side: {side}')
        return False

```

**Comment by xmatthias** [comment]
it'll roughly be  correct - though i don't fully understand why you're limiting open trades to "opened within 2 days".

It's either an open short, or it isn't - independent of "opened 3 days ago" ... but i assume i'm not fully grasping the concept of what you aim to do.

**Comment by pine2023** [comment]
I didn't think `open_date` was optional. then i have to remove it
thanks

**Comment by xmatthias** [comment]
"everything" in that method is optional ... without parameter, you'll get all trades (open and closed, from whenever the bot was started).
