### ISSUE TITLE
Adjust leverage of an open trade

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#9012]
## Describe your environment
(if applicable)

  * Operating system: Linux mint Una
  * Python Version: Python3.10
  * CCXT version: 4.0.12
  * Freqtrade Version: freqtrade 2023.7.dev-f020daa35

## Describe the enhancement

Currently the leverage method has: pair: str, current_time: datetime, current_rate: float, proposed_leverage: float, max_leverage: float, entry_tag: Optional[str], side: str

I would like to have a high leverage for the first several hours of a trade then drop it to a lower value as time goes. Would it be possible to have the trade object as an argument on the leverage method so that I could do something like this:
```
if (current_time - trade.open_date_utc).total_seconds()/60.0 <= <some unit in seconds>:
            return <some value>
return 1
```

**Comment by xmatthias** [comment]
You can't adjust leverage (that's assumed to be static for the duration of the trade).

You can however reduce your trade amount with [`adjust_trade_position()`](https://www.freqtrade.io/en/latest/strategy-callbacks/#adjust-trade-position) - where you can buy for a high initial amount - and then reduce your investment after some time (or whenever you'd like).
Leverage will remain identical - but the effect is essentially the same - you're de-risking the trade by reducing your stake.

**Comment by moinonin** [comment]
Oh I see. Thank you @xmatthias
