### ISSUE TITLE
Create custom Pairlist in docker install option

### ISSUE THREAD

**Issue by BahmanBinary** [freqtrade/freqtrade#9015]
## Environment

  * Operating system: MacOS
  * Python Version: 3.11.4 (`python -V`)
  
## Question

Hi
I recently migrated to mac (M2) and according to doc I have to install Freqtrade with docker. But in docker installation option there is no folder structure for creating custom pairlist. How I can create custom pairlist in docker mode? How I can register pairlist in `constants.py` under the variable `AVAILABLE_PAIRLISTS`?

**Comment by stash86** [comment]
Build your own docker image

**Comment by xmatthias** [comment]
Pairlists and Filters are currently not designed to be "user overridable".

While there's a request for this in #4477 (hence this is a slight duplicate) - there's no immediate intend to enable this, as it would make pairlists / filters a public interface (which it currently is not) - which would imply that it's interface must be kept stable (or at least backwards compatible) - neihter of which we're currently assuming or guaranteeing (changes to either of these interfaces can be made at any time, without notice).

As such, work on Pairlists and Filters is considered as development on freqtrade itself (ideally with the intend of contributing these changes, assuming it works) not as part of "regular user activity". The regular docker configuration won't allow for this - and it's not designed for this, either.

The repository contains a devcontainer configuration for development with Docker (opening the repo in vscode should ask you about that, assuming docker is installed).

there's also nothing preventing you from installing locally (without docker) - but be prepared to have some troubles in some areas during installation, as M1 wheels are still not fully available for all dependencies (it's near impossible to get a CI environment with an M1/M2 processor for an open source project, so i can't blame anyone for not providing matching wheels).
