### ISSUE TITLE
deriving strategies with different interface versions

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#9018]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Version in container (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.7 stable (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I have just derived a strategy with interface version 2 from one with interface version 3, wondering positively, that the bot does not stop, neither displays any warning (like version mismatching) in the log.

I guess, that we can assume, the logic will work fine then?

 

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
i don't see any reason to use interface version 2 when developing a new strategy.

It's still available for now to not break existing strategies - but there is no guarantee for how long it will stay this way, and V2 should be considered as deprecated.

Combining versions in the same strategy is clearly discouraged, and effectively not supported, so potential problems cannot be excluded.
It MAY work - but it's neither something we support, ever tested for, nor can guarantee that it works or keeps working.

you therefore cannot assume anything. it can break either clearly, or in subtle ways, having slight misfunctionings.
the strategy comming out from this is not supported - failures are up to you to debug (please don't open  issues for problems you encounter with such a mixed strategy, saving us the time to close that as "not supported").

For strategies you develop currently, please stick to interface version 3.
There's also an [update command](https://www.freqtrade.io/en/latest/utils/#strategy-updater) which will assist you in updating your strategy.

**Comment by myNextCoder** [comment]
I absolutely understand. I won't ever develop a strategy in two different interface versions nowadays. In my case, I was adapting an old strategy to my needs, by linking it to a new part. According to your input, I will need to make a code refreshment within interface 2, to have full interface 3 code.
