### ISSUE TITLE
Any plans for timeframe less than 1 minute?

### ISSUE THREAD

**Issue by shawnli957** [freqtrade/freqtrade#9024]
## Describe your environment
(if applicable)

  * Operating system: _3.10.12_
  * Python Version: _4.0.26_
  * CCXT version: _4.0.26_ 
  * Freqtrade Version: _2023.6_ 

## Describe the enhancement
Hi, I found you do not support trade on timeframe less than 1 minute. Do you have any plans for this? Or can I use additional data in 1s frequency to provide supportive indicators for my by-minute strategy? Thanks.

**Comment by xmatthias** [comment]
There's no immediate plans to support sub 1m timeframes.

you can (probably) use that as informative pair (if your exchange supports that) - but freqtrade will not be able to supply you a new dataframe once per second, so you'll get a new dataframe every few seconds (not one for every candle).

It may have other issues - as this is not something we ever tested for / actively test for, and for many functions, the default assumption is "1m is the minimum".
This is something that can be worked on - but i currently have no plans / capacity to try and look at that in detail.

---

Aside from that, it's also an operational / timing problem.

The default cycle time for freqtrade is 5s (if the bot operation is faster than this, it'll sleep until the 5s are passed).

While you can configure this, it's unlikely that you'll get to <1s operations - not once you start having a few open orders / trades - which will each require requests to the exchange - which each can take a few milliseconds.

You'll also probably not be able to use a great deal of indicators - as every strategy that takes more than a few ms to do it's calculations will not be suited.

**Comment by froggleston** [comment]
Marking this as asked and answered.

**Comment by dexterhahaha** [comment]
@xmatthias If 1s TIMEFRAME is supported, which parts of the entire system need to be considered for compatibility? Can you give me a todolist? I will support it.

**Comment by xmatthias** [comment]
you can use 1s for --timeframe-detail and download-data - though i'd still not recommend it, as it's memory requirements are huge and downloads take forever (60x the time and space needed for 1m data).

for live - it's not supported - and i don't think it makes sense - either - if you think about it.

It'd only work on the assumption that the whole cycle can reliably complete in <1s (downloading candles, analyzing indicators, checking open orders, ...) - which i very strongly doubt (purely from the principle of rate-limits on the exchange).
The moment your process takes >0.9s - you'll encounter "late" entries (more than 1 candle late) - which i'd determine as not possible.


> Can you give me a todolist?

No i cannot - as i didn't look at what exactly would be missing.

>  I will support it.

You've never interacted with this repository before - please understand that we can't take the promise of "i'll support it" seriously without any prior history of contributing.

Supporting 1s timeframes for dry-run is not on the roadmap at this point.

**Comment by iceteapi** [comment]
how can i use timeframe = 1m , because timeframe_detail must < timeframe when backtesting... , but download data can't not get <1m data

**Comment by stash86** [comment]
make sure your exchange offers that timeframe. Not all exchanges offers that.
