### ISSUE TITLE
Profit factor

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#9026]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Version in container (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.7 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Getting the information with the telegram command /profit shows one line with the profit factor. According to the online documentation, I would get a number, as the factor.
In my case, I get: inf
Is this due to my individual configuration, probably because of unlimited stake, combined with enabled position adjustment?

(By the way: Max Drawdown in this table is permanently zero)

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by stash86** [comment]
inf means 0 loss so far

**Comment by myNextCoder** [comment]
Sounds good :)
