### ISSUE TITLE
How to minimize the loss introduced by stoploss

### ISSUE THREAD

**Issue by shawnli957** [freqtrade/freqtrade#9029]
* Operating system: _Windows11_
  * Python Version: __3.10.12___ 
  * CCXT version: _4.026_
  * Freqtrade Version: __2023.6__ 
  
## Your question
Hi, I understand stoploss is necessary for risk management. But I do bear a lot of loss from stoploss. My bot trades spot in a minute basis and currently my winning rate is 63% but I am bearing a negative profit since large negative profits introduced by one stoploss could offset many positive ones. I'm setting a static stoploss and trailing stoploss, and stoploss is usually trigger in two circumstances:
1. My bot enters long at a high point, then the price drops dramatically, which triggers stoploss.
2. The market maker shorts with huge capital, which leads to huge drawdown and triggers stoploss.

My points to reduce the loss from stoploss are:
1. Use a dynamic stoploss percentage, which could be accomplished by cutom_stoploss( )
2. Check dynamic profit and loss with high frequency, which is set by 'stoploss_on_exchange_interval'. I read from the doc 
> 'The bot cannot do these every 5 seconds (at each iteration), otherwise it would get banned by the exchange'. 
So I set it to 6 seconds. Is that possible I set a smaller number since it's crucial to monitor stoploss?
3. Hedging. Currently got no clues on how to hedge with freqtrade.

Any instructions for point 2 and 3 or any other ideas would be highly appreciated : )

**Comment by xmatthias** [comment]
the actual frequency won't matter - but if you have more than 1-2 trades open, very frequent order placements will usually result in API bans.
The actual amount of orders you can place per minute depends, but for stop orders, that's usually lower - and you'll not want to be in a trade you can't get out because your ip is temporarily banned due to too many stop replacement orders.

Your real problem with losses is not the winrate, but the profit/loss ratio.

you can win 63% - but if you win 2% - and then lose 10% on the stoploss - you'll need _more_ than 5 trades to actually make this one loss back.

**Comment by jackchalat** [comment]
You could try `custom_exit` to exit a position when certain conditions are met before reaching stop-loss. This will reduce your loss amount but will lower your win rate. 

Overall, it's more about the strategy though. At 1m timeframe, the price action are mostly random. You might want to use Informative Pair to get candles at 4h timeframe and determine the trend first. There are plenty of examples in the documentation.

**Comment by stash86** [comment]
Or you can improve your entry logic. No entry = no loss. People sometimes got trapped into optimizing the exits, while they forgot that they need to improve the entries as well. The two scenarios you mentioned above are perfect example of bad entries

**Comment by shawnli957** [comment]
@stash86 Totally agree. Thanks a lot.

**Comment by shawnli957** [comment]
@jackchalat Thanks for your advice. I will dig into the doc.

**Comment by froggleston** [comment]
As others seem to have given good answers, I feel we can close this one. As for point 3, hedging is not possible in freqtrade within a single strategy at present so this could be revisited at a later date.
