### ISSUE TITLE
How disable get rate for pair

### ISSUE THREAD

**Issue by CrazyBoy49z** [freqtrade/freqtrade#9031]
## Describe your environment

  * Operating system: Arch
  * Python Version: 3.11.3
  * CCXT version: 
  * Freqtrade Version: 2023.7
  
## Your question

How disable get rate for pair for unused pair?

2023-08-08 14:34:54 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2023.7', state='RUNNING'
2023-08-08 14:35:02 - freqtrade.rpc.rpc - WARNING - Could not get rate for pair LDBNB.
2023-08-08 14:35:02 - freqtrade.rpc.rpc - WARNING - Could not get rate for pair SPARTA.
2023-08-08 14:35:02 - freqtrade.rpc.rpc - WARNING - Could not get rate for pair LDHOT.
2023-08-08 14:35:02 - freqtrade.rpc.rpc - WARNING - Could not get rate for pair CYBER.
2023-08-08 14:35:02 - freqtrade.rpc.rpc - WARNING - Could not get rate for pair SEI.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
You don't - this will happen when freqtrade detects an asset it can't determine a rate for.
It's a warning and should be - if it impacts a pair you own, it's usually a sign that there's something wrong (most likely, the pair got delisted or the api is down).

From experience / prior issues, i know that "LD" pairs are in the earn section on binance... not sure about the others, but i assume it's similar, or you have some now delisted pairs in your account (or some random airdrop tokens).

**Comment by CrazyBoy49z** [comment]
> You don't - this will happen when freqtrade detects an asset it can't determine a rate for. It's a warning and should be - if it impacts a pair you own, it's usually a sign that there's something wrong (most likely, the pair got delisted or the api is down).
> 
> From experience / prior issues, i know that "LD" pairs are in the earn section on binance... not sure about the others, but i assume it's similar, or you have some now delisted pairs in your account (or some random airdrop tokens).

I know what the pairs are, but I want to disable them in the bot so that they are not constantly asked

**Comment by xmatthias** [comment]
You can't - it's part of the response from the exchange.
We can't really "disable" this without potentially also hiding important messages - as a "unknown pair" could also be a pair that the bot thinks it owns, but is really a delisted pair that's no longer available (handling of this will depend on the exchange).

best to use a dedicated subaccount for freqtrade if this is bothering you, one which is used by freqtrade exclusively, where this message should not appear.

**Comment by CrazyBoy49z** [comment]
Thanks

**Comment by xmatthias** [comment]
I've revisited this part of the code - and found that it's actually not necessary - so we'll be removing this message (in develop / the next release).
