### ISSUE TITLE
Getting the duration between trade open and max/min rate in backtest results

### ISSUE THREAD

**Issue by erhangunay** [freqtrade/freqtrade#9033]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: 3.11.4
  * CCXT version: 4.0.36
  * Freqtrade Version: 2023.7, Docker
  
## Your question

Hello there,

I am trying to analyze my trades based on their in-trade performance. Meaning I would like to analyze when (after how many bars) they have started profiting or the duration between trade.open_date_utc and the max/min rate.

My questions:
1) Is it possible to somehow add a new column on backtest results, giving the duration between trade open date and the max / min values?
2) Is it possible to somehow analyze how long did the trade stay in profit before closing on loss?

I know the data is calculated in the background however also have no idea if this is something simple to ask.. I started learning python thanks to you guys and any suggestion that would help me get these values would be much appreciated.

**Comment by xmatthias** [comment]
adding new columns is always possible _if it makes sense_.

for `min/max` rate - i'm not entirely sure if it does though.
You can pretty easily load the data and look for the next best low within your trade range ... which will be your "low".

`min/max rate` is however pretty misleading - as it's simply the lowest price observed.
if you're using [position adjustments - `adjust_trade_position()`](https://www.freqtrade.io/en/latest/strategy-callbacks/#adjust-trade-position) - then the minimum rate is actually irrelevant / misleading (obviously if you don't - then this value is as good as any).

assuming your strategy does multiple position adjustments per trade - it'll be worthless to know "entry rate 100, lowest rate 90" on a 100$ initial entry - as the 90 could mean a loss of 10$ (10%) - or a loss of 2$ - if you did multiple adjustments - maybe some taking profits at 110$).

this won't mean the trade was down by 10% (in value) at any point in time - only that the price of the asset declined by this much.

While you can calculate the trade size at that point in time - the only think you'll discover is that "this wasn't my low point" - but the info of "in total, my trade was down 50$ at some other point in time" will not be contained.

---

A potentially more useful metric might be to capture absolute win/loss (-10$, +15$) in combination with the time of this event happening - as that will also include the information of position size at that moment (it's irrelevant if your lowest point was at 90$ - but it's useful to know "my trade was down by 20$ of my initial stake).

I did think about this for a bit in the past - but never really found the time to actually implement this.

---

regarding 2 - my suggestion would be to look at the data on a chart (freqUI can do backtesting, incl. charting) - which will give you a (visual) overview of this.
You can probably also use pandas for this (basically draw a straight line from the trade open towards when it crosses below) - but i doubt you'll be able to reliably automate this (at least not without severely overfitting your strategy), as a trade can flick between profit and loss several times a minute (if it's walking across this "break even" line).

**Comment by erhangunay** [comment]
Hello Matthias, 

Thank you very much for taking the time replying and your insightful suggestions.

Let me explain the purpose why I am asking for such a data and maybe you will have a better perspective of achieving what I am trying to do.

Currently I have built a strategy that uses 12H TF on the whole market with 40 open trades. I have pulled out the trades and put them on powerbi to analyze and while doing that I have noticed more than 50% of my trades have reached at least 4% profit. I have also analyzed all the Runup values (meaning the top profit moment of a trade (ex. if its long highest high / open_rate) and created my self a table of values which I will use as threshold.

Finally, my purpose is to do something similar to roi however in my version, I would like to close trades which are under a certain profit (based on the thresholds i have calculated previously). So lets say %50 of trades have %3 run-up. I want to say after X minutes, if the current_profit is lower than 3%, close the trade. Assuming that it will be better than closing on loss. 

Tricky part here is not to put it too early, therefor I want to analyze all the trades from the beginning 2019 until now to get a huge dataset and base my assumptions on statistics.

Do you have any suggestions on how to do this manually? (since the timerange is too high and the possibilities are too much, hyperopt is not a good option at least until having good filters to begin with)

**Comment by xmatthias** [comment]
honestly - you're working on 12h timeframes - time range will not be a problem, really - as you'll only have 700 candles per pair per year.

As mentioned above, based on the assumption of "no adjustments" - simply using the candle data will work (most likely, assumes the use of python though) - as the "next low" after the open that == min_rate will be your lowest point.

**Comment by erhangunay** [comment]
I am actually using 12h decorative on 1h timeframe to get more accurate results on the hourly changes. I noticed that having several backtests using roi gives the exact bar for each trade that covers the profit threshold.

Thank you for your time.
