### ISSUE TITLE
Bybit error

### ISSUE THREAD

**Issue by polyvios-bc** [freqtrade/freqtrade#9035]
## Describe your environment

  * Operating system: debian 12
  * Python Version: 3.9
  * CCXT version: 4.0.36
  * Freqtrade Version:  2023.7
  
## Your question

We are seeing this error suddenly on some Bybit bots that are using the new api v5. Is this expected?

s1_a1    | 2023-08-12 01:39:48,525 - freqtrade.exchange.exchange - INFO - Using CCXT 4.0.36
s1_a1    | 2023-08-12 01:39:48,533 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
s1_a1    | 2023-08-12 01:39:48,547 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
s1_a1    | 2023-08-12 01:39:48,562 - freqtrade.exchange.exchange - INFO - Using Exchange "Bybit"
s1_a1    | 2023-08-12 01:39:49,455 - freqtrade.exchange.exchange - INFO - Using cached leverage_tiers.
s1_a1    | 2023-08-12 01:39:49,463 - freqtrade.exchange.exchange - INFO - Done initializing 236 markets.
s1_a1    | 2023-08-12 01:39:49,538 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Bybit'...
s1_a1    | 2023-08-12 01:39:49,852 - freqtrade.commands.trade_commands - ERROR - list index out of range
s1_a1    | 2023-08-12 01:39:49,860 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
s1_a1    | Traceback (most recent call last):
s1_a1    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
s1_a1    |     worker = Worker(args)
s1_a1    |              ^^^^^^^^^^^^
s1_a1    |   File "/freqtrade/freqtrade/worker.py", line 37, in __init__
s1_a1    |     self._init(False)
s1_a1    |   File "/freqtrade/freqtrade/worker.py", line 53, in _init
s1_a1    |     self.freqtrade = FreqtradeBot(self._config)
s1_a1    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
s1_a1    |   File "/freqtrade/freqtrade/freqtradebot.py", line 81, in __init__
s1_a1    |     self.wallets = Wallets(self.config, self.exchange)
s1_a1    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
s1_a1    |   File "/freqtrade/freqtrade/wallets.py", line 47, in __init__
s1_a1    |     self.update()
s1_a1    |   File "/freqtrade/freqtrade/wallets.py", line 177, in update
s1_a1    |     self._update_live()
s1_a1    |   File "/freqtrade/freqtrade/wallets.py", line 145, in _update_live
s1_a1    |     positions = self._exchange.fetch_positions()
s1_a1    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
s1_a1    |   File "/freqtrade/freqtrade/exchange/common.py", line 167, in wrapper
s1_a1    |     return f(*args, **kwargs)
s1_a1    |            ^^^^^^^^^^^^^^^^^^
s1_a1    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 1424, in fetch_positions
s1_a1    |     positions: List[Dict] = self._api.fetch_positions(symbols)
s1_a1    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
s1_a1    |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/bybit.py", line 6896, in fetch_positions
s1_a1    |     return self.fetch_unified_positions(symbols, params)
s1_a1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
s1_a1    |   File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/bybit.py", line 6666, in fetch_unified_positions
s1_a1    |     market = self.market(symbols[0])
s1_a1    |                          ~~~~~~~^^^
s1_a1    | IndexError: list index out of range

**Comment by xmatthias** [comment]
Blaming v5 is certainly wrong considering ccxt has been using the v5 API all of 2023.

your "real" problem is the use of an unified account (or unified subaccount), which freqtrade does not support (and never did).
there's a simple workaround for this on the [bybit section of the exchange notes documentation page](https://www.freqtrade.io/en/latest/exchanges/#bybit)  - which essentially comes down to "use a subaccount".

---

Now this is certainly a bug in ccxt - and i'd welcome if you could report it there (i can't reproduce it as my account is not unified).

You can use the following snippet for reproduction (don't put your real keys anywhere on github).

``` python
import ccxt
exchange = ccxt.bybit({
    'apiKey': '<yourApiKey>', 
    'secret': '<yoursecret>', 
    'options': {'defaultType': 'swap'} 
    })
res = exchange.fetch_positions([])
print(res)
```

This has been broken before for other exchanges(https://github.com/ccxt/ccxt/issues/15468) - and is a side-effect of the JS transpile - which will hide the difference between an empty list and None.


**edit** nevermind - https://github.com/ccxt/ccxt/issues/18869
