### ISSUE TITLE
Why immediate re-enter after stoploss?

### ISSUE THREAD

**Issue by le8888e** [freqtrade/freqtrade#9036]
## Describe your environment

  * Operating system: __Linux__
  * Python Version: __3.9.16__ 
  * CCXT version: _3.0.37__ 
  * Freqtrade Version: _2023.3_
 
## Your question
Hi, I found there would be an entry right after a stoploss or trailing stoploss order closed, which may cause consecutive stoploss when the market didn't go your way. So I tried to manually lock the pair when there were closed orders within 3 minutes (my timeframe is 1m) whose exit reasons are stoploss or trailing stoploss. But the lock seemed don't work. Here is a sinppet of my 
populate_entry_trend() code:

    

 ```
def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
         """
         Based on TA indicators, populates the entry signal for the given dataframe
         :param dataframe: DataFrame
         :param metadata: Additional information, like the currently traded pair
         :return: DataFrame with entry columns populated
         """
         trades = Trade.get_trades_proxy(pair=metadata['pair'], is_open=False, open_date=datetime.now(timezone.utc) - timedelta(minutes=3))
         if trades != []:
             for trade in trades:
                 if trade.exit_reason in ['stop_loss', 'trailing_stop_loss']:
                     if not self.is_pair_locked(metadata['pair']):
                         self.lock_pair(metadata['pair'], until=datetime.now(timezone.utc) + timedelta(minutes=3))
                         break
                     
         if not self.is_pair_locked(metadata['pair']):
             dataframe.loc[
                 (
                     (dataframe['-di'] < 20) &
                     (dataframe['+di'] > dataframe['-di'])) |
                     (dataframe['rsi6'] < 8.1)
                 ),
                 'enter_long'] = 1      
         else:
             dataframe['enter_long'] = 0
         return dataframe
```

Could you please explain why there would be imdediate re-enters and see why my lock didn't work? Thanks a lot.

**Comment by xmatthias** [comment]
Freqtrade offers a feature called protections for this - [one of which](https://www.freqtrade.io/en/latest/plugins/#stoploss-guard) is exactly for this scenario - and which is the recommended way for this.


Your protection probably doesn't work because your 3m filter is on "open" - so you'll only get trades that opened (and stopped) within the last 3 minutes. Whenever you got a trade duration of more than 3 minutes, `trades` will be closed.

**Comment by le8888e** [comment]
Yeah I do wanna look back trades that opened within 3 minutes and check if they are closed due to stoploss or trailing stoploss, but it didn't work as you see in the pic below
![图片](https://github.com/freqtrade/freqtrade/assets/34771253/3323b51e-1e9a-485a-ac35-d5cabf80fe25)

**Comment by xmatthias** [comment]
your stoploss is WAY too tight (once you account for fees).
but that's up to everyone to actually determine.

**Comment by stash86** [comment]
The issue is that it re-enter 2 secs after exiting last trade, which is weird because by default, FT will autolock that pair for that candle.

Do you have any code in the strategy that unlock a pair manually?

**Comment by le8888e** [comment]
@stash86  Yeah, I do manually disable auto lock. Will the re-enter call populate_entry_trend() first so that I could lock the pair by some code like below?
```
def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        trades = Trade.get_trades_proxy(pair=metadata['pair'], is_open=False, open_date=datetime.now(timezone.utc) - timedelta(minutes=3))
        if trades != []:
            for trade in trades:
                if trade.exit_reason in ['stop_loss', 'trailing_stop_loss']:
                    dataframe['enter_long'] = 0
        else:
            dataframe[......, 'enter_long'] = 1
        return dataframe
```

**Comment by stash86** [comment]
and where do you put the code to unlock? bot_loop_start?

**Comment by le8888e** [comment]
I modified the auto lock related code in freqtrade/freqtradebot.py and freqtrade/rpc/rpc.py

**Comment by xmatthias** [comment]
Please understand that we're not able to assist you with modified freqtrade installations.

Maybe the problem you're encountering is due to the changes you made, which are now completely ignoring all locks (we're unaware what changes you made).

we'll therefore not be able to support you in this, unless you're using a non-modified version (which will NOT show this behavior, as the auto-lock is there to prevent exactly THIS problem).
thanks for your understanding.

**Comment by stash86** [comment]
And if you use `process_new_candle` to true and you don't set `ignore_buying_expired_candle_after` in your config, then the current behavior is correct.

The bot exited the trade. Autolock being set. Your new code now unlock it. The bot is still on "old" candle, so your populate entry won't be checked yet. The bot look at the dataframe, and the last row's enter_long is 1, so it re-enter the trade.

**Comment by stash86** [comment]
My advice, instead of remove the autolock and do the lock manually, why not keep the autolock and unlock the pair manually? Better performance (no quick re-entry like what you get now), and you can still control the lock/unlock with your conditions

**Comment by le8888e** [comment]
@stash86 So for my re-enter, the bot read the cached 'old' candle instead of call populate_entry_trend() to 're-generate' last candle?

**Comment by froggleston** [comment]
@le8888e Please read the docs section on bot loop logic to understand when populate_entry_trend is called: https://www.freqtrade.io/en/stable/bot-basics/#bot-execution-logic

It's not an "old" candle, but simply the most recent closed candle. There's no "regeneration" possible until the next candle is called from the exchange.

And as others have said, you're running your own modified freqtrade version so our support will be limited, if at all.

**Comment by shawnli957** [comment]
@froggleston Yeah, I totally understand. The thing is, populate_entry_trend() is not called every internals.process_throttle_secs (5 seconds by default) as stated in the docs, but called every timeframe (1m in my case). So I cannot manually lock or unlock pair in populate_entry_trend() within one timeframe.

**Comment by xmatthias** [comment]
`process_only_new_candles` controls this. Please read the documentation - which is there to actually explain such things.

calling `populatep_*` every iteration is pointless in almost all cases - as the indicators won't change if the candle didn't change - and is therefore a waste of time/resources.

**Comment by shawnli957** [comment]
@xmatthias Now I see, thanks a lot.
