### ISSUE TITLE
Configuration Validation Error with Custom Stoploss Strategy

### ISSUE THREAD

**Issue by Johan1974** [freqtrade/freqtrade#9038]
Hello Freqtrade Support Team,

I hope this message finds you well. I am currently facing an issue related to configuration validation when using a custom stoploss strategy in Freqtrade. I am seeking assistance in resolving this issue.

**Problem Description**:

I have set up a custom stoploss strategy that I would like to use with Freqtrade. The strategy has been implemented following the guidelines provided in the official Freqtrade documentation. The intention is to use a custom stoploss logic that triggers based on certain profit conditions.

However, despite following the documentation and ensuring that the strategy is correctly structured, I am encountering a validation error when running Freqtrade. The error message I am receiving is:

```
Invalid configuration. Reason: 'stoploss' is a required property
```

This error occurs even when I comment out or remove the standard stoploss logic in the strategy class and attempt to rely solely on the custom stoploss logic.

**Configuration and Setup:**

Here are the relevant details of my setup:

**Docker Compose configuration**: 

```
---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: ${BOTNAME}
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "/home/freggle/strategies:/freqtrade/user_data/strategies"
      - "/etc/localtime:/etc/localtime:ro"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "${PORTS}"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:///user_data/${DATABASE_FILE}
      --config /freqtrade/user_data/config.json
      --strategy ${STRATEGY}

```

**Custom strategy class:**

```
# --- Do not remove these libs ---
from freqtrade.strategy import IStrategy
from pandas import DataFrame
import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib


class CustomStrategy(IStrategy):

    # Set strategy parameters
    timeframe = '5m'  # The timeframe for the strategy
    trailing_stop = True  # Use trailing stop
    trailing_stop_positive = 0.01  # Trailing stop positive threshold (1% profit)
    trailing_stop_positive_offset = 0.02  # Trailing stop positive offset (should be greater)
    trailing_only_offset_is_reached = False  # Trail the stop-loss as soon as positive threshold is reached
    use_custom_stoploss = True

    # Define the indicators
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['sma_fast'] = ta.SMA(dataframe['close'], timeperiod=10)
        dataframe['sma_slow'] = ta.SMA(dataframe['close'], timeperiod=30)
        dataframe['ema_fast'] = ta.EMA(dataframe['close'], timeperiod=10)
        dataframe['rsi'] = ta.RSI(dataframe['close'], timeperiod=14)
        macd = ta.MACD(dataframe['close'], fastperiod=12, slowperiod=26, signalperiod=9)
        dataframe['macd'] = macd['macd']
        dataframe['macd_signal'] = macd['signal']
        return dataframe

    # Define the buy signal using custom stoploss logic
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        conditions = (
            (dataframe['sma_fast'] > dataframe['sma_slow']) &
            (dataframe['ema_fast'] > dataframe['sma_fast']) &
            (dataframe['rsi'] < 30) &
            (dataframe['macd'] > dataframe['macd_signal']) &
            (dataframe['custom_stoploss'] > 0)  # Activate buy signal when custom stoploss is active
        )
        dataframe.loc[conditions, 'buy'] = 1
        return dataframe

    # Define the sell signal
    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Define your sell conditions here
        return dataframe

    # Define custom stoploss logic
    #def custom_stoploss(self, pair: str, trade: 'Trade', current_time: #float, current_rate: float, current_profit: float, **kwargs) -> float:
    #    if current_profit > 0.06:
    #        return 0.06  # Activate stoploss at 6% profit
    #    return 0.0  # No stoploss

```

**Steps Taken:**

I have taken the following steps in an attempt to resolve the issue:

Commented out the standard stoploss logic in the strategy class.
Ensured that the class path in the config.json file is correct.
Verified that the Docker volume mappings are accurate and strategies are accessible.
Restarted Docker containers to refresh any cached data.

**Request for Assistance:**

I kindly request your assistance in identifying the root cause of this issue and providing guidance on how to resolve it. I have reviewed the documentation and community resources but have been unable to find a solution that works for my specific case.

If you need any further information or code snippets, please let me know, and I'll be more than happy to provide them. Your support in resolving this matter is greatly appreciated.

Thank you for your time and assistance.

Best regards,

Johan

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

If you very carefully read through the [custom stop](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stoploss) documentation, you'll find that it mentions the following:

> The traditional stoploss value serves as an absolute lower level and will be instated as the initial stoploss (before this method is called for the first time for a trade), and is still mandatory.

The error is pointing out exactly this - static stoploss is not set (neither in config, nor in the strategy).

**Comment by Johan1974** [comment]
I thnk i foud it at the end and could solve it , thanks

**Comment by zaradine** [comment]
Hello Johan1974, what solution did you find? I am having a similar problem.
