### ISSUE TITLE
freqtrade.strategy.strategy_wrapper - ERROR - Unexpected error 'buy' calling 

### ISSUE THREAD

**Issue by Johan1974** [freqtrade/freqtrade#9040]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: Python 3.8.10
  * CCXT version: ccxt 1.57.38
  * Freqtrade Version: Freqtrade 1.3.0

## Your question

I'm encountering an issue while implementing a trading strategy using Freqtrade. I have created a custom trading strategy using machine learning indicators, and I'm facing an unexpected error during the strategy execution.

The strategy involves training a RandomForestClassifier model on historical data and using its predictions to determine buy signals. The `populate_buy_trend` function seems to be working correctly, as I can log the predictions and verify them against the historical data.

However, when I try to implement the `populate_sell_trend` function, I encounter unexpected errors related to the 'buy' column not being found in the DataFrame. I have already confirmed that the 'buy' column is present and correctly populated in the DataFrame.

I have implemented logging to track the values of the 'buy' column, 'close' column, and the 'sell' column before and after the `np.where` condition. Interestingly, the 'buy' and 'close' columns appear to be populated correctly, but the 'sell' column still triggers the error.

I'm seeking assistance in understanding why this error is occurring and how I can successfully implement the `populate_sell_trend` function. Are there any specific considerations when using the 'buy' column in this context?

Thank you for your support and guidance.

Johan

**Comment by stash86** [comment]
Why not update your freqtrade to latest, and use V3 interface? We won't (and can't) help you debug errors on old FT.

**Comment by xmatthias** [comment]
on top of that - it's just a description, but doesn't contain the actual error / stacktrace. Without that, it's pretty difficult to help other than "look at other examples and determine where your strategy differs from the working examples".

**Comment by Johan1974** [comment]
Found the issue allready, thanks!
