### ISSUE TITLE
Backtest of other currencies

### ISSUE THREAD

**Issue by ahmad-develop** [freqtrade/freqtrade#9041]
*Operating system: Ubuntu 22.04
*Python Version: Python 3.8.10
*CCXT version: ccxt 1.57.38
*Freqtrade Version: Freqtrade 1.3.0

Hello, first I want to say that thank you very much for your good library and I know it is made for crypto currencies.

I need to backtest a forex currency.

I download the data of one of the crypto currencies with freqtrade, then I change the data in the file with Jason's data of another currency, but the data is not loaded during the backtest.

Can this be done? Do you have a better idea?

Thanks .

**Comment by stash86** [comment]
First of all, this is the second time I saw someone use FT 1.3.0. Can I know where you got such old version?

To answer your question, it would take more than just changing the data. You would need to change the internal codes. I heard someone has done it, so it's possible. But we won't help you for that.
