### ISSUE TITLE
Technical Writer MetAISmith 

### ISSUE THREAD

**Issue by MetAISmith** [freqtrade/freqtrade#9042]
> 

> 

## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

MetAISmith:bazelvers-1
## Describe the enhancement

*Explain the enhancement you would like*

**Comment by stash86** [comment]
Closing this as this has no content at all
