### ISSUE TITLE
Getting Cumulative Equity & Applying BBands on it in the background for other calculations

### ISSUE THREAD

**Issue by erhangunay** [freqtrade/freqtrade#9058]
## Describe your environment

  * Operating system: Windows 11
  * Python Version:3.11.4
  * CCXT version: 4.0.36
  * Freqtrade Version: 2023.7, Docker
  
## Your question

Hello guys,

I would like to create the bollinger bands of my cumulative equity in the background. The logic is, whenever my equity line crosses the upper boundary of the BBands, I would like to use 2x leverage and whenever it crosses lowerband below, i would like to return back to 1x leverage. 

Below is the visual of what I am trying to do. I do not need any visuals, infact I just need to know whether if its possible to get the cumulative equity based on trade index and use it as data source for calculating BBands.

![image](https://github.com/freqtrade/freqtrade/assets/17651818/3bc0b387-19ea-453e-bb9e-d9b8682ae8cb)

**Comment by xmatthias** [comment]
You can calculate bollinger bands in multiple ways, for example like this:

```
        bollinger = ta.BBANDS(dataframe, nbdevup=2.0, nbdevdn=2.0)
        dataframe['bb_lowerband'] = bollinger['lowerband']
        dataframe['bb_middleband'] = bollinger['middleband']
        dataframe['bb_upperband'] = bollinger['upperband']
```

It's not quite clear to me what you mean with "cumulative equity" - therefore i'll ignore that part for now.

**Comment by erhangunay** [comment]
Yes if we ignore the cumulative part, just the bbands of the equity :)

Maybe i was unclear..

**Comment by xmatthias** [comment]
You can get the equity at the current point in the strategy - but not over time.

if you carefully look at the [execution logic](https://www.freqtrade.io/en/stable/bot-basics/#bot-execution-logic) - you'll see  that it's actually impossible to get that in populate methods during backtesting - so it can't be an indicator you can "just use".

**Comment by erhangunay** [comment]
Would you have any suggestions on how to do it in a different way? Maybe a workaround? A list that can be filled each time a trade closes and creating a bb on that list? Any suggestions are much much appreciated but if there are none i shall close this question

**Comment by xmatthias** [comment]
assuming you want backtestability, you'll have to work in callbacks only (popuate_* methods will not know of ANY prior trade).

with that, you can probably get all trades - and aggregate their profits / losses over time - adding (and ffilling) that onto a date spine.
There'll be no real suggestions "in code" though - as that's all pretty unreliable, and will break in live the moment you touch assets on exchange.

**Comment by erhangunay** [comment]
okay then, thank you for your time
