### ISSUE TITLE
liquidation ratio

### ISSUE THREAD

**Issue by wfh958631772** [freqtrade/freqtrade#9059]
## Describe your environment

  * Operating system: _mac  m1_
  * Python Version: __3.10___ (`python -V`)
  * CCXT version: 4.0.36 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.7 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
May I ask how to adjust the liquidation ratio?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
you don't. 
the actual liquidation rate is defined by the exchange's formula, or in live, by the exchange providing it directly.

what you can modify (but shouldn't) is the [liquidation buffer](https://www.freqtrade.io/en/stable/leverage/#understand-liquidation_buffer).

**Comment by wfh958631772** [comment]
close order rate？ or How to modify close order percent @xmatthias

**Comment by xmatthias** [comment]
i'll assume that you talk about [custom pricing](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-order-price-rules). 

In general, this sounds like questions that can easily be answered by reading through the docs, which i'd strongly suggest you do.

**Comment by stash86** [comment]
Seeing no more comment, I assume your question has been answered. Closing this for now. Please re-open this if your question above hasn't fully been answered, or open new issue if you have different question.
