### ISSUE TITLE
API mode in containers

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#9060]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Version of below Freqtrade container (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.7 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I used to run Freqtrade with API mode under Minicoda, where I just have set for example IP 192.168.100.1 with port 12345 in config file. Opening the Windows Server port was enough, to access the Freqtrade website on any PC in the LAN.
Doing this with containers, I am prompted to use the loopback address, and the bot stops.
According to the online manual, it seems, that we might can vary with the port, but I do not see an example with 192.168.xxx.xxx
Is this due to your ready to use containers, which I have pulled, and do I need to open specific ports of the container?
In fact, opening a Windows Server port does not make the website accessible on my LAN, running the container.
(I won't have any security issue, since the website will only be visible from inside my Active Directory Domain)

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Quite honestly - we have a section for exactly this type of configuration [in the docs](https://www.freqtrade.io/en/latest/rest-api/#configuration-with-docker).

the configuration will always use 0.0.0.0 (you can't reliably predict the internal port - unless you have a non-default docker installation).
you may use 192.168.x.x in your docker port mapping - but that's up to you - and really a docker networking topic.

**Comment by myNextCoder** [comment]
Great, the link with this content will certainly help me, I thank you.
