### ISSUE TITLE
Different timeframe and context

### ISSUE THREAD

**Issue by rkumaroutlook** [freqtrade/freqtrade#9063]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.11.4 (`python -V`)
  * CCXT version: 3.1.44 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.6 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

While i found the details about informative pairs to get the calculation done for a different timeframe, i couldn't find any document which tells how to get the context also changed. 

For example: see below
// This calculates a 10-period moving average on the active chart.
sma = ta.sma(close, 10)
// This sends the `sma` calculation for execution in the context of the "AAPL" symbol at a "240" (4 hours) timeframe.
aaplSma = request.security("AAPL", "240", sma)

Issue i am facing is, i am able to calculate the SMA for 4 hour timeframe using "informative pairs" but i am unable to send the "SMA" value for the strategy timeframe as the input to it as informative pairs cannot read the SMA from other functions. Please help (also, please excuse me if this is a dumb question)

**Comment by xmatthias** [comment]
Quite honestly - your question doesn't really make sense / doesn't seem to be related to freqtrade.

the code snippets are not freqtrade compatible code - so are you sure you're actually working on a freqtrade strategy?

**Comment by stash86** [comment]
You are giving us pinescript code

**Comment by stash86** [comment]
And if I understand your question correctly, seems like you want to do "advance" informative. You want to calculate main timeframe SMA first, then use that value on 4h timeframe calculation. In that case, read my blog post, and look at the second example, where you have more flexibility

https://botacademy.ddns.net/2023/07/14/how-to-define-informative-timeframes/

**Comment by rkumaroutlook** [comment]
> And if I understand your question correctly, seems like you want to do "advance" informative. You want to calculate main timeframe SMA first, then use that value on 4h timeframe calculation. In that case, read my blog post, and look at the second example, where you have more flexibility
> 
> https://botacademy.ddns.net/2023/07/14/how-to-define-informative-timeframes/

@stash86, This is exactly what i was looking for. Thank you so much for your help. I've been banging my head on this for the last one week!!!

**Comment by rkumaroutlook** [comment]
> Quite honestly - your question doesn't really make sense / doesn't seem to be related to freqtrade.
> 
> the code snippets are not freqtrade compatible code - so are you sure you're actually working on a freqtrade strategy?

@xmatthias - My apologies for creating the confusion. I should have mentioned in my question that it was Pinescript code. I got my issue resolved with the help of @stash86 blog link.
