### ISSUE TITLE
'buy' and 'sell' of spaces for short trades in HyperOpt

### ISSUE THREAD

**Issue by pine2023** [freqtrade/freqtrade#9067]
## Describe your environment

  * Operating system: Linux
  * Freqtrade Version: 2023.8.dev-ba34318f7

## Your question

Do `buy` and `sell` behave like `entry` and `exit` for all trade directions?
Or should I write `sell` to `buy` for short trades?
Or if I'm going to do `--spaces=all` it has nothing to do with where I write it?

If I don't want the difference between long and short results, is there a space like `both` for both directions?

```python
        # duplicated case

        for val in self.long_ema1.range:
            dataframe[f'long_ema1_{val}'] = ta.EMA(dataframe, timeperiod=val)
        for val in self.long_ema2.range:
            dataframe[f'long_ema2_{val}'] = ta.EMA(dataframe, timeperiod=val)
        for val in self.long_ema3.range:
            dataframe[f'long_ema3_{val}'] = ta.EMA(dataframe, timeperiod=val)

        for val in self.short_ema1.range:
            dataframe[f'short_ema1_{val}'] = ta.EMA(dataframe, timeperiod=val)
        for val in self.short_ema2.range:
            dataframe[f'short_ema2_{val}'] = ta.EMA(dataframe, timeperiod=val)
        for val in self.short_ema3.range:
            dataframe[f'short_ema3_{val}'] = ta.EMA(dataframe, timeperiod=val)
```

**Comment by stash86** [comment]
They are just label. You can use buy (or sell) for all if you want to. In your case, it doesn't matter whether you are using buy or sell

**Comment by pine2023** [comment]
It's resolved. Thank you.
