### ISSUE TITLE
How to run "cross pair" analysis?

### ISSUE THREAD

**Issue by yohplala** [freqtrade/freqtrade#9069]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: 3.10 (`python -V`)
  * CCXT version: 4.0 (`pip freeze | grep ccxt`)
  * Freqtrade Version: dev (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Please, I would like details on how is organized the freqtrade loop.
It is introduced in the doc here
https://www.freqtrade.io/en/stable/bot-basics/

Please in which python file can i find it?

What i am looking to understand is:
- within a freqtrade iteration (every ~5s as per the doc)
- there is an inner loop over the pairs. For each pair are called populate_* methods

Then: 
- are the other methods called in this same nested loop (per pair)?
- or are they called only once populate_* methods have been run for all pairs first?

I am interested in the second option.

I would like a way to confirm or not an entry or an exit for a given pair, depending indicators' values of all other traded pairs
So i need the loop with the populate_* methods to be run for all pairs, before the next methods are called.
confirm_trade_exit / confirm_trade_entry

Thanks for your help!

**Comment by stash86** [comment]
each pairs are independent of others. Those steps you mentioned above are being run from first pair in whitelist to the last in order. You can't do what you want to do by default. You would need to modify freqtrade source code if you want it to work like that

**Comment by yohplala** [comment]
Thanks for the quick reply @stash86 !
Please, for me to investigate further, could you point me in which source this loop over pairs is run?

Thanks for your help!

**Comment by xmatthias** [comment]
please note that "dev" is not a proper freqtrade version - for actual problems, this will not be an acceptable version definition.
For this question it's probably fine - but please keep this in mind for the future.

---

You can look at other pairs analysis by either using [informative pairs](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs) - or by using the [dataprovider](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-dataprovider).

---

The code itself is open source - but to actually modify what you intend to, there's some level of python dev experience necessary - as it's not just "ask chatgpt to modify some lines".

All this really means is that you need to put in the work to learn how things work and are tied together - not that it's impossible or requires some special knowledge.
We could tell you the exact line - but you'll neither learn something through that - nor will you gain any experience in the freqtrade codebase by that - and as a consequence of that "not knowing" - break things you don't intend to.

Please note that we will **not** support your custom, modified version.

**Comment by yohplala** [comment]
Hi @xmatthias , thank you for your feedback!
Yes I confirm I am a complete newbie to ferqtrade, and I need to deep dive in its code. Being first interested in the understanding of this loop, I thought requesting a pointer would get me faster to it, but I do understand your comment.
I guess I can close the ticket.
I am sorry for the bother.
Bests,
