### ISSUE TITLE
shutdown should cancel open orders

### ISSUE THREAD

**Issue by xmatthias** [freqtrade/freqtrade#907]
## Proposal

When stopping the bot (via ctrl+c, `/stop`) open orders are kept open and will be filled by the exchange "whenever" the market is ready to.
This can be dangerous should the bot be stopped due to a sudden market crash

A proper shutdown should allow the following (configurable!):

- [ ] cancel unfilled open orders
- [ ] force-close all open orders

Comments, suggestions, Pullrequests in this regard are welcome :wink:

**Comment by ZeroCool940711** [comment]
I recommend this to be added to the config file as an option that can be toggle on or off according to what people need.

**Comment by jpribyl** [comment]
Just opened this - https://github.com/freqtrade/freqtrade/pull/3210

I did not add a config option yet - that should be very straightforward to work in after merging this!

**Comment by hroff-1902** [comment]
I also thought of this functionality, should be handy and useful...

* it should use cancel_all() method of ccxt, if it's implemented for the exchange (not sure without looking at the ccxt manual if it's a part of ccxt generalized interface, but many (some) exchanges provide this in their API). This exchange API call 
* it should be accompanied by closing open positions
* it should be configurable (with current behavior, no cancel orders and no closing positions, by default) -- so something like `on_exit = cancel_orders | closing_positions | keep_orders_and_positions`
* it should work even if the process dies by exception, i.e. be called at the exception handler before destroying the exchange object. Sometimes it will fail (in case of network errors, for example), but usually it will be able to cancel orders properly.

**Comment by jpribyl** [comment]
@hroff-1902 Thanks for the fast reply! I am not very familiar with the `ccxt` api but I will read into it and plan to rework my PR as soon as I have time.

It makes sense that we would not change the default behavior, I like the naming / options you suggested. Seems like we will need to update the docs to include this as well?

Good call on putting it at the exception handler. I did not think to do that!

**Comment by hroff-1902** [comment]
> @hroff-1902 Thanks for the fast reply! I am not very familiar with the `ccxt` api but I will read into it and plan to rework my PR as soon as I have time.

Should be assessed first. I do not actually remember if the really have `cancel_all()`

**Comment by xmatthias** [comment]
i disagree on using `cancel_all()` - irrelevant if the exchange supports it or not.

Using it will cancel ALL orders - also orders the bot did not open - which is wrong (assume i use the bot to trade USDT - but i do manual trading against ETH).

The bot should NEVER touch orders it did not open.

**Comment by hroff-1902** [comment]
Agree

**Comment by ArthurArias** [comment]
i'm using client.futures_cancel_all_open_orders(symbol="BTCUSDT",recvWindow=2000) on Binance, but the operation not closed, the massege it's was {'code': 200, 'msg': 'The operation of cancel all open order is done.'}. I don't know how  to solved, any recommendation?

**Comment by xmatthias** [comment]
@ArthurArias this is clearly not related to freqtrade, so we will not be able to help you with this.
