### ISSUE TITLE
deep analysis for every trade made by bot during backtesting

### ISSUE THREAD

**Issue by S-shekharDuggal** [freqtrade/freqtrade#9070]
## Describe your environment

  * Operating system: windows 10
  * Python Version: 3.11.4
  * CCXT version: 4.0.34
  * Freqtrade Version: current
  
i build this strategy with freqAI and did some backtesting find that it performed well but some stop loss triggers took all the profit so how could I analyze trades bot made during the backtesting?
<img width="764" alt="myAI2first" src="https://github.com/freqtrade/freqtrade/assets/28696174/d68092fb-66a0-47e3-bc53-998e017f840a">

**Comment by xmatthias** [comment]
The most likely simplest way is to use freqUI for this.

you start freqtrade with `freqtrade webserver` - and freqUI will have a backtesting view.
you can either run a backtest from there - OR load an existing backtest result. It'll give you the same data than the CLI - but also the ability to
* look at individual trades
* look at individual trades on a chart (with your indicators, if you choose to configure them)

**Comment by froggleston** [comment]
You can also use the `backtesting-analysis` command to look at indicators related to entry signals. (Exit signals are a future feature).

**Comment by S-shekharDuggal** [comment]
thanks for prompt reply
