### ISSUE TITLE
docker way: cannot download-data

### ISSUE THREAD

**Issue by 61go** [freqtrade/freqtrade#9073]
## Describe your environment

  * Operating system: macos
  * Python Version: 3.11.4
  * CCXT version: 4.0.36
  * Freqtrade Version:  2023.7 
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

when i run freqtrade in docker, and make a user-dir called 'ft_userdata'：
I run command like below:
 docker-compose run freqtrade download-data --exchange gate --days 30 --timeframe 1d
 there is nothing downloaded in the dirs.
 
 here is log;
 base) xxx@huruipengdeMacBook-Pro ft_userdata % dcr freqtrade download-data --exchange gate --days 30 --timeframe 1d                
[+] Building 0.0s (0/0)                                     
[+] Building 0.0s (0/0)                                     
2023-08-20 10:23:46,620 - freqtrade - INFO - freqtrade 2023.7
2023-08-20 10:23:46,620 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2023-08-20 10:23:46,623 - freqtrade.loggers - INFO - Verbosity set to 0
2023-08-20 10:23:46,623 - freqtrade.configuration.configuration - INFO - Using exchange gate
2023-08-20 10:23:46,688 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2023-08-20 10:23:46,688 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/gate ...
2023-08-20 10:23:46,688 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1d']
2023-08-20 10:23:46,688 - freqtrade.configuration.configuration - INFO - Detected --days: 30
2023-08-20 10:23:46,689 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2023-08-20 10:23:46,693 - freqtrade.exchange.check_exchange - INFO - Exchange "gate" is officially supported by the Freqtrade development team.
2023-08-20 10:23:46,693 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2023-08-20 10:23:46,694 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2023-08-20 10:23:46,697 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2023-08-20 10:23:46,697 - freqtrade.exchange.exchange - INFO - Using CCXT 4.0.36
2023-08-20 10:23:46,697 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2023-08-20 10:23:46,702 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2023-08-20 10:23:46,707 - freqtrade.exchange.exchange - INFO - Using Exchange "Gate.io"
2023-08-20 10:23:46,707 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Gate'...
2023-08-20 10:23:46,707 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2023-08-20 10:23:56,239 - freqtrade.data.history.history_utils - INFO - About to download pairs: [], intervals: ['1d'] to /freqtrade/user_data/data/gate

**Comment by 61go** [comment]
2023-08-20 10:23:56,239 - freqtrade.data.history.history_utils - INFO - About to download pairs: [], intervals: ['1d'] to /freqtrade/user_data/data/gate

I am sure that i have done the right config.json

**Comment by stash86** [comment]
Since I can't hack into your mac and look at the config.json there myself, nor can I read your mind, maybe it would be better if you paste your config.json here? Remove any sensitive info.

**Comment by 61go** [comment]
{
    "max_open_trades": -1,
    "stake_currency": "USDT",
    "stake_amount": 1000,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "pairs": [
        "ETH/BTC"
    ],
    "exchange": {
        "name": "gate",
        "key": "efa4327596d733adba4fc1b9a90c4f21",
        "secret": "xxx",
        "ccxt_config": {
            
        },
        "ccxt_async_config": {},
        "pair_whitelist": [
            "ETH/BTC",
            "BTC/USDT"
        ],
        "pair_blacklist": [
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": true,
        "token": "5341109352:xxx",
        "chat_id": "5097110543"
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "d4125c4701a1a8b1db764793c0bcb2a2432b285a3fa9c5f721b6fa12dfb4bf1c",
        "ws_token": "Rp4r56JNIDh0bwRuBEBnT2jXvGU5QKhSlA",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "freqtrader"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

**Comment by 61go** [comment]
> Since I can't hack into your mac and look at the config.json there myself, nor can I read your mind, maybe it would be better if you paste your config.json here? Remove any sensitive info.



here it is:


`
{
    "max_open_trades": -1,
    "stake_currency": "USDT",
    "stake_amount": 1000,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "pairs": [
        "ETH/BTC"
    ],
    "exchange": {
        "name": "gate",
        "key": "efa4327596d733adba4fc1b9a90c4f21",
        "secret": "a685f7c93c8e2de5436e4b4c2c9f22a669505c4b37bf085aee173eb5c2d00c4e",
        "ccxt_config": {
            
        },
        "ccxt_async_config": {},
        "pair_whitelist": [
            "ETH/BTC",
            "BTC/USDT"
        ],
        "pair_blacklist": [
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": true,
        "token": "5341109352:AAGr5IoXS35hQwU1zCM0gHe7GVK_64BJZwk",
        "chat_id": "5097110543"
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "d4125c4701a1a8b1db764793c0bcb2a2432b285a3fa9c5f721b6fa12dfb4bf1c",
        "ws_token": "Rp4r56JNIDh0bwRuBEBnT2jXvGU5QKhSlA",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "freqtrader"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}`

**Comment by 61go** [comment]
I am a chinese user. Thanks for your reply.

**Comment by stash86** [comment]
I deleted your config since you don't remove your API and telegram info. Re-paste the config after you remove them.

**Comment by 61go** [comment]
never mind.  the info is fake.

**Comment by xmatthias** [comment]
The initial suspicion here might be that `dcr` is resolving to the wrong thing.

Our [tutorials]() assume the use of `docker compose` - which implies that the directory is mounted appropriately.
`dcr` could be anything (correct or incorrect) - but is most likely the problem you're having.

Please use the commands the way the [documentation](https://www.freqtrade.io/en/stable/docker_quickstart/#example-download-data-with-docker) has them.

Also, you're not passing explicit pairs (`--pairs BTC/USDT ETH/USDT`) - and your configuration seems to not contain any pair info - therefore there's nothing to do for the bot.

**Comment by 61go** [comment]
<img width="933" alt="image" src="https://github.com/freqtrade/freqtrade/assets/38805537/e4f30986-c82d-4c17-98fd-97b448f914ed">

DCR = docker-compose run 
I set an alias bash for :docker-compose run

**Comment by 61go** [comment]
<img width="603" alt="image" src="https://github.com/freqtrade/freqtrade/assets/38805537/cfdc4d62-c010-49a0-beeb-bab9388e757d">

from this line, you can see .  freqtrade has read the --paris variables. but in the end , it lost for unkonwn reason.

**Comment by 61go** [comment]
can you guys run successfully in docker way?

**Comment by xmatthias** [comment]
Yes.
Your pair-namings seem wrong for the configuration. you're using futures - but pairs are named for spot.
Futures pairs should be named `base/quote:settle`.

the [documentation](https://www.freqtrade.io/en/latest/leverage/#pair-namings) is your friend in this regards.

**Comment by 61go** [comment]
Oh my God!  
It works! (ignore my pool English expression).
I change it from future to spot , it now works.
thx very much, I search for the reason for a whole day....
Alright, now I can happily lose money again!
And Best Wishes for you team! (a wish sentense from chatgpt)
