### ISSUE TITLE
error 100204 for bingx exchange

### ISSUE THREAD

**Issue by simons1010** [freqtrade/freqtrade#9074]
Hi

I am using freqtrade as a trading bot that uses ccxt and bingx as exchange but I see this error on the console when running the bot :

freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair BTC/USDT due to ExchangeError. Message: bingx {"code":100204,"msg":"","timestamp":1692542166362}". Retrying still for 4 times.

I am not a technical person and I need to know if this problem is from your side or exchange.

## Describe your environment

  * Operating system: windows server 2019
  * Python Version: 3.11.4 
  * CCXT version: 4.0.8
  * Freqtrade Version: 2023.7

**Comment by xmatthias** [comment]
could be both - binx is not an exchange we officially support - which effectively means you might be the first to actually try this exchange.


In theory, freqtrade supports every exchange ccxt supports, which would also include this exchange.

Now you're the first to ask for that (at least as far as i remember), so you're probably the first to have a look at this.
we have a rough guideline on things to check in the [contributors section of the documentation](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip).
While it's probably not complete, it should give you a good idea if the exchange will work for spot trading.

If you encounter specific problems, we're happy to assist up to a certain point - but the expectation for new exchanges is that the user is doing the legwork / most of the testing work - which also assumes a somewhat familiarity with python / testing/debugging things in python.

If you're new to python / development (as you say, you're not a technical person) - you're almost certainly better of with one of the supported exchanges.

---

the error itself points to a very generic problem.

A quick test shows that they probably don't support historic ohlcv candle data (i'm unable to provide a valid startTime parameter prior to a few 1000 candles - which effectively means you'll be flying blind (no backtesting, no more than ~1400 candles).

The API documentation doesn't really specify what limits they have for historic data - which is usually a sign that they don't have much available - if any.

That effectively excludes that exchange from being useful or a candidate to be supported by freqtrade - as work going into it will be time wasted.
