### ISSUE TITLE
patch docker for telegram notification

### ISSUE THREAD

**Issue by boiydiego777** [freqtrade/freqtrade#9075]
Hi Matthias,

can you implement the following in docker ft 

https://github.com/ssssi/freqtrade_strs/blob/main/binance/some_feature/max_min_profit%2Bcode/max_min.patch

[max_min.patch](https://github.com/freqtrade/freqtrade/files/12388920/max_min.patch)

Kind regards Diego

**Comment by xmatthias** [comment]
you should consider converting this to a pull request.

I understand this can be challenging if you never did, but it's not that difficult, and pretty well documented in various parts, for example:
[create a pull request](https://opensource.com/article/19/7/create-pull-request-github)

---

Please understand however that i'll not pull random patchsets (which are not even from the person requesting that).
There might be reasons why the original author didn't provide this as a pull request (reasons i'm not aware of), which can range from license concerns, to just "i was too lazy".

Simply applying the patch-set will imply that i have the authors authorization, which i don't - and would therefore equate to stealing that person's work.

By submitting a PR, the author of that PR takes ownership - which implies that he's either the author himself - or has permission by the author.
