### ISSUE TITLE
Multiple time frame

### ISSUE THREAD

**Issue by bartek666666** [freqtrade/freqtrade#9076]
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.10.12
  * CCXT version: 1.87.55
  * Freqtrade Version: 2023.7
  
## Your question

Hi

Sorry for dumb question but how can i use multiple time frames in one strategy? in strategy customisation there's and example how to add additional time frame in informative_pairs:

`    def informative_pairs(self):

        # get access to all pairs available in whitelist. 
        pairs = self.dp.current_whitelist()
        # Assign tf to each pair so they can be downloaded and cached for strategy.
        informative_pairs = [(pair, '1d') for pair in pairs]
        return informative_pairs`

It allows you to add additional time frame witch works, but I want add two time frames 4h and 1D. again, my programming skills are near zero so please be kind.

**Comment by stash86** [comment]
Look at the example here

https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs-decorator-informative

**Comment by bartek666666** [comment]
that works, thanks
