### ISSUE TITLE
Freqtrade unable to find pair BTC/USDT when running in futures mode

### ISSUE THREAD

**Issue by Zayonx-0** [freqtrade/freqtrade#9098]
## Describe your environment

  * Operating system:  Windows 10 
  * Python Version: 3.8.7
  * CCXT version: uknown
  * Freqtrade Version:  2023.7
  Using a docker installation. 
  
## Your question

I am trying to run a backtesting session using the exchange Bybit and using data from futures. However, after downloading all pairs using the right format (example:  "BTC/USDT:USDT") I get the following errors

 ```2023-08-22 07:31:16,826 - freqtrade.data.history.idatahandler - WARNING - No history for BTC/USDT, futures, 5m found. Use `freqtrade download-data` to download the data
2023-08-22 07:31:16,827 - freqtrade.data.dataprovider - WARNING - No data found for (BTC/USDT, 5m, ).
2023-08-22 07:31:17,061 - freqtrade.data.history.idatahandler - WARNING - No history for BTC/USDT, futures, 15m found. Use `freqtrade download-data` to download the data
2023-08-22 07:31:17,061 - freqtrade.data.dataprovider - WARNING - No data found for (BTC/USDT, 15m, ).```

command used to download the data : `docker compose run --rm -p 127.0.0.1:8081:8081 freqtrade download-data --timeframes 5m 15m 1h 4h 1d --timerange 20230101-20230821`

My config file :

{
    "max_open_trades": 5,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "EUR",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "futures_funding_rate":0,
    "liquidation_buffer": 0.05,
    "leverage": 5,
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "bybit",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
            "BTC/USDT:USDT",
            "ETH/USDT:USDT",
            "XRP/USDT:USDT",
            "SOL/USDT:USDT",
            "DOT/USDT:USDT",
            "ADA/USDT:USDT",
            "DOGE/USDT:USDT",
            "LUNA2/USDT:USDT",
            "UNI/USDT:USDT",
            "LINK/USDT:USDT",
            "LTC/USDT:USDT",
            "BCH/USDT:USDT",
            "MATIC/USDT:USDT",
            "XLM/USDT:USDT",
            "TRX/USDT:USDT",
            "EOS/USDT:USDT",
            "ATOM/USDT:USDT",
            "ALGO/USDT:USDT",
            "XTZ/USDT:USDT",
            "FIL/USDT:USDT",
            "AAVE/USDT:USDT",
            "KSM/USDT:USDT",
            "XEM/USDT:USDT",
            "THETA/USDT:USDT",
            "MKR/USDT:USDT",
            "SNX/USDT:USDT",
            "COMP/USDT:USDT",
            "HBAR/USDT:USDT",
            "ETC/USDT:USDT",
            "WAVES/USDT:USDT",
            "AVAX/USDT:USDT",
            "BLZ/USDT:USDT",
            "ZEC/USDT:USDT",
            "ZIL/USDT:USDT",
            "DASH/USDT:USDT",
            "ICP/USDT:USDT",
            "MANA/USDT:USDT",
            "ENJ/USDT:USDT",
            "BAT/USDT:USDT",
            "QTUM/USDT:USDT",
            "ONT/USDT:USDT",
            "ZRX/USDT:USDT",
            "OMG/USDT:USDT",
            "FTM/USDT:USDT",
            "SUSHI/USDT:USDT",
            "GRT/USDT:USDT",
            "IOST/USDT:USDT",
            "KNC/USDT:USDT",
            "ONE/USDT:USDT",
            "RVN/USDT:USDT",
            "LRC/USDT:USDT",
            "SC/USDT:USDT",
            "RUNE/USDT:USDT",
            "BNT/USDT:USDT",
            "OGN/USDT:USDT"
        ],
        "pair_blacklist": [
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList"
        }
    ],
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8081,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "8ce3c6b1a018577932f78cdc0f1e96b7c6e63786c9cfe375b8e70e0XXXXXXXXX",
        "ws_token": "3Itc5b7mQ_UmuL_JzzKcwOEU9XXXXXXXXX",
        "CORS_origins": [],
        "username": "fXXXXXXXXX",
        "password": "XXXXXXXXX"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

What I have tried already : 
- Completly deleting all files and folder in the data folder, then re-downloading all datas
- Downloading spot informations for BTC/USDT and include it in the data/futures folder

Any help would be much appreciated, thanks !

**Comment by xmatthias** [comment]
You're almost certainly using a strategy which is using [informative pairs](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs) or as [`@informative`](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs-decorator-informative) - which will be using the spot notation.

A good hint for this is that your error is for 2 timeframes, 5m and 15m.
You'll need to update these references for futures pairs as well (or ensure the system KNOWS that these should be spot pairs).
There's an (currently undocumented) way to for this - but for now, i doubt that's what you're after.

**Comment by ZahidGalea** [comment]
Thanks!

**Comment by ZahidGalea** [comment]
> You're almost certainly using a strategy which is using [informative pairs](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs) or as [`@informative`](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs-decorator-informative) - which will be using the spot notation.
> 
> A good hint for this is that your error is for 2 timeframes, 5m and 15m. You'll need to update these references for futures pairs as well (or ensure the system KNOWS that these should be spot pairs). There's an (currently undocumented) way to for this - but for now, i doubt that's what you're after.

Thanks! I was trading futures and also pulling spot informative_pairs inside my strategy
