### ISSUE TITLE
TypeError: unsupported type for timedelta minutes component: numpy.int64

### ISSUE THREAD

**Issue by pine2023** [freqtrade/freqtrade#9099]
## Describe your environment

  * Operating system: Linux
  * Freqtrade Version: freqtrade docker-2023.8.dev-cf226afb
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I know the value of `stop_duration` is in minutes
but it throws a type error

### Steps to reproduce:
```python
    # Define the parameter spaces
    use_cooldown_lookback = BooleanParameter(default=True, space="protection", optimize=True)
    cooldown_lookback = CategoricalParameter([720, 1440, 2160], default=720, space="protection", optimize=True)
    
    @property
    def protections(self):
        prot = []
        if self.use_cooldown_lookback.value:
            prot.append({
                "method": "CooldownPeriod",
                "stop_duration": self.cooldown_lookback.value
                # "stop_duration_candles": self.cooldown_lookback.value
            })
```
  
### Relevant code exceptions or logs

  ```
  File "/freqtrade/freqtrade/plugins/protections/cooldown_period.py", line 35, in _cooldown_period
    look_back_until = date_now - timedelta(minutes=self._stop_duration)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported type for timedelta minutes component: numpy.int64
  ```

**Comment by xmatthias** [comment]
By the looks of it, scikit-optimize converts the values to a numpy type (which makes sense if you think about how the underlying stuff works) if you're using a categorical feature.

You should be able to fix this pretty easily with `"stop_duration": int(self.cooldown_lookback.value)`.

**Comment by pine2023** [comment]
Thanks for giving me a temporary solution
I like to use categorical features in many places, and the error does not occur anywhere else in the strategy class.
Should I understand it as a characteristic of @property?

```python
    # works fine
    ema1 = CategoricalParameter([20, 30, 40], default=20, space="buy")
    ema2 = CategoricalParameter([50, 60, 80], default=50, space="buy")
    ema3 = CategoricalParameter([100, 150, 200], default=100, space="buy")
```

**Comment by xmatthias** [comment]
It's not temporary - there's no other fix for that (you can use IntParameter, where this would not occur afaik).

it's a characteristic of how it's used - as part of a shift in the python datetime module.

When using EMA - it'll almost certainly be used in something like `ta.EMA()` (or similar) - which accepts numpy types - but the python datetime module does not.

**Comment by stash86** [comment]
Just to add, even if you use IntParameter, you would still need to use `int(self.blablabla.value)`, esp on functions that specifically ask for int, for example talib's moving average functions

**Comment by pine2023** [comment]
As far as I know, IntParameter doesn't have a step function, so it may not be an alternative for users like me who don't want a wide space.
It looks good to handle this part in `cooldown_period.py`.
Thank you

**Comment by stash86** [comment]
You can always do 5* self.blabla.value, where int is 1 to 5, for example. Or other formula to get your preferred steps. Why limit yourself with steps?

**Comment by pine2023** [comment]
Does that mean you can change CategoricalParameter([720, 1440, 2160]) to IntParameter ?
The reason is that I don't want fine grain tuning.

**Comment by pine2023** [comment]
nvm, it's possible

**Comment by xmatthias** [comment]
hm, i thought it's limited to category - but apparently, it's because of the use fo stop_duration instead of `stop_duration_candles` (which is what i always use).

will be fixed on develop shortly..
