### ISSUE TITLE
Add support for slippage detection and add configurable max slippage value to the conf file.

### ISSUE THREAD

**Issue by ZeroCool940711** [freqtrade/freqtrade#910]
The slippage is one of the problems that we face when we start trading using the orderbook but its not all negative, it can help us getting more profit or it can cause losses depending on how we use it. For those of you that dont know what the slippage is here is a sort definition taken from google:

> What is 'Slippage'
Slippage refers to the difference between the expected price of a trade and the price at which the trade is actually executed. Slippage often occurs during periods of higher volatility, and also when large orders are executed when there may not be enough interest at the desired price level to maintain the expected price of trade.

Depending on the volume of our order and other factors we may end up buying or selling at a different price than the price we intended, to prevent problems with this I recommend we have a configurable option on the config file called max_slippage, if the result from calculating the slippage of our order is higher than that value the bot wont place the order to avoid lossing money, here is a link with more information on how to calculate the slippage and different ways to do it.

https://www.zipline.io/_modules/zipline/finance/slippage.html

**Comment by creslinux** [comment]
slippage is from making a market buy/sell not limit. 

- A limit buy will be filled or partially at price, or not, with no slip.
- A market buy will buy up the order book to fill the order, with possible slip 

There is no means to control slippage other than not executing the market entire order. 
If you market buy and the order book melts before you hit it you're buying at a higher price - end of. 

A pseudo means would be to create many smaller limit orders in serial. 

Any management of when to make orders, or not, should be in the strategy file not the core bot. 
The strategy can determine to make market / limit buys and if to make many small limit buys on confirmation of other smaller buys being successful or not.

**Comment by xmatthias** [comment]
@creslinux if i understand you correctly, you think this would be covered by completing #909 ?

**Comment by creslinux** [comment]
Although im not sure what that gives is over buying at $3 over spot on a limit order
