### ISSUE TITLE
Incorrect volume in futures (not base neither quote)

### ISSUE THREAD

**Issue by dnuno89** [freqtrade/freqtrade#9104]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.10 (`python -V`)
  * CCXT version: 3.1.44 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.6 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  

## Describe the problem:

I saw inconsistencies in the volume reported for futures markets. I checked directly with ccxt, having the same result, and opened an [Issue with them](https://github.com/ccxt/ccxt/issues/18941) .

They explained that in futures markets, the volume is reported in number of contracts, not in base or quote currency, and provided code to obtain that relation. Each coin may have totally different amounts for each contract, so the volume has arbitrary units. This makes using Volume for pairlist filtering unusable. 

An example (as given in the CCXT issue, where there is also more code/pictures related to the issue - https://github.com/ccxt/ccxt/issues/18941):

> If you print the tickers for ADA (current example) and LTC:
> ```
> ADA: {'symbol': 'ADA/USDT:USDT', 'timestamp': None, 'datetime': None, 'high': 0.27793, 'low': 0.23198, 'bid': 0.26379, 'bidVolume': None, 'ask': 0.26382, 'askVolume': None, 'vwap': 0.2638999441021817, 'open': None, 'close': 0.2639, 'last': 0.2639, 'previousClose': None, 'change': None, 'percentage': -4.45, 'average': None, 'baseVolume': 16709060.0, 'quoteVolume': 4409520.0, 'info': {'last': '0.2639', 'low_24h': '0.23198', 'high_24h': '0.27793', 'volume_24h': '1670906', 'change_percentage': '-4.45', 'funding_rate_indicative': '-0.000007', 'index_price': '0.26413', 'volume_24h_base': '16709060', 'volume_24h_quote': '4409520', 'contract': 'ADA_USDT', 'volume_24h_settle': '4409520', 'funding_rate': '-0.000007', 'mark_price': '0.26413', 'total_size': '498528', 'highest_bid': '0.26379', 'lowest_ask': '0.26382'}}
> 
> LTC: {'symbol': 'LTC/USDT:USDT', 'timestamp': None, 'datetime': None, 'high': 75.71, 'low': 54.99, 'bid': 65.29, 'bidVolume': None, 'ask': 65.3, 'askVolume': None, 'vwap': 65.29004929658765, 'open': None, 'close': 65.29, 'last': 65.29, 'previousClose': None, 'change': None, 'percentage': -13.28, 'average': None, 'baseVolume': 926839.0, 'quoteVolume': 60513364.0, 'info': {'last': '65.29', 'low_24h': '54.99', 'high_24h': '75.71', 'volume_24h': '9268397', 'change_percentage': '-13.28', 'funding_rate_indicative': '-0.000066', 'index_price': '65.33', 'volume_24h_base': '926839', 'volume_24h_quote': '60513364', 'contract': 'LTC_USDT', 'volume_24h_settle': '60513364', 'funding_rate': '-0.000066', 'mark_price': '65.33', 'total_size': '714013', 'highest_bid': '65.29', 'lowest_ask': '65.3'}}
> ```
> 
> For ADA, there is 'volume_24h_base': '16709060', 'volume_24h_quote': '4409520',  but the volume given by CCXT is  'volume_24h': '1670906', which is **the base volume divided by 10** (I supose this is related to the amount in each contract).
> 
> For LTC, is the contrary. 'volume_24h_base': '926839', 'volume_24h_quote': '60513364', but the volume given by CCXT is equal to 
> 'volume_24h': '9268397', which in this case is **the base volume multiplied by 10**, instead of divided.
> 
> This makes the volume of all pairs uncomparable, and in my case I can't implement a minimum volume to filter my pairlist, as each coin varies the relation between the CCXT given volume and the real volume (either base or quote).
> 
> 
>

**Comment by xmatthias** [comment]
I'm happy to look at this if you have an example where the sorting is actually wrong when using Freqtrade (please provide the pairlist configuration and exchange you used to get to that, and include information based on which it's visible that the sorting is actually wrong).

Otherwise, this is just theoretical question - which is usually a topic where we'll waste time with no real outcome.

**Comment by dnuno89** [comment]
I've now seen it was my fault. I have a custom pairlist function based on VolumePairlist, and didn't update it with the contract size which I now see, the freqtrade Volume pairlist do consider correctly. 
I'm sorry for the inconvinience,
