### ISSUE TITLE
Add fill_holes_in_book option to config file so the bot place orders between two orders on the orderbook

### ISSUE THREAD

**Issue by ZeroCool940711** [freqtrade/freqtrade#911]
Now that we have or will soon have the ability to place orders using the orderbook an not only the top order another useful feature would be the ability for the bot to fill holes on the orderbook, what it means is that if the bot bought B2G at 174.5 USD but there are only two orders close to that price, one is at 174 USD and the other one at 175 USD, if we open a new order for a few cents lower than the one at 175 USD for example at 174.9 USD we will be one position higher on the orderbook and most likely the volume of our order will be smaller than the one at 175 USD meaning that our order will have a higher chance to get filled before the one at 175 USD.

**Comment by ZeroCool940711** [comment]
That should be a core function in my opinion but it can be easily added as a true/false option on the config just to say if we want to use it or not and then on the strategy it can be modified to make it better and improve the decision of where to place the order exactly.

**Comment by creslinux** [comment]
its a buying strategy 
we could put all buy/sell strategy options into config.json with true/false. 

There is no difference between make buy when see a  gaps in order book than buy when crosses sma21.

**Comment by creslinux** [comment]
the bot should provide the order book as if should be able to provide the SMA
A gap in the order book is just an indicator, like any other 

The analysis of that indicator and buying decision is for a strategy to trigger on.

I would propose an "orderbook gap" indicator be written that takes  two argument of ceiling from spot and step 

e.g if btc is at 7,000 the ceiling may be $10, the step $0.50, it will provide back order volume for each 0.50$ step upto $10 above spot. 

This will allow  a strategy to determine where is currently best to to put there order, ahead of a buy wall as example.

**Comment by creslinux** [comment]
Slightly off topic, but of value.
The community should be aware of icebergs  - large hidden orders on the book.
Most exchanges support paying market rate on a limit order to hide the order from the book. 

Buying into an empty step may well be others have spotted a hidden buy wall and are avoiding it.

**Comment by ZeroCool940711** [comment]
I agree with the hidden orders for example Hitbtc allows that, for the rest of what you said I agree partially with you that the strategy should be able to handle all that stuff but if the fill holes thing will be handled by the strategies I recommend that its added to the default strategy and that just like other values like minimal_roi we can override it if we set a value for that on the config file, again, I agree with you that everything related to buy/sell should be handled by the strategy but some values should be easy to edit on the config file for those people who dont want to mess with the strategy directly and just want to change a few values easily.

**Comment by xmatthias** [comment]
This point will be enabled with #5347. 
While it will require some custom code to explicitly fill points between orderbook slots - this way will provide the most flexibility.
