### ISSUE TITLE
Python version under conda

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#9111]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: 3.10 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.7 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

To install Freqtrade under conda, you recommend python 3.10 here:
https://www.freqtrade.io/en/stable/installation/#installation-with-conda

conda create --name freqtrade python=3.10

Due to some installation issues, I ask you, if this version is still your current recommendation, if not:
What is the latest version, which is "waterproof" to run Freqtrade?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Freqtrade supports 3.8, 3.9, 3.10 and 3.11 - as listed in the [system requirements](https://www.freqtrade.io/en/stable/#software-requirements). (3.8+ includes all stable versions >= 3.8).

**Comment by myNextCoder** [comment]
Great, then I use 3.8
