### ISSUE TITLE
model not predicting 

### ISSUE THREAD

**Issue by S-shekharDuggal** [freqtrade/freqtrade#9120]
## Describe your environment

  * Operating system: windows 10
  * Python Version: 3.11.4
  * CCXT version: 4.0.36
  * Freqtrade Version:2023/7
  
Q1 dataframe["do_predict"] always return 0 or -1 due to which strategy not making trades. 
**what happened** : it was working well i tested it for BTC/USDT:USDT for the period 20191101-20191107 it made 4 trades and 4 of those were winner then I decided to test it for longer period and started backtesting again for the period 20191101-20191231 which ended with error while training and AI stopped trading.
**What I have tried**: I tried deleting all the data for AI by deleting identifier model and retrain it it did not work if i remove the condition dataframe["do_predict"]==1 from trading condition it works then I printed the values of dataframe["do_predict"] found those are either   0 or -1 but not 1
note: it is calculating target values and which is helping the bot to make the right decision but its still return 0 for do_predict

**Comment by robcaulk** [comment]
Hello,

Are you familiar with the outlier detection module in freqai? do_predict is handling this information for you. Have a read thru the documentation where we describe it as clearly as possible:

https://www.freqtrade.io/en/stable/freqai-configuration/#important-dataframe-key-patterns

If you prefer not to become familiar with the outlier detection in freqai, you can turn all the outlier detection methods off in your config or remove do_predict from your strategy.

cheers,

robert

**Comment by S-shekharDuggal** [comment]
thanks for reply... but I have this question what went wrong that its always returning anything but one because its not making trades for that same period where it did before and won with 100% win rate more over its been 3 days. I tested with different data many number of time even let it run for more than 15hours it didn't make any trade is there a possibility that I may have changed some variable or corrupted code which may cause this.
