### ISSUE TITLE
Show the indicator on the chart

### ISSUE THREAD

**Issue by armin-fallah** [freqtrade/freqtrade#9121]
* Operating system: ubuntu
* Python Version: 3.10
* CCXT version: 4.0.57
* Freqtrade Version:2023.7

Hello, I want to display the rsi indicator in the frequi chart. Is it possible ? Thank you for telling me how to do it.

**Comment by xmatthias** [comment]
You can use the cog (small wheel) at the top right of the chart to open the Plot configurator.

![image](https://github.com/freqtrade/freqtrade/assets/5024695/8ce10f7f-8524-4e25-83d7-939e4c33c2f7)

It'll allow you to
* add indicators to the main plot (including area charts)
* add new subplots
* Add indicators to subplots 
* Save that plot config
* create multiple plot configurations
* Load plot-configs from a [strategy](https://www.freqtrade.io/en/latest/plotting/#advanced-plot-configuration) _(only applies if your strategy includes the corresponding code)_

![image](https://github.com/freqtrade/freqtrade/assets/5024695/d39b2a37-65f1-4ae5-bafb-fe5e72e15aac)
