### ISSUE TITLE
How can I get the 10k+ features

### ISSUE THREAD

**Issue by berkeserol** [freqtrade/freqtrade#9122]
Operating system: ubuntu
Python Version: 3.10
CCXT version: 4.0.57
Freqtrade Version:2023.7

Hi, 

In the documentation summary it is mentioned that there are 10k+ features in the freqAI. When I look at the code and the documentation, it is not mentioned what are those 10k+ features. There are only a few of them named. As far as I know, pandas-ta and ta-lib have only hundreds of TAs. What is the code I need to write to have 10k+ features in my dataframe?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

On top of that, you'll need to be more precise about what you're actually asking.
if it's about freqAI features (most likely, but just an educated guess) , then the best read the full [freqAI docs](https://www.freqtrade.io/en/stable/freqai/) to understand how these features are architected.

**Comment by robcaulk** [comment]
You appear to be asking about how to perform feature engineering in freqai. Here is a link where we teach you:

https://www.freqtrade.io/en/stable/freqai-feature-engineering/#feature-engineering

**Comment by xmatthias** [comment]
Closing this as i think your question has been answered, and we didn't hear back from you after our pointers to the relevant documentation sections.

Feel free to comment below if it's still unclear.
