### ISSUE TITLE
Indicator examples without using TA?

### ISSUE THREAD

**Issue by Nuckaka** [freqtrade/freqtrade#9126]
I really don't want to make a request like "do it for me " but I really have no idea making my own indicators.

Because all(?) indicators from examples using TA and I can't customize or read TA-LIB easily according to google.

Examples that indicator without using ta within the price chart will be appreciated.

**Comment by froggleston** [comment]
There are a lot of other indicator libraries, including [pandas_ta](https://github.com/twopirllc/pandas-ta), [finta](https://pypi.org/project/finta/) and others. Please be aware that some of these libraries may have lookahead bias when used in backtesting with freqtrade, so be sure to check any strategy you develop or use with the `lookahead-analysis` command.

**Comment by Nuckaka** [comment]
I mean making my own indicator not using other indicator libraries. But thanks for your suggestion.

**Comment by xmatthias** [comment]
Well you're looking for ideas how an indicator can be implemented, or on "how to copy" an indicator and modify to your liking - so looking at other indicator libraries **is** the way to go / learn.

A few more idesas:
the vendored [qtpylib indicators file](https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/vendor/qtpylib/indicators.py) - or [technical](https://github.com/freqtrade/technical).

I'd be careful with finta, personally - it's repository is archived / read only now - we've found a few instances of it not performing calculations the way it should. This won't apply to all indicators - but to some.

**Comment by froggleston** [comment]
Those libraries should hopefully provide some inspiration - there's nothing stopping you from coding up anything you like in python based on OHLCV data or external data sources.
