### ISSUE TITLE
freqai with external data source

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#9130]
* Operating system: ____
  * Python Version: __Python 3.11.5
  * CCXT version: ___ccxt==4.0.76
  * Freqtrade Version: __docker-2023.9-dev-e0e0a258
## Your question

Experimenting with FreqAI and trying to hook up the external database. It seems that it doesn't follow the same logic as the standard freqtrade strategy file structure. 
I've tried to add in the feature_engineering_expand_all and also dedicated function to be used with populate_indicators where merge_informative_pair is called and at current state it's unable to find the columns 

```
 _ai  | 2023-08-31 10:23:36,794 - freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair ETH/USDT:USDT: 'chm_current_eth'
freqtrade_ai  | 
freqtrade_ai  | 2023-08-31 10:23:36,800 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair ETH/USDT:USDT
freqtrade_ai  | 2023-08-31 10:23:37,824 - freqtrade.freqai.freqai_interface - ERROR - Training ETH/USDT:USDT raised exception KeyError. Message: 'chm_current_eth', skipping.
freqtrade_ai  | Traceback (most recent call last):
freqtrade_ai  |   File "/home/ftuser/.local/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc

```
What would be the correct approach  for a location and reference of the external data source in freqai?

**Comment by xmatthias** [comment]
the logic is acutally exactly the same - you can effectively treat freqAI as just another indicator.

As with all indicators - sequence matters.
 in `populate_indicators` - you'll need to make sure to call this BEFORE calling freqAI, if you want freqAI to have access to this (which is my assumption for now - as that'll make the most sense, usually).

`feature_engineering_expand_all` is almost certainly the wrong location, unless you need it per "include_corr_pairlist" and per include_timeframes (which is what expand_all means).

**Comment by darioneto** [comment]
Ok I see, 
Is there a recommended function where I should insert code to pull data from my external database, or can I simply embed this within populate_indicators, just as I would in a traditional strategy file?

Does freqAI expect a specific set of column names in the DataFrame, or is it flexible like the traditional methods?

Regarding the 'include_corr_pairlist' and 'include_timeframes' features, does this mean that if I don't incorporate my external database within feature_engineering_expand_all, I won't be able to utilize these features? Which, in turn, means I would have to anchor it in all functions?

what do you think about establishing a persistent connection: Instead of connecting to the database within the populate_indicators method, maybe more efficient to establish a persistent connection in the strategy's constructor (__init__ method) and use it throughout the strategy? As if I need to ref those in the feature selections (basic, standard, all) I still need to call the db in each function first?
So instead just move the database query logic to a separate method dedicated to fetching the indicators and then call this method from within each function?

Alternatively maybe the easiest to take a working strategy file and start layering on the top to see what individual feature does? As when I add those additional freqai functions it's easy to get lost lol.

**Comment by xmatthias** [comment]
freqAI has quite extensive documentation about both [feature engineering](https://www.freqtrade.io/en/latest/freqai-feature-engineering/) - which includes how the the features should be named.

It's up to you to determine WHAT you pull from your "external database". Think about these methods as helpers to expand the feature space (by using different timeframes and different informative pairs).
What that "external database" provides is up to you to know.

> Alternatively maybe the easiest to take a working strategy file and start layering on the top to see what individual feature does? As when I add those additional freqai functions it's easy to get lost lol.

Clearly, you start with reading the freqAI documentation **until you understand it**.
Your questions make it clear that you probably didn't look at the documentation, or at least didn't  understand what each method does.

---

How you connect to your database is up to you.
Freqtrade does offer no guidance for this. If you're unfamiliar how to incorporate a database into a project, then best don't, and stick to known and documented methods.
We'll not prevent you from using a database - but the assumption is that you are familiar with the tradeoffs that each method has (like connection interrupts, ...).

**Comment by darioneto** [comment]
I have read through the documentation, and upon testing, I have found that the dataframes are not found in the feature engineering functions when I call the database in 'populate_indicators'. This is how it has been working for a long time with no issues in the regular strategy file. I also discovered that if I call the database directly within each function, it works. However, this is probably not the ideal method. Therefore, my question was about recommended approach for this case

**Comment by xmatthias** [comment]
you're probably looking for `feature_engineering_standard()` - which will work for both the historic simulations, as well as live/dry runs.
it's only called once per pair (per train period) ... and should therefore work for your  usecase.
you'll obviously still need to be aware of HOW things work - and avoid having your signals future-looking or similar.

**Comment by darioneto** [comment]
Thanks for the tip, I was sort of leaning that way based on tests. I'm not too worried about "look-ahead bias" as I was planing to use strategies that are already battle tested. The whole point of using freqai for me is to automate the constant tuning and hyperopt, which is a real time-sink. However on the other hand my other concern is about losing visibility and control. It could turn the system into more of a black box, which would make troubleshooting a lot harder. By the way, how do you rate from your experience freqai strategies stack up against traditional ones in terms of performance?
