### ISSUE TITLE
need to configure vscode along with docker to debug code

### ISSUE THREAD

**Issue by S-shekharDuggal** [freqtrade/freqtrade#9134]
## Describe your environment

  * Operating system: windows 10
  * Python Version: __python 3.11.4
  * CCXT version: 4.0.36
  * Freqtrade Version:2023.8
  
Q1 how do I configure vscode to use docker image of freqtrade I have already installed ?
I'm sorry for such naive question, I'm newbie with docker and python

**Comment by xmatthias** [comment]
Freqtrade contains a devcontainer configuration. 
if you open vscode with the right extensions installed, it should ask you to reopen in a devcontainer.

Doing so will allow you to use vscode within docker.
it will reuse some base of your existing image - but it's effectively a slightly different image, as it needs a bit more stuff installed.

best refer to the [official documentation](https://code.visualstudio.com/docs/devcontainers/containers) on how to use that on your particular system - and what extensions need to be installed for this (hint: it's the [Dev Containers extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers)

**Comment by S-shekharDuggal** [comment]
![image](https://github.com/freqtrade/freqtrade/assets/28696174/81fd56de-6083-4edd-81d1-6e3997b19147)
I tried that way but still not being able to debug getting many errors. can you suggest exact procedure

**Comment by xmatthias** [comment]
well based on the filename of the opened file i can tell that vscode is not running in a devcontainer.

If it's running correctly, then you'll see this in the files pane (see below screenshot, left top).
the devcontainer will "hide" the windows paths, as they'll be located (for freqtrade / vscode) within `/workspaces/freqtrade/user_data/` - which is automatically mounted into the devcontainer.

![image](https://github.com/freqtrade/freqtrade/assets/5024695/9084b9f8-1713-40c2-9cf1-52b820f5eb0a)

**Comment by S-shekharDuggal** [comment]
Yes because I can't find my strategy file in dev container that's why I opened it locally

**Comment by xmatthias** [comment]
You can't pick and choose what you'd like.
My recommendation is to always stick to ONE method (especially if you're not familiar with a topic).

you either use docker - or you don't. 
both methods are possible - and both methods work fine - as long as you don't mix them at random.

You CAN use a local installation - but then you'll need to have
* freqtrade installed locally
* selected the appropriate interpreter in vscode.

what you can't do is use a devcontainer, but open the file locally.
That cannot work - and will not work.

**Comment by froggleston** [comment]
This is not a freqtrade issue, but an issue with the configuration of vscode. Please follow one of the many online tutorials about setting up dev containers or remote execution environments in vscode.
