### ISSUE TITLE
FreqAi tensorboard

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#9138]
Operating system: __Docker
Python Version: __Python 3.11.5
CCXT version: ___ccxt==4.0.76
Freqtrade Version: _docker-2023.9-dev-f717928a

According to the documentation I must use torch container in order to access tensorboard. I build mine from freqtradeorg/freqtrade:develop_freqaitorch

however when I start the service the TensorFlow installation is not found , should I be using different image? 

```
ftuser@cea014c1cddb:/freqtrade/freqtrade$ tensorboard --logdir user_data/models/test-4 --bind_all
TensorFlow installation not found - running with reduced feature set.
/home/ftuser/.local/lib/python3.11/site-packages/tensorboard_data_server/bin/server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/ftuser/.local/lib/python3.11/site-packages/tensorboard_data_server/bin/server)
/home/ftuser/.local/lib/python3.11/site-packages/tensorboard_data_server/bin/server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/ftuser/.local/lib/python3.11/site-packages/tensorboard_data_server/bin/server)
/home/ftuser/.local/lib/python3.11/site-packages/tensorboard_data_server/bin/server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/ftuser/.local/lib/python3.11/site-packages/tensorboard_data_server/bin/server)
TensorBoard 2.14.0 at http://cea014c1cddb:6006/ (Press CTRL+C to quit)
```

then when trying to access the board I get You haven’t written any data to your event files.
TensorBoard can’t find your event files."

**Comment by robcaulk** [comment]
Hello,

the first warning about tensorflow is just that, a warning.

Tensorboard won’t show anything until you’ve written logs to your identifier sub folder.

you will need to provide a lot more information, like the location of your identifier folder and your launch command. Additionally, you’d need to include some verification that you’re actually logging to your tensorboard logs.

**Comment by darioneto** [comment]
I run with this inside of a container 

cd freqtrade
```
ftuser@f0242b0103b2:/freqtrade/freqtrade$ tensorboard --logdir user_data/models/test-5 --bind_all

TensorFlow installation not found - running with reduced feature set.
/home/ftuser/.local/lib/python3.11/site-packages/tensorboard_data_server/bin/server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/ftuser/.local/lib/python3.11/site-packages/tensorboard_data_server/bin/server)
/home/ftuser/.local/lib/python3.11/site-packages/tensorboard_data_server/bin/server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/ftuser/.local/lib/python3.11/site-packages/tensorboard_data_server/bin/server)
/home/ftuser/.local/lib/python3.11/site-packages/tensorboard_data_server/bin/server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/ftuser/.local/lib/python3.11/site-packages/tensorboard_data_server/bin/server)
TensorBoard 2.14.0 at http://f0242b0103b2:6006/ (Press CTRL+C to quit)
```
the folder structure of test-5 identifier indicate there is a log events in tensorboard

test-5$ tree .
.
├── backtesting_predictions
│   ├── cb_eth_1692748800_prediction.feather
│   └── cb_eth_1693353600_prediction.feather
├── global_metadata.json
├── historic_predictions.backup.pkl
├── historic_predictions.pkl
├── pair_dictionary.json
├── run_params.json
├── sub-train-ETH_1693815406
│   ├── cb_eth_1693815406_feature_pipeline.pkl
│   ├── cb_eth_1693815406_label_pipeline.pkl
│   ├── cb_eth_1693815406_metadata.json
│   ├── cb_eth_1693815406_model.joblib
│   ├── cb_eth_1693815406_trained_dates_df.pkl
│   ├── cb_eth_1693815406_trained_df.pkl
│   └── tensorboard
│       └── events.out.tfevents.1693815407.f0242b0103b2.1.807
└── sub-train-ETH_1693815427
    ├── cb_eth_1693815427_feature_pipeline.pkl
    ├── cb_eth_1693815427_label_pipeline.pkl
    ├── cb_eth_1693815427_metadata.json
    ├── cb_eth_1693815427_model.joblib
    ├── cb_eth_1693815427_trained_dates_df.pkl
    ├── cb_eth_1693815427_trained_df.pkl
    └── tensorboard
        └── events.out.tfevents.1693815428.f0242b0103b2.1.808

**Comment by robcaulk** [comment]
If you are following the docker instructions [here](https://www.freqtrade.io/en/stable/docker_quickstart/), you will see that the user_data is mounted. This means that the model files and tensorboard files are saved on the host machine disk in the mounted folder.

Therefore, you need to run tensorboard on the host machine directed at the mounted directory.

**Comment by darioneto** [comment]
Sorry I'm bit confused by what you saying 
user_data directory is mounted from the host to the container, either the host or the container will have access to the same data. I execute this within the same container since what I believe it was shipped with all the necessary packages according to the doc here https://www.freqtrade.io/en/stable/freqai-running/#using-tensorboard
Are you suggesting I should install standalone variant and use it separately from freqtrade included tensor packages?

**Comment by xmatthias** [comment]
Careful googling reveals that the warnings seem to be a known (but apparently irrelevant) problem with tensorboard (https://github.com/tensorflow/tensorboard/issues/5949).
As tensorflow itself wasn't able to fix this yet, and reports in that issue (as well as your own logs) confirm that tensorboard is actually running correctly, i don't think this is anything we can either fix or help you with (refer to tensorflow if this message is bothering you).

Also, tensorFlow is expected to not be installed - tensorboard can be used without it without problems.

`http://f0242b0103b2:6006/ ` in your shows that tensorflow is now running on port 6006.

Now running this in containers (either the same, or different ones) requires the following things to be in place
* port 6006 must have a port mapping to the outside world
* the mountpoint with the logfiles must be present
* the directories must be correct, and correctly specified

Neither of the first 2 above work if you start your container with `docker compose run`.

---

Also, you seem to be "too deep" into the directory structure (`/freqtrade/freqtrade`) - which is not really how we do start containers, and which can cause some odd problems.

if i start tensorboard, it looks like this (i ran docker compose up - followed by a `docker compose exec` to get into the running container after updating the port mappings).

![image](https://github.com/freqtrade/freqtrade/assets/5024695/9ff73120-d73a-4032-bcb7-2a2bc8e5cdc4)

with the result being this:

![image](https://github.com/freqtrade/freqtrade/assets/5024695/9c2bd7d0-9895-4954-9cbc-9b37aee8dcf3)

**Comment by darioneto** [comment]
ok seems the directory structure was the root cause. 
When I run it in the main, then it worked at the first time. According to the documentation I was under impression I must to execute it from within one level higher according to this https://www.freqtrade.io/en/stable/freqai-running/#using-tensorboard. Meaning when I exec to the container I was already defaulted to the ftuser@f0242b0103b2:/freqtrade$ pwd
/freqtrade and then this cd was sending me one level higher 
```
cd freqtrade
tensorboard --logdir user_data/models/unique-id
```
Thanks for looking into it guys.

**Comment by xmatthias** [comment]
Well the assumption for that documentation is not a docker container.
if you start from the freqtrade script - this might be correct.

it'll however heavily depend on the "how" - and i think that line is more missleading than it actually helps - the "user_data/" part will suffice (you can also store user-data elsewhere, where this command would be wrong anyway).
