### ISSUE TITLE
limit for merge_informative_pair 

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#9161]
## Describe your environment

  * Operating system: ___docker_
  * Python Version: ____Python 3.11.5
  * CCXT version: ___ccxt==4.0.81
  * Freqtrade Version: __docker-2023.9-dev-20cca01d
  
I'm trying to make freqai work with my external data and while merging with "merge_informative_pair" I'm hitting the hard limit (more then 3 of the same timeframe) with adding the subsequent dataframes.(Passing 'suffixes' which cause duplicate columns {'date_5m_x'} is not allowed)
The way I typically do it is:
```
        inf_tf_5 = '5m'
        dataframe = merge_informative_pair(dataframe, dataframe_1, self.timeframe, inf_tf_5, ffill=True)
        dataframe = merge_informative_pair(dataframe, dataframe_2, self.timeframe, inf_tf_5, ffill=True)
        dataframe = merge_informative_pair(dataframe, dataframe_3, self.timeframe, inf_tf_5, ffill=True)
```
any more after that will always raise exemption, regardless if this is 5m , 15 m etc. 
While this is also the same case with the regular strategy file, the workaround for me was to change different timeframes, ie: for 10 min , 15 min and so on. While doing this with freqai will introduce however another issue of NANs 
ERROR - Training ETH/USDT:USDT raised exception ValueError. Message: With n_samples=0, test_size=0.33 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters., skipping.
Traceback (most recent call last): This is due to the fact the lower timeframe strategy (5m) merging larger timestamps
trying to add this is not solving the issue neither 
        dataframe.fillna(method='ffill', inplace=True)
        dataframe.dropna(inplace=True)

What would be the best approach to fix it other then increasing main timeframe of the strategy?

**Comment by xmatthias** [comment]
> any more after that will always raise exemption, regardless if this is 5m , 15 m etc.

If something raises an exception, please provide the (full!) stacktrace for that.

it's pretty obvious that your approach will fail - as the resulting columns will have the same names.

`merge_informative_pair()` provides a `suffix`  parameter - which you'll need to pass with a different value each time.
(you need to pass `append_timeframe=False` if you use an explicit suffix parameter).

> While this is also the same case with the regular strategy file, the workaround for me was to change different timeframes, ie: for 10 min , 15 min and so on.

Using "different timeframes" will have a different meaning / different result.
Your comment strongly sounds like "I'm passing some random timeframe " - which is clearly not supported, and may lead to completely wrong results.

The base expectation is that both dataframes correspond to the timeframes given (if you pass in 5m, the dataframe will have a date at 00:00, 00:05, ...).
 If that's not the case, then there's no guarantee that the merge is successful or working. 


---

The remainder (freqAI problem) strongly sounds like your informative data doesn't have sufficient history (it starts WAY after your train period). that'll obviously mean the data will be empty - and will therefore be removed.

ffill will NOT fix this - as your earliest datapoint will still be NaN.

**Comment by darioneto** [comment]
yeah you are right, the suffix was the thing, thanks much for taking the time
