### ISSUE TITLE
informative_pairs cannot be used when no history of upper timeframe 

### ISSUE THREAD

**Issue by Mengflz** [freqtrade/freqtrade#9166]
## Describe your environment

  * Operating system: linux
  * Python Version: 3.8.10 
  * CCXT version: 4.0.71
  * Freqtrade Version: 2023.8 
## Your question

I want to use @inforamtive to get upper timeframe information. But after I download 1m ochlv ETH/USDT data, I cannot use @inforamtive decorator to get the 5m information. Unless I download one day 5m ochlv ETH/USDT data. I don't know if I use it in a wrong way. 

I can use the sample strategy multi_tf.py in https://github.com/freqtrade/freqtrade-strategies/ as an example:

I run command "docker compose run --rm freqtrade backtesting --config user_data/config.json --strategy multi_tf --timerange 20230101-20230909 -i 1m" in my linux terminal. And its output was like:

<img width="1091" alt="image" src="https://github.com/freqtrade/freqtrade/assets/51097823/28fba465-e0eb-49d3-a20d-5b36ca075032">
<img width="1024" alt="image" src="https://github.com/freqtrade/freqtrade/assets/51097823/7e630e20-fdc3-45b2-a57b-12049a1645cd">

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
freqtrade will not auto-download data for you.

If your strategy requires 1m, 5m and 30m data, then please use the download-data command with the corresponding timeframes (you can use `download data -t 1m 5m 30m (...)`
