### ISSUE TITLE
Freqai repainting entries/exits

### ISSUE THREAD

**Issue by darioneto** [freqtrade/freqtrade#9174]
* Operating system: __Docker__
  * Python Version: ____Python 3.11.5
  * CCXT version: ___ccxt==4.0.81
  * Freqtrade Version: __docker-2023.9-dev-20cca01d
  
I'm not sure if this is expected to see freqai repainting entries/exits in frequi?
my config is set to train the model every 24 hours so this is when I would expect to see this change in the conditions thus repainting potentially could occur 
```
    "freqai": {
        "enabled": true,
        "fit_live_predictions_candles": 300,
        "noise_standard_deviation": 0.03,
        "save_backtest_models": true,
        "purge_old_models": 3,
        "train_period_days": 200,
        "data_kitchen_thread_count": 64,
        "activate_tensorboard": true,
        "backtest_period_days": 30,
        "live_retrain_hours": 24,
        "identifier": "hybrid_27",
        "feature_parameters": {
            "include_timeframes": [
                "5m",
                "15m",
                "30m",
                "1h"
            ],
            "include_corr_pairlist": [
            ],
            "label_period_candles": 24,
            "include_shifted_candles": 4,
            "DI_threshold": 0.9,
            "weight_factor": 0.9,
            "principal_component_analysis": false,
            "use_SVM_to_remove_outliers": true,
            "indicator_periods_candles": [
                5,
                10,
                20
            ],
            "plot_feature_importances": 12
        },
        "data_split_parameters": {
            "test_size": 0.2,
            "random_state": 42
        },
        "model_training_parameters": {
            "learning_rate": 0.1,
            "n_estimators": 150,
            "max_depth": 6,
            "subsample": 0.85,
            "colsample_bytree": 0.85,
            "objective": "reg:squarederror",
            "n_jobs": -1
        }
    },
```

the logs indicate on continues training though so would this be a contributing factor? No totally sure if this is expected to see repainting so frequently (few minutes after refresh I can see different point of entries)

```
2023-09-11 10:00:52 - freqtrade.freqai.freqai_interface - INFO - Total time spent inferencing pairlist 38.76 seconds
2023-09-11 10:00:52 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-2023.9-dev-20cca01d', state='RUNNING'
2023-09-11 10:01:32 - freqtrade.freqai.freqai_interface - INFO - Total time spent inferencing pairlist 39.16 seconds
2023-09-11 10:02:11 - freqtrade.freqai.freqai_interface - INFO - Total time spent inferencing pairlist 39.47 seconds
2023-09-11 10:02:11 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-2023.9-dev-20cca01d', state='RUNNING'
2023-09-11 10:02:50 - freqtrade.freqai.freqai_interface - INFO - Total time spent inferencing pairlist 38.81 seconds
```
just for illustration here the place where bot shorted during the event the signals were indicating short and few candles after, repainted long which would mean the bot would take long instead of short if the repainting came earlier?
The model is xboost regressor and reinforcement learning is not present. 

![image](https://github.com/freqtrade/freqtrade/assets/31065537/16732885-c822-45e2-8fc0-20e08a81da66)

**Comment by robcaulk** [comment]
I'm sorry, it is not clear to me what is wrong. I have not observed any entry repainting.

Can you please post a full log?

**Comment by robcaulk** [comment]
@xmatthias noticed that you are likely using `process_only_new_candles=False` which is not compatible with FreqAI. Please change this value to True.

**Comment by darioneto** [comment]
indeed, I wasn't aware process_only_new_candles is incompatible,  I changed to True and works so far. thanks a lot
