### ISSUE TITLE
Possible Hyperopt optimization

### ISSUE THREAD

**Issue by l3-J** [freqtrade/freqtrade#9176]
## Describe your environment

  * Operating system: Linux Debian
  * Python Version: python 3.9.2
  * CCXT version: ccxt==4.0.59
  * Freqtrade Version: freqtrade 2023.8.dev-4c5f99267
  
## Your question

Hi,

First of all, thanks you for this awesome software with a very useful documentation.

I recently started using freqtrade and tried to optimize strategies with Hyperopt.
I was surprise to find nothing about my question on the documentation.

I'm developing a complex trading system with multiple optional parameterizable indicators.
Something like explain in the doc (https://www.freqtrade.io/en/stable/hyperopt/#hyperoptable-parameters);
```
        conditions = []
        # GUARDS AND TRENDS
        if self.buy_adx_enabled.value:
            conditions.append(dataframe['adx'] > self.buy_adx.value)
        if self.buy_rsi_enabled.value:
            conditions.append(dataframe['rsi'] < self.buy_rsi.value)
```
My point is that it's not really relevant to backtest this strategy with all possible ADX values when ADX is disabled (and the same for RSI...)
Is there a way with freqtrade to describe rules between parameters in order to reduce parameter combinaison for hyperopt ?

Thanks

Regards

l3-J

**Comment by stash86** [comment]
short answer is no.

Slightly longer answer, don't optimize a lot of parameters at once. Hyperopt isn't as smart as you think it is.

**Comment by xmatthias** [comment]
scikit-optimize (the library used for hyperopt) does not support hierarchical spaces (which would be a neccessity to selectively optimize parameters depending on other parameters).
In fact, the search-space is not allowed to change during the optimization.

Because of this - it's also not possible for freqtrade to support this functionality.
