### ISSUE TITLE
Fibonacci calculation based on trade entry

### ISSUE THREAD

**Issue by erhangunay** [freqtrade/freqtrade#9178]
* Operating system: Windows 11
  * Python Version: 3.11.4
  * CCXT version: 4.0.36
  * Freqtrade Version: 2023.7, Docker
  
## Your question

Hello i am trying to calculate fibonacci retracements based on my entry and while in adjust trade position i can call trade object and get my entry so i have done the following:

    def adjust_trade_position(self, trade: Trade, current_time: datetime,
                              current_rate: float, current_profit: float,
                              min_stake: Optional[float], max_stake: float,
                              current_entry_rate: float, current_exit_rate: float,
                              current_entry_profit: float, current_exit_profit: float,
                              **kwargs) -> Optional[float]:
        pair = trade.pair
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        leverage = trade.leverage
        filled_entries = trade.select_filled_orders(trade.entry_side)
        count_of_entries = trade.nr_of_successful_entries
        trade_date = filled_entries[0].order_date_utc
        trade_candle = dataframe.loc[dataframe['date'] == trade_date]
        high = trade_candle['high'].tail(13*24).max()
        low = trade_candle['low'].tail(13*24).min()
        diff1 = (high - low) * 0.236
        diff2 = (high - low) * 0.382
        diff3 = (high - low) * 0.5
        diff4 = (high - low) * 0.618
        diff5 = (high - low) * 0.786
        threshold1 = low + diff1
        threshold2 = low + diff2
        threshold3 = low + diff3
        threshold4 = low + diff4
        threshold5 = low + diff5
        if trade.is_short:
            if current_rate >= threshold1 and count_of_entries==1:
                try:
                    # This returns first order stake size
                    stake_amount = filled_entries[0].cost
                    # This then calculates current safety order size
                    return stake_amount / leverage
                except Exception as exception:
                    return None
            if current_rate >= threshold2 and count_of_entries==2:
                try:
                    # This returns first order stake size
                    stake_amount = filled_entries[0].cost
                    # This then calculates current safety order size
                    return stake_amount / leverage
                except Exception as exception:
                    return None
            if current_rate >= threshold3 and count_of_entries==3:
                try:
                    # This returns first order stake size
                    stake_amount = filled_entries[0].cost
                    # This then calculates current safety order size
                    return stake_amount / leverage
                except Exception as exception:
                    return None
            if current_rate >= threshold4 and count_of_entries==4:
                try:
                    # This returns first order stake size
                    stake_amount = filled_entries[0].cost
                    # This then calculates current safety order size
                    return stake_amount / leverage
                except Exception as exception:
                    return None
            if current_rate >= threshold5 and count_of_entries==5:
                try:
                    # This returns first order stake size
                    stake_amount = filled_entries[0].cost
                    # This then calculates current safety order size
                    return stake_amount / leverage
                except Exception as exception:
                    return None
        if not trade.is_short:
            if current_rate <= threshold1 and count_of_entries==1:
                try:
                    # This returns first order stake size
                    stake_amount = filled_entries[0].cost
                    # This then calculates current safety order size
                    return stake_amount / leverage
                except Exception as exception:
                    return None
            if current_rate <= threshold2 and count_of_entries==2:
                try:
                    # This returns first order stake size
                    stake_amount = filled_entries[0].cost
                    # This then calculates current safety order size
                    return stake_amount / leverage
                except Exception as exception:
                    return None
            if current_rate <= threshold3 and count_of_entries==3:
                try:
                    # This returns first order stake size
                    stake_amount = filled_entries[0].cost
                    # This then calculates current safety order size
                    return stake_amount / leverage
                except Exception as exception:
                    return None
            if current_rate <= threshold4 and count_of_entries==4:
                try:
                    # This returns first order stake size
                    stake_amount = filled_entries[0].cost
                    # This then calculates current safety order size
                    return stake_amount / leverage
                except Exception as exception:
                    return None
            if current_rate <= threshold5 and count_of_entries==5:
                try:
                    # This returns first order stake size
                    stake_amount = filled_entries[0].cost
                    # This then calculates current safety order size
                    return stake_amount / leverage
                except Exception as exception:
                    return None
        return None

However when i try to put this in populate indicators (to see it on the graph and double check the calculation i could not manage it. So i tried to do it with dataframe instead, how can i convert dataframe to trade candle from previous example? (This is in live version)

Any other suggestions that can give me the same result is much appreciated, hope you help..

        high = dataframe['high'].tail(13*24).max()
        low = dataframe['low'].tail(13*24).min()
        diff1 = (high - low) * 0.236
        diff2 = (high - low) * 0.382
        diff3 = (high - low) * 0.5
        diff4 = (high - low) * 0.618
        diff5 = (high - low) * 0.786
        dataframe['threshold1'] = low + diff1
        dataframe['threshold2'] = low + diff2
        dataframe['threshold3'] = low + diff3
        dataframe['threshold4'] = low + diff4
        dataframe['threshold5'] = low + diff5
*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
well your code (`.tail()`) is looking at the very last rows. 
During backtesting, this is therefore a function that causes lookahead bias (if done within populate_indicators).

instead of using tail - better use `.rolling()` (arguments should be the same). that'll make this somewhat more agnostic.

Now the problem in `populate_indicators` is the anchor point, as the same calculation is done for every individual row).

Applying this same logic to the dataframe will therefore result in different values per row (potentially).

Now  unless you're in trade mode (live or dry) - you can't access the actual trade entry in populate_* methods (it'll simply be empty) - so you can't reliably draw this.

**Comment by erhangunay** [comment]
Hi Matthias,

I am in live mode actually. How can i access the first trade(of my dca) open date in populate indicators?

**Comment by xmatthias** [comment]
it's in the [documentation](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-trades).
How exactly you need to filter for your particular usecase is up to you to figure out, but i assume something like `..., pair=metadata['pair'], is_open=True` might work.

Please make sure to read and understand the warning box.

**Comment by erhangunay** [comment]
I have actually read that :/ However i could not get the date out from it..

believe me i have read all the website over and over again just to make sure i did not skip anything

**Comment by xmatthias** [comment]
well the date will be in the trade (object)
the response from that command is just a list of trade objects (most likely with 1 response) - where each element corresponds to what you get as `trade` argument in callbacks.

the initial date will therefore still be either `trade.open_date_utc` - or the corresponding command for the first order fill (which you already highlighted above).

**Comment by perkmeister** [comment]
`trade_candle` should only have one entry (assuming the open date is still in the dataframe), using tail or rolling on that makes no sense in your original code.
