### ISSUE TITLE
Trouble with Stochastic RSI

### ISSUE THREAD

**Issue by Johan1974** [freqtrade/freqtrade#9181]
## Describe your environment

  * Operating system: ubuntu 22
  * Python Version: 3.10.12
  * CCXT version: 4.0.58
  * Freqtrade Version: 2023.7
 
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I have been working a while now to get the stocjastic RSI to work. But it seems the calcluations are not working or i am doing something wrong. I like to hear. If i compare the values with my platform Bitvavo (They are using TradingView also) The numbers do not add up. My rule is to buy crossing over 20 and sell crossing under 80. I see lot of trades are bougth while the K and D line are nowhere near the 20 line. And for selling vice versa. Are there any good working examples available that behaves the same as in trading view. I do see a lot of NAN values, K or D with a 0 value or a 100 value. Or even K at a very low number and D with a very high number.  

Here is an example 

```
2023-09-12 14:54:34,895 - StochRSIStrategy - INFO - Current StochRSI K: 0.0
2023-09-12 14:54:34,896 - StochRSIStrategy - INFO - Previous StochRSI K: 99.99999999999942
2023-09-12 14:54:34,896 - StochRSIStrategy - INFO - Current StochRSI D: 54.80103923758677
2023-09-12 14:54:34,897 - StochRSIStrategy - INFO - Previous StochRSI D: 54.80103923758677

```

### Steps to reproduce:

This is my strategy at the moment

```
from freqtrade.strategy import IStrategy
from freqtrade.strategy import merge_informative_pair
from pandas import DataFrame
import talib.abstract as ta

import logging


logger = logging.getLogger(__name__)


class StochRSIStrategy(IStrategy):
    
    timeframe = "1h"
    stoploss = -100
    trailing_stop = True
    trailing_stop_positive = 0.01
    trailing_stop_positive_offset = 0.06
    trailing_only_offset_is_reached = True

    use_buy_signal = True
    use_exit_signal = True
    can_short = False

    minimal_roi = {}

    process_only_new_candles = True
    startup_candle_count: int = 200

    # Define the strategy indicators
    def informative_pairs(self):
        return [("BTC/EUR", "1d")]

    def log_debug_info(self, metadata, dataframe, signal_type, entry_signal, exit_signal):
        """
        Log debugging information for StochRSI.
        
        Args:
            metadata (dict): Metadata containing pair information.
            dataframe (DataFrame): The dataframe containing relevant data.
            signal_type (str): Either 'buy' or 'sell' to indicate the type of signal.
            entry_signal (DataFrame): The DataFrame containing entry signals.
            exit_signal (DataFrame): The DataFrame containing exit signals.
        """
        separator = "*" * 50
        logger.info(f"{separator} StochRSI Debug ({signal_type}) {separator}")
        logger.info(f"Pair: {metadata['pair']}")         
        logger.info("\nClose prices:\n" + str(dataframe["close"]))
        logger.info("\nRSI:\n" + str(dataframe['rsi']))
        logger.info(f"\nCurrent StochRSI K: {dataframe['k'].iloc[-1]}")
        logger.info(f"Previous StochRSI K: {dataframe['k'].iloc[-2]}")
        logger.info(f"\nCurrent StochRSI D: {dataframe['d'].iloc[-1]}")
        logger.info(f"Previous StochRSI D: {dataframe['d'].iloc[-2]}")
        logger.info(f"\nEntry Signal ({signal_type}):\n" + str(entry_signal))
        logger.info(f"Exit Signal ({signal_type}):\n" + str(exit_signal))
        logger.info(separator * 2)

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Use the same parameters as Bitvavo's StochRSI
        LengthRSI = 14
        LengthStoch = 14
        SmoothK = 3
        SmoothD = 3

        dataframe['rsi'] = ta.RSI(dataframe["close"], timeperiod=LengthRSI)

        # Calculate StochRSI with Bitvavo's parameters
        stochrsi = ta.STOCHRSI(dataframe, timeperiod=LengthStoch, fastk_period=SmoothK, fastd_period=SmoothD)

        dataframe['k'] = stochrsi['fastk']
        dataframe['d'] = stochrsi['fastd']

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Define your exit conditions here
        exit_condition_prev = (dataframe['k'].shift(1) < 20) | (dataframe['d'].shift(1) < 20)
        exit_condition = (
            (dataframe['k'] > 20)
            & (dataframe['k'] < 50)
            & (dataframe['d'] > 20)
            & (dataframe['d'] < 50)
        )
        
        # Check if both current and previous StochRSI K values are not 0.0
        valid_k_values = (dataframe['k'] != 0.0) & (dataframe['k'].shift(1) != 0.0)
        
        dataframe['enter_long'] = (exit_condition & exit_condition_prev & valid_k_values).astype(int)

        # Log debugging information for sell signal if an exit signal is made
        #if dataframe['enter_long'].sum() > 0:
        self.log_debug_info(metadata, dataframe, 'entry', str(dataframe['enter_long']), None)

        return dataframe

    

    

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Define your exit conditions here
        exit_condition_prev = (dataframe['k'].shift(1) > 80) | (dataframe['d'].shift(1) > 80)
        exit_condition = (
            (dataframe['k'] < 80)
            & (dataframe['k'] > 50)
            & (dataframe['d'] < 80)
            & (dataframe['d'] > 50)
        )
        
        # Check if both current and previous StochRSI K values are not 100
        valid_k_values = (dataframe['k'] != 100.0) & (dataframe['k'].shift(1) != 100.0)
        
        dataframe['exit_long'] = (exit_condition & exit_condition_prev & valid_k_values).astype(int)

        # Log debugging information for sell signal if an exit signal is made
        # if dataframe['exit_long'].sum() > 0:
        self.log_debug_info(metadata, dataframe, 'exit', None, str(dataframe['exit_long']))

        return dataframe
```
  
### Observed Results:

I have these numbers in freqtrade in this case (FET/EUR) pair
```
2023-09-12 15:00:52,512 - StochRSIStrategy - INFO - Current StochRSI K: 41.44890464038838
2023-09-12 15:00:52,512 - StochRSIStrategy - INFO - Previous StochRSI K: 7.092136605680606
2023-09-12 15:00:52,513 - StochRSIStrategy - INFO - Current StochRSI D: 49.51368041535623
2023-09-12 15:00:52,513 - StochRSIStrategy - INFO - Previous StochRSI D: 69.03071220189345

```

But when i look in TV the stochrsi is around and above the 80 line at that time.

### Relevant code exceptions or logs

Not sure if this has to do with the calculations but the open date is 2 hours of with me. So when freqtrade opentrade tells my 13:00 it is actually at 15:00. Allready set the zone to Amsterdam but this does not solve this.

Can you help me out here as i think this is a good indicator but i can not seem to get it to work properly with freqtrade.

Thanks,

Johan

**Comment by xmatthias** [comment]
we usually don't strive to have indicators align with tradingview (that's also difficult to accomplish), and as such, also don't provide active assistance for that.

Their implementation is
* usually not public
* often deviates from the original papers

on some indicators, they use different EMA methods (sometimes exotic, but at any rate, different to the ones ta-lib is using) - making it near impossible to match tradingview.
Now that's all theory / experience from other indicators, not necessarily tied to stoch RSI in particular - but the general concept is the same for all tradingview.


At any rate, i don't see this as freqtrade problem (anything we can help you with), but as an indicator problem - which (if you strive for alignment) - you should talk to the corresponding library repositories (though you'll might get similar responses, there).

(as a side note, pandas_ta aims to be tradingview-aligned - so you might want to look at using their implementation).

**Comment by Johan1974** [comment]
It does not have to be exactly like tradingview but at least near the same area. But i notice such big differences that is hard to work with to have a reliable strategy.  Also i was more curious about the experiences you have with this indicator and what options there are to improve this. Now you mentionen pandas i will most certainly take a look at this option and see if i can get better outcome. 

Any more suggestions are most welcome ! 

Thanks!
