### ISSUE TITLE
 fetch_positions() returned exception: "Could not get positions due to ExchangeError.“

### ISSUE THREAD

**Issue by shawnli957** [freqtrade/freqtrade#9185]
## Describe your environment

  * Operating system: __LInux__
  * Python Version: _3.9.16_ 
  * CCXT version: __3.0.37___ 
  * Freqtrade Version: __2023.3__ 
  * 
## Your question
Hi, today I just come up with this error, without modifying any code or settings:

> 023-09-14 15:04:09,562 - freqtrade.exchange.exchange - INFO - Using CCXT 3.0.48
> 2023-09-14 15:04:09,562 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'enableRateLimit': True}
> 2023-09-14 15:04:09,581 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'enableRateLimit': True, 'rateLimit': 100}
> 2023-09-14 15:04:09,601 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
> 2023-09-14 15:04:16,530 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
> 2023-09-14 15:04:16,963 - freqtrade.exchange.common - WARNING - fetch_positions() returned exception: "Could not get positions due to ExchangeError. Message: binance {"code":-5000,"msg":"GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk"}". Retrying still for 4 times.
> 2023-09-14 15:04:17,211 - freqtrade.exchange.common - WARNING - fetch_positions() returned exception: "Could not get positions due to ExchangeError. Message: binance {"code":-5000,"msg":"GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk"}". Retrying still for 3 times.
> 2023-09-14 15:04:17,462 - freqtrade.exchange.common - WARNING - fetch_positions() returned exception: "Could not get positions due to ExchangeError. Message: binance {"code":-5000,"msg":"GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk"}". Retrying still for 2 times.
> 2023-09-14 15:04:17,713 - freqtrade.exchange.common - WARNING - fetch_positions() returned exception: "Could not get positions due to ExchangeError. Message: binance {"code":-5000,"msg":"GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk"}". Retrying still for 1 times.
> 2023-09-14 15:04:17,965 - freqtrade.exchange.common - WARNING - fetch_positions() returned exception: "Could not get positions due to ExchangeError. Message: binance {"code":-5000,"msg":"GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk"}". Giving up.
> 2023-09-14 15:04:17,965 - freqtrade.commands.trade_commands - ERROR - Could not get positions due to ExchangeError. Message: binance {"code":-5000,"msg":"GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk"}
> 2023-09-14 15:04:17,965 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
> Traceback (most recent call last):
>   File "/home/ec2-user/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 627, in fetch
>     response.raise_for_status()
>   File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/positionRisk?timestamp=1694703856905&recvWindow=10000&signature=a1507e8f13ce1910970021502f9a72abf1d0fff9584801a552481ff0cc0a8406
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ec2-user/freqtrade/freqtrade/exchange/exchange.py", line 1418, in fetch_positions
>     positions: List[Dict] = self._api.fetch_positions(symbols)
>   File "/home/ec2-user/.local/lib/python3.9/site-packages/ccxt/binance.py", line 6293, in fetch_positions
>     return self.fetch_positions_risk(symbols, params)
>   File "/home/ec2-user/.local/lib/python3.9/site-packages/ccxt/binance.py", line 6408, in fetch_positions_risk
>     response = getattr(self, method)(self.extend(request, params))
>   File "/home/ec2-user/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 507, in inner
>     return entry(_self, **inner_kwargs)
>   File "/home/ec2-user/.local/lib/python3.9/site-packages/ccxt/binance.py", line 6927, in request
>     response = self.fetch2(path, api, method, params, headers, body, config, context)
>   File "/home/ec2-user/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2884, in fetch2
>     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
>   File "/home/ec2-user/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 643, in fetch
>     skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
>   File "/home/ec2-user/.local/lib/python3.9/site-packages/ccxt/binance.py", line 6906, in handle_errors
>     raise ExchangeError(feedback)
> ccxt.base.errors.ExchangeError: binance {"code":-5000,"msg":"GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk"}
>

**Comment by xmatthias** [comment]
Your version (as well as the corresponding ccxt versions) are outdated.
Binance retired this endpoint, and apparently hard-removed it this week.

Please update to a recent, supported version (2023.8). 
Please make sure to update following the [how to update](https://www.freqtrade.io/en/stable/updating/) guide to have corresponding dependencies (most importantly ccxt - but other mismatches can cause malfunctionings, too).

Also, make sure to read the changelogs for all intermediate versions (basically form 2023.3 up to 2023.8) to avoid being blind-sided by some deprecations, changes in behavior or breaking changes that happened between your version and the latest version.
You can find these on the [release page](https://github.com/freqtrade/freqtrade/releases).
