### ISSUE TITLE
Liquidation price after second buy in DCA strategy seems incorrect

### ISSUE THREAD

**Issue by juancaoviedo** [freqtrade/freqtrade#9205]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.11.5
  * CCXT version: I'm using last docker image, so, I guess is 4.0.88
  * Freqtrade Version: freqtrade docker-2023.9-dev-20cca01d
  * Docker compose - image: freqtradeorg/freqtrade:develop_plot
  
## Describe the problem:

I'm designing a DCA (Dollar-Cost Averaging) strategy for trading futures. The concept behind my idea is simple: I would break down my long entries into three DCA purchases if the price continued to decline after my initial entry. My strategy trigger the subsequent DCA entries prior to the liquidation price. Consequently, the strategy initiates the next DCA phase right before reaching the liquidation point of the preceding trades. Naturally, this involved calculating 'new entry prices' since new orders altered the trade's size and computing new liquidation values due to changes in the entry price.

I implemented a custom liquidation formula to determine the liquidation price and then compared it with the liquidation formula integrated into freqtrade. Initially, both formulas yielded similar liquidation prices after the first entry. However, after the first DCA entry, my formula's results and freqtrade's formula results differ. While I am inclined to assume that my formula may be wrong, I remain uncertain about the accuracy of freqtrade's liquidation price after the subsequent DCA order.

To illustrate my point, I would like to provide an example that I run in backtesting mode for the BTC/USDT pair using a leverage of 10x:

First entry snapshot:
```
current_time is: 2022-05-06 13:40:00+00:00
Trade open_rate is: 38207.1
Trade stake_amount is: 22.92426
Trade amount is: 0.006
current_rate is: 35396.6
Freqtrade liquidation_price is: 34708.61855421687
My own formula for liquidation_price is: 34733.72727272727
```

Second entry snapshot:
```
current_time is: 2022-05-06 13:45:00+00:00
Trade open_rate is: 35637.5
Trade stake_amount is: 249.4625
Trade amount is: 0.07
current_rate is: 35482.7
Freqtrade liquidation_price is: 35189.99869038655
My own formula for liquidation_price is: 32397.72727272728
```

As you can observe, the initial entry took place at 38,207.1, with a trade size of 0.006 BTC. The subsequent entry occurred at approximately 35,482.7, with a trade size of 0.064 BTC, resulting in an average entry price of 35,637.5 after the second buy.

However, when I apply my formula with an entry price of 35,637.5, it yields a liquidation price of 32,397.7, while the liquidation formula within freqtrade calculates a liquidation price of 35,189.9.

Upon verification using the Binance liquidation calculator, the resulting liquidation price is 31,613.4. This calculation utilizes the entry price and trade amount provided by the Trade object in freqtrade, along with the appropriate leverage for the margin wallet.

I use Binance exchange. So, I check the freqtrade's code for computing the liquidation price and it is an implementation of the Binance formula. Interestingly, the formula I implemented also uses the Binance formula, but both formulas produce different results.

I am inclined to consider that my formula may be wrong. However, when I compute the liquidation price after the second DCA using the Binance calculator, the binance calculator produces a different liquidation price than the liquidation price of freqtrade. The difference between the liquidation price of binance maybe arise because I made something wrong in entering the data to binance calculator. However, looking at the amount of the entries (the second entry is bigger than the first) and the average entry price after the second buy, the liquidation price seems too much close to the second average entry price. So, maybe there is something off in the calculation of the liquidation price when using the formula to compute the liquidation price after making some DCA entries. 

I would greatly appreciate any insights or guidance that someone could provide to shed light on this matter.

### Steps to reproduce:

  1. Use a DCA strategy for trading longs (I didn't test short positions). 
  2. Adjust stop loss to -1. 
  3. Create conditions for the next DCA entry if the trade is having negative profits. My particular conditions for the next DCA order are as follows: 
```
# Define conditions for next buy
condition_1 = current_profit < 0
condition_2 = current_rate > liquidation_price
condition_3 = current_rate < liquidation_price + liquidation_price*range_of_security_to_buy
```
  
### Observed Results:

  * What happened? 
  The liquidation price is too much close to the average entry price after the second DCA entry. 
  
  * What did you expect to happen? 
  I expected to have a much lower liquidation price. 

### Relevant code exceptions or logs

I already add some logs in the explanation of the error. There are no errors that brake the execution of the code, simply the computed price of the liquidation seems off. 

**Note:** I ask the question in discord and it was suggested there to create an issue, so, that is why I'm here. I know it adds extra work for developers and maitainers, but, it is a good idea to verify if it is actually a bug or not. Thanks a lot. 

Here is the screnshot of the binance calculator liquidation price result. 
<img width="400" alt="binance calculator" src="https://github.com/freqtrade/freqtrade/assets/44776372/d5bfc04e-c7c7-47c9-9226-d4dcc6a5d814">

**Comment by xmatthias** [comment]
I'm not entirely sure what you expect out of this. If your implementation is the same than the freqtrade one - why would results differ?


that said, to actually look at this, we'll need the actual trade object, so we can easily verify what happened without wasting time trying to reproduce your exact trade situation.


Please provide the output of the following command for the affected trade:
`freqtrade show-trades --db-url sqlite:///<trades.sqlite> --print-json --trade-ids <tradeid>` 
Please use a "details block" to keep the issue itself kindof readable (see below for details on how to do that). 

<details>
<summary>Expand to see how to do details blocks</summary>

```
<details>
<summary>Expand full </summary>
(wrap in tripple ticks `)
Trades output ...
</details>
```
</details>

**Comment by juancaoviedo** [comment]
I expect to clarify whether the liquidation formula of Freqtrade is accurate after the second DCA entry.

I was verifying, and despite both formulas being implemented the same way, the entries of the functions are not the same.

I'm adding a figure here called *entries_comparison.jpg.* This figure shows the comparison between the two entries. My liquidation formula takes the `open_rate` information from `trade.open_rate`, while the formula from Freqtrade takes the `open_rate` from `propose_rate`. `propose_rate` is computed using `get_valid_price_and_stake()` inside `backtesting.py`. However, `propose_rate` is also an entry to `get_valid_price_and_stake()`, specifically as the third entry.

`get_valid_price_and_stake()` receives in the third position (`propose_rate`) `row[OPEN_IDX]` as an entry. `get_valid_price_and_stake()` verifies if the order is a *limit* order. If the order is a *limit* order, it recomputes `propose_rate`; otherwise, it returns the same value as the entry (`row[OPEN_IDX]`).

So, the proposed rate for long positions is either `row[OPEN_IDX]` or `min(propose_rate, row[HIGH_IDX])`. This is fine because it computes the correct liquidation price when entering the trade for the first time (because it uses as an entry price for the trade a value that is close to the open price of the candle). However, when you are employing a DCA strategy, you should apply the liquidation formula considering that the entry price of the trade is the **right** entry price. It should look like this:

1. First entry: The entry price should be the entry price of the trade.
2. Second entry: The entry price should be the average of the first entry and the second entry (considering trade amounts).
3. Third entry: The entry price should be the average of the first, second, and third entries (considering trade amounts).
4. And so on.

That's why when I apply my formula, the entry rate for me is `trade.open_rate` because `trade.open_rate` is already the average entry price of all the orders made before. However, the Freqtrade liquidation formula uses `propose_rate` as open_rate, which, according to `get_valid_price_and_stake()`, is the open price of the candle and not the average of the preceding DCA orders.

However, I do not have enough knowledge about freqtrade, I'm just starting to see the codes under the hood, so, maybe there are things I do not understand, so, please excuse me if my reasoning is incorrect. But, based on my previous comments, maybe changing `propose_rate` by `trade.open_rate` in line 899 of *backtesting.py* (in develop branch) will solve the problem. However, as I said, maybe there are things that I still do not understand, so, please let me know if my analysis is incorrect. If my analysis is incorrect, I will continue searching for the possible error. 

Thanks, 


![entries_comparison](https://github.com/freqtrade/freqtrade/assets/44776372/62912635-fab9-4377-a4e1-904565de7a8d)

**Comment by xmatthias** [comment]
While you write a lot of text, trying to make your point - there's nothing allowing for a simple reproduction, making the whole explanation kinda pointless.
Also, posting screenshots of code is VERY bad practice. if you intend to post code - post it as code. Otherwise, it's irrelevant (I've got better things to do than to copy text from your screenshots).

I've asked above for the output of `freqtrade show-trades ` - which was ignored.

As you seem to talk about backtesting, please provide a minimal strategy that reproduces this (including the command to run and eventual config to show this behavior).
if i'm wrong, and we talk about live / trade mode, the request for `freqtrade show-trades ` remains.

**Failing to provide either will mean i'll close this issue as invalid** - as i do NOT intend to waste my time trying to reproduce your issue (i'm more than happy investigating - but trying to reproduce things without clear path is a waste - as it'll never be clear if my reproduction would show what you intend to explain).

thanks for your understanding.

**Comment by juancaoviedo** [comment]
I'm refering to backtesting. 

I will summarize my last comment and provide what you are asking for. 

1. Liquidation price should be computed from the entry price of the trade. 
2. When doing DCA, the entry price of the trade change with each DCA entry. 
3. Liquidations after first DCA should be computed with "new" entry prices. 
4. **Line 899 of backtesting.py in develop branch is wrong**. Now looks like this: 

```
trade.set_liquidation_price(self.exchange.get_liquidation_price(
    ...
    open_rate=propose_rate,
    ...
))
```
**It should look like this**: 
```
trade.set_liquidation_price(self.exchange.get_liquidation_price(
    ...
    open_rate=trade.open_rate,
    ...
))
```

My previous comment explains why that change needs to be done. 

Here is the code for a sample working strategy. 

```
# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement
# flake8: noqa: F401
# isort: skip_file
# --- Do not remove these libs ---
import numpy as np  # noqa
import pandas as pd  # noqa
import datetime
from pandas import DataFrame
from typing import List, Optional, Tuple, Union

from freqtrade.strategy import (BooleanParameter, CategoricalParameter, DecimalParameter,
                                IStrategy, IntParameter)

# --------------------------------
# Add your lib to import here
import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib

import pandas_ta as pandas_ta
from freqtrade.persistence import Trade
from freqtrade.strategy import IntParameter, IStrategy, stoploss_from_open
from technical.util import resample_to_interval, resampled_merge

class Example_DCA(IStrategy):
    INTERFACE_VERSION = 3
    # DCA config
    position_adjustment_enable = True
    max_dca_entries = 4
    custom_info = { }
    DATESTAMP = 0
    
    # Strategy configuration
    leverage_opt = 50
    minimal_roi = {"0": 10}
    stoploss = -1  # 10% stop loss
    use_custom_stoploss = False
    trailing_stop = False  
    timeframe = "1h"
    process_only_new_candles = True
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False
    can_short: bool = False
    startup_candle_count: int = 55
    order_time_in_force = {"entry": "GTC", "exit": "GTC"}
    order_types = {
        "entry": "limit",
        "exit": "limit",
        "stoploss": "limit",
        "stoploss_on_exchange": True,
        "stoploss_on_exchange_interval": 180,
        "stoploss_on_exchange_limit_ratio": 0.96,
    }
    plot_config = {
        "main_plot": {
            # Plot EMAs
            "ema_fast": {"color": "orange"},
            "ema_slow": {"color": "blue"},
        },
    }
    def populate_indicators(self, dataframe, metadata):
        pair = metadata['pair']
        if pair not in self.custom_info:
            # Create initial default entry for this pair {DATESTAMP}
            self.custom_info[pair] = [''] 

        # Calculate EMA indicators
        dataframe['ema_fast'] = ta.EMA(dataframe, timeperiod=10)
        dataframe['ema_slow'] = ta.EMA(dataframe, timeperiod=55)
        
        return dataframe

    def populate_entry_trend(self, dataframe, metadata):
        # Generate long entry signal
        dataframe.loc[
            (dataframe['ema_fast'] < dataframe['ema_slow']) &
            (dataframe['ema_fast'].shift(1) >= dataframe['ema_slow'].shift(1)),
            'buy'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe, metadata):
        # Generate exit signal
        dataframe.loc[
            (dataframe['ema_fast'] > dataframe['ema_slow']) &
            (dataframe['ema_fast'].shift(1) <= dataframe['ema_slow'].shift(1)),
            'sell'] = 1

        return dataframe

    def custom_stake_amount(self, pair: str, current_time: datetime, current_rate: float,
                                proposed_stake: float, min_stake: Optional[float], max_stake: float,
                                leverage: float, entry_tag: Optional[str], side: str,
                                **kwargs) -> None | float:
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        
        # If starting the backtesting then return None
        if(len(dataframe) < 1): 
            return None
        
        # Assign last position in dataframe to the last candle
        last_candle = dataframe.iloc[-1].squeeze()

        # store date of current candle in custom dict
        self.custom_info[pair][self.DATESTAMP] = last_candle['date']
        
        # Define the custom size entry
        custom_size = proposed_stake / self.max_dca_entries

        return custom_size

    def adjust_trade_position(self, trade: Trade, current_time: datetime,
                                current_rate: float, current_profit: float,
                                min_stake: Optional[float], max_stake: float,
                                current_entry_rate: float, current_exit_rate: float,
                                current_entry_profit: float, current_exit_profit: float,
                                **kwargs) -> Optional[float]:
        # Define the pair
        pair = trade.pair

        # Create the dataframe pair
        dataframe_pair, _ = self.dp.get_analyzed_dataframe(trade.pair, self.timeframe)
        
        # If starting the backtesting then return None
        if(len(dataframe_pair) < 1): 
            return None
        
        # Assign last position in dataframe to the last candle
        last_candle = dataframe_pair.iloc[-1].squeeze()

        # Select the filled orders
        filled_entries = trade.select_filled_orders(trade.entry_side)
        
        # Count the number of entries
        count_of_entries = trade.nr_of_successful_entries

        liquidation_price = self.compute_liquidation_price_my_own_formula(trade)
        if current_time.day in [10] and  (current_time.hour in [23]):
            print(f"\ncurrent_time is: {current_time}")
            print(f"trade.open_rate is: {trade.open_rate}")
            print(f"current_rate is: {current_rate}")
            print(f"Freqtrade liquidation_price is: {trade.liquidation_price}")
            print(f"My own formula for liquidation_price is: {liquidation_price}")
            input("Press enter to continue...")

        if(self.custom_info[pair][self.DATESTAMP] != last_candle['date']):
            # only run if new candle, and store current candle date in the dict
            self.custom_info[pair][self.DATESTAMP] = last_candle['date']
            # only run if less than or equal to maximum allowed number of entries
            if 0 < count_of_entries <= self.max_dca_entries:        
                # Compute liquidation price according to:
                liquidation_price = self.compute_liquidation_price_my_own_formula(trade)

                # Define security margins to avoid liquidation
                # range_of_security_for_liquidation_fees = 0.05
                range_of_security_to_buy = 0.2
                
                # Define conditions for next buy
                condition_1 = current_profit < 0
                condition_2 = current_rate > liquidation_price
                condition_3 = current_rate < liquidation_price + liquidation_price*range_of_security_to_buy
                # TODO: Verify my own liquidation formula and the liquidation formula from freqtrade to see which one is rigth. 

                if condition_1 and condition_2 and condition_3:
                    try:
                        # This returns first order stake size
                        stake_amount = filled_entries[0].cost
                        print("\nAll conditions are met!")
                        print(f"\ncurrent_time is: {current_time}")
                        # print(f"trade.open_rate is: {trade.open_rate}")
                        print(f"current_rate is: {current_rate}")
                        # print(f"Freqtrade liquidation_price is: {trade.liquidation_price}")
                        # print(f"My own formula for liquidation_price is: {liquidation_price}")
                        input("Press enter to continue...")
                        return stake_amount
                    except Exception as exception:
                        return None    
                    
        return None

    def leverage(
        self,
        pair: str,
        current_time: datetime,
        current_rate: float,
        proposed_leverage: float,
        max_leverage: float,
        entry_tag: Optional[str],
        side: str,
        **kwargs,
    ) -> float:

        return self.leverage_opt
    
    def compute_liquidation_price_my_own_formula(self, trade):
        amount =  trade.amount # Equivalent to Position_1_BOTH in binance formula
        mm_ratio = 0.004 # Equivalent to MMR_B in binance formula
        open_rate =  trade.open_rate # Equivalent to EP_1_BOTH in binance formula
        wallet_balance = trade.stake_amount # Equivalent to WB in binance formula
        liquidation_price = (wallet_balance-amount*open_rate)/(amount*mm_ratio-amount)
        return liquidation_price
```

Here is the configuration json file:
```
{
    "max_open_trades": 10,
    "stake_currency": "USDT",
    "stake_amount": 100,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 5000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [    
            "BTC/USDT:USDT",
        ],
        "pair_blacklist": [
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList",
        }
    ],
    "telegram": {
        "enabled": ,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "",
        "ws_token": "",
        "CORS_origins": [],
        "username": "",
        "password": ""
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

```

Here is the command I use to run the backtesting. 
```
docker-compose run --rm freqtrade backtesting --config ./user_data/config.json --strategy Example_DCA --timerange 20220408-20220414
```

Here is the backtest results:
```
{"strategy":{"Example_DCA":{"trades":[{"pair":"BTC/USDT:USDT","stake_amount":1244.570782,"max_stake_amount":62228.5391,"amount":1.484,
"open_date":"2022-04-10 23:00:00+00:00","close_date":"2022-04-11 03:00:00+00:00","open_rate":41932.977830188676,"close_rate":42089.02612118577,
"fee_open":0.0002,"fee_close":0.0002,"trade_duration":240,"profit_ratio":0.1659935125127058,"profit_abs":206.63199381,"exit_reason":"liquidation",
"initial_stop_loss_abs":41245.7,"initial_stop_loss_ratio":-1.0,"stop_loss_abs":41245.7,"stop_loss_ratio":-1.0,"min_rate":41650.0,"max_rate":42399.9,
"is_open":false,"enter_tag":null,"leverage":50,"is_short":false,"open_timestamp":1649631600000,"close_timestamp":1649646000000,"orders":[
{"amount":0.029,"safe_price":42087.4,"ft_order_side":"buy","order_filled_timestamp":1649631600000,"ft_is_entry":true},
{"amount":1.455,"safe_price":41929.9,"ft_order_side":"buy","order_filled_timestamp":1649646000000,"ft_is_entry":true},
{"amount":1.484,"safe_price":42089.02612118577,"ft_order_side":"sell","order_filled_timestamp":1649646000000,"ft_is_entry":false}]}]
```

Backtest results are wrong:

First entry at 42087.4 produced liquidation price of 41445.1. 
Second entry produced a "new" entry price of  41932.9, which produced a liquidation price of 42089.0. 
Second liquidation price with an entry price of 41932.9 and a combined amount of 1.484 **should produce a liquidation price of 41264, not a liquidation price of 42089.02**, which was the one that trigger the exit from the trade (see "exit_reason":"liquidation"). 

**If anything else is required from my side please let me know. I know your time as the main developer is limited, but I'm just trying to help here.**

**Comment by perkmeister** [comment]
I'm wondering whether `trade.open_rate` is the right thing to use, this doesn't change with a partial sell so doesn't actually represent the 'average entry price' as such (i.e. the break even price). It does for DCA buys only.

**Comment by juancaoviedo** [comment]
I believe that only increases in trade amount modify the entry price (increase either long or short size). Decreases in trade amount do not modify the entry price of the trade (selling a part of the position do not modify entry price, at least in binance). 

I don't know exactly what `trade.open_rate` reflects. But if `trade.open_rate` reflects the average of the entries (**considering the quantities bought in each order**) then it will be the correct value for calculating the new liquidation price.

**Comment by perkmeister** [comment]
Yes, you're right. The method of calculating average price (i.e. `open rate`) when you have partial sells in the mix has always seemed a little counter intuitive to me but the maths do work out (it's not just summing the amounts bought and sold and the associated prices it bought and sold at , it involves using average price instead of sold at price for sells). Forget what I said then  ;)

**Comment by xmatthias** [comment]
@juancaoviedo if using position adjustments, you should familiarize yourself with the [calculations](https://www.freqtrade.io/en/latest/strategy-callbacks/#position-adjust-calculations).

That said, it's exactly what you say - it's a weighted average over all entries - with exits not modifying the entry price.
Will try to look at this soonish.

**Comment by perkmeister** [comment]
Well it's not quite that simple. Take the example:
```
    Buy 100@8$
    Buy 100@9$ -> Avg price: 8.5$
    Sell 100@10$ -> Avg price: 8.5$, realized profit 150$, 17.65%
    Buy 150@11$ -> Avg price: 10$, realized profit 150$, 17.65%
    Sell 100@12$ -> Avg price: 10$, total realized profit 350$, 20%
    Sell 150@14$ -> Avg price: 10$, total realized profit 950$, 40% <- This will be the last "Exit" message
```
If you just used weighted average over entries you'd conclude the average price after the third buy would be
```
((100*8)+(100*9)+(150*11))/(100+100+150) = 9.57
```
In fact the average price is 10.

**Comment by juancaoviedo** [comment]
Indeed, the weighted average of the entries should take into account the current invested amount (after partial sales). However, in line 1069 of `/persistence/trade_model.py`, the `open_rate` is recomputed using `current_stake` as follows:

```python
self.open_rate = float(current_stake / current_amount)
```

Additionally, `current_stake` is recalculated in line 1037 in the same file:

```python
current_stake += price * tmp_amount * side
```

This operation is performed for each order inside `self.orders`. Moreover, line 1037 takes into consideration the `side`. Therefore, my assumption is that `current_stake` already includes the partial sales. Also, I believe that `tmp_amount` contains the amount. Thus, `self.open_rate = float(current_stake / current_amount)` should precisely compute what we require, which is the weighted average entry price, accounting for partial sales.

P.S. Upon reviewing the code, I'm truly impressed by the amount of work that has gone into it. Cheers to you friends! remarkable effort!

**Comment by xmatthias** [comment]
Should be fixed in the latest develop (also added a test in the commit prior to the fix).

It wasn't just the value that needed adjustment though - you can't adjust the liquidation price until the order actually fills - and open_rate is recalculated, otherwise you'd be trailing with open-rate by one order (once the 3rd order is set, we'd set the liquidation price in accordance to the 2nd order).

**Comment by juancaoviedo** [comment]
Awesome! I'll make some tests from my side!

Thanks a lot!

**Comment by perkmeister** [comment]
Yes, the formula `current_stake += price * tmp_amount * side` takes into account partial sells, but note that `tmp_amount` is the safe price for buys (the price bought), and is the current average price for sells.

**Comment by juancaoviedo** [comment]
Hi,

I was trying to run some tests and I realized that it would be much easier to have the "new" liquidation price after each new DCA trade inside the `orders` section of the results in the backtesting. Something like this:

```
{"strategy": {"Scalping_V5": {"trades": [
{"pair": "BTC/USDT:USDT", "other_results", 
"orders": [
{"other_results": ..., "liquidation_price": last_liquidation_price},
]
```

So, I try to do it my self and this is what I did:

I checked the classes `Order`, `LocalTrade`, and `Trade` inside the "persistence/trade_model.py" file.

It seems that the `Order` class uses the function `to_json` to build the JSON outputs of the backtesting. The function `to_json(self, entry_side: str, minified: bool = False)` has an input called `minified`. So, maybe I can add the liquidation price in the attributes that are saved in the backtest results when "minified" alternative is chosen. However, it seems that the liquidation price is assigned to the `LocalTrade` object (using the `get_liquidation_price` function) instead of the `Order` object.

So, I copy paste the same function that `LocalTrade` has inside the `Order` class: 
```
    # Add liquidation price for each order (Useful when using DCA strategies)
    def set_liquidation_price(self, liquidation_price: Optional[float]):
        """
        Method you should use to set self.liquidation price.
        Assures stop_loss is not passed the liquidation price
        """
        if not liquidation_price:
            return
        self.liquidation_price = liquidation_price
```
Afterward, I copy paste the same code that xmathias did to update the liquidation of the trade, to add it to the order, like this: 
```
    def _try_close_open_order(
            self, order: Optional[Order], trade: LocalTrade, current_date: datetime,
            row: Tuple) -> bool:
        """
        Check if an order is open and if it should've filled.
        :return:  True if the order filled.
        """
        if order and self._get_order_filled(order.ft_price, row):
            order.close_bt_order(current_date, trade)
            if not (order.ft_order_side == trade.exit_side and order.safe_amount == trade.amount):
                # Compute liquidation price
                liquidation_price = self.exchange.get_liquidation_price(
                    pair=trade.pair,
                    open_rate=trade.open_rate,
                    is_short=trade.is_short,
                    amount=trade.amount,
                    stake_amount=trade.stake_amount,
                    leverage=trade.leverage,
                    wallet_balance=trade.stake_amount,
                )
                # Assign liquidation price to the LocalTrade and Order objects
                trade.set_liquidation_price(liquidation_price)
                order.set_liquidation_price(liquidation_price)

                # Adjust stop loss
                self._call_adjust_stop(current_date, trade, order.ft_price)
                # pass
            return True
        return False
```

After adding that code, the order object is updated. However, the last order is not computing the liquidation price. How to compute liquidation price for the order when the order is closed? 

Thanks,

**Comment by xmatthias** [comment]
i don't really see why having the liquidation price on the order object would make sense.
it's information that's only relevant at that moment - trying to persist it will blow up the backtest (and hyperopt) outputs for no good reason.

That said - the last order will not calculate the liquidation price - as that price would be either 0.0, or indefinitely high - as you're no longer in a position that could be liquidated.

**Comment by juancaoviedo** [comment]
I wanted to "print" the liquidation price (in the results of backtesting) inside the order object just to make easier the verification process of how the liquidations were computed after each order (I wanted to do it manually to improve my strat). Thanks to your information I realize that the last order is the "sell" order for the previous "long" entries, so, yes, there is no liquidation price for that order. 

Thanks for the information, I will not push nor create merge request for the codes I have made.

Thanks
