### ISSUE TITLE
Does support  Huobi.pro?

### ISSUE THREAD

**Issue by yaotian** [freqtrade/freqtrade#921]
## Step 1: Have you search for this issue before posting it?
Yes

## Step 2: Describe your environment
n/a
  
## Step 3: Describe the problem:
Does freqtrade support Huobi.pro, the most popular exchanges ?
Ccxt already supports Huobi.pro API.
The Huobi API doc link is https://github.com/huobiapi/API_Docs_en/wiki

**Comment by hashtagex** [comment]
I have tried without succes. Can't figure it our on my own at least. would be really awesome to have.

**Comment by xmatthias** [comment]
technically, it should work in theory, however at the moment we only support bittrex and binance officially.

Feel free to try and post eventual errors, we can try to help (but don't be upset if it simply does not work) as you're probably the first to try...

@hashtagex what problems did you encounter?

**Comment by yaotian** [comment]
@xmatthias Only enable debug, you can see after launch it, freqTrade is downloading data of time range for a long long time...

**Comment by yaotian** [comment]
@xmatthias I got some clues.
huobipro
Downloaded data for BTC/USDT time range [2018-06-16 14:42:00+00:00, 2018-06-15 22:03:00+00:00]

binance
Downloaded data for BTC/USDT time range [2018-06-15 22:08:00+00:00, 2018-06-16 14:47:00+00:00]

It seems huobipro got wrong time range: starttime is after endtime...

**Comment by xmatthias** [comment]
are you on the latest version?
i'm asking because it got a `sorted` builtin which should cover / fix this problem ...

https://github.com/freqtrade/freqtrade/blob/934974a54700858a3ca979e59d8cbed292677f83/freqtrade/exchange/__init__.py#L297-L310

**Comment by hashtagex** [comment]
Actually. I'm an idiot haha. I used huobi instead of huobipro. I'll run it and see what issues come up. Only one I know of is that it does not support dynamic-whitelist, something about exchange does not support it. I'll send the debug.

**Comment by yaotian** [comment]
I see. It was fixed in the new version. Close the issue.
