### ISSUE TITLE
What are some recommendations for using HyperOpt?

### ISSUE THREAD

**Issue by maksam07** [freqtrade/freqtrade#9212]
Hi everyone, I'm learning the data project little by little and discovering more and more information, including reaching hyperopt, but I don't fully understand how to use it to get better results.

On what amount of data is it better to use it for fast or long term income? 
In what sequence and which commands are best to use?
Which out-of-the-box strategies are still relevant now because they haven't been updated in a while?

My use case is to use a team like this:
```
docker compose run --rm freqtrade hyperopt -c * -s * --hyperopt-loss SharpeHyperOptLossDaily -e 500 --timerange 20230801- --min-trades 100
```
I can run this command several times and get different results, but I don't understand if they are better than the previous ones or if these miscalculations start from scratch and some of the past miscalculations might be better?
I may not understand everything in the documentation, so I wouldn't mind if you could explain a bit more or share some reading material. Thanks

**Comment by stash86** [comment]
Hyperopt is just series of backtesting. Important thing to note (taken from the docs)

```
In general, the search for best parameters starts with a few random combinations (see below for more details) and then uses Bayesian search with a ML regressor algorithm (currently ExtraTreesRegressor) to quickly find a combination of parameters in the search hyperspace that minimizes the value of the loss function.
```

What you need to do is create your own loss function that suits your preference.

**Comment by xmatthias** [comment]
The expression of "better" or worse in this context can vary wildly
some prefer high profits, other smaller drawdown (less risk).

Freqtrade includes a few [loss functions](https://www.freqtrade.io/en/latest/hyperopt/#loss-functions) for different scenarios - but it'll most likely not cover exact desires.
It's however pretty simple to develop [your own loss function](https://www.freqtrade.io/en/latest/advanced-hyperopt/#creating-and-using-a-custom-loss-function) - which has it's own rules to determine "better" or "worse" - based on your personal preferences.
