### ISSUE TITLE
Can this be used with a sentiment analysis trading bot?

### ISSUE THREAD

**Issue by bhuwan1998** [freqtrade/freqtrade#9215]
I have been looking for a way to simulate the market so that I can use my trading bot and check the trading strategy. I have not gone through all the documentation of this project. I was wondering if I can use this simulator for my purpose. Any suggestions or hints would be helpful.

**Comment by stash86** [comment]
`I have not gone through all the documentation of this project.`

Please do so before asking. Freqtrade can do backtest. Whether your bot can use it or not, we won't know. We can't read your mind. We don't even know in what language your bot is written. Read the docs and judge it yourself whether Freqtrade is suitable for your own bot or not.
