### ISSUE TITLE
Freqtrade optimizes specified parameters

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9216]
Can Freqtrade optimize specific parameters? For example, in the code below, I want to optimize the values in key-value pairs while keeping the keys unchanged:

minimal_roi = {
    "0": 0.21,
    "355": 0.157,
    "883": 0.074,
    "1336": 0
}

Thank you.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.


---

Please also use the documentation to see if this is already documented.

while it's not pre-defined automatically - you can accomplish this by overriding the [pre-defined space](https://www.freqtrade.io/en/latest/advanced-hyperopt/#overriding-pre-defined-spaces).

It's not exactly the way you need - but the example is there to be modified :)
