### ISSUE TITLE
How to buy a trading pair only once

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9236]
## Describe your environment

  * Operating system: **ubuntu 20.4**
  * Python Version: **3.8**
  * CCXT version: **4.0.89**
  * Freqtrade Version: **freqtrade 2023.8**
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hello, I have deployed freqtrade on Ubuntu and I am currently running live trading with a small amount of capital. However, I noticed that it sometimes repeatedly buys the same trading pair during the buy orders. I have two questions:

How can I set it to buy a trading pair only once?
Does it also allow multiple repeated buy orders by default during backtesting?

Thanks.

**Comment by stash86** [comment]
First off, please read and understand the strategy. Seems like you just pick a strategy online and run it live. Good recipe to lose money quickly.

Second, set `position_adjustment_enable` to False in the strategy to turn off any additional entries.

**Comment by WinPoss** [comment]
Okay, thank you for your advice. I will research it first and then make a firm offer.
