### ISSUE TITLE
How to buy a trading pair only once

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9237]
## Describe your environment

  * Operating system: ubuntu 20.4
  * Python Version: 3.8
  * CCXT version: 4.0.17
  * Freqtrade Version: 2023.8
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hello everyone, I have deployed freqtrade on Ubuntu and performed hundreds of backtests on my strategy. I am currently in the stage of live trading with a small amount of funds. However, I have noticed an unexpected behavior of my strategy in live trading:

It repeatedly buys the same trading pair multiple times.

The desired behavior we aim to achieve is as follows: for a trading pair, it should only be bought once when the buy signal conditions are met. In other words, if there is already a position or there are pending orders (including buy and sell orders), it should not be bought again.

I have tried adding the following to the config.json file:
`"position_adjustment_enable": false`

I have also added the following in the strategy file:
`position_adjustment_enable = False`

However, the test results still show repeated buy orders.

Then I came up with an idea: to check in the `populate_entry_trend` function of the strategy whether the trading pair is already in a position, or if there are any pending buy or sell orders, and then decide whether to execute a buy order.

But after going through the official documentation multiple times: [freqtrade documentation](https://www.freqtrade.io/en/stable/strategy-customization/), it seems that I need some functions for querying position/order information.

So, could you please help me with some guidance? How can I achieve the objective of buying each trading pair only once?

Thank you so much in advance!

**Comment by stash86** [comment]
upload your strategy and config

**Comment by leechee** [comment]
Sorry, I have only recently used git, and I can't seem to find the entrance to upload files?

**Comment by WinPoss** [comment]
[upload.zip](https://github.com/freqtrade/freqtrade/files/12747351/upload.zip)
this, pls

**Comment by WinPoss** [comment]
Can we set `max_entry_position_adjustment` to 0? This way, after buying once for each trading pair, there won't be any additional buy operations, right?

config.json file:
`"max_entry_position_adjustment": 0`

**Comment by xmatthias** [comment]
Your strategy doesn't do / implement position adjustments - so it's impossible to have more than one entry per pair.

What exactly makes you think that freqtrade is doing more than one buy per pair (before closing the trade)?

**Comment by WinPoss** [comment]
Now I'm thinking, could it be possible that the issue occurred because I previously used this command:

`docker-compose run freqtrade trade -c user_data/config.json --strategy BeautifulGain`

This might have caused multiple instances of the bot to run in the background.

Currently, I'm experiencing issues with the buy, sell, and Telegram message display functionalities.

Due to the time zone difference in our region, it's late at night now. Tomorrow, I will reinstall the Ubuntu system, set up freqtrade on a clean server, document the deployment process, and then run the bot again to see if the issue persists.

Thank you for your response!

**Comment by xmatthias** [comment]
if you're using docker - you can use `docker ps` to see running containers.

you can then stop them with either `docker compose down` - or with `docker stop <containerid>` - and `docker rm <containerid>`.

Also, do NOT use `docker compose run ...` to start a bot in trade mode. 
Instead, update the startup command in the docker-compose.yml file - and use `docker compose up`. 
This will 
* ensure only one instance is running
* properly mount specified mountpoints and ports

**Comment by WinPoss** [comment]
Yesterday, I redeployed freqtrade and bought 5 trading pairs. So far, I haven't noticed any duplicate purchases.

However, when I run the commands /daily and /monthly on Telegram, no data is displayed (running /status table and /profit commands works fine):

```
/profit 

No closed trade 
ROI: All trades
∙ 1.374 USDT (0.92%) (0.84 Σ%)
∙ 1.374 USD
Total Trade Count: 5
Bot started: 2023-09-29 02:28:23
First Trade opened: 21 hours ago (2023-09-29 02:28:27)
Latest Trade opened: 21 hours ago (2023-09-29 02:28:33)
Win / Loss: 0 / 0
Winrate: 0.00%
Expectancy (Ratio): 0.00 (100.00)
Updated: Sat Sep 30 00:18:36 2023

```
```
/daily

Daily Profit over the last 7 days:
Day (count)     USDT    USD       Profit %
--------------  ------  --------  ----------
2023-09-30 (0)  0 USDT  0.00 USD  0.00%
2023-09-29 (0)  0 USDT  0.00 USD  0.00%
2023-09-28 (0)  0 USDT  0.00 USD  0.00%
2023-09-27 (0)  0 USDT  0.00 USD  0.00%
2023-09-26 (0)  0 USDT  0.00 USD  0.00%
2023-09-25 (0)  0 USDT  0.00 USD  0.00%
2023-09-24 (0)  0 USDT  0.00 USD  0.00%
Updated: Sat Sep 30 00:18:40 2023
```

Therefore, I would like to ask if there is a specific parameter that needs to be configured in order to display the data for /daily and /monthly commands. 

Currently, I am using the default configuration settings

```
"telegram": {
        "enabled": true,
        "token": "my_telegram_token",
        "chat_id": "my_telegram_chat_id"
    },
```

Thank you.

**Comment by xmatthias** [comment]
`/daily` and `/monthly` will display data for closed trades.

As you re-deployed - i assume you restarted with an empty database - which means there will be no closed trades yet.
