### ISSUE TITLE
How frequently adjust_trade_position() is called?

### ISSUE THREAD

**Issue by soleiljy** [freqtrade/freqtrade#9238]
Hi,

According to https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position, 

_adjust_trade_position() is called very **frequently** for the duration of a trade, so you must keep your implementation as performant as possible._

How frequently is it called? In my case, I'm using an 1-minute timeframe strategy, and internals.process_throttle_secs is set to 3 seconds. 

Thanks!

**Comment by stash86** [comment]
Every throttle secs, which in your case is 3 secs

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

every `internals.process_throttle_secs` - yes - but see this as the minimum, not a guaranteed value. 
if you have 5 open orders on 5 open trades - then you'll most likely NOT be getting an iteration time of 3s.

If one iteration takes less than the 3s, then the bot will sleep for the remaining seconds (unless it's right before a new candle, where the new candle timestamp will mark the "sleep end").

If one iteration is > 3s - it'll simply continue. If this is then 4s, or 20s (or more) - will solely depend on your strategy, open trades, pairlist length, your exchange (ratelimits) - and maybe even system load.
