### ISSUE TITLE
Concerning lookahead-analysis

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#9240]
## Describe your environment

  * Operating system: Linux mint una
  * Python Version: 3.10.4
  * CCXT version: 4.0.76
  * Freqtrade Version: 2023.8
  
## Your question
Is it by default that lookahead-analysis brings up bias when a dataframe is shifted by -x? My indicator looks like this:
dataframe['close'].shift(-1).pct_change() and out of 20 others this is the only one flagged as bias. The strategy works most of the time. But I am worried about how it develops in future.

**Comment by xmatthias** [comment]
i'm ... not entirely sure what answer you're expecting here.

you're **explicitly** using the first (!) point of the [common strategy mistakes](https://www.freqtrade.io/en/latest/strategy-customization/#common-mistakes-when-developing-strategies).
this IS a very bias (no need for any command) - and will _never_ have the very last row of a dataframe populated.

you look into the future (even if only by one candle) - so every signal that's calculated based on this this cannot show up at the very last candle - which means a live bot will ignore it (backtesting will work fine - but live will ignore these signals, as they can only show up once the candle is the 2nd to last).

As an example ...
![image](https://github.com/freqtrade/freqtrade/assets/5024695/0bc10ad7-3342-4e8b-99f9-5d877e94eb6b)

notice that `"x"` is 0.0 on the last candle (first image) - but the ACTUAL difference (`"y"`) is not 0.
Once this candle shifts by one, the value on the "non-last" candle changes, making it a bias / unstable signal.

worst case, your strategy does `dataframe['x'] <> 0` - which would be a signal that makes tons of trades in backtesting - but would never actually cause ANY entry or exit in live (which only checks the very last candle).

**Comment by moinonin** [comment]
Thanks @xmatthias my stupid mistake 😬
