### ISSUE TITLE
binance.py Improvement 

### ISSUE THREAD

**Issue by Akshat111111** [freqtrade/freqtrade#9246]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*

**Comment by perkmeister** [comment]
???

**Comment by stash86** [comment]
I'll re-open this if you give us the real issue

**Comment by Akshat111111** [comment]
I will make a pull request ,If you assign me this issue then review it

**Comment by xmatthias** [comment]
> I will make a pull request ,If you assign me this issue then review it

I don't see why we would assign an issue for that (especially one that has no content).
you're free to open a pull request - but that's not what you did (you opened an issue).

issues without content will be closed - as there's nothing to act on.

Please note:
before bigger changes, please open an issue to propose the change first.
We'll review all PR's - but that's no guarantee that all changes are good, desired, or will be accepted.
