### ISSUE TITLE
this configuration, does the final returned trading pair list only include the /USDT trading pair?

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9264]
## Describe your environment

  * Operating system: ubuntu 20.4
  * Python Version: 3.8
  * CCXT version: 4.0.17
  * Freqtrade Version: 2023.8

## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Could you please tell me about this configuration, does the final returned trading pair list only include the /USDT trading pair?

Thank you very much.

**config.json:**
```
......
"stake_currency": "USDT",
......
"exchange": {
        "name": "binance",
        "key": "1111",
        "secret": "2222",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 50,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
......
```

**Comment by xmatthias** [comment]
The best way is to test this yourself - we have a command for that in `freqtrade test-pairlist <--config config.json>`

(hint: the answer is yes - but it's still better to learn how to test such things yourself - especially once you get into more advanced pairlist configurations).

**Comment by WinPoss** [comment]
Your suggestion is very good, but I found that `"method": "VolumePairList"` will also add stablecoins:

```
/whitelist
Using whitelist ['VolumePairList'] with 50 pairs
BTC/USDT, ETH/USDT, USDC/USDT, XRP/USDT, SOL/USDT, FDUSD/USDT, BUSD/USDT, BCH/USDT, TUSD/USDT, AMB/USDT, MATIC/USDT, LINK/USDT, LEVER/USDT, GALA/USDT, RUNE/USDT, ARB/USDT, DOGE/USDT, LTC/USDT, OP/USDT, AKRO/USDT, EUR/USDT, TRB/USDT, SUI/USDT, LOOM/USDT, LOKA/USDT, TRX/USDT, BLZ/USDT, MASK/USDT, OGN/USDT, WLD/USDT, ADA/USDT, AVAX/USDT, BAKE/USDT, ACA/USDT, STORJ/USDT, LQTY/USDT, MKR/USDT, SHIB/USDT, APT/USDT, CFX/USDT, PEPE/USDT, RAY/USDT, FTT/USDT, FRONT/USDT, RNDR/USDT, FIDA/USDT, RDNT/USDT, EOS/USDT, AAVE/USDT, LPT/USDT
```

and generally does not trade stablecoins, so I would like to make a suggestion: exclude stablecoins when use `VolumePairList` method:

```
"pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 50,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800,
            "exclude_stablecoins": ['TUSD/USDT', 'USDP/USDT', 'BUSD/USDT', 'FDUSD/USDT', 'USDC/USDT']
        }
```

**Comment by xmatthias** [comment]
It's up to you to define a pair_blacklist.
Your above setup only excluded BNB/.* - nothing prevents you from extending this to pairs you consider stablecoins.
