### ISSUE TITLE
Stoploss on exchange filled but trade closed incorrectly [Bybit]

### ISSUE THREAD

**Issue by Axel-CH** [freqtrade/freqtrade#9268]
## Describe your environment

  * Operating system: linux
  * Python Version: 3.9.18 (`python -V`)
  * CCXT version: 4.0.112 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.10-dev-fed5bd140 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the problem:
A trade had a sl on exchange filled but the bot was not properly aware of that.

*Explain the problem you have encountered*
I had a long position on TWT/USDT:USDT with a stoploss on exchange placed. The price moved down and my sl was filled.
Despite that fact, the bot "ignored" the filled event and did not sent the exited confirmation.
As a entry signal was still active, the bot opened a new trade on that position immediatly as the Cooldown period of 1 candle failed to engage.

### Steps to reproduce:
  1. Open long
  2. Put Stoploss on exchange
  3. Wait for the price reaching SL
  4. SL filled but bot ignore that and create new trade
  
### Observed Results:

  * What happened?
   Sl was filled but position not exited properly (no confirmation message)
  * What did you expect to happen?
  A confirmation message of trade exit, correct implementation of configured cooldow pair lock (config timeframe is 15m)
Trade id 7 is the problematic trade, Trade id 8 exited properly without issue.

### Comment
The bot tried to cancel the filled stoploss order but got "InvalidOrderException" from exchange:
`Message: bybit {"retCode":110001,"retMsg":"Order does not exist","result":{},"retExtInfo":{},"time":1696435530759}`
Maybe a bug from bybit?

### Relevant code exceptions or logs
![freqtrade_telegram_msg](https://github.com/freqtrade/freqtrade/assets/7593404/3617cc80-3cea-4d65-b098-411f245b4298)
![chart_tf_1s](https://github.com/freqtrade/freqtrade/assets/7593404/5f3c55f8-9eff-4efc-9776-3bafbb638abb)
![bybit_order_history](https://github.com/freqtrade/freqtrade/assets/7593404/771f7798-3e02-4f12-969d-592353b71e5c)

Concerning trade 7 I don't see anything wrong in DB, all fields seem filled corectly.
![strat01_trades_db](https://github.com/freqtrade/freqtrade/assets/7593404/08f3582d-ebab-46c4-958f-e587ec6d53f6)

*order f11e6a0f1e67 is the sl that got filled
*you can ignore error messages from GALA pair, as it is a "gost trade" and that's another issue...
[TWT_sl_on_exchange_ignored.log](https://github.com/freqtrade/freqtrade/files/12810813/TWT_sl_on_exchange_ignored.log)

**Comment by xmatthias** [comment]
unfortunately, the logs, while being 2MB big, don't actually contain the information necessary.

debug mode (`-v`) is not really helpful to debug such issues - what's really needed is `exchange.log_responses`) - which will show us the content of what the exchange returned (that's WAY better than knowing "made this call, won't tell you the response" which is what this log contains).

Please make sure to update to 1e0d622d80cd50631e88761af5ddd8cf0aa7e00e or later - which **may** already contain the actual fix for this.

Obviously let me know if it reappears with that version (with the logs mentioned above, hopefully) - or if you think you've seen a similar situation handled correctly (which will confirm that the issue is fixed).

**Comment by Axel-CH** [comment]
Thank you for you response, I already had `exchange.log_responses` set to true maybe -vv caused too much logs.
I updated the bot to latest and I will let you know if it is fixed.

**Comment by xmatthias** [comment]
> maybe -vv caused too much logs

yes, definitely

**Comment by Axel-CH** [comment]
Did not have that issue since the update with your fix. Thank you for your help 👍🏽
