### ISSUE TITLE
How to pass leverage param when using forceenter with rest_client

### ISSUE THREAD

**Issue by rkumaroutlook** [freqtrade/freqtrade#9269]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.10.12
  * CCXT version: 4.1.4
  * Freqtrade Version: 2023.8
  
## Your question

I couldnt find anywhere how to pass leverage as parameter when using rest_client to enter a trade using forceenter command. Please help.

**Comment by xmatthias** [comment]
the rest-client script doesn't currently support all possible parameters - but only the ones that are also available through telegram.

The main reason for that is that a command like `rest_client.py forceenter ETH/USDT long 5 2 6` is illegible, and makes it impossible to actually determine what you sent, or what the user intend is.
which of the 3 parameters is price, which is leverage, and which is amount/stake_amount ... ? 

impossible to say for sure - and therefore way too errorprone to enable like this.
For full control of force-entry commands, it's best to use freqUI - which will expose all parameters the endpoint currently accepts.
