### ISSUE TITLE
My minimal_roi setting is not taking effect. Am I understanding minimal_roi correctly?

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9271]
## Describe your environment

  * Operating system: ubuntu 20.4
  * Python Version: 3.8
  * CCXT version: 4.0.17
  * Freqtrade Version: 2023.8
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

I have two questions that I would like to ask:

**Question 1. Am I understanding minimal_roi correctly?**

```
minimal_roi = {
    "40": 0.0,
    "30": 0.01,
    "20": 0.02,
    "0": 0.04
}
```

The official website documentation provides the following explanation for the given code:

```
The above configuration would therefore mean:

Exit whenever 4% profit was reached
Exit when 2% profit was reached (in effect after 20 minutes)
Exit when 1% profit was reached (in effect after 30 minutes)
Exit when trade is non-loosing (in effect after 40 minutes)
```

My understanding is that in this case, the `key` refers to the time elapsed after buying a trading pair. For example, `"30": 0.01 `means that if the profit reaches 1% within 30 minutes after buying the trading pair, the strategy will execute a take-profit action. Is my understanding correct?

**Question 2. Why is the minimal_roi configuration in my strategy not taking effect? Could there be any other configuration errors?**

My strategy file and configuration file, please review the attachment.

Thank you very much.
[upload_files.zip](https://github.com/freqtrade/freqtrade/files/12832810/upload_files.zip)

**Comment by WinPoss** [comment]
I would like to set it up so that within 1440 minutes after buying a trading pair, if the return reaches 11%, the bot executes a take-profit.

**Comment by xmatthias** [comment]
min-roi will  usually be ignored if there's still an active entry signal (in the same direction) - so in case of sticking signals (or frequent signals), min_roi will be ignored.

Your best bet is to observe the startup logs - which will tell you which settings are currently used.
minimal_roi (as well as several other settings) can be set in both strategy and configuration - with the configuration overriding the settings in the strategy.

**Comment by jackchalat** [comment]
Here is what you have
```
minimal_roi = {
        "1440": 0.11,
        "2880": 1.77,
        "4320": 0.37,
        "7200": 1.11,
        "11520": 0.05,
        "18720": 1.38,
        "30240": 1.11,
        "48960": 0.41,
    }
```
This is not how it works if I understand correctly.
First you said after 1440 minutes, if the profit is 11% or more, take profit. Nothing wrong with this by itself.
But then you said after 2880 minutes, if the profit is 177% or more, take profit. This  will never happen since the first statement will always close trades first before the second can take effect. You should write it like the example. 

The longer the time passed, you can only lower the minimum profit target, not increase it.

**Comment by perkmeister** [comment]
`My understanding is that in this case, the key refers to the time elapsed after buying a trading pair. For example, "30": 0.01 means that if the profit reaches 1% within 30 minutes after buying the trading pair, the strategy will execute a take-profit action. Is my understanding correct?`

No, what you're missing is the part in the docs that says `in effect **after** 30 mins`. In other words that term is not even evaluated until 30 mins has elapsed, and then if it reaches 1% (or it's already at least 1%) it'll exit.

**Comment by WinPoss** [comment]
> Your understanding for this is correct. min-roi will however usually be ignored if there's still an active entry signal (in the same direction) - so in case of sticking signals (or frequent signals), min_roi will be ignored.
> 
> Your best bet is to observe the startup logs - which will tell you which settings are currently used. minimal_roi (as well as several other settings) can be set in both strategy and configuration - with the configuration overriding the settings in the strategy.




For example, this statement:

```
minimal_roi = {
    "30": 0.01,
}
```

For example:
I bought a trading pair at 10:00,
And, at 10:10, there is a 1% increase.
So, I would like to know if the above statement will execute the take-profit immediately at 10:10.
Or does the bot need to wait until after 10:30 to start evaluating whether the increase has reached 1% or more?

It is important to me to understand exactly which time period it takes effect. Thank you very much for your analysis.

**Comment by WinPoss** [comment]
> Here is what you have
> 
> ```
> minimal_roi = {
>         "1440": 0.11,
>         "2880": 1.77,
>         "4320": 0.37,
>         "7200": 1.11,
>         "11520": 0.05,
>         "18720": 1.38,
>         "30240": 1.11,
>         "48960": 0.41,
>     }
> ```
> 
> This is not how it works if I understand correctly. First you said after 1440 minutes, if the profit is 11% or more, take profit. Nothing wrong with this by itself. But then you said after 2880 minutes, if the profit is 177% or more, take profit. This will never happen since the first statement will always close trades first before the second can take effect. You should write it like the example.
> 
> The longer the time passed, you can only lower the minimum profit target, not increase it.

Is it correct that as time increases, the value of ROI decreases accordingly?

like this example:

```
minimal_roi = {
        "48960": -1,
        "30240": 0.11,
        "18720": 0.37,
        "11520": 0.61,
        "7200": 1.11,
        "4320": 1.34,
        "2880": 1.58,
        "1440": 1.77,
        "0": 0.41,
    }
```

**Comment by xmatthias** [comment]
> And, at 10:10, there is a 1% increase.
> So, I would like to know if the above statement will execute the take-profit immediately at 10:10.
> Or does the bot need to wait until after 10:30 to start evaluating whether the increase has reached 1% or more?

It will have to wait. before 10:30, there is no ROI in place.

the [corresponding documentation](https://www.freqtrade.io/en/latest/strategy-customization/#minimal-roi) explains this quite well i'd think, especially the "in effect after X minutes" should answer your questions exactly.

> Is it correct that as time increases, the value of ROI decreases accordingly?

In this particular example - ROI does NOT only decrease, but will increase first (from 41% to 177%).

Now that's not per se a problem - and will simply mean that we accept a quick 41% profit (before 1440 minutes) - but will require a 177% profit between 1440 and 2880 minutes, having it decrease thereafter, and force-selling all trades after 48960 minutes.

**Comment by WinPoss** [comment]
Sure, thank you for your response. Since I usually rely on translation software for English, my understanding of the semantic nuances in documents may not be very accurate. Now, after your explanation, I understand it. Thank you!
