### ISSUE TITLE
Set minimal roi to non-zero during hyperopt

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#9272]
## Describe your environment

  * Operating system: Linux mint Una
  * Python Version: 3.10.7
  * CCXT version:  4.0.76
  * Freqtrade Version: 2023.9-dev-e0e0a2581
  
## Your question

I am currently running hyperopt parameter tuning. I have a custom exit signal that I trust and can exit even when the trade profit is <= 0. How do I configure hyperopt so that I don't have the last value for say "360": 0. I am grateful for the tips on this.

**Comment by xmatthias** [comment]
well nobody forces you to actually hyperopt ROI.
configure what you like, and run hyperopt with `--spaces` excluding roi.

**Comment by moinonin** [comment]
Well you misunderstood me. I need ROI table without forcing it to have the key value "x": 0

**Comment by xmatthias** [comment]
You can [override each of the pre-defined spaces](https://www.freqtrade.io/en/latest/advanced-hyperopt/#overriding-pre-defined-spaces). 

Considering how long you're using this project, my assumption was that you'd have found this in the docs by now :laughing:

**Comment by moinonin** [comment]
Nice one :1st_place_medal:
