### ISSUE TITLE
How does available_capital work?

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9277]
## Describe your environment

  * Operating system: ubuntu 20.4
  * Python Version: 3.8
  * CCXT version: 4.0.105
  * Freqtrade Version: 2023.8
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

If my configuration file is set as follows (please note that I did not set stake_amount):

```
"max_open_trades": 10,
"available_capital": 300,
"tradable_balance_ratio": 0.99,
```

And I only have one bot running on my server (running only one strategy), then is the calculation of each stake amount done as follows:

(available_capital * tradable_balance_ratio) / max_open_trades

That is:

(300 * 0.99) / 10 = 29.7

Furthermore, as the bot continues to trade, the account's capital may increase or decrease, and the bot will dynamically allocate the stake amount for each trade based on the actual account capital and `max_open_trades`.

The above is my understanding of the configuration file, and I wonder if it is correct?

Thank you.

**Comment by xmatthias** [comment]
That's actually covered by [the documentation](https://www.freqtrade.io/en/latest/configuration/#assign-available-capital).

Don't see any question here that's not answered in full by that section.

as a side note: how many bots you run on a server doesn't matter  as long as there's sufficient resources available.
for live bots, what might make a difference is the bots running against the same (sub)account - as each bot will assume `available_capital` is fully available for that bot.

**Comment by WinPoss** [comment]
Is there any way to achieve the following use case:

If my `stake_amount` is set to 10, the bot will dynamically allocate the funds into 10 portions, using one portion for each buy order.

If the total capital of the account increases or decreases during trading, each portion of the funds will be adjusted dynamically, with the goal of maintaining an equal distribution across the 10 portions.

**Comment by WinPoss** [comment]
According to the [documentation](https://www.freqtrade.io/en/stable/configuration/#dynamic-stake-amount), does it need to be set like this:

```
"max_open_trades": 10,
"stake_amount" : "unlimited",
"tradable_balance_ratio": 0.99
```

**Comment by stash86** [comment]
Try it and see. Run a dry run bot, set it either to always buy, or use force entry telegram command. See how the config translated to stake amount
