### ISSUE TITLE
Help needed with stake_amount calculation for absolute loss with losing trade

### ISSUE THREAD

**Issue by sandervdhave** [freqtrade/freqtrade#9278]
Operating system: Ventura 13.4.1
Python Version: 3.11
CCXT version: 3.1.44
Freqtrade Version: freqtrade docker-2023.6.dev-c5510491

I am working on money management:

I set a fixed Risk Reward Ratio based on the ATR that is been calculated in the populate_indicator.
Next i calculate the Leverage. In this calculation i calculate the max leverage based on the liquidation price that ends up just below the StopLoss_rate.
After that is calculate the stake_amount, so that the maximum loss on a trade is $50
The last step is that i define a custom_exit based on the calculated fixed Reward Ratio.

The stake_amount calculation is not working properly when testing in dry-run. This is the code:

```
def custom_stake_amount(self, pair: str, current_time: datetime, current_rate: float,
                            proposed_stake: float, min_stake: Optional[float], max_stake: float,
                            leverage: float, entry_tag: Optional[str], side: str,
                            **kwargs) -> float:
        
        # Setting the custom SL value
        self.custom_sl_value_every_trade = self.stake.value # Dollar per trade

        # get dataframe
        dataframe, _ = self.dp.get_analyzed_dataframe(pair=pair, timeframe=self.timeframe)
        # get the last candle
        last_candle = dataframe.iloc[-1].squeeze()
        previous_candle = dataframe.iloc[-2].squeeze()

        if last_candle['enter_long'] ==1 and previous_candle['enter_long'] != 1:
            proposed_stake = self.custom_sl_value_every_trade / (((last_candle['close'] - last_candle['long_StopLoss_rate']) / last_candle['close']) * leverage)
            # logger.info(f">> Proposed LONG Stake: {proposed_stake}")
            return proposed_stake

        elif last_candle['enter_short'] ==1 and previous_candle['enter_short'] != 1:
            proposed_stake = ((self.custom_sl_value_every_trade * last_candle['short_StopLoss_rate']) / (last_candle['short_StopLoss_rate'] - last_candle['close'])) * (1 / leverage)
            # logger.info(f">> Proposed SHORT Stake: {proposed_stake}")
            return proposed_stake

        # Use default stake amount.
        return proposed_stake
```

I use the last_candle['close'] to find the open_rate of the trade that is about to happen. Am i right to think that this will work?
When i recalculate the stake_amount with made trades i get very different results using the open_rate of that trade.

Is it possible to use the exact open_rate for the calculations in this code? Or is there another way to make this calculation where the goal is to calculate a stake_amount where i only lose $50 when the trade is lost?

**Comment by stash86** [comment]
define `not working properly`

**Comment by sandervdhave** [comment]
Thanks for the fast reply! I will try to elaborate en be more specific.
My goal is to have a Fixed Risk:Reward Ratio of 1:3. Where i lose $50 or win $150 in a trade. 

In my dry-run i have 2 losing trades where i lose: $45, $228
I also have a few winning trades where i made: $49, $198, $1.5, $152, $76
So these numbers are all over the place. 

Let me give a example of one long trade:
open_rate = 0.007026
StopLoss = 0.006185
Leverage = 8.352851

stake_amount = 50 / ((open_rate - Stoploss) / open_rate * Leverage)
stake_amount = 50 / ((0.007026 - 0.006185) / 0.007026 * 8.352851) = $50.01
But the bot calculated a stake_amount of $126.17

Another example of a short trade:
open_rate = 0.007791
StopLoss = 0.00844
Leverage = 12.022354

stake_amount = ((50 * Stoploss)/(Stoploss - open_rate)) * (1/Leverage)
stake_amount = ((50 * 0.00844)/(0.00844 - 0.007791)) * (1/12.022354) = $54,09
But the bot calculated a stake_amount of $97,20

Of course, in my recalculations i am using the open_rate instead of the last_candle['close']. But i think that should be the same value. I cannot find the reason why my bot is not making the same calculations as my recalculations.

Can someone spot the difference? or is there a better way to calculate the stake_amount?

**Comment by sandervdhave** [comment]
I can see in one of my trades that the last_candle['close'] is not the open_rate. You can see in the picture that the trade gets triggered on the long red candle. I thought the trade would open on the entry of the next candle, but the open_rate is much lower as you can see.

Why is this? And how can i deal with this difference in above calculations?

![LongProfitStoploss](https://github.com/freqtrade/freqtrade/assets/41057106/cb7590e0-5d0e-417e-984a-7e07f1612cff)

**Comment by perkmeister** [comment]
It looks to me like the buy signal happened on the close of the previous candle, but remember that the trade will actually open somewhere in the next candle as that is determined by how long it takes to fill the buy, and by that time the price had plummeted so you entered at whatever the price happened to be at the time. What's a little curious as despite it telling you there was a 15.915% profit, the exit tag says it was a stoploss.

**Comment by xmatthias** [comment]
Entry price != prior close price. 
That's wrong for live (markets move all the time), and is also wrong for backtesting (it'll be open_price for the new candle).
While in backtesting, you might not see the difference that often, also crypto markets can gap down/up between 2 candles.


Assuming there's a entry signal on the candle prior to that entry (i'll get back to that soon) - it'll simply mean that there was an immediate drop right when this candle started.
you should be able to see that on lower timeframes - that the low (or at least something close to the low) happened the first minute of the trade or so.

All callbacks should get a `current_rate` parameter - which is the parameter the bot assumes to place the trade at.

The trade isn't guaranteed to execute at that rate. 
Assuming you get 95$ in your callbacks as "assumed entry rate" for a long entry (buy order).
if price drops further (say, to 90$) - you'd still be placing your orders with a price of 95$ - which would convert this to a marketable limit order (essentially hitting the ask - and executing immediately at the best price, most likely around 91$ or so).

If price raises - your order will stay unfilled - waiting for price to drop to your level again - and eventually timing out.

Now that's assuming limit orders - market orders will fill immediately.

You can't reliably account for this prior to placing the order - (low volume) markets can drop several % within seconds - so this is simply something your logic has to be able to cope with.

---

> Assuming there's a entry signal on the candle prior to that entry

Now coming back to this statement - that's the thing i'm missing in the above chart.
entry signals don't appear to be hidden (the green triangle is green, not gray as it were if they're not shown) - but the triangle itself is nowhere to be found (i'd expect a green triangle pointing up at the close of the candle before the entry).

There can be multiple reasons for that 
- a forced entry (with custom tag set to long) 
- an entry with custom pricing and long timeout (so the signal is no longer visible)
- Indicators repainting, disappearing at random (which usually also means they'll appear at random, which might look like ignored signals - and is usually a sign of a bigger problem in some indicator).


As long as YOU have a good explanation for it, i'll be fine with it - but i think it's something worth looking into.


----

> What's a little curious as despite it telling you there was a 15.915% profit, the exit tag says it was a stoploss.

The exit is not saying it's a stoploss, it's a `long_StopLoss` - which is a custom exit signal, not a builtin static stoploss (which i assume is what you're thinking about).

**Comment by sandervdhave** [comment]
Thanks for the reply's!

I start to see what i did wrong in my logic:
The custom_stake_amount, Leverage, takeprofit and stoploss are based on the prior close price. But the entry price could be much lower or higher. And that is where everything goed wrong.

> What's a little curious as despite it telling you there was a 15.915% profit, the exit tag says it was a stoploss.

In this case i was just lucky the price got above the calculated stoploss and was able to make profit.

I have been working with the current_rate, but i did not understand how to add this in my logic. Even with the examples from the documentation. Could you elaborate on the current_rate for me? Maybe give a example on the code i provided?

**Comment by xmatthias** [comment]
not sure what you expect from this.

current_rate is simply the price based on your pricing logic (it's a float).
As said above, please don't assume that price to be 100% what you'll get filled - that's something we don't really control - so your price can still be higher / lower (depending on your ordertypes)- and your strategy needs to be able to adjust to that.

**Comment by sandervdhave** [comment]
Thank you. I get what you say. But i really don't know how to make my strategy adjust to that. 

Is it possible to set a limit order at the prior close price? Is my logic right that if the trade gets filled on that price, my logic for custom_stake_amount, leverage, takeprofit and stoploss is better?

Or does someone have another idea to get the goal to calculate a stake_amount where i only lose $50 when the trade is lost?

**Comment by xmatthias** [comment]
you can place a order at a specific price - but in live, it's the markets determining the price you'll ACTUALLY get filled - which will be at that price _or better_ (in case of buy orders - that price or lower).

I understand what your intend is - and deviations will usually not be quite high (if you're not working on false assumptions, like - i enter on the prior order's close price) - and assuming your strategy goes through the pairlist in reasonably short time - but it's not something you can avoid (it's the same with manual-trading, really - until you've placed the order, price might have moved away from that spot - voiding all calculations you previously made). 

With an algo, you're usually faster - but that doesn't mean 0 delay.

your best bet is a combination - do your calculation against the assumed order price - and then adjust the stop according to the actually filled order prices.

if you start to play with prices, you'll need to account for order timeouts, due to that, late order placements, ... which all are not a problem - but need to be taken into account (which i assume your current logic doesn't - as it's statically based around what happened 1 candle ago.

**Comment by perkmeister** [comment]
> > What's a little curious as despite it telling you there was a 15.915% profit, the exit tag says it was a stoploss.
> 
> The exit is not saying it's a stoploss, it's a `long_StopLoss` - which is a custom exit signal, not a builtin static stoploss (which i assume is what you're thinking about).

I knew this was a custom exit label not a builtin stoploss, I was just curious why it was labelled as a stoploss (although no idea what that label really means to the OP).

**Comment by xmatthias** [comment]
most likely, output of the logic posted in #9245 ... ;)

**Comment by sandervdhave** [comment]
Thanks again for all the information. I get some ideas to try out. I have started this coding/freqtrade journey around March. My strategy does not work perfectly, but has a profit factor of 2.32 which is all thanks to the documentation and all the help from the community.
