### ISSUE TITLE
I want to reduce the number of calls to the Bybit API.

### ISSUE THREAD

**Issue by virgil0219** [freqtrade/freqtrade#9291]
* Python Version: _____ Python 3.11.3
  * CCXT version: _____ ccxt==4.0.76
  * Freqtrade Version: ____ freqtrade 2023.9-dev-78f356c0d
  
Question
I trading on Bybit.
I would like to modify ccxt so that the BTC price data is retrieved every 5 minutes.
Could you tell me where I can find a file where I can do something that will change the number of API calls?
The purpose of this change is to delay the frequency of determining if the value set in ROI or Stoploss has been reached.
If it is possible to change the frequency of calls to functions such as "update_trade_state" to be delayed, as shown on line 1831 of Interface.py, we would be happy to make that change.
Please let me know which file is calling bybitAPI, or which file to modify to delay the ROI and Stoploss decisions.

**Comment by xmatthias** [comment]
You can change `internals.process_throttle_secs` to slow down bot operations (defaults to 5s).

I'd however strongly advise against this - as it'll make the bot blind for "in between" spikes, and can potentially lead to huge losses, especially when used in leveraged markets, and/or without stoploss on exchange.

We'll not support nor advise on modifications like the one you propose above.
