### ISSUE TITLE
How can I place stop loss and stop profit when I confirm trade entry?

### ISSUE THREAD

**Issue by Vietdung113** [freqtrade/freqtrade#9295]
How can I place stop loss and stop profit when I enter a trade without using custom exit or exit signal?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---


Please consult the [documentation](https://www.freqtrade.io/en/stable/stoploss/) for questions that can be easily answered there (like - stoploss placement).

As for take profit - you cannot currently have a take-profit order on the exchange. Feel free to subscribe to #7499 for updates on this.
For "bot" take profits, you might want to search the documentation for "minimal_roi".
