### ISSUE TITLE
Use custom stoploss prior to default if closer to current rate

### ISSUE THREAD

**Issue by Axel-CH** [freqtrade/freqtrade#9296]
## Describe the enhancement
Currently the fixed default stop loss percentage value is always applied first, then the custom stop-loss is computed and replace the default one.
If the custom_stoploss value is closer to current price, it is not good to use the default first because:

On live, it is raising the risk associated with the trade, even for 10s.
On backtest, it is widening the gap between live result by being more pessimistic. As custom stop is updated after entry candle, if the price go bellow liquidation level an unrealistic liquidation will be registered in backtest, as live update more quickly stoploss.

*Explain the enhancement you would like*
**Initial stoploss should be custom_stoploss if the given value reduce risk percentage related to default one**.

Results:
Better live profits
Better backtests

**Comment by xmatthias** [comment]
I don't actually see the usecase for this if i'm honest.

if your liquidation triggers _before_ the stoploss, then you either have 
* the stoploss to wide
* too much leverage

(and most likely both).

It will introduce other problems you can't control, as you can't really know the _actual_ entry price before the order fills, so your logic will most likely be wrong / calculated against an assumed entry price - which may be too low or too high - causing an either too wide, or way too narrow (worst case, even above the open rate) price.

As such, i don't see a custom stoploss evaluation before the order fills as making much sense, as you're working on speculation only at that point.
once the order fills, `custom_stoploss()` will be evaluated - and will eventually adjust the price.


---

There will also be no impact to backtesting.

For backtesting, the "default" stop is only in place for cases where the custom-stop code from the strategy fails - as the evaluation happens as explained in [the docs](https://www.freqtrade.io/en/latest/bot-basics/#backtesting-hyperopt-execution-logic) - which is checking and adjusting before evaluating for stops or liquidations for the first time.

If you think that's not the case, i'm happy to get a reproduction that shows this so we can investigate.

---

I'll treat this as a question for now - with the option to have it as potential bug for backtesting IF we get a reliable reproduction of the above - which after a quick look through the code - i do doubt (but it's a quick look, not real investigation).

**Comment by Axel-CH** [comment]
Using custom entry price give the possibility to have the limit entry price before entry, so the stop loss can be set very precisely without issue.
For backtesting I've added that just for a quick test and got better results / less unexpected liquidations:
```
#line 911 backtesting.py
            custom_sl = strategy_safe_wrapper(
                    self.strategy.custom_stoploss, default_retval=True)(
                        pair=pair, trade=trade, current_time=current_time,
                        current_rate=row[OPEN_IDX],
                        current_profit= 0, after_fill= False)

            sltd_sl = self.strategy.stoploss
            if custom_sl:
                if custom_sl < 0:
                    sltd_sl = custom_sl if custom_sl < self.strategy.stoploss else self.strategy.stoploss

            trade.adjust_stop_loss(trade.open_rate, sltd_sl, initial=True)
```
What do you think about that?

I will prepare a reproducible example for you

**Comment by stash86** [comment]
I disagree that this would make better backtests. With how backtest is being done right now, you are gonna make the difference of results between backtest vs dry/live becomes larger.

As I have repeated many times in the server (and written in my blog), as long as you don't use current_profit too much, the difference won't be significant. But if you use it a lot, then difference can't be avoided. Your suggestion (from quick judgement) won't fix it either

**Comment by xmatthias** [comment]
> Using custom entry price give the possibility to have the limit entry price before entry, so the stop loss can be set very precisely without issue.

This will only work for backtesting - and also only on the assumption that the order actually fills (so it's actually irrelevant, and will increase the backtest/live gap).
if the order is adjusted before it fills- things would change, potentially causing another pointless call.

---

please make sure to have the sample use sane values (not 100x or so) - otherwise the solution will be to hard-limit the maximum leverage - just to protect users from themselfs.

> What do you think about that?

For now, I think it's ignoring reality by over-using leverage just to show the point.

if you hit a liquidation on the entry candle (this is the only scenario where this would be relevant for backtesting, otherwise the callback IS called prior to this) - then you've got bigger problems (overleveraged, ...).

**Comment by Axel-CH** [comment]
I'm running the back-tested strategy live since a few days. Got multiple trades but no liquidation so far. But I still got two mails from bybit saying that the current price was close to liquidation rate. Checked and saw that on both occasion my stop-loss on exchange prevented the liquidation.
So I though my "liquidation" issue was simply coming from a too high "liquidation_buffer" as my position management strategy make the trade to often come near liquidation price.
So I've set a liquidation_buffer of 0.0 instead of default and came from 64 liquidations to 58 on same period.
I still need to find the other cause.

**Comment by xmatthias** [comment]
well the assumption of the liquidation buffer is to have the stop slightly higher than the actual liquidation price.
if you're maxing out your range, a different setting can make sense - though i wouldn't set it to 0.0, as that'd mean your stop is AT the liquidation price - where you probably have a 50/50 chance of what happens  (if there's no liquidity in that pair around that price, it'll probably be the liquidation ...)

**Comment by xmatthias** [comment]
seems like the evaluation of liquidation price happened before stop - if both trigger on the same candle.
On live - not really a problem, but on backtesting, this will have an impact, as the calculation of liquidation price is way different to the one of backtesting.

**Comment by Axel-CH** [comment]
Thank your for your help 👍🏽
