### ISSUE TITLE
How to calculate ROI in back testing

### ISSUE THREAD

**Issue by virgil0219** [freqtrade/freqtrade#9297]
Suppose I set the ROI to 1% in a backtest using 15 minutes of chart data.
If the ROI reaches 1.3% during the 15 minutes, would that trade in the backtest be recorded at +1.3% or +1%?

**Comment by stash86** [comment]
If only such thing written in the docs....

oh wait, it is. https://www.freqtrade.io/en/stable/backtesting/#assumptions-made-by-backtesting

Please try to read the whole docs.
