### ISSUE TITLE
about increase，please help me，thanks

### ISSUE THREAD

**Issue by xxmmxx** [freqtrade/freqtrade#9300]
## Describe your environment

  * Operating system: windows 10 pro
  * Python Version: Python 3.10.6 (`python -V`)
  * CCXT version: ccxt==3.1.5 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.5.1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
Excuse me, Binance Perpetual Futures Contract, how to achieve the increase ranking of multiple contract pairs in a tick (within 24 hours)

**Comment by stash86** [comment]
Same answer, give us more context about what you actually want, otherwise this will be closed as well

**Comment by xmatthias** [comment]
Without the context (what are you trying to accomplish, ...) your question unfortunately does not make sense.

Please try to rephrase it, or maybe try to describe what you're trying to do.
as is, this is unfortunately not something we're able to provide an answer to.
