### ISSUE TITLE
Could not set margin mode due to NotSupported

### ISSUE THREAD

**Issue by Eugene952** [freqtrade/freqtrade#9319]
## Describe your environment

  * Operating system: Ubuntu 22.04.2 
  * Python Version: 3.10.12
  * CCXT version: 4.0.105 
  * Freqtrade Version: 2023.9
  
## Your question

Hello. I can't make a transaction on the stock exchange. I get this error:

freqtrade.exchange.common - WARNING - set_margin_mode() returned exception: "Could not set margin mode due to NotSupported. Message: binance setMarginMode() supports linear and inverse contracts only". Giving up.
2023-10-15 17:55:00,702 - freqtrade.freqtradebot - WARNING - Unable to create trade for ARPA/USDT: Could not set margin mode due to NotSupported. Message: binance setMarginMode() supports linear and inverse contracts only

My settings:
 "trading_mode": "futures",
 "margin_mode": "isolated",
  strategy Strategy001

On the exchange:
Asset-Mode -  Single-Asset Mode
Positions Mode -  One-Way Mode
Perpetual Margin Mode -  Isolated

What did I do wrong?

**Comment by xmatthias** [comment]
`ARPA/USDT` is not a futures pair - `ARPA/USDT:USDT` would be one.

This suggests that you've somehow got your pairlist configuration wrong - most likely by defining spot pairs.

**Comment by Eugene952** [comment]
Thank you very much for your help, everything works now.
