### ISSUE TITLE
Avoid new users raising issues like issue #3926 or issue #3925

### ISSUE THREAD

**Issue by roadbridgeaward** [freqtrade/freqtrade#9322]
This is a suggestion to finetune the documentation such that inexperienced new users will not fall into this trap and are not enticed to install an inaccurate edition of Docker.

If this fine altering of the documentation is implemented we will avoid unnecessary issues like:
[ Issue "Config.json is not found #3926" ]
[ Issue "config.json not found #3925" ]

For the full details of the justifications behind this suggestion please see the comment written by @roadbridgeaward in https://github.com/freqtrade/freqtrade/issues/3926#issuecomment-1769010464

**Comment by xmatthias** [comment]
I don't really see how reviving (and referencing) issues that are 3 years old is relevant.

Feel free to submit a PR proposing to enhance the documentation as you think is necessary.

As the linked issues are however 3 years old - and i've not really seen this issue recently, 
I don't intend to act on this myself - but Contributions (enhancing the documentation, in this case) are certainly welcome.

**Comment by roadbridgeaward** [comment]
Thank you so much @xmatthias
