### ISSUE TITLE
Improved roi mechanic when using limit orders

### ISSUE THREAD

**Issue by tomashinM** [freqtrade/freqtrade#9326]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.11.5
  * CCXT version: 4.1.13
  * Freqtrade Version: freqtrade docker-2023.10-dev-4a4b695b

## Describe the enhancement

Hello, I noticed a problem when I was working with limit orders:
If I am in position and I have open entry order (adjusting position on desired price level) when price gets to take_profit level its ignored (with standard roi and with custom_exit) as I understood because of open order. 

I found solution how to do it:
Set unfilled timeout to small value (1 minute) and not place order (in adjust_trade_position) when current_profit > 0 but downside of this is: its placing orders too frequently when current_profit < 0 increasing risk to miss entry on fast price movements.

Enhancement:
It would be nice to have current_profit, current_rate parameters in check_entry_timeout callback as it would allow to cancel order only when price gets closer to take_profit level. Or even better enhancement if order would cancel automatically.

**Comment by xmatthias** [comment]
well essentially, what you've got is 2 conflicting signals - which is usually a strategy problem (you either want to increase your position - **or** you'd like to exit the position (both default ROI and custom_exit will exit the trade completely) - but you'd like to do both at the same time - which doesn't really make sense from a strategy perspective.

I don't really see how the price in `custom_entry_timeout` would help that - as your signals are still conflicting, which is a conceptual problem of the strategy, not something the bot should or will handle for you.

If you really need the current price (you don't - your signals are conflicting) - you can query that from within your strategy (callback) via [data provider](https://www.freqtrade.io/en/stable/strategy-customization/#orderbookpair-maximum) - but i don't see us adding an additional call for no good reason.

**Comment by tomashinM** [comment]
Ok, thanks a lot for fast reply. I understand that my strategy usage case is very specific so maybe its not most important enhancement now. Anyway I tried what you proposed with data provider. And it seems to be working as expected. So thanks again for the tip.
