### ISSUE TITLE
Falling into misconceptions about future data.

### ISSUE THREAD

**Issue by zhihuba** [freqtrade/freqtrade#9341]
# version
- freqtrade 2023.9-dev-c894843d0
- Python 3.11.6
# Falling into misconceptions about future data.
## Sample code
```python
    def populate_indicators(self, df: DataFrame, metadata: dict) -> DataFrame:
        df['buy_basic'] = df['close'] <= df['xxxx']
        fxDown = (
                (df['low'].shift(2) < df['low'].shift(1)) &  # k2Low < k1Low
                (df['low'].shift(2) < df['low']) &  # k2Low < k3Low
                (df['high'].shift(2) < df['high'].shift(1)) &  # k2High < k1High
                (df['high'].shift(2) < df['high'])  # k2High < k3High
        )
        
        fxDownData = fxDown.shift(-1).fillna(False)

        true_buy_valid_pivot_low_indices = df[fxDownData].index
        
        fxDown_status = np.zeros(len(df), dtype=bool)
        
        for idx in true_buy_valid_pivot_low_indices:
            
            window = df.loc[idx - 2:idx, 'buy_basic']
            
            if window.any():
                
                fxDown_status[idx] = True
        df['fxDown'] = fxDown_status
    def populate_entry_trend(self, df: DataFrame, metadata: dict) -> DataFrame:
        '''
        xxxxxxxxx
        '''
        conditionsBuy = []
        if self.buy_fxDown_enabled.value:
            conditionsBuy.append(df['fxDown'])

        conditionsBuy.append(df['volume'] > 0 & df['buy_basic'])

        if conditionsBuy:
            df.loc[
                reduce(lambda x, y: x & y, conditionsBuy),
                'enter_long'] = 1


        return df
```
# Backtesting everything is fine. But normal transactions will not occur in "dryrun" mode. I delete the strategy part of the code. The final positioning is that there is a problem here. I don't quite understand why this is happening. How to solve

**Comment by xmatthias** [comment]
You might want to look at the [common strategy mistakes](https://www.freqtrade.io/en/stable/strategy-customization/#common-mistakes-when-developing-strategies) very carefully.

Your strategy does contain at least one of these - making it impossible for any signal to appear on the very last line of the dataframe (which is a requirement for dry/live runs to work).

**Comment by zhihuba** [comment]
I've read the documentation. Will there still be errors if I use a for loop?

**Comment by xmatthias** [comment]
then please read this section again until you notice your error :)

` fxDownData = fxDown.shift(-1).fillna(False)` will cause the last line to be empty. while you might ffill that - it's not going to be a signal.
Whatever you backtested is tehrefore based on a lookahead bias.
you should also get that as a result from [lookahead-analysis](https://www.freqtrade.io/en/latest/lookahead-analysis/).

**Comment by zhihuba** [comment]
```python
#fxDownData = fxDown.shift(-1).fillna(False)
fxDownData = pd.Series(False, index=df.index)
        for i in range(1, len(fxDown)):
            if fxDown[i]:
                fxDownData[i - 1] = True
        fxDownData[0]=False
```
It seems that it can be solved in this way, freqtrade lookahead-analysis biased_indicators no longer contains fxDown

**Comment by xmatthias** [comment]
i don't see why you would loop in this case.
Please take the time to learn how pandas works - this will allow you to write a lot more performant strategies (this is as simple as a regular forward shift.

**Comment by perkmeister** [comment]
> It seems that it can be solved in this way, freqtrade lookahead-analysis biased_indicators no longer contains fxDown

No, any entry in `fxDownData` still depends on one candle later on in the dataframe. In live/dry the last candle in the dataframe is the most recent candle, there is no candle later than that, so the last entry for `fxDownData` will always be False and it won't work in dry/live. In backtesting you would be relying on future data so you'll have lookahead bias.

**Comment by xmatthias** [comment]
Great spot! :+1: 

As mentioned above - you need to rethink what your strategy relies on. 
Think about pandas as an excel file (somehthing everyone is familiar), with the oldest row at the top.

You cannot use a value from below the current row to calculate the current row, otherwise it's forward looking.
There may be many ways for this - but the pure concept of doing that will be wrong.

**Comment by zhihuba** [comment]
It is just a method of finding low scores, if it is based on the current K-line. There will be conflicting results. So I need to move the result forward one df['fxDown'] = fxDown.shift(1).fillna(False)

**Comment by xmatthias** [comment]
moving forward by one is not a problem, it's the moving back that is (which your logic did - and is still doing, just now with a loop).

**Comment by zhihuba** [comment]
Discard this conditional filter.
