### ISSUE TITLE
Can freqtrade work with TradingView Webhook

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9343]
## Describe your environment

  * Operating system: ubuntu 20.4
  * Python Version: 3.8
  * CCXT version: 4.0.105
  * Freqtrade Version: 2023.9
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Can freqtrade receive buy and sell signals from TradingView Webhook and execute the corresponding trades?

Does freqtrade support perpetual contract trading on the OKX platform?

Thank you.

**Comment by stash86** [comment]
> Can freqtrade receive buy and sell signals from TradingView Webhook and execute the corresponding trades?

Yes it can. How? That's for you to learn yourself. Implement a way to read external API in populate_indicators, merge the data if needed, and use it as how you like, There is no official example or template on how to do it, It's just python programming

> Does freqtrade support perpetual contract trading on the OKX platform?

Please read the docs as said in the question template. https://www.freqtrade.io/en/latest/#supported-futures-exchanges-experimental

**Comment by WinPoss** [comment]
OK, Thank you.
