### ISSUE TITLE
Forcesell on Telegram broken

### ISSUE THREAD

**Issue by cloakedch** [freqtrade/freqtrade#9344]
## Describe your environment

  * Operating system: Linux v22018107122475583 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux on **Docker**
  * Python Version: Python 3.11.5
  * CCXT version: ccxt==4.0.105
  * Freqtrade Version: freqtrade 2023.9

## Describe the problem:

When trying to force-sell a trade (or in fact all trades using `/forcesell all`) in telegram, the following exception is thrown:

```
freqtrade  | 2023-10-27 05:41:15,153 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/rpc/telegram.py", line 86, in wrapper
freqtrade  |     return await command_handler(self, *args, **kwargs)
freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/rpc/telegram.py", line 1087, in _force_exit
freqtrade  |     await self._force_exit_action(trade_id)
freqtrade  |   File "/freqtrade/freqtrade/rpc/telegram.py", line 1114, in _force_exit_action
freqtrade  |     await loop.run_in_executor(None, self._rpc._rpc_force_exit, trade_id)
freqtrade  |   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
freqtrade  |     result = self.fn(*self.args, **self.kwargs)
freqtrade  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/rpc/rpc.py", line 848, in _rpc_force_exit
freqtrade  |     self.__exec_force_exit(trade, ordertype)
freqtrade  |   File "/freqtrade/freqtrade/rpc/rpc.py", line 827, in __exec_force_exit
freqtrade  |     self._freqtrade.execute_trade_exit(
freqtrade  |   File "/freqtrade/freqtrade/freqtradebot.py", line 1718, in execute_trade_exit
freqtrade  |     amount = self._safe_exit_amount(trade, trade.pair, sub_trade_amt or trade.amount)
freqtrade  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/freqtradebot.py", line 1662, in _safe_exit_amount
freqtrade  |     raise DependencyException(
freqtrade  | freqtrade.exceptions.DependencyException: Not enough amount to exit trade. Trade-amount: 0.017, Wallet: 4.9e-06
```

### Steps to reproduce:

  1. Run freqtrade in docker using docker-compose
  2. Start a trade
  3. Try to force-sell
  
### Observed Results:

I expect the trade(s) to force-sell and not throw an error.

### Relevant code exceptions or logs

**docker-compose.yml:**

```
version: '3'
services:
  freqtrade:
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy BbandRsi
```

**./docker/Dockerfile.custom:**

```
FROM freqtradeorg/freqtrade:stable
RUN pip install --user pyti ta finta
```

**Comment by stash86** [comment]
well, as said in the log, the real amount of the coin is 0.0000 something, which means you might have sold it manually, or the bot has sold it previously but the API didn't return correct response. Whatever it is, the current log isn't enough to show the reason.

**Comment by cloakedch** [comment]
I did not perform any actions outside telegram.
So the solution is to manually delete the trades from the sqlite database?

**Comment by xmatthias** [comment]
The point is a different one - this issue is not caused by the telegram command - but by "something" that happened before.
Right now, the bot assumes it owns 0.017 of something, but the wallet only has a fraction of that.

With the VERY limited logs, it's impossible to tell what's true. 
The point is - telegram failing to exit (or a regular exit failing) is just the symptom - not the cause.

Happy to look at this if we get  more logs (ideally from the whole duration of the trade, but that's most likely not possible) - but at any rate, the logs for at least one iteration - ideally more (before/after this exception).

**Comment by xmatthias** [comment]
Without logs from before this happened, it's impossible to diagnose or look at further.

Feel free to comment below should this still be an issue and you'd like us to look at it - which obviously implies that we get logs of not just the exception, but of what happened before that.
