### ISSUE TITLE
How to set timezone on the bot

### ISSUE THREAD

**Issue by rabichawila** [freqtrade/freqtrade#9345]
## Environment

  * Operating system: ____ Arch Linux x86_64
  * Python Version: _____3.11.5
  * CCXT version: _____ 4.1.13
  * Freqtrade Version: ____ 2023.10-dev-0a5cee6a7
  
                   -`                    cathouse@home-lab 
                  .o+`                   ---------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: OptiPlex 3020 01 
               `+oooooo:                 Kernel: 6.5.7-arch1-1 
               -+oooooo+:                Uptime: 5 hours, 23 mins 
             `/:-:++oooo+:               Packages: 666 (pacman) 
            `/++++/+++++++:              Shell: bash 5.1.16 
           `/++++++++++++++:             Resolution: 1440x900 
          `/+++ooooooooooooo/`           WM: dwm 
         ./ooosssso++osssssso+`          Theme: Adwaita [GTK2/3] 
        .oossssso-````/ossssss+`         Icons: Adwaita [GTK2/3] 

## How to set timezone on the bot

I'm currently on GMT+2 timezone and i see that the bot is returning up to -2hrs candles.

```
{
    "max_open_trades": 3,
    "stake_currency": "USDT",
    "stake_amount": 36,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 100,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
            "BTC/USDT:USDT"
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "44a9c85c715b434e1cd07c0276c32585897312c613e8469196c2b07cb19dbef7",
        "ws_token": "V75vgl2pijpW6q0L6ufrmtw-tRAna7lt9w",
        "CORS_origins": [],
        "username": "freqtrader",
        "password": "123456"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```

**Comment by xmatthias** [comment]
"returning" is relative, and depends on what you're looking at (which is unclear from the above).

Exchanges operate in UTC timezone - and so does the bot.


Similar to exchanges, FreqUI will allow you to change the timezone to your local timezone (via settings) - but the bot itself will continue to operate in UTC timezone - aligned with the exchange.

**Comment by rabichawila** [comment]
Thnks for the reply @xmatthias , Okay in simple English, suppose the time is 10:00 AM (GMT+2) now, And then i run the bot (`dry-run`) and in `bot_loop_start()` callback i fetch and print the `dataframe` .
What i see is that it only gets up to 8:00 AM `candle`.

Nevertheless, you're implying that the candle datetimes are the most recent from the exchange even though they're displayed in UTC timezone, correct?

**Comment by stash86** [comment]
Yes, the bot will fecth the most recent candles. But no, you won't see 0800 am candle, because that's not how candle is being timestamped.

https://botacademy.ddns.net/2023/10/14/misconception-about-candles-timestamp/
