### ISSUE TITLE
Backtest with dynamic-whitelist?

### ISSUE THREAD

**Issue by bavoogd** [freqtrade/freqtrade#935]
Is it possible to backtest using --dynamic-whitelist?

**Comment by xmatthias** [comment]
at the moment it is not possible.

It would be a good idea, but i'm not sure how to implement it yet.
- what should that be based on? the current highest volumes - or historic (at that point in time)?

if using historic data, it would require to have all (non-blacklisted) pairs of the exchange downloaded for the required period - depending on the exchange that could be a ton of pairs.

If using current volume - it would taint falsify the result as this is not how `--dynamic-whitelist` really works, which can change the top 20 pairs if the volume for them changes.

**Comment by GaetanoAr** [comment]
I'ts possible to get a complete pair list from Exchange(i use binance), so we can download all the pair story, and backtest using --dynamic-whitelist?

**Comment by hroff-1902** [comment]
> I'ts possible to get a complete pair list from Exchange(i use binance), so we can download all the pair story, and backtest using --dynamic-whitelist?

Yes, use `freqtrade list-pairs --exchange binance --all --print-json`

**Comment by hroff-1902** [comment]
Btw, `--dynamic-whitelist` was deprecated and removed, it no longer exist.

**Comment by GaetanoAr** [comment]
Thanks you

**Comment by Tekpre012** [comment]
Is there a way to get the top XX volume list pairlist from the excange?

**Comment by hroff-1902** [comment]
> Is there a way to get the top XX volume list pairlist from the excange?

yes, pls read the docs: https://www.freqtrade.io/en/latest/configuration/#dynamic-pairlists

**Comment by xmatthias** [comment]
not for backtesting - not yet anyway - but i'm working on something like this.

however that'll be a "current snapshot" ... not how it was back then (volumes today won't reflect volumes from last month ...).
