### ISSUE TITLE
How to create a second freqtrade bot?

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9363]
## Describe your environment

  * Operating system: ubuntu 20.4
  * Python Version: 3.9
  * CCXT version: 4.0.105
  * Freqtrade Version: 2023.9
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

```
mkdir ft_userdata
cd ft_userdata/

curl https://raw.githubusercontent.com/freqtrade/freqtrade/stable/docker-compose.yml -o docker-compose.yml

docker compose pull

docker compose run --rm freqtrade create-userdir --userdir user_data

docker compose run --rm freqtrade new-config --config user_data/config.json

docker compose up -d
```

According to the official documentation, I followed the above commands to create a freqtrade bot and ran it for two weeks. freqtrade is a great software that allows me to implement my own ideas for quantitative trading. Now I want to create a second bot. Should I create a new directory, for example, `mkdir second_ft_userdata`, and then follow the above commands to create the second bot?

I am not asking because I am lazy or unwilling to try and make mistakes on my own. I am a technical novice. It's just that when I created the first bot, it took me a lot of time and I had to reinstall the system dozens of times on the server. Now that the first bot is successfully trading, I am worried that if I use the above method to create the second bot, it may cause errors and have an impact on the first bot. That's why I came here to seek advice.

Thank you.

**Comment by stash86** [comment]
Read the docs. Use the search box. We already explain how to do multiple bots. Keyword to be searched "multiple instances"

**Comment by WinPoss** [comment]
OK, Thank you very much.

**Comment by xmatthias** [comment]
More specifically - [this](https://www.freqtrade.io/en/latest/advanced-setup/#multiple-instances-using-docker)

---

You can however also use the same method you used for the 1st bot in a 2nd directory - which would keep the 2 instances completely separate - which may be safer if you're unfamiliar with docker.

you will need to change the compose file to use a different port.
