### ISSUE TITLE
How to make futures trading?

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9365]
## Describe your environment

  * Operating system: ubuntu 20.4
  * Python Version: 3.9
  * CCXT version: 4.0.105
  * Freqtrade Version: 2023.9
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

I am using the simulation trading mode.

I have set up a trading bot for futures trading. To test it, I enabled the force entry feature. However, when I executed the following commands, I was unable to make a successful buy:

```
/forcelong BTCUSDT
/forcelong BTC/USDT
```

The prompt displayed: 
`Symbol does not exist or market is not active.`

I am using the OKEX exchange, and my configuration file has only one trading pair in the `whitelist: BTC/USDT`.

Could you please explain why the buy order was not executed? Thank you.

**Comment by xmatthias** [comment]
Futures uses different [pair namings](https://www.freqtrade.io/en/stable/leverage/#pair-namings).
As such, the pair BTC/USDT is invalid (both in the whitelist, as well as in the command).


---

I'd **STRONGLY** suggest to read though the full documentation at least once.
It'll help you get a grasp on freqtrade without opening 100ds of issues with questions which are covered in the documentation - which are automatically answered in a "not so polite" style - as it's a clear sign of "the user wanted us to read the docs for him" - which is wasting our time spent voluntarily on this project, while at the same time also drawing time away from working on actual enhancements, or helping people with actual issues.

Thanks for your understanding.
