### ISSUE TITLE
Incorporating with Pandas Ta 

### ISSUE THREAD

**Issue by Akshat111111** [freqtrade/freqtrade#9366]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement
Incorporating Pandas TA  will really very benificial.Pandas TA provides a wide range of technical indicators and overlays to analyze and interpret the financial data easily.

**Comment by xmatthias** [comment]
Well it's one of the libraries we have [in our documentation](https://www.freqtrade.io/en/latest/strategy-customization/#indicator-libraries) - and it's one that we also depend on, so every user will have it installed.

Now if you're using it in your strategy is totally up to you. as such, i'm not entirely sure what this question refers to exactly?

**Comment by Akshat111111** [comment]
Thankyou so much for your clarification, I have gone to the updated documentation, and its customizable.
