### ISSUE TITLE
Help using informative with another stake currency

### ISSUE THREAD

**Issue by macsim26** [freqtrade/freqtrade#9367]
## Describe your environment

  * Operating system: Ubuntu
  * Python Version:3.10
  * CCXT version: 4.0.105
  * Freqtrade Version: 2023.9
  
## Your question
Hello i want to use informative for each pair in my whitelist but with a different stake currency. I use FDUSD as stake currency but i need the informatives to be with USDT. I have try all i can fing from the help and from the discord but miserably fail...

The code i use is : 

    def informative_pairs(self, metadata: dict):
        # get access to all pairs available in whitelist.
        pairs = self.dp.current_whitelist()
        base = metadata['pair'].split('/')[0]
        # Assign tf to each pair so they can be downloaded and cached for strategy.
        informative_pairs = [(f'{base}/USDT', '1m') for pair in pairs]

        return informative_pairs

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        if not self.dp:
            # Don't do anything if DataProvider is not available.
            return dataframe
        inf_tf = '1m'
        # Get the informative pair
        base = metadata['pair'].split('/')[0]
        informative = self.dp.get_pair_dataframe(pair=f"{base}/USDT", timeframe=inf_tf)

        informative['atr_240'] = ta.ATR(informative ,timeperiod=240)
        informative['atr_360'] = ta.ATR(informative ,timeperiod=360)
        informative['atr_480'] = ta.ATR(informative, timeperiod=480)
        informative['atr_720'] = ta.ATR(informative, timeperiod=720)
        informative['atr_960'] = ta.ATR(informative ,timeperiod=960)
        informative['atr_1440'] = ta.ATR(informative ,timeperiod=1440)
        
        dataframe = merge_informative_pair(dataframe, informative, self.timeframe, inf_tf, ffill=True)  

but all i get are errors!!!
Can you help me please?
Thanks

**Comment by xmatthias** [comment]
well without seeing the errors, it'll be pretty difficult to actually help you.


At a glance, i'd say you can't invent parameters.
`informative_pairs()` does not have a "metadata" parameter, as such that parameter (as well as all subsequent use of metadata within that function) is wrong.

A quick fix for this might be something around the following in your informative function

```
        pairs = self.dp.current_whitelist()
        # Assign tf to each pair so they can be downloaded and cached for strategy.
        informative_pairs = [(f'{pair.split("/")[0]}/USDT', '1m') for pair in pairs]

        return informative_pairs
```

**Comment by macsim26** [comment]
All is ok now... 
You are a genius !!!
