### ISSUE TITLE
Discord webhook always send entry and exit fill

### ISSUE THREAD

**Issue by cabellop5** [freqtrade/freqtrade#9372]
## Describe your environment

I test a dry run bot with latest:develop image in docker

My config in discord is like this:

```
"discord": {
    "enabled": true,
    "webhook_url": "https://discord.com/api/webhooks/some_url",
    "entry_fill": [
        {"Trade ID": "{trade_id}"},
        {"Exchange": "{exchange}"},
        {"Pair": "{pair}"},
        {"Direction": "{direction}"},
        {"Open rate": "{open_rate}"},
        {"Amount": "{amount}"},
        {"Open date": "{open_date:%Y-%m-%d %H:%M:%S}"},
        {"Enter tag": "{enter_tag}"},
        {"Strategy": "{strategy} {timeframe}"},
    ]
}
``` 

## Describe the problem:

In config not has exit_fill but I receive this in discord

**Comment by xmatthias** [comment]
Both `entry_fill` and `exit_fill` have defaults configured - so an effectively valid minimal configuration would look as follows:

``` json
"discord": {
    "enabled": true,
    "webhook_url": "https://discord.com/api/webhooks/some_url",
}
```


Now i'm not sure what reason one could have to disable the exit-fills - so for now, i'm inclined to say "works as intended" - though maybe you have some good reasons to not want to be notified of exit_fills ?

**Comment by cabellop5** [comment]
I don't have any specific reason, I just don't want to receive those messages on Discord and I thought I could do it from the settings
Maybe you could put the enabled parameter inside each element, and control it with that, is only one idea

**Comment by xmatthias** [comment]
that'd be a breaking change -  we can't assume that "enabled" is a reserved keyword "afterwards". 

I've just updated this so you can now assign an empty array to disable either of the 2 default values.
it'll be in develop shortly - and subsequently in the next release in about a month.
