### ISSUE TITLE
entry/exit success rate

### ISSUE THREAD

**Issue by PalanQu** [freqtrade/freqtrade#9374]
Hi, It's an excellent project, I would like to ask a question, I use freqtrade to entry the trade, but because of unfilledtimeout config, it will cancel the order when the order haven't filled after 1min, I want to know the success rate of entry/exit order, is that possible? I think it's a significant information of trading, thx!
```
    "unfilledtimeout": {
        "entry": 1,
        "exit": 60,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
```
```
    order_types = {
        'entry': 'limit',
        'exit': 'limit',
    }
```
freqtrade/freqtradebot.py 1558 line
```
trade.delete()
```

**Comment by xmatthias** [comment]
Depending if the entry is the initial entry, this won't be tracked, as the trade will be deleted (there's no point in keeping 1000nds of unfilled trades in the database).
We could probably have some counter that tells you "deleted X entries" - but that'd probably not be per pair - and just a generic counter that increments by 1 for each deleted trade.

For subsequent entries / exits (via position adjustment callback) - the order will remain in the database as "unfilled".

**Comment by PalanQu** [comment]
@xmatthias thx for your quickly reply, `For subsequent entries / exits (via position adjustment callback) - the order will remain in the database as "unfilled".`  have this been implemented or just a proposal?

**Comment by xmatthias** [comment]
>  `For subsequent entries / exits (via position adjustment callback) - the order will remain in the database as "unfilled".` have this been implemented or just a proposal?

That's a fact - but as said, it only applies to exits, and "non-first entries" (not the initial entry order of a trade) executed via [`adjust_trade_position()`](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position).
you'll then find them as part of the trade object as `trade.orders` - which if unfiltered, will contain all unfilled exits.

**Comment by PalanQu** [comment]
@xmatthias thx for your response!
