### ISSUE TITLE
Using price ticker data (last price) and indicators only update when candles close.

### ISSUE THREAD

**Issue by ManstonGaming** [freqtrade/freqtrade#9380]
## Describe your environment

  * Operating system: Ubuntu 22.04.2 LTS
  * Python Version: Python3
  * CCXT version: 4.1.22 
  * Freqtrade Version: freqtrade 2023.10
  
## Your question

I have been experimenting with all kinds of strategy's and i found that i want to use the realtime price.
and why do i want it? well everytime a 'low' or 'high' crosses a indicator thats the point i want to buy or sell.
so i found this fuction for the "populate_indicators":

```
        if self.dp.runmode.value in ('live', 'dry_run'):
            ticker = self.dp.ticker(metadata['pair'])
            dataframe['last_price'] = ticker['last']
```
Now you see it will buy on the 'high' and 'low'. still its not really working well. 
it seems that the indicators open blank so it uses the open as the "trigger point" instead of the indicator line.

now i just shifted the indiator 1 and it still does the same for both indicators only updates on close. i just want to open a candle with the previous candle indicator line, so we are working with data we already know. how can i make that call?

is this even possible?

**Comment by xmatthias** [comment]
what you're (probably) missing is `process_only_new_candles = False`. 
without this setting - your populate_* methods will run only once per candle - not for every iteration.

your "shifts" are most likely counter-productive / wrong - though without knowing how / what you're shifting, that's difficult to tell.

Aside from that, i'd personally go with [orderbook](https://www.freqtrade.io/en/latest/strategy-customization/#orderbookpair-maximum) - ticker may be slightly delayed (depending on the exchange) - while orderbook is the current orderbook.

**Comment by ManstonGaming** [comment]
No, i'm using the 'process_only_new_candles = False'.
it buys and sells in between of the candles. 

here is a picture i think its easier to get the point across.
blue lines are the indicator and the red and green are the shifted +1

the triggers work on the shifted indicators. so you see in the case it shouldnt triggerd and you can see it on the 2nd picture.

![Naamloos](https://github.com/freqtrade/freqtrade/assets/83367697/11f05531-4572-4f43-a50b-fb2e25d08a4f)

but because we shifted what we already know onto realtime its not there yet on the open of the candle else this candle wouldnt triggerd.

**Comment by stash86** [comment]
Indicators are calculated based of closed candles only.  So in your second picture, the ticker data isn't compared to the red value of that candle, but with the previous candle, which means your ticker was going above it, hence short signal

**Comment by ManstonGaming** [comment]
thats the whole point, is there a way i can get the indicator data on the start of a candle? since that data is already created.

**Comment by xmatthias** [comment]
I think you're missing the point if i'm honest.

dates are candle start dates - freqtrade will not provide you with the candle until the candle closes.
You can however set "current values" into the latest candle available - and cause intra-candle" entries and exits.

that's obviously not backtestable - but will work just fine.
If we talk about indicators - indicators can often be calculated against other values than close - but that depends on the indicator(library) how to do that.

**Comment by ManstonGaming** [comment]
i understand what you are saying. this strat is only possible to see on the live trades and not backtestable. 

so lets say MA line closes on 10
i say ok we shift this 10 to the next candle. than when that one closes i get 15. but the candle 15 opens with the 10 and not the line because it get calculated after it closes. so its not possible to get the 12.5 in that candle? and it will use the 10?

**Comment by stash86** [comment]
Ticker data has no candle body. There is no such thing as open low high close, if the candle hasn't been closed.

**Comment by stash86** [comment]
> i understand what you are saying. this strat is only possible to see on the live trades and not backtestable.
> 
> so lets say MA line closes on 10 i say ok we shift this 10 to the next candle. than when that one closes i get 15. but the candle 15 opens with the 10 and not the line because it get calculated after it closes. so its not possible to get the 12.5 in that candle? and it will use the 10?

Yes, you will use 10 until that candle closes, which will give you new MA value, which will now be used on the next open candle

**Comment by stash86** [comment]
And you don't have to shift anything to use the last MA value. By shifting, you are using the second-from-last MA value

**Comment by ManstonGaming** [comment]
ok, i understand. 
while i was typing i made a calculation in between to give me the value i wanted. since its a fixed value instead of indicator body.

thats also does the trick now. 
thanks for the effort!

**Comment by xmatthias** [comment]
As mentioned above - the "shifts" are most likely counter-productive, as they either shift to something that doesn't exist - or shift from something that doesn't exist just yet - neither being what you want.

Glad we could help :+1:

**Comment by keerthankumar** [comment]
One more question in this, is there anyway to use the tickdata on indicator calculation before the candle closes?

say moving avg calculated till bar-10, now bar 11 is forming but untill the current bar is closed moving average indicator wont be able to reflect on that data. is there anyway the moving average will continously use the bar11 tick data untill its closed? Just like MT5 or Amibroker.

this helps in live trading, to avoid the wide spread or price movement.
