### ISSUE TITLE
install under raspbian 

### ISSUE THREAD

**Issue by fachos** [freqtrade/freqtrade#939]
hi... i try run freqtrade with my raspberry pi3... manual install python3.6, install basic dependencies that python3.6 required.. still got problem with skitlearn and scipy.... cant get thru setup.py... stuck with errors... In requirements.txt scipy=1.1.0 but scikit-learn requires scipy=0.13.3...
i try modify requirements.txt with scipy=1.1.0 also no luck... 

```
Running setup.py install for scikit-learn ... error
    Complete output from command /usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7hzdhjax/scikit-learn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3oomk4h0-record/install-record.txt --single-version-externally-managed --compile:
    Partial import of sklearn during the build process.
    Traceback (most recent call last):
      File "/tmp/pip-build-7hzdhjax/scikit-learn/setup.py", line 148, in get_scipy_status
        import scipy
    ModuleNotFoundError: No module named 'scipy'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7hzdhjax/scikit-learn/setup.py", line 269, in <module>
        setup_package()
      File "/tmp/pip-build-7hzdhjax/scikit-learn/setup.py", line 259, in setup_package
        .format(scipy_req_str, instructions))
    ImportError: Scientific Python (SciPy) is not installed.
    scikit-learn requires SciPy >= 0.13.3.
    Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html
```
can you guide me... thank you

**Comment by xmatthias** [comment]
Hi,
i took the liberty to fix the formatting a bit - as it was barely readable.

the problem appears to be related to scipy ... 
i don't think it's related to the version.

please try to install scipy from the apt repositories:
```bash
sudo apt-get update 
sudo apt-get install python3-scipy
```
Please note that the above installs scipy globally (in case you would like to use a virtual environment ...)
after the above, run the installation-instructions again.

**Comment by fachos** [comment]
hi xmatthias.... i again try sudo pip3.6 install scipy==0.13.0.... and scikit requirement already satisfied.. in the end it hold running install scikit... im waiting and will let you know.... thank you
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(.env) pi@raspberrypi~/freqtrade $ sudo pip3.6 install scipy==0.13.3
Collecting scipy==0.13.3
  Downloading https://files.pythonhosted.org/packages/2f/12/565c08132db50a0ba34a33e0901f3d1d4d72e3b432ea828e4d87be5a4991/scipy-0.13.3.tar.gz (10.7MB)
    100% |████████████████████████████████| 10.7MB 26kB/s
Installing collected packages: scipy
  Running setup.py install for scipy ... done
Successfully installed scipy-0.13.3
You are using pip version 9.0.3, however version 10.0.1 is available.
(.env) pi@raspberrypi~/freqtrade $ sudo pip3.6 install -e .
Obtaining file:///home/pi/freqtrade
Requirement already satisfied: ccxt in /usr/local/lib/python3.6/site-packages (from freqtrade==0.17.0)
Requirement already satisfied: SQLAlchemy in /usr/local/lib/python3.6/site-packages (from freqtrade==0.17.0)
Requirement already satisfied: python-telegram-bot in /usr/local/lib/python3.6/site-packages (from freqtrade==0.17.0)
Requirement already satisfied: arrow in /usr/local/lib/python3.6/site-packages (from freqtrade==0.17.0)
Requirement already satisfied: requests in /usr/local/lib/python3.6/site-packages (from freqtrade==0.17.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.6/site-packages (from freqtrade==0.17.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.6/site-packages (from freqtrade==0.17.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/site-packages (from freqtrade==0.17.0)
Collecting scikit-learn (from freqtrade==0.17.0)
  Using cached https://files.pythonhosted.org/packages/f5/2c/5edf2488897cad4fb8c4ace86369833552615bf264460ae4ef6e1f258982/scikit-learn-0.19.1.tar.gz
**Requirement already satisfied: scipy in /usr/local/lib/python3.6/site-packages (from freqtrade==0.17.0)
Collecting jsonschema (from freqtrade==0.17.0)**
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting TA-Lib (from freqtrade==0.17.0)
  Using cached https://files.pythonhosted.org/packages/90/05/d4c6a778d7a7de0be366bc4a850b4ffaeac2abad927f95fa8ba6f355a082/TA-Lib-0.4.17.tar.gz
Collecting tabulate (from freqtrade==0.17.0)
  Using cached https://files.pythonhosted.org/packages/12/c2/11d6845db5edf1295bc08b2f488cf5937806586afe42936c3f34c097ebdc/tabulate-0.8.2.tar.gz
Requirement already satisfied: cachetools in /usr/local/lib/python3.6/site-packages (from freqtrade==0.17.0)
Collecting coinmarketcap (from freqtrade==0.17.0)
  Using cached https://www.piwheels.org/simple/coinmarketcap/coinmarketcap-5.0.3-py3-none-any.whl
Requirement already satisfied: aiohttp>=3.0.1; python_version >= "3.5.3" in /usr/local/lib/python3.6/site-packages (from ccxt->freqtrade==0.17.0)
Requirement already satisfied: aiodns==1.1.1; python_version >= "3.5.3" in /usr/local/lib/python3.6/site-packages (from ccxt->freqtrade==0.17.0)
Requirement already satisfied: cchardet==2.1.1; python_version >= "3.5.3" in /usr/local/lib/python3.6/site-packages (from ccxt->freqtrade==0.17.0)
Requirement already satisfied: yarl==1.1.0; python_version >= "3.5.3" in /usr/local/lib/python3.6/site-packages (from ccxt->freqtrade==0.17.0)
Requirement already satisfied: setuptools>=38.5.1 in /usr/local/lib/python3.6/site-packages (from ccxt->freqtrade==0.17.0)
Requirement already satisfied: certifi>=2018.1.18 in /usr/local/lib/python3.6/site-packages (from ccxt->freqtrade==0.17.0)
Requirement already satisfied: future>=0.16.0 in /usr/local/lib/python3.6/site-packages (from python-telegram-bot->freqtrade==0.17.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/site-packages (from arrow->freqtrade==0.17.0)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests->freqtrade==0.17.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests->freqtrade==0.17.0)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.6/site-packages (from pandas->freqtrade==0.17.0)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.6/site-packages (from pandas->freqtrade==0.17.0)
Collecting requests-cache>=0.4.13 (from coinmarketcap->freqtrade==0.17.0)
  Using cached https://files.pythonhosted.org/packages/00/62/9e45a38988cb48c474805a1626439f4d9a486a042bd077af888fa8b17a64/requests_cache-0.4.13-py2.py3-none-any.whl
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.6/site-packages (from aiohttp>=3.0.1; python_version >= "3.5.3"->ccxt->freqtrade==0.17.0)
Requirement already satisfied: multidict<5.0,>=4.0 in /usr/local/lib/python3.6/site-packages (from aiohttp>=3.0.1; python_version >= "3.5.3"->ccxt->freqtrade==0.17.0)
Requirement already satisfied: async_timeout<4.0,>=3.0 in /usr/local/lib/python3.6/site-packages (from aiohttp>=3.0.1; python_version >= "3.5.3"->ccxt->freqtrade==0.17.0)
Requirement already satisfied: idna-ssl>=1.0 in /usr/local/lib/python3.6/site-packages (from aiohttp>=3.0.1; python_version >= "3.5.3"->ccxt->freqtrade==0.17.0)
Requirement already satisfied: pycares>=1.0.0 in /usr/local/lib/python3.6/site-packages (from aiodns==1.1.1; python_version >= "3.5.3"->ccxt->freqtrade==0.17.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/site-packages (from python-dateutil->arrow->freqtrade==0.17.0)
Installing collected packages: scikit-learn, jsonschema, TA-Lib, tabulate, requests-cache, coinmarketcap, freqtrade
  **Running setup.py install for scikit-learn ... -**
- - - - - - - - - - - - - - -
its running slow... have to waittttt

**Comment by dericdesta** [comment]
I've installed freqtrade an a rpi, too. You can use conda (with berryconda) to install the PyData stack much faster.

**Comment by fachos** [comment]
hi matthias.... i did install using scipy 0.13.3.... and the bot running... 
thank you....

**Comment by fachos** [comment]
hi dericdesta.... can you help me with your setup? i like to try.... please guide me... thank you...

**Comment by dericdesta** [comment]
Just install miniconda for armv7 as described [here](https://stackoverflow.com/a/39371773). Then create and set up an environment:
```sh
conda config --add channels rpi
conda install python=3.6
conda create -n freqtrade python=3.6
```
Then reopen the terminal, activate the environment (`source activate freqtrade`) and install the relevant packages via conda (`conda install scipy`) or pip.

**Comment by gcarq** [comment]
@dericdesta Thanks a lot! How long does it usually take to install it with conda?

**Comment by dericdesta** [comment]
Actually, setting up environments with python 3.6 with conda is super fast (I prefer it over virtualenv). The time-critical installations of numpy, scipy and so on is  speeded up considerably, since the rpi channel has pre-compiled versions of those packages.

**Comment by shusso** [comment]
would be nice if someone could make a PR for the documentation change for this
https://github.com/freqtrade/freqtrade/blob/develop/docs/installation.md

**Comment by xmatthias** [comment]
Going to close this as #1175 added documentation on how to install on a Raspberry PI
