### ISSUE TITLE
O

### ISSUE THREAD

**Issue by Toddy1242** [freqtrade/freqtrade#9401]
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*

**Comment by froggleston** [comment]
Closed, and reported likely spam user.
