### ISSUE TITLE
adjust_trade_position() | How to distinguish long or short trades?

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9406]
## Describe your environment

  * Operating system: ubuntu 20.4
  * Python Version: 3.8
  * CCXT version: 4.0.105
  * Freqtrade Version: 2023.10
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

Hello, I saw in the [official documentation](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position) that the `adjust_trade_position()` function can be used to sell half of the position. I would like to differentiate between long and short positions, but I couldn't find a tutorial on how to do that. How can I achieve this?

```
def adjust_trade_position(self, trade: Trade, current_time: datetime,
                              current_rate: float, current_profit: float,
                              min_stake: Optional[float], max_stake: float,
                              current_entry_rate: float, current_exit_rate: float,
                              current_entry_profit: float, current_exit_profit: float,
                              **kwargs) -> Optional[float]:

        if current_profit > 0.05 and trade.nr_of_successful_exits == 0:
            # Take half of the profit at +5%
            return -(trade.stake_amount / 2)

        return None
```

Thank you.

**Comment by WinPoss** [comment]
Can it be judged by `trade.direction == 'LONG'`?

**Comment by stash86** [comment]
read the docs. Search for `trade object`

**Comment by WinPoss** [comment]
Yes, I find it!!! Thank you!
