### ISSUE TITLE
it is possible to run multiple bots use same chatID and different token?same chatID,pay attention!

### ISSUE THREAD

**Issue by csquan** [freqtrade/freqtrade#9410]
I mean use same chatID ,[multiple instances](https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade) does not cover this,read many times,

**Comment by stash86** [comment]
we already pay attention and we have given you the answer.

**Comment by csquan** [comment]
[multiple instances](https://www.freqtrade.io/en/stable/advanced-setup/#running-multiple-instances-of-freqtrade) can use same chatid?
