### ISSUE TITLE
Not able to acces FreqUI

### ISSUE THREAD

**Issue by Arie6414** [freqtrade/freqtrade#9411]
* Operating system:  Synology DSM 7.2-64570 update 1
  * Python Version: 3.9
  * CCXT version: ?
  * Freqtrade Version: 2023.10
  
I was struggling to acces freqUI. Tried everything as already mentioned in several related issues. I am also new to docker-compose because portainer is doing very well for me. But nevertheless I tried a lot of thing to get it working. And at this moment FreqUI is working as it should. 

My issue was: after `sudo docker-compose up -d` the container appeared in portainer with administrator rights. I was not able to launch the previous command without sudo. Does anyone know why this is? 

gr Arjen

**Comment by xmatthias** [comment]
This sounds like a very generic docker / portainer issue.

i don't think that's an issue we are able to assist you with.

A shot in the dark:
most likely, the user you're using is not part of the docker group - hence docker-compose fails - as your user lacks the proper permission.

**Comment by Arie6414** [comment]
Thanks for replying! That is something i did not checked yet. But with all other containers i did not have any issues with :admin, restricted or public users. But i can figure something out to add A user group to the docker compose yml. 

Thanks again!

**Comment by perkmeister** [comment]
Or before you start docker you could try adding yourself to the docker group, logging out then back in, and restarting the docker daemon:
```
sudo usermod -aG docker $USER
log out then back in for that to have an effect, then
sudo systemctl restart docker 
```

**Comment by Arie6414** [comment]
> Or before you start docker you could try adding yourself to the docker group, logging out then back in, and restarting the docker daemon:
> 
> ```
> sudo usermod -aG docker $USER
> log out then back in for that to have an effect, then
> sudo systemctl restart docker 
> ```

Thnx, easy but effective !
