### ISSUE TITLE
freqtrade.commands.trade_commands - ERROR - `populate_entry_trend` or `populate_buy_trend` must be implemented.

### ISSUE THREAD

**Issue by Johan1974** [freqtrade/freqtrade#9412]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.5 (`python -V`)
  * CCXT version: N/A (Not using CCXT)
  * Freqtrade Version: 2022.11 (`freqtrade -V`)

## Your question

I have a custom strategy class (`MyOwnStrategyAI`) that extends `IStrategy`. The strategy interface version is set to 3 (`INTERFACE_VERSION = 3`). I have implemented the `populate_entry_trend` method in my strategy. Despite having the method implemented, I'm consistently getting the following error:

```
freqtrade.commands.trade_commands - ERROR - `populate_entry_trend` or `populate_buy_trend` must be implemented.
```

### Steps to Reproduce

1. Define a custom strategy class (`MyOwnStrategyAI`) with the `populate_entry_trend` method implemented.
2. Set the strategy interface version to 3 (`INTERFACE_VERSION = 3`).
3. Configure the strategy with relevant parameters.
4. Run the strategy using Freqtrade.

### Additional Information

```python
# Relevant snippet of the strategy code
# Define entry conditions in the 'populate_entry_trend' method
def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
    # Define entry conditions (Bullish EMA crossovers and Parabolic SAR below price)
    conditions = (
        (dataframe["ema5_red"] > dataframe["ema8_blue"])
        & (dataframe["ema8_blue"] > dataframe["ema13_green"])
        & (dataframe["sar"] < dataframe["close"])
    )

    # Set entry signals in the dataframe
    dataframe.loc[conditions, "buy_signal"] = 1

    return dataframe
```

### Expected Behavior

I expect the `populate_entry_trend` method to be recognized and executed without errors.

### Screenshots or Logs

No relevant screenshots or logs available.

## Note

I have reviewed the documentation and searched for similar issues but couldn't find a solution. Please provide insights into why I might be encountering this error.

**Comment by stash86** [comment]
Well, the bot can't find it. Your strategy must have some mistakes. Without looking at any code, that's all I can say

**Comment by stash86** [comment]
And `buy_signal` isn't the correct column name

**Comment by xmatthias** [comment]
Most likely, it's an indentation error (the method is not part of the class).

Alternatively, maybe it's finding a different file with the same classname and loads that first - which is also a quite common error made.

**Comment by Johan1974** [comment]
I found better sample files and now it is working. Stil not sure why it was telling me the function is not there when it is.
But for now it is working and i can continue optimizing and learning more about the use of freqai 

Thanks!
