### ISSUE TITLE
ccxt.base.errors.ExchangeError: okx {"msg":"API key doesn't exist","code":"50119"}

### ISSUE THREAD

**Issue by theo-wq** [freqtrade/freqtrade#9422]
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.okx.com/api/v5/asset/currencies

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 480, in _load_markets
    self._markets = self._api.load_markets(params={})
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 1446, in load_markets
    currencies = self.fetch_currencies()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/okx.py", line 1507, in fetch_currencies
    response = self.privateGetAssetCurrencies(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/types.py", line 26, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3157, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3154, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/exchange.py", line 627, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/okx.py", line 6467, in handle_errors
    raise ExchangeError(feedback)  # unknown message
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ccxt.base.errors.ExchangeError: okx {"msg":"API key doesn't exist","code":"50119"}
2023-11-13 23:28:08,713 - freqtrade.commands.trade_commands - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.

hey so this happen when i disable the dry_run and i see there is an author issue but I can figure out how to solve this problem
Thanks !!

**Comment by stash86** [comment]
well, as the error said, no API key.

**Comment by stash86** [comment]
Make sure you created API key on the exchange, and give it to the bot inside config.json

**Comment by theo-wq** [comment]
well i did but i thinks it's an header problem cause i get this message {"msg":"Request header OK-ACCESS-KEY can not be empty.","code":"50103"}

**Comment by stash86** [comment]
then you are putting it wrong. Your `key` is empty

**Comment by theo-wq** [comment]
I just put it in the config.json and i triple check there is nothing to do?

**Comment by stash86** [comment]
paste your config here. Replace your API details with random characters

**Comment by theo-wq** [comment]
"exchange": {
        "name": "okx",
        "key": "xxxxxxxxxxxxxxx",
        "secret": "yyyyyyyyyyy",
        "password": "eeeeeeeeeee!",
        "OK-ACCESS-KEY": "zddddddd",
        "OK-ACCESS-PASSPHRASE": "zzzzzzzzzzz",
        "ccxt_config": {},
        "ccxt_async_config": {},

thanks

**Comment by theo-wq** [comment]
maybe it's because i use the wallet api key instead of the exchange one ?

**Comment by xmatthias** [comment]
for OKX, you'll only need these 3 values, all of which you'll find on the OKX exchange page.
Iirc, you'll get shown the secret only once - so you might have to receate the API key if you've not stored that.

```
    "name": "okx",
    "key": "xxxxxxxxxxxxxxx",
    "secret": "yyyyyyyyyyy",
    "password": "eeeeeeeeeee!",
```

Freqtrade does not want  / need any "wallet api key" - it's a regular API okx offers.

**Comment by theo-wq** [comment]
so even if i need to trade futures i still take the api key of the exchange like this ? https://www.okx.com/account/my-api

**Comment by xmatthias** [comment]
what changes is the permissions you give to the key - not where you define the key.
