### ISSUE TITLE
margin freqtrade bot

### ISSUE THREAD

**Issue by theo-wq** [freqtrade/freqtrade#9426]
Hi,
I'm starting my futures bot but it's banned in my country so i was wondering if margin trading is available right now and if yes which exchange is compatible
thanks !

**Comment by froggleston** [comment]
No, margin is not available.

**Comment by theo-wq** [comment]
thanks man

**Comment by perkmeister** [comment]
Although you *might* be able to copy trade on spot with a margin account. I've no idea how feasible this is, but this guy runs copy trading code on a server that simply copies the spot trades and executes corresponding margin trades with leverage. Use at own risk. It looks safe to me but what do I know? ;) You need to check and double check that code is not doing anything malicious of course, but you'll have the source code for it.
https://www.youtube.com/watch?v=1VBpqjcGgJM

**Comment by theo-wq** [comment]
OOOH this seem very nice, your THE man thx :)

**Comment by stash86** [comment]
or trade futures on another exchange. Bybit?

**Comment by theo-wq** [comment]
actualy i live in the uk so futures contracts are banned :( right ?

**Comment by perkmeister** [comment]
I'm not convinced it's actually 'banned' per se for a UK resident. The actual wording is "If your firm carries out marketing, distribution or selling activities in, or from, the UK" those operations should cease, it doesn't mention residence. So can a UK resident use an exchange not regulated by the FCA, who doesn't require KYC, who doesn't target the UK market and who sells in their own jurisdiction and is not based in the UK? Bitget seems to be a candidate for that now Bybit requires KYC and doesn't allow UK citizens to access these services.
