### ISSUE TITLE
diferent results indicators

### ISSUE THREAD

**Issue by anakein** [freqtrade/freqtrade#9428]
I have been puzzled for some time by differences that I did not understand.

Now that everything else has been ruled out. Is it freqtrade problem?

We have 2 identical raspberries, with a copied image, the only difference is the freqtrade update that I did and you can see that they are different versions.

With the same strategy. we can see really different results.

green line is me entry line and Red line is exit line, but they are very different in each bot, with everything (rpi, strategy) being identical.

![1](https://github.com/freqtrade/freqtrade/assets/1563663/0295d260-9c9a-4498-b48d-48cbc50892ee)
![2](https://github.com/freqtrade/freqtrade/assets/1563663/ea13595f-cac4-4aea-b1a1-d4b304f40c44)

**Comment by froggleston** [comment]
You didn't start the bots at the same time, so could well be a problem with recursive indicators and not enough startup candles: https://www.freqtrade.io/en/stable/recursive-analysis/

**Comment by anakein** [comment]
mmm, testing it, thanks

**Comment by xmatthias** [comment]
at a glance, only the "exit_line" seems to be different - but it seems rather similar, potentially only shifted up by ~0.5.

without knowing the strategy (or rather, the indicators, how they're combined for this particular signal), it'll be rather difficult to determine what the actual difference is (maybe it's doing some aggregate on "whatever").

Obviously there's potentially been dependency updates, too (also a bit depending on your mode of installation) - but freqtrade itself has no say in HOW your indicators will actually be calculated.
