### ISSUE TITLE
Can I do DCA Martingale like 3commas dca bots in this trading bot?

### ISSUE THREAD

**Issue by REFLEXGAMING007** [freqtrade/freqtrade#9431]

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---


Using the [adjust trade position](https://www.freqtrade.io/en/latest/strategy-callbacks/#adjust-trade-position) callback, you can do DCA bots.

What strategy that follows (when to buy, ...) is however up to you - and (as free, open source bot) we do not provide pre-made strategies which are designed to "just work", which you sometimes find on commercial bots.
