### ISSUE TITLE
timerange

### ISSUE THREAD

**Issue by theo-wq** [freqtrade/freqtrade#9433]
Hey everyone 
I was wondering if it is possible to let the strategie active only for a certain timerange of the day, and if yes i would love to know how.
Thanks a lot !!

**Comment by stash86** [comment]
Use confirm_trade_entry, you get current_time there. Do whatever you want with it to reject or allow trade

**Comment by theo-wq** [comment]
oh nice directly in the strategy ?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Well it depends what exactly you're after
If it's to prevent entries - you can do that either through confirm_trade_entry - or by adding something like `(dataframe['date'].dt.hour == 5)` to your conditions (this will ONLY show valid signals at 5AM UTC).

If it's to prevent both entries and exits (basically disable all trading possibilities from the bot) - then the confirm methods for [entry](https://www.freqtrade.io/en/stable/strategy-callbacks/#trade-entry-buy-order-confirmation) and [exit](https://www.freqtrade.io/en/stable/strategy-callbacks/#trade-exit-sell-order-confirmation) are your way to go.

This way, you can also disable ROI / stoploss exits - though obviously I'd not recommend this for stoploss - as it'll deactivate your risk-control - and you have to assume 100% risk - as you might be "blocking" a stoploss - resulting in a way larger loss than anticipated.

in futures, you'll still get liquidations (these can't be prevented and won't call any callbacks, as it's something the exchange enforces directly) - but the rest could be disabled.
