### ISSUE TITLE
ROI: power distribution VS discrete values

### ISSUE THREAD

**Issue by dctremblay** [freqtrade/freqtrade#9437]
How's the ROI currently working, it seems to be discrete values.

Why not some kind of power distribution instead?

Thanks

**Comment by stash86** [comment]
Try reading the docs, it won't be discrete anymore. Feel free to use whatever roi table you think is best. Use custom_exit for more advanced logic

**Comment by dctremblay** [comment]
Thanks for your quick answer! No worries I spent weeks in the docs 😊

Yup I already implemented it in `custom_exit`, was just wondering.

**Comment by stash86** [comment]
Then you should be familiar with custom_exit
