### ISSUE TITLE
Access to data for all individual pairs in pairlist

### ISSUE THREAD

**Issue by infiniteneurotech** [freqtrade/freqtrade#9457]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.10.11 (`python -V`)
  * CCXT version: 4.0.105 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.9 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hi, I want to create an indicator that is the average of the close prices of every pair in my static pair list. So it would look like BTC['close'] + ETH['close'] + ADA['close'] / 3 for example. I've tried using dataprovider and metadata['pair'] but I'm beginning to wonder if it's possible given Freqtrade runs for each pair separately. Can this be done in a way that will work with backtesting, and if so could you please point me in the right direction?

Thanks

**Comment by xmatthias** [comment]
you can simply use `dp.get_pair_dataframe()` in a loop for all pairs in the whitelist (`dp.current_whitelist()`).
If you stick to the main timeframe - there's no need for further configuration of informative pairs (which is usually necessary for `get_pair_dataframe()`.

a (slightly different) example is [here](https://www.freqtrade.io/en/latest/strategy-customization/#complete-data-provider-sample) - but this area of the docs (this and a bit above it) will contain all you'll need, assuming some basic understanding of pandas and combining dataframes.

**Comment by infiniteneurotech** [comment]
Thanks for your help. I've ended up with this:

```
pairs = self.dp.current_whitelist()
    
        pair_dataframes = {}

        for pair in pairs:
            pair_df = self.dp.get_pair_dataframe(pair=pair)
            
            pair_df['pair'] = pair
            
            pair_dataframes[pair] = pair_df

        rdf = pd.concat(pair_dataframes.values())

```

It might not be the best way to get it done but it seems to work. Thanks again

**Comment by xmatthias** [comment]
Looks roughly correct - though you might want to do an EMA calculation on that pair_df immediately ... and eventually reduce the timeframe to only that column to save some memory.
