### ISSUE TITLE
Empty candle (OHLCV) data for pair LTC/USDT with informative 

### ISSUE THREAD

**Issue by boyitnew** [freqtrade/freqtrade#9462]
hi 
My main timeframe is 15m, and I wanted to add a 30m timeframe as well by using informative.
So, I added the following code to the populate_indicators section:

```
inf_tf = '30m'
if self.dp:
    informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf)
    informative['trend_close_t3'] = ta.EMA(informative['close'], timeperiod=3)
    informative['trend_close_t6'] = ta.EMA(informative['close'], timeperiod=4)
    dataframe = merge_informative_pair(dataframe, informative, self.timeframe, inf_tf, ffill=True)
    return dataframe
```

Unfortunately, my candles are being returned empty, and I’m getting this error:
“WARNING - Empty candle (OHLCV) data for pair LTC/USDT”

**Comment by froggleston** [comment]
Without seeing the full function, it looks like you're returning the dataframe "too early", i.e. after merging, but before the rest of the function is given a chance to run.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Aside from that - you're most likely missing the pair/timeframe combination in the [informative pairs](https://www.freqtrade.io/en/stable/strategy-customization/#informative-pairs) function, which in the method you're using, you're responsible to handle yourself.
