### ISSUE TITLE
Bybit futures sometimes stop trading with error message  : Could not load tickers due to BadSymbol.

### ISSUE THREAD

**Issue by macsim26** [freqtrade/freqtrade#9463]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: 3.10
  * CCXT version: 4.1.22
  * Freqtrade Version:  2023.10
  

## Describe the problem:

Hello on Bybit futures This message appair : freqtrade.exchange.common - WARNING - get_tickers() returned exception: "Could not load tickers due to BadSymbol. Message: bybit does not have market symbol BTC-15DEC23". Retrying still for 3 times.

And the bot stop working until restarted

How can i fix this?

Thanks

  // paste your log here
[erreur.txt](https://github.com/freqtrade/freqtrade/files/13457345/erreur.txt)

**Comment by xmatthias** [comment]
`BTC-15DEC23` is not a valid futures symbol - therefore you'll have to remove it.

Freqtrade only supports perpetual swaps - not expiring futures (which is what this would be about).

**Comment by macsim26** [comment]
Hello i have not this symbol in my pairs!
Here is my config file : 
[configbybit.json](https://github.com/freqtrade/freqtrade/files/13460890/configbybit.json)

I believe it's when Bybit pushed another pair in their cached leveraged pair that this bug occurs :
2023-11-24 15:24:07 - freqtrade.exchange.exchange - INFO - Using cached leverage_tiers.
2023-11-24 15:24:07 - freqtrade.exchange.exchange - INFO - Done initializing 281 markets.
just before it was 280 markets...

Here is a more complete log : 
[erreur.txt](https://github.com/freqtrade/freqtrade/files/13461023/erreur.txt)

**Comment by macsim26** [comment]
As i understand it's a Bybit option :

![Capture du 2023-11-24 17-47-20](https://github.com/freqtrade/freqtrade/assets/88237677/bd285aac-1e4e-449f-b2e6-7ec12b09ad00)

but as you can see i my config i have nothing about this pair and i have saw other persons talking about this problem with Bybit on the discord but none has an answer...
Thanks

**Comment by macsim26** [comment]
For me it's really a bug but i solved it making a cron task who read the log and restart the service if "Could not load tickers due to BadSymbol" is present in the last 20 lines... Thanks

**Comment by xmatthias** [comment]
That's an interesting problem indeed - one i'm tempted to say is (at least in part) caused by ccxt.

a (very simple) reproduction for this is the following:

``` python
import ccxt
exchange = ccxt.bybit({    'options': {'defaultType': 'swap'} 
    })
lm = exchange.load_markets()
del lm['BTC/USDC:USDC-231215']

exchange.fetch_tickers()
```

now in a running bot, it'll not happen in this sequence - but
* the pair will get listed and therefore "appear" in the various endpoints.
* until we reload markets  (the `load_markets()` call - by default, once every hour) - this pair is (partially) unknown to ccxt - which therefore fails.

---

now i don't think you'll need to restart the bot via cron (or anything else) - as they'll not be listing this pairs every day - and it can be pretty easily worked around by lowering `markets_refresh_interval` (in the exchange subsection).

**Comment by xmatthias** [comment]
aside from that, thelatest develop (see linked commit) will contain a fix for this, which forces a reload of the markets.

**Comment by macsim26** [comment]
Hello the thing is that in my case the bot seems locked on this,
 freqUI doesn't update anymore the candles and there is no other messages in the log if not this one and heartbeat until config and strategy reloaded...
So i am not sure that doesn't broke the normal running and as i don't know how to force reload strat and config i prefer to restart the service...
I have only seen this case two times in two weeks but i want to be sure my BOT is running without supervision...
Another thing you should add a lightning BTC address in the read-me so we can easily give you tips for your help...
Thanks

PS i just saw the commit will give a try thanks a lot...

**Comment by xmatthias** [comment]
I do have this in the logs, too - but it disappears within 1 hour.

I had it start on 08:33 - and stop at 09:03.
the call `Done initializing 281 markets.` terminates the behavior, as it's the regular market reload.
