### ISSUE TITLE
Error: No module named 'ephem'

### ISSUE THREAD

**Issue by rr8733380** [freqtrade/freqtrade#9465]
Perhaps this question has already been asked, but how can I fix this error on macOS m1 if I am building a project through docker?

Error: **freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/MyStrategy.py due to 'No module named 'ephem''**

## Describe your environment

  * Operating system: macos
  * Python Version: 3.9.6
  * Freqtrade Version: freqtrade 2023.10

**Comment by stash86** [comment]
https://www.freqtrade.io/en/stable/docker_quickstart/#additional-dependencies-with-docker

**Comment by rr8733380** [comment]
Sorry, but I didn't quite understand what needs to be done. Can you please give an example of code with ephem?

**Comment by stash86** [comment]
look at the example, the example install `pyti`. Now find the library name for ephem. Google is your friend

**Comment by rr8733380** [comment]
my `Dockerfile.custom` now looks like this: 
```
FROM freqtradeorg/freqtrade:develop

# Switch user to root if you must install something from apt
# Don't forget to switch the user back below!
# USER root

# The below dependency - pyti - serves as an example. Please use whatever you need!
RUN pip install --user ephem

# Switch back to user (only if you required root above)
# USER ftuser
```

What should I write in the `docker-compose.yml` in image, what is `freqtrade_custom`?

**Comment by stash86** [comment]
any name you want to give it

**Comment by rr8733380** [comment]
thank you so much

**Comment by rr8733380** [comment]
If I need to use
`image: freqtradeorg/freqtrade:develop_freqaitorch` for `FreqAi`, but I have image installed with my value for `ephem`. 
How do I install two images?

**Comment by stash86** [comment]
change the top of your `Dockerfile.custom`?

**Comment by perkmeister** [comment]
Not sure it should ask for the user to be switching to root, sudo maybe.

**Comment by stash86** [comment]
there is no need if the permission is set correctly

**Comment by perkmeister** [comment]
Indeed, I wonder if it's related to the user not being a member of the docker group?

**Comment by xmatthias** [comment]
> Indeed, I wonder if it's related to the user not being a member of the docker group?

Not sure what you're refering to ? 
the switch to root in the custom dockersample is there for eventual system level dependencies.
pip dependencies should be installed at user level (with `--user`) - and there shouldn't be any need for root permissions.


The docker group would be relevant on the host, not within the container (there usually is no docker group in the container) - but i'm not sure that's relevant for this issue ... ?
