### ISSUE TITLE
freqtrade strategy to freqai

### ISSUE THREAD

**Issue by Vain10** [freqtrade/freqtrade#9466]
## Describe your environment

  * Operating system: __docker__
  * Python Version: __3.10___ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
Hi 
 i have a freqtrade strategy which contains many indicators but now i want to use it with freqai and i just want to use the entry signal with % to be trained by freqtrade, is it possible?  and if so can u give a simple example on how to that.
thankyou for your time

**Comment by xmatthias** [comment]
I'll encourage you to read through the [freqAI documentation](https://www.freqtrade.io/en/stable/freqai/).

A freqAI strategy is not "that" different - but you need to understand the different parts that go into it, following which, you can implement the various [feature engineering](https://www.freqtrade.io/en/stable/freqai-feature-engineering/) methods you think you'll need (maybe all, maybe some, ...).

the only "actual" change will be in the configuration (the freqAI section), and the actual call to freqai (`dataframe = self.freqai.start(dataframe, metadata, self)`) in populate_indicators().

you'll then obviously also have to "somehow" use the added columns in the dataframe (if you don't, freqai will run but won't be used by your strategy).

You can also go in reverse - starting with a freqAI sample and then migrating your logic to that strategy - which will probably be easier to get started with freqAI.
