### ISSUE TITLE
Overall Risk Manages

### ISSUE THREAD

**Issue by linsua01** [freqtrade/freqtrade#9479]
## Your question

Hello, I hope you have a fantastic Monday.

I am trying to develop a multi-pair strategy that manages the risk of the overall portfolio e.g. 0.2 (20%), this means that the bot should not open more trades if

current_risk > total_balance * risk (0.2)

where "current_risk" would be the sum of the risk of each open trade, calculated based on the stop-loss of each trade,

This currect_risk should be decreased as the stop-loss strategy begins to be executed!

I'm looking at the documentation and I don't see any method that gives me this information, and I understand that I should implement it.

What would be the most efficient and recommended way?

Thank you very much!

**Comment by Ltei** [comment]
Hi, you can fetch the current trades (stored in a DB) for example in confirm_trade_entry so you can cancel trade entry if your computed risk would be above threshold

See https://www.freqtrade.io/en/stable/trade-object/

**Comment by linsua01** [comment]
Thank you Ltei,

Yes, I have tried it but the object that is returned does not have information about the stop-loss.

I tried this:
open_trades = Trade.get_trades_proxy(is_open=True)

Result:
Trade (id = 1151, pair = XRP/USDT, amount = 31.00000000, is_short = False, leverage = 1.0, open_rate = 0.61130000, open_since = 2023-11-23 08:00:00),

Exist any library to directly access the database and run a raw query?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---


best execute a `dir(trade)` on the object - you'll discover that it has much more to offer than what the `__repr__()` output (which is what you're looking at above) has to offer.

Not all are safe to use at all times (hence not all are documented) - but `stop_loss_pct` and `stop_loss` (and their corresponding `initial_*` counterparts) are pretty safe once the order filled.

**Comment by linsua01** [comment]
## Describe your environment

  * Operating system: macOS Catalina (10.15.7)
  * Python Version: 3.11.5 
  * CCXT version: ccxt==4.1.22
  * Freqtrade Version: freqtrade 2023.10
  * Running in docker.

Hi Matthias, thanks for the response, sorry for not following the rules, Im sending my setup at the top.

Now I can access the stop-loss information, I think I can get what I need.

On the other hand, I would like to ask.

I would like to manage the stop-loss based on technical indicators, I have studied custom_stop-loss, what should I do if I want to put the initial stop-loss at the Low of the candle that marks the signal and keep it there until the next N periods, and then move it to the minimum of that period.

I attach an image to better explain the concept.

Thank you!

<img width="681" alt="Captura de pantalla 2023-11-28 a las 9 35 01" src="https://github.com/freqtrade/freqtrade/assets/43039817/135fb5b4-39d0-472a-a881-19d7b63f9aaa">

**Comment by xmatthias** [comment]
Well we do have examples in the docs for both the [initial stoploss](https://www.freqtrade.io/en/stable/strategy-callbacks/#time-based-trailing-stop-with-after-fill-adjustments), as well as how to set a stoploss based on [some indicator](https://www.freqtrade.io/en/stable/strategy-callbacks/#custom-stoploss-using-an-indicator-from-dataframe-example).
combining this with the [dataframe access](https://www.freqtrade.io/en/stable/strategy-advanced/#dataframe-access)  will get you a long way.

Overall, i think it's more a matter of "what do i want to do" (min low within 5 candles) - and "how can that be represented in dataframes" (`dataframe['low'].rolling(5).min()`) - based on which you then have to combine the available information on how to properly approach this.
