### ISSUE TITLE
What could make a 15m strategy open a position at irregular times such as 15:10 or at 15:18?

### ISSUE THREAD

**Issue by sebastianmacias** [freqtrade/freqtrade#9481]
## Describe your environment

  * Operating system: Ubuntu 22.04.3
  * Freqtrade Version: freqtrade docker-2023.11-dev-79f765a9
  
## Your question
I have a 15m strategy with `process_only_new_candles = True `and the following configuration:

```json

{
    "max_open_trades": 80,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "timeframe": "15m",
    "dry_run": false,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "order_types": {
        "entry": "market",
        "exit": "market",
        "emergency_exit": "market",
        "force_entry": "market",
        "force_exit": "market",
        "stoploss": "market",
        "stoploss_on_exchange": false,
        "stoploss_on_exchange_interval": 60
    },
    "entry_pricing": {
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing": {
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "****",
        "secret": "****",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
            "1INCH/USDT:USDT",
            "AAVE/USDT:USDT",
            "ACH/USDT:USDT",
            "ADA/USDT:USDT",
            "AGIX/USDT:USDT",
            "....",


            "200 additional pairs"



        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList"
        }
    ],
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}

```

The strategy is currently running on an Ubuntu Server, which is equipped with 4 vCPUs and 8GB of RAM; this setup is solely dedicated to running the strategy with one instance on Bybit and another on Binance. The CPU usage remains low, and more than 80% of the RAM is consistently free. Moreover, I have not encountered any error logs.

However, I've noticed that the strategy is initiating positions at irregular times, such as 15:10, 15:18, and 15:48. Ideally, I would expect it to enter the market at more consistent intervals, closer to 15:00, 15:15, 15:30, and 15:45.

This issue does not happen during backtesting when using the --timeframe-detail set to 1 minute.

Could anyone shed some light on what adjustments I need to make?

**Comment by xmatthias** [comment]
well first off - your logic (80 open trades) with a 1000$ wallet runs into 12.5$ positions - which are too tiny for most binance markets.
Now since it's live, the wallet could also be bigger i guess, so this may or may not be a problem.

ad hock, it's often "position / capital became available" - where you'll have a sell half a minute earlier.
With 80 positions, that's unlikely, unless you run into "too small position size" problems.

Aside from that, it can also  mean that one iteration takes X minutes to process all pairs (which can mean a too big pairlist, too many (heavy) indicators, ...) (logs would stop between :00 and :08, for example).


in theory - you can use `ignore_buying_expired_candle_after` to prevent late entries - though that'll only apply to initial entries - and will not really tell you any reason - and is essentially the answer to "position/capital became available" - but not necessarily for other potential problems.

you may also want to differentiate between initial entries and "adjustment orders" - where the logic is completely within the strategy, which will be called once every iteration.


Without logs - all we can do is guess (see above).
logs would probably tell some story ...

**Comment by sebastianmacias** [comment]
I added logs to populate_entry_trend:

```python
    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Log the current time and the time of the last candle
        logger.info(f"Checking entry trend at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} for pair {metadata['pair']}")
        logger.info(f"Last candle closed at {dataframe.iloc[-1]['date'].strftime('%Y-%m-%d %H:%M:%S')}")



```

```
f1_bybit_15m_252_both    | 2023-11-28 17:01:17,095 - F1 - INFO - Checking entry trend at 2023-11-28 17:01:17 for pair 1INCH/USDT:USDT
f1_bybit_15m_252_both    | 2023-11-28 17:01:17,096 - F1 - INFO - Last candle closed at 2023-11-28 16:45:00
f1_bybit_15m_252_both    | 2023-11-28 17:01:18,003 - F1 - INFO - Checking entry trend at 2023-11-28 17:01:18 for pair AAVE/USDT:USDT
f1_bybit_15m_252_both    | 2023-11-28 17:01:18,004 - F1 - INFO - Last candle closed at 2023-11-28 16:45:00
f1_bybit_15m_252_both    | 2023-11-28 17:01:18,919 - F1 - INFO - Checking entry trend at 2023-11-28 17:01:18 for pair ACH/USDT:USDT
f1_bybit_15m_252_both    | 2023-11-28 17:01:18,920 - F1 - INFO - Last candle closed at 2023-11-28 16:45:00
f1_bybit_15m_252_both    | 2023-11-28 17:01:19,773 - F1 - INFO - Checking entry trend at 2023-11-28 17:01:19 for pair ADA/USDT:USDT
f1_bybit_15m_252_both    | 2023-11-28 17:01:19,774 - F1 - INFO - Last candle closed at 2023-11-28 16:45:00
f1_bybit_15m_252_both    | 2023-11-28 17:01:20,699 - F1 - INFO - Checking entry trend at 2023-11-28 17:01:20 for pair AGIX/USDT:USDT
f1_bybit_15m_252_both    | 2023-11-28 17:01:20,700 - F1 - INFO - Last candle closed at 2023-11-28 16:45:00

...
f1_bybit_15m_252_both    | 2023-11-28 17:04:32,197 - F1 - INFO - Checking entry trend at 2023-11-28 17:04:32 for pair ZEN/USDT:USDT
f1_bybit_15m_252_both    | 2023-11-28 17:04:32,198 - F1 - INFO - Last candle closed at 2023-11-28 16:45:00
f1_binance_15m_252_both  | 2023-11-28 17:04:32,730 - F1 - INFO - Checking entry trend at 2023-11-28 17:04:32 for pair ZIL/USDT:USDT
f1_binance_15m_252_both  | 2023-11-28 17:04:32,730 - F1 - INFO - Last candle closed at 2023-11-28 16:45:00
f1_bybit_15m_252_both    | 2023-11-28 17:04:33,007 - F1 - INFO - Checking entry trend at 2023-11-28 17:04:33 for pair ZIL/USDT:USDT
f1_bybit_15m_252_both    | 2023-11-28 17:04:33,008 - F1 - INFO - Last candle closed at 2023-11-28 16:45:00
f1_binance_15m_252_both  | 2023-11-28 17:04:33,533 - F1 - INFO - Checking entry trend at 2023-11-28 17:04:33 for pair ZRX/USDT:USDT
f1_binance_15m_252_both  | 2023-11-28 17:04:33,534 - F1 - INFO - Last candle closed at 2023-11-28 16:45:00
f1_bybit_15m_252_both    | 2023-11-28 17:04:33,823 - F1 - INFO - Checking entry trend at 2023-11-28 17:04:33 for pair ZRX/USDT:USDT
f1_bybit_15m_252_both    | 2023-11-28 17:04:33,824 - F1 - INFO - Last candle closed at 2023-11-28 16:45:00
f1_binance_15m_252_both  | 2023-11-28 17:04:35,374 - freqtrade.wallets - INFO - Wallets synced.
```

It looks like populate_entry_trend is called at the right time or close to the right time. However positions seem to be opened later on.

**Comment by xmatthias** [comment]
well your "trend" takes about 4m 30s to process the whole pairlist.

With that - entries at around 00:04:00 / 00:05:00 - as well as 00:18:00 / 00:19:00 are expected (as well as 2 other periods i'm too lazy to type now) - as that's about ~4-5m after the new candle arrives (at :00, :15, :30, :45).

it looks like mostly a topic of "too many pairs" - which can be seen by 
* initial download took 1m10s
* overall pairlist checking took an additional ~4m

I'll assume your pairlist is *available pairs* long  - or close to that ... ? 


---

at any rate - it explains and aligns to the dates you're seeing - if you do the math for not just :00, but also for the other "candle arrival" times.

**Comment by sebastianmacias** [comment]
I was running the strategy on both exchanges with over 200 pairs each. I then reduced the number of pairs to 20 on one, and now positions are opening at the correct times on that exchange.

Thank you for the clarification.

**Comment by xmatthias** [comment]
Well "correct" is relative, anyway.
neither time is incorrect - it might not have been expected - but that doesn't mean it's incorrect :laughing:
