### ISSUE TITLE
How to get get the last candle wich met a given condition

### ISSUE THREAD

**Issue by d-achcar** [freqtrade/freqtrade#9484]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8
  * CCXT version: 4.1.22
  * Freqtrade Version: freqtrade 2023.10
  
## Your question
First i would like to thank all the team for the excellent work you have been doing with freqtrade.
I'm writing a strategy that needs to locate the last row in the dataframe that met a given condition.
This is something like valueWhen function of pine script.

Example:
                                     date        open         high        low             close     volume   xtl_trend
0 2021-11-09 23:25:00+00:00  67279.67  67321.84  67255.01  67300.97   44.62253    1
1 2021-11-09 23:30:00+00:00  67300.97  67301.34  67183.03  67187.01   61.38076    1
2 2021-11-09 23:35:00+00:00  67187.02  67187.02  67031.93  67123.81  113.42728    0
3 2021-11-09 23:40:00+00:00  67123.80  67222.40  67080.33  67160.48   78.96008    0
4 2021-11-09 23:45:00+00:00  67160.48  67160.48  66901.26  66943.37  111.39292    1

So suppose that current candle is #3 it should get row #1 which is the last candle which had xtl_trend=1
I found in other strategy advices something similar but always with a fixed number of positions to look backwards(ie last 3 so it can be handled with rolling and counting crosses).
In this case is like a dynamic rolling based on a condition (xtl_trend=1) wich i'm struggled about how to deal with it in pandas.
Also i would like to solve it in a way that works fine in backtesting with no lookahead bias.

Any help? Thanks

**Comment by xmatthias** [comment]
Try something like the following (it's a complete sample ... you obviously need to modify this to use the freqtrade dataframe):

``` python
import pandas as pd
import numpy as np
data = {
    'date': [
        '2021-11-09 23:25:00+00:00',
        '2021-11-09 23:30:00+00:00',
        '2021-11-09 23:35:00+00:00',
        '2021-11-09 23:40:00+00:00',
        '2021-11-09 23:45:00+00:00'
    ],
    'open': [67279.67, 67300.97, 67187.02, 67123.80, 67160.48],
    'high': [67321.84, 67301.34, 67187.02, 67222.40, 67160.48],
    'low': [67255.01, 67183.03, 67031.93, 67080.33, 66901.26],
    'close': [67300.97, 67187.01, 67123.81, 67160.48, 66943.37],
    'volume': [44.62253, 61.38076, 113.42728, 78.96008, 111.39292],
    'xtl_trend': [1, 1, 0, 0, 1]
}

df = pd.DataFrame(data)
df['date'] = pd.to_datetime(df['date'])  # Convert 'date' column to datetime format


# Assign index to helper column
df['isTrue'] = df.index
# Reset column to be empty for rows where the condition does NOT match (note the ~).
df.loc[~(df['xtl_trend'] == 1),'isTrue' ] = np.NaN
# ffill that column
df['isTrue'] = df['isTrue'].ffill()
df

```


![image](https://github.com/freqtrade/freqtrade/assets/5024695/a081edd9-5b7e-44f7-80b8-8d11db5ba028)


There might be details you'll want to look at (is idx=4 in row4 correct??)
but in theory, it should allow you to "get" that individual row by the index in "isTrue".

How / what you do with that is beyond me (at least for now) - as you'll probably struggle to (efficiently) reference a row by index ...

**Comment by d-achcar** [comment]
Thanks a lot xmatthias for taking the time to write this down.
The idea once i locate the candle/row which met the condition is to use some of its values to compare with current row/candle.
Will work based on your suggestion. Thanks!
