### ISSUE TITLE
Backtesting multiple strategies - incorrect manual ?

### ISSUE THREAD

**Issue by 2morowMan** [freqtrade/freqtrade#9489]
Hello, is the manual wrong, or am i being really daft this morning ???
i was Backtesting multiple strategies (https://www.freqtrade.io/en/stable/backtesting/#backtesting-multiple-strategies)

and manual says "This will save the results to user_data/backtest_results/backtest-result-<strategy>.json" 
but i only get the usual two files in /backtest_results, "backtest-result-2023-11-30_16-24-18.json  and a .meta.json file.
i dont get a file with strategy name, and theres NO "There will be an additional table comparing win/losses of the different strategies".
Clearly something is wrong - either im doing it wrong, or the manual is wrong.

>docker-compose run --rm freqtrade1 backtesting --timeframe 5m --strategy-list Strategy003 Strategy005  --export trades

(ive asked around on forums but problem continues)

Win10,
Python 3.12,
grep not recognised
freqtrade 2023.10

**Comment by froggleston** [comment]
I can recreate this here, so yes I think the docs are incorrect. I'll take a look around.

**Comment by froggleston** [comment]
The code for storing backtest results doesn't seem to output per strategy in strategy-list, as far as I can see: https://github.com/freqtrade/freqtrade/blob/0235db48a8ac512e936804b4109e97669f87f2d2/freqtrade/optimize/backtesting.py#L1398

**Comment by xmatthias** [comment]
>  "This will save the results to user_data/backtest_results/backtest-result-.json"

I don't see this as incorrect, really. While we do add a date to the file in reality - nothing in the docs says it'll save it "per strategy" - so that's not what's happening, and i'd consider this as correct.
The 2 strategy results will be within the the one file (it'll not be one file per backtest run, unless you didn't change anything, where results may be cached).

**Comment by froggleston** [comment]
`This will save the results to user_data/backtest_results/backtest-result-<strategy>.json, injecting the strategy-name into the target filename` - this is incorrect though. I can't see anywhere in the code where the *strategy name* is injected into the *filename*.

**Comment by xmatthias** [comment]
Great catch :+1: 
i relied on the quoted text, didn't look at the actual docs :laughing:

**Comment by BigJonMMXX** [comment]
Can anyone tell me why this is closed? 
the manual has not changed, nor the behaviour of the code... one or other is still incorrect.
:( confused.
