### ISSUE TITLE
Monthly merging faulthy

### ISSUE THREAD

**Issue by atomcracker** [freqtrade/freqtrade#9490]
## Describe your environment

  * Operating system: Windows 11 Pro 23H2
  * Python Version: Python 3.11.5
  * CCXT version: ccxt==4.0.88
  * Freqtrade Version: freqtrade 2023.11

## Describe the problem:

Using informative timeframe does not seem to work correctly on monthly timeframe. Merging happens on the 30th, not on the 31th.

I am using ByBit BTC futures as an example.

### Steps to reproduce:

```
@informative('1M')
    def populate_indicators_1h(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        return dataframe
```
  
### Observed Results:

  * What happened?
```
date                      | open    | high    | low     | close   | volume | date_1M
2022-12-30 23:50:00+00:00 | 16621.5 | 16621.5 | 16618.0 | 16618.0 | 61.770 | 2022-11-01 00:00:00+00:00
2022-12-30 23:55:00+00:00 | 16618.0 | 16621.0 | 16615.5 | 16620.5 | 96.412 | 2022-12-01 00:00:00+00:00
```
The main timeframe used is 5min.
  * What did you expect to happen?
I'd expect the november candle on the monthly to be closed on the end of the 31th of december, not the 30th.

### Relevant code exceptions or logs

None

**Comment by xmatthias** [comment]
well first off - your timerame difference is too big.

you'll not be getting 1 month of 5m data in live - so for the later part of the month, the Monthly candles will be empty.
the merge happens on the date and is then forwardfilled - but if you don't have the 1st of the month in your candles, then no data can be forwardfilled (that's not the point of this issue though, just pointing out that this combination won't work in reality.).

---

Aside from that, i can somewhat recreate the problem.

It's problematic as  month lengths are not deterministic (a month can have anything between 28 and 31 days) - which also means pandas only supports it to some extend, and actually with slightly different methods, which makes this a special case that needs separate handling.

**Comment by atomcracker** [comment]
> you'll not be getting 1 month of 5m data in live

Yes that would result in custom data handling, which would be unnecessarily complicated as I don't fully use the 5m data. Let me explain: Say the current price is 99, I would want to buy as soon as the current price is higher than 100 (the hourly high).  I use the 5m close price to determine if above 100 and set an order. As far as I understand I can't use a limit order for 100 when the price is 99, it will just get filled immediately. I would also greatly prefer to be able to open more orders in the same hourly candle if a stop is hit. Do you maybe have any idea how to do this without using the 5m data as a 'check'?

**Comment by xmatthias** [comment]
that's correct, placing a buy order above current price converts that into a marketable limit order, which will fill immediately. That's basic market / exchange logic, nothing we can do about that.

the price (and when the order is placed) is however not related to the timeframe used ... so i'm not entirely sure i understand your question.

**Comment by atomcracker** [comment]
Yes, that's why I'm using a 'low' timeframe to check if the current price is above desired price. Was just wondering if you'd maybe know a more elegant solution. 

Correct, it is somewhat of a different question. The only relation is the reason why I am using a huge timeframe difference, which as you pointed out would result in other problems.

For backtesting I use the full available time range, the case in December 2022 was just an example to showcase the behaviour. Interesting that pandas itself does not fully support the month lengths.
