### ISSUE TITLE
How can I launch the old version through docker?

### ISSUE THREAD

**Issue by rr8733380** [freqtrade/freqtrade#9492]
How do I launch the old version of freqtrade through docker? 

I'm downloading a `zip` file from here: `https://github.com/freqtrade/freqtrade/releases/tag/2021.1`
I'm doing `docker-compose pull`, but I have the latest version installed
Do I need to change the `image: freqtradeorg/freqtrade:stable` in `docker-compose.yml`?

**Comment by stash86** [comment]
https://botacademy.ddns.net/2023/12/03/how-to-use-older-version-of-freqtrade/

**Comment by xmatthias** [comment]
quite honestly - you shouldn't.

there's a reason we do updates - old versions (especially ones that are 2 years old) WILL have problems, for example because exchange API's change all the time.
