### ISSUE TITLE
Kraken exchange: Time in force policies are not supported for Kraken yet.

### ISSUE THREAD

**Issue by san4io** [freqtrade/freqtrade#9497]
## Describe your environment

  * Operating system: Docker:stable
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Trying to run NASOS_v4 & Elliot_v8 on Kraken. And cannot launch bot. While on kucoin everything works perfectly.

Output: freqtrade.exceptions.OperationalException: Time in force policies are not supported for Kraken yet.

### Steps to reproduce:

  1. https://strat.ninja/overview.php?strategy=ElliotV8_3)
  2. Launch
  3. Check log
  
### Observed Results:

  * What happened? freqtrade.exceptions.OperationalException: Time in force policies are not supported for Kraken yet.

  * What did you expect to happen? Bot should work

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2023-12-03 23:11:00,561 - freqtrade.commands.trade_commands - ERROR - Time in force policies are not supported for Kraken yet.
2023-12-03 23:11:00,561 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
             ^^^^^^^^^^^^
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/freqtradebot.py", line 76, in __init__
    self.exchange = ExchangeResolver.load_exchange(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 37, in load_exchange
    exchange = ExchangeResolver._load_exchange(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 64, in _load_exchange
    exchange = ex_class(**kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/exchange/exchange.py", line 187, in __init__
    self.validate_config(config)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 229, in validate_config
    self.validate_order_time_in_force(config.get('order_time_in_force', {}))
  File "/freqtrade/freqtrade/exchange/exchange.py", line 641, in validate_order_time_in_force
    raise OperationalException(
freqtrade.exceptions.OperationalException: Time in force policies are not supported for Kraken yet.

  ```

**Comment by xmatthias** [comment]
You can easily get around this by reconfiguring your `order_time_in_force` configuration to either not exist, or to use "GTC" (The default).

Different Time in Force policies are something we need to explicitly configure per exchange (usually by refering to the exchange API docs, as we don't get the  information about which ones are available for each exchanges from ccxt) - therefore by default, only GTC is supported.
That also needs to be tested for each supported type individually.

I'm marking this as enhancement, as well as "good first issue" (which means we will leave it around for some time to give new contributors the chance to look at this) - as this is really a matter of adding 1 line to the kraken.py class (`order_time_in_force`, with supported Time In force) - and testing each of the different order-types on exchange.

**Comment by stash86** [comment]
Or you can just remove the hardcoded part in the strategy file

**Comment by san4io** [comment]
But kraken API supports:
![image](https://github.com/freqtrade/freqtrade/assets/12079341/4e6de111-42e0-4d51-9e6e-da9bc64836b8)
 
Or it is ccxt limitation?

**Comment by xmatthias** [comment]
please read this comment above:
it'll answer your point exactly.

happy for you to do the tests with kraken for the different settings - and submit a PR adding support for different timeInFoce methods kraken :)

**Comment by SarthakNikhal** [comment]
Is this issue resolved?

**Comment by xmatthias** [comment]
@SarthakNikhal nope, still up for grabs

as said above, it's not a technically difficult topic, but a timeconsuming one, as it needs testing of all the different scenarios on an active kraken account.
