### ISSUE TITLE
Seeking Guidance on Implementing Live and Backtest Forex Trading in Freqtrad

### ISSUE THREAD

**Issue by AmiraliOmidvar** [freqtrade/freqtrade#9503]
* Operating system: ubuntu 20.04
  * Python Version: 3.10
  * CCXT version: 4.1.66
  * Freqtrade Version:  freqtrade 2023.11-dev-79f765a93
  
I'm looking to add live and backtest forex trading to Freqtrade. I Read the docs, but I'm looking for practical advice and shortcuts if any. How much effort am I looking at here?

Any guidance, code snippets, or resources to make this smoother would be awesome.

Thanks a bunch.

**Comment by xmatthias** [comment]
Freqtrade relies exclusively on ccxt to connect to exchanges.
This is not just the connectivity part, but also the "message format" - which is using the ccxt unification throughout.

your first step will therefore be to look at implementing the exchange of your choosing to ccxt - which should auto-enable it for freqtrade (based on the assumption that necessary endpoints are available and implemented).
You can obviously also attempt to implement an exchange directly in freqtrade (that's however something we'll not be accepting as PR, as we do not have the capacity to maintain a direct exchange connection) - but again, you'll need to replicate the ccxt like responses and have these align with ccxt - and personally, i think using ccxt will be the simpler method (you might also find open PR's (or even support) for the exchange you're looking for in the ccxt repository.

As I've personally never implemented a ccxt exchange from scratch, i have no idea how much effort this part will be.

Beyond that - you might also need to do changes to freqtrade itself (like, adding support for markets that are not open 24/7) - but that's only really relevant once you have the actual exchange implementation ready and working.

---

Once the exchange implementation is ready (-> ccxt supports that exchange, or you have a fork that supports it):

We can assist to _some degree_  - best on discord's #core-dev  - but we'll not be hand-holding beyond a certain point - so understanding of the languages involved (ccxt writes exchanges in typescript and transpiles them to python), freqtrade is in python - as well as good debugging capabilities is a must.


Obviously - feel free to give it a go - let us know how it works.
It's however clearly not something simple or suited for beginners, so I'd recommend to start with other contributions to freqtrade to get to know the actual structure and inner workings before taking on a most likely long / big project.
