### ISSUE TITLE
Freqtrade update - error Building wheel for py_find_1st (pyproject.toml) did not run successfully.   │ exit code: 1

### ISSUE THREAD

**Issue by AJalgo** [freqtrade/freqtrade#9510]
## Describe your environment

  * Operating system: ____
  * Python Version: Python 3.10.12 (`python -V`)
  * CCXT version: 4.0.71 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.12-dev-af05e3d74 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
Hi, I am a novice at Github and looked through the issue list but found that this issue was last closed in 2020. I am running freqtrade on Ubuntu 22.04.3 which is in a virtualbox on a windows laptop.
Today I decided to run the update command ./setup.sh --update to update the entire freqtrade system since it had been a while since I installed it. I followed the instructions on the freqtrade page - entered the freqtrade directory and did not activate virtual environment.

But i ran into the following error:
`Building wheels for collected packages: py_find_1st
  Building wheel for py_find_1st (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for py_find_1st (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      /tmp/pip-build-env-btdwi39c/overlay/lib/python3.10/site-packages/setuptools/dist.py:314: InformationOnly: Normalizing '1.1.6
      ' to '1.1.6'
        self.metadata.version = self._normalize_version(self.metadata.version)
      /tmp/pip-build-env-btdwi39c/overlay/lib/python3.10/site-packages/setuptools/dist.py:472: SetuptoolsDeprecationWarning: Invalid dash-separated options
      opt = self.warn_dash_deprecation(opt, section)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/utils_find_1st
      copying utils_find_1st/__init__.py -> build/lib.linux-x86_64-cpython-310/utils_find_1st
      running build_ext
      check for clang compiler ... no
      building 'find_1st' extension
      creating build/temp.linux-x86_64-cpython-310
      creating build/temp.linux-x86_64-cpython-310/utils_find_1st
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_13_API_VERSION -I/tmp/pip-build-env-btdwi39c/overlay/lib/python3.10/site-packages/numpy/core/include -I/home/abhishek/freqtrade/.venv/include -I/usr/include/python3.10 -c utils_find_1st/find_1st.cpp -o build/temp.linux-x86_64-cpython-310/utils_find_1st/find_1st.o
      x86_64-linux-gnu-gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for py_find_1st
Failed to build py_find_1st
ERROR: Could not build wheels for py_find_1st, which is required to install pyproject.toml-based projects
Failed installing dependencies
`

Could someone please help me out with what went wrong? Or can freqtrade still run normally if py_find-1st dependency is not updated?

Thanks in advance

**Comment by xmatthias** [comment]
You will probably want to update / reinstall build-essentials.

taken from [here](https://stackoverflow.com/questions/11912878/gcc-error-gcc-error-trying-to-exec-cc1-execvp-no-such-file-or-directory):

```
sudo apt-get update
sudo apt-get install --reinstall build-essential
```

and then re-run the command above.

**Comment by AJalgo** [comment]
Tried the above suggestion. Still getting the same error. Any other option or full reinstall?
Will freqtrade still work if this dependency is not installed?

**Comment by xmatthias** [comment]
i doubt it will.
it's only used in edge - but edge is hard-wired into the core bot file.

It seems to be a compiler missmatch - though one i never encountered before, so i'm stuck to google.

maybe `apt install g++` might work - or  the following shows different versions 
```
g++ --version
gcc --version
```

**Comment by AJalgo** [comment]
Still running into the same issue. Guess I'll do a full reinstall after backing up all my strategies and historical data.
Thanks for your help Mathias

**Comment by EgyptianM** [comment]
I'm having same error on Windows in a fresh install
