### ISSUE TITLE
Multiple instances using Docker - dry run vs backtesting/hyperopt

### ISSUE THREAD

**Issue by 2morowMan** [freqtrade/freqtrade#9513]
## Describe your environment

  * Operating system: ____Windows 10
  * Python Version: _____ Python 3.12.0
  * CCXT version: _____ CCXT 4.1.66
  * Freqtrade Version: ____ Freqtrade 2023.11

## Your question

The documentation  [Multiple instances using docker](https://www.freqtrade.io/en/latest/advanced-setup/#running-multiple-instances-of-freqtrade:~:text=SQL%20Cheatsheet.-,Multiple%20instances%20using%20docker,-%C2%B6) is very clear and useful.
I have 3 bots - with their own names, strategies, DBs, logs, config files, etc.
PS>docker-compose up, and FreqUI (localhost), all work great - i can see all bots working in real time. ( really cool )

But i am unsure about Download-Data, Backtesting and Hyperopt...
>docker-compose run --rm freqtrade5 backtesting --strategy Strategy005
>docker-compose run --rm freqtrade1 backtesting --timeframe 5m --strategy-list Strategy003 Strategy005 --export trades

Q. Does it matter which instance "freqtrade1" i refer to? for the multi-backtest do i refer to the first instance in my docker-compose.yml?  (Likewise with Download-Data, i have to specify one service, so first one?)

Q. if i remove "max_open_trades: 4" from config, and place it in config1 and config2... i get 
2023-12-06 10:26:06,422 - freqtrade.configuration.configuration - INFO - Using max_open_trades: None ...
and then it all fails.
i've read everything everywhere, but it seems config1, 2, etc are not read with backtesting (same problem with hyperopt)

please advise

(edit: corrected template)

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

if you're not passing an explicit `--config <config>` - then the default config will be used (in a docker context, `user_data/config.json`).

`docker compose run --rm ...` commands explicitly ignore their "command" configuration - and only run what you're actually passing in via command line.

The service you're using does not "really" matter, assuming the configurations (user_dir etc.) are identical.
It also assumes that  actually trading bots are started with `docker compose up <service> <-d>` .
These will expose ports, and run with their configured command.

It **can** matter if you start separating user_data directories - mounting `user_data1` to the first service, and `user_data2` to the 2nd service. 
then the used service will define the directory the data is downloaded to - and for backtesting, will determine where the bot looks for data.

**Comment by 2morowMan** [comment]
Thanks for the reply (apologies for template mistakes)
For downloading data i see it doesnt matter which service i use - the data is the data. Good to know.

But i dont get this...
i have max_open_trades: 2 in config (the main config) and max_open_trades: 3 in config1 and max_open_trades: 4 in config2
all good for dry run
but for backtesting (single, or multi) im stuck with 2 (or max_open_trades: None and errors if i remove it)
docker-compose run freqtrade1 backtesting --timeframe 5m --strategy-list Strategy003 Strategy005 --export none

sorry if im being dense, but im just not seeing how its done.

**Comment by xmatthias** [comment]
you seem to be using a single user_data directory.
as you're not passing in a `--config user_data/config1.json` when running backtesting - it'll not be used.

As mentioned above - a `run` will NOT use the command configured in the docker-compose file.

**Comment by 2morowMan** [comment]
i thought you meant just the switch --rm, as "docker-compose freqtrade" doesnt work without 'run', but i will read (again, and again) about that.
And next i will edit docker-compose.yml to have different "user_data" folders....
Thanks.

**Comment by stash86** [comment]
There is no need to have different user_data folder. All you need is different config.json files. Don't over-complicate things that shouldn't be complicated.

**Comment by xmatthias** [comment]
> And next i will edit docker-compose.yml to have different "user_data" folders....

it's one possibillity (not one i'd personally use, multiple configs, with different db files and different log-files are more than sufficient).
Compose with multiple services can have many faccettes, we don't know what you configured, so all we do is guesswork based off of what our docs say.

**Comment by 2morowMan** [comment]
if you read the problem, i already have different config files, and they
are not read !!!!!!!!!!!!!!!!!!!!

**Comment by xmatthias** [comment]
please **read** what we're trying to tell you, instead of "screaming" (multiple exclamation marks i interpret as screaming).

when using (for example) `docker compose run --rm freqtrade1 download-data --exchange binance` - freqtrade will ONLY load the configuration files `user_data/config.json` and `config.json` (the default files).

If you have different files, **you, the user**  are responsible to let the bot know that you'd like to use a non-default config file, by specifying this with `--config user_data/config1.json`.

when using `docker compose run` - your `comand: ` section in the compose file is **not** relevant and will be ignored (that's only used for `docker compose up`).

as such, your command becomes `docker compose run --rm freqtrade1 download-data --exchange binance --config user_data/config1.json`, and `docker compose run --rm freqtrade2 download-data --exchange binance --config user_data/config2.json`.

Again, this assumes a default docker-compose file (as we provide it) which has been extended to multiple services, but has not otherwise been greatly altered.

please note:
from a content perspective, this is _exactly_ what i also mentioned in my very first response (https://github.com/freqtrade/freqtrade/issues/9513#issuecomment-1843343463) - just worded slightly differently this time.

**Comment by 2morowMan** [comment]
thanks for the reply, but i guess im not explaining myself clearly...

i followed this [Multiple instances using docker](https://www.freqtrade.io/en/latest/advanced-setup/#running-multiple-instances-of-freqtrade:~:text=SQL%20Cheatsheet.-,Multiple%20instances%20using%20docker,-%C2%B6)

My sub-configs# work great for dry-run, not for backtesting...
docker-compose run --rm freqtrade1 backtesting --timeframe 5m --strategy-list Strategy003 Strategy005 --export none

i am only trying to put different "max_open_trades": #, into each config...

So ive been trying all sorts... having different user_data_# folders, having only one config file per service (with different values), even putting max_ into the strategy, and nothing works. im beginning to think its not possible.

Maybe its worth adding a comment to the manual  [Multiple instances using docker](https://www.freqtrade.io/en/latest/advanced-setup/#running-multiple-instances-of-freqtrade:~:text=SQL%20Cheatsheet.-,Multiple%20instances%20using%20docker,-%C2%B6) stating that this method does not work with backtesting strategy list...

**Comment by xmatthias** [comment]
one last time:

`docker-compose run --rm freqtrade1 backtesting --timeframe 5m --strategy-list Strategy003 Strategy005 --export none`
needs to become `docker-compose run --rm freqtrade1 backtesting --timeframe 5m --strategy-list Strategy003 Strategy005 --export none --config userdata/config2.json` (notice the additional `--config` flag).

I've stated this now for 3 consecutive times above.

Following an advanced section of the documentation DOES assume that the basics have been understood, otherwise you'll need to review the relevant documentation sections for these parts.

**Comment by 2morowMan** [comment]
Thank for your reply, and for closing this issue, and for repeating yourself "3 consecutive times".
However you have not provided any solution, and the problem persists.

Please dont reply with more grumpyness, im only following the manual, and if backtesting (and hyperopt) is not compatible with having "multiple instances with docker", a simple sentence in the manual would suffice.

i suggest...
Backtesting with  `--strategy-list` will *only* work with one config file.

**Comment by stash86** [comment]
Bad suggestion. Why limit the user to only be able to use one config file? Whatif I wanted to test the strategies on different stake, different pairs, different exchanges?

There is no connection between backtest/hyperopt and multiple instances of docker. You are the one trying to connect the two unrelated things. So no sentence in the manual needed

**Comment by 2morowMan** [comment]
"Why limit the user to only be able to use one config file?" - im not, thats how it works. i am, indeed, a user that wants to use more than one config file. In fact it is even suggested early on in the manual to separate config settings into multiple files. What i have discovered is that backtesting, (and other later topics) FAIL with multiple files...

**Comment by stash86** [comment]
no it's not. Read what matthias wrote above. Sigh... I'm done. Won't comment anymore on this topic since answer has been given but you are refusing to learn to read our answers and understand it. You just kept repeating your false narratives. Good luck in your crypto journey.

**Comment by xmatthias** [comment]
> i am, indeed, a user that wants to use more than one config file.

both backtesting and trade commands (dry-run, live, ... as well as actually most other subcommands) do support _split configurations_, as explained [in the documentation](https://www.freqtrade.io/en/stable/configuration/#multiple-configuration-files).
you can either use multiple `--config` arguments, or use the `add_config_files` attribute.

As (also) explained in the documentation - the sequence of definition in both instances DOES matter - as the configuration files are merged, resulting in one final configuration.
this behavior is identical between running a bot in trade mode, and running backtesting (the same configs will be used, ...).

> Please dont reply with more grumpyness,

There's no grumpyness, just resignation after having explained the same thing multiple times - yet the next command you post does the same thing - not including a --config flag (which shows that you either didn't read, or didn't understand the prior answer).

**Comment by 2morowMan** [comment]
This thread is a good example of why people leave the project. You have not answered the question. And shown irritation and offensiveness at my attempts to clarify. 

"one more time" "explaining multiple times" "but you are refusing to learn to read our answers and understand it" - that is very offensive, especially as the replies do not address the problem.

If you dont know, why reply ?
if you dont understand the question, why reply?
Answering a different question, and getting upset about it, doesnt help anyone.
How do you see the future of this project with the being rude and belittling new comers ?

ive asked around and its agreed the grumpy answers do indeed ignore the clarified question. And "multiple exclamation marks i interpret as screaming" is a unique and unusual interpretation. 

For now i will forgive you both and move on.

**Comment by stash86** [comment]
LOL!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Honestly, I don't care if people leave. This is a free project. We gain nothing from this. People can use this if they want, or stop using it for whatever reasons. We will still work and use it ourselves.

Second, I don't ask for your forgiveness. You can take it back.

We are not belittling new comers. We are frustated with your communication skill. If only you explained as simple as how you explained in the discord, the issue will be solved faster.

And FYI, people leave the project not because we hurting their feeling. But because they lost money on the market.

**Comment by xmatthias** [comment]
To clarify this issue for future readers, as the actual solution is now intransparent:

The explanation / improved question on discord (as mentioned above)

> Anyone know if its possible to do simultaneous multiple backtesting and **have each strategy obey its own config file**?

_Highlight added for clarity_

changed the answer to this issue to "no, this is not possible directly".

only one configuration can be active during a bot run - if multiple configurations are given, then the [configurations are merged](https://www.freqtrade.io/en/stable/configuration/#multiple-configuration-files), as explained in the docs.


Different settings **per Strategy** are however possible for a _limited set_ of configurations by removing the key from the configuration, and instead configuring this value within the strategy.
this is limited to the settings listed in the [Parameters in the strategy](https://www.freqtrade.io/en/stable/configuration/#parameters-in-the-strategy) section of the documentation, and may come with slight syntax changes, as the definition in the strategy must be valid python (`true` -> `True`, ...).
