### ISSUE TITLE
frequi: add Timerange and Timeframe to "load results" tab

### ISSUE THREAD

**Issue by luck0r** [freqtrade/freqtrade#9517]
* Freqtrade Version: 2023.11

## Describe the enhancement

It would be great to have a timerange and timeframe in the load results tab. 
![Bildschirmfoto vom 2023-12-08 10-53-11](https://github.com/freqtrade/freqtrade/assets/67522404/6db938a1-8b8e-4275-bb8b-5687af93d164)
If you run multiple backtests on the same strategy, on different timeranges and different timeframes, it can take time to find the correct backtest. The timeframe you find after clicking on a result(takes time loading) but the timerange is more effort, you need to go on analyse result.

It would be great if both are visible directly from the overview.

**Comment by xmatthias** [comment]
i do understand that that might be neat - but this view is already pretty slow to load (i've got about  300 results in my folder, and it takes several seconds to load) - and it's current speed relies SOLELY on reading the data from the `.meta` files.

to get additional data (beyond backtest time), filename and strategy name, we'd need to read the full result - which from a size perspective, is not really feasible for all files in the directory in reasonable time.

Adding stuff to the metadata file is also edge-casy - as that'll increase it's size - and size IS a problem when reading 100ds of files.
for now, i'll mark this as an enhancement with low priority - but it could take quite a bit to actually get to work on this.

**Comment by xmatthias** [comment]
Will be available with the next UI release.

![image](https://github.com/freqtrade/freqtrade/assets/5024695/c8879efe-9620-4121-b8ca-973eaf33536a)

**Comment by luck0r** [comment]
Very nice, thank you!
