### ISSUE TITLE
Weekly Informative Pair on Daily Candles joining on Sundays (a day before weekly open)

### ISSUE THREAD

**Issue by alisalama** [freqtrade/freqtrade#9518]
## Describe your environment

  * Operating system: MacOS
  * Python Version: 3.9.1
  * CCXT version: 4.1.76
  * Freqtrade Version: freqtrade docker-2023.12-dev-b1487340
  
## Describe the problem:

First, thank you for all your work on this fantastic program! 

The weekly Informative Pair is being joined to Daily Candles on a Sunday, a day before weekly open, so is peeking at the candle before weekly open. I think it should be joined on the Monday.

### Steps to reproduce:

1) Simply adding the below. I'm using ETH/USDT, Binance, 1D.
 ```
@informative('1w')
    def populate_indicators_1w(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
        # Hull Moving Average (used to tag bear market)
        dataframe['hma_slow'] = ta.SMA(dataframe, timeperiod=14);
        dataframe['hma_fast'] = ta.SMA(dataframe, timeperiod=7);
        
        dataframe['hma_bull_bear'] = (dataframe['hma_slow'] <= dataframe['hma_fast']);
        return dataframe
```
   

### Observed Results:

Seems to match on the Sunday. See below.

For example, on Row 280, the 1W candle opened on the 06/10/2023 00:00, so closed at 12/10/2023 23:59, but it is joined to the daily candle that opened at 12/10/2023 00:00, which is a Sunday.
 
![Pasted Graphic](https://github.com/freqtrade/freqtrade/assets/7068759/42af19a1-efde-42f9-90b0-4cab48b6b434)

**Comment by xmatthias** [comment]
you had me doubt this for a second (hence a commit adding a test will be attached to this issue).

However, behavior is correct as is (letme explain)

> For example, on Row 280, the 1W candle opened on the 06/10/2023 00:00, so closed at 12/10/2023 23:59, but it is joined to the daily candle that opened at 12/10/2023 00:00, which is a Sunday.

That's exactly what's happening - and it's correct once you keep in mind that we're talking about candle **open** dates.

You've got the 1w candle correct - it closed on 12/10/2023 23:59.
however, the 1d candle _also_ closes at 12/10/2023 23:59 - so the 2 close at exactly the same time, and are therfore merged together (they're available to the bot / user at the same time).


The logic is pretty simple if you think about it
it's "open date + period duration - short period duration" - and that's exactly the logic applied here.

**Comment by alisalama** [comment]
ah I see... Yeah, that makes sense. It's the perspective of when it becomes available to the bot that I was missing.

Thanks for your help!
