### ISSUE TITLE
No history data when run hyperopt

### ISSUE THREAD

**Issue by godshades** [freqtrade/freqtrade#9535]
## Describe your environment

  * Operating system: Ubuntu 20.0.4
  * Python Version: 3.11.5
  * CCXT version: 4.1.22
  * Freqtrade Version: 2023.10
  
## Your question

i already download data
`freqtrade download-data --timeframes 1d --exchange binance --timerange 20230101-`
=> file KAVA_USDT_USDT-1d-futures.feather downloaded then i convert to KAVA_USDT_USDT-1d-futures.h5

when run hyperopt
`freqtrade hyperopt --hyperopt-loss ProfitDrawDownHyperOptLoss  --strategy XXX -e 500 --spaces default --enable-protections -i 1d --dry-run-wallet 50 --timerange 20230101- --data-format-ohlcv hdf5 --datadir user_data/data/binance/futures/ --config user_data/config.json`

i have this error:

```
freqtrade.data.history.idatahandler - WARNING - KAVA/USDT:USDT, futures, 1d, data starts at 2023-01-01 00:00:00
freqtrade.data.history.idatahandler - WARNING - No history for KAVA/USDT:USDT, futures, 1d found. Use `freqtrade download-data` to download the data
freqtrade - ERROR - No data found. Terminating.
```

help me please

**Comment by stash86** [comment]
You need to download more historical data, because you need to account for startup candle count

**Comment by godshades** [comment]
@stash86 worked, thanks

**Comment by xmatthias** [comment]
as an aside, i'd recommend to switch to the new default dataformat, feather - which has shown in [performance comparisons](https://www.freqtrade.io/en/latest/data-download/#dataformat-comparison) to be slightly above hdf5... while taking only half the size.

it's obviously up to you to take this decision - just pointing this out as it might be missed.
