### ISSUE TITLE
Select trades based on pairs relative strength when pairs trigger same signal at same time

### ISSUE THREAD

**Issue by alisalama** [freqtrade/freqtrade#9542]
## Describe your environment

  * Operating system: MacOS
  * Python Version: 3.9
  * CCXT version: 4.1.76
  * Freqtrade Version: freqtrade docker-2023.12-dev-0f82ea87

## Your question

Hi, thanks for the fantastic work! I have a couple of related questions that I can't find any info on...

For example, I have say 10 coins in the pairlist, and 3 of them trigger an entry signal at the same time, but I only have max_open_trades = 1.  I'm using the 1d timeframe, 10 of the largest pairs, and due to correlations in the market this triggering at the same time seems to happen a lot.

a) how does Freqtrade choose which one of the 3 it will go for? First one it processes presumably?
b) is it possible to create a mechanism to prefer one over the other two? say I gave each of them a score 0-1, and it should pick the one with highest score. Is there a Custom Pairlist or something?

Thanks,
Ali

**Comment by alisalama** [comment]
for b) I guess I could use informative pairs, but that would mean calculating everything for all pairs on each single pair. Which seems a bit heavy.

**Comment by xmatthias** [comment]
Pairs are checked in the sequence they are in the whitelist (in the UI, from top to bottom).

Different pairlists can influence this sequence - you can find supported pairlist handlers and their documentation [here](https://www.freqtrade.io/en/stable/plugins/#pairlists-and-pairlist-handlers).

You can't assign priorities to the trades - the "priority" (actually processing sequence) is given by the pairlist sequence.
