### ISSUE TITLE
huobipro: fetchOrderBook issue

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#9543]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Miniconda latest (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.10 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

According to a previous answer of you, if one has the issue 

Error: Could not get order book due to BadRequest. Message: huobipro fetchOrderBook() limit argument must be None, 5, 10, 20, or 150, default is 150

. . .the easiest way, to resolve the error, is to set use orderbook to false.
Since I do not work with the orderbook, we shoudn't probably use huobipro at all?
. . .if you still have a workaround, I am happy, to read your solution.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
huobipro is no longer a supported alias for huobi - and will stop working with the next release (ccxt removed some of the very old aliases).

Please use `huobi` as exchange name, and it should work just fine.

**Comment by myNextCoder** [comment]
Great, yes it works again. It seems, that the rebranding to HTX is just handled (routed) internally and in a correct way.

**Comment by xmatthias** [comment]
htx and huobi are valid aliases ... 
huobipro is no longer ... :)

**Comment by myNextCoder** [comment]
Cool, indeed htx works already, I just need to use 2023.11 instead of 2023.10 (stable)
