### ISSUE TITLE
Real-time Entry Method

### ISSUE THREAD

**Issue by thkwon9474** [freqtrade/freqtrade#9544]
Operating system: Ubuntu 22.04.2 LTS(docker)
Python Version: python 3.11.4
CCXT version: 4.0.71
Freqtrade Version: freqtrade 2023.8
  
## Your question

Thank you always for providing a great platform:)

- First, the intended strategy is to buy when a trendline or support/resistance line is broken.
- With populate entry, entry is only possible when the currently used timeframe is closed (open is an exception).
- Therefore, there is a high possibility of late entry in large timeframes.
- I have seen the custom entry function, but it seems a little difficult to include the function mentioned.

Is there another way?

**Comment by xmatthias** [comment]
> With populate entry, entry is only possible when the currently used timeframe is closed (open is an exception).

This is not entirely true.
While freqtrade will only provide you with closed candles - you you can use live [orderbook data](https://www.freqtrade.io/en/stable/strategy-customization/#orderbookpair-maximum) within that function - which you can then use to compare against the support/resistance line (which you'll have based off of closed candles i assume).

You also need to set `process_only_new_candles=False` in your strategy - to have the populate_* methods called more than once per candle.

You'll need to be quite careful with performance here - as each call to  the orderbook will be an active network request, which will take x amount of time - and be counted against your ratelimit - which may slow down calls after some time.

It's also not backtestable -but you can probably simulate this behavior by comparing the support/resistance line against low/high at 1m timeframes to get a reasonable accurate simulation.

Essentially, this strategy WILL also be repainting - which means you might see entries / exits, which after seconds, disappear again as the signal is no longer there (intra-candle).
This can lead to odd, head-scratching issues, like "why did the bot enter at this candle, while there is no signal" - which is expected - but can (to some degree) be helped by having a fallback for "future" candles onto the low/high logic also used for backtesting.

We'll not be providing much support for this type of strategy, as it's quite difficult to determine what happened after the fact - but that doesn't mean it's not possible.

> I have seen the custom entry function,

not sure where - but there's no such thing for initial entries.
