### ISSUE TITLE
asyncio errors in log when using socks5 proxy config

### ISSUE THREAD

**Issue by djvl** [freqtrade/freqtrade#9546]
## Describe your environment

  * Operating system: Debian 12
  * Freqtrade Version: freqtradeorg/freqtrade:2023.11 (Docker)
  * Docker image additions: pysocks (2.4.4), aiohttp_socks (0.8.4)
  
## Describe the problem:

I recently switched from not using a proxy to a socks5 proxy setup for interacting with the exchange, Kucoin in my case. I therefore added the ‘socksProxy’ option to the config, like:
```
    "exchange": {
        "ccxt_config": {
            "socksProxy": "socks5://u:p@ip:port/"
        },
        "ccxt_async_config": {
            "socksProxy": "socks5://u:p@ip:port/"
        }
```
This works, but. Now my logs are flooded with the messages below:
```
2023-12-13 21:32:21,568 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f56372b7990>
2023-12-13 21:32:21,569 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp_socks.connector._ResponseHandler object at 0x7f56565c38c0>, 4329631.841917572)]']
connector: <aiohttp_socks.connector.ProxyConnector object at 0x7f56372b7850>
2023-12-13 21:32:21,780 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5635a90ed0>
2023-12-13 21:32:21,781 - asyncio - ERROR - Unclosed connector
connections: ['[(<aiohttp_socks.connector._ResponseHandler object at 0x7f5657082c10>, 4329632.054234342)]']
connector: <aiohttp_socks.connector.ProxyConnector object at 0x7f565698e050>
```

It might not do any harm, but the logs are less readable because it seems to log five lines for each trading pair it fetches info for.

**Comment by xmatthias** [comment]
I've never actually used a socksProxy, and i'm not sure if / how reliable that works.

From afar (with the limited logs provided) it looks a little like ccxt fails to properly close the proxy connection - but connection handling at that side is really happening at the ccxt side.

Personally, i'd recommend the use of a regular http(s) proxy - which is tested and we know works properly.

If you're constraint to using a socksProxy - please try to reproduce this without freqtrade (essentially initializing the ccxt object and making some calls - based on the error, most likely async calls).

From the discussion in #8097 - it seems like ccxt expects the session to be handled "externally" (not sure that's still the case) - but the example (https://github.com/ccxt/ccxt/blob/master/examples/py/proxy-asyncio-aiohttp-python-3.py, https://github.com/ccxt/ccxt/blob/master/examples/py/proxy-usage.py) doesn't actually do this.

However, as mentioned in that issue, i don't really see this as worth supporting for now - and i don't have the environment (nor the interest, if i'm honest) to test this, so if  external session handling is a requirement, we'll be adding an addition to the documentation that socksProxies are not supported.

**Comment by djvl** [comment]
Thanks for your detailed answer. I have successfully switched to httpsProxy. I started using socks5 because the ccxt documentation states it supports both http and websockets. And I came across some claims socks5 has latency benefits compared to https.

**Comment by xmatthias** [comment]
using the very latest ccxt version (4.1.96, released 2 hours ago) - using a socks-proxy is working just fine.

didn't test if it's faster though - as that's really dependant on different things.
