### ISSUE TITLE
Issue with PrecisionFilter

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#9551]
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.11 stable version (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Only since today the PrecisionFilter eliminates coins, it shouldn't:

Whitelist with PrecisionFilter:

DOGE/USD, LINK/USD, NANO/USD, BCH/USD, EOS/USD, AAVE/USD

Whitelist without PrecisionFilter:

AVAX/USD, WAVES/USD, KNC/USD, ARB/USD, OGN/USD, ETH/USD, BCH/USD, MKR/USD, XTZ/USD, LDO/USD, ETC/USD, FIL/USD, AAVE/USD, COMP/USD, APT/USD, ENS/USD, BTC/USD, RNDR/USD, ICP/USD, ATOM/USD, BAT/USD, BOND/USD, EOS/USD, LTC/USD, QTUM/USD, SNX/USD, INJ/USD, UNI/USD, SAND/USD, LINK/USD, XRP/USD, MATIC/USD, DOT/USD, ADA/USD, ACH/USD, DYDX/USD, IMX/USD

. . .so the filter, which eliminates low value coins, suddenly deletes for example BTC and ETH.

I didn't change anything different in the config. My pairlist filter was edited last in October, and it worked fine since then.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
without your actual (pairlist) configuration and the exchange used - as well as  the logs the removal generates - there's nothing we will be able to do for you.

**Comment by myNextCoder** [comment]
I was thinking about a specific PrecisionFilter issue. But during my preparation of a test config file for you, I discovered, that here the PrecisionFilter makes no difference anymore. So it might be a "side-effect" of my usual configuration, which I need to analyze now. I let you know asap, if I still need your help.

**Comment by xmatthias** [comment]
Can't recreate this - precisionfilter works as expected.

Let me know if you still think it's the Precisionfilter ... but it's most likely something else.

**Comment by myNextCoder** [comment]
I just have discovered the issue, finally, it is no PrecisionFilter issue, but an unknown stoploss thing:

I send you your config full example json, with just as little changes, for letting run Freqtrade with USD stake.
I have set a strategy, which is known and publicly available. Originally the json file has a stoploss of -0.1.
This works fine.
I changed it to -1.0 (disable), which in my case leads to a whitelist of 0 pairs. I my test config I have no additional config file, and the command line looks like this:
freqtrade trade --config \\path\config_full.example.json

As I eliminate stoploss from the file (using the value from the py file), or set it to -0.99, it works fine.
So it is up to you, if you want to gather out, why stoploss interferes with the pairlist.


[config_full.example.json](https://github.com/freqtrade/freqtrade/files/13696701/config_full.example.json)

**Comment by xmatthias** [comment]
If you carefully read the documentation for the [PrecisionFilter](https://www.freqtrade.io/en/latest/plugins/#precisionfilter) - you'll find the following:

> Filters low-value coins which would not allow setting stoplosses.

This means - if you disable a stoploss, then it'll no longer be relevant / functional.
That's expected, and i doubt that using -0.99 will get you expected results from this filter, as it'll remove ANY pair where the minimum order price is above `current price * (1-0.99)`.

It's designed to prevent trading at the lower edge of a pair (where a 10% down gap would lead to the trade being unsellable).

Stupidly throwing filters in without reason is however not what it's designed for.

**Comment by myNextCoder** [comment]
I thank you, and I will take care of the value exactly now. In fact I have somehow copied the idea of disabling stoploss, from several known Freqtrade strategy programmers out there, with the idea, to handle losses in custom exit. But even there, I do not sell them at a certain level, my stoploss is timebombed, depends on indicators, and I only exit partially, step by step, if really needed. That's why, I want to be sure, that the system does not simply kick out my trade at a fixed minus level, where an uptrend might follow soon.

**Comment by xmatthias** [comment]
in that case, you're responsible to check for the "sellability" of your trade should it drop further.

That's not bad per se - but completely disabling stoploss means that you're responsible without fallback. if your code fails for some reasons, you can also encounter 100% loss on the position.
We specifically enable this - but it's not something i'd encourage, as it's usually a sign of a strategy that's keeping in (losing) positions for WAY too long - quite often to game backtest results to "never lose" by keeping losers open until they break even (and then be surprised if live, you run into a -60% position ...).

**Comment by myNextCoder** [comment]
Yes, in my case, my code needs to catch the losses at the right time. In very seldom cases, the trade goes to less than -30%. Part of my strategy, which is not algorithmic, is to put coins on the blacklist manually, which show a "crazy chart": Thanks to this, my positions do not deep dive anymore that often.
