### ISSUE TITLE
bitvavo: unsupported operand type(s) for +=: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by spidersecurity** [freqtrade/freqtrade#9560]
Getting error while backtesting with bitvavo. I've configured the docker-compose file for develop image and ran. Download data went successful but backtest!

2023-12-17 11:31:39,286 - freqtrade.strategy.hyper - INFO - Strategy Parameter: base_nb_candles_buy = 13
2023-12-17 11:31:39,286 - freqtrade.strategy.hyper - INFO - Strategy Parameter: ewo_high = 5.835
2023-12-17 11:31:39,286 - freqtrade.strategy.hyper - INFO - Strategy Parameter: ewo_low = -19.909
2023-12-17 11:31:39,287 - freqtrade.strategy.hyper - INFO - Strategy Parameter: low_offset = 0.978
2023-12-17 11:31:39,287 - freqtrade.strategy.hyper - INFO - Strategy Parameter: rsi_buy = 55
2023-12-17 11:31:39,288 - freqtrade.strategy.hyper - INFO - Strategy Parameter: base_nb_candles_sell = 18
2023-12-17 11:31:39,288 - freqtrade.strategy.hyper - INFO - Strategy Parameter: high_offset = 1.012
2023-12-17 11:31:39,288 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2023-12-17 11:31:39,301 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2023-12-01 07:30:00 up to 2023-12-17 11:15:00 (16 days).
2023-12-17 11:31:39,367 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1401, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1335, in backtest_one_strategy
    results = self.backtest(
              ^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1277, in backtest
    open_trade_count_start = self.backtest_loop(
                             ^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1188, in backtest_loop
    LocalTrade.close_bt_trade(trade)
  File "/freqtrade/freqtrade/persistence/trade_model.py", line 1251, in close_bt_trade
    LocalTrade.total_profit += trade.close_profit_abs
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
ERROR: 1

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

**Comment by spidersecurity** [comment]
@xmatthias Sorry for missing that – pls find below. Let me know if I need to open up a new one.



## Describe your environment

  * Operating system: Ubuntu 22.04, Running in docker (Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1)
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`) – 4.1.84
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker) – -v switch isn't showing any results and exiting, any other way I can determine the version pls?
  
## Your question

unsupported operand type(s) for +=: 'int' and 'NoneType' while backtesting with bitvavo

**Comment by spidersecurity** [comment]
+ My config:
```
{
    "max_open_trades": 3,
    "stake_currency": "EUR",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "EUR",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "bitvavo",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": ["ETH/EUR","BTC/EUR", "ALGO/EUR", "SOL/EUR", "BTT/EUR"
        ],
        "pair_blacklist": [
        ]
    },
    "pairlists": [
        {
            "method": "StaticPairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": true,
        "token": "xxk",
        "chat_id": "xx"
    },
    "api_server": {
        "enabled": false,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "f8<>6",
        "ws_token": "Nc<>Q",
        "CORS_origins": [],
        "username": "",
        "password": ""
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```

**Comment by spidersecurity** [comment]
+ My strategy:

```
from freqtrade.strategy.interface import IStrategy
from typing import Dict, List
from functools import reduce
from pandas import DataFrame
# --------------------------------
import talib.abstract as ta
import numpy as np
import freqtrade.vendor.qtpylib.indicators as qtpylib
import datetime
from technical.util import resample_to_interval, resampled_merge
from datetime import datetime, timedelta
from freqtrade.persistence import Trade
from freqtrade.strategy import stoploss_from_open, merge_informative_pair, DecimalParameter, IntParameter, CategoricalParameter
import technical.indicators as ftt



def EWO(dataframe, ema_length=5, ema2_length=35):
    df = dataframe.copy()
    ema1 = ta.EMA(df, timeperiod=ema_length)
    ema2 = ta.EMA(df, timeperiod=ema2_length)
    emadif = (ema1 - ema2) / df['close'] * 100
    return emadif


class SMAOffsetProtectOptV1(IStrategy):
    INTERFACE_VERSION = 2

    # Buy hyperspace params:
    buy_params = {
        "base_nb_candles_buy": 13,
        "ewo_high": 5.835,
        "ewo_low": -19.909,
        "low_offset": 0.978,
        "rsi_buy": 55,
    }
    # Sell hyperspace params:
    sell_params = {
        "base_nb_candles_sell": 18,
        "high_offset": 1.012,
    }

    # and disable roi:
    # ROI table:
    minimal_roi = {
        "0": 100.0
    }

    # Stoploss:
    stoploss = -0.15

    protections = [
        # 	{
        # 		"method": "StoplossGuard",
        # 		"lookback_period_candles": 12,
        # 		"trade_limit": 1,
        # 		"stop_duration_candles": 6,
        # 		"only_per_pair": True
        # 	},
        # 	{
        # 		"method": "StoplossGuard",
        # 		"lookback_period_candles": 12,
        # 		"trade_limit": 2,
        # 		"stop_duration_candles": 6,
        # 		"only_per_pair": False
        # 	},
        {
            "method": "LowProfitPairs",
            "lookback_period_candles": 60,
            "trade_limit": 1,
            "stop_duration": 60,
            "required_profit": -0.05
        },
        {
            "method": "CooldownPeriod",
            "stop_duration_candles": 2
        }
    ]

    # SMAOffset
    base_nb_candles_buy = IntParameter(
        5, 80, default=buy_params['base_nb_candles_buy'], space='buy', optimize=True)
    base_nb_candles_sell = IntParameter(
        5, 80, default=sell_params['base_nb_candles_sell'], space='sell', optimize=True)
    low_offset = DecimalParameter(
        0.9, 0.99, default=buy_params['low_offset'], space='buy', optimize=True)
    high_offset = DecimalParameter(
        0.99, 1.1, default=sell_params['high_offset'], space='sell', optimize=True)

    # Protection
    fast_ewo = 50
    slow_ewo = 200
    ewo_low = DecimalParameter(-20.0, -8.0,
                               default=buy_params['ewo_low'], space='buy', optimize=True)
    ewo_high = DecimalParameter(
        2.0, 12.0, default=buy_params['ewo_high'], space='buy', optimize=True)
    rsi_buy = IntParameter(30, 70, default=buy_params['rsi_buy'], space='buy', optimize=True)


    # Trailing stop:
    trailing_stop = False
    trailing_stop_positive = 0.001
    trailing_stop_positive_offset = 0.01
    trailing_only_offset_is_reached = True

    # Sell signal
    use_sell_signal = True
    sell_profit_only = False
    sell_profit_offset = 0.01
    ignore_roi_if_buy_signal = True

    # Optimal timeframe for the strategy
    timeframe = '5m'
    informative_timeframe = '1h'

    process_only_new_candles = True
    startup_candle_count = 30

    plot_config = {
        'main_plot': {
            'ma_buy': {'color': 'orange'},
            'ma_sell': {'color': 'orange'},
        },
    }

    use_custom_stoploss = False

    def informative_pairs(self):

        pairs = self.dp.current_whitelist()
        informative_pairs = [(pair, self.informative_timeframe) for pair in pairs]

        return informative_pairs

    def get_informative_indicators(self, metadata: dict):

        dataframe = self.dp.get_pair_dataframe(
            pair=metadata['pair'], timeframe=self.informative_timeframe)

        return dataframe

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        if self.config['runmode'].value == 'hyperopt':
            # Calculate all ma_buy values
            for val in self.base_nb_candles_buy.range:
                dataframe[f'ma_{val}'] = ta.EMA(dataframe, timeperiod=val)
        else:
            dataframe[f'ma_{self.base_nb_candles_buy.value}'] = ta.EMA(dataframe, timeperiod=self.base_nb_candles_buy.value)
            dataframe[f'ma_{self.base_nb_candles_sell.value}'] = ta.EMA(dataframe, timeperiod=self.base_nb_candles_sell.value)

        # Elliot
        dataframe['EWO'] = EWO(dataframe, self.fast_ewo, self.slow_ewo)
        
        # RSI
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        conditions = []

        conditions.append(
            (
                (dataframe['close'] < (dataframe[f'ma_{self.base_nb_candles_buy.value}'] * self.low_offset.value)) &
                (dataframe['EWO'] > self.ewo_high.value) &
                (dataframe['rsi'] < self.rsi_buy.value) &
                (dataframe['volume'] > 0)
            )
        )

        conditions.append(
            (
                (dataframe['close'] < (dataframe[f'ma_{self.base_nb_candles_buy.value}'] * self.low_offset.value)) &
                (dataframe['EWO'] < self.ewo_low.value) &
                (dataframe['volume'] > 0)
            )
        )

        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x | y, conditions),
                'buy'
            ]=1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        conditions = []

        conditions.append(
            (
                (dataframe['close'] > (dataframe[f'ma_{self.base_nb_candles_sell.value}'] * self.high_offset.value)) &
                (dataframe['volume'] > 0)
            )
        )

        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x | y, conditions),
                'sell'
            ]=1

        return dataframe
 ```

**Comment by xmatthias** [comment]
> * v switch isn't showing any results and exiting, any other way I can determine the version pls?

on docker, you can use `docker compose run --rm freqtrade -V` (as the template says). 
obviously assumes that "freqtrade" is the name of the service - but i'd assume this to be the case.

that'll give you the version number - which is important for such issues.

**Comment by spidersecurity** [comment]
@xmatthias Pls find it: _freqtrade docker-2023.12-dev-4cc4f0ff_

**Comment by xmatthias** [comment]
This seems to be an oddity in bitvavo (or in the setting from ccxt, anyway) - which defines the ["precision mode"](https://docs.ccxt.com/#/README?id=precision-mode) as `significant_digits`.

https://github.com/ccxt/ccxt/blob/58d08bd8859f58a1f12e52fd240aca9becc1050d/ts/src/bitvavo.ts#L274

for BTT/EUR - the designated amount-precision is 0 ... which means ALL values (no matter how small or big) will round to 0.
this doesn't sound correct to me from afar - but bitvavo is special in many ways, not just for this.

**Comment by xmatthias** [comment]
I've opened an issue on ccxt for this - we'll see what they respond.
https://github.com/ccxt/ccxt/issues/20408

**Comment by spidersecurity** [comment]
Thanks @xmatthias. Does this mean the backtest will work if I exclude BTT from whitelist and check with others?

**Comment by xmatthias** [comment]
Most likely (the prolem with BTT is that it's "precision" is 0) - but it's a bit of a game of luck, as there might also be other oddities in other piars that don't trigger the bug - but round the amount (or price) to an insane number...

**Comment by spidersecurity** [comment]
@xmatthias That worked by simply removing BTT from the list!

**Comment by xmatthias** [comment]
A little late - but i've ran into this same issue on another exchange - hence we're now overriding the mode given from ccxt for selected exchanges (currently 2).

That implicitly means that freqtrade will also work for BTT (or other coins with similar problems) - starting with the version for the commit that'll be linked to this issue.
