### ISSUE TITLE
No result after running hyperopt

### ISSUE THREAD

**Issue by godshades** [freqtrade/freqtrade#9580]
## Describe your environment

Operating system: Ubuntu 20.0.4
Python Version: 3.11.5
CCXT version: 4.1.22
Freqtrade Version: 2023.10
  
## Your question

Hi i have running a ProfitDrawDownHyperOptLoss on my vps, after 3-4 days it's finished but i can't find any log or file in hyperopt_results
So does this mean i'm running error ?

**Comment by xmatthias** [comment]
well hyperopt will print results to the console you've been running hyperopt.

Assuming it completed successfully, then you can also use `freqtrade hyperopt-list` and / or `freqtrade hyperopt-show` to list previous results.
obviously this assumes that there's results in hyperopt_results.

If there's nothing in that directory, then you're either in the wrong user_data structure - or hyperopt never actually ran (hyperopt dumps intermediate data after each batch, and doesn't "really" delete that data afterwards) - and as a consequence you waited on a process that never actually started.

Logs MIGHT tell you what happened (again, the console you ran the process in) - but without hyperopt results - it probably won't have run - so there's nothing to look at.
