### ISSUE TITLE
Apply selling strategy according to buying period

### ISSUE THREAD

**Issue by kbjang** [freqtrade/freqtrade#9588]
## Describe your environment

  * Operating system:Ubuntu 22.04.3 LTS
  * Python Version: 3.10.12
  * CCXT version:3.0.98
  * Freqtrade Version: 2022.11
  
## Your question

I would like to apply the exit strategy differently depending on the entry period. For example, I would like to apply strategy 1 within 1 hour after entry and strategy 2 after 1 hour after entry.
Is this possible on freqtrade? If possible, please provide a simple sample code.

**Comment by stash86** [comment]
https://www.freqtrade.io/en/latest/strategy-callbacks/#time-based-trailing-stop

**Comment by froggleston** [comment]
There's also a time-based example for immediate exits in the [custom exit callback example](https://www.freqtrade.io/en/latest/strategy-callbacks/#custom-exit-signal)
