### ISSUE TITLE
Minimum stake amount > available balance (bitget)

### ISSUE THREAD

**Issue by victormoc** [freqtrade/freqtrade#9603]
## Describe your environment

  * Operating system: ubuntu 22.04 lts
  * Python Version: python 3.10.12
  * CCXT version: ccxt 4.1.99
  * Freqtrade Version: freqtrade 2023.11
  
## Your question

Hello family, Im trying to run the sample strategy bot live using bitget broker, but Im getting this error:

`freqtrade.wallets - WARNING - Minimum stake amount > available balance. 5.25 > 0.0`

So according to this message my available balance = 0.0, but according to telegram /balance:

```
Starting capital: 1000 USDT , 999.996 USD.
USDT:
 Available: 1000.00000000
 Balance: 1000.00000000
 Pending: 0.00000000
 Bot Owned: 990.00000000
 Est. USDT: 990

Estimated Value (Bot managed assets only):
 USDT: 990
 USD: 989.996
```
Here is my config.json:

```
{
    "max_open_trades": 3,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": false,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
```
There are [one](https://github.com/freqtrade/freqtrade/issues/8091) [two](https://github.com/freqtrade/freqtrade/issues/4224) issues with a similar error but I didn't find a solution to my problem, I'm new to the freqtrade environment, if anyone can help me I would be very grateful!

**Comment by xmatthias** [comment]
While the message says "Minimum stake amount > available balance" - the value it's compared against is really a combination of available balance and maximum stake amount for this pair.

Now "available balance" will depend on a ton of things - config is one - but already open trades is another point.

The single log line doesn't mention any of that (nor the pair in question) - so for now, i'll speculate that either there were open trades already (so no balance was available at that point) - or the pair has a (wrongly set) max_amount of 0.



---

please keep in mind - bitget is an unsupported exchange, so you're probably the first to have a look at this exchange.
we have a rough guideline on things to check in the [contributors section of the documentation](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip).
While it's probably not complete, it should give you a good idea if the exchange will work for spot trading.

If you encounter specific problems, we're happy to assist up to a certain point - but the expectation for new exchanges is that the user interested is doing the legwork / most of the testing work - which also assumes a somewhat familiarity with python / testing/debugging things in python.

If you're new to python / development - you're better of with one of the supported exchanges.

**Comment by victormoc** [comment]
Thank you for your prompt response and clarification. I've taken note of the considerations you mentioned regarding the "Minimum stake amount > available balance" issue. It seems that the issue is specific to Bitget, an unsupported exchange.

I appreciate the guidance provided in the contributors' section of the documentation, and I understand that for unsupported exchanges, the expectation is for users to conduct most of the testing work.

I'll continue investigating the issue with Bitget, keeping in mind the points you raised. If I encounter specific problems, I'll reach out for assistance up to the specified limit.

Thanks again for your help!
