### ISSUE TITLE
Can't connect to web UI

### ISSUE THREAD

**Issue by ar-g** [freqtrade/freqtrade#9604]
## Describe your environment

  * Operating system: MacOS 13
  * Freqtrade Version: Latest
 
## Your question

After running docker with default user configuration can't access WebUi on http://127.0.0.1:8081/, getting 

`This page isn’t working127.0.0.1 didn’t send any data.
ERR_EMPTY_RESPONSE`

I've tried to change the port to 8083, but same issue occur.

I was following this page for the setup https://www.freqtrade.io/en/latest/docker_quickstart/

Here is the config:

https://gist.github.com/ar-g/37db50c8e57b3cc8671836d57440679f

**Comment by xmatthias** [comment]
based on the docker default config, it should be on port 8080, not on 8081.

Now this can be changed based on the docker-compose file - but your config seems wrong - for docker, the listen_ip_address should be 0.0.0.0, not 127.0.0.1 - which is also in the documentation you yourself linked above :)

**Comment by ar-g** [comment]
@xmatthias indeed, the ports were messed up, was just confusing that the ports needs to be `0.0.0.0:8080`, but actual UI is on `http://127.0.0.1:8080/`
