### ISSUE TITLE
`Trades Log` not shown in ip:8080/dashboard

### ISSUE THREAD

**Issue by HelloWorldWinning** [freqtrade/freqtrade#9605]
<img width="1025" alt="Trades Log" src="https://github.com/freqtrade/freqtrade/assets/16793742/1ee8849e-f4fa-4d39-bd10-3050cb6367e8">

freqtradeorg/freqtrade   stable    935b42c7dbe2   3 weeks ago   1.15GB
freqtradeorg/freqtrade   older_version    92d3cace0445   8 weeks ago   1.09GB

older_version works fine.

 buggy image info: 

 docker inspect 935b42c7dbe2
[
    {
        "Id": "sha256:935b42c7dbe25b76ccf7ee8817c9b7f37ab7def0f7464c17bec9f0f4d79d9afe",
        "RepoTags": [
            "freqtradeorg/freqtrade:stable"
        ],
        "RepoDigests": [
            "freqtradeorg/freqtrade@sha256:6c9773772ed92e980ccec1e125d5f36fdd633c108a8cebd88a4b8169fc193904"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2023-11-30T16:45:44.700283764Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "ftuser",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/home/ftuser/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D",
                "PYTHON_VERSION=3.11.6",
                "PYTHON_PIP_VERSION=23.2.1",
                "PYTHON_SETUPTOOLS_VERSION=65.5.1",
                "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/4cfa4081d27285bda1220a62a5ebf5b4bd749cdb/public/get-pip.py",
                "PYTHON_GET_PIP_SHA256=9cc01665956d22b3bf057ae8287b035827bfd895da235bcea200ab3b811790b6",
                "LC_ALL=C.UTF-8",
                "PYTHONDONTWRITEBYTECODE=1",
                "PYTHONFAULTHANDLER=1",
                "FT_APP_ENV=docker",
                "LD_LIBRARY_PATH=/usr/local/lib"
            ],
            "Cmd": [
                "trade"
            ],
            "ArgsEscaped": true,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/freqtrade",
            "Entrypoint": [
                "freqtrade"
            ],
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 1146698889,
        "VirtualSize": 1146698889,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/d0ec07191c99765e5293dacfb7f7ecdc34a39ee329cee6eb50f23fc16f3f7181/diff:/var/lib/docker/overlay2/61b0840da85dffc0e0d79e7e5492dc1f834589095fa9ec49f2ab8df26e86a6d2/diff:/var/lib/docker/overlay2/96089cfe7a7027d7bbf6e6d243d87a8b868e5f7dd300d65d1557cfee9d741756/diff:/var/lib/docker/overlay2/e39a56295ec7b7317634127135364c7b8ff3f97fb0644c6ab641ed202c57046b/diff:/var/lib/docker/overlay2/b302c389066ecfd1cfe5077f708a30c18b81dd14f54dfa4c7e348f2cd4978d92/diff:/var/lib/docker/overlay2/3750db67facd2f02589081cefd6e4edd03b2cbfaaf5ae56cb2095cf732c8bb02/diff:/var/lib/docker/overlay2/41b4cc40cd6a548133d69e5e1766239da3c2d6b3ab098abb4b04fd5532134a3e/diff:/var/lib/docker/overlay2/a0d37e4e736315913361fb97e6b804b1195f0f89f7d45e2e87c3588c0eef8a1d/diff:/var/lib/docker/overlay2/5083f574b0ee4b9edb6429d504bc7e8ef49d5a3b6156e7943b4f1134ba0035fb/diff:/var/lib/docker/overlay2/7ceda90575b6ed55494413822aca4a183c5e1bac9292c422051c4a2a1aee0392/diff",
                "MergedDir": "/var/lib/docker/overlay2/421c634589c901133ca222481cdb0ddc4eda81c755c62ad02088625cd88823e8/merged",
                "UpperDir": "/var/lib/docker/overlay2/421c634589c901133ca222481cdb0ddc4eda81c755c62ad02088625cd88823e8/diff",
                "WorkDir": "/var/lib/docker/overlay2/421c634589c901133ca222481cdb0ddc4eda81c755c62ad02088625cd88823e8/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:92770f546e065c4942829b1f0d7d1f02c2eb1e6acf0d1bc08ef0bf6be4972839",
                "sha256:ed123c9f1a56d55ad5533b08040e6518749b1ad01402871e64c0190e6b3334fb",
                "sha256:355bb094feb8871852ed726860d5d594a085a84f6409877fc25bb86e1cc33546",
                "sha256:8655910e6b5f5e04fc1f17e4b699e55049680aa26f38dc464d9f1ebc71688619",
                "sha256:d8815e8a268d3b124f3fa453c59d8327fe10d2c3742a21fad0bbe58a2ce9d8be",
                "sha256:ba43ee1e75aa1ef61cf26d4bc810c88fa8b73598e0183d5539804bd7ef938745",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:16e4d75d37e9bc7807edc953ed6c145c88676c87e41a09cbc776f2ec5236c528",
                "sha256:9a9a717423654b5fa731841701f6833cd72e7cfba1b019c60cf522373d634a9f",
                "sha256:587c1bd06f4248e7e838a9494d7611db7707d7568243903b190007b6b42351ce",
                "sha256:9ea5e71a3c14afa5eaacb935909f0082b7bcc343a7522fbd02724e229aeab5a3"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

The Image id is NOT a valid version - as it's not something we can reference on reliably. The issue template does contain precise instructions on how to get the versions.

---

This is fixed in the develop image - and will move to the stable update with the next release.
