### ISSUE TITLE
sdnotify should be disabled on systems where systemd isn't present

### ISSUE THREAD

**Issue by yurivict** [freqtrade/freqtrade#9609]
[sdnotify](https://github.com/freqtrade/freqtrade/blob/develop/requirements.txt#L36) should be disabled on *BSD systems, for example, because they don't use systems.

## Describe your environment

  * Operating system: FreeBSD 14.0 STABLE
  * Python Version: 3.9
  
## Describe the problem:

See above.

**Comment by yurivict** [comment]
Duplicate of https://github.com/freqtrade/freqtrade/issues/8167

**Comment by xmatthias** [comment]
Installing sdnotify is perfectly possible on all systems through pip (including windows) - as such, i don't really consider this as a "toxic" dependency we should try to only install where necessary.

@yurivict as mentioned in #8167 already - happy to get a PR if you think this is a must for you (i'll gladly review).

For the common freqtrade user however, this is not a relevant topic (we don't even officially support BSD, and most users i'm aware of either use docker or ubuntu), and will therefore not really provide a benefit that's worth investing my time.

The intersection of freeBSD users and freqtrade users is simply too small to justify time investment on our side.

**Comment by yurivict** [comment]
What do Windows users or MacOS users do? Do they have systemd on Windows or MacOS?

**Comment by xmatthias** [comment]
they don't need to - it's really irrelevant.

running `pip install sdnotify` on both windows and MacOS works perfectly fine - and also operationally, it's no problem to even call it afaik.

it's a plain python module - which handles the "systemd is not available" :)


As said above - you think it's a problem - please open a PR that addresses this.
If you don't - it wasn't important enough for you to spend your time on - so it's a none-issue anyway, as i can't see the benefit for freqtrade users :)
