### ISSUE TITLE
Bingx support

### ISSUE THREAD

**Issue by SajadRahimi1** [freqtrade/freqtrade#9614]
## Describe the enhancement

Hi, thanks from all that develop such thing. I suggest add Bingx support too. because of some reasons I can use only Bingx. Also there are a lot of prople like me that can use only Bingx

**Comment by xmatthias** [comment]
In theory, freqtrade supports every exchange ccxt supports, which would also include bingx.

Now you're the first to ask for that (at least as far as i remember), so you're probably the first to have a look at this.
we have a rough guideline on things to check in the [contributors section of the documentation](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip).
While it's probably not complete, it should give you a good idea if the exchange will work for spot trading.

If you encounter specific problems, we're happy to assist up to a certain point - but the expectation for new exchanges is that the user interested is doing the legwork / most of the testing work - which also assumes a somewhat familiarity with python / testing/debugging things in python.

If you're new to python / development - you're almost certainly better of with one of the supported exchanges.

---

It's a question of resources. 
Actively supporting an exchange can be timeconsuming, depending on how stable it's API is.

You're more than welcome to "adopt" bingx, testing the various aspects, and see if you can make it work (maybe it's working already - please let us know)...

This implies
* running the [tests listed in the developer section](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip)
* helping users both in github issues and on discord if they have problems with this particular exchange

As a part of that process - you'll also eventually learn a some about freqtrade internals ... :)
