### ISSUE TITLE
Is it a simple way to have DCA limit orders published on exchange?

### ISSUE THREAD

**Issue by macsim26** [freqtrade/freqtrade#9616]
## Describe your environment

  * Operating system: ____ubuntu 22.04
  * Python Version: _____3.10
  * CCXT version: _____ CCXT 4.0.105
  * Freqtrade Version: ____ 2023.11
  
## Your question

Hello,
In my leverage strategy (5X), I use the DCA to buy a token just before its liquidation. 
I'd like this purchase order to be published as a limit on the exchange so that if the token's value drops very quickly, my order is executed without fail. Is there a simple way to do this? 
Because i have try with custom_entry_price that check for  extra buy and personalised check_entry_timeout but it's realy a gas plant so i think i go in a wrong way...

Thank you

**Comment by xmatthias** [comment]
To place an order off-price, you'll have to use `custom_entry_price` (otherwise it'll just be a few orderbook slots at max, not something where you can directly control price).

If you need check_entry_timeout or not is up to you (you can also opt to replace the order every few minutes) ... 


so yes, this is the way to do this. it's not overly complicated, either, assuming some basic python knowledge.

**Comment by macsim26** [comment]
Thanks Matthias!!!
Have an happy new year!!!
Miguel

**Comment by macsim26** [comment]
Hi Matthias!
What do you mean when you say : "you can also opt to replace the order every few minutes"?
Can you give me a tips because i don't undeerstand clearly how to deal with that?
Thanks.
Miguel

**Comment by xmatthias** [comment]
As long as the trade is open - you can use [`adjust_entry_price()`](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-entry-price) to replace orders at a new / different price.

If that's what you want is beyond me - but that's what my comment above refers to.

**Comment by macsim26** [comment]
Hello i have tried to make the DCA orders to be published on the exchange without success : it seems to partially work but my log is full of "freqtrade.freqtradebot - INFO - Found open order for Trade(...)" and freqAI don't update prices even if neww candles are printed. The code i have make is :
[limit_DCA_entry.txt](https://github.com/freqtrade/freqtrade/files/13820757/limit_DCA_entry.txt)
But trades seems to be ok... Can you explain me what i am doing wrong? Thanks

**Comment by xmatthias** [comment]
> Found open order for Trade(...)

well that's expected - you place an order and wait for it to fill eventually.

your code doesn't seem to include `adjust_entry_price()` - so not sure what you're expecting to update prices ...

**Comment by macsim26** [comment]
Hi yes but freqAI  don't update prices even if new candles are printed and when i try to add adjust_entry_price() i have an error : " freqtrade.resolvers.iresolver - WARNING - Could not import /home/pcsimple/freqtrade/user_data/strategies/plenitude8.py due to 'name 'Order' is not defined'" that i don't know how to handle... Thanks

**Comment by macsim26** [comment]
In the help there is i believe an error : 
```
    def adjust_entry_price(self, trade: Trade, order: Optional[Order], pair: str,
                           current_time: datetime, proposed_rate: float, current_order_rate: float,
                           entry_tag: Optional[str], side: str, **kwargs) -> float:
```
should be : 
```
    def adjust_entry_price(self, trade: 'Trade', order: 'Optional[Order]', pair: str,
                           current_time: datetime, proposed_rate: float, current_order_rate: float,
                           entry_tag: Optional[str], side: str, **kwargs) -> float:
```
so my order error is solved but not the fact that freqUI seems locked and don't update curennt loss or profit in pais combined...

**Comment by xmatthias** [comment]
You can import `Order` from freqtrade.persistance - or use the quoted notation (both ways work - however not importing will usually lead to problems in syntax highlighting / completing.

> so my order error is solved but not the fact that freqUI seems locked and don't update curennt loss or profit in pais combined...

A trade will not have profit shown (it'll show as 0% iirc) unless the order actually filled (until then, you only show intend to enter a trade by placing an order - it's only a trade that can have / show profit once that initial order filled.

That's intentional and by design - and actually the only correct way to handle this (otherwise you might see a profit of millions - just because you placed a buy order at 1000$ for BTC - however that order will probably never fill - so you'll not have made the 40x profit).

**Comment by macsim26** [comment]
ok so it is normal that freqUI doesn't show the current realised profit or loss made by the filled order because there is an unfilled order waiting and i have no way of overpass this? 
Ok i will let the bot working to see if all is good... 
Thanks.
Miguel

**Comment by xmatthias** [comment]
Well you see the initial order didn't fill yet (* next to the Pair name)- so profit is 0.

![image](https://github.com/freqtrade/freqtrade/assets/5024695/9ce2b2e2-273a-4626-b726-19584290bac6)


This will change slightly once the initial order filled - where the rate may seem stuck - but it's really cached for RPC calls.
It'll move eventually - but not as often as when no order is open.

![image](https://github.com/freqtrade/freqtrade/assets/5024695/86e3418b-1995-4cf4-95e9-0526b89aa302)

**Comment by macsim26** [comment]
Hello thanks for this explanation but i have failed to do a working code. 
With these parameters the bot really lag and do not react normaly with the trailling stop and roi.
What i have tried to make is this : 
[limit_DCA_entry.txt](https://github.com/freqtrade/freqtrade/files/13832677/limit_DCA_entry.txt)
the exchange is well taking into account the limit order just before the liquidation price but this code seems to slow down thte bot reactvity to a extreme point... If you have some time to tell me where i am wrong in other case i will keep my working version and accept to be sometimes hardly liquidated like yesterdays where i have lost two month of benefits... Thanks a lot. Miguel

**Comment by xmatthias** [comment]
you've got an open order - so you're responsible for trade handling until that order is canceled, or cancel the order if you expect the bot to use "shortcuts" like ROI and trailing stop.

this includes eventual ROI or trailing stop sells.

so if your trade moves somewhere you'd like to place a different order (like, exit completely) - the strategy must first cancel the order - uppon which regular trade handling will continue.

**Comment by macsim26** [comment]
Hello, the short answer to my question is no: there's no easy way to publish a DCA limit order on the exchange...
If there's no way of getting around this difficulty, it means that you have to manage the transactions manually, and that's not what I was looking for. 

Thanks
Miguel

**Comment by xmatthias** [comment]
you asked if it's possible to easily publish them to the exchange.
That's easily possible with 1 callback - and if the order fills within reasonable time (is not placed at insane prices) - that can pretty easily be handled by a order timeout set to something around a minute or so.

If your goal is to have  open order at all times - then this is different - and comes with drawbacks - starting with "you'll always be slower in handling everything else - as 
* the bot must check if the order filled
* the bot must cancel the order before proceeding processing other orders 

As such - i think your actual requirement was stated wrongly.
It's not difficult to do - assuming you keep some common sense in the process.
