### ISSUE TITLE
Adjusting leverage on ongoing trade

### ISSUE THREAD

**Issue by Axel-CH** [freqtrade/freqtrade#9630]
## Describe the enhancement
In order to allow a better capital allocation of users wallet, a considerably useful feature is the capacity to  **adjust the leverage during a trade** with an active position related to:

- stake
- stoploss
- liquidation price
- maximum leverage
- current leverage

In case of a trailing stop loss, as the risk of liquidation is mitigated, there is no point keeping exceeding stake locked in a positive position.

*Explain the enhancement you would like*
At each process loop, after "custom_stop_loss" callback and before "adjust_trade_position" the "adjust_trade_leverage" callback will be called. The leverage could be raised here, that will free some capital in wallet just before "adjust_trade_position".

**Comment by xmatthias** [comment]
Adjusting leverage is not possible - and there's also no plans in adding this in the future.

you can just as well change your risk by simply changing the position size - which will free up some capital.

---

I've also got little idea how to properly calculate profits in such a scenario.

The increase in complexity of calculations in case of complex scenarios (multi-position adjustments, including with mutiple leverage changes...) is non-trivial - and i neither have  interest nor time in burdening myself with that added complexity, not with the resource constraints present.

You're obviously free to contribute this - but please **first** come up with a proper way to calculate profits in complex, multi-order, multi-leverage adjustment scenarios, which we can play through in detail on paper.

I'd also come with the assumption that you're able and willing to dedicate some hours a week to maintain and support this should problems with the logic arise (also in the future, not just short-term).
Unfortunately (and considering current and past contributions, which were often left unfinished) - this last part is almost certainly the breaking point - as i currently don't think you'll have this dedication.

**Comment by Axel-CH** [comment]
Hello @xmatthias thank you for your reply, I fully understand the issues you raised. We both have to deal with limited resources.
I will reopen this issue when I will have more bandwidth to integrate and maintain it. Concerning, my current contributions, I will allow more time to them as soon as possible, normally in a 2 or 3 weeks.
