### ISSUE TITLE
coinex Exchange is not supported for future trading.

### ISSUE THREAD

**Issue by 0xh0551** [freqtrade/freqtrade#9632]
## Describe your environment

  * Operating system: ____ Linux
  * Python Version: _____ 3.11
  * CCXT version: _____ 4.1.98
  * Freqtrade Version: ____2023.12
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

hello all, hope you are doing great and happy new year 2024.
I have an account on CoinEX exchange. every time the bot runs, backtests, ... it logs:
```
WARNING - Exchange "coinex" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
```

but it was working fine on SPOT market. now I want to use features of future trading, when I change the config to 
```
    "trading_mode": "future",
    "margin_mode": "isolated"
```

it logs an error:
```
freqtrade - ERROR - Freqtrade does not support isolated futures on CoinEx
```

just wanted to ask why? CoinEX is supported by CCXT library (CCT Certified and CCXT Pro). Why freqtrade future trading is not supported by freqtrade? 
and, will be supported or not?

### Steps to reproduce:

  1. running the bot of future market.
  2. backtesting a future config

**Comment by xmatthias** [comment]
the library is supported by ccxt. 
As far as i know, that only means that they paid for the certification - and that basic functionality (authentication, fetching and placing orders, ...) does work. 
It doesn't guarantee flawless functioning with freqtrade - nor does it aim to say that.

Most exchanges in ccxt (independent of being certified or not) do work out of the box with freqtrade for spot markets only.

Futures markets require different, per exchange adjustments (they all usually use different liquidation formulaes, often different formulas for funding rates, ...) and settings, and therefore do not work out of the box.

It's a non-neglectible time-investment to get an exchange integrated for futures - which means we'll have to pick and choose which exchanges we aim to support (in our free time).
This includes availability in our country - but also interest on our side to actually use that exchange.

Looking at different exchange rankings (coinmarketcap, coingecko) - the exchange lists at 58th place for futures exchanges (coinmarketcap), and at 66 on coingecko (which i assume is combined volume).

At the volume it's showing currently - it's not worth our time investment at this point in time.

If you're looking to use futures with freqtrade, please use one of the [supported futures exchanges](https://www.freqtrade.io/en/stable/#supported-futures-exchanges-experimental).
