### ISSUE TITLE
adjust_trade_position() | Not work with leverage 3

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9636]
## Describe your environment

  * Operating system: ubuntu 20.4
  * Python Version: 3.8.10
  * CCXT version: 4.1.98
  * Freqtrade Version: 2023.12
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

My code:

```
max_entry_position_adjustment = 0

order_types = {
        "entry": "market",
        "exit": "market",
        "emergency_exit": "market",
        "force_entry": "market",
        "force_exit": "market",
        "stoploss": "market",
        "stoploss_on_exchange": True,
        "stoploss_on_exchange_interval": 60,
        "stoploss_on_exchange_limit_ratio": 0.99
    }

def leverage(self, pair: str, current_time: datetime, current_rate: float,
             proposed_leverage: float, max_leverage: float, entry_tag: Optional[str], side: str,
             **kwargs) -> float:
    if pair == "BTC/USDT:USDT" or pair == "ETH/USDT:USDT":
        return 10

    return 3

def adjust_trade_position(self, trade: Trade, current_time: datetime,
                          current_rate: float, current_profit: float,
                          min_stake: Optional[float], max_stake: float,
                          current_entry_rate: float, current_exit_rate: float,
                          current_entry_profit: float, current_exit_profit: float,
                          **kwargs) -> Optional[float]:

    if current_profit >= 0.10 and trade.nr_of_successful_exits == 0:
        return -((trade.stake_amount * trade.leverage) / 2)
```

The bot has successfully bought the trading pair: SEI/USDT:USDT:

```
Binance: Long SEI/USDT:USDT (#7)
Amount: 389.00000000
Leverage: 3.0
Open Rate: 0.78460000
Current Rate: 0.78460000
Total: (101.736 USDT, 101.838 USD)
```
However, when SEI/USDT:USDT reached a profit of 10%, it did not successfully sell half of it. The log displayed the following information:

```
2024-01-04 12:55:01 freqtrade.freqtradebot: INFO - Adjusting amount to trade.amount as it is higher. 563.0 > 389.0
2024-01-04 12:55:01 freqtrade.freqtradebot: INFO - Remaining amount of 0.0 would be smaller than the minimum of 7.5.
2024-01-04 12:55:40 freqtrade.worker: INFO - Bot heartbeat. PID=1, version='2023.12', state='RUNNING'
2024-01-04 12:55:48 freqtrade.freqtradebot: INFO - Adjusting amount to trade.amount as it is higher. 563.0 > 389.0
2024-01-04 12:55:48 freqtrade.freqtradebot: INFO - Remaining amount of 0.0 would be smaller than the minimum of 7.5.
2024-01-04 12:55:53 freqtrade.freqtradebot: INFO - Adjusting amount to trade.amount as it is higher. 564.0 > 389.0
2024-01-04 12:55:53 freqtrade.freqtradebot: INFO - Remaining amount of 0.0 would be smaller than the minimum of 7.5.
2024-01-04 12:55:58 freqtrade.freqtradebot: INFO - Adjusting amount to trade.amount as it is higher. 563.0 > 389.0
2024-01-04 12:55:58 freqtrade.freqtradebot: INFO - Remaining amount of 0.0 would be smaller than the minimum of 7.5.
2024-01-04 12:56:40 freqtrade.worker: INFO - Bot heartbeat. PID=1, version='2023.12', state='RUNNING'
```
**Please, is it possible that the reason for the issue is that my code line is not written correctly?**

```
return -((trade.stake_amount * trade.leverage) / 2)
```

thanks.

**Comment by xmatthias** [comment]
well the adjustment is assumed to be in stake_currency - **before** leverage (so if you buy with a stake_amount of 50$ - you get a position of 100$ at 2x leverage).

to sell half of that trade - the assumption would therefore be to return 25$ (25*2x = 50$ - half of the stake).

in theory - you can remove the ".leverage" and it'll sell half.

the problem with that is - you'd sell half of the _initial_ trade value - but the trade value actually increased by 10% - so you'd be selling a little less than half of the trade (usually not a problem, still mathematically incorrect and not what you want).

you should therefore use `-(trade.amount / trade.leverage) * current_exit_rate` for a full exit through this callback (careful, only enabled in 2024.1-dev) ... or in your case, divide the result of that amount by 2 
(`-((trade.amount / trade.leverage) * current_exit_rate) / 2`)

**edit: mistakingly assumed your leverage to be 2x instead of 3x - while it'll make the calculations wrong - it won't change the conclusion you should be able to draw...

**Comment by WinPoss** [comment]
I don’t quite understand it yet. Let me study the logic you explained first.

**Comment by WinPoss** [comment]
For example, if I use 3x leverage with a margin of 100 USDT, I would obtain a position of 300 USDT. 

When reach a profit of 10%, the position actual value would be 330 USDT. 

At this point, I would like to sell half of the position, which would be 330/2.

So, can I simply write the code like this?

`return -(trade.amount / 2)`

Thank you.

**Comment by xmatthias** [comment]
no, `trade.amount / 2` would be rejected, as it'd try to sell 330 / 2 USDT (which is WAY more than your 100$ position).
You'd return the amount (in <asset> ...) - but you need to return the amount in stake-currency value (unleveraged at that).

the code i posted above = `(-((trade.amount / trade.leverage) * current_exit_rate) / 2)` - will do what you want. 

you could also return -50$ - which would correspond to `-(trade.stake_amount / 2)`  - but as mentioned above - your current (un-leveraged) position is not 100$ - but it's 330 / 3 (or 110$).


---

for partial exits, it's slightly unfortunate that the response is not in `trade.amount` - as that makes the logic stupid in certain cases. It however makes complete sense for increasing position size.

**Comment by WinPoss** [comment]
Okay, I will directly use this code:
`return (-((trade.amount / trade.leverage) * current_exit_rate) / 2)`

Mainly because my English is not good, and sometimes I don't understand the documentation accurately.

Thank you for your detailed explanation.
