### ISSUE TITLE
telegram - help command error

### ISSUE THREAD

**Issue by SaurFr06** [freqtrade/freqtrade#9639]
## Describe your environment

  * Operating system: 5.15.133.1-microsoft-standard-WSL2
  * Python Version: Python 3.10.12 (`python -V`)
  * CCXT version: ccxt==4.2.2
  * Freqtrade Version: freqtrade 2024.1-dev-ec1b2e1da
  
## Describe the problem:

/help message via telegram bot is not working

### Steps to reproduce:

  1. Send /help command to Telegram bot
  
### Observed Results:

No answer

### Relevant code exceptions or logs
freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
Traceback (most recent call last):
  File "/mnt/c/Users/xxxxx/freqtrade/freqtrade/rpc/telegram.py", line 104, in wrapper
    return await command_handler(self, *args, **kwargs)
  File "/mnt/c/Users/xxxxx/freqtrade/freqtrade/rpc/telegram.py", line 1620, in _help
    if self._rpc._freqtrade.trading_mode != TradingMode.SPOT:
AttributeError: 'FreqtradeBot' object has no attribute 'trading_mode

**Comment by xmatthias** [comment]
At maximum, this will happen at startup, where for a moment, that attribute may not exist.

If you wait for the bot to have a "Bot heartbeat" message at least once, you shouldn't encounter this anymore.

it's a theoretical problem, too - at least in my case, i'm unable to hit this splitsecond between rpc being available, and this attribute not being set.
