### ISSUE TITLE
Simple Dataframe Question

### ISSUE THREAD

**Issue by erhangunay** [freqtrade/freqtrade#9640]
## Describe your environment

  * Operating system: Windows11
  * Python Version: 3.11.6
  * CCXT version: 4.1.66
  * Freqtrade Version: freqtrade 2023.11
  
## Your question
Hello,

I have been trying to create a dataframe in populate indicators named dataframe['close_total'] in which I would like to get the sum of 2 different pairs' close values.

Is this possible?

PS: Please don't judge why I am trying to do this, I just tried my best before posting here and could not achieve it on my own.

**Comment by xmatthias** [comment]
we don't judge the "why" - though we might suggest alternatives or question if we think it won't work.


you should be able to use [`dp.get_pair_dataframe()`](https://www.freqtrade.io/en/latest/strategy-customization/#get_pair_dataframepair-timeframe) for this ... alternatively `dp.get_analyzed_dataframe()` (next topic in the docs).
