### ISSUE TITLE
FreqUI chart display range configuration

### ISSUE THREAD

**Issue by LJ-panda** [freqtrade/freqtrade#9643]
How can I adjust the visible range (number of candlesticks or time range length) of the pair chart in FreqUI?
<img width="1481" alt="image" src="https://github.com/freqtrade/freqtrade/assets/35164962/04c5fbcb-7c3d-44c7-a848-aefc5d500e99">

**Comment by xmatthias** [comment]
freqUI will display all candles available to the bot - but no more (there's no indicators calculated for this, ...).

You can (to some degree) change this via `startup_candle_count` in the strategy - BUT this has operational drawbacks and may slow your bot down to some degree, as it'll now have to calculate indicators for X times more candles.
