### ISSUE TITLE
Virtual Memory over RAM

### ISSUE THREAD

**Issue by MortonPNZ** [freqtrade/freqtrade#9661]
## Describe your environment

  * Operating system: Windows 10 22H2
  * Python Version: Python 3.10.11
  * CCXT version: ccxt 4.2.2
  * Freqtrade Version:  freqtrade 2024.1-dev-7a6888dfd
  
## Your question
When training with ReinforcementLearner_multiproc, FreqAI tries to primarily use virtual memory without utilizing RAM. Before this, I was experiencing this issue with only 32GB of memory and thought that upgrading to 96GB would solve the problem. 
My SSD is suffering from this. Т_Т
The options in config.json only affect the amount of memory used. Even with very small amounts of data, it still prefers to use virtual memory instead of physical memory.
Strategy and model file is almost identical to the one provided in the examples.
![image](https://github.com/freqtrade/freqtrade/assets/56561398/25e6a1a2-2518-4907-b0aa-d69f66408fa3)

**Comment by robcaulk** [comment]
Hello,

I'm not able to understand this screenshot, as I do not read Russian (?). 

If what you claim is true, that it does not use any real RAM, then you'd need to explain if you are using Docker or not. And if not, and you are using windows Native, then to be honest, I am of no help. I've seen nothing but problems trying to run machine learning libraries on Windows, and I do not own a windows computer to test or assist with support of that platform.

Cheers,

Robert

**Comment by MortonPNZ** [comment]
> I'm not able to understand this screenshot, as I do not read Russian (?).

Yes, its Russian. The screenshot shows 88GB of virtual memory being used, while 61GB of RAM is available.


> If what you claim is true, that it does not use any real RAM, then you'd need to explain if you are using Docker or not. And if not, and you are using windows Native, then to be honest, I am of no help. I've seen nothing but problems trying to run machine learning libraries on Windows, and I do not own a windows computer to test or assist with support of that platform.

Something like that. Only Python processes are placed in RAM, while all data and models are sent to virtual memory. If this issue does not occur on Linux, I will try switching to a Linux virtual machine.
I installed freqtrade and all its dependencies using pip install (installed everything, including from the dev file), in order to train the model I run backtest in the powershell terminal.

Here is the command I am using `freqtrade backtesting --userdir user1 --config config.json --strategy FReinforcedStrategy --timerange 20220103-20240103 --freqaimodel MyCoolRLModel` 
I don't think there's anything unusual here.
My freqai params can be slightly huge, idk. 
`"freqai": {
        "enabled": true,
        "data_kitchen_thread_count":8,
        "identifier" : "model1",
        "train_period_days": 120,
        "backtest_period_days": 30,
        "purge_old_models": 2,
        "live_retrain_hours": 12,
        "expiration_hours": 96,
        "save_backtest_models": true,
        "continual_learning": true,
        "write_metrics_to_disk": true,
        "activate_tensorboard": true,
        "feature_parameters" : {
            "include_timeframes": [],
            "include_corr_pairlist": [],
            "label_period_candles": 0,
            "include_shifted_candles": 0,
            "indicator_periods_candles": [10, 20, 50, 100],
            "plot_feature_importances": 0,
            "shuffle_after_split": false
        },
        "data_split_parameters": {
            "test_size": 0.25
        },
        "rl_config": {
            "train_cycles": 25,
            "add_state_info": false,
            "max_trade_duration_candles": 30,
            "max_training_drawdown_pct": 0.02,
            "model_type": "PPO",
            "policy_type": "MlpPolicy",
            "drop_ohlc_from_features": false,
            "model_reward_parameters": {
                "win_reward_factor": 5,
                "rr": 1,
                "profit_aim": 0.008
            },
            "progress_bar": true,
            "cpu_count": 16
        }
    }`

**Comment by MortonPNZ** [comment]
The training process looks like 2-3 minutes of CPU-intensive learning (from 8000 to 2000 it/s), then a minute of data loading and unloading into virtual memory (it/s drops to ~300), and so on in a loop until the required number of iterations is completed. I think that if we can switch from virtual memory to RAM, the iterations per second will increase and the training will take much less time. Not to mention that an SSD won't last so long.

**Comment by robcaulk** [comment]
I've never seen what you describe, I cannot reproduce what you describe, and no one from the community has ever reported RL using virtual memory instead of RAM.

The glaring issue that you have, is Windows.

Cheers,

Robert

**Comment by MortonPNZ** [comment]
> The glaring issue that you have, is Windows.

It looks very much like the truth)))

**Comment by xmatthias** [comment]
what you might wanna check here is if you're running python 32bit or python 64 bit (the former is known to only address a limited amount of memory - though that should be WAY below the 60G you claim.

I'd also think that this is not necessarily a freqtrade problem - but a problem of the model / library you're using - or even a problem of windows, which MAY be restricting "per  process" memory use.

Are you using WSL2 - or "real" windows python? (there's a difference here).
instead of a virtual machine, you might wanna try WSL2 instead to get to a windows process.

In my experience, that works quite well (better than real virtual machines, as it allows for resource sharing in a better way) - though you will need to tweak it to use more than half of your system's resources (https://learn.microsoft.com/en-us/answers/questions/1296124/how-to-increase-memory-and-cpu-limits-for-wsl2-win).

**Comment by MortonPNZ** [comment]
> I'd also think that this is not necessarily a freqtrade problem - but a problem of the model / library you're using - or even a problem of windows, which MAY be restricting "per process" memory use.

![image](https://github.com/freqtrade/freqtrade/assets/56561398/b4b71ef5-51e7-4847-a3e4-73b21287ab0b)

Maybe there could be something with Gym, because when I install it separately, I can't run freqtrade. The clean Gym environment looks a bit different from the supervised learning environment in freqtrade. As for the model, it was the default reinforcement learning model from freqtrade. I changed the model file from 5 actions to 3 actions and ReinforcementLearner_multiproc instead of classic multithread.

I have reinstalled Windows several times (when updating the RAM) and  Python environment must be clean as much as possible. All the necessary dependencies were installed from the guide + dev + ai + rl. 
Interestingly, I cannot find which process used 88 GB of virtual memory. The maximum that I see is 1.2 GB for Python.

So, few ways to solve it for me rn. WSL2 or separated linux. Could Docker also be a solution?
What level of it/s is considered normal in general? In my case, I have a powerful system with a 7950x Ryzen.

**Comment by robcaulk** [comment]
> The clean Gym environment looks a bit different from the supervised learning environment in freqtrade. 

I don't know what this means.

>  As for the model, it was the default reinforcement learning model from freqtrade. I changed the model file from 5 actions to 3 actions and ReinforcementLearner_multiproc instead of classic multithread.

These two sentences contradict one another. The "default" model is not `ReinforcementLearner_multiproc`, it is `ReinforcementLearner`. So use the default one if you are debugging a problem. Adding more complexity with `_multiproc` is not going to make it easier to understand your problem.

> What level of it/s is considered normal in general?

Depends entirely on hyperparameters, hardware, network architecture, algorithm choice, etc. etc. etc.

**Comment by MortonPNZ** [comment]
> These two sentences contradict one another. The "default" model is not `ReinforcementLearner_multiproc`, it is `ReinforcementLearner`. So use the default one if you are debugging a problem. Adding more complexity with `_multiproc` is not going to make it easier to understand your problem.

Sorry, I simply used a "default" model from guides/examples and made 2 changes: _multiproc and Base3ActionRLEnv. 

Without multiproc, it works well, but I want to train the model over a few years. The default ReinforcementLearner works at 1200-2000 it/s and will take a few days. The ReinforcementLearner_multiproc is much faster but more demanding on the SSD. And it can be faster if i found how to use ram instead of virtual memory

It turns out that I did exactly what you are talking about. I checked(debugged) that my strategy works by training it over ~30 days, but I expect to get better results when I train it over 2-3 years.

**Comment by robcaulk** [comment]
You are telling us that `ReinforcementLearner` uses only RAM?

**Comment by MortonPNZ** [comment]
> You are telling us that `ReinforcementLearner` uses only RAM?

I'm not sure because the memory usage isn't as large as in multiprocessing

**Comment by robcaulk** [comment]
> I'm not sure because the memory usage isn't as large as in multiprocessing

You should be able to see the python3 process(es) for freqtrade, and their associated memory usage.

**Comment by MortonPNZ** [comment]
> You should be able to see the python3 process(es) for freqtrade, and their associated memory usage.

python processes looks like a normal but i cant see volume changes when i change days in dataset or train_period_days in freqai config. I think python process memory keeps only libs and python, and not store data for train or model

I found something. Windows process manager can show only RAM usage per process and cant show virtual memory usage, instead of process hacker.
![image](https://github.com/freqtrade/freqtrade/assets/56561398/76200c1c-c4eb-47f6-8fc1-e114b2edb8c4)

**Comment by xmatthias** [comment]
I don't think this is something freqtrade can control - it's how the different libraries do use the actual memory.
