### ISSUE TITLE
My Plan for Automatic transfer from USDT futures account to spot account

### ISSUE THREAD

**Issue by pok1800** [freqtrade/freqtrade#9663]
Hi xmatthias,
     Can I develops condition  Automatic transfer from USDT futures account to spot account in Strategy.  Found code ccxt library https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py. Refer Code below
     I skill python is beginner. you can help to develops and use function simple to me.  
     
     `def futures_transfer(self, code: str, amount, type, params={}):
        """
         * @ignore
        transfer between futures account
        :see: https://binance-docs.github.io/apidocs/spot/en/#new-future-account-transfer-user_data
        :param str code: unified currency code
        :param float amount: the amount to transfer
        :param str type: 1 - transfer from spot account to USDT-Ⓜ futures account, 2 - transfer from USDT-Ⓜ futures account to spot account, 3 - transfer from spot account to COIN-Ⓜ futures account, 4 - transfer from COIN-Ⓜ futures account to spot account
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param float params.recvWindow:
        :returns dict: a `transfer structure <https://docs.ccxt.com/#/?id=futures-transfer-structure>`
        """
        if (type < 1) or (type > 4):
            raise ArgumentsRequired(self.id + ' type must be between 1 and 4')
        self.load_markets()
        currency = self.currency(code)
        request = {
            'asset': currency['id'],
            'amount': amount,
            'type': type,
        }
        response = self.sapiPostFuturesTransfer(self.extend(request, params))
        #
        #   {
        #       "tranId": 100000001
        #   }
        #
        return self.parse_transfer(response, currency)` 

<!-- 
Have you searched for similar issues before posting it?
Did you have a VERY good look at the [documentation](https://www.freqtrade.io/en/latest/) and are sure that the question is not explained there

Please do not use the question template to report bugs or to request new features.

## Describe your environment

  * Operating system: Debian 12
  * Python Version: 3.11 (`python -V`)
  * CCXT version: 4.2.9 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.11 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that. 

---

I don't see how this relates to freqtrade, actually.
It's a plain ccxt question to me.
freqtrade will not transfer funds between accounts - and you shouldn't use keys that do have this permission, either.

You can obviously create an independent script that can perform this transfer for you - but that's clearly out of scope for freqtrade - and not something we'll be able to provide you support with.

**Comment by pok1800** [comment]
xmatthias Thank you
