### ISSUE TITLE
The "Objective" column

### ISSUE THREAD

**Issue by VerDoe** [freqtrade/freqtrade#9664]
* Operating system: Debian 6.1.67-1
  * Python Version: Python 3.11.2
  * CCXT version: ccxt==4.1.98
  * Freqtrade Version: freqtrade 2023.12
  
Hello, I have a question about the output of hyperopts. What does the "Objective" column mean? I couldn't find anything about it in the documentation. Sometimes it contains positive numbers, sometimes negative. Thanks in advance! VerDoe

**Comment by xmatthias** [comment]
The objective column is the value that's being optimized by hyperopt (in a multi-dimensional space, usually).

How that's calculated (and what factors will be included in it's calculation) will depend on the actual [loss function](https://www.freqtrade.io/en/stable/hyperopt/#loss-functions) used.
In general, hyperopt will simply try to minimize that function - which means that lower values are "better" hyperopt results (not necessarily more profitable - depending on the loss function used).

It has no meaning / comparison value outside of the same loss function - as every loss-function has other rules - and other ranges the objective value can take.
