### ISSUE TITLE
when update to new version,warnings show up?

### ISSUE THREAD

**Issue by csquan** [freqtrade/freqtrade#9666]
my system is ubuntu 20,I use docker to run freqtrade.
After update to new version,run "docker compose pull",then just run it,logs show a lot of warnings as below:
/home/ftuser/.local/lib/python3.11/site-packages/technical/indicators/overlap_studies.py:52: FutureWarning: zema is deprecated, use dema instead
  warnings.warn("zema is deprecated, use dema instead", FutureWarning)
/home/ftuser/.local/lib/python3.11/site-packages/technical/indicators/overlap_studies.py:52: FutureWarning: zema is deprecated, use dema instead
  warnings.warn("zema is deprecated, use dema instead", FutureWarning)
/home/ftuser/.local/lib/python3.11/site-packages/technical/indicators/overlap_studies.py:52: FutureWarning: zema is deprecated, use dema instead
  warnings.warn("zema is deprecated, use dema instead", FutureWarning)
what happened？

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Well exactly what the warning says.
the implementation in technical that was named `zema` did use the formula of an indicator that's actually called `dema`.

The implementation didn't change - but the name of the function was corrected.
While i've re-added a fallback method for dema for compatibility **for the moment** - using it will show the above warning - alerting users to move to `dema` instead.


More info about this removal is in this pr: https://github.com/freqtrade/technical/pull/356

**Comment by csquan** [comment]
Thankyou ,solve it.
