### ISSUE TITLE
Add option to adjust position manually via UI 

### ISSUE THREAD

**Issue by maxkrukov** [freqtrade/freqtrade#9670]
## Describe your environment
(if applicable)

  * Operating system:  any
  * Python Version: last release version
  * CCXT version: last release version
  * Freqtrade Version: last release version

## Describe the enhancement

*Explain the enhancement you would like*
It will be great to have option to adjust position manualy using freqtrade UI. So freqtrade could be not only a trader but a manager of cypto investments when you can sell and adjust stake amount in any time.

**Comment by xmatthias** [comment]
Well you can do that by enabling [force_entry](https://www.freqtrade.io/en/stable/configuration/#understand-force_entry_enable), as well as actual [position adjustments](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position) (the flag, not necessarily the callback).

You can then use the regular force-entry dialog to increase your position - and the regular partial exit dialog (click on the actions menu of the position) to reduce your position size.
