### ISSUE TITLE
Kraken: stoploss on exchange fails to be placed

### ISSUE THREAD

**Issue by VerDoe** [freqtrade/freqtrade#9673]
Operating system: Debian 6.1.67-1
Python Version: Python 3.11.2
CCXT version: ccxt==4.1.98
Freqtrade Version: freqtrade 2023.12
  
Hi, I went live with my bot for the first time today and am getting the below error from Kraken. I have the same config running on Binance, no errors there. The problem has been addressed before, but no solution has been found.

2024-01-12 09:14:17,701 - freqtrade.exchange.common - WARNING - create_stoploss() returned exception: "Could not place sell order due to ExchangeError. Message: kraken {"error":["EGeneral:Invalid arguments:price"]}". Giving up.
2024-01-12 09:14:17,701 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/app/freqtrade/freqtrade/exchange/kraken.py", line 137, in create_stoploss
    order = self._api.create_order(symbol=pair, type=ordertype, side=side,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/ccxt/kraken.py", line 1328, in create_order
    response = self.privatePostAddOrder(self.extend(orderRequest[0], orderRequest[1]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/ccxt/base/types.py", line 34, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3332, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/ccxt/base/exchange.py", line 3329, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/ccxt/base/exchange.py", line 665, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/app/freqtrade/.venv/lib/python3.11/site-packages/ccxt/kraken.py", line 2661, in handle_errors
    raise ExchangeError(message)
ccxt.base.errors.ExchangeError: kraken {"error":["EGeneral:Invalid arguments:price"]}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/freqtrade/freqtrade/freqtradebot.py", line 1188, in create_stoploss_order
    stoploss_order = self.exchange.create_stoploss(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/freqtrade/exchange/common.py", line 182, in wrapper
    raise ex
  File "/app/freqtrade/freqtrade/exchange/common.py", line 167, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/app/freqtrade/freqtrade/exchange/kraken.py", line 156, in create_stoploss
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not place sell order due to ExchangeError. Message: kraken {"error":["EGeneral:Invalid arguments:price"]}

My configuration looks like this:
```
    "stake_currency": "EUR",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.50,
    "fiat_display_currency": "EUR",
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "download_trades": true,

    "order_types": {
        "entry": "limit",
        "exit": "market",
        "emergency_exit": "market",
        "force_exit": "market",
        "force_entry": "market",
        "stoploss": "market",
        "stoploss_on_exchange": true,
        "stoploss_on_exchange_interval": 60,
        "stoploss_on_exchange_limit_ratio": 0.99
    },
...
    "exit_pricing": {
        "price_side": "other",
        "use_order_book": true,
        "order_book_top": 1
        },
```
What am I doing wrong? Thank you in advance for your answer.

VerDoe

**Comment by xmatthias** [comment]
well kraken's stoploss (through ccxt) long had the "sickness" of having the prices on stoploss orders switched, which requires special (odd) handling for stop orders on kraken. If ccxt fixed this, it MIGHT cause other issues (we can't test for this reliably in CI as it requies exchange keys).

you might wanna test with `"stoploss": "limit",`, too - as that's slightly different handling - and might be more reliable.

**Comment by VerDoe** [comment]
Hello Matthias, that doesn't work either. I get the same error. I have now disabled stoploss_on_exchange. In the latest version of ccxt some things have been done regarding Kraken. Unfortunately I don't know if it worked before, as I have only recently started using Freqtrade. Thank you for your help and big praise for your work.

**Comment by xmatthias** [comment]
it definitely did - as i did use kraken in the past actively (though it's been probably 1-2 years ago).

I'll have a look sometime this weekend i hope.

**Comment by xmatthias** [comment]
Seems like a ccxt bug - which i currently fail to get around ... 
opened an issue there ... https://github.com/ccxt/ccxt/issues/20814

**Comment by xmatthias** [comment]
ccxt fixed the issue - so we'll have kraken stoploss support back soon (once CI passes we can merge the PR). 

It'll work for both stop-loss-limit and  stop-loss-market  configurations.

**Comment by VerDoe** [comment]
Thanks @xmatthias
