### ISSUE TITLE
Can freqtrade read existing position in Binance?

### ISSUE THREAD

**Issue by yuanye72** [freqtrade/freqtrade#9674]
## Describe your environment

  * Operating system: _Windows 11___
  * Python Version: __3.10.12___ 
  * CCXT version: 4.0.26
  * Freqtrade Version: _2023.8___ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

Hello. Is there a way for the bot to detect existing positions in Binance? We want the bot to trade only the difference between the goal position and the existing position.

Background info: Our bot would occationally shut down due to connection issues (still uncliear why. asked earlier here: https://github.com/freqtrade/freqtrade/issues/9672). When we restart the bot, we would need to manually close all positions on balance for the bot to run. We want to find a way for the bot to read the existing positions and avoid repetitive trades. 

Thank you for your help
.

**Comment by stash86** [comment]
No you can’t.

**Comment by xmatthias** [comment]
> When we restart the bot, we would need to manually close all positions on balance for the bot to run

if the bot was down for some time (and nobody interfered with manual trades) - then i don't see why this should be necessary.

Now if you do manual trades on the exchange, then that's simply an unsupported activity (freqtrade assumes that it's positions are left untouched by non-bot initiated orders).

**Comment by yuanye72** [comment]
The issue we run into is, the bot crashed 3 times in a week. 
Say the bot is down and existing positing is long 100 btc. We found out and restart the bot after 5 hours. Our signal has shifted from long 100btc to short 100 btc during the 5 hours. At the 6th hour, our signal is to buy 100 btc, and the bot does. Then the open position would be 200btc, when the intended position would be 100btc.

How would you recommend we deal with such an issue?

Thanks

**Comment by yuanye72** [comment]
we dont want to trade manually unless we have to. but not sure how to automate this restart process or avoid the crash

**Comment by stash86** [comment]
Install freqtrade as service (read the docs), or use docker.

**Comment by xmatthias** [comment]
you can use freqUI to increase / decrease the position manually, assuming forcebuy and position adjustments are enabled.

Doing manual position adjustments on exchange is not supported.

You can (probably) get the position back via freqUI by using the Reload Trade action.
![image](https://github.com/freqtrade/freqtrade/assets/5024695/e54a17ef-9725-4dc4-9cc8-a8baeb51a366)

It's probably not available in a version that's more than half a year old - but your first action in case of problems should anyway be to update to the latest version.


---

An error like the one in #9672 will not cause the bot to crash - it'll just remain inactive as it has no connection to the internet anymore.
Once that connection returns - it'll continue operating. If it doesn't - then your network didn't stabilize - in which case, the most likely cause is a system-wide network problem (no notification would be sent, either - as the system is effectively cut off from the rest of the world).
