### ISSUE TITLE
Can freqtrade push notification via telegram for alerts when the bot crashes?

### ISSUE THREAD

**Issue by yuanye72** [freqtrade/freqtrade#9675]
## Describe your environment

  * Operating system: _windows11
  * Python Version: _3.9.16_
  * CCXT version: _4.0.26
  * Freqtrade Version: _2023.8_
  
## Your question

Can freqtrade push notification via telegram for alerts when the bot crsshes? Our bot crashed and we found out only hours later. Is there a way to get a push notification about such an event via email or telegram?

Background info: Our bot would occationally shut down due to connection issues (still uncliear why. asked earlier here: https://github.com/freqtrade/freqtrade/issues/9672).

Thanks

**Comment by xmatthias** [comment]
You'll get a "process died" message eventually.

You can't however rely on this 100% - as it'll assume it's a problem freqtrade itself can handle, and the "cleanup code" is actually running.

![image](https://github.com/freqtrade/freqtrade/assets/5024695/c5864e12-84fa-4a17-a66b-6c671d11c4bd)
