### ISSUE TITLE
The container name conflict (bot and Jupyter Lab)

### ISSUE THREAD

**Issue by AliM1988** [freqtrade/freqtrade#9678]
## Describe your environment

  * Operating system: ubuntu
  * Python Version: 39
  * Freqtrade Version: freqtrade docker-2024.1-dev-cd392fbb
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I want to use Jupyter Lab via your docker-compose file. ([Tut](https://medium.com/@hangyulson1004/data-analysis-using-freqtrade-step-by-step-guide-2d492e1e7579))
Since bot is running, I get this error:
`ERROR: for freqtrade  Cannot create container for service freqtrade: Conflict. The container name "/freqtrade" is already in use by container "b56e285cba22c4dcb7a0f5d125309a4ff535cb80a35298acba3c5b987e850943". You have to remove (or rename) that container to be able to reuse that name.`

Within docker-compose-jupyter.yml file, I changed the container name to "freqtrade-jupyterlab". Then, it works fine.

So, I suggest 2 below :
1. Wrote instructions for Jupyter using Docker. (see sample below)
2.  Edit your `docker-compose-jupyter.yml` to change container name in order to avoid any conflict with bot.

sample for instruction:

Data analysis using docker compose:
On your user_data directory, create a folder named docker. Inside the folder, from the links below, make a file called ‘docker-compose-jupyter.yml’ and ‘Dockerfile.jupyter’:
cd ft_userdata/
mkdir user_data/docker

curl https://raw.githubusercontent.com/freqtrade/freqtrade/develop/docker/docker-compose-jupyter.yml -o user_data/docker/docker-compose-jupyter.yml
curl https://raw.githubusercontent.com/freqtrade/freqtrade/develop/docker/Dockerfile.jupyter -o user_data/docker/Dockerfile.jupyter

run Jupyter Lab service:
docker-compose -f user_data/docker/docker-compose-jupyter.yml up
or
docker-compose -f user_data/docker/docker-compose-jupyter.yml up -d

**Comment by xmatthias** [comment]
well quite honestly, you'll encounter the same if you're running multiple bots from different directories, or if you use multiple services in the same directory.

I don't see this as a problem, really - you can simply change (or even remove) the container-name IF it conflicts - which it will only do IF you already have a container started.

Even using different names wouldn't really help this - as you might want to run 2 jupyter containers out of different directories (for example, one for spot market,s one for futures).

For the jupyter compose specifically though, i guess we can simply remove the container name - as it's not really relevant.
