### ISSUE TITLE
Deprecation warning of using `enter_tag`, will raise in future versions of `pandas`

### ISSUE THREAD

**Issue by tibm** [freqtrade/freqtrade#9679]
## Describe your environment

  * Operating system: macOS 14.1 (23B73)
  * Python Version: Python 3.11.6
  * CCXT version: ccxt==4.1.98
  * Pandas version: pandas==2.1.4
  * Freqtrade Version: 2023.12

## Describe the problem:

Deprecation warning while using `enter_tag` as described in the spec [Freqtrade Advanced Strategy](https://www.freqtrade.io/en/stable/strategy-advanced/#enter-tag)
Not a hard fault, but the warning says it will raise in the future.

However, it's a little "annoying" especially running `hyperopt`, as it will spew a lot of warnings, thus making the process less readable. Just very verbose.

### Steps to reproduce:

  1. Run any `backtesting`, `trade`, `hyperopt` or other strategy related commands with `enter_tag` defined.
  
### Observed Results:

Warning gets emitted with the following output
`/strategies/TestStrategy.py:432: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'buy_1' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.`

### Relevant code exceptions or logs

Usage example in a strategy:
```
dataframe.loc[
        (
            (dataframe['rsi'] < 35) &
            (dataframe['volume'] > 0)
        ),
        ['enter_long', 'enter_tag']] = (1, 'buy_1')
```

**Comment by stash86** [comment]
Add `dataframe['enter_tag'] = ''` on top of your populate entry. Do similar stuff on populate exit if you are using `exit_tag`

**Comment by tibm** [comment]
Awesome! This does work. 
Should this be added to the documentation? Or any ways to add this to the caller, so strategies don't have to do it? 
I'll close the issue, thanks for the help!

**Comment by xmatthias** [comment]
Effectively, it's a pandas bug (https://github.com/pandas-dev/pandas/issues/56503) ... though one that isn't fixed just yet.
