### ISSUE TITLE
Freqtrade UI error

### ISSUE THREAD

**Issue by lutyne** [freqtrade/freqtrade#9693]
## Describe your environment

  * Operating system: ```Linux version 5.15.0-76-generic (buildd@lcy02-amd64-028) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023    ```
  * Python Version: ```Python 3.10.12```
  * CCXT version: ```4.1.98```
  * Freqtrade Version:``` freqtrade 2023.12```
  
## Your question   
When entering the UI, there are often console errors, which will then produce different effects, such as: 

1. After entering the UI, except for the log interface, the click is not responding, the console request is displayed incorrectly, and the log page loading is also very slow. Here is the log when connecting

```freqtrade  | 2024-01-17 02:31:17,406 - telegram.ext.Application - INFO - Application started
freqtrade  | 2024-01-17 02:38:26,010 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2023.12', state='RUNNING'
freqtrade  | 2024-01-17 02:39:26,015 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2023.12', state='RUNNING'
freqtrade  | 2024-01-17 02:40:31,001 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2023.12', state='RUNNING'
freqtrade  | 2024-01-17 02:41:19,508 - uvicorn.error - INFO - ('47.129.x.x', 8399) - "WebSocket /api/v1/message/ws?token=eyJhbGciOiJIUzI1NiIsIwiaWF0IjoxNzA1NDU5Mjc5LCJ0eXBlIjoiYWNjZXNzIn0.P51Iem8fyd2s-PtVV1no6ItGTkzc3ZJ2Gtv-2znXM-o" [accepted]
freqtrade  | 2024-01-17 02:41:19,510 - freqtrade.rpc.api_server.ws.channel - INFO - Connected to channel - WebSocketChannel(d5a81440, ('47.129.x.x', 8399))
freqtrade  | 2024-01-17 02:41:19,511 - uvicorn.error - INFO - connection open
freqtrade  | 2024-01-17 02:41:31,003 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2023.12', state='RUNNING'
freqtrade  | 2024-01-17 02:42:31,010 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2023.12', state='RUNNING'
freqtrade  | 2024-01-17 02:42:31,865 - uvicorn.error - INFO - connection closed
freqtrade  | 2024-01-17 02:42:31,866 - freqtrade.rpc.api_server.ws.channel - INFO - Disconnected from channel - WebSocketChannel(d5a81440, ('47.129.x.x', 8399))
freqtrade  | 2024-01-17 02:43:31,012 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2023.12', state='RUNNING'
freqtrade  | 2024-01-17 02:44:31,019 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2023.12', state='RUNNING'
freqtrade  | 2024-01-17 02:44:50,274 - uvicorn.error - WARNING - Invalid HTTP request received.
freqtrade  | 2024-01-17 02:45:36,001 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2023.12', state='RUNNING'
```

2. No response after entering the UI, the page is blank, console error: 
![image](https://github.com/freqtrade/freqtrade/assets/71123821/962d36c7-52a0-487d-b806-d78a0da23c81)

The request /api/v1/ping returns pong, but the console also comes with a lot of errors:

![image](https://github.com/freqtrade/freqtrade/assets/71123821/c004d7b1-6171-4d3e-a24d-d3c6f2d12b1f)

I first used the 2023.10 version and I got this error, and it still appears when I upgrade to 12, and I have tried to use docker or script installation, and this problem occurs, but it is normal for me to use the same config.json with windowns version docker on another PC, and the error seems to only appear on this Linux, is it related to the configuration? It is worth mentioning that this Linux is 1 core and 2G memory

api_server：
``` 
"api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "xxxx",
        "ws_token": "xxxx",
        "CORS_origins": [],
        "username": "xxxx",
        "password": "xxxxx"
    },
```
docker-compose:
```---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:2023.12
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "0.0.0.0:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy Babico_SMA5xBBmid

**Comment by lutyne** [comment]
Make up a screenshot of the console that does not respond when clicking on DashBoard in Situation 1
![image](https://github.com/freqtrade/freqtrade/assets/71123821/7fc4a831-f171-42e6-ac34-433e2c8977ba)

**Comment by xmatthias** [comment]
there'll be some log errors eventually, especially if the upstream bot is gone (we can't really avoid these if we want to try and reconnect) - but that's not something i'm particularily concerned.

The errors you're getting however points to a bigger problem, most likely a network or docker config problem (i'd not know what in freqtrade would cause this).

It's pretty clear that the UI stops responding - it's all types of calls that are failing, which essentially also means that they're missing.


the network level "CONTENT_LENGTH_MISMATCH" errors are pretty strange - but also something i can't recreate, neither with a develop, system level install, nor through docker 2023.12, nor through remote calls.

These errors also seem to happen for all types of resources, both for api calls (ping) - as well as for regular resource calls (calls where the browser itself is loading data, like images).
The ping call in particular is pretty telling (it's such a small call that problems should be immediately visible) - maybe you can also share a screenshot of the network tab, which shows the content of the ping call ?

from the obfuscated IP, i assume it's remote calls you're making? 
Maybe there's something between you and the remote host that's intercepting / modifying / doing whatever with these network calls?


Please try the same with localhost calls (essentially from the system you're logged in), trying to avoid problematic systems between you and your bot.

Also make sure that your browser doesn't have any plugins installed (plugins can sometimes intercept and modify requests, sometimes causing strange bugs) (private mode usually has all plugins disabled).

You might also wanna test this with different browsers to exclude  an installation / configuration problem with one particular browser ...

**Comment by lutyne** [comment]
> The ping call in particular is pretty telling (it's such a small call that problems should be immediately visible) - maybe you can also share a screenshot of the network tab, which shows the content of the ping call ?

![image](https://github.com/freqtrade/freqtrade/assets/71123821/7dd56fb1-cd3d-463f-a421-b57c8fd0a236)
This is actually the wrong picture after calling ```ping```, which will correctly return ```pong``` (these errors in the console are also returned) 

> Maybe there's something between you and the remote host that's intercepting / modifying / doing whatever with these network calls?

Yes, I am making calls remotely, and I cannot rule out whether it is a network problem, but all my operations are normal, except for the UI, which is more like a UI or other error than a network error.

> Please try the same with localhost calls (essentially from the system you're logged in), trying to avoid problematic systems between you and your bot.

I tried to use the w3m browser on Linux to access the local UI, but the result was that it could not be opened. When using curl, js must be used to take effect.

> You might also wanna test this with different browsers to exclude an installation / configuration problem with one particular browser ...

I also tried using different browsers: ```chrome``` and ```edge```, and also turned on incognito mode (without using plug-ins), but the situation was the same.

**Comment by xmatthias** [comment]
![image](https://github.com/freqtrade/freqtrade/assets/5024695/25706441-4e8b-4dc5-ac4d-9d13285a9d5e)

the ping error i mean is the one above - with "ERR_CONTENT_LENGTH_MISMATCH".


> Yes, I am making calls remotely, and I cannot rule out whether it is a network problem, but all my operations are normal, except for the UI, which is more like a UI or other error than a network error.

The UI can't be expected to work correctly if some of it's core files are failing to load (the .js files, for example).

---

Talking about the network - what exactly is your setup? simply exposed directly on the internet (which is against our recommendation)? 
some VPN/wireguard tunnel?

You could try to change the network route - maybe by using a different vpn or wireguard tunnel to exclude some environment-related issues (for example a network inspecting proxy on your host or whatever).

For simplicity, you might even try some ad-hock setup like this via a network tunnel:
`ssh <networkaddress> -L 8080:<networkaddress>:8080` - and then connect to `http://localhost:8080` on your actual host (you should also be able to configure this in putty somehow (search for LocalForward) if your actual pc is windows).
(it'll obviously only work for as long as the ssh connection is up and running).

> I also tried using different browsers: chrome and edge, and also turned on incognito mode (without using plug-ins), but the situation was the same.

This is good information - pointing to a network problem rather than a browser / plugin problem. 
It might also be some aggressive antivirus program - something / anything inspecting / modifying the network requests, anyway.

---

Based on the errors, this is not a problem we will be able to assist you with, other than a few suggestions on what you could try - but they'll revolve to either system or network problems.

For now, i'll treat this as a question, as everything points to network / environment related errors - but not something that freqtrade can solve for you.

**Comment by lutyne** [comment]
Thanks for the reply, I will troubleshoot the network problem
