### ISSUE TITLE
How to enter immediately instead of waiting for the next candle

### ISSUE THREAD

**Issue by chanwoood** [freqtrade/freqtrade#9699]
I know I can wait for the next candle to start buying when I write it this way, but I want to buy immediately when a certain condition is met. How should I write it?
```python
    dataframe.loc[condition , 'enter_long'] = 1
```

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Conditions are usually based on closed candles only (freqtrade only provides closed candles).
Signals that are not based on closed candles are very prone to repainting - which is not something you'll usually want.

If your strategy relies on data other than dataframe signals (like realtime data through dataprovider) - you'll have to set `process_only_new_candles` to false to have the populate_* methods called more often.
If your conditions rely on "dataframe only" signals though - this has no effect, as the dataframe will not contain data that's changing within a candle.

**Comment by chanwoood** [comment]
Yes, my strategy does not rely on "dataframe only", it will obtain the current real-time price by `self.dp.ticker(metadata['pair'])['last']`  ，Then when the real-time price meets the conditions, I want to enter immediately

**Comment by chanwoood** [comment]
> Please get used to filling out the issue template. Those who frequently omit the template may have their issues closed without comment. We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.
> 
> Filling out the template helps reduce our workload, and we greatly appreciate that.
> 
> Conditions are usually based on closed candles only (freqtrade only provides closed candles). Signals that are not based on closed candles are very prone to repainting - which is not something you'll usually want.
> 
> If your strategy relies on data other than dataframe signals (like realtime data through dataprovider) - you'll have to set `process_only_new_candles` to false to have the populate_* methods called more often. If your conditions rely on "dataframe only" signals though - this has no effect, as the dataframe will not contain data that's changing within a candle.

Yes, my strategy does not rely on "dataframe only", it will obtain the current real-time price by `self.dp.ticker(metadata['pair'])['last']`，Then when the real-time price meets some conditions, I want to enter immediately

**Comment by chanwoood** [comment]
Is there any way to enter immediately? Can you help me? Or reopen the issue. @xmatthias

**Comment by stash86** [comment]
Read his answer above. He already give you the answer to your question

**Comment by chanwoood** [comment]
I'm so sorry, I get it now.
