### ISSUE TITLE
confirm_trande_entry/exit is only executed for first and last orders

### ISSUE THREAD

**Issue by dnuno89** [freqtrade/freqtrade#9700]
## Describe your environment

 *Operating system: Windows 11
 *Python Version: 3.11.4
 *CCXT version: 4.1.98
 *Freqtrade Version: 2023.12

  
## Your question

In the documentation, both confirm_trade_entry and exit are inside "Bot order confirmation", but there are only methods for orders opening or closing a trade.
![image](https://github.com/freqtrade/freqtrade/assets/11979371/978c3727-63bf-4eda-9a5f-ae87c0f8333d)

Orders executed through adjust_trade_position do not pass through this confirmation process. It seems that custom_entry_price/exit_price do execute for each order as I understand in the documentation, but they do not provide means to cancel the order.

I have a slippage abort implemented in confirm_trade_entry() which doesn't execute for DCA orders. Is there another method to implement this for all orders?

Thanks

**Comment by xmatthias** [comment]
Aborts only really make sense if it's "kinda" uncontrolled - in the sense of from a dataframe signal.

`adjust_trade_position()` is a callback already - if you'd rather not place the order - simply don't return values that cause an adjustment order.
