### ISSUE TITLE
Second telegram bot is not responding?

### ISSUE THREAD

**Issue by hailuu684** [freqtrade/freqtrade#9701]
## Describe your environment

* Operating system: Ubuntu 20.04
* Python Version: 3.10 (python -V)
* CCXT version: _____ (pip freeze | grep ccxt)
* Freqtrade Version: 2023.12(freqtrade -V or docker compose run --rm freqtrade -V for Freqtrade running in docker)
  
## Your question
Hello everyone,
I tried to create 2 different telegram bots to run in dry mode. I read the document about running multiple instances. The first bot I run was okay, and it works perfectly. Then I wanted to run a different bot in a different terminal which means I ran the second bot after the first bot. However, the 2nd bot seems not responding.

This is the docker-compose.yml file:

```
---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
  

  freqtrade_alert:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade_alert
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8081:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
        --logfile /freqtrade/user_data/logs/freqtrade_alert.log
        --db-url sqlite:////freqtrade/user_data/tradesv3_freqtrade_alert.dryrun.sqlite
        --config /home/luu/projects/freqtrade/ft_userdata/user_data/bot_alert.json
        --strategy ThreeSMAStrategy
```

The first bot I ran there were no instance freqtrade_alert, I wanted a 2nd bot then I added instance freqtrade_alert, then I use this command to run

`sudo docker-compose run --rm freqtrade_alert trade -s ThreeSMAStrategy -c ./user_data/bot_alert.json --db-url sqlite:///user_data/tradesv3-bot-alert.sqlite
`

However, in the terminal I got only until this information and that's it:

```
...
2024-01-19 10:02:03,900 - uvicorn.error - INFO - Waiting for application shutdown.
2024-01-19 10:02:03,900 - uvicorn.error - INFO - Application shutdown complete.
2024-01-19 10:02:04,070 - telegram.ext.Application - INFO - Application started
```

I think after that there should be like sending rpc messages.

Also, in the telegram bot, there is only message: `Status: starting trader ...`, I think if the bot works, then after this there will be a warning: dry-run mode is running.

Do you think because of running later like this causing this problem?

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
well `2024-01-19 10:02:03,900 - uvicorn.error - INFO - Waiting for application shutdown.` suggests that the bot is shutting down ... not starting up.

Also, you shouldn't use docker with sudo (add your user to the docker group instead).
For a "trading" bot - you shouldn't use `run --rm` either - that's a command for one-off commands - not to actually start a bot (this way, it will not have ports exposed, so the UI will not be reachable).

The correct way is a simple `docker compose up [-d]` - which will check on the first bot (eventually restart / recreate it) - and start the 2nd service in the compose file.
you can also use `docker compose up freqtrade_alert` to leave the first bot untouched.

For more - the log is too truncated, sorry.

**Comment by hailuu684** [comment]
> well `2024-01-19 10:02:03,900 - uvicorn.error - INFO - Waiting for application shutdown.` suggests that the bot is shutting down ... not starting up.
> 
> Also, you shouldn't use docker with sudo (add your user to the docker group instead). For a "trading" bot - you shouldn't use `run --rm` either - that's a command for one-off commands - not to actually start a bot (this way, it will not have ports exposed, so the UI will not be reachable).
> 
> The correct way is a simple `docker compose up [-d]` - which will check on the first bot (eventually restart / recreate it) - and start the 2nd service in the compose file. you can also use `docker compose up freqtrade_alert` to leave the first bot untouched.
> 
> For more - the log is too truncated, sorry.

Thank you for your quick reply, I tried `docker-compose up -d `, it showed me 

```
Creating freqtrade_alert ... done
Creating freqtrade       ... done
```
Then I run `docker-compose run freqtrade trade -s StochRSIBot -c ./user_data/dry_run.json`. It is okay for the first bot.
Then I run `docker-compose run freqtrade_alert trade -s ThreeSMMA-c ./user_data/bot_alert.json`. The second bot doesn't work.

Or I misunderstood you on how to run 2 services simultaneously. Could you please show me more?

Also, I think in the live trading mode, I should use `docker-compose start`?

**Comment by hailuu684** [comment]
> well `2024-01-19 10:02:03,900 - uvicorn.error - INFO - Waiting for application shutdown.` suggests that the bot is shutting down ... not starting up.
> 
> Also, you shouldn't use docker with sudo (add your user to the docker group instead). For a "trading" bot - you shouldn't use `run --rm` either - that's a command for one-off commands - not to actually start a bot (this way, it will not have ports exposed, so the UI will not be reachable).
> 
> The correct way is a simple `docker compose up [-d]` - which will check on the first bot (eventually restart / recreate it) - and start the 2nd service in the compose file. you can also use `docker compose up freqtrade_alert` to leave the first bot untouched.
> 
> For more - the log is too truncated, sorry.

And this is the log when I run the 2nd bot

─
```
2024-01-19 14:18:48,539 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0                                                                    [609/1935]
2024-01-19 14:18:48,539 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-01-19 14:18:48,539 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-01-19 14:18:48,539 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-01-19 14:18:48,539 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-01-19 14:18:48,539 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 20
2024-01-19 14:18:48,539 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-01-19 14:18:48,541 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-01-19 14:18:48,541 - freqtrade.exchange.exchange - INFO - Using CCXT 4.1.98
2024-01-19 14:18:48,551 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2024-01-19 14:18:53,254 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2024-01-19 14:18:53,363 - freqtrade.wallets - INFO - Wallets synced.
2024-01-19 14:18:53,371 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/freqtrade/freqtrade/plugins/pairlist/VolumePairList.py'...
2024-01-19 14:18:53,595 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.api_server                                                                                               [593/1935]
2024-01-19 14:18:53,698 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forceexit', 'forcese
ll', 'fx'], ['forcebuy', 'forcelong'], ['forceshort'], ['reload_trade'], ['trades'], ['delete'], ['cancel_open_order', 'coo'], ['performance'], ['buys', 'entries'], ['exits', 'sells'], ['mi
x_tags'], ['stats'], ['daily'], ['weekly'], ['monthly'], ['count'], ['locks'], ['delete_locks', 'unlock'], ['reload_conf', 'reload_config'], ['show_conf', 'show_config'], ['stopbuy', 'stope
ntry'], ['whitelist'], ['blacklist'], ['bl_delete', 'blacklist_delete'], ['logs'], ['edge'], ['health'], ['help'], ['version'], ['marketdir'], ['order']]
2024-01-19 14:18:53,824 - freqtrade.rpc.api_server.webserver - INFO - Starting HTTP Server at 128.0.0.1:8080
2024-01-19 14:18:53,824 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.
2024-01-19 14:18:53,830 - uvicorn.error - INFO - Started server process [1]
2024-01-19 14:18:53,830 - uvicorn.error - INFO - Waiting for application startup.
2024-01-19 14:18:53,830 - uvicorn.error - INFO - Application startup complete.
2024-01-19 14:18:53,831 - uvicorn.error - ERROR - [Errno 99] error while attempting to bind on address ('128.0.0.1', 8080): cannot assign requested address
2024-01-19 14:18:53,831 - uvicorn.error - INFO - Waiting for application shutdown.
2024-01-19 14:18:53,831 - uvicorn.error - INFO - Application shutdown complete.
2024-01-19 14:18:53,993 - telegram.ext.Application - INFO - Application started
```

**Comment by xmatthias** [comment]
when you run `docker compose up` - you're already starting the bot (you can see logs via `docker compose logs <servicename>`).
running `docker-compose run ...` again will start ANOTHER bot - which will most likely conflict with your initial bot (the 2 running  via docker-compose up already).

Your problem seems to be the address - 128.0.0.1 is NOT a localhost address - so you can't bind to it. please change listen_ip_address to 127.0.0.1 ... then it shouldn't shutdown immediately again.

**Comment by hailuu684** [comment]
> docker compose logs

I see. The command docker-compose up actually works, but in the 2nd service, it say file config not found, but it is there. I am not sure why is that?

```
freqtrade.exceptions.OperationalException: Config file "/home/luu/projects/freqtrade/ft_userdata/user_data/bot_alert.json" not found! Please create a config file or che
ck whether it exists.
```
I ran the command `os.path.isfile( "/home/luu/projects/freqtrade/ft_userdata/user_data/bot_alert.json")`, it returns True.

**Comment by hailuu684** [comment]
Somehow I ran this command `docker-compose run freqtrade_alert trade --strategy ThreeSMAStrategy -c ./user_data/bot_alert.json --db-url sqlite:////freqtrade/user_data/tradesv3_freqtrade_alert.dryrun.sqlite` and I deleted api_server in the config file, it works. I deleted it because I run the code on the remote machine and now I just wanted to test on telegram bots.

Thank you very much for your time.

**Comment by xmatthias** [comment]
> I ran the command os.path.isfile( "/home/luu/projects/freqtrade/ft_userdata/user_data/bot_alert.json"), it returns True.

This path is on your host - in the docker container, the path will be different depending on the volume mounted - usually should translate to `/freqtrade/user_data/bot_alert.json` - assuming you didn't do something completely off.


When using docker, i'd strongly suggest to get a bit familiar with how it works under the hood. It'll save you a lot of troubles ...

**Comment by hailuu684** [comment]
> > I ran the command os.path.isfile( "/home/luu/projects/freqtrade/ft_userdata/user_data/bot_alert.json"), it returns True.
> 
> This path is on your host - in the docker container, the path will be different depending on the volume mounted - usually should translate to `/freqtrade/user_data/bot_alert.json` - assuming you didn't do something completely off.
> 
> When using docker, i'd strongly suggest to get a bit familiar with how it works under the hood. It'll save you a lot of troubles ...

Yeah you are right, I will try it out carefully. Thank you for your suggestion
