### ISSUE TITLE
about how much stake to allocate for buying assets

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9702]
## Describe your environment

  * Operating system: ubuntu 20.4
  * Python Version: 3.8.10
  * CCXT version: 4.1.98
  * Freqtrade Version: 2023.12
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

My configuration is set as follows:
```
"max_open_trades": 10,
"stake_amount" : "unlimited",
"tradable_balance_ratio": 0.99,
```

So by default, each trade uses 9.9% of the available balance for buying assets.

Could you please let me know if it's possible to implement the following functionality in the strategy file:

Under normal circumstances, use the default parameters, but in a specific situation, set the stake amount for buying assets to 20%, which would be 1.98% (20% * 9.9%).

Alternatively, in specific situations, allocate a fixed amount for buying assets, such as buying 300 USDT worth of BTC.

Thank you.

**Comment by froggleston** [comment]
Please always check the docs before raising issues. You can use custom stake size management features in your strategy: https://www.freqtrade.io/en/stable/strategy-callbacks/#stake-size-management

**Comment by WinPoss** [comment]
In my example, it seems like when `current_candle['fastk_rsi_1h'] > current_candle['fastd_rsi_1h']`, `return 100` means buying 100USDT worth of assets, which is the trading unit I use. Right?

```
class AwesomeStrategy(IStrategy):
    def custom_stake_amount(self, pair: str, current_time: datetime, current_rate: float,
                            proposed_stake: float, min_stake: Optional[float], max_stake: float,
                            leverage: float, entry_tag: Optional[str], side: str,
                            **kwargs) -> float:

        dataframe, _ = self.dp.get_analyzed_dataframe(pair=pair, timeframe=self.timeframe)
        current_candle = dataframe.iloc[-1].squeeze()

        if current_candle['fastk_rsi_1h'] > current_candle['fastd_rsi_1h']:
            return 100

        # Use default stake amount.
        return proposed_stake
```

**Comment by froggleston** [comment]
Yes, you return the stake size in your chosen stake currency.
