### ISSUE TITLE
Suggestion: Add a feature in freqtrade to delete all trade records with one click

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9710]
## Describe your environment
(if applicable)

  * Operating system: ubuntu 20.4
  * Python Version: 3.8.10
  * CCXT version: 4.1.98
  * Freqtrade Version: 2023.12

## Describe the enhancement
Add a feature in freqtrade to delete all trade records with one click.
`/delete all`

## Explain the enhancement you would like
Details: By typing `/delete all` in Telegram, all trade records can be deleted.

Reason: Sometimes, when we are doing simulated trading and updating our strategies, we need to analyze data based on the new strategy. If the old strategy has already been simulated hundreds of times, it becomes a laborious task to delete them one by one using `/delete id `command.

**Comment by stash86** [comment]
You can just delete the old database using 1 line command before you start the bot on new strategy.

`/delete all` command is dangerous because you will lose all data with no way to recover it, unless you do manual routine backup.

**Comment by WinPoss** [comment]
```
tradesv3.sqlite
tradesv3.sqlite-shm
tradesv3.sqlite-wal
```

Manually delete these three data before starting the new strategy? Delete all three? Thank you.

**Comment by stash86** [comment]
yes
