### ISSUE TITLE
dependency conflicts

### ISSUE THREAD

**Issue by VerDoe** [freqtrade/freqtrade#9728]
Operating system: Debian 6.1.67-1
Python Version: Python 3.11.2
CCXT version: ccxt==4.1.98
Freqtrade Version: freqtrade 2023.12

  1. (.venv) ... pip list |grep prom
     prompt-toolkit             3.0.36
  2.(.venv) ... pip install -r requirements-hyperopt.txt
     ...
     Requirement already satisfied: prompt-toolkit==3.0.36 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 50)) (3.0.36)
     ...
  3. (.venv) ... pip install ipykernel
      ...
      Installing collected packages: prompt-toolkit
      Attempting uninstall: prompt-toolkit
      Found existing installation: prompt-toolkit 3.0.36
      Uninstalling prompt-toolkit-3.0.36:
      Successfully uninstalled prompt-toolkit-3.0.36
      ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the 
     source of the following dependency conflicts.
     questionary 2.0.1 requires prompt_toolkit<=3.0.36,>=2.0, but you have prompt-toolkit 3.0.43 which is incompatible.
     Successfully installed prompt-toolkit-3.0.43
...
  4. (.venv) ... pip list |grep prom
     prompt-toolkit             3.0.43
5. (.venv) ... pip install -r requirements-hyperopt.txt
   Installing collected packages: prompt-toolkit
  Attempting uninstall: prompt-toolkit
    Found existing installation: prompt-toolkit 3.0.43
    Uninstalling prompt-toolkit-3.0.43:
      Successfully uninstalled prompt-toolkit-3.0.43
   ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 8.20.0 requires prompt-toolkit<3.1.0,>=3.0.41, but you have prompt-toolkit 3.0.36 which is incompatible.
Successfully installed prompt-toolkit-3.0.36

Hyperopt requires version 3.0.36 to work and the ipykernel version 3.0.43, see "Using virtual environment with system-wide Jupyter installation"

**Comment by froggleston** [comment]
Related to https://github.com/froggleston/freqtrade_analysis_notebook/pull/15. I would suggest trying to `pip uninstall jupyter ipykernel` and reinstalling before trying to install the hyperopt dependencies. You may also have to pin a specific ipykernel/jupyter version until the upstream conflict is resolved.

**Comment by xmatthias** [comment]
first off - it's a warning in reality (even though it says error) - which does result in a working environment anyway, at least in my experience.

you can pretty easily fix this by doing installs that require prompt-toolkit as well with ` prompt-toolkit==3.0.36` - so your install becomes `pip install ipython prompt-toolkit==3.0.36`.
This will have pip select a compatible ipython version.

The hard-pin on prompt-toolkit is not intentional, but a side-effect of an incompatibility with questionary - which pins on <=3.0.36.

**Comment by VerDoe** [comment]
This is the solution until the incompatibility is resolved.

pip install ipython prompt-toolkit==3.0.36
...
INFO: pip is looking at multiple versions of ipython to determine which version is compatible with other requirements. This could take a while.
Collecting ipython
  Downloading ipython-8.18.1-py3-none-any.whl.metadata (6.0 kB)
...

Installing collected packages: ipython
  Attempting uninstall: ipython
    Found existing installation: ipython 8.20.0
    Uninstalling ipython-8.20.0:
      Successfully uninstalled ipython-8.20.0
Successfully installed ipython-8.18.0

(.venv) ... pip install ipykernel
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in ./.venv/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel) (3.0.36)

Thank you!
