### ISSUE TITLE
Best way to hyper tune freqai params?

### ISSUE THREAD

**Issue by fridary** [freqtrade/freqtrade#9729]
* Operating system: Mac OS
  * Python Version: 3.11
  * CCXT version: 4.2.21
  * Freqtrade Version: 2023.12
  
I want to ask what's the best way to hyper tuning AI params like we do for algorithmic trading? For example, I need to find best params for this config params:
```
{
    "freqai": {
        "train_period_days": 15,
        "model_training_parameters": {
            "learning_rate": 0.01,
        }
    }
}
```
Let's take `CatboostRegressor`. For `model_training_parameters` I can make hyper tuning of CatBoostRegressor() with external lib like Optuna (https://optuna.org/), changing this function call in `**self.model_training_parameters`. Is it the best way or I can insert built-in freqtrade hyper tuning (https://www.freqtrade.io/en/stable/hyperopt/)?
How should I also be with `train_period_days`? Manually in fit() function change `train_data` by cropping it and then use built-in tuning in fit() with `IntParameter()`?

```python
class CatboostRegressor(BaseRegressionModel):
    def fit(self, data_dictionary: Dict, dk: FreqaiDataKitchen, **kwargs) -> Any:
        train_data = Pool(
            data=data_dictionary["train_features"],
            label=data_dictionary["train_labels"],
            weight=data_dictionary["train_weights"],
        )
        
        test_data = None
        init_model = self.get_init_model(dk.pair)

        model = CatBoostRegressor(
            allow_writing_files=True,
            train_dir=Path(dk.data_path),
            **self.model_training_parameters,
        )

        model.fit(X=train_data, eval_set=test_data, init_model=init_model,
                  log_cout=sys.stdout, log_cerr=sys.stderr)
```

**Comment by robcaulk** [comment]
Hello,

If you wish to hyperopt the regressor hyperparameters with optuna, you do so inside the fit() function you copy pasted here.

This means you can optimize any data in this fit() function, including the number of rows you feed to `model.fit()` inside the optuna optimize function. It is simply a matter of defining your objective function and defining your parameters.

```py
def objective(trial, X, y, weights, X_test, y_test, params):
    """Define the objective function"""

    window = trial.suggest_int('train_period_candles', 1152, 17280, step=2016)

    # Fit the model
    model = XGBRegressor(**params)
    X = X.tail(window)
    y = y.tail(window)
    weights = weights[-window:]
    model.fit(X, y, sample_weight=weights, eval_set=[(X_test, y_test)])
    y_pred = model.predict(X_test)

    error = sklearn.metrics.mean_squared_error(y_test, y_pred)

    return error
```

Cheers,

Rob
