### ISSUE TITLE
SortinoHyperoptLoss ignores 100% winrate strategies 

### ISSUE THREAD

**Issue by keithorange** [freqtrade/freqtrade#9731]
Description:
Problem

The default SortinoHyperOptLoss implementation in Freqtrade has a significant issue when dealing with strategies that yield a 100% win rate (i.e., no losses). Currently, such scenarios result in a Sortino ratio calculation error, leading to a loss value of 100. This is problematic as it effectively filters out all winning strategies from the hyperoptimization process, preventing the learning algorithm from considering potentially profitable strategies.
Proposed Solution

A simple yet effective solution is proposed to address this issue. The idea is to assume a minimal loss in scenarios where no actual losses are recorded. This approach allows for a more realistic and continuous assessment of the strategy's performance, even in cases of high win rates.

The following code snippet provides the implementation details of this solution:

``from datetime import datetime
from pandas import DataFrame
import numpy as np

from freqtrade.constants import Config
from freqtrade.optimize.hyperopt import IHyperOptLoss

class BetterSortinoHyperOptLoss(IHyperOptLoss):
    """
    Defines the loss function for hyperopt.

    This implementation uses the modified Sortino Ratio calculation, which can handle scenarios
    with no losses by assuming a minimal loss.
    """

    @staticmethod
    def calculate_modified_sortino(trades: DataFrame, min_date: datetime, max_date: datetime,
                                   starting_balance: float) -> float:
        """
        Calculate sortino
        :param trades: DataFrame containing trades (requires columns profit_abs)
        :return: sortino
        """
        if (len(trades) == 0) or (min_date is None) or (max_date is None) or (min_date == max_date):
            return 0

        total_profit = trades['profit_abs'] / starting_balance
        days_period = max(1, (max_date - min_date).days)

        expected_returns_mean = total_profit.sum() / days_period

        total_losses = trades.loc[trades['profit_abs'] < 0, 'profit_abs'].sum()
        MIN_DOWN_STDEV = 0.0001
        if total_losses <= 0:
            # If there are no losses, assume a minimal loss of 1% to avoid division by zero
            down_stdev = MIN_DOWN_STDEV
        else:
            down_stdev = np.std(trades.loc[trades['profit_abs'] <
                                0, 'profit_abs'] / starting_balance) + MIN_DOWN_STDEV

        if np.isnan(down_stdev) or down_stdev == 0:
            # Define high (negative) sortino ratio to be clear that this is NOT optimal.
            return -100
        else:
            sortino_ratio = expected_returns_mean / down_stdev * np.sqrt(365)

        # print(expected_returns_mean, down_stdev, sortino_ratio)
        return sortino_ratio

    @staticmethod
    def hyperopt_loss_function(results: DataFrame, trade_count: int,
                               min_date: datetime, max_date: datetime,
                               config: Config, *args, **kwargs) -> float:
        """
        Objective function, returns a smaller number for more optimal results.

        Uses the modified Sortino Ratio calculation to handle scenarios with no losses.
        If there are no losses, a minimal loss is assumed to calculate the Sortino Ratio.
        """
        starting_balance = config['dry_run_wallet']
        sortino_ratio = BetterSortinoHyperOptLoss.calculate_modified_sortino(
            results, min_date, max_date, starting_balance)

        # print(f"Results: {results}\n")
        # print(f"Config: {config}")

        # Invert the Sortino ratio to align with HyperOpt's minimization approach
        # A higher Sortino ratio is better, so we return its negative
        return -sortino_ratio
```

Implementing this solution would ensure that strategies with a 100% win rate are properly evaluated and included in the hyperoptimization process. This would enhance the overall effectiveness of the hyperoptimization in Freqtrade, allowing for a more comprehensive and realistic assessment of strategy performance.

Original BROKEN sortino
```class SortinoHyperOptLoss(IHyperOptLoss):
    """
    Defines the loss function for hyperopt.

    This implementation uses the Sortino Ratio calculation.
    """

    @staticmethod
    def hyperopt_loss_function(results: DataFrame, trade_count: int,
                               min_date: datetime, max_date: datetime,
                               config: Config, *args, **kwargs) -> float:
        """
        Objective function, returns smaller number for more optimal results.

        Uses Sortino Ratio calculation.
        """
        starting_balance = config['dry_run_wallet']
        sortino_ratio = calculate_sortino(results, min_date, max_date, starting_balance)
        # print(expected_returns_mean, down_stdev, sortino_ratio)
        return -sortino_ratio```

**Comment by stash86** [comment]
There is nothing broken. That is how Sortino calculation works.

https://www.investopedia.com/terms/s/sortinoratio.asp

If you don't like how the formula works, you are free to create your own modified hyperopt loss function. But we won't fix it because there is nothing to be fix. We implemented it as how it's intended.

And just friendly reminder, if you are using that BetterSortino for hyperopt, you might find cases where the bot will choose 1/0/0 epochs over 150/0/10 epochs for example.

**Comment by xmatthias** [comment]
With these modifications it's no longer a Sortino ratio - but "something" else.

As such - not an issue. COULD be an alternative hyperopt loss function - but then it should be 
* Not named Sortino - as that's not what it is any longer
* should be a Pull request
* should NOT use naming suggesting issues - while in reality simply providing an alternative method.
