### ISSUE TITLE
problem with downloading DATA, pairs configuration not work 

### ISSUE THREAD

**Issue by zhuangz-ma** [freqtrade/freqtrade#9732]
## Describe your environment

  * Operating system: __Windows__
  * Python Version: ___Docker__ (`python -V`)
  * CCXT version: __4.1.98___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _2023.12___ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

I am an old user of Freqtrade. Recently I moved my work to a new PC but freqtrade cannot download data anymore.

COMMAND: 

docker compose run --rm freqtrade download-data --exchange binance --pairs ETH/USDT XRP/USDT BTC/USDT

LOG: 
$ docker compose run --rm freqtrade download-data --exchange binance --pairs ETH/USDT XRP/USDT BTC/USDT
2024-01-26 03:44:28,059 - freqtrade - INFO - freqtrade 2023.12
2024-01-26 03:44:28,059 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2024-01-26 03:44:28,062 - freqtrade.loggers - INFO - Verbosity set to 0
2024-01-26 03:44:28,063 - freqtrade.configuration.configuration - INFO - Using exchange binance  
2024-01-26 03:44:28,147 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2024-01-26 03:44:28,149 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2024-01-26 03:44:28,149 - freqtrade.configuration.configuration - INFO - Using pairs ['ETH/USDT', 'XRP/USDT', 'BTC/USDT']
2024-01-26 03:44:28,150 - freqtrade.exchange.check_exchange - INFO - Checking exchange...        
2024-01-26 03:44:28,157 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2024-01-26 03:44:28,158 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-01-26 03:44:28,160 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-01-26 03:44:28,160 - freqtrade.exchange.exchange - INFO - Using CCXT 4.1.98
2024-01-26 03:44:28,160 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-01-26 03:44:28,167 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-01-26 03:44:28,174 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2024-01-26 03:44:28,174 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2024-01-26 03:44:28,175 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2024-01-26 03:44:35,193 - freqtrade.data.history.history_utils - INFO - About to download pairs: [], intervals: ['1m', '5m'] to /freqtrade/user_data/data/binance
 

As you can see, the pairs in configuration are identified. But no pairs show in the "About to download pairs" list. I also tried using configuration file. It doesn't work either with same issue.

Please give me a help, 
Thank you!

**Comment by stash86** [comment]
I assume you are on futures market. We change the pair naming format for futures.

https://www.freqtrade.io/en/stable/leverage/#pair-namings

**Comment by xmatthias** [comment]
> We change the pair naming format for futures.

Small correction on this - ccxt aligned how futures are named on binance.

**Comment by zhuangz-ma** [comment]
> I assume you are on futures market. We change the pair naming format for futures.
> 
> https://www.freqtrade.io/en/stable/leverage/#pair-namings

futures data work well. Spot market doesn't work. I am working on spot market. Does spot market have different name format with ETH/USDT?

**Comment by stash86** [comment]
check the stake currency you set in config.json and make sure you set the stake to USDT

**Comment by zhuangz-ma** [comment]
Stake currency in config.json is USDT for sure. I am wondering even I use arguments like --pairs, it still doesn't work.

**Comment by stash86** [comment]
paste your config.json here, remove any sensitive info

**Comment by zhuangz-ma** [comment]
{
      "max_open_trades": 3,
      "stake_currency": "USDT",
      "stake_amount": 0.05,
      "tradable_balance_ratio": 0.99,
      "fiat_display_currency": "USD",
      "timeframe": "5m",
      "dry_run": true,
      "cancel_open_orders_on_exit": false,
      "unfilledtimeout": {
          "entry": 10,
          "exit": 10,
          "exit_timeout_count": 0,
          "unit": "minutes"
      },
      "entry_pricing": {
          "price_side": "same",
          "use_order_book": true,
          "order_book_top": 1,
          "price_last_balance": 0.0,
          "check_depth_of_market": {
              "enabled": false,
              "bids_to_ask_delta": 1
          }
      },
      "exit_pricing": {
          "price_side": "same",
          "use_order_book": true,
          "order_book_top": 1
      },
      "exchange": {
          "name": "binance",
          "ccxt_config": {},
          "ccxt_async_config": {
          },
          "pair_whitelist": [
              "ETH/USDT:USDT"
          ],
          "pair_blacklist": [
              "BNB/.*"
          ]
      },
      "pairlists": [
          {"method": "StaticPairList"}
      ],
      "telegram": {
          "enabled": false,
          "token": "your_telegram_token",
          "chat_id": "your_telegram_chat_id"
      },
      "api_server": {
          "enabled": false,
          "listen_ip_address": "127.0.0.1",
          "listen_port": 8080,
          "verbosity": "error",
          "jwt_secret_key": "somethingrandom",
          "CORS_origins": [],
          "username": "freqtrader",
          "password": "SuperSecurePassword"
      },
      "bot_name": "freqtrade",
      "initial_state": "running",
      "force_entry_enable": false,
      "internals": {
          "process_throttle_secs": 5
      }
  }

**Comment by zhuangz-ma** [comment]
I just figured it out. The problem is "trading mode", if I use future, spot market data are not downloadable. Thank you @stash86 !

**Comment by chenenyu** [comment]
> I just figured it out. The problem is "trading mode", if I use future, spot market data are not downloadable. Thank you @stash86 !

After several hours of struggle, I finally resolved the issue. How I wish I had seen this issue earlier! I believe this matter should be flagged in the documentation.

**Comment by xmatthias** [comment]
this matter IS flagged in the documentation (twice), both [here](https://www.freqtrade.io/en/stable/bot-basics/#pair-naming) and [here](https://www.freqtrade.io/en/stable/leverage/#pair-namings).

I really can't help if people FAIL to read the documentation.

**Comment by zhuangz-ma** [comment]
I think this matter mentioned by me and @chenenyu  is not about naming convention.  Data downloading script with specified pairs\exchanges\timeframes should not be tied to [trading mode] in the configuration file.
 
Firstly, the purpose of this script is data retrieval, not TRADING. It seems unnecessary to have the users consider the trading mode in the configuration file.

Secondly, the trading mode can be easily inferred through naming conventions. Anyone reviewing the doc will recognize a pair formatted like BTC/USDT:USDT is clearly associated with the future market. Is there any room for confusion here? While I acknowledge that the naming convention aligns with the ccxt library, which is acceptable, I FAIL to see the need to set trading mode when doing data retrieving.

> this matter IS flagged in the documentation (twice), both [here](https://www.freqtrade.io/en/stable/bot-basics/#pair-naming) and [here](https://www.freqtrade.io/en/stable/leverage/#pair-namings).
> 
> I really can't help if people FAIL to read the documentation.

**Comment by xmatthias** [comment]
>  I FAIL to see the need to set trading mode when doing data retrieving.

Depending on how the ccxt object is initialized (for spot or futures markets) , you may or may not get correct data when using futures naming (this is dependant on the exchange).

So while for one exchange a mixed apporach MAY - it may simply fail for other exchanges, or worse yet, return the WRONG data (you specify BTC/USDT:USDT - but you get BTC/USDT data instead).

This (cross-compatibility of a spot ccxt object with future markets) is something neither we (nor ccxt) tests for - so cannot be relied uppon.
