### ISSUE TITLE
Store informative pairs in config

### ISSUE THREAD

**Issue by woutrbe** [freqtrade/freqtrade#9748]
## Describe your environment

  * Operating system: MacOS 14.1.2
  * Python Version: 3.9.16
  * CCXT version: N/A
  * Freqtrade Version: 2023.12
  
## Your question

In regards to getting informative pairs, I understand this can be done with the `informative_pairs` method. However in all the the examples, the pairs seem to be hard coded. 

I have a scenario where the informative pair is dependent on whatever pair I have whitelisted. As an example, for `XRP/USDT`, I want the informative pair to be `ETH/USDT`.
I therefore would like to be able to define this in the configuration file, instead of hard coding this in the strategy.

What would be the best place to do this? Is adding a new dict inside the config and then reading it with `self.config["informative_pair"]` an acceptable way?

```
{
   ... config
   {
       "informative_pair": {
           "XRP/USDT": "ETH/USDT"
       }
   }
}
```

**Comment by xmatthias** [comment]
well in the end, what you want is a simple pair mapping (pairA -> pairB).
Where you do it is really irrelevant - however I'd suggest to keep this all in the strategy - as i see this as something strongly tied to your strategy - not to the configuration.

**In theory**, you can do it via the configuration as well - but arbitrary settings in the configuration are not supported - therefore there won't be a guarantee this will continue to work in the future (it can break without notice - as it's not a supported way - it's not something that needs deprecation or even communication).


A simple dictionary at the base of your strategy should suffice, which you can then use in your informative_pairs methods (as well as in the corresponding `self.dp.get_pair_dataframe()` call, obviously).

**Comment by woutrbe** [comment]
That's fair. I wasn't sure if metadata was accepted in the configuration or not. And thinking about it now, you're right that it's tied to the strategy anyway, so best to keep it there. Thanks!

**Comment by xmatthias** [comment]
"accepted" ... it's working (config is loaded as a dict, and currently keeps arbitrary keys) - but that's behavior caused by implementation detail (because it's a dict) - not something intentionally supported - which makes it dangerous to use (there's no tests for it - it's not something we're actively trying to support).
