### ISSUE TITLE
Custom stoploss not working.

### ISSUE THREAD

**Issue by c7flat13** [freqtrade/freqtrade#9752]

**Comment by stash86** [comment]
Please remove your api key

**Comment by c7flat13** [comment]
> Please remove your api key

thanks. total noob here.

**Comment by xmatthias** [comment]
> Please remove your api key
@c7flat13 and make sure to revoke it immedaitely. While you've removed it from here - it'll still be available through the post history behind the "edited" button... 


---

well your settings are ... slightly conflicting.
your trailing stop will only trigger if it's within the first 300 minutes - beyond that, ROI will "win" (1% roi after that, vs. 1.5% trailing stop offset).

I'd also suggest to not mix regular trailing stop and custom-stop functionalities (as the custom-stop documentation also recommends) - the two settings will conflict - with the "tighter" one winning. It also doesn't really make sense if you think about "trailing_stop" functionality as a shortcut to a custom_stop functionality.

That's not a problem necessarily, but might be depending on the actual strategy behavior.
The same will most likely also apply to the custom stop functionality.

I'm not sure i'd trust the code to find a "buy candle" in that function (please use the [sample code from our documentation instead](https://www.freqtrade.io/en/latest/strategy-advanced/#dataframe-access)) - that "if" will only really be true if your entry happens to fall on a candle to the splitsecond - which is anything between unlikely and impossible in live (think 2024-01-01 07:00:00.000).

**Comment by Wenlong-Guo** [comment]
I also have the same issue with this strategy. It is the second-ranked strategy on https://freqst.com/. It can execute custom_stoploss during backtesting, but it does not execute during dry-run. I have not edit any modifications to this strategy. I hope to get some help. Thank you very much.

**Comment by froggleston** [comment]
This is a specific strategy development issue, not an issue with freqtrade's callback functions. I agree with xmatthias that you should implement a simpler custom_stoploss to understand how it works, preferably with one from the docs, and go from there.

**Comment by perkmeister** [comment]
This strategy has lookahead bias in the `pivot_points()` function which is not shown in the first post above. All bets are off how it performs in live or dry. Oh and freqst.com lists lots of strategies with lookahead bias, the top performers all suffer from it (they don't seem to know what lookahead bias is, even in their Telegram group).
