### ISSUE TITLE
Issue on stoploss on exchange

### ISSUE THREAD

**Issue by robotsmith** [freqtrade/freqtrade#9753]
## Describe your environment

  * Operating system: ____Ubuntu 22.04.1 LTS
  * Python Version: _____3.10
  * CCXT version: _____   4.2.25
  * Freqtrade Version: 2024.1
  
## The question

Hi there,
I'm not entirely sure if this is a bug or an error of mine but I get automatically emergency exit on stoploss on exchange. I can't figure out the issue alone, could you help me?

## CONF
Here is the configuration file for Binance.

>    "order_types": {
>         "entry": "limit",
>         "exit": "limit",
>         "emergency_exit": "market",
>         "force_entry": "market",
>         "force_exit": "market",
>         "stoploss": "limit",
>         "stoploss_on_exchange": true,
>         "stoploss_on_exchange_interval": 60,
> 	"stoploss_on_exchange_limit_ratio": 0.99
>     },
> 

## logs
Here is the log results

> 2024-01-31 20:27:36 INFO    freqtrade.persistence.trade_model - Found open trade: Trade(id=336, pair=CTSI/USDT, amount=270.00000000, is_short=False, leverage=1.0, open_rate=0.25380000, open_since=2024-01-31 06:50:32)
> 2024-01-31 20:27:36 INFO    freqtrade.freqtradebot - Updating 0 open orders.
> 2024-01-31 20:28:16 ERROR   freqtrade.freqtradebot - Unable to place a stoploss order on exchange. Could not create stop_loss_limit sell order on market CTSI/USDT. Tried to sell amount 270.0 at rate 0.0026 with stop-price 0.0026. Message: binance {"code":-1013,"msg":"Filter failure: PERCENT_PRICE_BY_SIDE"}
> 2024-01-31 20:28:16 WARNING freqtrade.freqtradebot - Exiting the trade forcefully

Maybe something in the strategy? I don't use the price adjustement feature...
I'm sure it is a stupid mistake, since the selling rate is 100x higher that it should...Any ideas?

Thanks a lot!!

**Comment by xmatthias** [comment]
What's the actual stoploss for this trade? (what does the strategy assign as stoploss?)

from the resulting price, it looks like it's something around 99% or so - which means a stop would be placed at "price * (1 - 0.99)" - which is usually way too low for the exchange to allow for order placement (it's also pointless to use stoploss on exchange with such a stoploss - as you're broke before the stoploss actually triggers.

**Comment by robotsmith** [comment]
Hi,
Wow...efficient ^^
Yes that was exactly this issue... It was of course the stoploss at 99%.
I didn't expect this origin.

Thanks a lot!!
