### ISSUE TITLE
 Even though it is version 24.01, the Backtest tab is not visible in FreqUI.

### ISSUE THREAD

**Issue by thkwon9474** [freqtrade/freqtrade#9754]
Operating system: Ubuntu 22.04.2 LTS(docker)
Python Version: python 3.11.7
CCXT version: 4.0.71
Freqtrade Version: freqtrade 2024.01
  
## Your question

Hello Team,

First of all, I would like to express my sincere gratitude for providing a good platform.
I am always having a good experience thanks to you.

I am currently using Freqtrade through a docker image.
The backtesting function has been added to FreqUI in this and the previous update, and I went into FreqUI to check it, and it is configured as follows.

![image](https://github.com/freqtrade/freqtrade/assets/123524953/2501db06-f89c-47c0-979c-709632659652)

There is no item related to the backtesting function in the Settings,
If you enter 127.0.0.1:8080/backtest at will, you can access it.

I've searched through previously reported inquiries, but couldn't find a solution, so I'm asking.
Could you help me with what's wrong?

**Comment by stash86** [comment]
https://www.freqtrade.io/en/latest/utils/#webserver-mode

**Comment by xmatthias** [comment]
You can't use backtesting unless the bot is in webserver mode.

even though you might be able to access that url directly - it'll be non-functional - and the bot will refuse requests to start a backtest.
