### ISSUE TITLE
How to Pause New Buy Orders in Code

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9756]
## Describe your environment

  * Operating system: ubuntu 20.4
  * Python Version: 3.8.10
  * CCXT version: 4.1.98
  * Freqtrade Version: 2023.12
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

I have set `"max_open_trades": 10,` in the configuration file. However, I want to pause new buy orders after purchasing 4 assets until all 4 of the already purchased assets become profitable. Only then should I proceed to buy the remaining 6 assets.

I couldn't find any relevant functions in the [Strategy Callbacks](https://www.freqtrade.io/en/stable/strategy-callbacks/). Is there an elegant way to help me achieve this goal?

Can I use something similar to the following in the `populate_indicators `function?

```
from freqtrade.persistence import Trade
# ...
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
    open_trades = Trade.get_open_trade_count()
    if open_trades >= 4:
        return dataframe
    ...
```

Thank you.

**Comment by xmatthias** [comment]
well you can to some degree (limited to live) - but it won't work for backtesting.

instead, you can use the [`confirm_trade_entry()`](https://www.freqtrade.io/en/stable/strategy-callbacks/#trade-entry-buy-order-confirmation) callback - which will work in both live and backtesting.

**Comment by WinPoss** [comment]
If I use `confirm_trade_entry()`, is it like this?
 
```
 def confirm_trade_entry(self, pair: str, order_type: str, amount: float, rate: float,
                            time_in_force: str, current_time: datetime, entry_tag: Optional[str],
                            side: str, **kwargs) -> bool:
    open_trades = Trade.get_open_trade_count()
    if open_trades >= 4:
        return False
```

**Comment by xmatthias** [comment]
that'll never allow more than 4 open trades at a time (independent of their profit / loss) ... but yes, essentially.


A bit of modifications to filter on profitable trades only should get you pretty far (use [`Trade.get_trades_proxy()`](https://www.freqtrade.io/en/stable/trade-object/#get_trades_proxy))

**Comment by WinPoss** [comment]
ok, thanks for your idea
