### ISSUE TITLE
Is it possible to handle-execute list of orders-signals with freqtrade while tp price, entry_price, and sl price is known?

### ISSUE THREAD

**Issue by elite-trader110** [freqtrade/freqtrade#9757]
## Describe your environment

  * Operating system: ____ Windows
  * Python Version: _____ 3.9.0
  * CCXT version: _____ 4.1.74
  * Freqtrade Version: ____2023.12
  
## Your question
I have a list of orders, single order have following attributes (pair, signal time-the time which order is valid after, entry price: the price that order should filled, take profit price, stoploss price). example order is :
pair: BTC/USDT
signal time: 1/2/2021  1:00:00 PM
entry time: - to be determined by freqtrade
entry price: 30179
stoploss price: 29741
take profit price: 30604
entry time is the time that order filled after signal time so the entry time should be after signal time. (in case of backtesting)

I have a list of such orders (I will extract these orders-signals with some calculation based on live market for example my list contains 100 orders at a time and this list will be increase by time) and I want to know is there any way to use freqtrade to manage/execute these kind of orders instead of enter_long column way (or maybe how to use enter_long column for these type of orders)?
comment: I don't want to use limit orders because all of my staking amount will be locked untill entry time (it is possible that signal time and entry time has a lot of time difference) so I think I should monitor the current_rate and if the price delta from entry price is less than eg. 0.0001% after order executed, managing the exit and stoploss is easy to implement because tp and stop price is known. (I have done before)
![image](https://github.com/freqtrade/freqtrade/assets/144953975/33ec33a0-b627-4563-b3ea-b2b6bb9b474f)

Any comment, solution will be appreciated...

Thanks all the developers for the Great Freqtrade!

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Entries do only happen based on the `enter_long` / `enter_short` columns.

you can set `process_only_new_candles` to False - and get `populate_*` methods called on every iteration (by default, roughly every 5 seconds) (obviously, this won't work in backtesting, where you only get one call per candle).
You can use the  [dataprovider](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-dataprovider) to get live prices (usually through the orderbook call). These are however active network calls - which will wait for the result - and as a result, will slow down your bot loop.

There's nothing preventing you from setting a signal mid-candle based on "whatever" logic you think should apply.

There's however also several downsides to this - but it's up to you to decide if you can work with these
* as your signal is unstable - you will not reliably see entry signals (they appear / disappear mid-candle) on plots. 
* you can't really backtest this unless you have a reliable way to set the signals simulating the live logic "somehow".

All "exit" logic should be possible through [callbacks](https://www.freqtrade.io/en/stable/strategy-callbacks/) ...

In the end, all the logic is up to you to define - but it's not something freqtrade will prevent from implementing if you carefully look through the documentation.
