### ISSUE TITLE
Access FreqUI and JupyterLab from the internet

### ISSUE THREAD

**Issue by AliM1988** [freqtrade/freqtrade#9758]
## Describe your environment

  * Operating system: linux/amd64
  * Freqtrade Version: freqtrade docker-2024.2-dev-0bc5c876
  
## Your question
According previous question #9689 I can use freqtrade and jupyterlab together. It is docker-compose file (maybe useful to others):

```
---
version: '3'
services:
  freqtrade:
    # image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy

  ft_jupyterlab:
    build:
      context: .
      dockerfile: docker/Dockerfile.jupyter
    restart: unless-stopped
    container_name: ft_jupyterlab
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Default command used when running `docker compose up`
    command: >
      jupyter lab --port=8888 --ip 0.0.0.0 --allow-root --NotebookApp.token=''

```

I ran bot on a VPS, and I want to access FreqUI and JupyterLab from the internet. I have already installed Nginx. 
I modify nginx config as below:

```
server {
    listen 9000;
    server_name _;

    location / {
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

server {
    listen 7000;
    server_name _;

    location / {
        proxy_pass http://localhost:8888;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```

By navigate http://vps_ip:9000 or http://vps_ip:7000 from external host, just the title of "FreqUI" or "jupyterLab" shown. No any contents don't rendered in browser.

**Comment by xmatthias** [comment]
we do **strongly** recommend to NOT expose the API (or freqUI) directly to the internet without further protections (like a VPN, wireguard, SSH tunnel or very strickt IP filtering - maybe have a look at tailscale?) - which the documentation also warns about.

As such, i also don't really see us providing support in getting such a setup running. 

As a quick note to may need to have a look at - almost no VPS provider will have random ports (like 7000 or 9000) open - so most likely, firewall is one of the problems here.

**Comment by AliM1988** [comment]
I found the problem. In docker-compose file in sections port mapping, `127.0.0.1` must be removed. 

```
    ports:
      - "8080:8080"
```

```
    ports:
      - "8888:8888"
```

**Comment by xmatthias** [comment]
well that'll expose them directly - but nginx would not be necessary in that case.

**Comment by AliM1988** [comment]
Yes. JupyterLab and FreqUi is accessible through http://<vps_ip>:8888 and http://<vps_ip>:8080 (without Nginx reverse proxy), but still the way using Nginx (http://<vps_ip>:7000 and 9000) doesn't work. 
The log for JupyterLab is just this:

`[I 2024-02-06 06:18:07.626 ServerApp] 302 GET / (@172.27.0.1) 0.63ms`

Anyway, my problem is solved but I wonder why Nginx reverse proxy can't handle it correctly.
