### ISSUE TITLE
Range bars

### ISSUE THREAD

**Issue by milcs** [freqtrade/freqtrade#9772]
## Describe your environment
  * Operating system: Win10
  * Python Version: 3.12.1 (`python -V`)
  * CCXT version: 4.2.8 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.1-dev-8d72ee358 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question 1: Range Bars
Does freqtrade support using range bars, e.g. bars that are build from streaming tick data and building custom bars.
Use case. A bar is created each time a price low-high hits 1% of open dynamically. 

## Your question 2: External Signal
Can freqtrade be configured - linked to an external source such as TradingView webhook or mqtt to execute trades rather than running candle-strategy loop.
I would like to use freqtrade to execute the trades triggered by an external signal source.
So in this scenario. freqtrade would receive a buy-sell signal at any given time and execute it.

**Comment by froggleston** [comment]
1. yes, you can code up pretty much anything you want as its "just python", but it won't be backtestable and the main dataframe still needs to be OHLCV. Changing the fundamental data type (an OHLCV dataframe) would require large changes to the underlying code.
2. yes, use the REST API `forceenter` and `forceexit` commands: https://www.freqtrade.io/en/stable/rest-api/
