### ISSUE TITLE
Add a parameter to measure hold for a relatively short time

### ISSUE THREAD

**Issue by moinonin** [freqtrade/freqtrade#9775]
## Describe your environment
(if applicable)

  * Operating system: Linux Mint Ulya
  * Python Version: 3.10.12
  * CCXT version: 4.2.25
  * Freqtrade Version: 2024.1

## Describe the enhancement

It would be nice to know how good the buying is by adding a parameter to check how the bought assets could perform if you hold for a certain relatively short time rather than the entire backtest. For example if you hold for 8h, 20h or several days after buying. Without exiting with any of the methods, ROI, custom_exit or exit signal or even stoploss.

**Comment by stash86** [comment]
you can already do this using confirm_trade_exit callback. Check the duration of the trade there and do whatever you want to do with it.

Create several variations of the strategy with different holding time. Backtest them, compare the result.

**Comment by moinonin** [comment]
I assume you mean something like:
```
if current_time - timedelta(minutes=360) > trade.open_date_utc:
    return False
```
But there is no current_time in the said callback. Unless if it is possible to get the time the trade was to be exited like this:

```
if trade.close_date_utc - timedelta(minutes=360) > trade.open_date_utc:
    return False

```

Is that doable?

**Comment by stash86** [comment]
There is `current_time` in the callback.

https://www.freqtrade.io/en/latest/strategy-callbacks/#trade-exit-sell-order-confirmation

**Comment by moinonin** [comment]
Thank you @stash86 I had not seen the updated doc.
