### ISSUE TITLE
Some suggestions for backtesting function

### ISSUE THREAD

**Issue by AliM1988** [freqtrade/freqtrade#9778]
## Describe your environment
  * Operating system: linux/amd64
  * Freqtrade Version: freqtrade docker-2024.2-dev-e50fac34

## Describe the enhancement

I know when I set VolumePairList in config, I get error: `freqtrade - ERROR - VolumePairList not allowed for backtesting. Please use StaticPairList instead.` I have a question: When --pair argument is used, actually those pairs must be considered and it is same as StaticPairList . Why backtesting function doesn't check it? If --pair argument presents pairlist method can be handled or ignored by backtesting function. At the result no need to change config.

Also, I have another suggestion: If it's possible, add --days option to  backtesting function (lika as download-data) to make it more flexible to specify which days of data must be considered. (--days=-100 , can equal 100 days from beginning date of existing data).

**Comment by xmatthias** [comment]
To start with your second question - `--days=100` would be rather opaque.
is it the last 100 days  (`datetime.now()  - timedelta(days=100)`) - or is it `data_start + timedelta(days=100)` - or even `data_end - timedelta(days=100)`?
it's not clear - leading to mistakes and errors - hence not a good option.

---

For the first:
this is also a clarity point - if you specify `VolumePairlist` - you expect that to be used. even though you specify `--pairs` - that doesn't negate the expectation from the configuration.
As such - i think it's better to be clear that this pairlist is not going to be used.
unfortunately, our experience has shown that rarely anyone carefully reads the logs - so simply logging "detected --pairs - ignoring pairlist configuration" would not be seen by 99% of the users.
