### ISSUE TITLE
scripts/rest_api.py FtRestClient.forceexit tradeid param must be str while status trade_id is int

### ISSUE THREAD

**Issue by milcs** [freqtrade/freqtrade#9780]
## Describe your environment

  * Operating system: Win10
  * Python Version: 3.12.1 (`python -V`)
  * CCXT version: 4.2.8 (`pip freeze | grep ccxt` or **pip freeze | findstr /i ccxt for Windows**)
  * Freqtrade Version:  2024.1-dev-8d72ee358 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
```scripts/rest_api.py``` ```FtRestClient.forceexit``` **tradeid** param must be str while ```status``` **trade_id** as returned by ```FtRestClient.status()``` is an int.

**Is there a reason for inconsistency?**

```FtRestClient.forceexit(tradeid=1)``` silently fails.
Debuging ```FtRestClient._call``` reveals a status_code error 422 with:
```json
{"detail":[{"type":"string_type","loc":["body","tradeid"],"msg":"Input should be a valid string","input":2,"url":"https://errors.pydantic.dev/2
.5/v/string_type"}]}
```

```FtRestClient.forceexit(tradeid="1")``` works like a charm.

**Comment by stash86** [comment]
Because if you want to exit all open trades, you need to send `tradeid="all"`.

**Comment by xmatthias** [comment]
don't really see why this is a problem if i'm honest - the script is intended to be used from the cli - importing it to other scripts is neither officially supported (doesn't mean it won't work) - and probably also not a good idea (there's no actual tests for the scripts - and i also don't really consider them as "public api" apart from how you call the API, so this part might change anytime without actual mention in the docs).


passing `python scripts/rest_client.py forceexit 1` to the script will not have it as an integer - but as a string (all arguments are strings by default). while it could be parsed (optionally, as it could also be "all" that's passed in)- there's no real reason for that - as that's simply more work.

Now a fix for this - accepting a number in the model (and then converting it to string in the backend) - is pretty easy / straightforward.

**Comment by milcs** [comment]
Indeed, pretty easy, that is why I posted a question and not a bug.
I like this project a lot. Well done, sufficient documentation. 
Anything I try just works!
