### ISSUE TITLE
freqtrade new-config - is this the normal behavior?

### ISSUE THREAD

**Issue by gagna** [freqtrade/freqtrade#9790]
I installed freqtrade using Docker, followed the procedure, and everything seems to be working.

While experimenting with commands, I noticed that when running this command:
`freqtrade new-config --config backtesting_config.json`

The intention was to create an alternative config file to be used only for backtesting.

However, the backtesting_config.json file is created outside the `user_data` folder, which seems counterintuitive to me. Interestingly, when using the `freqtrade new-strategy` command, the strategy file is correctly created within the `user_data/strategies ` folder, along with all user files.

I resolved this issue by using the command in this way:
`freqtrade new-config --config user_data/backtesting_config.json`

I followed the instructions [here](https://www.freqtrade.io/en/stable/configuration/), but it doesn't seem to refer to this.

Am I wrong? Is this how it should work?

**Comment by xmatthias** [comment]
well the same behavior happens outside of docker ... the path is relative to the current working directory (which should not be the user_data directory).

The [docker quickstart](https://www.freqtrade.io/en/stable/docker_quickstart/#docker-quick-start) references this correctly for docker, though outside of docker, using `--config config.json` is not wrong - and one of the default locations freqtrade looks for configs (`user_data/config.json`, `config.json`) if no explicit configuration is given.
