### ISSUE TITLE
problem with frequi 4 different bot on same windows vps

### ISSUE THREAD

**Issue by simons1010** [freqtrade/freqtrade#9810]
hello

I am on a Windows 2019 server and run 4 different freqtade bots using this command :

freqtrade -c configA.json -s StrategyA --db-url sqlite:///strategyA.sqlite
freqtrade -c configB.json -s StrategyB --db-url sqlite:///strategyB.sqlite

I created 4 different config files with all the same settings but changed the UI port number and removed the telegram

the problem is when strategies are running normally
frequi does not work and does not show anything for 1 or 2 of strategies

I change the port in each config but for some strategies, it shows frequi and trades
and for some other strategies, it does not show anything (frequi loads in the browser without any data)

the only thing I changed in config files is the port number

  * Operating system: windows 2016 server
  * Python Version: 3.11
  * CCXT version: latest
  * Freqtrade Version: latest

**Comment by xmatthias** [comment]
it's pretty much ... entirely unclear how you've set up things.

Let's assume the ports configured are 8080 (the default) and 8081.

are you navigating to each respective UI (`http://localhost:8080` and `http://localhost:8081`) - or are you trying to add them to the same UI (in which case you'll need to have [CORS](https://www.freqtrade.io/en/stable/rest-api/#cors) configured correctly.

You can always look at the network tab of your browser to figure out where requests are going and what their error cause is - but the most likely reason is usually that the backend is simply unreachable (firewall / maybe the port was already occupied by some other program,...).

**Comment by simons1010** [comment]
yes, I follow this pattern
127.0.0.1:8080 main strategy
127.0.0.1:8081 second strategy
127.0.0.1:8082 third strategy
127.0.0.1:8083 fourth strategy

I am not using docker and only python on Windows VPS
I have tried to change the port number, but it is not working, and I open all this on separate tabs on my browser

**Comment by xmatthias** [comment]
Then most likely - it's either your windows firewall that's preventing you accessing it - or there's something already running on that port.
As mentioned above - try using the devtools of the browser to look at the responses - these usually contain error information. 

We can also assist you with this to some degree - if you're able to share these screenshots.
