### ISSUE TITLE
Issue with last candle on lower timeframes (5m, 15m, 30m)

### ISSUE THREAD

**Issue by vforv** [freqtrade/freqtrade#9812]
I am using binance default config.

Problem is that data lag for 5m 15m and 30m. For example in populate indicators I would expect to get last closed candle but it return candle before last. Ex. Interval 15m, current time: 15:27, last candle will be 15:00 instead of 15:15

I believe this can be issue if you pulling data via http from ccxt, solution may be to use socket to get last data.

**EDIT:** ccxt lib working fine with http request, I am able to get last closed candle, so it's probably some issue with freqtrade code.

Test code:

```
import ccxt
from datetime import datetime

# Initialize the exchange (e.g., Binance)
exchange = ccxt.binanceusdm({
    'enableRateLimit': True,  # Recommended to avoid being rate-limited
})

# Symbol and timeframe you're interested in
symbol = 'BTC/USDT'
timeframe = '15m'

# Fetch OHLCV data
ohlcv = exchange.fetch_ohlcv(symbol, timeframe)

# Get the last interval data
last_interval = ohlcv[-1]

# OHLCV format: [timestamp, open, high, low, close, volume]
timestamp = last_interval[0]
open_price = last_interval[1]
high_price = last_interval[2]
low_price = last_interval[3]
close_price = last_interval[4]
volume = last_interval[5]

# Convert timestamp to datetime (CCXT returns timestamp in milliseconds)
date_time = datetime.utcfromtimestamp(timestamp / 1000).strftime('%Y-%m-%d %H:%M:%S')

# Print the last interval data
print(f"Date & Time: {date_time}")
print(f"Open: {open_price}, High: {high_price}, Low: {low_price}, Close: {close_price}, Volume: {volume}")
```

**Comment by froggleston** [comment]
There is no lag - https://botacademy.ddns.net/2023/10/14/misconception-about-candles-timestamp/

**Comment by vforv** [comment]
There is a lag, pls check difference between my script and your system:

![Screenshot from 2024-02-13 18-51-19](https://github.com/freqtrade/freqtrade/assets/10942178/a93f6d50-159b-4d2e-a562-9c22a6f3f7a4)

![Screenshot from 2024-02-13 18-51-29](https://github.com/freqtrade/freqtrade/assets/10942178/849316e1-6a0b-4b1d-90e0-980aca41c00f)

As you can see last candle needs to be at 17:45:00 but freqtrade returns 17:30:00 which means trades will delay

I tested same thing on 1h interval and it works correctly!

**Comment by stash86** [comment]
What you got there from CCXT is the current open candle. FT purposely remove it because we are only working with closed candles. So fhere is no lag as far as we concerned
