### ISSUE TITLE
Telegram /stats not reload able

### ISSUE THREAD

**Issue by syco** [freqtrade/freqtrade#9816]
https://github.com/freqtrade/freqtrade/blob/d2b0dc2171798aac81fcf939ac697ee20121a049/freqtrade/rpc/telegram.py#L997C1-L997C54

Hi,
Any reason why the above is not reload able?
Thanks

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

I really don't see why it would be a must to have that - though you're more than welcome to submit a pr adding that if you think it's a must.
