### ISSUE TITLE
Problem with Objective Calculation for Best in Hyperopt

### ISSUE THREAD

**Issue by abbaselmas** [freqtrade/freqtrade#9819]
## Describe your environment

  * Operating system: Ubuntu 22.04.3 LTS
  * Python Version: Python 3.10.12
  * CCXT version: 4.2.42
  * Freqtrade Version: freqtrade 2024.2-dev-60b12c1d9
  * Before asking Try to reset everything, install whole freqtrade from scratch.
  * Loss function is: ProfitDrawDownHyperOptLoss with not changed (default) DRAWDOWN_MULT 
  * command: freqtrade hyperopt -c config.json -c proxy.json -c static-pairlist.json -c private.json -e 200 -j 50 --spaces buy --print-json -s abbas8 --hyperopt-loss ProfitDrawDownHyperOptLoss --print-all --analyze-per-epoch --timerange 20240101-20240210
  * no memory error no process kill everything works smooth
  
## Your question

When i try to hyperopt a bit much parameters, hyperopt results are not meaningful. If I reduce the hyperoptable parameters to 10 for example problem disappears. I dont wanna go over part by part. What am I doing wrong?

![image](https://github.com/freqtrade/freqtrade/assets/28142617/61416606-ef38-4604-b08a-826db5d96d3a)
it not getting better, it getting worse actually
![image](https://github.com/freqtrade/freqtrade/assets/28142617/c8bda104-122d-4bf6-994c-1f8fa80894fd)

On this run hyperoptable parameters are below btw.
![image](https://github.com/freqtrade/freqtrade/assets/28142617/3cfa39b2-1977-4b7c-9824-a492f2bb5f65)

**Comment by xmatthias** [comment]
Well that particular drawdown is combining profit with drawdown - giving each a different weight.

https://github.com/freqtrade/freqtrade/blob/60b12c1d9ecd19e8ed7ae6e559021c810c068c8c/freqtrade/optimize/hyperopt_loss/hyperopt_loss_profit_drawdown.py#L30

Sense / nonsense of objective values is a different topic - the only "real" meaning is that lower values are better (based on the objective formula). you can't compare the values with other loss functions - nor will they have much meaning outside of each particular hyperopt run.

---

Now obviously - with more parameters - your space increases.
To simplify this (a lot!):
If you search for the "lowest" point on a line (1d space) - it'll be easier than searching for it in a 3d space (the deepest valley).

Once you reach one such valley - it's often difficult to get out of (we start with 30 random points - but if you have a 100 dimensional space, that may still produce local minima the optimization fails to get out of.

---

You can play with the actual results quite easily ... and you'll notice that the combination / result is ... odd at best in some scenarios - as it doesn't really respect the sign of the values.

![image](https://github.com/freqtrade/freqtrade/assets/5024695/86053111-40a1-4445-b1f2-1937c5c95ac1)
If you look carefully - the strategy with loss would be preferred .. which is clearly not the way it should be).

(formula / usage taken from this comment): https://github.com/freqtrade/freqtrade/issues/9563#issuecomment-1863329274

In reality - i think the way this loss function combines the values is not ideal - and I'm more than happy to get a PR that sees it improved.
The alternative is to simply pick a different loss function - which there's plenty of - and all try to search for different "improvements".

**Comment by abbaselmas** [comment]
Thank you for your comprehensive explanations, I am enlightened!

In order not to stuck within localminima i am using multiple predetermined seeds. Running more than 200 epoch dont change much, as you stated in docs. However running HO multiple times, effect the 30 random starting point. I think exploration of this way is better.

I dont think im capable of a PR, but eager to test new loss functions.

thanks for freqtrade ^_^
