### ISSUE TITLE
Telegram: Preview at entry time

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#9825]
## Describe your environment
(if applicable)

  * Operating system: Windows Server 2022
  * Python Version: Current Miniconda (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

Just a small thing:

Looking at the Telegram overview for example on a smartphone, one no longer see the coin ticker name at entry time with version 2024.1
Only the trade number is visible, since the coin ticker is now re-arranged in the 2nd line. For me personally, the trade number is less relevant, than the coin ticker. 
As you look at the exit information, here the coin ticker is visible in the overview, followed by the trade number.

Earlier versions at entry time showed for example: Kraken (dry): Long DOT/USD (#19)

*Explain the enhancement you would like*

**Comment by xmatthias** [comment]
Attempting a new trade just now to have a look at the messages - i'm not sure i understand your point.

Yes, formatting changed slightly - with the pair name now moving to the 2nd line (where it finds more space - as futures trades usually caused line wrapping).

That's been done to improve readability - as it's now clearer what the message actually does (new trade, trade fill, position adjustment).
 

![image](https://github.com/freqtrade/freqtrade/assets/5024695/0c3e82bd-eb76-4313-89aa-dc4db41986ce)
![image](https://github.com/freqtrade/freqtrade/assets/5024695/248d7178-7e5c-4034-9ee5-aca065095458)

**Comment by myNextCoder** [comment]
I was talking about the only top line, we have, when all chats in Telegram are visible at the left. The information "filled" is good, but I was appreciating to see the coin ticker. If multiple bots are buying the same coin "at the same time", which was visible in the overview, this gave me important information about the behavior.

**Comment by xmatthias** [comment]
I understand what i mean - however the change has been made intentionally improve message clarity - which wasn't the case previously (it relied on implicit understanding of the difference beween "entered" - "entering" - and didn't include the information of "Position adjustment" at all.

As such - there's currently no plans to revert this change.

**Comment by myNextCoder** [comment]
Never ever revert. One thing, which can "improve" the information on this first Telegram line could be, to use for example two different blue icon-colors for entering, and finally filling the trade. In that case, you do no longer need to write "fill" in addition on the top line, so you may win some space in this upper line.

**Comment by xmatthias** [comment]
That's again implicit information which forces the user to KNOW what which color means - otherwise it's meaningless.

this will work if i write something for myself - but not if you write it for a wider audience.

**Comment by myNextCoder** [comment]
You are right, for most traders, your update might be good, my idea, because you have two icons on profit exit-time: Green and Rocket (two meanings)
