### ISSUE TITLE
Getting Open PnL

### ISSUE THREAD

**Issue by erhangunay** [freqtrade/freqtrade#9826]
## Describe your environment

  * Operating system: Docker 2024.1
  * Python Version: Docker 2024.1
  * CCXT version: Docker 2024.1
  * Freqtrade Version: Docker 2024.1
  
## Your question
Hello,

i know that it is possible to get overall closed profit by 
profit = Trade.get_total_closed_profit()

Is there a way to get the overall open profit? Reason I am asking is, whenever overall open profit reaches a certain level, I want to close all trades. So I need to be able to calculate it in the custom_exit function. If there is no available way to do it, I intend to use get trades proxy and write profit calculation formula and sum it for each open trade in the list, however i didnt want to reinvent the wheel if it already exists. 

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
That's not available, and will probably also not be added anytime soon as a shortcut.

Calculating open profit does require the current rate for each open trade ... which worst case, is an active call against the exchange each time - making your whole method rather slow.

While we do have some similar code in the rpc module (which you might want to take as inspiration) - but that's not available to the strategy - and doing that actively on every botloop will probably impact performance beyond being useful - as now your botloop performance reduces quite some.

**Comment by erhangunay** [comment]
What would be the most efficient way to fx all if open profit is x percent of total balance?

My problem is I have a good entry strategy but on exit I could not achieve something good so I open a lot of trades and want to exit all of them at a certain profit. Right now I do it via telegram manually :(

**Comment by erhangunay** [comment]
Or can i somehow access rpc module calculations from strategy by importing? Like calling what is already calculated

**Comment by xmatthias** [comment]
no, you can't import rpc modules into your strategy (well you can, but it will not work).

i doubt that closing all positions is a good approach - you should treat each position individually - and then eventually close them if THAT pair tells you to - not "all pairs combined reached X - so i'm scrapping everything").

**Comment by erhangunay** [comment]
Ok i admit that this is just desperation. Maybe I should just find a way in my strategy. Thanks for your time Matthias.

**Comment by epetros** [comment]
> Ok i admit that this is just desperation. Maybe I should just find a way in my strategy. Thanks for your time Matthias.

Hi,
I am also looking to implement this feature, Have you managed to make progress?

**Comment by epetros** [comment]
> That's not available, and will probably also not be added anytime soon as a shortcut.
> 
> Calculating open profit does require the current rate for each open trade ... which worst case, is an active call against the exchange each time - making your whole method rather slow.
> 
> While we do have some similar code in the rpc module (which you might want to take as inspiration) - but that's not available to the strategy - and doing that actively on every botloop will probably impact performance beyond being useful - as now your botloop performance reduces quite some.

If even with the drawbacks you mention, I would like to proceed, I'm thinking something like:

    def custom_exit(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float, current_profit: float, **kwargs) -> str:
        """
        Custom exit logic, checking if the cumulative profit of all open trades exceeds 3%.
        """

        # Fetch all open trades using get_trades_proxy for efficiency
        open_trades = Trade.get_trades_proxy(is_open=True)
        ........................
What would be the best way to access current_profit of each open_trade?

**Comment by xmatthias** [comment]
You can't unless you calculate it yourself (you'll also need to get rates for each open trade individually) - though it's available in each individual trade's callback.

All necessary tools are listed in the documentation, if it's read carefully. 
I do however not intend to provide further information - as i think this is an anti pattern - will slow your bot down beyond reason. 
Please consider such an approach unsupported.

**Comment by erhangunay** [comment]
No, i could not manage to find it..

**Comment by epetros** [comment]
> No, i could not manage to find it..

If you are willing to take the risk xmatthias mentioned, this has been working reasonably well for me:
```
class your_strategy(IStrategy):


    # Initialize the strategy
    def __init__(self, config: dict) -> None:
        super().__init__(config)
        # Initialize in-memory storage for trade profits
        self.open_trades_profit = {}
        # Initialize the flag to control when to close all trades
        self.close_all_trades_flag = False

    --------------------------------------------

    def confirm_trade_entry(self, pair: str, order_type: str, amount: float, rate: float,
                            time_in_force: str, current_time: datetime, entry_tag: Optional[str],
                            side: str, **kwargs) -> bool:
        """
        Override to ensure the difference between the number of long and short positions globally does not exceed the limit.
        """
        # Correctly fetch all open trades
        trades = Trade.get_trades_proxy(is_open=True)
        # Reset the flag if there are no open trades
        if not trades:
            self.close_all_trades_flag = False
        longs = len([trade for trade in trades if not trade.is_short])
        shorts = len([trade for trade in trades if trade.is_short])

     ------------------------------------------------------------

    def custom_exit(self, pair: str, trade: 'Trade', current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:


        # Check if the flag to close all trades is set
        if self.close_all_trades_flag:
            # Signal to close the trade
            return 'sell_cumulative_profit'

        # Update the profit for the current trade
        self.open_trades_profit[trade.id] = current_profit

        # Calculate the cumulative profit of all open trades
        cumulative_profit = sum(self.open_trades_profit.values())

        # If the cumulative profit exceeds 6%, set the flag to close all trades
        if cumulative_profit >= 0.06:
            self.close_all_trades_flag = True
            return 'sell_cumulative_profit'

        # Perform cleanup of closed trades not triggered by this logic
        self.cleanup_closed_trades()

        # If no conditions are met for closing, return None
        return None
```

**Comment by erhangunay** [comment]
> > No, i could not manage to find it..
> 
> If you are willing to take the risk xmatthias mentioned, this has been working reasonably well for me:
> 
> ```
> class your_strategy(IStrategy):
> 
> 
>     # Initialize the strategy
>     def __init__(self, config: dict) -> None:
>         super().__init__(config)
>         # Initialize in-memory storage for trade profits
>         self.open_trades_profit = {}
>         # Initialize the flag to control when to close all trades
>         self.close_all_trades_flag = False
> 
>     --------------------------------------------
> 
>     def confirm_trade_entry(self, pair: str, order_type: str, amount: float, rate: float,
>                             time_in_force: str, current_time: datetime, entry_tag: Optional[str],
>                             side: str, **kwargs) -> bool:
>         """
>         Override to ensure the difference between the number of long and short positions globally does not exceed the limit.
>         """
>         # Correctly fetch all open trades
>         trades = Trade.get_trades_proxy(is_open=True)
>         # Reset the flag if there are no open trades
>         if not trades:
>             self.close_all_trades_flag = False
>         longs = len([trade for trade in trades if not trade.is_short])
>         shorts = len([trade for trade in trades if trade.is_short])
> 
>      ------------------------------------------------------------
> 
>     def custom_exit(self, pair: str, trade: 'Trade', current_time: datetime,
>                         current_rate: float, current_profit: float, **kwargs) -> float:
> 
> 
>         # Check if the flag to close all trades is set
>         if self.close_all_trades_flag:
>             # Signal to close the trade
>             return 'sell_cumulative_profit'
> 
>         # Update the profit for the current trade
>         self.open_trades_profit[trade.id] = current_profit
> 
>         # Calculate the cumulative profit of all open trades
>         cumulative_profit = sum(self.open_trades_profit.values())
> 
>         # If the cumulative profit exceeds 6%, set the flag to close all trades
>         if cumulative_profit >= 0.06:
>             self.close_all_trades_flag = True
>             return 'sell_cumulative_profit'
> 
>         # Perform cleanup of closed trades not triggered by this logic
>         self.cleanup_closed_trades()
> 
>         # If no conditions are met for closing, return None
>         return None
> ```

i am definitely gonna try this out, thanks! 

here is my telegram if you would like to share best practice & knowledge; erhangunay

I can also share the strategy i wanted to implement this (which i gave up on)

**Comment by erhangunay** [comment]
> > No, i could not manage to find it..
> 
> If you are willing to take the risk xmatthias mentioned, this has been working reasonably well for me:
> 
> ```
> class your_strategy(IStrategy):
> 
> 
>     # Initialize the strategy
>     def __init__(self, config: dict) -> None:
>         super().__init__(config)
>         # Initialize in-memory storage for trade profits
>         self.open_trades_profit = {}
>         # Initialize the flag to control when to close all trades
>         self.close_all_trades_flag = False
> 
>     --------------------------------------------
> 
>     def confirm_trade_entry(self, pair: str, order_type: str, amount: float, rate: float,
>                             time_in_force: str, current_time: datetime, entry_tag: Optional[str],
>                             side: str, **kwargs) -> bool:
>         """
>         Override to ensure the difference between the number of long and short positions globally does not exceed the limit.
>         """
>         # Correctly fetch all open trades
>         trades = Trade.get_trades_proxy(is_open=True)
>         # Reset the flag if there are no open trades
>         if not trades:
>             self.close_all_trades_flag = False
>         longs = len([trade for trade in trades if not trade.is_short])
>         shorts = len([trade for trade in trades if trade.is_short])
> 
>      ------------------------------------------------------------
> 
>     def custom_exit(self, pair: str, trade: 'Trade', current_time: datetime,
>                         current_rate: float, current_profit: float, **kwargs) -> float:
> 
> 
>         # Check if the flag to close all trades is set
>         if self.close_all_trades_flag:
>             # Signal to close the trade
>             return 'sell_cumulative_profit'
> 
>         # Update the profit for the current trade
>         self.open_trades_profit[trade.id] = current_profit
> 
>         # Calculate the cumulative profit of all open trades
>         cumulative_profit = sum(self.open_trades_profit.values())
> 
>         # If the cumulative profit exceeds 6%, set the flag to close all trades
>         if cumulative_profit >= 0.06:
>             self.close_all_trades_flag = True
>             return 'sell_cumulative_profit'
> 
>         # Perform cleanup of closed trades not triggered by this logic
>         self.cleanup_closed_trades()
> 
>         # If no conditions are met for closing, return None
>         return None
> ```

do you have a def self.cleanup_closed_trades() ?

i am getting this error
strategy object has no attribute 'cleanup_closed_trades'

**Comment by epetros** [comment]
> > > No, i could not manage to find it..
> > 
> > 
> > If you are willing to take the risk xmatthias mentioned, this has been working reasonably well for me:
> > ```
> > class your_strategy(IStrategy):
> > 
> > 
> >     # Initialize the strategy
> >     def __init__(self, config: dict) -> None:
> >         super().__init__(config)
> >         # Initialize in-memory storage for trade profits
> >         self.open_trades_profit = {}
> >         # Initialize the flag to control when to close all trades
> >         self.close_all_trades_flag = False
> > 
> >     --------------------------------------------
> > 
> >     def confirm_trade_entry(self, pair: str, order_type: str, amount: float, rate: float,
> >                             time_in_force: str, current_time: datetime, entry_tag: Optional[str],
> >                             side: str, **kwargs) -> bool:
> >         """
> >         Override to ensure the difference between the number of long and short positions globally does not exceed the limit.
> >         """
> >         # Correctly fetch all open trades
> >         trades = Trade.get_trades_proxy(is_open=True)
> >         # Reset the flag if there are no open trades
> >         if not trades:
> >             self.close_all_trades_flag = False
> >         longs = len([trade for trade in trades if not trade.is_short])
> >         shorts = len([trade for trade in trades if trade.is_short])
> > 
> >      ------------------------------------------------------------
> > 
> >     def custom_exit(self, pair: str, trade: 'Trade', current_time: datetime,
> >                         current_rate: float, current_profit: float, **kwargs) -> float:
> > 
> > 
> >         # Check if the flag to close all trades is set
> >         if self.close_all_trades_flag:
> >             # Signal to close the trade
> >             return 'sell_cumulative_profit'
> > 
> >         # Update the profit for the current trade
> >         self.open_trades_profit[trade.id] = current_profit
> > 
> >         # Calculate the cumulative profit of all open trades
> >         cumulative_profit = sum(self.open_trades_profit.values())
> > 
> >         # If the cumulative profit exceeds 6%, set the flag to close all trades
> >         if cumulative_profit >= 0.06:
> >             self.close_all_trades_flag = True
> >             return 'sell_cumulative_profit'
> > 
> >         # Perform cleanup of closed trades not triggered by this logic
> >         self.cleanup_closed_trades()
> > 
> >         # If no conditions are met for closing, return None
> >         return None
> > ```
> 
> i am definitely gonna try this out, thanks!
> 
> here is my telegram if you would like to share best practice & knowledge; erhangunay
> 
> I can also share the strategy i wanted to implement this (which i gave up on)

Sorry forgot to include:

    def cleanup_closed_trades(self):
        # Fetch the current open trades
        open_trades = Trade.get_trades_proxy(is_open=True)
        open_trade_ids = {trade.id for trade in open_trades}

        # Remove trades from the in-memory storage if they are no longer open
        for trade_id in list(self.open_trades_profit.keys()):
            if trade_id not in open_trade_ids:
                del self.open_trades_profit[trade_id]

        # Reset the flag if there are no open trades
        if not open_trades:
            self.close_all_trades_flag = False

    # Optionally, add a method to manually reset the flag if needed in other parts of your strategy
    def reset_close_all_trades_flag(self):
        self.close_all_trades_flag = False

Sure, let's collab!
