### ISSUE TITLE
Problem with wallets.get_total_stake_amount() method

### ISSUE THREAD

**Issue by tomashinM** [freqtrade/freqtrade#9827]
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: Python 3.11.7
  * CCXT version: 4.2.25
  * Freqtrade Version: 2024.1

## Describe the problem:

Hello, so I noticed that get_total_stake_amount returns wrong amount when i have limit orders. It seems to not account for stakes that tied up to limit orders so it returns smaller amount.

### Steps to reproduce:

  1. Place limit order with adjust_trade_position
  2. Output get_total_stake_amount 
  3. Compare with real amount on exchange

**Comment by xmatthias** [comment]
Without further information (why do you think this is a problem / where does this create a problem for you??), i'd think that this is an understanding problem more than anything (understanding what this method is supposed to show).

When you have an open limit order to enter a trade (this way it counts against your stake amount) - then that capital is not supposed to show in `get_total_stake_amount()` - as it's tied up.

While the exchange **may** show it in your account - it's not "free" to be used - but tied up in the limit order (e.g. you cannot withdraw that amount, nor can you use it to place further orders).

On Binance for example, you can see this in the "available" column.
Using this coin as example - as i have an open sell order for this - which is for the difference between the "amount" and the "available" columns.
 
![image](https://github.com/freqtrade/freqtrade/assets/5024695/4382baae-7ec3-438d-b923-4e443a0edb62)

The mobile App doesn't seem to show this in this way - but that's a problem of the mobile version (in this case Binance) - not something freqtrade can address.

**Comment by tomashinM** [comment]
Ok thanks for clearing that up. I understand that its not a bug. But still if i need full amount for my purpose how can i get that in freqtrade?

**Comment by xmatthias** [comment]
Well you can use the [wallets](https://www.freqtrade.io/en/latest/strategy-customization/#possible-options-for-wallets) object the way it was designed (`get_total_stake_amount()` is neither documented, nor should it be used directly in a strategy.

These options do take the asset though ('USDT') - not the whole pair.
