### ISSUE TITLE
data prepend does not have the desired effect kraken

### ISSUE THREAD

**Issue by nicolassim** [freqtrade/freqtrade#9830]
prepend does not work during download data.
This is the command used for first download:
freqtrade download-data --config user_data/config.json --timerange 20220101-20230901 -t 5m
this is successfully using kraken for few */EUR pairs (ETH/EUR included)

this is overwriting the data:
freqtrade download-data --exchange kraken --pairs ADA/EUR ETH/EUR --prepend --timerange 20211201-20220102

using the config file does the same.

Logs mention that starting date is earlier than avvailable pair and "current tades = 0", so it looks to me that tries to append and not to prepend.

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Kraken does not provide historic ohlcv data - you can only get the last 720 candles from their ohlcv endpoints (hence downloading-data does not work at all) - and as a consequence - the `--prepend` method is not a supported method.

To download data from kraken - we therefore must download "trades" data (which is WAY bigger, way slower - and must be converted to ohlcv afterwards).

Now if you did use the `new-config` command - AND select kraken for that - the `--dl-trades` command was automatically added for you through the configuration (the logs would tell this - you can also check for the existance of `<pair>-trades` files in your data directory).
If you didn't do either of the above - then you'll only have 720 candles downloaded anyway.

For kraken - there's an alternative, WAY faster method to download the data by 
downloading their pre-made [trades csv files](https://www.freqtrade.io/en/latest/exchanges/#historic-kraken-data) and placing them in the appropriate spot - which i'd strongly recommend to use unless you're kee to wait for weeks for the download to complete.

---

As for your explicit question  - yes, `--prepend` does not work for --dl-trades mode - and is not expected to as it does not make sense - as there's better methods to download for kraken (the only exchange that even needs the `--dl-trades` mode).

**Comment by nicolassim** [comment]
Thanks for pointing me in the right direction. 
I find however wrong that the tool accepts the —prepend parameter and silently overrides the data. 
If prepending is not possible an error would have been appreciated something like “prepend not possible for kraken, look at exchange specific notes”.
