### ISSUE TITLE
Stop-Loss in Backtest -Fails on both "when and price" Bug. Impacts backtest and hyperopt results

### ISSUE THREAD

**Issue by creslinux** [freqtrade/freqtrade#985]
Often in backtest a trade reports a loss greater than the stop-loss.  

Summary *edit - see next comments; TLDR - BT sets "current_rate" to "close" which is used in stop-loss processing. 

- This misses closing trades that would stopped out mid candle, keep trades open artificially longer than dry/live. 
- Uses the "close" price for trade loss calculation, this can be wildly lower/worse then the stop-price the user expects to receive, take a hit on

In backtest the logic should be : 
- If the  "Low" of the completed bar was lower than stop-loss the trade should be closed. 
- The price received and recorded in the trades table should be adjusted to 
             entry-price - stop-loss% - fee. 
- it is important to look back on the completed bar when checking the OLCH to align new trades entry realistically. 

If I entered a trade with a buy price of $100, and with a stop of 2% and fees are 0.05% on buy and sell each (binance). No trade in backtest should show a loss of more than 2.1% $2.10

This is true as in live stop-loss is not triggered on a OLHC data but ticker price. 
Therefor a candle having a low of minus 8% or close minus 6% is immaterial as the trade would have been closed at minus 2% per the stop.

Example trades with more than 2% loss with 2% set. 
<img width="876" alt="screen shot 2018-07-07 at 9 35 10 am" src="https://user-images.githubusercontent.com/34645187/42409377-36a197ec-81c9-11e8-8438-a9ccfc86c5d4.png">

**Comment by creslinux** [comment]
To support the above assertion, using a 2% stop as example.

In a backtest execution under debug we can see that the candle close rate (75939) is being used as "current_rate" in stop-loss processing. This is a side effect of there being no "current_rate" tick data during back-test to present to the function.  

Whilst this does ensure the stop exits the trade in the correct candle period it does not factor that rate can be significantly off, leading to bad backtest/hyperopt results when "close" is significantly lower then the stop. 

In dry-test and live "current _rate" will be presented as-quicky-as-can-get-it. 
At 2% the 'trade.stop_loss' would be greater than "current_rate" trigging sale.

The suggested fix is, in backtest only, to set received sale price to 'trade.stop_loss', not close. 
This then assumes in BT that stop was triggered and the price at stop was received. This is not perfect but will be much better than a close value. 

<img width="1278" alt="screen shot 2018-07-08 at 12 43 20 pm" src="https://user-images.githubusercontent.com/34645187/42420035-3e8983c0-82af-11e8-82ee-3968fca6ec7b.png">

<img width="1266" alt="screen shot 2018-07-08 at 12 49 31 pm" src="https://user-images.githubusercontent.com/34645187/42420037-4500103e-82af-11e8-88b4-fa57c2153ef5.png">

**Comment by xmatthias** [comment]
I think this approach would further taint results.

If we use low for stop-loss detection - we would also need to use high for take profit / ROI - as that is also used from "current rate" which is not available in backtesting.

However, backtesting lacks information on which of the 2 appeared earlier, so depending on the implementation it would 

* always be a loss if low breached stop-loss and high breached ROI
* always be a win if high breached ROI and low breached stop-loss

both scenarios are wrong as reality may differ (especially when using longer timeframes).

**Comment by creslinux** [comment]
I accept we do not know which would have occurred first if there are wicks for both stop-loss and for take profit.  It will not always be the case a candle will have wick to touch both. So if only touched stop there is no reason to not tigger stop. 

I would also argue that protection of capital outranks chase for profit in trading which give stop-loss the trump card.

To the second issue, price to use on stop. We know the stop price it should be used. 

"close" bares no relation to stop - stop is by design not associated with OHLC  but a hard fixed rate that can occur at any time but always the same sum.
We should never ignore the stop-value and assign another price, if stop is set at 1% and a candle dumps 10% stop must protect capital to 1% drop on position - or its not a stop .

The prime purpose of a stop is to protect from a huge dump in market value. 
We are engineering back testing to ignore stops prime purpose to ensure losses are capped on a trade. 

This undermines ability to apply/test money management and risk reward, which are above all other traits in successful trading.

**Comment by xmatthias** [comment]
i agree that porotection of capital outranks chase for profit - but i'm not sure that applies in backtesting - as it can pull strategy-performance to negative while it would have won (assume 4h candles, price swings to ROI after buy and then down again ... for each trade as i can detect a long green candle reliably).

i assume this has a bigger effect when using longer tick-intervals?

**Comment by creslinux** [comment]
Crypto markets are "shook out" and "dug for springs" and "stop hunted" many times each day.
 
Avoiding being stopped out is one strategy designs biggest challenges, finding the right level / balance between staying in the trade and not accepting to much loss if stopped out. 
A key backtest value add

Gracefully avoiding being shaken out provides false positive strategies.

Re longer time frames. No. Crypto tends to dump and dump hard in minutes.

**Comment by creslinux** [comment]
Having considered the ROI and SL argument further i disagree more. 
The two do not cancel each other out, but widens the problem, taint in the current setup is worse.

If we say our SL and ROI are 2% below/above spot respectively. 

- If BTC jumps $1,000 ROI does not take 2% profit, as uses close price not ROI , and takes %14 profit. 

- - The user believes the strategy is much more profitable than is. 

- If BTC dumps $1,000 STOP does not take 2% loss, as uses close price not ROI , and takes %14 loss. 

- - The user believes the strategy is much less profitable than is.

**Comment by creslinux** [comment]
<img width="1117" alt="screen shot 2018-07-09 at 8 39 43 am" src="https://user-images.githubusercontent.com/34645187/42440044-036dfba4-8354-11e8-9d03-51f9aa7ee46a.png">

**Comment by creslinux** [comment]
<img width="1084" alt="screen shot 2018-07-09 at 8 50 16 am" src="https://user-images.githubusercontent.com/34645187/42440426-3decdfec-8355-11e8-9e2a-308d47b8e93d.png">

**Comment by creslinux** [comment]
<img width="1084" alt="screen shot 2018-07-09 at 8 50 16 am" src="https://user-images.githubusercontent.com/34645187/42440440-49dd6790-8355-11e8-8eae-c1f5436b7a56.png">

**Comment by xmatthias** [comment]
i think this is the better issue for this - as it actually covers the above outlined options.
#1003 is only about stop-loss.

i think the following branch should fix the problematic scenarios outlined above.
https://github.com/xmatthias/freqtrade/tree/feat/functional_tests

due to buy-signal shift (avoiding look-ahead in backtest) i had to add a "empty" candle at the beginning of each test-case.

it does:
* use high for roi
* use low for stop-loss

does not:
* support all options correctly

would be great if @creslinux could give this a look when time permits, so i know if it fixes the outlined problems - and i can get to try and adapt this into "usable" code.

**Comment by mishaker** [comment]
@xmatthias 

Regarding your tests here: https://github.com/xmatthias/freqtrade/blob/feat/functional_tests/freqtrade/tests/optimize/test_backtest_detail.py 

It is maybe a question of personal taste but I prefer organizing the test and ticker more like the following so that it becomes more readable:

https://github.com/mishaker/freqtrade/blob/8a316aba35a8dc85ccdea8c4cf19f385ed139707/freqtrade/tests/edge/test_edge.py#L238

syntax wise I would propose to somehow unifying our tests cause we are working on the same thing. 

also:
How do you manage ROI and SL if both are hit on a candle ? is there a priority ?

**Comment by xmatthias** [comment]
i would like to keep the test-data (data + expected results) out of the test-function (so it's easy to reuse the same code for tens or hundreds of test cases). Eventually in it's own file - but there are not so many yet. pytest allows this easily with parametrized tests.

your approach needs a seperate "testing-function" for each case if i understood it correctly - which would work but produces a ton of boilerplate code, as in my implementation, i really need to test for the same exact thing each time, which is the selling-type and trade count.

My code is not yet cleaned up (a lot of comments as i had different results with different approaches) - i'll try to rebase and clean it up soon, and propose a PR.

clearly SL first. 
there is no way to know which was first in reality - and SL first protects users capital better. I would prefer to see a stop-loss more in backtesting, and then be positively surprised by a ROI than the other way around..

**Comment by mishaker** [comment]
ok. in that case I am going to base my tests on yours so we have a unified version as Edge test cases are the same for backtesting except that it doesn't consider ROI and TSL (it should not).
I have however some comments about your code that I am going to add on your branch.

**Comment by xmatthias** [comment]
these tests have been covered with #1306, therefore closing.
If you don't think #1306 resolves this or discover a bug feel free to reopen (or open a new issue).

@creslinux Thanks for investigating this so thorough and developing the test-cases
