### ISSUE TITLE
BTCMarkets Issue (No fetchTickers option, and error with VolumepairList workaround)

### ISSUE THREAD

**Issue by zonesql** [freqtrade/freqtrade#9851]
Hi all, I attempted to set up freqtrade for a dry run using BTCMarkets exchange. freqtrade website lists btcmarkets as available but missing opt '**fetchTickers**' (which seemed ominous).

I noticed the The freqtrade logs also mentions: 

> 'freqtrade.exchange.check_exchange - WARNING - Exchange "btcmarkets" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.''

On first run through I received this error:

> 'freqtrade.commands.trade_commands - ERROR - Exchange does not support dynamic whitelist in this configuration. Please edit your config and either remove Volumepairlist, or switch to using candles. and restart the bot.'

On attempting to use a variation for the VolumepairList as shown on the freqtrade website, I receive this error:

> 'freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair ADA/AUD due to BadRequest. Message: btcmarkets {"code":"InvalidPaginationParameter","message":"invalid limit parameter. max limit is 200"}". Retrying still for 4 times.'

So a) here is the requested 'report back'.  and b) any suggestions?

**Comment by stash86** [comment]
> freqtrade website lists btcmarkets as available but missing opt 'fetchTickers' (which seemed ominous).

I don't think this is true. Nowhere in the docs do we mention about btcmarkets exchange, unless I'm missing something.

Suggestion : use one of the supported exchanges

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

In theory, freqtrade supports every exchange ccxt supports, which would also include this exchange.

Now you're the first to ask for that (at least as far as i remember), so you're probably the first to have a look at this.
we have a rough guideline on things to check in the [contributors section of the documentation](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip).
While it's probably not complete, it should give you a good idea if the exchange will work for spot trading.

If you encounter specific problems, we're happy to assist up to a certain point - but the expectation for new exchanges is that the user interested is doing the legwork / most of the testing work - which also assumes a somewhat familiarity with python / testing/debugging things in python.

If you're new to python / development - you're almost certainly better of with one of the supported exchanges.


---

it _might_ be part of the output in the utils section about `list-exchanges` - but that list is neither intended to be complete - nor will it be uptodate.

`fetch_tickers` is clearly optional - and will only really impact some pairlists. a static pairlist should therefore work - at least to some degree (but is definitely the first thing to check on a new exchnage.
