### ISSUE TITLE
Backtest report - enhancement - add profitability for human readability 

### ISSUE THREAD

**Issue by creslinux** [freqtrade/freqtrade#986]
Backtest rather accurately reports avg % and number of trades. 
This somewhat obfuscates from how profitable the backtest has been. 

As example:  "109 Trades : Avg Prf 5.334% "
Can also be written as *$581% profitable  - which may be of interest and benefit to users. 

* Assuming no parallel trades needed. 

## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment]
letme understand this ... we do show "absolute" profit (toal profit stake-currency).

is the column you'd need "a cumulative percentage"? basically a sum of all percentages?

**Comment by creslinux** [comment]
If only a single stake was used in series it would be that yes. 
If two stakes were utilised (parallel) trades the profitability would be halved as its needed double the capital investment. 
(BTW of the issues logged this is the simplest and maybe most within my coding reach - happy to take it on)

**Comment by xmatthias** [comment]
then go for it :+1:

**Comment by xmatthias** [comment]
This was actually implemented in #1510 - which was reraised as #1497 ...
