### ISSUE TITLE
API Server not working properly using docker compose multiple bot configuration

### ISSUE THREAD

**Issue by ThatFack** [freqtrade/freqtrade#9863]
## Describe your environment

  * Operating system: Debian 10
  * Python Version: Python 2.7.16
  * CCXT version: 3.0.62
  * Freqtrade Version: freqtrade 2024.1

  
## Your question

Hello !

I have currently set up 3 bots. I used to repeat 3 times the docker compose up command to run them, changing directory in order to make it works etc... 

It was a bit too long so I decided to put all three bots in the same docker-compose.yml file. But since i did this, the API servers are not working properly anymore.

Please see below my current docker configuration and config files :

## docker-compose.yml

```
---
version: '3'
services:
  Scenario1:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade_MpStratBiais
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "10.8.0.1:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/Scenario1_freqtrade.log
      --db-url sqlite:////freqtrade/user_data/Scenario1tradesv3.sqlite
      --config /freqtrade/user_data/Sc1_config.json
      --strategy MpStratBiais
  Scenario2:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade_scenario2
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "10.8.0.1:8090:8090"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/Scenario2_freqtrade.log
      --db-url sqlite:////freqtrade/user_data/Scenario2tradesv3.sqlite
      --config /freqtrade/user_data/Sc2_config.json
      --strategy Scenario2BiaisLatest
  Scenario3:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade_scenario7
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "10.8.0.1:8070:8070"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/Scenario3_freqtrade.log
      --db-url sqlite:////freqtrade/user_data/Scenario3tradesv3.sqlite
      --config /freqtrade/user_data/Sc3_config.json
      --strategy Scenario7Latest
```

## Sc1_config.json

```
"api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "key",
        "CORS_origins": ["http://10.8.0.1:8080"],
        "username": "test",
        "password": "test",
        "ws_token": "token"
    },

```

## Sc2_config.json

```
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8090,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "key",
        "CORS_origins": ["http://10.8.0.1:8080"],
        "username": "test",
        "password": "test",
        "ws_token": "token"
    },
```

## Sc3_config.json

```
    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8070,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "key",
        "CORS_origins": ["http://10.8.0.1:8080"],
        "username": "test",
        "password": "test",
        "ws_token": "token"
    },
```

Here are the curl answers outputs : 

## The first one 8080 works properly : 

`curl http://10.8.0.1:8080/`

```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <link rel="icon" href="/favicon.ico">
  <title>FreqUI</title>

  <script type="module" crossorigin src="/assets/index-jMaMtX3c.js"></script>
  <link rel="stylesheet" crossorigin href="/assets/index-t4uHhMF3.css">
</head>

<body data-bs-theme="dark">
  <noscript>
    <strong>We're sorry but FreqUI doesn't work properly without JavaScript enabled. Please enable it to
      continue.</strong>
  </noscript>
  <div id="app"></div>
</body>

</html>
```

## The second one 8090 is up but reset the connection : 
 
` curl http://10.8.0.1:8090/`
` curl: (56) Recv failure: Connection reset by peer`

## And the last one 8070 is doing the same : 

` curl http://10.8.0.1:8070/`
`curl: (56) Recv failure: Connection reset by peer`

But some times I got this one also :

`curl http://10.8.0.1:8070/`
` curl: (52) Empty reply from server`

If I launch them separately, each one in a different directory with their own docker-compose.yml file it works fine.

I hope someone will be able to help, 

Thank you so much !

**Comment by stash86** [comment]
I have 18 bots under 1 .yml file and I have no issue with the API. Try stopping them all (docker-compose down) then up it again

**Comment by ThatFack** [comment]
@stash86 I tried to stop and restart them all but nothing changes, do you see something in my configuation that might differ from yours ? Thank you for having a look to my issue !

**Comment by xmatthias** [comment]
Whats the output of `docker ps`?
How exactly did you start the bots?

Are the bots actually running, or do their logs have errors / problems?

**Comment by iterativv** [comment]
I thought it was a configuration mistake, but it appears that the api server with version after 2023.12 is not working properly in a multi-bot setup as the above. Probably it's docker specific too.

Very likely it's similar issue as #9845

If 2023.12 works without issues, then it's either a module update or a FT commit. In this case, [ThatFack](https://github.com/ThatFack) maybe try a divide & conquer approach to locate where from the issue is starting. It should start somewhere in January, if that event.

**Comment by stash86** [comment]
If it's freqtrade related, my 2 vpses with 16 bots each would have had same issue. But they aren't

**Comment by xmatthias** [comment]
@iterativv If you've got nothing to contribute to an issue, then please don't.

Nothing / nobody in this issue even MENTIONS an older version that's working - the author had a different setup previously - which you can't compare.
#9845 did NOT provide any logs - neither did you - so it's just random noise, without providing value.

Things that help help are 
* proper logs
* any more details other than "could be this or that" - without actually having a clue

What doesn't help - and will get your comments hidden / deleted - and may eventually lead to a ban:

* Random finger-pointing
* Linking issues that are not related
* Highjacking issues "just because" (like you did with this issue).

Thanks for your understanding.

**Comment by rmtucker** [comment]
@xmatthias 
I am having exactly the same issues with the api.
I am running 3 bots within docker.
If i turn on the api server on all 3 of the bots,one of the bots is repeatedly restarting.
If i turn 1 of the api servers off,the bots run without problem.
It would be very helpful if you could explain what logs you would require to see the problem.

**Comment by xmatthias** [comment]
@rmtucker  i'm not immediately convinced i see the connection between what you say, and what this issue is about (which is most likely a simple configuration issue, and does NOT mention restarting at all). (it does sound more like #9845 - which for the moment, i see as something other than this issue - so please move the further conversation there).


Assuming you have 3 bots in one docker-compose file - then a simple `docker compose log` "might" help (either for all bots - or selecting individual bots).

If that doesn't include anything conclusive - then you might wana look at the system level logs (e.g. `journalctl`).

**Comment by ThatFack** [comment]
Hello,

thank you for your time reviewing my issue guys !

## This is the docker ps output :


```
f4b80af595db   freqtrade:local   "freqtrade trade --l…"   12 hours ago   Up 12 hours   10.8.0.1:8090->8090/tcp   freqtrade_scenario2
37721c436b24   freqtrade:local   "freqtrade trade --l…"   12 hours ago   Up 12 hours   10.8.0.1:8070->8070/tcp   freqtrade_scenario7
61669b9f7823   freqtrade:local   "freqtrade trade --l…"   12 hours ago   Up 12 hours   10.8.0.1:8080->8080/tcp   freqtrade_MpStratBiais

```

I start my bot by running this command in the bot root directory :

`sudo docker compose -f docker-compose.yml -f docker-compose.local.yml up`

The second docker-compose.local.yml contains the dockerfile path, which I use to install my additional dependencies please see below :

## Docker-compose.local.yml 

```
version: '3'
services:
  Scenario1:
    image: freqtrade:local
    build:
       context: .
       dockerfile: "./Dockerfile.env"
  Scenario2:
    image: freqtrade:local
    build:
       context: .
       dockerfile: "./Dockerfile.env"
  Scenario3:
    image: freqtrade:local
    build:
       context: .
       dockerfile: "./Dockerfile.env"
```

## Bots status

The bots are working properly, I have heartbeats and they are placing positions.

Bot 1 :

`2024-02-25 12:26:17,404 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-2024.1-dev-8d72ee35', state='RUNNING'`

Bot 2 : 

`2024-02-25 12:43:22,233 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-2024.1-dev-8d72ee35', state='RUNNING'`

Bot 3 : 

`2024-02-25 12:45:22,042 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-2024.1-dev-8d72ee35', state='RUNNING'`

Thank you for your help !

**Comment by xmatthias** [comment]
Now personally - i do keep the docker internal port identical (so all ports run on :8080) - and then do the mappings accordingly (so it's only one place to change - and personally, i find it less error-prone).
With your setup, one "mixup" between port mapping and config used would lead to an API no longer working.

How that'd look like in the compose file:

```
    ports:
      - 0.0.0.0:8081:8080
  ....
    ports:
      - 0.0.0.0:8082:8080
...
    ports:
      - 0.0.0.0:8083:8080

```

It's very clearly _personal preference_ - and as long as the following points are given, i don't see why it shouldn't work.

* the listen_ip is `0.0.0.0` (for docker setups)
* the `"listen_port"` in each config corresponds to the ":<port>" in the compose file

docker was started with `docker compose <...> up -d` (in theory the `-d` is optional - though i don't like my session to be tied to docker containers)

---
 
what's the response of `curl <10.8.0.1>:808x/api/v1/ping` for each of the bots / urls ? 
what's your actual setup? (10.8.0.1 is not localhost ...)?

Also, when the bots start - they should have something around `Starting HTTP Server at 0.0.0.0:8080` ... lines around this are ... important - the webserver could fail to start - which would not necessarily influence the bot's behavior.

**Comment by ThatFack** [comment]
I changed the configuration accordingly to your suggestions, the config file too, but now even the one that was working (8080 which is now 8081) is not starting.

## Please see below the logs about the http server :

```
2024-02-25 13:27:25,272 - freqtrade.rpc.api_server.webserver - INFO - Starting HTTP Server at 0.0.0.0:8082
2024-02-25 13:27:25,272 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.
2024-02-25 13:27:25,296 - uvicorn.error - INFO - Started server process [1]
2024-02-25 13:27:25,296 - uvicorn.error - INFO - Waiting for application startup.
2024-02-25 13:27:25,297 - uvicorn.error - INFO - Application startup complete.
2024-02-25 13:27:25,298 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8082 (Press CTRL+C to quit)

2024-02-25 13:27:15,120 - freqtrade.rpc.api_server.webserver - INFO - Starting HTTP Server at 0.0.0.0:8083
2024-02-25 13:27:15,120 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.
2024-02-25 13:27:15,154 - uvicorn.error - INFO - Started server process [1]
2024-02-25 13:27:15,154 - uvicorn.error - INFO - Waiting for application startup.
2024-02-25 13:27:15,155 - uvicorn.error - INFO - Application startup complete.
2024-02-25 13:27:15,157 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8083 (Press CTRL+C to quit)

2024-02-25 13:27:14,689 - freqtrade.rpc.api_server.webserver - INFO - Starting HTTP Server at 0.0.0.0:8081
2024-02-25 13:27:14,690 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.
2024-02-25 13:27:14,722 - uvicorn.error - INFO - Started server process [1]
2024-02-25 13:27:14,722 - uvicorn.error - INFO - Waiting for application startup.
2024-02-25 13:27:14,723 - uvicorn.error - INFO - Application startup complete.
2024-02-25 13:27:14,723 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)

```

## See the new config files :

1 :

```
"api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8081,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "key",
        "CORS_origins": ["http://10.8.0.1:8081"],
        "username": "test",
        "password": "test",
        "ws_token": "token"
    },
```

2 :

```
"api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8082,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "key",
        "CORS_origins": ["http://10.8.0.1:8081"],
        "username": "test",
        "password": "test",
        "ws_token": "token"
    },
```

3 :

```
"api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8083,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "key",
        "CORS_origins": ["http://10.8.0.1:8081"],
        "username": "test",
        "password": "test",
        "ws_token": "token"
    },
```
## Please see below the pings :
 
```
curl http://10.8.0.1:8081/api/v1/ping
curl: (56) Recv failure: Connection reset by peer

curl http://10.8.0.1:8082/api/v1/ping
curl: (52) Empty reply from server

curl http://10.8.0.1:8083/api/v1/ping
curl: (56) Recv failure: Connection reset by peer
```
## Set up

I use 10.8.0.1 because I want my dashboard to be available from internet, but without exposing my vps to internet. To do so I use a VPN tunnel and the vpn subnet is 10.8.0.0/24. 
So when I connect to my VPN i can reach the services hosted the on the machine from that ip.

It worked well until i combined the bots in one docker-compose.yml

Again thank you for your time !

**Comment by xmatthias** [comment]
well my (personal) config would look like this: `"listen_port": 8080,` .... (for all configs).

it all comes down to the compose format - which in reality is as follows:

```
- ports:
      - 0.0.0.0:8081:8080
      - <hostlistenaddress>:<exposedPort>:<PortInContainer>
```

The first two parts refer to the host - the last to the "within the container" section.
so your configuration must match the very last part - the "portInContainer".

The logs above do show that the listen_port wasn't changed - so the containers do listen on "8082, 8083, ..." ... but what actually counts is how they do look like outside of the container.

For the curl test - please run that test ON the server (even though you ultimately don't want to use it from there).
Just because there's a VPN doesn't necessarily mean there's no firewall in place.

**Comment by ThatFack** [comment]
Thank you for your help !

Using the same PortInContainer solved the issue!

I can now acces all of me three bots API :)

Below the working config for anyone that would need a similar set up : 

## docker-compose.yml

```
---
version: '3'
services:
  Scenario1:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade_MpStratBiais
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "10.8.0.1:8081:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/Scenario1_freqtrade.log
      --db-url sqlite:////freqtrade/user_data/Scenario1tradesv3.sqlite
      --config /freqtrade/user_data/Sc1_config.json
      --strategy MpStratBiais
  Scenario2:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade_scenario2
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "10.8.0.1:8082:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/Scenario2_freqtrade.log
      --db-url sqlite:////freqtrade/user_data/Scenario2tradesv3.sqlite
      --config /freqtrade/user_data/Sc2_config.json
      --strategy Scenario2BiaisLatest
  Scenario3:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade_scenario7
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "10.8.0.1:8083:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/Scenario3_freqtrade.log
      --db-url sqlite:////freqtrade/user_data/Scenario3tradesv3.sqlite
      --config /freqtrade/user_data/Sc3_config.json
      --strategy Scenario7Latest

```


## Config files :

1 :

```
"api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "key",
        "CORS_origins": ["http://10.8.0.1:8081"],
        "username": "test",
        "password": "test",
        "ws_token": "token"
    },
```

2 :

```
"api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "key",
        "CORS_origins": ["http://10.8.0.1:8081"],
        "username": "test",
        "password": "test",
        "ws_token": "token"
    },
```

3 :

```
"api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "key",
        "CORS_origins": ["http://10.8.0.1:8081"],
        "username": "test",
        "password": "test",
        "ws_token": "token"
    },

```

Really appreciate your help @xmatthias !

**Comment by xmatthias** [comment]
Well happy you got that fixed
would you mind fixing your config snippets to what you're actually using (listen_port should be 8080 - aligned with the compose file)? (as this configuration will NOT work, as the ports are miss-matched) :laughing:

**Comment by ThatFack** [comment]
Oups you are right I copied pasted the one above lol , fixed !

**Comment by xmatthias** [comment]
Perfect - _now_ it can serve as reference for future users with similar problems.
