### ISSUE TITLE
lightgbm is not installed with dev setup on macos

### ISSUE THREAD

**Issue by jokaorgua** [freqtrade/freqtrade#9874]
## Describe your environment

  * Operating system: macos m1 silicon
  * Python Version: 3.11.7 (`python -V`)
  * CCXT version: 4.2.51 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2024.2-dev-9d2bfa659
 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Describe the problem:

on the fresh install and on the fresh system `./setup.sh -i` (with y for installing all dev things) fails because lightgbm can't be installed.

`
Building wheel for lightgbm (pyproject.toml) did not run successfully.
  │ exit code: 1
`
### Steps to reproduce:

  1. take fully fresh macos
  2. git clone freqtrade
  3. ./setup.sh -i (y when asked for installing dev tools)
  
## How to fix?

run `brew install libomp` and re-run `./setup.py -i`

**Comment by xmatthias** [comment]
seems like they don't provide wheels for M1 ... though in my memory, they did.

Now i'm more than happy to get a PR improving setup for M1 (it should obviously work / be tested on a non-m1 mac, too).

i don't own a mac, and as such, don't have the possibility to test this, or work on it, so without a PR - the solution will be to skip install for M1 for lightgbm - which we did in the past for other freqAI dependencies - and i don't necessarily see as a problem now, either.
