### ISSUE TITLE
Force fetch remote pair 

### ISSUE THREAD

**Issue by godshades** [freqtrade/freqtrade#9875]
Hi i want force get new remote pair list after stoploss, can I do that ?

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

No, you cannot do that. 
Pairlist refreshing happens at regular intervals - and is independent of trade activity (except for `FullTradesFilter` - which does something else).

What you can do however is to fetch more pairs than what you need - and lock the pair that had the stoploss.
