### ISSUE TITLE
analyze_ticker/advise_entry throws error when trying to set enter_tag column in empty main dataframe

### ISSUE THREAD

**Issue by froggleston** [freqtrade/freqtrade#9879]
## Describe your environment

  * Operating system: Windows 10, WSL 2, Ubuntu 20.04
  * Python Version: Python 3.11.5
  * CCXT version: 4.2.25
  * Freqtrade Version: 2024.2-dev-0bc5c876c
  
## Describe the problem:

When using the strategy.analyze_ticker function, a bug arises if a strategy has no enter_tag set for entries within a strategy.

### Steps to reproduce:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[21], line 119
    118 print(f"[{strat_name}] Loaded " + str(len(all_candles[pair])) + f" rows of {br_config['trading_mode']} data for {pair} from {datadir}")
--> 119 analysed_candles = strategy.analyze_ticker(all_candles[pair], {'pair': f"{pair}"})
    120 analysed_candles = analysed_candles.set_index('date', drop=False)

File /freqtrade/freqtrade/strategy/interface.py:852, in IStrategy.analyze_ticker(self, dataframe, metadata)
    851 dataframe = self.advise_indicators(dataframe, metadata)
--> 852 dataframe = self.advise_entry(dataframe, metadata)
    853 dataframe = self.advise_exit(dataframe, metadata)

File /freqtrade/freqtrade/strategy/interface.py:1392, in IStrategy.advise_entry(self, dataframe, metadata)
   1391 # Initialize column to work around Pandas bug #56503.
-> 1392 dataframe.loc[:, 'enter_tag'] = ''
   1393 df = self.populate_entry_trend(dataframe, metadata)

File ~/.local/lib/python3.11/site-packages/pandas/core/indexing.py:885, in _LocationIndexer.__setitem__(self, key, value)
    884 iloc = self if self.name == "iloc" else self.obj.iloc
--> 885 iloc._setitem_with_indexer(indexer, value, self.name)

File ~/.local/lib/python3.11/site-packages/pandas/core/indexing.py:1809, in _iLocIndexer._setitem_with_indexer(self, indexer, value, name)
   1808 if not is_list_like_indexer(value):
-> 1809     raise ValueError(
   1810         "cannot set a frame with no "
   1811         "defined index and a scalar"
   1812     )
   1813 self.obj[key] = value

ValueError: cannot set a frame with no defined index and a scalar
```
  
Presumably this is most likely caused by having a zero length dataframe, so a check before this line is called might be a fix. Maybe just changing the method of column addition would work, e.g. `df.assign({"enter_tag":""})` (although this creates a new copy) or even simpler `df['enter_tag'] = ""`? Was there a specific reason to use .loc here?

I can submit a PR if a particular solution is appropriate.

**Comment by xmatthias** [comment]
I'm not entirely sure what you mean / what you need to do to trigger this problem.

`dataframe.loc[:, column]` is the recommended way by pandas itself - using `dataframe['column']` is flaky, as it's unclear if you mean the row or column index - forcing pandas to infer this (not always correctly).
I doubt that `df.assign()` will work better - as there's something wrong with the dataframe to begin with.

It would appear that the strategy does something funky with the dataframe as part of `populate_indicators()` - if you have that part of the strategy that's triggering this - we can most likely identify the cause.
Setting (or not setting) 'enter_tag' as part of the strategy is not relevant - this is the initialization for that column ...

**Comment by froggleston** [comment]
From a quick check I can actually see what's going on now. Typical :D

Thanks for responding though, but it's down to the 0 length dataframe as a result of trying to load spot named pairs when the TradingMode is set to FUTURES.

**Comment by xmatthias** [comment]
how'd you get that far with that configuration anyway? 
should be "no pair in whitelist" or similar ... ? 

---

well there's a different argument to this as well - with pandas 2.2.x - we could remove this workaround again - as it's no longer strictly necessary.

i'm still ... undecided on this - and probably will keep it there - at least for now - mainly because it doesn't hurt to have this initialized properly.

**Comment by froggleston** [comment]
It's from the notebook - things get initialised in a non-standard way due to me using stuff like an API ;)
