### ISSUE TITLE
Live: Stop-loss orders are not stop-loss, ensuring a bad price and risk users capital unnecessarily 

### ISSUE THREAD

**Issue by creslinux** [freqtrade/freqtrade#988]
Stoploss is  type of order added on the exchange to automatically trigger when price breaches that threshold.  They are the best means to protect/limit loss on a trade to a known limit. They are designed to protect a trade in event of any external failure whilst ensuring best price. 

A stoploss on the exchange ensures the best price as its ahead in the queue before incoming requests.  They protects against lack of connectivity, late ticker data, bot-crashes, ultimately unnecessary slip / loss of users capital.  

Freqtrade makes an order after it sees price has breached a threshhold to manage users stop levels.  

This ensures it is both late to manage stop and at the back of the order queue for handling stop. Both of which will negatively impact a users capital. It also exposes the user to risk should ticker be unavailable, the bot crash, the API be DDOS's, other 

Stop-loss in freqtrade should make stop-loss orders to better protect capital and mitigate connectivity / latency / cost risks.

**Comment by xmatthias** [comment]
one problem i see with stoploss orders is that it freezes the capital - so before selling (for profit, eventually) the bot would need to first cancel the stop-loss order - which would (again) impact users profit eventually, as the sell would come "a bit" later.

at least on kraken (and binance if i remember correctly), i can only have a stop-loss OR a take-profit order for the same currency (assuming i trade everything i have in this pair) - not both.

**Comment by creslinux** [comment]
Thats true, but a stop-loss is triggered when the trade is out of control, by definition the trade entry assumption has been proven wrong and if present the sell logic has failed too.  

Add into the mix, connectivity problems, crashes, cloudfare issue, API key cancelation like this week and a miriad of other use-cases a stop-loss should be on the exchange. 

Best case at the moment is we're lucky enough to see the price breaking same few seconds, place an order the book, there be liquidity for it, not too many people before us in the queue. 

In contrast Taking profits is undertaken when we're in control of the trade, time is on our side a we're waiting for profits to be reached. The cancelation of a stop and order will be tested but expectations are in the oder of second to seconds. 

The impact will be disproportionate.

**Comment by creslinux** [comment]
The bot could be enhanced to capture slip on stop, we can ask the community to submit this telemetry back to us. This would demonstrate the real-world $ cost.

**Comment by creslinux** [comment]
Yes thats how its done.  There is no cost to cancelling/re-applying a stop-loss or stop-buy. 

Trailing stops can be cancelled and re-applied at the new rate - this works across all exchanges and is the simplest to implement for that rational on a multi-exchange bot. 

Sme exchanges support trailing stops as an order type directly, others allow a modify order.

**Comment by creslinux** [comment]
As an aside there are stop-loss-market and stop-loss-limit. 

Stop-loss-market, sells down the orderbook till filled on breach of price X
Stop-loss-limit takes two parameters, price triggers and worst price to sell at, exchange will try for better. 

The first offers the most protection and is the norm.
The second tends to be used more to reducing position size in pyramiding.

**Comment by berlinguyinca** [comment]
I agree with creslin. stop loss orders should be set directly on buy. otherwise they will never really work.

and if trailing stop is used, need to be moved up constantly. 

for example:

1. I buy a coin
2. my internet connection crashes
3. hours later it comes back on and my money is gone, since the bot was not able to trigger a stop loss.

better would be

1. I buy a coin
2. immidiatly stop loss order is set
3. internet crashes
4. I dont care, since stop loss protects me

**Comment by xmatthias** [comment]
according to https://github.com/ccxt/ccxt/issues/2889 - stoploss orders are not yet unified in ccxt.

It does work "somehow" according to https://github.com/ccxt/ccxt/issues/2499#issuecomment-379829876, which provides a sample on how to make it work, but it's going to be different per exchange at the moment ... which makes it really difficult / error-prone to work with.


would a temporary workaround be to place the stoploss order as market order (so it's guaranteed to fill)?

**Comment by xmatthias** [comment]
closing as it's implemented for binance in #1341.
