### ISSUE TITLE
Leverage is not applied in live mode(Binance)

### ISSUE THREAD

**Issue by malanchuk** [freqtrade/freqtrade#9881]
## Describe your environment

  * Operating system: Ubuntu 22.10
  * Python Version: 3.11.7 (`python -V`)
  * CCXT version:  4.2.25 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I am trying to run the bot in live mode with leverage. 

### Steps to reproduce:

  1. I added this method to my strategy class:
```
LEVERAGE = 10


class MyStrategy(IStrategy):
    ...

    def leverage(self, pair: str, current_time: datetime, current_rate: float,
                 proposed_leverage: float, max_leverage: float, entry_tag: Optional[str], side: str,
                 **kwargs) -> float:
        return LEVERAGE

```  
  2. Set configuration like that:
  ```
"max_open_trades": -1,
"stake_currency": "USDT",
"stake_amount": 10,
"tradable_balance_ratio": 0.99,
"fiat_display_currency": "USD",
"dry_run": false,
"trading_mode": "futures",
"margin_mode": "isolated",
"unfilledtimeout": {
    "entry": 10,
    "exit": 10,
    "exit_timeout_count": 0,
    "unit": "minutes"
},
"order_types": {
    "entry": "limit",
    "exit": "market",
    "emergency_exit": "market",
    "force_entry": "market",
    "force_exit": "market",
    "stoploss": "market",
    "stoploss_on_exchange": false,
    "stoploss_on_exchange_interval": 60,
    "stoploss_on_exchange_limit_ratio": 0.99
},
"entry_pricing": {
  "price_side": "other",
  "use_order_book": true,
  "order_book_top": 1,
  "price_last_balance": 0,
  "check_depth_of_market": {
    "enabled": false,
    "bids_to_ask_delta": 1
  }
},
"exit_pricing": {
    "price_side": "other",
    "use_order_book": true,
    "order_book_top": 1,
    "price_last_balance": 0
},
"exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {
            "enableRateLimit": true,
            "options": {"defaultType": "future"}
        },
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200,
            "options": {"defaultType": "future"}
        },
...
```
  3. Start the bot in docker:
```
 ...
  command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy MyStrategy 

```  
### Observed Results:

  _* What happened?_
  In backtest/dry-run mode it works fine, but in live mode - it always opens trades with no leverage(1x)
  _* What did you expect to happen?_
  Expecting that the bot will trade with specified leverage in live mode.

### Relevant code exceptions or logs

  ```
2024-02-27 21:05:23,918 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for AGIX/USDT:USDT with stake_amount: 10 ...
2024-02-27 21:05:24,661 - freqtrade.freqtradebot - INFO - Order 2017557890 was created for AGIX/USDT:USDT and status is open.
2024-02-27 21:05:26,736 - freqtrade.wallets - INFO - Wallets synced.
2024-02-27 21:05:26,742 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 20, 'type': entry, 'buy_tag': None, 'enter_tag': None, 'exchange': 'Binance', 'pair': 'A
GIX/USDT:USDT', 'leverage': 1.0, 'direction': 'Long', 'limit': 0.6673, 'open_rate': 0.6673, 'order_type': 'limit', 'stake_amount': 10.0, 'stake_currency': 'USDT', 'base_currency': 'AG
IX', 'fiat_currency': 'USD', 'amount': 14.0, 'open_date': datetime.datetime(2024, 2, 27, 21, 5, 24, 662489, tzinfo=datetime.timezone.utc), 'current_rate': 0.6673, 'sub_trade': False}
2024-02-27 21:05:42,203 - freqtrade.wallets - INFO - Wallets synced.
2024-02-27 21:05:58,777 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=20, pair=AGIX/USDT:USDT, amount=14.98576352, is_short=False, leverage=1.0, open_rate=0.66730000
, open_since=2024-02-27 21:05:24)
2024-02-27 21:05:59,033 - freqtrade.persistence.trade_model - INFO - Updating trade (id=20) ...
2024-02-27 21:05:59,033 - freqtrade.persistence.trade_model - INFO - LIMIT_BUY has been fulfilled for Trade(id=20, pair=AGIX/USDT:USDT, amount=14.00000000, is_short=False, leverage=1.
0, open_rate=0.66730000, open_since=2024-02-27 21:05:24).
2024-02-27 21:05:59,825 - freqtrade.wallets - INFO - Wallets synced.
2024-02-27 21:05:59,828 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 20, 'type': entry_fill, 'buy_tag': None, 'enter_tag': None, 'exchange': 'Binance', 'pair
': 'AGIX/USDT:USDT', 'leverage': 1.0, 'direction': 'Long', 'limit': 0.6673, 'open_rate': 0.6673, 'order_type': 'limit', 'stake_amount': 9.3422, 'stake_currency': 'USDT', 'base_currenc
y': 'AGIX', 'fiat_currency': 'USD', 'amount': 14.0, 'open_date': datetime.datetime(2024, 2, 27, 21, 5, 24, 662489, tzinfo=datetime.timezone.utc), 'current_rate': 0.6673, 'sub_trade':
False}
  ```

**Comment by stash86** [comment]
`return self.LEVERAGE`

**Comment by malanchuk** [comment]
@stash86 Thanks, but looks like the problem is not in this.
The `LEVERAGE` variable is out of class. And it works in backtest/dry-run.
I think there is something with exchange configuration or leverage tiers.

**Comment by xmatthias** [comment]
well your config is questionable at best.
using ` "options": {"defaultType": "future"}` is incorrect - and doing so might lead to odd missbehaviors with ccxt (the correct defaultType would be swap - but freqtrade does set that accordingly depending on the trading-mode selected.

Most likely - this misconfiguration caused the leverage tiers to load incorrectly - which means your min/max leverage is set to 1 (this is the default if the leverage tiers are not available).
Startup logs MAY have some information about this ... but maybe the call itself  works - just doesn't contain the information we're looking for (I've never directly / actively tested for this)

Dry-run / backtesting won't be affected by this as we need to cache this file ([binance_leverage_tiers.json](https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/exchange/binance_leverage_tiers.json)) ... but in live, we're not using this file - but instead rely on the active response to have uptodate info.

---

In the end, it'll mean that your "LEVERAGE" is not within min/max leverage - which is information for the strategy - but is enforced after.
You might also notice that for some pairs, 10x is not available - in which case freqtrade will limit your strategy to whatever is available to that pair.

**Comment by froggleston** [comment]
Most likely a GPT generated config:

![image](https://github.com/freqtrade/freqtrade/assets/1872302/3e9306d2-c9c0-449f-bc23-9fc7ac3aa88b)

**Comment by malanchuk** [comment]
@xmatthias Thanks, you're right about min/max_leverage - that helped!
