### ISSUE TITLE
FreqAI: AI Strategy with ordebook data as feature 

### ISSUE THREAD

**Issue by dilivar** [freqtrade/freqtrade#9882]
Hello Guys;
 I made a very long and deep research to find out how to add orderbook data into AI based freqAI strategy as feature and/or label. Unfortunately I could manage to run the AI strategy with orderbook data.
  Does anybody share the opinion about possibility of creating an AI strategy with orderbook data?

Cheers
Fatih

**Comment by xmatthias** [comment]
Your big problem will be the (non) availability of historic orderbook data.
Uptodate orderbook data is outdated the moment you look at it (it's changing every other ms if you observe it carefully). 
You can use that  (it's an active call to the exchange) - but it's not really suitable to train a model, or to be used in backtesting.


Exchanges don't provide this data in a "historical" fashion ... so effectively, it means that you'll need to collect this data (snapshot every few ms, or whatever ganularity, over the whole training period) ... which will be rather huge data very quickly - which you'll then need to handle accordingly.

logistically, that's not a trivial problem - and not one we aim to provide a solution for in the context of freqtrade, at least not in the foreseeable future.

You're obviously free to develop something as part of your strategy/model - but it's not builtin / provided.
