### ISSUE TITLE
How do I view statistics in telegram?

### ISSUE THREAD

**Issue by rr8733380** [freqtrade/freqtrade#9884]
How can I use the telegram bot to view the number of open shorts and long positions for all time? I need to find out how often my algorithm opens short or long positions

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Luckily, we do have a good [documentation](https://www.freqtrade.io/en/stable/telegram-usage/#telegram-commands) which explains the different commands available.
No command in the "status" or "Metrics" section does modify stuff - so they're made to be tried out.

If in doubt - there's also a `/help` command - which will explain contain information on available commands.
