### ISSUE TITLE
Can not plot using the docker

### ISSUE THREAD

**Issue by SamiWada** [freqtrade/freqtrade#9887]
## Describe your environment

  * Operating system: Ubuntu 20.04.6 LTS
  * Python Version: 3.11.7
  * CCXT version: 4.2.47
  * Freqtrade Version: 2024.1
  
## Your question

Hello,
I've been using Freqtrade successfully for backtesting with the default strategy provided. However, I've encountered an issue when attempting to use the plotting functionality to visualize trade entry and exit points on price charts. Despite following the documented steps and ensuring my setup matches recommended configurations, no output file is generated when I run the plot command.
i'm using the stable version of the freqtrade docker image.
here the configuration of the plot container:
```
freqtrade-Plot:    
    image: freqtradeorg/freqtrade:stable_plot
    restart: "no"
    container_name: freqtrade-Plot
    volumes:
      - "/home/freqdock/ft_userdata/user_data:/user_data"
    command: >
      plot-dataframe
        --timerange 20220101-20240101
        --timeframe '1d'        
        --strategy SampleStrategy
        --config "/user_data/configs/backtest/config_static_pair_spot.json"
        --strategy-path "/user_data/strategies/samples"        
        --userdir "/user_data/"
        --pairs 'BTC/USDT'        
        --logfile '/user_data/logs/plot_samples.log'        
        -vv
```

Please find attached the log files for each step : download data , backetesting and plotting.
Could you please provide guidance on resolving this issue or suggest any additional steps I might take to diagnose the problem further?

Thank you,
[download_data.log](https://github.com/freqtrade/freqtrade/files/14450725/download_data.log)
[backtesting.log](https://github.com/freqtrade/freqtrade/files/14450726/backtesting.log)
[plot_samples.log](https://github.com/freqtrade/freqtrade/files/14450727/plot_samples.log)

**Comment by xmatthias** [comment]
well the error is quite clear - there is no data found for plotting.

My best bet is that you've messed up your config somehow (while the plot container per se will work as is - we don't know how your mount points for downloading data are - so the most likely reason is that you're either missing the mount - or have the mount point wrong when downloading data.


---

In general, i'd recommend to use `run`  for such commands - and only really configure the container command for the actual trade mode.
that will avoid issues like this - as you're always using the same configuration. 

[example for backtesting](https://www.freqtrade.io/en/latest/docker_quickstart/#example-backtest-with-docker) ... but you can do the same for all other commands - the only one where this is not recommended is for trade mode - which should be properly configured, and started with `docker compose up -d`.


---

At any rate - i think using freqUI will serve you better. It's a more interactive approach to this (including backtesting).
you should be able to start that via `docker compose run --rm -p 8080:8080 freqtrade-Plot  webserver` (with the assumption that according webserver config exists) - and can then access the UI - which will have a backtesting and plotting tab. (you can also load existing backtests - and look at the results incl. charts interactively there).

**Comment by SamiWada** [comment]
Thank you so much for your response. Ok i will check again the data path but for me is ok because i use the same config file for the backtesting and plot. And i will try freqUI for this because it's already configured.

**Comment by xmatthias** [comment]
well all i can do is read the available logs - which quite clearly say "no data found" :)

**Comment by SamiWada** [comment]
The problem is resolved when i removed the '--data-format-ohlcv json ' from the download data and from the backtesting container: use the default format 'feather'. i think the plot-dataframe use the default format and can find the data now (i didn't change anything in the config file.

**Comment by xmatthias** [comment]
well now in fairness, if it's not given (either through cli or configuration), then all commands default to feather (which has benefits in both speed and size).
