### ISSUE TITLE
How to update to version 2024.2?

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#9891]
## Describe your environment

  * Operating system: ubuntu 20.04.6
  * Python Version: 3.8.10
  * CCXT version: 4.2.25
  * Freqtrade Version: 2024.1
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

I previously used the following method to update to version 2024.1, but today when I tried to update to version 2024.2, it seems that the update was not successful. 

```
➜  ~ cd /root/ft_userdata
➜  ft_userdata docker-compose pull 
[+] Pulling 1/1
 ✔ freqtrade Pulled                                                                                                                                                 2.1s 
➜  ft_userdata docker-compose up -d  
[+] Running 1/0
 ✔ Container freqtrade  Running                                                                                                                                     0.0s 
➜  ft_userdata 
```

When I checked the current version on Telegram, it indicated version 2024.1.

```
/version
Version: 2024.1
```

**Comment by xmatthias** [comment]
Great spot, seems like the stable CI didn't properly finish with a random error setting up docker ... 
It's re-running right now - and should finish in about half an hour - after which you should be able to update using this method.
(you can follow the process here: https://github.com/freqtrade/freqtrade/actions/runs/8091566412 - once it's green, your update process should work).

I'll also close this issue once that process completes.

---

Seems like you've got `:stable` in your docker-file ... which should update using this method.
An alternative would be to pin the exact version using the version as tag (e.g. `:2024.2`) - but that'll not update this way, but will require an explicit change to the docker compose file to actually update.

**Comment by WinPoss** [comment]
Great work rate, you are awesome.

**Comment by xmatthias** [comment]
`:stable` images are now uptodate, too.

Thanks for reporting :+1:
