### ISSUE TITLE
Parameters: { "task_type" } are not used.

### ISSUE THREAD

**Issue by BangyuanX** [freqtrade/freqtrade#9894]
## Describe your environment

  * Operating system: Windows Docker
  * Python Version: _____ 
  * CCXT version: _____
  * Freqtrade Version: docker-2024.3-dev-f8cc2a6e

## Describe the problem:
I'm new to the FreqAI and still keep learning it. 
I've already set the task_type parameter to 'gpu' in the config file. When I run the bot, it said the parameter was not working. I also checked my cpu & gpu running status and the cpu is fully occupied and gpu is not working at the moment.

Here is the configuration.
```
"model_training_parameters": {
    "n_jobs": 10,
    "verbosity": 1,
    "task_type": "gpu"
}
```

The logs are attached in the followings.
```
reqtrade  | 2024-03-03 04:01:23,765 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': 'Using Protections: \nCooldownPeriod - Cooldown period of 4 candles.\nMaxDrawdown - Max drawdown protection, stop trading if drawdown is > 0.2 within 48 candles.'}
freqtrade  | 2024-03-03 04:01:30,032 - freqtrade.freqai.data_kitchen - INFO - dropped 52 of 999 prediction data points due to NaNs.
freqtrade  | 2024-03-03 04:01:33,698 - freqtrade.freqai.data_kitchen - INFO - dropped 52 of 999 prediction data points due to NaNs.
freqtrade  | 2024-03-03 04:01:34,448 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-2024.3-dev-f8cc2a6e', state='RUNNING'
freqtrade  | 2024-03-03 04:01:36,261 - freqtrade.freqai.base_models.BaseRegressionModel - INFO - -------------------- Starting training ETH/USDT:USDT --------------------
freqtrade  | 2024-03-03 04:01:36,372 - freqtrade.freqai.data_kitchen - INFO - ETH/USDT:USDT: dropped 2 training points due to NaNs in populated dataset 3931.
freqtrade  | 2024-03-03 04:01:36,373 - freqtrade.freqai.base_models.BaseRegressionModel - INFO - -------------------- Training on data from 2024-02-18 to 2024-03-03 --------------------   
freqtrade  | 2024-03-03 04:01:37,060 - uvicorn.error - INFO - ('172.21.0.1', 51398) - "WebSocket /api/v1/message/ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eSI6eyJ1IjoiZnJlcXRyYWRlciJ9LCJleHAiOjE3MDk0MzkzOTYsImlhdCI6MTcwOTQzODQ5NiwidHlwZSI6ImFjY2VzcyJ9.zXb8lQmXR2jJRfZu09JOYytL4i-TyUSTp36zNb00CY4" [accepted]
freqtrade  | 2024-03-03 04:01:37,061 - freqtrade.rpc.api_server.ws.channel - INFO - Connected to channel - WebSocketChannel(7bbc5c35, ('172.21.0.1', 51398))
freqtrade  | 2024-03-03 04:01:37,062 - uvicorn.error - INFO - connection open
freqtrade  | 2024-03-03 04:01:39,470 - freqtrade.freqai.base_models.BaseRegressionModel - INFO - Training model on 3266 features
freqtrade  | 2024-03-03 04:01:39,471 - freqtrade.freqai.base_models.BaseRegressionModel - INFO - Training model on 3929 data points
freqtrade  | [04:01:40] WARNING: /workspace/src/learner.cc:742: 
freqtrade  | Parameters: { "task_type" } are not used.
```

Did I set up this correctly? Let me know if you need to more information to debug this issue. Thanks a lot!

**Comment by xmatthias** [comment]
Support (or lack thereof) will depend on the acutal model used - which i don't really see mentioned.

Essentially the same applies to the actual setting (which is a warning only) - which simply tells you "this model doesn't use this".
Most likely, the model selected won't support this key - or will require a different parameter to enable GPU support.
Details for this are (intentionally) kept out of the freqtrade documentation - as that's model specifics which might become outdated with new versions.
There' showever links to each model's documentation [in the prediction model section](https://www.freqtrade.io/en/latest/freqai-configuration/#using-different-prediction-models).

**Comment by robcaulk** [comment]
Please review the parameter table, where we describe how `model_training_parameters` is a flexible dictionary that adopts any paramter for the library **you** chose.

https://www.freqtrade.io/en/stable/freqai-parameter-table/#model-training-parameters

**you** chose to use a library that doesnt support a parameter called `task_type`.
