### ISSUE TITLE
Using `custom_stoploss` to implement ATR based Risk on Reward

### ISSUE THREAD

**Issue by elja** [freqtrade/freqtrade#9895]
## Describe your environment

  * Operating system: Apple M1
  * Python Version:  3.11.1
  * CCXT version: 4.2.51
  * Freqtrade Version: 2024.2
  
## Your question

I'm building a simple Risk on Reward strategy using ATR on trade open to set stoploss and a takeprofit based on the stoploss risk. I'm planning to use it to short / long with leverage. I understand that `custom_stoploss` works as a trailing from `current_rate`, but I'm quite confused about what is the best practice to get ATR values from the trade open candle. There is an example of R:R strategy (long only) [here](https://github.com/freqtrade/freqtrade-strategies/blob/main/user_data/strategies/FixedRiskRewardLoss.py). 

So to take an ATR value from the open candle it seems like we can use this approach: 

```
def custom_stoploss(self, pair: str, trade: Trade, current_time: datetime,
                        current_rate: float, current_profit: float, after_fill: bool,
                        **kwargs) -> Optional[float]:
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
        open_trade_candle = dataframe.loc[dataframe['date'] == trade_date]
        
        if open_trade_candle.empty:
           open_trade_candle = open_trade_candle.squeeze()
           
       open_trade_candle['atr']  # here we go
```
can you be sure you can always access Open Candle and read ATR values even if the trade is taking many many days? 
Another approach is to use of custom `Dict` defined in the strategy:

```
custom_stoploss_meta = {}

def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        ...
        # saving custom stoploss rates for later use
        self.custom_stoploss_meta[metadata['pair']] = dataframe[
            ['date', 'abs_stoploss_long', 'abs_stoploss_short']
        ].copy().set_index('date')
       ...
       
def custom_stoploss(self, pair: str, trade: Trade, current_time: datetime,
                        current_rate: float, current_profit: float, after_fill: bool,
                        **kwargs) -> Optional[float]:
        resulting_sl = takeprofit_sl = -1
        curr_stoploss_info = self.custom_stoploss_meta.get(pair)

        if curr_stoploss_info is not None:
            trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc)
            open_date_mask = curr_stoploss_info.index.unique().get_loc(trade_date, method='ffill')
            open_df = curr_stoploss_info.iloc[open_date_mask]

            # trade might be open too long for us to find an opening candle
            if len(open_df) != 1:
                return -1  # won't update the current stoploss as it's lower then the latest one

            if trade.is_short:
                initial_sl_abs = min(open_df['stoploss_short'], max_stoploss_short_abs)
            else:
                initial_sl_abs = max(open_df['stoploss_long'], max_stoploss_long_abs)
    
        ...        
```
Can anyone recommend this approach, will it work well in backtest/dry-run/live? What is a best practice here? Also, the documentation isn't obvious, I tried to understand this line:
> E.g. current_profit = 0.05 (5% profit) - stoploss returns 0.02 - then you "locked in" a profit of 3% (0.05 - 0.02 = 0.03).
I'm having a hard time understanding what value should `custom_stoploss` function return:

- can it be negative or positive? based on the documentation example it may seem that it can be positive, but then the example doesn't make sense, as 0.02 should result in an immediate position close (stop loss 2% above a current rate)
- probably in the documentation it should be written as '_stoploss returns -0.02_'), then yeah if your current_profit is 5% then 2% below current_rate will result from a lock-in of 3+% of profit.

So for the example in the documentation, if `custom_stoploss` returns 0.02 I thought it would mean immediate trade close, shouldn't it be -0.02 instead? An example that goes right below where stop loss returned = -0.04 (4%) makes more sense than the text above it.

**Comment by xmatthias** [comment]
Custom stoploss values are sign independent - so `0.02` and `-0.02` means the same thing - 2% below the current price (below for long, above for shorts).

you can't have the stop at the other side - as then it'd have triggered already, which in many cases, would result in a failure in placing stoploss on exchange (almost no exchange allows this).

---

Neither of your approaches do guarantee that the value is available at all times.
You can rely on `dp.get_analyzed_dataframe()` for the most part (though it can be empty right after startup) - but it can also lead to the opening candle if you're working with long open trade times (more than 1000 candles on your main timeframe, usually).

You can work around this (to some degree) by using `startup_candle_count` (which can extend the available candles to up to 5x the initial call) - but trade "open dates" can still age out eventually (though i'd say it's pretty uncommon to have a trade open for 3 days on 1m timeframes).


your "dict" approach has several problems - first off, the fact that you're overwriting it on every iteration leads to the same problem than above - as it can age out just the same.
the dict is also not persisted, so it'll be empty after a bot restart.


Neither is a problem necessarily - but something you need to be aware of and have appropriate fallbacks in place.

**Comment by stash86** [comment]
I'll write a blog.post about this, and I will link it here. Currently I'm working with ATR on my strat

**Comment by xmatthias** [comment]
I think this is less about ATR per se - but more about "how to access values from the trade open date".

i think #6908  could help on that - as that'll ensure the data is kept in place.

**Comment by elja** [comment]
Oh, that was quick @xmatthias, thanks for the guidance. @stash86 looking forward to seeing your post.

**Comment by stash86** [comment]
https://botacademy.ddns.net/2024/03/04/fsd-how-to-use-atr-for-exits-roi-and-stoploss/

As long as your trade isn't opened for too long, even if the bot restarted, it should be able to re-calculate the ATR levels (and any other indicators that you might need)

**Comment by elja** [comment]
Hey @stash86, thanks for sharing.

I have a question, I see you `current_candle['close']` instead of `current_rate`, can you explain why?
```
dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
current_candle = dataframe.iloc[-1].squeeze()
current_candle['close']
```

**Comment by stash86** [comment]
well, read the post in full. I explained the reason there.

**Comment by elja** [comment]
> well, read the post in full. I explained the reason there.

gotcha, it's in separate article: https://botacademy.ddns.net/2023/07/09/backtest-traps-custom-exit/

**Comment by elja** [comment]
> well, read the post in full. I explained the reason there.

but how about that? https://www.freqtrade.io/en/stable/backtesting/#improved-backtest-accuracy
you seem to be able to use a lower timeframe to simulate a price movement, so the `current_rate` should change, isn't it?

**Comment by stash86** [comment]
I have addressed it in the backtest trap post. Please read in detail

**Comment by elja** [comment]
> I have addressed it in the backtest trap post. Please read in detail

it's quite hard to understand why using `close` instead of `open` is any better, generally highs and lows might be pretty far away from close so using [improved-backtest-accuracy](https://www.freqtrade.io/en/stable/backtesting/#improved-backtest-accuracy) seem to be better because lows and highs will hit your strategy methods.
