### ISSUE TITLE
Docker file inside Dockge on archlinux : can't start

### ISSUE THREAD

**Issue by abda11ah** [freqtrade/freqtrade#9909]
Hello,
I tried to run the docker-compose.yml file inside Dockge because I find it a very convenient interface to start and stop containers (like portainer but minimalist).
So I pasted the contents of the docker-compose.yml file and it downloaded the container image correctly, but then it can't start it because it can't find the config.json file :

```
freqtrade  | 2024-03-04 18:30:38,964 - freqtrade - INFO - freqtrade 2024.2
freqtrade  | 2024-03-04 18:30:39,541 - freqtrade.worker - INFO - Starting worker 2024.2
freqtrade  | 2024-03-04 18:30:39,541 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/config.json ...
freqtrade  | 2024-03-04 18:30:39,541 - freqtrade.commands.trade_commands - ERROR - Config file "/freqtrade/user_data/config.json" not found! Please create a config file or check whether it exists.
freqtrade  | 2024-03-04 18:30:39,542 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/configuration/load_config.py", line 61, in load_config_file
freqtrade  |     with Path(path).open() if path != '-' else sys.stdin as file:
freqtrade  |          ^^^^^^^^^^^^^^^^^
freqtrade  |   File "/usr/local/lib/python3.11/pathlib.py", line 1044, in open
freqtrade  |     return io.open(self, mode, buffering, encoding, errors, newline)
freqtrade  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  | FileNotFoundError: [Errno 2] No such file or directory: '/freqtrade/user_data/config.json'
freqtrade  | 
freqtrade  | During handling of the above exception, another exception occurred:
freqtrade  | 
freqtrade  | Traceback (most recent call last):
freqtrade  |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
freqtrade  |     worker = Worker(args)
freqtrade  |              ^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 37, in __init__
freqtrade  |     self._init(False)
freqtrade  |   File "/freqtrade/freqtrade/worker.py", line 50, in _init
freqtrade  |     self._config = Configuration(self._args, None).get_config()
freqtrade  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/configuration/configuration.py", line 42, in get_config
freqtrade  |     self.config = self.load_config()
freqtrade  |                   ^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/configuration/configuration.py", line 68, in load_config
freqtrade  |     config: Config = load_from_files(self.args.get("config", []))
freqtrade  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/configuration/load_config.py", line 102, in load_from_files
freqtrade  |     config_tmp = load_config_file(str(file))
freqtrade  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
freqtrade  |   File "/freqtrade/freqtrade/configuration/load_config.py", line 64, in load_config_file
freqtrade  |     raise OperationalException(
freqtrade  | freqtrade.exceptions.OperationalException: Config file "/freqtrade/user_data/config.json" not found! Please create a config file or check whether it exists.
freqtrade exited with code 0
```

Then I tried the classic method to generate the config.json file and it worked, but the problem is that now the freqtrade container doesn't appear in the Dockge interface.
I even retrieved the config.json file and then moved it to the /opt/stacks/freqtrade/user_data/ folder, but the container still reports the config.json file not found error.

Have you managed to get freqtrade working inside Dockge?
If so, what changes do you need to make to the docker-compose.yml file to get it working? I confess I'm at a loss as to what to do.

**Comment by xmatthias** [comment]
The error is rather clear - the config file is missing / nonexistant.
The expectation is that the whole user_data directory is mounted (that's the default). 
While not an absolute neccessity (you can do partial / split mounts eventually) - it's a non-standard setup - but from what i understand, not what you're using, anyway.

Why this is with your custom setup is beyond me. We do support instructions for docker compose - which i know work. If you need help with that - please let us know.
I'm however unable (and also unwilling if i'm honest) to research what you're doing wrong in a tool i've never heared of - letalone used.

as such - please try to run freqtrade using the regular `docker compose` commands.


---

if that works - feel free to give any management tool a try if you're familiar with these - but please understand that we'll not be able to support you in this journey - and if you're encountering problems - our answer will be "please use the understood / documented way".
If you do need support with any other tools, please use appropriate channels (i assume in your case whatever channel you can get for "dockge".

**Comment by abda11ah** [comment]
I finally used the classic method to generate the json configuration file and the user_data folder tree. I then moved all these folders into the user_data folder generated by Dockge and it worked.
