### ISSUE TITLE
Does this support tradeogre?

### ISSUE THREAD

**Issue by Miner1305** [freqtrade/freqtrade#991]
Does this support tradeogre?

**Comment by xmatthias** [comment]
officially we currently support bittrex and binance.

in theory, most exchanges supported by ccxt should work.

tradeogre does not seem to be working in ccxt yet (see https://github.com/ccxt/ccxt/issues/2150).

**Comment by rafa-br34** [comment]
Anything new in terms of support?

**Comment by xmatthias** [comment]
give it a try? it's in ccxt now - though we didn't test against it, and you're almost certainly the first to give it a try.

In theory, freqtrade supports every exchange ccxt supports, which would also include this exchange.

We have a rough guideline on things to check in the [contributors section of the documentation](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip).
While it's probably not complete, it should give you a good idea if the exchange will work for spot trading.

If you encounter specific problems, we're happy to assist up to a certain point - but the expectation for new exchanges is that the user interested is doing the legwork / most of the testing work - which also assumes a somewhat familiarity with python / testing/debugging things in python.

If you're new to python / development - you're almost certainly better of with one of the supported exchanges.

**Comment by rafa-br34** [comment]
I'm getting
```
Traceback (most recent call last):
  File "freqtrade\main.py", line 47, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "freqtrade\commands\trade_commands.py", line 24, in start_trading
    worker = Worker(args)
             ^^^^^^^^^^^^
  File "freqtrade\worker.py", line 39, in __init__
    self._init(False)
  File "freqtrade\worker.py", line 55, in _init
    self.freqtrade = FreqtradeBot(self._config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "freqtrade\freqtradebot.py", line 103, in __init__
    self.exchange = ExchangeResolver.load_exchange(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "freqtrade\resolvers\exchange_resolver.py", line 58, in load_exchange
    exchange = Exchange(
               ^^^^^^^^^
  File "freqtrade\exchange\exchange.py", line 291, in __init__
    self.required_candle_call_count = self.validate_required_startup_candles(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "freqtrade\exchange\exchange.py", line 830, in validate_required_startup_candles
    candle_limit = self.ohlcv_candle_limit(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "freqtrade\exchange\exchange.py", line 471, in ohlcv_candle_limit
    ccxt_val = self.features(
               ^^^^^^^^^^^^^^
  File "freqtrade\exchange\exchange.py", line 914, in features
    return feat.get(endpoint, {}).get(attribute, default)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```
After some debugging, it turns out that the first `get` returns a `None` instead of the default empty dict.
Output from `print(feat, endpoint, feat.get(endpoint, {}))`.
```
{'sandbox': False, 'createOrder': {'marginMode': False, 'triggerPrice': False, 'triggerDirection': False, 'triggerPriceType': None, 'stopLossPrice': False, 'takeProfitPrice': False, 'attachedStopLossTakeProfit': None, 'timeInForce': {'IOC': False, 'FOK': False, 'PO': False, 'GTD': False, 'GTC': True}, 'hedged': False, 'trailing': False, 'leverage': False, 'marketBuyByCost': False, 'marketBuyRequiresPrice': False, 'selfTradePrevention': False, 'iceberg': False, 'stopLoss': None, 'takeProfit': None, 'symbolRequired': True}, 'createOrders': None, 'fetchMyTrades': None, 'fetchOrder': {'marginMode': False, 'trigger': False, 'trailing': False, 'symbolRequired': False}, 'fetchOpenOrders': {'marginMode': False, 'limit': None, 'trigger': False, 'trailing': False, 'symbolRequired': False}, 'fetchOrders': None, 'fetchClosedOrders': None, 'fetchOHLCV': None} fetchOHLCV None
```
I don't know if this is a bug or if I'm just being stupid (likely the latter).

**Comment by xmatthias** [comment]
this would point out to either an old ccxt version - or a non-default implementation of features from ccxt.

At any rate - an issue that's 7 (!) years old is NOT the right place to discuss such a thing.
