### ISSUE TITLE
Import freqtrade library to python

### ISSUE THREAD

**Issue by christrt9** [freqtrade/freqtrade#9913]
## Describe your environment

  * Operating system: Ubuntu 22.04
  * Python Version: Python 3.10.12  (`python -V`)
  * CCXT version:  ccxt==4.1.95  (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2023.11  (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I want to use python to download data and use it like library instead of Bash commands

Example:

I want to have python script to run this commands with out exec or use freqtrade cli

```
freqtrade download-data

freqtrade backtesting
```

**Comment by xmatthias** [comment]
While it's possible in theory and practice (in python, you can import anything) - this is not a usecase we do support, and hence will also not provide guidance as to how to get it working (you're obviously free to discover it yourself - but please consider it as not supported).

Freqtrade internals (what you don't find in the documentation) may change at any time and is not considered as interface (something we keep stable to not break user's usecses) - so it can change at any time - without mention in any changelog or whatnot.

**Comment by froggleston** [comment]
You might like to check out my [jupyter notebook](https://github.com/froggleston/freqtrade_analysis_notebook) as it does use freqtrade functions in this way, but as xmatthias says, it is not officially supported and it's not without its difficulties and issues with implementation.
