### ISSUE TITLE
frequi why charts no show candles?

### ISSUE THREAD

**Issue by ExpressGit** [freqtrade/freqtrade#9918]
## Describe your environment

  * Operating system: centos7
  * Python Version: ___python3.7__ (`python -V`)
  * CCXT version: __4.2.58___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __V1.2.5__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## why charts no show candles?

![image](https://github.com/freqtrade/freqtrade/assets/11694747/e779afe1-6d45-410f-995a-ff5bf3374676)

but i have already downlaod data 

![image](https://github.com/freqtrade/freqtrade/assets/11694747/30f3318f-1689-45d6-890f-004460389e89)

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
Stored data is irrelevant in the "Trade" page of freqUI (the one you're looking at).

It'll use live data - which is however only available if the bot is actually running in trade mode - and if the strategy returns valid dataframes.
Bot backend logs MAY have some details as to why you're not seeing any data - which is however usually either right after startup (no data available yet) - or with a faulty strategy that's not returning a proper dataframe.
