### ISSUE TITLE
Thank you, Freqtrade team! This is awesome! 😍👏 I have used Freqtrade for over a year, and it's the best. Literally, everything is there for you. Good job to everybody! 🎉🔥🎊

### ISSUE THREAD

**Issue by keithorange** [freqtrade/freqtrade#9920]
Thank you, Freqtrade team! This is awesome! 😍👏 I have used Freqtrade for over a year, and it's the best. Literally, everything is there for you. Good job to everybody! 🎉🔥🎊

**Comment by xmatthias** [comment]
Thanks a lot for the postive feedback :100: 
most of the times, we only hear about problems - not from happy users :laughing:
