### ISSUE TITLE
recurent gate.io warning message about funding fees

### ISSUE THREAD

**Issue by macsim26** [freqtrade/freqtrade#9924]
## Describe your environment

  * Operating system: ____ubuntu 22.04
  * Python Version: _____ 3.10
  * CCXT version: _____4.2.51
  * Freqtrade Version: ____ 2024.2
  
## Your question

Hello on gate.io i have a recurent message : 
freqtrade.exchange.common - WARNING - _get_funding_fees_from_exchange() returned exception: "Could not get funding fees due to BadRequest. Message: gateio {"label":"INVALID_PARAM_VALUE","message":"Invalid request parameter from value: 1710063370.0"}". Giving up.
2024-03-10 11:31:10,078 - freqtrade.exchange.exchange - WARNING - Could not update funding fees for TIA/USDT:USDT.  
I don't know if it's an error in my config and if it's important because the bot in live seems to handle trades normaly? 
I have exactly the same config with Bybit and everything is running fine.. 
Thanks

**Comment by xmatthias** [comment]
Seems to be a bug in ccxt ... can't fetch funding_fees at all at the moment.
This did work - and the relevant code wasn't really changed ... so i'm pretty sure that handling on the exchange has changed.

opened https://github.com/ccxt/ccxt/issues/21651 - will close this once we bump the version past the fix on develop.

**Comment by macsim26** [comment]
Thanks...
Must i stop the bot in live or can i let it handle the trades without
funding fees?

**Comment by xmatthias** [comment]
it should be ok for the most part - though be prepared to have results slightly off (could go in both directions, really, depending on the trade direction, and funding-fee sign).

**Comment by macsim26** [comment]
Hi i have just put it in live and everything seems ok...
I'm ashamed to report bugs on Sundays every time!!!
Thanks a lot again for your reactivity...
Miguel

**Comment by xmatthias** [comment]
> I'm ashamed to report bugs on Sundays every time!!!

it's not like a bug on monday or wednesday is better :rofl:  so don't worry
