### ISSUE TITLE
Future calculations for each indicator

### ISSUE THREAD

**Issue by MrGalacticClouds** [freqtrade/freqtrade#9948]
A table for each indicator that would contain few(5-10?) future calculations of each indicator that gona be based on current candle ( good and enought for me). But it could be more complicated and even have something done with ai.

Could be something like
dataframe[ema10].futureview(0) # if howmanycandlessinfuture=10  then it would be 10th in future
Im learning python by using this project so it gonna take some time for me to do it by myself, idea isnt bad so if someone would do it ealier that would be nice :)

variables 
howmanycandlessinfuture=10 # how many calculations in future. Work for every indicator. If >0 make calculations if 0 then not. 
futureviewshow=true #to see or not the future ones on charts
futureviewuse=true #to use it or not in signals, if true future ones arent substracted after calculations just copied

in indicator calculations add this 10 to x candles 
if there are no candle for next calculations take last candle
at end substract last 10 to futureview table

Hopefully You gonna understand me :)
Thank You all for creating this project :)

**Comment by xmatthias** [comment]
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

> Hopefully You gonna understand me :)

No, not really (i think the below is based on lack of understanding - either from me understanding your question - or viceversa - you understanding how time works).


If you think about what you just said - you'd essentially look into the future.
You take "now's" candle (say, it's 10:00) - and calculate "what's going to be in 2 hours" (so what's at 12:00).
Weather forecasts TRY to do that - but you'll still leave work every now and then with a surprised rain shower that wasn't on the forecast.

If this were possible in financial markets - i'd be VERY rich (among many others)  ... but it ain't - as it'd involve timetravel (sorry, freqtrade does not support time machines at this point, nor do we have immediate plans to do so).

you can TRY to predict the future (this is what a strategy does - essentially) - try to guess the direction of the market in the near term future - but it is and will remain a guess.

**Comment by stash86** [comment]
or you can use freqai and let the model predict the future, which still has the same issue which is it's still a guess

**Comment by MrGalacticClouds** [comment]
At simple explenation
If i have 120 candles of 1m data, and this data starts at 10:00 and ends at 11:59 (h:m), and I want to have 5 candles calculations in future. So i want to have calculations till 12:04(not candles, just calculations). 

As You going to have not very usefull data on rsi etc., on things like ma/ema/bband You going to have more "accurate" data that You can use for better future predictions. 
Now when You calculate last data, You calculate only last candle and its indicators. With this idea You calculate indicators for last and 5 future ones. Its not going to be 100% accurate with reality, but going to bring better view on some price moves. 

Just when " indicator calculator" run off the existing data, then You add/use there 5 ghost candles based on last one with future time based on interval(12:00;12:01;12:02;12:03,12:04)(only for calculations). 
So candle data stay the same but there already are  "future" calculations for 5 next candles in data.

I see it very usefull for exits, atleast :)
Maybe I have some lack of knowlege but this... sarcasm? its not good for nice flow in comunication :)

**Comment by stash86** [comment]
No, it's not sarcasm. We are asking the real question, how can you predict the future candles? You don't even know what the price would be the next candle, how can you predict the indicators?

**Comment by stash86** [comment]
Since you don't like sarcasm, let me put it bluntly. What you ask is unrealistic. Such "feature" won't be entertained, even for a discussion.

Please do manual trading first, then see if you can really make a future indicators calculation that can at least be 75% accurate.

**Comment by MrGalacticClouds** [comment]
So based on my example.
Ema 120 calculations
11:59(now) - used all candles for calculations
12:00(future 1m) - used last 119 candles with last one 2 times
12:01(future 2m) - used last 118 candles with last one 3 times
12:02(future 3m) - used last 117 candles with last one 4 times
12:03(future 4m) - used last 116 candles with last one 5 times
12:04(future 5m) - used last 115 candles with last one 6 times
Its more like bit a look in possible future based on last data.

**Comment by stash86** [comment]
You can already do such "trick" by playing around with the dataframe. Learn pandas if you really want it. We won't implement such feature.

**Comment by MrGalacticClouds** [comment]
Ok, thank You for Your time :)

**Comment by xmatthias** [comment]
well copying the last candle X times will not get you anywhere - as that's the most unrealistic scenario (you'll never see 5 candles exactly repeated in a row - not if there was ANY price movements / volume on that pair).

All calculations based on this would therefore tell you nothing - not even a remote direction.
