### ISSUE TITLE
freqUI logon issue: Won't accept credentials from config.json

### ISSUE THREAD

**Issue by k0ushal** [freqtrade/freqtrade#9949]
## Describe your environment

  * Operating system: Mac OS
  * Python Version: 3.11.8 (`python -V`)
  * CCXT version: 4.2.51 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.2 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

I'm using the docker images on Mac OS. I created a new config file and verified that the same config file is being used in the docker-compose.yml. Here's my config:
```
{
    "max_open_trades": 5,
    "stake_currency": "EUR",
    "stake_amount": 100,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "EUR",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
        ],
        "pair_blacklist": [
            "BNB/.*"
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": false,
        "token": "",
        "chat_id": ""
    },
    "api_server": {
        "enabled": true,
        "listen_ip_address": "127.0.0.1",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
        "jwt_secret_key": "6fc68e2c3e58c22d1210d4ecaba1f50b8f5032a82f0ed90e94dbe8d86e3d40ee",
        "ws_token": "6V1458iABJSlHtUcsdENyG05xlWmE6He_g",
        "CORS_origins": [],
        "username": "admin",
        "password": "admin"
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```
After the config.json was created as per the installation steps, I've only changed the username and password to `admin` in it.
The container instance is running and when I try to access `http://localhost:8080`, I do see the logon prompt.
However the credentials of `admin / admin` aren't accepted. I don't get any error message but I don't see the freq UI either.
It only prompts me to enter the credentials again.
I've also `exec'd` into the running container instance and verified that the config.json file is the same that I created with the credentials set to `admin / admin`.

Can anyone tell what's going wrong here? 

There are no logon error logs generated either. All the other logs are displayed correctly.

**Comment by stash86** [comment]
Your API config is wrong. Read this

https://www.freqtrade.io/en/stable/rest-api/#configuration-with-docker

**Comment by k0ushal** [comment]
My docker-compose already had this:
```
    ports:
      - "127.0.0.1:8080:8080"
```
Only the `listen_ip_address` was incorrectly set in the config file.
Changed it to `"0.0.0.0"` but the issue persists.

**Comment by stash86** [comment]
try restart the docker container

**Comment by k0ushal** [comment]
I did that ofcourse after changing the config file.
Tried again anyway.
Still the same.

**Comment by k0ushal** [comment]
You would not believe what was wrong.
I had VLC player open on the side and it was using the same port of 8080. I wasn't connecting to FreqUI's page in the first place.
Although I did expect some errors to be thrown while starting the docker container if the port is already in use by another application.

Anyway, appreciate your help.
Cheers

**Comment by stash86** [comment]
paste the full startup logs
