### ISSUE TITLE
Cannot create new config

### ISSUE THREAD

**Issue by oti5** [freqtrade/freqtrade#9954]
## Describe your environment

  * Operating system: Ubuntu MATE 22.04.4
  * Python Version: Python 3.10.12 (`python -V`)
  * CCXT version: 4.2.51 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.2 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. write ```freqrtrade new-config```
  2. config an new config, write some important information e.g for telegram bot
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2024-03-15 13:57:05,342 - freqtrade - INFO - freqtrade 2024.2
? Do you want to enable Dry-run (simulated trades)? Yes
? Please insert your stake currency: USDT
? Please insert your stake amount (Number or 'unlimited'): 100
? Please insert max_open_trades (Integer or -1 for unlimited open trades): -1
? Time Have the strategy define timeframe.
? Please insert your display Currency (for reporting): USD
? Select exchange other
? Type your exchange name (Must be supported by ccxt) coinex
? Do you want to enable Telegram? Yes
? Insert Telegram token **********************************************
? Insert Telegram chat id *********
? Do you want to enable the Rest API (includes FreqUI)? Yes
? Insert Api server Listen Address (0.0.0.0 for docker, otherwise best left untouched) 127.0.0.1
? Insert api-server username freqtrader
? Insert api-server password
2024-03-15 13:57:52,521 - freqtrade.commands.build_config_commands - INFO - Writing config to `config.json`.
2024-03-15 13:57:52,521 - freqtrade.commands.build_config_commands - INFO - Please make sure to check the configuration contents and adjust settings to your needs.
2024-03-15 13:57:52,521 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/opt/freqtrade/freqtrade/commands/build_config_commands.py", line 266, in start_new_config
    deploy_new_config(config_path, selections)
  File "/opt/freqtrade/freqtrade/commands/build_config_commands.py", line 246, in deploy_new_config
    config_path.write_text(config_text)
  File "/usr/lib/python3.10/pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: 'config.json'

  ```

**Comment by xmatthias** [comment]
From the error:
you're trying to write on a directory you (the user running freqtrade on that system) doesn't have permission to create new files in.

That's not an error we can help you with - as all permission modifications would also require elevated permissions - which we intentionally don't ask for.

commonly, this error happens if the installation happened with the root user (maybe using `sudo`) - but the subsequent execution doesn't use elevated privileges - or if the directory (or git clone) was done with sudo.
