### ISSUE TITLE
Permission denied on plot images

### ISSUE THREAD

**Issue by stefan612** [freqtrade/freqtrade#9957]
Hello, 
i'm successfully installed freqtrade with docker on ubuntu.
There is just  a strange behaviour on generated plots like this:
freqtrade plot-dataframe -s SampleStrat -p BTC/USDT
The file is generated successfully in folder plots.

But trying to open with firefox says:
Permission denied.
By checking the rights (ls-l) on the files i get:
rw-r--r-- 1 100999 100999 3943250 Mär 16 18:01 freqtrade-plot-BTC_USDT-15m.html

Seems like there's a problem with the group and user 100999.
I already tried without any success: sudo usermod -a -G docker myName
Anybody knowing a solution for this?

Many thanks in advance

**Comment by xmatthias** [comment]
well docker will use it's internal user ID's (which can be mapped - but i'd not go there) - not the ones you have.

you can usually get around this by running `sudo chown -R <youruser> user_data/plot` - changing the permissions to your user.

Instead however, i'd recommend to use freqUI to look at charts. It's way more performant and offers an interactive way to configure your bot.

Simply run `freqtrade webserver` (obviously in docker) and expose the port - and enjoy.

**Comment by stefan612** [comment]
Yes, i did chown for accessing the files and it worked.

I'll definitely give freqUI a try :)

Thanks a lot for your help!
