### ISSUE TITLE
Live trading on futures not working

### ISSUE THREAD

**Issue by Xleo-code** [freqtrade/freqtrade#9958]
## Describe your environment

  * Operating system: ____Ubuntu
  * Python Version: ___ 3.10.12
__ (`python -V`)
  * CCXT version: ___4.2.25__ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ___2024.2_ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
Hi everyone i am new to freqtrade and i just created my first strategy is a strategy based on the ichimoku cloud also im using freqai, when i try to backtest the strategy it goes well but when i try to run the bot on dry mode with live data it doesnt work at all even if the conditions get met multiple times. The freqai config are working on binance futures with margin_mode isolated, i have basically personalized the example config_freqai file. I have tried to change the trading mode from futures to spot but it gives me errors like the v1 is not supported and asks me to change my python strategy based on the requirements, i make the changes but it still gives me the error of populate_entry_trend and exit_trend, even if they are located inside my strategy. I would appreciate any kind of help even direction to some documentions or how to prorperly change the trading mode. 
Thank you in advance!!

**Comment by xmatthias** [comment]
your most likely problem is a lookahead bias in the strategy.
That'd mean that your indicators look at data from the future - which are not available in live - and hence no signal will ever happen at the very last candle.

Ichimoku is rather prone to this - as it defaults to a 26 candle offset (showing you candles from 26 candles in the future).

You can usually check for this via [lookahead analysis](https://www.freqtrade.io/en/latest/lookahead-analysis/) - though i'm not entirely sure if it's fully compatible with freqAI (it should be - but i'm not sure it was tested for it).

**Comment by Xleo-code** [comment]
Thank you for your response i did look into it and it could very likely be a problem, i tested using "freqatrade lookahead-analysis" command and the output i got was extremely differente than the one i got from "freqatrade backtesting" is that a normal thing?

**Comment by xmatthias** [comment]
well the 2 serve different purposes. If they were showing the same thing, why would it have to be 2 different commands in the first place? :laughing:

**Comment by Xleo-code** [comment]
hahaha, you are right. 
Thank you for your help!
