### ISSUE TITLE
Fastk value is not used correctly

### ISSUE THREAD

**Issue by QgitM05** [freqtrade/freqtrade#9959]
## Describe your environment

  * Operating system: Windows
  * Python Version: 3.10
  * Freqtrade Version: freqtrade docker-2024.2-dev-4aef5676
  
## Your question

In my strategy one of the input signals for entering trades is the stochastic fast value. 
In my code I have the follow line in the entry trend for long trades:
(dataframe['fastk']<25)

Yet when I plot the dataframe of a backtest, it uses all of my input signals correctly except the fastk value. It simply seems to ignore it. For example it will enter when the fastk value is 50. Is this a known issue, am I doing something wrong, what's going wrong?

Thanks in advance

**Comment by xmatthias** [comment]
Freqtrade only cares about the signal columns (enter_long, enter_short, ...).
How you get to that is completely up to the strategy (author).
So there's no "known issue" here - if fastk is ignored - it's your strategy ignoring that.

Now to some degree, we can assist with that - but not with the information you've shared.
with one partial line of a strategy, all we can say is "this compares fastk < 25".
Maybe you combine it wrongly with other indicators, maybe you're looking at the wrong strategy ...

Feel free to provide sufficient information to actually have a look at this - otherwise will close this tomorrow as this is not something that contains even remotely enough information to try to assist further.

**Comment by QgitM05** [comment]
![Schermafbeelding 2024-03-17 111742](https://github.com/freqtrade/freqtrade/assets/158221885/340dcf5e-7e11-456e-84f5-6b298146dad6)

**Comment by QgitM05** [comment]
Those are the indicators I am using. Now when I set the fastk value to something crazy like <1, it does not enter any trades. So that means it is using the line in my code. Yet when I set the value to 25, it enters trades even when the %k value at that moment is for exmaple 50 or 60 or whatever. The rest of the indicators are used correctly.

**Comment by QgitM05** [comment]
Let me know if this is sufficient info and if you need anything else

**Comment by xmatthias** [comment]
well this tells me that this part is using fastk to check if it's below 25.

if there's other conditions - we don't know. how it's calculated, we don't know.

From what you shared - i can't see anything wrong - though i also can't see what you think is wrong. (maybe you can share a screenshot from freqUI showing that it's > 25 and showing an entry signal ... ?

**Comment by QgitM05** [comment]
Alright I figured something out. 2 things:

1:
Previously I checked the actual fastk value with cryptowatch.net which is not exactly the same as the data presented and used by freqtrade (UI).

2: 
The freqUI shows that indeed the bot bought when the fastk was 39.3 (see image). Yet that's understandable as the bot confirms the signal in a certain candle (the previous candle had fastk 24.8 therefore <25) so it proceeds to buy but the actual entry happens in the following candle.

So in the end it makes sense that the actual value during the entry isn't always <25. And on top of that it's not fair to try to match the freq data with cryptowatch.net



![image](https://github.com/freqtrade/freqtrade/assets/158221885/ed621a5b-51c4-44b7-8ca3-e21451169ac1)

**Comment by xmatthias** [comment]
well as most indicators - there's parameters for the calculation (iirc, in STOCHF's case, it's several).

i don't know what cryptowatch is using for their calculation - neither do i know what the default for ta-lib is. 
Usually, using the default does help - though it's not always guaranteed to yield identical results. 

Freqtrade can't / won't really determine "this is the correct value for your strategy to use" - it's your strategy calling a library with (usually sensible) defaults. 
if that's not what you want (the defaults) - then simply configure them the way you need them to align with your expectations.

if it still doesn't align - it might be a bug in the library you use - but that's usually not freqtrade - but either ta-lib, pandas_ta, or some other technical indicator library - making it hard for us to help you in this.
