### ISSUE TITLE
Typo in the FreqAI settings doc

### ISSUE THREAD

**Issue by PieBru** [freqtrade/freqtrade#9970]
## Describe your environment
(if applicable) 

  * Operating system: Arch Linux
  * Python Version: Python 3.11.8 (`python -V`)
  * CCXT version: ccxt==4.2.67 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2024.3-dev-a0a423033 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement
The example FreqAI config misses the first and last graph parenthesis.
If that example config is copied+pasted into the `.json`, the freqtrade parser aborts raising a `Fatal error`.

*Explain the enhancement you would like*
Please correct the documentation at https://www.freqtrade.io/en/stable/freqai-configuration/#setting-up-the-configuration-file

**Comment by xmatthias** [comment]
I guess it's a question of expectations.

the assumption is that it's copy/pasted into an existing configuration file - where this will be all you need - as you'll have "several" keys prior to this ... and potentially several keys after this.

Now if you assume "this is a full config" - then sure - it's missing the initial and ending parenthesis. 
But in that case, it's also missing about 10 other properties that you'll also want to configure (while most have defaults - you should take ownership of important settings - aside from the fact that not all settings have defaults (e.g. stake_currency) ).
So it's pretty clear that it's not intended to be used as "full" config. We can eventually highlight this with some `// ... ` at the beginning / end - but i do think that having it this way provides more flexibility for the majority of the userbase.


The documentation also mentions this - which also highlights the above point.

> A full example config is available in config_examples/config_freqai.example.json.
