### ISSUE TITLE
Two bots on the same Freq UI, Docker

### ISSUE THREAD

**Issue by ludvigas** [freqtrade/freqtrade#9976]
## Describe your environment

  * Operating system: Windows 11
  * Python Version: 3.11.0
  * Freqtrade Version: 2024.2
  
## Your question

I have found closed issues with similar problem but I cant get it to work. 

I'm having trouble with running two bots in the same FreqUI with Docker.
Before i was able to access the second bot on http://localhost:8081, but not in the same UI. Now i can't even access the second bot on 8081. But the main goal is to have them on the same UI.

Bot1 is running fine, but not bot2. I can see that the docker container for bot2 is running fine even making trades (dry-mode).

I have the two bots in two different folders but within the same freqtrade folder when managing in vscode, so two configs, two docker-compose

Config bot1: 
![image](https://github.com/freqtrade/freqtrade/assets/160531537/d5d755b2-f9ae-43c9-ad67-1f809750782e)

Config bot2:
![image](https://github.com/freqtrade/freqtrade/assets/160531537/9c211e4d-3a41-41b3-a5bb-035a684a8eda)

Docker-compose bot1:
![image](https://github.com/freqtrade/freqtrade/assets/160531537/6ddb464e-05c9-4553-8c10-e694eb67f2b0)

Docker-compose bot2:
![image](https://github.com/freqtrade/freqtrade/assets/160531537/95d0afc2-963a-4cf7-a690-bda1810f8ed4)

Very thankful if someone can point out my issue!

**Comment by xmatthias** [comment]
well you've changed ... one thing too much :laughing: 

if you consider the docker-compose port mapping - it's `<IP>:<hostport>:<containerport>`.
in your case - it's `127.0.0.1:8081:8080` - which means it's exposed on 8081 - but expects something running internally at 8080.

your (2nd) config however uses 8081 as port - which is therefore a disconnect.

For Docker deployments - i usually recommend using the identical port internally (8080) - and use portmappings to have different ports exposed - which in your case - would mean you change `listen_port`  to 8080 -  and it'll work.

Your cors configuration is correct - IF you're accessing your UI via `http://localhost:8080`. If you use `http://127.0.0.1:8080` in your browser, it'll no longer work (CORS is VERY picky in this regard).

**Comment by ludvigas** [comment]
Hahah ahhh thank you so much! 🙌
