### ISSUE TITLE
Protection enahncement idea

### ISSUE THREAD

**Issue by syco** [freqtrade/freqtrade#9977]
Hi,

I'd like a protection like MaxDrawdown, but that also considers all open trades.

The idea is that if I have the maximum open trades set to 10 and I have, let's say 5 trades already open, and they all go into negative, I don't want to open any more trades until those clear or are manually closed.

This would solve a situation I'm having where the strategy is successful for a few hours, than things start to turn. Usually what that means is that it opens some trades that go into negative, not as bad to trigger the stoploss, but sort of stuck in between.
When this happens it usually means market conditions are not suitable for the strategy, and any subsequent trade follows the same patters and they all stay negative. So I want to detect that all the open trades summed together are below a predefined threshold and stop it from opening any more trades.
I hope this makes sense.
I think this should be triggered by a timer, so that it can be executed independently from trades opening/closing or other events.

You think is this an extension of the existing MaxDrawdown, or should it be a new protection?

Any suggestion welcome.
Thanks

**Comment by xmatthias** [comment]
that's not a suitable usecase for protections if you ask me.
Protections trigger when positions close (and only then) - and should not look at open trades, either, asthese will change - but the protection won't reevaluate until the next trade closes, making the whole protection unreliable.

---

You can however pretty easily implement essentially any logic you can think of as part of callbacks (which are also backtestable if you use them right).
If you'd like to prevent entries for some reason - you can for example use the [`confirm_trade_entry()` callback](https://www.freqtrade.io/en/stable/strategy-callbacks/#trade-entry-buy-order-confirmation) - simply returning False from that method will reject valid signals.

What logic you implement there is up to you - and the logic you describe above is clearly something that should belong into a strategy - not into a protection or core freqtrade logic.

**Comment by syco** [comment]
Thanks for the advice, so all I need is the callback function you mentioned and the trade object from here: https://www.freqtrade.io/en/stable/trade-object/
I'll close this and work on my strategy then. Thanks again.
