### ISSUE TITLE
Running the bot with no strategy

### ISSUE THREAD

**Issue by Utfard** [freqtrade/freqtrade#9979]
Hello ! 
Excellent project and I'd like to thank all the contributors so far ! 

I would start the bot for the beginning with no strategy, just to place short or long orders controlled externally via telegram bot.
How should the 'strategy' look like for this use case ? Is it possible to start the bot with no strategy, just to listen for buy/sell  orders ? 

Thank you !

**Comment by stash86** [comment]
https://botacademy.ddns.net/2023/10/18/fsd-basic-template-of-a-strategy/

Make sure to change the roi and stoploss to a very high numbers if you prefer manual exit.

**Comment by Utfard** [comment]
> https://botacademy.ddns.net/2023/10/18/fsd-basic-template-of-a-strategy/
> 
> Make sure to change the roi and stoploss to a very high numbers if you prefer manual exit.

 Many thanks !

**Comment by xmatthias** [comment]
In short - what you require is an empty strategy (not setting any signals, or setting them always to 0) - and roi / stoploss to stay out of the way.

That's however not really how freqtrade is designed to be used ... but nothing prevents that use, either.
