### ISSUE TITLE
Getting RPC strategy messages from websocket

### ISSUE THREAD

**Issue by Axel-CH** [freqtrade/freqtrade#9980]
## Describe your environment

  * Operating system: linux
  * Python Version: Python 3.9.18 (`python -V`)
  * CCXT version: ccxt==4.2.47 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2024.2-dev-6179511a9 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question
I'm trying to subscribe to the RPC datastream on my local bot, I'm able to receive various datastream datas such as 'whitelist' but i'm not able to get any data from 'strategy_msg' stream, even when I validated that I receive strategy messages on telegram.

Here is the code I'm using to subscribe to websocket stream:
```
import asyncio
import websockets
import json

async def listen_for_bot_messages(ws_token):
    print('listen_for_bot_messages')
    uri = f"ws://localhost:8080/api/v1/message/ws?token={ws_token}"  # Adjust if your setup is different
    async with websockets.connect(uri) as websocket:
        msg = {
                "type": "subscribe",
                "data": ["whitelist", "strategy_msg"]
                }

        await websocket.send(json.dumps(msg))

       # Listen for incoming messages
        async for message in websocket:
            data = json.loads(message)
            print("New DATA")
            print(data)

if __name__ == '__main__':
    ws_token = "TOKEN"
    asyncio.get_event_loop().run_until_complete(listen_for_bot_messages(ws_token))
```

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment]
strategy_msg is a message type that's not usually issued, unless your strategy does so - and even then - it depends on the bot having enabled that functionality (through `allow_custom_messages`).

**Comment by Axel-CH** [comment]
From what I'm seeing , the 'allow_custom_messages' is available for "telegram" or "webhook", I did not see that config for "api_server" for RPC

**Comment by xmatthias** [comment]
it's probably not documented - as it's an extreme edgecase - but it's also not something we did ever test for - nor is it something that i would consider worth testing for (or supporting) actively.

it's probably something around `apiserver.allow_custom_messages` - but i didn't test this (just got this from looking at the code).

Feel free to report back if you figure out the correct key - but i suspect the above is the right one.

**Comment by Axel-CH** [comment]
I've just looked at "test_rpc.py" and did not seed a test covering this case, I'm looking at it thank you for the help.

**Comment by xmatthias** [comment]
well it's a specific setting for strategy messages - it should be tested someplace - though most likely only for telegram - as that's the only place it really makes sense (that and webhooks, maybe).

**Comment by Axel-CH** [comment]
It is working now, the correct key is apiserver.allow_custom_messages as you said. Thank you for your help
