### ISSUE TITLE
Getting data from Trade Object

### ISSUE THREAD

**Issue by cnbzmst** [freqtrade/freqtrade#9988]
**Describe your environment:**
- Operating system: Ubuntu 22.04
- Python Version: 3.10.12 
- CCXT version: using docker with latest version of freqtrade (pip freeze | grep ccxt)
- Freqtrade Version: 2024.1 (freqtrade -V or docker compose run --rm freqtrade -V for Freqtrade running in docker)

**My Question:**
Hello,
I have read the topic 'Trade Object' many times.
I searched almost all the past questions on the platform regarding my question  (eg #9479), but I could not find the answer or example implementation. 
My Question: I could not manage to pull the 'close_rate' data from the 'Trade' object using 'Trade.get_trades()'. I can always pull a maximum of a limited data set like below.
eg. [Trade(id=1, pair=BTC/USDT:USDT, amount=0.03000000, is_short=False, leverage=4.0, open_rate=51880.00000000, open_since=closed)]. I tried it in live trade as well.
Is it possible to retrieve 'close_rate' or other data? How can I do it?

**Comment by xmatthias** [comment]
well you shouldn't use `.get_trades()` - but `get_trades_proxy()` - so it'll work in backtesting, too (limited to callbacks).

What you get is a list - and the output you're showing is simply the representation of the trade object - essentially what we select to show (if we show all attributes, it'd be a 10 row element).
Nothing prevents you however to use attributes described in the [documentation](https://www.freqtrade.io/en/stable/trade-object/) for each element (e.g. `trades_list[0].close_rate`).
Now usually, you'll not want to do this for individual elements, but for all elements in the list.

i'd want to point out that this part of the documentation is in the "advanced topics" section - as it assumes some basic understanding of python.
Without this basic understanding, you'll not get very far if you're trying to write callbacks - so i'd strongly recommend to get some basic understanding of python (and how python works) first.

**Comment by cnbzmst** [comment]
Thank you very much xmatthias. Thanks to your guidance, I was able to extract the data I wanted.
