### ISSUE TITLE
Freqai training with synthetic data

### ISSUE THREAD

**Issue by Silur** [freqtrade/freqtrade#9990]
A less-common but existing and useful technique in algotrading is to "inflate" training dataset using AutoEncoders, Transformers etc. This is a double-edge sword as it's really easy to introduce false distributions into the predictor/RL agent but I think it'd make sense to allow this as an opt-in feature with the necessary documentation, especially for RL where it's not catastrophic for the agent to operate on "worst-case" distributions.

The current way to hack this type of functionality is to re-load a chunk from an external dataframe inside `feature_engineering_standard` using `self.config['runmode'].value` as a conditional, but not really elegant.

Instead it'd be great to have it as an optional config variable that points to a feather/csv/json dataset only used at training.

**Comment by robcaulk** [comment]
How do you guarantee it has the same structure as the training data created in feature engineering functions? 

What do you do if you point to a csv that has a different structure than what the user builds in feature engineering (the guaranteed case that will always occur)?

**Comment by Silur** [comment]
Naturally it's up to the user who opts in for the custom dataset to engineer them consistently with the live/dryrun structure. For now what I did is to write out the dataframe at the end of `feature_engineering_standard` into a temp file to observe its structure and make my autoencoder follow the same manually

**Comment by robcaulk** [comment]
If you are adding columns, then I dont see why using `feature_engineering_standard()` is a problem? That is precisely what this function is for, adding any columns from any data source you want. The data source can be from the close price of an informative, from an API, from a file; this is the place to merge this information in.

If you are appending new rows, then it's even easier in this function because you have no merging to do. 

Sorry, I don't see how adding a new function would make this any simpler.

**Comment by Silur** [comment]
it's not about adding columns, it's to completely replace the whole dataframe (rows) with the same column structure.
`feature_engineering_standard` receives only a dataframe "window". The idea here is the replace the whole downloaded exchange feather/json file that gets fed into this function PRIOR.

**Comment by robcaulk** [comment]
Replacing the entire dataframe means you are essentially removing the adaptive retraining nature of FreqAI. In this case, you have no need for any of the FreqAI internal mechanics, so you can safely do all your custom ML inside `populate_indicators()` without any need for FreqAI.

**Comment by Silur** [comment]
I don't see why adaptive retraining cannot continue on a bootstrapped model with synthetic data? As long as the structure is the same it doesn't matter what dataset the model achieved convergence and continues to do so.

**Comment by robcaulk** [comment]
If you are indeed adapting your data/model, then this is why we have the `IFreqaimodel`, you can fit any model(s) you want on any data that you create/load. Perhaps you overlooked the IFreqaimodel?

**Comment by Silur** [comment]
Indeed I did :) having a "pretrain" function at launch in `IFreqaiModel` is the most elegant way of doing this, closing as resolved.
