### ISSUE TITLE
hyperopt doc bad link

### ISSUE THREAD

**Issue by ikt** [freqtrade/freqtrade#9992]
easy one

https://www.freqtrade.io/en/2019.9/hyperopt/

Before we start digging into Hyperopt, we recommend you to take a look at an example hyperopt file located into [user_data/hyperopts/](https://github.com/freqtrade/freqtrade/blob/develop/user_data/hyperopts/sample_hyperopt.py)

404 on the link

**Comment by stash86** [comment]
because that is a very old docs you are trying to read?

https://www.freqtrade.io/ is the correct link
